### ISSUE TITLE
Mob pathing inaccurate.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#100]
All mobs and NMs that move are moving far too much. I have witnessed mobs moving in excess of 40 yalms away from where they stop. Fafnir even walked out his pit and killed an LS member.

**Comment by Wiggo32** [comment]
went to view some mobs... and they seem to be behaving according to retail standards... including fafnir. could you provide some more detail as to what mob(s) are causing a problem and what exactly happened to get the mob(s) to behave inappropriately. if we can reproduce the issue, it will be much easier to fix.

**Comment by Serephim** [comment]
Places I have witnessed these behaviors include Newton Movapolos while I was soloing BST pets. The BST moblins walk around far too much before stopping. Also the Crabs and Diplopod in Kuftal Tunnel. Saw a Diplopod and crab walk all the way from 1-5 to I-7 and aggro me. Fafnir is not supposed to aggro you if you are up top the ledge in dragon's aery but he walked right up the ledge and killed Treble. She is a GM and can confirm this.

**Comment by Wiggo32** [comment]
awesome! thanks for the info, we'll check it out!

**Comment by JigokunoOusama** [comment]
I played retail for years and I don't see anything standard about the goblin behavior.  Their AI, movement speed, pathing, time stationary, attack speed, cast times, and other parameters are off.  They should have standard spots they stop and not immediately 180* when you approach from behind and instant cast spells.  They aggro by sight, not sound, and they have cast times like every other mob.

**Comment by godmode** [comment]
Fafnir will aggro on top of the ledge in retail if he sees you unless you're far enough up. He should not come grab you though he should draw you in.

**Comment by slassen** [comment]
This has been fixed as of a recent patch.

**Comment by Serephim** [comment]
This has not been fixed. It is worse than ever. Mobs are pathing WAY further than even before. They used to just path a very long distance and hit a wall and stop, now they turn around and keep going for another 20-40 yards. Mobs are also spawning in locations where they shouldn't. This is making certain outposts like Valkurm Dunes, EAD, Zitah, Terrigan...ect to name a few... all death traps when you zone in. Worms are also now staying underground for extended periods of time due to the extended range of pathing. At least the mobs are not despawning when they path too far anymore though.
