### ISSUE TITLE
Whitegate MH doesn't prompt to save homepoint after job change

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#1000]
This is ticket #1000, do I win a prize?!?!

**Comment by jmcmorris** [comment]
Congratulations! You win a brand new fixed bug!

**Comment by beauxq** [comment]
This is not completely fixed, only partially.
I get the prompt to set home point, but I say yes and my home point doesn't change.

**Comment by Alirio926** [comment]
Same bug on Al Zahbi
