### ISSUE TITLE
Automaton skillup rate too low

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#1001]
As we all know, the player combat/magic skill up rate is not era. Skillups were super slow back then. Automaton skill up rate is VERY slow and is nowhere near anywhere close being able to be kept up with while leveling. Can we please make automaton skill up rates the same as player skill up rates? I think having to skill up both the player as well as the pet on retail back then was one of the many reasons PUP was in a bad spot. Having a player in your party far behind in skill ups is basically pointless - as is the case with the PUP pet here.

**Comment by jmcmorris** [comment]
Even today on retail PUP is a pain to skill up. The one thing they have done to help alleviate it is add in the [Percolator attachment](https://ffxiclopedia.fandom.com/wiki/Percolator).

**Comment by mpinholster** [comment]
Yeah PUP has always been a PITA to skill up.
One bonus: I got "rich" fighting Even Matches while skilling up.  Pick targets that get you gil.
Even at low levels, pick the Crystal Type that is high selling if possible.

**Comment by mpinholster** [comment]
Also you are 100% about having an underskilled Automaton was bad.
It was a big reason that PUPs were LOLPUP for so long.
That and the poor PUPs who lacked the attachments.

**Comment by Oneirowatts** [comment]
Perhaps you could allow skill up on ranger pup weaponskills.

**Comment by KnowOne134** [comment]
I see no issue with current system as I've done it myself on era
