### ISSUE TITLE
SMN Beastmen should not cast spirits in log, but summon like BST do

### ISSUE THREAD

**Issue by Nyoomy** [EdenServer/community#1002]
Unsure if this is for all SMN pets outside of ToAU or just the ones in Giddeus, but I assume it's all. The following is details for the Yagudo SMNs in Giddeus since that's the ones I'm currently poking. 

Yagudo's Elemental pets in Giddeus are casting all black magic, regardless of elemental type, Air Elementals are casting Stone, Blind, etc.

The elementals are also linking with each other and possibly other Yagudo, this is incorrect and they should only link with their summoner.

They also always spawn in as Wind Elementals, they should be able to spawn as Fire, Wind or Earth.

There is a log message of the Summoner casting Fire Spirit, Earth Spirit, or Air Spirit when they call their pets, which is incorrect as they just spawn their pets like the other pet classes (unlogged summoning magic spell). We got this working in ToAU zones with Troll PUP, Mamool DRG and Lamia SMNs, though they may still link with other pets, as that was a bit harder to test out since the SMN Lamia did not spawn very close to each other.
.

**Comment by Nyoomy** [comment]
Update on this one - The latest patch seems to have fixed the summoning issue, and the Yagudo are now acting correctly, and spawning all 3 appropriate types of elemental.

The pets themselves are linking with each other still however, they should only ever link with the Summoner that spawned them.

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
