### ISSUE TITLE
PUP Level Sync issue

### ISSUE THREAD

**Issue by Nyoomy** [EdenServer/community#1003]
Level Syncing whilst having the pet out dismisses the Automaton if the PUP's level doesn't actually change.

If the level sync is the same level as the PUP, the Automaton should persist through it, it should only deactivate if the PUP's level drops through Sync.

EG - PUP level 12, party syncs to level 12, Automaton should persist.
PUP level 12, party syncs to level 13, Automaton should persist
PUP level 12, party syncs to 11, Automaton should deactivate.

**Comment by Volkaru** [comment]
The puppet is also being despawned when level sync wears off. Once the 30 seconds are up, they go poof.
