### ISSUE TITLE
PUP Job Ability "Deus Ex Automata" isn't active at level 5

### ISSUE THREAD

**Issue by mpinholster** [EdenServer/community#1004]
I just hit level 5 and this job ability isn't active.
I tried logging out.  I will try zoning real quick and see if that makes it work.
Full disclosure: I haven't been level 5 PUP since like 2007?

https://ffxiclopedia.fandom.com/wiki/Deus_Ex_Automata

**Comment by jmcmorris** [comment]
This is an out of era ability added in 2010

**Comment by Volkaru** [comment]
Deus Ex Automata is out of era. But honestly it should be added in. This job is severely hampered by the loss of our automaton. And unlike BST, SMN, or DRG. We can't quickly recall our pet if activate is down. Leaving us up to 15+ minutes without 70% of our damage if something went wrong quickly
