### ISSUE TITLE
PUP shield bash with hammermill attachment does not slow enemy

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#1006]
Using shield bash with the hammermill attachment the puppet should have a chance of slowing the enemy with increased % slow and duration based on how many earth maneuvers are active. https://ffxiclopedia.fandom.com/wiki/Hammermill

**Comment by jmcmorris** [comment]
Tested with a single earth maneuver and it is correctly working. Slow effect is not applied if you do not have any earth maneuvers.

**Comment by FariskaEden** [comment]
Sorry, I should've clarified a bit more. I've been soloing T-IT mobs and usually have 2-3 earth maneuvers up all the time when shield bashing and have found it weird that I've never seen any indication of a slow applying or falling off. Would it be possible to double check with 2 and 3 earth maneuvers up? Thanks for your time.
