### ISSUE TITLE
Colibri not casting spells.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#1008]
When you cast spells on Colibri, they are supposed to stop meleeing and cast it back either at the caster or the person with this highest hate according to this source.

https://ffxiclopedia.fandom.com/wiki/Colibri

I've been casting Flash, Banishes, and enfeebles on them and haven't seen a single one cast a spell.

**Comment by montijin** [comment]
The Colibri in my party reflected back lullaby but it never stuck on anyone, was always resisted.

**Comment by jmcmorris** [comment]
Which Colibri were you fighting? Lesser Colibi do not reflect magic.

**Comment by Aneyus** [comment]
Regular Colibri were reflecting just fine when I fought them last night.

**Comment by gweivyth** [comment]
> Which Colibri were you fighting? Lesser Colibi do not reflect magic.

Yeah it was normal Colibri.  They weren't reflecting Divine spells at all.

**Comment by godmode** [comment]
This seems to be working fine. Tried flash, dia, and banish.
