### ISSUE TITLE
Evoker's Roll not granting the proper amount of refresh

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1011]
With a 5 (lucky), evoker's roll should grant +3 mp a tick without a SMN in party.

As it stands, it's only giving 2. I haven't tested the other numbers.

**Comment by jmcmorris** [comment]
Tested all rolls and it is working properly except busting does give a -1mp/tick. Will work on resolving that.

**Comment by Treble011** [comment]
Still not working correctly live.
