### ISSUE TITLE
F-Keys Randomly Failing 

### ISSUE THREAD

**Issue by xerodok** [EdenServer/community#1012]
During gameplay, the F-keys (F1-F6) will often stop working, particularly with self targeting and while in a party. This will occur at random times and self-heal / start working again after a while. The F1-F6 keys will work properly outside of the client window. This has been reported by other linkshell members as well. It occurs while single & dual boxing.

**Comment by godmode** [comment]
This is likely an issue with Windower or Ashita.

**Comment by Setz0r** [comment]
we can't really troubleshoot client related issues like this.  not heard any more about this either.  could be a bad addon or plugin which is beyond our support scope.
