### ISSUE TITLE
I get "Formula is beyond your current craft level" when desynthing at appropriate level

### ISSUE THREAD

**Issue by Kaijiru** [EdenServer/community#1013]
My leathercrafter is level 14 and I should be able to desyth a Lizard Mantle, however I get a "formula is beyond your current craft level".  I'm using a lightening crystal and a lizard mantle for the desynth

**Comment by Mozzy4Ever** [comment]
![image](https://user-images.githubusercontent.com/11255886/64747021-62a9e480-d4d3-11e9-85f4-302c1474a02c.png)

Looks like the desynth level required is set to 69 for some reason
