### ISSUE TITLE
Evoker's roll not granting the appropriate amount of refresh

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1014]
Lucky (5) should get +3 MP per tick and is only giving +2. I have video footage I can submit through discord (Bass or Treble in game). 

This was previously ticket #1011.

**Comment by Treble011** [comment]
It's not giving the correct value for 11 either.

**Comment by Treble011** [comment]
Just noticed after the reboot that this is working correctly, I assume a patch was pushed?

**Comment by jmcmorris** [comment]
Nope, it has not been merged yet. That is very bizarre that it is now working. Feel free to reopen if you see this or anything similar again.
