### ISSUE TITLE
Airship blackscreens getting on

### ISSUE THREAD

**Issue by pksweets** [EdenServer/community#1016]
Got a black screen boarding the airship from Port Windurst. !go doesn't appear to work, perhaps because I never zoned into the airship route; I'm still technically in Port Windurst. pls halp my exp party is waiting on me ; ;
![leku_2019 02 16_203058](https://user-images.githubusercontent.com/27723566/52908436-b2b91500-322a-11e9-8e10-20f8d73c9302.png)

**Comment by 59blargedy** [comment]
have not heard of this issue in particular since this post, need more details or new occurrences and can reopen
