### ISSUE TITLE
Phomiuna Aqueducts issues.

### ISSUE THREAD

**Issue by NovadragonZero** [EdenServer/community#1019]
**Aegis Schism: Single target 75% Defense Down.**

This move does damage and doesn't go through shadows.

**Dancing Chains: 10' AoE Drown. STR penalty is significant and HP loss is 15/tic.**

Shadows is blocking this and does damage.

**Grim Halo: 10' AoE heavy physical damage. Absorbed by Utsusemi. Used only by Fomors with 2-handed weapons -- generally those of WAR BLM DRK SAM DRG SMN jobs.**

This is working correctly, but the Blm is using a club and is using Grim Halo.

Fomor Ranger are using ranged attacks without animation, meaning it's instant fire.

**NM**

Eba is hanging in a corridor, not the big wide room exclusive to it with Fomors/Bats.

The Fomors that are meant to be in Eba is room are jammed in a void where no one can reach them. Can use /fillmode to see them, but no way to even reach them with a ranged attack, including bats are stuck with them. This makes the Bst/Brd Subligar (Gaudy Harness) impossible to get without Sacrarium. 

Minotaurs are only attacking once and they're Monks, meant to always attack twice.

**Comment by xizeta** [comment]
Not sure when this was fixed but currently the fomors in the Eba room are in the correct position.

**Comment by statuseffect** [comment]
Adding on to this issue, Eba still does not spawn in the correct location. Also Aegis Schism causes ranged attacks to do "Obscene" amounts of damage to VT and IT oil spills when charmed and familiar'd.  The NIN fomors and RNG fomors do not have ranged attack animations.

While trying for a BST subligar, my buddies IT slime had aegis schism applied, then the RNG fomor was doing 300-400 damage ranged attacks to it killing it in 2 attacks.

**Comment by KnowOne134** [comment]
Corrected 12/11/2020 update
