### ISSUE TITLE
COR roll bonuses effected by jobs being set as sub

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1020]
Notably, to receive the bonus refresh on Evoker's roll, someone only has to be /smn and using an avatar, not actually SMN main.

**Comment by Shoruto** [comment]
Unfortunately with all the sources of information available I saw nothing that confirmed or denied this.  Everything just says Optimal Job SMN nothing about whether you get an effect with a /smn in party.

**Comment by KnowOne134** [comment]
tested and confirmed, only main job is taken into account for job bonus
