### ISSUE TITLE
Fishing on boat to Selbina

### ISSUE THREAD

**Issue by Wrunil** [EdenServer/community#1023]
Ran into an issue while trying to fish on the boat bound for Selbina. Anytime I attempt to "/fish" I get the message "This area is currently affected by the Super Kupower: Thrifty Transit!" and it won't cast the line.

**Comment by ElectroNicMan83** [comment]
I have been having the same bug. 
- Happen in around 1/8 boat ride.
- Give the same message as above when pushing the "Fish button" 

Gm told me to update my client and I did to make sure I was updated. The message still came back.

**Comment by Mimic716** [comment]
Can confirm.

**Comment by Deepupuu** [comment]
This happens when theres suppose to be pirates once they fix pirates this will be fixed.

**Comment by Setz0r** [comment]
if this is still an issue it's likely the message offsets need to be adjusted.  will investigate.

**Comment by Setz0r** [comment]
this is not an issue
