### ISSUE TITLE
Lamian Kaman-1 exceptionally low drop rate

### ISSUE THREAD

**Issue by Elysien** [EdenServer/community#1029]
Drop rate for this -1 should be the same as the other beastmen tribes; round 'bout 40%. Currently it is something ridiculously low, which is not correct.

**Comment by jmcmorris** [comment]
Thanks for reporting. Whenever making claims like this you need to provide some evidence. Here https://ffxiclopedia.fandom.com/wiki/Lamia_Toxophilite we see that the droprate has very little data. 

Fortunately these two links give us a better idea of the droprate.
http://ffxidb.com/zones/54/lamia-toxophilite
http://ffxidb.com/zones/79/lamia-toxophilite

**Comment by Elysien** [comment]
Ah, didn't think to check that database site. Thanks for looking into it, it's a valuable item!
