### ISSUE TITLE
Some more NMs tagged wrong.

### ISSUE THREAD

**Issue by Nyoomy** [EdenServer/community#1030]
Another group of NMs that are using the wrong tag. "The Hoo Mjuu the Torrent starts casting Cure"

Hoo Mjuu the Torrent
Eyy Mon the Ironbreaker
Zhuu Buxu the Silent
Juu Duzu the Whirlwind

I have yet to have him spawn for me, but I believe Vuu Puqu the Beguiler will also have this issue, as all other Yagudo NMs did.

**Comment by rujind** [comment]
Are you sure it didn't do this on retail too?

**Comment by Nyoomy** [comment]
Yeah, NMs who have a name rather than a title were referred to by the game as such.

So if the mob's name is it's actual name, like Hoo Mjuu, the game's log would reflect it like:
"Hoo Mjuu the Torrent starts casting Blink."

If the mob's name was a title, but it was still an NM for example a Vanguard Neckchopper from Dynamis, it would be
"The Vanguard Neckchopper readies Battle Dance."

**Comment by rujind** [comment]
Ah, I remember we used to make fun of engrish bugs like this, maybe it was fixed on retail at some point lol.

**Comment by 59blargedy** [comment]
resolved
