### ISSUE TITLE
Jolly Green Not Spawning

### ISSUE THREAD

**Issue by reynierk** [EdenServer/community#1031]
Hello,

I have been camping Pashhow Marshlands, I-7 / I-8, taking down the single Goobue every 5mins and 45s for a couple of hours, over the past few days. I have not seen Jolly Green once, but I know there are Shaman's belt 'cause they have been sold in the AH. 

The [wiki](http://classicffxi.wikia.com/wiki/Jolly_Green)  says it is a 1-2 hour wait between spawns, and I am confident I have covered that time-span, across multiple days. Maybe something fell through the cracks in between patches? I guess this black mage is just looking for peace of mind once this gets reviewed.

Thank you,
Reynierk

**Comment by reynierk** [comment]
=) No Shaman's Belt in the AH since I posted this

**Comment by KnowOne134** [comment]
Tested, It does spawn, closing
