### ISSUE TITLE
Puppetmaster Ranger Model not moving closer in to auto attack occasionally. 

### ISSUE THREAD

**Issue by Oneirowatts** [EdenServer/community#1033]
Sometimes the ranger puppet model is not moving in to auto attack and will stay far away and ranged attack every so often only. This isn't correct as sometimes it moves closer and melee's and sometimes it doesn't. Doesn't seem to have this issue while on Harlequin Body.

**Comment by Nyoomy** [comment]
The actual AI of the Sharpshot Head is to stand still wherever it is deployed and use Ranged Attacks/Spells from there unless it does not have access to them/MP to cast, in which it will run into melee range. It would only melee AND Ranged Attack/Cast if it was deployed in melee range of it's target already.

You could also pair the Sharpshot Frame with the Valoredge or Harlequin Heads, as the both of these heads are supposed to force the Automaton into melee range, and do accurately.

There were new Animators added to retail which forced the Automaton into or out of melee regardless of the Head's AI, but these are iLv Animators and are far out of era.

Though if you mean that getting the Automaton to follow you into Melee range to shoot can be a pain sometimes, see the navmesh issue here: #438

**Comment by rujind** [comment]
If you want your RNG automaton to melee, you either need to make sure it is positioned as close to the mob as possible when using Deploy (I often run to the opposite side of a mob to force this), or use Deploy from 15+ yalms away.

**Comment by jmcmorris** [comment]
Closing this since it is working properly
