### ISSUE TITLE
Gajaad not giving out Walahra Water's.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#1036]
Every 100 coins you trade to him he should give you 1 Walahra Water. I got none. He just kept asking me to sign his petition every single time. 
I did however get my Turban though, so that part works okay.

**Comment by jmcmorris** [comment]
Congrats! How many where you trading him at a time? You have to trade him 100 coins at once to get a water.

**Comment by Serephim** [comment]
Thanks! I traded 1 stack of 99 at a time. I was under the impression every 100 you turned in you got a water. It's kind of silly that it would require you to trade a stack of 99 and then a single. lol

**Comment by jmcmorris** [comment]
Yeah, agreed but that is how it is.
