### ISSUE TITLE
Coffee Macaron is OOE and craftable/useable.

### ISSUE THREAD

**Issue by marlinla** [EdenServer/community#1040]
Spotted someone using coffee macaron. 

https://www.edenxi.com/db/items/5780/coffee_macaron
https://ffxiclopedia.fandom.com/wiki/Coffee_Macaron

First wiki entry 2009. 

[*] Not so much a rule either but if you are aware of any non-era item/NM/recipe/et cetera please report it. And do expect the rewards obtained from it to be removed. I can't find every non-era thing at once but as I find them I will be removing them.

There's a whole class of simiar items you could probably start finding at these link:
https://ffxiclopedia.fandom.com/wiki/Skill_Gain_Rate

**Comment by Treble011** [comment]
Pretty sure Godmode made the decision to leave macarons in when they were brought up months ago. Check with him obviously, but yeah.
