### ISSUE TITLE
Seedspall Lux 

### ISSUE THREAD

**Issue by NovadragonZero** [EdenServer/community#1041]
Dropping from Orcs in Jugner forest. 

https://i.imgur.com/Wo17zx9.jpg

Used in Crystalline Prophecy Mini-Expansion.

 https://ffxiclopedia.fandom.com/wiki/The_Echo_Awakens

**Comment by l33tbmb** [comment]
Also received from Yagudo in Meriphataud Mountains outside of Castle Oztroja
