### ISSUE TITLE
'Three Men and a Closet' quest in Whitegate

### ISSUE THREAD

**Issue by saintfoley** [EdenServer/community#1042]
Three Men and a Closet starts successfully, but I am not able to talk with Ratihb to continue the quest. https://ffxiclopedia.fandom.com/wiki/Three_Men_and_a_Closet

**Comment by godmode** [comment]
Please separate these into different bug reports with the name of the quest postfixed with "not implemented". It is unlikely that 1 developer will tackle all 4 quests at once and it is useful to have one issue per ticket.

**Comment by saintfoley** [comment]
So I'm looking through the implemented quest list on DSP (https://wiki.dspt.info/index.php/Quests#Aht_Urhgan_Quests) and can't find any information about Led Astray or Striking a Balance. Should I omit the bug report about Arts & Crafts + the two with no information seeing as they're not implemented on DSP? I've switched this report to the one I know is implemented and currently not working for me.

**Comment by godmode** [comment]
I would write bug reports for all of them if they are an era quest

**Comment by KnowOne134** [comment]
quest is missing half the logic

**Comment by KnowOne134** [comment]
Fixed 11/23 update
