### ISSUE TITLE
[Not Implemented] 'Striking a Balance' quest in Whitegate

### ISSUE THREAD

**Issue by saintfoley** [EdenServer/community#1045]
The quest _Striking a Balance_, starting at Wazyih - Aht Urhgan Whitegate (F-11) is not implemented. 

However, you can get the starting cutscene. No quest is added and the second NPC required for the quest will not give further cutscenes. Not sure if this should be considered partially implemented or bugged. No information on DSP wiki.

https://ffxiclopedia.fandom.com/wiki/Striking_a_Balance
Wiki contains information dating back to era, 2006.

**Comment by KnowOne134** [comment]
corrected 1/19/2022
