### ISSUE TITLE
Automaton doesn't claim mobs when...

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#1046]
1. Agroing the mob with a spell.
2. Missing a ranged attack.
The mob will remain yellow until the automaton successfully lands a ranged/melee attack.
(not sure about if it misses a melee attack)

**Comment by Nyoomy** [comment]
The missing issue also happens if the Automaton misses a WS. I assume its a special ability problem

**Comment by 59blargedy** [comment]
this should be resolved by claim changes (but spells do not claim)
