### ISSUE TITLE
BLU Spell Head Butt not working on Giga Family

### ISSUE THREAD

**Issue by Spintaru** [EdenServer/community#1048]
So I tested this out, and noticed that Head Butt's stun isn't working on Giga Family mobs. See the following chat logs for reference:

![spintaru_2019 02 18_131739](https://user-images.githubusercontent.com/46164024/52970027-70095100-3380-11e9-943c-c8829e6aa10b.png)
![spintaru_2019 02 18_131851](https://user-images.githubusercontent.com/46164024/52970028-70a1e780-3380-11e9-9563-7d36620c6938.png)

In the one with the Clipper, after Head Butt is cast, connects, and stuns, it then shows the stun wears off. 
In the other, shows a giga, get hit by, but isn't stunned by, or show that it resisted the stun. I have tried multiple times, against 10-20 Giga's, it hits, but doesn't stun.

Someone suggested that the stun is Lighting based, but from what this post shows, it's Physical Based, not lighting or elemental:
https://www.bg-wiki.com/bg/Head_Butt
https://ffxiclopedia.fandom.com/wiki/Head_Butt

I haven't been able to find anywhere that Giga's are supposed to be Immune to Stun Mechanics.
https://ffxiclopedia.fandom.com/wiki/Category:Gigas
https://www.bg-wiki.com/bg/Category:Gigas

Let me know if you need additional information or need some more testing data.

**NOTE**

I tried with INT rings and INT Food too, just in case it was resisting, still no dice

**Comment by Spintaru** [comment]
![spintaru_2019 02 18_201842](https://user-images.githubusercontent.com/46164024/52983749-94821f00-33ba-11e9-9095-d9c661e222d2.png)

Just confirmed you can stun them (this was an EM Giga), so they are Heavily Resisting the Additional Stun Mechanic of Headbutt

**Comment by KnowOne134** [comment]
No issues found besides full magic overhaul in future
