### ISSUE TITLE
COR AF Hat Fight -- Against the Odds, lots of bugs

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1049]
Initially, upon approaching the cutter, you stand inside the ship like the navmesh is off. You have to target the BCNM and wander around until you can reach it to start the fight.

The fight itself there are some issues as well; first off, one of the people in our party never entered the fight, he just black screened and couldn't do anything (as a side note, GMs can't !goto people inside the fight, it just sends them out into the middle of the ocean).

The mobs themselves functioned mostly correctly, the BLU was using all his spells and was immune to silence / dark based sleep, the WAR two houred(he was the only one we got to damage), however their WS were not ignoring shadows like they should. We kept one bound away from the other so we're not sure if they would have skillchained if given the chance.

We targetted the WAR first, and after killing him, the fight black screened and our tank got kicked out but the BLU continued to attack us and I kept having to sleep on BRD until we used the fireflies item to escape. Upon escaping, I got the win cutscene.

Mid cutscene, the entire server crashed and we were in the water after the server came back.

**Comment by Treble011** [comment]
Note: Godmode fixed the final cutscene crash.

**Comment by jmcmorris** [comment]
We also got in a fix to make you not win when only killing a single mob which will hopefully fix several of these issues.

**Comment by Mikokiko** [comment]
I have just done this fight here what happened: 
No one beside me was able to enter the fight, rest blackscreen/D/C
The blue was spamming spell the whole fight, everything was removing shadows
The hume used is 2 hours and WS, but he was not able to hit me (  I was on thf) 
I killed both of them and after the fight I ended up in middle of nowhere, you have to use warp scroll

![miko_2019 02 25_133408](https://user-images.githubusercontent.com/43910014/53360621-02bb6a00-3904-11e9-8c2c-d5db09ce57fc.png)

**Comment by godmode** [comment]
FWIW Jasson fixed it I just listened to him and typed it in ;)

**Comment by Momo027** [comment]
I've just tried to enter the BC today and it would never let me in. Here's the message that it gives:

"Only nearby party members with the same objective will accompany you to The Ashu Talif.
All party members with the appropriate clearance will now be transported to The Ashu Talif. Are you ready?
Connecting to server.
Please wait."

"You cannot enter at this time. Please wait a while before trying again."

At first, the wording sounded like it would only allow players who have this quest flagged or completed to assist in the fight.  So I dropped party and tried to enter solo, but it still kept giving me the above message, no matter how long i waited/zoned/relogged.  I received the long CS when arriving to the cutter, so I'm absolutely certain that I've met all pre-requisites to enter.

**Comment by Serephim** [comment]
Yeah the server for this fight is still down 2 weeks later.
Still cannot enter. :(

**Comment by TheKingOfJeuno** [comment]
https://cdn.discordapp.com/attachments/537046948537171990/564314873295536139/unknown.png

tried to do it last night 4/7/2019 cant get in either

**Comment by panfunk** [comment]
Just did this fight.


> We also got in a fix to make you not win when only killing a single mob which will hopefully fix several of these issues.

This fix doesnt work. After I killed the Hume, Chan was teleported out and got the CS for winning, while Pan was still inside, getting hit by the BLU.
![image](https://user-images.githubusercontent.com/36666121/55860560-cf136700-5b74-11e9-9376-b123ecfd1a3c.png)


> The fight itself there are some issues as well; first off, one of the people in our party never entered the fight, he just black screened and couldn't do anything (as a side note, GMs can't !goto people inside the fight, it just sends them out into the middle of the ocean).

Pan was also blackscreened upon entering, but a simple Escape/Enter on keyboard put Pan onto the ship .

After the fight both chars exited into water, as already mentioned

**Comment by VerrenGunnar** [comment]
![image](https://user-images.githubusercontent.com/49046209/56951534-194d8f80-6b06-11e9-8b56-af0241ccb3f1.png)
Just did the fight, it spit me out at 0,0,0

**Comment by raventn** [comment]
![Alexzi_2019 06 26_211035](https://user-images.githubusercontent.com/35200581/60207732-ddf5e580-9856-11e9-86bc-fedb69e56cb0.png)

Npc still hit me inside BCNM even tho its finished.

**Comment by perkuprightmeow** [comment]
This issue was closed but still having some huge problems with it -- killed the BLU first and one member was teleported out like the fight was over, while the other 2 black screened (one of whomst was actually on the quest), and were killed by the other boss. 

Now just stuck on the boat after rebooting and killing other boss.

**Comment by KnowOne134** [comment]
The fix isn't live yet until Monday's patch

**Comment by perkuprightmeow** [comment]
Ah ok. Well used fireflies, got the CS, and the server didn't crash so overall not too bad :)

**Comment by Volkaru** [comment]
Reopening. Seems people are still getting stuck after the fight ends. #2382

**Comment by KnowOne134** [comment]
needs more info, stuck after killing both? black screen stuck in zone?

**Comment by Qair** [comment]
Just did it today, my alt is stuck under the map after killing both nms while my main who the quest was for was able to warp out fine.

**Comment by Qair** [comment]
Completed the quest again and same situation occurred. As far I can tell, all zone's to the area and out of the area are problematic if you do not have the quest active. My main got stuck in a black screen exiting the area which resulted in me having to restart my client and it spawned me under the ground.

**Comment by dc9111** [comment]
> https://cdn.discordapp.com/attachments/537046948537171990/564314873295536139/unknown.png
> 
> tried to do it last night 4/7/2019 cant get in either
> 
> 
> ![image](https://user-images.githubusercontent.com/47612850/55686897-b65c4480-591b-11e9-8b9c-01fe1f482f2e.png)

Getting this same message when trying to enter on 18/06. Pretty significant bug considering Corsair need to complete this fight in order to break level 70 cap.

**Comment by Mozzy4Ever** [comment]
Heard this is still an issue. Gantofu gave good info on https://github.com/EdenServer/community/issues/2418 as to what happens on enter and exit that might help narrow the issue down

**Comment by KnowOne134** [comment]
Fixed exiting and entering issues. Make a new ticket if any other problems as this 1 is too long and out dated
