### ISSUE TITLE
Mount Zhayolm Ebony Pudding Camp

### ISSUE THREAD

**Issue by Frylokk** [EdenServer/community#1051]
The Ebony Puddings in Mount Zhayolm do not have the pudding trait where they take +25% bonus dmg to magic. This makes this camp pretty worthless in BLM burns. Especially w/ Refresh Sanction not working. We had an xp group out there and T4's were doing the same as if it was a regular mob. 

https://ffxiclopedia.fandom.com/wiki/Ebony_Pudding

**Comment by Frylokk** [comment]
Also, I think we landed 1 silence out of 30 casts, im not sure how the rate was on retail but a RDM with OP gear should be albe to land a Silence i would think

**Comment by jmcmorris** [comment]
I have not heard of Refresh Sanction not working. No one has reported that? Is it just not working at all?

**Comment by Frylokk** [comment]
Yeah Regen or Refresh doesnt work, it takes you 100 points and doesnt show up

**Comment by roclm** [comment]
You do not receive a separate buff icon for Regen/Refresh. I received Sanction w/ Refresh effect on NIN/RDM and had the latent effect apply appropriately.

**Comment by jmcmorris** [comment]
Can you reconfirm this is the case with the Sanction Regen and Refresh. I tested it last night on Eden and Refresh worked perfectly for me. Keep in mind that neither of these go up to 100%. https://ffxiclopedia.fandom.com/wiki/Sanction

**Comment by Frylokk** [comment]
yeah looks like its fine now, me and a few others tested it day 1 of launch and it was working for us

**Comment by Aneyus** [comment]
Seems to me that puddings are indeed taking the bonus magic damage. Nuking 1.3k+ with thunder 4 on them and most mobs only take 1100ish.

**Comment by jmcmorris** [comment]
This seems to be working as intended. Check and the Ebony Pudding do have the 25% bonus magic damage set.
