### ISSUE TITLE
Big bomb pop item not in Friar's Lantern loot pools

### ISSUE THREAD

**Issue by Frylokk** [EdenServer/community#1054]
Only a few of the Friar's Lanterns drop the Smoky Flask.
The ones that do are higher level, and also share some of Big Bomb's attributes, such as growing in size.
Friar's Lanterns that drop Bomb Arms do not drop Smoky Flasks, you also cannot steal Bomb Arms from them.
These are all found near Big Bomb's spawn point:
Two on the bridge near the pop site.
Two in the room where Mythril Mouth Monamaq pops.
Two in (I-10) around the lava pit.

We killed these and they all dropped bomb arms. Its currently impossible to obtain fire bomblet.
They should drop bomb ash and Smoky Flasks

**Comment by godmode** [comment]
He is not a forced pop on Eden.
