### ISSUE TITLE
Mismatched client message doesn't pop up

### ISSUE THREAD

**Issue by mharrington622** [EdenServer/community#1056]
Gweivyth says there's supposed to be a version mismatch message that pops up when logging in.

Installed version: 2.0
Latest version: 2.1
[Screenshots of chat logs without messages](https://imgur.com/a/QIZkx56)
Using Ashita from Eden 2.0 installer

**Comment by godmode** [comment]
This happens if your client is not on the same version but the installer may have different dats and still be on the same install.
