### ISSUE TITLE
Chocobo Digging tables might be wrong.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#1057]
I've been digging in Western Altepa Desert for about an hour now, and I've pulled up 0 Coral Fragments, however I am pulling up Fish Scales, which should not be in the loot table for this area.

According to Somepage, Fish Scales are not available in any chocobo digging loot table.  http://ffxi.somepage.com/chocobo/digging.php#row1

**Comment by marlinla** [comment]
I think the Western Altepa table is in Sauromugue Champaign and Tahrongi Canyon. An audit would probably be in order.

**Comment by gweivyth** [comment]
After 12 more stacks I eventually dug up a fragment.  Apparently we are using FFXIclopedia's charts and not the Somepage ones.

**Comment by Wiggo32** [comment]
There is a complete rework in place of ALL of the chocobo loot tables per zone based on FFXIclopedia's listings. While we understand that FFXIclopedia is not the bible when it comes to FFXI. It was chosen as the baseline for this specific issue. Please refer to FFXIclopedia when attempting to dig items or searching for specific items to dig and if there are any other problems, do not hesitate to open another ticket. If there are any questions as to whether or not a specific item should be included in Eden's drop tables but it is not listed on FFXIclopedia, simply provide a video reference of proof that it exists on retail and we will be happy to add it. Sorry, for the delay in getting this finished. Happy digging!
