### ISSUE TITLE
Giddeus Yagudo NMs may not link with other Yagudos

### ISSUE THREAD

**Issue by Nyoomy** [EdenServer/community#1061]
Confirmed on both Hoo Mjuu and Vuu Puqu earlier, no other Yagudo came to fight me whilst I held him for 5 mins, had a case where 3 were staring right at him fighting me.

Going out on a limb to say this is probably the same for others, did not see any Yagudo join the fight whilst fighting Vuu Puqu the Beguiler each time I fought him, either.

**Comment by Novadragon-Siren** [comment]
This goes the same for Mee Deggi and Quu Domi.
