### ISSUE TITLE
ENM Sheep in.... - Tuchulcha visible

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#1065]
Just did the ENM and saw Tuchulcha after he dug at 25%, saw him w/o nameplate walk to new spawn location.

**Comment by Eme-FFXI** [comment]
Can confirm this behaviour, NM seemed to walked back to original pos and agroed on its way.

**Comment by godmode** [comment]
Has this happened recently?

**Comment by Eme-FFXI** [comment]
yes still happening.

**Comment by piercingdark** [comment]
Also somewhat related, he was stuck in a wall for us last time. Serendipitously found him when he came flying out of the side of the wall/above me while I was trying to run back to party members and avoid aggro of the other antlions.

**Comment by KnowOne134** [comment]
can not reproduce

**Comment by KnowOne134** [comment]
have me re open if issue re occurs

**Comment by falzum** [comment]
Only seems to occur if you cast on him as he's burrowing. Timing is really tight.
