### ISSUE TITLE
Minor bug in BLU unlock quest

### ISSUE THREAD

**Issue by Xaver-Entropia** [EdenServer/community#1066]
Upon completing the quest "An Empty Vessel" to unlock Blue mage, you are supposed to get the Permanent Key Item "Mark of Zahak" (Key Item ID = 771)
You get a message saying you get it, but you don't actually get it.

**Comment by Xaver-Entropia** [comment]
I believe the following script is missing a line:
https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Aydeewa_Subterrane/Zone.lua

Lines 54 and 55
player:unlockJob(dsp.job.BLU)
player:setPos(148,-2,0,130,50)

Should probably add between those two lines

player:addKeyItem(dsp.ki.MARK_OF_ZAHAK);

**Comment by KnowOne134** [comment]
this is fixed now
