### ISSUE TITLE
Accuracy of physical blue magic is extremely low

### ISSUE THREAD

**Issue by Toxophile** [EdenServer/community#1070]
I haven't been parsing, but so far in parties in the dunes my physical spells are missing incredibly often. I was in a party with a Bard even, using accuracy food and as much accuracy gear as possible at level 15-16, and on multiple occasions I literally spent my entire mana bar without landing a single spell.

I haven't had any accuracy issues with physical spells on EM or lower mobs while hunting spells, but against VT-IT in exp parties physical spells are practically useless.

**Comment by 59blargedy** [comment]
resolved with pdif update and first hit bonus acc added
