### ISSUE TITLE
beastmen pet not spawning

### ISSUE THREAD

**Issue by jerock** [EdenServer/community#1071]
Mamool Ja Pikermans aren't summoning again their pets after being killed. Tested in  Bhaflau Thickets map 2

**Comment by jmcmorris** [comment]
They have a 20 minute cooldown iirc

**Comment by jerock** [comment]
um thats weird i remember finishing leveling black mage on these, not sure about the year but before wotg

**Comment by KnowOne134** [comment]
Can reopen issue if proof can be given
