### ISSUE TITLE
Traveling Preformers Not Traveling to Rank 1 Country

### ISSUE THREAD

**Issue by Drognand** [EdenServer/community#1072]
So After some thinking and my first trip to bastok on this character something struck me as odd. From what I recall from retail there was a pack of Traveling Preformers who would only preform at the Conquest Leading town. The Preformers are Currently in Port Bastok. They should in Sandy atm as Sandy is first.
![drognand_2019 02 20_103903](https://user-images.githubusercontent.com/47567545/53103507-c51da200-34fb-11e9-860c-09e9bef3a47d.png)

I searched through the Git Hub and didn't find this in there so figured i should post it.

**Comment by KnowOne134** [comment]
Has been fixed
