### ISSUE TITLE
Ashita Eden Bootloader logging in then closing

### ISSUE THREAD

**Issue by PsychedelicNPC** [EdenServer/community#1076]
Currently, at the ashita bootloader I am being asked to login. Which, I have set up. And the game connects to the server; 'Hairpin fixed'.
However, then it just says "closing".
and closes.

How, do I open the game. I have a problem with Nasomi to.

**Comment by Riphook** [comment]
https://na.nasomi.com/forum/viewtopic.php?t=3654

Someone realized that Nasomi modifies the registry for all installations of this game. As long as you keep your installations seperate, run the bat file tied to the server you want to play on and then login. The bat files are located in forum post.

**Comment by PsychedelicNPC** [comment]
Then how do I play on Eden?

Sent from Yahoo Mail on Android 
 
  On Sun, Feb 24, 2019 at 10:02 PM, Riphook<notifications@github.com> wrote:   
https://na.nasomi.com/forum/viewtopic.php?t=3654

Someone realized that Nasomi modifies the registry for all installations of this game. As long as you keep your installations seperate, run the bat file tied to the server you want to play on and then login. The bat files are located in forum post.

**Comment by Setz0r** [comment]
guessing he finally got in or gave up.  either way, closed.
