### ISSUE TITLE
Bird Blood vendor price inaccurate

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#108]
Before SE nerfed bird blood farming due to RMT, it was priced at ~300-342gil. It was changed on December 8th, 2008 according to Wiki. https://ffxiclopedia.wikia.com/wiki/Bird_Blood?diff=725235&oldid=713471 was the last change to the page prior to December 8th. I realize that 2008/2009 is the era of the server from what I can tell (haven't heard of any set date) but I believe that since the change in price was due to RMT which we don't have on this server, it'd be nice for new players to have something they can farm for gil. The price currently is ~153 which is less than half of what it used to be

**Comment by Mozzy4Ever** [comment]
Price is still 153. Thought that vendor edits didn't require server restart to update, though that may have changed since I last dabbled in that ^^;

**Comment by godmode** [comment]
This fix will be deployed on the next update

**Comment by Mozzy4Ever** [comment]
Ah ty. How do you reopen? Guessing normal users can't?

**Comment by godmode** [comment]
Haha ok thanks for bringing it up. Im planning to work on tickets nearly exclusively this weekend since TH is back in.

**Comment by Mozzy4Ever** [comment]
:S

**Comment by JigokunoOusama** [comment]
Still sells for over 300gil a piece.  The place is always being camped.

**Comment by JigokunoOusama** [comment]
You make upwards of 60k gil in less than an hour with treasure hunter.  I can't imagine what these 75 thfs are making out there.
