### ISSUE TITLE
Quest priority conflict: Koru Moru will not progress The Puppet Master (SMN AF1) if prereqs for Blast from the Past are met

### ISSUE THREAD

**Issue by kassisaf** [EdenServer/community#1081]
Not sure if this is retail behavior, but if the prerequisite quest for Blast From The Past has been completed, Koru Moru will NOT progress SMN AF1 until you accept and complete Blast From The Past

**Comment by marlinla** [comment]
I cannot get Koru-Moru to even flag Star Struck. The prerequisite to Blast From The Past.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
