### ISSUE TITLE
Crystal Eater NM not spawning after trading to dampsoil

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#1083]
Crystal eater in Aydeewa Subterrane currently does not spawn when you trade a crystal to the dampsoil. 
https://ffxiclopedia.fandom.com/wiki/Crystal_Eater

**Comment by jmf9808** [comment]
NM is not implemented yet, will update when it is.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
