### ISSUE TITLE
Lottery spawn NMs after server crash/reset

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#1087]
I've been in Aydeewa Subterrane today trying to spawn a lottery NM and after it spawned the server crashed and upon reset when I logged back in the NM was no longer up. 

Lottery spawn NMs that are timer based also will occasionally respawn after a reset into a different NM if that is applicable. I first noticed this when a Diamond Quadav respawned into Adamantking and I've also heard that Fafnir respawned into Nidhogg after reset.

**Comment by Treble011** [comment]
They reroll whatever is the chance for them being HQ. We've had kings turn back into their NQ versions because of a crash as well. Godmode does know.

**Comment by tectal831** [comment]
It should be noted that if people are found crashing the server to reroll nms, they will be disciplined as appropriate to the severity.
