### ISSUE TITLE
Date Eruca 

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#1088]

**Comment by StriderClerix** [comment]
Ooops!  Well, anyways..

The Date Eruca in Bhaflau Thickets link when they're asleep - I am fairly certain that was not a thing on retail.

**Comment by HammerhandsKupo** [comment]
I know this is closed. But yeah this guy is right. They should not link while they are asleep.

**Comment by Far-The-Killer** [comment]
Are they still linking while asleep?

**Comment by HammerhandsKupo** [comment]
My apologies. I thought it was still up for review and not fixed. Yes it is working correctly now. I just went and tested it and died in the process. Thanks Far-The-Killer and for now on I'll test before bumping...
