### ISSUE TITLE
Rock Racketeer - Sharp Stone Drop

### ISSUE THREAD

**Issue by DrfistMD** [EdenServer/community#1089]
Trying to complete the ques Rock Racketeer and after 7 stacks of Pickaxes, I was unable to mine up the Sharp Stone from the mithril seam.  Per the wiki the Sharp Stone should come from the western mithril seam, but I've gone through stacks of pickaxes on both seams just in case, and have not had the Sharp Stone show up.  Not sure if this is a case of horrible RNG or if the stone isn't set to drop properly.

**Comment by Shoruto** [comment]
Ok what I'm finding is if the stone won't drop and you are constantly breaking pickaxes... Go back to windy, give the 10gil to Mihgo, talk to Varun.  The stone won't drop until you advance the quest.

Just to verify you need the third floor of the Mines at I9.  Its the western mythril seam.  One person got it on the first try.  Hopefully it's not bugged, I would try those steps first. Bring some extra axes just in case it takes a couple.

Once you do those steps, please update this so we know if it worked or if it still needs to be looked at.

**Comment by DrfistMD** [comment]
I had already completed those steps previously, I just went back to Palborough to the same node as before and got my stone first try.  I am 100% certain it's the same node, maybe I had another quest or something at the time that was interfering or something.  But as of right now, I got my sharp stone so whatever was stopping my before is not happening at the moment.

**Comment by Shoruto** [comment]
Awesome
