### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Beniyahou** [EdenServer/community#109]
I created a character then /shutdown to mess with my configs a bit. Since then I time out at the "Downloading data..." screen, FFXI-3001. I notice the "Who's online?" Link lists me as still online, perhaps I logged out improperly?

On a separate note, is there a discord? The link on the main page doesn't work.

**Comment by godmode** [comment]
https://discord.gg/uKgpypT Try restarting your PC and waiting 5 minutes. Then let us know if it doesn't work. https://discord.gg/uKgpypT is the Discord. Thanks for letting me know, I'll update it!

**Comment by gweivyth** [comment]
I had this happen to me on Saturday. I waited about 20 minutes and was able to log in just fine. I think I tried to log both of my characters in too quickly behind one another to cause this to happen.

**Comment by Beniyahou** [comment]
Well I just gave it over an hour and still no good.

**Comment by Mozzy4Ever** [comment]
Is that the only character on the account?

**Comment by Beniyahou** [comment]
I've made/deleted new ones but they couldn't get in either.

**Comment by Beniyahou** [comment]
No luck; 9 October.

**Comment by godmode** [comment]
Try downloading Ashita from Atomos’ website and setting up the server config there. It solved another person’s 3001 error.

**Comment by Aneyus** [comment]
Stumbled upon this post and downloaded and installed a fresh Ashita. Successfully logged into Good! #14

**Comment by Beniyahou** [comment]
No luck with a fresh Ashita and fresh boot config.

**Comment by gweivyth** [comment]
Are you connecting with a proxy?  That could also be an issue.

Quoting Beniyahou <notifications@github.com>:

**Comment by Beniyahou** [comment]
Not connecting with a proxy. I was able to get online this morning for a while but now I'm getting a 3305, if not the 3001.

**Comment by Beniyahou** [comment]
Most consistent fix I've found so far is to remove '--hairpin' from the command line, fail to log in, then put it back and log in, but I've not done it enough times to be very conclusive about that.
