### ISSUE TITLE
[PUP] Soulsoother Head Quest bug

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1090]
Having an issue with the WHM head upgrade quest. Traded a cure V scroll. Which guarantees 2-4 days of wait time. Two if you give him coffee each game day he asks for it, and up to four if you don't. Went two days giving him coffee. On the third day now. I should be receiving my Soulsoother head. Instead he's asking for a third cup of coffee. Not sure if the minus on the day counter is registering or not when I give him the coffee. Will edit to see what he says on day four.

EDIT: Day four. He's asking for a fourth cup of coffee. With the scroll I turned in, even without any coffee the quest should be done now.

Talked with another PUP. They had to trade three coffee before they got their's. I had to trade 4 before I got mine. Seems the quest is giving a random order for people between 2-4. When it should be 4 as a baseline. With -1 for each day you give him coffee for a minimum of 2. (this is all if trading Cure V to him)

Also seems to be giving incorrect timer for Spiritreaver upgrade. With trading stone IV, the same should apply. However I had to wait three days of trading coffee for my head, instead of two.

**Comment by jmcmorris** [comment]
Working as intended

**Comment by jmcmorris** [comment]
Spiritreaver upgrade is wrong though...

**Comment by jmcmorris** [comment]
Scratch that... https://www.bg-wiki.com/bg/Ghatsad
