### ISSUE TITLE
[PUP] Automaton WHM & RDM Enhancing/Healing Magic Priority issue.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1091]
RDM head seems to have some spell priorities in the wrong order. I.e It’ll cast protect on master, then on itself, then shell on master, then on itself. THEN it’ll cast haste > phalanx > stoneskin.
 It shouldn’t be casting protect and shell on itself unless it has hate or the master has all other buffs already.
Order should be:
Prot target's target
Shell target's target
Haste target's target
Phalanx target's target
Stoneskin target's target

Soulsoother will also not cure someone who isn't on their target's hate list. Had a party member resting with 10% HP. Soulsoother refused to cure them until they hit the mob. I've seen it multiple times with other mobs, too.

Seems the issue is the same on Soulsoother head, as well. But he focuses on buffing the master and himself first before even casting protect on the main hate target. It should be main hate target > master > other PT members > Automaton. 

There are other priority issues with the AI as well. Will update post as I remember them.

**Comment by jmcmorris** [comment]
Do you know if Protectra and/or Shellra was ever casted by Automatons in era?

**Comment by Volkaru** [comment]
They were not.

**Comment by KnowOne134** [comment]
These were all ooe and have been removed
