### ISSUE TITLE
[PUP] Activate, Deactivate, Activate hate issue.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1093]
Activate, Deploy, Deactivate is broken for hate reset. Hate should not be on the PUP after the Automaton casts a spell and is deactivated without also auto attacking a mob (If it gets an auto attack in, the master IS put on the threat list) So Casting a spell or using a ranged attack on a mob then deactivating right after, still gives the master hate, when it shouldn't. This makes keeping sharpshot skilled up a pain.

**Comment by jmcmorris** [comment]
Partially fixed for spell casting. Ranged attacks and other skills need to be added to not generate hate for the master.

**Comment by godmode** [comment]
@jmcmorris since this issue is linked it will automatically be closed. Please reopen if it needs to be.
