### ISSUE TITLE
[PUP] [Attachment] Ice maker weird properties.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1095]
Doesn’t seem to function all the time, seems all around buggy. Sometimes has a delayed reaction on removing Ice Maneuvers, sometimes doesn’t remove ice maneuvers but still gets the damage bonus, and sometimes just doesn’t function at all?

**Comment by jmcmorris** [comment]
Will fix eventually but lower priority for now since Ice Maker is not available to players. It becomes available through the Pulling The Plug ENM in Promy Zvahl.

**Comment by Shoruto** [comment]
Additional Ice Maker issue #2355

**Comment by 59blargedy** [comment]
duplicate/resolved in November 29, 2021 update
