### ISSUE TITLE
[PUP] [Attachment] Armor plates

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1096]
There seems to be some weird scaling going on with the -PDT. Should be -40% with both plates on 3x earth maneuvers. Seems to be more against ITs at some levels. But then a T will hit for a lot more than the IT in some cases.

After further testing. It seems a T two levels higher than the puppetmaster is hitting for 40 damage more on average than a VT four levels higher.

This seems to be based on the Automaton's level. Gained a level as a master, without resummoning my automaton. Fought a mob that was VT the previous level, now T. Still took less damage than other mobs at T. Resummoned, found a mob at the same level. Now taking the extra 30-40 damage per hit.

**Comment by jmcmorris** [comment]
The Armor Plate attachments are working correctly. If there is a problem here it would have to be with damage calculates much more fundamental than this.
