### ISSUE TITLE
[PUP] Automaton WS aggro and Ranged attack aggro issue.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1097]
If an Automaton misses a weaponskill, it does not gain any aggro/claim on what it attacks.
This also means Sharpshot Ranged Attacks missing will not aggro, either. (They wouldn't claim until the automaton actually melee hit the monster, but they'd still aggro, even if missed)

**Comment by KnowOne134** [comment]
all new claiming code installed now, open a new issue with details if reoccurs
