### ISSUE TITLE
Loot drops to people in different zone

### ISSUE THREAD

**Issue by Eme-FFXI** [EdenServer/community#1099]
Just observed the issue, where one PT member was in Windy and loot dropped to him(SS1, magic pot shard). I attached the 2nd screenshot, where I have 2 PT members in the zone, one passed, one lotted on loot but its not dropping cause 3rd PT member in different zone is kinda "holding it from dropping".

![eme_2019 02 22_143536](https://user-images.githubusercontent.com/44308523/53246201-4ae24e80-36b0-11e9-8898-3a2cec256253.png)

![vis_2019 02 22_143736](https://user-images.githubusercontent.com/44308523/53246208-559ce380-36b0-11e9-9c04-7c5ed09362d1.png)

**Comment by MGramolini** [comment]
This bug existed on Kupo a long while back.  I remember someone getting a Katayama from Carnero while in the main city.

**Comment by 59blargedy** [comment]
treasure changed to zone pool system a while ago. should no longer see this
