### ISSUE TITLE
Outpost Warp Bastok.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#11]
Looks like the Outpost Warp NPC in Bastok Mines is still working just fine.  The NPC seems to be missing in Metalworks.  When you port back to Bastok from an outpost, it still dumps you in Metalworks.

**Comment by godmode** [comment]
The plan is to move him to Metalworks but leaving this ticket open as a reminder to do that.

**Comment by godmode** [comment]
Moving all OP npcs back to their current retail positions until this can be resolved.
