### ISSUE TITLE
Petrifying Pair BCNM

### ISSUE THREAD

**Issue by CdoubleOkay** [EdenServer/community#1100]
Both aggroed upon entry and one person died instantly. After the death the lizards stopped and did not continue to attack party until added to hate list. Also one person in our party could not attack the lizards. Even called for help to see if that would work and it did not.

**Comment by godmode** [comment]
If you haven’t already please also place a GM ticket and send me a screenshot so I can refund the orb (assuming you were unable to complete the bcnm because of it)

**Comment by 33username** [comment]
I can confirm this also happened to my brother and I.  He lizards instantly attacked upon him entering and used a TP move first thing.  He survived as he was on PLD.  Upon entering, I could not engage either of the lizards.
