### ISSUE TITLE
Assassin's Charge (And possibly Warrior's Charge) doesn't activate when used with Weaponskill.

### ISSUE THREAD

**Issue by Anonyy89** [EdenServer/community#1106]
Tried using "Assassin's Charge" in conjunction with my weaponskill "Shark Bite" and the inflicted damage was around the same as if I used "Shark Bite" without it. 

I repeated this several times to be sure and the following tests all yielded the same results. It appears as though Assassin's Charge (and possibly Warrior's Charge) doesn't have any affect on weaponskills.

**Comment by MGramolini** [comment]
You will always get TP back as if you triple attacked (and usually get up to 200 more damage on thf with assassins charge when i have used it).  I stopped using it with weaponskills unless i am closing a skillchain as I have found that the TP gain part of it is more powerful than just a slight increase in a weaponskill damage.

**Comment by Anonyy89** [comment]
Well what weapon skill are you using that you get an extra 200 damage? I'm using "Shark Bite" and atm the damage is nearly the same as if I didnt even us Assassin's Charge.

Given that "Shark Bite" has such a high damage multiplier I would think having a extra 3 hits would significantly increase your damage when using it. ("Shark Bite" normally only has 2 hits, so you're nearly tripling the amount of damage when you use it with "Assassin's Charge." My damage results aren't showing that at all.)

**Comment by Anonyy89** [comment]
I tried using "Assassin's Charge" with "Dancing Edge" and I DID notice a significant increase in damage. So maybe it's just "Shark Bite" that it isn't -connecting- with.

**Comment by GalkaZajin** [comment]
Assassin's Charge does not appear to be working with weapon skills anymore. No extra tp return or damage.

**Comment by 59blargedy** [comment]
resolved with pdif and followup updates
