### ISSUE TITLE
Dreadbug (Paladin AF Feet Quest)

### ISSUE THREAD

**Issue by NovadragonZero** [EdenServer/community#1107]
Dreadbug is dropping 1 Giant Shellbug when it should be dropping 1-4.

https://ffxiclopedia.fandom.com/wiki/Dreadbug

https://imgur.com/AMLU1VB

https://imgur.com/iZEurR1

https://imgur.com/m3KeL3m

3x we killed him, only dropped 1 Bug. Either it's pretty rare to drop more than 1, or it's only set to drop 1.

**Comment by Shukinen** [comment]
i killed 2x and got 1 each time also

**Comment by 59blargedy** [comment]
resolved in January 4, 2021 patch
