### ISSUE TITLE
COR bust effects -- not working correctly

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1108]
Specifically on evoker's roll (the easiest to see because we get a visible return), bust should give -1 refresh and does nothing right now. Can probably assume that busts across the board aren't giving the negative effect to the corsair (i.e. the XP roll should give the cor negative xp % per kill).

**Comment by Volkaru** [comment]
Evoker's gives -1 refresh to the total of your refresh effect recieved. If you bust it won't start draining your MP. Did you have another source of refresh on to test it?

**Comment by Treble011** [comment]
No. I don't idle in any refresh on COR and I did not have sanction refresh.

**Comment by godmode** [comment]
To clarify what you mean, on retail you should never have MP drain? If you bust its either 0 or your total refresh minus 1? Whatever is higher?

**Comment by jmcmorris** [comment]
That's right GM.
