### ISSUE TITLE
Lumbering Lambert re-pop too frequent

### ISSUE THREAD

**Issue by rka666** [EdenServer/community#1112]
Hey,
Lumbering Lambert NM in Latheine needs to be checked. He pops too often where by wiki it should be:

"
Minimum respawn time is 1 Hour from last Time of Death.
Can take up to 12 hours to spawn.
"

I have spent good few hours here and never seen repops being that long. 
Thank you.
IGN Ram

**Comment by rka666** [comment]
Also, Bloodtear Baldurf pops after server restart. Should be 21-24h after kill. Spawns from normal Battering Rams and not Lumbering Lambert. 
Wiki 2005:
"Lottery spawn off Lumbering Lambert every 21-24 hours."

**Comment by rka666** [comment]
Just a follow up. Killed Lambert today and next pop was after less than 40 min. Saved Screen Shots if needed.

**Comment by rka666** [comment]
Killed Lambert my time 21:18, next killed 21:58.

**Comment by Shoruto** [comment]
I have not found any evidence to show what the proper repop time of Lambert should be. There are players that have mentioned that Lambert has taken as little as 20 minutes to pop from a ram up to 8 hours. However the times mentioned are from dates post era. Unfortunately that is the only time frame that is available right now.

https://ffxiclopedia.fandom.com/wiki/Talk:Lumbering_Lambert

Regarding Bloodtear, in the same link with the players talking one mentioned that Bloodtear did spawn from a ram. Now we can only hope that they were speaking accurately but that is the only time I have seen so far about its spawning from a ram vs Lambert.

**Comment by KnowOne134** [comment]
pop time is unchanged and we cant go back to era to verify, but it is verified in todays standards of 20 minutes. Unlikely was never changed by SE and that it was all on random and lack of updates that led to believe 1 hour repop.
closing issue for Placeholder changes and that repop times is going to be unchanged
verified that Tremor Rams in other zone were already correct
