### ISSUE TITLE
ENM - Sheep in Antlion's clothing

### ISSUE THREAD

**Issue by beitlich** [EdenServer/community#1120]
When entering our ENM, my character (scoots) did not receive battlefield entrance tag and the miasma filter was not consumed. I entered an empty battlefield while the rest of our party entered a regular instance. Leaving the battlefield I was able to start a second instance and other party members were able to enter. We warped out from the second battlefield so as not to abuse, but it seems like maybe only one party member needs the miasma filter.

**Comment by tectal831** [comment]
Do you happen to know what steps you took to cause this, or does this appear to be a one off instance?

**Comment by Beniyahou** [comment]
The key items work more like bcnm orbs - you need only 1 per fight.

**Comment by icariumkupo** [comment]
See #1198

**Comment by godmode** [comment]
This issue should be resolved.

**Comment by Mikokiko** [comment]
https://ffxiclopedia.fandom.com/wiki/Category:ENM?direction=prev&oldid=57787
 Revision as of 15:55, March 27, 2006 by Gahoo

ENM battlefields differ from regular battlefields in the following way :

-An orb is not required to enter an ENM quest battlefield.
- Characters succeeding in an ENM battle will be rewarded with large amounts of experience, as well as unique items.
