### ISSUE TITLE
2-3 Cutscene Broke after BCNM Win - Did not get KI 

### ISSUE THREAD

**Issue by AnnetteBastette** [EdenServer/community#1124]
I completed the Windurst 2-3 Dragon/eye fight in PMines/WShrine on Annette and Bastette.  The CS never loaded and I was stuck in the zone.  Print screen did not help.  I did not get the KI needed to finish the mission, but I got the title.  Screenshots are in tech support in Discord.  Please help me get Rank 3.

**Comment by tectal831** [comment]
Please contact a GM if you haven't already to start the process of attaining your key item
