### ISSUE TITLE
wrong monster location gusgen mines

### ISSUE THREAD

**Issue by charley222** [EdenServer/community#1125]
hello   i try to report these issue to give player the true ffxi experience 

some ghoul pop in the entrance of gusgen mines  and is very wrong  because now low  level can not go there and make some exp    and this also make any sense  to have higher level mob blocking the entrance 
here some video showing the right order first room   4 skeleton next room 4 skeleton after 2  ghoul in the tunnel before  the   step to go down 

https://www.youtube.com/watch?v=IdEeH9OEi18 https://www.youtube.com/watch?v=H4gXMewSyRI https://www.youtube.com/watch?v=LeOGOn97L_8

**Comment by Aneyus** [comment]
I don't think anything is spawning in the wrong place. Somebody probably just zoned a mob and it got stuck on the terrain. I believe the dev team is already discussing possible methods of dealing with mobs getting stuck like that.

**Comment by charley222** [comment]
> I don't think anything is spawning in the wrong place. Somebody probably just zoned a mob and it got 

yes there are   this video will show you    i make this video  about 6 hour later  and the monster are still there  and i kill him higher level   
this video show the ghoul patrol there   https://www.youtube.com/watch?v=o0DO8nvM2IM

   ghoul spawning video in the entrance 1.22 sec   https://www.youtube.com/watch?v=WqkewkqnNl4

**Comment by Aneyus** [comment]
As far as I recall ghouls and skeleton warriors are supposed to spawn in the front there. Can you find any videos from retail showcasing the mobs you think are supposed to be there?

**Comment by Wiggo32** [comment]
Ghouls are actually, supposed to spawn later on in the tunnel near the stairs and only Skeleton warriors are supposed to spawn in the first two rooms. If the ghouls are not stuck, and they are indeed respawning in one of the rooms designated for skeleton warriors, then we'll look into it and get it fixed.

**Comment by charley222** [comment]
this video  show you very well the right location    first room 4 skeleton warriors next  room  4 skeleton warriors  tunnel  2 ghouls one drk one warrior   ,   around the step  2 more ghouls  :)  is like this from 2003  to now :)  i know this because is my best leveing  spot low level :) 
https://www.youtube.com/watch?v=IdEeH9OEi18
i hope this help if not  a bunch of video on youtube will always show you the same location i say  , peace

**Comment by charley222** [comment]
big thank you  to update  the gusgen mines  very appreciated , keep up the good work peace
