### ISSUE TITLE
Making the Grade

### ISSUE THREAD

**Issue by Swankyjr** [EdenServer/community#1127]
So i can not even pick up the quest Making the Grade, last time i checked i was Rank 4 Fame and most of the sites i check say you need to be Rank 3 Fame in Windurst.  I have talked to Fuepepe, and also tried trading the test answers to him too; same thing with  Chomoro-Kyotoro and nothing starts the quest for me.

**Comment by Shoruto** [comment]
Did you do the previous quest Teacher's Pet?  If you did make sure you zone before attempting to start Making the Grade

**Comment by godmode** [comment]
It looks like this is working properly. Please place a GM ticket if you've verified that you've followed all the era steps and are still unable to begin.
