### ISSUE TITLE
Gigantobugard not dropping H.Q. skin

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#113]
Per http://oldschool.dspt.info/moblist.php?l=G&mobid=16879690 (which is base DSP drop rate of Gigantobugard), Gigantobugards in Misereaux Coast don't drop the H.Q. skin. Dunno what DSP guy set it that way, but even per FFXIWiki (which is stupidly what DSP used for drop rates), it's supposed to be ~20%. Per FFXIDB (http://www.ffxidb.com/zones/25/gigantobugard) it should be ~11.7% with no TH.

**Comment by Aneyus** [comment]
This issue was already posted (#75 )

**Comment by Mozzy4Ever** [comment]
But... Mine is better :(
