### ISSUE TITLE
Aura Steal - Dispells Visually Steals buff, But not actually

### ISSUE THREAD

**Issue by CorlaZodren** [EdenServer/community#1131]
I was out camping Sozu Rogberry, Killing the Ninja Tonberries while waiting for the NM to spawn and I was able to Aura Steal their Utsusemi Ni Buff.  It showed that I had 4 shadows like it would be for a nin, even though I was not a nin, but the mob was able to hit me through these 4 shadows.  I also couldn't over ride these shadows by casting the spell on myself.  I had to remove the buff manually and then apply my own before shadows would work on me.

**Comment by Wiggo32** [comment]
1. There is a problem with shadows in core that prevents it from working properly when you have the effect on during zoning, most likely causing this issue as well.

2. You either steal an item OR you debuff/steal debuff. You cannot do both. Steal takes priority, your only chance to debuff is to fail steal or steal from a mob that has no steal item.

**Comment by CorlaZodren** [comment]
Okay, thanks for the clearify

**Comment by Wiggo32** [comment]
NP, keep this open for now though, cause its a reminder that shadows needs to be investigated.

**Comment by KnowOne134** [comment]
Corrected in 5/22/23 update
