### ISSUE TITLE
Bastok Quest: "Rivals"

### ISSUE THREAD

**Issue by mpinholster** [EdenServer/community#1132]
The quest "Rivals" should give Wolf Gorget.  Instead it gave me Wolf Mantle.

To be perfectly honest, I don't think this matters.

But I bug reported it for accuracy purposes.

**Comment by tectal831** [comment]
Please provide evidence for your claim

**Comment by mpinholster** [comment]
It is a non-repeatable quest and I didn't think to get a screenshot.
I will remember next time I bug report something.
