### ISSUE TITLE
[PUP] Repair giving "Cannot attack. Your target is already claimed." message.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1133]
I'm not sure of the cause. But sometimes when I want to repair my Automaton, I get the message in the title when fighting something. And cannot repair him. Doesn't seem to be fixed by deactivating. Fixed by zoning. But when repair is needed that's not exactly an option.

**Comment by Wiggo32** [comment]
this will happen when your pet autamaton is being targeted by a mob's pet. it also happens to bst pets preventing the use of reward or ready commands. it's a core issue and might take some time to figure out, in the meantime, just be aware when fighting mobs that have pets.

**Comment by Volkaru** [comment]
Thanks for the tip, @Wiggo32 . I couldn't figure out what was happening to replicate the issue. I realize last time this happened I was fighting goblin's leeches in Gustav. Never aggro'd the actual goblin, though.
