### ISSUE TITLE
Crystals don't drop in Fei'Yin after recent tally

### ISSUE THREAD

**Issue by Murgleis** [EdenServer/community#1134]
After recent conquest tally in 24.2, crystals do not drop from monsters in Fei'Yin (possibly whole region?). Have signet, tested on multiple EP-T mobs pots golems bats etc. Region is controlled by Windurst.

**Comment by Nimlith** [comment]
Seems to be the same in Elshimo Uplands

**Comment by tectal831** [comment]
I was in party a few days ago in fei'yin and was getting crystals. maybe this has to do with conquest when it first rolls over?

**Comment by roclm** [comment]
I'm currently exping in Valkurm Dunes and getting no crystals from Hill Lizards. I'm pretty certain I've received crystals while exping off these before, but I decided to check the conquest information.

The zone is owned by San d'Oria, but the Beastman have max influence. I know this is a different zone than the current ticket, but I searched before making my own bug report, and I suspect it might be somehow related.
