### ISSUE TITLE
2-1 Windurst Mission 2-1 Lost for Words 

### ISSUE THREAD

**Issue by Crogie** [EdenServer/community#1135]
I am stuck on the part where I need to go to Maze of Shakhrami to examine a "Fossil Rock" to collect a Lapis Coral. I have followed multiple guides notating where the Fossil Rocks will be and have been unable to receive the Lapis Coral after examining each one. In fact, I was doing the mission with a friend and they were able to receive the Lapis Coral no problem. I have tried re-zoning, talking to the NPC again, and kept running around the maze re-examining each Fossil Rock, but have not gotten the quest item.

**Comment by Strumerjohn** [comment]
I was having trouble with this as well; however, I was just unlucky and was picked to have to find the Lapis Coral deeper into the Maze of Sakhrami. Mine wasn't with the ones all chunked up together that i'm sure you checked :(. There are a LOT of fossil rocks in there, but the ones you want to look for are likely around (I-8) of [this map](https://vignette.wikia.nocookie.net/ffxi/images/4/48/MazeofShakhrami2.png/revision/latest?cb=20070726082232). You should see some scorpions in this room, I believe. Hope this helps!

**Comment by Kurtalicious** [comment]
I did this mission last night and followed a guide.  I found that the problem is with the guides not the mission or fossil rocks.  Many of the fossil rocks are not detailed in guides.  Keep looking you'll eventually find a fossil rock that gives it to you.

**Comment by Crogie** [comment]
Thanks everyone! Guess I just kept missing that one Fossil rock >.< I was able to get the Coral after going examining all the rocks.
