### ISSUE TITLE
Sea Puks using Spirits Within

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#1139]
The ones outside the Mamool Ja Staging point use this, they should not have this ability.
![image](https://user-images.githubusercontent.com/46270382/53465234-042b8600-3a1b-11e9-85e5-826c19f6bf73.png)

**Comment by tectal831** [comment]
Are you version matched? If so, can you please provide evidence for the claim you are making

**Comment by FariskaEden** [comment]
Yes, I'm using 2.1 which is the current version I believe. I don't think puks have a hard hitting ability like this. 
![image](https://user-images.githubusercontent.com/46270382/53682682-0107f280-3cc6-11e9-9fa2-d803e6d623ad.png)
