### ISSUE TITLE
VE placeholders are randomly despawning

### ISSUE THREAD

**Issue by gamexover** [EdenServer/community#1141]
VE placeholders are randomly despawning

**Comment by CloudyDesarroi** [comment]
I imagine this may be related to a change in the recent patch:

> - Mobs will now despawn when roaming outside of their spawn range.
[https://www.edenxi.com/forums/viewtopic.php?f=29&p=3960&sid=3766ad85e1acb9e37ffdc12cc9efebf7#p3960](url)

**Comment by klement87** [comment]
It probably happens in any open area where mobs can roam a lot. Can confirm Giant Spiders in Eastern Altepa also despawn randomly.

**Comment by jamiehavok** [comment]
im pretty sure valkurm emperor can now spawn without killing place holders as his ph despawns.

**Comment by godmode** [comment]
This is true until Monday. There is a patch for it.

**Comment by Volkaru** [comment]
Still having this issue after today's patch with some Sabertooth Tigers in Batallia. Donno if it ended up not getting pushed, or it didn't fix all the instances of this happening.

**Comment by Far-The-Killer** [comment]
The fix is still waiting for review which was delayed because of the issues today.

**Comment by godmode** [comment]
This does not effect the NM spawning itself. There is another issue that relates to mobs despawning in general I will be leaving that ticket open.
