### ISSUE TITLE
Mog Wardrobe 1 Awarded Prematurely

### ISSUE THREAD

**Issue by DemiHeart** [EdenServer/community#1143]
Both of my characters (Demi and Darko) were able to utilize Mog Wardrobe 1 before attaining Bastok Rank 3. Both characters were at some point in "The Emissary" (2-3) when I saw the "blue 1" on a piece of equipment indicating that it was using that functionality, perhaps from an equipset I configured? This was the earliest point in my play that I had used it, and while I attained Rank 3 shortly thereafter, I did use the wardrobe functionality thinking I had misremembered when it was awarded. When I last surveyed the forums I read it was not supposed to be available until Rank 3, and so I have made the bug report ticket. 

*Note: these characters were technically created back on KupoXI, though I only got them to like level 7 at the time and didn't play them again until like a month ago. 

Thanks for everything.

**Comment by godmode** [comment]
Is the bug report being that you already had access to it before you earned it?

**Comment by DemiHeart** [comment]
That is correct!

**Comment by Aneyus** [comment]
Characters being created on kupo would be the cause I imagine

**Comment by godmode** [comment]
All characters that had wardrobe 1 and did not attain rank 3 should no longer have wardrobe access.
