### ISSUE TITLE
Lure of the Wildcat (San d'Oria)

### ISSUE THREAD

**Issue by Natchananananan** [EdenServer/community#1144]
Amutiyaal will not complete the quest after I have spoken to all of the NPCs. I tried this quest before i did the Aht Urhgan Mission 2: Immortal Sentries. After completing Immortal Sentries, Amutiyaal still doesnt provide warp and my quest is still active.

**Comment by rujind** [comment]
Did you complete a quest with any of the NPCs involved? Some NPCs may need to be spoken to multiple times if they start quests also.
In the Jeuno version, I talked to the Beastman Seal NPC. Then I traded him Beastman Seals to store. This seemed to erase my progress with him, and I couldn't finish the quest until I spoke to him again.

**Comment by Natchananananan** [comment]
I went ahead to spoke with all the npcs again but still Amutiyaal will not stop responding with flashing the badge.

**Comment by rujind** [comment]
Can you to Quests>Current>Sandoria and list everything there please?

**Comment by Natchananananan** [comment]
![natchanan_2019 03 02_102222](https://user-images.githubusercontent.com/46227433/53683983-81821f80-3cd5-11e9-99d9-ab20648154b1.png)
![natchanan_2019 03 02_102212](https://user-images.githubusercontent.com/46227433/53683984-834be300-3cd5-11e9-8c51-ced3749dc2f8.png)

**Comment by Natchananananan** [comment]
![natchanan_2019 03 02_102934](https://user-images.githubusercontent.com/46227433/53684038-56e49680-3cd6-11e9-9917-6f533fa90f5e.png)

**Comment by rujind** [comment]
Curilla and Femitte are involved in quests on that list so I'm going to assume it's one of those, either The General's Secret or Distant Loyalties interfering with Lure of the Wildcat. You might try talking to those NPCs multiple times, but you're more than likely going to need to complete their quests first (for the time being at least).

**Comment by Natchananananan** [comment]
![natchanan_2019 03 02_201759](https://user-images.githubusercontent.com/46227433/53689658-7d332200-3d28-11e9-8a41-68f0ee046524.png)
![natchanan_2019 03 02_201744](https://user-images.githubusercontent.com/46227433/53689659-80c6a900-3d28-11e9-811b-c48de59070a6.png)
![natchanan_2019 03 02_201558](https://user-images.githubusercontent.com/46227433/53689662-845a3000-3d28-11e9-98cc-bc1f7ee90108.png)

**Comment by Natchananananan** [comment]
Still unable to finish the Wildcat quest.

**Comment by ababyduck** [comment]
It looks like you have Her Majesty's Garden flagged. You'll need to complete that at the very least to get the correct dialogue from Chalvatot.

**Comment by godmode** [comment]
It appears that this quest is working properly. If you are still having issues please place a GM ticket and reference this ticket number.
