### ISSUE TITLE
Mission2.3 dragon fight

### ISSUE THREAD

**Issue by Sangoten** [EdenServer/community#1147]

**Comment by Sangoten** [comment]
mission bug in Cs entrance battlefield, and after GM reboot mission all broke now and no battlefield too …
![trump_2019 02 28_122028](https://user-images.githubusercontent.com/12719406/53563512-88cdef80-3b54-11e9-87ab-a22f21240eda.png)

**Comment by godmode** [comment]
I have no idea what this ticket is about other than mission 2-3. Please add more details to the ticket if there isn’t a ticket already made for the same issue you’re having.
