### ISSUE TITLE
Barrage completely missing

### ISSUE THREAD

**Issue by 33username** [EdenServer/community#1148]
Barrage will occasionally miss completely which NEVER happened in retail.  I've even had it miss on a wild hare in West Ron as a 70thf/35rng when trying out new arrows.  From my experience in leveling RNG to level 53, Barrage will completely miss about 5-10% of the time even with +40 ranged accuracy gear.

**Comment by rujind** [comment]
Pretty sure I remember "barrage miss -_-" being a thing. The wiki even states during era:
Once a shot from Barrage misses, "subsequent" shots do not fire. For example, if a level 50 Ranger were to have their "first" Barrage shot miss, all shots after that will not fire.

**Comment by 33username** [comment]
Wow, I dont remeber that at all.  Guess I'll close this down then.
