### ISSUE TITLE
Blessed Briault skill cap too low

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#1149]
According to every source I've found, except one, this should be a 102 cap synth. The only page that shows it as a 100 cap, which it currently is on Eden, is [BG-wiki](https://www.bg-wiki.com/bg/Blessed_Briault). BG also had it listed as a 102 synth until 2012.

Sources that list it as a 102 cap synth:
https://www.bg-wiki.com/index.php?title=Blessed_Briault&oldid=129547 (Pre-2012)
https://www.ffxiah.com/item/14436/blessed-briault
https://ffxiclopedia.fandom.com/wiki/Blessed_Briault
https://ffxi.gamerescape.com/wiki/Blessed_Briault
http://ffxi.allakhazam.com/db/item.html?fitem=9032
http://ffxi.somepage.com/itemdb/6493

**Comment by tectal831** [comment]
Moved to more info required because i don't know which source you want to use godmode. Please look into this when time allots.

**Comment by Oyaziiiiiii** [comment]
Any word on this? CC100 is nearly impossible until this synth gets fixed :(
