### ISSUE TITLE
Hitting a worm while it's going underground makes it untargetable

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#1150]
And it's still hitting you :(

**Comment by CloudyDesarroi** [comment]
Not a permanent fix by any means, but if this happens to you again you may want to try "/attack <bt>". That's worked for me when fighting worms in Qufim.

**Comment by rpcon** [comment]
This has happened to me about a dozen times, in both KRT and La Thiene. I will try using attack < bt > next time.

**Comment by Mahou81** [comment]
Same here. /attack <bt> doesn't work that well either. Either you can only get in 1 hit and then automatically disengage, or you immediately disengage again without hitting it.

**Comment by godmode** [comment]
Duplicate of #135
