### ISSUE TITLE
Charmed pets despawn immediately after Leave

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#1151]
A charmed pet will despawn immediately after using Leave if the mob is outside it's normal roam radius. It should remain up for a few seconds, at least enough time to re-charm it.

**Comment by McLucas** [comment]
I can confirm this behavior as well. Though I do have some more details about the behavior.

I see two distinct behaviors when I started using Leave on my BST.

1) When Leave is used on a pet OUTSIDE their spawn area, the monster will immediately disappear.  I have seen this behavior with pets becoming uncharmed as well.

2) When Leave is used on a pet INSIDE their spawn area, they will immediately start roaming back to their position.  If the mob is aggressive, it will also immediately aggro the player.  This makes it impossible to use Leave on an aggressive pet and NOT have it aggro you the moment you Leave.

During the COP and TOAU days, there used to be a delay for when the despawning and "roam back to spawn" actions would occur.

**Comment by xizeta** [comment]
This issue also occurs when a charmed pet expires and the pet is out of range of its spawn area. The correct behavior is that the now uncharmed mob should agro the BST and be claimed to them. It's quiet annoying when you have to grab an EM pet from far away only to have it disappear a few mins later.

I will investigate all of these issues, as they are likely related.

**Comment by Setz0r** [comment]
Dont touch any of the BST functionality until we've had a chance to discuss what i've been working on in regards to bst abilities.

**Comment by EliannaEden** [comment]
Setzor my love. Fixing the real issues.
