### ISSUE TITLE
Logging carepenters landing

### ISSUE THREAD

**Issue by eskimoslayer** [EdenServer/community#1152]
A tree in carpenter's landing continues to respawn after I gather it endlessly. Wondering if broken. Never gathered in retail so not sure if this is normal

**Comment by tectal831** [comment]
please do not continue to gather this tree while we look into it. Thank you for reporting

**Comment by Wiggo32** [comment]
Yeah, we recently made a change that allows this to happen. It will happen with ALL logging points in the zone not just that one. It may not be a thing that hangs around but for now, It's a known side effect for a planned change and we aren't really punishing people for it when it happens.

**Comment by godmode** [comment]
This shouldn't be possible anymore. If it still happens please make a comment.
