### ISSUE TITLE
EXP rings timer

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#1153]
During era the cooldown timer for these rings were 16 hours and not 10min.

ref: 
http://ffxi.allakhazam.com/db/item.html?fitem=9636

**Comment by Shoruto** [comment]
Everything I'm finding to be era accurate the Empress Band actually should be a max of 180 min (3 hour) duration, not 16 hours or 10 min.

The picture of 720 min is post era

https://ffxiclopedia.fandom.com/wiki/Empress_Band?oldid=375241
https://www.bg-wiki.com/index.php?title=Empress_Band&oldid=20522
http://ffxi.somepage.com/itemdb/7591

**Comment by Far-The-Killer** [comment]
They mean reuse timer which was 16 hours

**Comment by Shoruto** [comment]
Ah yes, once again my misreading wins the day lol

**Comment by KnowOne134** [comment]
resolved in November 29, 2021 update
