### ISSUE TITLE
Megalobugard Respawn

### ISSUE THREAD

**Issue by AkumoBunni** [EdenServer/community#1155]
After a few days of an LS mate farming NMs in Lufaise Meadows and attempting to spawn Megalobugard, without success, another LS mate started killing Gigantobugards at 5:15 pm est today hoping to spawn the NM. It is now currently 9:15 pm est with no spawn of the NM. Along with this, I have been keeping an eye on the auction house in hopes to catch a ring on AH to buy. There are only 5 listings. 3 of those are a guy selling to himself, the 4th is the guy selling to another name, and the 5th is an unrelated name selling to another person. Between the lack of the NM spawning and lack of AH record, I was wondering if there was a problem with the NM. I sent in a GM ticket today and [GM] Xyn got in contact me and told me they believed the NM was working properly but would check in with other GMs. After the initial conversation with the GM, He contacted me again and asked me to submit a bug report, as they would like to look into this further.

**Comment by AkumoBunni** [comment]
After 6 hours, I have confirmed the NM does spawn. I am unsure how to close this, if I am able.
![mega](https://user-images.githubusercontent.com/47017672/53615986-361d2380-3ba6-11e9-903c-f733f02177d2.PNG)

**Comment by Oyaziiiiiii** [comment]
Ever since the last merge, this thing has been an absolute nightmare to pop. I've spent a good 5 hours there clearing everything and have had no luck. LS mates of mine have seen it pop but also report that it takes hours of PH killing. Before the last DSP merge it would pop relatively fast when the window was open, so I think something may have changed with its pop chance.

**Comment by AkumoBunni** [comment]
I'm only 60 PLD, so I have time. But yea, the 5-6+ hours for a spawn at killing all the mobs the whole time is a bit excessive when I know I've done this before and hardly ever saw it go that long, if ever. I know it won't be top priority, since it DOES spawn, but I hope at some point it can be figured out.

**Comment by Umarusuzy** [comment]
I've had to kill all the mobs in the vicinity for hours to get this NM to pop.  I'm pretty sure I went past 5-6 hrs for one of the kills as well.  This used to pop much more reasonably when it was first available.  I wouldn't be surprised if there's something iffy going on here.

**Comment by icariumkupo** [comment]
On stock dsp there is only 1 place holder mob FYI

**Comment by AkumoBunni** [comment]
Even with 1 PH, killing all 10-11(ish) mobs in the area for 5-6+ hours seems excessive. Even if you kill just the PH, that won't stop it from being that long of a spawn. Maybe save yourself a few minutes..

**Comment by jmf9808** [comment]
Looked at Megalobugard code/did some testing and everything seemed fine. Could have just been that good ol' terrible rng luck.

**Comment by AkumoBunni** [comment]
Hard to believe all of us had terrible rng over it, and the same time frame of 5-6 hours. But you're the one who knows the code and such so I'll take your word for it. lol Thanks.

**Comment by panfunk** [comment]
This is a general lottery NM issue imo, especially NMs with a single PH and the more often than not 5% pop chance.
You can get lucky and get it right away or you waste hours and hours and won't see it
