### ISSUE TITLE
Barrage turbine unable to buy

### ISSUE THREAD

**Issue by dakumauler** [EdenServer/community#1156]
i have 5323 IS and it cost 5000 IS will not let me buy it hmmm...

**Comment by panfunk** [comment]
This attachment was added in 2011, thus not era and should not be purchasable.
Similar to Warp Ring at conquest NPCs, which are listed but not purchasable.

**Comment by tectal831** [comment]
the attachment is out of era unfortunately

**Comment by beauxq** [comment]
Like the linked issue, it is an issue because it needs a dat mod.

**Comment by KnowOne134** [comment]
Duplicate issue. Closing
