### ISSUE TITLE
Moghancement: Experience

### ISSUE THREAD

**Issue by Deepupuu** [EdenServer/community#1158]
0 experience points are lost when moghancement: experience is active.

**Comment by tectal831** [comment]
Can you please elaborate a bit more? 0 experience points should be lost when you die but dont? 0 experience points are currently lost and this is not accurate?

**Comment by Deepupuu** [comment]
yes when you die 0 experience points are lost i dont think thats how its suppose to work but idk for sure i just assume its suppose to reduce experience points lost not get rid of losing experience points all together when you die

**Comment by Deepupuu** [comment]
I lost xp today when I died with moghancement experience active. Today I was able to trade the moogle shrimp lure and selbina butter maybe that changed something.

**Comment by KnowOne134** [comment]
what level were you?

**Comment by KnowOne134** [comment]
tested mog enhancement off and on job level 5 20 50 75 99. all works correctly. reopen if issue occurs again
