### ISSUE TITLE
Mog Wardrobe 2 not functional at rank 6 Bastok

### ISSUE THREAD

**Issue by Umarusuzy** [EdenServer/community#1160]
Ticket #996 can be referenced for the same issue.  I'm currently rank 6 Bastok.  Wardrobe 2 isn't functional on my character Umaruchan.

**Comment by godmode** [comment]
Duplicate of #996

**Comment by BuffaloOnEden** [comment]
Mine doesn't work either. Character name is Buffalo.

**Comment by godmode** [comment]
This ticket is closed please write it on the original ticket that was linked to. #996
