### ISSUE TITLE
Lost 100 Piece to R0 in Dynamis WIndrust

### ISSUE THREAD

**Issue by SaberSuper** [EdenServer/community#1162]
Tantalas LS lost a single 100 windy shell piece on 2/22/2019.  I sent a message to GodMode but i'm not sure if i needed to submit a report for this.  This R0 occurred as we were leaving Dynamis, only a handful of people were left in the zone.  You can ask anyone from our linkshell for confirmation. Only really care about the 100 piece.  If anyone could reimburse our loss to Supersaber, it would be greatly appreciated.  Thank You.

![supercrash_2019 02 22_231401](https://user-images.githubusercontent.com/44216595/53677859-e19ca580-3c84-11e9-8178-63cb41e33b2c.png)

**Comment by jmf9808** [comment]
Please put in a gm call about this. Bug reports are only for server bugs.
