### ISSUE TITLE
Quest "A_Reputation_in_Ruins" not starting/implemented

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#1163]
https://ffxiclopedia.fandom.com/wiki/A_Reputation_in_Ruins

Required to fully acces Pso'xja Tower #2

**Comment by bkesecker** [comment]
Working this one now.  NPC dialog almost done and fiddled with spawning the Gargoyles and opening/closing doors.  Should be too long to complete.

**Comment by bkesecker** [comment]
Finishing up dialog with the NPC, and then tuning the Gargoyle toughness.  Almost done.  One strange issue I haven't figured out is that the client seems to periodically open the closed doors.  So I'm sending the close door call repeatedly during the fight.  If no errant packets are coming from DSP making this happen, I don't have any other way to fix that.  However, I added a feature to the ???'s such that they can be checked to open the closed door if for some reason they aren't opening.
