### ISSUE TITLE
Stuck in place after chocobo dismount.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#1165]
Was chocobo digging this evening in Altepa.  I eventually ran out of time on my bird, but I kept spamming dig in hopes that I could get my last green in before I got dismounted.  After I was dismounted, I was stuck in place in the same way that people get stuck in place after requesting synthesis recipies from NPCs at crafting guilds.  

Eventually I was attacked by an Antica and had to warp because I couldn't move to fight it (and it was a BLM, so it wouldn't come to me, it just kept casting and I was on DRG so I couldn't silence...) 

First time I've experienced this particular bug, and I've been digging a lot since it came out.  Might be a corner-case, not sure.

**Comment by Wiggo32** [comment]
this happens when you try to dismount during a "dig" command and is an issue that will require some more investigation into the core. for now, i would pay attention to your ride time and stop using macros when you are about to be kicked off the bird.

**Comment by Setz0r** [comment]
This has been fixed during bugapalooza
related ticket: https://github.com/EdenServer/community/issues/732
