### ISSUE TITLE
Cannot Desynth Gavial Cuisses

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#1169]
https://ffxiclopedia.fandom.com/wiki/Gavial_Cuisses

Does not work.

**Comment by Shoruto** [comment]
Do you have evidence of during era that this de synth is possible?  If you change the date to during era, it doesn't show any de synth recipe for this item.  The first date that shows a de synth recipe is January 9th, 2010

During Era
https://ffxiclopedia.fandom.com/wiki/Gavial_Cuisses?oldid=313624
https://www.bg-wiki.com/index.php?title=Gavial_Cuisses&oldid=16083
https://ffxi.gamerescape.com/w/index.php?title=Gavial_Cuisses&oldid=812839

Post Era
https://ffxiclopedia.fandom.com/wiki/Gavial_Cuisses?oldid=1060670
https://ffxi.gamerescape.com/w/index.php?title=Gavial_Cuisses&oldid=812847

**Comment by mlandrum22** [comment]
It's probably because no one tried it. 

https://ffxiclopedia.fandom.com/wiki/Gavial_Mask?oldid=87858

A cheaper, but similar synth had desynth info in 2006.
