### ISSUE TITLE
Paralyze not functioning properly on players.

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#117]
Paralyze is currently not consuming items when it procs upon item usage, and not consuming JA cooldowns on proc either.

As much as I hate to report this one because I HATE being paralyzed randomly when I'm eating food or something, it's making paralyze far less scary than it should be.

**Comment by gweivyth** [comment]
Ugh please don't add this to items. Paralyzing abilities is fine but paralyzing items is just awful.
