### ISSUE TITLE
Lost RR when entering  Ilrusi Atoll Staging Point and died

### ISSUE THREAD

**Issue by wheeeels** [EdenServer/community#1170]
Silvercap aggroed an imp close to the  Ilrusi Atoll Staging Point. While running away, he was able to reach the gate and click to enter. The menu showed and as he clicked to enter the gate he died to a spell cast by the imp. 

The image in attachment proves he cast the re raise before the could have expired.
![silvercap_2019 03 02_234843](https://user-images.githubusercontent.com/11963325/53689239-4de0dd00-3d49-11e9-9a23-020fd33bf4a0.png)

**Comment by KnowOne134** [comment]
Unable to reproduce

**Comment by KnowOne134** [comment]
This is actually you dying while in the cutscene to use the runic portal to go to whitegate. You dies before the cs ended in that zone, then the cs moved you to whitegate and zoning removes your rr effect if dead. There are 2 bugs in this possibly.
1. The gates to staging points are supose to clear all hate after entering. 
2. Does you dying before a cs ends voids the cs?
