### ISSUE TITLE
I think drop table for Goblin Reaper in Beaudicine Glacier are incorrect.

### ISSUE THREAD

**Issue by mpinholster** [EdenServer/community#1172]
I think drop table for Goblin Reaper in Beaudicine Glacier are incorrect.

I've killed a ton of these at the Nue camp.

Have gotten a ton of Stun Scrolls, but 0 Absorb Scrolls.

https://ffxiclopedia.fandom.com/wiki/Goblin_Reaper

Just curious if this could be looked into.

**Comment by mpinholster** [comment]
Nevermind, the other stuff is dropping now. Just seemed weird to get 15+ Stun Scrolls and not a single Absorb.
Seems like the Absorb Scrolls are just very rare.
I have gotten Absorb INT and AGI thus far.

**Comment by Far-The-Killer** [comment]
Checked the DB and absorb scrolls do drop from this mob.
