### ISSUE TITLE
"7 deadly sins" Notorious monsters in Eldieme Necropolis do not seem to be implemented

### ISSUE THREAD

**Issue by jamiehavok** [EdenServer/community#1174]
7 Skeleton NMS in Eldieme Necropolis that all spawn at once when you light 7 candles with a flint stone within 5 minutes of each other. 

https://ffxiclopedia.fandom.com/wiki/Skull_of_Gluttony
https://ffxiclopedia.fandom.com/wiki/Skull_of_Envy
https://ffxiclopedia.fandom.com/wiki/Skull_of_Greed
https://ffxiclopedia.fandom.com/wiki/Skull_of_Lust
https://ffxiclopedia.fandom.com/wiki/Skull_of_Pride
https://ffxiclopedia.fandom.com/wiki/Skull_of_Sloth

There isn't much information on each of the nms specifically,  but it seems each nm is soloable by a lvl 75 character, you need 7 characters to pop them as you cant get to all candles in 5 minutes but each person should be able to solo their nm.  
The drop rates of the items are quite poor but the lighting of the candles only has a 1 hour cooldown. 

https://ffxiclopedia.fandom.com/wiki/Talk:Skull_of_Gluttony#Testimonials
http://ffxi.allakhazam.com/db/bestiary.html?fmob=553
http://ffxi.allakhazam.com/db/bestiary.html?fmob=1509

**Comment by EliannaEden** [comment]
I'm going to add to this. 

We tried today this still does not work, even though it is listed on the official NM level guide here - https://classicffxi.fandom.com/wiki/Notorious_Monsters%3A_Level_Guide#Levels_70_.E2.80.93_79

When trading the flint stones to the Tallow Candle, it does not light or give you the correct message stating the number of candles remaining to be lit. If you click on the candles without trading a flintstone, they light but do not pop the NM's or the display the cooresponding message. 

We attempted this 3 times with flintstones and 3 times without flintstones, using the in game timer as a reference for when to trade.

**Comment by godmode** [comment]
The official NM level guide is not official. Although it is a staff member that compiled it it is still player led. Wiki stuff should be treated as that. Follow the bug reports. They should always be updated. As far Aiko’s project I believe he wrote all that will be implemented at some point because they are era.

**Comment by Setz0r** [comment]
The mobs aren't even loaded, nor are they properly setup in the database.  I have put in a request for the process to be captured on retail.  Apparently all 7 need to be lit within a 5 minute time limit by trading a flint.  The Candles themselves aren't even setup in the scripts.  So this seems to be a "from scratch" situation.

**Comment by jamiehavok** [comment]
Has this been implemented now then?
