### ISSUE TITLE
KSNM chests should also drop gil as a reward

### ISSUE THREAD

**Issue by Qair** [EdenServer/community#1176]
Some video proof:
https://youtu.be/57FrnwqzNA0?t=159
12k - 2007 in a duo

https://www.youtube.com/watch?v=VD8LpS2L2bI

24k - 2007 on a solo run

https://youtu.be/FBcN3HW0oeo?t=334

4K - 2007 in a party of 6

**Comment by rujind** [comment]
If anyone does a KSNM, can anyone check their gil before and after to see if the gil is being received but just not reported in the log?

**Comment by Qair** [comment]
you don't get any, my gil amount didn't change in about 12 runs yesteday.

**Comment by Qair** [comment]
This still hasn't been updated. I did a ksnm30 two days ago and gil still isn't being dropped.

**Comment by Qair** [comment]
KSNM 30 is still not dropping the gil reward. This needs to be reopened
