### ISSUE TITLE
LB3 ??? didn't give Yag Crest

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#1177]
(character Azmanz)

I was doing LB3, I already have the Quad/Orc crest so I know I have the mission. I clicked on the ??? in Castle O and it gave me a "nothing out of the ordinary" tag.

Please don't make me run through Castle O again lol

**Comment by godmode** [comment]
Do you have a screenshot of it?

**Comment by mlandrum22** [comment]
I'm a dummy. Must have missed the dialogue and saw that message on my 2nd click. In my mini-rage quit i didn't check my Key Items. It was there. I'm so sorry to bother you
