### ISSUE TITLE
Holy Bolts Additional Damage Bug

### ISSUE THREAD

**Issue by JDFlashffxi** [EdenServer/community#1178]
When using Holy Bolts, the Addition damage would sometimes proc for very large numbers but not do any addition damage i could tell of, seemed to only do this on creatures weak to light damage, also the additional damage when proced normally was only doing 3-9 additional damage which is not correct, i remember these doing upwards to 40 additional damage per shot.
![max damage](https://user-images.githubusercontent.com/48188921/53702359-0bb0ad80-3dd4-11e9-9d31-b20d8efa163b.png)

**Comment by rujind** [comment]
TBH, Addition Effect damage in general is broken. Sirocco Kukri wind damage is very random (and often seems pretty low) but on retail I feel like it was a consistent 13-15 damage, somewhere around there?

**Comment by Setz0r** [comment]
this has been a DSP issue since the dawn of time.  i plan to investigate this in the future.

**Comment by godmode** [comment]
Duplicate of #1301
