### ISSUE TITLE
Lottery NM despawn

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#1181]
Spawned Ullikumi earlier today, and decided to give it a shot as DRG/BLU while waiting for ppl to kill it.
I obviously wiped and went afk. When ppl arrived Ullikummi was nowhere to be found. 
I suspect he despawned due to that 'mobs too far from spawn despawn'-thing.

https://github.com/EdenServer/community/issues/1141#issue-414956292

**Comment by Far-The-Killer** [comment]
Yep this is a known issue, part of the fix that is still under review.

**Comment by godmode** [comment]
Hmm, NMs shouldn’t be a part of despawning. I imagine he’s stuck somewhere but we will have to look into it.

**Comment by Far-The-Killer** [comment]
Godmode is correct, lotto NMs should walk back (tested on VE). Also that NM is not a lotto, but I'll test later.

**Comment by godmode** [comment]
Ulli should be a lotto with Eden’s current setting unless it is not coded as intended

**Comment by tectal831** [comment]
Ulli is a lotto

**Comment by panfunk** [comment]
Happened today again, Ulli was poped, group wiped, and Ulli was despawned when i arrived to help.

Maybe he has the 'pop-item NM despawn after 15-min'- behaviour since he's a poped NM on current retail?

**Comment by icariumkupo** [comment]
Has this exact scenario play out at Big Bomb. Check fix for #1268

**Comment by panfunk** [comment]
I guess you mean https://github.com/EdenServer/community/issues/1269 Ica :D
