### ISSUE TITLE
Weapon Bash doesn't deal damage

### ISSUE THREAD

**Issue by roclm** [EdenServer/community#1182]
The DRK job ability Weapon Bash should deal consistent low blunt damage, but it currently isn't dealing any on Eden.
https://i.imgur.com/QRuf1rV.png
The damage formula should be: FLOOR(((LV+11)/4) + Equipment Bonus)
The important "Stun" part of the job ability is working, though :P 

References:
https://www.bg-wiki.com/bg/Weapon_Bash
https://www.bluegartr.com/threads/108197-Random-Facts-Thread-Abilities?p=5487202&viewfull=1#post5487202
https://ffxiclopedia.fandom.com/wiki/Weapon_Bash

**Comment by xizeta** [comment]
Damage formula is correct but the message for damage dealt is missing.
