### ISSUE TITLE
Jungle Boogymen Avatar up at start of the bcnm

### ISSUE THREAD

**Issue by Destroyerz83** [EdenServer/community#1186]
Before starting the bcnm the avatar was up and did astral flow on pull.

It was related to the fact that previous bcnm we killed SMN too quick so it didnt astral flow.

Also, I wonder if the smn astral flow do too much damage if you compare to retail.

We found a way to do it having 1 person die, I dont know if its the way of doing it.

**Comment by E5una** [comment]
This problem still exists, we had the exact same issues. We stun locked the SMN so it couldn't 2 hour, and then the next run the avatar already had carbuncle out and opened up with astral flow which caused us to wipe (it took off the BLU sleeper's shadows and let the other tonberries interrupt the sleep, as well as half HPing everyone).

Important note: We prevented the SMN from 2Houring again in a subsequent run about an hour later and this problem DID NOT reoccur, so it seems intermittent.

Just a random thought... it was a carbuncle, and maybe that is relevant. That matches the screenshot that I put into discord the other day of me doing Treasures and Tribulations and there being a random "Yagudo's Avatar" Carbuncle that was standing there the whole time as well (theoretically from a previous persons BCNM).

**Comment by 59blargedy** [comment]
i believe this issue has been fully resolved, but please comment if this needs to be reopened
