### ISSUE TITLE
You cannot attack that target

### ISSUE THREAD

**Issue by BuffaloOnEden** [EdenServer/community#1187]
I don't know if this is a bug or it's the claim shield I've heard rumors about, but I tried to claim Sozu @20:51:06 CST and I received the following message:

"You cannot attack that target"

Six seconds later, you can see in the attached picture, I try again, and it is claimed by another player. I appreciate you making this server available to everyone, and I enjoy playing here, but instituting a claim shield is not sustainable as more people become higher level and LS alliances become irrelevant.
![untitled2](https://user-images.githubusercontent.com/48140912/53778865-e4390e00-3ec3-11e9-96c4-0e50c859a44c.png)

**Comment by rujind** [comment]
Someone will likely ask you to take any discussion regarding claim shield to the forums. 

Yes, what you experienced was claim shield. For a random unspecified amount of time, certain NMs have the shield after spawning. If you try to claim the NM while the shield is active, you'll get locked out, for what is currently a static amount of time that no one knows except the devs. Your goal is to try and not claim the NM until the shield is gone - basically, you have to guess. If you hit the claim shield you can pretty much say goodbye to the NM.

You cannot attack that target. = claim shield
Cannot attack. Target is already claimed. = trying to claim after claim shield is down.
