### ISSUE TITLE
Kirin 2hr twice

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#1190]
Kirin hit is with 2 astral flows today back to back and wiped us at kirin today. can provide screen shots upon request.

**Comment by godmode** [comment]
Please add more details and reopen the ticket.

**Comment by tectal831** [comment]
What more details do you want? He astral flowed, we got hit by it, and then he astral flowed again, which he shouldnt do, causing a wipe. I was wearing a green t shirt and drinking a tea.

**Comment by Treble011** [comment]
This should not be closed. It's still happening.
