### ISSUE TITLE
BST as a subjob 

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#1192]
Currently the level of your beastmaster does not effect the level of monsters you can charm when beastmaster is used as a subjob.  This is not correct as the max level of your bst is supposed to dictate the level you can charm up to. 

reference: https://genomeffxi.livejournal.com/11846.html

**Comment by icariumkupo** [comment]
Can you be more specific? Pretty sure this is working just fine for me. I have a 75 bst and sub it on other 75 jobs all the time. I'm able to charm anything and they last same duration as my 75 bst as far as I can tell.

**Comment by montijin** [comment]
That would be correct behavior of charm since your Beastmaster is already 75. Currently on Eden you don't need to have BST fully leveled though, your BST can be below 37 even as a sub and you can charm level 70-74 monsters. 

i.e a level 75RDM/25BST charming flamingos in sky.

**Comment by icariumkupo** [comment]
Ah that indeed is def an issue then. Anyone with BST unlocked could charm like a 75 BST then haha. Not good.

**Comment by Strumerjohn** [comment]
There is still some scaling apparent I've noticed so you don't have to worry about a 75XXX/1BST going out to charm level 75 stuff (it's literally impossible even with over 100CHR); however, once you're within like a third of your target level with CHR you can charm (i.e. the /25BST example above). Charm also seems to work this way on Nasomi so it could just be DSP?

**Comment by godmode** [comment]
This doesn't look like it is the case. Please add some proof of testing in here if you believe this to be an issue. Such as something like failing to charm level 70 mobs as a 75WAR (75BST sub) several times.

**Comment by montijin** [comment]
The issue isn't that you can't charm things with a BST sub, its that you aren't supposed to be able to charm things out of the range of the max level of your beastmaster. BST as a subjob works differently from other jobs. 

From the blogpost I linked from 2006: "Note: Charm has a very unique property.. while your BST subjob is capped at 37, charm's effectiveness (success rate) "remembers" if your original BST level was above level 37, and by how much. In other words, whereas skills like summoning magic skill or singing skill are capped as a subjob, the hidden charm skill is NOT (it is still somewhat nerfed as sub however). It is the only thing I know that works this way in this game, but trust me, I was very skeptical too until I tested it enough to know myself."

**Comment by gweivyth** [comment]
> This doesn't look like it is the case. Please add some proof of testing in here if you believe this to be an issue. Such as something like failing to charm level 70 mobs as a 75WAR (75BST sub) several times.

Definitely want to reopen this.  Charm success rate, even as a subjob ability, should always be dictated by the ACTUAL level of your Beastmaster, not the level of your main job.

**Comment by EliannaEden** [comment]
Are you telling me we could have been doing BST Tiamats with an army of MAIN75/BST1 job, all of this time? >.>;

**Comment by montijin** [comment]
Well you definitely don't need to take BST to 75 ^^;

**Comment by tirem** [comment]
What was the end result of this issue? Is it confirmed on Eden that level of BST matters as a subjob beyond half the mainjobs level?
