### ISSUE TITLE
Mobs frequently despawn in East and West Altepa

### ISSUE THREAD

**Issue by ababyduck** [EdenServer/community#1196]
I've been seeing a lot of this over the last week or so. Beetles or scorpions or spiders will just randomly despawn. They're not chasing anyone, they're not aggressed, they just occasionally fade out for no apparent reason. 

Possibly caused by wander behavior moving them too far from their spawn points?

**Comment by gweivyth** [comment]
Watched this happen a little bit while chocobo digging today, definitely has to do with the "too far away from spawn" patch.  Mobs in the deserts have pretty long roam ranges so this doesn't surprise me.

**Comment by blacknesscrows** [comment]
ya this happens often, i hope its not jackin up the dune widow ph's. shes a great source of delicious webs

**Comment by 59blargedy** [comment]
i believe this was resolved with the range/roam changes introduced earlier this year. can reopen if not
