### ISSUE TITLE
Summoner healing prevention check is called on the wrong event

### ISSUE THREAD

**Issue by ababyduck** [EdenServer/community#1197]
Currently, Summoners are able to begin resting with an avatar out, and just before the first recovery tick they will be forced to stand and receive the "cannot rest with an avatar" message. Expected behavior is for SMN to be unable to initiate healing at all, and to receive the "cannot rest with an avatar" message immediately in response to /heal.

**Comment by beauxq** [comment]
My memory of retail is that the current behavior is correct.

**Comment by Setz0r** [comment]
this behavior was tested on retail.  it will allow you to try and rest, but will force you to stand on the next healing tick
