### ISSUE TITLE
Incorrect text ID plays after Xarcabard cutscene for Dynamis access

### ISSUE THREAD

**Issue by ababyduck** [EdenServer/community#1199]
Currently, after the Dynamis access cutscene plays, the player sees a message that a Mog Tablet has been found, rather than the correct "You can now enter Dynamis" text. 

Usually this is a result of attempting to play a textID with a bad value. DSP will fall back to textID 0 for the zone in this case, which is usually the Mog Tablet message.

**Comment by KnowOne134** [comment]
went through all the textids for the zone and nothing about dynamis entering was seen, the voided message you were getting was a nil keyitem text id for VIAL_OF_SHROUDED_SAND
