### ISSUE TITLE
Failed 2-3 BCNM (Waughroon) and can't retry

### ISSUE THREAD

**Issue by xizeta** [EdenServer/community#1201]
I entered the BCNM solo, killed the Seeker and then died to Dark Dragon. Was not able to re-enter, BCNM is missing from the list. I went back and spoke to every NPC for the mission, they just say "Good luck" etc. and the BCNM list is still blank. To be clear, the only option in the menu is "None.".

```lua
[64] = function() return ((player:getCurrentMission(SANDORIA) == JOURNEY_TO_BASTOK2 or
                        player:getCurrentMission(WINDURST) == THE_THREE_KINGDOMS_BASTOK2) and player:getVar("MissionStatus") == 10) end, -- Mission 2-3
```
(From DSP Master)
525: scripts/globals/bcnm.lua says the MissionStatus should be 10 for the option to appear. Checked with GM and my MissionStatus is currently 0.

Additionally I thought this was worth including:
The FFXIclopedia page suggested the "Dark Key" was a required item for the Waughroon BCNM (I think because the table was copied directly from the Windurst BCNM version). None of the NPCs in Bastok give a Dark Key, BGWiki doesn't mention it (Only for Windurst) and the DSP master branch (I checked as far back as 2013) doesn't check for it either. Anyway, the wiki entry has since been updated, because it was clearly incorrect. This may have caused some confusion about what was necessary for entry.

**Comment by godmode** [comment]
Thanks for the detailed report. This actually clears up a lot of previous bug reports that I found their MissionStatus was set to 0. This is very helpful.

**Comment by 1Zeta** [comment]
Please can my player var for MissionStatus be updated to the correct value of 10?

I don't want to be a pain but I know GM can't update this and I want to complete the mission for Mog Wardrobe. Let me know if there's anything else I can do to assist with this.

Thank you.

**Comment by godmode** [comment]
Yeah, go ahead and place a gm ticket for this and address it to me. Please leave this ticket open even after your particular case has been addressed
