### ISSUE TITLE
Lure of the Wildcat (San d'Oria)

### ISSUE THREAD

**Issue by Natchananananan** [EdenServer/community#1202]
https://github.com/EdenServer/community/issues/1144

Can i just have my quest reset so i can do this again please? Thank you

**Comment by godmode** [comment]
I’m not sure if a GM told you to post here. If so, sorry for the runaround. You were right to post your original issue as a bug report. However, resolving issues comes by priority. This one currently is not at the top of the list but it will be handled eventually with your initial ticket. Please add more details on that one if you stumble across more. Thanks for your patience.
