### ISSUE TITLE
Lamia No. 19

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#1203]
I spent an hour and change trying to spawn Lamia No. 19 today, but couldn't get it to pop. We did the Elvaan sacrifice at the area where the Qutrub are ( E-11 to F-9) and inside the Lamian Prison where the NM is circled on the map. 

The info on the wiki debates where you need to be located, but in my experience on retail it was zone wide; which is also mentioned in the talk section of the NM. 

https://ffxiclopedia.fandom.com/wiki/Lamia_No.19

**Comment by jmcmorris** [comment]
How many sacrifices did you make? Any Tarutarus? I did test this while implementing this NM and it should be working with a wide range.

**Comment by montijin** [comment]
Tarutaru lives actually matter, so none were sacrificed while we were trying to spawn the NM. My combat log shows that 39 Elvaan deaths wasn't enough to spawn it.

**Comment by Mikokiko** [comment]
We tried to pop it today, we tried bot area, the one circled on the map and the one commented bellow on wiki. No message and no pop, mithra willing to die again for testing purpose !

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
