### ISSUE TITLE
Yhoator Jngle OP failed to teleport me after I got engaged by a mob.

### ISSUE THREAD

**Issue by Solisie** [EdenServer/community#1205]
I used a homing ring to get to the yhoator OP then I talked to the teleport npc and chose to be teleported by spending conquest points andd during that a nearby thornberry engaged me.

I became invisible as if teleporting but after that I was left there not being able to do anything while the thornberry chef stabbed me to death then I simply Home Pointed.

**Comment by CloudyDesarroi** [comment]
Might be related: #460 
I imagine that the teleport sequence is considered a CS and thus has the same issue.

**Comment by godmode** [comment]
It's not an issue with the aggro it's because of the issue linked by Cloudy. Closing this ticket as a duplicate.
