### ISSUE TITLE
Mom the Adventurer

### ISSUE THREAD

**Issue by Wilsor** [EdenServer/community#1206]
The next quest (The Signpost Marks the Spot) can be flagged without finishing the pre-requisite if you have enough fame. The quest then becomes unfinishable. The NPC (Nbu Latteh) won't accept the required item (copper ring). Finishing 'The Signpost Marks the Spot' still won't let you finish the previous quest.

**Comment by ShiyoKozuki** [comment]
It's weird that only the second part of this chain is in.

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
