### ISSUE TITLE
Norvallen OP displaying Wrong Flag.

### ISSUE THREAD

**Issue by Drognand** [EdenServer/community#1207]
I was grabbing my pld item in davoi, Run back to the OP to find this
![drognand_2019 03 07_072040](https://user-images.githubusercontent.com/47567545/53956438-a4338000-40a9-11e9-984b-b19fd77d40c1.png)

![drognand_2019 03 07_072206](https://user-images.githubusercontent.com/47567545/53956483-ba414080-40a9-11e9-976e-a67614965064.png)

Simply Windy owns the Area, Right Guard, just wrong flag

**Comment by xizeta** [comment]
Additionally, when Bastok has control, it shows the outpost NPC and the Beastmen flag.
