### ISSUE TITLE
Incorrect weather in Norg

### ISSUE THREAD

**Issue by triple-lariat** [EdenServer/community#1208]
According to https://ffxiclopedia.fandom.com/wiki/Norg?direction=next&oldid=484638 there is supposed to be no possible weather in Norg, yet I found that water weather had occurred there:
![desarroi_2019 03 07_081747](https://user-images.githubusercontent.com/30502556/53967278-2758d400-40b2-11e9-99d8-3f1baf82e90f.png)

**Comment by KnowOne134** [comment]
retail captures ive done shows it shares weather with Sea serpent grotto. and rain does exsist as well as fog sun, clouds and clear

![image](https://github.com/EdenServer/community/assets/35616771/ff98d8a8-3636-48e9-a651-625a3d7d39fc)
