### ISSUE TITLE
[PUP] Sharpshot Automaton WS Daze doing low damage

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1210]
Daze was an amazing WS for PUP to get on retail. With 3x fire maneuvers and some decent attachments, it'd hit for 500+ on Lesser Colibri in the mid 50s while exping. Going up to 700 or so the higher your level. 

However, on here. With the same attachments, the highest me or any other PUP on here has been able to push it is 400 while 60+. It seems Flame Holder isn't affecting the WS as it should be. In 55 sync parties I'm lucky to break 300 with 3x fire maneuvers.
I'm actually seeing higher or similar numbers with just Tension Spring 1+2, and Inhibitor. As I am with Tension 2, inhibitor, and flame holder. While that same combination would equal 500+ damage on retail.
A large draw to daze was it's much improved damage over Arcuballista. However on this server, they do very similar amounts of damage (around 300 each)
I've also been on the test server and used Attuner, which we can't get yet. The damage only increased slightly to about 350-400. While in retail Attuner with Flame holder would've equaled a massive 600+ damage WS.

**Comment by jmcmorris** [comment]
Looked into this and everything looks right so I'm not sure what is the problem and why it is doing lower damage than what you experienced on retail. Unfortunately retail changed the fTP modifiers for Daze (along with just about every other weaponskill) so it is a little hard to test this and figure out what might be wrong.

**Comment by jmcmorris** [comment]
@Volkaru mentioned to me that the missing element is actually Attuner attachment after all. I'm going to close this for now and we'll see how things pan out once Pulling the Strings ENM is added.
