### ISSUE TITLE
Arrapago Reef Map Purchase Bugged.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#1211]
I bought the map of Arrapago Reef on Serephim with Imperial Standing and it gave me the crafting key item "Metal Purification" instead which is a GP KI for Smithing.
I bought it right after on Voretechz and I got the Arrapago Reef map normally.
![serephim_2019 03 07_131254](https://user-images.githubusercontent.com/43891789/53979327-7ff09700-40db-11e9-9537-06be584f1dd0.png)

**Comment by Serephim** [comment]
This isn't just a visual bug either, it actually gave the the smithing key item and not the map.

**Comment by KnowOne134** [comment]
issue has been resolved
![image](https://user-images.githubusercontent.com/35616771/64469012-091b7180-d0f1-11e9-894a-01875dd21447.png)
