### ISSUE TITLE
DRG Merit Deep Breathing

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#1215]
Group 2 merit ability Deep Breathing doesn't work.

https://ffxiclopedia.fandom.com/wiki/Deep_Breathing?oldid=188948

When using the macro syntax described in the link the msg 'No effect on that pet.' appears.
Nor does < pet > work.
Wyvern is summoned ofc :D

**Comment by deepbreathingeden** [comment]
can confirm it doesnt work at all. it just says no effect on that pet

**Comment by KnowOne134** [comment]
Fixed this update
