### ISSUE TITLE
Kirin Osode drop rate

### ISSUE THREAD

**Issue by Frylokk** [EdenServer/community#1217]
My LS is currently 2/20 on Eden with this drop. It was around 30-40% on retail. There is no way that we are just unlucky. 

https://ffxiclopedia.fandom.com/wiki/Kirin

**Comment by panfunk** [comment]
I can't speak for Osode, but I noticed something similar for N.feet droprate on Suzaku, current retail droprate is at 30%ish, with up to two. Which should apply to era aswell I suppose. Yet in the last 10 kills I seen, it never dropped.
Ofc this could be bad RNG, but maybe there is a general issue with loottables/drop generation on NMs/HNMs with a large itempool

**Comment by bkesecker** [comment]
Reported previously.  https://github.com/EdenServer/community/issues/928

**Comment by bkesecker** [comment]
@panfunk Please open a new issue if you feel Suzaku drop rates are wrong.
