### ISSUE TITLE
Tonberry Pursuer 18min respawn instead of 16min

### ISSUE THREAD

**Issue by Altnob** [EdenServer/community#1218]
This isn't something that calls for immediate action, but with Sozu Rogberry having such a low drop % on THF Knife, it would be nice to get the correct respawns on the placeholders. I know some people who camp for 6 hours a day and they could save 45 minutes in PH respawns with correct timers.

**Comment by Mimic716** [comment]
Can confirm.

**Comment by Mimic716** [comment]
This may also be preventing the NM from spawning on time. I spent 9+ hours last night / this morning without a pop.

**Comment by icariumkupo** [comment]
That's not how lottery works. There is no upper end. Every time you kill a PH it has a chance to spawn as a NM on repop. Knowing this, it could technically never spawn again, since they're only a chance, not a guarantee. 1-8 hours is just the average!

**Comment by Altnob** [comment]
Yea, it's a lotto but the respawn is still off on the PH. Two minutes might not seem like a lot but considering people will spend months camping this NM, those two minutes will add up.

**Comment by Mimic716** [comment]
If the PH repop time is +2 minutes higher than it was in era its average spawn time is also offset by +2.
