### ISSUE TITLE
Sabotender Bailarina not implemented?

### ISSUE THREAD

**Issue by Qair** [EdenServer/community#1219]
Nm is located in quicksand caves and is suppose to drop dune boots, but the ph doesn't seem to ever change and it doesn't pop. Hoping to have it put into the game. Thanks.

**Comment by bkesecker** [comment]
Confirmed.  Mob ID is in the DB, but no where is it referenced, nor is there Lua to control it.

**Comment by gweivyth** [comment]
> Confirmed. Mob ID is in the DB, but no where is it referenced, nor is there Lua to control it.

Darn this is good to know.  I spent hours trying to camp this thing, I eventually gave up once I found out that Dune Boots were likely a dps decrease over Fumas anyway, but they would still be cool to have.

**Comment by bkesecker** [comment]
DarkstarProject basically has no issues or pull requests with any data on this guy.  We'll need to pull from scratch or guess with what is on the wiki.

**Comment by Wiggo32** [comment]
heres another one for future data mining when someone gets around to it: 
https://youtu.be/NBQzrC87jVc

**Comment by rolanberry** [comment]
This was very surprising to me, because I'm very certain that I was able to pop this NM on the official Darkstar Classic server in April/May 2013 to get Dune Boots for my 75 MNK.  Trying to get my login credentials back in order to confirm

Dune boots are very satisfying
