### ISSUE TITLE
Garharlor the Unruly shouldn't be active

### ISSUE THREAD

**Issue by godmode** [EdenServer/community#1220]
Garharlor the Unruly and buddies are spawnable all the time in Mount Zhayolm but should only spawn during Besieged. Garharlor should be disabled and any loot obtained be removed until besieged is implemented.

**Comment by jmcmorris** [comment]
I made them available as long timed pops since we will likely not be implementing Besieged any time soon if ever and he has a good drop.

**Comment by icariumkupo** [comment]
I say keep!! I've killed him and he is very hard!

**Comment by Strumerjohn** [comment]
Yeah, he takes about 20-30 minutes to kill with a party. His friends aren't implemented though and just stand there, doing nothing. If Besieged isn't ever going to come, maybe put all the besieged nms on timers that would align to if besieged did exist, if they aren't already?

**Comment by godmode** [comment]
Who said Beseiged won’t come? :D I typically do not do custom things unless they are critical to the game like the Bastok bridge. Feel free to open a thread in forums about it if you believe they are though.

I’m not sure if you knew if they should be up or not but I imagine you didn’t. I just saw them and noticed they should not. Anyways for the future if you do notice something that may be broken it’s better to bring it up because it’s a core philosophy of our server that we don’t intentionally release broken content because it gives an unfair advantage to people that started playing earlier. It’s ok to DM me those queries in case you don’t want other LS’s knowing about ToDs and such though. I understand that aspect of it.

**Comment by godmode** [comment]
I just now read Jasson’s comment. I didn’t know that it was intentional. I will have to confer with him now. As far as Beseiged being implemented though—It will at some point.

**Comment by Strumerjohn** [comment]
Yeah, his friends definitely don't work. They don't drop anything though and he still has the buff that he should have if they're not killed, so he's still really difficult. It'd be cool to see them work so he doesn't take forever to kill lol.
It'd be awesome to see besieged come though too! I'm glad to hear that's still on the table because whenever I see it asked about it seems to always be in a negative light.

**Comment by jmcmorris** [comment]
When I implemented him I tested his bros as well and they were working. Perhaps something got messed up in the merge.

**Comment by godmode** [comment]
Could you make this so that it despawns after a certain amount of time so it's more like it would be if beseiged is active? And if it's higher than level 1 advancing make his repop time more rare?

**Comment by montijin** [comment]
went back today and now only the main NM is active and the other two brothers do not have a name plate/can't be aggro'd. Similar to how Khim/Cerb/Hydra were when toau was released here.

**Comment by godmode** [comment]
This NM will be disabled until it can be properly implemented.
