### ISSUE TITLE
San d'Oria Mission 5-1

### ISSUE THREAD

**Issue by Hekkensn** [EdenServer/community#1221]
Upon flagging sandy mission 5-1 and talking to halver, i received the new fei yen seal. Visited the gate guard and mission is flagged in my log The ruins of fei yen. Proceeded to do the mission today with a party and never did receive cut scene when i entered fei yen. I was allowed to enter the bcnm, but we failed so unsure if i would get the next key item. I've double checked everything and i do have the seal in my key items.

**Comment by bkesecker** [comment]
You have the burnt seal?
