### ISSUE TITLE
Silver Quadavs don't seem to have Quadav Stew

### ISSUE THREAD

**Issue by Strumerjohn** [EdenServer/community#1222]
I've been stealing from these for about 3 hours now and I've had no luck getting anything outside of a silver beastcoin. I know that the steal rate is low and this is meant to be hard, but I literally went 1/1 on a steal on a Garnet Quadav and got the stew. If Silver Quadavs DO have the stew, it should be easier to steal. The [wiki page](https://ffxiclopedia.fandom.com/wiki/The_Tenshodo_Showdown?oldid=359782), even back in 2007 era, shows that Garnet Quadavs, Silver Quadavs, Zircon Quadavs, and Bronze Quadavs all have the item to steal.

![image](https://user-images.githubusercontent.com/1610510/54062691-eb626380-41c4-11e9-8b92-4e9925a233c6.png)

**Comment by KnowOne134** [comment]
was corrected on 11/19/2023 update
