### ISSUE TITLE
Campsite Mobs Roam Far From Camp

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/community#1224]
I have noticed mobs that gather around campfires/campsites do not hug the site, rather wander quite far away.  Specifically West Sarutabaruta and West Ronfaure.

**Comment by godmode** [comment]
Good find!

**Comment by Serephim** [comment]
This is an issue with a lot of mobs. They roam way outside of their normal leash range.

**Comment by 59blargedy** [comment]
resolved by another dev in July 5th, 2024 patch
