### ISSUE TITLE
Imperial Sanction NPCs offer to sell PUP Attachments, but don't actually sell them

### ISSUE THREAD

**Issue by mpinholster** [EdenServer/community#1225]
Imperial Sanction NPCs offer to sell PUP Attachments, but don't actually sell them

This might be working as intended?

**Comment by jmcmorris** [comment]
The disabled attachments are out of era but unfortunately require a dat mod to hide them on the client side.

**Comment by KnowOne134** [comment]
Duplicate issue already posted
