### ISSUE TITLE
hovering oculus sighted in ranguemont pass

### ISSUE THREAD

**Issue by charley222** [EdenServer/community#1226]
hello everyone   

i play ffxi from 2003   to today  i join this server because is suppose to be a 75 cap server 
so i guess is normal i expect playing on a 75 server      but my issue a lot of monster have  the wrong monster level   but also  some monster are from the 99 era and have any existence of the 75 cap era  i go in Ranguemont Pass and find some Hovering_Oculus oO  make any sense to me ,  because these   monster are from the 99 server and  are in the wrong place  cause many issue to reach other zone  or destination

**Comment by jmcmorris** [comment]
We have correctly adjusted nearly all of the monsters to be the appropriate level and if we have missed any you can just inform us and we will work on getting it fixed. The names have also been adjusted but for now you have to use an Ashita plugin, renamer, to have them be correctly displayed until we get the dat files correctly changed.

**Comment by Far-The-Killer** [comment]
As this is not exactly a bug report, I am closing it. If you have any bugs to report please make another report detailing exactly what the bug is i.e "X mob is lvl Y instead of lvl Z in zone P"

**Comment by charley222** [comment]
i just say Hovering Oculus does not exist in the 75 era  and are not suppose to block the way to Ranguemont Pass    Floating Eye  are the right Ahriman and Bat Eye   http://ffxi.allakhazam.com/db/bestiary.html?fmob=6   https://ffxiclopedia.fandom.com/wiki/Bat_Eye

**Comment by charley222** [comment]
i just say (89level drop around 42 to 44 wrong level wrong name )Hovering Oculus does not exist in the 75 era and are not suppose to block the way from Ranguemont Pass to Beaucedine tunnel Floating Eye are the right Ahriman and Bat Eye http://ffxi.somepage.com/mobdb/1322 http://ffxi.somepage.com/mobdb/1336
and thank you for your great work /bow

**Comment by godmode** [comment]
The Hovering Oculus name but they shouldn’t be a higher level than the other eyes. Can you confirm?

**Comment by roclm** [comment]
The Hovering Oculus on Eden check Too Weak to a lv75 character. I don't use Battlemod so I can't confirm their exact level, but it looks like everything is the way it should be for these particular mobs.

**Comment by charley222** [comment]
my drk is 41 and i see  The Hovering Oculus  tough ,    the right monster level suppose to be a round  34-36    
and the real name suppose to be Floating Eye   no big deal for the name  but the monster level is wrong  look your self here   
http ://ffxi.somepage.com/mobdb/1322   ,       my opinion because i have  no software The Hovering Oculus  are around level 42-44 and use bat eye level the issue  here  bat eye in  Ranguemont Pass is  a nm  not a regular Ahriman like ( Beaucedine Glacier bat eye are regular monster ) here the link you will understand  how confusing is it  http://ffxi.somepage.com/mobdb/1336    Lottery spawn Ranguemont Pass    https://www.bg-wiki.com/bg/Bat_Eye   keep the good work thank you  :)

**Comment by bkesecker** [comment]
Was messing around in Ranguemont Pass and checked on these.  Hovering Oculus should be Bat Eye, Bilesucker also there are wrong.  Looks like neither drop anything.  75 THF with TH 4 was getting items just fine from other mobs, but not these.  It is strange, as I do see the Axe the Bat Eye is supposed to drop with sale history on Eden AH.  Perhaps the Bat Eye in Beau. Glacier are dropping items (but should not drop the Storm Axe).

**Comment by bkesecker** [comment]
Correction.  Hovering Oculus should be Floating Eye.  Both Hovering Oculus and Bilesucker would need entries added into Eden's renamer Lua.  I will see about getting that to Godmode for incorporation.  However, I will make a pull request to address the missing Floating Eye (there are supposed to be 5) and the item drop tables for these two mobs.  For reference, the renamer Lua is, as of this writing, is located here: https://www.edenxi.com/forums/viewtopic.php?f=31&t=1428

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
