### ISSUE TITLE
Enagakure Aggroing Through Floor

### ISSUE THREAD

**Issue by reynierk** [EdenServer/community#1227]
![Annalyst_2019 03 09_154726](https://user-images.githubusercontent.com/47019496/54077242-caad1300-4283-11e9-9377-18189afd897c.png)

Hi,

Is Enagakure meant to aggro through the floor?  As soon as the boat departed, Enagakure began casting Sleep II on me, twice... and then Stone III to ensure my death as a lvl 10 War haha. I did not move, I did not blink, I was just attacked through the floor the moment the ship began moving.

Not sure if this falls as a bug, or if it will ever get prioritized, but wanted to bring it to light in hope that this can be improved. I missed the first boat, then skipped the second boat because it was headed to Al Zahib, jumped on the third boat, and now dead - I hope this provides a little color to my agony.

Thank you,

**Comment by Setz0r** [comment]
this has been fixed already.
