### ISSUE TITLE
wrong zone-out  location from N sandy mog house

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#1228]
When I zoned out of my mog house into north sandoria (choosing "same location") I spawned at the position you're in when you zone into N. Sandy from S. Sandy. Only time this has ever happened to me, not sure how it happened.

**Comment by Mozzy4Ever** [comment]
Old bug report I know but was searching for something else. That's the default location for North Sandy if you zone into it. Happens if connection/lag issues happen during zoning. Server doesn't get previous zone information, so places you there.
