### ISSUE TITLE
Padded Cap NPC price is too low

### ISSUE THREAD

**Issue by Blex64** [EdenServer/community#1229]
Padded Cap should sell for ~2600 gil to an NPC with max fame. It was reduced as a counter-RMT measure.

**Comment by Elysien** [comment]
this is intentional

**Comment by Blex64** [comment]
Bump per discord discussion

**Comment by mlandrum22** [comment]
Fame doesn't affect sale price on Eden (from player to NPC) so I think we're just going to get stuck with w/e the low end is.

**Comment by Blex64** [comment]
Sounds like something that needs iits own separate ticket

**Comment by mlandrum22** [comment]
It has one.

**Comment by bkesecker** [comment]
I'll lump this in with a few other assigned issues.

**Comment by bkesecker** [comment]
Current price is accurate for Eden's era.  Closing.
https://ffxiclopedia.fandom.com/wiki/Padded_Cap?oldid=332527
https://classicffxi.fandom.com/wiki/Padded_Cap

**Comment by godmode** [comment]
I believe this is one of those gil nerf prices. Traditionally, we go with the original sell price. I’m not sure if this is what happened here or something else though.

**Comment by Raphtalia1** [comment]
Found some more information regarding this, looks like they did sell for 2600 gil, but were nerfed to 800 gil, on eden they currently sell for the 800 price
