### ISSUE TITLE
Ship ride Selbina to Mhuara

### ISSUE THREAD

**Issue by Deepupuu** [EdenServer/community#1231]
The ship ride Mhuara to Selbina works just fine however when taking the ship ride from Selbina to Mhuara it just automatically teleports you to Mhuara without a shipride.

Combine this with the Enagakure NM automatically spawning every night limits those who cannot fight the NM to one ship ride a day for fishing, please fix these issues x.x; thanks!

**Comment by Deepupuu** [comment]
Also I dont really want to create a separate ticket for this but Titanictus is suppose to be fishable on the manaclipper ride to pogo island and it currently is not, please fix that as well so it's a little easier to fish Titanictus up thanks.

**Comment by Deepupuu** [comment]
Update: Ship ride from Selbina to Mhuara is working this time around, maybe its just a bug sometimes idk.

**Comment by bkesecker** [comment]
I took the boat from Mhuara to Selbina yesterday.  When the boat docked, the front portion of the boat was higher than the back, but no issues boarding.  Saw Enagakure, didn't mess with it, and stayed behind the pilot.

**Comment by Deepupuu** [comment]
It seems Mhuara to Selbina now has the same issue of teleporting you to Selbina no boat ride now. Happened twice today but hasn't happened Selbina to Mhuara today.

**Comment by Setz0r** [comment]
these teleports are related to pirates which are in the works.
