### ISSUE TITLE
Wild Card (Several Issues)

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#1234]
The Corsair two-hour Wild Card is not restoring MP (on the relevant rolls), giving TP (on the relevant rolls), and abilities don't count as being reset unless you zone (as far as I can tell).  It's essentially literally does nothing at all in combat.  Feels bad man.

**Comment by MGramolini** [comment]
Seems to be missing pushing some packets to the client based on the results. If you gain xp or level possibly other things seem to cause the updates to display on screen.

**Comment by ThrisStraizo** [comment]
In the case of TP, if it was being recieved, it would update after a melee strike and its not the case.  In terms of MP, it doesn't even show as having mp being restored after a zone, so no MP as well.

You're probably right though when it comes to the issue of restored abilities.

**Comment by ThrisStraizo** [comment]
Just throwing this out there, used Wild Card in a party and it did EVERYTHING it was supposed to.

This is the first time I've seen Wild Card do that.  I don't know whats going on.

**Comment by VerrenGunnar** [comment]
Seems like a gear swap can fix it too, someone i was in a party with the other night had to do that to show his 2-Hour off of cooldown after i rolled a 5
