### ISSUE TITLE
[PUP] Overdrive not giving full maneuver benefits with 1x maneuver.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1235]
Under the effect of overdrive. The bonus from a single maneuver will enhance an attachment in the same way as if you had used 3x of that maneuver. 

https://ffxiclopedia.fandom.com/wiki/Overdrive
"Maneuvers give the effects of three maneuvers for attachments."
From an at era history section of the page: "Maneuvers have their effects tripled. For example, a fire Maneuver will have the same effect as 3 on an attachment. However, the effect caps with a single maneuver. Using multiple maneuvers of the same element will have no effect."

For example. Drum Magazine at 3x wind maneuver makes the automaton use a ranged attack every 5 seconds. With a single wind maneuver. It's every 14 seconds. If under the effect of overdrive. A single wind would give that full benefit of 5 second ranged attacks to the attachment. 

However, currently using 1x wind with drum magazine during overdrive is still only letting my automaton RA every 14 seconds. 
The same is said of other attachments. Flame holder should give the full bonus of 3x fire when 1x fire is used for overdrive. As well as the -PDT of Armor plates, etc. Every attachment is displaying this behavior.

This is limiting the capability of the two hour as a whole.

**Comment by Volkaru** [comment]
Here is some more info for when this gets fixed. If someone feels like they wanna take a second look at what stats the ability gives:
Here's the data about Overdrive Haste and stat resistances from 2007: https://web.archive.org/web/20110915015615/http://www.geocities.jp/pupff/other/overdrive.html (In JP)
From a BG thread: "The way haste is categorized for automatons is as follows:
From PC equipment: Considered Equipment haste
From Attachments: Considered Magic Haste
From Overdrive: Considered Magic Haste (Effect of +25%)"
And here's the testing for overdrive damage, etc. Unfortunately the accuracy will need to be verified another way, since he went from only 6% below cap, to cap (back when it was 95%)
https://web.archive.org/web/20180913022437/http://ffxi.allakhazam.com/forum.html?fjob=18;mid=121071128015227511

**Comment by KnowOne134** [comment]
Idea: use the local var "overdrive" as a check in the ability/attachments so that when gain or lose an effect checks if the var is active and if so any maneuvers > 0 will default to 3. Losing manuavours potentially may need no extra work

**Comment by KnowOne134** [comment]
closing in lieu of the certain attachments that arent working for overdrive. Pattern being attachments that remove manuvers on use, rest are working
