### ISSUE TITLE
Lost a fishing level?

### ISSUE THREAD

**Issue by Avaataru** [EdenServer/community#1236]
When I checked my fishing level tonight, it said it was 30, but I was 31. I double checked the website and it was still showing me as 31 fishing under my character profile (Avaa). 

As far as I remember, I hit 31 maybe four or five days ago in Batallia Downs, trying to get Herrings. I just got some skill ups like 10-15 mins ago to see what happened when I leveled, and now I'm 31 again. Can you look into it for me? It's possible I'm remembering incorrectly (though the website agreed with my memory) but if there's a bug with people losing fishing levels somehow, that's definitely no bueno. Thanks!

**Comment by jmcmorris** [comment]
The website rounds the craft jobs up from what I can tell. Hopefully it is just your memory that is faulty so we don't have yet another bug to fix. ;)

**Comment by godmode** [comment]
Thanks for reporting—we will look into it. In the mean time I will probably make the website round down in case it is what Jasson was saying.

**Comment by CdoubleOkay** [comment]
Any chance you can make the website show the decimal so we can see how close we are to the next level rather than rounding? Would be helpful in a lot of cases.

**Comment by Far-The-Killer** [comment]
This isn't the place for asking for features. Yooouu can post that here however https://www.edenxi.com/forums/viewforum.php?f=1

**Comment by Avaataru** [comment]
Thanks! It isn't just the website that my concern was based on, but it did incorrectly "validate" my memory when I used it to double check that I wasn't losin' it, hehe. I think the rounding down thing is a good idea Godmode. 

I hope you're right though Jasson and maybe I just got really close to 31, and then looking at the website altered my memory ;) Thanks for looking into it for me! Appreciate you guys.

**Comment by MGramolini** [comment]
It would be best if the website rounded down as that is how the game treats your level

**Comment by gweivyth** [comment]
Can 100% confirm that the website rounds up.  Was annoying while I was leveling Bonecraft to 100, but also sort of the driving force that helped me get to 100 at all.

**Comment by Setz0r** [comment]
you cannot lose levels during fishing or the fishing skillup method.
