### ISSUE TITLE
Sandoria Mission 2-3 Lost Key Item

### ISSUE THREAD

**Issue by hrmitchell** [EdenServer/community#1238]
Following https://ffxiclopedia.fandom.com/wiki/Journey_Abroad Windurst path first.

- Talked to gate guard and received the mission. 

- Talked to Halver and received key item: Letter to Consuls. 

- Traveled to Windurst and talked to Mourices. 

- Talked to Kupipi and received key item: Shield Offering.

At this point I logged off the game, which is where I think things went wrong. 

- Went to Giddeus and obtained x2 Parana Shields from NM. 

- Talked to  Uu Zhoumo, who says, "Me be keeper of treasure chamber. Hoot! Me be .... yada yada yada... Leave now." 

At this point I noticed both key items, Letter to Consuls and Shield Offerings, were gone. Traveled back to Mourices who says, "Fool. You only handed over Windust's offering and skipped back, leaving the balance of power unchecked." Also checked back with Kupipi who says something along the lines of "Back so soon...  yada yada".

My mission is still flagged, both key items are still gone. Thank you for your support.

**Comment by bkesecker** [comment]
If a GM has not fixed your situation, please make a GM call.
