### ISSUE TITLE
Unable to OP warp

### ISSUE THREAD

**Issue by stretchfox** [EdenServer/community#1239]
It does the animation and charges me for the CP, but I just go invisible. 

![image](https://user-images.githubusercontent.com/48193709/54087628-a5bbad00-4322-11e9-8c67-6e716d068437.png)

**Comment by stretchfox** [comment]
Update, didn't work with gustaberg, but did work to the dunes.

**Comment by Strumerjohn** [comment]
That usually occurs when you don't have enough CP for what CP-CostX10 of the teleport would cost. In this case, if you didn't have 800 CP then the teleport would have glitched out as it did now. Even though it only costs 80CP I think people were saying that the server still checks for what was the original CP value of the teleports on DSP of x10 the costs. You shouldn't have lost any CP from the teleport that didn't go through as far as I know, but I'm not sure on that. 

If you did have enough CP for this at the time, it may be something else for them to look into...

**Comment by stretchfox** [comment]
It was giving it back after i zoned to fix the invisible thing.  Got some more and working like you said.  Thanks.
