### ISSUE TITLE
San d'Oria Mission 5-2 no cut scean with Halver while having the key item, unable to finish and obtain R6

### ISSUE THREAD

**Issue by Hightowers** [EdenServer/community#1245]
San d'Oria Mission 5-2 no cut scean with Halver while having the key item, unable to finish and obtain R6

**Comment by Hightowers** [comment]
i have the Shadow fragment in my Temp Key Items,
the only other time i've talked to Halver was during the Lure of the wildcat quest. 
in witch i was sitting on the ability to rank up but forgot about it.  and started and completed the lure of the wild cat quest.

**Comment by bkesecker** [comment]
If you haven't already, please call GM to ask for help on this issue.
