### ISSUE TITLE
Monster TP generation upon being attacked -- too much

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1250]
This is an ongoing issue and the reason Spoondaggers has long used Summoners to kill Faffles without TP feed. Even 1 melee auto attacking an HNM yields a ridiculous amount of TP feed on a monster that we've never been able to properly quantify and we eventually decided to spare ourselves the XP and just use summoners.

This is also a major issue with Vrtra to a more limited extent (he doesn't even need anyone touching him to do 1K+ damage at 30' AoE) but we believed this was more a regain issue than us feeding him TP.

Tonight, we did Hydra. Granted, we had several melee on him (3 NINs, a WAR, and a THF) but there wasn't even a delay in how quickly he was TPing. Back-to-back-to-back tremblings, constant uptime of phys immunity at times.

Monster TP in its current state makes bringing a melee to an HNM impractical and far more difficult than it needs to be.

**Comment by 59blargedy** [comment]
tp return is normal to era at this point in time, unsure if something changed since 2019, if the monsters you were fighting had strange regain values, etc., but this isn't an issue on eden currently, so closing out.
