### ISSUE TITLE
DRG unlock quest bugged

### ISSUE THREAD

**Issue by cirdanffxi** [EdenServer/community#1253]
I have flagged the DRG unlock quest and am on the part where you mine the wyvern egg from the excavation point (in my quest log) in the maze of shakrami.  I can't get the excavation point to give me the wyvern egg.  I have used over a stack of pick axes.  I went back and redid all the steps with a GM and still can't get it to work.  I also checked my mog safe/storage to make sure I didn't already have the egg somehow.

**Comment by gweivyth** [comment]
Just saw that there is an escalated ticket for this in the ticket queue.  Can we try replicating this issue with GM characters or something?  It's the only reported instance of this happening.

**Comment by chrisalleng** [comment]
Just to double check, you're trading the pickaxe, not using it right?

For this quest you have to trade the pickaxe - I was able to complete this less than a week ago.

**Comment by cirdanffxi** [comment]
I have tried both trading and using the pickaxe.  I also Have a friend who successfully got the egg by using a pickaxe.  I have used/traded over two stacks of pickaxes to various excavation points in the maze.
