### ISSUE TITLE
BCNM40 teleported out of zone and lost some loot

### ISSUE THREAD

**Issue by Kobe3000** [EdenServer/community#1254]
Chest was opened while two people exited out of the cricle and we passed, one person was ported out into the mines from Royal Jelly room after opening.
We passed the scroll first before everything else and the scroll of Refresh was lost because it was supposed to to to Darkone. The person who was supposed to lot got zoned out after chest opening while we passed and there was also this wierd delay after chest was supposedly opened and the loot showed on screen.
https://cdn.discordapp.com/attachments/554139689565683724/554924096916553748/unknown.png

**Comment by godmode** [comment]
Sorry for the long wait. How long did it take for Darkone to zone out kicked being ejected from the BCNM?

**Comment by slassen** [comment]
Not enough information is provided here. Considering the issue closed. Please comment if you have more information as a bug report.
