### ISSUE TITLE
Bard Song Mambo effect

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#1255]
Hello,

I believe that the values for "Dragonfoe Mambo" and "Sheepfoe Mambo" are incorrect; however I cannot find any era-appropriate data to support.

After testing today with Gemshorn +1, each mambo gives +30 evasion.  Typically with Bard Songs, the next tier grants a higher amount.

The only data I could find supporting actual evasion bonuses on the wikipedias show 99cap with capped song values..
https://www.bg-wiki.com/bg/Category:Mambo
https://ffxiclopedia.fandom.com/wiki/Mambo

**Comment by godmode** [comment]
Sorry for the long wait. How long did it take for Darkone to zone out kicked being ejected from the BCNM?

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 update.
