### ISSUE TITLE
First attack round against mobs with spikes on doesn't trigger spikes

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#126]
Not using sneak attack or anything special, but the first round of attacks when I engage a mob that has blaze spikes on isn't triggering the spikes effect.

**Comment by roriffxi** [comment]
Did some testing again this morning and the animation occurred on inital attack

**Comment by godmode** [comment]
So it’s an intermittent issue?

**Comment by roriffxi** [comment]
Yeah I'm not sure, I saw it happen 3 times in a row yesterday when killing Mysticmaker Profblix, I've now killed him twice today and the spikes hit me immediately & I take damage.

**Comment by godmode** [comment]
Is this still happening?
