### ISSUE TITLE
Yowie NM - Kuftal Tunnel

### ISSUE THREAD

**Issue by LongTimeGaming** [EdenServer/community#1260]
This NMs gil amount he drops is not correct. Have gotten barely 100gil the passed 4 kills
![yowie](https://user-images.githubusercontent.com/47086093/54246437-3bb22c00-450b-11e9-84c8-c3717a57909e.png)
 when wiki says he's supposed to drop 12k+ https://ffxiclopedia.fandom.com/wiki/Yowie

**Comment by ababyduck** [comment]
Also sas "Can be Mugged repeatedly for the maximum ~3,000-4000 gil" but I got maybe ~100 when I went with a 75 THF.

**Comment by Redenius** [comment]
Mug seems broken all around. You will not get much gil from any NM.

**Comment by ababyduck** [comment]
> 
> 
> Mug seems broken all around. You will not get much gil from any NM.

I believe that's actually due to the "purse" value set on a per-mob basis. Mug itself works fine on certain HNMs, like Simurgh and Serket for example.
