### ISSUE TITLE
CoP- The Secrets of Worship; Old professor Mariselle behaviour

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1261]
This NM is supposed to warp around the room. Currently, he despawns but respawns immediately where he despawned from. He casts and pops adds correctly.

**Comment by PoppaPip** [comment]
Echoed. Fought last night, he "warps", but ends up in the same location.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update, will post new ticket for keeping ghosts inside the rooms
