### ISSUE TITLE
Install Download Fails

### ISSUE THREAD

**Issue by Issom** [EdenServer/community#1262]
I am getting this error from the Google Doc download.

This site can’t be reached The webpage at https://doc-0k-48-docs.googleusercontent.com/docs/securesc/vuieeci51abdr2aeqadkal8p09nf47l9/k6nnlg5hpl1t8h3g2thkd02ds5lgsgtm/1552442400000/04754488575280426238/17359188221457803708/16pGVEbrxCuVI49I4HbyZlPTi8FYoKyMa?e=download might be temporarily down or it may have moved permanently to a new web address.

Thanks for your help
Issom

**Comment by godmode** [comment]
There is currently an issue with Google Drive. Unfortunately it's out of my hands on this one. I will leave the ticket open until the Google team fixes the issue. https://downdetector.com/status/google-drive

**Comment by Issom** [comment]
Perfect.. Thank you for the reply.
