### ISSUE TITLE
NM - Nue (Beaucedine Glacier) Drop Rate?

### ISSUE THREAD

**Issue by hienlongli** [EdenServer/community#1263]
According to the website link https://classicffxi.fandom.com/wiki/Nue the drop rate seems to be fairly rare. However, I've killed Nue 10 times with TH1 and 2 times with TH2 with no drops yet. I was just wondering if this was a possible bug or just extremely unlucky.

**Comment by Far-The-Killer** [comment]
Looks like he drops it, just pretty rare. Also rng is messed up so expect it to be a little tougher sometimes.
