### ISSUE TITLE
Chaosbringer kills while not on Blade of Darkness/Death not counted

### ISSUE THREAD

**Issue by chrisalleng** [EdenServer/community#1264]
Steps undertaken:
Accepted "Blade of Darkness", equipped chaosbringer
Killed 105 mobs, with only auto attacks
Completed "Blade of Darkness"
Character was not high enough fame to start "Blade of Death"
Character killed another 100 mobs in the same way (total 205)
Character accepts "Blade of Death" quest
Character was not able to complete "Blade of Death" quest by trading the Chaosbringer in Gusgen Mines
Killed another few dozen mobs with the sword (however many level 1-2 mobs get a DRK from 3 -> 5) 😆 
Character was still not able to complete "Blade of Death"

I opened an issue in darkstar which should hopefully help:
https://github.com/DarkstarProject/darkstar/issues/5791

Basically, Chaosbringer kills are only being counted while the player is on the Blade of Darkness or Blade of Death quests - this is incorrect. Kills with the weapon should be counted even when the player is not on either quest.  

Source: https://ffxiclopedia.fandom.com/wiki/Blade_of_Death as well as personal memory.  That line on the wiki was added in 2011, but I remember doing it this way in retail during RotZ, though of course my memory could be wrong.  It seems incredibly unlikely this was changed randomly in 2011 though, when the wiki was updated.

darkstar/scripts/globals/mobs.lua line 16-40 contains the relevant code

EDIT: Also, it's an incredibly minor technicality, but to be the same as retail other abilities such as Jump shouldn't be counted - I'm not sure if isWeaponSkillKill includes other things like that, though.  Frankly, the quest not counting abilities or WS kills was probably a bug in retail in the first place, not sure it's worth the effort of reproducing!

**Comment by Live-xi** [comment]
Has this been reassigned to anyone for a solution?

**Comment by chrisalleng** [comment]
Oh, while I'm not an active player anymore (just no time, unfortunately), I did follow the darkstar side of things here: https://github.com/DarkstarProject/darkstar/issues/5791.  The TL;DR there seems to be permanently on hold until they refactor how all the weapons with state work, so I wouldn't expect anything upstream anytime soon.

Thanks again for maintaining this - it's an amazing effort.

**Comment by KnowOne134** [comment]
Corrected 7/29/2021
