### ISSUE TITLE
Flamingos in Sky not giving sword skill ups past 207

### ISSUE THREAD

**Issue by CorlaZodren** [EdenServer/community#1267]
Been trying to skill up off of these mobs and they don't seem to be giving me any skill ups on my sword.  I switched to hand to hand which was 192 and that worked fine, I have 265 evasion and got a skill up to 266 off them and am getting parry skill ups around 219, but I can't get any skill ups on swords.

I've zoned several times and changed my gear, nothing seems to be working.  The mob's levels are 72-74

**Comment by ISilenceI** [comment]
Then this is not an issue. They should only raise sword to 208 at most.
Use this to calculate what the maximum skill a mob will give.
http://ffxi.somepage.com/skilldb/
Select sword on skill, then select Thief for job and put the Mob level in the level box. That is the skill you can gain from the mob.

**Comment by CorlaZodren** [comment]
But they are giving skill ups on skills higher than 208 on other skills....

**Comment by ISilenceI** [comment]
Because those other skills have a better skill rating.  For THF you could get 264 dagger skill on those mobs, but only 208 sword skill.

**Comment by gweivyth** [comment]
> Then this is not an issue. They should only raise sword to 208 at most.
> Use this to calculate what the maximum skill a mob will give.
> http://ffxi.somepage.com/skilldb/
> Select sword on skill, then select Thief for job and put the Mob level in the level box. That is the skill you can gain from the mob.

Wow this is such a useful tool that I was unaware of, thank you for posting this.
