### ISSUE TITLE
Big Bomb despawns if left alone too long

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#1269]
Upon initial spawn, Big Bomb seems to stay up indefinitely. However, after fighting and dying to this NM, he returned to his spawn area but then despawned after about 15 minutes. Probably unintended left over mechanic from when he was a forced pop NM. He should remain up until killed.

**Comment by Lilswitche** [comment]
Adding on to this bug report: This NM is taking a very long time to pop in general.  It's supposed to be able to be popped after 1 hour from previous kill and shouldn't take 15+ hrs to pop.  Prior to the smoky flask changes, it was able to spawn from either of the Friar's Lanterns on the bridge.  On Eden, there's 3 bombs, but I suspect there's only 1 PH and the pop % is incredibly low.

**Comment by jmcmorris** [comment]
Verified that despawn is not correct and I will fix that however the PHs are correct and while it is definitely possible for the NM to take 15 hours it is on average not going to take nearly that long if you are killing all of the PHs.
