### ISSUE TITLE
Mug cooldown is 5 minutes, should be 15

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#127]
http://ffxiclopedia.wikia.com/wiki/Mug?oldid=351963

Mug on retail was updated at some point to be 5 minute cooldown.  It should be 15 in era.

**Comment by gweivyth** [comment]
Mug sucks anyway, we should leave it like this lol.

**Comment by godmode** [comment]
I'm planning to leave this in as a job balancing adjustment. Hide as well.
