### ISSUE TITLE
Whence Blows the Wind (lb3)

### ISSUE THREAD

**Issue by carmdeldensan** [EdenServer/community#1271]
I was invisible on the platform in Castle O where the ??? is.  I clicked the ??? and instead of getting the yagudo crest, all my buffs were removed including signet and my character was locked in place.  I couldnt move, cast, or interact with anything.  I also did not get aggro in this state.  I did not receive any message like "you are too far away to interact" when i clicked the ???.  i was able to log out and when I logged back in i was able to move again and collect the yagudo crest.

**Comment by godmode** [comment]
Are you on Eden’s client version? You can find out what version you are on by typing /ver in game

**Comment by vegeta2999** [comment]
30181205_0

**Comment by godmode** [comment]
That’s our version. Very weird behavior then. Thanks for reporting.

**Comment by godmode** [comment]
If anyone else runs into this issue please comment on this thread. Unable to reproduce. Closing for now.
