### ISSUE TITLE
Guild Points Hand in Bug (Fishing Guild)

### ISSUE THREAD

**Issue by HammerhandsKupo** [EdenServer/community#1273]
Today I was 87 Fishing and checked the GP fish at Fenella in the Fisher's Guild. It was Moat Carps. I decided to not fish Moat Carps because they offered very little GP.  I instead leveled again to 88, ranked up to Veteran, and checked the new GP fish. The new GP fish Fenella was asking for was Elshimo Frogs, with a GP limit of 2,321 points.  I went and fished 15 Elshimo Frogs and attempted to hand them in.  The lady Fenella would not take them. She still says I have a limit of 2,321 and is asking for Elshimo Frogs.  

I'm guessing the bug here lies in the fact that I checked her twice in one day (once before ranking up, once after).  I have not tried fishing Moat Carps to see if she will take them. She shouldn't because those are the old rank fish. XD

**Comment by ISilenceI** [comment]
You cannot turn in GP items after ranking up. You must wait until the next real life day (11am EST). It is this way for all guilds and is not a bug.

**Comment by HammerhandsKupo** [comment]
Ah, yeah. I spoke with a guild mate that logged in this morning and he agreed. This was era up until WoTG-ish.  My bad. I'll close this issue. Thanks!
