### ISSUE TITLE
Guild points limit is not what NPC will accept in edge cases

### ISSUE THREAD

**Issue by marlinla** [EdenServer/community#1276]
Two cases where guild point limit is not what NPC will accept trades for guild points while says there are availible guild points.

Starting a new contract.
Ranking up.  

Ranking up refreshes the guild point limit reported, and refreshes the item. But it will not accept any further trades.

![image](https://user-images.githubusercontent.com/18357827/54370745-91dbb800-464e-11e9-8b2c-d51ffa545c9f.png)

**Comment by MGramolini** [comment]
This is working as intended, you cannot gain guild points the same IRL day that you rank up.

**Comment by MGramolini** [comment]
The only thing that is not correct is the response from the NPC.

**Comment by KnowOne134** [comment]
Corrected 6/11/2022 update
