### ISSUE TITLE
Random Deal

### ISSUE THREAD

**Issue by Mikokiko** [EdenServer/community#1278]
Random deal has the possibility of reseting the recast time of a random job ability for party members.

However, it have been a few times where it reset 2 hours. Wicht it should not be able to do so.

It happened in a XP merit party, where the war poped is 2 hours, because why not. I used Random Deal to reset the job ability, and it's where he told me it reset is 2 hours. Wild card was still avaible, so I did not use my 2 hour by mistake. He used his 2 hours again, I tried to random deal it again to see if it would reset again, did not work. Then when random deal was back up I used it and it reset is 2 hours again.

So out of 3 random deal I was able to reset 2 hours twice and 0 job ability.

**Comment by Kusarigama-Eden** [comment]
Bump this is still a issue and quite and abusable one.

**Comment by Volkaru** [comment]
As referenced in #2397 and #2427 this is still an issue.

**Comment by slassen** [comment]
This will now not restore some charge abilities. Due to the way the system was coded 2 hours and some other abilities share the same recast ID which is how recasts are deleted. A bug report will need to be made for that. However it will no longer restore 2 hours.

**Comment by Fng098** [comment]
It seems to still be bugged. I reset a SMN 2 hour today with Random deal. Possibly needs more testing before closed.

**Comment by Volkaru** [comment]
Can confirm. There is also an issue where sometimes wildcard will only reset one ability, even on a 5/6. So it's possible the resets for COR in general are bugged.

**Comment by Kusarigama-Eden** [comment]
I have been pondering quite a while about what might be going on. I do not know the levels of the other people but Loaded Deck and Commodors Frac (do not have the latter yet) could be triggering 2 hour resets on their own. Frac for those who do not know increases the reset from 1 ability to occasionally and Loaded Deck is the base version which focuses Random Deal on recast abilities. Most COR will have 1 point in it normally not more. Both have a possibility of circumventing as well maybe. Just a thought.

**Comment by Fng098** [comment]
I do not have any COR AF nor COR merits.  So that theory is less likely to be the issue.

**Comment by Volkaru** [comment]
Sorry. Should have mentioned. My COR is only 74. So no frac or merits.

**Comment by Kusarigama-Eden** [comment]
Woo just wanted to report at this time with/without zoning Random Deal is not resetting 2 hours. <3

**Comment by 59blargedy** [comment]
i havent heard of this issue occuring for years, assumed resolved in may 2020 and closing out. can comment if still occurring.
