### ISSUE TITLE
Fly High

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#1279]
When completing the quest for Mistmelt I tried to trade in a second set of hippo feathers and received this message:
![qiWO83C](https://user-images.githubusercontent.com/2160211/54391097-f9572f00-4671-11e9-9d2d-944582275154.png)

I'm not sure if its correct that you can only have one, the item doesn't have a tag for rare or ex. I lost the second set of feathers though.
https://ffxiclopedia.fandom.com/wiki/Fly_High

**Comment by godmode** [comment]
I believe it’s one of the items that had it’s rare tag taken off in SoA. Will have to add a check for the items in the script. Please make a GM ticket addressed to me for the feathers although it will be a few days most likely before I can get to it.

**Comment by bkesecker** [comment]
Apologies.  I was a bit rushed implementing this and missed that case.

**Comment by bkesecker** [comment]
Trying to !additem while possessing the Mistmelt results in the same message, so you definitely cannot carry more than 1 at a time.

**Comment by icariumkupo** [comment]
https://web.archive.org/web/20060118044908/http://promathia.runtimerepairs.com/Missions/4-2.html

According to this era guide, mistmelt is ex but not rare

**Comment by godmode** [comment]
http://ffxi.allakhazam.com/wiki/December_9%2C__2004_Update_Notes_%28FFXI%29

**Comment by godmode** [comment]
Working on CoP now and found these patch notes. For future reference. http://www.playonline.com/pcd/update/ff11us/20070606TsVPr1/detail.html

**Comment by godmode** [comment]
![04en](https://user-images.githubusercontent.com/6099499/65378443-62a1a580-dc86-11e9-9537-bd21be84d153.jpg)

**Comment by roriffxi** [comment]
This is either still a problem, or became a problem again.  I cannot obtain a 2nd Mistmelt even though it should be Ex.
