### ISSUE TITLE
LoO PH should be a 5 min repop?

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#128]
http://ffxiclopedia.wikia.com/wiki/Lord_of_Onzozo

I can't find any information on if this was changed at some point in retail, but currently it says here that the LoO PH is a 5 min repop and the PH will rage after 10 minutes.

This would lead me to think it was added when Rage was added to mobs (so fairly early, definitely within era).

**Comment by godmode** [comment]
Even if this was the case LoO dropped Octave Club this era so we probably wouldn’t change it for consistency.
