### ISSUE TITLE
Zilart Mission 4- KI not given after completion

### ISSUE THREAD

**Issue by phobos1234** [EdenServer/community#1285]
Had an issue with ZM4 where we tried to enter, but someone was doing the BC60 "Jungle Boogeyman".

We got ported to nowhere, a GM ported us back (thanks!) and then we completed the ZM fight.  No key item given though, despite receiving the cutscene, and now I'm stuck in ZM mission limbo.

Attached pics
![Phobos_2019 03 14_205350](https://user-images.githubusercontent.com/46583105/54402725-7cdd4400-46a3-11e9-83d2-9f47e3c71d5a.png)
![Phobos_2019 03 14_214821](https://user-images.githubusercontent.com/46583105/54402728-7ea70780-46a3-11e9-9e46-e1beff3e9e34.png)
![Phobos_2019 03 14_214854](https://user-images.githubusercontent.com/46583105/54402729-81096180-46a3-11e9-8ae5-6ff7a513986b.png)

**Comment by godmode** [comment]
Please leave this issue open. Even though I fixed the issue on your character the problem still exists. Thanks.
