### ISSUE TITLE
Vrtra Drop Pool

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#1286]
Vrtra should have a 100% drop rate on 2 thread and 2 wool, but we only got 1 thread and 2 wool. plz halp =(

**Comment by tectal831** [comment]
https://ffxiclopedia.fandom.com/wiki/Vrtra for reference

**Comment by tectal831** [comment]
it looks like wyrm horn is supposed to be 100% too http://www.ffxidb.com/zones/190/vrtra

**Comment by VirtuosusFFXI** [comment]
Wyrm Horn is still not 100% drop rate. Needs to be re-opened.

**Comment by VirtuosusFFXI** [comment]
According to this: http://www.ffxidb.com/zones/190/vrtra

Out of 92 kills, 97 Wyrm Horns dropped. So there may even be a very low chance of another horn dropping, but not really sure.

**Comment by setsuk0** [comment]
Can confirm out of our ~10 kills or so on Vrtra, have received 0 wyrm horns.

**Comment by 59blargedy** [comment]
resolved 11/2 update
