### ISSUE TITLE
Bloody bolts not draining HP

### ISSUE THREAD

**Issue by CorlaZodren** [EdenServer/community#1288]
I've noticed the higher level the mob the less Bloody Bolts will drain, with it even returning 0 HP.  I've capped Marksmenship for THF and mostly on NMs (even some lower level NMs) the bolts don't return much of any, or no HP.

**Comment by ISilenceI** [comment]
Which type of mobs were you fighting?

**Comment by gweivyth** [comment]
If the bolts are working the same way Drain does, this sounds normal.  [Skill is a huge factor in drain damage](https://ffxiclopedia.fandom.com/wiki/Drain).  Thief's Marksmanship skill isn't that great (C+ is meh) so you're basically shooting with the same skill a level 66 who had A- skill would have.

**Comment by Wiggo32** [comment]
Bloody Bolts are indeed affected by INT on retail. Lets close this though because there is already an issue opened with regard to the Bolts:
https://github.com/EdenServer/community/issues/1191
