### ISSUE TITLE
??? for Limit Break 2 is disappearing quickly

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#129]
The ???'s that pop after the NMs die are disappearing really fast. We had to do a couple of them twice because not everyone could click them in time.

**Comment by godmode** [comment]
Sounds like era to me!

**Comment by gweivyth** [comment]
> I mean there's a lot of things that are Era, but something like this could be a nice QoL change. You completed the requirements for the quest, it requiring you to kill them again is a mistake on SE's part. 15 seconds (what I believe was era) is a bit ridiculous. Even 1+ minute would be fine, retail has it at 5 iirc

I think GM was making a joke there.  :P

**Comment by godmode** [comment]
My jokes are quite dry but I wasn’t here. 👹If the time is not correct to era or there are issues with the ??? spawning after the mob dies please update the ticket.

**Comment by Oyaziiiiiii** [comment]
Just did this again and it's still too fast so I did a little digging.

https://www.youtube.com/watch?v=KI584dgb5ec

3:34 mark: Hound dies, and the ??? pops immediately. 35 seconds later the video cuts but the team gets out of there without the ??? depopping on them or getting aggroed by the repop. 

Here, the ??? doesn't spawn until the monster depops. That cuts the window down to hit the ??? by like 17-18 seconds. We had to kill them all twice because that's not enough time to click the ??? and get out of there safely, especially for a 2box.

**Comment by godmode** [comment]
Seems like the date is 2009 there. I remember them being very short. They expanded it a couple times. However I imagine it was when they died the qm popped instead of despawn. So will give you a bit more time.

**Comment by roriffxi** [comment]
Wiki history has the repop time at 30 seconds in Era.  Thats not the problem.

The problem is the ??? isnt appearing until 15 seconds into that window.

So instead of having 30 seconds to hit the ??? and get out, you're only getting 15 seconds.

**Comment by Oyaziiiiiii** [comment]
https://www.youtube.com/watch?v=qLXTTtiQiiQ&t=6s 

At 3:42 they run to the ??? without waiting for the mob to depop. It's hard to see but they had more than 20s at minimum to get out of there. Enough time for more than 18 people body blocking each other to get the ??? and get out without aggro. I think the issue is the ??? is supposed to pop when the mob reaches 0 hp and not when the mob depops.

**Comment by godmode** [comment]
Yeah I think so too. Respawn time seems appropriate though
