### ISSUE TITLE
Crystals dropping/not dropping incorrectly

### ISSUE THREAD

**Issue by roclm** [EdenServer/community#1299]
I had my suspicions that the _current_ influence of a nation was determining crystal drops in regions, and I've finally got a smoking gun, basically.
As it stands right now, you cannot obtain crystals in regions in which the Beastman are the Dominant influence. This is incorrect behaviour, crystals should still be obtainable in regions in which Beastman are the Dominant influence as long as one of the three Nations **controls** the region.
On the other side of the coin, you CAN obtain crystals in regions _owned_ by the Beastman. This is incorrect, as even the text upon hourly Conquest updates states. 
https://i.imgur.com/Hkd8kY1.png
https://i.imgur.com/UeSdf3Z.png

As the above screenshots show, the Beastman currently control the Tu'Lia region on Eden. Monsters should not drop crystals in this case. However, because San d'Oria is the Dominant influence in the region, crystals are dropping. Earlier this week, the reverse was true in Valkurm Dunes: #1246; and an earlier example where I first theorized this was the case: #1134 .

I believe a fix to this will solve a plethora of bug reports about crystals dropping.

**Comment by godmode** [comment]
Great finding! Thanks for the detailed info. This should help.
