### ISSUE TITLE
Flash overpowered

### ISSUE THREAD

**Issue by Talimax** [EdenServer/community#1300]
Based on videos actual land rate seems to be good, however only the actual land rate should be good. Like most debuffs this was subject to degrees of landing, i.e; 1/4, 1/3 resist, 1/2 resist. It currently appears to full land every time, similar to the Bind bug report that was reported some time ago.
The effect itself also seems ridiculously powerful, I've yet been able to get a solid information concerning how strong it should be, all I've found so far is "a large decrease in acc". should not be touched until some solid data is brought around but maybe some others can chime in I do not remember it basically producing -95% acc as it seems to be doing on eden though. 
-95% acc that is not resisted and lasts full duration every time is quite strong and PLD can use it a lot with haste equips and march song and haste spell.

**Comment by roclm** [comment]
Flash was tested after the days of /checkparam to be -300 accuracy to start, which is a pretty sizable decrease. If it feels overpowered, it might be because the accuracy decrease is static?

https://www.bg-wiki.com/bg/Flash
https://www.bluegartr.com/threads/108196-Random-Facts-Thread-Magic?p=6044139&viewfull=1#post6044139

**Comment by Talimax** [comment]
Ah that is a possibility. Good link, thanks for that!

https://www.bg-wiki.com/bg/Flash

That link also states, in addition to the rapid decrease over time;

"The effect is typically only resisted by light-based enemies or enemies which are either fully or temporarily immune to magic. That being said, though high level enemies will not resist the effect outright, it will tend to only last an instant"

This is how I remember Flash being on HNM/Sky god. It lasted 1-3 second and on these types of enemies was just a means for a good bit of enmity rather than basically shutting down a endgame boss like it can on Eden.

**Comment by rujind** [comment]
Yeah but how many people had their Divine skill leveled back then. Skill matters a LOT and skill was pretty insane to level back then.

**Comment by Talimax** [comment]
every PLD I am sure. It is a low level spell, and they spam it in every situation ever the moment they can learn it.

**Comment by beauxq** [comment]
The accuracy penalty effect of Flash is not too strong. I remember a time fighting Dynamis Lord in era retail and he got off an Oblivion Smash, but he was flashed at the time, so Oblivion Smash missed everyone and did nothing. Yes, HNMs should be almost guaranteed to miss you when they are flashed. That's how strong the accuracy penalty should be.

The main problem is just that its duration should be resisted more.

**Comment by rujind** [comment]
> every PLD I am sure. It is a low level spell, and they spam it in every situation ever the moment they can learn it.

I don't really consider 37 that low of a level. A PLD probably casts it once per mob, if that. 25 MP is also a hefty cost per mob if there's no form of MP regen in the party. So a PLD had a small chance, per every 1-2 mobs, to skill up in Divine.

Again, I think you just don't recall what leveling up skills was like during era. It's not the same here/DSP, if you weren't aware. I never played PLD or WHM but a close friend was a PLD on retail during era, and I recall him talking about how amazing and potent Flash was.

**Comment by gweivyth** [comment]
> Yeah but how many people had their Divine skill leveled back then. Skill matters a LOT and skill was pretty insane to level back then.

Every Paladin.  Probably less common for White Mages, but on PLD I capped Divine every level very easily once I got Flash.  I had a harder time leveling Ninjutsu.

**Comment by marlinla** [comment]
Flash is the light analog to stun. Both share similar enmity, disable, and duration properties but the actual implementation mechanic is different. The effect is intended to briefly lock down a character to react with more longer term responses in combat after a significant event. -95% accuracy for a very short period seems correct from a design point of view.

**Comment by Elysien** [comment]
.

**Comment by Elysien** [comment]
Duration certainly needs some looking at, I do recall it landing very briefly on hnm such as the link the topic creator posted suggested.

As it stands, me as a 75 rdm with pathetic evasion would have Cerberus miss almost 5 attack rounds every time Flash was cast on him, so it would appear that the diminishing effect of Flash is also either too weak or absent entirely.

Toau hnm's main stopping power, aside their iconic "ultra" ability, is there low delay/high attack standard melee rounds. Flash is pretty crippling to them on this regard.

**Comment by erenik** [comment]
As a former PLD I can agree that Divine magic skill never really required leveling up. After lvl 40+ (refresh) or in the presence of a bard you would Flash every fight at least a few times and keep it high level or nearly capped all the way. I only really remembered having to skill-up shield skill as PLD. I don't know the statistics, but the feeling of accuracy drop of enemies under flash was probably around -50 to -80% for IT mobs, which would still hit you a lot of the time even when flashed.

**Comment by ababyduck** [comment]
Thoughts from a retail WHM: Flash was what you casted when the NIN tank had to recast Utsu1 with no shadows, or when your BLM was about to get deleted. It had a short duration but almost guaranteed a miss, with or without much Divine skill. This is how I always used it, well before CoP gave us an easy way to level divine (dolphins).

On DSP I don't even bother using it. I haven't done any recent testing, but at least on Kupo it felt like Flash gave far more enmity than it should have, with a negligible and totally unreliable acc penalty. I'm not sure what changes Eden has made that are relevant to Flash, but those are my thoughts on how it was, and should be.

**Comment by beauxq** [comment]
I remember using it that way as WHM too. If you cast it right as the NIN starts casting Utsu ichi, you would almost guarantee that the mob misses, so the NIN can complete Utsu ichi.

**Comment by roriffxi** [comment]
There was a patch recently which should have addressed this, making it so flash doesnt always last full duration.

**Comment by 59blargedy** [comment]
resolved in February 1, 2021 update.
