### ISSUE TITLE
Damage display with Holy bolts

### ISSUE THREAD

**Issue by Quetzaxi** [EdenServer/community#1301]
May need more testing, but in Promy-Dem Holy Bolts show additional effect damage for 13,000+

This has no effect on how much damage is being down, appears to be purely visual. Unsure if additional effect damage is being applied in anyway from the bolt attacks. 
Group is currently running Prommy if Devs need to view in action.

**Comment by Setz0r** [comment]
This has been a DSP bug for many years.  I guess it has never been important enough for anybody to research

**Comment by AnimeMuyou** [comment]
(bump) Observed that Holy Bolts are displaying zero additional light damage (at least when shooting Antica in West Altepa).
