### ISSUE TITLE
Rampart/Warcry emnity.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#1302]
Requesting code check to ensure they are giving increased emnity based on hitting multiple allies with the JAs.  Currently it feels like these 2 job abilities are only giving the base emnity as if you were solo. The emnity values should be 1 CE / 300 VE per ally hit - up to 6 CE / 1800 VE. 

Also, this should apply to AoE spells but I believe those to be working correctly based on some expriences playing bard.

[Wiki Proof of emnity multiplying based on allies hit.](https://ffxiclopedia.fandom.com/wiki/Warcry?oldid=358846)

[Emnity Table Link](https://kanican.livejournal.com/13848.html)

**Comment by Zaekkor** [comment]
In my experience Rampart isn't pulling much if any enmity. 1800 enmity is the same enmity as Sentinel, which works very well for grabbing a mobs attention, and is enough that provoke wont pull it off the PLD..a full stack Rampart does not mimic the enmity gain of Sentinel, in fact I have never seen a mob turn from using it.

**Comment by tectal831** [comment]
Can confirm rampart doesnt seem to give enmity. Can not confirm if it supposed to however. At work so I cant check if somebody can chime in with evidence

**Comment by gweivyth** [comment]
In my experience it does generate enmity, but barely any.  Maybe equivalent to "circle" spells.  Either way definitely not working as intended.

**Comment by icariumkupo** [comment]
Maybe do a full audit? Seems to me Flash gives too much enmity. Nin/drk can't keep up with pld/nin at all.

**Comment by erenik** [comment]
As a former PLD/WAR I concur that Rampart gave little enmity, but that it seemed to increase by the amount of party members affected (maybe a third or fourth of a provoke). Warcry should generate a great deal of hate, somewhat similar to a provoke if it hits all 6 party members.

**Comment by godmode** [comment]
This will be fixed for warcry and rampart in the upcoming patch. If there are other abilities that generate enmity for each player affected please bring them up in a new ticket.
