### ISSUE TITLE
Client-Side Conquest Point Prices

### ISSUE THREAD

**Issue by RustyIsBad** [EdenServer/community#1303]
Copied and pasted from Discord at the request of Farthekiller so that this info doesn't get lost, even if it turns out to be a dead end.

"If I'm understanding correctly, ROM/25/39.dat should be where the dialogue table for Southern San d'Oria is located. Item IDs (or at least NPC IDs, I can't confirm item IDs) are shown in their hexadecimal format, but reversed. Scroll of Instant Warp seems to be item 4182, or 1056 in hex, so I figure if we find "56 10" somewhere in that .dat, it could lead us in the right direction.
And I'm pretty sure it would need to be found and changed for every conquest vendor."

Sources:
Dark Star Project
https://i.imgur.com/d8tPyj0.png

POLUtils
https://i.imgur.com/L43lz9m.png
https://i.imgur.com/r0ZqCBy.png

**Comment by KnowOne134** [comment]
duplicate issue seen here
https://github.com/EdenServer/community/issues/1713
