### ISSUE TITLE
Black Coney / White Coney spawn not working in Uleguerand Range at New moon / Full Moon 

### ISSUE THREAD

**Issue by Dauingen** [EdenServer/community#1305]
We tried fiding spawn at new moon for about an hour, no luck. 
Any plans on implementing NM?  It seem s to be an era nm according to NM list on classicffxiWiki nm list.

**Comment by godmode** [comment]
All era NMs will be implemented at some point. It depends on their priority when it happens.

**Comment by Viscus** [comment]
So is there any update on when these nm's will be implemented?

**Comment by bkesecker** [comment]
https://github.com/DarkstarProject/darkstar/pull/6325

**Comment by Caelic** [comment]
[DarkstarProject/darkstar#6388](https://github.com/DarkstarProject/darkstar/pull/6388)

Bumping for interest. Any news on this being added?
