### ISSUE TITLE
Ixtab Placeholders

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#1306]
Currently in Upper Delkfutt's Tower 6 Phasma spawn, 3 on each floor. There should be a total 5 Phasma spawning, so 2 or 3 per floor. The floor that has the third Phasma has one of those act as a potential placeholder for the NM Ixtab. I'm not sure if we were unlucky but we were also unable to spawn Ixtab by killing all the Phasma for a good while. Also not sure if having the extra Phasma is causing any issues with its spawn.
https://ffxiclopedia.fandom.com/wiki/Ixtab

**Comment by Serephim** [comment]
I have NEVER got this NM to spawn either on Kupo or Eden in dozens and dozens of hours of camping which leads me to believe you might be onto something with the placeholders being incorrect. I was speculating the same thing.

**Comment by godmode** [comment]
The NM is currently unimplemented

**Comment by Serephim** [comment]
Well that explains why I couldn't pop it. :(

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
