### ISSUE TITLE
OOE Inside The Belly fish.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#1307]
There are some fish that can be traded for Inside The Belly that weren't added until 2010 or later. 

[Latest Wiki Entry](https://ffxiclopedia.fandom.com/wiki/Inside_the_Belly)

[Last edit prior to WoTG release](https://ffxiclopedia.fandom.com/wiki/Inside_the_Belly?oldid=293359)

**Comment by Setz0r** [comment]
This was audited and fixed several months ago.
