### ISSUE TITLE
Sprinklers instantly respawning on the way to Suzaku

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1308]
The Sprinklers on the staircase leading to the teleporter to Suzaku Island respawn instantly.

Obviously, they should not be. The Sprinklers on the way to Seiryu behaved normally.

**Comment by HunnyDoo** [comment]
Can confirm this is true, they come out and of the stairs like an infinite conveyer belt. Finally a monk merit camp! (Joking)

**Comment by godmode** [comment]
I was unable to reproduce this. Does this still happen?

**Comment by KnowOne134** [comment]
unable to reporduce either closing issue
