### ISSUE TITLE
Jug pet job traits

### ISSUE THREAD

**Issue by Nimlith** [EdenServer/community#1309]
Doesn't appear that jug pets are getting their respective job traits (for example DA on war pets) https://ffxiclopedia.fandom.com/wiki/Tiger_Familiar

**Comment by Shoruto** [comment]
Connected to #2479 (Killer Effect)

**Comment by Shoruto** [comment]
This is a copy paste of boh1788's report

**Title** - Killer effect not assigned to jug pets #2479

Jug pets do not seem to have killer effects. Spent 4 hours using a crab jug against worm in Qufim without a proc of intimidation. Using natural pets, intimidation worked.

**Comment by 59blargedy** [comment]
resolved december 7 patch
