### ISSUE TITLE
"falls to the ground" instead of "defeated" if a mob is killed by an attack that has additional effect dmg

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#131]
Killing mobs with my thief right now, anytime my sirocco kukri gets the kill shot on a mob, the mob "falls to the ground" instead of being Defeated.

I dunno if this is anything other than a cosmetic issue, but it worries me that it might be causing the mobs to no take TH effect when they die.

**Comment by jmcmorris** [comment]
This is likely because of the wind additional effect killing the mob instead of your dagger hit. I think I know the issue and can fix it (I broke it). Thanks for reporting!

**Comment by gweivyth** [comment]
Does this effect anything other than being cosmetic?  Just wondering.

**Comment by godmode** [comment]
Some things will be left for players to test so we won’t be giving out lots of information of how the bugs might be integrated with other components.

**Comment by Treble011** [comment]
This still exists. I am including a screen shot that shows killing normal or killing by additional effect. Apparently, killing by additional effect doesn't count as killing the monster at all as I got no message or opportunity for loot. I demand my tree cutting, GM.

[http://i66.tinypic.com/4j8c3d.jpg](url)

**Comment by godmode** [comment]
Devs: If someone gets to this before I can test it on an exp mob check to see if you’re getting experience in your status menu after zoning not via chat message.
