### ISSUE TITLE
Earthern Ward removes Sneak

### ISSUE THREAD

**Issue by Eme-FFXI** [EdenServer/community#1311]
Casting Titan's Earthern Ward will remove Sneak (and possibly Invis) from any receiving party member.

**Comment by panfunk** [comment]
Applies to Frost Armor / Aerial Armor aswell

**Comment by ShiyoKozuki** [comment]
Testing this a bit, and without looking at the coding, I think the coding for "Blood Pact: Rage" to remove sneak was simply copy pasted to "Bloody Pact: Ward" and is the culprit.

**Comment by rude-jerk** [comment]
Resolved in patch on December 21, 2020.
