### ISSUE TITLE
Can /ra wihile resting

### ISSUE THREAD

**Issue by Eme-FFXI** [EdenServer/community#1313]
what the title says. Char stands up, shoots, and sit downa gain...

**Comment by marlinla** [comment]
Does it reset resting tick progression? Do you have to wait 20 seconds again to get ticks, or is it uninterrupted?

**Comment by Eme-FFXI** [comment]
no it's uninterrupted

**Comment by Caelic** [comment]
https://github.com/DarkstarProject/darkstar/pull/6328

**Comment by KnowOne134** [comment]
Fixed 11/23 update
