### ISSUE TITLE
Avatars should auto-attack after BPs

### ISSUE THREAD

**Issue by slassen** [EdenServer/community#1314]
When you perform a blood pact on an enemy the avatar should begin auto attacking the mob. Currently it just executes the BP and then idles unless the monster is attacking the SMN.

**Comment by 59blargedy** [comment]
resolved in the March 29, 2021 update

**Comment by roriffxi** [comment]
I'm curious where the research for this bug report came from.

https://youtu.be/KRCnIyoMIao?t=147
https://www.youtube.com/watch?v=_Cynxx4mtCE

The first video was recorded in 2004 (you can see that BPs aren't even separated between rage/ward) and at this specific timestamp you can see Elvira use spinning dive on tiamat and they don't immediately release the avatar and it stands idle for 4-5 seconds without auto attacking despite having just performed a blood pact.  In the second video from 2009 you also see the titan not make a move to close / begin meleeing after the geocrush finishes.
