### ISSUE TITLE
Fomor Hate 

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#1316]
So either some mobs don't give any 'Fomor Hate' or the values are just too damn low.

We spent hours in Sacrarium killing Fomors, made like 15k xp killing them while also doing CoP 4-3 and the msg for my toons was 'Heart racing' before and after the grind. We didn't kill any Tauri during this.

We got to pop the Hume NM and killed it, resetting the hate to 0 as supposed to. Then after around 20 kills, the person that poped still had no 'Goosebumps' when checking the 'Stale Draft'. Took like 10 more kills for the 'Goosebumps' msg to appear.

**Comment by panfunk** [comment]
The fomor in misereux coast seem to grant hate as intended. killing roughly 50 of them put me to maximum hate from 0, according to the 'Hate-check-NPC'

**Comment by Jimmayus** [comment]
Having immense trouble with this as well. We've killed in excess of 20 fomor inside, and around that many outside. I still have level 1 threat. Male Hume if that makes a difference.

**Comment by Gretal1** [comment]
Mithra also seem unable to gain max hate.

**Comment by Slamm21** [comment]
It seems from the darkstar code you do not get hate unless you physically kill the mob, this is definitely not how it was on retail.
I have spent hours subligar farming as RDM and now just checked my hate and it is still 0
