### ISSUE TITLE
Bugard skin

### ISSUE THREAD

**Issue by Redenius** [EdenServer/community#1318]
Bugard skin npc's for the wrong price. It currently NPC's for 210 with fame 4. It should be at least 450 gil. 

Era info below:

https://ffxiclopedia.fandom.com/wiki/Bugard_Skin?oldid=297732

**Comment by Shoruto** [comment]
Can confirm that they changed the price to 210-215 post era.  The era accurate price should be 450-459

**Accurate era price**
https://ffxiclopedia.fandom.com/wiki/Bugard_Skin?oldid=347539

**Post era change**
https://ffxiclopedia.fandom.com/wiki/Bugard_Skin?oldid=751252

**Comment by Volkaru** [comment]
Confirmed this is still an issue for High-Quality Bugard skins, as well. In era they could sell for as much as 1.6k.
https://ffxiclopedia.fandom.com/wiki/High-Quality_Bugard_Skin?oldid=378657

On here currently they're NPCing for 412gil.

**Comment by Novadragon-Siren** [comment]
Here's evidence of it.

https://i.imgur.com/VTpTeFf.jpg
