### ISSUE TITLE
Raging Rush: Possible incorrect parameters

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#1319]
Base DSP's Raging_Rush.lua has an incorrect value for this weaponskill.

params.crit100 = 0.1 should be 0.15.

Sources: ([Wiki](https://ffxiclopedia.fandom.com/wiki/Raging_Rush) , [BGWiki](https://www.bg-wiki.com/bg/Raging_Rush))

Edit: I guess the Str modifier was increased at some point and isn't era.

**Comment by Brachydios** [comment]
the crit mod is out of era. in era raging rush should be increase dmg based on tp.

https://ffxiclopedia.fandom.com/wiki/2007_-_(08/27/2007)_The_Version_Update_has_come!

scroll down to weaponskills will show adjustment

then scroll down to see the title adjustment they made at this time and you will notice wings of the goddess banner in the screenshot.

**Comment by Lilswitche** [comment]
That patch was 3 months before the release of WoTG.

**Comment by 59blargedy** [comment]
resolved in november 23rd update
