### ISSUE TITLE
windurstian consulate npc in bastok

### ISSUE THREAD

**Issue by Tacoxtuesday** [EdenServer/community#1320]
The NPC Lexun-Marixun, W.W. is giving no dialogue.
This is the npc in bastok where windusrtians can get signet or spend Conquest points in the Metalworks

**Comment by ababyduck** [comment]
Not sure if this has been changed since your initial report, but he works fine for me, aside from not recharging rings. You should be able to receive Signet and spend CP.

**Comment by ababyduck** [comment]
Missing EXP band recharge reported in #1478

**Comment by cocosolos** [comment]
This NPC definitely worked a few weeks ago, but as of right now I'm getting no dialogue.

**Comment by bkesecker** [comment]
That is correct behavior.  Make sure your supplies are not 'rotten'.

**Comment by Tacoxtuesday** [comment]
Your findings have nothing to do with the NPC in question. It is not a supply quest NPC, it is for windurstians to spend conquest and get signet in Bastok.

**Comment by bkesecker** [comment]
All conquest NPCs call the same base code, so that all exhibit the need to toss rotten supplies, including this one.

**Comment by cocosolos** [comment]
If that's the case, shouldn't this NPC have disposed of my supplies for me then given normal dialogue? I had to go to a gate guard to dispose.

**Comment by cocosolos** [comment]
Metalworks is missing some IDs, as are a bunch of other zones that can cause crashing if someone talks to a guard with old supplies. See [here](https://github.com/DarkstarProject/darkstar/commit/1a6eaa31d76bf449b91b972142cf815ddda97bfb).

**Comment by godmode** [comment]
Most zones should already have these. Was fixed in a PR with supplies not being removed. However it shouldn’t cause crashing it should give a weird message. Do you have specific missing dialog?

**Comment by cocosolos** [comment]
Almost all the zones with [conquest overseers](https://ffxiclopedia.fandom.com/wiki/Conquest_Overseer) don't have KEYITEM_LOST defined in their ID files. These are used by areSuppliesRotten when removing the key item. I tested the crashing by picking up a supply quest, setting playervar supplyQuest_fresh to 0, and attempting to turn in at North Gustaberg. Got the same crash doing the same thing at the Metalworks consulate. Game server just crashes when you talk to them. I'm not sure why, but not all the zones without KEYITEM_LOST caused a crash, as was the case with the guard in Bastok Markets. Just gives his normal dialogue about setting homepoint. As far as Lexun-Marixun, W.W., CONQUEST isn't defined in the Metalworks ID file so if you have old supplies game server just gives an error about CONQUEST being null and it just returns.

**Comment by godmode** [comment]
North Gusta has it. Copying from mobile.
KEYITEM_LOST                  = 6573, -- Lost key item: <keyitem>.

**Comment by godmode** [comment]
I will check to see if it is not importing the IDs file but I imagine it is. Is anyone else having this problem live?

**Comment by cocosolos** [comment]
I'm sorry the whole crashing thing was on a private test server running stock DSP. I just pushed the KEYITEM_LOST crashing fix there and don't know you may have fixed that already on Eden. At the time of my first comment it seems like I was getting the CONQUEST error that I was able to reproduce on my test server by adjusting the playervars. I've been pretty busy and haven't played recently so idk if that was fixed either and don't have any old supplies.

**Comment by godmode** [comment]
No problem. It was in this patch: https://www.edenxi.com/forums/viewtopic.php?f=29&t=192
