### ISSUE TITLE
Subcrafts at 70, era is 60.

### ISSUE THREAD

**Issue by marlinla** [EdenServer/community#1321]
![image](https://user-images.githubusercontent.com/18357827/54498470-50613c00-48de-11e9-8dd2-520ab0266cd3.png)

I noticed this while AH stalking. The subcraft cap is 60 in era. This person has multiple 70 crafts.

**Comment by tectal831** [comment]
The subcraft cap was never 60, but instead you were allowed 4p points after 60. This meant you could have 2 level 80 crafts, or 4 level 70 crafts. Most people defaulted to 1 lvl 100 craft. Hope this helps
