### ISSUE TITLE
The moonlit path: unable to complete

### ISSUE THREAD

**Issue by Tacoxtuesday** [EdenServer/community#1322]
I have the KI 
![Tacotuesday_2019 03 17_161808](https://user-images.githubusercontent.com/46499148/54499608-e726fc00-48d0-11e9-99c2-27395fc6a34e.png)
But when i talk to the npc it just says  
![image](https://user-images.githubusercontent.com/46499148/54499619-0a51ab80-48d1-11e9-8116-43fda357d675.png)
 and doesn't give me any options.

**Comment by Tacoxtuesday** [comment]
Any update to this? I can't get Fenrir because of this.

**Comment by bkesecker** [comment]
Need to know if you have Key Items: MOON_BAUBLE, all whisper types, TRAINERS_WHISTLE, FENRIR_WHISTLE

**Comment by Tacoxtuesday** [comment]
Ive already completed the fight and have the whisper of the moon

**Comment by Tacoxtuesday** [comment]
i do not have any of the other whispers/bauble as they are consumed.

**Comment by bkesecker** [comment]
Tacotuesday does not have The Moonlit Path flagged in either the current (accepted) or completed state, but was able to obtain the Whisper of the Moon.  In code, it looks like it is possible to obtain the Whisper without flagging the quest.  Will test to confirm soon.

**Comment by icariumkupo** [comment]
Check out my comment in #1120 

Perhaps taco was pulled into the bcnm without having all the entry requirements? Since this is possible on Eden.
