### ISSUE TITLE
Baobhan Sith May Be Broken

### ISSUE THREAD

**Issue by Blex64** [EdenServer/community#1325]
Hard to tell for sure, but just killed PHs for about 3 hours and didn't see a pop. Hard to imagine anyone else kills him with any sort of consistency, let alone right before I was there. Most lotteries I've seen that have been left alone for extended periods of time seem to pop rather quickly, so it certainly appears like something is wrong.

**Comment by Elysien** [comment]
Nothing but RNG, 3 hours is nothing for Sith, partly the reason it's drops are not on the market, it is not uncommon for this NM to take over 6 hours as it's spawn rate is very low and the PH is on a long repop.

As for that thing about leaving stuff alone makes them spawn more quickly; not true whatsoever, more rng.

**Comment by Blex64** [comment]
Updating this: Spent a few more hours today killing PHs and still haven't seen him. I doubt anyone has killed him since I posted this, and as far as I know nobody has seen him at all since he was supposedly moved back to his original spawn location. 

I concede I could be wrong about this and just getting extraordinarily unlucky, but it doesn't seem very likely to me. 

The lotteries popping quickly is purely anecdotal, and blatant speculation.

Has anyone killed him at all since he was moved? Every person who has told me they've killed it did so at it's current retail spawn.

**Comment by Serephim** [comment]
I have literally never got this NM or Ixtab to pop once in dozens of hours of camping each. lol

**Comment by Slamm21** [comment]
I've seen a Cheviot Cape so perhaps he existed at some point?
dsp code says
```
function onMobDespawn(mob)
    dsp.mob.phOnDespawn(mob,ID.mob.BAOBHAN_SITH_PH,5,math.random(14400,28800)); -- 4 to 8 hours
end;
```
I have been here for 8 hours and nothing, and yesterday I was here a few hours also. I have tried both spots but according to the Eden Wiki he should spawn at J7 from the 3 ghosts there.

I think Serephim is right and this NM is broken.

**Comment by Serephim** [comment]
Nah I can confirm it is indeed working, it just took forever for me to spawn it. It's a real whore to spawn. It has an extremely low lottery spawn rate it seems.

**Comment by Blex64** [comment]
From my understanding, he spawns at his current retail location, and not at his "era' location where he is "supposed" to spawn, but honestly, I have no idea.

A developer told me directly on Discord that he moved his spawn to his correct era location, but to my knowledge he has only ever been seen on his retail location. I don't know what to believe at this point, but the lack of clarity around it makes a shitty NM that much shittier.

**Comment by Slamm21** [comment]
So I assume he has been changed to pure lottery then? as I killed them for about 9 hours in the end in both retail and era locations without a pop. If the location was just moved, with the DSP code he would have popped after 8 hours.

Can we get confirmation on whether he pops from the mobs in era location (J7) or retail location (K8)? Eden Wiki says J7 so I am going to go back and assume that for now, but it would be nice for confirmation.

**Comment by icariumkupo** [comment]
Keep killing the 2 ghosts at K8 and he will spawn. I've killed him a dozen times

**Comment by Slamm21** [comment]
Thanks, I have been killing those also for a long time, but will just kill those for now. I have updated the wiki to say K8

**Comment by Slamm21** [comment]
Finally popped, K8 is the right location. Took forever but it does exist

**Comment by Mozzy4Ever** [comment]
@59blargedy Was this closed due to it's spawn position being fixed to era accurate J-7? Or does it still spawn at K-8, the current retail position?

**Comment by 59blargedy** [comment]
it spawns in the correct location of J-7. i made no changes, as that is where it was already coded to spawn.
