### ISSUE TITLE
Cor Hat AF Quest "Against All Odds" Can't Enter BCNM

### ISSUE THREAD

**Issue by Robb083** [EdenServer/community#1329]
The quest seems bugged, I can't enter the battlefield for the fight.  I can select "Against All Odds" on the list of battlefields, but it keeps repeating that I can't enter, try again later.  I'm 100% sure I have all the pre-reqs.

**Comment by panfunk** [comment]
Same problem for me, tried to enter as RDM.
This is what chatlog said: (never seen this kind of msg)
![image](https://user-images.githubusercontent.com/36666121/54640747-d6bd7f80-4a90-11e9-8711-ed44085f69d9.png)

**Comment by Serephim** [comment]
Same here. Just says...
Connecting to server...
Please wait....
You cannot enter at this time, please wait a while before trying again.
Cannot enter no matter how many times I tried.
