### ISSUE TITLE
Lots of EP mobs still aggroing at 75 that shouldn't.

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#133]
Just got aggro from a Yagudo Abbot in Oztroja. Also received aggro from EP goblins in Labyrinth of Onzozo the other day but I forgot to document it at the time.

http://ffxiclopedia.wikia.com/wiki/Yagudo_Abbot

**Comment by gweivyth** [comment]
I remember the EP goblins being aggressive in Onzozo on retail.  It was super annoying.

**Comment by roriffxi** [comment]
I was running around in Ugglypie today and Tonberry Harriers and other 60+ tonberries weren't agroing me even though they should.

its a fine line between too low to agro and just barely high enough to agro.

**Comment by godmode** [comment]
Thanks for reporting. We will probably need to get retails behavior before another adjustment is made.
