### ISSUE TITLE
Ninja's Roll

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#1334]
Ninja's Roll is not providing the correct values. With a ninja in party for the bonus here is the bonuses I was receiving from rolls vs my base evasion. 

Base stats: 
![Y9nx1a3](https://user-images.githubusercontent.com/2160211/54578301-3ce0ce80-49cd-11e9-86d2-a8880262a657.png)

With Ninja's Roll: 

![G7fitcI](https://user-images.githubusercontent.com/2160211/54578304-436f4600-49cd-11e9-9c90-3a445e782a54.png)

**Comment by jmcmorris** [comment]
Hello, can you provide information on what you think it should be - link to wiki(s) is best?

**Comment by Volkaru** [comment]
https://www.bg-wiki.com/bg/Ninja%27s_Roll
Has the proper amounts listed.

**Comment by jmcmorris** [comment]
Those are the buffed versions of Ninja's Roll and are out of era. Unfortunately it appears that no one knows the exact evasion bonus it gave before these changes so the best we can do is make an estimated guess based off of the other roll changes that were made at the same times.

**Comment by Volkaru** [comment]
I edited my initial post, finding the page that lists the old values from before the 2016 buff.

**Comment by AikoSachi** [comment]
http://forum.square-enix.com/ffxi/threads/41814-May-15-2014-%28JST%29-Version-Update

I scoured through all the patch notes in order, this is the very first time that the phrase "Ninja Roll has been adjusted" is seen, if you find anything pre-dating this date that should be the original value.

**Comment by AikoSachi** [comment]
https://www.bg-wiki.com/index.php?title=Ninja%27s_Roll&direction=next&oldid=374698

This post pre-dates that particular patch, but not all the information is listed, unfortunately I have to head to work, but I'll continue my search later tonight on Allakhazam and what not.

**Comment by Volkaru** [comment]
This post has the same numbers, but a filled out chart.
https://www.bg-wiki.com/index.php?title=Ninja%27s_Roll&oldid=381305

**Comment by jmcmorris** [comment]
Here we can see what it was between the two updates: http://wiki.ffo.jp/html/6054.html

I'll accept these as the correct rolls and make the adjustment. Thanks!

**Comment by Volkaru** [comment]
I keep forgetting about that site. I gotta start using it a lot more.

**Comment by KnowOne134** [comment]
Corrected 4/5/2021
