### ISSUE TITLE
Characters receiving different amounts of exp under the same conditions

### ISSUE THREAD

**Issue by kassisaf** [EdenServer/community#1336]
I noticed while dualboxing today that Jody was receiving ~20% more exp than Zuri on every kill.

Party size two, both characters level 75, both characters had Sanction. I tried switching them both between EXP and Limit Point mode and it made no difference.

When Zuri got 31, Jody got 37.
When Zuri got 33, Jody got 40.
When Zuri got 36, Jody got 43.

Every single time.

This was on Lesser Colibri on Wajaom, but another player confirmed that he noticed the same thing with his characters while killing Volcano Wasps in Ifrit's Cauldron.

I couldn't identify a pattern to what may be causing this, but I'm happy to provide any additional data.

**Comment by MGramolini** [comment]
did one of them have refresh or regen sanction?

**Comment by ababyduck** [comment]
> 
> 
> did one of them have refresh or regen sanction?

Nope, both had normal sanction with no added effect.

**Comment by Drognand** [comment]
I saw something similar in a quiff burn pt. My main who was pulling got a chain 5 when the rest of my pets chain reset and only gave them chain 1.

**Comment by InoUno** [comment]
Should be resolved in February 1st, 2021 patch.
