### ISSUE TITLE
Defending Ring does not exist.

### ISSUE THREAD

**Issue by Brachydios** [EdenServer/community#1338]
My linkshell, and the other one have killed countless king b now server has not seen a single ring.

drop rate is fixed at 5% . if the rate is 5% tho then maybe the share pool with piixe ear is not working properly ?

**Comment by Shoruto** [comment]
When you say countless what number would you estimate you are at? Because that defending ring has a really low drop rate and it does shared the same as the p ring making it even harder to get.

**Comment by Brachydios** [comment]
hard to say really but enough that, at 5%, an average would have produced at least 1 ring by now

**Comment by MGramolini** [comment]
There would have to be about 100 kills to be concerned that an item with 5% fixed drop rate hasn't dropped.  I don't think we are there yet.

**Comment by Brachydios** [comment]
5%, or 5 drings in 100 kills on average.

Another way of looking at this is 1 ring in 20 kills for the average. Collectively at the very least we are coming up to 50 king behemoths, especially if you count the ones killed on kupo.

I would just like to request devs re-examine this

**Comment by tectal831** [comment]
This has been tested, and dring does exist.
