### ISSUE TITLE
Blue physical magic accuracy way too low

### ISSUE THREAD

**Issue by BuffaloOnEden** [EdenServer/community#1341]
#1180 and #1070 are on to something, but it goes a little deeper than that. All blue physical spells are suffering from accuracy problems. Blue physical accuracy is supposed to be based on blue magic skill and physical accuracy, but even with capped blue magic, accuracy gear, sole sushi, and full tp, physical blue spells miss much more than they should.

**Comment by kicker300zx** [comment]
I have also experienced this. The damage and accuracy seems way off from Retail. This is the 3rd time i have leveled bluemage. 

Anything i can do to help fix this issue. Please let me know.

**Comment by DrfistMD** [comment]
I provided some details on testing in my ticket #1180 so I won't drone on again here.  But just want to chime in and say something is definitely off with how BLU physical spells are behaving at the moment.

**Comment by VerrenGunnar** [comment]
I lvled in partys from 11ish to 23, and in that all time i can think of only a handful of times where the dmg from my phys spells was more then my swords auto-attack dmg

**Comment by 59blargedy** [comment]
should have been resolved with pdif update
