### ISSUE TITLE
SMN pet bugged when lvling

### ISSUE THREAD

**Issue by CalOmega** [EdenServer/community#1342]
I had carbuncle summoned. Killed a mob to level up from level 5 to 6. I had plenty of mp prior to leveling. Carby was still out, following me around, The pet hp bar was no longer on my screen, I could use assault as if I had a pet out but carby did not respond. I could also cast summon carby without recieving "You already have a pet out." You can verify this in the screenshot between timestamps 20:49:44 to 20:50:20.
![Liv_2019 03 19_205939](https://user-images.githubusercontent.com/47418706/54656186-4da34a00-4a8a-11e9-802a-4ef469b88c31.png)

**Comment by godmode** [comment]
Was this reproduceable when you went from 6-7 or any other leveling up? If not was there anything different that was going on when you leveled from 5-6?

**Comment by 59blargedy** [comment]
havent seen this reproduced, closing for now
