### ISSUE TITLE
[PUP] Valoredge Shield Bash low stun rate.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1345]
Valoredge's shield bash only stuns mobs about 50% of the time. It's supposed to be comparable to the PLD's Job ability, which has a much higher stun rate.

**Comment by Shoruto** [comment]
When the shield bash is being used, whats your level and whats the mobs level because the ability's chance of landing gets reduced as the level between the player and the mob increases.

**Comment by KnowOne134** [comment]
i see at least an 80% chance if not 90%

**Comment by 59blargedy** [comment]
this needs more information/corroboration as i haven't heard this to be a concern and no data has been provided. also would want data on accurate rates if believed inaccurate. welcome to comment with additional data or form a new issue if this remains a problem.
