### ISSUE TITLE
Kuftal Tunnel Coffer Chest

### ISSUE THREAD

**Issue by Novadragon-Siren** [EdenServer/community#1347]
After opening the coffer for the Kuftal map from before, the coffer chest refuses to open. Meaning it will remove my sneak/invis, but I keep the key, no reward.

https://i.imgur.com/s5S42pe.jpg

**Comment by Shoruto** [comment]
Was this the same coffer that you got your map from and didn't despawn or was this a new coffer?

**Comment by Novadragon-Siren** [comment]
New Coffer.
