### ISSUE TITLE
Unable to target worms

### ISSUE THREAD

**Issue by Aeniesh** [EdenServer/community#135]
While soloing as smn, I've noticed that if you sic your avatar on a worm and the worm burrows, the avatar will still attack the worm, but you are unable to target it.

**Comment by Zaekkor** [comment]
Had this happen while in Dangruf wadi. I was meleeing on my two characters and it went under and became untargetable but still could melee me. It doesn't cast spells though.

**Comment by burkewitz** [comment]
I haven’t seen this mentioned anywhere but I was taught yesterday that, atleast if you’re melee (this may work /ma or /ja commands) is simply type /a <bt>. It’s sketch as hell, you’ll have no indication of your target or or it’s health, but you will attack it, and it will die. A reliable workaround while this gets sorted.
