### ISSUE TITLE
Shadowlord can be slept - when woke spams queued abilities

### ISSUE THREAD

**Issue by CdoubleOkay** [EdenServer/community#1350]
When Shadowlord went to phase 2 we immediately slept him (Not sure if he can be slept?) and then upon waking he spammed AOE for what seemed like the amount he was slept for.

**Comment by Aneyus** [comment]
That's normal. He always spams AoE in phase 2.

**Comment by GalkaZajin** [comment]
It was not normal at all. We mean like spam spam, to where he animation locked us so much as we were resting that we couldn't get up and it had already killed a few people. He was slept for about 2 minutes and built up every time he should have aoe'd to use them all at once.

**Comment by CdoubleOkay** [comment]
> That's normal. He always spams AoE in phase 2.

When I say spam, I don't mean the 10s spam. I mean back to back to back to back to back....to back. No time in between

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update

**Comment by CdoubleOkay** [comment]
@59blargedy DOING WORK!!!!
