### ISSUE TITLE
Lamia No.19

### ISSUE THREAD

**Issue by Mikokiko** [EdenServer/community#1351]
https://ffxiclopedia.fandom.com/wiki/Lamia_No.19

We tried to pop this NM, we sacrified (died) my character all over the area indicated in the comments and on the map. We never received the message where it indicate the windows is open. The NM never poped.

Can it be checked to see if it's in game  ?

Thanks!

**Comment by icariumkupo** [comment]
#1203

**Comment by Mikokiko** [comment]
damn didint even pop in search when i pasted it there!
