### ISSUE TITLE
Al Zahbi chocobo issue

### ISSUE THREAD

**Issue by Solisie** [EdenServer/community#1352]
This happened:

- I bought chocobo in Al Zahbi

- I spawned in wajaom entrance as always but without a chocobo

- I ran back to town and I got stuck on loading screen

- I closed the client, when I logged back in I was in Al Zahbi below the floor and stuck.

I just warp scrolled out.

**Comment by triple-lariat** [comment]
Had the same exact series of events happen to a friend today. If it's of any use they were running client version 30181205_0

**Comment by KnowOne134** [comment]
this is caused from a slow connection while zoning
