### ISSUE TITLE
BRD: Changing Instruments resets TP; did not do this on retail

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#1353]
Edit: Beauxq provided a link with Kupo fix; see below for details - 
https://github.com/EdenServer/community/issues/1353#issuecomment-475716383

My TP resets whenever I change instruments for a different song (i.e., switching from Cornette +1 to do minuet then doing elegy and changing to horn). However, it did not do this on retail. I mentioned this in my LS and someone stated it did this on Nasomi, but I was pretty certain it didn't do this on retail. 

I found a video of a bard fighting Maat in 2007 to support this: 

https://www.youtube.com/watch?v=1DL6ewvrYFA&feature=youtu.be&t=173

I've skipped ahead in the video, but you can clearly see that the bard has TP, which does not reset upon changing instruments for elegy and mambo. 

Thanks!

**Comment by Shoruto** [comment]
I found on BG Wiki, you will lose TP when changing out Main/Sub/Range slot items.  This would include Instruments.

TP is lost when you equip something from your main/sub/ranged slots or de-equip something from main/sub slots. 
https://www.bg-wiki.com/bg/Tactical_Points

Unsure on the video, something might be affecting the tp when switching instruments.

**Comment by roclm** [comment]
That was my initial reaction as well, but Bard instruments appear to be an exception to the rule. 
The first post on this page for a DD BRD guide on FFXIAH references this behaviour:
https://www.ffxiah.com/forum/topic/46553/military-parade-a-dd-bard-guide/8/
"

> "You can't switch instruments when fighting! You'll lose TP!"
> 
> This statement is false.
> 
> You may keep your TP if you:
> ♪ Equip into an instrument.
> ♪ Equip into an ammo piece.
> ♪ Unequip an ammo piece entirely.
> 
> You may not keep your TP if you:
> ♪ Unequip an instrument entirely.
> ♪ Equip into a ranged weapon.
> ♪ Unequip a ranged weapon entirely. "

The easiest way to see would be if someone has a retail account with Bard leveled. This feels like something that would've easily slipped through the cracks.

**Comment by Shoruto** [comment]
The interesting thing about that argument is don't you actually "unequip" the previous instrument in order to make a slot available for your new instrument?  You can't equip something without unequipping the previous one, unless that slot was previously empty before equipping an instrument.

Based on what I'm reading, if you have TP when you equip an instrument for the first time with the slot being empty prior to, you should keep your TP but if you had an instrument in that slot before then you would lose TP.

**Comment by MGramolini** [comment]
No, you don't unequip something "entirely" unless you take it off or use the unequip command.  You can equip over existing gear and the game "replaces" that equipment.

**Comment by roclm** [comment]
You don't unequip your instrument anymore than you unequip any piece of gear when you swap? I don't understand what you're saying. Here's another video example of a BRD Maat fight including a person swapping instruments appropriately (including from wind->string):
https://www.youtube.com/watch?v=UjG5NeHu3ws

I honestly just think Bard Instruments are the exception to the rule when swapping your "Ranged" slot equipment and shouldn't zero out TP.

**Comment by Shoruto** [comment]
Gotcha, I understand

**Comment by setsuk0** [comment]
I beat Maat on BRD in 2004 on my second character and again a few years later on a third character. Changing instruments did not reset TP. This particularly stuck out to me because I felt like I would have remembered if using my regular macros would have reset my TP whenever I was running around playing with a Joyeuse, but this was never an issue on retail since TP did not reset. 

Here's a video from 2006 showing instrument switch and no reset of TP: 

https://youtu.be/8iUsPVgUa_8?t=102

I could dig up more if needed, but I'm positive instruments were an exception to this rule.

**Comment by beauxq** [comment]
We fixed this on Kupo. Here's a diff for the older Kupo version of DSP. It may be outdated.

https://github.com/bdhs/darkstar/commit/7f2901a8ae733de1e52f01e08ed2867333b78d9c

The second section shouldn't be called without an item for `PItem`, but it might be safer to check for the null pointer, changing that line to something like:
```
    if (equipSlotID != SLOT_RANGED || PItem == nullptr || PItem->getJobs() != 512) {  // not instrument
```
so it can short-circuit that dereference if it's null.

**Comment by beauxq** [comment]
@setsuk0
You might want to add this link to the top post to make it easier for people to see there's a fix for it.

`https://github.com/EdenServer/community/issues/1353#issuecomment-475716383`
