### ISSUE TITLE
Stuck on Selbina boat

### ISSUE THREAD

**Issue by Darcatvar** [EdenServer/community#1354]
Character (Darcatvar)is stuck on the boat and every time I log in the game crashes. Not sure what to do.

**Comment by godmode** [comment]
You should be good to login in Selbina now.

**Comment by Darcatvar** [comment]
Thank you sir. Should  I not be riding the boat like retail?

**Comment by godmode** [comment]
@Setz0r is working on this I believe. I’m not sure what happened exactly. He might chime in here.
