### ISSUE TITLE
Tachi: Y/G/K

### ISSUE THREAD

**Issue by Elysien** [EdenServer/community#1355]
Short story: they are too weak.

Long story: I'm not sure if this is a problem with Tachi: Yukikaze/Gekko/Kasha itself, or possibly the atk/def formula or something else, but ask most SAM and they will tell you these WS are very much weaker than they remember.

Today I decided to get a look at how it performed against Fafnir, as I'm very familiar with fighting this NM as Samurai in the era and, to my dismay; it was abysmal. In what is mostly 'best in slot' equipment, mostly fully merited and atk food, my Tachi:Gekko were doing an astounding 60-250 damage. My critical hits would sometimes deal more damage, pretty depressing--especially after putting a lot of effort into maximizing the job.
 It isn't just limited to Fafnir either, vs Sky gods while buffed to the balls with brd/cor, /war with atk food I'm looking at 400-500 Tachi:Gekko. 

It was difficult to find some retail era videos of SAM dmg vs this stuff without filters on, but I did find something briefly against Nidhogg, a beefier Fafnir.

https://www.youtube.com/watch?v=75OhISFURqk&t=110s

Starts at 0:55 seconds, we see "Tankk" using a Yuki for 617 damage, then a Gekko for 995. I wouldn't be able to get even close to these numbers even if I did a Sneak Attack Gekko that also scored a double attack! And this was on Nidhogg, not even Fafnir.

Can't really see his gear, but as I pretty much have as good as it gets for the most part bar a few minor slots it doesn't really matter what he has--he doesn't have the relic weapon, looks like Hagun but it might not even be. The author of the video is in the same party as him too and you can see they aren't getting buffed to the balls, in fact they're barely buffed for damage output.

**Comment by Aneyus** [comment]
Cosigned, another era SAM main.

**Comment by godmode** [comment]
Is this an issue with just these weaponskills or are other weaponskills underperforming on the mobs you are basing this off of as well?

**Comment by Aneyus** [comment]
My initial guess would definitely be the mobs' defenses being too strong in some way rather than the weaponskills themselves being too weak. Other WS also perform unexpectedly poorly against Fafnir/Nidhogg. Need further testing against other HNMs but I'm usually stuck on PLD instead of SAM :P

**Comment by godmode** [comment]
Enemy TP gain has been adjusted and it seems to be era accurate. May be worth bringing additional melee to test it and normal damage now.

**Comment by Aneyus** [comment]
For other mobs I'll certainly make the effort to get some testing in, but we bring melee to every faf and it is 100% not taking accurate damage from melee. Double digit Raging Rushe and Tachi:YGK are common =/

**Comment by godmode** [comment]
What about normal hits? Do you have recorded data on that? Maybe some screenshots or a recording? I imagine the above video has some numbers for normal hits too. Those would be more indicative of defense values since there are just so many more of them.

**Comment by montijin** [comment]
Its an issue with all physical dd from what I can tell. A lot of the posts through this thread do not have context for buffs/tp returns so its kind of hard to tell what buffs, da/ta procs they had but the numbers here are so staggeringly different that its pretty obvious something is up with formulas. 

https://www.bluegartr.com/threads/39766-Fapworthy-WS-SC-or-MB-dmg

Here is just an example of something in the thread from 2006
![Spik3DMG](https://user-images.githubusercontent.com/2160211/54752164-1d9f9800-4bab-11e9-9dd4-f9172072e5b4.png)

**Comment by Godlylegato** [comment]
![Limlight_2018 11 04_213005](https://user-images.githubusercontent.com/37812880/54752648-49c01680-4bb5-11e9-87c5-3564b260ec27.png)

this was before the dsp merge which changed hnm p. def to what it currently is (broken) 

i'm lucky to break 300 now. march/minuet, berserk, 2hour, war charge, no dia2. 

you guys had adjusted hnm p.def to be more melee friendly. during this time i could keep up with our blm, now i have no chance in hell. 

the same with kb. 700+ slug shots (double minuet, dia2), now sub 300. no one brings rng to kb anymore. we're forced to sc+mb and put blm in every party slot. i'm lucky to break 150+ on nid. i just play rdm for khim, no point to bring anything that isn't smn.

**Comment by Serephim** [comment]
Agreed. There is no reason to even use physical damage on HNMs anymore because the damage output is so trash. Especially Ranger where you are literally throwing money at the mob to do pitiful damage. lol

**Comment by godmode** [comment]
I see a lot of hits for 0s in that era video. Maybe wings are up. I’ll research as well but if you guys have any more videos for me feel free to post them. It may speed up the process.

**Comment by montijin** [comment]
There is a couple of weaponskills in this video on wyrms from 2005.
https://www.youtube.com/watch?v=8NzoD6SdE9A
![u1o89K9](https://user-images.githubusercontent.com/2160211/54754550-be915180-4bb1-11e9-9793-d245544a3dc8.png)
![bOCfl5A](https://user-images.githubusercontent.com/2160211/54754601-dff23d80-4bb1-11e9-997b-8f1093f6eb20.png)
![8MxED9Q](https://user-images.githubusercontent.com/2160211/54754651-fef0cf80-4bb1-11e9-938b-1984432414dc.png)

**Comment by Elysien** [comment]
> I see a lot of hits for 0s in that era video. Maybe wings are up. I’ll research as well but if you guys have any more videos for me feel free to post them. It may speed up the process.

Awesome dude, thanks! And thanks everyone for chiming in!

**Comment by phobos1234** [comment]
This website has a TON of era content.

https://kanican.livejournal.com/12475.html

Plenty of videos and materials here, although they also mana burned many of the mobs.

**Comment by Gretal1** [comment]
Could it also be that YGK are not getting their natural attack boost?

**Comment by Brachydios** [comment]
The lua for these ws as far as I can tell look correct but I could be wrong.

**Comment by ccl085** [comment]
if anyone has acces to retail, going there  and testing HNM defense(at least for Kings) should be easy since they are pop item now and their stat did not change since lvl 75 era.

**Comment by Setz0r** [comment]
i have a 75 sam on retail with moderate gear.  i will see about grabbing another of the devs on his 99 and go give em a try.

**Comment by MGramolini** [comment]
Any news on this?

**Comment by montijin** [comment]
Is this being worked on??? It's really disappointing that after all this time the entirety of endgame hnm and sky is still tiptoeing around busted pdif by using other inaccurate damage formulas.

**Comment by godmode** [comment]
Some R&D has been done. If you have anything further to contribute to resolve the issue please reserve comments to that rather than bumping. I know Setzor has solicited help on more than one occasion. You can keep an eye on the testing-123 Discord channel.

**Comment by TheKingOfJeuno** [comment]
i read the OP and i agree with this

Co-signing this from Samuraijake

might even stream the issues with Y G K

**Comment by Mozzy4Ever** [comment]
Pretty sure this was fixed with pDif changes

**Comment by Slamm21** [comment]
it was, closing.
