### ISSUE TITLE
Bard Resistance songs

### ISSUE THREAD

**Issue by Snapplecracker** [EdenServer/community#1356]
The bard songs that raise resistance against certain status ailments don't seem to be working correctly, I have 4 or 5 of them and none of them are casteable, they all say you cannot cast <spell name> 

Shining Fantasia, Scops Operetta, Faul Abaude etc.

I've asked other bards but they didn't have them or didn't respond, I checked clopedia history and there doesn't seem to be any special casting conditions

**Comment by Tjonke** [comment]
I can attest to this as well, no resist status song as able to be cast. Known DSP issue and has been as long as I can recall and that is over 3 years playing BRD on Nasomi.

**Comment by godmode** [comment]
Are you able to cast it using text commands? This seems like a fairly easy fix if not able to that way either.

**Comment by Snapplecracker** [comment]
Cannot cast with text commands, tried a few and it gives the same results

**Comment by theseraphgabriel** [comment]
Can also vouch for this as Herb Pastoral doesn't work for me.
It does nothing at all.

**Comment by Setz0r** [comment]
from the little bit of retail testing Wiggo and I performed, most of the bard song formulas are just made up out of thin air here.  the amount of testing just for 1 song takes several hours.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
