### ISSUE TITLE
Lv70+ Fomor Pets in lufaise

### ISSUE THREAD

**Issue by HunnyDoo** [EdenServer/community#1357]
The fomor pets on the watchtower at H-8 in lufaise are significantly stronger than the fomors that summoned them.

(sorry for jank printscreen/paint picture, cant save ingame screenshots due to installation error not making a screenshot folder)

![Fomor lvl](https://user-images.githubusercontent.com/46686806/54753599-6fe2b800-4baf-11e9-95d8-e5d45e222976.png)

**Comment by Shoruto** [comment]
Did you actually kill them to see if they give the exp for that /check level or did you just /check them?  Need to make sure it's not a mis wording vs a wrong difficulty level setting.

**Comment by HunnyDoo** [comment]
I killed the elemental and it gave 54 exp at lv75 and dropped a kindred seal.  Also it spammed flare and fire 3 the whole fight.  That little guy is the biggest badass in tavnazia.
