### ISSUE TITLE
Xolotl didn't spawn in 24hours

### ISSUE THREAD

**Issue by Altnob** [EdenServer/community#1358]
Just camped xolotl for 24 hours and he didn't spawn once. I have not logged out, I'm standing at E7 where he spawns in retail and he didn't spawn.

**Comment by icariumkupo** [comment]
#355 

This NM hasn't spawned in months

**Comment by Altnob** [comment]
Yea, I read that issue and saw that  it was fixed which is why I committed my time to getting a ToD. Looks like I got honeydicked.

Mods please respond.
