### ISSUE TITLE
Avatar not heeling

### ISSUE THREAD

**Issue by Aeniesh** [EdenServer/community#136]
Noticed after an avatar kills a monster, majority of the time it will not return to the smn's side. Also noticed that the avatar will not heel when retreat is used.

**Comment by gweivyth** [comment]
Need more info on this one.  When you use retreat, does it at least stop attacking the mob it is currently attacking?

**Comment by Aeniesh** [comment]
I've had my pets just sit where they were.

**Comment by Serephim** [comment]
This was really bad in promyvions. Pet would just sit still after a kill and not move. Would also get stuck on the sides of the maps and on objects. I haven't had much of a problem elsewhere with it though.

**Comment by godmode** [comment]
Duplicate of #438
