### ISSUE TITLE
Crane Fly poison from Venom needs adjusting.

### ISSUE THREAD

**Issue by CalOmega** [EdenServer/community#1360]
Crane Flies in Meriphataud Mountains land 4hp/tic for 1min duration Venom. The flies are EM/T to me. I don't have any evidence if this was the same in retail but 240 damage to a player with a total 313 hp seems a bit over powered.

**Comment by erenik** [comment]
The poison breath from Lizards in dunes is also overpowered, 4 hp per tic there is much more than retail. Wiki says "Poison proportional to Lizard's level.", so perhaps it should be re-adjusted to something like 1 + (monster level / 20) per tick? I can imagine it being higher damage in end-game, but early game it is fatal, and I have never been on the white mages so much to Poisona when playing in retail earlier.

https://ffxiclopedia.fandom.com/wiki/Plague_Breath

**Comment by godmode** [comment]
When I was starting out in retail I would die frequently at near full health from lizards, fungars, or crawlers pending where I was starting out at. Just because it’s a long duration doesn’t mean it’s overpowered. It may be but I would find a source to back it up with.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
