### ISSUE TITLE
Item on AH disappeared

### ISSUE THREAD

**Issue by Alirio926** [EdenServer/community#1361]
I put a scroll of shell to sell on AH and at the same time it disappeared. Just now. I got a SS.

**Comment by godmode** [comment]
Are you able to post it?

**Comment by Alirio926** [comment]
![Squallbr_2019 03 21_205418](https://user-images.githubusercontent.com/25528593/54793614-f637e200-4c21-11e9-9150-3d484436cfc3.png)

I buy the scroll on NPC and put on AH, imetiade he disappeared, i run to delivery but not show gil. no history, nothing.

**Comment by Alirio926** [comment]
I removed a bomb ash from AH and shell show on list .

**Comment by GalkaZajin** [comment]
This is normal if you have more than 7 items up on AH. You can only see your first 7 listed. If you list more than 7, they are there, no need to worry.
