### ISSUE TITLE
Out of Era WHM spell Sacrifice Available in AH

### ISSUE THREAD

**Issue by Gavilrain** [EdenServer/community#1362]
Going through the AH I came across the WHM spell Sacrifice.  It didn't look familiar to me so I checked  the Wiki and seen it didn't get introduced to the game until 2009.

Scroll is a drop from Goblin Alchemists in various locations.  Loot table to said monster may need to be adjusted. 

EDIT:  The WHM Scroll of Auspice is also available on the AH with 12 on hand, This spell was also not era and was introduced in 2009 the same as Sacrifice.  

Wiki says it's a drop from various monsters or sold from Brave Ox in Rabao

**Comment by ababyduck** [comment]
I submitted a partial fix which corrects Brave Ox's shop inventory compared to base DSP, but I should have verified this was even necessary first, as it's already been taken care of on Eden live.

Have you confirmed that Goblin Alchemists are still dropping this? I recall them dropping on Kupo at one point, but they were never usable and I believe they were eventually removed.
