### ISSUE TITLE
Wading Beasts (Bastok Mission) Not Repeating

### ISSUE THREAD

**Issue by Grayrail** [EdenServer/community#1364]
Looks like Wading Beasts is not repeating.  I just completed Rank 2-3 Dragon and I wanted to build up my Rank Point Bar so I can work to accept  the next missions.  I remember building rank points by doing the Wading Beasts over and over instead of using crystals.  Is this not the case on Eden?
![Grayrail_2019 03 22_013850](https://user-images.githubusercontent.com/48819078/54803254-247ae900-4c45-11e9-8dee-652dbd203394.png)
![Grayrail_2019 03 22_013856](https://user-images.githubusercontent.com/48819078/54803258-2775d980-4c45-11e9-9c4d-416df02bcd6b.png)
![Grayrail_2019 03 22_013936](https://user-images.githubusercontent.com/48819078/54803261-2a70ca00-4c45-11e9-84bd-77266ef5a34f.png)
![Grayrail_2019 03 22_014204](https://user-images.githubusercontent.com/48819078/54803263-2c3a8d80-4c45-11e9-8ab1-ab23f6d7c9fd.png)
![Grayrail_2019 03 22_014213](https://user-images.githubusercontent.com/48819078/54803265-2f357e00-4c45-11e9-9d7e-96f2cec413f5.png)
![Grayrail_2019 03 22_014225](https://user-images.githubusercontent.com/48819078/54803266-30ff4180-4c45-11e9-9807-01702b574283.png)

The second to last picture is after I tried trading the lizard egg to Alois and it wasn't accepted.  The last picture is to double check that the mission is not current (should it be? or always show as completed?)

Thank you for your reply.

**Comment by 59blargedy** [comment]
can't find an issue here, am able to get the mission again, have it showing in current and completed missions, and can re-complete the mission. assume solved over the years at this point
