### ISSUE TITLE
Incorrect Skillchain

### ISSUE THREAD

**Issue by RamboEden** [EdenServer/community#1365]
**Spinning Axe** > **Blade: Jin** gives _**Detonation**_  but it should give **_Fusion_**

**Spinning Axe** properties
(A) _**Liquefaction**_  (B) **_Scission_**

_**Blade: Jin**_ properties
(A)_**Detonation**_ (B)**_Impaction_**

Skillchain should be like
**Spinning Axe** (A) _**Liquefaction**_ > **Blade: Jin** (B)**_Impaction_** = **_Fusion_**

but instead its doing
**Spinning Axe** (B) **_Scission_** >  **Blade: Jin** (A)_**Detonation**_ = _**Detonation**_

**Comment by erenik** [comment]
Incorrect. The A-properties are always prioritized based on the closing WS. It is thus the Blade: Jin's A-property which is prioritized, giving it the correct Detonation SC.

**Comment by RamboEden** [comment]
I believe skillchain priority is based on skillchain level Detonation is level 1 and fusion is level 2
i double checked with 2 different skillchain calculators and they both resulted in Fusion.

**Comment by RamboEden** [comment]
There is another thread for skillchain issue with different weapon skills
Duplicate of #69

**Comment by erenik** [comment]
I am unsure after checking the calculators, indeed, and was mostly going from experience that it seemed as if it was prioritizing the A-properties. I have never felt that it prioritized level 2 over level 1 just like that.

**Comment by 59blargedy** [comment]
this was resolved in 5/16/20's patch, just needs to be added to notes
