### ISSUE TITLE
Like A Shining Subligar (Norg quest dialog)

### ISSUE THREAD

**Issue by Novadragon-Siren** [EdenServer/community#1369]
Heiji is saying Rusty Subligaria, not Rusty Subligar.

https://i.imgur.com/RfmHzDt.jpg

**Comment by erenik** [comment]
Subligaria is plural. See description in https://ffxiclopedia.fandom.com/wiki/Like_a_Shining_Subligar and https://en.wiktionary.org/wiki/subligaria
