### ISSUE TITLE
Latent on the Senjuinrikio not Functioning

### ISSUE THREAD

**Issue by LokiStinkpalm** [EdenServer/community#137]
So i got a Senjuinrikio before Kupo went down, broke the weapon with over 600 ws points (it needs 500 to break), and the latent isn't functioning properly.  submitting a screenshot of /checkparam with a fudo/fudo & fudo/Senjuinrikio and that stats are exactly the same.  If its working, then the damage on the offhand should have been lower than the main hand.

First stats on the /checkparam are for fudo/fudo and second stats are fudo/Senjuinrikio

![loki_2018 10 10_202539](https://user-images.githubusercontent.com/43826696/46779182-90871780-cccb-11e8-9c1e-1b314a8ae5b0.png)

**Comment by Aneyus** [comment]
Checkparam doesn't have anything to do with DMG though. It shows you your attack which is only based on your skill with a given weapon and your gear. This is not conclusive.

**Comment by Setz0r** [comment]
This latent is working
