### ISSUE TITLE
Computer freezes when selecting a starting city

### ISSUE THREAD

**Issue by dal5ton** [EdenServer/community#1370]
Computer freezes when selecting a starting city during character creation.

**Comment by dal5ton** [comment]
I can log into an account with a charter already made no problem. But cannot create a new character on my buddy's new account

**Comment by godmode** [comment]
This is most likely an issue with your computer and the settings ffxi has. Try looking for this issue in tech-support channel in discord. Iirc it had some checkbox you had to uncheck like simple character creation.

**Comment by dal5ton** [comment]
This did not work. We found that setting in ashita. Honestly not a big deal, I can make his toon on my computer, just thought you should be aware in case it affects others
