### ISSUE TITLE
Chestnut Club Desynthesis missing

### ISSUE THREAD

**Issue by HenryKari** [EdenServer/community#1372]
Using a lightning crystal on a Chestnut Club results in synthesis canceled, because the combination of material cannot be synthesized. This desynthesis is supposed to yield a piece of chestnut lumber.

**Comment by Shoruto** [comment]
Can confirm this is during era and should produce 1 chestnut lumber (Yield and HQ1) or 1 bird feather (HQ2) with lightning crystal

https://ffxiclopedia.fandom.com/wiki/Chestnut_Wand?oldid=318567
https://ffxi.gamerescape.com/w/index.php?title=Chestnut_Wand&oldid=864731
http://ffxi.somepage.com/itemdb/579

**Comment by HenryKari** [comment]
Chestnut **Club**, not Chestnut Wand

**Comment by Shoruto** [comment]
Bah, not sure how I got wand from club lol.  Thx for the correction

**Comment by Shoruto** [comment]
Lets make this more accurate this time *disappointed*

After browsing my resources I have found no desynthesis recipe for Chestnut Club during era.  I believe the message you received would be accurate, it.  The earliest evidence that shows a recipe is November 2, 2008.  

**During Era**
https://ffxiclopedia.fandom.com/wiki/Chestnut_Club?oldid=318566

**Post Era**
https://ffxiclopedia.fandom.com/wiki/Chestnut_Club?oldid=711756

**Other resources showing no desynthesis for the Chestnut Club during era**
http://ffxi.allakhazam.com/db/item.html?fitem=934#Desynthesis
http://ffxi.somepage.com/recipedb/woodworking-desynth-1.php
http://ffxi.somepage.com/itemdb/3403

**Comment by HenryKari** [comment]
I see. Thanks for doing the research. Perhaps this is then working as intended.
