### ISSUE TITLE
Lost the Elshimo Lowlands Outpost Warp

### ISSUE THREAD

**Issue by Avaataru** [EdenServer/community#1374]
I no longer have the Elshimo Lowlands outpost warp on my character Man. I got his Kazham keys and flew him out there to get it on 3/16 so I could take him there to fish, and he doesn't have access to it on Jeanvirgaud now. (I know the date because I took a screenshot of him on the airship to Kazham at the time)

![Man_2019 03 16_110700](https://user-images.githubusercontent.com/48400114/54872586-7033ac80-4d83-11e9-9e81-127ca893db47.png)

**Comment by Virtuekupo** [comment]
Pretty sure Man isnt high enough level to outpost to elshimo lowlands since his highest job is 16, he wont offer the teleport to anyone under lvl25 even though you already did the supply run.

**Comment by Avaataru** [comment]
You're right, that's absolutely why. I thought it would still show in the list, but give an error about level limitation when you tried to select it. Thanks!
