### ISSUE TITLE
Silk Caterpillar NM always up in Rolanberry F.

### ISSUE THREAD

**Issue by RottenUnagi** [EdenServer/community#1375]
Silk Caterpillar is the crawler NM involved in the Bastok quest: [Fear of Flying](https://ffxiclopedia.fandom.com/wiki/Fear_of_Flying). It should spawn automatically in Rol. Fields every time the Bastok airship flies to Jeuno, and despawn on the airship's return trip. I've passed by there a handful of times and he's always been up. The last time I observed for a space of about 16min to rule out coincidence, and he never despawned during that time.

![silk_caterpillar_duration](https://user-images.githubusercontent.com/48870729/54873641-070e6200-4da0-11e9-976d-b65ee0884698.jpg)
Per the wiki:

"Spawns when the Airship flies by overhead towards Jeuno - _every 11 minutes_ - and will despawn after the airship flies back overhead towards Bastok if left unclaimed."

**Comment by KnowOne134** [comment]
must work correctly now, tested locally and on test server, spawns and despawns
