### ISSUE TITLE
There can be only one (ram spawn in Konschtat Highlands)

### ISSUE THREAD

**Issue by RottenUnagi** [EdenServer/community#1376]
A couple of times I've been out farming Tremor Rams in Konschtat. There should be 2 separate rams just like in La Theine. One spawns toward the Valkurm zone around G-5, and the other should be around the west/southwest side of the crag, but so far I've only ever seen the one at G-5, even when I'm the only on in zone. I walked around the whole zone with my alt meanwhile and couldn't find a second ram anywhere. I did not have widescan but they should be fairly easy to spot without it. The HQ1 (Rampaging Ram) eventually popped in place the G-5 ram over at the SW corner of the crag roughly around where the 2nd NQ ram should be found. After killing it the G-5 ram continued to spawn as normal, but still no sign of the other.

**Comment by bkesecker** [comment]
Observed this behavior as well.

**Comment by rujind** [comment]
The HQ was up, which is normally the case.

**Comment by Solisie** [comment]
Now the one in H-5 is spawning but the one in G-5 isn't and there isn't any NM's to speak of!

**Comment by Kortex76** [comment]
Today, July 27 2019, I have been camping 1 hour at the H-7 spawn zone (near crag of Dem), with widescan, and no Tremor ram pop or NM at this location. I really don't think this is a normal behaviour.

**Comment by Raulfin** [comment]
For the last 3-5 weeks now only 1 ram has spawned in each of the highlands and la theine. The west ram in both zones no longer spawns.

**Comment by tigo9** [comment]
it's glitch spawning at 0,0

if you look you might find it under the map with /wireframe

**Comment by 59blargedy** [comment]
resolved 11/16
