### ISSUE TITLE
Quest "You Call That a Knife?" won't flag

### ISSUE THREAD

**Issue by RottenUnagi** [EdenServer/community#1377]
With higher than rank 6 fame in Kazham neither of my characters can begin this [quest](https://ffxiclopedia.fandom.com/wiki/You_Call_That_a_Knife%3F). I get no response from NPC Mhebi Juhbily when trading her a sandfish. No prerequisite quests required for this quest.

edit: Is verified era appropriate as of Oct. 17 2005 on wiki

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
