### ISSUE TITLE
Aspir Quest:

### ISSUE THREAD

**Issue by mpinholster** [EdenServer/community#1378]
I did the Aspir quest on 2 characters and both characters still have their Test Answers.

I don't think this is WAI?

If this is OK, can I sell the Test Answers?

I don't want to cheat.

**Comment by godmode** [comment]
Thank you for your honesty. It was missing trade complete code. I’ve added that in now.

**Comment by bkesecker** [comment]
Godmode, did you make this change live?  Might be causing https://github.com/EdenServer/community/issues/1424

**Comment by godmode** [comment]
I did and it does. I’ve already edited it back. Not sure why the answers weren’t removed On this ticket.

**Comment by KnowOne134** [comment]
Duplicate
