### ISSUE TITLE
CoP 3-3 - Mimeo Jewel not reattainable

### ISSUE THREAD

**Issue by nekozuko** [EdenServer/community#1379]
After killing the NM at the Loose Sands, I received the key item "Mimeo Jewel". Our party had issues climbing the mountain and took longer than 30 minutes. We never got any warning messages along the way. When we got the top, we obtained the key item "Second Mimeo Feather." "The Mimeo Jewel has grown dark and shattered." So we went back down to kill the NM and tried to get a new Mimeo Jewel to climb under 30 minutes. When clicking on the Loose Sands we do not get a new key item, we only get System Message: Ok. We tried logging off and logging back in and doing it again with the same system messsage. After attempting to climb anyways, we get to the top and get the same "The Mimeo Jewel has grown dark and shattered" 

We are stuck on CoP 3-3 now.

**Comment by whiskeyhughes** [comment]
![image](https://user-images.githubusercontent.com/24579922/54875260-faa2fd00-4dd1-11e9-8ebd-87383372dfd2.png)

![image](https://user-images.githubusercontent.com/24579922/54875270-1dcdac80-4dd2-11e9-82ed-b5b3e581d84a.png)

**Comment by whiskeyhughes** [comment]
The characters affected are Hellvan, Mytrans, Tookosoko, Zuri, Nekozuko, and Musubi.

**Comment by whiskeyhughes** [comment]
I also just talked to Yoran - Oran to see if we could still complete the Mission and I couldn't.

**Comment by bkesecker** [comment]
This seems like a higher priority issue since it is Mission related.  As soon as I finish what I am working on, I will self assign if still unassigned.

**Comment by whiskeyhughes** [comment]
Thanks!

**Comment by ababyduck** [comment]
#1138 Should be addressed at the same time.

I've spoken with @godmode about fixing this, just waiting for him to remember to send me the relevant NPC scripts some time after work and before sleep ;). Should be a quick one.

**Comment by ababyduck** [comment]
A fix has been tested and submitted for review. If approved it should close #1379 and #1138, as well as a few other undocumented issues related to this leg of CoP M3-3. Players affected by this issue should be able to pop the NM again and proceed as expected without any GM interaction.
