### ISSUE TITLE
Can't leave with boat first try

### ISSUE THREAD

**Issue by Darcatvar** [EdenServer/community#1384]
While riding the boat from mhaura to selbina I have almost every time not been able to take the first boat that comes. It will leave without me and say I don't have a permit. Second try works most of the time.

**Comment by panfunk** [comment]
From Mhaura there are 2 different Ferrys, one to Selbina, the other to Aht Urghan Whitegate, maybe you took the Ferry to Whitegate on these occasions without the necessary Boarding Permit KI?

**Comment by Darcatvar** [comment]
oh god, I forgot about the second boat.
