### ISSUE TITLE
Ferry Selbina-Mhaura, possible Pirates issue

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#1385]
I was trying to do the quest 'The Sand Charm' which requires a drop from mobs that spawn during pirates attack on the ferry.

I took about a dozen rides when suddenly both my toons got warped from Selbina to Mhaura after the ferry departed.
![Chan_2019 03 24_213010](https://user-images.githubusercontent.com/36666121/54886327-2e8c2a00-4e87-11e9-8f06-0939972a83b4.png)

Notice how my second toon is still shows as on the ferry in party box.

After this I decided to split up my toons, so one each is on the ferry Mhaura-Selbina, Selbina-Mhaura at the same time, until I crashed on Pan after the ferry departed. After being stuck on 'downloading data' screen I managed to relog still on the ferry and crashed again right away.
This second issue sounds similar to this bug report: https://github.com/EdenServer/community/issues/1363#issue-424045124

Edit: After the ferry arrived in Selbina, Pan is still logging in onto the ferry and crashing, as described in above bug report.

I suppose this might be related to the pirates event.

**Comment by RAllessi** [comment]
Wasn't doing the above-mentioned quest, but I too am stuck in a crash loop due to the ferry. Character name is Kaddis. 

Issue: Game crashes as soon as I log in, which shows my character on the ship from Mhaura to Selbina.

**Comment by Alirio926** [comment]
I'm keep:
Issue: Game crashes as soon as I log in, which shows my character on the ship from Mhaura to Selbina.

**Comment by panfunk** [comment]
Is it possible to confirm / deny that this bug is related to the 'Pirates' Event please?

**Comment by godmode** [comment]
We believe it is related. But we need more digging

**Comment by panfunk** [comment]
Okay ty, then I will stop looking for them for now!

**Comment by Setz0r** [comment]
This has been fixed and is indeed working.
