### ISSUE TITLE
Can access non-RDM Sword Weaponskills without the required subjobs

### ISSUE THREAD

**Issue by erenik** [EdenServer/community#1386]
Noticed this with Red Lotus Blade, which should require Paladins, Blue Mages, Warriors, and Dark Knights main or sub jobs to use, see: https://ffxiclopedia.fandom.com/wiki/Red_Lotus_Blade?oldid=768665

The same applies to Seraph Blade and Vorpal Blade, which I would guess have similar issues right now. 

Seraph blade: https://ffxiclopedia.fandom.com/wiki/Seraph_Blade?oldid=511057
Vorpal Blade: https://ffxiclopedia.fandom.com/wiki/Vorpal_Blade?oldid=531072

![image](https://user-images.githubusercontent.com/6832027/54886662-cb03fb80-4e8a-11e9-86ff-db5a94f98f4d.png)

**Comment by Mahou81** [comment]
Red mage unable to use Seraph blade would be era-accurate. Both my memory, ffxiclopedia old pages and current Edenxi wiki state this. I did not check for Red Lotus Blade or Seraph Blade, but it seems those should not be available either.

**Comment by ShiyoKozuki** [comment]
Yeah this is out of era and only recently in retail did they give RDM access to these weapon skills.

**Comment by ISilenceI** [comment]
https://github.com/EdenServer/community/issues/62
Someone didn't do a search before they made a ticket. Tsk tsk.

**Comment by Mahou81** [comment]
That post is only about Vorpal Blade, while this 1 is about mutiple WS. That is why I commented on this 1. Anyway, if deliberate these kinds of changes should be listed on this Eden wiki page to avoid confusion:
https://classicffxi.fandom.com/wiki/Eden_Custom_Changes

**Comment by Slamm21** [comment]
RDM having those WS is indeed out of era, however, I would like to point out though that RDM doesn't solo anything tough with a sword.
You either DoT and Nuke or very rarely, you hit it with a low damage low delay dagger so you hit for 0, but enspells kill it so that it almost never has any TP.

**Comment by Mahou81** [comment]
Depends on your definition of 'tough'. A decent rdm/nin can easily melee mobs that check Tough and meleeing is by far the most effective way of farming stuff. But even if it were true, what's your point exactly? That it doesn't matter? Then why even make that post?

**Comment by Slamm21** [comment]
You would go THF sub if you were farming without an alt and still kill a T without issues. If you had an alt you surely would melee with that always? It will do way more damage than any rdm while you debuff and occasionally nuke.

If you want to melee RDM things which are tough, you will struggle to hit them with RDM and even with Mandau+Joy or Enhancing + KC you still barely melee a thing. It's just not efficient.
Also in both those situations, you don't use any of those weapon skills.

**Comment by Mahou81** [comment]
Different players, different play styles. Don't tell others how they should play please. Also, this is way off topic.

**Comment by ShiyoKozuki** [comment]
It's a buff to a job that's already one of, if not the strongest job in the game. There's no real reason for this to be in.
