### ISSUE TITLE
[PUP] Automaton unable to Parry

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1387]
Just as it says. Can't believe I didn't ever notice this til now. But after asking multiple other 75 PUP... We've realized that our automatons have never parried a single attack on this server.

**Comment by xizeta** [comment]
This doesn't seem to be documented on any of the wikis, so I had to go through some videos.
You can see an Automaton parry an attack here at 3:58.
https://youtu.be/gfTuCwNC99Q?t=238
