### ISSUE TITLE
Making the Grade

### ISSUE THREAD

**Issue by Swankyjr** [EdenServer/community#1388]
After talking to Fuepepe and trading him the Test Answers, it seems like i lost the Test Answers to him, i noticed this after i went to Chomoro-Kyotoro, cause you need to trade him the Test answers to him to advance the quest further.

**Comment by Hatberg** [comment]
Can confirm.

Trading Test Answers to Fuepepe consumes the item but progresses the quest. The NPC will direct you to Koru-Moru. The item should not be removed at this point.

To receive the key-item Tattered Test Sheet from Koru-Moru you will need to trade him Test Answers as well, which was obviously consumed in the previous quest step.

The quest is currently only completable by trading and losing 2x Test Answers.

**Comment by Shoruto** [comment]
It did work for me with only one test answer, so not sure what happened to need 2 of them.

**Comment by 59blargedy** [comment]
This issue was resolved some time ago (2019)
