### ISSUE TITLE
Cherry Muffin NPC sell Prices

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#1389]
Current retail and Eden:
Resale Price: 62 gil
Resale Price: 91 gil HQ

Era values:
NPC Sell Price: 160 - 169 gil
NPC Sell Price: 374 - 395 gil HQ

**Comment by Shoruto** [comment]
I am not finding any record of this or the HQ item anytime during era.  Everything begins when WoTG was released.  I believe this is an item that needs to be removed from the game to keep Eden era accurate, unless someone else finds something proving it was here during era.

**Cherry Muffin**
https://ffxiclopedia.fandom.com/wiki/Cherry_Muffin?action=history
https://www.bg-wiki.com/index.php?title=Cherry_Muffin&oldid=66234
http://ffxi.allakhazam.com/wiki.html?h=FFXI_ITEM:Cherry_Muffin
https://www.ffxiah.com/item/5653/cherry-muffin

**Cherry Muffin +1**
https://www.bg-wiki.com/index.php?title=Cherry_Muffin_%2B1&action=history
https://ffxiclopedia.fandom.com/wiki/Cherry_Muffin_%2B1?action=history
https://www.ffxiah.com/item/5654/cherry-muffin-1
