### ISSUE TITLE
Enmity

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#139]
Pretty sure Enmity is not resetting on death

**Comment by Slamm21** [comment]
I've noticed this is still happening.
On Kirin our whm will die, get up and cast 1 cure only to die again constantly because she must still have more CE and VE in the table than the PLD.

**Comment by Volkaru** [comment]
This was referenced in another bug report back around may, but was supposedly fixed. It seemed fine for a while. The fix may have gotten reverted somehow. Will edit with the report once I find it.
It's also an issue on Automatons. I'll be curing the main tank, deactivate my automaton, which should wipe hate on him. Then when i reactivate and start curing again, the monster will go after the automaton very quickly.
