### ISSUE TITLE
lost tonko: ichi cuz para

### ISSUE THREAD

**Issue by itachioax** [EdenServer/community#1390]
is this a bug? cuz i lost my scroll after use it (and i was paralized)

=(

**Comment by Far-The-Killer** [comment]
This is era behavior as far as I understand. Should never use items when paralyzed because of this.

**Comment by godmode** [comment]
Anything can be lost while paralyzed. This is most evident with warp items. You could frequently lose warp items when a fight was going South and you tried to use it when paralyzed.

**Comment by greyenvy** [comment]
Scrolls too though?  I can't recall that ever happening but I never tried to eat a scroll with paralyze on.  Thing with stuff like Tonko is it's a quested scroll so he can never get another one on that character.  Pretty rough.

**Comment by AnkleAssassinz** [comment]
Unfortunate that happen but that is indeed era accurate. ANY item you are trying to use while paralyze can potentially be lost; seen it trying to learn Warp scroll after leveling up in paralyzed state.
