### ISSUE TITLE
Mob Spell Behavior

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#1392]
mob (Beastmen) spell behavior is odd.  at times they will recast spells they don't need to cast.  I have seen mobs give themelves Protect twice in a few minutes time.  I've seen them also reapply Dia before it wears off, same with poison.  I'm not sure how the AI does these things but something about it just seems off a tad.

**Comment by beauxq** [comment]
related, but not the same thing https://github.com/EdenServer/community/issues/716

**Comment by bkesecker** [comment]
There's no AI sadly.  Just a random number that picks a spell from a list.  Absolutely needs fixed, but fixing it is a major change that will need sufficient testing.

**Comment by Lilswitche** [comment]
One thing that might need to be considered is the interval between casts.  Currently, it seems as though the delay is calculated based on the start of cast rather than the end of casting.  This can result in mobs chain casting ancient magic spells.

**Comment by RottenUnagi** [comment]
I agree with this post. Particularly I want to emphasize the fact that mobs are casting way too often, similar to ranged mobs using ranged attack too often. Worms are a perfect example of this. Step out to South Gustaberg, provoke a worm from distance, and it will spam Stone every ~5 seconds. In retail a mob will wait significantly longer between casts of any two given spells in general (though I think there are some cases where they might quickly throw out another emergency spell out of rhythm, like Stun, etc.?)

**Comment by KnowOne134** [comment]
Partially fixed, added a check for enhancing maging to check if it has the effect applied before recasting

**Comment by 59blargedy** [comment]
most of the issues on this ticket are out of date at this point/resolved, and mobs will cast spells like poison and dia on retail despite them already being on the player, so going to close this out
