### ISSUE TITLE
Yara Ma Yha Who incorrect spawn conditions.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1393]
Yara Ma Yha Who
https://ffxiclopedia.fandom.com/wiki/Yara_Ma_Yha_Who?oldid=330517
Supposed to be able to trade a water every 50 minutes to increase the chance for spawn. However it's been over two hours and I haven't been able to trade any but the initial water after server reset.
Zoning, or using another character didn't help.

Edit: Was able to finally trade a second water after over three hours passed. When it should be 50 minutes.

Edit 2: Okay. Been camping this for 6+ hours now since reset. I think I figured out the problem. It's possibly that every time someone clicks the ???, it resets the 50 minute timer if it's not already up. If I leave it alone for an hour. I can water it. If I click it to check any time before that, it gets reset.

**Comment by GiichiHiro** [comment]
I spawned this a couple of days ago and died to it.  I haven't been able to trade a water to it since.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
