### ISSUE TITLE
Typing /wait 30 in regular non-macro chat forces the game to halt for 30s

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1397]
If you type /wait followed by a number in the chat window and send it it forces your game to freeze for however many seconds you type afterwards.

So if you type /wait 6 into your say window and send it, it will literally freeze your game for six seconds and when the time is up your game will unfreeze.

**Comment by ababyduck** [comment]
This is expected behavior for Ashita, not a server issue.

Please see https://wiki.ashitaxi.com/doku.php?id=ashitav3:commands#time_based_commands

**Comment by archfiendrubicante** [comment]
My bad then.
