### ISSUE TITLE
Sozu Rogberry no longer spawning

### ISSUE THREAD

**Issue by Strumerjohn** [EdenServer/community#1399]
I can't confirm it's been ever since the emergency maintenance, but it has been at least 26+ hours since the last Sozu Rogberry has spawned. I understand that it is a lottery NM and could technically never spawn, but this long of a stretch seems extremely abnormal given on average, since the buff, Sozu has spawned once every four hours at least. Did the buff get reverted, is Sozu bugged, or is this just bad luck for all of us who have been here for the past going on two days?

**Comment by Novadragon-Siren** [comment]
He wasn't buffed spawning, only removed the cool down. His PH is a 5% chance for NM to spawn, it is overall possible to take that long.

**Comment by Strumerjohn** [comment]
I guess, but he still hasn't spawned and it's been 5 more hours since I created this report.

**Comment by Novadragon-Siren** [comment]
Are you killing the Pursuer? If so that's Sozu for ya. 

Sozu has the worst spawn conditions to exist in the game.

**Comment by Strumerjohn** [comment]
Nah, I'm killing the magic pots. Maybe that's it. Thanks, man!

**Comment by godmode** [comment]
It doesn't appear to be anything wrong with the pop. I can check to make sure and nothing was changed back.

**Comment by Strumerjohn** [comment]
Thanks! Confirmation would just be nice. I'm fine with going crazy inside here killing PH for hours/days but just wanted to make sure it was still working since this is the first time I've not seen for like 30+ hours lol. Issue can be closed if nothing changed obviously.

**Comment by Strumerjohn** [comment]
Finally got a Sozu pop about 20 minutes ago, so it at least still spawns! ^^;. Not sure if you changed anything, but I guess all means have outliers. This was a really long pop over the ones throughout the rest of the week last week/weekend though... it doesn't feel as good as it was, but maybe it was never "meant" to be as good as it was since the buff. This issue can be closed if no changes were mistakenly made.

**Comment by Novadragon-Siren** [comment]
Sozu is pure lottery, very RNG. 5% PH, 3-5% drop rate.

**Comment by godmode** [comment]
No changes were made to make the pop condition worse, only better. Thanks for the update, gonna close the ticket now.
