### ISSUE TITLE
Persistent black screen issues (Can't login to certain characters)

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#14]
For the last week or two [back on Kupo] I was unable to log into the characters Grim and Good, every time met with a black screen and error 3001. I was disappointed to see the same issue upon my first attempt to log into Good on Eden :( Hopefully it can be fixed!

**Comment by Aneyus** [comment]
Same issue just occurred on my main characters Aneyus & Chawlee when I tried to relog. Can't login at all now =/

**Comment by godmode** [comment]
This was resolved by updating to the latest version of Ashita and reentering the server config information.

**Comment by Aneyus** [comment]
The new bootloader worked once, and then I was unable to log into Good again with the same issues. Unable to test a freshly downloaded bootloader at this moment; will update later.

**Comment by Aneyus** [comment]
In retrospect this issue may have been caused by a lack of --hairpin on the launch configs I was using at the time. Necrobumping with potentially useful info for future reference
