### ISSUE TITLE
Berserk cancels Defender and vice versa

### ISSUE THREAD

**Issue by HenryKari** [EdenServer/community#1400]
If you have Defender active and you use Berserk, Defender will be automatically cancelled, and the same happens the other way around, too. This is not working as intended in the game. 

[FFXIclopedia](https://ffxiclopedia.fandom.com/wiki/Berserk) says:

> When Defender is activated at the same time as Berserk, the two abilities effectively cancel each other out, however both effects will remain active unless canceled. Should one ability be canceled, the other will resume having an effect.

While there is generally no point in having both effects active at the same time, you might sometimes want to temporarily activate one while the other is already active. So using one should not immediately cancel the other. It should be left for the player to decide to cancel.

**Comment by ShiyoKozuki** [comment]
Can confirm this is not working as intended. Can this please be fixed? It greatly lowers the skill cap of any /war or war/x job combination and is awful.

**Comment by Caelic** [comment]
when linking the wiki be sure to use a 2007 version of the page using the History button on the right side. in this case it doesn't seem to change so it remains true for 2007 version (just worded differently)

https://ffxiclopedia.fandom.com/wiki/Berserk?oldid=262286

as for the coding, it's a case of effects with the same type overwriting each other. in SQL:

`id,name,type FROM dspdb.status_effects WHERE id IN (56,57); -- berserk and defender`

they both have the type 56. giving defender an unused type id would fix this issue. again in SQL:

`SELECT * FROM dspdb.status_effects WHERE type NOT IN (0) ORDER BY type ASC;`

just to see what ids are available for use. in stock dsp, type 57 is available so just a simple update query

`UPDATE dspdb.status_effects SET type = 57 WHERE id IN (57); -- defender will have its own type
SELECT id,name,type FROM dspdb.status_effects WHERE id IN (56,57); -- berserk and defender`
