### ISSUE TITLE
Bloody Blade not proccing

### ISSUE THREAD

**Issue by SBC-Nyxai** [EdenServer/community#1401]
Bloody Blade has not proc'd at all on mobs. Have put in a few hundred hits. Have tried with both full hp and non-full hp and also on TW, EP, DC mobs.

https://ffxiclopedia.fandom.com/wiki/Bloody_Blade

Here is input from an FFXIAH user on the proc rate:
https://www.ffxiah.com/item/16827/carnage-blade
https://www.ffxiah.com/item/16556/bloody-blade

* Have put thousands of hits on mobs that range across multiple difficulties with no proc at all.

**Comment by SBC-Nyxai** [comment]
Tried in both MH and OH on different types of mobs. Never got an HP Drain Proc. Hope its fixed soon, thanks.

**Comment by bkesecker** [comment]
@SBC-Nyxai  These are now implemented and live.  However, the proc rate may not be accurate.  Can anyone corroborate the data from these sources?  Some other info: https://ffxiclopedia.fandom.com/wiki/Talk:Bloody_Blade
