### ISSUE TITLE
Istakoz biting on shrimp lure and crayfish ball

### ISSUE THREAD

**Issue by tacbox3** [EdenServer/community#1402]
According to http://www.great-blue.jp/?fid=110&lng=en Istakoz should not bite on these baits. This is an issue as it creates off-target fish for people skilling up in Nashmau and Arrapago Reef. Please correct the bite table for this fish.

**Comment by tacbox3** [comment]
This seems to be a broad issue with ToAU bite tables, and is not isolated. Some tables are incomplete (Ahtapot not biting on Crayfish Ball), while others include baits they should not (see above for Istakoz).

**Comment by Deepupuu** [comment]
yeah according to ffxiclopedia history it shouldnt bite on shrimp lure either
