### ISSUE TITLE
Lord Of Onzozo issues

### ISSUE THREAD

**Issue by Chief-E** [EdenServer/community#1403]
Here are some issues with Lord of Onzozo:
1- It doesn't use Draw-In, I have been able to pull it to the entrance twice.
2- It uses Water IV, Blindga which were added in mid 2007, before that it had only Waterga III and Flood: [confirmation](https://ffxiclopedia.fandom.com/wiki/Lord_of_Onzozo?oldid=79996)
3- Whirlwind/Maelstorm are AoE skills and should wipe Utsusemi shadows, but here it just does damage without wiping shadows: [confirmation](https://ffxiclopedia.fandom.com/wiki/Whirlwind)

**Comment by Elysien** [comment]
I'm not 100% sure of this, but I believe it's draw in is just standard draw in, not regional draw in. So even on retail, if you moved slowly enough you could get it to the zone line.

An example of regional draw in would be Fafnir/Nidhogg where you cannot remove them from the platform they spawn on under any circumstance.

An example of normal draw in would be Simurgh, where if you exceed 20 yalms of it, you will be drawn in but so long as you were within those yalms you could move Simurgh any where.

I believe LoO possessed the latter, but as I said, I could be mistaken.

**Comment by Chief-E** [comment]
I have lost sight/target of it lots of times (because it was casting) and had to move back to see if its still following me, which means I moved more than what is needed for a draw in

**Comment by Oyaziiiiiii** [comment]
I think the discrepancy in its spell list is just wiki user error. All the videos I've found show it using flood, blindga, and waterga3, but not water 4. I can't imagine them ever changing its spell lists. At the 5:39 mark, maelstrom strips shadows and does damage. At 8:54, whirlwind strips shadows and does damage. So I think both of those should be corrected and water 4 should be removed from the spell list. 

https://www.youtube.com/watch?v=Im3YZKS0fsI

**Comment by AikoSachi** [comment]
Should also mention mid-2007 would still be considered Era based on my knowledge you basically have until November 11th, 2007 until it becomes "OOE"

**Comment by Chief-E** [comment]
I noticed one more issue yesterday:
Cross Attack is a two hit skill and should remove two shadows but currently it is removing one shadow only.
https://ffxiclopedia.fandom.com/wiki/Cross_Attack
