### ISSUE TITLE
Treasure and Tribulations no effect on enfeebling magic

### ISSUE THREAD

**Issue by ccl085** [EdenServer/community#1404]
We attempted this BCNM as nin rdm brd, our enfeebling got resisted but when we tried to enfeebling it again we got the no effect message as if the magic landed but it clearly did not land as his accuracy/attack speed did not lower and we never got the paralyzed message.

**Comment by Shoruto** [comment]
I had that happen during my dunes party yesterday on my Blind spell.  Thought it was kinda odd.  When I recasted it, it landed.

**Comment by Slamm21** [comment]
![Slamm_2019 03 26_145819](https://user-images.githubusercontent.com/5552081/55089621-96b85700-50a5-11e9-9a94-c5c1560b27a5.png)

It also hit much faster than it should, being the biggest chest. It seems like it had the same attack speed as the small chest when the big one is meant to hit slower but harder.

**Comment by AikoSachi** [comment]
I think this happened in one of my parties also with out WHM's silence, I didn't think anything at the time, but worth checking.

**Comment by ccl085** [comment]
Tried this bcnm again with better gear/elemental seal and enfeebling magic still not landing, this make this BCNM much harder than retail

**Comment by bkesecker** [comment]
I can confirm that it is impossible to enfeeble the Large Box.  Resistance may be in the DB.  Don't see it in the Lua.

**Comment by bkesecker** [comment]
Figured out the issue, fix is easy.  Did the due diligent research myself, but can't find anything saying these boxes can't be slept or bound.  Does anyone know?  Otherwise, I am inclined to make them immune to sleep/bind/lullaby.

**Comment by Raphtalia1** [comment]
anecdotal but I recall that you couldn't sleep them back in the day, bind worked (however it was useless, as it would draw in if i couldn't reach at least one player)
