### ISSUE TITLE
Baren Moren buged

### ISSUE THREAD

**Issue by Joeytarutaru** [EdenServer/community#1405]

**Comment by Joeytarutaru** [comment]
Hat in Hand
A Feather in One's Cap
All at sea

cant speak with the NPC

**Comment by Shoruto** [comment]
Did you try zoning and then going back in and speaking with him?

**Comment by Joeytarutaru** [comment]
Yes

**Comment by ababyduck** [comment]
Can anyone else verify that they are unable to interact with Baren-Moren? His quests appear to be implemented in base DSP as of 3 years ago, so it's unlikely that has been changed here.
