### ISSUE TITLE
Ninja Kyahan movement speed times incorrect

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1407]
Currently, the base AF feet for ninja are giving 25% movement speed from dusk til dawn (which is only supposed to happen with the +1). 

Nighttime = 18:00 - 6:00
Dusk til Dawn = 17:00 - 7:00 

https://ffxiclopedia.fandom.com/wiki/Time_of_Day

**Comment by icariumkupo** [comment]
Actually it works 18 to 7

**Comment by Treble011** [comment]
I only noticed it yesterday because I don't play NIN often. It should have been reported a while ago.

**Comment by roriffxi** [comment]
I only just started playing Ninja and noticed that my speed wasn't wearing off at 6 game time unless i removed the shoes and put them back on.  Then it reduces me to regular run speed.

Been too paranoid to leave them on so I just was doing that, so I dunno if it cuts out automatically at 7 game time.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update

**Comment by statuseffect** [comment]
Ninja Kyahan remained active up until 7:30 were deactivated once i zoned.
