### ISSUE TITLE
Lottery NM's not spawning:

### ISSUE THREAD

**Issue by whiskeyhughes** [EdenServer/community#1409]
It seems like there have been a few instances where lottery nm's aren't spawning like they should be. For a while I was camping Dune Widow and getting the kill 2-4 times a day. Then out of nowhere I haven't seen Dune Widow spawn in over a two week period following a patch. At first I thought it was bad luck, but then while camping Biast, other people have reported similar issues. 

Can someone on the dev team just confirm that Dune Widow and Biast are actually spawning regularly? I am sure it is logged somewhere. I just want to make sure that I am not going insane.. 

Is it possible that the NM's are despawning? I have also noticed that while killing spiders in Altepa, that some will just despawn out of nowhere..

**Comment by godmode** [comment]
NMs should not despawn but I can test to make sure. The pop rates were not adjusted though.

**Comment by whiskeyhughes** [comment]
Gotcha! Is there logging by default that would tell you when a NM spawned and if it was killed?

**Comment by godmode** [comment]
Yeah

**Comment by Aneyus** [comment]
Biast just spawned the other day. Working fine there.

**Comment by ababyduck** [comment]
> 
> 
> NMs should not despawn but I can test to make sure. The pop rates were not adjusted though.

I'm not sure this is working as intended. Ulli despawned today after a couple of us took the time to pop him and then wiped.
