### ISSUE TITLE
Mysticmaker Profblix not dropping the proper gil

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#141]
He's dropping ~100 gil and it should be 3k-9k
http://ffxiclopedia.wikia.com/wiki/Mysticmaker_Profblix

**Comment by Shoruto** [comment]
There is no posted evidence of what this NM gil drop should be during era, only what it was during retail as per your link you posted.  The 100 gil would be accurate for the level goblins in Onzozo for retail date however the NM should be higher then that by default of being a NM vs regular goblin.  Just no info on what that range should be.  

To be era accurate, the 3k-9k range would be too high.  Its only a guess right now of what it should be, until any new evidence pops up.

**Comment by roriffxi** [comment]
http://ffxi.allakhazam.com/db/bestiary.html?fmob=1554&p=5#m11406295532019 -6k gil
http://ffxi.allakhazam.com/db/bestiary.html?fmob=1554&p=2#m117448599832047564 -almost 3k gil
http://ffxi.allakhazam.com/db/bestiary.html?fmob=1554&p=5#m11381277198055 - 4.5k gil
http://ffxi.allakhazam.com/db/bestiary.html?fmob=1554&p=5#m113797612114504 - over 9k gil
http://ffxi.allakhazam.com/db/bestiary.html?fmob=1554&p=6#m113002295512337 - 6k gil

All era timerange sources.
Sorry I should have researched and responded to this a while ago, having it closed reminded me about it.
