### ISSUE TITLE
Windurst Mission 1-2 having to repeat cutscenes

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1410]
While trying to finish 1-2 at the beginning of the mission I put all of the orbs into receptacles. After that I had to activate the gate three times to get the orbs to properly charge despite not being attacked by anything, and on some of the orbs I've had to check some of the receptacles more than once to properly get the glowing orb key items.

**Comment by Shoruto** [comment]
Were you able to finish the mission and has this happened on any new missions that you've tried?

**Comment by archfiendrubicante** [comment]
I was able to finish the mission, but while I was guiding multiple people through the mission (I've helped at least 5 people finish it) at least three have had instances of viewing a cutscene and not getting the associated key item / event trigger.

It didn't happen in 1-3 with anyone of the five who came with me to finish that mission, so I think its just localized to 1-2.
