### ISSUE TITLE
Feeler Antlion(Rostrum Pumps NM) broken

### ISSUE THREAD

**Issue by Virtuekupo** [EdenServer/community#1412]
Hard to say when the fight broke but currently Feeler antlion only spawns executioners when sandpit was used and never spawned alastor on sandblast, also the executioners are now untargetable this could also effect the alastor but we don't know since it never popped
![Virtue_2019 03 27_203717](https://user-images.githubusercontent.com/47134174/55121457-fa0bae80-50d0-11e9-8f6d-3f291f18ea3e.png)

**Comment by godmode** [comment]
Oh yikes. Make a GM ticket for the pop item please.

**Comment by Jimmayus** [comment]
Adding onto this with a couple of screenshots. Some confirmed things:

1) You can trade the Antlion Trap to farm the feeler antlion, we just did so this evening.

2) Sandpit will spawn Executioner Antlions, but like the original post says they spawn underground and are untargetable. They pop above ground to attack but then immediately go down again. They can become the battle target, however, and are attackable. We don't know if they took damage. 
![Jimmayus_2019 04 12_205319](https://user-images.githubusercontent.com/45926115/56073189-b9b15f00-5d65-11e9-84ee-7fd41955487f.png)
![Jimmayus_2019 04 12_205256](https://user-images.githubusercontent.com/45926115/56073192-be761300-5d65-11e9-9117-250d2df4c015.png)

3. Sandblast did actually spawn Alastor Antlion, who exhibited the same broken behaviors as the Executioner Antlions. 
![Volkaru_2019 04 12_185408](https://user-images.githubusercontent.com/45926115/56073239-2d536c00-5d66-11e9-8844-8a37a9877891.png)

See also this youtube recording of our attempt:

[https://www.youtube.com/watch?v=smlMOOBLveg&feature=youtu.be](url)

**Comment by VirtuosusFFXI** [comment]
Any update to this? I'm going to assume its still not functioning since we last tried and I would rather not waste a pop item to test it.

**Comment by CurzonEden** [comment]
Is this fix currently live? just want to know before I drag a bunch of my friends out to Attowah, don't want to waste there time or a pop item if it this won't be in till next patch.

Also, Thanks for fixing it!

**Comment by godmode** [comment]
It isn’t. It should have the fix on deploy tag.
