### ISSUE TITLE
Acid bolt Additional Effect activation rate WAY too low.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1413]
Recorded each shot while leveling DRK going through 15-25, using up 9 stacks of acid bolts. Accuracy of landing hits in general was around 50% according to Scoreboard. Counted the times the Defense down activated. It was every 8-9 bolts landed. This was all on T-IT+ mobs. That leaves the activation rate around 15-20% overall for bolts. That is extremely low compared to retail, where the activation rate was easily 50% or higher.

**Comment by Spintaru** [comment]
Volkaru, I've noticed this too as well, I can hit the target, but if I don't do enough damage with the hit, it doesn't proc. For example, if the bolt lands, and does 23 damage (hypothetical) it won't proc at all, but the moment i hit 25 damage, it either procs or doesn't. If I hit it enough times at 25 damage, it does proc like retail, about 50/50 split. Anything that is DC or lower, procs nearly 100 percent of the time, because i'm always in that hit range where there is enough damage, and the mob is too low to resist the proc. I'll be leveling RNG soon past 18, I should have more data on procs then.

**Comment by Volkaru** [comment]
Possibly. I don't think damage is a set factor, though. I'm a galka DRK. every bolt is landing for high damage.

**Comment by roriffxi** [comment]
Activation rate on ammo should be 100% for everything except those bullets with stun.

However, mobs can resist the effects.  I'm not sure if the effect isn't activating the proper amount or if mobs are just resisting too often.  I suspect they're just resisting too often.

**Comment by falzum** [comment]
Retail evidence provided by Dowzer that Acid bolt debuff should be able to overwrite itself

https://imgur.com/rr4IQJp

**Comment by dowzer** [comment]
Large sample vs. Mourning Crawler lv103-105
![5mourningcrawler](https://user-images.githubusercontent.com/54732693/154853572-1b2b99ac-324a-4847-ab3a-8794f427e5df.png)

Greater Colibri (Wind resistance playing a role?)
![1gcolibri](https://user-images.githubusercontent.com/54732693/154853582-febf304a-71b1-4585-8b20-ee327b4f7d66.png)

Wivre in the same area
![4wivre](https://user-images.githubusercontent.com/54732693/154853590-1dfd5aca-0c82-4098-bb94-94b6a28c24bc.png)

Dahak in Mount Zhayolm
![3dahak](https://user-images.githubusercontent.com/54732693/154853594-d36839d5-a1c6-43e6-983b-27824b51718b.png)

Bune
![2bune](https://user-images.githubusercontent.com/54732693/154853603-29298ed1-cbfd-4d2e-809d-a504352cfbd2.png)


All these samples were done against mobs higher than level 75. I'll post lower level results later.

**Comment by dowzer** [comment]
RNG15/NIN7 vs Lv21-22 Damselflies

![acidboltdamselflylv15](https://user-images.githubusercontent.com/54732693/186028884-39f2de73-9976-4d87-abb6-d93f30d4990f.png)

RNG15/NIN7 vs Lv21-22 Snippers

![acidboltsnipperlv15](https://user-images.githubusercontent.com/54732693/186031009-b5b63146-40a6-4d9b-afad-61467344930e.png)

**Comment by dowzer** [comment]
Somewhere at either Lv78~79, Proc % drops off a cliff from 99% to around 69% when comparing these to Dahaks

RNG75/NIN37 vs Lv61-63 Robber Crabs

![acidboltrobbercrablv75](https://user-images.githubusercontent.com/54732693/186037744-20512e09-4eea-4c40-ada0-a2009330c36b.png)

RNG75/NIN37 vs Lv76 Steelshell

![acidboltsteelshelllv75](https://user-images.githubusercontent.com/54732693/186037806-51431f65-1b45-492c-93e5-31934d3be10c.png)

RNG75/NIN37 vs Lv77 Demonic Rose

![acidboltdemonicroselv75](https://user-images.githubusercontent.com/54732693/186038020-30ce6e84-d2e5-4143-ab7c-df7238b42e3f.png)

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
