### ISSUE TITLE
Eagle Eye Shot Ranged Accuracy way too low

### ISSUE THREAD

**Issue by ccl085** [EdenServer/community#1414]
Eagle Eye shot ranged accuracy seems off, It is missing a lot, even on target I have capped or close to capped hit rate.

**Comment by Shoruto** [comment]
Just to clear some items up, were you under the effect of Blind or any accuracy down affect? and the monster you were attacking did they have blink or any type of shadow up?  Any of these will affect the chance of it landing.

**Comment by ccl085** [comment]
Nope, happened on almost all my xp pt from level 10 to 40, sadly I can't spam it to try the exact %

**Comment by montijin** [comment]
Even outside of possible accuracy issues; EES against high level NMs just does 0-40 damage most of the time and then I feel ashamed. 

![image](https://user-images.githubusercontent.com/2160211/75124203-41991280-5673-11ea-9c8b-cfa524228642.png)

**Comment by 59blargedy** [comment]
resolved with update, however dmg on HNMS will not fully change until monster update.
