### ISSUE TITLE
5 Astral Flows in a Row

### ISSUE THREAD

**Issue by BuffaloOnEden** [EdenServer/community#1415]
In Jungle Boogymen, on the last tonberry, the summoner, he did astral flow FIVE TIMES in a row. See the screenshot. 
![Buffalo_2019 03 28_200752](https://user-images.githubusercontent.com/48140912/55202770-c72bee00-5196-11e9-90e2-42d1148eed27.png)

**Comment by Shoruto** [comment]
I can't find anything videos or websites/forums that say much about the 2 hour abilities during era.  Other then it uses Astral Flow.  5 does seem excessive but not sure.  I know some NMs do nothing but spam their abilities so it might be the same way here.  Just a guess though.

**Comment by godmode** [comment]
It’s likely due to a lag issue on the server. The code is not ideal as it is so I suspect this is the case. Will fix it regardless.

**Comment by Volkaru** [comment]
It also seems to be affecting Avatars, as well. When fighting Ifrit last night, he would do two BPs in a row. Flaming crush, instantly followed by inferno. He used Inferno a total of three times during the fight. They're supposed to only be used once. And in the place of another TP move.
Also had the same issue during Fenrir fight. He'd use TP moves back to back. And used his Astral flow four times. Twice were within a couple minutes of each other.

**Comment by Gretal1** [comment]
To add on this, we had Kirin use Astral Flow 3 times consecutively, wiping our alliance pretty much. 
Can see where verrin took damage at least twice. 
![image](https://user-images.githubusercontent.com/48834068/56165098-b9000f00-5f97-11e9-9f2a-07d5142dfcce.png)

**Comment by Slamm21** [comment]
Can confirm that 2hrs were always only used once on retail. Usually around 50%. Seems some mobs use them as if they were a standard tp move.
