### ISSUE TITLE
Quest Chain Missing.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#1416]
The chain of quests...
https://ffxiclopedia.fandom.com/wiki/Chasing_Dreams
And https://ffxiclopedia.fandom.com/wiki/The_Search_for_Goldmane
Are missing. 
They give 2 really nice items. :P

**Comment by Shoruto** [comment]
Before you attempted to do these, did you complete Chains of Promithia 2-1?

**Comment by Serephim** [comment]
Yes, I am done all the CoP Missions available. Finished 4-3 Sacrarium when it came out.

**Comment by 59blargedy** [comment]
fully resolved with Goldmane quest in October 4, 2021 update
