### ISSUE TITLE
Enmity on pull incorrect

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#1418]
As someone who has pulled nonstop to 75 on two jobs now, this particular bug is a thorn in my side.

The puller of a mob either has some sort of enmity boost or modifier which simply shouldn't exist.

For instance, if I pull a mob with a 50 damage ranged attack, then someone should be able to pull it off of me with a 100 damage hit.  This however, doesn't happen.  The initial puller will still have hate; way more than they should.

**Comment by Lilswitche** [comment]
There was an emnity boost on first emnity producing action on retail.  I'm not 100% on the mechanics on Eden, can't some of the specifics like if it applied when /ra missed on pull, etc. The Kanican livejournal i believe outlines this mechanic.

**Comment by ThrisStraizo** [comment]
I'm just throwing out there that the increase in enmity for pulling just seems to be a bit more than it should be.  I'm not entirely sure on what the code looks like, but it certainly FEELS like a modifier on the initial pull Enmity rather than a stagnant amount. 

Doesn't feel right brother.

**Comment by Serephim** [comment]
Yeah this always existed that is why people always wanted a first voke in parties. :P

**Comment by godmode** [comment]
Eden is using Kaeko’s enmity values for first pull. If it doesn’t seem like it’s accurate to that please add a new comment to the ticket.

**Comment by ThrisStraizo** [comment]
Alrighty, well whatever the values are, they are wrong.  

A puller pulls by ranged attacking for 133 damage then crits for 263.
It is then provoked off of him.  Under the same conditions on Eden a provoke would not be sufficient to pull hate off of this.

Here at: https://youtu.be/NM7Awys8LQ0?t=201


The same thing happens SEVERAL times throughout the video where the puller does around 350 damage to the Colibri while pulling and provoke can pull it off of him.

However, if I pull the same mob at the same camp with a 250 damage quick draw, provoke isn't enough to pull hate off of me.

The added Enmity on pull right now is most certainly excessive.  It just seemed so blatant to me that I thought it might have been part of Enmity issues that were already reported.  After a career of pulling more Colibris that should be allowed on God's green earth in retail, I can assure you, it's off.

If you want to find a more era video of the same thing happening I will, but I'm not looking forward to it.
I don't think anything about enmity values has changed and that video should show why the enmity pull values on Eden are ridiculous  as it stands.

**Comment by ThrisStraizo** [comment]
I should have opened with this more thorough report.  After pulling with quick draw a bunch and provoke doing nothing to pull it off of me, I was just a lazy kind of angry I suppose. (No but for real, plz fix.)

**Comment by Lilswitche** [comment]
It may have less to do with bonus enmity on first action as does with the enmity calculation on damage.  Keep in mind in the video linked, the puller pulls for 133 damage, takes over 200 damage and 14 seconds elapses before the voke goes off. 

I've personally felt like enmity from damage builds very quickly but fixed emnity values from bonus/spells/abilities seemed to have correct values.  We had an HNM change hate the other day, not soon after pull,  from a 500+ damage Corsair quickdraw after we had been building some emnity for a good 45s~.

**Comment by ThrisStraizo** [comment]
> Keep in mind in the video linked, the puller pulls for 133 damage, takes over 200 damage and 14 seconds elapses before the voke goes off.

I've pulled very far side colibris with 250 damage which takes a while to get to camp and provoke still doesn't pull hate.  It's awful.

**Comment by ThrisStraizo** [comment]
> Eden is using Kaeko’s enmity values for first pull. If it doesn’t seem like it’s accurate to that please add a new comment to the ticket.

I'd also like to throw this one out there, I couldn't find specific numbers (CE or VE) in the livejournal on pulling.   Only that the initial puller gets more hate.

If someone could show me where specific numbers for pulling is that would be great.  But if its not there, I would have to assume that the numbers for it was simply guessed for DSP.

**Comment by godmode** [comment]
https://web.archive.org/web/20081224025202/http://kanican.livejournal.com/21727.html

**Comment by ThrisStraizo** [comment]
Thanks for the link Godmode.   That should be pretty clear cut, but I just don't understand the difference between the example video I linked, and the fact that a Provoke didn't pull off of me, just yesterday, from a 212 damage quick draw.

It doesn't make any sense.

**Comment by ThrisStraizo** [comment]
I think I'm going to conduct a couple of experiments.  I have a hunch about something, but I'm not sure.

**Comment by ThrisStraizo** [comment]
I tried the same Colibri just now, did 322 damage and had the voker wait 20 seconds before provoking and it didn't pull hate off of me.

While the retail Samurai in the video did 396 damage, and got successfully voked off of in 14 seconds.
I'm not sure if the paladin in the video is wearing any AF that might give +Emnity, so I tried something else.

I did 384 damage with -6 emnity gear.   Provoker waiting 15 seconds.  It still didn't pull off of me.

I'm not sure what else to think of this.

**Comment by ThrisStraizo** [comment]
Pulled with 155 damage.  Provoke did not pull off of me immediately.
Pulled with 140 damage.  Provoke DID pull off of me.

**Comment by godmode** [comment]
Seems to be correct at the moment. I'm going to close for now. If you find era retail evidence please post.

**Comment by Slamm21** [comment]
I've had plenty of people tell me how "hate is bugged" on Eden and honestly I think they just remember things differently considering how long it was ago. Just before the level cap was raised, even your basic tank had some decent enmity or haste gear to spall CE and VE spells or abilities to great effect and as such it was harder to pull hate as a DD. And after the cap was raised SE completely ruined how enmity worked and that may be what people are remembering.

If Kaeko's values are being used then I'm positive everything is era accurate. I assume Eden also uses the formula for CE lost by damage taken?    [ CE Loss ]  =  1800 x [ Damage Taken ] / [ Target Max HP ] 
and the formula for damage dealt shown here [https://web.archive.org/web/20081224033743/http://kanican.livejournal.com/31338.html](url)
If this is the case, the values must be correct as extensive testing was done to get the precise values for all of that.

**Comment by slassen** [comment]
https://web.archive.org/web/20081224025202/http://kanican.livejournal.com/21727.html

Another link found by Slamm showing the actual values.
