### ISSUE TITLE
Cannot accept San d'Oria Mission 3-1

### ISSUE THREAD

**Issue by Eden-Lothar** [EdenServer/community#1419]
After completing "Journey Abroad", mission NPCs in San d'Oria only offer me a list of previously completed missions and do not accept crystals in order for me to begin mission 3-1. The NPC says I must be on a mission to trade crystals.

I can attempt to accept older missions but none of them register in my mission log and I cannot complete them. If I speak to the NPC again after accepting a mission, it gives me the same list of missions to accept. 

I was able to successfully accept and complete "The Davoi Report" which I had previously skipped on my way to "Journey Abroad". I was awarded rank points but I still am not offered "Infiltrate Davoi" and I still cannot turn in crystals. "The Davoi Report" is now the same as the other missions; if I accept, the mission is missing from my log and the NPC continues to offer old missions.

**Comment by bkesecker** [comment]
Your rank bar is full?  IIRC the crystals need turned in to the singnet guards, not mission giver.

**Comment by Eden-Lothar** [comment]
I turned in a stack to a signet guard and that seems to have worked. Thanks.
