### ISSUE TITLE
Korroloka Leeches '???' Disappears after clicking (Ninja Unlock Quest)

### ISSUE THREAD

**Issue by FallenXI** [EdenServer/community#1420]
Was duoing the Leeches with with a friend and the ??? disappeared after we killed the Leeches, and he clicked it and received the KI. I then had to wait for the ??? to appear again to receive the KI (which worked), but it also then disappeared again after this.

Expected behaviour is that the ??? should stay up once someone clicks it and obtains the KI.

Quest: Ayame and Kaede (Ninja unlock quest)

**Comment by Tolkage** [comment]
The issue here is that the person who starts the fight by clicking the ??? initially, needs to be the LAST person to click it again to get the KI. Once the person who initiated the fight gets the KI, the ??? disappears and you get the behavior you described above.

**Comment by bkesecker** [comment]
@Tolkage Do you know if what you describe is retail behavior?

**Comment by KnowOne134** [comment]
Corrected 4/5/2021
