### ISSUE TITLE
BST: Reward Bug

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#1422]
When fighting a Goblin Pet with your own Charmed pet (did not confirm for jug pets yet), you cannot use the "Reward" command.  This is a very significant bug to the way the job functions.  I am literally locked out of the command with the message.

Cannot attack.
That target is already claimed.

You can see it on my video last night here 7:03 of the video: https://youtu.be/e-gMKFNWUkI?t=414
Timestamp in log: 20:26:32

**Comment by Serephim** [comment]
This was happening to me a lot when I leveled BST in parties. I was locked out of using any commands like fight, ready and reward even though I could attack it normally with my character. No idea what caused it.

**Comment by mlandrum22** [comment]
(Azmanz) Have had this happen "Cannot attack .. " etc a lot in both Upper Delkfutt and Korroloka -- and it happens with Jug Pets too.

I thought it was due to pets of Gigas at first, but then sometimes I couldn't Ready vs the Giga's either (and I want to say it happened vs Gigas w/o pets, but maybe a pet was near?), so I couldn't quite pinpoint the exact issue.

Don't think I've had it happen in other zones.

**Comment by greyenvy** [comment]
Well it doesn't seem to have anything to do with enmity (ie. a party member has claimed the mob first).  It has only happened to me when I fight another pet type mob.  I wonder if it could happen with BST mobs as well.  I could do some testing in Qufim later.

**Comment by FariskaEden** [comment]
Check out #1133 , seems it has to do with when your pet is fighting a mob that has pet.

**Comment by greyenvy** [comment]
Seems so.  Locking out a job ability is a critical issue imo and needs attention.

**Comment by panfunk** [comment]
This was also reported way back on Kupo, https://github.com/KupoServer/Issues/issues/27#issue-306199575

Apparently occurs when fighting pets / have multiple targets.
Oddly I never had this happen as SMN, so I believe it has something to do with the nature of BSTs JA's, which are never used on your target or on your pet, but on yourself exclusively.

**Comment by mlandrum22** [comment]
Did Maat yesterday as BST so he had a pet. Dawn Mulsums work so you can still use items, but Reward/Ready didn't
