### ISSUE TITLE
"Making the Grade" Aspir Quest bugged

### ISSUE THREAD

**Issue by TorchlightEden** [EdenServer/community#1424]
I handed in the Test Answers to Fuepepe, however, he did not return them back to me like he was supposed to. Now I can't advance the quest by trading them to Koru-Moru unless I go farm MORE Test Answers, which shouldn't be the case. Especially since it's behind the 3 mage door and usually not the easiest place to get to.

Will go farm more, however, as I do have THF sub and Portal Charm.

**Comment by Shoruto** [comment]
Refer to #1388 and reply to it.

**Comment by bkesecker** [comment]
@TorchlightEden Were you able to progress?

**Comment by TorchlightEden** [comment]
@bkesecker Yes, the work around this random bug is to just farm another pile of answer sheets to trade to Koru to force the quest forward.
