### ISSUE TITLE
Operation Desert Swarm Scorpions WAY overtuned compared to retail.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1425]
On retail the scorpions hit a buffed Automaton for around 30-40 per hit. On here they're hitting for 90+ per hit. 
Old data on the fight I have lists hits for 60-90 with protect with 130 crits on master. Here they hit for 200+ on both galka PUP and Elvaan NIN. with crits of almost 300.

Here's a few youtube videos to back up this claim:

Taru BLM solo with 60-70 per hit with Phalanx/protect/food.
[https://youtu.be/lCMbcRAxizw](url)

RDM and DNC 75 duo. 35-60 hits with 100 damage earth pounders on a mithra DNC with buffs and evasion gear set. 
[https://youtu.be/aI0geIhIxKM](url)

BLM solo, hitting near the end for 40ish. 
[https://youtu.be/UDPB91xO5To](url)

Here is a regular party set up video. Showing multiple instances of AoEs hitting for 70-120. And melee hits for similar damage.
[https://youtu.be/SrgLLyDRPq0](url)

Now, here are the screen shots from a run me and a NIN did. PUP with merits and proper attachments was able to solo this on retail. Attempted here. It absolutely went terribly. First is the damage my automaton took. Way too high compared to retail. 
![Volkaru_2019 03 29_153157](https://user-images.githubusercontent.com/9113384/55266064-56d5a900-5238-11e9-80e2-196266679d8c.png)

And here is the damage done to Galka PUP and Elvaan NIN.
![Volkaru_2019 03 29_153206](https://user-images.githubusercontent.com/9113384/55266095-7d93df80-5238-11e9-98f1-6bb4bf246794.png)

As it stands the fight is much harder to complete for most classes due to the literal doubling of the damage the scorpions would do on retail. there is a multitude of other videos and screen shots from retail that also show proper damage numbers in various situations.

Thank you for your time in reading this long report.

**Comment by Shoruto** [comment]
I would partially agree as what I'm finding shows the initial damage taken to a buffed tank is between 70-80 damage when all 6 scorpions are up.  As each scorpion dies the damage is going up by roughly 30-35 damage.  I saw when only one was left a hit of 251 on a fully buffed tank.  The one part that never changed was the AoE damage no matter how many were still up.  It stayed between 115 and 162 damage.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
