### ISSUE TITLE
Missing Dark Elemental in Xarcabard

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#1426]
I checked pretty early in dark weather and there was no one in Xarcabard so I don't think anyone killed it, but there was no Dark Ele in G10 near the LB2 Hound. 

The other 2 southern ones were working properly, though.

https://vignette.wikia.nocookie.net/ffxi/images/1/18/XarcabardElementals.png/revision/latest?cb=20060412194600

**Comment by Serephim** [comment]
All of them were there when I killed them today except the one at G-10. It's always been missing on Kupo and Eden.

**Comment by Far-The-Killer** [comment]
All including the G-10 elemental exist on my server, might just have to search around a bit for it.

**Comment by mlandrum22** [comment]
I have wide scan and it wasn't on it.

**Comment by Far-The-Killer** [comment]
http://www.ffxidb.com/zones/112/dark-elemental
