### ISSUE TITLE
Windurst Quest "A Greeting Cardian" bugged

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1427]
On the character "Nuwa" I spoke with Kororo to start the quest, spoke with One to give him a greeting, zoned and waited one earth minute, and attempted to go back, but the line she gives is, "I'm still newy around here, so they won't let me helpy out in creating the Cardians yet."

Instead of the lines to progress the quest towards going to Buburimu Peninsula.

I think this may have occurred due to the fact that I was able to start the quest before zoning after completing this prerequisite quest "The All-New C-2000". I was able to start without having to zone and I think that might have messed with the progress flag for the quest.

Can I have this quest data reset or the next flag tripped so that I can progress through the quest?

**Comment by Shoruto** [comment]
One suggestion is instead of doing the 1 minute wait as it says in the most current update in Wiki, follow the page for Sept 10, 2007 that says wait till JP Midnight.  After JP Midnight and having zoned, talk to Kororo again.

**Comment by archfiendrubicante** [comment]
It does seem to be that the quest was changed later and retail and that waiting until JP midnight does properly start the next phase of the quest. Closing the issue.

**Comment by godmode** [comment]
After that time is finished if it doesn’t progress please update the ticket and can reopen it.
