### ISSUE TITLE
Voluptuous Vivian not popping

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#143]
I'm not sure if it's because of bad rng, the pop chance being too low, or if she's just not working but I haven't been able to get her to pop since the Eden Launch. Yesterday I killed 25 place holders over the course of the day. Overall I probably killed close to double that.

Edit: She should also be a 16+ hour lottery pop. Friend said she was a 24h lotto in dsp.

http://ffxiclopedia.wikia.com/wiki/Voluptuous_Vivian

**Comment by gweivyth** [comment]
I have passively been watching for her while chocobo digging and have never seen her on Eden even once.

**Comment by Oyaziiiiiii** [comment]
I think you're thinking Vilma but that's another one that should probably be looked into.
