### ISSUE TITLE
Yoichinoyumi Relic Weapon quest text missing.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#1432]
When starting stage 3 of the Yoichinoyumi (Bow) quest the NPC Switchstix in Castle Z does not give any instructions on which weapons to bring him. Instead of detecting your Wolver Bow and asking for a Power Bow, a War Bow and a Shigeto Bow he just says his normal dialogue text. But when I traded the bows he advanced the quest anyways.
Not a huge deal, just might confuse people since it did do this for stage 2.

**Comment by rude-jerk** [comment]
Resolved in November 16, 2020 patch.
