### ISSUE TITLE
Pirates

### ISSUE THREAD

**Issue by Deepupuu** [EdenServer/community#1433]
Pirates aren't working again it seems. I've been riding mhuara to selbina only setting my HP in mhuara for 10 hours today and saw sea horror 4-5 times today but no pirates. Today is day 3 of riding the boat all day and no pirates, Ive seen sea horror 10-20 times and no pirates. The first sand charm I got it took 6-8 hours of riding the boat but I got to see pirates twice within that time now its been about 20-30 hours and 0 pirates.

**Comment by archfiendrubicante** [comment]
I checked the NPC on the way to Selbina from Mhaura, and got this message from the captain at the end of the boat ride. I also didn't get a "boat departure" cutscene.

https://gyazo.com/3f4d7cdeeecc9cdc0d437bc51ef6b410

Could this have something to do with the pirates not spawning?

**Comment by Setz0r** [comment]
Apparently, pirates have been temporarily disabled to see if a client crash bug is related.

**Comment by Hatberg** [comment]
Any info on reactivation of pirates?

**Comment by godmode** [comment]
They shouldn’t be deactivated. They should be present yet.

**Comment by crimson-woof** [comment]
I just rode on one ferry 8 times, and the mirrored ferry 7 times, no pirates.  Is that too small sample size?  It took me almost 4hrs to verify.  I will finish out my 8th ride on this ferry but it seems unlikely no pirates in 4hrs?  I will try again at a later time.

**Comment by CdoubleOkay** [comment]
https://gyazo.com/03b115e7c05720e800a852d2abccc271

**Comment by CdoubleOkay** [comment]
`<a href="https://gyazo.com/03b115e7c05720e800a852d2abccc271"><img src="https://i.gyazo.com/03b115e7c05720e800a852d2abccc271.png" alt="Image from Gyazo" width="340"/></a>`

**Comment by kicker300zx** [comment]
Has anyone confirmed this yet? been riding the boat for a few hours.

**Comment by Setz0r** [comment]
They are just scared of Eden people i think...  they were working, then something changed and now they aren't.  I have yet another "fix" proposed, we'll see come patch time

**Comment by Raphtalia1** [comment]
Pirates still not working after 5/20 patch, boat still depositing players at destination occaisonally

from what ive been told, that happenes when pirates should happen

**Comment by Raphtalia1** [comment]
unable to find pirates after 7 hours of boating after 5/21 patch, no glitch warps either.

**Comment by archfiendrubicante** [comment]
I believe the pirates event is now working as intended, this issue can be closed.

**Comment by Setz0r** [comment]
it can, thanks!
