### ISSUE TITLE
Shadow lord following group outside of arena

### ISSUE THREAD

**Issue by falisaxi** [EdenServer/community#1435]
Attempted the Shadow Lord fight, things didn't go so well so we decided to run. The boss followed us out of the arena into the main walkway you get teleported out to. Definitely not something that should be happening! Screenshot posted.
![Raine_2019 03 31_012026](https://user-images.githubusercontent.com/48370698/55287551-45d38780-535f-11e9-8eae-0814a6915746.png)

**Comment by ababyduck** [comment]
Happens with other BCs as well, including Mammets.

**Comment by 59blargedy** [comment]
issues like this should be resolved by recent updates
