### ISSUE TITLE
Crystal drops are incorrect

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#1436]
Sometimes I'll get 2 crystals from a mob even though I'm going solo. What I noticed today though, is that someone came and tossed me a cure while fighting a crab in qufim, and I ended up getting 2 crystals. I think the enmity from the guy that cured me made the mob drop 2 crystals instead of 1.

**Comment by Shoruto** [comment]
I get 2 crystals ever now and then.  I don't believe this is an error.  Can't recall though if it happened during era.

**Comment by beauxq** [comment]
The maximum number of crystals that drop should be the number of people with signet in the party that gets the kill.

(Note that this is true even for an alliance fight. If you have an alliance with a party with 6 signet, and a 2nd party with 0 signet, and the 2nd party gets the killing blow, you don't get any crystals, even though you have 6 signet in the alliance. This is how it was in retail era.)

**Comment by Shoruto** [comment]
Kinda interesting but I seem to get more double wind crystals then any other type.

**Comment by Mahou81** [comment]
Can confirm this issue. You shouldn't be getting double crystal drops when soloing.

**Comment by KnowOne134** [comment]
correct only 1 crystal per member in party with higher randoms per crystal

**Comment by KnowOne134** [comment]
Resolved in February 20, 2023 update
