### ISSUE TITLE
Auction House Item Duplication

### ISSUE THREAD

**Issue by brndmfrd** [EdenServer/community#1437]
Items that I have sold in the past were found in my auction house "Sales Status" menu despite being sold days/weeks ago.

I went to the Windurst Woods AH.
My current goodies were not selling so I pulled them (stop sale) intending to lower the price.
Verified my goodies were all gone from the AH (not selling anything).
Attempted to sell new goodies and met with a general failure in my chat log - "Failed to place merchandise on auction".
I checked what I was selling (sales status) and found a list of 6 items I sold three days ago (estimated time).
I pulled these items (stop sale) and sure enough found them back in my inventory.
I was able to repeat this and acquire items I sold even later.
In an attempt to capture a video and repeat one more time, the bug disappeared, I no longer had items on the AH (sales status) and I could sell new items once again.

Sadly, I was not selling kraken clubs this week, only gausebit grass, if the items being sold makes any diff.

**Comment by MGramolini** [comment]
How many auctions would you estimate you had for sale at the time?

**Comment by brndmfrd** [comment]
I typically max the number of auctions I'm allotted at a time when I visit the auction house. So, I would estimate I had 6 auctions.

**Comment by MGramolini** [comment]
If you do not check the "sales status" you can post as many as you want.  So i feel like you maybe just posted more items than you think you did.
