### ISSUE TITLE
character stuck and won't load 

### ISSUE THREAD

**Issue by eskimoslayer** [EdenServer/community#1439]
My alt missymay is stuck in woodworking guild after talking to Advanced synth npc. chose the middle option on accident and froze my character. I hard crashed game and now will not load into game.

**Comment by eskimoslayer** [comment]
got her back in. but just a heads up on the issue if it persists.

**Comment by Shoruto** [comment]
Thanks for the update

**Comment by Setz0r** [comment]
this has been fixed in a recent update
