### ISSUE TITLE
memory drop rates in Promys are not correct

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#144]
Looking at the base DSP rates and then reading up about Memories and how they should drop (also with the pending update to warp scroll costs due to warp cudgels being available) I've come to the conclusion that their drop rates are very wrong. (rates are at 1-10% for the most part off the Wanderer type mobs in base DSP).

Issue number 1: The type of memory should be dictated by the element of the core of the Empty mob that you're killing.
http://ffxiclopedia.wikia.com/wiki/Memory
DSP doesn't appear to support this and it doesn't appear to be supported on Eden either.

Issue number 2: Due to issue number 1, the drop rates shown on FFXIClopedia & within the FFXIDB are skewed.
http://ffxidb.com/zones/18/wanderer

Looking here it would seem that the rate of anima drops is from 7-17%. 

If you add up all of the drops compared to the reported kills you'll see that 20,235 drops have been reported out of 28,390 kills (I'm ignoring the Remnant because it is a separate drop pool, which is specific to the mob type and not related to the core of the mob).

This puts the chance of getting a memory at 71%.
The low rates on each of the memory types is explained by the different Core types of the mobs being killed, however the tool that FFXIDB uses to gather this data isn't accounting for the core type of the mobs being killed.  This could further be skewed because we don't know the number of mobs of that core type that were killed.  Due to the nature of the way the memorys drop, it is entirely reasonable that some of the types are underrepresented as a total % of kills because the memory dropped by them isn't as desirable as the memories dropped by others.

This data is unfortunately from the time after the promys were uncapped so TH2+ is possible, where normally it shouldn't be and FFXIDB doesn't expose the sample size of each TH level, so its hard to have complete confidence.

I'm not entirely certain of what the solution should be, since I expect it would be a lot of effort to code in the Core types, but the drop rates are definitely too low if we want to have an economy where items such as Warp Cudgels, Reraise hairpins ect... are affordable and plentiful

**Comment by chlorr** [comment]
Well in about 4 hours, ive farmed around 110~ memories solo . anywhere from 0-3 mobs on avg per drop. And ive also got 3 to drop and a recollection from 1 mob. seems pretty fair to me as they are all EP-(-) and no TH (went with TH1 still). Didn't keep track, but my logs are good to look at.

And yeah they deff. do not follow the core element for drops. I've yet to try other promies, as less  mobs to kill. But it might be they have the other Mems. on a more common drop. In Dem i'm seeing mostly 3 types, then random for the others at a 3/4:1 ratio.

 Will test out Holla and / or Mea later on tonight

**Comment by roriffxi** [comment]
Each of the different promies do have different rates.  For example, Fleeting Memories (in base dsp) are a higher rate from the wanders in Mea than in Holla / Dem when fighting the EP wanderers on Floor 1.

**Comment by godmode** [comment]
This will probably be fixed when we set elements per mob

**Comment by Serephim** [comment]
All i know is I spent 7 hours farming the first 2 floors of Mea and Dem and got dozens of other types but only got 3 fleeting. They are exceedingly rare.
