### ISSUE TITLE
OOE Synth - Date Tea

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#1440]
EZmode synth that's abusable to reach 100 cooking that wasn't introduced until 2012.

Cooking (105)
--
Pot Of Maple Sugar x1
Clump Of Imperial Tea Leaves x1
Flask Of Distilled Water x1
Date x1

**Comment by Shoruto** [comment]
This is definitely a post era synth.  Nothing was posted until March, 2012 and it is 105 skill level.  Needs to be removed as soon as possible to minimize the chance of being used as a skillup option.

On the ffxiah forums link (last one) you will see several posts from 2012 regarding players using Date Tea for post skill 100 crafting.

https://www.bg-wiki.com/index.php?title=Date_Tea&oldid=218595
https://ffxiclopedia.fandom.com/wiki/Date_Tea?oldid=1391463
https://fr.ffxiah.com/forum/topic/30600/skill-up-100-110/1/

**Comment by ababyduck** [comment]
If the GMs aren't already on top of this, there's been at least one guy yelling to buy Dates for the last couple days, and one post on the forums asking about harvesting them. No doubt people are abusing this whether they realize it or not.

As someone with 93 cooking deliberately avoiding this synth, I sincerely hope that the people abusing it won't be allowed to keep those levels.
