### ISSUE TITLE
Lindwurm Skin drop rate is incorrect

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#1441]
I'm something like 1/11 on lindwurm dropping lindwurm skins on this server. Volkaru suggested to me that in the base code lindwurm skin might be set to the drop rate of valiant knife, 6% which is incorrect. According to http://www.ffxidb.com/zones/205/lindwurm the drop rate of lindwurm skins is something approaching 100% for the first one and tapering off after. I imagine it follows a similar pattern to yowie.

**Comment by Shoruto** [comment]
Not finding anything regarding drop rate during era, not even videos.  My question is the numbers that are showing on ffxidb, are those updated by players during post era or during era. It does say the data is as of the 2015 patch. If that's being skewed by both sets of numbers, then it wouldn't be accurate to go off of.  I wish there was a way to separate the numbers from a certain date.

**Comment by Volkaru** [comment]
@Shoruto As far back as 2009 it says it can drop multiple skins. https://ffxiclopedia.fandom.com/wiki/Lindwurm?oldid=934098
I remember in era this NM would drop them like candy, similar to Yowie, etc.
The only update I saw from 2014/15 was one to make the skins stackable.

**Comment by Shoruto** [comment]
Gotcha, good to know

**Comment by mpinholster** [comment]
I have chatted with Jimmy about this.
As a BST back then I use to hunt a lot of the Lizards0(going by the beastmaster chart) NMs for skins like Amemet, Lindwurm, Yowie and Tarrasque.
I think it was always 100% for one and Treasure Hunter would open up additional slots.
