### ISSUE TITLE
Some mobs Randomly despawning in the dunes

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1442]
Sometimes when walking by an enemy it will vanish and disappear as if it was never there in the first place. I'm unsure whats causing it but its occurred at least four times in the last 24 hours for me, so its pretty consistent that it occurs.

**Comment by archfiendrubicante** [comment]
Update:
Upon trying and attempting to farm Valkrum emperor today, upon killing one of the damselflies in the area, the other damselflies would vanish. I am unsure as to the cause of this, but it happens enough that I can repeat it consistently.

**Comment by bkesecker** [comment]
I have seen this behavior most prevalent in wide open outdoor areas.  It is almost like the mobs roam patch is a square rather than a circle, and when the despawn if too far from spawn point check is done, succeeds because the mob was in a corner.

**Comment by bkesecker** [comment]
As I understand it, this is a combination of the distance away from spawn point plus the time too far away.  XiNavmeshes determines the roaming, but Eden code determines what factors lead to a despawn.  Despawning on Eden is intentional.

**Comment by gtapperdesign** [comment]
Can confirm this is happening in the dunes. Sometimes a Damselfly will only be alive for 20 seconds and not even 20 yalms away from its spawn and it'll still despawn. It's happened during the day too so it's not like the mob pool is clearing out for night mobs.

**Comment by slassen** [comment]
I should have fixed this as of the last patch.
