### ISSUE TITLE
Warp Scroll in Aht Urghan is really cheap

### ISSUE THREAD

**Issue by mpinholster** [EdenServer/community#1443]
I heard on LS that Instant Warp Scrolls in Whitegate are only 10 IS.

Guessing they are supposed to be more?

I haven't checked this myself yet, because if its untrue, I don't want to burn 750 or 800 IS.

**Comment by Shoruto** [comment]
If it was indeed 10 IS, it is based on retail, not era.  It should be 750 IS for era

https://ffxiclopedia.fandom.com/wiki/Instant_Warp?oldid=348848
https://www.bg-wiki.com/index.php?title=Instant_Warp&oldid=118047

**Comment by KnowOne134** [comment]
rolling this issue into this one
https://github.com/EdenServer/community/issues/1713
