### ISSUE TITLE
Weapon Skills Guaranteeing Weapon Skillups

### ISSUE THREAD

**Issue by SBC-Nyxai** [EdenServer/community#1444]
I have dagger skill 245 and I am getting guaranteed skill-ups off of mobs below level 37 that are too weak whenever I use a weaponskill.

**Comment by SBC-Nyxai** [comment]
So I am not getting guaranteed skill-ups anymore. But it is an extremely high rate of skill-up. Sometimes I gain 1.3+ levels of dagger skill on too weak mobs.

**Comment by CloudyDesarroi** [comment]
Can confirm having this occur with polearm as well.
![Desarroi_2019 04 01_181841](https://user-images.githubusercontent.com/30502556/55369288-cfdc3700-54aa-11e9-8f7c-afd497d15f39.png)

**Comment by carmdeldensan** [comment]
Swords too confirmed

**Comment by Suzarn** [comment]
Scythe as well.

**Comment by CloudyDesarroi** [comment]
Using an archery WS as Ranger seems to have given skill-up for my main hand weapon (dagger) rather than archery.

**Comment by agjevik999** [comment]
I had the same issue with my Sword skill around 100. Skilling up on mobs way lower then my level.
