### ISSUE TITLE
Jotunn Hallkeeper(MNK) attacks too fast

### ISSUE THREAD

**Issue by Altnob** [EdenServer/community#1445]
These mobs attack way too fast at the moment. Probably around a 200delay double attack which is not normal.

**Comment by Volkaru** [comment]
This was also an issue for MNK mobs in ToAU. 
For the dev who looks at this, Morris figured out the issue there. They were MNK/MNK. And for mobs it seems the same tier of Martial Arts was stacking for them. So they'd get a massive delay reduction.

**Comment by beauxq** [comment]
probably goes with this: https://github.com/EdenServer/community/issues/503
