### ISSUE TITLE
Madflies In Gusgen Mines Have Double Attack Now

### ISSUE THREAD

**Issue by Momo027** [EdenServer/community#1446]
The Madflies at Gusgen Mines killed by exp parties now seem bugged, they can now Double Attack, although at a semi-low rate.  Just finished the worm section of our party and right as we started flies, 3 members died within 5mins, all from Double Attacks.  We've exp'd here in the past a ton and are 99% sure they could never Double Attack before.  Seem's they got bugged with today's (April 1) update.

**Comment by Suzarn** [comment]
They are supposed to have double attack. They are warrior class above level 25. It is not a bug.

**Comment by greyenvy** [comment]
So some of these mobs were renamed in retail and put in place for level 75+ to exp on from what others have told me.  They’re supposed to be level 84-88 and ibar plugin will tell you that but it seems on this server these mobs have the same level as the other mobs in the same family in the zone. Hence Madfly are exactly the same as Sadly and are level 25-27 so they will have double attack.

Other examples of this include the King Crawlers, Dancing Jewels, and Olid Funguars in CN are exactly the same levels are Solider Crawlers, Hornfly, and Exorays, respectively.

**Comment by gweivyth** [comment]
Have all flies been updated to the right job?  Because none of the flies people have been exping on have been double attacking before now.  Source: Every Crawlers' Nest or Zi'Tah party in the past year and a half.

**Comment by tacbox3** [comment]
That's incorrect gweivyth. Zi tah flies do indeed double attack. I remember dying to one, not something you easily miss when it's associated with a death.

You might be able to convince me that the rate is too low, however.

**Comment by gweivyth** [comment]
> That's incorrect gweivyth. Zi tah flies do indeed double attack. I remember dying to one, not something you easily miss when it's associated with a death.
> 
> You might be able to convince me that the rate is too low, however.

It could also be a recent change, it's definitely been months since I've exp'd in any of those places.  My last job that I played that low level was DRG and that was right when Eden launched.
