### ISSUE TITLE
Can't desynth Iron Splitter +1

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#1449]
https://ffxiclopedia.fandom.com/wiki/Iron-splitter_%2B1

**Comment by Shoruto** [comment]
This is so weird...While wiki does show that there is a desynth for the Splitter +1, all the other places only show desynth available for the NQ Splitter. not for the HQ version. 

**Wiki showing HQ Splitter desynth**
https://ffxiclopedia.fandom.com/wiki/Iron-splitter_%2B1?oldid=359502

**Other places not showing HQ desynth available**
**NQ** - https://www.ffxiah.com/item/17569/iron-splitter
**HQ** - https://www.ffxiah.com/item/17570/iron-splitter-1

**NQ** - https://www.bg-wiki.com/bg/Iron-splitter
**HQ** - https://www.bg-wiki.com/bg/Iron-splitter_%2B1

**Comment by panfunk** [comment]
This report made me curious, and imo it could very likely be that every HQ can be desynthed, just noone tried/reported that f.e. Haubergeon+1 can be desynthed.

Most HQs are simply worth more than the desynth with a few execption like 'Iron Splitter+1' or Gold Earring+1 (desynth dates back to 2006)
https://ffxiclopedia.fandom.com/wiki/Gold_Earring_%2B1?action=history
