### ISSUE TITLE
Chaupire is never restocked

### ISSUE THREAD

**Issue by Kai-Tybalt** [EdenServer/community#145]
Character: Tybalt
Nation: San d'Oria

Carpenter's Guild (in San d'Oria) merchant Chaupire is never restocked and I had trouble opening the "buy" option.

**Comment by MGramolini** [comment]
Is the delay too short or too long for item drops? I recall it being 3 or 5 minutes.

**Comment by godmode** [comment]
Hi, thanks for posting. I edited your ticket since the others were already reported.
