### ISSUE TITLE
Bloodsucker NM incorrect spawn conditions

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#1457]
Instead of spawning 21-24h after server reboot as it should it seems it spawned upon server restart. It's supposed to be 21-24h and then 72 hours after Time of Death.

**Comment by Suzarn** [comment]
As far as I know, only HNM timers persist on Eden and it should stay that way until every NM has it because the server has random crashes all the time. Resetting the timer every time the server goes down would effectively make it impossible to get some items.

**Comment by Mozzy4Ever** [comment]
Can be closed. Spawns as it should now.
