### ISSUE TITLE
Mining removing sneak buff

### ISSUE THREAD

**Issue by LongTimeGaming** [EdenServer/community#1461]
While trying to mine, I noticed that sneak was being removed as I was mining which shouldn't be the case. Only invisible should be removed. Please see my old retail picture of me mining in Mount Zhayolm and only invisible being removed from me and not sneak. Please advise.

![pol 2009-12-15 07-14-58-21](https://user-images.githubusercontent.com/47086093/55506809-5e27f880-5624-11e9-9527-d1b9576db9f9.jpg)
![pol 2009-12-15 07-01-07-42](https://user-images.githubusercontent.com/47086093/55506810-5e27f880-5624-11e9-9887-b7e1c586e211.jpg)
![pol 2009-12-18 23-03-06-53](https://user-images.githubusercontent.com/47086093/55506885-80ba1180-5624-11e9-885c-b64958bfd409.jpg)

**Comment by TorchlightEden** [comment]
This also occurs with opening the doors in sea serpent grotto, which it's also not supposed to.

**Comment by Suzarn** [comment]
I searched a bunch of old guides and none of them explicitly state that sneak drops from gathering. They only imply it. "Get safe and reapply sneak." This could just be the guide trying to be extra careful and advising to keep the sneak timer as high as possible.

**Comment by LongTimeGaming** [comment]
I'm showing you with pictures, that sneak doesn't drop while mining. It shouldn't be a thing.

**Comment by Suzarn** [comment]
Right, but I have not found anything that says sneak should drop when gathering. It would be pretty simple to test if someone has an active retail account.

**Comment by Setz0r** [comment]
sneak gets removed no matter what you trade. well. it used to ;)
