### ISSUE TITLE
Giddeus - Kiting Mass Amounts of Mobs gives you 3000+ Ping

### ISSUE THREAD

**Issue by Dabman710** [EdenServer/community#1462]
Farming Yagudo Necklaces so I kited the mobs around in Giddeus, as soon as I got all the mobs together, probably about 25+.. my ping went from 150 to over 3000+ and was taking minutes to do one action. On top of freezing every time a mob casts a spell on you, I was infinitly stuck until I either dced or died. This is not an internet connection issue, someone else said it happened to them too.

**Comment by Serephim** [comment]
Yeah.... 
Don't pull more than 20-25 mobs together or you will basically start to lock up. lol
Not really a bug, more of server limits.

**Comment by ababyduck** [comment]
Not a bug. While there's always room for server optimization, what you're most likely seeing is client-side animation lock. It's pretty common in Giddeus due to all of the BLMs and BRDs casting on you. Training too many at a time gets dangerous, and this happens on retail too.

Also the R value is not ping, it's just your downstream. It's natural that you're going to be **R**eceiving a lot more data when you train a large amount of mobs.

**Comment by Strumerjohn** [comment]
It's a bit different than client-side animation lock. You can typically safely stop at ~22 monsters before things start to get to a point where there's "input delay" on your actions. Even if you're not being whacked on by monsters (i.e you're someone else in the area near a large group that's been pulled), it is apparent. R doesn't seem to go above 3,000ish and the client and server seem to get out of sync when it is.

**Comment by Setz0r** [comment]
Packet optimization has already taken place and this doesn't seem to be a reported issue anymore.   Server lag happens, and the client can only properly handle so many entities within range.

**Comment by Althaia** [comment]
This used to happen to me, until a friend pointed out to me that there was a rule that we shouldn't train more than eight monsters at a time, so I stopped doing long Giddeus trains. If you think it's been fixed, you can change the rule...

[Terms and Conditions](https://www.edenxi.com/forums/viewtopic.php?f=31&t=66)

Expressed Rules:
2. Until a technical solution is implemented; no more than 8 monsters may be intentionally gathered to kill at the same time.
