### ISSUE TITLE
Corsair Rolls seem to be giving the wrong values

### ISSUE THREAD

**Issue by Culltrip** [EdenServer/community#1464]
I did evokers roll & i noticed on one roll of an 8 someone was getting back 1mp per tick rather then the 2 it should have been, & later on a 10 they were getting 2 rather then the 3 they should have

**Comment by Shoruto** [comment]
Reference #1108

**Comment by VerrenGunnar** [comment]
In that post its claiming bust doesn't work & then the admins explain why hes wrong, that is a separate issue even if its the same roll

**Comment by Shoruto** [comment]
Since this is dealing with the same ability, it needs to be grouped together not by you but the devs that way they can know that the ability has a couple issues with it.

**Comment by godmode** [comment]
It’s fine to have separate issues even if it’s about the same roll. That way we can fix one and not the other and close a ticket

**Comment by Shoruto** [comment]
Agreed

**Comment by 59blargedy** [comment]
could not replicate and code seems fine, assumedly solved long ago
