### ISSUE TITLE
Corsairs "Healer Roll" giving out of era buff

### ISSUE THREAD

**Issue by VerrenGunnar** [EdenServer/community#1465]
In era Healers Roll is supposed to give a "MP recovered while healing" buff, it was only in 2012 that it was changed to a cure potency buff, but on eden it is currently cure potency & not resting MP

**Comment by Shoruto** [comment]
Reference #972

**Comment by VerrenGunnar** [comment]
That post doesnt specifically refer to this issue & simple claims there are dat issues and merchant issues, 
Also both another COR in my LS and I have tested it and can confirm that healer does not currently give hmp & therefore either gives nothing or a healing buff

**Comment by Shoruto** [comment]
They both are dealing with an out-of-era buff.  Even if they're not exactly alike,  they are still related enough.  Since this one is slightly different, it definitely can stay here I just wanted to reference a similar report for the devs.
