### ISSUE TITLE
Hitting the Marquisate 

### ISSUE THREAD

**Issue by Tlandy** [EdenServer/community#1466]
Have completed all the prerquisites to continue this quest. However I get stuck at the Garlaige Citadel part. I have KI Cat Burglar's Note, and Bomb Incense. 

Contacted GM in game, and he told me to double check if I did this part:

Go to Lower Jeuno (G-10) and speak to Yatniel (he's a bit southwest of 'Gems by Kshama').
After he finishes cursing at you, trade 4 Quake Grenades to Yatniel.

I knew I had done that part already cuz spending the gil on the 4 Grenades is something you will rememeber lol, but just to do what I was told from the GM and cover the "What if's"  I did it again, with no success to progression but just an other -18.4k gil xD 

Please help!
Look forward to solving this issue.
Thank you

Tlandy & Madgreek

**Comment by Shoruto** [comment]
When you say stuck, which part of it did you get stuck with?  Since there are a bunch of instructions, just wanted to check before responding with suggestions.

**Comment by Tlandy** [comment]
Sent from my Huawei phoneI cant begin the Garlaige citadel part. -------- Original Message --------Subject: Re: [EdenServer/community] Hitting the Marquisate  (#1466)From: Shoruto To: EdenServer/community CC: Tlandy ,Author When you say stuck, which part of it did you get stuck with?  Since there are a bunch of instructions, just wanted to check before responding with suggestions.

**Comment by Shoruto** [comment]
Is it just me or did Tlandy's response not show properly?

**Comment by Tlandy** [comment]
Hey, I'm sorry. Was sent from phone all messed up. 
Where I can't progress further on to the quest is the Garlaige Citadel part where I need to start examining all the ???.

**Comment by Shoruto** [comment]
Are you unable to open the banishing gate or you unable to locate any ??? Or is selecting the ??? not giving you the option to go to the next one. Can you try to be a little bit more specific on what exactly you're stuck with.

**Comment by Tlandy** [comment]
Clicking the 1st set of ??? does nothing.
 I'm suppose to hit the 1st ??? by the  banshing gate which opens up the next part of the quest, which requires me to click a sequence of ???.

**Comment by Tlandy** [comment]
??? not giving me the option to go to the next one.

**Comment by bkesecker** [comment]
Original issue: https://github.com/EdenServer/community/issues/1074

**Comment by 59blargedy** [comment]
looks like this was never closed when the fix went in in 2019, so closing now.
