### ISSUE TITLE
Grotto Bats incorrect spawn behaviour

### ISSUE THREAD

**Issue by falantar** [EdenServer/community#1467]
Spawning inside Yughott Grotto from 18:00 to 6:00, i believe they should be up at all times. Haven't had this issue in Korroloka so it might just be the grotto.

**Comment by Shoruto** [comment]
There are conflicting places the show spawn conditions. These first two show no sign of it spawning only at night however the last one does specifically says spawns at night.

**No spawn conditions**

https://ffxiclopedia.fandom.com/wiki/Grotto_Bats?oldid=373443

https://www.bg-wiki.com/index.php?title=Grotto_Bats&oldid=48850

**Spawns at night**

http://ffxi.allakhazam.com/db/bestiary.html?fmob=440

**Comment by falantar** [comment]
I see. I personally don't remember any cave bats spawning by time, but I think zam is the most era accurate of the 3 so I'll just close it.
