### ISSUE TITLE
Ghost Mob @ H-9 of Arrapago Reef Sight Aggroes

### ISSUE THREAD

**Issue by RenaviOnEden** [EdenServer/community#1470]
Title pretty much covers it, had sneak on only after trading Lamia Fang Key to the Iron Gate, started to run past the Phasma to the 2nd gate otw to finish COR quest and it aggroed me, assuming because of sight.  HP wasn't low and sneak was still on from before.

**Comment by Far-The-Killer** [comment]
Just tested and looked at the DB, no aggro by sight. Your sneak probably wore off after trading to the gate and you didn't notice.
