### ISSUE TITLE
Abraxas Lufaise Meadow

### ISSUE THREAD

**Issue by ElectroNicMan83** [EdenServer/community#1473]
Abraxas are too weak at 75, there was a topic on it 6 months ago but it got closed.  

If you let them too weak can we farm them? ( asking before doing it.)

**Comment by godmode** [comment]
What do you define as too weak? As in they don't have enough defense or they /check as "too weak"?

**Comment by ElectroNicMan83** [comment]
They /check too weak anyone could solo them at 75.

**Comment by godmode** [comment]
Oh I see, I’ll fix it for next patch. Thanks for reporting you can farm for now.

**Comment by MGramolini** [comment]
They were probably incorrectly set to a similar level to https://ffxiclopedia.fandom.com/wiki/Diatryma .
