### ISSUE TITLE
Brass Nuggets NPC price too high

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#1474]
https://ffxiclopedia.fandom.com/wiki/Brass_Nugget?oldid=1654301
Currently brass nuggets are NPC'ing for 940 gil
Not much info from the past, but current retail price appears to be 5gil.  Not 940 gil (and gold nuggets, which appear to be accurate only NPC for 179 so I'd be inclined to believe that the current price is very-very wrong)

**Comment by MGramolini** [comment]
If you compare to mythril, it seems the nuggets npc for about 1/10 of what an ingot does.  If you follow that pattern, 5g would be correct.
