### ISSUE TITLE
Dawn Mulsum should be 98 (new evidence not a change in level)

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#1475]
https://ffxiclopedia.fandom.com/wiki/Dawn_Mulsum

Currently set at 97 and should be 98.

**Comment by Shoruto** [comment]
Do you have proper _era_ evidence of it showing 98 from Nov 2007 or earlier?  Back in 2011 it was 97.  The current retail shows 98.  Nothing during era shows what the synthesis level should be.

**Comment by MGramolini** [comment]
If you look through the history, it was entirely unknown how to get the item according to the wiki until 2011.  I have gone through all of the patch notes from 2006-2012 and not found a single piece of information on this item.  Lots of high level recipes end up being off by 1 level for long periods of time because people either don't get skillups for 12+ synths on an item and decide they are over cap and move to something else, or they are less common to skill up on etc.  The note the person made when updating the wiki to be 98 was "Have received 2 skill-ups while at 97".  Based on this information i propose this item is a 98 cap.

**Comment by roriffxi** [comment]
https://www.bluegartr.com/threads/104032-New-item-to-heal-Wyverns-Automatons-Avatars-Pets-without-a-JA-outside-Abyssea

Dawn Mulsum shouldn't even exist.  It was data-mined but never activated until Abyssea.
