### ISSUE TITLE
Xolotl respawns every 1-2 nights

### ISSUE THREAD

**Issue by Altnob** [EdenServer/community#1476]
Xolotl is respawning every 1-2 nights. I'm not sure if it matters whether or not players are killing his ads after he dies but most everytime, there's a Hound Warrior chilling, so I will kill it and then Xolotl respawns either the next night or the night after.

I've seen three groups kill Xolotl today (not sure if anyone has killed it more than once)

**Comment by Far-The-Killer** [comment]
This should be fixed already. If not leave a comment, but for now I'm closing it
