### ISSUE TITLE
Crab Sushi is OOE

### ISSUE THREAD

**Issue by ababyduck** [EdenServer/community#1477]
Crab Sushi wasn't added until well into WOTG. First wiki entry is from June 2008.

Removing Crab Sushi would not only be era-accurate, but would also have a significant effect on gil inflation as people shift toward Sole Sushi, allowing fishermen to sell more of it on the AH rather than vendoring it all for ~500k/character/day.

**Comment by godmode** [comment]
Yeah, good eye. I don’t remember having crab sushi either but on Kupo that was the only choice so I figured it was a thing on ToAU retail we just didn’t have to pick it :D

**Comment by bkesecker** [comment]
Ahhhh... bummer.  #ilovesushi
