### ISSUE TITLE
Oak Cudgel not Desynthable

### ISSUE THREAD

**Issue by LokiStinkpalm** [EdenServer/community#148]
I looked on wiki and the earlier post is 2006 that shows the oak cudgel and oak cudgel +1 desynthable.  Currently it gives me an error when i try to desynth saying that "Synthesis cancelled.  That combination of materials can't be synthesized."   Makes it a REAL pain in the ass to make Warp Cudgels if i cant get my mats back from desynthing.  Link to 2006 page below:

[http://ffxiclopedia.wikia.com/wiki/Oak_Cudgel_%2B1?oldid=54751](url)

**Comment by Wiggo32** [comment]
that page doesn't actually confirm the oak cudgel +1 as being able to be desynth'd. on most things the HQ versions are not able to be desynth'd. There are some exceptions though, and I need some guidance as to whether or not this is one of them. The NQ version desynth though will be fixed and added with the next update.

**Comment by Wiggo32** [comment]
nevermind, i found it on a different wiki page: http://ffxiclopedia.wikia.com/wiki/Oak_Cudgel_%2B1

**Comment by LokiStinkpalm** [comment]
Just tried to desynth it again and it's still not going.  why is this labeled fixed?

**Comment by godmode** [comment]
Please read the descriptions of the label to get more information on what they mean. In this case fixed means we found and fixed the issue and it will be deployed on the next update.

**Comment by LokiStinkpalm** [comment]
gotcha thanks
