### ISSUE TITLE
Judgement Key not working on the Brass door in the uppermost floor in Castle Oztroja.

### ISSUE THREAD

**Issue by Geltus** [EdenServer/community#1483]
Farmed a Judgement Key off of the mnk yagudo on the top floor after assisting a friend with the crest for lb. Tried to leave through the Brass Door just past the High Priest, but using the key just gives the same message "Its Locked"

**Comment by beauxq** [comment]
I think the person who programmed this door in DSP thought that a certain Windurst mission should be required for this door. That would be wrong. The door should open with the key any time, no matter what mission you have or don't have.

The door is required for the mission, but the mission should not be required for the door.

**Comment by Geltus** [comment]
Yes, that is what I had assumed had happened. Ended up having to death warp out due to no method of warp/teleport.
