### ISSUE TITLE
Desynthesis Skillup Issues

### ISSUE THREAD

**Issue by Blex64** [EdenServer/community#1484]
Not sure if this is an intentional change or not, there's no direct mention of it in the patch notes, but it seems that Desynth skillups have some kind of issues. Desynths during a full moon. 8 Levels below the synth, with advanced support (so, 5 levels below):
![image](https://user-images.githubusercontent.com/15820441/55672263-1f35b500-5867-11e9-8066-c8d4ff7056b2.png)

Unless there was a change I'm not aware of, I should be able to skill up off all those breaks, and I'd expect to see a lot more than 0 during a Full Moon. My one completion also got me a skillup.

**Comment by isotor** [comment]
I may be wrong, but my knee-jerk understanding is support doesn't count towards hitting the skillup requirement on breaks.

**Comment by Blex64** [comment]
It has every other time I've attempted it.

**Comment by godmode** [comment]
Nothing has been intentionally changed to make this happen but I will look to see if something I did made this a side effect

**Comment by FariskaEden** [comment]
From my experience, you'll only get skill ups on breaks if your actual skill is within 5 levels below the recipe's. 6 levels or further, you'll only get skill ups from successes.

**Comment by Blex64** [comment]
Maybe I'm just taking crazy pills. Definitely feel like I've gotten support to bridge that and get the skillups but I have no hard evidence of that.

**Comment by MGramolini** [comment]
You need actual skill of 5 under cap to receive skillups on breaks.  It has been this way since day 1 kupo.
