### ISSUE TITLE
"Accuracy Varies with TP" weaponskills

### ISSUE THREAD

**Issue by Qair** [EdenServer/community#1485]
Everyone that knows me knows that I have a gripe with the way monk performs on this server. Asuran fists is straight garbage on dsp and it shouldn’t be. In the following, I want to give my observations.

First and foremost – the dsp values for weapon skills that have “accuracy varies by tp” as a modifier are completely busted. A few of these weaponskills include Dancing Edge, Asuran Fists, Penta Thrust.

The dsp TP modifiers are as follows for these three weaponskills:

params.acc100 = 0.8 params.acc200= 0.9 params.acc300= 1

Sources:

Asuran Fists - https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/asuran_fists.lua

Dancing Edge - https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/dancing_edge.lua

Penta Thrust - https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/penta_thrust.lua

All three of these weapon skills share the same negative accuracy modifier as Sidewinder(which is also an acc varies by tp weaponskill)

Sidewinder -
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/sidewinder.lua

This in itself is beyond insane, sidewinder is suppose to have a negative modifier at 1000 tp. In the description itself it even reads “delivers a powerful but inaccurate attack”

Why do mulihit weapon skills such as penta thrust(5 hits), Dancing Edge(5 hits), and Asuran Fists (8 hits) have the same negative accuracy value at 1000 tp as sidewinder/slugshot does?

Imagine if that were applied to any other “ x varies by tp” weaponskill. Should evis give a .8 crit modifier at 1000 tp so that you actually have a less chance to crit? How does that make any sense?
 

Your accuracy should raise with your tp, not be penalized unless you’re at 3000tp

Beaux posted the fix for this here -
https://github.com/bdhs/darkstar/commit/bb97b5c1ae07be63eb3332ee4693fc0c16b7bd4a

Please implement this fix.

#savethemnkclass  

Mnk is really hurting on this server and this is one of the reasons.

**Comment by panfunk** [comment]
I can't speak for MNK, but as retail THF I can add that on Eden Dancing Edge is outperformed by Shark Bite in every situation except when using it on EP mobs without SA/TA.

iirc Dancing Edge should be the strongest THF WS ~80% of the time. Outperformed by SB only on HNMs cuz you can't stack that much accuracy to get 5Hits on them.

**Comment by Enignite** [comment]
I'd like to add that in addition to all of this, the actual calculations for the acc penalty is incorrect as well. currently the params.acc100 = 0.8 means that you WS with 80% of your total Acc, not hitrate but Accuracy meaning you could having -80 Acc or more at 75 with these WSs. Obviously due to the way hitrate works in FFXI having something that scales like this is bad idea, they should be fixed -40/-20/0 Acc for Slugshot/Sidewinder (I think, from tests posted on killingifrit as i can't find the post anymore).

**Comment by Qair** [comment]
I did a little testing on dancing edge last night and it suffers the same effect as asuran. 95% hit rate and returning sub 100 tp consistently with a few exceptions of higher tp returns. These values make these weapon-skills unviable for this server. I haven't tested penta thrust yet, but i assume it's in the same boat. Luckily polearm gives piering bonus vs most exp mobs and thf has sharkbite. Monk is currently shit out of luck as all of its other weaponskills are also subpar.

**Comment by gweivyth** [comment]
Penta behaves exactly the same way, although I'd be down to team up tonight and run some tests.  I have 75 MNK, THF, and DRG so I can actually test all three of the current case samples.

**Comment by Qair** [comment]
I parsed Riaq verse Greater Colibs today and was able to do 53 weaponskills. No focused was used and all hits had crab sushi for the most part.

Max TP possible for Asuran Fists = 158 tp, which seems low but that's besides the point
Riaq's melee Accuracy was 94.43%
Riaq's average weaponskill return was 123 tp per asuran
Riaq's weaponskill average was 412 damage with MINUET taking my attack from 394 to 451.

I'm not sure how multihit weaponskills are caluclated so I just divided 158 / 8 to get 19.75 tp per hit.

Conclusion - Asuran Fists was only hitting 6/8 hits on average and I was only able to get a full tp return 4 times out of 53 weaponskills. 4/53 = 7.5% chance to land all 8 hits in this sample. 

According to wiki
Due to the 95% accuracy cap there is only a 66% chance of all 8 hits landing, so approximately a one third chance of missing some of the hits at the cap.

**Comment by isotor** [comment]
I'd just advise that pointing to wiki as a datapoint is dangerous. As usual in fact, that quote is useless as some genius just decided to calculate 0.95^8 (=0.6634) and present that as evidence on how Asuran Fists actually works.

**Comment by Qair** [comment]
I agree, but i can't find parses from 2007 nor any indicators that asuran should have the same accuracy modifier as sidewinder so I'm trying to use whatever i can get

**Comment by beauxq** [comment]
> I'm not sure how multihit weaponskills are caluclated so I just divided 158 / 8 to get 19.75 tp per hit.
> 
> Conclusion - 123 average tp per hit / 19.75 = 6.2 hits per weaponskill

Even though this isn't how it works, this calculation method would still work out correctly, except for the bonus accuracy on the first hit of weaponskills.
Taking that into account, you actually got an average of 5.9 hits per weaponskill.
(4.9 average out of the 7 hits with normal accuracy.)

**Comment by Qair** [comment]
5.9 hits out of 8 is even more disgusting. I edited my other comment, apparently i derped a line. I only was able to land 4 "158" tp weaponskills out of 53 attempts which put me at 7.5% chance to land all 8 hits for that session. How is that even possible.

**Comment by Qair** [comment]
Caelic posted this on the forums. it looks like penta did have an acc penalty, but dsp applied it to asuran too.

   FINAL FANTASY XI Update (Nov. 28) -The penalty to Accuracy for the weapon skills "Guillotine" and "Penta Thrust" has been removed.

Nov 28th, 2007 was literally one week after WotG was released so it would only be natural to assume that other multi-hits held this property as well during the ToAU era. Still, I will also attest to saying that MNK was actually a decently desirable job in ToAU era even against colibris and that you are correct in saying Asuran Fists was a very consistent weapon skill.

**Comment by Qair** [comment]
https://img.photobucket.com/albums/v285/MrBill82x/parse81.jpg

Parse from 2007 with a blackbelt mnk/war with an average weapon-skill of 671 damage, 200+ points over mine despite only having 75% hit rate.

**Comment by Qair** [comment]
I just want to bump this because it's still a problem:

the asuran description on github reads "Due to the 95% params.accuracy cap there is only a 66% chance of all 8 hits landing, so approximately a one third chance of missing some of the hits at the cap" which is stupid to begin with but on top of only having a 66% supposed chance to land all 6 hits you also have a .8 acc modifier so it makes it even less then 66%  with params.acc100 = 0.8 params.acc200= 0.9 params.acc300= 1.

**Comment by VirtuosusFFXI** [comment]
I believe this is also affecting Dancing Edge, Penta Thrust, and other accuracy varies by TP weapon skills. In my opinion params.acc100 should be at least 1. Its absurd that you need 3000 tp just to have your base accuracy, it was never like that in era.

**Comment by FallenXI** [comment]
I agree with the above. Played DRG since 05 and never had real issues with landing most hits of penta at 100tp - intact I would think that that kind of mod would mean it wouldn't even be used.

**Comment by VirtuosusFFXI** [comment]
Seems like Penta Thrust was changed from "Damage varies by TP" to "Accuracy varies by TP" in August 2007.

Proof: https://ffxiclopedia.fandom.com/wiki/2007_-_(08/27/2007)_The_Version_Update_has_come!

"Several weapon skills have had the effects of TP adjusted in the following manner:
Raging Rush: Damage varies with TP >> Chance of critical hit varies with TP
Penta Thrust: Damage varies with TP >> Accuracy varies with TP
Skewer: Accuracy varies with TP >> Chance of critical hit varies with TP"

The discussion page for the Penta Thrust entry on the wiki also mentions this: 

FINAL FANTASY XI Update (Nov. 28) - The penalty to Accuracy for the weapon skills "Guillotine" and "Penta Thrust" has been removed.

There was a penalty to accuracy? Can't complain about them removing it, but when did that happen? --Thala 19:52, 28 November 2007 (UTC)

happened during the august 2007 update--Catharsis of valefor 04:44, 8 December 2008

**Comment by FallenXI** [comment]
So between August and November 28th it was shit (can't remember) and this just so happens to land on the timeline for this server lol. Big oof.

**Comment by VirtuosusFFXI** [comment]
Yes, thats essentially it. In my opinion they should make an exception for this because its kind of silly, and it doesnt really have anything to do with WotG.

Also, I haven't seen any complaints about Guillotine but its totally possible that its also affected. Either way, theres more than just Penta and Guillotine that have an issue. 

Asuran is probably the most noticable, its extremely incosistent and almost impossible to land all hits until its fixed. I also clearly remember Dancing Edge being THF's best weapon skill for damage and Shark Bite only saw use for Light skillchains or for high defense/evasion targets where multihit would perform poorly against. This definitely isn't the case on Eden, as SA/TA Shark Bite basically always outperforms Dancing Edge.

**Comment by FallenXI** [comment]
Again I totally agree with DE being useful - was the same situation with THF and DRG. Multihit good for everything bar HNM, then Wheeling Thrust/SB for Light SC.

**Comment by Qair** [comment]
So I subbed back on retail and made a 75 mnk to test out asuran fists accuracy as there's no patch notes stating that is was either raised or lowered in the duration of the game. I did 50 asurans with sushi and 50 asurans without sushi and these are the results:

With squid sushi my monks accuracy was 415 and had a melee hit rate of 97.70%
Vs 50 greater colib

I averaged a 174.8 tp return out of a possible 176 max tp return

44/50 weaponskills returned full tp which = 88% chance to hit all 8 hits
---------------------------------------------------------------------------------------------------------
My eden mnk Riaq which has 428.27 accuracy with crab sushi and had a melee Accuracy of 94.43%

**Comment by isotor** [comment]
More than just `params.acc` *(which I believe is flogging a dead horse at this point)* the above is fairly compelling evidence that the `hitrate` should be capped at 0,98 not 0.95.

> melee hit rate of 97.70%
> 88% chance to hit all 8 hits (0.98^8 = 85%)

Any chance you could extend this test (just the retail side) for a larger sample?

**Comment by isotor** [comment]
Actually, a point relevant to an era-server in the [Dec 10, 2014 Version Update](http://forum.square-enix.com/ffxi/threads/45365?p=534537#post534537):

> __The maximum accuracy of one-handed weapons equipped as the main weapon has been increased from 95% to 99%.__

Your test seems to at least confirm that h2h falls under the category of "one-handed" in this case, however, this change on retail (that shouldn't be reflected on Eden) suggests 66% should be the upper limit on landing all 8 hits of Asuran Fists.

You test still supports @beauxq's adjustment to `params.acc`, and in my view this is nothing short of a no-brainer at this point.

**Comment by Qair** [comment]
I don't know what else I can do at this point for this change to be implemented.

**Comment by Enignite** [comment]
It's extremely unlikely it was ever a % accuracy modifier in the first place, and as Guillotine also had it I'm assuming it was a pre-existing penalty due to them being multi-hit 2-handed WSs and nothing about 'Accuracy varies with TP', similar to how Penta has a negative attack mod to balance it.

We aren't even sure when the penalty was added, could have been there from start and cleaned up due to the 2 hand buffs or maybe it was implemented with 2 hand buffs and they decided to remove it later on. I don't think there's any reference to either of these WSs receiving the penalty in the first place so it's hard to tell.

**Comment by Qair** [comment]
While I agree with you that penta probably never had a negative percent acc modifier, there's not much to do about it. I can't test it on retail like asuran because it was changed.

**Comment by Qair** [comment]
Whoops accidently closer it in my phone. Buttons are to close together
