### ISSUE TITLE
Divine Might no Reward

### ISSUE THREAD

**Issue by nekozuko** [EdenServer/community#1486]
I flag the quest last saturday 1000% sure when I was waiting on our linkshell to gather. The event was canceled because nobody had the Ark Pentasphere. Today, our LS was able to gather up and complete Divine Might. I went back in Shrine of Ru`Avitau and talk to the unmarked area and I got the same message I did the previous weak about getting an Ark Pentasphere...

Please even check my logs from last saturday around 3-3:30PM cst. 

I've checked my quest log and I've had the "Divine Might" quest in my Outlands quest log.

**Comment by dantaface** [comment]
Same fight..  

Hellvan
Mytrans
Tartaru 
Nekozuko

didnt get the reward, tho they have the quest flagged

**Comment by MGramolini** [comment]
Are you 100% sure you talked to the wall twice?

**Comment by nekozuko** [comment]
Yes I am sure I talked to the wall more than twice last saturday. I do this to basically all my cutscenes

**Comment by KnowOne134** [comment]
Can not reproduce. Common occurence only clicked wall 1x. Then do battle clicking wall again after fight actually logs the battle then no reward and make a ticket.
