### ISSUE TITLE
Kirin Issues. (able to use Riddle, TPing too often.)

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1488]
Kirin shouldn't be able to cast Riddle. Yet doing it tonight, he pretty much spammed it.
He also is supposed to TP every 10-15 seconds. He is TPing back to back instantly. So his Regain is probably too strong, or there's no cooldown in place.

**Comment by Elysien** [comment]
You appear to be correct concerning Riddle, as for tp gain;

https://www.youtube.com/watch?v=QFXAlvgOHXo

**Comment by Volkaru** [comment]
Guess I should've done more research about the TP gain, sorry.

**Comment by Volkaru** [comment]
Some people were saying he uses all standard Manticore moves. However, that is not correct. He specifically has never cast Riddle. Here's multiple sources to back this up:
https://ffxiclopedia.fandom.com/wiki/Kirin?oldid=366446
https://ffxiclopedia.fandom.com/wiki/Kirin?oldid=70359
http://ffxi.allakhazam.com/db/bestiary.html?fmob=1690
https://youtu.be/QFXAlvgOHXo
https://youtu.be/O3JSJj7x9qg

**Comment by Novadragon-Siren** [comment]
Kirin can use all the TP moves except Riddle. You're right once he actually uses a TP move, he results to melee or casting Quake/Rasp/Sleepga/Stone V/Stonega IV, till like 10-15 seconds later depending on his HP. Below 25% Kirin would TP pretty much more spam.
