### ISSUE TITLE
No character collision

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#149]
Characters can run through one another without the effect of being body blocked. This has been tested by multiple players on multiple characters.

**Comment by Aneyus** [comment]
Praying for a wontfix tag on this one personally lol. Nice, not overpowered QoL especially for people who remember using GM mode on retail to do the same thing. Would make Dynamis a lot more playable as well!

**Comment by roriffxi** [comment]
https://www.ffxiah.com/forum/topic/31579/dev-character-collision-adjustments

It's an adjustment that SE made in 2012 that is probably reflected in stock DSP.
