### ISSUE TITLE
Devil Mantas in Cape Terrigan

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#1491]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)

### Details
Devil Mantas were originally in both Cape Terrigan and Kuftal Tunnel but were later removed from Cape Terrigan for RMT Changes. 
https://ffxiclopedia.fandom.com/wiki/Devil_Manta?oldid=29926

**Comment by dowzer** [comment]
The strength required to reel in Devil Manta is much higher than in Kuftal. With 0 skill, sometimes it can only be reeled to 50%.

On retail, fishing skill did not determine how difficult it was to reel in a monster. I used to fish at both spots before it was changed. Even much later in my time, at 110 with Ebisu, the strength remained the same to this day.

**Comment by 59blargedy** [comment]
resolved by rmt changes October 4, 2021
