### ISSUE TITLE
Fafnir Drop Rate

### ISSUE THREAD

**Issue by ultimazero** [EdenServer/community#1495]
### Checklist

- [*] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [*] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [*] I have provided my client version in the details. (type /ver into your game window)

### Details

Fafnir drops seem a bit low for the 50%+ items with Treasure Hunter 3. We are 0/3 on either the Aegishjalmr, Andvarnauts dropping. Feels off, might just be bad RNG but might be worth looking into the drop rate on those items. I remember on retail one of those dropping pretty regularly.

**Comment by MGramolini** [comment]
We get them at least 50% of the time. Sometimes they will drop 8 times in a row.

**Comment by godmode** [comment]
The treasure pool seems to be where it should be after review. Please continue to keep an eye on it.
