### ISSUE TITLE
[Pso'Xja] Labyrinth Lizards Lv.52-58 Gauge as cannot be Charmed.

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#1498]
The Labyrinth Lizards should be charmable.  This was a viable BST camp in retail using Lizards vs. Snoll at the (I-7) entrance and has been eliminated.  Please make these lizards charmable to be retail accurate.  Thank you!

**Comment by godmode** [comment]
Please open this issue with the template filled out.
