### ISSUE TITLE
[Pso'Xja] Labyrinth Lizards gauge as not able to charm.

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#1499]
### Checklist

- [ X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X ] I have provided my client version in the details. (type /ver into your game window)

### Details
The lizards in this area should be charmable and they are not.  This was a viable BST camp to defeat Snoll and Cryptonberry in retail and the lizards for whatever reason have been set to uncharmable.  Please fix!  Thank you.

To reproduce use "Gauge" on lizards at (I-7) entrance of Beaucedine Glacier.

version 30181205_0

**Comment by montijin** [comment]
#899
