### ISSUE TITLE
EXP bands always cost 700 to recharge, regardless of remaining charges (possibly a visual bug)

### ISSUE THREAD

**Issue by kassisaf** [EdenServer/community#1501]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Just traded my empress band which still had 4 charges left on it to the gate guard in Bastok Mines. He says "Your empress band has received 7 charges in exchange for 700 conquest points," when it should have only taken 300 CP for 3 charges. Not sure if this is a visual bug or not, as I didn't check my CP beforehand.

Client version 30181205_0

**Comment by isotor** [comment]
https://github.com/DarkstarProject/darkstar/blob/3d2995917a664ba28d3ff5551c95053767640fa7/scripts/globals/conquest.lua#L967

looks like they palmed it and gave you a new one fam

**Comment by Althaia** [comment]
I don't know if it's a text-only issue or if it actually takes 700 regardless of charges, but I noticed this, too. I had three charges left and it said it charged me 700.

I'm Windurstian and traded in at the Windurst Woods guard, if that matters.

**Comment by Althaia** [comment]
Hey guys, I had 2/7 on my Emp band today and recharged it.

It took 500 points from me, as it should, but the text said "you receive 7 charges for 500 points" -- just an FYI that it should probably say "5 charges."

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
