### ISSUE TITLE
Incorrect drop rate on specific Quicksand Caves NMs

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#1502]
The NMs: Antican Legatus, Antican Praetor, and likely Antican Consul as well as incorrect drop rates for Darksteel Ore.

I want to preface this post with the fact that I lived in Quicksand caves and killed these NMs nearly everyday for 5 months straight. 

The wiki has the drop rate listed as 38.5% with a very low sample size.
https://ffxiclopedia.fandom.com/wiki/Antican_Praetor
https://ffxiclopedia.fandom.com/wiki/Antican_Legatus   (Had it listed as 100%, lmao)

The drop rate for these Darksteel Ores was closer to 40-45% with Th4.  Source: 5 Months of sandy hell.

Whatever the drop rate of these NM's are, it's significantly lower than it should be.

### Checklist

- [Checked] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ Checked] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [N/A? ] I have provided my client version in the details. (type /ver into your game window)

### Details

30181205_0

**Comment by Shoruto** [comment]
For the Legatus, two players posted that they received darksteel ore 4/4 and 11/11 both were during era
http://ffxi.allakhazam.com/db/bestiary.html?fmob=605

**Comment by ThrisStraizo** [comment]
This issue has been addressed in the new loot spreadsheet.
