### ISSUE TITLE
Dia overwriting itself

### ISSUE THREAD

**Issue by Jake123123** [EdenServer/community#1503]
Monsters casting Dia of the same tier will refresh the duration of Dia. This isn't era/retail behavior since Dia can't overwrite itself unless it's a higher tier 

Example: 
Goblin Weaver casts Dia -> 1 minute duration 
30 seconds remaining 
Goblin Weaver casts Dia -> Back to 1 minute duration 

It should only deal the initial damage but not re-apply the effect until the Dia debuff icon is completely gone. It's pretty annoying since your DoT will be continuously reapplied when fighting certain enemies and never have a chance to wear off due to their whacky spellcasting behavior that makes them recast things they don't need to

**Comment by Shoruto** [comment]
Similar to #1392

**Comment by tacbox3** [comment]
This is different shoruto. This is about dia, not beastmen spell behavior. Even fighting multiple mobs in a row dia still overwrites itself. Can confirm this from my time soloing in KRT recently. Dia should not be refreshed when recast, similar to how blind and other debuffs work.

**Comment by Shoruto** [comment]
Since this was mentioned in the previous report 

- I've seen them also reapply Dia before it wears off

It's still similar

**Comment by mousseng** [comment]
DSP by default has Dia set to overwrite "equal or higher" statuses of the same kind. this applies to all sources of the effect, including players.

assuming this is era behavior (a quick glance through the wiki didn't turn up anything conclusive), a simple update and server restart should bring it in line with blind and friends:
```sql
-- change dia/bio from EFFECTOVERWRITE_EQUAL_HIGHER to EFFECTOVERWRITE_HIGHER
update status_effects
set overwrite = 1
where id in (134, 135) and overwrite = 0;
```

```diff
diff --git a/sql/status_effects.sql b/sql/status_effects.sql
index cd18b24090..4a7c77f0f5 100644
--- a/sql/status_effects.sql
+++ b/sql/status_effects.sql
@@ -173,8 +173,8 @@
 INSERT INTO `status_effects` VALUES (130,'choke',8405026,0,0,0,129,131,4,0);
 INSERT INTO `status_effects` VALUES (131,'rasp',8405026,0,0,0,130,132,2,0);
 INSERT INTO `status_effects` VALUES (132,'shock',8405026,0,0,0,131,133,6,0);
 INSERT INTO `status_effects` VALUES (133,'drown',8405026,0,0,0,132,128,3,0);
-INSERT INTO `status_effects` VALUES (134,'dia',8405026,0,135,0,0,0,7,0);
-INSERT INTO `status_effects` VALUES (135,'bio',8405026,0,134,0,0,0,8,0);
+INSERT INTO `status_effects` VALUES (134,'dia',8405026,0,135,1,0,0,7,0);
+INSERT INTO `status_effects` VALUES (135,'bio',8405026,0,134,1,0,0,8,0);
 INSERT INTO `status_effects` VALUES (136,'str_down',8405026,0,0,0,0,80,3,0);
 INSERT INTO `status_effects` VALUES (137,'dex_down',8405026,0,0,0,0,81,2,0);
 INSERT INTO `status_effects` VALUES (138,'vit_down',8405026,0,0,0,0,82,4,0);
```

**Comment by roriffxi** [comment]
This fix was incorrect as it prevents dia damage from applying to the mob entirely.  The damage portion of Dia&Bio should still land, allowing skillgain, it just shouldn't refresh the duration of the DOT effects.
Eden behavior now, which is wrong:
![2](https://user-images.githubusercontent.com/37307792/86147306-135a9200-baae-11ea-92e3-b3a166fbfa32.PNG)

Later thread, but the behavior never changed, all of it talks about spamming dia for skillups.
https://www.ffxiah.com/forum/topic/40386/enfeeb-magic-skilling/

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
