### ISSUE TITLE
Guard proqs with no skill seem too stronk

### ISSUE THREAD

**Issue by chlorr** [EdenServer/community#1505]
### Checklist

As I have been farming BLU spells as BLU/WHM, with 1 H2H merit, and none in guard. Once i take off my weapon to feed TP to the mob the guard rate seems a lot higher then on my MNK or PUP and always reduces DMG done to 0. 

As a blu/whm no innate H2H or guard skill. with the ammount of proqs I deff don't think it's right. Farming Dhalmels I've had 3 guards in a row, 0 DMG, a hit, guard, hit, hit, guard (was the most memmorable streak, but id say 5-20% guard rate).  Deff. seems too strong or a bug with one of the skills.

 Didn't get any SS's but will add when i go farming for some more spells in a bit

VER- 30190202_0

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by gweivyth** [comment]
Should you even be able to guard without guard skill?

**Comment by chlorr** [comment]
that's what im saying. idk but i don't think so

**Comment by tengokujin** [comment]
I can confirm that this is happening.
The guard animation and the damage reduction are definitely procing on a BLU/WHM trying to learn a spell. 
I do not have any merits, so I definitely do not have any reason for it to proc.

**Comment by Shoruto** [comment]
This additional information was provided by Spiffly

Guard appears to be proccing when using H2H, even with 0 guard skill. There is no guard animation when it procs but wen it does, mobs go from hitting 10-20 to 0.

![Tttt_2021 03 11_205214](https://user-images.githubusercontent.com/46944745/110873454-c7e4be80-829f-11eb-8988-6bcf3b6246b3.png)

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
