### ISSUE TITLE
Eastern Shadow and his counterpart NMs have incorrect PH respawns

### ISSUE THREAD

**Issue by Altnob** [EdenServer/community#1506]
I noticed this a while back but forgot to make the post.

Spectres in Fei'yin have a 5min respawn rate instead of the 16 min era respawn rate . This makes popping all directional NMs extremely easy. This is also why their drops are probably so cheap.

**Comment by gweivyth** [comment]
Was like this on Kupo too, maybe an oversight?  I didn't notice the NM spawn rate being particularly good, but I was at least racking up more exp/hour than I should have been while I camped, lol.

**Comment by godmode** [comment]
I will look at their spawn chance when increasing repop time.
