### ISSUE TITLE
Boroka respawning after crash

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#1507]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Ver: 30181205_0

I'm unsure if the devs want this NM's tod to persist or not, but atm it's not persisting.

**Comment by Serephim** [comment]
This is broken again. He's spawning after crashes.

**Comment by perkuprightmeow** [comment]
Can confirm after getting last ToD from Serephim, does spawn after crashes but not sure what windows.
