### ISSUE TITLE
[Onzozo] Flying Manta are MNK; only attack once per round.

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#1509]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

Seems like a bug as other MNK mobs attack twice per round (ie. Mandragoras).

**Comment by gweivyth** [comment]
Hmm, found a video that shows it maybe just double attacking like a WAR?  Not sure what to believe! 

https://www.youtube.com/watch?v=XvWWPs-hTzM

**Comment by isotor** [comment]
#wikifails

**Comment by greyenvy** [comment]
Well that definitely have "Counter" because I saw them do that against my pets last night.  So somehow they do have MNK traits of a sort.  Any double-attacking you might see is likely due to that perhaps.

Maybe I'm crazy but I recall these attacking twice in retail.  I could be totally wrong and someone can log on retail and see if that's the case.

**Comment by Kurtalicious** [comment]
The Mantas in Onzozo are currently attacking twice per round.

**Comment by dowzer** [comment]
The Sea Monk family aren't supposed to attack twice per round as a MNK would. They are also not supposed to Counter or Guard. They have Double Attack at the appropriate level. It's difficult to demonstrate that they can't Counter when they can barely hit me. 

Mantas on Eden also have a much higher delay than retail, they should have the same standard delay that monsters have.

Hopefully these videos are helpful apart from the sped up frame rate. 

SSG:
https://www.youtube.com/watch?v=l4P-TkJH2j0

Kuftal:
https://www.youtube.com/watch?v=qsbqK8vTR8k

LoO PH:
https://i.imgur.com/30mhLTE.mp4

**Comment by 59blargedy** [comment]
resolved sept 27 2020
