### ISSUE TITLE
Double skillups from Blade: Rin

### ISSUE THREAD

**Issue by ababyduck** [EdenServer/community#1512]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Blade: Rin currently grants two Katana skillups. Not sure whether skillups on single-hit WS are being doubled while dual-weilding, or Blade: Rin is incorrectly set up as a two-hit WS and multihit WSes are granting multiple chances at skillups. Needs further testing.

https://i.imgur.com/4pARD7p.png

Client version 30181205_0

**Comment by Lilswitche** [comment]
Were you dual-wielding at the time? To my knowledge, offhand weapons get a swing during weaponskills as well.

**Comment by beauxq** [comment]
yeah, dual wield adds an extra hit to weaponskills

**Comment by ThrisStraizo** [comment]
Working as intended if dual wielding.
