### ISSUE TITLE
Fishing a rock

### ISSUE THREAD

**Issue by godoz** [EdenServer/community#1517]
### Checklist
<!--
Just some NPC that are miss placed
### Details

![image](https://user-images.githubusercontent.com/22343858/55840932-38ef2a80-5afb-11e9-9dea-2f2027d6710d.png)

**Comment by godoz** [comment]
![image](https://user-images.githubusercontent.com/22343858/55840970-6340e800-5afb-11e9-8963-be591fe8f844.png)

**Comment by bkesecker** [comment]
Please explain in more detail, as there are none.

**Comment by Aneyus** [comment]
I think he means the NPCs are facing the wrong way.

**Comment by EpicTaru** [comment]
Is it wrong that I find this very very very oddly amusing?

**Comment by tacbox3** [comment]
They did this on retail too. NPCs will turn to face you when you talk to them or trade. They don't always turn back.

**Comment by godoz** [comment]
Its only visual. No biggy. But no. They do turn on retail when talking to you but will never cast their rods on the port lol. Just close the ticket. I thought it was just nice to fix a visual bug...



Sent from my Bell Samsung device over Canada's largest network.


-------- Original message --------

**Comment by bkesecker** [comment]
Nah, this is pretty easy to fix.  No need to close.  I just thought it was about fishing rocks out of Port San d'Oria.

**Comment by InoUno** [comment]
Resolved in December 28, 2020 patch.
