### ISSUE TITLE
FFXI-3101 on FF's login screen since 4/5

### ISSUE THREAD

**Issue by Emericajosh** [EdenServer/community#1519]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I've been unable to login at all as everytime I try I get  the following error. FFXI-3101. This is after loading from Ashita and before I make it to the main FFXI menu. It's been ongoing since April 5th

**Comment by godmode** [comment]
It’s not very clear on our website but this repository is generally for reporting in-game issues. The tech-support channel in Discord is your best place to get help to connect.
