### ISSUE TITLE
Blink Mechanics

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#152]
Currently Blink/Aerial armor style shadows operate in the same way as Utsusemi shadows, however, the mechanics should be vastly different.

[ffxiclopedia](http://ffxiclopedia.wikia.com/wiki/Blink_(Status_Effect))
[BG Wiki](https://www.bg-wiki.com/bg/Blink)

The big points: 
-Activation rate should be approx 50% and not 100%;
-AoE Physical TP moves generally wipe blink shadows completely and still deal damage/status effects, e.g. Battle Dance, Earthpounder/Earthbreaker/Wild Rage, Sweep, etc;
-Single target multi-hit physical TP moves: when blink procs, it should absorb ALL hits from the TP move with a single shadow. e.g. Wing Thrust from Aerns, Goblin Rush, etc.

The difference in mechanics between Blink/Utsusemi are pretty important for events like Dynamis. Mages using blink should be positioning accordingly, otherwise they take damage from the likes of Battle Dance, Sweep, Scorpion pet TP moves, etc.

**Comment by beauxq** [comment]
Blink does not currently operate in the same way as Utsusemi shadows. It doesn't have 100% activation rate. I have been playing WHM puller a lot the last few days, and have seen a lot of hits go through with blink on.

Blink probably does have some problems, but we should make sure we well understand what's wrong before we try to fix what isn't broken.

**Comment by Lilswitche** [comment]
You're right the activation rate isn't 100%, I guess when I had observed it earlier it gave me the impression it was and Kupo's of course was busted.  I'll be testing the AoE mechanics shortly.
