### ISSUE TITLE
Ranged Weapon Skill giving melee combat skill up

### ISSUE THREAD

**Issue by hienlongli** [EdenServer/community#1522]
version 30181205_0

RNG/WAR Level 16-19 in Valkrum Dunes. When I used a ranged weapon skill such as flaming arrow or piercing arrow it gave me skill ups for my melee weapon instead of ranged. 

Screenshots:
https://prnt.sc/na9339
https://prnt.sc/na923z
https://prnt.sc/na90vh
https://prnt.sc/na90b7
https://prnt.sc/na93st

### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

**Comment by MGramolini** [comment]
Title should probably say ranged weapon skill.  Good find.

**Comment by Wonkstar** [comment]
I've also been experiencing the same thing. Used a marksmanship weapon skill, got dagger skill up.
