### ISSUE TITLE
Linking type mobs won't link when you claim one using Sleep?

### ISSUE THREAD

**Issue by RottenUnagi** [EdenServer/community#1523]
I don't think this is true in retail?

~ I noticed this behavior with sahagins in SSG (aggressive/linking/sound). Two sahagins standing next to each other unclaimed, I sleep one with a single target sleep spell, the other doesn't link, doesn't respond at all. If I wake up the slept one then the other will link as normal. At lv52 these particular ones (Spring/Pond/Lake sahagins near Wuur the Sandcomber area) are EP to me but non-aggressive, not sure if that has anything to do with it.
~ On a tangent, I also found that the Undead Bats here aren't linking as normal (sleep notwithstanding). They're listed on the wiki as being linking types. These are also EP to me.

[/ver 30181222_1]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

**Comment by isotor** [comment]
If true, this actually sounds like a huge bitch to fix for what appears such an unlikely/niche case I'd question if it's worth it at all. I assume the moment sleep wears off link behavior kicks in?

**Comment by RottenUnagi** [comment]
I see your point & agree. I'm just not sure if it's exclusive to just these mobs/this area. Just reporting some strange behavior. They do link when sleep wears off, although later on I was noticing more strange behavior in regards to linking. Sometimes they wouldn't link at all under any circumstance. Most surprisingly when I went to J-9 (first map), voked one of them with my WAR alt, then intentionally ran it around all the other sahagins & they wouldn't link at all, not by sound, not by sight.

**Comment by Novadragon-Siren** [comment]
No, it happens to all mobs. Sleeping mob is considered no aggro to other mobs that Link.

**Comment by RottenUnagi** [comment]
I see, thanks for that input Nova. No access to retail & I couldn't find anything stated to that effect in a quick google search. Still some funky linking behavior going on if I could trail a sahagin all around that room & not link any of the others. Maybe ultimately an insignificant/niche issue though like isotor said.

**Comment by InoUno** [comment]
Resolved with December 7, 2020 patch.
