### ISSUE TITLE
BLU spell Jettatura - request for audit

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#1526]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

~0/50 on this one between 2 players. Attempted to learn from Hippos in Riverne Site B. Requesting audit to confirm this spell is learn-able. Thanks!

**Comment by Shoruto** [comment]
Can confirm this should be a learn-able spell during era

https://ffxiclopedia.fandom.com/wiki/Jettatura?oldid=349112
https://www.bg-wiki.com/index.php?title=Jettatura&oldid=50175
http://ffxi.allakhazam.com/db/spell.html?ffspell=641
https://www.zentoo.net/ffxi/blu/Jettatura.html

**Comment by Far-The-Killer** [comment]
That spell is indeed missing. Implementation for it is there, just not learn able.
