### ISSUE TITLE
Unable to zone to Horlais Peak spring from Yughott Grotto

### ISSUE THREAD

**Issue by Hatberg** [EdenServer/community#1529]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

When zoning from Yughott Grotto into Horlais Spring from either J-6 or J-9, you will always be placed at the BCNM entrance.

This means that the quest "Secret of the Damp Scroll" currently cannot be completed unless you first successfully complete a BCNM and be placed at the spring-side exit. Quest completion requires the Damp Scroll to be doused into the hot spring, resulting in a Scroll of Jubaku: Ichi.

**Comment by Hatberg** [comment]
Likely related to [Sacrificial Chamber BCNM Exit glitch #1511](https://github.com/EdenServer/community/issues/1511)

**Comment by TheKingOfJeuno** [comment]
[https://clips.twitch.tv/VenomousNimbleEaglePJSalt](url)

havcing this same problem, cant complete nin paralyze quest
