### ISSUE TITLE
Crab sushi?

### ISSUE THREAD

**Issue by chlorr** [EdenServer/community#153]
Making some crab sushi as one does. My hq's, x6 +1 sushi. when all of a sudden i got an HQ for only 4. and only the one time.
By that logic id be HQ2ing every few syths, and a random HQ1 for less sushi, as Im only T1 on it

![chlorr_2018 10 12_161250](https://user-images.githubusercontent.com/43849717/46897858-14f7a880-ce3a-11e8-9705-f4fa7ef0cd25.png)

**Comment by Oyaziiiiiii** [comment]
HQ1 is giving 6 Crab Sushi+1 but it should give 6 NQ Crab Sushi.

http://ffxiclopedia.wikia.com/wiki/Crab_Sushi
http://www.classicffxi.com/db/items/5721/plate_of_crab_sushi
