### ISSUE TITLE
FFXI Cop 2-5 Ancient Vows Mammet AI

### ISSUE THREAD

**Issue by NovadragonZero** [EdenServer/community#1530]
### Checklist
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Mammets are out of position on spawn like on a diagonal formation than a straight line staring at us. 

I would have to stream them but the Mammets role change does not lock them from other behaviours. Role Change > They continue to run as they do it/Attack/Cast Blm spells soon it goes. In retail, Mammets always have a downtime on a role change before following up their actions. Not moving, no attacking, no TP attacks, no casting. 

With the Navmesh pathing bug (Including this ^^^^^), this can cause a lot of difficulty spikes in surviving their attacks. Pretty much throwing strategies out of the window to more restrictive. 

Version: 30181205_0

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
