### ISSUE TITLE
Stuck at death screen cannot HP

### ISSUE THREAD

**Issue by Khale781** [EdenServer/community#1531]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
Character Jaycie died in a zoning screen (black screen). character did not reappear. closed client and character was still dead and now have the option to HP. Will NOT HP when i click on it. character is stuck and cannot /shout /yell.

**Comment by KnowOne134** [comment]
Gm ticket issue
