### ISSUE TITLE
Bomb Queen add behavior appears to be incorrect

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#1532]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

Bomb Queen's spawn mechanics, and Bomb Queen's add's mechanics both appear to be incorrect. It is both spawning minions way too quickly and also the minions may be exploding too quickly. I know that the revision history from the encyclopedia indicates that these bombs respawn quickly, but I would like to counter with a recording from November of 2007 of the fight itself:

https://www.youtube.com/watch?v=jmcfkr3i1-c

As you can see, the Bomb Queen spawns only 1 bomb every 30 seconds and 2 Fire IIIs are sufficient to oneshot it consistently. Our group tonight was seeing multiple bombs spawning within seconds of each other; in fact, the Queen was constantly summoning new adds.

**Comment by Jimmayus** [comment]
sorry my version number is 30181205_0

**Comment by Shoruto** [comment]
Related to #228

**Comment by Cheese-Sandwich** [comment]
Bumping on this to add my encounter with BQ tonight as well and figured I would add some notes. Wasn't able to defeat the raid boss mechanics and lost pop item. Hope these notes help!

- Popped with approximately 5 adds at the beginning 
- Each add self destructed every 10 seconds, as opposed to 30 seconds. (ex : at 00:08, 00:18, 00:28 etc)
- Adds would sometimes hit for 10 damage, then the following hit would do 700-800.

**Comment by Raphtalia1** [comment]
Bumping this, its still an issue, my ls just wiped to a bomb queen that spawns adds every 5 seconds or less, and somehow spams -ga's while summoning adds.

In retail she wouldn't cast while summoning an add, and she could only summon 1 of each baby, and even then only once every 30 seconds

**Comment by Tjonke** [comment]
For now, just sleep the adds, She will only have a maximum of 1 of each up at a time so you won't be overwhelmed by adds self-destructing.
