### ISSUE TITLE
Meteorite damage negligible at best

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1533]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Ticket made per godmode's request

**Comment by Shoruto** [comment]
#856
