### ISSUE TITLE
Gust Slash / Cyclone aren't Ranged weaponskills

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1535]
### Checklist

- [o] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [o] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [o] I have provided my client version in the details. (type /ver into your game window)

### Details

Version: 30181205_0
Gust Slash and Cyclone don't appear to be Ranged weaponskills.
In retail they always have been. 

Upon attempting to use the weaponskills at range, they state that <playername> is too far away.
It then completely deplete's <playername>'s TP but the TP bar doesn't update.

Steps to Reproduce:
Equip a dagger and attempt to use Gust slash or Cyclone.

**Comment by Setz0r** [comment]
Per retail testing:

> you must be within 15.9 yalms (less than 16.0) for both gust slash and cyclone to successfully connect with the target (aoe range for cyclone is within 10 yalms)


Will be implementing tonight.
