### ISSUE TITLE
Unable to flag "Tuning in" Quest

### ISSUE THREAD

**Issue by ISilenceI** [EdenServer/community#1540]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
I checked my fame and I am fame 8
https://i.gyazo.com/e3490847603547c4d852b59f68276889.png
Quest requires 4+
https://ffxiclopedia.fandom.com/wiki/Tuning_In

Leppe-Hoppe just keeps giving me the Moonlit Path quest dialogue.
https://i.gyazo.com/48fbff0a1a2270bdbb79c14829e2f78c.png

I tried zoning as well to see if he would give the quest. He would not.

https://i.gyazo.com/c5e155230db671863b509ef04342aa7a.png

**Comment by FariskaEden** [comment]
I have also tried to flag this quest line after completing Moonlit Path and had no luck. I believe it has not yet been implemented in DSP.

**Comment by Setz0r** [comment]
quest is currently not implemented at all

**Comment by greyenvy** [comment]
I am trying to obtain the Cache-nez since I'm leveling tank jobs now and this quest is not implemented yet.  The three rare/ex items can however be obtained for the quest.  Can this quest and "Tuning Out" be made available in the near future?

**Comment by InoUno** [comment]
I've implemented this and the following quest in topaz, and they've been tested and merged into release:
https://github.com/project-topaz/topaz/pull/564
https://github.com/project-topaz/topaz/pull/590

**Comment by 59blargedy** [comment]
quest has been implemented
