### ISSUE TITLE
Lost inventory items due to new stack when full inventory

### ISSUE THREAD

**Issue by Kreggan** [EdenServer/community#1542]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

I had a full stack of 99 Beastman Seals in my inventory when this happened. My inventory space became full (30/30), then I received a couple other items, one of them being another beastman seal, and similarly to another submission (#824) my inventory showed 29/30 and new loot was going to treasure lots. I ran back to town to see if it would fix itself. It did, showing 30/30, but I noticed that instead of having a full stack of 99 beastman seals, I only had the 1 from the treasure pool.

**Comment by Shoruto** [comment]
Related to #824 

Make sure you submit a ticket to a GM also regarding your lost stack.

**Comment by HitGubz** [comment]
Can confirm this happened to me with Lizard Tails, stack of 12 disappeared.
