### ISSUE TITLE
Smithing: Light Crystal + Rusty Pick should be War Pick

### ISSUE THREAD

**Issue by Hatberg** [EdenServer/community#1543]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Before RMT rusty changes, a Rusty Pick should repair into a War Pick. Currently it repairs into a Plain Pick.
- War Pick repair recipe can HQ, Plain Pick can only NQ.
- War Picks have vendor value, whereas Plain Picks have (virtually) none.

[https://www.edenxi.com/db/items/17955/plain_pick](https://www.edenxi.com/db/items/17955/plain_pick) Recipe
[https://www.edenxi.com/db/items/16650/war_pick](https://www.edenxi.com/db/items/16650/war_pick) Recipe

Pre-RMT: [https://ffxiclopedia.fandom.com/wiki/War_Pick?direction=prev&oldid=204011](https://ffxiclopedia.fandom.com/wiki/War_Pick?direction=prev&oldid=204011)

**Comment by Hatberg** [comment]
Similar problem:

Light + Rusty Greatsword = Plain Sword
should be: Two-Handed Sword

[https://ffxiclopedia.fandom.com/wiki/Two-Handed_Sword?oldid=144423](https://ffxiclopedia.fandom.com/wiki/Two-Handed_Sword?oldid=144423)

[https://www.edenxi.com/db/items/16593/plain_sword](https://www.edenxi.com/db/items/16593/plain_sword)
[https://www.edenxi.com/db/items/16589/two-hand._sword](https://www.edenxi.com/db/items/16589/two-hand._sword)

**Comment by Shoruto** [comment]
Can verify that this was done to combat RMT.  Here are several items to show it.

SE's Update Notes (March 8th, 2007)
http://www.playonline.com/pcd/update/ff11us/20070308c2bbd1/detail.html

**The synthesis recipes listed below were temporarily removed in the February 2007 version update. These recipes will now create different items.

rusty cap/rusty greatsword/rusty pick**

Here are some posts regarding this report

### Mar 25 2007
I'm leveling up smithing, it seems that this has replaced the Padded Cap, at least in recipe (Light Crystal + Rusty Cap). I don't know the cap, but I seem to be making them somewhat reliably with great skillups at level 26 smithing


**Apr 06 2007**
This is basically the War Pick which is synthed from using a Light Crystal and a Rusty Pick,
but is currently selling on Valefor for 3k less than a War Pick >.>

FYI Rusty Picks can be fished in Batallia Downs ^.^


**Dec 21 2004**
I can confirm this. Light Crystal + Rusty Greatsword does indeed yield a Two-handed Sword. I cannot confirm what lvl is required.

**Comment by roriffxi** [comment]
https://github.com/EdenServer/community/issues/359

This was closed and 'in-code-review' its possible it got lost to the abyss.

**Comment by archfiendrubicante** [comment]
https://www.bg-wiki.com/bg/The_History_of_Final_Fantasy_XI/2007

In the History of Final Fantasy, Rusty Pick, Rusty Greatsword, and Rusty Cap had their recipes changed due to RMT reasons. This was a change that was made in ERA before the release of WOTG In March 2007.

The recipes were changed to "Plain Pick", "Plain Sword", and "Plain Cap"

@godmode

**Comment by sukasaroth** [comment]
I am leveling smithing and am inquiring about this also. If they've changed Plain Picks to War Picks, Rusty swords still repair to Plain, instead of two-handed and Rusty caps are still plain caps instead of padded.
