### ISSUE TITLE
Akamafula does not sell Nodachi

### ISSUE THREAD

**Issue by Eme-FFXI** [EdenServer/community#1544]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)

### Details
According to [ffxiclopedia](https://ffxiclopedia.fandom.com/wiki/Akamafula?oldid=10308) from 2005, NPC Akamafula in Lower Jeuno should sell Nodachi, but does not.

**Comment by Shoruto** [comment]
It says that certain items from that vendor are not automatically restocked and only shows up if a player sells it to them.

**Comment by godmode** [comment]
Confirmed, it can stock it but needs players to sell.
