### ISSUE TITLE
Missing Recipe: Cerberus Mantle Desynth

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#1545]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [N/A] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [N/A] I have provided my client version in the details. (type /ver into your game window)

### Details

Submitting a bug report of it's own for this synth since it was only mentioned on Discord and as a comment on the main Desynth bug report.  This recipe was never listed on Wiki likely because it was unknown for some time and also likely because it was kept a secret for quite some time in order to profit from it.  It's all over BG and even the FFXIAH for the item has people discussing it.

Recipe should be:
Leatherworking (95)
Yield: Cerberus Hide
HQ 1: Cerberus Hide
HQ 2: Cerberus Hide
HQ 3: Cerberus Hide
Lightning Crystal
1 x Cerberus Mantle

I was hesitant to post this until Desynth was more in line with retail specs as this would have been otherwise very abusable to get +1's.  Being the loss rates on desynthesis have been reigned in, it seems more appropriate to reintroduce this recipe.

Proof: [BG Thread](https://www.bluegartr.com/threads/39845-Cerberus-Mantle-Desynth)
[Picture 1](https://cdn.discordapp.com/attachments/460703006300831754/567214350209777690/ffxi_20090401_033615.png)
[Picture 2](https://cdn.discordapp.com/attachments/460703006300831754/567214943603130368/ffxi_20090331_143108.png)

**Comment by icariumkupo** [comment]
Shouldn't it be leather 95 rather than woodworking?

**Comment by godmode** [comment]
Gotta smooth out those splinters from the workbench, bro!

**Comment by Lilswitche** [comment]
Woops my b. Good catch.
