### ISSUE TITLE
Crawler's Nest - Vespo - Not Era

### ISSUE THREAD

**Issue by McLucas** [EdenServer/community#1546]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)

### Details

In Crawler's Nest there is a bee monster called Vespo.  This mob was not added to retail until around 2011 when lvl 99 was introduced.

Links
https://ffxiclopedia.fandom.com/wiki/Vespo
https://ffxiclopedia.fandom.com/wiki/Vespo?action=history

**Comment by MGramolini** [comment]
You probably just need to use the renamed addon and Eden profile.

**Comment by Sulfuricsixx** [comment]
There are a lot of mobs like that, in various dungeons. They left them there in DSP instead of removing and or reverting. I don't know if there are plans to fix or change these mobs, however I'm pretty sure they know about it already.
