### ISSUE TITLE
Missing Recipe: Desynthesis of "Mythril Baselard"

### ISSUE THREAD

**Issue by TheDynamis** [EdenServer/community#1547]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
Version: 30181205_0

The recipe is missing. It is as follows:

Desynthesis Recipeshide
Goldsmithing 
Yield: Steel Ingot x 1
HQ 1: Steel Ingot x 1
HQ 2: Mythril Ingot x 1
Lightning Crystal
1 x Mythril Baselard

https://ffxiclopedia.fandom.com/wiki/Mythril_Baselard

**Comment by Hatberg** [comment]
As far as I can tell, up to +/- April 2014 there was no desynthesis for this. Adding a desynth would make it out of era, unless there's another source that proves the desynth existed before November 2007.

April 2014 = No Desynth https://ffxiclopedia.fandom.com/wiki/Mythril_Baselard?direction=prev&oldid=1507563
Feb 2015 = Has desynth https://ffxiclopedia.fandom.com/wiki/Mythril_Baselard?direction=next&oldid=1484537

**Comment by Setz0r** [comment]
if this does exist in retail, it is definitely out of era.
