### ISSUE TITLE
Sandoria mission 2-3 mythril sand bug

### ISSUE THREAD

**Issue by Blademage** [EdenServer/community#1550]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Cannot turn in mythril sand to Savae E Paleade, been waiting for 6 hours total for a GM to show up to help me. have friends waiting on me to do this. I made sure i talked to Pius and Ghrom again, i have even went back to the mines to get a new set of mine gravel and refined in in the machine and trading the new mythril sand and she will not accept the sand. 

please help.

https://github.com/EdenServer/community/issues/492
https://github.com/EdenServer/community/issues/658
https://github.com/EdenServer/community/issues/1238
https://github.com/EdenServer/community/issues/1536

other such cases

**Comment by Shoruto** [comment]
Awesome
