### ISSUE TITLE
Elemental Blue Magic 

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#1552]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently elemental blue magic spells are not effected by weather, day of the week or elemental staves.

**Comment by montijin** [comment]
Also noticed that blue mage magic spells might not be giving enough TP to mobs.

**Comment by rude-jerk** [comment]
Resolved in November 23, 2020 patch.
