### ISSUE TITLE
Shadow (Fei'Yin) in Party

### ISSUE THREAD

**Issue by TorchlightEden** [EdenServer/community#1553]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
The Shade mobs known as "Shadow" in Fei'Yin near the stairs up towards Qubi arena act as if they are in a party when they're not supposed to be. If one is pulled from a safe corridor, they aggro from all around. This led to my swift death after a long run to get my alt a key for Teleport-Vahzl. :\

I don't know how to provide my client version info.

**Comment by ISilenceI** [comment]
Shadows link by sound. Try pulling them when they have a good bit of distance between them and see if they still act like they are in a party.

**Comment by TorchlightEden** [comment]
They did not; I don't recall them ever linking by sound. Then again, my
memory is not the greatest.

**Comment by ISilenceI** [comment]
Wiki from early 2007. Aggro, Link, Detect by Sound, Detect by HP
https://ffxiclopedia.fandom.com/wiki/Shadow?oldid=436973
Not an issue, please close.
