### ISSUE TITLE
Maat's Pet in Mission 2-3

### ISSUE THREAD

**Issue by TorchlightEden** [EdenServer/community#1554]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Maat's Pet pops in the Bastok leg of Mission 2-3, dragon fight. Thankfully, it doesn't aggro. 
This is a picture of me helping my friend with their dragon. They are Sandorian, hit windurst first and finished in Bastok.

I don't know how to post my client version info.
![MaatsPetIn2 3](https://user-images.githubusercontent.com/49079960/56324111-2f814600-612b-11e9-94e0-39b077c34585.jpg)

**Comment by montijin** [comment]
This happens when a battlefield is cleared and a pet isn't killed. The next group to enter will have the unkilled pet/summon in their battlefield.

**Comment by 59blargedy** [comment]
this shouldn't occur anymore based on current code and bcnm revamp a while back
