### ISSUE TITLE
Anima Does Not Appear to work

### ISSUE THREAD

**Issue by TorchlightEden** [EdenServer/community#1555]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Each of our party farmed Hysteroanima and used macros to make sure we didn't give the promyvion Dem boss a chance to use TP, but despite the animas that are supposed to block it using the TP attack, it still managed to use TP attacks before the 30 seconds was up. This could be due to anima being broken or the duration is closer to 10-15 seconds rather than 30.

This is the screenshot I took after the night it happened, sadly, it's not a very good one, as it just shows the boss readying the TP attack seconds after anima is used but not executing it's ws, which is the anima working as intended. The only evidence you can see in this log is that people got paralyzed by it's AoE paralyze TP attack earlier despite supposedly being under the effect of anima.

![AnimaNotWorking](https://user-images.githubusercontent.com/49079960/56324382-e7aeee80-612b-11e9-88fb-93fd1445d931.jpg)

I don't know how to post my client version info.

**Comment by tacbox3** [comment]
Two things.

1. The message that they're "readying" the skill will still show, but the attack will not physically execute.

2. In era anima was 30s max duration. Could be anywhere from 10-30 iirc.

This looks like a case of "working as intended"

**Comment by ababyduck** [comment]
I'm not sure what the correct times are for hystero, althrough the wiki lists it as 30 seconds and I can't find any history or evidence to suggest otherwise. Maybe digging through old videos could solve that.

Terroanima was definitely incorrect when I did my promy runs. It's supposed to make the boss run around, which it does not do.

**Comment by Mozzy4Ever** [comment]
Can also confirm. Used terror in the Dem fight and it did nothing

**Comment by KnowOne134** [comment]
Has been fixed
