### ISSUE TITLE
Players can target and perform actions on monsters they cannot see

### ISSUE THREAD

**Issue by slassen** [EdenServer/community#1558]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0
This is best seen because you can cast on mobs or shoot mobs that you can't see.
To reproduce, equip a bow and arrow and hide behind a wall. Attempt to shoot the mob and it should perform successfully. This is not intended behavior. When unable to see the monster you should receive a message saying "you're unable to see the {monster name}"

**Comment by InoUno** [comment]
Resolved with October 4th, 2021 update.
