### ISSUE TITLE
Monsters in battlefields will not aggro immediately

### ISSUE THREAD

**Issue by godmode** [EdenServer/community#1559]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0
When creating a pause time for mobs to aggro after spawning this also affected battlefield mobs. Battlefield mobs should be able to aggro immediately. To reproduce, enter a dynamis area and attack a statue. Mobs will spawn and not do anything until after the grace period has ended.

**Comment by tacbox3** [comment]
This actually makes pulling without links a little trickier in dynamis. I'm glad you've identified the issue!
