### ISSUE TITLE
Missing Recipe: Jadagna Desynth

### ISSUE THREAD

**Issue by HunnyDoo** [EdenServer/community#1562]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
 
v30181205_0

After synthing a Jadagna -1 into a Jadagna, you're supposed to be able to desynth it with a lightning crystal into troll bronze ingots.  Getting message "That combination of materials cannot be synthesized."  I haven't tried desynthing any other upgraded -1 troll weapons/armor such as Januwiyahs but I'd check those out too.

Edit: 2007 wiki link with the desynth recipe https://ffxiclopedia.fandom.com/wiki/Jadagna?oldid=352950

**Comment by Blex64** [comment]
Just confirming that I ran into the same issue today. Cannot desynth them.

**Comment by danismyhero** [comment]
This is issue is still occurring.  Recipe is missing.

**Comment by freddiepines** [comment]
6 months after the initial bug report this recipe is still missing.

![image](https://user-images.githubusercontent.com/50085658/66721799-186a9a80-edd4-11e9-8cf4-8188b753e00f.png)


Severely limits skillup options for smithing 86+.

**Comment by 59blargedy** [comment]
INSERT INTO synth_recipes VALUES(0,1,0,0,0,0,0,0,0,91,0,4100,0,18405,0,0,0,0,0,0,0,2302,2302,2302,0,1,1,2,0);
