### ISSUE TITLE
Cream Puffs OOE

### ISSUE THREAD

**Issue by Tacoxtuesday** [EdenServer/community#1567]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
First listed June 2008 As with Crab sushi, these are also OOE

**Comment by Shoruto** [comment]
Crab Sushi has been brought up in #1477 
They are working on getting all the OOE stuff removed.  Just takes some time.  Thanks for mentioned this item.
