### ISSUE TITLE
Memory Receptacle problems?

### ISSUE THREAD

**Issue by itachioax** [EdenServer/community#1568]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
we're at promy mea, and MR on third floor just pop a lot of stray at 40% is this normal?
like 5-8 strays

**Comment by Shoruto** [comment]
As you lower the MR it will spawn multiple strays.
