### ISSUE TITLE
Roll back character mission rank 4 Magicite

### ISSUE THREAD

**Issue by roidesgobs** [EdenServer/community#1569]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Hi , my character was rank 5 bastok since yesterday and i got my airship pass with my 2 character Nairolf & Temperance.
Today i have a problem to log in with Temperance and i must attempt several times to get in game. Afterthat i got a kind of "rollback" and Temperance is rank 4 and everything i got yesterday with her is just erase !
Help plz !

**Comment by bkesecker** [comment]
Please place a GM call if you haven't already.
