### ISSUE TITLE
Smoke on the Mountain (Bastok repeatable quest)

### ISSUE THREAD

**Issue by JIFCode** [EdenServer/community#157]
Quest initiated by Hungry Wolf in Metalworks G-9. Quest appears to not trigger the trade of the meat with the campfire at K-9. 

Used /item "G. Sheep Meat" < t> while targeting campfire.

**Comment by 59blargedy** [comment]
I was able to trade, but the meat does not cook within 1 earth minute as listed on wiki. Gave up after 17 earth minutes. Screenshots with timestamps:
![Linden_2019 07 07_155944](https://user-images.githubusercontent.com/52636208/60773317-a0ece700-a0d1-11e9-9d35-8b5baa220c58.png)
![Linden_2019 07 07_160901](https://user-images.githubusercontent.com/52636208/60773318-a2b6aa80-a0d1-11e9-8fa2-17cbb1f33b7e.png)

**Comment by bkesecker** [comment]
I don't know if the quest works, but this is the correct in-era information here (takes 1 real-life hour to cook): https://classicffxi.fandom.com/wiki/Smoke_on_the_Mountain

**Comment by bkesecker** [comment]
One Vana'diel day is the ToAU era accurate cooking period.  The campfire logic was not accepting the meat when the quest status was completed.  This will be fixed after the associated pull request is merged, and then a new version of Eden made available.
