### ISSUE TITLE
Mission sandy 2-3 - part 1 ( bastok )

### ISSUE THREAD

**Issue by godoz** [EdenServer/community#1570]
### Checklist

- [x] I did use wikipedia to do the mission ( worked on 1 char out of 2 )

- [x] I did my both char at same time, they both got the gravel, they both grinded the gravel into sand and collected it. Only worked on 1 char, for some reason the 2nd char doesnt trigger the CS when trading the item.

- [x] 30190202_0

**Comment by godoz** [comment]
Azwraith is the character name ( just realised i didnt mention it lol )

**Comment by godoz** [comment]
What ive tryed so far.
1) talked back to all NPC, didnt work
2) Zoned out and traded again, didnt work
3) Logged out and traded again, didnt work
Im stuck in the matrix!

**Comment by Shoruto** [comment]
#658 had same issue, see if anything there helps.  Make sure you read over every step.

**Comment by godoz** [comment]
> #658 had same issue, see if anything there helps. Make sure you read over every step.

I did all this already, even 5 times lol, wanted to make sure...

**Comment by godoz** [comment]
Even got the pickaxes from Ghrom to actually dig the mine gravel...

**Comment by godoz** [comment]
remade the issue with more details ( closing this 1 )
