### ISSUE TITLE
Prime Avatars' Astral Flow

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#1571]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181222_1

Prime Avatars do not seem to properly trigger their astral flow abilities. I just fought Ramuh & Shiva Primes; Shiva Prime didn't use Diamond Dust at all, however Ramuh Prime used Judgment Bolt twice.

Wiki pages for Prime avatars suggest that they use their Astral Flow abilities only once around 50% HP.

**Comment by NovadragonZero** [comment]
Yeah, in retail Prime Avatars hit their Astral Flow once you hit/pass 50%.

**Comment by Slamm21** [comment]
Right now they all spam Astral Flow and other abilities, sometimes instantly, I have had all 6 use Astral Flow on me sometimes 5x a fight. This does not seem to be just Avatars, I have experienced this with various other NMs also.

Ifrit seems the worst, I once had him do 4x Flaming Crush and 1x Astral flow within 15 seconds.

**Comment by bkesecker** [comment]
Two other issues 1) prime avatars do not appear to cast their respective elemental magic and 2) some do not aggro until hit (they should aggro [sight? true?] when approached within a certain range).

**Comment by bkesecker** [comment]
Need research done into damage increase/decrease done for strong/weak day of the week, respectively.  Some of the talk history for each prime avatars hint that the strong/weak day of the week should result in enhanced/diminished difficulty, respectively.

**Comment by 59blargedy** [comment]
resolved in december 14th update
