### ISSUE TITLE
Royal Knight Army Shield +1 desynth

### ISSUE THREAD

**Issue by cyphun24** [EdenServer/community#1574]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

the Royal Knight Army Shield +1 doesn't have a desynth in game, but wiki says it did.

**Comment by Shoruto** [comment]
When you take Wiki to era date August 6, 2007 there is no desynth listed

https://ffxiclopedia.fandom.com/wiki/Royal_Knight_Army_Shield_%2B1?oldid=321708

**Comment by cyphun24** [comment]
Yea seems i didn't do all the work on this.

**Comment by MGramolini** [comment]
I dont know.  If you look at https://ffxiclopedia.fandom.com/wiki/Darksteel_Nugget  It never lists it as a result from this desynth.  Does that mean it is not a result?  I'm pretty sure Desynthesis results are added by users and not just patch note/game data.   This can cause desynth results to come out months after they are available.

**Comment by MGramolini** [comment]
If you look at the date of the addition, there was no patch for almost 3 months before this was added to the wiki.  I vote this was likely existing but never added by a user until a wiki contributer tried to desynth it.

**Comment by statuseffect** [comment]
I believe this desynth should be relevant now with our current cutoff date.
