### ISSUE TITLE
Auction house gave me wrong item

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#1575]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver: 30181205_0

I have seen 2 sets of weird behavior.  First and without screenshots is when you go to buy a stack of items, but end up buying a single instead, paying 10-100x more than you should for a single.

Second, I purchased a stack of wind crystals, but only ended up with a single crystal.  The AH history says i bought a stack, but only a single went into my inventory.

**Comment by MGramolini** [comment]
![WindCrystal_1](https://user-images.githubusercontent.com/1774728/56499266-9b6d0100-64d3-11e9-9f5f-1af5bda18b0c.png)
![WindCrystal_2](https://user-images.githubusercontent.com/1774728/56499267-9c059780-64d3-11e9-9cc6-e4f3b6b41689.png)
![WindCrystal_3](https://user-images.githubusercontent.com/1774728/56499268-9c059780-64d3-11e9-843b-bb254f0e19e6.png)

**Comment by Shoruto** [comment]
Submit a GM ticket so you can get your full stack.

**Comment by MGramolini** [comment]
I don’t care about the item, not worth anyone’s time to fix that. I’m kore concerned with the cause of the issue.

**Comment by KnowOne134** [comment]
Can not duplicate
