### ISSUE TITLE
Hippo feathers

### ISSUE THREAD

**Issue by Qair** [EdenServer/community#1577]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Hippo feathers can't be traded, bazaared, ah'd, or dboxed. There's no way to give them to other party members to also get mismelts.

**Comment by MGramolini** [comment]
It is possible this item is supposed to be exclusive.  Would be good to make sure of this.

**Comment by Far-The-Killer** [comment]
Looks like these things should just be unable to be npc'd

**Comment by godmode** [comment]
The item should be exclusive as it was on release

**Comment by MGramolini** [comment]
Maybe a needs-dat-mod tag?

**Comment by Qair** [comment]
I assumed it was bugged because there's one for sale on the auction house, thought it may have gotten messed up in between then and now.

**Comment by Far-The-Killer** [comment]
are you sure it isnt a normal feather? what category is it under?

**Comment by MGramolini** [comment]
https://edenxi.com/db/items/1619/hippogryph_feather   This is a different item.

**Comment by MGramolini** [comment]
the quest item is https://edenxi.com/db/items/1690/hippogryph_tailfeather

**Comment by Fng098** [comment]
Causes communication error if trying to dbox them.  Seems to just freeze the senders screen until Communication error message comes up.  Seems to support they need to be coded / dat modeded to EX (get more than 1, but cant be traded / sold / dboxed)

**Comment by 59blargedy** [comment]
resolved in a previous 2022 update

**Comment by KnowOne134** [comment]
has been dat edited and can be found here:
https://github.com/EdenServer/Eden-Client_DATs

completed 2/23/2023
