### ISSUE TITLE
Mission 2-3 bugged -- cant turn in my item to the NPC -- Mythril Sand

### ISSUE THREAD

**Issue by godoz** [EdenServer/community#1578]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
I did this mission on 2 characters, they both did the same thing, but 1 of them got bugged when it was time to give the tradable item to the NPC. I did try to talk to all NPC all over again, i did try to zone and even relog. I did talk to Prius, asked to go at Ghrom, received pickaxe on both char, went to palbo mine, digged 3 chunk of gravel ( needed 2 ). Gave 1 to my alt, both used the machine with the gravel to receive the sand. Went back to bastok, gave the item to the NPC' worked on the alt (Baudelaire), but not on the main ( Azwraith ). 

Walked back to all NPC that are involved in the quest, nothing worked... Im stuck and need help ( been 3 days now ) I cant advance in my missions without this solved. Please do something.

Ver: 30190202_0

**Comment by bkesecker** [comment]
Please place a GM call to fix.  The quest is not bugged, rather the base DSP code.

**Comment by godoz** [comment]
> Please place a GM call to fix. The quest is not bugged, rather the base DSP code.

I did the GM call last night, nobody came back to me. Im off to work, will do another 1 when im back tonight.

**Comment by bkesecker** [comment]
No need if already done.  It won't make it get fixed faster.

**Comment by godoz** [comment]
GM solved this. Thanks!
