### ISSUE TITLE
Carbuncle Debacle bug in Rabao

### ISSUE THREAD

**Issue by Vecter521** [EdenServer/community#1579]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver: 30181205_0

I'm doing the Carbuncle Debacle quest for my SMN Head AF. Once in Rabao, the taru refuses to give me the text and rare/ex item to be able to fight my boss. Only gives me the prime avatar fight text. I did beat Garuda to be sure it wasnt blocking my quest. Nothing changed. I zoned, tried to log back, I even changed job. Help :/

**Comment by bkesecker** [comment]
Please place a GM call.  It is not a bug with the quest, but a bug with DSP base-code.  This quest is bugged at 60 FPS, however, just have to hit the print screen key to continue at the Cloister of Storms.

**Comment by bkesecker** [comment]
Was your progress resolved?
