### ISSUE TITLE
Buffs not lost on entering Riverne Site B

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#1580]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Upon entering Riverne Site B I kept my protect/shell 4 buffs. I doubt this is intended behaviour

**Comment by roriffxi** [comment]
https://ffxiclopedia.fandom.com/wiki/Level_Restriction?oldid=347422

Just for confirmation, you are correct.  All positive status effects should be removed whenever the level cap status is gained.

**Comment by xerodok** [comment]
This also applies when exiting Spire of Dem | Holla | Mea and going back into the Lv.30 cap Promvyion zone. Reraise, Protect IV / Shell IV, and buffed Stoneskin all applied.

**Comment by bkesecker** [comment]
This was fixed and is live.
