### ISSUE TITLE
Monster Bonus Experience - Nimbus Hippogryph

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#1581]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

According to https://ffxiclopedia.fandom.com/wiki/Experience_Points?oldid=460123
Hyppogryphs should award bonus experience (+15%), which they apparently don't.
Just killed a Nimbus Hypprogryph Lv49 as Lv50 solo for 86xp, should be 98,9->99.
Throwing the suggestion out to check all the mob(-familys) listed in that table.

**Comment by Volkaru** [comment]
Confirming this is a thing in era:
https://ffxiclopedia.fandom.com/wiki/Experience_Points?oldid=361693#Monster_Bonus
