### ISSUE TITLE
PUP auto attachment damage gauge isn't working correctly

### ISSUE THREAD

**Issue by darthleia** [EdenServer/community#1585]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0
When using a healing auto + damage gauge attachment with one light maneuver, the healing threshold for master/pt members is moved to 70% then 80% with 2 light maneuvers but the threshold doesn't change for the auto he will still only heal himself when under 50%.  Thank you for all your hard work making this game great!

**Comment by Volkaru** [comment]
Thanks for catching this. Meloetta and I extensively tested the job. But neither of us took much time seeing how the mage frame reacts to damage. Good catch.

**Comment by KnowOne134** [comment]
Can you link me source for auto curing itself

**Comment by 59blargedy** [comment]
the only data i can find is bg wiki referring to this as expected behavior - 
https://www.bg-wiki.com/ffxi/Damage_Gauge
"Light Maneuvers increase the percent that the automaton will cure its master, but not itself, this will always remain at 50%."
