### ISSUE TITLE
Lizard's Infrasonics skill sets your evasion to 0

### ISSUE THREAD

**Issue by FallenXI** [EdenServer/community#1586]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Partying in Valkurm Dunes, Infrasonics was setting my evasion to 0 from 53.

Other members in party mentioned it being a known issue on Nasomi/DSP, and another mentioned it's the same with the Beetle skill 'Hi-Freq Field' (not tested).

Wiki states that it should be -20 evasion:
https://ffxiclopedia.fandom.com/wiki/Infrasonics

Screenshots to show buffs and evasion with /checkparam:

<img width="326" alt="Screenshot 2019-04-24 at 15 18 55" src="https://user-images.githubusercontent.com/48524641/56667196-497bd500-66a5-11e9-8c19-a7a4fa11323e.png">

<img width="380" alt="Screenshot 2019-04-24 at 15 17 52" src="https://user-images.githubusercontent.com/48524641/56667197-497bd500-66a5-11e9-9454-f39fb006d9c1.png">

Version: 30181205_0

**Comment by FallenXI** [comment]
Single (Giant) Bats skill Ultrasonics, also sets your evasion to 0.

**Comment by Enignite** [comment]
This is the cause https://github.com/DarkstarProject/darkstar/issues/5701 

It's anything that tries to lower your evasion by more than the evasion+ gear/buffs you are using at the time. Simple fix but never got around to relearning how to submit pull requests and then kinda forgot about it.
