### ISSUE TITLE
Out of era item: Pumice stone

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1588]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
The item "Pumice Stone" Which drops from ghouls in Gusgen mines is out of era. It's used primarily for the "Shantotto ascention" quests.

**Comment by Shoruto** [comment]
Can confirm this is OOE

Earliest post on any website is November, 2009 and was indeed used for the Shantotto quest

https://ffxiclopedia.fandom.com/wiki/Pumice_Stone?oldid=1013487
https://www.bg-wiki.com/index.php?title=Pumice_Stone&oldid=123402
https://www.ffxiah.com/item/2776/pumice-stone
