### ISSUE TITLE
I'll Take the Big Box

### ISSUE THREAD

**Issue by Eleeciam** [EdenServer/community#1589]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Shoruto** [comment]
No details listed
