### ISSUE TITLE
Digging: Valkurm Dunes + Sauromugue Champaign have the dig tables from Western Altepa

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#159]
If you dig in VD or SC you'll only pull up items that are identical to the Western Altepa table.  If anyone has other zones that are problematic feel free to add onto this thread.

**Comment by Wiggo32** [comment]
Hmmm... I think you're right. We are going to have to go over all the dig tables most likely. May I ask which website you use for dig info?

**Comment by Wiggo32** [comment]
no problem, I'm gonna dig through all of them. that's actually a dsp issue as well cause we used their tables. but, i see that they are incorrect thanks to you!

**Comment by Wiggo32** [comment]
issue resolved: 
https://github.com/godmode/dsp/pull/462
