### ISSUE TITLE
Denied Entry to Manaclipper in Bibiki Bay to Purgonorgo Isle

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#1590]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Bought a manaclipper ticket from Bibiki Bay to Purgonorgo Isle, got onto the ferry with a friend. He made through the loading screen, but I was immediately ejected for not having a ticket. Checked my key items and the ticket disappeared.

Client version: 30181205_0

![Virtuosus_2019 04 24_235616](https://user-images.githubusercontent.com/49970272/56709245-3b05db80-66ee-11e9-99fa-27849e59c552.png)

**Comment by godmode** [comment]
Which pass did he and you buy? The single or multi?

**Comment by VirtuosusFFXI** [comment]
He bought the multi-ticket and I bought the single one.
