### ISSUE TITLE
Beastmen pet Give reduced exp

### ISSUE THREAD

**Issue by Kinunu** [EdenServer/community#1591]
### Checklist

- [/ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ /] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/ ] I have provided my client version in the details. (type /ver into your game window)

### Details

30181305_0  version.
Soloing beastmen pets as BLM is giving around half the exp it should. camp is gustav tunnel H-10, mob is goblins leeches, they check as tough to a 53 BLM, getting 75exp on first kill around 93 on chain 3. definitely not correct

**Comment by MGramolini** [comment]
related forum thread.

https://www.edenxi.com/forums/viewtopic.php?f=34&t=1423
