### ISSUE TITLE
Subcrafts for the Greatsword recipe may be incorrect

### ISSUE THREAD

**Issue by Blex64** [EdenServer/community#1593]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0

Small thing I noticed doing guild points today. Wiki has the subcrafts for the Greatsword synth listed at Leather 11, Wood 9: https://ffxiclopedia.fandom.com/wiki/Greatsword. I looked it up on the Eden DB after skilling my leather up on it (my leather is 12), and we have it listed as Leather 18 Wood 9. Not sure which is "correct" or how to reconcile them, though.

**Comment by MGramolini** [comment]
The subcrafts were unknown until very recently (and could have even changed).  That being said, i'm not sure if the DSP guys just tried to estimate based on the materials used and/or compared to items using similar materials via subcraft.  I wouldn't take what the wiki has to actually be correct (especially for the era we are in as it could have changed during the major crafting overhauls).
