### ISSUE TITLE
 De'Vyu Headhunter (I-9)

### ISSUE THREAD

**Issue by Iced-Latte** [EdenServer/community#1594]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

De'Vyu Headhunter is supposed to spawn at I-9 every 5-15min. We have been here for 2 hours and he has not popped. Mocha came with widescan and saw him pop up at J-5 in the ground. He then dissapeared. We have confirmed no one in the zone killed him.

**Comment by Iced-Latte** [comment]
De'Vyu Headhunter is supposed to spawn at I-9 every 5-15min. We have been here for 2 hours and he has not popped. Mocha came with widescan and saw him pop up at J-5 in the ground. He then dissapeared. We have confirmed no one in the zone killed him.

**Comment by Iced-Latte** [comment]
GM Iudex responded to a ticket and killed the NM under ground at I-8. I believe this is usually caused by someone aggroing the NM and zoning.

**Comment by Mozzy4Ever** [comment]
While this is a navmesh issue, could it be temp-fixed by having De'Vyu Headhunter coded as a normal mob? IE: If far outside it's normal spawn radius and unable to move back to spawn point via navmesh, despawn and respawn at spawn point
