### ISSUE TITLE
OOE mob in Misareaux Coast

### ISSUE THREAD

**Issue by VerrenGunnar** [EdenServer/community#1595]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

![image](https://user-images.githubusercontent.com/49046209/56781858-add88a80-67b2-11e9-99ba-ba8002bdbaaa.png)

Seems like the Out of Era mob Seaboard Vulture is in Misareaux Coast

**Comment by godmode** [comment]
Good catch. We had left that in as a merit camp until ToAU was out and forgot to remove it!

**Comment by Spiffly** [comment]
Bumping this as apparently these mobs are still in the game. They are doing no harm (as far as i'm aware) but only seems fair and consistant that these OOE mobs are removed. Other OOE mobs have previously been removed (worms in gusgen springs to mind) whilst these have remained.
