### ISSUE TITLE
Teleport-Altep Spell Quest

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/community#1597]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

A player able to get the scroll for free just talking to the NPC in Sandy after triggering the quest.

**Comment by tieig** [comment]
Just wanted to come here to say this still is happening. I was just able to get the scroll without actually doing anything for the quest besides flagging it. Came to open a ticket and found this

**Comment by 59blargedy** [comment]
resolved in April 12, 2021 update.
