### ISSUE TITLE
Silent Oils/Prism Powders ~5 second duration

### ISSUE THREAD

**Issue by Kreggan** [EdenServer/community#1598]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
client version 30181205_0

I bought a stack of prism powders and one silent oil to get past mobs in carpenter's landing (entrance from Sandoria) to go fishing. When I used the the oil and powder, the sneak and invisible effects only lasted about 5 seconds each. I continued to use more prism powders to see if it was just a bad roll. All the powders I used granted me invisible for roughly 3 to 5 seconds. I assume this would have been the same for the oils, had I bought a stack of those as well. https://youtu.be/j-JbGiJf9qI <--- This is a recording of what happened.

**Comment by Volkaru** [comment]
What level were you? Sneak/invis effects duration have a buff level modifier like most spells. The lower below the spell's level you are, the less of a max duration you'll have. If you're on a level 1 mule, this is about how long Sneak/Invis will list.

**Comment by Kreggan** [comment]
Ah, I didn't know that. Yes, I was level 1, because I was planning on fishing to a certain level, then bloodporting immediately after. I thought powders and oils would grant me invis/sneak regardless of level. My mistake.
