### ISSUE TITLE
Everyone's Rancor dealing way too much damage.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#160]
Had it hit my WHM for 6300, went and cleared my hate afterwards and only paid 1038 to reset, which is nowhere even remotely close to cap.  (Which is 6000.)  I screenshotted the damage, but forgot to screenshot my hate reset.  Sorry.

https://cdn.discordapp.com/attachments/487301249184563214/500877107858112512/be23978f2fbd8bc8cb7b3c80cabff7bf.png

**Comment by Serephim** [comment]
I literally just reset my hate then fought Sozu Terberry and he 1 shot both my characters back to back with everyone's rancor for 1800 damage a pop. lol

**Comment by RoninXI** [comment]
Also Sozu Rogberry shouldn't have Everyone's Rancor, just got 1 shotted by him.
