### ISSUE TITLE
got logged out randomly

### ISSUE THREAD

**Issue by TheKingOfJeuno** [EdenServer/community#1600]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by TheKingOfJeuno** [comment]
was in game, got logged out randomly, reporting it now that it started at 3:15pm PST

tried to relog in and it says same character is already logged in.

**Comment by Shoruto** [comment]
We just had a server lag spike and some players got d/ced. Wait a couple min and try logging back in.
