### ISSUE TITLE
oneshotting mobs in dyna should still allow for spawn of children

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1601]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181025_0

Various statues in Dynamis-Windurst were missing, making us unable to complete the run.

Yoran-Oran's house had only one statue, 254. The one that spawns Xoo Kaza The Solomn was not there. Nor were any of the statues at Heavens Tower up. 
So total statues missing were: 244, 248, 251, 255, 341, 331, 337, 334, and 344 as listed on this map here: 

![strategy_win1](https://user-images.githubusercontent.com/9113384/56857583-3b87b780-6924-11e9-8db7-a1ace34ac20e.jpg)

**Comment by Jimmayus** [comment]
Regarding "monsters will not popped from monsters that are time nuked" discussions, I would like to submit this discussion from 2008 of dynamis strategies:

https://www.bluegartr.com/threads/54340-General-Dynamis-Strategies-and-Party-Setups

Particularly posts #4 and #8. I see no particular way the strategy described there could be useful if monsters simply did not spawn when monsters are time nuked. Perhaps Dynamis - Windurst is unique in some fashion, but I am unconvinced without supporting evidence.

**Comment by EliannaEden** [comment]
It's a bit preposterous to claim timed nukes were never an accepted strategy.  It was a widely practiced and the core of many low-man Dynamis-Beaucedine and Dynamis-Xarcabard runs.  I'd be interested to read any posts that state that time nukes were an unreliable strategy.

**Comment by MGramolini** [comment]
The vanguard eye in that video was not one-shot, but killed by many hits over the course of a short period of time (very short).

**Comment by Jimmayus** [comment]
Right I agree, the context of the response was related to someone in Discord suggesting that time nukes will not spawn monsters. Regardless this is a tangent because as the bug report denotes the issue was a series of statues that simply did not spawn.

**Comment by EliannaEden** [comment]
> The vanguard eye in that video was not one-shot, but killed by many hits over the course of a short period of time (very short).

So you're saying if it was hit by Burst II and one shot, none of those mobs would have spawned and that entire run was lost? Ridiculous!

**Comment by MysticLogos** [comment]
Just wondering if there is any update on this from the dev team?  For reference, this Dynamis-Windurst run was the first run we've done on Eden that didn't R0 for us.  All the runs in the other cities R0'd, usually after the first pull, and the Dynamis server had to be reset for us.  This didn't happen with Dynamis-Windurst, so I am wondering if this has something to do with the statues not loading properly.  Maybe?

**Comment by Jimmayus** [comment]
We successfully completed a Dynamis-Windurst run this evening (May 11th). In conferring with Rori he indicated that Dynamis had been reset for them on a run previously during the week. For reference, the sequence of events and behaviors was:

- We cleared the NMs on the outer circle of waterways

- Clearing these nms spawned the icons at Heaven's Tower, which also spawned their NM

- With all nms cleared the boss spawned, which we were able to clear and acquire the key item.

Previously the BLM NM statue did not spawn for our first dynamis. I believe based on this experience and once again conferring with Rori that a full reboot of the dynamis server upon any open dynamis instance being empty for 5 minutes after the boss dies (or some other metric for determining a dynamis has been evacuated) would solve most problems with dynamis.

-

**Comment by Treble011** [comment]
This is still an issue.

**Comment by Treble011** [comment]
Initially, we noticed about an hour to 1.5 hours before discovering the issue, that a mob we were currently engaged with vanished like it was despawned (no other mobs in the pull, just the one vanished). We thought nothing of it and moved on, but when we got to the bridge leading to Heaven's Tower, none of the statues that are supposed to be there were up, nor were any of the statues (or NM) in Heaven's Tower. 

I ran a loop to verify that there were no other mobs up in zone, nothing.

**Comment by godmode** [comment]
This should be fixed. If it happens again please make a comment.

**Comment by Treble011** [comment]
This happening still.

**Comment by Treble011** [comment]
Specifically, tonight it wasn't a statue -- it was the SMN NM in Bastok, Gu'Nhi Noondozer -- but if I remember correctly from the last time this was happening, it was across any Dynamis zone and was fixed at the same time.

**Comment by roriffxi** [comment]
http://forum.square-enix.com/ffxi/archive/index.php/t-4226.html?s=94de84f3ea99d59f7be55a6d78849e6f

Relevant quote about mob spawns:
I'm not sure if you hit a different glitch, but your assertion about the mechanics is incorrect. If you one shot a statue in Dynamis it does spawn all of it's "children", but they spawn without aggro.

Only if the Dynamis status is an MP or HP statue. It doesn't die right away, it has that microsecond where it stops to refill everyone's MP and HP. The mobs that this kind of statue spawns do not aggro, as you stated.

If you one shot a regular Dynamis statue it won't spawn any mobs. This hasn't changed since Dynamis came out.

**Comment by Slamm21** [comment]
After thinking about my old low man xarc runs I think what rori is saying is correct.
However there should be a period, maybe 1-2 seconds after a mob is first hit, to when it dies before the mobs spawned can aggro. So if you time nuke with a rdm going at the same time as a blm, the rdm hit would land and not kill, mobs spawn, blms nuke kills eye/statue and mobs don't aggro because it was killed quickly after the first hit landed.

**Comment by 59blargedy** [comment]
resolved by another dev in July 5th, 2024 patch
