### ISSUE TITLE
Bastok Mission Fetichism not repeatable

### ISSUE THREAD

**Issue by zuzupetals** [EdenServer/community#1603]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by zuzupetals** [comment]
I cannot repeat the Bastok mission Fetichism. The gate guard (Cleades, Bastok Markets) assigns me the quest, and the chat log say i accepted the quest, but i do not get the quest. I've tried zoning but that doesn't seem to work.
ver 30181205_0

**Comment by Shoruto** [comment]
You tried to trade all 4 items to Cleades and he wouldn't accept them?

**Comment by zuzupetals** [comment]
Correct. I also zoned and tried again. I tried trading with every gate guard.

**Comment by Shoruto** [comment]
Lets try something...Do this optional part and then go back to Cleades and try trading them again. Shouldn't matter but who knows might get you past the hurdle.

Optional: Talk to Gumbah (J-7) in an upper-level house in Bastok Mines for an extra cutscene

**Comment by zuzupetals** [comment]
I'd love to try that but unfortunately I ran all the way to san d'oria last night and changed my allegiance (due to bastok never getting any outposts :P)

**Comment by zuzupetals** [comment]
After joining San d'Oria and working my way up to rank 2 i have ran into the same issue. I cannot repeat Save the Children. After talking to the gate guard and receiving the first cut scene, and after getting the message "You accepted the mission," I do not have the mission in my mission log, nor can i advance the mission by talking again to the next NPC Arnau.

**Comment by Shoruto** [comment]
I saw in some later updates to the wiki post regarding Save the Children its not required to talk to Arnau again when repeating.  Even though it doen't show the mission, see if it will let you do the fight anyways.  If you click on the Hut Door and nothing happens then we know it never gave you the mission.  This will clear up whether its just a word issue vs not actually giving the mission.

**Comment by zuzupetals** [comment]
I tried your idea. On my way out of San d'Oria I accepted the mission again. In Ghelsba I clicked on the hut door and it said "which battlefield will you enter?" Only choice was None.
