### ISSUE TITLE
Fail coffer pick with living key gave 3 hour weakness

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#1604]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Reference  ##233

/ver 30181205_0

I attempted to pick a coffer in the Monastic Cavern with a Living Key on a 75 THF but failed and received message " fails to open the chest." The coffer didn't move so I tried again, failed, and this time got the message "The chest was trapped!" Despite this message, no mimic spawned and the chest remained. I tried once more and got the message "You cannot open the chest when you are in a weakened state." To my dismay I then noticed I had a 3 hour weakness! LOL I had to die on a level 1 job to remove it.

https://imgur.com/LxMVjZx

**Comment by Shoruto** [comment]
This is not a bug, there is a chance to get a weakened state anywhere from few min to several hours

https://ffxiclopedia.fandom.com/wiki/Picking_your_Coffers_and_Chests?oldid=366679
https://ffxiclopedia.fandom.com/wiki/Talk:Picking_your_Coffers_and_Chests

There are others that list a powerful weakness as an option

**Comment by icariumkupo** [comment]
That's insane! Well still the text display missing my name from the first attempt, and then also no mimic pop from the second attempt are bugs for sure.

**Comment by Shoruto** [comment]
Mimic is not always going to happen if you fail, it can be weakness instead

**Comment by gweivyth** [comment]
Hah, yep this is working as normal.  Godmode and I spent a good 3+ hours messing with this a while back, weakness is pretty rare and gets more rare as you level up, but still possible even at 75.
