### ISSUE TITLE
Various Abilities/Spells with OOE Values

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#1605]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently, there are a few spells and abilities that I've found to be inaccurate for this era.

Protect/Protectra 4 are currently giving the retail value of 120 defense instead of the era value of 55 defense. This is a big one, as in era Protect 4 only gave 55 and Protectra 5 only gave 60 defense. Current values are much higher (120/175 defense respectively) causing everybody to have a lot more defense than they should have. This may also affect other tiers of Protect.

Samurai and Dragoon's Warding and Ancient circles have a recast time of 5 minutes instead of 10 minutes, and durations of 3 minutes instead of 1 minute. This may also affect PLD's circle buff.
(Side note: The buffs in-game descriptions mention that they increase resistance/attack/defense against the opposing mob family. I assume this is just a remnant from the retail changes and not active, but it is worth making sure that killer/circle effects are only causing intimidates and no stat bonuses.)

Warrior's Tomahawk (Merited Ability) is able to be used without consuming/equipping a throwing tomahawk. This may also affect Dragoon's Angon. 

ver 30181205_0

**Comment by greyenvy** [comment]
Reraise says it costs 175 MP but it only consumes 150 MP.  Not sure if that is intended.  Not the same issue but ancillary.

**Comment by Volkaru** [comment]
Can add on to this to say DRK's Circle is working semi-properly. Has the 10 minute recast, but also the 3 minute duration instead of the 1 minute it should have. Does not give the enhanced attack, etc. though. Just killer effects. Have not tested to see if the other circles give their OoE attack bonus, though.

**Comment by tacbox3** [comment]
SAM circle is currently a 3 minute buff on a 5 minute cool down. Haven't tested attack bonus.

**Comment by erenik** [comment]
Found fix for the Circles of protection durations and cooldowns.

**Comment by erenik** [comment]
Fixing values for protect and protectra is also easily done.

**Comment by erenik** [comment]
Proposed fixes for protectra and circles of protection: 
- https://github.com/erenik/dsp/pull/3
- https://github.com/erenik/dsp/pull/2

**Comment by VirtuosusFFXI** [comment]
Update on Tomahawk: May need to be looked at to ensure that the special defense down effect is functioning.

Taken from BG Wiki:

> If enemy has a physical resistance to a certain type of damage this ability will reduce it by 25% (from 50% to 37%, 25% to 18%, etc.).
This includes reducing 100% weapon immunities such as Invincible or on enemies such as Jailer of Temperance and ones in Apollyon SE to 75% resistance.
This also includes resistances to magic damage, so Jailer of Temperance can be nuked while Tomahawk is active.

Specifically against PLD mods using Invincible, I've fact checked this and it seems it also functioned this way in era:
[https://www.bluegartr.com/threads/39333-Quick-question-about-Tomahawk?p=1300558&viewfull=1#post1300558](url)

**Comment by ShiyoKozuki** [comment]
Warding circle is supposed to be 30 seconds not 1 minute.
https://classicffxi.fandom.com/wiki/Warding_Circle

**Comment by KnowOne134** [comment]
tested circles for duration and recast, angon, protect values, reraise values all tested in era
only thing not done is tomahawk is not coded will make new report for it
