### ISSUE TITLE
DRK AF2 Quest "Dark Puppet" Placing character behind zone line after CS

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1608]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181025_0

After the initial cutscene upon zoning into Ordelle's Caves for the DRK AF quest Dark Puppet, you are placed behind the zone line. Not a huge bug, but figured I'd report it all the same.

**Comment by 59blargedy** [comment]
resolved in January 18, 2021 update

**Comment by statuseffect** [comment]
This just occurred to me when doing this quest.
