### ISSUE TITLE
Crashed on Promyvion Dem NM, didn't get win after logging back in

### ISSUE THREAD

**Issue by RottenUnagi** [EdenServer/community#1609]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [? ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
[tl:dr I experienced a freak crash~d/c recently in Promy Dem which caused me to miss the win. I want to know if this can possibly be remedied apart from going back through the demi-hell that is any given Promyvion mission.]
_Client ver. 30181222_1_

So this is *a bit* delayed, but: not quite 2 weeks ago I had a very untimely crash, d/c, idk, just as my Promy Dem party was nearing victory over the Progenerator. This may or may not just be coincidence but I went to hit some macro or other and well, time suddenly stopped. My send/receive started dwindling so I switched over to my alt who was waiting outside the arena in another Promy party (full alliance) and was also d/c'ing. Switched to my browser and it was navigating fine. Discord/voice chat were working fine. My internet otherwise was fine, so I'm baffled. Eventually both my chars hit R0 & full d/c'ed. By the time I logged back in to my main the battle was won & I was stuck alone in the empty arena, uncapped, and without the win or a way to get out. [GM] Banner helped get me unstuck but wasn't able to provide any further assistance as far as the Dem victory & advised I try later with the daytime GMs (it was ~12:30am MST at this time). Everyone encouraged me to contact a GM or submit a bug later on. I dragged my feet, didn't do it. I tried Promy Dem again 2 nights ago & failed miserably on the 3rd floor (Leeroy Jenkins was in my party). So f**k it...

Dear GMs: please gimme *Light of Dem* & help me move on to the next CS in Lufaise. 

Really though, is this something that can somehow be further helped by a GM/admin?

![dem_debacle](https://user-images.githubusercontent.com/48870729/57053078-f1b31000-6c48-11e9-83d4-aa13945a8685.jpg)

**Comment by panfunk** [comment]
Probably connected to:
https://github.com/EdenServer/community/issues/693#issue-396728216

I suppose after a DC/tractor you loose the 'BCNM' buff and thus are no longer recognized as participant in the BCNM and thus can't be target of any actions from ppl with the BCNM buff / gain rewards for clearing

**Comment by RottenUnagi** [comment]
Is this a fact or a speculation? I mean, we won. We were a breath away from the win when I crashed. The longer this goes without a real response or investigation, the slimmer my chances of somehow proving it happened, or having eyewitnesses be able to back me up from memory, or whatever it takes to satisfy the mods. Haven't even gotten a response from a GM call other than the one that got me unstuck  :|
