### ISSUE TITLE
Accounts swap if 2 PC's log in from same house

### ISSUE THREAD

**Issue by raegn** [EdenServer/community#1610]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

If my roommate and I log into the game at the same time, the server will log us into each other's accounts instead of our correct accounts.  The issue only happens if you log in very close to each other, but seems to occur reliably.  Only a minor annoyance but I figured it might be worth reporting.

Thanks for your time!

**Comment by Setz0r** [comment]
this is not a fixable issue, people logging in from the the same home internet will just need to take turns getting fully logged in
