### ISSUE TITLE
Ogre Eel - Halcyon Rod / Line Snap

### ISSUE THREAD

**Issue by freddiepines** [EdenServer/community#1611]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Fishing for Ogre Eels with Halcyon Rod / Sinking Minnow can result in line breaks - per the database at http://www.great-blue.jp/?fid=023&lng=en and my own experience as a level 100 fisher from 2005 on this should not be the case.

Easily reproducible by fishing with Halcyon Rod and Sinking Minnow in South Gustaberg.

Also seems like Cobalt Jellyfish have a much higher snag rate on Sinking Minnow than they should in this area.

Client Version - 30181205_0

Thanks.

**Comment by freddiepines** [comment]
These can also break a Halcyon rod which is absolutely incorrect.

Thanks again.

![Ogre Eel](https://user-images.githubusercontent.com/50085658/57117385-a6246300-6d29-11e9-9a39-c660b7781ec7.jpg)





Willow Fish. Rod | Unknown |  
Yew Fishing Rod | Unknown |  
Bamboo Fish. Rod | Unknown |  
Fastwater F. Rod | Unknown |  
Tarutaru F. Rod | Unknown |  
Glass Fiber F. Rod | Unknown |  
Carbon Fish. Rod | Line is breakable |  
Clothespole | Unknown | Too Small
S.H. Fishing Rod | Unknown | Too Small
Mithran Fish. Rod | Unbreakable | Too Small
Comp. Fishing Rod | Unbreakable | Too Small
Lu Shang's F. Rod | Unbreakable |  
Hume Fishing Rod | Line is breakable |  
Halcyon Rod | Unbreakable |  
Ebisu Fishing Rod | Unknown





Willow Fish. Rod | Unknown |  
Yew Fishing Rod | Unknown |  
Bamboo Fish. Rod | Unknown |  
Fastwater F. Rod | Unknown |  
Tarutaru F. Rod | Unknown |  
Glass Fiber F. Rod | Unknown |  
Carbon Fish. Rod | Line is breakable |  
Clothespole | Unknown | Too Small
S.H. Fishing Rod | Unknown | Too Small
Mithran Fish. Rod | Unbreakable | Too Small
Comp. Fishing Rod | Unbreakable | Too Small
Lu Shang's F. Rod | Unbreakable |  
Hume Fishing Rod | Line is breakable |  
Halcyon Rod | Unbreakable |  
Ebisu Fishing Rod | Unknown




Willow Fish. Rod | Unknown |  
Yew Fishing Rod | Unknown |  
Bamboo Fish. Rod | Unknown |  
Fastwater F. Rod | Unknown |  
Tarutaru F. Rod | Unknown |  
Glass Fiber F. Rod | Unknown |  
Carbon Fish. Rod | Line is breakable |  
Clothespole | Unknown | Too Small
S.H. Fishing Rod | Unknown | Too Small
Mithran Fish. Rod | Unbreakable | Too Small
Comp. Fishing Rod | Unbreakable | Too Small
Lu Shang's F. Rod | Unbreakable |  
Hume Fishing Rod | Line is breakable |  
Halcyon Rod | Unbreakable |  
Ebisu Fishing Rod | Unknown

**Comment by Mozzy4Ever** [comment]
Still an issue, have broken 3 halc rods now on Ogre Eels

**Comment by Setz0r** [comment]
angler sense procs are "critical bites" from being close or above the fishes level.  it doesn't make your rod stronger for catching.

**Comment by Setz0r** [comment]
then again, on the flipside, there should be a level difference bonus applied to durability in general which was in my original system, but got scrapped because of misunderstanding the data i was reading.

**Comment by Mozzy4Ever** [comment]
Yea I figured that if you were able to get angler sense procs, it would be unlikely for you to break a rod... Nonetheless, ogre eels shouldn't be able to break a half rod
