### ISSUE TITLE
Adaman Cuirass desynth recipe missing

### ISSUE THREAD

**Issue by gavin-eden** [EdenServer/community#1612]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181222_1

Desynth recipes for the Adaman Barbuta, Sabatons, and Cuisses aren't in the game.

Steps:
1) Use Lightning Crystal + Any of the listed items.

Result "Combination of materials doesn't not exist"

**Comment by gavin-eden** [comment]
Title is wrong, Cuirass is actually in the game, but the others arent

**Comment by Far-The-Killer** [comment]
The desynth for these weren't listed until almost 2010 on the wiki. Do you have any proof that these could be desynthed in era?

**Comment by gavin-eden** [comment]
BG-wiki has the at least headpiece as being desythable as early as Jan 2008, but it doesnt even have the synthesis recipe before that, so not sure how to track down more proof.

Nvm I guess

**Comment by Veesae** [comment]
https://github.com/DarkstarProject/darkstar/pull/6427
