### ISSUE TITLE
Possible accuracy issues

### ISSUE THREAD

**Issue by Qair** [EdenServer/community#1613]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I opened up an account on retail to do some testing for monk (of course) and I noticed a few odd things about our server compared to squares with base accuracy.

The formula that's used to determine base accuracy is as follows:

Equation: Accuracy from DEX = floor( DEX×0.75 )
Equation (200 ≤ Skill ≤ 400): Accuracy from Skill = floor( (Skill - 200)×0.9 ) + 200

If we were to take my mnk/war for instance

http://tinypic.com/r/2we0192/9

with 292 h2h skill it has a base accuracy of 316

according to the formula ((292 - 200)x.9) + 200 = 282.8
calculating the acc from dex = dex x.75 = 68 x .75 = 51
282.8 + 51 = 333 base acc
Riaq's current base accuracy with full h2h merits = 316

Now you may be thinking but riaq what about in 2007, so i found this formula from 2007 which assumes 2 dex = 1acc for non 2handers

When combat skill is beyond 200

Accuracy = ( 200+ (Combat Skill-200)*0.92 + dex/2 

200+(292-200)*.92 + 68/2 = 323.64 which is still higher than riaqs 316 base.

**Comment by Enignite** [comment]
200 + 92*0.9 + 68/2 = 316.8

MNK does use 2 DEX = 1 Acc but you are multiplying by 0.92 in the last equation.

**Comment by Qair** [comment]
I'm using .92 because that's the equation that was give from 2007 listed on the wiki.

**Comment by Qair** [comment]
I'm using .92 because that's the formula listed on the wiki for 2dex = 1 acc 
https://ffxiclopedia.fandom.com/wiki/Accuracy?oldid=231107

**Comment by Enignite** [comment]
That was an error, it was fixed the following month in April 2007.
