### ISSUE TITLE
Imps crossing into Azouph Isle Staging point when aggroed

### ISSUE THREAD

**Issue by dank-CoP** [EdenServer/community#1614]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Zoned into Azouph Isle Staging point after having carby take aggro off imp. Carby dead before zoning.  After zone, the imp crossed into staging point and killed me in front of immortal guard.  Pretty sure they shouldn’t do that.

**Comment by tacbox3** [comment]
I'm not sure if this is incorrect behavior, but I can confirm this. I had an important chase me into both azouph and ilrusi still staging points.

**Comment by Volkaru** [comment]
This is incorrect behavior. It is (or was at one point) being worked on, though. Will probably be a part of the Navmesh overhaul.

**Comment by Shoruto** [comment]
Related to #970
