### ISSUE TITLE
Can't access certain guild craft related NPC's Buy menu

### ISSUE THREAD

**Issue by Lingchao8** [EdenServer/community#1615]
Can't access the shop of Chaupire (Woodworking guild NPC).  There are other NPC that are guild related in the Metalworks (Smithing guild), Windurst Woods (Bonecraft guild) that I'm also unable to access their shop.  I am able to buy from all the NPC's that stand next to them and sell the guild's raw materials.  I am able to sell items to them so i can view what they should be selling possibly.   
First SS is being able to see the vendor's raw materials working fine
https://gyazo.com/7abb14d2441e0b85e012fabd01fd2e1c
Second SS is seeing what they should have or sell rather
https://gyazo.com/aeeaf362430d9b46bd7204c3ca95f3d0
Version:  30181003_1

- [- ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ -] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ -] I have provided my client version in the details. (type /ver into your game window)

**Comment by 59blargedy** [comment]
this was related to your version being off
