### ISSUE TITLE
Shen's Water Elementals Casting Every element of nukes and black magic.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1616]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The Shen's Filtrates that assist Shen do not have proper spell lists. They can cast any Aga III, AM, Spikes, BLM enfeeb (drown, choke, etc.) And Sleepga II.
Did a few Shen runs yesterday. The adds would open with anything from Sleepga II to Thundaga III. 

They cast fire magic more than anything else. They also seemed overtuned. We had no problem killing Shen himself. But trying to take down the elementals they about wiped an alliance. Ended up having everyone alive log off to shed hate. Runs after that we just had someone open with Sleepga and kite them around the whole island til Shen was dead. 

Which means also the hate-linking with Shen described on the wiki is not functioning, either. 

https://ffxiclopedia.fandom.com/wiki/Shen

**Comment by Shoruto** [comment]
Related to closed #123

**Comment by Volkaru** [comment]
@Shoruto Godmode asked me to make a new seperate bug report after the latest closed Shen one.

**Comment by Shoruto** [comment]
Thats no problem, just wanted to mentioned the other one incase it helps get this one fixed quicker :)

**Comment by gweivyth** [comment]
I think the elementals casting different spells is a new issue, they didn't cast anything but water-based spells during our fight.  Were they actually sleepable now?  Or were you just using Sleepga to grab hate?

**Comment by EliannaEden** [comment]
They slept once easily, resisted heavily after that and were eventually immune to seal + sleep. We just had one person out of the alliance pull them and run across the island, then the person who popped it and the kiter /logout after Shen died.
