### ISSUE TITLE
Promyvion-Vahzl

### ISSUE THREAD

**Issue by Mikokiko** [EdenServer/community#1617]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

In Promyvion-Vahzl, corsair quickdraw Iceshot does about 240 dmg / shot.

I was not even using DPS gear, I think I could have poped around 400 dmg shot with all dmg gear on. I did not try with full DPS gear since it really didin't seem to be working correctly, did not want to push it over.

**Comment by Shoruto** [comment]
Which monster did this damage occur?

**Comment by Mikokiko** [comment]
I did once on last floor boss, then on the promy valz bosses. 

Damage was flat constant 240, only one time i got a 120(resist). Even the one that resisted me, I was able to do 240 with other shot on same mob. 

Element did not seem to affect anything. I could not sleep anything, and dispel was often resisted. 

It just seem the damage is off atm. I did not test other elements out of ice/light/dark.

**Comment by 59blargedy** [comment]
with all the changes done to quickdraw and magic hit rate over the years, i dont believe this is an issue anymore
