### ISSUE TITLE
Gob in Dynamis Jueno using Blu spell.

### ISSUE THREAD

**Issue by baroom84** [EdenServer/community#1619]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
In Dynamis Jueno a Dragontamerer after the Megaboss used a Blu spell Feather Storm.
![Baroom_2019 05 05_202514](https://user-images.githubusercontent.com/46089689/57202500-14f4fc80-6f74-11e9-9bd1-819c40878bc0.png)

**Comment by MGramolini** [comment]
This seems more likely that it’s the yagudo ability. Have you seen dragontamers use any other yagudo abilities?

**Comment by baroom84** [comment]
No just this one twice.
