### ISSUE TITLE
Unable to progress BRD AF Hands quest (Borghertz's Harmonious Hands)

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#162]
http://ffxiclopedia.wikia.com/wiki/Borghertz%27s_Harmonious_Hands

Character: Aneyus

I was able to start the quest and get the Old Gauntlets key item out of the Zvahl Coffer, but unable to do any of the steps after that. I tried doing the "first time completing AF" portions of the dialogue as well, just in case, but Deadly Minnow had nothing to say to me. I then tried to pop Dark Spark and the ??? only said "There is nothing out of the ordinary here."

**Comment by Xaver-Entropia** [comment]
did you examine the wooden box ??? in port jeuno and got the CS?

**Comment by Xaver-Entropia** [comment]
i did this today. talked with the npc in upper jeuno and then Deadly Minnow didn't have anything to say. But we got the CS in port jeuno right after, where the ghost asks you to go to kill dark spark.
Haven't gone there yet, I'll see if it works when I have the chance

**Comment by Aneyus** [comment]
I tried to get the CS in Port Jeuno on multiple jobs including Bard but nothing ever happened when I touched the ???. I believe this CS is the next necessary step for me but for whatever reason it's not triggering

**Comment by Aneyus** [comment]
Haven't gotten around to double checking everything on Bard yet, been too busy exping! Lol.

**Comment by Aneyus** [comment]
Redid absolutely all of the conversations on bard and was able to progress in the quest. Closing this ticket!
