### ISSUE TITLE
Summoner issues

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#1620]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [NA ] I have provided my client version in the details. (type /ver into your game window)

### Details

Summoning Skill over the level cap does not grant avatars the bonus' they should.
https://ffxiclopedia.fandom.com/wiki/Avatar_Physical_Accuracy

Using /checkparam <pet> and putting on + summoning skill gear (while also capped on skill for the level) makes no change to the avatars accuracy rating.
This should also affect their magic accuracy
https://ffxiclopedia.fandom.com/wiki/Avatar_Magical_Accuracy

Additionally, the Summoner's Bracers only grant 7 Accuracy when it should be 14 (as noted in my first link).  Evoker's slops should also grant 14.

Summoner's Pigaches are only giving 7 attack, but I can't find a source that says what they should be.  Maybe someone with an active retail account can checkparam it for us.

Lastly, magic accuracy of avatars in general is just bad.  Khimaira is the only HNM that doesnt resist Tier2 merits the vast majority of the time.  Even against xp mobs the resist rate for tier2 merits is 50% or higher.

Fixing the +summoning skill bonus might fix this issue.

**Comment by chlorr** [comment]
can confirm, since 70BP's were nerfed, smn feels super lack luster with T2 merits, asked around the old days but no one had T2 merits back then on smn for this reason

**Comment by Jimmayus** [comment]
Summoning Magic skill actually does not affect  the duration of wards either. In addition, wards themselves have wildly inconsistent timers. This is easily visible by checking Rolling thunder's base duration and then adding any item (evoker's ring is good) and checking duration. You'll see it does not have the expected effect of increasing duration by (60 base = 2 sec/skill till 180 sec, and ring = +10 skill so 10x2) 20 seconds.

**Comment by Blex64** [comment]
I'm fairly certain that Summoning Magic Skill only affects Blood Pact accuracy + magic accuracy, not overall. This isn't a determination on whether it's working or not, but I don't think you'd see it reflected properly in /checkparam.

**Comment by bkesecker** [comment]
At this time, summoning magic skill does not appear to be used for any calculation in Eden's version of DSP code.  For reference:
https://ffxiclopedia.fandom.com/wiki/Category:Summoning_Magic?oldid=373534
