### ISSUE TITLE
Error 3307 - Characters Both Online and Can Not Log In

### ISSUE THREAD

**Issue by Dabman710** [EdenServer/community#1622]
I am trying to log in my characters Day and Night but the server says they are online already, which I am not logged in. When I try to log in I just get 3307 errors and I have been trying to log in for the past hour.  They have been sitting in Zitah for hours so no one is using them, the server seems to be keeping them online for some reason.

- [ Yes] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [Yes ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [Yes ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Volkaru** [comment]
Hot and Mocha are having this same issue, too.

**Comment by Xenith-the-Red** [comment]
Me too on "Xenith"

**Comment by Vrysol** [comment]
Me too on "Vyrsol"

**Comment by HotMochaNoWhip** [comment]
Same what Volkaru said. Hot is stuck in limbo and needs a forced loggout.

**Comment by Mozzy4Ever** [comment]
^ for Mozzy

**Comment by godmode** [comment]
Were you guys trying to log in when the server was under maintenance before I announced it was online or tried after?

**Comment by Mozzy4Ever** [comment]
I was logged in and forgot to logout before it shutdown, though I did also try to login cause someone said it was up (I got duped good)

**Comment by Vrysol** [comment]
I honestly don't remember. I don't think I tried logging in until I saw the green server status on the web page but I could be wrong.

**Comment by HotMochaNoWhip** [comment]
It might have been that @godmode ! I also got duped by someone joking that it was up and seeing the green light server status on the webpage. But Hot could have also easily been logged in before the server went down. I attempted to log in on Mocha as well before you made the announcement, but that character I can use just fine.

**Comment by Xenith-the-Red** [comment]
I was still logged-in when maintenance started. I only attempted after seeing a live Eden twitch stream up.

**Comment by Dabman710** [comment]
6 hours later still looks like they are still logged in. I went afk for a while before the maint. and was not able to log my chars off before time.

**Comment by Xenith-the-Red** [comment]
Same, I sent an in-game GM ticket on a new account too

**Comment by godmode** [comment]
I believe I have fixed the issue. We’ve only had an issue like this once but odd things can happen from time to time if you leave your character logged in during maintenance. If at all possible try to log off ahead of time.

**Comment by Drakesbane** [comment]
I am having the same issue right now. unable to log back in due to character already online. I dc'd while zoning into sandy.

**Comment by Drakesbane** [comment]
> I am having the same issue right now. unable to log back in due to character already online. I dc'd while zoning into sandy.

Im back in. Took about 30 min for the system to log him out.
