### ISSUE TITLE
Lost Outpost warp after Immigrating to San d'Doria

### ISSUE THREAD

**Issue by zuzupetals** [EdenServer/community#1624]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by zuzupetals** [comment]
I previously had the North Gustaberg outpost warp, but after changing allegiances to San d'Oria I lost the warp. I have checked available warp choices on Jeanvirgaud on my level 20 RDM and have all of my outpost warps except North Gustaberg. It is my understanding that outpost warps are kept after changing Nations, as it states here: https://ffxiclopedia.fandom.com/wiki/Immigration_NPC

**Comment by Hatberg** [comment]
Please consult the era correct wiki article. Back in 2007 you would lose outposts when changing allegiance.
https://ffxiclopedia.fandom.com/wiki/Immigration_NPC?oldid=330362

If you still have actual Outpost warps after changing allegiance, this would be the actual bug.
