### ISSUE TITLE
Call Wyvern drops Mazurka

### ISSUE THREAD

**Issue by burkewitz** [EdenServer/community#1625]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0

Characters: Friendjack & Needle

Using Call Wyvern repeatedly strips both Mazurka effects. For the hell of it I put on a battery of buffs (spells and songs), popped Call Wyvern, and mazurka is the only one affected. Found no evidence that this is intended or era. Guessing it’s a side effect of the prior Mazurka fix (to drop on damage done or taken).

Super not a big deal. Just have to change my order of operations when I warp the two toons to a new zone or something

**Comment by burkewitz** [comment]
Super not a big deal. Just have to change my order of operations when I warp the two toons to a new zone or something.

**Comment by godmode** [comment]
Yep, that is what did it. Whoever picks up this ticket should probably address this as well as the dropping sneak when HELM ticket. It’ll require deleting effects individually for these activities rather than as a batch process.

**Comment by burkewitz** [comment]
Ha I figured. Well Godspeed to whoever takes it. Basically data entry at this point.

**Comment by 59blargedy** [comment]
resolved in March 22, 2021 update
