### ISSUE TITLE
Lamia Harp

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#1632]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)

### Details

Lamia Harp is supposed to have double casting range, it currently does not. 

https://ffxiclopedia.fandom.com/wiki/Lamia_Harp

**Comment by xizeta** [comment]
This is not confirmed and needs testing on retail. Stringed instruments **do** have a longer range than Wind instruments, which is probably the source of this rumor.

**Comment by 59blargedy** [comment]
tested everything i could think of to test comparing a standard harp and a lamia harp, from stat differences (nonexistent) to range of cast differences (none, both enemy and player), to virelai duration (no change) to horde lullaby radius (no change) to offensive spell range (no difference) to chr song increase (none). gonna put this one to rest.
