### ISSUE TITLE
NMs with Random Spawn Locations always spawn in the same spot.

### ISSUE THREAD

**Issue by Schlomoo** [EdenServer/community#1634]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
NMs such as Sozu and KA are supposed to have spawn ranges but instead always spawn in the same location, i can only assume other NMs are this way also. in Actual Era these NMs had random spawn locations within a designated area.

**Comment by godmode** [comment]
Not all NMs are like this we will treat this ticket as KA and Sozu though. If you see others please open a ticket for them.

**Comment by erenik** [comment]
This seems to apply to Tremor Rams, Steelfleece Baldarich and Ramping Ram as well, have always found them within feet of a single position.

**Comment by Elysien** [comment]
Believe it's the same with Odqan or however it's spelt as well, the NM cluster in misa coast, outside tav.

**Comment by godmode** [comment]
Sozu and KA are in review.

**Comment by gtapperdesign** [comment]
Can confirm this is happening on Leaping Lizzy. Only the top place holder LL spawn will always spawn at the southeast corner of F-8. Bottom place holder LL spawn is still randomized.

Stardew | Valley

**Comment by 59blargedy** [comment]
none of the mobs listed here have static pop locations at this point in time, so closing
