### ISSUE TITLE
Centurio XII-I underground, but not in a tunnel

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#1635]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Centurio XII-I is underground, but it doesn't appear he's in a tunnel. Found him on widescan then used /wireframe to determine he's not in a tunnel. 

![Azmanz_2019 05 11_104930](https://user-images.githubusercontent.com/15933400/57573346-1f335280-73db-11e9-83cf-a9de06121484.png)

**Comment by godmode** [comment]
While this is a bug it is likely to be an issue with pathing and navmesh which will be fixed significantly into the future. Someone probably zoned him and he ran into the floor while pursuing them. Please place a GM ticket for these so that they can despawn the mob.
