### ISSUE TITLE
Cannot Promote/Break linkpearls of people who aren't equipped in #1 slot.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#1639]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

As noted in the title of the thread, as the linkshell holder, if a player does not have their linkpearl equipped in linkshell slot 1, you are unable to kick them nor promote them to pearlsacks.  This is really inconvenient when trying to remove troublesome players, as it is a very well known issue that players use to dodge being kicked when doing uncouth things.

**Comment by godmode** [comment]
Can you inform me if they were in the same zone as you?

**Comment by gweivyth** [comment]
Randomly, on this specific occasion, they actually were.  We were both in Bastok Mines.
