### ISSUE TITLE
Outpost Warp took me nowhere?

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#164]
Paid for an outpost warp and was not teleported anywhere.  My character stood in place, invisible, giving the monsters chasing me a full 30 seconds to chase me down and kill me when I very clearly should have been gone.  Screens attached...

https://i.gyazo.com/adfc4511f930a8b6c6d07e760925e276.png

https://i.gyazo.com/54f34b0c6914fb341b95f5bf8398cc4a.png

**Comment by roriffxi** [comment]
I experienced this a couple times trying to outpost from town.  The issue wasn't affecting every outpost and it resolved itself (or at least, I haven't had an issue recently) after a day or two.

**Comment by godmode** [comment]
Please comment if you have this issue after next patch.

**Comment by archfiendrubicante** [comment]
Issue is still occurring.

**Comment by archfiendrubicante** [comment]
Just occurred to me in Qufim Island, I flee'd through a group of giants, attempted to outpost warp, and my avatar disappeared and didn't go anywhere, forcing me to zone to get rid of the monster aggro.

Unsure if CP for the warp was deducted or not.

**Comment by archfiendrubicante** [comment]
I think the common issue here is the having of aggression while triggering the teleport

**Comment by godmode** [comment]
Yes, this issue was a different bug. Aggro and warping may cause other issues. Remember though, that if it were like retail it would cancel the menu.

**Comment by archfiendrubicante** [comment]
They were miles behind me before my teleport went nowhere though. Generally the cancelled menu results when you're speaking to an npc and interrupted by aggressive actions.

This happened completely by itself and independent of monster attacks, there was a good 10 seconds between my avatar disappearing and my warp not taking me anywhere before any monster hit me. After that I zoned.

**Comment by archfiendrubicante** [comment]
You could probably replicate this by activating flee, running through the giants south of the delkfutt's entrance, then attempting an outpost warp.
