### ISSUE TITLE
Worm appeared claimed

### ISSUE THREAD

**Issue by Shoruto** [EdenServer/community#1642]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Version - 30181205_0

I was in South Gustaberg waiting for worms to show up. They started respawning and one of them spawned purple (claimed) but no one was around them.

<a href="https://ibb.co/R2JxZ5B"><img src="https://i.ibb.co/sjX0kB6/Zork-2019-05-13-182651.png" alt="Zork-2019-05-13-182651" border="0"></a>

**Comment by burkewitz** [comment]
Could very well have been one someone smacked while submerging, and then left it’s range but not the zone

**Comment by Shoruto** [comment]
Ah this might be the case

**Comment by Shoruto** [comment]
Ah this might be the case
