### ISSUE TITLE
Bone Cudgel +1 only gives NQ value for GP

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#1643]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Bone_Cudgel_%2B1

NQ 768
HQ Should be 1,088

**Comment by gweivyth** [comment]
Can confirm, did this yesterday as well, woke up to make a bug report yet here it is.
