### ISSUE TITLE
Lufaise Diatryma are using NM variants of tp skills

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#1646]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

See https://ffxiclopedia.fandom.com/wiki/Category:Rocs for details

The Diatryma are Roc type monsters near the Sacrarium. I noticed today while learning Feather Barrier that instead of using the regular Roc-type variant abilities 'Triple Atttack', 'Gliding Spike' and 'Scratch' they are instead using the NM-only ability replacers 'Giga Scream', 'Blind Vortex' and 'Dread Dive'. I believe they may be erroneously set to use NM tp moves instead of regular monster moves.

ver 30181205_0

**Comment by 59blargedy** [comment]
at some point this was resolved as diatryma's skill list does not contain these moves at present.
