### ISSUE TITLE
Commodore Tricorne (COR Relic Hat) has no effect on Phantom Roll

### ISSUE THREAD

**Issue by xizeta** [EdenServer/community#1647]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30190305_0

Tested with Evoker's Roll and only ever received the "No SMN" roll values.
https://ffxiclopedia.fandom.com/wiki/Evoker%27s_Roll

```
Occasionally supercharges rolls with bonuses usually only received if a specific job is in party, without the need for that job to be present. Chances of effect happening seem to be around 31-33%.
```
https://ffxiclopedia.fandom.com/wiki/Commodore_Tricorne

**Comment by xizeta** [comment]
Was finally able to reproduce the effect and confirmed the rate is correct.

**Comment by setsuk0** [comment]
Couldn't find a new bug report for this, but I've the COR relic hat for quite some time now, have never once seen this proc on evokers. Not sure if it was broken in a more recent patch, but I've had multiple people tell me it doesn't work for them either. Probably need to reopen this.

**Comment by Steam-arch** [comment]
Tested on test server and didnt find anything that was off. Went through most scenarios (different merits, having 1 & 2 rolls active, double upping doesnt remove buffed roll either). Rate of activation seems correct too. 

![image](https://user-images.githubusercontent.com/69089249/194570584-28b51a40-726d-42bf-b386-a42201939b72.png)
![image](https://user-images.githubusercontent.com/69089249/194570592-804a417c-423a-48ca-9509-ff32d6128ab7.png)
![image](https://user-images.githubusercontent.com/69089249/194570604-d8bdd16d-c9be-45ee-a848-65005d5e6eb9.png)

**Comment by setsuk0** [comment]
Weird, thanks for testing. I had taken cor to multiple camps, multiple JoLs and not had a single proc + had others telling me they were having the same issue with it not ever procing. Tested just now and got 1/6 to proc. Guess I just had insanely bad luck.
