### ISSUE TITLE
Yagudo Conquistador missing Hyoton: Ni drop.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#1649]
I'm about 100 kills into farming this scroll.  I've seen 3+ drops of each of the other scrolls in the loot table, but this one seems to be omitted.  Would just like an audit to make sure. 

https://ffxiclopedia.fandom.com/wiki/Hyoton:_Ni

**Comment by bkesecker** [comment]
Audit passed.  Also drops from the same named mobs in Castle Zvahl (not necessarily the same rate).

**Comment by gweivyth** [comment]
Bummer.  Terrible luck then.  I just bought one, screw it.
