### ISSUE TITLE
Den of Rancor lantern gates broken

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#165]
The gates in den of rancor are not functioning correctly. The torches should stay on until all are lit. The gates should be soloable. It explains that in this mission. http://ffxiclopedia.wikia.com/wiki/The_Temple_of_Uggalepih
You should only need one lantern.
Currently, the only way to open 1 of the gates (G-7/G-8 Map 3 By Hakutaku) with the unlit lantern in time is if you have Crimson Cuisses or Strider Boots. And even then you can barely make it, you have to be flawless in your timing. The others are impossible. This gate should remain open for 15 minutes as well to give you enough time to collect the blue and crimson rancor flames that are outside of this gate in order to get through the next gate that is ahead.

**Comment by godmode** [comment]
I believe they increased the time to allow for solo players at a later date. I remember the flames going out.

**Comment by Serephim** [comment]
This is not true. You could always get through all the gates solo. The flames do go out eventually, but it is after a long period of time. Here is a proof from as early as 2004. 
![zm4 - the temple of uggalepih __ q_ - http___ffxi allakhazam com_db_quests html](https://user-images.githubusercontent.com/43891789/46961168-2a551880-d06e-11e8-9b00-8518b03ceba4.png)
