### ISSUE TITLE
Vrtra - Bugs / Issues

### ISSUE THREAD

**Issue by xerodok** [EdenServer/community#1650]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Current Client: Fully up to date

Referencing #1250 which has been open with no response. This issue is specifically for the wyrm, Vrtra.

**Issues:**
1. Regain - Vrtra has regain which I would eyeball triple the amount it should. During a normal fight, it will spam TP moves back to back without being damaged. Damaging the monster causes Regain and normal TP gain to clash causing even more spam. 

2. Pathing - when kiting, it does not draw in on the out edges of the room; specifically by the door. Vrtra also will not walk or route to the top threat holder and will stop and spam casts instead. This potentially is related to the regain issue and her wanting to use a TP move instead of moving.

3. Spells - overcasting Bio IV is spammed rather than Bio III, Dispelga, Blindga, and Sleepga II. In era, Bio IV was not part of the rotation.

**Comment by xerodok** [comment]
Other related ticket but without data: https://github.com/EdenServer/community/issues/807

**Comment by 59blargedy** [comment]
items 1 and 3 resolved december 7 update. item 2 remains but is featured on this ticket, so closing this one and leaving the other. https://github.com/EdenServer/community/issues/2096
