### ISSUE TITLE
In a Pickle

### ISSUE THREAD

**Issue by Crissski** [EdenServer/community#1652]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Troubles with NPC not responding while trading.
Quest is listed in current quests
When trading a crawler calculus to the NPC she doesn't respond at all.
I also had this issue with my Adventurer's Coupon being traded to the correct NPC for that (will be reported seperately) However, I was able to trade for a different quest so its not a global issue for all quests.

Version: 30181205_0
Quest: "In a Pickle"
NPC: Chamama
Character name: Tyrionn

**Comment by Far-The-Killer** [comment]
She takes a smooth stone, not a crawler calculus. Did you mean smooth stone?

**Comment by Crissski** [comment]
No. Thank you for solving that. I must have not read the quest in details. Sorry
