### ISSUE TITLE
Adventurer's Coupon

### ISSUE THREAD

**Issue by Crissski** [EdenServer/community#1653]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

Issue with trading Adventurer Coupon to NPC  Selele in Windurst Woods.
The NPC doesn't respond to the trade transaction.
https://ffxiclopedia.fandom.com/wiki/Adventurer%27s_Assistant
She doesn't speak or accept the trade.

version : 30181205_0
Character: Tyrionn & Nesandra

**Comment by falisaxi** [comment]
This is accurate to era as is. Selele is an out of era NPC
https://ffxiclopedia.fandom.com/wiki/Selele?action=history

**Comment by xizeta** [comment]
Ah, that's right, good catch. To be clear, the correct NPCs are labeled "Overview Map" in that table.

```
Jack of Clubs | Port Windurst D-6
Jack of Diamonds | Windurst Walls C-13
Jack of Hearts | Windurst Waters G-9
Jack of Spades | Windurst Woods H-10

#Bricorsant | Port San d'Oria H-8
#Daveille | Northern San d'Oria D-8/9
#Luthiaque | Southern San d'Oria G-9

Arva | Bastok Mines H-7
Dulsie | Port Bastok J-8
#Quasim | Metalworks G-8
Reet | Bastok Markets G-7
```

I remember having the same issue when I started, and I wasn't sure about this myself, so I went ahead and tested all of the NPCs. Some of these are not working correctly (I have marked with a #) and this will be addressed in another ticket.

Thanks for your report!
