### ISSUE TITLE
Algol Fire damage proc rate

### ISSUE THREAD

**Issue by him911** [EdenServer/community#1654]
### Checklist

- [yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ /] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ /] I have provided my client version in the details. (type /ver into your game window)

### Details  Algol Fire damage proc rate is not working. 
this weapons saving grace was its additional dmg from its very high fire dmg proc rate. ATM its not procing at all. I havent tested it long enough to see if the triple attack even procs

**Comment by baroom84** [comment]
Tripple attack procs
