### ISSUE TITLE
Voll the Sharkfinned

### ISSUE THREAD

**Issue by him911** [EdenServer/community#1655]
### Checklist

- [ yes] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ yes] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Voll the Sharkfinned in SSG is not spawning. I might have spent one week there spawning every single nm and its the only one that never showed up.

**Comment by 59blargedy** [comment]
just went to fix this and had no issues with his spawning. there's just one ph and it's in a v specific area.
