### ISSUE TITLE
Mob levels just outside at East Sarutabaruta

### ISSUE THREAD

**Issue by agjevik999** [EdenServer/community#1656]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I searched and couldnt find anything related, but I've lvld a few jobs recently just outside Windurst in East Saruta, and I noticed that there are Savannah Rabbit there that seems to have too high of a level. Ive noticed that the vary from 2-6. Maybe Im wrong and this was always like that, but I feel like I remember them being slightly lower then that and quite easy to solo around lvl 3 max, at least the ones that are just outside of the town.

**Comment by Mozzy4Ever** [comment]
https://ffxiclopedia.fandom.com/wiki/East_Sarutabaruta

They are listed as level 1-6, though I'm pretty sure in retail the farther you got from the city the higher their average level was whereas the closer rabbits should be lower

**Comment by agjevik999** [comment]
Yes thatcwas my point. The distribution seems a bit off

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
