### ISSUE TITLE
Fei'Yin shadow NMs - Incorrect spawning

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#1658]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window

### Details

ver 30190328_2

This is a bit like #1506 , however there's a little more than what that issue talks about regarding the Shadow NMs in Fei'Yin. In each room, the WAR shadows respawn every 5 minutes. The rest of the shadows respawn in 16 minutes as they should. The base DSP lua (https://github.com/DarkstarProject/darkstar/blob/ffcda6bd2b04107a62005f6ca10b7040fc53ec09/scripts/zones/FeiYin/IDs.lua) has a couple incorrect npc IDs in it.

North shadow has PH of 17613099 which is correct but the PH respawns every 5 minutes since it's a WAR type PH (should be 16)
Eastern has PH of 17613108 which is the THF and it's supposed to have a RNG placeholder. 17613109 is the RNG
Western I believe has already been fixed per #1628 
Southern is correct with a PH of 17613118 which is the BLM

**Comment by godmode** [comment]
Thanks for your report but 17613108 is a RNG

**Comment by Mozzy4Ever** [comment]
> Thanks for your report but 17613108 is a RNG

Got back to camping Eastern Shadow as of late. 17613108 should not be a range. It should be a THF. THF Specters have sword/shield. WAR have sword/pickaxe. RNG have just a sword, BLM have great sword. 17613108 has a sword/shield. Can also confirm that yes, he acts as a RNG and Eastern Shadow pops off of him. Neither of those should happen.

**Comment by Mozzy4Ever** [comment]
Also the WAR specters (17613092, 17613099, 17613117, and 17613106 at least) are still on 5 minute repops

**Comment by MalteseFalcon** [comment]
The NM's also have incorrect respawn timer, currently they are lottery after 10hrs. Should be lottery between 16-32 hours. Additionally the timer does not persist through maintenance which it probably should considering respawn timer.

https://ffxiclopedia.fandom.com/wiki/Eastern_Shadow?oldid=374974

Lottery Spawn from the Specter (Ranger) in the small room at G-6 - G-7 approximately every 16-32 hours.

**Comment by Arckaina** [comment]
I didn't want to make a new issue for this specifically since this bug is somewhat related but not entirely. If I should let me know. The warrior mobs (shield and pick axe) and the mobs with the single long sword and nothing in their other hand (which I guess is the ranger but it doesn't use a ranged attack) now seem to have double and triple attack.  I know the damage and accuracy calculations were just changed for all mobs, but they used to not have this ability and now they do. So I'm thinking it's a bug of some kind, as I've not seen any mention in the patch notes of adding this skill to them.

**Comment by 59blargedy** [comment]
@Arckaina 
https://discordapp.com/channels/482610771126386688/670735434799644690/783430962905481226
■ Job traits on mobs will now be properly reapplied when they respawn. 
the bug was these mobs _not_ having their proper job traits, and was resolved.

**Comment by 59blargedy** [comment]
fully resolved last patch
