### ISSUE TITLE
Golden-Tongued Culberry spells not interrupting

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#166]
http://ffxiclopedia.wikia.com/wiki/Golden-Tongued_Culberry

His spells are supposed to be interrupted when hate changes (i.e. provoke) but that is not functioning correctly. He works fine otherwise.

**Comment by VerrenGunnar** [comment]
not sure if i should leave this here or make a new issue, but he also doesn't move to get his targets in range for spells, he just stands there the whole fight,
the wiki page talks a lot about kiting strats & the Image on the wiki even shows him at the bottom of the stairs

**Comment by 59blargedy** [comment]
resolved in June 28th, 2021 update
