### ISSUE TITLE
Unobtainable conquest item despite meeting requirements

### ISSUE THREAD

**Issue by Giddean** [EdenServer/community#1660]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0
Rank 6- Royal Knight Equipment. Text log states my rank is not high enough to purchase despite having rank 6. This was at an unfilled rank bar. Also occurred with a full rank bar after trading crystals. I also have the required conquest points

See attached screenshot
![conquestitembug](https://user-images.githubusercontent.com/50757448/57962466-dc92de00-78e4-11e9-917e-ddd3e7f882c3.png)

**Comment by MGramolini** [comment]
This is likely due to Sandy not being in first. Please double check the conquest rank required.

**Comment by xizeta** [comment]
Related to https://github.com/EdenServer/community/issues/1315

**Comment by Treble011** [comment]
This can only be obtained when Sandy is in 1st place. Working correctly, devs should disregard this report.

**Comment by xizeta** [comment]
The conditions in this case are currently correct but the dialogue issue will be addressed. Thanks for your report!
