### ISSUE TITLE
Auction House Allowed More than Max Items Posted

### ISSUE THREAD

**Issue by gallanon** [EdenServer/community#1663]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details
Version:  30181205_0

I forgot about the AH limit when I first restarted and posted more than the max number allowed (which the game let me do without issue). Then when I checked my sales status some of the items I posted didn't show up. Stopping sale of existing items and then closing out and rechecking sales status caused the missing items to reappear on the list.

**Comment by bkesecker** [comment]
This is intended behavior.  There is no limit, however, the client will act like there is.
