### ISSUE TITLE
Text linked to Banishing gates doesn't appear when the gates are open

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1668]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Upon standing on all four switches generally an event occurs which causes the gate to open, which also starts a parallel counter which decreases. When the counter reaches zero the event to close the gate occurs. 

There needs to be two lines of code for each banishing gate that outputs a message to the area that the banishing gates are Open ( 4x switch pressed == True ) and Closed ( Gate counter == 0 )

Currently you don't know whether the gate is open or closed if you aren't closely communicating with people trying to open them.

V.30181205_0

**Comment by beauxq** [comment]
I think it might be that a message is given only to one person.
The messages should be given to everyone in the entire zone.
