### ISSUE TITLE
Yagudo High Priest x3

### ISSUE THREAD

**Issue by Dydexius** [EdenServer/community#1671]
### Checklist

-Version 30181205_0
There are no repeatable steps neccessarilly when I was doing my LB3 Quest Whence Blows the Wind I was going to the Yagudo crest and when i was in the big area with the ??? for it there were not 1 but 3 of the Yagudo High Priest NMs up for some reason.

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

**Comment by godmode** [comment]
There are only 2 possible in the game. It's possible one from the top was kited down and it got stuck.
