### ISSUE TITLE
Exit the Gambler not awarding 2000 exp

### ISSUE THREAD

**Issue by gallanon** [EdenServer/community#1673]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details
Completed Exit the Gambler Quest in Sandy.  I received a message saying that the map of King Ranperre's Tomb was received by I did not receive any exp for completion. As I recall there is not supposed to be a message letting you know that you receive the exp, but I checked my exp before and after and it is unchanged.

**Comment by roclm** [comment]
The experience points reward isn't era. When Square Enix updated it so you could buy every map from vendors, an experience points reward was added to all the old map quests in case you had bought it and couldn't receive a second map.

**Comment by bkesecker** [comment]
@roclm is correct.
