### ISSUE TITLE
Revenant at K-12 in Sanctuary of Zi'Tah not despawning during the day.

### ISSUE THREAD

**Issue by Dydexius** [EdenServer/community#1676]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by beauxq** [comment]
Note that Sanctuary of Zi'Tah should not have normal night time hours, and different sources give different hours.
(some pages on ffxiclopedia say 16:00 to 7:00 and others say 17:00 to 7:00)

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
