### ISSUE TITLE
Energetic Eruca Damage Scaling

### ISSUE THREAD

**Issue by inaringo** [EdenServer/community#1677]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

Energetic Eruca did 4250 damage with its breath attack against level 73 paladin. Seems off.

**Comment by 59blargedy** [comment]
a damage cap for incinerate was put in place in 2020, so this no longer occurs
