### ISSUE TITLE
San d'Oria Mission: Save the Children

### ISSUE THREAD

**Issue by zuzupetals** [EdenServer/community#1678]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by zuzupetals** [comment]
the mission is now repeatable, however, every time it is completed you rank points are reset. Additionally, each acceptance requires visiting the cathedral npc before being able to access the battleground. Plus (not sure if this is intended or not) completing the mission grants 1k gil every time.

**Comment by InoUno** [comment]
Resolved in December 1st 2020 patch.
