### ISSUE TITLE
Maat Double Attacking

### ISSUE THREAD

**Issue by Ryuu-Zetsu** [EdenServer/community#168]
Just tried maat, he currently double attacks on every round (At least against RDM). Seems to crit with both hands when he crits as well. Took nearly 600 dmg from one round.

Edit: Just did maat on SAM, no double attacking. Fight went exactly as expected from watching old videos of the fight.

Edit2: Just beat maat as elvaan RDM. 57+26 int. Capped Elemental Magic. Aero 3 damge on windsday with Auster's Staff are as follows: 139, 278, 34, 75, 139, 305, 305, 139, 278. This was my first RDM maat, but it seems to me given those stats his resist rates are extremely high.

**Comment by GRiMiNSANiTY** [comment]
This was my Maat attempt on RDM. I'm not at all too familiar with how the fight is supposed to go in terms of retail, but it was a very difficult fight. Below is a clip I recorded on twitch of the fight (I forgot to record sound). https://www.twitch.tv/videos/322877020 (The fight starts around 3:00~)

**Comment by jmcmorris** [comment]
Super impressive fight @GRiMiNSANiTY. Congrats on the win!

**Comment by godmode** [comment]
Please comment if he continues to do this after today's mini update. Jasson fixed many double attacking issues today.
