### ISSUE TITLE
Fishing Bite Rate

### ISSUE THREAD

**Issue by Riphook** [EdenServer/community#1680]
Fishing bite rate needs to be addressed.

The more valuable a fish is to NPC, the lower the bite rate it has.

Lu Shang rod needs to have the hidden effect removed but make it so it can't break on a fish within its level range or below, unless it's legendary. Legendary can always break Lu Shang, only Ebisu is unbreakable.

Fishing Pools need to be introduced and fish rarity needs to be adjusted to reflect proper bite rates. The reduced bite rates that we have now were a temporary fix until fishing pools were introduced.

Hards numbers/stats were given to Godmode.

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by Blex64** [comment]
FIshing bite rate is still horribly nerfed for black sole in particular. This "temporary fix" has now been in place for over 3 months.
