### ISSUE TITLE
Elementals not spawning on boats to Selbina/Mhaura

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1683]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Elementals don't appear to be spawning during Water or Thunder weather on the boats to Mhaura and Selbina. Perhaps it has something to do with pirates not showing up? Unsure.

Was on water weather for the full trip from Mhaura to Selbina and saw no elementals.

Version 30181205_0

**Comment by Raphtalia1** [comment]
can confirm no elementals, was on ship for about 7 hours today, no pirates either

**Comment by archfiendrubicante** [comment]
This also seems to be occurring on the Open Sea route to Al zahbi. No enemies ever spawn on that boat period.

**Comment by Setz0r** [comment]
the enemies on boats are scripted spawns, so the elementals aren't setup yet.  
right now the only boats with monsters are the ship to selbina/mhaura (regular and pirates) and fishable mobs in phanauet channel.

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
