### ISSUE TITLE
Rolanberries not for sale in Windurst Cooking Guild

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1684]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
https://ffxiclopedia.fandom.com/wiki/Rolanberry?oldid=382407

In era, historically Rolanberries were sold by Kopopo and Chomo in the windurst cooking guild. In retail it was removed from those two NPCs and moved to only be sold at the M&P market in Upper Jeuno and the Duty free store in Port Jeuno.

**Comment by bkesecker** [comment]
Both Chomo nor Kopopo stock Rolanberry.

```sql
SELECT * FROM dspdb.guild_shops WHERE (guildid = 530 OR guildid = 5302) and (itemid = 619 OR itemid = 4365); -- (Kopopo, Chomo Jinjahl) (Popoto, Rolanberry)
```
