### ISSUE TITLE
Sandy 3-1 Cant talk to the Prince for CS

### ISSUE THREAD

**Issue by xxxArchangelxxx** [EdenServer/community#1685]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by xxxArchangelxxx** [comment]
I have finished 2-3 got my rep up and started 3-1. I went to davoi and no NPC would give me the quest item. I realized that you had to talk to the Prince and get a CS. No matter how many times I zone the gaurd will not let me in the room. I have clicked on him and the door and nothing. With out that CS I cant progress to Davoi and get the Key items from the NPCs.

**Comment by bkesecker** [comment]
If you haven't already, please call a GM in-game.  They will be able to help fix.
