### ISSUE TITLE
TH not applying due to being out of range

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#1686]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30190328_2

I've heard rumors about whether TH is applied to a mob if the THF who applied it is outside of 28'. Looking at IsWithinEnmityRange and GetHighestTH in enmity_container.cpp, it does seem like this is accurate where if you applied the highest TH and you're outside 25' for non-NMs or 28' for NMs when the mob dies, your TH isn't applied to the drop table. This doesn't make sense to me as in retail it's been tested and shown to be based on enmity list (so long as you're on it with TH, mob has TH) and can be further confirmed by comments by SE (https://ffxiclopedia.fandom.com/wiki/Fan_Festival_2007_Live_Blog#Q.26A). 

Testing:

 I setup a private server using base DSP and un-commented line 779 (ShowDebug(CL_CYAN"DropID: %u dropping with TH Level: %u\n" CL_RESET, m_DropID, m_THLvl);) in mobentity.cpp so I would know the TH of the mob when it dies. I tested on worms since they can't move, and so long as I was within 25' of a non-NM, it had TH1 (was doing as RDM/THF so I could DoT and move away for it to die). If I moved outside of 25', it would have TH0. For NMs it was the same, but a distance of 28'. 

Fix:

On line 441 of enmity_container.cpp, remove the IsWithinEnmityRange(PEntity) check. Doing this resulted in no TH change based on distance during my testing, and had no adverse affects that I saw. 

I'm told by Teo that the distance check was due to myths at the time which have been disproved

**Comment by xizeta** [comment]
Thank you for your very detailed report. I've also confirmed this issue through testing and it will be addressed.
