### ISSUE TITLE
Culinarians' Guild NPC missing items in shop

### ISSUE THREAD

**Issue by him911** [EdenServer/community#1688]
### Checklist

- [yes] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
The npc(Chomo Jinjahl) at the cooking guild is not selling certain item that it should have in stock.
Ie: Kazham pineapple and popoto

**Comment by Volkaru** [comment]
Please try checking again the next game or RL day. The stock of them might have been bought up already. 
If they continue to not show up, then it is an issue. 
This Oct 2007 wiki entry shows that she is supposed to restock both.
https://ffxiclopedia.fandom.com/wiki/Chomo_Jinjahl?oldid=366181

**Comment by bkesecker** [comment]
Popoto is not part of Chomo Jinjahl's stock, but Kazham Pineapple are.
Reference to old ID: https://ffxiclopedia.fandom.com/wiki/Chomo_Jinjahl?oldid=366181
Can search DSP SQL with
```sql
SELECT * FROM dspdb.guild_shops WHERE guildid = 5302 and (itemid = 4432 OR itemid = 619); -- Chomo Jinjahl
```

**Comment by bkesecker** [comment]
@him911 To resolve the filed issue, Popoto can be added.  However, going through and making sure all the items are in Chomo's era list will take a bit longer to get implemented.  There are three options, 1) add popoto and close this issue, 2) add popoto and leave this issue open for the remaining audit, or 3) wait until a full audit can be performed.  Do you have a preference?

**Comment by bkesecker** [comment]
Related: https://github.com/EdenServer/community/issues/1684
