### ISSUE TITLE
Angel's Earring Desynth

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#1689]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30190328_2

Angel's Earring doesn't have a desynth. Per https://www.bg-wiki.com/bg/Angel%27s_Earring it's supposed to be:

Goldsmithing 85
 NQ: Angelstone
HQ1: Angelstone
HQ2: Platinum Ingot
HQ3: Platinum Ingot x2

I simply ran

 INSERT INTO `synth_recipes` VALUES (XXXXX,0,0,0,0,0,0,85,0,0,0,4100,4242,13357,0,0,0,0,0,0,0,813,813,746,746,1,1,1,2); -- Angel's Earring (desynth)

 where XXXXX is the last entry in synth_recipes cause idk shit about coding let alone SQL queries/commands/whatever so I dunno how to query the last entry in the table for a field (in this case, ID), add 1, then enter a row with that increased field. 

4100 = NQ Lightning Crystal
4242 = HQ Crystal
13357 = Angel's Earring
813 = Angelstone
746 = Platinum Ingot

**Comment by MGramolini** [comment]
You can probably just skip the value, depending if the table is using auto Id for its key (auto increment).

If not I think the query you are looking for is SELECT MAX(ID) FROM synth_recipes

**Comment by MGramolini** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/sql/synth_recipes.sql#L27

It is auto increment so you can skip the column in your query, unless you need to make a join on that ID and want to make sure it’s definitely that value.

**Comment by Mozzy4Ever** [comment]
![image](https://user-images.githubusercontent.com/11255886/67518258-05748780-f66a-11e9-866e-4d945390217d.png)

Pasting for future reference so I can link this to those who are reporting missing synths
