### ISSUE TITLE
Porter Moogle has AF and can't retrieve

### ISSUE THREAD

**Issue by RhysonEden** [EdenServer/community#1690]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

I'm on version 30181205_0 and have attempted to address this issue via discord (albeit it's been awhile since I was on and have worried about this issue). I have a slip from the porter moogle since before Eden became Eden and have several AF items I cannot retrieve as the porter moogle is no longer in game, nor can I redo the quests. I'm not sure what reproducable steps I can provide other than going to Bastok Markets and not seeing the moogle, but showing the slip in my inventory.

**Comment by godmode** [comment]
I need more details to be able to check into this. Please provide as much information that you can. The most important being your character name.

**Comment by RhysonEden** [comment]
Rhys.

There's not a whole lot more information I can provide. Porter Moogle was removed for being OOE, however my red mage gear was in storage with him.

**Comment by Serephim** [comment]
I also have AF gear in Porter Moogle storage too that I can no longer access too on Serephim.

**Comment by godmode** [comment]
All of these slips have been deleted and AF returned via delivery-box. The data was stored on the slip so if the slip was tossed there is no record of what was stored.

**Comment by Serephim** [comment]
I still have my gallant claim slip for my PLD AF and didn't get mine back. I don't know if you meant you were doing it now, or next patch. Thought I would let you know.

**Comment by godmode** [comment]
This was using the Porter Moogle. If there was another form of storage I’m not aware of it and it wasn’t fixed on this ticket

**Comment by Serephim** [comment]
Yeah this is for the porter moogle right? I stored my Paladin Artifact armor. This is the claim slip for it I still have.
![Serephim_2019 07 14_110246](https://user-images.githubusercontent.com/43891789/61185418-5b776f00-a627-11e9-8dbb-ef61f65aa9dd.png)
