### ISSUE TITLE
Enemy TP moves taking away 0 shadows??

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1692]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

https://gyazo.com/b277367a4b3498a4f96ce1daf8183efd

When being hit by enemy TP moves, I'll do a successful evasion, and the game will display "0 shadows being removed", but the TP move still takes off shadows.

v30181205_0

**Comment by Volkaru** [comment]
It's just a text bug.

**Comment by godmode** [comment]
When did this begin?

**Comment by Volkaru** [comment]
Seems to have started after last patch. Probably a side effect of the bug of Utsusemi Shadows taking 1HP getting fixed. Issue #1607 . There also seems to still be an issue with Ranged attacks still taking 1HP; Mentioned in #1670

**Comment by godmode** [comment]
Cool I think we’ll be able to figure it out

**Comment by godmode** [comment]
For whoever picks up this ticket and #1670 the time consuming solution would be to edit all the mobskill files after updating the return value of `utils.takeShadows` and adding a shadows return value along side the dmg return value of `MobFinalAdjustments` but I think there is a smoother way once we do some refactoring.
