### ISSUE TITLE
Rapid Shot Not Working Properly

### ISSUE THREAD

**Issue by Caelic** [EdenServer/community#1693]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.) // this has been posted and is closed but the issue is still occurring right now
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window) // this is a server-sided issue. client ver is 30190305_0 anyway

### Details

1) use ranged attack until rapid shot activates
2) the ranged attack animation will fire off quicker
3) you must still need to wait the same amount of time to pull out your ranged weapon as if you had just fired a normal ranged attack without rapid shot

Functional behavior should be that you are able to fire again immediately after the animation finishes of your character putting the bow/xbow/gun away. As it is right now, if you proc rapid shot, you have to wait a short period of time after the animation finishes and it seems like the delay is the exact same as if you had just fired a normal ranged attack that wasn't enhanced with rapid shot. As of right now, this job trait is nearly useless because it's not increasing the RNG's damage output at all.

**Comment by Serephim** [comment]
Ah crap and I just dropped max merits on this. :(

**Comment by Caelic** [comment]
RIP

**Comment by Caelic** [comment]
I'm nearly certain this has to do with an issue with ranged attacks overall where, ever since the ranged attack update to fix ammo delay, the server is adding the ammo's delay to the time needed to wait BETWEEN shots instead of adding the delay to HOW LONG the bow/xbow/gun is in its aiming animation. So it's an issue in general with ranged attacks. It's just accentuated with Rapid Shot because Rapid Shot speeds up the animation but doesn't touch that added between-shots delay.

**Comment by ElectroNicMan83** [comment]
I confirm it doesnt like to be working, I dumped 5 merit on it too and made no difference. :\

**Comment by Caelic** [comment]
holy crap you guys did it

THANK YOU!!!!!!!!!!!!!!!
