### ISSUE TITLE
Chocobo Digging Not Working

### ISSUE THREAD

**Issue by gallanon** [EdenServer/community#1695]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Client Version:  30181205_0

Went through four full stacks of gysahl greens without a single item (0/48). Should not have been at digging fatigue because (1) it was about an hour past JP midnight and (2) I didn't dig to fatigue the day before, only about 15 items. This occurred in both east and west ronfaure and using /sea allows me to be confident that the zone was not already dug out because for a large period of time there was no one high enough level to ride a chocobo in east ronfaure. So maybe the zones are not correctly populating digable items? I've dug in the past without issue.

**Comment by gallanon** [comment]
Update: Tried again about 2 hour later. Did some of the same zones and some new ones. Still can't pull up anything.

**Comment by GalkaZajin** [comment]
I'm no digging expert but I know you cant dig anything up during certain moon phases, something like 40-60%.

**Comment by gallanon** [comment]
> I'm no digging expert but I know you cant dig anything up during certain moon phases, something like 40-60%.

45-60 % isn't great for digging but won't drop you down to 0% success. Didn't think to check the moon phase though to be honest.

**Comment by GalkaZajin** [comment]
Maybe for retail you wouldn't hit 0% but it seems like it is coded to 0% here.

**Comment by gallanon** [comment]
Oh that is very good to know. Thanks.

**Comment by bkesecker** [comment]
https://www.edenxi.com/forums/viewtopic.php?f=3&t=1560&p=6611&hilit=dig#p6611

**Comment by godmode** [comment]
Seems to be working as intended here. Please update the post if you have additional information to add.
