### ISSUE TITLE
Snarl

### ISSUE THREAD

**Issue by truewatts** [EdenServer/community#1697]
### Checklist

- [o] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ o] I have provided my client version in the details. (type /ver into your game window)

### Details
Beastmaster ability snarl is missing. I cannot reproduce those steps as I do not have control over that. It was added Nov 20, 2007. I found the info on the update history on the retail ver. 
http://www.playonline.com/pcd/update/ff11us/20071120wwnX41/detail.html

**Comment by greyenvy** [comment]
This was the pre-wotg patch so it is borderline for Eden.  Based in the other notes in this patch I would judge this out of era pretty firmly.

As much as I’d like to see Snarl I think it was removed for this reason.

**Comment by bkesecker** [comment]
https://github.com/EdenServer/community/issues/380

**Comment by truewatts** [comment]
> 
> 
> This was the pre-wotg patch so it is borderline for Eden. Based in the other notes in this patch I would judge this out of era pretty firmly.
> 
> As much as I’d like to see Snarl I think it was removed for this reason.

I thought this was a 2007 era server? Was that only meant for the beginning of 2007?

**Comment by greyenvy** [comment]
That’s a good question.  There is a “cut-off date” I’ve seen floated but it’s pretty clear it’s not adhered to 100%.

**Comment by chlorr** [comment]
ill take crab sushi over snarl any day

**Comment by truewatts** [comment]
> 
> 
> ill take crab sushi over snarl any day

Use carp sushi. Its cheaper and just as good if all you need is acc.

**Comment by godmode** [comment]
November 20th is the WoTG date--our cutoff for content other than a few exceptions like Mythic Weapons in the future.
