### ISSUE TITLE
Got a strange Error when desynthing death earrings. 

### ISSUE THREAD

**Issue by Cheezcakee** [EdenServer/community#170]
I desynthed 12 death earrings but only got 11 platinum ingots back and saw this strange error. 
Maybe that's what happens when you HQ the desynth to get a death stone. Either way, would be nice to get either the ingot back or the deathstone. <3

![speedy_2018 10 15_172221](https://user-images.githubusercontent.com/43824969/46979428-99973080-d09f-11e8-99b8-68a73cb64b80.png)

**Comment by icariumkupo** [comment]
Or could be you failed the synth, therefore not receiving the ingot, and the message displayed incorrectly. :)

**Comment by Wiggo32** [comment]
this means you desynthed it into a deathstone in a tier that wasn't officially added to the database, so since it couldn't find the db entry it did not supply you with the stone but instead gave you that 0 message. This is fixed now though and awaiting official merge.

**Comment by godmode** [comment]
Cheeze please remind me to give you a deathstone after maintainence tonight. Closing this issue.
