### ISSUE TITLE
Ranged attack counts as magic damage

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#1700]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

A gigas just killed me with Catapult while my Perfect Dodge was active.

**Comment by Aneyus** [comment]
Ranged attacks are in fact supposed to hit through perfect dodge. This is not an issue

Ability description, ingame: Allows you to dodge all melee attacks.

From the wiki https://ffxiclopedia.fandom.com/wiki/Perfect_Dodge
"However, this ability cannot dodge ranged attacks or magic."

**Comment by Balrahn** [comment]
my bad
