### ISSUE TITLE
No HQ GP crafter rings OOE

### ISSUE THREAD

**Issue by marlinla** [EdenServer/community#1701]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver 30181205_0

There's a cycle of OOE rings for each craft with the same property.

Alchemist's Ring
Bonecrafter's Ring
Carpenter's Ring
Chef's Ring
Goldsmith's Ring
Smith's Ring
Tailor's Ring
Tanner's Ring

https://ffxiclopedia.fandom.com/wiki
/Goldsmith%27s_Ring?action=history

**Comment by FariskaEden** [comment]
I believe these rings have already been removed and trying to purchase them does not work anymore either.

**Comment by marlinla** [comment]
I've seen the smithing one equiped in game as of this morning May 26, 2019.

**Comment by godmode** [comment]
The remaining rings will be removed July 22nd.
