### ISSUE TITLE
Shigeto Bow +1 not giving samurai RACC+8

### ISSUE THREAD

**Issue by beerking27** [EdenServer/community#1702]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Equipping the Shigeto Bow +1 as a 75sam/rng does not give me the +8 ranged accuracy boost according to /checkparam. It does give the correct Ranged attack boost of +16 however. I will check with an nq and update but I assume it is the same.

Version: 30181205_0

**Comment by xizeta** [comment]
Checking NQ will not be necessary, as this issue is being addressed. Thanks for your report!
