### ISSUE TITLE
Crescent Fish - Breaking Halcyon / Hume Rods

### ISSUE THREAD

**Issue by freddiepines** [EdenServer/community#1704]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

Client version 30181205_0

Crescent fish is currently breaking rods it shouldn't, namely Halcyon and Hume.  Per Great-Blue this fish should be snapping the lines, but not the rods:

![image](https://user-images.githubusercontent.com/50085658/58393758-1e6f0300-800e-11e9-82fa-921fe72d177d.png)

Easily reproducible by fishing with the rods for awhile.

Thanks.

**Comment by tacbox3** [comment]
This is intended behavior under setzor's fishing system. Any "bad feeling" message always has a small chance to break the rod and a higher chance to snap the line.
