### ISSUE TITLE
Promyvion Vahzl Teleports

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#1705]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version_30181205_0

Quote from FFXI-Wiki from Oct, 1st 2007:
"Each time you get the cutscene, you’re given the option to warp to that Memory Flux from the gate in Pso'Xja. So, after you beat a Memory Flux, you can resume there later without starting over."
https://ffxiclopedia.fandom.com/wiki/Desires_of_Emptiness?oldid=354731

This doesn't work currently, we climbed as 7 ppl and ment to do the BCNM twice, after first clear we tried to be teleportet back to Floor#5, but the gate didn't give that option. Obviously we did said NMs/prereq.

**Comment by godmode** [comment]
I believe there is an open issue for this. Can you try searching for it and if it exists close this one? If not leave it open.

**Comment by panfunk** [comment]
You're right, didn't see that one
