### ISSUE TITLE
Memory Receptacle audit

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#1706]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version_30181205_0

Memory Receptacle seems terribly overtuned and I'd request an audit on their difficulty. 
In Vahzl I think we fought the Floor4 MR's with 7 ppl for a longer period than the final BCNM with 6ppl.

Also some 'Stray''s had different models, plus seemed way stronger than their true model counterparts.

**Comment by Satirof** [comment]
Adding to this as we encountered problems with Promyvion-Vahzl's Floor 4 MR Strays.

I believe the models are correct, however the HP on the weeper/seether model strays does seem absurdly high. I looked for videos online but could not find anything for Vahzl climb other than current retail era (where they just get 1shot at uncap)

However the bug we encountered was the sheer amount of Strays. After clearing the surrounding strays, we engaged the boss. The boss starts spitting out adds every so often as usual. However after a few minutes the original strays start repopping under the MR in addition to the normal ones it spawns while engaged. Which feels like a bug as I never recall experiencing this in retail. However am again unable to find an era accurate video of this :/

Thinking easiest fix would be making Strays be on a 16min respawn, except for those that are supposed to spawn when the boss is engaged?

Steps:
1: Proceed through Promyvion-Vahzl to Floor 4
2: Kill Floor 4 Boss (Solicitor)
3: Proceed to MR to attempt to reach floor 5
4: Kill all strays
5: Attack MR
6: Have low enough DPS that ~3-5 minutes can pass
7: Be completely flooded by huge amounts of strays spawning in short periods of time.
8: Die.

**Comment by roriffxi** [comment]
Experienced this issue as well.  The strays around the MRs on floor4 are repopping after 5 minutes, leading to a flood of strays overwhelming you at that point.

**Comment by KnowOne134** [comment]
many strays at floor 3 and higher have wrong mob groups set ids include: 
16867506
16867520
16867513
16867602
to name a few to look into

**Comment by KnowOne134** [comment]
seems to be correct for weeper and seether type mobs to be at MRs at 3rd floor up

**Comment by bkesecker** [comment]
Linking so that this doesn't get lost: https://youtu.be/AcqWgkl2x-M?t=77

**Comment by roriffxi** [comment]
The video that bksecker posted is for the 'Pulling the Plug' ENM and isnt actually related to this bug, since this bug is specifically talking about the MRs used for advancing floors , specifically during the CoP 5-2 Promyvion - Vahzl mission

**Comment by KnowOne134** [comment]
Corrected on 7/5/2024
