### ISSUE TITLE
Swift Belt NM resetting everyone's fomor hate after each kill.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#1708]
### Checklist

- [/ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ /] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ /] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0

The swift belt NMs are resetting everyone in the alliances fomor hate after each kill.
I checked my hate before we popped the Galka NM, killed it, went to the hume NM and all of our hate was reset to zero. This should not happen, only the person who pops it should be set to zero.
This is a MASSIVE issue as it takes hours and hours of work to raise your hate up to maximum and it screws an entire alliance of people.

**Comment by EliannaEden** [comment]
We haven't experienced this issue, but we have had an issue where hate gets locked at a certain level. I've been on LV3 hate for 100's of Fomor kills and it will not go any higher. I have never been able to pop the NM. A Hume in our LS has the same issue. 

The only race we've been able to pop it repeatedly on is Galka.

**Comment by Serephim** [comment]
I haven't had any issues getting to max hate on hume or mithra. But I helped a friend kill it today, and it reset my hate back to zero. :(

**Comment by panfunk** [comment]
https://github.com/EdenServer/community/issues/1316#issue-421943098

**Comment by Jimmayus** [comment]
Right pan but that doesn't change the problem where we can't gain hate at all

**Comment by panfunk** [comment]
Right, but I linked that bug report cuz the 'not gaining hate' issue isnt new

**Comment by Jimmayus** [comment]
Oh I see, right I misinterpreted.

**Comment by Serephim** [comment]
Well, even if you can get hate its no good if everyones is wiped every kill. :(

**Comment by tacbox3** [comment]
I really hope these bugs are given priority sometime soon. As it stands it's impossible to set up Swift Belt "runs"... In which case what's the point of having it in?

**Comment by GalkaZajin** [comment]
Is this a very recent bug? I have killed probably 40 of the NMs over the last month or so and haven’t had this happen to any of us.

**Comment by panfunk** [comment]
must be recent, I haven't had this issue either

**Comment by tacbox3** [comment]
Not recent at all. Check out the date on 1316

**Comment by GalkaZajin** [comment]
That’s a different issue of building hate, not everyone losing hate when 1 person pops

**Comment by Slamm21** [comment]
I believe the building hate issue is related to the fact that right now hate is bugged and you only get hate if your character kills the fomor itself.
As for it resetting whole alliance hate, would a temporary solution, for now, be to pop the NM outside of the party and then rejoin?

**Comment by Slamm21** [comment]
Can confirm, we have been dropping party while popping so only the one who pops nm loses hate. Just have invite ready and accept straight after you trade.

**Comment by godmode** [comment]
That’s a smart workaround for now until we can fix it.

**Comment by Slamm21** [comment]
In regards to building hate, can confirm only if you land the kill you get hate right now. On retail, you just had to be in the alliance. Also, any Tauri/Orcs/Warmachines/Gigas with the finishing blow by your character reduce the hate significantly.

Side note, the drop rate on these seems way too low, a few people have told me they are around 0/10. we are 1/13 (1/10 on hume and 0/3 on Mithra) always with TH2, on retail with TH2 drop rate was roughly 50%. I know it is a very small sample size but still seems way off.

**Comment by GalkaZajin** [comment]
Rates seem fine to me, we are about 12/35ish? Cant say I have kept track but went 4/6 on our last run

**Comment by Slamm21** [comment]
we just went 1/1 on taru so maybe just the hume?

**Comment by godmode** [comment]
This does not look to be the case. However I can confirm #1316 does only give the player who killed hate.

**Comment by Serephim** [comment]
If it is not the case then how did both of my characters go from max hate before the fight to 0 hate after the fight when someone else popped the NM? :(

**Comment by godmode** [comment]
I looked frantically and couldn’t find where it would be possible in the code. I imagine it’s just how things seemed. If someone else is about to go on a run let me know and I can check hate in the database before and after the NM is popped.

**Comment by Serephim** [comment]
Okay, i'll let you know next time I go Godmode. I will max both my characters hate before the fight and see what happens.
