### ISSUE TITLE
Sozu Sarberry uses 2hr multiple times

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#1714]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

30190328_2

![Sozu](https://user-images.githubusercontent.com/11255886/58567820-b2042780-81f8-11e9-8218-7960f773a07a.png)

Sozu can use his 2hr more than once per pop. https://ffxiclopedia.fandom.com/wiki/Sozu_Sarberry?diff=526136&oldid=522380 says he won't

**Comment by KnowOne134** [comment]
could not duplicate

**Comment by danismyhero** [comment]
I have had this happen also.  It seems when it goes idle, it resets?
