### ISSUE TITLE
BLU  Magic fruit is not being enhanced 100% of the time by healing %+ effects

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#1717]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

See https://ffxiclopedia.fandom.com/wiki/Magic_Fruit for reference

Blue Magic healing spells do not use the exact same calculation as white magic healing spells, but they do utilize healing % bonuses (light staff, etc.) the exact same way. In other words, as long as you have the staff or other source equipped you should get the % bonus healing every time. Magic Fruit is not obeying this rule, and I'm guessing the other blue magic healing spells are following a similar pattern. See the following screenshot:

![Jimmayus_2019 05 29_205331](https://user-images.githubusercontent.com/45926115/58602927-536c9700-8254-11e9-8f44-13761216ae16.png)

neutral day, same gear yielded one healing bonus at 407 and 2 lower ones.

**Comment by Tolkage** [comment]
Related to https://github.com/EdenServer/community/issues/1552 I'm sure

**Comment by 59blargedy** [comment]
i dont believe this is an issue anymore, the code utilizes cure potency regardless of spell type, and i cant see why it would skip certain casts. as i cant duplicate the intermittent lack of cure pot, closing this ticket but if anyone experiences this issue these days please let us know
