### ISSUE TITLE
Monarch Linn drops you through the floor after you disconnect.

### ISSUE THREAD

**Issue by EliannaEden** [EdenServer/community#1719]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Client Version: 30181205_0

This is a separate issue from Treble's post regarding leaving the BCNM arena in Monarch Linn and not losing your battlefield icon status. 

Upon disconnecting in the BCNM, I reconnected both of my characters to find myself under the floor of the Monarch Linn arena. The rest of my party was able to leave the BCNM and enter RivernesiteB01 to clear their battlefield status. One party member decided to click on the portal and reenter the fight and was witnessed immediately dropping through the floor and joining my two characters in my underground limbo. 

I was not able to move, target anything and was not close enough to the portal to run away from the battle. GM moved us back to the RivernesiteB01 entrance to Monarch Linn and asked me to make a report in regards to this issue.

**Comment by godmode** [comment]
This should have been resolved a couple months ago I just forgot to update the ticket. Please update if you experience the issue again.
