### ISSUE TITLE
Fafnir Resisting Paralyze and Paralyze 2. 

### ISSUE THREAD

**Issue by Cheezcakee** [EdenServer/community#172]
Fafnir Resisting Elemental Seal Paralyze 2 and paralyze. I don't think Nidhogg has this problem as treble said it was landing no problem just Fafnir. Tried with Potency maxed, and magic accuracy maxed. Elemental Seal as well. Linked is a Video of the SD guys from gilgamesh landing paralyze on him 34 seconds into the video. Mattoid Paralyzes Fafnir with no elemental seal. Again at 1:33. Also it landed fine on the first fafnir on October Second 10/2. Not sure when the change was made or what caused it since then. 

Also i was looking at our attendance screenshots
Fafnir's experience points rewarded
was 66,71,71,and 76 on 10/10, 10/11, 10/12, 10/13respectively. 

On the 14th and 15th it was 110 and 124. So maybe the change happened in between 10/13 and 10/14. Hope that helps. 

https://www.youtube.com/watch?v=8717Pp60RF0

**Comment by Serephim** [comment]
I think Elemental Seal is broken in general. Black mages are getting 50% resists on ES nukes.

**Comment by godmode** [comment]
This will be an issue until there is an magic resistance refactor unfortunately. Ice resist ties in all resistance, enfeebling and elemental.
