### ISSUE TITLE
Crafting max level gap incorrect

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#1720]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

At Level 57 Goldsmithing I attempted a Level 69 synth and got a message that the gap is too high, same at 58.
To my knowledge the maximum allowed gap is 15 levels, well known to be used for the good old 'break synth' skillups on retail.
As a reference: https://ffxiclopedia.fandom.com/wiki/Break_synth

**Comment by godmode** [comment]
Thanks for reporting, this is a far out of era range though. You can check era ranges by using the history button that pops up in a drop down menu on those pages.

**Comment by panfunk** [comment]
Eh, I'm pretty sure the 15 gap is era,
if you check the above link from 2006 it says quote:

"Woodworkers would purposefully attempt the synthesis with smithing as low as 45 and hope to save the Adaman Ingot ingredient."
Said synth is Iron-Splitter which has a cap of 60 on smithing.

**Comment by godmode** [comment]
Hmm. I will dig up some sources I found and look again.

**Comment by panfunk** [comment]
Another source stating 15 level gap:
https://ffxiclopedia.fandom.com/wiki/Goldsmithing_Guide_by_Gatsby?oldid=172277

Level 69 - 73
Shrimp Lantern
Requires Alchemy 40-45 and Smithing 26-31
Fire Crystal
Tin Ingot
Beeswax
Moblin Putty
Moblumin Sheet
This is your first possible break synth recipe. Keep one skill 15 levels below its cap and proceed to break each synth in hopes of skill. This is the pop item for the HNM Shen. So people may want to buy it from you.
