### ISSUE TITLE
Sandy Mission 2-3 BCNM no KI (Waughroon Shrine)

### ISSUE THREAD

**Issue by goose123456** [EdenServer/community#1723]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
**Version 30181205_0**

### Details
No KI (kindred crest) received after victory from BCNM 
Sandy mission 2-3 "Journey Abroad" Windy to Bastok route
https://ffxiclopedia.fandom.com/wiki/Journey_Abroad 

- All NPC talked to
- Party entered BCNM (Waughroon Shire) received CS and then left BCNM "ran away" because member forgot lvl cap gear.
- later on won with victory CS and warp to BCNM exit with no KI (kindred crest) awarded 
- checked KI on character profile with nothing and checked NPC with no further advancement.
 - did BCNM with another group to try again with no KI rewarded.

**Comment by godmode** [comment]
If you are still having an issue with this please place a GM ticket and reference ticket 1723
