### ISSUE TITLE
Verify gear swapping timing for effectiveness

### ISSUE THREAD

**Issue by Riphook** [EdenServer/community#1725]
Getting a few reports saying that gear swap macros don't appear to be having effect when changed midcast when the spell should check gear as the spell goes off and not when casted. Can spell formula's just be double checked?

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by EliannaEden** [comment]
Can't you check this ingame and confirm or deny it yourself, and then make a bug report?

**Comment by Riphook** [comment]
I'm sorry who are you? I placed a bug report because there was a player report and as a GM I don't take the time to test every bug report submitted as a GM ticket but instead place a report for a dev to investigate.

**Comment by Tacoxtuesday** [comment]
I just did some very minimal testing with ashitacast and equipviewer. The gear changes just after the spells starts to cast, and gear bonuses were taking effect. I would say that it works fine, and may take a few milliseconds for the gear swap to visually update.

**Comment by Tacoxtuesday** [comment]
Perhaps next time have the player with the issue submit a bug report so that they can explain what's going on.

**Comment by Riphook** [comment]
Yes I understand the stats update but the player report is wondering if the formula for spellcasting takes your stats before the cast or properly at the time it goes off because they believe it is wrong and taking it when the spell starts casting.

**Comment by Riphook** [comment]
Ok why am I being attacked and told what to do here...a player submitted a report...you know how many will submit a bug report on github? Most don't want to create a github account just to submit a paragraph of information....players barely submit a 5 word explanation of why they're placing a GM ticket...go easy guys...

**Comment by bkesecker** [comment]
This is not a forum, please take the discussion there.

**Comment by Slamm21** [comment]
Only thing I have noticed with ashitacast when switching from royal cloak to af body and hat on short spells, sometimes it equips hat and no body, or body and no hat. As far as I know, this could be just the animation and it actually equips both but it is so quick I have not been able to open the equipment menu fast enough.

**Comment by godmode** [comment]
This appears to be working correctly.
