### ISSUE TITLE
DRG AF2 Drachen Brais Bug

### ISSUE THREAD

**Issue by adrienmerignac** [EdenServer/community#1727]
### Checklist

Hi i got an issue with the AF2 DRG quest.

After that i've traded Ceraulian the Gold Airpin, i've waited 1 minute like it is supposed to be.

But from now he is only spamming me the sentence on the screenshoot and i'm not having the next cutscene to go forward on the quest.

Please let me know what is going on and if it's definitly a bug.

The version of my client is 30181205_0.

![Ysatsu_2019 06 01_190012](https://user-images.githubusercontent.com/30231135/58751522-d3d30800-849f-11e9-86bb-b27c82613c04.png)

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by burkewitz** [comment]
Pretty sure I had to wait one game day

**Comment by adrienmerignac** [comment]
This is what is written also on wikia..

![DRG_AF2](https://user-images.githubusercontent.com/30231135/58751667-98393d80-84a1-11e9-833b-5cc63083fd72.png)

**Comment by burkewitz** [comment]
Yup. And check this revision from 2009
https://www.bg-wiki.com/index.php?title=Chasing_Quotas&direction=prev&oldid=392618

**Comment by adrienmerignac** [comment]
Oh must be that then.

I will try tomorrow then thanks for your help.
