### ISSUE TITLE
Missing item text during THF AF3 - Hitting the Marquisate

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1731]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://gyazo.com/91bb871aa37c3db0d14d2ecf775ca1c4

The name of the item "Chandelier coal" is missing from the final sentence of Hagain. The item text isn't there and doesn't display, it's just a period.

**Comment by xizeta** [comment]
Thanks for the report. Issues like this are a nice easy fix. Happy to have stuff like this to do!
