### ISSUE TITLE
Repop rate of coffers in Crawlers Nest.

### ISSUE THREAD

**Issue by AlfWaji** [EdenServer/community#1733]
### Checklist

- [ /] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [/ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/ ] I have provided my client version in the details. (type /ver into your game window)

### Details
30181205_0

I've encountered this bug several times.

**Comment by AlfWaji** [comment]
the coffers take too long to repop

**Comment by godmode** [comment]
Thanks for the report, however there is no data here other than they take too long to pop. Please add a comment with data. Era articles on chest repop time is good too. Closing for now because I’m pretty sure it is accurate. However if you provide extra data we can troubleshoot better.
