### ISSUE TITLE
Fomor Bat in Lufaise Meadow has very high level

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#1736]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

The Fomor Bat, a pet of Fomor Beastmaster in Lufaise Meadows at (H-8) has a very high level, higher than it's master.  I did not snag the level with the checker plugin but it seems that the level of the Fomor are correct to era value but this pet's level is not.  

ver: 30181205_0

**Comment by Slamm21** [comment]
Not just the bat, but there are also fomor elementals there around level 77

**Comment by Toritos** [comment]
mob_groups groupid 582, probably still set to level range 72-74.

**Comment by greyenvy** [comment]
The automatons in Mount Zhayolm that are pets of the Hilltroll Puppetmasters are also much higher level than wiki states they should be.  These mobs were checking in the mid-70s and wiki has them parked in the mid-60s.
