### ISSUE TITLE
Cartonnier

### ISSUE THREAD

**Issue by Deepupuu** [EdenServer/community#1738]
There's no AH listing for Cartonnier. It's suppose to be under the Furnishings section but it isn't there.

**Comment by xizeta** [comment]
Please note: The recipe currently on FFXIclopedia is not era.
The correct era recipe is:

```
Woodworking (96-97) Smithing (35)

Yield: Cartonnier
Earth Crystal

* 2 x Iron Sheet
* 3 x Mahogany Lumber
* 1 x Bloodwood Lumber
* 2 x Cassia Lumber
```
