### ISSUE TITLE
Swift Belt drop rate is way too low

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#1739]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Reproduction: Kill the NMs a bunch of times with TH2 and see how rarely it drops.

The swift belt NMs should be dropping 30-50% of the time depending on which source you wanna use.  Currently its dropping less than 10% of the time.

**Comment by Gretal1** [comment]
We went about 2/5 when we did our runs.

**Comment by Imakyl** [comment]
2/4 here with TH1

**Comment by Slamm21** [comment]
Which race though? we went 1/1 on Taru, 0/3 on Mithra and 1/11 on Hume.
all of which with TH2 have different drop rates but should hover around 50%
I also know of a Galka who is 0/13 in his attempts

**Comment by Gretal1** [comment]
1/3 Galka, 0/1 Elvaan, 1/1 taru.

**Comment by Slamm21** [comment]
very small sample size but interesting we both went 1/1 on taru.

**Comment by GalkaZajin** [comment]
Out of my group going 12/35ish, most kills were hume, elv and galka, few drops from each. Also went 1/2 on taru

**Comment by Slamm21** [comment]
we are now 3/13 on Hume, 1/2 on Taru and 0/3 on Mithra with TH2 on all kills.
so 4/18 in total

**Comment by Slamm21** [comment]
We just got our final drop, 6/24 total so 25% with TH2
4/17 Hume, 2/4 Taru and 0/3 Mithra. 
4/17 on Hume does not seem right, however, we could have just been super unlucky.

**Comment by Toritos** [comment]
Assuming Eden haven't changed the drop rates, they are set as followed:
Galka - 21%
Hume - 25%
Mithra - 32%
Elvaan - 37%
Tarutaru - 38%

**Comment by Slamm21** [comment]
then where has TH gone?
If the item does not drop TH1 gives an extra roll and if still no drop TH2 does a roll again.
Therefore Galka TH2 drop rate = 51%
Hume = 58%
Mithra = 69%
Elvaan = 75%
Tarutaru = 76%

For example, with Hume you do 1-0.25 = 0.75
Now 0.75 is cubed to represent the three rolls = 0.421875
1-0.421875 = 0.578125 which is the drop rate with TH2 on average.

**Comment by godmode** [comment]
Darkstar base uses mostly the wiki for drop rates which do not count for variance in TH or several other things. Most drop rates are modified from that.

**Comment by godmode** [comment]
The drop rate seems to be too high if anything. I'm leaving it as is.
