### ISSUE TITLE
Got stuck fishing off of Kazham Airship (docked)

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#1742]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I got stuck while fishing off of an airship loading platform. In port Jeuno, I was fishing while waiting for the Jeuno->Kazham airship. When it arrived, I was a bit greedy, and wondered if I could stand on the loading strip that connects the airship to the dock and fish there. I could, but when the airship took off, it disappeared beneath my feet and my screen never transitioned to consider me on the airship. The problem is, it didn't put me on the dock either, I could walk around on an invisible airship in the dock and could see the cabin room. I'll upload a picture that shows me standing on the water looking at the cabin. I had to use !unstuck to get out. 

Note: I was in the process of catching a fish (rusty subligar) when the airship started moving, and i continued to reel it in, if that matters.

Version: 30181205_0

**Note: I used the !unstuck command, and while I was waiting the airship came back. When it departed again, it actually took me with it, zoning me to the airship sequence etc.**

![InvisibleAirship](https://user-images.githubusercontent.com/13668758/58888102-dc505c00-86b4-11e9-9332-23d69a41ffed.PNG)

**Comment by Setz0r** [comment]
this should be a lesson in greed :P

**Comment by E5una** [comment]
> this should be a lesson in greed :P

No disagreement here :) Just wanted to report it so it didn't happen to others.

**Comment by Setz0r** [comment]
its all good, i'm planning on fixing all of the dock boundaries

**Comment by E5una** [comment]
FYI, I validated that standing on the same "welcome landing" on the airship and NOT fishing is totally fine :). I know this is probably common knowledge, just wanted to update the ticket with more info.

**Comment by Setz0r** [comment]
Fishing now gets interrupted on zoning, this issue should be resolved.
