### ISSUE TITLE
BST Pets Despawn Randomly and Get Stuck on Walls and Trees

### ISSUE THREAD

**Issue by BGFFXI** [EdenServer/community#1743]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by xizeta** [comment]
These are two separate issues:
* Pets sometimes despawn when charm wears off. This issue is already being investigated
* Mobs get stuck on terrain due to navmesh issue. This is a known issue.

Thanks for your report but I am closing as this duplicates existing issues.

**Comment by bkesecker** [comment]
For reference.
https://github.com/EdenServer/community/issues/1151
