### ISSUE TITLE
The Final Image (Bastok M7-1) doesn't require Key Item

### ISSUE THREAD

**Issue by Friesaredone** [EdenServer/community#1745]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproductive steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver.30181205_0

https://ffxiclopedia.fandom.com/wiki/The_Final_Image

The quest order should have the players in question locating a ??? > examining to spawn a pair of NMs and then locating the ??? in its new location once the enemies have been defeated. Doing so should reward each flagged player with _Reinforced Cermet_ Key Item. Currently, players receive a message letting them know nothing out of the ordinary can be found here. In retail, the players in question could not leave the zone, log out or be tractored without having to redo the NM portion of the mission. As it stands currently none of those options will allow you to pop the NMs again and the Key Item portion of the mission is skipped entirely from a visual standpoint. Returning to Cid will allow you to complete the mission as he acts as if you had the Key Item all along; this despite the fact it never appears in the log and doesn't show up as a temp KI.

I'm unable to verify if players need to check the ??? a second time to trigger the KI despite the lack of it appearing in the chat log or if players can simply kill the NMs and return to Cid. I can confirm that the ??? we had to examine was the correct one and not one associated with the WSNM spawn.

**Comment by erenik** [comment]
Indeed. After sneak-pop killing one golem and waiting for a long time and clicking the ??? the first time I got no message at all (silently obtaining the key item?), the 2nd and 3rd time around clicking the ??? "There is nothing out of the ordinary here." was displayed. I could then finish the mission with the hidden key item.

**Comment by KnowOne134** [comment]
Did this mission yesterday and did recieve the message of getting the keyitem after finding the ??? The 2nd time.

**Comment by KnowOne134** [comment]
Corrected 3/29/2021
