### ISSUE TITLE
Knight Stalker quest interfering with sandoria mission

### ISSUE THREAD

**Issue by Tolkage** [EdenServer/community#1746]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0
https://ffxiclopedia.fandom.com/wiki/Lightbringer (Guide being followed for 8-2)
https://ffxiclopedia.fandom.com/wiki/Knight_Stalker (Problem quest causing issue with NPC)

While trying to advanced through Mission 8-2 for Sandy, I ran into an issue where Rahal would not respond to my attempts to interact with him. NPC was not giving me any dialogue or options, despite being the next step in the quest after the cutscene with the king.

After talking with GM Nibbler it was determined that having the quest "Knight Stalker", which is started by Rahal, flagged was preventing me from progressing on mission 8-2. This appears to be unintended behavior.

**Comment by Tolkage** [comment]
Update:
After completing "Knight Stalker" quest, I was able to speak to Rahal and receive the Crystal dowser KI. After receiving the KI and talking to Curilla for the optional CS, I was unable to progress the mission further, as the ??? inside Uggalepih were unresponsive just as Rahal was before.

Going off of the wiki, once I receive the KI from Rahal I should be able to procee directly to Uglypie, so there is no chance I've missed a step on this one. Also, the ??? are simply hanging and unresponsive as opposed to even giving a "Nothing interesting" message.

**Comment by bkesecker** [comment]
GM explained the situation.  Unfortunately, code seems to be favoring quest progress over mission progress when speaking with Rahal and/or Curilla.  I would suggest updating the code to favor mission logic over quest.  I would further suggest that NPCs related to mission progress be audited for similar behavior.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
