### ISSUE TITLE
BST jug pets not despawning over time

### ISSUE THREAD

**Issue by beerking27** [EdenServer/community#1747]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

I noticed today while playing BST that my jug pet CourierCarrie never despawned. Wiki says this jug specifically should despawn after 30 minutes of being called out. It was up for well over 3 hours, which also allowed my beastmaster 2hr to "stack" onto this jug pet. I have not tested if this is the same for other jug pets but I can further test if necessary.

Ver is 30181205_0

**Comment by KnowOne134** [comment]
Duplicate

**Comment by KnowOne134** [comment]
Fixed with https://github.com/godmode/dsp/pull/1236
