### ISSUE TITLE
Cheupirudaux Doesn't Accept HQ Mythic Pole

### ISSUE THREAD

**Issue by CdoubleOkay** [EdenServer/community#1748]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205

Tried to turn in Mythic Pole +1 as my guild test item and the WW Master won't accept it.

**Comment by xizeta** [comment]
I noticed that none of the guilds are coded to accept HQs at any rank. You can see that they should here:
https://www.bg-wiki.com/bg/Rank-up_test
```
 All versions of the required item (NQ, HQ1, HQ2, HQ3) are accepted by the guild NPC.
```

This will need a substantial rewrite.

**Comment by xizeta** [comment]
As a I work around, I would gladly trade you my normal quality Mythic Pole for an HQ one. Send me a tell. Haha

**Comment by CdoubleOkay** [comment]
Thanks for the offer. I just crafted an NQ to turn in though
