### ISSUE TITLE
Today's cooking guild item is Irmik Helvasi.

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1749]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Today's Cooking guild recipe to turn in for the Veteran Rank is Irmik Helvasi.
Not only do you have to complete a quest that takes a full day to complete, but you also have to have the Patisserie Key Item to make the Irmik Helvasi.

This seems like an unintended recipe.. Just based on the difficulty. Is this an intended mechanism?

**Comment by archfiendrubicante** [comment]
Preface: In the In-era FFXIclopedia entry for August 17, 2007 Guild points value is listed as: None.
https://ffxiclopedia.fandom.com/wiki/Irmik_Helvasi?oldid=329006

**Comment by bkesecker** [comment]
Digging into it, the item was added to the guild item list after ToAU was released.  Getting to the quest giver can happen far before level 60 and the item needed for the quest is dropped by a mob a bit above level 60.  Item seems reasonable, but it would be interesting to know what item was replaced by it.

**Comment by archfiendrubicante** [comment]
But after you finish the quest it takes a day to get access to the recipe

**Comment by mlandrum22** [comment]
It might suck but you can still buy them in Whitegate.
