### ISSUE TITLE
San d'Oria Rank 6 Conquest Itens

### ISSUE THREAD

**Issue by Silvercap** [EdenServer/community#1750]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

When choosing the rank 6 items from the conquest NPC on San d'Oria it shows the same item(Royal Knight's bascinet) independently of choosing different items. The other lower ranks (1 to 5) seem to display the items correctly.

**Comment by xizeta** [comment]
This only seems to occur when the player doesn't have enough Conquest Points to purchase the item, so it shouldn't impact gameplay. We've located the issue and this will be resolved in the next patch.
