### ISSUE TITLE
Zone Crash

### ISSUE THREAD

**Issue by gallanon** [EdenServer/community#1751]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

Grabbed a chocobo in Lower Jeuno and the game got stuck loading into rolanberry. Ended up having to force quit and relog. When I relogged I was in the middle of Rolanberry right in front of a goblin who immediately aggroed and killed me. I get that zone crashes will happen, but is there a way to make the reset point somewhere safe--like maybe one of the zone entrances?

**Comment by godmode** [comment]
Thanks for reporting your concern. We won't move players that crash to zone entrances but we will try to fix client crash issues that are using our version--which you are.
