### ISSUE TITLE
Auction House is Bugged

### ISSUE THREAD

**Issue by PsychedelicNPC** [EdenServer/community#1752]
Hi, I went fishing for the first time. I got to skill level six. I got 5 stacks of Moat Carp and 5 stacks of crayfish. 
I sold the fish on the AH.
The AH never sold any fish.

If I'm level 6 and there's no fish what went wrong.
I should have 15,000 worth in fish I sold the Moat Carp for 1.9 and the crayfish for 500 a stack.
Edit: June 8, 2019 I listed more Moat Carp and other earth crystals on AH. Nothing listed. My AH is now bugged.
 Edit: June 9, 2019 apparently this is still an issue when you sell 2 more stacks and there's nothing.
Edit: June 11, 2019 I sold 2 more stacks of fire crystals all came back on the AH.
Can a moderator please check my AH for a not selling fish bug?
My in game name is Valthan

Please help me out it was my way out

### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)
30181205_0

**Comment by Teaspoons** [comment]
I checked ur AH history on eden website, I didnt see that u sold any fish, did u just list it on the AH? If you listed it on the AH, that does not mean it sold, you have to wait until someone buys your fish, which could mean others will sell first if they listed for a lower price.

**Comment by xizeta** [comment]
The Auction House only displays 7 items, although you can list more. You probably listed more than 7 and it got bumped off the list (It is still listed, you just can't see it unless you cancel some of the items).

**Comment by PsychedelicNPC** [comment]
No I think the AH is bigger and will not let me auction fish. 
I posted more fish to AH and nothing posted.

**Comment by bkesecker** [comment]
Understanding the client limit is helpful.  Only 7 selling items will display from the menu option to check sales status.  Your items are still listed and once sold, the proceeds will show up in your delivery box.  Please close this issue once you see the proceeds reach your delivery box.

**Comment by PsychedelicNPC** [comment]
I should have more than 12.  There isn't anything to take up space.
