### ISSUE TITLE
Mithran Stone Hidden Effect

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#1753]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

This item supposedly has a hidden effect of +10 accuracy and +10 evasion for Mithra not under the effect of food and currently does not provide that bonus.
http://ffxi.allakhazam.com/db/item.html?fitem=3405

version 30181205_0

**Comment by xizeta** [comment]
The evidence is very inconclusive. This will need retail testing.

**Comment by FariskaEden** [comment]
If this does get tested on retail it wouldn't hurt to also check out if it has any effect on the other races as well.

**Comment by FariskaEden** [comment]
Had this tested for mithra, the hidden effect gives an additional 7 accuracy & evasion (for a total of +10 accuracy and evasion) while not under the effects of any food.
![image](https://user-images.githubusercontent.com/46270382/73393219-4d2e2f00-42a9-11ea-9c7d-24c79ed0309a.png)

**Comment by KnowOne134** [comment]
retail testing has found it hidden effect is +7 to both for a total of +10 but hidden is only without food and for all races

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
