### ISSUE TITLE
Crimson Jelly's portrait informs Int-6, when the item is actually Int+6

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1755]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://i.gyazo.com/10594dcd9165f7f6ae2ff16d5c9aab18.png

There are many instances documented on FFXIclopedia that this item in question Adds INT, not subtracts it. The portrait in question should either be changed to reflect this.

**Comment by xizeta** [comment]
I checked this item in retail and this is retail accurate. Thanks for your report but we aren't interested in changing how SE chooses to represent items in the game.
