### ISSUE TITLE
Augmented gear

### ISSUE THREAD

**Issue by Arvec** [EdenServer/community#1756]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0
My character, Arvec, had two pieces of gear with augments on them -- a Spatha and a Longsword.  I don't recall when/how I aquired them, or if they had augments on Kupo.  I discarded the Spatha, but thought to hold on to the longsword and file a bug report. The Longsword says it increases HP by 1 and MP by 33, and the stats screen reflects the change when it is equipped.

**Comment by godmode** [comment]
Interesting. I will have to go through the backups and see when it was.

**Comment by KnowOne134** [comment]
There should be no gear with augments. If you have something. It needs to be tossed a d or reported
