### ISSUE TITLE
Aggro through floor in KRT

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#1757]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

30190328_2

Much like #193 , in KRT if you're on the outside of KRT (near where the Treasure Chests spawn) at J/K-8, mobs will aggro through the floor from the tunnel underneath. If that wasn't annoying enough, an ambusher spawns underneath and he doesn't like to teleport above ground to you so he'll run around underground linking other goblins. There's a bat that also spawns underneath that does the same thing.

**Comment by InoUno** [comment]
Resolved with October 4th, 2021 update.
