### ISSUE TITLE
Lord of Ozonzo spawn timer resetting on server crash/restarts.

### ISSUE THREAD

**Issue by him911** [EdenServer/community#1759]
### Checklist

- [yes] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [yes] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [yes] I have provided my client version in the details. (type /ver into your game window)

### Details
Spawn conditions of Loo were reported to persist through crashes months ago but apparently he still resets everytime the server crashes or goes through maintenance.
Loo should persist similar to Cassie, Serket and other lesser HNMs as they did on retail.

**Comment by Blex64** [comment]
All lottery spawns currently reset on server restart, so I'm not sure why Lord of Onzozo would be different.

Also, persisting is a custom change for Eden. On retail, everything reset on a server reset.

**Comment by FallenXI** [comment]
Blex is correct, persisting is a custom change because of the frequency of downtime compared to retail.

**Comment by godmode** [comment]
We should probably put LoO on a persistent timer since he's got a major drop.

**Comment by Serephim** [comment]
Yeah I would think so. There are a crap ton of Kraken Clubs on the server now since people can kill it multiple times a day depending on how many crashes or outages there are and it is probably the most expensive item on the server. lol
