### ISSUE TITLE
Evil Clones?

### ISSUE THREAD

**Issue by Xaver-Entropia** [EdenServer/community#176]
Character models seem to stay behind after you zone.

![xaver_2018 10 16_205745](https://user-images.githubusercontent.com/8134710/47040653-0cc7a200-d187-11e8-9f8f-1cdc36816294.png)

He really was in Bastok, but i could poke him. I could not check him though nor cast on him, reciveing the message "You cannot attack that target"

Dabeast's model stayed there even after he zoned in, but it disappeared when he got in range.

**Comment by gweivyth** [comment]
I noticed this when outpost warping on my characters. Very strange.

**Comment by godmode** [comment]
Please add details to this ticket if you learn more about it.
