### ISSUE TITLE
Puppetmaster skill levels on frames incorrect.

### ISSUE THREAD

**Issue by Tristin42** [EdenServer/community#1763]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version: 30181205_0

Hi! So bug here, on puppetmaster, there is an error with Automaton skill levels between Frames. Valoredge and Sharpshooter frames should have the exact same skill level between Valor's melee skill, ahd sharpshots ranged skill with the proper frame/head combinations. Currently, it seems as though sharpshot has an incorrect rating on his ranged attack skill. Valoredge, at lvl 70, has a melee skill of: 252. Sharpshot, on the other hand, has a ranged skill of 244 at level 70. It's not a MAJOR bug, but it definitely affects accuracy and attack values, as well as the level of which puppetmasters are learning their pet's weapon skills. I'm not sure if the other frames have incorrect values, as far as I can tell, the mage frames magic skill values are correct. Not sure about melee though.

Thank you for your time!

Edit: I actually figured it out. From what I can tell, it seems as though Valoredge has a A+ Rating in his melee attack scaling, while Sharpshot has a A- scaling. On live, it was actually A- for both. So I'm reporting a bug that will negatively affect pups once fixed! Whoops. I BELIEVE those are the correct values that I've posted.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
