### ISSUE TITLE
Infinite Quick Draw - COR

### ISSUE THREAD

**Issue by Starved** [EdenServer/community#1764]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

At the end of an level Synced party in Bhaflau Thickets, I used my 2hr Wild Card and noticed that the cooldown for Quick Draw was over 2:00 min (was 2:40).  I thought this was an error with an addon and thought I may have had another shot left, but by spamming my macro, I found that I could endlessly use quickdraw and blasted a couple of birds with my new Ice Shot gattling gun to confirm the issue.  It was fun while it lasted, but this should definitely be fixed before someone else finds and abuses, as it can probably be used to kill gods quite easily.

version 30181205_0

**Comment by Shoruto** [comment]
I have moved this report to #2333 in it's entirety and will close this report. If you have any more information to provide please put it on the other report. Thanks
