### ISSUE TITLE
Bark spiders in Bohyada tree hitting too hard

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1767]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

![image](https://user-images.githubusercontent.com/10780696/59316883-9b48e080-8c8e-11e9-8651-22abba8d445e.png)
![image](https://user-images.githubusercontent.com/10780696/59316907-b87daf00-8c8e-11e9-9f24-be5cfb807ff8.png)

Those were two sickle slashes from a level 60 spider. 
What on earth is that nonsense man it one shot two of our guys at level 50.

**Comment by FallenXI** [comment]
I think there's a bigger issue across the board with TP moves honestly, Rhino Attack from Beetles can also often oneshot tanks at Garlaige EXP level.

There was another TP move too, but can't remember it off the top of my head.
