### ISSUE TITLE
Beryl-footed Molberry overtuned

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#1770]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

I enjoy a good challenge as much as the next guy but this NM is somewhat overtuned.  According to the wiki talk page this mob can be solo'd by a BST75/THF15 and some other jobs.  I have fought it a few times now and can confirm that it absolutely cannot be solo'd, even with a Familiar'd CourierCarrie.  The mob has far too much HP and does way too much damage.  It has very high attack speed as well.  I cannot recall fighting it on retail but comparing the experience from this talk page and the in-game mob, I can safely say it is overtuned in some way.  Please investigate.  Thank you!

Talk page: https://ffxiclopedia.fandom.com/wiki/Talk:Beryl-footed_Molberry#Testimonials

ver: 30181205_0

**Comment by Setz0r** [comment]
Per this 2005 jp wiki page:
```
The level of NM will be Lv63 or Lv64 
HP is 6000
```
