### ISSUE TITLE
In the THF AF3 quest, in the final step, quest text is missing

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1773]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://gyazo.com/27d56f9dbfe48a43dba2c94cdac72266

The word "Pickaxe" is supposed to be where the blank space is, as a pickaxe is required to dig up the chest.

**Comment by archfiendrubicante** [comment]
It should also be known that the text for which nation the adventurer belongs to isn't pulling correctly.
https://gyazo.com/9095df8e6224953c73d4007a50c21c38

**Comment by archfiendrubicante** [comment]
( I'm Windurstan )

**Comment by archfiendrubicante** [comment]
This may have something to do with the /salute emote and why its the same for everyone. Perhaps the nation isn't being properly set upon character creation in regards to this emote?

**Comment by archfiendrubicante** [comment]
The text "Rogue's Poulaines" is also missing from this line:
https://gyazo.com/b95a384387992f423643b437314d9869

**Comment by xizeta** [comment]
Thanks for your report. In future please do not put multiple issues into the same ticket, it makes things much harder to track. :)
