### ISSUE TITLE
You can attack while crafting

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#1775]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

If you engage a monster and start a synthesis, you can continue to craft and your character will also continue to attack as normal. 

It's late and I'm on my laptop and can't find where the screenshot is saved so I can update the screenshot later, but it shouldn't be necessary as this is very reproducible. 

Version: 30181205_0

**Comment by KnowOne134** [comment]
Has been corrected in a past patch
