### ISSUE TITLE
Leather guild NPC bugged. Cannot receive any GP

### ISSUE THREAD

**Issue by shaddix83** [EdenServer/community#1776]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
There was 1 issue but it turned out they didn't know you have to wait a jp midnight. I've waited multiple 
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
I changed guilds from clothcraft to leather on a Saturday night.
Sunday afternoon after jp midnight/tally: I was asked to make barbarian's belts.
I crafted some and traded the leather GP npc the belts and there was no dialouge, she did not accept them, nothing happens at all.
Thinking the tally bugged, I waited the next day. Was asked to make raptor helms. 
Made some and traded...nothing happened at all.
Waited one last day, was asked to make leather gloves. Got some and traded them. Nothing happened at all. Thinking I bugged the leather npc, I swapped to smithing.
The next jp midnight, I was able to turn in gear and acquire GP for smithing. I got my 10k GP needed. I swapped back the leather to see if it would work.
I waited a jp midnight and they asked for magic belts. I crafted some and traded them and nothing happened at all. I cannot receive any leather GP at all.

[x] I have provided my client version in the details. (type /ver into your game window)
version 30181205_0

### Details
I have switched to from cloth to leathercraft. It's been 3 jp midnights and the npc Alivatand will tell me what he is accepting but when I trade it, nothing happens. I did not rank up. He should be accepting the items. I switched to smithing and was able to turn in items just fine. I got my 10k GP and key item I needed. I switched back to leather (thinking maybe something bugged the 1st time) waited a jp midnight and crafted the items the npc above asked for. He does not accept them, doesn't give me any dialouge...nothing happens at all. The Leather GP npc is not accepting my items and I cannot receive any leather Guild points (I've tried a total of 4 days [jp midnights and even a weekly tally] and this npc isn't giving me guild points at all

**Comment by bkesecker** [comment]
Super late comment, but if not resolved, please call GM, might be able to get it fixed.
