### ISSUE TITLE
Dynamis Sandy - Mega Boss/Win and Repops failed to spawn - Request partial reimbursement

### ISSUE THREAD

**Issue by SaberSuper** [EdenServer/community#1777]
Dynamis Sandy on 6/14/2019 

Cleared entire zone until mega boss, it did not spawn and Bass was unable to reach GM.  This is our third time, Supersaber/Supercrash was our sponsor for tonight.  Looking for partial reimbursement or whatever you guys think is fair. Thanks. feel free to send me a message on Discord if i'm not online or talk to Pan/Chan or Xaver they are leaders of our shell.

Kindest Regards,

Supercrash

### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by godmode** [comment]
Can you give me a coin count so I don’t have to look it up?

**Comment by SaberSuper** [comment]
Hey GM,
Yeah it was roughly 450 currency on Friday, exact number might be tough i merged them with my other currencies.  I was about 3050 and i came to about 3500, again rough numbers i rounded up.
Kindest Regards,
Superrcrash    On Saturday, June 15, 2019, 10:08:28 AM EDT, Godmode <notifications@github.com> wrote:  
 
 
Can you give me a coin count so I don’t have to look it up?

**Comment by rude-jerk** [comment]
This seems like a specific request that likely should have been a GM call, going to close it for now.
