### ISSUE TITLE
All cursed gear NPC for 0 gil

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#1778]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

I checked several different cursed items and they all NPC for 0 gil. I think they should NPC for around 12k ea or so.

Example:
https://ffxiclopedia.fandom.com/wiki/Cursed_Subligar

**Comment by rka666** [comment]
I echo this. NPC cursed gear is at least 11k+ and now in game it is at zero gil sale price.

**Comment by godmode** [comment]
If you can link the wiki pages you want adjusted with the historical pages I will check into this.

**Comment by Timonthy** [comment]
Thirded, https://ffxiclopedia.fandom.com/wiki/Cursed_Finger_Gauntlets?direction=next&oldid=501910 sell for 0 gil here, unfortunately can't find earlier than 2008.

**Comment by rka666** [comment]
Pity, I only found 2008 one myself.
https://ffxiclopedia.fandom.com/wiki/Cursed_Gloves?oldid=498372

I think people just did not update Sale Prices on Wiki at all as some of them even at 2019 would not have values.

**Comment by PoppaPip** [comment]
Bumping this with research...

The earliest mentions of NPC pricing I've found are a comment [here](https://www.ffxiah.com/item/1390/cursed-cuisses) from June of 2008, and a wiki article [here](https://ffxiclopedia.fandom.com/wiki/Cursed_Finger_Gauntlets?oldid=528875) from May of 2008. I know our cutoff is ~ish WoTG which was November of 2007. I couldn't find anything posted earlier than that date.

I went through the [update history](http://www.playonline.com/pcd/verup/ff11us/update.html) from 2004 to 2011, and there isn't a single note about cursed gear price changes. I _did_ however find changes for the prices of [sweets](http://www.playonline.com/updateus/041209we8yu0.html), [rusty items](http://www.playonline.com/comnewsus/200402264502.html), and [padded caps](http://www.playonline.com/updateus/040914gs7tr3.html) in 2004, [fish](http://www.playonline.com/updateus/050224hu5ol4.html) in 2005, [weapons and materials](http://www.playonline.com/pcd/verup/ff11us/detail/3893/detail.html) in 2008, and [pet items](http://www.playonline.com/pcd/verup/ff11us/detail/5338/detail.html) in 2010, meaning that at least between those years they logged NPC price changes, and any wiki/reliable sources posted in that interim should be accurate.

Checking the two oldest wiki pages I've found, [cursed hauberk](https://ffxiclopedia.fandom.com/wiki/Cursed_Hauberk?oldid=585195), and [finger gauntlets](https://ffxiclopedia.fandom.com/wiki/Cursed_Finger_Gauntlets?oldid=528875), the price point doesn't change between 2008 and 2019, which indicates that current prices should reflect era prices.

As for -1 vs NQ, [cursed mask -1](https://ffxiclopedia.fandom.com/wiki/Cursed_Mask_-1?oldid=1408088) and [cursed mask](https://ffxiclopedia.fandom.com/wiki/Cursed_Mask?oldid=1470364) (from 2012/2014), [cursed greaves -1](https://ffxiclopedia.fandom.com/wiki/Cursed_Greaves_-1) and [cursed greaves](https://ffxiclopedia.fandom.com/wiki/Cursed_Greaves) (current), as well as others, evidence a slight increase for HQ, between 8-22%.

With that being said, I've compiled current wiki prices below.

**Cursed Crown** 6,757 ~ 6,790 gil
**Cursed Dalmatica** ~ 25,804 gil
**Cursed Mitts** 10,457 ~ 11,136 gil
**Cursed Slacks** ~ 20,371 gil
**Cursed Pumps** ??? ~ ??? | _**HQ** ~ 21,865 gil_

**Cursed Mask** ~ 8,513 gil | _**HQ** ~ 9,913 gil_
**Cursed Mail** ~ 15,237 gil
**Cursed Finger Gauntlets** 7,420 ~ 7,605 gil
**Cursed Cuisses** ~ 10,202 gil | _**HQ** ~ 11,181 gil_
**Cursed Greaves** 6,625 ~ 6,790 gil | _**HQ** ~ 8,148 gil_

**Cursed Kabuto** ~ 11,543 gil | _**HQ** ~ 12,901 gil_
**Cursed Togi** 19,596 ~ 19,692 gil | _**HQ** ~ 21,050 gil_
**Cursed Kote** 11,352 ~ 11,408 gil | _**HQ** ~ 12,766 gil_
**Cursed Haidate** 10,702 ~ 10,728 gil | _**HQ** ~ 12,086 gil_
**Cursed Sune-Ate** 9,010 ~ 9,235 gil | _**HQ** ~ 10,593 gil_

**Cursed Schaller** 10,427 ~ 11,018 gil
**Cursed Cuirass** 39,150 ~ 40,128 gil
**Cursed Handschuhs** ~ 11,275 gil
**Cursed Diechlings** ~ 11,500 gil
**Cursed Schuhs** ~ 11,250 gil

**Cursed Celata** ~ 10,185 gil
**Cursed Hauberk** ~ 27,705 gil
**Cursed Mufflers** 8,353 ~ 8,827 gil | _**HQ** ~ 10,185 gil_
**Cursed Breeches** ~ 9,235 gil 
**Cursed Sollerets** 15,767 ~ 16,161 gil
