### ISSUE TITLE
Musketoon not listed on AH, only the +1 version is

### ISSUE THREAD

**Issue by falantar** [EdenServer/community#1779]
### Checklist

- [ O ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ O ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ O ] I have provided my client version in the details. (type /ver into your game window)

### Details

The Musketoon +1 is listed on the AH but not the NQ version. Website says that there are 68 listed.

Game version: 30181205_0

**Comment by ccl085** [comment]
Not sure if I should put it here or open a new one, but Musketoon is actually an out of era gun (2009), the 1st available gun for corsair on era was bandit gun at level 15
