### ISSUE TITLE
Dagourmarche is not implemented

### ISSUE THREAD

**Issue by slassen** [EdenServer/community#1780]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

https://ffxiclopedia.fandom.com/wiki/Dagourmarche
This monster should pop when his spawn conditions have been met in Dynamis - Beaucedine. Currently he does not spawn because of several issues with being as mater to multiple pets. The person who picks up this ticket should ensure that the avatar will Astral Flow immediately after triggering, is resummoned when dies. Call Wyvern is only used when the wyvern is down but otherwise the 2 hour abilities are used multiple successive times in constant intervals. Finally, he should be able to charm and familiar should work on all pets.

**Comment by Setz0r** [comment]
well, thanks to the divine might update, mobs can now call multiple pets by passing the mob ID as the 2nd parameter to spawnpet. see ark angel mithra's lua.

**Comment by Slamm21** [comment]
![image](https://user-images.githubusercontent.com/5552081/87757996-8a5c8e00-c803-11ea-8d2c-2230e28af9d6.png)
Just confirming this NM is still not implemented, he didn't pop on our last run.

**Comment by HunnyDoo** [comment]
Yeah the NM currently still doesn't pop. I feel bad for the Gungnir builders.................. not so much for the gutler and claustrum builders.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update. will need an updated renamer file to have the hound's name register properly so for the foreseeable future every stream will have him as Taquede but hey
