### ISSUE TITLE
Cannot pick up a Siren's Tear after doing the quest

### ISSUE THREAD

**Issue by Jamini** [EdenServer/community#1782]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

--

Client version 30181205_0

After completing The Siren's Tear quest, you are unable to pick up another Tear.

Steps to reproduce

1. Complete The Siren's Tear
2. Find the ??? in North Gustaburg
3. Unequip Weapon
4. Touch the ???

Expected Response: Obtaining a Siren's Tear
Current Response: Error Message

"You cannot Obtain Siren's Tear"
"Please come back after sorting your inventory"

---
This error persists even if you have an empty inventory.
Confirmed this is occurring on two characters.

![image](https://user-images.githubusercontent.com/1775680/59556380-bae25080-8f8f-11e9-9fff-b710334c05ad.png)

**Comment by Jamini** [comment]
It is possible to work around this by creating an alt and having them pick up the tear (which can then be put on a bazaar). However that workaround does not fix the underlying issue.

**Comment by Toritos** [comment]
Currently not set as a repeatable quest, as when you complete the quest the first time, the player var SirensTear gets set to 0, and it needs to be > 2 to be able to obtain the tear, hence why you cannot obtain it again.

**Comment by Jamini** [comment]
Well that certainly isn't retail behavior, and causes issues for other quests that need the item. (Namely, the BLU questline has a Siren's Tear as a possible required item.)
