### ISSUE TITLE
Bazaars not properly showing

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#1786]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I can not see about 90% of bazaars that I know are open bazaars. They just show as if I checked a player without any bazaar open. I have had to have LS members buy from the bazaar even with me standing right there. I've tried a completely fresh reinstall with latest version and tried with disabling all addons/plugins on both Ashita and Windower4, same issue.

**Comment by 59blargedy** [comment]
havent heard of this happening to anyone, going to assume this was an isolated issue or something resolved through code overhauls over the years and close out
