### ISSUE TITLE
Elshimo Pachira Fruit(Out of Era food ingredient)

### ISSUE THREAD

**Issue by him911** [EdenServer/community#1787]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

![pacchiro](https://user-images.githubusercontent.com/50463084/59574403-28919800-90c8-11e9-84d1-cc721aafd7c6.png)
Its used to make the furnishing Elshimo Pachira 
Added to game in 2010

**Comment by archfiendrubicante** [comment]
It isn't a food ingredient, it's a furnishing ingredient.

**Comment by him911** [comment]
Its listed under food > ingredients   

I already pointed out that its used to make a furnishing
