### ISSUE TITLE
Hauteclaire drop rate check

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#1788]
So far on Eden there have been 39 Khimaira kills and only one Hauteclaire has dropped. TH3 for every kill. Wiki has the drop rate at 7.2% so it might be lower than it should be on Eden. 

As a sidenote, 6 seveneyes have dropped which is very close to the wiki %. (15.4% on Eden, 14.4% on wiki)

https://ffxiclopedia.fandom.com/wiki/Khimaira
Version 30190328_2

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by Toritos** [comment]
Set as 7% drop rate (before any mods) in darkstar so I expect the same on Eden

**Comment by Oyaziiiiiii** [comment]
Drop rates were adjusted to account for TH, so TH3 should yield the 7% average rate here. But as a server we are 1/39 now, with only one drop in over four months of killing. I never saw a stretch like that on retail.

**Comment by Oyaziiiiiii** [comment]
Update: 1/64 overall, 0/20 since the patch on 7/1 that adjusted the drop rate.
