### ISSUE TITLE
Apkallu egg drop rates not accurate

### ISSUE THREAD

**Issue by him911** [EdenServer/community#1791]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
I cant count how many i'v killed with TH3 and barely any are dropping from Zhayolm Apkallu's

**Comment by him911** [comment]
To put in context 

With TH3 on craftables with a 9-10% drop rate im getting the drop at almost 40-50% just eyeballing it

Apkallu eggs are listed at higher than 20% drop rate and im getting less than 10% rate on them and thats being generous.

**Comment by archfiendrubicante** [comment]
I'll buy those eggs off you fren

**Comment by Apocalypse612** [comment]
What zone are you in, and what enemies are you fighting? There needs to be more details here.

**Comment by archfiendrubicante** [comment]
I think its pretty apparent where he is and what he's killing...

> I cant count how many i'v killed with TH3 and barely any are dropping from **_Zhayolm Apkallu's_**

**Comment by bkesecker** [comment]
The present rate is 8%.  Can anyone provide a link with supporting evidence?

**Comment by Apocalypse612** [comment]
FFxiclopedia lists 21%.

https://ffxiclopedia.fandom.com/wiki/Zhayolm_Apkallu

**Comment by Shoruto** [comment]
Everything I'm finding supports the 8-12% drop rate (and even lower in one case) range.  The 21.1% is from retail information.

http://www.ffxidb.com/zones/61/zhayolm-apkallu = 12% 
http://ffxi.allakhazam.com/db/item.html?fitem=10001 = Replied post underneath is as follows

**Aug 30 2007** at 10:59 AM
Onotheo
These eggs are hard to obtain. I killed 30 apkallus (**lvl75 thf)** and only got two. Maybe it was just bad luck. The only other way I know of how to obtain them is through auction house when it happens to be someone is selling.

**Comment by bkesecker** [comment]
Found similar, "Really sad that these are so rare because some of the food you can make with them give such great hMP+ bonuses. 2009-10-08 21:42:28". The date of the comment leans toward the existing rate being more era accurate.

**Comment by bkesecker** [comment]
General consensus among the development team is no change to be era accurate.
