### ISSUE TITLE
windurst mission 8-1:Vain - not working

### ISSUE THREAD

**Issue by blacknesscrows** [EdenServer/community#1792]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

The taru Sedal Godjal is not accecpting my curse wand. When i talk to him he asks for it but there is no CS when the item is traded. 

another thing i noticed is the CS in R'Maeve keeps repeating when i click on the pool which is what makes me think there is an isssue. 

Thank you all, 
Sootle

**Comment by Volkaru** [comment]
The Ro'Maeve Cutscene never finishes for me. I have tried /fps 2, print screen, etc. And the cutscene won't finish properly. It hangs for 2-3 minutes, then goes forward. The doll never appears, and a few lines of dialogue in the mission are missing.

**Comment by Volkaru** [comment]
Made a MEGA video showing the Cutscene. As you can see it hangs for a minute, skips some dialogue, and then I can click the spring again to start the CS all over again. It's probably not giving me the proper completion flag.

**Comment by Slamm21** [comment]
this seems to be still happening, just had this issue today

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
