### ISSUE TITLE
Pugs in Qufim Island shouldn't be aggressive

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#1793]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

30190328_2

Greater Pugils in Qufim Island are currently aggressive by Sound. 

https://ffxiclopedia.fandom.com/wiki/Greater_Pugil?diff=223788&oldid=208374  shows them as non-aggressive and only link by sound.

**Comment by shawnhind** [comment]
Agreed, it was only ever the ones that you fished up that agro'd you.  I'd been curious why this was different as well and assumed it was that way before i started playing or something but looking at the wiki history indicates that it was never like that.

**Comment by Mozzy4Ever** [comment]
@godmode 

The pugs now neither aggro nor link.
