### ISSUE TITLE
Sahagin key quest requirements

### ISSUE THREAD

**Issue by falisaxi** [EdenServer/community#1794]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Hurr the Betrayer is only accepting 3 Mythril Beastcoins to give you a sahagin key. He should be accepting a single gold beastcoin as well to provide the key. I do recall in era that he should accept either of the two, but at least FFXIclopedia lists that he should use gold beastcoin for the repeatable portion of obtaining the key.

https://ffxiclopedia.fandom.com/wiki/Sahagin_Key_Quest?oldid=317449

version 30181205_0

**Comment by shawnhind** [comment]
To complete the quest you need to trade him three mythril beastcoins but to get subsequent keys you have to trade him a gold one.  

Quotes from the article you posted:

> Hurr the Betrayer asks for three Mythril Beastcoins and one Norg Shell.
Trade him the items and he will give you a Sahagin Key.

This is to get the initial key (and complete the quest.


>Obtaining **Subsequent** Sahagin Keys
Go directly to Hurr the Betrayer and trade one Gold Beastcoin and one Norg Shell to obtain a Sahagin Key.

This is to get more keys.

**Comment by falisaxi** [comment]
I am saying the gold beastcoin didn't work for getting another key. Only took mythril beastcoin for subsequent keys.

**Comment by 59blargedy** [comment]
wiki indicates that there is a random chance for it to require the mythril beastcoins even on a second (or third or fourth) go around) and the code does that currently - rolls randomly each time you obtain the quest, with it weighted towards gold beastcoin for second time +. going to close out this ticket as a result.
