### ISSUE TITLE
Blunderbuss NQ Missing from AH

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#1796]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
30181205_0
### Details
https://edenxi.com/db/items/19226/blunderbuss

The item , "Blunderbuss" is missing from AH listings ingame.  Website shows 29 of them on AH, and only one has sold.  After sorting AH listings twice I was unable to locate (Sorted by level, only Blunderbuss +1 is on AH for the level 61 range)

**Comment by godmode** [comment]
The HQ should be missing from the AH as well. Fixing that.
