### ISSUE TITLE
"Party Actions" not working with Adventuring Fellow

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#1797]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
To reproduce, use trick attack behind adventuring fellow. It is supposed to work as if they are a party member (from memory and wiki: "Your Adventuring Fellow can be used for Trick Attack to grant the damage received from striking behind a party or alliance member." - https://ffxiclopedia.fandom.com/wiki/Adventuring_Fellow ).

Version: 30181205_0

**Comment by Wiggo32** [comment]
FYI for Whoever picks this one up. In addition to this, Buff spells that target the entire party do not target the fellow as they should when casted by the fellow's master. Nor do BRD songs, COR rolls, Teleport Spells, or Escape.

**Comment by archfiendrubicante** [comment]
Can confirm, Trick attack doesn't work with Adventuring fellow.

**Comment by E5una** [comment]
It seems like the NPCs aren't being treated as being in the party at all. Back in the day I distinctly remember cringing as my tarutaru healer NPC was destroyed by BLM -aga spells, but so far any monster AoE that doesn't just use a hate list seems to not affect my NPC at all. It is affected by Goblin Bomb, but I feel as though that is based on them having some amount of hate from hitting the goblin.

**Comment by Leonira** [comment]
You're also supposed to heal and cast buffs on someone elses fellow as if they were someone outside of the party, but neither buffs nor cures can be cast on someone elses fellow at present.

**Comment by Althaia** [comment]
I think what E5suna says is right, they're not being treated like they're in the party at all.

I've been healing my Adv. Fellow a lot and I've noticed I can use the usual Cure an Protect spells on her, which I'd be able to do to anyone (even people not in my party), but not Regen spells, which are party-only.

**Comment by Satirof** [comment]
Adding to this as I used fellow in retail a lot. 
For spells like refresh which can only target party members, it was possible to use them on fellows with the command /ma "Refresh" <ft>. This worked for all 'party-member only spells', such as erase and regen. I believe /ma "Refresh" <st> also allowed refresh to work when you sub-tab over to the fellow, but I personally just used <ft>.

Regarding party aoe's: Blue mage spells under 'Diffusion' (blu merit ability) should also hit adventuring fellows. Currently they do not.

**Comment by Leonira** [comment]
In Response to Althaia, I can use regen on my fellow, but only when using macros that are <stpc>, not when using it from the magic menu.

Another interesting development, I accidentally mistargeted today and used paralyze on my NPC.
And I was able to cast it on her! I can apparently cast debuffs on my npc! I don't think that's supposed to be a thing, right?

**Comment by KnowOne134** [comment]
corrected on 12/28 upate
