### ISSUE TITLE
Signal Pearl inconsistent reuse delay being displayed

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#1798]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Signal Pearl shows a reuse delay of 6 hours (not era) but the actual reuse delay appears to be Era (20 hours). The display for the item just needs an update.

![image](https://user-images.githubusercontent.com/13668758/59763807-5dd4ec00-9268-11e9-84ad-238d2a8f2895.png)

Version: 30181205_0

**Comment by KnowOne134** [comment]
has been dat edited and can be found here:
https://github.com/EdenServer/Eden-Client_DATs

completed 2/26/2023
