### ISSUE TITLE
Adventuring Fellow Bond

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#1799]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

At the moment I have summoned my adventuring fellow 2 times and selected the option "Let's chat" at a Rendezvous Point on 3 separate days so I should have a total of 5 bond with my AF. When 5 bond is reached the option to change fighting styles should become available, however I have not been given this option. I'm unsure if bond points are being gained or if the options to change fighting styles are not showing up since I should have met the requirements.

version 30181205_0

**Comment by Wiggo32** [comment]
Fellow has not been released for long enough for ANYONE to reach level 5 bond when this was posted.

**Comment by panfunk** [comment]
Ehm, according to Wiki, you get +1 Bond for summoning your fellow via Signal Pearl and +1 Bond for 'chatting' with your fellow once per RL day at a Rendevouz point, so if FariskaEden did that, he should have bond of 5, which would enable the changing of the class.

Sidenote, I personally summoned my fellows 3 times, and 'chatted' 4 times on 4 different earth days and I can't change their jobs.

**Comment by FariskaEden** [comment]
As of today I was given the option to change my fellow's combat style. So I believe the issue is that the "Let's chat" option is not giving any bond. You should be able to get 1 bond from it once per RL day.
