### ISSUE TITLE
Promyvion, black screen on teleport between floors

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#18]
This is an issue I encountered on the Nasomi server as well.

After defeating a Memory Receptacle and the teleport appearing, one member of the party received a black screen after stepping onto the portal and was unable to go up with the rest of the group. This forces a group to go back down to bring them up as they cannot login until they completely d/c from the server and the teleporter has often despawned by then.

**Comment by Treble011** [comment]
This is still occuring. Witnessed it happen to two people at 5:30PM EST in Promy-Dem.

**Comment by dantaface** [comment]
usually what we did in Nasomi.. did it with 4 toons. 
Wait every dead Stray to disappear
Then get 1 by 1 on the teleporter.
Should help until it is fixed

**Comment by panfunk** [comment]
Happened again yesterday several times
