### ISSUE TITLE
Nidhogg Stats too low during wingmode.

### ISSUE THREAD

**Issue by Cheezcakee** [EdenServer/community#180]
Nidhogg Stats too low during wingmode.

**Comment by gweivyth** [comment]
Before this gets tagged with needs more info, can you be more specific? Will save a step.

**Comment by Cheezcakee** [comment]
I don't know specifically, a GM asked me to make a bug report saying his stats were too low during wingmode. Not sure if he means magic defense stats or physical stats. No idea how that works.

**Comment by godmode** [comment]
No worries on filling this one in. I just needed something to remember. Thanks guys!

**Comment by gweivyth** [comment]
Yeah I do remember him hitting for 0 on some of the mages, which was pretty weird.  His autos should break stoneskin for sure on black mages.  Maybe not white mage.
