### ISSUE TITLE
True Sight Kindred

### ISSUE THREAD

**Issue by Steel3man** [EdenServer/community#1800]
### Checklist

- [yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ yes] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ yes] I have provided my client version in the details. (type /ver into your game window)

### Details
The kindred mobs on the way up the mountain in Uleguerand Range are now aggressive to true sight instead of the normal detect by sight for kindred. I did the enm Brothers last week and had no true sight agro issues from kindred as I went up the mountain to obtain the ice . This week as I get higher up the mountain all the Kindred start becoming true sight and make the enm very difficult to complete. It seems the mobs with same names are true sight in Dynamis-Xarc but not in Uleguerand Range according to the web.
ver: 30181205_0

**Comment by Kurtalicious** [comment]
I second this.  Please fix.  It's almost impossible to navigate this area with so many true sight mobs.

**Comment by setsuk0** [comment]
The demons in Uleguerand Range seem to be true sight again. I am currently trying to run up to do the ENM and kindred demons are aggroing true sight.
