### ISSUE TITLE
Dynamis-Bastok ~ 2 TEs still not working reliably

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1802]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

		17539300 (Vanguard Vindicator) should give 10 minutes extension
		17539304 (Vanguard Constable) should give 10 minutes extension

**Comment by MysticLogos** [comment]
My linkshell has experienced the same issue with these exact time extensions not working in our last 2 Dynamis-Bastok runs.

**Comment by StriderClerix** [comment]
Doing dynamis today, these 2 TE's are missing from Constable and vindicator.

Reference: http://www.dynamisbums.com/strategy/images/maps/strategy_bas1.jpg
