### ISSUE TITLE
Fellow summon length and xp not era

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#1803]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently on Eden we can get 50 kills on the first summon, and we can get 400 xp per kill (so only need 15 kills to level 30-31). This matches the current retail numbers, and also means we can cap at 50 in less than 2 weeks.

https://ffxiclopedia.fandom.com/wiki/Adventuring_Fellow?oldid=340426

We're supposed to only be able to get 15 kills per summon until we raise the bond with our fellow and cap at 200 xp per kill (so 29 kills from 30-31).

**Comment by Wiggo32** [comment]
Thanks @mlandrum22 for the era values!
