### ISSUE TITLE
Buffoon's Collar not showing on AH

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#1805]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

Much like #1779, https://ffxiclopedia.fandom.com/wiki/Buffoon%27s_Collar (Item ID 16281) isn't listed on the AH but the +1 version (ID 16282) is.

**Comment by archfiendrubicante** [comment]
This is an out of era item.

https://ffxiclopedia.fandom.com/wiki/Buffoon%27s_Collar?action=history

**Comment by Mozzy4Ever** [comment]
> This is an out of era item.
> 
> https://ffxiclopedia.fandom.com/wiki/Buffoon%27s_Collar?action=history

So it would seem. Dec 8th 2008 update (https://www.bg-wiki.com/bg/Version_Update_(12/08/2008)) seems to have added "Many new pieces of equipment have been added." (though it doesn't list what....)

**Comment by godmode** [comment]
Removing the HQ from the AH
