### ISSUE TITLE
Error 3307 login

### ISSUE THREAD

**Issue by jadger** [EdenServer/community#1809]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
I cant login un the Game   after i use a instant warpscroll.     User:  Jagger

**Comment by bkesecker** [comment]
Please report things like that in-game via Help Desk and a GM will help you eventually.

**Comment by bkesecker** [comment]
Apologies. Sometimes you need to wait a while for your session to clear.  Try again, and if you still can't login, reopen this issue.
