### ISSUE TITLE
Nations Lost Control of Regions/Their Vendors and Outpost Guards Missing

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#1814]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

After the maintenance today, I was no longer able to buy/sell from vendors that my nation controlled. When using the OP warp to a place that was under our control the guard is missing from the outpost and I had to pay the amount I would pay as if the region was not under my nation's control.
![image](https://user-images.githubusercontent.com/46270382/60052543-8a8f6600-96a3-11e9-8a49-2184142579b8.png)
![image](https://user-images.githubusercontent.com/46270382/60052549-8ebb8380-96a3-11e9-8485-249653e997cc.png)

version 30181205_0

**Comment by godmode** [comment]
Very odd. Nothing even slightly touched that stuff. I wonder what happened. We will look into it.
