### ISSUE TITLE
Reacquired Key Item

### ISSUE THREAD

**Issue by AkumoBunni** [EdenServer/community#1816]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Helped an LS mate with Sandy 2-3 and when we finished the fight, It said I acquired key item Kindered Crest. (I'm rank 10 Sandy.) I'm not sure if this should happen or not, and I don't want to have the key item and it mess up something later. 
![KC](https://user-images.githubusercontent.com/47017672/60055062-0688ae80-96a2-11e9-920d-699e1ffecb70.PNG)

**Comment by bkesecker** [comment]
Did you confirm you have the key item?  If so, and you do, please make a GM call to get it removed.

**Comment by AkumoBunni** [comment]
I DID have it after this, I checked my key items after doing it and it was there. However, I just checked now and it is no longer in my key items. I had forgotten I submitted this report. I guess it worked itself out at some point.

**Comment by KnowOne134** [comment]
Corrected 3/29/2021
