### ISSUE TITLE
Tremorstone obtained from ??? in Cloister of Tremors is out of era

### ISSUE THREAD

**Issue by PatricYuumi** [EdenServer/community#1818]
I was about to do Trial by Earth fight and clicked the ??? next to Earth Protocrystal in the Cloister of Earth. It gave me a Tremorstone item which is used in a quest to obtain Loadstone key item, allowing users to pass through the weighted doors in Quicksand Caves.

I looked up both key item and tremorstone on wiki and it looks to be after era, were these left in for Quality of Life improvement or by accident?

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Slamm21** [comment]
I got one of those myself and chucked it not knowing what it was, I assume it is not meant to be there.
