### ISSUE TITLE
Caedarva Mire monster (Imp and Fly) levels possibly incorrect 

### ISSUE THREAD

**Issue by raventn** [EdenServer/community#1819]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

Heraldic imps are to high level shows around 80+ at azouph Isle stagging point they usely be 76 - 78 very good exp spots for 66 67+ 
and hit like they where HNM. 

Flys Spongilla fly has wierd def as 69 ninja i hit them for 8 to 20 dmg and it can hit me for 233 dmg+ level is correct but there stats are way higher then they suppose to be.

**Comment by godmode** [comment]
It looks like they are correct. If you have current retail testing please post it as a comment here.
