### ISSUE TITLE
Kirin multiple astral flows

### ISSUE THREAD

**Issue by Twentytwox** [EdenServer/community#1820]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver. 30282305_0
![pol_YVoxjHuEos](https://user-images.githubusercontent.com/47615465/60143822-0a91fa80-978e-11e9-92e0-3545a7890a75.jpg)

**Comment by Twentytwox** [comment]
![pol_n5ROQcQfO1](https://user-images.githubusercontent.com/47615465/60146401-7593ff00-9797-11e9-8d27-bfbe41521cee.jpg)

**Comment by Slamm21** [comment]
Prime Avatars do this as well, sometimes 5x per fight. Seems to be a problem on a number of nms

**Comment by asphodel-eden** [comment]
We had the same issue today. Kirin summoned Fenrir and used Astral Flow. Fenrir's 2hr, Howling Moon, went off 3 times in a row. Please see image attached. 
![kirin_AF](https://user-images.githubusercontent.com/61460959/79670029-e9235480-818d-11ea-8f28-62c985d3bddb.png)

**Comment by Crescensx** [comment]
We had the same issue just now as well. 
![KirinDouble2hr](https://user-images.githubusercontent.com/60233601/99930573-8b587b80-2d1f-11eb-9f04-879958c88f53.png)
