### ISSUE TITLE
Fellow doesn't attempt to close distance upon engaging

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1827]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

![image](https://user-images.githubusercontent.com/10780696/60309767-79518e00-991d-11e9-9754-fc74789e0faf.png)

Upon attempting to aggress something within a long distance from your fellow, the fellow will go into battle stance and stand still even if out of range of the target. (You can see the fellow far in the distance in the screenshot)

To repeat this, use flee with the fellow out, run away with it on, then engage something.

**Comment by KnowOne134** [comment]
Updated 3/8/2021
