### ISSUE TITLE
Eldieme Necropolis Tomb Warrior drops Chest Key instead of Coffer Key

### ISSUE THREAD

**Issue by l33tbmb** [EdenServer/community#1828]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Tried farming for a coffer key vs Tomb Warrior and Tomb Mages in The Eldieme Necropolis and received two regular Chest Keys from Tomb Warriors. Checked wiki history on FFXI and Allakhazam sites, both list Tomb Warriors as dropping Coffer Key, not Chest Key.

Tried farming other mobs for the coffer key but died before I could see drops from Mages and Spriggans.

Client Ver: 30181205_0

**Comment by Slamm21** [comment]
Seems the chest key drop is out of era, however, I can confirm that both the tomb mages and warriors drop the coffer key. I have had it drop from both of them before. Right now the warriors just drop both keys.

**Comment by godmode** [comment]
Removing the chest key from Tomb Warrior drop list.
