### ISSUE TITLE
Den of Rancor Gates still not quite right.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#183]
I tested the gates again after you extended the times the lanterns stayed lit and you can now get through the gate to the sacrificial chamber and the the first gate by Hakutaku in time if you haul ass and don't aggro anything even without movement speed +, so that part is fixed. 
But the gate by Hakutaku doesn't stay open long enough for you to collect the crimson flame and get back to and through this gate again. Once you open the gate it just automatically closes after a few seconds. It has to stay open for at least 10 minutes before it closes in order to make it back in time. I timed it.

**Comment by godmode** [comment]
These were just captured from retail recently. Leading me to believe they shouldn't stay open as long as the other. Please update the ticket if you know otherwise as this wouldn't be hard to implement.

**Comment by Serephim** [comment]
I remember specifically being able to get there and farm Fudos myself. After some digging around, the only proof I can find about the gate staying open in order to get to the NM's ahead solo is people saying they solo'd and duo'd them on the Wiki.  http://ffxiclopedia.wikia.com/wiki/Tonberry_Decapitator

**Comment by Wiggo32** [comment]
Per retail: The gates only stay open for 30 seconds once all of the lanterns are lit. The lanterns will stay lit until the gate associated with them opens. (either by lighting all the lanterns or hitting the switch from the inside) (some gates dont have inside switches). If you want to solo open all the way to the NM's you must get your Crimson Flame, then farm another unlit lantern, then get the Blue Flame, then farm another unlit lantern, and from there proceed to open the Hakutaku gate with the regular runs of Rancor Flame.

**Comment by Serephim** [comment]
@Wiggo32 Thank you! That is how I did it solo! I knew there was a way to do it but I assumed the only way it would be possible would be if the gate was to stay open to be able to collect all 4 flames in time. I totally forgot that when you collect a flame with a Rare/Ex unlit lantern it changes the unlit lantern to a flame so the item switches and allows you to hold more than 1 at a time. Man I feel so stupid now. Appreciate your input. :) 
So I guess the only thing that is wrong now is that the lanterns have to stay lit unless all associated lanterns are lit and the gate opens then?
