### ISSUE TITLE
Wyvern Skull should be ra/ex

### ISSUE THREAD

**Issue by GalkaZajin** [EdenServer/community#1831]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Wyvern Skull was ra/ex all the way up until 2017.

https://ffxiclopedia.fandom.com/wiki/Wyvern_Skull?oldid=378177
version 30181205_0

**Comment by GalkaZajin** [comment]
It looks like this is still being sold on the AH? I can confirm that it's untradable though.

**Comment by GalkaZajin** [comment]
Are we able to completely remove this from the AH?

**Comment by VirtuosusFFXI** [comment]
These are still being bought off the AH, should not be

**Comment by falzum** [comment]
Since the update 2ish months ago these are now ra/ex for the purposes of being traded, but they can still be mailed via dbox

**Comment by KnowOne134** [comment]
has been dat edited and can be found here:
https://github.com/EdenServer/Eden-Client_DATs

completed 2/26/2023
