### ISSUE TITLE
21-24 hour NMs biased towards last window

### ISSUE THREAD

**Issue by marlinla** [EdenServer/community#1835]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

Many if not all 21-24 hour NM spawns are biased towards last window. Could it be verified that all windows have equal likelihood of spawning an NM and is determined at ToD?

**Comment by KnowOne134** [comment]
This is all done by RNG 1 to how many windows it has

**Comment by 59blargedy** [comment]
im not sure why this one is open still, but can say that the code was validated and chance is equally weighted.
