### ISSUE TITLE
Several NPCs are not returning to their default rotation after speaking..

### ISSUE THREAD

**Issue by Apocalypse612** [EdenServer/community#1836]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Client Version: 30181205_0

NPCs in general have a few issue after you are done speaking to them. 

1) They are not returning to their default rotation after you are done speaking with them. If I walk into Bastok Markets and someone else talks to the signet NPC, he shouldnt be facing an odd direction at a wall when I've never talked to him before.

2) they will "lock on" to you if YOU or ANOTHER PLAYER that has spoken with them at least once. This is supposed to be client side only. I shouldn't be able to see a signet NPC locking contact (aka I see his head moving and twisting) with another player character on th e server.

I've tested this with several NPCs in Bastok, unsure if ALL of them behave this way.

**Comment by Apocalypse612** [comment]
Here's a few that I've noticed so far that have this broken behavior:

Khonzon - Bastok Mrkets (E-9)
Gawful - Bastok Mines (H-8)

**Comment by InoUno** [comment]
Resolved in December 28, 2020 patch.
