### ISSUE TITLE
Oztroja stairs ridiculously buggy, perpetual "out of range"

### ISSUE THREAD

**Issue by archfiendrubicante** [EdenServer/community#1837]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Something is going on with the stairs near where the torch door is in Castle oztroja, the mobs standing on it at any time are always out of range and you cannot attack them under any circumstance aside from ranged or Magic.

https://gyazo.com/cdf74d59374755dc02fd02a2c3413c14

The stairs I'm referring to are these:
https://gyazo.com/772b68a53760be60ad43097b21300736

**Comment by godmode** [comment]
This is a navmesh issue and will be some time before it is fixed. If you search the bug reports you can see several like this. It will all be the same fix.
