### ISSUE TITLE
Hilltroll Puppetmasters might be PUP/PUP & have OoE trait

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#1838]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

I suspect the Hilltroll Puppetmasters in Mount Zhayolm are PUP/PUP because at level 80 Puppetmasters gain the trait Evasion Bonus IV and these mobs range from 79-83. They normally rate to me as having neutral evasion without a few accuracy pieces but when encountering the level 80 or higher ones with my accuracy gear equipped they have high evasion and are very difficult to hit.

version 30181205_0

**Comment by greyenvy** [comment]
I have observed the same jump in evasion going to the level 80+ mobs.  Furthermore, and I don’t know if they should, they do not attack with both hands either.  Just a single attack per round as it is now.

**Comment by 59blargedy** [comment]
resolved 11/9
