### ISSUE TITLE
Loaded into ship bound for Mhaura dead

### ISSUE THREAD

**Issue by brndmfrd** [EdenServer/community#1839]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
# Issue:    
* Spawned dead on ship from Selbina-Mhaura.
* A pirate attack did occur, but I did not appear to be attacked at any point. 

# Steps:    
* Board the boat for Mhaura.
* While waiting, go to the bathroom and brush teeth.
* Come back to game to find your character dead in the cabin of the boat.

# Added Info
* A pirate attack occurred which did involve Silverhook. (Logs show "Silver hook starts casting Ice Spikes...")
* Nothing in my log indicated that I was attacked. Absence of "XXX hits you for YYY damage!".
* At no point did I leave the cabin. I was afk when the boat transition occurred (Area change from Selbina to "Area: Ship bound for Mhaura").

# Version:   
"version 30181205_0"

**Comment by Setz0r** [comment]
No other reports for this.  A fix was put into place to keep players safe below deck.
