### ISSUE TITLE
The effect of Tonko: Ichi or Tonko: Ni lasts for a randomized duration instead of a fixed duration

### ISSUE THREAD

**Issue by Spider-Dan** [EdenServer/community#1840]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

client version: version 30181205_0
steps to reproduce issue: with at least one Shinobi-Tabi in inventory, cast the spell Tonko: Ichi or Tonko: Ni and observe duration of effect

Tonko: Ichi and Tonko: Ni currently behave like the White Magic spell Invisible, providing a randomized duration (within a certain range) of invisibility.  However, the era-accurate behavior for these spells is a fixed duration of invisibility: 3 minutes for Tonko: Ichi, and 5 minutes for Tonko: Ni.  For reference:

https://ffxiclopedia.fandom.com/wiki/Tonko:_Ichi?oldid=310282
https://ffxiclopedia.fandom.com/wiki/Tonko:_Ni?oldid=310283

**Comment by AikoSachi** [comment]
Worth pointing out that on those wiki pages they have Durations listed and are from an era-appropriate time-frame.

On the invisible/sneak pages there is no duration listed as they were randomized, which further supports that the durations listed here were static rather than randomized for these 2 abilities.
