### ISSUE TITLE
Bastok 1-1: The Zeruhn Report, Lucius doesn't walk correctly during end cutscene.

### ISSUE THREAD

**Issue by Apocalypse612** [EdenServer/community#1841]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
During the final cutscene of Bastok Mission 1-1: The Zeruhn Report, the NPC Lucious doesn't walk correctly down the stairs. He does this weird half-step cycle that loops, its a bit hard to explain.

Here's how he's SUPPOSED to look when he walks down the steps:
https://youtu.be/lky6qR00nJc?t=446

**Comment by bkesecker** [comment]
I noticed the same, but it feels client-side.  Maybe SE updates caused it to glitch with later releases?
