### ISSUE TITLE
Naigama (Lvl70 Scythe)'s Additional Effect (MP Drain) Doesn't Work.

### ISSUE THREAD

**Issue by CzarLimit** [EdenServer/community#1842]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0
I've spent a lot of money into making this scythe so my BLM can solo and gain some MP while meleeing and doing damage. But I'm almost level 100 scythe and it has never drained any sort of MP from any monster in the game.

**Comment by bkesecker** [comment]
Probably among those missing additional effects.  Any research provided by the community will get it implemented faster.  Thank you for reporting.
