### ISSUE TITLE
Arondight does not proc, tyvm.

### ISSUE THREAD

**Issue by Natchananananan** [EdenServer/community#1843]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by Natchananananan** [comment]
Arondight does not proc. ty.

**Comment by bkesecker** [comment]
Some research will go a long way to getting this implemented faster.  Thanks for the report.
