### ISSUE TITLE
Heavymail Djidzbad (dyna-beaucedine) loot table

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1845]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently, the NM Heavymail Djidzbad in Dynamis-Beaucedine appears to have a 100% drop rate on at least 1 piece of AF and a high (3/4) drop rate on 2 pieces of armor. His loot table should be the same as any other orc NM.

**Comment by Treble011** [comment]
He actually dropped 3 AF pieces tonight. Lol.

[http://i64.tinypic.com/25r0d3k.jpg](url)

**Comment by Serephim** [comment]
Well, to be fair, he is like 3-4X's harder than the other NMs so it's fair. XD
