### ISSUE TITLE
DRG Quest Unlock Bugged

### ISSUE THREAD

**Issue by Shika10** [EdenServer/community#1846]
### Checklist

- [yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [no ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [yes ] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0

I followed all the steps to unlock DRG all the way through beating Cyranuce M Cutauleon and choosing my wyvern name. I accidentally clicked on the tent to go into the battle again, but backed out of it. I now do not have DRG in my list of jobs and Rahal gives me the same commentary as if I had not beaten the dragon in Ghelsba Outpost. I have not tried beating the dragon again, but can when I have more time tomorrow.

**Comment by godmode** [comment]
Sometimes variables do not save like this in events. It's an uncommon issue but its good to double check before you go in and out. Variables not always saving is in process of potentially being fixed but it may be a few months out yet.

**Comment by Landruce** [comment]
version 30181205_0

Issue still not completely fixed. Just attempted this quest again today. Got through the cutscene, named the wyvern, and everything. Quest is flagged still, quest key item still in inventory, Job not unlocked.
