### ISSUE TITLE
Behemoth's Domain Light Elementals

### ISSUE THREAD

**Issue by Tristin42** [EdenServer/community#1847]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

Hi! Real simple bug, the Weather in Behemoth's Domain can't be anything else other than thunder weather. It's supposed to also be Light Weather. I've been farming Behemoths Domain for a very long time, not once has there been a light elemental here, even when Qufim and the tower have light weather. 

Thank you.

**Comment by setsuk0** [comment]
This is not true. I farmed 59 light clusters in behemoth's dominion in June in a single light weather. It's just super rare.

**Comment by godmode** [comment]
Closing this ticket. If you have more data on weather statistics in Behemoth's Dominion please post links here.
