### ISSUE TITLE
[NM] Pahh the Gullcaller placeholders are incorrect

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#1848]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

The NM "Pahh the Gullcaller" may have incorrect placeholders.  I have spawned this NM four times and it only ever seems to spawn off the nearby "Swamp Sahagin".  According to [this wiki page from Oct 2007](https://ffxiclopedia.fandom.com/wiki/Pahh_the_Gullcaller?oldid=368835) it should be a lottery spawn off the Sahagins in that area.  Now on Eden there are 6 Sahagins in that area: 4 Bog, 1 Swamp (the apparent only PH), 1 Marsh Sahagin.  According to the [DSP file on this zone](https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Sea_Serpent_Grotto/IDs.lua) there is only the one PH and the coordinates (-13.532 21.301 -20.861) are exactly where this one Swamp Sahagin spawns (as per the ibar) plugin.  This should be fixed so that all six of the sahagins in the area are placeholders.  

Oh and his Call Wyvern ability is totally broken.  He does the 2h animation but a wyvern never shows up.  IDK what you want to do about that.  **Edit: Mouu the Waverider and Zugg the Shoreleaper have the same 2h and it actually works and summons the Sahagin's Wyvern.  Might look to those two NMs for why.**

Thank you.

ver: 30181205_0

**Comment by bkesecker** [comment]
Thanks for reporting.  I resolved a similar issue recently with another set of placeholder spawns.  Hopefully that speeds up a fix for this one.

**Comment by greyenvy** [comment]
Thanks.  You may want to see my issues on Sozu Bliberry and Celeste-Eyed Tozberry as well.  They have similar problems that I’ve documented in those reports.

**Comment by Eme-FFXI** [comment]
can confirm it only spawn off the swamp sahagin. Killed it 8 times with TH3 and no spear drop... normal drop rate according to ffxidb is aroudn 60%. Might be very bad luck yes, but maybe can look into it? (got 1 Siren's hair tho)

**Comment by greyenvy** [comment]
I recently discovered it will spawn of either of the nearby Swamp Sahagins.  But still only those two mobs, which is still incorrect.

**Comment by Eme-FFXI** [comment]
Can confirm spawns also from Swamp Sahagin a little north.

Also, 0/15 on the Calamar with TH3, seems very odd for an item that drops 64% (http://www.ffxidb.com/items/16882)
