### ISSUE TITLE
Sneak/invis duration

### ISSUE THREAD

**Issue by nevxi** [EdenServer/community#1849]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently sneak and invis duration is scaled down when cast on a player below level 20/25.  This was not accurate to retail.  Spells like haste were scaled by level however sneak and invisible never were.  I Attached a few photos from alakazham forums from 2005 where you can see players posting that they were able to run through sea serpent grotto at level 1 using just a few oils and a post with someone asking about spell duration rumours

![91FCC27C-C2E0-4E35-9F76-5E0C81D8711A](https://user-images.githubusercontent.com/52473886/60554063-c2c62280-9cfb-11e9-8f1d-a3512f9b2de4.png)
![391FDE22-588F-49C0-B3BD-4AFB2CB38216](https://user-images.githubusercontent.com/52473886/60554064-c2c62280-9cfb-11e9-9f66-15170ceb6f55.png)

**Comment by godmode** [comment]
I know invisible and sneak as a spell were. I am unsure about items--if you have more data please provide.

**Comment by nevxi** [comment]
[image1.png]

I could be wrong about the spells and unfortunately information from this era is very hard to narrow down.   A common strategy for many things such as spells, mog locker, and some quests was to take a level one job to limit the xp loss.  I added a post from Corsair job quest since this was a very common strategy for this quest back in 75 era and one of the few things I could think of where I could find an example of people using sneak and invis at level one.   This would not have been a possible strategy if durations wore virtually instantly.

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
