### ISSUE TITLE
Ifrits C. Mining only has 1 node?

### ISSUE THREAD

**Issue by chlorr** [EdenServer/community#185]
went to do some mining in ifrits cauldron and ive gone through the pathing a few times and theres only 1 node up on the whole path, and ofc its the hell room.

Would love to know if its 1 at a time in that hell hole now, or if its a bug and there should be more up

**Comment by Wiggo32** [comment]
there's supposed to be 6. we're looking into the issue.

**Comment by chlorr** [comment]
thanks! the only one up is on map 8 H-11 atm.

**Comment by Wiggo32** [comment]
all 6 points are working fine.
