### ISSUE TITLE
Mobs go unclaimed despite having people alive/on threat list

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#1850]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

(version 30181205_0)

### Details

King Behemoth went unclaimed and was claimed by others while being kited and while having people still alive on the threat table. Dabeast had provoked King Behemoth and can be seen in video still kiting when KB had claim taken by another linkshell. Claim should not be lost until everyone on threat table is dead. 

Edit: fixed title since we found that this can be replicated on any mob, not just KB.
Edit 2: Added reproducable steps to a later post. See below.

**Comment by setsuk0** [comment]
https://www.twitch.tv/videos/447545556

This is from the other linkshell's stream, for a different point of view on the fight. Skip to 1:06 ish and you can see Dabeast still alive and trying to kite after having provoked. However some where down the line it changed claim.

**Comment by hienlongli** [comment]
here is the video I captured that may help in this report. Around 7:15 for when behemoth goes unclaimed/reclaimed. https://vimeo.com/345943497

**Comment by ultimazero** [comment]
Provoke has 1 point of cumulative and I don't see him near KB when claim falls. Looks like there is probably a minimum threshold of threat (similar to retail) so if he voked near the beginning and then didn't do an action for awhile while the other tanks all died to meteor that volatile enmity would fall off and the 1 CE probably isn't enough to keep threat. 

Nothing looked out of Era from the video. Looks like he was either on WAR or SAM/WAR? Not a ton of cumulative enmity there.

**Comment by ultimazero** [comment]
Here is some info on how losing claim happens in era/retail:

http://forum.square-enix.com/ffxi/archive/index.php/t-8954.html?s=6b59fc860199abacc850525c76435892

**Comment by ultimazero** [comment]
Also, the only frustrating thing in retail about keeping claim was BST charming pets would make you lose claim. However, that has been a huge QOL change on Eden that enables BST to solo alot easier and not worry about people stealing claim.

Our LS and SpoonDaggers hasn't had an issue of losing claim to anything but we also haven't been dying to things.

**Comment by setsuk0** [comment]
Dabeast had hate and continued to kite for some time after your LS claimed it. He was never over 50 yalms, so from our end it does not make since for it to go white. In that situation, KB was teleporting across our screens with everyone at R2500+. Our tanks were running into characters they couldn't see since not everyone was loaded/visible and not everyone ran out of the way.  There was a player intentionally standing in our kiters' paths. That's also not going to help things. After our experience, SD was able to have a plan to approach KB in combination with the lag, which included having everyone stand still except for the tanks. It's a live and learn situation, but it still does not make sense for KB to continue chasing Dabeast but lose claim.

**Comment by Mozzy4Ever** [comment]
> Also, the only frustrating thing in retail about keeping claim was BST charming pets would make you lose claim. However, that has been a huge QOL change on Eden that enables BST to solo alot easier and not worry about people stealing claim.
> 
> Our LS and SpoonDaggers hasn't had an issue of losing claim to anything but we also haven't been dying to things.

There are two tables. Enmity (which has VE and CE), and hate. For a mob to go white, all members must be off of the enmity list. You can do this by doing things like logging out, changing zones, or dying. If you are at the top of the enmity list while still logged out, in another zone, or dead and the mob tries to attack you, then your enmity list for that mob is deleted. Doing these 3 things also removes you from the hate list. You can be the top of the enmity list but if you're not on the hate list, the mob won't go after you until everyone currently on the hate list is cleared (typically via death). This is why if you zone a mob after having top threat (clears you from hate list but not enmity) while a 2nd person in your party is fighting it, the mob will turn to that 2nd person. If you zone back in and your party member dies (or you still have top threat) the mob will be chasing after you.

In both this scenario and the instance of SD losing claim to LD on LoO, neither hate not emnity lists were cleared.

**Comment by ultimazero** [comment]
> Our tanks were running into characters they couldn't see since not everyone was loaded/visible and not everyone ran out of the way. There was a player intentionally standing in our kiters' paths. That's also not going to help things.

Not a part of this bug report discussion but please send me proof of this claim. Anyone who is intentionally greifing (including calling for help on monsters) is instantly kicked from our linkshell because we aren't 12.

> Apparently something similar happened to SD on Sunday at LoO as well where the tank D/C'd but other players were still alive and getting beat on. But I wasn't there. I only heard about that claim issue from SD members.

I wasn't there as well but the primary person kiting LoO around D/C'd which made him go white. Fair game if the other people aren't helping because they are AFK at where he spawns while they kite it around the zone.

**Comment by Blex64** [comment]
> It doesn't matter the quantity of CE btw. If you have only 1, you still have claim.

This is not correct and never has been. I don't know if there is hard data on _precisely_ how claim works, but maintaining claim has more to do with who last acted on the monster than someone being on the hate list. For example, if you're the last person to act on a monster and then drop your party, you retain the claim and the rest of the party can no longer act.  

The same is true for going white. I imagine that the way it works is if X number of people who have acted last (with X being pretty much completely unknown as far as I'm aware) die/zone/leave the party, the monster goes white if nobody has acted on it within a certain time period. Considering about a dozen people died at once (maybe more?) that is almost certainly what happened here. None of the logs I've seen show Dabeast doing anything to KB for quite some time before or after the Meteor, so the fact that KB is chasing him at that time is irrelevant.

**Comment by Mozzy4Ever** [comment]
> > It doesn't matter the quantity of CE btw. If you have only 1, you still have claim.
> 
> This is not correct and never has been. I don't know if there is hard data on _precisely_ how claim works, but maintaining claim has more to do with who last acted on the monster than someone being on the hate list. 
> 
I failed to edit that portion of my comment when I finished my testing (See Edit2). I verified that whether or not the mob is claimed is based on the hate list. If you were the last to interact with the mob, you would be at the top of the hate list. That's why if you were last actor and you leave the party, you will have claim. This isn't a factor in this case though since the mob went WHITE. This is only possible if the hate list is empty, which is not naturally possible in this instance because the person who originally claimed the monster did not do any of the actions that would remove themselves from the hate list.

>The same is true for going white. I imagine that the way it works is if X number of people who have acted last (with X being pretty much completely unknown as far as I'm aware) die/zone/leave the party, the monster goes white if nobody has acted on it within a certain time period. Considering about a dozen people died at once (maybe more?) that is almost certainly what happened here. None of the logs I've seen show Dabeast doing anything to KB for quite some time before or after the Meteor, so the fact that KB is chasing him at that time is irrelevant.

This is not true whatsoever. This is exactly why there is a rule about not holding a NM for longer than 5 minutes. Once you act on the mob, you will have claim forever unless you die, zone, or logout. You can test this yourself by performing an action against a mob to claim it, and just going AFK. You'll still have claim even if you go AFK for an hour (like I did when I tested this).

I did do a bit of further testing and found that if the last actor on the mob dies AND home points (ie: zones), then the mob will go white. I had 2 characters in a party. 1st char voked the unclaimed mob. I then waited about 5 minutes (even though only 30 is necessary for all of Provoke's VE to deteriorate)  and cast Dia on the mob with the 2nd char. I let the 2nd char die to the mob's AoE, and home pointed it. At that point, the mob went white even though the 1st char never performed any of the actions that would remove it from the hate list. This should have resulted in 1st char retaining claim to the mob. While this could be applicable to this bug report's instance, it's extremely unlikely since the second Meteor finished casting it went white.  I see no way that someone could home point in that time frame.

**Comment by setsuk0** [comment]
Duration of time since last action is not a factor in the mob turning white. I was able to replicate this issue multiple times tonight. 

To test, I gravity'd a mob with my BLM and performed some actions (elegy/lullaby) on BRD. I then warp 2'd my BRD. The mob went white and continued to attack my BLM.

I tried this again, same steps only I pulled hate on BRD, let the mob kill BRD, and home pointed. The mob went white and continued to attack my BLM. I replicated this a couple of times, and the mob going unclaimed occurs each time.

I did this again with a friend in LS. I used BLM to use cure spells. I used BRD to do direct actions on the mob. Sanzio casted multiple spells, pulled hate, died, homepointed, and the mob went unclaimed. It then beat on BRD. I warped BRD. It turned to my BLM which had only used cure spells and beat on my BLM. (Just outlining everything here)

Additionally I did this to a lightning elemental. I casted on it with BLM, hit it with a sword on BRD and casted elegy/finale, and then warp 2'd my BRD. It went unclaimed but continued attacking my BLM. An outside alliance THF (thanks Hunny for helping) claimed the elemental then used hide. The outside THF maintained claim, but the elemental continued attacking my BLM. My BLM could not attack the mob, received the "target is claimed" msg, but kept having spells cast on him by the elemental.

**Comment by Blex64** [comment]
> Once you act on the mob, you will have claim forever unless you die,

Yes. 

Which is exactly what happened.

**Comment by Mozzy4Ever** [comment]
> > Once you act on the mob, you will have claim forever unless you die,
> 
> Yes.
> 
> Which is exactly what happened.

That is obviously not what happened

**Comment by Mozzy4Ever** [comment]
Update: Happened at most recent KB (~0010 EST on 8 Dec) again. Lots of extra lag being caused by other players moving around. Caused KC to lose several people. Saw at least 1 of them home point which in my above testing was found to cause this to happen.

**Comment by KnowOne134** [comment]
all new claiming code installed now, open a new issue with details if reoccurs
