### ISSUE TITLE
Sozu Sarberry spawn conditions and gil drop rate

### ISSUE THREAD

**Issue by him911** [EdenServer/community#1851]
### Checklist

- [yes] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [yes] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [yes] I have provided my client version in the details. (type /ver into your game window)

### Details
please fix it. I was told before camping it that its in a horrible state at the moment and after 1 week of camping i have to say its just broken.  I can spawn sozu rogberry 10 times in the time sarberry pops once

**Comment by mlandrum22** [comment]
I wouldn't be surprised to hear his spawn % is tied to the current retail 5 minute pop time and not the era 16 minute.

**Comment by greyenvy** [comment]
I have actually had the opposite experience with Sozu Sarberry.  However I don't "camp" in the sense of only being at Temple for him.  I will kill the Cutter PH and then go and do something else for 16-20 minutes, then kill the PH again.  It has never taken more than an hour for me to pop him in this manner and I have maybe 5 kills under my belt now.  

What @mlandrum22 said may be accurate however.  Pop rates on pretty much all the Tonberry seem pretty bad with the exception of Rogberry which always seems to pop within the 1-8 hour window based on reports on LS mates.  I have camped Tozberry as well and it is the same problem.  Never gave Janberry the college try but have killed it as well.

**Comment by him911** [comment]
Yes, it can pop in its regular spawn window but it can also go well beyond if you camp it everyday.  On two days it has exceeded 7-8  hours with no pop, killing ph every 16 mins

**Comment by greyenvy** [comment]
This is actually a problem with several NMs that just have on placeholder.  Extensive camping of two others on this server (Tozberry and Gullcaller) have done the same to me.  Well over 6h on at least one occasion for both NMs.  The problem with the ones I named however are they are improperly implemented and are actually lotto spawns from several placeholders.  Not sure how to solve the Sarberry problem without just flat increasing the percentage to spawn over time.  Right now it probably acts a lot like Rogberry I'd imagine and that can take well over 8h to spawn too.

**Comment by mlandrum22** [comment]
I've camped it for ~38 hours, and got it to spawn 9 times. 

https://ffxiclopedia.fandom.com/wiki/Sozu_Sarberry?oldid=401062

Assuming the max time should be 7 hours and the first spawn can happen 45 minutes in, we should be seeing Sozu ~17% of the spawns which is about 1/6. This would set the mean closer to 2 hours 20 minutes, not the 4+ hours that I'm seeing.

**Comment by him911** [comment]
Bump. His loot list and gil drop rate are also innacurate. 
All records show a minimum of 3000 gil dropped when solo'd and atm he drops 64~ gil
He's also not dropping dried mugwort at all
This is based on 30-40 TH3 kills so far. still no hocho :(  , plenty of tonko and hojo scrolls as well as shurikens 

![sarberry](https://user-images.githubusercontent.com/50463084/61186939-72947c00-a67c-11e9-9b22-42aa0c4f2d5c.png)

**Comment by him911** [comment]
Sozu sarberry should be dropping more than 64 gil per kill

**Comment by mlandrum22** [comment]
It still seems to have too high a spawn time. I've camped for over 12 hours today with just 1 pop.

**Comment by mlandrum22** [comment]
Another 8+ hour spawn. It should never take longer than 7 yet it routinely takes longer than 8. This is now the 5th time (i've killed him 27 times) it's taken at least 8 hours to pop. 

I've also never seen it pop within 2 hours of it's last kill (although I've only tried to double pop him 10 or so times due to it taking so long to pop him the first time so often)
