### ISSUE TITLE
Journey Abroad Sandy 2-3 Mythril Sand 

### ISSUE THREAD

**Issue by Cyclohexene1** [EdenServer/community#1853]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (Version: 30181205_0)

### Details

Character: Saga
Version: 30181205_0
Sandy Mission 2-3: Journey Abroad (Journey to Bastok)
I have talked to Savae, then Pius, then Ghrom. Ghrom does not provide pick axes nor a CS. 
I attempted to trade Mythril Sand to Savae. I've tried logging out, zoning, and changing jobs. I've re-downloaded the game.

**Comment by godmode** [comment]
Please place a GM ticket and reference ticket #1853
