### ISSUE TITLE
Issues with Fomor Groups in Lufaise Meadows

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/community#1855]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Tower Group (!pos -129 -24 2)

- Beastmaster may not summon pet under certain conditions, or at all

Day Group (!pos 197 -23 345)

- 16875669 BLM (casted Tornado?)
- 16875668 DRK
- 16875672 DRK
- 16875678 DRK

Night Group (!pos 197 -23 345) Day Group also present

- RETAIL VERIFICATION NEEDED: There are ~10 Fomor here in one place
- RETAIL VERIFICATION NEEDED: These are past the IT-to-75 mobs, and I think should be IT as well
- BROKEN: Fomor ranger does not animate when shooting
- BROKEN: Beastmasters and Dragoon may not summon pets under certain conditions, or at all
- OK: Summoner does resummons pet eventually if the pet dies
- OK: Summoner's pet dies when master is defeated

Night Group on Path (!pos 226 -22 267)

- RETAIL VERIFICATION NEEDED: These just seem out of place and clump together
- RETAIL VERIFICATION NEEDED: These are past the IT-to-75 mobs, and I think should be IT as well

```SQL
USE dspdb;
SELECT * FROM mob_spawn_points WHERE groupid IN (571,574,581) AND mobname LIKE 'Fomor%'; -- Dragoon, Summoner, Beastmaster
SELECT * FROM mob_spawn_points WHERE groupid IN (582,583,584); -- Their corresponding pets
```

**Comment by 59blargedy** [comment]
all resolved May 31, 2020 except mob group numbers - much like monastic cavern, all mobs currently spawn at top of hill instead of in specific groupings

**Comment by 59blargedy** [comment]
Resolved by another dev in February 20, 2023 update
