### ISSUE TITLE
Magicite 4-1 to Rank 5 Bugged

### ISSUE THREAD

**Issue by YucaXI** [EdenServer/community#1856]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Hello,

Chr Name: Yuca
San Dorian 4-1

Received all the key items from each magicite, talked ot the arch duke of jeuno, got the cut scene, turned in the magicite, got the airship pass, went to san dorian embassay....tells me to go back to the arch duke palace...when I do the guards turn me away.

Version 
30181205_0

**Comment by godmode** [comment]
Please place a GM ticket and reference ticket number 1856
