### ISSUE TITLE
Certain Yagudo not dropping 13-knot Quipi

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#1858]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Yagudo Interrogator (groupid 8109, dropid 4254)  and Heralds (group id 8106, dropid 4239) are supposed to drop the Thirteen-Knot Quipi (Item ID: 1535). in mob_droplist.sql that itemID is currently only assigned to dropID 4233:

![image](https://user-images.githubusercontent.com/11255886/60733015-460c9180-9f11-11e9-89e9-0bfda21e6a38.png)

In mob_groups.sql the only groupID with that dropID is 8104, which only has Yagudo Drummers:

![image](https://user-images.githubusercontent.com/11255886/60734038-2c207e00-9f14-11e9-8c82-896e388fd6d8.png)

![image](https://user-images.githubusercontent.com/11255886/60733319-1c079f00-9f12-11e9-8992-42ec5c1fb60e.png)

Solution = Run the following:

insert into mob_droplist (dropid, dropType, groupID, groupRate, itemId, itemRate)
VALUES ('4254', '0', '0', '1000', '1535', '50');

insert into mob_droplist (dropid, dropType, groupID, groupRate, itemId, itemRate)
VALUES ('4239', '0', '0', '1000', '1535', '50');

**Comment by godmode** [comment]
Thanks for the leg work!
