### ISSUE TITLE
San d'Oria Mission 5-1 "The Ruins of Fei'Yin" Bugged

### ISSUE THREAD

**Issue by freddiepines** [EdenServer/community#1859]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

Client version 30181205_0.

After accepting the mission from Halver and receiving the key item "New Fei'Yin Seal" I cannot advance the mission further.  No cutscene when zoning into Fei'Yin, no battlefield selectable at Qu'Bia Arena.  Both my alt account and the other person I was with were able to advance the mission and received a cutscene on zoning into Fei'Yin but I did not.  I've tried relogging, rezoning, talking to Halver again multiple times, nothing has worked.

Submitted a GM ticket yesterday as well.  Thanks.

**Comment by bkesecker** [comment]
Was this resolved by GM?  If so, please close.

**Comment by freddiepines** [comment]
Was resolved by GM.  Thanks.
