### ISSUE TITLE
King Vinegarroon drop rate off?

### ISSUE THREAD

**Issue by superform1** [EdenServer/community#1861]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by superform1** [comment]
version 30181205_0
I have been camping King Vinegarroon for two weeks+, have killed him six times with TH2 or TH3 each time, and have heard of two other kills. Ace's helm dropped 0/8, Heavy shell dropped 2/8, and Venemous claw dropped 0/8 as well. 

I believe that Ace's helm drop rate is wrong at the moment, and is supposed to be around a 43% drop rate. 
I believe that the drop rate on the Heavy shell appears to be accurate. 
And I am not sure if the drop rate on venomous claw is accurate at the moment.

**Comment by Raphtalia1** [comment]
Anecdotally the helm should be roughly 25% drop rate without treasure hunter, the claw should be nearly 50% with a chance of multiple dropping

I helped kill KV a couple dozen times back in retail and with TH4 we got helms from about half of them, and claws (sometimes multiple) from nearly all of them

**Comment by godmode** [comment]
The drop rate looks to be correct. Please continue to keep records of the drop rates if you feel it is still off.

**Comment by superform1** [comment]
Have killed two more times, both times dropping Ace's helm; will continue to watch.  -Thank you
