### ISSUE TITLE
Windurst M7-1 - Tosuka-Porika gives no cutscene or dialogue

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#1862]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

Version: 30181205_0
### Details

I started Windurst Mission 7-1 on both of my characters. The next step is to talk to Tosuka-Porika in WWaters. I received the cutscene right away on my second character. However, on my main, I was only given the dialogue to start the quest "Early Bird Catches the Worm." I completed this quest and talked to Tosuka-Porika again. He gives me no dialogue now when I talk to him. I tried zoning out and relogging, but this did not help. I am supposed to get a cutscene and a temporary key item (optistery ring) in order to continue the mission, but I am unable to progress now. 

https://ffxiclopedia.fandom.com/wiki/The_Sixth_Ministry

Edit: A GM was able to fix this for me. Thanks, Nibbler.

**Comment by Volkaru** [comment]
Re-opening. Confirming this is still an issue. GM fixing is a nice work-around. But please leave open until the issue itself is actually fixed. 
Personally tried everything from zoning to logging off, he never gives the 7-1 cutscene or the KI to me.

**Comment by Volkaru** [comment]
Adding onto that he also will not let me finish mission 7-1. 
I killed the hinge oils and got the CS in Toraimorai. Had to run back to Tosuka-Porika to get the last CS to finish the mission and a KI... He's not reacting at all. Just referencing the quest Early Bird Catches the Bookworm.

**Comment by Volkaru** [comment]
Update: After finishing the quests Early Bird Catches the Bookworm and then Chasing Tales I was able to get the proper CS to finish the mission. However, doing those took an extra hour I shouldn't have needed to do.

**Comment by waffleness** [comment]
The quest Hat in Hand also interferes with this mission. Icarum ran into this issue and was unable to get the Key Item from Tosuka. Had him complete the quest and he was able to proceed.

**Comment by marlinla** [comment]
Tosuka for Hat in Hand first gives the hat quest dialog. Then no dialog at all, blocking obtaining the Key item for the mission. Completing the hat quest clears the block.

**Comment by 59blargedy** [comment]
resolved in April 19, 2021 update
