### ISSUE TITLE
Quests not consuming items

### ISSUE THREAD

**Issue by Kythaela** [EdenServer/community#1864]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Kythaela** [comment]
Less of a hindrance really but i noticed when i completed the Aspir Scroll quest that it had not consumed my Test Answers Rare item. Similar thing happened with the Chocobilious quests and Papaka Grass.

**Comment by Shoruto** [comment]
#1378 - Test Answers Not Being Consumed

**Comment by KnowOne134** [comment]
Has been fixed
