### ISSUE TITLE
Chocobo "Dismount" command is missing from the targeted mob menu.

### ISSUE THREAD

**Issue by Apocalypse612** [EdenServer/community#1865]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
The menu command "Dismount", while on a chocobo, is missing from the menu list while you have a mob targeted. It's there only if you have nothing selected, but it should still be present even if you select a Mob or other NPC.

**Comment by KnowOne134** [comment]
doesnt seem the case
i remember that if you used attack it would auto mismount and go into attack mode
![image](https://github.com/EdenServer/community/assets/35616771/99083490-4c19-40c1-bd2e-27570e56b0e3)
