### ISSUE TITLE
Synthesis Level - Jaridah/Akinji feet/leg

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#1866]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Subcraft level requirements for
https://www.edenxi.com/db/items/15605/ and
https://www.edenxi.com/db/items/15689/
seem off.

Every gear set synth I can think of usually requires the highest Craft/Subcraft levels for the body piece. In this case the Set-Body's requirement is much lower than feet and legs.
https://www.edenxi.com/db/items/14526/

FFXI-Wiki shows legs subcraft levels @34/35 instead of 53/35
https://ffxiclopedia.fandom.com/wiki/Akinji_Salvars

I dare assume that a similar requirement is need for feet synthesis, with subcrafts between 30-40.

**Comment by statuseffect** [comment]
Jaridah/Akinji Feet have an incorrect clothcraft sub in the Eden database, as the Eden Website states it as a 54 Cloth sub on the Crafting drop down, when it should be a 28 Cloth sub,
![image](https://user-images.githubusercontent.com/62901732/162578816-439d1cd0-6109-44c8-a686-da62ad371331.png)
![image](https://user-images.githubusercontent.com/62901732/162578902-435cc357-8488-4b5b-b2da-278d3751efb1.png)

**Comment by bliven-was-taken** [comment]
Confirmed on retail I couldn't attempt synth at 39/12/0 and I could attempt synth at 39/12/1 so the clothscraft level is 100% lvl 28, the smithing is 66 or below, and the leathercraft is 39 or below, so the levels on FFXIclopedia seem to be correct.
