### ISSUE TITLE
Alchemy Guild Rep will not accept requested items

### ISSUE THREAD

**Issue by rpcon** [EdenServer/community#1867]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30190430_0

1. Craft wax swords.
2. Trade wax swords to the alchemy guild rep.
3. No points are awarded, and no items are removed from inventory.

Zoning, changing jobs, rebooting all have no effect.

**Comment by 59blargedy** [comment]
my guess is this was a result of getting rankup same day, or was when the hq wouldnt accept nq, but can reopen if this happens for other players.
