### ISSUE TITLE
Mobs that should rage but dont

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#1868]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
I'm using the wiki page on rage to compile the list, but there is contradicting information in regards to when some of these creatures rage when looking at the history for the specific NM.  So, in the cases I find a discrepancy I'll be posting a link directly to that monsters history and / or discussion page.

Please comment if something is missing / incorrect.

https://ffxiclopedia.fandom.com/wiki/Rage?oldid=376160

King Arthro 
20 Minutes

Simurgh 
20 Minutes

Roc 
20 Minutes

Serket 
20 Minutes

Capricious Cassie (There is evidence this should be a 30 min rage, not 20 min.  See linked discussion)
https://ffxiclopedia.fandom.com/wiki/Talk:Capricious_Cassie
20 or 30 Minutes

Lord of Onzozo 
20 Minutes

Behemoth 
https://ffxiclopedia.fandom.com/wiki/Behemoth?oldid=397487
30 Minutes

King Behemoth 
60 Minutes

Adamantoise 
60 Minutes

Aspidochelone 
60 Minutes

Fafnir 
60 Minutes

Nidhogg 
60 Minutes

**Comment by HunnyDoo** [comment]
Just to piggyback on the topic of mob tweaks. Cassie and Lord of Onzozo don't use draw-in.  Cassie also might not use Drain Whip but I'm unsure of that. Cassie and Manipulator drop incorrect amount of gil (based on wiki).

**Comment by CurzonEden** [comment]
I've witnessed: Simurgh, Serket, Lord of Onzozo all enter there enraged state before.  However I do think there is an issue with how rages cooldown is being applied.  In era It should require the mob to go unclaimed and regen to 100% hp.  This was later changed by SE however I believe sometime in  mid 2009 to only require the mob to go unclaimed and regen 1 tic of hp. Currently Eden's rage is using the latter, admittedly I've only witnessed this once.

**Comment by Serephim** [comment]
Can confirmed, Sim, Serket, Cassie and LoO all currently enrage. I've seen it happen when people try to hold them. Not sure about Roc. HNMs all do not enrage at all. 
(Really Adamantoise is 60 minutes? I can duo him in like 5 minutes. Seems excessive Square Enix. lol)

**Comment by raventn** [comment]
all hnm's should have rage like retail.

**Comment by KnowOne134** [comment]
all mobs listed have rage set
