### ISSUE TITLE
Gusgen Mines NMs do not spawn/exist at all!

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#1877]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

The following Notorious Monsters do not spawn in Gusgen Mines.  They are supposed to spawn when the sirens ring at the locations noted on their wiki page but they do not.  I have been there two times and have noticed that not only do they not spawn but the siren always rings at 2:00 gametime. It should ring once randomly at 0:00, 1:00, or 2:00 and not be just one set time (only two observations of this so not sure if it only ringing **only** at 2:00 is 100% accurate but I am fairly certain it is.):

- [Asphyxiated Amsel](https://ffxiclopedia.fandom.com/wiki/Asphyxiated_Amsel)
- [Burned Bergmann](https://ffxiclopedia.fandom.com/wiki/Burned_Bergmann)
- [Crushed Krause](https://ffxiclopedia.fandom.com/wiki/Crushed_Krause)
- [Pulverized Pfeffer](https://ffxiclopedia.fandom.com/wiki/Pulverized_Pfeffer)
- [Smothered Schmidt](https://ffxiclopedia.fandom.com/wiki/Smothered_Schmidt)
- [Wounded Wurfel](https://ffxiclopedia.fandom.com/wiki/Wounded_Wurfel)

If someone has actually seen these NMs please let me know.  There is no AH for any of the Mal* Rings, which suggests that they have never been killed because they have never existed.

/ver: 30181205_0

**Comment by MonkeyAce9** [comment]
I have been farming in Gusgen Mines for the past few weeks and I can confirm 100% that the siren does indeed always go off at 02:00 every day. I didn't know the NMs didn't spawn though.

**Comment by 59blargedy** [comment]
resolved in May 3, 2023 update
