### ISSUE TITLE
Sauromague Champaign Goblin's Beetles drop wings/shells/jaws

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#1879]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The Goblin Beetles here (Pets of Goblin Pathfinder) are dropping beetle items.  Beastmaster pets should only ever drop crystals and beastman/kindred seals (depending on lvl).

**Comment by OverTheNeptune** [comment]
The Goblin's Bees in Rolanberry field are also dropping typical bee drops.

**Comment by roriffxi** [comment]
I'd wager the fly pets in battalia downs are the same

**Comment by bkesecker** [comment]
Sounds like this should fall under a full audit of pets, such that none can drop items.  Should any pet drop items?

**Comment by OverTheNeptune** [comment]
Goblin's Bees in Yhoator Jungle are also dropping bee-related loot. This includes bees that assist both the Goblin Pathfinders and the Goblin Traders.

Goblin's Gallinipper in Attohwa Chasm don't appear to drop items. I did a few levels on rdm there and only got beastman seals and crystals.

It's been awhile, but I've also done a little pet exping on Goblin's Leeches in Gustav Tunnel, Goblin's Rarabs in Bibiki Bay, and Goblin's Bats in Newton Movalpolos. I don't remember seeing any items drop from these except for the coffer key in Netwon Movalpolos and that dropped in retail.
