### ISSUE TITLE
BST AF weapon bugged

### ISSUE THREAD

**Issue by rpcon** [EdenServer/community#1881]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Got the quest Wings of Gold, switched to thief, used a skeleton key on the chest and there was a message in the log indicating it had been opened but nothing happened.
https://imgur.com/a/1AtkHyt

Edit: after getting the key and using it on the chest, it opened correctly and I received the KI.

**Comment by bkesecker** [comment]
Just to clarify, the bug may be that skeleton key use results in no key item acquisition for BST AF weapon quest?

**Comment by rpcon** [comment]
I tried a skeleton key on the Horutoto chest yesterday and got the same result. It's bugged and doesn't pop the chest.

**Comment by bkesecker** [comment]
Thanks.  Bug is that a skeleton key was used.  Sounds like an audit of all chests that could be opened with skeleton key is needed.

**Comment by bkesecker** [comment]
Perhaps Skeleton keys only work on treasure chests, not coffers.  "Note: no effect if used on a brown Treasure Coffer."
