### ISSUE TITLE
Cannonball (Blue Magic)

### ISSUE THREAD

**Issue by zippern** [EdenServer/community#1882]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Verson 30181205_0
It can seem as the modifier defense are correctly applied to the spell.
After a few tries it seems like the spell does more or less the same damage or at least does not buff the spell to what it should be.

This tests have been done on too weak worms in "Eastern Altepa Desert" by using defense buffs and not using defence buffs with berserk to lower the defense even more.
I have not tested the STR or VIT modifiers since most of those are on my armor and will also change the defense stats, these may also be bugged but I can not say for sure.

whit Protect 4+Cocoon(Defense 550) Cannonball did 627 damage.
whitout any defense buff but berserk active(Defense 234) Cannonball did 645 damage.

I did not play BLU in retail so I can not say what it should be, but have been looking at old post from around this era and seems like people got it up to 3k damage without perfect gear.

Added three screenshots from the tests.
Zippa(BLU) does the spell, but I have added abit too much filters on her so she can't see the damage
Zippe is here to have the damage in the chat log.
[canon.zip](https://github.com/EdenServer/community/files/3389023/canon.zip)

**Comment by Serephim** [comment]
I played retail BLU and I agree the damage is super low on it cannonball and it needs to be buffed significantly but the 3K damage you hear about is on a mob with super low defense like Boreal Hound and such. Damage on normal monsters with defense with a perfect setup was no where near that high. Like 2K and change max with sneak attack.  1K-1500 were pretty average. But it's super hard to find video evidence.

**Comment by greyenvy** [comment]
Everything Seraphim just said is accurate.  I have no video data or hard evidence to follow however.  I just have a knack for remembering mundane bullshit from 15 years ago.

**Comment by xizeta** [comment]
We need damage numbers from era to balance this properly.
Please provide some data and we can get this implemented.

**Comment by Volkaru** [comment]
Here are multiple sources for BLU damage. And Cannonball damage.
BLU spell multiplier data. It looks accurate to era, with references for data: http://www.neko-sentai.com/images/BlumageNFO.htm
Here is a page showing some well-geared Cannonball damages on Dark Ixion and Cerberus
![ffxi20080718123531rv0](https://user-images.githubusercontent.com/9113384/72631767-b4db9600-3909-11ea-9c1a-76c2f6d33430.png)
: https://www.ffxiah.com/forum/topic/8645/cannonball-damage
Here are some other high-damage screenshots on NMs: https://www.ffxiah.com/screenshots/15219
https://www.ffxiah.com/screenshots/19125
Old guide  on heat breath vs. cannonball mentioning damage numbers: http://ffxi-eremes.blogspot.com/2009/07/cannonball-vs-heat-breath-analysis.html
Please let me know if you want more info. I found a lot in old BLU threads and BG's 'fapworthy' damage threads for the era.

**Comment by Lixion** [comment]
Gist posted at request of Godmode

https://gist.github.com/Lixion/ee93eb58434ea5188186671fd23ba035

**Comment by Lixion** [comment]
[bluemagic_new.lua.zip](https://github.com/EdenServer/community/files/4631089/bluemagic_new.lua.zip)

**Comment by Volkaru** [comment]
If anyone needs testers to implement this, I'd gladly help.
