### ISSUE TITLE
Most mamools don't use Warm-up

### ISSUE THREAD

**Issue by zippern** [EdenServer/community#1883]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0

It seems like Mamools don't use Warm-up.
After killing about 50 Mamools (Mamool Ja Bounder/Mamool Ja Mimicker/Mamool Ja Spearman) I have not seem them use Warm-up, it's possible I have had bad luck but from what I recall from retail when fighting them(also from "The Blue Mage Hunting Grounds") "Do Mamool Ja's like to use the move? Yes, they use it often."

I'm not sure how you can provide reproducable steps(also why I have not checked the box) other then go and fight them while feeding them tp. If I'm wrong great it works as it should I have just been unlucky.

Edit:
icariumkupo is right the nin(Mamool Ja Zenist) did use warm up.

**Comment by icariumkupo** [comment]
You might be right in that some are not using when they should be able to, but I was able to learn this spell from the NIN mamool in Wajaom near southern Mamook zone.

**Comment by Serephim** [comment]
Icarium is correct, that is where I learned it after trying a million times on other mobs. On the first mob too. lol

**Comment by 59blargedy** [comment]
resolved in February 8, 2021 update
