### ISSUE TITLE
Unable to communicate in Tu'Lia region. (Sky)

### ISSUE THREAD

**Issue by Iced-Latte** [EdenServer/community#1884]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

While in the Tu'Lia region, one cannot communicate with anyone outside of the region with either /tell, /yell, /linkshell. Those outside the region cannot see anyone chat inside and vice versa. This presents an issue for everyone I am sure when participating or gathering in sky events.

This is not an isolated issue, we have 12+ people in zone with the same exact symptoms. We tried relogging/resetting clients to no avail.

**Comment by KnowOne134** [comment]
Was a message server issue. Restarting fixes it
