### ISSUE TITLE
Sleep Bolt not working properly on Empty

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#1885]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

When you use a sleep bolt  on an empty in a promyvion it says that the sleep took affect, the but empty never falls asleep and the message of them waking up is never displayed in the chat either. I'm not sure if they are immune to sleep or not, they resisted Soporific and Sheep Song as well, but the bug I'm reporting is more that the log indicates it should be sleeping when in fact it never falls asleep and also never prints that it woke up.

IIRC I used to sleep these on Thief back in the day but I could be wrong.

Note: I was testing this on the first floor of Promyvion-Dem on the small models of the Wanderers and Weepers. Sorry for no screenshots.

Version: 30181205_0

**Comment by dowzer** [comment]
Video for reference, their affixed element determines their resistances

https://youtu.be/hT-EWgcC2cI

**Comment by E5una** [comment]
Opened https://github.com/EdenServer/community/issues/3273 for a related, but separate issue.

**Comment by KnowOne134** [comment]
Corrected 11/19 update
