### ISSUE TITLE
Demons not dropping Demon Skulls

### ISSUE THREAD

**Issue by Twentytwox** [EdenServer/community#1887]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver. 30282305_0

![Screenshot_20190715-090144_Chrome](https://user-images.githubusercontent.com/47615465/61218295-b5d40680-a6df-11e9-8c1e-8f7633904d1a.jpg)
![Screenshot_20190715-090320_Chrome](https://user-images.githubusercontent.com/47615465/61218297-b79dca00-a6df-11e9-91a0-8c51d0b7ff47.jpg)
![Screenshot_20190715-090336_Chrome](https://user-images.githubusercontent.com/47615465/61218302-bb315100-a6df-11e9-9cca-738d6de10a0a.jpg)

Drop rate on demon skulls from demons in u.range appears to be off. Killed Kindred demons for 2 hours with TH3 and not a single skull dropped.

**Comment by perkuprightmeow** [comment]
Can confirm, did this completely separately on Kindred Demons for a little over 2 hours and didn't get a single helm with TH3. 20+ kills.

**Comment by Mozzy4Ever** [comment]
Checked base DSP drop rates.

Below are drop rates for the mobs in Uleguerand Range:
Kindred Warrior (Group ID 146, dropid 1927): 5%
Kindred Dark Knight (Group ID 144, dropid 1905): 5%
Kindred Summoner (Group ID 145, dropid 1922): 3%

Those drop rates match http://www.ffxidb.com/items/886 as well. Those values you show in your picture are the average across the various kills when including the various TH. If you click on the dropping-monster's name, you can see what TH0 drop rate should be.

**Comment by Twentytwox** [comment]
I appreciate you looking into this. Is there a way the DSP rates would differ from the Eden rates? 4 hours with TH3 should produce at least one skull

**Comment by Mozzy4Ever** [comment]
I see no reason why the drop rates would be different than DSP's

**Comment by bkesecker** [comment]
Keep trying.  Even with TH on your side, the rate is slim.  Since it has been a while, just want to confirm someone has gotten the drop before closing.

**Comment by Twentytwox** [comment]
Can confirm someone did happen to get a demon skull to drop. Thanks for looking into it
