### ISSUE TITLE
Kung Fu Shoes

### ISSUE THREAD

**Issue by raventn** [EdenServer/community#1888]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
Cactuar Cantautor NM 
Area Western Altepa Desert
I know this item are suppose to be ingame but after many hours of farming and kill the nm
 so many times i start feeling this one is broken 0/20 with th2 and still wont drop its to me broken its not about luck here  i don think the items is even ingame?

Im pretty sure reports that people are 0/10 and even 0/40.

**Comment by Serephim** [comment]
I talked to JMCMorris about this and he said the drop rate is like 10%ish.
I don't believe that this NM is not broken. No one has ever got the drop from this NM in hundreds and hundreds of kills even dating back to the Kupo days. I myself killed it over 40 times.

**Comment by raventn** [comment]
yea if its 10% as it suppose to be but it could missing out on loot table ?

**Comment by Serephim** [comment]
He said it's on the loot table but the chances of it NEVER dropping at 10% in years is extremely low. lol

**Comment by raventn** [comment]
but even in retial it wasent super rare either ithink need fix it for sure for us mnks :D

**Comment by bkesecker** [comment]
Database files indicate that Cantautor should drop Kung Fu Shoes.  I could confirm the rate on Eden, but then it wouldn't be a mystery.

**Comment by raventn** [comment]
iknow its 10% drop rate but it seems stupidly it hasent drop months even years. like Serephim said people been 0/40 on it make zero sense

**Comment by Serephim** [comment]
There is most definitely something wrong with it if it has a lower drop frequency than defender ring which is already ungodly low. lol

**Comment by bkesecker** [comment]
Using latest code and DB, setting Cantautor's drop rate to 100% on Kung Fu Shoes, and then defeating it yielded a pair of Kung Fu Shoes.  Keep trying!

**Comment by Serephim** [comment]
Ok, now set it to 10% and see how long it takes for it to drop when it isn't 100%. lol
