### ISSUE TITLE
Certain Titles not unlocking for me.

### ISSUE THREAD

**Issue by Tristin42** [EdenServer/community#1889]
### Checklist
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Hi! So I contacted a GM about this a little bit ago, I have certain titles that aren't unlocking for me after completing certain objectives. I was wondering if there's something that can be done about this? I know it's minor, but the two main titles I noticed I DON'T have are my Dynamis-Bastok title, and the Master of Manipulation title for doing my limit break quest. Titles are very minor, but it's a small quality of life thing. I did check at the title changers that these should be available at as well.

**Comment by 59blargedy** [comment]
need more info/more recent reports, have not heard this to be an issue
