### ISSUE TITLE
Avatar Tuning Forks unable to be obtained

### ISSUE THREAD

**Issue by LokiStinkpalm** [EdenServer/community#189]
So i was running around getting the avatar tuning forks to do the primals again.......My main char could get them and my alt couldnt.  Both of my chars have the moon bauble in their possession so it cant be a fame thing (i maxed all fame before the move to eden on both chars).  I even waited a game day (or 7) in between trying to get them and it didnt work.  Any help is appreciated because im trying to get all the summons  >.>

**Comment by Lilswitche** [comment]
Double check fame on your other character.  It's been previously reported that others have seen their fame drop as a result of how fame is calculated differently.

**Comment by LokiStinkpalm** [comment]
Ok i will.  But i maxed fame on both chars before the switch over to Eden

**Comment by roriffxi** [comment]
It looks like fame checking on Kupo was done as a multiplier of your actual fame.  Rather than gaining at a faster rate, Kupo just credited you with a higher level than what you'd actually earned.

I had max fame in Kupo but here when I checked it in bastok I was only fame level 4.

**Comment by jmcmorris** [comment]
It could be that the fame levels on Kupo were just significantly lowered. Gaining fame in Kupo was extremely fast and nearly negated the fame system entirely.
