### ISSUE TITLE
Dynamis Jeuno - Statue on Balcony Now Pulls Whole House.

### ISSUE THREAD

**Issue by ultimazero** [EdenServer/community#1890]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)

### Details

When you pull the statue that is on the balcony now pulls the whole house no matter how you pull it, almost like it is in a party with the other statues way in the back. Never happened in any other dynamis jeuno run.

**Comment by godmode** [comment]
It didn’t do this in retail either?

**Comment by Raphtalia1** [comment]
No mention of any special behavior from that statue on the dynamisbums strategy page from way back

**Comment by godmode** [comment]
Then I imagine it links just like everything else.

**Comment by Mozzy4Ever** [comment]
> Then I imagine it links just like everything else.

There are several statues in various dynamis' that do this and aren't supposed to. I believe it has to do with the navmesh issues.

**Comment by falzum** [comment]
https://www.youtube.com/watch?v=TjzVlodVOl8

Video evidence that the balcony statue should not link.

**Comment by 59blargedy** [comment]
i'm not quite sure which one this ticket referred to, and if it is resolved, if someone that's around can comment i'd appreciate it.

**Comment by falzum** [comment]
This is still happening. If you try to run into the palace the balcony statue will aggro you from above. If I get a chance I'll try to download the line of sight stuff and tinker with it tomorrow

**Comment by 59blargedy** [comment]
had a couple folks try this on test and it no longer seems to be an issue
