### ISSUE TITLE
No CP received when trading extra crystals at same time as rank bar fillup

### ISSUE THREAD

**Issue by Spider-Dan** [EdenServer/community#1891]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

I have a Rank 4 character.  I traded enough earth crystals (approximately 3 stacks) to Arpevion to nearly fill up my rank bar, then traded 8 stacks of earth crystals so the excess would be converted into CP.  I had 51,640 CP prior to this trade.  The 8 stacks of crystals were accepted and removed from my inventory, but I received no additional CP.  I then attempted to trade a 9th stack of crystals (which was rejected) to verify that crystals are only accepted when you are below the limit for your rank.

![cp_crystals](https://user-images.githubusercontent.com/52397049/61266906-adfd7c00-a74a-11e9-9b8a-bc842f395d2a.png)

**Comment by Spider-Dan** [comment]
This happened again at the following rank.  Before/during/after trade screenshots are attached.
![1-before](https://user-images.githubusercontent.com/52397049/64132794-15b56800-cd87-11e9-9ce4-741c279bd091.png)
![2-during](https://user-images.githubusercontent.com/52397049/64132798-19e18580-cd87-11e9-9561-9b8a542c54f0.png)
![3-after](https://user-images.githubusercontent.com/52397049/64132799-1d750c80-cd87-11e9-9671-2f558920dffe.png)

**Comment by KnowOne134** [comment]
Unable to reproduce bug
