### ISSUE TITLE
Boreas cestis

### ISSUE THREAD

**Issue by itachioax** [EdenServer/community#1892]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Kirata not dropping Boreas cesti im 0/8 with TH3 its weird 
could any check this NM?
or anyone already got cesti before?

**Comment by AnkleAssassinz** [comment]
Posting to confirm the tiger nm does drop the lvl 30 cesti. Went  1/5 if i remember right.

**Comment by Mozzy4Ever** [comment]
8 kills is hardly a large sample size. I'll admit you do seem unlucky considering the drop rate should be ~24% with TH0

**Comment by bkesecker** [comment]
Has been a while, how goes the hunt?  Please close this issue if the drop was acquired.
