### ISSUE TITLE
Armour Bug

### ISSUE THREAD

**Issue by PsychedelicNPC** [EdenServer/community#1893]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
My in game name is Valthan.
I am having a bug that does not show another person's armor.
The only armour I see is everyone's starter set.
How do I fix this... it really takes away from the game.

**Comment by bkesecker** [comment]
Most likely DAT file missing or corrupt.  Reinstall might fix.  Don't uninstall, just reinstall.

**Comment by PsychedelicNPC** [comment]
I got it working
