### ISSUE TITLE
Geush Urvan

### ISSUE THREAD

**Issue by raventn** [EdenServer/community#1894]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details
Question is this working eden?

https://ffxiclopedia.fandom.com/wiki/Geush_Urvan?oldid=20171

Im pretty sure this is Era was even working back in 2005 tho not many had gear to kill this guy tho.
needed items is an  **Haunted Muleta** 
Spawned by trading a Haunted Muleta to the ??? at (K-7) in Uleguerand Range

Haunted Muleta
**witch is craft items**
Spectral Goldenrod = Haunt kuftal tunnel or Srei Ap Uleguerand Range
Spectral Crimson = From fomors rdm pld and brd  or Phasma
Yew lumber

**Comment by bkesecker** [comment]
The NM will spawn if the item is traded, not sure whether the drop table for the NM is accurate.

**Comment by raventn** [comment]
drop should be 100% tho since force pop since items to get crafting items are rare

**Comment by bkesecker** [comment]
Cool.  Pop it and drop it.  If no loot, let us know here.  Otherwise, please close this issue.

**Comment by raventn** [comment]
ok i need farm the mats from the monsters first then gona try it if works

**Comment by raventn** [comment]
> Cool. Pop it and drop it. If no loot, let us know here. Otherwise, please close this issue.

but would be good tho to know if the Geush Urvan even works here on Eden.

**Comment by bkesecker** [comment]
Investigating that it can be spawn was easy, whether it works or not is a bit more involved.  If you don't get the 100% drop item, make a GM call, and then it will be awarded.  Any findings you have on the battle itself, drop here to get investigated/fixed.

**Comment by rude-jerk** [comment]
Guesh Urvan is both spawnable and correctly has Toreador's Cape as a 100% drop.
