### ISSUE TITLE
Ranged Attack interupts

### ISSUE THREAD

**Issue by agjevik999** [EdenServer/community#1895]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version: 30181205_0

I never played retail since they introduced item sets, so maybe this is working as intended. If it is please close this report.

I have my macro set up so that my macro that starts a ranged attack also equips a set with racc. It seems that this bug only happens when the equipment swap results in a "blink". When that blink happend your ranged attack gets interupted the same as it would if you have moved. 

I also made sure to recheck to make sure that I wasnt moving my char by mistake, and had the same problem while standing completely immobile and same interruption happened.

**Comment by godmode** [comment]
Please make sure to search for existing issues first before posting. (The first checkbox.) #547
