### ISSUE TITLE
Fished up monsters removed from "pool" when disconnecting

### ISSUE THREAD

**Issue by beerking27** [EdenServer/community#1896]
### Checklist

I noticed today if you disconnect with a fished up monster on your line, it will remove them from being able to be caught again. i.e. if I have devil manta on my line and disconnect, I can no longer catch this monster again. I assume the only way at the moment to resolve is zone reboot.

Version 30181205_0

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

**Comment by Setz0r** [comment]
interesting. thanks for the report. will investigate
