### ISSUE TITLE
Guild Point items require HQ

### ISSUE THREAD

**Issue by rpcon** [EdenServer/community#1898]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Guild Point NPCs require HQ synts for the current bracket. Even in era, this was never the case. Both NQ and HQ items would be accepted, with HQ providing more GP.
Currently, GP NPCs will *only* accept HQ versions of the items requested, which is incorrect.

**Comment by bkesecker** [comment]
Please indicate which item and which guild.  There are plenty of guild items where HQ are accepted.

**Comment by rpcon** [comment]
Today's cooking guild, Apple Pie +1.
Yesterday it was Witch Soup, and would not accept Mushroom Soup.

**Comment by rpcon** [comment]
Journeyman cooking, NQ roast mutton is not accepted, but HQ is.
https://imgur.com/a/rhNGkYB

**Comment by 59blargedy** [comment]
other examples: carapace mittens +1, doublet +1
