### ISSUE TITLE
King Athro Spawn Radius is a little too large

### ISSUE THREAD

**Issue by CurzonEden** [EdenServer/community#1899]
### Checklist

- [ /] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [/ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/ ] I have provided my client version in the details. (type /ver into your game window)

### Details

The recent change to KA seems to have set his spawn radius  a little to large for Era.  The current DSP spawn isn't correct. He should still be spawning in a random position however in a much smaller radius around the area he did before the patch, but not in the area above the shoreline as he currently is doing.

**Comment by 59blargedy** [comment]
should be resolved by 5/16/20 patch
