### ISSUE TITLE
Golden Bat 

### ISSUE THREAD

**Issue by Saccharose** [EdenServer/community#1901]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver30181205_0

https://classicffxi.fandom.com/wiki/Golden_Bat

This NM is not spawning in any sort of its designated 1 or 2 hours pop time.
Other players have similar stories about this NM not popping.

**Comment by Slamm21** [comment]
I killed him yesterday, but not sure how long it has been since the last kill

**Comment by Saccharose** [comment]
I was hunting him for three hours one morning. Heard cases of not seen for many bat-killing hours.

**Comment by bkesecker** [comment]
There is conflicting evidence regarding window in talk page of ffxiclopedia.  Current window on Eden takes that into account.  Suggest closing issue unless more detailed data can be presented.
