### ISSUE TITLE
Physical weapon skills of monsters now interrupts casting while absorbed by Utsusemi's copy image buff

### ISSUE THREAD

**Issue by marlinla** [EdenServer/community#1902]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

July 22 patch notes:

> ■ Physical weapon skills of monsters will now attempt to interrupt player casting.

Physical weapon skills of monsters now interrupts casting while absorbed by Utsusemi's copy image buff. I'm fairly certain that if something is absorbed by shadow images, it has no impact on casting.

The 0 image combat log bug still remains. I'm not sure if these are comorbid issues.

Found this result while EXPing on Funguar and Mandragora weapon skills.

**Comment by Slamm21** [comment]
yes nothing should impact casting if it is absorbed, unless it has a knockback effect

**Comment by GalkaZajin** [comment]
Noticed the same effect with third eye, I blocked a physical tp move while casting and ended up being interrupted.

**Comment by godmode** [comment]
Shouldn't need a reboot to be fixed. Will probably just make it so that mobs can't interrupt on skills again until I have more time to look into it.
