### ISSUE TITLE
All Timed NM which don't persist broken since maintenance?

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#1903]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ 30181205_0] I have provided my client version in the details. (type /ver into your game window)

### Details
I had TOD for Bright-handed Kunberry from before maintenance and as I was not sure if he persisted through it I came just under 21hrs since he was last killed and waited until 21hrs 40mins was up. No one else was there and he never popped, so logically I assumed he resets with maintenance.

Wiki says he spawns 20hrs after maintenance with possibly around 15mins extra, so I arrived just before 20hrs after maintenance and have been here now for 2 hrs and no pop. Eden wiki says he is 21hrs-21.5hrs so he 100% should have popped by now. Again no one else was here.

Furthermore, a friend is trying to get a delkfutt key for his alt who had never done the mission yet Porphyrion has not popped in over an hour, and neither has Mimas when they should pop every 12 or 15mins respectively.

**Comment by Slamm21** [comment]
Bright-handed Kunberry just popped so I assume this was fixed. Friend left the tower after well over an hour with no pops but I assume he is up now.

**Comment by kylemorel** [comment]
Bright-handed Kunberry actually spawns 15min to 3 hours after maintenance. This can be seen in the DSP code [here](https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Yhoator_Jungle/Zone.lua). Then 21-21.5 hours after kill. . It has not been changed on Eden, as I have claimed in the short window after maintenance.

**Comment by godmode** [comment]
Probably just a fluke. Nothing was changed with all NMs only specific NMs and this wasn't one of them.  Let me know if you are still having issues.

**Comment by Slamm21** [comment]
Got here again for a friend to give TH3, 21hrs after kill, 40mins later still no pop so something is definitely up it seems.

**Comment by Slamm21** [comment]
perhaps he is set to 21-24 by mistake?

**Comment by kylemorel** [comment]
Most likely the server that the zone resides on crashed and had to be rebooted, thus resetting the spawn timer.

**Comment by Slamm21** [comment]
possibly but I see no mention of r0 in the jungle in Eden discord for yesterday unless I am blind.

**Comment by Slamm21** [comment]
actually looks like lots of zones crashed this morning, just not yhoat specifically. that must explain it, thanks

**Comment by kylemorel** [comment]
Yeah. Yhoat is a very quiet zone. If it goes down with some others there's a good chance nobody is even there to call it out.
