### ISSUE TITLE
Porphyrion Not Spawning

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#1904]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Porphyrion should be respawning every 12 minutes in Upper Delkfutts and is not. This makes Rank 4 unobtainable. 

Mimas is not spawning either.

**Comment by godmode** [comment]
This is due to someone them off the map. Navmesh issue--I'll work on making it possible to reset their positions.
