### ISSUE TITLE
Players can only enter Promyvions they've cleared

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#1905]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

After the latest patch it seems that players can only enter Promyvions they've cleared. We tried forming a group to attempt them and players who had not cleared were not able to enter after meeting the prerequisites. A player in our group who had cleared Holla was only able to enter Holla and not the other two. Another player in our group who had entered Holla before but did not clear was not able to enter any of them on this attempt.

version 30181205_0

**Comment by godmode** [comment]
Steps to reproduce, please.

**Comment by FariskaEden** [comment]
When you try to go to any of the crystals that teleport you into a Promyvion and have not cleared it you get the following message that keeps repeating when you click the crystal and hit the yes option.
![image](https://user-images.githubusercontent.com/46270382/61816713-ee2fbf00-ae1a-11e9-9713-92c4033e904c.png)
![image](https://user-images.githubusercontent.com/46270382/61816723-f1c34600-ae1a-11e9-8d11-588c83f841cc.png)
