### ISSUE TITLE
Castle Zvahl coffer keys

### ISSUE THREAD

**Issue by Teaspoons** [EdenServer/community#1906]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

So we were farming coffer keys last night, fighting the correct mobs, yet they dropped 3 chest keys, no coffer keys. This doesnt seem right.

**Comment by bkesecker** [comment]
Knee jerk reaction, this would have been reported a long time ago if Zvahl Coffer Keys were not dropping.

**Comment by GalkaZajin** [comment]
They have been dropping just fine for me, the drop rate actually seems super high for a coffer key, Only the abyssal demons can drop both the chest and coffer key but the chest key is pretty rare from them

**Comment by Teaspoons** [comment]
We must just have terrible luck then, like an hour and a half with thief, 3 chest keys, 0 coffer keys,

**Comment by bkesecker** [comment]
Confirmed from the DB that all mobs that are supposed to drop the coffer key do.  Closing.

**Comment by waffleness** [comment]
Just to add - they were dropping from Abyssal Demons (I don't believe any others) at a near 50% drop rate with TH2. According to the Zvahl chest key page on the wiki in Nov 2007, the Abyssal Demon doesn't drop these. And the current wiki page for Abyssal Demon has a chest key on there at a 0% drop rate. The issue would really arise if a chest key drop prevents and coffee key from dropping.

**Comment by GalkaZajin** [comment]
I farm there quite regularly. I have gotten both to drop at once and it’s much rarer to see the chest key

**Comment by Teaspoons** [comment]
My main concern was that something may have bugged out and the chest key was dropping instead of coffer keys, as long as other have gotten drops recently, it was just bad luck.

**Comment by Slamm21** [comment]
It was new moon last night, and from my experience on eden the moon effects are wrong.
New moon should increase rare mob drop rates and HQ crafting rate, while increasing the chances of breaks, while Full moon should increase crafting success rate and drop rates on your average drops.

It seems like on here that Full moon is good for everything and new moon terrible, but this is just my observation and sadly have no numbers to back this up. I could be wrong.

**Comment by Raphtalia1** [comment]
New moon lowers mob drop rates, increases HQ chance, break chance, and skill up chance.

Full moon increases drop rate, and synth success, but lowers HQ chance, Skill up chance.

From mine and others experiences on Eden this has held true

**Comment by Slamm21** [comment]
thanks for the clarification
