### ISSUE TITLE
Dragon's Aery darters should have alliance hate

### ISSUE THREAD

**Issue by Mikokiko** [EdenServer/community#1909]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
        Version 30181205_0
### Details
**Darters are not sharing hate with alliance**
In dragon's aery, the hate from the darters are shared amongs the player in the alliance regardless if you had made anything to share hate on them or not. As of right now, only the person who target the darter get aggro from them. Same with smn pet, wich allow smn to use slowga w/o fear of causing a wipe since darter lose aggro upon releasing avatar.

https://ffxiclopedia.fandom.com/wiki/Darter?oldid=436949

**Fafnir sleep**
For some reason ninja are able to land sleep extremly easily on fafnir. BLM using ES get resisted, something seems off. Light shot also work wonders. This should be looked into.

**Comment by roriffxi** [comment]
Slowga, when used with a non-darter target, won't cause alliance hate.
https://www.bluegartr.com/threads/45516-SMN-Pull-amp-AoE-questions

However, the other part of alliance hate is an issue.

Fafnir resisting ES sleep from a black mage is also definitely an issue.

**Comment by danismyhero** [comment]
Darters continue to not share hate with alliance members.  Once a party or alliance member has hate, every alliance member should be on the hate list of a Darter.

**Comment by Caelic** [comment]
i wrote a script for the darter shared hate for party/alliance members and have a pull request to the darkstar repo here: https://github.com/DarkstarProject/darkstar/pull/6315

if the eden devs want to use the code feel free. comes with a video demo too.

**Comment by Steam-arch** [comment]
Confirmed that DA darters still have the uniqueish hate mechanic on retail. 

But its not true alliance hate, they actually just add everyone (in that persons ally who tagged/linked them) to the hate list who was below 8.0 (might be 7.9) range **of the monster itself** the moment the monster was tagged. The linking darters also adds everyone to the hate list (from target ally) who was below 8 range from around the **linking darters themselves** the moment it linked. But the darters still keep seperate hate lists individual to that ID itself.

/nin Stealth trait does **NOT** reduce the 8 aggro range on darters (didnt check caveberries). If you pull a darter off of another ally, that darter acts normally and does **not** re-apply the 8.0-hate mechanic.

Caveberries (saplings) in CN also confirmed to have exact same mechanic, Witch Hazel (saplings) in CN do not.

Darter test video:
https://www.dropbox.com/s/pm8bfuur6x542bc/2022-11-10%2015-49-19.mp4?dl=0

Caveberry test:
![image](https://user-images.githubusercontent.com/69089249/201217961-7aae4fa5-ca06-4541-aaaa-f6c956637b68.png)


Witch hazel test
![image](https://user-images.githubusercontent.com/69089249/201217801-22103fcf-7d8b-466f-b77e-470ef05f459f.png)

**Comment by 59blargedy** [comment]
resolved by another dev in July 5th, 2024 patch. as mentioned in this, it is not alliance hate but a more global hate on detect system
