### ISSUE TITLE
Newton Movalpolas gates not operating correctly

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#191]
Traded a firesand to the northern furnance. Only the northern gate switched. The southern gate did not. AFAIK all gates should switch upon operating any furnace.

**Comment by Wiggo32** [comment]
you are correct. we'll get on it

**Comment by icariumkupo** [comment]
This one still broken. Same issue. North gate changes but south gate does not rendering most of Newton inaccessible.

**Comment by Anillo84** [comment]
This is still not working correctly.
