### ISSUE TITLE
Shiva Primal Fight Bugged

### ISSUE THREAD

**Issue by dachaosbringer** [EdenServer/community#1910]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)

- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

- [x] I have provided my client version in the details. (type /ver into your game window)

I believe is the window version 64

### Details
Hello, on July 25 2019 I was streaming on my channel this game Final Fantasy XI Eden Server 
and decided to solo Shiva Primal on my 66 RDM/NIN. I enter the fight and was doing good until Shiva performed her Blood Pack attack back to back 3 times. This attack was suppose to activate upon building enough TP and only once until TP is build up again but Shiva did in fact use this move back to back 3 times and I got it highlighted on my channel if you would like to look at it at www.twitch.tv/dachaosbringergaming The title of this highlight is Shiva Primal Fight Bug. I am sure this is a bug and that you guys will take care of the issue, thanks again for taking the time to read this and to take care of the issue.

**Comment by Slamm21** [comment]
All the primal fights and fenrir are nothing like retail currently.
They not only spam blood pacts but also their 2hr. While all easy on here, the prime fights were even easier on retail with the main thing you had to watch out for being the 2hr. Fenrir here is a complete joke, he can catch you out with 2hr spam but apart from that he is so much easier.

Eden does seem to have an issue with a lot of mobs spamming 2hrs when they should only use it once.

**Comment by rockemsockemman** [comment]
Can confirm, just ran through all prime fights and the avatars are using their 2hr multiple times per fight.

**Comment by 59blargedy** [comment]
resolved in December 14th patch
