### ISSUE TITLE
"Past Reflections" Quest not implemented

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#1911]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Luto Mewrilah doesn't seem to offer any quests past the initial Mirror Mirror quest to get your Signal Pearl. I have a level 44 Adventuring Fellow and am hoping to keep progressing once I hit the 50 cap. A prerequisite to the 50 cap quest is that you have adventuring bond 35+. In order to raise your Adventuring bond cap from 30 to 50 you must complete the quest Past Reflections (mentioned in name of ticket). Luto should offer this quest after zoning once you complete Mirror Mirror.

Note: Even though my Adventuring Fellow is mentioning the Emptiness Investigation (quest to get Tactics Pearl), I can't get that either because you need 33+ Adventuring Bond to summon your NPC in a Promyvion zone, and Eden seems to be currently capped at 30 without this Past Reflections quest.

Version: 30181205_0

**Comment by E5una** [comment]
Just an update, I've reached NPC Fellow lvl 50 and they no longer give updates on their EXP since they are capped. Looking forward to NPC quests being implemented!

**Comment by KnowOne134** [comment]
Can close as quest is coded and works
