### ISSUE TITLE
Depopping a NMs Placeholder should never spawn the NM

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#1912]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
https://www.bluegartr.com/threads/38800-Depopping-PH-and-the-effect-on-Lottery-NM

Immediately after SE put in the monster depopping change for MPK'ing, they did another patch which made it so that the same mob type always respawned.  It has been reported that VE and other NMs can pop after their placeholder has been depopped, rather than killed.

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
