### ISSUE TITLE
NPC Shomo Pochachilo in N.San d'Oria possible incorrect dialogue

### ISSUE THREAD

**Issue by Kule02** [EdenServer/community#1914]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver. 30181205_0

After completing the quest 'Father and Son' and receiving the willow fishing rod, Shomo Pochachilo will display the dialogue "Haha, I saw that. You rrreturned his fishing pole. How nice of you!" even if you did not return the rod to the boy. 

I'm unsure if she displays this text before taking the quest or at what point it triggers.

This page from a japanese wiki seems to suggest that it should trigger after the full set of quest events. https://www18.atwiki.jp/magichappy/pages/677.html

**Comment by bkesecker** [comment]
The dialog you found should only be displayed if the player returns the rod to the son.  There is no tracking yet.
