### ISSUE TITLE
Attestation drop rate audit request

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#1916]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Hey guys sorry to ask for this but we've seen awful drop rates on Attestations. Not in that we're not seeing them drop but we're seeing the same ones over and over. Always club and bow for example. Would you guys mind checking if the rates are distributed evenly? Between 2 linkshells scythe is 1/13 or something with lots of bows. Same for horn, I believe 2/13+ and instead a ton of clubs.

Thanks for all your hard work.

**Comment by Serephim** [comment]
DSP RNG FTW? lol
We been getting a ton of bows too (Which worked out well for me since I went 1/1 on mine. lol)

**Comment by icariumkupo** [comment]
Trending rng sucks but this one feels similar to how nidhogg used to heavily favorite m.body for a couple months.

**Comment by AnkleAssassinz** [comment]
fwiw went 1/17 or 1/16(?) back in retail for Aegis shield attestation. LS joke was Bravura for all since it dropped Force the most.

**Comment by icariumkupo** [comment]
I believe that attestation is special in that it can only drop as a secondary item only if another weapon drops as well. 

From wiki:
Attestation of Invulnerability does not share lot pool slot with weapon attestations but has ~30% chance to drop along a guaranteed weapon attestation

**Comment by bkesecker** [comment]
Some of these are absolutely the wrong rarity (guaranteed)
```sql
SELECT itemId,rarity FROM dspdb.mob_droplist WHERE itemId BETWEEN 1556 AND 1569; -- Attestations
```
