### ISSUE TITLE
NPC Capiria N. San d'Oria Laborman's Way - displaying quest text before taking quest

### ISSUE THREAD

**Issue by Kule02** [EdenServer/community#1918]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver. 30181205_0

Before accepting the quest 'Flyers for Regine', Capiria is already displaying her text from when the player hands her the flyer.

**Comment by Kule02** [comment]
The NPC 'Coullene' in N. San d'Oria cathedral is also displaying her acceptance dialogue before the player trades her the flyer.

**Comment by Kowl91** [comment]
I can confirm I am having the same issue with Capiria and Coullene as the 2 above. DOS ver 00.01.11 
Game Ver .30181205_0
