### ISSUE TITLE
Bat Hunt - NPC will not accept Orcish Mail Scales

### ISSUE THREAD

**Issue by Ramp87** [EdenServer/community#1919]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
30181205_0
### Details
When accepting 1-2 "Bat Hunt" gathered the item. forgot to click on the headstone for the CS.  NPC refuses to accept the Orcish Mail.  Dropped Orcish Mail, went back to KRT and watched the CS, then gathered another set of Orcish Mail.  NPC still refuses to accept them and states, "What? I don't what that".
- Have tried turning in with every gate guard in San d'oria multiple times. all give the same account. Have attempted to sign out and back into the game with the same results. Have dropped and regathered item, have rewatched CS and regathered item.

**Comment by bkesecker** [comment]
Please make a GM call if you haven't already.

**Comment by Ramp87** [comment]
I have made a GM call, waiting on an answer.

**Comment by freddiepines** [comment]
Can confirm as bugged, same issue on an alt account.  Submitted GM ticket.

**Comment by bkesecker** [comment]
@Ramp87 @freddiepines Were your issues resolved?

**Comment by Ramp87** [comment]
Yes they were. Thank you.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by bkesecker** [comment]
Thanks for the update.  Most likely this resulted from the commonly known issue when character data doesn't persist to the database.  Work has been done on a replacement solution.  However, it is yet to be released.  Closing as duplicate.

**Comment by ceramsey** [comment]
> Thanks for the update. Most likely this resulted from the commonly known issue when character data doesn't persist to the database. Work has been done on a replacement solution. However, it is yet to be released. Closing as duplicate.

Has the replacement solution been implemented? I am having this issue but while doing it as a repeat mission and am stuck (I don't get the cutscene anymore as I'm past this mission in rank) and he wont accept fangs or scales. Opened GM ticket (but that was my first time doing so, just trying to make sure it gets addressed correctly or I did everything right on my end). Thanks you.
