### ISSUE TITLE
Out of Era cooking recipes

### ISSUE THREAD

**Issue by him911** [EdenServer/community#1921]
### Checklist

- [yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [yes ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [yes ] I have provided my client version in the details. (type /ver into your game window)

### Details

Red curry bun and yellow curry bun were introduced in 2009 but can be crafted currently.
AOE melee food

Kitron juice is also a 2012 recipe that can be crafted

Add Goulash to that list of ooe recipes ingame

**Comment by EpicTaru** [comment]
https://github.com/EdenServer/community/issues/496

**Comment by him911** [comment]
555

**Comment by SleazyFFXI** [comment]
I've seen some 100 cooking and I'm almost positive they aren't using cursed soup to cap,   my guess is OOE walnut cookies or something,   any way to tell what they are using to cap and if it was OOE recipes to cap what would be done about it?

**Comment by mlandrum22** [comment]
As someone who's been looking for apkallu eggs for weeks, people are almost certainly not doing walnut cookies -- although it does appear that's a recipe in Eden.

**Comment by him911** [comment]
Walnuts cant be obtained to craft walnut cookies.

**Comment by KnowOne134** [comment]
fixed next update
