### ISSUE TITLE
San d'Oria Mission 2-3 Kindred Report not recognized

### ISSUE THREAD

**Issue by Kross22** [EdenServer/community#1924]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I did the San D'Orian Mission 2-3 by going to Windurst > Bastok.

I beat the Dragon and received the "Kindred Report" Key Item from Savae E Paleade.

When I returned to the Chateau to speak with Halver, he gave me the Mission anew as if I never started, and gave me the key item "Letter to the consuls", even though I have the Kindred Report (See Screenshot).

![Letter and Report](https://user-images.githubusercontent.com/53446169/62070716-0df32880-b209-11e9-9b01-b08cc10bdcc4.PNG)

--Kindred Report Received--

![Kindred Report received](https://user-images.githubusercontent.com/53446169/62070728-16e3fa00-b209-11e9-8e53-5c60cd83143f.PNG)

--Halver not recognizing the Kindred Report

![Halver not recognizing Kindred Report](https://user-images.githubusercontent.com/53446169/62070755-1f3c3500-b209-11e9-8e35-834056d56020.PNG)

Thank you for your attention with this!.

Kross

**Comment by Kross22** [comment]
Version is 30181205_0

**Comment by Slamm21** [comment]
2-3 does seem to be bugged. I did it yesterday to help a friend and despite me and my alt being rank 6, we still received the key item. I'm hoping when I decide to do more missions it won't suddenly think I am rank 2 again.

**Comment by 59blargedy** [comment]
this should be resolved with April 26, 2021 update but missions are a cluster so please comment if still an issue and ill reopen
