### ISSUE TITLE
Colibri Fletchings should not be a desynth

### ISSUE THREAD

**Issue by GalkaZajin** [EdenServer/community#1925]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
https://gyazo.com/b6b655f9ff2c187e7e38bae58919edda

Was struggling for an 8 lvl gap with advanced support then realized I hit an HQ3 in the middle of those synths.

**Comment by waffleness** [comment]
Didn't catch this report before trying this myself. But just adding my experience. 6 level gap for me + advanced synthesis. Definitely classified as a desynth.

https://imgur.com/XX5YivX

**Comment by GalkaZajin** [comment]
Was looking to see what arrow these were for and noticed that this synth is OOE. /panic

**Comment by AikoSachi** [comment]
It is indeed OOE.
Item ID of Colibri Fletchings: 2649

**Comment by bkesecker** [comment]
Manual close; automatic didn't take.
