### ISSUE TITLE
Phantom roll 11s bug

### ISSUE THREAD

**Issue by pksweets** [EdenServer/community#1926]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

A party member earlier got an 11, then immediately started busting the next roll repeatedly. Apparently if you have an 11 roll, then you can't be afflicted by Bust on your next roll and the phantom roll cooldown is lowered, allowing you to just keep rolling until you get another 11 then rinse and repeat. 

Steps: Roll an 11 on any phantom roll.
You should now be immune to Bust, allowing you to reroll repeatedly until a desired number is rolled (or until the first 11 wears off.)

version 30181205_0

**Comment by Slamm21** [comment]
Just tested this on my alt, rolled a bust then happened to roll an 11 on the next roll. Phantom roll recast was reset and I could re-roll on the roll I busted on. So the party had 2 buffs and my alt had bust status still, yet the 2nd roll had overwritten the original one.

**Comment by ccl085** [comment]
Started corsair on Eden and I actually noticed this too, this isn't a bug per say, it is that we're having the 2011 out of era phantom roll effect on XI.

On era, the effect on XI roll was double duration, but it got changed in 2011 to what we have now on Eden

**Comment by KnowOne134** [comment]
Has been corrected
