### ISSUE TITLE
THF AF1 -> Towers not changing

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#1928]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = N/A

For THF AF1 "As Thick as Thieves", the towers for the Sauromugue Champaign grappling part are supposed to change every day per https://ffxiclopedia.fandom.com/wiki/As_Thick_as_Thieves?diff=next&oldid=1671358 . Currently according to https://github.com/DarkstarProject/darkstar/blob/4fe5278f79addf80707176a93b541ebbea1f8487/scripts/zones/Windurst_Woods/npcs/Bopa_Greso.lua you're set a variable between 2 and 7 and which tower works for you is based on what variable you receive. Technically that is accurate according to an edit from our era ( https://ffxiclopedia.fandom.com/wiki/As_Thick_as_Thieves?diff=377834&oldid=368069 ) but I believe the info from our era is just inaccurate due to lack of knowledge at the time. The edit that changed the wiki to "change every day" wasn't done in reaction to an update on retail.

**Comment by Treble011** [comment]
This is still an issue.

**Comment by 59blargedy** [comment]
resolved  in recent update
