### ISSUE TITLE
Davoi NM's which don't spawn

### ISSUE THREAD

**Issue by Arckaina** [EdenServer/community#1931]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

Hawkeyed Dnatbat, and Steelbiter Gudrud are not spawning. Spent 10 hours in Davoi, mostly alone, the other 2 NMs in the area spawned, but all day these 2 did not. Again, someone could have claimed a spawn 1 or 2 times, but, I was there all day, /sea and mostly was alone. Never saw either of these 2 NMs. Killing the correct placeholders according to online wiki, with correct history timeline.

**Comment by Mozzy4Ever** [comment]
Unless something was changed recently (past week or two i'd say) I can confirm they definitely do spawn. They can often be stingy little fucks though.
