### ISSUE TITLE
NPC Andelain (East Ronfaure) - quest: The Vicasque's Sermon - not displaying quest dialogue

### ISSUE THREAD

**Issue by Kule02** [EdenServer/community#1932]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver. 30181205_0

Anderlain seems to be displaying dialogue from an Abyssea NPC in his default state. When taking the quest 'The Vicasque's Sermon' and trading him the 'blue peas' he responds with: 

"To where will you head?
The past.
Walk of Echoes.
Nowhere for now."

As a side note, I have the 'carnivorous maw' icon on my map. So it's probably linked together.

**Comment by 59blargedy** [comment]
resolved in september update
