### ISSUE TITLE
Cleric's Briault bonus (+ hp to regen) not triggering

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1933]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently, this body piece does not give additional HP when equipped while casting regen (which is kind of the whole point)

**Comment by beauxq** [comment]
My Cleric's Briault is giving the regen bonus for me.

If it is not working for someone else, a suspicion that arises in my head is that it only works if the caster ALSO has regen merits.
That would be a bug if that's the case. It should work for someone without merits.

If that's not it, I'm not sure what else it might be.

**Comment by Serephim** [comment]
Hmmm it's working for me too. Regen 3 is giving me 3 more HP per tick. Which regen spell did you test it out on Bass?
