### ISSUE TITLE
Job traits Whm & Blu

### ISSUE THREAD

**Issue by jn2840** [EdenServer/community#1935]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
Version:  30181205_0

My 37 whm is missing Clear Mind II from the list of traits.  The trait was available when I hit 35 but it noticeably disappeared around 2 days ago as resting was taking longer than usual.  I have been switching jobs and changing syncs to try and reset the trait to the list but it is not working.

In addition my 23 blu has a Magic Defense Bonus listed in the trait menu but that should not be there till lvl 50-60.  It should say Auto Regen but its not listed either.  I removed all spells from the set list and the trait was still listed.

Thanks guys!

**Comment by ShiyoKozuki** [comment]
![Shiyo_2019 12 26_010405](https://user-images.githubusercontent.com/58101246/71460880-a3c0be80-277b-11ea-8a10-e21110e718d1.png)
Clear mind/traits in general should not appear as "II" in our era and I don't see the issue you're having with BLU.

**Comment by KnowOne134** [comment]
tested with no problems found, the clearmind trait will only ever display clear mind, there is not a clear mins II it just stacks the effect to the 1st
