### ISSUE TITLE
Rampart Does Not work

### ISSUE THREAD

**Issue by Blex64** [EdenServer/community#1936]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

Client version 30181205_0.

Rampart does not appear to be functioning currently. Observed on Imp spells, Magmatic Eruca Incinerates, Haunt spells, and Cursed Spheres and Venoms from flies in both Mount Zhayolm and Caedarva Mire. Rampart would be up, magic damage would go off, and everyone would take full damage and the Rampart buff would still be up.

**Comment by Drognand** [comment]
I will myself put some testing into this to see if it is true. As an old old in retail I know what rampart should do in terms of MGk reduction.

**Comment by ShiyoKozuki** [comment]
![Shiyo_2019 12 26_010102](https://user-images.githubusercontent.com/58101246/71460767-3e6ccd80-277b-11ea-9896-23ff7c2424b6.png)
Seems to work for me. The formula could be off but the ability actually functions.

**Comment by slassen** [comment]
Can see issue https://github.com/EdenServer/community/issues/2238 for updates
