### ISSUE TITLE
Guild Points: Maple Tables not accepted for GP

### ISSUE THREAD

**Issue by Aviglug** [EdenServer/community#1937]
GP rep at the wood guild asked for maple tables but nothing happens when traded.

### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by AnkleAssassinz** [comment]
That happens when you rank up and you did not wait 1 full in-game day to pass before checking the gp npc. Happened to me also.  I don't think its a bug because the same thing happens in retail.

**Comment by bkesecker** [comment]
@Aviglug Were you able to try the next game day?  Otherwise, I am inclined to accept @AnkleAssassinz and close.

**Comment by Aviglug** [comment]
@bksecker I was able to get gp the next day. @AnkleAssassinz is correct!

**Comment by bkesecker** [comment]
Great!  Closing issue.
