### ISSUE TITLE
Quest Progress Blocked CoP Desires of Emptiness and Cid

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/community#1938]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Players are blocked by CoP Desires of Emptiness mission and Promathia status higher than a certain value from obtaining dialog from Cid to advance quests further down in the Lua logic.

**Comment by HunnyDoo** [comment]
Attempting to start AF2 quest with 61 DRK that has AF1 quest complete and CoP 5-1 complete

https://www.youtube.com/watch?v=IzxqL58bG_c&feature=youtu.be
