### ISSUE TITLE
Grand Marid aggro

### ISSUE THREAD

**Issue by jadeanime** [EdenServer/community#1939]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver 30181205_0

Grand Marid spawned in Bhaflau Thickets at (G-8). It was immediately aggressive to a lvl 70 BST who warped to safety. Checked several old and new sites - all say that the Grand Marid, while it links to other Marid, is -**not aggressive**-. I joined the BST on my 69 THF to test it - the Grand Marid aggroed once more.

**Comment by Mozzy4Ever** [comment]
Can be easily fixed via going to mob_pools.sql and filtering for 1787 (Grand Marid's poolid). Change the "aggro" flag to 0

**Comment by bkesecker** [comment]
> Can be easily fixed via going to mob_pools.sql and filtering for 1787 (Grand Marid's poolid). Change the "aggro" flag to 0

Thank you Mozzy.  Made it a quick fix.
