### ISSUE TITLE
Sandy Mission 9-2: Trion claiming mob making it unattackable

### ISSUE THREAD

**Issue by Eme-FFXI** [EdenServer/community#194]
In phase 2 we engaged the PLD boss, sleeping the others. At one point Trion "claimed" the PLD boss making it purple for everyone in the party. We killed off the other mobs but could not get claim on the main mob again.

See attached screenshot
![eme_2018 10 20_025522](https://user-images.githubusercontent.com/44308523/47249888-f1c09080-d419-11e8-885f-9fb9a71315ad.png)

**Comment by KnowOne134** [comment]
Was told this is fixed yesterday. Reopen if it persistes
