### ISSUE TITLE
Misnamed Aydeewa Mobs

### ISSUE THREAD

**Issue by HunnyDoo** [EdenServer/community#1940]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

v30181205

In addition to Mycoskulker mushrooms, we have Mycoskulker spiders and tigers @ I-8/9 (not sure which map, 1 maybe?)

![misnamed](https://user-images.githubusercontent.com/46686806/62639483-35cb4600-b905-11e9-9111-8908ae732f13.PNG)

**Comment by Mozzy4Ever** [comment]
Looks like something renamer would fix, those are retail names. In retail that area is all funguar (https://ffxiclopedia.fandom.com/wiki/Mycoskulker). For renamer to fix, someone would have to go there and use something like targetinfo to grab their IDs and edit the eden.lua renamer file.

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
