### ISSUE TITLE
???'s for Curtana up at East and West Side 

### ISSUE THREAD

**Issue by baroom84** [EdenServer/community#1942]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

Cheese obtained a Curtana at 14:47:52(East side and I (Baroom) received at 14:49:28.
![Baroom_2019 08 08_180307](https://user-images.githubusercontent.com/46089689/62740811-d2294180-ba06-11e9-9668-4c293982e3c2.png)

**Comment by Mozzy4Ever** [comment]
Gunna bump this with a lil more info - Curtana ??? are instantly up, have no cooldown. Have had it spawn, grabbed a Curtana, and ??? spawned again in the same spot so dropped Curtana and got another to make sure it was the right ??? :p

**Comment by baroom84** [comment]
I don't know if it's still the case or not but I picked up a cutana on the west side of sky and 1 min later another ls member said they got the curtana on the east side. Not sure if it was a one time glitch or not.

**Comment by Mozzy4Ever** [comment]
Nah it's a constant bug and still happens

**Comment by montijin** [comment]
Respawn timer on Eden is currently set for 5 minutes as well.

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
