### ISSUE TITLE
Bloodsuckers in Bostaunieux Oubliette lvls all the same

### ISSUE THREAD

**Issue by Wade9363** [EdenServer/community#1943]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

The regular bloodsuckers in lower Bostaunieux Oubliette are all level 65.  There should be some level variation.  Wiki suggests 65-68 is the correct level range.

**Comment by greyenvy** [comment]
good change.  this will open up another bst camp!
