### ISSUE TITLE
Pupetmaster shield bash crash the game.

### ISSUE THREAD

**Issue by raventn** [EdenServer/community#1944]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x]I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

There is issue where pet tun an monsters move and game just crash for party memebers to.
it happens alot.

**Comment by FariskaEden** [comment]
This has more to do with stunning / killing a mob during a TP move since it displays a weird animation. Mobs I've noticed that crash people a lot on a stunned TP move are mandragoras, funguars and dhalmels.

**Comment by raventn** [comment]
yes that even in promys pupetmaster tank pet use shield bash just crashing out players

**Comment by KnowOne134** [comment]
Best to list the moves to be looked at. As it's the mob skills that are the issue and not fully dialed in

**Comment by FariskaEden** [comment]
For mandragoras I've noticed that dream flower definitely can cause crashes when interrupted. For funguars both queasyshroom and silence gas have caused crashes when interrupted. It's been a while since I've exp'd on dhalmels but if I crash on them again I will list the ability then.

**Comment by 59blargedy** [comment]
while there are still issues with puppets crashing the game, this does not appear to be a current issue. please comment if new information specific to shield bash
