### ISSUE TITLE
Pirate Event-Only Gugrusaurus Catchable w/o Drill Calamary/Rings 

### ISSUE THREAD

**Issue by HammerhandsKupo** [EdenServer/community#1945]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version: 30181205_0

Last night I went fishing for Sea Zombies during a pirate event.  I caught some sea zombies. I was also able to fish up Gugrusaurus. I caught two of them. I've never caught them before.  I was using a Lu Shang's and Meatballs.  After speaking to a fellow player today, he informed me that should be impossible to do. He said it should only work with Drill Calamary Lure and Mooching KI (I have the KI).  I will provide a screenshot of me catching them.  

Another player who is also 100 fishing said I should ask a GM. I kept the two fish and did not turn them in to the Inside the Belly NPC and I did not sell them. **I will discontinue all fishing** until I get an official response from a GM on this.  

It should also be noted I've had Gugrusaurus on the line on the open-sea route to Alzhabi and they were impossible to reel in.  I would run out of time before they were half way out of stamina. I was only able to catch them during the Pirate event on the Mhaura to Selbina Ferry last night.   Also I didn't have any on the line during normal ferry rides. During normal ferry rides I only had Ryugu Titans and Titanictus bite. 

Reproducible steps:
Have 100 Fishing skill, Lu Shang's, Fishing Apron, Waders, and all fishing gear equipped for a total of 144 fishing skill. 

Have Fishing KI's Serpent Rumors and Mooching.  Have meatballs as bait.  

During the pirate event on the Mhaura to Selbina ferry attempt to fish up Gugrusaurus.  Most should be lost to lack of skill or line/rod break. But you should always be able to get them to zero stamina and press Enter on time.

Attached: Screenshot of catching Gugrusaurus last night.
![Gugru](https://user-images.githubusercontent.com/47540211/62800140-85da1200-ba97-11e9-84b9-47173c40d57d.jpg)

**Comment by Setz0r** [comment]
Hax! But really though, let me see if i can decipher what you're saying.  You are unable to catch gugru's on the mhaura/alzhabi boat, but you are able to catch them on the pirates mhaura/selbina boat?

**Comment by HammerhandsKupo** [comment]
Correct. I was able to catch them only during the pirate event. With just a meatball. No special lure.

**Comment by Setz0r** [comment]
that's odd because the fish stats aren't based on the area they are caught in.  the area only determines which fish are able to be caught.

**Comment by Setz0r** [comment]
are you sure you weren't hooking something else on the alzhabi boat?

**Comment by HammerhandsKupo** [comment]
I am not sure if I was hooking the same thing on the alzhabi boat. But what whatever it was it had the slower arrows that a Gurgru did on the pirate boat. Most other giant fish I’ve caught have a lot faster arrows. A lot faster.

**Comment by HammerhandsKupo** [comment]
> **I will discontinue all fishing**

I meant I'm not gonna fish up Ebisu-related fish (gugrusaurus) until this post gets resolved. I will be fishing up other things in the meantime.  Thanks for helping Setzor.
