### ISSUE TITLE
Grand Slam does 1 dmg every time.

### ISSUE THREAD

**Issue by SBC-Nyxai** [EdenServer/community#1946]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
Grand Slam TP move from Gigas in Lower Delkfutt Tower does 1 damage every time its used. Not sure about other gigas.

**Comment by greyenvy** [comment]
Came here to post the exact same thing, except to report that the Gigas in Qufim Island are the exact same way.  It may just be the entire formula for Grand Slam is screwed up.
