### ISSUE TITLE
The Old Monument Bard quest seems to require an extra step

### ISSUE THREAD

**Issue by sanchez513** [EdenServer/community#1947]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by sanchez513** [comment]
I keep trading the parchment to the song rune and it is not doing anything. I saw the cutscene that comes the first time you click on the song rune.  Please assist.

**Comment by Mozzy4Ever** [comment]
Reference #733 and follow the specific NPC-conversations that that poster had, see if that fixes your issue. Gunna also tag #749. Both are closed, however apparently this issue is still happening if OP followed the quest correctly.

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
