### ISSUE TITLE
Muddy Siredon

### ISSUE THREAD

**Issue by MonkeyAce9** [EdenServer/community#1948]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
While travelling on the ferry in the Phanuet Channel I was fishing and caught a Muddy Siredon however after the first one I continued fishing on the ferry but when I successful caught another I wasn't allowed to keep any more of these fish. When I made it back to town I tried selling it on the AH but  I wasn't allowed to put it up on the AH to sell it so I then tried selling it to a nearby NPC but couldn't sell it to the NPC either.

Client version 30181205_0

**Comment by godmode** [comment]
This is because it is missing the original CoP item flags.

**Comment by KnowOne134** [comment]
This is all the normal behavior of this item. More than likely the only issue is the ease of catching them.
