### ISSUE TITLE
Switchmon

### ISSUE THREAD

**Issue by gannony** [EdenServer/community#1951]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by godmode** [comment]
There are no details or boxes checked. In addition if this is an issue with a third party utility it is not something that we support—even if it is allowed.
