### ISSUE TITLE
Worm Family "casting is interrupted" constantly

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#1952]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Mobs of the worm family constantly have their spells interrupted when they are in idle mode (not engaged in any way).  By what, I do not know.  Perhaps their movement is triggered while they are mid-cast of some spell.  It's hard to know because I don't think they have any buff spells from what I recall, so I'm not sure what they are casting that is being interrupted.

To reproduce this issue stand in the middle of Den of Rancor by those worms or in Kuftal Tunnel near the worms.  Your log will be spammed by "X's casting is interrupted" over the course of several minutes.  It's very  odd behavior but I know we have a lot of mob spell behavior issues.  

/ver: 30181205_0

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
