### ISSUE TITLE
BST AF3 fight Tigers not charmable

### ISSUE THREAD

**Issue by Wade9363** [EdenServer/community#1953]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

During the BST AF3 Fight in Eldieme Necropolis, A New Dawn, neither of the Tigers can be charmed.  Both Trombe and Taifun should be charmable.  I didn't get a chance to use Gauge, but failed to charm 5x in a row.

**Comment by Balrahn** [comment]
I tried gauge and it said that it's uncharmable. Hope this can be fixed quickly.

**Comment by godmode** [comment]
For whoever picks this ticket up it is because they are NMs and charming doesn't work on NMs. If someone has retail clips of someone checking to see if they are NMs that would be great. That way we can either adjust the code to edit that some NMs can be charmed or that these tigers aren't considered NMs.

**Comment by mlandrum22** [comment]
Similar issue with the Kraken in Qufim.

**Comment by Balrahn** [comment]
Here it's referenced from 2006 that the tigers can be charmed 
https://ffxiclopedia.fandom.com/wiki/Talk:A_New_Dawn?oldid=347348

Here's also a video from 2006, the first tiger gets charmed before 26 secs into the video.
https://www.youtube.com/watch?v=2t1rJm66AoI

**Comment by Balrahn** [comment]
I'm fairly certain they're NMs. Wiki lists them as NMs, and the trio NM bats in Wings of Fury are also charmable despite being NMs.

**Comment by Balrahn** [comment]
Found something else that's wrong: If you read the top strategy tip from 2006 on this, it says you should be able to pop them without aggro, however they all spawn claimed. https://ffxiclopedia.fandom.com/wiki/Talk:A_New_Dawn#Strategies
