### ISSUE TITLE
Muketsu Additional Effect

### ISSUE THREAD

**Issue by aspiraga** [EdenServer/community#1955]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
(ver. 30181205_0) The additional drain effect of Lv.54 Katana "Muketsu" seems to be missing. I have used them a lot and asked other people who use them if they've ever had a proc and they also report no.

**Comment by gweivyth** [comment]
```lua
-----------------------------------------
-- ID: 17778
-- Item: Muketsu
-- Additional effect: HP Drain
-- Gweivyth
-----------------------------------------
require("scripts/globals/status")
require("scripts/globals/magic")
require("scripts/globals/msg")
-----------------------------------

function onAdditionalEffect(player,target,damage)
    local chance = 10

    if (math.random(0,99) >= chance or target:isUndead()) then
        return 0,0,0
    else
        local drain = math.random(9,13)
        local params = {}
        params.bonusmab = 0
        params.includemab = false
        -- drain = addBonusesAbility(player, dsp.magic.ele.DARK, target, drain, params)
        drain = drain * applyResistanceAddEffect(player,target,dsp.magic.ele.DARK,0)
        drain = adjustForTarget(target,drain,dsp.magic.ele.DARK)
        drain = finalMagicNonSpellAdjustments(player,target,dsp.magic.ele.DARK,drain)

        return dsp.subEffect.HP_DRAIN, dsp.msg.basic.ADD_EFFECT_HP_DRAIN, player:addHP(drain)
    end
end
```

Tested these at length, they work perfectly.
