### ISSUE TITLE
Vingijard does not reset AF questlines/coffers

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#1958]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Vingijard currently does not reset AF quests for players that had acquired and thrown away all AF pieces for a job. When speaking with Vingijard he only displays the following message even if you have 10,000 gil to fulfill his request.

![image](https://user-images.githubusercontent.com/46270382/63118562-1f0f9980-bf6c-11e9-8bab-9c7dd9d33ad0.png)

https://ffxiclopedia.fandom.com/wiki/Vingijard

version 30181205_0

**Comment by bkesecker** [comment]
Most accurate description of what this NPC supports.
`
Vingijard will allow a character to repeat their AF quests. What happens is he will simply delete the quests from your quest log. This includes AF1, 2 and 3, the Boghertz Gloves quest, and any/all treasure coffers. In order for you to be able to do this, you must have completed ALL AF quests, and be missing any piece. If you talk to him without missing any, he won't offer it to you. It costs 10k gil to do this.
`
and
`
he was added before Limbus was implemented. 
`
Source: http://ffxi.allakhazam.com/db/bestiary.html?fmob=3195

**Comment by bkesecker** [comment]
Have retail capture, decoding bitmasks in-progress.

**Comment by 59blargedy** [comment]
resolved february 22, 2021 patch
