### ISSUE TITLE
Toau mobs have very low drop rate on craft materials

### ISSUE THREAD

**Issue by him911** [EdenServer/community#1959]
### Checklist

- [yes] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [yes] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [yes] I have provided my client version in the details. (type /ver into your game window)

### Details

Drop rates on craft materials from most mobs in toau is inaccurate since release. 
Crabs
Apkallu
Diremites
Funguars
Qiqirns
I havent killed enough Crawlers, Tigers, Morbols , Wamoura or Leeches or other mobs in different zones to add them but the ones listed have incorrect values or my TH is broken after hours, which doesnt make sense. Its craftable material. you kill enough and you should see results. I'm not getting any return or incentive to kill them at the moment. 

http://www.ffxidb.com

![toaum](https://user-images.githubusercontent.com/50463084/63127545-b227ee00-bfc3-11e9-9157-2b2a0c28defa.png)
![wamoura](https://user-images.githubusercontent.com/50463084/63127552-b7853880-bfc3-11e9-9ca6-90f85e58d69e.png)

**Comment by godmode** [comment]
Can you edit this title to "ToAU mobs have low drop rate"

**Comment by mlandrum22** [comment]
Adding to this: Killed over 30 Zhayolm Apkallu and received 2 Eggs and 5 Feathers. I can say for certain the Feathers are not a 60% drop, Eggs may have been an unlucky 20%, but would like this looked into.

https://ffxiclopedia.fandom.com/wiki/Zhayolm_Apkallu

**Comment by bkesecker** [comment]
Prior Apkallu egg drop rate issue research: https://github.com/EdenServer/community/issues/1791

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
