### ISSUE TITLE
Beryl-footed mulberry spawns behind a wall

### ISSUE THREAD

**Issue by Umarusuzy** [EdenServer/community#196]
After trading the pop item he spawns past a wall and needs to be pulled far to get him to clip into the pop item room.  He can run through walls.

**Comment by gweivyth** [comment]
I've had this problem on every DSP server. Was he still REALLY buff too? On Kupo he had an insane amount of HP.

**Comment by Umarusuzy** [comment]
i had some close calls on him so I would say yes he was pretty tough.
