### ISSUE TITLE
A Taste of Honey

### ISSUE THREAD

**Issue by Deepupuu** [EdenServer/community#1961]
### Checklist

- [yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ yes] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [yes ] I have provided my client version in the details. (type /ver into your game window)

### Details
ver: 3018125_0

I did the quests Delivering the Goods and Vanishing Act over the past two days. Today I should have been able to start A Taste of Honey since I completed Vanishing Act yesterday but I get no cutscene when I talk to Qutiba.

**Comment by KnowOne134** [comment]
Quest is uncoded

**Comment by KnowOne134** [comment]
resolved 11/2
