### ISSUE TITLE
Crimson Orb Quest Bug

### ISSUE THREAD

**Issue by SBC-Nyxai** [EdenServer/community#1962]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0
I completed the white orb > cursed orb leg of the crimson orb quest. When I returned to the NPC it gave me another white orb. I then had to talk again to the NPC to receive a crimson orb.

**Comment by KnowOne134** [comment]
Corrected 3/29/2021
