### ISSUE TITLE
Ice Ele replaced upon changing weather

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#1963]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I was killing an Ice Elemental in Beaucidine with 2x ice weather at the pond near OP (the one SW of the pond). When it had 10-15% health left, the weather changed to single Ice Weather.

My Elemental disappeared and a new one popped, my Courier Carrie warped to it and started attacking it and the new ele was at full health.

**Comment by HunnyDoo** [comment]
Can confirm the same thing happens in altepa when weather changes from single to double or vice versa. Elemental despawns instantly mid-battle and a new one repops in the original location.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
