### ISSUE TITLE
Sandoria Mission 9-1, NM's don't spawn and aggro immediately

### ISSUE THREAD

**Issue by Wade9363** [EdenServer/community#1964]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

At the beginning of the battle in Batallia Downs vs Suparna & Suparna Fletching, the NM's did not immediately aggro.  They stood motionless for about 10 seconds before engaging just like a when a normal mob spawns.

I can't repeat the quest to test further, but it seemed like we could have ran behind them or cast invisible before aggro and pulled them one at a time.

This was not possible on retail.  In order to separate them on retail the general strategy was to bind one and zone the other.

**Comment by 59blargedy** [comment]
resolved in April 12, 2021 update.
