### ISSUE TITLE
Under Observation magic resistance overtuned

### ISSUE THREAD

**Issue by piercingdark** [EdenServer/community#1965]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Under Observation mobs have very high magic resistance compared to retail, at least to ninjutsu. Capped ninjutsu with +INT was having the elemental wheel (ex: huton: ni, hyoton: ni, etc) hit for ~1. Occasionally would get a 14 damage spell... maybe 1 out of 10. 

Party member was nin/blm with even higher INT and hitting for 1 with ninjutsu as well, did get up to 30 once. In retail we could have had mobs dead in 5 minutes... in 5 minutes here they were down to 90%.

**Comment by godmode** [comment]
How is elemental ninjitsu in other places like exp parties and so on?

**Comment by piercingdark** [comment]
Works fine from what I’ve seen except it can’t be magic bursted (whereas on retail it can be).

**Comment by Raphtalia1** [comment]
Not sure if Ninjutsu can’t MB or if the game just doesn’t call it out, I’ve noticed a few higher than normal nukes when attempting to MB but I cannot confirm if it’s actually an MB or coincidence that I wasn’t being resisted.

**Comment by piercingdark** [comment]
Tried MBing over and over on beetles in an exp party and it was the same damage with what should have been the correct timing. Someone in party said ninjutsu MB doesn’t work right on DSP.

**Comment by Raulfin** [comment]
Have seen Sobbing use Breakga, but sometimes it will only use it 0-1 times per run, other runs it will use it several times. Seems you've just had good luck with breakga sofar.

**Comment by 59blargedy** [comment]
magic resistance resolved with magic hit update this year, other addons resolved in November 29, 2021 update
