### ISSUE TITLE
PUP/BST Charmed pets error on level, second charm causes crash

### ISSUE THREAD

**Issue by fluffydeadangel** [EdenServer/community#1967]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When you level up as PUP/BST, the pet still shows but you cannot select anything or do anything with them. When you charm another pet or call your autobot, the game crashes. I've seen this happen 4 times today, and it seems to take everyone else in the region out with me.  

Repeatable: Level up with a charmed pet as pup/bst. Charm something else. Two pets, only one interacts. Zone crashes.

version on the front screen shows ver.30181205_0

![broken](https://user-images.githubusercontent.com/54287722/63291427-1b8c5300-c289-11e9-9544-2c112b2ca579.PNG)

**Comment by mlandrum22** [comment]
Illegal charms seem to crash the server. 

In Dyna-Beaucidine, one of our melees was charmed by an NM Orc. One of our BRDs then tried to charm the already charmed player and then Dyna-B crashed.

I tried to find the bug report to link it, but couldn't find it.

**Comment by godmode** [comment]
Nice! I did a temp check on this just now but I did see this characters name in the crash. Thanks for providing details so I can follow up on it!

**Comment by KnowOne134** [comment]
Has been fixed. Can only have 1 pet at a time
