### ISSUE TITLE
Trick Attack not working ! in PTs and solo!

### ISSUE THREAD

**Issue by MrAbdul85** [EdenServer/community#1968]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by KnowOne134** [comment]
No details?

**Comment by MrAbdul85** [comment]
Hello, i have been in pts lately and lv30 , used trick attack, each time the animation is working but when  it lands, it misses,  i even used it with "sneak attack" together and they both miss!

**Comment by KnowOne134** [comment]
Behind the mob and another player In  front of you?

**Comment by MrAbdul85** [comment]
Trick Attack :not working behind a player .  miss

Trick Attack + Sneak Attack : not working behind player: miss

**Comment by MrAbdul85** [comment]
i haven't test it yet  on lv45 with hide ability , i haven't reach that lv , im lv31

**Comment by KnowOne134** [comment]
Trick attack is not a guaranty hit. Sneak attack is but only when you are
behind the mob

**Comment by MrAbdul85** [comment]
i see, but using it with a weapon skill , still miss?

**Comment by MrAbdul85** [comment]
using both trick attack + sneak attack alone , could both miss same time too. is that normal?

**Comment by Raphtalia1** [comment]
Sneak attack is a guaranteed hit if you are behind a monster, it will always fail to activate on a hit if you are not behind the monster, even with a weapon skill

**Comment by MrAbdul85** [comment]
yes i know sneak attack is guaranteed hit behind< i mean together  with trick attack they both missed behind the monster

**Comment by roriffxi** [comment]
Sometimes elevation causes a problem.  If you're on a slope the calculations are off.
At level 60 you'll have the assassin trait which turns TA into a guaranteed hit as long as you are behind a player that is in your party/alliance.  "behind" is also very fickle and you have to make sure you're exactly behind them.

**Comment by MrAbdul85** [comment]
Thank you for clearing this up :)

last question: will trick attack+ ws = guaranteed hit ? or even enmity boot for the tank as well ?

**Comment by Raphtalia1** [comment]
No, trick attack will always fail if you don’t have a player between you and your target, and it’s not a guaranteed hit until 60+, and even then only if you have a player in your party between you and your target

**Comment by MrAbdul85** [comment]
Thank you so much, thats explain all the misses, sadly we some how stuck on level syncs and we wont see that  alot on later pts ;(
 
everything is explained,  thank you again guys for the help!
