### ISSUE TITLE
5-1 Darkness Rising - Broken

### ISSUE THREAD

**Issue by GRiMiNSANiTY** [EdenServer/community#197]
We were able to challenge 5-1 Darkness Rising without any issues for our first attempt, aside from the fact Chawlee threw the fight. He was too close to aggro range so we decided to let the BCNM timer run out. Once the timer ran out, it warped us back to the portal room.

This is where we started having issues. When I tried to activate the fight for the second time, I was momentarily granted the BCNM icon and warped to the arena as if everything was working as intended, however the BCNM icon disappeared and I was no longer level restricted. There was also no present time limit for the fight.

I explored the arena to check to see if any of the enemies had spawned for the mission. The room was completely empty. I proceeded back to the entrance of the arena and attempted to exit, but I was unable to. Instead I was given the option to enter "Darkness Rising" while still inside the arena for Darkness Rising. I went ahead and selected "Darkness Rising" again, and I proceeded to warp, received the BCNM icon, and ended up back inside the same room with the same conditions as before.

The images below are screenshots I have taken:
https://i.gyazo.com/5364dfdb94d2a5ce6aa880119b207449.jpg
This screenshot was immediately after I entered the fight for the second time.

https://i.gyazo.com/3f044bad377db3dee387f9112971593e.jpg
This screenshot is where the fight actually takes place. There should be mobs present here.

https://i.gyazo.com/c65f081a6bd9c64bb1cf85d780a48552.jpg
This screenshot is to show I was not level restricted.

https://i.gyazo.com/862aef425d798bd3bebde49afb4c4648.jpg
This screenshot is the menu I received when examining the Burning Circle inside "Darkness Rising." Normally you would have the option to exit the fight here.

All my Key Items and Mission logs are correct. I have the New Fei'Yin Seal required for the fight, and my current Mission reads "Darkness Rising." Gweivyth attempted to assist us. Gweivyth was able to port me out of the BCNM to where we reformed our party and zoned in and out of the portal room. Upon re-entering the fight, we got the same results. Gweivyth also ported me to Metalworks and had me talk to Naji to see if the Mission had progressed, but that too was not the case.

If there is any more information I can provide please let me know.

**Comment by godmode** [comment]
Thank you for the very detailed report!

**Comment by GRiMiNSANiTY** [comment]
Update:
We challenged the fight again, but instead of having one of my characters initiate the fight, we had someone else challenge the fight for the first time. We cleared the fight and both of my characters received the necessary Key Items to complete the Mission.

**Comment by godmode** [comment]
This issue was fixed along with some other BCNM issues. It was due to the battlefield being initiated when trying to enter again.
