### ISSUE TITLE
Adventure Fellow Quest 'Unlisted Qualities' not completing after recent patch

### ISSUE THREAD

**Issue by trodeghero** [EdenServer/community#1971]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
Version 30181205_0
### Details

I completed the quest 'Unlisted Qualities' which is the first for the adventuring fellow last night; however, when I talk to Luto Mewrilah she repeats the same dialogue/CS over and does not award a silver ingot.  This was after the patch on Monday, 8/19/19

![Darklighter_2019 08 20_070852](https://user-images.githubusercontent.com/54328926/63372468-c5ccaf00-c34b-11e9-8740-30cd4212262a.png)

**Comment by KnowOne134** [comment]
I see issue and will put in patch
