### ISSUE TITLE
Minium Price Too High

### ISSUE THREAD

**Issue by Deepupuu** [EdenServer/community#1972]
### Checklist

- [ yes] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [yes ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ yes] I have provided my client version in the details. (type /ver into your game window)

### Details
ver: 30181205_0

Minium is 111,106 on our server. On the earliest history wiki pages that report a price for Minium its reported to be priced as "~68,062" gil.

btw thanks for adding Minium but if I can save 40k per minium that'd save me 240k overall for my crystal rose synth lol

**Comment by bkesecker** [comment]
I'll lump this in with a few other similar issues assigned to me.

**Comment by AnkleAssassinz** [comment]
..Or maybe its the median price as temp 'fix'? ffxclopedia says its anywhere between 68,062 gil-254,100g

https://ffxiclopedia.fandom.com/wiki/Minium

 Maybe npc price is tied to your current mercenary rank(?) which atm is not fully implemented.

**Comment by bkesecker** [comment]
Price presented is based on remaining stock.  The values on Eden are era accurate.  Closing.
