### ISSUE TITLE
Unlocking Advanced Automaton Frames

### ISSUE THREAD

**Issue by Kreepsta** [EdenServer/community#1976]
Hello, I was working on completing the unlock for the "Sharpshot" frame for Puppetmaster. (Ranger frame) When I was researching how to complete this quest, I didn't presume that this quest would have a separate era-appropriate turn in. It has been quite a while since I have originally done this quest in retail. Online the quest turn in says that it will require a "Heavy Crossbow," as well as when you accept the quest to turn in the items. When the dialogue is complete with the NPC "Ghatsad" it will be followed up with a system message reading "Note: Instead of of Heavy Crossbow you need Repeating Crossbow." Upon further research of era appropriate Ffxiclopedia pages, I found that the quest did originally require a repeating crossbow. I'm not sure if i'm in the majority of players who looks up a quest and obtains the turn in items before accepting the quest; however, I am truly at fault for doing so. I just happened to spend most of my gil on obtaining and having crafted the wrong era-appropriate item.

It may be beneficial possibly, if when the class is originally unlocked to mention to players beforehand that the future quest has been updated (rolled back) to the original turn in to avoid this happening again. Maybe even allow the turn in of either item as well? I'm not sure what exactly would go into trying to solve this issue, just some ideas!

Version 30181205_0

### Checklist

- [/ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [/ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by KnowOne134** [comment]
Best assume to always look at the mid 2007 wiki history as we havent dat modified this as of yet.

**Comment by KnowOne134** [comment]
It has been dat edited now. Can also use the eden wiki

**Comment by godmode** [comment]
It has been dat edited but it is not in the installer yet. Please leave open for now.

**Comment by KnowOne134** [comment]
Fixed some time ago
