### ISSUE TITLE
beginning Weaponskills too low skill

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#1977]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
205_0
### Details
the 1st weaponskills gained from each weapon were higher in Era, but they all gain 1 @5 skill now

**Comment by Mozzy4Ever** [comment]
Not sure if it's all but I don't see how it couldn't be. I know currently on Eden, Flaming Arrow (archery's 1st) unlocks at 10 as per era requirements. Fast blade is set to 5 I know for sure. Back in era times in was 10 ( https://ffxiclopedia.fandom.com/wiki/Fast_Blade?diff=306442&oldid=306341 )
