### ISSUE TITLE
Multi-hit weaponskills and double attack

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#1979]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I've noticed that Multi-hit weapon skills seem unable to proc more than one double attack per weapon skill. Every hit of a weapon skill should be able to proc, independently from each hit, up to a maximum of 8 hits. 

https://www.bluegartr.com/threads/42685-Guillotine-double-attacks-(Ruke-read-this!)/page2

**Comment by icariumkupo** [comment]
Just wanted to also mention this should be true for triple attack, but again max of 8 hits. So in the case of a thf/nin dual wielding, dancing edge should hit 6 times, 5 from the ws + 1 from offhand hit + chance for TA proc on any hit, but only once since that gives 8 hits.. unless there's a miss! Then TA could theoretically proc again to get to 8 hits. 

More discussion here
https://www.bluegartr.com/threads/37140-Weapon-skills-where-Double-Attack-can-proc

**Comment by icariumkupo** [comment]
Wiki sources:

https://ffxiclopedia.fandom.com/wiki/Double_Attack
May activate during weapon skills.
On multi-hit weapon skills, Double Attack can proc on any hit of the weapon skill. Note, however, that Double Attack cannot proc to induce a weapon skill to attempt to hit more than 8 times.

https://ffxiclopedia.fandom.com/wiki/Triple_Attack
On multi-hit weapon skills, (using Dual Wield) Triple Attack can occur twice (once on first hit and again on off hand hit).

https://www.bg-wiki.com/bg/Double_Attack
Can Proc a maximum of 2 times per Weapon Skill.
Subject to the 8-hits per round limit.

https://www.bg-wiki.com/bg/Triple_Attack
Can Proc a maximum of 2 times per Weapon Skill.
Subject to the 8-hits per round limit

**Comment by VeilEden** [comment]
My hero.

**Comment by icariumkupo** [comment]
Thinking about this some more. Considering that sources claim up to two procs of DA or TA can occur for a weaponskill - I wonder if that is for dual wield only.

Perhaps it's like this:
1. Any hit from the main hand WS (any hit except the last) can proc either TA or DA. With TA checking first for each hit, then DA.
2. Offhand hit has a chance to proc. TA check first then DA. 

This would be consistent with a regular dual wield melee swing.

**Comment by Setz0r** [comment]
what about for H2H

**Comment by icariumkupo** [comment]
H2H for DA and TA on regular hits is treated like dual wield. Either hand can proc and both can proc in the same attack round. However, Asuran Fists is a special case I've seen mentioned. Since that weapon skill is already 8 attack rounds, it cannot proc DA under any circumstance, even if a hit misses.

**Comment by Setz0r** [comment]
so you can't double attack with the first hit, meaning if one of the other 7 miss, you still wind up with 8?

**Comment by Raphtalia1** [comment]
It should check how many attacks are going before calculating hits/misses, so DA/TA can never proc on Asuran since you are already at the number of attacks cap

**Comment by Setz0r** [comment]
a dumb question, is it possible to miss the first hit of a double attack, but get the second, or does double attack only execute if the first hit makes it

**Comment by Raphtalia1** [comment]
You can miss the first hit of a DA

**Comment by Setz0r** [comment]
i mean in WS, i know in regular swings you can

**Comment by Raphtalia1** [comment]
In ws too, however you can not get a zanshin proc unless the first hit missed/was blocked/was gaurded/was parried

**Comment by 59blargedy** [comment]
resolved with pdif changes
