### ISSUE TITLE
Asuran fist Quest: WS point counter seems bugged

### ISSUE THREAD

**Issue by Rinkanu** [EdenServer/community#1980]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

I am having issues completing the first part of the asuran fist weaponskill quest. Namely the part where you receive the knuckles of trials and are required to accumulate 300 weaponskill points.

After weeks of unsuccessfully trying to accumulate enough points and seeing the latent effect dissapear from the weapon i am convinced something is broken in the mechanic.

I did the following things:

-Made sure i had the weapon of trials equipped obviously.
-Did 459 raging fists solo keeping track manually.
-Did 32 Light skillchains with a friend opening and me closing. did this on full HP mobs making sure the monster received the full light dmg and did not die before the light chain dmg could land.
-Relogged, unequipped/equipped the weapon. 
-Verified the latent effect applied the stats it showed.
-Tried to talk to the questgiver regardless

Could someone look into this please. If only to check whether i accumulated any WS points at all would be greatly appreciated.

Regards

Monza, the monk on Eden

**Comment by KnowOne134** [comment]
Can you check if you have the key item you get with quest, I believe its annals of truth.  Seen before that the keyitem doesnt give sometimes and can't complete without it

**Comment by Rinkanu** [comment]
Indeed i only have the "weapon training guide" key item
I do not have the annals in temporary nor permanent key items.

How can i get one reissued?

**Comment by KnowOne134** [comment]
Just looked it up. Weapon training guide is the keyitem needed. So your good on that end, you get the annals when you turn in the trial weapon

**Comment by Rinkanu** [comment]
Ah you had me hopeful for a swift and easy solution but anyways, thank you for the incredibly quick reply to my problem.
