### ISSUE TITLE
Lilith's Rod MP Drain effect broken/not working!

### ISSUE THREAD

**Issue by DrunkSkeeterPilot** [EdenServer/community#1981]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

Take a Lilith's Rod and attack Banshees or Amphisbaena, for example, and the MP drain effect will never proc.

According to XI wiki going back to 2007, it should proc fairly often:
------------------------------------------------------------------------------------
https://ffxiclopedia.fandom.com/wiki/Lilith%27s_Rod

The Additional Effect on this weapon triggers very frequently (~20-30%). It generally drains up to 25 MP per hit
------------------------------------------------------------------------------------

I spoke to a staff member and they said the effect is not yet implemented.

I overpaid for this item, so I hope this gets picked up and fixed soon!!

Thank you for your attention.

**Comment by bkesecker** [comment]
Fortunately, this is a quick fix, and one I have been focusing on.
