### ISSUE TITLE
King Vinegarroon spawn conditions are incorrect.

### ISSUE THREAD

**Issue by Kurtalicious** [EdenServer/community#1982]
KV spawn conditions are not correct.  I have witnessed him violate all the below rules multiple times.  He is supposed to pop at the beginning of earth weather but he can pop at anytime during single or double earth.  He is not a guaranteed popped during double earth.  And, I have seen double earth weather carried over past the 21 hour mark and he did not pop.  

Been camping KV religiously for a few months now.  I can provide you with video proof but I'd rather you just believe me, do an investigation and fix the problem.  I don't want to have to clip/edit the 8 hour+ videos cause it will take about 1-2 hours for me to edit them and upload them so you can view them.  It is a huge pain in the ass.  Please fix.

The following rules are sentences straight from wiki:

"Will only spawn at the beginning of Single Earth or Double Earth weather."
" If Double Earth weather is present, King Vinegarroon will spawn."
"Can spawn via an earth weather effect that was present prior to opening and carried over past the twenty-one hour mark (but only during the moment it carries over, ruling it together with the prior notation)."

**Comment by dowzer** [comment]
FFXIclopedia's spawn conditions seem to be correct.

I'm not sure how helpful this will be, or how much evidence must be amassed for a correction to be made. Here is a video of it spawning at the beginning of single and double earth weather on retail.

https://www.youtube.com/watch?v=Tvvm0OV5SFQ

**Comment by Mozzy4Ever** [comment]
Have camped KV quite a few times on Eden and haven't seen it violate the wiki spawn rules so far

**Comment by 59blargedy** [comment]
this was based on cluster restarts is my guess, as he's not set to persist across those. i dont think he should be based on the low frequency of restarts, and era practice of maintenance resetting the window, so closing.
