### ISSUE TITLE
Adventuring Fellow Quest - Picture Perfect

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#1983]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

After completing Past Reflections, A Pose by Any Other Name and raising my fellow bond to 35+ with a level 50 fellow, I was unable to begin the quest Picture Perfect with Diederik. When speaking to him he gives the following dialogue as if I don't meet the requirements.
![image](https://user-images.githubusercontent.com/46270382/63642256-9939cf80-c68a-11e9-9f5a-44d7fb991a15.png)
I also tried having the signal pearl equipped/unequipped and in my inventory instead of in my mog wardrobes but had no luck either.

https://ffxiclopedia.fandom.com/wiki/Picture_Perfect

version 30181205_0

**Comment by KnowOne134** [comment]
You sure you have 35 bond?  How have you determined this?

**Comment by FariskaEden** [comment]
Past Reflections required 30 bond to begin and I completed it the day of the patch. I have talked to my fellow each day and summoned them 5 times since I completed it which should have given me more than 5 bond.

**Comment by KnowOne134** [comment]
Doesnt really work that way in era. Give it another 2 days of summoning it and talking

**Comment by E5una** [comment]
I am observing the same behavior as Fariska. I have completed Past Reflections, have called and talked to my NPC 5+ times each, have lvl 50 NPC and my Signal Pearl in my inventory and observe the same results when trying to flag this quest. 

Per the patch notes, we should be able to raise our bond by 1 each day by talking @ the rendezvous point, so that alone should be sufficient I would think.

**Comment by KnowOne134** [comment]
Tacktics pearl quest is uncoded besides getting the ki to start it still

**Comment by KnowOne134** [comment]
Can close, have spoken to another player after this update and it works now

**Comment by FariskaEden** [comment]
I can confirm I was able to complete the quest and increase my adventuring fellow's level cap since the patch. However the only weird thing I noticed was that in some cutscenes my adventuring fellow was replaced with a dark elemental.
![image](https://user-images.githubusercontent.com/46270382/64195211-ec600f00-ce4e-11e9-8e0a-2158efa9b565.png)

**Comment by KnowOne134** [comment]
correct its in a note, that cs's inside on bastok involving fellow have a visual bug
