### ISSUE TITLE
Tactics Pearl Quest Not Implemented

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#1986]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

My Adventuring Fellow has given me an Emptiness Investigation Note, I have completed Past Reflections and called my NPC for a week via Signal Pearl and Rendezvous Point, so I should have 35+ bond since I had 30 bond when Past Reflections was released a week ago. Clicking the ??? in Promyvion still does not call my NPC though.

Version: 30131205_0

**Comment by Mahou81** [comment]
I would like to see this implemented. The Tactics Pearl makes fellow much more useful. Sorry for the bump.
