### ISSUE TITLE
Vodyanoi NM spawning outside of 20:00-4:00 on Phanaeut Channel Boat Ride

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#1988]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Client ver. 30181205_0

I got on the boat from south channel to north channel during the day (Vana'diel time around 10:00). The NM Vodyanoi was up immediately upon the boat's departure but despawned a few seconds later. According to the wiki, it should only spawn between 20:00-4:00 and despawn after 4:00. Since the initial boat ride was around 10:00 Vana'diel time, it should not have been up at all. 

To replicate, just try riding the boat during the day from south to north channel when the NM has not been killed recently (supposedly 12-15 hour respawn) to see if it will spawn outside of its night time hours.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
