### ISSUE TITLE
Dark Spark not spawning

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#199]
Dark Spark did not spawn when I was doing MNK AF hands quest. Instead I just searched the other torch and immediately got the Shadow Flames without having to fight him.

**Comment by gweivyth** [comment]
I just did this quest and Dark Spark spawned as usual. Nothing seemed to off when I did it. 

I was also doing Temple Gloves, too.

**Comment by Matsur000** [comment]
Just experienced the same bug as Serephim but for BRD AF hands. 3 Torches gave the "There is nothing out of the ordinary here." with the final one giving the key item without spawning Dark Spark.

**Comment by Setz0r** [comment]
My guess is that the quest isn't resetting after the last person who completes it.

**Comment by Setz0r** [comment]
@Serephim @Matsur000 did either of you help previous people kill dark spark before doing it for yourself?  Like at ANY time previous, even months ago.

**Comment by NovadragonZero** [comment]
Came Across this bug, it still exists.

What you need to do is activate the quest from Guslam, but do not talk to the Borghertz. Go straight to Dark Spawn instead and you will be given the Shadow Flames. Then go to Borghertz and will skip the request cut scene and give you the gloves.

[https://i.imgur.com/wbP7QiJ.png](url)

**Comment by KnowOne134** [comment]
can not reproduce issue, code reviewed
