### ISSUE TITLE
Healing Staff Latent Not Working

### ISSUE THREAD

**Issue by DrunkSkeeterPilot** [EdenServer/community#1991]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

Steps:
Equip a Healing Staff and cure someone with low health, both with the staff equipped and unequipped. Curing with Healing Staff equipped and unequipped results in same amount of HP being cured each time. Staff is supposed to grant 10% to curing potency:

https://ffxiclopedia.fandom.com/wiki/Healing_Staff

I'm guessing this is just another of the latents on weapons that has yet to be fixed. Hope it gets patched soon, since I bought it for this specific effect!

Thank you for your attention.

**Comment by beauxq** [comment]
That is not sufficient for steps to reproduce. You also have to make sure it's not lightsday or darksday or light weather or dark weather.

Did you make sure it wasn't lightsday or darksday or light weather or dark weather when you tested it?

The cure potency on healing staff worked when I tested it.

**Comment by DrunkSkeeterPilot** [comment]
I tested further and conclude it must have been light/dark day disrupting the effect, I tested on other days (firesday) and get consistent 10% results. Closing.

**Comment by bkesecker** [comment]
Glad it is working.  Thank you for coming back to close in GitHub.
