### ISSUE TITLE
Shii bug

### ISSUE THREAD

**Issue by rathorse** [EdenServer/community#1993]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Sukesada is suppose to be 100% drop
![ffxi_2019 08 29_14 57 52](https://user-images.githubusercontent.com/54687166/63973881-4e94ca80-ca71-11e9-9f74-40e82365899b.jpg)

**Comment by bkesecker** [comment]
No research or evidence, no problem, but do try to provide it in the future please.  Certainly helps make development more motivated.

https://ffxiclopedia.fandom.com/wiki/Shii?oldid=376441

> Item Drops: Sukesada drops 100% of the time.

http://ffxi.allakhazam.com/db/bestiary.html?fmob=1843

> Guaranteed drop(s): Sukesada

http://ffxi.somepage.com/mobdb/67

> Item Drops: Sukesada drops 100% of the time.

**Comment by rathorse** [comment]
Did you notget the picture in my post? I killed shii and he didnt drop the
gk.

**Comment by bkesecker** [comment]
> Did you notget the picture in my post? I killed shii and he didnt drop the
> gk.
> …

I provided the links needed to resolve this issue for whoever picks it up, with the intent of speeding up resolution.
