### ISSUE TITLE
Stuck in bastok market but area is all grey

### ISSUE THREAD

**Issue by thorules** [EdenServer/community#1999]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by thorules** [comment]
Am Stuck in bastok Market unable to move.  I have logged out and back in.  Area is all grey with buildings looking dark as if I am standing on cloud.

**Comment by KnowOne134** [comment]
use the command /s !unstuck
will give you stun for 20 mins then send you to your HP
then you can close issue its happens sometimes

**Comment by thorules** [comment]
worked thanks
