### ISSUE TITLE
Aftermath on relic weapons.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#2]
Looks like Aftermath effects are still active even on the level 75 versions of these weapons.   From what I can tell, these weren't added until 2013 per the revision history on this source.  I tested this with both Mandau and Excalibur and it seems to apply to both.  Update: Also tested with a few others, all of them are active.

http://finalfantasy.wikia.com/wiki/Aftermath?action=history

**Comment by Lilswitche** [comment]
Thought I'd make a reply here as this was discussed in Discord.  Aftermath effects were active in the game when the Relic weapons were first added.  The page for Aftermaths wasn't made til later on, but individual aftermaths can be verified on the Relic WS pages.  

e.g. [Mercy Stroke](http://ffxiclopedia.wikia.com/wiki/Mercy_Stroke?oldid=381801)
[Catastrophe](http://ffxiclopedia.wikia.com/wiki/Catastrophe?oldid=86385)
