### ISSUE TITLE
Traveling conquest vendors missing

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2000]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30190328_2

Valeriano is no longer appearing in any city, no matter the rankings. Last week (Aug 25-31) he should've been in Sandy (no conquest ties). This week (Sept 1-8) he should be in Bastok. Bastok is rank 1 with Sandy 2nd, windy 3rd. Windy allied with sandy. He's not in Port Bastok though, nor is he in Sandy or Windy areas.

**Comment by perkuprightmeow** [comment]
Wanted to expand that Ominous Cloud & Nokkhi Jinjahl who are also tied to conquest are MIA from Port Bastok (& all other locations).

**Comment by godmode** [comment]
I am not sure what happened here. The code must have skipped this somehow. I will look into it but for now I've ran the code that updates them manually so they should be good to go again.

**Comment by gweivyth** [comment]
This doesn't appear to be working.  Bastok is in first place right now but the NPCs don't seem to have migrated to Port Bastok.

**Comment by InoUno** [comment]
Resolved in February 22nd, 2021 patch.

**Comment by panicstevenson** [comment]
I don't know if maintenance or the patch implementation messed with this week's location, but Valeriano is currently in Port Bastok (Bastok tied for second with Windurst) while San d'Oria is in first place.

**Comment by InoUno** [comment]
Thanks for notifying! It should be fixed live now.
