### ISSUE TITLE
Ominous Cloud, Nokkhi Jinjahl Missing from Bastok (Outright 1st Place)

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2001]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

When any nation is in outright first place Ominous Cloud and Nokkhi Jinjahl should be there. Bastok is in outright first place, and neither are in Port Bastok. In addition the travelling circus is missing. 

https://ffxiclopedia.fandom.com/wiki/Nokkhi_Jinjahl?oldid=260641
https://ffxiclopedia.fandom.com/wiki/Ominous_Cloud?oldid=347409

**Comment by godmode** [comment]
Going to reference Mozzy's report here. Thanks for commenting on that report. #2000
