### ISSUE TITLE
Light Shot accuracy too high

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#2002]
Light shot seems to be nearly unresistable, even on high level HNM. Fafnir and Jormungand were both chain slept without resist. 

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Oyaziiiiiii** [comment]
Tiamat was chain slept every landing as well with light shot. I imagine this lands at(or close to) a 95% rate for any monster that can be slept.

**Comment by YarAsti** [comment]
Light shot also overwrites itself which it should not be able to do...

Here is a pic of it overwriting itself:
https://gyazo.com/4165b3601852fcd74fa1e4c5a1b35eb2

If the mob is already slept it should take no effect:
https://gyazo.com/92dd30cf7d0ab827c0751ec0a763d470

**Comment by StriderClerix** [comment]
If this is an issue that has been bug reported, why are there linkshells still using light shot spam as a strat to kill Tiamat?

**Comment by Volkaru** [comment]
There is something going on with accuracy on certain HNMs, etc. But during exp it seems to have average acc. at 54 in Colibri party every ten or so misses even with light staff. It might be a level correction thing.

**Comment by Caelic** [comment]
So a few things:

Base effect accuracy is 70%
+/- 2 MACC = +/- 1% to hit rate
level difference is hard capped. anything beyond 5 level difference is just treated as 5 level difference. the hit rate penalty is additive flat -15% at 5+ level difference.
+/- 2 AGI = +/- 1 MACC for quick draw effects, so
+/- 4 AGI = +/- 2 MACC = +/- 1% hit rate
example: a character with 80 AGI = flat, additive +20% to hit rate (does this seem absurd to anyone?)
also, even though COR has a B in Marksmanship, the effect's hit rate is being calculated as if COR had an A+ in Marksmanship so basically think red mage-tier enfeebling rates along with the monstrous MACC added from AGI

this is just magic hit rate alone. if the hit rate misses but the resist is only 1/2 resist, it will still stick with 1/2 duration. 3/4 resist and beyond (7/8 resist, 15/16 resist) still causes the effect to fail however.

**Comment by JDFlashffxi** [comment]
As far as i know all shots have a base accuracy not effected by any skill, this accuracy is then improved upon by stats. So with something like light shot having a base accuracy, its understandable its less accurate at lower levels due to having less stats to apply to its overall effect. at 75 with all agi gear up to +90 agi (45acc) and ele staves(30acc) + warlock roll adding up to an additional +20 mag acc, the accuracy bonus, the chance to hit is HUGE, on top of that light based sleep is in an different resist pool then dark based sleep that blm and rdm use. so to compare their landing effect rate doesn't prove much,

**Comment by Caelic** [comment]
right. what i said wasn't the full story. that base accuracy is based on your level and is calculated as if you had a maxed A+ skill. at level 75 it calculates as if you were using an enfeebling spell with 276 enfeebling skill, even if your marksmanship is literally 0. that's where the base acc comes from

also the only thing known about agi is that increasing it increases accuracy, nobody knows where the STARTING POINT is. in darkstar it was just assumed that the starting point is at 0 AGI which i don't think is right. if anything i'd bet that the stat calculation is actually the difference between your AGI and the mob's AGI. a lot of other calculations with the core 3-letter also work on a stat difference basis between yourself and the target so it'd make sense.

**Comment by Slamm21** [comment]
the calculation would be exactly that, the difference between your agi and mobs agi.
Just like with rdm your enfeebles use Dint or Dmnd

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 update.
