### ISSUE TITLE
Issues with "rage" 

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#2005]
1. The rage is supposed to ramp up quickly over time but it seems instantaneous.
2. The monster's magic damage should increase but it doesn't. Eg. Fafnir hurricane wing damage should increase while raged.
3. COR elemental shots and physical SMN bloodpacts still do substantial damage.
4. There should be a noticable increase in attack speed. 
5. BLM nukes currently do 0 damage. While their damage should be reduced and resist rates much higher, they should be able to do some damage.

https://www.youtube.com/watch?v=aK5pVFqCtzs&t=486s
https://ffxiclopedia.fandom.com/wiki/Rage

### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by setsuk0** [comment]
PUP pet still does a lot of damage to a raged mob. Observed a PUP pet hit a raged KA for 847dmg bone crusher and consistently melee for 140-186 dmg each hit.

**Comment by phazedMD** [comment]
PUP pet was under the affects of Overdrive (2H).

**Comment by Volkaru** [comment]
There IS an issue with Automaton autos ignoring special defense, though. They do full damage to elementals, etc. for example.

**Comment by KnowOne134** [comment]
It's the same with all pets.

**Comment by godmode** [comment]
Several pets have had a damage type set. I suspect automatons accidentally got left out.

**Comment by FariskaEden** [comment]
Automaton damage seems fine versus elementals now, here's an example versus a level 44-46 ice elemental from a 75 automaton. 
![image](https://user-images.githubusercontent.com/46270382/65822684-5c777000-e216-11e9-9b91-62f035f73d81.png)
I have yet to fight anything enraged so it could just be an issue with that.

**Comment by Volkaru** [comment]
Guess it got fixed at some point during my absence.
