### ISSUE TITLE
Error Code: FFXI-3321

### ISSUE THREAD

**Issue by Sworn777** [EdenServer/community#2006]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
After update this error code prevents play.

**Comment by Mozzy4Ever** [comment]
Checklist is there for a reason.

3321 during character creation is because your character name is invalid (typically taken, though can also be caused by the language filter)
