### ISSUE TITLE
Unbridled Passion No Title Granted

### ISSUE THREAD

**Issue by Raizuo** [EdenServer/community#2007]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Not a big bug but nonetheless a bug. Just finished Unbridled Passion after 9/2/2019 patch and noticed that the title of Paragon of Ranger Excellence was not granted yet the Hunter's Socks was granted. Unable to reproduce steps due to the nature of quests.

Ver 30181205_0

**Comment by bkesecker** [comment]
Confirmed.  PARAGON_OF_RANGER_EXCELLENCE is the label not set in the appropriate Lua.
