### ISSUE TITLE
Windurst Outpost Warp NPC moved back to "new" spot.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#201]
I had to do a server restart last night after a few players crashed it while trying to do mission 2-3.  After we got back up and running, someone reached out to me and said that they outpost warp NPC was "gone."  We went and looked at the spot it used to be at before they were moved, and there he was, back in his original spot. 

Sorry if I broke it.

**Comment by godmode** [comment]
This was intentional. It was something I patched in but wouldn't take effect until next reboot. But since the server kicked the bucket earlier than the next patch I couldn't write about it.
