### ISSUE TITLE
Cooking recipe missing from Auction house + OOE recipes

### ISSUE THREAD

**Issue by him911** [EdenServer/community#2010]
### Checklist

- [yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [yes ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [yes ] I have provided my client version in the details. (type /ver into your game window)

### Details

The recipe for NQ Coffeecake muffin is currently not listed visibly on the auction house even though the HQ variant is(coffeecake muffin +1)

Also the following are Out of Era recipes that can be crafted atm. 

Red curry bun
Yellow curry bun
Goulash
Kitron juice

**Comment by EpicTaru** [comment]
https://github.com/EdenServer/community/issues/496

**Comment by him911** [comment]
Yeah the list you keep referencing had mistakes. Coffeemuffin cake was included before wotg

**Comment by mlandrum22** [comment]
I'd like to weigh in on the curry buns. I see them as more of a QoL improvement, similar to stacking ores (which is also OOE). No one wants 3 hour Dynamis food, and we already have similar styled foods (turn 3-hour foods into 6 30-minute foods) in the game in era like Tacos and Coeurl Subs. 

They aren't level 100+ synths, and shouldn't affect markets for other foods, so I think it's nice to have them around.

**Comment by him911** [comment]
I agree. For some of these late recipes, removing them leaves certain ingredients completely useless, yet still very common from harvesting and planting.  But Its one or the other or have someone pick and choose what stays and what doesnt, and 7 other crafts to call for the same reasoning.

**Comment by Jimmayus** [comment]
I dunno if any work has been done on this bug report but Kitron juice is still craftable as of 12/20/2019.

**Comment by KnowOne134** [comment]
these have been removed
