### ISSUE TITLE
Leaping Lizzy top placeholder is spawning in the same location.

### ISSUE THREAD

**Issue by gtapperdesign** [EdenServer/community#2012]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

As requested on ticket #1634 - created a new ticket for similar behavior on another NM

After several Leaping Lizzy kills, I can confirm that the top place holder LL spawn will always spawn at the southeast corner of F-8. Bottom place holder LL spawn is still randomized.

Stardew | Valley
version 30181205_0

**Comment by KnowOne134** [comment]
all normal mobs in all of DSP spawn in same location, only NMS have the code ability to have have multiple locations

**Comment by gtapperdesign** [comment]
No, not the placeholder. I mean the Leaping Lizzy spawn by the top place holder. Leaping Lizzy is spawning in the same location when spawned in the top placeholders place.

If spawned from the bottom placeholder, Leaping Lizzy's spawn location is random.

**Comment by Mozzy4Ever** [comment]
Can confirm what gtapper is saying. The western (aka lower) Leaping Lizzy has varied spawn locations. The Eastern (aka top) Leaping Lizzy has only 1 spawn location.

**Comment by KnowOne134** [comment]
Note to self:
ID 17215868 needs NM_spawn_points set
