### ISSUE TITLE
Luisant Set sub crafts

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#2013]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I was considering farming the aluminum to make some of this set, until I noticed it is only T1 in Eden's database:

Luisant Haubert:  Smithing (64), Goldsmithing (51), Clothcraft (1)

This item along with all the Luisant pieces should be T2, i.e. GSM and Cloth subs should require no higher than ~30.

Here are some discussion threads about this set:

https://www.bluegartr.com/threads/50646-Luisant-Haubert
https://www.bluegartr.com/threads/35023-Luisant-Haubert-HQ-rate
https://www.bluegartr.com/threads/35971-Luisant-set-on-Bahamut-server
https://www.bluegartr.com/threads/57360-Luisant-set-sub-crafts

**Comment by ShiyoKozuki** [comment]
That explains why these items aren't on the AH.
