### ISSUE TITLE
thief's kote

### ISSUE THREAD

**Issue by itachioax** [EdenServer/community#2014]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
im already 0/20 on those gloves, anyone have idea if this nm is broken??? (just dropping seals and thief's test nothing else)
i mean i already got a pair of fudos from decapitator, but no one kotes from tracker

**Comment by Mozzy4Ever** [comment]
![image](https://user-images.githubusercontent.com/11255886/64442917-60d8bf00-d096-11e9-9177-37d2377cc61c.png)

Looks like in base DSP it has a 10% drop rate so you could just be getting unlucky

**Comment by itachioax** [comment]
ty so much, ill keep trying

**Comment by Iamtheproof** [comment]
Can confirm NM is not broken. I am 1/11 for these. If you want to buy them HMU in game. Proof is character name.

**Comment by KnowOne134** [comment]
Correct as any RNG even at 80% you can be unlucky 20 times still. But it is not broken, closing
