### ISSUE TITLE
Chat filter resets bug

### ISSUE THREAD

**Issue by moonyaco** [EdenServer/community#2018]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

![image](https://user-images.githubusercontent.com/54994876/64445032-15f78f80-d108-11e9-9fd0-7b1a6fe6050b.png)

Chat filter resets every time a party is forms/disbands. A similar bug shared by another private server but not on retail. With the bug in place, players would always need to go to config>chatfilter and redo their chat filter every time they join a new party.

**Comment by KnowOne134** [comment]
Duplicate issue, believe that this filters are saved in playonline and not in game themselves. Can close the issue as it's been reported and still open

**Comment by Tjonke** [comment]
Get the addon "Filters" to get around the issue.

**Comment by Mozzy4Ever** [comment]
> Duplicate issue, believe that this filters are saved in playonline and not in game themselves. Can close the issue as it's been reported and still open

From what was explained to me via Atomos, iirc it can be handled by the server (or, maybe the loader?). The data just isn't handled properly.
