### ISSUE TITLE
Text/KI name missing - "Art for Everyone" in quest "Early Bird Catches The Bookworm"

### ISSUE THREAD

**Issue by nickycupcakes** [EdenServer/community#2021]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver: 30181205_0

Reproducable steps:
1)  Begin "Early Bird Catches the Bookworm"
2)  Speak to Furakku-Norakku
3)  Note missing KI name in text

During the quest "Early Bird Catches The Bookworm" (https://ffxiclopedia.fandom.com/wiki/Early_Bird_Catches_the_Bookworm) Furakku-Norakku references the book "Art For Everyone" (which I think is a KI).  I think he should say:

"Some Hume named Orn still has the book 'Art for Everyone' out on loan" 

but instead says (note the space where KI name should be):

"Some Hume named Orn still has the book  out on loan"

**Comment by godmode** [comment]
Well typed out report. Thanks.

**Comment by Tavnazian** [comment]
This must be reopened as it has either not been fixed, or has been broken again.


![Missing word](https://github.com/EdenServer/community/assets/86973967/cee716f8-7877-4728-a484-012a7247b6bd)

**Comment by Tavnazian** [comment]
further in the quest, Orn's dialogue omits the overdue book ki. 
![Missing 2](https://github.com/EdenServer/community/assets/86973967/e0a91f46-32fa-4be3-ba3e-860512d9d0b4)
![missing 3](https://github.com/EdenServer/community/assets/86973967/2fe246a9-cef3-4ccb-984a-78a87c089b58)
