### ISSUE TITLE
Unable to receive a Siren's Tear unless you are on quest or have completed. Required for BLU unlock

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2026]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

The quest for unlocking BLU requires one of three items, One of those being the Siren's Tear you pick up in North Gustaberg around the river near Port Bastok entrance. This stone should be free to pick up as soon as you've flagged the quest for BLU (An Empty Vessel) but on Eden it requires you to also be on the quest "The Siren's Tear" from Wahid in Bastok Mines. Or have completed this last mentioned quest and then talked to Carmelo in Port Bastok. That isn't a required step in any era of the game, as you could just go get the stone as soon as you wanted. 

Game ver: 30181205_0

**Comment by gweivyth** [comment]
This must be new, I unlocked Blue Mage a few months ago without this issue.
