### ISSUE TITLE
Quest Picture Perfect - Minor Display Error

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#2027]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

30181205_0

Duing two of the cutscenes for Picture Perfect my fellows, both Tarutaru, where displayed as Galka / FireElemental.
Forgot to make a screenshot, but it happened both times after receiving a CS from Umberto in Bastok Markets iirc.

**Comment by KnowOne134** [comment]
Known error, all fellow CS in bastok dont show correctly

**Comment by ayther** [comment]
My Npc appeared as a ice spirit, during the final CS of this quest, the all other CS with the NPC had them in full scale armor(even though mine has different armor on, not a big deal).
I choose Option 1 Angelica path.
![Minu_2020 06 09_165711](https://user-images.githubusercontent.com/58160592/84199289-e6006280-aa72-11ea-9dd4-819e649d2203.png)

**Comment by KnowOne134** [comment]
Fixed 12/28/2020
