### ISSUE TITLE
Hakutaku Magic Resistance is Very High

### ISSUE THREAD

**Issue by Wade9363** [EdenServer/community#2029]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

Version:  30181205_0

This may or may not be intentional, but when a Million Eyes pet casts any magic on Hakutaku the damage is a tiny fraction of what it was on retail.  Flare was hitting for around 25 dmg, Water IV ~50, Thundaga III ~50.  

The behavior of Million Eyes pets makes is much more difficult for them to hold hate.  On retail, they would only Cast magic if Sic was used while they were out of range of their target.  Otherwise they just meele like any normal pet.  If my memory is correct, Flare would hit Hakutaku for ~800 dmg on retail.  I remember this behavior very well because as a Bst I would intentionally pull my pets back and use Fight/Sic in the hope that my pet would cast a strong spell every 3:00.

On Eden, a Million Eyes pet will regularly cast Magic just like they would if they were an enemy mob.  They'll do this the moment I use the Fight command, and at regular intervals while meele'ing.

The result of this is that a Million Eyes pet regularly stops to cast spells with long cast times, does little to no damage, and cannot hold hate on Hakutaku worth a darn.

This may be a difficult thing to fix.  If you simply reduce Hakutaku's magic resistance so that spells hit him as they would, Million Eyes pets will be overpowered.  Left as is Million Eyes pets are underpowered (only vs Hakutaku: vs normal mobs they currently OP).  

Changing Hakutaku's magic resistance would require also changing pet behavior to stay balanced.

**Comment by rpcon** [comment]
I'm not sure what was changed, but as of now (Sept 20), charmed Million Eyes in Den of Rancor do not use TP moves. Ever. Even when commanded to Sic. They just cast spells - even in melee range - and do auto attacks.
When fighting Million Eyes, the behavior is as expected regarding TP moves and spells.

**Comment by 59blargedy** [comment]
magic resistance issues resolved in March 1, 2021 update. if there's still an issue with charmed eyes, can you file a new bug report please?
