### ISSUE TITLE
Bune respawning too fast

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#203]
Pretty sure Bune is respawning much faster than 21 hours. Sorry for lack of further details.

**Comment by godmode** [comment]
If he's doing this other than after a server reboot please inform me. I've checked the code and he shouldn't. But we both know that hasn't stopped ninja code from doing weird things on the side!

**Comment by Aneyus** [comment]
I camped him for several more days after this ticket and everything seemed normal. It was probably just the rogue server restart that messed things up a bit originally.
