### ISSUE TITLE
Cesti missing at merchant Ashene in Sandy

### ISSUE THREAD

**Issue by Skerxan** [EdenServer/community#2030]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I was about to craft Lizard Cestis when I noticed that Cesti was not being sold by Ashene.
I checked Wiki at around 2005-2006 and it was being sold by her regardless of Conquest rank.

plz add :(

**Comment by KiplingFFXI** [comment]
Bumping this rather than submitting a new report.

Wiki showing she sells it in era: https://ffxiclopedia.fandom.com/wiki/Ashene?oldid=632150

https://ffxiclopedia.fandom.com/wiki/Cesti?oldid=329263

**Comment by ffxireports** [comment]
Bumping this. Ashene is supposed to sell these if Sandy is any rank

https://ffxiclopedia.fandom.com/wiki/Ashene?oldid=360763
https://ffxiclopedia.fandom.com/wiki/Cesti?oldid=329263

Please fix.

**Comment by Balrahn** [comment]
Bump please fix

**Comment by 59blargedy** [comment]
resolved december 7 update
