### ISSUE TITLE
0 damage dealt with high damage AoE

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2034]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I've been farming on my summoner recently and have been repeatedly noticing that Ramuh's Thunderspark will occasionally hit one low level mob for 0, while the rest are getting obliterated (See screenshot). This has happened to me on every monster I've farmed, which admittedly has only been Boggarts and Air Elementals. (Also as a side note and potentially separate ticket, the damage seems excessive, but this ticket is for 0 dmg bug).

Also the mob that it says takes 0 damage actually takes 0 damage, they are alive each time, it is not just a logging issue like the 0 damage Feather Storm BLU issue.

![0Dmg2](https://user-images.githubusercontent.com/13668758/64879419-f25ea880-d623-11e9-97ea-3225199c9db6.PNG)

Version: 30181205_0

**Comment by godmode** [comment]
How many mobs were hit for damage and how many mobs were hit for 0? Is it the same amount each time?

**Comment by E5una** [comment]
I’ve never seen more than 2 take 0 damage in a batch of 7-8, but usually it’s 0 or 1. I’ll do some testing with different counts next time I farm air eles.

**Comment by godmode** [comment]
Have you ever seen more than 6 take damage at once? What about if there are less than 6 does one ever take 0 damage?

**Comment by E5una** [comment]
Good questions, and I'll make some time this weekend to gather some data for you. For starters, here are some screenshots from my SMN AF fight today (FYI Astral flow was on for the last one). There are 6 monsters at the start of the fight, and yes I can see one of them taking 0 when there are 6 of them, AS WELL as when there are only 4, but as you can see, sometimes they all get hit.


![Dryad1](https://user-images.githubusercontent.com/13668758/64901648-062cfd80-d66a-11e9-9009-3bd78a069472.PNG)
![Dryad2](https://user-images.githubusercontent.com/13668758/64901650-088f5780-d66a-11e9-9d99-0b57831e8668.PNG)
![Dryad3](https://user-images.githubusercontent.com/13668758/64901653-0af1b180-d66a-11e9-9a61-fb3b11b46d45.PNG)
![Dryad4](https://user-images.githubusercontent.com/13668758/64901655-0cbb7500-d66a-11e9-8fb7-5b1171e66e97.PNG)

**Comment by E5una** [comment]
I should do more testing on this, but here's a group of 7 where 1 had a shadow and 1 took 0 for no reason:
![image](https://user-images.githubusercontent.com/13668758/72183326-af3af900-33bb-11ea-8763-1d3360dd648c.png)

**Comment by E5una** [comment]
Ah, as requested, here is a screenshot of 5 mobs (notably less than 6) where one of them took 0 damage:

![image](https://user-images.githubusercontent.com/13668758/72184260-093cbe00-33be-11ea-8500-bf6afc7fbb54.png)

**Comment by KnowOne134** [comment]
but if you toggled all the mobs did 1 of them actually take 0 damage, it could just be a visual bug

**Comment by E5una** [comment]
Not a visual above as I mentioned above in a previous post, that monster will definitely still be standing and have taken 0 :)

**Comment by E5una** [comment]
And again, this time with only 4 mobs claimed  (3+a dragoon's wyvern):

![image](https://user-images.githubusercontent.com/13668758/72185098-0216af80-33c0-11ea-9ec4-cc62d91a8fb0.png)

I'll stop updating data now, but that should be helpful!

**Comment by 59blargedy** [comment]
i believe this has been resolved as a result of the summoner magic update, but please comment if you see issues moving forward and we can reopen
