### ISSUE TITLE
Windurst 9-2 breaks when going to Fei'Yin

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#2036]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver 30190305_0

After accepting Windurst 9-2 and completing the mission up to the final battle, traveling to Fei'Yin caused a Sandy mission CS to happen on both of my characters. I don't know which mission it was, I've never done Sandy, but they were talking about Orcs in Qi'bia Arena and Pieji cast Shell on Trion. 

Now I'm unable to initiate the fight "Moon Reading" At Full Moon Fountain. I was still able to enter the fight and assist my party members, but the game seemed to be treating me as if I had already completed the fight, which I hadn't. 

We sadly lost the fight, I returned to Heaven's tower to talk to the Star Sybil thinking it would fix my issue of not being able to enter the fight and the game gave me rank 10.

**Comment by godmode** [comment]
Good work on retracing the steps. This’ll definitely help in fixing the bug.

**Comment by Volkaru** [comment]
Since this was never closed, I decided to test these same steps to see if it had been patched. It is fixed, I got no CS in Fei'Yin, and was able to activate the mission fight just fine. Closing.
