### ISSUE TITLE
The Curse Collector blocking other Bastok quests?

### ISSUE THREAD

**Issue by Althaia** [EdenServer/community#2037]
### Checklist

* [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
* [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
* [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is: Version 30181205_0

So I've had an alt named Minimina in Bastok for a while now. When Minimina was a newb, I just went around talking to pretty much every NPC I could see, mostly in Bastok Markets and Mines.

Some time later, I wanted to complete the quest for Traveler's Hat, but no matter how much I spoke to the lady, her mother-in-law, all the people in the various houses around there, etc. I couldn't flag it.

Fame's not a problem, it's maxed on both my alt and my main. Then someone suggested that one of the other quests I picked up as newbie Minimina might've interfered, so I endeavored to complete all the quests in the quest log. I did them all but The Curse Collector, which would've been too much to attempt on an alt.

Since, as my main character Althaia, I was able to travel to Bastok and had no trouble completing the Traveler's Hat quest ("The Wisdom of the Elders"), I let it go. ( Although I did previously report it in a comment in #422 )

Now it seems The Curse Collector is keeping another quest from being activated on Minimina. It's the one where you turn in the Silver Name Tag. Once again, I traveled to Bastok as my main and had no problems doing the quest -- repeatedly, in fact -- on my main.

Here's a list of quests I believe can't be flagged because of The Curse Collector:

1. The Wisdom of the Elders - Benita - Port Bastok (J-6)
2. Fallen Comrades - Pavvke - Bastok Mines (I-7)

So I don't know if the issue is really The Curse Collector or if there's some hidden Bastok quest (not showing up in log) that's keeping either of these quests from being given to Minimina. Minimina's never gone to any other city, so the problem would have to be in Bastok.

Part of the reason I believe The Curse Collector is blocking these quests from being flagged is because for both quests, I was able to activate them on Althaia when she didn't have any Bastok quests active in her quest log at all.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
