### ISSUE TITLE
Promy animas not tradeable

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2038]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

From what I've been told/vaguely remember myself, the 3 animas (Psycho, Hystero, and Terro) were able to be at least traded/bazaar'd, if not AH'd as well. I can't find any information saying that this wasn't a thing across ffxiwiki, bgwiki, and allakhazam.

**Comment by Raphtalia1** [comment]
Unfortunately the update that made them traceable was during WoTG I looked it up earlier when I did promies here

**Comment by Mozzy4Ever** [comment]
Ah, damn. I started playing towards the end of toau so :(
