### ISSUE TITLE
Quest: Over the Hills and Far Away (for Ule.Range map) unable to be started

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2039]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

In order to start the quest you first have to read page 4 of a diary in Southern San d'Oria, but the diary only allows you to read page 1 and 2, tried for at least 10 times to advance past page 2 but no bueno.

**Comment by panfunk** [comment]
Did you do the necesary prequests? There were apperantly removed as prereq on retail but back in 2007 you needed to complete some to start this one:
https://ffxiclopedia.fandom.com/wiki/Over_the_Hills_and_Far_Away?oldid=398394
https://github.com/EdenServer/community/issues/640#issue-395088395
