### ISSUE TITLE
An Explorers Footsteps Bug

### ISSUE THREAD

**Issue by hrmitchell** [EdenServer/community#2040]
The mayor of Selbina seems to repeatably ask for whatever stone tablet I just turned in, and he accepts multiple copies of the same tablet with gil payout. So, one could, for instance, just keep trading the stone monument tablet near selbina over ... and over ... and over. Thank you for your time and hard work on Eden!

**Comment by bkesecker** [comment]
Good find.  Related https://github.com/EdenServer/community/issues/1812

**Comment by bkesecker** [comment]
After pouring over many GM accounts, this issue is directly related to failure of setting character variables.  Should get resolved with adoption of the improved way of storing this information.
