### ISSUE TITLE
Despawning NMs (Ulli Pallas Alky)

### ISSUE THREAD

**Issue by HunnyDoo** [EdenServer/community#2041]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

v30181205_0

If Ullikummi, Pallas, or Alky are dragged more than 50 yalms outside of their spawn area and deaggro, they'll despawn like a regular mob.  The only thing I can see these NMs have in common is that they were pop nms that were converted to other spawn conditions.  Who wants to test this out on a Sozu :P

**Comment by gweivyth** [comment]
Had this happen to me with Alky and I didn't even have to drag him anywhere.  I was clearing a path so I could pull him, and apparently he roamed too far on his own and despawned before I could get to him.  Pretty frustrating.

**Comment by StriderClerix** [comment]
This happened today with Ullikummi. He was in his spawn location, but depopped around the 15-20 minute mark.

**Comment by Balrahn** [comment]
I spent most of my (read: all) day trying to pop Ulli. He eventually popped and I tried to solo him. His regen was far too great though so had to call for reinforcements (regen should not be this strong). I had dragged him to the porter room. I slapped a bind on him and  proceeded to log out, so that I could lose aggro. When I logged back in he was still there and walking slowly back to the room. When he reached the door he despawned.

**Comment by icariumkupo** [comment]
I believe this is a side effect of any NM that was changed from force pop to lottery or free spawn. I've witnessed this depop behavior before on Big Bomb.

**Comment by Slamm21** [comment]
Testing this on the test server Ulli I aggroed Ulli right in the centre and let him kill me, and 3 minutes later he immediately despawned. Will test later if he does without being touched.

The above makes sense as to why he might be doing it.
