### ISSUE TITLE
Mobs resist subjob Stun way too often

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#2043]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

The spell "Stun" is resisted like 95% of the time be nearly everything in Tu'Lia when cast from /DRK.  My skill is not capped for subjob, however, in era retail, NIN/DRK could Stun sky gods, Tiamat, and tons of other mobs that did not have an inherent "Stun resistance" of any sort (ie. Fafnir, Nidhogg, KB, and some others).  NIN/DRK should be able to stun things but as it stands, they cannot.  Dark Magic skill is being checked each cast but it should not be on most mobs.  It should function like Flash for the most part and always land unless the mobs has stun resistance or builds it over time in a fight (ie. Cerberus, Khimaira).  

To recreate this, pop Suzaku and try to Stun on NIN/DRK.  It will resist it nearly every time.  I think in 30 casts I landed 1 Stun last night.  This completely nerfs NIN/DRK as a tank and it should not.  

I cannot provide video evidence but the wiki has information on what is resistant to stun and what isn't.  Players can probably chime in and confirm this too.

**Comment by godmode** [comment]
This will probably be resolved inadvertently in the latest patch with some Dynamis Xarcabard preparations. Let me know after the patch if it has or has not been resolved.

**Comment by greyenvy** [comment]
Glad to hear.  I look forward to it!

**Comment by greyenvy** [comment]
Glad to hear.  I look forward to it!

**Comment by Falaras** [comment]
This has not been resolved. Still a near 90-95% chance of Stun getting resisted from a Nin/drk.
