### ISSUE TITLE
The quests: To Cure a Cough and Over the Hills and Far away are bugged

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2044]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

The diary in Southern San d'Oria only has access to page 1 and 2, you need page 3 for "To Cure a Cough" quest and page 4 for "Over the Hills and Far away". 

Game ver: 30181205_0

**Comment by Althaia** [comment]
I went to the second floor and couldn't even find this diary, when I was doing "To Cure a Cough," but I was able to complete it anyway. Amaura still gives the required dialogue, asking for Thyme Moss.

I haven't attempted "Over the Hills and Far Away."

**Comment by bkesecker** [comment]
Althaia is correct.  Reading page 3 is not required to start To Cure a Cough.  However, make sure you don't have Thyme Moss or Cough Medicine key items.  If you do, may need to call GM.  There is a well known issue where sometimes quest progress doesn't get saved/reset randomly.
