### ISSUE TITLE
The quest: One Good Deed? is bugged

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2045]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

The quest called "One Good Deed?" in Port Windurst for the Attohwa Chasm map is bugged, the NPC "Chipmy-Popmy" doesn't give the cutscene required to start quest, no matter how many times you talk to him (I have rank 9 Windurst fame so not a fame issue). This was reported on in January and still no fix.

Game version: 30181205_0

**Comment by godmode** [comment]
Please do not knowingly duplicate issues or your access will be removed from bug reports.
