### ISSUE TITLE
A step is missing in An Eternal Melody CoP mission

### ISSUE THREAD

**Issue by slassen** [EdenServer/community#2047]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

Progress to through CoP missions to this mission. https://ffxiclopedia.fandom.com/wiki/An_Eternal_Melody

Finish step 1 and then while performing step 2 you should receive a dialog but you don't. Instead you can progress directly to step 3. Expected behavior is that it is mandatory to complete all steps in order.

**Comment by 59blargedy** [comment]
resolved with april 26, 2021
