### ISSUE TITLE
Shall Shell and Istiridye synth results incorrect

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#2048]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
The NQ for Shall Shells and Istridye should be Pebbles, not pearls.  

https://ffxiclopedia.fandom.com/wiki/Pebble?oldid=404711
https://ffxiclopedia.fandom.com/wiki/Pearl?oldid=144833

**Comment by Raphtalia1** [comment]
The NQ of shall shells and istirideyes were originally pearles, later an anti-rmt nerf made them pebbles and Hq pearles/black pearles, and an even later patch reverted them to Nq pearles and HQ black pearles

Since Eden works with anti-rmt nerfs rolled back this is likely the correct recipe

**Comment by Raphtalia1** [comment]
I posted a earlier recipe with the NQ being pearles

**Comment by translucentlights** [comment]
> I posted a earlier recipe with the NQ being pearles, also the alla post was updated in June 2007 to the pebble version, earlier versions are not available

The link you posted lists Pebble as the NQ.

**Comment by Raphtalia1** [comment]
That’s odd, when I check it shows pearles as the NQ, I’m on mobile though so maybe it’s not loading right :/

**Comment by Raphtalia1** [comment]
Even so I remember this being nerfed for the same reasons as rusty cap/pick/greatsword because RMT were abusing it.

Nerfing it here will piss off alot of fishers who already had their bite rates nerfed and once someone can find the patch notes it will have to be reverted.

**Comment by gweivyth** [comment]
2005 'clopedia says Pebble if you search for Pebbles. 

https://ffxiclopedia.fandom.com/wiki/Pebble?oldid=16004

**Comment by gweivyth** [comment]
2005 'clopedia says Pebble if you search for Pebbles.

https://ffxiclopedia.fandom.com/wiki/Pebble?oldid=16004

Also CTRL+F'd thru all of these up to 2008 and didn't find any changes to Pebbles nor Shall Shells.

http://www.playonline.com/pcd/verup/ff11us/update.html#
