### ISSUE TITLE
Jenglot (FeiYin Synergy NM) spawning

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#205]
https://github.com/DarkstarProject/darkstar/blob/09b3ddfe5f24190203a2ceb225c479bcc699d045/scripts/zones/FeiYin/mobs/Jenglot.lua

http://ffxiclopedia.wikia.com/wiki/Jenglot

While not a big issue, he spawns right near Miser Murphy (RDM AF NM) and is magic aggro. Could be a problem for newer players, and he has no purpose on this server since we don't have Synergy

**Comment by tectal831** [comment]
Duplicate of #206
