### ISSUE TITLE
Died in Moghouse

### ISSUE THREAD

**Issue by Twentytwox** [EdenServer/community#2051]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0

To reproduce, be poisoned, enter your mog house at very low (less then 5) hp. On zoning in, you will be dead, will full HP, the death menu will pop up, but wont let you home point.

**Comment by icariumkupo** [comment]
You forgot to block out your name in your game's window title. FYI 🙃

**Comment by Twentytwox** [comment]
Thanks! Am a bad. Now you know my secret🤯

**Comment by gweivyth** [comment]
Closing your client and reopening fixed this for me in the past.  Annoying, but quicker and easier than involving GMs.

**Comment by Aneyus** [comment]
Considered opening a new issue but this seemed related enough. Entering your Mog House should remove all debuffs that cause damage over time.

Source: My brain, and also https://ffxiclopedia.fandom.com/wiki/Mog_House

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
