### ISSUE TITLE
Bright Handed Kunberry

### ISSUE THREAD

**Issue by Sworn777** [EdenServer/community#2052]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

So, 1 hour after maintenance no spawn. 20 hours after maintenance no spawn... 21 hours no spawn... find out servers reset the night prior.. Wait another 10+ hours do not leave zone... Zone crashes again, 20 more hours go by. Do not leave zone... Zone crashes again... every single time this zone crashes his timer is being reset... I will never kill him at this rate. No one has out claimed me I have not slept in 40 hours. 

FIX THIS it is not okay to forever reset spawn time, i'd rather fall asleep and miss it than stay here for 48 hours and never see it spawn.

**Comment by rpcon** [comment]
Came here to post the same thing. Still broken.
