### ISSUE TITLE
True sight Kindred

### ISSUE THREAD

**Issue by Twentytwox** [EdenServer/community#2054]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Kindred Demons in Uleguerand Range are true sight. Could be same as issue #1800 . Made a new ticket as other was closed. Attached is Aggro types circa May 2007. Ran by while invisble and they aggro. 
Version: 30181205_0
![demons](https://user-images.githubusercontent.com/47615465/65191250-5c6eb780-da41-11e9-8747-07bdd9da84e5.png)

**Comment by setsuk0** [comment]
I posted on the old ticket, wasn't sure if I should make a new one. Also, the demons all check as "impossible to gauge" right now, which is also incorrect and was also bug reported once here #227

**Comment by perkuprightmeow** [comment]
Can confirm most (if not all) kindreds are true sight right now. Not a good time.
