### ISSUE TITLE
Suspected incorrect calculation for crit hit rate.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#2055]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [N/A] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [N/A] I have provided my client version in the details. (type /ver into your game window)

### Details

Based on some in game testing and scanning through base DSP, I suspect the incorrect formula may be in use for calculating critical hits.  Base dsp uses the following:

`            int32 dDEX = std::clamp(attackerdex - defenderagi, 0, 50);`

`          crithitrate += (dDEX * 30) / 100 + PAttacker->getMod(Mod::CRITHITRATE) + PDefender->getMod(Mod::ENEMYCRITRATE);
            crithitrate = std::clamp(crithitrate, 0, 100);`

As you can see the correlation between adding dex gear is linear with crit rate based on this formula, however, on retail this was not the case.

The formula for calculating crit hits remains the same on retail now as it was back during ToAU era.  The table formula for melee crit hits can be found [here.](https://www.bg-wiki.com/bg/Critical_Hit_Rate)  It also includes the formula for calculating the crit hit rate of ranged weapons.  

Here is the table in question for melee hits:
> dDEX | Crit Rate
>    0-6 | +0%
>  7-13 | +1%
>14-19 | +2%
>20-29 | +3%
>30-39 | +4%
>40-50 | +(dDEX-35)%

**Comment by 59blargedy** [comment]
now using correct formula
