### ISSUE TITLE
Defense went negative and rolled over to 65445

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#2056]
### Checklist

- [ x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I was a level 1 thf/blm and ate a Nashmau Stew (gives -10 VIT/AGI/INT/MND/CHR, and -100 evasion/defense).

Evasion correctly was 0 after /checkparam, but defense went up to 65445.

When I fought a level 4 T bunny, I was getting hit for 0 to 2 so it feels like it was using the 65445 in it's calculation and it wasn't just a visual bug (my VIT was 0 after the food, I'm pretty sure).

**Comment by FariskaEden** [comment]
![image](https://user-images.githubusercontent.com/46270382/72023380-9954f900-3240-11ea-99ea-d722a2a240b4.png)
I was on BLU and equipped a shotel (which gives -shield skill) and my shield skill rolled over into a high positive amount as well.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
