### ISSUE TITLE
Lord of Onzozo does not aggro a level 75 character to sound.

### ISSUE THREAD

**Issue by Kurtalicious** [EdenServer/community#2057]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

Lord of Onzozo does not agro a level 75 character to sound.

**Comment by 59blargedy** [comment]
may have been an old navmesh issue, as i cant duplicate it now and it aggros level 75 consistently
