### ISSUE TITLE
Haste belts possibly coded wrong

### ISSUE THREAD

**Issue by everlast101069** [EdenServer/community#2059]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
Game ver: 30181205_0

Haste belts were an item you used in your waist that had to stay equipped and used as an item every 3 minutes. They had 20 charges and they would give you the status symbol of haste along with you having the spell haste icon beside it. These effects were cumulative to each other along with marches. I might be reading this wrong in code but it seems it checks for spell haste and then applies if not there not adding additional to it. I know it does this because i used them countless times before. Here is the link to the DSP code with this line in particular: 
if not target:hasStatusEffect(dsp.effect.HASTE) then target:addStatusEffect(dsp.effect.HASTE, 1000, 0, 180)

https://github.com/DarkstarProject/darkstar/blob/08c45198354141ea62b0c9cfeadd32187a3af55c/scripts/globals/items/haste_belt.lua
Wiki:
https://ffxiclopedia.fandom.com/wiki/Haste_Belt

**Comment by KnowOne134** [comment]
If so it would use and enchantment style code like I did for the pld item gained in pulling the strings enm. It also changes the enchantment icon into a refresh icon but you can then gain 2 refreshes. 1 from the spell 1 from the enchantment

**Comment by KnowOne134** [comment]
https://github.com/DarkstarProject/darkstar/blob/12b097cbc804559070ae7604c5a4fafe503f7531/scripts/globals/items/vial_of_refresh_musk.lua
