### ISSUE TITLE
Buying a new Instant Warp while Using an Instant Warp Crashes the cluster

### ISSUE THREAD

**Issue by sukasaroth** [EdenServer/community#2060]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

**Comment by godmode** [comment]
This type of crash has been happening nearly every day on one or more servers. Thanks to you I found a reliable way to reproduce it and I've made a change to prevent it. It will be deployed either on the next version update or as servers crash one-by-one. Thank you very much for reporting!
