### ISSUE TITLE
After guild rank up, npc will not take anymore gp items bug

### ISSUE THREAD

**Issue by rathorse** [EdenServer/community#2061]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
upon ranking up in a craft guild, you are unable to trade any gp items to the npc even if you have not turned in any thing for previous rank. This is wrong. You are suppose to beable to turn in items up to X amount to not exceed gp point limit for the new item.

Note: It is possible to obtain the maximum number of guild points for an item on a given day, then achieve a guild rank-up and receive more points on the same day, with a new item. However, the new item must have a maximum guild point cap that is more than the old item, and the guild points you have already received are logged so that you can only receive a maximum accumulated total for the day, that does not exceed the total of the new item.

https://ffxiclopedia.fandom.com/wiki/Guildworker%27s_Union

**Comment by waffleness** [comment]
While it doesn't dispute that you might be correct, the addition of that note to the wiki page was added in December 2008. So you will likely need to find another way to verify.

https://ffxiclopedia.fandom.com/wiki/Guildworker%27s_Union?direction=next&oldid=732954

**Comment by Far-The-Killer** [comment]
Yes, you'll need more than a single ffxiclopedia entry. Looking at the correct dates and through SE's patch notes are a good start.

**Comment by gweivyth** [comment]
https://www.ffxiah.com/forum/topic/5774/rank-up-and-guild-point-question
https://www.ffxiah.com/forum/topic/44397/guild-points-changes-or-se-screw-up/

Multiple counts of people describing it the way the OP says it does, but the dates are post-2007.  I don't see anything in the patch notes about changing guild point turn ins until 2012 when they added 110 into the mix. 

It's incredibly hard to find any information about this topic anywhere else though, and especially in the timeframe.  I spent a good 40+ minutes this morning looking for anything and I came up empty handed.

**Comment by rathorse** [comment]
The NPC did say that i could turn in the new item for points. I don't have a screen shot however. Otherwise the npc should had stated i could not earn points or i had reach my max limit or something rather. Which would imply thats how  it is in retail. And fairly sure it was the same in era. My previously stated experience was when i was lvling smithing and going for the gloves so that had to be the same time cop was released.

**Comment by agjevik999** [comment]
I have actually had this issue recently at the Bone Crafting guild. I checked the item before I did the rank up turn in. Decided it was not an idea item to craft, and turned in my rank up quest. The item requested by the GP NPC changed and I crafted a few pieces, but when I tried to trade the items, I got no response whatsoever. 

I though maybe it bugged out, so I tried to log out, which didn't work, and still no luck when I tried to zone and come back.

I don't really have any sources, but from what I remember from retail you can turn in items after ranking up, but only if the new item requested had a high total GP return, and even then you would only be able to get the difference of the maximum daily GP from of the new item, minus the old item.
