### ISSUE TITLE
Can't fish up Mythril Sword in Sauromugue Champaign (and other places)

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#2062]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I don't believe Mythril Swords exist in fishing pools in Sauromugue Champaign, even though they should.

http://www.great-blue.jp/?aid=045&bid=&lng=en

I've actually never fished one up anywhere, but they should be in the following places:

http://www.great-blue.jp/?fid=072&lng=en

**Comment by ShiyoKozuki** [comment]
You can fish them up, they are incredibly rare. 
Source: I saw someone fish one up today.

**Comment by Setz0r** [comment]
They are hard to get as they NPC for a large amount.  They exist in nearly 10 different fishing spots.
