### ISSUE TITLE
Ground Kings(HQ versions) not popping often enough

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#2063]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
I'll start by referring to this post where the OP logged data over 5 months: https://www.bluegartr.com/threads/42316-Fafnir-Nidhogg-Statistics.

From that data, the average HQ pop was every 6.04 days. On Eden, the average has been every 6.89 days. This is a pretty substantial difference, especially considering the drop rate on the second abjuration is still much lower than retail.

Another thing to note is that there has not been a single Day4 HQ pop in 150 total HQ kills. There have also been 0 Day5 HQ pops since May 27th. I'm not sure if there was a merge or something that broke this because they were fairly common before then. The average HQ pop since then has been 7.40.

**Comment by godmode** [comment]
What was the longest someone has seen it go to? How many days?

**Comment by Cheese-Sandwich** [comment]
We've seen a few day 10 pops. Rare but still more common then day 4.

**Comment by setsuk0** [comment]
In the month of June, we had 2 Nidhoggs go to day 10 within a 3 week period. Day 5 HQ pops did seem more common prior to June. We had a day 5 KB in April, and as Oyaziiiiiiiiiiii noted they had a day 5 HQ near the end of May but none that early since. 

Personally, I have not seen a day 4 HQ at all on this server, granted I have only been doing kings since March.

**Comment by mlandrum22** [comment]
Don't know if Overlord Bakgodek should follow the same pop schedule as ground kings, but his last pops (when I started camping) have been on days 6, 8, 11, 9, 5 and 6.

**Comment by godmode** [comment]
The HQ pop rate has been adjusted. It will go into effect on the next patch.

**Comment by Mozzy4Ever** [comment]
Think this is kinda still an issue. From what I can tell, it's not a weighted system currently. It should be an increasing % chance to spawn starting from Day 4. Seems like all that's done is a /random between 4 and 9, and HQ spawns on whatever day that random results in. With the RNG hitting min/max often on Eden, Day 4 or Day 9 HQs (and Window 1/2 or 6/7) are much more common than they should be.
