### ISSUE TITLE
Reraise Wore While fighting Mammets 2-5 Ancient Vows fight

### ISSUE THREAD

**Issue by Grayrail** [EdenServer/community#2064]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
During Mammet fight, Reraise was cast on Grayrails (character)  During the fight, Character Grayrails was defeated upon leaving the BC and Reraise wore.  Another character, Bah, also cast Reraise, however they had the prompt when they died.

Putting in this report to understand what happened with Reraise wearing.

Thank you!

**Comment by Mozzy4Ever** [comment]
To add to this: If you die in a fight and don't reraise and instead wait to be kicked out of the fight, you'll appear at the entrance but without the reraise prompt. Seems like player being moved while having reraise prompt makes the prompt go away. Would explain #1806 as well.

**Comment by KnowOne134** [comment]
This has been corrected some time ago and reraise persists now
