### ISSUE TITLE
Hydra Dark Knights in Dynamis - Beaucidine using Out of Era spells

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2065]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

While doing Dynamis - Beaucidine attestation run we found out that the Dark Knight Hydras (Fomor) use Absorb - ACC which wasn't a spell until Wings of the Goddess came out.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
