### ISSUE TITLE
Stuck in black loading screen

### ISSUE THREAD

**Issue by Chiandra** [EdenServer/community#2066]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I recently retrieved the mini-fork for the Ramuh battle from Mhaura. After zoning from Mhaura into Buburimu Peninsula, my character, Chiandra, has been stuck in the black loading screen and will not load into the next zone.

**Comment by Chiandra** [comment]
Issue solved. Reloaded game multiple times on different ISPs. System finally reloaded I to Mhaura.

**Comment by Twentytwox** [comment]
Glad to hear your issue is resolved! In the future, visit this address to call a GM who may be able to help you sooner! 

https://www.edenxi.com/forums/viewtopic.php?t=829

**Comment by KnowOne134** [comment]
Most likely was a crashed zone or ISP issue
