### ISSUE TITLE
Korrigan in boyhada tree loot table is wrong

### ISSUE THREAD

**Issue by alioh7** [EdenServer/community#2072]
![IMG_20190927_131933](https://user-images.githubusercontent.com/55878362/65762756-60c65f00-e12a-11e9-9f06-a12ec28cd39a.jpg)
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

i was try to farm a four leaf korrigan bud to craft a garden bangles but it wont drop , until i saw that they dropped me a fiend blood which is wrong because online sites say they dont. so i attached a picture of the drops and made a bug report.

**Comment by alioh7** [comment]
please fix it.

**Comment by greyenvy** [comment]
Months back I reported a similar issue with the boyahda saplings dropping weird items and nothing from their actual loot pool.  Godmode fixed it pretty quick.

Hardly anyone exp's in the tree these days.  A full audit of mob loot tables might be in order.  I cak contribute that robber crab, knight crawlers, funguar, and bark spiders are okay!
