### ISSUE TITLE
Subcrafts for Adaman Sainti may be incorrect

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2079]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently on Eden the subcrafts for Adaman Sainti are listed as 54 goldsmithing and 43 woodworking. The jp wiki lists the subcrafts for Adaman Sainti as 45 goldsmithing and 42 woodworking. http://wiki.ffo.jp/html/8148.html

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
