### ISSUE TITLE
Pitchfork +1 issues

### ISSUE THREAD

**Issue by chlorr** [EdenServer/community#208]
So Loki and i have been trying to get our +1s for 2 hours roughly. we've tried the gobby turn in twice in each city and none of them are working.

Also, we were unable to receiveour NQ in windy, with a few different years of costume combos (05 ((the one Eden is using)) and 08). We had to use bastok for our NQ.

**Comment by Wiggo32** [comment]
sorry, it's fixed now.
![pitchfork 1](https://user-images.githubusercontent.com/30469395/47297349-72c68600-d5da-11e8-9909-28ff3667a995.jpg)
