### ISSUE TITLE
Geush Urvan difficulty etc.

### ISSUE THREAD

**Issue by PoppaPip** [EdenServer/community#2081]
Hi! Geush Urvan is supposed to ignore shadows with his auto attacks - he doesn't here. He's also supposed to do absurd amounts of damage with his auto attacks - he doesn't here either.

Also a possibility, I believe the ??? to pop him is a little out of place. It should (according to 90% of sources) be at L-8 where the underground pops back out, instead it's out in the open a bit aways.

https://ffxiclopedia.fandom.com/wiki/Geush_Urvan?oldid=223834

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

**Comment by Volkaru** [comment]
From that same link: "Does over 1000 damage per melee hit; must be blink tanked."
Videos I've seen show him being NIN tanked or BST burned. So I don't think his autos are supposed to ignore shadows.

**Comment by PoppaPip** [comment]
https://www.youtube.com/watch?v=6qrL7Ngp2_k at 0:49 you can see it auto attack him, wipe his shadows and do 1k+ damage. So it's possible that it's a variable thing, but it definitely happens on occasion. When we fought him he would do 200~ in auto attacks, and not once did they wipe/ignore our shadows.

**Comment by perkuprightmeow** [comment]
Yeah, his auto attacks were hitting me on RDM for about 60-100 dmg with a PDT set. Shadows would block his autos 100% of the time. He also seemed to auto attack much slower than in the video. 

Finally, he should be casting only ice spells, rn he's casting stuff like Tornado and Blaze Spikes.

**Comment by 59blargedy** [comment]
resolved with May 10, 2021 update
