### ISSUE TITLE
Sky (Seiryu, Suzaku, Genbu, Faust, Despot etc.) severely undertuned. Ulli's regen is too high.

### ISSUE THREAD

**Issue by PoppaPip** [EdenServer/community#2083]
Hi! I'm afraid all I really have here is anecdotal, but figured I'd throw it out there and see if anyone else has better evidence.

All gods seem to have significantly lower resistance here than in retail. You can land bind with 95% accuracy on Seiryu without merits or amazing gear. They also appear to have far lower regain here than retail.

Seiryu specifically I have never seen cast Silencega or Blink, which he should have.

Faust's movespeed seems much lower here than retail.

Ullikummi's regen here is higher than Poison2/Bio2 stacked, and I used to solo him easily in retail with just those two spells.

Thanks! Like I said, other than youtube videos, my personal recollections, and https://belkinator.livejournal.com/2591.html which was my bible back in the day I'm afraid I don't have the stats etc. for any of this. So, grain of salt.

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

**Comment by greyenvy** [comment]
I concur that Ulli's regen is a tad higher than I recollect.  It was definitely a solo job by rdm/nin in era.  I cannot see how that's possible here.  

Not sure on Faust.  Almost always pull him with carby or flee and never watch his move speed.

Not sure on the other stuff personally.  Before this past month it had been at least 13 years since I killed any of the sky gods.

**Comment by Oyaziiiiiii** [comment]
Some seiryu videos: 
https://www.youtube.com/watch?v=oUKMJ1nvyAw&t=159s
https://www.youtube.com/watch?v=1AwlBgAbWfw

I didn't watch the entire videos but I didn't see any silencega casts. It should cast Blink and Gravity though.  Gravity cast at 2:12, Blink cast at 3:05. I don't believe it casts either of these here but correct me if I'm wrong.

**Comment by Slamm21** [comment]
I used to solo Ulli all the time on rdm and before I bothered with Bio 3, Bio2 + poison 2 definitely beat his regen.

**Comment by Slamm21** [comment]
I couldn't remember Seiryu ever casting silencega when I used to solo, but wanted to check and make sure.
https://belkinator.livejournal.com/3049.html
He does radiant breath, definitely mentions there about blink though.

**Comment by PoppaPip** [comment]
Hmmm it's possible Silencega could just be me misremembering Radiant Breath.

**Comment by Balrahn** [comment]
The problem with adding a bug like this with so many NMs is that it will never get done. Nobody wants to start working on something this big. I suggest closing this and adding seperate bugs for each NM. Starting with Ulli! Lol.

**Comment by 59blargedy** [comment]
resolved december 7 update, though please post a followup report if issues remain.
