### ISSUE TITLE
Snakeeye + Ice Lance Additional Effect ( & Latent) Not Working

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2084]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Snakeeye is supposed to give you +5 STR when poisoned, currently it does not. 
It's supposed to add 20HP/Tick dmg to any poison you have. 
It's supposed to poison on hit 100% of the time unless a mob has resist (debatable, but supposed to be high accuracy).
https://ffxiclopedia.fandom.com/wiki/Talk:Snakeeye
https://www.ffxiah.com/item/18708/snakeeye

Have been using Ice Lance +1 in 75 Merit Parties 2 weeks now, have never seen it proc with additional ice damage.
https://ffxiclopedia.fandom.com/wiki/Ice_Lance

**Comment by gweivyth** [comment]
Ice Lance hasn't been added in yet, additional effects are slowly being added.  #1487 

I didn't touch Snakeeye though, that one might be further out.

**Comment by 59blargedy** [comment]
fully resolved in October 4, 2021 update
