### ISSUE TITLE
Shikigami weapon should save ToD

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2085]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

On retail, Shikigami Weapon's ToD was reset on maintenance. On here, I think it'd be best to have it's ToD saved due to crashes. The cluster it's on goes down quite often so the robe is much more common than it should be

**Comment by KnowOne134** [comment]
I agree

**Comment by Volkaru** [comment]
This was changed to persist as well as one other NM in the December 30th patch

**Comment by KnowOne134** [comment]
I'm not showing any code to support that

**Comment by KnowOne134** [comment]
fixed with #1201
