### ISSUE TITLE
GSM Guild Does Not Carry Brass Sheet

### ISSUE THREAD

**Issue by CdoubleOkay** [EdenServer/community#2086]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver: 30181205

As of August 19th, 2007 The GSM Guild should carry Brass Sheets on both NPCs. Not sure the exact date of our "era" but I asked and Discord and was told Pre Nov, 22, 2007.

Wiki Link for reference:
https://ffxiclopedia.fandom.com/wiki/Brass_Sheet?oldid=330155

**Comment by bkesecker** [comment]
Brass Sheet is stocked by the Goldsmith's Guild.  Most likely the stock was depleted.  However, the daily increase is 0.  Need to determine if this item is auto-stocked by the guild or only if players sell Brass Sheets back to the guild.

**Comment by 59blargedy** [comment]
this appears to be an item only obtainable through the guild if sold by players
