### ISSUE TITLE
Hagun Possibly not applying TP Bonus

### ISSUE THREAD

**Issue by xzeikx** [EdenServer/community#2087]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ok so i was meriting on Greater Colibri as SAM/WAR. And noticing Soboro and Hagun do not have the big gap in ws numbers it should have. For reference Soboro is a 40 base damage GK and Hagun is 72 (With TP bonus Mod)

WS Gear is as following
Soboro 
Pole Grip
Hume Sachet (STR+1) 
Wyvern Helm +1
Kirins Osode
Alky Bracelets
Foragers Mantle
Warwolf Belt
Triumph Earring
Spike Necklace
Bushinomimi
Flame Ring x2
Shura Haidate +1
Rutter Sabatrons

I am STR 72+73 in WS gear and hasso up. Im dealing 300-600 Gekkos with Soboro and 500-1000 with Hagun. (I did do a 1188 which was nice but likely a crit + DA proc) Because i only ever broke 1k 3x in 2 hours. This was with Varying instances of zerk and warcry being up. We had a BRD but it was solely double march so no other outside buffs. I also did not use food for the purpose of this test.

**Comment by everlast101069** [comment]
You can't crit a non critical weapon skill without a force crit from either all hits with mighty strikes or first hit from sneak attack.

**Comment by Slamm21** [comment]
Gekkos damage is also significantly higher if you cap PDIF which means sometimes hauby > osode if no minuet etc which you didn't have.

**Comment by piercingdark** [comment]
Using Hagun and 76+70 STR, 281 GK skill and 2/5 overwhelm merits on greater colibri with chaos roll and berserk/warcry up intermittently, I parsed weapon skill average of 684 using Gekko.

Using the link to era below from BG, you can see that at similar STR weapon skills (albeit better gear and varying camps), they were getting 1200-1300 average Gekko using Hagun. Literally twice as much damage. https://www.bluegartr.com/threads/47551-Parses-after-the-patch

**Comment by Falaras** [comment]
I wonder how YGK are set up to function on DSP? These weaponskills, along with some other weird ones like Ground Strike, had strange properties but I'm not sure anyone ever explicitly figured out. https://www.bluegartr.com/threads/68018-Yuki-Gekko-Kasha-Attack-bonus-Testing/page3 This thread was where a lot of YGKs in era testing got done, originally it was theorized to just have a massive attack bonus but people later decided it was a much lower Ratio than normal I guess? I don't know that kind of math very well, but from what I can understand reading that the ratio was basically half of what normal would be so you basically hard capped attack without buffs on many mobs depending on level.

Then again every WS sucks on DSP so it's hard to say that is the problem when Raging Rush also sucks and doesn't function in that way at all.

**Comment by Falaras** [comment]
Also it is worth noticing Piercingdark that the thread you linked is from 08/2007 which was directly after the original 2 handed update which was 1STR=1 Attack and 1DEX=1 Acc. Eden operates off the revised 2 handed update from 11/2007 where 1STR=.75 Attack and 1DEX=.75 Accuracy. Does that matter specifically for YGK? I don't know/maybe not? Worth mentioning though that that thread should not be accurate to Eden.

**Comment by Raphtalia1** [comment]
for YGK the 2handed update doesn’t really effect it much, att has a low impact on overall performance, same with accuracy, so the dmg from weapon skills should be fairly accurate,

Overall DoT is much lower before and after 1:1 but that’s because of melee dmg per hit rather than WS damage

**Comment by piercingdark** [comment]
I wouldn’t think it would matter for Gekko since it’s the raw STR that matters with PDif capped.

**Comment by Falaras** [comment]
It won't matter as long as it is capped, just depends on the situation. Capping attack on Gekko is not super hard but it is possible to be uncapped for sure.

**Comment by Slamm21** [comment]
https://www.bluegartr.com/threads/68018-Yuki-Gekko-Kasha-Attack-bonus-Testing?p=2506651&viewfull=1#post2506651
I sent this to a few friends recently just showing that going all out STR on Gekko is a merit thing since you have capped pdif there and not a hnm thing.
Y = 33% attack bonus
G = 100% attack bonus
K = 50% attack bonus

I believe spinning slash was 50% and ground strike 75% also? not sure on those two

**Comment by beauxq** [comment]
The way to figure out if the TP bonus is working is not to compare Eden numbers to numbers from other sources, because that could mix in other bugs to make it more complex.

The way to figure it out is to compare Eden numbers that should have TP Bonus with Eden numbers that shouldn't have TP Bonus.

Tachi of Trials is close to the same DMG as Hagun with no TP Bonus. So compare Tachi of Trials WS damage with Hagun WS damage. (Or find another GK with close to the same DMG.)

**Comment by panfunk** [comment]
Small test:
Lesser Colibri 63-65, all WS done with 1000-1300 TP, Hasso, in front:

Kazaridachi: (76dmg)
![TP-Bonus Test 1](https://user-images.githubusercontent.com/36666121/66309579-49e1f280-e90a-11e9-859c-3f5a0fdd7c30.PNG)

Hagun: (75dmg)
![TP-Bonus Test 2](https://user-images.githubusercontent.com/36666121/66309598-59613b80-e90a-11e9-8578-a4242c975bfa.PNG)

**Comment by ShiyoKozuki** [comment]
Hagun is 100% applying the TP bonus. I tested it multiple times.

**Comment by Mozzy4Ever** [comment]
![image](https://user-images.githubusercontent.com/11255886/82765895-48553400-9de0-11ea-81c1-4dcd1337d88f.png)

Definitely is giving proper TP bonus. Issue is elsewhere

**Comment by 59blargedy** [comment]
assumed issue resolved with pdif update, as was not about the hagun tp bonus
