### ISSUE TITLE
Light Shot doesn't claim a monster if it misses

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2088]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Was in Mount Zhayolm, pulling on COR and wanted to sleep a monster so it would come timely for us to kill after the monster we were killing. But being Elvaan I of course missed my Light Shot, and that's when I noticed that it stayed unclaimed. This isn't what should happen.

**Comment by KnowOne134** [comment]
still an issue?

**Comment by 59blargedy** [comment]
resolved january 25, 2021 patch
