### ISSUE TITLE
Gourmet bugged after !unstuck in B. Markets

### ISSUE THREAD

**Issue by Althaia** [EdenServer/community#2089]
### Checklist

* [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
* [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
* [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is: Version 30181205_0

So I just got stuck for the first time today, it was on my alternate character in Bastok. I zoned in from Mog House to Bastok Markets and calmly did !unstuck like I'd heard everyone say I should do.

Waited the 20 mins, zoned back into my Mog House, zoned back out, did some AH stuff, then made my usual trip to Salimah to do the quest "Gourmet."

As usual, I checked with the little girl to see what she wanted right now; it was sleepshrooms, so I traded one to Salimah and waited.

Nothing happened. Traded again, nothing happened -- and it looked like I still had the sleepshroom in my inventory. For reference, there's supposed to be a long grateful dialogue that pops up upon trading, along with the gil reward.

Finally, I pressed enter on Salimah and got "Thanks to you, I'll make the best dish yet!" which I believe is usually at the end of her long reward dialogue. However, there was no quest reward.

Then, I logged out and logged back in, to see if that would fix the issue. I fully close the window and logged back in through Ashita.

I pressed enter on Salimah and got the same incorrect dialogue. So then I ran down to Bastok Mines and back to Salimah, hoping that zoning out of the Markets zone completely (instead of just a mog-house-zoning) would fix the issue.

Thankfully, it did! I zoned out to Metalworks and back to Salimah one more time, just to make sure the fix wasn't a fluke the first time around, and it worked.

So now I can repeat the quest as per usual, which requires a zone out between attempts normally, too. I don't know if it's because Mines is on the Dynamis cluster or just because Mines is a different zone (so maybe this fix would've worked zoning into Metalworks or Port, too).

Now am I SURE that it was !unstuck that screwed up the quest? No, of course not, but that's literally the only thing I did different today, so it's all I can think.

**Comment by 59blargedy** [comment]
there's a zone check on this quest that may have been triggered by using unstuck, however !unstuck code has been updated since this report and i cannot replicate the issue, so assuming it's been resolved.
