### ISSUE TITLE
Alkyoneus respawning quickly?

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#209]
Alkyoneus seems to be respawning extremely quickly, he's already up again less than 4 hours after his last death.

I'm not sure if this is intentional or not as he was originally a 21-24 hour NM and then became force popped in 2007ish without a change to his drop rates.

Regardless, I left him alive after encountering him for the second time, but some reassurance as to whether this fast respawn is fair game to kill or not would be appreciated. Thanks!

**Comment by godmode** [comment]
No, he shouldn’t be respawning that quickly. I imagine I goofed somewhere. Thanks for reporting but please leave him up until 21 hours later.

**Comment by Aneyus** [comment]
Seems to still be respawning and despawning (and/or being killed by others) as he pleases... Killed him at 8:02am EST yesterday and he was already up again by ~10pm EST the same evening. Unfortunately I don't really have any further details as I've been trying to only kill him once per day, but it's quite frustrating to leave him alone intentionally and then see him gone when he is actually supposed to be there later =/

**Comment by Aneyus** [comment]
And immediately after I post that he spawns. Crazy guy, that Alkyoneus!

**Comment by tectal831** [comment]
This appears to have gone the opposite way now, with reports that He is depopping and not being seen for days. Please investigate

**Comment by godmode** [comment]
I'm closing this issue, please report if it needs opened back up.
