### ISSUE TITLE
Sirius Axe drop may be too low.

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#2092]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

We're (Kraken Club) 0 for 6 on a Sirius Axe dropping off Hydra (all with TH3), and I asked a member of SD and they said they're 2 for 15.

http://www.ffxidb.com/zones/51/hydra

The drop rate should be close to 48%.

**Comment by Kurtalicious** [comment]
Now that this is fixed we just need to make the weapon work right.
