### ISSUE TITLE
Wivre's "Granite Skin" causes client crash

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2093]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver = 30190328_2

Was doing merit party in Bhaflau Thickets. Pulled a Wivre to keep chain. It used Demoralizing Roar and Boiling Blood without issue but once it used Granite Skin it crashed our entire party. This wasn't from it dying while trying to use the ability, either. It was still at half HP

**Comment by beauxq** [comment]
I have also seen lots of client crashes on Wivres with 30181205_0

**Comment by Mozzy4Ever** [comment]
Did another merit party today after reverting to 30181205_0 and fought a lot of wivres. They used granite skin several times with no issue, but at one point a wivre used it and only I crashed out of the party. Wasn't able to confirm the rest of the party's /ver sadly

**Comment by KnowOne134** [comment]
Someone with pup pld frame in party or anyone cast stun?

**Comment by Mozzy4Ever** [comment]
Not that I see in my chat logs. We had a DRK that occasionally cast stun but he hadn't cast it before that

**Comment by Mozzy4Ever** [comment]
Closing because I haven't personally seen nor heard of this since it happened to me.
