### ISSUE TITLE
Aftermath Effect Duration

### ISSUE THREAD

**Issue by AresHypnos** [EdenServer/community#2094]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
version: 30181208_0

While using Bec de faucon at 1000% TP Aftermath duration is randomly between 16-23 seconds.  Effect usually disappears within 1-3 seconds of total use.  If WS is used on killing blow, no aftermath effect is applied.
![aftermath](https://user-images.githubusercontent.com/37120745/66173768-cf159080-e606-11e9-8271-e5660f3c2a3a.PNG)
![aftermath #2](https://user-images.githubusercontent.com/37120745/66173771-d2a91780-e606-11e9-83f3-5ff0492a981c.PNG)

In the photos above, the chat log is delayed a bit, but you can see the effect wearing off as soon as the weapon skill is being used

**Comment by gweivyth** [comment]
Looks like it might just be wrong in base DSP, because Mythics have static aftermath effects attached to them, but uncompleted relics and relic weapons just have this:

`local getTier1RelicDuration = function(tp)
    return math.floor(tp * 0.02)
end

local getTier2RelicDuration = function(tp)
    return math.floor(tp * 0.06)
end`

**Comment by gweivyth** [comment]
Stumped on it not applying Aftermath of the WS deals a killing blow though, that's probably deeper than I am qualified to go.

**Comment by gweivyth** [comment]
So looking at Aftermath in [base DSP](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/aftermath.lua) doesn't really tell a story as to why it would be as wonky as it is.  If it's referencing getTier1RelicDuration then you should be getting 20 second durations at 1000 TP.

```
local getTier1RelicDuration = function(tp)
    return math.floor(tp * 0.02)
end

local getTier2RelicDuration = function(tp)
    return math.floor(tp * 0.06)
end
```

```
    [7]  = { mods = { dsp.mod.HASTE_GEAR, 1000 }, duration = getTier1RelicDuration }, -- Apocalypse
```

Mythics have defined durations in their actual lua, and I don't understand why these two aftermath effects were written differently:

``` 
   [38] = -- Gastraphetes, Death Penalty
    {
        mods = { { dsp.mod.RACC, function(tp) return math.floor(tp / 50) end },
                 { dsp.mod.RATT, function(tp) return math.floor(3 * tp / 50 - 90) end },
                 { dsp.mod.REM_OCC_DO_DOUBLE_DMG_RANGED, function(tp) return 60 end } },
        duration = { 90, 120, 180 }
    },
```

**Comment by AresHypnos** [comment]
Upon further testing today in dynamis, the aftermath effect adds no haste when under effect

**Comment by gweivyth** [comment]
Probably haven't updated to current DSP since [this fix](https://github.com/DarkstarProject/darkstar/commit/f7a90063fa2ca36e341d3e6c416dd4d1d596a941#diff-9e8082cb777b402cdaa3d98f40d763aa) was put in.

**Comment by Relic3** [comment]
First Dynamis with Bec de Faucon. Aftermath does not actually apply the 10% haste.

**Comment by icariumkupo** [comment]
Just wanted to add the actual duration and values of the Aftermath effect for Catastrophe:

https://www.bg-wiki.com/bg/Apocalypse_(Level_75)

1000 TP = 20 seconds
2000 TP = 40 seconds
3000 TP = 60 seconds 

This should scale linearly with TP (TP*.02). Which DSP does seem to implement correctly in the snippet above.

The haste amount should be 10% Equipment Haste (+102/1024). Currently the aftermath effect does not grant any amount of haste, for either Bec de Faucon (in Dynamis) or Apocalypse. 

Additonal notes: 
-Bypasses Utsusemi, but not Third Eye.

Drain effect:
See ticket #2168
