### ISSUE TITLE
Warcry does not boost Ranged Attack like it should. 

### ISSUE THREAD

**Issue by FriskArt** [EdenServer/community#2095]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details
As far as I remember in retail, Warcry always boosted ranged attacks just like berserk does. 
If check param is working correctly, Warcry does not boost ranged attacks whatsoever.

https://www.bg-wiki.com/bg/Warcry

**Comment by gweivyth** [comment]
No mention of Warcry increasing ranged attack anywhere that I can find, [but I did find mention of berserk raising ranged attack](https://www.bg-wiki.com/bg/Berserk).  Not sure if that's working correctly on Eden, but it's likely that you're probably just confusing the two.

**Comment by Slamm21** [comment]
Warcry does, it was mentioned on that link posted to BG Wiki "Attack and Ranged Attack bonus given by Warcry varies by level of the Warrior or Warrior Subjob using Warcry."

Also here https://ffxiclopedia.fandom.com/wiki/How-To_Guide:_Ranger

Warrior
"A good support job early-game, and a very risky (but amazing) support job in the later-game. It certainly provides ample base damage through Berserk and Warcry, as well as a high base strength and dexterity. "

**Comment by KnowOne134** [comment]
Would need retail capture to prove it before I would add it
