### ISSUE TITLE
BCNM30 - Petrifying Pair Bugged

### ISSUE THREAD

**Issue by sukasaroth** [EdenServer/community#2097]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Upon using an orb on the hut for BCNM30 Petrifying Pair: The lizards roam the BCNM instead of staying in their stationary spot. Causing them to be able to aggro players upon entry of the battlefield. If a player aggros a lizard before all members of the party can enter, the other party members can not get battlefield status, will get warped inside the hut but not be able to act on the lizards, thus getting stuck inside the BCNM.

**Comment by KnowOne134** [comment]
Sounds like the mobs need the flag for battlefield mobs so they dont roam

**Comment by sukasaroth** [comment]
How simple of a fix is that? I don't want my friend Averel to lose another orb.

**Comment by roriffxi** [comment]
https://github.com/EdenServer/community/issues/1100

Looks like this was reported and put into code review a while ago, but apparently not fixed (or recently re-broken)

**Comment by 59blargedy** [comment]
appears resolved months ago, please comment if still an issue,
