### ISSUE TITLE
Have Supplies (i don't remember picking them up) Zulkheim

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#210]
On Sunday afternoon EST, i went to get signet from Zulkheim WW at the OP and it dinged and gave me text as if i brought supplies.  I clicked again and the same noise/text.  I checked and i have the Zulkheim supplies now (it is possible i picked them up earlier in the week but don't recall doing it).

I am now stuck with these supplies and I want to get 3 new OPs i have earned this week!  Please delete supplies so I can do my new supply quests.

**Comment by beauxq** [comment]
Duplicate of:

https://github.com/EdenServer/community/issues/158

**Comment by MGramolini** [comment]
supplies have dropped now when talking to npc

**Comment by MGramolini** [comment]
> Duplicate of:
> 
> #158
