### ISSUE TITLE
Initial Portal in Ru'Aun Teleports to Wrong Locations

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/community#2101]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The initial red portal in Ru'Aun Gardens tends to teleport to two points to the right (on the map shown in the link below) rather than straight across.  Out of 10+ tries, not a single try ended up straight across.

https://www.ffxi-atlas.com/maps_normal2/0076_ruaun-gardens_2.jpg

**Steps**

1. zone into Ru'Aun Gardens
2. take the first, and only, telepoint
3. !pos will be one of 358.975 -40.1059 -255.473 or 107.414 -40.1059 -432.526
4. !pos should be 0.0153 -34.1059 -471.9400 rotation 192

_30181205_0_

**Comment by KnowOne134** [comment]
closing, can not reproduce, must have been fixed by something
