### ISSUE TITLE
Kirin Enmity Issues

### ISSUE THREAD

**Issue by Raphtalia1** [EdenServer/community#2102]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0

When kiting kirin, if you run further than 25' he will go attack someone else randomly on the hate table. (including people who have recently raised and have taken no action other than resting)

Before the bind mob targeting update this didn't happen, so i am inclined to believe that this is an unintended consequence

**Comment by Tjonke** [comment]
That was always the case when kiting. You start losing hate as soon as you get out of 20' and it just drops the further you get from the monster.

**Comment by Slamm21** [comment]
No way that is correct. You can gain hate as long as the action is performed on something within 25' of the mob. So if you were 45' away and cast cure iv on a mob 25' away you will get hate.
Hate can seem like it is magically lost when kiting if you either had a lot of VE hate (which decreases over time) or you get hit which would reduce your CE hate.

**Comment by Slamm21** [comment]
You can get 10k CE  hate and 10k VE hate.
VE is lost at 60/second, which is why all your VE hate from provoke (1800VE) is lost exactly when that timer is up.

On retail before we tp burned I would just run around with capped 10K CE hate getting way out of the 25' range and not get hit so I never lost hate.

**Comment by Raphtalia1** [comment]
just to be clear, we noticed that hate was lost instantly the moment a tank hit 25.1 distance

once we stopped getting more than 25 away hate was solid like it was expected to be
