### ISSUE TITLE
Buffs time scales improperly with level sync

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#2103]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

In Phomiuna Aquaducts, 40 sync zone, when I cast haste from my 55whm onto my 41nin, the buff duration is 2:30. Haste should be a flat 3:00 duration from level 40 onwards.

**Comment by 59blargedy** [comment]
resolved may 31, 2021 (was only an issue with haste)
