### ISSUE TITLE
Master Caster's Bracelets not available for non Windurstians even when Windurst in 2nd place

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2104]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

The rank 8 conquest item "Master Caster's Bracelets" that should be availble to buy by any nation ranked higher than Windurst while Windurst is still in second place are unavailable to purchase. This is a staple item for Red Mages who want +7 elemental and enfeebling skill on a pair of hands. Only item you are offered are the Master Caster's Mitts.

Game version: 30181205_0

**Comment by setsuk0** [comment]
I checked a couple of websites, and not being able to obtain the item if you are from another nation seems to be accurate to retail despite what the wikipedia page says. You can see this in other forum discussions located here: 
http://www.eosun.org/forum/showthread.php?t=42781&page=1
https://www.ffxiah.com/forum/topic/1455/conquest-item-question
https://www.bg-wiki.com/bg/Conquest_Points

Per BG wiki, "If an item has a nation rank requirement, only citizens of that nation can purchase them." This means that the FFXIclopedia page stating you can purchase these is actually incorrect. You need to change your allegiance to Windurst to purchase these.
