### ISSUE TITLE
Moonlight giving skill ups for each party member hit

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#2105]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Moonlight seems to be giving skill ups for each member of a party hit. Making club skill rise incredibly fast. 
![Volkaru_2019 10 06_192747](https://user-images.githubusercontent.com/9113384/66325747-a6c6b400-e8dc-11e9-9e5f-f3f1a2ea21d8.png)

**Comment by KnowOne134** [comment]
has been found that self targeted weapon skills will not award skillups at all

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
