### ISSUE TITLE
Shadows of the Mind ISNM Consuming More Than One Key Item

### ISSUE THREAD

**Issue by inaringo** [EdenServer/community#2107]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Entered Shadows of the Mind ISNM with one other player. After failing the fight we found that both of us had lost our key items, when it's supposed to consume only one at a time. Tried to see if we could enter again and didn't work.

**Comment by jmcmorris** [comment]
This has been resolved! Thanks for reporting.
