### ISSUE TITLE
No exp from kills when a charmed pet is lvl 76+.

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#2108]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

I charmed a level 76 Million Eyes. Used Familiar and started killing other eyes. I get no exp.
My bst is 73.

**Comment by KnowOne134** [comment]
unable to reproduce set job to 73 bst charmed T familiared fought em and t's and gained xp.

ok to close?

**Comment by Wade9363** [comment]
This happens to me all the time, but totally randomly as BST.  I have no idea what triggers it.  It seems to happen more often with T or higher pets, but it happens occasionally with Jug pets also.  

For Example: In Bibiki Bay I charmed & Familiared a Catoblepas pet (LVL 80) to kill Hobgoblin Blaggers (LVL 78+) and it seemed I got 0 exp more often than not.  

However, last week I was farming for Anima's in Promyvion-Dem and with a Jug pet and got no experience several times for seemingly no reason.  

I can't reliably reproduce it.

**Comment by KnowOne134** [comment]
Problem stems from xp penalty of pet to your level vs mob killed level?

**Comment by Wade9363** [comment]
That is possible, but it has happened several times where that shouldn't have been the issue.  For Example:

A friend and I duo'd Hakutaku and we got no experience as 75RDM & 75BST.  The Max level of Million Eyes pets are 76 vs Hakutaku (85).  It should not be possible to kill Hakutaku and get no experience, but it happened.

**Comment by Wade9363** [comment]
Just remembered something:

When I received no Experience using a Jug Pet in Promyvion-Dem, I was dual boxing at the time and my other character died mid-fight.  I Home pointed, but I do not remember if I home pointed before or after I killed the 2 mobs I had engaged.  

Perhaps in that instance, after dying, xp was being calculated using my full job level instead of the restricted lvl 30.

**Comment by KnowOne134** [comment]
Found issue: xp tables dont exist on eden after 75. So you pet takes you out of xp range. Atm
