### ISSUE TITLE
Keyboard and Controller

### ISSUE THREAD

**Issue by PsychedelicNPC** [EdenServer/community#2109]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I am using the newest update of FFXI Eden. I have recently been on a 2 month hiatus coming back I had to install the newest version of Eden.
After logging in I had my controller plugged in. This had function just fine.
However, my keyboard no longer had function. It was running but in-game nothing was working.
Then, I unplugged my controller and the keyboard was working.

This was not an issue in the old Eden.
Is there anyway I can fix this.
I really like the keyboard Controller combo because I like to fish and would like to be able to fish and chat ingame.

**Comment by Mozzy4Ever** [comment]
This isn't really a eden-specific bug, as shown here - http://forum.square-enix.com/ffxi/archive/index.php/t-50138.html?s=ae6f79173c6be8cdcc0438c8cc45446b
