### ISSUE TITLE
GP caps are higher than era values for Cooking.

### ISSUE THREAD

**Issue by Nuntias** [EdenServer/community#2111]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The cap for GP items isn't era appropriate. The cap is higher than was available at the time for when Eden is set. The GP per item is correct, the cap is different. If you look at the GP cap for items when turning in for GP, the amount is what you'll find in late 2009-2011 on the wiki. 

On the day of submitting this bug or discrepancy, the GP item "Witch Soup"/"Mushroom Soup" offers 5200 total GP. This amount wasn't edited on the wiki until Revision as of 23:35, October 7, 2011.  I believe it should correctly be 4560. 

Client version 30181205_0

**Comment by Volkaru** [comment]
Link from late 2007 to back this up: https://ffxiclopedia.fandom.com/wiki/Witch_Soup?oldid=361534

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
