### ISSUE TITLE
Missing PH Balloon Spawn for Doppelganger Gog/Dio

### ISSUE THREAD

**Issue by tengokujin** [EdenServer/community#2113]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version: 30181205_0

While camping the NMs for Cruel Spear/Scythe, I've discovered two issues.
The spawn points for Doppelganger Gog/Dio are supposed to be in three spots, but there is no PH spawn of a Balloon in G-7 of the appropriate zone.
This should be easily demonstrated by going to the appropriate spawn locations.

**Comment by Eme-FFXI** [comment]
confirmed, only 2 PHs are up at their designated rooms east side, no PH in the room to the west. NMs can spawn in the western room tho as they should.

**Comment by 59blargedy** [comment]
resolved in oct 4 2021 update
