### ISSUE TITLE
Tractor puts you out of bounds in Bearclaw Pinnacle 

### ISSUE THREAD

**Issue by HunnyDoo** [EdenServer/community#2114]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
v30181205_0

Using tractor during Brothers ENM fight puts you somewhere off the map.

**Comment by InoUno** [comment]
Resolved in January 11th 2021 patch.
