### ISSUE TITLE
Bastok 7-2 fight, NMs doesn't use their 2hours.

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#2115]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I just did this battle and none of the NMs used their 2hour abilities.
They should all have them available.

**Comment by KnowOne134** [comment]
tested and has already been fixed
