### ISSUE TITLE
Know One's Onion is Repeatable

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2116]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Reported by Madddogg -

Know One's Onions isn't supposed to be a repeatable quest, but no CS is given after trading 4 Onions and you receive a scroll of Blaze Spikes. Can trade infinitely for infinite scrolls. 

May have something to do with having a Carbuncle Ruby in inventory -- unsure.

**Comment by KnowOne134** [comment]
Well I'm KnowOne. I should fix my quest right
