### ISSUE TITLE
Curaga Earring "Unable to use item" 

### ISSUE THREAD

**Issue by ceramsey** [EdenServer/community#2117]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0

Currently I am a 61 PLD with the Curaga Earring equipped. There is no countdown on the timer, 50/50 charges, it is equipped from inventory and not mog wardrobe. Select item using F1 --> Items --> Curaga Earring --> enter (targeting me) --> enter. Chat log states Unable to use item and then the casting bar starts casting. Casting fails. Is this an out of era item? Is it bugged? I just spent 40k (which was a lot for a newbie) on it via auction house and haven't been able to use it yet. Thanks.

**Comment by Setz0r** [comment]
this item is not coded yet.
