### ISSUE TITLE
SCH dropping in dynamis-xarc instead of BLU

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#2118]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Like the title says, Scholar AF2 Hat dropped in dynamis-xarcabard. Blu doesn't appear to drop (pup and cor have both dropped for multiple linkshells with no blu), so we suspect sch is dropping in it's place.

**Comment by godmode** [comment]
That’s exactly what is happening. For shells that get SCH drop please lot on it if you want it replaced with BLU. For those linkshells that had SCH drop before this please make a GM ticket noting who got SCH drop and who should get BLU drop.

The drop rate may for AF in general be too high with TH4 though so I am investigating.
