### ISSUE TITLE
Dragoon Job Quest/ Dragon Fight

### ISSUE THREAD

**Issue by starryarrow** [EdenServer/community#2123]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)

### Details

I completed the Dragoon Job Quest Dragon Fight, named my wyrven and yet I do not have the dragoon job option.  I went back to talk with Rahal in Sandoria and he talks as if I never did the fight.

**Comment by Solidmacks** [comment]
I have this issue as well on my character Ehgo quest is still active in my log as well.

**Comment by KnowOne134** [comment]
this is not a normal issue, but quest has been fully reworked since thei. closing
