### ISSUE TITLE
Third Eye issues

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#2125]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I noticed that Third Eye wears off after being hit by a normal attack when Seigan is active.
As I always understood, Third Eye should only wear off on AoE or after anticipating an attack.

![third](https://user-images.githubusercontent.com/36666121/66704313-e47f6e80-ed1a-11e9-902e-627d86476b63.PNG)

Also, according to wiki from 2007:
https://ffxiclopedia.fandom.com/wiki/Third_Eye?oldid=338161

Third Eye is supposed to fully anticipate Multihit attacks (i.e. Peckling Fury)

Edit:
Just thought about this, and both issues might be connected, i.e. sometime Peckling Fury gets anticipated ( I know this, spending alot of time seigan tanking birds ), but iirc third eye will always wear off after anticipating peckling fury, which by my understanding of this, shouldn't always happen.

Also, sometimes peckling fury will hit, even with thrid eye active, and third eye will wear off after, just like normal hits not being anticipated and followed by third eye wearing off.

**Comment by ShiyoKozuki** [comment]
still falls off prematurely w/seigan up (takes one hit and disappears sometimes)

**Comment by StriderClerix** [comment]
Per the wiki: https://ffxiclopedia.fandom.com/wiki/Third_Eye


> The chance that the player will keep the Third Eye effect even after anticipating tends to gradually decrease from the time that Third Eye is used. 5-6 anticipations is generally regarded to be a good/lucky streak, but note that it is always possible to get only one anticipation even if attacked immediately after using Third Eye.

**Comment by Falaras** [comment]
Pecking Flurry still is going through Seigan+Third Eye pretty regularly. Seems to happen about 50% of the time. Without Seigan up Third Eye always absorbs the Flurry like it should though.

**Comment by Serephim** [comment]
Still broken

**Comment by 59blargedy** [comment]
should be resolved by 10/18 update
