### ISSUE TITLE
Battlefield Effect Issue with ISNM

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2128]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When entering the ISNM Call to Arms the battlefield effect was only applied to myself, the person who initiated the ISNM, and the rest of the group was not able to enter due to this. Prior to this we had done ISNMs 3 times within the zone making the 4th attempt a dud. One of the earlier ISNMs was also started by me and afterwards I went back to town to buy another order to have another attempt at an ISNM. I'm not sure if this is what caused the issue but I was the only one who started an ISNM twice on the same day. The first order I used was purchased earlier in the week.

version 30181205_0

**Comment by 59blargedy** [comment]
should be resolved with move over to new bcnm system a couple months ago, comment if this occurs again
