### ISSUE TITLE
Call to Arms - Summoned Imp Bandsman HP

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2129]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

In the ISNM Call to Arms the Imp Bandsman that uses Bugle Call summons imps that have the same initial HP as it. Summoned imps should have less HP than the Imp Bandsman that is first encountered in the ISNM.

"The called imps have the same name, but are significantly weaker and will not call imps themselves." https://ffxiclopedia.fandom.com/wiki/Call_to_Arms

version 30181205_0

**Comment by FariskaEden** [comment]
Attempted this on retail and I think the summoned imps should have around 1900hp, 76 damage to one of the summoned imps took it down to 96% hp.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
