### ISSUE TITLE
Gobbiebag quests probably giving Mog Sack slots

### ISSUE THREAD

**Issue by Xaver-Entropia** [EdenServer/community#213]
As the title says.
https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Lower_Jeuno/npcs/Bluffnix.lua
Lines 98, 99 and 100:
    player:changeContainerSize(0,5);
    player:changeContainerSize(5,5);
    player:changeContainerSize(6,5);

Also, since new players in server are getting all containers, could we please have Mogwardrobes 3 and 4 opened? I mean, gear inventory is horrible atm, specially with the new gear, gear not scaling down, almost no gear in AH, etc...

**Comment by Aneyus** [comment]
@godmode issue is apparently not fixed. still receiving reports of people getting sack/satchel slots.
