### ISSUE TITLE
Lauan Shield Unavailabe at NPC

### ISSUE THREAD

**Issue by itsamemaybe** [EdenServer/community#2130]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

I tried buying the lauan shield from Carautia in Rosel's Armour Shop in southern san d;oria.  Shield did not appear in inventory.  Should be available to all when Sandy is of any conquest rank.  For reference I talked to the NPC as a Sandy citizen of Rank 5, using a PLD level 1. 

I have previously (don't remember exactly how long ago) purchased this shield from this NPC on this server. However that was multiple weeks ago.

**Comment by Volkaru** [comment]
Looks like in-era Lauan Shield isn't listed as sellable by her. You may have purchased it before an NPC audit happened. https://ffxiclopedia.fandom.com/wiki/Carautia?oldid=360748
https://ffxiclopedia.fandom.com/wiki/Lauan_Shield?oldid=317824

Carautia doesn't show up as a seller of the item until at least 2011: https://ffxiclopedia.fandom.com/wiki/Lauan_Shield?oldid=1369963
