### ISSUE TITLE
Dynamis Beau - Hee Mida the Meticulous RNG & NIN?

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2133]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Hee_Mida_the_Meticulous?diff=234860&oldid=55158

According to wiki, Hee Mida is a RNG however I'm told it uses both NIN and RNG 2hrs. Haven't been able to see it myself cause it's now always handled as a NIN mob and just time nuked.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
