### ISSUE TITLE
Shadows of the Mind & Sleepga/Clone HP

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2134]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = N/A

Even https://ffxiclopedia.fandom.com/wiki/Shadows_of_the_Mind?diff=374597&oldid=369083 (the last update before our era cutoff) states that clones could ONLY be slept by BRD's lullabies, not sleepga. According to the current wiki page, they are laughably easy to sleep with lullaby ("Bard using a stringed instrument with only 105 stringed instrument skill never got resisted"). Currently with RDM/BLM I had no resists using Sleepga, but as a BRD with 71+58 CHR & 462 skill, I had several resists using Horde

The clones also don't take extra damage from ice spells from what I've seen. A BLM using Blizzaga II only did ~450 damage on the clones, but in this video https://youtu.be/fRc5nZjD3r8?t=75 you can see that a RDM/BLM cast Blizzaga 1, dealing 178 damage to the main puk and 580 to the clones (3.25x) on lightsday, 1 shotting them.

**Comment by E5una** [comment]
Just to add to this, BLU is able to Soporific with seemingly 100% success, when it should be immune to dark based sleeps.

**Comment by Mozzy4Ever** [comment]
My understanding of the issue is that currently there is no difference between light based sleep and dark based sleep. Only resistance to dark/light element, or resistance to sleep.

**Comment by 59blargedy** [comment]
resolved in october 4, 2021 patch.
