### ISSUE TITLE
Beastmaster mobs in dynamis use familiar instead of charm when their pet is killed first

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#2135]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

v.30181205_0
I've noticed a few times when a beastmaster's pet is accidentally be killed before its master in dynamis, that the beastmaster will still use Familiar as its 2hour ability instead of Charm.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
