### ISSUE TITLE
Dread Spikes - March 2007 *In Era*

### ISSUE THREAD

**Issue by sukasaroth** [EdenServer/community#2137]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Dread_Spikes?oldid=202588

I've heard from many people that this server is based off of 2007 Era so I wanted
to take the time to suggest the addition of Dread Spikes, which were added in the March 2007 patch.

**Comment by VeilEden** [comment]
They’re in the game.

**Comment by Mozzy4Ever** [comment]
Yea. definitely already in the game lol
