### ISSUE TITLE
Hydra: Serpentine Tail/Trembling not correct.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#2138]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [N/A] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently Serpentine Tail is single target absorbed by 1 shadow.  It should be conal with 2-3 shadows taken, like other ToAU king tail attacks (Scorching Lash and Plague Swipe).

**Comment by Lilswitche** [comment]
Trembling also incorrect. Currently it wipes shadows whereas it should be absorbable by 2-3 shadows.

**Comment by Raphtalia1** [comment]
Can confirm, Hydra Serpentine Tail only hits one target, all the Wiki's seem to have low or no information regarding the tail, but switche is probably correct here as the other ToAU kings opperate similarly

**Comment by Treble011** [comment]
S-tail definitely takes more than 1 shadow, though, every time. If you only have 1 shadow and it hits you, you are going to take damage.

**Comment by Treble011** [comment]
I found this mechanic that is unique to tinnin: Nerve Gas: Wide conal AoE Breath Attack that causes Curse Curse (Status Effect) and 20hp/tick Poison Poison (Status Effect). **AoE range may be affected by how many heads Tinnin currently has, with fewer heads making the cone narrower** 

-- I wonder if Hydra has something similar, where the radius of his aoe (or conal abilities) changes due to how many heads he has. It would make perfect sense.

**Comment by Lilswitche** [comment]
I've messed around with Hydra on retail as 95NIN and recorded some video.  The following are things I have noted about Hydra abilities/mechanics which differ from Eden's:

**TP moves from behind**- Eden's Hydra will only use Serpentine Tail.  Retail Hydra is able to use Trembling, Serpentine Tail, Pyric Bulwark (right head alive) and Polar Bulwark (left head alive) when attacking with it's tail.  It tends to heavily favor Trembling when only 1 head is remaining.  

**Serpentine Tail** - I only had the opportunity to test it with 1-head and 2-heads, in both instances it was single target.  This ability can take up to 3 shadows, and based on my approximations of dodging hits on 95NIN, I would be willing to say it's very high accuracy against a level 75 character.   I was unable to test if it was AoE at 3 heads because, as you can witness in the videos, it very heavily favored other abilities at 3 heads.

**Trembling** - This ability is absorb-able by shadows, it does not wipe.  It can take up to 3 shadows and will dispel a # of effects based on the number of hits it got past shadows.  

**Barofield** - The gravity effect from this ability is **potent** and has a **long duration**. _Refer to the videos for evidence of potency_.

**Draw-In** - Retail Hydra will draw-in an individual if it leaves Hydra's battle area or when they're approximately further than 9 yalms away.  Immediately after drawing in a character, it will use a damaging TP ability (Trembling, Polar Blast, Pyric/Polar Blast [if able]), regardless if it has enough TP.

**Regain** - Hydra does have regain, regardless of the number of heads and HP that it has. At sub 25% it appears to  use a TP ability approx every 30 seconds indicating a TP regain of roughly 100TP/tick.

**Head Regeneration** - I tested this at high HP and head regeneration appeared to be timed at exactly **15 minutes** regardless if Hydra was unclaimed at 100% HP. The time it takes to regenerate a head appeared to scale down with it's current HP.  Below **25% HP** a head would regenerate at just over **2 minutes** as evidenced at times 24:42 and 26:48 of the last video.  You can note that when Hydra **regenerates a head it will immediately use a TP ability** regardless of current TP (at 22:42 it had just used a TP and would not have had enough TP.  I did not test head respawn times at intermediate HP% amounts like 50% or 75%.

**Regen** - HP regen is noticeable even at 1-head.  It increases signification at 2/3 heads.  I did not calculate a rough estimate of the HP regen but there are periods in the last video that you might be able to time a full percentage point to get a rough HP/tick regen. 


Videos: 
[1](https://www.youtube.com/watch?v=K79267fJ5IA&feature=youtu.be)
[2](https://www.youtube.com/watch?v=Zhx8vdsnsBE&feature=youtu.be)
Third video incoming - I was unable to upload the full length and will have to trim it down.

**Comment by Raphtalia1** [comment]
Just a quick note: Eden’s hydra will also use both bulwarks when tanking from behind as well, and uses them far more frequently than other tp moves

**Comment by roriffxi** [comment]
Tacking on to this:

Hydras serpentine tail is now activating / striking targets in front of Hydra.  It appears to happen when someone has attacked it from behind (like a thief) but didn't pull hate right as it gained TP.

**Comment by Axelution** [comment]
Hydra is also able to regenerate both heads at the same time, resulting in one TP move per head being used back to back. Sometimes three TP moves would be used back to back. The animation for a head loss would also sometimes not play.

**Comment by 59blargedy** [comment]
i think most of this has been resolved as of may 22, 2023's patch, though will need to test serpentine tail to determine when it should be AOE and when it should be single target. be easier to understand if any issues remain in a clean new report
