### ISSUE TITLE
H2H weaponskills

### ISSUE THREAD

**Issue by beauxq** [EdenServer/community#214]
This is something that was fixed on Kupo, same fix needs to be applied here.

Here is the fix:
https://github.com/bdhs/darkstar/commit/01cb8828b332c3e40f27e5d458d5d4247653e776

Hand-to-hand weaponskills should be like dual wield in TP return (first 2 hits full TP) and also like dual wield in number of hits (always at least 2 hits).

**Comment by godmode** [comment]
Does this factor in Martial Arts? I felt Kupo's adjustment was a bit too slow.

**Comment by beauxq** [comment]
This is not the attack speed one... that was a different patch.

**Comment by Serephim** [comment]
Yeah nearly all the weapon skills are wrong. Like it's saying Dragon Kick is an 8 fold attack. lol

**Comment by gweivyth** [comment]
> Yeah nearly all the weapon skills are wrong. Like it's saying Dragon Kick is an 8 fold attack. lol

:O  You have my attention...Is it returning TP like a multihit too?

**Comment by beauxq** [comment]
I think that Dragon Kick tooltip is just a typo in the client dats, and has nothing to do with the server.

**Comment by Serephim** [comment]
Yeah most of the tooltips for H2H are wrong. lol

**Comment by beauxq** [comment]
Dragon Kick 8 hits is the only tooltip I found that is wrong. What else are you seeing?

**Comment by Serephim** [comment]
> Dragon Kick 8 hits is the only tooltip I found that is wrong. What else are you seeing?

All the single hits are showing as 2 fold attacks as well.

**Comment by beauxq** [comment]
That is not wrong. That is correct.

There are no single hits. All H2H weaponskills are at least 2 hits. That's how it has always been on retail.

That's what DSP has wrong, and that is part of the reason for this bug report here.
The client has it correct. DSP has it wrong.

**Comment by Serephim** [comment]
> That is not wrong. That is correct.
> 
> There are no single hits. All H2H weaponskills are at least 2 hits. That's how it has always been on retail.
> 
> That's what DSP has wrong, and that is part of the reason for this bug report here.
> The client has it correct. DSP has it wrong.

All wiki's just say they are just single hit attacks. And they specifically say that multi hit weaponskills are 2 fold, 3 fold, 8 fold, ect... None of them say any of those attacks are 2 fold attacks. The only 2 fold attack Monk has is Tornado kick and it specifically says it's a 2 fold attack. 
https://ffxiclopedia.fandom.com/wiki/Category:Hand-to-Hand
https://www.bg-wiki.com/bg/Category:Hand-to-Hand#Weapon_Skills
http://ffxi.allakhazam.com/wiki/Hand-to-Hand_%28FFXI%29
Shoulder Tackle, One Inch Punch, Backhand blow, Spinning attack and Howling Fist are all single hit attacks. Even their animations are all single hits.

**Comment by beauxq** [comment]
Go find any videos of those weaponskills and look at the TP return. The TP return makes it really obvious. H2H has always been like dual-wield in TP return and number of hits.

You can also find that they are 2 hits in damage calculators.

The people who put the information in the wikis said they were one hit because they only paid attention to the animations and the unclear tooltips (that SE has since fixed). SE wouldn't have made that many mistakes at once. They just made a simple typo with Dragon Kick.

**Comment by beauxq** [comment]
@godmode This looks like it is not working.

**Comment by godmode** [comment]
Hmm, I merged the code in from your branch. Setzor has a PR out that touches more code though.

**Comment by gweivyth** [comment]
I didn't get a chance to mess with this last night but I promise to get to it tonight.
