### ISSUE TITLE
Mokyokyo at Odin's Gate in Windurst Waters has Kenappa-Keppa's dialogue

### ISSUE THREAD

**Issue by tjackson** [EdenServer/community#2140]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
A search for these NPCs here on the Github issues tracker didn't show anything.

- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

- [x] I have provided my client version in the details. (type /ver into your game window)
version 30181205_0
### Details

An NPC at Odin's Gate, Mokyokyo, has Kenappa-Keppa's (a different, unrelated NPC) dialogue. Observed while talking to everyone in Windurst Waters to do the "Hat in Hand" quest.

The dialogue  starts like "Our work...never works..."

Simply speak to him. Currently it's unclear if you need to be on the Hat in Hand quest.

**Comment by KnowOne134** [comment]
tested and could not reproduce, sugest closeing if issue isnt happening still

**Comment by KnowOne134** [comment]
Tried that also, no problem found
