### ISSUE TITLE
Incorrect Job Distribution for Skeleton mobs in Sea Serpent Grotto & Xarcabard

### ISSUE THREAD

**Issue by Dribblet** [EdenServer/community#2142]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0
While looking around for WAR Skeletons in the 40s to solo, I noticed that in both Xarca and SSG that there are only BLM-type skeletons (Lost soul in Xarca, Ghast in SSG).

While it's hard to me to say exactly where or how they spawn, there should be at least a reasonable distribution of both, compared to the current spread of 100% BLM all day every day.
This will likely need a capture from a retail account to figure out where the WAR skeletons would spawn vs BLM.

Couple of links of evidence I dug up:

Ghast (WAR)
- https://ffxiclopedia.fandom.com/wiki/Sea_Serpent_Grotto?oldid=364670 - Says there should roughly be an even split between WAR and BLM skeles in the zone, unlike the current distribution
- In this vid at 12:02 you can see a WAR Ghast in the distance. This video is the only footage in SSG I could find not killing NMS, and it's also OoE so grain of salt. It also shows the the Ghast on the tunnel path to Norg is always BLM which means it's not a randon chance to be a BLM or WAR Ghast.
https://youtu.be/_i0cckLcVjI?t=722

Lost Soul (WAR)
- https://ffxiclopedia.fandom.com/wiki/Lost_Soul - Shows they spawn in Xarca, and that they aren't listed as (BLM Only) for the zone
- https://www.bg-wiki.com/bg/Xarcabard - Another Wiki confirming War Lost Souls would be spawning in Xarca
- Video of someone killing WAR Lost Souls, admittedly OoE since it's hard to find someone in-era just recording the zone, but shows WAR Souls exist and where 1 would/could spawn. https://www.youtube.com/watch?v=XdL-EKfBzZY

**Comment by ShiyoKozuki** [comment]
Same issue for wendigo's in horutoto ruins, they all spawn as warriors only BUT drop the caster-specific gravity spell scroll and test answers quest item.
https://ffxiclopedia.fandom.com/wiki/Wendigo?oldid=317410

**Comment by Lehawah** [comment]
Same issue for Wights! Particularly troublesome farming the BLM type spells. (at least i think drops are exclusive).
I remember the Ice Spikes sound being the feared tell tale sign of many Skeleteon Spawns. While farming Escape i did not come across **Wight Skeleton** with Ice Spikes or casting spells at me! (Others, yes, but Wights there was none - **it should be BLMs as much as WARs** from experiance.) This is true for **Qufim Island / Gusgen Mines / Maze of S.**

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
