### ISSUE TITLE
Bastok 9-2 Where two paths converge

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#2143]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

So this battle is very bugged. I tried soloing it and spawned a pet Homunculus that later died.
As I was losing the battle I ran away and re-entered after zoning. When phase 2 came Volkers name was Homunculus.

Didn't win so came back a few days later with 2 more people.
Now upon phase 2 the battle spawned 1 Volker for each character that entered.
There were also no CS after the battle ended.

**Comment by Balrahn** [comment]
Also Zeid never spawned any shadows.

**Comment by Volkaru** [comment]
" I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)" Please search before submitting a new report. all of this is detailed in #1431

**Comment by godmode** [comment]
Just a note for both reports. I have audited this and most other nation missions and fixed related bugs. It is in a PR now so it should be in the 1st November patch.
