### ISSUE TITLE
Wrath of Gudah gives me insane movement speed.

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#2145]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

In Dynamis Bastok the NM TP move Wrath of Gudah gives me a gravity effect. While the effect is active I get movement speed far faster than flee. Noticed this speed 2x. Didn't notice anyone else getting the effect. I were wearing dusk gloves and ledelsens.

**Comment by perkuprightmeow** [comment]
Can confirm this happened to a member in our Dynamis. Not sure why, but he was also wearing dusk hands + feet (did not happen to anyone else also wearing the same combo).

**Comment by baroom84** [comment]
It's a huge knock back and you don't get the animation for the knock back. I think it just has you in two locations at once and it confuses the game.

**Comment by icariumkupo** [comment]
Sounds like an underflow on speed value from the gravity + dusk

**Comment by 59blargedy** [comment]
resolved 11/16
