### ISSUE TITLE
Sacrifice Torque Latent Won't Activate

### ISSUE THREAD

**Issue by inaringo** [EdenServer/community#2147]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Latent effect (3 mp and 8 hp a tick drain, pet +att) on torque is supposed to activate when yourself or party member has summon out. With summon out no drain was observed.

**Comment by Hestichan** [comment]
can we get an update on if this will be fixed soon pls?

**Comment by Hestichan** [comment]
pwease?

**Comment by Zaekkor** [comment]
Latent still not working. Observed no mp/hp drain, and !statcheck on test server shows no +atk being added.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
