### ISSUE TITLE
Poison hp/tic too high

### ISSUE THREAD

**Issue by AJ3281** [EdenServer/community#215]
Orcish Mesmerizer in Ghelba casted poison on me for 3-5hp/tic every second or so. This should be 1hp a tic.

**Comment by AJ3281** [comment]
Ghost in highlands just cast poison on me for up to 19/tic. Please fix this!

**Comment by Oyaziiiiiii** [comment]
We fought Olla grande last night and his poison was doing 100 hp per tick.

**Comment by godmode** [comment]
Make Poison Great Again. Probably another consequence from the enfeebling update from DSP.

**Comment by gweivyth** [comment]
Wait until you experience Paralyze, lol.

Yeah new DSP enfeebling is way out of time for 75.
