### ISSUE TITLE
Breakrate of hatchets vs. pickaxes is not era accurate

### ISSUE THREAD

**Issue by freddiepines** [EdenServer/community#2150]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

Version 30181205_0

Currently on Eden nearly no one is logging; mining is much more profitiable not only due to the market but also due to the cost difference in pickaxes (180g @ max fame) vs hatchets (450g @ max fame) and the breakrate on both.

I tracked an extensive amount of digs & chops in Yughott Grotto and Ghelsba Outpost, both while wearing a full set of NQ gathering gear:

15279 items dug with 3449 pickaxes - 4.43 items per pickaxe
3154 items chopped with 702 hatchets - 4.49 items per hatchet

The breakrate on hatchets should be vastly lower, data indicates they are breaking at approximately the same rate as pickaxes here on Eden.  Some posts from a few places on the internet about logging in era:

http://ffxi.allakhazam.com/db/item.html?fitem=1304

" I can usually make a stack last for a couple hours of steady logging."

"With a full set of level one field gear in less than 5 mins at Ghelsba Outpost i was full of logs with no break-age at all.. "

https://www.bluegartr.com/threads/68460-Gathering-hobbies?s=774e96bfe511cf958028c81abe7ea06e

"I haven't mined for years, but yeah. Back when I did it it seemed like the number of breaks was way way higher than I'd get in the other gathering "crafts". I assumed it was intentional, since (back then) you could could make tons more money through mining than through the others."

http://ffxi.allakhazam.com/db/item.html?fitem=2686

"Harvesting gives tons of items/point, and few breaks...but the items suck.
Logging gives few breaks, and a good deal of rare items, but sometimes you chop 6-7 times at one tree.
Mining gives lots of multiples, and several rare items, but at the cost of TONS of breaks."

Also, somethng to consider is the NPC price of hatchets (non-guild vendor) at 450 gil and pickaxes at 180 - we currently have a situation where pickaxes are yielding 2.5 times more items per gil spent and the market value of those items is typically much, much higher.  

Easily reproducible by chopping trees and mining nodes and tracking the breakrates of both and the items gained.

Happy to share my data w/ the developers on request.

**Comment by Zaekkor** [comment]
JP wiki entries on break rates here:
http://wiki.ffo.jp/html/2150.html (Hatchet) 
http://wiki.ffo.jp/html/911.html (Pickaxe)

**Comment by freddiepines** [comment]
Issue updated with more data. 

Tested again on 5/12/20 and the breakrates remain the same, thanks.

**Comment by tobioeden** [comment]
Zaekkor posted it as well but I translated the break rates into the following google sheet.
https://docs.google.com/spreadsheets/d/13LKs54UrgUPAA8gL74hluDMD93hnQ8XU1fcN2RKg5c4/edit?usp=sharing

**Comment by Mozzy4Ever** [comment]
Update for this - If logging nodes are stacked on top of each other, the break rate definitely seems higher. Did some quick testing resulted in this:

```
Only 1 point on a tree (11 instances):
15 breaks
35 nothing
43 item
15 item + hatchet break

Stacked logging points on a tree (5 instances):

14 breaks
19 nothing
9 item
14 item + break
```

Even with less than half (well, by 1) of the "stacked nodes" instances, I had the same hatchet break rate and the same item+break rate as if the node was by itself on a tree.

So for anyone interested in avoiding this bug, I would recommend having multiple people in the same zone at a time so that the nodes don't stack on top of each other.

**Comment by freddiepines** [comment]
Over 1 year later this is still an issue.

Hatchet breakrates and pick breakrates should not be equal - data shown below from the JP wiki (linked above in Nov. 2019):

Hatchets

![image](https://user-images.githubusercontent.com/50085658/97503542-96500400-194b-11eb-8bbe-328208019ecb.png)

Pickaxes

![image](https://user-images.githubusercontent.com/50085658/97503491-7f111680-194b-11eb-8a38-75c25bf81c4a.png)

Would be nice if we had another source of logs other than the guild / chocobo digging, fixing hatchet breakrates would make logging viable on Eden.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
