### ISSUE TITLE
DBox crashes when sending Elm mats or Mythril mats

### ISSUE THREAD

**Issue by CdoubleOkay** [EdenServer/community#2152]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Version: 30181205

When trying to dbox Elm mats (Logs or Lumber) or Mythril mats (Ore or Ingots) my dbox crashes and removes everything. I have been able to replicate this on 3 different characters.

https://gyazo.com/f00cee048968312da920a3e8693210ed

**Comment by KnowOne134** [comment]
It's any stackable item and I've informed the team and looking into it. Fix for now would be if you have an item stack that won't go in. Split the stack

**Comment by CdoubleOkay** [comment]
Isn't just stacks for me now. Can't dbox a Merman's Earring either

**Comment by KnowOne134** [comment]
Should be fixed. Test and can close

**Comment by KnowOne134** [comment]
Issue has been fixed
