### ISSUE TITLE
Slowga going unresisted on HNMs

### ISSUE THREAD

**Issue by Kurtalicious** [EdenServer/community#2153]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver the newest one 

Resist rate on Leviathan slowga is much lower in comparison to a 75 rdm.  I'm yet to see Levithan get resisted by Cerberus but yet seen multiple rdms struggle to land slow 1 out of 5 times
.

**Comment by StriderClerix** [comment]
As an in-Era summoner, 
With full skill set you could achieve high success rates. 

Summoner’s skill does nothing on this server at the time.

**Comment by Jimmayus** [comment]
Bumping this for a demonstration in action on Khimaira: https://youtu.be/_wJE_TnDCtk . Notable examples of in-era reliable sources noting the difficulty of slow landing on this monster:

- https://kanican.livejournal.com/tag/hnm%20fights! (search 'Khimaira')

- http://ffxi.allakhazam.com/db/bestiary.html?fmob=5828

- https://www.bg-wiki.com/bg/Bellerophon%27s_Bliss -- This is the 1st Lieutenant fight against a monster of the same family as Khimaira. I link it here as a suggestion that slow in general is notoriously difficult to land on this family

- https://ffxiclopedia.fandom.com/wiki/Khimaira

I can attempt to get some idea of resistance for retail slowga on this same monster, but of course retail's calculations heavily favor summoners so it will be generally biased in their favor.
