### ISSUE TITLE
Mamet fight ending when mamets use certain abilities

### ISSUE THREAD

**Issue by Raphtalia1** [EdenServer/community#2154]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
 
Mamets will ready ... and then the BCNM ends with no success, currently impossible to clear

**Comment by Raphtalia1** [comment]
![unknown](https://user-images.githubusercontent.com/50685071/67359957-f4206380-f521-11e9-9863-3f204292ffa6.png)

**Comment by slassen** [comment]
This was an issue with Tenzen sharing a mobskill list. Should have been fixed already now.
