### ISSUE TITLE
Bridge in Oldton Movalpolos Not Working

### ISSUE THREAD

**Issue by Grayrail** [EdenServer/community#2156]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I searched for Oldton and Swashstox before making this report.

My friends and I worked to operate all the levers in Oldton Movalpolos to raise the bridge to get to a certain part of Newton Movalpolos so we can fight Swashstox Beadblinker.  We tried a bunch of different times and ways and the bridge levers did not work.

I checked this list: https://classicffxi.fandom.com/wiki/Notorious_Monsters%3A_Level_Guide and noted that Swashstox was viable on this server, however I am not aware of a way to actually move to the area where it pops.

If a fix cannot be made for the bridge, maybe a warp can be set up much like how the bridge for the airship is completed in Port Bastok.

Thank you for your time!

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
