### ISSUE TITLE
Rank 4 mission CS not triggering correctly

### ISSUE THREAD

**Issue by Yubadub** [EdenServer/community#2159]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
I just finished Rank 4 mission. I got the airship pass by clicking the Audience Chamber and my next step is to go talk to Windurst Embassy and talk to the receptionist.
By mistake, I spoke to the SanDoria Embassy receptionist NPC and got a cut scene that involves Archducal permit key item. 
After the cut scene the area turned black except for the npc.
Now when I talk to Windusrt embassy npc, she says "as long as Star Sybil is safe, then all is well.  We don't have any task for you here, so continue your service to your country".

Version 30181205_0

**Comment by 59blargedy** [comment]
resolved with April 26, 2021 update
