### ISSUE TITLE
Event Storage NPC not working

### ISSUE THREAD

**Issue by LokiStinkpalm** [EdenServer/community#216]
so i did the halloween event and got all except for pitchfork+1.  went to store all 9 items and the npc in windy wouldnt take ANY of them.  yes i have the right npc, yes im trading one item at a time, and yes i tried on multiple chars

**Comment by Wiggo32** [comment]
that's going to be added soon. working on resolving a conflict atm.

**Comment by LokiStinkpalm** [comment]
ok thanks

**Comment by KnowOne134** [comment]
found no issue with the npc at this time
