### ISSUE TITLE
Rage disappears on mob going white

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2160]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [NA ] I have provided my client version in the details. (type /ver into your game window)

### Details

Killing Serket, got it to ~25% when it raged. Held out for 6 minutes before party got wiped. Went white, another group voked it instantly and it had zero rage even though it didn't even get above 30%

**Comment by Aneyus** [comment]
Afaik this is intended behavior. As soon as the mob goes white, rage is off.

**Comment by godmode** [comment]
The way I remember it is it needs to regen to 100% for rage to wear. Anyone else remember anything different?

**Comment by MalteseFalcon** [comment]
I remember it only needed to go white, have no aggro on anyone and regen 1 tick. Which is what it basically says on the wiki;

Rage status will only be removed by allowing the monster to become unclaimed and have zero hate on anyone in the area. After becoming passive, it will immediately lose its rage status. 

https://ffxiclopedia.fandom.com/wiki/Rage

**Comment by perkuprightmeow** [comment]
Here's a video of a 2008 raged NQ Behemoth being re-claimed shortly after going white at 9% and being unraged, also claimed at 9%: 

https://www.youtube.com/watch?v=SjKLOOTxuWw

**Comment by setsuk0** [comment]
https://www.bluegartr.com/threads/51076-Rage/page2
2007 forum post--
"Rage ends when the monster raging de-aggros. I know this from KA and Simurgh. This dumb RDm and THF raged it and killed a bunch of ppl til some maat capped MNk started kiting with herald gaiters while still raged until he lost aggrp and I claimed and killed. Same with Simurgh, THF with Dring qand shitty PLD +BRD raged, waited til it de aggroed and claimed and killed."

The ffxiclopedia page and misc. posts on BG forums point towards rage being erased once a mob completely de-aggros anyone in the area.

**Comment by Camuel666** [comment]
ok so even if the rage is supposed to end when he deaggros that also leaves the the nm is not properly raging. At 20 mins he became fully raged no spells would do dmg and attacks would constantly miss. This does not show the gradual increase in the stats as it supposed to be.

**Comment by Camuel666** [comment]
also spells like flash slow II para II would be resisted instantly after the initial rage

**Comment by CurzonEden** [comment]
At some point in 2008 they changed how the rage mechanic worked. 

During Era you had to let it go unclaimed, threat table to be clear and Regen to 100% in order for the rage to wear off.  I recall waiting with competing linkshells for mobs to hit 100% to claim then getting frustrated when somebody got it at 99% and had to start the process all over again. 
Here is the November 2007 Wiki entry: https://ffxiclopedia.fandom.com/wiki/Rage?oldid=376149


Later in 2008 it was changed to only require one tic of mob hp regen and nobody to be on the threat table. I'll try to find the patch notes on it a little later and update this post if I can.

**Comment by Lilswitche** [comment]
Very common misconception that a raged mob needed to regen for rage to wear off.  It only ever required the hate list being cleared.  You could actually have the last person on the enmity list die, and someone else within the party voke it before the mob went white and have it be rageless. 

If you look at the talk page on that entry, even in 2007 people were saying they could have it reclaimed unraged with as little as 1 tic of regen.  There's nothing in patch notes indicating this mechanic has ever changed and the more recent wiki entries reflect the fact that rage wears immediately when the enmity list is cleared.

**Comment by Balrahn** [comment]
Let us not forget this:
https://www.youtube.com/watch?v=aK5pVFqCtzs
