### ISSUE TITLE
Sabotender Bailarin - Missing

### ISSUE THREAD

**Issue by Redenius** [EdenServer/community#2161]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

The Cactaur NM known as Sabotender Bailarin is missing from the server. This NM was active on the server as early as October 14, 2005. This NM drops two items one of which I feel is vital to the economy. The Cactuar Root that it drops is used for a 102 alchemy synth that will help alchemist achieve level 100 "easier". It also drop the Bailathorn which can help with NIN leveling. Specific NM details can be found here:
https://ffxiclopedia.fandom.com/wiki/Sabotender_Bailarin?oldid=324931
this link is taken from the Revision as of 00:32, August 10, 2007.

**Comment by Redenius** [comment]
**There should be two Sabotender Bailaor normal mobs at H-7 of Map 2 to Quicksand Caves. One of which is the NM's placeholder. 

**Evidence of two Sabotender Bailaors can be found here:
https://www.youtube.com/watch?v=LgEKYQsPlvc
**In this Video it appears as if the real PH was killed and the other one was used by the beastmaster as a pet. It can drop multiple Bailathorn's as proven in this video.

**Drop rate information as well as spawn location for this NM can be found here:
http://www.ffxidb.com/zones/208/sabotender-bailarin

**This is a lottery spawn which I can only assume has a minimum of 1 hour repop.

**Comment by 59blargedy** [comment]
resolved in February 8, 2021 update
