### ISSUE TITLE
Jormungand aggro range.

### ISSUE THREAD

**Issue by Kurtalicious** [EdenServer/community#2162]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver the current one

Jormungand agro range seems to be pretty absurd.  He just drew me in from over 30 yalms away.  Can we reduce this to something a little more realistic you can barely walk to ENMs without aggroing him or waiting for him to move?

**Comment by PoppaPip** [comment]
Agreed that his aggro range is insane, but I don't know what it was supposed to be in retail.

**Comment by godmode** [comment]
Please keep bug reports for bugs, not requests.

**Comment by Kurtalicious** [comment]
This is not a request it needs an investigation because this might be a valid bug.  Please see the talk section of the Jormungand page and the testimony titled aggro range where a player tested it's aggro range, then posted their results.  Does anyone have any other testimonies or evidence?

"Aggro range
My friend and I were having a little fun with her tonight, found out sight agro was 30' and sound is about 13~15' --Nerji & Nedman of Phoenix 03:26, March 6, 2010 (UTC)

Nedman just found out it was 15' and is now 74 :) --Nerji 03:51, March 6, 2010 (UTC)

Okay, so if you have invisable up she won't agro till 15' --Nerji 04:03, March 6, 2010 (UTC)"

**Comment by godmode** [comment]
Thanks. This looks more like a bug report with this data now.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
