### ISSUE TITLE
Can not purchase Scimitar from Zhikkom

### ISSUE THREAD

**Issue by Rocketshuttle** [EdenServer/community#2164]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Was unable to purchase the weapon "Scimitar" from the weapons dealing NPC "Zhikkom" in Bastok Markets. Of the three alts/mules that attempted between myself and friends the only one who was able to purchase the item was the only one that did not have a "New Adventurers" status. To clarify, two characters labeled as New Adventurers were unable to purchase the item, but a character without this designation was.

Version 30181205_0

**Comment by bkesecker** [comment]
Checked the code and the era information, does not seem to be an issue.  Most likely the stock was depleted.  Did you try buying a Scimitar with a New Adventurer before the successful purchase by a player with higher standing?

**Comment by Rocketshuttle** [comment]
The issue was with two New Adventurers with the ? status.  Only the player without the ? status was able to purchase the item.  I wasn't aware that non-guild merchants could deplete stock, and even if they could I don't recall ticking past in-game midnight between attempts.

**Comment by KnowOne134** [comment]
i have found 0 issues in the code and testing confirmed no issue
