### ISSUE TITLE
Maximum concurrent linkpearls should be capped at 64

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#2166]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

[Source here](https://ffxiclopedia.fandom.com/wiki/Linkshell)
A maximum of 64 Linkpearls can be in use at any one time - however there can be an infinite amount of pearls in existence at any one time. Example: If you have a linkshell with 100 members only 64 of them will be able to equip and use the linkpearl at any one time.

**Comment by gweivyth** [comment]
What's the bug?  Is it uncapped at the moment or something?

**Comment by Drognand** [comment]
As it stands right now yes its uncapped I believe.

**Comment by Volkaru** [comment]
Honestly I feel this should stay as is. The 64 limit was a retail server congestion limit. And it was a headache all around for large linkshells.

**Comment by KnowOne134** [comment]
We have talked about it and have decided to leave it this way.
