### ISSUE TITLE
Diabolos Blood Pact: Ultimate Terror

### ISSUE THREAD

**Issue by NovadragonZero** [EdenServer/community#2167]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Diabolos in 3-5 uses a move called Ultimate Terror. He is using this move as a single target, not AOE. As normal cannot bypass shadows, but he has used it multiple times against us, only hits the Samurai.

https://ffxiclopedia.fandom.com/wiki/Ultimate_Terror

![Novadragon_2019 10 28_223910](https://user-images.githubusercontent.com/4391280/67724474-02192d00-f9d7-11e9-8551-6019bbcc7fcd.png)

**Comment by 59blargedy** [comment]
resolved in January 4, 2021 patch
