### ISSUE TITLE
Courier Carrie's stats (and likely other BST jug pets) are wrong

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#2169]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I went on retail today to test out the stats of jug pets and compared to Eden's. First glance is Accuracy/Attack/Evasion are ~7-8% too low and defense is 25% low.

Courier Carries /checkparams on retail (for levels 73, 74, 75):
Accuracy: 294, 299, 305
Attack: 309, 314, 319
Evasion: 272, 277, 283
Defense: 420, 427, 433

CC's /checkparam on Eden (73, 74, 75):
Accuracy: 272, 276, 281
Attack: 282, 287, 293
Evasion: 264, 269, 274
Defense: 303, 308, 314

I also did Amigo Sabotender, but I've never got him on Eden so I can't compare. Either way, his stats are significantly better than any jug on Eden. These are only for levels 73 and 75.
Accuracy: 297, 308
Attack: 337, 348
Evasion: 285, 296
Defense: 361, 373

I've done a ton of the NQ jug pets on retail and will compare to Eden once Eden's is up (I don't have random NQ jug stats lying around, but I do have CC/Allie/Audrey/Lars at 73-75)

**Comment by mlandrum22** [comment]
I found a site with the correct stats for each pet. 

https://www.ffxiah.com/node/371

These lineup with what I just found on current retail. 

I went through every version update from 2007 to 2011 from here: https://ffxiclopedia.fandom.com/wiki/Category:Version_Updates

And 2011 to 2019 from here:
http://forum.square-enix.com/ffxi/archive/index.php/f-84.html?s=1dbcd7ee8c265223750ca2b1de99bd86

And did not find a change to pet statistics (outside of ilevel adjustments, which don't apply to these), so I'm confident these are the stats that should be on Eden.

**Comment by HammerhandsKupo** [comment]
Retail stats are super buffed and CC should definitely not be as strong as retail CC.  You can one-shot most things with CC Big Scissors on retail, and even solo Under Arms with one CC jug.  

Going to retail to check things and saying it should be like that, is like saying I should be able to lift this much after seeing The Rock lift that much.

**Comment by Wade9363** [comment]
Not sure how setting jug pets Acc/Eva/Att/Def is going to allow CC to one-shot mobs or solo Up In Arms.  

Currently Big Scissors misses like 80% of the time and does like 200 dmg on xo mobs when it lands..

**Comment by HammerhandsKupo** [comment]
> Not sure how setting jug pets Acc/Eva/Att/Def to Era Retail is going to allow CC to one-shot mobs or solo Up In Arms.
> 
> Currently Big Scissors misses like 80% of the time and does like 200 dmg on xo mobs when it lands..

I was speaking of retail by making a point that retail is not a good comparison.

**Comment by Wade9363** [comment]
The original bug report links to a page with the base jug pet stats from 2007, and he confirmed it's the same stats as current retail at lvl 75.

**Comment by mlandrum22** [comment]
I checked every version update and there hasn't been any chance to pet statistics outside of ilevel pets.

**Comment by mlandrum22** [comment]
I'm assuming you didn't play BST in retail Hammerhands, Pets did insane damage vs EP and below. In #2172 I found a thread of a dude who did 40-50 damage in Batallia Downs where his pet was doing 200+ on autos (from 2005).

If he was doing 40-50 he was no higher than a level 50 BST.

Eden currently has a cap where CC can't do more than ~190ish, meaning a level 75 here can't even outdamage that level 50.

**Comment by HammerhandsKupo** [comment]
> I'm assuming you didn't play BST in retail Hammerhands, Pets did insane damage vs EP and below. In #2172 I found a thread of a dude who did 40-50 damage in Batallia Downs where his pet was doing 200+ on autos (from 2005).
> 
> If he was doing 50-80 he was no higher than a level 60(?) BST.
> 
> Eden currently has a cap where CC can't do more than ~190ish, meaning a level 75 here can't even outdamage that level 60.

I'm speaking of my experiences of playing BST on current retail. At 75 you can easily Big Scissors for 5k damage on EM, 1-2k on HNM, and ??? Needles for 9k damage on HNM.  While leveling to 75, I was easily killing EM's in 1-2 BS.  Say what you will, but damage numbers currently are immensely buffed on retail today.  

I am not speaking of 2007 era whatsoever.

**Comment by MB213** [comment]
Whatever is allowing those high damage numbers to happen on retail has almost nothing to do with a 24 accuracy and 26 attack boost, of that I'm certain. I doubt those values have changed at all, because they're honestly pretty low even for era.
