### ISSUE TITLE
http://ffxiclopedia.wikia.com/wiki/The_Chamber_of_Oracles

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#217]
I entered all 8 of my fragments and nothing happened.  I clicked on the Ice pedestal again and it triggered the cutscene.  This makes me think that clicking any of them after inserting all 8 probably works.  But I would expect the CS to be triggered on the 8th entry.

**Comment by godmode** [comment]
I’m pretty sure this is how the mission worked on retail but I’d have to look it up to be absolute

**Comment by roriffxi** [comment]
http://ffxiclopedia.wikia.com/wiki/The_Chamber_of_Oracles?oldid=130674

From 2006.  Walkthrough states the CS should occur after the 8th fragment is placed.
