### ISSUE TITLE
Unable to list a single item from incomplete stack on AH

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#2173]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Title says it all. Trying to list a single item on AH from an incomplete stack currently isn't working. 

Edit: Ver - 30190305_0

**Comment by Far-The-Killer** [comment]
Proof of era-ness
> For stackable items select a full stack to sell a stack and select a single or a partial stack to sell a single.

https://ffxiclopedia.fandom.com/wiki/Auction_House?oldid=348523

**Comment by Raizuo** [comment]
I, too, am having this issue but I've found a work-a-around. You must manually "unstack" the item until there is only 1/single unit of it. Then you can place it on the AH.

**Comment by KnowOne134** [comment]
Can no longer produce issue
