### ISSUE TITLE
ISNM 'Shadows of Mind' and ENM 'Holy cow' drop table issue reverted

### ISSUE THREAD

**Issue by AnkleAssassinz** [EdenServer/community#2174]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Hello,
 Just did ISNM 'Shadows of the Mind' and its dropping wrong items again.
[img]https://i.postimg.cc/qvBcPttx/JPANESEbutton-ONRY.jpg[/img]

AnkleAssassin

**Comment by danismyhero** [comment]
So to add on to this, I just did the ENM Holy Cow and received this drop:

![image](https://user-images.githubusercontent.com/49649778/68535170-a1a5bc00-0303-11ea-8be9-e489f8006aeb.png)

**Comment by KnowOne134** [comment]
Has been fixed. Can close
