### ISSUE TITLE
When failing a synth all materials lost with message stating you interupted your synth.

### ISSUE THREAD

**Issue by Lynara93** [EdenServer/community#2177]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
When crafting after the server came back up this morning, I noticed that when I failed a synth I would lose everything, every time, with a message stating that I had interrupted the synth. I tried zoning as well to see if it was a bad load however this did not remedy the situation. I have attached a word document with pictures of the encounter.

This can be reproduced by crafting in Bastok Mines or Bastok moghouses and failing the synth.

I apologize if this is not enough information.

[FFXI crafting isue.docx](https://github.com/EdenServer/community/files/3827745/FFXI.crafting.isue.docx)

**Comment by godmode** [comment]
Are you crafting using any FPS addons?

**Comment by Lynara93** [comment]
Not that I know of but I could be wrong, I leave it at /fps 2 (so capped at 30 fps)

**Comment by Lynara93** [comment]
Appears to be working correctly now, not sure if something was done or it was me just having a bad luck morning.
![image](https://user-images.githubusercontent.com/57574737/68535492-2c80b980-02f8-11ea-8fb7-de4788d9c2d2.png)

**Comment by Setz0r** [comment]
were you using a lastsynth macro and if so, what exactly did you have in it.

**Comment by Lynara93** [comment]
![image](https://user-images.githubusercontent.com/57574737/68535521-79649000-02f8-11ea-90bf-3a2bf6b0f522.png)
