### ISSUE TITLE
Shadow [RNG] in Fei'Yin will trigger a "getting hit" by a ranged attack animation even if the attack missed.

### ISSUE THREAD

**Issue by ghost** [EdenServer/community#2179]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Pretty self explanatory. I was THF/NIN when I noticed this. The chat log will say the ranged attack missed or that you lost a shadow but the animation (at least for mithra) will always be that you got hit by the ranged attack.

**It seems to be occurring with Goblin Poachers (Glacier) as well. I will edit as I find more mobs.**

/ver 30181205_0

Thanks.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
