### ISSUE TITLE
Character Stuck in Bostaunieux Oubilette

### ISSUE THREAD

**Issue by Frylokk** [EdenServer/community#218]
Was zoning here for a quest and now I am sitting above the map unable to move. Its totally black and I am above the map. Please get me outa here. Toon name is Kronk

**Comment by godmode** [comment]
You may want to submit a gm ticket on the website as well to get your character moved in the mean time. Most GMs won’t read bug reports

**Comment by Wiggo32** [comment]
this was resolved
