### ISSUE TITLE
Signpost being flagged as "Treasure Casket"

### ISSUE THREAD

**Issue by tengokujin** [EdenServer/community#2180]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Signpost in East Ronfaure, at G-7, is being flagged as "Treasure Casket" instead of "Signpost"
![edenxi_2019-11-10_22-09-20](https://user-images.githubusercontent.com/55920387/68558335-efefb380-0406-11ea-975c-8541d9f77aa3.png)

**Comment by KnowOne134** [comment]
Most likely you aren't running the official version for eden. But retails

**Comment by tengokujin** [comment]
Yup. It was because I'd tried to log into retail while server was down and it "updated" everything. Thanks for the advice.
