### ISSUE TITLE
Holy Cow ENM

### ISSUE THREAD

**Issue by Kurtalicious** [EdenServer/community#2182]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver "It's the new one"

Apis in the ENM Holy Cow needs to be re-tuned.  He is far too accurate, attacks too fast, double and triple attack rates are too high and does not take the appropriate amount of damage from elemental spells.  

The talk section on wiki claims that elemental ni/san spells should be doing 200/250 damage, respectively.  Elemental Ni spells here aren't even breaking 100 they are usually in the 20-90 damage range depending on its form.  

T3 elemental nukes are not doing the appropriate amount either.  Wiki says it should take anywhere form 700-800 while in it's weak to magic state.  The RDM in the video on the home page for the ENM is nuking for 950-1020ish all day.  I'm nuking it for 150-500 damage depending on form.

Oh also he isn't using any TP moves.  Ever.  

Please see the following links and video at the bottom of the wiki page for reference.

Tons of videos out there for reference here are a few.  The current mob is far more powerful than the push over you will see in these videos.  

2007 Era accurate video of a nin nuking for more than I ever could wish for and evading more than I could have hope (also take note of it's attack speed and accuracy): https://www.youtube.com/watch?v=Favb3KCiN2s

2009 Video of nin nuking the shit out of it: https://www.youtube.com/watch?v=-8KIUEmMMLQ

2009 Video of rdm nuking the shit out of it: https://www.youtube.com/watch?v=Xq1SMZs9Z20

2009 Video of a lessor geared rdm but still nuking for more than I ever could wish for: https://www.youtube.com/watch?v=yCT1QOEXuTM

https://ffxiclopedia.fandom.com/wiki/Holy_Cow
https://ffxiclopedia.fandom.com/wiki/Talk:Holy_Cow

https://ffxiclopedia.fandom.com/wiki/Apis
https://ffxiclopedia.fandom.com/wiki/Talk:Apis

**Comment by VeilEden** [comment]
Can confirm he uses TP moves. I duo’d it pretty easily on Nin + War. His accuracy wasn’t very good against my Nin, but after Steel Cyclone pulled hate he wiped the Wars shadows with a DA, into a 1400 dmg single target TP move. Can’t recall the name. Entire fight lasted about 90 seconds? One Darkness skillchain was approx ~60% of its health.

**Comment by PoppaPip** [comment]
Not sure about the rest of it, but currently on Eden when he switches modes he just takes _less_ damage, when in retail his modes would make him _entirely immune_ to that form of damage. You can see this in the videos where Bio will do 0 damage, or at 2:35~ in the first video where he tests by casting Stone (also doing 0 damage).

Also, Noralain has Novio Earring, obis and more, so that's a tough comparison to make.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
