### ISSUE TITLE
Diabolos Nightmare sleep seems underpowered or acting like regular sleep.

### ISSUE THREAD

**Issue by jamiehavok** [EdenServer/community#2186]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

Get to Darkness named Cop Mission. Go through Pso'xja and enter Diabolos Battlefield

- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Havent played in a while but saw these videos on youtube:

https://www.youtube.com/watch?v=4jFxwqVIPbg

never used Nightmare. 

and
https://www.youtube.com/watch?v=ra3X6uaPArA&t=24s

Uses nightmare once around 8:42 but sleep wears off immediatly like the bio itself got rid of it. Nightmare sleep should not wear off from damage or DoT spells only cures and last a good long while like regular sleep only being mitigated a bit by barsleep. Should probably use it at least once per battle too.

Obviously need people with first hand experience to chime in here.

**Comment by beauxq** [comment]
> Uses nightmare once around 8:42 but sleep wears off immediatly like the bio itself got rid of it.

Cure took off the sleep like it's supposed to. (It was a lucky cure timing.)

**Comment by jamiehavok** [comment]
Ah yeah i see that now! I'll leave this open though as i think he should be trying to cast nightmare more than 0-1 times in a battle - in retail it was more like 2-3 times i think.

**Comment by Tjonke** [comment]
Diabolos can either cast it 0 or 15 times, it's all random. Have fought him when he didn't cast it once and other times he would only spam it to the point where we ran out of stuns with 2 DRK/NINs and a BLU.
