### ISSUE TITLE
Corsair Double-Up has incorrect cooldown.

### ISSUE THREAD

**Issue by Leonira** [EdenServer/community#2187]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Version: 30181205_0

As per the title, the corsair ability double-up has incorrect cooldown before repeated use. 
It is supposed to have an 8 second cooldown, it's cooldown is currently one second (can use near instantly)

Steps to reproduce:
Be a corsair
Use any roll
Use Double-up
See how long it takes before you can double up again.

**Comment by Volkaru** [comment]
It is correct for era. Double up right after using a roll is instant. Then after that first one the recast is 5 seconds. The 8 seconds on FFXIClopedia is wrong and always has been, and any video from retail will show otherwise. Even a BGwiki entry from 2007 has the correct timer.
https://www.bg-wiki.com/index.php?title=Double-Up&oldid=1245

**Comment by Leonira** [comment]
Interesting. I tried to look into this, and while as you're saying, the bg entry you provided lists it at 5 seconds, I couldn't find any videos from the 2007 era that had a corsair doing rolls visibly to verify it. :/

Like you've guessed, I've gone off the information on ffxiclopedia (for 2007), and my personal experiences playing corsair on Nasomi (which uses the 8 second cooldown). I do not have any retail experience with COR, so you may well be entirely correct.

If you manage to find any video showing me a corsair doing instant double-ups or having a 5 second cooldown on it, I'll gladly alter or close this issue. :)

**Comment by Volkaru** [comment]
Nasomi has it even worse off. He has it set so double-up goes on cooldown when you first roll. It's supposed to be up instantly to use after one.

**Comment by KnowOne134** [comment]
No issue found

**Comment by Dribblet** [comment]
It is definitely not correct values for era. In-Era, and up until Sept. 20th, 2011, Corsair should have a 7 second recast on Double-Up. 

Sources (Which have also been compiled in Corsair Dossier on the Eden Discord):

Official Square Enix patch notes for Sept. 20 2011, clearly states: 
"The recast time for the corsair ability Double Up has been shortened from seven seconds to five."
http://forum.square-enix.com/ffxi/threads/15044-September-20-2011-%28JST%29-Version-Update
This sets the baseline that before this date, Double-Up has a 7 second Recast time.

This Youtube video shows a Corsair using Phantom Roll followed by 3 Double-Ups in a row.
https://youtu.be/-8-VsYyNwFM?t=275
Uses a Double-Up at the tail-end of 4:38, timer addon shows 0:07 recast for Double-Up, then he recasts Double-Up at the tail-end of 4:45 again, final Double-Up at 4:53.

Archived version of Ladyluck, a JP cor-only wiki also shows 7秒 (7sec recast) of Double-Up when dated back to Oct 11, 2007. 
https://web.archive.org/web/20071011092248/http://ladyluck.holy.jp/cor/index.php?%E3%83%80%E3%83%96%E3%83%AB%E3%82%A2%E3%83%83%E3%83%97

Ffxiclopedia, and Allakhazam show an 8sec recast for Double-Up when dated before the 09/20/11 patch. While those are also incorrect values, they are closer to the real value of 7sec moreso than the incorrect 5sec that BG-Wiki states.

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
