### ISSUE TITLE
Delivery Box - "Communications seem to be congested"

### ISSUE THREAD

**Issue by Althaia** [EdenServer/community#2188]
### Checklist

* [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
* [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
* [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is: Version 30181205_0

When attempting to remove gil from Delivery Box with a full 30/30 inventory, I got this message:

"Communications seem to be congested."

And it wouldn't let me take it out of DBox. Following that message, I also couldn't access the DBox or move things from my inventory to my Mog Safe.

Zoning in and out again allowed me to try again.

Eventually, I figured out the problem was the full inventory; upon freeing up some space, I was able to remove the gil from my Delivery Box successfully.

EDIT1: This just happened to someone else in my LS and the inventory wasn't the problem, so maybe it was just a coincidence in my case. Someone else said that she came back 10 mins later and then it worked.

EDIT2: The person in my LS just said that clearing inventory and zoning (as opposed to zoning then clearing inventory?) worked for her. So I dunno.

**Comment by KnowOne134** [comment]
Gil is also an actual item its just in the hidden inv slot 0. You will need room in inv to receive it the it auto sorts
