### ISSUE TITLE
Gardening appears to be frozen; plants won't grow.

### ISSUE THREAD

**Issue by Althaia** [EdenServer/community#2189]
### Checklist

- [ ✓ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ✓ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ✓ ] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is: Version 30181205_0

Every day since we came back from the two-week-or-so downtime, I've seen people asking if gardening and/or harvesting is screwed up.

I myself have noticed that my plants don't grow anymore. Everything seems to be frozen.

Is it possible that the GM hitting that emergency kill switch froze everything on the server, including gardening, and gardening was never un-frozen? Just a thought.

No one's made a topic yet and I was already here, so... here's the topic. ;P People feel free to add their own experiences/additional information.

**Comment by Leonira** [comment]
Can't provide anything to back this up, but I'd like to addd the question: 
Is this also affecting plants planted after the two-week downtime? Or only things that had already been planted before the downtime?

**Comment by TanstaaflEden** [comment]
I have wildgrass seeds planted. i fed a crystal before the server went down for 10+ days. they have not advanced to the next stage since the server came back up. they should have flowered by now.

**Comment by Pocketrockets81** [comment]
Same issue. I had 10 grain seeds and 10 wildgrass seeds that had already flowered prior to the shutdown, and they have not progressed to harvest.

**Comment by trodeghero** [comment]
In the same boat with my main and alt with wildgrass seeds. fed water crystals and they still haven't flowered yet ... they seem frozen in time

**Comment by jmcmorris** [comment]
I have pinpointed this issue and we will get it resolved soon. Thanks for reporting!

**Comment by KnowOne134** [comment]
Has been fixed, can close
