### ISSUE TITLE
Avatar lvl 70 BPs have SC properties

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#219]
The level 70 blood pacts (65 for fens eclipse bite) have skill chain properties.  It doesn't look like they should, only the lower tiered blood pacts.

Era source on blood pact skillchain properties:
http://www.taultunleashed.com/final-fantasy-xi-submissions/ffxi-avatar-skillchain-guide-t21336.html

The properties were added in 2014 to the high level physical BPs:
http://forum.square-enix.com/ffxi/threads/44943?p=530794#post530794
Skillchain attributes have been added to the following Blood Pacts: Rage
Ecliptic Bite / Flaming Crush / Mountain Buster / Spinning Dive / Predator Claws / Rush / Chaotic Strike

**Comment by Setz0r** [comment]
@roriffxi does this happen for mob avatars or player avatars?

**Comment by beauxq** [comment]
Where would we ever see 2 mob avatars that could skillchain with each other?

Mob avatars only use astral flow, except for the primes, which are alone.

**Comment by roriffxi** [comment]
@Setz0r Its player avatars performing skillchains.
