### ISSUE TITLE
Yagudo Ranged attack Bug

### ISSUE THREAD

**Issue by ReeceR09** [EdenServer/community#2190]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

Details:

Ver: 30181205_0

Firstly i'm sorry i am unsure what reproducable steps mean. 

Yagudo (Ninja job) are using shruikens on me and even when it is missing it is showing the hit animation and playing the hit sound. Tried this with a few yagudos to make sure this is repeatedly happening which it is.

The yags i was killing are the Heralds in Castle O around Quu Domi The Gallant.

IGN Lavond - Please let me know if i can be of any help.

**Comment by NovadragonZero** [comment]
![Novadragon_2020 01 07_233039](https://user-images.githubusercontent.com/4391280/71938064-26973f80-31a6-11ea-8e2e-35eabda720d3.png)

Goblins are doing it to.

**Comment by slassen** [comment]
Thanks for reporting. Closing this in favor of this report https://github.com/EdenServer/community/issues/2245
