### ISSUE TITLE
Coralline Uragnites in Purgonorgo Isle are Aggressive

### ISSUE THREAD

**Issue by batjokes** [EdenServer/community#2191]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Not sure if this constitutes a bug, but as far as I know, the Coralline Uragnites on Bibiki Bay -Purgonorgo Isle have always been non-aggressive.  Checking ZAM and BG Wiki says the same:  non-aggro and non-linking.  

As for "reproducable steps", all I did was exit the boat and tab out of the game with my character near the end of the dock (on the sand), and when I tabbed back in my character had died.  I thought a stray Kraken had gotten me, but checking the chat log shows that a Coralline Uragnite had attacked.  I did nothing to provoke it--no magic, job abilities, resting etc.  I was simply standing there.  

If this is an era thing I apologize, but afaik, they've always been non-aggressive.

![bandicam 2019-11-12 17-14-22-426](https://user-images.githubusercontent.com/57689978/68719821-cb184f00-0572-11ea-88ed-947983c6feca.png)

**Comment by ShiyoKozuki** [comment]
I've never seen a hostile urganite, this is 100% wrong.

**Comment by 59blargedy** [comment]
this was fixed in a june 2020 update
