### ISSUE TITLE
A Test of True Love - Reward Missing

### ISSUE THREAD

**Issue by Althaia** [EdenServer/community#2192]
### Checklist

* [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
* [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
* [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is: Version 30181205_0

I flagged the quest, got the keys, opened all three chests, returned to Carmelo for the cutscene...

At the end of the cutscene, he said the required text and the victory music that plays when you get a reward played, but there was no actual reward.

The reward is supposed to be 10k gil, but there was no line of text indicating I'd gotten the gil and my gil amount remained unchanged.

Also after clicking on Carmelo again, he defaults to his current default text for me, about the stars of Ifrit (I'm done with that quest, but this is just what he says when I'm not doing any other quest with him).

![](https://i.imgur.com/dKvD8gf.png)

**Comment by KnowOne134** [comment]
Did it complete the quest in your log?

**Comment by Althaia** [comment]
@KnowOne134 Yes, it did complete the quest in my quest log.

I see that GodMode closed the topic, is that because the issue's been fixed for anyone doing the quest in the future?

And if so, I'll go ahead and place a GM call for my 10k gil, please & thank you. XD

**Comment by KnowOne134** [comment]
I fixed it for next update to give reward. Case closed
