### ISSUE TITLE
Lovers in the Dusk - "Dusk" Time Different?

### ISSUE THREAD

**Issue by Althaia** [EdenServer/community#2193]
### Checklist

* [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
* [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
* [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is: Version 30181205_0

Hi, I don't know what time Dusk is in this era, but according to the guide I was looking at, I should have been able to complete this quest between the hours of 16:00 - 18:00.

I started clicking on the spot in Zitah at 16-something, but it didn't activate until 17:00.

Anyhow, I finished the quest and got the reward, just wondering if the time for "dusk" in-game was wrong.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
