### ISSUE TITLE
Jump, High Jump and Super Jump working incorrectly

### ISSUE THREAD

**Issue by MB213** [EdenServer/community#2194]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver 30181205_0

Last edit just to consolidate everything everyone contributed into one post.   
Thanks to everyone below for all of their testing, input and supporting videos.

Jump & High Jump:
- 	Enspell effects don't proc.
-	Additional effects don't proc. 

Super Jump:

-	Doesn't prevent AoE damage
-	Doesn't interrupt spells targeting the Dragoon
- 	Doesn't interrupt TP attacks targeting the Dragoon 

Sources:
https://youtu.be/-gBRaa7bk48?t=116			(Video: Super Jump avoiding Judgment Bolt)
https://i.imgur.com/IzoRXN0.mp4			        (Video: Super Jump cancelling a spell)
https://i.imgur.com/0iRO4Ir.mp4			        (Video: Super Jump cancelling a TP attack)
https://www.youtube.com/watch?v=aS0EYcAZpiE	(Video: Double Attack TP return)   
https://www.bg-wiki.com/index.php?title=Jump&oldid=53134 (2007 BG Wiki, lists what effects proc on Jumps)

Topaz code Virtuosus posted which may be helpful in addressing these issues:
https://pastebin.com/8tKmpZvj

**Comment by montijin** [comment]
Just confirming that this issue isn't an isolated with ridill. Jump/high jump with soboro, kraken club and mercurial kris never proc extra swings either.

**Comment by falzum** [comment]
Just exp'd for 2hrs as sam/drg. Had the same issue with Soboro. 15tp return, every time. No additional attacks while jumping.

**Comment by perkuprightmeow** [comment]
Bumping this since just tested and it's still an issue.

With Wyvern Earring being out it would be great if this was finally looked at :)

**Comment by VirtuosusFFXI** [comment]
Just did a bunch of testing.

1) Double Attack and Triple Attack do not proc on jumps.

2) Relic weapon hidden effects (occasionally deals 2~3x normal damage) do not proc on jumps.

3) Multi-hit weapons (such as Kraken Club/Soboro) do not proc on jumps.

4) Using a shield in the offhand slot is being considered as a second weapon for jumps and returning double damage/TP. This should not be the case. 

5) Enspells (such as Enwater, Enblizzard, etc) are not being accounted for in jump damage.


I believe all of the above stems from the fact that jumps are not classified as melee attacks on Eden/DSP.

https://ffxiclopedia.fandom.com/wiki/Jump

https://ffxiclopedia.fandom.com/wiki/High_Jump

**Comment by VirtuosusFFXI** [comment]
Found another problem.

6) Jumps are feeding enemies TP, which according to both wikis, they should not.

**Comment by VirtuosusFFXI** [comment]
The latest branch of Topaz seems to have included most of the above fixes for jumps, from what I can tell, aside from including Enspells/Additional Effects of weapons.

https://pastebin.com/et31xBsZ

`    /************************************************************************
    *                                                                       *
    *   Jump DRG Job ability                                                *
    *                                                                       *
    ************************************************************************/

    uint16 jumpAbility(CBattleEntity* PAttacker, CBattleEntity* PVictim, uint8 tier)
    {

        // super jump - remove 99% of enmity
        if (tier == 3 && PVictim->objtype == TYPE_MOB)
        {
            ((CMobEntity*)PVictim)->PEnmityContainer->LowerEnmityByPercent(PAttacker, 99, nullptr);
            return 0;
        }

        // target has perfect dodge - do not go any further
        if (PVictim->StatusEffectContainer->HasStatusEffect(EFFECT_PERFECT_DODGE, 0)) {

            // Claim the mob.
            battleutils::ClaimMob(PVictim, PAttacker);
            return 0;
        }


        // multihit's just multiply jump damage
        auto sub = dynamic_cast<CItemWeapon*>(PAttacker->m_Weapons[SLOT_SUB]);
        uint8 numattacksLeftHand = 0;

        //sub weapon is equipped
        if (sub && sub->getDmgType() > 0 && sub->getDmgType() < 4)
            numattacksLeftHand = battleutils::CheckMultiHits(PAttacker, sub);

        auto PWeapon = dynamic_cast<CItemWeapon*>(PAttacker->m_Weapons[SLOT_MAIN]);

        //h2h equipped
        if (PWeapon && PWeapon->getSkillType() == SKILL_HAND_TO_HAND)
            numattacksLeftHand = battleutils::CheckMultiHits(PAttacker, PWeapon);

        // normal multi hit from left hand
        uint8 numattacksRightHand = battleutils::CheckMultiHits(PAttacker, PWeapon);


        uint8 fstrslot = SLOT_MAIN;

        uint8 hitrate = battleutils::GetHitRate(PAttacker, PVictim);
        uint8 realHits = 0;         // to store the real number of hit for tp multipler
        uint16 totalDamage = 0;
        uint16 damageForRound = 0;
        bool hitTarget = false;

        // Loop number of hits
        for (uint8 i = 0; i < (numattacksLeftHand + numattacksRightHand); ++i)
        {
            if (i != 0)
            {
                if (PVictim->isDead())
                    break;

                if (PWeapon && PWeapon->getSkillType() != SKILL_HAND_TO_HAND && i >= numattacksRightHand)
                {
                    PWeapon = dynamic_cast<CItemWeapon*>(PAttacker->m_Weapons[SLOT_SUB]);
                    fstrslot = SLOT_SUB;
                }
            }

            if (tpzrand::GetRandomNumber(100) < hitrate)
            {

                // attack hit, try to be absorbed by shadow
                if (!battleutils::IsAbsorbByShadow(PVictim))
                {
                    // successful hit, add damage
                    float AttMultiplerPercent = 0.f;

                    // get jump attack bonus from gear
                    if (PAttacker->objtype == TYPE_PC)
                        AttMultiplerPercent = PAttacker->getMod(Mod::JUMP_ATT_BONUS) / 100.f;

                    float DamageRatio = battleutils::GetDamageRatio(PAttacker, PVictim, false, AttMultiplerPercent);
                    damageForRound = (uint16)((PAttacker->GetMainWeaponDmg() + battleutils::GetFSTR(PAttacker, PVictim, SLOT_MAIN)) * DamageRatio);

                    // bonus applies to jump only, not high jump
                    if (tier == 1)
                    {
                        float jumpBonus = 1.f + PAttacker->VIT() / 256.f;
                        damageForRound = (uint16)(damageForRound * jumpBonus);
                    }

                    hitTarget = true;
                    realHits++;

                    // incase player has gungnir^^ (or any other damage increases weapons)
                    damageForRound = attackutils::CheckForDamageMultiplier((CCharEntity*)PAttacker, PWeapon, damageForRound, PHYSICAL_ATTACK_TYPE::NORMAL, SLOT_MAIN);

                    totalDamage += damageForRound;
                }
            }
        }


        //check for soul eater
        if (PAttacker->objtype == TYPE_PC)
            totalDamage = battleutils::doSoulEaterEffect((CCharEntity*)PAttacker, totalDamage);

        // bonus jump tp is added even if damage is 0, will not add if jump misses
        if (PAttacker->objtype == TYPE_PC && hitTarget)
        {
            int mod = PAttacker->getMod(Mod::JUMP_TP_BONUS);
            PAttacker->addTP(mod);
        }

        // if damage is 0 then jump missed
        if (totalDamage == 0) {

            // Claim the mob.
            battleutils::ClaimMob(PVictim, PAttacker);
            return 0;
        }


        // high jump removes %50 emnity + more from any gear mods
        if (tier == 2 && PVictim->objtype == TYPE_MOB)
        {
            uint16 enmityReduction = PAttacker->getMod(Mod::HIGH_JUMP_ENMITY_REDUCTION) + 50;

            // DRG sub has only 30% enmity removed instead of 50%.
            if (PAttacker->GetSJob() == JOB_DRG)
            {
                enmityReduction = PAttacker->getMod(Mod::HIGH_JUMP_ENMITY_REDUCTION) + 30;
            }

            // cap it
            if (enmityReduction > 100)
            {
                enmityReduction = 100;
            }
            ((CMobEntity*)PVictim)->PEnmityContainer->LowerEnmityByPercent(PAttacker, (uint8)enmityReduction, nullptr);
        }

        // Under Spirit Surge, High Jump lowers the target's TP proportionately to the amount of damage dealt (TP is reduced by damage * 20)
        if (tier == 2 && PAttacker->StatusEffectContainer->HasStatusEffect(EFFECT_SPIRIT_SURGE))
            PVictim->addTP(-(totalDamage * 20));

        // try skill up (CharEntity only)
        if (PAttacker->objtype == TYPE_PC)
            charutils::TrySkillUP((CCharEntity*)PAttacker, (SKILLTYPE)PWeapon->getSkillType(), PVictim->GetMLevel());

        // jump + high jump doesn't give any tp to victim
        battleutils::TakePhysicalDamage(PAttacker, PVictim, PHYSICAL_ATTACK_TYPE::NORMAL, totalDamage, false, fstrslot, realHits, nullptr, false, true);

        return totalDamage;
    `}`

**Comment by MB213** [comment]
#2457 is another issue with Super Jump / Climb.

**Comment by Shoruto** [comment]
This is a copy paste from FariskaEden's Report

Title - [DRG] Super Jump & Super Climb do not avoid attacks/spells #2457

Details

When a dragoon uses the ability super jump, they should not be able to be attacked by an enemy. Also, if timed correctly, a spell that's about to finish casting on the dragoon that super jumps should be interrupted. These traits should also apply to the dragoon's wyvern when it uses super climb. On Eden currently attacks and spells ignore the traits of these abilities.

https://ffxiclopedia.fandom.com/wiki/Super_Jump?oldid=312133

version 30181205_0

**Comment by Axelution** [comment]
> 
> 
> This is a copy paste from FariskaEden's Report
> 
> Title - [DRG] Super Jump & Super Climb do not avoid attacks/spells #2457
> 
> Details
> 
> When a dragoon uses the ability super jump, they should not be able to be attacked by an enemy. Also, if timed correctly, a spell that's about to finish casting on the dragoon that super jumps should be interrupted. These traits should also apply to the dragoon's wyvern when it uses super climb. On Eden currently attacks and spells ignore the traits of these abilities.
> 
> https://ffxiclopedia.fandom.com/wiki/Super_Jump?oldid=312133
> 
> version 30181205_0

Era behavior avoiding damage using Super Jump:
https://youtu.be/-gBRaa7bk48?t=116

Retail behavior of a spell being cancelled using Super Jump:
https://i.imgur.com/IzoRXN0.mp4

Retail behavior of a TP move being cancelled using Super Jump:
https://i.imgur.com/0iRO4Ir.mp4

**Comment by MB213** [comment]
I've updated this bug report to make it more concise and easier to read. 
I hope it gets some attention as these issues affect Dragoon as a main job and a sub job more than it may seem at a glance. 
Thanks devs for all the work you do.

**Comment by 59blargedy** [comment]
resolved multihits, tp gain, enemy tp gain for jump/high jump July 8, 2022. DA/TA present since player pdif updates.
Note that the vit mod currently does not replicate across multihits as i could find no compelling information that it should, only a mention that it shouldn't. happy to revise if someone can find better information.
remaining issues (super jump is filed on a separate ticket so would be easier to remove) are the enspells/add effects

**Comment by Falaras** [comment]
Just tested Jump/High Jump procing Relic 2.5x damage procs on retail. Using 119 Ragnarok 99 Drk/drg, so even a higher proc rate than 75 level relics. 

Jump:
2007
1533
2072
2059
1518
1509
2052
1529
1556
miss
1531
2090
1550
1532
2027
2081
2030
2055
2080
2102
1554
1524
2096
2059
1555
1537
1560
1529
miss
2070
2052
2049
1528
1568
1553
2077
1553
1532
miss
1563

High Jump:
1099
1099
1108
1416
1483
1112
1106
1084
1428

Didn't see a 2.5x damage relic proc in 50 jumps, pretty sure Jumps shouldn't proc it.

**Comment by 59blargedy** [comment]
i believe all issues have been resolved on this ticket as of september 21, 2022 update. if more issues/unsolved crop up, please start a new report as this one is a doozy, thanks!
