### ISSUE TITLE
Diffusion (BLU Merit Ability) not wearing off

### ISSUE THREAD

**Issue by Satirof** [EdenServer/community#2195]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I unlocked Diffusion last night. When activating it, it allows all self-cast only BLU buffs to be AoE. However after casting a buff, it does not wear off like it is supposed to. As such it is able to be used to put up many BLU buffs at once (cocoon, refueling, feather barrier etc).

1: Use Diffusion
2: Cast buff
3: Cast more buffs
4: Profit

/ver = 30181205_0

**Comment by Jimmayus** [comment]
Just a heads up it's not just buffs, it also makes your healers like Magic Fruit aoe

**Comment by Satirof** [comment]
Adding to this post-diffusion fix...

While duoing today I noticed that Magic Fruit is still causing diffusion not to wear. This is technically correct, as Magic Fruit (and wild carrot) should be be able to be made AoE by Diffusion, however they are still aoeing. As such you can still currently spam mass Magic Fruit AoE's (Curaga 3? 4? spam) without losing diffusion.

Diffusion will wear once you cast a proper enhancing spell (refueling, metallic body etc).

From my understanding (and from wiki + BG), BLU cures should not be affected by diffusion in any way, and should not cause the buff to wear. Only actual support spells should be affected. Such as the list of spells listed https://ffxiclopedia.fandom.com/wiki/Diffusion

Lastly, diffusion'd spells (cures and enhancing) still don't affect Fellows~

Steps:
1: Use Diffusion
2: Cast Magic Fruit
3: Notice diffusion is still active
4: Cast a support spell (e.g. refueling)
5: Notice diffusion drops
