### ISSUE TITLE
Certain EP mobs now aggro that shouldn't. 

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#22]
This was not previously the case. They used to be on the low end of EP where they still wouldn't aggro. Note: Only some of the mantas aggro, not all of them. I'm assuming the ones that spawn at the high end of their level range.

Edit: Some of the goblins aggro now too.

**Comment by godmode** [comment]
Most mobs that are Easy Prey should aggro 75. Can you confirm that this was not the case in retail era or just going off what you experienced at Kupo?

**Comment by Aneyus** [comment]
Breaking down the previous comment, at least the way I understand it.
A given monster's level range is X-Y; if Y is greater than or equal to 61, then EP mobs from that set of monsters can aggro at 75. If Y is less than or equal to 60, EP mobs from that set should not aggro.

**Comment by beauxq** [comment]
I noticed this bug today with anticans in quicksand caves. The anticans have level range up to 59, and are aggressive to 75 when they shouldn't be.

**Comment by beauxq** [comment]
I recommend changing the name of this issue. It's not just one specific type of mob.

**Comment by godmode** [comment]
Please keep us updated / inform us if some mobs are now not aggroing that should.

**Comment by roriffxi** [comment]
I was running through loo and a Flying Manta agro'd me.  The highest level they should be is 59.

**Comment by godmode** [comment]
Hmm I specifically tested level 59 jobs so maybe something didn’t compile right. Will check again

**Comment by beauxq** [comment]
I did find one easy prey that didn't aggro. So not all easy preys are aggroing.
