### ISSUE TITLE
Rampart Overpowered

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#220]
With rampart active, you take 0 damage from any incoming magic

**Comment by godmode** [comment]
Does it wear off like a stoneskin? This sounds like current retail.

**Comment by Treble011** [comment]
I didn't check, you're welcome to come watch us, we're at suzy and I ate flare without shadows, 0 damage

**Comment by Aneyus** [comment]
From Wiki:
Magic Shield tests have shown that the amount of magic damage Rampart absorbs (as a magic analog to Stoneskin) is variable. The currently accepted formula for damage absorbed seems to be VIT*2.


It's almost certainly absorbing more than VIT*2
