### ISSUE TITLE
Trading while synthing causes the crafter to be unable to move.

### ISSUE THREAD

**Issue by AlfWaji** [EdenServer/community#2200]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by AlfWaji** [comment]
sorry for being so vague, but i have had this happen three times in the past two days. 11-14-2019. my character is unable to do anything after completing a trade during a synth. has only happened recently so i only searched recent bug reports.

**Comment by mlandrum22** [comment]
I had this happen with a fisherman. Someone was fishing and I requested a trade (they did not accept) and they were unable to move after.

**Comment by AlfWaji** [comment]
i was lighting crystal desynthing goblin masks in bastok mines  and a stranger offered to trade me. he traded me 2 goblin masks. i was unable to move afterwards. relogging fixed it. just today i was crafting eye drops in bastok mines and i had my alt trade me some more ahriman tears. afterwards i was unable to move. so i relogged and traded again while crafting (just to test) and was unable to move again.

**Comment by Setz0r** [comment]
do not attempt to trade while performing a synth or while fishing.

**Comment by KnowOne134** [comment]
Fixed next update

**Comment by KnowOne134** [comment]
Fix is your not supose to trade while anything of fishing. Your locked in states
