### ISSUE TITLE
Batagreens NPC Sale Price Wrong

### ISSUE THREAD

**Issue by gallanon** [EdenServer/community#2202]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

NPCs offer 0 gil for Batagreens (I think anything sellable is supposed to have a minimum of 1 gil) Wiki lists resale as 12.

**Comment by bkesecker** [comment]
Sale price is out of era (ToAU).  Sometime around February 15, 2015 were they made sellable.  Closing.
