### ISSUE TITLE
Halcyon + Robber Rig = Line snaps at Buburimu

### ISSUE THREAD

**Issue by 3mbrava** [EdenServer/community#2204]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Several different fishing guides recommend fishing Bluetails and Shall Shells at Buburimu, using Halcyon Rod with Robber or Rogue rigs. 

I had two line snaps already losing 30k each. 

http://www.great-blue.jp/?fid=037&lng=en
http://www.great-blue.jp/?fid=039&lng=en

https://classicffxi.fandom.com/wiki/Quick_Skillup_Fishing_1-100_by_Talila

**Comment by 3mbrava** [comment]
Actually this might be an issue with having retail client.

**Comment by 3mbrava** [comment]
Also breaking line with Halcyon and Minnow bait.

**Comment by ShiyoKozuki** [comment]
This is not a bug. What level is your skill? If you're below the cap, you'll get line breaks. Great blue is not a bible(and very inaccurate).
