### ISSUE TITLE
wrong messaging when unable to purchase item with conquest points

### ISSUE THREAD

**Issue by Darkmastervivi** [EdenServer/community#2205]
### Checklist
 

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

I am trying to purchase Royal Knight's Breeches using my conquest points, I am rank 6 and have enough points to buy by like 50K but it tells me my rank is too low. My version of the game is 30181205_0

**Comment by bkesecker** [comment]
Sandy must be 1st place, currently 2nd.  https://ffxiclopedia.fandom.com/wiki/Royal_Knight%27s_Breeches?oldid=368559

**Comment by beauxq** [comment]
It's still a bug if it says the player's rank is too low.

**Comment by Darkmastervivi** [comment]
Cheers guys was just confused as usually items are not shown on the list if
you cant buy them due to nation position. Will wait till were first and buy
them then.

**Comment by bkesecker** [comment]
@beauxq Agreed.  Think I looked at this once before, the code just doesn't take into account the `place` parameter provided in the Lua.  Leave this open please.

**Comment by 59blargedy** [comment]
resolved in may 4, 2023 update
