### ISSUE TITLE
Please remove Holy Shield from Alchemy GP items

### ISSUE THREAD

**Issue by rpcon** [EdenServer/community#2208]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

It requires Mana Barrrrel, which only drops from Sacrificial Goblet (66-68 NM) in Temple of Uggalepih.

**Comment by KnowOne134** [comment]
If it's in era then it would stay

**Comment by bkesecker** [comment]
ToAU era resources seem to indicate the item is correct.
https://ffxiclopedia.fandom.com/wiki/Holy_Shield?oldid=321687
http://ffxi.allakhazam.com/db/item.html?fitem=3013
Closing.
