### ISSUE TITLE
Stuck cannot move

### ISSUE THREAD

**Issue by Myronnis** [EdenServer/community#2211]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0

I have accepted a trade for perpetual Hourglass for Dynamis - San D'Oria while crafting and I am now stuck and can't move at all

Unstuck doesnt seem to work and resetting the game either, says im always crafting but I am not
Warp 2 didnt work either

![Myronnis_2019 11 19_193655](https://user-images.githubusercontent.com/18298758/69198908-4db98500-0b04-11ea-91c8-b3fe3d45e252.png)

**Comment by Myronnis** [comment]
fixed itself after 20 mins of !unstuck but need to investigate why it happened

**Comment by KnowOne134** [comment]
Its todo with locking your char in states to not do hinky stuff while trading or crafting. Resolve by crashing client
