### ISSUE TITLE
PLD Greatsword skill cap bug

### ISSUE THREAD

**Issue by Dallanolar** [EdenServer/community#2212]
What I was doing:
Leveling PLD at a lower with with WAR attached as my SJ. 7 PLD / 3 WAR
Playing version: 30181205 0

What happened:
My greatsword skill capped at skill-level 12

What I expected to happen
My greatsword skill to have capped at skill-level 22.

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Dallanolar** [comment]
Unequipping and requipping the weapon solved the sillver.

**Comment by Leonira** [comment]
This same bug was on Nasomi as well and after much testing to try and figure out when and why it happens, I believe I figured it out. 
It is related to fighting mobs that are much weaker than you are.
If you hit the cap "for that mob" (i.e. as high skill as that mob can give you), your skill caps out even if you could technically go higher at your level.

This is also why it happens frequently in the lower levels when you're running around murdering EP mobs.

Like you mentioned, reequipping your weapon resolves the issue, but it's still a very annoying bug that will hopefully get fixed. :)
