### ISSUE TITLE
1,000 needles (1000 needles) damage from Sabotender only added to 500

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2215]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Unfortunately I forgot to save the screenshot I took of this before restarting computer, but earlier today in a 40ish sync SMN burn party in Eastern Altepa Desert a Sabotender used 1,000 needles and each of the 5 pets that were in melee took 100 damage. No one else was near, and no one else was damaged, affected, or targeted in any way by the move. There were 6 of us in the party, one person was just in the process of resummoning when it happened. It seemed like each pet should have taken 200 damage.

**Comment by mlandrum22** [comment]
Avatars have 50% physical damage reduction.

**Comment by E5una** [comment]
Huh, okay thanks! I guess none of the SMN in the party knew that. I guess I’ll close the ticket
