### ISSUE TITLE
ENM Sheep in Antlion's Clothing Tuchulcha will spawn at same location as a Hunter.

### ISSUE THREAD

**Issue by danismyhero** [EdenServer/community#2217]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
30181205_0
Reproduced two runs in a row, separate spawn positions.

Tuchulcha will spawn at the same location as one of the Hunters for the final 25% (not confirmed if it is *only* the final 25%, but can confirm has happened twice at this point so far).

This does not happen in retail, Tuchulcha will spawn at a separate location from the Hunters, and makes the ENM very difficult to impossible for low man to win.

![image](https://user-images.githubusercontent.com/49649778/69397847-5bf6d500-0cad-11ea-800a-5c49632f17ad.png)

**Comment by montijin** [comment]
There is also an issue where sometimes the Tuchulcha will instantly ambush again after it goes down from being pushed past a threshold.

**Comment by KnowOne134** [comment]
resolved in October 4, 2021 update
