### ISSUE TITLE
Mog Wardrobe 2 not accessible after Bastok Rank 6 obtained

### ISSUE THREAD

**Issue by Chiandra** [EdenServer/community#2219]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Mog wardrobe 2 cannot be accessed after completing Bastok Rank 6 mission on Chiandra. Ver. 30181205_0.
Submitting ticket as stated by previous issue posts.

**Comment by godmode** [comment]
The comment probably wasn’t very clear. Please submit a GM ticket on the in game help desk menu.
