### ISSUE TITLE
Orpiment chunks.

### ISSUE THREAD

**Issue by chlorr** [EdenServer/community#222]
Orpiment chunks in Ifrit Cauldron are dropping way too commonly, about 2.5 stacks of picks in, 4 DSteel, 3 Ada, 3 Ori and now 12 Orpiment. They are supposed to be Very Rare as they are for Relic +1 mats. I've heard from Wiggo DSP recently broke it. 

Do i drop them/some? or stop mining here for now?

Never mined on retail, only kupo which didn't include Orpiment. not sure how common its supposed to be, sorry!

**Comment by godmode** [comment]
Please stop mining there for now we will try to fix it tonight or tomorrow. Thanks for being honest.
