### ISSUE TITLE
Absorb-tp should be limited to 50% of the mobs tp

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#2221]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
There originally was no cap on it but sometime in 2007 it was changed to 50% of the mobs tp.
I cant find the exact patch notes, but they're referenced in this thread.  (It was later nerfed even more to even less 50%, but those changes are out of era)
https://www.bluegartr.com/threads/44736-Absorb-TP-quot-Absorb-quot

It doesn't appear to have this 50% limit on eden.

**Comment by montijin** [comment]
The resistance rates for absorb-tp on high level NMs and the amounts you can absorb are still an issue.

**Comment by godmode** [comment]
May be worth for someone to open a new issue if they get time for this. Since it doesn’t really fall in line with this ticket other than the spell but it is a problem.
