### ISSUE TITLE
Amaltheia behavior 

### ISSUE THREAD

**Issue by Cheese-Sandwich** [EdenServer/community#2224]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

- 4 kills. Everytime Amaltheia was popped she immediately started summoning the sheeps. I believe this ability should be random through the fight and not immediately started at the beginning.

-Once the Tavnazian Sheep arrived. They did not link or agro to anyone engaged to Amaltheia. Instead they all stood still and watched a fellow ram die. The Rams however linked just fine.

-Used T3/4 Elemental -ga instead of any holy magic (Holy, Cure V, Banish IV, Banishga III) Additionally, these elemental spells were very weak and hardly did any damage.

-Highly susceptible to Rolling Thunder.

**Comment by Cheese-Sandwich** [comment]
https://ffxiclopedia.fandom.com/wiki/Amaltheia

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
