### ISSUE TITLE
SMN/PUP can't use any maneuvers with puppet pet out

### ISSUE THREAD

**Issue by Raizuo** [EdenServer/community#2225]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181505_0
No similar topics found through search.

As a 1SMN/1PUP with the puppet pet out, I cannot activate any maneuvers rendering the puppet somewhat useless. Tried as lv2 2SMN/1PUP, still can't use any maneuvers. Upon attempting to use any maneuvers, I would get "Raizou cannot perform that action."

**Comment by KnowOne134** [comment]
You have to use an animator. Which is pup only so not equipable. Best you can do is have it follow you around. Making /pup a useless job

**Comment by KnowOne134** [comment]
I see no issues and working as intended

**Comment by Volkaru** [comment]
Regular lvl1 animator can be equipped by all jobs, so you cna use maneuvers when subbed.

**Comment by Raizuo** [comment]
I ended up forgetting to equip the animator. Everything is working as intended and I apologize for wasting everyone's time.
