### ISSUE TITLE
Empathy [DRG merit] does not work

### ISSUE THREAD

**Issue by tdburley** [EdenServer/community#2226]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
No buffs are being copied to the Wyvern when Spirit Link is used despite two points in Empathy. It does allow the player to use Spirit Link while the Wyvern is at max HP however (there is just zero benefit to doing so).

Individually tested with Protect II, Regen, Blink, Enspells, and Stoneskin buffs in Wajaom Woodlands as a 75DRG/37RDM Galka. 

No similar issues found.
Version 30181205_0

**Comment by tdburley** [comment]
Bump - After further testing, this appears to be more broken than I initially suspected and simply does not work at all. Edited title and text to reflect this. Aspiring DRGs beware!

**Comment by Caelic** [comment]
https://github.com/DarkstarProject/darkstar/pull/6326
merry christmas DRG brother

**Comment by tdburley** [comment]
> [DarkstarProject/darkstar#6326](https://github.com/DarkstarProject/darkstar/pull/6326)
> merry christmas DRG brother

I really needed good news today. Thank you :)

**Comment by KnowOne134** [comment]
I can look I to porting this once dsp says it's good enough for them. Then I can comb through it
