### ISSUE TITLE
SMN Job Quest Fire weather in Altepa gave Orange Light not Red Light. 

### ISSUE THREAD

**Issue by Fng098** [EdenServer/community#2227]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
Previously obtained orange @ North Gustaberg.  Now Fire Weather wont trigger a new "Red" cut scene.  Can not finish quest.

**Comment by Fng098** [comment]
quest did finish without final cut scene.

**Comment by Fng098** [comment]
![Fng_2019 11 27_060403](https://user-images.githubusercontent.com/57783175/69720237-281e1400-10e0-11ea-9170-9b14005ad24c.png)

**Comment by Mozzy4Ever** [comment]
Sounds like a /ver issue which you said you included in the details, but did not.
