### ISSUE TITLE
Treasure Coffer

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#223]
Charcter: Chan 50SMN

Picked a Treasure Coffer in Toraimarai Canal earlier while weakened.

Got the error msg: Cannot pick coffers while weakened. Plus a mimic spawned and killed me, plus my key was gone :D

Doubt this is supposed to happen.

**Comment by Aneyus** [comment]
You're not supposed to be able to open coffers while weakened, I think this is correct

**Comment by godmode** [comment]
Also if you fail sometimes you will pop a mimic and your tool will be gone. I'm not sure if the two are supposed to happen together though.

**Comment by panfunk** [comment]
> Also if you fail sometimes you will pop a mimic and your tool will be gone. I'm not sure if the two are supposed to happen together though.

This is the issue, I'm not entirely sure but I suppose in that situation, just the msg: unable to pick while weakened" should habe poped up, keeping the key and no mimic spawning

**Comment by Serephim** [comment]
Yeah mimic's should only spawn if you use a skeleton key or living key as THF.
Coffer Key's are 100% success.
Not sure about the whole weakened thing as I have never tried to open a coffer weakened before.

**Comment by Mozzy4Ever** [comment]
According to https://ffxiclopedia.fandom.com/wiki/Picking_your_Coffers_and_Chests, the error should pop up and you shouldn't open the coffer. It does, however, take your tool you used to pick the coffer. A mimic should not have a chance of spawning in this case.

As for OP's issue, yea... He used a coffer key so he shouldn't have been weakened and a mimic shouldn't have appeared (neither can happen with coffer key, only with thf tools)

**Comment by godmode** [comment]
Are you sure he had coffer key? He said he “picked it” so I was imagining he used a skeleton key

**Comment by panfunk** [comment]
So, I had the coffer key, and I was weakened before and while I tried to open it, as stated I was on SMN50 to get my AF gear.
When I tried to open it with the coffer key, the error msg + mimic + key gone happened.

**Comment by jmcmorris** [comment]
According to this page, https://ffxiclopedia.fandom.com/wiki/Treasure_Coffer, you cannot open coffers while weakened. @godmode has a fix in place for this.
