### ISSUE TITLE
Tiamat draw-in and spike flail not working

### ISSUE THREAD

**Issue by him911** [EdenServer/community#2233]
### Checklist

- [yes] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Tiamats draw-in ability doesn't exist right now and he doesnt seem to spike flail even if we try to force it.

**Comment by perkuprightmeow** [comment]
It definitely does exist, just is weird about when it activates / don't really have a reliable set up FOR it activating. 

He also spike flailed me yesterday when I raised behind him, but he wasn't actively engaged.

**Comment by roriffxi** [comment]
Tiamats draw-in only seems to work when she is in flight mode on Eden.

**Comment by Tjonke** [comment]
I was drawn in as I was running towards her before pull. So she definetly uses it even on ground.

**Comment by Volkaru** [comment]
Mobs on eden don't have weighted TP moves. So being behind it with hate on here doesn't gaurantee it'll use spike flail. It just opens up the possibility for it to use it.

**Comment by godmode** [comment]
Not totally true—but mostly true. I added support for this so it’s easy to added weighted moves to mobs. Only a handful of mobs use them right now.

**Comment by 59blargedy** [comment]
tested, can't replicate issues, mob draws in and spike flails for me. drawin is tether based vs individual from personal testing.
