### ISSUE TITLE
"It's Raining Mannequins" quest missing

### ISSUE THREAD

**Issue by Leonira** [EdenServer/community#2235]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Version: 30181205_0

Steps to reproduce: Try to trigger the questline at the NPC Fyi Chalmwoh.

The quest "It's Raining Mannequins", and presumably its followup quests "Behind the smile" and "Knocking on Forbidden Doors" Are missing. Fyi Chalmwoh doesn't even have dialogue.

Would be lovely if these quests were added sometime soon so we can get some mannequins, and mannequin pumps. :)

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update via lsb work
