### ISSUE TITLE
Carbuncle should have auto regen

### ISSUE THREAD

**Issue by Kurtalicious** [EdenServer/community#2236]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

I noticed while soloing that carbuncle does not have his auto regen trait.  He gains this at level 25.  I found a summoner guide and ffxihaven.org supporting my claim.  The guide was last updated on 07/25/06 and ffxihaven.org has a copyright date on it from 2004-2005, which would make it era accurate.  

A number of links and quotes below.

"Carbuncle: Auto Regen (no MP) this is not listed anywhere but it seems if you 
watch Carbuncle's HP bar closely, he regens a little HP every 3 seconds."

https://gamefaqs.gamespot.com/pc/555735-final-fantasy-xi/faqs/26383

http://www.ffxihaven.ffshrine.org/ffxi-summoner-avatars-carbuncle.php

Here is one more source dated January 2007 that claims auto regen at level 25.

https://ffxi.gamerescape.com/wiki/Talk:Carbuncle_Mitts

This guide claims the auto-regen is 1hp/tick.

https://www.bluegartr.com/threads/120221-Avatar-HP-and-MDB

**Comment by godmode** [comment]
It could be that they have some form of jobs. And one of the things they receive are job passives. Like Carby would be WHM. It would be interesting if someone on retail could determine if Ifrit gets Double Attack to prove this theory.

**Comment by Kurtalicious** [comment]
Outside of carby having auto-regen I'm not aware of avatar's having passive job traits.  When Avatar's Favor was introduced all the Avatars got a special bonus while it was active and Ifrit's was double attack.   Elemental siphon and Avatar's Favor made smn quite enjoyable and they seemed to be well thought out.  I'm all for adding job traits/abilities and spells that were part of the level 75 era.  Let's do it! ^^ :-) 

P.S. please no fields of valor >.>
