### ISSUE TITLE
Rampart and Warcry have no enmity attached to them

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2238]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Rampart (PLD) and Warcry (WAR) were promised to be fixed in "next patch on July15 by Godmode" and still broken. Rampart's shield value is also way out of wack, doesn't even stop stone from Goblin's in West Ronfaure. These 2 abilities are major enmity generators and defensive cooldowns for PLDs and is causing PLD to be a lesser tank than they are supposed to be,

**Comment by slassen** [comment]
It looks like the bulk of it was fixed and support to enable it was as well but there was a condition that was missed. Should be good to go now once the code is merged in.
