### ISSUE TITLE
Sheep in Antlion's Clothing: Tuchulcha occupying same spot as another antlion

### ISSUE THREAD

**Issue by piercingdark** [EdenServer/community#2241]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0

We wiped in Sheep in Antlion's Clothing ENM this morning. We got Tuchulcha to 75% initially, then when we went to find him after he burrowed, he spawned at the same exact point as another antlion. They both came up and did Pit Ambush for 500+ each (almost 1100 dmg combined). Chat log showed it happened at the same time. On my screen they were physically in the same place momentarily (bodies and names overlapping) before moving so they were standing side by side. 

Interestingly, I went to HP after dying and it brought my dead body to Port Windurst where I was able to be raised.

**Comment by roriffxi** [comment]
https://github.com/EdenServer/community/issues/2217

This has already been reported here.

**Comment by Shoruto** [comment]
Closing due to duplication as mentioned above.
