### ISSUE TITLE
Mog Tablet related text at Windy Gate Guard

### ISSUE THREAD

**Issue by Rocketshuttle** [EdenServer/community#2242]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
When speaking to the Port Windurst Gate Guard "Milma-Hapilma, W.W." and turning in outpost supplies from an unfinished outpost quest (to the Li'Telor Region), the following text appeared:

[17:57:16] Milma-Hapilma, W.W. : We will dispose of those unusable supplies.
[17:57:16] Greetings adventurer! I'm so glad you've come, kupo!
To celebrate the safe recovery of all eleven of King Kupofried's mog tablets, we're offering a limited-time teleportation service for the low, low price of 85 gil! What do you say?

At this point the conversation with the guard was terminated by the client and no further options were given.
version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
