### ISSUE TITLE
Barspell Duration is too long

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#2246]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently on Eden, bar spells last ~7 minutes or longer.

Retail was much, much less. I was casting it nearly every Haste rotation on bigger fights (Tiamat,Cerberus).

References: 

https://ffxiclopedia.fandom.com/wiki/Barstonra?oldid=646347  - shows a possible formula from Aug30 2008

https://ffxiclopedia.fandom.com/wiki/Bar_Elemental?oldid=1183715 - Shows possible formula from Aug 2010.

Obviously neither are from 2007 or earlier; but SE wouldn't have lowered the duration in that time - they would have increased if anything. 

The amount of the resistance increase A and the effect duration in seconds D are related to Enhancing Magic Skill E as follows:

A=40+0.2E

D= { 150   if E <180
        150 + 0.8(E-180) if E>180 }

The maximum amount of elemental resistance gained from Enhancing Magic skill is capped at 100 (obtained at 300 Enhancing Skill).

**Comment by ShiyoKozuki** [comment]
Can confirm it's far, far, far too long.

**Comment by Caelic** [comment]
should be an easy simple fix.
`dsp/scripts/globals/spells/barspell.lua`
change the "calculateBarspellDuration" function to be
`function calculateBarspellDuration(caster,enhanceSkill)
    if enhanceSkill < 182 then
        return 150
    else
        return 150 + math.floor(0.8*(enhanceSkill-180))
    end
end`

**Comment by Caelic** [comment]
should be an easy simple fix. in:

dsp/scripts/globals/spells/barspell.lua

change the "calculateBarspellDuration" function to be
```lua
function calculateBarspellDuration(caster,enhanceSkill)
    if enhanceSkill < 182 then
        return 150
    else
        return 150 + math.floor(0.8*(enhanceSkill-180))
    end
end
