### ISSUE TITLE
Republic Circlet's Magic Attack Bonus not active in Dynamis - Xarcabard

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#2248]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Multiples Thunder IVs used on a consistent level 80 monster (Black Ahrimans) with the same exact set of gear, food, etc. Damage with Circlet and without Circlet were the same, indicating that the +5 MAB is not active in Dynamis - Xarcabard. Not sure if this is true for other Dynamis zones, but I will try to test this in the future as well. Obviously this takes time and is entirely up to my linkshell's schedule.

Taken from FFXIclopedia, as well as my personal experience in era playing BLM in Dynamis:

> Items with the effect of +stat 'In areas under own nation's control" will only take effect when, during conquest, the nation you currently are allied to is in control of the region you are in. This effect will take place in all zones within a region.

> **Furthermore, these benefits will still activate in certain areas that are not subject to conquest**, regardless of which nation actually controls the area (if any). Examples of such areas are anywhere in the cities of San d'Oria, Bastok, Windurst, and Jeuno, **Dynamis**, and the Lumoria region (Sea). Benefits are not active in Promyvion. The benefits will never be active anywhere in the Aht Urhgan or Wings of the Goddess areas.

Also, while I'm making this post I would like to also note that these types of items ("In areas under own nation's control"/"In areas outside own nation's control") should also function in Sea once that is out.

**Comment by VirtuosusFFXI** [comment]
Update: Republic Circlet also does not function in Dynamis - San d'Oria. Will continue to update with the rest of the zones as I am able to test it.

**Comment by KnowOne134** [comment]
Did retail testing and only the latent outside own nations control work in dynamis and sea. The wiki is somewhat confusing on the mater here
