### ISSUE TITLE
Net and Lure

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#2249]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I tried to purchase Net and Lure from the Fishing Guild. 
I never received the item and lost 50k GP.
This happened a couple of days ago
After some research I see that the item isn't era, so that
explains why I didn't get the item, but shouldn't have lost the GP.

I tried calling a GM to get the GP back, but haven't gotten any answers from my tickets.

**Comment by Balrahn** [comment]
Ver 30191004_0

**Comment by Setz0r** [comment]
the system will not take your GP if you do not receive the item.  it's pretty basic code with little to no room for error.  are you certain you lost the GP?

**Comment by Balrahn** [comment]
very certain

**Comment by Balrahn** [comment]
I had 50k+ points, and I were unable to buy a fishermans belt after. Had to turn in more fish to reach 10k.

**Comment by Setz0r** [comment]
what specific date/time did you spend the points, we will need to review backups to verify the points were there / spent.

**Comment by Balrahn** [comment]
I didn't write down the time sadly :( 
Can you see the GM tickets I've called in? I called one in shortly after it happened.

**Comment by Setz0r** [comment]
Not able to reproduce
