### ISSUE TITLE
Rng damage on gods

### ISSUE THREAD

**Issue by RoninXI** [EdenServer/community#225]
When we were doing Seiryu/Genbu/Byakko yesterday normal ranged attacks were doing between 35-42. And Arching arrow between 202-230 with a Brd using Prelude and Minuet. I'm wondering if the formula is not taking into account the dmg from the bow? Anyways in comparison melee were hitting for I seen a 400-900 Tachi: Gekko. Rng is grossly underpowered atm in any case. It makes Rng a worthless class to level.

**Comment by Serephim** [comment]
Yeah it seems Ranger got hit with a bad shadow nerf or something. They are not even competitive DPS anymore and you are throwing money away too. lol

**Comment by gweivyth** [comment]
Can you guys try and get me some more info?  Parses, etc?

I don't think this was intentional, and when I was playing RNG before the DSP update it felt just as strong as it was on Kupo.  I don't know of anything else that has changed between now and then.

**Comment by Serephim** [comment]
I don't have any screen shots of parses but I will try to collects some next time.
Let's just say that against Suzy I did 1180 damage the entire fight and a BLM did 4800.
RNG's accuracy is garbage now. I had double Prelude on, 78 RACC and using Pot-au-feu's and I couldn't hit Suzy worth shit. Pretty much the same deal with Seiryu and Genbu. Did the same damage per hit on each of them. Did slightly more damage per hit on Byakko though, damage was from 48-62 per hit.

**Comment by godmode** [comment]
Is there any era retail data you can provide for how much normal hits should be doing and accuracy?
