### ISSUE TITLE
Missing Horn Flies in Crawler's Nest

### ISSUE THREAD

**Issue by ceramsey** [EdenServer/community#2250]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

While running through crawler's nest on the way to map 3 at J-10 all the spawn points for Horn Flies are missing in the hallway after the recent update. 

version: 30181205_0

**Comment by ceramsey** [comment]
Also there are missing exoray from the hallway that ends with a bomb and crawler.

**Comment by godmode** [comment]
Iirc they were never in this location in era. They were moved here from the open basement area because higher level mobs took over.

**Comment by KnowOne134** [comment]
so if this is the case to be correct in era, this issue can be closed?
