### ISSUE TITLE
Unable to remove Wivre Ring from Delivery Box

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#2251]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

-When attempting to remove Wivre Ring from delivery box, system gives message "You can only hold one item of that type." 
-The item is not rare. 
-It is also no longer in the outbox of the sender, and therefore delivery cannot be canceled.
-There are two rings.

Sender: Astraea
Receiver: Larry

Thanks for your time!

![unknown](https://user-images.githubusercontent.com/37199798/70088699-0804be00-15d4-11ea-93d2-691807746575.png)

**Comment by KnowOne134** [comment]
This is a gm issue. And a larger problem with all items that can be setup as the same via universal ids
