### ISSUE TITLE
/lastsynth causing critical failure, destroying crystals and materials

### ISSUE THREAD

**Issue by tengokujin** [EdenServer/community#2253]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Ver: 30181205_0

Went to get advanced synthesis support, started crafting iron ingots.
First synth is as normal, from the item window.
Second synth is with /lastsynth; it immediately shows "success" animation and sound, returns, "Synthesis interrupted. You lost the crystal and materials you were using."
Third synth is with /lastsynth again; it proceeds as normal.
Fourth synth is with /lastsynth and fails like the second synth.

Further /lastsynth testing is aborted because I'd just spent an hour mining materials, I'm not losing them pointlessly.

![Tengokujin_2019 12 03_234539](https://user-images.githubusercontent.com/55920387/70113607-bd149600-1627-11ea-8c21-d98621178a70.png)

**Comment by godmode** [comment]
It looks like you may be using a FPS addon to craft faster than allowed. If so the game will technically allow you to synth faster but you will lose your materials.

**Comment by tengokujin** [comment]
Is there no way for crafting to ignore the fps addon? I don't have any intention nor desire to craft faster and it's an irritation to disable and re-enable the addon anytime I need to do more than one of the same synth.

**Comment by Raphtalia1** [comment]
If the addon is loaded there is no way for any part of your client to ignore it, including crafting, if you are in FPS 2 (the default) you should see no issues with crafting, if you use FPS 1 or .1 you will lose materials. 

Sorry for the inconvenience but this is a required function to keep people from abusing client side cheats
