### ISSUE TITLE
Culinarians' Guild Point Item Error

### ISSUE THREAD

**Issue by ArsinoeX** [EdenServer/community#2254]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Client Version: 30181205_0

Experiencing an issue with the Culinarians' Guild NPC not accepting the appropriate item (Bowl of Puls) for guild points. (12/04/2019)

I attempted to test the issue with a few steps:
- Tried trading 1 item and multiple items on separate occasions
- Waited til next in-game day
- Zoned twice

**Comment by bkesecker** [comment]
Code doesn't reveal anything that would indicate there is a problem with the NQ or HQ version of Puls being accepted by the guild.  What rank were you?  What were you doing prior?  Any other surrounding details you can provide?

**Comment by KnowOne134** [comment]
I'm assuming rank up or guild change blocking trade until next real day. Closing issue can reopen if anyone else experiencing it with more detail
