### ISSUE TITLE
Charybdis placeholders incorrect

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2256]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details
Per:
https://ffxiclopedia.fandom.com/wiki/Charybdis?diff=374854&oldid=342603

Charybdis is supposed to effectively have 1 placeholder. It will either spawn far inside the room, or outside the room. Per https://github.com/DarkstarProject/darkstar/blob/fc1fcef9eb5093cc4cd5738c2da9154ec9b4be6a/scripts/zones/Sea_Serpent_Grotto/IDs.lua , it has the two placeholders setup properly. Currently, they can both be up at the same time. I figure adding a random 1,2 and having one npcid spawn if roll = 1 while 2 gets set to disallow and vice versa, would do the trick ( not the most effective use of resources though I imagine)

**Comment by E5una** [comment]
Relating this to https://github.com/EdenServer/community/issues/3082 by mentioning it here, not sure if there are actual relationships you can make between tickets.

**Comment by 59blargedy** [comment]
resolved by another dev in may 3, 2023 update (patch notes need updating
