### ISSUE TITLE
Sanction Refresh may be using base MP only for 75% threshold

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#2257]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

1. Change job to 75 WAR / 37 SAM
2. No MP merits - base MP is 0
3. Obtain sanction, choosing refresh effect
4. Enter a TOAU zone, i.e. Bhaflau Thickets - or maybe it works in Whitegate? Not sure
5. Equip MP+ item, i.e., Walahra Turban will give 30 MP total for the warrior
6. Observe no refresh effect

Perhaps sanction refresh is using base MP for the below 75% MP threshold, rather than total MP? With the above config the warrior should have a +1 mp/tick refresh effect up to 22 or 23 MP depending on rounding.

Thanks for your time!

**Comment by icariumkupo** [comment]
Linking #1897

**Comment by rockemsockemman** [comment]
I observe the same issue, BST/WHM w/ sanction refresh I receive the +1MP/tick. Change to BST/NIN and I do not receive any refresh effect no matter how much mp gear I equip.

Definitely appears to only be using base MP and not total MP.

Any % of 0 is 0, so the effect does nothing.

Should be including the total MP+ bonuses in the check but ignoring converts hp to mp gear and mp%+ gear.

**Comment by greyenvy** [comment]
Presently Sanction refresh is ticking my COR/WHM back up to 100% MP.  It does NOT stock ticking at 75% of natural MP as it should.  
<https://ffxiclopedia.fandom.com/wiki/Sanction>

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
