### ISSUE TITLE
Meteorite damage formula changed

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#2260]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Meteorites damage formula changed and is doing much more damage on the top end than it should be.  I noticed it after mondays patch but we had other buffs happening that would have increased damage so I didn't think as much of it.  But after some testing without those buffs the damage is still too high.

**Comment by Tjonke** [comment]
You've known this for 10+ months and been abusing it for Khimaira the whole time, and as soon as we see you use it you report? No double moral there at all...

**Comment by roriffxi** [comment]
Not really sure what you're on about.  2 weeks ago meteorite topped out short of 600 dmg unless you had a COR buffing you or some really major INT debuffs.

Now its damage is doing upwards of 800 with no buffs.

This is a completely different change from what has been going on in the past.

**Comment by Jimmayus** [comment]
I dunno about that, carbuncle has been used on hnms for months from Fafnir to cerberus precisely because it's damage values have been arbitrarily higher aside from the lack of resistance (read: unnaturally high magic accuracy for summons generally).

**Comment by Jimmayus** [comment]
Case in point: another example of this in action is the widespread usage of leviathan's slowga to bypass slow resistance monsters (apparently) had in retail. I was even able to consistently land lunar cry on Jormungand.

**Comment by roriffxi** [comment]
The last time meteorites damage formula was purposely worked on, it brought its 0 tp damage to somewhere just shy of 600 on most enemies.  The dev who worked on it ensured the formula was correct, even though it had been pointed out that still seemed a bit high.  It's entirely possible the difference causing the damage to be above 500 rather than below 500 is the result of mobs having less INT than they should.

Either way, that formula changed with the most recent patch but the notes don't make it sound like it was an intentional change.  Which is why I submitted this bug report.

**Comment by Jimmayus** [comment]
Is there proof your statement? There's a big difference between core damage calculation and "the way magic resistance is applied". Using the calculation Damage = (500 + dINT*1.5 + TP÷2) × Day/Weather Bonus × MAB ÷ MDB you would need a massive dINT or proof of low magic defense across the board. It's not like this meteorite usage specific to one monster, it's prevalent even in tp parties.

**Comment by Setz0r** [comment]
I fixed meteorite to match known formulas, the problem is the resistance is some made up stuff because there's no alternative at the moment, end of story.

**Comment by Jimmayus** [comment]
What about the uncanny accuracy of ward debuffs in general? Leviathan's slowga was not used in by contemporary players to bypass coming /blm just because era players were ignorant, the actual stats of the avatars are at issue here as well.

**Comment by godmode** [comment]
This is not a place for drama. I have 0 tolerance for drama on here. Knock it off or take it to tells.

Meteorite’s resistance was changed to actually have non-garbage resistance recently so this is probably a new issue.

**Comment by Jimmayus** [comment]
For reference
![img_20191218_232928](https://user-images.githubusercontent.com/45926115/71148591-aa868900-21f1-11ea-9aa8-b7565447d693.png)
![img_20191218_232941](https://user-images.githubusercontent.com/45926115/71148592-aa868900-21f1-11ea-8cb2-56c523f52cba.png)

These are from retail testing. I plan to use meteorite for derive monster INT (You can obtain raw mdb stat using a different blood pact and, once you know that, the only damage variable in meteorite is dINT). Wild Rabbits are level 1 and have 6 INT according to various sources including encyclopedia and helix testing (https://www.ffxiah.com/forum/topic/47208/helix-ii-base-damage/ ). Using the damage calculation:  Damage = (500 + dINT*1.5 + TP÷2) × Day/Weather Bonus × MAB ÷ MDB for meteorite and solving for netural day, neutral mab / mdb and tp we get 500 + (dINT)*1.5 as final damage. From there, with our knowledge that wild rabbits have 6 INT we can see Carbuncle's INT at 75 is 54. 

I don't have screenshots but I can personally attest to seeing meteorites in excess of 1k damage to Cerberus today, and should I get the chance to see people using meteorite on HNMs I will take screenshots. I'm just indicating here that even in the most favorable dINT situation for a 75 carbuncle you're not even hitting 600 damage before resistances.

**Comment by Jimmayus** [comment]
See also 
![Porobururu_2019 12 19_014357](https://user-images.githubusercontent.com/45926115/71151428-4b2c7700-21f9-11ea-8153-80855ee34c57.png) 

From Eden today

**Comment by Jimmayus** [comment]
See also from Eden live: 
![unknown](https://user-images.githubusercontent.com/45926115/71151804-461bf780-21fa-11ea-92b1-e8303a6a282d.png)

**Comment by Jimmayus** [comment]
For further reference and to demonstrate there is at least some dINT calculation happening (so maybe wrong V value) please see this video of meteorite damage on Khimaira: https://youtu.be/_wJE_TnDCtk . Looks to me like meteorite hits for either 829 cap or 851? from one summoner, I'm not sure why, on what is presumably a monster with higher INT than a wild rabbit.

**Comment by Jimmayus** [comment]
https://youtu.be/yod3ftOlroU for a live retail video demonstrating that meteorite is probably ignoring damage reduction types (mdt -% and light-specific reductions)

**Comment by Jimmayus** [comment]
https://youtu.be/DWfXGacN7JM another video from a Cerberus kill on Eden. 1018 meteorite damage is the highest recorded damage. I believe either the calculation for meteorite is still incorrect, or Carbuncle's base INT and mab (which should be 54 and +0 respectively) are very off. I'm not sure what else it could be.

**Comment by Jimmayus** [comment]
Responding to myself for the purposes of comparison, here is a retail testing of Cerberus and meteorite: 
https://youtu.be/DjO27kDhEBA . As you can see, meteorite should cap out at something close to 1/4 of the damage it does on Eden retail. I am willing to bet that this damage is a confluence of two things: HNM stats are not correct, and Carbuncle stats are not correct. It's possible the meteorite bloodpact damage calculation is technically appropriate but still drawing from these poisoned derived stat sources.

**Comment by ShiyoKozuki** [comment]
It also seems to be ignoring monster MDT. Taken as naked 75smn/37 WHM. 
Neutral MDT(+- 0%+ monster:
![Shiyo_2019 12 28_164314](https://user-images.githubusercontent.com/58101246/71549794-85cca700-2991-11ea-8dbd-39ba0460fac8.png)

+MDT monster. Lower numbers because much higher level monster and the formula uses dint, but you can see the +MDT isn't functioning at all still.
![Shiyo_2019 12 28_164759](https://user-images.githubusercontent.com/58101246/71549813-d47a4100-2991-11ea-8671-cd2e2eef1016.png)
