### ISSUE TITLE
Upyri spams TP move's

### ISSUE THREAD

**Issue by alioh7** [EdenServer/community#2261]
![upyri ](https://user-images.githubusercontent.com/55878362/70372690-7c50a180-18f3-11ea-8f00-cfa077916555.jpg)
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

so i was camping this NM for 2 days now and everytime i fought him day or night time he just spams TP move's without stop, i know he has a high regain at night but not like this.

**Comment by 59blargedy** [comment]
resolved in june/july
