### ISSUE TITLE
Linkpearl unequips on job change

### ISSUE THREAD

**Issue by Caelic** [EdenServer/community#2265]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

version 30190305_0

STEPS:

1) Receive a linkpearl to a LS you haven't been in before
2) Equip the pearl on your character
3) Change jobs
4) The pearl should now be unequipped and you must re-equip it on every single job before it's saved in your job equipment sets

### Details

related to the update that caused equipment to be saved to your job when you change jobs. in the code you guys did for this it's an easy fix just exclude equip slot IDs 16 and 17 as those are LS1 and LS2 slots for the job change equipment function
![Image](https://i.imgur.com/v8q70qV.jpg)

**Comment by KnowOne134** [comment]
this is no longer an issue
