### ISSUE TITLE
"Tea with a Tonberry?" Quest Fails to Start.

### ISSUE THREAD

**Issue by Reataru** [EdenServer/community#2269]
### Checklist

- [/ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ /] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/ ] I have provided my client version in the details. (type /ver into your game window)

[Version 30181205_0]

Finished previous quest "Signed in Blood" easily enough, but when I tried to activate next quest, Sobane (Quest NPC) ignores me after I click on her.  

- I have zoned out/back in [Wiki did mention to do that, did multiple times after failure]
- Waited game day. [Not mentioned in wiki but figured I'd try anyways]
- Confirmed I had adequate San d'Oria fame. [Wiki has it at 4, I am currently at 9]
- I have not seen the reward item [Willpower Torque] on Auction House transaction history.

I have went and required items, so I imagine that the quest is available, but perhaps just not workin' for me? [Ingame name is Altana]

[Wikipedia Quest Page](https://ffxiclopedia.fandom.com/wiki/Tea_with_a_Tonberry%3F)

**Comment by bkesecker** [comment]
Not implemented on DarkStarProject list https://wiki.dspt.info/index.php/Quests so probably not yet implement on Eden.

**Comment by Reataru** [comment]
Thanks for the quick response.  /bow
