### ISSUE TITLE
Quick Draw Damage verification

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2270]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Corsair:_Guide_by_Yemaya?diff=377847&oldid=377845#Quick_Draw

![image](https://user-images.githubusercontent.com/11255886/70688147-9e8d4b00-1c76-11ea-9907-9a62d839fac9.png)

And yet I pulled this data from a recent Fafnir kill:

20 Earth shots:
Lowest - 29
Highest - 768
Average - 441

12 Lightning shots:
Lowest - 175
Highest - 699
Average - 532

Doesn't seem right. Especially since per #1101 you can do 2/minute instead of the era value of 1/minute

**Comment by Raphtalia1** [comment]
I have been suspicious of QD’s dmg output for a while now, the formulae here is incorrect however. MAB is a % increase for QD not a linear increase, corsair’s hat is a static increase 

[2 * (Gun base DMG + bullet base DMG + Corsair's Tricorne bonus)] * [1 + (MAB / 100)] * (Elemental Staff bonus) * (Day/Weather Bonus)

**Comment by ShiyoKozuki** [comment]
This explains why I see so many COR's and demand for COR's from recruiting linkshells - it's busted like summoner.

**Comment by Volkaru** [comment]
Can confirm it's very broken. Shooting for over 600 as a 69COR/25BLM ( so no MAB II) with just macc/mab roll, AF head, NQ ice staff, and moldy earring.
Those are like... Fully geared COR with Death Penalty kind of numbers. Yes the mobs were ice weak. But the damage is still very inflated. 
![Arktos_2019 12 19_204338](https://user-images.githubusercontent.com/9113384/71232069-4e7d3c80-22a5-11ea-91ab-337a9638ea61.png)

**Comment by Jimmayus** [comment]
https://youtu.be/DWfXGacN7JM I recorded this recent Cerberus kill. You can see that even on much higher level monsters with supposedly high magic resist quick draw is indeed still nuts.

**Comment by godmode** [comment]
Quick Draw has a temporary adjustment on the 30th patch. It will reduce damage significantly until the formula and root cause is found.

**Comment by ShiyoKozuki** [comment]
Seems reasonable now.  NQ ice staff, moldavite, blm sub, no other gear.
![Shiyo_2019 12 26_015237](https://user-images.githubusercontent.com/58101246/71462774-6f043580-2782-11ea-9f9b-f8596a5119b6.png)
![Shiyo_2019 12 26_015240](https://user-images.githubusercontent.com/58101246/71462779-71668f80-2782-11ea-8653-9edfd3252af9.png)

**Comment by ShiyoKozuki** [comment]
Quick draw is ignoring MDT which is inflating it's damage on HNM's as well.

Tested as named COR75/WHM37 with a peacemaker and silver bullets.

Neutral MDT mob - 306 damage
![Shiyo_2019 12 28_193047](https://user-images.githubusercontent.com/58101246/71550905-f4692f00-29a8-11ea-9bd6-24bede60cbc5.png)

+MDT mob. 306 damage
![Shiyo_2019 12 28_193257](https://user-images.githubusercontent.com/58101246/71550907-0054f100-29a9-11ea-92ab-637418aef702.png)

**Comment by Rikoooooo** [comment]
I can see that from this thread that Quick Draw has been adjusted in the past. However, the simple base calculation of: ((Gun DMG + Bullet DMG) x2) = Base DMG is currently giving me results as if the multiplier was x1.62~1.63 and not x2.

I am at level 42 COR and my Gun DMG is 28 and bullet DMG is 46. At this level without any additional bonuses from MAB or other equipment. **It should be ((28 + 46) x2) = 148**. However, I went out and shot many Ice Shots vs a Too Weak mob and got **only 120 DMG every time**. This was done on Darksday and vs. mobs that aren't resistant to ice. 

Just thought I'd let you know that the base calculation is slightly off.

**Comment by 59blargedy** [comment]
resolved may 31, 2021 - quick draw damage goes by the posted formula, and is subject to mhit resists
