### ISSUE TITLE
''Community Service'' quest ' Lamps have wrong time

### ISSUE THREAD

**Issue by Anniakai** [EdenServer/community#2271]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver. 30181205_0

Something wrong with the clock (time of day) for this quest.
Could not flag quest at 9:00 (as suggested by NPC)  or complete if flagged at the usually correct time of 18:00.

Clicked on the first lamp immediately after flagging the quest from Zauko (right after 18:00), and received message from lamp: "You have failed to light the lamps in time".  
Clicked again on Zauko who said, "It's too early. Lights on at 9:00."
Clicked after 1:00, Zauko said, "I am disappointed. Stay sharp next time."
Attempted to flag quest at 9:00 as Zauko suggested and got normal, " I am Zauko. I patrol Lower Jeuno.…" message.

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
