### ISSUE TITLE
Crossbones check like NMs during Pirate Attack

### ISSUE THREAD

**Issue by Althaia** [EdenServer/community#2272]
### Checklist

* [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
* [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
* [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is: Version 30181205_0

I was riding the midnight ferry from Mhaura to Selbina, hoping to catch a pirate attack and get a sand charm from a Crossbones. I got it, so then I just ran around checking out all the monsters.

That's when I noticed the Crossbones were checking as "impossible to gauge," which is a designation reserved for NMs. The Crossbones are normal monsters, so they really shouldn't check that way.

[https://ffxiclopedia.fandom.com/wiki/Crossbones](https://ffxiclopedia.fandom.com/wiki/Crossbones)

This was during a normal pirate attack (no NMs like Blackbeard or Silverhook), if that makes a difference.

**Comment by ShiyoKozuki** [comment]
They're impossible to gauge on retail. Are you sure they aren't supposed to be impossible to gauge?

**Comment by Shoruto** [comment]
Crossbones are not listed as NMs during era, when checked OOE dates they still weren't listed as NMs.

https://ffxiclopedia.fandom.com/wiki/Crossbones?oldid=317411
https://www.bg-wiki.com/index.php?title=Crossbones&oldid=56649
https://ffxi.allakhazam.com/db/bestiary.html?fmob=1020
http://ffxi.somepage.com/mobdb/2107

Just for comparison sake the levels seem to vary on the webpages and player reports for the crossbones.

-----------------------------------------------------------------------

Feb 23 2004
Anonymous
Anonymous
**Its not a notorious monster**

the levels are 35-50

IT COME AT DAY TOOOOO

It wont really agro...unless your stupid enough to get close to it

How you will know: well first ull start hearing some badass music^^ then ull see another ship that means run up the stairs and hide behind the captains thing ull see a ship with 3 summoner casting some spell and like 10 cross bones appear on deck...as long as ur at the top of the stair they wont agro you

------------------------------------------------------------------

**Comment by 59blargedy** [comment]
resolved 11/16
