### ISSUE TITLE
2-3 CoP

### ISSUE THREAD

**Issue by Dominatusnox** [EdenServer/community#2273]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

2-3 CoP mission won't finish when talking with Justinius. Tarutaru approach then don't say anything. So CS is stuck have to force close game.

**Comment by Volkaru** [comment]
Are you using /fps 1? If a cutscene freezes, try hitting the Print Screen key to force it to continue. If that doesn't work, switch to /fps 2 for just the Cutscene, then you can switch back once it's done.
