### ISSUE TITLE
Unable to obtain colored bracelets in Pso'Xja

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#2277]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

The ???s in Pso'Xja do not spawn the NMs when touched for the blue or green bracelet needed to travel through certain parts of Pso'Xja.

https://ffxiclopedia.fandom.com/wiki/Chips

**Comment by bkesecker** [comment]
Quest A Reputation in Ruins must be flagged.  Is it?

**Comment by montijin** [comment]
Ah, I see that was the issue after all. I thought I had the quests flagged.
