### ISSUE TITLE
Mimics in Pso'Xja

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#2278]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Set mimics in Pso'Xja are supposed to attack you when you examine them. They are currently acting like normal chests instead.

https://gfycat.com/RealCalculatingCoypu

**Comment by montijin** [comment]
It should be noted that these mimics are necessary to complete the quest for CCB Polymer which is used in the upcoming 6-4 fight releasing at the end of the month.

**Comment by VirtuosusFFXI** [comment]
This is still an issue after today's patch. In retail/era all you had to do was examine chests and if it was a mimic, it would spawn and attack you. Not functioning this way currently.

**Comment by Jimmayus** [comment]
Pso'Xja mimic spawn behavior from retail
https://youtu.be/PCFOXFXM0tc
https://www.dropbox.com/s/fogs17blu41zk7z/Pso%27Xja%20mimic%20spawn%20behavior.rar?dl=0

**Comment by montijin** [comment]
Just to add onto chest issues, I ran across an invisible chest earlier in pso'xja. 
https://gfycat.com/MagnificentWastefulCapeghostfrog

**Comment by perkuprightmeow** [comment]
Bumping this, it's still incorrect and with TH changes farming Cyan chips is considerably more punishing. I believe the drop rate on chips themselves are correct/match sources I can find, but the mechanic being incorrect obliterates any kind of balance. 

TH2: 8.57% (12/140)
TH3: 9.55% (17/178)
TH4: 10.76% (47/437)

On the test server you just repeatedly trade a key to a chest until it decides it's going to be a mimic. They don't despawn after trading, and a chest that gave you 10k gil a second ago, can be a mimic the next time you trade a key.

**Comment by PyreOgion** [comment]
I think there is still issues with the Mimics here. As you can see in the image the mimic is showing an HP bar. When I click the chest to trigger a mimic, my cursor deselects the chest. There isn't any message about needing a key. The normal treasure chest mentions the chest key.

![image](https://user-images.githubusercontent.com/32087703/88490736-97d7ed80-cf52-11ea-8dfd-d6cc7ae3b0e6.png)
