### ISSUE TITLE
Diffusion + Exuviation Combo is not perform "Erase" on party

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2279]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver: 30181205_0

When using Diffusion + Exuviation, the AoE heal is happening, but the Erase effect of Exuviation is only applying to me (the blue mage caster). I've tested it vs. Slowga and multiple times against Soulflayers using Tribulation to inflict Bio/Blind on the party. The Exuviation takes off my debuff 100% of the time and never affects my party members.

**Comment by Volkaru** [comment]
Also I heard Exuviation isn't giving the proper amount of hate. Using it on a full party should give the BLU comparable hate to a PLD using Invincible.
