### ISSUE TITLE
Diamondhide seems like it may be using the wrong formula

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2280]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver: 30181205_0

If someone could look at the Diamondhide code it might be helpful. I'm not sure exactly how much it is blocking but if I had to guess, I'd say 450-500 with 299 Blue Magic Skill. As far as I can tell from the wiki, the formula should be something like Blue Magic Skill * 6 + 20, or Blue Magic Skill * 2/3 depending on what date in the wiki you use (its probably the former, and the latter was just a guess back in 2007).

By all means, leave it if it is correct and I'm misinformed, I'm just comparing the wiki to my experience while playing.

**Comment by KnowOne134** [comment]
Looks like correct is skill x 1.5. Can you link your refrences

**Comment by E5una** [comment]
I was just using the current wiki page:

https://ffxiclopedia.fandom.com/wiki/Diamondhide

And the nov 11th 2007 one:

https://ffxiclopedia.fandom.com/wiki/Diamondhide?oldid=375034

**Comment by KnowOne134** [comment]
What was the cap for this in era 200 or 320?

**Comment by Volkaru** [comment]
The current formula listed on Ffxiclopedia is correct. It's never been changed. Caps at 500 skill with 320 (we can't get that in Era) it's about 2/3rd your skill level for amount restored.

**Comment by VirtuosusFFXI** [comment]
I know this issue has been closed, but I thought I would throw my testing into it just in case:

![1000needles](https://user-images.githubusercontent.com/49970272/71769918-bca43f00-2ef4-11ea-9cee-762823dc94c0.png)

![diamondhide1](https://user-images.githubusercontent.com/49970272/71769919-bca43f00-2ef4-11ea-8083-7846b8c459a0.png)

![diamondhide2](https://user-images.githubusercontent.com/49970272/71769920-bca43f00-2ef4-11ea-8c6c-5ad568786f06.png)

Level 75 BLU with capped Blue Magic skill, 8 merits, AF2 Head, AF Body is at 312 Blue Magic skill and Diamondhide absorbed 468 damage. 

This means that the current formula is Skill * 1.5, and era formula should be (Skill * .6) + 20 or (Skill * 2/3) which results in 207.2 or 208 respectively. Hard caps at 320 in current retail or 200 in era.

**Comment by KnowOne134** [comment]
Yes that's what I just changed the formula to. But could not find the cap onfo for era. Can you post refrence

**Comment by VirtuosusFFXI** [comment]
200 is something I can personally account for as being the cap in era, however I've also looked back on the wiki:

September 7, 2010

![cap2010](https://user-images.githubusercontent.com/49970272/71770092-ee1e0a00-2ef6-11ea-9213-a95bbc99bddb.png)

September 14, 2010

![capsept142010](https://user-images.githubusercontent.com/49970272/71770112-26254d00-2ef7-11ea-8d48-58b460ae0950.png)

Current Date
![cap](https://user-images.githubusercontent.com/49970272/71770120-3fc69480-2ef7-11ea-965e-b725b59c230c.png)

It seems as though the cap was 200 until an update that happened on September 8th, 2010.

**Comment by VirtuosusFFXI** [comment]
Unfortunately, I tried to reference this page but it seems that it may have been a ninja change by SE as I couldn't find it listed anywhere:

[https://www.bg-wiki.com/bg/Version_Update_(09/08/2010)](https://www.bg-wiki.com/bg/Version_Update_(09/08/2010))

**Comment by KnowOne134** [comment]
Good enough. I can update the cap on another pr
