### ISSUE TITLE
Unlisted Qualities / Adventuring Fellow Glitch

### ISSUE THREAD

**Issue by hrmitchell** [EdenServer/community#2281]
I was really excited to hear adventuring fellows was implemented, so I talked to Luto Merwrilah to see if I had enough fame / rank to start the quest. I was offered dialogue to start the quest, but I wasn't sure which fellow to choose, so I **declined starting the quest.** After looking on wiki for a bit, I returned to see that **the computer auto-selected an adventuring fellow fellow for me.** It auto-defaulted to the first npc on the list, **a hume-male named Feliz.** Moreover this happened on my alt as well, so the **glitch is reproducible**. I'm really thinking of deleting both of my characters over this....

**Comment by KnowOne134** [comment]
The fellow is defined by the choices you make at the other NPCs in the quest after luto by telling them who you are looking for. Try completing the quest 1st

**Comment by hrmitchell** [comment]
https://ffxiclopedia.fandom.com/wiki/Unlisted_Qualities

But the **first choice is race / name via Luto**, which I'm saying is bugged and auto defaults to a hume named Feliz:
https://ffxiclopedia.fandom.com/wiki/Adventuring_Fellow#Adventuring_Fellow_Names

I only know this because I followed up with the next npc who told me in so many words... "Oh you are looking for that hume named Feliz."

**Comment by xizeta** [comment]
Please make a GM call with the Help Desk in-game, list the characters involved and the issue number #2281. We will fix your characters and address the code issue.
