### ISSUE TITLE
BST capable of claiming a monster another player already has claimed.

### ISSUE THREAD

**Issue by Fideide** [EdenServer/community#2285]
### Checklist

- 

- [✓] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)

- [✓] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [✓] I have provided my client version in the details. (type /ver into your game window)

### Details

Client Version : 30181205_0

How to reproduce: This was only tested with bst as i do not have SMN or PUP at this time.
When someone else goes to fight the same mob as you, when you send you pet in on it, they get claim first however your pet doesnt care, and takes claim for your self. the order seems to be 

Sick pet> player2 casts any spell/ melee's before pet arrives>they have claim>pet will attack their solo claimed monster and get claim for your self. Tested on TW mobs in saruta, but first witnessed in valkrumdunes. Hard to abuse but there's a;ways the risk someone will learn how to abuse it.
Have also stole claim from my parties PL while they already had it claimed in dunes. Could not reproduce this however.

**Comment by roriffxi** [comment]
https://github.com/EdenServer/community/issues/1596

**Comment by InoUno** [comment]
Should be resolved with January 4th, 2021 patch.
