### ISSUE TITLE
Jaded Jody PH Incorrect

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2286]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

30181205_0

https://github.com/DarkstarProject/darkstar/blob/8ad895e0d5a0b8d2e5f60f800958e06fb5ec5112/scripts/zones/Wajaom_Woodlands/IDs.lua

Indicates PHs for Jaded Jody are 16986376 and 16986390.

https://ffxiclopedia.fandom.com/wiki/Jaded_Jody?diff=347063&oldid=304489 says "The placeholders are the two Great Ameretats on the lower part of the ledge.". 390 is located in E-12. Correct PH should be 16986377, not 16986390.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
