### ISSUE TITLE
Fomor Hate not working correctly (will aggro even at lowest level of "hate")

### ISSUE THREAD

**Issue by PoppaPip** [EdenServer/community#2287]
Me and my party killed loads of orcs/gigas in Lufaise Meadows until we had "level 1"/default hate levels https://ffxiclopedia.fandom.com/wiki/Fomor_Hate?oldid=491377. After counting over 50 kills, as well as confirming through https://ffxiclopedia.fandom.com/wiki/Resauchamet?oldid=1676394, we still got aggro. The Fomor in Lufaise aggro'd by /healing next to them, and those in Sacrarium still aggro'd to both sound and low HP.

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

**Comment by KnowOne134** [comment]
Was resolved in 5/3/2023 update
