### ISSUE TITLE
Burdock Root grown in moghouse OOA

### ISSUE THREAD

**Issue by Eydaos** [EdenServer/community#2288]
### Checklist

- [0 ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [0 ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [o ] I have provided my client version in the details. (type /ver into your game window)

### Details
Burdock Root is OOA. It is being grown in the MH using vegetable seeds and fire crystal. Wild Onion should be the result instead.

/ver 30181205_0

**Comment by Spiffly** [comment]
Just harvested this myself. First mention of it on retail wikipedia is it being harvestable in West Sarutabrauta (S). [https://ffxiclopedia.fandom.com/wiki/Burdock?oldid=387317](url)
