### ISSUE TITLE
Lost items via trade

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#229]
Player A had 26/30 inventory
Player B had 12+ spaces 

Player A put 6 items in the trade window, player B put 4 items in trade window.

Upon trade completion, player B received the 6 items, but player A did not receive the 4 items, they poofed.

These 4 items lost have some value to me, around 250k gil or so.

**Comment by Serephim** [comment]
I also did this, but it was with 99,999,999 gil. ;)
On the serious though, that is a little scary that this can happen. I trade very precious items between my characters a lot. x_x

**Comment by icariumkupo** [comment]
To add, it may have been the case that player A had less than 4 spaces available. Could be instead of failing the trade the items were destroyed. Dunno if stuff like this is logged but just in case, the trade happened around 5pm est on 10/24. The items lost in question were 4x Life Belt. Hopefully I'm not being a dumdum and misplaced but I've checked everywhere many times. Dey gone.

**Comment by RoninXI** [comment]
Happened to me as well. I was trading spike earrings to Ryu and he was trading me mats for spike necklaces. My inv was full, when I went to check if I had the mats I didn't and neither did he.

**Comment by gweivyth** [comment]
Yep this happened.  I feel like a jackass.  Please fix GM.  :(

**Comment by beauxq** [comment]
@godmode I found this bug. Here is the fix:
in src/map/utils/charutils.cpp
in `bool CanTrade(CCharEntity* PChar, CCharEntity* PTarget)`

change
`if ((PTarget->getStorage(LOC_INVENTORY)->GetFreeSlotsCount() + PTarget->UContainer->GetItemsCount()) < PChar->UContainer->GetItemsCount())`

to
`if ((PTarget->getStorage(LOC_INVENTORY)->GetFreeSlotsCount() + PTarget->UContainer->GetItemsCount()) < 0)`


This is more restrictive than some players would like it, but I think it is accurate to era retail.
If I remember correctly, in era retail, you needed to have enough empty slots before the trade for all the items you receive in the trade, including counting gil as if it were an item.
My memory could be wrong on that though.

If you want to try the less restrictive way (that someone was attempting when they wrote this bugged code), it would be more complex. You would replace the `GetItemsCount` on the containers with a new method `GetNonGilItemsCount`. And I suspect there might be other side effects with that that could cause problems.

**Comment by godmode** [comment]
My fix was similar to that. Thanks for the snippet!
