### ISSUE TITLE
Warriors can use kite shields - OoE

### ISSUE THREAD

**Issue by ShiyoKozuki** [EdenServer/community#2290]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

Warrior can use all the "Kite"class shields on Eden. This is not era accurate and makes warrior better at shields than was intended by SE in our era. https://ffxiclopedia.fandom.com/wiki/Kite_Shield?oldid=317808 2007
https://ffxiclopedia.fandom.com/wiki/Kite_Shield?oldid=447905 2008
https://ffxiclopedia.fandom.com/wiki/Kite_Shield?oldid=1045713 dec 2009

Screenshot taken from Eden.
![kite shield on warrior](https://user-images.githubusercontent.com/58101246/71050714-efd48900-2113-11ea-8f0c-bd15f16e1fb4.png)

This is true for ALL "Kite" PLD/DRK class shields and not JUST "Kite shield"

https://ffxiclopedia.fandom.com/wiki/Category:Shields?oldid=356108 october 2007. Search "Kite"

**Comment by KnowOne134** [comment]
Implemented but dats need modes to remove war from seen equipment

**Comment by PrettyCoolPattern** [comment]
I have compiled a list of all the shields listed with the wrong code in the .dat file and have edited my files to appropriate, in final stages. fix coming soon. 

If any more shields are missed please let me know.

Kite Shield
Heater Shield
Darksteel Shield
Ritter Shield
R.K. Army Shield
T.K. Army Shield
Ryl.Grd. Shield
Tower Shield
Argos Shield
Kite Shield +1
Heater Shield +1
Dst. Shield +1
Ritter Shield +1
Tower Shield +1
Scutum +1
R.K. Shield +1
R.K. Shield +2
Charging Shield
T.K. Shield +1
T.K. Shield +2
General's Shield
Admiral's Shield
Jennet Shield

**Comment by KnowOne134** [comment]
Eden already has the sql edited

**Comment by KnowOne134** [comment]
has been dat edited and can pick up latest dats here:
https://github.com/EdenServer/Eden-Client_DATs

resolved 2/26/2023
