### ISSUE TITLE
Windurst 6-2 BCNM bugged

### ISSUE THREAD

**Issue by piercingdark** [EdenServer/community#2291]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version  30181205_0

Party of 4 went into BCNM at Balgas Dias for Windurst 6-2. We beat BCNM but the Yagudo Avatar was still alive even though the summoner was dead. The rest of the party got CS, KI (Balgas Champion Certificate) and the appropriate title. My screen went black and the Yagudo Avatar (carby) was attacking me. I force d/ced, came back with no battlefield buff on and avatar was still up (so I killed it). However I could not leave the BCNM normally from the back and never got CS, KI or the title. Eventually just warped out of BCNM.

**Comment by bkesecker** [comment]
Most BCNMs can exhibit this behavior and is a long standing issue with legacy code.  Just wanted to let you know you aren't alone, and to the development team, another victim who needs to call GM to correct the missing progress.

**Comment by Volkaru** [comment]
I ran into this same exact issue. It's still happening. Had to have the Senior GM fix me.

**Comment by Dribblet** [comment]
I had the same issue, it seems that the Carbuncle gets summoned frozen and untargetable during the fight, only to unfreeze when the BCNM icon falls off to attack whichever target had the SMN's hate at the time of 2hr, black screening them.
I was able to bypass this black screen issue by getting the SMN 2hr to pop & killing the smn, then dying and re-raising, which reset aggro on the frozen carby, preventing a blackscreen. You should also be able to accomplish this by having a pet take hate from the SMN and then having the SMN 2hr, and then unsummoning the pet before the fight ends.
