### ISSUE TITLE
Dynamis - Windurst boss statue will repop all monsters if you kill the monsters before the boss

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#2295]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0
We pulled the Tzee Xicu Idol in Dynamis - Windurst and killed the non-boss monsters while the puller died and the boss deaggroed. The statue made its way back to the spawn point while we full cleared its spawned monsters. When we pulled the boss again it respawned all monsters, including both paladin NMs (Muu Febi and Maa Febi the Steadfast).

**Comment by Mozzy4Ever** [comment]
To add to this - Don't have to let megaboss get back to it's spawn point. Our THF pulled megaboss to the bridges past AH and died while we were killing the spawned mobs. Megaboss pathed back and sight aggro'd us, spawning the mobs we hadn't killed yet.

**Comment by 59blargedy** [comment]
resolved in december 28, 2020 update
