### ISSUE TITLE
sea monk family whirlwind/maelstrom attacks versus shadows

### ISSUE THREAD

**Issue by bootseden** [EdenServer/community#2297]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

whirlwind used by sea monk family mobs should remove shadows from those struck by it, it currently does not remove shadows
https://ffxiclopedia.fandom.com/wiki/Whirlwind

**Comment by ShiyoKozuki** [comment]
https://youtu.be/tJrWFHTfHrU?t=65
Here's a 10 year old retail video with proof of this.

**Comment by bootseden** [comment]
interesting, this video also shows that maelstrom should be removing shadows as well at https://youtu.be/tJrWFHTfHrU?t=135 , it's not currently doing that on eden

**Comment by danismyhero** [comment]
I feel like this is a greater issue with aoe weaponskills for all mobs, and not mantas specific.   

Golems come to mind, and I think the issue may be aoe skills that cannot be absorbed by shadows are not clearing them.

**Comment by ShiyoKozuki** [comment]
Could you give me a list of all the TP moves that ignore shadows and aren't supposed to? I'll test them all.

**Comment by bootseden** [comment]
hmm it's probably aoe elemental damage tp abilities then in general that aren't wiping shadows based off of what dan said, golems have 3 moves like that: crystal rain, thunder break and ice break

**Comment by ShiyoKozuki** [comment]
Crystal rain, ice break and thunder break all wipe shadows
![Shiyo_2019 12 27_175059](https://user-images.githubusercontent.com/58101246/71535137-99b0d400-28d1-11ea-862c-34f41cf1eda8.png)
![Shiyo_2019 12 27_175135](https://user-images.githubusercontent.com/58101246/71535142-a33a3c00-28d1-11ea-92dc-bda604e0795f.png)
![Shiyo_2019 12 27_181431](https://user-images.githubusercontent.com/58101246/71535602-be5a7b00-28d4-11ea-95a0-ccee3d27ca55.png)

**Comment by KnowOne134** [comment]
Its adding a parameter to the script that is needed

**Comment by KnowOne134** [comment]
Has been fixed
