### ISSUE TITLE
Promies empty seed dmg

### ISSUE THREAD

**Issue by sefried12** [EdenServer/community#2298]
### Checklist
 the damage empty seed does from the promies is way to high can nearly one shot someone it makes it where melees are undissired in the rin entirety and makes it hard people w/o pup or smn lvled

- [ *] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ *] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by sefried12** [comment]
Dmg is to high on empty seed can 1 shot people making it where only ranged and pet jobs are wanted or disired make ppl w/o those classes lved nearly impossible to progress

**Comment by Jimmayus** [comment]
So I wasn't sure whether this was the case, but I had a bit of time and went and checked it out on retail. You can see for yourself in this video: https://youtu.be/9NJJPOs_b0E . The first floor promyvion-mea empty receptacle was hitting a basically naked level 30sch/15blm (so a mage) for between 50 and 70 damage.

**Comment by sefried12** [comment]
I get that but on eden is very strong pt was taking 100s 1st floor and upper ones it nearly killed a galka thf in 1 hit 200-300ish dmg

**Comment by Jimmayus** [comment]
oh yeah that evidence is in your favor. The video suggests that receptacles on retail are much weaker.

**Comment by sefried12** [comment]
Thank u for backing me bud

**Comment by ShiyoKozuki** [comment]
I don't remember this TP move annihilating people. Here's a 2010 video that mimics Jimmys
https://www.youtube.com/watch?v=wL9yN-dhDNE&feature=youtu.be&t=196

**Comment by 59blargedy** [comment]
this has been resolved for some time, missed closing it
