### ISSUE TITLE
Kuftal Tunnel rock not moving

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#23]
Waited for over 30 minutes for the rock to move in order to get to the basement of Kuftal Tunnel.

**Comment by godmode** [comment]
Most likely the necessary requirements are not met. Please check the wiki history and try again.  Leaving this ticket open for a while in case there is a bug.

**Comment by dantaface** [comment]
Rocks are not supposed to have a necessary requirement. They drop after 10 to 15 minutes.
