### ISSUE TITLE
survival guides

### ISSUE THREAD

**Issue by beauxq** [EdenServer/community#230]
Survival Guides all over the place not from era.

`SELECT * FROM dspdb.npc_list
WHERE name = "Survival_Guide";`

**Comment by beauxq** [comment]
@godmode You didn't get all of them. I just passed one in Inner horutoto ruins.

**Comment by godmode** [comment]
Can you take a screenshot and maybe give the position of it? I can't find it being missed in the DB

**Comment by beauxq** [comment]
near the entrance I-7, from east sarutabaruta J-7 

![beaux_2018 12 05_235828](https://user-images.githubusercontent.com/6052147/49564656-ece06f00-f8e9-11e8-8db3-988e414813b1.png)
