### ISSUE TITLE
Can't complete Hitting the Marquisate (Thief AF boots) 

### ISSUE THREAD

**Issue by rpcon** [EdenServer/community#2301]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
I initially tried to do this quest as a warrior a few months ago, and got up to checking ceiling hole 5, when I could only get, "There is a hole in the ceiling."
Tried again yesterday. Now, even the first ceiling hole gives the same default text.
I confirmed that I have the bomb incense key item, and that the quest is active in the log. I even went back to the NPC in Mhaura, but again, only got default text.

**Comment by xizeta** [comment]
Please send a GM ticket in-game through the Help Desk, referencing this issue number #2301.

**Comment by rpcon** [comment]
After re-doing the entire Garlaige part of the quest, I was able to complete it.
