### ISSUE TITLE
player/pet tp gain when struck by monster spells & tp abilities

### ISSUE THREAD

**Issue by bootseden** [EdenServer/community#2304]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

players should be gaining 50 tp (out of 1000) when struck by spells
https://ffxiclopedia.fandom.com/wiki/Tactical_Points?oldid=360036 "When a player is hit by a damaging spell, he gains 5 TP." (article states this on the 100tp scale so 5tp becomes 50 on the 1000tp scale)

another thing that could use some verification is if players gain tp when struck by damaging tp abilities (should test if multi-hit/magical/breath reward different amounts)

after doing this for players, observe if the above is the same for player's pets

**Comment by ShiyoKozuki** [comment]
Can confirm, hit with multiple spells and gained 0 TP. I typed the text command <tp> after and before every spell and you can see in my party window I do not have TP despite being nuked and dying.

Tested as a naked 75 WHM/NIN with protectra5 and shellra5
![image](https://user-images.githubusercontent.com/58101246/71465665-3f0d6000-278b-11ea-9851-16984a0188c0.png)

**Comment by bootseden** [comment]
did some testing regarding pets getting hit by spells on eden and results were:
summoner pet - 300tp
wyvern - 300tp
jug pet - 300tp
charmed pet - 100tp
automaton - 100tp
so guess some verification is needed if player's pets follow the same rules as players, however i also think all the ways they gain tp (attacks they make & when they they are hit) should also be checked out too

**Comment by Wade9363** [comment]
The TP gain for Charmed Pets & Jug Pets is pretty much irrelevant to the job. 

Sic is on a 3 minute cooldown, so between Sic's charmed pets usually have a lot more than 100tp.

Ready moves work regardless of Jug Pets TP.

**Comment by ShiyoKozuki** [comment]
It's relevant because it's wrong and possibly imbalanced. Jug pets shouldn't just randomly get 3x the TP from being hit by spells that's just silly(neither should wyverns or summoner pets)

**Comment by Wade9363** [comment]
It's irrelevant "for the job".  

E.G. At no point in lvl'ing BST to 75 or doing content as a BST main have I looked at pet TP for any reason.  Some ready moves hit harder with higher TP, but by waiting till full TP to use them dmg is being gimped since Ready can be used every 30 seconds.

By all means fix it, but it's not going to impact the job or how it is played.

**Comment by bootseden** [comment]
looking at the tp gains from shiyo's screenshots it seems that we can conclude that jug pets, wyverns and summoner pets gain tp at x3 the rate that enemies do (when they make attacks, when they are hit by attacks/spells)

charmed pets & automatons seem to follow the enemy tp gain rates from https://ffxiclopedia.fandom.com/wiki/Tactical_Points?oldid=360036

so what needs testing/confirmation from retail is if pets follow the same rules for tp gain as players or enemies and also how much tp players and player's pets gain from being hit from damaging tp abilities/spells (should be 50tp for spells on players)

**Comment by Setz0r** [comment]
Pet TP gain was in fact coming in at 3 times the actual era rate.  this has been fixed in todays patch.

**Comment by bootseden** [comment]
yes, i believe that should be investigated and then compared to pets
