### ISSUE TITLE
Sandy 2-3 bastok leg

### ISSUE THREAD

**Issue by Everian** [EdenServer/community#2305]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Im basically having the same issue as in ticket #1853. grohm does not give cs or pickaxes to continue the mission. my character is Llaco ver 30181205_0

**Comment by 59blargedy** [comment]
(hopefully) fully resolved these sorts of issues in april 26, 2021 update
