### ISSUE TITLE
Quest: In a Stew - Repeatable More than Once per Tally

### ISSUE THREAD

**Issue by Althaia** [EdenServer/community#2306]
### Checklist

* [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
* [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
* [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is: Version 30181205_0

This is something I've noticed for a while, but never created a bug report because I wasn't sure if this quest being repeatable only "once per conquest tally" is in-era or not.

I vaguely seem to recall it's only once per conquest tally? It's how it appears on retail:

https://ffxiclopedia.fandom.com/wiki/In_a_Stew

Anyway, I just accepted the quest twice in a row -- without even finishing it the first time -- so it got me thinking the NPC behavior of it being offered is buggy somehow, favoring being able to do it more often than a person should.

The entire quest works fine, I can do it and turn in the key item for the reward. I just don't know if it's supposed to be able to be repeated more than once per conquest tally.

**Comment by Volkaru** [comment]
Can confirm via old wiki pages. Able to be completed once per tally: https://ffxiclopedia.fandom.com/wiki/In_a_Stew?oldid=352300

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
