### ISSUE TITLE
Breath attacks ignore MDT

### ISSUE THREAD

**Issue by ShiyoKozuki** [EdenServer/community#2308]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

All breath attacks ignore MDT. They are only supposed to ignore MDB and thus not benefit from MAB. I am going to assume this is the exact same for monsters - and why players seem to take big hits from breath attacks from monsters.
https://www.bg-wiki.com/bg/Heat_Breath
Base damage is equal to players current HP divided by 2, but is subject to fractional resists.
Not affected by Magic Attack Bonus.
Damage is not affected by Magic Burst or Monster Correlation bonus, but accuracy is increased.
Damage is increased by Convergence.
Ignores Magic Defense Bonus, but is subject to direct magic % resistance or weakness.
![Shiyo_2019 12 26_023233](https://user-images.githubusercontent.com/58101246/71464735-79c1c900-2788-11ea-9827-624f27c8e1a3.png)
Screenshot is a naked 75 bluemage/NIN. It's doing EXACTLY 50% of my HP on a monster with -MDT.
![Shiyo_2019 12 26_165226](https://user-images.githubusercontent.com/58101246/71491706-35720f80-2800-11ea-95c7-81742305708e.png)
In this screenshot, it's doing exactly 50% of my HP on a monster with +MDT(Extra magic damage taken).

Version 30181205_0

**Comment by Slamm21** [comment]
They also can never be resisted on Eden which is wrong.
I believe barspells helped but I do not 100% remember on that but you could resist it up to making it do 1/16th of the damage and even on Kirin, 1/16 was not uncommon.

**Comment by ShiyoKozuki** [comment]
Mevasion works on them, and barspells are mevasion. They get resisted pretty frequently on highrer end monsters with base MDT.
![Shiyo_2019 12 26_164308](https://user-images.githubusercontent.com/58101246/71491471-dc55ac00-27fe-11ea-85bf-ee35dbb6859d.png)

**Comment by Slamm21** [comment]
that's what I thought.
On here a too weak manticore will always heat breath you for 500dmg, even at 75 with barfire lol

**Comment by ShiyoKozuki** [comment]
Magic evasion from mob breath attacks 100% work as well. 
![Shiyo_2019 12 27_183501](https://user-images.githubusercontent.com/58101246/71535955-7f2e2900-28d8-11ea-83f6-49b2381cc72e.png)
![Shiyo_2019 12 27_184232](https://user-images.githubusercontent.com/58101246/71535975-a97fe680-28d8-11ea-9b90-ecb3a99de04f.png)
![Shiyo_2019 12 27_184005](https://user-images.githubusercontent.com/58101246/71535946-5d34a680-28d8-11ea-9663-57b3a14801b5.png)

**Comment by 59blargedy** [comment]
from retail testing, breath attacks are only affected by -BDT, it's just that most things that have -mdt also have -bdt on them as well. 
resist states do exist. between this and mhit changes a while back, this bug report has been resolved
