### ISSUE TITLE
Flame Degan(lvl40 sword) not proc'ing Additional effect: Fire Damage

### ISSUE THREAD

**Issue by papikong** [EdenServer/community#2309]
### Checklist

- [O] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [O] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [O] I have provided my client version in the details. (type /ver into your game window)

### Details

Had these Flame Degans for a while. Usually use them for farming low lvl mobs on BRD and I have never seen them proc the fire damage. Didn't mind it too much and assumed this was a global issue.

Recently, I purchased a pair of Flame Swords (lvl18 sword) with the same effect and they proc regularly like in era retail.

It would be appreciated if this can get fixed since I still use these to farm. The small amount of fire damage adds up.

version 30181205_0

**Comment by ShiyoKozuki** [comment]
The sword is level 40.
https://classicffxi.fandom.com/wiki/Flame_Degen
it also doesn't seem to be working, my parser shows "Additional effect" and after 98 attack rounds dual wielding the NQ flame degens I didn't get a single proc.
![Shiyo_2019 12 26_182005](https://user-images.githubusercontent.com/58101246/71493418-65271480-280c-11ea-9366-8c16d54f7bd3.png)

**Comment by papikong** [comment]
Sorry, I edited the title.

**Comment by gweivyth** [comment]
```lua
-----------------------------------------
-- ID: 16522
-- Item: Flame Degen
-- Additional Effect: Fire Damage
-- Gweivyth
-----------------------------------------
require("scripts/globals/status")
require("scripts/globals/magic")
require("scripts/globals/msg")
-----------------------------------

function onAdditionalEffect(player,target,damage)
    local chance = 10

    if (math.random(0,99) >= chance) then
        return 0,0,0
    else
        local dmg = math.random(10,15)
        local params = {}
        params.bonusmab = 0
        params.includemab = false
        dmg = addBonusesAbility(player, dsp.magic.ele.FIRE, target, dmg, params)
        dmg = dmg * applyResistanceAddEffect(player,target,dsp.magic.ele.FIRE,0)
        dmg = adjustForTarget(target,dmg,dsp.magic.ele.FIRE)
        dmg = finalMagicNonSpellAdjustments(player,target,dsp.magic.ele.FIRE,dmg)

        local message = dsp.msg.basic.ADD_EFFECT_DMG
        if (dmg < 0) then
            message = dsp.msg.basic.ADD_EFFECT_HEAL
        end

        return dsp.subEffect.FIRE_DAMAGE,message,dmg
    end
end
```

This should fix this item and the HQ version as well.  (Flame Degen +1)  I didn't observe any difference in proc damage with NQ vs. HQ.
