### ISSUE TITLE
Signed items missing last letter

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#231]
When I sign stuff on my character "Mcdohl" the l gets left off and I'm left with a Mcdoh signature. This only seems to happen when the signed item is transferred to a different character and after that character zones. If I keep the items on Mcdohl, I don't have the issue.

Edits: This doesn't seem to happen on my other characters. 
This only seems to happen on my main craft(Goldsmithing). I signed a leather item with Mcdohl and I didn't have the issue.

**Comment by icariumkupo** [comment]
Mc'doh!

**Comment by jmcmorris** [comment]
This was apparently fixed in DSP last month. Perhaps not entirely. https://github.com/DarkstarProject/darkstar/pull/5240

**Comment by Oyaziiiiiii** [comment]
Ah I haven't tried it in about a month. I'll double check, this might not be an issue anymore.

**Comment by Oyaziiiiiii** [comment]
It does seem to be fixed. Yay for no more Mcdoh brand.
