### ISSUE TITLE
BLU Cold Wave using wrong formula

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2310]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver: 30181205_0

According to https://www.bg-wiki.com/bg/Cold_Wave, Cold Wave should be dealing Level/5 + 3 damage (18 at lvl 75). According to this 2007 ffxiclopedia page, the estimation is also about 18: https://ffxiclopedia.fandom.com/wiki/Cold_Wave?oldid=349118

When testing outside Bastok on lvl 1 monsters (Huge Hornet), it takes 8 ticks for the monster to die without my intelligence gear on (66 INT), and 4 ticks for the monster to die with my intelligence gear on (108 INT). This sounds like it is using the same stats as Frost, the debuff that it applies, which would deal 2/tick @ 66INT and 4/tick @ 108INT according to https://ffxiclopedia.fandom.com/wiki/Elemental_Debuff?oldid=382217.

I took a look at the DSP code and it appears to be using Frost calculations from what I can tell. I didn't look too much into it, but I would guess the -AGI is insufficient as well if that is the case.

**Comment by E5una** [comment]
For what its worth, DSP has some code in there for Disseverment that looks like it applies the Poison 2 DoT @ a rate of Level/5 + 3. I didn't look it over very closely, but this is the same formula Cold Wave is supposed to use according to the sources I linked, so my guess is you could leverage something from Disserverment to help with the solution.

**Comment by ShiyoKozuki** [comment]
Pretty much every single blu spell is the wrong formula.

**Comment by E5una** [comment]
Can’t hurt to help the dev team :). I think saying a spell is wrong is probably not helpful, but providing them information on specifics like this may help, especially in the case of magic BLU spells rather than physical, which don’t suffer from all the same inherited issues.

**Comment by KnowOne134** [comment]
You are correct. Any info given with proof is welcome and very nice to have to get it fixed quicker

**Comment by ShiyoKozuki** [comment]
Fair enough. If you'd like, I'll test any blu spells you'd like tested if you give me a list. Perhaps it'll help the devs fix them faster when they start working on blu.

**Comment by KnowOne134** [comment]
It would. Can make a report per spell
Blue mage spell: whatever formula is wrong
