### ISSUE TITLE
Bust/COR

### ISSUE THREAD

**Issue by cannonbear23** [EdenServer/community#2311]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
everytime i get a Bust on /COR i get kicked form the game

**Comment by cannonbear23** [comment]
everyyytime i bust on /cor i get kicked form game

**Comment by dowzer** [comment]
I read it’s a problem with the recast and/or timers addons. Disable them and check if it still crashes.

**Comment by cannonbear23** [comment]
still doing it and just been doing it on XP roll and dose it COR/ and /COR

**Comment by StriderClerix** [comment]
It’s the timers plugin on windower. Disable it and you won’t crash when you bust.

**Comment by 59blargedy** [comment]
reopen if not addon/plugin issue
