### ISSUE TITLE
The Promise - Dark Mana Orb - Additional CS not available?

### ISSUE THREAD

**Issue by Althaia** [EdenServer/community#2313]
### Checklist

* [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
* [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
* [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is: Version 30181205_0

Hello, I'm Rank 10 Windurstian; there's supposed to be an additional cutscene for The Promise if you've beaten Fenrir as a Rank 10 Windurstian.

https://ffxiclopedia.fandom.com/wiki/The_Promise

I completed "The Promise" and then went and beat Fenrir and got my reward, along with the required key item: Dark Mana Orb.

There's supposed to be a cutscene that ties together the S.O.B. storyline with the Windurst storyline and I'd really like to see it, if it's available?

When I talk to Kohlo-Lakolo, he just says the usual thing about never breaking a promise; no additional cutscene.

I'm glad I got the Dark Mana Orb with no problems, but is this additional cutscene on our server?

**Comment by Deepupuu** [comment]
I can confirm, the additional cutscene is not working right now. I'm Rank 10 Windurst, Completed The Promise and have the Dark Mana Orb key item from beating Fenrir as Rank 10 Windurstian and the cutscene is not working. :'(

**Comment by 59blargedy** [comment]
resolved with April 26, 2021 update
