### ISSUE TITLE
After defeating Ultima CS doesn't show Ducal Guard's Ring

### ISSUE THREAD

**Issue by godmode** [EdenServer/community#2316]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

Complete CoP mission battlefield "One to Be Feared". As you get auto-zoned to Lufaise Meadows you will get a CS where you search the three tarutarus. "You find a !" should be "You find a Ducal Guard's Ring".

**Comment by KnowOne134** [comment]
works now
