### ISSUE TITLE
Fenrir fight missing 2hr skill

### ISSUE THREAD

**Issue by dakumauler** [EdenServer/community#2317]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
This doesn’t have to do with the test realm but I did find some content missing or wasn’t captured for the Fenrir fight for summoners he does not Astro flow at 50% and 20% like he is supposed to he does use normal blood pacts like he should but makes the fight abit to easy because of missing skill in fight.

* Uses his Astral Flow pact, Howling Moon, at approximately 50% of health, and sometimes again at 30%. Fenrir Prime's version acts more like the ultimate ability of Diabolos, dealing damage based on a percentage of the target's remaining HP.  https://ffxiclopedia.fandom.com/wiki/Fenrir_Prime

I have done the fight a few times and still does not work. Video proof of it not working. Skip to 27:07 which is 3% before 50%. https://www.twitch.tv/videos/523791821

**Comment by Slamm21** [comment]
I've seen him spam his 2hr on here just like all the avatars currently do.
Also, I killed him solo him countless times on retail and never once did he 2hr twice. I'm positive that is wrong.

**Comment by dakumauler** [comment]
I share all info and even have a stream as proof of it not working and the link to the info which has years of compiled information does not lie.

**Comment by KnowOne134** [comment]
I see a problem to fix

**Comment by Volkaru** [comment]
There must be something else at work, because I had done this fight only a couple months ago. And he used his two hour four times over the course of the fight. It seems to be treating all the avatars astral flow moves as a regular TP move to choose from, not something special to trigger at X HP% and USE ONCE like it's supposed to. So you can run into fights where they will use them multiple times, or not at all.

**Comment by dakumauler** [comment]
Well happy I brought this up and gave you guys something to fix

**Comment by Slamm21** [comment]
Just clarifying, I was not accusing you of lying about him not using his 2hr. I was just pointing out that I have experienced him using it on Eden, and more than once in the same fight just like all other avatars on here.
What it says on the wiki is definitely wrong though, it should only use it once.

**Comment by MB213** [comment]
From my experience his behaviour seems to vary wildly. I've seen him not AF once and also seen him AF 6+ times in a fight. I've also seen him use TP moves as if he had huge regain i.e. no auto attacks in between.

It was reported by Pan here https://github.com/EdenServer/community/issues/566

**Comment by danismyhero** [comment]
Done this fight multiple times, have had Fenrir use 2 hour many times, multiple times like every other avatar.

**Comment by dakumauler** [comment]
For those that are continuously commenting on this open ticket that’s not the point as shown in the video it does not happen it’s inconsistent hence why it needs to be fixed it could happen in your fight it could happen another persons fight but it doesn’t happen every single person‘s fight it uses other blood packs but it’s two hour at the 50% mark and possible 30% mark Does not always happen before you make a post look at the video to understand.

**Comment by KnowOne134** [comment]
Fixed with # 1176
