### ISSUE TITLE
Hippogryph ability Fantod duration too short

### ISSUE THREAD

**Issue by Wade9363** [EdenServer/community#2320]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

When Hippogryphs in Riverne Site A-01 use Fantod the attack boost only lasts between 3-5 seconds.  This happens consistently, I have not seen it last longer than 5 seconds.  

I have not tested this on any higher level Hippogryphs or NM Hippogryphs.

![Fantod](https://user-images.githubusercontent.com/53628897/71563587-df42dd80-2a46-11ea-9bf7-34b303f110fd.PNG)

**Comment by Volkaru** [comment]
Fantod is like MNK boost. It's supposed to wear off after the next attack, but give enhanced attack.

**Comment by Wade9363** [comment]
Oh I did not know that. Pretty weak TP move.
