### ISSUE TITLE
Incorrect mob placement(Fei'Yin)

### ISSUE THREAD

**Issue by ShiyoKozuki** [EdenServer/community#2321]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

At J-7 and all the little "rooms" around it has retail monsters(and their names) instead of the monsters that were here during era.

https://ffxiclopedia.fandom.com/wiki/Experience_Points:_Guide_for_Levels_37-75?oldid=371922

This tells you that you can camp in J-7 and J-10 for fomors and ore golems, but they are not here, and only Balayang(Retail level 95+ mob), Sentient Carafes(retail level 90+ mob) and Wakufe(Retail level90+ mob) are there. You can also tell it's messed up because oldschool FFXI did not have rooms full of 6+ mobs in a tiny corridor - this is something they added post level cap increase to every zone with high level mobs as well to give people a place to level outside of abyssea.

Update notes showing that these were added in 2011
http://forum.square-enix.com/ffxi/threads/6290
Several areas will receive adjustments to monster distribution in order to cater to high-level characters.
Affected Areas:
Ranguemont Pass / Bostaunieux Oubliette / Toraimarai Canal / Zeruhn Mines / King Ranperre's Tomb / Dangruf Wadi / Inner Horutoto Ruins / Ordelle's Caves / Outer Horutoto Ruins / The Eldieme Necropolis / Gusgen Mines / Crawlers' Nest / Maze of Shakhrami / Garlaige Citadel / **Fei'Yin**

https://ffxiclopedia.fandom.com/wiki/Balayang
https://ffxiclopedia.fandom.com/wiki/Wekufe
https://ffxiclopedia.fandom.com/wiki/Sentient_Carafe

All mobs inside the red circled area mentioned above do not belong and should be replaced by level 44-46 shadows and level 43-45 ore golems(2-3 shadows per small room, ore golems and bats in the big sentient carafe room). The black X's already have ore golems in them.

https://ffxiclopedia.fandom.com/wiki/Shadow?oldid=323397
https://ffxiclopedia.fandom.com/wiki/Ore_Golem?oldid=252591
![Fei'Yin Fix](https://user-images.githubusercontent.com/58101246/71564712-4bd3d180-2a73-11ea-9ddb-5803b2b39381.jpg)

MobIDs

Balayang
17612918
17612919
17612920
17612921
17612922
17612923
17612924
17612925
17612926
17612927
17612928
17612929
17612930
17612931
17612932
17612933
17612934
17612935
17612936
17612937
17612938
17612939
17612940
17612941

Wekufe
17612882
17612883
17612884
17612885
17612886
17612887
17612888
17612889
17612902
17612903
17612904
17612905
17612914
17612915
17612916
17612917

Sentient Carafe(Might be called Droma)
17612906
17612907
17612908
17612909
17612910
17612911
17612912
17612913

Shadows(that need to be moved)
17612881
17612880
17612879
17612876
17612875
17612874
17612873
17612871

The shadows here(red circle in picture below) should be removed and put in the spots I mentioned above, as they were moved and put here when they added the 3 level90+ mobs on retail. These shadows should be replaced with triple bats(Undead bats) to be era accurate.
![Fei'yin Fix 2](https://user-images.githubusercontent.com/58101246/71567808-c90d3f80-2a8f-11ea-8ad7-ba700efed3df.jpg)

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
