### ISSUE TITLE
Charm does not bind enemies immune to charm

### ISSUE THREAD

**Issue by ShiyoKozuki** [EdenServer/community#2322]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

Charm is supposed to apply a bind effect to enemies immune to charm. This is incredibly important when soloing NM's or anything difficult that cannot be charmed. Without this it removes a big layer of depth bst can have when soloing, and makes it a lot harder to solo NM's when you run out of decent charmable monsters in the area. This effect was used for some breathing room or simply to run away - it had many uses strategically and was a nice option to have.

https://ffxiclopedia.fandom.com/wiki/Charm?oldid=366124

If this ability is used against an enemy that cannot be charmed, target will be bound for a short time. Be careful, as the mob will be considered engaged and will attack after it becomes unbound.
A non-charmable mob cannot be charmed (bound) if there is an active pet.
The ability cannot be used on an enemy that is in Call for Help status.

**Comment by Lilswitche** [comment]
It doesn't mention it on the Wiki, but from what I remember the bind time was somewhat variable and short and it's success rate wasn't 100%.  I vaguely remember seeing a BST bind/kite Kirin once and the bind didn't always land.

**Comment by ShiyoKozuki** [comment]
I see it's current implemented but the duration is less than a second. Any chance you could make the duration a bit better?

**Comment by KnowOne134** [comment]
It not active until next patch. The code I wrote up is pending
