### ISSUE TITLE
The Quest "Let Sleeping Dogs Lie" is not in the game

### ISSUE THREAD

**Issue by Althaia** [EdenServer/community#2326]
### Checklist

* [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
* [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
* [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is: Version 30181205_0

Earlier this month I noticed the lack of "Scooped!" was reported as being not in the game. It's been added in today's patch.

If it's simply a matter of reporting that a quest isn't there, there's a few other Windurst ones I'd like to see implemented...

The quest "Let Sleeping Dogs Lie" is not in the game:

https://ffxiclopedia.fandom.com/wiki/Let_Sleeping_Dogs_Lie

The apparent lack of this quest was previously reported here: #955

**Comment by ShiyoKozuki** [comment]
Please refer to this list:
https://classicffxi.fandom.com/wiki/Unavailable_Quests

**Comment by Althaia** [comment]
Yeah, I'm aware of it and have it bookmarked. In fact, it helped me determine that these quests were not in the game, rather than me specifically having a problem triggering them.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
