### ISSUE TITLE
Unable to spawn mimics in Pso'Xja with thief's tools

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#2327]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0

Currently, mimics in Pso'xja are unable to be spawned using thief's tools. Instead, they are only spawnable from using a chest key. Presumably this is a bug as this behavior is a custom fix for Eden spawn behavior. See:

Pso'Xja mimic spawn behavior
https://youtu.be/PCFOXFXM0tc
https://www.dropbox.com/s/fogs17blu41zk7z/Pso%27Xja%20mimic%20spawn%20behavior.rar?dl=0

for reference regarding expected retail behavior.

**Comment by VirtuosusFFXI** [comment]
![mimic](https://user-images.githubusercontent.com/49970272/71603878-f2c87400-2b2c-11ea-8270-131a242b4316.png)

**Comment by VirtuosusFFXI** [comment]
Montijin was able to spawn one shortly after using Pso'Xja key. Currently unsure what causes the bug in screenshot above.
