### ISSUE TITLE
Mimics to not always spawn from chests opened in Pso'xja

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#2328]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0

Currently, there is only a randomized chance of mimics spawning from pso'xja chests. Since this is a custom fix for mimic behavior for Eden, I believe this should be a guaranteed chance. Mimics in Pso'xja on retail have fixed spawn locations and respawn at static times. See:

Pso'Xja mimic spawn behavior
https://youtu.be/PCFOXFXM0tc
https://www.dropbox.com/s/fogs17blu41zk7z/Pso%27Xja%20mimic%20spawn%20behavior.rar?dl=0

for reference regarding expected retail behavior.

**Comment by Serephim** [comment]
The rate of a mimic spawning is incredibly low too, I have seen 1/19 so far and i've been here for many, many hours.
