### ISSUE TITLE
Mimics will turn hostile and aggro when you use aoe near them in Pso'xja

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#2329]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0
See title of bug report. The steps to reproduce:

1) Bring monster to a known mimic 
2) use an aoe move on top of it

This should make the mimic hostile.

**Comment by Jimmayus** [comment]
Apparently this is not a guaranteed thing. We tried to reproduce on the same chest and were unsuccessful.

**Comment by Jimmayus** [comment]
After my last update we checked all 6 mimic spawns. We were not able to aggro anymore using the above method. On the last mimic we used a pso'xja chest key and it respawned as a mimic.

**Comment by montijin** [comment]
Chip acquisition from mimics is beyond reasonable in its current state. I spent 4 hours+ with TH3 and didn't get a chip after using 25+ pso'xja keys.

**Comment by roriffxi** [comment]
Similar issue, if you /ra a mimic chest it will hit it and cause it to agro

**Comment by roriffxi** [comment]
You can actually engage and auto attack them too, seems to happen if you wait the 15-16min respawn time after killing one.  And then you can't until they 'respawn'

**Comment by Shoruto** [comment]
Created a list of all the mimic reports in #3407 including the ones mentioned in this report.  If any of you have any additional information to provide, reply to that report.  Thanks.
