### ISSUE TITLE
npcs traded gil do not function properly

### ISSUE THREAD

**Issue by Raizuo** [EdenServer/community#2332]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

NPC Amutiyaal in South Sandy no longer teleport when traded 300g. Prior to 12/30 patch, teleport worked as intended. Didn't verified if Bastok/Windy has the same issue yet.

ver 30181205_0

Update: Verified NPC Alib-Mufalib Wildcat Teleport Bastok to Whitegate and NPC Ibwam Wildcat Teleport Windy to Whitegate is also broken. Jeuno is also broken, too.

**Comment by Volkaru** [comment]
Confirmed EVERY Whitegate warp NPC from the nations is broken.

**Comment by Mozzy4Ever** [comment]
Works now
