### ISSUE TITLE
Completion of Quest Cid's Secret blocking COP 5-3 Progression

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#2335]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Cid only repeats dialogue concerning obtaining Rolanberry 874 instead of providing dialogue to begin Three Paths (5-3). Per reports on discord, completing this quest clears up the issue, but I don't believe that this unrelated bastok quest should gate CoP progress, and don't see any reports of that doing a basic search of old wiki and google.  This seems to affect anyone who has the quest already OR has never obtained the quest, as Cid's dialogue will default to starting the quest. 

Reproducable by completing promy vahzl and then speaking to cid.

**Comment by ShiyoKozuki** [comment]
According to Mozzy:
It's an issue with Cid's lua checking for Cid's Secret quest and if you have it, giving you the default dialogue. Skips over all other checks.

**Comment by jmcmorris** [comment]
This has been resolved as of the latest patch.
