### ISSUE TITLE
Mineshaft #2716 warp using Twinkbrix is not functioning

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#2336]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I was able to reproduce the non-functionality of the warp by attempting to trade 2,000 gil to the npc Twinkbrix while in possesion of the relevant key item. I had previously made use of this warp before the latest patch. The npc does not return any message when I trade him the gil, be it the correct amount or some other amount.

**Comment by Jimmayus** [comment]
https://youtu.be/XZnRqvKjg4Y

**Comment by perkuprightmeow** [comment]
To add to this - Sleakachiq is also not working. He's supposed to teleport you to the beginning of mineshaft for 800 gil. No gil taken, no dialogue (this is probably related to #2332, it seems like no gil based teleports are working, but item based teleports are).

**Comment by perkuprightmeow** [comment]
Moderately interesting note, the gambling NPC quest in S Sandy (Varchet) is functioning properly and you can trade him gil for dialogue.

**Comment by Mozzy4Ever** [comment]
From what I understand this (and the toau warp npcs) was fixed on the maintenance this morning
