### ISSUE TITLE
Pulling the Plug Undertuned

### ISSUE THREAD

**Issue by GalkaZajin** [EdenServer/community#2339]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Pulling the plug seems a little bit too easy - Only took 2 ws to kill the main receptacle (Probably should have been 3 with my gear setup)

SAM/WAR - Well Geared

https://gyazo.com/2d94fae2c8c08184a1f5dd62f9af65a9

version 30181205_0

**Comment by GalkaZajin** [comment]
Did this fight after the level increase and it still needs a lot of tuning. 

Aggro'ing the red receptacle should spawn the other receptacles, currently we have to hit it to spawn them.

The main red receptacle should be using draw in every 20 seconds. It currently does not draw in at all.

The NM that spawns from the aqua receptacle should be hitting for higher (Nearly double what he currently hits for).

From watching videos it seems like the receptacles should be using empty seed more often.

I also verified that #2448 was possible. I was given the option of being able to re-enter after already completing it. (Did not actually try to enter)


https://gyazo.com/5580d3b1afb143958dc8195c6ea6ed14

**Comment by Mozzy4Ever** [comment]
Can also confirm. Does not appear to have been adjusted. Receptacles are still as easy as they used to be. In retail from what I saw the satellite receptacles also rotated around the main, which made the empty seed spam more difficult to handle. Would often get drawn in by the main and empty seeded by the others almost right away, flinging you every which way. Then while killing your receptacle(s) of choice, the others would occasionally change position resulting in further empty spam. Currently they spawn in static positions. Always forming a triangle with the main receptacle.
