### ISSUE TITLE
CoP 5-3 A century of hardship, experience loss upon KO in battlefield

### ISSUE THREAD

**Issue by LahaEden** [EdenServer/community#2341]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

According to wiki exp loss in battlefield should not occur.
https://ffxiclopedia.fandom.com/wiki/Past_Sins_(Louverance%27s_Path)?oldid=372956

**Comment by KnowOne134** [comment]
As of 6/05/2007 no experience points loss on death

**Comment by KnowOne134** [comment]
I have been informed we go by original hard mode for cop bcnm time frame. So this way is correct
