### ISSUE TITLE
Should not receive healing magic skillups if target has full HP

### ISSUE THREAD

**Issue by lunacorn** [EdenServer/community#2342]
### Checklist

- [ x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x ] I have provided my client version in the details. (type /ver into your game window)

### Details

client ver 4.3

steps to reproduce : cast cure on full hp player while healing magic skill is uncapped

Bug : i should not skill up on full hp players ... that was changed in either WoTG or Seekers

**Comment by lunacorn** [comment]
this likely also includes enhancing magic skillups  if i can spam protect over n over though is untested

in that situation i should only skillup if they do not posses protect / shell or other bufff of equal or greater level

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
