### ISSUE TITLE
Chocobo persists through teleport

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#2343]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Bought a choco at dem, teleported myself with my alt. I was still on chocobo when I landed at holla.

Did not work teleporting to vhazl. 

Ver: 30181205_0

**Comment by KnowOne134** [comment]
issue fixed last update
