### ISSUE TITLE
Gaining Subcraft Skillups on Desynth

### ISSUE THREAD

**Issue by CdoubleOkay** [EdenServer/community#2344]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0

While lvling Smithing I was doing the Rising Sun recipe and when doing the desynth of that I was receiving skillups on my GSM as a subcraft. According to the wiki the recipe does not require GSM for desynth.
![Cdoubleokay_2020 01 01_130615](https://user-images.githubusercontent.com/29466950/71644583-c6ca0180-2c98-11ea-958a-307b91a58b86.png)

**Comment by PrettyCoolPattern** [comment]
In snyth_recipes.sql on line 3200:

```INSERT INTO `synth_recipes` VALUES (3084,0,0,0,0,0,0,51,0,87,0,4098,4240,657,745,914,0,0,0,0,0,17286,17295,17295,17295,1,1,1,1,'Rising Sun');```

Had goldsmithing 51 in there as well should be:

```INSERT INTO `synth_recipes` VALUES (3084,0,0,0,0,0,0,0,0,87,0,4098,4240,657,745,914,0,0,0,0,0,17286,17295,17295,17295,1,1,1,1,'Rising Sun');```
