### ISSUE TITLE
Mission 2-3 Dragon - Cutscenes Bugged

### ISSUE THREAD

**Issue by Althaia** [EdenServer/community#2346]
### Checklist

* [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
* [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
* [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is: Version 30181205_0

Hello, I help people with Mission 2-3 dragon a lot. This is the first time I've helped someone with it since the Dec. 30 patch.

The cutscene bugs occurred for the Giddeus dragon (Balga's Dais). We went in and for the first time ever, I saw the option to skip the opening cutscene! Which was nice, so I clicked "Yes" to skip it.

Turns out my other two party members either chose not to (Mercury) or couldn't because it was their first time doing the cutscene (Fio).

I entered the battlefield just fine, but they both got frozen in a cutscene. They had to forcequit to re-log. When they came back, they were on the battlefield with me and we proceeded through the fight with no problems.

Then we got to the ending cutscene. Mercury and I both skipped it, but since Fio couldn't...

Fio's ending cutscene featured the dragon instead of the eye; this dragon was apparently a moogle. So I guess it said something like Dark Dragon, but it looked like a Moogle.

Additionally, the ending cutscene froze up again for Fio. He forcequit to relog. When he came back, he had the necessary key item (Kindred crest). Fio is Bastokan, if it matters. Mercury and I are both Windurstian.

As you can see, I'm not Mercury or Fio, so I don't have 100% information on this or what happened to them or why, but this is everything I know.

EDIT:

This happened again in January 2020. I think it happened to the person who started the fight again, too.

**Comment by ShiyoKozuki** [comment]
Happened to me when I had retail installed due to bad DATs. Reinstall eden over your current eden install and then set fps to 30 and should fix it up.
