### ISSUE TITLE
Kaduru-Haiduru not warping after using free warp taru

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#2347]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)
30181205_0
### Details

https://ffxiclopedia.fandom.com/wiki/Kaduru-Haiduru

"If you use the services of Shihu-Danhu, Kaduru-Haiduru will refuse to warp you, even if you pay him (he won't take the coin away from you). You will know this when he comments that his magic has been replaced by "back-alley parlor tricks." To get him to warp you again, you need to wait until the next Vana'diel day after being rejected."

I've gone through 3 vanadiel day changes, trading imperial coin and he still has not warped me.

**Comment by Volkaru** [comment]
Iirc it's 3 days AFTER the day you first talked to him and he refused. Try again one more day and report back, please.

**Comment by StriderClerix** [comment]
3 game days?

**Comment by StriderClerix** [comment]
Hmm, going through the history, it says a few game days, then it says JST(I'm assuming JST midnight) -- I'll try again tomorrow morning.

**Comment by KnowOne134** [comment]
Its using wrong kind of a timestamp and should be updated

**Comment by StriderClerix** [comment]
Update:

Tried after JP midnight, still did not work.

**Comment by StriderClerix** [comment]
Tried after server reset, multiple days after first attempt, still nothing.


Have not used free taru in over a week.

**Comment by KnowOne134** [comment]
Can you make a gm ticket to correct you. Still have to work this script to fix but won't be out until next update

**Comment by KnowOne134** [comment]
You could also use the free 1 to reset your wait time
