### ISSUE TITLE
Quest an empty vessel doesnt give dialog for what he seeks after inital cs

### ISSUE THREAD

**Issue by Rocketshuttle** [EdenServer/community#2348]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by Rocketshuttle** [comment]
ver 30181205_0

When doing the quest "An Empty Vessel"  to unlock Blue Mage, friend was given only half the dialogue of the quest.  Dialogue appeared as though Dangruf Stone was the required item to continue, but the NPC does not accept the item via trade to progress.
Note timestamped 18:10:30 to see what appears to be a chunk of missing dialogue.
![KEH BLU Dialogue](https://user-images.githubusercontent.com/57078138/71648084-aec0a500-2ccd-11ea-8623-207458e2abb6.png)

**Comment by KnowOne134** [comment]
Would need to see the original al dialog to see what he said the 1st time. You can file a gm ticket to find the object he wants. 
Also the title of the issue is very lack luster
