### ISSUE TITLE
Gray Chip Lost - Shouldn't be rare update: Carmine also

### ISSUE THREAD

**Issue by Satirof** [EdenServer/community#2349]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I tried to obtain a second gray chip, however it was lost. Chips were made 'non-rare' in June 2007, which is still classified as era.

Steps: 
1: Obtain Gray Chip (#1)
2: Obtain Gray Chip (#2)
3: #2 gets automatically lost.

ver = 30181205_0

**Comment by Volkaru** [comment]
For CoP this server uses as close to original release as possible. So even if a change like chips/anima, etc not being rare is in era, it's not on this server. Chips were R/EX on release. 
https://ffxiclopedia.fandom.com/wiki/Gray_Chip?oldid=89160
