### ISSUE TITLE
ifrit double punch broken

### ISSUE THREAD

**Issue by itachioax** [EdenServer/community#2350]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
we were doin Cop 4-3(sacrarium)
then this happen
![Largheta_2020 01 01_235919](https://user-images.githubusercontent.com/12620527/71653908-7bddd780-2cf4-11ea-9f0a-e9abdda4982f.png)
![Largheta_2020 01 01_235927](https://user-images.githubusercontent.com/12620527/71653913-826c4f00-2cf4-11ea-89e6-a404d11b2050.png)

1k dmg double punch
800+

**Comment by ShiyoKozuki** [comment]
Yeah most summoner blood pacts do anywhere between 2-5x their era damage. I've seen 5.5k flaming crushes which is retail ilvl summoner damage lol

**Comment by StriderClerix** [comment]
5.5k flaming crush is era. I distinctly remember doing 4.5-6.5k on the bones outside of Full Moon Fountain.

**Comment by MB213** [comment]
1k Double Punch on an NM at level 50 does seem a bit much though. Could this have something to do with the mob being targeted here or does it hit everything this hard at 50? 

Level 70 BPs always hit low level mobs ridiculously hard.

**Comment by roriffxi** [comment]
Doing the promy vahzl fight our double punches were more in the 100-300 range.  This is likely some kind of weakness on the professors part (which may or may not be correct).
