### ISSUE TITLE
[PUP] Ice maker erases maneuvers if casting interrupted.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#2355]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

If a monster dies or the automaton gets interrupted in any way when casting, Ice maker still erases ice maneuvers. It should only erase them if a cast successfully fires. It also is getting removed with drain, which it shouldn't affect.

Also if an ice maneuver is used during cast, it's not getting eaten. I haven't tested if that's not adding to the MAB of the total nuke or not. (ex. 2x ice up, start nuke, pop third ice, nuke only eats two, leaving one left. It should be eating them all.)

EDIT: CONFIRMED If you start the cast with 2x maneuvers and use the third during cast, ice maker isn't counting it for bonus MAB. When it should.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
