### ISSUE TITLE
Can't Log In

### ISSUE THREAD

**Issue by starryarrow** [EdenServer/community#2356]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

When I try to log in it says my character is already logged in.  My Character's name is Rheya.  I have been trying to log in for over an hour.  I waited 10 minutes without boot loader open and still can't get in.  I do have the most updated loader as I was having a similar issue before and getting the new loader fixed the issue.  Now it's not working.  I logged out I guess around 5pm and tried to log in around 6pm and couldn't, with the loader giving me the issue that my character was already logged in.

**Comment by Paroj123** [comment]
I'm having the same issue, been about 2 hours now and its still saying I'm logged in.
