### ISSUE TITLE
[CoP] Omega spawning without returning you to deck

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2357]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

### Details

In the CoP Fight One to be Feared (6-4) you're supposed to be teleported off the ship after Mammets, receive full HP + MP, and be able to rebuff before going inside. Currently Omega just spawns after the last mammet nameplate disappears, warps out the one member with the killing blow, and spawns.

He does not appear to aggro until that member comes back onto the airship you engage on.

**Comment by godmode** [comment]
100% of the time?

**Comment by perkuprightmeow** [comment]
In my four fights, yes every time. The group that did it first also mentioned this.

**Comment by Garphilius** [comment]
After doing this fight multiple times, I can confirm this bug happened with our PT every single time. Further, only that one member that was ported got full HP and MP, the rest of the members that were not ported did not get full HP and MP. However, when we let said member come back to the airship, Omega did not aggro, we had to actually aggro him ourselves. For Ultima, it works as intended, warping all members and restoring full HP and MP.

**Comment by Raizuo** [comment]
First attempt. We cleared mammets then it teleported all of us straight to omega where it aggro'd and engaged us. We wiped. We never got to an empty airship after mammet clear.
