### ISSUE TITLE
[CoP] No Cutscene Pre-Tenzen Fight (The Warrior's Path)

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2358]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

### Details

No CS plays pre-Tenzen fight currently. I still have no idea why I'm fighting Tenzen.

**Comment by Garphilius** [comment]
Can confirm this with our PT experience with this fight. As soon as we went into the BC, we had option to skip or play event but no matter which option you choose, they both default to skip.

**Comment by LazarusKai** [comment]
Can confirm this still happens as of 2/1/2021. Just did the mission yesterday with my LS and we had no CS's before the one with the mothercrystal and Selh'teus.

**Comment by 59blargedy** [comment]
resolved in March 8, 2021 update
