### ISSUE TITLE
[CoP] Ru'aerns seem to be completely resistant to sleeps

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2359]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

### Details

Doesn't seem like you can sleep Ru'aerns with ES > Sleep, Sleep 2 etc. No Light based sleeps were working either. In captures, they were able to be slept.

**Comment by ShiyoKozuki** [comment]
They should have 0% dark SDT and be incredibly easy to sleep with darkness based sleeps, they are light based mobs.

**Comment by Slamm21** [comment]
they were very easy to sleep on retail
