### ISSUE TITLE
Odqan possibly not spawning properly

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#236]
Hard to verify for sure if it's been foggy weather or not yet, but he seems to just be roaming around at all times while untargetable. 
![chawlee_2018 10 25_223731](https://user-images.githubusercontent.com/40915578/47546581-c79e2100-d8a6-11e8-8b52-0e3a67e6be51.png)

**Comment by roriffxi** [comment]
Oqdan is purposely disabled because his spawn conditions are not correct.  He shows up as an untargetable cluster wandering around.

Similar to how you can see Tiamat roaming around in Attohwa but not target / get eaten by him.
