### ISSUE TITLE
[CoP] Garden of Antiquity 8-1 CS Sometimes Not Giving KI

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2360]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

### Details

Once you defeat Tenzen and get to Al'Taieu many people aren't receiving the CS or the Light of Al'Taieu. You must repeat the CS every time you zone in, and won't get the KI until you log in & out and watch the cutscene again.

**Comment by Raizuo** [comment]
I can confirm this. Upon defeated Tenzen, I and another elected to skip the long cs due there being an option to skip the event. We both appeared at Sea w/o the KI and without the Seeker of Light title, but we did receive The Chebukkis' Worst Nightmare title.

**Comment by KnowOne134** [comment]
Corrected on 7/5/2024
