### ISSUE TITLE
[CoP] Monster Ability Issues (Depuration & Vertical Cleave)

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2361]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

### Details

The move Aern Depuration is supposed to erase all effects, currently only does one. 

The BLU/Luminian move Vertical Cleave isn't going through shadows and is currently being absorbed by them.

**Comment by ShiyoKozuki** [comment]
https://www.bg-wiki.com/bg/Vertical_Cleave
This spell ignores Utsusemi shadows.

**Comment by 59blargedy** [comment]
to note - depuration will not remove status effects that are not erasable, so it's functioning with removing more than one, but it's correct behavior for it not to remove poison, blind, etc. 
It still has an incorrect message upon use which will need to be fixed at some point.
