### ISSUE TITLE
[CoP] Warped to Al'Taieu despite not being on proper place in Warrior's Path

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2362]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

### Details

Pre-Tenzen Fight (Calm Before the Storm) we had 3 people not talk to Sueleen and weren't on The Warrior's Path. They were able to enter the BCNM, clear, and teleport to Al'Taieu without being on the proper mission. 

Was tipped off to this by trying to talk to Sueleen to warp back, getting the proper CS, and repeating the fight to get clear to *actually* unlock Al'Taieu.

**Comment by Garphilius** [comment]
This happened to one of our members as well. Said member was warped to Sea without talking to the NPC near the gate at Sealion's Den. We had to do the fight again just for them.

**Comment by 59blargedy** [comment]
(hopefully) resolved in November 29, 2021 update. not an easy one to test
