### ISSUE TITLE
[CoP] Aerns dropping items pre-reraise death. 

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2363]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

### Details

Aerns aren't supposed to drop items before they reraise. Currently they do, not sure how this will apply to higher level NMs etc.

**Comment by Mikokiko** [comment]
it seems to be only happening with seals, not sure if seals should be droping from there. Cannot use signet staff in sea, so I think they shouldnt?

**Comment by VirtuosusFFXI** [comment]
![seals1](https://user-images.githubusercontent.com/49970272/71762436-209b1900-2e9d-11ea-96d9-82b76b5d295d.png)
![seals2](https://user-images.githubusercontent.com/49970272/71762437-209b1900-2e9d-11ea-8ef0-2bc03d60d6cc.png)
![seals3](https://user-images.githubusercontent.com/49970272/71762438-2133af80-2e9d-11ea-8e99-c60265ede66f.png)


I combed through a bunch of threads from era on BG and FFXIAH and found some off-handed comments of people mentioning that monsters in sea should indeed not be dropping seals. I also got confirmation from Jimmayus through retail testing that he has not gotten any seals to drop. He also observed that aerns did not drop any items until their final death.

**Comment by Jimmayus** [comment]
https://youtu.be/WCcyh0IL15k

**Comment by Balrahn** [comment]
Seeing an item drop from an aern were always a good indication that it would not reraise.

**Comment by fadingcaptain** [comment]
I agree with Mikokiko. It seems that only seals are dropping before RR. I've killed 50+ aerns and have yet to see organs/tissue drop before a RR.

**Comment by 59blargedy** [comment]
resolved with recent update
