### ISSUE TITLE
Airship battle issues

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#2364]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
1. Omega's HP pool is much higher than it should be. Per the wiki, it should be around 14k-15k HP. 
https://www.youtube.com/watch?v=o0OHUyg_0_g for reference. At 4:15 a 580 damage skewer takes off about 4%,  consistent with an HP pool of 14-15k. The eden version has far more, upwards of 35-40k.
2. Target analysis should be absorbable by shadows. Currently it strips shadows, then absorbs all buffs from everyone in range. In addition, it stacks multiple versions of the same song. For example, if 3 people have victory march song on and Omega uses target analysis, it now gets three victory march songs. 
3. Furthermore, target analysis should not steal buffs. It is only supposed to absorb attributes. 
https://www.youtube.com/watch?v=MUsEPakmsvA 2:50 for reference to see that it didn't steal any buffs, but instead put str/dex/agi etc down on the people in range. Wiki says it is similar to Diabolos's Ultimate Terror: https://ffxiclopedia.fandom.com/wiki/Ultimate_Terror
4. Omega is supposed to have a counter trait, but I didn't see it countering during the fight. Others have seen it counter though, so maybe the "front" is too small of an area.
5. Currently the en-stun seems to be near 100% proc rate. Unsure of what it actually should be, but in this video there are multiple instances of it not proccing. https://www.youtube.com/watch?v=MUsEPakmsvA 2:58 is one such instance. 
6. In the instances where we beat this BC, Omega did not use Target Analysis. I'm not sure if usage of this TP move was fixed after our first two wins or if sometimes it never uses it, but I figure I should mention that here as well.

**Comment by ShiyoKozuki** [comment]
1. The wiki is wrong, he has more than 14k hp, I watched Jimmyasus' capture and mathed it out to 16k at the very least.
4. If it's not countering it could be positional issues? You can only counter from the front. Our servers aren't as precise as SE's and it's why breath attacks from dragons can do full damage despite being on the side of them.

**Comment by Oyaziiiiiii** [comment]
It currently has far more than 16k. 16k is reasonable based on the video evidence and very close to the wiki value. I was meleeing on ninja from the front and was never countered.

**Comment by ShiyoKozuki** [comment]
I'd like to see video proof of this 35-40k amount, that's pretty absurd. Doing math on Jimmy's capture the most consistent number I got was 18k.

**Comment by Oyaziiiiiii** [comment]
I'm talking about Eden's version having close to 40k, not retail...

**Comment by Tjonke** [comment]
4. When we did the fight yesterday I kept losing shadows from Omega countering my attacks, but only while I hitting it from the front. 

5. I also got hit a few times without shadows and only got stunned twice, one was a 10s+ stun and one was more like 3-4s (blinking icon as soon as it hit me).

**Comment by Oyaziiiiiii** [comment]
After looking in my logs I did find a few instances where it didn't proc, but it still seems excessively high. Zero counters though.

**Comment by Tjonke** [comment]
Yes, the 2 counters I found in log were within like 1min of us engaging it, so I adjusted my position as soon as I saw those. And that's probably were only ones in my log for the whole fight. We also saw around 40k health based on how 432 dmg droped it 1% in health.

**Comment by ShiyoKozuki** [comment]
Please link a video showing damage done to Eden omega so we can see this 30-40k hp.

**Comment by Oyaziiiiiii** [comment]
As Toth said,  a 432 damage skill took off 1%. A 700 damage skill took off 2% in our run. That means its HP is in the ballpark of 40k

**Comment by ShiyoKozuki** [comment]
I don't see a video of 432 damage taking off 1%, or the 700 damage. You also have to look at multiple instances to get a proper HP pool, not a single one(or even two).

**Comment by montijin** [comment]
Just to add onto a different issue with the fight Ultima and Omega should both be aspirable but in my fight on Eden neither one of them gave me MP back when I used Aspir.

**Comment by Oyaziiiiiii** [comment]
> I don't see a video of 432 damage taking off 1%, or the 700 damage. You also have to look at multiple instances to get a proper HP pool, not a single one(or even two).

You don't need to see a video of this. Godmode and the other devs know exactly how much Eden Omega has, which is roughly 35-40k.

**Comment by Garphilius** [comment]
After doing this fight multiple times, we saw a similiar approximation of 35-40k HP(that OP is stating) with just simple math of 450ish damage equating to around 1％ of Omega's HP. Clearly, Omega is bugged in this fight.

**Comment by Falaras** [comment]
We just attempted it, can confirm we wiped at 60% and had done 43k damage done total that fight.  Assuming 20k of that was Mammets we had dealt 23k damage to Omega without it being below half HP.  Also the buff absorb is insane.

**Comment by Slamm21** [comment]
Now that the absorb buff is fixed, this fight is great. the HP pool is a non issue, we usually finish this fight in 25-30mins. 45 is more than enough time to deal with his hp pool.

**Comment by Mozzy4Ever** [comment]
> Now that the absorb buff is fixed, this fight is great. the HP pool is a non issue, we usually finish this fight in 25-30mins. 45 is more than enough time to deal with his hp pool.

And yet, not retail era so :P

**Comment by Shoruto** [comment]
Additional issues for PM 6-4 #2785 and #3257

**Comment by 59blargedy** [comment]
fully resolved February 15, 2021 patch
