### ISSUE TITLE
Stuck Online/Cannot Log In

### ISSUE THREAD

**Issue by Highwind5574** [EdenServer/community#2365]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
I used the "Shutdown" command in Jugner Forest a few hours ago and I am stuck online.  I do have the new Bootloader that was released.  Playing and logging on and off fine until just last night around 1am. EST Tried logging on at 4:30am. EST still online.

**Comment by setsuk0** [comment]
For this issue, I believe you need to post in tech support with your in game name and wait for a GM to boot your character offline, or do a GM call with your character name from another character if you have one.

**Comment by Highwind5574** [comment]
I see,  Unfortunately Discord will not send me a verification email so I am barred from communicating.  Is there another way to contact?

**Comment by Highwind5574** [comment]
Found a Staff Contact on the website^^  Thanks!
