### ISSUE TITLE
Desires of Emptiness forces you to do Cid's Secret quest in order to finish it

### ISSUE THREAD

**Issue by Raizuo** [EdenServer/community#2366]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently, you cannot finish Desires of Emptiness by talking to Cid in the metelworks to get the final CS in order to process to the Three Paths CoP missions. When talking to Cid, he forces you to undergo the quest Cid's Secret which has NOTHING to do with the CoP questline. I have screenshots of the kill and the CS that comes after the three NM kills. But the CS from Cid is currently unobtainable until you assumingly finish Cid's Secret first.

ver 30181205_0

**Comment by Tjonke** [comment]
https://github.com/EdenServer/community/issues/2335

**Comment by jmcmorris** [comment]
This has been resolved as of the latest patch.
