### ISSUE TITLE
[PUP] Damage Gauge + Replicator Interaction

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2367]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When the damage gauge & replicator attachments are both equipped this should cause the replicator attachment to trigger at ≤75% of the automaton's HP rather than ≤50%. This interaction does not work currently and shadows will only trigger at ≤50%.

https://ffxiclopedia.fandom.com/wiki/Replicator?oldid=375559

version 30181205_0

**Comment by Volkaru** [comment]
It doesn't seem like damage Guage has any effect on the automaton itself. It will also not cure itself at higher percentages with it equipped and light maneuvers are used, either. Referenced in #1585

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
