### ISSUE TITLE
Snoll Tzar using Hypothermal Combustion too early (PM 5-3)

### ISSUE THREAD

**Issue by MB213** [EdenServer/community#2369]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver. 30181205_0
On Snoll Tzar fight for PM 5-3 (Ulmia's Path), Hypothermal Combustion goes off too early. The NM is supposed to use this attack after 45 seconds + 20 seconds for each salt used, but when we used 1 salt the fight never lasted over 56 seconds. You can also still lose if you kill the NM before Hypothermal Combustion goes off. On another attempt where we did not use any salts, Hypothermal Combustion was used 30 seconds after the Snoll Tzar was engaged, which seems to indicate that the attack is going off 15 seconds too early.

Unsure if this is a bug, but TP also persists when you enter this fight. 

Steps to reproduce:
1) Enter Battlefield and engage Snoll Tzar
2) Use a Shu'Meyo salt on the Snoll Tzar and attack it
3) Check log for the time it takes for it to use Hypothermal Combustion

Also note that in the screenshot attached, we killed the NM but still lost. It did not successfully use Hypothermal Combustion and we were not given the message that ejects you from the battlefield, we were put back in Bearclaw Pinnacle with no completion. 

![SnollTzar](https://user-images.githubusercontent.com/37488914/71754520-a12c3a80-2eda-11ea-9a10-8bfe44525200.png)

**Comment by perkuprightmeow** [comment]
It looks like you didn't account for the era time of Shu'Meyo Salt. In era it was a ~10-12s (I think 12) charge/use time pre-CoP nerfs. 

No comment on y'all still losing despite the Hypothermal not looking like it goes off. It must have been a frame or two too late - we had Tenzen ready his auto-lose WS and still got the clear by beating him before it went off.

**Comment by MB213** [comment]
Oh if it takes 10s to use then that part about the 2nd salt can be ignored I guess. It never got around to my turn to use a salt so I was going by the Eden wiki saying it's a 1 second use. 
 
In that case the problem seems to be it's using Hypothermal Combustion at 30 seconds instead of 45 seconds. I checked wiki history and it was always 45. We did do one round where we used no salts at all and it blew up in 30 seconds.

**Comment by setsuk0** [comment]
Can confirm that this just used hypothermal combustion after 35 seconds instead of 45 seconds with us. Recorded it as well to double check the time. Replay confirms 35 seconds.

**Comment by asphodel-eden** [comment]
Hi, we are having the same issue as original poster. I was contacted in-game from GM Thefuzz who told me to post the issue here. Hypothermal Combustion went off before the 45 seconds after the Snoll Tzar was engaged. Has this been fixed at all? If not, what can we do to get past this point?

**Comment by asphodel-eden** [comment]
![C8BCB676-EF38-44FB-A630-5E928A54CBC6](https://user-images.githubusercontent.com/61460959/75248091-76a38300-57a1-11ea-80b1-9007eb743615.jpeg)

**Comment by asphodel-eden** [comment]
![C8EA5B12-7DE7-4D3C-BB0E-F5A3BB944AEA](https://user-images.githubusercontent.com/61460959/75248160-9d61b980-57a1-11ea-90b0-9f753b8687de.jpeg)

**Comment by asphodel-eden** [comment]
![0FAE5EAA-082E-4A50-9DB3-7E05EABD09AC](https://user-images.githubusercontent.com/61460959/75248185-ace10280-57a1-11ea-9d4b-abd0cb55117b.jpeg)

**Comment by setsuk0** [comment]
@asphodel-eden You can beat this despite the fight kicking you out early. We were able to do it afterwards with MNK SAM SAM BRD RDM and I forget what the 6th person was, either SAM or NIN, and all the melee just 2 hour'd. However it would be helpful for other players/party set ups if the timer were adjusted to correctly allow 45 seconds.
