### ISSUE TITLE
LL spawns?

### ISSUE THREAD

**Issue by chlorr** [EdenServer/community#237]
I came to see if all the PH's were being killed and they are. Ragtagrabbit has been here for almost 4 hours killing them all and no spawn. Just wondering if maybe something broke with the update ? or did you sneaky devs make it a true 100% lotto from the usual 45-1.5hrs he takes

**Comment by godmode** [comment]
What do you mean by “true lotto”?

**Comment by chlorr** [comment]
Well ive never seen it take more then an hour and a half, maybe a bit more. and True lotto as in, could be 3 days from now, cause its 100% random lotto

**Comment by godmode** [comment]
That’s what I figured you meant by it. This is how all lottery’s work for their end time. The “true lotto” definition comes from if the mob can spawn immediately after the first PH is killed with no cooldown period. If he’s routinely taking longer than the average times listed on wiki though there is probably something wrong. In that case average times posted here would be good data.

**Comment by chlorr** [comment]
Alright, well they were at hour 5 before they went to bed. ill ask them / the others in their home to keep notes and post here. thanks!

**Comment by godmode** [comment]
Ty. Sometimes it’s just bad luck. Please post a few different times back to back:

**Comment by Mikokiko** [comment]
I've killed him about 10 times on Eden, most of the time I was able to get him pop an hour after starting to kill PH. Longest time it took him to pop was about 6 hours.

**Comment by Mozzy4Ever** [comment]
Yup, have had it take a long time to pop before, have also had it pop on the first PH cycle after window opened. Sounds like bad luck
