### ISSUE TITLE
[ToAU]Qutrubs such as Lamia Idolator can overwrite Slow2 with Animating Wall

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2371]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

This must have started happening last couple of patches, because they were behaviing properly eariler. Properly being that Slow2 would make Animating Wall have "no effect", You can still overwrite the haste from Animating Wall with Slow2 again, no need to dispel. So shows that the haste is weaker than Slow2 and should have no effect.

**Comment by Tjonke** [comment]
Slow1 also overwrites the Animated Wall Haste.

**Comment by ShiyoKozuki** [comment]
https://ffxiclopedia.fandom.com/wiki/Animating_Wail?oldid=533734

It says the haste effect is 30%, which means it should overwrite slow1 and slow2.

**Comment by VirtuosusFFXI** [comment]
Depending on dMND, Slow II can exceed 30% easily, though I can't say whether that was the case here or not. Also, it wouldn't explain Slow 1 overwriting Animated Wail.

**Comment by KnowOne134** [comment]
closing to make 1 big report
