### ISSUE TITLE
Shiki isn't persistant or did spawn time change?

### ISSUE THREAD

**Issue by Deepupuu** [EdenServer/community#2372]
I had exact tod yesterday as 7:58:54am PST which would put shiki spawning today at 5:14:54am PST (21 hr 16min). I was there from 5:00am PST to 5:30am PST with widescan and it never popped. So either zone crashed and reset the time making it not persistant or did you guys change its spawn time to 24hr or something?

**Comment by KnowOne134** [comment]
Next update it persists. Duplicate issue

**Comment by Deepupuu** [comment]
Well it didnt repop after this maint just now so I have no idea whats going on unless spawn time changed or it got stuck in limbo.

**Comment by Deepupuu** [comment]
I killed it yesterday at exactly 7:58:54am PST just to be more clear on the subject.

**Comment by KnowOne134** [comment]
Found out that update was done yesterday. So persist is happening now. Not next update

**Comment by Deepupuu** [comment]
it spawns 21-24 hours after tod now seen it pop 24 hours after tod a couple times already this week.
