### ISSUE TITLE
Brigandish Blade should require THF to last hit with Buccaneer's Knife

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2374]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver: 30181205_0

Although I did perform a melee attack with Buccaneer's Knife at some point during the fight, our Samurai was able to kill Brigandish Blade without the knife landing the killing blow. Per the wiki and the memory of our veteran players, the THF (or more specifically the wielder of Buccaneer's Knife) should have to land the killing blow with a melee attack.

https://www.twitch.tv/videos/530834306

https://ffxiclopedia.fandom.com/wiki/Talk:Brigandish_Blade#Testimonials

**Comment by godmode** [comment]
This is likely due to some condition where the mob was already dead but showed up as alive. I’d try it without the THF hitting it or without hitting it with the appropriate weapon and see what happens. It shouldn’t die.

**Comment by E5una** [comment]
Hmmm yeah, looks like you are right, I took a screenshot from that stream I linked and looks like I did hit it at essentially the same time as the WS that killed it. 

![image](https://user-images.githubusercontent.com/13668758/71767989-1bab8900-2ee0-11ea-8d13-38169f254cb1.png)

**Comment by 59blargedy** [comment]
doesnt seem like an issue, so closing
