### ISSUE TITLE
Her Majesty's garden quest

### ISSUE THREAD

**Issue by Khabraxis** [EdenServer/community#2375]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

The Chalvatot NPC does not interact with my character at all. he doesn't tell me to go away. he doesn't initiate the quest, and he will not take the required item. 

just to be clear, I have the required fame (4). I am from Sandy. The quest has not been completed already. I do not have the quest in my active quest list. to the best of my knowledge no other quests are blocking this one from activating.

I was able to interact and complete the quest with another character.

If I click on the npc he does not respond at all. he doesn't turn around to face me. there is no text communication from the npc. 

thank you, let me know if there's any other info you need.

**Comment by Jaeral** [comment]
Just had the same bug. 
One character (Fame 5, Windurstian, Rank 3) was able to accept and finish the quest without any issue. 
The other character (Fame 7, San d'Orian, Rank 6) did not even get any dialogue from Chalvatot. 
She doesn't have the quest active or finished.

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
