### ISSUE TITLE
door to Toraimarai Canal half broken

### ISSUE THREAD

**Issue by thorules** [EdenServer/community#2376]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.) Reported before but closed in March 2019
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

Went thru Priming Gate but when you try to leave via it, you end up back in and are unable to leave

**Comment by Mahou81** [comment]
Same issue, please look into this!

**Comment by RoboRawb** [comment]
Confirming that as of today this is still broken. You cannot leave the "exit/entrance' area of this gate once you've passed through it.

If you don't have the Rhinostery Certificate you should be able to exit Toraimarai Canal through the gate, regardless. Once you have the Rhinostery Certificate you should be able to pass freely through    and out the gate, but even with such, it's still broken, never letting you exit through the gate to freely access Windurst Walls.

**Comment by slassen** [comment]
This was possible to exit but you had to be specific positions. However, I fixed it so that it should work properly now. It should be live soon pending code review.
