### ISSUE TITLE
Seigan + Third Eye not interacting correctly with multi hit moves

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#2377]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
It seems on Eden there is a 0% chance you will retain Third Eye after being hit by a Pecking Flurry or from what I can tell any multi hit move. I'll only speak to Pecking Flurry because it's the one I have the most experience with. In era/on retail right now, Pecking Flurry would be treated as a single hit absorbed by Third Eye so it was actually very unlikely to consume your entire Third Eye. On Eden even if its a 29 second Third Eye if you get hit by a Flurry you will lose Third Eye. 

Here's a picture of a friend testing it for me on retail: https://i.imgur.com/GMafJAM.jpg as you can see hit by flurry, still has TE up on buffs. 

Also the issue where multi hit WSes just go through Third Eye is still happening. Had it happen a few times last night where I had Seigan+Third Eye up, was hit with a Pecking Flurry that did full damage through them, and then anticipated the next auto attack.
 
Version 30181205_0

**Comment by ShiyoKozuki** [comment]
#2125

**Comment by PrettyCoolPattern** [comment]
scripts\globals\ability.lua
Line 534:

```
    --Handle shadows depending on shadow behaviour / skilltype
    if (shadowbehav ~= MOBPARAM_WIPE_SHADOWS and shadowbehav ~= MOBPARAM_IGNORE_SHADOWS) then --remove 'shadowbehav' shadows.

        dmg = utils.takeShadows(target, dmg, shadowbehav);

        -- dealt zero damage, so shadows took hit
        if (dmg == 0) then
            skill:setMsg(dsp.msg.basic.SHADOW_ABSORB);
            return shadowbehav;
        end

    elseif (shadowbehav == MOBPARAM_WIPE_SHADOWS) then --take em all!
        target:delStatusEffect(dsp.effect.COPY_IMAGE);
        target:delStatusEffect(dsp.effect.BLINK);
        target:delStatusEffect(dsp.effect.THIRD_EYE);
    end

    --handle Third Eye using shadowbehav as a guide
    if (skilltype == dsp.attackType.PHYSICAL and utils.thirdeye(target)) then
        skill:setMsg(dsp.msg.basic.ANTICIPATE);
        return 0;
    end

    if (skilltype == dsp.attackType.PHYSICAL) then
        dmg = target:physicalDmgTaken(dmg, skillparam);
    elseif (skilltype == dsp.attackType.MAGICAL) then
        dmg = target:magicDmgTaken(dmg);
    elseif (skilltype == dsp.attackType.BREATH) then
        dmg = target:breathDmgTaken(dmg);
    elseif (skilltype == dsp.attackType.RANGED) then
        dmg = target:rangedDmgTaken(dmg);
    end
```

Maybe this is because Third Eye is using shortcut code from Blink + Shadow Image.

If multihit ws are handled that way with blink + Shadow its likely.

Third Eye will need its own function to handle hits differently.

**Comment by 59blargedy** [comment]
should be resolved by 10/18 update
