### ISSUE TITLE
Adventuring fellow doing double WS

### ISSUE THREAD

**Issue by Xellz** [EdenServer/community#2378]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Hi, i currently am training my adventuring fellow which is lvl 34 it is a big galka healer. I've  noticed that when it does WS, it does it twice in a row, which seems odd,. anyone else noted this?

![image](https://user-images.githubusercontent.com/59521173/71774722-4d047300-2f39-11ea-8832-142bc48d8641.png)

**Comment by Mahou81** [comment]
This is still an issue. Each time my fellow does a WS it will do 2 in a row. Can we at least make them self-chain? xD

**Comment by KnowOne134** [comment]
Issue is fixed 1/4/2021
