### ISSUE TITLE
Cure V enmity

### ISSUE THREAD

**Issue by beauxq** [EdenServer/community#238]
Cure V currently giving full cure enmity.
Cure V is supposed to be a lot lower enmity.

ffxiclopedia:
The enmity received from Cure V is about equal to that of Cure III, despite the amount of HP that is recovered.
bgwiki:
This spell has significantly reduced enmity associated with casting it compared to lower tier cure spells as the enmity generated is a flat amount and not determined by the amount healed.

fix:
in scripts/globals/spells/cure_v.lua
change:
`    caster:updateEnmityFromCure(target,final)`
to:
`    caster:updateEnmityFromCure(target,180)`

**Comment by roriffxi** [comment]
Should look at cure4 too.  I'm pretty sure it's supposed to generate a flat amount of enmity as well, but it's a fairly high amount.
