### ISSUE TITLE
[PUP] AI Behavior when MP is 0/0 with Caster Heads

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2381]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When stormwaker, soulsoother, or spiritreaver heads are equipped the automaton should run into melee range to attack when it is out MP. This works correctly when it's a frame that has MP. However when you equip these heads to the valoredge or sharpshot frames and deploy within 15 yalms of a target they will follow caster behavior and remain stationary even though their MP is 0/0.

https://ffxiclopedia.fandom.com/wiki/Stormwaker_Head
https://ffxiclopedia.fandom.com/wiki/Soulsoother_Head
https://ffxiclopedia.fandom.com/wiki/Spiritreaver_Head
"Will only move if the enemy is out of casting range or when it is out of MP."

version 30181205_0

**Comment by KnowOne134** [comment]
resolved in November 29, 2021 update
