### ISSUE TITLE
Stuck in arrapago reef

### ISSUE THREAD

**Issue by Kat444** [EdenServer/community#2382]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Im in Arrapago Reef, just did the Cor hat fight to help someone. Screen went black. Logged off and back on - now everything is grey and I cant move. Logged off/on again and same thing. Can my character be unstuck please

**Comment by Volkaru** [comment]
Just type !unstuck
You'll be terrorized for 20 minutes, then automatically homepointed. This is a known issue with the COR AF hat fight. 
#1049
