### ISSUE TITLE
The Warrior's Path - Tenzen BC not wiping TP on entry

### ISSUE THREAD

**Issue by Garphilius** [EdenServer/community#2383]
### Checklist

- [check ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [check ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

TP is not lost when zoning into the BC. You can pretty much do a dry run, accumulate TP, loss the fight, retry the fight and you will have TP for massive DPS spike opening. This was also happening on Snoll Tzar. I do not recall this being possible during era.

**Comment by montijin** [comment]
Just adding that this is with all BC fights on Eden, not just CoP stuff.
