### ISSUE TITLE
Pso'xja Chests not giving map and chests not despawning after opening.

### ISSUE THREAD

**Issue by Garphilius** [EdenServer/community#2385]
### Checklist

- [Check ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ Check] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

1) Farm key (easy because high drop rate)
2) Find a chest in Pso'xja and trade the key to open it.
3) Chest opens, no map, you get Gil or Item.
4) Chest does not despawn at all.
5) Farm another key, open same chest, still no map, get Gil or item and chest still does not despawn.
6) Repeat and profit at a decent rate.

**Comment by Serephim** [comment]
Can confirm. Also makes spawning mimics for the Chips quest for the CCB Polymer Pump impossible. Trade key to chest and either got money 8/13 times and 5 times it said a mimic spawned and nothing happened and it ate my key. Super broken.
