### ISSUE TITLE
Moblin Mask Recipe Not giving Skillups

### ISSUE THREAD

**Issue by CdoubleOkay** [EdenServer/community#2386]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30191205

I am LC 26 and have been doing the moblin mask recipe, wiki has recipe at 31 LC, and synthed 12 times with no skillups. Should have a chance to get on fails as well. So I logged out and ran 24 more synths, still no skillups...
![Cdoubleokay_2020 01 06_123359](https://user-images.githubusercontent.com/29466950/71836054-294c4480-3081-11ea-8cc0-5bff60205f58.png)

**Comment by CdoubleOkay** [comment]
https://gyazo.com/ebc26ea7555c3333524ea9a5398f35e5

Eden item search has it registering as a lvl 2 synth which is incorrect according to the classic wiki
https://classicffxi.fandom.com/wiki/Moblin_Mask

**Comment by 59blargedy** [comment]
not sure where wiki got 31, but this is synthable with no LC skill in retail, and I can't find patch notes to suggest the recipe was changed at any point. If you find them, post them please, but atm assuming this is not an issue and I've changed the skill level on classic wiki to reflect.
