### ISSUE TITLE
San'dOria Mission 9-2 Cutscene Bug

### ISSUE THREAD

**Issue by Aldamiir** [EdenServer/community#2387]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
After completing the battle and following custscene in Fei Yin, I home point warped back to North San dOria and no cutscene popped. I entered the Chateau and got the cutscene that plays before the step of going to Fei Yin so can't progress correctly.

Edit: After more research, I used the summoner warp for faster FeiYin access and didn't receive the cutscene upon zoning in which I believe is the real culprit here even though it allowed me to continue onto BCNM and complete the fight even getting the post battle cutscene.

Game ver: 30181205_0

**Comment by slassen** [comment]
The new BCNM system shouldn't let you enter a BCNM you're not qualified to enter anymore. This should no longer be a problem.
