### ISSUE TITLE
Shadow Dragon not spawning

### ISSUE THREAD

**Issue by samibutera** [EdenServer/community#2389]
### Checklist

- [y] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [y] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [y] I have provided my client version in the details. (type /ver into your game window)

### Details

Client version is 30191102_1

Shadow Dragon in Xarcabard doesn't appear to be spawning.  I've spent over two hours in the zone running around looking for it and it seems like it isn't here and for the majority of those two hours I was alone in the zone as well.  It's meant to respawn every 10 minutes.  LS member came out and also couldn't find it.

**Comment by dowzer** [comment]
I might be wrong, isn’t it a 30min respawn here and 10min on retail? I couldn’t find it the other day as well but I wasn’t using wide scan.

**Comment by Tjonke** [comment]
16 minutes respawn when I camped for Biast.

**Comment by samibutera** [comment]
I was in the zone for an hour each time with no competition (no one even entering zone) and I couldn't find it personally (^:

**Comment by roriffxi** [comment]
There is definitely an issue where Shadow Dragon either stops spawning at some point (and Biast isn't up) or it may not be spawning ever at the moment.
