### ISSUE TITLE
Bastok mines elevator

### ISSUE THREAD

**Issue by Mikokiko** [EdenServer/community#239]
The south Elevator is bugging,

getting on the platform from ground level to go up, its bounce up and down while its going up. Then you cannot get off for quite some times once it reach upper floor.

**Comment by gweivyth** [comment]
These elevators are a hidden boss on all Darkstar servers. 😂

**Comment by Shuu-37** [comment]
Also experiencing this issue, quite frustrating.

**Comment by raventn** [comment]
Yea its still bounce up and down while its going up
