### ISSUE TITLE
Reraise incorrect MP cost

### ISSUE THREAD

**Issue by ShiyoKozuki** [EdenServer/community#2391]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

Reraise is 175 MP on eden, it's supposed to be 150.
https://ffxiclopedia.fandom.com/wiki/Reraise?oldid=352144

ver 30181205_0

**Comment by Setz0r** [comment]
Reraise is currently at 150, reraise 2 is at 175.

**Comment by FariskaEden** [comment]
I've noticed that when I cast reraise it'll consume 150 MP but I can only cast it when I have 175 MP or more.

**Comment by Setz0r** [comment]
it's apparently a client issue that requires modding.

**Comment by ShiyoKozuki** [comment]
Can cast with macro but cannot cast through the menu(which I use for 1 hour duration buffs) so it kinda sucks.

**Comment by KnowOne134** [comment]
Turn off all addons and plugins. AnD retry. I think I it's something stored in windower

**Comment by ShiyoKozuki** [comment]
I'm using ashita

**Comment by KnowOne134** [comment]
you didnt roll back history current retail is 150, in era its 175 for reraise 2

**Comment by Volkaru** [comment]
We're talking about Reraise ONE. It's showing 175 MP on spell list, unable to be cast with less than 175, but more than 150.
In era cost is 150: https://ffxiclopedia.fandom.com/wiki/Reraise?oldid=352144

**Comment by KnowOne134** [comment]
reraise 1 shows it needs 175 mp to cast, would need to be dat moded to fix the client limitation
typing it will work though to bypass
/ma reraise <me>

**Comment by Caelic** [comment]
For the person who does the dat mods for Eden's installer: the MP cost for Reraise 1 is in ROM/118/114.DAT under the address 0x2BBF5. This DAT has variable 8-bit rotation; the MP cost for this spot in particular is a 2-bit rotation to the right. MP cost is 16-bit so if the value is 0x00EB (175 mp) it needs to be changed to 0x00A5 (150 mp).

**Comment by KnowOne134** [comment]
I'd like to learn dat swapping. Our guy is mia.

**Comment by Caelic** [comment]
Welllll if you neeeeeedddd a guyyyy...

**Comment by KnowOne134** [comment]
Dat mod created and posted
