### ISSUE TITLE
Venessa accepts all 3 items when traded but only awards 1

### ISSUE THREAD

**Issue by CdoubleOkay** [EdenServer/community#2392]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30191205_0

Traded Venessa all 3 items from "Pulling the Plug" not thinking and she accepted all 3 but only rewarded 1. Items were removed from inventory then.
![Cdoubleokay_2020 01 08_095935](https://user-images.githubusercontent.com/29466950/71988430-e5327e80-31fd-11ea-9470-be8f229cab02.png)
![Cdoubleokay_2020 01 08_095920](https://user-images.githubusercontent.com/29466950/71988446-ed8ab980-31fd-11ea-9d5f-faefb2331788.png)

**Comment by Volkaru** [comment]
Please submit a GM ticket.

**Comment by Setz0r** [comment]
NPC script needs to be fixed to only allow 1 at a time

**Comment by CdoubleOkay** [comment]
@Volkaru I believe I submitted one via the "Contact Staff" part of the website and did an in game GM call via the Help Desk. Is there another way to submit a ticket now?
