### ISSUE TITLE
Republic Circlet's Magic Attack Bonus not active in Al'Taieu/Lumoria Region

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#2393]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

Tested nukes on Ul'Hpemde. Damage with Circlet and without Circlet were the same, indicating that the +5 MAB is not active in sea. This likely also affects other "inside/outside of Nation's control" items.

I was told to make a new bug report specifically for sea. Similar issue to #2248

**Comment by KnowOne134** [comment]
Tested in retail. The wiki is written wrong when it comes to this. Sea and dynamis will only work on latent items for items outside own nations control. Not inside
