### ISSUE TITLE
WHM bug Cure V does not work as intended

### ISSUE THREAD

**Issue by him911** [EdenServer/community#2394]
Cure V doesnt work. I get almost full enmity from the heals it delivers

Last post on this was in 2018 so im making a new one.

whm is important

thank you
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Setz0r** [comment]
Cure V is currently coded to generate:
400 CE
700 VE

per web search, that's accurate?

**Comment by ShiyoKozuki** [comment]
No.
https://www.bg-wiki.com/bg/Cure_V_(Scroll)
300 CE
600 VE

**Comment by Slamm21** [comment]
https://web.archive.org/web/20081224025202/http://kanican.livejournal.com/21727.html
400 CE/600VE is correct

**Comment by Setz0r** [comment]
i'm seeing 400/700 in several places at this point dating back to 2008, that 600 is the only outlier

**Comment by Slamm21** [comment]
https://kanican.livejournal.com/17795.html
yeah says 700 there

**Comment by beauxq** [comment]
@Setz0r 
Are you sure you looked at the code closely? When I looked at the code for Cure V enmity, there was some tricky stuff, and it did not do what it looked like it did at first glance.

**Comment by Setz0r** [comment]
i traced it from script to spellcast, i'll set a debug point later tonight and make sure that C++ code gets hit.

**Comment by beauxq** [comment]
400 CE seems like a lot.
It's a lot more than Cure IV which is usually about 260 - 290 CE.

**Comment by Setz0r** [comment]
well, all we have to go on for the time period is testing done by the community then, and multiple sources confirm the 400/700 numbers.

**Comment by Caelic** [comment]
I very often use Cure5 on Eden because it's giving way less enmity than a Cure4 from my own, very extensive, personal experience. I'm pretty sure it's fine.

**Comment by Slamm21** [comment]
@beauxq Considering the amount of hp healed, Cure V costing 400CE is very low.
Cure V is 800hp ish, which if Cure IV cured that amount would give just under 600CE and just under 2500VE.

**Comment by him911** [comment]
https://kanican.livejournal.com/21727.html

His enmity table says 400/600

**Comment by him911** [comment]
Its either that or enmity in general is off somewhere. 

I died on whm during a Tiamat fight, tossed one Cure IV on a tank the moment i was raised and was immediately targetted by tia. 
And this was 50% in with tanks that havent died from the start. Theres no way one Cure IV should top the enmity they had stacked already. Plus i got decent -enmity gear for cures

**Comment by Slamm21** [comment]
His enmity table says 600VE yeah, but the whm specific bit I linked above said 700VE so it is confusing. I'm unsure which is right.

Perhaps enmity is not wiping on death?

**Comment by Volkaru** [comment]
@him911 There are various bugs with enmity on here. The biggest being your hate table not being cleared on death sometimes. (referenced in #365 and many others)
