### ISSUE TITLE
Wyrm's Wing attacks are physical dmg instead of magical dmg

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2395]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

All wyrm's wing attacks (Tebbed Wing from Tiamat, Gregale Wing from Jormungand and Hurricane Wing from Fafnir/Nidhogg) (not faught Vrtra yet, so can't confirm at the moment) are mistakingly set as physical dmg and are reduced by -dmg taken gear and abilities such as Sentinel.

**Comment by ShiyoKozuki** [comment]
Does Utsusemi work on it?
https://ffxiclopedia.fandom.com/wiki/Hurricane_Wing Wind
https://ffxiclopedia.fandom.com/wiki/Gregale_Wing Ice
https://ffxiclopedia.fandom.com/wiki/Tebbad_Wing Fire
https://ffxiclopedia.fandom.com/wiki/Cyclone_Wing Dark

https://www.bg-wiki.com/bg/Category:Wyrm All listed here

**Comment by Tjonke** [comment]
No shadows don't work against them, but things like Umbra Cape, Darksteel set and jelly ring brings the dmg down by a lot, and sentinel almost nullifies the dmg.

**Comment by 59blargedy** [comment]
All wyrm wing attacks are coded correctly as magical. Had tester validate on test with pdt and sentinel having no effect.
