### ISSUE TITLE
Random Deal Still Resetting 2 Hours

### ISSUE THREAD

**Issue by HunnyDoo** [EdenServer/community#2397]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

v.30181205

Random Deal has a chance to reset 2 hours of your party and yourself.  I have a point in loaded deck merit, not sure if it matters.

**Comment by Volkaru** [comment]
It's a known issue. Please reply to the old closed issue, and I will re-open it. Referenced in: #1278 #2232
