### ISSUE TITLE
7 members in a party.

### ISSUE THREAD

**Issue by Spiffly** [EdenServer/community#2399]
### Checklist

- [* ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

I was invited to an XP party which somehow ended up with 7 members. Only 6 were showing up on the party list on screen bottom right, but checking the party list via the menu's showed all 7 members. The leader of the party said he had sent out multiple invites at the same time.

A couple of party members reported the party list going off screen when zoning which also happened to me. The leader decided to boot the 7th but somehow the party became disbanded. Not sure how.

We reformed as a 6 and went out and xp'ed, no issues.

![Pendulum_2020 01 08_104525](https://user-images.githubusercontent.com/59734926/72156847-6af52c00-33ae-11ea-91b3-838b6a52a667.png)

**Comment by Mozzy4Ever** [comment]
Followup on this: Can be easily duplicated by sending out 1 invite and that person not joining, then filling party up. Once that 7th person joins, they'll successfully join and their party list will bug. If any of the original 6 in party zones, their party list will also bug (Goes off the bottom of the screen). Didn't test kicking the 7th person to join, but having one of the original 6 leave the party fixed party list for everyone else.

**Comment by 59blargedy** [comment]
this issue should be fully resolved with recent updates, but please comment if you're still encountering
