### ISSUE TITLE
You can buy new xp rings even if you recharged already

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#240]
Just tossed my empty (which i recharged earlier in the week) chariot ring and picked up an empress band.

It let me do this.  It shouldn't.

**Comment by RoninXI** [comment]
you could do the same thing in retail. Recharge and purchase in the same week.

**Comment by roriffxi** [comment]
I'll do some research then. But the text when you try to purchase the same ring or recharge a second time makes it sound like you can only do it once. Maybe that only applies to when it's the same ring

**Comment by roriffxi** [comment]
https://www.ffxiah.com/forum/topic/1523/empress-band-emperor-band/
https://ffxiclopedia.fandom.com/wiki/Empress_Band

All I see is restrictions like I described.

Maybe there was a brief period of time where you could do the behavior that is happening now, but if so, it was patched and most likely not intended.

**Comment by godmode** [comment]
I'm unable to reproduce this. Can you give details like when you buy it the first time and when you repurchase?

**Comment by roriffxi** [comment]
I haven't tried to recreate it. What I did was recharge the chariots ring. Used the charges and then tossed the ring a little bit before the conquest update and tried to buy an empress. It ended up giving it to me when it shouldn't have.

**Comment by godmode** [comment]
If you get a chance to try it again let me know. Please and thanks.

**Comment by roriffxi** [comment]
I gave this another shot today and I was able to drop my empress and buy a new one after having recharged it already this week.

**Comment by Setz0r** [comment]
shits retail, don't break it!
