### ISSUE TITLE
Pukatrice Egg in game (OOE)

### ISSUE THREAD

**Issue by baggedmilk2112** [EdenServer/community#2400]
### Checklist

- [/ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [/ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Noticed this item in someones bazaar. Was not in the game until 2017 according to ( https://ffxiclopedia.fandom.com/wiki/Pukatrice_Egg?action=history ).

**Comment by 59blargedy** [comment]
appears to have been removed
