### ISSUE TITLE
Sandy Mission 2-3 problem? 

### ISSUE THREAD

**Issue by mordicai** [EdenServer/community#2401]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)  /ver.  30181205_0 

### Details

Alright so, I am doing Sandy 2-3. Did the windurst 1st route. Windy then Bastok. Got through the whole thing and died during the fight.  After the fight attempted to re-enter and the cue “curse placed upon bla bla” ... can not enter. So I go back to Bastok and talk to the 3 npc’s in order. Came back to attempt again...no go. Went all the way back to Sandy and talked to starting npc then went to windy and talked to all npc’s in order again then Bastok and talked to the people there in order...no CS, no ki’s given, last cue for what I am suppose to do is to talk to a guy ive talked to 3 times now and still cannot get selection to attempt the fight again.  My character is : Mordicai . I’ve read all I can online and can’t find a solution.

I’ve walked through the entire quest a second time to no avail.

**Comment by pyromaniackeca** [comment]
A friend and myself also finished this mission two days ago(started more than a week ago though).
We took the same route as you, died to the dragon fight twice, but had no issues retrying each time.

**Comment by mordicai** [comment]
After you did the fight were you able to click the shrine seal and it give you the option to fight again!

**Comment by pyromaniackeca** [comment]
@mordicai Yes, I was able to click the shrine and got offered the option to start the fight.

To make it as detailed as possible, after failing the fight I logged out for the day. Then the next day all I did was go back to the shrine, click on it and select the mission. This was the only option I was offered when clicking the shrine in case that effects anything.

After I got the cutscene again and the fight started. I did the same thing without any issues the next day when I finally beat it.

Outside of the above I didn't do anything else in order to reattempt the fights.

**Comment by mordicai** [comment]
> @mordicai Yes, I was able to click the shrine and got offered the option to start the fight.
> 
> To make it as detailed as possible, after failing the fight I logged out for the day. Then the next day all I did was go back to the shrine, click on it and select the mission. This was the only option I was offered when clicking the shrine in case that effects anything.
> 
> After I got the cutscene again and the fight started. I did the same thing without any issues the next day when I finally beat it.
> 
> Outside of the above I didn't do anything else in order to reattempt the fights.

Well if that’s the case then something is definitely wrong.  I did exactly as you and cannot enter to complete the mission

**Comment by 59blargedy** [comment]
having reviewed code i believe this was an individual issue related to variables and not something that happens globally, closing with 2-3 updates made april 26, 2021
