### ISSUE TITLE
Yuhtunga Mandragora using OOE abality and d/c ing party member

### ISSUE THREAD

**Issue by Fng098** [EdenServer/community#2405]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
VER 30181205_0
Mandies outside of Kazham zone seem to do a weird TP move then it d/c's a party member.  Unable to see what the TP move is.
It does not actually do the TP move, just does a weird animation then someone d/cs.
They can log right back in.

**Comment by jonip9** [comment]
I managed to capture footage of it afterall, didn't notice until after the party was done. You can see the mandy use Leaf Dagger but the animation is completely different.
[https://www.dropbox.com/s/5z58vakrtar0j7e/mandy_tp_move.mp4?dl=0](url)

**Comment by Setz0r** [comment]
I believe I have fixed this issue.  Should go live in an upcoming patch.

**Comment by Fng098** [comment]
Can you put it on the test information post on discord? It will remind me to test it tomorrow

**Comment by E5una** [comment]
Not sure if this has been fixed, but my party used to hit this bug on Mandys and Funguar when we would attempt stuns. I’m on mobile so not sure how to link tickets, but I believe #1944 is a duplicate and covers what I would have opened when we ran into this months ago.

**Comment by Setz0r** [comment]
The issue is that the interruption animation is supposed to be a "start skill" animation and right now it's set as a "finish skill" animation, which is causing unintended issues with some mobs.  I have swapped the flags, and it will be going live on the 20th.

**Comment by KnowOne134** [comment]
Stun has been reworked. Reopen report if it occurs again
