### ISSUE TITLE
[CoP] Al'taieu Map not obtainable

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#2407]
### Checklist
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

I just tried to do the quest for the Al'taieau Map to hit all 20 Quasilumin. I went through hitting all 20 twice in a row to make sure I didn't miss any and was unable to obtain the map. On the second time through I even tried not zoning/using updraft and hitting every single Quasilumin twice.

Version 30181205_0

**Comment by Tjonke** [comment]
Worked fine a few hours ago for sure

**Comment by VirtuosusFFXI** [comment]
Are you making sure to talk to the 20th one more than once? That was what did it for me a while back.

**Comment by Falaras** [comment]
I continued just rando spamming every Quasi I ran by while in Sea and it eventually worked!
