### ISSUE TITLE
[Quest] Map quest for Ulegurand Range isn't available for everyone even with prequest done

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2409]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I've tried to get the map for Ulegurande Range (Over the Hills and Far Away) since starting on the server in december 2018, I'm a mapoholic and have all others available, but have been unable to flag this quest no matter what I do, have done all prerequired quests listed (including Medicine Woman etc. that were prereqs previously). In September I got close, was able to read page 3 for the quest in the Diary in Southern San d'Oria, but now I'm back to only seeing page 1 and 2 again. I've had LS mates be able to flag the quest just fine even without completing all prerequired quests and able to complete it.

**Comment by xizeta** [comment]
As the wiki recommends, please ensure you have at least 8 reputation and the quest "A Taste for Meat" is not in a state which interferes. https://ffxiclopedia.fandom.com/wiki/Over_the_Hills_and_Far_Away

**Comment by PoppaPip** [comment]
You have to finish the entire medicine quest line (you shouldn’t have to, but you do here).

**Comment by HunnyDoo** [comment]
I have the same issue. Both my chars have rank 8 sandy reputation, a taste for meat is NOT triggered, medicine woman is in completed quests log, I've done every dialogue option Nenne has, and I've read page 1 and 2 multiple times. Neither char can read past page 2.

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
