### ISSUE TITLE
Gilfinder (sometimes?) only applying to the THF and not the rest of the party.

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#241]
I've noticed that sometimes when I farm beastmen, both of my characters will receive the increased gil from gilfinder as intended, and sometimes only the character on THF will receive the extra gil. If I remember correctly it's supposed to be multiplied before it gets split amongst the party, right?

**Comment by gweivyth** [comment]
Nope.  It adds to the Thief's total gil received, not the party.
