### ISSUE TITLE
Sacrarium Maze wrong layout on Iceday

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2412]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver: 30181205_0

The maze matches the wiki on water/light days for sure, but both times we have tried the maze on Iceday it has been the wrong configuration. It is using the windsday/darks day map on Iceday. 

https://ffxiclopedia.fandom.com/wiki/Sacrarium/Maps

Posting this from mobile, sorry if rough!

**Comment by E5una** [comment]
It seems this is intermittent. I’ve seen it wrong twice, but yesterday the maze was correct on ice day.

**Comment by Mozzy4Ever** [comment]
If the cluster crashes, I believe it gets set to a default layout and won't correct on next day change.

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
