### ISSUE TITLE
Blue magic Geist Wall is learned from wrong TP move

### ISSUE THREAD

**Issue by jonip9** [EdenServer/community#2413]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Blue magic Geist Wall is learned from the wrong Eft TP move, seemingly Cyclotail. See the screenshot. https://i.imgur.com/UuUpXzN.png
Unknown if Geist Wall itself still teaches the magic, it took me nearly 5 hours to learn the move in the first place.

How to reproduce: Try to learn Geist Wall from Efts in Bibiki Bay.
version 30181205_0

**Comment by Rocketshuttle** [comment]
Personally did learn Geist Wall from correct TP move.

**Comment by Mahou81** [comment]
I had the same issue yesterday with Pinecone Bomb. I fought a Walking Tree in Jugner Forest and it only used Entangle, but I learned Pinecone Bomb when I killed it. Admittedly, I did KO on probably the same Walking Tree just before that after it used Pinecone Bomb and then HPed, but this should not matter normally. I have no screenshot unfortunately.

**Comment by rude-jerk** [comment]
Resolved in patch on December 14, 2020.
