### ISSUE TITLE
Equipping kilo Fan into Ammo slot does not create additional wind damage when paired with Reppu Katana. 

### ISSUE THREAD

**Issue by Pugbug** [EdenServer/community#2414]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Equipping a kilo fan into ammo slot (lvl30) does not create an additional affect of wind damage when paired with reppu katana (lvl32). I have not tried with battery's or other equipment. 

Step 1 - Equip Reppu and Kilo Fan
Step 2 - Engage and fight monsters
Step 3 - Measure results - In my case no wind damage and no charged ammunition. 

https://ffxiclopedia.fandom.com/wiki/Reppu
https://ffxiclopedia.fandom.com/wiki/Charged_Ammunition 

Version 30181205_1

**Comment by Mistakeyjakey** [comment]
Having the same issue with the spark dagger

**Comment by gweivyth** [comment]
I tried to look into these when I was working on the additional effects for weapons, but it was just too complicated for me.  They're on my personal list to look at later, but I just need to learn more lua first.  :(

**Comment by 59blargedy** [comment]
resolved a few months ago with additional effect weapons changes
