### ISSUE TITLE
Drain (and presumably Drain II+Aspir) damage calculation is incorrect.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#2415]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [N/A] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently on Eden, when Drain (and I assume Drain II + Aspir) lands unresisted, it will always does full damage.  I tested this with a Pluto's staff, dark skill of 226 and on watersday with no weather. All unresisted drains equaled 280hp. This appears to be the highest possible damage according to the following formula:

0-300 skill: (Dark Magic skill + 20)*(Staff modifier)*(weather/day modifiers)

However, according to the [wiki](https://ffxiclopedia.fandom.com/wiki/Drain) and [bgwiki](https://www.bg-wiki.com/bg/Drain), drain when unresisted is supposed to do a variable amount (50% to 100% potency) based on the above mentioned formula.  So, my drains should have been doing approx 140 to 280 damage.

**Comment by Shoruto** [comment]
This is a copy and paste of joebinne's report

**Title** - Drain/Aspir/Bio unresisted while weaken. #2450

**Details**

BLM's Drain, Aspir and Bio seems to bypass weakness/double weakness status and still land "normal" damage.

**Comment by dowzer** [comment]
It is possible for Drain and Aspir to function while double weakened. Even at the lowest value of magic accuracy, they may still draw small amounts of HP/MP since magic attack/bonus don’t affect them.

To clarify, Bio damage over time is not affected while double weakened, however, the initial damage will always be zero due to magic damage/bonus being set to their lowest value.

**Comment by Slamm21** [comment]
https://irethesire.livejournal.com/2703.html
formula is here
and you can see here
http://robonosto.blogspot.com/search/label/dark%20magic
that skill capped at 300 before 2010, after 300 skill just gives magic accuracy and no damage increase
int is always magic accuracy only, no increase in damage
MAB does nothing
Plutos staff does increase damage, and so does magic bursts

**Comment by 59blargedy** [comment]
resolved in February 1, 2021 update.
