### ISSUE TITLE
Learned Blue Magic Spell without being in same zone

### ISSUE THREAD

**Issue by Rocketshuttle** [EdenServer/community#2416]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

###
![Yahehe_2020 01 13_175405](https://user-images.githubusercontent.com/57078138/72299137-f6c8bb80-362d-11ea-88f5-acb6bc4bbcb9.png)
While running through Ranguemont Pass with one party member fighting in Castle Zvahl Baileys I learned the spell "Hecatomb Wave".  I meet the requirements to learn the spell, but I should have had to be at least in the same zone.  Checked spell list, and I did in fact learn the spell.

version 30181205_0

**Comment by rude-jerk** [comment]
Resolved in patch on December 14, 2020.
