### ISSUE TITLE
Seigan + Third Eye still randomly Drops after 1 hit

### ISSUE THREAD

**Issue by TheKingOfJeuno** [EdenServer/community#2417]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
![third eye bug](https://user-images.githubusercontent.com/47612850/72299905-143e5b00-3617-11ea-9c7b-5f08fc5ca692.png)

version 30181205_0

**Comment by panfunk** [comment]
https://ffxiclopedia.fandom.com/wiki/Seigan:

"Seigan also adds a **chance** of Third Eye to remain in effect after anticipating an attack, instead of wearing off after just one."

**Comment by TheKingOfJeuno** [comment]
![eden thrid eye patch note](https://user-images.githubusercontent.com/47612850/72393002-5e424200-36e6-11ea-8e38-86b0124e2db5.png)
link it to the devs then when they made the decision to include it as a patch note

**Comment by TheKingOfJeuno** [comment]
add that ol' "Chance" part in there

**Comment by xizeta** [comment]
Before the changes, you would take damage from the hit which made Third Eye wear off. It will now always block damage on the **last** Third Eye and wear off **after** preventing damage.

**Comment by xizeta** [comment]
I'm going to close this issue. Please post a new issue if you think there is still a problem with Third Eye. Random Deal is covered by another issue, so I removed it from the title.
