### ISSUE TITLE
War merit Tomahawk is uncoded

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#2419]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by slassen** [comment]
A good test subject for this, once coded, would be Jailer of Temperance.

**Comment by rude-jerk** [comment]
Resolved in patch on December 7, 2020.
