### ISSUE TITLE
Corsair LB5 Battle Overtuned. Qultada able to WS.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#2421]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Attempted the COR LB5 fight multiple times. Every single time Qultada, even at low HP. Is pulling out 1k+ Spirits Within.
![Not right](https://user-images.githubusercontent.com/9113384/72446279-1cf27680-3768-11ea-8729-aa56c4dcccb2.png)

EDIT: I have looked over multiple guides and various videos. It doesn't look like he actually is supposed to Weapon Skill at all.
https://youtu.be/KYjormva2YU?t=450
https://youtu.be/jzJxvomKUoo?t=294
https://youtu.be/BwXR9GBOCho

**Comment by Volkaru** [comment]
Managed to barely win thanks to a massive amount of prep and luck. This was considered one of the easiest LB5s on retail. His stats and usable WS are all out of whack. 
It took Three Slug shots + quick draw to win. In retail two slug shots would have been enough.
![Arktos_2020 01 15_225338](https://user-images.githubusercontent.com/9113384/72500880-553a9900-37ea-11ea-9c79-b53157a56322.png)
He also hit me with a ridiculously powerful Savage Blade. Again, no data from any guide or video suggests he can even WS at all.

**Comment by ShadUpJoe** [comment]
Seems like Qultada have more HP than intended? Wiki says he should have about 1500 hp, I did ~1500 damage with 2ws+SC+1QD before he used wild card and hit me with a 3000TP spirits within for 870 around 45 or 55%.

This means one of two things: 

1. Spirits Within is using incorrect TP modifiers. In era, Spirits Within at 300% TP should do 15/32 of your current HP. On Retail, Spirits Within deals 100% of your current HP at 300%TP. 

2. Qultada has much more HP than intended. If a 300% TP Spirits Within deals a 870 damage, then that means that Qultada's HP when he weaponskilled me at 300% TP when he is at 45-55% HP, it would mean his current HP was around 1933 with a maximum of around 3800-4000, which is seemingly impossible.

Seeing how people in this thread have beaten the fight, I doubt he has that much HP, but both his HP and the modifier on Spirits should be checked. 

VERSION: 30181205_0
![Corsair LB5](https://user-images.githubusercontent.com/8342166/97396172-c643cc80-18a3-11eb-9653-028f9cc9cdc7.PNG)

**Comment by wargameslive** [comment]
Please note that I have gone 0/3 on this fight the last 2 days due to these bugs. It is really hurting my ability to progress/enjoy the game. I have videos of all 3 attempts if that would help in any way.

**Comment by E5una** [comment]
The last few times I've done this for people the mobs were also easily slept/silenced despite what the wiki said, so that may need to be adjusted as well. 

@wargameslive I couldn't find your discord name but I'd be happy to log in to do the fight for you if you need help with progression, message me on Discord.

**Comment by wargameslive** [comment]
> The last few times I've done this for people the mobs were also easily slept/silenced despite what the wiki said, so that may need to be adjusted as well.
> 
> @wargameslive I couldn't find your discord name but I'd be happy to log in to do the fight for you if you need help with progression, message me on Discord.

I feel like we're talking about different fights, as much as I appreciate the offer. This is the COR LB5 fight and can only be solo. :(

**Comment by E5una** [comment]
My mistake, thought it was the Hat =D

**Comment by KnowOne134** [comment]
have a hard time believing a humanoid mob cant ws. in all the videos it was killed in 2 to 4 hits so not enough tp was even given to it to produce a ws. can believe the HP is too high though

**Comment by 59blargedy** [comment]
tp moves/strength were adjusted a while back (he does and should use them) and KO fixed the last part, HP, in the November 29, 2021 update
