### ISSUE TITLE
Sandy mission 2-3 issues

### ISSUE THREAD

**Issue by mordicai** [EdenServer/community#2422]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x]I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

Version: 30181205_0

character: Mordicai

I finished the bcnm Sandy Mission 2-3 fight. Chat log states I obtained key item : Kindred crest. I checked my temp KI’s and no Kindred crest is there. 

The Npc’s I was directed to after the fight yielded no cut scenes.  This is yielding a character that is incapable of gaining rank.

**Comment by Volkaru** [comment]
This kind of issue is best put as a GM ticket, not a github post. Heard you made a GM ticket afterward. Closing.
