### ISSUE TITLE
UFOs in Sea do not move back to their spawn point.

### ISSUE THREAD

**Issue by Garphilius** [EdenServer/community#2423]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

1) Aggro a UFO.
2) Kite it to any location on the map.
3) Either die or use a rift to change locations.
4) That UFO will now be stuck there and will no roam back and fly up to it's spawn point. 

If someone was evil enough, they could train a UFO to all rifts, park them there and no one could enter Sea as they would be raped by the UFO as soon as they zoned into Sea.

**Comment by 59blargedy** [comment]
resolved a couple months ago
