### ISSUE TITLE
Blue Mage (BLU) Auto-Refresh Trait Requirements are incorrect

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2425]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver: 30181205_0

Blue mage is able to gain Auto-Refresh trait by only equipping Cold Wave + Frightful Roar + Stinking Gas. This is only "4 refresh points" out of the 8 that should be required to gain this trait. This DOES allow BLU to get access to Auto-Refresh at level 52 instead of 58, which should be the earliest that it can get it. It also allows BLU to have 4 free points. 

Here is the auto-refresh blue mage wiki page dated back to Aug 2007 (the closest date I could find to our November date)

https://ffxiclopedia.fandom.com/wiki/Auto_Refresh?oldid=328817

(I know this isn't relevant from a debug perspective, but I just want to mention that although this is wrong and needs to be fixed, BLU also can't increase its blue magic points from Assimilation merit ability since it is not working. We are sort of in a state where the two are balancing each other out for endgame BLUs, but understandably, overpowering lower level BLU mages. Sorry for the opinions, just sharing :) )

**Comment by tobioeden** [comment]
Going to bump this because I ran my mouth off about it on the BLU discord. Works from level 50 with stinking gas/frightful roar/self-destruct as well.
