### ISSUE TITLE
Wyvern Family "Dispelling Wind" TP move removing too many buffs

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#2426]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

Dispelling Wind is currently removing 3 buffs on Eden, wiki states it should only be removing 2. May need someone to verify on retail to make sure though.

**Comment by 59blargedy** [comment]
per retail testing (and blue mage learning wiki), this dispels 3 buffs.
