### ISSUE TITLE
Random Deal Still resets 2hours After the 12/30/2019 Patch

### ISSUE THREAD

**Issue by TheKingOfJeuno** [EdenServer/community#2427]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable stxeps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
youtube link provided below... short details is that you can use random deal to reset 2 hour infinitely. Its a "On Chance" proc but it can still reset 2 hour.  Below is also a link to a gyazo pic from allakazam, but do as you wish with all of it. 

Youtube link
https://www.youtube.com/watch?v=VFnFNRQvZ6s&feature=youtu.be

Gyazo link from allakazam
https://gyazo.com/c6c0243f1d80505899a0903f4a687ed4

version 30181205_0

**Comment by Volkaru** [comment]
Please search for issues before posting a new one. This has bug reports for it already with #1278 
If a closed report is still having an issue, comment on it and it will be re-opened.
