### ISSUE TITLE
Mimic in psox'ja

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#2428]
Mimic stay up after trading key.  When they respawn there is no way to claim them after 16 minutes,  someone could abuse with thief tools probably because you can trade key to all of the spawn,  cant even claim them too after it been killed once when it respawn waited 1 hours at least.

### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Shoruto** [comment]
Created a list of all the mimic reports in #3407 including this one.  If you have any additional information to provide, reply to that report.  Thanks.
