### ISSUE TITLE
Blue Mage (BLU) Ranged Physical Attack Category issue

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2429]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver: 30181208_0

There is an issue with the 3 "Ranged Physical Attack" BLU spells (Queasyshroom, Feather Storm, and Pinecone Bomb) where they are taking stats from your Ranged equipment into account. This means that casting these spells without a ranged weapon equipped results in them always doing 0 damage. Notably, when Pinecone Bomb does 0 damage, it will not attempt the sleep either.

Note: I contacted a friend on retail and had them test and validate that this is not the case on retail.

The other issue with this is that ranged weapons that are not intended to have damage values are also modifying the formula with non-zero values. My guess is that these items have placeholder values in these columns in the DB that aren't expected to be pulled (rightfully so), but are being read by the code for these 3 spells. A notable example of this is a level 20ish BLU can deal ~100-140 damage with Feather Storm instead of 1-40 with a hume fishing pole equipped (heard second hand, but my numbers were roughly +100 when I did the comparison between my Rogesturin and the Hume Fishing Rod as well on Too Weak monsters.

The link below shows the groupings of blue magic spells and you can see that these are the 3 that would be affected, and I have tested each of them individually. That link also has a damage formula for"Ranged Physical Attack" BLU spells.

https://ffxiclopedia.fandom.com/wiki/Calculating_Blue_Magic_Damage

**Comment by Setz0r** [comment]
this issue has been fixed.
