### ISSUE TITLE
Claim bug with pets caused loss of claim

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#2430]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Myself and another person (THF/BST?) were camping Citipati.  We both had Trench Antlions as pets, which use "Pit Ambush" when you use the Fight command.  It does not claim the mobs.  However, my Fight went off first, then I cast Dia II on Citipati (you can see this in the screenshot), and it did not go claimed to me.  Instead it went claimed to the other person who used Fight second.  So I lost the NM and this needs to be investigated because clearly my Dia should have claimed the mob.

![Ashton_2020 01 18_154756](https://user-images.githubusercontent.com/48332558/72670450-64e4f800-3a0b-11ea-9881-f6300ae18f35.png)

Furthermore, after I used Dia II (and it landed as per screenshot), I ran to a safe place to fight it and used Heel.  This moves the Antlion to me and puts it underground as per their AI.  Citipati chased my pet and stood where it was underground waiting for it to resurface.  the other player did not even realize they had claim because rightfully, they should not have.  

Please investigate.  Thank you.

/ver 30181205_0

**Comment by Volkaru** [comment]
This is, for the most part, retail behavior. Pets will not claim with job abilities, only an actual auto attack. An avatar will not claim with a BP, just generate a lot of hate. An automaton cannot claim with a nuke or a ranged attack, a pet will not claim with a TP move. Only an auto attack afterward, or something done by the master. So if their pet got off an AA before you, they would get claim. 

There DOES seem to be an issue if you had done that much damage, yet they claimed with a single auto attack or dia. It's supposed to be that if you had ample hate on your pet, it would take a couple actions for it to be claimed by someone else. If you can, please provide a more detailed timeline of who's pet did what action, etc.

**Comment by greyenvy** [comment]
That screenshot's all I got, sorry.  I understand the typical pet claiming behavior.  What I am stating is I used Fight and also cast Dia II on Citipati (which should claim it) and it did not claim to me.  It seems odd.

**Comment by KnowOne134** [comment]
Should be corrected in today's update
