### ISSUE TITLE
Says Character is logged on but Im not

### ISSUE THREAD

**Issue by Kat444** [EdenServer/community#2431]
It says my character is logged in but Im not (and has said that for hours). I updated my bootloader last time this happened. This time I just black screened like 4-5 hrs ago and its said that ever since. Thanks 
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Volkaru** [comment]
Please make a GM ticket, not a bug report. There is a contact option on the website, as well as a #Tech-Support channel to access in the discord.
