### ISSUE TITLE
Gusgen Mines monster respawn times

### ISSUE THREAD

**Issue by Suzarn** [EdenServer/community#2432]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
30181205_0
### Details

Many of the monsters in Gusgen have incorrect respawn times. As it is a dungeon, the spawn times should be 10 minutes at minimum. Many are 5 minutes.
https://ffxiclopedia.fandom.com/wiki/Gusgen_Mines

This is what Rockmill is supposed to be called.
https://ffxiclopedia.fandom.com/wiki/Ore_Eater

**Comment by ShiyoKozuki** [comment]
Dungeons are 15 minutes in era unless lowbie dungeons then they're ~10m generally. The lowbie dungeons are dangruf, KRT, and horototo ruins.

**Comment by Suzarn** [comment]
That is what I was trying to say. Right now, things in Gusgen respawn too quickly.

**Comment by bkesecker** [comment]
Needs an audit.  Respawn timers for lots of mobs are off.  Helpful SQL:
```sql
SELECT DISTINCT(zoneid) FROM dspdb.mob_groups WHERE respawntime = 960; -- check various values
SELECT * FROM dspdb.zone_settings WHERE zoneid IN (9,12,16,18,20,22,27,28,33,34,35,54,62,65,68,72,79,85,92,99,147,148,149,150,153,154,158,159,160,161,162,167,169,171,174,175,176,177,178,195,197,200,204,205,208,212,213,138,155,181,267,192) ORDER BY zoneid ASC; -- 106,118, not dungeons?
SELECT groupid,respawntime FROM dspdb.mob_groups WHERE zoneid IN (9,12,16,18,20,22,27,28,33,34,35,54,62,65,68,72,79,85,92,99,147,148,149,150,153,154,158,159,160,161,162,167,169,171,174,175,176,177,178,195,197,200,204,205,208,212,213,138,155,181,267,192) AND respawntime > 5 ORDER BY respawntime ASC;
```

**Comment by Suzarn** [comment]
GG. No more cheating at this camp. Thank you for fixing it.
