### ISSUE TITLE
Empress band buff dissapearing on zone

### ISSUE THREAD

**Issue by joeis78** [EdenServer/community#2435]
### Checklist

- x[ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

1) use empress band, receive exp buff
2) change zones

client version: 30181205_0

**Comment by Mozzy4Ever** [comment]
Issue fixed on the Jan 21st server restart.
