### ISSUE TITLE
Food being added and removed during zones

### ISSUE THREAD

**Issue by Satirof** [EdenServer/community#2436]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Since todays patch, every time I zone I am given a food with ~20s duration, when the subsequently wears off. Even if I have another food effect (longer duration), this new food replaces it, and causes you to lose your existing food buff.

Note: From /checkparam and checking my stats, it seems like the 20s duration food is Bream Sushi.

1. Zone
2. Find out you have food
3. Wait 20s
4. Be hungry

Option 2

1. Eat tasty things
2. Zone
3. Find out what you ate isn't actually what you ate
4. Wait 20s
5. Be Hungry

**Comment by Volkaru** [comment]
Related to #2435

**Comment by KnowOne134** [comment]
has been fixed
