### ISSUE TITLE
Ifrit's blade

### ISSUE THREAD

**Issue by alioh7** [EdenServer/community#2441]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
 been using the ifrit's blade for a long time now and havent seen its enfire effect proc. Tested on normal days,fire weather and fire day.

**Comment by Volkaru** [comment]
A lot of weapons don't have additional effects coded properly currently. There were some fixed a few months ago, but the project was abandoned.

**Comment by Volkaru** [comment]
A list and linking of bug reports for additional effects is being compiled with #1487

**Comment by gweivyth** [comment]
-----------------------------------------
-- ID: 17665
-- Item: Ifrit's Blade
-- Additional Effect: Fire Damage (Bonus based on day)
-- Numbers retail matched by Gweivyth
----------------------------------
require("scripts/globals/status")
require("scripts/globals/magic")
require("scripts/globals/weather")
require("scripts/globals/msg")
-----------------------------------

function onAdditionalEffect(player,target,damage)
    local chance = 15

    if (VanadielDayElement() == dsp.day.FIRESDAY) then
        chance = chance+6
    end

    if (math.random(0,99) >= chance) then
        return 0,0,0
    else
        local dmg = math.random(29,39)
        local params = {}
        params.bonusmab = 0
        params.includemab = false
        dmg = addBonusesAbility(player, dsp.magic.ele.FIRE, target, dmg, params)
        dmg = dmg * applyResistanceAddEffect(player,target,dsp.magic.ele.FIRE,0)
        dmg = adjustForTarget(target,dmg,dsp.magic.ele.FIRE)
        dmg = finalMagicNonSpellAdjustments(player,target,dsp.magic.ele.FIRE,dmg)

        local message = dsp.msg.basic.ADD_EFFECT_DMG
        if (dmg < 0) then
            message = dsp.msg.basic.ADD_EFFECT_HEAL
        end

        return dsp.subEffect.FIRE_DAMAGE,message,dmg
    end
end
