### ISSUE TITLE
Buffs not dropping when changing jobs at nomad moogle

### ISSUE THREAD

**Issue by MalteseFalcon** [EdenServer/community#2442]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

was on BRD with chocobo mazurka on, switched to SMN at nomad moogle and still had mazurka effect.

Ver: 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
