### ISSUE TITLE
Fold not correctly erasing longest remaining duration roll.

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#2444]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

V. 30181205_0

Fold currently works correctly when you have one roll and one FRESH bust up.

In every other scenario, Fold is not working correctly.  If you have ANY combination of rolls or busts other than having an old roll and a fresh bust, then Fold currently targets the roll or bust that you have with the shortest duration left rather than the LONGEST duration.

Quite frustrating, especially in the case of two busts, where it erases the bust with 1 minute left rather than the one with 5 minutes left. 

To reproduce: Get two rolls up and use fold.   Get two busts up and use fold.   Get an old bust up and a new roll and use fold.

**Comment by rude-jerk** [comment]
https://github.com/project-topaz/topaz/pull/1418

**Comment by rude-jerk** [comment]
Resolved in November 16, 2020 patch.
