### ISSUE TITLE
Topaz Earring Desynth not in game

### ISSUE THREAD

**Issue by Markymark674** [EdenServer/community#2447]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details
There is no topaz earring desynth when in era topaz earrings could be desynthed
https://ffxiclopedia.fandom.com/wiki/Topaz_Earring?oldid=350176

**Comment by 59blargedy** [comment]
INSERT INTO synth_recipes VALUES(0,1,0,0,0,0,0,85,0,0,0,4100,0,13318,0,0,0,0,0,0,0,789,789,746,746,1,1,1,2);
