### ISSUE TITLE
Possible to re enter Vahzl ENM after completion.

### ISSUE THREAD

**Issue by RenaviOnEden** [EdenServer/community#2448]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Completed Promyvion Vahzl ENM "Pulling the Plug" on one character solo.  Left entire Promyvion zone after completion and then re entered and ran both of my characters to the Spire in a PT.  Entered ENM on 2nd character while 1st character was still in party and zone.  Character who had already completed ENM still gained battlefield buff icon and was allowed to enter.  Did not attempt to use character who had already cleared during battle but they were in the arena.

**Comment by 59blargedy** [comment]
i believe this issue was resolved a few months ago, but please comment if it remains an issue
