### ISSUE TITLE
Mobs aggro through walls

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#2449]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
ver 30181205_0
### Details

Since the last update, mobs aggro through walls. Any solid object (walls, or monoliths in sky etc but not doors) should block all forms of aggro, including magic aggro.

**Comment by Setz0r** [comment]
revert already pushed for this error.

**Comment by Toxophile** [comment]
1/26/2020 patch notes say this issue was fixed, but it has not been fixed. I just got aggro through the floor in Beadeaux. This always happens when I walk over any of the small underground rooms around I-6/I-5/J-5.

**Comment by Volkaru** [comment]
The patch reverted to the previous system. Beadeaux has always had problems with DSP. There isn't any Z plane for aggro ranges, least on most things. So those quadavs are sound aggroing through the floor. However, it is unrelated to this bug report, and a larger issue at whole.
