### ISSUE TITLE
Crafting skill ups / Rank up bug ?

### ISSUE THREAD

**Issue by chlorr** [EdenServer/community#245]
On my alchemist, Mogget i am currently crafting venom bolt heads to skill up, I've successfully made 198, so that's 33 successful synths and 0 skill ups. 1 level short to gain skill on fails, so i can't say how many failed attempts I've made.

I've heard there was an issue with ranking up and not receiving skill ups, but the people I've asked aren't too sure if it was a bug or not.

So i did some testing, and ranked up my goldsmithing and I have gotten a .3 after the rank up.

So im not sure if there is a bug or not, but would deffs. appreciate some dev insight as to why I can't seem to skill up on Moggets Alch. and even on Chlorrs cooking (ranked up on eden to 80-90 and I've yet to get a single skill up, making multiple recopies 80-85, 20-30+ stacks of mats)

**Comment by chlorr** [comment]
just tried a different item to skill on Chlorrs Cooking, 3 stacks made and 0 skill ups again

**Comment by Xaver-Entropia** [comment]
this isn't a bug. its a matter of having touched the skill up rate multiplier for craftings.
1x doesnt mean 1x like it was on retail

**Comment by chlorr** [comment]
and how does making roughly 20-25 stacks of akamochi, at 2 per synth give not a single skill up? also 
 3 stacks of chamomile tea, and a couple stacks of sweets all withing skill up range. something is wrong.

**Comment by Xaver-Entropia** [comment]
ya, whats wrong is that 1x here means 0.5x or so of what it was in retail back then. if you burn through a couple hundred stacks u will get an skill up or 3.

**Comment by godmode** [comment]
It could be bad luck but I think it’s more than likely a bug. Chlorr what are your crafting levels? Is this at a rank cap?

**Comment by Xaver-Entropia** [comment]
i really doubt most of us are having an streak of bad luck, tbh

**Comment by godmode** [comment]
That's what I think too. Is why I think there is a bug.

**Comment by godmode** [comment]
This may be WIP. We are still trying to find the root cause of this. Please update if skill rates are far out of line of being retail accurate.
