### ISSUE TITLE
Drain/Aspir/Bio unresisted while weaken.

### ISSUE THREAD

**Issue by joebinne** [EdenServer/community#2450]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

BLM's Drain, Aspir and Bio seems to bypass weakness/double weakness status and still land "normal" damage.

**Comment by fadingcaptain** [comment]
This isn't a bug. Dark-based spells worked that way in retail too.   
 
https://www.bluegartr.com/threads/44944-Double-weakness-affects-BLM-RNG-any-other-jobs/page2

Solo strategy for Carmine Dobsonfly made use of this.   
https://ffxiclopedia.fandom.com/wiki/Carmine_Dobsonfly/Strategies?oldid=605940

**Comment by Shoruto** [comment]
I have moved this report to #2415 in it's entirety and will close this report. If you have any more information to provide please put it on the other report. Thanks
