### ISSUE TITLE
Benaige item sell list OOE error

### ISSUE THREAD

**Issue by ShiyoKozuki** [EdenServer/community#2451]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

The vendor Benaige in south sandy is selling me maple sugar. I am not a sandy citizen and according to the wiki this is not era accurate.

https://ffxiclopedia.fandom.com/wiki/Benaige?oldid=379049

>    Citizen: San d'Orians Only
>    Conquest: San d'Oria, 1st
> Cinnamon 239 - 270
> Millioncorn 44 - 49
> Maple Sugar 36 - 41

ver 30181205_0

**Comment by fadingcaptain** [comment]
I believe that's a mistake. I regularly bought maple sugar from Benaige as a cook from Windurst back in era. The same page linked above even says it's also available to all citizens:
 
Citizen: All
Conquest: San d'Oria, 1st, 2nd
Dried Marjoram 44 - 49
San d'Orian Flour 55 - 62
Maple Sugar 36 - 41

Also, there are entries in the wiki both before and after that don't list maple sugar as San d'Oria citizens only. No matter which entry you look at it always lists it as available to all citizens.

June 2007 - https://ffxiclopedia.fandom.com/wiki/Benaige?direction=prev&oldid=311010
January 2009 - https://ffxiclopedia.fandom.com/wiki/Benaige?direction=next&oldid=711942

**Comment by KnowOne134** [comment]
closing issue i see no problem
