### ISSUE TITLE
Panzer Percival and placeholder spawn behaviour incorrect. 

### ISSUE THREAD

**Issue by jamiehavok** [EdenServer/community#2453]
### Checklist

- [/] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [/] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

Go to Panzer Percivals south spawn location of jugner forest and kill the placeholder. It will always spawn in the same location except when panzer percival spawns which will allways be in the south location. 

- [/] I have provided my client version in the details. (type /ver into your game window)

v30181205_0

Panzer percival is supposed to spawn in 2 locations in jugner forest. The placeholder is supposed to alternate between locations. Also like Leaping Lizzy there is effectively 2 spawns but independant of where the placeholder spawns so if Panzer spawns in the south location it could spawn in the north location immediately after or even if you killed the ph in the opposite location. 

It is explained here https://ffxiclopedia.fandom.com/wiki/Panzer_Percival?oldid=708932

What is actually happening is that the placeholder will always spawn in the south location and panzer percival will only ever spawn in the south location. I and a few other people have witnessed this behaviour.

**Comment by Shoruto** [comment]
Additional Panzer Percival issue (in code review) #101

**Comment by Mozzy4Ever** [comment]
#101 was fixed but the issue OP speaks of isn't related. 101 was about how it wasn't lottery to begin with. Now it is, just doesn't the lottery system for it isn't setup properly.

**Comment by Shoruto** [comment]
Correct it's not the same issue but it involves the same NM that's why it's listed.

**Comment by 59blargedy** [comment]
resolved in February 22, 2021 update.
