### ISSUE TITLE
Stack of Elm Lumber acting like rare item in delivery box.

### ISSUE THREAD

**Issue by Kurtalicious** [EdenServer/community#2455]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I have a stack of elm lumber stuck in my delivery box.  It acting like a rare item "You can only hold on item of that type."  I have tried to return to sender and they get the same error.  Rito please help.

**Comment by Althaia** [comment]
My inventory was overflowing so I sent a few stacks of Beastcoins to my own delivery box. I was able to remove all but one.

On the last stack of Beastcoins, it gave me the "You can only hold on item of that type." message, like Kurt has reported above.

I think I've gotten it before when sending rusty buckets to my alt, too; that's also a case of multiples of the same item in the Delivery Box at the same time, just like my Beastcoins and just like Larry reported with his Wivre Rings #2251 

So maybe Kurt had more than one stack of Elm Lumber he was taking out at the time, too??

I dunno, just a theory. Like Kurt above, I've also tried returning it to sender to fix the error, to no avail.

**Comment by gtapperdesign** [comment]
I just got this issue on a Goshenite. I have none in my possession and my inventory is 22/30.

https://i.imgur.com/HXguzzA.png

player character: Valley

**Comment by Mahou81** [comment]
I am getting the same issue on a magic belt after sending multiple from 1 of my char to another. I can return the item to sender, but the issue remains on both characters.

**Comment by Anniakai** [comment]
I currently have two items stuck this way in my delivery box. A stack of moat carp and a stack of San d'Orean flour. So 25% of my delivery box is out of order. This makes me sad.

**Comment by bahamut44** [comment]
I have had two separate linkshell members report this with Wildgrass Seeds sending to their gardening mules. No fix or workaround found as of yet other than dropping the items and require them from the NPC. If this issue happens with a harder to acquire item then that would be a much bigger problem. I see the last post on this was from Dec 2020. I'm curious if anyone is working on it, or what progress has been made.

**Comment by KnowOne134** [comment]
Bigger issue with universal ids stored to items. Closing as its known to devs, needs gm intervention
