### ISSUE TITLE
[DRG] Super Jump & Super Climb do not avoid attacks/spells

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2457]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When a dragoon uses the ability super jump, they should not be able to be attacked by an enemy. Also, if timed correctly, a spell that's about to finish casting on the dragoon that super jumps should be interrupted. These traits should also apply to the dragoon's wyvern when it uses super climb. On Eden currently attacks and spells ignore the traits of these abilities.

https://ffxiclopedia.fandom.com/wiki/Super_Jump?oldid=312133

version 30181205_0

**Comment by Shoruto** [comment]
I have moved this report to #2194 in it's entirety and will close this report.  If you have any more information to provide please put it on the other report.  Thanks
