### ISSUE TITLE
Greater Pugils don't exist in Korroloka Tunnel

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2459]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently there are no greater pugils present in Korroloka Tunnel. They should spawn in the little puddles found in the zone.

https://ffxiclopedia.fandom.com/wiki/Korroloka_Tunnel?oldid=366350

version 30181205_0

**Comment by ShiyoKozuki** [comment]
Can confirm these exist on retail and existed in era.
This guide mentions them and shows exactly where they spawn:
http://campsitarus.blogspot.com/2006/07/23-25-korroloka-tunnel.html

**Comment by 59blargedy** [comment]
resolved september 20 update
