### ISSUE TITLE
Gate guards not deleting previous supplies

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#246]
From what I can recall, if you have supplies on you from a previous conquest week, talking to a gate guard would delete the item from your Temp Items so you could grab supplies for the current conquest week. As it is now, you have to travel to the OP that you have the old supplies for, talk to the guard there, and they'll discard them. For getting to locations like Elshimo Low/Uplands, that reeeeeally sucks....

**Comment by godmode** [comment]
This appears to be working when testing. Please reopen this issue and/or provide more detail if it hasn't been resolved.
