### ISSUE TITLE
San d'Oria Mission 3-1 Infiltrate Davoi is skippable

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2460]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently on Eden it is possible to skip this mission if you finish 2-3, rank up, and then trade enough crystals to a gate guard where you can start 3-3 Appointment to Jueno. This mission should not be able to be skipped, 3-2 is skippable but 3-1 shouldn't be.

https://ffxiclopedia.fandom.com/wiki/Infiltrate_Davoi

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
