### ISSUE TITLE
Spider Family Acid Spray isn't single target

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2461]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When spiders use acid spray, it should only affect its current target. On Eden currently it behaves like a conal attack and will affect anyone standing in front of it.

https://www.bg-wiki.com/bg/Spider_(MON)

version 30181205_0

**Comment by oo7sk8punk** [comment]
https://ffxiclopedia.fandom.com/wiki/Acid_Spray is as should be

**Comment by Volkaru** [comment]
Acid spray has always been conal. proof posted above, closing.

**Comment by FariskaEden** [comment]
When I got hit by it on retail it wasn't conal. The wiki is wrong.

**Comment by oo7sk8punk** [comment]
Current retail is wrong... Like he said things got changed

**Comment by FariskaEden** [comment]
Are there retail patch notes on this?

**Comment by FariskaEden** [comment]
https://www.youtube.com/watch?v=3AN7UrweLSY
This video is before monstrosity and shows that acid spray is not conal but single target.

**Comment by oo7sk8punk** [comment]
You mean that video where the guy dual wield k clubs... Yeah cause that's not private server footage 😏

**Comment by FariskaEden** [comment]
One of them is an octave club, you can see him showing the weapons.

**Comment by FariskaEden** [comment]
Please reopen this as the video posted shows that this is a bug.

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 (whoops) update
