### ISSUE TITLE
Aht Urhgan Attercop stun

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2464]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently on Eden Aht Urhgan Attercops are not stunned by damaging JAs, crits or weapon skills that can crit. Damaging JAs and crits should stun them for a few seconds.

https://ffxiclopedia.fandom.com/wiki/Aht_Urhgan_Attercop

version 30181205_0

**Comment by KnowOne134** [comment]
Whaaat,  I gotta see this myself

**Comment by 59blargedy** [comment]
could never replicate ws or crit stun, just the JA. Resolved that portion in June 13, 2022 update. If someone can provide vid (and preferably packets with a capture tool) of ws or crit stunning, can open a new ticket for those elements.
