### ISSUE TITLE
[COR] Choral Roll went from 8>0 after getting +4

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2465]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Was messing around with Choral Roll for fun while waiiting on a NM to pop, twice managed to go from 8 to 0 in chat log even after getting a IV (4) which should bust me.
![Toth_2020 01 29_235605](https://user-images.githubusercontent.com/9790100/73405127-7378bc80-42f3-11ea-816c-8746fea29ca8.png)

**Comment by 59blargedy** [comment]
dont believe this occurs after roll overhauls
