### ISSUE TITLE
Anubis's Knife not working

### ISSUE THREAD

**Issue by Wannaspoon** [EdenServer/community#2467]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

When attempting to use the enchantment of Anubis's Knife I receive the message "Unable to use item."

**Comment by Volkaru** [comment]
Linking to #1487

**Comment by Wannaspoon** [comment]
This is not an additional effect weapon, it's an enchanted weapon that applies poison to self.  https://ffxiclopedia.fandom.com/wiki/Anubis's_Knife
