### ISSUE TITLE
Taking damage did not interrupt dialog

### ISSUE THREAD

**Issue by Khessed** [EdenServer/community#2469]
### Checklist

- [v] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [v] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [v] I have provided my client version in the details. (type /ver into your game window)

### Details
client version 30181205_0

I ran to the Outpost in Valkrum Dunes and talked to the NPC that allows you to warp back to your home nation. While this dialog was open, I had pulled aggro from a goblin that started beating me up. At some point, I had noticed my HP was at 0, but my character was still alive and talking to the NPC. I was able to warp back to town without the dialog or my choices getting interrupted by the goblin attack. After warping succesfully, I loaded into Port Windurst, dead. As far as I'm aware, the Goblin's attack should've interrupted dialog/the choice menu.

**Comment by 59blargedy** [comment]
resolved in october 11 update
