### ISSUE TITLE
Skillchain damage may be incorrect on HNM

### ISSUE THREAD

**Issue by SBC-Nyxai** [EdenServer/community#2471]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

On Cerberus, darkness was hitting for 10% of the closing WS damage. A 800 mercy stroke would close darkness for ~80 damage.

On Hydra, darkness was also hitting for 10% of the closing WS damage. A double darkness skillchain closed by Mercy Stroke which should deal 1.5x of WS damage (800+) hit for ~120. 

Not sure if it is intended for darkness to be reduced by magic resist values or if there is a decimal misplaced. At least 30 darkness were closed on Cerb and it was 10% of the damage every time. 

Client version 30181205_0

**Comment by SBC-Nyxai** [comment]
Additionally, darkness was doing full damage on Faf today, so it seems like maybe there is a problem with ToAU skillchain damage on kings?

**Comment by 59blargedy** [comment]
i think with mhit changes, this most likely is no longer an issue. Though i do think that skillchain dmg in general still needs looking at, it's not for this specific reason so closing this specific issue
