### ISSUE TITLE
Compliments to the Chef - NM drops break item

### ISSUE THREAD

**Issue by bootseden** [EdenServer/community#2472]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

the angler orobon in the isnm compliments to the chef drops orobon lure(s) when its lure is broken after it is killed, it should not reward this item

https://ffxiclopedia.fandom.com/wiki/Compliments_to_the_Chef
https://ffxiclopedia.fandom.com/wiki/Angler_Orobon
https://www.youtube.com/watch?v=N0eEbvMXKVM (shows lure broken and no lure rewarded after it is killed)

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
