### ISSUE TITLE
Bin Stehihna (Windurst Vendor: Zulkheim) unable to Buy or Sell

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#2474]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version: 30181205_0

Bin Stejihna (G-8) Windurst Woods
Type: Regional Vendor NPC
Region: Zulkheim

Issue: Approached this vendor to buy some materials after maintenance.  Buy or Sell options did not appear.

Windurst is currently in control of this region.  It was working prior to the server maintenance around 7:00AM Thursday 2/19.  After the servers came back up this NPC would only provide default shop text and then nothing else would happen.

Checked other vendors in the same zone, they appeared to work. 
Checked another regional vendor for a different region in Port Windurst outside the Mog House and it worked.

**Comment by DeuceFFXI** [comment]
Issue seems to have resolved itself.

**Comment by Shika10** [comment]
As of 4/12/2020, this issue is back.
