### ISSUE TITLE
Cerberus / Khimaira / (likely hydra?) draw-in function

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#2476]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

Cerb/Khim's draw-in mechanics were changed to be more accurate (drawing in to spawn point) and it is functioning well in that regard but right now, they also have regional/group draw in (think KV or the 55 limit break NMs in Xarcabard) and should not have this.

You can effectively draw in party members from the zone line at this point which is broken and completely negates camping the NM if you can just do it with a level 1 mule.

**Comment by 59blargedy** [comment]
should be resolved with 5/16 patch, please comment if it remains an issue

**Comment by Oyaziiiiiii** [comment]
Khimaira doesn't seem to be drawing in anymore. It was pulled all the way up the ramp nearly to the entrance corridor entrance and didn't draw in. The highest threat target also got at least 30 yalms of separation and it still didn't draw in.
