### ISSUE TITLE
Soporific recast too short

### ISSUE THREAD

**Issue by Satirof** [EdenServer/community#2477]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Based on FFXI wiki Soporific (BLU sleepga II) should have a recast of 90 seconds. However on Eden it only has a 26 second recast (while naked, no fast cast traits).

Originally at BLU release it was a 26 second recast, but in November 2006 it was changed to 90 second. So really depends on if Eden is balancing classes based on just before WotG release (2007), or when the job was first implemented.

Steps:
1: Cast soporific
2: Notice recast is 26 seconds

**Comment by Satirof** [comment]
Didn't realise I didn't post the wiki links

[26s Recast](https://ffxiclopedia.fandom.com/wiki/Soporific?direction=prev&oldid=165614)

[90s Recast updated](https://ffxiclopedia.fandom.com/wiki/Soporific?oldid=167711)

There is also [wiki update inbetween these](https://ffxiclopedia.fandom.com/wiki/Soporific?direction=prev&oldid=167711) before the new recast was found, so the patch should be around that date.

**Comment by KnowOne134** [comment]
duplicate, and fixed

**Comment by KnowOne134** [comment]
Issue fixed next update
