### ISSUE TITLE
Buche au Chocolat does not provide group food effect

### ISSUE THREAD

**Issue by rpcon** [EdenServer/community#2478]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

This food affects the user but not other party members, although an aoe marker does appear when it's used.

**Comment by Bushawg** [comment]
Yogurt Cake is a group food, but it doesn't share with the group.  I haven't checked the other Group Foods yet.  Thanks!

**Comment by 59blargedy** [comment]
resolved in February 8, 2021 update
