### ISSUE TITLE
Killer effect not assigned to jug pets

### ISSUE THREAD

**Issue by boh1788** [EdenServer/community#2479]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by mlandrum22** [comment]
Same thing using lizards vs. bees. Had a party of 4 BST and all using lizards, never intimidated once the whole time.

Not sure if the extra damage works or not. That's kind of hard to test.

**Comment by mlandrum22** [comment]
Jug pets CAN be intimidated by mobs, however.

**Comment by mlandrum22** [comment]
Wonder if this was broken when Killer Instinct was fixed. 

But this is kind of a big deal for BST who chose their pets based on their enemies. Especially since it works in the wrong direction.

**Comment by Shoruto** [comment]
I have moved this report to #1309 in it's entirety and will close this report. If you have any more information to provide please put it on the other report. Thanks

**Comment by rude-jerk** [comment]
Resurrecting this as it's independently achievable on a shorter timeframe than the issue it was merged into.

**Comment by rude-jerk** [comment]
Resolved in November 16, 2020 patch.
