### ISSUE TITLE
Blunderbuss is out if ah, but Recipe still on

### ISSUE THREAD

**Issue by dpmannoroth** [EdenServer/community#2481]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Trying skill Smithing i make this synth, last night, its works and be success but its out of ah.

**Comment by bkesecker** [comment]
Thanks for the report.  Out of era item is able to be crafted.

**Comment by dpmannoroth** [comment]
Then can i use it?
