### ISSUE TITLE
Multiple characters are able to fish a single instanced monster at one time.

### ISSUE THREAD

**Issue by danismyhero** [EdenServer/community#2483]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver 30181205_0

I would imagine this able to be done with any mob, but most easily recreated with fished up monsters that have a single entry in the zone DB, like Devil Manta in Kuftal.

It is possible for multiple fishers to 'claim' this mob in a fishing sequence, and if both are successful at catching it, the last person to complete the sequence will get final claim of the monster.  This results in the monster being teleported to that person, regardless of it's position, engagement status (such as claimed to another party), etc.

The mob will go to claimed status of the last person to finish fishing it.
![Devil Manta](https://user-images.githubusercontent.com/49649778/75163381-bc4e4600-56e4-11ea-88fc-81b1790ea162.png)

**Comment by Mozzy4Ever** [comment]
Still possible. If 2 people have same mob on their hook, last person to fish it up will steal claim.

**Comment by Setz0r** [comment]
this issue has been fixed
