### ISSUE TITLE
[BRD] Army's Paeon V missing

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2487]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Army's Paeon V (level (level 65 Bard) is unavailable, the spell simply doesn't drop from the Sahagin like it's supposed to. And the spell is an integral part of Bard's Maat fight

**Comment by setsuk0** [comment]
The first update I see on the wiki of this dropping from the sahagin is June 28, 2014. Prior to this, it shows it only dropped from the ENMs "Like the Wind" and "Shell we dance?" I'm unable to find a source for this dropping off sahagin prior to 2014.

**Comment by KnowOne134** [comment]
The enm will have to he coded, currently 1 of these is in the works
