### ISSUE TITLE
An empty vessel (BLU unlock quest requested item issue)

### ISSUE THREAD

**Issue by Mahou81** [EdenServer/community#2488]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Today I started An Empty Vessel. When I talked to Waoud in Whitegate and answered all the questions according to the wiki, he clearly talked about the siren's tear being the item he needed (unfortunately no screeshot due to server reset around this time due to searcvh and ah issues, FEB 26th 16:00-17:00 EST). After waiting 1 game day as described by the wiki, I talked to Waoud again and he suddenly mentioned the description for the Dangruf Stone. So I went out and got the stone, but nothing happened when I tried to trade it with Waoud. Remembering him mentioning the sires tear in the ialogue before the 1 game day wait, I went to get the tear and sure enough, when I traded it to Waoud he accepted it and let me continue the quest. TLDR: Waoud mentioned sirens tear at first, but then asked for Dangruf stone. He didnt accept Dangruf stone, but sirens tear worked in the end. Dialogue might need to be fixed.
Edit: Version: 30181205_0

I have screenshots of him asking for the dangruf stone and then accepting the sirens tear if needed.

**Comment by KnowOne134** [comment]
Duplicate issue that's open. Code to fix should be in next update. Can open a gm ticket to find what the real item is that he wants

**Comment by raventn** [comment]
It seems to be bugging out again dungeruf stone is actully a Sirens tear ....

**Comment by KnowOne134** [comment]
What was the text given when triggering him?

**Comment by perkuprightmeow** [comment]
I helped with this -- Waoud was giving him dialogue / reminder to bring Dangruf Stone. EmptyVesselStone check was returning 576 instead of 553 to match with dialogue. 

Was able to change Stone var to 553 and he was able to turn in normally.

**Comment by Nyur0** [comment]
Bump.

Just tried unlocking BLU myself.. Seem to be running into the same issue. Waoud asks for Dangruf Stone. I farmed the stone, went to trade, and nothing. Upon then following the info from this thread and hunting down the Siren's Tear, he proceeded the quest:

https://imgur.com/a/m6zzn1d
https://imgur.com/a/leK1JJQ

Confirming that the dialogue may need some tweaking.

**Comment by him911** [comment]
This is still bugged. Dangruf stone not accepted by Waoud when he asks for it, instead having to trade him a sirens tear to continue with the quest.

**Comment by falzum** [comment]
For what it's worth, I got him to accept my dangruf stone after clicking the option to restart the quest and talking to him.

**Comment by E5una** [comment]
Just wanted to add this here for other future BLUs that might be having issues with this quest. It looks like the Sunsands branch of the quest works properly if he asks you for that, but requires you to zone after a day passes. Hope this helps someone.

![image](https://user-images.githubusercontent.com/13668758/97180817-ede64800-1770-11eb-9644-a50d0f92404a.png)
