### ISSUE TITLE
Quickdraw not working : only able to use 1 charge out of the 2.

### ISSUE THREAD

**Issue by Danebstar** [EdenServer/community#2490]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

use quick draw , see the timer , see your charges , cant wont go off if 1 chaarge is left , but will when 2. 

- [x] I have provided my client version in the details. (type /ver into your game window)

30181205_0

### Details
Quickdraw not working as it should.

**Comment by Danebstar** [comment]
Ty

**Comment by KnowOne134** [comment]
Its work for the in era. In 2007 you only had 1 charge every 60 seconds
