### ISSUE TITLE
Bundling twine sale says 99. 

### ISSUE THREAD

**Issue by Kikuichimoji** [EdenServer/community#2491]
When buying Bundling twine the sale says 99. Only sells 12 and charges you for 12. Tried buying a few times and changed zones, but it persisted.

Ver. 30200205_1

### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

**Comment by 59blargedy** [comment]
im not encountering this with either bundling twine npc, looks like the version you had was from another ps and i didnt see at the time. closing out, thanks!
