### ISSUE TITLE
Monsters do not regen mp outside of battle

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2492]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Monsters with MP are not regenerating their MP outside of battle. This means that casts a buff on itself will eventually run out of MP if left alone for long enough. As a blue mage that relies on MP Drainkiss I run into this CONSTANTLY.

Another related bug, that doesn't need to be fixed if we fix this first issue, is that if you aggro a mage that is out of mp, they will not engage in melee with you until you engage in melee with them. They will stand at a distance and it seems their AI is in "casting mode" even though they have no MP to cast spells. FYI this part I'm reporting second hand through multiple stories and discord screenshots, I have not experienced this or sought it out.

IIRC, monsters should not run themselves out of MP, but I would need someone else to give their input that is more knowledgeable about retail/era. I personally never remember running into a monster that ran itself out of MP on buffs.

Version: 30181205_0

**Comment by E5una** [comment]
Maybe in retail they just would stop casting buffs if their MP got low enough. Sorry that I don't have any more insight into their MP conservation.

**Comment by KnowOne134** [comment]
Will look at it
