### ISSUE TITLE
The Missing Piece (Rabao): Alfesar - [Teleport-Altep Quest] Dialogue Missing

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#2493]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Zone: Rabao
NPC: Alfesar (H-7)
Quest: The Missing Piece
Issue: Key Item name "Ancient tablet fragment" is missing from the quest dialogue.  It simply displays a space at the end of the sentence prior to a period.

**Comment by DeuceFFXI** [comment]
Also, ??? for key item does not depop and move to another location after being examined once as it should.  I noticed this same issue with the quests for Teleport-Dem, and Teleport-Holla.  Altana's Sorrow and Healing the Land respectively.

**Comment by 59blargedy** [comment]
resolved in January 4, 2021 patch
