### ISSUE TITLE
Unable to remove Maple Table from Mog House

### ISSUE THREAD

**Issue by Spiffly** [EdenServer/community#2494]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

I've had a maple table in my Mog House with 10 brass flowerpots on it for months. Decided to remove them as i want to re-roll the mule in a different city.  The pots i was able to 'remove' under the 'layout' tab with no issues. I'm unable to remove the maple table. The 'remove' option always stays greyed out.

Tried relogging, moving it around, zoning and re-placing/re-removing pots on it and made no difference.

/ver - 30181205_0

**Comment by 59blargedy** [comment]
is this still an issue?

**Comment by Spiffly** [comment]
Sorry i thought i had closed this issue. It was never an issue, just me being dense. Can't remove furniture if you have items in storage.
