### ISSUE TITLE
[Dynamis] Attestation mobs dropping multiples/too many

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#2495]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

The attestation mobs in Dynamis are dropping more than one attestation and can drop duplicate. This is not era accurate.  

Attestation mobs should only be able to drop 1 attestation (the first slot is shared by the ones it is supposed to drop) with the exception of Goublefaupe who can also drop Attestation of Invulnerability in a slot all on its own (so it can drop Glory/Force/Righteousness + Invuln).   

Here are screenshots of the loot pools being way off:

Velosareon dropping two attestations (should only drop one).
![Ashton_2020 02 26_224609](https://user-images.githubusercontent.com/48332558/75600675-14d46900-5a80-11ea-9d4c-c3370603fec2.png)
Goublefaupe dropping TWO glory and then invulnerability.  It should never drop slot1 attestations.
![Ashton_2020 02 26_231026](https://user-images.githubusercontent.com/48332558/75600672-0f771e80-5a80-11ea-9bf8-5fb97a63bf0c.png)

Not sure why this has gone unreported for so long when there are clearly multiple relics already made lol

**Comment by icariumkupo** [comment]
#1916 related

**Comment by roriffxi** [comment]
https://ffxiclopedia.fandom.com/wiki/Mildaunegeux?oldid=892105
https://ffxiclopedia.fandom.com/wiki/Quiebitiel?oldid=893509
https://ffxiclopedia.fandom.com/wiki/Velosareon?oldid=881483
https://ffxiclopedia.fandom.com/wiki/Goublefaupe?oldid=816131

From 2009, states multiple attestations can be dropped.  Goublefaupe is the only one that specifically points out the shield being able to drop along side the "guaranteed weapon drop". 

Dynamis overhaul happened in 2011, so it being in the 2009 wiki means it was at least added during the more old school version of dynamis.

There are no mentions in the wiki / comments stating "only 1 attestation pops" that I saw until it was updated in 2009 and a search of the patch notes around that time period don't make any mention of Dynamis changes.

https://www.bg-wiki.com/bg/Category:Update_History#April_8.2C_2009

I'm not saying you're necessarily wrong, but there is evidence that you are while you have provided no evidence that you're right and so maybe you shouldn't make statements like:
"Not sure why this has gone unreported for so long when there are clearly multiple relics already made lol"

**Comment by roriffxi** [comment]
http://ffxidb.com/zones/134/dagourmarche

But looking at this data definitely suggests its 1.  Since if you add up all drops it is almost exactly equal to the number of kills (off by 1, which could be explained by someone already having the test that was chosen and causing a "no drop").

I would find it weird to believe SE would restrict it down to a single drop when it was previously a multiple drop.

**Comment by greyenvy** [comment]
It was only one attestation in era, with the exception of Goublefaupe as I stated above.  I led a linkshell that made a dozen relics prior to 2009.  That is how it always was.  I can go find some additional evidence but I bet if you asked on the BG discord all the old school players will tell you that is how it was.

If there are era players here, they'd know that too and it should have been reported.

**Comment by gweivyth** [comment]
Also ran a linkshell that made multiple relics pre-2008, never saw multiple Attensations drop ever.  Don't do Dynamis on Eden so don't know how often/if it happens here, but if it is, it shouldn't be.  

I actually don't even remember Goublefaupe dropping multiples, but we also could have just been unlucky.

**Comment by Raphtalia1** [comment]
The multiple attestations update happened in late 2008, when they increased drop rates in both Xarcabard and Beucedine, previously only the relic shield had a chance to drop alongside the one of the other drops

**Comment by greyenvy** [comment]
Glad we could clear that up.

**Comment by Volkaru** [comment]
Related to #2841

**Comment by Mozzy4Ever** [comment]
From what I could tell from the (brief) testing I did in #2841 , it seems like there's 4 rolls when Goublefaupe dies. 1 roll where each attestation is a 33% drop chance. A 2nd roll where you can get the  same attestations, but they have a lower chance to drop and you can get a "nothing" drop. A 3rd roll for if you get the shield attestation which seems to have a lower chance than it should. Seems to have a ~10% rate, should be around 33%. Then a 4th roll for if you get any of the 3 currencies. 

From the various research that myself and others above have done, it should be 2 rolls. 1 roll of the three 33% chance attestations, with the last 1% being a montiont. Then a 2nd roll of 33ish% chance of shield. 1st roll for currency could be a .33% chance of any of the 100s, with .01% nothing? Someone on BG mentioned getting nothing from Gouble but didn't give a screenshot.

**Comment by bkesecker** [comment]
Some of these are absolutely the wrong rarity (guaranteed)
```sql
SELECT itemId,rarity FROM dspdb.mob_droplist WHERE itemId BETWEEN 1556 AND 1569; -- Attestations
```
