### ISSUE TITLE
Selbina boat does not appear

### ISSUE THREAD

**Issue by Bjuglez** [EdenServer/community#2496]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

The ship does not appear in selbina waited for it 5-6 times. cant progress since i need to get to windurst <.<
And sorry if this is issue is perhaps known but all posts i found were about the ship appearing and people teleporting but in this one the ship just does not come.

**Comment by Lexxi-foxxx** [comment]
I'd like to add that both of the ships do not show up in Mhaura. I have checked off and on all day as I have been trying to get to Whitegate for the first time.

**Comment by Fayru44** [comment]
Airships aren't showing up either, waited for the Kazham one for 2-3 rotations but no luck.

**Comment by bkesecker** [comment]
@Bjuglez If this issues is resolved, please close.  The cause was because I adjusted cluster distribution, and some zones that needed to be on the same cluster were not.

**Comment by Bjuglez** [comment]
its resolved thanks
