### ISSUE TITLE
Windurst 5-2 The Shadows Await

### ISSUE THREAD

**Issue by nxetrilla** [EdenServer/community#2497]
### Checklist

- [/] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [/] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30200217_0
When receiving the cutscene for 5-2 at the door in the Throne Room it begins the cut scene, but then your character will just continue to run into the door.  Issue happens on non-retail clients too (^: Using prt scrn does not fix the problem and you'll be stuck until you force close your client. Maven posted a video of what happens in tech-support channel as well.  

https://cdn.discordapp.com/attachments/496834102666723339/683493135493627941/VID_20200229_154034_LS.mp4

**Comment by 59blargedy** [comment]
have not been able to replicate this unless on a different version, as the ids have shifted and the door stays closed as a result. using eden install does not seem to encounter this issue, so closing.
