### ISSUE TITLE
Mobs in Dunes despawn seemingly at random

### ISSUE THREAD

**Issue by Fayru44** [EdenServer/community#2498]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver 30181205_0

**Comment by Slamm21** [comment]
@Fayru44 You ticked the first checkbox yet don't seem to have searched for it?
Thanks for reporting but please make sure to check in future.
https://github.com/EdenServer/community/issues/1442

**Comment by KnowOne134** [comment]
duplicate
