### ISSUE TITLE
RDM missing Magic Attack Bonus traits

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#25]
RDM seems to be missing Magic Attack Bonus I and II traits. 

Magic Attack Bonus I at lvl 20.
Magic Attack Bonus II at lvl 40.

http://ffxiclopedia.wikia.com/wiki/Red_Mage

**Comment by roriffxi** [comment]
Here is some era specific evidence that the traits should exist:
http://ffxiclopedia.wikia.com/wiki/Red_Mage?oldid=218883

**Comment by beauxq** [comment]
DSP says this is WOTG, but Rori's comment shows that that is wrong.

See it in the database here:
`
SELECT * FROM dspdb.traits
WHERE traitid = 5 AND job = 5 AND level < 76;
`

Here is the fix:
`
UPDATE dspdb.traits SET content_tag = NULL
WHERE traitid = 5 AND job = 5 AND level < 76;
`
