### ISSUE TITLE
Metallic Body should be longer casting time

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2503]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

BLU's Metallic Body should be a 7 second casting time, it seems more like 4 seconds.

Here is the closest dated wiki page to show September 20th 2007's version:
https://ffxiclopedia.fandom.com/wiki/Metallic_Body?oldid=349052

And here is the next one (no difference) from January 2008:
https://ffxiclopedia.fandom.com/wiki/Metallic_Body?oldid=417979

Version: 30181205_0

**Comment by Setz0r** [comment]
cast time in database is 3 seconds.
