### ISSUE TITLE
Leech Scimitar Additional Effect

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2509]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently leech scimitar's additional effect of MP drain does not function. Tried using this weapon on retail and found out it drains between 5-8 MP randomly. Think proc rate was about every 1/20 or 1/10 swings (was mostly trying to see the range of the MP drain).

version 30181205_0

**Comment by gweivyth** [comment]
#1487 

@KnowOne134 This one wasn't in the luas I sent you but here are my numbers on it.  I think I just missed this one in my initial sweep. 

Proc% - 8-13% - 1844 ATTACKS
ProcDMG - 6-11
Notes - NA

**Comment by KnowOne134** [comment]
Atm I'm actually just need all IDs item name and the effect. And it can be added to the global I created. I have info on contributing channel

**Comment by E5una** [comment]
I don't own a Leech Scimitar but I've heard 2nd hand that it is proccing nearly 25% of the time for 25-40mp, which would be far too strong. I'm asking them for screenshots to upload here if they can provide them.

**Comment by E5una** [comment]
![leech](https://user-images.githubusercontent.com/13668758/84600996-3567d980-ae4b-11ea-949e-7a7d111cc2df.png)
