### ISSUE TITLE
Summoner AF1 Quest: The Puppet Master

### ISSUE THREAD

**Issue by blacknesscrows** [EdenServer/community#251]
I dropped my quest item on accident and NPC wont give it back.

**Comment by godmode** [comment]
I tested this and it seems to be working. Will need additional information if it's not working for you. Such as character name, what part of the quest you were on when you dropped it, etc

**Comment by blacknesscrows** [comment]
I spoke to the house of the hero and received the quest, then spoke to the taru in Bastok to receive the quest item, Earth Pendulum. This is the point which i believe i dropped the item. I can't say for sure because i started the quest on Kupo and took a break before rejoining Eden and dropping said item. I spoke to all relevant NPC's and did not progress in the quest line. I'm Sootle in game. Thank you for helping and hosting GM.
