### ISSUE TITLE
LoO Place holder is able to be charmed and held

### ISSUE THREAD

**Issue by Camuel666** [EdenServer/community#2511]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
version 30181205_0
### Details

LoO Placeholder can be charmed and held. Witnessed this several times yesterday where it would be charmed and then released 13-15 secs later. Wiki states that the place holder can be charmed but would immediately be come uncharmed and aggro but this was added to the wiki in 2009 so unsure if this was what happened in era and unable to be tested.
https://ffxiclopedia.fandom.com/wiki/Lord_of_Onzozo?oldid=950513

**Comment by Camuel666** [comment]
also i found on the Flying mantas talk page of someone trying to charm the PH and was only able to charm it for 2 secs back in 2007

https://ffxiclopedia.fandom.com/wiki/Talk:Flying_Manta

**Comment by dowzer** [comment]
The PH should also rage after being held for a determined period of time.

**Comment by KnowOne134** [comment]
Issue has been fixed
