### ISSUE TITLE
NMs are charmable

### ISSUE THREAD

**Issue by Corvinus1337** [EdenServer/community#2516]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Notorious Monsters are currently charmable. This morning while hunting Valkurm Emperor I was able to charm him and thus could not fight. When I did get him to de-charm he did not drop.

Ver: 30181205_0

![Charmed_VE](https://user-images.githubusercontent.com/61441566/76325234-7fc24300-62bd-11ea-846b-197731794e2c.jpg)

**Comment by KnowOne134** [comment]
Has been fixed
