### ISSUE TITLE
Counter steals mob claim

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2518]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

### Details
If you're on monk and take hate from a mob claimed by another player and are able to successfully counter an attack (by being engaged on another target), you'll take claim. The monster grants full exp and drops to the monk who steals claim, and it's impossible to get back for the original claimer. 

https://gph.is/g/ZrdmVdw

**Comment by 59blargedy** [comment]
resolved by another dev in April 18, 2022 patch
