### ISSUE TITLE
THF AF1 Quest "As Thick As Thieves" Not working

### ISSUE THREAD

**Issue by itzalme** [EdenServer/community#2522]
Version 30181205_0

After flagging the quest and receiving the key items, I went to Sauromuge Champaign to try to spawn the NM by clicking the ??? underneath the 6 towers. However for 2 days I have no been able to spawn the NM from all 6 including the one you need to go through the Citadel with. I only receive "It is impossible to climb this wall with your bare hands." On every single tower. I have zoned, tried different real life days, tried different in game days, I can not get the NM to spawn.

### Checklist

- [
![unknown](https://user-images.githubusercontent.com/62090934/76493578-544c6f00-6409-11ea-9710-ddbc2da00525.png)
![unknown (1)](https://user-images.githubusercontent.com/62090934/76493583-57475f80-6409-11ea-8dfa-4a6a73f994ac.png)
![unknown (2)](https://user-images.githubusercontent.com/62090934/76493592-5a425000-6409-11ea-90a8-cfb9763eec63.png)

x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by E5una** [comment]
Friend had this problem and failed to get the goblin to spawn at all spawn points on multiple days. They then went back and did the OPTIONAL dialogue and were able to spawn the goblin immediately after. Hope this helps someone in the future or prompts a dev to fix :).
