### ISSUE TITLE
Blue Textile Dye out of era recipe still active.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#2523]
### Checklist

- [ /] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ /] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ /] I have provided my client version in the details. (type /ver into your game window)

### Details

Blue Textile Dye is an out of era recipe wasn't added until 2008. Still see people abusing this to skill up. https://ffxiclopedia.fandom.com/wiki/Blue_Textile_Dye?action=history
 
Version = 30911205_0

**Comment by bkesecker** [comment]
Confirmed.  These recipes exist in live database, but only red appears in source control.

**Comment by bkesecker** [comment]
Fixed live.
