### ISSUE TITLE
Ranger AF weapon quest bug 

### ISSUE THREAD

**Issue by Segepor** [EdenServer/community#2525]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
I was doing the ranger AF weapon quest was working fine i got to the last part where i have to click on some ???s on a tree in Jugner Forest i click on the the CS starts 4or5 times i tired i get stuck at the same part  Shikaree M said "That is your title. correct?" in the CS and nothing happens after that it just stops i can still type in chat so its not like i froze the CS just does not advance past the point this also happen to other person that was trying to do the quest too 
My version is 30200217_0

**Comment by slassen** [comment]
Sorry, there is not enough information here to reproduce the issue.

**Comment by Volkaru** [comment]
This is probably related to using /fps 1 if you do. Next time you activate the cutscene, try pressing the print screen key to force the CS to continue. If that doesn't work, restart but set your fps to /fps 2 before clicking the ???

**Comment by Mozzy4Ever** [comment]
> This is probably related to using /fps 1 if you do. Next time you activate the cutscene, try pressing the print screen key to force the CS to continue. If that doesn't work, restart but set your fps to /fps 2 before clicking the ???

It's because his /ver is 30200217_0 and not Eden's, which is 30181205_0. Incorrect /ver often breaks cutscenes
