### ISSUE TITLE
Fafnir issues

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#2528]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
1. Fafnir's hurricane wing damage is too high atm. It seems to have been raised recently, about the same time the TP regain was increased. Currently it is hitting for 660 damage without any form of mitigation(shell/phalanx/etc) on Eden. Here are some videos of retail numbers:

https://www.youtube.com/watch?v=8717Pp60RF0 At 2:10, 287 damage to a BRD/NIN tank with shell 4.
https://www.youtube.com/watch?v=xnlXjwhoV98  At 1:10, a SAM takes 368 with no shell. 

That means Fafnir wings are doing nearly 80% more than they did on retail... basically two wings for the price of one.

2. Fafnir is currently aspirable. It shouldn't have any MP.

**Comment by Oyaziiiiiii** [comment]
Update: Today it did about 100 less, 376 with shell 4 vs 481 with shell 4. Unsure if anything was changed or if there is a variation in level with Fafnir here that might have caused it. Still higher than retail though.

**Comment by 59blargedy** [comment]
this should have been resolved by changes in recent patches. please comment if not the case
