### ISSUE TITLE
missing title

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#2529]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

Not a big issue, but a bit annoying.

So I just beat Dynamis - Beaucedine and after getting the KI I didn't get the title.
The title changer npc in Lower Jeuno doesn't offer it up either.

**Comment by KnowOne134** [comment]
what should the title be?

**Comment by KnowOne134** [comment]
Dynamis-Beaucedine Interloper

**Comment by 59blargedy** [comment]
title is only granted to the alliance that kills, so if you were in an outside party/alliance you would not receive title. assuming that is what happened here, but please comment if needed.
