### ISSUE TITLE
Kirin

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#253]
We did Kirin tonight and a few notes:

The minis, while a significant step better than Kupo's, were too weak. We were able to blow them up before they even 2hr'd so we're not certain that they do.

Kirin himself is way too resistant to gravity; he resists even with Elemental seal occasionally, and we're talking RDMs with 8/8 enfeebling merits, crimson mask, and auster's staff.

His astral flow appeared to do about 2200 damage aoe through shell IV. One shot my PLD for over 2K damage.

**Comment by Treble011** [comment]
In regards to Ranger, damage is too high it seems, we had almost 1200 damage Sidewinders, 100+ auto attacks

In regards to SMN: avatar's auto attacks (even elementals) seem to ignore defense

**Comment by Aneyus** [comment]
All of these problems are still there with Kirin. We will probably not fight it again until they are addressed to avoid the headache.

**Comment by tectal831** [comment]
We just did 3 runs of kirin, none of the minis are using 2 hour anymore it seems. also yea, astral flow is super strong. issues from 10/29 still exist.

**Comment by roriffxi** [comment]
As of our last Kirin run, 3/28, the mini-gods still aren't 2hr'ing.
