### ISSUE TITLE
Hidden Affect of Sirius Axe doesn't seem to work

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#2535]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I was in a full party using Sirius Axe on main hand and Juggernaut on my off hand. Sirius should have had 51 dmg vs 46, but my 2nd swing was consistently doing more damage than my first, making me think the hidden affect of Sirius Axe wasn't working.

https://ffxiclopedia.fandom.com/wiki/Sirius_Axe

**Comment by 59blargedy** [comment]
resolved in January 4, 2021 patch
