### ISSUE TITLE
Melody Earring

### ISSUE THREAD

**Issue by baroom84** [EdenServer/community#2536]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

This is giving evasion not evasion skill.

https://ffxiclopedia.fandom.com/wiki/Melody_Earring

**Comment by PrettyCoolPattern** [comment]
in scripts/global/item_latents.sql

-- -------------------------------------------------------
-- Melody Earring
-- -------------------------------------------------------
INSERT INTO item_latents VALUES(14725, 68, 5, 25, 0);     -- EVA+5 song/roll active

-- -------------------------------------------------------
-- Melody Earring +1
-- -------------------------------------------------------
INSERT INTO item_latents VALUES(14726, 68, 6, 25, 0);     -- EVA+6 song/roll active


Should be:



-- -------------------------------------------------------
-- Melody Earring
-- -------------------------------------------------------
INSERT INTO item_latents VALUES(14725, 108, 5, 25, 0);     -- EVA+5 song/roll active

-- -------------------------------------------------------
-- Melody Earring +1
-- -------------------------------------------------------
INSERT INTO item_latents VALUES(14726, 108, 6, 25, 0);     -- EVA+6 song/roll active

as 

  PRIMARY KEY (itemId, modId, value, latentId, latentParam)
calls modID
    EVA                             = 68,
should be:
    EVASION                         = 108,
