### ISSUE TITLE
Capricious Cassie Sleep/Draw-in

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2538]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205

Capricious Cassie is easily put to sleep via sleep bolts. Haven't tested normal sleep spells on it yet, and test server is offline atm :(

His draw-in radius is also waaay too small. If you run outside of it's draw-in radius, you'll get chain draw-in'd until you get stuck inside of a wall. Seems like the radius for draw-in is <5' which further causes issues because of the size of the mob.
https://www.bluegartr.com/threads/30459-Capricious-Cassie-strategy speaks of kiting Cassie, and https://ffxiclopedia.fandom.com/wiki/Capricious_Cassie says that cassie will only use draw-in if target moves into a hallway.

**Comment by 59blargedy** [comment]
resolved december 7 update. comment here if drawin is still causing issues, but should be resolved.
