### ISSUE TITLE
Cartonnier gives 20 storage instead of 6

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2539]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Disclaimer: I HAVE NOT TESTED THIS MYSELF

I was told secondhand by a woodworker that Cartonnier is giving 20 storage instead of 6. Would be nice if someone would look into this. It gives 20 today in retail, but should give 6 at the time of our server: https://ffxiclopedia.fandom.com/wiki/Cartonnier?oldid=374493

Apologies for opening a ticket I cannot test myself.

version 30181205_0

**Comment by Raphtalia1** [comment]
That is the same for all furniture, the server has the early 2008 storage buff. Fixing would require both code and re-making all the .dats for furniture

**Comment by slassen** [comment]
I agree the SQL changes would probably be best to all do at once. dat mods are usually done separably though so a ticket should probably stay open until that's done. with a `needs-dat-mod` label.

[The storage capacity for the following items has been adjusted:](http://www.playonline.com/pcd/verup/ff11us/detail/3347/detail.html)

**Comment by Shoruto** [comment]
I have moved this report to #2602 in it's entirety and will close this report. If you have any more information to provide please put it on the other report.  This includes any other furniture that provides OOE storage amounts. Thanks
