### ISSUE TITLE
Hyorin Obi - Sea Obi

### ISSUE THREAD

**Issue by ElectroNicMan83** [EdenServer/community#2540]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Sea obi's from in the name of science dont seem to work. 
Went in Ulugerand Range. Double Ice Weather.
No waist => 1236 With obie => 1236.

While writing a report,  most organ drop rate except aern seem to be way lower the retail drop rate.

**Comment by perkuprightmeow** [comment]
We did some pretty extensive testing when Obis came out and found them to be functional -- how many casts/tests did you do? 

Weather and day have the innate ability to "occasionally increase" damage, the obi just guarantees it afaik.

**Comment by Slamm21** [comment]
yeah you just got the double ice weather effect when you nuked without the Obi as well. Like above there is always a chance you get it to increase damage but obis make sure it always happens.
