### ISSUE TITLE
Tigereye Ring Recipe is Not Added

### ISSUE THREAD

**Issue by CdoubleOkay** [EdenServer/community#2541]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

Tigereye Ring Recipe is not in, returns "That combination of materials..."

**Comment by 59blargedy** [comment]
recipe didn't get listed until 2008, but item only obtainable via synthesis so:
INSERT INTO synth_recipes VALUES(0,1,0,0,0,0,0,40,0,0,0,4099,4241,1766,13456,0,0,0,0,0,0,15801,15802,15802,15802,1,1,1,1);

**Comment by tacbox3** [comment]
Please add this synth, it's the only evasion ring below level 50, and is 100% in era. Wiki shows item added in Aug. 2007.
