### ISSUE TITLE
Jormungand not immune to Paralyze.

### ISSUE THREAD

**Issue by YarAsti** [EdenServer/community#2544]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Jormungand should be immune to Paralyze however that's not the case  on Eden currently.

https://gyazo.com/b3d598b6a248ef42df05f076937833b4
(Screenshot of paralyze landing on Eden)

https://gyazo.com/1101599a1b381267baa883580c7817cd
(Screenshot from https://www.bluegartr.com/threads/44389-Rdm-Merit-Spells/page2 talking about RDM merits and how Jorm is immune to para)

**Comment by roriffxi** [comment]
https://github.com/EdenServer/community/issues/807

Another issue related to Jorm.  And a tack-on I suppose.

Of the 6-7 times this mob has been defeated on Eden.  It has always only dropped a single ore.  It should drop up to 4 with multiples being a pretty regular occurance.

**Comment by KnowOne134** [comment]
Can you make it under a new report. I just fixed this issue and is pending
to close

**Comment by perkuprightmeow** [comment]
Rebumping this, still was able to reliably land paralyze on Jorm instead of a "no effect" message.
