### ISSUE TITLE
Fomor Family Dancing Chains

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2545]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

The fomor family TP move dancing chains should only be inflicting a drown DoT effect on targets hit by the ability, this ability also ignores shadows. Currently on Eden this ability inflicts initial damage as well as placing the drown DoT on targets hit by it, it is also absorbed by shadows when it should not be.

![image](https://user-images.githubusercontent.com/46270382/77278386-9c835100-6c95-11ea-94a4-3ee35c6ab0cc.png)

https://ffxiclopedia.fandom.com/wiki/Dancing_Chains

https://www.youtube.com/watch?v=_YsdcKbrsx0&feature=youtu.be&t=165 Shows the ability ignoring shadows and only inflicting a drown DoT.

version 30181205_0

**Comment by Slamm21** [comment]
![image](https://user-images.githubusercontent.com/5552081/77279721-58567780-6cba-11ea-8c18-2decdd6e433f.png)

It's so brutal right now. Everyone here had shadows up.

**Comment by E5una** [comment]
As of the last patch it seems like this now bypasses shadows to apply the DoT, which I believe is correct. That being said, there were no patch notes or github updates on this ticket so it was a bit of a surprise.

**Comment by Slamm21** [comment]
yeah this should be now closed.

**Comment by FariskaEden** [comment]
Damage was lowered in the patch from what I noticed, however it's should only be applying a DoT and deal no damage.

**Comment by E5una** [comment]
Hmmm, I haven’t noticed it dealing damage but maybe the damage is getting absorbed by my shadow and the DoT is just going through. I’ll post again tomorrow when I do another swift belt run and can say with confidence if there is still damage and now it is interacting with my shadows.

**Comment by Balrahn** [comment]
The damage also ignores stoneskin.
