### ISSUE TITLE
Gun of Trials latent isn't breaking

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#2546]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver. 30181205_0

I've been at breaking gun of Trial's latent for about 4 hours and have done over 100 level 2 skillchains with it and it still hasn't broken.

It's fairly easy to track due to consuming bullets.

I'm super let down after grinding the fuck out it ;(

**Comment by HunnyDoo** [comment]
You're 1 more away from breaking it.

**Comment by ThrisStraizo** [comment]
Fucking kill me.

**Comment by ThrisStraizo** [comment]
Confirmed.
