### ISSUE TITLE
Enemy Damaging TP Moves Feel Overtuned

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2549]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When an enemy is higher level than a player or pet and uses a TP move that inflicts damage on them, it can cause too much damage. It feels like enemies have the same advantage pets do versus lower level targets. Looking at some older videos you can also see that moves don't do as much damage as they do on DSP. I realize there will be stat adjustments to mobs soon, but I'm not sure if that'll stop the high values on some moves I've seen on Eden.

Some examples:
https://www.youtube.com/watch?v=VNnadi0kwvQ&t=93 - level 16 pup soloing a tough lizard - lizard uses brain crush and the pup only takes 10 points of damage (has protect on)
https://www.youtube.com/watch?v=K9GdogwxZAc - level 60 pup in AF soloing a VT lesser colibri, pecking flurry inflicts about 60-160 damage when they have defender up

version 30181205_0

**Comment by mlandrum22** [comment]
"t feels like enemies have the same advantage pets do versus lower level targets."

Funny thing is Eden's pets don't even do good damage vs. lower level mobs like they should and did in retail. #2172

**Comment by FariskaEden** [comment]
Well I've seen some increase in ability damage at least from PUP and SMN on lower things, haven't seen BST in action versus lower level stuff. But yeah the boost that enemies get feels similar to that. Something weird is going on with how enemy ability damage is calculated in any case.

**Comment by mlandrum22** [comment]
Well would you look at that. I hadn't busted out jugs vs too weak recently since jugs are far more valuable now, but it does look like they fixed that bug w/o mentioning it anywhere.

Thanks Fariska.

**Comment by jmcmorris** [comment]
The majority of monster TP moves have been fixed. If you find issues with specific TP moves then please open a new issue and provide details on the moves and how they are incorrect. Thank you!
