### ISSUE TITLE
Last resort duration too long

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#255]
Last resort is currently remaining active for 3 minutes. This is out of era and should be 30 seconds.

**Comment by icariumkupo** [comment]
Imo this should be left alone. It's a great balance addition to drk bringing it in line with warrior. Without this change, last resort is essentially useless. It was adjusted by SE for a reason. All balancing additions should be considered for keeping.

**Comment by godmode** [comment]
Would like to hear more input on the matter from others too.

**Comment by Frylokk** [comment]
I'm okay with a couple items here and there not being era but I'm not for keeping skill and duration that's out of era. I feel it should be back to 30 seconds. The reason I feel this way is because some people may want other jobs tweaked in the future with out of era skills because we decided to keep this in.

**Comment by godmode** [comment]
I’m ok with balancing out of era if it makes sense. I’m ok with opening that can of worms.

**Comment by Treble011** [comment]
As it is right now, a DRK can merit LR into having -50 seconds of recast, +10% more potency (making it 25% like berserk), and -10% 2h weapon delay with desperate blows. This doesn't balance the ability with WAR's berserk, it blows WAR's out of the water. 

DRK is already the leading DPS in a zerg.

Keeping this in is not a balance at all.

**Comment by icariumkupo** [comment]
But a warrior can do the same if fully merited on berserk and aggressor. As is, even with this LR, war is *still* stronger. If LR is reduced to 30s, then drk is useless outside zerg. War will always be preferred

**Comment by Treble011** [comment]
The JAs can be merited down on both, yes. WAR does not get the -2H delay or Souleater. The 30s LR basically puts it on par with Warcry.

The question posed by GM was if this would balance the classes which is not the case at all as DRK already excels in another area and this would make them excel in both. It wouldn't even put it on the same level as WAR.

**Comment by icariumkupo** [comment]
But warrior gets agressor, warcry, and double attack. I respectfully disagree. I believe keeping LR at 3 mins only brings DRK closer to war. War is still the stronger job imo

**Comment by Oyaziiiiiii** [comment]
I played on Nasomi when this was a 3min skill and I can say from experience this is something that needs to be changed to maintain balance. The -10% delay with desperate blows merits is massive with a 3min last resort.

**Comment by Elysien** [comment]
Dark Knight isn't lacking to Warrior, especially as it stands, and if this adjustment is made either. 
 the default value (x1). Effectively, those two weaponskills have a 50% ATK boost, and 75% ATK boost respectively, on them. This, with good gear/buffs will bring them quite near the cap on quite a deal of the hardest enemies for the weaponskill itself. While it's true Warrior has access to Groundstrike, it's skill rating in the weapon pales in comparison to Dark Knight. 

(On an outgoing note here, Tachi: Gekko, Yuki, and Kasha all have a 2.0x ATK mod tied to them, effectively a 100% ATK boost over 95% of the games weaponskills.)

The adjustment made to Last Resort that is currently here on Eden was an adjustment Square Enix made at the Heroes of Abyssea expansion (90-cap). This adjustment was made to help Dark Knight compete with the complete and utter indisputable damage kings of that time (Warrior - Ukko's Fury / Monk - Victory Smite / Ninja - Blade: Hi). At this point, Dark Knight was so low in the meta is was basically PUP-tier. Dark Knight is not so low in the meta at the 75cap to warrant such a buff.

(Disclaimer: I'm a Lv.75 DRK, and have invested a lot in to my Dark Knight besides just a Kraken Club zerg build -- it's fully merited in Scythe/Greatsword, and geared pretty for damage outside of Kraken Club zerging.)
Guillotine is a powerful weaponskill for trash mobs, for the most part with decent food and gear you're bringing yourself close to the attack cap to where additional attack granted from LR/Berserk is negligible anyways. Warrior and Dark Knight are fairly even here in damage potential even if Last Resort if nerfed, without the nerf Dark Knight has a 10% leading in magic haste over Warrior, might not sound like much but it seriously is, especially when paired with Hasso.

On enemies with high defence it tips the scales in Dark Knight's favour considerably vs. Warrior. Spinning Slash has 1.5x ATK mod tied to it, and Groundstrike has a 1.75x ATK mod on it. No Greataxe weaponskill has above

**Comment by Lilswitche** [comment]
DRK already gets utility above what some other DPS get and they have the distinct advantage of having the  'Zerg DPS crown'.  Why give them best in class sustained DPS as well?

**Comment by roriffxi** [comment]
Drk gets sleep, two stuns, drain hp, drain mp, drain stats, drain tp, drain spikes and the most innate atk from traits. Do they need to add better berserk on top of it?

**Comment by Aneyus** [comment]
imo this would be acceptable to leave in as-is if not for Desperate Blows also lasting 3 minutes. 3 minutes of that seems far too strong. If it was just the attack bonus, sure.

**Comment by Treble011** [comment]
I agree that desperate blows is what makes this over the top but I'm not suggesting we remove that either.

**Comment by icariumkupo** [comment]
Hard to argue with your guy's points. Except one counter I'll make is that maxing desperate blows is no easy task, that's a lot of exp and should still be rewarding. Perhaps a balancing comprise could be made? I would just be disappointed to see last resort and all its merits become trivial again because of such a short duration. What if we reduced duration of LR in half or reduced effectiveness of desperate blows in half?

**Comment by beauxq** [comment]
I think we should avoid stuff that doesn't match either era or current retail. That makes it significantly harder for people to learn the game.

**Comment by Serephim** [comment]
I'm a 75 DRK and I agree it is kinda OP. lol
It was changed to 3 minutes in an era where they had to compete with jobs with much more overpowered abilities and weaponskills than are available now. DRK is already a decently competitive DPS in end game and has a lot of utility that other DPS don't have. Having access to all the ToAU dark magic spells will make DRK much better too. Kinda parroting what other people are saying so I will leave it at that.
