### ISSUE TITLE
Tiamat (and probably Jormungand and Vrtra) missing claim shield

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#2551]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Tiamat currently does not have a claim shield mechanic.

**Comment by CurzonEden** [comment]
Bumping this as I think Tiamat is now the only contest HNM on the server that lacks a claim shield.
