### ISSUE TITLE
Teleport in G-9 Pso'Xja tower = Downloading Data...

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2552]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Using the teleport in the basement of the G-9 Pso'Xja tower (the one used for mimic chest farming) is supposed to kick you out to Beaucedine Glacier. On use, I consistently get stuck in a "Downloading Data..." screen, despite the zone functioning as normal (not crashed).

**Comment by 59blargedy** [comment]
could not duplicate, assuming resolved with event fixes in 2020
