### ISSUE TITLE
Enemy Astral flows casted on players are doing 0 damage

### ISSUE THREAD

**Issue by YarAsti** [EdenServer/community#2553]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
As title says we ran some Jungle boogeymen and some Ifrit Prime today and every time we were hit by Astral flow it did 0 damage.  I imagine this is the case for all mobs astral flows (including Kirin) but not confirmed.  Here are our screen shots...

https://gyazo.com/dafe9dc277b830be26d8ff5c076da59e

https://gyazo.com/f6d13fa836e0289b0698aa5565a931ae

https://gyazo.com/84584dbbcecff37f9a25001dc5c1a70d

https://gyazo.com/3cf758bda49c80c7bc9fc369e0ba8378

https://gyazo.com/c16b360e0542027b1ba55906c2fbca3a

**Comment by roriffxi** [comment]
Astral flow in dynamis is definitely not doing 0 damage.

**Comment by Falaras** [comment]
Saw this happen in Dynamis - Jueno last week to us. I've never seen it happen before though, usually Dynamis mobs and Kirin definitely do damage with AF.

**Comment by E5una** [comment]
Just wanted to update and say my friend did Boogeyman today and saw consistent 0 damage astral flows as well. Maybe something on the current patch?

**Comment by bkesecker** [comment]
This should be resolved with the next patch.  Please close if so.  The code that fixes it has already been merged into our main, and, therefore, will not auto-close this GitHub issue.
