### ISSUE TITLE
Dark Puppet Quest: Duplicate Gerwitz's Sword

### ISSUE THREAD

**Issue by stevelicavoli** [EdenServer/community#2554]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
When completing the Dark Knight AF quest named Dark Puppet on March 24, 2020 (Sorry, I did not get a timestamp though it was after 6PM EST),  I discovered Gerwitz's Soul drops an additional copy of Gerwitz's Sword. The Sword is a necessary item to spawn Gerwitz's Soul and is consumed in the process. I believe the intended behavior is for the player to no longer have Gerwitz's Axe or Gerwitz's Sword when the encounter with Gerwitz's Soul begins and upon quest completion.

**Comment by 59blargedy** [comment]
resolved in January 18, 2021 update
