### ISSUE TITLE
Shall Shell don't bite robber rig + halycon rod in Valkurm Dunes

### ISSUE THREAD

**Issue by joeis78** [EdenServer/community#2558]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
1) See era wiki or era fishing guides to observe robber rig + halycon rod + valkurm dunes is an ideal setup for this fish
2) Use this comp to fish in valkurm dunes
3) 0 bites out of over 30 casts
version 30181205_0

**Comment by Setz0r** [comment]
the affinity for this bait/fish combo was incorrectly set.  correcting for upcoming patch

**Comment by mlandrum22** [comment]
Is there any correction being made for Istiridye in Nashmau? I can just as many Istakots (every where says bites should be "rare") as I do Istiridyes.

Catch rate with crayfish balls is significantly higher even though wiki says the preferred bait is robber.
