### ISSUE TITLE
/jump emote

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2559]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When using /jump other players can't see you perform the emote. It only shows you jumping on your client.

version 30181205_0

**Comment by 59blargedy** [comment]
jump is way ooe (2017? 18?) though it is damn fun.

**Comment by FariskaEden** [comment]
Aw didn't realize it was from that time frame but yes it is fun.

**Comment by 59blargedy** [comment]
while this was one of my favorite things SE added, it's not in era so just going ahead and closing it out. we have enough reports 😂
