### ISSUE TITLE
Ranged Attacks Have No Leash Range

### ISSUE THREAD

**Issue by Caelic** [EdenServer/community#2560]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.) a similar issue is posted but the ticket is closed, the ticket lacks this checklist, has an inaccurate ticket title and has no reproducable steps
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
version 30190305_0

STEPS:
1. Begin the ranged attack animation on a target at near-max distance for ranged attacks (stand at about 24 yalms away) and wait for the target to move away. Longbow and gun are best for this due to high delay
2. If target does not move away, cancel RA and go back to step 1
3. When the ranged attack attempts to complete after the target has moved a short distance away from you, the ranged attack will cancel

### Details

Thanks to aether for demonstrating this on live SE servers in this video... as you can see a ranged attack must be started within 25 yalms but there is a leash range that will allow the ranged attack to still complete beyond that if the monster moves away. In the video it is shown that the leash range is AT LEAST 8 yalms (to 33 yalms) but it could be longer. Video below.

https://youtu.be/SHEs5cjBg2E

The fix is entirely going to be within the map/ai/states/range_state.cpp source file and I will post more details on what exact code edits are needed in the next post once I get home.

**Comment by Caelic** [comment]
Ok so, in range_state.cpp

```cpp
bool CRangeState::Update(time_point tick)
{
    if (tick > GetEntryTime() + m_aimTime && !IsCompleted())
    {
        auto PTarget = m_PEntity->IsValidTarget(m_targid, TARGET_ENEMY, m_errorMsg);

        CanUseRangedAttack(PTarget);
```

change to

```cpp
bool CRangeState::Update(time_point tick)
{
    if (tick > GetEntryTime() + m_aimTime && !IsCompleted())
    {
        auto PTarget = m_PEntity->IsValidTarget(m_targid, TARGET_ENEMY, m_errorMsg);

		uint8 range = 25;

		if (tick > GetEntryTime()) // after checking for the initial time, the mob can move further away and not cancel our RA
		{
			range = 40;
		}

        CanUseRangedAttack(PTarget, range);
```

then update the declaration of the function in the header file and the definition of the function to have a second argument that is "uint8 range". after that there is one other reference to this function at

```cpp
CRangeState::CRangeState(CCharEntity* PEntity, uint16 targid) :
    CState(PEntity, targid),
    m_PEntity(PEntity)
{
    auto PTarget = m_PEntity->IsValidTarget(m_targid, TARGET_ENEMY, m_errorMsg);

    if (!PTarget || m_errorMsg)
    {
        throw CStateInitException(std::move(m_errorMsg));
    }

    if (!CanUseRangedAttack(PTarget))
    {
        throw CStateInitException(std::move(m_errorMsg));
    }
```

just update to

```cpp
CRangeState::CRangeState(CCharEntity* PEntity, uint16 targid) :
    CState(PEntity, targid),
    m_PEntity(PEntity)
{
    auto PTarget = m_PEntity->IsValidTarget(m_targid, TARGET_ENEMY, m_errorMsg);

    if (!PTarget || m_errorMsg)
    {
        throw CStateInitException(std::move(m_errorMsg));
    }

    if (!CanUseRangedAttack(PTarget, 25))
    {
        throw CStateInitException(std::move(m_errorMsg));
    }
```

then within CanUseRangedAttack there is a distance check pretty far down, looks like

```cpp
if (!isFaceing(m_PEntity->loc.p, PTarget->loc.p, 40))
    {
        m_errorMsg = std::make_unique<CMessageBasicPacket>(m_PEntity, PTarget, 0, 0, MSGBASIC_CANNOT_SEE);
        return false;
    }
    if (distance(m_PEntity->loc.p, PTarget->loc.p) > 25)
    {
        m_errorMsg = std::make_unique<CMessageBasicPacket>(m_PEntity, PTarget, 0, 0, MSGBASIC_TOO_FAR_AWAY);
        return false;
    }```

just change the 25 to be the new function's argument

```cpp
if (!isFaceing(m_PEntity->loc.p, PTarget->loc.p, 40))
    {
        m_errorMsg = std::make_unique<CMessageBasicPacket>(m_PEntity, PTarget, 0, 0, MSGBASIC_CANNOT_SEE);
        return false;
    }
    if (distance(m_PEntity->loc.p, PTarget->loc.p) > range)
    {
        m_errorMsg = std::make_unique<CMessageBasicPacket>(m_PEntity, PTarget, 0, 0, MSGBASIC_TOO_FAR_AWAY);
        return false;
    }```

**Comment by slassen** [comment]
Thanks for the snippet! My theory is there is no limit to how far an entity can move away after the ranged attack is initiated. If that's true it's probably easier to add a second param `ignoreRange` to `CanUseRangedAttack()` and pass `true` when it's being called in `CRangeState::Update()`.

**Comment by KnowOne134** [comment]
@slassen are you gonna handle this?

**Comment by slassen** [comment]
Sorry, I just noticed this comment. No, I hadn't planned on it. Suggesting to add it to the other PR open for ranged attacks though.
