### ISSUE TITLE
Suzaku immune to Silence

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#2562]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Suzaku seems to be immune to Silence, even with Elemental Seal. 
This is only outside Suzaku. Kirin's Suzaku pet can be silenced as normal.

I remember in era using ES silence to shut down Chainspell. 

Ver - 30181205_0

**Comment by Balrahn** [comment]
Can confirm this. I've silenced it before.
Here's also a comment from 2007 supporting it.
https://ffxi.allakhazam.com/db/bestiary.html?fmob=1638 

Today's ffxiclopedia also confirms this:
https://ffxiclopedia.fandom.com/wiki/Suzaku

**Comment by Balrahn** [comment]
http://i173.photobucket.com/albums/w62/Egobrane/silence.png

**Comment by Balrahn** [comment]
People talking about it here as well. From 2008, but don't think much changed the last year.
https://drive.google.com/uc?id=11NZMCAnPLXt1sCOTupp65MCSmsrNpgOG&export=download

**Comment by Slamm21** [comment]
This was possible, but hard to land.
It was not reliable at all, which is why to solo it you would let it nuke you until it's mp was gone, then kill with an easy chainspell

**Comment by KnowOne134** [comment]
are you getting the immune message when you cast it? NO EFFECT

**Comment by KnowOne134** [comment]
your right i see it now
