### ISSUE TITLE
Selbina/Mhaura Nomad Moogles are out of ToAU era

### ISSUE THREAD

**Issue by Caelic** [EdenServer/community#2563]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
version 30190305_0

STEPS:
1. Travel to Selbina from Valkurm Dunes
2. Go straight and take a left up the stairs where the sheep pen is. At the top are Nomad Moogles

1. Travel to Mhaura from Buburimu Peninsula
2. Take the stairs immediately at the right, then at the top go left across the wooden bridge. Here there are a few Nomad Moogles

### Details

The most current revision on the Wiki shows that Nomad Moogles are in Selbina and Mhaura, giving the player access to their mog house while in these towns.

https://ffxiclopedia.fandom.com/wiki/Nomad_Moogle?oldid=1675826

An older revision from 2007 shows that they were not yet added to Selbina nor Mhaura.

https://ffxiclopedia.fandom.com/wiki/Nomad_Moogle?oldid=339474

Hence, these moogles are out of era on Eden.

**Comment by KnowOne134** [comment]
That is correct. I've been saying it since about month 1

**Comment by KnowOne134** [comment]
not out of era anymore
