### ISSUE TITLE
Astral Flow inflicting double damage

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#2566]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

In Jungle Boogeyman BCNM - Astral Flow hit for 502 damage in the log, but killed me with 900+ HP. I believe it might be hitting for twice the damage shown in the log.

**Comment by Raphtalia1** [comment]
Astral flow from Lobias just oneshot a party fighting him, everyone has ~600+ hp, log only shows 300-400 dmg

**Comment by slassen** [comment]
This is definitely not the case right now as last I heard they were underpowered. Please open a new ticket after a couple of weeks if there is still an issue with Astral Flow so that they can be adjusted.
