### ISSUE TITLE
Leaving BCNM before opening chest breaks Orb

### ISSUE THREAD

**Issue by RemotelyPlausible** [EdenServer/community#2568]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Exit BCNM through entrance via "Run away!" prior to anyone opening the chest

Attempting to use orb for the first time on the door afterwards with "a very solid-looking gem" is met with a "used" message.
![srGA17C](https://user-images.githubusercontent.com/60304873/77830911-446ba500-7102-11ea-8cb4-473e16ad3333.jpg)

Note: this orb was purchased on March 27, 2020 prior to the update on March 28, 2020. But another member was able to use his bought a week prior, so this shouldn't be relevant.

**Comment by KnowOne134** [comment]
The orb is broken as soon as you enter the bcnm

**Comment by RemotelyPlausible** [comment]
I didn't open the BCNM with my orb.

**Comment by RemotelyPlausible** [comment]
Guess I'll rephrase to make it 1000% clear.

I didn't use my orb to enter the BCNM. A different member used his orb, I left through the front entrance after defeating enemies before opening chest to test if that optional was now functional. It resulted in 2 broken orbs for one run.

**Comment by slassen** [comment]
I was not able to reproduce this locally with new orbs. This isn't to say other bug made your orb break but so far the only code will write something to the game saying like "the monster has escaped and cracked the orb".
