### ISSUE TITLE
Distant Beliefs CS issue

### ISSUE THREAD

**Issue by Hruizii** [EdenServer/community#257]
Talk to Justinius on the upper level, at (J-6).

CS freezes on both my characters (Ares/Hypnos) when green haired taru portion starts.

**Comment by Setz0r** [comment]
Are you still having this issue?  I just tested every cutscene Justinius offers and all played to completion without a hickup.

**Comment by Hruizii** [comment]
Yes, issues still persists for me. I can log in tomorrow morning and show
you what's happening

**Comment by Hruizii** [comment]
![stuck](https://user-images.githubusercontent.com/37120745/48920773-b0276900-ee4f-11e8-977b-3cd180ed5471.PNG)

At this point is where it freezes

**Comment by Hruizii** [comment]
print screen worked. thanks for the help

**Comment by Setz0r** [comment]
and you aren't using any special dat mods or plugins?

**Comment by Hruizii** [comment]
It was fixed using print screen button
