### ISSUE TITLE
BCNM40 Worm's Turn Loot Audit

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2571]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

There's several issues with this BCNM that need a git hub report mechanically, but wanted to push for an audit on the loot tables themselves.

https://ffxiclopedia.fandom.com/wiki/The_Worm%27s_Turn?oldid=324225

^ Should be the proper loot table, but I received 

[00:09:54] You find a Hotei card in the Armoury Crate.
[00:09:54] You find a scroll of Phalanx in the Armoury Crate.
[00:09:54] You find a rosewood log in the Armoury Crate.
[00:09:54] You find a yellow rock in the Armoury Crate.
![Juul_2020 03 28_154139](https://user-images.githubusercontent.com/52988064/77833365-c364db80-710a-11ea-9d37-33bf54f17145.png)

Noticeably the Hotei card which is part of the Starlight Celebration. 

WTT my card for whatever I was supposed to get thanks :)

**Comment by slassen** [comment]
I just checked to make sure it wasn't a part of my rewrite and thankfully it wasn't. This was a pre-existing issue. For the person adding/removing items the card itemid is `1751` and the item it should be is a scroll of erase, itemid `4751`.

**Comment by Mozzy4Ever** [comment]
> WTT my card for whatever I was supposed to get thanks :)

If this ends up being a thing well: 
![image](https://user-images.githubusercontent.com/11255886/77836093-16498d80-7121-11ea-8370-2a50179319bd.png)

:P

**Comment by slassen** [comment]
FWIW, I just fixed the Chainspell worm casting so no need to make a new bug report on it.
