### ISSUE TITLE
Pet Assault Putting Initial Aggro on Players + Not Claiming if Miss

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2574]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)

### Details

Since the patch if you assault on a monster and your summon misses, instead of having aggro on the summer it aggros you instead. This isn't how it is on retail. 

Retail:
https://gfycat.com/velvetysarcasticgaur

Can see carbuncle miss, and the monster is on carbuncle. On Eden since the patch it now just runs to the player on a summon initial miss.

Apparently this applies to all pets currently. Also worth noting, if your pet misses the monster isn't claimed which isn't retail behavior.

**Comment by FariskaEden** [comment]
This is also happening with deploy from puppetmasters, so may be an issue with all pet jobs that can command a pet to attack.

**Comment by KnowOne134** [comment]
still an issue?

**Comment by perkuprightmeow** [comment]
Unsure on live, but fixed on the test server.
