### ISSUE TITLE
Puppetmaster Out of Era Spells

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#2575]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

Out of era Puppetmaster spells:
Protect (I-V) / Shell (I-V) / Haste / Dispel
All of these spells where added to automatons in the 2011 patch linked below and are not in era. Likely there are a significant amount more spells like this, but I do not have the ability to test that.
https://forum.square-enix.com/ffxi/threads/16436

Puppetmaster apparently gets Protect V here, a White Mage merited ability in era, lol.
Ver 30181205_0
*Edited ticket to make more sense.

**Comment by FariskaEden** [comment]
Protect V is only unlocked for automatons through merits currently.

**Comment by Falaras** [comment]
Right, and was not added to Pup until 2011.

**Comment by ThrisStraizo** [comment]
> Absorb-Attri

At the very least, absorb int is era.

**Comment by Falaras** [comment]
I'm going to edit the ticket I realize I only listed the spells it gained in that 2011 patch, not the spells Eden has from that patch.

**Comment by ThrisStraizo** [comment]
Also they don't have acces to Addle, Regen IV, Shell V or Stoneskin.

**Comment by ThrisStraizo** [comment]
Also if you want to be more specific, currently rdm puppet has access to tier IV nukes when it should be restricted to III.

(Not that I want any spells taken, I mean, we got extra H2H skill already but hey, I'll add as much information that I'm aware of for era specific content.)

**Comment by Falaras** [comment]
Do you know what patch it was that Pup gained T4 nukes? I'm trying to verify that and I'm seeing that at least in January 2009 (as far back as the page I am looking at goes) they had access to T4.

**Comment by ThrisStraizo** [comment]
I think blm puppet always had it.  Not sure when rdm puppet got it.

**Comment by ThrisStraizo** [comment]
Yeah it looks like the RDM head got access to T4 nukes in the same patch you linked above.

**Comment by KnowOne134** [comment]
Corrected on today's update
