### ISSUE TITLE
Unable to trade Skeleton Key to Iron Door in Phomiuna Aqueducts to attempt to pick open the lock. version 30181205_0

### ISSUE THREAD

**Issue by DeliriumOnEden** [EdenServer/community#2576]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

As the title says I'm unable to attempt to pick open the locked Iron Door in Phomiuna Aqueducts during CoP mission 2-3

**Comment by 59blargedy** [comment]
i can't replicate this issue, though it is slightly finicky as to where you stand and of course you have to be on THF main when using keys/tools. will reopen if this issue reoccurs for someone else, but appears resolved.
