### ISSUE TITLE
Yellow Liquid?

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2577]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205

https://ffxiclopedia.fandom.com/wiki/One_to_be_Feared?diff=383123&oldid=369117
"Remember to use Yellow Liquid to speed up the fight. **Due to the number of additional Mammets and two to three Liquids dropping from each**, you'll most likely end the fight with more than you use."

I have never seen a single yellow liquid drop, let alone 2-3 from each.

EDIT - Suddenly started having yellow liquids drop from mammets on the fight after I made this bug report (of course). Though the quantity was always 1, and sometimes 0. Leaving bug report open cause technically not correct, but not really significant

**Comment by 59blargedy** [comment]
this was resolved with an additional drop chance 5/16/20 patch. if conclusive proof of three dropping can be found at any point, please comment.

**Comment by Qair** [comment]
Kind of relevant but I found this from 2006 verse the ENM:

![yo](https://user-images.githubusercontent.com/38199815/82346124-b30b0780-99bb-11ea-8f6c-e7a8bcc28c8f.jpg)
