### ISSUE TITLE
Wrong key item when buying map of Mamook

### ISSUE THREAD

**Issue by Jaeral** [EdenServer/community#2578]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

I was checking out the possible options of things to buy from the Imperial Standing vendor Asrahd and picked a map of Mamook. Instead of the map the vendor gave me a key item called "Mythril astrarium" though. The second time i tried to buy the map he gave me the map as expected. Screenshots and version screenshot attached. 

![Jaeral_2020 03 29_123524](https://user-images.githubusercontent.com/48056420/77847065-82c49b00-71ba-11ea-872e-eb7412140568.png)
![Jaeral_2020 03 29_123935](https://user-images.githubusercontent.com/48056420/77847067-835d3180-71ba-11ea-832a-1333055e5667.png)
![Jaeral_2020 03 29_124002](https://user-images.githubusercontent.com/48056420/77847069-848e5e80-71ba-11ea-9e9e-03da15b97052.png)
![Jaeral_2020 03 29_124202](https://user-images.githubusercontent.com/48056420/77847091-b9021a80-71ba-11ea-8d57-289eac34c57f.png)

**Comment by Spider-Dan** [comment]
I can also verify this bug.  
![mamook_map](https://user-images.githubusercontent.com/52397049/81514945-92b9b980-92e6-11ea-82e1-2fd3642b28d7.png)

I am also currently on version: 30181205_0

**Comment by 59blargedy** [comment]
another poster had some addl details that may help

I received a key item "Carpenter's Aurum tome" while buying maps from the Imperial Standing/Sanction npc Asrahd in Whitegate. I tried to buy a Map of Mamook but received the wrong key item. I was then able to choose Map of Mamook from the list again, and actually purchase it the second time around.

Before going to buy the map, I first looked at the Rank 0 items, specifically Katana Strap, Axe Grip, and Staff Strap from Asrahd's menu. Then I backed out (I did not close the dialog window, I simply back out a few menus) and went to Rank 1 items and bought Map of Mamook.

I purchased the Map of Halvung and the Map of Arrapago Reef immediately after with no issue.

**Comment by squeezybutt** [comment]
I got the wrong key item for this map not too long ago. Ate my IS and gave me the Spiffy Synth. permanent key item.

![synth](https://user-images.githubusercontent.com/36972263/174468190-f269392f-9247-4689-bc04-a78a95e444f9.png)

**Comment by Mozzy4Ever** [comment]
Dunno if it helps but in @squeezybutt 's case, the KI ID was 2022.

**Comment by MauMix** [comment]
I got a "Map of Silver Sea Remnants" when I purchased a map for Mamook
I also bought the map for Mamook on my other character and got it with out issue.
![Screenshot 2022-06-21 022418](https://user-images.githubusercontent.com/98431609/174730578-e70d2715-30f8-471a-8508-167fb2e7f926.png)
k

**Comment by 59blargedy** [comment]
resolved by another dev in July 8, 2022 update
