### ISSUE TITLE
Fafnir is extremely susceptible to lullaby

### ISSUE THREAD

**Issue by danismyhero** [EdenServer/community#2579]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
30181205_0
### Details
To reproduce:
Cast Foe or Horde Lullaby on Fafnir.

/ver 30181205_0

Fafnir has virtually no resist to Lullaby.  In retail, it was almost impossible to light sleep in general without ES, however if anyone would like to share data on this by all means. 

![image](https://user-images.githubusercontent.com/49649778/77851798-9ebb4300-71a0-11ea-9bbf-0df454571398.png)

**Comment by HunnyDoo** [comment]
Almost no resist to any bard debuff. Appears to be 95%.

**Comment by danismyhero** [comment]
Hindsight is 20/20 but now I wish your tried to Virelai it.

**Comment by slassen** [comment]
From memory I don’t remember lullaby landing often on HNM and if it did it was a very short duration. I can’t remember fully though.

**Comment by 59blargedy** [comment]
this should have been resolved a few patches ago, but please comment if not
