### ISSUE TITLE
Specter Warrior wrong respawn time

### ISSUE THREAD

**Issue by jubs1982** [EdenServer/community#2581]
After 2011 they changed it to 5 mins.

Era should be 16 mins.

All the other Specters have 16 min, seems just the warrior one got missed.

**Comment by Mozzy4Ever** [comment]
Repeat of info in #1658

**Comment by jubs1982** [comment]
its been almost a year 0.0

**Comment by Mozzy4Ever** [comment]
Yea, it's been a busy year.
