### ISSUE TITLE
BLU sleeps (Sheep Song, Soporific, Yawn) should not overwrite other forms of sleep

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2582]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version: 30181205_0

Currently on Eden Sheep Song is being treated as a normal Sleep and Soporific and Yawn are being treated as Sleep II's for the purposes of overwriting and being overwritten. Correct behavior is that BLU sleeps should never overwrite another sleep and should be overwritten by all forms of sleep, almost like they are their own tier of "Sleep 0", below everything else.

Disclaimer, all the references that I can find talk about how they are overwritten by, and do not overwrite, sleep, sleepga, repose, lullaby, sleep II, Sleepga II, and Shiva's Sleepga Blood Pact, but I do not see any references to Light Shot. That being said, based on this sentence in the Quick Draw wiki page (https://ffxiclopedia.fandom.com/wiki/Quick_Draw), I would assume Light Shot would also overwrite all BLU spells, but I can't say for sure:

"Light Shot Sleep is overwritten by and does not overwrite Sleep II and Sleepga II."

_______________

References.

https://ffxiclopedia.fandom.com/wiki/Soporific
https://www.bg-wiki.com/bg/Soporific

https://ffxiclopedia.fandom.com/wiki/Sheep_Song
https://www.bg-wiki.com/bg/Sheep_Song

https://ffxiclopedia.fandom.com/wiki/Yawn
(BG post doesn't explicitly say it for yawn but its easily verifiable through quick google searches and reading forum posts. Despite their durations, all are treated as being their own tier of sleep where they are overwritten by everything and don't overwrite anything. Almost like a "Sleep 0")

Here is forum post of people discussing the sleeps if that's helpful, you can find a lot of quotes there like "Like Tonko said, none of them overwrite each other. Personally I'd go with Sop whenever you can.":
https://www.bluegartr.com/threads/37619-Blue-Mage-Best-thread-ever/page172

**Comment by E5una** [comment]
I think this needs to be reopenned, I've done a lot of reproducing of the issue but I don't have any screenshots on hand. I've been overwriting Lullabies and my own sleeps with other BLU sleeps though. Will try to get on and get some screenshots soon

**Comment by 59blargedy** [comment]
sure, im kinda working on something tangential, so i think i know why it happens.

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update - remaining issue is lullaby will not currently overwrite, but that's sort of opposite to this issue, will make new report
