### ISSUE TITLE
Metallic Body casting bar does not match actual cast time now

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2583]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Easily reproducible by just casting metallic body in game. The casting bar uses the old 3 second casting time, yet the spell now takes the appropriate 7 seconds to cast after being fixed in a previous ticket. The visual just needs to be synced up now so that BLU's don't think they are D/Cing every time they cast the spell :P

Version: 30181205_0

**Comment by 59blargedy** [comment]
dat mod is available here:
https://github.com/KnowOne134/Dats-TOAU-Era/tree/master/FINAL%20FANTASY%20XI/ROM
