### ISSUE TITLE
Treasure and Tribulations Loot audit

### ISSUE THREAD

**Issue by Zotielol** [EdenServer/community#2584]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Did 3 runs of treasure and tribulations all dropped the same exact items, Scroll of quake and Kampfer ring. Opened Big chest first, fight. Second and third were both small chest and ended bcnm without fight. 

Ver. 30200205_1

**Comment by roriffxi** [comment]
This was related to an issue affecting all BCNMs/ENMs, it should have been fixed with todays maintenance.
