### ISSUE TITLE
Gold Key not progressing CS at Mine Shaft #2716

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2585]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Multiple people having issues trading their Gold Key to the door at Mine Shaft after completing the Bugbear/Moblin fight. Had them check optional dialogue and didn't progress anything. Cid giving "come back later" dialogue as well.

**Comment by StriderClerix** [comment]
I'm having same issue as well.

Is the optional portion required? 

> (Optional): Return to Oldton Movalpolos and talk to Tarnotik to learn that you will need a Gold Key to enter the shaft.

That might be the missing part.

**Comment by KnowOne134** [comment]
Fixed now
