### ISSUE TITLE
Dynamis AF2 Treasure Hunter Category

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#2586]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)
Ver 30181205_0
### Details

![image](https://user-images.githubusercontent.com/5552081/77864543-116c0300-7221-11ea-95ac-29a3227c9c56.png)

This image clearly shows the different categories. I think TH is working fine but af2 is in the wrong category since the last patch. Also Super and Ultra rare I'm positive did not exist in era.
2% drop rate for TK with TH2 seems about right which is probably the rarest item I can think of.

![image](https://user-images.githubusercontent.com/5552081/77868019-8e9f7400-7231-11ea-85a2-a46d4cd82967.png)

I got the numbers of mobs based off ffxidb (this does not include statues, only normal mobs and NMs)
Quite clearly if the numbers from ffxidb are correct, then AF2 must be in the "Rare" category which has 8% chance of some AF2 dropping with TH4 per kill. 
Instead if seems clear Eden is using the "Very Rare" category which is only 2.5% with TH4

Anyone who did Dynamis often on retail will tell you that with a full clear of a city, the 12-19 average looks very accurate whereas 4-6 is clearly wrong. You used to see Dynamis shells who had 64 people in every run they did, and no one would have joined if only 4-6 AF2 dropped lol

**Comment by icariumkupo** [comment]
I would also add that on Eden, Dynamis-Bastok and Dynamis-Windurst have less mobs than your count, because the stats that repop after the big boss is killed are empty - they do not spawn mobs.

**Comment by Slamm21** [comment]
Also single currency should be in the "Very Common" category (64% with TH4)

![image](https://user-images.githubusercontent.com/5552081/77869409-5e0e0900-7236-11ea-9065-b89c5ffba61b.png)

so 194-249 average based on the city which seems perfect. If in "Common" category it is way too low for a full clear

With 100s, "Very Rare" seems correct
![image](https://user-images.githubusercontent.com/5552081/77869484-99a8d300-7236-11ea-8e8d-ff2f979a3a87.png)

together this would give an average total currency per zone with TH4 of:
Jeuno | 673
Sandy | 706
Basty | 681
Windy | 762
The above seems absolute dead-on to what me and many other people I know used to get on retail.

If set to super rare for 100s it would be
Jeuno | 510
Sandy | 542
Basty | 525
Windy | 598
That seems too low for a full clear. Please keep in mind, many shells on retail did not tag everything and didn't really use THF/BRD for a long time either.

**Comment by Slamm21** [comment]
also would like to add that the special NMs in xarc should be "Uncommon" so 18% with TH4
so 2.7 should drop on average when you kill all 15. Xarc is literally designed over doing these NMs instead of mass amounts of kindred

**Comment by Raphtalia1** [comment]
Great work, just want to add that Boss monsters (the 4 larger statues, Angra mainyu, and DL) seemed to have better than normal drop rates of 100’s, likely common or uncommon, it was fairly common to see a 100 drop from these monsters

**Comment by ThrisStraizo** [comment]
We don't even know if the chart they released even applies to era.  They likely completely reworked treasure hunter when they allowed it to proc on hit with increasing potency.

**Comment by Slamm21** [comment]
Maybe true, we will never know for sure, but it will likely be the system Eden uses for the considerable future.
So what we need to do is work out which items go in what category for anything that feels wrong. 

Dynamis is probably the best thing to start on with this, 100s seem fine on normal statues/eyes but are way too low on bosses and AF is clearly in the wrong category to anyone who did Dynamis on retail.

**Comment by slassen** [comment]
Using 300 as a base amount of mobs killed in Dynamis. The average should be 24 AF drops rather than 7.5?

**Comment by Slamm21** [comment]
Yeah that would be right. I got 155-240 though from ffxidb which could be wrong.
Like this is windy which was always raining AF and currency, which was often spammed in shells with just fresh 65-75s because it's easier than the glacier.
![image](https://user-images.githubusercontent.com/5552081/77904772-0050df80-727d-11ea-8c15-f602e36dd206.png)

I was planning to go on the test server after work and see if I can physically count them all

**Comment by Slamm21** [comment]
More thinking, Perhaps every AF2 is "Ultra Rare" and all 13 or 14 (depending on zone) AF have a chance to drop each mob?
If that is the case, this would be the average result per city
![image](https://user-images.githubusercontent.com/5552081/77933654-f2b04f80-72a6-11ea-9992-6ca3758fe10b.png)

**Comment by slassen** [comment]
To clarify, all AF shares a group on common mobs, so only 1 AF can drop per mob.

**Comment by perkuprightmeow** [comment]
To add to this, seems like crafting materials from dynamis were put into a category too low as well (Giant Frozen Head, Wootz Ore, etc.).

**Comment by Slamm21** [comment]
An update on this, I have now done 4 Xarcabards since the TH changes. At best outside of the NMs we have only had 2 relic drop when most of the zone has been cleared. Also might be RNG but only certain NMs seem to drop for us, are the drop rates on these different as they should be the same as each other?

**Comment by Slamm21** [comment]
@Raphtalia1 brought up today that perhaps AF2 and relic weapons shared a slot. This makes more sense. If we were to assume 50/50 chance of weapon or AF you could just half these numbers below for example.
![image](https://user-images.githubusercontent.com/5552081/79713477-cdbb6500-82c5-11ea-8f61-506f76c95152.png)

**Comment by Slamm21** [comment]
After discussions with various people including @Raphtalia1 we believe weapons shared a slot with AF, and as such this would be the drop rates for cities
![image](https://user-images.githubusercontent.com/5552081/79714411-9601ec80-82c8-11ea-9864-e213f6811136.png)
I think this cracks it, 7.89 average in jeuno at the lowest, to a 11.89 average in windy.

Please remember, shells struggled to full clear on retail, especially windy.

**Comment by Slamm21** [comment]
Another Update, from many discussions I believe AF2 and weapons share the same category.
If you look at this link
https://www.bluegartr.com/threads/32918-dynamis-sandy-drop-o-o?p=1085498&viewfull=1#post1085498
They had 339 AF for 456 weapons in cities. (42% AF)
now there are 4 weapons each run, and 13-14AF in a city, so the weight to match the above would be
AF1/AF2/AF3/AF4/AF5/AF6/AF7/AF8/AF9/AF10/AF11/AF12/AF13/AF14/Weapon1/Weapon2/Weapon3/Weapon4/Weapon1/Weapon2/Weapon3/Weapon4/Weapon1/Weapon2/Weapon3/Weapon4/Weapon1/Weapon2/Weapon3/Weapon4/Weapon1/Weapon2/Weapon3/Weapon4
In total that is 14 AF (sometimes 13) and 5 lots of 4 weapons (20) sharing the slot
This perfectly matches the ratio above.

Now with that clarified, the drop rate for cities must be uncommon (18% with TH4)
![image](https://user-images.githubusercontent.com/5552081/79776860-4524df00-832e-11ea-9d05-c1afac25dbac.png)
This gives an average of 11.49-17.02 with a full clear. **Full clears were very uncommon, especially on windy. If you could full clear windy you should not and should instead split zones**

Now let's look at Northlands where weapons did not drop
![image](https://user-images.githubusercontent.com/5552081/79777188-cc725280-832e-11ea-8446-70f8a3877cad.png)
I think it is obvious here the rate was very rare until the 2008 update, then moved to rare.
Please keep in mind a full clear in the glacier was almost impossible and very pointless and one in Xarcabard while possible, not really done because it just was not efficient.

**Comment by Slamm21** [comment]
This has been addressed in the stream today, so I'm marking this as closed.
