### ISSUE TITLE
1st attack delay

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#2587]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver: 30181205_0

So this has bothered me for a while and I'm surprised to see no bugreport about it.

When you engage a mob, your character will wait a full delay round before attacking.
The first attack should be almost instant without delay.

**Comment by E5una** [comment]
They definitely don't wait a full attack round for me. However I do have to wait a full attack round if I draw my weapons and quickly switch to a different weapon. But to my knowledge that is intentional and normal to avoid delay abuse.

**Comment by Balrahn** [comment]
lol and there it is.. Both my jobs will swap weapons upon engage.. Closing
