### ISSUE TITLE
Shield Bash Not stunning

### ISSUE THREAD

**Issue by jubs1982** [EdenServer/community#2588]
Noticed today in EXP party pup shield bash has 0% proc rate on stun.  Some plds in discord was saying their shield bash stun rate is low or none existent as well.  Before update pup stun was very high but idk about pld since I dont play it.

According to wiki

"Stun rate is fairly high, but not 100%. Being an instant ability, Shield Bash is very effective at stunning mob TP moves."

**Comment by Caelic** [comment]
My experience has been quite similar. I have personally had better reliability with Flat Blade than I have had with Shield Bash lately...

**Comment by KnowOne134** [comment]
i have seen no issue

**Comment by jubs1982** [comment]
Pup issue seems to have fixed, only has the issue just that one day after maintenance. Idk about pld.
