### ISSUE TITLE
Pup pet still not claiming after last ticket closed

### ISSUE THREAD

**Issue by jubs1982** [EdenServer/community#2589]
Title says it all.  Pup pet still not claiming mobs.

**Comment by KnowOne134** [comment]
With what method?
Automatons in retail can only claim a mob to you with a melee attack. Not to be confused with a ranged attack as that's a mobskill move. 
It can also not claim a mob with a spell cast

**Comment by jubs1982** [comment]
If we being picky why take it away after having it? There are loads of things not era.  Guess people gonna be chasing after there mobs after my pet takes first hit cus I aint giving it up lol

**Comment by KnowOne134** [comment]
Because we are trying to replicate the game as close as possible as it's being coded. Closing due to that's the way it should be
