### ISSUE TITLE
Guild point items giving more than they should

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#259]
![capture](https://user-images.githubusercontent.com/37307792/47894945-c9c22b80-de22-11e8-8691-d26f9d5f1964.PNG)
This happened both yesterday and today.  I was doing my guild point items for alchemy, yesterday it was antidote and today it was deodorizer.

I trade the first item, i get the number of guild points I'd expect.  I trade the second item and I get 10 times that amount.

I then trade the 3rd item and I get the remaining GP I'm allowed to receive for that day.

**Comment by Wiggo32** [comment]
This is an issue with the code inside the guild point lua scripting. I've noticed that these erroneous results appear only when you are dealing with items that are stackable.

**Comment by Mozzy4Ever** [comment]
> This is an issue with the code inside the guild point lua scripting. I've noticed that these erroneous results appear only when you are dealing with items that are stackable.

Yup just noticed this myself. It doesn't seem to check if you're trading a specific number out of a stack. It'll give you full points as if you traded the entire stack but only take what you put into the trade.

 Tested it today with Bastore Sardine (24 GP) @ Fishing Guild. Traded 1 sardine out of a stack of 2, got 48. Traded the other sardine that was left in the stack of 2, got 24. Traded 1 sardine out of a stack of 12, got 288 (which is 12x24) but still had 11/12 in that stack.

**Comment by godmode** [comment]
This should have been fixed awhile back. Please comment if it isn't.
