### ISSUE TITLE
Sandy Mission 9-2 Does Not Reward Gil

### ISSUE THREAD

**Issue by KiplingFFXI** [EdenServer/community#2590]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

**The Issue:**

I completed San d'Oria Mission 9-2 last night on two characters and did not receive any gil as a reward. You are supposed to receive 100,000 gil and a San d'Orian Flag furnishing item for attaining Rank 10, but I only received the San d'Orian Flag.

**References for Rewards:** 

Eden wiki - https://classicffxi.fandom.com/wiki/The_Heir_to_the_Light
FFXIclopedia - https://ffxiclopedia.fandom.com/wiki/The_Heir_to_the_Light
BG Wiki - https://www.bg-wiki.com/bg/San_d%27Oria_Mission_9-2

**The Evidence:**

Here is a screenshot from my main character showing that I completed the mission and obtained the San d'Orian Flag, but no gil.

![Sandy 9-2 bug report - proof 1](https://user-images.githubusercontent.com/62963895/78073204-4bd6bc80-7355-11ea-955a-ff771018bcdc.png)

Here is proof that I did indeed obtain Rank 10.

![Kipling_2020 03 30_221523](https://user-images.githubusercontent.com/62963895/78073227-542ef780-7355-11ea-90bf-040ea66579e5.png)

Here is proof that I completed the mission.

![Kipling_2020 03 31_133754](https://user-images.githubusercontent.com/62963895/78073250-601ab980-7355-11ea-841b-16bb139458ba.png)

![Kipling_2020 03 31_133808](https://user-images.githubusercontent.com/62963895/78073260-66109a80-7355-11ea-83d5-6dc59e810d9f.png)

For good measure, here is a VOD demonstrating that that we completed the BCNM and I got Rank 10. I was recording myself on Twitch but had my chatlog covered, which is why I posted the chatlog screenshots above.

https://www.twitch.tv/videos/579497658?t=04h13m52s

**Additional Details:**

I should also add that I was unable to receive ANY of the optional cutscenes all wikipedia articles listed. Not sure if that is somehow related.

**Comment by slassen** [comment]
Fix is in code review. I can confirm the code doesn't work at the time you won so please make a GM ticket to retrieve the gil owed.
