### ISSUE TITLE
Pirate chart quest and  5-2 Vahzl NMs not agro'ing properly

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#2591]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Pirate chart mobs mobs should agro and run at the person who turned in the chart when they spawn.  As of the patch on 3/28 they no longer do this.  Instead they stand wandering around like an unagro'd mob.

Promy Vahzl 5-2 NMs should agro in a specific order when the previous boss reaches 20%.  This is also no longer happening as of the 3/28 patch.

**Comment by E5una** [comment]
Can confirm the promy boss thing. I have a video from Saturday if needed of it happening. Meant to report, Ty Rori!

**Comment by 59blargedy** [comment]
could not recreate - must have been solved along the way, feel free to comment if this issue is still happening on live
