### ISSUE TITLE
Dynamis Countdown Timer is no longer functioning. 

### ISSUE THREAD

**Issue by CurzonEden** [EdenServer/community#2593]
### Checklist

- [/ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ /] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/ ] I have provided my client version in the details. (type /ver into your game window)

### Details
During our Xarc run last night the countdown timer for Dynamis was not functioning properly. Neither the normal system message countdown. Or the timestamp on the  hourglass  appeared. 

To reproduce: Enter Dynamis and wait.

**Comment by E5una** [comment]
Also no countdown system messages for BCNMs

**Comment by Mozzy4Ever** [comment]
"Time Remaining" messages were removed due to OOE. Hoping that can be voided via #feedback. Made a report for Dynamis as the glass doesn't update with reservation time (#2595)

**Comment by slassen** [comment]
This was overlooked in the patch notes as it was one of the bugs fixed in the BCNM rewrite. I've quoted what should happen in Dynamis below. Will fix it so that it displays at the right intervals.

> Time limit warnings will be displayed when 10 minutes, 3 minutes and 30 seconds are left. (The time your "reservation" expires will always be listed in the item description of each Perpetual Hourglass held.)

https://ffxiclopedia.fandom.com/wiki/Category:Dynamis

**Comment by DeuceFFXI** [comment]
I was going to make a similar bug report about this, but saw this was still open.  Currently on Eden we get warnings beginning at 5min remaining, but no 10min.

I've found evidence that a 10min warning was indeed given during era.  Possibly it was changed later on?  

![10m Warning Message 2004-07-12](https://github.com/EdenServer/community/assets/61279359/549a9cff-a095-46bf-91aa-4490416c89c4)

Message seen in this [video](https://www.nicovideo.jp/watch/sm33245709) around 68:28.  Video is from July 2004.

**Comment by DeuceFFXI** [comment]
Upon further review of the video, it should be noted that no 5min. warning was given in 2004.  Only a 3min and a 30sec as another was commented above.


3 MIN
![3m Warning Message 2004-07-12](https://github.com/EdenServer/community/assets/61279359/8da7aff9-6ebe-40bf-a117-7971474140e5)

30 SEC
![30s Warning Message 2004-07-12](https://github.com/EdenServer/community/assets/61279359/9dc04406-7687-42b1-8931-9d89d9d71394)

Currently I'm unaware of any era changes to these warnings.  Possibly someone has information to the contrary?

**Comment by KnowOne134** [comment]
Corrected on 7/5/2024
