### ISSUE TITLE
Yara Ma Ya Who 

### ISSUE THREAD

**Issue by itachi83** [EdenServer/community#2599]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

when i zone into tahrongi canyon and trade a distilled water to the ??? marks it accepts it but then even after 1hour+ it doesnt accept another trade even tried waiting for 2hours but nothing happens , can some1 look into this please ?

**Comment by 59blargedy** [comment]
duplicateish of https://github.com/EdenServer/community/issues/1393
see that bug report for how to temporarily avoid the issue until it is solved
