### ISSUE TITLE
Some starting equipment is missing.

### ISSUE THREAD

**Issue by Kai-Tybalt** [EdenServer/community#26]
I started my character (Tybalt) out as a lvl 1 thief. I am unable to interact with my starting weapon and nation ring. I can view that I have them through the Item chat command and I am allowed to sell them, however I cannot view them in my actual inventory of items. They won't equip through the /equip command either.
( I joined through the Kupo server just as it was shut down, in case that matters).

I know it is a small issue but it could be a problem for making new players to the server feel comfortable.

*Update: I found 1 way to interact with them by using the shortcuts alt+I & alt+e. While this solved my immediate issue of needing a weapon, I'm still not able to interact with items using the methods I first described (in case that is important).

**Update 2:My apologies after meeting one of the more experienced players I found out about the main menu button. I guess I just didn't have a strong enough grasp of the menus yet.

**Comment by godmode** [comment]
Could you provide more details? Your race, starting nation, starting job, etc
