### ISSUE TITLE
Citipati is bugged

### ISSUE THREAD

**Issue by BuffaloOnEden** [EdenServer/community#2600]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

In client version 30181205_0, Citipati has been exhibiting incorrect behavior regarding claim. On one occasion last night, I was soloing it on BLU, waiting for a THF (in the party) to come TH it, when I was charmed and the name went white. It was daytime by that time, and it immediately depopped. Then, during daytime, a regular corse popped in its place. As far as I know, you don't lose claim if you're charmed on retail, and certainly, corses don't pop in daytime.

On a second occasion (today a few hours ago), a BST/THF claimed it first with mug, yet it stayed white, so my later cannonball claimed it. I invited the BST to the party, but he didn't seem too happy about it. Undoubtedly, the recent claim changes will create additional problems we have not discovered yet. Please consider reverting the system to how it was.

**Comment by greyenvy** [comment]
![Ashton_2020 04 01_144724](https://user-images.githubusercontent.com/48332558/78262600-cd058f00-74ce-11ea-8442-960c8164fb37.png)
Here is the screenshot of me (the BST/THF) claiming it with Mug but it not going red to me.  Check timestamps to see.

**Comment by greyenvy** [comment]
I think Mug isn't claiming properly.
![Ashton_2020 04 02_120736](https://user-images.githubusercontent.com/48332558/78272657-cf221a80-74db-11ea-9cb0-6d334365cc0f.png)

**Comment by 59blargedy** [comment]
resolved in apr/may
