### ISSUE TITLE
Dynamis Jeuno Statues + their mobs constantly repop 

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#2605]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

client  version 30181205_0

When our LS attempted to do Dynamis Jeuno yesterday, the statues near the start (@ moghouse, one between the stairs and the one on the stairs) constantly repopped as well as the mobs associated with those statues. A GM attempted to kill command the mobs, but this did not fix the issue, and the statues and mobs continued to repop, forcing us to end the run. Other LSs should be warned to not attempt Dynamis Jeuno until this is looked into. 

To replicate, enter Dynamis Jeuno and start killing statues.

**Comment by Mozzy4Ever** [comment]
Think this can be closed, was fixed awhile ago.
