### ISSUE TITLE
Blackened Siredon does not appear on AH

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2609]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When searching for Blackened Siredon on the AH under  Food > Meals > Meat & Eggs, it does not appear in the search and is missing.
https://ffxiclopedia.fandom.com/wiki/Blackened_Siredon?oldid=269172

version 30181205_0

**Comment by FariskaEden** [comment]
Hmm also oddly enough while you can list them on AH (but can't search for them), these can't be bazaared either.

**Comment by FariskaEden** [comment]
Also tried to trade them but they can't be traded either. Maybe they're listed as ex when they shouldn't be.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
