### ISSUE TITLE
[TH] Dragon Blood droprate low from Nightmare Bats in Cauldron

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2610]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Dragon Blood is currently:
2.5% with TH3 (10/404)
2.6% with TH4 (13/500)

When FFXIDB has them at 4.1% with TH2 alone, and 4.8% with TH3+. 
http://www.ffxidb.com/zones/205/nightmare-bats

**Comment by Mozzy4Ever** [comment]
Also as of note, went 13/500 with TH2

**Comment by slassen** [comment]
This should be adjusted per J's TH review
