### ISSUE TITLE
No credit for CS's due to party member action or mob

### ISSUE THREAD

**Issue by jubs1982** [EdenServer/community#2611]
If you are in a CS and a mob aggro you or you party member nearby decides to fight something you don't get credit for the CS.  You will need to redue the CS and it will let you.

You can tell if this has happened to you after you CS you can not be targeted by spells.  Even tho you can move around freely spells cannot be cast on you. Exp. Sneak/warp 2

Even the smallest CS like climbing a ladder in  Aqueducts can cause this glitch.  In that case you just cant cast spells on the person since there is no benefit in the CS.

**Comment by 59blargedy** [comment]
should be resolved with October 11th update on majority of cses
