### ISSUE TITLE
Grand Palace Quasilumin hit with Horde Lullaby

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#2612]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Our Quasi got hit by our brds horde lullaby, seems to be perma stuck now. Been 5+ minutes so it should be moving again. 

VER 30181205_0

**Comment by falzum** [comment]
We resolved it by having our rdm nuke and kill it and restarting the escort. Not ideal but a suitable workaround for now

**Comment by InoUno** [comment]
Should be resolved with October 4th, 2021 update.
