### ISSUE TITLE
Hecteyes should be immune to dark based sleeps

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2614]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Our RDM was able to sleep a hecteyes mob, but I believe they should be immune per the wiki.

Wiki says that Hecteyes family should be immune to dark based sleeps:
https://ffxiclopedia.fandom.com/wiki/Category:Hecteyes

2007 Wiki (closest to our server date without going over) says they are immune to dark based sleeps:
https://ffxiclopedia.fandom.com/wiki/Category:Hecteyes?oldid=311334

![image](https://user-images.githubusercontent.com/13668758/78465305-f4707d80-76c1-11ea-9a5d-5b134e2d4c14.png)

Ver: 30181205_0

**Comment by Slamm21** [comment]
they were not immune on retail, but it was basically the 5% floor iirc

**Comment by 59blargedy** [comment]
resolved with mhit patch and adjusted in April 12, 2021 update.
