### ISSUE TITLE
Astral Flow still dealing double damage (or more?)

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2615]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Astral flow killed our full HP THF. Log says it did 535 but it definitely did over 900. 

![image](https://user-images.githubusercontent.com/13668758/78466077-33ef9780-76cb-11ea-9384-8a54d1f61759.png)

Looks like this related ticket was closed prematurely:

https://github.com/EdenServer/community/issues/2566

ver: 30181205_0

**Comment by DeliriumOnEden** [comment]
This also happened to me on rollback Saturday. Took 591 damage from Garuda while at over 1100hp and died. I did not grab the screenshot though. Was 71 Thief. Had 75 RDM tanking

**Comment by dc9111** [comment]
This is still an issue, happened to us today. Log says 508 dmg, however it 1 shotted our tank with over 1k HP.

**Comment by Slamm21** [comment]
this might be what happened to us on kirin the other day, we saw titan pop up twice at the same time and it 1 shot the entire alliance.
