### ISSUE TITLE
Mijin Gakure weakened when raised.

### ISSUE THREAD

**Issue by Kurtalicious** [EdenServer/community#2618]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Just used Mijin Gakure when I was raised I was weakened.  -.-

**Comment by Setz0r** [comment]
did you get tractored?

**Comment by Setz0r** [comment]
woopsie

**Comment by slassen** [comment]
Closing this issue. Needs checklist filled out and a more informative title and description.

**Comment by Kurtalicious** [comment]
Happened again.  I cannot provide you with anymore information.  I used Mijin Gakure I raised myself and I'm weakened with xp loss.

here is your checklist 
x
x
x
ver current

**Comment by Mozzy4Ever** [comment]
Well the weakened when raised is in era from what I recall, though the XP loss shouldn't happen

**Comment by Kurtalicious** [comment]
I believe it has to do with dying with less than 100% hp.  When I Mijin Gakure with 100% hp I am not weakened.

**Comment by Kurtalicious** [comment]
Used 2hr to hp home.  Lost xp.

**Comment by perkuprightmeow** [comment]
There's a ninja in my LS who insists it's *only* in ToAU zones. Otherwise Mijin works fine. Maybe something about signet or the zones themselves.

**Comment by Kurtalicious** [comment]
A while back there was a bug where you could 2hr raise yourself and gain xp.  Ever since they patched that it's been acting up.
