### ISSUE TITLE
After CS area goes completely black except NPCs

### ISSUE THREAD

**Issue by Mikokiko** [EdenServer/community#262]
Just completed rnk 4, everything desapear and leave you ina weird area empty but with NPC.

![riptown](https://user-images.githubusercontent.com/43910014/47936082-f6be1f00-deb2-11e8-8b4a-efc50abd3667.png)

**Comment by tectal831** [comment]
Has anybody else been able to recreate this issue?

**Comment by Mikokiko** [comment]
Seems each time I completed a rank mission involving that NPC it did that, might be something off on my side ? I dunno.

**Comment by godmode** [comment]
I'm not sure what causes this but I've seen it happen before. Changing the title to something more general.

**Comment by Setz0r** [comment]
this happens when a fadeout runs, but then the subsequent event doesn't proc.

probably related to the SQL race condition issues we've been having with setvar.

**Comment by 59blargedy** [comment]
resolved in April 26, 2021 update
