### ISSUE TITLE
[CoP] Mission 6-2 A Place to Return Cutscene didn't trigger

### ISSUE THREAD

**Issue by MonkeyAce9** [EdenServer/community#2620]
### Checklist

I had just completed the last step of PM6-1 For Whom the Verse is Sung. I watched the cutscene with Ulmia and picked the top option "Yes, I'll fight to the end!". The cut scene ended and I immediately proceed towards the Grand Duke Palace, I went to Pherimociel first, however he only send generic lines, I then proceed to the Grand Duke Palace Doors at the top of the steps.
I clicked on the doors and then on the two npcs either side, nothing happen and I decided to zone.

After zoning I again went to Pherimociel first and this time he said something different, about how the ducal guards are preparing for an attack on the ground, then another line of dialog, similar to the first but preparing for an attack from the sky. I then proceed to the Grand Duke Palace doors, no change from before.

I zoned and logged out fully, then logged back in, again I spoke to Pherimociel first and he gave different dialogue again, I then proceed to the Doors at the top of the stairs and again, no change.

Client version 30181205_0

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by jmcmorris** [comment]
Had this happen to me too. If you talk to Pherimociel first before getting the stairs CS then he skips that CS for you and you can proceed with the mission. This is a bug and I will fix it. Thanks for reporting it.
