### ISSUE TITLE
Sea - IX'drg dont spawn wynavs

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#2621]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
We spawned him, no wynav at all the entire fight. Way to easy that way.

**Comment by InoUno** [comment]
Resolved with December 14, 2020 patch.
