### ISSUE TITLE
8-2 eo'ghrah spawn/credit for fight issues

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#2622]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
related to #2611 
issues similar to 2611 are occuring on the 8-2 Eo'Ghrah fight for a LOT of people. It should be that one person spawns the mob, and the party/alliance should get credit for it. instead, killing the mob and then checkng the door for the cutscene as required will sometimes pop a new Eo'Ghrah, while still entering the user into a cutscene, and behavior similar to 2611 occurs - post cutscene, the user cannot be targeted by spells (you are able to start casting on the affected person, but your spells are interrupted when they would land and you receive "cannot cast on that target" message) and the user is not on the When Angels Fall mission as should happen as part of the cs.

steps to replicate: bring a party up to the fight, see who gets locked out of cs and who receives the cutscene without repopping ghrahs over and over. 

there appear to be a myriad of random ways to get around this bug - for us, we were in an alliance and disbanded the alliance, had user force quit game, reforned as party when he logged back in, had separate party member initiate fight (don't think this should be possible since already past mission), kill mob again, and have  affected user check the door. that seemed to work but honestly unsure how.

**Comment by jmcmorris** [comment]
This has been fixed as of the latest patch
