### ISSUE TITLE
[BRD] Mazurka is lost upon using an ability as if you go into combat

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2624]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

version: 30181205_0
Using an ability like Troubadour/Nightingale or Divine Seal (Tested as BRD/WHM) removes Mazurka from you as if you were put into combat.

**Comment by rude-jerk** [comment]
Resolved on March 22, 2021 patch.
