### ISSUE TITLE
Qn'Zdei mechanic not working

### ISSUE THREAD

**Issue by ElectroNicMan83** [EdenServer/community#2626]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

In CoP mission, the door dont close if you agro those Zdei. Also They are not on their original place and are not spinning.

**Comment by roriffxi** [comment]
https://ffxiclopedia.fandom.com/wiki/When_Angels_Fall

Specifically talking about the pot mobs in Part II of the walkthrough here
