### ISSUE TITLE
Warrior G-Axe Combat Skill capped too low

### ISSUE THREAD

**Issue by ChrisShaw89** [EdenServer/community#2627]
Just started playing on Eden and chose Warrior as my first class.  I've got to level 9 and I noticed that my G-Axe Combat Skill is capped at 1/2 what it should be, I think.  Currently it's capped at 15, but I believe it should be capped at Combat Skill 30 at level 9.  Please see picture below:

![image](https://user-images.githubusercontent.com/63205911/78506815-f1b56d00-7741-11ea-8804-2308eab6f0b1.png)

### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by KnowOne134** [comment]
Unequipped something and requip it. A common elusive bug. Has been reported before. Can close issue if that fixes it for you

**Comment by ChrisShaw89** [comment]
Fixed, thank you.
