### ISSUE TITLE
Prishe doesn't help in part 2 of Final battle

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#2628]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Twice now Prishe has just stood and watched while we tried to take down Promathia on phase two. It's especially annoying because you need her dispel to deal damage.

For now, we won by bringing in a mixed damage comp and just chipping him down. 

VER 30181205_0

**Comment by roriffxi** [comment]
She will apparently start attacking after 15minutes in Phase2.
