### ISSUE TITLE
Blacksmithing Synth - Plain Sword

### ISSUE THREAD

**Issue by Chiori1990** [EdenServer/community#2629]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Trying to craft a 'Plain Sword' (lvl 31BSM) using a light crystal and Rusty Greatsword as per this link:
https://ffxiclopedia.fandom.com/wiki/Plain_Sword

However, the synth creates a 'Two Handed Sword' which is a lvl 42 BSM synth. see the following link:
https://ffxiclopedia.fandom.com/wiki/Two-Handed_Sword

Thanks,

Rach

**Comment by roriffxi** [comment]
This is a RMT counter measure change up.  The Two-Handed Sword is the correct synth result.

**Comment by Raphtalia1** [comment]
This is the correct result per our intention to remove anti-rmt measures/nerfs (since we police the practice stronger than SE did we can afford to leave certain synths in their original format)
