### ISSUE TITLE
Full Force Blow - Worm Family

### ISSUE THREAD

**Issue by CharsiFFXI** [EdenServer/community#2631]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
TP move "Full Force Blow" seems to be hitting above average numbers.
Hits through seem to average around 290/cast
1HKO players level 18/19 on Qufim Island.

![image](https://user-images.githubusercontent.com/63218986/78519254-2e4a9c80-7806-11ea-8546-15310a5a2780.png)
![image](https://user-images.githubusercontent.com/63218986/78519271-399dc800-7806-11ea-836b-f799b33ebdac.png)
![image](https://user-images.githubusercontent.com/63218986/78519305-54703c80-7806-11ea-8d2d-36131a3eb1c5.png)

![image](https://user-images.githubusercontent.com/63218986/78519372-779aec00-7806-11ea-97be-ec149778089f.png)

**Comment by 59blargedy** [comment]
resolved a few patches ago, comment if still seeing issues
