### ISSUE TITLE
CoP Head Wind BCNM Regain Effect Timing

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2632]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

The mithra in this fight should start their regain effect when they are engaged. They each immediately used a weaponskill when my group fought them so I think they start their regain effect when spawned rather then when engaged.

https://www.youtube.com/watch?v=9uyAeqTRTMs <shows mithra not immediately TPing when engaged

version 30181205_0

**Comment by jmcmorris** [comment]
This is an issue for all monsters with regain it is just most noticeable with bcnm mobs since they tend to be up for awhile before being engaged.
