### ISSUE TITLE
CoP 8-4 Dawn: Selh'teus death = Crash

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2633]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205

If Selh'teus dies in the Dawn fight, the cluster will crash. Technically does stop the fight I suppose, but probably not in the intended way

**Comment by Lilswitche** [comment]
A few other issues with this BC:

-If Prishe dies, Promathia depops.  The fight should continue even if Prishe dies and you could raise her to full HP to continue fighting alongside you;
-During Phase 2 of the BC, Prishe does not currently engage Promathia when you start the fight.  She's supposed to immediately start fighting or engage Promathia on her own if you've not begun the fight in a specified amount of time.  Currently, it would seem she only joins the fight after X amount of time;
-Selh'teus doesn't contribute anything to the 2nd phase of the fight.

**Comment by bkesecker** [comment]
Reopening, as this is not completely fixed.
