### ISSUE TITLE
Cannot login , black screen

### ISSUE THREAD

**Issue by mordicai** [EdenServer/community#2634]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Error code FFXI-3001. Connection time out. No issues 5 minutes prior. Attempted to create new character and it failed to login with same code flagged. Now main and only character cannot login either. Black screen and downloading data tab running bottom of screen. 

Character Name : Mordicai

**Comment by Mozzy4Ever** [comment]
That's a normal error when you connect with a new character. Closing your loader/client, waiting 5 minutes (5 minutes. Not less than 5 minutes) typically fixes it.
