### ISSUE TITLE
SMN AF battlefield fights

### ISSUE THREAD

**Issue by lindz** [EdenServer/community#2635]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

The Summoner AF1 quest "The Puppet Master" battlefield is not triggering upon trading the Earth Pendulum to the Earth Protocrystal in Cloister of Tremors while in a group. When the Earth Pendulum was traded, we received the message, "It is a giant crystal." When we dropped group, the person with the quest could them trade the Earth Pendulum, but this resulted in them needing to solo the battlefield. We attempted this with two separate people on the SMN AF1 quest and it was reproduceable. 

Edit: This is the same case for AF2 "Class Reunion". In a group of four, three were on the quest, one was not, we traded the ice pendulum and got a "It is a giant crystal" message. When the person who was *not* on the quest dropped, we were able to trigger the AF2 battlefied. 

So: Only people that are on the summoner AF battlefield fights, or have already completed them, are able to assist with these fights.

**Comment by ArsinoeX** [comment]
Confirming that this issue is still persisting, even after patch notes indicated a change to the quest.

To follow up lindz report, two SMN (one whom completed the fight and one who needed it) attempted to enter the battlefield and it would not trigger the instance.

**Comment by bkesecker** [comment]
> Confirming that this issue is still persisting, even after patch notes indicated a change to the "The Puppet Master" quest.
This issue isn't related to what was in the patch notes.

> To follow up lindz report, two SMN (one whom completed the fight and one who needed it) attempted to enter the battlefield and it would not trigger the instance.
This should be fixed live, however, the wrong cutscene still displays.

**Comment by bkesecker** [comment]
> Edit: This is the same case for AF2 "Class Reunion". In a group of four, three were on the quest, one was not, we traded the ice pendulum and got a "It is a giant crystal" message. When the person who was not on the quest dropped, we were able to trigger the AF2 battlefied.

This should also be resolved live.

**Comment by ArsinoeX** [comment]
> This should be fixed live, however, the wrong cutscene still displays.
Friends continued to have an issue with entering the instance (as a party) as of this afternoon

They did find a work-around with the issue, however. First they disbanded their party, reinvited to a new one, but they did not accept the invite until the 42SMN had traded the Earth Pendulum to the crystal. Once having the window open, the two of them were able to enter.

**Comment by Namiea012** [comment]
Experienced this bug 11/8/20 with "Class Reunion". The workaround that ArsinoeX mentioned worked, so thank you so much for posting that. I was going crazy for a while, there. :)
