### ISSUE TITLE
Tavnazia Bell Not Dropped By Dark Stalker

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/community#2636]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Dark Stalkers do not drop Tavnazia Bell, but the database seems to indicate that the bell can be stolen.  This makes it difficult for WHM to complete quest Pieuje's Decision because the item is Exclusive.

**Comment by 59blargedy** [comment]
i can testify that at least 4 months ago dark stalkers dropped the bell, as I have WHM AF. it wasn't a fantastic droprate, but it existed. something changed in the meantime if it's no longer listed as a drop in the db as the above seems to indicate.

**Comment by post32015** [comment]
I confirm that they can be stolen currently.  Stole 2 of them with my 61war/30thf on Apr. 4th....unfortunately this didn't help the 58whm that needed the bell.  I came back as 58whm/5thf, but was never successful in stealing a bell.
