### ISSUE TITLE
Cardians in Outer Horutoto ruins may need a drop rate audit

### ISSUE THREAD

**Issue by TheKingOfJeuno** [EdenServer/community#2637]
### Checklist

- z[ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

**Comment by TheKingOfJeuno** [comment]
while im here also going to throw in that the knight crawlers in the boyhada tree have a suspiscious drop rate for lucky eggs... as in they dont drop either after killing 50+ of them with th1 but i'm not a dev and i have limited tools to actually test something as ambiguous as a drop rate.

**Comment by perkuprightmeow** [comment]
When I did this quest before TH changes the Ten of Coins card was BY FAR the one that took me the longest. I went around 1/50 on it. Wiki and FFXI DB have droprate at 10% +

**Comment by TheKingOfJeuno** [comment]
managed to find the card, edited the github report title, the mobs in the zone may just need an audit for accurate drop rates. Also found the lucky egg which pay have its own loot table concerns but it's something i dont have spare time for at the moment.

**Comment by Althaia** [comment]
Thank you so much for making this topic!

I have been trying to get a Ten of Cups to drop since before the Treasure Hunter audit!

...And you can probably tell by all the exclamation points in this post that it hasn't happened yet.

Earlier this year / late last year, I tried for hours on my own, then for more hours with a friend who had TH2, then for more than an hour with another friend who had TH3.

During all those hours, we got a few Ten of Coins cards (helping others do Opo-Opo quest), but NEVER a Ten of Cups card. I seriously think it's not even in the loot pool, could its drop rate be looked at, please?

I need a Ten of Cups for a quest. :-/

There are only two spawns for Ten of Cups with a 15 min respawn each, which is a really time-consuming camp for something I'm not even sure can drop, so I haven't tried it again since the TH changes.

**Comment by TheKingOfJeuno** [comment]
@Althaia , i managed to find the ten of coins card a few weeks ago... I slaughtered both rooms full of cardians about 20 times. I got lucky in finding the ten of coins card after almost a day of farming that place and waiting for respawns. You would think y bags would of been full of various different cards  as a result of farming everything. I got my card and left that horid place as soon as possible.

**Comment by Althaia** [comment]
@TheKingOfJeuno Yeah, Ten of Coins is the only Ten card I've ever seen, I think. And it sounds to me like you never got a Ten of Cups card in all that time, which supports my suspicion that its drop rate is either seriously off or non-existent. XD

I agree, you should've gotten a lot more cards after all that farming, not just one Ten of Coins.

There was a Twitch with Eden Devs earlier this week where they asked people what they thought should be looked at after the Treasure Hunter changes, but I forgot to log on and mention the Ten of Cups issue. :-/

**Comment by TheKingOfJeuno** [comment]
The Ten of coins card was the only item saw.I havent watched any dev videos/twitch, the github is open, and its now someone elses problem. That sounds like its only for people who have a voice or server favorites, so good luck to you if you try that avenue :D

**Comment by Mozzy4Ever** [comment]
> The Ten of coins card was the only item saw.I havent watched any dev videos/twitch, the github is open, and its now someone elses problem. That sounds like its only for people who have a voice or server favorites, so good luck to you if you try that avenue :D

I mean, it's pretty clearly neither of those. It's legit just an open forum for people to come and say "Hey, I think this should be checked out". Pretty hard to say that's only for people with a voice or are server favorites...

**Comment by TheKingOfJeuno** [comment]
what happened to the rest of tech support members, thought it used to be much bigger

**Comment by slassen** [comment]
This GitHub repo is is not for server feedback or drama. Please only use comments to provide new bug reports or data.

**Comment by statuseffect** [comment]
Too add on to this, "coin" type Cardians should drop Light Crystals. They currently drop Fire.

**Comment by 59blargedy** [comment]
swords, cups, batons adjusted. crystals is a different issue but noted.
