### ISSUE TITLE
Pso'Xja Mimic Bug

### ISSUE THREAD

**Issue by Kusarigama-Eden** [EdenServer/community#2638]
### Checklist

- [ x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x ] I have provided my client version in the details. (type /ver into your game window) 

**VER: 30181205_0** ; Only thing I changed recently as well was adding Enternity addon

**Details:** This seems to only happen AFTER defeating a Mimic in Pso'Xja.  I have been locked 3 times this hour alone. All of the sudden I can not /heal which means I can not logout (must force close), I can not see HP bars and etc in the UI bar and I can not cast on myself. Other people in my LS say they had the same experience. The Mimics are also not always Draw In other party members as well. 

**NOTE:** When I zone it fixes itself and it is awfully tedious to constantly force close or run to the nearest zone to reset it.

**Comment by Shoruto** [comment]
Additional Mimic issue in Pso'xja #2329

**Comment by Shoruto** [comment]
Created a list of all the mimic reports in #3407 including this one.  If you have any additional information to provide, reply to that report.  Thanks.
