### ISSUE TITLE
Fishing - Angler Senses

### ISSUE THREAD

**Issue by Siushaga** [EdenServer/community#264]
While fishing in Selbina from 0 to 2 skill, I was targeting Cobalt Jellyfish with Clothespole and Little Worms. I was also wearing +4 fishing gear items. Anytime I would receive the message "Your keen angler's senses tell you that this is the pull of a cobalt jellyfish!" the fish HP bar would immediately deplete and can complete the catch without playing the mini game.

**Comment by Setz0r** [comment]
this was a bug in the formula that calculates "critical bites"  it should have already been resolved
