### ISSUE TITLE
[PLD] Shield Bash merit reduction not 12s even after the increase cooldown from last patch

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2640]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

When Shield Bash was 5 min cooldown you could merit it down to 4 minutes by droping it's cooldown by 5 merits in it's cooldown reduction (Was 12s for each merit not 6s as it is now).

And Rampart STILL isn't fixed 16 months after it was reported it gives no hate/defense buff to PT members and way too weak magic shield. PLD getting nerfed without fixing the obvious bugs hurts.

**Comment by Lilswitche** [comment]
Back when it was a 5 minute recast on shield bash, each Shield Bash Recast merit was worth -10 seconds.  Currently, they are at -6 seconds.  

Proof: [Old Wiki page for Merit Points](https://ffxiclopedia.fandom.com/wiki/Category:Merit_Points?oldid=731836)

**Comment by Tjonke** [comment]
Yeah -10s it was, just know it wasn't -6 as currently. Sorry for the confusion
