### ISSUE TITLE
Aerns in Garden of Ru'Hmet don't appear to reraise.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#2641]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [N/A] I have provided my client version in the details. (type /ver into your game window)

### Details

Farmed a couple Ix'DRG and Ix'DRK last night and I don't recall seeing a single aern reraise after defeat (aside from Ix'DRK).  I have not yet tested Palace yet to see if the mechanic is in place and the last time I was outside in sea the mechanic was working (Could someone that has killed aerns outside recently confirm?). 

Either the mechanic appears to be missing or the rate is too low.

**Comment by perkuprightmeow** [comment]
They do re-raise in palace. Can't comment on proper rate etc. but the mechanic is there.
