### ISSUE TITLE
Aw'aern/Ix'xaern MNK attack speed is way too fast

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2644]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Not sure what the root cause is, maybe double bonus from being MNK/MNK or something, but Aerns in sea seem to be permanently attacking at almost 100 fist speed. Very spooky.

**Comment by 59blargedy** [comment]
is it just ix'aern mnk and his helpers? if so, when they go into bracelets mode this is normal behavior for them. their attack speed is insane.

**Comment by perkuprightmeow** [comment]
No, it's all aerns inside of sea. It might extend to outside, not sure.

**Comment by Falaras** [comment]
The ones outside don't have that issue, killed a lot of those bastards for very few organs.

**Comment by 59blargedy** [comment]
Here's how fast they should be attacking with and without bracelets (from retail)
https://youtu.be/wxlrTDq8cH0

**Comment by Slamm21** [comment]
looking at that video, the Eo'aerns seem to be hitting as if in bracelets mode 100% of the time
