### ISSUE TITLE
Skeleton Key should be able to open coffers

### ISSUE THREAD

**Issue by rwaffle** [EdenServer/community#2646]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

The 3/28 patch removed THF's ability to pick coffers with Skeleton Keys. I'm not sure where information was gathered to suggest that this should be accurate, but sites and posts from 2007 and prior indicate that coffers can be picked with Skeleton Keys. 

I think, although I'm not sure, them not able pick coffers came from this note on wiki:

https://ffxiclopedia.fandom.com/wiki/Skeleton_Key?oldid=1671891

![image](https://user-images.githubusercontent.com/50626123/78721558-c4112500-78f5-11ea-8322-87bc3be1cc5d.png)

This note was added in 2018, and seemingly refers to brown treasure caskets that spawn in the field when killing enemies (referenced here in a FFXIAH comment: https://www.ffxiah.com/item/1115/skeleton-key) . The era date of this page does not contain this note. 

https://ffxiclopedia.fandom.com/wiki/Skeleton_Key?oldid=261198

Guides and forum posts from this era also speak to Skeleton Keys used to pick coffers.

https://ffxi.allakhazam.com/db/item.html?fitem=3627
https://ffxiclopedia.fandom.com/wiki/Picking_your_Coffers_and_Chests?oldid=366679
https://www.ffxionline.com/forum/ffxi-game-related/race-job-type-q-a/thief/33363-thief-tools-living-key-skeleton-key-work-on-af-coffers

This should be reverted to what it was prior to the 3/28 patch.

**Comment by 59blargedy** [comment]
resolved in 11/2 update
