### ISSUE TITLE
Diorite dropping from Aura Statues

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#2647]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Technically with our cutoff date these statues should be dropping these, as Ullikummi was changed in 2007, but I'm not sure if this was an intended change or not. If it was intended, there is no ??? to spawn it.

Version: 30181205_0

**Comment by Mozzy4Ever** [comment]
The diorite system was implemented on retail due to RMT. Eden doesn't include RMT-related changes.

**Comment by Oyaziiiiiii** [comment]
I'd argue that was more of a broken system change rather than an RMT change, but it's debatable. It made no sense to have Ulli act as that much of a bottleneck.

**Comment by Mozzy4Ever** [comment]
http://www.playonline.com/pcd/update/ff11us/20070308c2bbd1/detail.html

It was definitely an RMT related change.

**Comment by Oyaziiiiiii** [comment]
Maybe. Not here to argue that though, just pointing out that we had one drop earlier
