### ISSUE TITLE
Bard Song Fowl Aubade Will Not Cast

### ISSUE THREAD

**Issue by aprilgarrity** [EdenServer/community#2650]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

version: 30181205_0

1) Be BRD
2) Try to cast Fowl Aubade in any circumstance
3) Receive "<me> cannot cast Fowl Aubade."

This spell is useful for the Diabolos fight for CoP as it will reduce the duration of Nightmare. Thankfully I tested to see if this spell worked before going to the arena. Multiple people in my linkshell have the same issue where they cannot cast this spell.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
