### ISSUE TITLE
Hu'Xzoi one way teleport at G9/10 going south not functional

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#2651]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

https://www.bg-wiki.com/bg/File:Grand_Palace_of_Hu%27Xzoi-map2.jpg

At G9/10 of the Hu'Xzoi basement (map linked above), should allow player to travel south via one way teleporter. This is not functional and is instead a dead end.

**Comment by icariumkupo** [comment]
Want to add that this makes camping Ix'MNK more tedious. Because instead of being able to travel from the West side to the East side, the player must instead escape and perform two escorts to get to the eastern spawn point.

**Comment by Garphilius** [comment]
Yes, please, fix this. Having to escape and re-run escorts on opposite side is tedious and a waste of time when farming Ix'aern MNK.
