### ISSUE TITLE
BST jug Tiger "Claw Cyclone" hit mobs a floor above

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#2652]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Was in upper Delkfutt's farming a key for my BST axe and I used claw cyclone in the room with the magic pots. It also hit Incubus bats on the floor above. Needless to say they came down and tried to kill me.

**Comment by statuseffect** [comment]
Did it again with other conal TP moved from other jug bets.

**Comment by 59blargedy** [comment]
this was resolved by the line of sight changes a while back
