### ISSUE TITLE
Monk merit point group 2

### ISSUE THREAD

**Issue by trollsc** [EdenServer/community#2653]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by FariskaEden** [comment]
I merited 3/3 in Invigorate and receive the correct duration and regen effect. Can you give more details when you used the ability? It should only work at level 75 and not when level synced.

**Comment by trollsc** [comment]
It is working today. I trying to delete post.
