### ISSUE TITLE
Tiny Mandragora are not supposed to attack twice.

### ISSUE THREAD

**Issue by Kythaela** [EdenServer/community#2654]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

Tiny Mandragora outside Windy zones attack twice like a MNK when they are only supposed to attack once.

**Comment by roriffxi** [comment]
They also have guard, which they shouldn't have.

**Comment by 59blargedy** [comment]
resolved 11/2 update
