### ISSUE TITLE
Jailer of Fortitude sometimes doesn't spawn with pets

### ISSUE THREAD

**Issue by slassen** [EdenServer/community#2655]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

Found by players, Jailer of Fortitude sometimes does not spawn with its adds. This was not reproducible on my local machine so I'm writing this ticket in hopes that over enough spawns, reproducible steps are found. Please post here if you have additional details regarding this.

**Comment by 59blargedy** [comment]
dont believe this occurs anymore / cannot reproduce
