### ISSUE TITLE
Iron/Steel Splitters Synthesis Skillup Issue

### ISSUE THREAD

**Issue by avethecook** [EdenServer/community#2656]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

There seems to be an issue with Iron Splitters and Steel Splitters not giving proper skillups. I am 97WW (three levels under synth cap) and have crafted 3 stacks of adaman ingots worth of Iron Splitters (~30 splitters), which I then turned into steel splitters (~30 more). I also desynth'd all of those steel splitters. I did not receive a single skillup in the ~90 total synths. I get that 97-100 is supposed to be hard, but there is something very wrong with this particular synth. I have multiple other 100 crafts and have never encountered anything like this before on Eden.

There was a similar issue posted last year which is now closed. The user commented that he finally received 0.1 skillup on one of them, but didn't mention what level WW he was at. 
https://github.com/EdenServer/community/issues/1783

Is there any chance these are incorrectly capped at 97, or that some other issue is at play?

Thanks!

v30181205_0

**Comment by slassen** [comment]
The synth and desynth are set to 100WW. It may be something with the odd trend we’ve been having with RNG.

**Comment by avethecook** [comment]
> The synth and desynth are set to 100WW. It may be something with the odd trend we’ve been having with RNG.

I’m very appreciative of the quick reply - but can you please provide any more details? What do you mean by odd trend? Is there an open ticket that discusses the problem in more detail? Is it something that’s currently being investigated? 

Is this RNG issue crafting skill-up specific? Should I stop skilling up until it’s resolved? If this really is a potential bug, I’ve already wasted millions, and any heads up at all that I should sit tight and wait it out is something that would be really nice to know. Again really I appreciate your feedback.
