### ISSUE TITLE
Cactrot Rapido

### ISSUE THREAD

**Issue by Elysien** [EdenServer/community#266]
It's claim method is incorrect, and because it runs even faster than it did on retail, I couldn't try conventional means of claiming. The latter shouldn't be possible, it should completely ignore all attacks/ja/spell made against it, and just keep on running. It might actually already ignore conventional means of claiming, but I gave up trying to test if it could be after 30mins of unsuccessfully making a clear shot at it.

As for how it should be claimed, it should only be able to be claimed by claiming a local Sabotender, and Cactrot Rapido "linking" to it. The link range was round about 10yalms. Currently on Eden, Cactrot Rapido directly ran through the Sabotender I had claimed, and did nothing, as if to say "you're on your own, kid".

Seriously though. Cactrot Rapido drops quite a valuable item, and I wanted to see how the NM functioned. I wasn't able to do that, so I'll just give a basic rundown of what the NM should be doing. It might already have most if not all of it there, I just was not able to confirm. 

-Immunity to Sleep, Bind, Stun, and Gravity.
-150 Base delay.
-10% Double Attack Rate.
-Access to the ability "10,000 Needles".

Those are the major things, some minor things that are animation related:
-Cactrot Rapido would kick up sand as he roamed, does not currently have this on Eden.
-Cactrot Rapido has a unique Cactaur melee animation, in addition to normal Cactuar melee animations, Cactrot Rapido would also perform a jumping kick.
-Movement Speed should be 250%, seems to be 300%, possibly more. It's run speed is pretty irrelevant though when it's proper claim method is implemented. 

The aforementioned aren't really a big deal, but they're pretty cool.

**Comment by Wiggo32** [comment]
This NM has not been fully implemented yet. It's going through some balancing and comparison to retail data.  It has only been given script to "run" around the desert. Once it is complete and ready, linking will be activated and an announcement will be made to the forums. Thanks for the info on what it's supposed to do/have... that is always helpful.

**Comment by beerking27** [comment]
any update or word on this being implimented?

**Comment by greyenvy** [comment]
When will this be ready to implement?  The behavior reported above is the same today as it was in November.  Thanks.

**Comment by KnowOne134** [comment]
Has been completed
