### ISSUE TITLE
Aquarius has improper attack speed.

### ISSUE THREAD

**Issue by ZariusCane** [EdenServer/community#2660]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)  Ver: 30181205_0

### Details

https://www.youtube.com/watch?v=cYtEVpQlEB4

Video from 2007, currently on Eden, Aquarius has normal crab attack speed.  Aquarius is supposed to have enhanced attack speed. 

https://ffxiclopedia.fandom.com/wiki/Aquarius?oldid=407595

*Hits extremely fast and hard, but inaccurate.
*Has extremely high defense
*Special Attacks: Additional Effect: Enwater

**Comment by E5una** [comment]
Wiki also indicates that he should be immune to sleep, yet this is not the case on Eden.
