### ISSUE TITLE
Jump/High Jump not claiming monsters

### ISSUE THREAD

**Issue by Satirof** [EdenServer/community#2664]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver: version 30181205_0

Since the changes to yellow/red on monsters, Jump and High Jump will no longer claim mobs if they are the first attack. If you use one after another then the second will claim.

Tested this while solo, with both weapon out and idle on Robber Crabs in Boyahda.

1: Find a monster
2: Target monster and use Jump or High Jump
3: Damage/hate goes off (monster engages user)
4: Monster stays yellow until next action is performed against it.

**Comment by KnowOne134** [comment]
Fixed in today's update
