### ISSUE TITLE
The Mhaura -> Al Zhabi Captain NPC (Adeben) says you'll be arriving in 0 minutes the entire ride

### ISSUE THREAD

**Issue by joeis78** [EdenServer/community#2666]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Talk to the NPC at any point during the ride from mhaura to al zhabi and he always reports 0 minuts (less than 1 hour) until arrival.

**Comment by Frozzen907** [comment]
This appears to be happening agian~
