### ISSUE TITLE
Blood Pacts do not have damage types correct

### ISSUE THREAD

**Issue by slassen** [EdenServer/community#2667]
Filing this on behalf of Jailers testing results. This was found fighting Jailer of Temperance which should have immunity to different forms of damage at a time. Each physical blood pact should also have a specific damage type: slashing, impact/h2h, piercing.

> SMN non-magic pet moves (non-merited blood pacts etc.) always damage regardless of phase/type
Blunt vs. non blunt smn damage makes no difference

**Comment by 59blargedy** [comment]
resolved 10/18
