### ISSUE TITLE
Shadowbind is classified as bind

### ISSUE THREAD

**Issue by slassen** [EdenServer/community#2668]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

30181205_0

Shadowbind should be classified as it's own type of bind in a way similar to light sleep is classified differently from dark sleep. It's unknown if other abilities like Shadowstich should be classified as magic or "ability" bind. To test this try fighting a monster that should be immune to bind magic but not ability bind like Shadowbind.

**Comment by Slamm21** [comment]
An example on this is you could not bind AV but Shadowbind would work

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
