### ISSUE TITLE
Self-Destruct damage (or resist rate) from Kabooms may need to be investigated

### ISSUE THREAD

**Issue by nickycupcakes** [EdenServer/community#2669]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version:  30181205_0

Disclaimer:  I don't know if this is actually an issue or not, because it could just be chalked up to "luck" but I feel like I've been hit by Self Destruct often enough to be able to pinpoint this as more than just a statistical anomaly.

I have been battling Kabooms in Garlaige basement, and the most damage I have received from a Self Destruct has been 58 points.  The enemy is usually at low HP when it Self-Destructs on me (under 35%), which I know lowers the damage, however it's been a consistent 50-58 points of damage each and every time I get hit.

My Fire Resist is at "6" and my gear is pretty terrible (and I only have access to Shell 1) - so I'm pretty sure I should be seeing higher numbers, especially when my pets are taking 200-800 points, and I only get hit for 50 or so.

Would love to know if there's indeed something wrong, or if not, that I'm OK to continue XPing in this location.

**Comment by Shoruto** [comment]
Related #3191 #2685

**Comment by panfunk** [comment]
I have a theory concerning this issue.
I think the self-destruct target with the highest threat takes a significant higher damage from the attack.
I noticed this camping Big Bomb. 
My RDM never took enough damage to break stoneskin when the PHs blew up, while my THF almost died.
But when I TA'WSd my RDM and he took hate, he died to SD several times, while my THF took little dmg.

**Comment by 59blargedy** [comment]
resolved in June 28th, 2021 update
