### ISSUE TITLE
Fishing - Coral Fragments.

### ISSUE THREAD

**Issue by Elysien** [EdenServer/community#267]
As per request by Setzor, making this bug report. Apparently Fishing Skill of 40 is required to fish these in Sea Serpent Grotto. That is, however, incorrect. To my knowledge, all fished items can be reliably fished with any combo of rod/lure at lv0 fishing.

I could be wrong about that, but I'm not wrong about it for Coral Fragments.

Wiki link:

https://ffxiclopedia.fandom.com/wiki/Sea_Serpent_Grotto

**Comment by Setz0r** [comment]
this is confirmed to be an issue.  i will be removing the requirement for fishing skill on items

**Comment by Setz0r** [comment]
This was fixed in the last fishing update released.
