### ISSUE TITLE
BCNMs Showing "xxx is full" when no one is inside BCNM + BCNM status not clearing when you run away 

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2670]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Haven't experienced this personally, but there's been several reports on it. When a group is ready to enter a BCNM it will say it's full, despite everyone in /sea being outside the battlefield and accounted for. 

Unsure if they have run away from a fight previously, because to add, currently when you 'Run Away!' from a fight your BCNM status does not clear and is only fixed by zoning.

**Comment by 59blargedy** [comment]
i dont think this is an issue anymore, but will reopen if you think it remains
