### ISSUE TITLE
Storing Egg Helm in Armor Depository causes Moogle to request "First 3" combination again, locks out other combos

### ISSUE THREAD

**Issue by Dribblet** [EdenServer/community#2672]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Ver 30181205_0

Initially traded SARUT when Windy controlled the region, got Wing Egg (Sandy Egg). Eventually the wrong region reward bug was found and fixed to my knowledge, however even after attempting different combinations I cannot get any new furniture eggs. Throwing away my Wing Egg furnishing does not let me trade initial eggs for a new furnishing egg, nor can I repeat combos to get all 3. 

In-era it should be that I can repeat region egg combos until get all 3 furnishing eggs:
https://ffxiclopedia.fandom.com/wiki/Egg_Hunt_Egg-stravaganza_2006
"Repeatable - Yes, as long as you do not have all three furniture eggs yet."
 (Also in-era 2007 I should be able to get jeweled egg too but i'm focusing on getting my Windy Egg rn)

plz bugfix, plz

**Comment by xizeta** [comment]
There's nothing in the code preventing you from re-obtaining the same furniture, it just won't complete the trade if you currently have it. There is also nothing saved (eg. windurst_egg = 1) when you receive a furniture so it's impossible for obtaining the Wing Egg to have locked you out of any other furniture.

Please be more specific about which combos you are using
Also, make sure you have inventory space.

The update specifically says this is 2006, so there will not be a Jeweled Egg this year.

**Comment by Dribblet** [comment]
"it just won't complete the trade if you currently have it."
I threw away my Wing Egg, there should be 0 reason why I'm still counted as having it.

"However, you can only receive one reward per Vana'diel day."
It was the 1st reward of the day, and it gave 0 dialog, as in nothing, no "You can only receive 1 reward a day" prompt, it didn't even acknowledge my combo. I also had the space but even then it'd tell me I couldn't obtain the "x" until I sort my inventory if so.

Tried SARUT for Sarutabaruta initially on Saturday (worked but wrong egg) and then after conquest update (no message, nothing), and also ZULKH for Zulkheim. Both tried after conquest update, neither produced a valid result nor did the moogle comment that they were even valid combinations.

**Comment by Dribblet** [comment]
Tried SARUT on alt, they got Lamp Egg (Bastok egg, Saruta is owned by Bastok atm). Tried once more on main and nothing. Tried all 3 nation combos (ZULKH, SARUT, FAURI) none worked.

There might be some issue where players that got incorrect furniture eggs before the patch are affected and can't get new furniture eggs

**Comment by Dribblet** [comment]
Update: tested 3 more combinations after maint (SARUT, FAURI, ZULKH) with the moogle, all failed, however I seem to have found the problem:
Putting your Egg Helm in the Armor Depository seems to reset the moogle to wanting the "first 3" request, and locks out any other combinations from being fufilled as a result. After I pulled my Egg Helm out of the depository, it allowed me to turn in my region combinations like normal.

**Comment by xizeta** [comment]
Many other event guides on the wiki tell you that you must remove the relevant items from storage for them to be considered already acquired. I do not think this is a bug.

But I'm glad you were able to resolve the issue.
