### ISSUE TITLE
All Fomor link by sound

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2673]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently in Sacrarium fomors not in a party link with each other. When fomor are in a party together they usually move together as a group. Below is a rough map of where I found fomor parties in Sacrarium from retail (number indicates the size of the party).

![image](https://i.gyazo.com/f9c27b75f0f988a997a80eee3f76c5f4.png)

H-11 on this map had the only odd setup of fomor parties as they do not roam together but sit still while within this room on retail.
![image](https://user-images.githubusercontent.com/46270382/79074408-2ed9ac00-7cba-11ea-81c6-edd993d40ad0.png)
https://i.gyazo.com/be2cbbd8fc5784ca18f85b4c1d2ea3bd.mp4

Also this shows non-partied fomor not linking on retail.
https://i.gyazo.com/ca0adb262dae1ceb5f82366f3578e735.mp4

https://ffxiclopedia.fandom.com/wiki/Sacrarium#Regular_Monsters_Found_Here

version 30181205_0

**Comment by FariskaEden** [comment]
So I think that the issue is all fomor link by sound rather than only linking with the party they spawned with (no cross party linking), regardless of area. From retail 2 party behaviours I've noticed are: they stand still together as a unit (usually in a triangular formation or a line) and they roam together almost like following a party leader. 

https://i.gyazo.com/76e6242ade7eaaf927f4cc1a698b6b48.mp4 shows party following behaviour

Went into Phomiuna Aqueducts on retail and made maps of where fomor parties are in the zone.

![image](https://user-images.githubusercontent.com/46270382/79641854-fdecf180-8167-11ea-8af5-d1d74713f352.png)
![image](https://user-images.githubusercontent.com/46270382/79641858-034a3c00-8168-11ea-9d82-60cd0e8dc270.png)

Notes about some of these parties:
Map 2 C-8: Stand still in a triangular formation.
![image](https://user-images.githubusercontent.com/46270382/79641954-bca91180-8168-11ea-9846-81a615b88c40.png)
Map 2 E-8 & E/D-4/5 Intersection: Parties stand still in a line within the middle of these rooms.

The other parties in the zone patrol a small area roughly where the markers are placed. Also on Eden in the Map 3 F-8 lever puzzle room there are fomor present, should be no fomor present in that room.

**Comment by FariskaEden** [comment]
Party compositions always seem to be the same on each respawn on retail. Updated the Sacrarium map to show how fomor are partied up there.

**Comment by 59blargedy** [comment]
this is (generally) resolved in April 18, 2022 patch. follow up reports on mob behavor (i.e. the party following) to bring this down to what's left would be appreciated
