### ISSUE TITLE
[Egg Hunt] No rewards for turning in: 1. 5 letters from Beastmen controlled region name and 2. ORPHIC

### ISSUE THREAD

**Issue by By-T0r** [EdenServer/community#2674]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

Issue 1.
I've turned in 'MOVAL' for Movalpolos, which is currently controlled by Beastmen, and got no reward for it.
I haven't got any rewards on the same game day besides 2 eggs (1 daily plus 1 from party member).
The wiki states the following:
"Other Rewards
- Trading the first five letters for a Beastman controlled region will get you a Beastman Costume."
https://ffxiclopedia.fandom.com/wiki/Egg_Hunt_Egg-stravaganza_2006

Issue 2.
No rewards for turning in 'ORPHIC'.
As per wiki:
"Trading the letters for "Orphic" will get you a Beastman Costume."
https://ffxiclopedia.fandom.com/wiki/Egg_Hunt_Egg-stravaganza_2006

**Comment by tengokujin** [comment]
I used the 2007 guide and got an Orphic Egg by trading the element on the element day.
I have a related issue where the moogle is not rewarding a Jeweled Egg for turning in a region 5-letter after getting each nation egg nor any other B-tier rewards.
I am unsure if this is a lack of the feature or a bug.

**Comment by By-T0r** [comment]
Event gone.
