### ISSUE TITLE
Zilart Mission 3 CS prevented by Dagger of Trials (Quest) being active.

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#2675]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

The cutscene for Zilart Mission 3 will not load if a player has the Dagger of Trials quest active.  In order to trigger the cutscene the player has to quit the quest and drop the dagger for it to work.  If not the dialogue for Dagger of Trials will take priority.

**Comment by ibm2431** [comment]
[A fix for this issue was PR'd to Topaz about a week ago.](https://github.com/project-topaz/topaz/pull/452)

**Comment by KnowOne134** [comment]
Corrected some time ago
