### ISSUE TITLE
Bin Stehihna (Windurst Vendor: Zulkheim) unable to Buy or Sell

### ISSUE THREAD

**Issue by Shika10** [EdenServer/community#2676]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

This vendor gives the initial greetings text, but does not offer the buy or sell options. Windurst is currently in control of Zulkheim.

version 30181205_0

**Comment by bkesecker** [comment]
This NPC has been live edited and should now be presenting a shop (if Windurst is currently in control of Zulkheim).
