### ISSUE TITLE
Fighting or killing Boggelmann (With a puppet?) is causing the entire Tav region to crash.

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#2679]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver. 30181205_0

Happened twice as my puppet finished the mob with a ws.

Happened a third time when the mob readied Hungry Crunch on my puppet.

I might have to try it on a different job...

**Comment by KnowOne134** [comment]
Told it was fixed. Comment to open if still an issue
