### ISSUE TITLE
Fishing Guild Fish Tanks

### ISSUE THREAD

**Issue by SaberSuper** [EdenServer/community#268]
Uhh the fish in the fish tanks at the fishing guild shop are upside down, is that normal? lol

**Comment by Wiggo32** [comment]
The fish in the fishing tank at the fishing guild on retail are exactly the same as the fish in the fishing tank at the fishing guild on eden. That's hardcoded into the client and would need dat modification if someone would want it changed. But, then it wouldn't be retail accurate! ;-)
