### ISSUE TITLE
Sickle Slash damage too high

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#2681]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Aht Urgan Ahtercops Sickle Slash went from doing 2-300 damage last week, to doing 800+ this week to a level 57 sync Samurai. It wasn't listed in the patch notes as a tp move that was changed so not sure if this is a bug or working as intended now. 

VER: 30181205_0

**Comment by 59blargedy** [comment]
this should have been resolved in the recent mob and mob skills update, can comment if not the case and will reopen
