### ISSUE TITLE
Self-Destruct used by Nitro Clusters in Riverne - Site #B01 is hitting for 1610 damage consistently

### ISSUE THREAD

**Issue by tobioeden** [EdenServer/community#2685]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Nitro Clusters in Riverne - Site #B01 were used Self-Destruct for 1610 damage at under 10% hp 3 times in a row, on two different characters, seems to be a set damage value (maybe checking against full hp?).

version 30181205_0

**Comment by re1master** [comment]
Feu Follet in Gusgen Mines appear to be hitting for under 100 HP with Self Destruct. Attacks have ranged between 30-90 from what I've seen.

**Comment by Serephim** [comment]
Easy Prey Atomic Cluster just hit me for 1410 in Misaraux Coast while trying to learn refueling. It was at 1% HP, and I was just letting it hit me to use TP moves. Did 41 damage the first time, 59 the second. Then I left the room to get water, came back to a 1410 and a corpse. lol

**Comment by Serephim** [comment]
Snoll also hits 75 WHM for 680 with Hypothermal Combustion through a fresh stoneskin. Hits 54 BLU next to him for 63 damage. The damage calculations for these abilities is beyond broken.

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
