### ISSUE TITLE
Lost Yhoator Gate Crystal Key Item.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#2686]
### Checklist

- [/ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ /] I have provided my client version in the details. (type /ver into your game window)

### Details
I lost my Yhoator Gate Crystal I had for years at some point and just noticed it when a GM checked into it for me. Don't know what caused it or how to reproduce it. But the GM told me to create a bug report for it just for future reference.
Version 30181205_0

**Comment by Slamm21** [comment]
Did you try logging out and back in?

**Comment by Serephim** [comment]
I'll try that now

**Comment by Serephim** [comment]
> Did you try logging out and back in?

Completely logging out and out in not work.

**Comment by KnowOne134** [comment]
seems a 1x issue and not something that has reoccurred, a server kickup somewhere that isnt reproducible
