### ISSUE TITLE
Imperial Signet removed TP on rest

### ISSUE THREAD

**Issue by dakumauler** [EdenServer/community#2688]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

**Comment by 59blargedy** [comment]
sanction does not offer the same benefits as signet. tp removal on resting is correct behavior.
https://ffxiclopedia.fandom.com/wiki/Sanction

**Comment by dakumauler** [comment]
So the link you shared does not say that it removes TP as you recover HP. took the time to read it all does not say it any place. So not sure that is correct.

**Comment by Falaras** [comment]
Keeping TP  is not the default while resting. The wiki would only state if the buff allowed you to go against the default, which it does on both Signet and Sigil because they both allow you to do that. Sanction does not mention TP at all because it never has kept TP at all.
