### ISSUE TITLE
Beastmasters- terrorists!

### ISSUE THREAD

**Issue by Calamityjrx** [EdenServer/community#2689]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Is charm working as intended ?
Charmed and released monsters (or monsters that were hit by Bst's pet) once regain 100% HP Should give experience points! 
The way they do when a player hit a monster (a worm for example) then run away to deagro. When worm regain full HP it gives full exp. 
At the moment Beastmasters can create diversions... Go to any exp camp, charm-release all mobs and leave.. Ppl who will come to the camp will enjoy a few kills w/o exp.

**Comment by greyenvy** [comment]
This is called "griefing" if done on purpose and it is warnable/bannable.  Report anyone doing this intentionally.
