### ISSUE TITLE
Sozu Bliberry might be set as a timed spawn instead of a lottery

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2690]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I have no hard evidence of this, but Sozu Bliberry is always up when I walk by. They are supposed to be a lottery spawn, so I wouldn't expect them to always be standing there unless they were a timed spawn. Can someone just check on this?

version 30181205_0

**Comment by greyenvy** [comment]
I reported all the Tonberry NM problems about 10 months ago. 

Related: https://github.com/EdenServer/community/issues/1789
