### ISSUE TITLE
COR testimony.

### ISSUE THREAD

**Issue by LayZeeGamer** [EdenServer/community#2691]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

There is something really wrong with the drop rates on COR testimony. I feel that the rng for this supposed 13% drop is actually .01%. I've lost count on the numbers of Lamia that were slain with no avail drop, with help from TH0 - TH4. Please check into this.

**Comment by bkesecker** [comment]
Make sure you are targeting these.  https://ffxiclopedia.fandom.com/wiki/Corsair%27s_Testimony?oldid=337566

Also, found that 2 of the 4 groups do not have the item in their drop table.  You may need to experiment with defeating different groups until it is fixed.
```sql
SELECT * FROM dspdb.mob_spawn_points WHERE mobname LIKE '%Fatedealer' OR mobname LIKE '%Icedancer';
SELECT * FROM dspdb.mob_droplist WHERE dropid IN (1998,1999,2249,2250); -- itemid 2332 is missing from dropid 1999 and 2250
```

**Comment by LayZeeGamer** [comment]
> Make sure you are targeting these. https://ffxiclopedia.fandom.com/wiki/Corsair%27s_Testimony?oldid=337566
> 
> Also, found that 2 of the 4 groups do not have the item in their drop table. You may need to experiment with defeating different groups until it is fixed.
> 
> ```sql
> SELECT * FROM dspdb.mob_spawn_points WHERE mobname LIKE '%Fatedealer' OR mobname LIKE '%Icedancer';
> SELECT * FROM dspdb.mob_droplist WHERE dropid IN (1998,1999,2249,2250); -- itemid 2332 is missing from dropid 1999 and 2250
> ```

Day 3 of farming in Mire, it is finally obtained. Now "Breaking bonds" for COR is not working. Checked the ??? for a cs and after trading the testimony in Arrapago it warped me to Talacca, which now will not let me enter for the fight. I have the quest flagged on my log.

**Comment by bkesecker** [comment]
Breaking Bonds is working, but confirming it is broken on a non-GM character.

**Comment by andrewj3191** [comment]
@bkesecker , is there a plan to address this quickly?  I'm stuck at 70 now as this is my first job there.

**Comment by Ladypinky** [comment]
Same issue but for PUP BCNM. Trade door testimony, but upon entering there's no mobs in the room, just empty. Doesn't appear to consume/break the testimony though.

**Comment by bkesecker** [comment]
> @bkesecker , is there a plan to address this quickly?  I'm stuck at 70 now as this is my first job there.

I made a live edit.  Please try again and let me know if working or not.

**Comment by LayZeeGamer** [comment]
> > @bkesecker , is there a plan to address this quickly?  I'm stuck at 70 now as this is my first job there.
> 
> I made a live edit. Please try again and let me know if working or not.

Able to enter the fight for COR, Thanks.
