### ISSUE TITLE
Elemental resistance to elemental weapon skills is too high

### ISSUE THREAD

**Issue by rpcon** [EdenServer/community#2694]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Weapon skills like cyclone and gust slash should be doing roughly twice as much damage as the are against all elementals except air.

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 patch
