### ISSUE TITLE
Level 74/75 Homunculus is hitting for 18 damage vs Level 64-66 mobs.

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#2696]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I pulled out a Homonculus with /checkparam stats of 282 acc, 288 att (he should be level 74 or 75 because I used AF2 gloves) and he's hitting for 18 damage vs. Spriggans in Eldieme -- should be like level 64-66 mobs.

CC was hitting for like 125.

**Comment by 59blargedy** [comment]
resolved in December 21, 2020 patch
