### ISSUE TITLE
ISNM 75 Jade Sepulcher "Puks" not working

### ISSUE THREAD

**Issue by AnkleAssassinz** [EdenServer/community#2697]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
 I tried to do this ISNM today(4/16/2020) with 4 people but when we zone in, there were no puk mob to kill. Luckily our rdm subbed blm for escape. 
  This ISNM used to work before.

**Comment by KnowOne134** [comment]
Fixed in today's update
