### ISSUE TITLE
Dalham (PM 7-4 NM)

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2698]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently Dalham attacks like a regular sea monk (2 attacks per round) it should start off by attacking once per round and has an ability that increases the number attacks it gets per round by 1(activates when it reaches around 70%, 40%, & 15%).

https://www.youtube.com/watch?v=HxSTQmNiW_Q

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
