### ISSUE TITLE
Magic Acc. Issues

### ISSUE THREAD

**Issue by Aeniesh** [EdenServer/community#27]
In a dunes party with lv sync @15, as blm and ele damage is all over the place. My INT is 22+7 w/o food and out of 10 cast, 3 were actual dmg (55-70) and the rest were just horrible (8-12)

**Comment by roriffxi** [comment]
In addition to the magic accuracy issues, magic damage looks to be off.  It would seem that magic atk bonus (at least from traits) isn't properly affecting magic damage.

with 44+30 int my Fire2 is hitting for 210 unresisted against Dancing Jewel in Crawlers nest at level 40.

If i remove my gear and have 44+3 (food was still in effect) and this dropped my unresisted dmg to 183.  Exactly 27 points less, which is how much int was removed.

Being a lvl 40 black mage I should have +24 MAB from traits, which is affected by INT, so you'd expect roughly 1.24 points of damage added /removed per point of int added / removed

**Comment by MGramolini** [comment]
I was also seeing 3/4th resist using burst2 on fafnir.. 450ish damage on a MB. He can also no longer be hit by water or wind spells accurately like kupo, not sure what retail was like.

**Comment by MGramolini** [comment]
Iirc rori, int wasn’t always 1 dmg per point. There is a lot of other math involved including spell tier and dInt. I haven’t thoroughly tested MAB yet so I can’t be sure.

**Comment by Lilswitche** [comment]
Fafnir on retail had no resistance to Thunder, Wind, Water or Earth based nukes.  Fire/Ice on the other hand - good luck.

**Comment by MGramolini** [comment]
After a certain amount of dInt, You will likely only see 1 dmg per 2 int on T1/2 spells and eventually they cap. I would try to see 1-2 int at a time what the unresisted dmg is but I’m guessing the math is correct in this case.

Resistance is definitely wrong however

**Comment by roriffxi** [comment]
Tier2 spells have a multiplier of 1.  So unless you're hitting the soft cap of dint, adding 1 point of int will add 1 point of damage without magic attack bonus modifiers.

At level 40 against mobs in CN there is no way I should be surpassing the dInt soft cap.

Furthermore, adding 6 points of MAB only increased my unresisted Thunder4 damage against Nidhogg by 6 points.  That is simply wrong.

**Comment by roriffxi** [comment]
Level 54, 58+18 Int.  earth staff.  elemental seal Quake gets 50% resisted by the goblin veternarians bat in 60 cap pso'xja.

Elemental seal should never be resisted by an xp mob unless the mob is somehow immune / extremely resistant to that specific element, which a bat isnt.

**Comment by erenik** [comment]
I agree that the magic burst resistance seems to be off. In dunes at lvl 14 Fire with INT+10 on flies does a consistent 60ish damage, and 80 damage in magic burst, but the resistance when magic bursting seems to be similar as normal casts (e.g. halved, quarter, eighth). During magic burst the resistance should be lower, so mainly proccing 100% damage or 50% if it resists a bit (ofc depending on enemy mob lvl, but for exp parties it would not resist a lot if at all during MB).

**Comment by erenik** [comment]
The rate of half resists also seem much lower than in retail (compared to quarter and eighth), which is described a bit here: https://ffxiclopedia.fandom.com/wiki/Magic_Hit_Rate

**Comment by erenik** [comment]
Just as an example, this should barely be possible, MB max resisting and normal spells full-damaging: 
![image](https://user-images.githubusercontent.com/6832027/55276122-189bc080-52f0-11e9-8ca2-39b30ad0ffb6.png)

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 update.
