### ISSUE TITLE
[PUP] Optimization merit

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2701]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently the optimization merit does not increase the automaton's ranged attack. Each point placed in this merit should also increase the automaton's ranged attack by 5%. Despite the description only mentioning attack it also increases ranged attack like the tension spring attachments do.

https://ffxiclopedia.fandom.com/wiki/Optimization

Eden 75 Sharpshot stats with 3 points in optimization:
![image](https://user-images.githubusercontent.com/46270382/79601967-aa22cf80-80b7-11ea-8e8b-ae5650a3bc40.png)

Retail 75 Sharpshot stats with 3 points in optimization:
![image](https://user-images.githubusercontent.com/46270382/79602000-bb6bdc00-80b7-11ea-9a4b-5813a3bd95c4.png)

version 30181205_0

**Comment by ThrisStraizo** [comment]
So we know if the other parts of the merit are functioning correctly?

**Comment by FariskaEden** [comment]
They should be, I remember when I first took the merits I did comparisons before and after the merits were placed (for attack and defense). Only part I'm not sure of is the magic attack bonus since I didn't really use magic enough at the time I took it.

**Comment by ThrisStraizo** [comment]
I did a ton of nuking, I can say the MATTK part of the merit is working for sure.
