### ISSUE TITLE
NM Sewer Syrup - Bostaunieux Oubliette

### ISSUE THREAD

**Issue by AresHypnos** [EdenServer/community#2702]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver30181205_0

As a lotto spawn this NM is taking 16-20 hours to pop, seems a bit excessive.  Currently in linkshell we are 1/9 on Jelly Ring drops with TH4.

Item Drops: Jelly Ring drops a high percentage of the time, but not every time.
https://ffxiclopedia.fandom.com/wiki/Sewer_Syrup?oldid=373075

The Panna Cotta PH in the hall at H-11, sometimes takes 57 min to re-spawn.

**Comment by 59blargedy** [comment]
adjusted in previous patch/drop rate looks commensurate with rarity
