### ISSUE TITLE
Euvhi behaviors: improper linking/movement; stupor spores; crystal clusters

### ISSUE THREAD

**Issue by RottenUnagi** [EdenServer/community#2703]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

_**Linking**_: In Garden of Ru'Hmet, the Aw'euvhi ('flowers') are linking when they're open (pull Aw'euvhi 'A' while Aw'euvhi 'B' is near it and open, then 'B' links with 'A' though it shouldn't if it's open). They should only link when closed. Aside from that, their aggressive behavior is accurate: aggro while open; non-aggro while closed. I'm unsure about any of the other Euvhi mobs anywhere else, I only interacted with these ones. ~ https://ffxiclopedia.fandom.com/wiki/Category:Euvhi?oldid=32059 (from Jan. 6, 2006)

_**Movement**_: Apparently they should stand still while open, but they don't, they're mobile while open.

**_Stupor Spores_**: This is an AoE TP move that causes sleep. The sleep is wearing off instantly as soon as it's applied. While that doesn't exactly bother me, it's still a bug I noticed.

_**Clusters**_: In the several hours & scores of kills it took me to farm 5x organs & tissues for a Relaxing Earring, not a single crystal nor cluster ever dropped. I'm not sure if region control affects their ability to drop clusters (probably not?), but for reference Tavnazia was controlled by Windurst at the time. _Edit: Derp. Sea is part of Lumoria region anyway, not Tavnazia, and isn't subject to region control_

**Comment by 59blargedy** [comment]
while there are still some euvhi behaviors that aren't correct, these particular issues were resolved in the last year
