### ISSUE TITLE
Savanna Rarabs in East and West Sarutabaruta not dropping Hare Meat

### ISSUE THREAD

**Issue by BigTo20** [EdenServer/community#2704]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0

I killed 40-50 Rarabs across each zone and have gotten 0 Hare Meat drops. The era accurate Eden Wiki states they should drop from the level 1-5 (west) and 1-6 (east) Savanna Rarabs yet neither have dropped a single Hare Meat

**Comment by lemmikens** [comment]
Can confirm on this. They do not drop.

**Comment by Mozzy4Ever** [comment]
https://ffxiclopedia.fandom.com/wiki/Savanna_Rarab?diff=next&oldid=383523 is the last date before our cutoff. There was no drop data for it at that time. Going forward to https://ffxiclopedia.fandom.com/wiki/Savanna_Rarab?diff=prev&oldid=495812 someone killed 106 of them and still no meat. 

http://ffxidb.com/zones/116/savanna-rarab 35097 kills, no meat.
http://ffxidb.com/zones/115/savanna-rarab 19903 kills, no meat.

I don't think they're supposed to drop meat.
