### ISSUE TITLE
Hitting the Marquisate Chandelier NM activating Self-Destruct on /ra

### ISSUE THREAD

**Issue by Mahou81** [EdenServer/community#2705]
- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
 Version 30181205_0
While doing the Quest Hitting the Marquisate, we had issues with the Chandelier NM performing a self-destruct when pulled with a ranged attack, which shouldn't happen. What is even stranger, is that it only seemed to ready the self-destruct, but then not execute it. We still had to kill it ourselves, but then the r/e item for the quest would not drop. What is even more strange, is that the first time I pulled with a ranged attack I hit it and dealt some damage and it did NOT self-destruct and dropped the r/e item. All attempts after this I missed the /ra and it did self-destruct (but not die, not stunned) with no drop as a result. Also, one time my blm friend did attempt a Stun right after I pulled with /ra and it readied the self-destruct, which should've stopped it, but we still didn't get a drop. This was quite frustrating for my friend who still needed it, and me for wasting my time on it.

**Comment by 59blargedy** [comment]
this should be resolved in April 18, 2022 patch, but i couldnt actually replicate the op so was unable to prove. can reopen if still issues.
