### ISSUE TITLE
Funguar Familiar is missing 3 of it's abilities.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#2706]
### Checklist

- [ /] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ /] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ /] I have provided my client version in the details. (type /ver into your game window)

### Details
The Jug Pet Funguar Familiar summoned with Seedbed Soil is missing 3 of it's best ready abilities. "Silence Gas", "Dark Spore" and "Shakeshroom". Silence Gas and Dark Spore should do around 300-600 max to an IT at 60 so it's really rough missing them. Silence Gas and Dark Spore should cost 3 charges each and Shakeshroom is 2 charges.
https://ffxiclopedia.fandom.com/wiki/Funguar_Familiar
Version 30181205_0

**Comment by rpcon** [comment]
PanzerGalahad (HQ tree sap) has no TP moves at all. Jug pet ready pet commands need a full audit.

**Comment by KnowOne134** [comment]
Duplicate issue of 
https://github.com/EdenServer/community/issues/2106
Please comment there with additional info if needed
