### ISSUE TITLE
Carbuncle is much weaker than retail.

### ISSUE THREAD

**Issue by Kurtalicious** [EdenServer/community#2708]
Carbuncle seems to be overall too weak.  His power level needs to be adjusted to be better aligned with retails overall strength.  Carby seems to get hit too often and take more damage than retail resulting in battles that are much harder than intended.  It was communicated in discord that Carbys Att/Acc/Eva/Def are all too low but that Str/Dex/Agi etc are all accurate.  

Below I have linked a video containing 4 other vids.  First vid is someone on retail in 2006, followed by 3 vids of myself fighting the same exact mob on Eden.  I have also linked the discord conversation that lead to me posting this bug report and the follow up conversation that includes some conversation and conclusions of the video.  

Please take a moment to review and address issues as you see appropriate.  

kthxbye

https://www.twitch.tv/videos/594154784

https://discordapp.com/channels/482610771126386688/670754050018377728/700056735192186920

https://discordapp.com/channels/482610771126386688/670754050018377728/700572013676331089

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
