### ISSUE TITLE
incorrect loot on goblin enchanters, labyrinth of onzozo

### ISSUE THREAD

**Issue by StormyEden** [EdenServer/community#2709]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0
Enchanters are dropping gold ore and mythril beastcoins

https://i.imgur.com/2Xl9ExH.png
https://i.imgur.com/i9lBH3C.png
https://i.imgur.com/jyZBYbU.jpg

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
