### ISSUE TITLE
Dynamis Lord overtuned

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#2711]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Overtuned puts it mildly. 

This guy has extreme evasion and defense. Maybe too much HP too, not sure about that, but even 8 kraken club DRKs can fail to slay this beast. By far the hardest enemy on Eden, it's not even close.

SV madrigal + 11 roll hunters + sushi + acc gear and you're still sniffing maybe 50% hit rate.

Should be killable by an average group of well prepared players in a zerg setup. Commonly slain without even a single kraken club DRK on retail.

Perhaps compare stats to something like Kirin?

Please comment on your experience with Dynamis Lord. I've searched, but didn't find any related tickets about his strength.

/ver 30181205_0

**Comment by ThrisStraizo** [comment]
Can confirm, my LS in retail could kill Dyanmis lord with 4 well geared DD zerg parties.  When two full parties of Kraken drks and other additional DD support struggles to down it, something is up.

**Comment by ThrisStraizo** [comment]
Zerg videos of note:  
A normal group lowman zerging https://www.youtube.com/watch?v=ssCWL2qA8Jc
Ridill drks (Which do like 1/4 the damage of KC?) deleting SL: https://www.youtube.com/watch?v=0QzE5ipf9g4

A very standard zerg burning DL in 45 seconds: https://youtu.be/eqdZZf2SZg4?t=150

I'll shift through more videos latter, but Icarium may be right about the accuracy issue.

**Comment by Oyaziiiiiii** [comment]
Tried to melee burn this again after the patch. DRK with max club merits, 2hr madrigals, sushi etc had less than 30% accuracy. Asuran fists did 68 damage, Shark Bite for 464 damage. Safe to say that his physical evasion and defense are still much too high.

**Comment by Mikokiko** [comment]
It was suggested to me to post video here from kills i've done in 2006 

Don't mind trhe music, Sonix is a nerd lol.

https://www.youtube.com/watch?v=6XtyN2DRydY

https://www.youtube.com/watch?v=bErpJWzBcqg&t=27s

**Comment by Falaras** [comment]
This is definitely still a problem
https://imgur.com/digynAw
These were our accuracy levels with Soul Voice Madrigal x2 + Hunters Roll + Opening with Feint. I didn't do a checkparam but I imagine my accuracy was around 550-600 and his Evasion down by Feint and I was at 65% hit rate. Also accuracy shouldn't go below 20%

**Comment by Slamm21** [comment]
with that you should have all had capped accuracy really.

**Comment by VeilEden** [comment]
I think in the video a lot of them used Carb and meats. Without sushi here you’re gonna whiff a ton.

**Comment by GalkaZajin** [comment]
With 560 Accuracy, I should be able to use meats tho...

**Comment by Falaras** [comment]
There is no world where you need Sushi to hit era DL with with nearly 600 accuracy.

**Comment by perkuprightmeow** [comment]
This was our last DL run parse with SV'd melees, mostly sushi, and feint: 
https://i.imgur.com/u7UAMQx.png

Axe, Data, Dyno, Monti, Freddie were K Club DRKs, Contra was on SAM. Haiku I think had mkris DRK, and Relic prob Apoc. Just for reference. 

Curitsh + Trajan THF

**Comment by Slamm21** [comment]
Yeah that is mental, no way should you need sushi on DL.

**Comment by Relic3** [comment]
My 90% was Apoc with Carbonara, but I prioritized Accuracy over HP in gear.

**Comment by Falaras** [comment]
I'm a little surprised by that, seems like we fought vastly different Dynamis Lords? Did you guys use multiple Feints?

**Comment by Relic3** [comment]
Ever since our first DL, we just made sure to have Hunter's Roll, Haste > Accuracy > HP gear + sushi on multi hit drks, and Hunter's Roll, along with the normal SV x2 Madrigals and Feint and it's been fine since.

**Comment by Falaras** [comment]
It's likely a kill speed thing honestly, you guys killed it pretty fast so longer time in Feints high percentage range. Zajin and I both had SV x2 Madrigal + Hunter with Meat and I imagine have pretty similar accuracy to yours and both were in the 60% range. 

Anyways, doesn't change the fact that none of this is era accurate. Here's a video of a linkshell zerging it in 2006 using 1 Song and 0 Rolls on their DPS and the chat log has barely any misses in it: https://www.youtube.com/watch?v=mMNLoVyj7l8

**Comment by 59blargedy** [comment]
resolved december 7 update
