### ISSUE TITLE
Sirocco Kukri lost 100% proc rate of additional effect after today's update

### ISSUE THREAD

**Issue by gilnear** [EdenServer/community#2712]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Client Version: 30181205_0

I noticed after today's update that my Sirocco Kukri's Additional Effect (Wind damage) is not procing 100% anymore, the rate seems to have been decreased by a lot. It should be 100%. It was working yesterday, before the update (it's a new issue). 

https://ffxiclopedia.fandom.com/wiki/Sirocco_Kukri?oldid=196659
Note added on 2/20/2007: `The additional effect: Wind is 100% proc rate.`

Steps to reproduce:
1. Switch to job: Thief
2. Equip Sirocco Kukri in main hand or in off-hand
3. Attack something; The dagger should have an additional effect on every hit

**Comment by KnowOne134** [comment]
Already on the docket to being fixed

**Comment by Slamm21** [comment]
right now the additional effect damage is also extremely low

**Comment by bkesecker** [comment]
Fix will be in next patch.

**Comment by Murgleis** [comment]
Ascalon also does not have 100% proc rate on dragons. Only got it today don't know if it had this issue before. Sounds like it might be connected to this bug report?

**Comment by KnowOne134** [comment]
Make a separate report for each. And no wasnt coded that way yet
