### ISSUE TITLE
PUP LB5 Not functioning

### ISSUE THREAD

**Issue by Ladypinky** [EdenServer/community#2714]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Trading Testi to NPC correctly sends me to Navuko. I trade my testimony to the door and it allows me to select my fight for LB5. After selecting it, it says to please try again later, yet it puts me into the battlefield but there are no mobs inside. >.< Was told PUP LB5 is functioning on Eden or I would've choose something else for my first Lv70+! Help!

**Comment by bkesecker** [comment]
This, and the BLU entry, are both proving to be difficult to figure out.  It looks like startEvent is getting the wrong param3 (CPP) value or param4 (Lua) value.
@Landyr @Ladypinky

**Comment by Ladypinky** [comment]
>.< If anyone can do it, it's you! Thanks for taking a look into it >.<! <3
