### ISSUE TITLE
PUP Achieving True Power

### ISSUE THREAD

**Issue by Landyr** [EdenServer/community#2717]
### Checklist

Please help.  I am attempting complete my Limit Break on PUP and while I can  access the battlefield it is empty of enemies.  This is my first job to 70 so I cant progress on another job at this time.  

Thank you for looking into this,

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by bkesecker** [comment]
Duplicate: https://github.com/EdenServer/community/issues/2714
