### ISSUE TITLE
Mobs ignore Sneak and Invis

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2718]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Have had several monsters flat out ignore Sneak and Invisible today, also heard others who have had the same experience. The one I know that always ignores my sneak is the malboro near the spider/bird camp in Bhaflau Thickets, got aggro from that twice while running to get the Nyzul Isle staging point even with sneak and invisible up.

**Comment by mlandrum22** [comment]
Had it happen back to back times in Kuftal today with crabs. One of them aggroed through a wall, through sneak.

We also had a cactuar aggro from across the map somehow. We were at G-9 and one just showed up and started attacking. I don't think at that spot there are cactuar above or below.

**Comment by FariskaEden** [comment]
Were you guys in parties when this happened? If so did anyone in your party in the same zone have aggro / hate on something? 

One of my party members in an exp group encountered something weird in regards to sneak/invis yesterday. We were fighting goblins and players died/zoned from them. The party member using sneak/invis was not at the camp yet but one of the goblins we fought that was still alive ran through the zone to kill them, even though they did not participate in the fight and were well out of range.

**Comment by perkuprightmeow** [comment]
This was happening with Colibri yesterday (Fariska's comment), they seem to have some kind of alliance/party hate function right now?

**Comment by mlandrum22** [comment]
So the crabs/random cactuar were not the same as you were saying. They were fresh aggro.

BUT there was one instance like that. One of our party members was far away and aggroed an Air Elemental. After the Elemental killed him, it came all the way across the map to us.

**Comment by E5una** [comment]
To echo what others are saying about weird shared party/alliance hate, earlier today I hit a bug with Hpemde that I've hit several times now. If you attack them while going underwater they aggro you and become untargetable. I was in a party with someone afk across the zone. I zoned out (far from them) and the Hpemde walked across the entire zone to go kill them before deaggroing. Since these are passive monsters, I feel like this is very telling towards a change in monster behavior.

**Comment by Tjonke** [comment]
Wasn't in a PT, was solorunning around and wasn't alliance hate. But yes, colibri have some weird alliance hate now, but not same bug as this I think.

**Comment by 59blargedy** [comment]
resolved a few patches ago with fix to enmity
