### ISSUE TITLE
Fishing - Rusty Greatsword

### ISSUE THREAD

**Issue by re1master** [EdenServer/community#2721]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Fished up Rusty Greatsword in Sauromugue Champaign at 08:57:36 EST 4/20/2020. According to wiki this should not be in zone (Classic Wiki did not have item in database to check era accuracy).

Game Version: 30181205_0

Have confirmed after multiple fishing attempts that you can catch Rusty Greatsword's using Composite Rod + Meatball.

**Comment by Setz0r** [comment]
removing for upcoming patch
