### ISSUE TITLE
Gardening Seeds Drop Rates

### ISSUE THREAD

**Issue by MysticLogos** [EdenServer/community#2722]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

version 30181205_0

Grain Seeds and Vegetable Seeds are completely out of stock on the AH. I went to farm some in South Gustaberg. I have killed over 250 Walking Saplings with TH1, received 5 grain seeds (~13% drop rate), 4 vegetable seeds (~7% drop rate), 16 treant bulbs (~22% drop rate).  I used to get a bag of seeds every 4-5 kills.  Please revert TH changes.  This is ridiculous and nothing good has come of the TH changes for our server.  The changes not only affect Dynamis - they affect all of these low level drops too (hare meat is another example), which hurts the economy a lot.

**Comment by 59blargedy** [comment]
adjusted in recent patch to reflect ffxidb numbers
