### ISSUE TITLE
Bartholomew's Knife / Brigandish Blade

### ISSUE THREAD

**Issue by Killface777** [EdenServer/community#2723]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

1. Spawn BB with Curtana in north side of room.
2. Steal and then kill BB with the Buccaneer's Knife.
3. Trade Buccaneer's Knife to ??? podium in south side of room.

I have attempted to obtain the Bartholomew's Knife after 12 times of killing Brigandish Blade in sky. The ??? podium continues to state: "Nothing happens...". After speaking with some people who have obtained the knife they have traded as little as two times for multiple people.

**Comment by xizeta** [comment]
This is not a bug. It is working as intended.
