### ISSUE TITLE
NM - Shen Bugged

### ISSUE THREAD

**Issue by TheChefm** [EdenServer/community#2724]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

We popped Shen on Saturday 4/18/20 three times.
1st pop went fine.  He popped, The adds popped, we tanked him near the ???, did skillchains and nuked.  Rev mail dropped. No Problem.
2nd pop. This is where it scuffed. We did everything the same as the 1st pop, but no matter how much damage we did, Shen would regen back to 100%. We tried moving Shen up the beach, off the beach, moved his adds. The whole ally logged off, lost hate, logged back on, reclaimed at the ??. Still scuff. _We do have to admit_ that after the 1st kill, the ??? was still up, so we pop it after waiting 5min.  Wiki says that's a 15min respawn ???. Lost Pop / Pop Item
3nd pop.  We thought ok, maybe the 5min repop was too fast.  We waited 15min this time.  Same scuff Shen.  Lost pop/ Pop item. 
Posting on behalf of the LS event.

**Comment by him911** [comment]
We did shen yesterday and had the same issue, no damage was enough, he just  regen'd way too fast to 100% and became almost invincible

**Comment by Setz0r** [comment]
he's been updated to have this particular issue fixed.

**Comment by KnowOne134** [comment]
Updated today

**Comment by ReeceR09** [comment]
This issue is still not fixed. Went to shen today 5/6 BLMs, Magic bursts and skillchains. No damage was enough to pop him out of  his shell. He would get to 85%(we got to 70% using Manafont) and would stay in shell until fully regened. Could not get enough sustained damage down to kill.

**Comment by Slamm21** [comment]
http://ffxi.somepage.com/mobdb/3523
clearly here it says shen has around 20k HP and the filtrates have under 1k, on here both seem to have a ton more.
Also you should be able to pop him out of his shell with enough magic damage.

**Comment by Kusarigama-Eden** [comment]
Added video of Slammnation's Shen Fight
https://drive.google.com/file/d/1CH-funXgr98co5WSQMwEdynhF-VIDNLn/view?usp=sharing

**Comment by TheChefm** [comment]
Sooooo can we do Shen Fight yet

**Comment by ayechonk** [comment]
ditto

**Comment by PoppaPip** [comment]
Popped tonight, same issues, would dive into shell over and over and mega regen everything. Adds had loads of HP (upper tens of thousands?). Also I attempted to kite adds around island on 2nd character while killing Shen, and after a few minutes of kiting they vanished, though I'm not sure if they got stuck on something or deposed, or frankly whether or not that's supposed to happen.

**Comment by roriffxi** [comment]
We just had the same experience.  Kept going back into his shell constantly, the filtrates have insane HP and get summoned immediately after death.
