### ISSUE TITLE
Big Bomb incorrect spawn conditions 

### ISSUE THREAD

**Issue by jubs1982** [EdenServer/community#2725]
Big Bomb  seems to be set as it was in 2006, however since this is 2007 based server the update in March 2007 changed it to forced pop per item. 

Source info: http://ffxi.somepage.com/news/318

**Comment by Falaras** [comment]
That is considered an RMT change which Eden does not have.

**Comment by jubs1982** [comment]
RMT change would be making a item rare/ex.  The change made it easier to spawn and sell not harder. (Not RMT change)

**Comment by Falaras** [comment]
Generally speaking the entire March 8th 2007 update is considered the RMT change. This includes the ra/ex items, Thief Knife, the removal of Sirens Hair off NMs in SSG, force spawn Ullikumi, ect

**Comment by slassen** [comment]
Closing, this should be listed as a change on the website once it is back online.
