### ISSUE TITLE
BLU's Magic (Not Physical) Damage Grants Monsters No TP

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2726]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver: 30181208_0

I've tested with 1000 Needles and Cursed Sphere, and neither of them are granting enemies TP after use. Easily tested by Feather Tickling after a BLU magic spell. The Feather Tickle will have no effect, which happens when the monster has 0 TP.

**Comment by rude-jerk** [comment]
Resolved in November, 23 2020 patch.
