### ISSUE TITLE
Kinkobo additional effect delay is wrong when eating pamamas

### ISSUE THREAD

**Issue by Murgleis** [EdenServer/community#2727]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Kinkobo's delay does not reduce correctly when eating pamamas. +10 acc does activate too.
TP return before eating pamamas: 105 per hit
TP return after eating pamamas: 104 per hit (? should be like 85)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
