### ISSUE TITLE
A testing time

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#2728]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

30181205_0

The counter is completely broken. 
I went to Tahrongi and killed 36~40 mobs, then went back to the npc.
The npc said that I had killed 16 mobs.

I went back again to Tahrongi and killed 30~35 mobs while the mission were still active from before.

Upon my return I were told that I had killed 0 mobs.
Talking to the npc again after a short time without killing anything would change the number to 1, then eventually 2, 5 and then it told me I had overdid it.

**Comment by Balrahn** [comment]
![overdid1](https://user-images.githubusercontent.com/12987658/79892167-66ef9600-8402-11ea-99b6-a12f0bc58225.png)
![overdid2](https://user-images.githubusercontent.com/12987658/79892170-6820c300-8402-11ea-8b82-98d0698b4b74.png)
![overdid3](https://user-images.githubusercontent.com/12987658/79892171-68b95980-8402-11ea-8cd9-24938be61b52.png)

**Comment by 59blargedy** [comment]
looks like this was resolved with some code refactoring a couple years back.
