### ISSUE TITLE
Potential Fame/Gobbiebag issues?

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#273]
I've turned in 8 stacks of Boyahda Moss and my Jeuno fame is not allowing me to pick up Gobbiebag III.  That should be more than enough moss to hit max fame for Jeuno.

**Comment by gweivyth** [comment]
Just used the fame check NPC and he gives me the message that I am maxed out on fame, so this could be a potential issue with Gobbiebags themselves.  

"You have emerged as a hero to the people of Jeuno.  Just the sound of your name strikes courage into their hearts.  As a representative of its citizens, I humbly ask you to continue your efforts for the good of the Duchy."

**Comment by godmode** [comment]
I'm closing this issue. Please mention if your issue got resolved and if so what was the issue.
