### ISSUE TITLE
Opo-opo crow quest NPC bug

### ISSUE THREAD

**Issue by ziegh** [EdenServer/community#2730]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

the 7th opo-opo NPC is bugged at kahzam for the opo-opo crow quest, when you select Tatapp ( NPC's name ) he speak as Bubupp ( another NPC opo-opo ) in chat log and you can't trade the item, nothing happen so you can't finish up the quest.

**Comment by ziegh** [comment]
https://gyazo.com/ab15c7384b1a24a0db151a03ca1dd7e3

one off the screen i posted to technical support on eden discord

**Comment by rude-jerk** [comment]
Could not reproduce
