### ISSUE TITLE
BLU Actinic Burst lasts way too long

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2731]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

BLU spell Actinic Burst should be a flashga for ~15 second duration. Everything I find online says ~15 seconds, yet it lasts about 1 minute and 15 seconds on Eden. This means you can keep things permanently flashed. 

![image](https://user-images.githubusercontent.com/13668758/79918895-525bcf80-83fb-11ea-96cb-3fb4ea473d15.png)

![image](https://user-images.githubusercontent.com/13668758/79919119-bed6ce80-83fb-11ea-9c07-6c82d27ed1cd.png)

**Comment by Garphilius** [comment]
Damn....that is broken as hell...

**Comment by E5una** [comment]
Has anyone had a chance to look at this? Is the max duration just wrong? I'd love to see this fixed as newer BLUs are forming bad habits =D. This is incredibly overpowered at the moment.

**Comment by KnowOne134** [comment]
Yes, resist is giving increased time instead of reduced time

**Comment by E5una** [comment]
Hmm, there might be something wrong with that formula that does this but I think its more static than correlating with a resist. Its extremely common that I have roughly 1 minute 15 second duration flashes on lower level monsters that I don't expect resists on, and extremely rare that a higher level monster has a shorter flash. 

Using a full INT gearswap with HQ Staff (Apollo's) this was my result on a Tough that I just walked by:
![image](https://user-images.githubusercontent.com/13668758/82554201-7e21c080-9b33-11ea-97e7-83104e9c2939.png)
![image](https://user-images.githubusercontent.com/13668758/82554253-972a7180-9b33-11ea-83aa-4abb5187b241.png)

That one was 1 minute 20 seconds, which seems to be the norm.

I'm happy to look over the code on this one and help however I can, or capture data, whatever helps! Thank you again for even looking at it, its very much appreciated.
