### ISSUE TITLE
Blizzard gloves and other on use Enspell items not working

### ISSUE THREAD

**Issue by gittubb** [EdenServer/community#2732]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Enchantment based on use item Blizzard Gloves do not work, use the onuse and does not activate - I assume that the other varients of on on use Enspell gloves do not work similarily.

**Comment by ThrisStraizo** [comment]
https://ffxiclopedia.fandom.com/wiki/Blizzard_Gloves

Some important info from the page and talk:

Enchantment: "Enblizzard"
The enchantment lasts for 3 minutes.
The gloves may be removed after use without losing the enchantment effect.
Damage ranges from 1-10, dependent on enhancing magic skill.

Observations on the enchantment effect
Damage:
Base damage is 10 per hit, this can be resisted, up to 90%(1 damage).
Resist rates vary based on a character's Enhancing Magic Skill:
Jobs with Enhancing Magic Skill will get a high(~85%) rate of full 10-damage hits vs. EP-EM.
Job combinations with Enhancing Magic Skill from a SJ will get primarily 5-damage hits vs. EP-EM.
Job combinations with no Enhancing Magic Skill will get primarily 1-damage hits vs. EP-EM, however, occasional higher numbers(up to 10) will occur.
INT does not seem to be a factor in resist rates or base damage.
It does not appear to be possible to increase the damage beyond 10 with added INT or Enhancing Magic Skill.
—The preceding unsigned comment was added by Chrystopher (talk • contribs).

THF/NIN Blizzard gloves vs. EP-Tough targets. the DMG was 5-11 and almost constantly 10. vs IT Marid DMG ranged from 1 to 10 and averaged ~5.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
