### ISSUE TITLE
Alchemy Recipe Bug - Gigas Socks + Fire Crystal

### ISSUE THREAD

**Issue by Earthliving** [EdenServer/community#2733]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Alchemy recipe level 15, Fire Crystal + Gigas Socks = 2x Poison Dust.
It broke in a way that suggests the recipe is bugged in the code.
14 Synthesis attempts - 12 breaks, 5 w/ item loss at a skill level of 83.
Client ver. 30181205_0

![broke](https://user-images.githubusercontent.com/16230704/80083744-90e8ab80-851b-11ea-8c0e-d06df8ea45dd.png)

**Comment by PrettyCoolPattern** [comment]
In snyth_recipies.sql at line 982:
```INSERT INTO `synth_recipes` VALUES (866,1,0,15,0,0,0,0,0,0,0,4096,4238,497,0,0,0,0,0,0,0,943,943,943,943,2,4,6,8,'Poison Dust');```

Is set as a desynth for some reason and lvl 15, should be:

```INSERT INTO `synth_recipes` VALUES (866,0,0,14,0,0,0,0,0,0,0,4096,4238,497,0,0,0,0,0,0,0,943,943,943,943,2,4,6,8,'Poison Dust');```

**Comment by 59blargedy** [comment]
not all desynths are thunder-based, this is a fire-crystal based desynth. while the rate of break on the desynth here is kinda over the top, that's more a separate issue of desynth break rates and whether or not they need a change, so closing this report.
