### ISSUE TITLE
2nd Tonberry Tracker is not on 26 minute timer

### ISSUE THREAD

**Issue by Lordwmd** [EdenServer/community#2738]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version is 30181205_0
I stayed behind the gates for several days camping Tonberry Tracker for Thief's Kote with my brother and his wife, were killing the Tracker in the main pit every 26 minutes (Total of 11 hours over 3 days). I accidentally fell into the pit and we found a 2nd tracker which I pulled and then died so they could tractor me back up the ledge. We tried to do this 26 minutes, even an hour later and the 2nd tracker had not respawned. On the day I had left the area more than 24 hours after we killed the 2nd tracker it had not respawned. Please investigate this as all I can find indicates they should both be 26 minutes.

**Comment by falzum** [comment]
I'm in Den camping this right now and can confirm that only one tracker is respawning. Going on two hours now.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
