### ISSUE TITLE
Bloodthirster Madkix not spawning

### ISSUE THREAD

**Issue by marlinla** [EdenServer/community#2739]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Bloodthirster Madkix has a much longer spawn time then the reported 2-8 hours in his own room.

https://ffxiclopedia.fandom.com/wiki/Bloodthirster_Madkix?oldid=32155

https://www.twitch.tv/videos/600760817

version 30181205_0

**Comment by marlinla** [comment]
The goblins don't drop keys either.

**Comment by gilnear** [comment]
I've spent 2-3 hours killing everything in that room three different times and I never got it to spawn. I realize the wiki says that the window is 2-8 hours but I don't think anyone else was trying to pop it before I got there, so it shouldn't take that long.

**Comment by Kurtalicious** [comment]
Adding a discord link of players testimonies that support the original bug complaint. Please see the conversation that follows. 

https://discordapp.com/channels/482610771126386688/487088937857187852/719717808241508393

**Comment by 59blargedy** [comment]
this was resolved in a recent patch
