### ISSUE TITLE
Dia & Bio

### ISSUE THREAD

**Issue by him911** [EdenServer/community#2742]
Atm it seems like Bio can overwrite Dia but not the other way around

Was skilling up both dark and enfeebling, almost equal in skill level and enfeebling skillups stopped entirely once i cast a bio whereas if i started with dia, bio overwrites it and i see dark skillups

iirc both should overwrite one another

### Checklist

- [yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [yes] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by 59blargedy** [comment]
in terms of overwriting, bio 3 >> dia 3 >> bio 2 >> dia 2 >> bio >> dia
unless you were overwriting bio with a higher level dia, dia will never overwrite bio.

**Comment by him911** [comment]
yea i read that on wiki just wasnt sure about it. confirmed it now from other sources, its correct
