### ISSUE TITLE
Aerns in Palace and Garden Zones Not Dropping HQ Organs

### ISSUE THREAD

**Issue by Garphilius** [EdenServer/community#2744]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Before the patch that fixed Aerns in Garden and Palace not Reraising, we would farm Ix'aern Drk/Drg in Garden and Ix'aern Mnk in Palace and we would get around 5-7 HQ organs a night just by killing regular Aerns in these zones.

Once the patch for them to Reraise was launched, we have had zero HQ organ drops in all of our farming sessions. 

I really think something is wrong and this should be looked at.

Step by step

1) Zone into Garden or Palace.
2) Start killing Aerns for a couple of hours.
3) Note that no HQ organ drops.

**Comment by 59blargedy** [comment]
these only drop in the grand palace, can confirm they drop
https://ffxiclopedia.fandom.com/wiki/High-Quality_Aern_Organ
