### ISSUE TITLE
Diremite in Aqueducts - Spinning Top OP

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#2745]
![death](https://user-images.githubusercontent.com/62901732/80267363-65c2a100-866e-11ea-9259-f890548a1f9b.png)
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Was duoing Diremites with my friend in Aqueducts and was one shot with Spinning Top from a VT diremite.

**Comment by statuseffect** [comment]
Spinning Top also is ignoring DEF on Slime Pets also causing a lot of damage.

**Comment by 59blargedy** [comment]
this should have been resolved in the recent mob and mob skills update, can comment if not the case and will reopen
