### ISSUE TITLE
Kreutzet Stormwind

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#2746]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

30181205_0

Kreutzet is supposed to do 3 Stormwinds in a row with the attack growing stronger for each use. 
none of the attacks seemed to do much, also Kreutzet spammed 11 Stormwinds in a row and not 3.

**Comment by Shoruto** [comment]
Additional information on closed report #522

**Comment by 59blargedy** [comment]
resolved in July 29, 2021 update
