### ISSUE TITLE
Ul'phuabo drops both Phuabo and Xzomit organs

### ISSUE THREAD

**Issue by InoUno** [EdenServer/community#2747]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

@jmcmorris 
Just killed an Ul'phuabo after today's patch, and it seems like the drops for this mob was not set correctly during the droprate changes. Got both a phuabo and a xzomit organ from a Ul'phuabo kill:

![image](https://user-images.githubusercontent.com/774909/80286324-11312b80-872b-11ea-9215-cc2f26151cc6.png)

**Comment by E5una** [comment]
You probably have all the info you need on this one, but I just wanted to add that I kill Om'phuabo very often and it doesn't seem to be a problem with the Om, only the Ul.

![image](https://user-images.githubusercontent.com/13668758/83874059-e90df280-a702-11ea-9222-dc2065c2c6f8.png)
