### ISSUE TITLE
Silver Shark bite rate in Sauromugue Champaign

### ISSUE THREAD

**Issue by re1master** [EdenServer/community#2748]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Silver shark bite rate seems very low after 4/25/2020 update in Sauromugue Champaign (removal of Rusty Greatsword+Increase in fishing pools).

Silver sharks seem to bite 15-20% of the time since the changes were made using Halycon Rod + Meatball.

Version 30181205_0

**Comment by Setz0r** [comment]
silver shark bite rate wasn't touched.  each fish has different bite rates depending on moon phase, time of day, month of year.
