### ISSUE TITLE
Creepy Crawlies graphic error?

### ISSUE THREAD

**Issue by GotoRa** [EdenServer/community#275]
Illu Bohjaa - woods (I-6)
Traded 3 Crawler Calculus lightsday 4:00 (24%)
Got obtain 600 Gil message twice
Didn’t check Gil amount previous won’t repeat quest until resolved in fear of doing so may get all my Gil taken away potential amount to be removed 1.2k

**Comment by tectal831** [comment]
Please repeat the process and let us know the results
