### ISSUE TITLE
Magic resists are broken

### ISSUE THREAD

**Issue by him911** [EdenServer/community#2750]
Level 82 NM(Ungur) vs level 68 bard landing lullaby with ease on him. 
No Mary's horn or any notable gear pieces other than apollo's.
Seems like lullaby landing easily on everything now.

![lolmresists](https://user-images.githubusercontent.com/50463084/80288782-506f7480-874b-11ea-8913-524b7e01ad60.png)

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 update.
