### ISSUE TITLE
Northward Quest - Incorrect text flag

### ISSUE THREAD

**Issue by By-T0r** [EdenServer/community#2751]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

This issue has been posted over a year ago but is still unsolved:
https://github.com/EdenServer/community/issues/1398

![bug](https://user-images.githubusercontent.com/63556595/80291979-ba2a5700-8728-11ea-8752-2b3c47c8df2a.png)

As you can see, the NPC won't give the correct dialogue for the quest even with enough fame for it. For reference: https://classicffxi.fandom.com/wiki/Northward

I was able to trade the sword and get the map even with incorrect dialogue.

**Comment by 59blargedy** [comment]
closing as duplicate
