### ISSUE TITLE
Padded cap NPC sell price is using post 2004 RMT related adjustment

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#2752]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

http://www.ac-tool.com/forums/index.php?/topic/4279-rusty-caps-have-offically-been-nerfed/

Related to #1229 but that was closed already.
Here is a relevant quote to the proper price: 
Posted September 13, 2004
  Quote
Rusty cap still profitable, go figure ^^
 

 

LOL how do you figure, the only reason people were buying them for 1k was to synth it with a light crystal and turn it around and sell it for 2.5k.... noone will be buying rusty caps anymore

**Comment by xizeta** [comment]
https://www.ffxionline.com/forum/ffxi-game-related/crafting-synthesis/42293-rusty-caps-padded-caps

`some people wish for SE to nerf this whole idea to sell padded cap 2.7k`

http://samhart.net/node/680.html

`With like a lv 34 smither u can turn rusty caps into padded caps and sell to an NPC for 4k`

https://www.bg-wiki.com/bg/The_History_of_Final_Fantasy_XI/2004

`Rusty Caps could sell to NPCs for 2,500 gil. This rumor was spread more and more, and fish botters gathered in Rabao. `

**Comment by Mozzy4Ever** [comment]
Strong cap on both live & test is currently vendoring for 2700. Based on Zeta's findings above, Strong should be at least 3k (500 more than Padded) if not higher. Padded caps currently vendor for 2.5k
