### ISSUE TITLE
Dynamis Statues seem to have TP off the bat

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#2755]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)
ver 30181205_0
### Details

THF pulled statue (so it got 100tp) then it hit his shadows twice, never dealing damage. Then proceeded to weapon skill. This was in Sandy but I assume all zones.

**Comment by 59blargedy** [comment]
Resolved in June 7, 2021 update
