### ISSUE TITLE
RSE not being rewarded

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#2759]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Trying to obtain my last piece of RSE and the Goblin won't give me the goods.

I got my Magical Pattern but my RSE week has technically ended. According to wiki and my personal experience from retail he should still reward the equipment. even if my week is over. 

VER: 30181205_0

**Comment by greyenvy** [comment]
Doesn't sound like a bug.  The week must be active on Eden to receive the gear.  Once it rolls back around, talk to him and you'll get it.

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
