### ISSUE TITLE
Mage's Ballad out of era

### ISSUE THREAD

**Issue by scorchedxi** [EdenServer/community#2761]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

The yagudos in Giddeus shouldn't drop mage's ballad. It wasn't added as a drop until 2012 according to wikipedia and was only obtainable via a quest in San d'Oria.
Link from 2007: https://ffxiclopedia.fandom.com/wiki/Mage%27s_Ballad?oldid=988321
Link from 2009: https://ffxiclopedia.fandom.com/wiki/Mage%27s_Ballad?direction=next&oldid=988321
Link from 2012(First one that shows it dropping from mobs): https://ffxiclopedia.fandom.com/wiki/Mage%27s_Ballad?direction=next&oldid=1336579

**Comment by perkuprightmeow** [comment]
Just to add to this, the quest it is supposed to come from in era is not functional.
