### ISSUE TITLE
Alliance invite wiped existing lots

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#2763]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)
ver 30181205_0
### Details
![image](https://user-images.githubusercontent.com/5552081/80555294-c97b0000-89c7-11ea-8044-92854ac42e0a.png)
![image](https://user-images.githubusercontent.com/5552081/80555307-d0a20e00-89c7-11ea-8c18-02e889053672.png)

I had passed on Line and only Ryzechs had lotted, we added another party to Alliance and then it dropped to Line.

**Comment by Slamm21** [comment]
An update to this, I don't think this had anything to do with the alliance.
In dynamis today only Youda lotted on this, no one left or entered dynamis and no parties were changed.
![image](https://user-images.githubusercontent.com/5552081/81267103-cde58f80-903d-11ea-855d-cf09d40e5032.png)
It dropped to Ryzechs, who had never lotted. Youda did not have a full inventory.
![image](https://user-images.githubusercontent.com/5552081/81267159-e9509a80-903d-11ea-867a-edb4fc7e644b.png)

**Comment by Mozzy4Ever** [comment]
I believe this was fixed (alongwith several other dynamis bugs) on February 15th, 2021. 
![image](https://user-images.githubusercontent.com/11255886/113517483-caa49d80-9545-11eb-9782-0ea733b8d54e.png)
https://discord.com/channels/482610771126386688/670735434799644690/810894527874990081
