### ISSUE TITLE
Missing Plastron Set

### ISSUE THREAD

**Issue by MaesterEntropy** [EdenServer/community#2769]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
I went looking for the items in the link provided. I could not find if the recipe was in-game or not. Nothing been sold on AH or came up in shouts or yells when asked about this. The history of this set shows it being in the era of 2005. 
(https://ffxiclopedia.fandom.com/wiki/Plastron_Set)

Version 30181205_0

**Comment by Falaras** [comment]
Ouryu has not been released yet.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
