### ISSUE TITLE
Shikigami Weapon

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#277]
Howdy, this is less an issue but a request.

I killed Shikigami weapon for the 8th ( 6 times with TH3 ) time just now without drop. If possible I'd like to ask a Dev to check the loottable of it and see if Yingyang Robe has a reasonable droprate.

https://ffxiclopedia.fandom.com/wiki/Shikigami_Weapon

Sorry to bother, but I'm wondering if something's off or if I'm just incredibly unlucky ( wouldn't be anything new :p)

Pan

**Comment by jmcmorris** [comment]
Sorry for not responding to this request until now. I looked at the drop rate and it does look to be at an appropriate amount. Keep in mind that the FFXI wiki drop rate includes all levels of TH so the base drop rate is lower than that. With that being said, you are indeed getting unlucky. I hope you have gotten your drop by now.
