### ISSUE TITLE
[PUP] Sharpshot, Stormwaker, Soulsoother & Spiritreaver Head Max Stationary Ranges

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2770]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently the max stationary range of automatons is incorrect for sharpshot and caster heads. They are all set to 15.

Sharpshot head should have a max stationary range of 14, further than that the automaton should move into melee range of its target.
https://i.gyazo.com/12cc253bedcc1a8b4644390509f4dc5c.mp4 <shows sharpshot automaton remaining stationary 14 away from a target when deployed
https://i.gyazo.com/49a0944648845c272c1f3be255a6cc01.mp4 <shows sharpshot automaton moving in when deployed from 14.4 away from a target

Stormwaker, soulsoother and spiritreaver heads should have a max stationary range of 18, further than that the automaton should move into melee range of its target.
https://i.gyazo.com/43d6640209a0330f62085825161de6c4.mp4 <shows stormwaker automaton remaining stationary 17.3 away from a target when deployed
https://i.gyazo.com/c098d7f6a4d696a738ff362e78e63ed8.mp4 <shows soulsoother automaton remaining stationary 17.7 away from a target when deployed
https://i.gyazo.com/96fcafe9e03c25b406393c5740628701.mp4 <shows spiritreaver automaton remaining stationary 17.5 away from a target when deployed

https://i.gyazo.com/a810db7fce99b02360590424f515b1ee.png <caster automaton is 18.6 away from target
https://i.gyazo.com/f874676e91a273002ec48af636948f18.mp4 <shows caster automaton moving in when deployed from 18.6 away from a target (could not stand on top of automaton and deploy since the range of deploy is shorter than this)

version 30181205_0

**Comment by KnowOne134** [comment]
resolved in November 29, 2021 update
