### ISSUE TITLE
Mercurial Kris should be very / super rare item. 

### ISSUE THREAD

**Issue by rka666** [EdenServer/community#2773]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

**Pirate's Chart** very / super rare - discussions on FFXI AH, Wiki etc. 
**Mercurial Kris** drop rate 2.8% - Wiki.

Mercurial Kris is too common on Eden.

/ver 30181205_0

**Comment by Falaras** [comment]
It would probably help to post those discussions on FFXIAH, wiki, ect. Right now all I see is wiki has it listed as 4/145 which is a very low data set to draw conclusions from.

**Comment by Setz0r** [comment]
there's not really any good numbers for this.  i see a post on zam right now where a guy claims he got 3 in 20 runs (roughly 10% rate) but he has friends that went 1/40-50. (2-2.5% rate)

**Comment by rka666** [comment]
Few mentions of relevant items.

**Pirate's Chart** 
1/20 is the average rate on these charts - http://ffxi.somepage.com/itemdb/7618

https://ffxi.allakhazam.com/db/item.html?fitem=9730
9/132 
Got it after trading about 180 Marlins.
0/158
On my first try got the chart in 7 fish...second try 0/51 before I got a Brigand's Chart

https://www.bluegartr.com/threads/43167-Mercurial-Kris-Pirate-s-Chart-fight
1/20
I think I was around 0/50 on charts when I gave up
0/27
4/27
140 marlins for that chart

**Inside The Belly** 
Item obtained roughly 1 out of every 50 times a fish is turned in - http://ffxi.somepage.com/questdb/399

**Mercurial Kris** 
2.8% 4/145 - https://ffxiclopedia.fandom.com/wiki/Pirate%27s_Chart_Quest

1/8 https://www.bluegartr.com/threads/43167-Mercurial-Kris-Pirate-s-Chart-fight

**Comment by Slamm21** [comment]
Looking at everything here, my guess would be it was 5%
it could only be 1%, 5% or 10% based on TH data.

**Comment by Setz0r** [comment]
unfortunately, sample sizes of less than a few hundred are not very good for low % items...  wiki has no links to the testing data...web searches are fruitless.  

I believe this was rare on retail because there weren't nearly as many fishermen trying to get it every single day.   Also, the rumor surrounding it was that it was a 1/1000 chance so why bother.
