### ISSUE TITLE
Puppet Roll level needs adjusting

### ISSUE THREAD

**Issue by Far-The-Killer** [EdenServer/community#2777]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Puppet roll is currently set at lvl 52, but in era was lvl 23. Needs a dat edit as well.

**Comment by Rikoooooo** [comment]
I just noticed this too as Lv25 COR I was not able to learn Puppet Roll which in this era is supposed to be lv23. However, I WAS able to use Drachen Roll and learn it, which in this era is Lv52. Not sure why SE choose to switch these around for some reason. Anyway, I currently have a Lv52 roll on my 25 COR apparently lol.

**Comment by KnowOne134** [comment]
Closing due to issue is already open
https://github.com/EdenServer/community/issues/3559
