### ISSUE TITLE
Amigo Sabotender's ??? Needles Doesn't Do Anything

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#2778]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I pulled out a Amigo Sabotender and used ??? Needles, it used all 3 charges but Amigo didn't do anything.

**Comment by 59blargedy** [comment]
resolved with the April 5, 2021 update
