### ISSUE TITLE
BCNM40: Hostile Herbivore melee attacks do not knockback and no sheepsong

### ISSUE THREAD

**Issue by AnkleAssassinz** [EdenServer/community#2782]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
  According to ffxiclopedia Sept 28 2007, https://ffxiclopedia.fandom.com/wiki/Hostile_Herbivores?diff=353453&oldid=353393 , the melee attacks of the 3 sheep should knockback but on the 2 separate runs, it did not do so. Also not sure if we were just lucky or not but the sheeps never cast  sheepsong, aoe sleepga move.

**Comment by AnkleAssassinz** [comment]
Edit: I meant BCNM50**

**Comment by 59blargedy** [comment]
resolved in March 8, 2021 update
