### ISSUE TITLE
KS99 Horns of War Sleep/Meteor?

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2783]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205

Did KS99 today. From what I can research, Chlevnik is basically King Behemoth. If so, I imagine his resists and immunities would be the same. Currently he can be Bind/Gravitied with extreme ease without ESeal (did a total of 4 and only saw 2 gravity resists, no bind). Can also sleep him? Which I don't think should be possible (at least, not with the 0 resists we saw). 

Also, never used meteor once in any of the fights. Figured the fight would be relatively easy, but it never using meteor along with the issues above made it faceroll

**Comment by Setz0r** [comment]
did it at least do its final meteor?

**Comment by Mozzy4Ever** [comment]
That's the only one it did

**Comment by Setz0r** [comment]
he has no mp. fix will go in next update.

**Comment by Mozzy4Ever** [comment]
Should he have MP? The behemoth family isn't aspirable (https://ffxiclopedia.fandom.com/wiki/Category:Behemoths). I figured that Meteor would basically be a TP move for them.... or not cost MP. Or maybe they have MP but just aren't aspirable? Just that none of the pages for KB/Behemoth/Chlevnik mention them having MP

**Comment by Setz0r** [comment]
well, get confirmation on not aspirable and i'll figure it out, until then KB has always had MP on eden.

**Comment by Falaras** [comment]
We just had a run that had 9 drops, nothing in the Behemoth Hide/Behemoth Horn/Out of Era Healing Staff slot. I can't find any record of a KS99 dropping not 10 items online. I think the drop rates might be set wrong because of Healing Staffs removal?

**Comment by Setz0r** [comment]
the shank was removed

**Comment by Falaras** [comment]
The Shank is an 11th drop.

**Comment by Falaras** [comment]
Actually it looks like the Shank takes the place of the 3rd to last slot? The one that does Coral Fragment, Raxa, Demon Horn, ect.

**Comment by Setz0r** [comment]
![image](https://user-images.githubusercontent.com/3248222/80928129-3c89cb00-8d68-11ea-94d0-cadf145e83da.png)

doesn't add up to 100%

**Comment by Falaras** [comment]
Personally I can't find any video or picture of a KS99 not dropping 10 items in any era of the game. The wiki even says One Of instead of Zero to One Of.

**Comment by Mozzy4Ever** [comment]
> ![image](https://user-images.githubusercontent.com/3248222/80928129-3c89cb00-8d68-11ea-94d0-cadf145e83da.png)
> 
> doesn't add up to 100%

I think this is likely due to how shit wiki editors are at actually updating all of the drops in a pool, and how often drop rates are fucked with by people just trying to be dicks.

**Comment by Mozzy4Ever** [comment]
@Setz0r 

https://www.youtube.com/watch?v=Cl-jcFARvq4
@2:16

Apparently KB did have MP on retail and could be aspired.... Though that still leaves the question of could you aspir all of his MP and would he stop using meteor?

**Comment by KnowOne134** [comment]
Haha that's the same question I asked

**Comment by Mozzy4Ever** [comment]
I imagine on retail if using meteor does cost MP, they would give the mob so much MP that it couldn't all be drained by the time rage/timeout happened. Would require a lot of people to test, sadly... Like a shit ton of BLMs just spamming aspir for the entire time

**Comment by KnowOne134** [comment]
Believe its coded 1 mp for meteor if the mob pool = behemoth model

**Comment by 59blargedy** [comment]
resolved in recent patch
