### ISSUE TITLE
PM 6-4:  "One to be Feared" not rewarding 1500xp 

### ISSUE THREAD

**Issue by AnkleAssassinz** [EdenServer/community#2785]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
 According to the wikiguide, https://ffxiclopedia.fandom.com/wiki/One_to_be_Feared , folks who completed it already and helping others should get 1500xp per day(not sure if vanaday or irl).  We just helped an ls member and did not get the 1500xp reward. 
  I'm also thinking maybe the same thing is happening on the earlier 'Mother Crystal' part, https://ffxiclopedia.fandom.com/wiki/The_Mothercrystals . People who completed already should also receive  1500xp as long as at least pt member has not done yet. 

Thanks

**Comment by bkesecker** [comment]
Evidence in ToAU era links:
https://ffxiclopedia.fandom.com/wiki/One_to_be_Feared?oldid=369117
https://ffxiclopedia.fandom.com/wiki/The_Mothercrystals?oldid=359825

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
