### ISSUE TITLE
Royal Jelly - Queen Jelly Regain

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2786]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205

From what I can tell, the Queen Jelly is supposed to have some pretty high regain. Looking at https://youtu.be/V2dkkutDxZI?t=321 from retail, it would spam TP moves constantly. @6:00 it did a fluid spread, got hit by a player once, 3 times by a TigerFamiliar, and hit a player once, and did another TP move (Digest). It then got hit 3x by players, 5x by familiars, hit a player once, and TP'd again. Compared to https://www.twitch.tv/videos/568546255?t=0h9m14s you can see on Eden that it doesn't TP nearly as much, nor spam -aga like it did on retail. 

It seems like on retail, Queen Jelly had some pretty strong regain

**Comment by 59blargedy** [comment]
resolved in recent patch
