### ISSUE TITLE
Leave incorrectly shares cooldown with Heel/Stay

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#279]
Heel and Stay should share a cooldown.
Leave should be mutually exclusive.

https://ffxiclopedia.fandom.com/wiki/Heel
https://ffxiclopedia.fandom.com/wiki/Leave

Additionally, there should be some grace period (5-10 seconds or so) after using Leave before a monster will become aggressive. Currently, enemies will immediately agro after Leave.

**Comment by godmode** [comment]
Unfortunately, this is a client-side issue. I am unsure if it is a dat mod or something in the packets. We can change it on the server so you could manually type "/ja leave" by changing its recast ID but that won't help the majority of use cases. I am going to label it as `needs-dat-mod` and once we start switching more things over we can determine if its a dat or an client issue

**Comment by KnowOne134** [comment]
this is in era now to the 11/19/2007 update
