### ISSUE TITLE
Easy Prey charmed pets not lasting long enough

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#2790]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I charmed a Warden Beetle in Garlaige, it's level 56 (Easy Prey) and he only lasted 13 minutes. I had +6 charm on, so it looks like Easy Prey is set for 10 minutes, where it should be 20. (Decent Challenge should be 10 minutes.)

https://ffxiclopedia.fandom.com/wiki/Charm?oldid=366124

**Comment by Spider-Dan** [comment]
I can also verify this bug.  As a LV75 BST, I charmed an Easy Prey Temple Bee in Temple of Uggalepih while wearing Charm+20 (BST AF), which should double the duration.  Exactly 20 minutes later, the bee uncharmed, when it should have been 40 minutes (20 minutes for EP, +100% with Charm+20).

My client version is:
30181205_0

**Comment by KnowOne134** [comment]
Fixed last update
