### ISSUE TITLE
Odqan not functioning properly

### ISSUE THREAD

**Issue by bungdup** [EdenServer/community#2793]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Odqan spawns in one static spot @ I-7, doesn't have a claim shield, and doesn't de-spawn, i saw odqan just up at night in lightning weather, saw again spawn past 11 in fog, he's supposed to spawn at either of the 3 spawn areas during fog between 2 and 7, and de-spawns at 9 or when fog ends when the other atomic clusters de-spawn. Also he might have multiple spawns, stock dsp has 2 odqan spawns at once.

Have spawn in a random one of the three locations with a wider spawn radius, have spawn between 2 and 7 in fog weather only , have a claim shield and have odqan de-pop when fog weather disappears.

**Comment by rude-jerk** [comment]
Resolved in patch on February 1, 2021.
