### ISSUE TITLE
Elshimo Marble Drop Rate

### ISSUE THREAD

**Issue by DeliriumOnEden** [EdenServer/community#2795]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I've farmed Ivory Lizards in Yuhtunga Jungle for 108 kills today and approximately 150 kills last week and have not seen the Elshimo Marble drop for the Teleport-Yhoat quest. I'm pretty certain the drop rate for this item is incorrect. Verified I do not have one in my Mog Safe, Mog Safe 2, Mog Locker, or Storage.

version 30181205_0

**Comment by 59blargedy** [comment]
validated, it's just a crap drop rate at ~1.7% with th0
