### ISSUE TITLE
Player=Chong should be Rank3 , but is Rank 2

### ISSUE THREAD

**Issue by StopClick** [EdenServer/community#2797]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

**Comment by InoUno** [comment]
Resolved in December 1st 2020 patch.
