### ISSUE TITLE
Golden-Tongued Culberry not functioning properly

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#2798]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

Resists Stun and most other debuffs according to the wikia and past experience.

It can currently be slept, it was able to be slept repeatedly in every instance I’ve seen. There were very few resisted casts.

The most important issue, which was reported over a year ago, is still not fixed. The NM is currently stationary in one location where the ??? trigger is.

This is an observation from watching another group stream their fights. There are likely other functions that deserve an audit.

Spell list, casting time, and MP cost. It’s supposed to do nothing when it runs out of MP. (Typically after many hours on retail)
Casting mechanics when enmity shifts AND when a pet takes hate.

Thank you

**Comment by perkuprightmeow** [comment]
Yeah we just did it (and probably the group he's talking about). On Eden the only two real viable options to kill him are some form of sleep nuking/tp burning or send summoners at it since it doesn't move at all.

**Comment by 59blargedy** [comment]
resolved in June 28th, 2021 update, though feel free to comment with any lingering issues
