### ISSUE TITLE
Senjuinrikio in Operation Desert Swarm droprate

### ISSUE THREAD

**Issue by lindz** [EdenServer/community#2799]
- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Senjuinrikio droprate in KSNM30 Operation Desert Swarm seems significantly lower than documented. https://ffxiclopedia.fandom.com/wiki/Operation_Desert_Swarm list it as a 23% drop rate from a loot pool with 3 other rare/ex weapons. In 16 runs, I have seen a roughly even distribution of the other 3 rare/ex weapons, but no Senj. 0/16 is statistically improbable with the 23% droprate which leads me to believe the droprate is lower than reported. The droprate may need to be reexamined, though it's fair that data besides ffxiclopedia has been difficult to find.

**Comment by Kurtalicious** [comment]
I am currently 0/13 on this BCNM.  If Senj is a ~25% drop rate the probability of going 0/13 is 2.3%.  I think something is wrong.

**Comment by Kurtalicious** [comment]
1.7% chance of going 0/14.

**Comment by Kurtalicious** [comment]
Below are other testimonies of players talking about their drops rates in Eden discord.

https://discordapp.com/channels/482610771126386688/670753813442986027/708049299161874493

https://discordapp.com/channels/482610771126386688/670753813442986027/708039610865025085

https://discordapp.com/channels/482610771126386688/670753813442986027/708051952348692652

**Comment by 59blargedy** [comment]
is set to equal rate as other weapon drops in the bcnm
