### ISSUE TITLE
[PopNM] Kurrea not implemented, plus other issues

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#2800]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

As title states, Kurrea is not implemented.  According to the [Eden wiki](https://classicffxi.fandom.com/wiki/Kurrea) it should exist on this server since there is a page for it!

Past that, the item Adamantoise Soup which is used to spawn Kurrea is implemented.  You can farm up all the materials and have it crafted without issue.  However, the drop rate for Tavnazian Ram Meat is abysmally low.  Members were reporting it's drop rate to be less than 5%.  

According to [this post](https://ffxi.allakhazam.com/db/item.html?fitem=9362#m1124873489615280 the drop rate shoud be Rarity 3.  
According to [The main wiki](https://ffxiclopedia.fandom.com/wiki/Tavnazian_Ram) the drop rate is closer to 30.4% (7/23, not many trials, I know). That would put it between Rarity 4 and 5, depending on whether TH1 or TH4 is used.

Please take a look at that one.  Thanks!

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
