### ISSUE TITLE
Frightful Roar should not be learnable in Phomiuna Aqueducts

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2801]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Frightful Roar requires level 41 to learn it, and Phomiuna Aqueducts has a level 40 cap. In 2010 they removed the level restriction of the zone and then you were able to learn it there, but that is not the case on Eden. I personally have learned the spell from the Aqueducts and have helped another BLU learn it there as well.

Current Wiki:
https://ffxiclopedia.fandom.com/wiki/Frightful_Roar

2007 Wiki:
https://ffxiclopedia.fandom.com/wiki/Frightful_Roar?oldid=349113

version 30181205_0

**Comment by FariskaEden** [comment]
Only way I can think of where you should be able to learn this in Phomuina Aqueducts at 40 is if you were already a 75 BLU and had blue magic merited. It'd give you the skill needed to learn the spell then. I'm guessing your scenario was without merits so maybe the skill requirement needs a bump up then.

**Comment by Dribblet** [comment]
It should be possible to learn Frightful Roar in Phomiuna Aqueducts via Blue Magic merits, as you only need to be within 29 Blue Magic skill to learn a spell, and 40->50 is a 30 skill difference, however you should not be able to learn the skill while unmerited as lvl40 cap does not give enough skill to reach the minimum to learn Frightful Roar.

Tested on Test Server, 123 Blue Magic skill (Capped @ 40 with no merits), was able to learn Frightful Roar (153 skill cap @ it's level of 50) which is a 30 skill difference and shouldn't be learnable.

**Comment by E5una** [comment]
My guess would be that the code is pulling your uncapped skill into the equation, but I don't want to speculate too much, I'll just let the devs take a look.

**Comment by E5una** [comment]
I believe this line needs the integer to be changed to 29 in topaz's blueutils.cpp:

if (playerSkillLvl >= skillLvlForSpell - 31)

I went on the test server and also printed out the values for playerSkillLevel and skillLvlForSpell and found they are 123 and 153 respectively. Everything is working as expected on the test server, but I believe that 31 skill cap is the issue per the wiki:

https://ffxiclopedia.fandom.com/wiki/Category:Blue_Magic#:~:text=Blue%20Mage%20must%20be%20set,used%20a%20blue%20magic%20spell.&text=After%20level%2050%2C%20when%20the,decreases%20from%209%20to%205.

"The maximum skill difference to be able to learn a spell is 29 points below the skill level of the spell. Below level 50, one can learn skills as early as 9 levels prior. After level 50, when the increase in Blue Magic Skill from level to level rises from +3 to +5, the level range at which one can learn spells decreases from 9 to 5."

For what its worth, the era version of that page lists 27 points, but says it is unconfirmed, although it does explicitly say Frightful Roar is not learnable in the Aqueducts due to the skill gap.

https://ffxiclopedia.fandom.com/wiki/Category:Blue_Magic?oldid=377120

**Comment by E5una** [comment]
Blah, but the BG-wiki says 31.... not sure how to reconcile these.

https://www.bg-wiki.com/bg/Category:Blue_Magic#Learning_Blue_Magic

**Comment by KnowOne134** [comment]
i believe you could get this spell at 40 but it was just so rare.
an old place i use to use back in the day also shows that all 50 leveled spells can be learned at 40 here https://zentoo.net/ffxi/blu/BLUMain.html

so the question really is and we may never know is did the skill check ever change from the -31, such as -29 pre level 40. but i believe with capped blue skill at 40 can learn these level 50 spells now then there is no issue.

will leave this open for a bit to see if any discussion comes of it before deciding to close.
