### ISSUE TITLE
Tame not working after failed charm

### ISSUE THREAD

**Issue by Satirof** [EdenServer/community#2803]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version = 30181205_0

Attempting to use Tame after Charm (when charm resists) appears to have a 100% fail on Eden. This should not be the case, as in retail during era this was Tame's main purpose.
In retail if you to charm a monster, you could use tame, which had a decent success rate to passify the monster and cause it to turn back yellow and return to idle, either despawning and walking back to its normal area.

However after leveling BST solo, I have had 0% success for it to work in this case. 

Steps:
1: Fail to charm a charmable monster (e.g. crab)
2: Use tame on said monster
3: Tame fails 100% of time.
4: Run around to try not to die...

How it should work:
1: Fail to charm a charmable monster (e.g. crab)
2: se tame on said monster
3: Tame succeeeds (success rate based on BSTs INT vs monsters INT, and equipment like AF helm and bison/khimeira legs)
4: /happy

Images of the current failed messages.
![Higana_2020 04 29_121744](https://user-images.githubusercontent.com/38270613/81375865-5c8d0600-913d-11ea-80c3-86f8e0b807b0.png)
![Higana_2020 04 30_163545](https://user-images.githubusercontent.com/38270613/81375875-631b7d80-913d-11ea-8501-32c5120c7bf9.png)

I believe the 'No effect' message should be when trying to use tame on an untamable monster (like beastmen, or a NM), and the 'miss' message should be for if you do actually fail to tame on a charmable monster.

Wiki entries:
August 2007:
https://ffxiclopedia.fandom.com/wiki/Tame?oldid=314875

Current: (because it has some more information as tame, like BST, was not hugely popular in era
https://ffxiclopedia.fandom.com/wiki/Tame

**Comment by statuseffect** [comment]
Was testing this as well. It works on passive mobs to help the next charm but when you fail a charm is "RARELY" lands. I have maybe landed it once or twice. 

Also charm is missing text on a successful/failed charm. 
The <t> is now under <me>' s control.
Fails to charm the <t>.

I also feel that charm rate needs to be looked at as the number of failed charms seems to be very high with apollo's and near perfect charm gear.

**Comment by slassen** [comment]
While this would work in one situation, I think it's more likely that enmity is cleared when it becomes tamed rather than just on the BST. This could be easily verified by two people with a retail account. Have one get hate on a mob, and then a BST tame and release it.

**Comment by mlandrum22** [comment]
https://www.ffxiah.com/forum/topic/4121/tame-success-rate/#161254

This matches my memory of Tame where the success rate was very high. At least vs similarly leveled mobs and ones you haven't attacked it.

https://www.ffxionline.com/forum/ffxi-game-related/race-job-type-q-a/beastmaster/62030-how-exactly-does-tame-work?p=938769#post938769

You can get xp off of a Tamed mob that didn't fully regenerate, apparently. Taming a mob you hit lowers chance of Tame.

My guess is it's either a strict calculation on HP% or it's some sort of enmity calculation.

**Comment by KnowOne134** [comment]
resolved in October 4, 2021 update
