### ISSUE TITLE
Soulflayer Immortal Shield is functioning improperly

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2804]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The Soulflayer Immortal Shield move is functioning improperly. It seems to be functioning like a magic shield effect, making BLU unable to land debuffs and stuns. According to the wiki it is essentially supposed to be a stoneskin for magic damage only.

https://ffxiclopedia.fandom.com/wiki/Immortal_Shield

The current state of the ability makes it very hard for BLU to solo learn Mind Blast (but not impossible)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in July 29, 2021 update
