### ISSUE TITLE
[NM] Ga'Bhu Unvanquished Issues

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#2806]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

NM Ga'Bhu Unvanquished in Beadeaux is implemented incorrectly.  According to the [wiki entry for this mob](https://ffxiclopedia.fandom.com/wiki/Ga%27Bhu_Unvanquished) if should be a lottery spawn from the three Emerald Quadav that spawn around (J-5) and (J-6).  At present it only has one placeholder because that is [how it was implemented in DSP](https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Beadeaux/IDs.lua).

Furthermore this NM only has a single spawn point.  It should be able to spawn in place of any of the three placeholders it was killed from or anywhere within the map coordinates of those placeholders.  

To reproduce, simply kill the only PH over and over and it will always spawn off that one only right on the little brown bridge near it which sticks out over the edge of the raised area.  It will never spawn off any other Emerald Quadav in that area.

Supposed rarity of the items it drops:
Dual Rapier: 6
Valkyrie's Mask: 3

Respawn window should be set to 60 minutes.

/ver 30181205_0

**Comment by 59blargedy** [comment]
resolved in February 22, 2021 update.
