### ISSUE TITLE
Aern's do not restore MP upon reraise

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#2808]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

Really only an issue with Ix'Drk since he can reraise so many times. A blm group fighting this mob will eventually aspir all it's MP. However, each time an Aern reraises, it should restore it's MP to full:

https://ffxiclopedia.fandom.com/wiki/Category:Aern

"Aerns will Reraise to full HP and MP a few seconds after they are defeated - and some, like the Dark Knight Ix'aern, may Reraise multiple times before being defeated for good."

**Comment by greyenvy** [comment]
It should also be noted that Aerns presently retain their TP after pseudo-death and into reraise.  I am pretty sure TP should be clear during the RR function.  I don't have retail account to check however, just from memory.

**Comment by setsuk0** [comment]
We are currently fighting Ix'drk and after multiple reraises, it is now no longer restoring MP after reraising. Aspirs from all blms are getting 0 mp after every reraise.
