### ISSUE TITLE
Behemoth not dropping Behemoth Hide

### ISSUE THREAD

**Issue by ElectroNicMan83** [EdenServer/community#2809]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- x[ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

We had TH4 and Behemot dropped 0 hide. First hide should be 100%, with a chance at second.

**Comment by perkuprightmeow** [comment]
This is still happening. (😢)

**Comment by VirtuosusFFXI** [comment]
![nodorp](https://user-images.githubusercontent.com/49970272/94667095-5827dc00-02dc-11eb-899f-a6526e8b1ce6.png)

**Comment by VirtuosusFFXI** [comment]
![nodorp](https://user-images.githubusercontent.com/49970272/94667319-ae951a80-02dc-11eb-9a28-843ebbc362fe.png)
