### ISSUE TITLE
IX'aern Dark Knight Sleep Bolt

### ISSUE THREAD

**Issue by ElectroNicMan83** [EdenServer/community#2810]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
I was able to process Sleep with Sleep bolt on IX'DRK .

**Comment by icariumkupo** [comment]
Can be slept with black mage too no problem. Not sure this is a bug though? No mention of this enemy being resistant to sleep on the wiki.
