### ISSUE TITLE
0 Loot Table for Screamer mobs in Jugner, And Walking Trees don't drop Oak logs anymore

### ISSUE THREAD

**Issue by TherosRed** [EdenServer/community#2811]
### Checklist

- [1] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [1] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [1] I have provided my client version in the details. (type /ver into your game window)

### Details
**Client Version:  30181205_0
**Have TH4

Walking Trees in Jugner Forest no longer drop Oak logs.   (Killed for 15 hours repeatedly over 3 days)
AND
Screamer birds drop absolutely nothing. Also failed stealing several times, which is uncommon.
20 consecutive kills

I have spent many entire days killing Walking trees before there were changes made to treasure hunter.  Although rare, when I spent an entire day there, I would leave with several.  I think I have killed them or 3 full days since the treasure hunter changes,, with 0 drops.

**Comment by 59blargedy** [comment]
screamer drop pool corrected. oak log drop rate is appropriate to multiple sources so is unchanged.
