### ISSUE TITLE
Bune spawning outside 21-24 hour window and has low accuracy.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#2812]
### Checklist

- [ /] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ /] I have provided my client version in the details. (type /ver into your game window)

### Details
Bune spawned 6 minutes after his 21-24 hour window closed. Died at 9:27 AM EST yesterday, then popped at 9:33 AM EST today. 
Also his accuracy seems pretty low. He misses my Thief an incredibly large amount wearing no evasion gear, actually have negative evasion on my gear. He's missing me like a dozen times in a row sometimes. Even his TP moves rarely land. He's supposed to be a lot harder but he's kind of a joke. Fang rush should take all your shadows and pretty much 1 shot you if you don't have shadows up and all hits land. But it's super negligible. In 2007 era mambo tanking with a NIN or THF was a good idea because his accuracy was very high as detailed here. https://ffxiclopedia.fandom.com/wiki/Bune?oldid=209731

Version 30181205_0

**Comment by slassen** [comment]
In the code it's scheduled to respawn between 75600 and 86400 seconds which is 21-24 hours. There could be an unknown variable/edge case that caused it to pop 6 minutes later--either server side or user error but that much is unknown. I did however increase accuracy.
