### ISSUE TITLE
"Leujaom Cleansing" Assault is nonoperational.

### ISSUE THREAD

**Issue by Qair** [EdenServer/community#2814]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

"Leujaom Cleansing" Assault is nonoperational. Trying to enter the instance results in the error message "You cannot enter at this time. Please wait a while before trying again."

**Comment by KnowOne134** [comment]
has been fixed
