### ISSUE TITLE
Seagull grounded does not initiate

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#2815]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Similar to #2814 , you cannot begin this assault mission.  You get an error message trying to.

**Comment by KnowOne134** [comment]
has been fixed
