### ISSUE TITLE
Excavation Duty and Golden Salvage don't let you teleport via Runic Portal

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#2816]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Characters which already have the Halvung and Ilrusi Atoll staging points are told they haven't activated them when attempting to teleport using assault tags.  EVen when they do have these staging points active.

**Comment by KnowOne134** [comment]
fixed this morning, patch incoming
