### ISSUE TITLE
Temporary maps for assault zones are not placed in player inventory.

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#2817]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently when you are in an Assault you are not given the map for the zone. When you open the map inside of assault it shows no map. 

https://www.bg-wiki.com/bg/Category:Magical_Maps

**Comment by falzum** [comment]
Happened to us in Leujaoam Sanctum.

**Comment by KnowOne134** [comment]
ah something i never thought of, i play with all maps on test servers
