### ISSUE TITLE
Unable to do assault or cancel orders

### ISSUE THREAD

**Issue by aspiraga** [EdenServer/community#2819]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Attempted to do Excavation Duty with a group and did not get pulled into the Assault zone with the rest of the party, apparently due to clicking on the Runic Seal while another member had already initiated the mission. I am now unable to do the Assault or cancel the order with Rytaal, who says nothing when clicked. I have also been unable to use the Runic Portal since first accepting this Assault Order, but that seems to be a known issue already.

Character: Requeus
Version: 30181205_0

**Comment by InoUno** [comment]
Same thing just happened to us. We all initiated the mission at the same time, but only one got pulled in while the rest got stuck outside and couldn't move.
Crashing the client made us able to move again on the outside, but we can't enter the mission now, and just get "Nothing happens.." even though we still have the assault armband.

**Comment by KnowOne134** [comment]
Only 1 person gets armband. AMD that 1 person starts the mission

**Comment by InoUno** [comment]
Aha, makes sense now reading the wiki.
Is the way to get unstuck with the rest now to make separate parties for each armband?

**Comment by KnowOne134** [comment]
Party 3 to 6 players. 1 person gets armbandand Intiates the gate. The rest wait and will be entered auto

**Comment by KnowOne134** [comment]
No align. Just 1 party

**Comment by InoUno** [comment]
Yep, got that, will do that for future entries :)

But we now have 3 characters now with both assault orders and armband (those who were left out of the initial assault entry), and they can't enter the assault nor cancel the orders at Rytaal. So they aren't able to do anything right now it seems?

**Comment by InoUno** [comment]
The Runic Seal just says "Nothing happens.." when trying to enter for those three characters.

**Comment by KnowOne134** [comment]
Gonna assume you got a new I'd tag before canceling mission. 
Check key items for tags. Orders and mission active in log

**Comment by hyakuzaku** [comment]
My group had the exact same issue, tried with 6 and only 3 could go in. Stuck as a black screen and disconnected to fix it. Now after the hot fix I can warp to the Halvung staging point, but unable to get an armband, enter, or cancel orders at Rytaal (he gives no dialog at all). This means I obviously cannot leave the staging point or use the runic portal normally.

My current mission is President Salaheem, and I have Lebros Assault orders in my key items

**Comment by InoUno** [comment]
Rytaal gives no dialogue at all, so can't get a new ID tag or cancel mission.

Currently have Lebros Assault orders and Assault armband as key items. No ID tag key item.

**Comment by perkuprightmeow** [comment]
As a temp fix if you haven’t already please file a GM ticket under help desk > help desk & leave your character online if possible.

**Comment by InoUno** [comment]
@perkuprightmeow Filed a ticket and left my char online for most of 24h, but seems like it hasn't been answered yet, as I still can't enter assaults or cancel orders.

Any chance for a fix soon? Would really like to be able to do my assaults for this week :)

**Comment by perkuprightmeow** [comment]
@InoUno What's your in game name?

**Comment by InoUno** [comment]
@perkuprightmeow The three characters that got stuck from our run were: Inodos, Wakka, and Random

**Comment by KnowOne134** [comment]
Patch coming soon to clear up stuck chars and fix code from not happening

**Comment by KnowOne134** [comment]
has been fixed
