### ISSUE TITLE
Dynamis NIN Mob 2hr

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#282]
NIN 2hr is supposed to scale down with remaining HP%.  For example, if a NIN mob 2HRs at 1% it would deal little damage and a 25% 2HR would do significantly more.  Currently, a NIN 2HRing even at low HP does significant damage.

There also used to be an HP threshold that needs to be passed prior to a NIN attempting to 2hr.  Offhand I can't remember if it was 25% or 50%.

**Comment by gweivyth** [comment]
They could do it at 50%.  It wouldn't kill them obviously.

**Comment by Oyaziiiiiii** [comment]
Just for an idea of how emo these mijin gakures are, the lowest I saw today on my galka was 562, the highest 1106.
