### ISSUE TITLE
Killed all rocks in Excavation Duty, but the Rune of Release didn't spawn

### ISSUE THREAD

**Issue by zuultek** [EdenServer/community#2820]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
Client version 30181205_0

Killed all rocks in Excavation Duty, mostly with dots and spells. When the last one died, there was no completion message and the Rune of Release did not spawn, ending up in eventual timeout. Completely sure we did not miss any.

**Comment by KnowOne134** [comment]
found a issue where you need to have mob claimed on death to count for credit, can attack while doting or just make sure the mob is red on death until fixed

**Comment by Qair** [comment]
Can confirm, still broken. I noticed like you said that the walls kept going unclaimed, not much we can do about it as melee.

**Comment by Mikokiko** [comment]
We have that bug that just happened, wall went white as it  died, got no credit.

**Comment by KnowOne134** [comment]
Stay engaged to it for now until the bug is worked out and I can close issue

**Comment by Mikokiko** [comment]
We had it go white even when engaged and no other wall up.

**Comment by KnowOne134** [comment]
has been fixed

**Comment by Mozzy4Ever** [comment]
Is un-fixed again. Having the wall unclaimed when it dies bugs it again.

**Comment by falzum** [comment]
Had this happen to me last week as well but forgot about it. Bio'd the wall and walked away and it died unclaimed and bugged out
