### ISSUE TITLE
Imperial I.D tag timer

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#2821]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Imperial I.D tag timer seems to work incorrectly.
I got my first tag yesterday around 5pm local time, and by my understanding it should be refreshed today at 5pm local time (24hr cooldown).

But the NPC says the next tag will be issued at 2pm tomorrow, thats exactly 24hrs after I got my 3rd tag from the NPC. 

Mabye the timer resets whenever you get a tag from NPC?

**Comment by Relic3** [comment]
Just went to check the exact timing after it wouldn't supply me with my Tag after getting my first tag yesterday after maintenance. Did my last assault last night just after midnight, and it won't let me get my next tag until 24hrs after my last assault. We should be getting an assault tag every 24hrs after the first tag taken. Not 24hrs after the last tag taken.

![Assault Timer](https://user-images.githubusercontent.com/56906818/81512505-f647e500-92ee-11ea-9128-ba0f5612c1d3.JPG)

**Comment by falzum** [comment]
Picked up my tags asap after servers stabilized on saturday and my tags are still at 0.

**Comment by Relic3** [comment]
Yea, it seems like we are all having the same issue on this.

**Comment by KnowOne134** [comment]
this issue is low on my radar atm, working on the issues of not working at all and people getting stuck. It is on my radar though, next is getting golden salvage functional. until clear advice is run all tags and wait 3 days but they do reset time every 24 hours

**Comment by Lixion** [comment]
Low possibly but really shit. My last tag out of 3 was pulled 10:50pm MST on 05/09. I was unable to pull the tag at the same time 05/10, got one. I then pulled a tag on 5/11 at 10:30pm MST. I am now a tag behind because my timer thinks I have to wait till 05/12 to get tag 2, which is not the case as I should be on tag 3. So either pull them all at once or get boned

**Comment by KnowOne134** [comment]
ok im stumped and my math skills are weak so im giving out the info i have a hand and seeking help from anyone that can shed some light.
what you will need to know there are varaibles attached to chars and that time is measured in epoc time stamps from https://www.epochconverter.com/

in the rewrite im looking at when you 1st talk to the npc for assault you get a varriable set of allTagsTime to current time or os.time(), and wont be over ridden until you take a tag when you have 3 tags after you finish the taking a tag CS with:
        if tagCount >= 3 then
            player:setVar("allTagsTime", os.time())
        end

to get the time working right when you have 0 tags left i have this code which is the local set allTagsTimeCS that feeds into a param into the CS:

    local allTagsTime = player:getVar("allTagsTime")
    local diffday =  math.floor((os.time() - allTagsTime)/86400)
    local allTagsTimeCS = (allTagsTime - 1009897200) + (diffday * 86400)
    
no clue why the 1009897200 but it was what to be found out to get the proper time to display SE does these things alot lol.

so what i need now is a equation that will set a varriable to the char when you take a tag and then also count up and down how many tags you should have maybe my just time stamps or also by day stamps using
player:setVar("lastTagTime", os.time())
player:setVar("id_tags", tagCount - 1)

**Comment by Lixion** [comment]
I think the time epoch thing is correct.That isn't the problem, calculating the day. The problem here is allTagsTime gets overwritten when you hit 0, if I'm reading this correctly. You want to start the timer and keep that timer until the player hits 3 tags. So since my comment was removed let me restate it 

- I had 3 tags and ran my first at 8pm. My "tagRefreshTime" should be locked in here.
- When I pull my 3rd tag I allTagTime went to 10:50pm. (This would be ok if we got all tags back after 3 days instead on 1/day)
- On day 2, I couldn't pull I tag so I'm back to 1. My allTagTime should still be 10:50pm
- On day 3, I pulled my refreshed tag at 10:30pm, this triggers my new time to be 10:30pm as I hit 0, but then I missed a tag by 20mins and am now 1 day behind.

If my refresh time was set to 8pm I would have attained all 3 tags waiting 24hrs for each after my first, and only when I go from 3 to 2 tags should my refresh time be reset, unless, we keep a refresh time and rolling index for all tags but that triples the data/player.

**Comment by KnowOne134** [comment]
I'm making a all new system to replace current amd need help. Disrguard how
it works now.

**Comment by Lixion** [comment]
With the scope I have this is what I would do:

On check:
local allTagsTime = player:getVar("allTagsTime")
local tagCount = player:getVar("id_tags")
local howManyDays =  math.floor((os.time() - allTagsTime)/86400)
local allTagsTimeCS = 0

tagCount = howManyDays + tagCount
if(tagCount > 3) {
    tagCount = 3
}
else {
   --Get time taken in in game days, always add 24hrs, then add how many days have passed
   allTagsTimeCS = (allTagsTime - 1009897200) + 86400 + (howManyDays * 86400)
}
player:setVar("id_tags", tagCount)
 ...Talk to NPC...

On take:
local tagCount = player:getVar("id_tags")
if( tagCount >= 3) {
    player:setVar("lastTagTime", os.time())
}
player:setVar("id_tags", tagCount - 1)

**Comment by InoUno** [comment]
Made a little simulation of how I think it should work: https://jsfiddle.net/v1b4cpfe/1/
The logic for it is in these two functions:

```javascript
  talkToNpc = () => {
  	let { currentTime, refreshAt, tagStock } = this.state
    
  	while (currentTime >= refreshAt && tagStock < 3) {
    	refreshAt += 24
      tagStock += 1
    }
    
    if (tagStock === 3) {
    	refreshAt = undefined
    }
    
    this.setState({
    	currentTime, refreshAt, tagStock, isTalkingToNpc: true
    })
  }
  
  takeTag = () => {
  	let { tagStock, refreshAt, currentTime } = this.state
  	if (tagStock === 0) {
    	return;
    }
    
    if (tagStock === 3) {
    	refreshAt = currentTime + 24
    }
  	tagStock = tagStock - 1;
    
  	this.setState({
    	tagStock, refreshAt, isTalkingToNpc: false
    })
  }
```

**Comment by KnowOne134** [comment]
sorry this is in lua construct

**Comment by InoUno** [comment]
In lua it would be something like this::

```lua
-- Talk to NPC
function talkToNpc(player)
    local tagStock = player:getVar("id_tags")
    local refreshTime = player:getVar("refresh_tag")
    local currentTime = os.time()

    while currentTime >= refreshTime and tagStock < 3 do
        refreshTime = refreshTime + 24 * 60 * 60
        tagStock = tagStock + 1
    end

    player:setVar("id_tags", tagStock)
    player:setVar("refresh_tag", refreshTime)
end


-- Take tag
function takeTag(player)
    local tagStock = player:getVar("id_tags")
    if tagStock == 0 then
        return -- or show however much time is left until "refresh_tag" variable
    end

    if tagStock == 3 then
        player:setVar("refresh_tag", os.time() + 24 * 60 * 60)
    end
    player:setVar("id_tags", tagStock - 1)
end
```

Note that I haven't tested this, but logic should be the same as the javascript above.

**Comment by KnowOne134** [comment]
@InoUno  your are my savior here, ive done my write up and some testing, will push to our test server for in game testing. :bow:
