### ISSUE TITLE
Pets AoE hit claimed mobs

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#2823]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Both Bubble Shower from CC (Ready AoE) and 1000 Needles charmed Sabotender (Sic AoE) hit mobs claimed by someone else and put both the pet and me on the other mob's hate table.

**Comment by InoUno** [comment]
Resolved in December 28, 2020 patch.
