### ISSUE TITLE
Unable to progress in ToAU 4 Knight of Gold while Rat Race is active

### ISSUE THREAD

**Issue by tigo9** [EdenServer/community#2825]
### Checklist
- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

Client Version 30181205_0

**Steps to Reproduce**
- Be on the Rat Race quest (I was at the point where you need to collect fish to make Nashmau Stew)
- Try to get the cutscene from Cacaroon for ToAU 4 - Knight of Gold

**Expected result**
Cutscene triggers

**Actual result**
No cutscene is given - Cacaroon gives the dialogue associated with Rat Race

**Comment by 59blargedy** [comment]
yeah looks like that was retail behavior too, unfortunately. https://ffxiclopedia.fandom.com/wiki/Aht_Urhgan_Mission_4:_Knight_of_Gold
https://ffxiclopedia.fandom.com/wiki/Talk:Rat_Race

**Comment by KnowOne134** [comment]
retail behavior
