### ISSUE TITLE
Unable to interact with cursed chests in Golden Salvage assault

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#2827]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Currently the chests in the Golden Salvage Ilrusi Atoll assault cannot be interacted with. Clicking on them does nothing, shorthand does not work and using AoE abilities near them also doesn't aggro them. The group I was in went through and clicked every chest to make sure it wasn't just an issue with the mimics.

**Comment by Balrahn** [comment]
Can confirm this. Same issue with my group.

**Comment by KnowOne134** [comment]
Golden salvage is gonna be closed until further notice
