### ISSUE TITLE
Using the appraisal NPC Chochoroon in Al Zahbi causes zones to crash

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#2829]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

My group just finished a few Lebros Cavern runs, had some ??? Earrings to appraise. As soon as the item was traded to Chochoroon, it caused Whitegate/Al Zahbi to crash, in addition to a few other zones. When we logged back in, we tried it again and it caused a second crash. 

Using the Drahbah in Whitegate instead did not cause a crash.

**Comment by KnowOne134** [comment]
Were you in party. And if so were all player in same zone? If not which zones?

Unable to produce on test servers and need all details

**Comment by Tjonke** [comment]
We had a party of 4 and all were in Al'Zahbi standing next to the NPC.

**Comment by bkesecker** [comment]
Fixed.  Did not auto-close.  Closing.
