### ISSUE TITLE
PUP Desummon in Lebros Caverns Evac Duty, Crashes Assault an others inside.

### ISSUE THREAD

**Issue by Kogasho** [EdenServer/community#2831]
### Checklist
 
Zoned Crashed when other pup in party De-summon his pet, when we were all kicked from the Arena we appeared halfway across the zone in Mount Z. It counted as a loss of tag because of the crash. 

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by Kogasho** [comment]
Refund on tag?

**Comment by JerichoReigns** [comment]
Did two runs also as as Puppetmaster. First run using PLD automation frame. No Deactivate used. Still crashed at 4th stonewall at 30%.    Second run Used WHM Automation for the Haste Di2/Poison2 spam. Deactivated Automation after first wall was downed. Resummoned BLM Automation at second wall. Used up its MP reserves. Deactivated Automation and resummoned while engaged with the wall, crashed immediately. Or as far as I can tell about it.    Lost both tags.

**Comment by KnowOne134** [comment]
belive oy has been fixed, duplicate issue report
