### ISSUE TITLE
Beeswax HQ Tier code check

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#2833]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)
30181205_0
### Details

Hello,
After doing well over 300 synths of Beeswax, I've yet to get a HQ2 under trituration yielding 6 Beeswax. Can we get a code check?

https://ffxiclopedia.fandom.com/wiki/Beeswax

Synth I'm using:

Alchemy (5/16)
Yield: Beeswax x 2
HQ 1: Beeswax x 4
HQ 2: Beeswax x 6
HQ 3: Beeswax x 8
Fire Crystal
KeyItemTrituration
6 x Beehive Chip
1 x Distilled Water
1 x Triturator

Current alchemy level: 57 (T3 HQ rate)

Thank you.

**Comment by Tjonke** [comment]
It's the same for Black Pearls, went 1/144 and 0/144 on my last 2 attempts Shall Shells. With 105 Bonecraft

**Comment by StriderClerix** [comment]
Nevermind can close, must have been incredibly unlucky. I did a smaller batch today and did quite a few T2 HQ's
