### ISSUE TITLE
[Dynamis] Can only steal Whiteshells from Goblins and Demons

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#2834]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

While in Dynamis - Jeuno or Beaucedine and attempting to Steal currency from Goblins, you will only receive Tukuku Whiteshells.  Similarly, when fighting the demons in Dynamis - Xarcabard, you can also only steal Whiteshells.  

We bring 3-4 Thief every run and they are all reporting this behavior.  Goblins and Demons should have all 3 single currency types in their Steal pool, not just Tukuku Whiteshells.

To reproduce go and steal from them and you will always get a Whiteshell, I promise!

**Comment by rka666** [comment]
To add, cannot steal any currency from Goblin type mobs in Dynamis Beaucedine. It always fails. Myself and friend THF tried that at a few runs with Steal sets on. Other type mobs are perfectly fine.

**Comment by InoUno** [comment]
Resolved with January 25th, 2021 update.
