### ISSUE TITLE
Jungle Boogeymen NIN RA is ignoring third eye.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#2835]
### Checklist

- [ /] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [/ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Cyaneous-toed Yallberry's Shurikens are ignoring third eye. Happens every time.

Version 30181205_0

**Comment by 59blargedy** [comment]
should be resolved by 10/18 update
