### ISSUE TITLE
Mana Chestnut Lumber/High Mana Wand Recipes aren't in the game

### ISSUE THREAD

**Issue by tobioeden** [EdenServer/community#2839]
### Checklist

- [/] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [/] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/] I have provided my client version in the details. (type /ver into your game window)

### Details

The wiki for them dates back to 2006, but the Mana chestnut lumber recipe isn't currently functional.

Yield: Mana Chestnut Lumber x 1
Crystal: Wind
Crafting Tool: Wood Purification
1 x Chestnut Log
1 x Earth Anima
1 x Light Anima
1 x Water Anima

Here is a link to the 2006 wiki page.
https://ffxiclopedia.fandom.com/wiki/Mana_Chestnut_Lumber?oldid=56278

**Comment by 59blargedy** [comment]
could not reproduce on test, recipe exists and is synthable with the right KI. comment if further issues.
