### ISSUE TITLE
Signet Staves not working.

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#284]
Tested with Kingdom Signet Staff. No effect but the charge was consumed on the staff.

**Comment by jmcmorris** [comment]
Tested and this appears to be working. Are you aligned with San'dOria?

**Comment by Aneyus** [comment]
Yeah, I am. I'll try to let my signet run out so I can test it again sometime soon.

**Comment by jmcmorris** [comment]
When you do please let me know what zone you try it in too. Thanks!

**Comment by godmode** [comment]
I'm closing this ticket. Please comment if it happens again
