### ISSUE TITLE
Fish Scales Synthesis - Incorrect Skill Cap

### ISSUE THREAD

**Issue by freddiepines** [EdenServer/community#2840]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Client version: 30181205_0

Recipe for fish scales / H.Q fish scales is coded incorrectly, should be 6 as show below:

https://ffxiclopedia.fandom.com/wiki/Fish_Scales

Latest revision shows skill cap of 6 and older versions show 6 as well:

![image](https://user-images.githubusercontent.com/50085658/81888322-1d144e80-956f-11ea-9cd2-f9d43a22a7ab.png)

With bonecraft skill at 60 I'm hovering around 25%~ HQ rate which is T2, probably set incorrectly to 16 as seen here:

![image](https://user-images.githubusercontent.com/50085658/81888879-3ec20580-9570-11ea-9a2d-ad9fd435e9d7.png)

Reproduce by using lightning crystals on a batch o' Gavial Fish.

**Comment by PrettyCoolPattern** [comment]
Change line 859 from:
`INSERT INTO `synth_recipes` VALUES (743,0,0,0,16,0,0,0,0,0,0,4100,4242,4477,0,0,0,0,0,0,0,864,1587,1587,1587,12,1,2,4,'Fish Scales'); `

to

`INSERT INTO `synth_recipes` VALUES (743,0,0,0,6,0,0,0,0,0,0,4100,4242,4477,0,0,0,0,0,0,0,864,1587,1587,1587,12,1,2,4,'Fish Scales'); `
