### ISSUE TITLE
Dynamis - Beaucedine Attestation NM loot tables

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#2841]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Currently the attestation NMs can drop multiple and duplicate attestations. Also as far as I could tell with 150~ kills it _seems_ like they do not have their chance to drop 100 pieces that should be included on the loot table. A check on that while fixing the tables would be great.  
![BFj8nLF](https://user-images.githubusercontent.com/2160211/81977216-4aa0dc80-95ef-11ea-999b-0e36e71d18ab.png)

Era screenshot of a 100 dropping from Attestation NM:

![b8KA8lz](https://user-images.githubusercontent.com/2160211/81977332-7d4ad500-95ef-11ea-9dd3-298b5d69e0df.png)

**Comment by Mozzy4Ever** [comment]
Killed 105 Goublefaupe on the test server with no TH (low kill count but was looking into the Invulnerability drop rate, so didn't need too much). The following is my findings:

35 Force
40 Glory
37 Righteousness
**13 Invulnerability** - Bolded cause this was a ~30% drop rate separate from the other 3 attests according to wiki

9th kill - Righteousness & Invulnerability 
**10th kill - Force dropped twice (Shouldn't be possible)**
**15th kill - Force & Righteousness (Shouldn't be possible)**
18th kill - Righteousness & Invulnerability 
20th kill - Force & Invulnerability 
**21st kill - Righteousness & Glory (Shouldn't be possible)**
26th kill - Glory & Invulnerability
27th kill - Righteousness & Invulnerability
_**29th kill - Righteousness, Force AND Invulnerability**_ (wut)
30th - Force & Invulnerability
35th - Force & Invulnerability
46th - Righteousness & Invulnerability
**58th - Force & Righteousness (Shouldn't be possible)**
**65th - Glory & Righteousness (Shouldn't be possible)**
72nd - Force & Invulnerability
84th - Righteousness & Invulnerability
**85th - Glory dropped twice (Shouldn't be possible)**
**88th - Force dropped twice (Shouldn't be possible)**
94th - Glory & Invulnerability
**98th - Righteousness dropped twice (Shouldn't be possible)**
101st - Righteousness & Invulnerability

Hundreds: 1 Montiont, 1 Lungo, 1 100 byne

**Comment by bkesecker** [comment]
Some of these are absolutely the wrong rarity (guaranteed)
```sql
SELECT itemId,rarity FROM dspdb.mob_droplist WHERE itemId BETWEEN 1556 AND 1569; -- Attestations
```
