### ISSUE TITLE
DCing from Excavation Duty dumps you in the middle of Mount Zhayolm

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2842]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

If you DC/R0 from Excavation Duty (Lebros Cavern) and reconnect you'll log back in the middle of several Hilltrolls in Mount Z. 0/10 experience.

**Comment by KnowOne134** [comment]
This was fixed few weeks back
