### ISSUE TITLE
Sheep in Antlions Clothing- Tuchulcha can be RA'd during Sandpit and reagro'd

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#2846]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Initiating a ranged attack on Tuchulcha at the right time as it is burrowing will cause you to hit it and make it pop right back up, rather than running away and needing to be found again.

**Comment by KnowOne134** [comment]
resolved in October 4, 2021 update
