### ISSUE TITLE
Lebros Cavern Assault Puppetmaster Crash

### ISSUE THREAD

**Issue by JerichoReigns** [EdenServer/community#2847]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
 
Day 1 of Assault releasing, my party and others at that time had the zone crash two runs in a row. Not knowing what I've come to know now my party and myself tried again with the same setup only to crash once again resulting in not 1 but 2 lost ID tags. Thinking it was possibly me as Puppetmaster being the factor of breaking the zones, I swapped to SAM instead and proceeded without issues.
Two days later going again as PUP to get an idea of exactly what could be the issue, we tried again. This time I watched very carefully as to the exact actions and hows/whens of abilities used in different situations. I believe I have found the reason and moment of the zone crash.

The following is a detailed report of the actions I took and what I've come to believe.

First run using PLD automation frame. Destroyed the first 3 Brittle Rockwalls without issues. At the fourth wall, I decided to swap over to the BLM automation to speed it up a bit. So after already being engaged with the wall being around 30% at the time, I Reactivated my automation. The instant I did the zone immediately flat-lined upon the "Jericho uses Activate." popping into the chatlog. The following run, using the BLM automation from the beginning this time around, we blew through the first 2 walls without issues. I used both Activate and Deactivate inbetween the walls. No crashes. No issues. Coming up to the third wall, shortly after engaging it BLM auto ran out of MP. So I did the good ole Deactivate/Activate for the MP refill. Deactivate did indeed desummon my automation, and a moment later hitting my Activate macro to bring it back out, "Jericho uses Activate." was the final chatlog line to appear and the server zone once again crashed. 

Seeing as I've used both abilities between the walls leads me to believe the exact reason of the crashes are: **### Being engaged to the Brittle Wall and using Activate.**
Have not yet tried to disengage and moving out of range to Activate automation again, so I cannot be sure that would be a solid temp fix to not crash zone or not. Seeing Activate WHILE engaged with the wall has happened 2/2 times of doing it, and 0/4-5 times while not engaged must be a good start to finding the reason behind the crashes. Good luck fixing the issue!

**Comment by bkesecker** [comment]
Attempted to reproduce several times, but no luck.  Tried swamping frames in/out of combat stance, as well as engaged on multiple rocks.  However, I do see the probable cause in the code.  Would really like to reproduce before calling it a fix.

**Comment by KnowOne134** [comment]
believe has been fixed, reopen issue if re occurrs

**Comment by Crescensx** [comment]
Had my Pup crash the assault again tonight. Was using BLM PUP. I was engaged on a rock and the puppet was mid cast, I used deactivate and then immediately used reactivate. Seemed like the R0 happened soon as I hit reactivate.

**Comment by Snugglepunk** [comment]
Crashed Leujaoam Cleansing Assault with Puppet today.  Deactivated the WHM pup and immediately hit activate and zone R0d.  In my SS I have the old pets name greyed out + new pet active.  Perhaps its something to do with having 2 pets active and waiting till the first ones name disappears is not crashing the zones
