### ISSUE TITLE
Zaldon not accepting trades/fish since the patch (5/16/20)

### ISSUE THREAD

**Issue by trodeghero** [EdenServer/community#2849]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

After today's patch, Zaldon is no longer accepting any of my fish when either trading or using /item "fish name" <t>.  I attempted zoning, reloggin, and trying 3 different fish (Lik, Gugrusaurus, and Bhefhel Marlin). He does not respond when attempting to trade.  
Client version 30200327_2

**Comment by bkesecker** [comment]
This is fixed live, but please leave this open so I don't forget to push the code fix to our source control repo.
