### ISSUE TITLE
Jailer of Justice - adds mijin multiple times/don't die

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2852]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Right now Qn'Xzomits are not despawning after they Mijin the first time, and will continuously spam Mijin unless killed. 

Video here of it despawning after mijin: https://youtu.be/NTDtEmltkHM?t=65

**Comment by roriffxi** [comment]
They also don't seem to do their timed mijin if left up.  You can pull them and tank them as long as you don't dmg them without mijin going off.

**Comment by icariumkupo** [comment]
Mijin doing much more damage than retail. 800+ damage

In the beginning of this video you can see it barely breaks the stoneskin on this red mage.

https://www.youtube.com/watch?v=mbP5pZqH6yU
