### ISSUE TITLE
8-2 Qausilumen Break if hit by AoE

### ISSUE THREAD

**Issue by Raphtalia1** [EdenServer/community#2853]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

Qausilumen's in escord quest 8-2 will stop moving and never restart moving if hit with an aoe (specifically frightful roar from blumage, possibly all aoe's)

**Comment by Imdesyda** [comment]
Can confirm this. Once you hit it with an AoE you are also able to attack them as if they are an enemy. While not a fix you can kill the bugged one and run back to spawn a new one without having to wait for the first one to time out.

**Comment by 59blargedy** [comment]
this was resolved in a previous update by another dev
