### ISSUE TITLE
Level sync in alliance leveled - Broke party possibly server wide

### ISSUE THREAD

**Issue by Fng098** [EdenServer/community#2855]
### Checklist

- [ x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x ] I have provided my client version in the details. (type /ver into your game window)

### Details

While alliance'd and level sync'd our sync leveled and it busted the alliance and party.  Additionally other seemed to shout that their party busted as well.   

Ver 3018205_0

**Comment by bkesecker** [comment]
I stopped the login server for maintenance, that is what busted things.  Closing.
