### ISSUE TITLE
Nadrs additional effect: Poison has wrong damage.

### ISSUE THREAD

**Issue by ffxireports** [EdenServer/community#2856]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

The wiki suggest it does 10dmg/tick. Doing some testing, I calculated it's only doing 3dmg/tick

Data of calculation:

Mob: Diatryma
Dmg: 45 = 100%->98%
45/2 = 22.5
1%=22.5hp

Proc'd at :19s
1% taken at :43s
43s-19s=24s
24s/3s = 8 ticks
8ticks/22.5hp(1%) = 2.8/tick (assuming rounded to 3)

**Comment by KnowOne134** [comment]
Awesome math deductions. Will find some time to fix you up by next patch
