### ISSUE TITLE
Blade Bash - Additional Merits do not decrease recast time

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#2857]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Currently, one merit into Blade Bash by default is a 15 minute recast. Putting a second and third merit increases the plague duration as per blade_bash.lua on DSP.

>-- Applying Plague based on merit level.
>    if (math.random(1,100) < 65) then
>        target:addStatusEffect(dsp.effect.PLAGUE,5,0,15 + player:getMerit(dsp.merit.BLADE_BASH))
>    end

This is out of era, additional merits should decrease recast time by 2:30 per merit, and not affect plague at all.

What it should be:

1 Merit: 15 Minute Recast
2 Merits: 12.5 Minute Recast
3 Merits: 10 Minute Recast

**Comment by Relic3** [comment]
To add to this, weapon bash merits for DRK are using incorrect OOE values based on when they buffed weapon bash to 3mins. On Eden weapon bash is a 5minute recast and is using 6s buff for each merit and it should be 10s for each merit.
