### ISSUE TITLE
Excavation duty mines not working

### ISSUE THREAD

**Issue by trodeghero** [EdenServer/community#2859]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30200327_2

While doing Lebros cavern assault 'excavation duty' our party tried to use a mine dropped from the qiqirn on the wall but it had no effect.  We were able to get a 2nd mine and it also didn't work.

**Comment by 59blargedy** [comment]
mine user must be engaged to the wall, works fine if you do that
https://ffxiclopedia.fandom.com/wiki/Excavation_Duty
"To use a mine, have the person engage the Brittle Rock, use the Qiqirn Mine on it, and stay engaged while it blows it up. "

**Comment by trodeghero** [comment]
Reran it again and it worked, we were not engaged.  Thanks, sorry for putting in the report
