### ISSUE TITLE
Unable to purchase Fishing Guild GP items

### ISSUE THREAD

**Issue by GRiMiNSANiTY** [EdenServer/community#286]
I attempted to purchase a Robber Rig from the Fishing Guild. When I complete the transaction, I do not have the item nor do my Guild Points deplete.
https://i.gyazo.com/thumb/1000/05c56b0a6a670f0ad52b26e060fa021e-jpg.jpg

**Comment by Setz0r** [comment]
I'll take a look at it in the morning, thanks!

**Comment by chlorr** [comment]
this happened with some of my other crafts, might be out of era or low rank, they have all been showing since lv30 in alch at least, but some are higher ranks req to buy

**Comment by GRiMiNSANiTY** [comment]
Everything is displaying correctly. The title of the ticket could be a little misleading. Currently the only GP items available for purchase are Robber Rig and the KI Frog Fishing (both which are obtainable at the Novice rank). The only one I tried purchasing is the Robber Rig.
