### ISSUE TITLE
Jailer of Fortitude Highly Resisting Ranged Attacks

### ISSUE THREAD

**Issue by Garphilius** [EdenServer/community#2862]
### Checklist

- [/ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- /[ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Almost BiS Ranger doing 3 to 4 damage on each ranged attack. According to wiki from back in 2007, this jailer should not have a physical resistance against ranged attacks.

"The Jailer is highly resistant to all forms of physical damage except ranged attacks."

1) Play a Ranger.
2) Pop Jailer of Fortitude.
3) Sit back and laugh as your ranged attacks do 3 to 4 damage on this jailer.

**Comment by slassen** [comment]
From what I've been told this is a thing with all ranged attacks and high level or high defense mobs. I may look into ranged attacks at some point in the future. Is it fair to say all jailers are resistant to ranger or is this specifically found to be a bug on Fortitude?

**Comment by Garphilius** [comment]
In cannot comment on other high defense mobs like HNMs as I do not camp them at all. For Sky Gods, ranged attack seem OK, nothing huge to worry about. 

For Sea, we have only done Temperance, Fortitude and Faith. For temperance I do not bother going on RNG as other jobs are better for this fight. For Faith, I also do not come on RNG as my other DD jobs performs better. However, on a fight like Fortitude where magic and ranged attack are extremely viable, I came on RNG and was disappointed with the 1-3 dmg ranged attacks. Ranged attacks should be doing way more on this fight.

**Comment by Serephim** [comment]
Yeah ranged attacks underperform on a lot of HNMs even with a relic weapon and the best arrows in the game.

**Comment by slassen** [comment]
Closing this as no new information given as if this is specific to Fortitude. Please comment if new data is available.
