### ISSUE TITLE
Mercenary Rank Points

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#2863]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Completed all 5 PSC Assaults, but according to Abquhbah I only have 19-24 points.
https://ffxiclopedia.fandom.com/wiki/Mercenary_Rank
Completing an Assault for the first time should award 5 points.
Note, I failed my first try of 'Seagull Grounded', maybe that's why I didn't get the 'first completion' credit? Or is the system not correctly implemented yet anyway, since we can't rank up as of yet?

**Comment by KnowOne134** [comment]
There is no rank ups yet and only 1 tier of assaults open. Will come when more are made

**Comment by VirtuosusFFXI** [comment]
What is the long term policy on implementing mercenary ranks? In era, while it was not the most efficient, you could hit max rank off of tier 1 assaults if you wanted to. If ranks are going to be gated behind assault tiers, then there is going to be a lot of wasted potential, as every 25 days that a new tier isn't out, that is a missed opportunity for players to gain an extra rank towards Perdu weapons and other items, as well increased Sanction duration.

**Comment by KnowOne134** [comment]
Can only work as fast as I can in free time. Come out as they are tested and ready is plan. 1st win does give 5 points, after that its 1.

**Comment by KnowOne134** [comment]
Cant open next rank until the next assaults are even ready as the client unlocks the next set in memory and then people will be stuck in uncompleted assault missions

**Comment by VirtuosusFFXI** [comment]
Oh, to be clear I was not talking about adding new assault tiers, but simply the rank up quests being implemented so as to not waste the 1 point players get every Assault completion after the first. I believe once you hit 25 rank up points, you are capped out until ranking up, correct? So any excess points would be wasted. 

Edit: I see, so it is a client limitation. That is rough. Thanks for the explanation and the work you've done.

**Comment by KnowOne134** [comment]
Not really an issue but I'll keep.it open so people can see it's not coded

**Comment by panfunk** [comment]
I made the topic cuz the mercenary rank point calculation (if implemented) appears to be wrong. Or the NPC message doesn't work correctly (if implemented).
Not cuz I couldn't rank up.

**Comment by roriffxi** [comment]
Is it possible to unlock the rankups and then use purple system text to let players know that an tier2+ assault is not available while trying to accept it that the mission isn't available and block the action?  It will result in the lists showing each new tier of assaults, most of which won't be available to actually accept, while allowing people to rank-up?

**Comment by KnowOne134** [comment]
It is not

**Comment by KnowOne134** [comment]
has been added
