### ISSUE TITLE
Crafting interrupted at H-7 outside of Port sandoria port

### ISSUE THREAD

**Issue by Omnidex1** [EdenServer/community#2864]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
client version 30181205_0

I use a single macro which does the following:
/lastsynth <wait25>
/lastsynth <wait25>
/lastsynth <wait25>
/lastsynth <wait25>
/lastsynth <wait25>
/lastsynth

I have a screenshot that I posted in "tech-support" at 3:11 pm EST on May 18, 2020.  I had 4 failed attempts in a single screenshot, and I've lost more than this.  I was not moving or by any means that I know "interrupting" the synthesis.  This isn't the first time this has happened, but it seems to happen more frequently the more time goes on.  My fps was previously unchanged and untouched until someone in my linkshell started talking about it and I chose random numbers.  It's now set to "2" and is still interrupting on occasion.
![Omnidex_2020 05 18_150947](https://user-images.githubusercontent.com/65565855/82252574-3d505e80-991d-11ea-846d-dcda6ebef941.png)

**Comment by Kurtalicious** [comment]
Make sure there is a 23 second wait between synthesis attempts. If the server see that you are synthesizing too quickly it will interrupt you synthesis and take your materials.

**Comment by KnowOne134** [comment]
Correct, frame rates and trying to synth too quickly can result in a full fail I even put mine to 24 just becuase, 1 second while I afk  a few synths won't hurt
