### ISSUE TITLE
Fish Rankings Bug

### ISSUE THREAD

**Issue by Valkyre506** [EdenServer/community#2866]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0
Recently with the newly added Fish Ranking content I've ran into a bug. The bug being when i turned in my #1 ranking Giant Donko Chenon accepted my fish and took my Gil but when the leaderboards became visible to the public my name was not there with the rest of the 150 donkos. When prizes became available to the top ranking Fishermen i did not receive my Pelican Ring. Below is a picture of the Fish i put in my bazaar. thx.
![img_20200513_095748](https://user-images.githubusercontent.com/65469162/82261486-75639b80-9935-11ea-92a7-62941c1995f8.jpg)

**Comment by KnowOne134** [comment]
Supposedly it's fixed for next contest

**Comment by darkraven922** [comment]
Yea but are they gonna trade the pelican ring for the fish as said via Setzor check the  discord screenshot ive linked. Cuz GM Help Desk ask for a github. But the github says its fixed for the next contest.
![Setzor_part_2](https://user-images.githubusercontent.com/58438018/82263208-64645b80-9930-11ea-9a1c-183f6adec8af.JPG)
![Setzor_part_1-1](https://user-images.githubusercontent.com/58438018/82263219-6a5a3c80-9930-11ea-88ea-16ba1debae70.JPG)

**Comment by freddiepines** [comment]
Looks like this still may be an issue - had a friend turn in a 1319 size fishing and he does not appear on the ranking board:

![image](https://user-images.githubusercontent.com/50085658/86518888-11246a80-be03-11ea-97bd-faefcef768a9.png)
