### ISSUE TITLE
Redoing Sandy Rank 1-3 Mission (Save the Children) resets rank / rank points

### ISSUE THREAD

**Issue by ThoseWhoFight** [EdenServer/community#2868]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Was already rank 2 and had turned in enough crystals to cap out rank points for rank 2. I mistakenly selected the "Save The Children" mission a second time and since there's no way of cancelling, had to re-accomplish the mission to progress. Upon completion it gave me rank 2 achieved animation - as if I had not completed the mission yet, and also reset my rank points bar, effectively allowing me to repeat this endlessly for unlimited conquest points. Tested with more stacks of crystals to confirm. I'm assuming it is possible to redo this as many times as one would like and not intentional, so I will refrain from doing so. This should probably be fixed quick. 

version 30181205_0

**Comment by Beakthing** [comment]
This happened to me some days ago. No matter your current rank, repeating this Mission will set it back to 2, making it impossible to get your ranks back (because you already completed the quests associated with ranking up).

**Comment by InoUno** [comment]
Fixed in December 1st 2020 patch.
