### ISSUE TITLE
Summoner Elementals

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#287]
Elementals summoned by SMN sometimes cast spells like they should. But every other day they don't cast spells at all.
Last week I exped in Valkurm Dunes, 3 SMNs vs. gobbies from Lv11 to 17ish, and our elementals were casting spells regulary.
Today again in Dunes with 4 SMNs vs gobbies and from Lv11 to 15 with nothing but elementals summoned there was not a single cast.

**Comment by Cheezcakee** [comment]
They're also the wrong ones. Like for example it will say it's casting fire spirit, and the image will be fire spirit, but the mob itself isn't a fire spirit and doesn't resist fire II for example. I was killing the elementals that accompany tonberry harrier, and they were not water or fire spirits when summoned.

**Comment by roriffxi** [comment]
I'll try to experiment and add more to it.  Here are the details I can recall at this time.

One day while PL'ing in the Dunes as SMN, i summoned a light spirit to kill a goblin that agro'd someone.  The spirit was casting banish, flash, holy and dia.  This was without level sync.

Then, other times, still without sync it just won't cast.

WHen I did CoP 2-5, the Mammets fight, running through Riverne Site A (lvl 40 capped zone) my spirits were casting.  They also cast during the Mammets fight.

However, earlier that day in the Aquaducts they were not casting (also a 40 cap zone).

It seems that most-often they will be casting just after a patch, but then sometime within the next couple days they will stop casting.

They were not casting yesterday (12/7/2018) while I was in a sync'd party.

**Comment by jamiecol25** [comment]
Hmm not sure if this is the correct report but only one I could find. Summoner elementals don't cast spells like they should, I will do more testing but the main one is light spirit. It should prioritise curaga over any spell if people need heals but they don't do it. The only spells I see them cast are offensive.
