### ISSUE TITLE
Golden Salvage - Notes

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2871]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Golden Salvage Eden Notes:
-Eden chests can be attacked before opening, even the non-mimic one with the idol inside (this chest can attack even though it's not a mimic if attacked, attacks as a normal chest)
-Eden mimics only aggro when opened, chests shouldn't need to be opened to become mimics, mimics aggro from 1.9 yalms away (true sound) on retail (https://i.gyazo.com/27cb850b5114f1b251206d94829b08ad.mp4)
-Chests should have no name above them until they become mimics

Other notes from retail:
-Draw in range for mimics is around 22 yalms (https://i.gyazo.com/d419a38ce8ebd1b743e5103df41ac433.mp4)
-Mimics take ~30 seconds to deaggro/change back to chests from being out of draw in range unless target they attacked died / was desummoned (https://i.gyazo.com/6d428e738b1fd4b520531a02e35b0275.mp4)
-If you walk back into range of draw in after being out of range the mimic will draw you back in (https://i.gyazo.com/d419a38ce8ebd1b743e5103df41ac433.mp4)
-Chest with idol inside is the only one that can be successfully opened, as mimic chests will always attack you before being in opening range (https://i.gyazo.com/a1c25a7baafb4dde66c37a4fc7bb1dee.mp4)
-Percipient fish have 3.9 yalm true sound aggro range (https://i.gyazo.com/567a58d1f34b8176e72368255606b28b.mp4)

version 30181205_0

**Comment by roriffxi** [comment]
Additionally, Mimics have a high amount of threat on the person who agro'd them.  THis makes it very difficult for a carbuncle to pull them off (usually the carbuncle has to hit 2-3 times or you have to use meteorite).  The threat should be so low that a *missed* attack from an avatar will cause the mimic to start attacking them.

As they behave now it would be pretty much impossible for an avatar form a /smn to take hate.  Using garuda with aerial armor as /smn was a valid strategy on retail.

The above point of mimics agro'ing without needing to be checked I don't think is era accurate:
https://www.youtube.com/watch?v=pZZeAaXReIc

This video from 2007 clearly shows the player having to check the chest for it to become a mimic.

**Comment by FariskaEden** [comment]
Eden mimics feel like they have the high threat right now since maybe opening them is like initial hate when you act to pull a mob. 

You can never actually "open" mimics, they will always display the message that you must move closer to open them. By doing that it leads you closer to their aggro range making you think that you have to "open" them. That's why if they aggro onto you, using /smn or having someone do something to the mimic out of range of the draw in lets you walk away.

Your video does not show the chat log but this one does https://www.youtube.com/watch?v=N6bWUxz-bjY. No message was displayed that they opened the chest so them having an aggro range is most likely era accurate and was likely never changed.

**Comment by Volkaru** [comment]
The hate is an issue with all mobs. Kanican says the initial hit hate is this ridiculously high amount, which is what eden uses. But on retail it clearly wasn't, and has been mirrored by almost every player. It's been brought up multiple times, but hasn't been changed yet because there's no definitive amount to change it to.

**Comment by slassen** [comment]
I’m not completely sure what you mean but Eden using the VE and CE values that were recorded in the enmity table.

**Comment by Volkaru** [comment]
Exactly. And it's been noted countless times that the initial aggro enmity is overblown from that chart.
