### ISSUE TITLE
Dynamis loot doesn't sort if everyone passes if there character is logged out within the zone

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#2877]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
We've had this issue before where everyone passed after the 5 min warning and loot didn't sort and was lost.   Today during the 5 min warning, we had passed all loot and it wasn't sorting until a chracter who had been logged out earlier in the run, logged in and passed the loot.  As soon as they passed the loot it then sorted.

Repro:
Go into dynamis
Enter a char into the zone and log them out
Kill a mob for loot
Have all logged inchars pass the loot

Observe:
Loot doesn't sort.

Next:
Log the logged out char in and have them pass before the loot would auto-sort normally.

Observe:
Loot sorts.

**Comment by danismyhero** [comment]
Coupled with this, even if all loot is not passed, in retail the last person to enter the dynamis zone would receive the treasure pool upon the forced exit from the expiration of the Perpetual Hourglass.  

This of course would include tractors, disconnects > relogs, dropping glass and reentering, etc.

**Comment by InoUno** [comment]
The issue with loot not sorting even if everyone else passed should be resolved with the February 15th, 2021 patch.
