### ISSUE TITLE
Federation Kukri not giving stats when outside own nation's control

### ISSUE THREAD

**Issue by ffxireports** [EdenServer/community#2878]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Simply +7 atk outside of own nation's control. Unequipping while in Valkurm owned by Windy as a Bastokian does not drop my atk by +7.

**Comment by 59blargedy** [comment]
i cannot replicate, equipping kukri outside my nation's control adds 7 attack, changing to another knife removes it, including in sea
 - one thing to note is that you need signet or sanction up for these effects to proc. going to assume those buffs werent active when attempted, but if you're still around feel free to comment.
