### ISSUE TITLE
Map of the Aqueducts - Mini-Quest

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#288]
Tried yesterday to aquire the "Map of the Aqueducts". Checked all rooms on the 3rd Map of the Aqueducts and clicked every ???, but didn't receive the map.
https://ffxiclopedia.fandom.com/wiki/Map_of_the_Aqueducts

Little note, the mission relevant western portion of map3 only had the "???" to open the secret gates.
The eastern part of the map had two "???" that didn't surve any purpose, plus the "???" to open the gates.

**Comment by Mikokiko** [comment]
Can confirm this. I tried to get the map yesterday, used my 2 keys, went in all 4 room and found exactly the same thing. I tried today again after maintenance, still not working. 

Spent 4 keys for nothing, I should have checked here first RIP

**Comment by Jimmayus** [comment]
I see this was moved to development but I just wanted to confirm that it is still nonfunctional even after updating to current dsp.

**Comment by Volkaru** [comment]
Can also confirm it's still not functioning. Just went to all four rooms. No one was able to obtain it.

**Comment by 59blargedy** [comment]
resolved with october 11th update
