### ISSUE TITLE
[Assault] Excavation Duty Brittle Rocks Ranger Issue

### ISSUE THREAD

**Issue by ElectroNicMan83** [EdenServer/community#2881]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
I have capped merit and here are the damage I did. I dont know if ranger was that bad in reail in this but it doesnt feel right.
Ranged attack - 1-3 dmg 
Barrage - 6
Slugshot- 10

**Comment by KnowOne134** [comment]
reopen issue if you find proof
