### ISSUE TITLE
Jailer of Prudence Tuning / Mechanic Issues

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2882]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)

### Details

Some of these are from test server, some are from live. 

* Exhibiting incorrect behavior when it comes to pop aggro. This is the same issues darters in DA, and other monsters have. You can't pop Prudence, grab one off on THF and zone it because the other one immediately goes back to the popper since they're weirdly on emnity table. Does not despawn. I understand it's a larger issue with the mechanic in general, but noting here since several strategies point this out as possible.
* The two are not using TP abilities in-sync
*** When mouth is open (once one dies) it takes half damage instead of more damage, but deals increased damage correctly.
* Seems to pop with perma flee speed that doesn't wear off, and keeps up with a NIN in AF boots at night, making it impossible to kite one while killing one. The second one in open mouth mode seemed to only have increased movement speed while in perfect dodge mode ( correct ). Can't say for sure since it was a live fight / weren't really testing, but movement speed on these is incorrect currently.

> They do not have increased movement speed over normal Hpemde, and they "swim" in the same fashion, so kiting one image around the island southwest of the spawn point while the other one is manaburned near the spawn area is a preferred tactic. - the wiki

* Triple attacks proc insanely often (almost every attack)

Overall feels pretty over tuned, especially the open mouth mode not taking any increased damage.

**Comment by Lilswitche** [comment]
The pop emnity mechanics also created some weirdness with Jailer of Fortitude adds as well bouncing all over the place because it places the popper on the emnity list with some emnity.

As a work around to the pop emnity mechanics, you could optionally just have someone sack the pop and move forward from there with a clean emnity table.

**Comment by slassen** [comment]
I believe the popper was the THF in retail? Am I remembering this incorrectly? And you would pull off the THF/popper.

**Comment by perkuprightmeow** [comment]
Yeah, but with how pop mechanics are (started a report here #2883) whoever popped it just gets hate bounced back to them over and over, so the best workaround is just to have them die.

**Comment by slassen** [comment]
Ok, understood. This will probably stay more challenging until the in sync TP moves can be fixed. I’m still unsure why this doesn’t work on the test server or live server as it works local testing. But after that is fixed we can fix the other bugs that make this much harder than it should be.

**Comment by Tjonke** [comment]
Jailer of Prudence also completly ignores terrain, it swam right through walls when was kited making it impossible to keep ahead of it. And after killing the puller it swam right back through the wall/boulders.

**Comment by Satirof** [comment]
Our LS did prudence today, burnt down the first one in a respectable time, but found that the second one's defence shot through the roof with its mouth open (should be the opposite and be taking double damage compared to the first). My SA cannonballs were doing about 1/4 to 1/3 of the damage compared to the first prudence. Was a way overtuned fight (on the second prudence only)

**Comment by Satirof** [comment]
Commenting to state that prudence is still messed up once one of the twins is dead. The second one (with mouth open) still isn't taking increased damage.
I don't know what the patch notes mean with "■ The notorious monster Jailer of Prudence has been adjusted to ensure attack and defense buffs are removed upon death." but it's defense is still crap.

DRG dmg for reference (5 dmg jump, 40 dmg high jump, wyvern 20 dmg) (with mouth open)
When both were alive my jumps were doing ~120 on average, and wyvern was hitting for ~75
![Higana_2020 07 24_212309](https://user-images.githubusercontent.com/38270613/88390922-271abf00-cdf4-11ea-9aa8-1b92a92be359.png)

**Comment by Garphilius** [comment]
Aye, Prudence was not fixed. My hand to hand hits were doing 1 dmg.

**Comment by Slamm21** [comment]
the most important thing would be for a thf to be able to depop 1 like he could on retail.
You would use powder boots > pop JoP > run towards the zone until flee wore off, then use flee to make the rest of the way there.
While this happened the other group could fight the other one, making sure not to finish it off until the mouth opened.

**Comment by rude-jerk** [comment]
Resolved in May 31, 2021 update
