### ISSUE TITLE
Linking, Aggro + Enmity Mechanics are Incorrect

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2883]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Referenced this in #2882 so figured it probably needed it's own topic since it's been discussed a lot but nothing formal has ever been filed. Excuse me if I use the wrong terms. 

On Eden currently if a monster aggros or links to you, you are permanently on the 'aggro/hate' list for that monster:
Example 1: If you get aggro from a goblin in the dunes and someone pulls it off you (without you engaging or touching it or them) and they zone or warp, it will come back to you.
Example 2: If you pull lizards in the dunes and get a link, and someone pulls the link off of you and zones it / runs away and warps, the lizard will come back to the original puller aggro'd. 
Example 3: See 2, but if someone pulls the lizard off and you heal yourself/invincible/etc. you'll get hate from the linked lizard you preformed 0 actions on and should not be on the 'hate table/buildable emnity list' for. 

All of these are incorrect. If a monster links to you or aggros you, and it's pulled off of you by someone else it should not ever go back to you/you should not be able to preform an action on yourself that will generate hate on it and make it come back to you. 

Here's a quote to back this up: 

> When you take aggro from a monster by walking into their aggro range (sight/sound/magic/hp/number of cookies in inventory) you are not in their hate list. Instead you are, and this is the best way i can describe it, just their current target. If you imagine a monster having a hate list that shuffles around and a pointer to whoever is their current target, when aggroing happens only the pointer is updated with your character. The list remains empty. This means, and it can be easily tested, that if someone else does actualy comit any aggresive action to the monster, they will be added to the list but you will still be out, effectively ridding you out of any harm in the event that such person would lose hate (by dying, zoning or whatever case). This is the same reason why you can spam magic on the person that has aggro/link monsters following him without ever entering the list of any monster. Basicly, you enter the list if you perform an action on the monster or an action on someone that's already on the list (or by resting when a monster is following someone, but this is one of those weird cases that's a bit harder to explain).
From : https://www.bluegartr.com/threads/54056-deaggro-aggro-reset-and-some-party-dynamics-testing

Retail videos showing examples:
Example 1: https://www.dropbox.com/s/vq4gxxgtflkkc0s/2020-05-21%2018-12-36.mp4?dl=0 (does not return to person it aggro'd originally)
Example 2: https://www.dropbox.com/s/l1d2cibb9ut41g0/2020-05-21%2017-52-08.mp4?dl=0 (does not return to person it linked to)
Example 3: https://www.dropbox.com/s/d0xjh4df5bkcp21/2020-05-21%2017-56-44.mp4?dl=0 (Linked monster pulled off doesn't aggro/go back to original player if they do high emnity actions)

Thanks Bigswitche for sharing the forum post, and Jimmayus for helping me test/record on retail :)

**Comment by Lilswitche** [comment]
There are still a couple scenarios to test:
1) The way resting interacts with mobs that have aggro'd or linked to a party member; and
2) The "alliance hate" mechanic some seem to remember. Essentially, when you pull a mob and your party member is within detection range of that monster, will it then target the party member if the puller warps/dies/logs.

**Comment by 59blargedy** [comment]
resolved with 8/16 patch. comment if still seeing issues
