### ISSUE TITLE
Jailer of Faith randomly goes unclaimed and resets aggro

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#2884]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

While kiting Jailer of Faith in the square rooms near its spawn, it will sometimes randomly go unclaimed, regardless of how long it has been since last action. It will just stop chasing, go unclaimed (white) and resets enmity entirely, sometimes instantly regen'ing its HP by 10%. 

In one scenario, it had just been Bio'd 5 seconds prior and went unclaimed and started moving back to its spawn. In another scenario, a THF had just finished doing a ranged attack and it went unclaimed literally 1 second after.

**Comment by slassen** [comment]
Hmm this is likely due to not having an action on it in awhile or it having an action on you. This can happen with any mob. I can't remember the exact time but it will go white and lose hate. Is Faith the only mob that this has happened to you with or has it it happened with more?

**Comment by VirtuosusFFXI** [comment]
For me personally, this has only ever happened with Faith. As I said, it's gone unclaimed despite performing an action very recently, which is what threw me off. In fact, since I made this bug report I've fought it some more, and on one occasion I lost claim and it deaggroed *WHILE* casting Quake II on me, interrupting its own cast and just starting to walk back to its spawn.

**Comment by Kurtalicious** [comment]
> For me personally, this has only ever happened with Faith. As I said, it's gone unclaimed despite performing an action very recently, which is what threw me off. In fact, since I made this bug report I've fought it some more, and on one occasion I lost claim and it deaggroed _WHILE_ casting Quake II on me, interrupting its own cast and just starting to walk back to its spawn. That was an interesting one, lol

It lost faith.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
