### ISSUE TITLE
Dread Spikes incorrect duration

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#2885]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

Dread Spikes has the post 2015 Duration of 3 minutes. It should last 1 minute pre-2015.

Patch it was added in:
https://forum.square-enix.com/ffxi/threads/48564-Sep-16-2015-%28JST%29-Version-Update

**Comment by VirtuosusFFXI** [comment]
I believe Dread Spikes should also wear off early after its absorbed half of the user's max HP on initial cast and the damage it deals should be equal to the damage the enemy is doing to you, is that correct on Eden? I don't have DRK leveled on Eden so I don't know exactly how its working here.

**Comment by Imdesyda** [comment]
It does wear at 50% I believe, and absorbs 100% of melee hits. Haven't tested on mobs with magic reduction though. Can try to verify exact HP% later tonight
