### ISSUE TITLE
Dynamis: Death + Tractor = Double weakened

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2886]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Died in dynamis on BLM, had to get tractor'd to get raised. Got raised and all nukes were hitting for 0 as if I was double weakened even though I should've only been single weakened. Guessing it's because when you get tractor'd it zones you which gives 15 minutes of double weakened that gets removed and set to 5 minutes of what _should be_ single weakened

**Comment by 59blargedy** [comment]
tested a few times in various zones and it appears this no longer occurs
