### ISSUE TITLE
Please Audit Sulfur drop off Stone Eaters

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#2887]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

There's a shortage of Sulfur so I went out to farm some Stone Eaters. Drop rate with TH2 was around 50% so I think the Eden drop rate is currently set at Very Common (24/48/56%), where I think it should be Super or possibly Ultra Common.

https://ffxiclopedia.fandom.com/wiki/Stone_Eater

That says drop rate is 73%, I don't know how many people were farming this with TH1/2 back in the day so it's hard to determine the exact number.

**Comment by Mozzy4Ever** [comment]
Your data source only has 60 samples.

http://ffxidb.com/zones/191/stone-eater 1102 kills at TH0 with a 30% drop rate. Most likely a 24% base rate then since the next up is 50%

**Comment by 59blargedy** [comment]
came to same conclusion based on ffxidb last month and forgot to close.  thank you!
