### ISSUE TITLE
Dead Copy of a Puppet Follows You

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2888]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When you use activate, then deactivate (or have your puppet die) and change the head/frame of your automaton in its equipment menu a dead copy of the head/frame you have selected will follow you around until you reactivate your automaton again. This copy doesn't do anything else but follow you and can't be commanded, it also disappears upon zoning.

https://i.gyazo.com/8d0ae917c57fd3c2d77727a9ff9302cf.mp4

version 30181205_0

**Comment by slassen** [comment]
Lol that is awesome

**Comment by KnowOne134** [comment]
Well....Pup was suppose to be Necromancer

**Comment by FariskaEden** [comment]
I no longer see dead puppets.
