### ISSUE TITLE
Banish Spells versus Undead Physical Resistances

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2892]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When the banish line of spells are used on undead that have physical resistances (skeleton's 50% piercing resistance for example), it should reduce the physical resistances by a certain % depending on the tier of banish used. Currently no physical resistances are reduced when these spells are used.

Banish and Banishga reduce undead physical resistances by 50% for 15 seconds
Banish II and Banishga II reduce undead physical resistances by 70% for 30 seconds
Banish III reduces undead physical resistances by 90% for 45 seconds

Also lower tier banish resistance reductions can't overwrite higher tier ones and do not stack with/overwrite Tomahawk (i.e. Banish II cannot overwrite Banish III damage resistance, much like the Dia/Bio line of spells). Cleric's Mitts also further increase the bonus of damage reduction of banish spells by 1/8. The white mage Banish Effect group 1 merit increases the duration of the physical resistance reduction by 2 seconds each rank. Ghosts, skeletons and corses seem to be the only type of undead that have physical resistances.

https://www.bg-wiki.com/bg/Category:Banish_Spells
https://www.bluegartr.com/threads/68414-Banish-Fenian-Ring-Testing
https://www.bg-wiki.com/bg/Cleric%27s_Mitts
https://ffxiclopedia.fandom.com/wiki/Banish_Effect_(Merit)
https://ffxiclopedia.fandom.com/wiki/Category:Ghosts
https://ffxiclopedia.fandom.com/wiki/Category:Skeletons
https://ffxiclopedia.fandom.com/wiki/Category:Corses

version 30181205_0

**Comment by rude-jerk** [comment]
Resolved in November 30, 2020 patch.
