### ISSUE TITLE
Giga in qufim Island

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#2893]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Giga in qufim Island are way to strong, overtunned,  would be fun to xp on them and those in tower like retail.  ( also mamool Ja merit party would be fun)  We fight one and half pt die.  Grandslam did 361 dmg on a 390 hp elvaan.

**Comment by 59blargedy** [comment]
this should have been resolved in the recent mob and mob skills update, can comment if not the case and will reopen
