### ISSUE TITLE
Gallinipper in Attohwa Chasm should not aggro

### ISSUE THREAD

**Issue by Mahou81** [EdenServer/community#2896]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0
The Gallinippers in Attohwa Chasm should not be aggressive. However they aggro my lv 44 whm character. I checked ffxiclopedia history page for Gallinippers and 2006 page also states they do not aggro. Source: https://ffxiclopedia.fandom.com/wiki/Gallinipper?oldid=155809

**Comment by KiplingFFXI** [comment]
This looks correct. Every wiki page I have found on these mobs says the Gusgen Gallinippers are aggressive but not the Attohwa Chasm Gallinippers. 

**Sources:**

- FFXIclopedia: https://ffxiclopedia.fandom.com/wiki/Gallinipper?oldid=155809

- BG wiki: https://www.bg-wiki.com/bg/Gallinipper

- Somepage: http://ffxi.somepage.com/mobdb/2743
