### ISSUE TITLE
Goobue Hummus drops from wrong mobs

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#2897]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Goobbue Humus currently is dropping from Goobbue in Zi'tah, when it should be dropping from Goobbue in The Boyahda Tree in era. 

Current retail drops: https://ffxiclopedia.fandom.com/wiki/Goobbue_Humus
Era drop location: https://ffxiclopedia.fandom.com/wiki/Goobbue_Humus?oldid=296937
ver: 30181205_0

**Comment by MrBeignet** [comment]
Thanks for pointing that out Falz.

After speaking with a player farming in Zi'tah quite often, it appears that Humus doesn't drop in the Sanctuary anymore (it used to, some patches ago), its pool place have been swapped for a Dahlia.

It also looks like Old Goobue in the Tree don't drop anything except for crystals. Elders seems unafected.

**Comment by 59blargedy** [comment]
this should have been resolved on saturday's patch on all accounts: 
old goobbue drop table inserted (including humus)
zitah goobbues no longer drop humus, drop dahlia instead
elder unchanged (already dropped humus)
are you still seeing issues since saturday, or is this an old report you meant to file?

**Comment by MrBeignet** [comment]
> 
> 
> this should have been resolved on saturday's patch on all accounts:
> old goobbue drop table inserted (including humus)
> zitah goobbues no longer drop humus, drop dahlia instead
> elder unchanged (already dropped humus)
> are you still seeing issues since saturday, or is this an old report you meant to file?

May be bad RNG then, we killed at least 50 Olds and a dozen Elders since the patch, but w/o any TH. We will try again and report findings !

**Comment by falzum** [comment]
Well if it does drop inside tree than sorry for making this report. I made it based on my knowledge of the mission from doing it months ago and a friend of mine complaining they couldn't get the drop in tree after hours of farming. I didn't even realize it was supposed to drop from the tree until my friend and I spoke today.

Sorry if I caused a bunch of unnecessary confusion

**Comment by 59blargedy** [comment]
no need for apology, actually went back and checked and there was an error so the old goobbue was still missing his drops. fixed for next patch. elders will drop the humus at this exact point in time.
