### ISSUE TITLE
Simurgh and Roc do not use draw-in

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#290]
They don't use draw-in at all

**Comment by panfunk** [comment]
Same with Bune

**Comment by icariumkupo** [comment]
Sim uses draw in several times in this video

https://youtu.be/h-5yEUHLT-k

It's also mentioned that he uses draw in in wiki

https://ffxiclopedia.fandom.com/wiki/Simurgh

And bg wiki

https://www.bg-wiki.com/bg/Simurgh

**Comment by Elysien** [comment]
They're indeed suppose to have it, it just isn't regional draw in -- i:e you can essentially pull them anywhere, but exceeding a certain distance from them will cause them t draw you to them.

Regional draw in is pretty rare, and limited to only the big guys. Fafnir, for example, could not be removed from the pit by any means whatsoever. It probably doesn't have that on Eden currently, but it's not something anyone has or probably would abuse, anyways.

**Comment by Oyaziiiiiii** [comment]
Guess it does. Looks like it's a really far distance from that video though which is probably why I don't remember it. Much more than the 10 yalms or w/e Kupo had.

**Comment by godmode** [comment]
This has been fixed but it will be a short distance from the mob until draw in activates until draw in is overhauled.
