### ISSUE TITLE
Dragoon Wyvern's Remove Breath priority incorrect.

### ISSUE THREAD

**Issue by Satirof** [EdenServer/community#2902]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version = 30181205_0

When a Dragoon subs a mage job, and uses a WS, the wyvern should remove negative status effects from the dragoon and party members.

Currently if both the Dragoon and a party member suffer the same status effect, the wyvern will remove it off the party member first. This is incorrect. The wyvern should always prioritise the master before anyone else (normal healing breath does this correct).

Steps:
1: Be DRG/Mage
2: Be in a party
3: Have both Dragoon master and another party member get hit by same status effect, e.g. Paralyga
4: Dragoon uses WS
5: Wyvern uses Removal Breath on Party member <-- this part incorrect, should be Master first.

**Comment by joeis78** [comment]
can confirm i noticed this behavior on Eden. party members are always prioritized currently.

**Comment by rude-jerk** [comment]
https://github.com/project-topaz/topaz/pull/1263

**Comment by rude-jerk** [comment]
Resolved in November 16, 2020 patch.
