### ISSUE TITLE
Ix'aern DRG spawn chance way too low

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#2903]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
ver 30181205_0
### Details

We killed all 16 aerns over and over for 10 hours straight with 3 parties for most of that period. 
we killed over 400 aerns total.

**Comment by perkuprightmeow** [comment]
We also did around ~110 Aern kills with no DRG pop on Sunday.

**Comment by Slamm21** [comment]
so IIRC DSP is set to 0-2 PH per room of 4 aerns.
So on average that is 1 PH per room.
I am positive this was set to 5% on retail based on common sense. I would reasonably assume SE to use TH categories for other things such this.

Ulli being very rare (1%) because there are 13 statues in his room who die quickly. Assuming a 1minute kill with a large group there, you would kill all 13 then wait 3 minutes for the first one to pop, So this would take you 121 minutes to kill them all after the 3 hour window opens.
Notice when ulli became forced pop, Diorite was set to very rare (1% without TH)
Which meant you could get a diorite every 71 minutes on average with TH4, but 212 minutes with TH0, the window was removed however.

if we assume ix'drg as rare (5%) and the average of 1 PH per room out of 4 aerns. I would think it fair to assume 5 minutes per room for a big group and 5 minutes total walking between rooms, making it 6.25 mins to kill 1 PH on average (25/4). You would have to clear 20 rooms which is 125 minutes. (2 hours and 5 minutes) That sounds perfect to me. 

**Keep in mind if you went up there in a smaller group, then kill times are significantly increased**
The absolute max average speed would be 80 minutes if you killed all as soon as they popped whereas many on retail could only clear 1 room over and over which is essentially 320 minutes, over 5 hours.

**Comment by InoUno** [comment]
> Ulli being very rare (1%) because there are 13 statues in his room who die quickly. 

Ulli wasn't a 1% pop from all statues – it had a single PH on era retail. I know this for a fact, because I used to solo pop and kill him.

**Comment by Slamm21** [comment]
yeah I'm sure that's right
the PH for ulli was likely common then (15%)
which would mean 107 minutes plus kill time, likely 2 hours total.

**Comment by Garphilius** [comment]
We have had a similar issue with Ix' aern DRG. Definitely did not camp it for 10 hours like Slamm's LS did but we did give it almost a 4 hour session and no pop. 

On another note, it seems Jailer of Temperance is also messed up. We camped three towers killing PHs for over 3 hours and nothing. Needs more testing but I feel something is wrong with the new patch on Temperance.

**Comment by slassen** [comment]
I've greatly increased the spawn rate once the issue is closed. Please continue to report either spawning too often or not enough once the patch happens after this issue is closed.
