### ISSUE TITLE
De'Vyu Headhunter not spawning

### ISSUE THREAD

**Issue by Grom1** [EdenServer/community#2904]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by KiplingFFXI** [comment]
I just got it to pop after a 15 minute respawn. Video proof: https://www.youtube.com/watch?v=0B9-G-D2DVE&feature=youtu.be

**Comment by 59blargedy** [comment]
i believe there was an issue with the mob spawning out of bounds but that no longer exists atm.
