### ISSUE TITLE
Veydal Wrasse Fish is the wrong Fish of the Day

### ISSUE THREAD

**Issue by MonkeyAce9** [EdenServer/community#2905]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Was asked to catch Veydal Wrasse fish today, this is incorrect. This is, I believe an Apprentice level fish and today's fish is meant to be a Novice level fish. Basically I believe the data for this fish is just in the wrong column and needs to be the next column over.

version 30181205_0

**Comment by Mozzy4Ever** [comment]
According to https://discordapp.com/channels/482610771126386688/692845607945109645/697866503160070164 ,(A list of the various fish and the levels they're coded as) Veydal Wrasse is a level 35 fish.

**Comment by MonkeyAce9** [comment]
Either the level of this fish is wrong or what the Fishing Guild is asking for when your asked to catch this fish is wrong, sorry but I'm standing firm on this one, there is a mistake here somewhere.

**Comment by 59blargedy** [comment]
veydal wrasse was replaced by dark bass in a recent guild points audit, so closing this ticket
