### ISSUE TITLE
Purchased Yigit Crackows yet received Pahluwan Dastanas

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#2907]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

Spend 20k points at NPC Famad to obtain Yigit Crackows, but received Pahluwan Dastanas instead.

![image](https://user-images.githubusercontent.com/37199798/83079833-f1e33200-a039-11ea-9c47-22a0bf5d06dd.png)

**Comment by KnowOne134** [comment]
Send in a gm ticket. I'll fix the issue
