### ISSUE TITLE
BLU self-destruct in Excavation Duty

### ISSUE THREAD

**Issue by Draucant** [EdenServer/community#2909]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Used the BLU spell self-destruct on the brittle rock in excavation duty. The spell was unresisted and did 1.1k damage. Brought it up in the BLU discord channel asking if that should be the case and was told it shouldn’t do that much damage.

**Comment by blinkwise** [comment]
It’s not clear that this is unintended. It’s not mentioned one way or another in era posts since using self-destruct leaves a BLU weakened for 4 mins making it not really an effective strategy for winning.

**Comment by KnowOne134** [comment]
It should not be the case and needs adjusting. Dont abuse broken mechanics by using this spell in this assault until fixed, which would be worthless when fixed anyway

**Comment by KnowOne134** [comment]
It should not be the case and needs adjusting. Dont abuse broken mechanics by using this spell in this assault until fixed, which would be worthless when fixed anyway

**Comment by Satirof** [comment]
It is unintended, https://ffxiclopedia.fandom.com/wiki/Talk:Excavation_Duty
Down that page it mentions "Tested it. Does not blow up a wall and does crap for damage. Not worth it. --Maerina 21:37, 10 January 2009 (UTC)"

I had mentioned this bug upon the release of assaults to Cygon in hope that it would get fixed before becoming public and potentially abused :/

**Comment by blinkwise** [comment]
Well don't use this spell because its illegal I guess (one post isn't evidence imo) and also because its a total crap strategy. Being weak for 4 mins is more of a DPS hit then the spells damage itself.
