### ISSUE TITLE
Unable to turn in GP items after ranking up until next item switch

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#291]
I am lvl 89 cooking.  I just ranked up to veteran.  After ranking up I checked the GP item for the day.  The item is Eel Kabob.  It says i have 4321 points left for the day.  This amount is the 2011 value from the wiki (4320).  I think it should probably be 500/3840(pre 2011).

Anyway it won't let me turn these in and i spent almost 40k gil getting these items to turn in.  Very unfortunate now that the items are useless and now inventory -1.

**Comment by gweivyth** [comment]
I'm honestly not sure, without being able to check on retail I'm not entirely certain if there is supposed to be dialogue that warns players of this or not.  Up to your discretion on keeping this open or not.  Either way, this was not a bug, the mechanic itself is working as intended.

**Comment by godmode** [comment]
Thanks!

**Comment by archfiendrubicante** [comment]
Having this issue right now on a very expensive synth.. After ranking up to Journeyman cook, the item updated to Bataquiche, after crafting a bunch of them (and paying a ton of cash) when trying to turn them in, the NPC just doesn't respond and just sits there. :(

**Comment by MGramolini** [comment]
I wanted to mention the text will also say you can turn items in after switching from one guild to another, but this is not true. Like gweivyth said the mechanic is correct.

**Comment by archfiendrubicante** [comment]
Whether the mechanic is correct or not, there should be some indication that you wont be able to turn in items after ranking up.
