### ISSUE TITLE
Tiamat is missing claim-shield mechanic.

### ISSUE THREAD

**Issue by CurzonEden** [EdenServer/community#2911]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)

### Details
Tiamat is currently the only contested HNM that does not have a claim shield mechanic.

**Comment by KiplingFFXI** [comment]
Related report here https://github.com/EdenServer/community/issues/2551
