### ISSUE TITLE
Quest - A Sentry's Tale unable to hand-in Ointment

### ISSUE THREAD

**Issue by sean-scs** [EdenServer/community#2912]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

**Steps:**
Talk to Glenne (Southern San d'Oria F-8) to receive an Ointment.
Zone to West Ronfaure and look for Aaveleon at (G-6).
Trade Ointment to Aaveleon - Unable to trade due to following message

**Dialogue**
_"Thank you for your help.  I was wondering what to do about that worm bite. Nasty buggers, those worms are."
"Actually, I have a request for you. Do you think you could take this container to my wife?"
"Ah...but it seems you're already carrying too much.  Perhaps you should lighten your load."
"Ow! Ouch! Gah... If only I'd remembered that oitment"_

At first I thought my inventory was full but I removed enough for 4 slots free but still wouldn't allow me to trade.  I suspect it's because it can't have two ointments in a players inventory at the same time.

Version: 30181205_0

**Comment by KnowOne134** [comment]
Corrected in updat 9/272020
