### ISSUE TITLE
The Quest NPC "Peddlestox" for the Quest "Beastmen Treasure (Elshimo Lowlands Region)" did not spawn on Windsday.

### ISSUE THREAD

**Issue by Rikoooooo** [EdenServer/community#2913]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The Quest NPC "Peddlestox" for the Quest "Beastmen Treasure (Elshimo Lowlands Region)" is supposed to spawn on Windsday at (H-6) in Yuhtunga Jungle but has not shown up this time. This quest is repeatable, I done it once before a couple days back without issue. But the NPC did not show up this time. Will attach a screenshot of proof and for my client version.

![Pounce_2020 05 29_231644](https://user-images.githubusercontent.com/64914008/83310150-032b6a80-a203-11ea-8232-c40323f84301.png)

**Comment by slassen** [comment]
Sometimes NPCs fail to show up and you will need to run 50' away and back. This is more commonly known with BCNM treasure chests.

**Comment by Rikoooooo** [comment]
I was actually aware of this and I might not have ran 50' away, but I did actually go into Kazham and come back. Really thought that would have made been the same solution.

Anyway, I only saw this happen once. I done the quest 4 times. Finally got the ring lol.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
