### ISSUE TITLE
The NM Vodyanoi is spawning every game night.

### ISSUE THREAD

**Issue by Rikoooooo** [EdenServer/community#2915]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

Take the ferry from either Central Landing to South Landing via Newtpool or South Landing to Central Landing via Emfea Waterway during the game hours of 20:00 to 04:00.

The NM Vodyanoi that spawns on the Phanauet Channel ferry is supposed to spawn every 12~15 hours after death, but I've killed him now each night for at least 4 nights in a row.

**Comment by Shoruto** [comment]
Related #1988

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
