### ISSUE TITLE
Wrong drops from mobs in Delkfutt's tower, 

### ISSUE THREAD

**Issue by ayther** [EdenServer/community#2917]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
version 30181205_0
### Details

attack mobs in Delkfutt's tower, includes gobs, giants, pot, dolls, etc

Seems like there is missing/incorrect drop table data on these mobs. I got a pair of 'Greaves' to drop which is not listed as an obtainable drop on the associated wiki's:
https://classicffxi.fandom.com/wiki/Lower_Delkfutt's_Tower
https://classicffxi.fandom.com/wiki/Lower_Delkfutt_Tower
https://classicffxi.fandom.com/wiki/Middle_Delkfutt%27s_Tower

![Minu_2020 05 31_211707](https://user-images.githubusercontent.com/58160592/83367757-26315800-a384-11ea-98b0-ecf5fedcf648.png)

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
