### ISSUE TITLE
Making Headlines Unable To Be Completed

### ISSUE THREAD

**Issue by Shika10** [EdenServer/community#2918]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

After following all directions in the Eden Classic FFXI Wiki, I am unable to complete the quest Making Headlines. I got all four key items by talking to all the tarutaru in Windurst and then clicked on the Mahagony door in Inner Horutoto Ruins. I received the message "You do not have COP installed on your account" but clicked the door again three times and received "The door is firmly closed" all three times. Back in Windurst, Naiko-Paneiko only says, "Work harder! Work harder! The Tarutaru Times Company can never rest! We can't afford to miss the publication deadline of our "Magic Paradise Weekly"! It's the only source of reliable news in Windurst. So work harder!" He does not complete the quest and award 560g.

version 30181205_0

**Comment by jaymantan** [comment]
I'm having the exact same issue.

**Comment by NiQ1** [comment]
same. if not properly implemented please change it so the quest cannot be flagged in the first place.

**Comment by Mozzy4Ever** [comment]
#1729

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
