### ISSUE TITLE
Tonko lasts 10 minutes

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#292]
After last update, Invisible from Tonko continues to last 10 minutes. Not sure if intended.

Also, Monomi would sweet if added. Just sayin :)

**Comment by godmode** [comment]
I totally forgot about adjusting Tonko...

**Comment by gweivyth** [comment]
Can we use this as an opportunity to talk about Monomi?  It would be a very solid addition and is from the same era as a few QoL notorious monsters we're keeping.  It would take the reliance away from people having to dual box mages.

**Comment by godmode** [comment]
Reliance? Carry oils! Lol

**Comment by Spider-Dan** [comment]
I don't know how Tonko worked prior to the change listed here, but the era-accurate behavior for Tonko: Ichi is 3 minute of invisibility every time, with a 5 minute duration for Tonko: Ni.  For reference:

https://ffxiclopedia.fandom.com/wiki/Tonko:_Ichi?oldid=310282
https://ffxiclopedia.fandom.com/wiki/Tonko:_Ni?oldid=310283

However, in the current Eden build, Tonko has a random duration (within a range) just like white magic Invisible.  This is not era-accurate and should be corrected.
