### ISSUE TITLE
Wrong spawn animation and Pop Location for Jailer of Hope

### ISSUE THREAD

**Issue by Garphilius** [EdenServer/community#2920]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently, Jailer of Hope has the same model as a regular Shark, it is small. It should be a bigger shark as can be seen in the following Youtube video. Further, Jailer of Hope is currently spawning to the right of the ??? and is not underwater. The correct pop location should be to the left of the ??? and underwater. 

Video for reference:

https://www.youtube.com/watch?v=V9xRnhdGdgA

Reproducible Steps:

1) Pop Jailer of Hope
2) Notice that it pops above water and to the right of the ???
3) Also notice the size of the Jailer is not a huge shark model as it should be.

**Comment by slassen** [comment]
I have updated the size but the spawn animation and location have not been updated.
