### ISSUE TITLE
Weapon Skill calculations

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#2921]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Putting my findings here so they do not get lost.
Modifiers are working correctly, FTP is working correctly.
Alpha is not, the formula for this should be `WSC = floor (floor((A x A%) + (B x B%)) x α)`
instead what we have now is `WSC = floor((A x A%) + (B x B%)) x α`

Here is proof
![image](https://user-images.githubusercontent.com/5552081/83479029-587bac00-a48f-11ea-858f-c331e916d6c1.png)
(88(Weapon Damage) + 17 (fstr cap) + floor(floor{151(STR) x .6)}) x .83) x 3 x 3 
=88 +17 + 74
=1611
if it didn't floor it you would get 75 and not 74 (151x0.6 =90.6)
90.6x0.83 is 75. Both have to be floored to get the correct 74 value.

To make sure this is correct, I have made a test server where PDIF is always 3 and the randomiser of 1 to 1.05 is never applied. With 100STR I got constant 1393 Kaitens.
88+17+(100x0.6x0.83)x3x3 is giving 49.8 instead of 49 if it were floored. The correct damage should be 1386.

I have fixed the code, line 91 of weaponskills.lua presently says
` local wsMods = calcParams.fSTR +
        (attacker:getStat(dsp.mod.STR) * wsParams.str_wsc + attacker:getStat(dsp.mod.DEX) * wsParams.dex_wsc +
         attacker:getStat(dsp.mod.VIT) * wsParams.vit_wsc + attacker:getStat(dsp.mod.AGI) * wsParams.agi_wsc +
         attacker:getStat(dsp.mod.INT) * wsParams.int_wsc + attacker:getStat(dsp.mod.MND) * wsParams.mnd_wsc +
         attacker:getStat(dsp.mod.CHR) * wsParams.chr_wsc) * calcParams.alpha`

It should instead say this
`local wsMods = calcParams.fSTR +
        math.floor((math.floor(attacker:getStat(dsp.mod.STR) * wsParams.str_wsc) + math.floor(attacker:getStat(dsp.mod.DEX) * wsParams.dex_wsc) +
         math.floor(attacker:getStat(dsp.mod.VIT) * wsParams.vit_wsc) + math.floor(attacker:getStat(dsp.mod.AGI) * wsParams.agi_wsc) +
         math.floor(attacker:getStat(dsp.mod.INT) * wsParams.int_wsc) + math.floor(attacker:getStat(dsp.mod.MND) * wsParams.mnd_wsc) +
         math.floor(attacker:getStat(dsp.mod.CHR) * wsParams.chr_wsc)) * calcParams.alpha)
    local mainBase = calcParams.weaponDamage[1] + wsMods + calcParams.bonusWSmods`

This is now returning 1386 as it should :)
Will update if I find anything else

**Comment by Slamm21** [comment]
Some of these may have already been corrected on Eden, but they are wrong on DSP

**Tachi:Gekko** has params.ftp100 = 1.5625 params.ftp200 = 1.88 params.ftp300 = 2.5
it should be params.ftp100 = 1.75 params.ftp200 = 2 params.ftp300 = 2.5
https://www.bg-wiki.com/index.php?title=Tachi:_Gekko&oldid=25574

**Tachi:Yukikaze** has params.ftp100 = 1.5625 params.ftp200 = 1.88 params.ftp300 = 2.5
it should be params.ftp100 = 1.75 params.ftp200 = 2 params.ftp300 = 2.5
https://www.bg-wiki.com/index.php?title=Tachi:_Yukikaze&oldid=25566

**Tachi: Kasha** has params.ftp100 = 1.56 params.ftp200 = 1.88 params.ftp300 = 2.5
it should be params.ftp100 = 1.75 params.ftp200 = 2 params.ftp300 = 2.5
https://www.bg-wiki.com/index.php?title=Tachi:_Kasha&oldid=33240

**Sturmwind** has params.atk100 = 1; params.atk200 = 2; params.atk300 = 3.5;
it should get no attack bonus
https://w.atwiki.jp/studiogobli/pages/93.html

**Steel Cyclone** has params.atk100 = 1.66; params.atk200 = 1.66; params.atk300 = 1.66;
it should be params.atk100 = 1.5; params.atk200 = 1.5; params.atk300 = 1.5;
https://w.atwiki.jp/studiogobli/pages/93.html

**Mandalic Stab**has params.atk100 = 1.66; params.atk200 = 1.66; params.atk300 = 1.66;
It should be params.atk100 = 1.75; params.atk200 = 1.75; params.atk300 = 1.75;
https://w.atwiki.jp/studiogobli/pages/93.html

**Empyreal Arrow** has params.ftp100 = 2 params.ftp200 = 2.75 params.ftp300 = 3
it should be  params.ftp100 = 1.5 params.ftp200 = 2 params.ftp300 = 2.5
https://www.bg-wiki.com/index.php?title=Empyreal_Arrow&direction=prev&oldid=204767

**Crescent Moon** has params.ftp100 = 1 params.ftp200 = 1.75 params.ftp300 = 2.5
it should be params.ftp100 = 1.5 params.ftp200 = 1.75 params.ftp300 = 2.5
https://www.bg-wiki.com/index.php?title=Crescent_Moon&direction=prev&oldid=270937

**Howling fist** has params.atk100 = 1; params.atk200 = 1; params.atk300 = 1;
it should be params.atk100 = 1.5; params.atk200 = 1.5; params.atk300 = 1.5;
https://www.bg-wiki.com/index.php?title=Howling_Fist&oldid=204739

**Blade: Chi** has params.ftp100 = 1 params.ftp200 = 1 params.ftp300 = 1
it should be params.ftp100 = 0.5 params.ftp200 = 0.75 params.ftp300 = 1
https://www.bg-wiki.com/index.php?title=Blade:_Chi&direction=next&oldid=271515
(not OOE, can see it on studio gobli link on the bg page)

**Atonement**, has params.ftp100 = 1 params.ftp200 = 1.25 params.ftp300 = 1.5
it should be 1 params.ftp200 = 1.5 params.ftp300 = 2
https://www.bg-wiki.com/index.php?title=Atonement&direction=next&oldid=380670
(Not OOE, this is the earliest information on the modifier)

**Ascetics Fury** has params.atk100 = 1; params.atk200 = 1; params.atk300 = 1;
it should be params.atk100 = 1.5; params.atk200 = 1.5; params.atk300 = 1.5;
https://w.atwiki.jp/studiogobli/pages/93.html

**Iron Tempest** has params.atk100 = 1; params.atk200 = 2; params.atk300 = 3.5;
it should be params.atk100 = 1; params.atk200 = 1.25; params.atk300 = 1.5;
https://www.bg-wiki.com/index.php?title=Iron_Tempest&direction=next&oldid=204253

**Retribution** has params.atk100 = 1; params.atk200 = 1; params.atk300 = 1;
it should be params.atk100 = 1.5; params.atk200 = 1.5; params.atk300 = 1.5;
https://w.atwiki.jp/studiogobli/pages/93.html

**Empyreal Arrow** has params.atk100 = 1; params.atk200 = 1; params.atk300 = 1;
it should be params.atk100 = 2; params.atk200 = 2; params.atk300 = 2;
https://w.atwiki.jp/studiogobli/pages/93.html

**Detonator** has params.atk100 = 1; params.atk200 = 1; params.atk300 = 1;
it should be params.atk100 = 2; params.atk200 = 2; params.atk300 = 2;
https://w.atwiki.jp/studiogobli/pages/93.html

Blade: Kamu has params.atk100 = 1; params.atk200 = 1; params.atk300 = 1;
it should be params.atk100 = 1.3125; params.atk200 = 1.3125; params.atk300 = 1.3125;
https://w.atwiki.jp/studiogobli/pages/93.html

**Comment by Slamm21** [comment]
One thing to note, is YGK should use the post 2H update values

correct value =
https://www.bg-wiki.com/index.php?title=Tachi:_Gekko&oldid=90067
https://www.bg-wiki.com/index.php?title=Tachi:_Kasha&direction=next&oldid=33240
https://www.bg-wiki.com/index.php?title=Tachi:_Yukikaze&direction=next&oldid=25566

before 2h update value=
https://www.bg-wiki.com/index.php?title=Tachi:_Gekko&direction=prev&oldid=90067
https://www.bg-wiki.com/index.php?title=Tachi:_Kasha&direction=prev&oldid=90069
https://www.bg-wiki.com/index.php?title=Tachi:_Yukikaze&oldid=25566

**Comment by VirtuosusFFXI** [comment]
**Rampage** on DSP has params.crit100 = 0.10 params.crit200 = 0.30 params.crit300 = 0.50.
Conflicting results on what the actual modifiers should be. Read below.

FFXIclopedia in 2007 has it at 0/20/40:
https://ffxiclopedia.fandom.com/wiki/Rampage?oldid=277031

FFXIclopedia today has it at 10/30/50: 
https://ffxiclopedia.fandom.com/wiki/Rampage

BGwiki today has it at 0/20/40:
https://www.bg-wiki.com/bg/Rampage

There is also this thread and post on BG forums in 2007:
https://www.bluegartr.com/threads/44084-dex-crit-relation-WS-crits-WS-gorgets-discussion?p=1517773#post1517773


Most "Chance of critical varies with TP" weapon skills will likely have to be audited, where possible.

**Comment by 59blargedy** [comment]
resolved in november 23rd update
