### ISSUE TITLE
Poroggos are casting Death as they please

### ISSUE THREAD

**Issue by jonip9** [EdenServer/community#2924]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Poroggos in Mamook cast Death without activating Providence first. Screenshot from start of the fight to the end. Edit: They might actually cast other Providence spells as well as I have seen them cast and lose the effect of Haste.
https://ffxiclopedia.fandom.com/wiki/Category:Poroggos
![Ratix_2020 06 04_190456](https://user-images.githubusercontent.com/38398785/83782186-225d4880-a698-11ea-8117-f6582c64ed3a.png)

ver 30181205_0

**Comment by DrfistMD** [comment]
Can confirm when I was out there learning Magic Hammer, all the Poroggos seemed to be under Providence from the moment they spawned.  They also seemed to only cast Providence spells and did not cast any of their normal high level BLM spells.

**Comment by KnowOne134** [comment]
corrected 1/25/2021 update
