### ISSUE TITLE
RSE Sachet has potential to drop for wrong race

### ISSUE THREAD

**Issue by freddiepines** [EdenServer/community#2929]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Client version 30181205_0.

During male Elvaan RSE week I popped Aroma Fly in Gusgen Mines as male Elvaan and received Civet Sachet (Mithran RSE) as a drop:

![image](https://user-images.githubusercontent.com/50085658/83892890-42831b00-a71d-11ea-9f35-55d64c2e564a.png)

It was always my understanding that this should be impossible - one race should never receive another's RSE.  Kill was during the first game day of the week's window for M. Elvaan.

Probably an edge case of some type, have never seen this before and subsequent kills led to dropping the proper sachet for M. Elvaan.  Will be popping / killing for a 2nd sachet (hopefully) and will report if this occurs again.

Reproducible by spawning & killing Aroma Fly/Crawler/Leech and recording drops.

**Comment by freddiepines** [comment]
Addendum - also looks like the respawn time is bugged for one of the ??? point in Gusgen, same point that spawned the Fly with the bugged drop earlier.

??? @ F-7 on map 3 spawned between 0 and 10 minutes from last TOD.

**Comment by greyenvy** [comment]
Problem still persists.  During Male Elvaan week I got the Female RSE sachet.
![Ashton_2020 06 23_102046](https://user-images.githubusercontent.com/48332558/85755389-e5570580-b6db-11ea-8a38-abaf0d050c80.png)

**Comment by knifepartner** [comment]
![ffxiAromaLeechScreenshot](https://user-images.githubusercontent.com/66795519/86216770-8d415880-bb4c-11ea-8c61-9ec4d4464972.JPG)
Problem persists for me as well. Defeated the Aroma Leech in Ordelles Caves during M Elvaan week I received the Hume M RSE Sachet.

**Comment by Gantofu** [comment]
![image](https://user-images.githubusercontent.com/59887688/106338229-1ede8900-6248-11eb-8db0-f8b2d4c0789a.png)
Defeated Aroma Crawler in Maze of Shakhrami during F Elvaan week and received Hume F RSE ammo

**Comment by rude-jerk** [comment]
Resolved in update on October 4, 2021

**Comment by Blazebleu** [comment]
![Blazeblue_2022 09 18_123418](https://user-images.githubusercontent.com/79831186/190919042-975a10e0-2dba-49c5-967b-39920ab7d7f5.png)

went 1/5 on aroma leech in ordelles today.. when it finally dropped it was Galka ammo XD
