### ISSUE TITLE
Claim loss from SMN pets

### ISSUE THREAD

**Issue by Umarusuzy** [EdenServer/community#293]
Summoner pets frequently takes claim from other parties when they automatically engage/auto-attack as a result of pulling hate with cure spells.  This does not happen while the pet is currently engaged with another mob.  But once that mob is dead, they will go after the mob with SMN hate.  I would think that this could be the case for BST pets as well but I don't have a BST to test it.

**Comment by Mikokiko** [comment]
Confirm this still happen
