### ISSUE TITLE
Learning Bluemage spell Uppercut without goobbue useing the ability 

### ISSUE THREAD

**Issue by Segepor** [EdenServer/community#2930]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
I was Fighting Goobbue Farmers in Rolenberry Fields to learn Uppercut. The goobbue i was fighting
used Antiphase Blank Gaze and Antiphase Again. I killed the goobbue and learned Uppercut.
![Segepor_2020 06 05_114956](https://user-images.githubusercontent.com/62173744/83899242-1cae4400-a726-11ea-84f1-141f4d0e3b4f.png)
![Segepor_2020 06 05_115009](https://user-images.githubusercontent.com/62173744/83899269-2a63c980-a726-11ea-8407-8b73b4695090.png)
![Segepor_2020 06 05_115018](https://user-images.githubusercontent.com/62173744/83899281-30f24100-a726-11ea-80b9-a6ee19f3cfac.png)
![Segepor_2020 06 05_115024](https://user-images.githubusercontent.com/62173744/83899289-33549b00-a726-11ea-9887-0637f573b372.png)

Client Version 30191205_0

**Comment by Dibision** [comment]
![Desktop Screenshot 2020 12 08 - 09 33 24 55](https://user-images.githubusercontent.com/75684098/101500289-45fd9600-393c-11eb-9f71-30868a767ca1.png)
![Desktop Screenshot 2020 12 08 - 09 33 33 77](https://user-images.githubusercontent.com/75684098/101500292-472ec300-393c-11eb-8c3e-50c992caf933.png)

I too learned a spell by the mob using a different one. It used Whirl Claws and I learned Foot Kick

**Comment by falzum** [comment]
I think what's happening is the mob used those moves on someone else, then that person died or warped, without killing the mob. So it was technically 'used'. There-by allowing you to learn it.

**Comment by KnowOne134** [comment]
Just talking to jerk about this and your right

**Comment by rude-jerk** [comment]
Resolved in patch on December 14, 2020.
