### ISSUE TITLE
Double Attack can proc on ranged weapon skills (and likely ranged attacks)

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#2933]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
this bug is definitely on dsp, as I've noticed it during my weapon skill testing. If this hasn't been noticed before it will be on Eden too.

testing weapon skills on level 1 bunnies I found sometimes damage spiked and I got more tp return whenever I was /war

**Comment by 59blargedy** [comment]
this was solved by pdif changes
