### ISSUE TITLE
Attributes Merit Category needs auditing

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#2934]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

At one point it was possible to get more than 5 points total in the Attributes merit category. IE: 5 STR merits and 5 DEX merits at the same time. This was changed at some point to no longer be possible, but players who had already gone past the category cap did not get their additional merits removed.

**Comment by GalkaZajin** [comment]
Big if true

**Comment by Garphilius** [comment]
Whaaaaaaat?

**Comment by Garphilius** [comment]
Do you have proof of someone with 10 points merited in Attributes category?

**Comment by VirtuosusFFXI** [comment]
If I had concrete evidence I would have included it. All I have is word of mouth that people have kept their extra merits, which is why I requested an audit. Anyone who may have these extra merits is free to step forward about it.

**Comment by Relic3** [comment]
I was able to be prompted to add a 6th merit a while ago but didn't go forward with it as I didn't know if it was gonna be permanent. Recently fully merited on the jobs I play so I went to try again and was unable to even click on it anymore.

**Comment by Rikoooooo** [comment]
If you need a source for what the stats should be at 75 you can use this site: [http://ffxi-stat-calc.sourceforge.net/cgi-bin/ffxistats.cgi](url)

For anyone that wishes to check.

**Comment by 59blargedy** [comment]
Validated that this is not an issue, and no players have more than 5 upgrades across the attributes category.
