### ISSUE TITLE
Call to Audit Baronet Romwe's Loot Table / Drop Rate

### ISSUE THREAD

**Issue by Garphilius** [EdenServer/community#2935]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I have now killed Baronet Romwe 12 times. 0/12 on the Demon's Axe.

After looking at Wiki and ffxidb, there seems to be a huge discrepancy between the two when it comes to drop rates on the axe. I am wondering what percentage is the drop rate set on the axe in Eden and is it correct? Also, every time I have killed him, only Demon Horn has dropped.

https://ffxiclopedia.fandom.com/wiki/Baronet_Romwe

http://ffxidb.com/zones/162/baronet-romwe

**Comment by Garphilius** [comment]
Alright, I am up to 24 kills on this NM, and still no Axe. Talked with a person that has killed him 50+ times on Nasomi and no Axe. I am wondering if Eden just has the information on this NM pulled from DSP days and has never really looked at this NM as not many people care about the Axe.

Asking to please check this NM.

**Comment by 59blargedy** [comment]
This is set to a 4, uncommon
10% | 12% | 15% | 16.50% | 18%

Since wiki and ffxidb have horrible sample sizes and vastly differ, it's difficult to change, but the axe does exist and is tied to that mob. Will leave ticket open if anyone wants to get more of a sample size in retail.

**Comment by SleazyFFXI** [comment]
I've killed this NM 10+ times in the last 3 days and I'm 0/10+,   I have seen Demon Skull though,   Gar's 24/0,   starting to think the axe isn't in it's loot pool.

**Comment by Garphilius** [comment]
I killed him a few more times and still nothing. Godmode claims the axe is in the loot pool but I gave up since after 30+ kills it just did not seem worth it for a short lived BiS Gaxe at birds. 

Glad to see other people camping it and trying to get axe/posting on here with more sample sizes.

**Comment by bkesecker** [comment]
The mob group has the correct drop ID and the drop ID includes the item ID for the Demon's Axe.  The axe has dropped for players in the past.

**Comment by SleazyFFXI** [comment]
It exists I just got the drop,  somewhere around 1/15
