### ISSUE TITLE
Enmity Merits not functioning

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2938]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

https://github.com/DarkstarProject/darkstar/blob/2eef5d2f8010d00efccd352b30d9dc05dd487146/src/map/enmity_container.cpp line 101 (function for CalculateEnmityBonus) has this:

`float CEnmityContainer::CalculateEnmityBonus(CBattleEntity* PEntity)
{
    int enmityBonus = PEntity->getMod(Mod::ENMITY);

    if (auto PChar = dynamic_cast<CCharEntity*>(PEntity))
    {
        enmityBonus += PChar->PMeritPoints->GetMeritValue(MERIT_ENMITY_INCREASE, PChar) - PChar->PMeritPoints->GetMeritValue(MERIT_ENMITY_DECREASE, PChar);

        if (PChar->StatusEffectContainer->HasStatusEffect(EFFECT_SOULEATER))
        {
            enmityBonus -= PChar->PMeritPoints->GetMeritValue(MERIT_MUTED_SOUL, PChar);
        }
    }

    float bonus = (100.f + std::clamp(enmityBonus, -50, 100)) / 100.f;

    return bonus;
}`
Looks like it ties the increase or decrease in merits to the Enmity mod (27)
Hopped on the test server to use !getmod. Was naked and did !getmod 27, returned 0. Put on PLD body (+2 Enmity) and !getmod 27 returned 2. Put points into "Enmity Increase" and at each level, checked with !getmod 27 and enmity stayed at 2 for each increase. Did the same with "Enmity Decrease" and still was stuck at 2. 

EDIT - Stupid github not putting everything into the code backticks even though there's no other ` in the code.

**Comment by Kurtalicious** [comment]
Rip my wasted merits ;;

**Comment by slassen** [comment]
This is not the code that we have but this code would seem to function properly if it was. Are you concerned they aren’t working because the getmod is not returning more than 0 when you have enmity merits?

**Comment by Mozzy4Ever** [comment]
Correct. I can try and verify in other ways but it's iffy... whereas having a command I can run to check the values that should be changed is a more concrete

**Comment by 59blargedy** [comment]
validated that enmity merits add ve/ce. it just doesnt add it as a checkable mod.

**Comment by Mozzy4Ever** [comment]
:reee:
