### ISSUE TITLE
Aquarius' spawn timer is incorrect - respawns every 20-30min

### ISSUE THREAD

**Issue by Kross22** [EdenServer/community#2939]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

I discovered this bug while skilling up in The Boyhada Tree today, Aquarius popped and we killed, then repopped 20-30min later.  It's supposed to be a 2 hours spawn

Game Version: 30181205_0

**Comment by E5una** [comment]
Wiki seems to indicate otherwise, saying "Lottery Spawn from the Robber Crabs around (H-9) on the first map approximately every 2 to 6 hours (Can instantly repop; see testimonials)."

**Comment by greyenvy** [comment]
This is normal behavior.  Should close this report.

**Comment by 59blargedy** [comment]
have to depend on wiki in the absence of collected data, closing with the assumption that current behavior is correct.
