### ISSUE TITLE
Dagourmache Behavior Incorrect

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/community#2941]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Dagourmache problems:
- is not summoning a wyvern
- his avatar should be fenrir not carby
- when he uses astral flow it does nothing (and is only used once)
- did not attempt single target charm

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
