### ISSUE TITLE
Soultrapper cuts off names

### ISSUE THREAD

**Issue by slassen** [EdenServer/community#2942]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 13081205_0

The soultrapper should be able to list names of up to 20 characters. After that I'm uncertain if it uses an ellipsis or just cuts off the name. However, currently it cuts off the last letter of each name. Even if it is less than 20 characters.

To reproduce get a soultrapper and blank soul plate. Take a picture of a short named mob and view the imprinted soul plate.

**Comment by KnowOne134** [comment]
Has been corrected
