### ISSUE TITLE
Moghouse Homepoint in Whitegate not functioning

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#2945]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [30181205_0 ] I have provided my client version in the details. (type /ver into your game window)

### Details

Whitegate moghouse is not currently setting players homepoint if selected. The option is there, but it doesn't actually move your homepoint if you select it.

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
