### ISSUE TITLE
Vodyanoi not 12-15 hours

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2948]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

Took boat from south landing along Emfea Waterway and each time Vodyanoi was up

**Comment by Rikoooooo** [comment]
Guess you didn't actually search for existing issues lol. Yes, he pops every night. I posted this issue sometime last week or so.

**Comment by Mozzy4Ever** [comment]
Hah, somehow nothing shows up. Guessing I misstyped when I searched.
