### ISSUE TITLE
Pets & Teleporter Interactions

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2949]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently wyverns & automatons are lost in most cases when a teleport places you in a downloading data screen (i.e. warp spells, outpost warps, red teleporters in sea, Delkfutt's Tower teleporters). These pets should persist and shouldn't be lost unless you change your job / sub-job / sync below your current level / ride a chocobo. For example if you had an automaton summoned and used an outpost warp to go back to town and went to another area either by using the outpost warp NPC or a crag teleport, your automaton should be automatically resummoned without having to reuse activate.

With the latest update to pet pathing, all types of pets no longer travel together with their owners when using non-downloading data teleporters (i.e. telepads in sky, Riverne's unstable displacements). They will walk until they reach you again which can either be a short or long wait depending on how they choose to path back.

version 30181205_0

**Comment by FariskaEden** [comment]
Note: second half of this report should be resolved but the first half is still an issue.

**Comment by KnowOne134** [comment]
Can we open another issue report just for that. It's an old time core issue and not in the scope of the fix for portal use that was introduced with pet pathing

**Comment by FariskaEden** [comment]
Sure I'll make one.
