### ISSUE TITLE
Monster death bug/Two Monsters claimed

### ISSUE THREAD

**Issue by TanstaaflEden** [EdenServer/community#295]
I used Combo to kill a Ding Bats in South Gustaberg. Its nameplate stayed red after death and its HP showed as 100% again.  A second Ding Bats nearby also had its nameplate turn red, but it remained non-aggressive towards me.  Eventually Ding Bats #1's body faded away and it respawned immediately with its nameplate still red, but non-aggressive towards me (and it was invisible).

The Ding Bats in this area had been spawning all throughout the daytime hours, so perhaps it is related to that.

**Comment by TanstaaflEden** [comment]
![tanstaafl_2018 11 07_123721](https://user-images.githubusercontent.com/44847749/48153506-01e6c580-e28c-11e8-943a-41a4090e160f.png)

**Comment by godmode** [comment]
Was unable to reproduce this. If someone else sees this again please comment.
