### ISSUE TITLE
Genbu's Movement Speed

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2950]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Genbu should have decreased movement speed instead of the current normal movement speed it has. Looks like its speed should be as if it's permanently gravity'd since when you have normal movement speed you can outrun it. 

https://www.youtube.com/watch?v=AgIC5thdlPw 
https://www.youtube.com/watch?v=tJqwiKfjYJI
https://ffxiclopedia.fandom.com/wiki/Genbu

version 30181205_0

**Comment by Balrahn** [comment]
No mobs on this server can be outrun unless you make it get stuck. This is an issue with all mobs.

**Comment by 59blargedy** [comment]
resolved december 7 update
