### ISSUE TITLE
Sky: Teleporters From God Islands When God is Up

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2952]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Much like in #2078, after a god is popped in sky the teleporter that leads back to the main island from the god's island should become disabled until the god is dead/despawns.

Currently you are able to leave a god's island while a fight is in process.

version 30181205_0

**Comment by KnowOne134** [comment]
I would need retail capture of the behavior. There is 0 code that controls that portal. It is completely handled by the client unlike all the other portals

**Comment by FariskaEden** [comment]
Just investigated this on retail, turns out you can leave the island when fighting a sky god. So either it was changed at some point or whoever told me about this misremembered.
![image](https://user-images.githubusercontent.com/46270382/84041010-5030de80-a971-11ea-9e01-3ba0e002b8ef.png)
Though one thing of note was that the Seiryu did not follow me off the island which sky gods can currently do on Eden (related to #2307). I had to wait a few minutes for it to despawn since the teleporter that leads back up was disabled.

**Comment by KnowOne134** [comment]
more than likely it has a roam leash and cant leave the island, can open anothe rissue reguarding that

**Comment by Balrahn** [comment]
Can't say I ever tried using the porter during a sky god still being up. However the porter leading up to the island should be closed while the god is up. Perhaps that is what you somewhat remembered?
