### ISSUE TITLE
Convergence is not increasing 1,000 needles damage

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2954]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Convergence should grant bonus damage to 1,000 needles based on how many merit points you have invested in it. I have 3 merits in it, so it should do 1,150 damage.

https://ffxiclopedia.fandom.com/wiki/1000_Needles

"Damage and accuracy are enhanced directly by the Merit job ability Convergence, giving 5 Magic Accuracy and 5% additional damage per merit."

![image](https://user-images.githubusercontent.com/13668758/84045222-8ae94580-a976-11ea-9536-92c0d80dd407.png)

**Comment by 59blargedy** [comment]
resolved 11/2 update
