### ISSUE TITLE
3 hours farming ro’maeve water with TH4 and no drop

### ISSUE THREAD

**Issue by Magnum1965** [EdenServer/community#2957]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Party setup: 
WHM/BLM
THF/NIN
DRK/NIN
SMN/WHM
Moon: Waxing Crescent 38%
Started farming 7:00pm gmt, finished farming 10:00pm gmt, THF was TH4, everything but water dropped. I think the TH settings are too low for this item.

**Comment by Kurtalicious** [comment]
The drop rate is set to rare which is 8% with th4.  You got unlucky my friend.

**Comment by ReeceR09** [comment]
@Kurtalicious Nah - This is just for tonight. Collectively we have spent the good part of 10-12hours now trying to obtain a water to pop Olla without any drop at all.

**Comment by Kurtalicious** [comment]
Please see the link below. It is a current list of items that have had the drop rates audited in the recent past. Water was changed live during Seige’s stream I watched him change it. The drop rate is set correctly at category 3 which is rare.  That doesn’t mean that something else might not be occurring with rng or the loot pool bugging. 

https://docs.google.com/spreadsheets/d/12d7uSwVhFNwPrIIuV6OAo-h6iravdIDYJQcz_x4IdE0/edit

**Comment by bkesecker** [comment]
The rate is accurate to era.  Closing.
