### ISSUE TITLE
Dynamis San d'Oria misc bugs

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#296]
Voidstreaker Butchnotch should give 30 minute time extension upon being defeated. He currently gives 9 hours. 

On two separate instances, upon attacking a statue with summoner monsters inside, they spawn and immediately astral flow. Bass was one shot by Tidal Flow and Searing Light tonight just minding his own business and pulling. (I know the specific statues attached but not the mob IDs of the culprit summoners)

**Comment by Treble011** [comment]
The mega boss of the zone repeatedly spawns the notorious monsters and statues attached to him if you kill them and then leave him up for a few minutes unattended.

Upon entering today on Bass, I zoned into Southern San d'Oria instead of Dynamis, had to run back to the trail markings and trade hourglass again; entered fine after but had that stupid 15 minute weakness.

More incidents of monsters coming out of their statues with two hours already active (RDMs and THFs today) and reusing their two hours if they go unclaimed.

**Comment by godmode** [comment]
For weakness, that was how it was during era retail if you reentered the same instance. Just without the bugs.

**Comment by Treble011** [comment]
Well, I shouldn't have been 'reentering', it was just a bug. Still obnoxious.

**Comment by Oyaziiiiiii** [comment]
Just an extra note, it's not just the SMN mobs that are 2hring immediately after they pop. We've now also seen RDMs use chainspell and THFs use perfect dodge immediately.

**Comment by Treble011** [comment]
Multiple zones too, not just in Sandy. When I wrote this, I hadn't noticed it elsewhere.
