### ISSUE TITLE
Zeni gain inconsistencies / reports

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#2964]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Yesterday was Aquans-Crabs.  Highest reported return from normal monsters was 70 zeni from EM-T crab mosnters (Steel shells and mamook crabs).
Received 90 Zeni from plates taken from a 5% Aquarius (Crab NM).

Today is Aquans-Pugil.  Still received 90 Zeni from Aquarius.  This makes sense since Family doesnt matter, only 'Aquans' are implemented right now.

What doesn't make sense is:

Plates obtained from a 1% Northern Piranu only returned 70 zeni.
https://ffxiclopedia.fandom.com/wiki/Northern_Piranu

compared to aquarius:
https://ffxiclopedia.fandom.com/wiki/Aquarius

The Piranu is a substantially higher lvl NM than Aquarius and for some reason produced fewer Zeni while also at a lower hp percent.

I'm creating this bug report as a place for issues to be posted as they come up so they are easily found by the developers while they refine the system.

**Comment by E5una** [comment]
The issue here is that Northern Piranu is not coded as an NM on Eden so you don't get the bonus points. I was also going to report the same thing :)

**Comment by GalkaZajin** [comment]
Tried 1% Aw'euvhi (Limbus KI Flower NM) which was reported to be 65ish and only received 47 zeni.

Tried a 1% Dahak which is supposed to be near 100 zeni and only received 37 zeni.

**Comment by roriffxi** [comment]
52 points from 5% Khim point blank while it was the recommended fauna.

**Comment by slassen** [comment]
It may have been left out of the patch notes but recommended fauna is completely unimplemented currently. Only current subject of interest ecosystems, and NMs provide bonuses.

**Comment by 59blargedy** [comment]
resolved with znm implementation
