### ISSUE TITLE
Skill discrepancy between log and menu

### ISSUE THREAD

**Issue by Tollbee** [EdenServer/community#2966]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
version: 30181205_0

As I skill up, the log claims I skill up enhancing or healing by x amount. When it levels it gives the level up status. However, the level the log says and what I can verify in the menu are different - the log will say "skill 132" and the menu will say "142", for example. The menu is about 10 points higher for my blue capped magic skills. 

This only appears to affect my magic and those above 100 thus far. 

I am a level 60RDM, name Tollbee.

**Comment by rwaffle** [comment]
Do you have on equipment with +skill on it? This will show up in the combat skill menu, but not the chat log.

**Comment by Tollbee** [comment]
Oh my gosh, thank you! Sorry for such a blunder!
