### ISSUE TITLE
Stat Bonus Etude songs not working correctly.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#2968]
### Checklist

- [/ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ /] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ /] I have provided my client version in the details. (type /ver into your game window)

### Details
All of the stat bonus etude songs for Bard... vital, herculean, sage, swift, logical, bewitching, uncanny...ect only cast on yourself when they are supposed to be an AoE that is centered on yourself. Right now it only hits the caster as a single target song and will not hit party members.

Version 30181205_0

**Comment by Serephim** [comment]
Yes I am using the Eden client. I can only target myself with the etude spells, not party members.

**Comment by KnowOne134** [comment]
Maybe your missing a dat. Can download and paste them all from 
https://github.com/KnowOne134/Dats-TOAU-Era

**Comment by Serephim** [comment]
Not really all that familiar with how to mess with dats. How do I download them?

**Comment by Serephim** [comment]
Do I just have to replace all the dats?

**Comment by greyenvy** [comment]
> Do I just have to replace all the dats? I don't know which is which.

Yeah should just be overwrite with those dats and you're good to go.

**Comment by 59blargedy** [comment]
dat replacement will resolve
