### ISSUE TITLE
Slave globes taking 0 physical damage

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#297]
Fought Mother Globe yesterday and the slave globes were taking 0 physical damage.

Another minor thing is they kinda just roam freely in the room when idle instead of following MG around. 

https://www.youtube.com/watch?v=_ZCoYzFp-_I&t=89s (Video of slave taking melee damage)

**Comment by godmode** [comment]
Wasn’t intentional. Not sure how this happened.

**Comment by jmcmorris** [comment]
I just tested this and it seems to be working. Please report again if you encounter it again. Thanks!

**Comment by godmode** [comment]
Oops forgot to close this when it was fixed
