### ISSUE TITLE
Soultrapper using incorrect animation.

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#2970]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

I'm sure you guys are aware, but the Soultrapper (And 2000? haven't tried) is currently using the incorrect animation.  It should look like this: https://youtu.be/1HHrwPVnyLY?t=112

Super minor in the grand scheme of things, but it adds a lot of flavor.

**Comment by 59blargedy** [comment]
resolved upon znm implementation
