### ISSUE TITLE
Bluestreak Gyugyuroon possible drop rate bugged?

### ISSUE THREAD

**Issue by andrewj3191** [EdenServer/community#2974]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I wanted to see if the drop rates for Bluestreak Gygyuroon could be looked at for possible issues.  I've been hunting it for about a week and a half.  Currently, I have killed it 8 times, and neither Peacemaker or Qiqirn Collar has dropped once.  It's hard to find exact % data on the drop rates, but reading through forums, ffxidb, etc. would lead me to believe the collar should be 20-30%, and the gun above 50%.

**Comment by mlandrum22** [comment]
I've killed this a bunch of time, think it's set at 10% and probably because FFXIDB has a total of 5 data points.

http://www.ffxidb.com/zones/68/bluestreak-gyugyuroon

**Comment by 59blargedy** [comment]
could you link the forum posts you mentioned, @andrewj3191 ? would be helpful

**Comment by greyenvy** [comment]
I have been camping this NM as well the past two days.  According to DSP files, there should be two Placeholders, but I can only find one, the second one on this list:

        BLUESTREAK_GYUGYUROON_PH =
        {
            [17055941] = 17056156, -- -221.7 13.762 -346.83
            [17055942] = 17056156, -- -219 14.003 -364.83
        },

The second one pops in the hall at I-9.  The other PH I cannot find whatsoever and the coordinates even appear to be inside a wall?  I have hunted a ton of NMs on Eden and they have basically been exactly what DSP files say but this one seems weird to me.  Please look into it and make sure it has two PH?  I think it should even have more than this according to some older posts: https://www.bluegartr.com/threads/48347-Bluestreak-Gyugyuroon?p=1966607&viewfull=1#post1966607

**Comment by 59blargedy** [comment]
updated ph and how it spawns in October 9, 2024 update. checking out forum posts and what little data there is drop rate seems fine.
