### ISSUE TITLE
Dropping Perpetual Hourglass Copies Will Eject Character

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/community#2976]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

If any Perpetual Hourglass from any Dynamis is dropped (even a valid copy), and the character is presently in an active Dynamis, that character will be ejected from Dynamis.  Unsure if this is retail accurate, but my recollection, if players accidentally created more hourglasses than needed for entry, and then later dropped hourglasses during Dynamis, no ejection occurred, only when no more valid hourglasses were in possession.

**Comment by Slamm21** [comment]
yeah it's definitely not retail accurate. If someone was late for dynamis and you had no glass mule outside you had to warp out and run back to trade them and get back in.

**Comment by slassen** [comment]
I'm surprised this issue wasn't filed earlier. Thanks for filing. It's not retail accurate but for performance reasons I didn't make it accurate until I can think of something that will work fast and have time to implement it. This will be the same with Einherjar lamps as well.

**Comment by 59blargedy** [comment]
this was resolved in the august 2023 update

**Comment by Steam-arch** [comment]
dropping last glass and afterwardsa buying one from bazzaar doesnt interrupt being ejected from dynamis (you can essentially exit with a glass like this), intended?

**Comment by DeuceFFXI** [comment]
Intended or not, I think it would be hard to prove how SE handled that sort of scenario in era.  Would probably need to search some era forum posts on Dynamis to get an answer on that.  It certainly seems like a way to circumvent the mechanic that SE may not have coded to prevent.
