### ISSUE TITLE
Tonberry Pursuer do not Triple Attack

### ISSUE THREAD

**Issue by marlinla** [EdenServer/community#2978]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

Tonberry Pursuer do not Triple Attack as THF mobs. Particularly the PH for Sozu Rogberry.

**Comment by 59blargedy** [comment]
Resolved in December 1st patch
