### ISSUE TITLE
Learned Healing Breeze off of Berserk

### ISSUE THREAD

**Issue by GiichiHiro** [EdenServer/community#2981]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

Fought a Dhamel, it used berserk, when I killed it, I learned healing breeze.
I can't reproduce personally, due to the nature of blue magic, but screenshot:

![Giichi_2020 06 12_210633](https://user-images.githubusercontent.com/66037286/84554997-fb82c000-acf0-11ea-8853-ed5aa47ef54c.png)

**Comment by Crabdance9** [comment]
Similar issue, I was able to learn Death Scissor when a scorpion never used the move.

![Crabdance_2020 06 27_105111](https://user-images.githubusercontent.com/48329462/85928830-e8313200-b864-11ea-9f42-e92c035b6790.png)

**Comment by rude-jerk** [comment]
Resolved in patch on December 14, 2020.
