### ISSUE TITLE
BRD Instrument Storm Fife not functional

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#2983]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

The BRD Instrument Storm Fife is not functional. It should provide +1 tick to Ballads, yet no such increase was observed during Ilrusi Atoll Assault.

https://ffxiclopedia.fandom.com/wiki/Storm_Fife

You may also wish to check the effect should work in Salvage as well.

1. Be BRD 50+
2. Equip Storm Fife
3. Enter assault or salvage area
4. Cast Ballad and/or Ballad 2
5. Observe no increase in ballad effect

Thanks.

**Comment by KnowOne134** [comment]
has been fixed
