### ISSUE TITLE
Cannot perform action on specified target.

### ISSUE THREAD

**Issue by AlfWaji** [EdenServer/community#2984]
### Checklist

- [/ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/ ] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0
-Cannot use shadows (cannot perform that action on the specified target)
-Cannot use toolbag: shihei ("")
-Cannot /logout or /shutdown
First time experiencing this. Just killing ahrimen in castle zvahl keep. Casted ustu, went through a teleporter, fought an ahriman, could not recast utsu during the fight. Tried to logout to fix it (couldn't log). Tried using a consumable (toolbag: shihei) only because it's an action on myself, and I was curious if it would let me.

**Comment by AlfWaji** [comment]
Zoning fixes the issue

**Comment by AlfWaji** [comment]
It happened again, it seems to be the teleporters.

**Comment by Mozzy4Ever** [comment]
Iirc, happens if a mob tried to act on you while the server was trying to move you (like teleporting). Have seen it happen when leaving a BCNM as well.

**Comment by AlfWaji** [comment]
Hmm, well i was completely free of agro both times it has happened. I have use these teleporters probably a couple thousand times on Eden in the past (farming) and haven't ran into the issue until recently.

**Comment by AlfWaji** [comment]
Allthough, the also recent issue (in my experience) of becoming stuck in a black screen when using the teleporters seems to have been resolved. It hasnt happened to me recently, anyways.

**Comment by AlfWaji** [comment]
My last statement is inaccurate. It's not a black screen, it's my character going invisible (except for name and Linkpearl) and unable to do anything when using a teleporter, and the issue still exists. Only solution i have found is force closing the game.

**Comment by 59blargedy** [comment]
should be resolved with October 11th update
