### ISSUE TITLE
Pets Lost in Downloading Data Warps / Teleporters

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2985]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently pets are lost in most cases when a teleport places you in a downloading data screen (i.e. warp spells, outpost warps, red teleporters in sea, Delkfutt's Tower teleporters). These pets should persist and shouldn't be lost unless you change your job / sub-job / sync below your current level / ride a chocobo. For example if you had an automaton summoned and used an outpost warp to go back to town and went to another area either by using the outpost warp NPC or a crag teleport, your automaton should be automatically resummoned without having to reuse activate.

version 30181205_0

**Comment by tigo9** [comment]
Just a note that this also affects npc fellows

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
