### ISSUE TITLE
Mijin Gakure is causing exp loss

### ISSUE THREAD

**Issue by maldra** [EdenServer/community#2986]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
I used Mijin Gakure and de-lvled. There is not supposed to be any exp loss when using this ability.

**Comment by slassen** [comment]
Did this just start happening or did you notice after the patch? Can anyone else comment?

**Comment by maldra** [comment]
Yes, it only started happening after the patch today. Also, I noticed the weakened part isn’t working properly either. I did the nin 2 hr, HPed and lost exp. i later died on thief, got a raise 3 and was not weakened.

**Comment by roriffxi** [comment]
Yeah, just noticed this myself, it wasn't happening yesterday.

**Comment by bkesecker** [comment]
Should be resolved.  Please reopen if not.
