### ISSUE TITLE
my staging point got erased

### ISSUE THREAD

**Issue by alioh7** [EdenServer/community#2987]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

me and my brother were heading to mamool ja staging point to do ISNM and cant use the runic portal as if i dont have it, so i went and got a assault order and got this message. i know for a fact that i have all staging points obtained months ago.
![Aliohxtrm_2020 06 14_211635](https://user-images.githubusercontent.com/55878362/84600823-e5a60400-ae84-11ea-82a4-c5fcc02b6670.png)

**Comment by Mikokiko** [comment]
They aren't erased, all NPC show sanctume total atm

If you check currency, your total should be there, but atm if you do any assault they pop under sanctum.

https://github.com/EdenServer/community/issues/2988

**Comment by Mikokiko** [comment]
Prolly somewhat related to this : https://github.com/EdenServer/community/issues/2988

**Comment by bkesecker** [comment]
Should be resolved.  Please reopen if not.
