### ISSUE TITLE
Assault point added to wrong instance

### ISSUE THREAD

**Issue by Mikokiko** [EdenServer/community#2988]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

We did lebros cavern, the point got addedd to sanctum, 

We can see it in currency.

When we talk to the NPC, they are all using the value of sanctum for point exchanging reward.

![Kiko_2020 06 14_153238](https://user-images.githubusercontent.com/43910014/84602539-19b60080-ae56-11ea-85f5-068564aa0034.png)
![Kiko_2020 06 14_154803](https://user-images.githubusercontent.com/43910014/84602580-7ca79780-ae56-11ea-8fac-c81852cddb44.png)

**Comment by tacbox3** [comment]
![Contrabanned_2020 06 14_133522](https://user-images.githubusercontent.com/48967119/84602588-8d580d80-ae56-11ea-9f6d-6e3d5b227178.png)

Having the same problem. All NPCs report the same value of points, even though my true points (seen in currency window) are all different. This is not simply a visual bug, as I cannot buy the Chiv Chain I came here to get.

**Comment by Mikokiko** [comment]
I went and checked the NPC, the messages now appear to be correct, would need someone to test an assault see if the point allocation got also fixed with the maintenance of earlier.

**Comment by KnowOne134** [comment]
Issue corrected

**Comment by KnowOne134** [comment]
Issue corrected
