### ISSUE TITLE
Killed by Mijin Gakure, not weakened

### ISSUE THREAD

**Issue by Eme-FFXI** [EdenServer/community#2989]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Just got killed by Mijin Gakure from a Tonberry Decapitator and after raised, I was not in a weakend state.

**Comment by slassen** [comment]
Had you Mijin Gakure'd previous to this and then homepointed?

**Comment by Eme-FFXI** [comment]
Indeed I have.

**Comment by slassen** [comment]
Ok, I think we understand the issue. Thanks for reporting.

**Comment by 59blargedy** [comment]
resolved last patch
