### ISSUE TITLE
Rosel the Armorer - quest-giver gives declined dialogue even when accepted.

### ISSUE THREAD

**Issue by Pen-ff** [EdenServer/community#2990]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Minor issue - If you accept the "Rosel the Armorer" quest from Rosel in Sandoria, speaking to him again will trigger dialogue as if the quest was rejected. You can then accept the quest again, but a duplicate of the key item does not appear in the key items list.

![rosel](https://user-images.githubusercontent.com/66931503/84614641-58ff4400-ae8c-11ea-84f2-ef6a756ba6bb.PNG)

**Comment by KnowOne134** [comment]
Quest has been rewritten
