### ISSUE TITLE
Issues w/Maiden's Virelai on Colibri

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#2991]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

We were messing around at the end of a merit party and our Bard cast Virelai on a Greater Colibri intending to get charmed so that we could kill him for laughs and a free ride home. 

When the Colibri began to reflect the spell back, the zone crashed immediately.

Also of note, the chat log message said that the Greater Colibri was Charmed by our bard's Virelai spell but there was no actual charm effect.

ver. 30181205_0

**Comment by InoUno** [comment]
Resolved with December 14, 2020 patch.
