### ISSUE TITLE
Puppets do not teleport with master

### ISSUE THREAD

**Issue by InoUno** [EdenServer/community#2994]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

When being teleported (i.e. by portals in Riverne Sites, or out of BCNMs), puppets will be left behind and will not teleport with the master. This probably applies to all pet jobs.

With the new changes to pet pathing, it will take them a very long time to get back to the master since they have to (eventually) clip through a lot of terrain in order to get there. Before the pet pathing fix, they would just teleport to the master, since the master was far enough away for that to trigger.

**Comment by KnowOne134** [comment]
This was corrected in yesterday's patch. Are you still having problems today?

**Comment by InoUno** [comment]
Did a BCNM after yesterday's patch, and after exiting via the Run Away option (so you don't have to run all the way around to reenter) the puppet didn't teleport out with me, and it took a long time for it to make its way to me.

I haven't tried the Riverne Sites portals after yesterday's patch, but I did experience that last week before the patch.

**Comment by KnowOne134** [comment]
has been corrected
