### ISSUE TITLE
Unable to receive Assault Armband

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#2995]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Talking to any guard at any Staging point results in the message "Falzum's Mercenary Badge flashes" which I think is the ToAU mission text. 

Falzum is progressed up to the end of the available toau missions, and has all 5 assaults won and is PFC wildcat rank. So it's not mission progress related. 

My other character, Starby, has no problems getting armband.

ver: 30181205_0

**Comment by falzum** [comment]
Okay I'm an idiot, turns out I had an armband on Falzum this whole time. I assumed I didn't have one cause of how many assaults I did.

I've had one in KI this whole time which was promting the other text.

Perhaps all Armbands should be taken from party members upon entering? 

Or maybe a way to make sure only 1 party member buys one?

**Comment by KnowOne134** [comment]
This is retail accurate behavior. You can get 1 at anytime. Only consumers on the assault initiator
