### ISSUE TITLE
T1 ZNM trigger price not increasing at Sanraku

### ISSUE THREAD

**Issue by danismyhero** [EdenServer/community#2997]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Currently, when purchasing a T1 pop item from Sanraku, the price will not increase.  I was able to purchase two T1 in a row on separate characters without a price increase.

Quote from otherwiki:
https://ffxiclopedia.fandom.com/wiki/Sanraku

The amount of Zeni needed for a pop item appears to rise by 100 for Tier I for each item Sanraku hands out.
The amount of Zeni required for pop items decreases every two hours from when the last pop item was purchased. The amount decreased is 100 Zeni for Tier I, 200 for Tier II, and 300 for Tier III.
Maintenance resets demand to the minimum level, requiring 1000 Zeni for Tier I.
The maximum price for Tier I is 2500 Zeni

**Comment by 59blargedy** [comment]
missed this, resolved when znms rolled out
