### ISSUE TITLE
Post 10/2/2018 update black magic costs

### ISSUE THREAD

**Issue by Heretic667** [EdenServer/community#30]
Stone displays as costing 4 MP, have exactly 4 MP and it says I don't have enough MP.  MP costs likely are set to era values, but the display is still incorrect.

**Comment by godmode** [comment]
You’re correct—they are set to era values. Thanks for reporting this. We have plans of modifying the client dats in the future but it will take some time.

**Comment by beauxq** [comment]
Don't forget cast times also. That should also be changeable in dats.
