### ISSUE TITLE
Various Lord of Onzozo issues

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#300]
1. He's not supposed to be silencable/sleepable according to https://ffxiclopedia.fandom.com/wiki/Lord_of_Onzozo?oldid=340097 but I was able to do both here.

2. He doesn't cast Water 4 but that should be on his list of spells. 

3. He seems to greatly favor casting Flood. In two kills and 37 total casts, LoO has casted 25 Flood, 5 Waterga3, 7 Blindga, 0 Water 4. 

4. TP gain/usage is supposed to be higher than regular mobs but this doesn't seem to be the case here.

**Comment by godmode** [comment]
Are you sure that TP gain should be elevated here?
