### ISSUE TITLE
MP Drainkiss benefiting from Magic Attack

### ISSUE THREAD

**Issue by blinkwise** [EdenServer/community#3000]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

MP Drainkiss according to https://ffxiclopedia.fandom.com/wiki/MP_Drainkiss should not gain any benefit from Magic Attack.

 "Unlike Magic Hammer, MP drained is not enhanced by Magic Attack Bonus "

This is not the case on eden as is easily testable by using momento mori (MA+) before using drainkiss.

![image](https://user-images.githubusercontent.com/28693044/84807617-83104d80-afd5-11ea-8878-9331fa1dd8d9.png)

Looking at the topaz code it looks like topaz has a part of the function "addBonuses" carved out for drain and aspir, but leaves out mp drainkiss. If eden's code is similar it should be an easy fix of editing the file /scripts/globals/magic.lua.

The code carving out for drain/aspir is:

----------------------------------------------------------------------
    if (spellId >= 245 and spellId <= 248) then -- Drain/Aspir (II)
        mabbonus = 1 + caster:getMod(tpz.mod.ENH_DRAIN_ASPIR)/100
        if spellId == 247 or spellId == 248 then
            mabbonus = mabbonus + caster:getMerit(tpz.merit.ASPIR_ABSORPTION_AMOUNT)/100
        end
    else
        local mab = caster:getMod(tpz.mod.MATT) + params.bonusmab
------------------------------------------------------------------------
According to https://wiki.dspt.info/index.php/Spell_IDs the spell ID for MP Drainkiss is 521. So this might be fixable by adding an elseif:
------------------------------------------------------------------------------------
    if (spellId >= 245 and spellId <= 248) then -- Drain/Aspir (II)
        mabbonus = 1 + caster:getMod(tpz.mod.ENH_DRAIN_ASPIR)/100
        if spellId == 247 or spellId == 248 then
            mabbonus = mabbonus + caster:getMerit(tpz.merit.ASPIR_ABSORPTION_AMOUNT)/100
        end
    elseif (spellID == 521) then --MP Drainkiss
           mabbonus = 1
        end 
    else
        local mab = caster:getMod(tpz.mod.MATT) + params.bonusmab
---------------------------------------------------------------------------------------------------

Ill leave the fix to you guys since I am not a dev so don't take my code as correct, but since the code carves out an exception for aspir, and mp drainkiss is effectively aspir the same carve out should work.

Thanks,

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 update.
