### ISSUE TITLE
Charm Rate vs. Slime likely too low

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#3001]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Was messing around in Garlaige Citidel and was unable to charm a level 52 slime after 5 attempts (normal fighting gear, barely any CHR) so I put on my CHR set (116 total CHR + light staff) and it took another 6 attempts to charm.

I know slimes should be a little resistant to charm but a 23 level difference plus that much CHR should be able to charm anything at an almost perfect rate.

It was Watersday, 90% Waning Gibbous if that matters.

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
