### ISSUE TITLE
Souleater Interaction With Stoneskin

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3004]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When buffed by Stoneskin and using Souleater, Stoneskin should nullify some of the health loss from it. Currently the health loss ignores Stoneskin and is not absorbed.
https://ffxiclopedia.fandom.com/wiki/Souleater - "The damage penalty of Souleater can be nullified by Stoneskin for an amount equal to the HP equivalent that the Stoneskin provides."

version 30181205_0

**Comment by rude-jerk** [comment]
https://github.com/project-topaz/topaz/pull/1442

**Comment by rude-jerk** [comment]
Resolved in November 16, 2020 patch.
