### ISSUE TITLE
DRK OoE Traits

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3005]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently the traits Stalwart Soul & Desperate Blows (non-merited version) are shown in the job traits menu on DRK. 

Stalwart Soul works and reduces the amount of health you would lose when using Souleater. This trait was added in 2011. 
https://ffxiclopedia.fandom.com/wiki/Stalwart_Soul

Unsure if Desperate Blows (non-merited version) is active pre-75 but this should be a merited ability only in this era. Currently the merit is called Desperate Blows Effect which was added later when Desperate Blows became a non-merit ability. Also another thing I'm unsure of is if Desperate Blows Effect is giving the OoE 2% haste per merit or the era 5% haste per merit. But basically Desperate Blows should be removed as a basic trait, Desperate Blows Effect merit should be renamed to Desperate Blows and then the haste % should be made to 5% per merit if it's not.
https://www.bg-wiki.com/index.php?title=Desperate_Blows&oldid=22254
https://ffxiclopedia.fandom.com/wiki/Desperate_Blows_Effect

version 30181205_0

**Comment by Mozzy4Ever** [comment]
iirc all meritable traits show in the job trait menu, but aren't actually active unless you have merits

**Comment by Slamm21** [comment]
while it says delay, this is actually job ability haste. Max here should be 15% with 3 merits, 5% per merit.

**Comment by danismyhero** [comment]
> 
> 
> iirc all meritable traits show in the job trait menu, but aren't actually active unless you have merits

This.  I most certainly did not merit Aggressive Aim.

**Comment by KnowOne134** [comment]
Fixed this update
