### ISSUE TITLE
"Chasing Tales" Quest Broken

### ISSUE THREAD

**Issue by jaymantan** [EdenServer/community#3006]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Per the classicffxi.fandom.com instructions:
I talk to Tosuka-Porika who tells me there is another overdue book and to speak to Furakku-Norakku.
Furakku-Norakku tells me that Hae Jakkya at the Windurst Woods Auction House has an overdue romance novel called "A Song of Love".
Hae Jakkya says "You nincompoop! Never in all me life 'as anyone even suggested I'd borrow an embarrasin' book like !. It's not just obstruction of business, why, it's violatin' me rights, that's what it is! Get the 'ell outa 'ere before I scrrratch ya eyes out!". *The text actually says "!" rather than the title of the book.
Returning to Furakku-Norakku, she says "Huh? You forgot? It's Hae Jakkya, who runs the auction house in The Windurst Woods. She's got a romance novel out called "A Song of Love" that is now overdue. Please get it back for us, okay?"
I've tried rechatting with all parties involved, but the quest does not progress from here.

version 30181205_0

**Comment by rude-jerk** [comment]
https://github.com/project-topaz/topaz/pull/1416

**Comment by 59blargedy** [comment]
just a note we need to fix some early bird catches the bookworm things with the correct param. may just correct it as part of this:
![image](https://user-images.githubusercontent.com/52636208/98452380-f0f01980-211c-11eb-855c-27b104912101.png)
![image](https://user-images.githubusercontent.com/52636208/98452470-ab801c00-211d-11eb-96d7-a6d607a95e4a.png)
also wiki mentions quu bokye will be walking around (he was not walking around) (minor issue)

optional dialogue from furakku after talking to hae the first time does not exist (minor issue)
able to complete quest after speaking with sandy hae and then furakku (pass)
optional dialogue post quest completion from hae does not exist (minor issue)
a smudge on one's record (next quest in series) is available upon completion of this quest and setting fame to 4 (pass)
overall pass, but note to self to look at fixing some of the dialogue if possible for early bird, as well as optional dialogue here.

**Comment by rude-jerk** [comment]
Resolved in November 9, 2020 patch.

**Comment by galenor** [comment]
I completed early bird catches the bookworm quest, unfortunatly am unable to get Chasing Tales, when talking to client, he has no reaction at all.

**Comment by galenor** [comment]
Still unable to get chasing tales quest
