### ISSUE TITLE
Monsters misnamed in Mount Zhayolm

### ISSUE THREAD

**Issue by nickycupcakes** [EdenServer/community#3009]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Client version:  30181205_0

Steps to reproduce:  At the intersection where i/j - 9/10 all meet (near the Cast Iron Plate spawn location on [this map](https://ffxiclopedia.fandom.com/wiki/Mount_Zhayolm/Maps)) there are a bunch of mobs who all are named "Sicklemoon Jagil" including Crabs and Flies (and maybe some Eruca too).  

I think the Crabs should be Wootzshell, the Flies should be Assassin Fly, and the Eruca should be Magmatic Eruca.

**Comment by 59blargedy** [comment]
this is a condition of client/not having renamer files
