### ISSUE TITLE
Monsters going into Staging Points in Mount Zhayolm 

### ISSUE THREAD

**Issue by Dorinorin** [EdenServer/community#3010]
![1B957B5B-DAC0-4789-A124-A7758066460C](https://user-images.githubusercontent.com/66181140/85092022-cd9cf000-b1b6-11ea-9bbc-737f3193da05.jpeg)
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

Two Magmatic Eruca came into the staging point in Mount Zhayolm (Halvung) when I had aggro. They shouldn’t be able to enter that section of the zone.

**Comment by Rikoooooo** [comment]
Yes! Lol, I had an Imp follow me through the gate thinking I'd escaped him, but nope!

**Comment by KnowOne134** [comment]
Fixed 10/11/20
