### ISSUE TITLE
Elementals disappearing and respawning mid fight when weather changes

### ISSUE THREAD

**Issue by maldra** [EdenServer/community#3011]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

I have twice witnessed thunder elementals respawning while fighting one. By this I mean if it is double thunder weather while I’m fighting a thunder elemental and the weather changes to single thunder weather the thunder elemental that I am fighting disappears and instantly reappears at the spawn point at 100%. I have also witnessed this when the weather goes from single thunder weather to double thunder weather.

Version 30181205_0

**Comment by mlandrum22** [comment]
Same issue as #1963.

**Comment by bkesecker** [comment]
Closing as duplicate.
