### ISSUE TITLE
Crafting | Moon/Direction/Day are confirmed to not affect crafting in any way.

### ISSUE THREAD

**Issue by ffxireports** [EdenServer/community#3014]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I don't know if this needs to be posted here but I know that base DSP has at least some moon/day/direction coded to it and FFXI devs have confirmed that none of these affect crafting in any way. With that said, I'm just making this to confirm the Eden devs know this. I see a lot of people spreading false information in game or at least tossing the idea that these affect crafting.

Assuming Eden is not coded this way, then my apologies for making this report. However, maybe it would be a good idea to make an announcement/add to the next patch notes that these are fact.

Source:
https://www.reddit.com/r/ffxi/comments/4ulgh1/official_ffxi_developer_ama_with_producer_akihiko/

Personally, it would be majorly disappointing to me if Eden uses these variables in crafting equations like many private server do.

**Comment by icariumkupo** [comment]
![Screenshot_20200620-193302_1](https://user-images.githubusercontent.com/37199798/85214779-11196a80-b32d-11ea-9cc3-612b88a011f6.png)

**Comment by ffxireports** [comment]
#eden

**Comment by Slamm21** [comment]
Closing this, devs know the above

**Comment by Mozzy4Ever** [comment]
"I know that base DSP has at least some moon/day/direction coded to it"

They have toggles for it, which are by default set to disabled. Every person I've spoken to that crafts a shit ton says they notice no difference when it comes to day/direction/etc. Consideringb that on DSP it increases/decreases the level of the synth by 1, this would actually be something pretty easy for someone to prove with a cheap synth. Synth something 100 times while 1 under the Tier 1 level while facing the right direction. Should be pretty apparent. If it's enable, you'd have about a 10% HQ rate. If not, 1%.

**Comment by rka666** [comment]
Slightly off topic.
Crafting might need to be revisited by devs?
T1 at 10% HQ chance 4/100. Next morning another 0/24. 
T2 at 25-35% HQ chance 0/8.
Will start writing down my numbers or taking screens going forward as many of my crafts are like 1/50, 2/50 at T1.

**Comment by Mozzy4Ever** [comment]
> Slightly off topic.
> Crafting might need to be revisited by devs?
> T1 at 10% HQ chance 4/100. Next morning another 0/24.
> T2 at 25-35% HQ chance 0/8.
> Will start writing down my numbers or taking screens going forward as many of my crafts are like 1/50, 2/50 at T1.

Would be a separate bug report
