### ISSUE TITLE
bolt belt

### ISSUE THREAD

**Issue by therawns** [EdenServer/community#3015]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

When I try to use a bolt belt I made, it will not work.  It says unable to use item.

**Comment by therawns** [comment]
my name on the game is rawns so if a GM can contact me that would be great.

**Comment by KnowOne134** [comment]
Means it's not coded yet

**Comment by therawns** [comment]
It says I need to file a report on here.

**Comment by therawns** [comment]
So I thought I did. What did I do wrong?

**Comment by therawns** [comment]
Even if I could just get the items that were used to make the belts I would be okay with that.

**Comment by KnowOne134** [comment]
You did right. I've documented tHat it needs to be coded. Will be closed
when it is

**Comment by therawns** [comment]
Did this get taken care of?

**Comment by KnowOne134** [comment]
In testing mode
