### ISSUE TITLE
Fafnir's susceptibility and lack of resistance to sleep

### ISSUE THREAD

**Issue by Corvinus1337** [EdenServer/community#3016]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

There are 2 issues at play here: 
1) Fafnir is too easily slept currently 
2) Fafnir is not building resistance to sleep.

On retail Fafnir would  generally require ES in order to sleep and he would gradually build resistance to sleep to prevent players from continuously sleeping it as a holding tactic. On Eden he is not building any resistance and players are currently able to land sleep without the use of ES.

I have collected some screenshots of sleeps being used within a short period of time and landing without a single resist. I have also linked FFXI patch notes from 2006 that specifically mention that "certain wyverns resistance against sleep has been increased."

Lastly, I have added comments from players in an old BG thread where they discuss landing sleep on Fafnir.

Fafnir #1 
![0](https://user-images.githubusercontent.com/61441566/85225757-6abb7c80-b3a1-11ea-8065-fc02bf4da448.jpg)
![1](https://user-images.githubusercontent.com/61441566/85225761-76a73e80-b3a1-11ea-9718-adad4f99e2c0.jpg)
![2](https://user-images.githubusercontent.com/61441566/85225762-773fd500-b3a1-11ea-970a-742fb9aa8aeb.jpg)
![3](https://user-images.githubusercontent.com/61441566/85225763-773fd500-b3a1-11ea-8715-0318a7f1c396.jpg)
![4](https://user-images.githubusercontent.com/61441566/85225765-77d86b80-b3a1-11ea-9933-9af7df3233f2.jpg)
![5](https://user-images.githubusercontent.com/61441566/85225766-78710200-b3a1-11ea-9657-828d20545fd0.jpg)

Fafnir #2 
![0](https://user-images.githubusercontent.com/61441566/85225774-858df100-b3a1-11ea-8868-8aae35bd781f.jpg)
![1](https://user-images.githubusercontent.com/61441566/85225775-86bf1e00-b3a1-11ea-83df-cdb8082d0824.jpg)
![2](https://user-images.githubusercontent.com/61441566/85225776-8757b480-b3a1-11ea-9294-c3b2a90b536e.jpg)
![3](https://user-images.githubusercontent.com/61441566/85225777-8757b480-b3a1-11ea-9415-31916a3742da.jpg)
![4](https://user-images.githubusercontent.com/61441566/85225778-87f04b00-b3a1-11ea-9a35-3c00d42a0286.jpg)
![5](https://user-images.githubusercontent.com/61441566/85225779-8888e180-b3a1-11ea-9b68-80f549d0c6c2.jpg)

Comments from old BG threads:
![1](https://user-images.githubusercontent.com/61441566/85225943-a0ad3080-b3a2-11ea-9f2d-7755b6fcd6bc.PNG)
![2](https://user-images.githubusercontent.com/61441566/85225944-a0ad3080-b3a2-11ea-82ef-4ac7d31e4881.PNG)
![3](https://user-images.githubusercontent.com/61441566/85225945-a0ad3080-b3a2-11ea-9a57-92d1353ccd00.PNG)

FFXI 2/21/2006 patch notes:
http://www.playonline.com/pcd/update/ff11us/20060221pJb1z1/detail.html
![patchnotes](https://user-images.githubusercontent.com/61441566/85226011-12857a00-b3a3-11ea-8ded-ec708b94dcb2.PNG)

**Comment by Slamm21** [comment]
you could wait a period of time before sleeping again and the resistance would start to fade. a decent RDM could sleep it much easier also but eventually resistance would still build. Without the resistance update, a good RDM could have slept it forever without issue.

The building resistance itself is more a magic hit rate thing for all NMs

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 update.
