### ISSUE TITLE
Changing weapon (e.g. to a warp cudgel) crashes cluster when wearing a Justice Torque

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3017]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Reporting from mobile on behalf of a friend. When wearing a Justice Torque, switching his main weapon (for example, to a warp cudgel) causes the zone to crash. Obviously this is inconvenient, but it could also be abused by anyone with this torque to intentionally crash a zone. 

Not sure if someone else with this item can weigh in, it could be a combination of factors, but it started as soon as he put his torque on. 

Hopefully this unveils related problems.

Version 30181205_0

**Comment by bkesecker** [comment]
Crash details caught.
