### ISSUE TITLE
BST pets are not aggressive if Charm wears off while they are asleep

### ISSUE THREAD

**Issue by nickycupcakes** [EdenServer/community#3018]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version:  30181205_0

Reproducable Steps:  

1)  Charm mob and fight an enemy mob with a TP move that can Sleep.  In my case, I charmed a Diving Beetle and fought a Birdtrap in Carpenter's Landing.

2)  Allow enemy to use Sleep TP move (Soporific) and make sure it sleeps your pet

3)  If pet is still asleep when Charm duration expires, the former pet will not agro the Beastmaster when it wakes up.  

Note:  I was standing right next to my former pet when it eventually woke up, so definitely within 30 yalms.  I had not Charmed a new pet yet, as his name remained "Blue" until sleep wore off

I'm fairly sure that the pet should agro the BST when it wakes up in this case, since it would normally be aggressive after Charm wears off if it is awake.  I've only experienced the conditions for this one time so far, so I have not been able to reproduce it more than once.

**Comment by InoUno** [comment]
Should be resolved in January 11th 2021 patch.
