### ISSUE TITLE
All of the Adventuring Fellows WSs are AoE

### ISSUE THREAD

**Issue by GiichiHiro** [EdenServer/community#3020]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

I've noticed my fellow getting weird adds and aggro when using her lately.  It seems each of her WSs are doing AoE.

![Double](https://user-images.githubusercontent.com/66037286/85303958-9150e480-b481-11ea-9e3d-d8c8f1888015.PNG) This was against a Manta and Torama
![2 beetles](https://user-images.githubusercontent.com/66037286/85303961-9150e480-b481-11ea-9e6e-651807785737.PNG) This was against 2 beetles.

**Comment by iklarazu** [comment]
I can confirm this is happening to me as well.

I have Fellow AoE WS turned off (meaning she won't use AoE weaponskills, such as Circle Blade,) however, my Fellow's single target WS seem to be hitting more than one target; they are not inflicting dmg, but are waking/agro'ing adjacent mobs.

![image](https://user-images.githubusercontent.com/65548510/87873702-88d5c600-c9bb-11ea-98da-7b01d8f4498f.png)
![image](https://user-images.githubusercontent.com/65548510/87873734-bae72800-c9bb-11ea-99c7-4ae32a1fbf88.png)


In this screenshot, we're killing 2 crawlers, the BLM sleepga'd them, and we woke one up to attack, but at the point were Tsuim uses Burning Blade, it woke up the 2nd crawler, but didn't actually do any dmg, and it's not recorded as such. We tried this a few times to confirm (though the first 2, I didn't have dmg recorded in log.)

**Comment by KnowOne134** [comment]
cannot reproduce issue
