### ISSUE TITLE
Castle Zvahl Keep Chest missing

### ISSUE THREAD

**Issue by Calamityjr** [EdenServer/community#3023]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Did some farming in Keep, got key and poped chest. It didnt repop even 6 hrs later. Sometimes after u pop it i resp as it should in diffeent or same location. But when it pops in broken location you cant get it til server reset. Had this situation twice during  12 hrs farming in there. Dont ask me like - have you check all 9 possible pop locations ? Ofcourse i did during 12 hrs farm.

**Comment by iklarazu** [comment]
It may be worth noting that I've found some chests don't pop in the correct locations. Kuftal Tunnel being a good example. There's one chest that spawns a little further down in the same room, and there's another one that pops near the entrance from Altep.

**Comment by Mozzy4Ever** [comment]
For the record it is possible for the Castle Zvahl Keep chest to spawn outside the map:
![image](https://user-images.githubusercontent.com/11255886/218879780-f44ad14c-bc9b-4e05-851b-da69b8a081ce.png)
!pos returns -347.000, 24.000, 64.000. Location is neither directly above nor below any section of the map.

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
