### ISSUE TITLE
Tele to whitegate from Ibwam in Windy Woods takes wrong amount of gil

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3025]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Traded Ibwam the 300g to warp myself to Whitegate when I had 447g. Now I'm in Whitegate with 403g. 

Ver: 30181205_0

**Comment by bkesecker** [comment]
Confirmed.
