### ISSUE TITLE
Serket Ring Drop % is likely too low

### ISSUE THREAD

**Issue by Raphtalia1** [EdenServer/community#3026]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Serket?diff=next&oldid=993244

http://ffxidb.com/zones/200/serket

Based on the Era Drop data on serket Sourced from ffxidb and ffxiclopedia (linked above) I believe his Base (TH0) drop rate on ring should be common (15%) rather than rare (5%), the data that shows it as a very uncommon drop rate on ffxiclopedia was after a major addition of kills/drop data that clearly makes little sense, the reported kills/drops went from 15/31 to 15/852 on ring, but the reports for V.Claw Jumped from 6/31 to 60/310. These are very suspicious rates and are not corroborated by ffxidb, but the rates prior to ffxidb do align with a common drop

**Comment by Raphtalia1** [comment]
Apparently i am late to the party and this was already addressed

**Comment by Mozzy4Ever** [comment]
If it was already addressed, it's not on the https://docs.google.com/spreadsheets/d/12d7uSwVhFNwPrIIuV6OAo-h6iravdIDYJQcz_x4IdE0/edit#gid=0 sheet
