### ISSUE TITLE
stream in Zeruhn mines is flowing wrong direction

### ISSUE THREAD

**Issue by AnimeMuyou** [EdenServer/community#3029]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
client version 30181205_0

The stream in Zeruhn Mines is supposed to flow from Palborough Mines in the north to pass through Zeruhn Mines in a southward direction.  Yet, standing on the bridge in Zeruhn Mines, I see the stream flowing from south to north (wrong/opposite direction).  Also confirmed by player Nidhogg.

**Comment by 59blargedy** [comment]
on retail it flows south to north as well, guess SE messed up, going to close this out.
