### ISSUE TITLE
"Nothing Matters" Quest not implemented?

### ISSUE THREAD

**Issue by porkbeast** [EdenServer/community#3030]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The quest [Nothing Matters](https://classicffxi.fandom.com/wiki/Nothing_Matters) doesn't seem to be implemented; Koru-Moru doesn't issue the quest.
- I have completed the previous quest
- I have maximum windy fame
- I have changed areas before returning to Koru-Moru

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
