### ISSUE TITLE
Dhalmel Meat Not selling for the correct amount

### ISSUE THREAD

**Issue by GiichiHiro** [EdenServer/community#3031]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver 30181205_0

As can be seen here, the max price should be 61: https://ffxiclopedia.fandom.com/wiki/Dhalmel_Meat

As can be seen here, with my max fame, it's capped at 59: 
![CheapMeat](https://user-images.githubusercontent.com/66037286/85769926-d29afb80-b6f0-11ea-87c9-82a9375a4242.PNG)

Minor issue, I know.

**Comment by Mozzy4Ever** [comment]
Issue related to https://github.com/EdenServer/community/issues/1907

**Comment by bkesecker** [comment]
The old ID page lists 61, but the resale price was further refined later in history.  In all likelihood, this was set to 59 to split the difference, given the issue Mozzy referenced.  It is probable that this issue will be filed again if closed without change, so if we set it to the minimum reported of 58, it should cap at 61 once we fix 1907.
