### ISSUE TITLE
BLM AF Eldieme Coffer - Gave me Gil.. (AF2 Quest is active)

### ISSUE THREAD

**Issue by ChipxAhoy** [EdenServer/community#3034]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version  30181205_0

I have BLM AF2 quest "Recollections" open, went to Eldieme to open the coffer (on BLM) for Wizards Tonban but i only received gil.

**Comment by FariskaEden** [comment]
I think you'll need to complete Recollections, and at least start Borghertz's Sorcerous Hands before the coffer there will give you AF. https://ffxiclopedia.fandom.com/wiki/Borghertz%27s_Sorcerous_Hands

**Comment by ChipxAhoy** [comment]
Hmm ok so it seem that its wiki that has wrong info.. damnit.  Thanks   [https://www.bg-wiki.com/bg/Recollections]

**Comment by 59blargedy** [comment]
closing per comments
