### ISSUE TITLE
is Shikigami this bad?

### ISSUE THREAD

**Issue by Nastynutsu** [EdenServer/community#3035]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
please take a look at Shikigami's drop rate, something is not right. 5 kill in a roll without any drop (no seal, Christal, nothing...)
3 out of 5 have TH4 helping... and got nothing.

**Comment by Slamm21** [comment]
This probably should be in the common category based on ffxidb
http://www.ffxidb.com/zones/122/shikigami-weapon
However it might already be, 5 kills is an extremely low sample size.

**Comment by 59blargedy** [comment]
The drop rate is coded as common. with th4, there is a 45% chance of the robe dropping, with TH0 there is a 15% chance. Sorry you are having bad luck and hope it drops for you soon, closing this ticket out.
