### ISSUE TITLE
Scogan's Knuckle latent not coded.

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3037]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

with checkparam on pet  the ACC latent doesnt kick in when equiped.

**Comment by Shoruto** [comment]
Duplicate of #1136
