### ISSUE TITLE
Wyverns/Automaton Despawn Conditions When Entering Battlefields

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3039]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently when entering battlefields (BCNMs, KSNMs, ENMs, etc.) if you have a wyvern or automaton out you will always lose it after entering. If your pet is the same level or below the sync cap for these fights they should not be desummoned. For example if I enter the ENM Sheep in Antlion's Clothing as a 75 puppetmaster with an automaton active, it should not be lost upon entering the battlefield. These pets should only be lost if they are above the level of the battlefield as this is still the same on retail to this day.

version 30181205_0

**Comment by 59blargedy** [comment]
do you have any information that states this? i can only find uncapped fight examples, so would like some proof of this before implementing

**Comment by FariskaEden** [comment]
https://www.youtube.com/watch?v=rhoV4KXl8os - I had carried over a level 60 automaton from doing a 60 cap ISNM (pets retain their sync'd level if you zone on retail, might have to make a bug report on this part too) but you can see the pet came in with me despite being sync'd lower
https://www.youtube.com/watch?v=dcMx1yDmj4Y - pet "killed" entering a 75 cap ENM since it's higher level here
https://www.youtube.com/watch?v=PrBbG-bR37A - pet retained entering a 75 cap ENM since it was summoned in another 75 cap ENM and brought over since level was retained

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
