### ISSUE TITLE
The "???" for Map of Phomiuna Aqueducts does not give the map.

### ISSUE THREAD

**Issue by Rikoooooo** [EdenServer/community#3041]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

In Phomiuna Aqueducts there should be a "???" on the third map in 1 of the 4 library rooms filled with fomor. I searched each room within a few hours and found the right "???" but it gave nothing. Notice also that there are multiple "???" possible in these rooms to open hidden doors, however these "???" are restricted to the Bookcases. The one that gives the map would be in a corner with Boxes, Pots etc., not on the Bookcase. Like I said, I found the one in a corner on some pots, clicked it but nothing and it was used for nothing else. The other "???" in the room opened doors, this one did nothing. Also there was very few people in the zone when I was doing this and the few that were, were farming for a Fomor Codex.

Hope this was helpful enough, I'm a map fiend. I need all the maps! Lol.

version 30181205_0

**Comment by Slamm21** [comment]
Old bug with existing bug report, https://github.com/EdenServer/community/issues/288
closing this.

**Comment by Rikoooooo** [comment]
Ah okay! I searched for "Phomiuna", so I missed this report.
