### ISSUE TITLE
Sandy Mission 2-3: Journey Abroad (Journey to Bastok)

### ISSUE THREAD

**Issue by nitro-neal** [EdenServer/community#3042]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

 I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)

    I have provided my client version in the details. (Version: 30181205_0)

Details

Character: Trabe
Version: 30181205_0
Sandy Mission 2-3: Journey Abroad (Journey to Bastok)
I did the windhurst part and now I'm in Bastok attempting to do the burning circle part.
I have talked to Savae, then Pius, then Ghrom. Ghrom says head to the mines, but when I click on the burning circle solo nothing happens.

**Comment by thesuie** [comment]
I am having the exact same issue. Find attached images mapping out the issue.

I spoke with the Sandy consulate in Bastok, who sent me to Pius. Pius now gives me the text below, stating I need to talk to Grohm.

Grohm gives me the text below, telling me to to go the mines.

At the mines, I do not have the options to start the battle scene.

I do notice that the mission text in my log is not updating for some reason.


![pius](https://user-images.githubusercontent.com/68578922/88012996-4d391a00-cae9-11ea-93b5-0f7b0016a99f.PNG)
![grohm](https://user-images.githubusercontent.com/68578922/88013015-588c4580-cae9-11ea-818a-aae7a630bd5d.PNG)
![cursed](https://user-images.githubusercontent.com/68578922/88013032-64780780-cae9-11ea-88c2-62ee35c06153.PNG)
![mission update not](https://user-images.githubusercontent.com/68578922/88013082-81acd600-cae9-11ea-8a77-818d9c20df27.PNG)

**Comment by Shoruto** [comment]
Similar issue #2401

**Comment by 59blargedy** [comment]
having reviewed code i believe this was an individual issue related to variables and not something that happens globally, closing
