### ISSUE TITLE
Your Crystal Ball - Kurou-Morou won't read fortune after completing quest

### ISSUE THREAD

**Issue by aprilgarrity** [EdenServer/community#3043]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version: 30181205_0

1) Have Jeuno reputation level 2.
2) Complete "Your Crystal Ball Quest," verified it is listed under "completed quests"
3) Visit Kurou-Morou any other game day after completing this quest.

Rather than giving a fortune, Kurou-Morou just gives the line of dialogue, "Welcome! You stand before Kurour-Morou the Magnificentaru! Speak to me, and will will be revealed." The next quest doesn't begin until you have reptutation level 5, but all wiki's explicitly state the reward for the quest being that you get to have your fortune told.

I have waited several irl days as well and have still not been able to receive a fortune.

**Comment by KnowOne134** [comment]
closeing due to dupelicate https://github.com/EdenServer/community/issues/1973
