### ISSUE TITLE
Collect Tarut Cards - Incorrect Reputation level for flagging

### ISSUE THREAD

**Issue by aprilgarrity** [EdenServer/community#3044]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version: 30181205_0

1) Be Jeuno reputation 2.
2) Speak to Chululu
3) Cry

Cannot flag quest, I'm assuming due to my reputation. Chululu gives me the following line of dialogue: "Aha! I haven't seen you before. I am Madam Chululu. I specialize in divining compatibility." To be clear, I have already completed "Your Crystal Ball" and was able to flag and complete it without issue. I have also been able to flag other Jeuno quests that require reputation 2; this is the only one I am having problems with. There are no pre-requisites for this quest, so I am assuming it is due to reputation. I was able to flag and complete this quest on my main, who has max fame.

**Comment by aprilgarrity** [comment]
I returned once I obtained Reputation level 3 and was able to flag the quest. However, this quest is supposed to be flagable at level 2.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
