### ISSUE TITLE
Crafting Titanictus Shell does not result in proper HQ amount

### ISSUE THREAD

**Issue by re1master** [EdenServer/community#3046]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Crafting Armored Pisces into Titanictus Shell will only yield 1 shell on HQ. HQ should be 2-4 shells.

https://ffxiclopedia.fandom.com/wiki/Titanictus_Shell?oldid=313183

Version 30181205_0

![2020-06-27 13_40_26-Window](https://user-images.githubusercontent.com/2515375/85928560-da3adb80-b87b-11ea-88c0-5161939c0c70.png)

**Comment by MalteseFalcon** [comment]
The synth is fine. Armored Pisces can't HQ its always 1. The HQ is only possible when desynthing Titanictus speficically.

![titanictus](https://user-images.githubusercontent.com/33695616/85932666-fcdcec80-b89b-11ea-8b12-ec3b74913028.jpg)

**Comment by re1master** [comment]
Thank you for proving I need glasses, lol.
