### ISSUE TITLE
Soldier/Worker Pephredo drop rates

### ISSUE THREAD

**Issue by him911** [EdenServer/community#3047]
This cant be right. 2 hours of killing Soldier and Worker Pephredo with TH4 and not a single royal jelly dropped

### Checklist

- [yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [yes ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by 59blargedy** [comment]
This is set to rarity 2 on both mobs which corresponds with wiki and [ffxidb.](http://www.ffxidb.com/items/4508#dropped-by)
