### ISSUE TITLE
Ether Tank synth acting strangely

### ISSUE THREAD

**Issue by dunayevskaya** [EdenServer/community#3048]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
VER:30181205_0

When I try to craft "ether tank" it says I don't have the necessary skill to craft it. I cannot do the synth. I'm 60 Alchemy (craftsman), 0 Leatherworking and the synth appears to be 54 Alch 1 Leather: https://ffxiclopedia.fandom.com/wiki/Ether_Tank?oldid=113829 

Yes I did sign up at the Leatherworking guild

I have all the necessary materials, it gives an error that's identical to when I try to craft something thats far above my skill level.

The reason this became a issue for me is that the alchemy guild asked me to make them as a guild point item today.

**Comment by ccl085** [comment]
Leather sub is most likely higher than 1, I had the same issue
