### ISSUE TITLE
Cutter crabs dropping white rocks

### ISSUE THREAD

**Issue by AinzOdie** [EdenServer/community#305]
Cutter's in Castle Oztoja dropping white rocks
![white rock](https://user-images.githubusercontent.com/44917243/48298241-a11fde80-e47f-11e8-9bf6-9efd75db0468.PNG)

**Comment by chlorr** [comment]
Should be that way I think.
 https://ffxiclopedia.fandom.com/wiki/Cutter
 wiki says 0% but its still in their pool. just a rare drop from the crabs opposed to the other mobs there (crawlers)

**Comment by jmcmorris** [comment]
My guess that this is a mistake and Cutter should not drop White Rock. I imagine the person that added it to the wiki had gotten it from a nearby Meat Maggot that do drop them.
