### ISSUE TITLE
OP bugged out when trying to warp back to town

### ISSUE THREAD

**Issue by Spiffly** [EdenServer/community#3050]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

I used the OP warp from West Ronafaure to get back to Sandy. Everything worked as normal until i was 'warped'. My character turned invisible but i didn't get warped. I was still able to run around the zone and kill mobs like i had beeen doing leading up to this. The mobs could also still attack me.

Other info:

I was NIN12/BST5 and i had a pet currently charmed when i tried to warp.
I was still able to send the pet to attack after the bug,
Trying to OP warp a 2nd time fixed the issue and i was promptly sent to town.
I don't know whether i was charged twice or not.

![Pendulum_2020 06 30_001051](https://user-images.githubusercontent.com/59734926/86098692-62082c00-baae-11ea-81e1-b640ea414195.png)

**Comment by Mozzy4Ever** [comment]
iirc this and other bugs like it (like using teleporters in Promies/Sky) are caused by combat happening while using the teleport

**Comment by 59blargedy** [comment]
resolved 10/12 update
