### ISSUE TITLE
Corsair LB5 Quest Is Not Breaking Limit. (70-75)

### ISSUE THREAD

**Issue by MissMaven** [EdenServer/community#3052]
[https://youtu.be/y5Zkun4fNnU](https://youtu.be/y5Zkun4fNnU) ![IMG_20200630_230654](https://user-images.githubusercontent.com/67683575/86224910-55331900-bb3e-11ea-9559-0f4674de8598.jpg)
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Client Version: 30181205_0
Quest: Breaking The Bonds Of Fate

I first encountered an error last week, when I entered the arena, followed the strategies I'd read on using sleep pots with opo necklace, buffing rolls, eating food using blink band and swapping back to good gear, etc and went in to engage and camera zoomed into first person, couldn't move or engage, died and the camera went into a free flying mode I could move around with the WASD keys. So I put tickets in to try and get my testimony back at least.

The reason I mention that is because I was able to get my testimony replaced, this evening (6/30) by a GM, so not sure if that's why it bugged tonight when I completed it or if it was something else entirely.

Anyways, I completed the fight, barely winning and the cutscene played and it teleported me out to Tallaca Cove and played the Victory music and gave me a clear time. I had read I'd be done after that, so I went to XP and found that I was still capped. Told to talk to Matt or try Ratihb and neither had anything to say.

Also, when viewing other videos of the fight, I noticed it says "Your level limit is now 75" and for me it did not. I have screenshots and video in the discord tech support channel as well as here.

This is my first bug report and sorry if it's not detailed or filled with irrelevant details. xD

**Comment by KnowOne134** [comment]
no ther reports of said bug and quest has been reworked since this, clearing report
