### ISSUE TITLE
Taxim gil too low

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#3053]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

We killed Taxim and received 360g when we should get 3500-5580.

Also, Homepoint's DB tool doesn't have him dropping any spells when he should be dropping them at a pretty good clip. (we got 2 bone chips and no other drops)

http://www.ffxidb.com/zones/212/taxim

**Comment by xizeta** [comment]
Have confirmed this is set correctly on Eden. Please ensure you are posting bugs for Eden server only. The issue tracker for HomepointXI can be found here: https://github.com/HomepointXI/Issues
