### ISSUE TITLE
Fly's Cursed Sphere appears to be coded as water-based

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3054]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Did some messing around on the test server with SMN. While dark elemental did occasionally resist a fly's use of Cursed Sphere, it definitely seemed like Water Elemental had a straight reduction in damage to it leading me to believe that Cursed Sphere is coded as water damage instead of the dark damage like it's supposed to be (https://ffxiclopedia.fandom.com/wiki/Cursed_Sphere)

NOTE - I'm specifically talking about how when mobs use it, it's dark based. When BLU uses it, it's supposed to be water based (and currently is)

**Comment by KnowOne134** [comment]
Fixed this update
