### ISSUE TITLE
Kirin instantly summons gods

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3056]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently when fighting Kirin, it will instantly summon gods instead of taking the time to cast them to summon them. Cast time looks to be 7-8 seconds?
https://www.youtube.com/watch?v=QFXAlvgOHXo

version 30181205_0

**Comment by 59blargedy** [comment]
Resolved in 8.16 patch
