### ISSUE TITLE
Enemy Heat Breath & Radiant Breath cast times

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3057]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently the cast time of enemy Heat Breath & Radiant Breath is near instant. These abilities should have a longer cast time, around 3-4 seconds from the looks of it.
https://www.youtube.com/watch?v=VzEZ2HtZUEM
https://youtu.be/QFXAlvgOHXo?t=610

version 30181205_0

**Comment by 59blargedy** [comment]
resolved december 7 update
