### ISSUE TITLE
Soultrapper can't be used on mobs claimed by others.

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#3058]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver. 30181205_0

"It is possible to capture the image of monsters claimed by others."

https://ffxiclopedia.fandom.com/wiki/Category:Pankration

I tried to take a picture of Nidhogg in an outside party and could not, which made me very sad :(

**Comment by danismyhero** [comment]
Did you try to manually use it via inventory or a macro line?  If you have not tried to use it via macro line
`/item "Soultrapper" <t>`
Try that and see if it is able to be used on a claimed mob.

**Comment by 59blargedy** [comment]
resolved upon znm implementation
