### ISSUE TITLE
Pieuje's Decision NM Altedour I Tavnazia total pushover

### ISSUE THREAD

**Issue by Mahou81** [EdenServer/community#3059]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Version: 30181205_0
The NM Altedour I Tavnazia in WHM AF quest Pieuje's Decision is far weaker than it is supposed to be. I killed it on my 75 rdm/nin and it died much too quickly. It seemed even weaker than the normal Shadow mobs which already proc "Too weak" on a 75 in Fei'Yin. Please review this NM's stats and magic/ablility use and adjust where necessary. The NM was popped by my lv 50 WHM alt by the way. Ffxiclopedia page on this nm (please check testimonials): https://ffxiclopedia.fandom.com/wiki/Altedour_I_Tavnazia

**Comment by E5una** [comment]
Looks like this bug report already exists but I can second this. Era wiki (https://ffxiclopedia.fandom.com/wiki/Altedour_I_Tavnazia?oldid=365634) mentions a potent en-aspir on melee, but you can see that didn't happen from the log (Ryldz is a WHM).

"Has an En-Aspir effect on physical attacks that is very potent."

Current wiki (https://ffxiclopedia.fandom.com/wiki/Altedour_I_Tavnazia) says 16,000~17,000 HP, but you can see from my screenshots that he has ~3.5k.

It also mentions his resistance to things like Silence. I'm not saying he's not resistant, but it might be something to check.

![StartOfCombat](https://user-images.githubusercontent.com/13668758/90829773-61ea1700-e30e-11ea-9f8c-941f6bfe60c7.PNG)
![EndOfCombat](https://user-images.githubusercontent.com/13668758/90829778-64e50780-e30e-11ea-972c-91b9bf7b3f56.PNG)

version: 30181205

**Comment by 59blargedy** [comment]
resolved in December 21, 2020 patch
