### ISSUE TITLE
Asking crafting guild members for synthesis information freezes character.

### ISSUE THREAD

**Issue by Shuu-37** [EdenServer/community#306]
~~After speaking with Fatimah NPC in Bastok Goldsmithing guild, unable to move or do anything.~~

Speaking to a crafting guild person and asking for synthesis information freezes your character.

**Comment by chlorr** [comment]
I've only experienced this when accidently asking for tips from them miss clicking instead of support. maybe that happened?

**Comment by Shuu-37** [comment]
@chlorr Yep, exactly that.

**Comment by chlorr** [comment]
yeah idk why it happens but can confirm you freeze when doing so

**Comment by godmode** [comment]
Duplicate of #435
