### ISSUE TITLE
Sleepga from Shiva not attempting to sleep multiple mobs

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#3060]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
https://github.com/EdenServer/community/issues/2569

It looks like the same issue that this person reported and then later closed.  Basically, Sleepga seems to only be affecting the 1 mob that it was cast on and then not attempting to sleep any other mobs around it.

These mobs had not previously been slept (sleepga was my hail-mary to see if i could logout to save myself... it didnt work)
![image](https://user-images.githubusercontent.com/37307792/86500114-c55ebc00-bd43-11ea-9451-a3d0c035876b.PNG)

**Comment by 59blargedy** [comment]
resolved oct 4, 2020 update, was an issue with macc. will still give incorrect "no effect" message if sleep doesnt land on targets instead of resist msg.
