### ISSUE TITLE
Ebisu Rod Quest not working properly - does not issue rod after conquest update

### ISSUE THREAD

**Issue by nicholasbludau** [EdenServer/community#3063]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by xizeta** [comment]
Please provide more info. Is this resolved?

**Comment by Raphtalia1** [comment]
It’s not resolved, it should be given after next conquest update but instead it’s giving the rod 24h after item turn in, was reported a while ago but likely didn’t get documented correctly

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
