### ISSUE TITLE
Cannibal Blade versus Perfect Dodge

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3066]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently Cannibal Blade will miss versus Perfect Dodge. Cannibal Blade should never be able to miss.
https://www.youtube.com/watch?v=8zDwl51XgVo

version 30181205_0

**Comment by E5una** [comment]
Update: It can miss normally too, but shouldn't be able to:

![image](https://user-images.githubusercontent.com/13668758/167212974-d3e50f88-d476-4be2-86d1-69337122bcd8.png)
https://ffxiclopedia.fandom.com/wiki/Cannibal_Blade

Missed after a flash

![image](https://user-images.githubusercontent.com/13668758/167213025-629039a8-3e69-4566-aff3-15a01219f71a.png)

**Comment by 59blargedy** [comment]
resolved July 8, 2022 update
