### ISSUE TITLE
Crow beret sub craft

### ISSUE THREAD

**Issue by scorchedxi** [EdenServer/community#3067]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
Crow Beret leather sub craft is incorrect. Wiki states the cap at 20, received a skill up at 53 leather.
https://ffxiclopedia.fandom.com/wiki/Crow_Beret

ver 30181205_0

**Comment by 59blargedy** [comment]
resolved
