### ISSUE TITLE
Stealth Shot and Flashy Shot

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#3068]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

### Details
The ranger merit abilities stealth shot and flashy shot currently do not have a status icons on the icon bar. 

Stealth shot on use (activating the status effect) gives 3000 VE instead of 300 VE. 
Flashy shot currently does nothing.

https://www.bg-wiki.com/bg/Stealth_Shot
https://www.bg-wiki.com/bg/Flashy_Shot

**Comment by dowzer** [comment]
Example of Flashy Shot vs Nyzul Fafnir

Rng/Sam

Uses Sekkanoki and Flashy Shot together, sweet spot range and the rest from melee range
First Sidewinder: 1857
Second Sidewinder: 1573 (No Flashy Shot)
Sharpshot+Barrage: 1659
Third Sidewinder: 1328

https://youtu.be/MhzYXDvvVEc?si=T-xyVAsjQo5qa3OX&t=1456

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
