### ISSUE TITLE
Zones go to sleep before mobs have a change to return

### ISSUE THREAD

**Issue by NiQ1** [EdenServer/community#3069]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

When the last player leaves a zone, the zone apparently goes to sleep immediately, before mobs have a chance to depop or move back to their spawn points. The result is that if you zone a mob it will remain on the zoneline and will aggro lower level who enters the zone immediately upon entry and before they have any chance to anything (e.g. cast sneak/inivis).

Steps to reproduce:
1. Be the only player in a certain zone (I specifically was in Qulun Dome)
2. Get a mob to chase you, then zone while it's near you
3. Wait for as long as you want, as long as nobody else enters the zone (from any direction, not only from where you stand)
4. Zone back
Expected - The mobs will go back to their initial spawn points
Actual - The mobs remain on the zoneline and if aggressive, will aggro you immediately when the zone finishes loading

**Comment by bkesecker** [comment]
This is intentional.  We can choose to turn zone sleep on and off.

**Comment by NiQ1** [comment]
> 
> 
> This is intentional. We can choose to turn zone sleep on and off.

Of course I know that zone sleep is intentional, I meant that zones should stay alive for about 15-20 secs before going to sleep, just so mobs don't instantly aggro players who zones without expecting it.
Please reconsider.

**Comment by bkesecker** [comment]
Thanks for clarifying.

**Comment by InoUno** [comment]
Resolved in March 29th, 2021 update.
