### ISSUE TITLE
Voluptuous Vilma & Rose Garden up at same time

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#307]
https://i.imgur.com/tujodgs.jpg

Rose Garden is supposed to morph into Vilma after an "unknown" amount of time (DSP is set to 10-10.5 hours). Looking at https://github.com/DarkstarProject/darkstar/blob/cb53b2e2e5386b827530b256b7990f6ace7b2aa2/scripts/zones/Yuhtunga_Jungle/mobs/Rose_Garden.lua it looks like if Rose Garden despawns to allow Vivian to spawn, it also enables Overgrown Rose (the PH for Rose Garden) to respawn. This will make it so that Overgrown Rose and Vivian are up at the same time. If enough time elapses, that would make the Overgrown Rose spawn into Rose Garden again. It seems like in the Rose Garden lua, there needs to be a check so that if Rose Garden is despawning to allow Vivian to spawn, the Rose_Garden_PH still needs to be set to DisallowRespawn(ID.mob.ROSE_GARDEN_PH, true); under onMobDespawn. 

I imagine under onMobDespawn it could be something like:

function onMobDespawn(mob)
    DisallowRespawn(ID.mob.ROSE_GARDEN, true);
    if (DisallowRespawn(ID.mob.Voluptuous_Vilma, true)) then
       DisallowRespawn(ID.mob.ROSE_GARDEN_PH, false);
GetMobByID(ID.mob.ROSE_GARDEN_PH):setRespawnTime(GetMobRespawnTime(ID.mob.ROSE_GARDEN_PH));
    end
    if (DisallowRespawn(ID.mob.Voluptuous_Vilma, false)) then
       DisallowRespawn(ID.mob.ROSE_GARDEN_PH, true);
end;

**Comment by godmode** [comment]
Very detailed! Thank you!
