### ISSUE TITLE
Fail to spawn provoker

### ISSUE THREAD

**Issue by alltanos** [EdenServer/community#3070]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver 30181205_0

Trading a satiator remnant to the ??? In promyvion - vahzl will not spawn the nm provoker 

https://classicffxi.fandom.com/wiki/Provoker

**Comment by alltanos** [comment]
https://github.com/project-topaz/topaz/pull/1035

**Comment by 59blargedy** [comment]
yeah, i approved the submission there :) just need some time to port it over, code is a bit different here. s o o n

**Comment by 59blargedy** [comment]
resolved 10/18
