### ISSUE TITLE
Outpost warps should be lost when changing nations

### ISSUE THREAD

**Issue by MalteseFalcon** [EdenServer/community#3073]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

If you change nations, all of the outpost warps should be lost and the supply runs should need to be compete again upon returning to that nation.

Complete supply runs on nation 1 > switch to nation 2 > switch back to nation 1 > all outposts should be unavailable until completing supply run again

https://ffxiclopedia.fandom.com/wiki/Outpost_Teleportation?oldid=348589

![OP-warps](https://user-images.githubusercontent.com/33695616/86783333-2b8e5c00-c02e-11ea-848e-79528428b0c6.jpg)

https://discordapp.com/channels/482610771126386688/529445946699022336/729953471649808400

ver 30181205_0

**Comment by Slamm21** [comment]
this would be an awful change to put in imo.
it takes way longer to get an OP on here than it did on retail. QoL is important.

**Comment by TracentEden** [comment]
Is this now in era (https://www.bg-wiki.com/ffxi/Version_Update_(06/09/2008)) ? if so probably can be closed.

**Comment by KnowOne134** [comment]
Is now in era
