### ISSUE TITLE
Thief-class mobs respawning with incorrect stats

### ISSUE THREAD

**Issue by TaskaDev** [EdenServer/community#3074]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Normal stats:
![Normal rabbit](https://cdn.discordapp.com/attachments/707915352100831312/730131472945512518/Taska_2020.07.07_143609.png)

Incorrect stats:
![Weak rabbit](https://cdn.discordapp.com/attachments/707915352100831312/730131502544715806/Taska_2020.07.07_144047.png)

Kill the Hobgoblin Animalier's first pet after the zone comes back online. All subsequent pets summoned by the Hobgoblin Animalier will have lower combat stats than normal and no ability to double or triple attack.

I am not aware if this same issue applies to other BST-type mobs.

version 30181205_0

**Comment by TaskaDev** [comment]
I have just experienced the same issue again with Nival Raptors in Uleguerand Range, which were respawning with lower evasion and no triple attack capability. It appears this issue is affecting Thief-type mobs.

**Comment by 59blargedy** [comment]
Resolved in December 1st patch
