### ISSUE TITLE
Uragnite and Coralline Uragnite spam Venom Shield starting at ~86%

### ISSUE THREAD

**Issue by Shika10** [EdenServer/community#3075]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Pretty easy to reproduce. Find any Uragnite and start fighting it. It will spam Venom Shield until dead while rarely stopping to do other abilities.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
