### ISSUE TITLE
Maat dodging ranged attack

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#3077]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Perfect dodge should not dodge ranged attacks, however on Maat it does.

**Comment by 59blargedy** [comment]
resolved in may 31, 2021 update
