### ISSUE TITLE
Dark Elemental (sky) immune to Sheep Song (light based BLU sleep)

### ISSUE THREAD

**Issue by Satirof** [EdenServer/community#3078]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

Dark elementals in sky are being 100% immune to sheepsong. This should not be the case. They should be immune to dark based (such as soporific), but not light based sleeps.
![Higana_2020 07 09_180027](https://user-images.githubusercontent.com/38270613/87020293-9a2a1000-c20e-11ea-8901-c0a5edb3e179.png)

Steps:
1: Attack Dark Elemental (sky)
2: Cast Sheep Song
3: Get 'no effect' message
4: Get beat on some more.

**Comment by E5una** [comment]
The same goes for sheep song on dark based Grah in sea. Not sure if this should be related to my other ticket on sheep song not working on undead:

https://github.com/EdenServer/community/issues/2700

**Comment by KnowOne134** [comment]
Yes it's all the same ticket. So closing. Already started preliminary work on fixing and splitting light/dark sleeps and resists
