### ISSUE TITLE
CoP Birds use wrong TP moves

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3079]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Category:Birds

CoP birds, such as those found in Bibiki Bay and Misareaux Coast ONLY use Helldive and Wingcutter. They should be able to use the other three attacks in the wiki link I provided.

Blindside Barrage - Damage, STR Down, and VIT Down.
Broadside Barrage - Damage, INT Down, and MND Down.
Damnation Dive - Conal damage and Stun.

Ver: 30181205_0

**Comment by bkesecker** [comment]
Damnation Dive appears to be coded, but Blindside Barrage and Broadside Barrage are not.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
