### ISSUE TITLE
Dynamis - Green/blue eyed statues that spawn after boss not recovering HP/MP

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#308]
Noticed this in Dynamis - San d'Oria last night. The original statues that are up when you zone in function properly, but the second set after you clear the boss doesn't do any of the healing.

**Comment by greyenvy** [comment]
Old issue, I know, but related.  The statues only give the HP/MP refresh to the alliance that killed it.  This effect should just hit all players within like 30 yalms or whatever.  It shouldn't be restricted just to one alliance as far as I remember.
