### ISSUE TITLE
[Sky] Aura Pot drop rate audit, Ro'Maeve water too low

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#3080]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

As of this moment Ro'Maeve Waters, required to spawn Olla Grande are a very low drop rate.  In fact I believe all drops from the Aura Pots in this area need to be audited.

The drop rates listed on our beloved [wiki](https://ffxiclopedia.fandom.com/wiki/Aura_Pot) for Aura Pots is based on 2028 trials with no way to determine what level of Treasure Hunter was used.

However on the [ffxidb](http://www.ffxidb.com/zones/178/aura-pot) entry for these same Aura Pots the drop rates are scaled out by Treasure Hunter level and are based on 52.643 trials, _significantly_ more than those on the wiki entry.  I believe this site has the more accurate of the two for this particular mob.

Based on the entry that appears to be correct, these should be the (rarity) for each of its drops:
Magic Pot Shard (4)
Mercury (4)
Red Mage's Testimony (4)
Flask of Ro'Maeve Water (3) - I believe this is set to 2 right now.
Thunder III (2)
Thunder IV (2)
Thundaga III (2)
Shell IV (2)
Burst (1)

Please take a look.  Thanks!

**Comment by Mozzy4Ever** [comment]
It was fixed. Hallelujah. 8/23/2020

**Comment by greyenvy** [comment]
Praise Altana.
