### ISSUE TITLE
Qutrub family don't have their triple HP triat (Lamia Idolator for example)

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3081]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Qutrub family should take double damage but have triple HP. Right now on Eden they take double damage but DO NOT have their triple HP trait.

https://ffxiclopedia.fandom.com/wiki/Category:Qutrub

"Strangely, while they possess approximately triple the normal HP of other mobs their level, qutrub also take twice the normal damage from both physical and magical damage."

Lamia Idolators have ~5k hp on Eden but should have ~15k hp per the wiki

https://ffxiclopedia.fandom.com/wiki/Lamia_Idolater

![image](https://user-images.githubusercontent.com/13668758/87154365-1bbd8480-c287-11ea-9037-b8e053ee73a3.png)

![image](https://user-images.githubusercontent.com/13668758/87154634-8f5f9180-c287-11ea-991c-54a205735c22.png)
(exp ring on btw)

version 30181205_0

**Comment by FariskaEden** [comment]
To add to this, qutrub family mobs do not calculate damage from skillchains correctly. On Eden currently a light skill chain will do 1:1 damage (i.e 1000 damage will have 1000 light skill chain damage).

Checked them out on retail and here are some skillchains performed on them.
![image](https://user-images.githubusercontent.com/46270382/87238929-10796e80-c3d7-11ea-8501-097ed17c6750.png)
![image](https://user-images.githubusercontent.com/46270382/87238932-140cf580-c3d7-11ea-95d7-a41d86a3ea2b.png)
![image](https://user-images.githubusercontent.com/46270382/87238933-17a07c80-c3d7-11ea-85d0-eec9dd2a5402.png)
![image](https://user-images.githubusercontent.com/46270382/87238935-1a9b6d00-c3d7-11ea-94e7-1b231456342a.png)
![image](https://user-images.githubusercontent.com/46270382/87238938-1e2ef400-c3d7-11ea-8e03-95d77d668a9e.png)

Elemental resistances seem to match up to https://www.bg-wiki.com/bg/Category:Qutrub. So for example the light skillchains shown here all do 2.6x of the damage inflicted (weaponskill damage x 1.3 light weakness x 2 double damage they take). Induration (ice) they resist by 50% so the one shown here gets the double damage trait negated essentially and inflicts normal level 1 skill chain damage.

**Comment by Far-The-Killer** [comment]
@FariskaEden Can you open this as a separate bug report?
