### ISSUE TITLE
Charybdis placeholders incorrect respawn times

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3082]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Charybdis placeholders should be 16 min respawn time, not 5 minute respawn time like they are on Eden. The 5 minute respawn time is the current 2020 version, and is not era.

Here is the Nov 11th 2007 wiki page
https://ffxiclopedia.fandom.com/wiki/Charybdis?oldid=374854

"Minimum respawn time of 8 hours. After that time passes, Charybdis has roughly a 5-10% chance to spawn in place of its placeholder. (Devil Mantas have 16 minute repop times.)"

version 30181205_0

**Comment by E5una** [comment]
Relating this to https://github.com/EdenServer/community/issues/3082 by mentioning it here, not sure if there are actual relationships you can make between tickets.

**Comment by jesq22** [comment]
Can confirm Devil Manta respawn times to be 5-6 minutes.

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
