### ISSUE TITLE
Wingcutter damage seems weak. 

### ISSUE THREAD

**Issue by Fng098** [EdenServer/community#3083]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Raven's in Bibiki bay were doing wingcutter.  No shell, no baraera damage was 30ish HP.  That seems super low.  
Might be tied to issue 3079 where they are not doing the correct spells / job abilities.

**Comment by 59blargedy** [comment]
resolved in December 21, 2020 patch
