### ISSUE TITLE
DRK AF Feet Cutscene (Ordelle's) put me behind zone line.

### ISSUE THREAD

**Issue by Satirof** [EdenServer/community#3085]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Doing DRK AF feet. I entered ordelle's and got the cutscene with zeid. After the cutscene was over I noticed I was behind the zone line, and was able to follow the path further north. Screenshots show where on the map I could get to, as well as end of the terrain. I did not try walking into the void as did not want to get more stuck.

I was able to follow the path back to the zone and zone out from the other side of the zone line (if that makes sense?)

Can't reproduce as the cutscene is one-time only

Steps
1: Start DRK AF
2: Zone into Ordelle's Cave (was on BLU if that makes a difference)
3: Have cutscene with Zeid
4: Go north at end of cutscene and notice you're outside the normal map area
![Higana_2020 07 11_144137](https://user-images.githubusercontent.com/38270613/87217539-42fa7b80-c385-11ea-9dbe-4d2b5aafd5da.png)
![Higana_2020 07 11_144131](https://user-images.githubusercontent.com/38270613/87217540-4857c600-c385-11ea-8635-76f582153e4a.png)

**Comment by 59blargedy** [comment]
resolved in January 18, 2021 update
