### ISSUE TITLE
Ecliptic Howl giving +25 instead of +26 to eva/acc.

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#3086]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

On Earthsday 45% it gave 12 acc and 13 eva. 

On Darksday 12% it gave 5 acc and 20 eva. 

They should be adding up to 26, not 25. Assuming this is just some sort of rounding error. 

https://ffxiclopedia.fandom.com/wiki/Ecliptic_Howl

Looks like it should be 13/13 and 5/21.

**Comment by 59blargedy** [comment]
fixed with august 9 update
