### ISSUE TITLE
King Arthro spawn positions are inaccurate

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3087]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

A majority of King Arthro's spawn positions are currently not accurate to era/retail. As most people who camped KA in era would remember, people used to always crowd around the North bank and nowhere else. Right now on Eden, the spawn positions have everyone spread out evenly along spots at the N shore, S shore, E tree/hill between the shores, and even a very odd spot near the SW trees, completely out of bounds of the shoreline. It's completely unlike era. 

Going to provide some screenshots/videos below, fair warning some of them are pretty poor quality.

![KA1](https://user-images.githubusercontent.com/49970272/87239083-ed4fbe80-c3d8-11ea-80e1-6a33aa9329c8.png)
![KA2](https://user-images.githubusercontent.com/49970272/87239085-efb21880-c3d8-11ea-8623-1924af38bad8.png)
![KA3](https://user-images.githubusercontent.com/49970272/87239086-f17bdc00-c3d8-11ea-8c34-32466d19f26a.png)
![KA4](https://user-images.githubusercontent.com/49970272/87239087-f3459f80-c3d8-11ea-990b-7c0b94caf71b.png)
![KA5](https://user-images.githubusercontent.com/49970272/87239090-f5a7f980-c3d8-11ea-8e31-7eb78523b933.png)

Videos where these screenshots were taken from:
https://www.youtube.com/watch?v=O89LEDHkVe8
https://www.youtube.com/watch?v=wzSUB8QIsfk
https://www.youtube.com/watch?v=mhDcFbpuS0Y
https://www.youtube.com/watch?v=q-GjigdeAb0
https://www.youtube.com/watch?v=Ve7JksdL3KM

This was just me searching YouTube for a bit. I'm sure there is plenty more proof out there.

I have provided an in-game screenshot showing the same area (northern shore) shown in the above screenshots/videos.

![KAshore](https://user-images.githubusercontent.com/49970272/87239133-7e269a00-c3d9-11ea-9bdb-a68bac3a1679.png)

**Comment by ElectroNicMan83** [comment]
Wasnt the spawn position changed, I remember that a year ago. It was made larger

**Comment by dowzer** [comment]
I recall reading it was changed on Eden as well, although it’s still incorrect.

On retail servers, it only spawns on the north beach. The spawn location was never altered.

**Comment by Mozzy4Ever** [comment]
![image](https://user-images.githubusercontent.com/11255886/93409852-7104ac00-f85d-11ea-9b07-c6b9af726898.png)

Just updating with this map from http://ffxidb.com/zones/104/king-arthro

If you double-click on the google map you can zoom in and show that across 529 kills, it always spawns in those areas. Currently KA still has an invalid spawn point a good 15-20' from the southern half of the beach.

**Comment by 59blargedy** [comment]
resolved sept 27 2020, comment here if still looking wonky
