### ISSUE TITLE
SexChange Addon Broken?

### ISSUE THREAD

**Issue by Nyur0** [EdenServer/community#3090]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Heya,

Noticed for a couple of days now, the SexChange Addon will load but won't register when I go to change equipment. 

Have heard a couple of other players have experienced the same thing. I know this is strictly aesthetic, but is it possible to look into?

![Screenshot_71](https://user-images.githubusercontent.com/65654611/87344249-1462d900-c51c-11ea-9a11-d599b25699eb.jpg)

IGN: Nyuro
version 30181205_0

**Comment by KnowOne134** [comment]
Not a problem for the server, can ask in ashita discord
