### ISSUE TITLE
Yagudo Dynamis NMs - AoE Doom Removal on Death

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3092]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When Yagudo NMs die in Dynamis they should have a benediction like animation affect nearby players. This effect removes the effect of doom from their doom TP move if anyone had been affected by it.
https://www.youtube.com/watch?v=UgOpwVHQuR0&feature=youtu.be&t=214

version 30181205_0

**Comment by rude-jerk** [comment]
https://github.com/project-topaz/topaz/pull/1422

**Comment by rude-jerk** [comment]
Resolved in November 9, 2020 patch.
Note: the animation does not play, but the effect is removed.
