### ISSUE TITLE
Storm of Fates

### ISSUE THREAD

**Issue by MonkeyAce9** [EdenServer/community#3093]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I was heading into Rivine Site #B01 with the LS to hunt an NM and ran into the cut scene for Storm of Fates at the point when you check the Dilapidated Gate. the cut scene played as normal but right at the end after Prishe said she was a normal girl now, she then turned away and just slid away into the portal. Was quite funny actually.

ver 30181205_0

**Comment by 59blargedy** [comment]
resolved in the March 15, 2021 update
