### ISSUE TITLE
BLU Spell Enervation is not applying Magic Defense Bonus Down

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3096]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Enervation should apply a -8 Magic Defense Bonus penalty to the target. My MAB when casting is +47, so I'd expect roughly a 12% damage increase by applying -8 MDB. I tested multiple times, and all my tests revealed no difference with Enervation (I'll attach screenshots below). These tests 
were performed on watersday, so Eyes on Me was not impacted at all by day bonuses or penalties.

Enervation:
![Enervation](https://user-images.githubusercontent.com/13668758/87569934-de496480-c695-11ea-83ee-b85bb50f9d22.PNG)

No Enervation:
![NoEnervation](https://user-images.githubusercontent.com/13668758/87569899-d5589300-c695-11ea-9551-0ada192b3d47.PNG)

version 30181205_0

**Comment by KnowOne134** [comment]
Its def coded, will have to add prints and check to make sure it's being properly applied

**Comment by KnowOne134** [comment]
corrected on 11/9 update
