### ISSUE TITLE
BLU merit Diffusion should be 20 min recast

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3097]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

In era, Diffusion cooldown was 20 minutes with -2.5 minutes on the recast for each merit in it. On Eden it is currently a 10 minute cooldown.

https://ffxiclopedia.fandom.com/wiki/Diffusion?oldid=330993

**Comment by KnowOne134** [comment]
Fixed last update, merits fixed this update
