### ISSUE TITLE
Qutrub Family Mobs do not Calculate Skill Chain Damage Properly

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3101]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Qutrub family mobs do not calculate damage from skillchains correctly. On Eden currently a light skill chain will do 1:1 damage (i.e 1000 damage will have 1000 light skill chain damage).

Checked them out on retail and here are some skillchains performed on them.
![image](https://user-images.githubusercontent.com/46270382/87626502-76793500-c6fa-11ea-8a4a-9e9a3d26a907.png)
![image](https://user-images.githubusercontent.com/46270382/87626544-9a3c7b00-c6fa-11ea-9ffe-292dea0f92b3.png)
![image](https://user-images.githubusercontent.com/46270382/87626568-acb6b480-c6fa-11ea-99c2-0a90464951c4.png)
![image](https://user-images.githubusercontent.com/46270382/87626581-b2ac9580-c6fa-11ea-9efd-9735f4054f45.png)
![image](https://user-images.githubusercontent.com/46270382/87626463-5ea1b100-c6fa-11ea-803a-cee24a5fe082.png)

Elemental resistances seem to match up to https://www.bg-wiki.com/bg/Category:Qutrub. So for example the light skillchains shown here all do 2.6x of the damage inflicted (weaponskill damage x 1.3 light weakness x 2 double damage they take). Induration (ice) they resist by 50% so the one shown here gets the double damage trait negated essentially and inflicts normal level 1 skill chain damage.

version 30181205_0

**Comment by Serephim** [comment]
They should take double damage, that's why that happens. They have approximately triple the HP but take double the damage. That was the trade off.

**Comment by 59blargedy** [comment]
it appears this was solved, possibly with magic hit fixes.
