### ISSUE TITLE
Bastok Mission 9-2 Where Two Paths Converge Shadow HP

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3103]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Shadow of Rage summons from the Bastok Rank 10 fight seems to have the same amount of HP as Zeid himself. https://ffxiclopedia.fandom.com/wiki/Where_Two_Paths_Converge?diff=373526&oldid=373525 says that the Shadows have very low HP and that a Blizzard 3 should 1-shot them. https://youtu.be/FxmLDVkMcMs?t=81 shows a fight from retail where a Thundaga 3 of 1011 damage 1-shot them. I did a 1082 Thundaga 3 here and they went down to about 90% HP. 

Also of note - Easily slept them, which is the only way I'm gunna be able to beat this fight since they have over at least 10x the HP they should have.

**Comment by InoUno** [comment]
Resolved in December 28, 2020 patch.
