### ISSUE TITLE
Double Fire Weather dont Procc Summoner Flag quest

### ISSUE THREAD

**Issue by ElectroNicMan83** [EdenServer/community#3104]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
I been able to complete the summoner quest, but for some reason some of the weather cutscene didnt trigger. 
- On those 7 I had 3 that didnt process and I had to assume It worked.

**Comment by Slamm21** [comment]
Closing, this guy already had fire complete
