### ISSUE TITLE
Iron Chainmail/Scale Armor Claim Slip Mixup at the Armor Storage NPC

### ISSUE THREAD

**Issue by tengokujin** [EdenServer/community#3105]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver: 20181205_0

When storing the Iron Chainmail set (lv 24), the NPC gives you an Iron Chainmail Claim Slip.
![edenxi_2020-07-16_22-13-12](https://user-images.githubusercontent.com/55920387/87741325-3bd2d380-c7b2-11ea-8888-3d1b7e033f49.png)

However, when you attempt to withdraw the set, it is not under the lv 24-30 sets of armor, but under the 31-40 sets, as Iron Scale Armor.
![edenxi_2020-07-16_22-13-38](https://user-images.githubusercontent.com/55920387/87741378-66bd2780-c7b2-11ea-9889-8fe944291514.png)
![edenxi_2020-07-16_22-13-59](https://user-images.githubusercontent.com/55920387/87741385-6a50ae80-c7b2-11ea-9acd-c88c7eea66ab.png)

**Comment by KnowOne134** [comment]
Fixed in today's update
