### ISSUE TITLE
VoS & Qufim Island not triggering SMN unlock quest

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3107]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Per https://ffxiclopedia.fandom.com/wiki/I_Can_Hear_a_Rainbow, Valley of Sorrows should trigger AT LEAST wind weather for the quest. On Eden, it doesn't count whatsoever. I believe that all weather in VoS (Clear/Wind/Fire) should trigger. It's just not documented because on retail, VoS and Cape Terrigan share the same weather so for you to get the weather trigger in VoS you'd have to be in Cape Terrigan when weather changed, then zone into VoS. 
Qufim Island is also supposed to count for Lightning weather. I know that https://ffxiclopedia.fandom.com/wiki/I_Can_Hear_a_Rainbow?oldid=369408 doesn't state as such, but later on the page gets further updated to state that you have to zone out of Delkfutt's tower to Qufim for the lightning weather to count. I'm not surprised that this wasn't figured out until later on because Qufim typically has lightning so you'd have to zone into Qufim when there wasn't lightning, zone into Delkfutt's Tower, then zone back into Qufim when lightning weather happens.

**Comment by KnowOne134** [comment]
looked through the dats for the 3 zones on the wiki listed and found 0 cs data involving Carbuncle, or the doll, also went in to the dats to look for npc id data and same there which leads me to believe that players posted this info as false. Can reopen if any tangible can be brought to light
