### ISSUE TITLE
K/Behemoth and turtle spawn altered and incorrect after some patch

### ISSUE THREAD

**Issue by him911** [EdenServer/community#3108]
Right no K/Behemoth only spawns in the far north east corner of the zone. It had a somewhat accurate spawn area then a patch or two ago it was changed to a single corner of the zone.Same issue with turtle.  wtf is going on
### Checklist

- [yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ yes] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by 59blargedy** [comment]
spawn points were adjusted to match ffxidb spawn points, but to be fair im unsure if behemoth spawn area was generated post-??? change as it does seem strange to me that they are bunched in the corner.  if someone has some accurate old ls self-mapped data or some other clear proof of a different spawn area in era, please comment on this issue and we'll reopen and adjust. turtle spawn points are fine.
