### ISSUE TITLE
Magnet knife not working?

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#3109]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I haven't seen my Magnet Knife proc gravity on mobs even once.
I'm basically taking -eva with no benefits.

**Comment by 59blargedy** [comment]
Resolved with 8.16 patch
