### ISSUE TITLE
Puppet claim stay white.

### ISSUE THREAD

**Issue by ElectroNicMan83** [EdenServer/community#3110]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Claiming with puppet leaves mob white and allow other to land their spell. 

In a matter of a 3 seconds Dia Cast  - Deploy - Provoke both puppet and someone else Mob stayed white for a while. Mob casted spell on puppet first since he got claim first but mob stayed white.

**Comment by 59blargedy** [comment]
this is correct behavior from attachments, automaton spells or ranged attacks. what isn't correct is enmity attached and that still needs to be addressed per https://github.com/EdenServer/community/issues/2758
