### ISSUE TITLE
Shock Spikes OP against ZM8

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#3112]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver: current

So I were out helping someone with Kam'lanaut fight. 
Was going nice and slow as pld rdm rdm. 

Then suddenly I got hate and kam'lanaut hit me. 
He instantly died.

Shock Spikes had done 16k damage to him.

**Comment by Balrahn** [comment]
![kamlan](https://user-images.githubusercontent.com/12987658/87850532-49db3e00-c8f1-11ea-8f1a-56570a7eadfd.JPG)

**Comment by Balrahn** [comment]
Looking through the log, kam hit me twice. Shock Spikes did 8dmg on the first hit. then 16k on next.
He had used fire blade beforehand. It was dispelled, and dispel said it removed enblizzard, should have been enfire? There were no enspell effect when I got hit.

**Comment by InoUno** [comment]
Resolved with March 15th, 2021 patch.
