### ISSUE TITLE
Imperial Ring not functioning.

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#3113]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver. 30181205_0

I'm sure you guys are working on the general code for these kinds of items like in #2983 , but I noticed Imperial ring also wasn't working.  This should work in both Assault and Salvage.

https://ffxiclopedia.fandom.com/wiki/Imperial_Ring

There are other items that I'm sure you'll need to apply these new conditions too as well, but I can't confirm if they work yet.

https://ffxiclopedia.fandom.com/wiki/Storm_Loop

https://ffxiclopedia.fandom.com/wiki/Storm_Gages

https://ffxiclopedia.fandom.com/wiki/Storm_Shield

https://ffxiclopedia.fandom.com/wiki/Storm_Zamburak

https://ffxiclopedia.fandom.com/wiki/Storm_Ring

https://ffxiclopedia.fandom.com/wiki/Storm_Crackows

https://ffxiclopedia.fandom.com/wiki/Storm_Cape

https://ffxiclopedia.fandom.com/wiki/Storm_Sash

https://ffxiclopedia.fandom.com/wiki/Storm_Belt

https://ffxiclopedia.fandom.com/wiki/Storm_Muffler

https://ffxiclopedia.fandom.com/wiki/Storm_Mantle

https://ffxiclopedia.fandom.com/wiki/Storm_Scimitar

https://ffxiclopedia.fandom.com/wiki/Storm_Earring

https://ffxiclopedia.fandom.com/wiki/Storm_Torque

**Comment by KnowOne134** [comment]
Already have a pending fix in place

**Comment by Mozzy4Ever** [comment]
We sure this got fixed? Had ring on outside of zone and some slow gear on. Ni had a 47 second recast. Entered assault and Ni still had 47 second recast with same gear.
