### ISSUE TITLE
Wyrm Mail not correctly adding subjob traits to Wyvern

### ISSUE THREAD

**Issue by MB213** [EdenServer/community#3114]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

Steps used to test:

1. Equip Wyrm Mail as 75DRG/37WHM
2. Use Call Wyvern
3. Equip Drachen Brais in leg slot, which adds +10% Wyvern HP. This puts Wyvern at 91% HP.
4. Wyvern should get Auto-Regen job trait from WHM sub, but its HP stays at 91%. 

I tried zoning many times with the Wyrm Mail equipped to see if that fixed the problem but it didn't. 
Briefly tested /SAM too and Wyvern wasn't granted the Store TP trait - TP return was 83 per hit with or without Samurai subjob. 

Worth noting for any fix that the job traits should stay on the Wyvern until you zone, dismiss or it dies, even if the mail is unequipped.

**Comment by rude-jerk** [comment]
Created Topaz PR https://github.com/project-topaz/topaz/pull/990 to add this effect

**Comment by 59blargedy** [comment]
resolved oct 4, 2020 update
