### ISSUE TITLE
Adamantoise/Aspid  have an incorrect spawn point

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3115]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

At some point in (recent) time, Eden's HNMs were changed to spawn in their era-accurate locations. From what I can tell, the FFXIDB maps were used for their spawn points.
Adamantoise/Aspid: 
http://ffxidb.com/zones/128/adamantoise (Double-click on the map to zoom in and see the spawn points)
![image](https://user-images.githubusercontent.com/11255886/87875750-04724b80-c999-11ea-90ff-6d0568d9a57a.png)
The spot circled is currently an active spawn point and is not supposed to be., That's where the ??? to force-spawn Turtle is on retail and is why it shows as one on the FFXIDB map.

**Comment by 59blargedy** [comment]
i just doublechecked the points and dont have one this far south for either mob. may have been changed in an update
