### ISSUE TITLE
Ranged attack from mobs does way too much damage.

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#3116]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver: current

A while back I posted a photo on the discord of a Hydra in dynamis hitting me with a ranged attack for 900dmg. 
Today I were fighting a Tonberry Stabber which was easy prey to me on a lvl 74 thf. This Stabber kept hitting me for 450dmg. This is insanely high damage, and can in no way be era or how it has ever worked.

![ucerealm8](https://user-images.githubusercontent.com/12987658/87877299-c5b2b480-c9dd-11ea-9fdc-a9b4299c90d2.JPG)

**Comment by danismyhero** [comment]
Keep in mind we are pre-Ranged Attack nerf.  So while that may be too much damage, they should be doing more damage than what you are used to in era.

**Comment by Balrahn** [comment]
Looking through the logs and I can see that I had been hit with Lateral Slash which lowers my defense by 75%. Not sure how the maths work on this, so perhaps 450dmg is correct?

**Comment by Mozzy4Ever** [comment]
I mean, range attacks from mobs definitely do high damage. But I'm pretty sure that's an issue with pDif which should be mitigated (if not fixed completely) when pDif is finished.

**Comment by Slamm21** [comment]
that's correct

**Comment by Raphtalia1** [comment]
Pdif from mobs is way too high atm, ranged attacks are hitting for way more dmg than they should due to this. even after pdif changes ranged attacks from mobs will still likely do too much dmg, but that will be because of other issues that are planned to be addressed in the future
