### ISSUE TITLE
Sea torque drop rate appears to be low

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#3118]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

My linkshell noticed that the jailers weren't dropping torques very often, so I started keeping track of our drop rates. Currently we're 7/59 on tier 2 jailers(4/20 on Hope, 2/19 on Justice, 1/20 on Prudence). Hope is right about where you'd expect it to be but 3/39 on the other two is unlikely. I don't have the T1 jailer data on hand but they were also low. Input from other groups for more data points would be appreciated as well!

**Comment by Slamm21** [comment]
our ls is 2/16 also
so between the two that is 9/75, 12% which is closer to the 8% mark than 18% with TH4.
I know these sample sizes are not huge, but perhaps we can get some numbers from other shells to see how things are looking?
Tinfoil but maybe there are certain situations where TH is lost on the mob somehow.

**Comment by VirtuosusFFXI** [comment]
1/12 on Jailer of Faith here.

**Comment by icariumkupo** [comment]
0/10 on justice here

**Comment by setsuk0** [comment]
^ What Ica said. I don't have exact numbers for our linkshell. I thought we had gotten a justice torque when I spoke with Slamm, but I was incorrect. It seems like we are about 0/10 on that one, 1/10+ on prudence, and 2/10+ on Hope. 

We have groups that low-man the tier 1 jailers, but for what I've actually attended, I've seen 0/7ish on Faith, 0/8+ on Fortitude, and 2/6+ on Temperance.

**Comment by 59blargedy** [comment]
rarity is set appropriately for sea torques per retail testing, ffxidb and wiki comparisons. unfortunately, sea has never been great for drops.
