### ISSUE TITLE
Bloodsucker NM spawning too quick.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#312]
We killed him last night, came back in the morning and he was up.  Camped Sewer Syrup for a couple of hours, came back downstairs and he had already respawned.  I don't know how fast he respawned in era, some people in LS said it was supposed to be a long respawn though.

**Comment by MGramolini** [comment]
https://ffxiclopedia.fandom.com/wiki/Bloodsucker_(NM)?oldid=398619
Says 21-24 hours after maintenance OR 72 hours after last kill.

Icarium has info from retail era that he says is more accurate.
0-3 hours after maintenance OR 69-72 hours after last kill.
