### ISSUE TITLE
Evil Weapon Family - Smite of Rage

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3121]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently when Evil Weapon mobs use Smite of Rage, it's a multi hit move (might be 3-hit) instead of being single hit. Maybe it might be using the NM version Flurry of Rage? Unsure if the BLU spell is like this as well.

![image](https://user-images.githubusercontent.com/46270382/87967774-598f8980-ca8d-11ea-8630-1d926186c8a9.png)
https://ffxiclopedia.fandom.com/wiki/Category:Evil_Weapons
https://www.bg-wiki.com/bg/Smite_of_Rage

version 30181205_0

**Comment by tengokujin** [comment]
Don't AoE attacks wipe all shadows?

**Comment by Mozzy4Ever** [comment]
Not always, no. However Smite of Rage is supposed to be a single-target TP move.

**Comment by 59blargedy** [comment]
fixed by august 9 update
