### ISSUE TITLE
Character keeps logging in dead

### ISSUE THREAD

**Issue by marlinla** [EdenServer/community#3123]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I keep logging dead on my new character Pororo. I also seem to die every time I zone.

version 30181205_0

![image](https://user-images.githubusercontent.com/18357827/88059862-6e265d00-cb33-11ea-9d5c-a3550fbf34af.png)
![image](https://user-images.githubusercontent.com/18357827/88059919-84ccb400-cb33-11ea-934d-bc82a57b24cb.png)
![image](https://user-images.githubusercontent.com/18357827/88059993-9b730b00-cb33-11ea-8532-c9c4dd925cb4.png)

**Comment by marlinla** [comment]
This needs a system message to avoid wasting peoples time.

Like just say we killed you cause your doing something wrong.

**Comment by bkesecker** [comment]
This is intentional.  Raise your character and warp it out.

**Comment by marlinla** [comment]
The issue is not if it's intentional or not, I know it is not a bug. The issue is that it the action (slaying the player) did not stop me from identifying or complying with new security policies. I've dragged level 1 characters out Kazham before.

**Comment by bkesecker** [comment]
I still don't understand what you are trying to identify as broken.  The details of these counter measures are not something we should reveal.
