### ISSUE TITLE
Boroka dmg

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3124]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Seem to hit around 300-500 on hoof volley wich is not what is expected. I assume from wiki it should one shot the non blink tank.

Wiki :
Uses "Hoof Volley" (critical single-target damage attack that resets hate) after all of its special attacks. Very rarely can also use it without doing a special attack prior.
A tank capable of using Blink or Utsusemi is recommended, **as direct physical damage from "Hoof Volley" is likely to be too high.** ("Fantod" + "Hoof Volley" is recorded to deal over 2100 direct damage!)

**Comment by ThrisStraizo** [comment]
It will do 300-500 on a fully defensed up tank without fantod up.   But It's def one shotted me as a galka as a non tank, doing 900+ damage.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
