### ISSUE TITLE
The new Stay fix did not carry over to charmed mobs

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#3127]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I charmed and familiared a 78 Puk and tried to regen some of his health with Stay but it was going at the slow rate. not the rate jug pets are currently getting.

**Comment by 59blargedy** [comment]
this should be resolved as of august 9 patch
