### ISSUE TITLE
Greatsword WS Shockwave audit

### ISSUE THREAD

**Issue by danismyhero** [EdenServer/community#3129]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

This is more precautionary than anything, but the weapon skill additional effect seems too good.  It's accuracy is extremely high and duration very consistent.  Could be based off the 2017 revisions (http://forum.square-enix.com/ffxi/threads/52747?p=597349#post597349).

https://youtu.be/6okVEQQjgHU

Here's a video in Sea Grotto of the sleep in action, these are EP at 75.  I didn't take a video of it but it does the same to Even Match and Tough mobs in Sea.

https://www.bg-wiki.com/index.php?title=Shockwave&oldid=270946

"Sleep duration seems to have some non-typical variability. Listed values were the maximums observed in a short test, but they typically varied between 50% of the value and the maximum value.

    Sleep effect is dark based and overwritten by Sleep II.
    Sleep effect is currently very inaccurate on the real servers. "

Maybe this is how it should be, maybe it isn't just didn't quite seem right so letting you all decide I didn't use this in retail era.

**Comment by roriffxi** [comment]
I tested this on some VT mobs (Spinner in Mamook) and was getting 20-40 second sleeps.  Looks like duration depended on the amount of dmg dealt.  Low amount of dmg = shorter duration, higher dmg = longer duration.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
