### ISSUE TITLE
Relic Aftermath effect should apply to the initial WS that adds the buff

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3130]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

This means that a player who does a Tachi: Kaiten with no aftermath up should still see Store TP +7 applied to it. In other words, aftermath effects should be applied before the weapon skill is even calculated.

This affects the following:
 
Guttler - Onslaught (+Attack)
Mjolnir - Randgrith (+Accuracy)
Yoichinoyumi - Namas Arrow (+Ranged Accuracy)
Amanomurakumo - Tachi: Kaiten (+Store TP)
Annihilator - Coronach (-Enmity)
Spharai - Final Heaven (+Subtle Blow)
Kikoku - Blade: Metsu (+Subtle Blow)

Proof from testing done on retail, courtesy of ccl:

No Aftermath:
Tachi: Fudo - 228 TP Returned
Tachi: Kaiten - 237 TP Returned

Aftermath:
Tachi: Fudo - 237 TP Returned
Tachi: Kaiten - 237 TP Returned

Tachi: Fudo with no aftermath on:
![Fudo](https://user-images.githubusercontent.com/49970272/88311706-3d832680-ccdf-11ea-83bc-baf493ed9a09.jpg)

Tachi: Kaiten with no aftermath on:
![Kaiten](https://user-images.githubusercontent.com/49970272/88311753-4bd14280-ccdf-11ea-913f-71c08b15244f.jpg)

**Comment by icariumkupo** [comment]
I believe this should grant the user aftermath even if the WS misses. The aftermath should apply when the user "readies" the weaponskill. Prior to weaponskill hit. 

Currently if, for example, an Apocalypse user misses with Catastrophe, aftermath is not granted.

**Comment by VirtuosusFFXI** [comment]
Good point. Will ask for them to test for this as well.

**Comment by VirtuosusFFXI** [comment]
Can confirm that should also be the case. They were able to use relic WS on a Perfect Dodged NM, which results in a miss but received Aftermath status effect.

**Comment by 59blargedy** [comment]
the majority of this was solved some time ago - i seem to recall we were leaving it up for a small fraction of an issue, but since i cant remember what it is it's probably better to file a new report with any issues remaining. the aftermath currently applies during the ready phase which then includes the ws itself, and occurs regardless of hit/miss.
