### ISSUE TITLE
Sheep in Antlions Clothing should have more than 1 "slot" for weapon/mantle drops

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#3131]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Currently it seems that the ENM Sheep In Antlion's Clothing only has 1 slot where the weapons & mantle can drop.

There should be at least 2, if not 3, slots with equal weighting for this.

This can be seen in the table on the main FFXI wiki as well as being discussed in 2010 within the talk page. 

To the best of my knowledge there wouldn't have been any updates to these ENMs to increase the number of items dropped by them.
https://ffxiclopedia.fandom.com/wiki/Sheep_in_Antlion's_Clothing
https://ffxiclopedia.fandom.com/wiki/Talk:Sheep_in_Antlion%27s_Clothing

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
