### ISSUE TITLE
Eo'Ghrah are still not treating Sheep Song as being light based

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3132]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Light based Eo'Ghrahs are NOT immune to sheep song and should be, and Dark based Eo'Ghrahs are immune to BOTH Sheep Song and Soporific (didn't test Yawn)

version 30181205_0

**Comment by KnowOne134** [comment]
👍 let me know of any other mobs tht need the new light base immunites or resistances

**Comment by E5una** [comment]
Just an update here, all dark elementals are also immune to sheep song / yawn. This is extremely relevant for the top floor of Temenos East since it kills solo runs :(
