### ISSUE TITLE
Jailer of Temperance not using Optic Induration

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3134]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

vershion 30181205_0

Jailer of Temperance should be using Optic Induration, a high damage conal tp ability that inflicts petrification and resets hate, but it never uses it. I've killed the jailer 9 times without it using this ability, and I've heard the the same from other linkshells. This is changing the fight pretty significantly by removing its highest damaging, and scariest move, as well as removing its move that resets hate.

From the wiki:

"Most dangerous in Blunt mode, when it can use Meikyo Shisui + Optic Induration to petrify most of the alliance.

Optic Induration resets hate."

I also want to note here that when normal Zdei use Optic Induration, it completely breaks them and disables their attacks (even after they respawn). I'll link my other bug report for that.

This is sort of covered in another ticket that lists various problems with Jailer of Temperance, but some of those were addressed, so I though maybe it was best to break this off into its own ticket and reference the other ticket.

**Comment by E5una** [comment]
https://github.com/EdenServer/community/issues/2869 is the parent ticket that references a variety of Jailer of Temperance problems, some of which are fixed and some of which are not, so I created this ticket for a specific issue.

https://github.com/EdenServer/community/issues/2876 is another ticket I commented on that references the Zdei family not having this ability working properly for them, since it causes their auto attacks to be disabled.

**Comment by 59blargedy** [comment]
fix put in august 9th patch, comment if this continues to be an issue
