### ISSUE TITLE
Excavation Duty Issues

### ISSUE THREAD

**Issue by Blex64** [EdenServer/community#3135]
### Checklist
- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver 30181205_0

Lebros Cavern Assault Excavation Duty had some issues pop up today:

- When engaging the rock, none of the parties were able to see each other. We were still able to cast on each other.

- Rock did not show as engaged, and we could not see its health going down

- Rock DID take damage, and was eventually defeated. HOWEVER, the rock did not "break" and we've been unable to progress further:

![brokenrock](https://user-images.githubusercontent.com/15820441/88487974-023f5c80-cf58-11ea-91c3-fe32ee16027c.PNG)

**Comment by Shoruto** [comment]
Additional Excavation Duty report #3228

**Comment by KnowOne134** [comment]
1st time hearing this, and cant duplicate issue. respond if still occurs
