### ISSUE TITLE
A player's attack delay rarely will get randomly set to 0

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3137]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I've heard of this happening to others in the last week to two weeks, but I got the "hundred fist bug" today where suddenly my attack speed had no delay. It persisted through gear swaps, weapon swaps, and resting. I'm not sure what caused it, but I didn't do anything out of the ordinary. Sorry for the lack of information, I just wanted it documented so people can add to the report. I would have uploaded more screenshots but had to log out for maintenance.

![image](https://user-images.githubusercontent.com/13668758/88554586-b0004900-cff4-11ea-8c8a-8d3d589d0497.png)
![image](https://user-images.githubusercontent.com/13668758/88554607-b42c6680-cff4-11ea-8b9e-8994d2f6a115.png)

ver 30181205_0

**Comment by E5una** [comment]
Happened again to me today. I'm not sure what to say other than my log isn't very helpful. I logged in, starting fighting one mob, got a link, and did a lot of spell spamming so its really hard to notice when the bug actually starts because I'm linking spells back to back. What IS relevant is that after resting for some time my attack delay went in the opposite direction and I had a delay of 32 seconds between auto attacks with a weapon with 213 delay (I might have had haste on, not sure). A few min later I had hundred fists again. A few min later I was back to normal attack speed, so I don't have any helpful leads here other than the fact that I staff swap A LOT when I'm fighting, but I always have and haven't had this bug.

**Comment by Arzehn** [comment]
Had the same bug occur. 
![image](https://user-images.githubusercontent.com/69144694/89168334-93529c80-d531-11ea-9166-6a1f21777b96.png)
![image](https://user-images.githubusercontent.com/69144694/89168385-a6fe0300-d531-11ea-9234-8878ff96607d.png)

Fixed itself after a few mobs, i did alt tab out to try to record but when i came back in and tried to fight a mob it stopped. I did "switch target" to choose another non-moving target when it did resolve. Not sure that has anything to do with it.

THF35/RNG1 Using Centurion's sword
8/3/2020 2:05AM PST

**Comment by lokpoki** [comment]
Same thing happened to me. It occurred right after I used Steal and lasted for a minute. 

THF6 Using Onion Sword at 9/8/2020 13:46:16 EST

![image](https://user-images.githubusercontent.com/70973059/92512051-35723e00-f1dc-11ea-9e26-8cfae2a9bd4a.png)

**Comment by DrfistMD** [comment]
Had this happen to me when I switched gear sets in the middle of a fight, I did go from a dual wield setup to a 1H and shield setup and then suddenly I was stuck attacking with 0 delay until I zoned .

![Xerox_2020 09 10_034855](https://user-images.githubusercontent.com/46073012/92696883-90a94b00-f318-11ea-8bfb-20118771be11.png)

**Comment by bkesecker** [comment]
@DrfistMD @lokpoki Did this happen to you after Sept. 6th patch?

**Comment by DrfistMD** [comment]
Yes, this happened just this past night Sept 9 / morning of Sept 10.

**Comment by lokpoki** [comment]
Yeah it happened on Sept. 8th around 13:46:16 EST

**Comment by lokpoki** [comment]
This just happened again to me while I, a level 18PLD/7War, was fighting Gobs/Wind Bats in King Ranperre's Tomb. I was using a sword shield combo. This is slightly different as the second strike lands for an insane amount of damage, from 54046-64989. Also it seems to think I am was a Greatsword, when I had sword/shield equipped, as it was granting me Great Sword skill points. This happened on September 25 5:27 PM EST and lasted for a minute.

![image](https://user-images.githubusercontent.com/70973059/94317786-fa4e6980-ff54-11ea-8f9f-e86f05d19b64.png)

**Comment by bkesecker** [comment]
54046 in binary is `1101 0011 0001 1110` with the most significant bit to the far left.  However, `0001 1110` is 30, which is the damage that was supposed to be inflicted, but the higher order bytes ended up being garbage.  How it became garbage is one of the things needing to be solved.

**Comment by E5una** [comment]
Probably not helpful this far into the investigation, but wanted to mention that you don't get TP when "Eden Hundred Fisting" :)

**Comment by InoUno** [comment]
At least the "hundred fist" part of this bug report should be resolved with December 21, 2020 patch. The same bug may also have caused the high damage output, so it might have been fixed too.

Please reopen/comment if it happens again.
