### ISSUE TITLE
Simurgh is not era-accurate

### ISSUE THREAD

**Issue by Corvinus1337** [EdenServer/community#3139]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently Simurgh is soloable on Eden as THF/NIN even within the rage timer if geared properly. This is not era accurate as Simurgh was much harder to solo on retail. Part of the problem is that his accuracy on Eden is based on his level (58) when on retail it had at least ~90% accuracy even against an evasion-geared THF at lvl 75. Here are some examples from wiki:

![wiki](https://user-images.githubusercontent.com/61441566/88602477-dea41100-d040-11ea-994c-7d25976d7d7a.PNG)

**Comment by bkesecker** [comment]
Are you saying you forced Simurgh to rage state after the last patch, and were still able to solo?

**Comment by Corvinus1337** [comment]
No, I'm saying Simurgh's accuracy is way too low right now, on retail the accuracy was high enough that it was impossible for a THF or practically any job to solo it. 

The rage thing is a separate issue as right now a THF can hit hide and it will reset the rage timer (on any non-true sight/sound HNM) as long as no one else is on the hate list. Iirc on retail you had to let the HNM get 1 tick of HP at least + have no one on hate list before its rage would reset.

Currently both of the aforementioned issues are at play.

**Comment by Rikoooooo** [comment]
I believe the drop rate of Strider's Boots should also be taken in to consideration of not being era-accurate. While camping this for 20 days in a row, zero have dropped. This is a small sample size I know. But I've encountered someone that camped it for 2 months and only got 2 pairs of Boots. I believe the Boots are categorized as "Rare", perhaps they should be categorized as "Uncommon".

On retail I don't remember a month going by where people wouldn't get at least 2, possibly 3 pairs in a month. XIVDB that I know you occasionally use for drop rate accuracy shows it being at least around 20% drop rate with 0 TH. Which moves it further into more of a "Common" category. But to be honest, SE could have changed it over time, so who knows. I'd settle for it being place into the "Uncommon" category lol.

Thanks for reading~

**Comment by Corvinus1337** [comment]
This was audited and actually, the current categorization of '**rare**' is retail accurate. The confusion happens because SE bumped up the drop rate later on, but that was post-era, which does not apply to Eden.  

It sucks but it did take me 40+ kills to get my pair as well (;_;). Regardless, the current drop rate is accurate.

**Comment by Rikoooooo** [comment]
If this took you 40 kills to see a pair drop then it further proves my point that there is something wrong with the "Rare" category. You would have a base 5% chance, bumped up to 7% with TH2. You should have saw boots way sooner or potentially have had 2 drop within that amount of time. I understand that tracking drop rates/RNG can be hard and has the potential to vary greatly, but this does not seem accurate enough in my opinion.

**Comment by Mozzy4Ever** [comment]
> If this took you 40 kills to see a pair drop then it further proves my point that there is something wrong with the "Rare" category. You would have a base 5% chance, bumped up to 7% with TH2. You should have saw boots way sooner or potentially have had 2 drop within that amount of time. I understand that tracking drop rates/RNG can be hard and has the potential to vary greatly, but this does not seem accurate enough in my opinion.

That's not how RNG nor drops work

**Comment by Rikoooooo** [comment]
Clearly, but I still see an issue somewhere. lol

**Comment by 59blargedy** [comment]
resolved december 7 update.
