### ISSUE TITLE
Windy mission 7-2 bugged

### ISSUE THREAD

**Issue by Nastynutsu** [EdenServer/community#3140]
![Nutsu_2020 07 28_190633](https://user-images.githubusercontent.com/67473538/88652966-6ef85980-d106-11ea-9148-56b681ddf0be.png)
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### After Cursed key cutscene, I did not get "Book of Gods" KI and Leepe-Hoppe won't give me my rank 8.

see attachment, for mission 7-2 dialog.

**Comment by 59blargedy** [comment]
did not see an issue in the code when fixing other bugs, most likely this was a one-off variable issue solved by GM
