### ISSUE TITLE
Bronze harness Price Incorrect

### ISSUE THREAD

**Issue by ZionGaius** [EdenServer/community#3142]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Bronze Harness Price from Miogique in Southern San d'Oria(K-8) is incorrect should be g230-268 currently 576 with rank 9 fame.

Thank you for your time Zion, Gaius, Slammnation
![Gaius_2020 07 30_162036](https://user-images.githubusercontent.com/69005200/88941212-a5f27a80-d280-11ea-9d10-33570e60c700.png)

**Comment by 59blargedy** [comment]
resolved
