### ISSUE TITLE
Assault Imperial Agent Rescue

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#3143]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Did 2 failed attempts. 

The door at I-9 is working fine and both weapon throws and fire spits are hitting the door.
On J-9 it seems to be random. Seen firespit miss and hit the door with tank and mob is in the exact same position on both hit and miss.
In our case the mamool missed the door more often than hitting it. 

Did not get as far as to try the door at J-7/8

**Comment by KnowOne134** [comment]
Its random if it hits the door or the player. Rng. If you mean the points added up to supose to open the door and it didn't then thats a failing door and needs to be reopened. As I read it now sounds like normal play
