### ISSUE TITLE
Demon mob family movement speed incorrect

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3146]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Era page states "Naturally Enhanced Movement Speed", it's more defined on May 15th, 2008 (https://ffxiclopedia.fandom.com/wiki/Category:Demons?diff=next&oldid=508827) to show +25% movement speed.

Reproducing: 
1) Go to area with demons that's not laggy (Uleguerand Range is perfect)
2) Have flee speed and aggro a demon. It will not only keep up with you, but be able to hit you as well.

Even with funky lag and/or navmesh, it shouldn't be able to keep up with you AND hit you if it only has +25% movement speed when you have Flee.

**Comment by KnowOne134** [comment]
from captures: players has a speed of 40 and Kindread have a speed of 70, tigers 60
