### ISSUE TITLE
Beastmaster Pets linking

### ISSUE THREAD

**Issue by PitBadger** [EdenServer/community#3147]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I don't have a retail account to 100% verify this, but I'm fairly certain that mob BST pets aren't supposed to link to other mobs/other pets.

Normal mobs are supposed to link to aggro'd Beastmaster pets for sure, but I'm pretty certain it isn't the other way around.

The easiest place to replicate this is the two Mamool BSTs on the top level of the Nyzul G Coli camp. If you pull one of the Mamool Ja's Raptors with the other one too close then you'll get both coming down to see you.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
