### ISSUE TITLE
Alkyoneus Claim Shield

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#3148]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Alkyoneus doesn't seem to have a claim shield. I'm looking for confirmation and requesting it be added.

**Comment by VeilEden** [comment]
I can’t find the patch notes by SE that list claim shield being added. But I don’t think Alky ever had it added. I believe it was just Wyrms, ToAU Kings, ground Kings, and KA. Those are the only names I see mentioned in forum discussion. The RMT/bot fix for smaller NMs wasn’t added until much later when many NMs went to force pop through items. (see: Ulli with Diorite)

**Comment by Mozzy4Ever** [comment]
I mean, doesn't mean it shouldn't have it on here... Anti-cheat shouldn't be a "It's not era" thing

**Comment by VeilEden** [comment]
Sure. I don’t disagree. But where do we stop with this? All NMs? Only the ones people special request? Do we put it on anything contested? Additionally, a side affect on doing it to smaller NMs is that you’re effectively putting any job that isn’t a mage(Rdm specifically), or THF/WAR at a disadvantage. Do we put it on Simurgh to give the guy solo camping a better chance against the merc group who sells them? Stuff the think about.

**Comment by Mozzy4Ever** [comment]
Personally I think anything that checks as "impossible to gauge" should have it. I fail to see how claim shield favors one job over another. If anything, it allows all jobs to have an equal chance instead of just the person closest to the server who has an instant-claim (provoke, charm, etc).

**Comment by dowzer** [comment]
I’m still searching BG Update History. By memory, it applied to all monsters, not only NMs. An example being the Spook in KRT, even it has a shield.

**Comment by VeilEden** [comment]
I mean, all monsters would mean it applies to exp camps, which was never the case. And @Mozzy4Ever, it gives everyone an equal chance to try once, and is more forgiving if you chose to stand in the wrong spot on a broad area pop. The jobs I listed have a much higher claim rate because they get more opportunities. Ranged + Fast Cast or Chainspell, or Flee + 3 instant JAs. I mean we’ve all seen that at KA dozens of times.

**Comment by dowzer** [comment]
It applied to every monster, even on placeholders and exp mobs.

https://ffxiclopedia.fandom.com/wiki/2005_-_(08/1/2005)_Update_Details

> - Players will no longer be able to use spells or abilities to claim a monster as soon as it appears.
> - If players attempt to use spells or abilities to claim a monster before a set amount of time has passed since it appeared, they will not be able to use those spells etc. again for a certain duration. 

If it's too large of an overhaul to apply on every monster, at the least it should apply to all that are Impossible Gauge, as Mozzy suggested. Ideally, it would reflect the era appropriately applying to every monster.

**Comment by Slamm21** [comment]
definitely applied to every monster.
Agree here that it should just apply to all NMs

**Comment by VeilEden** [comment]
Weird. I have no recollection of ever being claim shielded while meriting. And you typically provoked on pop if the puller was preoccupied.

**Comment by dowzer** [comment]
Well, for one thing, your list of NMs was wrong. It wasn’t a select few HNM.

I camped Rogberry before the patch. After the adjustment it definitely had a shield and so did the Pursuer PH.

**Comment by Goto28** [comment]
Can we please get a claim shield on this NM? There is a suspicious player questionably claiming Alky, without the shield it's basically impossible to beat them as by the time you even able to scroll through all the surrounding shit to target Alky, it was claimed 2 seconds ago. 

As for prior discussion it is a fact that all enemies on retail had a claim shield, I remember this from when camping lord of onzozo it's PH had a shield which I would hit often from spamming from menu. Also Leshy in Lufaise Meadows.

**Comment by ThoseWhoFight** [comment]
In addition to Alky, Pallas also seems to have no claim shield. Whenever this gets changed, I would highly recommend adding more spawn locations, because as it currently stands both NMs spawn in the exact same spot every time. Not fun from a competitive standpoint. If there were more spawn locations, you pretty much wouldn't even need a claim shield.

**Comment by him911** [comment]
From what i hear only one persons been claiming alky for awhile now and its claimed before anyone can target it, havent been there in a longtime to verify

**Comment by ThoseWhoFight** [comment]
> From what i hear only one persons been claiming alky for awhile now and its claimed before anyone can target it, havent been there in a longtime to verify

Is this really the place for salt posting about losing claims? Surely that is what the help desk in-game is for if you feel a player isn't playing fairly despite you apparently never having been yourself.

**Comment by him911** [comment]
This entire thread is about alky claim shield dude lol

**Comment by Elysien** [comment]
If the likes of Mee Deggi the Punisher has a claim shield, there is _**zero**_ reason Alkyoneus, carrying a hand slot item worth 10 million gil or so, shouldn't have. Needs a claim shield desperately, or it will become a prime target for shorthand abusers, or whatever else is out there --- if it hasn't already.

**Comment by 59blargedy** [comment]
resolved with 9/6 update
