### ISSUE TITLE
Jailer of Justice adds blowing up for zero damage

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#3149]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
ver 30181205_0
### Details

The adds for JoJ are really undertuned here, they are blowing up for 0 damage

**Comment by 59blargedy** [comment]
should be resolved by 8/9 patch, comment if otherwise
