### ISSUE TITLE
Cant create character

### ISSUE THREAD

**Issue by Ssinz7965** [EdenServer/community#315]
trying to create a character ingame but im constantly getting the japanese error code on name creation. im guessing this is something to do with my IP and such so im hoping to get assistance from developer team to create me the following:

Hume
Model: Blonde Pony Tail
Size: Large
Name: Ssinz

I have the username and password. please message me privately and ill provide it.

**Comment by godmode** [comment]
The tech-support channel probably has the answer you need if the following doesn’t work. https://discord.gg/uKgpypT

But I imagine you’re trying to use a name that’s already been selected. You can try to search for it and see if it already exists by using the player search function on the website.

**Comment by Ssinz7965** [comment]
thanks for the swift reply!!

altho i tried other names and also the autogenerate name but it doesnt seem to work for me. i feel like its the same issue i had with nasomi. i can connect to the game but someone had to create my character for me. and i dont know anyone yet in the server to trust with my account details. ill try and ask help on the discord link tho. thanks !!
