### ISSUE TITLE
/heal on and /heal off don't function

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3153]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

'/heal on' should never make you stand up. 

Right now typing /heal, /heal on, or /heal off just toggles resting and standing. 

Ver: 30181205_0

**Comment by bkesecker** [comment]
Reference https://ffxiclopedia.fandom.com/wiki/Command/heal?oldid=272861

**Comment by JamesMcMinn** [comment]
I fixed this in LSB as was suggested to me on discord. Perhaps it can get merged into Eden as it would remove a huge annoyance I have with some complex macros: https://github.com/LandSandBoat/server/pull/2647

**Comment by 59blargedy** [comment]
resolved by james mcminn in september 21, 2022 update (thanks for the contribution!)
