### ISSUE TITLE
Spinel Quadav Mage Blood

### ISSUE THREAD

**Issue by Deepupuu** [EdenServer/community#3155]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
ver: 30181205_0

Spinel Quadavs drop Quadav Mage Blood in Beadeaux, they might drop it in other areas too, I dont know.

Only Topaz Quadavs are suppose to drop Quadav Mage Blood.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
