### ISSUE TITLE
Mage's Ballad overwrites Mage's Ballad II

### ISSUE THREAD

**Issue by re1master** [EdenServer/community#3156]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

When casting songs, it appears that Ballad 1 will overwrite Ballad 2 if there is another song currently active (ex: casting Minuet, Ballad 2 and then Ballad - Will result in Minuet and Ballad 1 being the active songs).

version 30181205_0

**Comment by roriffxi** [comment]
The shortest duration song will be the one overwritten.  In your scenario with minuet if you were using a minuet enhancing instrument, the duration left on minuet is likely to still be higher than the duration on ballad2 even though you sang the minuet first.  Which would result in the ballad 2 being overwritten.

**Comment by Slamm21** [comment]
this is how it worked on retail.
