### ISSUE TITLE
Exited Mog House to Wrong <pos>

### ISSUE THREAD

**Issue by Spiffly** [EdenServer/community#3157]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

I zoned into my mog house from Port San d'Oria and then zoned out to South San d'Oria. Instead of exiting outside my mog house, i was loaded at (I-8), directly opposite the Auction House.

I have attempted to recreate this by repeating the above steps but have been unable to do so.

Ver: 30181205_5

**Comment by KnowOne134** [comment]
its due to a poor internet connection or speed while zoning and setting you to pos 0,0,0
duplicate issue is already submitted
