### ISSUE TITLE
Fomor Summoner in Misareaux Coast seems to have the wrong stats

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3158]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I can't speak to others, but the Fomor Summoner at E-7 seems to have the wrong stats. It could be all Fomor SMN, not sure, but he is a Taru SMN and is consistently the last one alive when I AoE down this camp. I always check the logs to make sure he is getting hit by all my spells. I've done this over 200 times and he's always the last to die.

![image](https://user-images.githubusercontent.com/13668758/89446620-c14b0300-d722-11ea-9fe5-4afde1d64b22.png)
![image](https://user-images.githubusercontent.com/13668758/89446657-cd36c500-d722-11ea-8668-a517a4cc7dd0.png)
![image](https://user-images.githubusercontent.com/13668758/89446681-d889f080-d722-11ea-8a88-d3ac5be2a8bb.png)

version 30181205_0

**Comment by E5una** [comment]
Looks like they all have likely the wrong stats. Not sure if they are always the same levels (if the RDM is higher level) but the mithra RDM always seems to outlive the Elvaan Ranger as well.

![image](https://user-images.githubusercontent.com/13668758/98115065-3807b180-1e74-11eb-8d2d-d2f0c96c000a.png)

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
