### ISSUE TITLE
Teleportation to Tu'Lia

### ISSUE THREAD

**Issue by Deepupuu** [EdenServer/community#3159]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
ver: 30181205_0

I did the Teleportation to Tu'Lia Quest and when I used the teleport in Hall of Transference (Crag Mea) with both my characters Deepupu and Imouto, Deepupu arrived dead in Ru'Aun Gardens. Imouto arrived just fine. They are both on game ver: 30181205_0 The only difference was Imouto was full HP and Deepupu was yellow HP. It was the first time using the teleporters for both characters and the clear chips did not break for either character. I typed !re on both characters to make sure I was actually dead, and I was. I had Imouto cast raise on Deepupu and raised regaining some lost xp and receiving the weakened status.

**Comment by KnowOne134** [comment]
pretty sure this was an anticheat measure that has been since removed
