### ISSUE TITLE
Shock Spikes blocking Bloody Bolts effect

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#316]
Not sure if other spikes are doing this as well, so far have only tested on mobs that had Shock Spikes. Shot probably 30 bolts at elementals that had spikes on, no drain whatsoever. Once I found one that didn't have spikes, drain effect worked as normal.

EDIT: Now suddenly the effect is working on mobs that have spikes? Maybe I just needed to zone? Someone in LS said they were having the same issue but after blinking their character (due to lockstyle) it worked for them. I tried that, but I still wasn't able to drain... weird

**Comment by gweivyth** [comment]
This is an issue with lockstyle.  You need to actually have a crossbow equipped when you turn on Lockstyle or it gets funky and doesn't want to apply on-hit effects from bolts.  I've had this happen a bunch of times, it is super annoying.

**Comment by Setz0r** [comment]
Lockstyles with ranged weapons was fixed, but Lockstyles is dead, just like this issue.
