### ISSUE TITLE
Qufim Island - Kraken is incorrectly tagged as a Notorious Monster

### ISSUE THREAD

**Issue by Nyoomy** [EdenServer/community#3160]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Client Version - 30181205_0
The Kraken guarding the Nightflowers in Qufim Island (F-8) currently /checks 'Impossible to Gauge!' denoting it as an NM.
Reproducible steps - Go to Qufim Island, and /check the Kraken that spawns by the nightflowers.
This should be a regular enemy (Too Weak - Incredibly Tough), the NM variant of 'Kraken' in Qufim is the fished up monster.

**Comment by Wade9363** [comment]
I can confirm.  In retail 2004, the Kraken at the night flowers spawn point could be charmed by BST.

**Comment by KnowOne134** [comment]
Fixed in today's update
