### ISSUE TITLE
Optional Followup to BLM AF3 (Hat) Not Triggering

### ISSUE THREAD

**Issue by tengokujin** [EdenServer/community#3161]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Ver: 30181205_0

The optional followup to the BLM AF3 (hat) quest, where you take an Earthen Charm (KI) from Kupipi into the ruins to get some cutscenes does not trigger, despite zoning.

![vs1rNqC 1](https://user-images.githubusercontent.com/55920387/89485973-f9c4fe00-d76f-11ea-8fc5-89e990aa6b0a.png)

![Hjz2sv7 1](https://user-images.githubusercontent.com/55920387/89486096-41e42080-d770-11ea-89b0-724ba47bdebd.png)

**Comment by KnowOne134** [comment]
corrected in the 11/19/2023 update
