### ISSUE TITLE
Bastok 9-2 Where Two Paths Converge Boss has too much hp in phase 2

### ISSUE THREAD

**Issue by tigo9** [EdenServer/community#3162]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

/ver = 30181205_0

Steps to Reproduce:
- Enter "Where Two Paths Converge" battle
- Defeat phase 1
- Notice boss HP in phase 2

### Details

What should happen is you get Zeid below 70% during phase 1, this triggers a cutscene, then you get phase 2 of the fight. At the start of phase 2, Zeid should have the same hp you left him with at the end of phase 1. Around 5:30 in the following video shows this:

https://www.youtube.com/watch?v=ZlqNk1GyNPQ

![hhhd](https://user-images.githubusercontent.com/29804086/89541775-b5c90c00-d7f6-11ea-8279-ddb60f573bd9.png)

Instead what is happening is at the start of phase 2 Zeid is being refilled to full hp:

![Xellotath_2020 08 06_141800](https://user-images.githubusercontent.com/29804086/89541478-54a13880-d7f6-11ea-8306-c62cd5df5cee.png)

Not only is the HP refilling to full, but his hp is doubling, to around 20k. So instead of having around 7k hp left to take off in phase 2, you have 20k.

Additionally, after wiping and re-entering, he will have the bugged 20k hp from the start of phase 1.

**Comment by bkesecker** [comment]
For further reference https://www.youtube.com/watch?v=YZKC5HkjhV0&feature=youtu.be

**Comment by freddiepines** [comment]
Experienced this tonight myself.

The adds in this fight also have waaay too much HP - from my calculations looks like 10k each?  Plenty of accounts on the wiki stating they should have vastly less:

"A well-timed -ga spell can kill both in one hit."
"followed by Thundaga III to wipe Zeid's Shadows as he called them without giving them a chance to attack"
"After the CS MNK 2hr and when Zeid spawned the adds the BLM Thundaga III them. He only got the chance to spawn the adds once"

https://ffxiclopedia.fandom.com/wiki/Talk:Where_Two_Paths_Converge

**Comment by freddiepines** [comment]
Looks like Zeid has 8k~ HP in phase 1 and 30k~ in phase 2 currently:

![image](https://user-images.githubusercontent.com/50085658/89735833-36744c00-da33-11ea-8fc9-53249c2b41a2.png)

**Comment by Shoruto** [comment]
Additional Mission 9-2 HP issues #3103

**Comment by InoUno** [comment]
Resolved in December 28, 2020 patch.
