### ISSUE TITLE
[DRG] 'Spirit Link Recast' merit is working but incorrect value

### ISSUE THREAD

**Issue by MB213** [EdenServer/community#3164]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

Spirit Link Recast should reduce the recast time of Spirit Link by 6 seconds per merit, not 3. 
It was reduced to 3 seconds later when Spirit Link's base recast was halved to 1.5 minutes. 
On Eden Spirit Link is 3 minutes cooldown. 

Steps to reproduce:
1) Put a merit in Spirit Link Recast
2) Use Spirit Link, the recast is 2:57 instead of 2:54

Sources:
https://www.bg-wiki.com/index.php?title=Spirit_Link&oldid=23624
https://ffxiclopedia.fandom.com/wiki/Spirit_Link_Recast?oldid=730093

**Comment by KnowOne134** [comment]
corrected on 8/23/2020 update
