### ISSUE TITLE
Khimaira is a complete and utter joke

### ISSUE THREAD

**Issue by Elysien** [EdenServer/community#3165]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://gyazo.com/3f7e066625225b79b4ef74036a275762

^This is Khimaira on Eden.

That kind of melee damage was consistent, and pretty weak in terms of what era retail Khimaira would be doing. This is me tanking it on RDM/NIN in -50% PDT, a maxed potency phalanx and protect IV/tav.taco. 

On retail in the same set up, I would be seeing around 150-170/swing.

Consequently, this also makes Khimaira's scariest ability, Tourbillion, pretty laughable as well due to Khimaira having pretty laughable attack on Eden as things stand. On retail, Tourbillion _could_ do upwards of 1k-1.5k to a tank, depending on various factors such as 1-0 shadows at the time of it connecting, no shield block proc on PLD, etc.

Other issues with Khimaira;

Slow, Paralyze, and presumably Elegy as well, are far too easy to land on Khimaira. Should be an easy fix, it should have around about the same resistance level as Cerberus on retail, and Cerberus here is fairly retail-accurate in terms of slow/paralyze land rate. So, copy/paste? /SHRUG

Finally, Fulmination readying time is like a year here, I don't remember what it is on retail exactly but it certainly was not as long as it is here. I could have time to go for a piss, come back and still have time to throw up my MDT set before it gets off.

(On a outgoing note, I did some testing on retail as Lv75 RDM/NIN a few years ago collecting some data for a nasomi dev--they recorded a video of us duoing it and I'm trying to see if they can send the video to me as it has some good data for damage taken)

**Comment by Jimmayus** [comment]
This can be closed for the time being as redundant to the ongoing pdif overhaul available for testing on the test server. Physical stats have been calculated from testing done in the last two weeks and will be included as a package. As for magical land rates, this will be similarly addressed in the magic hit overhaul slated for development after pdif is pushed.

**Comment by xizeta** [comment]
Fulmination ready time was tested against retail and is accurate.

**Comment by Shoruto** [comment]
Similar to #3270 and #1249

**Comment by 59blargedy** [comment]
resolved december 7 update. if there are remaining issues or new issues that crop up, please post in new bug report
