### ISSUE TITLE
Luminian Tissue is Stealable and Should Not Be

### ISSUE THREAD

**Issue by KiplingFFXI** [EdenServer/community#3166]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My version is 30181205_0.

Luminian tissue can be stolen from Ul'Phuabo monsters in Al'Taieu. I am unsure if it can be stolen from other monsters in sea, because it seems to have a very low success rate when I try. Attached is log proof:

![luminian tissue steal](https://user-images.githubusercontent.com/62963895/89688926-13715d00-d8b8-11ea-8a0c-9b9bc20b1300.png)

It looks like it is  despoilable on retail, but going back through the wiki history never shows it able to be stolen on this page - https://ffxiclopedia.fandom.com/wiki/Ul%27phuabo

**Comment by KnowOne134** [comment]
corrected on 8/23/2020 patch
