### ISSUE TITLE
Adventuring Fellow - Blighted Gloom Quest

### ISSUE THREAD

**Issue by holyhobgoblin** [EdenServer/community#3167]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I have leveled my adventuring fellow to lvl 55 and i am trying to flag the quest "Blighted Gloom". I have done all quests before this no problems. Asked around and know one seems to know if this quest is available even though its listed on the classic Wiki EDEN recommend.

Can someone confirm if this quest is available on EDEN?

I've using my Signal and Tactics Pearl for the last few weeks thinking my BOND is not high enough, do not want to continue waste my time and pearl usage if this quest is simply not available.

Thank you in advance

**Comment by KnowOne134** [comment]
Not coded

**Comment by holyhobgoblin** [comment]
Cheers. All i needed to know.

Are there any plan to implement it?

Think I'll update the Eden WIKI with this info.

**Comment by KnowOne134** [comment]
Everything in the time frame we play is planed eventually
