### ISSUE TITLE
Meteormauler Zhagtegg respawn timer is incorrect at 23 hours.

### ISSUE THREAD

**Issue by Toanerz** [EdenServer/community#3168]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0

Meteormauler Zhagtegg NM in Jugner Forest currently has a respawn timer of 23 hours + 10 minute window when it should be 21 hours + 10 minute window. Killed him 3 times in a row to verify.

**Comment by 59blargedy** [comment]
resolved 11/2 update
