### ISSUE TITLE
Lance Belt should be in BCNM 30 "Petrifying Pair" loot pool.

### ISSUE THREAD

**Issue by Rikoooooo** [EdenServer/community#3169]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I noticed there are none ever on the AH and the sale history shows no listings also. I was sure the belt could also drop from the BCNM30 "Petrifying Pair", at least it is listed on the old Wiki as a potential drop. But not included on Eden?

version 30181205_0

**Comment by 59blargedy** [comment]
resolved oct 4, 2020 update
