### ISSUE TITLE
Rune Staff not giving MAB bonus latent.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#317]
Doing 1146 max damage with Thunder IV with no weapon equipped.
Doing 1163 max damage with Thunder IV with Rune Staff equipped and being engaged and MP is draining.
Seems I am only getting the INT+2 MND+2 CHR+2 latent bonuses but not the +10 MAB.
https://www.bg-wiki.com/bg/Rune_Staff

**Comment by godmode** [comment]
This appears to be functioning as intended.
