### ISSUE TITLE
Diamondhide is learned from the wrong type of Trolls on Eden

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3170]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Sorry to open without a ton of detail but this has been undocumented and wasting people's times for too long. Diamondhide should be learned off of the armored type trolls, and it is instead learned by the unarmored ones. Most people I know have wasted hours trying to get it off of the wiki mobs, and then have to hear through word of mouth that the unarmored mobs (for example, the Hilltroll Puppetmaster at Mount Zhayolm) are the ones that teach it on Eden

https://ffxiclopedia.fandom.com/wiki/Diamondhide

ver 30181205_0

**Comment by 59blargedy** [comment]
resolved in February 8, 2021 update
