### ISSUE TITLE
Thousand Eyes should be 15m respawn in King Ranperre's Tomb, not 5m

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3171]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Here is the wiki dated back to the most recent date before the patch that Eden operates on. Thousand Eyes should be a 15 minute respawn time, rather than 5 minutes.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in February 8, 2021 update
