### ISSUE TITLE
Pets in Dynamis Sandoria giving exp

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3172]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Did Dynamis Sandoria on 8/9. Entering at approx 1:10pm est. 

bst pets and wyverns were giving approx 9exp per kill each with 20 people in zone. They never dropped any loot(Nor should they).

All currency and af/weapon drops were normal.

ver:30181205_0

**Comment by Slamm21** [comment]
the same in windy, statues too.

**Comment by Garphilius** [comment]
Same happened to us in Bastok last night.

**Comment by jamiecol25** [comment]
We got exp from some normal mobs in dynamis sandy last night didnt note which but wasn't all, NM defo gave exp

**Comment by Slamm21** [comment]
it's only NMs, pets and statues

**Comment by bkesecker** [comment]
This issue was introduced with the latest changes to prevent Dynamis mobs from giving exp randomly.  Expected fix is known.

**Comment by 59blargedy** [comment]
resolved
