### ISSUE TITLE
Waking Dreams Diabolos Instant Casts Spells

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3174]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Tried Diabolos Prime today and noticed he had instant cast on all of his spells. From what I can tell from what appear to be era videos, this not a mechanic he should have and I can't find a reference to it anywhere in discussions / wiki pages.

Here is a clear example of a spell cast time for Aspir in what appears to be a retail/era video. The video is timestamped for convenience. 

https://youtu.be/jQ9p-sFkhCQ?t=152

Here is a timestamped video from Jimmayus' Diabolos Capture that shows the full cast time as well.

https://youtu.be/VYWigflF30M?t=101

I didn't make it far enough in my fight to see Nightmare, but figured I'd include this 2010 video (presumably era, no proof) timestamped at a Nightmare cast, in case his abilities were also coming out instantly on Eden.

https://youtu.be/9zHLaUwYkOg?t=297

version 30181205_0

**Comment by E5una** [comment]
Maybe I did it in dark weather, there's a note on the 2007 wiki that says "Dark Weather in The Shrouded Maw grants Diabolos an innate Fast Cast which cannot be dispelled". I'll try in another weather and update.

**Comment by E5una** [comment]
Did it in ice, still appeared to have the same fast cast mechanic.

**Comment by 59blargedy** [comment]
resolved with 9/6 update. insta cast still a thing when dream shroud up.
