### ISSUE TITLE
Sidewinder should be a straight -50 racc penalty, not %

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#3176]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
ver 30181205_0
### Details
http://wiki.ffo.jp/html/2540.html
details here

**Comment by 59blargedy** [comment]
resolved November 23rd patch
