### ISSUE TITLE
Horrid Roar Enmity Decrease

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#3177]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
ver 30181205_0
### Details
https://ffxiclopedia.fandom.com/wiki/Horrid_Roar
Horrid Roar should be different depending on what is using it

Fafnir/Cynoprosopi/Smok - One buff removed, minimal enmity reset (assuming 25%)
Nidhogg - All buffs removed including food, moderate enmity reset (assuming 50% which is what base dsp is set to)
Tiamat/Jormungand/Vrtra/Ouryu - All buffs removed including food, heavy enmity reset (assuming 75%)

they might be all set to the same on Eden, and if so they shouldn't be.

**Comment by Elysien** [comment]
CoP Wyrms were/are actually 100% hate reset, but the rest sounds accurate.

For the most part it's accurate on Eden, not sure on the values for Faf/Nid, though, but CoP wyrms wipe all buffs and hate

**Comment by 59blargedy** [comment]
there are three different roars on eden, with varying enmity reductions and effects, and assigned to the appropriate monster(s).  I don't see any bug or issue, but feel free to comment if you test and find one.
