### ISSUE TITLE
Beastmen King NMs are missing claim shields

### ISSUE THREAD

**Issue by hikarii4533** [EdenServer/community#3178]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

The following beastmen king NMs are missing claim shields. In era, these NMs all had claim shields. Moreover, having a claim shield for these NMs can prevent the use of shorthand.

The NMs include:
Orc NMs (Overlord Bakgodek and Orcish Overlord)
Yagudo NMs (Yagudo Avatar and Tee Xicu the Manifest)
Quadav NMs (Diamond Quadav and Za'Dha Adamantking)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved with 9/6 update
