### ISSUE TITLE
Nether Blast is not working properly.

### ISSUE THREAD

**Issue by danismyhero** [EdenServer/community#3179]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Nether Blast is not being calculated properly for damage, and is able to be resisted by mobs under the normal magic casting rules.  The advantage to this blood pact was that it was both ranged and consistent damage.

It does not appear to be affected by Pet: MAB (tested with both Dream Shroud and Puppet Roll).

Damage formula is as follows:

(5 x Avatar's Level + 10) * MAB(of avatar)/MDB(of monster) * Day/Weather

Further information from wiki: https://ffxiclopedia.fandom.com/wiki/Nether_Blast

If at the time this ability is used Diabolos is under the effect of Dream Shroud, damage will be increased.
Merits in Avatar Magical Attack and gear that specifically enhances avatar magic attack will increase the damage.
Seems to deal a fixed amount of damage, but can be affected by day/weather effects.
Diabolos' TP does not affect damage.
Ignores Resist Dark traits (Fomor, Skeles, Bats, etc)
Ignores Magic Damage Taken-% but not Magic Defense Bonus.
Ignores Level of Target.
This Blood Pact is a ranged magic attack, and can be successfully used even when Diabolos is not within melee range. 

Nether Blast is in the same category of damage as Spirits Within and Chi Blast, and so is subject to dealing additional damage to the Cerberus family of mobs as the mob targets HP lowers (unsure if this is currently implemented on Eden in general.)

Source: https://www.bluegartr.com/threads/108197-Random-Facts-Thread-Abilities?p=5412576&viewfull=1#post5412576
/ver 30181205_0

Some further era related postings of Nether Blast:
https://www.bluegartr.com/threads/43292-Drachen-Roll?p=1477652&viewfull=1#post1477652

**Comment by 59blargedy** [comment]
most resolved 11/2 - remaining items would be the cerb thing (had not heard of this) and potentially the range. please report back if that piece is still missing.

**Comment by 59blargedy** [comment]
at this point all of these have been resolved via various updates. ill make a separate ticket about cerb and spirits within/chi blast/nether blast as that is not solely a nether blast thing.
