### ISSUE TITLE
Sleep Bolts shouldn't work on skeletons

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#3181]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

Skeletons in Eldieme Necropolis are able to be slept with Sleep Bolts. Skeletons (not all undead) resist sleep as dark based monsters. To avoid confusion, not all undead are immune or resist sleep, ghosts are susceptible to dark based sleep.

**Comment by Raphtalia1** [comment]
Skeletons ghosts and fomor are immune to dark based sleep but susceptible to light based sleep. Sleep, sleep2, sleepga, sleepga2, And nightmare are all dark based.

 Light shot, lullaby, repose, and sleep bolts are light based sleeps and all work on undead as well as other dark immune creatures.

**Comment by dowzer** [comment]
It would be difficult to sleep Tonberries if sleep bolts were light based, similar to Lullaby.

Here is a demonstration of why I made this bug report. 

https://www.youtube.com/watch?v=ipM2WSuniTo

**Comment by Raphtalia1** [comment]
well consider me told, i always thought they were light

**Comment by dowzer** [comment]
The animation certainly looks bright.

I tested ghosts too because I could have sworn they resisted sleep bolts as well. Nope, I was wrong, sleep bolts can land on ghosts.

**Comment by KnowOne134** [comment]
has been corrected from 8/23/2020 patch

**Comment by dowzer** [comment]
It's still possible to sleep skeletons with sleep bolts

In Qufim on THF vs Wights

**Comment by KnowOne134** [comment]
possible but highly resistant, acc goes up as your higher level than them

**Comment by Mozzy4Ever** [comment]
> possible but highly resistant, acc goes up as your higher level than them

I mean <.< In the video Dowzer supplied he was I believe level 99 on a level 42-46 mob though

**Comment by KnowOne134** [comment]
so either we need to increase the resistance of undead, or should they be immune? its more of a problem with undead and not the bolts

**Comment by VirtuosusFFXI** [comment]
Would this not need magic hit rate to be overhauled to work properly anyway? It's in the plans after pdif bugs are handled and WSC audits are done.

**Comment by VirtuosusFFXI** [comment]
So I imagine stuff like this will get a pass over when that time comes.

**Comment by KnowOne134** [comment]
yes, give me sleep spell answers to compare, im not able to see videos <i can barely use web pages at home, just coding and testing on local server and sending in>

**Comment by VirtuosusFFXI** [comment]
Based on Jimmayus's explanation of magic hit rate, Skeletons should be functionally immune to dark based sleeps. The only way to land it would be to increase their 5% dark evasion to 10% by using a dark element aligned skillchain and magic bursting Sleep on them, which would result in a 12.5% chance of landing a dark based sleep. Since Sleep Bolts obviously can't magic burst, this means that sleep bolts can never sleep a skeleton.

This all assumes the magic hit rate system in place is functioning as it should be, which it isn't.

**Comment by dowzer** [comment]
Interesting, that lines up with wiki stating they're resistant, but not immune.

Tried on SCH99/BLM49 vs 23-26 Ghouls

Dark Arts + Elemental Seal + Sleep = Resist (Immunobreak)
Dark Arts + Focalization + Sleep = 1 minute duration

https://i.imgur.com/UAdFnwo.png

**Comment by Jimmayus** [comment]
Yeah I would consider this a bug report that will get solved in the larger magic hit overhaul.
