### ISSUE TITLE
CCB Amneisa duration seems to exceed one minute.

### ISSUE THREAD

**Issue by Qair** [EdenServer/community#3182]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

The CCB pumps amnesia's duration appears to be far exceeding one minute. After using a CCB pump on Ultima at 20%, Ultima did not use another weapon skill till its death. Same story for Omega. We used a pump at 40% and at 20% and I don't think it used a tp move the rest of the fight. 

Version 30181205_0

**Comment by 59blargedy** [comment]
resolved February 15, 2021 patch
