### ISSUE TITLE
Pots in 8-3 BC fight aren't returning to spawns after wipe.

### ISSUE THREAD

**Issue by Qair** [EdenServer/community#3183]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

As noted in the title, the pots in the bc 8-3 fight do not return to their pedestals after a full party wipe which makes it hard to use the re-raise strategy unless the last person alive dies on the other side of the room. 

Version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
