### ISSUE TITLE
You are able to stack synthesis supports for different crafts using belts

### ISSUE THREAD

**Issue by Zaekkor** [EdenServer/community#3184]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

It was recently brought to my attention that it might be possible to have guild synthesis support from multiple guilds via the use of the synthesis support GP belt item you can purchase (tanner's belt, boneworker's belt, etc). 

I tested this by first getting adv. support from one guild, then using the belt of another guild and observed both buffs applying to my character. I went on the test server and tested this as well by using two different belts and not using the npc. It will stack with either 2 belts, or NPC first, then belt. But it will not apply if you use belt first then talk to NPC.

Client version: 30181205_0
![bone belt](https://user-images.githubusercontent.com/29270598/90319723-b9504780-df08-11ea-822a-3080acb51339.png)
![npc cloth](https://user-images.githubusercontent.com/29270598/90319725-b9e8de00-df08-11ea-8ff3-1075741771f9.png)
![cloth and bone](https://user-images.githubusercontent.com/29270598/90319724-b9504780-df08-11ea-8f71-3261e0ec8aff.png)
![bone and leather belt](https://user-images.githubusercontent.com/29270598/90319726-b9e8de00-df08-11ea-9ee9-d05d1404e971.png)
![bone and leather support](https://user-images.githubusercontent.com/29270598/90319727-b9e8de00-df08-11ea-889d-475678bbe481.png)

**Comment by 59blargedy** [comment]
Resolved with 8.16 patch
