### ISSUE TITLE
Items duplicate when put into storage

### ISSUE THREAD

**Issue by iklarazu** [EdenServer/community#3185]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

This seems to be affecting pretty much anything I put into storage right now.

Using Brd AF Feet (slippers) as example, in my inventory, it is one item:

![image](https://user-images.githubusercontent.com/65548510/90334750-c7b16880-dfc7-11ea-9ac1-a1d2082a412e.png)

Moving the slippers into Locker or Mog Safe 1/2, it is one item:

![image](https://user-images.githubusercontent.com/65548510/90334790-faf3f780-dfc7-11ea-8b8b-7f9f09f576e1.png)

However when I put the slippers into Storage, they immediately double:

![image](https://user-images.githubusercontent.com/65548510/90334807-20810100-dfc8-11ea-9295-8b9d03cd4b6c.png)

This seems to be by appearance only, as when I remove the slippers from storage, they return to 1 item:

![image](https://user-images.githubusercontent.com/65548510/90334865-7fdf1100-dfc8-11ea-95bc-535031d79013.png)

I've tried /shutdown and logging back in, but still seems to happen.

I only have 2 pieces of furniture for storage right now which are White Jar and Adventurer's certificate.

![image](https://user-images.githubusercontent.com/65548510/90334916-dd735d80-dfc8-11ea-87af-0f965ca59223.png)

**Comment by iklarazu** [comment]
I've just noticed that my storage says 4/7 when there are only 2 items in there:

![image](https://user-images.githubusercontent.com/65548510/90334977-62f70d80-dfc9-11ea-8f5e-6b4d5a1aef57.png)

**Comment by KnowOne134** [comment]
Corrected 9/21/2022 update
