### ISSUE TITLE
Sky NMs not persisting

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3187]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

Sky NMs should persist through crashes/maintenance. They currently don't

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
