### ISSUE TITLE
BST pets not despawning on death

### ISSUE THREAD

**Issue by Calstaw** [EdenServer/community#3188]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version is 30181205_0

Have reproduced this all three time I tried it.

Leveling in Tahrongi, charmed a pet to fight with. Kill a few mobs and pet dies, however it is still listed as my pet and I am unable to charm a new pet. I zone and it takes the pet away, however the mob is back in its normal spawn location and it's name is now white and cannot be attacked or recharmed.

**Comment by MeyiLekoh** [comment]
Additionally pets now aggro other monsters around them. I was in Qufim with a fish, ran by two gigas and two ghouls, and they all aggroed my pet (not me, because I am a level 68 BST).

**Comment by KnowOne134** [comment]
has been corrected
