### ISSUE TITLE
White named Tiny Mandragora in Sartua

### ISSUE THREAD

**Issue by FriskArt** [EdenServer/community#3189]
### Checklist

There is a white named Tiny Mandragora right outside of Windurst Waters in West Saruta at (J-8).
It roams around like a normal mob but you cannot act on it. 

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
30181205_0
### Details

https://cdn.discordapp.com/attachments/744656944903618631/744657091175645254/Frisk_2020.08.16_164041.png

**Comment by Mozzy4Ever** [comment]
Related to #3189

**Comment by KnowOne134** [comment]
has been corrected
