### ISSUE TITLE
Ullikummi Immune to Silence. 

### ISSUE THREAD

**Issue by Cheezcakee** [EdenServer/community#319]
Ullikumi is immune to silence here. Not sure if he is supposed to be but was an ez silence for merited rdm on Kupo. Wiki doesn't say anything about immunity to silence.

**Comment by Elysien** [comment]
Is indeed suppose to be immune, though various FFXI wiki are absent on good documentation concerning this NM so I suppose this is only my word; but as someone who soloed a lot of the Sky stuff for gil on retail, this is a correct feature of this NM.
