### ISSUE TITLE
Diabolo prime clear sometimes does not persist.

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#3190]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver. 30181205_0

I cleared Diabolo prime a couple days ago and logged of saying I would visit windurst in good time to complete the quest.

Today I tried to turn it in to get the avatar but the cutscene started to begin the quest again and I got the starting Key Item.

Cause: Unknown.   Maybe logging off, maybe a server reset.  Either way, the bug exists and now I have to do the fight again :(

**Comment by 59blargedy** [comment]
resolved in 9/6 update
