### ISSUE TITLE
Bomb Queen adds might have wrong Self Destruct damage

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3191]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version: 30181205_0

Lots of things went wrong in our BQ run today so we had a few of the adds explode. Both times they exploded during the fight, no one took any significant damage (0-50). The last summon AFTER we killed BQ blew up for a ton more on 1 character. All times that bombs exploded they were under 25% HP. Is the damage supposed to be this variable where normally they deal 0-50 damage? I would think they would deal a lot more damage consistently.

![image](https://user-images.githubusercontent.com/13668758/90518493-dbc6a880-e134-11ea-93ce-f036d211ec35.png)

**Comment by 59blargedy** [comment]
resolved in June 28th, 2021 update
