### ISSUE TITLE
Fenrir Prime occasionally enters a mode where he spams TP moves that do nothing.

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3192]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I don't have the screenshots because this is a retroactive bug report from last week, but Fenrir Prime will occasionally enter a mode where he rapidly spams back to back TP moves that do nothing. I was hit by a Moonlit Charge for 0 while I had shadows up and no stoneskin, so something is definitely wrong with it. Stunning him will remove him from this mode, so I would just Head Butt to reset him to normal.

ver 30181205_0

**Comment by E5una** [comment]
Similar to an already closed issue, https://github.com/EdenServer/community/issues/566

**Comment by Deirdre5017** [comment]
Also similar to already closed issue #566 but different than Esunii's experience, we just had Fenrir spam his 2hr 5-6 times in a row in about a one minute span. I want to say he was around 20-30% HP at the time.

version 30181205_0

![img_20201016_211443](https://user-images.githubusercontent.com/73006091/96325818-32e3df00-0ff9-11eb-96bc-42c16aa3bd75.jpg)

![img_20201016_211455](https://user-images.githubusercontent.com/73006091/96325819-34ada280-0ff9-11eb-9215-79a571b09fc4.jpg)

**Comment by 59blargedy** [comment]
resolved November 30th patch
