### ISSUE TITLE
Weapon Bash Recast - DRK Merit

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3193]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

The group 1 merit Weapon Bash Recast for Dark Knight does not appear to function. Placing points in it does not reduce the cooldown of Weapon Bash (should be -10 seconds per point placed).

https://ffxiclopedia.fandom.com/wiki/Weapon_Bash_Recast?oldid=730073

version 30181205_0

**Comment by KnowOne134** [comment]
Fixed in today's update
