### ISSUE TITLE
BST stay ability does not work.

### ISSUE THREAD

**Issue by willydoo188** [EdenServer/community#3194]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

-Charm a pet.
-Activate Stay.
-Pet continues to follow you around.

Confirmed by another bst in my ls.
Ver 30181205_0

**Comment by ElectronicMan83** [comment]
Been reported long time ago. It happen when the pet have a DoT on him.

**Comment by MirkSerain** [comment]
This is different though.  Jug pets seem to be able to 'Stay' but charmed pets do not, doesn't matter if they have a dot or have even had one at any time.

**Comment by KnowOne134** [comment]
fixed in 8/23/2020 update
