### ISSUE TITLE
Berserk + Flat Blade is doing way, way too much damage.

### ISSUE THREAD

**Issue by baggedmilk2112** [EdenServer/community#3196]
### Checklist

- [/] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [/] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/] I have provided my client version in the details. (type /ver into your game window)

### Details

Use Berserk + Flat Blade and you will see. I did 650 damage with one of them at level 58. Works well every time.
ver:30181205_0

**Comment by 59blargedy** [comment]
im thinking pdif changes will solve this, but can you provide more details? what job? what equipment? what target, specifically?

**Comment by baggedmilk2112** [comment]
Sure. I will say a friend and I tried it on a few different mobs and it's pretty damn strong on anything I fought, that isn't much higher than your character.

I was on 58 or 59THF/WAR with a Bloody Blade  http://edenxi.org/tools/player/Fyooz
First night I noticed it was on the Underworld Bats in Fei'yin. Being a few levels lower than me and being bats, I hit them for 650~.

**Comment by l33tbmb** [comment]
I was running my 64~ PLD/WAR, I forget if we were using level sync at the time. My berserk + flatblade wasn't as effective, but it was still several hundred damage or more.

**Comment by 59blargedy** [comment]
thanks for the info guys

**Comment by 59blargedy** [comment]
resolved with pdif update
