### ISSUE TITLE
Puppetmaster still crash assault / zone randomly

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3197]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

In assault after the issue was closed and fixed in patch note I did crash the assault zone with my puppet, on activation.
And it happened again in some zone very rarely but enough so people PM me and say " GTFO with your cancer job " . 

Again its always on activate when it happen.  No specific delay between deactivation and activation.

**Comment by Crescensx** [comment]
Happened to me tonight at 11:25pm EST. Crashed during Activate while attack the wall in the Excavation Duty in Lebros Cavern

**Comment by ElectronicMan83** [comment]
Assault crashed again tonight.  Sent us in middle of MTZ. Pup Deactivate / Activate again.

**Comment by KnowOne134** [comment]
waiting for the puppet to fully disappear before recalling?

**Comment by ThrisStraizo** [comment]
Aye, you have to wait for the puppet's name to disappear and you'll be good.

**Comment by 59blargedy** [comment]
i believe this was solved in january, can report back if there are still crashing issues with activate/deactivate and we'll reopen
