### ISSUE TITLE
Pieuje's Decision NM Altedour I Tavnazia (WHM AF Body) is not at its era spawn point

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3198]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Summary, the pop for the NM should be moved from H-8 back to J-10.

The wiki (https://ffxiclopedia.fandom.com/wiki/Altedour_I_Tavnazia) refrences his new/old spawn point in the description. Eden is using the new spawn point when it should be using the old one.

"Spawned for the quest Pieuje's Decision by trading a Tavnazia Bell to the ??? located on first map at (H-8), near the well.
It is no longer at (J-10)."

The era dated wiki (https://ffxiclopedia.fandom.com/wiki/Altedour_I_Tavnazia?oldid=365634) references the old J-10 position.

"Located on first map (J-10)."

Version: 30181205_0

**Comment by 59blargedy** [comment]
resolved in December 21, 2020 patch
