### ISSUE TITLE
Unlocking Beastmaster

### ISSUE THREAD

**Issue by Darkestknight412** [EdenServer/community#3199]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
When trying to unlock BST, I received the start up quest, Save my son. I run down to the the area in qufim for the cutscene. During the correct time I click on the flowers and receive the cutscene. After watching, I run back to jeuno and am given the initial start up cutscene again. It does not seem to register that I went to qufim and progressed the quest.

**Comment by 59blargedy** [comment]
issue with needing multiple clicks to register a variable on occasion. not exclusive to this quest, am able to progress.
