### ISSUE TITLE
Impossible To Redo Aht Urhgan Mission 15 BCNM Fight

### ISSUE THREAD

**Issue by HunnyDoo** [EdenServer/community#3201]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

v30181205

After completing the boat fight, your Ephramadian Gold Coin that allowed you to get into the fight is consumed. You're supposed to be able to get a new Ephramadian Gold Coin from Jazaraat's Tomb if you need to do the fight again to help out a friend. Currently reexamining the tombstone after finishing mission 15 gives no Ephramadian Gold Coin and no dialogue so the mission can only be completed by an ENTIRE group that hasn't ever won the fight.

**Comment by KnowOne134** [comment]
Fixed in today's update
