### ISSUE TITLE
BST Pet attacking claimed monster

### ISSUE THREAD

**Issue by ReeceR09** [EdenServer/community#3203]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window) - 30181205_0

### Details

Set my pet to attack a Bomb mob in Valkurm dunes. While it was heading to it, our PL claimed the mob outside of party just to clear it. The pet still engaged and attacked it while it was claimed to someone else in pt. 

Haven't found any other bug reports on this and couldn't think of anything else that would explain it. 

Was a Sand hare being set to attack a 'Will-o-the-wisp'.

**Comment by InoUno** [comment]
Should be resolved with January 4th, 2021 patch.
