### ISSUE TITLE
Puppet WS's doing 0 damage.

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#3204]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Ver. 30181205_0

Puppet weaponskills are currently doing 0 damage. 
![pupdmg3](https://user-images.githubusercontent.com/45871917/90983737-22e1de80-e525-11ea-95ff-36c8a0a06309.PNG)
![pupdmg2](https://user-images.githubusercontent.com/45871917/90983754-30976400-e525-11ea-97ad-49c4a7bc35e3.PNG)
![pupdmg1](https://user-images.githubusercontent.com/45871917/90983756-30976400-e525-11ea-9ca2-59ebb51073d2.PNG)

**Comment by 59blargedy** [comment]
resolved
