### ISSUE TITLE
PUP is doing 0 dmg

### ISSUE THREAD

**Issue by Niko17pr** [EdenServer/community#3205]
the ranger doll is doing 0 dmg with range attacks. also all frames ws are doing 0 dmg.

**Comment by Ryo2133** [comment]
I took some screenshots to confirm this is currently not working.
![Pup_Broken](https://user-images.githubusercontent.com/70116350/90991005-dec9fa80-e573-11ea-93d2-53cfe0268392.jpg)

**Comment by 59blargedy** [comment]
resolved
