### ISSUE TITLE
Slugshot ACC

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3206]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Since update I went to check up the updated dmg on ranger. Saw no difference except when I do : Sharpshot + barrage >> WS.
0/7 so far on slugshot on greater colibri. I have 470 racc with merited Marks.

I didnt go in party that was the only way to test but something seem off.

**Comment by VirtuosusFFXI** [comment]
Ranged WS currently not dealing damage on live. Unable to replicate on test server, its a known issue right now though so hang tight.

**Comment by icariumkupo** [comment]
Saw an EES hit for 0 as well in lv 30 exp pt on eft. Sample size 1

**Comment by 59blargedy** [comment]
resolved
