### ISSUE TITLE
Labyrinth Lizard in Crawler's Nest have generous drop rates

### ISSUE THREAD

**Issue by l33tbmb** [EdenServer/community#3208]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window) **30181205_0**

### Details

Labyrinth Lizards in Crawler's Nest (at least within the area around H-8) seem to have an extremely generous drop rate. Every kill drops 5 to 7 items (mostly lizard skins and lizard eggs, and some lizard tails) without any form or Treasure Hunter. After 5-6 lizard kills I (Copper, 65 PLD/RDM at the time of hunting) have collected over a stack of lizard skins and lizard eggs as well as fire crystals from signet and one nest key.

**Comment by xizeta** [comment]
This is the correct behaviour. It is a known farming location from era and the unusually high drop rate is accurate.
