### ISSUE TITLE
Pup using repair crashes my ashita

### ISSUE THREAD

**Issue by karanora** [EdenServer/community#3209]
### Checklist
 
- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is, 30181205_0
The problem is when i am in a party with a PUP(Puppetmaster) or in a alliance, and the PUP takes out his automaton and uses the job ability Repair, i reinstalled the lastest Eden version 5.0 from my last, 4.1, when i still had the problem, since so far i am the only having this problem.

**Comment by Mozzy4Ever** [comment]
That sounds like an addon/plugin issue then. If it was a server issue, other people in your group would be having it.

**Comment by karanora** [comment]
This is my list on addons
![image](https://user-images.githubusercontent.com/70120091/90995859-0e780300-e572-11ea-9944-9fae238254f5.png)

**Comment by karanora** [comment]
and my list on pluggins 
![image](https://user-images.githubusercontent.com/70120091/90995931-3ff0ce80-e572-11ea-926d-317dddd57610.png)

**Comment by KnowOne134** [comment]
Internal plugin/addon issue. Turn them all off, add one and do whatever until it crashes to find which one. Then contact the developer of the plugin or don't use it anymore
