### ISSUE TITLE
Fafnir sleep resistance

### ISSUE THREAD

**Issue by Elysien** [EdenServer/community#321]
Fafnir's sleep resistance is ridiculously low, have only fought Nidhogg once since playing on Eden and didn't get a look at the sleep resistance, but if Nidhogg's is looking good, Fafnir's should be comparable, if a little less.

As RDM/NIN casting in an enmity+ set featuring pretty much 0 enfeebling+ gear, nor dark/pluto staff, I can effectively lock down Fafnir with sleep for pretty much the entirety of the battle.

**Comment by godmode** [comment]
Let me know if this is still too low after the next patch is deployed.
