### ISSUE TITLE
Bune needs more work

### ISSUE THREAD

**Issue by alltanos** [EdenServer/community#3211]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Bunes draw in seems to be set to activate if the player is a certain distance away. On retail he would draw in after the player with hate was out of mele range for a set amount of time. You could get 2 maybe 3 spells off b4 being drawn in.

Bune should have some amount of double attack.

Bune should not have mp to aspir. 

https://youtu.be/RRBai2f-49Y

30181205_0

**Comment by ElectronicMan83** [comment]
Bind/grav seem to land 100% with a well geared blm. I dont recall blm being able to solo in retail.

**Comment by Slamm21** [comment]
blm could solo this on retail

**Comment by alltanos** [comment]
Can't say blm solo would be impossible on retail but I dought it. Not sure how it's relavent to the issue though
