### ISSUE TITLE
Its a small bomb after all

### ISSUE THREAD

**Issue by alltanos** [EdenServer/community#3213]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

30181205_0

Big bomb is missing all tp moves besides berserk.

His place holders only know berserk and self destruct

Drop rate on fire bomblet seems much lower than anything I can find online

**Comment by hotspoot** [comment]
Drop rate does seem lower than retail/era and can confirm it only ever uses Berserk. Additionally, I can confirm the Friar's Lantern mobs (phs) only use Berserk and Self-Destruct.

**Comment by Elysien** [comment]
To add to this, it's also far too easy to land silence  on Big Bomb, should be very resistant and when silence did land it didn't last long.

Including the placeholders, the 'grow' mechanic didn't actually seem to do anything but I'm not 100% sure on that, just basing it on some eyeball testing. What it's suppose to do is increase the mobs ATK/MAB with each growth by an unknown but pretty substantial amount.

Finally I believe Big Bomb, as well as the placeholders, have a degree of fast cast as well which they don't here. Can also confirm they are missing TP moves, Big Bomb will just spam Berserk and only Berserk, effectively making his own grave.

**Comment by 59blargedy** [comment]
im going to close and reopen a ticket with remaining issues as most of these are resolved and it's hard to read through
