### ISSUE TITLE
[BST] Familiar ability not extending time enough

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#3214]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

The Beastmaster two-hour ability "Familiar" is not extending the time on a Charmed mob to 30 minutes, at least not when the mob is over your level.  I just lost my Level 79 Cave Antlion which I Familiar'd after exactly 5 minutes almost leading to my unexpected death!

Here is the wiki entry to Familiar within our era-timeframe: https://ffxiclopedia.fandom.com/wiki/Familiar?oldid=341820
The entry clearly states "While active, a charmed pet will stay with the user for a total of **30 minutes** from the start of the charm, regardless of level difference."  Now I get that it isn't always exactly 30 minutes, but FIVE minutes is way too short of a duration.  The last two patches have reduced the Familiar timer and it wasn't so bad before (I could keep the Antlion for about 15-20 minutes depending on level), but this is ridiculous and completely broken.

To duplicate simply Charm a Cave Antlion, use Familiar, and you will see it will un-charm way before the supposed 30 minutes I am supposed to get out of my two-hour ability.

**Comment by SleazyFFXI** [comment]
Can confirm this also happened to me with a mob of higher level

**Comment by 59blargedy** [comment]
resolved in 9/6 update
