### ISSUE TITLE
Tiny Mandragora have incorrect move set

### ISSUE THREAD

**Issue by Kythaela** [EdenServer/community#3215]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

Tiny Mandragora outside Windy have the wrong move sets. Unlike their bigger counterparts these are supposed to be starter mobs so should not have monk move set. Currently they have double attack and guard which they should have neither of.

This needs to be stressed again because these are supposed to be starter mobs that can easily kill a lvl1 player in two combat rounds. Not so much an issue for people on their second job but for new players it could be annoying.

**Comment by 59blargedy** [comment]
resolved 11/2 update
