### ISSUE TITLE
Switchstix can eat dyna currency

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3217]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Had a LS mate trying to finish Amano and accidentally traded 10k coin to Switchstix. 
A fix for this was posted to DSP on July 27th, 2015 (https://github.com/DarkstarProject/darkstar/commit/ed02e2bfca781cbdd73851f28a192618d4b4e63e)
Well before our last merge date, so I'm guessing that bit of code isn't actually preventing the 10k coin trade. Happened on live and verified it's still possible by progressing through Amano upgrade by force-updating my RELIC_DUE_AT var using !setplayervar Mozzytest RELIC_DUE_AT 1. Got to the 10k point where you're not actually supposed to trade the 10k coin to Switchstix but are instead supposed to trade to the respective ??? based on your relic and after trading my 10k coin, Switchstix said the following on 10k coin trade:
![image](https://user-images.githubusercontent.com/11255886/91273361-c22fed00-e742-11ea-942f-38562daf1197.png)
Trading the Totsukanotsurugi (wtf is that word) results in asking if I want to "cancel the order?"
![image](https://user-images.githubusercontent.com/11255886/91273378-ca882800-e742-11ea-8f51-46dbc972984d.png)
Saying "Yes" and confirming next prompt results in this picture where it looks like it's canceled...
![image](https://user-images.githubusercontent.com/11255886/91273413-d70c8080-e742-11ea-91a8-9fe715346f61.png)
Talking to Switchstix again then gives the starting CS for final relic phase along with additional text of "You are to offer these to me, along with the Tosukanotsurugi, on the peak of the mountain that looms above the forest and the city of knights... then shall I willingly enter your service". It didn't originally give the extra part when talking to Switchstix. What looks like another TextID then pops up as well from Switchstix talking about the Totsukanotsurugi again
Trading the Tosuk. AGAIN results in repeat of the "Cancel the order?" prompt
**End result is still 10k coin eaten**
Manually adding the 10k coin back to inven and trading to the unmarked spot in Horlais Peak still results in Amano + 30 montionts as it should

**Comment by greyenvy** [comment]
Well that sucks.  Hope we can get this guy his goldpiece reimbursed soon!

**Comment by rude-jerk** [comment]
https://github.com/project-topaz/topaz/pull/1361

**Comment by rude-jerk** [comment]
Resolved in November 16, 2020 patch.
