### ISSUE TITLE
Double Harmodios NPC

### ISSUE THREAD

**Issue by PrymalNights** [EdenServer/community#3218]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

There's double the npc of Harmodios in Bastok Markets at Harmodio's Music store.

**Comment by 59blargedy** [comment]
resolved 11/16
