### ISSUE TITLE
Please Audit Subligar drop rates from Phomiuna Aqueducts

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#3219]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I'm currently farming Subligars in Phomiuna Aqueducts and am 0/18 on THF and 2/18 on DRK with TH1. I believe these should be 15% drops or 24%, so 30%/48% with TH1. But I'm 2/36. 

http://www.ffxidb.com/zones/27/fomor-thief
http://www.ffxidb.com/zones/27/fomor-dark-knight

Both of these lineup with either 15% or 24%, so could go either way.

**Comment by VirtuosusFFXI** [comment]
Just to add to this, I agree that the category for these should be set to either Very Common (24% base, 48% TH1) or Common (15% base, 30% with TH1). I am leaning more towards a 15% base.

Here's some data from various ffxidb fomor mobs:

![brd](https://user-images.githubusercontent.com/49970272/94633814-6f46d980-029c-11eb-850d-380f4e3b3b86.png)
![bst](https://user-images.githubusercontent.com/49970272/94633815-6fdf7000-029c-11eb-8192-1db21f7f8071.png)
![drk](https://user-images.githubusercontent.com/49970272/94633817-6fdf7000-029c-11eb-814b-8bdda0ea44c7.png)
![rdm](https://user-images.githubusercontent.com/49970272/94633818-6fdf7000-029c-11eb-8d98-c8331f6dd5d6.png)
![sam](https://user-images.githubusercontent.com/49970272/94633819-6fdf7000-029c-11eb-9cd0-9bde11f563d1.png)
![smn](https://user-images.githubusercontent.com/49970272/94633821-6fdf7000-029c-11eb-9a74-b3c4a96e0bfc.png)
![thf](https://user-images.githubusercontent.com/49970272/94633822-70780680-029c-11eb-816d-18f4e5dc375b.png)

**Comment by 59blargedy** [comment]
resolved oct 4, 2020 update
