### ISSUE TITLE
Beastmen King are much weaker than their retail counterparts.

### ISSUE THREAD

**Issue by danismyhero** [EdenServer/community#3220]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The three beastmen king ( Za'Dha Adamantking, Overlord Bakgodek, Tzee Xicu the Manifest) are entirely too easy compared to the retail versions.  They do not currently resist any enfeeblement spells, their attacks, defense, accuracy, and evasion are not accurate, and quite frankly do not put up any type of fight.

They should not be susceptible to sleep or silence, and very resistant to bind.

Za'Dha is missing his potent regen, and likely does not spam cures at low level, however it's difficult to say since it can be silenced with no issue.
https://ffxiclopedia.fandom.com/wiki/Talk:Za%27Dha_Adamantking for testimonials.

Overlord Bakgodek should be "Resistant to Silence, highly resistant to Sleep." and "Resistant, but not immune to Paralyze." as well as damage based around "Hits Ninja tanks very hard ~500 normal attack and up to 1.3k Slam Dunk. "

https://ffxiclopedia.fandom.com/wiki/Talk:Overlord_Bakgodek cites a duo is possible, but the fights taking over 1 hour.

Tzee Xicu does not have a lot of era information on wiki, however https://ffxiclopedia.fandom.com/wiki/Talk:Tzee_Xicu_the_Manifest does mention a long fight, much like the others.

There are many other HNM that need to be audited for difficulty, but since these three are so similar I have reported them together.

Please turn off easy mode on Eden.

**Comment by Goto28** [comment]
not sure if xicu does here or not but it should have double attack and hit quite hard, but otherwise pretty standard mechanics except for the en-para

immune to sleep, hard to bind etc

and yes not easy mode eden would be great, almost every big monster on this server has big issues

**Comment by 59blargedy** [comment]
mostly resolved december 7 update based on data that was verifiable. retail captures needed of overlord and tzee for full completion/validation.
