### ISSUE TITLE
Diabolos CoP Fight

### ISSUE THREAD

**Issue by ghost** [EdenServer/community#3221]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Whilst doing the CoP lv40 cap diabolos fight at around 20% he fell down into the Diremite pit and drew in the whole PT to the diremites, they ate us up fairly fast. 
He was stationary on one of the "safe" platforms, aggro switched from one melee to the other and he moved just enough to drop through the cracks himself.
![Omnico_2020 08 30_161728](https://user-images.githubusercontent.com/62794262/91662759-623b9c80-eadc-11ea-97a8-9bf71b39856c.png)

**Comment by 59blargedy** [comment]
resolved january 4, 2021 patch
