### ISSUE TITLE
Spamming blood pact macro stops auto attacks.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#3222]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Posted at the behest of Kathryn: 
"I'm a SMN75, I'm fighting avatars. I like to spam my "Crescent Fang" macro 5ish seconds before CD expires because I lag a lot, sometimes that makes it more efficient. However in these 5 seconds of macro spam, I noticed my auto-attacks stopped. I tested by mashing the macro every second for an entire minute. In that whole minute, I didn't auto-attack once. I believe this to be a bug.
I'm auto-attacking w/ a Staff so the swings are very low in general. When I mash the macro, they just straight up stop until I stop mashing it.

Version 30181205_0"

**Comment by E5una** [comment]
Can second this with all job abilities executed through macros. If you spam something that is on cooldown through a macro (not through the menu) it will prevent your auto attacks. There is some abuse that can be done with this.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
