### ISSUE TITLE
Puppetmaster Merit Ability "Role Reversal" Not Working

### ISSUE THREAD

**Issue by MothVolka** [EdenServer/community#3224]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### 

The Puppetmaster merit job ability Role Reversal is not working. This ability is suppose to swaps the master's current HP with the automaton's current HP. When used last night, the ability did nothing. This was used 7 times and did not do anything each time. This ability was tested while engaged in combat and idle. This ability was working correctly before the 8/23/2020 update. 

Client version: 30181205_0

**Comment by FariskaEden** [comment]
Works fine for me, did you do anything else before trying to use it?

**Comment by ElectronicMan83** [comment]
Seem to be working fine here too. When its not triggering I assume its because the puppet hp have the around the same amount of hp as the master.

**Comment by KnowOne134** [comment]
No issue found
