### ISSUE TITLE
sleep bolts op

### ISSUE THREAD

**Issue by Goto28** [EdenServer/community#3225]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

the sleep effect on these bolts are landing on nms that should otherwise be immune to all forms of sleep

lands on;

Overlord Badgodek
Capricious Cassie
Cemetery Cherry

these are the ones I've discovered, I expect there is a much greater list if anyone would like to chime in

**Comment by dowzer** [comment]
Alkyoneus and Pallas (They are able to be slept on Eden by enfeebling spells too)

They should be immune to sleep

https://www.youtube.com/watch?v=P0gau8wQXS4
https://www.youtube.com/watch?v=H2Nhyl1YHG0

**Comment by danismyhero** [comment]
Pretty sure NQ Behemoth can be added.

**Comment by 59blargedy** [comment]
if you have retail or video proof of sleep immunities, please post them here. adjusted alky and pallas based on video proof (thank you) but wiki isnt really clear on sleep immunity for others.

**Comment by dowzer** [comment]
Confirming Capricious Cassie is immune to sleep.
https://www.youtube.com/watch?v=XF1SoH3oirM


Za'Dha Adamantking is NOT immune to sleep. (Unfortunately, I miss typed the command to record video and couldn't demonstrate Auto-Regen. It definitely does have Auto-Regen.)
https://imgur.com/a/3vaMF0o

**Comment by dowzer** [comment]
Behemoth is NOT immune to sleep although it is resistant to a RDM99/BLM49.
https://www.youtube.com/watch?v=FvFfXgM_2Yo


Confirming King Behemoth, Aspidochelone, and Adamantoise are immune to sleep.
https://www.youtube.com/watch?v=AeVBSsEA_84
https://www.youtube.com/watch?v=BIFdMxU4XZM

**Comment by KnowOne134** [comment]
The sleep bolts them selves have had a check to immunity applied 11/19 update. As for the individual mobs listed they would still need to be verified if the have it set

**Comment by KnowOne134** [comment]
Resolved 12/ 7
