### ISSUE TITLE
tiamat issues

### ISSUE THREAD

**Issue by Goto28** [EdenServer/community#3226]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Tiamat

Couldn't find much proof to what I'm reporting, but any retail Tiamat vet can chime in and confirm

Eden Tiamat currently has limited MP, in retail she must have had a large refresh effect, scrubby linkshells would fight this thing for 3hours straight in the day with BLMs and it would never run out of MP, here you can totally rinse her mp after 20mins.

Tiamat should have a permanent, undispellable en-fire effect, that proc rate isn't 100% though, I'd guess 40-50%, and doesn't do too much dmg, about 30-40 with shell V, does not have this on eden currently

I cant confirm whether eden tiamat has this as its difficult to tell but it is worth checking....like Hydra, Tiamat goes into a sort of rage state sub 25%, this effect is also permanent... does not go away with regening. The effect is noted to be +30% ATK, it also lowers her delay a little, from 180, to 160

she has other issues, such as enfeebling magic landing too easily...especially sleep and paralyze but i heard there is a magic adjustment in the works that will hopefully address this

**Comment by Ballanoir** [comment]
There is an LS that killing it almost all the time since years now and never said anything about it

**Comment by 59blargedy** [comment]
Please keep personal opinions and accusations out of bug reports, this is not the place for that type of discussion.
If anyone has any video, or actual proof of the above, it would help move this forward. Retail tests are useful, as immunities would not change, nor would enfire, etc.

**Comment by Ballanoir** [comment]
Your are 100% right about it its not the place for this i just found it funny that the bug report just came after few years maybe it was convenient that way until now

**Comment by roriffxi** [comment]
https://github.com/EdenServer/community/issues/807

**Comment by Elysien** [comment]
https://www.youtube.com/watch?v=z2Zg0NVqXds&feature=youtu.be

This video here shows proof that tiamat has a perma enfire effect, this was taken on retail while collecting data on Tiamat for another private server

It doesn't show much else as proof to the points of this topic, that being said there is a reason Paralyze is not being tempted whatsoever, it just did not land on Tiamat, and being a fire-based enemy at lv95, makes sense. Even when this was taken, retail underwent massive m.acc boosts in the enfeebling formula, to the point where you can see sleep it somewhat decently (though this is with the absolute best in slot gear as well, which is easy to amass now) and Paralyze still just did not land

**Comment by 59blargedy** [comment]
refresh, enfire added. attack bonus below 25 already existed. added paralyze immune, light sleep immune, high dark sleep resist but may require mhit rate update for full realization. calling this closed as of december 7 update, but can comment if not fully resolved.
