### ISSUE TITLE
Misareaux Coast - Bigclaw & Diatryma

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3227]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Both Bigclaw & Diatryma in Misareaux Coast are aggressive when they should not be. To test: be above their level where they check as too weak and rest near them and you'll get aggro.

https://ffxiclopedia.fandom.com/wiki/Bigclaw
![image](https://user-images.githubusercontent.com/46270382/91894213-562e1700-ec63-11ea-9329-f6a29bc50587.png)
https://i.gyazo.com/419fd45ca0f37650806b8cab6be8b7aa.mp4 - resting near one on retail

https://ffxiclopedia.fandom.com/wiki/Diatryma
![image](https://user-images.githubusercontent.com/46270382/91894311-7fe73e00-ec63-11ea-8a97-ffccc9ac535c.png)
https://i.gyazo.com/ad522e7f24bfa30b46d720e38626d8e5.mp4 - resting near one on retail

version 30181205_0

**Comment by 59blargedy** [comment]
resolved 11/2 update
