### ISSUE TITLE
Enhancing Sword giving +5 enspell dmg to offhand

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3229]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Enhancing sword is currently giving +5 damage to offhand weapon as well. It should only be giving it to the sword itself per https://ffxiclopedia.fandom.com/wiki/Enspell?diff=next&oldid=408018
"Note2: When using Dual Wield along with either the Buzzard Tuck or Enhancing Sword, only the hits inflicted by these two swords will receive their own benefits to Enspell damage. The other melee weapon used will not receive the Buzzard Tuck's or Enhancing Sword's Enspell damage boosts upon its own hits (although it will still receive boosts from the Fencer's Ring and Hollow Earring, if used). This game mechanic behaves similarly to weapons that boost Critical Hit Rate, which also only boost their own crit rate, not the crit rates of any other weapon(s) the player may be using at the same time."

While the update to that page is from slightly out of our "era" date (January 9th, 2008... about 1.5 months) I believe it's still accurate for our era especially considering how on retail currently, it's still true.

**Comment by Dukilles** [comment]
Resolved in 10/9 patch
