### ISSUE TITLE
Byakko

### ISSUE THREAD

**Issue by Elysien** [EdenServer/community#3232]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Aside for the obvious glaring issue of it being bindable/gravable with extreme ease and full duration almost every time, it also moves at normal tiger speed. Should be flee speed.

**Comment by 59blargedy** [comment]
resolved december 7 update
