### ISSUE TITLE
Ruby Quadov

### ISSUE THREAD

**Issue by Arckaina** [EdenServer/community#3234]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Looked at the history on the wiki and the Ruby Quadov has always been 20mins from what I can see, yet it only seems to spawn every 25-27 minutes on Eden. Not sure if this is a bug or if it was this long back in the day (though again no history page on the wiki says anything other than 20 min respawn). Trying toget a friend a RDM testimony and only can get 2 tries an hour is resident sleeper.

**Comment by Mozzy4Ever** [comment]
Kinda sorta a bug I suppose. But I'm pretty sure it's because when the zone goes into standby (due to nobody in it), the respawn timer may stop ticking.

**Comment by Arckaina** [comment]
Understandable I'm just out here with my RDM friend, (staying in the zone the whole time so no standby) and we've been here for hours and only getting 2 an hour as opposed to 3 an hour is hurting, even though this testimony is a 25% drop rate ZZZZZ

**Comment by Tjonke** [comment]
I'd recommend the Hover Tanks in Uggalepeigh if no sky access for RDM testimony. Seen maybe 2-3 testimonies from Ruby Quadav and I used to farm them for Rubies.

**Comment by 59blargedy** [comment]
resolved in February 8, 2021 update
