### ISSUE TITLE
BCNM orb lost

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3236]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I had an orb in mog house for a while waiting for ksnm. I went to do the ksnm then checked bc to see if orb was working and it was. I canceled the chat box message  or just clicked out and when it was my turn 
 my orb wasnt working anymore and had message saying "No longer contain a monster "

**Comment by KnowOne134** [comment]
Corrected in a later patch
