### ISSUE TITLE
Jailer of Temperance PHs not working correctly

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#3237]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
ver 30181205_0
### Details

We killed all 5 PHs within 1 minute of each other 3x in a row, no pop.
the PH should move every 15minutes, so the chances of that happening 3x in a row is incredibly low.

**Comment by ElectronicMan83** [comment]
We farmed temperance for a few hour, having at least 3/5 tower covered 100% of the time. Didnt pop once either.

**Comment by falisaxi** [comment]
Also farmed Temperance for a total of about 6 hours with no pop. Seems very likely something is wrong here and this is causing a hard stop to any Sea progression since this means no JoL.

**Comment by setsuk0** [comment]
Not sure if this has been looked into, but this week we had people sitting at each tower for nearly 5 hours with no pop. We had 3/5 towers covered for the first couple of hours until we split a couple people off to get the other two, but it still never popped.

**Comment by maldra** [comment]
We popped Jailer of Temperance on our first PH kill last night, but there were other issues with it that require a separate entry.

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
