### ISSUE TITLE
Darts do not have the proper delay.

### ISSUE THREAD

**Issue by Cebianz** [EdenServer/community#3238]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.) Threw several darts and had others do the same
- [x] I have provided my client version in the details. (type /ver into your game window) 30181205_0

### Details
Howdy, darts do not have the proper delay. Much higher than it should be.

**Comment by Wannaspoon** [comment]
I was on Brd, level synced at 27-30 and later 39-40.  Pebbles where having a much higher delay than normal as well, but only when synced.  The first throw seemed to be the correct delay but after switching back to an instrument and to the pebbles the delay was again way too long (roughly ten seconds).

**Comment by VirtuosusFFXI** [comment]
For reference, Pebbles shoud have a delay of 4.6 seconds and Darts should have a delay of 2.8 seconds.

**Comment by E5una** [comment]
Assuming this is the main ticket, I just wanted to offer up that a dragoon (and later a monk) in my parties yesterday were able to throw pebbles with normal delay. I however still had the long delay on bard, so its probably related to the instrument or ranged slot. Hope this helps, sorry if it is additional noise :)

**Comment by 59blargedy** [comment]
duplicate/resolved w/ september 20 update
