### ISSUE TITLE
KRT bats exp are not accurate after the 1st kill

### ISSUE THREAD

**Issue by Moogleslayer** [EdenServer/community#3239]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver. 30181205_0
Today I formed a 6 man party to XP on KRT bats (synced to 51) the first bat we killed gave full xp around 273 with XP ring on and every bat after approximately 3 more bats gave 16-20 XP for everyone in the PT. I was warned by one of our PT members that the XP was broken, but we decided to see if it had been fixed. He stated it was broken since at least last week's patch. (I cannot verify that)

**Comment by Wannaspoon** [comment]
Did you kill anymore, or kill them after re-spawn?  It's possible the bats had been previously aggrod by a higher level.  If this was the case the bats would "tainted" until they re-spawn no matter how long ago they have been aggrod.

**Comment by falzum** [comment]
This is not exclusive to KRT. It's a problem with exp staying 'dirty' after being aggro'd at any point by a high level player. 

Mobs don't return to normal exp value after being de-aggro'd and makes the first round of mobs at a camp potentially shitty. 

For example, if a 75 thf runs in, aggros something and uses hide, that monster's exp will stay dirty til it's killed.
