### ISSUE TITLE
Bugged Flyer Quest

### ISSUE THREAD

**Issue by Kowl91** [EdenServer/community#3241]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Game Client ver.30181205_0

Ticket 1918 and 718 did not have this issue, but I believe them to be related, but neither report a missing NPC.

Flyers for Regine at the Magicmart in Port San d'Oria. It is a level 1 quest for handing out 15 flyers. I have handed out 14,  but it appears the 15th NPC doesnt exist and should be with another NPC in 1 of the port's 2 cargo rooms and niether of them exists it looks like. Been searching Sandy for about 3 hours. 
(Technically 2 missing NPCs, but I dont know what the npc next to her is for) I will be away until Thursday evening, so it will be a minute before im back on in fame, but I will still be here with phone on me.

Missing NPCs: https://ffxiclopedia.fandom.com/wiki/Prietta

**Comment by xizeta** [comment]
Prietta is in the proper location as listed on https://classicffxi.fandom.com/wiki/Flyers_for_Regine up the stairs above the cargo rooms.

**Comment by Kowl91** [comment]
*sigh* my fault entirely. There is a staircase that looks like a tunnel next to 1 of the cargo rooms. I did not notice it before.
