### ISSUE TITLE
Ninjutsu Cast Range

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3243]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Ninjutsu that targets an enemy currently has a max cast range of 16.4 yalms. The max cast range should be 17.5 yalms. To test try casting ninjutsu on enemy who is 17.5 yalms away, the cast will fail and give the out of range message.

https://i.gyazo.com/a6dc9f1861930fe753fe3a1fca13b921.mp4 - clip of max cast range on retail (test was done on an enemy who does not move and on a flat surface)

version 30181205_0

**Comment by 59blargedy** [comment]
Resolved in June 7, 2021 update
