### ISSUE TITLE
Bano Del Sol, incorrect activation on additional effect

### ISSUE THREAD

**Issue by him911** [EdenServer/community#3245]
Bano Del Sol(Dagger)
Additional effect vs. slimes: Light damage
100% activation rate vs. slimes.

On Eden it activates on all types of mobs at a decent rate but it should not proc at all vs non slimes
And it does not have 100% activation on slimes at the moment. 

### Checklist

- [yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [yes ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [30181205_0 ] I have provided my client version in the details. (type /ver into your game window)

**Comment by 59blargedy** [comment]
resolved 11/2 update
