### ISSUE TITLE
SMN Trial Avatar fight - Multiple 2 hrs

### ISSUE THREAD

**Issue by Satirof** [EdenServer/community#3246]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

Fought Titan Prime earlier (level 75 fight), and found that he used mountain buster two times. Whereas he should only be able to use it once. 
https://ffxiclopedia.fandom.com/wiki/Titan_Prime
The Wiki pages from 07 don't mention the once per battle, but it was the same then (know from experience as I used to solo them a lot on RDM when bored)

Steps:
1: Enter Primal fight
2: Get primal under 50%
3: Primal will use 2 hour
4: Keep fighting, but not killing
5: Primal will be able to 2 hours again if it chooses it.

Also, I found that primals on Eden seem to use TP moves like regular monsters. Above 50% only at 3k TP, between 26-50% at 2k TP, and under 25% at 1k TP. IIRC in retail they were more based on a timer (like bloodpacts) and not based on TP. Maybe I'm remember that wrong, but should be simple enough to check if someone has a retail account.

![Higana_2020 09 09_193048](https://user-images.githubusercontent.com/38270613/92588701-5cac3680-f2d4-11ea-99fd-97d8dfc61f2a.png)

**Comment by Shoruto** [comment]
Similar to #1571

**Comment by 59blargedy** [comment]
resolved in December 14th update
