### ISSUE TITLE
Scarlet Sap Jug Pet - No Ready Abilities

### ISSUE THREAD

**Issue by Spintaru** [EdenServer/community#3247]
I have searched for this on all the open and closed issues, didn't see any results.

This is at least reproducible on my character, haven't tried it on another.

Client version: 30181205_0

When a Scarlet Sap Jug Pet is used, no Ready Abilities are present in the selection screen, screenshot to verify will be attached.

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by Spintaru** [comment]
![EdenFFXI - BST bug report proof](https://user-images.githubusercontent.com/46164024/92638188-e98ccb00-f2a7-11ea-9779-4dc0ad72535d.png)

**Comment by Tjonke** [comment]
Yeah, this almost cost me my Maat Fight.

**Comment by FriskArt** [comment]
This is own and there is already an issue for this. 
https://github.com/EdenServer/community/issues/2106

**Comment by 59blargedy** [comment]
resolved in December 21, 2020 patch
