### ISSUE TITLE
Pebbles have 999 delay

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3249]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Since the update on 9/6, Pebbles have 999 delay. They should have 276 delay as per https://ffxiclopedia.fandom.com/wiki/Pebble

This seem to not be effecting all players. Only 2/3 people in my party earlier had the special max delay pebbles. We're not sure why the one person was uneffected.

Ver: 30181205_0

**Comment by Mozzy4Ever** [comment]
You should probably uncheck your first box

#3238
#3244

**Comment by KnowOne134** [comment]
Nice. So many reports of same problem. But in multiple tickets
