### ISSUE TITLE
Readying a Weaponskill on a Dying/Dead Target

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3250]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently when a weaponskill is readied on a target that is in the process of dying/dead you will lose all your TP even when your weaponskill did not interact with the target. TP should be retained if you were in range of being able to use the weaponskill that was readied. I would have liked to record this happening from retail but it's not easy to reproduce/time, but I have noticed keeping TP when it did happen on there. This also applies to pet weaponskills as well.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved w/ september 20 update
