### ISSUE TITLE
Unable to do Promathia fight (CoP BCNM fight in Dawn) with people who have completely completed CoP

### ISSUE THREAD

**Issue by maldra** [EdenServer/community#3251]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x]I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0

Friends of mine who have completed CoP and have done all cutscenes available (up until the bahamaut quest which is currently unavailabe). Their mission log says that Dawn is a completed mission, but it is also listed as their current mission.

I am able to enter the BCNM solo, but when any of the members who have completed all available CoP cutscenes/missions join the party, the selection is no longer available.

**Comment by Garphilius** [comment]
Devs know this is a bug hurting all BC Missions. 

Quick fix for now so you can get it done with your friends:

Invite all your friends to your party but instruct them to wait on accepting invite. You then click on the object to start BC fight. When it prompts you to choose the BC fight to enter, tell your friends to accept the invites. Once all have accepted, click on the battlefield you want to enter.

**Comment by maldra** [comment]
That sounds like a very good work around! I’ll have to try that, thank you!!

**Comment by 59blargedy** [comment]
resolved oct 4, 2020 update
