### ISSUE TITLE
Sorcerer Skeletons Didn’t Engage

### ISSUE THREAD

**Issue by MaesterEntropy** [EdenServer/community#3252]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Everything worked fine until after we walked into the mission 5-1 fight. We buffed then took off to the Archduke. After about 30seconds, I noticed the sorcerers were not attacking. They also had not even moved from there spot. In efforts to see if they would agro I walked next to one of them and they remained lifeless. (pun intended)

**Comment by MaesterEntropy** [comment]
Version 30181205_0

**Comment by InoUno** [comment]
Should be resolved with December 21, 2020 patch. Please reopen if this is not the case.
