### ISSUE TITLE
Drachen Roll does not affect Sharpshot Frame Ranged Accuracy

### ISSUE THREAD

**Issue by Pupaiya** [EdenServer/community#3254]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Using Drachen Roll or Beast Roll on a Automaton with the Sharpshot Frame does not seem to increase the ranged accuracy or Ranged Attack of the Automaton. When tested as /COR, busting a Drachen roll does not lower the Sharpshot Frame's Ranged Accuracy as well. It seems that ranged accuracy and ranged attack are not affected at all by Drachen and Beast roll from these tests.

/checkparam was used on the Automaton to verify the increase or decease to stats.

version 30181205_0

**Comment by rude-jerk** [comment]
Resolved in January 18, 2021 patch.
