### ISSUE TITLE
NM Placeholders (Audit)

### ISSUE THREAD

**Issue by FriskArt** [EdenServer/community#3255]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
30181205_0
### Details

Certain NMs spawn conditions are working improperly. 

Example: 

VE can spawn from any of the Flies around whitebone sands when it should only be able to spawn from the one that spawns on the beach. Mob ID 14A
https://ffxiclopedia.fandom.com/wiki/Valkurm_Emperor

Mee Deggi the Punisher works a little differently. The placeholder is a Interrogator or a Drummer that share the same spawn. Same applies for Quu domi and his Placeholders. With these two NMs their spawn window opens after the time of death of the placeholder and the NMs can spawn in 1 minute windows prior to the placeholder respawn. 

On Eden, all Interrogators and Drummers (Herald and Oracle for Quu Domi) are considered placeholders for these NMs. 
https://ffxiclopedia.fandom.com/wiki/Mee_Deggi_the_Punisher
https://ffxiclopedia.fandom.com/wiki/Quu_Domi_the_Gallant

**Comment by KnowOne134** [comment]
would need to list out individual claims for issues.
i will take these 2 and make seperate tickets.
