### ISSUE TITLE
Dying while charmed by Jailer of Justice results in double exp loss.

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#3256]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Client Version 30181205_0

While charmed by Jailer of Justice, if you're killed by another player it will produce two death messages in the log along with double the experience point loss. After a Raise III I lost around 2,566 experience points which includes some the experience points gained from the death of Jailer of Justice's spawned adds. This would suggest that it counted as 2 deaths, one being influenced by the Raise III the other being a full loss as if I home pointed for a total of 2,640 experience point loss.

This happened to me **twice**, so it is surely easily repeatable.

I wasn't able to capture the double death message, so these two screen shots are my only proof at the moment.

![Tanya_2020 09 12_185535](https://user-images.githubusercontent.com/65121606/93008119-4950d380-f53f-11ea-9fed-b400e0fd7a83.png)
![Tanya_2020 09 12_190615](https://user-images.githubusercontent.com/65121606/93008120-4bb32d80-f53f-11ea-8e77-f58a11b4ddfe.png)

Reproducable Steps:
1) Get charmed by Jailer of Justice
2) Get killed by another player while charmed

**Comment by FariskaEden** [comment]
From what I've read, there should be no experience loss at all if you die while charmed.
https://ffxiclopedia.fandom.com/wiki/Charm_(Status_Effect)?oldid=366003
"Players who are charmed are treated as full-fledged enemies and can be defeated by other players, though no experience points penalty is incurred if you are defeated while charmed."

**Comment by VirtuosusFFXI** [comment]
This is still an issue. Died to charm, got two deaths in the chat log, lost 4,800 EXP. Raise 3 only refunded EXP for one of the deaths.

**Comment by InoUno** [comment]
Resolved with December 14, 2020 patch.
