### ISSUE TITLE
Wyverns lose TP in CoP6-4 stage changes

### ISSUE THREAD

**Issue by Dorinorin** [EdenServer/community#3257]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details
Just was doing CoP6-4 on Puppetmaster, and normally the TP resets to 0, but this time we had 2 different Puppetmasters and a Dragoon and both automatons had TP when moving from Mammets to Omega ship. The Wyvern’s TP reset to 0 like the rest of the Party.
![970BFC4B-E2C9-481C-B867-79FD9E8C581F](https://user-images.githubusercontent.com/66181140/93008604-89668500-f544-11ea-8531-d4329fdee4c0.jpeg)

**Comment by FariskaEden** [comment]
The wiki does mention this: 
![image](https://user-images.githubusercontent.com/46270382/93008903-43132500-f548-11ea-9fdf-7a26cc980997.png)
So could also be bugged in a way that the wyvern should've kept its TP.

https://ffxiclopedia.fandom.com/wiki/One_to_be_Feared

**Comment by Dorinorin** [comment]
You’re right. Then it’s a bug then for Wyverns to not keep TP.

**Comment by KnowOne134** [comment]
fixed 11/9 update
