### ISSUE TITLE
CoP6-4 wipe, 1 person waiting to get kicked: automatically re-entering fight.

### ISSUE THREAD

**Issue by Dorinorin** [EdenServer/community#3258]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Party member left fight by accident before Mammets, and the rest of us couldn’t leave, so we died. Then all but 1 person HP’d and we ran back to wait for the one person to get kicked from fight, but upon entering Sealion’s Den, we entered right into the fight again.

**Comment by Dorinorin** [comment]
Version 30181205_0

**Comment by KnowOne134** [comment]
Corrected on 7/5/2024
