### ISSUE TITLE
Gration drop rate is wrong

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#3259]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Can you check Grations drop rate? Feel I'm just wasting my time with this one.
I've killed this thing 8 times now with 0 drop. With NQ the shield it's supposed to be 50% drop rate.

**Comment by Balrahn** [comment]
ver: 30181205_0

**Comment by 59blargedy** [comment]
just having bad luck, is coded at 50% for nq
