### ISSUE TITLE
Fool's Gold is not giving mogenhancement for goldsmithing

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#326]
I got Fool's Gold the other day but it isn't giving me the Mogenhancement for goldsmithing.

**Comment by jmcmorris** [comment]
Is this the only piece of furniture you have in your MH? If not can you list out the placed furniture you have in your MH? I placed Fool's Gold by itself in my MH and I was granted the Goldsmithing Moghancement.

**Comment by Oyaziiiiiii** [comment]
I have 10 brass flower pots in my MH as well but I couldn't remove those since they have stuff growing. When I placed the Clothcraft item with the 10 flowerpots I still got the clothcraft mogenhancement though.

**Comment by jmcmorris** [comment]
Ah ok, that is because Spinning Wheel is Earth element. Moghancement is determined by strongest element type and then item with the strongest aura value.

https://ffxiclopedia.fandom.com/wiki/Moghancements
