### ISSUE TITLE
Ranged Attack Delay Longer After 09/13 Update

### ISSUE THREAD

**Issue by benjaminrclayton** [EdenServer/community#3261]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Ranged attack delay is much longer after the routine maintenance performed on 9/13.

**Steps to reproduce**

1. Perform ranged attack action
2. Note the delay is longer than expected.

Version: 30181205_0

**Comment by bkesecker** [comment]
Going to need more specific details.  What job, weapon, and ammo.

**Comment by ThoseWhoFight** [comment]
Thf 75 / Nin 37, Velocity bow NQ, Acid bolts for sure are longer atm. Can't speak for others

**Comment by bkesecker** [comment]
What is the difference?  Many seconds or less than 1?

**Comment by benjaminrclayton** [comment]
Thf 50 / Nin 30, Almogavar bow blind bolt

**Comment by benjaminrclayton** [comment]
Feels like 1-2 seconds longer.

**Comment by ThoseWhoFight** [comment]
Same deal for velocity bow, 1-2 seconds longer I'd say. 216 delay should basically be 2 seconds

**Comment by bkesecker** [comment]
What main hand weapon was equipped?

**Comment by benjaminrclayton** [comment]
Bone Knife +1

**Comment by ThoseWhoFight** [comment]
NQ Behemoth knife. Maybe an issue with items of that model? Idk how it works. Only common denominator I can see with those two items.

**Comment by benjaminrclayton** [comment]
Able to reproduce issue with H2H and sword equipped as main weapon.

**Comment by FriskArt** [comment]
1-2 Seconds longer with THF51/WAR25. Zamburak+1/Acid Bolts
Corsair's Knife/Viking Shield

**Comment by Om-nico** [comment]
V Bow +1 same problem. A good 1 second delay has been added. Main hand Harpe, Off hand Thiefs Knife. 

Archery seems the same on my sam/rng but i could be mistaken as i am not as used to the delay like i am on my THF

**Comment by 59blargedy** [comment]
resolved w/ september 20 update

**Comment by bkesecker** [comment]
> While I think the delay seems okay the time to take another shot with Xbow seems to back back to the way it was. As mentioned with Snapshot on bow / xbow if Snapshot procs you still have a delay after where you can’t shoot again effectively borking the effectiveness of Snapshot. That issue seemed to have been fixed on the last round of updates but seems to be back again.

**Comment by ThoseWhoFight** [comment]
Assuming OP means after rapid shot procs. Not Snapshot, since that is just a static -delay.

**Comment by 59blargedy** [comment]
resolved oct 4, 2020 update
