### ISSUE TITLE
Beastmaster pet auto Heel after Update 09/13 

### ISSUE THREAD

**Issue by Zecheria** [EdenServer/community#3262]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

1. Activate Fight on target.
2. Move camera around.
3. Pet automatically stop attacking designated target and starts following player.

After activating /ja "Fight" <stnpc>  or Fight from the menu pet will auto "Heel". 

This happens more often when camera is moved around but will also happen randomly when doing nothing after command is issued from both macro and menu.

version 30181205_0

**Comment by Zecheria** [comment]
After additional experimentation this seems to affect the first "Fight" command given to each target. After pet heels the first time your second Fight command will work fully.  if your issuing the command to one target then a second target it will Heel on both targets individually  but will then Fight both targets normally after the second command is given on each target.

**Comment by Jaylocs205** [comment]
Seems to affect me multiple times. I had my pet "Heel" 3xs back to back.

**Comment by DirtDigler32** [comment]
Same here, I have had it happen 4 times a few times as well.  Very frustrating.

**Comment by Zecheria** [comment]
Guess Ill put an update here since I have been "trying" to play Beastmaster of the past few days. This is my most recent fight and seems to be the norm although during 1 fight I had to reissue the fight command 9 times before my pet just died and I had to charm another pet.  

Summary of just 1 fight.  Every fight is basically the same.
-------------------------------------------

Picture is me starting a fight with a Sniper against a Damselfly. After first hit sniper starts following me. I reissue the fight command 2 more time.  One time the command didn't even activate. The sniper continued to follow me around as if the command wasn't even issued.  Third command was issued and again the snipper continues following me around.  Sniper Dies...   Have to charm another Damselfly.  Issue Fight command.  1 hit lands  and then pet starts following me again. I issue 3 more fight commands with non of them actually working as the aggroed fly continues attacks my pet.  On the 4th fight command the fly finally stops following me and continues to attack the enemy until it dies.  I have to use Charm on the enemy and give up.

-------------------------------------------

I understand this is being worked on but compared to slow arrow bugs, sleep not working on empty, and the multitude of other bugs that seem to be getting worked on I am still frustrated.  

This is quite literally a JOB BREAKING BUG that makes and entire job in this game unplayable.
I can understand some bug fixes being rolled out with a standard weekly patch but this is job breaking enough that it should be patched as soon as a fix has been found.

I appreciate the effort being put into running this server and I cant even begin to comprehend the amount of work that goes into troubleshooting and implementing fixes for bugs in the game but I'm just having a hard time wrapping my head around how this is still broken after almost an entire week.

![image](https://user-images.githubusercontent.com/71225484/93604505-2191bd80-f9ce-11ea-9fce-1b438ca5241f.png)

**Comment by EpicTaru** [comment]
It's a known, acknowledged issue, I'm sure it's being worked on.  Remember that the administration of private servers do what they do **in their free time, no one is getting paid to do anything.**

https://discordapp.com/channels/482610771126386688/506960380275327009/755457968501162104

**Comment by KnowOne134** [comment]
No need to keep posted should be cleared up by Sunday patch

**Comment by Slamm21** [comment]
this seems to happen whenever the pet takes damage

**Comment by 59blargedy** [comment]
resolved w/ september 20 update
