### ISSUE TITLE
Not Setting HP Causes New Characters to homepoint to Zone 0 after death.

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#3263]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Ran into this a few times, but it appears if a new character doesn't set their HP they'll homepoint to 'unknown area' / zone 0. Probably some error where new accounts don't start with a default homepoint. 

![Summerstone_2020 09 13_204219](https://user-images.githubusercontent.com/52988064/93035126-c6dd1800-f601-11ea-9379-72b84068ffd5.png)

**Comment by perkuprightmeow** [comment]
Just to add from someone's testimony on discord -- 
Character A blackscreened after creation and didn't the opening nation CS and had the unknown homepoint error. Had this bug happen to him. 
Character B got the starting cutscene and didn't have the homepoint bug / their homepoint was set. 

Which, now that I think about it this bug started popping up when the server added the starting nation CSs, so that all makes sense.

**Comment by rude-jerk** [comment]
Resolved in November 23, 2020 patch.
