### ISSUE TITLE
A Pose by Any Other Name quest isn't coded for RDM

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#3264]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
This could be fixed, but considering someone just had an issue with it on live Eden figured I'd post the bug here. He's on RDM trying to do this quest, and getting no response / instructions from Angelica. 
https://ffxiclopedia.fandom.com/wiki/A_Pose_by_Any_Other_Name?oldid=56659

Checked on DSP, and for some reason, even though it's commented, the quest doesn't check for RDM: 
```
elseif (mjob == dsp.job.WHM or mjob == dsp.job.BLM or mjob == dsp.job.SMN or mjob == dsp.job.PUP or mjob == dsp.job.SCH) then     -- Quest Start: Tunic (Whm/Blm/Rdm/Smn/Pup/Sch)
            player:startEvent(92,0,0,0,12608);
            player:setCharVar("QuestAPoseByOtherName_equip",12608);
```
Should be
``` 
elseif (mjob == dsp.job.WHM or mjob == dsp.job.BLM or mjob == dsp.job.SMN or mjob == dsp.job.PUP or mjob == dsp.job.RDM) then     -- Quest Start: Tunic (Whm/Blm/Rdm/Smn/Pup/)
            player:startEvent(92,0,0,0,12608);
            player:setCharVar("QuestAPoseByOtherName_equip",12608);
```

**Comment by 59blargedy** [comment]
resolved oct 4, 2020 update
