### ISSUE TITLE
BLU Burst Affinity not working on breaths/aspirs

### ISSUE THREAD

**Issue by DrfistMD** [EdenServer/community#3265]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [[X] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

I noticed during a Colibri party that MP Drainkiss was not properly consuming/working with Burst Affinity.  After the party I quickly tested this with another magical BLU spell and observed Burst Affinity was not being consumed.  I also tested this with Magic Carrot and Burst Affinity was not consumed as well.  I captured some video evidence of this and the URLs are below.

https://www.youtube.com/watch?v=iykdaS4I4lw

https://www.youtube.com/watch?v=jt86oXnMHuQ

**Comment by E5una** [comment]
BLU can definitely burst with other damaging spells, I do it all the time. MP Drainkiss use to work a year ago, but some number of months ago I noticed the buff stop being consumed and it didn't burst anymore. I can post a screenshot of a magic burst with a different spell though, I'll go capture.

**Comment by E5una** [comment]
I don't believe Wild Carrot should consume Burst Affinity in the first place, but I can't confirm that. MP Drainkiss should though and should be able to magic burst. Here is a screenshot of a normal damage dealing spell magic bursting through:

![image](https://user-images.githubusercontent.com/13668758/93225767-8fc15080-f740-11ea-91ba-6d008c489759.png)

Also one of a non-damaging spell to show that that works too:

![image](https://user-images.githubusercontent.com/13668758/93227668-9e106c00-f742-11ea-9962-27d714b344ae.png)

**Comment by 59blargedy** [comment]
changed title

**Comment by DrfistMD** [comment]
From doing some more random testing, looks like everything was consuming Burst Affinity so far except for MP Drainkiss and coincidentally, Flying Hip Press.  Both of these spells are consuming neither BA or CA.

**Comment by DrfistMD** [comment]
Also confirmed Poison Breath not consuming the Burst Affinity buff.

**Comment by E5una** [comment]
It’s probably breaths and drains/aspirs then based on other’s comments. If I’m remembering correctly, this weekend I magic bursted digest but it didn’t consume burst affinity, but the MB worked.

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 update.
