### ISSUE TITLE
True Will NIN AF Body NMs need tuning

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3268]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by E5una** [comment]
https://ffxiclopedia.fandom.com/wiki/True_Will

Per the wiki page, only the WHM should be sleepable, but all are sleepable on Eden.

![image](https://user-images.githubusercontent.com/13668758/93247473-54347f80-f75c-11ea-8cd5-be46b117bbad.png)

Wiki says they use their corresponding 2 hours, but I killed all 3 and none of them 2 houred.

**Comment by 59blargedy** [comment]
resolved in December 21, 2020 patch
