### ISSUE TITLE
Monster defense values still need some work 

### ISSUE THREAD

**Issue by Elysien** [EdenServer/community#3270]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://gyazo.com/3ee76d24a2376242a3a6b439e4f236a4

As per screenshot, you can see Arima on Samurai hitting Khimaira for 0 damage, equipment is pretty much best in slot with whats available minus the relic weapon, also used ATK food.

From memory, only enemies on retail you'd see this is on Adamantoise families, but this happened on Khimaira frequently, it also frequently happened on Jailer of Love. Probably many other things as well. 

Doesn't stop there though, even if my memory is wrong something is certainly up here. Arima frequently hit 0 on this Khimaira but the PLDs using Mac+1, no ATK food did not hit 0 at any point in the fight, no 0's at all.

**Comment by Slamm21** [comment]
The formula is 100% correct, the issue here is mob stats which will be fixed at some point, closing.

**Comment by VirtuosusFFXI** [comment]
To go into more detail, Khimaira's defense values are currently overtuned/incorrect. The reason you are observing melees hitting for 0 is because their attack vs Khaimira's defense on top of level correction are creating a scenario where pdif min is 0, and when pdif rolls 0 you're going to do 0 damage. 

On the other hand, 1 handed pdif min never goes below 1/6, which is why your THF never once hit a 0, but the two hander did.

**Comment by 59blargedy** [comment]
reopening (and retitling) until HNM defense values are changed, as those concerns are valid. Pretty confident in player pdif but aware of mob issues, thanks for the report.

**Comment by Slamm21** [comment]
pdifmin for 2h is 0 or -0.5 + 1.2 x cRatio whichever is higher, if the mob has super high defence this means 2h will hit for 0 often.
1h cannot go under 1/6

say if he has 900 defence, and you have 450 attack, your ratio is 0.5 your cratio is 0 and q won't come into play unless cratio is above 0.5 so you get no spike.

**Comment by Elysien** [comment]
The calculations detailed make sense to why that is happening, thanks for the insight

**Comment by Shoruto** [comment]
More defense reports #3220 #1249

**Comment by 59blargedy** [comment]
this was resolved around the time of the recent mob update
