### ISSUE TITLE
Adventuring fellow bond - monsters killed vs level cap correlation

### ISSUE THREAD

**Issue by jovegajo** [EdenServer/community#3271]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by jovegajo** [comment]
After obtaining Adventuring fellow bond level sufficient to keep them out for the maximum number of battles, summoning the adventuring fellow at a low level causes this to reset (or be bugged). Summoning the Fellow again at a higher level afterwards, the NPC will only stay out for the minimum 20 monsters again.

**Comment by tigo9** [comment]
You should only be able to increase max mobs past 20 by getting bond level 70, which was only possible with the recently implemented quest Blighted Gloom.

**Comment by KnowOne134** [comment]
correct its all about bond which is only capped to 70 atm after doing all the quests. 70+ bond is 25 kills max
