### ISSUE TITLE
Sleep has no effect on Empty

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3273]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Empty seem to be sleep immune on Eden. I only tested with Sheep Song and Lullaby on few non-light based Empty in Promyvion-Dem, but it seems like they are immune here, but not on retail. I tried researching any documentation of their sleep immunity online but I can't seem to find anything that suggests that they should work this way.

Please see the video uploaded of a retail capture by Dowzer of using different kinds of sleeps on different element Empty in the related ticket.

Version: 30181205_0

**Comment by Garphilius** [comment]
I also tried sleeping Empty in Promy-Mea and they were all immune to it. Nothing on the chat log shows up as well.

**Comment by KnowOne134** [comment]
Fixed 11/19 update
