### ISSUE TITLE
Amanomurakumo Quest Wait Times Incorrect

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3274]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

### **Eden Experience:**

**Trade items for Stage 2**
- JP Midnight Wait [Craft Time]
- 1 Earth Week Downtime Period _(Gives me default dialogue, as though I am meeting him for the first time. Won't discuss Stage 3.)_

**Trade items for Stage 3**
- Three? IRL Day Wait [Craft Time]
- Unknown Downtime Period _(Same as above, acts like he's never met me. Won't discuss Stage 4. Currently on this step, but will report back.)_

### **Retail Era Experience:**

**Trade items for Stage 2**
- JP Midnight Wait [Craft Time]

**Trade items for Stage 3**
- 1 IRL Week Wait [Craft Time]

**Trade items for Stage 4**
- 82 IRL Hours Wait [Craft Time]

_(No more timers past this point.)_

As you can see, the only wait times should be for the crafting of the weapons, and there should be no cooldown/downtime period in between stages.

Source: https://ffxiclopedia.fandom.com/wiki/Category:Relic_Weapons?oldid=359908

**Comment by Mikokiko** [comment]
I had the proper wait time when I did my Ghorn until a server crash / maintenance, then I could proceed to next step. Got told it was a known issue. Just writing it here since you opened a ticket.

**Comment by VirtuosusFFXI** [comment]
Seems like the problem may have something to do with this:

    -- No relic, or waiting until next conquest tally.
    elseif (itemid == nil or relicConquest > os.time()) then
        player:startEvent(10);

    -- Found a relic and conquest tally is not due (0, or passed), time to explain a stage
    elseif (itemid ~= nil and relicConquest <= os.time()) then
        eventParams = getRelicParameters(itemid);

Found here: https://github.com/DarkstarProject/darkstar/blob/7823190dbea8c76992a94ad1b1f9399e4853b3fd/scripts/zones/Castle_Zvahl_Baileys/npcs/Switchstix.lua

There should be no wait times to "explain" or move on to the next stage, nor should there be a check for conquest tally at all as far as I am aware. There is no downtime period both in era and current retail. The only waits should be for the crafting time after handing in upgrade items. These waits should be:

Stage 2: JP Midnight
Stage 3: 1 Week
Stage 4: 3 Days, 10 Hours

**Comment by VirtuosusFFXI** [comment]
Just to further clarify, the above wait times need to be applied here:

            -- Stage 1->2, wait until next game day
            if (eventParams[7] == 1) then
                player:setCharVar("RELIC_DUE_AT",getMidnight());

            -- Stage 2->3, wait RELIC_2ND_UPGRADE_WAIT_TIME (7200s / 2 hours default)
            elseif (eventParams[7] == 2) then
                player:setCharVar("RELIC_DUE_AT",os.time() + RELIC_2ND_UPGRADE_WAIT_TIME);

            -- Stage 3->4, wait RELIC_3RD_UPGRADE_WAIT_TIME (3600s / 1 hour default)
            elseif (eventParams[7] == 3) then
                player:setCharVar("RELIC_DUE_AT",os.time() + RELIC_3RD_UPGRADE_WAIT_TIME);
            end

RELIC_2ND_UPGRADE_WAIT_TIME should be 1 week
RELIC_3RD_UPGRADE_WAIT_TIME should be 3 days, 10 hours

As for the Conquest Tally checks:

local relicConquest = player:getCharVar("RELIC_CONQUEST_WAIT");

I really don't even know why DSP has this at all. Perhaps there was some reason they implemented this, to stagger time between each stage further for whatever reason?

**Comment by rude-jerk** [comment]
Resolved in November 16, 2020 patch.
