### ISSUE TITLE
Black Coffin... too easy?

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3275]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Felt like Black Coffin may have been a little too easy. Was dual boxing as THF/NIN & RDM/BLM. Thing that made it kinda a pushover was not needing elemental seal whatsoever to sleepga everything, including the captain. 
This is my sleep build, not shown is +16 Ele skill from merits:
![image](https://user-images.githubusercontent.com/11255886/93638209-8512ef80-f9bc-11ea-9be8-0ab845566b06.png)
From what I could tell based on testimonies, people were pretty adamant about needing elemental seal to sleep the mobs. I'm not sure if my setup is better than what the testimony's RDMs had back then... I doubt it though. 

As for actual issues with the fight itself besides difficulty:
1) Upon entering the fight, 2nd char (which wasn't the first to enter) was stuck at a black screen and couldn't move. Party list showed that char in Arrapago Reef. Turns out I had some hidden menu prompt that I wasn't able to see so hitting Esc zoned me in.
2) Instantly upon 1st char zoning in, Gessho was already engaged on one of the Crew. Had no time to buff or make a strategy on how to start or which to take down first. 
3) When Captain popped out, if he wasn't asleep my chat log was filled with him trying to WS if I was out of range.
![image](https://user-images.githubusercontent.com/11255886/93638497-05395500-f9bd-11ea-98ac-63188d22c762.png)
He never moved from the spot that he spawned on. Once I pulled threat off my RDM with my THF, the last "readies" he did was Vulcan Shot which -should- be an AoE attack but SOMETHING simply ate 1 of my shadows. I'm not sure if the Vulcan actually went off though. Could've just been a normal attack from the Captain with the various "Readies" bugging out and wiping his TP constantly because of it.
4) Related to other issues (including the above) on Eden, but Gessho, the Captain, nor the range minions ever moved into melee distance. Instead sat at a distance and did range attacks. Bit frustrating since Gessho does some good melee damage/TP moves when in range.

**Comment by FariskaEden** [comment]
Vulcan shot should just be single target, think the wiki is wrong on it stating that it's AoE. https://youtu.be/kw_lhwEGSYs?t=325 shows it only hitting the main target and they are standing close to other people.

**Comment by FariskaEden** [comment]
Actually looking more into it, I think Vulcan Shot is a conal attack? https://www.youtube.com/watch?v=OycR1Ar1tx0&feature=youtu.be&t=3200 would make sense since nobody else got hit by it in the previous video I linked. Additional effect seems to be a -50% defense debuff.

**Comment by KnowOne134** [comment]
resolved in October 4, 2021 update
