### ISSUE TITLE
Are spiders drop rate of spider web lower in western altepa desert?

### ISSUE THREAD

**Issue by danny20623** [EdenServer/community#3276]
### Checklist

version 30181205_0

I've been killing spiders in Western Altepa desert for a few hours and I've only gotten one drop. Wiki says they should be a 12% drop and I have th2.  

If you ignore th2 and let the drop rate be 12% the chance of this happening over 50 ~ kills (I've killed at least this many) would be 1.1%. th2 makes this lower then that :,(.

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Mozzy4Ever** [comment]
http://ffxidb.com/zones/125/desert-spider
Base drop rate is 5%. With TH2 that's 7%.

**Comment by danny20623** [comment]
what you linked says base is 6.2% and the th2 is 13.1%. If thats true then with a 13.1% drop rate my cahnces of going 1 drop in 50 is 0.067%

**Comment by Mozzy4Ever** [comment]
You should look at the sample size.
Also:
![image](https://user-images.githubusercontent.com/11255886/93656740-2700ff00-f9f2-11ea-8a79-5ca1760d5291.png)
This is how TH works

**Comment by danny20623** [comment]
alright thanks. with that its a 10% chance but thats alot better than the .067. Lastly though where did u find the 5% drop rate? I was using https://ffxiclopedia.fandom.com/wiki/Desert_Spider

**Comment by perkuprightmeow** [comment]
Just a general note, I *think* the drop rates in western and eastern Altepa spiders are swapped here. When i was testing the reworked TH system I was getting nothing in Western, but much higher / expected in Eastern.

**Comment by Mozzy4Ever** [comment]
> alright thanks. with that its a 10% chance but thats alot better than the .067. Lastly though where did u find the 5% drop rate? I was using https://ffxiclopedia.fandom.com/wiki/Desert_Spider

Because wiki is shit for drop rates. Based on the TH1/2/3+ drop rates (albeit, not high sample sizes) it's much more likely that it's a 5% rate and not 10%. It's one or the other since ffxidb shows 6.2% with TH0. If it was Base 10, the other rates would be much higher than displayed.

**Comment by danny20623** [comment]
nooo sorry mozzy what i meant by 10% is that the chance to kill 50 mobs with 1 drop at a 7% drop rate is a 10% chance.

Also perk i think ur right im currently 2/8 in eastern (i know this is a terrible sample size, im not making any claims just letting him know :D)

**Comment by Mikokiko** [comment]
I went 2/100 with Th4. So I decided to farm something else.

**Comment by 59blargedy** [comment]
just validated drop rates/rarity and eastern is set lower than western, at values that match ffxidb/th average of wiki, so doesn't seem like something to change. it is not a great farm, for sure. can try some of the higher percentage drop rates from spiders noted here:
http://www.ffxidb.com/items/838
