### ISSUE TITLE
Mp related weapon skill not using TP

### ISSUE THREAD

**Issue by kochiemonster** [EdenServer/community#3277]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Weapon skills, such as Starlight and Moonlight that give Mp back to yourself and party members are currently spammable .  MP is recieved, no changes to your TP

**Comment by 59blargedy** [comment]
resolved w/ september 20 update
