### ISSUE TITLE
Flash duration incorrect

### ISSUE THREAD

**Issue by him911** [EdenServer/community#3278]
Flash atm is lasting the full unresisted duration on every cast

### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Mozzy4Ever** [comment]
Pretty sure this is related to the magic resist formula not being correct

**Comment by Tjonke** [comment]
It might last full duration, but that full duration isn't correct either. It's supposed to last up to 12 seconds unresisted, on Eden it's  8 seconds. So 2/3 of proper duration for unresisted. Just tested on 10 mobs in West Ronfaure and every single flash wore after 8 seconds.

**Comment by him911** [comment]
I havent tested the exact duration(8 or 12) for normal mobs but on HNMs it never lasted beyond 2 seconds if you're lucky.

**Comment by Tjonke** [comment]
Yes, but for those 2 seconds you were almost untouchable by HNMs, here they have a ~50% chance to hit you even when flashed, so it's not just duration that is incorrect, it's the -accuracy as well.

**Comment by Shoruto** [comment]
Duration mentioned in #1300

**Comment by 59blargedy** [comment]
resolved in February 1, 2021 update. note that the logs dont seem to line up properly with actual coded duration, but that's a separate issue and not flash-specific.
