### ISSUE TITLE
King Ran Orge bat aggroes (h-10) (i-10) through wall

### ISSUE THREAD

**Issue by codercraig** [EdenServer/community#328]
King Ran Orge bat aggroes (h-10) (i-10) through wall on the way to tombstone, bat will attack 

![image](https://user-images.githubusercontent.com/10678415/48624080-6cda7f80-e9a3-11e8-88b6-9dd3010b7fae.png)

**Comment by beauxq** [comment]
possible duplicate of https://github.com/EdenServer/community/issues/193

**Comment by godmode** [comment]
Duplicate of #193
