### ISSUE TITLE
Pso'Xja Mimic issues.

### ISSUE THREAD

**Issue by PyreOgion** [EdenServer/community#3280]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Treasure Chest mimics in the (G-9) tower stop fighting after they use Death Trap.  
-Using /sitchair or resting causes them to aggro.
Clicking them while they are in the mimic mode does not aggro the player either.
![image](https://user-images.githubusercontent.com/32087703/93691889-8e758800-faa0-11ea-8714-8efe7c108ea1.png)

**Comment by 59blargedy** [comment]
resolved 10/11? update
