### ISSUE TITLE
Parade Gorget not work when weakened

### ISSUE THREAD

**Issue by Satirof** [EdenServer/community#3281]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

While weakened Parade Gorget won't active (even at 100% HP). I'm guessing this is because although I'm at 100% HP while weakened, this is under the 85% threshold when unweakened. But I can't find any information online stating that it shouldn't work when weakened.

https://ffxiclopedia.fandom.com/wiki/Parade_Gorget?oldid=354086

Steps:
1: Die
2: Get Raised
3: Get back above 85% HP (or full) - While weakened
4: Equip Parade gorget
5: Notice no MP regen

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
