### ISSUE TITLE
Petrifying Pair monsters move around/aggro at BCNM start.

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#3282]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

For some reason Killioa and Kalamainu aren't set to stay in their static locations at the start of the BCNM and roam once they're loaded in. This has caused several groups to wipe as they're buffing / not expecting it. 

Note for anyone reading this who want to do the BCNM : moving to the back left immediately will avoid this issue most of the time.

![image](https://user-images.githubusercontent.com/52988064/93727295-2c8c4f80-fb80-11ea-8125-be71053d8ad8.png)

**Comment by perkuprightmeow** [comment]
This is related to #1100 and #2097 that are both closed / resolved but this is still an issue.

**Comment by 59blargedy** [comment]
should be resolved sept 27 2020 but these guys are pesky, reopen if need be

**Comment by statuseffect** [comment]
Appears to be happening again.

**Comment by 59blargedy** [comment]
resolved by another dev in february 20, 2023 update
