### ISSUE TITLE
Subcraft too low

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#3284]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I'm trying to do a break synth.
The guide tells me that my sub needs to be 15 lvls below cap, however when I try to synth I get the message that I'm too low.

**Comment by danismyhero** [comment]
Eden currently requires to be within 10, instead of era retail 15.  I reported this directly to the devs months ago, must have forgot to github it.

**Comment by bkesecker** [comment]
Needs supporting evidence.  ffxiclopedia does not have a value for it in the target era.

**Comment by bliven-was-taken** [comment]
https://ffxiclopedia.fandom.com/wiki/Goldsmithing_Guide_by_Gatsby?oldid=101624

See the section for Shrimp Lantern and the section for Moonring Blade. This is a guide from August 2006.

**Comment by danismyhero** [comment]
https://www.bluegartr.com/threads/38803-Skilling-up-with-insufficient-subs

**Comment by mark-johnstone** [comment]
Is any more info needed for this to be progressed?

**Comment by Mozzy4Ever** [comment]
It'll get fixed when it gets fixed.

**Comment by 59blargedy** [comment]
Resolved in June 7, 2021 update
