### ISSUE TITLE
Spike / Fang Necklace GP Turn In

### ISSUE THREAD

**Issue by re1master** [EdenServer/community#3285]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The Bonecraft Guild Point item 'Spike Necklace' is displaying the incorrect total point value and turn in value per item. According to the Wiki History for 2007, the Spike / Fang Necklace should have a maximum turn in of 3680 along with the turn in rates of -

Fang (NQ) - 636
https://ffxiclopedia.fandom.com/wiki/Fang_Necklace?oldid=303005
Spike (HQ) - 872
https://ffxiclopedia.fandom.com/wiki/Spike_Necklace?oldid=303008

I just turned in 6 Fang Necklaces and received a total of 846 guild points, which equates to 141 GP per turn in.

![Capture](https://user-images.githubusercontent.com/2515375/94014494-9b80c880-fd79-11ea-88c6-417edfaf5477.PNG)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved oct 4, 2020 update
