### ISSUE TITLE
Mee and Quu spawns

### ISSUE THREAD

**Issue by Arckaina** [EdenServer/community#3286]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Mee deggi and Quu domi don't spawn in between spawn times anymore. They are supposed to be able to spawn at the top of any minute, of any placeholder, but they currently only spawn when a placehorder is respawning. So instead of killing a placehorlder, and Mee/Quu spawning 4 minutes after that placeholder died, it only will spawn 12 minutes (I think that's the respawn on placeholders) after the death of the placeholder, when the placeholder would naturally respawn.

**Comment by statuseffect** [comment]
https://github.com/EdenServer/community/issues/3255

**Comment by 59blargedy** [comment]
closing as duplicate
