### ISSUE TITLE
CoP 6-4 - Omega not using TP moves below 25% HP

### ISSUE THREAD

**Issue by rwaffle** [EdenServer/community#3288]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

In my last two fights against Omega (9/20 and 9/25), it did not use any TP movies below 25% hp. It should use Pile Pitch and Discharger. 

On the first fight, we did not use a CCB Polymer Pump. We had a Blue Mage stunning during the fight. It still should use a TP move at some point, but none were used from 25% HP until death. I do not have any video or logs of this fight. I thought this might be a fluke occurrence. However - 

On the second fight, we did use a CCB Polymer Pump, with some weapon skill stuns. From 25% until death was about 2 minutes and 15 seconds. Pumps should give amnesia for 1 minute, but no TP moves were used for the entire 2 minutes and 15 seconds. Screenshot of the battle logs are below. Logs are from time of CCB Polymer use until death.

![Omega](https://user-images.githubusercontent.com/50626123/94325133-f3325600-ff6a-11ea-8f53-feed1285ca07.PNG)
![Omega 2](https://user-images.githubusercontent.com/50626123/94325134-f4fc1980-ff6a-11ea-8f49-a4245cc4bedf.PNG)
![Omega 3](https://user-images.githubusercontent.com/50626123/94325137-f6c5dd00-ff6a-11ea-912a-48047b57c0e3.PNG)
![Omega 4](https://user-images.githubusercontent.com/50626123/94325138-f9283700-ff6a-11ea-8ce4-3a130b9826e6.PNG)

ver 30181205_0

**Comment by Zaekkor** [comment]
I recently did this fight as well, within the last week or so..and I noticed none of the "below 25%" moves were used either. I thought we were just lucky and/or our BLU was getting off good stuns, but this seems to suggest it might be a bug instead.

**Comment by ThoseWhoFight** [comment]
Noticed this during our fight today, and also on Iron's stream of the fight from the other day too in this video:
https://www.twitch.tv/videos/755118745?t=01h50m21s

Safe to say this is happening consistently and likely bugged.

**Comment by 59blargedy** [comment]
resolved oct 4, 2020 update
