### ISSUE TITLE
Yaa Haqa The Profane Drop problem

### ISSUE THREAD

**Issue by Herralaze** [EdenServer/community#3290]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version : 30181205-0
Hello
I've killed Yaa Haqa The Profane about 10 times in order to get an Earth Doublet, and here are the drops results :
7/10 : Frost Robe
3/10 :  **No Drop at all**
Now, I'm not concerned about not getting the Doublet at all, but I thought Yaa Haqa like Mee Deggi or Domi was supposed to drop one item of the 2 possible 100% of the time. Am I wrong, or is it a bug ?
Thx for your attention

**Comment by Shoruto** [comment]
Related to #939 and gives exception to Yaa Haqa Drop condition.

**Comment by 59blargedy** [comment]
this doesnt seem to be an issue as the mob can drop one or both, and though the drop rate is very high for frost robe it's not clear that it should be quite 100% based on sample size and wiki/ffxidb discrepancies.
