### ISSUE TITLE
Boreas Cesti not proccing 100% as it's supposed to in era

### ISSUE THREAD

**Issue by andrewj3191** [EdenServer/community#3293]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Boreas Cesti are supposed to proc 100%, but are not proccing

Source Eden's own Wiki:  https://classicffxi.fandom.com/wiki/Boreas_Cesti

**Comment by bkesecker** [comment]
There was a boreas_knuckles.lua, but I removed it because no such weapon exists and no references in the DB to it.  There is a boreas_cesti.lua that should be getting pulled in.

**Comment by andrewj3191** [comment]
Get Cy, does this mean it gets fixed on Sunday update?

**Comment by FriskArt** [comment]
Boreas cesti is not proc'ing whatsoever.

**Comment by KnowOne134** [comment]
Fixed 10/11/20
