### ISSUE TITLE
Hate Reset Issue

### ISSUE THREAD

**Issue by Phildian** [EdenServer/community#3296]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Client Version 30181205_0

Hate reset abilities such as Sand Trap from Anticans are completely resetting the hate on all players hit instead of leaving a minimal amount. This is causing monsters to go unclaimed and walk away if all players are hit. This should not be the case.

**Comment by 59blargedy** [comment]
resolved oct 4th update
