### ISSUE TITLE
"The Black Coffin" - Various Issues

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3297]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Ran into some issues with this fight. Here's the run down:

Issue 1: Couldn't get all characters into the BCNM.
Issue 2: Gessho aggroed the mobs immediately

To go into further detail:

I was dualboxing two characters, SAM and RDM. I clicked the Cutter door and chose "The Black Coffin", followed by the following text, similar to assaults:

"Connecting to server.
Please wait. 
Commencing transport to The Ashu Talif!"

The character that initiated made it into the BCNM, but my other character got stuck in a black screen (can still see chat log) and never left Arrapago Reef.

In addition to this, as soon as I loaded into the BCNM, Gessho was already engaged and fighting the crew members. I do not think this is correct behavior, as the wiki states the following: 

"Five Ashu Talif Crew will spawn, but will not attack until approached: 2 Rangers, 2 Red Mages, 1 Corsair."

**Comment by VirtuosusFFXI** [comment]
Followup: 

![blackcoffin](https://user-images.githubusercontent.com/49970272/94535938-25181680-0210-11eb-8989-04863db7a952.png)

**Comment by VirtuosusFFXI** [comment]
![blackcoffin2](https://user-images.githubusercontent.com/49970272/94536321-a2dc2200-0210-11eb-90b9-53d2f5f5dfc0.png)
![Lin_2020 09 29_045954](https://user-images.githubusercontent.com/49970272/94536329-a5d71280-0210-11eb-9a16-60ba31ebf579.png)

**Comment by deepbreathingeden** [comment]
![1612766398802](https://user-images.githubusercontent.com/53072734/109506331-f354f580-7ab6-11eb-945c-7c2f0a2e59ef.jpg)

**Comment by falzum** [comment]
To add to this my friend attempted the fight yesterday and got in with both characters no problem but said the mobs instant aggro'd when he zoned in. 

Said 2nd wave instant aggro'd as well when they spawned and had to kite them to recover

**Comment by KnowOne134** [comment]
resolved in October 4, 2021 update

**Comment by statuseffect** [comment]
Zone crashed upon defeateing the captain.

**Comment by Mozzy4Ever** [comment]
> Zone crashed upon defeateing the captain.

Would create a new bug report for this as it's a different issue and this one is closed
