### ISSUE TITLE
Incorrect Guild Points

### ISSUE THREAD

**Issue by Kharnek** [EdenServer/community#3298]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

I turned in my daily Clothcraft GP item as a 75 Clothcraft. The item was headgear. I crafted and turned in a mix of NQ and HQ to go from 20.5k to 21.7k GP. Went to trade more in and would not accept more headgear(no dialogue) though I should have been able to get more GP from it. I noticed my Guild Points had risen dramatically to 87.5k. Hoping to fix the issue I relogged my character and my guild points had risen even further to 153k. I checked to see if my Guild Points in currencies menu under Status would maybe show the correct amount of 21.7k but shows 218k. I next tried a full client shut down and restart and GP became 284k. 

![ArenzenGP](https://user-images.githubusercontent.com/63361940/94634014-eda37b80-029c-11eb-8480-e8a423775f94.png)
![ArenzenGP2](https://user-images.githubusercontent.com/63361940/94634016-ee3c1200-029c-11eb-8bd4-5fc3e771f9d0.png)
![ArenzenGP3](https://user-images.githubusercontent.com/63361940/94634018-ef6d3f00-029c-11eb-9e08-c838a8013bb3.png)
![ArenzenGP4](https://user-images.githubusercontent.com/63361940/94634021-f005d580-029c-11eb-9380-70c41f3044a3.png)

**Comment by deepbreathingeden** [comment]
![bbc for juul](https://user-images.githubusercontent.com/53072734/109506354-f819a980-7ab6-11eb-9d88-9485681e1eff.jpg)

**Comment by 59blargedy** [comment]
resolved by another dev in february 20, 2023 update
