### ISSUE TITLE
Seagull Grounded Debaucher immune to Sheep Song

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3299]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

According to the wiki page, the Debaucher in Seagull Grounded should be sleep immune but vulnerable to Lullaby. My understanding is that Sheep Song = Lullaby, but someone who knows more would need to confirm this for me. If so, the Debaucher need to be updated to have Sheep Song vulnerability as well, since it is currently immune to Sheep Song.

Disclaimer: I have not tested Sheep Song on other "Doomed" family mobs,  to know if this a mob family issue, and I have not tested Lullaby on the Debaucher to know if the real issue is that it is immune to all sleeps on Eden

https://ffxiclopedia.fandom.com/wiki/Seagull_Grounded

version 30181205_0

**Comment by VirtuosusFFXI** [comment]
Might have to do with it being flagged as NM or something? It cons Impossible to Gauge.

**Comment by KnowOne134** [comment]
Need to change 
mob:addImmunity(dsp.immunity.SLEEP)
To
mob:addImmunity(dsp.immunity.DARK_SLEEP)
