### ISSUE TITLE
XP Bands

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#33]
XP bands give 15,000 exp at the moment. This is enough to get through the dunes on one charge. It should be nerfed

**Comment by roriffxi** [comment]
This was an intentionally left in by Godmode, it's in the eden starts tomorrow announcement

**Comment by godmode** [comment]
It was left this way due to the exp tables being reverted to their original values. The setup is made this way so that people can level just as fast as they did on Kupo but they can't power level extremely quickly.
