### ISSUE TITLE
Orcish Warlord Bugged spawn position ( cant target / in wall )

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3300]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

In monastic cavern in the Genkai area where the Beastmen king spawn there is supposed to be 1 hexspinner + 1 warlord NM.  I went to farm stonega scrolls and saw on widescan that the Warlord was either bugged or someone get it stuck there. Didnt bother make a gm call for that but if you could look into it would be appreciated.

**Comment by Mozzy4Ever** [comment]
Doesn't spawn there. Happens when someone drags the mobs to the zone line. They don't path back all the way.

**Comment by ElectronicMan83** [comment]
The hexspinner is know to get stuck on bottom of the ramp. Warlords I never figured how he could end up lost in the wall so far.

**Comment by deepbreathingeden** [comment]
![1612766336404](https://user-images.githubusercontent.com/53072734/109506341-f5b74f80-7ab6-11eb-9410-9c83566e83eb.jpg)

**Comment by InoUno** [comment]
Resolved in May 31st, 2021 update.
