### ISSUE TITLE
Luminous Drape (Jailer of Love/Yovras) charm effect duration is far too long

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3302]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Jailer of Love's charm effect lasts around a minute (or more?) on Eden when unresisted. This likely is the case for the entire yovra family as well. This does not match up with numerous reports from era.

### Examples:

1) > If hate shifts to melee under it, it can use all its TP moves, including charm (will only hit those directly under it, and it usually wears off before the melee go to hit the tank).

Source: https://www.bluegartr.com/threads/54989-Jailer-of-Love-Questions-Help?p=1918294&viewfull=1#post1918294

2) > If your tank does get hit with charm remember its a hate reset move so have your dd back off a bit. It doesn't last long.

Source: https://www.bluegartr.com/threads/54989-Jailer-of-Love-Questions-Help?p=1918519&viewfull=1#post1918519

3) > The worst that could happen is a ton of charmed melee running after the tank, but the charm doesn't last long at all

Source: https://www.bluegartr.com/threads/50147-Jailer-of-Love-Help?p=1757540&viewfull=1#post1757540

4) > Even better is Draw hate, get Charmed, and have a free hate reset, typicaly charm lasts 10 seconds, if that.

Source: https://www.bluegartr.com/threads/50147-Jailer-of-Love-Help?p=1758956&viewfull=1#post1758956

5) > Also, JoL's Charm generally only lasts about 2-10 seconds, a quick Sleepga and a follow up Curaga and its basically like you pressed a button to reset your hate.

Source: https://www.bluegartr.com/threads/82405-JoL-Strategy?p=3121155&viewfull=1#post3121155

6) > my ls has only done a few JoLs and charm only happened once, it wore off before anyone did any damage to the pld at all

Source: https://www.bluegartr.com/threads/51761-Sheer-animosity-and-JoL?p=1806659&viewfull=1#post1806659

7) > JoL charm is really short usually. Always wore off before we reach the tank (who wasnt even kiting).

Source: https://www.bluegartr.com/threads/51761-Sheer-animosity-and-JoL?p=1808642&viewfull=1#post1808642

8) > ルミナスドレープは範囲魅了で、効果時間はランダムで割りと短めなんでが
合同先のLSにレリック最終の鎌を持ってる人が居たので非常に怖いWSでも有りました（ぉ
（ちなみにこのWSを食らうとHateリセットが出来ます。）
Luminous Drape's AoE Charm length is random but rather short, but it was kind of scary since the LS we teamed up with had the Final Version Relic Scythe. (Also, when Charmed, your hate is reset versus JoL)

Source: https://www.bluegartr.com/threads/35381-Absolute-Virture-Blog-Tranlation?p=1145352&viewfull=1#post1145352

**Comment by 59blargedy** [comment]
resolved in January 18, 2021 update
