### ISSUE TITLE
Royal Jelly - sometimes Princesses get stuck/unkillable and won't turn into Queen

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#3303]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Not sure what triggers it, but sometimes 1-2 Princess Jellies will get stuck in the middle of the BCNM and won't turn into the Queen. As a GM I can fix this for someone by using !mobhere on a Princess (it will instantly despawn and the Queen will pop in the middle), but figured a bug report should go in about it.

**Comment by rude-jerk** [comment]
Resolved in November 30, 2020 patch.
