### ISSUE TITLE
Beastmaster job not unlocking.  Kraken aggroing during cutscene.

### ISSUE THREAD

**Issue by tjkleens** [EdenServer/community#3304]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
After speaking to the beastmaster quest start NPCs I traveled to the spot with the flowers.  I was able to select the flowers and activate the cut scene while sneak oil was still in effect.  I did not attempt to move my character once the cut scene started. 
 During the cut scene the Kraken aggroed and killed me.  I allowed the cut scene to finish.  After the cut scene was done my player fell to the ground and I returned to Jueno.  I returned to the quest NPCs door and instead of it finishing the quest and him giving me the whistle, he repeats that I need to go find the flower.  
ver. 30181205_0

**Comment by tjkleens** [comment]
Sorry I forgot to mention the characters name I was using was Hindsight.  The incident occurred about 10 min before I filed the issue above.  Saturday 2:10ish pm est.

**Comment by mlandrum22** [comment]
Yeah this is normal Eden behavior. I died in a cut scene for a windy mission in the Temple (gd bees) and had to get another key and do the CS again.

**Comment by KnowOne134** [comment]
fixed 11/9 update
