### ISSUE TITLE
Goobbue Humus Drop Rate

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#3305]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
ver 30181205_0
### Details
Killed about 200 of these with TH4, no drop (both old and elder in the tree)
Drop rate should be 8% with TH4 category.

**Comment by mlandrum22** [comment]
It was set to 4.9% on base DSP so it was likely floored to 1%

**Comment by jrwhite811** [comment]
Has there been any update on this? Is anyone able to get the drop in the tree?

**Comment by 59blargedy** [comment]
resolved in January 4, 2021 patch
