### ISSUE TITLE
Diabolos CoP 3-5 "Completely Resisting" Silence

### ISSUE THREAD

**Issue by Spiffly** [EdenServer/community#3306]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

Completed CoP 3-5 recently and Diabolos resisted silence which out group didn't think or remember was possible. Screenshot attached to show the resist. He also resisted and Elemental Seal Silence too. His job is BLM/DRK according to wikipedia and neither job has the Resist Silence trait, nor is there any mention of him additionally having this trait at 40 cap or uncapped.
![cop diabolos resist](https://user-images.githubusercontent.com/59734926/95018410-82202c00-0657-11eb-8b13-5becd983e3cd.png)

**Comment by Shoruto** [comment]
What was your enfeebling skill level?

**Comment by Spiffly** [comment]
It wasn't me that casted but a friend. They were on WHM and i would presume capped Enfeebling for 40 cap as they're 75.

**Comment by 59blargedy** [comment]
resolved in January 4, 2021 patch
