### ISSUE TITLE
Beastmaster Sic Recast Merit not working

### ISSUE THREAD

**Issue by githubsellsinfo** [EdenServer/community#3307]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Sic Recast Merit level 2 not working.  Timer goes down from :30, to :29 after first Merit.  Second Merit, timer remains at :29 and should be :28.

**Comment by KnowOne134** [comment]
fixed in 11/9 update
