### ISSUE TITLE
Imperial Agent Rescue: Mamool Ja's Lizard can agro the Dilapidated Gate under certain conditions.

### ISSUE THREAD

**Issue by danismyhero** [EdenServer/community#3308]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

While starting the grind for my next Yigit piece, found a strange bug with the BST pets and the gate.  If the person or persons with hate die or deagro the pet, it can start attacking the gate.

If you /assist the pet, you can then target the gates HP, and see that it is taking damage per hit.

The gate uses structure based TP moves.
https://ffxiclopedia.fandom.com/wiki/Gaea_Stream
https://ffxiclopedia.fandom.com/wiki/Category:Structures

![image](https://user-images.githubusercontent.com/49649778/95034753-7a2cb000-0688-11eb-9d67-ba0ec6ce9903.png)

https://youtu.be/7LQu1t3SpjY

**Comment by MonkeyAce9** [comment]
This happened to me today, all 3 of us had just died and then the mob turned onto the gate and started attacking it, I even saw the gate use a few moves. We had aggroed the 2 mobs on the way to the North gate.

![Awesome_2020 11 06_123008](https://user-images.githubusercontent.com/51872113/98366542-105b4980-202c-11eb-82ff-3acd2cd8beff.png)
![Awesome_2020 11 06_123013](https://user-images.githubusercontent.com/51872113/98366559-16512a80-202c-11eb-86f4-0068e24c6ec5.png)
![Awesome_2020 11 06_123026](https://user-images.githubusercontent.com/51872113/98366575-1c470b80-202c-11eb-9a18-dbbc28062815.png)

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
