### ISSUE TITLE
jobs with pets arent able to summon there pets inside crawlers nest

### ISSUE THREAD

**Issue by Vongolabige** [EdenServer/community#3309]
### Checklist
no clue how to do this,,the tittles says it all tried to zone it does spawn in rolanberry hils but not crawlers nest
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by Vongolabige** [comment]
no clue how to do this,,the tittles says it all tried to zone it does spawn in rolanberry hils but not crawlers nest

**Comment by setsuk0** [comment]
this happened before and was fixed, look like it's happened again? See #2890

**Comment by KnowOne134** [comment]
Known issue and fix coming

**Comment by KnowOne134** [comment]
Fixed 10/11/20
