### ISSUE TITLE
No weather in Xarcabard

### ISSUE THREAD

**Issue by vrusso-kong** [EdenServer/community#3310]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

I have been zoning in to Xarcabard several times throughout the day to farm elementals and no weather has occurred in several hours of trying, I have tried different ways of zoning to see if its a client issue and several people have confirmed to see the same thing I have. The sky is also pitch black at night, which is very unusual.

**Comment by jrwhite811** [comment]
This issue seems to also be effecting Crawlers' Nest. Have spent close to 20 hours over two days in the zone waiting for weather to do BLM AF2 quest and there has been no weather there whatsoever.

**Comment by 59blargedy** [comment]
an issue was found and will be resolved upon normal patch day at the latest. thanks for the heads up!

**Comment by ZariusCane** [comment]
I don't think any of the weather but fog was showing up across all zones.

**Comment by ThoseWhoFight** [comment]
Can confirm it's happening in Al'Taieu as well. When  the weather swaps to fog (didn't even know it could do this) it changes to the normal blue/pink, but as soon as the zone weather clears again it will go back to being really green.

**Comment by KnowOne134** [comment]
Fixed 10/11/20
