### ISSUE TITLE
Solicitor Warp Not Working [Promy-Vahzl]

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#3311]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)

### Details

Not sure why this hasn't been reported, but the warp to the 4th floor of Promy-Vahzl (Solicitor) doesn't work currently. Have gotten multiple GM reports about it, and just noticed a bug report hasn't been made.

**Comment by ElectronicMan83** [comment]
Worked fine on thursday night, we had around 4 people helping us from that floor. Not 100% broken.

**Comment by 59blargedy** [comment]
resolved 11/2 update
