### ISSUE TITLE
Purgatory Bat in Newton are aggressive and should not be

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#3315]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Purgatory Bats in Newton Movalpolos are not supposed to aggro but they do. 

https://ffxiclopedia.fandom.com/wiki/Purgatory_Bat?action=history   The February 11, 2007 edit is specifically to say that these bats do not aggro here.

https://www.bg-wiki.com/bg/Purgatory_Bat 
This page also says they don't aggro

**Comment by KnowOne134** [comment]
Fixed in next update
