### ISSUE TITLE
Yhoator Jungle Harvesting nodes

### ISSUE THREAD

**Issue by ThecraftyLion** [EdenServer/community#3316]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Step1. Equip harvesting gear body, legs, feet
Step2. Harvest node
Step2. either broken sickle or not able to harvest

Maybe it is not of era, I am really not sure, however, Yhoator Jungle harvesting points have no items associated with them. I tried about 20 times to harvest the node but it either broke or was unable to harvest.

**Comment by 59blargedy** [comment]
resolved 11/16
