### ISSUE TITLE
 ToAUM-08: A Mercenary Life - Cutscene will not Trigger to move onto Next mission

### ISSUE THREAD

**Issue by DustMoonsugar** [EdenServer/community#3317]
I am unable to proc the cutscene to proceed into Mission 9. 
per the Eden Wiki: https://classicffxi.fandom.com/wiki/A_Mercenary_Life

Walkthrough
Wait until Japanese Midnight.
Return to Salaheem's Sentinels. The start of the cutscene marks the beginning of the next mission.

Reproducible steps: 

I Waited until Japanese Midnight for 2 earth days now. (10 AM US CST for my time zone)
I always zoned in on a +50 Level Class (Warrior)
Walked around the desk in the office in all directions in case the trigger is directional. No luck
Zoned from 300gil trade guy in Port Bastok and tried from Residential area in Whitegate.
Naja just keeps telling me that she is fired up.

Version: 30181205_0

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by KnowOne134** [comment]
Gms !setplayervar missionWaitAht 1

Looks to be that time was changed from actual time based to game day wait. File a gm ticket to have corrected

**Comment by KnowOne134** [comment]
Fixed 10/11/20
