### ISSUE TITLE
Cactrot Rapido

### ISSUE THREAD

**Issue by Goto28** [EdenServer/community#3318]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

cactrot should have some double attack, currently does not have any...think it also hits a little too weak

everything else looks good

https://www.youtube.com/watch?v=jaKzxEZ8kH0&ab_channel=Lpg54 - for da 'proof'

**Comment by 59blargedy** [comment]
resolved in February 1, 2021 update
