### ISSUE TITLE
Glittering Ruby not functioning correctly

### ISSUE THREAD

**Issue by JDFlashffxi** [EdenServer/community#3319]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

Seems like currently Glittering Ruby isnt giving the random stat buff but instead tries to do damage to everyone in range even carby, its always for 0 damage though, tried serveral times, zoned, and reloaded. same results
![wtfsdaad](https://user-images.githubusercontent.com/48188921/95547323-b6d21180-09d0-11eb-8384-b2dbec42d429.PNG)

**Comment by 59blargedy** [comment]
resolved 10/18
