### ISSUE TITLE
Tarasque doesn't have blaze spikes

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3320]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Per the wiki, Tarasque should have blaze spikes, yet he didn't in our fight at all, despite being hit by him. 

https://ffxiclopedia.fandom.com/wiki/Tarasque
"Special Attacks: Blaze Spikes.
Tarasque won't use his Blaze Spikes until he sucessfully lands a hit on the player."

Its unclear whether or not they should be dispelable, some links say no some say yes, but there's an allakhazam post in 2006 that makes it sound like they became dispelable at some point prior to our era date:

"His blaze spikes can be dispelled, they must've changed it in an update or a glitch but I just watched the RDM I duoed Tarasque with dispel his spikes. Even so he's nothing tough to bring down, I just used my bloody bolts to regen HP to counter-act the spikes."

You can see in this 2010 video that he has these blaze spikes right away after landing a hit.

https://www.youtube.com/watch?v=aTtsNMMUTek

Not sure if worth noting for coding, but a testimonial on the wiki page also says:

"Just stole his Blaze spikes with Aura steal. Lasted for ca. 1 hour on me and delt around 50 dmg a hit. --Auriane 07:15, 16 August 2008 (UTC)"

Here is our battlelog showing me getting hit and no spikes:
![image](https://user-images.githubusercontent.com/13668758/95616999-bbcaab80-0a38-11eb-8626-ae74e6244c39.png)
![image](https://user-images.githubusercontent.com/13668758/95617043-ce44e500-0a38-11eb-8654-a64c6b8af448.png)
![image](https://user-images.githubusercontent.com/13668758/95617094-dc930100-0a38-11eb-9566-da16da6ab4d1.png)

version 30181205_0

**Comment by KnowOne134** [comment]
Corrected 11/19 update
