### ISSUE TITLE
Dynamis - Mob Parry Combat Skill

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3321]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Orc, Yagudo, Quadav, & Goblin mobs/NMs in Dynamis zones should be able to parry if they are jobs that have parrying combat skill (WAR, RDM, THF, PLD, DRK, BST, BRD, SAM, NIN, DRG). Currently these mobs do not parry at all.

Unsure of how much parrying skill they should have but they might be capped out at their jobs respective ranking for parrying for their level. Testing on retail has also shown that Hydra & Kindred do not parry. 

![image](https://user-images.githubusercontent.com/46270382/95627718-a8284080-0a4a-11eb-880a-a3cd1da462bb.png)
![image](https://user-images.githubusercontent.com/46270382/95627737-ae1e2180-0a4a-11eb-9fee-f2ea4024d7ba.png)
![image](https://user-images.githubusercontent.com/46270382/95627746-b24a3f00-0a4a-11eb-80f4-8986cf018bdc.png)
![image](https://user-images.githubusercontent.com/46270382/95627760-b70ef300-0a4a-11eb-8fc6-1f399d92005d.png)
![image](https://user-images.githubusercontent.com/46270382/95627768-baa27a00-0a4a-11eb-9ad5-081b08bd4b17.png)
![image](https://user-images.githubusercontent.com/46270382/95627793-c8f09600-0a4a-11eb-9d94-c8f38e48522c.png)
![image](https://user-images.githubusercontent.com/46270382/95627796-cc841d00-0a4a-11eb-98c3-ce3b2a92acee.png)
![image](https://user-images.githubusercontent.com/46270382/95627802-d0b03a80-0a4a-11eb-8f47-b81f17191971.png)
![image](https://user-images.githubusercontent.com/46270382/95627810-d443c180-0a4a-11eb-86b0-73a14ca65de0.png)
![image](https://user-images.githubusercontent.com/46270382/95627868-ec1b4580-0a4a-11eb-9a6a-3e33d1e3d037.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
