### ISSUE TITLE
Dynamis - Frypan TP Move

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3322]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Goblin family mobs/NMs in Dynamis should be able to use Frypan like they do with other Moblin TP moves. Currently they do not use this move at all.

https://www.youtube.com/watch?v=_N_AWD2ByRM&feature=youtu.be&t=27 - Capture / .log file for Frypan
https://www.youtube.com/watch?v=Hs5rCEyEbHw&t=90s - 2007 Dynamis Jeuno where Frypan is used

version 30181205_0

**Comment by 59blargedy** [comment]
resolved 11/2 update
