### ISSUE TITLE
Seigan interaction with third eye issues

### ISSUE THREAD

**Issue by Goto28** [EdenServer/community#3323]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Aside the various other bug reports about the interactions here with Seigan Third Eye not anticipating enough/etc, there is another issue that has gone unreported. Using Seigan then using third eye followed by immediately cancelling the Seigan ends up breaking the third eye effect, rendering it totally useless. The third eye icon will still be present, but it will not do anything whatsoever.

Correct behavior , the way it should work, is using Seigan then Third Eye, then cancelling the Seigan and the remaining third eye effect should be good for one anticipation, as if you used third eye without seigan at all; that same effect. But as it stands doing this simply breaks the third eye completely as it stands.

**Comment by 59blargedy** [comment]
should be resolved from 10/18 update
