### ISSUE TITLE
NM not resetting HP when party wipes

### ISSUE THREAD

**Issue by Dorinorin** [EdenServer/community#3324]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

wiped to Shikigami Weapon at 12% HP. Home Pointed, went back. Took approximately 10 minutes to get back to Ro’Maeve; when reclaimed was at 12% HP still.

**Comment by deepbreathingeden** [comment]
![1614324985261](https://user-images.githubusercontent.com/53072734/109506208-d1f40980-7ab6-11eb-9269-f51c70d85bf1.jpg)

**Comment by rude-jerk** [comment]
Resolved in May 10, 2021 update
