### ISSUE TITLE
qm10 in Phomiuna Aqueducts does not open door

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3325]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

qm10 (ID 16888123) at J-7, 2nd floor of Phomiuna Aqueducts does not open the door to the southern hallway as it should. Oil Lamp (ID 16888057) on the inside of the door does open the door that qm10 is supposed to, so the lua for it could probably just be copied to qm10 and be good to go.

**Comment by 59blargedy** [comment]
resolved 10/18
