### ISSUE TITLE
Vendor stack sizes for tools is 99, should be 12

### ISSUE THREAD

**Issue by rpcon** [EdenServer/community#3326]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Windurst vendors for HELM tools (pickaxes, sickles) show stack sizes of 99, although attempting to buy more than 12 will only result in 12 being bought. Checked windy only, not other cities.
![180902](https://user-images.githubusercontent.com/12719393/95667507-69ff4f80-0b24-11eb-8c1b-087a9bb7f43d.png)

**Comment by deepbreathingeden** [comment]
![1614121272006](https://user-images.githubusercontent.com/53072734/109506204-d02a4600-7ab6-11eb-9f76-1637eafdb27f.jpg)

**Comment by 59blargedy** [comment]
i just checked on this and get groups of 12 from these vendors. i'm wondering if this was a /ver issue - closing out
