### ISSUE TITLE
Temenos - Western Tower TE Chest Bug

### ISSUE THREAD

**Issue by GalkaZajin** [EdenServer/community#3327]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Had a TE chest drop on the fourth floor with the lizards and could not click it on any character.

![image](https://user-images.githubusercontent.com/48496938/95688314-52cd6a00-0bd7-11eb-9878-10511aa94144.png)

This would have been our 3rd or 4th TE.
version 30181205_0

**Comment by bkesecker** [comment]
This should be fixed live.

**Comment by perkuprightmeow** [comment]
This just happened to a group on the first floor of Western Temenos.

**Comment by ThoseWhoFight** [comment]
My group did Temenos West the first week after the patch without any chest issues. Maybe group or patch version?

**Comment by perkuprightmeow** [comment]
It's an entry issue, not a chest issue we found out when next group's run went fine (and the entry for this group was buggy). 

Will open a separate ticket for that once we can isolate the issue.

**Comment by falzum** [comment]
We ran Western on Monday night and had no issues. We were a single party.

We're you in an alliance?

**Comment by ThoseWhoFight** [comment]
> We ran Western on Monday night and had no issues. We were a single party.
> 
> We're you in an alliance?

Negative, we were a 6 man party.

**Comment by 59blargedy** [comment]
believe this has been resolved (have heard no further issues with entry), so closing. can comment if this issue remains and will reopen
