### ISSUE TITLE
Cosmo-Cleanse price is wrong according to the era date

### ISSUE THREAD

**Issue by zippern** [EdenServer/community#3329]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Using the date given on the webside as seen under and using the history on https://www.bg-wiki.com/ and https://ffxiclopedia.fandom.com/ it's possible that the date used for this prise is wrong, it seems like the date for the price used is from https://ffxiclopedia.fandom.com/ January 28, 2007. the following links are the closes dates I found for November 20th, 2007.

https://www.bg-wiki.com/index.php?title=Cosmo-Cleanse&oldid=43266
https://ffxiclopedia.fandom.com/wiki/Cosmo-Cleanse?oldid=328795

Here you can see what the era price should 30k and not 50k.

http://www.classicffxi.com/about
"Eden was created in part to recreate the era experience as close as possible. We define era as anything that happened before the Wings of the Goddess release on November 20th, 2007."

**Comment by Mozzy4Ever** [comment]
It's not a bug. It's intentional

**Comment by zippern** [comment]
In the patch notes it says "Note that in-era cost for Cosmo-Cleanse is 50,000 gil.", using the era date given to us by eden that's not the right information, so if they want to make it era cost then it's a bug.

**Comment by bkesecker** [comment]
> The cost of Cosmo-Cleanse, required by each player for entry to Limbus, at retail release was 50,000 gil, and then in June of 2007 was changed to 30,000 gil.

Eden staff voted to start at 50K and transition to 30K at a later date.  This is not a bug and intentional as Mozzy indicated.

**Comment by zippern** [comment]
If that's the case then dont lie in the patch notes and say you made a custom change for eden that's out of era in the patch notes.

**Comment by KnowOne134** [comment]
getting heated in here... all of cop in eden is of original difficulty so in light of that we decided to make the entrance fee of the same, on release limbus was 50K. its said so in patch notes its said so on the npc when buying it. End of discusion
