### ISSUE TITLE
Apollyon NW - Floor #4 Missing Recovery Chest

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3330]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Reporting this bug on the account of someone else. Verified on test server after to make sure nothing weird was happening. The fourth floor with the wyverns and Fafnir mini-boss is missing a recovery chest, which is normally located in the Center/NE tree patch area.

![Apollyon-NW4](https://user-images.githubusercontent.com/49970272/95704860-3d306280-0c20-11eb-833e-e6bb3fb2ada7.jpg)

![Virtuosus_2020 10 12_001718](https://user-images.githubusercontent.com/49970272/95704884-4f120580-0c20-11eb-8037-294bb2ef7577.png)

**Comment by Zaekkor** [comment]
I also experienced this. I didn't get a chance to report it because I went straight to bed afterward. I thought it was weird that there was no chest.

**Comment by Satirof** [comment]
Also noticed this during my groups run today~

**Comment by falzum** [comment]
Same experience with us today. I thought our puller popped it on accident. I owe him an apology.

**Comment by andrewj3191** [comment]
> Same experience with us today. I thought our puller popped it on accident. I owe him an apology.

As the puller of that group, I am greatly offended

**Comment by 59blargedy** [comment]
resolved 10/18
