### ISSUE TITLE
Entering Apollyon sometimes sends you to the wrong location

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#3331]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

game version 30181205_0

Swirling vortices sometimes teleport a player to the wrong entrance of Apollyon. For example, a player may try to enter the SE side but be ported to the NW side. To replicate try to enter Apollyon from sea after obtaining the card, and sometimes a player from the party will randomly be on the wrong side.

**Comment by 59blargedy** [comment]
resolved in January 11, 2021 update
