### ISSUE TITLE
Dynamis - Mob 2-hour Usage

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3332]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently in Dynamis most mobs will use their job's 2-hour at the wrong percentage of HP. Testing on retail has shown that depending on the job of the mob their 2-hour activates at certain percentages. For example BST mobs could 2-hour at ≤94% or ≤89% or ≤84% HP remaining and when spawned the mob will randomly choose one of these values to use their 2-hour at. Dynamis NMs also seem to follow this rule. Most of this testing was done by slowly lowering the HP of mobs. There may be some ranges missing but this is what I've found.

WAR - ≤89% or ≤84%
https://i.gyazo.com/167e44c431d36ad2ac8e237d386e878a.mp4 - ≤89%
https://i.gyazo.com/da1af07bac48e943c8a49f3ee618cdd0.mp4 - ≤84%

MNK - ≤94% or ≤89% or ≤84%
https://i.gyazo.com/e5b82c5a1b96dea1f43f76679755a367.mp4 - ≤94%
https://i.gyazo.com/eb9fcb18a2d60922e4e46240805135d2.mp4 - ≤89%
https://i.gyazo.com/b2d6d36400a8d32328e985e3315db7fa.mp4 - ≤84%

WHM - ≤34% or ≤29%
https://i.gyazo.com/a8fb9350303a0aea30795c10289033dc.mp4 - ≤34%
https://i.gyazo.com/1c402c7d34c7f384900eebcc6f83d588.mp4 - ≤29%

BLM - ≤94% or ≤89% or ≤84%
https://i.gyazo.com/8017d8c6684ef1f83b1326f0fc8ab91c.mp4 - ≤94%
no footage but it should 2 hour at ≤89% as it's in between these values
https://i.gyazo.com/2eafe15518834a552c8583b0181cfeda.mp4 - ≤84%

RDM - ≤94% or ≤89%
https://i.gyazo.com/a16ccd0ada523a25f1c1107e9b0efcfb.mp4 - ≤94%
https://i.gyazo.com/accd7d84c726bba91482095d5f419b11.mp4 - ≤89% NM

THF - ≤54% or ≤49% or ≤44%
https://i.gyazo.com/42e59bd827e12b0b242d59515a5abcb3.mp4 - ≤54%
https://i.gyazo.com/c5f9e9ee43ac0328806ed98f2ad506cc.mp4 - ≤49%
https://i.gyazo.com/859a318f642b91084a499bab4eb954fc.mp4 - ≤44%

PLD - ≤54% or ≤49% or ≤44%
https://i.gyazo.com/51ca10c1cc5df9d888041da442dbb8f3.mp4 - ≤54%
no footage but it should 2 hour at ≤49% as it's in between these values
https://i.gyazo.com/d273c893cb2fa46626ec16593de6b30d.mp4 - ≤44%

DRK - ≤89% or ≤84%
https://i.gyazo.com/af3c327af278c76166cfd9fdb6f9a87c.mp4 - ≤89%
https://i.gyazo.com/8818bb60fdea5b548ad42812a5e2001f.mp4 - ≤84%

BST - ≤94% or ≤89% or ≤84%
https://i.gyazo.com/7ec65d92fd205e949516b20a20bc4fdc.mp4 - ≤94%
https://i.gyazo.com/c39bffd79aaab805f41012884a688239.mp4 - ≤89% NM
https://i.gyazo.com/5a006d549e5249f7494370b8b56a5963.mp4 - ≤84%

BRD - ≤94% or ≤89%
https://i.gyazo.com/56529d931caf0df3fb25fb7a4ad414e7.mp4 - ≤94%
https://i.gyazo.com/527e634173c57477bcf629fceecfe002.mp4 - ≤89% NM

RNG - ≤79% or ≤74% or ≤69%
https://i.gyazo.com/6532df91525f86e7060d40d473d78ebe.mp4 - ≤79%
https://i.gyazo.com/39d8fdfdcb8f51a1594e7982259ff6f0.mp4 - ≤74%
https://i.gyazo.com/cafe9bd67798129ab2b26828c5b3d143.mp4 - ≤69%

SAM - ≤94% or ≤89% or ≤84%
https://i.gyazo.com/3f75e28c49f92add1bbd3cb28f009709.mp4 - ≤94%
https://i.gyazo.com/bd546194692989ce42a63ef8c1e2885c.mp4 - ≤89% NM
https://i.gyazo.com/7d1698b3022a94abd89b623260cec996.mp4 - ≤84%

NIN - ≤24% or ≤19%
https://i.gyazo.com/1bfc5a1f48ac952ca7220aec7eecc3d5.mp4 - ≤24%
https://i.gyazo.com/40d1e1673341156da62fff574f35e195.mp4 - ≤19%

DRG - ≤94% (have not seen any variation on this at all)
https://i.gyazo.com/bbdad3a43bc0805f5ee594a591d1f04b.mp4 - ≤94% NM
https://i.gyazo.com/42c9348ea63b2668f977e152723b37fe.mp4 - ≤94%

SMN - ≤54% or ≤49% (won't 2hr if pet is dead)
https://i.gyazo.com/95796dd0d6e571f503d434746ccf4f01.mp4 - ≤54%
https://i.gyazo.com/24ab3c780fb611bac4f3742e697583c7.mp4 - ≤49%

version 30181205_0

**Comment by 59blargedy** [comment]
resolved 11/2 update
