### ISSUE TITLE
Using Thief's Tools as /THF Consumes the Tool - Potentially Able to Pick Chests/Coffers?

### ISSUE THREAD

**Issue by rwaffle** [EdenServer/community#3337]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Used some Thief's Tools on a coffer in SSG as DRG/THF. Since THF main should only be able to pick chests and coffers, nothing should have happened. However, trading the tools resulted in the 'fails to open chest' text, that you receive when a THF fails to pick a lock. This result also consumed the tools. Given that nothing should happen, the tools should not be consumed and I would assume some other text should be returned (needs verification).

This leads me to think that either picking locks is possible on /THF (which it shouldn't be), or at least the failure portion of that code is active for /THF, which I don't believe should be the case either.

![Capture](https://user-images.githubusercontent.com/50626123/95902111-4fb2b500-0d62-11eb-9f6a-74a6bbdbc74b.PNG)

ver 30181205_0

**Comment by rude-jerk** [comment]
https://github.com/project-topaz/topaz/pull/1381

**Comment by 59blargedy** [comment]
resolved 11/2 update
