### ISSUE TITLE
Appolyon SW

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#3338]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

The elementals on the last floor are way too tanky, they shouldn't have that much physical dmg reduction and they are also immune to Souleater dmg. Kraken Club DRK was dealing 40 dmg/swing to them.

**Comment by Tjonke** [comment]
Dark Elementals were also unable to be slept by either Lullaby or Dark based sleeps. Light Elementals were able to be slept by both

**Comment by Slamm21** [comment]
they are not immune to souleater damage at all. My damage doubled with SE

> Souleater is subject to physical damage modifiers, examples being open-mouthed Hpemde(+100% damage), and Slimes(-50% damage); additionally the modifiers for damage type (slashing, blunt, or piercing) based on the weapon used will affect the damage dealt by the ability--e.g., Skeletons take extra damage from Souleater when used with a Club.

the physical damage reduction affects souleater

**Comment by E5una** [comment]
Relating to https://github.com/EdenServer/community/issues/3132 for the sleep issue.

**Comment by DeuceFFXI** [comment]
@Tjonke Did SW apollyon last week and was going to report this myself.  The elementals acted as though they were elementals out in the open world and took their normally reduced physical damage, which is not accurate for SW apollyon top floor.

**Comment by InoUno** [comment]
Damage resistance resolved in Nov. 2nd update.
