### ISSUE TITLE
Windhurst outpost npc buy/sell problem.

### ISSUE THREAD

**Issue by SonicUK** [EdenServer/community#3339]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Windhurst outpost npc not showing the buy/sell window after selecting it.
client version 30181205_0

**Comment by Spiffly** [comment]
Same issues as #3328 but a different vendor.

**Comment by 59blargedy** [comment]
duplicate/resolved
