### ISSUE TITLE
Newton Movalpolis Bugbear Watchman

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#334]
#79 says it was fixed, however the Bugbear Watchman at G-9 of Newton Movalpolos are moving again and are supposed to be stationary according to https://ffxiclopedia.fandom.com/wiki/Black_Mage_Solo_Guide#64-71_-_Newton_Movalpolos

**Comment by icariumkupo** [comment]
Last I checked, there furnaces also still do not operate correctly. Getting past the southern gate is not possible

**Comment by pksweets** [comment]
![Leku_2019 03 17_014536](https://user-images.githubusercontent.com/27723566/54487736-a68a9c80-4856-11e9-84da-69f6a94cf8f8.png)
This is apparently still happening. Kinda ruins an important BLM solo camp D:
