### ISSUE TITLE
Black screen in Dufulks Tower

### ISSUE THREAD

**Issue by zernon916** [EdenServer/community#3340]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Screen goes black when clicking the gate in defulks tower floor 1 in consulate area to take you to floor ten.

**Comment by Mozzy4Ever** [comment]
That 3rd check box is important for these kind of issues

**Comment by 59blargedy** [comment]
duplicate/resolved
