### ISSUE TITLE
Defulks Tower Screen goes black after entering a gate/door in consulate area.

### ISSUE THREAD

**Issue by zernon916** [EdenServer/community#3342]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205, I use windower.

Enter Dufulk tower from qufim.  Turned left, headed towards stairs.  Went to the right path.  Traded Tower Key to door. Door opened.  Went to next gate.  Selected it.  HIt enter.  Asked if I wanted to enter. I said yes.  I had a giant chasing me.  Screen went black. I died. Screen stayed black after death.  Had to force close the client, reopen game to get display back. You may be able to skip the dead part ^.^

Screen goes black when clicking the gate in defulks tower floor 1 in consulate area to take you to floor ten.

**Comment by 59blargedy** [comment]
resolved 10/18
