### ISSUE TITLE
Unable to Challenge Maat after a ToAU Limit Break

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#3343]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

If you do your final LB with a ToAU job (PUP, BLU, COR) you're unable to start Shattering Stars, nor trade testimonies to BCNMs to fight Maat on any other jobs. 

Shattering Stars checks if your current cap is 70 for you to be able to accept to challenge him the first time (and starting this quest is a pre-requisite for being able to fight him).  
`    elseif (shatteringStars == QUEST_AVAILABLE and LvL >= 66 and mJob <= 15 and player:levelCap() == 70 and MAX_LEVEL >= 75) then
        player:startEvent(92,player:getMainJob()); -- Start Quest "Shattering Stars"`

Pretty sure the intended behavior is you should be able to just talk to Maat > challenge him at a BCNM like you would any subsequent Maat fights after your first.

**Comment by deepbreathingeden** [comment]
![bbc for juul](https://user-images.githubusercontent.com/53072734/109506010-9ce7b700-7ab6-11eb-893e-1847adee73de.jpg)

**Comment by statuseffect** [comment]
This is still occurring, My alts first limit break was COR, and is trying to challenge maat as a 66BLM. No dialogue from maat, nor can I trade testimonies to the BCNM.

**Comment by falzum** [comment]
Ofc it's still occurring. That's why the ticket is still open. If you call a gm ingame then can help get you sorted
