### ISSUE TITLE
Scream Fungus

### ISSUE THREAD

**Issue by Raulfin** [EdenServer/community#3344]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver is 30181205_0

Received a Scream Fungus from Boyahda Tree Coffer. Was the 4th or 5th coffer we popped and only one that wasn't gil. Per the items page it is only available from chocobo digging, harvesting, and gardening. per the coffers page the item should not be in the loot table.

https://classicffxi.fandom.com/wiki/Scream_Fungus
https://classicffxi.fandom.com/wiki/Boyahda_Coffer_Key

Imgur link to log.
https://imgur.com/nchxodX

Reproduction;
Farm a Boyahda Tree Coffer Key and pop the coffer, due to rng may take several attempts.

**Comment by KnowOne134** [comment]
Corrected 11/2
