### ISSUE TITLE
Dynamis - Statues vs Stun/Stun Effects

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3345]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently on Eden statues in Dynamis are immune to stun/stun effects. Statues should be able to be stunned as well as the NM versions at the end of cities. Also believe this would include eyes as well in Dynamis - Beaucedine/Xarcabard.

![image](https://user-images.githubusercontent.com/46270382/96056753-67b73100-0e55-11eb-8e61-4876ca4cc498.png)
https://youtu.be/Hl9-URveXV0?t=470

![image](https://user-images.githubusercontent.com/46270382/96056944-d8f6e400-0e55-11eb-8431-a84650d07968.png)
https://youtu.be/jCAgJgmyyEs?t=295

![image](https://user-images.githubusercontent.com/46270382/96057196-62a6b180-0e56-11eb-9883-68fd39eaefdd.png)
![image](https://user-images.githubusercontent.com/46270382/96057207-69352900-0e56-11eb-82c6-40e4c759e245.png)
Thanks to rudejerk for providing these screenshots of stuns on other statues.

version 30181205_0

**Comment by falzum** [comment]
Are these screenshots from our era or from current retail? I'd love statues and stuff to be stun-able but afaik SE changed a lot of how dyna works. (I quit retail at 80 cap and never did the new dynamis, it's just what I heard)

**Comment by FariskaEden** [comment]
They mostly changed the zones in that they are no longer instanced/reserved and that mobs respawn after a short while. The enemies however are still the same I'd say.

Also here's a video of this happening from 2006:
![image](https://user-images.githubusercontent.com/46270382/96192926-0c4c7800-0f15-11eb-8037-e9a4f450878d.png)
https://youtu.be/zbL8eZub_Fc?t=255

**Comment by Raphtalia1** [comment]
The enemies are very different, many are weaker, statues are stunable and you can avoid detection with sneak/invisible. Prior to the dynamis update statues were immune to stun, which is the version we are emulating

**Comment by Slamm21** [comment]
you could definitely stun statues in era

**Comment by falzum** [comment]
To add to this, this wiki page in the mob description section says they're debuffable by nins Ni spells https://ffxiclopedia.fandom.com/wiki/Category:Simulacra?oldid=957936

"Ninja Ni de-buffs also land with fair frequency so wisely used by Ninja kiters to inhibit abilities of statues from reaching full strength."

So perhaps they shouldn't be immune to anything except grav/bind?

**Comment by deepbreathingeden** [comment]
![1614121272006](https://user-images.githubusercontent.com/53072734/109506018-9f4a1100-7ab6-11eb-9931-eada4bdb0439.jpg)

**Comment by deepbreathingeden** [comment]
![1614234208431](https://user-images.githubusercontent.com/53072734/109506092-b38e0e00-7ab6-11eb-93a2-2b0950fd07d4.gif)

**Comment by 59blargedy** [comment]
resolved with the April 5, 2021 update
