### ISSUE TITLE
Cannot buy magic from Port Sandy Magic shop.

### ISSUE THREAD

**Issue by FriskArt** [EdenServer/community#3346]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
30181205_0
### Details

The Magic scroll NPC does now allow you to buy or sell after you choose which magic you'd like to purchase. The Buy/Sell menu never comes up after selecting White or Black Magic.

https://www.youtube.com/watch?v=sbsKdkU2huo&feature=youtu.be

**Comment by bliven-was-taken** [comment]
Same as issue 3328

**Comment by Spiffly** [comment]
Fixed with update 10/18/20. Needs closing.
