### ISSUE TITLE
Sozu Rogberry Doesn't drop Dried Mugwort

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3347]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
According to 2007 wiki, Dried Mugwort should drop from a bunch of tonberry nms. 

https://ffxiclopedia.fandom.com/wiki/Dried_Mugwort?oldid=292628

Either the drop rate is mega low, I'm super unlucky in 50+ kills with no drop, or it's not in the loot table.

ver: 30181205_0

**Comment by 59blargedy** [comment]
resolved in January 4, 2021 patch
