### ISSUE TITLE
Apollyon NE Floor 3 missing recovery chest

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3348]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/NE_Apollyon

The recovery chest on floor 3, with the dolls and pots, was absent during our run today. 

We entered with 6 people. All in one party.

/ver is the standard eden version, I'm on mobile and don't remember the number.

**Comment by deepbreathingeden** [comment]
![1612766336404](https://user-images.githubusercontent.com/53072734/109506026-a1ac6b00-7ab6-11eb-8742-4783a5d17bdb.jpg)

**Comment by 59blargedy** [comment]
i do not believe this is an issue at this time, but can comment if it should be re-opened
