### ISSUE TITLE
Guild Points NPCs requesting HQ Items?

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#335]
I never really did any crafting on retail so I'm pretty much entirely a crafting scrub, but I don't think that GP NPCs are supposed to request HQ items. My understanding was that they would only request NQ items, but reward additional GP for turning in HQ items instead.

The last several days of my cooking GP items have been HQs that I'm either t1 or t0 on, and the NPC won't accept NQ versions. Apparently this was (possibly still is) an issue an Nasomi as well?
https://na.nasomi.com/forum/viewtopic.php?t=5879

**Comment by icariumkupo** [comment]
IDK about cooking but when leather crafting guild asks for HQ, they will still accept NQ

**Comment by Aneyus** [comment]
It seems like they sometimes accept NQ items and sometimes they don't. I just tried trading a Mutton Tortilla when the requested item was a Mutton Enchilada and it worked fine. But the other day the requested item was Bass Meuniere +1 and the NQ was not accepted.

**Comment by godmode** [comment]
The one reported as well as several others should have been fixed in January or February. Let me know if this isn't the case.
