### ISSUE TITLE
Blood Pact: Tier 2 Spell damage too low

### ISSUE THREAD

**Issue by Dorinorin** [EdenServer/community#3350]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

The Ice Elemental was T to level 46 Summoner. Skill is capped. Damage was 39. Even if resisted, it shouldn’t have been that low. Tried a 2nd time and did 49 damage. 
![0A5195B4-9646-45AF-8EAD-5BB34A3AD3FE](https://user-images.githubusercontent.com/66181140/96359338-ba0b8280-10df-11eb-8fcf-10f44ab40096.jpeg)
![46357C76-E0EC-476E-B2B4-A16D0A3624B0](https://user-images.githubusercontent.com/66181140/96359339-bb3caf80-10df-11eb-9d10-f091a1b0360f.jpeg)

**Comment by 59blargedy** [comment]
believe this was resolved with smn updates, but please comment if not.
