### ISSUE TITLE
Valkurm emperor not spawning

### ISSUE THREAD

**Issue by thundercleese000** [EdenServer/community#3352]
Only 3 dams show on WS and been here for 7hrs. Bugged or someone is holding the PH.
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by Mozzy4Ever** [comment]
Mob was bugged, GM fixed it.
