### ISSUE TITLE
Limbus: restore chests restore hp/mp to dead characters and 'raise' them

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#3353]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

if a character is dead when a restore chest is popped in Limbus, it grants them hp/mp and if they crash and come back their character is alive again without weakness.  I believe it causes them to 'lock' and cannot be raised normally, but haven't confirmed.

**Comment by KnowOne134** [comment]
To tag on to this report. They should also restore hp/mp to pets
