### ISSUE TITLE
Signet duration longer after patch

### ISSUE THREAD

**Issue by Pyroblade99** [EdenServer/community#3354]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

After patch on Sunday 10/18/20, I noticed my Signet lasts 7 hrs instead of 5hrs on my main Character [Phyrah - 8mnk - Rank2 - Bastok (3rd place)].

I let Signet wear a few times and each time the Conquest Overseer (Crying Wind, I.M.  - Bastok Mines) casts signet on me it puts me at 7hrs. I used the same Conquest Overseer every time, haven't tried another Conquest Overseers.

My alt toon [Fyrah - 3 Whm - Rank 1 - Sandy (1st place)] is not showing a timer. I used Conquest Overseer Arpevion, T.K. in S. Sandy by East Ronfaure entrance.

**Comment by Slamm21** [comment]
your alt just doesn't have timers turned on in config. Signet.
Your nation just went from 1st to 3rd place in conquest which is why signet duration is longer.

**Comment by VirtuosusFFXI** [comment]
Not related to what this player said, but Signet duration is currently out of era and has an extra 3 hours across the board that it shouldn't have.

San d'Oria is currently in 1st place. Signet Duration for a Rank 10 San d'Orian should be as follows:

10 hours (Rank 10) + 1 hour (1st place) = 11 hours

Instead, it is currently as follows:

3 hours base + 10 hours + 1 hour = 14 hours
