### ISSUE TITLE
SE Apollyon Floor 2 Crabs and Boss take 0 melee damage

### ISSUE THREAD

**Issue by aragan12** [EdenServer/community#3355]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

The Adamantshells on floor 2 of SE Apollyon are only supposed to be immune to slashing damage, but are immune to all damage types. We tried all 3 weapon types (kc for blunt, axe for slashing, dagger for piercing) and they take 0 damage from everything. The only way to defeat them is by nuking or using rolling thunder currently. The sea monk boss is only supposed to be immune to slashing as well and is immune to all weapon damage types just like the crabs.

**Comment by Garphilius** [comment]
I was unable to replicate this on test right now. If this is a problem, might just be on live. @devs

**Comment by ffxi-waxer** [comment]
Hi! Waxer here!

My friends and I did SE Apollyon tonight and confirmed all of floor two is immune to all weapon types. The only way we were able to progress was thankfully by having a summoner in our group as well and using Rolling Thunder. 

Confirming:

Adamantshell and Tieholtsodi on 2nd floor of SE Apollyon are currently bugged and take zero damage from physical melee attacks of any kind.

**Comment by DeuceFFXI** [comment]
My group attempted SE apollyon last night as well.  Can also confirm that this bug does indeed exist.

**Comment by Mozzy4Ever** [comment]
Cause is known and should be fixed on Sunday

**Comment by 59blargedy** [comment]
resolved on server xfer. can comment if still an issue, but should be fine.
