### ISSUE TITLE
Killed during cutscene for Bat Hunt in Ranperre's Tomb

### ISSUE THREAD

**Issue by erenik** [EdenServer/community#3356]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Expected behaviour: I shouldn't die while in mission cut-scenes.
Actual: While in cutscene at the Tombstone at I-10 in King Ranperre's Tomb, my character was killed (no attacks appeared in log, no monsters nearby after cutscene finished).

Version: 30181205_0

**Comment by erenik** [comment]
![bild](https://user-images.githubusercontent.com/6832027/96583697-6b2b3c00-12dd-11eb-9e05-0d18eedf78f1.png)

**Comment by KnowOne134** [comment]
do you have documentation showing you wont get agro while in the CS can you post it. if so i can re open ticket as im unable to to duplicate issue except dying while in cs from undead
