### ISSUE TITLE
Club bug : Huge dmg (10K+ ) faster than K.Club

### ISSUE THREAD

**Issue by Nimsrod** [EdenServer/community#3358]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

Version : 30181205 0

Hello, 

Sorry if i made a mistake posting here , it's my 1st github post and bug report .

But , this could be abused , i think so , here's my report 👍 

So , i was rying to get a garlaige coffer key , trying to drop it on Vauld and Over weapon with my thf 69 and WHM 56...

My Arcana club is faster than a K. club ( 4 attack per second ) and doig 11K + dmg

![Nimsrod_2020 10 21_150540](https://user-images.githubusercontent.com/73235097/96723742-3f788680-13af-11eb-80c3-365be6062c53.png)

Thanks for the hard work.

Best regards

**Comment by deepbreathingeden** [comment]
![Uploading dfgsdfg.png…]()

**Comment by deepbreathingeden** [comment]
![dfgsdfg](https://user-images.githubusercontent.com/53072734/109505767-627e1a00-7ab6-11eb-8401-545e74216152.png)

**Comment by 59blargedy** [comment]
this has not happened in some time, closing as resolved in a previous patch
