### ISSUE TITLE
Pet AOE not claiming / getting hate on all monsters

### ISSUE THREAD

**Issue by Fng098** [EdenServer/community#3359]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
Using Tiger pet in Carpenters Landing, Tiger pet used Roar, Roar hit and paralyzed a nearby beetle.   Beetle did not attack / Agro the tiger

**Comment by Shoruto** [comment]
Not attacking/Agro similiar to #1596

**Comment by deepbreathingeden** [comment]
![this works](https://user-images.githubusercontent.com/53072734/109505779-6447dd80-7ab6-11eb-83b5-1ed3eb62c350.png)

**Comment by 59blargedy** [comment]
resolved with the April 5, 2021 update
