### ISSUE TITLE
HP percentage boosts

### ISSUE THREAD

**Issue by beauxq** [EdenServer/community#336]
HP percentage boosts should be calculated after flat HP boosts.
Right now they are calculated before.

I used this blog post from 2006 for reference and testing:
https://genomeffxi.livejournal.com/5025.html
On my DSP server, I made a character with the same race/job/level/merits/gear/stats/etc. as those in the blog post, and the max HP was off by about 200.

With this fix, the HP was off by 2. (I suspect this is because of some rounding somewhere - not really worth worrying about.)

I'm assuming MP should be the same way.

Here is the fix:
https://github.com/bdhs/darkstar/commit/bc322a964bddb572004a5b294e277891501aa4a4

**Comment by jmcmorris** [comment]
Can you share your testing setup for this? I will try the blog post character as well.

**Comment by beauxq** [comment]
The character in the blog post is a Hume MNK75/WAR37 with 4 HP merits and 4 MP merits (some MP needed for Intruder Earring).

He doesn't mention it in the blog, but his food is Carbonara. You can tell by the bonus STR, VIT, and INT that matches what's visible with all the below items. And it was a popular HP food of the day.

Items:
Kirin's Pole
Fenrir's Stone  (daytime)
Melee Crown
Bloodbead Amulet
Ethereal Earring
Intruder Earring  (signet, not controlled area, and have enough MP)
Melee Cyclas
Seiryu's Kote
Bloodbead Ring
Bomb Queen Ring
Empowering Mantle
Silver Moogle Belt
Melee Cyclas
Melee Gaiters
