### ISSUE TITLE
Promyvion - Vahzl map quest ???s do not appear to be in their proper location.

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#3360]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Checked all four possible spawn locations for Promyvion - Vahzl map quest ???s and they did not appear to be in any of the four locations.  This was all done within the same game day and there was no one but myself in the zone at the time.  I'm not sure if they're in an incorrect location or just not spawning properly as it'd be too difficult to search the entire zone for them by myself.

**Comment by 59blargedy** [comment]
resolved 11/2 update
