### ISSUE TITLE
Event Storage NPC won't store pumpkin/horror heads 

### ISSUE THREAD

**Issue by CdoubleOkay** [EdenServer/community#3361]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver: 30181205_0

The Event Storage NPC Gallagher will not accept either pumpkin nor horror heads to store.

https://gyazo.com/5c19ba0ecc3af3e988366684300ca72a

**Comment by KnowOne134** [comment]
Was the other npcs checked or just this one?

**Comment by KnowOne134** [comment]
found no issue, I'm a betting mad and i bet that you have the items already stored from last year and cant store 2 sets.
![image](https://user-images.githubusercontent.com/35616771/97238717-0ded2a00-17b8-11eb-9147-b7214b109bdf.png)
