### ISSUE TITLE
Apollyon NW Last Floor Chest Not Opening (Possible in other Limbus zones)

### ISSUE THREAD

**Issue by Garphilius** [EdenServer/community#3362]
### Checklist

- [ Yes] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [Yes ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [Yes ] I have provided my client version in the details. (type /ver into your game window)

### Details

So we had a bug tonight on last floor of Apollyon NW. I died (leader of PT and person who entered the Apollyon NW zone first) and I accidently Home Pointed when someone threw me a raise. My PT killed the KB (boss) and chest popped. However, they were unable to open the chest. I tried running back to Apollyon waiting area and they still could not open it. I tried leaving the PT, they still could not open it. I tried logging off, they still could not open it. 

Steps to possibly reproduce this bug:

1) PT leader enters a Limbus zone first (in our case Apollyon NW).

2) Clear all the way to the top (as we did but could possibly even happen in any floor to be honest).

3) PT leader gets killed (PT leader got killed on last floor due to Meteor but again, this could possibly be on any floor).

4) PT leader gets raised but somehow ignores the raise and Homepoints (possibly do not need the raise portion of this step just saying how it happened, play by play).

5) PT continues like normal and kills the boss (in our case last floor, last boss Kaiser Behemoth but again, this could theoretically be any floor boss that pops item chest) and items chest pops.

6) PT members try opening chest but are unable to.

Client Version:

30181205_0

**Comment by Oyaziiiiiii** [comment]
My group had chests not open in NE Apollyon today too. We opened the first chest(it was a time chest) and weren't able to open any other chests after that on any other floor.

**Comment by perkuprightmeow** [comment]
Just to add to this there seems to be two kinds of chests issues: 

1. Your group can't open ANY chests -- this is related to some kind of entry issue. You're instanced and can fight monsters, climb floors, etc. but chests are unresponsive. When this happened to us it's because one member couldn't enter despite meeting all the requirements. 

2. When someone warps out, leaves the zone, etc. you can no longer open any chests. This just happened to me in NE. The leader wasn't the one who warped out

**Comment by DeuceFFXI** [comment]
> 1. Your group can't open ANY chests -- this is related to some kind of entry issue. You're instanced and can fight monsters, climb floors, etc. but chests are unresponsive. When this happened to us it's because one member couldn't enter despite meeting all the requirements.

Our group accidentally locked someone out last Tuesday in Apollyon SE, but we were still able to open chests; although, due to the damage type immunity bug we weren't able to see if chests on other floors had issues beyond floor two.

**Comment by InoUno** [comment]
Resolved in Nov. 2nd update.
