### ISSUE TITLE
Counters not subject to hit rate checks

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3364]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Not sure if this is all counters or just Seigan+Third Eye counter, but I observed counters going through a Vanguard Pillager's Perfect Dodge in Dynamis San d'Oria as SAM. Didn't pay attention to its HP to see if it actually dealt damage. 

"It is possible to miss a counter attack. In the case of a missed normal counter, there will be no special animation or message; you will simply take a hit." 

"Counterattacks are subject to a Hit Rate check to see if they land. Missed counters are treated as if they never happened.
If an incoming Counter is parried (or counteredVerification Needed), that Counter is also treated as if it had missed.
If the enemy evades the counter attack, the attack on the player goes through normally."

https://ffxiclopedia.fandom.com/wiki/Counter

https://www.bg-wiki.com/bg/Counter

**Comment by VirtuosusFFXI** [comment]
More issues with counter. Monsters that counter player attacks bypass Third Eye.

**Comment by rude-jerk** [comment]
Resolved in November 16, 2020 patch.
