### ISSUE TITLE
Strange reproducible Seagull Grounded bug with workaround

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3365]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I've done 40+ successful escort runs for Seagull Grounded and there is a strange reproducible bug near the start with a very clear workaround. Once you start the NPC up, if the rest of the party stays back and only the escorter walks behind the NPC (in range as normal), the NPC will flee at that first doorway it comes across every time, from what I've seen. I've tried different distances, avoiding pillars and everything navmesh related, but the only thing that seems to work (some credit to Garphilius here) is to have 1 character stand ahead of the NPC just beyond the doorway so that it triggers the "garlic" message and stops the NPC here. If you don't stop the NPC by having someone running by or running ahead with this method, he flees here for some reason.

I also want to note that after the NPC flees at this checkpoint the first time, if you are able to stop him before the exit he will NOT flee here a second time, which is a big red flag that something strange is up.

Note: I decided to split this off as its own bug report since it is a localized issue.

version: 30181205_0

**Comment by Shoruto** [comment]
Related to #2822

**Comment by deepbreathingeden** [comment]
![warzone ping](https://user-images.githubusercontent.com/53072734/109505788-6611a100-7ab6-11eb-931d-947d32ff13b5.PNG)

**Comment by Slamm21** [comment]
LoS changes seem to have fixed this, happy days
