### ISSUE TITLE
Anrin Obi issue

### ISSUE THREAD

**Issue by SonicUK** [EdenServer/community#3366]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I have been testing the Anrin Obi and found that it does not increase drain/aspir in dark weather or day nor does it decrease them in light weather or day, so that could mean that non of the others work either ?

30181205_0

**Comment by Slamm21** [comment]
It works, remember this can also proc without an obi, an obi just makes it 100%.

**Comment by jamiecol25** [comment]
Sorry,

What procs without an obi ? I thought they are supposed to increase damage corresponding to the element ?

**Comment by Slamm21** [comment]
Gain full benefit of Darksday/dark weather bonuses
10% for magic of the day
10% for magic matching single weather
20% for magic matching single weather and day
25% for magic matching double weather
35% for magic matching double weather and day
Will also gain negative bonuses during Lightsday/light weather

the above can happen without an obi, it just **always** happens with the correct obi

**Comment by VirtuosusFFXI** [comment]
> Will also gain negative bonuses during Lightsday/light weather
> 
> the above can happen without an obi, it just **always** happens with the correct obi

Everything stated is true except this part. Dark Obi does not force negative bonuses from Light. Still based on chance.

**Comment by VirtuosusFFXI** [comment]
Sorry, I should go into more detail. Just to be clear, the wiki is wrong when it mentions that line. That is true only of the Hachirin-no-Obi, which is the all-in-one obi SE added later on. The reason for this is because it forces all 8 bonuses, both positive and negative. People just copy/pasted that to all the obi pages without thinking.
