### ISSUE TITLE
Titanic Sawfish/Maliyakaleya Reef Route

### ISSUE THREAD

**Issue by Hydroponic808** [EdenServer/community#3367]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
On the Mana Clipper to the Reef trying to catch Titanic Sawfish, im pulling Gugrusaurus on the reef instead of Titanic Sawfish. I Shouldnt be able to fish up Gugrusaurus on this route. Ive went on multiple runs to the reef with no success on Titanic Sawfish and only pulling Gugrusaurus up when I get to the reef.
version 30181205_0

**Comment by mlandrum22** [comment]
I noticed this today too when looking for Titanic Sawfish.

This must be a recent change because a few months ago this route was working completely fine.

**Comment by deepbreathingeden** [comment]
![bbc for juul](https://user-images.githubusercontent.com/53072734/109505813-6ca01880-7ab6-11eb-8e05-61d9c6788b2d.jpg)

**Comment by failffxi** [comment]
Can confirm this bug still happening as of March 2022.

These fish are needed for "The Big One" Furnishings which are essential for late game fishers, so hoping it can fixed soon.

**Comment by 59blargedy** [comment]
Duplicate ticket/Resolved in June 13, 2022 update
