### ISSUE TITLE
Dynamis Beaucedine Quadav & Yagudo NMs

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3368]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently NMs for these mob families in Dynamis Beaucedine don't seem to use their NM only TP moves (Wrath of Gu'Dha for quadav, Doom for yagudo). They should be able to use them just like how orcs use Fanatic Dance and how goblins use Goblin Dice.

version 30181205_0

**Comment by rude-jerk** [comment]
Resolved in November 9, 2020 patch.

**Comment by rude-jerk** [comment]
Wrong issue!

**Comment by 59blargedy** [comment]
resolved 11/16
