### ISSUE TITLE
A Reputation in Ruins Pso'Xja tower

### ISSUE THREAD

**Issue by Zoltz** [EdenServer/community#3369]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Turning in the quest A Reputation in Ruins stops the Blue (and presumably the Green) Bracelet from allowing me through the blue archway. I still have the key items, they just no longer function.

version 30181205_0

![Zoltz_2020 10 23_212319](https://user-images.githubusercontent.com/73376070/97067844-cdeb3480-1576-11eb-80d4-8e80414ece06.png)

**Comment by Zoltz** [comment]
... Walking away from the door and walking back up to it made it work. I'm no longer certain why it didn't work in the first place.

**Comment by deepbreathingeden** [comment]
![1612766398802](https://user-images.githubusercontent.com/53072734/109505848-745fbd00-7ab6-11eb-93a6-5cc54920b393.jpg)

**Comment by 59blargedy** [comment]
the door requires you to be a certain distance away/close so that's probably what you encountered. kind of like the doors to unlock in phomiuna aqueducts and certain mission doors. im sure it can be done better but yeah, they're functional, just have to scootch.
