### ISSUE TITLE
Utsusemi Ni does not overwrite itself

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#337]
![image](https://user-images.githubusercontent.com/1774728/48738307-95ba7900-ec1e-11e8-8379-e82e56c0c585.png)

**Comment by MGramolini** [comment]
Added info.  

Previously casted Ni not ichi.
Had 1 shadow left.

**Comment by jmcmorris** [comment]
Is this happening for you every time? I attempted to reproduce this and it was working as expected.

**Comment by MGramolini** [comment]
It’s only happened once... but it’s the first time I have recasted with no shadows still up. So 100% if the time for me.

**Comment by jmcmorris** [comment]
Thanks. I will try that.

**Comment by godmode** [comment]
@jmcmorris I was able to reproduce it doing the same thing. Changing id 66 to `overwrite` 1 in `status_effects` tables did not fix the problem. This is all I tried so far

**Comment by Aenge** [comment]
From src\map\status_effect_container.cpp:

The function SaveStatusEffects mishandles utsusemi, and the wrong values get written into the database. In the lines

if (PStatusEffect->GetStatusID() == EFFECT_COPY_IMAGE) {
                PStatusEffect->SetPower(m_POwner->getMod(Mod::UTSUSEMI));
            }
SetPower should be SetSubPower. Copy Image uses the power field to define the level of utsusemi that was used (1=ichi, 2=ni). The SubPower field holds the number of shadows remaining. So, when you zoned out, the number of shadows was being saved as the power level. If you had more than 2 shadows up when zoning, you could gain a tier of copy image higher than ni provides, meaning you couldn't overwrite it with another ni cast.

Also, in LoadStatusEffects, the same thing occurs in these lines:

if (PStatusEffect->GetStatusID() == EFFECT_COPY_IMAGE) {
                m_POwner->setModifier(Mod::UTSUSEMI, PStatusEffect->GetPower());
            }

GetPower() should be GetSubPower().

**Comment by Aenge** [comment]
From src\map\status_effect_container.cpp:

The function SaveStatusEffects mishandles utsusemi, and the wrong values get written into the database. In the lines

if (PStatusEffect->GetStatusID() == EFFECT_COPY_IMAGE) {
PStatusEffect->SetPower(m_POwner->getMod(Mod::UTSUSEMI));
}
SetPower should be SetSubPower. In utsusemi_ichi.lua and utsusemi_ni.lua, copy image uses the power field to define the level of utsusemi that was used (1=ichi, 2=ni). The SubPower field holds the number of shadows remaining. So, when you zoned out, the number of shadows was being saved as the power level. If you had more than 2 shadows up when zoning, you could gain a tier of copy image higher than ni provides, meaning you couldn't overwrite it with another ni cast.

Also, in LoadStatusEffects, the same thing occurs in these lines:

if (PStatusEffect->GetStatusID() == EFFECT_COPY_IMAGE) {
m_POwner->setModifier(Mod::UTSUSEMI, PStatusEffect->GetPower());
}

GetPower() should be GetSubPower().

**Comment by mlandrum22** [comment]
This bug also happens with Ichi. We were going around in Pso Xja last night, the 40 cap one near OP with all the colored "doors", and it happened quite often due to zoning so many times.

**Comment by MGramolini** [comment]
Yea, it happens when you zone with shadows on, you will always have to cancel them when casting any shadows over them.
