### ISSUE TITLE
Dynamis Mob Summoner Astral Flow

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3370]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently when summoner mobs use Astral Flow it will cause their pet's special Blood Pact to go off instantly. These Blood Pacts should have a readying time and should be interruptible. Also the animation of Astral Flow should look like the effect of most other 2-hours in Dynamis (dust cloud) but uses some other effect currently. Mobs should also not Astral Flow if their avatar is dead but currently will.

https://www.youtube.com/watch?v=S2VCT50jI34 - retail usage 

version 30181205_0

**Comment by 59blargedy** [comment]
resolved 11/16

**Comment by Steam-arch** [comment]
Am I wrong but, on eden, is there a weird amount of avatars running around not using 2hr BP even tho their master has used Astral flow. It seems to be trigged if avatar is awake when the 2hr is used  (?), but feels like avatars arent instantly using Diamond Dust/other if the avatar wakes up AFTER the astral flow? Shouldnt mobs use astral flow right after they wake up?

Im too scared to test this on live incase I wipe my ls 👯

**Comment by falzum** [comment]
I've noticed this too steam but didn't know of my retail memory was just bad. I feel like currently avatars only af if they're awake when the summoner uses af like you said.

They should have it in queue to use as soon as they wake up

**Comment by Steam-arch** [comment]
They still use their AF BP after they wake up but they wait several seconds before using it, I do feel like it should be queued too, but might still need a retail confirmation .

I dont remember retail having those "guess we got lucky lol"- moments when dealing with SMNs in dyna
