### ISSUE TITLE
Koen is not giving the Enfire buff upon activation

### ISSUE THREAD

**Issue by baggedmilk2112** [EdenServer/community#3372]
### Checklist

- [ /] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ /] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Koen?oldid=459009 does not give Enfire. I don't believe the additional effect works either.

30181205_0

**Comment by KnowOne134** [comment]
Corrected 11/2
