### ISSUE TITLE
Jailer of Temperance resistance modes not functioning properly

### ISSUE THREAD

**Issue by maldra** [EdenServer/community#3373]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Jailer of Temperance resistance modes are not functioning properly.  While no rings, it is expected to be weak to blunt damage.  However, when meleeing with H2H weapons it was not causing any damage.  The same thing goes with piercing damage while the jailer should be weak to piercing damage;  daggers caused 0 damage to it.  When it had the rings that are weak to slashing, slashing weapons were damaging it just fine, but so were daggers (piercing). However, the dagger's ws did no damage.

In addition to this, I did blood pacts on the jailer, and they all did damage just fine according to what resistance was up.  For example, with no rings (weak to blunt) Titan's Mountain Buster was doing damage normally, when weak to slashing, Garuda's Predator Claws was doing damage normally, and when weak to piercing, Fenrir's Crescent Fang was doing damage normally.

Based on this, it appears that WS damage/blood pact damage is correct based on the damage resistant type, but melee auto attack damage is not correct according to the damage resistance type.

**Comment by Slamm21** [comment]
same bug as https://github.com/EdenServer/community/issues/3355

**Comment by 59blargedy** [comment]
resolved on server xfer. can comment if still an issue, but should be fine.
