### ISSUE TITLE
Guild Item Restock Low

### ISSUE THREAD

**Issue by mark-johnstone** [EdenServer/community#3374]
### Checklist

- [ ✓] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [✓ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ✓] I have provided my client version in the details. (type /ver into your game window)

### Details

Since the October 25th 2020 patch guild supply NPCs are not restocking the correct amount of items each game day. 
Dehbi Moshal in Al Zahbi should restock 6 elm lumber per game day, however is currently only restocking 1. Similar issue seen at woodworking guild in N Sandy. 
Game version: 30181205_0

To reproduce purchase all elm lumber from NPC Dehbi Moshal in Al Zahbi, wait 1 game day and check stock level of elm lumber (should be 6).

Pic showing restock after two game days:
![Dehbi Moshal](https://user-images.githubusercontent.com/29806202/97171903-1a588f00-1786-11eb-8bf5-83e3651d1a83.png)

**Comment by perkuprightmeow** [comment]
I would guess this is related to #2843 with the recent server instability.

In general though guild stock here has been changed to reflect the server population size.

**Comment by mark-johnstone** [comment]
Updated to correct date issue first seen to be 25th

**Comment by roriffxi** [comment]
Yeah, I noticed this at the CC guild too.  I'm not sure what the "full stock" is, but it went from 5stacks +4 singles down to 1stack and 4 singles once at the lowest price.

**Comment by MysticLogos** [comment]
This is happening with Tarutaru Rice at the cooking guild as well.  Only 1 unit is being restocked per game day, and it should be 6.

**Comment by 59blargedy** [comment]
as an fyi, this will be resolved with monday's patch.

**Comment by 59blargedy** [comment]
resolved 11/2 update
