### ISSUE TITLE
The Garden of Ru'Hmet Teleporter doesn't shed aggro

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3375]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The central elevator on floor 2, where ix'drg spawns, does not shed aggro upon use. Had two ghrah still trying to chase me down after using it to zone down to the first floor level. 

/ver 3018120_0

**Comment by 59blargedy** [comment]
resolved in February 22, 2021 update.
