### ISSUE TITLE
Behemoth family resistances are noth implemented

### ISSUE THREAD

**Issue by danismyhero** [EdenServer/community#3376]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Category:Behemoths

Immune to Aspir.

https://ffxiclopedia.fandom.com/wiki/Behemoth_(MON)

Immune to Stun.

Elemental resists and enfeebling gradual resistance not implemented.

Just a reminder, none of this is implemented, stuff is too easy.

**Comment by Mozzy4Ever** [comment]
Would take the "immune to aspir" with a grain of salt. There's videos of people using Aspir on King Behemoth.

**Comment by danismyhero** [comment]
KB has MP.  He casts Meteor.  NQ does not.  It's a mob by mob situation.

**Comment by ElectronicMan83** [comment]
I agree with the MP or No MP
From BG wiki : "Behemoths are typically Warrior/Thief, with the Elasmoth subspecies as Dark Knight/Thief.Which begs the question, how do they have MP and use Meteor?"
------
I want to add that a Dark Knight shouldnt be able to land bind consistently and so easily on B. 
Also a SMN solo/could hold kite behemoth for 10 minutes easily. Carbuncle took 50 dmg per hit ??? even without gravity with the tree situation . ( smn can pretty much hold everything in the current state)
Behemoth need some tweak to make it a bit more challenging and ERA accurate.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
