### ISSUE TITLE
Cannot Progress in Thief AF 2 Quest As Thick As Thieves 

### ISSUE THREAD

**Issue by benjaminrclayton** [EdenServer/community#3377]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version: 30181205_0

After trading the Grapnel to the ??? and watching the cut-scene to get the first letter signed, Sniggnix will not play 'roll-the-dice.' Instead he just says "hey, we dont trust you people none, but we can always smell a profit". 

I have two key items in my inventory related to the quest: "first signed forged envelope" and "second forged envelope".

**Comment by benjaminrclayton** [comment]
Went back to check the towers in Sauromugue Champaign and when clicking the ??? it says "You no longer have a need to climb the tower".

**Comment by perkuprightmeow** [comment]
For some reason the towers are no longer updating the variable 'thickAsThievesGamblingCS' to 1 whenever you get KI 189 from the tower NM kill.

Have fixed this 5 times for people, but am unsure if it's happening 100% of the time. Maybe only at certain towers? Dunno.

**Comment by 59blargedy** [comment]
resolved 11/2 update
