### ISSUE TITLE
AF+1 upgrade materials should be RA/EX in era

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3378]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

AF+1 upgrade materials from Temenos and Apollyon are ra/ex in era.

![af+1](https://user-images.githubusercontent.com/49970272/97376603-292d6780-1894-11eb-8516-6a026a5f1453.png)

**Comment by Shoruto** [comment]
Earliest update to this item changing to EX was December 11, 2013 (FFXI Wiki, BG Wiki)
Can confirm and located a post by a player to confirm on https://ffxi.allakhazam.com/db/item.html?fitem=8668

Diabolic Yarn
**Sep 22 2006** at 1:33 AM 

Used for upgrading blm AF, pairs with Diabolic Silk. Trading Sagheera the requisite number of ancient beastcoins, the two blm upgrade items, the af piece you wish to upgrade, as well as a third crafted item, will net you the AF+1 result at next conquest tally. (Japanese Monday... 10am eastern standard, 11am eastern daylight time) Trade coins first (number depends on which piece you upgrade), then the AF, all three upgrade items (**two rare/ex**, one crafted).

**Comment by KnowOne134** [comment]
Corrected 11/2
