### ISSUE TITLE
Eo'ghrah's cannot be killed with drain.

### ISSUE THREAD

**Issue by cxm1071** [EdenServer/community#3379]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Eo'ghrah in Grand Palace of Hu'Xzoi can't die from drain.
Tested on all elemental types of ghrahs. Drain will do 0 damage once ghrah has only 1hp left.

Reproducible steps: Lower Eo'ghrahs hp and cast drain.

Version 30181205_0

![Untitled](https://user-images.githubusercontent.com/36733706/97401321-fb154b00-18c6-11eb-8d00-e761f6b9f889.png)

**Comment by VirtuosusFFXI** [comment]
Same issue with some mobs in Dynamis - Xarcabard. I've observed the same issue on certain demons there, Drain will do whatever damage it can until the mob has 1 HP left.

**Comment by Mozzy4Ever** [comment]
Thought there was already a bug report in for this but I guessed wrong... It appears to happen to any mob that has Magic Defense Bonus.

**Comment by rude-jerk** [comment]
Resolved in November 9, 2020 patch.
