### ISSUE TITLE
Quest: Sorcery in the North Drops after you pick it up.

### ISSUE THREAD

**Issue by zernon916** [EdenServer/community#3382]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Finished Tele Holla quest, zoned, picked up Quest: Sorcery of the North,  Checked was in log, went to Feyin, got key, got chest, No Longer in quest log, no key item...

**Comment by KnowOne134** [comment]
no other mentions of this happening and cant reproduce, sounds like a quest setting issue from database
