### ISSUE TITLE
Selene of Windurst is missing

### ISSUE THREAD

**Issue by toronasgard** [EdenServer/community#3383]
[###]Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0
In Windurst at k-10, an NPC named Selele who is supposed to be there for new players to introduce to maps. etc. Is not there, I have logged in and out multiple times and still nothing, I looked for videos if maybe she was somewhere else or was moved but no, she's just not in Eden's version. For reference, she's supposed to be here: Start at 12:12 https://www.youtube.com/watch?v=0CB83urzKGA
https://imgur.com/a/1XJsONU?third_party=1

**Comment by roriffxi** [comment]
https://ffxiclopedia.fandom.com/wiki/Selele?oldid=664632

This npc was added in September of 2008 to help guide new players, but is out of the era for Eden.
