### ISSUE TITLE
Boss keep missing in Apollyon NW

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3385]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

In our run last night in Apollyon "Millenary Mossback" Boss and others seemed to have acc issue. 
The one mentionned been tested out to see if it was just matter of luck but wasnt. Monster seem to be undertunned too but cant say much about it. 

When straight standing in front of the Turtle NM as Black Mage It missed 0/10+.  Other seemed to miss too.

**Comment by 59blargedy** [comment]
resolved in January 4, 2021 patch
