### ISSUE TITLE
Summoner NMs avatar can be slept before despawn

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3386]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

When fighting Crimson-toothed Pawberry (carby mitts NM), I was readying a Sheep Song when the monster used its 2 hour, spawning a Tonberry's Avatar (Leviathan). The Avatar got a Tidal Wave off but was instantly slept after, preventing it from despawning. For the rest of the fight it was hit with other AoE (none of it was damaging AoE, so not sure what happens in that case) and when woke up it just looked at me and followed me around. After the NM died the avatar continued to follow me around. It was never targettable and it never attacked, it just walked next to me. Eventually I logged out which lead to the avatar pacing around the room as if it was unclaimed (still untargettable). 

The NM is not able to be popped while the avatar is still alive.

Eventually a GM had to interact with it, which caused it to 2 hour and then despawn, and then we were able to pop the NM and continue on as normal.

Don't have screenshots of the log due to the logout / more fighting after.

![image](https://user-images.githubusercontent.com/13668758/97634808-bb587b80-1a0c-11eb-9b49-51c2210d70a1.png)

version 30181205_0

**Comment by InoUno** [comment]
Resolved in March 22nd, 2021 update.
