### ISSUE TITLE
MNK Mob Kick Attacks

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3388]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Monk mobs belonging to Aern & Fomor families currently do not perform kick attacks when attacking with hand-to-hand. Monks belonging to these families should be able to perform kick attacks.

https://i.gyazo.com/a9663c6c60c184108b1ce2cdd94c6da4.mp4 - Ix'aern (MNK)
https://i.gyazo.com/01afa294659324b4e6621afe488bdbd4.mp4 - Eo'aern (MNK)
https://i.gyazo.com/5a85f75f8330573a4900270622c925c4.mp4 - Hydra Monk
https://i.gyazo.com/8cba70633675322b7fad8f76b230e3a3.mp4 - Fomor Monk

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
