### ISSUE TITLE
Dynamis - Some Ninja Issues

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3389]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently Mi'Rhe Whisperblade in Dynamis Beaucedine will attack twice per round while using a 2H weapon, he should only attack once per round. Hydra Ninjas in Dynamis Beaucedine currently will attack once per round while dual wielding, they should attack twice per round. Also I think there is no delay on ranged attacks made by most ninja mobs within Dynamis in general, they should have some wind-up time to them.

Eden Mi'Rhe Whisperblade / no ranged attack delay:
![image](https://user-images.githubusercontent.com/46270382/97660245-5b32fb00-1a47-11eb-9170-5bd09f359035.png)

https://i.gyazo.com/f0c239cffc6ee7d24a0ca1741102739d.mp4 - retail hydra ninja attack rate / ranged attack wind-up

version 30181205_0

**Comment by deepbreathingeden** [comment]
![1788268](https://user-images.githubusercontent.com/53072734/109505706-52fed100-7ab6-11eb-8b0b-4f6addbd1f76.jpg)

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
