### ISSUE TITLE
Mobs in Apollyon and Temenos are not walking back to their location

### ISSUE THREAD

**Issue by Eme-FFXI** [EdenServer/community#3391]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)

### Details
Pull mobs in limbus away from their spot, die, wait for them to move away in order to reraise. But they don't (mobs just stay put). In retail they are moving back.

**Comment by 59blargedy** [comment]
resolved in february 1, 2021 update
