### ISSUE TITLE
BST Exp Nerfed Using T Pets and Leave

### ISSUE THREAD

**Issue by rockemsockemman** [EdenServer/community#3392]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details
Client Version: 30181205_0

When charming T+ pets, exp is nerfed even if using Leave before killing the mob. Should be able to use Leave and get full EXP like on retail.

Easy to repeat, just charm a T mob and use Leave and the EXP will be less once mob is killed.

**Comment by KnowOne134** [comment]
not in era, you have killed the mob same as if you had a party member with same level as your pet. highest level attacker is now the level of xp reward

**Comment by rockemsockemman** [comment]
You’re a fucking idiot. Do some research on BST. All BAT used Leave for EXP pre ToAU, Pre CoP.

**Comment by InoUno** [comment]
@rockemsockemman If you want things changed, do the research, and bring proof that things aren't correct as they are. Right now you are just claiming it is wrong.
