### ISSUE TITLE
Tonberry Light of Penance isn't functioning correctly

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#3393]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

TP should not be reduced when the target of Light of Penance successfully turns around to avoid the gaze attack.

https://www.youtube.com/watch?v=hzqY1bG8_fs

**Comment by 59blargedy** [comment]
resolved 11/16
