### ISSUE TITLE
Limbus elementals have insane physical resistance

### ISSUE THREAD

**Issue by rpcon** [EdenServer/community#3395]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Fourth Floor SW Apollyon
https://ffxiclopedia.fandom.com/wiki/SW_Apollyon
They are susceptible to melee damage, **unlike normal elementals**. That being said, they still have a higher resistance than normal non-elemental monsters to melee attacks.

Eden's elementals have at least 75% physical damage reduction. I normally hit mobs for 110 to 140 and was only doing 25-40 per white hit. It caused us to time out with the party comp since we didn't have enough magic damage.

**Comment by Shoruto** [comment]
Related to #3338

**Comment by 59blargedy** [comment]
resolved 11/2 update
