### ISSUE TITLE
Arrow Stats do not show up in /checkparam - Are they working?

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3396]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

/checkparam without arrows equipped. Note ranged accuracy.
/checkparam again after equipping arrows. Note ranged accuracy. 

No change. Tested with Kabura and Demon arrows.

**Comment by falzum** [comment]
Do you need to change a visable armor piece and make your character blink for changes to take effect?

**Comment by rude-jerk** [comment]
Resolved in November 9, 2020 patch. All bow, gun, and x-bow ammunition was audited for correct range accuracy bonus values.
