### ISSUE TITLE
Mob casts healing spells on full hp allies

### ISSUE THREAD

**Issue by Spiffly** [EdenServer/community#3397]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

I have killed Ni'Ghu Nestfender in Palborough mines earlier. Wiki page here: https://classicffxi.fandom.com/wiki/Ni%27Ghu_Nestfender

For the warrior AF feet quest: https://classicffxi.fandom.com/wiki/The_Talekeeper%27s_Truth

I cleared the 2 regular mobs that occupy the room where the ??? is. These mobs respawned mid-fight and Ni'Ghu Nestfender promptly cast Cure IV on one of them, at full HP. As far as i'm aware, no mob(s) should be casting cures on another with full HP.

Ver: 30181205_0

**Comment by E5una** [comment]
Light based Ghrah’s (and probably all mobs that can) do this in sea when they are already at full HP as well (like if you pull with a missed ranged attack, or even if you run by and face aggro them they can do it)

**Comment by Spiffly** [comment]
Changed the title as it seems more of a generic behaviour issue than just that NM.

**Comment by Shoruto** [comment]
Related #449

**Comment by 59blargedy** [comment]
some visual proof of this issue occurring, with the attacked mob at 10%, they cast cure on a nearby allied mob that was not involved in the fighting and had full health.
![image](https://user-images.githubusercontent.com/52636208/123521994-38192380-d688-11eb-8f52-3211be72fa52.png)

**Comment by KnowOne134** [comment]
closing due to duplicate report
https://github.com/EdenServer/community/issues/449
