### ISSUE TITLE
AF upgrade items in Limbus can be lotted even if one is already owned

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3399]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver: 30181205_0

Was just able to lot(and win lot on) Diabolic Yarn in Apollyon. I assumed since I was able to lot I didn't have one in my inventory.

Turns out I had one in storage from a previous run. So the one that I had lotted and won lot on fell to the floor. 

If an af+1 upgrade item is in inventory, you shouldn't be able to lot.

**Comment by Slamm21** [comment]
does anyone know of any other item this happens with other than AF+1 ones? Not sure if there are any

**Comment by falzum** [comment]
If an item is rare, you shouldn't be able to lot another. You'll get a message along the lines of "You can only hold one item of this type.".

**Comment by IzaleaCF** [comment]
I assume the existing yarn was collected before the R/E change in Monday's patch?  I suspect there's a mismatch going on with "old" AF1+1 items, which are still marked as only Ex in my MH.
![image](https://user-images.githubusercontent.com/73662229/98156777-4242a380-1ea6-11eb-9e91-c1ed746f7a1a.png)

**Comment by Slamm21** [comment]
interesting, so it might be that once we all use up our supply of old items, this issue no longer happens.

**Comment by rude-jerk** [comment]
They're not separate items, just flags on those items to have them set to rare have been added. 
It's more likely that the client handles the can lot check, so it would require a dat modification.

**Comment by KnowOne134** [comment]
should be corrected now with edited dats found here:
https://github.com/EdenServer/Eden-Client_DATs
