### ISSUE TITLE
Knight's Minne might need to cap lower in era

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3400]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My current Minne IV (with some average +sing/+string gear on, not BiS) is providing 80ish defense +/- based on merits, gear, etc.

Era wiki's suggest there is a much lower cap, but I am having a hard time finding the exact info and numbers in dates that exactly match our server, or anything other than basic wiki pages:

August 2007 ffxiclopedia:
https://ffxiclopedia.fandom.com/wiki/Knight%27s_Minne_IV?oldid=326069

Caps at +49 Defense, below natural skill caps for BRD75. Or if it isn't capped, +35 skill is not enough to get another point of Defense. Harp +1 adds +5 Defense.

March 2012 BGwiki:

https://www.bg-wiki.com/index.php?title=Knight%27s_Minne_IV&oldid=216010

Caps at +48 Defense before gear/merit enhancements

As you can see there are some slight disparities in the wiki pages too.

Note: All tiers of the spell probably need the update.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 patch
