### ISSUE TITLE
Harp +1 (+2 Minne) is providing 6 defense rather than 5

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3401]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The +2 Minne from Harp +1 is providing 6 defense rather than 5. I'm not sure if this is indicative of a larger issue with the way +songs work so reporting it in case it is. 

Here is a chart from 2012 bg wiki that shows how the values should be, but I'm having a hard time finding info in era. OOE modern is 10% defense bonus per +1 for Minne.

https://www.bg-wiki.com/index.php?title=Category:Minne&oldid=216042

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 patch
