### ISSUE TITLE
Minne merits appear to be +1 defense in era, not +2

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3402]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ffxiclopedia says +1 defense per minne song for each merit, but the in game UI says 2. BG-wiki in era shows only a benefit of +1 defense. Currently Eden merits give +2 defense, so this should probably be reduced to 1.

https://www.bg-wiki.com/index.php?title=Knight%27s_Minne_IV&oldid=216010

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in February 8, 2021 update
