### ISSUE TITLE
Zephyr Mantle cast time should be 7 seconds, not 4 seconds.

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3403]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Zephyr_Mantle?oldid=349146

Era and current cast times for Zephyr Mantle are 7 seconds. I'm not sure why it is set to 4 seconds in topaz/eden, but there is no documentation for it ever being 4 seconds.

Note: When this is updated, players will also want a dat mod to fix the cast time so they aren't constantly interrupting their spell by moving after the bar fills.

version 30181205_0

**Comment by KnowOne134** [comment]
Corrected 11/30
