### ISSUE TITLE
Attack Down, Bio, Accuracy Down, Blind, and Flash should affect Ranged Attack/Accuracy

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3404]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Currently, monster TP moves such as Gastric Bomb, Sonic Boom, Demoralizing Roar (Attack Down), Dust Cloud (Blind), Actinic Burst (Flash), etc do not/may not all reduce ranged attack or ranged accuracy. 

All of these effects should lower both player and monster ranged attack and accuracy. Verified on retail.

**Comment by greyenvy** [comment]
Should we also check on paralyze against ranged attacks?  Not sure what retail behavior is on that one.

**Comment by ccl085** [comment]
paralyze do affect ranged attack on retail

**Comment by 59blargedy** [comment]
resolved 11/16, show proof on paralyze and put in a new bug report if so
