### ISSUE TITLE
Neptunal Hands drop rate seems too low from Byakko

### ISSUE THREAD

**Issue by HitGubz** [EdenServer/community#3406]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details
20+ Kills of Byakko with TH4 and 0 Neptunal Hands - the drop seems to be lower than it should be. While ERA wiki doesn't state %'s I've read as many era blogs as I can and found one suggesting 25% ish drop http://ayana.moo.jp/sky/byakko.html . Please could you take a look at the loot pool and see if anything's up with it?

**Comment by 59blargedy** [comment]
drop rate is fine. rng strikes again - all items are set equally from him, with 1 chance being guaranteed and split 25% each way, and another chance at a second drop that's much lower but split equally among the abjurations again. my ls kept getting efeeted. it just seems to go that way. hopefully complaint strats work and you get n hands next drop!
