### ISSUE TITLE
Pso'xja Mimic Issues

### ISSUE THREAD

**Issue by Shoruto** [EdenServer/community#3407]
I have done a full copy/paste of the reported Mimic issues and put them here in one report and will close the rest.  If anyone knows of any other problems with Mimics in Pso'xja please reply to this report.  Thanks.

**List if Issues**

**Author** - ElectronicMan83
**Title** - Mimic in pso'xja #2428

**Details**

Mimic stay up after trading key. When they respawn there is no way to claim them after 16 minutes, someone could abuse with thief tools probably because you can trade key to all of the spawn, cant even claim them too after it been killed once when it respawn waited 1 hours at least.

**Author** - Jimmayus
**Title** - Mimics will turn hostile and aggro when you use aoe near them in Pso'xja #2329

**Details**

version 30181205_0
See title of bug report. The steps to reproduce:

    Bring monster to a known mimic
    use an aoe move on top of it

This should make the mimic hostile.

**Additional Information for the above bug**

Jimmayus commented on Dec 30, 2019

Apparently this is not a guaranteed thing. We tried to reproduce on the same chest and were unsuccessful.

Jimmayus commented on Dec 30, 2019

After my last update we checked all 6 mimic spawns. We were not able to aggro anymore using the above method. On the last mimic we used a pso'xja chest key and it respawned as a mimic.

**Author** - Kusarigama-Eden
**Title** - Pso'Xja Mimic Bug

**Details** 

VER: 30181205_0 ; Only thing I changed recently as well was adding Enternity addon

Details: This seems to only happen AFTER defeating a Mimic in Pso'Xja. I have been locked 3 times this hour alone. All of the sudden I can not /heal which means I can not logout (must force close), I can not see HP bars and etc in the UI bar and I can not cast on myself. Other people in my LS say they had the same experience. The Mimics are also not always Draw In other party members as well.

NOTE: When I zone it fixes itself and it is awfully tedious to constantly force close or run to the nearest zone to reset it.

**Author** - montijin
**Details**

Chip acquisition from mimics is beyond unreasonable in its current state. I spent 4 hours+ with TH4 and didn't get a chip after using 25+ pso'xja keys.

edit: I had better luck the next morning, but still spent about 8 hours total between two sessions to get 6 chips.

**Author** - roriffxi
**Details**

Similar issue, if you /ra a mimic chest it will hit it and cause it to agro

You can actually engage and auto attack them too, seems to happen if you wait the 15-16min respawn time after killing one. And then you can't until they 'respawn'

**Comment by Kurokami5297** [comment]
Test

**Comment by Fng098** [comment]
The issue of them staying up after defeated seems fixed.   9/11/22 killed many in uncapped Psojax.

**Comment by Fng098** [comment]
Traded living key to chest at H-9 (behind green door) and was transported to H-7 uncapped Psojax off of the G-9 entrance

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
