### ISSUE TITLE
Ramuh Shock strike stuns on miss

### ISSUE THREAD

**Issue by jamiecol25** [EdenServer/community#3408]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

So leveling smn and using ramuh, I have noticed that shock strike will stun even when it misses. Not tested other avatar abilities like slow from rock throw will test that later. Prior to smn changes these level one abilities didn't apply the additional effect but since the changes I can see the stun from Ramuh going off so seems to be related to that.

**Comment by 59blargedy** [comment]
resolved 11/16
