### ISSUE TITLE
Paralyze Proc Rate

### ISSUE THREAD

**Issue by Blex64** [EdenServer/community#3409]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Client version 30181205_0

I've noticed the Paralyze proc rate on Eden seems to vary pretty drastically - especially when it comes to HNMs. I don't have hard data, but I've landed Paralyze II on Khimaira probably upwards of a dozen times, and never seen it proc. I've seen it proc on Fafnir maybe only a couple of times period. 

There's pretty extensive Paralyze I testing here: 
https://www.bluegartr.com/threads/83846-Extensive-Paralyze-I-Testing

I wasn't able to quickly find anything as detailed about Paralyze II specifically, but FFXI Wiki lists the proc rate at ~14% with dMND @ -40, and ~34% with dMND @ +40. BG WIki has similar numbers, at 10 + 30% for the same dMND values. I don't know what formula we're using on Eden but it does seem safe to assume it's not being floored at 10-15%, especially on HNMs.

**Comment by Slamm21** [comment]
https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6503005&viewfull=1#post6503005
this is how para 2 works but I asked setzor to check this a long time ago and it matched up

**Comment by Blex64** [comment]
I have a pretty hard time believing we're floored at ~10% at -40.

**Comment by 59blargedy** [comment]
this was actually resolved with mhit changes this year
