### ISSUE TITLE
Damage calculation bug - 1 shotting monsters

### ISSUE THREAD

**Issue by andeluvian** [EdenServer/community#3410]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I was farming Crane Fly and Hill Lizards in sauromugue champaign on my alt.
I noticed that the lizards died super fast, at first I didn't pay any attention until I 1 shot a crane fly, they are EP to me so they shouldn't die that fast.

I looked at the damage logs and I've been doing 40k damage to Hill Lizards and Crane Flies.
I tested on Boggars and Goblins all get 1 shot.

I am a 27 RDM/WAR how I did this was I cast protect , cast enthunder, pull with dia, warrior double strike procs and I do 40k dmg.

I am using a flame sword + enthunder so I don't know if this can be damage calculation error on damage stacking?

Screenshot:
https://i.ibb.co/grZNF4b/dmgbug.png

Client version:
30181205_0

**Comment by mastemium** [comment]
This has happened to me twice. Once in Dynamis Sandoria against a Pillager and once against a Tonberry Stabber in Temple of Uggalepih. I think it has to do with my Bartholomew's Knife. In both cases it happened after trying to steal from the mob and then when I was reposition and I forgot to switch back to regular daggers and I hit it with the Bart Knife it just did 30k+ damage.
![Celestia_2021 01 04_204312](https://user-images.githubusercontent.com/47079690/103800198-78c1a980-5022-11eb-9809-a59165b61b9c.png)

**Comment by Mozzy4Ever** [comment]
This can be closed now. I believe it was fixed with the January 11th, 2021 update.
https://discord.com/channels/482610771126386688/670735434799644690/798209060780245072
![image](https://user-images.githubusercontent.com/11255886/113921259-65ea7c80-97ab-11eb-83cb-45710161f994.png)

**Comment by KnowOne134** [comment]
Butterfingers

**Comment by 59blargedy** [comment]
it's been a while since we've heard of this happening, so closing these reports
