### ISSUE TITLE
Manta ability "Cross attack" woefully weak

### ISSUE THREAD

**Issue by Goto28** [EdenServer/community#3411]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

A Manta's most powerful physical attack, this should deal upwards of 600 damage to an unbuffed 75 character even from a DC Manta -- currently it does less than Tentacle, a much weaker Manta attack.

**Comment by 59blargedy** [comment]
it would be helpful to provide proof - i.e. video, screenshots etc. of the claim so that it is easier to implement requested changes.

**Comment by Goto28** [comment]
Hey there Blargedy, I'll try my best to look around but that'll probably be difficult, what's even more lame is even a retail capture of today wouldn't even be accurate due to the defence overhauls it underwent over the years

**Comment by Goto28** [comment]
https://www.youtube.com/watch?v=UEoW5TalT5U&ab_channel=TatianaFFXI

This is the best I could find, ignore the date of the video, it's a re-upload of a very old video in HD.

Skip to 12;50, player is hit with a waterga III then hit with cross attack shortly after for 394 damage.

Things to note is;

Player has Protect IV and Shell IV on.
Player has Phalanx on.
Player was hit with Cross Attack in an MDT-% set, which likely has little to none of any -% Physical Reduction gear.
Player had a Stoneskin effect on prior to being hit with Waterga III, the Stoneskin strength almost certainly being max strength (350~HP worth), the Waterga III didn't break Stoneskin, but player had an -%magic damage taken set, plus Shell IV and Phalanx prior to being hit with Waterga III, under those circumstances Waterga III would actually deal pretty small amount of damage to them---meaning the Cross Attack that broke his stoneskin that was a little weakened by the Waterga III in addition to dealing 394 damage means it was a fairly hefty one, especially considering player had Protect IV and Phalanx up.

**Comment by 59blargedy** [comment]
I appreciate the effort, this is at least something to go on.

**Comment by 59blargedy** [comment]
resolved in December 21, 2020 patch
