### ISSUE TITLE
Enveloped in Darkness conflicts with Undying Flames

### ISSUE THREAD

**Issue by Viscus** [EdenServer/community#3412]
The quest Undying Flames started by the NPC Pagisalis can block progress in the quest Enveloped in Darkness if not completed first. Pagisalis will not accept the velvet cloth that needs to be traded to him in the quest Enveloped in Darkness. 
Ver. 30181205_0
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

**Comment by KnowOne134** [comment]
Corrected in 11/19/2023 update
