### ISSUE TITLE
Shakhrami Chest Key doesn't drop

### ISSUE THREAD

**Issue by Godfather0711** [EdenServer/community#3413]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The Shakhrami chest key doesn't drop. Despite farming with 4 people (2 THFs) for 1 hour 1/2, we didn't get any.

**Comment by galenor** [comment]
I am experiecing the same issue. killed well over 30 mobs in shakrami. not only did the chest key not drop, no single item dropped. goblins did give gil upon death.

**Comment by Godfather0711** [comment]
Well as for us, we did have common items drop from mobs. We even got a "Rusty key" used in windy quest and few others rar/ex items, but no Shakrami chest key :'(

**Comment by E5una** [comment]
I’ve farmed this one several times and typically I pull the entire zone on that side of the map and clear with TH2 3-4 times before I get it. It’s a pain in the butt but should be there unless something changed.
