### ISSUE TITLE
Quest & mission variables not updating while in combat

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#3414]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Ever since the update involving cutscenes, been seeing a huge uptick of people reporting getting cutscenes, but variables not updating (not able to move on in missions) because people in their party were in combat. They receive the cutscene as normal, but their variable doesn't tick over. 

This has obviously always been a minor issue, but seeing it a lot more lately since the update-- a few trouble spots include the wooden gate at the end of Sacrarium, and Promy-Vahzl memory fluxes off the top of my head. 

I'm not 100% sure that it has to do with party members being in combat, but it's a common thread amongst all the tickets I've handled.

**Comment by InoUno** [comment]
Resolved in November 23, 2020 patch.
