### ISSUE TITLE
 Seagull Grounded - npc "now's my chance" 

### ISSUE THREAD

**Issue by TheChefm** [EdenServer/community#3416]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

While standing 2.5-4 yalm away if you get to a Door way or the "left or right" spots at H-7/H-8 no matter what 90% of the time will run away "Now's my chance".  So we even tried having people stand at the door to lock him up with the garlic saying, nope.  Its like it comes to these door ways / "left or right" does a double double check on yalm, ends up doubling it and running away.  We have lost 4 tags now in all the same places.  Since the navmash isn't great in there, maybe being less strict with the yalms checks.

**Comment by ThrisStraizo** [comment]
Can confirm, this assault need some serious attention.  It's worked just find in the past but now it's pretty much completely unclearable and the NPC seems to not care if you're standing right next to him, he will try and make a break for it anyways.

**Comment by SyHub** [comment]
Another confirmation, burned a few tags and did some extensive testing. Leaving characters in the end hallway did not stop the NPC and keeping players between 5-30 yalms ahead did not stop him.

**Comment by Balrahn** [comment]
Thought this was known, but can confirm that leaving a character in the hallway definitely does not stop him. Would leave my alt in the hallway to stop him if he ran when doing this, and did not help at all. Also sometimes when he runs away he'll run through the walls making it impossible to reach him.

**Comment by ccl085** [comment]
The NPC will run away if it see mob even if you're close to it, distance doesn't matter on run away if there are mob on the way, you're supposed to stop the npc before it can see mob, standing  close to the npc for a few second will stop it. It will also try to run away if you stand too far from it even if there are no mob

The npc is not supposed stop while running away if you have a character in the hallway, it's stop when it's tired from running away and say "<Pant>... <Wheeze>" or w/e message. If you have a character nearby(<3 for me) when it does that it will say "Damn" then you can move back and it will start walking like normal.

**Comment by Slamm21** [comment]
After doing this multiple times now, the only major issue I have found is on the first doorway, he will often run for no reason even if you are a yalm away.

**Comment by ThrisStraizo** [comment]
If only it behaved like that, rather than running away for literally no reason while you're inside of his ass.

**Comment by Slamm21** [comment]
![image](https://user-images.githubusercontent.com/5552081/103159917-09002300-47c7-11eb-85fe-5992f2222993.png)
had it again today, I think I worked it out.

I think when you enter it chooses someone at random, and if that person does not stay close by the first door it bugs out.
I've tried having myself be the one to run to him first but that doesn't stop it, however, if you have everyone stay in the first room except you until you get past the door, that seems to avoid this bug.

We also had him do the run away through walls today, first time for me so we lost 2 in a row from bugs lol. I've done lots of runs though so either I'm lucky or that bug seems to be a rare one.

Until fixed, I suggest trying the above about the first door and see if that helps.

**Comment by E5una** [comment]
See https://github.com/EdenServer/community/issues/3365 and my “guide” listed in https://github.com/EdenServer/community/issues/2822 for additional details on this first door and general advice, unless things have changed, unclear from the comments but someone said something may have changed.

**Comment by Slamm21** [comment]
LoS changes seem to have fixed this, happy days
