### ISSUE TITLE
CoP Dawn - Prishe does not use Nullifying Dropkick

### ISSUE THREAD

**Issue by Zoltz** [EdenServer/community#3419]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Prishe is supposed to remove Promathia's damage shields with Nullifying Dropkick. However, once Promathia uses Wheel of Impregnability to become immune to physical damage, it's game over because she doesn't. I wonder if she's missing a regain trait? She can't hit for TP at that point, so perhaps that's why.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
