### ISSUE TITLE
Outpost Guard in Valkurm Dunes Near Konschtat Highlands Has Incorrect Name

### ISSUE THREAD

**Issue by JigokunoOusama** [EdenServer/community#342]
Guard in Valkurm Dunes near Konschtat Highlands zone entrance displays incorrect name.  It's dialogue is also incorrect.  There seems to be two faction flags posted next to him.

**Comment by godmode** [comment]
Thanks for reporting. This is likely because you have an incorrect client version. When you log in it will say something like “Eden doesn’t support this version.”

**Comment by beauxq** [comment]
Can you confirm what version of the game you have?
In the game type `/ver`
