### ISSUE TITLE
Den Scorpion might not be agressive to sound.

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3420]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
I went to try a fishing spot in den of rancor. I tought I was in a safe spot then den scorpion came in very close and didnt even agro, so maybe its because I was standing in the water. Wanted to report that cause they are aggressive and sound agro. I didnt test out if they were outside water cause it was a 100% death to me.

**Comment by mlandrum22** [comment]
I believe this is a navmesh issue? There are similar areas around water that do not aggro. I know the Manta spot in Kuftal doesn't aggro at all, and there are patches of no aggro at the Cape Terrigan Manta spot.

**Comment by ElectronicMan83** [comment]
Oh might be the same case than kuftal. So I assume we can fish there safely without having issue with navmesh rules since its not the case in kuftal?

**Comment by InoUno** [comment]
Resolved with October 4th, 2021 update.
