### ISSUE TITLE
Monarch Ogreflys Not Double Attacking

### ISSUE THREAD

**Issue by Spiffly** [EdenServer/community#3421]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

Was skilling up on Monach Ogreflys in attohwa Chasm. They're listed here https://ffxiclopedia.fandom.com/wiki/Monarch_Ogrefly as being warrior type mobs. I killed these for around 45 minutes and didn't have double attack proc once. I have no other source of information to confirm that they are indeed warrior type mobs.

**Comment by 59blargedy** [comment]
resolved in december 1 patch
