### ISSUE TITLE
Steam Cleaner Detectors spawn more then 5 dolls

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3422]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Detectors in sky should only ever spawn five dolls. https://ffxiclopedia.fandom.com/wiki/Detector

It seems that by zoning then, de-aggroing, then reclaiming before it despawns causes them to reset their mob counter.

While trying to spawn SC this morning I got to 7 mobs before realizing something funny was going on.

ver: 30181205_0

**Comment by 59blargedy** [comment]
this appears to be by design and expected behavior
https://ffxiclopedia.fandom.com/wiki/Detector
