### ISSUE TITLE
SMN quest "Class Reunion"

### ISSUE THREAD

**Issue by Lilmallet** [EdenServer/community#3425]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
game version 30181205_0

If attempting to do the BC fight on this quest in a party with someone who has completed it previously, it will not give the battlefield prompt. Trading the Ice Pendulum will only give the text "It is a giant crystal."

**Comment by 59blargedy** [comment]
resolved in January 4, 2021 patch
