### ISSUE TITLE
Disseverment applying Poison without dealing damage

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3429]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

In Castle Oztraja I used Disseverment on a Yagudo Conquistador that had 4 Ni shadows up. The log printed that 4 of his shadows absorbed the damage, and I'm assuming I missed on the final hit of Disseverment, yet his HP moved to 97%. Nowhere did it mention that my attack landed at all for any damage, and I think it's safe to assume the 5th hit missed since Disseverment normally kills these mobs in 1 cast, so 3% damage from 1 hit doesn't line up.

I checked topaz and the lua for disseverment is missing a check to make sure the move did greater than 0 damage before applying the poison. I audited the other BLU physical spells with additional effects, and its clear there are some differences between Topaz and Eden, but here are my notes, hope this helps:

BLU Spells that don't appear to check for > 0 damage before applying effects in topaz:

Battledance
Disseverment
Frypan
Helldive (Topaz doesn't seem to have the knockback but I see it on Eden, so not sure if the damage check is there, worth quickly looking for)
Hydroshot (The additional effect isn't coded on topaz, and probably isn't on Eden either, but if it is, it needs a damage check)
Ram Charge (Same as Helldive, Topaz doesn't have the knockback but worth checking for damage > 0 on Eden, we have the knockback)
Sprout Smack
Tail Slap
Terror Touch
Wild Oats

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in February 8, 2021 update
