### ISSUE TITLE
Smilodon hide and crafts related to it

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#343]
https://ffxiclopedia.fandom.com/wiki/Smilodon_Hide

This is a WOTG era crafting material that was available on Kupo but is no longer available here.  I think it was gained from either Leatherworkers guild purchases or from killing the high level tigers at the bottom of Kuftal Tunnel.

Either way, they're not available on Eden but Smilodon Mantles (NQ and HQ version) do exist still.  It is possible there are leathers & other crafts derived from those hides as well.

Reporting this so it can be addressed by the dev team.

**Comment by icariumkupo** [comment]
I can confirm smilodon hides were purchase-able from the leathercrafting guild on Kupo. It would be my opinion to add those hides back to the guild rather than remove the mantles. It's a rather harmless item.

**Comment by Elysien** [comment]
I wouldn't say harmless, if it just served as a mid level alternative to Amemet that would be fine, but in the case of Samurai, the HQ is actually best in slot at 75 SAM for numerous instances, beating even Cerberus Mantle+1 for Y/G/K on a lot of things.

**Comment by gweivyth** [comment]
I'd say keep it.  I'm not entirely sure if it is actually better than Cerberus Mantle +1 (is 1 strength better than 12 attack?  I don't know.) but regardless, if it's ONLY "better" for Samurai, I'm cool with that.  We've left in other pieces of gear for other jobs from WoTG mobs for variety in gear, I don't see why this would be different.  I can't see any job other than SAM really caring about this except maybe WAR/THF?

**Comment by godmode** [comment]
It’s different because Smilidons don’t exist in present vanadiel

**Comment by beauxq** [comment]
I'm neither for nor against keeping the smilidon stuff, but I'd just like to point out:

The fact that smilidons don't exist in present vanadiel doesn't mean their hides don't exist in present vanadiel.

I do care about coherence like this, but this isn't exactly incoherent. The smilidons could be extinct, but the hides and leathers could still be preserved, maybe even in abundance.

**Comment by Elysien** [comment]
>           I'd say keep it.  I'm not entirely sure if it is actually better than Cerberus Mantle +1 (is 1 strength better than 12 attack?  I don't know.) but regardless, if it's ONLY "better" for Samurai, I'm cool with that.  We've left in other pieces of gear for other jobs from WoTG mobs for variety in gear, I don't see why this would be different.  I can't see any job other than SAM really caring about this except maybe WAR/THF?

Samurai's top-end weaponskills come tied with a 100% attack boost, generally speaking it isn't difficult for them to attack-cap on even the higher end of targets depending on buffs/food/etc. It's probably a similar case with Greatsword Dark Knight, they also have a hefty attack boost tied to their weaponskills, though Samurai has a 25% boost lead over Dark Knight.

When Hagun is released you're going to see Samurai a lot more often, and as things stand a (or rather, was) easy mid-tier synth stands to outperform a high-end, and pretty coveted mantle in more cases than not. To be frank, Cerberbus Mantle is pretty much the main reason to hunt Cerberus at all, and while the aforementioned Mantle is useful for other jobs in other areas, it would lose a fair deal of appeal if Smilidon Mantle remains as is.
