### ISSUE TITLE
Up in Arms monster Fe'e has extremely slow attack speed

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3430]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

A recent patch "broke" Fe'e's attack speed. Per youtube videos and the wiki, he should multi-attack often and rapidly early for low damage, and ramp up his attack damage and lower his attack speed/multi-hit as his tentacles break. I did this a few weeks ago and it had these mechanics, but now (perhaps after the fix to Sea Monk attack speed?) it starts the fight out with no multi-hits and 8 seconds between attacks. This invalidates old strategies of using spike damage and can cause you to time out if you are relying on older strategies.

![image](https://user-images.githubusercontent.com/13668758/99750839-17b03780-2aaf-11eb-963e-6ee8a9563cd2.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in February 1, 2021 update.
