### ISSUE TITLE
Vulcan degen and other Alchemic Ensorclement usables (probably clothcraft too) don't work

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#3432]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Similar to this issue:https://github.com/EdenServer/community/issues/3372
The item-use feature that would grant an enfire effect does not work (the additional effect: fire damage does work)

https://ffxiclopedia.fandom.com/wiki/Vulcan_Degen

I strongly suspect the following items are also affected by this:
https://ffxiclopedia.fandom.com/wiki/Prominence_Axe
https://ffxiclopedia.fandom.com/wiki/Prominence_Sword
https://ffxiclopedia.fandom.com/wiki/Vulcan_Blade
https://ffxiclopedia.fandom.com/wiki/Vulcan_Claymore
https://ffxiclopedia.fandom.com/wiki/Vulcan_Sword

Similar item type but should grant 'enlight':
https://ffxiclopedia.fandom.com/wiki/Sacred_Sword
https://ffxiclopedia.fandom.com/wiki/Sacred_Mace
https://ffxiclopedia.fandom.com/wiki/Sacred_Degen
https://ffxiclopedia.fandom.com/wiki/Hallowed_Sword
https://ffxiclopedia.fandom.com/wiki/Sacred_Maul
https://ffxiclopedia.fandom.com/wiki/Sacred_Wand
https://ffxiclopedia.fandom.com/wiki/Sacred_Lance

Similar items that grant Enfire/Enwater/Blaze spikes:
https://ffxiclopedia.fandom.com/wiki/Fire_Bracers
https://ffxiclopedia.fandom.com/wiki/Water_Mitts
https://ffxiclopedia.fandom.com/wiki/Blaze_Hose

https://ffxiclopedia.fandom.com/wiki/Kinkobo

**Comment by deepbreathingeden** [comment]
![1612766398802](https://user-images.githubusercontent.com/53072734/109505511-19c66100-7ab6-11eb-8ac7-f295040dcec0.jpg)

**Comment by 59blargedy** [comment]
mostly resolved in November 29, 2021 update. will put up a new ticket for those remaining (enchanted items that cast spells)
