### ISSUE TITLE
Seigan+Third Eye counter mechanic needs check implemented for facing target

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3433]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

Currently possible to counter without facing the enemy using Seigan+Third Eye. Needs a check for facing target, similar to MNK counter.

**Comment by rude-jerk** [comment]
Resolved in November 30, 2020 patch.
