### ISSUE TITLE
Hydro Shot (Sahagin TP Move) incorrectly giving enmity down buff

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3434]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

Sahagin's TP move, Hydro Shot, seems to be giving the player an Enmity Down status effect. This effect can either be erased or clicked off, oddly enough. This is what the player blue magic spell does. However, the monster version should just be an enmity reset. Wiki also mentions that it should have a lengthy ready time. 

**Mob Skill:**

![hydromob](https://user-images.githubusercontent.com/49970272/99928177-f604b980-2d15-11eb-95eb-5b04ca1692a3.png)

**Blue Magic:**

![hydroblu](https://user-images.githubusercontent.com/49970272/99928176-f56c2300-2d15-11eb-85d4-aa0720c65fb8.png)

**Comment by rude-jerk** [comment]
Resolved in November 30, 2020 patch.
