### ISSUE TITLE
Kirin's Avatar using 2 hour ability twice

### ISSUE THREAD

**Issue by Toxophile** [EdenServer/community#3435]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0

Steps to reproduce:
1) Pop Kirin
2) Reduce Kirin's HP to whatever percentage causes it to use Astral Flow

There are multiple tickets on this issue already posted which have all been closed with no explanation:
https://github.com/EdenServer/community/issues/1820
https://github.com/EdenServer/community/issues/1415
https://github.com/EdenServer/community/issues/1190
https://github.com/EdenServer/community/issues/486

Issue:
Kirin's Avatar is using it's 2 hour ability twice in a row, 5 seconds apart. You can see in the screenshots the avatar readies Tidal Wave at 20:29:27 and again at 20:29:32. In the second screenshot you can see the actual usage of Tidal Wave at 20:29:31 and 20:29:40.

After wiping due to this, we popped a second Kirin and kited it around at 50% until it used Astral Flow. This avatar also used it's 2 hour ability twice in a row. I don't have screenshots of this one since we did not wipe to it.

![Toxophile_2020 11 22_203816](https://user-images.githubusercontent.com/45986546/99930468-f7c68100-2d05-11eb-8605-9b0b58dcc277.png)
![Toxophile_2020 11 22_203856](https://user-images.githubusercontent.com/45986546/99930469-f9904480-2d05-11eb-90ad-2a5b1af412d2.png)

**Comment by ArsinoeX** [comment]
We had a taste of this Kirin bug this evening. Splat after **_four_** back to back 2 hours. 
Tox just so happened to be there as well!

![unknown](https://user-images.githubusercontent.com/58524966/106706534-b0316080-65a4-11eb-817c-070f957edadb.png)

**Comment by deepbreathingeden** [comment]
![1612766460812](https://user-images.githubusercontent.com/53072734/109505495-159a4380-7ab6-11eb-8e8c-440433bf32ce.jpg)

**Comment by InoUno** [comment]
Should be resolved in March 22nd, 2021 update.
