### ISSUE TITLE
TP consumed when mob is out of range

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3436]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

TP should only be consumed if you ready a weaponskill on a monster that is in range, then gets pulled out of range by say a blm, or trying to ws a kited mob. Very similar to how you can run from monster tp attacks.

Engaging and using tp on a mob 20' away, should not consume tp, and should instead give an 'Out of Range' message and NOT consume tp. 

As far as I know, this is for melee weaponskills only. Ranged ws are behaving normally and tp should be consumed if you try to initiate from too far away. 

I haven't been able to find a solid proof of this from era and I don't have a retail account to verify, but as soon as I find something I'll add it to this report. 

/ver 30181205_0

**Comment by FariskaEden** [comment]
TP should be consumed on melee weaponskills if they are out of range.
Retail footage: https://i.gyazo.com/f2d726f656e734a3ab7c1d36d679dd02.mp4

**Comment by KnowOne134** [comment]
Its should, with proof given
