### ISSUE TITLE
Zdei Optic Induration is not resetting Enmity

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3437]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

It might be a little hard to tell from this log, but it petrifies me here and doesn't switch to my BRD that is on the hate list from Elegy/Requiem/Songs/etc.

Per the wiki it sounds like it should be an enmity reset

https://ffxiclopedia.fandom.com/wiki/Optic_Induration

![image](https://user-images.githubusercontent.com/13668758/99962131-9df1a580-2d5d-11eb-84d3-ecd02189aae0.png)

version: 30181205_0

**Comment by 59blargedy** [comment]
it is not a full reset - tested this tangentially when working on the chargeup fix, worked fine
