### ISSUE TITLE
Eo'zdei are not charging up before using Optic Induration

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3438]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Unless I missed the animation several times, Zdei don't seem to be charging up to use Optic Induration at all, they are using it as a normal TP move. I've stunned it, so its not instant, but the prerequisite "charging" before it uses it doesn't seem to be there. Again, I could be missing the charging animation, I'll keep an eye out but I haven't noticed it at all yet and have seen them use it twice.

version: 30181205_0

**Comment by 59blargedy** [comment]
resolved in February 1, 2021 update
