### ISSUE TITLE
Rainbow Berry mined in  Oldton Movalpolos

### ISSUE THREAD

**Issue by Wonkstar** [EdenServer/community#3439]
### Checklist

- [\ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ \] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [\ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Description:
Mining in Oldton Movalpolos gives the Rainbow Berry Key Item. I mined the same node pre patch today and did not get this same issue.

Expected Results:
Should only revieve mining results available for the zone

Steps to Reprodude:
1) Logged into Oldton Movalpolos after patch on 23/11/2020
2) Mine the mining point at F-8
3) Notice that each time I mine the node I get a chat message Obtained KI Rainbow Berry

![image](https://user-images.githubusercontent.com/6034185/99987827-c41b4380-2d65-11eb-9966-32860ac9344c.png)

Version:  30181205_0

**Comment by rude-jerk** [comment]
Resolved in November 23, 2020 emergency maintenance.
