### ISSUE TITLE
Mandragora mobs don't have H2H or Martial Arts

### ISSUE THREAD

**Issue by beauxq** [EdenServer/community#344]
Mandragora mobs are attacking once per round instead of twice like they should.

And their delay is about 6.4 seconds per attack round, which is actually what it should be, but in light of this other bug: https://github.com/EdenServer/community/issues/339 , this suggests that they don't have the Martial Arts trait. So fixing that other bug, should increase their delay and then the Mandragoras will need Martial Arts to return their delay back to 6.4 seconds.

**Comment by beauxq** [comment]
Did you change only the mobs named "Mandragora"?
It was meant to be all of the category Mandragora.

**Comment by godmode** [comment]
Yeah a search for them I didn’t see the others. Should have done family id
