### ISSUE TITLE
Padfoot NM respawning if no Ring or Earring drop

### ISSUE THREAD

**Issue by Wanpide** [EdenServer/community#3440]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

The NM Padfoot is supposed to spawn in 5 locations and only one of them is supposed to drop an Astral Earring or Assailants Ring. Once one of these items drop the remaining unclaimed Padfoots despawn. Today after maint, the Padfoots kept respawning if no ring or earring dropped. Which should not be the case.

**Comment by deepbreathingeden** [comment]
![1612766460812](https://user-images.githubusercontent.com/53072734/109505354-f1d6fd80-7ab5-11eb-922c-b7af2554d93d.jpg)

**Comment by 59blargedy** [comment]
resolved by another dev in february 20, 2023 update
