### ISSUE TITLE
Dark Knight Spell absorb not accurate

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3442]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
From :https://www.bg-wiki.com/bg/Category:Absorb_Spell and https://ffxiclopedia.fandom.com/wiki/Absorb-DEX
absorb are much lower on eden. 

When I got the spell I was doing 3-6 on absorb dex. When I got resisted, It just didnt absorb anything. When it landed it was full duration.
It will profit to future people leveling dark, but I remembered some vague memory of it.

**Comment by VirtuosusFFXI** [comment]
You're linking present day wiki articles, which is a bit unhelpful. Here is the information I could find for era:

吸収量は詠唱者のLvに依存する。Lv75で最大18吸収

"The amount of absorption depends on the caster's Lv. Up to 18 absorption at Lv75"

In addition to this, there was a patch on retail that changed how Absorb-STAT spells function. Here are the notes: 

"The effects of the following dark magic spells no longer diminish over time:
Absorb-STR / Absorb-DEX / Absorb-AGI / Absorb-INT / Absorb-MND / Absorb-CHR / Absorb-ACC"

**Comment by ElectronicMan83** [comment]
What I did try was on desert beetle at level 40 where you can obtain the spell on about 10-20 beetle I tested.
If you follow from wiki : 

Absorb-DEX gives a base absorption of 11~22 Dexterity.
Every 5 levels adds +1 Dexterity.[1]

11 base at 40.
if you apply that math at 75 you end up with 18 too, Wiki is accurate. 
The +3-6 was right after I used it . So It wasnt decaying.

**Comment by VirtuosusFFXI** [comment]
Ah yeah that's a fair point, the 22 is just the extra +4 for level 75>99. So it seems the main difference is that there should be a decay.

**Comment by ElectronicMan83** [comment]
Must be complicated to code decay so they put a low steady absorb, but it feel a bit low.

**Comment by deepbreathingeden** [comment]
![1614121272006](https://user-images.githubusercontent.com/53072734/109505382-fa2f3880-7ab5-11eb-9c81-9a329fe301a0.jpg)

**Comment by 59blargedy** [comment]
resolved in June 28th, 2021 update
