### ISSUE TITLE
[PUP] Valoredge does 0 dmg in Limbus Apollyon SE floor 1 (slashing weak/blunt immnue)

### ISSUE THREAD

**Issue by Snugglepunk** [EdenServer/community#3443]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Valoredge does 0 dmg to slashing weak mobs in Limbus Apolloyon SE

Melee hits should be slashing.  All WS should be slashing except Bone Crusher which is Blunt.

**Comment by deepbreathingeden** [comment]
![1614324985261](https://user-images.githubusercontent.com/53072734/109505393-fbf8fc00-7ab5-11eb-9014-90e7f7eed791.jpg)

**Comment by E5una** [comment]
Update: I've heard from other pups that the same is true for observing the damage type being bludgeoning on Jailer of Temperance / Undead.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
