### ISSUE TITLE
Gravity's Evasion Down effect is incorrect

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3444]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver30181205_0

Currently, Gravity reduces the targets evasion by a static -10 evasion. In era, Gravity should reduce the target's evasion by 5%. This was added in an April 2003 update.

http://www.playonline.com/comnews/200304152139.html

> ヘヴィの追加効果としてターゲットの回避率をやや下げる(5%前後)ようになりました。
>As an additional effect of heavy, the evasion rate of the target is now slightly reduced (around 5%).

**Comment by KnowOne134** [comment]
in 2005 it seems to be changed to a static amount

**Comment by VirtuosusFFXI** [comment]
Which patch was that? BG wiki in 2008 still mentions that its a 5% reduction: 
https://www.bg-wiki.com/index.php?title=Gravity&oldid=83081

**Comment by VirtuosusFFXI** [comment]
If you're looking at FFXIclopedia, there is basically an edit war ongoing between 2005 and forward where it keeps getting changed between -10 evasion and -5% evasion every couple of months by people. Considering Square Enix noted the exact percentage reduction in their original patch, and then didn't touch it in any patch notes until July 2014 (introduction of Distract and Distract 2) I think its safe to go with SE's -5% claim.

**Comment by deepbreathingeden** [comment]
![pale-blonde-blue-eyes-pale-teen-petite-blonde-black-jason-brown-with-small-tits](https://user-images.githubusercontent.com/53072734/109505584-306cb800-7ab6-11eb-804a-e7ace3f6f42d.jpg)

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
