### ISSUE TITLE
Seaboard Vultures in Misareaux Coast are OOE exp camp

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3445]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The Seaboard Vultures in Misareaux Coast are level lvl 99 era mobs and appear to be scaled down on Eden to a level that is viable as an exp camp. In era, these mobs don't exist in the zone, and OOE they are level 83-84

Era:
https://ffxiclopedia.fandom.com/wiki/Misareaux_Coast?oldid=388371

OOE:
https://ffxiclopedia.fandom.com/wiki/Misareaux_Coast

version: 30181205_0

**Comment by E5una** [comment]
Just wanted to remind that this camp is still being used for level sync exp over 22k/hour on birds that shouldn't exist. Let me know how I can help. Taking a peek as Topaz it looks like these lines would need to be removed from mob_spawn_points.sql, although I have no experience with getting rid of spawns so I'm just guessing:

INSERT INTO `mob_spawn_points` VALUES (16879691,'Seaboard_Vulture','Seaboard Vulture',26,444.649,-7.877,61.826,252);
INSERT INTO `mob_spawn_points` VALUES (16879692,'Seaboard_Vulture','Seaboard Vulture',26,415.499,-7.782,44.747,35);
INSERT INTO `mob_spawn_points` VALUES (16879693,'Seaboard_Vulture','Seaboard Vulture',26,408.626,-7.746,45.758,228);
INSERT INTO `mob_spawn_points` VALUES (16879694,'Seaboard_Vulture','Seaboard Vulture',26,414.968,-7.841,66.431,119);
INSERT INTO `mob_spawn_points` VALUES (16879695,'Seaboard_Vulture','Seaboard Vulture',26,423.851,-8.004,44.379,237);
INSERT INTO `mob_spawn_points` VALUES (16879696,'Seaboard_Vulture','Seaboard Vulture',26,466.659,-8.271,83.38,215);
INSERT INTO `mob_spawn_points` VALUES (16879697,'Seaboard_Vulture','Seaboard Vulture',26,481.401,-8.672,77.162,96);
INSERT INTO `mob_spawn_points` VALUES (16879698,'Seaboard_Vulture','Seaboard Vulture',26,473.821,-8.431,81.614,254);
INSERT INTO `mob_spawn_points` VALUES (16879699,'Seaboard_Vulture','Seaboard Vulture',26,454.876,-7.955,70.81,35);
INSERT INTO `mob_spawn_points` VALUES (16879700,'Seaboard_Vulture','Seaboard Vulture',26,456.532,-7.813,71.153,66);

INSERT INTO `mob_spawn_points` VALUES (16879709,'Seaboard_Vulture','Seaboard Vulture',26,454.764,-23.776,236.728,251);
INSERT INTO `mob_spawn_points` VALUES (16879710,'Seaboard_Vulture','Seaboard Vulture',26,470.149,-24.343,277.509,67);
INSERT INTO `mob_spawn_points` VALUES (16879711,'Seaboard_Vulture','Seaboard Vulture',26,479.864,-23.78,265.142,14);
INSERT INTO `mob_spawn_points` VALUES (16879712,'Seaboard_Vulture','Seaboard Vulture',26,459.28,-23.966,285.45,231);
INSERT INTO `mob_spawn_points` VALUES (16879713,'Seaboard_Vulture','Seaboard Vulture',26,474.917,-23.651,257.635,105);
INSERT INTO `mob_spawn_points` VALUES (16879714,'Seaboard_Vulture','Seaboard Vulture',26,470.908,-23.778,262.96,54);
INSERT INTO `mob_spawn_points` VALUES (16879715,'Seaboard_Vulture','Seaboard Vulture',26,499.943,-24.185,324.51,15);
INSERT INTO `mob_spawn_points` VALUES (16879716,'Seaboard_Vulture','Seaboard Vulture',26,475.186,-24.925,331.739,206);
INSERT INTO `mob_spawn_points` VALUES (16879717,'Seaboard_Vulture','Seaboard Vulture',26,500.323,-24.229,323.273,77);
INSERT INTO `mob_spawn_points` VALUES (16879718,'Seaboard_Vulture','Seaboard Vulture',26,485.193,-24.415,325.114,250);
INSERT INTO `mob_spawn_points` VALUES (16879719,'Seaboard_Vulture','Seaboard Vulture',26,486.742,-24.403,315.951,15);

INSERT INTO `mob_spawn_points` VALUES (16879823,'Seaboard_Vulture','Seaboard Vulture',26,-31.599,-32.739,286.045,197);
INSERT INTO `mob_spawn_points` VALUES (16879824,'Seaboard_Vulture','Seaboard Vulture',26,-36.873,-32.267,312.571,45);
INSERT INTO `mob_spawn_points` VALUES (16879825,'Seaboard_Vulture','Seaboard Vulture',26,-35.18,-32.309,280.994,37);
INSERT INTO `mob_spawn_points` VALUES (16879826,'Seaboard_Vulture','Seaboard Vulture',26,-26.602,-32.678,294.633,29);
INSERT INTO `mob_spawn_points` VALUES (16879827,'Seaboard_Vulture','Seaboard Vulture',26,-28.876,-32.696,285.922,149);
INSERT INTO `mob_spawn_points` VALUES (16879828,'Seaboard_Vulture','Seaboard Vulture',26,47.113,-32.725,282.755,128);
INSERT INTO `mob_spawn_points` VALUES (16879829,'Seaboard_Vulture','Seaboard Vulture',26,4.818,-32.341,280.823,234);
INSERT INTO `mob_spawn_points` VALUES (16879830,'Seaboard_Vulture','Seaboard Vulture',26,4.849,-32.413,280.494,52);
INSERT INTO `mob_spawn_points` VALUES (16879831,'Seaboard_Vulture','Seaboard Vulture',26,-3.987,-32.303,289.209,221);
INSERT INTO `mob_spawn_points` VALUES (16879832,'Seaboard_Vulture','Seaboard Vulture',26,-4.155,-32.454,280.533,109);

This is all in the "-- Misareaux Coast (Zone 25)" section.

**Comment by deepbreathingeden** [comment]
![bbc for juul](https://user-images.githubusercontent.com/53072734/109505423-04513700-7ab6-11eb-9b1d-cce77f3bcd9e.jpg)

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 update.
