### ISSUE TITLE
Lebros Cavern Excavation Duty Assaulted booted party

### ISSUE THREAD

**Issue by HevansEden** [EdenServer/community#3446]
### Checklist

- [/ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ /] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ /] I have provided my client version in the details. (type /ver into your game window)

### Details

Lebros Cavern Assault booted my party out just before midnight (cst) 11-25-2020. BLM WAR THF. We were split doing walls when we were all booted from the server, when we logged on we were in the troll area of Halvung with aggro from trolls causing us to die.

**Comment by Mozzy4Ever** [comment]
Heh whoops. Told him it was a bug report issue but I misunderstood the problem. Was caused by server crash, can be closed.
