### ISSUE TITLE
 Tonberry Decapitator = NIN/SMN w/ Toad pet

### ISSUE THREAD

**Issue by TheChefm** [EdenServer/community#3447]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- x[ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

The  Tonberry Decapitator in Den of Rancor is suppose to be a NIN nm only , Went down there and its a NIN/SMN w/ Toad pet. Or could be a weird Naming ID thing ?

**Comment by EpicTaru** [comment]
What is your client version?

**Comment by TheChefm** [comment]
30181205-0

**Comment by TheChefm** [comment]
After a couple of attempts , Every attack was a double attack + Ranged Attack . But weird damage number, Attack1: 84, Attack2: 3, RA: 180 .  I have screenshot of this

**Comment by Mozzy4Ever** [comment]
Checked and Tonberry Decapitator is coded as NIN/NIN (which doesn't seem right...) Not seeing a pet with it, though.

**Comment by TheChefm** [comment]
I have screenshots / chatlog and isotaz as my witness of pulling a  Tonberry Decapitator  and a  Doom Toad was acting like its bst pet or smn pet .

**Comment by jamiecol25** [comment]
Was it not aggro through a floor / wall? No bst mobs have an undead toad as a pet as far as I'm aware

**Comment by rude-jerk** [comment]
Confirmed that the Tonberry Decapitator incorrectly has a Doom Toad pet.

**Comment by rude-jerk** [comment]
This beautiful couple was broken up in the patch on November 30, 2020. I hope you're all proud of yourselves.
