### ISSUE TITLE
Provoker NM very rarely using TP moves & heals from all elements.

### ISSUE THREAD

**Issue by PoppaPip** [EdenServer/community#3448]
The Provoker NM in Promyvion-Vahzl almost never uses TP moves. I've fought him (her?) twice, and each fight (lasting around 30 minutes) they only used one TP move. Also, it never switched element, and would heal from nukes of every kind.

Should be easy to check, but I have video if needed.

### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

version 30181205_0

**Comment by PoppaPip** [comment]
Update : Fought a few more times with more characters and it TP'd a few times per fight, "seems low" but could be normal. The "element swap" was still broken every time, though.

**Comment by deepbreathingeden** [comment]
![b](https://user-images.githubusercontent.com/53072734/109505600-3367a880-7ab6-11eb-978e-373d5e16d666.jpg)

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
