### ISSUE TITLE
karakul spawn chigoe as a charmed pet

### ISSUE THREAD

**Issue by Levanthro** [EdenServer/community#3449]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

When using a karakul as a charmed pet and you use sic it will spawn a chigoe that is non aggressive and "invisible" for about 3-4 seconds and then aggro the master as if it belonged there. This makes it hard to keep hate on the sheep.

version 30181205_0

**Comment by 59blargedy** [comment]
this was resolved some time ago and just never closed
