### ISSUE TITLE
Atelloune's Lament (OOE) can be started (but not completed) on Eden

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#3450]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently can pick up this quest from Atelloune even though it's OOE. Cannot complete since Ladybug Wings come from WotG areas.

**Comment by 59blargedy** [comment]
resolved in February 22, 2021 update.
