### ISSUE TITLE
SMN Avatar Diabolos seems to be doing real Diabolos Nightmare damage

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3453]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Per the bg-wiki page (ffxiclopedia doesn't list any numbers) this should be a 2 damage bio/tick effect. Currently it is doing something more like 30-50 damage per tick from some quick testing outside in South Gustaberg. I hit a goblin for 9 which brought it to ~90%, and then 2 ticks of nightmare killed it.

https://www.bg-wiki.com/bg/Nightmare

version: 30181205_0

**Comment by E5una** [comment]
I did some quick searching and the 2 seems backed up by a random forum post from 2005 (http://www.dynamisbums.com/forum/archive/index.php/t-1016.html):

"I personally wouldn't use Nightmare (AoE sleep and bio). I used it on a bumblebee outside of windurst, by accident actually, it slept just fine, but it's HP was going down very very slowly."

**Comment by seehj** [comment]
Gonna add one more link:

https://www.bluegartr.com/threads/35702-Diabolos-broken-kind-of/page2

Someone says that nightmare does 5%-7% of hp on EP(smn lv 75) mob before they wake up and claims SE caps smn damage on TW mobs(in the same thread someone says nightmare doesn't do crap to TW).

As additional note, Diabolos was bugged on release, so there is possibility that potencies were not correct in 2005 during time of these posts.

**Comment by 59blargedy** [comment]
resolved december 7 update
