### ISSUE TITLE
Warrior gets trait too soon

### ISSUE THREAD

**Issue by Ascheriit00** [EdenServer/community#3454]
I dont know if this is some kind of rework for the warrior job but i'm getting the trait Resist Virus I at level 11 when it's supposed to be obtained at level 15. My character name is Schnee if any developer wants to check out.

Also when using Axe i'm not getting the Raging Axe weapon skill at skill level 5.

Game version 30181205_0

### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

**Comment by KnowOne134** [comment]
in era Raging Axe is skill 10
