### ISSUE TITLE
Bloodsucker do not link

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3455]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Bloodsuckers in Bostanieux oubliette do not link, never been reported before.  They agro sound that is working just fine. I expect the nm to not link either making it even easier to solo.

**Comment by 59blargedy** [comment]
resolved in February 22, 2021 update.
