### ISSUE TITLE
Garuda Blood Pact: Hastega not being used at all

### ISSUE THREAD

**Issue by Levanthro** [EdenServer/community#3456]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I was doing avatars and used hastega before any other BP and it didn't use the BP but took the mp. Tried this in the original 6 primes.
Version 30181205_0

**Comment by Namiea012** [comment]
I wanted to kindly confirm that this same issue happened to me as well on 12/1/20. Hastega does not give haste, unfortunately.

**Comment by 59blargedy** [comment]
Resolved in December 1st mini-patch
