### ISSUE TITLE
[SAM] Missing job traits

### ISSUE THREAD

**Issue by adailtonoliveira** [EdenServer/community#3457]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window) VERSION 30181205_0

### Details
Job traits are not appearing correctly in job SAM. I'm level 50 and the JTs are missing: Resist Blind II (lvl25), Store TP II (lvl30), Resist Blind III (lvl40) and Store TP III (lvl50). My character is Sephirus. VERSION 30181205_0

**Comment by KnowOne134** [comment]
Are they supose to be shown like that. Only tier 2 i know to show is treasure hunter. Other wise they just stack onto the original trait

**Comment by rude-jerk** [comment]
Job traits simple stack onto a single job trait entry. Here's how job traits look on my 99 SAM on retail:
![image](https://user-images.githubusercontent.com/9592857/100821656-d3ae2280-341e-11eb-9e9e-186bb93a96b8.png)


Confirmed that you get the benefit of the second tier of Store TP:
![image](https://user-images.githubusercontent.com/9592857/100821428-58e50780-341e-11eb-9503-5b3518f519a8.png)
