### ISSUE TITLE
[PUP] Valoredge using Shield Bash at non intended range, causing automaton to freeze for the duration, no chat log seen however SB cooldown is back to 3mins

### ISSUE THREAD

**Issue by Aster-FF** [EdenServer/community#3459]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

As stated in title: if you engage a monster with your Valoredge automaton beyond melee range, and if the monster is casting a spell or is just about to do a ranged attack, the automaton would still attempt to use Shield Bash. But because it isn't in melee range to do Shield Bash, Valoredge would freeze for a few seconds(I assume it to be the same duration as the SB animation), with no chat log showing that Shield Bash is used. However, the Shield Bash cooldown would go back up to 3minutes.

Steps to reproduce:
1. Aggro from ranged distance, a monster capable of casting spells. Provoke/dia, whatever works.
2. Deploy your Valoredge to engage the monster while it's casting spells. Valoredge would freeze for a couple of seconds, then run into melee range to attack. Shield Bash cooldown is back to 3minutes.
(You can easily tell this because if the monster does an ability or casts another spell, your automaton will not use Shield Bash.)

Version 30181205_0

**Comment by rude-jerk** [comment]
Resolve in patch on December 7, 2020.
