### ISSUE TITLE
I suddenly started to double attack with the second hit doing almost 30k damage!

### ISSUE THREAD

**Issue by Rikoooooo** [EdenServer/community#3460]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

I was killing Mist Lizards in Konschtat Highlands for around 45 mins to an hour as 11RDM/5MNK. When out of no where I suddenly began to kill them in one attack round. I'd engage and seemingly double attack; the first hit being normal damage, but the second hit...around 30000 lol. I will provide screenshots of both the Mist Lizards I have killed thus far.
The first:
![Vampire_2020 12 01_172810](https://user-images.githubusercontent.com/64914008/100778480-f9c3ca80-33fe-11eb-8a91-d5ee6a443c4d.png)

The second:
![Vampire_2020 12 01_173749](https://user-images.githubusercontent.com/64914008/100778496-fdefe800-33fe-11eb-9664-d37e986b3895.png)

I was equipped with a Bee Spatha +1 and the buffs I had were food effect from Meat Jerky, Protect and Signet. I wasn't casting any spells on these Mist Lizards either, just engaging and swinging sword.

**Comment by Rikoooooo** [comment]
After those 2 kills I stopped to submit this bug report and after I went back to killing these lizards again and it seems to have went back to normal. ¯\_(ツ)_/¯

**Comment by 59blargedy** [comment]
resolved in a previous patch
