### ISSUE TITLE
Jeuno doesn't have Christmas Music during the Starlight Celebration

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#3464]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently Jeuno isn't playing the Starlight Celebration music. For full era immersion I'm hoping we can get it implemented. 

https://www.youtube.com/watch?v=C4m8w9xkelw

It slaps.

**Comment by Far-The-Killer** [comment]
Fixed kind of, but needs a better fix before closing.

**Comment by deepbreathingeden** [comment]
![pale-blonde-blue-eyes-pale-teen-petite-blonde-black-jason-brown-with-small-tits](https://user-images.githubusercontent.com/53072734/109505661-42e6f180-7ab6-11eb-9318-2a170ff351ad.jpg)

**Comment by 59blargedy** [comment]
resolved for now/future by another dev in a recent live update
