### ISSUE TITLE
Making headlines 

### ISSUE THREAD

**Issue by Joeytarutaru** [EdenServer/community#3465]
Making headlines is bugged not letting me complete have all scoops examined door got Cop not installed check door again went back to npc and still not working

#

## Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by tigo9** [comment]
https://github.com/EdenServer/community/issues/1729

https://classicffxi.fandom.com/wiki/Unavailable_Quests

**Comment by KnowOne134** [comment]
Rule 1 not checked. Duplicate
