### ISSUE TITLE
Hume F RSE in Ordelle's Caves, didn't get Magical Pattern

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3466]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Verified correct RSE week per http://www.pyogenes.com/ffxi/timer/v2.html. Did not have magical pattern KI. Quest was active under "Current". Could not get Magical Pattern from chest despite multiple tries.

**Comment by Mozzy4Ever** [comment]
I'm big dumb, wrong zone.

**Comment by rude-jerk** [comment]
motz dumb

**Comment by Mozzy4Ever** [comment]
So dumb I failed to even close it
