### ISSUE TITLE
Apollyon SW: 3rd Floor Mimics do not drop ABCs

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#3469]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

The mimics on the 3rd floor of Apollyon SW still do not appear to drop ancient beastcoins as they should.

**Comment by 59blargedy** [comment]
resolved january 11, 2021 patch
