### ISSUE TITLE
Fishing skillups on x2 or x3 catches.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#347]
Unsure if it's just bad luck or it isn't coded to be possible - when catching x2 or x3 Yellow Globes or Bastore Sardines I'm not getting multiple skillups.  On retail for example, you had a skillup chance for each fish reeled in and it appear like this:

Lilswitche caught 3 bastore sardines!
Lilswitche's fishing skill rises 0.1 points.
Lilswitche's fishing skill rises 0.1 points.
Lilswitche's fishing skill rises 0.1 points.

**Comment by Setz0r** [comment]
I want to believe this because i have a slight memory of it from 14 years ago.  But after testing on retail, we can't seem to reproduce this.  You wouldn't happen to have a link to a forum post or screenshot of this happening?

**Comment by Lilswitche** [comment]
Trying to find something - I wanted to say this was the case because in the age of fatigue getting a x2/x3 counted against your fatigue as well.

**Comment by Lilswitche** [comment]
I can't find evidence of this without it possibly being Pelican Ring procs.  Maybe that's where my memory gets fuzzy since that item allows for separate skillups from 1 fish.
