### ISSUE TITLE
[DRG] Spirit Surge possibly not healing enough

### ISSUE THREAD

**Issue by MB213** [EdenServer/community#3470]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

Spirit surge might not be returning the right amount of HP. The only 2007 sources I can find on it all say it's supposed to restore HP equal to the Wyvern's remaining HP, which is at least 991 at level 75. Currently for me it restores 267. 
I haven't tested High Jump or Super Jump, but aside from those the other effects of Spirit Surge all seem to be working properly. To reproduce at level 75 just use Spirit Surge at low HP with a full HP Wyvern.

Sources:
https://ffxiclopedia.fandom.com/wiki/Spirit_Surge?oldid=342684
https://www.bg-wiki.com/index.php?title=Spirit_Surge&oldid=23640

**Comment by rude-jerk** [comment]
Resolved in patch on December 14, 2020.
