### ISSUE TITLE
NPC is charging full conquest point price for scroll of instant warp

### ISSUE THREAD

**Issue by Eolis82** [EdenServer/community#3471]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0
Crying Wing, I.M. used 750 conquest points instead of 10 when I purchased it from him in Bastok Mines

**Comment by KnowOne134** [comment]
Must not bee reading that big blue text that pops up before you buy it
