### ISSUE TITLE
Dawn mission Bugged entry/fight

### ISSUE THREAD

**Issue by Dtrix360** [EdenServer/community#3472]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

While attempting the Dawn mission a few things happened and now I am unable to access it at all. 

- Firstly my party entered the fight, buffed, then engaged. After first form went down, the second form almost immediately one shot one of our members with a 1100 damage invisible unlogged meteor and almost wiped another. Promathia killed both npcs and then continued fighting vs resetting.

- Upon trying to re-enter the fight myself and a few others were unable to enter the fight, instead getting locked up staring at the entry location awaiting the dialog to pop up. Those who crashed themselves after 15+ minutes of waiting ended up in a state of falling forever while waiting for unstuck to take effect.

- The two that entered killed themselves to Promathia who then spent the next 25 minutes killing Prishe every minute without a raise.

Version 30181205_0

**Comment by Orangemenace** [comment]
In addition to this if Prishe dies and is revived her and the other npc lose all ai and just sit there till the party wipes

**Comment by deepbreathingeden** [comment]
![1612766460812](https://user-images.githubusercontent.com/53072734/109505274-dc61d380-7ab5-11eb-8fd2-b89e9fa318d4.jpg)

**Comment by 59blargedy** [comment]
most of these issues are resolved as of jan 10, 2022, so will put up a new ticket for just the bugged entry

**Comment by davidsound** [comment]
upon defeating Promathia and starting cutscene, users are disconnected from the server and stuck in the zone upon logging back in and cannot progress mission.
