### ISSUE TITLE
Monolith in Ve'lugannon Palace Bug

### ISSUE THREAD

**Issue by Namiea012** [EdenServer/community#3474]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Hello,

During Sky, we worked with GM Penance who told us to make the following bug report: 

Monolith id 17502634 is only closing and not opening. It is instead acting like a yellow monolith.

The steps to reproduce this are to open the yellow monolith which will close the blue monolith. 

Thank you so much!

client version: 30181205_0

**Comment by rude-jerk** [comment]
Resolved in patch on December 14, 2020.
