### ISSUE TITLE
Ranged Attacks doing 0 dmg

### ISSUE THREAD

**Issue by Levanthro** [EdenServer/community#3476]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
I just ran through the dunes aggroed an ambusher checked its lvl it was 18 and my thf is lvl 11 and i was being hit for 0 dmg multiple times.

Version: 30181205_0

**Comment by 59blargedy** [comment]
resolved, thanks!
