### ISSUE TITLE
Exiting MH to Aht Urghan Whitegate puts you in the Serpentking Square fountain

### ISSUE THREAD

**Issue by MrBeignet** [EdenServer/community#3477]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

I exited the MH selecting "Area you entered from" and got put in the fountain. Then I was stuck, unable to move. I Mea'd my way off this place.

**Comment by rude-jerk** [comment]
This issue was temporarily hotfixed on December 7, 2020.

**Comment by KnowOne134** [comment]
Fix is in
