### ISSUE TITLE
Drexerion and Phanduron the Condemned

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#3481]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I was able to pull Drexerion without linking Phanduron and neither of them used their 2 hour. 

version 30181205_0

**Comment by 59blargedy** [comment]
2 hour added in earlier update, linking resolved in February 8, 2021 update
