### ISSUE TITLE
Jungle Boogeymen SMN mob casting tier4 and 5 nukes

### ISSUE THREAD

**Issue by redddddddddd** [EdenServer/community#3482]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
Hi all,

Version 30181205_0

Did Jungle Boogeymen and the SMN mob didn't summon any avatar and is casting tier 5 magic spells. It hit my rdm for 700 damage. Screenshots attached. Been looking online and have not seen any mention of this. It also didn't summon an elemental of any kind.

We didn't do anything special to make it happen, when we engaged it started casting Blizzard 4 immediately. 
![image](https://user-images.githubusercontent.com/75703014/101550810-f770eb80-397d-11eb-8a39-bda9a0c03fa2.png)

![image](https://user-images.githubusercontent.com/75703014/101550187-e378ba00-397c-11eb-89a2-097f14c10647.png)

**Comment by DrfistMD** [comment]
Did 10 runs of JB yesterday and the SMN did use Astral Flow each time, but other than that did nothing SMNey.  When it wasn't silenced it did try and cast Freeze I/II and Blizzard V, and never had an elemental out.

**Comment by deepbreathingeden** [comment]
![dfgsdfg](https://user-images.githubusercontent.com/53072734/109504943-89881c00-7ab5-11eb-9495-7ada361baa9f.png)

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
