### ISSUE TITLE
Descriptions for Group 2 Merits Incorrect

### ISSUE THREAD

**Issue by ubrobbins** [EdenServer/community#3485]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Desperate Blows Effect in game states: "Reduce delay by 2 percent."
Eden Wiki states the effect is 5% not 2% per merit.

Dark Seal states: "Recast: 5min. Shorten cast time of all dark magic spells by 10 percent."
Eden Wiki states it should be 15 min like other similar job abilities in era. With each additional merit reducing the recast by 2.5 minutes. Additionally, it does not shorten the cast time of all dark magic spells at all.

Diabolic Eye states: "Recast: 5 min. Increase physical attack accuracy by 5 percent." 
It should read "Recast 15min. Increase physical attack accuracy by 20."

Additionally the Group 2 merits: Warrior's Charge, Assassin's Charge, Feint, Feral Howl, Killer Instinct, Stealth Shot, Flashy Shot, Shikikoyo, Blade Bash, Sange, Deep Breathing, Diffusion, Snake Eye, Fold, Role Reversal all have errors in their recast time in their respective descriptions.

Version: 30181205_0

**Comment by KnowOne134** [comment]
all have been corrected and found here:
https://github.com/EdenServer/Eden-Client_DATs
