### ISSUE TITLE
Windurst Rank 10 Mission Final Cutscene

### ISSUE THREAD

**Issue by Orangemenace** [EdenServer/community#3487]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Once clicking on door the final time for the rank 10 cutscene for windurst rank the cutscene plays and you are ported out into windurst walls you gain rank 10 but get no money or windurst banner.  Zoneing into Walls or logging back into walls will play the cutscene as well as touching the door but still no money or banner but the rank 10 will still be obtained.
GM Penance was able to see the same thing on the test server.

**Comment by InoUno** [comment]
Resolve with March 8th, 2021 patch.
