### ISSUE TITLE
Zoning resets cooldown on Beastmen's Seal and Kindred's Seal dropping

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#3488]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Zoning appears to reset the 5 minute timer between obtaining two seals.

How to reproduce:
1. Obtain a Beastmen's Seal or Kindred's seal
2. Leave the zone
2b (optional). Return to the previous zone
3. You can now obtain another Beastmen's Seal or Kindred's Seal without waiting 5 minutes.

ver 30181205_0

**Comment by KnowOne134** [comment]
have we determined this is correct behavior from retail, anyone?

**Comment by ccl085** [comment]
This is the correct retail behavior

**Comment by KnowOne134** [comment]
I thought so
