### ISSUE TITLE
DRK AF Quest "Blade of Evil" mobs have incorrect jobs

### ISSUE THREAD

**Issue by Toxophile** [EdenServer/community#3489]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Client version 30181205_0

There are three mobs spawned for this AF quest, one Gerwitz's Scythe and two Scythe Victims. Per the various wikis, the Gerwitz's Scythe is supposed to be a RDM, one Scythe Victim should be a BLM, and the other a WAR. I just completed this quest about 10 minutes ago and the Gerwitz's Scythe was a DRK casting only Absorb spells, and both Scythe Victims were WAR casting nothing.

Steps to reproduce:
1. Be on the quest Blade of Evil
2. Travel to Middle Delkfutt's Tower and trade a Quadav Mage Blood to the ??? to spawn the mobs for the quest

**Comment by 59blargedy** [comment]
resolved in January 18, 2021 update
