### ISSUE TITLE
Fafnir/Nidhogg has MP / is Aspir-able

### ISSUE THREAD

**Issue by danismyhero** [EdenServer/community#3490]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Fafnir / Nidhogg was not Aspir-able in retail.  They do not have a MP pool.

https://ffxiclopedia.fandom.com/wiki/Category:Wyrms

Review Family information.

**Comment by 59blargedy** [comment]
resolved january 11, 2021 patch
