### ISSUE TITLE
Fenrir Prime's Crescent Fang applies paralyze through shadows

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3491]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

This is a retroactive bug report so I'm sorry for missing some screenshots of perfect information, I think I'll be doing it again very soon so I can update. Last time I did Fenrir Prime (within the last few days) Crescent Fang was being absorbed by my shadows (correct) but was applying paralyze even though it was absorbed (incorrect?). I can't find anything that suggests this is desired behavior. 

I didn't notice if the blind on Moonlit Charge was the same or not, only this one sorry!

Note: Not sure if this happens w/ player version of the pet, haven't checked vs a mob w/ shadows!

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in December 21, 2020 patch
