### ISSUE TITLE
Hot Dog title not granted

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#3494]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Very important bug, when you finish the quest Smoke on the Mountain you are not granted the title Hot Dog.

**Comment by Far-The-Killer** [comment]
fixed
