### ISSUE TITLE
Mirror, Mirror quest doesn't pops Dragon at the second part of fight

### ISSUE THREAD

**Issue by genelhu** [EdenServer/community#3495]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details
version: 30181205_0
When i entered the BCNM of this quest to fight the dragon, i called a jug pet, since i am BST to help me in the fight. The fight begins you alone and after some HP of the dragon is taken, there is a CS and after the CS it brings back the Dragon AND your fellow to fight with you. Since i was with my pet, nor the dragon, nor the fellow came in, and i bacame stuck in the BC without the possibility of continue the fight. So i had the idea of leave the BC and restart the fight without the pet.

After the CS, the Dragon AND the fellow came in and i could finish the fight, even calling a pet to help.

Since i called the GM, he asked me to post it here so u could solve this issue.

HOPE THIS HELPS!

Sangraawl

**Comment by KnowOne134** [comment]
was fixed 12/15/2020
