### ISSUE TITLE
Gates of Havlung will not open with KI

### ISSUE THREAD

**Issue by Sorant18** [EdenServer/community#3496]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Gates of Havlung in Mount Zhayolm will not open with Key item.
Spoke with GM Penance and they were unable to open them as well.

Steps to reproduce error....
1 - have key item "Cast metal plate"
2 - click on Gates of Havlung
3 - get text " You insert the cast metal plate into the keyhole.
4 - doors do not open

version 30181205_0

**Comment by InoUno** [comment]
Thanks for the report! This should be fixed live now. If the door still doesn't open, then please reopen the issue.
