### ISSUE TITLE
Rytaal in Aht Urghaan Will not give new ID Tags

### ISSUE THREAD

**Issue by Drognand** [EdenServer/community#3497]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

So this is fun :). 

Myself and Shuro went and did Leujaoam Sanctum Assualt and completed it. After when we returned to Aht Urghan to get new ID tags from Rytaal (K-10 Aht Urghaan) he would react just like when multiple people used to talk to NPC's, we get 0 text or response from him at all. We did not have Tags active from prior to maintenance. I myself handed in old tags that failed prior to picking up the Assault mission without any issue picking up the first set of tags and entering the assault.

We came across another group who also finished an assault and had the same issue as we did. After placing a GM ticking and talking with Pennance it was determined a bug report was needed for this issue :D

Happy Hunting guys ^^

**Comment by KnowOne134** [comment]
was fixed 12/15/2020
