### ISSUE TITLE
diabolos can draw in players with no battlefield status

### ISSUE THREAD

**Issue by geologue** [EdenServer/community#3498]
### Checklist

First i was not in a party when i entered the fight called Darkness named.
second i accept an invite once i'm inside the fight.
Third: the draw in worked on the persons outside the fight and they were prisoner inside the fight without being able to interact with the fight.
Fourth: diabolos won and put them in an eternal prison. we had to warp.

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by KnowOne134** [comment]
Corrected on 7/5/2024
