### ISSUE TITLE
Fachan in Uleguerand Range have 0 drops (or I was incredibly unlucky) 

### ISSUE THREAD

**Issue by HitGubz** [EdenServer/community#3499]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details
Version: 30181205_0
Attempting to farm Ahriman Wings and tears from Fachan in Uleguerand Range. 
0/20 on any drops, hardly a big size pool but with Th4 I'd expect a tear every 2 kills. ~
http://www.ffxidb.com/zones/5/fachan -  65 Ahriman Wings out of 744 killed with no Treasure Hunter. 
Note was successful in stealing tears from them. 

Is the treasure pool incorrect on these mobs?

**Comment by Mozzy4Ever** [comment]
Hopped on test server, got wing on 4th kill.

![image](https://user-images.githubusercontent.com/11255886/102142798-9ab37c00-3e28-11eb-915c-e7b98d671501.png)

**Comment by KnowOne134** [comment]
unlucky feels
