### ISSUE TITLE
Beastmen Seals / XP

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#35]
Players can free farm beastmen seals from promyvion, and xp is rather easy to solo here as well. Look into this.

**Comment by godmode** [comment]
This will likely be patched when level sync has a penalty adjusted. Leaving the ticket open for now as a reminder.

**Comment by roriffxi** [comment]
Beastman seals should always be available in the promys, same with xp.  An xp penalty should be applied however if the job you're on is over level 30, but xp should never be completely negated.

http://ffxiclopedia.wikia.com/wiki/Promyvion_Guide?oldid=70377

Relevant bit:
Experience earned in a level-capped zone is either...
Formula 1) You earn the xp you'd get if your class were at it's full level.
Formula 2) You earn 1/2 the xp of your capped job.
... whichever is greater. If you're on a lv31 main capped down to 30, you'll get lots of xp and can do xp chains. If you're on a 60 main capped down to 30, you'll get 1/2 the xp a lv30 would earn, and you can't do xp chains.

**Comment by randomslumber** [comment]
I noticed a stray spawned from receptacle did not give any XP but dropped a beastman seal today
