### ISSUE TITLE
Unable to dig Elemental Ores

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#350]
Currently Adept (A20/level 80+) and have spent a few thousand greens already to no avail.  All digging done during waxing crescent with weather (mostly elemental weather) in Passhow, Tahrongi, and Rolanberry.

Even if the drop rate was excessively low, like 0.1%, there's a high probability I would have come accross one by now.

**Comment by Wiggo32** [comment]
Very impressive, you're moving up fast! Sounds like some bad luck, keep at it! Your chances only get better as you get higher. They're diggable I promise.

**Comment by tectal831** [comment]
dig harder!

**Comment by godmode** [comment]
After reviewing the code seems like bad luck. Please keep us updated if it continues after you rank up a couple times
