### ISSUE TITLE
Mob 'on death' functions not firing properly

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#3500]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

New issue as of this update, posting for general awareness since fix is already being worked on. 

Monsters who have an on death function aren't triggering their event. To be clear, this isn't ALL the time, but if you encounter some weirdness in the below, it's probably why.

Examples:
TE NMs in Dynamis
Boss statues in dynamis for ??? win
Monsters in Limbus to spawn portals (specifically SW tower, floor 3, perhaps others)
Possible CoP NMs
Possible BCNMs 

If you run into one of these make sure you take a screenshot of the issue as best you can and file a GM ticket.

**Comment by danismyhero** [comment]
Can add Bastok 9-1 Gigaplasm to this list.  Should split on death, does not.

**Comment by KnowOne134** [comment]
was fixed 12/15/2020
