### ISSUE TITLE
Ifrit and Leviathan resistances to amnesia are off

### ISSUE THREAD

**Issue by rpcon** [EdenServer/community#3501]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Ifrit and Leviathan are supposed to be virtually immune to amnesia from imps' abrasive tantra. They are actually no more or less resistant than any other avatar (i.e. they receive the status effect every time).

https://ffxiclopedia.fandom.com/wiki/Talk:Abrasive_Tantara

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 update.
