### ISSUE TITLE
Strider Boot drop rate is incorrect

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#3503]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Strider boots should be an Uncommon Category drop, but (I think) it's currently set to Rare. 

It's hard to 100% know, since there exists VERY little data on Strider Boots when they dropped from Simurgh, but based on the vast majority of comments about them in era, alongside the reported Trotter droprate they were replaced with it's fairly safe to assume these should be an 18% drop rate with TH4. 

https://ffxi.allakhazam.com/db/item.html?fitem=599

- "2 drops in 3 days."
- "we are 0/4 with 75 THF + THF knife and 1/1 with 0 THF in party Orz. ; ;" [1/5]
- "my Ls has got this HNM 4 times in a row so far so ^_^ the drop rate so far is 1/4"
- "We're 2/13 on drops over the past 15 days"

Trotters are listed at a 22.4% drop rate below with TH0 & a 350 sample size, which I'm not sure what that's worth considering the differing values between that and the XI wiki (there is no era data on the wiki from before the change).  
http://www.ffxidb.com/items/15736

Anyway, if anyone has any more sources it'd be appreciated.

**Comment by Sirhc137** [comment]
looks like the ffxiwiki page was subject to a few jumps in the reported rates:

<https://ffxiclopedia.fandom.com/wiki/Simurgh?direction=prev&oldid=806895>
became:
<https://ffxiclopedia.fandom.com/wiki/Simurgh?direction=next&oldid=805540>

<https://ffxiclopedia.fandom.com/wiki/Simurgh?direction=prev&oldid=830383>
became:
<https://ffxiclopedia.fandom.com/wiki/Simurgh?direction=next&oldid=822402>

reported values consistently suggest that Trotters are drop twice as frequently as D.Ingots. Earlier reports suggest the higher category.

**Comment by 59blargedy** [comment]
resolved with rmt changes in oct 4 2021 update
