### ISSUE TITLE
Wyvernpoacher Drachlox doesn't 2hr

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3504]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Just killed this nm(12/15/2020) and according to wiki he should use Eagle Eye Shot. He did not.

https://ffxiclopedia.fandom.com/wiki/Wyvernpoacher_Drachlox

/ver: 30181205_0

**Comment by 59blargedy** [comment]
resolved in January 18, 2021 update
