### ISSUE TITLE
Sword Skill incorrect cap, then cap changes to correct cap

### ISSUE THREAD

**Issue by nlogan89** [EdenServer/community#3506]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Playing on Mithra Thief level 5-6 with sword, started using sword at level 5 it capped at skill level 6. Then switched to dagger, switched back, then skill cap changed to correct level 12 cap. Happened again after level up, switching weapons fixed again. Small bug, but worth mentioning for future patch.

**Comment by Mozzy4Ever** [comment]
The checklist is there for a reason... 
https://github.com/EdenServer/community/issues/2743
https://github.com/EdenServer/community/issues/1648
