### ISSUE TITLE
Kirin is resistant to Stun/Thunder

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#3507]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
/version 30181205_0

https://www.youtube.com/watch?v=y3R13bVjmVg

Kirin should have an extremely high resistance to Stun. It landed once in 51 casts. It only landed while under the effect of Stymie.

It doesn't display the message that it -completely resists the spell. 

It was resisted by Elemental Seal and even Saboteur. It finally landed when I used Stymie, which increases Enfeebling Magic accuracy to 100% but does not bypass a mob's status immunity. The effect doesn't wear off if the spell is resisted, it took 4 casts until Stun landed.

I briefly nuked it a few times for a very small sample. Thunder and Earth elemental spells were heavily resisted. Fire, Water, and Blizzard seemed to land neutrally. Wind had a bonus.

Elemental resistance should be obvious considering the stats on lv99 gear, yet I imagine a much larger sample would probably be needed. This is only to give a small hint. 

Tier 5
Thunder 588
Stone 566
Water 4572
Aero 9232

Tier 1
Thunder 141
Blizzard 1133
Fire 1122
Water 1095
Aero 1906

If it's not too small of a sample, the frequency and variance of TP abilities used in this video might be helpful with another issue
https://github.com/EdenServer/community/issues/2090

From a quick glance, it seems to cycle through using certain TP move phases between casting spells.

It answers this closed issue as well, but Stun resistance is still incorrect. Silence, Gravity, and Bind landed. I can't discuss duration because gear is lv99, this is strictly fishing for immunity/high resistance checks. 
https://github.com/EdenServer/community/issues/376

**Comment by danismyhero** [comment]
There was a lot of theory work done on BG about this, how he isn't immune but has extreme resistance to the element.  Currently Eden does not have a generalized system in place (to my knowledge) and so a mob by mob audit has to be done.

Just one of the discussions:
https://www.bluegartr.com/threads/108199-Random-Facts-Thread-Other?p=5408544&highlight=kirin+stun#post5408544

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 update.
