### ISSUE TITLE
A Pose be Any Other Name - Cannot flag this quest

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#3508]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I am unable to flag [this quest](https://ffxiclopedia.fandom.com/wiki/A_Pose_by_Any_Other_Name) which is a pre-requisite to the adventuring fellow level cap raise quest chain.  Another player (Wulfgang) in my LS was able to flag it on DRK but I have been unable to flag it on several jobs.

Here are some facts:
-I have more than enough Windy fame to flag this quest.
-I have already tried talking to Angelica with and without various pieces of gear equipped and removed.

I think there may be a quest conflict of some sort happening.  I have the following quests in my "Current" logs:
Sandy: The general's secret, introduction to teamwork, the rivalry, signed in blood
Bastok: Rivals, The Stars of Ifrit
Windy: In a Pickle, Mandragora-Mad, Rock Racketeer
Jeuno: Storms of Fate, Lure of the Wildcat, Chocobo on the Loose
Other areas: Under the Sea, Test my Mettle
Outlands: Mama Mia, Trial by Water
Aht Urhgan: Rat Race

Please help or advice.  I put in a GM ticket but heard nothing thus far.  Figured it might be a problem for others.  Seems strange.

**Comment by KnowOne134** [comment]
https://ffxiclopedia.fandom.com/wiki/A_Pose_by_Any_Other_Name

You don't have quest in log?

What job and body armor where you wearing when triggering?

**Comment by greyenvy** [comment]
No i do not.  I have tried on rdm drk war pld whm and it will not flag no matter what I do.  Angelica just says three different things bit nothing about this quest.

**Comment by KnowOne134** [comment]
Try 1 of the jobs with the correct body. Like rdm with nothing on but tunic

**Comment by greyenvy** [comment]
I did that too.  I tried rdm and whm with the tunic and war with the harness.

**Comment by KnowOne134** [comment]
See code issue. Needa rewritten

**Comment by KnowOne134** [comment]
Fixed 12/28/2020
