### ISSUE TITLE
When Charm wears during combat the pet is non-aggressive (Bibiki Bay)

### ISSUE THREAD

**Issue by rockemsockemman** [EdenServer/community#3510]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details
Client Version: 30181205_0

When Charm is wearing off during combat, the mob wanders off/is non-aggressive. If there is no combat occurring, the pet is aggressive when charm wears off (which is normal behavior).

This is occurring in Bibiki Bay with Tropical Rarabs. This is happening with every charm.

Behavior seems to be similar to when Leave is used. (I am not using Leave in these occurences.)

**Comment by InoUno** [comment]
Should be resolved in January 11th 2021 patch.
