### ISSUE TITLE
BST pets attacking mobs that are already claimed

### ISSUE THREAD

**Issue by Wanpide** [EdenServer/community#3513]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Was in Phomiuna Aqueducts, I ranged attacked a Taurus but not before a BST could sic his pet on the mob. I claimed the mob but the pet attacked anyways. The mob then when claimed for the BST and I could not attack it. 

![Wanpide 12_18_2020 5_43_18 PM](https://user-images.githubusercontent.com/71911614/102668098-154a0780-4159-11eb-8f76-b8dbc9420128.png)

**Comment by InoUno** [comment]
Should be resolved with January 4th, 2021 patch.
