### ISSUE TITLE
King Vinegarroon Behavior

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#3514]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

It has spawned at the beginning of single earth weather twice, I'll be able to confirm double earth.
*It has spawned at the beginning of double earth weather
It has around 25k HP
Immune to Bind

There's a difference in how KV uses Draw-In, it appears to have:
Alliance Draw-In
Single target Draw-In
Boundary target Draw-In

Whenever either ~2-5 minutes go by, or it receives enough TP, it will always use either Alliance Draw-In or Single target Draw-In, followed by an AOE (always Earthbreaker, Venom Storm or Wild Rage)
After the AOE, it was always followed that with a Single target TP move (Critical Bite, Death Scissors, or Venom Sting)

FFXIclopedia is accurate about TP move descriptions, there's more to add.
I used a DRG75/NIN75 to find:
Earthbreaker is absorbed by 1-3 shadows or can miss.
Wild Rage is absorbed by 1-3 shadows or can miss.
Venom Storm goes through shadows, they're not lost, it can be resisted/evaded.
Critical Bite is absorbed by a single shadow or can miss. Although if it lands, it has a chance to reset the targets enmity. At 5:53 (24min video) It also has an added effect of Bind.
It also uses Death Scissors, it never used Mandible Bite because that's replaced by Critical Bite.

Boundary target Draw-In isn't followed by a TP move at all. It's only used if the main target is over 12' away from KV (doesn't always activate when the target is far away, more testing is needed) or attempting to leave the boundary. This shouldn't be confused with Single target Draw-In, it happened when Critical Bite knocked me back over 13'. At 3:51 (Highlights video) Yet, another time it landed, it didn't reset the targets enmity. At 3:22 (24min video)

The Boundary can be seen toward the end of the 24min video.

Highlights video:
https://www.youtube.com/watch?v=SV4tQZbwzME

24min video (Capture addon)
https://www.youtube.com/watch?v=UZZDwYNVgUo

Versus DRG75/NIN37:

https://i.imgur.com/6fYw1SR.png
https://i.imgur.com/hHQ4ZkA.png

**Comment by deepbreathingeden** [comment]
![pale-blonde-blue-eyes-pale-teen-petite-blonde-black-jason-brown-with-small-tits](https://user-images.githubusercontent.com/53072734/109504716-49289e00-7ab5-11eb-8379-16b90ddb98ab.jpg)

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
