### ISSUE TITLE
Memento Mori has 56 second recast time, should be 120 seconds.

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3515]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Tested on the test server while wearing no equipment, recast time was 56 seconds rather than 2 minutes per the wiki.

Current wiki (2 minutes)
https://ffxiclopedia.fandom.com/wiki/Memento_Mori

Era dated wiki (still 2 minutes)
https://ffxiclopedia.fandom.com/wiki/Memento_Mori?oldid=361971

June 2006 wiki entry (56 seconds, this is what we are using, but its not correct for our date)
https://ffxiclopedia.fandom.com/wiki/Memento_Mori?oldid=77387

version 30181205_0

**Comment by KnowOne134** [comment]
Corrected 4/5/2021
