### ISSUE TITLE
Growing Flowers (mog house exit quest)

### ISSUE THREAD

**Issue by Anniakai** [EdenServer/community#3516]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Quest:     Growing Flowers, San d'ORia
Problem:     Cannot trade the Marguerite flower to the NPC (Kuu Mohzolhi) to unlock the mog house exit choices.
Version: 30181205_0
All dialog provided by the NPC is normal. (She will explain gardening)
When attempting to trade the flower, nothing happens and the flower remains in my inventory.
When exiting a mog house in San d'Oria, no choice of exits menu appears. 
I AM able to trade the holiday event Kiddie Present to this NPC.
An in-game GM was unable to assist.

**Comment by EdenPenance** [comment]
To add onto this:

Was able to trade flower with GM character and quest completed without issue.
Player is from Windurst.
 Enna had !checkquest 0 GROWING_FLOWERS ran and returned AVAILABLE.
 moghouseFlag was 0.
 Tried manually adding the quest to player and having them trade, no dice. 
 
 Suspect the holiday event may be preventing this quest from progressing as it should.

**Comment by KnowOne134** [comment]
Corrected 4/5/2021
