### ISSUE TITLE
Banishing Gates in Garlaige Citadel have wrong text colour.

### ISSUE THREAD

**Issue by Rikoooooo** [EdenServer/community#3517]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Currently the Banishing Gates text colour in the chat log displays as white. On retail it would display the same as the hourly conquest update text, a greyish/black.

**Comment by 59blargedy** [comment]
resolved in February 22, 2021 update.
