### ISSUE TITLE
Summoner Avatar Shiva Blood Pact Ward : Sleepga - duration scaling

### ISSUE THREAD

**Issue by seehj** [EdenServer/community#3519]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver. 30181205_0

Currently sleepga duration scales with +smn skill on gear, with +28 sleep last 3 min.
This is incorrect according to this page: https://ffxiclopedia.fandom.com/wiki/Sleepga_(Blood_Pact)
+skill should only affect resist rate, with 90 seconds being full/max duration.

**Comment by E5una** [comment]
Era pages don’t say anything about the duration at all, and the current page says it duration doesn’t scale with skill, but this Oct 2008 page says +1 second duration for each +1 skill

https://ffxiclopedia.fandom.com/wiki/Sleepga_(Blood_Pact)?oldid=694231

Either way the 3 min duration with +28 skill doesn’t line up, but I’m not sure what is correct for era.

**Comment by E5una** [comment]
Ah, if you look through the history, the same day someone said it scaled +1 history, the same person removed their comment and edited it to say it doesn’t affect the duration at all, so it seems like there’s nothing to suggest a scaling duration. Seems like this should be removed.

**Comment by 59blargedy** [comment]
resolved in January 18, 2021 update
