### ISSUE TITLE
Mamool Ja Raptor might give inapropriate xp/ not enough hp.

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3520]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
I been meriting twice in Nyzul lately and saw people killing pet xp in Nyzul xp camp. I went to try not long after that night. A good merited black mage can one shot these for 340 xp per kill. They respawn fast ( maybe too fast ). But from the SS the xp yield is way too much. 340 base xp in chain 5 would give you 500+ xp here? sound off. 

That website site got legit screenshot and info. 

https://evilpaul.blogspot.com/2008/10/12k-exphr-black-mage-solo-or-why.html

http://www.playonline.com/pcd/verup/ff11us/detail/3668/detail.html
Quoting from that 2008 update 
The HP of the following monsters in areas introduced since the release of the Treasures of Aht Uhrgan expansion have been adjusted:
Mamool Ja's Lizard / Mamool Ja's Raptor / Fomor's Bats / Goblin's Bat / Goblin's Bee / Goblin's Beetle / Goblin's Crawler / Goblin's Rarab / Goblin's Dragonfly / Goblin's Ladybug / Gigas's Tiger

**Comment by InoUno** [comment]
The "per monster cap" for experience points has been resolved with the February 1st, 2021 patch.
