### ISSUE TITLE
NPC Quest Blighted Gloom NM drops incorrect item

### ISSUE THREAD

**Issue by AnkleAssassinz** [EdenServer/community#3523]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Just killed the mettalic slime NM in Rong. Pass and it dropped an axe for some reason. Killed as Thief TH4.

![image](https://user-images.githubusercontent.com/48929380/102933294-ffe21f80-446f-11eb-9253-27cd1ca463c6.png)

**Comment by KnowOne134** [comment]
Haha, someone's old code to clean up. Alright. Thank you

**Comment by KnowOne134** [comment]
Fixed 12/28/2020
