### ISSUE TITLE
Cactrot Rapido attacking slowly/not procing DA

### ISSUE THREAD

**Issue by BindXI** [EdenServer/community#3524]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I checked through log and didn't see a single event where he DA'd me.  I think he's technically a WAR and the old Avesta video also shows him attacking faster than he appeared to be attacking me.  Even accounting for the speed of the video.

**Comment by 59blargedy** [comment]
appreciate the report, but this has been noted on #3318 , so will track under that existing bug report instead.
