### ISSUE TITLE
Summoner Avatar Diabolos Blood Pact Rage: Camisado - missing Compression Attribute

### ISSUE THREAD

**Issue by seehj** [EdenServer/community#3525]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver. 30181205_0

Camisado is missing compression skillchain attribute.
This is easly checked by summoner using Shell Crusher into Camisado. This should produce gravitation skillchain. To double check if Shell Crusher has correct attribute you can do skillchain with moonlit charge or double punch, both of which produce gravitation.

Sources:
https://classicffxi.fandom.com/wiki/Camisado
https://ffxiclopedia.fandom.com/wiki/Moonlit_Charge?oldid=333505
https://ffxiclopedia.fandom.com/wiki/Blood_Pact?oldid=357786

![image](https://user-images.githubusercontent.com/10786412/102999912-3ed4ab80-452a-11eb-87a7-e8aee06e99fa.png)

**Comment by 59blargedy** [comment]
resolved in January 4, 2021 patch
