### ISSUE TITLE
Apollyon: Kaiser Behemoth has very low accuracy

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3526]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

30181205_0

See attached image. This is without flash or blind, on a couple of black mages. KB didn't hit us once the entire fight. He wiffed 10/10 swings.

![Miss](https://user-images.githubusercontent.com/55296729/103000015-2b105180-44f8-11eb-800f-4f65a6cbb441.PNG)

**Comment by Mozzy4Ever** [comment]
![image](https://user-images.githubusercontent.com/11255886/103019962-433e9b80-450d-11eb-86fb-22fb3580c988.png)

**Comment by 59blargedy** [comment]
resolved in January 4, 2021 patch
