### ISSUE TITLE
Summoner Avatar Carbuncle Blood Pact Ward : Glittering Ruby - bonus not decaying over time

### ISSUE THREAD

**Issue by seehj** [EdenServer/community#3527]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver. 30181205_0

According to this page: https://classicffxi.fandom.com/wiki/Glittering_Ruby , attribute bonus should gradually decrease.

**Comment by 59blargedy** [comment]
resolved in June 28th, 2021 update
