### ISSUE TITLE
Vanishing Act not available

### ISSUE THREAD

**Issue by tigo9** [EdenServer/community#3529]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

A Taste of Honey quest was implemented in 11/02/2020 patch, however the pre-req quest Vanishing Act is not working. You can speak to Ulamaal and get the starting cutscene, but after cs the quest does not appear in the list. Speaking to Ulamaal again just repeats the cutscene.

https://ffxiclopedia.fandom.com/wiki/Vanishing_Act

**Comment by rude-jerk** [comment]
Hi! Can you DM your character name to rudejerk in discord? I'd like to ask someone to check on your quest statuses just to be sure nothing has been missed before we dedicate time to trying to figure it out!

**Comment by KnowOne134** [comment]
just did this quest myself yesterday on an alt
