### ISSUE TITLE
In-Range Mobs "Out of Range"

### ISSUE THREAD

**Issue by JigokunoOusama** [EdenServer/community#353]
Many relatively stationary mobs like worms and undead mages will sometimes give the "<t> is out of range" dialogue.  During this time players are unable to attack the mob and it can be difficult to coax the mob into moving.

**Comment by Mozzy4Ever** [comment]
From what I understand, this has to do with navmesh

**Comment by archfiendrubicante** [comment]
https://gyazo.com/1fef494839eb7e0ae7851be3bf45fa54

Here's an instance of this specific issue occurring in West Sarutabaruta. It's happened twice in the last hour or two.

**Comment by archfiendrubicante** [comment]
That's with no addons or plugins enabled.
