### ISSUE TITLE
Groundskeeper Berserk should give Warcry status

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3530]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Berserk_(Doll)

Groundskeeper (And all Dolls) should gain warcry when they use Berserk. Currently, they're gaining a berserk effect.
![berserk](https://user-images.githubusercontent.com/55296729/103134050-38eedf80-467c-11eb-8787-60c13cb95687.PNG)

/ver: 30181205_0

**Comment by deepbreathingeden** [comment]
![1614121272006](https://user-images.githubusercontent.com/53072734/109504536-15e60f00-7ab5-11eb-9926-49d9cfa5b527.jpg)

**Comment by InoUno** [comment]
Resolved in March 22nd, 2021 update.
