### ISSUE TITLE
Tactics pearl completion puts you in space

### ISSUE THREAD

**Issue by tigo9** [EdenServer/community#3531]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Checking a ??? for tactics pearl quest, choosing to end and return to the entrance places you in space unable to move and need to use a warp item to get out.

Have confirmed this happens in promy-mea on the first and second floor ???s.

**Comment by KnowOne134** [comment]
i did this 3 times last week without an issue, ill be doing it again after conquest to see again. i only ever do 1st floor though

**Comment by tigo9** [comment]
Have it recorded on both video and screenshots if you need to see.

**Comment by tigo9** [comment]
Update: confirmed the same in dem

**Comment by KnowOne134** [comment]
Fixed 12/28/2020
