### ISSUE TITLE
Girandola- craftable but doesn't "exist"

### ISSUE THREAD

**Issue by Sworn777** [EdenServer/community#3532]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

Tried crafting Girandola's for 60-66 on Goldsmithing  recipe = x2 Beeswax, x2 Gold ingot, x1 Fire Crystal.
The issue: NPC price is 0 gil to sell back. I can put it on AH, but it doesn't show up/does not exist on the AH. 
Is this intended? Resale price on retail was 6,820-6,990 gil depending on fame level. 
I can still get skill ups on this item still, but at an extreme loss of gil with no possibility of any return.

**Comment by Mozzy4Ever** [comment]
Looks like it's an OOE synth so the synth needs to be deleted

**Comment by rude-jerk** [comment]
Resolved in January 18, 2021 patch.
