### ISSUE TITLE
Summoner merited Bloodpacts aren’t Magic Bursting

### ISSUE THREAD

**Issue by maldra** [EdenServer/community#3533]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0

I have tried using both Heavingly Strike and Thunderstorm (smn merit blood pacts) and neither of them are MBing like they should be. A friend of mine has tried Wind Blade as well and that did not MB either. These all should be able to have a MB according to their elements, but are not currently doing so.

**Comment by ElectronicMan83** [comment]
Also on a fusion skillchain in valkurnes dunes.  Fire II from Ifrit didnt magic burst.

**Comment by 59blargedy** [comment]
validated the code and tested, and these actually all magic burst and add damage based on the burst, just do not have a message. going to close and open a new ticket for clarity
