### ISSUE TITLE
"Chasing Tales" Quest Broken 

### ISSUE THREAD

**Issue by galenor** [EdenServer/community#3534]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.) Issue 3006 exists but closed, have been trying for a month to get someone to reopen it, but everyone ignores my questions about it, as a desperate measure opening a new one.
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

I completed early bird catches the bookworm quest, unfortunatly am unable to get Chasing Tales, when talking to client (Tosuka-Porika), he has no dialog or reaction whatsoever.

 I have skipped the step of asking for a time extension"early bird catches the bookworm" in the previous quest, not sure if related to this issue.

**Comment by deepbreathingeden** [comment]
![1612766398802](https://user-images.githubusercontent.com/53072734/109504538-17afd280-7ab5-11eb-9e18-e51b1530cf5a.jpg)

**Comment by KnowOne134** [comment]
sounds like you had quest hat in hand active which looks to be the real problem.
complete that quest and you can continue, all quests will be getting a make over as they can be
