### ISSUE TITLE
Actinic burst ridiculously overpowered

### ISSUE THREAD

**Issue by Goto28** [EdenServer/community#3535]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

way too powerful saw it land every single time on a hnm for full up time 100% for like 15 seconds every time the dude had like no equipment on literally

**Comment by 59blargedy** [comment]
resolved in February 1, 2021 update.
