### ISSUE TITLE
Simurgh Rage Timer

### ISSUE THREAD

**Issue by PancakeOfDoom** [EdenServer/community#3536]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Simurgh rage timer very much broken, supposed to rage after 20 mins and was held for around 25 mins until killed with no sign of rage.

**Comment by rude-jerk** [comment]
Resolved in January 4, 2021 patch.
