### ISSUE TITLE
Lobais' avatar not de-spawning when Lobais dies. 

### ISSUE THREAD

**Issue by Fng098** [EdenServer/community#3537]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
Doing swift belt runs and having back to back issues with Lobais' avatar not de-spawning when we kill Lobais

**Comment by deepbreathingeden** [comment]
![1612766460812](https://user-images.githubusercontent.com/53072734/109504572-20080d80-7ab5-11eb-8c02-91554d68d61c.jpg)

**Comment by KnowOne134** [comment]
Corrected 4/5/2021
