### ISSUE TITLE
Chat Filter Changes Not Saving

### ISSUE THREAD

**Issue by JigokunoOusama** [EdenServer/community#354]
After adjusting chat filters in the configuration menu settings are not permanently saved upon exit.  The settings seem to revert after a certain amount of time or after zoning.

**Comment by roriffxi** [comment]
There is an ashita plug-in called Filters that you can use to save filter settings.

Them not saving is a bug on all DSP servers and I think it might be tied to PlayOnline which we bypass here.  If that's the case, this is unfixable and the addon needs to be used instead.

**Comment by JigokunoOusama** [comment]
Is there anything I need to do to save my settings with the addon?  My settings seem to disappear after logout, zone, or whatnot, even with the addon.

**Comment by gweivyth** [comment]
If you use Ashitacast, you can have Ashitacast automatically load them on zone.  I am not at home so I don't have the command you need to do that, but maybe someone else will.

**Comment by KnowOne134** [comment]
duplicate https://github.com/EdenServer/community/issues/1327
