### ISSUE TITLE
Harmodios (Bastok music shop npc) is completely missing

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#3540]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

game ver 30181205_0

https://ffxiclopedia.fandom.com/wiki/Harmodios

Harmodios is currently completely missing from the game. The music shop is empty. To replicate, please go to the music shop and see that no one is standing in the shop. Very important npc for poor souls who need to purchase cornettes for fame.

**Comment by KnowOne134** [comment]
Pretty sure this is me. I'll correct tonight

**Comment by davidsound** [comment]
Should I open up a new issue for another NPC in Bastok Markets?

This one is missing too:

(I-9) Horatius (Inside Trader's Home)

**Comment by KnowOne134** [comment]
No need

**Comment by KnowOne134** [comment]
Fixed 12/29
