### ISSUE TITLE
Puppet not using any skills that target self

### ISSUE THREAD

**Issue by Kagekiki** [EdenServer/community#3541]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Kagekiki** [comment]
Puppets will not self cure or use stoneskin properly have tried to have it cure it self

**Comment by KnowOne134** [comment]
After the wait period of 3 mins for stoneskin?

**Comment by Nanji-yo** [comment]
I second that - no stoneskin after waiting >3 min

**Comment by KnowOne134** [comment]
Fixed 12/29
