### ISSUE TITLE
Beastmaster Job Quest completed, but job not unlocked

### ISSUE THREAD

**Issue by galenor** [EdenServer/community#3543]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Quest Save My Son shows as completed in jeuno quests, but beastmaster job not available. Character name Chipie. Quest completed maybe 1-2 months ago, never noticed the problem before now.

**Comment by 59blargedy** [comment]
That quest does not unlock beastmaster. did you do the quest following, https://ffxiclopedia.fandom.com/wiki/Path_of_the_Beastmaster
?

**Comment by galenor** [comment]
Hey, I was checking wiki again and just realized my mistake, will close this for now after I try talking to Brutus, sorry.
