### ISSUE TITLE
Mamool Ja Lurker's (Mamook) evasion seems too high.

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#3544]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Fought two level 83 Mamool Ja Lurkers in Mamook and their evasion seemed awfully high even for them.  Used /checkparam to determine accuracy and it was 395 while auto attacking, but still managed to miss over 50% of hits on both mobs.

I'm not entirely sure their evasion is retail accurate, perhaps prior to pDIF changes they were given higher evasion to compensate for incorrect values, but currently their evasion reminds one of Byakko when its evasion was adjusted too high.

**Comment by DeuceFFXI** [comment]
Shortly after killing one, we discovered their respawn timer was significantly shorter than it should be as well.  Roughly 5min. respawn when it should be 10min.

**Comment by EdenPenance** [comment]
![image](https://user-images.githubusercontent.com/76273942/103255608-8bb3ea00-494f-11eb-8076-f95bf9200ab9.png)

Seems about right to me since they're 83 and a THF mob. https://ffxiclopedia.fandom.com/wiki/Mamool_Ja_Lurker has a level 83 listed as 434 EVA

**Comment by Falaras** [comment]
You are short 111 accuracy using that max level ffxiclopedia stats,

**Comment by DeuceFFXI** [comment]
Could've just been the fact that I was using a 1-handed weapon, which I'm not too used to the caps for.  Some of the respawns did seem rather quick though.

**Comment by Slamm21** [comment]
plenty of 2h jobs like drk can have somewhat similar accuracy. Basically, thief mobs are meant to be evasive like this and private servers have had them with wrong stats for so long it's a distant memory.
