### ISSUE TITLE
Couldn't revive while wearing Berserker's Torque. 

### ISSUE THREAD

**Issue by Chungustein** [EdenServer/community#3545]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Died while engaged with Berserker's Torque on and died immediately after reviving. Was unable to revive and had to /ac naked to remove all equip before finally being able to revive. Lost around 5k exp trying to get a quick cure in before I died again until LS suggested I /ac naked. 

ver. 30181205_0

**Comment by deepbreathingeden** [comment]
![dfgsdfg](https://user-images.githubusercontent.com/53072734/109504607-29917580-7ab5-11eb-9032-5b044aeeb986.png)

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
