### ISSUE TITLE
Promy Vahzl - Procreator adds do not return to spawn point after party wipe

### ISSUE THREAD

**Issue by Kurokami5297** [EdenServer/community#3546]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver. 
30181205_0

In Promy Vahzl, the adds from Procreator do not follow the NM to return to spawn point after entire party's wiped.  The party could not reraise because the adds stayed on top of them.

**Comment by DeuceFFXI** [comment]
I would like to add that I had encountered this bug before as well on October 19th, 2020.  I made a comment about it in the discord but forgot to make a bug report.

In our failed attempt, much of our group had wiped on the steps, Procreator then walked back to its original position, and the Offspring simply gathered around a specific point on the stairs.  A few individuals attempted to reraise and were killed by the Offspring immediately.  Some of the offspring had to move to reach those individuals, which is when we noticed that they would reset to where they were after the initial wipe.

From what I could tell at the time, it appeared as though the Offspring would set their origin point to wherever the Procreator was whenever everyone on the hate table had died during the wipe.

**Comment by Mozzy4Ever** [comment]
Pretty sure this happens with any pet spawned by a mob. Wyverns from Dragoons are a common culprit. They don't follow their owner back to the owner's starting position, the pet will walk back to where it was spawned

**Comment by KnowOne134** [comment]
Correct. The point it was called is its spawnPoint

**Comment by GiichiHiro** [comment]
It would be highly unlikely that ALL of them spawned on the stair case across several runs though (This same thing happened to be, Offspring returned to the top of the stairs where all of the mages were)
When they spawned ontop of the Melees in the middle of the room.

**Comment by DeuceFFXI** [comment]
I'll add that they didn't seem to be returning to where they spawned as we were fighting Procreator more inside the arena than on the stairs until we started wiping.

**Comment by rude-jerk** [comment]
Resolved in patch on February 1, 2021.
