### ISSUE TITLE
Feint wears on missed swing

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3547]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently, the Feint buff is being consumed on the first swing, hit or miss and one of two things happen: You hit and the mob gets -eva, or you miss and lose the buff and no debuff is applied.

How it should be is Feint effect lasts up to one minute, and only wears off when you hit the mob, and the evasion down is applied. The buff should persist through missed swings. 

From wiki: Unlike Sneak Attack or Trick Attack, Feint still remains active despite missing. As long as a hit is landed (even for zero damage) within 1 minute of activation, Feint's evasion down effect will apply. https://ffxiclopedia.fandom.com/wiki/Feint?oldid=387857

/ver: 30181205_0

**Comment by rude-jerk** [comment]
Resolved in January 4, 2021 patch.
