### ISSUE TITLE
Apollyon SW Mimics {Too Weak}

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3548]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Mimics in SW Apollyon seem very weak. I don't have any data to show how they should be sadly, but this is just with !regen on the test server with 371 attack, Mandau/Blau.

![image](https://user-images.githubusercontent.com/11255886/103395376-85f70980-4af3-11eb-9c72-42970f4e935a.png)

I'm guessing their 289 defense is to blame. Though maybe they should have some sort of PDT/MDT as well? Not sure. Wiki's family page on mimics says they take -50% damage from Blunt/Piercing/Slashing, but Limbus likes to ignore normal family traits it seems.

**Comment by 59blargedy** [comment]
Resolved in January 11, 2021 update.
