### ISSUE TITLE
Windurstian Scarf and Master caster mitts gear not functioning outside nation's control

### ISSUE THREAD

**Issue by nicholasbludau** [EdenServer/community#3549]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Windurstian Scarf and Master caster mitts do not apply the gear stats when used outside nations control anymore.

**Comment by deepbreathingeden** [comment]
![b](https://user-images.githubusercontent.com/53072734/109504619-2dbd9300-7ab5-11eb-9b2f-90c70214ea83.jpg)

**Comment by dowzer** [comment]
Master Caster's Mitts are applying the correct stats in areas outside own nation's control, including zones controlled by beastmen, and Lumoria. They should also work in Dynamis. They correctly don't activate their stats in Aht Urhgan areas. 

These types of items require Signet for the stats to be applied. Sanction will also activate their stats.

**Comment by 59blargedy** [comment]
just validated windurstian scarf is fine as well. my guess is OP did not have signet on
