### ISSUE TITLE
Xolotl spawn conditions

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#355]
Haven't been able to get this guy. I check every now and then but he just simply never spawns.

**Comment by roriffxi** [comment]
I have checked on him too.  Either he isn't spawning at all, or he is despawning and resetting his spawn timer like KV does.

Problem is, this isn't correct for Xolotl, he should pop every night at 20:00 until he is killed.

**Comment by godmode** [comment]
This should be fixed.

**Comment by Setz0r** [comment]
@godmode the spawn conditions are wrong.  i found them on accident while looking for relevant code.

his hours are set to (hour >= 20 *and* hour <= 2) which is impossible
