### ISSUE TITLE
BST Pet despawning when charm fades

### ISSUE THREAD

**Issue by andre-macc** [EdenServer/community#3550]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver 30181205_0

- Have a charmed pet
- Engage in fight
- Wait for charm to fade while fighting
- Pet will despawn when charm fades

I have experienced that with a bunch of different mobs and regions, so I can't say if it's specific to certain mob families or zones. I've seen rabbits, crawlers, dhalmels despawning.

I've also been experiencing this issue:
https://github.com/EdenServer/community/issues/3510

Both are very similar.

**Comment by andre-macc** [comment]
I've been having this problem more frequently when I'm fighting with a charmed Hare around J-8 in Valkurm Dunes. This might be inconsequential though... I don't know.

**Comment by andre-macc** [comment]
Easy place to test mandies walking away (no aggro) after charm fades: E-9 Buburimu.

**Comment by InoUno** [comment]
Should be resolved in January 11th 2021 patch.
