### ISSUE TITLE
Carbuncle Ruby acts as "Old Ring" from Onion Rings quest

### ISSUE THREAD

**Issue by NoisomePossum** [EdenServer/community#3551]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Client version: 30181205_0

- After obtaining a Carbuncle's Ruby I went to activate the quest and clicked on the door to the House of the Hero. 
- Instead of the cutscene for the Summoner unlock quest I got the ending cutscene for the quest "Onion Rings"
- I don't have the "Old Ring" normally required to complete that quest (I had only gotten the very first dialog from Kohlo-Lakolo saying we needed the ring to get into the house). I'm also not on the Windurst mission (3-1) that would normally have you going to the location where the ring is found (I'm still on 2-3).
- "Onion Rings" is now marked as completed in my quest log although I never got the reward for the quest and I've now managed to flag the next quest in that line.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
