### ISSUE TITLE
pets are able to move while in a cannot move situation

### ISSUE THREAD

**Issue by andre-macc** [EdenServer/community#3552]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

Charmed pets that are petrified follow you out of battle but can't take any commands.

- Get pet petrified by a lizard
- Kill the lizard
- Move around and observe pet following
- Test a pet command like Stay

**Comment by Steam-arch** [comment]
Happens if you charm a sleeped pet also, pet wont fight untill status effect wears

**Comment by KnowOne134** [comment]
corrected in 8/7/2023 update
