### ISSUE TITLE
Unlisted Qualities

### ISSUE THREAD

**Issue by Dibision** [EdenServer/community#3553]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
I'm trying to start the Adventuring Fellow questline (starting with Unlisted Qualities) and the starting npc Luto Mewrilah in Upper Jeuno is bugged. Have had multiple characters and linkshell members attempt to interact with her and we all have the same result. Once you click on her literally nothing happens. No speech, nothing.

Update. It appears to not let people start the initial quest Unlisted Qualities but if you've completed that one already she will offer the chain quests like normal.

Version 30181205_0

**Comment by InoUno** [comment]
This issue should now be hotfixed. Can you try talking with Luto again to confirm that it works for you as well?

**Comment by Dibision** [comment]
Confirmed it is fixed.
