### ISSUE TITLE
Seiryu 

### ISSUE THREAD

**Issue by Rinomaru-eden** [EdenServer/community#3554]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Rinomaru-eden** [comment]
Today Jan 4 2021 our LS fought Seiryu.
Upon spawn it immediately used Dispelling wind, and it non-stopped spammed skill after skill. There was no melee break besides hundred fists. It was 100% necessary to bind/kite and melee was just un-doable.  Everyone did not recall "era appropriate"

**Comment by 59blargedy** [comment]
i (and others) did a lot of research for this. tping and regain is accurate. note the stun strategy here, may work for your melee efforts:
https://www.youtube.com/watch?v=jcOUy58MrvU
