### ISSUE TITLE
Ogre Bats and King Ranperre's Tomb

### ISSUE THREAD

**Issue by Malarion** [EdenServer/community#3555]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Ogre Bats in King Ranperre's Tomb aggroing from below ground, killing players outside tomb above ground.

**Comment by InoUno** [comment]
Resolved with October 4th, 2021 update.
