### ISSUE TITLE
KSNM orb sent me into another person's KSNM

### ISSUE THREAD

**Issue by Kaliria** [EdenServer/community#3556]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
Traded my clotho orb at same time as another person in a different party (or they were solo, I'm not sure), and I was warped into their BCNM and the rest of my party was locked out. By the time I got in, the person was done with their BCNM and had left, leaving me stuck in an empty BCNM by myself.

**Comment by 59blargedy** [comment]
resolved by another dev in jan 11th? 12th? mini-update
