### ISSUE TITLE
Summoner Avatar Diabolos - Blood Pacts take no mp

### ISSUE THREAD

**Issue by seehj** [EdenServer/community#3557]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver. 30181205_0

Pretty much title, diabolos blood pacts don't take mp upon use.

**Comment by 59blargedy** [comment]
resolved in January 18, 2021 update
