### ISSUE TITLE
WHM AF Body NM in Fei

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3558]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I helped someone with this NM earlier today and noticed there were potentially still a few smaller issues. The first issue is that I think the end of combat dialogue is printing once for EACH party member

![image](https://user-images.githubusercontent.com/13668758/103803471-9c82f080-501e-11eb-8e40-1dca98f70de1.png)

The only other issue (that I tested) was that I was able to land headbutt with 100% accuracy. I'm not sure if it has any stun resistance, or if this will come after the MACC patch, but the wiki makes it sound like it should have some sort of resistance. 

https://ffxiclopedia.fandom.com/wiki/Altedour_I_Tavnazia

"Resists Silence, Stun, and Sleep; can be Paralyzed, Slowed, Bound, Flashed, Addled, Blinded and Petrified."

I don't know much about DNC or its ability to land a stun but if you look at the testimonials there are DNC's saying they stacked up to level 5 stacks of steps and tried a flourish and still couldn't stun, and at least one of them mentioned being level 90, so I think its safe to say all of my head butts probably shouldn't land.

I didn't test silence or sleep at all but I get the same sort of vibe from the wiki page for those, sorry I forgot to cast!

version 30181205_0

**Comment by E5una** [comment]
(Sec, I accidentally hit submit give me a min to add details lmao)

**Comment by 59blargedy** [comment]
resolved in January 18, 2021 update
