### ISSUE TITLE
Pet rolls not correct

### ISSUE THREAD

**Issue by MasterRhyno** [EdenServer/community#3559]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Ver30181205_0
Drachen Roll gives pet acc but not pet ranged acc, this is both incorrect and out of era. Puppet Roll should be lv23 and give Pet Acc and Pet Ranged Acc, and Drachen Roll should be lv52 and give Pet Magic Attack and Pet Magic Acc. These 2 rolls were swapped around 2012. Puppet Roll description said Pet Acc but also gave Pet Ranged Acc, numbers were not confirmed in era but was assumed to be the same as Hunters Roll only for pets. Beast Roll should give Pet Attack and Pet Ranged Attack as well similar to Chaos Roll

**Comment by KnowOne134** [comment]
corrected in 8/7/2023 update
