### ISSUE TITLE
/sea commands

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#356]
/sea all linkshell posts a list of everybody who has a linkshell equipped on the server instead of for your own linkshell, making it effectively a /sea all command.

also, the linkshell list truncates. not a problem except for when you have to promote somebody / kick somebody from shell and their name starts with a Sanzio but you cant see passed the L's

**Comment by gweivyth** [comment]
> / kick somebody from shell and their name starts with a Sanzio but you cant see passed the L's

Yeah this part specifically makes this a game-breaking bug.  

Real talk though we could use some work on the search functions, they're pretty integral to the game.

**Comment by Fng098** [comment]
I believe this issue is resolved now?  I cant find which patch note, but the /search functions are way better now.

**Comment by KnowOne134** [comment]
Has been corrected
