### ISSUE TITLE
Desperate Blows working with 1handed weapons

### ISSUE THREAD

**Issue by aragan12** [EdenServer/community#3560]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

Right now, Desperate Blows is working with 1 handed weapons for dark knight. I tried taking video, but it wasn't working properly. I just tested with a dagger without last resort up and then used last resort and it is very clear that the haste from desperate blows was added. This should only work with 2 handed weapons.

ver 30181205_0

**Comment by 59blargedy** [comment]
Resolved in January 11, 2021 update.
