### ISSUE TITLE
Actinic Burst not generating correct emnity

### ISSUE THREAD

**Issue by Wonkstar** [EdenServer/community#3561]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Used the following resource for emnity values https://kanican.livejournal.com/20380.html
Steps to Repoduce:

1. Blu Casts Actinic Burst on mob (should generate 1020 VE)
2. RDM casts 2 Enfeebling magic spells that generate 320 VE each (silence, para, slow ect)
3. notice the aggro shifts to rdm

Expected Results

Even with the decay of VE in the time it takes to cast the 2 enfeebles, blu should likely still have the highest emnity

Version: 30181205_0

**Comment by Wonkstar** [comment]
Not a bug

**Comment by E5una** [comment]
Just to add context here in case anyone gets confused on this in the future, it was closed after it was realized that the RDM pulled with silence and thus had extra starting enmity from the pull.
