### ISSUE TITLE
Hand-to-hand damage doing around 50k/hit to Pots in Hu'Xzoi

### ISSUE THREAD

**Issue by Zidrux** [EdenServer/community#3562]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Hand-to-hand damage is doing around 50k dmg/hit on pot in Hu'Xzoi

**Comment by Herralaze** [comment]
Same issue for me ( 4k-17k dmg per punch)
I have been doing some tests, and this issue occurs **everytime** I switch from Destroyers to another H2H weapon, if I equip Destroyers back on then no problem. 
Also once I equipped Destroyers, the only way to use another H2H properly is to equip it and logout.

**Comment by 59blargedy** [comment]
resolved january 11, 2021 patch
