### ISSUE TITLE
The Weight of Your Limits (Not on log and no KI)

### ISSUE THREAD

**Issue by PrymalNights** [EdenServer/community#3563]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

I got my Axe of Trials from Iron Eater, finished my latent, and went to try and trade it to him and nothing happened. I checked my quest log and the quest isn't in there, and I don't have the key item he normally gives you in the beginning.

Version 30281205_0

**Comment by KnowOne134** [comment]
this is a DB update bug, need to file a bug report through gm team to get corrected
