### ISSUE TITLE
Frenzy sallet bug.

### ISSUE THREAD

**Issue by A-nomaly** [EdenServer/community#3566]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver. 30181205_0

Frenzy sallet not working as intended. I have been slept with Lullaby and Sleepga, equip helm and only get the 100hp poison a tick, but do not get woken up.

**Comment by rude-jerk** [comment]
Resolved in January 18, 2021 patch.
