### ISSUE TITLE
Additional Effect on Kabrakan's Axe doesn't work.

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#3567]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver. 30181205_0

![image](https://user-images.githubusercontent.com/65121606/104154583-4530a780-53b3-11eb-8830-b643842613fb.png)

I've used it for over 2 hours continuously now on different monsters, the slow has never proc'd once.

**Comment by KnowOne134** [comment]
corrected 2/1/2021 update
