### ISSUE TITLE
Mining Animation Plays Twice Since Update

### ISSUE THREAD

**Issue by Haljinn** [EdenServer/community#3568]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version: 30181205_0 

Since the update the mining animation now plays twice instead of once; I spoke with [GM] Penance about this to confirm it was a bug and not an intentional change. 

Reproduction step: Trade a pickaxe to a mining point.

**Comment by ConteAlmaviva** [comment]
The mining animation only plays (correctly?) once if you are moving when you start the mining action. https://gfycat.com/accuratelegalhoneycreeper

**Comment by DeuceFFXI** [comment]
Can also confirm that this is a bug that currently exists, and it is quite an annoying one.

**Comment by ConteAlmaviva** [comment]
@DeuceFFXI It appears it was fixed in the most recent maintenance (Today?)

**Comment by KnowOne134** [comment]
correct, fixed 1/18/2021
