### ISSUE TITLE
Phial of Volant Serum

### ISSUE THREAD

**Issue by Teaspoons** [EdenServer/community#3571]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Volant_Serum

i dont know if it can still be crafted, but the items do exist, if it can still be crafted its OOE from 2009, but all it does is put you in a bat costume in town so doesnt really hurt the game, but again it might still be able to be crafted so figured might as well report.
![image](https://user-images.githubusercontent.com/51509708/104241519-cf1c5700-542b-11eb-9d14-0c9e0ac05bed.png)

**Comment by rude-jerk** [comment]
Resolved in January 18, 2021 patch.
