### ISSUE TITLE
Primal Avatar tier 2 spells remove shadows completely

### ISSUE THREAD

**Issue by Camuel666** [EdenServer/community#3572]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
version 30181205_0
### Details
Each of the primal avatar fights they have casted a tier 2 spell such as blizzard 2 for shiva and it would completely remove shadows and still do dmg. Fighting ramuh he used a tier 4 and it was absorbed by 1 shadow like normal. unsure if this is intended or if it is a bug but each one that casts a tier 2 acts as if the spell is an aga 2 spell on single target.

**Comment by deepbreathingeden** [comment]
![bbc for juul](https://user-images.githubusercontent.com/53072734/109504515-0ebf0100-7ab5-11eb-98c0-2d4d21066b73.jpg)

**Comment by 59blargedy** [comment]
resolved with May 10, 2021 update. the moves actually ignore shadows per retail testing.
