### ISSUE TITLE
Devil Manta in Terrigan might be dropping Angel Skin?

### ISSUE THREAD

**Issue by andrewj3191** [EdenServer/community#3573]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I've noticed the same player(s) in Cape Terrigan consistently fishing up Devil Mantas in Cape Terrigan for the last ~7-8 days.  I know that fishing up devil manta in Terrigan is era accurate, but that only the ones in Kuftal drop Angel Skin.  I can't confirm that player is indeed fishing up for angel skins, but seems like that would be the only reason to be there for 7-8 straight days fishing up devil manta every 15-30 minutes.

Something to look into.

**Comment by Teaspoons** [comment]
Devil manta in era were not only fishable in cape terrigan, but also dropped angel skins
![image](https://user-images.githubusercontent.com/51509708/104340073-51595980-54c6-11eb-8483-0b2a41aa3225.png)

**Comment by andrewj3191** [comment]
Tea, technically the RMT patch to remove them from Terrigan was before the patch that we play in.  It's just Eden didn't implement this patch.
