### ISSUE TITLE
Assault: Lamia No. 13 ??? Items wrong

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3574]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Just received a ??? Polearm from Lamia No. 13. The appraisal guy won't even accept it. 
According to https://ffxiclopedia.fandom.com/wiki/Lamia_No.13_(Mission), polearm shouldn't be a drop from Lamia. 

/ver: 30181205_0
![Lamia](https://user-images.githubusercontent.com/55296729/104375295-220c1200-54f1-11eb-9395-9fe99bf0ab35.PNG)

**Comment by faivruit** [comment]
+ ??? Gloves

Ran the assault a couple times, only received ??? Polearms and also ??? Gloves - none of which are appraisable.

**Comment by 59blargedy** [comment]
resolved in January 18, 2021 update

**Comment by DeuceFFXI** [comment]
We attempted to hand the gloves in after today's patch and they still were not able to be appraised though.  Tried with three different characters and all had the same issue of being unable to hand them in.
