### ISSUE TITLE
Mercenary rank check NPC reports wrong text

### ISSUE THREAD

**Issue by faivruit** [EdenServer/community#3579]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
I had enough mercenary points (25) to get the rank up mission with Naja, however, the NPC Abquhbah reported the text for 19-24 points. It seems like the actual text will never appear:

"Hello, hello. You'll be hearing from President Naja any day now! (Poor thing, you'll wish you'd stayed a worthless pile of beaten pulp...)"

This happened for rank up from PFC to SP and a LS friend had the same issue from PSC to PFC.

/ver: 30181205_0

**Comment by bliven-was-taken** [comment]
Known issue.

**Comment by Mozzy4Ever** [comment]
> Known issue.

Was reported in https://github.com/EdenServer/community/issues/2863 but closed as it had been implemented. Guessing it's still a lil buggy though.

**Comment by bliven-was-taken** [comment]
Knowone said the text that says you are ready to rank up isn't implemented, even though the actual rank ups are.

**Comment by Mozzy4Ever** [comment]
Ah yea, I misread the other report. That one is regarding the actual rank up process as opposed to this one being about the text. Don't think it's been reported before.

**Comment by KnowOne134** [comment]
What's the correct message for 25+ points and I can look to adding it?

**Comment by bliven-was-taken** [comment]
I just edited my previous post with it, but I'll repost it here.

When you are able to rank up, you will be told:

    "Hello, hello. You'll be hearing from President Naja any day now! (Poor thing, you'll wish you'd stayed a worthless pile of beaten pulp...)"

**Comment by faivruit** [comment]
I believe it shows both until ranking up, as in the initial issue ticket above. At least that's what's shown on wiki.

**Comment by KnowOne134** [comment]
Will need retail data to find the correct csid + params, or textid

**Comment by KnowOne134** [comment]
seems the 1st 4 are cs's and last is just text ids
```
  </thing>
  <thing type="DialogTableEntry">
    <field name="index">9418</field>
    <field name="text">Hello, hello.
You'll be hearing from President Naja any day now!≺Prompt≻
</field>
  </thing>
  <thing type="DialogTableEntry">
    <field name="index">9419</field>
    <field name="text">(Poor thing, you'll wish you'd stayed a worthless pile of beaten pulp...)≺Prompt≻
</field>
  </thing>
```

**Comment by KnowOne134** [comment]
Corrected 1/18/2021
