### ISSUE TITLE
Death Earring Desynth

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#358]
Death Earring currently desynths a deathstone, and the first varified desynth of this is that it should desynth into a plat ingot. https://ffxiclopedia.fandom.com/wiki/Death_Earring?oldid=241091

**Comment by roriffxi** [comment]
https://github.com/EdenServer/community/issues/170

Are you certain you didn't HQ on your desynth attempt?

**Comment by Cheezcakee** [comment]
They desynth into plat ingots. I did get 1 deathstone back. on an HQ desynth though awhile ago.
