### ISSUE TITLE
Can engage monsters while slept

### ISSUE THREAD

**Issue by Orangemenace** [EdenServer/community#3581]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
You are able to engage mobs while you are slept. This is an issue because you can engage while slept then equip berserkers torque and wake up even if you weren't engaged to start with.

Ver 30181205_0

**Comment by rude-jerk** [comment]
Resolved on March 22, 2021 patch.
