### ISSUE TITLE
Mob pathing in Mount Zhayolm buggy

### ISSUE THREAD

**Issue by rockemsockemman** [EdenServer/community#3582]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details
Client Version: 30181205_0

Camping @ J-8 and pulling mobs causes them to path under the ground when going uphill. (Confirmed with fillmode to be going underground.)

**Comment by InoUno** [comment]
Should be resolved with March 1, 2021 patch.

**Comment by statuseffect** [comment]
This issue is still happening at the same camp.
