### ISSUE TITLE
Requiem Assault: Skeletons not assisting their wyverns

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#3583]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
You can pull the wyverns while the skeletons are facing them and the skeletons will not link / assist.

**Comment by KnowOne134** [comment]
corrected 2/1/2021 update
