### ISSUE TITLE
Guardian Crawler eats pops

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3585]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

The Crawler's Nest NM [Guardian Crawler](https://ffxiclopedia.fandom.com/wiki/Guardian_Crawler) that you spawn with a single Rolanberry will eat your Rolanberry even if it's impossible to spawn (ie: previous Guardian Crawler's body hasn't despawned yet)

**Comment by KnowOne134** [comment]
Corrected on 7/5/2024
