### ISSUE TITLE
Sanction incorrect duration after getting Superior Private

### ISSUE THREAD

**Issue by tigo9** [EdenServer/community#3586]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver 30181205_0

After achieving Superior Private and confirming able to purchase Superior Private items from sanction npc, sanction duration did not increase to 5h.

**Comment by DeuceFFXI** [comment]
I would like to add to this as well.  Currently the durations for Sanction at all ranks aside from Private Second Class are incorrect.

For Private First Class it should be 4 hours, and Superior Private as stated should last 5 hours.  Currently Superior Private lasts 3hr40min.

Here's a wiki article with a table for the Sanction durations of all ranks from Aug 2007 prior to the cutoff date: https://ffxiclopedia.fandom.com/wiki/Sanction?oldid=334140

and here's one from Oct 2007: https://ffxiclopedia.fandom.com/wiki/Sanction?oldid=368670

Both list the same durations for Sanction at each rank.

**Comment by KnowOne134** [comment]
Corrected 3/1/2021
