### ISSUE TITLE
Warhorse Hoofprint showing up on Widescan.

### ISSUE THREAD

**Issue by Garphilius** [EdenServer/community#3587]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Per wiki, the Hoofprint should not show up on Widescan. The ability to be able to see the Hoofprint on Widescan was added on 2015.

To reproduce this:

1) Switch to a job that can use Widescan. 
2) Go to the zone where the hoofprint is located.
3) Use Widescan.
4) See the Hoofprint on Widescan.

**Comment by InoUno** [comment]
Resolved with January 25th, 2021 update.
