### ISSUE TITLE
(Assault) ??? Gloves not appraising, also obtained from incorrect Assault

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#3588]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Lamia No. 13 (mission)

Did four of these assaults after last week's patch and from one of the chests we received "??? gloves"; however, this is not supposed to be in the loot table for this assault.  Rather it should be, "??? footwear", and the "??? gloves" should be obtainable from Azouph Isle's assault "Orichalcum Survey".

Regardless we attempted to hand in the ??? gloves that we received with multiple characters and none of them were able to receive a reward from Drahbah in Whitegate.

**Comment by 59blargedy** [comment]
this was resolved in today's patch and the ticket was closed https://github.com/EdenServer/community/issues/3574

**Comment by KnowOne134** [comment]
you will have to drop them, they are void items

**Comment by DeuceFFXI** [comment]
so we won't get a different ??? item in exchange?
