### ISSUE TITLE
Rusty cap synth

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#359]
https://ffxiclopedia.fandom.com/wiki/Rusty_Cap?oldid=161534

Rusty cap currently synths into plain cap, which is an rmt counter measure. 

In era it should synth into a padded cap

https://ffxiclopedia.fandom.com/wiki/Rusty_Pick?oldid=96363

Also the rusty pick should synth to a war pick

And rusty sword should synth into two-handed sword

**Comment by sukasaroth** [comment]
HQ of rusty cap is still padded cap, instead of Strong Cap.

**Comment by statuseffect** [comment]
Rusty picks no longer have a HQ result, either does padded cap, nor two-handed swords from rusty items. You still get a high-quality animation but the result is NQ.

**https://ffxiclopedia.fandom.com/wiki/Padded_Cap?oldid=59194**
**https://ffxiclopedia.fandom.com/wiki/War_Pick?oldid=96410**
**https://ffxiclopedia.fandom.com/wiki/Two-Handed_Sword?oldid=60416**

**Comment by KnowOne134** [comment]
has been corrected
