### ISSUE TITLE
Taking Auroral Updraft = Black screen

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#3590]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 301281205_0

Taking the Auroral Updrafts in Sea to get back to the entrance to Al'Taieu causes a black screen. Character can still move, target things, and navigate menus. Typical "fix" is to target the Auroral Updraft @ H-12 (entrance) and go back to Sealion's Den and then take the airship back to Sea once again.

**Comment by ElectronicMan83** [comment]
Had this happen a few time lately too. But I get the exact same bug with Sky warp from crag too.

**Comment by Slamm21** [comment]
also happens entering sacrarium sometimes

**Comment by InoUno** [comment]
Resolved in February 9th, 2021 mini-patch.
