### ISSUE TITLE
Dahak using wrong TP moves

### ISSUE THREAD

**Issue by GiichiHiro** [EdenServer/community#3591]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

Trying to learn Body Slam on Dahak in Mount Zhayolm, which proved difficult as the Dragons seem to be using the wrong set of TP moves, based on this chart: https://ffxiclopedia.fandom.com/wiki/Category:Dragons
![PoisonBreath](https://user-images.githubusercontent.com/66037286/105496615-1ad4c900-5c94-11eb-8d83-29c7ac5b79f5.PNG)
![ChaosBlade](https://user-images.githubusercontent.com/66037286/105496617-1ad4c900-5c94-11eb-8292-79de89ede7d9.PNG)
![HeavyStomp](https://user-images.githubusercontent.com/66037286/105496619-1b6d5f80-5c94-11eb-9f26-4041d16379f0.PNG)
![WindBreath](https://user-images.githubusercontent.com/66037286/105496620-1b6d5f80-5c94-11eb-86fc-20add1d92077.PNG)

**Comment by E5una** [comment]
Looking through DSP (I know this means nothing for Eden), I'm not seeing a lot of the ToAU alts listed in mob_skill_lists.sql. I see Eruca there, but I don't see entries for things like Dahak. Maybe it is categorized differently but I can't find it, this could be related/causing the issue. Sorry if its a false lead!

**Comment by 59blargedy** [comment]
resolved February 15, 2021 patch
