### ISSUE TITLE
Give a moogle a break glitched

### ISSUE THREAD

**Issue by xxxsnagxxx** [EdenServer/community#3592]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0
Character name Snag
Bronze bed placed in mog house
Quest give a moogle a break activated.
Power bow and beetle ring traded to moogle 
Moogle dialogue re going away to see relatives.
3 real life days have passed. No new dialogue from moogle. Quest still active. No mog safe increase. 
Bought items again and wont accept trade.

**Comment by rude-jerk** [comment]
Your quest can be completed after Sunday, January 24, 2021 10:00:00 AM GMT-05:00.

**Comment by Mozzy4Ever** [comment]
> Your quest can be completed after Sunday, January 24, 2021 10:00:00 AM GMT-05:00.

Based on backdated wiki, it shouldn't work like this.
It should be:
Place bed in Mog House
Wait until conquest tally
Get quest
Trade items
JP midnight wait (or 24 hour wait?)
Moogle comes back with upgraded safe

https://ffxiclopedia.fandom.com/wiki/Give_a_Moogle_a_Break?diff=prev&oldid=355085
