### ISSUE TITLE
SW Apollyon Mimic

### ISSUE THREAD

**Issue by ubrobbins** [EdenServer/community#3594]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproduceable steps. (No "as the title says" posts please. Provide reproduceable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
When my group went with Iron on Wednesday Night EST(1/20/2021) to do SW Apollyon the vortex on the 3rd floor for Mimics did not appear until the 5th or 6th Armoury Crate. According to https://classicffxi.fandom.com/wiki/SW_Apollyon the vortex is supposed to appear after killing the first Armoury Crate. 

https://www.twitch.tv/videos/881668953 about 2:57:00 is when we start going up to 3rd floor.

Version: 30181205_0

**Comment by Mozzy4Ever** [comment]
I believe when it says "Defeating one of the Mimics opens the vortex." it means that which Mimic pops the vortex is random. The testimonials on the ffxiclopedia page (https://ffxiclopedia.fandom.com/wiki/Talk:SW_Apollyon#3rd_Floor_Mimics) talk about some people getting lucky that it was the first mimic, and others unhappy that they had to kill all of them.

**Comment by 59blargedy** [comment]
yep, the tested chance for vortex is random on mimic kills - could be the first one, could be the last, so your experience is by design.
