### ISSUE TITLE
Count Bifrons

### ISSUE THREAD

**Issue by Sethious** [EdenServer/community#3595]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Count Bifrons does not seem to be popping, I don't know if he is coded, the other 3 NM's in the zone are there I spent 4 hours killing his placeholder and no pop i also looked at the AH and the scythe he drops has never been sold. He is of era, first came to XI in 2005.

Steps taken: Kill the Demon Knight @I-9 and wait for Respawn, then repeat.

Version: 30181205_0

**Comment by 59blargedy** [comment]
he exists, just bumped his chance up a little bit as only one place holder. resolved in February 22, 2021 update.
