### ISSUE TITLE
Assault : ??? Item drop rates

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#3597]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
I compiled all the data from wiki
https://docs.google.com/spreadsheets/d/1ymsL0B5BZ86jbtAhhuvkuuEORnQvs3LkAopJI2zFlls/edit?usp=sharing
In the source data you can see a very small minority where it doesn't reach 100% but some at over 100% which is obviously just minor typos with the data. I think it's clear that a ??? item should always drop, whereas right now on Eden fairly often it does not.

It also looks like the percentage chance of a box is likely meant to be 40%, with the remainder taking up the 60%
I think the other items are even, for example in a 4 item assault, the box is 40%, the other 3 are 20% each.

**Comment by KnowOne134** [comment]
Updated 3/8/2021
