### ISSUE TITLE
Ruinous Omen on diabolos dont agro surronding ennemies.

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3599]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

When using smn 2 hour with diabolos. Ruinous omen does a big aoe and do damage to these ennemies (that work as intendend).

If you do it the surronding mob wont agro but will get damaged. On other avatar AOE, all these mob agro and kill the Avatar quick then the hate drop. The end point is the same except if an ennemy is agressive it could link up to the party.

**Comment by 59blargedy** [comment]
resolved with the April 5, 2021 update
