### ISSUE TITLE
Digestable Rocks in the Excavation Assault

### ISSUE THREAD

**Issue by DrfistMD** [EdenServer/community#3602]
### Checklist

- [/] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [/] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

The rock walls in the Excavation Duty assault take damage from the Blue Magic Digest.  It's on average only 20 damage, so nothing crazy, but the walls are supposed to be immune to drain spells (Drain I from either our DRK or BLM appropriately did not do damage.)  I used Digest a handful of times so this was not a one off occurrence, the damage was consistently dealt.

**Comment by DrfistMD** [comment]
Decided to give this a try after the recent adjustments to magic accuracy and now Digest is hitting the rocks for 185.  I double checked other BLU spells, including those that use HP as part of their damage formula, but only Digest does abnormal damage.
![Untitled](https://user-images.githubusercontent.com/46073012/109911052-6016ee00-7c77-11eb-849b-cf2fadb2a8f1.png)

**Comment by DrfistMD** [comment]
Our DRK was also able to Drain II the rocks, which was definitely not possible before.
![Untitled2](https://user-images.githubusercontent.com/46073012/109911670-7c675a80-7c78-11eb-8f8c-561d3321cd5b.png)

**Comment by DrfistMD** [comment]
And to perhaps no surprise, Blood Drain also works on rocks.
![Untitled](https://user-images.githubusercontent.com/46073012/110576547-f727ee00-812e-11eb-9836-9dc62636d910.png)

**Comment by 59blargedy** [comment]
Resolved in June 7, 2021 update. drain is still effective, just not ridiculous.
