### ISSUE TITLE
Jaggedy Ear Jack placeholder not spawning

### ISSUE THREAD

**Issue by Goodfat22** [EdenServer/community#3603]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Goodfat22** [comment]
After killing the PH for JEJ 3 or 4 times, it discontinued spawning.  Still after more than 60 minutes, the placeholder forest hare or JEJ was still now spawned.

**Comment by KnowOne134** [comment]
know someone who was camping this religously few months back, got multiple kills so it is working atm
