### ISSUE TITLE
Spiny Spipi not spawing by classicffxi wiki rules

### ISSUE THREAD

**Issue by artemicon** [EdenServer/community#3604]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version: 30181205_0

Hello,

Using the following page, I killed the placeholder crawler mobs for Spiny Spipi for 120+ minutes and no spawn occurred.  If the rules for spawning on the page are correct, I have to believe there is an error server-side with the spawning mechanics.

https://classicffxi.fandom.com/wiki/Spiny_Spipi

_"Lottery spawn from the Crawlers around I-7 to J-7.
Killable by: Solo at level 15 As a normal melee job
Spawns every 45-90 minutes"_

I started killing crawlers near 6PM CST on 1/28/21 and got every spawn in the location uncontested during this time and finally finished after 8PM when I didn't get a spawn well after the 90 minute window.

It's minor, I understand, but thank you for looking into the issue.

**Comment by falzum** [comment]
The 45-90 minutes is a suggested average spawn time. Afaik lottery spawn nms don't have an upper limit.

After killing most NMs, there's a set amount of time before it can spawn again. Once the NM's window is open, it's a % chance to spawn off each place holder(Chance to spawn varies based on each nm).

**Comment by artemicon** [comment]
Ah, understood.  Thanks.  I'll just chalk it(lottery spawns) up to one of those things that isn't very well explained.

**Comment by KnowOne134** [comment]
Closing due to more understanding on the subject
