### ISSUE TITLE
BRD Virelai/Charm lasting too long

### ISSUE THREAD

**Issue by gilliam86** [EdenServer/community#3609]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

When I'm on BRD75/BST30 when I Virelai I can fully control (to the extent I know how to use the controls) the pet and it lasts for 20+ minutes.

I was also able to Charm, the BST ability, Raptors in Valley of Sorrows.

**Comment by perkuprightmeow** [comment]
Related to #3186 but with the addition that /BST30 shouldn't be full duration charming if it's relying on the BST's level. 

Also, the whole /BST giving commands to the Virelai'd mob, when before it was kind of a party trick.

**Comment by 59blargedy** [comment]
resolved by another dev in July 5th, 2024 patch
