### ISSUE TITLE
Dragvandil additional effect not proccing

### ISSUE THREAD

**Issue by Isabel-Eden** [EdenServer/community#3610]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

In 190 Ivory Lizard kills, that took about 7 hits each, Dragvandil's paralysis additional effect has not procced once. By this I mean it has not applied paralysis to the mob, and not that, once paralysis is applied, it prevented the mob from acting.

This was with a 60PLD/16THF (so all the mobs checked too weak to be worthwhile), client version 30181205_0, on Jan 31st, 2021.

**Comment by 59blargedy** [comment]
resolved in February 22, 2021 update.
