### ISSUE TITLE
Level Capped Zone XP

### ISSUE THREAD

**Issue by DrfistMD** [EdenServer/community#3613]
### Checklist

- [/ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [/ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Regarding the changes in level capped zone experience points today, these changes do not look to address that limit points were still gained normally inside of level capped zones.  The below BG forum post cites this behavior as of 2007.

https://www.bluegartr.com/threads/44018-Level-Capped-Zones-EXP

**Comment by rwaffle** [comment]
Video from May 2007 showing alliance of 11 killing a level 56 NM in Riverne B. Based on my math, an alliance of 11 (16.36% xp share per player) would get ~76 full xp/limit points from that mob and level difference. Video shows 75 limit points after kill. 

[https://www.youtube.com/watch?v=s_-Tx6BNmwA](url)

**Comment by DrfistMD** [comment]
Video from 2008 showing an Alliance of 8 vs Carmine Dobsonfly and still getting normal limit points.  Chain starts at 1m30s, first fly drops 69 limit points.  8 person alliance is 22.5% XP share, 4 level difference at that level range is 300 XP, and 300 * 0.225 = 67.5.  This and the above clearly show limit points were not subject to the same penalty as normal experience points.

https://www.youtube.com/watch?v=OhI9KuI2QFU

**Comment by InoUno** [comment]
Resolved with February 8th, 2021 patch.
