### ISSUE TITLE
Qiqirn Archaeologist ranged attack behavior incorrect / flee behavior missing

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#3615]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Qiqirn Archaeologists use ranged attacks too quickly. They also lack their mechanic of running away.

Eden:
https://www.youtube.com/watch?v=lOM_EthWQVE

Retail:
https://www.youtube.com/watch?v=DIOSmYEfyFI

ver 30181205_0

**Comment by KnowOne134** [comment]
Corrected 6/11/2022 update
