### ISSUE TITLE
Adventuring Fellow MACC

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#3616]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Adeventuring Fellow's appear to have a extremely high MACC.
Been killing Heraldic Imps with my Lvl55/56 Fellow and he landed every enfeeble.

**Comment by E5una** [comment]
Can confirm, my 55 NPC has enfeebled Hakutaku, thanks for reporting this.

**Comment by KnowOne134** [comment]
Wait until you see the mdb!

**Comment by panfunk** [comment]
> Wait until you see the mdb!

I noticed them to take less dmg from AoE magic than my 75 toons, but wanted to wait before reporting that to get more data. AoE damage from mobs seems wierd alot of times

**Comment by KnowOne134** [comment]
Corrected 2/8/2021
