### ISSUE TITLE
When Hell Freezes Over XP reward doesn't show in log

### ISSUE THREAD

**Issue by BindXI** [EdenServer/community#3617]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I know this is a tiny issue, just thought I'd put it on the radar before people start submitting that they didn't get reward.  I definitely did get the XP reward.  Reread log and I simply don't see my reward showing.

**Comment by InoUno** [comment]
Resolved with February 8th, 2021 patch.
