### ISSUE TITLE
Stuck on EXP chain #4

### ISSUE THREAD

**Issue by PrymalNights** [EdenServer/community#3618]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

I have been killing Huge Hornets in Gustaberg, and have been stuck on Chain #4 no matter how long I wait in between. As you can see from the screenshot below, and the times on the left.

Ver - 30181205_0

![image](https://user-images.githubusercontent.com/70297289/106529503-74f93980-649f-11eb-95ab-46d910b102cd.png)

**Comment by PrymalNights** [comment]
And I started at level 1, and it didn't go away.

![image](https://user-images.githubusercontent.com/70297289/106530021-5e9fad80-64a0-11eb-9450-391b50eda045.png)

**Comment by InoUno** [comment]
Thanks for the report!
Having looked into this, it turns out to be just a visual bug caused by the changes in today's patch. You are actually not gaining any chain bonus experience from this.

**Comment by InoUno** [comment]
Resolved with February 8th, 2021 patch.
