### ISSUE TITLE
Carbuncle's Healing Ruby does not activate

### ISSUE THREAD

**Issue by krausware** [EdenServer/community#3619]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
 
Character will do the animation, however carbuncle does not show his charging up the blood pact animation, and also the blood pact never goes off.

**Comment by krausware** [comment]
version 30181205_0

**Comment by InoUno** [comment]
Resolved with February 8th, 2021 patch.

**Comment by krausware** [comment]
Thank you!
