### ISSUE TITLE
BCNM Orb will crack if traded & canceled

### ISSUE THREAD

**Issue by EdenPenance** [EdenServer/community#3620]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

30181205_0

If you trade your BCNM/KSNM orb and get the menu open then close out of it, if someone else then trades their orb and enters, both orbs will be cracked.

**Comment by KnowOne134** [comment]
Corrected in an earlier update
