### ISSUE TITLE
Extra TE in Dynamis-Beaucedine

### ISSUE THREAD

**Issue by EdenPenance** [EdenServer/community#3621]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

30181205_0

Per http://www.dynamisbums.com/strategy/bcd.html, Eye 453 (NPCID 17326721)  is not supposed to be a time extension. On Eden, it currently gives +15 minutes resulting in a total 3 hours and 45 minutes in Dynamis - Beaucedine.

**Comment by Slamm21** [comment]
![image](https://user-images.githubusercontent.com/5552081/106722889-670dfa80-65fe-11eb-8ed9-fd6a346d6e3e.png)
easier to read map

**Comment by ThrisStraizo** [comment]
148 AND 147 don't both give 15 min extensions do they?  I've only noticed 147.

**Comment by EdenPenance** [comment]
On Slamm's picture both 147 and 148 do, yes.

**Comment by Falaras** [comment]
I don't think 147 exists on Eden, only 148 which gives the TE instead.

**Comment by EdenPenance** [comment]
They both exist. 147 pops by killing 138/139/140. I verified via test server that they both give TE.

**Comment by Falaras** [comment]
Oh wow yeah just tested it your right.

**Comment by 59blargedy** [comment]
resolved with May 10, 2021 update
