### ISSUE TITLE
Consumable with error

### ISSUE THREAD

**Issue by Xellz** [EdenServer/community#3622]
### Checklist
 
Grilled Hare NQ item has attack +30% and caps at +15 attack when at 50 base attack
Grilled Black Hare item states  states attack +20% and caps at +30 attack, which would be at 150 attack.
I believe this is a mistake, since most HQ recipes for food have same % of added attack albeit with a slightly higher cap.
Cap that would make sense is 30% attack and caps at +20 which would involve a mixup in both the cap and % added.

I believe this is a mistake, since most HQ recipes for food have same % of added attack albeit with a slightly higher cap.
 
Used Grilled black hare item on character with 48 attack which resulted in +9 attack and 1 attack extra from the STR added.

version 30181205_0

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by 59blargedy** [comment]
it may be a mistake, but it's an SE mistake that is uncorrected to this day, so going to leave as is. it should last an hour longer, so if it is not can comment here.
https://www.bg-wiki.com/ffxi/Grilled_Black_Hare
https://translate.google.com/translate?hl=en&sl=ja&u=http://wiki.ffo.jp/html/2571.html&prev=search&pto=aue
![image](https://user-images.githubusercontent.com/52636208/114458761-9cf6ce80-9bad-11eb-8349-5b3cd8f7dd9a.png)
