### ISSUE TITLE
Chigoe Burn EXP

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#3623]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

This problem is inadvertently affected by the PL patch. Is there a solution to prevent exp being dirtied by this method?

A level 75 character holds and melees a Wild Karakul to spawn Chigoes for a level ~50 sync party to gain exp from.

https://www.youtube.com/watch?v=3ga826OwHWc

From what I can tell, in CL and other areas, the problem was a level 75 player essentially tanking a group of monsters that a group would leech to aga burn. 

In a Chigoe burn, the level 75 player doesn't tank the targets that are being killed. 

ver 30181205_0

**Comment by dowzer** [comment]
EXP is dirtied no matter how fast the chigoes are claimed.

**Comment by KnowOne134** [comment]
this is the counter measure the team has added to not hold mobs for others to level on, this also includes hold mobs for pet spawning such as goblins that spawn pets.
