### ISSUE TITLE
Vertical Cleave does not have proper hidden attack modifier

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3624]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Just creating a ticket so the dev team has something to track it rather than it being tribal knowledge that its a missing piece of BLU. Vertical Cleave has some kind of a hidden attack modifier but the details are unknown. 

You can find some vague hints at damage in guides like this, but I think we'd need some screenshots/videos and more info about gear to be able to make headway on this.

https://ffxiclopedia.fandom.com/wiki/Blue_Mage:_Sky/God_Spells_And_Subs

"Other Alternatives is to Set Vertical Cleave + STR Spell and gears + food like Coeurl Sub -> Chain Affinity + SATA (min 100% TP) : Vertical Cleave can hit for 1.5K damages on Byakko - Seiryu and Suzaku. It's great for gives a lot of Enmity on your Tank."

**Comment by GiichiHiro** [comment]
Some other anecdotal evidence.  Can assume BiS, but should be able to duplicate it at least:

https://www.ffxiah.com/forum/topic/11253/lv-80-blue-mage/#656201
https://www.ffxiah.com/forum/topic/6749/blue-gear-advice/2/#350328

From what I've read, people stack 100% into STR, including other Blu spells, to get those numbers.

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
