### ISSUE TITLE
Automaton WS Slapstick seems to be missing Reverberation tag

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3625]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Per the wiki, Slapstick should have Reverberation / Impaction SC properties and Slapstick -> Combo should be a valid skillchain:

![image](https://user-images.githubusercontent.com/13668758/106955778-b2f69780-6703-11eb-9fec-9d8715642da5.png)

![image](https://user-images.githubusercontent.com/13668758/106955735-a70ad580-6703-11eb-895e-8f1584a96a75.png)

In testing on the test server, Slapstick -> Combo doesn't SC.

Best guess is that it is missing the Reverberation SC tag that it would need for the SC to work.

version 30181205_0

**Comment by Birdy-gif** [comment]
Thanks for posting this for me :D

**Comment by 59blargedy** [comment]
resolved in february 8, 2021 patch
