### ISSUE TITLE
"Over the Hills and Far Away" Diary Issues.

### ISSUE THREAD

**Issue by Zalnoch** [EdenServer/community#3627]
### Checklist

Diary was not working for pages 3-4.
Was able to to get pages 3 and 4 to appear with the following.

Squires Test II - Completed
Medicine Woman - Completed
To Cure a Cold - Flagged.

Ver. 30181205_0

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
