### ISSUE TITLE
Jagil in Purgonorgo Isle are aggressive when they should not be

### ISSUE THREAD

**Issue by prwilson42** [EdenServer/community#3628]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Jagil in Purgonorgo  are set to aggressive when they should not be. [Wiki ](https://ffxiclopedia.fandom.com/wiki/Bibiki_Bay_-_Purgonorgo_Isle) and [BG Wiki](https://www.bg-wiki.com/ffxi/Jagil) indicate they are not aggressive and do not link.

I tested this on retail to verify.  They indeed are not aggressive and do not link.  

Reproducible steps:
.5 Make sure you are level 40 or under.
1. Enjoy a nice ride on the ferry to Purgonorgo Isle. I suggest at sunset.
2. Run to the western beach where Serra pops.
3. Talk a walk amongst the fishes there. Careful of the misplaced Viscous Clots as they do aggro!
4. Die from many angry fish taking there revenge on you for all the sushi you ate.

Version: 30181205)0

**Comment by 59blargedy** [comment]
resolved in February 22, 2021 update.
