### ISSUE TITLE
Viscous Clots in Purgonorgo Isle are not correctly placed.

### ISSUE THREAD

**Issue by prwilson42** [EdenServer/community#3629]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

There is a mechanic to the respawning of the two to three Viscous Clots on the island. They should not appear together on the same beach. There is four possible spawn locations, one on each beach with only two to three up at a time and one spawn is shared with a Kraken on the south beach. When the kraken is up a clot will also spawn on the same beach.
Reference [wiki page](https://ffxiclopedia.fandom.com/wiki/Viscous_Clot)

Reproducible steps:

1. Enjoy a nice ride on the ferry to Purgonorgo Isle. I suggest at sunset.
2. I noticed two clots on the western beach where Serra pops.
3. Take a look around at other beaches.
4. Kill the kraken(if up) then the clots and wait 5 mins for repops.

Version: 30181205)0

**Comment by 59blargedy** [comment]
resolved in March 5, 2023 update
