### ISSUE TITLE
Keen angler's senses 

### ISSUE THREAD

**Issue by Ofock707** [EdenServer/community#3630]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0

Fishing in Sauromugue Champaign using Comp. Rod with Minnow with Angler/fisherman gear

Sometimes while fishing Keen angler's senses tell you that this is the pull of a Cone Calamary, after the mini game I get "You lost your catch whatever caught the hook was too small to catch with this rod". I'm targeting Bluetail/Cone Calamary with this set up and I shouldn't have any problems fishing them up but 6 out of 10 casts come back with fish is too small for this rod. Not sure if its the default message or if its a bug.
![FFXI](https://user-images.githubusercontent.com/78657737/107125631-f2d29180-685f-11eb-8dc1-2a0f2372d446.PNG)
![FFXI_1](https://user-images.githubusercontent.com/78657737/107125668-26152080-6860-11eb-9bcd-17cc75f5cd76.PNG)

**Comment by bliven-was-taken** [comment]
https://www.great-blue.jp/?fid=030&lng=en

![image](https://user-images.githubusercontent.com/61694447/107125917-8dd86500-687a-11eb-86ff-0002a637e737.png)

**Comment by Ofock707** [comment]
thank you for your time, im a big dummy.
