### ISSUE TITLE
Byakko Divine Log drop rate

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#3631]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Divine logs seem ridiculously rare on this server. Both ffxiclopedia and ffxidb have them listed at around 20% from Byakko. I do not believe this is currently the rate, but obviously I can't see the code. 

http://www.ffxidb.com/zones/130/byakko

Both the TH0 and TH2 numbers are listed above 20%. 

https://ffxiclopedia.fandom.com/wiki/Byakko

This shows 20% approximately as well.

I believe all the data suggests that it should be listed as a 4 at least, and I could see an argument for 5.

**Comment by 59blargedy** [comment]
it looks like it's set appropriately from byakko. always good to check.
