### ISSUE TITLE
Kraken on Purgonorgo Isle Con as Impossible to Gauge

### ISSUE THREAD

**Issue by prwilson42** [EdenServer/community#3632]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Kraken on Purgonorgo con as impossible to gauge.  Their level range should be 37-40 as a normal monster.  [Wiki](https://ffxiclopedia.fandom.com/wiki/Bibiki_Bay_-_Purgonorgo_Isle)and [BG Wiki](https://www.bg-wiki.com/ffxi/Bibiki_Bay_-_Purgonorgo_Isle) list as a normal monster.  I checked retail and they do con level 37-40 there as normal monsters.

Reproducible steps:

1. Enjoy a nice ride on the ferry to Purgonorgo Isle. I suggest at sunset. Maybe with a friend this time ;)
2. Run to a beach where a Kraken spawns and check it. They all con impossible to gauge.

Version: 30181205)0

**Comment by 59blargedy** [comment]
resolved in march 8, 2021 update
