### ISSUE TITLE
Monsters on the Manaclipper to Purgonorgo Isle aggro that didn't originally

### ISSUE THREAD

**Issue by panicstevenson** [EdenServer/community#3633]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I was aboard the Manaclipper and was aggro'd by a too weak to be worthwhile Cutter and an easy prey Uragnite. I was `/sit`ting near the NPC and was surprised that the crab came up to me and started attacking me. The monster families generally are non-aggressive, but I double checked on FFXIclopedia, both current and era entries, and nothing notes these monsters as being aggressive on the boat: [Manaclipper](https://ffxiclopedia.fandom.com/wiki/Manaclipper?oldid=188666). I'm aware that resting will aggro something that generally checks too weak to be worthwhile, but I don't think `/sit` has the same effect, or, at the very least, shouldn't aggro anything that doesn't normally aggro. For noting the level, I was level 45.

### Reproduction Steps

1. Board the Manaclipper
2. `/sit` (necessary?)
3. Get aggro

### Game Version

30181205_0

**Comment by 59blargedy** [comment]
/sit does act like /heal in terms of aggressive mobs aggroing you, but just validated on retail that cutter and and uragnites on the manaclipper should not be aggressive, since wiki had no information either way.

**Comment by 59blargedy** [comment]
resolved in april 26, 2021 update
