### ISSUE TITLE
Kupipi wrong text San d'Oria 2-3

### ISSUE THREAD

**Issue by faivruit** [EdenServer/community#3634]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Kupipi greets me as an adventurer from Bastok, even though I am San d'Orian and on San d'Oria's mission "Journey Abroad"

![grafik](https://user-images.githubusercontent.com/77455848/107157048-358c8a80-6982-11eb-813b-3d24a901beeb.png)

To reproduce: Talk to Kupipi while being on the appropriate session of "Journey Abroad" as a San d'Orian citizen (Windy path first).

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in April 12, 2021 update.
