### ISSUE TITLE
Manaclippers have the incorrect fishing pools

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#3635]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

The manaclippers from Bibiki Bay/Purgo/Dhalmel Rock/Maliyakaleya isle have the incorrect fishing pools. As such, the fish you catch on each boat ride are incorrect. I found this by fishing on the manaclipper the past couple of days and only catching fish from the "Purgo Isle to Bibiki Bay" pool (e.g., bibikibo, bladefish, gugrusaurus) on each manaclipper. These fish should not be catchable in the Maliyakaleyha pool. Having the wrong fishing pools means that certain fish like the titanic sawfish are not catchable. The correct pools for each boat ride are posted on the wikis:

https://classicffxi.fandom.com/wiki/Manaclipper
https://ffxiclopedia.fandom.com/wiki/Manaclipper

To replicate, ride the manaclipper for 2 days and fish for things with variable baits/lures.

**Comment by deepbreathingeden** [comment]
![man of culture](https://user-images.githubusercontent.com/53072734/109504087-8f313200-7ab4-11eb-8a22-6a0c7ca64e27.PNG)

**Comment by 59blargedy** [comment]
resolved in June 2022 update
