### ISSUE TITLE
wrong map received from imperial overseer

### ISSUE THREAD

**Issue by Rochwin** [EdenServer/community#3636]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
on 2/6/2021 Eastern time at 23:46:21 got Vunkerl Inlet Map insted of Map of Halvung

**Comment by deepbreathingeden** [comment]
![bbc for juul](https://user-images.githubusercontent.com/53072734/109504060-850f3380-7ab4-11eb-9661-a4d09cd4c862.jpg)

**Comment by 59blargedy** [comment]
resolved by another dev in July 8, 2022 update
