### ISSUE TITLE
Player spawn point on Manaclippers is incorrect

### ISSUE THREAD

**Issue by prwilson42** [EdenServer/community#3637]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

When the Manaclipper leaves the dock and when you zone into the sailing portion of the map you spawn in the middle of the Manaclipper.  In retail you spawn on one of the egress platforms on the side of the Manaclipper.  This is, I assume, to avoid aggro from monsters that commonly appear on the boat during its trip.

Reproducible steps:

1. Enjoy a nice sightseeing ride or go to Purgonorgo Isle on the Manaclipper. I suggest at sunset. Take your fishing rod!
2. After the Manaclipper leaves look at where you spawn.

Version: 30181205_0

**Comment by deepbreathingeden** [comment]
![1614121272006](https://user-images.githubusercontent.com/53072734/109504042-7d4f8f00-7ab4-11eb-92ce-5c1e3a687184.jpg)

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
