### ISSUE TITLE
Fradubio doesn't seem to be a 21-24 hour lottery spawn from the Fraelissa and it also doesn't spawn Duessa

### ISSUE THREAD

**Issue by SleazyFFXI** [EdenServer/community#3638]
### Checklist

- [Yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [30181205_0 ] I have provided my client version in the details. (type /ver into your game window)

### Details
I killed it and came back 21 hours later and stayed for 4-5 hours killing Fraelissa and it never spawned,   no one else was in zone and the Fraelissa spawned every hour ish like its supposed to.

**Comment by deepbreathingeden** [comment]
![Uploading 1612766460812.jpg…]()

**Comment by deepbreathingeden** [comment]
![1612766460812](https://user-images.githubusercontent.com/53072734/109504044-7fb1e900-7ab4-11eb-8da9-5d1d206eb7b8.jpg)

**Comment by 59blargedy** [comment]
resolved in the March 29, 2021 update
