### ISSUE TITLE
The Missing Piece quest missing dialogue

### ISSUE THREAD

**Issue by JRoKK78** [EdenServer/community#3640]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

The quest "The Missing Piece" (Teleport-Altep) does not want to complete.  I received the quest, proceeded through getting all key items.  When I got to the end NPC he stays on the line telling me to come back later.  I zoned in and out several times, over several game days(real life hours) and the dialogue does not change/ scroll not received.  I went back to the start NPC in Rabao and he keeps talking like i never received the first key item.  The quest is not flagged or completed in quest list either. ver 30181205_0

**Comment by 59blargedy** [comment]
please try after jp midnight, though it does sound like some dialogue is missing for in between states even if the era wait time resolves your issue.

**Comment by JRoKK78** [comment]
Waiting till JP midnight did the trick.  Just finished the quest and got the scroll.  Thank you!

**Comment by deepbreathingeden** [comment]
![1612766460812](https://user-images.githubusercontent.com/53072734/109504017-7294fa00-7ab4-11eb-96c8-1e1c7fb11ca8.jpg)

**Comment by 59blargedy** [comment]
resolved in April 12, 2021 update.
