### ISSUE TITLE
Sharpening The sowrd

### ISSUE THREAD

**Issue by tray15** [EdenServer/community#3641]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0
Sharpening the Sword quest did not flag, instead the next quest for PLD AF, A Boy's Dream flagged without prior completion of the quest for the sword. I am level51 and did not attempt to start AF until now.

**Comment by KnowOne134** [comment]
dupelicate of https://github.com/EdenServer/community/issues/3658
