### ISSUE TITLE
Shirataki 

### ISSUE THREAD

**Issue by Fiasco78** [EdenServer/community#3642]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
Shirataki should be sold by the npc Amalasanda in Lower Jeuno. This is a necessary ingredient for 2/3 of the stewpot recipes.

**Comment by 59blargedy** [comment]
resolved February 15, 2021 patch
