### ISSUE TITLE
Gungnir aftermath wearing when it shouldn't be

### ISSUE THREAD

**Issue by shaddix83** [EdenServer/community#3644]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

Aftermath for Gungnir wears when swapping to TP set. There's no change in weapon/grip/ammo. I remove each piece of gear manually with aftermath on and it stays on, but the macro makes it wear, as shown in the clip. The second clip shows me pressing the ws macro again with aftermath. There's NO gear change at all as I am already wearing the gear but aftermath still wears off. All of my drg item sets have the "Keep same piece" on the weapon, grip, ammo. 

https://youtu.be/gV2VUjIeVvU

https://youtu.be/rnfRQSBNaPk

**Comment by deepbreathingeden** [comment]
![1614121272006](https://user-images.githubusercontent.com/53072734/109503956-5b560c80-7ab4-11eb-9d18-df822dd94c20.jpg)

**Comment by shaddix83** [comment]
This might be macro related as I may the only person who doesn't use ashita cast but I completed mandau and my aftermath wears off in the same way. I press a macro to swap to TP set and the macro does not change any weapons. The TP does not hit 0 as shown in the video with Gungnir. But the aftermath still wears off. Mandau's aftermath wears the same way. I am assuming most, if not all, relic users use ashitacast and idk if this is why they aren't experiencing this issue I Am but both relic aftermaths wear when using a gearswap macro, even though the weapons remain the same

**Comment by falzum** [comment]
How strange. I don't use ashitacast either with my apoc but I don't have this issue. I'm stepping out now with the wife but I can help you with this later/tomorrow and see if we can get to the bottom of it.

**Comment by shaddix83** [comment]
Instrument change causes loss of aftermath but not TP, so this range slot change caused the aftermath to wear. My drg set for some reason had a "remove item" on range slot even though I have nothing in that slot. But that removing nothing on the range slot was causing AM to wear whilst keeping tp. The change of range slot is the cause of aftermath wear
