### ISSUE TITLE
Evoker's roll gives wrong mp values to party members

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3645]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Disregard: Apparently this is intended behavior when you're a low level cor buffing a high level target. I wasn't aware but the cor channel has taught me their ways.

https://classicffxi.fandom.com/wiki/Evoker%27s_Roll

With no smn in the party evokers roll is giving the correct values to me on cor/whm, but it is giving my alt 1 less mp per tick for all roll values, flooring at 1mp/tick. This is with both characters naked, and without and refresh bonuses from outside sources. 

A quick chart to show what I mean: This chart didn't format as nicely when I submitted the bug, sorry.

Roll | COR mp/tick | ALT mp/tick
1        1                        1
2        1                        1
3        1                        1
4        1                        1
5        3                        2
6        2                        1
7        2                        1
8        2                        1
9        1                        1
10      3                        2
11      4                        3

/ver 30181205_0

**Comment by 59blargedy** [comment]
appears to not be an issue
