### ISSUE TITLE
Hellion NM 

### ISSUE THREAD

**Issue by Howland11** [EdenServer/community#3646]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
The NM Hellion in labyrinth of onzozo is supposed to have an additional effect darkness damage during its melee hits but this effect never occurred a single time in the 9 minutes I spent soloing it with a torama as beastmaster

**Comment by 59blargedy** [comment]
resolved in February 22, 2021 update.
