### ISSUE TITLE
Woodworking skillups

### ISSUE THREAD

**Issue by Xellz** [EdenServer/community#3647]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
currently Cooking lvl 58 and woodworking lvl 8, crafting sausages for skillups.

sausages are listed as 62 cooking with a subjob of 7 WW so skillups on WW are unexpected or the recipe is wrong.

cheers.

![image](https://user-images.githubusercontent.com/59521173/107548512-5fb59680-6b94-11eb-9d74-e9f2df098920.png)

![image](https://user-images.githubusercontent.com/59521173/107548873-c76be180-6b94-11eb-8a1a-264a69645849.png)
photo taken after i hit 59 but WW is the point in this pic

**Comment by Mozzy4Ever** [comment]
Sausages are listed as having a WW subsynth of 9 on both https://www.ffxiah.com/item/4578/sausage and https://www.bg-wiki.com/ffxi/Sausage

**Comment by Spiffly** [comment]
I've update our wiki to show level 9 as the cap and with it, hopefully bringing an end to sausage-gate.
