### ISSUE TITLE
Voluptuous Vivian should be immune to Sleep

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#3650]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

Voluptuous Vivian can currently be slept, according to ffxiclopedia it's only resistant but it should be immune.

A few quotes from a Bluegartr thread: https://www.bluegartr.com/threads/61831-Voluptuous-Vivian-RDM-NIN

"I've never even tried to sleep it since i've seen blm's ES-Sleep2 resist."

"2. Paralyze will not stick, but Slow II is very easy (and essential) to land, even with full MND gear which is also important. Obviously you can't Sleep her,"

Retail video: https://www.youtube.com/watch?v=rnrvGnwbSdQ

**Comment by 59blargedy** [comment]
resolved in February 22, 2021 update.
