### ISSUE TITLE
Bard harps not extending song range

### ISSUE THREAD

**Issue by failffxi** [EdenServer/community#3652]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)

- [x] I have provided reproducible steps. (No "as the title says" posts, please. Provide reproducible steps even if it seems like a waste of time.)

- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

**Issue:**
Bard harps are supposed to have enhanced range compared to flutes. 

Based on the Bards singing + string skills, harps should have anywhere from 10.0 - 20.0 range on their effects (Each tier song has a singing+string skill required to reach max range, lower-tier songs require lower caps) however, harps do not appear to be enhancing the range of any songs at all.

**Reproducible steps:**
Open the in-game config > Misc 3 > Turn "Area Display" On
When preparing to cast a song, you should see the range of a potential song with a blue circle, players that should be affected by the song within the area will have their names displayed in a larger text size. With a flue on, you can see the range is capped at 10.0, and with harps, the range is shown to be increased, but casting a song with players inside the increased range does not give them the song effects if they are between 10.1 - 20.0.

Version 30181205_0

**Comment by deepbreathingeden** [comment]
![Uploading 1609266619516.jpg…]()

**Comment by deepbreathingeden** [comment]
![1612766398802](https://user-images.githubusercontent.com/53072734/109503932-52fdd180-7ab4-11eb-9371-4074aa0e945e.jpg)

**Comment by 59blargedy** [comment]
i was not able to replicate this. using a harp and every buff song possible, my range was appropriately extended based on my string skill. im wondering if there was a particular harp not properly coded that may have caused the issue for you, or something had issues with casting range back in february that has since been resolved.
