### ISSUE TITLE
Bastok "Valentione's Day" event Moogle trade isnt working

### ISSUE THREAD

**Issue by mcdougles84** [EdenServer/community#3653]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The "Valentione's Day" event Moogles in both Bastok Mines and Bastok Markets will not accept the 2 chocolate halves for trade. I have all 8 chocolates (4 right parts, and 4 left parts) and my alt (opposite gender) has the other 8, both characters have the appropriate items needed (traded the 4 part from M for F) and I have tried all combination on both characters and the Moogles still wont respond 

ver 30181205_0

**Comment by 59blargedy** [comment]
you have to trade your right parts to your alt, THEN trade the left and right parts to the moogle.

**Comment by mcdougles84** [comment]
yes, I have already done all that

**Comment by perkuprightmeow** [comment]
Mind filing a GM ticket under help desk so we can check your variables? 

Help desk > Help desk > I'd like to report... > Yes I have > Yes, this is...

**Comment by mcdougles84** [comment]
thank you perkuprightmeow, ticket summited,

**Comment by xizeta** [comment]
Fixed on live. Thank you for your report!
