### ISSUE TITLE
Cursed Chests in Golden Salvage (50 Cap) often spawn as lvl 73-75, others ~50.

### ISSUE THREAD

**Issue by Lehawah** [EdenServer/community#3654]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
1. Aquire the Ilrusi Atoll Assault order.
2. Enter Golden Salvage assault with a level cap of 50.
3. Click the Chests.
4. At least 50% of the cursed chests will be level 73/74/75, others 49 or similar. (basically 2 shotting players. @300+ dmg on geared mages.) Asked around and it was suggested to me, ithat ts probably unintended - makes even SMN strategy very painful and sometimes just no chance of escape.
*Edit: Client Version: 30181205_0

**Comment by deepbreathingeden** [comment]
![Uploading dfgsdfg.png…]()

**Comment by deepbreathingeden** [comment]
![Uploading pale-blonde-blue-eyes-pale-teen-petite-blonde-black-jason-brown-with-small-tits.jpg…]()

**Comment by deepbreathingeden** [comment]
![1614324985261](https://user-images.githubusercontent.com/53072734/109504004-6b6dec00-7ab4-11eb-8e5e-076a5b003e24.jpg)
![1788268](https://user-images.githubusercontent.com/53072734/109504104-97896d00-7ab4-11eb-821a-ca4b377729a3.jpg)

**Comment by 59blargedy** [comment]
going to have to revisit this and try another method

**Comment by KnowOne134** [comment]
resolved in October 4, 2021 update
