### ISSUE TITLE
RSE Ammo NMs dropping wrong race.

### ISSUE THREAD

**Issue by Kakaijimaseraph** [EdenServer/community#3656]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Have killed Aroma NMs in different zones during Taru RSE week and received the wrong race's items 3 different times. Aroma Fly gave me Mithra Satchet and Aroma Crawler has given me Galka and Hume items.

**Comment by deepbreathingeden** [comment]
![dfgsdfg](https://user-images.githubusercontent.com/53072734/109504181-b0921e00-7ab4-11eb-9e84-ef667b394668.png)

**Comment by perkuprightmeow** [comment]
Adding to this -- it seems like it drops whatever race was active whenever the ??? spawns, rather than when the monster is popped/killed.

**Comment by rude-jerk** [comment]
Resolved in October 4, 2021 update
