### ISSUE TITLE
PLD AF1 Quest Skipped

### ISSUE THREAD

**Issue by WongEden** [EdenServer/community#3658]
### Checklist

Hello,

I went to accept PLD AF1 quest but somehow the quest skipped to PLD AF2. According to guides online, this should not have been possible. This is a problem because subsequent quests require AF1 to be completed before attempting coffers, AF3, etc. I am unaware how this issue occurred but my only guess is that I accepted it when I was lvl 50+. 

Version 30181205_0

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

**Comment by KnowOne134** [comment]
Corrected 3/15/2021
