### ISSUE TITLE
Couldn't get new Outpost supplies

### ISSUE THREAD

**Issue by Soleece** [EdenServer/community#3659]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

client version: 30181205_0

This week my supplies didn't get thrown out when I talked to a gate guard. I then try an outpost guard as well. When that didn't work I contact a GM. 

Steps: My thoughts. 
I do believe that that there were contributing factors that played into this bug. Last week, the server was down during the conquest tally. When it came back up, Windurst had the same region, so I never thought to get new supplies. I believe those circumstances could have contributed to the bug. Either the fact that we had the same region for two weeks or that the server went down and that when it came back up we had the same region. 

My character's name is Soleece, and I'm from Windurst. Hope that helps.

**Comment by rude-jerk** [comment]
This was because the server was down and the conquest update was forced.
