### ISSUE TITLE
CoP Ring Re-acquisition after waiting 28 real life days. 

### ISSUE THREAD

**Issue by MrTheroux** [EdenServer/community#3660]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Client Ver. 30181205_0

I originally swapped out my CoP Ring successfully on (or a few days before) 12/10/20 on Eden. I then discarded my CoP ring on Fri. Jan 8th (01/08/21) and clicked on the Marble Bridge door that same day to activate the " 28 real life day" waiting period. The wait period passed and I've been checking the door daily to try and trigger the cutscene with no luck.

I submitted a GM ticket on 02/20/21 and spoke with [GM]Penance. Per the conversation with him, the math done for checking if you've waited 28 days is based on the previous ring acquisition. So it's doing like 51(today's Julian date) - 346 (when I got my previous ring) and if it's greater than, or equal to 28, it will give the correct prompt. The equation won't ever be true because there's not 28 days after 346, only 19/20 (leap years) so the year flip messed it up.

Thank you for the fast reply Penance.

Character name: Shiru // San d'Oria Rank 10.  Please let me know if you need any more information.

**Comment by 59blargedy** [comment]
this issue was resolved in a late 2022 update
