### ISSUE TITLE
Electrum Ingots are synthable

### ISSUE THREAD

**Issue by EdenPenance** [EdenServer/community#3661]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

Electrum Ingots are an OOE item that you can currently synth on Eden. Their listing on the AH was removed, but not the synth itself. https://ffxiclopedia.fandom.com/wiki/Electrum_Ingot
All of their uses are OOE as well.

**Comment by deepbreathingeden** [comment]
![Uploading 1612766460812.jpg…]()

**Comment by deepbreathingeden** [comment]
![Uploading bbc test.PNG…]()

**Comment by 59blargedy** [comment]
resolved in march 8, 2021 update
