### ISSUE TITLE
Synth for Sanjaku-Tenugui exists

### ISSUE THREAD

**Issue by GiichiHiro** [EdenServer/community#3663]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_5

Was able to perform the synth for Sanjaku-tenugui, which is the tool necessary for Monomi.  Neither of these are era, so the synth shouldn't exist.

**Comment by deepbreathingeden** [comment]
![Uploading 1614121272006.jpg…]()

**Comment by deepbreathingeden** [comment]
![Uploading 1612766336404.jpg…]()

**Comment by 59blargedy** [comment]
resolved in march 8, 2021 update
