### ISSUE TITLE
Outpost Teleportation Fees are incorrect

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#3664]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Please refer to the table found on this page of the June 6th, 2007 version update.

http://www.playonline.com/pcd/update/ff11us/20070606TsVPr1/detail.html

![teleportationfeestables](https://user-images.githubusercontent.com/61279359/108753111-ef026880-7509-11eb-9e94-b32d12a77c76.png)

**Comment by deepbreathingeden** [comment]
![1614121272006](https://user-images.githubusercontent.com/53072734/109500735-0b754680-7ab0-11eb-8ff3-f4b72a3f0672.jpg)

**Comment by KnowOne134** [comment]
Corrected 3/1/2021
