### ISSUE TITLE
Limbus Fee for Cosmo-Cleanse Should be 30,000 Gil not 50k

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#3665]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Please refer to the patch notes found on this page of the June 6th, 2007 version update.

http://www.playonline.com/pcd/update/ff11us/20070606TsVPr1/detail.html

![limbusfee](https://user-images.githubusercontent.com/61279359/108753325-35f05e00-750a-11eb-9dfa-bb10f64b5eae.png)

**Comment by rude-jerk** [comment]
The price of 50,000 gil was intentional to combat inflation.

**Comment by bliven-was-taken** [comment]
Also this already existed. https://github.com/EdenServer/community/issues/3329#issuecomment-706798245
