### ISSUE TITLE
COR AF Quest Against All Odds - Missing Pants/Boots/Sword in CS & CS replayed twice

### ISSUE THREAD

**Issue by Garphilius** [EdenServer/community#3666]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

In the cutscene on the Cutter, it seems Yazquhl is missing his pants, boots and sword. Jahqip is also missing his pants and boots and the mithra npc is also missing her pants and boots. Looks like a subligar festival up in here.

Here is what they should actually be wearing:

https://www.youtube.com/watch?v=8DUKZVqxP0U&feature=emb_title

Further, the final CS replayed twice.

**Comment by deepbreathingeden** [comment]
![Uploading 1612766398802.jpg…]()

**Comment by 59blargedy** [comment]
resolved in March 8, 2021 update except the poor brother will not have pants until a new capture. leaving up until that can be resolved

**Comment by 59blargedy** [comment]
fully resolved March 15, 2021. rest in pants.
