### ISSUE TITLE
Tactics Pearl Quest - Aht Urghan Whitegate Rendezvous Point Completion

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3667]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

After completing the first part of the quest where you check the ??? in any of the Promyvion zones with your fellow, the quest is not able to be completed if you try to turn it in at the Aht Urghan Whitegate rendezvous point. Instead a cutscene about learning combat styles is played over and over again whenever you call for your fellow there (they don't actually learn one).
![image](https://user-images.githubusercontent.com/46270382/108802686-f3a93a00-7566-11eb-8fea-f0cc50b542a0.png)

version 30181205_0

**Comment by deepbreathingeden** [comment]
![Uploading 1612766460812.jpg…]()

**Comment by deepbreathingeden** [comment]
![Uploading bbc test.PNG…]()

**Comment by KnowOne134** [comment]
Corrected April 19 2021
