### ISSUE TITLE
Tavnazian Ring Cannot be Reobtained

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3668]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

If you dropped your Tavnazian Ring and have completed the CoP mission Dawn, Justinius should be able to give back your lost ring once per conquest tally. 
https://www.youtube.com/watch?v=cQ0iKYOMC2c - retail footage / log file of this
The ring also seems to be ready for use once given back.

version 30181205_0

**Comment by deepbreathingeden** [comment]
![Uploading 1614121272006.jpg…]()

**Comment by deepbreathingeden** [comment]
![Uploading 1614121272006.jpg…]()

**Comment by InoUno** [comment]
Added in March 22nd, 2021 update.
