### ISSUE TITLE
Dkhaaya npc doesn't respond. (Olduum ring quest)

### ISSUE THREAD

**Issue by bungdup** [EdenServer/community#3669]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Someone in my xp party mentioned that they couldn't start the olduum ring quest, I tried and couldn't flag it either, Dkhaaya npc doesn't respond.  The quests not flagged or completed on either of my accounts.  30181205_0

**Comment by falzum** [comment]
https://ffxiclopedia.fandom.com/wiki/Dkhaaya NPC in question.

Doesn't seem to be connected to any other quests.

This 100% used to work as I have the ring on both of my characters.

**Comment by 59blargedy** [comment]
This was fixed live and you should be able to obtain the quest now. please comment if not the case.
