### ISSUE TITLE
Land Pugil in Beadeaux should be aggressive

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#3670]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Land Pugil in Beadeaux should aggro sound, but are currently passive. Was able to walk by them and rest by them on lvl 27 THF.

https://ffxiclopedia.fandom.com/wiki/The_Four_Musketeers

"The Quadav in the primary kill area are level 22-28 and will sound-Aggro to players under level 42. The Land Pugils in the kill area are level 20-23 and will sound-Aggro to players under level 35."

Current page for Land Pugil that shows aggressive in this zone

https://ffxiclopedia.fandom.com/wiki/Land_Pugil

Era page for Land Pugil that shows aggressive in this zone

https://ffxiclopedia.fandom.com/wiki/Land_Pugil?oldid=223472

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in march 8, 2021 update
