### ISSUE TITLE
Hand-to-Hand weapons give 2 swings without Hand-to-Hand skill.

### ISSUE THREAD

**Issue by Soleece** [EdenServer/community#3671]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Version: 30181205_0

I was trying to figure out TP for Hand-to-Hand so I could update the wiki, irrelevant. 

Anyway, I had noticed that I clocked a strike for 70tp. I thought, "Oh, that must be for one strike." Turns out it was. The problem was I was RDM/WHM testing what TP would be without Hand-to-Hand skill. 

Without a weapon equipped I strike once. With a weapon equipped (I've tested this with both "Cesti" and "Cat Baghnakhs" I swing twice. I'm under the impression this is an error in the code. 

I don't have the retail version of the game to test so I can't go into to figure out how it works, but from Wiki's they suggest that without Hand-to-Hand skill, there should only be one swing. 

Note: It doesn't mention whether having a weapon equipped would change this. 

The other thing to think about before toying with this is the damage calculation. If you're swinging with one hand, technically you're only using half of the added damage that the weapons give. 

I also can't figure out how TP is being calculated because none of the available calculations are working. It's worth noting that with skill the TP is being calculated as 128TP per rotation, while without (and without a weapon equipped) it's being calculated as 130TP per swing. 

This goes against how the wiki's are telling me that H2H TP is calculated, but it does make sense as each individual strike would be calculated at half the 480 delay (240 each strike), Understanding that there is likely some form of tier (less than 180, 180- 'some number,' etc.) 

The reason I'm saying this is because if you lower the strike on the weapons without Hand-to-Hand skill to one strike, then you "Should" technically lower the added damage by half, but... it isn't going to matter if you simply don't and let that calculation be wrong because no one is going to be using Hand-to-Hand without skill and if they do that little bit of added damage will only help slightly and isn't going to unbalance the game in any way. What I'm saying is that if you're going to change something to fix that (which you don't really have to because no one is ever going to notice), make it easier on yourselves. Lol

I just wanted you to know, incase all this isn't working as intended and you wanted to remove a strike. 

You can also just close this and not worry about it because it is not going to affect much.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
