### ISSUE TITLE
Big Bomb NM has no claim shield

### ISSUE THREAD

**Issue by ThoseWhoFight** [EdenServer/community#3672]
- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

Big Bomb currently has no claim shield and spawns in one spot.

**Comment by rude-jerk** [comment]
Resolved on March 22, 2021 patch.
