### ISSUE TITLE
Don't Have Access to Adventuring Fellow Bond Points

### ISSUE THREAD

**Issue by runnings1oth** [EdenServer/community#3673]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
After completing "Mirror, Mirror" and obtaining a Signal Pearl... 
1) talking to Luto Mewrilah with Signal Pearl equiped doesn't initiate a cut scene
2) speaking with Ajahkeem with Signal Pearl equiped doesn't initiate a cut scene and he doesn't refer to Adventuring Fellows at all
3) I don't seem to be able to call my Adventuring Fellow at Rendezvous Points (tried Windiest Waters and Rulude Gardens)
4) I've called my Adventuring Fellow twice and "Status>Currencies>Fellow Bond" is still zero.

**Comment by tigo9** [comment]
On point 4, are you talking about "Fellow Points" ? Afaik that does not work and is not expected to. Even the 'Applicable NPC' in the title bar is not correct and seems to point to a default name 'Ajahkeem'.

**Comment by runnings1oth** [comment]
> On point 4, are you talking about "Fellow Points" ? Afaik that does not work and is not expected to. Even the 'Applicable NPC' in the title bar is not correct and seems to point to a default name 'Ajahkeem'.

Yes, "Fellow Points". I'm not sure I follow the last sentence. First time doing an Adventuring Fellow, but my understanding is there should be ways to increase your Bond to unlock further equip/skills/lb quests.

**Comment by KnowOne134** [comment]
In era bond is hidden. You can find out what it is by certain quests and options unlocking
Bind goes up by talking at r points and calling it to battle

**Comment by runnings1oth** [comment]
> In era bond is hidden. You can find out what it is by certain quests and options unlocking
> Bind goes up by talking at r points and calling it to battle

Thanks for the clarification. Independent of Status> Currencies... Should I still be able to complete the following from the ffxiwiki?

"To gain access to fellow points, equip your Signal Pearl and speak to Luto Mewrilah in Upper Jeuno (G-8) for a cutscene.
Go to G-9 in Ru'Lude Gardens, next to the Rendezvous Point, and speak with Ajahkeem for a second cutscene."

And why can't I summon my Adventuring Fellow at what I believe are the correct Rendezvous Points.
Ru'Lude Gardens: G-10
Windurst Waters (North): K-10/11
Northern San d'Oria: L-10
Port Bastok: J-13
Aht Urhgan Whitegate: F-10

**Comment by KnowOne134** [comment]
Those fellow points from the 1st question are OOE, they don't exsist. 
As for as not using the points to talk to your fellow, only requirement is to have completed mirror mirror. Does it show completed in quest log. If so make a gm ticket to find out issue

**Comment by runnings1oth** [comment]
> Those fellow points from the 1st question are OOE, they don't exsist.
> As for as not using the points to talk to your fellow, only requirement is to have completed mirror mirror. Does it show completed in quest log. If so make a gm ticket to find out issue

Thanks for the help. Will check and then proceed with ticket if necessary.

**Comment by KnowOne134** [comment]
bond Points are OOE for the server, other issue is a GM ticket situation
