### ISSUE TITLE
Sonic Knuckles additional effect does not appear to be working

### ISSUE THREAD

**Issue by GiichiHiro** [EdenServer/community#3674]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ver 30181205_0

I've attached 2 pages worth of logs, using Sonic Knuckles, on Windsday, and the item has not proc'd once.
I've used it for a couple of levels now, and haven't seen it proc once, so thinking it's not set up to work. 

![SK1](https://user-images.githubusercontent.com/66037286/109307948-c505ba80-7817-11eb-92d4-bcc31a0dd4be.PNG)
![SK2](https://user-images.githubusercontent.com/66037286/109307950-c59e5100-7817-11eb-8137-8a968e276c47.PNG)

**Comment by E5una** [comment]
Not sure if helpful, it’s just forum chat, but here are some people talking about the effect being way more common on windsday and pretty rare for other days. I’ve been leveling with Giichihiro though and haven’t seen them proc either.

https://ffxi.allakhazam.com/db/item.html?fitem=16

**Comment by deepbreathingeden** [comment]
![dfgsdfg](https://user-images.githubusercontent.com/53072734/109501480-12e91f80-7ab1-11eb-91dc-17e9c8b5933b.png)

**Comment by KnowOne134** [comment]
Corrected 3/1/2021
