### ISSUE TITLE
Panzer Percival casts magic, don't think it should

### ISSUE THREAD

**Issue by GiichiHiro** [EdenServer/community#3675]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Ver 30181205_0

Just killed Panzer Percival, NM Beetle in Jugner.  He's listed as a Dark Knight, but I'm pretty sure he's not supposed to be casting, similar to most Beetles. He casted Aero and Bind on me.

I can't find any instance of someone saying he DOES cast, which itself should be proof enough that he shouldn't, as most Mobs that do, have a mention of it somewhere. (And I don't recall it casting from personal memory)

**Comment by GiichiHiro** [comment]
And if he IS supposed to be a caster, his spells should be limited to Earth based mage. Similar to other Dark Knight Beetles (But he shouldn't be a caster)

**Comment by HunnyDoo** [comment]
Watched a few retail youtube vids on Panzer. He never casts a spell.

**Comment by 59blargedy** [comment]
resolved in March 8, 2021 update
