### ISSUE TITLE
Sabotender Enamorado should not link with Cactuar

### ISSUE THREAD

**Issue by faivruit** [EdenServer/community#3676]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Sabotender Enamorado (San d'Oria mission 6-1) is said to not link with the regular cactuar in the area according to wiki, but on Eden the Cactuar link with him.

version 30181205_0

**Comment by deepbreathingeden** [comment]
![Uploading 1612766460812.jpg…]()

**Comment by 59blargedy** [comment]
resolved in a previous update
