### ISSUE TITLE
Every mob in the G-10 Area of Ordelle's Caves is called "Buds Bunny" - is this an early Easter Event?  

### ISSUE THREAD

**Issue by HitGubz** [EdenServer/community#3677]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- {X] I have provided my client version in the details. (type /ver into your game window)

### Details
Everymob in the G-10 area of Ordelle's Caves is called Buds Bunny
![Buds Bunny](https://user-images.githubusercontent.com/50017064/109387784-3ec2a480-78fb-11eb-918c-b6fd3d26a1d1.PNG)

**Comment by deepbreathingeden** [comment]
![Uploading dfgsdfg.png…]()

**Comment by deepbreathingeden** [comment]
![Uploading 1614121272006.jpg…]()

**Comment by deepbreathingeden** [comment]
![Uploading 1612766460812.jpg…]()

**Comment by 59blargedy** [comment]
while this is my one of my favorite bug reports, this is an issue of either client mismatch, not having an updated renamer file, or renamer going wonky and not something we'd solve, so closing.
