### ISSUE TITLE
Redoing BLM AF hat quest - don't need to check 2nd ???

### ISSUE THREAD

**Issue by tigo9** [EdenServer/community#3679]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

/ver 30181205_0

### Details

After resetting AF quests with Vingijard, when you redo the blm hat quest, you can skip the 2nd ??? (where you should have to use Manafont) and go pop the NM at the 3rd ???.

**Comment by deepbreathingeden** [comment]
![1614121272006](https://user-images.githubusercontent.com/53072734/109500757-14661800-7ab0-11eb-9425-930001869527.jpg)

**Comment by deepbreathingeden** [comment]
![Uploading 1614121272006.jpg…]()

**Comment by deepbreathingeden** [comment]
![Uploading 1614324985261.jpg…]()

**Comment by deepbreathingeden** [comment]
![Uploading 1614121272006.jpg…]()

**Comment by deepbreathingeden** [comment]
![Uploading bbc test.PNG…]()

**Comment by 59blargedy** [comment]
resolved in the March 29, 2021 update
