### ISSUE TITLE
Beadeaux Quadav Linking Below Ground

### ISSUE THREAD

**Issue by prwilson42** [EdenServer/community#3681]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Quadav link from below the ground.  Pulled a Quadav and it linked all the other Quadavs in the room below.  After they killed me they all walked back through the ground to the room they were in.

**Comment by deepbreathingeden** [comment]
buy some gil for as low as 1m/1$! paypal payment safe and instant! add discord for more info: LargeSeLLs#7167

**Comment by deepbreathingeden** [comment]
![dfgsdfg](https://user-images.githubusercontent.com/53072734/109501306-db7a7300-7ab0-11eb-9e4d-2d11304e8f72.png)

**Comment by deepbreathingeden** [comment]
![Uploading 1612766460812.jpg…]()
