### ISSUE TITLE
Dynamis Lord Summons Ying and Yang on pull

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3682]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
During our Dynamis Lord attempt yesterday Ying and Yang were summoned immediately when DL was pulled. 

2009 video showing that at 0:55 he summons Y and Y with a normal summoning animation and they spawn back at the castle vhazl gate. You can see them approaching the alliance at the last second of the video. 

(:55 summons) https://www.youtube.com/watch?v=s1mnGxAT99M

(2:14 they pull DL, no instant death or dragon summon for whole fight) https://www.youtube.com/watch?v=Mv1rJgWy9As

(Summons Y and Y at :35) https://www.youtube.com/watch?v=zmxFz5zGWJk

30181205_0

**Comment by deepbreathingeden** [comment]
buy some gil for as low as 1m/1$! paypal payment safe and instant! add discord for more info: LargeSeLLs#7167

**Comment by deepbreathingeden** [comment]
![Uploading 1612766460812.jpg…]()
buy some gil for as low as 1m/1$! paypal payment safe and instant! add discord for more info: LargeSeLLs#7167

**Comment by deepbreathingeden** [comment]
![Uploading bbc for juul.jpg…]()

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
