### ISSUE TITLE
Serious digging bug

### ISSUE THREAD

**Issue by MB213** [EdenServer/community#369]
Went digging today and success rate of digs were abnormally high.
I also dug up 3 fire ores. 2 in Valkurm Dunes and 1 in Konschtat Highlands, minutes apart. 
I'm only rank 2 digging, it was a 79% moon, iceday, no weather. 
This isn't a visual error, I have the items in my inventory.

![mihki_2018 11 27_162108](https://user-images.githubusercontent.com/37488914/49061113-16532800-f264-11e8-8650-d0c6bd809088.png)
![mihki_2018 11 27_163735](https://user-images.githubusercontent.com/37488914/49061205-3da9f500-f264-11e8-8d9d-db19b9ce310d.png)
![mihki_2018 11 27_164450](https://user-images.githubusercontent.com/37488914/49061212-44d10300-f264-11e8-880b-c28734fd2dee.png)

**Comment by godmode** [comment]
Thanks for reporting, I made a patch early this morning. It was applied in real time so you can continue digging now.

**Comment by panfunk** [comment]
Digging accuracy still seems way off:

![pan_2018 11 27_204222](https://user-images.githubusercontent.com/36666121/49107198-5c6cb380-f285-11e8-8400-7f4fab5851d9.png)

Just dug in Altepa

**Comment by godmode** [comment]
Try now

**Comment by panfunk** [comment]
I'm almost certain the problem is with the Last/First Quarter Moon-Phases.
Atm it's first quarter moon, I bough 1 stack of greens on Pan/Chan and went 11/12 and 12/12 succesful digs.
Every other moon phase I digged so far, felt normal.

**Comment by Lilswitche** [comment]
Forgot this wasn't fixed and went out at 45% moon.  With weather and Expert digging, the dig rate was 100%.  As soon as the day ticked over to 43%, the dig rate returned to normal. 

It appears how the LQM/FQM moon phases affect rolls is not working correctly and bore/burrow items are not being drawn at all.
