### ISSUE TITLE
fishing merchants

### ISSUE THREAD

**Issue by Laved** [EdenServer/community#370]
fishing merchants dont have a lot of their restockables of lures and fishing rods.  no selbina/mhaura ferry so cant buy lures there either, inturn the stuff is being mega price gouged on the AH T_T

**Comment by roriffxi** [comment]
You need to check the wiki history from late 2007 and provide a link to it showing the items that were for sale. Retail has added a lot of items to vendors that weren't originally there.

**Comment by godmode** [comment]
Thanks for reporting @Laved! I've included [this link](https://ffxiclopedia.fandom.com/wiki/Babubu?oldid=367015) which is the last wiki history page before wotg for your reference. In future tickets the more you provide the faster and easier it will be for us to take these on. Thanks again
