### ISSUE TITLE
Furniture Quests

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#371]
Howdy, 
according to patch notes 'Furniture Quests' were added. I'm not certain if you mean the Mog Safe expansion quests by this but the quest:
https://ffxiclopedia.fandom.com/wiki/Give_a_Moogle_a_Break
is not triggered. Bronze bed is arranged in MH and fame is adequate

**Comment by godmode** [comment]
All furniture quests including the mog safe expansion ones are implemented and were tested to work on the dev environment. Please make sure you are following an era accurate guide and reopen the ticket if the issue exists.

**Comment by Siushaga** [comment]
Been a couple of months and still no luck with flagging this quest. Are there any tips on doing anything special to get this to flag like removing and placing the Bronze Bed again on a certain day and then waiting until another certain day? Have tried quite a few methods on my own, but mostly just been letting it sit there for weeks to see if my rude Moogle would finally appreciate his gift!

**Comment by rpcon** [comment]
I am also having the same problem.
