### ISSUE TITLE
Citipati broken

### ISSUE THREAD

**Issue by Eme-FFXI** [EdenServer/community#374]
Camping Citipati since a couple of days, 2 things seem strange to me (I never camped it on retail)
1. Citipati was up during day when I logged in (probably I killed PH before going to sleep and it popped and staying up until I logged in again)
2. 4 kills with TH2 and no drop at all (no trousers, no bracelet, no harp) seems below bad luck

**Comment by icariumkupo** [comment]
I killed this the other day. Looked to me like he doesn't have a PH at all. He popped when night turned but so did the 3 corse in his spawn area. He should have taken the place of one of them.

**Comment by Eme-FFXI** [comment]
Popping him seemed ok to me, I killed 3 PHs then 5min later 1 PH would not pop so I search for NM and it was up. Despawning when unclaimed during day seems to be broken tho

**Comment by tectal831** [comment]
Duplicate of #421

**Comment by Eme-FFXI** [comment]
I'm not sure if this issue should be closed as a duplicate. The fact that Citipati does not drop anything remains.
