### ISSUE TITLE
experience rings not giving all of their (era) "Maximum Bonus" in some situations

### ISSUE THREAD

**Issue by beauxq** [EdenServer/community#378]
The total amount of experience that exp rings give is reduced in some situations.

The problem is here:
https://github.com/DarkstarProject/darkstar/blob/master/src/map/utils/charutils.cpp#L3415

The line `exp = charutils::AddExpBonus(PMember, exp);`
needs to be moved down below any penalties or canceling of experience.
The pet penalty and the "too far away to gain experience" should come before that line.
(If a level sync exp penalty is added, that also needs to be before that line.)

The issue is that that function is not a pure function. It has side effects. And those side effects still happen with the full values even if "You are too far from the battle to gain experience."

That line should be moved down to right before
`charutils::AddExperiencePoints(false, PMember, PMob, (uint32)exp, baseexp, chainactive);`

**Comment by panfunk** [comment]
![image](https://user-images.githubusercontent.com/36666121/51032674-2c614180-15a1-11e9-97ae-0d57999109bc.png)

just a bump to this issue! *bump*

**Comment by beauxq** [comment]
@godmode I found today that this is not completely fixed yet.

I think the change below will fix it.
I haven't tested this, but it looks pretty simple.
It just adds one line to say "if the person is dead, then skip all of the exp stuff".
(Note: The `return` is not from the `DistributeExperiencePoints` function. It is from the lambda from the first line of this diff, similar to the `return` when someone is too far away to get experience.)

```
--- a/src/map/utils/charutils.cpp
+++ b/src/map/utils/charutils.cpp
@@ -3206,6 +3206,7 @@ namespace charutils

         PChar->ForAlliance([&PMob, &region, &minlevel, &maxlevel, &pcinzone](CB
attleEntity* PPartyMember) {
             auto PMember = static_cast<CCharEntity*>(PPartyMember);
+            if (PMember->isDead()) { return; }
             uint32 baseexp = 0;
             auto exp = 0.f;
             float permonstercap, monsterbonus = 1.0f;
```
