### ISSUE TITLE
Movement speed gear stacking

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#379]
Movement speed gear (e.g. strider boots and crimson legs) stacking when it shouldn't.

**Comment by Xaver-Entropia** [comment]
Where did you get the info about Aketons stacking?
I haven't found any reference to that.

https://ffxiclopedia.fandom.com/wiki/Movement_Speed
"Boosts to movement from multiple pieces of equipment will not stack with each other. The largest boost is the one the player will receive."

https://www.bg-wiki.com/bg/Movement_Speed
"Note that while positive movement speed bonuses on equipment DO NOT stack (only the highest bonus equipped takes effect), negative movement speed equipment does stack."

**Comment by Aneyus** [comment]
You're right, I was just parroting what I had heard someone else say. Updated OP

**Comment by godmode** [comment]
Thanks for reporting. Just an FYI for anyone that might read this report: Until this issue is fixed I don’t mind this being used to travel around so much just don’t use it in a monster killing strategy.

**Comment by Mikokiko** [comment]
I dunno if it's a common bug around DSP, but on Nas you could have strider + crimson legs + marzuka and did not seem to have a cap.

**Comment by Slamm21** [comment]
https://github.com/EdenServer/community/issues/3106
seems this is still an issue

**Comment by perkuprightmeow** [comment]
Just to note, this only applies AFAIK to Aketon + W Legs **OR** Striders. It does NOT work for W Legs + Striders. AKA it can only be used in town.

**Comment by Slamm21** [comment]
I think this should be closed then.
