### ISSUE TITLE
Sauromugue Champaign rusty greatswords

### ISSUE THREAD

**Issue by Laved** [EdenServer/community#383]
im fishing up rusty greatswords in Sauromugue Champaign, i dont think their supposed to be there but this is the earliest wiki reference of the fishing list i can find https://ffxiclopedia.fandom.com/wiki/Sauromugue_Champaign?oldid=479134
older ones dont have a fishing list added, sorry if im wrong about this!

**Comment by Setz0r** [comment]
never just check wiki, too much copy and paste and inconsistencies 
http://www.great-blue.jp/?aid=045&bid=&lng=en
