### ISSUE TITLE
Davoi Farming

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#384]
I've heard a lot of people talking about Orcish Footsoldiers in Davoi having above average drop rates on Silver armor of all types, some people even claiming that they were getting multiple pieces per kill.  

I went out last night and tested for about an hour and a half and observed a pretty average drop rate overall.  (Went 4/11 on Footsoldiers, none double dropping)  This camp might be high income per hour for players who are already VERY overgeared, but my Thief is pretty average and I don't see this being a 100k/hour camp for your average player.  Overall I only walked away with about 20k. The drop rate didn't seem to be out of line of the Cuir gear you can farm from similarly leveled Goblins in Altepa Desert.  And you can steal the same beastcoins from those goblins too.  Cuir isn't worth much less than the silver stuff and is used in making Dusk armor so its value is a little more overall tangible. 

I plan on doing more to increase sample size this weekend, will post more as I go.   I did want to have a bug report up for this though in case we run into another Antlion Jaw situation.

**Comment by Serephim** [comment]
If you are only killing foot soliders and you only killed 11, you are doing it wrong and thats a really small  sample size. :P

**Comment by gweivyth** [comment]
Yeah there was already someone else there farming so I had to stick to the ones on the way to Monastic Cavern instead of the "normal" path.  I was killing the PLD ones too (the ones that drop the plate armor) but they weren't anything special and took a bit longer to kill. 

Sample size was small cause I started kinda late at night.  Had to sleep.  :(

**Comment by Serephim** [comment]
Today I filled my inventory twice in just over an hour. Got 2 stacks of gold orc masks too. Drop rates seem quite OP compared to Kupo and retail. Granted I was there with a Ridil THF and KC THF clearing the zone. But the drop rates definitely felt much higher than Kupo's. I can only imagine what it would be like on full moon. lol

**Comment by Aneyus** [comment]
I was starting to keep data from my farming in Davoi but then I lost my (borrowed) TH3. The one run I had data from went something like this farming with KC TH3 and a MNK/WAR.

Time Elapsed: 1hr 45 Minutes
Moon: 44%-40% waning crescent
Total gil gained from vendorables (sans raw gil drops b/c I forgot to check before starting): 165,825
Gil/hr: ~94,757

**Comment by Aneyus** [comment]
https://cdn.discordapp.com/attachments/487301249184563214/518242598121635845/Fate_2018.11.30_204136.png

**Comment by Aneyus** [comment]
https://media.discordapp.net/attachments/418616007129825287/519004027095220286/Fate_2018.12.01_215216.png?width=705&height=397

**Comment by Aneyus** [comment]
https://cdn.discordapp.com/attachments/418616007129825287/519310681770819645/Fate_2018.12.03_193430.png

**Comment by gweivyth** [comment]
I still haven't had a crack at farming here, there's literally ALWAYS someone there when I want to go.  My gear got a little better (got Ridill) so now I'm curious to see what I can get in "slightly above average" gear.
