### ISSUE TITLE
Character stuck after zoning

### ISSUE THREAD

**Issue by Catrim** [EdenServer/community#392]
![catrim_2018 12 01_115345](https://user-images.githubusercontent.com/45519691/49331508-b7432b00-f563-11e8-8dc2-42abcb85f1c2.png)

Happens when I leave moghouse.  Was asked on discord to create a bug report and screenshot.

**Comment by gweivyth** [comment]
Has this happened again since posting this?  It's pretty rare.

**Comment by Catrim** [comment]
About half the time I leave MH...

**Comment by Catrim** [comment]
If I change my jobs enough to trigger the 'You changed jobs and you might wanna set your HP here' msg, it  doesn't happen... so I've been using that as a workaround.

**Comment by Catrim** [comment]
![catrim_2018 12 15_105126](https://user-images.githubusercontent.com/45519691/50046966-6d356b80-0072-11e9-8d94-c7a468a98316.png)

**Comment by Catrim** [comment]
This is still happening to me several times per day.  The cheap warp scrolls available at Gate Guards  are my way out of this situation.  I see you are considering resetting warp scrolls to era prices, but I urge you to address this issue in some manner before making that change.

**Comment by godmode** [comment]
@Catrim can you please continue to update this ticket when this happens? When you exit from (zone and position) and where you zone into (zone and position). Also clarifying if it is from mog house when you specify the zone. Screenshots are helpful as well.

**Comment by Catrim** [comment]
![catrim_2019 01 07_223206](https://user-images.githubusercontent.com/45519691/50809895-3a2a7480-12cc-11e9-9b81-40b4698ad36a.png)

**Comment by Catrim** [comment]
![catrim_2019 01 09_104221](https://user-images.githubusercontent.com/45519691/50914037-52e57800-13fb-11e9-8082-a0e42b676c0c.png)

**Comment by Catrim** [comment]
![catrim_2019 01 11_120816](https://user-images.githubusercontent.com/45519691/51051538-b0afc680-1599-11e9-9ee0-344690aa2e78.png)

**Comment by Catrim** [comment]
![catrim_2019 01 12_070327](https://user-images.githubusercontent.com/45519691/51073553-384c1280-1638-11e9-9bbb-483023e65f7f.png)

**Comment by godmode** [comment]
Is it always the same place you move each time? If so can you mention the area you exited from?

**Comment by Catrim** [comment]
Exited from MH.  It's always the same place in the zone I'm zoning to.  I would be willing to recreate issue for someone if they wanna watch.

**Comment by godmode** [comment]
I’ll check it out tonight after this key item patch goes live.

**Comment by Catrim** [comment]
![catrim_2019 01 13_214317](https://user-images.githubusercontent.com/45519691/51095719-53c03600-177c-11e9-9968-8f9af6ce60cb.png)

**Comment by Catrim** [comment]
![catrim_2019 01 15_091338](https://user-images.githubusercontent.com/45519691/51189737-41421b80-18a6-11e9-8405-f3c9afeae00e.png)

**Comment by Catrim** [comment]
![catrim_2019 01 16_103047](https://user-images.githubusercontent.com/45519691/51263441-de21b900-1979-11e9-97be-cae2426a6447.png)

**Comment by Catrim** [comment]
![catrim_2019 01 17_081552](https://user-images.githubusercontent.com/45519691/51324490-78443880-1a30-11e9-8a11-d1d82aba0e0a.png)

**Comment by Catrim** [comment]
![catrim_2019 01 20_124428](https://user-images.githubusercontent.com/45519691/51448999-aefba680-1cef-11e9-9337-78df513464e2.png)

**Comment by Catrim** [comment]
I've been using 'Do you want to set your HP here" as a workaround to NOT get this error.

**Comment by Catrim** [comment]
![catrim_2019 01 22_102241](https://user-images.githubusercontent.com/45519691/51549339-d8bbe700-1e2f-11e9-87e7-ad5138ab71ca.png)

**Comment by Setz0r** [comment]
@Catrim do you have the latest client?

**Comment by Catrim** [comment]
yep
________________________________

**Comment by Catrim** [comment]
![catrim_2019 01 28_171156](https://user-images.githubusercontent.com/45519691/51872678-f1d90200-231f-11e9-865b-0f65fdf397cb.png)
First time I've had this issue in a few days.  It's been kinda nice.

**Comment by Catrim** [comment]
I haven't had this issue since I last posted.

**Comment by godmode** [comment]
That’s good news! Thanks for the update.

**Comment by Catrim** [comment]
![catrim_2019 02 23_174220](https://user-images.githubusercontent.com/45519691/53293052-789fc400-3792-11e9-86ba-ba8a9cb574f2.png)
First time I've had this issue since the last screenshot I took.

**Comment by godmode** [comment]
We think we know the issue now but it will take quite a bit of time to fix it. Probably don’t need to post more screenshots now. Just gotta hang in there when it does happen for now :(

**Comment by Catrim** [comment]
I see you closed this ticket... but the problem is back with a vengeance.  it's almost everytime I zone now.  I keep getting dropped from parties... I am ghosted in search a lot...

Just wanted to let you know.
________________________________

**Comment by Aviglug** [comment]
I am having the same problem. Almost every single time i leave the mog house but it happens in all 3 cities.
