### ISSUE TITLE
autotarget only for last hitter

### ISSUE THREAD

**Issue by beauxq** [EdenServer/community#395]
Currently autotarget only works for the 1 player that gets the last hit on the enemy.
autotarget should work for everyone engaged.

Here is a fix:
https://github.com/bdhs/darkstar/compare/58b398037af80f9cc16ee6e895d864beeb7e0280..38cdd6622f7e07ca0d14507eb1a76e648b430ed7

**Comment by gweivyth** [comment]
The real MVP here.  This is going to be insanely important for merit parties.
