### ISSUE TITLE
Chocobo Digging - Rank Up

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#396]
Hey, I just dug up lightning ores, then I checked my rank by zoneing and saw that I apparently have the maximum rank: 10sec delay upon zoneing.
I only hit Rank4 ( 0 dig delay ) like 1 week ago. I didn't write down the amount of stacks I burned since then, it was maybe 1000~. So I shouldn't be at max-rank for a long time.
 
![pan_2018 12 02_014244](https://user-images.githubusercontent.com/36666121/49334464-25750580-f5d7-11e8-9ad9-5b0e7aa66f0d.png)

Zone delay:
![pan_2018 12 02_014816](https://user-images.githubusercontent.com/36666121/49334466-2c037d00-f5d7-11e8-820d-6b29a0dfd9fc.png)

**Comment by godmode** [comment]
This should be fixed
