### ISSUE TITLE
Exiting Mammets BCNM doesn't clear battlefield

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#397]
First and foremost, the BLM form of the mammet needs to be susceptible to silence without Elemental Seal.

Beyond that, the major bugs I've encountered have to do with exiting the BCNM, either trying to run away from the encounter or dying and being spat out back into the staging area.

If you escape by exiting the way you entered (Run away! option) the mammets follow you out into the staging area and kill you. Sync persists (even though it is a 75) area until they kill their target and return to the island and regen to 100%.

If you die and are kicked out, your reraise is wiped and you are occasionally trapped in a black screen. I have also witnessed people being kicked out to the wrong side of Monarch Linn as if they won when their party is still on the other side.

**Comment by slassen** [comment]
The title of this issue should have been fixed in the BCNM rewrite, please reopen the issue if it is not the case. If there are other items on this list that need corrected as well, someone please create separate issues for each item.
