### ISSUE TITLE
Unstable Cluster (Soboro NM)

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#398]
This NM does use self destruct (it is supposed to use it 3 times max if it is successful; it does not die from it) but it is rare. You can go an entire kill without seeing it attempt to use self destruct.

Perhaps needs the frequency of use of this particular TP move higher prioritized until it has used it 3 times.

Note: We have had kills almost wipe to self destruct multiple times in a fight, but it is not common enough.

**Comment by Treble011** [comment]
After the patch today, none of the clusters seem to be self destructing at all now and formation attack does 0 damage.

**Comment by Oyaziiiiiii** [comment]
Clustered tar(the pop item) drop rate might be a little high too. Wiki says 33% but it felt higher unless we just got really good rng.

https://ffxiclopedia.fandom.com/wiki/Nitro_Cluster

**Comment by godmode** [comment]
This should be using the correct mechanics now. Can you also let me know about the drop rate if it's still too high? Thanks.

**Comment by AnkleAssassinz** [comment]
Update 07/17/2019: 
 My group noticed this NM *NEVER* move from initial spot once popped; instead it just spams 'Refueling'.

**Comment by Serephim** [comment]
Can confirm, went to do this today and it didn't move from it's spawn point, it just spams TP moves over and over. Refueling if you are not within range, will mostly use refueling but sometimes uses other TP moves too when you are in range.

**Comment by KnowOne134** [comment]
found no issue
