### ISSUE TITLE
Opening treasure chest with full inventory allowed but item lost

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#399]
Started with 60/60
Opened chest with key
![image](https://user-images.githubusercontent.com/1774728/49335447-90184800-f5bb-11e8-8755-46ad58ec0088.png)

Now 59/60

**Comment by asmolyneux** [comment]
80/80 inventory
![molyneux_2018 12 24_045517](https://user-images.githubusercontent.com/46098588/50391233-a2f4e700-0739-11e9-8b6c-3b5f1c22bcd8.png)
![molyneux_2018 12 24_045526](https://user-images.githubusercontent.com/46098588/50391235-a6886e00-0739-11e9-8efc-3ed4df845eb8.png)
![molyneux_2018 12 24_045537](https://user-images.githubusercontent.com/46098588/50391236-a8eac800-0739-11e9-8efe-42efd4e388cd.png)
Item received
![molyneux_2018 12 24_045631](https://user-images.githubusercontent.com/46098588/50391237-ab4d2200-0739-11e9-9d1f-809647c19645.png)

Just confirming that you should have still received the item.

**Comment by KnowOne134** [comment]
you would get a message you can not open chest, sort your inventory message and nothing would be consumed
