### ISSUE TITLE
King Vinegarroon

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#4]
1. Shouldn't be aggressive.
2. Earthbreaker should be absorbable with shadows. This is for all scorpions that use this skill. I imagine earth pounder is the same but I can't find a video on it.
3. Wild rage should be absorbable with shadows. This is for all scorpions that use this skill.
4. Stun resist should be super low. RDM/DRK shouldn't see many(any) resists.
5. Shouldn't be sleepable.
6. Should pop 100% on double weather, ~10% on single weather, and depop if weather drops. I noticed he was chilling up with no weather when I went to check on him.

https://www.youtube.com/watch?v=n5I_2cp0mog ( 0:41-0:46 earthbreaker absorbed by shadows)
https://www.youtube.com/watch?v=i1l7uthLPMY (1:30 wild rage absorbed by shadows)

**Comment by godmode** [comment]
Stun will be on a separate patch along with magic resistance overhaul. Earthbreaker and Earth Pounder I'm going to leave wiping shadows for now until I can get verification on current retail from one of my devs.
