### ISSUE TITLE
Supply runs to outposts not saving

### ISSUE THREAD

**Issue by Billbo1** [EdenServer/community#402]
Hi yesterday i started doing supply runs on my character billbo, and successfully delivered a few with no problems, then i did norvallen and aragoneu and they delivered as normal, however when i wanted to tele there from the npc in bastok i noticed they were not available to warp out to, i went back to gate guard and he told me they were done.
Today i did derfland region and the same has happened, showing as completed but not available to warp to, however with a ll the glitched OPs i can teleport back home from them.
Any help would be appreciated in fixing this issue.

**Comment by godmode** [comment]
What level are you and what OP are you trying to use?

**Comment by Billbo1** [comment]
I am level 14 atm, and i was trying to warp to the outposts i supplied to norvallen, aragoneu and derfland.
I have zero issues warping to any other zones i have done the warps for, just those 3 zones just do not show up from the Conrad the teleport NPC. But if i go back to the guard, under supply missions they are completed.

**Comment by godmode** [comment]
You don't meet the requirements to use those OPs yet. Please check out some sources or ask around. If you believe it is still an issue please make another comment on this ticket.
