### ISSUE TITLE
Mandragora mobs only attack once

### ISSUE THREAD

**Issue by Lexxi-foxxx** [EdenServer/community#404]
It was fixed on the 12/1 patch according to the patch notes on the website, but the ones in Tahrongi Canyon still only attack once. I did not test any others but someone told me the black ones in Boyahda still only attack once as well.

**Comment by Nyoomy** [comment]
Just killed Tom Tit Tat, Mandragora NM in West Sarutabaruta - it also only has one attack per round.

**Comment by gweivyth** [comment]
The update to DSP re-broke it it looks like.  They were working OK for a few days.

**Comment by rujind** [comment]
"Korrigan"s in The Boyahda Tree only attack once

**Comment by godmode** [comment]
This wasn't a problem from DSP it was my error. The fix should be live Tuesday after the patch
