### ISSUE TITLE
Talking to Npcs.

### ISSUE THREAD

**Issue by NovaDrag0n** [EdenServer/community#405]
Playing from England with a compatible POL/FFXI, I noticed every time I talk to Npcs, I get a slight delay in load allowing me to run like 0.2-3 seconds, then the Npc stops me and talks to me.

**Comment by beauxq** [comment]
I think that is how it is on retail. It's just part of how the game works.

**Comment by NovaDrag0n** [comment]
Yeah, but on Nasomi it instantly responds.

**Comment by beauxq** [comment]
The client has to receive a message over the internet to start the reaction. It has to take time for the message to travel over the internet.

It may be the case that on Nasomi, you can't walk during the time that you are waiting for the message from the internet. But that doesn't change how fast the message travels over the internet.

**Comment by NovaDrag0n** [comment]
Alright, I'll just close it then to save a time waste. I'm just not used to it.
