### ISSUE TITLE
OP to Dunes too expensive for Bastok this week. 

### ISSUE THREAD

**Issue by Catrim** [EdenServer/community#406]
![catrim_2018 12 03_121320](https://user-images.githubusercontent.com/45519691/49392789-1be1bf80-f6f5-11e8-89f1-4ad965181f1c.png)

**Comment by Xaver-Entropia** [comment]
This isn't an issue.
800 gil is the cost to warp to Zulkheim region when your home nation doesn't own it.

**Comment by godmode** [comment]
The issue I saw was 800CP same as gil

**Comment by Xaver-Entropia** [comment]
true, it should be 1/10th, but i thought you kept it that way on purpose

**Comment by Siushaga** [comment]
Confirmed that CP is truly charging what it says, and not just a visual/text issue. Had 61,275 before OP to Dunes and then had 60,475 afterwards. Text stated 800 Gil or 800 Conquest Points, so definitely not doing the 1/10th rate for CP.
