### ISSUE TITLE
Blm spells and MP.

### ISSUE THREAD

**Issue by NovaDrag0n** [EdenServer/community#407]
I'm currently Level 5 blm, have 7 MP and game states I don't have enough MP to use Stone or Water. Stone cost 4 MP and Water cost 5 mp, cannot use if I'm below 10 MP.

**Comment by NovaDrag0n** [comment]
Ok might below 15 MP, Water/Stone refuses at 11 MP.

**Comment by beauxq** [comment]
Duplicate of https://github.com/EdenServer/community/issues/30

**Comment by godmode** [comment]
Duplicate of #30
