### ISSUE TITLE
Mamool Ja Mimers hit too hard with some spells

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#4099]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
https://media.discordapp.net/attachments/569144558659567618/799778032314482708/Capture3.PNG

I don't have a lot of details / extensive testing on it.  Nor do I know what an appropriate amount of damage should be, but occasionally they just rock your world.

This was against a level 75 rdm with Shell4.  Tho hecatomb might be a physical dmg spell and thus shell4 would do nothing.

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
