### ISSUE TITLE
Login/Account Problem

### ISSUE THREAD

**Issue by XenoDragonfly** [EdenServer/community#41]
I cant login doesnt matter where Webpage or game it self.

Acc: Xenonflash & Xeno

![2018-10-02_23h16_31](https://user-images.githubusercontent.com/39119593/46408115-53da7f80-c711-11e8-8581-0ef65f60e31d.png)

but i can find all of my ACC:

![2018-10-03_13h37_35](https://user-images.githubusercontent.com/39119593/46408166-81bfc400-c711-11e8-95f3-bb47380f7577.png)

**Comment by XenoDragonfly** [comment]
oh and also my friend ACC also not working: lilly_unartig 

but we could login a few days ago to Kupo 💃

**Comment by godmode** [comment]
Please confirm that you both are entering your login credentials correctly. Everything looks like it's still there. If you triple checked you are using the right username and password please send a private message on discord to me.

**Comment by godmode** [comment]
This was due to a corrupt / incorrect bootloader. For anyone looking at a similar issue please download the newest version of Ashita before posting a bug report like this.
