### ISSUE TITLE
Can lot shit from Mog House

### ISSUE THREAD

**Issue by NojKujata** [EdenServer/community#410]
![naj_2018 12 03_225030](https://user-images.githubusercontent.com/43772801/49418150-d05bff80-f74e-11e8-8e5a-1c14e4963ccd.png)

**Comment by NojKujata** [comment]
Handy or Hax

**Comment by Setz0r** [comment]
you're able to lot the treasure pool of characters not in the same zone?

**Comment by Treble011** [comment]
This was a bug on Kupo originally as well, I just entirely forgot about it until Naj mentioned this last night. You can lot on anything in other players treasure pools from other zones as long as you're in the party with them.

**Comment by godmode** [comment]
I believe this has been fixed now for a few months. Please comment if it is still happening.
