### ISSUE TITLE
G5 Maat (NIN?)

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#4100]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Just fought Maat as 66NIN and he hit me for 4/5 damage.
Mijin Gakure did 550 damage @40%~
Saw a cpl Maats bug reports but none like this.

![image](https://user-images.githubusercontent.com/36666121/109546807-f4901d80-7aca-11eb-8048-584a1076320a.png)

![image](https://user-images.githubusercontent.com/36666121/109546865-ff4ab280-7aca-11eb-8eda-93c304610967.png)

**Comment by 59blargedy** [comment]
resolved in the March 15, 2021 update
