### ISSUE TITLE
NIN or /NIN Mob offhand (off-hand) damage too low

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4101]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

There is an issue with some mobs that appear to be the same as the issue that NIN Mamool Ja had where their offhand hit is for negligible damage. It seems like it might be somehow related to dual-weild, although most NIN mobs don't attack twice (tonberry/yaduo don't). It affects Ark Angel HM, as shown below, captured form the test server.

![image](https://user-images.githubusercontent.com/13668758/109561422-22fe0080-7aab-11eb-8668-a325c5a6d2e8.png)

version 30181205_0

**Comment by E5una** [comment]
This may or may not be related to https://github.com/EdenServer/community/issues/4100. I'm not familiar enough with the battle log display that user is using to determine if it is an offhand hit or not. I couldn't figure out how to have myself fight NIN Maat to test.

**Comment by 59blargedy** [comment]
resolved in the March 15, 2021 update
