### ISSUE TITLE
Magic Burst Damage calculation is wrong post recent magic accuracy patch

### ISSUE THREAD

**Issue by davidsound** [EdenServer/community#4102]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

It's doing too much damage. I'm magic bursting Burst II in limbus for 4k

**Comment by davidsound** [comment]
https://imgur.com/a/qkyk5Qu

**Comment by davidsound** [comment]
https://imgur.com/a/SoSBrla

Burst II magic burst damage

**Comment by 59blargedy** [comment]
resolved march 2, 2021
