### ISSUE TITLE
Garuda's Dagger "Silence" AE not functioning

### ISSUE THREAD

**Issue by EdenPenance** [EdenServer/community#4103]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Posting on behalf of Linseed#5956:

Garuda's Dagger is not working as intended. After extensive testing, it has been found to never silence any mob under any circumstance.
![image](https://user-images.githubusercontent.com/76273942/109623529-da723180-7b02-11eb-843e-3921ee1c01d1.png)

**Comment by 59blargedy** [comment]
resolved in the March 15, 2021 update
