### ISSUE TITLE
Dynamis Jeuno Statues by Maat too close together and always link

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4105]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

http://www.dynamisbums.com/strategy/images/maps/strategy_jeu1.jpg
Statue 289 and statue 285 should be moved back to be closer to statue 293. Close enough that they don't link when you pull 283/281

You can see the statue arrangement in era here: (4:00)https://www.youtube.com/watch?v=viHBluchmGE&feature=emb_title at the 4 minute mark. 

Another video where they pull without timed nuking and still no link: (8:10)https://www.youtube.com/watch?v=T2TBxPWGgBs&t=543s

/ver 30181205_0

**Comment by Slamm21** [comment]
https://static.wikia.nocookie.net/lowdroprates/images/c/ce/Jeuno1.jpg/revision/latest?cb=20100430220829&format=original
better map

**Comment by 59blargedy** [comment]
Resolved in June 7, 2021 update
