### ISSUE TITLE
Quest: For the Birds / Koblakiq

### ISSUE THREAD

**Issue by Killface777** [EdenServer/community#4106]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

After completing the Missionary Moblin quest with Koblakiq in Oldton, the npc does not start the next quest in the line "For the Birds", which is dated back to 2005. I have zoned, logged, etc and have the completed Missionary Moblin in my quest log. There do not seem to be any other prerequisites listed.

https://ffxiclopedia.fandom.com/wiki/For_the_Birds

**Comment by 59blargedy** [comment]
we just recently implemented missionary moblin, don't yet have this quest in!

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
