### ISSUE TITLE
Flans are not taking 25% extra magic damage

### ISSUE THREAD

**Issue by AbsoluteXzeroX** [EdenServer/community#4108]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Flans are not taking 25% extra magic damage. Attached are screenshots of the same gear used to nuke a low level mob and a pudding for similar damage. 

![t4_worm](https://user-images.githubusercontent.com/26514268/109721630-5cf20400-7b8a-11eb-9a9c-f2f2235911d8.png)
![t4_pudding](https://user-images.githubusercontent.com/26514268/109721651-624f4e80-7b8a-11eb-948e-c851dd0642f8.png)
![burst2_pugil](https://user-images.githubusercontent.com/26514268/109721659-64b1a880-7b8a-11eb-910d-3d89fbd645e1.png)
![burst2_pudding](https://user-images.githubusercontent.com/26514268/109721663-67140280-7b8a-11eb-82f0-dd4d18676fb7.png)
 

Ver: version 30181205_0

**Comment by tigo9** [comment]
https://www.youtube.com/watch?v=wHJnd81hizk

**Comment by Slamm21** [comment]
Please provide your gear you use to nuke, without that this bug report does not show anything

**Comment by AbsoluteXzeroX** [comment]
Thunder staff
Bugard strap+1
millefleurs sachet
demon helm
black neckerchief
moldavite earring
cunning earring
igquira weski
wizard's gloves
diamond ringx2
rainbow cape
penitent's rope
errant slops
yigit crackows

1 burst 2 merit
no other merits

![gear](https://user-images.githubusercontent.com/26514268/109725556-16070d00-7b90-11eb-98a6-7f990793e680.png)

**Comment by Slamm21** [comment]
Then yeah everything is fine, the 25% is applying.
The guy in the video just has better gear, novio, z mitts etc
this is why his burst 2 does 1,595 and yours did 1457
25% extra would make it do 1,821 which is way too high
