### ISSUE TITLE
Crying Over Onions Quest Bugged.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#411]
I completed this quest in Windurst, got the reward, the Star Necklace. But it still says I have not completed the quest in my log which makes it impossible to start the next quest in the chain which is "Wild Card".

**Comment by Aenge** [comment]
@Serephim 

Note that after you receive the star necklace, the quest is not completed. After getting the necklace, you then need to talk to Kohlo-Lakola, and finally return to Honoi-Gomoi to complete the quest. Have you done that?

**Comment by godmode** [comment]
@Serephim let us know if this issue hasn't been resolved. Closing for now.
