### ISSUE TITLE
Castle Zvahl Bailey monster agro through wall and elevated terrain.

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#4110]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
1st  : I don't know if it was doing it before but I was resting on the drop plate at 1 of the 4 holes, a bit in the inside. I ended up linking the whole bottom floor.

2st : At the 4 room with nm's I was on the lower ground killing Ahrimans and I got agro from elevated platform Demons.

3st : I don't know the real behavior the monster should have but by pulling one NM It should be expected to go down directly, but the pathing that happen is that it does link a bunch of demon then cut straight through the wall in tunnel.

**Comment by 59blargedy** [comment]
i havent been able to replicate these issues, so am assuming they were resolved by follow-up tweaks that occurred around this patch. can let me know if you're still seeing.
