### ISSUE TITLE
Korroloka Tunnel Aggro Issues w/ new update

### ISSUE THREAD

**Issue by MasonOl** [EdenServer/community#4111]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

When you go to Korroloka Tunnel over the bridge on the second floor, you aggro mobs such as the Gigas and the Jelly and the Giant Spiders. Prior to the latest patch, this did not happen.

1. Enter Korroloka Tunnel.
2. Go to the left side to head to the second floor.
3. Cross the bridge between the left and right side on a character eligible to receive aggro.
Client version is 30181205_0

**Comment by 59blargedy** [comment]
validated that this is correct retail behavior, so closing ticket
