### ISSUE TITLE
Tin Bullet appears to be OOE

### ISSUE THREAD

**Issue by Spiffly** [EdenServer/community#4113]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Quote from this page: http://www.playonline.com/pcd/verup/ff11us/detail/4377/detail.html

* New synthesis recipes have been added.

On it's retail wikipedia history it only has it's first entry in 2009: https://ffxiclopedia.fandom.com/wiki/Tin_Bullet?action=history

Item is currently craftable on Eden as it has an AH history.

**Comment by SleazyFFXI** [comment]
Have you tried crafting it before making a bug report?   How about looking at said AH history which is from 2019

**Comment by Spiffly** [comment]
![tin bullets](https://user-images.githubusercontent.com/59734926/110042553-d8e07d80-7d3d-11eb-98bf-172a8b6b770b.png)

Is currently craftable on Eden.

**Comment by 59blargedy** [comment]
resolved with the April 5, 2021 update
