### ISSUE TITLE
Abuseable terrain in Tahrongi Cayon

### ISSUE THREAD

**Issue by Spiffly** [EdenServer/community#4117]
![Tttt_2021 03 05_143914](https://user-images.githubusercontent.com/59734926/110144408-37563c00-7dd0-11eb-9bed-a96ecce6c2e5.png)
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

This is a bit of a strange one. I was fighting Wild Dhalmels in Tahrongi Canyon, specifically the one that pops around where I-8 and J-8 meet. It's the first Dhalmel you run into when approaching from Buburimu Penisula. It somehow became stuck on what i presume was the terrain/navmesh? and refused to close the distance to me. If i was within 4 yalms of the mob, it would attack but if i crept out to 4.1+ we would both just stand there, neither attacking, as shown in the screenshot. I was able to make the mob move again by moving further away than 5 yalms.

It sounds a little petty i must admit but with the recent navmesh changes (possibly related?) and the fact that i could have moved into this little space and /ra the mob down without fear of attack made me report it. I plan to farm these dhalmels in the near future so i will report if i find any repeatable steps with this.

Not logged in currently but /ver is Eden's. Never had any other version installed on this laptop.

**Comment by Spiffly** [comment]
So i have done some more testing of this and it's easily abuseable. You need to be fighting mobs on hilly terrain. Manouvre them so they have the high ground and edge away. It doesn't take long to get them 'stuck' and as long as you don't move yourself too far away, they will just stand there and not auto-attack. Mobs are stilll able to target the player with TP attacks while 'stuck' however.

I tested this on multiple mobs and i was able to replicate it on them all. Also attached another screenshot to demonstrate a ranged attacks onto a mob and it taking no action on me between them.
![Tttt_2021 03 05_203313](https://user-images.githubusercontent.com/59734926/110171244-5dd99e80-7df3-11eb-979f-a5c2ea983370.png)


Ver: 30181205_0

**Comment by GiichiHiro** [comment]
I can second this.  I was in Pso'Xja doing https://ffxiclopedia.fandom.com/wiki/A_Reputation_in_Ruins  Fighting the gargoyles. During the second set of them, I must have positioned myself in such a way on the stairs that 1 of them just stopped auto attacking.  I was elevated above them in this case. He still did TP and casted spells.

**Comment by InoUno** [comment]
Resolved with March 8th, 2021 patch.
