### ISSUE TITLE
Trick Attack not functional on Adventuring Fellow

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4118]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Supposed to be able to Trick Attack your fellow per wiki as mentioned here - #1797. In that bug report it says that party actions work on them now, however Trick Attack doesn't seem to work still.

**Comment by KnowOne134** [comment]
Corrected 6/11/2022 update
