### ISSUE TITLE
Death during CS in Pso'Xja for CoP 5-3

### ISSUE THREAD

**Issue by EdenPenance** [EdenServer/community#4119]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

30181205_0

Player died during the cutscene for CoP 5-3 (Tenzen's Path). 
![image](https://user-images.githubusercontent.com/76273942/110227981-fa1ea680-7ec2-11eb-95ad-465cc19e7c74.png)
![image](https://user-images.githubusercontent.com/76273942/110227982-fe4ac400-7ec2-11eb-9b37-d232ab2f14f8.png)

Verified via test server that starting the cutscene does not drop aggro nor prevent aggro throughout it.
Door ID = 16814523
File for it is /scripts/zones/PsoXja/npcs/_09h.lua

**Comment by 59blargedy** [comment]
resolved in March 8, 2021 update
