### ISSUE TITLE
San d'Oria 7-2 Wyvern Should Not Need To Be Defeated

### ISSUE THREAD

**Issue by faivruit** [EdenServer/community#4120]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
In the mission "The Secret Weapon" (San d'Oria 7-2), you have to fight some orcs, warmachines, and a drg orc's wyvern. You should not need to kill the wyvern to win. I killed everything else, but the fight was not won until I also killed the wyvern.

Source: https://ffxiclopedia.fandom.com/wiki/The_Secret_Weapon?oldid=723505
_Confirmed you do not have to kill the wyvern to win_

ver: 30181205_0

**Comment by 59blargedy** [comment]
resolved in March 8, 2021 update
