### ISSUE TITLE
Unable to use Sic pet command as BST with Aht Urhgan Attercop as a pet

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#4122]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

1) Charm an Aht Urhgan Attercop as BST in Wajaom Woodlands.
2) Fight another monster with it for it to gain TP. (I used petinfo addon to make sure it was at 1000+ TP)
3) Use Sic out of the menu or macro when the Aht Urhgan Attercop has 1000+ TP and is engaged to another monster.
4) "Unable to use Job Ability."
5) I repeated to process with a Lesser Colibri of the same level and sic worked properly with that mob. 

ver: 30181205_0

**Comment by 59blargedy** [comment]
resolved in the March 15, 2021 update
