### ISSUE TITLE
Wild Card not refreshing 2Hs unless you change equipment/zone

### ISSUE THREAD

**Issue by linceed** [EdenServer/community#4124]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

30181205_0 version

Corsair's 2H ability Corsair's Roll, doesn't refresh other party member's 2H unless they zone, making this one of the most brutal bugs in combat.

**Comment by 59blargedy** [comment]
hmm, we reset them all the time in combat. may require an equip change (which is still wrong) but don't need to zone. Make sure folks arent just relying on their timers to tell them.

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
