### ISSUE TITLE
SAM AF2 Quest Issue after resetting AF memory

### ISSUE THREAD

**Issue by ArsinoeX** [EdenServer/community#4125]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Upon resetting my SAM AF memory, I experienced a problem with the AF2 quest "Yomi Okuri." The quest indicates that you must speak to an NPC named Washu and she will request 4 items you must trade her for a key item. However, she would not accept the traded items and did not progress the quest further. This key item is required to spawn an NM later in the quest line.

If you are experiencing this problem, there is somewhat of a work-around with it. If you have a friend who is also on the same quest and they are able to receive the "Washu's Tasty Wurst" key item, they can spawn the NM for you and both can receive the second key item "Yomotsu Feather." This should allow you to finish the quest.

Thanks for the help!

**Client Version**: /ver 30181205_0

**Comment by 59blargedy** [comment]
resolved in the March 29, 2021 update
