### ISSUE TITLE
Navmesh Issue - Plagues Bats in King Ranperre's Tomb

### ISSUE THREAD

**Issue by Spiffly** [EdenServer/community#4126]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

This bug is the already known navmesh bug where mobs aggro through floors/walls where they should not. Reporting as i can't find any instances of this particular one being reported before. Plague bats will aggro from above when engaging wind bats/grave bats in the location highlighted on the map attached.

Ver: 30181205_0
![KRT bats](https://user-images.githubusercontent.com/59734926/110391104-e4de7f00-805e-11eb-80ce-bcbee114c823.png)

**Comment by hehelolxd69** [comment]
EXCElent
