### ISSUE TITLE
Range Attack bug

### ISSUE THREAD

**Issue by BladesEnd22** [EdenServer/community#416]
When I use a Range Attack my sings instead of drawing his bow it still does damage but the Animation isn't correct

**Comment by beauxq** [comment]
Did you have /lockstyle on?
What specific weapon was it?

**Comment by gweivyth** [comment]
This is an issue with /lockstyle.  Turn your /lockstyle off and then turn it back on. 

This bug also makes it so that your ranged attacks do not apply on-hit abilities.  (Bloody/Acid/Holy Bolts, etc.)

**Comment by BladesEnd22** [comment]
how do I turn lock style off

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 6, 2018 at 8:59 AM, gweivyth<notifications@github.com> wrote:   
This is an issue with /lockstyle. Turn your /lockstyle off and then turn it back on.

This bug also makes it so that your ranged attacks do not apply on-hit abilities. (Bloody/Acid/Holy Bolts, etc.)
