### ISSUE TITLE
Taxim NM 

### ISSUE THREAD

**Issue by Howland11** [EdenServer/community#4168]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Recently I’ve been killing this NM on bst and noticed it keeps casting Stone V Sleepga 2 and Aeroga 3 wiki has a list of spells he casts and none of these are listed. 

Went back and further read the log he cast 
Freeze, Stone V, Aeroga 3, sleep 2, sleepga 2 
Aero 4 and Quake

**Comment by 59blargedy** [comment]
just half afked/fought him in retail for an hour he has far more spells than wiki lists, saw burst, sleepgas, sleep, grav, bind, poisonga2, all the blm ele dots, aero iv, drain, aspir, thundaga 3 etc,
for a while he seemed to favor certain spells which is something to look into for all nms/mobs in terms of spell weighting, but for this particular issue i think his current spell list is ok except perhaps stone v
