### ISSUE TITLE
Unable To Flag "Hat in Hand" Quest 

### ISSUE THREAD

**Issue by SaveTheSunF1R3x** [EdenServer/community#417]
Quest is unable to be flagged. I believe this is an "of era" quest according to the dates listed on the quests Zam page: http://ffxi.allakhazam.com/db/quests.html?fquest=1

**Comment by dsriker** [comment]
the NPC dosen't respond at all.

**Comment by Shoruto** [comment]
This is confirmed a during era quest and should be active.

https://ffxiclopedia.fandom.com/wiki/Hat_in_Hand?oldid=340441
http://ffxi.allakhazam.com/wiki.html?p=FFXI_QUEST:Hat_in_Hand&oldid=2325

Post with during era date
http://ffxi.allakhazam.com/wiki.html?p=FFXI_QUEST:Hat_in_Hand&oldid=2325
