### ISSUE TITLE
Ghrah Should close to melee range at 100% hp

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4170]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Since this monday's patch(3/8) that changed Ghrah to blm AI they only come into melee range below 65% hp. They should always melee

9:55 on this video the person aggros a ghrah and it melees: https://www.youtube.com/watch?v=jTAjJxbJpP8

/ver: 30181205_0

**Comment by 59blargedy** [comment]
resolved in the March 15, 2021 update
