### ISSUE TITLE
Xzomit mobs don't have the mother/child relationship, other incorrect functionality

### ISSUE THREAD

**Issue by GiichiHiro** [EdenServer/community#4171]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)

### Details

Xzomit mobs don't seem to be set up quite correctly in a lot of aspects.

In groupings, there should be a larger "mom" Xzomit, that the children will follow. 
These moms would be Aspirable.
Large Xzomits do not link; small Xzomits only link to their original mother Xzomit.

They should also wander a lot more than they currently do, since they're all grouping and static moving.

It LOOKS like there's a "Mom" mob spawning nearby to some groups, but doesn't have these characteristics set up.

https://youtu.be/k_9wyql_ytA?t=91

https://youtu.be/j9tGWPzX1bQ?t=301

Some video evidence.

Some wiki info for how they function: https://ffxiclopedia.fandom.com/wiki/Category:Xzomit

**Comment by KnowOne134** [comment]
Related to
https://github.com/EdenServer/community/issues/2292

**Comment by Slamm1eden** [comment]
![1614796326241](https://user-images.githubusercontent.com/80293027/110677894-200fb800-81ef-11eb-9db4-27cb27d0c824.jpg)
i had the same issue

**Comment by KnowOne134** [comment]
retail behavior on the roaming is they never stop, always moving

**Comment by 59blargedy** [comment]
mostly resolved in November 21, 2022 update. will put up new report for remaining issues
