### ISSUE TITLE
Macuillie (Smithing NPC NSandy)- doesn't offer Sheeting Key Item.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#418]
Currently Journeyman rank and the item is not in my possession.  The item is supposed to be offered at Novice+ for 10k guild points.

[2007 wiki link](https://ffxiclopedia.fandom.com/wiki/Sheeting?oldid=267257)

Edit: Went to buy chainwork and instead the NPC gave me sheeting.  
![image](https://user-images.githubusercontent.com/41595732/49595060-36aa7300-f945-11e8-8c0e-d3ebe5e4f9d0.png)

**Comment by Lilswitche** [comment]
To follow up on this issue - the smithing npc from Bastok at first glance appears to working correctly.

**Comment by KnowOne134** [comment]
fixed in next update
