### ISSUE TITLE
Orc weaponskill 'Aerial Wheel' is displaying Japanese text

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#42]
Observed in West Ronfaure, unsure if it's only these Orcish Fodders or all orcs that can use this skill that have this problem.

Client updated from Kupo.

**Comment by Wiggo32** [comment]
I've observed this behavior on certain mobskills on retail, it may be a client based issue. I will get more research.

**Comment by godmode** [comment]
Wiggo, I confirmed it does give that animation. It's using animation id `349` right now. Capture time? >:)

**Comment by Wiggo32** [comment]
This can be fixed by updating the client version
