### ISSUE TITLE
Citipati (And other undead) are alive during the day.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#421]
Screenshot attached.  See time on the bottom of the screen. 

![image](https://user-images.githubusercontent.com/37130689/49617636-6a0bf280-f983-11e8-8432-f67c08d4ce2c.png)

**Comment by icariumkupo** [comment]
Duplicate of #125

**Comment by godmode** [comment]
Is this still happening?

**Comment by Aneyus** [comment]
I believe this particular issue should be resolved.
