### ISSUE TITLE
The Wisdom of Elders

### ISSUE THREAD

**Issue by Tobalito** [EdenServer/community#422]
THis quest seems to be bugged and will not start. Cant obtain Travelers Hat

**Comment by bkesecker** [comment]
Successfully completed recently.  Suggest closing.

**Comment by godmode** [comment]
Please comment with more information including fame level if you’re still unable to begin this quest.

**Comment by Althaia** [comment]
I know this is a closed issue, but I have more information.

So here's the thing, I have a Bastok alt with plenty of fame who just cannot flag this quest.

I was, however, able to complete this quest on my main upon zoning into Bastok and going straight to the quest NPC to do this quest first (I pre-farmed the Bastok fame).

So for my Bastok alt, I had run around just talking to random NPCs. Someone suggested, therefore, that one of my other open quests was blocking this quest from starting.

Keeping that in mind, I closed out all my Bastok quests on my alt except one:

The Curse Collector (Zon-Fobun - Bastok Markets (G-5)). This requires a trip to Beadeaux and that's of course way too much trouble to ever do on an alt.

I still couldn't flag this quest on my alt after doing all that.

Therefore, it is my belief that having The Curse Collector flagged prevents The Wisdom of the Elders from starting.
