### ISSUE TITLE
King Vinegarroon Draw-in 

### ISSUE THREAD

**Issue by EdenPenance** [EdenServer/community#4232]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Split from #3514 due to grouped bug reports.
30181205_0

There's a difference in how KV uses Draw-In, it appears to have:
Alliance Draw-In
Single target Draw-In
Boundary target Draw-In

Boundary target Draw-In isn't followed by a TP move at all. It's only used if the main target is over 12' away from KV (doesn't always activate when the target is far away, more testing is needed) or attempting to leave the boundary. This shouldn't be confused with Single target Draw-In, it happened when Critical Bite knocked me back over 13'. At 3:51 (Highlights video) Yet, another time it landed, it didn't reset the targets enmity. At 3:22 (24min video)

Highlights video: https://www.youtube.com/watch?v=SV4tQZbwzME
24 min video: https://www.youtube.com/watch?v=UZZDwYNVgUo

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update except for boundary draw in, which is a missing mechanic for a bunch of nms and differs from tether. will post a new ticket for it.
