### ISSUE TITLE
King Vinegarron TP Move Verification

### ISSUE THREAD

**Issue by EdenPenance** [EdenServer/community#4233]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Split from #3514 due to grouped bug reports. Removed TP issues from 3514 if they work correctly here. 
30181205_0

Earthbreaker is absorbed by 1-3 shadows or can miss. - **Currently wipes shadows and gives stun, no matter shadow count.**
Critical Bite is absorbed by a single shadow or can miss. Although if it lands, it has a chance to reset the targets enmity. At 5:53 (24min video) It also has an added effect of Bind. - **Currently does not give Bind.**

24 min video: https://www.youtube.com/watch?v=UZZDwYNVgUo

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
