### ISSUE TITLE
Tiamat appears to gain TP from her attacks made while in air

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#4237]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Recently when fighting tiamat she has been using TP while in the air despite no outside TP feed from spells.  The only dmg being dealt to her is via Diabolos' Nether Blast.  Since she is flying she cannot be hit by melee from using assault w/ diabolos to get into range.

This leads me to be believe she is incorrectly generating TP from hitting with her fire-based air attack.  Either that or she has regain again.

**Comment by 59blargedy** [comment]
i cant really find any confirming info on whether or not tiamat is supposed to gain tp in the air or not. do you have any information to support or is this based on memory?

**Comment by roriffxi** [comment]
I was going off reports that were sent to me.  When I looked into it, it does appear that Tiamat gains TP from her attacks in air.

**Comment by 59blargedy** [comment]
gotcha, sounds good thank you
dowzer was on retail testing it out earlier today, so posting vids as proof if it comes up again
https://www.youtube.com/watch?v=58az7_emaS8
https://www.youtube.com/watch?v=424nLA_5d78
