### ISSUE TITLE
Mythril Ring +1 (13519) has no desynth

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4239]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver = 30181205_0

Based on current wiki (https://ffxiclopedia.fandom.com/wiki/Mythril_Ring_%2B1) it should be NQ = 1 Mythril Ingot (653), HQ1 = 1 ingot, HQ2 = 2 ingots. Backdated wiki has desynth as "Unknown".

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
