### ISSUE TITLE
You can send R/E equipment to other characters on your account

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#424]
This is a change that was made in retail that let R/E equipment be shared among characters on the same account.

It's not Era so I'm reporting it for a decision to be made.

**Comment by roriffxi** [comment]
I can almost guarantee people are using it to give themselves nation rings to nations they arent members of.  If you care to look into it.

**Comment by godmode** [comment]
Yeah, those rings will probably just be removed when it comes time. Thanks!
