### ISSUE TITLE
Experience Bonus Rings OOE Cooldown

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#4240]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
ver 30181205_0
### Details
you can see here
https://ffxiclopedia.fandom.com/wiki/Empress_Band?oldid=288360#Additional_Information
(ignore the image)
<7/7 0:15/[16:00:00, 0:15]>

In Era the cooldown was 16 hours per charge for chariot, empress and emperor band
This is a nice QoL change we currently have imo, but recording this as it is technically OOE

**Comment by roriffxi** [comment]
https://github.com/EdenServer/community/issues/1153
