### ISSUE TITLE
Dosetsu Tree NM applying weird effects

### ISSUE THREAD

**Issue by GiichiHiro** [EdenServer/community#4241]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

Fought Dosetsu Tree NM the other day, and every time it used Pinecone Bomb, it applied a weird additional effect.  Which was funny, but seemed otherwise harmless.

![copyimage](https://user-images.githubusercontent.com/66037286/111530074-a3765f80-8741-11eb-90d1-bbafc9bc9366.PNG)
![lastresort](https://user-images.githubusercontent.com/66037286/111530081-a4a78c80-8741-11eb-9584-72e687c84e91.PNG)

**Comment by InoUno** [comment]
Resolved in March 22nd, 2021 update.
