### ISSUE TITLE
Hasso / Seigan Casting Delay currently additional 100% casting time

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#4243]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

In era Hasso/Seigan are supposed to add an additional 50% delay to the casting time and recast of magic, songs and ninjutsu. Currently both are treating recast correctly, but have casting times set to an additional 100% rather than the 50% it should be.

https://www.bg-wiki.com/index.php?title=Seigan&oldid=1690
https://classicffxi.fandom.com/wiki/Seigan
https://classicffxi.fandom.com/wiki/Hasso

RudeJerk confirming they are set to the wrong value currently:
https://discord.com/channels/482610771126386688/670753652818051092/821982836398751755

"uwu"

**Comment by rude-jerk** [comment]
Resolved on March 22, 2021 patch.
