### ISSUE TITLE
Fishing up Hippogryphs instead of normal monsters in Batallia

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4244]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

![Capture](https://user-images.githubusercontent.com/55296729/111626303-335ced80-87c4-11eb-8318-4759246ffdbc.PNG)

Me and Miah both saw this fish as a Hippogryph. It didn't live long enough to use a tp move so no idea if it was a graphical bug or what. 

I don't have any .dat swaps for monster models

/ver: 30181205_0

**Comment by falzum** [comment]
This does use hippogryph tp moves

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
