### ISSUE TITLE
Multi-hit ws doing too much damage / return too much tp on critical HP targets

### ISSUE THREAD

**Issue by ReeceR09** [EdenServer/community#4245]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Posted on behalf of Falzum/Starby

Right now if you use a multi hit weaponskill like Raging Rush, Guillotine, Pentathrust etc you will do full damage and get tp for all hit that connect

Multi hit weaponskills should check after each swing if the mob is dead, then stop dealing extra damage and stop giving tp.

If I use a multi hit on a target with 1hp, only one hit of my ws should do damage and return tp.

Some video examples from era
2:48 Weak Enpi with low tp return: https://www.youtube.com/watch?v=ni1KieaVMNc
4:15 Full tp return with normal damage

3:20 PLD is getting 7tp per swing, gets an 8tp return on ws because 2nd hit killed the imp: https://www.youtube.com/watch?v=ni1KieaVMNc

2:30 THF kills mob with SA Viper Bite for 4tp return, which is just the main hand hit: https://www.youtube.com/watch?v=ni1KieaVMNc&ab_channel=fatalbiohazard

**Comment by rude-jerk** [comment]
Resolved in May 31, 2021 update

**Comment by E5una** [comment]
I think there may be a defect here, several people are reporting that their level 75 characters are frequently leaving low level (20-30ish) level monsters alive with their multi hits like dancing edge or asuran fists and only dealing a small amount of damage if the monster is low health. Example, someone using DE on a 2% skeleton and having it live at 1%.

Appollo/Artemmis just went and did two tests in Gusgen with Dancing Edge as a 75 THF on a level 20 Ghoul and said both times they only hit the first hit only and the ghoul was left with very little HP.
