### ISSUE TITLE
Skillchain should not go off if the mob dies from WS damage

### ISSUE THREAD

**Issue by ghost** [EdenServer/community#4246]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

Posted on behalf of Falzum/Starby

Current Eden behavior is if you kill something with a ws, even if the enemy has 0 hp, the skillchain still goes off. 

Here's an example of a 2 party light skillchain Fragmentation -> Kasha should end in Light, which fails because the imp died to the Kasha damage

3 part light skillchain at 2:50 https://www.youtube.com/watch?v=7OOhB7evsWE

/ver: 30181205_0

**Comment by Mozzy4Ever** [comment]
Currently on Eden if the WS killed the mob, the skillchain will go off but it'll do 0 damage

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch

**Comment by statuseffect** [comment]
Still occurs if a bloodpact is the closer of a WS
