### ISSUE TITLE
HQ Rusty Pick synth not making War Pick +1

### ISSUE THREAD

**Issue by Far-The-Killer** [EdenServer/community#4250]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
When using a light crystal + rusty pick synth for War Picks.  HQ synthesis results do not result in War Pick +1
https://classicffxi.fandom.com/wiki/War_Pick

**Comment by 59blargedy** [comment]
as part of rmt changes in october 4, 2021, the recipe for this has now changed
