### ISSUE TITLE
BRD songs getting buff from fishing rod equipped

### ISSUE THREAD

**Issue by itstheaquinn** [EdenServer/community#4252]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

It was brought to my attention by Guitarmacist on discord that BRD songs are receiving a buff when a fishing rod is equipped. He provided his testing on his Elvaan BLM30/BRD15 (/BRD skills: capped 44 Singing, capped 44 String, and uncapped 39 Wind):

On /BRD, only Singing skill should be considered for song potency. Fishing rods appear to be including String and/or Wind instrument in the potency calculation. Army's Paeon restores the expected amount (2HP/tick) with Halcyon rod equipped. Therefore it is assumed to not be a "+Song" tier.

**No songs: 80 acc, 88 attack**
Minuet: 80 acc, 99 attack (+11 attack)
Madrigal: 85 acc, 88 attack (+5 acc)

**Crayfish ball equipped, no Range**
Minuet: 80 acc, 99 attack (+11 attack)
Madrigal: 85 acc, 88 attack (+5 acc)

**Halcyon rod equipped, no Ammo**
Minuet: 80 acc, 104 attack (+16 attack)
Madrigal: 95 acc, 88 attack (+15 acc)

**Halcyon rod + Crayfish ball equipped**
Minuet: 80 acc, 104 attack (+16 attack)
Madrigal: 95 acc, 88 attack (+15 acc)

**Clothespole equipped, no Ammo**
Minuet: 80 acc, 104 attack (+16 attack)
Madrigal: 95 acc, 88 attack (+15 acc)

**Animator equipped, no Ammo**
Minuet: 80 acc, 99 attack (+11 attack)
Madrigal: 85 acc, 88 attack (+5 acc)

### I then went ahead and tested this on my BRD75/BLM37 with capped skills (Singing240, String233, Wind237):

**No songs**
Attack: 59
Accuracy: 65

**No Ranged or Ammo equipped**
Minuet IV: 91 Attack
Blade Madrigal: 80 Accuracy

**Cornette +1 (Minuet +2 wind instrument) equipped**
Minuet IV: 125 Attack

**Traversiere +1 (Madrigal +2 wind instrument) equipped**
Blade Madrigal: 97 Accuracy

**Composite Fishing Rod equipped**
Minuet IV: 120 Attack
Blade Madrigal: 95 Accuracy

Version: 30181205_0

**Comment by 59blargedy** [comment]
resolved in the March 29, 2021 update
