### ISSUE TITLE
Changing Weapons Resets Weapon Delay

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#4253]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

On retail when you change weapons your delay isn't reset ; you can swap sword > staff > sword ; or staff > sword > staff and experience minimal delays when swapping. 

On Eden when if you swap weapons to cast , on engaging, etc. you experience a massive delay -- I THINK it's taking the full delay of your old weapon + new ; but unsure. I just know comparatively the Eden delay is significantly longer in side by side videos showing the same swap.

Retail : 
https://www.dropbox.com/s/cjbkwg29zqczht0/2021-03-23%2011-58-42.mp4?dl=0

Eden Test : 
https://www.dropbox.com/s/z1uts76mhxeux6u/2021-03-23%2012-03-13.mp4?dl=0

This is probably tangentially related to #3509 ; and it just appears weapon delay can be wonky in general.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
