### ISSUE TITLE
The second group of Merits for Summoner do not seem to be functioning correctly

### ISSUE THREAD

**Issue by ReeceR09** [EdenServer/community#4254]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
I did not find anything relating to this issue.

- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

Reporting on behalf of Grim/Buffy.
 
Issue: The second group of Merits for Summoner do not seem to be functioning correctly (specifically Grand Fall Blood Pact, Leviathan). The damage is supposed to scale with TP. Each additional merit increases the TP bonus for said Blood Pact, but it appears to either be broken or not correctly adding the TP bonus.

Both of my characters, Grim and Buffy, are level 75 SMNs with the same exact gear, skills, merits (with the exception of Grand Fall). Grim has 5/5 merits into Grand Fall, while Buffy only has 1/5 merits into Grand Fall. I've tested the Bloodpact several times on some Huge Hornets out in South Gustaberg. The results were the same for both Grim and Buffy, Grand Fall was hitting for consistent 880s despite the difference in Grand Fall Merits.

My Client version is: version 30181205_0

If there is anymore information I need to provide, please let me know!

**Comment by 59blargedy** [comment]
resolved the grand fall issue March 29, 2021, however noted that the merits above 1 do not add value at 0 tp like they should, so closing this and making a new bug report
