### ISSUE TITLE
Incorrect minimum recast time

### ISSUE THREAD

**Issue by AcornFFXI** [EdenServer/community#4255]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

"era" recast reduction should cap at 50%, but it looks like eden may be using the current retail cap of 80%.

Steps:
- Get a lot of haste
- cast utsusemi ni
- observe recast timer

ver 30181205_0

**Comment by InoUno** [comment]
Changed cap in March 29th, 2021 update.
