### ISSUE TITLE
Relic additional damage procs when it shouldn't

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#4256]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

Currently the relic damage procs (the 2x-3x damage ones specifically) work on:
Double Attack
Triple Attack
Kick Attacks
Offhand hits with Spharai

None of these should be eligible for relic procs.

According to bgwiki on Spharai (and every other weapon has a similar excerpt except the damage/proc rate changes):
Hidden Effect: Does Triple Damage on the first main-hand swing of an attack round 5% of the time.
Will never activate on hits from Double Attack, Triple Attack, etc.

**Comment by 59blargedy** [comment]
this was resolved in a previous update
