### ISSUE TITLE
Chat log issues - buffs and debuffs

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#4257]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
1) The caster should be able to see chat log messages when buffs they've cast have worn, if the recipient of buffs remains in range of the caster and regardless of if the recipient is in the same party as the caster.
2) Debuff wearing messages should only be visible to the caster of the debuff.
will update with additional detail/expected behavior via screenshots/vid

**Comment by InoUno** [comment]
Resolved in April 12th, 2021 update.
