### ISSUE TITLE
Cerberus missing additional damage increase as hp lowers from spirits within, chi blast, nether blast

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#4259]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Nether Blast, Spirits Within and Chi Blast should deal additional damage to the Cerberus family of mobs as the mob targets HP lowers 

Source: https://www.bluegartr.com/threads/108197-Random-Facts-Thread-Abilities?p=5412576&viewfull=1#post5412576

**Comment by dowzer** [comment]
I was testing these abilities on Cerberus and I'm left with a few more questions now. 

https://www.youtube.com/watch?v=j5IZ92HYtcY

Nether Blast damage weakened as HP lowered. 
13054 @ 99%
9028 @ 75%
7935 @ 57%
6493 @ 39%
5444 @ 23%

Spirit's Within was unusual, I couldn't recreate the damage each time I warped. It might have been an error I made, I'm not sure.

In the first video, damage was only slightly lowered. I went back to get a 3000TP @ 100% HP baseline and it landed for 6236. Then it was obvious: 5531, 4931, 4391, 4030, 3739, 3546. 

I went back again and recorded it: 3818 @ 100%, 3607, 3238, 3172... until 2080 @ 11%. 
Not sure why damage fluctuated so much:
https://www.youtube.com/watch?v=fYtV48uwUXk

Chi Blast increased damage as HP lowered. 
126 @ 100%
218 @72%
289 @ 25%
289 @ 10%

Hand to hand did the exact opposite, drastically - at 100% I engaged for 633, 792, 754, 698. By the time it was around 11% HP I was hitting 2 digit numbers 28 crit, 28 crit, 21 non crit.

**Comment by 59blargedy** [comment]
interesting and im not sure what to make of it either lol. it's clear there's some sort of interaction but having it be the opposite of what people mentioned is confusing.

what's your baseline netherblast on a lvl 1 mob/what is your total pet mab gear? if you see him up again sometime, may be easier to compare values without 119 gear as it has strange damage interactions with netherblast.

now i wonder if that guy in the thread was wrong and the bonus was based on moonphase like fenrir, in so much that you hit it on opposite day lol.

**Comment by Lilswitche** [comment]
Rori documented this mechanic a couple years ago when we were investigating Cerb/Khim/Hydra: it's a floating damage modifier that changes based on the damage type of the damage being done to Cerberus.

For example, if you do mostly physical damage then physical damage begins diminishing and magic damage increases, or vice versa.  If you switch up the damage type it sends sends the damage modification the ither way.

May want to reach out to him to see if he still has the videos of him demonstrating this.

**Comment by Lilswitche** [comment]
A little more research on this: [Retail Cerb video](https://youtu.be/omAdp99CfjU)

You can see at the start of the fight Cerberus is taking triple digit damage from auto-attacks and as the mob's HP decreases, it takes **significantly** lower physical damage (down from near 200 to 20's at low mob hp%).  It likely has a cap on how much additional % damage is boosted for the weakened damage type, as observed by Atonement/Spirits Within damage.

Also, here's a discussion on the Square-Enix forum with someone making the same observation I've noted above: [Link](https://forum.square-enix.com/ffxi/archive/index.php/t-34194.html?s=3105eb885f258163329434eb252f8263)

**Comment by 59blargedy** [comment]
Awesome, thanks for the info.

**Comment by dowzer** [comment]
That makes a lot more sense. I've seen that sort of seesaw mechanic before, I think in Delve. Someone killed Cerb on my server so I'll have to wait a few days.

Nether Blast set has MAB 246 (including job point gifts) and BP dmg 101. 9748 on two different Wild Rabbits in West Ron. Naked did 1236 twice as well.

**Comment by Lilswitche** [comment]
Napkin math for that video: seems like the damage reduction caps at about -95%. Almost seems relative to the amount of physical damage that was done to Cerberus. Cap for damage boost likely +50%. 

Of course this all needs to be tested as well as how much seesaw'ing there is.

**Comment by 59blargedy** [comment]
There was more to it than this. Boy was there more. Resolved in June 13, 2022 update.
