### ISSUE TITLE
Hydro Greataxe cannot be desynthed

### ISSUE THREAD

**Issue by Far-The-Killer** [EdenServer/community#4264]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Player: Xenz
Hydro Greataxe cannot be desynthed.Similar issue with Hydro Baghnakhs can't be desynthed.
Fire Crystal x1, Hydro Greataxe

https://classicffxi.fandom.com/wiki/Hydro_Axe

**Comment by 59blargedy** [comment]
resolved with April 26, 2021 update
