### ISSUE TITLE
Carol resistance increase not showing in equip screen

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4266]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Carols don't increase the "Elemental Resistance" values in the equipment screen. Checking on test server via !statcheck does show the increase to resistances, though.

**Comment by 59blargedy** [comment]
resolved in April 19, 2021 update
