### ISSUE TITLE
Rangers in Dyna-Windy not 2hring

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4268]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver  = 30181205_0

Yagudo Salvagers (Rangers) in Dynamis-Windurst don't 2hr. I'm not sure if this is an issue with the Yagudo Salvagers in Dyna-Beauc, but RNG mobs in other dyna zones still 2hr.

**Comment by 59blargedy** [comment]
resolved in April 19, 2021 update
