### ISSUE TITLE
Pso'Xja 40 cap elevator = death trap

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#427]
Today, while going to fight Diabolos, a party member stepped onto the elevator and instantly died despite having no aggro or any sort of dot, just lost all his hp and died.

He was a taru, if this was intentional.

**Comment by Slamm21** [comment]
there is also a level 80+ elemental down there

**Comment by godmode** [comment]
That shouldn’t be the case anymore. There was a separate bug report for it that is closed

**Comment by KnowOne134** [comment]
Can not reproduce
