### ISSUE TITLE
WAR AF Feet - Parasite Skin drop rate

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#4270]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
The current drop rate of parasite skin for WAR AF mission The Talekeeper's Truth from Yagudo Parasites appears to be off. 

https://ffxiclopedia.fandom.com/wiki/The_Talekeeper%27s_Truth?diff=prev&oldid=357236 - Implies you only have to kill one.
https://ffxiclopedia.fandom.com/wiki/Talk:Yagudo_Parasite - Player reporting that every time they killed 1, the skin dropped.
http://ffxidb.com/zones/151/yagudo-parasite - Shows high drop rate for Parasite Skin. I believe it doesn't show 100% because on retail if everybody in the party already has the RA/EX item, it won't drop.
https://ffxi.allakhazam.com/db/item.html?fitem=2648 (I know, LOLKhazam...) - "This is a 100% drop off each Yagudo Parasite, located in small pool at H-9 on floor 3."

Current ffxiclopedia has the drop rate at 24/32 which may be why it is not currently a 100% drop, but the above evidence suggests it should be.

**Comment by 59blargedy** [comment]
resolved with April 26, 2021 update

**Comment by erenik** [comment]
Needed like 40 kills with TH1 today to get it. I would consider re-opening this ticket.

**Comment by 59blargedy** [comment]
re-resolved in June 13, 2022 update
