### ISSUE TITLE
Xolotl missing spawn point variance

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#4272]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Xolotl currently spawns in the same spot every time.  should vary spawn points within the general area noted here:
![image](https://user-images.githubusercontent.com/52636208/113962732-42005880-97f6-11eb-96f1-b553e2d6e244.png)

**Comment by rude-jerk** [comment]
Resolved in May 10, 2021 update
