### ISSUE TITLE
convergence not increasing breath damage

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#4273]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
convergence is not currently increasing the magic damage of breath spells. will want to validate macc bonus as well

![image](https://user-images.githubusercontent.com/52636208/114078056-7ae01200-9876-11eb-994b-2ab23dc79be5.png)
https://ffxiclopedia.fandom.com/wiki/Heat_Breath
https://www.bg-wiki.com/ffxi/Convergence
https://ffxiclopedia.fandom.com/wiki/Convergence

**Comment by KnowOne134** [comment]
Corrected April 19 2021
