### ISSUE TITLE
Castle Oztraja trap door (first door w/ two handles) triggers too fast

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4279]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Something changed recently with the first trap door in Castle O with the handle on each side. You used to / should be able to stand in the middle, hit a lever, and immediately run backwards, but today it instantly dropped me. I talked to some other users in discord and they are reporting similar behavior, that it changed fairly recently and is too fast now.

Here is a retail video of what the delay should be like, timestamped:
https://youtu.be/hLJBi4AjD88?t=448

**Comment by rude-jerk** [comment]
Resolved in April 19, 2021 patch.
