### ISSUE TITLE
Your Crystal Ball: missing JP midnight wait

### ISSUE THREAD

**Issue by InoUno** [EdenServer/community#4282]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

From: Teitaka#6385

Quest: Your Crystal Ball

Bug: The part where you trade the "Ahriman lens" to the 'Rockwell' in Maze of Shakhrami should have a "Wait till Japanese Midnight" flag before being able to obtain the Divination Sphere. Currently you can obtain the Divination sphere immediately.

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
