### ISSUE TITLE
Rabbats in Dunes

### ISSUE THREAD

**Issue by InoUno** [EdenServer/community#4283]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

From: Teitaka#6385

Looks like after the recent Dunes rework that some monsters are either named incorrectly, or are in the wrong grouping:
![image](https://user-images.githubusercontent.com/774909/115320668-9a364380-a182-11eb-8369-0242a6449b52.png)

**Comment by 59blargedy** [comment]
resolved with April 26, 2021 update
