### ISSUE TITLE
Skillchain damage is printing the wrong amount when it heals

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4286]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

![image](https://user-images.githubusercontent.com/13668758/115881068-5c9f1800-a419-11eb-84d2-1d06e499096c.png)

Similar to the closed bugs with incorrect numbers printed when an additional effect or elemental WS heals a monster, the print is still off for skillchains healing monsters.

**Comment by E5una** [comment]
Related to https://github.com/EdenServer/community/issues/1340

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
