### ISSUE TITLE
SMN Spirits drop aggro on release

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4287]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Summoner Spirits doesn't always maintain claim. When releasing a spirit, sometimes a monster will go unclaimed, but not all the time. I'm not sure what causes this, but it has nothing to do with whether or not the spirit lands an attack vs. only missing + casting. I was able to make a monster go unclaimed in both cases.

Here is it going unclaimed after the spirit hits:
![image](https://user-images.githubusercontent.com/13668758/115893426-2916ba80-a426-11eb-9ff1-85be23610046.png)

Here is it going unclaimed after the spirit misses:
![image](https://user-images.githubusercontent.com/13668758/115893517-46e41f80-a426-11eb-83b6-74f7fe855850.png)

Here is two part screenshot of my Ice Spirit maintaining a claim:
![image](https://user-images.githubusercontent.com/13668758/115893726-8874ca80-a426-11eb-8d50-3d8747ab4399.png)
![image](https://user-images.githubusercontent.com/13668758/115893795-96c2e680-a426-11eb-8822-5b0876bcd9b6.png)

verrsion 30181205_0

**Comment by 59blargedy** [comment]
want to just tag on to the existing issue?
https://github.com/EdenServer/community/issues/3294

**Comment by E5una** [comment]
The difference _might_ be that if the monster hits the SMN once, you keep claim. I don't know if this is true, but that appears to be the difference in the screenshots.

**Comment by E5una** [comment]
Ugh 100% yes. I hate that sometimes I can't find a story despite 3 different searches because I'm using the wrong terminology =D

**Comment by E5una** [comment]
Closed as duplicate of #3294, thanks for pointing that out!
