### ISSUE TITLE
Monster Benediction does not remove all debuffs

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4288]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Monster benediction only removes erasable status debuffs but needs to remove all similar to player benediction (was fixed in the past on Eden)

Steps to reproduce:
1. Poison a WHM 2 hour using monster (Yagudo High Priest works)
2. Proc Benediction by getting them low health
3. Disengage and try to sleep.
4. Note that they are still poisoned and wake up immediately.

(It wore off on two because I used Venom Shell, AoE Poison, so I could see the "is poisoned" message)
![image](https://user-images.githubusercontent.com/13668758/115968096-0f4ba500-a504-11eb-8fcf-5d70dbaa7889.png)

version 30181205_0

**Comment by rude-jerk** [comment]
Resolved in May 10, 2021 update
