### ISSUE TITLE
Rogetsurin NMs - up every night

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#429]
https://ffxiclopedia.fandom.com/wiki/Bendigeit_Vran Should be Timed Spawn during Nighttime (between 17:00-5:00) only during a New Moon.

https://ffxiclopedia.fandom.com/wiki/Haty Spawns between 17:00-5:00 during a Full Moon once per night throughout the zone.

Right now, they're both up, every night.

**Comment by everlast101069** [comment]
Just camped both these mobs on both moon cycles and neither one seems to be popping. I'm not sure if Lumbering Lambert is messing with their pop cycles as he has been there both times but in their typical pop areas I have seen neither. I camped 5 cycles on full moon and so far 2 on new and neither NMs have popped.

**Comment by KnowOne134** [comment]
found no issue in the code
