### ISSUE TITLE
Wrong mob levels in LoO. 

### ISSUE THREAD

**Issue by ReeceR09** [EdenServer/community#4290]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

Posted on behalf of Ram.

Version - 30181205_0

Wrong mob levels in LoO (Goblin Leech). Should be as per this image: 

![image](https://user-images.githubusercontent.com/13455324/115990728-aecc6e80-a5bc-11eb-9f83-aaaf210e01fc.png)

But currently on Eden it is: 

![image](https://user-images.githubusercontent.com/13455324/115990748-cb68a680-a5bc-11eb-81bd-56d6a94cb314.png)

Thanks!

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
