### ISSUE TITLE
Certain NMs do not drop the era amount of gil

### ISSUE THREAD

**Issue by Axelution** [EdenServer/community#4291]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

![image](https://user-images.githubusercontent.com/72828303/116007175-4765ed00-a5c3-11eb-898b-1438a1c627c9.png)

Source: 2006-2007 blog posts via https://kruemel-shiva.livejournal.com/?skip=40

**Cerberus**
Live:
![image](https://user-images.githubusercontent.com/72828303/116004779-30220200-a5b9-11eb-8083-f3ade732e785.png)

Era:
![image](https://user-images.githubusercontent.com/72828303/116005112-69a73d00-a5ba-11eb-8507-0175154b0a4d.png)
![image](https://user-images.githubusercontent.com/72828303/116005173-9eb38f80-a5ba-11eb-9365-432483c2a16e.png)
![image](https://user-images.githubusercontent.com/72828303/116005278-1ed9f500-a5bb-11eb-8f8b-c9e366ef7101.png)
![image](https://user-images.githubusercontent.com/72828303/116005312-3ca75a00-a5bb-11eb-9f6b-a173eec57cda.png)
![image](https://user-images.githubusercontent.com/72828303/116005349-5e084600-a5bb-11eb-982b-e85f0be098d7.png)

___________________________________________________________________________

**Adamantoise/Aspidochelone**
Live:
![image](https://user-images.githubusercontent.com/72828303/116005434-b9d2cf00-a5bb-11eb-8a3c-d44ddfe30930.png)
![image](https://user-images.githubusercontent.com/72828303/116006296-79755000-a5bf-11eb-8944-15db983fb073.png)

Era: (split due to being in a party or alliance)
![image](https://user-images.githubusercontent.com/72828303/116007044-babb2f00-a5c2-11eb-9e18-bdd2a80683ca.png)
![image](https://user-images.githubusercontent.com/72828303/116004838-770ff780-a5b9-11eb-9940-b3d6b95b9446.png)
![image](https://user-images.githubusercontent.com/72828303/116005302-31542e80-a5bb-11eb-99c6-7ba269c78d14.png)
I'm guessing turtle is supposed to drop around 20k, like Behemoth

___________________________________________________________________________

**Khimaira**
Live:
![image](https://user-images.githubusercontent.com/72828303/116007009-91020800-a5c2-11eb-8a7f-29896d8f61f4.png)

Era:
![image](https://user-images.githubusercontent.com/72828303/116005040-2e0c7300-a5ba-11eb-81e4-0f80606ca334.png)
![image](https://user-images.githubusercontent.com/72828303/116005140-83e11b00-a5ba-11eb-9c66-f0657ffec628.png)

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
