### ISSUE TITLE
Behemoth/King Behemoth's Howl animation is incorrect

### ISSUE THREAD

**Issue by Axelution** [EdenServer/community#4292]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

on Eden, Behemoth does a smol growl followed by the warcry animation:

https://user-images.githubusercontent.com/72828303/116019205-8a8e8300-a5f8-11eb-8232-78a2708538d3.mp4

around era, Behemoth did a RAWR accompanied by some uplifting red rage lines

https://youtu.be/MrwtJfxke9o?t=41

![image](https://user-images.githubusercontent.com/72828303/116019422-05579e00-a5f9-11eb-8870-c0118f893ad6.png)

**Comment by 59blargedy** [comment]
resolved with April 26, 2021 update
