### ISSUE TITLE
Porphyrion Eagle Eye Shot is too strong

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4294]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Reporting on behalf of Tam, but I tested on the test server and Porphyrion's EES does appear to be too strong compared with wiki testimonials.

![image](https://user-images.githubusercontent.com/13668758/116110009-4dbb9e00-a683-11eb-93ab-8a7f0aa617d7.png)
 
Tam mentioned getting EES for 800 on 51 DRK. I'm not wearing the best gear, but I did cast protect to try to help a bit. EES averaged around 800 +/- 100. One crit me for 1928, which a bit more than double what I had been seeing, but probably just a lucky roll on a lucky shot.

![image](https://user-images.githubusercontent.com/13668758/116111369-96c02200-a684-11eb-8542-4eaefe32536a.png)

Wiki testimonials only list EES doing 200-400 on characters up to 15 levels lower than me.

https://ffxiclopedia.fandom.com/wiki/Talk:Porphyrion#Testimonials

I highlighted some of the ones from characters about the same level as me:

![image](https://user-images.githubusercontent.com/13668758/116110915-20232480-a684-11eb-95d8-483cb90c116b.png)

Note: Not sure if this is localized to Porphyrion or if it is all EES by mobs.

version 30181205_0

**Comment by Slamm21** [comment]
EES is too strong in general I believe, would be nice if anyone could get some numbers from mobs doing it in dynamis on retail too.

**Comment by 59blargedy** [comment]
increased damage from gigas EES specifically has been resolved May 10, 2021, though whether or not EES is too strong as is would require a separate report with clear proof
