### ISSUE TITLE
Somnolence is missing its MB properties (or SC?)

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4295]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

![image](https://user-images.githubusercontent.com/13668758/116168865-6c488600-a6d1-11eb-8ce7-9a9f201af5a3.png)

Somnolence doesn't seem to have its SC properties (modern wiki says it works in a skillchain https://ffxiclopedia.fandom.com/wiki/Somnolence), or its MB properties (era wiki suggests it MBs 
https://ffxiclopedia.fandom.com/wiki/Somnolence?oldid=262666).

What's odd is that if you look at the era page for Compression, it doesn't list Somnolence as being something that can MB there. 

That being said I did find this post where someone is saying an old page is wrong and that it is supposed to MB darkness:

https://ffxi.allakhazam.com/db/spell.html?ffspell=702

version 30181205_0

**Comment by E5una** [comment]
Found the JP wiki that references its magic bursting, if that's helpful:

http://wiki.ffo.jp/html/4108.html

A bit hard to tell some of the details through the google translate function, but I think its saying the damage is pretty mediocre without a MB and solid damage with one? Either way, it mentions that it can MB dark based SCs

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
