### ISSUE TITLE
Lamia no. 13 - charmed npcs should not regain health

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#4296]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
when charmed by the lamia, the npcs are currently regaining 10% health at the moment of charm, and should not be.

**Comment by KnowOne134** [comment]
resolved with May 10, 2021 update
