### ISSUE TITLE
Paralyze should proc on player ranged attacks

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4299]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Paralyze should proc on player ranged attacks and show no message in the log

2008 video proof(Skip to 1:50) https://www.youtube.com/watch?v=fF4ocntwVV0

2006 BG post talking about it https://cdn.discordapp.com/attachments/837451111422099458/837452385827815485/bluegartrpara_forum.jpg

Another post https://cdn.discordapp.com/attachments/837451111422099458/837485504651067402/Screenshot_2021-04-30-03-27-11-820_com.mi.globalbrowser.jpg

/ver 30181205_0

**Comment by rude-jerk** [comment]
Resolved in May 10, 2021 update
