### ISSUE TITLE
Tier 2 merits have out of era tweaks (OP)

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#430]
MANY of our tier 2 merits have out of era boosts attached to them that are relatively game breaking if utilized correctly. I have attached a link to the patch notes (Dated 3/26/12) and bolded all of the lines that tell what the merit did prior to this update. **Troubadour** (basically a free elemental seal) and **Feint** (_increased treasure hunter_) are absurdly overpowered just off the top of my head, but the others might be as well if you care to dig into them.

Patch notes (I couldn't be bothered to dig through SE archives but I can if you need the official one and don't believe this is accurate): https://www.bg-wiki.com/bg/Version_Update_(03/26/2012) 

The following job adjustments and refinements have been implemented:
_[dev1084] Warrior_
Warrior's Charge
Recast time has been reduced from fifteen minutes to five.
**Additional merit points will now increase the chance of a threefold attack by 5% per point.**

_[dev1087] White Mage_
Martyr
Recast time has been reduced from twenty minutes to ten.
**Additional merits no longer reduce casting time, but instead increase HP granted by 5% per point.**
Devotion
Recast time has been reduced from twenty minutes to ten.
**Additional merits no longer reduce casting time, but instead increase MP granted by 5% per point.**

_[dev1080] Thief_
Assassin's Charge
Recast time has been reduced from fifteen minutes to five.
**Additional merit points now increase the chance of a fourfold attack by 5% per merit point.**
Feint
Recast time has been reduced from ten minutes to two.
**Additional merit points no longer reduce recast time, but instead _raise the chance of Treasure Hunter leveling up by 25% per point._**

_[dev1085] Paladin_
Fealty
Recast time has been reduced from twenty minutes to ten.
**Additional merit points no longer reduce recast time, but instead extend duration by an additional five seconds per point.**
Chivalry
Recast time has been reduced from twenty minutes to ten.
**Additional merit points no longer reduce recast time, but instead increase MP recovery by an additional 5% per point**

_[dev1086] Dark Knight_
Dark Seal
Recast time has been reduced from fifteen minutes to five.
**Additional merit points no longer reduce recast time, but instead reduce casting time for dark magic spells by an additional 10% per point.**
Diabolic Eye
Recast time has been reduced from fifteen minutes to five.
**Additional merit points no longer reduce recast time, but instead increase accuracy by an additional five points per merit.**

_[dev1088] Beastmaster_
Feral Howl
Recast time has been reduced from fifteen minutes to five.
**Additional merit points no longer affect casting time, but instead increase accuracy by five percent per point.**
Killer Instinct
Recast time has been reduced from fifteen minutes to five.
Duration has been extended from one minute to three.
**Additional merit points no longer affect casting time, but instead extend duration by ten seconds per point.**

[dev1081] Bard
_Nightingale_
Recast time has been reduced from twenty minutes to ten.
**Additional merit points no longer affect recast time, but instead increase the chance of extremely rapid spellcasting by 25% per point.**
_Troubadour_
Recast time has been reduced from twenty minutes to ten.
**Additional merit points no longer reduce recast time, _but instead increase song accuracy by 25% per point_**

[dev1082] Ranger
_Flashy Shot_
Recast time has been reduced from twenty minutes to ten.
**Additional merit points no longer affect recast time, but instead increase ranged attack by 5% per point**.

**Comment by godmode** [comment]
Thankfully feint didn't have any TH on it

**Comment by icariumkupo** [comment]
Great so we're going to make group 2 merits even less useful by giving them ridiculous 15 minute cooldowns? Sounds like fun /s
