### ISSUE TITLE
Dark Spark lets all party members get Shadow Flames

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4300]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Only people with a Borghertz quest active should be able to get Shadow Flames key item from torch after killing Dark Spark. 

Klife was able to pop Dark Spark for his quest, and got shadow flames on Klife AND his alt Applesir who has no Borghertz quests active atm(Though he has completed one in the past). 

https://cdn.discordapp.com/attachments/766445128407449611/837718509294190642/Capture.PNG
https://cdn.discordapp.com/attachments/766445128407449611/837719514107609198/Capture2.PNG

/ver Version 30181205_0

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
