### ISSUE TITLE
Leather Pot synth missing

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4302]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Tried to craft this recipe from June 2007 and it wont' work https://ffxiclopedia.fandom.com/wiki/Leather_Pot?oldid=265760

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
