### ISSUE TITLE
ENM Sheep in Antlion's Clothing: Tuchulcha appears to be moving while underground

### ISSUE THREAD

**Issue by Axelution** [EdenServer/community#4304]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

![image](https://user-images.githubusercontent.com/72828303/116802218-12c3cb00-aac6-11eb-9ab8-8e7d5d5758ac.png)

### Details

After using Sandpit, Tuchulcha spawns at one of its random spawn points, but then appears to move from that location back to its first spawn point. While standing still, it has Pit Ambushed from a place it only could have got to by pathing back toward the initial spawn. Additionally, it has been absent from the initial spawn after its first Sandpit, but after waiting long enough and checking all other spawns, it was found _back_ at the initial spawn.

**Comment by falzum** [comment]
I had the same experience as Axel today. Tuch is trying to get back to his initial spawn while being underground.

https://ffxiclopedia.fandom.com/wiki/Sheep_in_Antlion%27s_Clothing

The nm should not move at all while underground

**Comment by slassen** [comment]
This was fixed before with this commit `ec96ab54decc60250125cabe4d481fe690c10c4e`. This functionality implemented is used more than once so it's probably broken in another area as well. It may have been broken as a side effect of other code? Additionally, to add on to this issue, I heard that it has been taking damage from dots while underground.

**Comment by KnowOne134** [comment]
resolved in October 4, 2021 update
