### ISSUE TITLE
Holy Bolt procs very weak

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4305]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Holy bolts additional effect is super weak compared to retail and in many cases doesn't do damage at all regardless of +mnd.

![Capture](https://user-images.githubusercontent.com/55296729/116809977-1b8cbf00-ab0f-11eb-9802-fafe74148706.PNG)

**Comment by Raulfin** [comment]
Yeah it has the same bug that rdm En-spells use to have(#3128), if a mob is weak to light dmg then holy bolts will do 0 added effect. Bug seems to affect a lot of things overall.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
