### ISSUE TITLE
Paralyzed action should claim mob

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4306]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Retail testing shows that if an action is paralyzed it should claim the mob
https://imgur.com/a/4aFls1t

**Comment by 59blargedy** [comment]
some additional testing/details
1) the following paralyzed actions make the mob turn red for a brief period of time, but do not make it aggressive:
(from any distance, even 1 yalm away)
- ranged attack 
- magic

2) the following paralyzed actions claim the mob fully, and cause the mob to be aggressive
- auto attack (even from behind)
- job abilities (provoke, steal, bully tested)

im unsure if the brief period of red mob name in scenario 1 would block others claim, and will need to do more testing.

**Comment by 59blargedy** [comment]
mostly resolved in November 29, 2021 update. i will add a report for the pet stuff separately
