### ISSUE TITLE
Monster Exuviation issues

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4307]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Exuviation when used by wamoura should remove ALL debuffs and heal for 487 x # of debuffs removed
Screenshots from retail testing: 

https://cdn.discordapp.com/attachments/670754214628032513/837774672674029648/woowza.PNG
https://cdn.discordapp.com/attachments/670754214628032513/837775227164557312/BaseLine.PNG

Current eden implementation is that warmoura only remove eraseable debuffs like Slow, but not poison

**Comment by 59blargedy** [comment]
if no debuffs are on the mob, does it heal for 487 or 0 or some other base value?

**Comment by falzum** [comment]
Good question, I'll see if Giichi still has retail access and can check for me

**Comment by falzum** [comment]
![Capture](https://user-images.githubusercontent.com/55296729/119144055-4c795900-ba16-11eb-8108-682ddc5b984f.PNG)

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
