### ISSUE TITLE
MP Recovery in Xarc is wrong model

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4308]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

ID 17330847 in Dyna-Xarc has same model as regular eyes. It should be a statue. This is why the MP recovery function of it doesn't work. http://www.dynamisbums.com/strategy/spawn_xar.html lists that mob (175 on dynamisbums cause lowdroprates is gross) as a "Tombstone Prototype". In xarc, tombstone prototypes use 7235 as their groupID

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
