### ISSUE TITLE
Results of retail blu debuff testing

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4309]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

According to Esunii current Eden implementation of many blu debuffs has wrong debuff duration AND all effected mobs have the debuff wear at the same time. 

Some screenshots from retail showing some examples that that is not how it should work. 

Magnetic Cloud(Max duration seem to be 38 seconds Gravity) https://cdn.discordapp.com/attachments/670754214628032513/838434844584312882/MagCloud1.PNG

Ice Break( Max duration 40 seconds Bind) https://cdn.discordapp.com/attachments/670754214628032513/838506790085591125/IceBreak2.PNG

Blast Bomb( Max duration 41 seconds) https://cdn.discordapp.com/attachments/670754214628032513/838508092223651871/Blastbomb3.PNG

**Comment by falzum** [comment]
Mysterious Light(Max duration 54 seconds Gravity) https://cdn.discordapp.com/attachments/670754214628032513/838432702360322088/MysteriousLight1.PNG

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
