### ISSUE TITLE
Prism Powder resale

### ISSUE THREAD

**Issue by AinzOdie** [EdenServer/community#431]
Was asked to post a ticket on the resale price of Prism Powder. Mats are not bought from npc so are limited,  but a stack resales for 4200. Not sure if its an economy issue or resale issue.

**Comment by roriffxi** [comment]
https://ffxiclopedia.fandom.com/wiki/Prism_Powder?oldid=370094
NPC price 350 - 358 gil.

DOesn't look like a problem to me.

**Comment by godmode** [comment]
Thanks for reporting Ainz! I think we will go ahead and close this for now though. It seems like it's not too bad of an increase of gil to cause economy issues by crafting and then vendoring these
