### ISSUE TITLE
Dyna Xarc RNG and NIN type monsters not using Hecatomb Wave

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4311]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Kindred_Ranger?direction=next&oldid=824439
https://ffxiclopedia.fandom.com/wiki/Kindred_Ninja?direction=next&oldid=824448

Both Kindred nin and rng mobs(Including the NMs) are using some un-named normal ranged attack currently instead of spamming hecatomb wave like they should. Ran Dyna - Xarc on 5/2 and saw this behavior the whole run.

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
