### ISSUE TITLE
Mohbwa Cloth dropping from Requiem Skeletons

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4312]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

Mohbwa Cloth currently can drop from the skeletons in the Requiem assault. Per http://ffxidb.com/items/2274, it should only drop from varioius Bhoots (1 of which being the one in that assault). Oddly enough, didn't see one drop from the Bhoots in Requiem but not enough of a sample size to say they can't.

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
