### ISSUE TITLE
BLU Magic Fruit should not be boosted by Light weather/day

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4314]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Retial work by Giichi showing Korin Obi has no effect on magic fruit

![image](https://user-images.githubusercontent.com/55296729/117163268-7df4f200-ad91-11eb-9109-039cd8666429.png)

**Comment by 59blargedy** [comment]
resolved in June 28th, 2021 update
