### ISSUE TITLE
Bo'Who Warmonger needs spawn update

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4315]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Reporting on behalf of another.

NM Bo'Who Warmonger in Pashlow Marshlands is spawning in the same, exact location every single time. He should pop randomly in the K-10 area of the zone. As it stands, people that know his timer, just stand at his spawn point and spam away to get claim. Further, according to wiki. he should occasionally pop with 2 other quadavs. As it stands, I have yet to see the other quadav spawn with him, he usually pops solo.

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
