### ISSUE TITLE
Party Fomor at the ladders shouldn't pace, they should be in static formations

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4319]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

On Eden the Fomor in these parties are roaming within their small rooms. On retail/era they are in static formations and stand still like statues.

![image](https://user-images.githubusercontent.com/13668758/117705730-673c0a00-b19a-11eb-85b2-bf57c09c8dad.png)

![image](https://user-images.githubusercontent.com/13668758/117705782-7a4eda00-b19a-11eb-80db-c76b44e7936e.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 update
