### ISSUE TITLE
Random disengage 

### ISSUE THREAD

**Issue by raventn** [EdenServer/community#432]
I noticed some wierd things auto disengage but your still hitting mob but can't use a ws and such just auto attacking.

**Comment by roriffxi** [comment]
Are you fighting bats?  Sometimes they do their HP drain move at low hp and the client thinks they died but then they gain the HP from the move so now they're not dead.

That at least where I see it occur the most often.

**Comment by raventn** [comment]
> Are you fighting bats? Sometimes they do their HP drain move at low hp and the client thinks they died but then they gain the HP from the move so now they're not dead.
> 
> That at least where I see it occur the most often.

no can be anything from goblins, flys, lizards
