### ISSUE TITLE
Mistletoe drop rate from Olden Treants may be been missed in audit

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4320]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Reporting on behalf of someone else.

The drop rate of several of these treants, including Olden Treants, was audited for the 5/16/2020 update, but it is believed that Mistletoe category change was missed and is not updated.

"Mistletoe from Olden Treants was supposed to be buffed to 6 rarity. I think they're still at 2 rarity"

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
