### ISSUE TITLE
One Aqueducts Fomor Thief should share a spawn with a Fomor Ranger

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4321]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The Fomor Thief and Fomor Ranger at D-11/D-12 of map two in Phomiuna Aqueducts should share a spawn point, so only one should be up at a time. These are two sought after subligars and should be the only non-party fomors on the first floor where you can farm them so it’s making them more available than they should be.

The detail is referenced on the wiki and I had Giiichi validate on retail via discord as well.

https://ffxiclopedia.fandom.com/wiki/Fomor_Thief

“ In Phomiuna Aqueducts, on the second map, there is one @ (L-8). The Fomor Thief at D-11/D-12 is a lottery spawn from the Fomor Ranger. (( I believe this is backwards, as I have killed 4-8 Fomor Thiefs in a row without a Fomor Ranger spawning. -Stoneysmurf~Asura))((Confirmed Lottery spwan from Rangers. I have killed 2 rangers and than popped some thieves. Macchiavelli - Sylph)) Other Fomor Thieves can be found upstairs in the library, after passing through the locked gate at (J-6 or G-8), either using a Bronze Key or lock picking.”

Posted on mobile, sorry if it’s sparse.

**Comment by E5una** [comment]
![Uploading 736094F9-AF2E-4BFC-97CC-D79A0BD55DFF.png…]()

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
