### ISSUE TITLE
Single Target Multi-hit ws(ie Goblin rush, Pecking flurry) should always take utsusemi shadows

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4322]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Copy_Image?direction=next&oldid=429744
"Likewise, Goblin Rush will always remove 3 shadows from player characters, even if the player could've evaded all 3 hits easily."

From a wiki page in 2008, since Utsusemi didn't receive any chances I assume it should have worked this way in 2007. 

Having Utsu up should prevent evasion checks vs single target tp moves until all shadows were consumed.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
