### ISSUE TITLE
Dia cast by some monsters wearing instantly

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4325]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
This is level 75 cor vs Light elementals in sky, 0 light resistance in gear. You can see from the log that Dia wore off so fast that it was gone even before the damage message came through. 

Expected behavior is that dia should last full duration if it lands

https://cdn.discordapp.com/attachments/773021402684325900/842340589827784724/unknown.png

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
