### ISSUE TITLE
Yagudo Templar Respawn timer incorrect

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4326]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Era wiki says 20 minutes respawn time for this NM, but it is taking ~26 minutes on Eden.
https://ffxiclopedia.fandom.com/wiki/Yagudo_Templar?oldid=377007

![image](https://user-images.githubusercontent.com/13668758/118158804-436f0300-b3ea-11eb-8656-2e50af1838de.png)

![image](https://user-images.githubusercontent.com/13668758/118158759-37834100-b3ea-11eb-89d8-969990e48330.png)

Seems very similar to https://github.com/EdenServer/community/issues/3234, so my guess is all the beastmen NMs that fall into these categories could probably use the same adjustment.

version 30181205_0

**Comment by 59blargedy** [comment]
Resolved in June 7, 2021 update
