### ISSUE TITLE
Ranged attacks aren't automatically missing when a monster moves out of range

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4327]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Reporting on behalf of Dowzer:

"If the target of a ranged attack moves out of weapon range, the ranged attack will now automatically miss."
http://www.playonline.com/updateus/050224hu5ol4.html

According to Dowzer, ranged attacks can still land on monsters that move out of the max range of the attack.

**Comment by 59blargedy** [comment]
think this got missed in a patch note (my bad), but this was resolved a couple patches ago to always miss. there is a debate on this overall, as modern retail does NOT always miss, but i think that was changed when distance correction was put in place is my guess.
