### ISSUE TITLE
Ammo additional effects should proc on Ranged WS

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4329]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Reporting on behalf of Dowzer:

Holy Bolt damage during Invincible according to retail:
https://www.youtube.com/watch?v=bUtJ3k3j7cU

Acid Bolts, Blind Bolts, Venom Bolts, Demon Arrows, and Kabura  Arrows will proc on Ranged WS:
Sleep Bolts and Arrows work as well.
https://www.youtube.com/watch?v=cEnZur-hRgM

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
