### ISSUE TITLE
COR 2hr bug when rolling a 3

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4331]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
https://ffxiclopedia.fandom.com/wiki/Wild_Card_(Ability)?oldid=283309

III: Restores some Job Abilities (does not restore Two Hour Abilities), 100% TP Bonus

Rolling a 3 on Eden sets everyones tp to 100, so if you have 200tp you LOSE tp. 
![Capture](https://user-images.githubusercontent.com/55296729/118290639-a624d500-b4a4-11eb-90d6-580c02d7cb71.PNG)

**Comment by KnowOne134** [comment]
utils.clamp(player:addTP(player:getTP() + 1000), 1000, 3000)

Clamps it to 3000 max

**Comment by 59blargedy** [comment]
resolved in June 7, 2021 update
