### ISSUE TITLE
Sanction Increased Meal Duration buff works in base game zones

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4334]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Sanction

Sanction buffs should only work in ToAU areas. 

I just got meal duration buff, warped to sarutabaruta and ate my 3hr food, and it now has a 6 hour duration. If you eat outside of a toau zone, it should give the normal duration food buff

**Comment by KnowOne134** [comment]
retail tested:
```
drinks = no bonus

ate cookie in whitegate with sanction increase = 6mins 3x2
traveled to sandy = still 6 mins 3x2

ate cookie in sandy with sanction increase = 6 mins 3x2

ate cookie in west ron with sanction increase = 6 mins 3x2

meat jerky in east ron with sanction increase = 1 hour  30x2
```

shows that for food buffs it doesnt care where you are and is working as it should

tested drinks as well on retail and eden and work accordingly, no boost
