### ISSUE TITLE
Swift Belt Hume NM Balor doesn't use Eagle Eye Shot

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4335]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I've killed this NM many many times and never seen EES in the log or seen the animation.

https://ffxiclopedia.fandom.com/wiki/Balor

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
