### ISSUE TITLE
Blood Pacts should generate enmity for the summoner

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4336]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://www.youtube.com/watch?v=uf2Q2ZOVp_s
14:55 : Summoner assaults Carby
15:10 : Summoner uses blood pact and pulls hate, no other actions taken. 

Video is from 2012, after the level cap increase, trying to find an older video or evidence and will post it if I find one. 

Backdated bgwiki links say rage and ward are both 1CE and 300VE
https://www.bg-wiki.com/index.php?title=Blood_Pact:_Rage&direction=prev&oldid=386740
https://www.bg-wiki.com/index.php?title=Blood_Pact:_Ward&oldid=386730

**Comment by falzum** [comment]
2007 video : https://www.youtube.com/watch?v=Z48aytRYRxQ

Fight opens with smn using a bunch of blood pacts and the whm debuffing the mob. When they do a pet swap at 4:40 the mob attacks the summoner, not the whm. (You can tell because carby auto-engages to protect his master without the use of assault. He can't assault because he's in the middle of casting stoneskin)

On eden as it is right now that mob would have attacked the whm

**Comment by Snugglepunk** [comment]
Some more era vids showing this enmity mechanic that is missing on eden. Also another report related to the summoning magic enmity posted which is also missing on eden. 
https://github.com/EdenServer/community/issues/4530

https://www.youtube.com/watch?v=Y1tjETEzdyk
https://www.youtube.com/watch?v=KDvuJOUBVpw
https://www.youtube.com/watch?v=jLPZkbzAay4

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
