### ISSUE TITLE
ZM8 Kam'lanaut Light Blade not functioning properly

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4337]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Kam'lanaut's Light Blade is being absorbed by 0 shadows, and not decreasing shadow count at all.

Per the wiki:
Light Blade is a single target attack that has a max range of 30' and causes high amounts of damage (~1000) to anyone without shadows. Blinkable with 1 shadow.

![image](https://user-images.githubusercontent.com/13668758/118657742-bba64180-b7b9-11eb-89ef-e5f8c678d4ab.png)

![image](https://user-images.githubusercontent.com/13668758/118657463-826dd180-b7b9-11eb-8eb9-8372ab445bd7.png)

![image](https://user-images.githubusercontent.com/13668758/118657944-eabcb300-b7b9-11eb-8d30-8a91bbc388ee.png)

**Comment by 59blargedy** [comment]
resolved in June 7, 2021 update
