### ISSUE TITLE
Wing Thrust shouldn't overwrite haste

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4340]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver=  30181205_0

According to both https://ffxiclopedia.fandom.com/wiki/Category:Aern?diff=353253&oldid=344572 and https://ffxiclopedia.fandom.com/wiki/Wing_Thrust, even if Wing Thrust hits you (Not all of the hits get absorbed by shadows), the Slow effect shouldn't apply if you already have Haste on you. It also says that Wing Thrust's slow can be overwritten by haste.

**Comment by 59blargedy** [comment]
note: the slow applied is 120%

**Comment by KnowOne134** [comment]
closing issue for 1 big report
