### ISSUE TITLE
Molbolger doesn't persist

### ISSUE THREAD

**Issue by Raphtalia1** [EdenServer/community#4343]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
Ver 30181205_0
Molbolger spawn resets on zone crash, can be reproduced by crashing the zone before molbolger spawns

**Comment by KnowOne134** [comment]
corrected in 12/15/2023 update
