### ISSUE TITLE
Quest Arts and Crafts giving wrong reward

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4345]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Arts_and_Crafts?oldid=321192
https://cdn.discordapp.com/attachments/707915352100831312/846023285593866260/unknown.png

Quest is giving a silver piece when it should be giving a bronze

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
