### ISSUE TITLE
Titan's Rock Throw has the appropriate slow but the duration should be twice as long

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4346]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

https://w.atwiki.jp/bartlett3/pages/329.html#14

![image](https://user-images.githubusercontent.com/13668758/119342487-2694c400-bc63-11eb-818e-73f375f684ee.png)

In testing on the test server as a level 99 SMN vs a 41 Ogrefly I was never able to observe the slow lasting for more than 1 minute, it always wore off exactly at 1 minute. **Per this JP wiki page it should be a 2 minute duration.**

To test I was using prints to check for the haste modifier and printing every second to see when it wore off.

Note:  There are some other properties listed on that page that I'd like to repot too but I'll have to get confirmation from someone first that we want to use this page as a source.

**Other References**
FFXIClopedia has no details about the slow other than the fact that it slows
https://ffxiclopedia.fandom.com/wiki/Rock_Throw

BG-Wiki has no details about the slow other than the fact that it slows
https://www.bg-wiki.com/ffxi/Rock_Throw

This other JP wiki doesn't have any details about the slow other than the fact that it slows
http://wiki.ffo.jp/html/8535.html

**Comment by E5una** [comment]
These pages might be OOE, Shock Strike is listed as having up to a 12 second duration and that can't be right. Might close the bug report but also looking for more info.

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
