### ISSUE TITLE
Megalith Throw is missing its slow

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4347]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Per the wiki page below, Megalith Throw should have a 30% slow for 2 minutes. It currently has no slow attached to it.

https://w.atwiki.jp/bartlett3/pages/329.html#14

![image](https://user-images.githubusercontent.com/13668758/119342986-d10ce700-bc63-11eb-9d2d-6a54d2f7f231.png)

I tested this on the test server as a 99 SMN against a 41 Ogrefly and printed haste mods to check for slow. It never gained the slow.

Other references:

FFXIClopedia says it slows, but there is no data on potency or duration:
https://ffxiclopedia.fandom.com/wiki/Megalith_Throw

BG-Wiki is the same. It references the slow but has no details:
https://www.bg-wiki.com/ffxi/Megalith_Throw

This other JP wiki references "theories of a 30% slow" but also references a "delicate" occurence rate:
http://wiki.ffo.jp/html/4099.html

**Comment by E5una** [comment]
Not sure if the data here is OOE or not, but the slow is entirely missing so the bug report is still useful in some capacity.

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
