### ISSUE TITLE
Double Dragonian dragons should not have MP

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4348]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Reproduced on the test server after SamuraiJake noticed Leech Scimitar proccing on live server
![image](https://user-images.githubusercontent.com/13668758/119349336-0f0e0900-bc6c-11eb-812c-460de712dc97.png)

![image](https://user-images.githubusercontent.com/13668758/119349251-f0a80d80-bc6b-11eb-878a-e3e96b1f2018.png)

The dragons are WAR and BRD so they shouldn't have MP, and I can't find anything online suggesting otherwise.

Note: The dragon wiki page says not aspirable, yet Shadow Dragon has MP, so I guess there are exceptions, but it doesn't appear these are an exception unless someone can retail test.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
