### ISSUE TITLE
Goblin Replica Statues shouldn't have auto regen

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4349]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
https://www.youtube.com/watch?v=Hs5rCEyEbHw
5:44, statue is targetted and not touched for 20 seconds and never regens a bit.
This same amount of time on eden and the goblin statue would have regened a significant amount of hp

**Comment by Mozzy4Ever** [comment]
![image](https://user-images.githubusercontent.com/11255886/119385088-44761f00-bc8b-11eb-9141-86d3ab3f6d52.png)

Looks like for some reason they're getting a 22hp/tic regen mod. Results in ~2.2% hp/tic

**Comment by rude-jerk** [comment]
Resolved in October 4, 2021 update
