### ISSUE TITLE
asking synth recipes locks up character

### ISSUE THREAD

**Issue by EternalGrump** [EdenServer/community#435]
I was in the cooking guild last night and after joining, I went to talk to some of the npcs.
The guild master npc said to ask them about recipes.
When I selected the option to have them tell me what things I can make, my character and most of my controls froze.
The camera still worked but my character was unable to move or cancel out of the conversation or open any menus in order to log out.
Another person was in the background crafting so I can tell that the lockup didn't just freeze my client all together.
I ended up having to forcibly close the game and re-log in order to get out of the lockup.
While stuck, I sort of got the impression that I was still in an npc conversation that hadn't ended yet.
Like the game was holding onto my character, waiting for the npc to correctly give a message that it never managed to deliver.
That may just be my sense of it but the process of the lockup occurring seemed that way.

This issue happened with at least 2 different npcs in the guild and may affect others, I just stopped trying to talk to any more of them after this happened more than once.
I don't recall the npc names off the top of my head but one was an elvaan with black hair I think, cooking in a pan on a stove near the guild master npc.
The other was a taru taru standing over a large cooking pot, stirring away (pretty immediately visible when entering the guild building).

Hopefully this is enough info for you to find and fix the issue.
This is quite the new player booby trap.

**Comment by erenik** [comment]
The same applies to Hugues in the Metalworks Smithing guild.

**Comment by archfiendrubicante** [comment]
This is also occurring with Terude-Harude in the Clothcraft guild as well.

As far as the normal behavior is concerned, I'm pretty sure he would look up your skill level and give you recipes you could use to level your skill.

**Comment by sugreff** [comment]
Happening in the culinary guild in Windurst as well.
