### ISSUE TITLE
Titan Mountain Buster missing additional effect Bind

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4350]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Titan's Mountain Buster is missing its bind that it should apply. Tested on test server as 99SMN vs 41 Ogrefly (and used retreat immediately afterward to avoid an auto attack that could break the bind).

The only source that I could find that referenced a time at all was this one, that estimated it as 36 seconds.

![image](https://user-images.githubusercontent.com/13668758/119494098-eb5fc700-bd2e-11eb-98d4-2c06f68078a8.png)
https://w.atwiki.jp/bartlett3/pages/329.html#13

BG wiki doesn't reference duration, only that it functions like shadowbind in the sense that damage easily breaks it
https://www.bg-wiki.com/ffxi/Mountain_Buster

ffxiclopedia is the same as bg-wiki
https://ffxiclopedia.fandom.com/wiki/Mountain_Buster

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
