### ISSUE TITLE
Titan's Rock Buster is missing its additional effect bind

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4351]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Tested on the test server as 99 SMN and was unable to bind a level 41 Ogrefly. The effect seems to be missing.

BG-wiki says unresisted is 30 second duration:
https://www.bg-wiki.com/ffxi/Rock_Buster

No duration info here:
![image](https://user-images.githubusercontent.com/13668758/119494998-ebac9200-bd2f-11eb-973e-27d7fa57117d.png)
https://w.atwiki.jp/bartlett3/pages/329.html#13

No additional info on ffxiclopedia:
https://ffxiclopedia.fandom.com/wiki/Rock_Buster

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
