### ISSUE TITLE
Mimics can be picked as if they were coffers

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#4353]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
![image](https://user-images.githubusercontent.com/52636208/119842684-e3418c00-bed4-11eb-9240-580bbdc2c980.png)
![image](https://user-images.githubusercontent.com/52636208/119842697-e76da980-bed4-11eb-8420-05988055ac1c.png)

First one was a mimic, out of habit I spammed the pick macro and it seems to have picked the mimic (for a drop from the coffer), then coffer respawned as usual after a mimic

**Comment by KnowOne134** [comment]
Corrected 2/7/2022 update
