### ISSUE TITLE
Ix'drg can target far away alliance members & chase after them

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#4357]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

My ls was in an alliance with one group at ix'drg and another group at ix'drk. When ix'drg spawned, a member casted dia on it but it just took off running and reappeared at ix'drk and started attacking an alliance member who was helping kill ix'drk. I assume that ix'drg currently spawns with hate on a random member of the alliance instead of targeting an alliance member who is nearby. Also since ix'drg and ix'drk are on different floors, ix'drg likely shouldn't be able to travel in this way since the teleporters typically reset aggro. 

To replicate, pop ix'drg in a party or alliance with some of the members in a different part of the zone.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
