### ISSUE TITLE
Star Struck Quest Not Triggering

### ISSUE THREAD

**Issue by Blex64** [EdenServer/community#436]
The Windurst quest "Star Struck" is not triggering for me. I have the appropriate item in my inventory, and don't have any known conflicting quests flagged.

**Comment by Xerlic1212** [comment]
I was also unable to flag this quest on either of my 2 characters. Both have level 3 windurst fame and have the torn epistle in their inventories. I tried to trade a meteorite to the NPC and nothing happens.

**Comment by Xerlic1212** [comment]
I figured it out thanks to talking to someone else in game who had trouble flagging this quest.. If you have "Making the Grade" flagged, you are unable to flag "Star Struck". This was not the case in retail.

**Comment by Drinarii** [comment]
I'm having that same problem.  It sucks that having the "making The Grade" quest will interfere with this one because you need to get behind the 3 mage gate to complete the Making The Grade quest and kill Wendigos.  Being as I just started recently, I won't be able to complete it for awhile.

**Comment by xizeta** [comment]
Resolved
