### ISSUE TITLE
Roc Enrage too long

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4360]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

```
ver 30181205_0

Asking speaking to a GM, it has been confirmed that the NM Roc's enrage has been set to 30 mins when the era value should be set 20 mins
```

Bug report on behalf of Artoo#4331

Checked via test server and **!checklocalvar [rage]timer mob 17269106** shows roc's timer to be 30 minutes. https://ffxiclopedia.fandom.com/wiki/Roc?diff=375324&oldid=374693 states that enrage for Roc should be 20 minutes.

**Comment by 59blargedy** [comment]
resolved in June 7, 2021 update
