### ISSUE TITLE
Phalanx effect not correctly mitigating damage from multi-hit mobskills

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#4361]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Reporting on behalf of Bigswitche.

Phalanx effect should mitigate damage from every hit of a mobskill and not from the final damage number.

If it's like Topaz's calculation in battleutils.cpp, it would look like this: 
```
        if (damage > 0)
        {
            damage = std::max(damage - PDefender->getMod(Mod::PHALANX), 0);
            damage = HandleStoneskin(PDefender, damage);
        }
```

To my knowledge, this looks like it's incorrectly applying phalanx instead of applying it to every hit of the mob's weaponskill.

Proof that it should apply to each hit individually:
https://ffxiclopedia.fandom.com/wiki/Phalanx_(Status_Effect)

> The amount of damage reduced from each attack is a flat, constant number (exact amount depending on the source and strength of the effect) and not based on percentage. Each attack in a multiple-part attack such as weapon skill can be reduced separately. It is capable of reducing the damage of attacks to zero.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
