### ISSUE TITLE
Blue Magic - Learned Light of Penance when mob only used Vertical Slash

### ISSUE THREAD

**Issue by AikoSachi** [EdenServer/community#4362]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Blue mage
Learned blue mage spell Light of Penance from Tonberry Hexxer that used ability Vertical Slash in Yhoator jungle near the outpost 
Can't replicate due to blue mage spell learning mechanics
Level 66 Blue Mage
Can contact Kiwiapple if necessary for more information if that is helpful.

![unknown](https://user-images.githubusercontent.com/46535607/120131912-368a3780-c17e-11eb-9d1b-6ba9dfdcfab5.png)

**Comment by KnowOne134** [comment]
Corrected 6/11/2022 update
