### ISSUE TITLE
Angon range too long

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4363]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Dragoon merit ability Angon can be used at 18' at perhaps even farther away. 

Should be 10' max range according to https://ffxiclopedia.fandom.com/wiki/Angon

**Comment by 59blargedy** [comment]
resolved in June 7, 2021 update
