### ISSUE TITLE
Vorpal Blade should only be used by BLU Mamool

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4364]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

![image](https://user-images.githubusercontent.com/13668758/120343928-1c0fa580-c2c7-11eb-82d5-c8cb06bfbf5c.png)

Seems like non-BLU Mamool are using this ability, and simultaneously, BLU Mamool are not using this ability.

![image](https://user-images.githubusercontent.com/13668758/120344019-334e9300-c2c7-11eb-98f4-89c935665549.png)

https://ffxiclopedia.fandom.com/wiki/Category:Mamool_Ja

**Comment by 59blargedy** [comment]
resolved in June 28th, 2021 update
