### ISSUE TITLE
Can use boost while resting

### ISSUE THREAD

**Issue by ghost** [EdenServer/community#4365]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Posted on behalf of Sselluous.

ver 30181205_0
When Resting I was able to use the Job Ability Boost.

Mnk Sub
Using Windower
Worked in Dunes & Rolanberry

Image shows boost going off while resting.

![image](https://user-images.githubusercontent.com/13455324/120380160-b77d3680-c318-11eb-9dd3-5766b3c304dc.png)

**Comment by KnowOne134** [comment]
part of a bigger issue, duplicate issue to https://github.com/EdenServer/community/issues/4816
