### ISSUE TITLE
WHM fellow has double attack trait

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4366]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver: 30181205_0

WHM fellow seems to have double attack trait when it shouldn't, DA procing aprox 15% of the time

**Comment by falzum** [comment]
https://ffxiclopedia.fandom.com/wiki/Adventuring_Fellow

**Comment by 59blargedy** [comment]
resolved in July 29, 2021 update
