### ISSUE TITLE
Quiver/Toolbag npc appearing in San d'Oria

### ISSUE THREAD

**Issue by AinzOdie** [EdenServer/community#437]
Nokkhi Jinjahl and Ominous Cloud NPCs in San d'Oria when they are not first in conquest
Conquest was Bastok 1st, Windy and Sandy tied for 2nd
NPCs did not appear in Windy, but did in bastok and sandy
https://ffxiclopedia.fandom.com/wiki/Nokkhi_Jinjahl?oldid=204630
https://ffxiclopedia.fandom.com/wiki/Ominous_Cloud

**Comment by Mimic716** [comment]
She appears in Bastok and San'doria regardless of conquest results, leaving Windurst without the proverbial pot to piddle in.
