### ISSUE TITLE
Group 1 PUP merits are not era

### ISSUE THREAD

**Issue by Axelution** [EdenServer/community#4371]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

![image](https://user-images.githubusercontent.com/72828303/121592574-b9698880-c9ef-11eb-8615-45bbfa10aeb3.png)

### Details

According to Sept 16, 2015 retail patch notes, PUP group 1 merits were changed accordingly
![image](https://user-images.githubusercontent.com/72828303/121592074-1a449100-c9ef-11eb-800a-c72a4028bfd6.png)
https://forum.square-enix.com/ffxi/threads/48564-Sep-16-2015-%28JST%29-Version-Update

era wiki pages for them instead have "Automaton skills" separated into Melee/Ranged/Acc, and no Repair effect or Maintenance recast
![image](https://user-images.githubusercontent.com/72828303/121592426-845d3600-c9ef-11eb-9dc4-e1ce038131df.png)
https://ffxiclopedia.fandom.com/wiki/Category:Merit_Points?oldid=731765#Puppetmaster

**Comment by KnowOne134** [comment]
Resolved in 5/3/2023 update
