### ISSUE TITLE
Quest: A Pose by Any Other Name [Requested Item Missing from Dialogue]

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#4372]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently this quest's dialogue displays as shown in the screenshot below:

![APoseByAnyOtherName](https://user-images.githubusercontent.com/61279359/121617015-ad9ab800-ca29-11eb-880a-faa8c95f62d8.png)

The quest is still doable if you follow one of the guides which exist for it, but it would certainly be helpful to have the dialogue display correctly.

**Comment by 59blargedy** [comment]
resolved in July 8, 2022 update
