### ISSUE TITLE
Nachtmahr in Bostaunieu Oubliette dropping Eldieme Coffer Key

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4373]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Reporting on behalf of Acorn, Nachtmahr in Bostaunieu Oubliette shouldn't drop a coffer key for The Eldieme Necropolis.

![image](https://user-images.githubusercontent.com/13668758/121618906-a1b4f300-ca35-11eb-9d84-f84fa7431943.png)

**Comment by 59blargedy** [comment]
resolved in June 28th, 2021 update
