### ISSUE TITLE
Mother Globe Issues

### ISSUE THREAD

**Issue by Raphtalia1** [EdenServer/community#4374]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
30181205_0

Mother globe does not chase for long, should be tracking by scent
Slaves deaggro fast and reaggro random targets

Will record next time

**Comment by 59blargedy** [comment]
confirmed on retail MG does not track by scent and deaggros as a normal mob does. slaves do not share hate with mg and can be pulled off and deaggroed.
