### ISSUE TITLE
Mother Globe Resistances

### ISSUE THREAD

**Issue by Raphtalia1** [EdenServer/community#4376]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details
30181205_0

Mother Globe seemed to have much lower resistance than previously, no spells resisted, everyone present recalled requiring Ele Seal to land some spells on retail, all spells landed here

**Comment by 59blargedy** [comment]
on retail with 75 rdm, hq staff, 297 enfeebling skill, 89 int and 86 mnd (i.e. ZERO enfeebling gear at all) i was able to consistently land all debuffs - i resisted one gravity after 8 casts (inline with grav building resistance) bind, slow, blind, paralyze all landed with ease. doesn't seem like MG is particularly resistant. maybe folks tried with blm back in the day with little enfeeb gear, idk.
