### ISSUE TITLE
Multi-hit weapon skills not killing enemies when they should be

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4378]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Reporting on behalf of Appollo/Artemmis in discord.

I think there may be a defect here, several people are reporting that their level 75 characters are frequently leaving low level (20-30ish) level monsters alive with their multi hits like dancing edge or asuran fists and only dealing a small amount of damage if the monster is low health. Example, someone using DE on a 2% skeleton and having it live at 1%.

Appollo/Artemmis just went and did two tests in Gusgen with Dancing Edge as a 75 THF on a level 20 Ghoul and said both times they only hit the first hit only and the ghoul was left with very little HP.

Update: They are saying potentially skeleton related only since they were killing wyverns and it wasn't happening. Just passing the message along, haven't tested myself.

May be related to the closed ticket https://github.com/EdenServer/community/issues/4245

**Comment by Tofutoshi** [comment]
Update on this. It's based on the mob's resistances. Leeches/hecteyes won't die to monk weaponskills. Ghost wouldn't die to dancing edge. 

Need to test more with 2h weapon types.

**Comment by Appotemmis** [comment]
Yeah, you can test this on elementals, the walls in Lebros assault. Anything that has a resistance to a weapon skill will 100% not die to a multi-hit WS unless the first hit kills it

**Comment by Kagekiki** [comment]
I have been testing this on MNK vs Elementals and wondering why the numbers for Asuran Fists Falls right off the lower their HP. I thought I was going crazy or something that I could never hit a killing blow with it.

**Comment by LahaEden** [comment]
This has been a thing i noticed myself on monk a very long time ago. having killed probably 5000 leeches in SSG asuran could never 1 shot them. if asuran at 100% hp it would drop to like 10%. if leech was at 70% it still would never die and it was like my ws damage adjusted itself accordingly
