### ISSUE TITLE
OOE Butterpear dropping from Goblin Reaper in Yhoator Jungle

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4379]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Rerporting on behalf of Radgnr in discord:

![image](https://user-images.githubusercontent.com/13668758/122089654-f8735180-cdd4-11eb-8ab4-074275ba4502.png)

Butterpear appears to be a 2011 or later item per the wiki history

https://ffxiclopedia.fandom.com/wiki/Butterpear

**Comment by 59blargedy** [comment]
resolved in June 28th, 2021 update (was a logging result not gobbie, for clarity)
