### ISSUE TITLE
Dynamis Windurst repop statues missing hp and mp restore types

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4382]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

http://www.dynamisbums.com/strategy/images/maps/strategy_win2.jpg

All the statues that spawn after mega right now on eden are red eye statues. Should be some hp and mp ones sprinkled in the mix. They were working correctly before the change to add mobs to the repop statues

**Comment by falzum** [comment]
Second source https://static.wikia.nocookie.net/lowdroprates/images/9/9d/Windurst2.jpg/revision/latest?cb=20100430140041

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
