### ISSUE TITLE
Awakening: Tenshodo Door/Norg gives CS twice

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4384]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

For ZM17: Awakening, you're supposed to get 2 cutscenes. 1 upon zoning into Norg, 1 when interacting with the door to the Tenshodo Headquarters in Lower Jeuno. It doesn't matter what order you get the CS in, according to wiki. Both instances seem to add 1 to your ZilartStatus var. Both do a check to see if your ZilartStatus is 0 or 1 to give you the cutscene. Issue is if you hit the Tenshodo Door again after getting the cutscene for it, it'll progress you to ZilartStatus 2 which then makes zoning into Norg not give you the CS. Same for the reverse (Zoning into Norg twice = ZilartStatus 2).

**Comment by KnowOne134** [comment]
Resolved 7/1/2021
