### ISSUE TITLE
BRD AF "Circle of Time" 

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4386]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

https://ffxiclopedia.fandom.com/wiki/The_Circle_of_Time
Spawning Bugaboo requires circleTime = 7. Killing Bugaboo gives circleTime 8. If you touch the Altar afterwards, you get circleTime 9 and have your key items removed that allow you to spawn the NM. At this point you're supposed to go to the final NPC (Chalvatot) who requires circleTime 9. If for some reason you end up having to kill another Bugaboo, it'll set your circleTime to 8 and you'll be stuck because you no longer have the key items. This'll make the ` if circleOfTime == QUEST_ACCEPTED and player:hasKeyItem(dsp.ki.STAR_RING1) and player:hasKeyItem(dsp.ki.MOON_RING) then` check fail, so you instead just get `player:messageSpecial(ID.text.ALTAR)`

**Comment by 59blargedy** [comment]
resolved in June 28th, 2021 update
