### ISSUE TITLE
Beastmaster ready does not show abilities if pet spawn level is <25

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#4387]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

- equip fish oil broth
- change to level 25 beastmaster
- engage/fight and try to use ready, no abilities will be in the menu

While testing on the test server, this error disappeared when I changed to level 75, but would be removed again when i changed back to level 25. also tried to zone to refresh list, did not work.

**Comment by mlandrum22** [comment]
Tested this on the test server, when CC spawned at level 23 or 24, she had no Ready moves, but the moves were there at level 25.

**Comment by 59blargedy** [comment]
ooh thank you... so something about it not spawning at the same level as you, but only at level 25?

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
