### ISSUE TITLE
Blessed Bliaut/Briault should be a 100 synth

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4388]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver=  30181205_0

From Falaras (So hate him, not me):
Currently on Eden, Bliault is a 102 synth. 
JP Wiki rolled back shows 100 synth: http://wiki.ffo.jp/wiki.cgi?Command=HDetail&articleid=60050&id=2965
Retail testing shown here: https://youtu.be/AE7mIdXGST4 has found Blessed Briault is a 100 cap synth.
You can only attempt a synth if you are within 27 levels of a synth on retail. Blessed Bliaut is synthable at 73 so it caps at 73+27=100. Current BGWiki shows it as a 100 synth as well.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
