### ISSUE TITLE
CP/ISP shouldn't be gained via Chocobo Digging

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4389]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver = 30181205_0

Blame Falaras!
https://forum.square-enix.com/ffxi/threads/50760-Jun.-7-2016-%28JST%29-Version-Update
June 7th, 2016 is when you were able to dig up ISP/CP: 
![image](https://user-images.githubusercontent.com/11255886/123487569-c7b0ca80-d5d3-11eb-99ef-a5112615de5d.png)

**Comment by KnowOne134** [comment]
resolved in October 4, 2021 update
