### ISSUE TITLE
XP bands shouldn't be rechargeable in ToAU

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4390]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver = 30181205_0
Kinda an OOE QoL thing but documenting here.
http://www.playonline.com/pcd/verup/ff11us/detail/3893/detail.html
![image](https://user-images.githubusercontent.com/11255886/123488797-3db63100-d5d6-11eb-8605-9fc924656b1e.png)

Shouldn't be able to recharge bands with ISP

**Comment by slassen** [comment]
For clarity I think Mozzy means ToAU zones not ToAU era. Just commenting because that’s what the title meant to me.

**Comment by KnowOne134** [comment]
resolved in October 4, 2021 update
