### ISSUE TITLE
Yagudo Avatar Summon {Too Weak}

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4392]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

![image](https://user-images.githubusercontent.com/11255886/123534654-341aef00-d6e4-11eb-9d7f-cb8fa91f3912.png)

A level 75 mob is summoning a level 25 elemental

**Comment by 59blargedy** [comment]
resolved in July 29, 2021 update

**Comment by Mozzy4Ever** [comment]
Avatar's summoned elemental is now correct level, but still uses spells as if it was ~25
