### ISSUE TITLE
Flags for Muddy Siredon and Blackened Muddy Siredon

### ISSUE THREAD

**Issue by InoUno** [EdenServer/community#4394]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

_From: Teitaka#6385_

"Muddy Siredon" is given a hidden "Rare/Exclusive" tag despite it having its Rare & Exclusive status' removed on 5th June 2007
![image](https://user-images.githubusercontent.com/774909/123807672-5aad7580-d8f0-11eb-84aa-245e4010eed3.png)
(And can view all subsequent history-change links after June 5th as it was corrected/updated over several tweaks listing it as sellable in bazaar/AH etc)

Also, the reward for handing in this fish, the "Blackened Muddy Siredon" is not rare/Ex but is also not allowed to be bazaared( or possibly even traded) it seems, despite being sell-able on AH back in Era
![image](https://user-images.githubusercontent.com/774909/123807778-7284f980-d8f0-11eb-97d1-fdb6a555f89e.png)

**Comment by slassen** [comment]
Not sure what the direction is on CoP now but #1468 is similar. There was a chart I posted on one of them as well taken from some SE patch notes

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 update
