### ISSUE TITLE
Killed during Cutscene for CoP 8-4: Dawn

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#4395]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I was killed by the Fomors at Blueblade Fell while in the middle of the cutscene for CoP 8-4: Dawn.  This should not be possible as the player should not be detectable/aggroable by mobs while inside of a cutscene.  This should be the state the player is in for all cutscenes within the game.

![Rabadaba_2021 06 29_165526](https://user-images.githubusercontent.com/61279359/123872627-f8a63d80-d8fa-11eb-861c-1ce409eb49e4.png)

**Comment by 59blargedy** [comment]
resolved in July 29, 2021 update
