### ISSUE TITLE
Crimson-toothed Pawberry can be popped back to back without a wait

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4396]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Crimson-toothed_Pawberry

Wiki indicates there should be a 15 min wait between pops (a previously closed ticket notes that the ??? should stay up and not be usable, but the wiki says there should be a wait, which seems to be missing.)

Not sure if any retail testing was done to confirm what ffxiclopedia is saying, but figured I'd report since they differ and typically in era we have 15 min waits.

**Comment by 59blargedy** [comment]
resolved in august 2nd mini-update.
