### ISSUE TITLE
Various davoi orcs double attacking

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#44]
In Davoi (maybe elsewhere, dunno) the Orcish Impalers are ALWAYS double attacking despite being DRG. Doesn't matter if they miss or hit with the first attack, it's always double attack.. Seems like they attack faster with a 2h than my THF does with DW knives, too... but dunno if that's different compared to retail/kupo, didn't pay too much attention then

![untitled](https://user-images.githubusercontent.com/11255886/46417432-444a3f00-c6ef-11e8-9c93-f7a6942d17a0.png)

EDIT: Orcish Serjeant (also davoi) is a PLD doing the same
EDIT2: Orcish Gladiator is attacking VERY fast. Was hitting every ~4-5 seconds despite having Slow on it

**Comment by godmode** [comment]
Seaboard Vulture and Gigas in beaucedine glacier as well

**Comment by jmcmorris** [comment]
I dug into this. Many mobs are incorrectly assigned as H2H. We are working on getting this fixed up.
