### ISSUE TITLE
mog safe / furniture quests

### ISSUE THREAD

**Issue by Helios314** [EdenServer/community#440]
My reputation is 9. 
I have a bronze bed installed in my Mog House that I haven't moved since last week.

I haven't had the quest for Mog Safe capacity to activate the last two conquest rolls. Is there anything I'm missing? I'm assuming it's not fixed yet.

**Comment by godmode** [comment]
I missed something during the patch last week. It should be available after the patch this Tuesday

**Comment by Helios314** [comment]
No problem ^^ thank you

**Comment by Helios314** [comment]
It's still broken.
