### ISSUE TITLE
Ark Pentasphere should require clear weather and be a more strict window of night

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4400]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Per DSP code and reports in Eden discord, you can currently obtain the Ark Pentasphere in any weather, which is how it currently functions, but not how it functions in era. In addition, it seems the window was extended OOE to be 18:00-06:00, but the era wiki pages all show 00:00-03:00 on bgwiki and ffxiclopedia.

DSP:
_if ((Hour >= 18 or Hour < 6) and IsMoonFull() == true) then_

The era wiki page shows that clear weather is required, and the modern bg-wiki page references that "clear weather is no longer required", and this requirement disappears off of the ffxiclopedia page at a later date.

Era ffxiclopedia
https://ffxiclopedia.fandom.com/wiki/Ark_Pentasphere?oldid=354794

OOE BG wiki, but still 2008, when the old requirements were there (era page has no details):
https://www.bg-wiki.com/index.php?title=Ark_Pentasphere&oldid=59777

Modern BG wiki:
https://www.bg-wiki.com/ffxi/Ark_Pentasphere

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
