### ISSUE TITLE
Mobs casting spells spinning to face their targets

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4403]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Not sure when it was changed but during dyna Thursday and fighting Ghrahs yesterday, mobs casting spells would continue to face their targets if you tried to run behind during a Flare to Sneak Attack for example. Mobs should not spin while casting

**Comment by InoUno** [comment]
Resolved with July 29th, 2021 patch.
