### ISSUE TITLE
The Road to Aht Urhgan quest missing wait

### ISSUE THREAD

**Issue by slassen** [EdenServer/community#4405]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The is a missing wait step for the Aht Urghan quest. Instead of getting the following waiting message as described in the quest I got my boarding permit immediately.

"After trading the item(s) or paying the gil he requests, zone, wait until the next game day, and talk to him again after zoning for the Key ItemBoarding Permit."

ver 30181205_0
https://ffxiclopedia.fandom.com/wiki/The_Road_to_Aht_Urhgan

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
