### ISSUE TITLE
Save the Children bcnm no aggro

### ISSUE THREAD

**Issue by slassen** [EdenServer/community#4406]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

May be a combo of a no superlink or maybe they just dont aggro to any level? I didn't get aggro as a level 33. Additionally, they did not link when I bound one and then went around back to kill it.

ver 30181205_8

![Godmode_2021 07 04_111221](https://user-images.githubusercontent.com/6099499/124396716-10494180-dcc0-11eb-8323-7f6a9740bdc3.png)

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
