### ISSUE TITLE
Mamool Ja (BLU) blue magic range may be incorrect

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#4409]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

During some runs of T2 Mamool Assault (Preemptive Strike), witnessed the BLU Mamool Ja Executioners casting spells at a range which seems to be incorrect. It was able to get off spells such as Sickle Slash and Sandspray, which are usually very close range spells, from very absurd ranges. (Around 20' or more) 

Unsure if this behavior is true for all BLU mobs, or just the ones in this assault. Also unsure about the extent of spells affected by this.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
