### ISSUE TITLE
Victory March incorrect

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#4410]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
**Magic Haste**

**Victory March**
http://wiki.ffo.jp/html/2151.html
96/1024 with 600 skill
 our system adds a zero
Faerie Piccolo adds on 32/1024 (+20% is OOE) which is 320 for us
so with Faerie Piccolo it should be 1280 with 600 skill

https://ffxiclopedia.fandom.com/wiki/Victory_March?oldid=1041394
matches with this chart, so let's work backwards to 450 skill (naked 75 brd)
![image](https://user-images.githubusercontent.com/5552081/124895112-29116a00-dfd4-11eb-8144-792d2a7427e5.png)
so a naked 75 brd should = 710 without Faerie Piccolo and 1030 with it, right now it is6 25 and 937.

http://wiki.ffo.jp/html/4797.html
shows precise values for Victory

**Comment by Slamm21** [comment]
of course, if the whole thing is out of 10000 and not 10240
something like victory march would be 71/1024 = 0.0693
=693
or with Faerie Piccolo 103/1024 =0.1005
=1005 
at 450 combined skill (naked 75 brd no merit)

**Comment by KnowOne134** [comment]
To clarify dsp removed the /1024 and went to a 1/10000 scale. So 15% haste is 1500/10000

**Comment by Slamm21** [comment]
> To clarify dsp removed the /1024 and went to a 1/10000 scale. So 15% haste is 1500/10000

that means haste spell is correct then as it is currently 1465/10000
but marches are off by a big amount

**Comment by Slamm21** [comment]
http://wiki.ffo.jp/html/4797.html
shows precise values for Victory

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
