### ISSUE TITLE
Bard songs need an audit on their ranges

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4412]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Below are my notes from testing on Eden test server and having Bliven test on live retail. All my tests were performed with both a flute and a harp to make sure there was no difference.

All testing was done on Eden test server on a worm that is not moving, but MIGHT be on slight .1 elevation.
_______________

ALL threnodies were tested and found to have 21.5 as max casting range. Modern wiki lists them as 20', Bliven tested on retail, 21.5

https://www.bg-wiki.com/ffxi/Fire_Threnody
_______________

Foe lullaby - Bg wiki says 20', Eden is 21.5, Bliven testing is 21.7 on retail

https://www.bg-wiki.com/ffxi/Foe_Lullaby
_______________

Horde Lullaby - Bg wiki says 20', Eden has 16.4', Bliven got 17.6 for retail testing

https://www.bg-wiki.com/ffxi/Horde_Lullaby
_______________

All requiem tested - Bg wiki says 20', Eden has 16.4' for all of them, Bliven tested on retail and its 17.6 there.

https://www.bg-wiki.com/ffxi/Foe_Requiem
_______________

Both elegies are listed as 24' on BG wiki - Tested both and found to have 21.5' on Eden, both have 21.5' on retail via Bliven testing.
_______________

Magic Finale has 21.5' on Eden, but is listed as 20' on bg-wiki, Bliven's testing shows 21.5' on retail
_______________

Maiden's Virelai is listed as "Instrument" on bg-wiki, so variable by instrument, which is very odd. Bliven tested on retail and said its 17.6' for both ghorn and terpander(string).

On eden it's 16.4'

Version 30181205_0

**Comment by E5una** [comment]
I don't think its any relation to https://github.com/EdenServer/community/issues/3652 but thought I'd mention there could be some relation. I don't think they are related though.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
