### ISSUE TITLE
Horde Lullaby radius is too big

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4413]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Horde Lullaby radius on Eden is currently 10' for both wind and string. It should be 4' for wind and 8' for String. Bliven tested this for me on retail and confirmed that is the case. 

Modern wiki page (says the ranges):
https://ffxiclopedia.fandom.com/wiki/Horde_Lullaby

Era wiki page (says no detail):
https://ffxiclopedia.fandom.com/wiki/Horde_Lullaby?oldid=300849

BG-wiki that confirms the range:
https://www.bg-wiki.com/ffxi/Category:Lullaby

There is no era BG-wiki page for this.

_______________

In order to test this I aggrod bats and got them on top of me and then moved various distances away from a stationary worm that I was casting on to check the range. Bliven used the same approach to test on retail.

Here is a screenshot at 10.2 to show the max range is 10. 

![image](https://user-images.githubusercontent.com/13668758/124936608-b3f26480-dfd4-11eb-9b7d-59be37a09888.png)

Here is a screenshot of me using a wind instrument at 9.4, showing that the horde lullaby reaches.

![image](https://user-images.githubusercontent.com/13668758/124936659-bbb20900-dfd4-11eb-8c4b-5fab24417a41.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
