### ISSUE TITLE
Angra Mainyu teleports too quickly/frequently 

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#4415]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

game version 30181205_0

When my LS engaged Angra Mainyu  today in Dynamis Beaucedine, we found that it was teleporting too frequently and quickly to get any actual damage on it. Even when a GM showed up to assist it teleported away a few times before the GM was able to kill it. Video here- https://youtu.be/xAfJChlmAQc    you can see that Angra Mainyu frequently teleports away, sometimes did so without anyone being on/near it, sometimes teleports away while I'm engaged on it and teleports back into the same position, etc. 

To reproduce, do dynamis beaucedine and engage angra mainyu.

**Comment by 59blargedy** [comment]
resolved live a few weeks ago, permanently merged in July 29, 2021 update.
