### ISSUE TITLE
Goblin Statue #64 should be perma-bound and never move even if attacked

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4416]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://static.wikia.nocookie.net/lowdroprates/images/c/ce/Jeuno1.jpg/revision/latest?cb=20100430220829

The statue #064 by Maat should never move, even if aggrod or acted on. 

Old era vidoes: Mind the volume some of the music is loud
8:17 in this one, statue links with the previous pull(eyes open) but it never moves https://www.youtube.com/watch?v=T2TBxPWGgBs&t=79s

3:30 in this vid: alliance moves right up to the statue, eyes are open and it's turning in place facing the person with aggro but never moves https://www.youtube.com/watch?v=ontfs_4uu4g

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
