### ISSUE TITLE
Goblin Statues getting 'stuck' in Dyna Jeuno and Beaucedine

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4417]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

During pulls today(7/11/21), especially larger pulls, the statues would stop to cast a buff on an idle statue and then stand still for upwards of 60 seconds. Attacking them wouldn't make them continue chasing

**Comment by InoUno** [comment]
Resolved with July 29th, 2021 patch.
