### ISSUE TITLE
Dyna-Jeuno boss (Goblin Golem) should be stunnable

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4418]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Boss is currently immune to stun on eden

https://www.youtube.com/watch?v=vuodWXvtgPQ&t=426s
At 6:54 the Mega boss starts to cast death and it get stunned.
6:58:  You can see the 'Goblin Golem's casting is interrupted message' 

https://www.youtube.com/watch?v=Z9RTYMtUiTQ
3:20 Mega is walking and gets stunned in place, unfortunately chatfilters are active and you can't see it in the log

**Comment by Slamm21** [comment]
Some of the xarc statues seem to be the same too, every statue should be stunnable

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
