### ISSUE TITLE
NM Arachne PH's don't seem to be in era or modern location

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4419]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Modern wiki shows PHs's should be here

![image](https://user-images.githubusercontent.com/13668758/125458940-eabb7976-db8c-4df0-b654-dca7a234dc4f.png)

Era wiki says PH's should be "Lottery Spawn from the Recluse Spiders around (F-9) - (F-10) on the second map from Cape Teriggan.". **There are not spiders at this location at all, so I think we have a bigger issue with monters not being in era spots**

![image](https://user-images.githubusercontent.com/13668758/125459147-07928d90-98ce-49e8-96ed-3f6f0f7d8599.png)

It doesn't seem like either of these spots contains the PHs currently

version 30181205_0

**Comment by E5una** [comment]
Edit: Upon rereading that closely, it doesn't say "map 2" it says "the second map from Cape Terrigan" so it might be referring to the same spot. That being said the PHs still don't appear to be in the that area, I think they are 1 room above?

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
