### ISSUE TITLE
Crimson-toothed Pawberry (NM)

### ISSUE THREAD

**Issue by Mikokiko** [EdenServer/community#442]
When you trade the item to pop Crimson-toothed Pawberry, the ??? does not desapear after.

Trading a pop item when the ??? is up does nothing. 

After 15 min are done you can trade and repop NP.

**Comment by tectal831** [comment]
Can you reword this please? I am not understanding your issue

**Comment by Mikokiko** [comment]
You need to trade a temple offering to pop Crimson-toothed Pawberry.

The ??? should desapear while you fight the nm and kill the NM.

The ??? should reappear 15 min after NM death or depop.

However, on Eden the ??? is always up.  After you just kill Crimson-toothed Pawberry, the ??? is up, trying to trade the offering within 14 minutes of the death does nothing, but the ??? should not be up for that period of time. 

Does it make sence?

**Comment by tectal831** [comment]
Got it. Thanks

**Comment by godmode** [comment]
This seems to be retail behavior. It is intentionally coded different from other QMs. Closing for now but if you hear any different this is not hard to change to a normal pop. I couldn't find any info for it on the wiki so a retail pop is really the only way we are going to find out.
