### ISSUE TITLE
CoP 6-4 One to be Feared, omega fight, issue between phases when dead

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4420]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

When players die during a phase, they are not HP/MP restored on the next phase, but the UI reflects them as having full HP/MP even when they need a raise. 

![image](https://user-images.githubusercontent.com/13668758/125511995-31842290-1629-471a-acf0-100f473efb1e.png)

Might be just a visual bug, or maybe they should be raised, I'm not sure, but I think as is its a little off.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
