### ISSUE TITLE
Purchased map of Mamook, but got Carpenter's aurum tome

### ISSUE THREAD

**Issue by Kurokami5297** [EdenServer/community#4421]
### Checklist

- [✓] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [✓] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [✓] I have provided my client version in the details. (type /ver into your game window)

### Details

I talked to NPC Nabihwah, checked common items, then 1000pt items.  Attempted to purchase map of Mamook, got Carpenter's aurum tome instead.
I zoned to Nashmau via ferry from Whitegate.  Before talking to Nabihwah, I set my home point, viewed the cutscene to start the quest "Rat Race", and checked most of the vendors but did not buy anything.  version 30181205_0

![image](https://user-images.githubusercontent.com/74320120/125891200-449035df-92a3-44da-a8fb-2676b3cab967.png)

**Comment by 59blargedy** [comment]
resolved by another dev in July 8, 2022 update
