### ISSUE TITLE
EES hitting for 0 in SE Apollyon  (not the ones immune to piercing)

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#4424]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Katchoo reported he used it on 3 different boss mobs in SE apollyon, and all hit for 0 damage.
EES seems fine outside of that zone.

**Comment by Slamm21** [comment]
Katchoo — Today at 23:23
Tested on normal mob, 0dmg also
in Limbus

Seems to be all mobs in the zone

**Comment by 59blargedy** [comment]
im wondering if the player was wearing a gorget based on that recent bug report. not sure if they're still around to ask?

**Comment by Slamm21** [comment]
I checked with him and that was the case, closing
