### ISSUE TITLE
Mission 5-1 Sorcerer's Not Engaging

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4425]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver = 30181205_0

The Ancient Sorcerers for Mission 5-1 Ruins of Fei'Yin aren't engaging with Archlich Taber'quoan. They sit on the sides and just buff themselves.

**Comment by slassen** [comment]
I just noticed this today as well. I think this was working in the past and bug introduced within the last couple years. They do blood aggro. But not aggro to the main mob like they should on engage.

**Comment by 59blargedy** [comment]
is this still occurring? i can't replicate on local, though i do see the sorcerers start positions are wrong

**Comment by InoUno** [comment]
Resolved with October 4th, 2021 update.
