### ISSUE TITLE
Headbutt seems overtuned

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4426]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I'm sorry for the complete lack of detail on this ticket, but BLU's headbutt is landing for full duration stun way too reliably, on any target, including high level NMs like Omega. With proper support, BLU can essentially permastun anything reliably, only really missing 5% of the time when the accuracy check fails.

A retail friend went out and did some testing on too weak monsters and said headbutt fluxuated from 2-5ish seconds, possibly less on the upper side. I personally have not put in the testing to determine if it should have some sort of random normal distribution component like Bind, but as is it seems too strong on many things.

This stream will only be up for another week and a half, but you can watch this Omega fight I did where it used like two TP moves the whole fight and barely auto attacked due to headbutt stunlock. This does require support from two other characters with a couple buffs/debuffs, but it still doesn't seem quite right.

https://www.twitch.tv/videos/1090090722?filter=archives&sort=time

**Comment by E5una** [comment]
Weirdly this morning I noticed bombs were functioning more similarly to what I'd expect on retail, but maybe not performing as well. That being said, ZM4 Tonberries had the normal 5 second stun. Crazy that I never ran into this before these bombs:

![image](https://user-images.githubusercontent.com/13668758/126336539-d4923d69-9047-41fd-93c4-8ce5e8baee79.png)

**Comment by E5una** [comment]
Ah they have 50% lightning res, didn't know that, probably what's going on, but no idk anything

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
