### ISSUE TITLE
Claim shield doesn't reset when invisible wears off NMs/HNMs

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#4428]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
game version 30181205_0

Apologies if this is something that has already been fixed. I have a number of videos showing invisible popped ground kings. Of those, this one illustrates this issue the best- https://youtu.be/f92gkkbax9w  In this video the player was able to cast stone and claim Fafnir before its invisible wore off. After speaking with a former dev I was informed this was a bug and that claim shield wasn't meant to start its timer or whatever until invisible wears off. In a similar video that I have dated May 17th of this year, Aspid is popped invisible and upon invis wearing off, it's instantly voked, which I assume meant that it's claim shield had worn before invisible dropped. 

To replicate, spawn some invisible NMs and test the claim shield. If an NM or HNM's claim shield wears off while it's still invisible, then from my understanding this is unintentional.

**Comment by rude-jerk** [comment]
This is something that was fixed a number of months ago.
