### ISSUE TITLE
Super jump lets you auto attack while petrified

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4429]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I wanted to pass on a bug I encountered yesterday in Limbus. I was fighting a lizard that used Baleful Gaze. I was in Super Jump when it used it and when I came back down I was petrified but still able to auto attack. I couldn't take any other actions or move but I was autoing while petrified.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
