### ISSUE TITLE
Bronze bed elemental strength is incorrect

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#4430]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Via Cheatmeal
So figured out that Bronze Beds have an incorrect aura strength on Eden. Their strength on Eden is 10 when they should be 6.

**Comment by slassen** [comment]
I’ll get you the era accurate values of storage and auras for staticSQL/item_furnishing.sql when I get home.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
