### ISSUE TITLE
Quasilumin in mission A Fate Decided 

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#4432]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Captured from retail every party can pop another Quasilumin to open doorways. 1st popped will always be the mob with proper id that's coded any extras will be popped as an ally id -- needs implemented outside of bcnms and instanced zones

**Comment by InoUno** [comment]
Resolved with October 4th, 2021 update.
