### ISSUE TITLE
[Darksteel Nodowa +1] is currently not desyntheable

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#4433]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Skilling up from Darksteel Nodowas and managed to HQ one, attempted to later desynth the +1, but it stated it was not valid recipe.

**Comment by 59blargedy** [comment]
resolved by another dev Oct 4 2021 update
