### ISSUE TITLE
Fire in the Sky wrong exit

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4435]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Was sent to the primary entry for Monarch Linn at the end of a win for Fire in the Sky. Based on video (https://youtu.be/cdSS-3jZcYM?t=87, https://youtu.be/TQSFxXaVcGs?t=66, https://youtu.be/Kq9FlqjnkM0?t=55) it looks like you should get the normal exit with the Displacement that lets you choose to exit to Misareaux Coast, or go back to the entrance of Monarch Linn.

**Comment by 59blargedy** [comment]
Resolved July 30th
