### ISSUE TITLE
Miratete's Memoirs gave Limit Points

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4436]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver 30181205_0

https://ffxiclopedia.fandom.com/wiki/Miratete%27s_Memoirs?diff=prev&oldid=511458 specifies it gives EXP. Later edits to the page clarify that it will not give Limit Points. 
Had my Mode Switch set to Limit Points for this SS.
![image](https://user-images.githubusercontent.com/11255886/127568025-815c2fab-b8d5-44b0-9831-6e8fbe86b470.png)

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
