### ISSUE TITLE
Mob Eagle Eye Shot does too much Damage (in Dynamis specifically) 

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#4438]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)

### Details

On behalf of Makise:

EES does too much damage on eden, went on retail and tested with the same stat here are the result:
Stat: Def 337 / Vit: 104 Mob level 75 (so no level correction), made sure Warcry wasn't on the mobs.
![image](https://user-images.githubusercontent.com/52988064/127792662-760a42ce-f3e4-497f-8ed7-24fb410ff2ee.png)

On Eden:
Stat: def 337 / vit: 104 mob level 81 (so level correction do apply on here but 6 level shouldn't basically double mob damage done, assuming 0.05 ratio bonus per level, damage increase should be 30% at most)
![image](https://user-images.githubusercontent.com/52988064/127792666-1e0dd395-90c2-4333-aebb-1118a3c32f35.png)

**Comment by 59blargedy** [comment]
resolved by another dev in may 22, 2023 patch
