### ISSUE TITLE
Avatar attack range too far? (Titan and Fenrir only)

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4439]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Titan and Fenrir attack worms from too far away so that they don't attack back, they just cast spells. Not sure if this is intentional or not, would need someone to validate on retail but I am assuming it is not.

Reproduced on the test server and tested with all avatars, the rest were fine.

Edit: Tested with all spirits too. No issues with spirits.

**Comment by 59blargedy** [comment]
cant replicate this, unsure where this occurred and what the terrain was like, as i could not replicate in qufim island, korroloka, or dangruf wadi. either it's been resolved in the meantime or it's a very specific condition which upon receiving details can reopen the report
