### ISSUE TITLE
Crimson Orb mini-quest still having issues

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#4441]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Still getting a few GM tickets a month about this -- this particular player had both Blood and Pink orbs in their KIs which should be impossible. Other times people will get the same orb twice in a row. Sometimes it's completely fine. 

"Doing LB3. Turning in Blood Orb to fourth pond in Davoi gave me a Pink Orb. Still have Blood Orb too. No Cursed Orb. Ponds not triggering anything now"

![image](https://user-images.githubusercontent.com/52988064/128466555-d09e7099-2688-44b0-bd6b-b7e20c8233df.png)

Related to #1962 that was closed I think.

**Comment by Avarghaladion** [comment]
This is still happening as of 21 May 2022. Just did this and my White Ord went Pink > Pink > Red > Pink. I currently have Pink and Red KIs, the pools no longer respond, and the Taru will not complete the quest.

**Comment by KnowOne134** [comment]
Resolved 7/8/2022 update
