### ISSUE TITLE
Uninvited Guests RA item loss

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4443]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

If you already have the Rare-marked reward that completing Uninvited Guests is trying to give you, you completely lose it. The quest is completed and speaking to Justinius gives default dialogue.

**Comment by falzum** [comment]
According to wiki Justinius should hold the item for you until you have a chance to sort your inventory

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
