### ISSUE TITLE
Automaton's don't seem to have spellcooldowns

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4445]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Per the wiki, Harlequin Head+Frame combo should have 37 seconds between spell casts, but it seems to have much less, or no cooldown at all. I can update with some minimum testing later when I'm available, but here is a screenshot of 17 seconds.

https://ffxiclopedia.fandom.com/wiki/Harlequin_Frame

![image](https://user-images.githubusercontent.com/13668758/129202986-0162ef24-91ea-46df-b683-abe6510ef04e.png)

![image](https://user-images.githubusercontent.com/13668758/129202947-a21d0c3d-4aba-4e9e-90b1-8e5a816749e7.png)

**Comment by E5una** [comment]
Will need to do some testing when I'm available to determine minimums and compare against modern PUP AI. Also the body page shows the cooldowns I listed above, while the head page shows this info:

https://ffxiclopedia.fandom.com/wiki/Harlequin_Head

I know that there weren't individual timers until a 2011 update there is no longer a universal wait time, so we definitely still would have that wait time in era.

![image](https://user-images.githubusercontent.com/13668758/129204633-0ea161f2-6997-48b4-82a4-5c8bd9c5297f.png)

All that being said, here is the era wiki page for Harlequin Head, which also shows a 36 second cooldown (1 second different than the body page, so clearly not an exact science here)

https://ffxiclopedia.fandom.com/wiki/Harlequin_Head?oldid=162894

**Comment by KnowOne134** [comment]
Believe we are going with modern era for spell casting ai as it would cripple the job completely. But if we could get real numbers to the cool downs would be great from retail as I don't trust the wiki page.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
