### ISSUE TITLE
Fenrir Prime has too much HP

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4446]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Per the wiki, Fenrir Prime should have between 9-10k HP. On Eden he currently has ~25k hp.

https://ffxiclopedia.fandom.com/wiki/Fenrir_Prime

I found a forum post that estimates about that as well.

https://www.ffxiah.com/forum/topic/3574/fenrir-prime/

This lines up with this youtube video (in high quality 240p) that I took this screenshot of Fenrir's health after 4 Blizzard IIIs that landed for 630 each.

https://www.youtube.com/watch?v=1IoyTHhHbLI&t=5s

![image](https://user-images.githubusercontent.com/13668758/129222073-73a24ba2-0b02-4d6e-89e0-4c71a5fa9de1.png)

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
