### ISSUE TITLE
PUP Automaton seems to have OOE Shock Absober

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4447]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Looks like Shock Absorber is giving the improved OOE version of stoneskin from the 2011 patch. 

Here is the current wiki showing the current formula as 200 + Skill x 0.2. I can reproduce this on the test server, as shown below

https://www.bg-wiki.com/ffxi/Shock_Absorber

![image](https://user-images.githubusercontent.com/13668758/129365338-fc9068cd-be65-4834-8ae8-aed9de997276.png)

![image](https://user-images.githubusercontent.com/13668758/129365361-31c77490-f28d-428a-a005-acef7e180ea1.png)

200 + 240 * 0.2 = 248. 1000 needles divided by 2 is 500 each. 500 reduced by 248 is the 252 shown in the log.

Era ffxiclopedia has no numbers, but July 2008 says "100 regardless of level"

https://ffxiclopedia.fandom.com/wiki/Shock_Absorber?oldid=580087

Era bgwiki also has no numbers, but January 2008 bgwiki has "Gives a Stoneskin effect to automaton. Absorbs approximately 100 HP, regardless of level."

https://www.bg-wiki.com/index.php?title=Shock_Absorber&oldid=57178

**Comment by KnowOne134** [comment]
resolved in October 4, 2021 update
