### ISSUE TITLE
Hammermill bonus from Earth Maneuvers is too high

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4448]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

A 3x Earth Maneuver Shield Bash seems to be doing roughly x10 damage instead of x2 damage.

This is a level 17 automaton vs an IT worm in Korroloka Tunnel with no earth maneuvers

![image](https://user-images.githubusercontent.com/13668758/129445982-f47922e2-338b-4387-8d2d-1b6e01e782f8.png)

This is the shield bash damage when I was level 16 with 3x Earth Maneuvers

![image](https://user-images.githubusercontent.com/13668758/129446001-db9dcccd-0eae-41fc-9a56-93e8c485dc60.png)

Per the JP wiki, they estimate about a 100% damage bonus from 3 maneuvers

http://wiki.ffo.jp/html/12156.html

And per ffxiclopedia, they estimate about the same if you look at their numbers from a 75 PUP fighting "Too Weak" monsters with it.

https://ffxiclopedia.fandom.com/wiki/Hammermill

![image](https://user-images.githubusercontent.com/13668758/129446026-7d0cd880-0d9b-48a4-8a45-f527262fba58.png)

BG-wiki does not have info on numbers.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
