### ISSUE TITLE
Bats link to Tonberry when they shouldn't

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4450]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Harun667 mentioned it in discord, but bats seem to link to tonberry in Pso'Jxa and Den of Rancor. I checked the wiki and it looks like these are the only two zones the two mob types coexist, and I see nothing that suggests they should link. I reproduced the behavior on the test server by assaulting Carbuncle onto a Tonberry Slasher in Den Of Rancor and a Succubus Bats linked to it.

Harun said they've only noticed it with NIN tonberry but reproduced with NIN and THF in Den of Rancor so presumably its all.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
