### ISSUE TITLE
Sacred Lance and Fire Bracers are missing their activatable enspell effects

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4452]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Reporting on behalf of Kovuscar on discord

The following items "Sacred Lance" and "Fire Bracers" do not provide their "Enlight" and "Enfire" enchantments respectively.  I crafted both items and equipped them and tried multiple times to get the enchantment by using them but the bar fills to 100%, a charge is used and no buff is given.   
                                                                                         
Version 30181205_0

**Comment by 59blargedy** [comment]
duplicate/resolved in November 29, 2021 update
