### ISSUE TITLE
Chimera Ripper missing +100 accuracy bonus

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4453]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Chimera Ripper feels like it doesn't have its +100 accuracy bonus, it misses a lot. Both of the below sources reference the +100 accuracy bonus but BOTH also are from 2015 and 2016 forums/wikis. I'm struggling to find era information on this one.

https://forum.square-enix.com/ffxi/archive/index.php/t-47346.html?s=53cb7fa4092b751c2401ce07535c3c37

https://www.bg-wiki.com/ffxi/Chimera_Ripper

**Comment by E5una** [comment]
Just adding some parse info from an exp pt that supports that it seems to be missing the +100 acc bonus. That being said, finding era info to say it has this bonus is still something I'm working on.

You can see the automaton has ~73% acc in the exp pt
![image](https://user-images.githubusercontent.com/13668758/130366081-d748c70c-dabe-402d-ad24-280b93c68283.png)

But only 63% WS accuracy. Small sample size I know, but seems like enough to suggest the +100 isn't there
![image](https://user-images.githubusercontent.com/13668758/130366136-bff384bd-2031-4149-b430-c8258d17e829.png)

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
