### ISSUE TITLE
Sharpshot PUP frame ranged attack damage is instant but then channels a ranged attack animation.

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4454]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Seems like the Sharpshot frame procs is damage from the ranged attack right away when it starts it’s animation and then plays out the entire ranged attack ready delay anyways after. Not sure what else to say, sorry!

Edit: The clip below in the comments seems to show an instant attack at the start but I don’t see the automaton channeling a long attack animation in place while the mobs run to it like it does on Eden.

**Comment by FariskaEden** [comment]
I do not think this is a bug, damage looked instant from this clip.
https://i.gyazo.com/389a415922cc8546227e7db3f5537f9f.mp4 - clip from retail

**Comment by E5una** [comment]
Yup, bazaar! I’ll close

**Comment by E5una** [comment]
Actually reopening and retitling because Eden still doesn’t match that clip. I’ll have to look for more clips.

**Comment by FariskaEden** [comment]
The ranged attack animation was done in that clip but when it was moving haha. Retail behaviour has automatons perform actions while moving if they are out of their max stationary range or have a melee head (valor / harlequin) equipped. Currently this is not implemented on Eden.

See https://github.com/EdenServer/community/issues/2772 https://github.com/EdenServer/community/issues/2770 for examples.

**Comment by E5una** [comment]
Hmmm okay, assuming those 2 other ones cover the behavior I'll close this.
