### ISSUE TITLE
Jettatura cooldown is ~56 seconds, should be 120

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4457]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Jettatura seems to have about a 56 second cooldown, but all wiki pages show 2 minutes.

Era wiki:
https://ffxiclopedia.fandom.com/wiki/Jettatura?oldid=349112

Current Wiki:
https://ffxiclopedia.fandom.com/wiki/Jettatura

Current BGwiki: 
https://www.bg-wiki.com/ffxi/Jettatura

Era wiki doesn't exist for bgwiki, but dec 2007 shows the same 120 seconds.

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
