### ISSUE TITLE
Infrasonics has the wrong cooldown

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4458]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Infrasonics should have a 120 second cooldown, currently has a 60 second cooldown.

Era wiki:
https://ffxiclopedia.fandom.com/wiki/Infrasonics?oldid=349145

Current Wiki:
https://ffxiclopedia.fandom.com/wiki/Infrasonics

BGwiki:
https://www.bg-wiki.com/ffxi/Infrasonics

There is no data on era bgwiki, but dec 2007 shows 120 seconds as well.

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
