### ISSUE TITLE
Gate guard NPC Mokyokyo is giving dialogue from the wrong NPC (Kenapa-Keppa).

### ISSUE THREAD

**Issue by Hyskos** [EdenServer/community#4460]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Player is half-way through Windurst Mission 1-3 and receiving text from Kenapa-Keppa when he talks to Mokyokyo, they've completed Food for Thought but not Overnight Delivery (both involve Kenapa-Keppa).

![dadadsda](https://user-images.githubusercontent.com/46092827/130235071-8461657f-bb71-400a-9764-db4680060a93.png)

Ver 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
