### ISSUE TITLE
NM tonberry pontifex gil

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#4461]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
posting for someone**

behind these gates they have a tonberry tracker a tonberry decapitator but on retail they have x2 trackers, so its missing 1 they pop every 24-28 mins, also tonberry pontifex who pops every 21-24 hrs there only drops 36 gil but hes suppose to drop 20-30k gil

**Comment by 59blargedy** [comment]
tracker is noted here: https://github.com/EdenServer/community/issues/2738
there are two, but one doesnt repop if one is killed. it is very odd.
don't see any proof of the gil value from pontifex, so would need retail capture.

**Comment by dowzer** [comment]
Here's a clip from a youtube video, it's uncertain whether they have gil finder

![pontifexgil](https://user-images.githubusercontent.com/54732693/229592766-6c418a36-5e5c-4eab-b2ab-333a70ce270e.png)

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
