### ISSUE TITLE
Charm vs Mantraps

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4463]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently Mantraps in Misareaux Coast cannot be charmed.  Retail testing has shown that they are charmable.
![image](https://user-images.githubusercontent.com/46270382/130643303-c33a59f4-fe3f-4723-a5c6-d275e3c278a9.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
