### ISSUE TITLE
Automaton Shield Bash never misses with Hammermill

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4464]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I've never had a shield bash miss with Hammermill equipped. I think we might have the OOE "never miss" interaction with that attachment from 2011:

https://forum.square-enix.com/ffxi/threads/18132-December-14-2011-(JST)-Version-Update

![image](https://user-images.githubusercontent.com/13668758/130643841-c22982de-627b-4fc4-a446-f6c3c81c56f3.png)

This could also be related to Fariska's bug report about it possibly functioning like a PLD shield bash: https://github.com/EdenServer/community/issues/4462

**Comment by 59blargedy** [comment]
Hammermill has no effect on the hit/miss of shield bash, so closing this one out.
