### ISSUE TITLE
[PUP] Cannibal Blade TP gain / log message

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4466]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently when used Cannibal Blade will give one hit worth of TP when it hits. Also the combat log message on Eden shows healing like a heal/drain rather than damage. Retail testing has shown that Cannibal Blade rewards no TP when it hits and the the damage was shown in the combat log (healing for damage dealt still occurs).

https://i.gyazo.com/54af42fa2c1eb5032dd11bcedf82aac1.mp4 - TP zeroing out / combat log message

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
