### ISSUE TITLE
[PUP] Harlequin Frame Max MP

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4469]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

The harlequin frame currently has too much MP, it essentially has double MP. Retail seems unchanged regarding this frame's MP amounts from what I can tell.

Level 37 Harlequin Eden
![image](https://user-images.githubusercontent.com/46270382/130729736-c5a2f8c4-2699-4a1c-a309-5c0d1c393d5a.png)

Level 75 Harlequin Eden
![image](https://user-images.githubusercontent.com/46270382/130729759-55dfbd14-a6d1-4223-8c93-bb410fa031a4.png)

Level 37 Harlequin Retail
![image](https://user-images.githubusercontent.com/46270382/130729775-dbdc60fb-f376-494b-8336-23683f0a78d6.png)

Level 75 Harlequin Retail
![image](https://user-images.githubusercontent.com/46270382/130729790-a830c9fb-c81b-47b0-bd89-8ffe722bd682.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
