### ISSUE TITLE
Overlord Bakgodek doesn't link

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4470]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Other orcs don't link to Overlord Bakgodek

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
