### ISSUE TITLE
Avatar Obtainability

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4472]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently when summoner is not unlocked, avatars can be obtained from their respective quests. On retail summoner needs to be unlocked first to be able to get that option as a reward.

https://www.youtube.com/watch?v=HEwEUs52BLM - shows not being able to pick the avatar when summoner is not unlocked
https://www.youtube.com/watch?v=Y5oAobU6RrU - shows being able to pick the avatar with summoner unlocked

version 30181205_0

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
