### ISSUE TITLE
TP Gain from Damaging TP Moves

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4473]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently when a player is hit by a damaging TP move no TP is gained. On retail when this occurs 1 hit worth of TP is gained (regardless if it's multi-hit or not from what I could tell).

version 30181205_0

**Comment by 59blargedy** [comment]
do you have any video/screenshots? moreso for single hit vs multi than anything else, since tp gain is v different on retail

**Comment by FariskaEden** [comment]
I don't have my own footage of the multi-hit move thing however I did manage to find some older videos (with readable text) of this occurring.

https://www.youtube.com/watch?v=KFyS-hBlqag&t=55s - PUP61/DNC30 takes pecking flurry for 226 damage from the lesser colibri and gains 2TP
https://www.youtube.com/watch?v=m81Rj40BJhs&t=92s - THF72/NIN36 takes pecking flurry for 55 damage (shadows absorbed hits but this looks like just one hit of it I think) from the equal colibri and gains 2TP

Normal hits in these vids also seem to give 2 TP since it's on the older TP scale. Not sure if that pecking flurry from the lesser colibri is more than one hit but it seems like it is to me.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
