### ISSUE TITLE
Fly Family Venom

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4475]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently venom used by flies will last like a minute and have a high DoT amount. Retail testing has shown that the DoT from venom appears to only be 1 damage per tic (this was shown from Dragon's Aery Darters). However, the duration of venom can last much longer and the duration might scale with TP or level since it lasted for like 6 minutes from the Darter.

https://i.gyazo.com/b398f1aa5d2846e4dcf83c0e8cc16a04.mp4 - duration shown as it's applied
https://www.youtube.com/watch?v=yU4vDhibRQk - video showing the 1 damage per tic on player and trust

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
