### ISSUE TITLE
Magic Pots Battery Charge should be MP Regen

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4476]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Currently on Eden, when a Magic Pot mob uses Battery Charge, it gives Refresh. It should replenish MP, not give refresh. 
https://ffxiclopedia.fandom.com/wiki/Category:Magic_Pots?diff=311628&oldid=311627
https://youtu.be/D_EqoH1eVoQ?t=609
![image](https://user-images.githubusercontent.com/11255886/131163022-237a03e4-b21a-45a9-9d9d-608905de6612.png)

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
