### ISSUE TITLE
Olla Grande Regain too low

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4477]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver = 30181205_0

Olla Grande should use a TP move every 10-15 seconds under 25% without hitting a target. It's regain above 25% is 300, which seems to be correct. However under 25%, it's regain drops to 150 which results in a TP move every ~20 seconds.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
