### ISSUE TITLE
Spectral Barrier duration incorrect

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4478]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver = 30181205_0

Currently on Eden, it looks like Spectral Barrier from Magic Pots lasts a static 1 minute duration. 
https://youtu.be/D_EqoH1eVoQ?t=886 shows "Olla Grande gains the effect of Magic Shield" at 23:43 in-game timestamp (14:57 in video). At 24:26 (15:40 in video) the RDM lands Poison 2 on Olla Grande. This is a 43 second difference.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
