### ISSUE TITLE
Qutrub Family Jobs

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4480]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently Qutrubs / Lamia Idolators are missing their other jobs. Qutrubs that are BLMs and use daggers are also part THF. Qutrubs that are DRKs and use swords are also part WAR.

![image](https://user-images.githubusercontent.com/46270382/131232054-8e85ebb5-f525-42cf-8c65-f8cd9212ce87.png)
Can see there's an evasion difference between the different types here.

https://i.gyazo.com/612f77a16d406e1a1e8de517034ee4ba.mp4 - Lamia Idolator BLM triple attacking
https://i.gyazo.com/493d4489eb7d1c0f80a72e5bc4373dd0.mp4 - Qutrub BLM triple attacking
https://i.gyazo.com/289b6c2f6b269fa60854241d3769ba15.mp4 - Lamia Idolator DRK double attacking
https://i.gyazo.com/d000ab2d10d9a46a3fa6c81ddedf2f0f.mp4 - Qutrub DRK double attacking

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
