### ISSUE TITLE
Mandragora / Korrigan Guard Animation

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4484]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently when you fight a mandragora / korrigan mob and it guards their unique guard animation does not play. They should dip into the ground when guarding.

https://i.gyazo.com/b895ee5d3e886e07ba21d022fb3d86d4.mp4 - mandragora guard animation
https://i.gyazo.com/fb2da7cb98637a177b4777f16c9ba640.mp4 - korrigan guard animation

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
