### ISSUE TITLE
Xolotl and his adds should be sleepable with lullaby

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4485]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

(2007 wiki link) https://ffxiclopedia.fandom.com/wiki/Xolotl?oldid=393034

Currently Xol and his adds are lullaby immune, but should be susceptable according to wiki.

Couldn't find era video evidence to back this up, might need a retail check

**Comment by falzum** [comment]
https://puu.sh/I7ZHh/4738182ff7.png

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
