### ISSUE TITLE
Brothers ENM Eldertaur should have large Sound aggro

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4488]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver = 30181205_0

Based on https://youtu.be/-6vZZLABAec?t=193, it seems like Eldertaur (and maybe Mindertaur too?) should have either a large sound aggro range, or have a large HP aggro. Player was at almost 30' from the Eldertaur and it had it's back turned, but still aggro'd upon reraise.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
