### ISSUE TITLE
pup whm head quest.

### ISSUE THREAD

**Issue by godpup** [EdenServer/community#4489]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
 pup af whm head . The quest wont give me the head. npc has been working on it for a year now. Ghatsdad , galka npc w.e his name is. in automation shop

**Comment by Mozzy4Ever** [comment]
Many people have gotten WHM head within that time frame. This sounds like a GM ticket issue, not a bug report.

**Comment by godpup** [comment]
Ok awesome.  I did make a ticket and never got a response.  Minoru is my
ffxi char name

**Comment by KnowOne134** [comment]
Please make a new ticket into the gm team to look into your specific issue
