### ISSUE TITLE
Kirin Dia3 duration 

### ISSUE THREAD

**Issue by KeziaC** [EdenServer/community#4490]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Version 30181205_0

Kirin resists Dia3 duration. I'm not sure if it extends to other high level NMs, but we fought 3x Kirin and Dia 3 duration was consistently 45s. I have 3/5 Dia 3 merits, duration should be 90s. Tested Dia 2 and Bio3 - each were hitting the correct duration.

After all Kirins were done, went and tested on a random weapon type mob in sky, Dia 3 lasted the correct 90s duration.

Seems to be something with at least Kirin resisting the duration of Dia3 - it was 50% the duration of what I had expected. Did not see any other durations. Dia 3 should not have a shortened duration AFAIK. 

Reproducable steps - Allocate Dia 3 3/5, cast it on Kirin, watch the duration of the effect.

**Comment by 59blargedy** [comment]
Kirin has .5 sdt to light so it will automatically halve durations of dia (same with bio since his sdt is .5 for dark). whether or not sdt should affect dia/bio durations is a good question as i dont think it should, but just explaining why the issue exists for now (and that it affects any mob with .5 light sdt and any level of dia)

**Comment by KeziaC** [comment]
That's interesting (I won't pretend to know what sdt is haha) because I also cast Bio3 and Dia2 on Kirin to test the duration, and they both had the full duration. I only cast Bio3 and Dia2 once each IIRC but their duration was normal. Maybe there is something specific to Dia3?

The RDM channel in the discord seems to be split - some think the duration resist is normal, others stating Bio/Dia should always be max duration. The very limited research I did only showed the initial damage hit to be resisted, not the duration. At the end of the day this isnt a huge game-changer either way. Appreciate the explanation/investigation!

**Comment by Slamm21** [comment]
duration resist is definitely impossible for dia and bio
damage can resist though.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
