### ISSUE TITLE
A l'Outrance proc % incorrect

### ISSUE THREAD

**Issue by Clonegoat** [EdenServer/community#4491]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The Scythe "A l'Outrance' [Lv.62 WAR/DRK/BST] has 'Additional effect vs. beasts: Darkness damage' which is supposed to proc 100% of the time. Unfortunately it only procs the "standard" additional effect proc rate which I believe is 2.5~5% somewhere in that ballpark. I was fighting Dhalmel with it yesterday and today for quite some time skilling up, and it certainly was not 100%

I am running version 30181205_0
I run damage on screen only so I sadly do not have a screenshot of it not being 100%

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
