### ISSUE TITLE
60k GP in one day

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4495]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Not sure if this is a gm issue or a bug report so sorry if this doesn't belong here but: 

Went from ~18000 -> 85000 GP after doing my gp for the day. 

https://cdn.discordapp.com/attachments/838019469108183050/884945459397922856/Gordonramsy_2021.09.08_002841.png

https://cdn.discordapp.com/attachments/838019469108183050/884945470445736048/Gordonramsy_2021.09.08_002845.png

**Comment by 59blargedy** [comment]
resolved by another dev in february 20, 2023 update
