### ISSUE TITLE
Uleguerand Milk is out of era

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4496]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

It was introduced in March 2008

https://ffxiclopedia.fandom.com/wiki/Uleguerand_Milk

https://ffxiclopedia.fandom.com/wiki/Uleguerand_Milk?dir=prev&action=history

**Comment by KnowOne134** [comment]
Remove item 5703 from npc Macchi Gazlitah
DELETE from mob_droplist where itemid = 5703;
DELETE from char_inventory where itemid = 5703;
DELETE from AH and Delivery_box

**Comment by KnowOne134** [comment]
Is in era now
