### ISSUE TITLE
Quick Draw Dispelling Debuffs

### ISSUE THREAD

**Issue by awibmer** [EdenServer/community#4498]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

This bug was noticed and tested numerous times over several hours during an exp party using primarily Ice Shot. The monsters would receive paralyze from the RDM, paralysis would noticeably affect and trigger normally. When Ice shot is fired, instead of buffing the paralyze effect I as the COR noticed my text log mentioning "The [monster's] paralysis effect has worn off." Right as the Ice Shot is used and from then on the paralyze would not trigger until it was either reapplied by the RDM or until the end of the fight.

Steps to reproduce:

1. Have paralysis land on mob
2. Use ice shot
3. "The [monster's] paralysis effect has worn off." should appear only in COR's log

**Comment by 59blargedy** [comment]
couple questions to help troubleshoot, as i am unable to duplicate this: what level party? were you wearing any gear that affects quick draw? were there other debuffs noted with a similar wears message or just paralyze? was the wears message in standard chat log or do you use battlemod?

**Comment by awibmer** [comment]
>what level party? 

Level 68-69? Fighting at the Mamool Ja staging point against Puks and Mamool ja stabler and raptor. Level sync'd, also.

> were you wearing any gear that affects quick draw? 

Yes, COR AF hat.

> were there other debuffs noted with a similar wears message or just paralyze? 

I did not test other debuffs extensively, only paralyze once I noticed it.

> was the wears message in standard chat log or do you use battlemod?

Standard chat log

**Comment by 59blargedy** [comment]
hmm, i cant replicate locally, paralyze is increased properly with ice shot and doesn't immediately wear. if you happen to have this happen again soon, can you get a screenshot / vid? thank you!

**Comment by awibmer** [comment]
Will do, thanks!

**Comment by joercasey** [comment]
I did two tests. The results are inconsistent. Debuffs seem to be removed under some unknown conditions (higher level mobs?).

**Test 1:** Lv75 COR/RDM, AF hat; targeting goblins in Buburimu.
1. COR/RDM casts Paralyze on goblin.
2. Same COR Ice Shots goblin. Note: there was no "effect wears off" message.
3. Same COR casts Paralyze on goblin again.
**Result**: "Paralyze has no effect."
![image](https://user-images.githubusercontent.com/5439017/134336775-1bcfc148-23b2-442a-bcfa-f21b1d85bcbf.png)

**Test 1a:** Lv75 COR/RDM, AF hat; a second character to cast debuffs; targeting goblins in Bubu.
1. BLM/RDM casts Paralyze on goblin.
2. COR Ice Shots goblin. Note: there was no "effect wears off" message.
3. Same BLM/RDM casts Paralyze on same target.
**Result**: "Paralyze has no effect."
![image](https://user-images.githubusercontent.com/5439017/134337391-99507225-ecb6-4e58-a2c8-500bb69d7271.png)

Later, I did some assaults and wanted to see if the debuffs were indeed staying on the mobs. 

**Test 2:** Lv75 COR/NIN, AF hat; another character casting Slow; targeting Mamool Ja in "Preemptive Strikes" assault.
1. BLM/RDM casts Slow on Mamool Ja Executioner. Mob is slowed.
2. COR/NIN uses Earth Shot. Note: I _did_ received an "effect wears off" message simultaneously with the Earth Shot damage, but that message is presented in my other window log, and thus was not captured in the screenshot.
3. BLM/RDM casts Slow again.
**Expected**: "Slow has no effect."
**Actual**: "Mamool Ja is slowed."
![image](https://user-images.githubusercontent.com/5439017/134338162-f4dfcbae-876f-4dd1-a5dc-c5f4d33acad3.png)

12 seconds between first slow and Earth Shot; 7 seconds between Earth Shot and 2nd Slow spell.

**Test 2a:** Same as 2, but with Paralyze spell.
1. BLM/RDM casts Paralyze on Mamool Ja Executioner. Mob is Paralyzed.
2. COR/NIN uses Ice Shot. Note: I _did_ received an "effect wears off" message simultaneously with the Ice Shot damage, but that message is presented in my other window log, and thus was not captured in the screenshot.
3. BLM/RDM casts Paralyze again.
**Expected**: "Paralyze has no effect."
**Actual**: "Mamool Ja is paralyzed."
![image](https://user-images.githubusercontent.com/5439017/134338381-cbf31884-3e9a-45f0-886c-ad9b4b10605c.png)

8 seconds between first paralyze and Ice Shot; 9 seconds between Ice Shot and 2nd Paralyze spell.

**Comment by 59blargedy** [comment]
thanks for the addl data. i still cant replicate but we'll keep trying, clearly there's something wrong

**Comment by bliven-was-taken** [comment]
Here's another example sorry it doesn't have full data. 

[23:10:15] Bliven casts Slow II.
Proto-Omega is slowed.

[23:10:26] Dekustick uses Earth Shot.
Proto-Omega takes 140 points of damage.

He told me in voice that he was getting the message about it wearing off, so I decided to cast slow II again.

[23:11:04] Bliven casts Slow II.
Proto-Omega is slowed.

https://cdn.discordapp.com/attachments/755879656439152770/894427214475575296/edenxi_2021-10-03_23-13-14.png

[23:14:10] Bliven casts Slow II.
Proto-Omega is slowed.

https://cdn.discordapp.com/attachments/755879656439152770/894427207097790464/edenxi_2021-10-03_23-14-25.png

I didn't think to cast slow again after that one. He didn't think to screenshot until I told him to before that.

**Comment by statuseffect** [comment]
This appears to be occurring again. Not sure how long it's been going on but I've noticed it a few nights ago fighting Byakko and last night in Gigas. 
![image-4](https://user-images.githubusercontent.com/62901732/215112423-329c7645-ee2f-4479-9c2d-52d6c1fc2f4d.png)

Friend casted Dia II, I Light shot to upgrade to Dia III. Chat log says Dia wears off, friend can apply Dia when it should have no effect.

**Comment by boggartff11** [comment]
I see this issue pretty consistently when fighting enemies in limbus with paralyze and slow getting removed by quick draw.

**Comment by doughnuteden** [comment]
I have recently been encountering this issue. It might be potentially related to weather: either same and/or opposites. I didn't save a screenshot but I earth shot Fafnir (commonly thunder weather) and that caused slow 2 to fall off. I attached some screenshots of  some playing around in Limbus today with light shot. Zone was Temenos 1st Floor (always double light weather).

![image](https://user-images.githubusercontent.com/132183590/235335433-fa3250f8-9397-47d2-847a-06677493e865.png)
![image](https://user-images.githubusercontent.com/132183590/235335434-d09b369c-67b0-42cd-9ce2-abe12e70134e.png)
![image](https://user-images.githubusercontent.com/132183590/235335445-71684e02-3b6a-4d38-8f0a-2b80987466a1.png)
As you can see in that last screenshot I didn't even need to land light shot for it to make dia fall off.
I did some testing outside Bastok on level 1 mobs just to see what would happen and everything functioned as expected.
![image](https://user-images.githubusercontent.com/132183590/235335502-cbccc685-a44e-4fb5-90d7-d242f3ed919e.png)
![image](https://user-images.githubusercontent.com/132183590/235335442-026e11fd-7b8b-4ab1-b6ea-e3243f72b425.png)

**Comment by doughnuteden** [comment]
Doing some more testing with higher level mobs.
![image](https://user-images.githubusercontent.com/132183590/235335841-75ecec43-2358-4712-8968-6be5b9689b59.png)
![image](https://user-images.githubusercontent.com/132183590/235335867-42fe6fd2-a416-4ae0-a5f5-fc2e0f42bdae.png)
![image](https://user-images.githubusercontent.com/132183590/235335872-93f2b124-15b7-476b-8fd5-633f592dd3f2.png)

**Comment by StriderClerix** [comment]
Seems to be intermittently happening.  Had it in nyzul 80 on a cerberus, Dia would immediately wear off (no other debuffs), then the next run it would work as intended. 

It broke on merit pt colibri and wivres for an entire day a week or two ago.

**Comment by doughnuteden** [comment]
Mob level or perhaps mob stat seems to be involved somehow. Very consistently didn't have any issues on lower level mobs

**Comment by statuseffect** [comment]
Happened yesterday with dia2 + light shot on Hakutaku.

**Comment by StriderClerix** [comment]
Lightshot dispelling dia in nyzul isle on 7/17 

was working the week prior.

**Comment by StriderClerix** [comment]
Seemingly fixed at JOL today, 8/8/2023.

Unsure if it is a Aht Urghan zone vs COP zone issue; or if monday's maintenance reset the spaghetti code.  I haven't been able to test in toau areas yet.

**Comment by StriderClerix** [comment]
![ffxi_2023 10 29_23 13 02](https://github.com/EdenServer/community/assets/46233090/c849ecb9-9182-42b0-847c-a2761affc717)
![ffxi_2023 10 29_23 13 33](https://github.com/EdenServer/community/assets/46233090/97198145-950a-48ac-8c8c-ae17c7ac0ccb)
![ffxi_2023 10 29_23 16 36](https://github.com/EdenServer/community/assets/46233090/7f295f5b-dad5-4fff-baba-b927e826540a)
![ffxi_2023 10 29_23 16 38](https://github.com/EdenServer/community/assets/46233090/848ccf63-3d97-4742-ba6b-8c93439f5f88)
![ffxi_2023 10 29_23 16 47](https://github.com/EdenServer/community/assets/46233090/2ff5972e-e3b4-452c-9516-3da24dec3a11)


https://discord.com/channels/482610771126386688/670754275877453834/1168387219225055262
You can follow from this message on, showing what each SS is.

**Comment by StriderClerix** [comment]
Relevent: We are meriting, and i noticed it happened some time after I used a darkshot to dispel a wivre's granite skin after I had used a light shot to boost up his Dia2. 
 (It was working up til then) - 2nd chain around.   Might correlate with that somehow.

**Comment by StriderClerix** [comment]
Update: Also removing Paralyze in Sea in Ix'Aern

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
