### ISSUE TITLE
Love and Ice

### ISSUE THREAD

**Issue by Kurokami5297** [EdenServer/community#4501]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
30181205_0

Cannot start Love and Ice quest despite having proper prereqs.

**Comment by Kurokami5297** [comment]
![image](https://user-images.githubusercontent.com/74320120/133025307-0dd8e174-1bde-46d0-8206-d3d00766abd9.png)

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update

**Comment by Mozzy4Ever** [comment]
Now you'll get the finishing cutscene and the "quest completed" noise, but vars/quest won't change nor will you get the rewards.

**Comment by 59blargedy** [comment]
that would be a different unrelated issue needing a new ticket, but i dont see a problem. did you have a full inventory?

**Comment by 59blargedy** [comment]
ah i do see an issue at the end, it's fixed for next update
