### ISSUE TITLE
Guard should be able to proc during mobskill (and assumedly ballista ws)

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#4507]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently guard does not proc on monster tp moves or when fighting players in ballista.  
Per https://ffxiclopedia.fandom.com/wiki/Guarding_Skill, guard can proc on tp moves. for multihits, it will proc on one hit only. 
it's unclear what is meant by nullify - if guard reduces pdif to 1 that's not fully nullifying dmg, so admittedly more research is needed on this to determine what to implement. 

NOTE: the earliest mention of guard proccing on monstertpmoves is April 2008, however I cannot find mention in update notes of this changing, so believe it was applicable in era as well.

**Comment by Herralaze** [comment]
From [this journal](https://genomeffxi.livejournal.com/profile) page, it says Guard can proc on WS , it completely nullifies dmg and it shows this :
![image](https://user-images.githubusercontent.com/71975492/134103656-f4008051-0060-44be-9d37-11a68a769440.png)

You can find a lot of good infos about Guard here : it's from April 2008 but you can tell he'd been testing guard for months
 [https://genomeffxi.livejournal.com/18269.html](url)

**Comment by 59blargedy** [comment]
this was resolved a couple months ago, missed it in a bug report closing wave
