### ISSUE TITLE
Ilrusi Atoll - Sanction Regen / Refresh

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4508]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently the regen / refresh sanction buffs seem to not function when in the Ilrusi Atoll assault areas. They should function here like they do in the other Aht Urhgan areas.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
