### ISSUE TITLE
WHFO Snow Devils

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4510]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently snow devils in When Hell Freezes Over will link with each other. Retail testing has shown that they do not link.

https://www.youtube.com/watch?v=-ZcgY5h04Z8 - shows them not linking

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
