### ISSUE TITLE
Attack increase % of Boost should be 12,5 not 12

### ISSUE THREAD

**Issue by Herralaze** [EdenServer/community#4511]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
As stated in the title, 
Boost attack increase % is now close to 12% while it should be 12,5% as specified on wiki.
Doesn't sound huge, but the difference adds up.
Thanks :)

Version 30181205-0

**Comment by 59blargedy** [comment]
just as a note to save time for dev work, all mods are integers, so while it has 12.5 in the lua, the actual mod is floored. i think it would require overhaul of mods to fix (so sadly not an easy solution)

**Comment by KnowOne134** [comment]
Up the values ×10 and outcome /10

**Comment by 59blargedy** [comment]
i thought of that but didn't think it would work with where this mod is procced - go for it if it will, would be so much easier.

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
