### ISSUE TITLE
Currently players can get a new key every Vana'diel day when it should be once per conquest tally.

### ISSUE THREAD

**Issue by slassen** [EdenServer/community#4514]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
30181205_0

Visit `scripts\zones\Caedarva_Mire\npcs\qm8.lua` in dsp. Click and receive a new key once per vanadiel day.

Currently players can get a new key every Vana'diel day when it should be once per conquest tally.

Before era it was only an item drop, during era this was once per conquest week. It was later changed to once per real life day and then to its current state once per Vana'diel day.

[Players can now receive a new Lamian fang key by checking a “???” point in Caedarva Mire after each Conquest results tally.](http://www.playonline.com/pcd/update/ff11us/20060725vNusN1/detail.html)

It wasn't changed to the next tier (once per real life day) until sometime in 2012.

**Comment by KnowOne134** [comment]
resolved in October 4, 2021 update
