### ISSUE TITLE
Dyna Xarc eyes near first time extension should patrol

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4515]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Start video at 1:13(Mute before loading) https://www.youtube.com/watch?v=3ZtvtykeKCI

Currently the eyes around the first TE are stationary and easy to pull. They should patrol around the statue. I tried to find a better era video but this was the best youtube could offer unless I missed something. 

https://static.wikia.nocookie.net/lowdroprates/images/1/15/Xarcabard1.jpg/revision/latest?cb=20100430122508
Eyes 006, 007, 008, and 009 on this map

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
