### ISSUE TITLE
Last Resort attack % increase is wrong

### ISSUE THREAD

**Issue by Herralaze** [EdenServer/community#4516]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Client Version 30181205-0

By default (with no merit) : 
Last Resort attack bonus is currently 25% while it should be around 15% (38/256) as Wiki says.
Same goes for the Defense Malus, it's now -25% instead of -15%.
/cheer

**Comment by 59blargedy** [comment]
here's proof that it was 15 in era:
https://forum.square-enix.com/ffxi/threads/46976-May-14-2015-%28JST%29-Version-Update
if you can, try to provide links to wiki/updates proving your bug report to save our (very small) dev team time researching, but either way, reports are appreciated.

**Comment by Herralaze** [comment]
Ok roger that, was thinking I didn't need to, since it's in the Eden Wiki too ^^
Thanks for your time :)

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
