### ISSUE TITLE
BCNMs don't have time out messaging

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#4517]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
The time out messaging doesnt appear for bcnms when you run out of time on the battlefield. if you run out of time, you are correctly warped out, but do not receive messaging.
I haven't tested all zones, but this occurs at least in waughroon shrine. 
correct messaging sample from retail:
![image](https://user-images.githubusercontent.com/52636208/134395816-b96c8b02-1295-4023-9176-fd6eed904614.png)

**Comment by KnowOne134** [comment]
Corrected on 7/5/2024
