### ISSUE TITLE
ws gorgets make EES do 0 damage

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4518]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Without Gorget: https://cdn.discordapp.com/attachments/670753880396660764/890325272992305172/unknown.png

With Gorget: https://cdn.discordapp.com/attachments/670753880396660764/890325424771596389/unknown.png

**Comment by rude-jerk** [comment]
Resolved in patch on October 4, 2021.
