### ISSUE TITLE
Relic weapon additional effects proc too infrequently

### ISSUE THREAD

**Issue by tacbox3** [EdenServer/community#4519]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

**What should the proc rate be?** 
Numerous reports from era place the proc rate on relic melee swing additional effects somewhere in the 5-10% range. Here are a few quotes from era threads:

_"Additional effects proc at a very similar rate on relic weapons from what I have seen, and it should be around 10%"_ (1)

_"[Gungnir] Proc rate would be about 10% on IT mobs. It's wind based debuff so it will never proc on wind immune/absorb mobs such as Puks... It procs alot more than Thallasocrat and Mezraq. It also overwrites itself to extend the duration"_ (1)

_"Just going on eyeballing (yes I know that sucks) with 1 year of Amano, I would easily say 8-12% proc rate regardless of mob... 5% seems extremely low"_ (1)

_"while you will obviously have fewer overall hits _[NOTE: this is referring to accuracy of melee swings]_ on HNM, from what I have seen the proc rate is consistent"_ (1)

In this source, the question "does this still proc on HNM" is directly asked, and the answer is essentially: yes, proc rate does not depend on the mob. One commenter also suggests that relic AEs proc at same rate as Thalassocrat/Mezraq. A number of people jump in to say no, this is wrong. Proc rate on relic AEs is higher than those weapons. A kikoku user says "wait... my proc rate is 5% at most." And the reasons for this are discussed - it actually shares the same 10% proc rate from all relic weapons, but is unable to overwrite itself due to the nature of the debuff (paralyze). Because it can't overwrite, it won't apply if the mob is already paralyzed, from Kikoku or any other source.

Other era references:

_"From what I hear the DEF down effect from Gungnir proc is fairly frequent and potent, I think most Gungnir users are pretty happy with it"_ (2)

_"Defense Down procs that happens quite often"_ (2)

_"the para... procs VERY often"_ (2)

**What are the relic AE procs like right now?**  
Right now on Eden, the proc rate on "standard endgame mobs" (dynamis and merits) is around 2%, and the proc rate on HNMs (i.e. JoL, Cerb) is essentially zero. This is due to a macc check that is being applied to the 10% proc rate, per RJ. Here are some parse summaries illustrating this. For the full data, you can contact Contrabanned or Falaras.

**"Standard" Endgame Mobs**
Bird Merits 1.04% Bravura, 2.27% Amano, 2.10% Amano2
Full Xarc 0.92% Bravura.
Dynamis Bastok* 2.3% Bravura, 2.94% Amano
Dyna Glacier Goblins and Hydras 1.98% amano (7/353), 1.89% gungnir (6/317)
*A Mezraq was also parsed here, and had essentially the same proc rate at 2.91%

**HNMs or other big mobs**
Hydra 2.01% for Bravura
JoL .0.35% Bravura, 1.41% Amano
JoL 0.36% Bravura, 2.16% Amano
JoL 0% gungnir x2 (0/773)
Cerberus 0% gungnir (0/52)

I am happy to collect additional data if it helps in any way.

It's worth highlighting that the people in the era threads above are reporting _apparent_ proc rate, on IT mobs and HNMs. So if it is true that there is a macc check, the base (pre-adjusted) proc rate would have to be _higher_ than 10%. Alternatively, and more likely given the testamonials above, it may be that there is no macc check. This fact has already been established for at least one relic AE. (3)

Further, the discussion about some relic AEs overwriting themselves implies a much higher proc chance than we see on Eden. With the Eden rates, the odds of two procs occuring close enough for this to be observed is less than 0.1%. And in practice, mobs living long enough to observe this event pushes the occurrence rate much lower.

**Why hasn't this been noticed yet?** 
Likely because Gungnir's AE is the only one with real significance, and only two Gungnirs existed on Eden prior to last week.

**What are the possible fixes?** 
One of two things can be done. Either the macc check can be removed, or the base (pre-macc check) proc rate can be increased to move the apparent (post-macc check) proc rate closer to these reports from era. Given that one source reports that wind-immune mobs cannot receive a wind-based defense down proc, there is likely to be some kind of elemental check. But it may be a simple immunity check instead of what is currently implemented.

**References**
(1) https://www.bluegartr.com/threads/77925-Gungnir-Additional-Effect/page2
(2) https://www.bluegartr.com/threads/63762-Rate-your-relic-weapon/page7
(3) https://www.bg-wiki.com/ffxi/Additional_Effect

client version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
