### ISSUE TITLE
Carmine Dobsonflies aren't repopping correctly

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#452]
10 copies of this NM are supposed to spawn at the same time, 21-24 hours after death on the island at G-11 in Riverne A01. We killed them a few days ago and came back to kill again today, but none of them respawned on the island. There was only one fly that popped at the spatial displacement that you take to portal to the island at F-10.

https://ffxiclopedia.fandom.com/wiki/Carmine_Dobsonfly

**Comment by panfunk** [comment]
Not an error, I killed 9 of them. Sorry man! :D

**Comment by godmode** [comment]
Well that solves it! Lol

**Comment by panfunk** [comment]
![image](https://user-images.githubusercontent.com/36666121/49752331-5973b900-fcb0-11e8-8423-561d367aeb51.png)

**Comment by Oyaziiiiiii** [comment]
Oh strange. There was one fly that didn't run back to the island though, it was just stuck outside. Was there an issue with them all zoning through the displacement/linking?

**Comment by panfunk** [comment]
Yea I tried to 'zone" the last fly with the displacement, but it ran after me and flew to the displacement leading to the dobsonfly island

**Comment by panfunk** [comment]
that reminds me that I wanted to make a bug report that these displacements don't make you 'zone' as they should
