### ISSUE TITLE
Tauros Mob Linking with Demon in Uleguerand Range

### ISSUE THREAD

**Issue by jdpitt05** [EdenServer/community#4520]
### Checklist

- [ X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X ] I have provided my client version in the details. (type /ver into your game window)

### Details

At F-7 in Uleguerand Range when pulling Demons, the Tauros mob there (Molech) links with Demons.  I've done this a few times to ensure I didn't get true sight aggro while pulling but the Molech does link with the demons.  This is low priority but thought I'd submit a report as I didn't think Tauros mobs should link with Demons.

Version 30181205_0

![Jerf_2021 09 23_125416](https://user-images.githubusercontent.com/73665771/134553490-aabd3975-df5c-437a-a077-a2d1b2ce28bf.png)
s.

**Comment by dowzer** [comment]
They're supposed to link with Kindred and vice versa.

**Comment by jdpitt05** [comment]
Ok thanks for info. I wasn't aware of this.  I can close this.
