### ISSUE TITLE
Maneuvers are giving OOE stat bonuses

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4521]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently Maneuvers are giving a scaling bonus based on level, scaling up to +6 at 75 (+7 with AF hands). 

The update that gave maneuvers scaling bonuses based on your level is from 2010
http://www.playonline.com/pcd/verup/ff11us/detail/5338/detail.html

![image](https://user-images.githubusercontent.com/13668758/134673254-35b543e9-cc13-409d-bd29-ce0c7e1c03de.png)

As you can see in the 2009 wiki page, base maneuvers (without AF hands) were only giving +1 to each stat until this update. 

https://ffxiclopedia.fandom.com/wiki/Fire_Maneuver?oldid=1044621

You can also see this limit of era maneuvers referenced on this era wiki page for AF hands, where it outlines +1 per maneuver, and +2 with AF hands.

https://ffxiclopedia.fandom.com/wiki/Puppetry_Dastanas?oldid=328748

**Comment by KnowOne134** [comment]
Adjust bonus formula on each maneuver lua to :

local bonus = 1 + target:getMod(dsp.mod.MANEUVER_BONUS)

**Comment by KnowOne134** [comment]
resolved in October 4, 2021 update
