### ISSUE TITLE
Automatons shouldn't use TP immediately upon gaining it

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4522]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I do not have a retail account but from what I can tell this is able to be validated even today on current retail.

On Eden today an automaton will immediately use its TP after crossing the 1k TP threshold unless you are using an inhibitor, in which case it waits to close a skillchain. 

It appears as though correct behavior is a bit less predictable. I'm summarizing my findings here (again if someone can test this in retail without using new attachments or equipment that changes functionality that would be amazing), but it seems as though automatons will randomly use their TP between 1k and 3k TP similar to monster AI (my observation, the comparison may not be exact). This AI seems subject to several factors, but it does seem like having a Fire Maneuver active will "suggest" to your puppet that it should use its TP soon after crossing the 1k tp threshold. There is another weird note about its AI with Daze, but I'll detail that below.

Here are some of the notes I've come across that indicate behavior different than Eden:

The current wiki page for Fire Maneuver
https://ffxiclopedia.fandom.com/wiki/Fire_Maneuver
"Using Fire Maneuver will force an Automaton to use its TP almost immediately after reaching 100%." 

Fire Maneuver page from 2010
https://ffxiclopedia.fandom.com/wiki/Fire_Maneuver?oldid=1098063
"Using Fire Maneuver will force an Automaton to use its TP almost immediately after reaching 100%. Usually an Automaton will wait until a target is readying a TP move or casting a spell to use Daze, a Fire Maneuver will prevent this."

Really weird AI note there about Daze (which has a stun). That would require some amount of retail testing to learn more about that behavior.

A random forum post from 2011 after an update
https://forum.square-enix.com/ffxi/threads/16451-Pupdate-10-28-2011?p=223357
"As it stands, the automaton will perform weapon skills in an INCREDIBLY unintelligent manner, both with and without the inhibitor (the inhibitor changes how it does weapon skills, but it changes it to an equally unintelligent and undesirable method). Without the inhibitor, the automaton will randomly WS between 100 and 300 TP, with the likely hood of WS increasing with how much TP it has (I have only ever once had my puppet hold TP to 300%, but wow was I annoyed), typically this results in the puppet wasting 30~70 TP every WS, occasionally more when it decides to hold past 200%."

The next page in the same forum
"I just want /pet "Armor Shatterer" <t> seems even simpler. I know it is possible since you can do those macros with bst jug TP moves. I hate sitting there saying, would you go poppo, go dammit, then it waits till mob is 2 percent and does a 3k ws. why thanks poppo you idiot. Only other option is to pull the puppet off and lose dmg also."

Some of those should be taken with a grain of salt. There could be people who don't understand inhibitor, or people who are perceiving Daze stunning an enemy ability and confusing luck with AI, but in general it seems like the consensus is that even in retail today automatons using era parts will no immediately use their TP at 1k by default.

**Comment by KnowOne134** [comment]
I do have a retail account and noticed that it will hold tp to a certain point then use. I only just unlocked pup a few days ago and it's in the 50s now and I'm just powering through so not really collecting the data

**Comment by E5una** [comment]
Awesome, feel free to DM me on discord if you want to work together on outlining any tests for how to hone in on its correct behavior.

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
