### ISSUE TITLE
Meikyo Shisui Issues

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#4523]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

Meikyo Shisui currently gives you the TP return of the WS you use while under its effect, it should not do that. The only way to gain TP under the 2h effect should be Meditate and getting hit. 

Have a Samurai Maat video for your trouble (and to verify): https://www.youtube.com/watch?v=PzV3oMsp14Y

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
