### ISSUE TITLE
Manticore Family Heat Breath

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4525]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently this TP move scales too well with the amount of HP a manticore has. There should be more of a fall off in damage the lower HP it has. On retail I had a level 13 carbuncle from subbing SMN get hit by a level 77 greater manticore's heat breath at 16% HP and it inflicted 151 damage to it. On Eden you'd get hit for the full damage cap of 500 from the same level mob at that percentage of HP.

https://www.youtube.com/watch?v=aycgaPRh2eI - timestamps of the heat breaths used are in the description

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
