### ISSUE TITLE
Steam Cleaner doesn't despawn

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4526]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Steam Cleaner should despawn after being passive for 2 minutes (https://ffxiclopedia.fandom.com/wiki/Steam_Cleaner?oldid=568343). Using the test server, it stay up for over 1.5 hours despite never being claimed.

**Comment by slassen** [comment]
Is this original sky behavior? I honestly don’t remember but I may have specifically changed it to not despawn if that’s the case way back in the day. Again, I can’t remember. But thought I’d comment in case it was.

**Comment by KnowOne134** [comment]
Add mobmod
IDLE_DESPAWN, 120
