### ISSUE TITLE
Yomi Okuri

### ISSUE THREAD

**Issue by Raulfin** [EdenServer/community#4529]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver 30181205_0

In the second part of the quest if the 2 NMs, Doman and Onryo, are spawned before 0500, but not killed before 0500 the game will either: 
A) Not give credit for the kill and the player must wait untill the next chance to spawn them at 1900, but must zone to respawn them, like the kill is marked as failed at 0500.
B) Get credit, but not be able to get the item untill after 1900 if they don't zone.

A happened to me,  and 2 days later B happened to a friend i was helping with the quest.

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
