### ISSUE TITLE
Panacea is missing slow effect removal 

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4531]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

![image](https://user-images.githubusercontent.com/11255886/135133667-2aca288a-05f9-46fd-878b-9955afdfe448.png)

Per wiki, Panacea should act as if erase was cast on you and can remove multiple affects at once.

**Comment by KnowOne134** [comment]
Add line:
target:delStatusEffect(dsp.effect.SLOW)
To flask_of_panacea.lua

**Comment by KnowOne134** [comment]
resolved in October 4, 2021 update
