### ISSUE TITLE
Scavenge Cooldown

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4533]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently scavenge has a cooldown of 3 minutes which appears to be a change done in 2013. In era the cooldown of scavenge was 5 minutes.

https://ffxiclopedia.fandom.com/wiki/Scavenge?oldid=348951
https://www.bg-wiki.com/index.php?title=Scavenge&oldid=22660

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
