### ISSUE TITLE
Shield of Diplomacy - Khimaira 13

### ISSUE THREAD

**Issue by Raulfin** [EdenServer/community#4534]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver 30181205_0

During the fight against Khimaira 13 after 28m, in a rdm/whm blm/rdm duo, the boss was at 35-40%. Karababa's AM2s were only doing 30-300 dmg, (at most half seem to have done 300, while half did 30-250) while the BLM was doing 250 with Bliz3.
Seems the boss Mdef may be off similar to #4399.
Boss also had a very high regen, bio 2, psn 2, burn, choke, and shock were barly able to match the regen.
Karababa would also stop casting completly if the boss turned off her for more than a few seconds.
Karababa whould not "phase", after taking a lot of dmg, gaining a large Mattk bonus and changing to only cast AM1s

In era testimonials reported rdm/nin dot kite solos and smn kite solos both in the 15m range, by estimate a dot duo, currently, would take about 50m-70m. 
One a nin/war tanked it to 70% then died and Karababa was able to solo the rest, this too would not be possable currently. Partly also because Karababa takes about 250 dmg from a melee hit and can easily die after a few hits (she seems to have about 2.5k Hp).

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
