### ISSUE TITLE
Charm status on players should reduce movement speed

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4536]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Charmed players currently move at normal speed. Both bg wiki and era wiki state that players should move at reduced speed while charmed.

Can't find any numbers but both pages mention slight reduction so I assume equal to a piece of dusk gear -12%

https://www.bg-wiki.com/ffxi/Charm_(Status)
https://ffxiclopedia.fandom.com/wiki/Charm_(Status_Effect)?oldid=366003

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
