### ISSUE TITLE
Dyer's Woad is harvestable (OoE?)

### ISSUE THREAD

**Issue by AzrielltheWise** [EdenServer/community#4537]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I am able to harvest Dyer's Woad in West Sarutabaruta.  The Eden guide does not have a page for it, but FFXIclopedia shows its page as being created in 2008, so I believe it is OoE.  

Not sure about reproducable steps.  I just harvested 3 of them.  New Moon, no HELM gear, West Sarutabaruta.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
