### ISSUE TITLE
Overlord Bakgodek should drop D Ingot

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4538]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver = 30181205_0

This video shows Overlord Bakgodek dropping a D Ingot: https://youtu.be/sUyFR9hLbPM?t=295
![image](https://user-images.githubusercontent.com/11255886/135685257-7a5a2b87-ccb5-4627-8f84-08b44f71576a.png)

There's also mention of it (sadly no screenshot) if it still dropping on retail in 2011: https://ffxiclopedia.fandom.com/wiki/Talk:Overlord_Bakgodek?diff=next&oldid=1252199

I imagine the drop rate was the same as Tzee/ZaDha, sadly there's not much for concrete data there though.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
