### ISSUE TITLE
BCNMs with summoner pets should have them up on spawn

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#4543]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
In bcnms like Jungle Boogiemen, Kindred Spirits, etc. the summoner should already have his pet out. On eden currently, the mob will summon his pet upon engage, which can occur post-sleeping and mess with a sleep strategy.

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
