### ISSUE TITLE
Quadavs with WoTG skin use wrong Shell Guard animation

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4549]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver = 30181205_0

Noticed the Ancient/Adaman Quadavs in Qulun dome contort their bodies when they use Shell Guard (mobskill ID 614). Tested the other WoTG skinned quadavs in Beadeaux and they do the same. Regular skins don't.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
