### ISSUE TITLE
Valoredge Automaton is doing nlunt instead of slashing damage

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4550]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I have not personally tested this but reporting on behalf of two other people that have confirmed it by fighting undead and, more importantly, Jailer of Temperance. They said Valoredge was dealing 0 damage during Slashing phase and dealing normal damage during Bludgeoning phase which is incorrect.

Its documented on a many pages but here is an example of one:
https://ffxiclopedia.fandom.com/wiki/Valoredge_Frame

Not sure is the other automatons need an audit, as well as their weapon skill damage types.

**Comment by Snugglepunk** [comment]
https://github.com/EdenServer/community/issues/3443 saw this issue a while back in limbus. Melee hits should be slashing but are blunt.
