### ISSUE TITLE
Promy LoS

### ISSUE THREAD

**Issue by Raulfin** [EdenServer/community#4553]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver 30181205_0
After the last update LoS is broken by the edges of the islands in promy zones.
https://imgur.com/6Lwq9md

**Comment by 59blargedy** [comment]
resolved in october 10, 2021 update
