### ISSUE TITLE
Thrown Returning Weapons TP Gain

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4554]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently thrown returning weapons seem to have the incorrect amount of TP returns when they hit and deal damage. For example using a Lamiabane should give 77 TP on a damaging hit but currently returns 145 TP. Thrown items that are equipped in the ammo slot give expected TP returns so might be an issue for only returning weapons as they are placed in the ranged slot.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
