### ISSUE TITLE
(2) Stroper Chyme ID wrong?

### ISSUE THREAD

**Issue by Clonegoat** [EdenServer/community#4555]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Killing Stroper Chymes for Shikaree's after the RMT Patch has lead to some interesting "drops" (none of which have been the ring in probably 100 kills but that's hopefully beside the point) The Stropers are named properly on mob, but their ID when killing them changes, sometimes? I've only noticed it on the 2 at the drop points, not the two in the upper hallway. The one to the East will often claim to be a Targe Beetle when it drops Oils, and the one to the West a Bilis Leech. I do not have the renamer addon, so I don't know if that would be the fix? I'm just hoping this isn't effecting drop rates as, I know it being a very rare drop but I'm also having quite the poor luck so I wanted to add this to be sure.
![Screenshot 2021-10-06 112857](https://user-images.githubusercontent.com/80860333/136245279-e75813b2-37c9-4386-b27c-1ddc9d2eedc3.png)
![Screenshot 2021-10-06 112932](https://user-images.githubusercontent.com/80860333/136245281-bc8a4392-1ec8-4950-a79c-031cba2b81cd.png)

**Comment by Clonegoat** [comment]
Also it depends on distance, I forgot to mention. On the character out of range, it'll display improperly, but the character who killed it will be correct. This screencap is the same time as the one where it claimed to be a Targe Beetle, from my other character's perspective.
![Screenshot 2021-10-06 113207](https://user-images.githubusercontent.com/80860333/136245751-39d209ac-cb44-44d0-92f5-0100fc1d33ba.png)

**Comment by 59blargedy** [comment]
drops are appropriate so going to close this one out. it's not a great drop chance as you can see from the link below. sounds like one char you have renamer loaded and one you dont, possibly. can check your addon load script
http://ffxidb.com/zones/193/stroper-chyme
