### ISSUE TITLE
LoS shouldn't halt already started casts

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4557]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

Currently on Eden if you start a cast on a mob and they move into a position where LoS would block your initiation of the cast, your cast will be interrupted. 
Per this video from retail (Ty Dowzer): https://www.youtube.com/watch?v=R6LCpfQrHLk this should not happen. If your cast starts, it should finish whether on a mob or player. Mob -> Player has this functionality, but Player -> Player and Player -> Mob do not.

**Comment by 59blargedy** [comment]
resolved by another dev in October 10, 2021 update
