### ISSUE TITLE
Fe'e (Up In Arms) lack of knockback

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4558]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
/ver = 30181205_0

When all of Fe'es tentacles are wounded, his fake ink-jet is supposed to have a knockback effect. Currently, it does not.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
