### ISSUE TITLE
Bee Family Pollen

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4563]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently pollen seems to under perform in terms of healing and does not really scale with the mob's TP. Retail testing has shown that this TP move scales with level and TP (may also be a % based heal that scales with TP as NMs can heal for more). 

https://www.youtube.com/watch?v=GiJI5q-htkY - retail level 41 bee in Crawler's Nest (healed for about 90-110 here on Eden)
https://www.youtube.com/watch?v=O-xCe-M9Cm0 / https://www.youtube.com/watch?v=iQrog6kBhIs - retail level 63 bee in Wajaom Woodlands (healed for about 250-280 from a level 65 bee on Eden)
https://www.youtube.com/watch?v=SQKZlcKyJmI - charmed this bee to kind of get a better look at its TP before it used pollen
https://www.youtube.com/watch?v=OKWDcPp2tlA - shows pollen from the NM Demonic Tiphia and how it can be annoying to kill with the healing it does from pollen

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
