### ISSUE TITLE
Pso'Xja elevator to Promyvion Vahzl possibly impassable for Galka.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#4567]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Possibly related to the Line of Sight patch. But the elevator leading down the Promyvion Vahzl is broken, and not just visually. We were told that eventually running through would get you to go past it. However, only smaller races were able to get through. Myself (galka) and another galka player were both stuck for over 10 minutes until we client-side race changed to something smaller, and set fps to 2. 
version 30181205_0

![InkedVolkaru_2021 10 08_071210_LI](https://user-images.githubusercontent.com/9113384/136578554-cb39d9bf-bb0a-4e50-9d12-ea3fa9107808.jpg)

**Comment by Raulfin** [comment]
It looks like if you /sit on the elevator it will let you get off on the bottom.

**Comment by 59blargedy** [comment]
resolved by another dev in an update within a week of this report, not quite sure when
