### ISSUE TITLE
When Angels Fall - Ix'zdei BCNM

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4568]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

When you enter the Ix'zdei BCNM of When Angels Fall they will immediately aggro and cast/attack at you when you enter. They should not immediately aggro so your party has time to enter / prepare. This issue might be related to the new line of sight.

version 30181205_0

**Comment by Volkaru** [comment]
Think we figured out what's causing the aggro, at least. The first person who enters isn't actually being teleported. It's making their body super speed run from the door all the way to the back of the arena, through the middle of the room, which is aggroing all four.
Can confirm this by watching another group with /fillmode on. The first person zooms through the entire room. And when someone tried exiting, it had them super speed through the door, back outside.

**Comment by Volkaru** [comment]
There is also an issue because of them aggroing, that sometimes people entering won't get BCNM status if they aren't all entering at the same time. Since the status no longer applies once aggro is generated. Each attempt we had a person not get status because they would be too late clicking to enter before aggro.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
