### ISSUE TITLE
Flame Holder not getting benefits of Overdrive.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#4570]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Flame holder, as well as any other attachment that eats maneuvers for an additional bonus is not receiving the full "1x maneuver is 3x maneuver" bonus of the PUP two hour Overdrive.
Even with Overdrive up, Flame Holder with 1x maneuver will still do the same amount of damage as 1x fire maneuver outside of the 2-hour. Compared to 3x fire outside 2 hour.
Tested on level 1 Tiny Mandragora with exactly 1k TP in every scenario.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
