### ISSUE TITLE
Ice Maker not getting benefits of Overdrive.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#4571]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Ice Maker, as well as any other attachment that eats maneuvers for an additional bonus is not receiving the full "1x maneuver is 3x maneuver" bonus of the PUP two hour Overdrive. This is probably also affecting any other similar attachments. I will test the ones I can, but ones like Replicator will be harder for me to test for.
Even with Overdrive up, Ice Maker with 1x maneuver will still do the same amount of damage as 1x Ice maneuver outside of the 2-hour. Compared to 3x Ice outside 2 hour.
Tested on level 1 Tiny Mandragora outside Windurst, same weather/day, same spell.

Additional Ice maker bugs for easy reference: #2355

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
