### ISSUE TITLE
ToAU Mission 31: Shades of Vengeance Cannot Enter With Less than 3 Players

### ISSUE THREAD

**Issue by HunnyDoo** [EdenServer/community#4572]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

30181205_0

https://ffxiclopedia.fandom.com/wiki/Aht_Urhgan_Mission_31:_Shades_of_Vengeance?oldid=428876

Currently you need a minimum of 3 people to enter the mission 31 boss fight. Unfortunately the earliest testimony that mentioned 2 people entering the mission is from Jan 2008 but no revision mentions a minimum of 3 people being mandatory.

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
