### ISSUE TITLE
Multiple movement speed decrease effects cause increased movement speed

### ISSUE THREAD

**Issue by ConteAlmaviva** [EdenServer/community#4573]
### Checklist

- [*] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [*] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [*] I have provided my client version in the details. (type /ver into your game window)
- [] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Last night in Temenos 1F, a couple of our melees were hit with Gravity and Curse while fighting the Enhanced Dragon (I think the special abilities are Lodesong and Chaos Blade respectively).  While both effects were active, our melees had hugely increased movement speed, almost like the variable controlling movement speed underflowed.

I'm not sure how to readily reproduce this, but if there's a test server where I can manually put both effects on myself I'd be happy to do so.

**Comment by falzum** [comment]
Used to encounter this same issue while wearing dusk gear with gravity from wrath of gu'dah in dyna bastok

**Comment by KnowOne134** [comment]
Its def an underfloor issue

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
