### ISSUE TITLE
Apollyon SE Metalloid Ameoba Linking Issue

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#4578]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

There's a specific duo on Apollyon SE floor 1 of Metalloid Ameobas that link on Eden but should not link. The video linked shows someone pulling them separate, I cannot recreate this on Eden as they will always both come doing that. Timestamped video: https://youtu.be/Ln0WgxSUwmE?t=434

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
