### ISSUE TITLE
NE Apollyon 2nd Floor Boss always the same

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4581]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

The first Bialozar (ID 16933065) is almost always if not always the boss of that floor. https://ffxiclopedia.fandom.com/wiki/NE_Apollyon?diff=357793&oldid=355700 says it should be any of the 4 Rocs on that floor.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
