### ISSUE TITLE
Orcish Overlord has no Double Attack

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4582]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
30181205_0

Per https://ffxiclopedia.fandom.com/wiki/Orcish_Overlord and https://youtu.be/DzzhA0jb4n8, Overlord should have at least DA trait. Currently on Eden it's PLD/PLD. In the (sadly short) video, it attacked 13 times with 2 DA. Can't find another video showing more of a sample size sadly :(

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
