### ISSUE TITLE
Overlord Bakgodek lacking TP drain

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4583]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Per https://youtu.be/H9BFC09lmsw?t=40
![image](https://user-images.githubusercontent.com/11255886/136896684-a762533d-30d9-4dd1-9217-c7c70d3da64d.png)

Overlord Bakgodek should have Additional Effect: TP Drain as the wiki states (https://ffxiclopedia.fandom.com/wiki/Overlord_Bakgodek?diff=351828&oldid=348689)

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
