### ISSUE TITLE
Quicksand Caves "NPC"

### ISSUE THREAD

**Issue by Raulfin** [EdenServer/community#4584]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

The sand drops in QSC now have a targetable marker named "NPC" that has to be clicked to drop to the level below. Specifically Drop B on map 2 @M9 (the coffer loop). It's the only drop on the coffer loop, and didn't check the rest of the drops in the other sections.

I have the renamer linked in the patch notes (EdenServer/community) installed and active.
/addon load renamer
/renamer load eden

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
