### ISSUE TITLE
Inaccuracies with Mythril Mouth Monamaq in Halvung

### ISSUE THREAD

**Issue by Spintimalli** [EdenServer/community#4586]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
version 30181205_0

Note that this NM is not important in the current implementation of Eden. However, it makes 2 Friar's Lantern spawns capable of dropping Smoky Flasks to spawn Big Bomb pretty much inaccessible. 

Sources:
- https://ffxiclopedia.fandom.com/wiki/Mythril_Mouth_Monamaq
- http://wiki.ffo.jp/html/12503.html

**Inaccuracies**
> Assisted by two Troll Mythril Guards (warriors). 
- They are DRKs, and they do not assist or link with Mythril Mouth Monamaq. 
- After defeating the NM, the guards remain up and respawn quickly if killed. 
- NM also respawns ~15mins after ToD. http://wiki.ffo.jp/html/12503.html says _"24 to 72 hours"_

> The Troll Mythril Guards respawn 5 seconds after being killed.
- They respawn fairly soon, but not 5 seconds later. Info from http://wiki.ffo.jp/html/12503.html says _"it will be defeated from the escort troll first , but the escort will not disappear even if it is defeated, and it will be revived when the frying pan of Mythril Mouth Monamaq is activated"_

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
