### ISSUE TITLE
Twinkbrix unresponsive when ENM is in cooldown.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#4587]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The NPC Twinkbrix in Oldton Movalpolis refuses to be interacted with if you have Pulling The Strings on cooldown. He will not mention your time left til you can reattempt, nor be interactable with at all. Clicking on him does nothing. 
EDIT: It's possible this is retail behavior, but need confirmation.

Ver. 30181205_0

**Comment by 59blargedy** [comment]
pushed fixes live, will be formally resolved next patch

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
