### ISSUE TITLE
Hydra Greaves NQ/HQ model

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4590]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently hydra greaves and their +1 version use the incorrect model. They are using scale greaves as their model instead of the proper one which is the one that gavial greaves use.

https://ffxiclopedia.fandom.com/wiki/Hydra_Mail_Set

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
