### ISSUE TITLE
Treasure and Tribulations (T&T) doesn't level cap/spawn mobs 

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#4592]
- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
30181205_0

T&T currently doesn't spawn mobs, level cap your char, or give BCNM status. Still breaks orb.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
