### ISSUE TITLE
Hide(If successful) Should stop enemy spell casting

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4594]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Dowzer made this video to show how hide makes a mob go passive and stop casting a spell with no message.
Current Eden behavior this spell would still go off
https://www.youtube.com/watch?v=djcVewiS5kA

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
