### ISSUE TITLE
Octave Club Hidden Effect may not function

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#4596]
Posting for Pants.

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Pants tried using Octave Club specifically as a level 64 RNG. Tried both with Level Sync and without Level Sync. Main hand or off hand. It only swings once, never multi-swings.

https://ffxiclopedia.fandom.com/wiki/Octave_Club

At level 64, it should be capable of hitting up to 8 times.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
