### ISSUE TITLE
Novv the Whitehearted is missing silence immunity

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4598]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Novv the Whitehearted should be immune to silence per the wiki

https://ffxiclopedia.fandom.com/wiki/Novv_the_Whitehearted

![image](https://user-images.githubusercontent.com/13668758/137501705-91759cee-9156-4eef-bbdd-731c2bba4510.png)

Era wiki page saying the same:
https://ffxiclopedia.fandom.com/wiki/Novv_the_Whitehearted?oldid=385437

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
