### ISSUE TITLE
 Cutscenes should pause status and drop aggro once initiated

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#460]
The Spatial Displacement don't drop all aggro from your chars as they should, iirc. 
Happened yesterday when I killed Carmine Dobsonfly. The last fly followed my char to the next island after using the Spatial Displacement. It flew through the abyss! :D

**Comment by Wiggo32** [comment]
This is a longstanding issue with dsp in general, something that certainly could use some digging into. But, yes, cs events should drop aggro and make the player unable to be aggro'd for the duration of the cs event. Although, this should not happen unless the player actually "makes it" into the cs event. So, just clicking the npc and pulling up the menu does not count. And actually, any attack by mobs or even friendly actions (cure, corsair rolls, songs, etc) will kick the player out of the menu completely before they actually reach the actual cs event. So, it is fairly difficult to lose aggro this way unless you have a significant distance from the mob and can navigate the menu quickly enough before it reaches you to make an auto attack.

**Comment by 59blargedy** [comment]
resolved october 11th update for majority of cs events
