### ISSUE TITLE
Repop stat in Dyna Jeuno is only targetable/attackable from underneath it + in the wrong location

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#4602]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver 30181205_0

Goblin statue #376 spawns next to the end boss and is not targetable while standing anywhere near it. We were only able to target it and attack it from down below where the fountain is in Dynamis Jeuno. Confirmed this is stat 376 on Dynamis Bums b/c it spawned the PLD NM Scruffix Shaggychest. Dynamisbums shows #376 as being on the lower/east side of the map, not near the last boss spawn. 

http://www.dynamisbums.com/strategy/images/maps/strategy_jeu2.jpg

<a href="https://ibb.co/T0pNGYF"><img src="https://i.ibb.co/xgPrbXR/Setsutaru-2021-10-16-185448.png" alt="Setsutaru-2021-10-16-185448" border="0"></a>

^ While standing next to it we only received the "Unable to see target" message.

**Comment by 59blargedy** [comment]
resolved by another dev in November 29, 2021 update
