### ISSUE TITLE
Firespit (BLU spell) should not be obtainable from Mamool Ja Zenist

### ISSUE THREAD

**Issue by nickycupcakes** [EdenServer/community#4603]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Client Version:  30181205_0
Reproducible Steps:  Kill Mamool Ja Zenist in Wajaom Woodlands as a BLU, learn Firespit spell
Screenshot:  https://ibb.co/r4jZzGn

According to [Wiki history from 2007](https://ffxiclopedia.fandom.com/wiki/Firespit?oldid=306062) Firespit should only be obtained from the mage Mamool Ja (Savant and Sophist) in Wajaom Woodlands.  I learned it from a Mamool Ja Zenist (NIN).

The screenshot does not show "defeats the Mamool Ja Zenist" but he was the only enemy I was fighting at the time.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
