### ISSUE TITLE
Ga'Fho Venomtouch shouldn't be a WAR & Goblin

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4606]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
30181205_0

Ga'Fho Venomtouch (ID 17326135) in Dyna-Beauc should be a Quadav WHM that spawns from the mega statue in the quadav area:
![image](https://user-images.githubusercontent.com/11255886/137829972-be246884-2a3d-469e-9f66-73840701147a.png)
http://www.dynamisbums.com/strategy/spawn_bcd.html#:~:text=%5B192%5D%20Dynamis%20Effigy
https://ffxiclopedia.fandom.com/wiki/Ga%27Fho_Venomtouch

Currently it spawns as a Goblin, and is a WAR.

**Comment by 59blargedy** [comment]
resolved by another dev in November 29, 2021 update
