### ISSUE TITLE
Stegotaur can aggro up some (or maybe all) ledges in Aqueducts after LoS patch

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4609]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On map 2 of Phomiuna Aqueducts, at K-10 ladder and I-6 ladder I got IT Stegotaur aggro while standing at the top of a ladder. This will definitely get some people killed as it used to be safe to stand up there (and should be). This is also a problem because even after climbing a ladder (which removes aggro) a stego can aggro you while you are standing at the top. I would assume this is at all ledge/ladders.

**Comment by Raulfin** [comment]
Agroing the upper areas seems to be correct behavior.
https://ffxiclopedia.fandom.com/wiki/Stegotaur
