### ISSUE TITLE
Goblin Swordsman missing followers and drop rate for Sylvan Stone

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4612]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On Eden, Sylvan Stone drop rate seems to be lower than it seems from era ffxidb/ffxiclopedia. Someone asked me to look into it after going 1/3 (TH2 no drop, TH4 drop, TH4, no drop) when the wiki says "Item Drops: Sylvan Stone drops 100% of the time; sometimes drops two copies at once."

https://ffxiclopedia.fandom.com/wiki/Goblin_Swordsman

ffxidb lists the item as over 90% drop rate from Goblin Swordsman

http://ffxidb.com/items/1781

In attempts to reproduce on the test server, I was 3/6 with TH0, which is high, but doesn't seem to match the info online. 

I think the relevance to the high drop rate is that there is a swordsman outside the ENM that is a convenient way for people to reliably get their drop.

On another note, both wikis list that the swordsman is followed by two other goblins and that they assist him, which I didn't have that experience when testing it. I'm assuming if it says they assist him, they aggro when you engage him.

https://ffxiclopedia.fandom.com/wiki/Goblin_Swordsman
https://www.bg-wiki.com/ffxi/Goblin_Swordsman

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
