### ISSUE TITLE
"Eight of Cups" mobs missing

### ISSUE THREAD

**Issue by Allorddemon** [EdenServer/community#4615]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

I came to the Outer Horutoto Ruins - Dahlia Tower looking for Eight of Cups mobs as they should spawn there.
There weren't a single one.
I've been checking for 2 days manualy and with Wide Scan ability, waiting for a spawn, but still can't find one.
DB says it should be 4 of them.
These mobs inflicts Mute through an Additional Effect by it's weapon, while Mute effect needed for "Catch It If You Can!" quest.
Info is taken from [https://classicffxi.fandom.com/wiki/Catch_It_If_You_Can!](https://classicffxi.fandom.com/wiki/Catch_It_If_You_Can!)

**Comment by 59blargedy** [comment]
> 
> 
> The mute from beadeaux might work while this is getting fixed?

it won't because the mute (despite its name) inflicts removable silence, unfortunately. could get bane from the celery bcnm until other sources are fixed.

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
