### ISSUE TITLE
NM Vouivre drops wrong gil amount + doesnt triple attack (+most likely missing auto-regen)

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4619]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Drops wrong amount of gil (wiki states 28,335~ gil), Also did not triple attack the entire fight. Wikies mention "has high double attack, can triple attack". Seems to be lacking regen aswell (wiki suggests ~50hp/tic)

![image](https://user-images.githubusercontent.com/69089249/138916845-6c25dee0-ba17-4854-a2aa-2211f7af727b.png)

https://ffxiclopedia.fandom.com/wiki/Vouivre

DA rate seemed too low also. Sources arent specific about the DA/TA rate but:

https://www.youtube.com/watch?v=sUH5REKLJ-w retail video about the fight. Counted 100 attack rounds and the DA rate seems to be around 60% while triple attack rate ~20%. Drops 9k gil ea for 2 people in the vid.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
