### ISSUE TITLE
Aquarius D Cloth Drop RMT Change?

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#4623]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

http://www.playonline.com/pcd/update/ff11us/20050715Pm01B1/detail.html
The July 2005 patch notes included this line. " Some of the treasure items earned from notorious monsters in the Boyahda Tree have been changed."
This was referring to D cloth being removed from Aquarius presumably as a RMT change.

https://ffxiclopedia.fandom.com/wiki/Aquarius?direction=next&oldid=22003 
This edit on wiki in September 2005 was specifically to remove D Cloth from the drop pool.

If this was done in the RMT change patch, I don't see it listed in the patch notes.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
