### ISSUE TITLE
Kindred Ranger EES

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4625]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Kindred Rangers in Dynamis - Xarcbard currently have their Eagle Eye Shots go off instantly. EES for these mobs have a ready time similar to Hecatomb Wave (as that's what these mobs use for ranged attacks). Interrupting this may also make them not able to use it again (needs retail verification).

https://www.youtube.com/watch?v=PaTZBS6Kkvs&t=180s - era video, around here it shows this message 
![image](https://user-images.githubusercontent.com/46270382/139489743-266fe350-8647-4cb3-b867-c4c610ca4812.png)
https://i.gyazo.com/2fb5e785500cf0bc2e883aa2e54ffa37.mp4 - another retail clip of this behaviour

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
