### ISSUE TITLE
Mob TP Retained Out of Combat

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4626]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently mobs that leave combat and reset / become idle again will retain any TP they've gained indefinitely. Mobs should gradually lose TP when not in combat. They seem to lose 100 TP (on the 1000 scale) per tic but I'm unsure how long a tic is for this, it may occur every rest tic as it seemed to be a gradual loss on retail.

https://www.youtube.com/watch?v=r9DKAz87j2Y - vid showing some of the TP loss on a tic

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
