### ISSUE TITLE
Spell meteor in bcnm Dawn

### ISSUE THREAD

**Issue by Raulfin** [EdenServer/community#4627]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0
During the Dawn fight Meteor hits for 1000+ with no multi target reduction, it should only do 300-600, and the range is atleast 30y. It's essentually 1-shoting the whole group with shell 5.

XIclopedia links
[Sep 2007 Page](https://ffxiclopedia.fandom.com/wiki/Dawn?type=revision&diff=342302&oldid=337061)
[Videos page](https://ffxiclopedia.fandom.com/wiki/Dawn/Video)
[2006 video](https://youtu.be/zZnLsLgntDk?t=204) Meteor dmg doing 200-400, the whm and blm can be seen in the background not getting hit.
[Eden meteor doing 1000-1300](https://imgur.com/yVb6SEK)

**Comment by 59blargedy** [comment]
resolved in january 10, 2022 update
