### ISSUE TITLE
Angel Lyre doesn't increase time of Goddess Hymnus

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#4628]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

When I cast Hymnus with an Angel Lyre, the song timer is 2 minutes when it should be 140 seconds. 

https://ffxiclopedia.fandom.com/wiki/Goddess%27s_Hymnus

```Equipment that gives "Hymnus +" or "All Songs +" increases the duration of the song by 10 seconds per +1 level.```

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
