### ISSUE TITLE
Under Observation Item loadout incorrect. 

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#4629]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

You are supposed to always get a Mercury and a Hecteyes eye plus 2 other groupings for a minimum of 4 items in a chest.
Currently you only get one of the hecteyes and no mercury.

![image](https://user-images.githubusercontent.com/62901732/140240037-61386717-6732-4720-a888-21b538fb10a6.png)

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
