### ISSUE TITLE
Om'Yovra seem to be missing their paralysis additional effect on attack

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4630]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I've never seen an Om'yovra inflict paralyze on hit on Eden but I normally am /NIN and sleep nuking so I don't usually get hit. In talking to others it seems like they don't have it though.

https://ffxiclopedia.fandom.com/wiki/Om%27yovra

"Melee attacks have the additional effect of Paralysis."

https://ffxiclopedia.fandom.com/wiki/Category:Yovra

The family page lists it too 

![image](https://user-images.githubusercontent.com/13668758/140420814-3af6611b-4959-4c97-9353-f5db5cdb22bf.png)

**Comment by Mozzy4Ever** [comment]
https://youtu.be/I8FU4knitPU?t=25 shows an Om'Yovra hitting a PLD and causing paralysis:
![image](https://user-images.githubusercontent.com/11255886/140420564-cb3a6a08-bca9-4e4e-b7b7-4ba33707ca62.png)
(Hard to tell from SS but can see on status bar he got paralyzed and shortly thereafter gets a para proc)

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
