### ISSUE TITLE
Yovra family missing Regen

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4631]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
30181205_0

Currently on Eden, Yovras have no regen whether over land or water. Wiki states "Possesses a very potent Auto Regen trait, which increases while above water." (https://ffxiclopedia.fandom.com/wiki/Om%27yovra)

https://youtu.be/I8FU4knitPU?t=190 shows an Om'yovra going from 43 to 44% HP in the span of 6 seconds with no DoT on it.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
