### ISSUE TITLE
Dynamis Xarcabard 3 NM pets should be sleepable

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#4633]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [N/A] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

In this video, you can see a player named Greypoupon landing a sleep 2 on Andras's Vouivre around the 41-42 second mark.
https://www.youtube.com/watch?v=HaJq2y6V6fI&t=41s.

In the same video, you can see a blm casting a sleepga right as summon wyvern is used by King Zagan. The sleepga animation goes off on the wyvern, but there is no chat message. However, the wyvern isn't moving so it seems pretty clear it is asleep. (2:30ish)

In this video, you can see a horde lullaby having the no affect message on Nebiros's Avatar and the avatar not moving around after that. As far as I know you only get that message if the enemy is already asleep. 
https://www.youtube.com/watch?v=lLbNh-0p0_E  (Timestamp is about 7:33-7:34)

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
