### ISSUE TITLE
No title given for Wyrmking Descends

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4634]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Neither tank party nor party of the killer got title.
https://ffxiclopedia.fandom.com/wiki/The_Wyrmking_Descends?diff=374533&oldid=prev
Should be "Wyrm Astonisher"

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
