### ISSUE TITLE
Bv2 Impulsion is absorbed by shadows

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4637]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
30181205_0

Sadly I can't find much data on this TP move. FFXIClopedia says it's a magical AoE that wipes shadows. JPWiki says the same. Currently on Eden you can prevent any of the additional effects by keeping shadows up. 

None of these sources say it's absorbed by shadows:
https://rukenshin.livejournal.com/13893.html#cutid4
http://wiki.ffo.jp/html/3112.html
https://ffxiclopedia.fandom.com/wiki/The_Wyrmking_Descends

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
