### ISSUE TITLE
NM Ellyllon in Boyahda Tree dropped & mugged gil is too low

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#4638]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

30181205_0

The gil and mug rewards from the NM "Ellyllon" in Boyahda Tree are too low.

Reproducible steps:
1) Kill Ellyllon
2) See how much gil it drops

From killing it on Eden:
![image](https://user-images.githubusercontent.com/65121606/140746494-329315fc-37c2-4334-aa05-4d2095929a9a.png)
![image](https://user-images.githubusercontent.com/65121606/140746580-9fe1defc-5bbe-4c16-9a0d-b97e2e070051.png)

Multiple sources from in era claim a 6k gil drop without gilfinder trait maxing out at about 10k with gilfinder, somewhere about half that from a successful mugging.

Links to era sources:

https://ffxi.allakhazam.com/db/bestiary.html?fmob=1624

**Use Ctrl + F for gil to find these in the comment section:**

August 2004: Claim of 6k gil drop each time from 5 kills
October 2004: Claim of 6k gil drop
February 2005: Claim of 6k gil drop
April 2005: Claim of 6k gil drop
June 2005: Claim of 3k gil drop each to two characters 
December 2007: Claim of 6k gil drop

As there was no updates to this mob that I could ever find, this is when the changes were added to ffxiclopedia to include how much drop it could drop or be mugged for:

May 2008: Claim of 6k gil drop
https://ffxiclopedia.fandom.com/wiki/Ellyllon?type=revision&diff=814595&oldid=528102

September 2008: Claim of 3,516 gil from Mugging with Assassin's Bonnet. Claim of dropping 6,000 gil up to 9,679 with gilfinder.
https://ffxiclopedia.fandom.com/wiki/Ellyllon?type=revision&diff=814595&oldid=670478

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
