### ISSUE TITLE
Recycle effect rate on "Scout's Beret" (RNG AF2 head) is too low

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#4639]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

30181205_0

![image](https://user-images.githubusercontent.com/65121606/140751386-be3fd99f-510a-4f43-b0eb-717a9cd961d7.png)

From testing this item on Eden, it would appear the recycle effect activates (does not consume ammo) 5% of the time. Multiple sources have it listed as activating at 25%.

Reproducible steps:
1) Equip Scout's Beret
2) Equip ammunition and a ranged weapon for it, taking into account how much you had
3) Use a ranged attack that consumes ammo
4) Observe activation rate of Recycle (I used multiple parsers to confirm and used 5 stacks of arrows with only basic ranged attacks, but anyone working on this can just look into the source code)

Sources from era:

2005:
Listing has it at 25% recycle rate,
**Use Ctrl + F for both "recycle" and "%" you will find claims in the comment section from 2005 onwards saying 10~30% recycle rate (some saying 1/10 1/5 or 1/4).**
https://ffxi.allakhazam.com/db/item.html?fitem=5091

As I could not find any patch notes saying this item was changed, it would be safe to assume the following are era accurate.

Jan 2008: Claim of "roughly 33%" recycle rate 
https://www.ffxiah.com/item/15082/scouts-beret

Feb 2008: Claim of "conserves approximately 25% of ammunition used" added to the listing, this **has later been updated to simple 25% exactly on the current listing.**
https://www.bg-wiki.com/index.php?title=Scout%27s_Beret&type=revision&diff=560045&oldid=61318

Sept 2008: Change to FFXIclopedia listing, claiming "20~30%" recycle rate which it still has currently.
https://ffxiclopedia.fandom.com/wiki/Scout%27s_Beret?type=revision&diff=1662986&oldid=664667

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
