### ISSUE TITLE
San d'Oria Mission 5.1 The Ruins of Fei'Yin. Halver Bugged?

### ISSUE THREAD

**Issue by Allorddemon** [EdenServer/community#4640]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
version 30181205_0

Trying to complete 5.1 San d'Oria Mission, defeated Archlich Taber'quoan and received Burnt Seal, but Halver just refuse to complete the mission saying phrase on the screenshot over and over again.
Still can't complete this mission or take another one.

![2021 11 09_231058](https://user-images.githubusercontent.com/93088403/141007078-ae9b5926-9251-447c-960b-e1f879becd55.png)

![2021 11 09_23315511](https://user-images.githubusercontent.com/93088403/141008495-9ef0aab0-fdfb-4ef1-be0a-9ceeb69a0cc1.png)

**Comment by 59blargedy** [comment]
have you filed a gm ticket? they will be able to resolve this issue for you.

**Comment by Allorddemon** [comment]
Just did, they helped. 
Seems like bug was caused because "A Timely Visit" quest was opened at the same time.
Once I completed that quest, I was able to complete this 5.1 mission.
Many thanks!
