### ISSUE TITLE
Test your Mite damage/tp drain adding together

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4641]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
30181205_0

The TP drain AE from Pasuk is combining with the damage done and dealing that total damage, while also draining the TP
![image](https://user-images.githubusercontent.com/11255886/141175659-38e6f624-6903-4a90-a421-813b430fc213.png)

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
