### ISSUE TITLE
Can exit MMJSP w/ assault orders

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4642]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
30181205_0

https://ffxiclopedia.fandom.com/wiki/Staging_Point?oldid=185945
![image](https://user-images.githubusercontent.com/11255886/141228591-62a082ce-6d34-4430-a4f9-0640bf1d78bc.png)

On Eden if you have both a runic portal use permit and MMSJP assault orders, you can still exit.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
