### ISSUE TITLE
Dynamis Bastok TE statue spawn point

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#4646]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
http://www.dynamisbums.com/strategy/bas.html

So when we cleared the Zeruhn mines area (13, etc on this map), we didn't get any TEs. We went to go kill the stuff at Bastok Markets zone line, we noticed a statue had seemingly randomly repopped where 158 is on the dynamis bums map. When we pulled that statue, it had the 10 minute TE Vindicator and the 10 minute TE constable. It should be spawning over by Zeruhn mines but it spawned close to the stairs down by ore street (where 158 is on the map). To note, the statue that had the 2 10 minute TE quadavs did NOT give the 10 minute TE that I believe it is supposed to, but that is probably a separate bug. Mozzy confirmed the spawn location was also in the same spot on test.

**Comment by 59blargedy** [comment]
resolved by another dev in November 29, 2021 update
