### ISSUE TITLE
Alumine / Luisant Haubert Level

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#4647]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
There was discussion today about what the correct level for Alumine / Luisant Haubert crafts are. 
https://ffxiclopedia.fandom.com/wiki/Luisant_Haubert lists the requirements as Smithing 64, GSM 28, and Clothcraft 25.
BG wiki and ffxiah have no listed subcrafts but also have 64 for the smithing requirement. DSP seems to have the levels listed as 64, 51, and 1, but that's not right. I know there was a bug report that was doing already about this item, but I wanted to check to make sure it is correct.

I actually took the time to level smithing on retail to test this synth. I have provided 2 captures showing that at 37/0/0 I could not synth the item, but at 37/1/0 I could in fact synth the item. This shows 100% that the requirements are 64 smithing or below, 28 goldsmithing, and 27 clothcraft or below. (If people don't know you can attempt a synth on retail if you are 27 levels below or closer).

This data leads me to believe the ffxiclopedia information and I believe the synth should be changed to 64 / 28 / 25 to match ffxiclopedia if that isn't already what it is listed at for Eden.

https://www.youtube.com/watch?v=nYq9MB1uc2g

https://www.youtube.com/watch?v=wJu4nNTVq90

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
