### ISSUE TITLE
Zanshin not procing

### ISSUE THREAD

**Issue by Herralaze** [EdenServer/community#4648]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Ver: 30181205-5

Hello guys ^^
Been trying NIN59/SAM29 on Lesser Colibris and after 1+ hour, I got absolutely zero Zanshin, I then decided to investigate further : 

- When **single** wielding Katana, Zanshin does proc !
- When dual wielding Katana : No Zanshin !
- When Hand to Handing : No Zanshin !

Been looking on several wikis, and I've not seen anywhere it should be this way , so ... bug ?
[https://ffxiclopedia.fandom.com/wiki/Zanshin?oldid=449178](url)

**Comment by falzum** [comment]
This is correct behavior. Zanshin will not proc while dual wielding or using h2h. Single handed only.

**Comment by Herralaze** [comment]
K, thanks for the help Falzum, 
did a lil bit of research and found this forum from 2008 [https://www.bluegartr.com/threads/61850-Hachiryu-Zanshin-test/page2](url)
Confirmed  Zanshin don't work with Dual wielding and H2H.
Closing.
