### ISSUE TITLE
Mobs Charmed/Effected by Failed Charm - Do Not Move After BST Dies

### ISSUE THREAD

**Issue by Mu-cky** [EdenServer/community#4649]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Searched for this issue, spoke with Mozzy#0001 on Discord about it. They requested that I submit this ticket.

Steps
Charm a mob OR attempt to charm a mob and fail
Die
Observe the mob does not move
Have RR up OR receive a raise from another player
Accept Raise
Observe mob finding you and killing you
Raise again
As long as you do not re-aggro, hate will be cleared and you can proceed as normal

Version 30181205_0

Character: Mucky

Zone: Sea Serpent Grotto
Time: 12:09-12:11 PM PST
Pet: Royal Leech
Royal Leech Killed by another: 12:33 PM PST - had not moved

Images
![Mucky_2021 11 17_115635](https://user-images.githubusercontent.com/94568270/142278288-bb6302f1-32f5-492a-92d2-7a83d00aae8d.png)
![Mucky_2021 11 17_123225](https://user-images.githubusercontent.com/94568270/142278331-de356411-e505-4567-a6c7-394445ec1fcb.png)
![Mucky_2021 11 17_123341](https://user-images.githubusercontent.com/94568270/142278344-3a2e2190-00f6-49df-9f32-384fa6a3b27d.png)

**Comment by Mu-cky** [comment]
Again. Occurred at 11:58 AM PST.

After death, uncharmed pet remains frozen in place. Does not disappear or move within spawn area.
![Mucky_2021 11 23_115858](https://user-images.githubusercontent.com/94568270/143095482-dec00305-ae8f-43bf-b74a-864b7f85ae29.png)

**Comment by Mu-cky** [comment]
Occurred again. 18:00:00 PST 11.26.2021 Eastern Altepa Desert
After death, pet remains frozen in place. Does not disappear or move within spawn area
![Mucky_2021 11 26_180023](https://user-images.githubusercontent.com/94568270/143664748-0dbebd77-3ac8-4d6a-8689-56b5f081b1d4.png)
.
![Mucky_2021 11 26_180458](https://user-images.githubusercontent.com/94568270/143664766-47331706-112d-41e9-9e36-84a4f0163750.png)

**Comment by Mu-cky** [comment]
Another character observing the same event
![Jinrei_2021 11 26_181629](https://user-images.githubusercontent.com/94568270/143665055-aa23ff75-a0c6-4c7d-b3b9-a1e1fdb1dbdf.png)
.

**Comment by Mu-cky** [comment]
Happed again. 15:39 PST 11.27.2021
Eastern Altepa Desert
Desert Dhalmel - Pet
Character - Mucky - BST 43

Is a fix required? This seems bugged, but haven't heard back on this.

Again, uncharmed pet does not move within spawn zone, does not recover HP.
![Mucky_2021 11 27_154026](https://user-images.githubusercontent.com/94568270/143723618-d0976e8d-559e-404d-829e-cb5564e0c6f6.png)
![Mucky_2021 11 27_154239](https://user-images.githubusercontent.com/94568270/143723619-aad5f81f-0b51-423e-bb3a-8bfe2ebb4aae.png)

**Comment by Mozzy4Ever** [comment]
You don't need to post every time it happens. A fix is required as it's a bug, yes. Eventually it will be done.

**Comment by mlandrum22** [comment]
I like seeing every time a bst dies

**Comment by Mu-cky** [comment]
Ah, ok. I don't mind being the source of enjoyment, just want to help it get fixed if possible. ^^

**Comment by Mu-cky** [comment]
This is still the case. Mob frozen in place. Makes the use of RR impossible.

21:10 PST 12.26.2021
Labyrinth of Onzozo
Labyrinth Leech - Pet
![Mucky_2021 12 26_213015](https://user-images.githubusercontent.com/94568270/147437803-d9c815e9-f809-48c5-a954-29deaa6a86d6.png)

**Comment by Mozzy4Ever** [comment]
Pretty sure it hasn't been fixed yet, otherwise this ticket would've been closed.

**Comment by Wistdogcheese** [comment]
Happened to me again today. Died with bunny pet charmed. Pet remained stationary. Got raise. Accepted raise. Previously charmed mob (none aggroing) killed character.

**Comment by Mu-cky** [comment]
![Mucky_2022 01 27_220540](https://user-images.githubusercontent.com/94568270/151496027-9c540949-809a-4c88-9b5b-e7d61839642e.png)

Still the case for me as well. As you can see, uncharmed pet, Olid Funguar in Crawler's Nest is frozen in place, requiring the bst to HP or raise, then die, then raise again to clear hate.

**Comment by Mozzy4Ever** [comment]
> Pretty sure it hasn't been fixed yet, otherwise this ticket would've been closed.

**Comment by Mu-cky** [comment]
![Mucky_2022 02 04_200418](https://user-images.githubusercontent.com/94568270/152628171-0916c41f-7a44-4053-99f6-47c88310c23b.png)

Still an issue. Another zone.

**Beastmasters on Eden cannot effectively use RR.** 

This case was in Toraimarai Canal. Even if the pet is not near their spawn area; Dark Aspic pet was 30+ yalms away from spawn area. When bst died, the pet went uncharmed and remained anchored in place, waiting for RR to be used.

**Comment by Chris-Bardsley** [comment]
This is still happening.

**Comment by KnowOne134** [comment]
Yep. Wasn't closed. To be expected

**Comment by Mu-cky** [comment]
This seemed to be an issue with retained enmity. Up until the last patch. I saw this issue. Even using tractor on the master experiencing this bug, drew hate to the tractorer.

However, since the last patch I conducted a more thorough test after speaking with Aether. Here are my tests and results. I have videos catalogued for each trial, I have included the 5th and 6th trial video here. I can upload and share the other trial videos if needed.

Aether asked me to post some additional details to this issue.

Today 2/24/2023
Zone: Bibiki Bay
Position: (F-6)
master Level: 75BST/37WHM
Mob: Tropical Rarab
Is Mob Aggressive Normally? No
Mob Level: 76

Note: None of the characters were in the same party for testing

Normal bug: A charmed mob that turns and kills its master maintains Cumulative Enmity (CE) on the master, even after the master dies. If charm failed, this CE behaves in the same way—remaining on the master after death. CE can be transferred to others if they use tractor on the dead master.

Defining terms used:
Master = The level 75BST/37WHM conducting the study
Tropical Rarab = Level 76 Tropical Rarab at (F-6) Bibiki Bay on Eden Private Server
Within normal spawn area = a place where if the mob was Leave’d, it would wander back and regen HP (tested to ensure) – in this case ~1-2 yalms from spawn point
Outside normal spawn area = a place where if the mob was Leave’d, it would disappear (tested to ensure) - in this case ~50 yalms from spawn point

Trial 1: Attempting to replicate normal bug within spawn area
/ma Reraise <me> 
/charm Tropical Rarab
Charm Success
Wait for Charm to Wear off
Death of master
Mob is mobile
Accept reraise
Tropical Rarab does not attack

Trial 2: Attempting to replicate normal bug within spawn area, when a charm fails
/ma Reraise <me>
/charm Tropical Rarab
Fail to Charm
Death of master
Tropical Rarab is mobile
Accept reraise
Tropical Rarab does not attack

Trial 3: Attempting to replicate normal bug outside of spawn area
/ma Reraise <me>
/charm Tropical Rarab
Walk 50 yalms away to a place on the map where if the mob was Leave’d, it would normally despawn
Wait for Charm to Wear off
Death of master
Mob is frozen, despawns
Accept reraise

Trial 4: Attempting to replicate normal bug within spawn area after fighting with Tropical Rarab
/ma Reraise <me> 
/charm Tropical Rarab
Charm Success
/ja Fight Tragopan (Level 72)
Tragopan dies
Tropical Rarab is at 50% health
Wait for Charm to Wear off
Death of master
Mob is mobile
Accept reraise
Tropical Rarab does not attack

Observation: When this bug typically happens, the master has low HP from a battle, and the pet only hits you a few times or lands the killing blow. A normal situation for BSTs as we level using charm or solo difficult mobs with charm.
Question: Maybe cumulative enmity is being lost if the master has higher HP during this bug. 
Illustration: In Trial 4, damage taken to master was 1239. The CE generated by charm is 320. Given the formula CE Loss = 1800 x Damage Taken/Maximum HP, CE Loss for 1239 with max HP of 1000 is 1800 x 1000/1000
Therefore, CE Loss = 1800
1800 > 800
We know that CE from charm is 320
Therefore, for a character with 1000 hp, a single charm would only allow the pet to do less than 177 damage before CE loss would take care of the enmity loss.

Hypothesis: A master with 1000 hp who charms a pet, waits for it to turn, takes less than 177 damage, will have enough CE for this bug to work.

Trial 5: Attempting to replicate normal bug within span area, after lowering HP to <177
/ma Reraise <me>
/charm Tropical Rarab
Charm Success
Wait for Charm to Wear off
Death of master
Mob is mobile
Accept reraise
Tropical Rarab does not attack

[Here is the video from the 5th trial](https://drive.google.com/file/d/1a6myfvX16k3iNTTl2LwPjozT02IHKd-r/view?usp=sharing)

Observation, in Trial 5, the master's hp was 127, but the Tropical Rarab hit the master for 290 points of damage with Foot Kick. An additional trial may be used to generate more CE and test again.

Trial 6: Attempting to replicate normal bug within spawn area, with three consecutive charms + one unsuccessful charm
/item “Reraise Earring” <me>
/charm Tropical Rarab
Charm Success 1
Wait for Charm to wear off
/charm Tropical Rarab
Charm Success 2
Wait for Charm to wear off
/charm Tropical Rarab
Charm Success 3
Wait for Charm to wear off
/charm Tropical Rarab
Charm failure
Master takes 280 points of damage, which is a CE Loss of 500
CE should have been 1280 from charms and misscharm

[Here is the video from the 6th trial](https://drive.google.com/file/d/1qz-VJjgwhJQKQ-9519ZPWlw1f2uUtmW-/view?usp=share_link)

Increased enmity generation with multiple charms and a failed charm does not appear to effect the result.

More testing in other zones with other mobs could be conducted, but this bug does not appear to be an issue since the last patch.

**Comment by Mu-cky** [comment]
Upon asking other BSTs if they are still experiencing this issue, one was able to recreate it in Sky. Here is Pants' screenshot from today.
![Pants_2023 02 25_165924 Record of it happening to Pants today in Sky](https://user-images.githubusercontent.com/94568270/221387794-6918ffa7-e701-4034-a6bc-0fa0dd166dbf.png)

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
