### ISSUE TITLE
Unlimited Shot and Ranged Attack Misses

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#4650]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver. 30181205_0

Unlimited Shot consumes ammo on missed /ra and does not remove the buff. Missed WSs will remove the buff and not consume ammo. Can reproduce consistently.

https://cdn.discordapp.com/attachments/755939449040404552/910653740552454175/Pants_2021.11.17_141129.png

https://cdn.discordapp.com/attachments/755939449040404552/910653783523090503/Pants_2021.11.17_141146.png

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
