### ISSUE TITLE
Leafstorm from Jidra Boss in SW Apollyon should remove food

### ISSUE THREAD

**Issue by faivruit** [EdenServer/community#4651]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
https://www.bg-wiki.com/index.php?title=South_West_Apollyon&oldid=38870
The leafless Jidra has enhanced TP abilities much like Cemetary Cherry: Leafstorm is a full dispel (including Food and Job Abilities) and Slow;

Food is currently not removed by this. Not sure if it should remove reraise (it does not currently), but wiki sounds like it ("full dispel").

How to reproduce: Go to SW Apollyon second floor, eat food, let the boss use Leafstorm, check buffs.

version 30181205_0
![grafik](https://user-images.githubusercontent.com/77455848/142298206-db9d239b-069f-46e8-9c1f-2b8713d438a7.png)

**Comment by faivruit** [comment]
Update: Reraise not being dispelled seems to be OOE as it should fall under the Dec 9, 2008 update:

http://www.playonline.com/pcd/verup/ff11us/detail/3893/detail.html
The Reraise effect granted by certain spells and items will no longer be removed by magic and abilities such as Dispel and Voidsong.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
