### ISSUE TITLE
Sunlight Pole Regen not triggering on Sunny weather, Tested using Ashitacast weather rules

### ISSUE THREAD

**Issue by RistarPryde** [EdenServer/community#4653]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
