### ISSUE TITLE
Flashbulb having no effect = Client crash

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4655]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver = 30181205_0

An automaton using Flashbulb on the main Pulling the Strings Memory Receptacle while it is under magic immunity will cause a client crash for all parties nearby. Cause also happen if Flashbulb is used in other "No effect" situations like on a magic pot after it's used Spectral Barrier

Also causes this error in the loader:

![image](https://user-images.githubusercontent.com/11255886/142743676-3a1905de-158c-4e12-ac3f-2b6ae1841b5c.png)

**Comment by E5una** [comment]
It must have something to do with immunity, because I regularly get no effect messages in exp pts when a PLD is there to flash

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
