### ISSUE TITLE
Chaotic Strike stun duration most likely way too short

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4656]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On eden, tested around 30 Chaotic strikes on EP Devil Mantas, stun seemed to be set to around 0-1s/hit + stun checks landed. 

2007 Wiki edit suggests this to be 0-5s/hit +checks landed:
![image](https://user-images.githubusercontent.com/69089249/142748709-ad0f1a4f-0084-46f0-8fac-c4056d78c741.png)
https://ffxiclopedia.fandom.com/wiki/Chaotic_Strike

BG wiki as other sources also mention it being a long stun, but dont go into specifics.
https://www.bg-wiki.com/ffxi/Chaotic_Strike

Might need retail testing.

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
