### ISSUE TITLE
Guivre's Skull drop rate is too low

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#4657]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver. 30181205_0

Reproducible steps:
1. Kill Guivre in Kuftal Tunnel
2. Observe drop rate of Guivre's Skull item

**My Data**

I have killed Guivre on Eden for 11 consecutive spawns now, screenshotting the results of the last 8. No skull ever dropped for me with TH4 on every kill.
![image](https://user-images.githubusercontent.com/65121606/142786881-28be9bc9-4e87-4f84-84a0-833b3358d451.png)
![image](https://user-images.githubusercontent.com/65121606/142786942-a3cda460-0ec2-4db5-af39-017b254487b1.png)
![image](https://user-images.githubusercontent.com/65121606/142786888-064cfd20-c52f-4478-bc69-a7097d5cddd3.png)
![image](https://user-images.githubusercontent.com/65121606/142786903-46435821-5488-49fa-9d4a-b46d4d3187cc.png)
![image](https://user-images.githubusercontent.com/65121606/142786954-2b80dc15-60a4-41dd-98e7-a050ab525ea7.png)
![image](https://user-images.githubusercontent.com/65121606/142786963-febf319f-7008-45c5-ba55-3a41e821669a.png)
![image](https://user-images.githubusercontent.com/65121606/142786965-ad58ed1c-4523-4602-bd13-60c9f2ba7659.png)
![image](https://user-images.githubusercontent.com/65121606/142786975-3c50d24b-3480-4f63-bcb2-43c6c05d785c.png)

Only taking into account my 8 documented kills and throwing out the other 3 I am claiming, if the skull was a "very common" (64% drop rate with TH4), the chance of it not occurring over 8 kills would be  0.028%. 
![image](https://user-images.githubusercontent.com/65121606/142787688-38b549f9-22f2-4e3a-b5ba-8d16f3dbbaff.png)
Similarly if it was classed as "common" (45% drop rate with TH4), the odds of not getting a skull after 8 kills is 0.837%.
![image](https://user-images.githubusercontent.com/65121606/142787936-bf775ed2-0c67-43fc-ae6a-86a6089615df.png)

**Available Sources**
According to the only sources available I could find, the drop should be much higher. FFXIclopedia has 7 kills documented (added around 2008) with 4 drops of the skull. FFXIdb has 285 kills recorded with 122 skulls dropping.
![image](https://user-images.githubusercontent.com/65121606/142788401-81a80e7d-cddd-4452-b4da-7f6b76d5ae4a.png)
https://ffxiclopedia.fandom.com/wiki/Guivre
![image](https://user-images.githubusercontent.com/65121606/142787154-7303cab5-9ae5-414f-95dd-82cb04682b4d.png)
http://www.ffxidb.com/zones/174/guivre

With how treasure hunter works and given what evidence I have, I believe the drop rate of the skull has been miscategorized into either "uncommon" (capping at 18% chance with TH4), "rare" (capping at 8% chance with TH4), or "very rare" (capping at 2.5% chance with TH4). 

**While the evidence from sources as close as you can get to era would clearly point to the skull being in the "very common" category (capping at 64% chance with TH4), given the over all drop rate from both sources and the TH0 drop rate given by FFXIdb at 25.9% (very common being 24% with TH0), it aligns perfectly with the given data**.
![image](https://user-images.githubusercontent.com/65121606/142786872-28ecf873-3ec2-450f-ab50-9a643594f572.png)

I am unable to find any contrary evidence showing there was some change to the drop rate of this item over updates, and the TH0 data on FFXIdb throws out much of a question if newer higher levels of TH on era has effected the data.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update (and thanks for the extraordinarily detailed report)
