### ISSUE TITLE
Quest NPC Peddlestox for quest "Beastmen Treasure (Eshimo Uplands)" is not spawning on Lightnings Day.

### ISSUE THREAD

**Issue by Windsong2** [EdenServer/community#4658]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I have completed this quest twice before but the NPC is not spawning on the appropriate day now.  I see the same problem has occured with this quest in other regions based on issues reported in the past.  I tried fixes suggested in those reports:  Walking 50 yalms away and returning did not cause him to spawn.  Re-zoning didn't work either.  As you see in the screenshot, there's now a crawler spawning up on a wall in this section of the zone.

![Windsong_2021 11 21_210036](https://user-images.githubusercontent.com/94816023/142795527-1622326c-c3f3-46d0-9d07-8db5c573639f.png)

**Comment by 59blargedy** [comment]
this should have been resolved in April 18, 2022 patch, but it wasn't an obvious fix so please let us know if it didnt
