### ISSUE TITLE
Hyperion in NE Apollyon Immune to all spells

### ISSUE THREAD

**Issue by Raphtalia1** [EdenServer/community#4660]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Hyperion (NM Gigas in NE Apollyon) is completely immune to all spells nukes, dots, enfeebling

He should be immune to magic DAMAGE but not to dots or enfeebles

https://ffxiclopedia.fandom.com/wiki/Hyperion

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
