### ISSUE TITLE
Adventuring Fellow can be attacked.

### ISSUE THREAD

**Issue by AzrielltheWise** [EdenServer/community#4663]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Adventuring fellows can be drained, aspir'd, and nuked.  Cannot click on them and engage but /attack might work (I forgot to test; will update this tomorrow after I check).

&lt;bt&gt; targets Adventuring fellow.   If you have a monster claimed, &lt;bt&gt; prioritizes the monster, but if you have no claimed monster &lt;bt&gt; targets Adventuring fellow.  If you have weapon drawn and you're engaged with a monster, but you haven't hit the monster and it's still unclaimed, &lt;bt&gt; targets the monster.

ver: 30181205_0

**Comment by KnowOne134** [comment]
Corrected on 11/21 patch
