### ISSUE TITLE
Jug pets that spawn at level 23 or 24 have no Ready moves.

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#4664]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I went in to Palborough Mines rank 2-3 Dragon fight and 2x I pulled out a sheep with no Ready moves. I was also not able to use macros to use Ready moves.

Sheep Familiar had moves right outside BCNM.

CourrierCarrie had her moves while in this BCNM.

Homunculus had no moves.

**Comment by 59blargedy** [comment]
i dont think is related to bcnms directly, see https://github.com/EdenServer/community/issues/4387
any more info is appreciated
