### ISSUE TITLE
Silence should prevent dragons from using  lode-, void-, thorn- and nullsong

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4665]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Silence should prevent dragon type monsters from using Lode-, Void-, Thorn- and Nullsong (if they have them in their moveset list)
![image](https://user-images.githubusercontent.com/69089249/143498982-24f2139c-1141-4232-97f1-90d413a4ef39.png)
![image](https://user-images.githubusercontent.com/69089249/143498998-ff9d19c5-8cf4-4de1-8b4d-3080326e1e00.png)
Same law should apply to all dragons. Only tested shadow dragon and dahakas on eden, but propably an issue with every mob in the family.

![image](https://user-images.githubusercontent.com/69089249/143499926-7cf7d9aa-2f0e-477c-a900-4e2bd9c3134a.png)

Proof:
![image](https://user-images.githubusercontent.com/69089249/143499138-219aeab5-c7f9-4ac5-90dc-1cd74925e46b.png)
https://ffxiclopedia.fandom.com/wiki/Dahak

![image](https://user-images.githubusercontent.com/69089249/143499205-5e1e6d4d-dd04-42cf-b280-9d5cdb5a7ace.png)
https://finalfantasy.fandom.com/wiki/Silence_(status)

https://www.youtube.com/watch?v=bwOQRCOb1B4
Silence attemp  vs ash dragon at 1:05 at, further proof could be said that ash dragon never uses a song after gekkos

![image](https://user-images.githubusercontent.com/69089249/143499791-32c737fa-36ce-4bca-a12a-9a3a7ad9ee4d.png)
einherjar guide against dragons
https://www.ign.com/wikis/final-fantasy-xi/Einherjar_-_Part_2

version 30181205_0

**Comment by 59blargedy** [comment]
i actually tested this on retail and found it to be incorrect, at least on dahaks, shadow dragon, and i believe someone else tested the limbus dragon. the silenced mob continued to use songs that existed in its moveset. I could not find an instance of an update where this behavior would have changed, so as a result of this testing, we removed the job and silence limitation until we could find an instance where it actually did work to suppress the song. 

because of the sheer volume of moves available, I chalked this up to a wiki lies moment, or one where the effect was grossly exaggerated from working on 1-2 dragons. i'll see if i can validate ash dragon in the next few weeks,

**Comment by Steam-arch** [comment]
Pretty bizarre. Yeah can be. I dont see why it would be removed either. Altho the silencing would make sense mechanic wise. For some reason its all over threads and wiki pages.

THE LIES RUN DEEP (?)

**Comment by Steam-arch** [comment]
![image](https://user-images.githubusercontent.com/69089249/151653244-4d2e7b7d-c2bc-4f1b-9dcf-21bd949c7734.png)
Just adding this here, a nyzul guide recommending silencing the nyzul dragons, incase someone ever tests this on retail or something.

**Comment by dowzer** [comment]
I've only been able to make Dahaks use Thornsong while silenced. I haven't seen them use other -song abilities otherwise. Are we positive they can use other -song abilities while silenced?

Ash Dragon is immune to silence. Dynamis Xarcabard dragons are as well but I don't have a screenshot.
https://i.imgur.com/SaoT7Hs.png

**Comment by 59blargedy** [comment]
No, not sure, that's why I left the ticket open and commented.
Could be that thornsong is the only exception to the silence rule, though
it seems odd that only one type of song can be sung through silence.

**Comment by dowzer** [comment]
It's strange that dragons who don't cast spells can be immune to silence as well then?

**Comment by 59blargedy** [comment]
Yeah, I understand the train of thought that the immunity for dragons is
potentially related to avoiding song suppression, but there are a lot of
silence immune mobs with no songs or spells.

We know that thornsong is not suppressed by silence, despite many claims
that it is. That's the one fact we have. Just need some time to validate
other things.

**Comment by Steam-arch** [comment]
Shadow dragon should use both lode- and voidsongs 🌚.Toau dragons only do null & thorn according to the chart.

But yeah silence immunity doesnt really make sense unless it has an actual function.

**Comment by dowzer** [comment]
_I've only been able to make Dahaks use Thornsong while silenced._ 

I watched that video again and silence had worn off when it used Thornsong. I tried again and I couldn't make Dahaks use any -song moves while they're silenced. 

The first one without silence used Null Song right away:
https://www.youtube.com/watch?v=_uSNxL3HVqo

While they're silenced they didn't use Thornsong or Nullsong, about ~20 minutes worth:
https://www.youtube.com/watch?v=Lnrg7A6aVR0

**Comment by dowzer** [comment]
Dahaks in Mount Zhayolm won't use -song moves while they're silenced. I've spent hours, overlapping with other testing to confirm this.

**Comment by dowzer** [comment]
A few more confirmations:

![dragoniansilence](https://user-images.githubusercontent.com/54732693/155253753-53d5b826-3247-4dd4-86e3-03c015e11b1c.png)

![enhanceddragonsilence](https://user-images.githubusercontent.com/54732693/155254073-09affa53-a6f2-4f0a-961d-21def94c1259.png)

![shadowdragonsilence](https://user-images.githubusercontent.com/54732693/155254096-32ab6365-5f7c-4f57-85f7-27716ffeac09.png)

**Comment by dowzer** [comment]
Was Thornsong used by a Dahak in Nyzul Isle? I still haven't seen them use it in Mount Zhayolm.

**Comment by 59blargedy** [comment]
yep, those are the two examples that made us question. honestly i had the
hardest time getting dahaks to use songs in general,but I did have one
using thornsong at one point in zhayolm. unfort it was 1/100 moves and was
during a period where it was not silenced so i can't tell.
i appreciate you reconfirming the silenced use of songs on those two mobs.
why are they special? i do not know...
the compromise is probably to allow silence to restrict the moves
specifically on dahaks.

**Comment by Steam-arch** [comment]
Maybe silencing dahakas is mob unique feature like the spider outside WG getting stunned by crits/job abilities.

I did watch an einherjar video with voice coms, they had the dahaka chamber and one of them asked "do these spam body slams like the other ones when silenced"

Somewhat weird though to add a complete silence immunity to some dragons and on some dragons allow them to be silenced but they still use songs.

**Comment by 59blargedy** [comment]
resolved (for dahaks) in April 18, 2022 patch
