### ISSUE TITLE
Pulling the strings - fantoccini stuck (corsair)

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#4666]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
During this ENM doing the corsair version of the fight I ended up having to kite and run away. Once I moved out of attack range the fantoccini didn't chase me leaving me to potentially rest to full or wait for goblin dice rolls.

**Comment by 59blargedy** [comment]
i can't seem to replicate this, do you have more information about what you were doing?

**Comment by montijin** [comment]
I had this happen again this morning. It just seems to be running away. Maybe when the fantoccini is in a ranged attack animation?  I did it twice actually and the second time the fantoccini got stuck in a wall.
https://streamable.com/efxbea

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
