### ISSUE TITLE
Astral Staff's avatar defence bonus is not implemented

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4669]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
The staff
![image](https://user-images.githubusercontent.com/69089249/143945706-eff5ecf8-3a2d-48b2-897c-b157b22ef0d3.png)
Should apply a defence bonus to summoned avatar.

Internet sources seem to point that the Defence bonus is 1 tier, 10 def.
![image](https://user-images.githubusercontent.com/69089249/143937241-ff40ff2c-2760-49ec-8cb5-3877569ab59d.png)
https://www.bluegartr.com/threads/114636-Monster-Avatar-Pet-damage?p=6033568&viewfull=1#post6033568

![image](https://user-images.githubusercontent.com/69089249/143937377-f3b9e66d-35dd-4399-81d8-9b1b7f9ba5ed.png)
https://www.bg-wiki.com/ffxi/Astral_Staff

![image](https://user-images.githubusercontent.com/69089249/143937767-5dd9a30b-3cea-405e-a290-3d6549cd8c65.png)

On Eden, the staff gives no extra defence, checked via checkparam
![image](https://user-images.githubusercontent.com/69089249/143946114-51b4a7f2-7f0b-4aa8-b800-459f749e7438.png)
![image](https://user-images.githubusercontent.com/69089249/143945386-efbb6900-8803-4b3e-8a27-fea96177cc9a.png)

Version 30181205_0

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
