### ISSUE TITLE
NPC Parvipon (rabbit hides)

### ISSUE THREAD

**Issue by yueamyen** [EdenServer/community#467]
NPC not rewarding 120 gil...now rewarding Freshwater aquarium?

**Comment by Sethious** [comment]
no it rewards the gil but it says that idk why but it does

**Comment by jmcmorris** [comment]
This might be caused by having a more updated FFXI client than what Eden is on which would cause the text to be off.

**Comment by godmode** [comment]
You need to use the Eden installer to connect to the server. Otherwise you will see incorrect texts.
