### ISSUE TITLE
Trick Attack applies damage bonus when used behind a dead player.

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#4671]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
30181205_0
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

![image](https://user-images.githubusercontent.com/62901732/143976908-98302037-8c8b-4afd-843b-5d08ac9fe767.png)

I will try to test further but I've noticed this twice in the last week and decided to actually report it. In the screenshot Pendeharu was killed by a Wyvern mob in KSNM30 and Sukhoruk TA WS'd from behind him after he was killed and it still applied the damage bonus from Assassin.

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
