### ISSUE TITLE
Mazurka should work in dynamis xarcabard 

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4673]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Mazurka should potential work in both glaciers and maybe cities but I only found references to mazurka in dyna xarc to help kite nms

8th post in this thread: https://www.bluegartr.com/threads/39067-Mazurka-Flee-Speed

**Comment by falzum** [comment]
Seems to work in all 'outdoor dynamis' according to an ffah post https://www.ffxiah.com/item/5073/chocobo-mazurka

"Sylph.Penance[Report] Score: 0  
Its a great thing to have just to get you from point A to point B and helps in outside dream dynamis's to reduce the time you spend running from NM to NM since your on a strict time limit. so all in all its a very useful song :D"

**Comment by falzum** [comment]
SE patch notes specially call Dynamis Beacedine, Xarcabard, Buburimu, Qufim, and Valkurm, 'field areas'. When referring to cites they don't say field. 

"Two new Field areas" Addition of dyna xarc and bcd: http://www.playonline.com/comnewsus/200404226037.html
"New Field Areas" Addition of Outdoor CoP dynamis: http://www.playonline.com/pcd/update/ff11us/20051213fMt7e1/detail.html

To see the distinction: "The new area" http://www.playonline.com/pcd/update/ff11us/20060221pJb1z1/detail.html

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
