### ISSUE TITLE
Emperor band is OOE

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#4674]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
The xp band didn't exists in the toau timeline

**Comment by falzum** [comment]
https://ffxiclopedia.fandom.com/wiki/Dedication?oldid=287417

Only Empress, chariot, and anniversary existed

**Comment by Raulfin** [comment]
http://www.playonline.com/pcd/update/ff11us/20080311cPxl31/detail.html
Emperor band added in March 2008 update a few months after WoG release.

**Comment by KnowOne134** [comment]
Is in era now
