### ISSUE TITLE
Goobbue Humus not removed after Windy 9-1

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4676]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Goobbue Humus isn't removed from the player after trading it to the Mandragoras for Windy 9-1. No other use for it so kinda :man_shrugging:  but still :P

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
