### ISSUE TITLE
CoP Dawn final cutscene Louverance and other npc swapped

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4679]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Retail CS: (0:50 - 1:10 for the part in question) https://www.youtube.com/watch?v=gLw9q2zq8No

Eden CS: (4:44-502 and 6:13) https://www.youtube.com/watch?v=ZL-z8DBp37A
6:13 has the non-brigandine npc

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update
