### ISSUE TITLE
Bibiki to Purgonurgo manaclipper starting position in the water 

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4680]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Taking the boat from bibiki to Proganoro puts you in the water for the whole ride. 

![Kerx_2021 12 03_195106](https://user-images.githubusercontent.com/55296729/144690752-f3baf732-4df0-436c-a639-50b9de5d964d.png)

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
