### ISSUE TITLE
ISNM Compliments to the Chef Angler Orobon wrong level + isnt immune to sleep

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4682]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

**Wrong level proof:**
It likely to be under leveled on eden because it hits way way way too soft from what it hits in era. The monster does NOT give exp and wikis do NOT state its level so unfortunately idk what the level is

![image](https://user-images.githubusercontent.com/69089249/144754208-ad47a2fb-a89d-4bed-9ae0-3f68a488a6f1.png)
![image](https://user-images.githubusercontent.com/69089249/144754847-a78b2979-718e-4017-b202-0a49b0f44217.png)
hits on SAM75, no dmg- gear/buffs on aside protect IV

In era videos it hits for 220-330 to a Fully buffed lvl 75 pt
![image](https://user-images.githubusercontent.com/69089249/144754261-456cc913-2b95-4cc6-bb5d-7e765d7fd080.png)
![image](https://user-images.githubusercontent.com/69089249/144755156-c4753b1e-47c8-43c2-86bd-4aede9a451a6.png)
![image](https://user-images.githubusercontent.com/69089249/144754302-37e2dcb4-2ac0-4b10-8779-b233989098c7.png)
![image](https://user-images.githubusercontent.com/69089249/144754329-a743673d-7caa-4028-b260-ca7d1a605377.png)
Lord in the picture is a lvl 70 hume war, mikrik hume (?) nin 75
https://www.youtube.com/watch?v=0b2ZtJu5mek&t=18s

2009 Fully buffed phalanx rdm getting hit: 
![image](https://user-images.githubusercontent.com/69089249/144754549-29e07cbe-23ad-492e-abc4-77c18e920f3f.png)

**It Isnt immune to sleep Proof:**

Wiki sources claim its immune to atleast the dark based Sleep
![image](https://user-images.githubusercontent.com/69089249/144754605-1d260cb3-14fe-4918-a88f-5d049939f634.png)
![image](https://user-images.githubusercontent.com/69089249/144754621-acf98917-f19f-4a16-bef2-094115669380.png)

On eden it it sleepable: 
![image](https://user-images.githubusercontent.com/69089249/144754652-b981d8c9-ce47-4e9b-8015-647826736890.png)

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
