### ISSUE TITLE
Xzomit TP move "Siphon Discharge" is an AOE currently instead of cone attack

### ISSUE THREAD

**Issue by Deirdre5017** [EdenServer/community#4683]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

When Xzomit's use the TP move "Siphon Discharge," it is currently acting as a 14.9' AOE around the mob rather than a frontal cone attack. 

[BG-Wiki](https://www.bg-wiki.com/ffxi/Category:Xzomit):
Siphon Discharge   | Frontal  | Deals  damage + Knockback.

[Somepage Jailer of Justice write up](http://ffxi.somepage.com/mobdb/3344): 
"Special Attacks -- mainly more powerful versions of standard Xzomit attacks" "Siphon Discharge (100-200HP frontal cone damage)"

[Siphon Discharge page on FFXIcyclopedia](https://ffxiclopedia.fandom.com/wiki/Siphon_Discharge)
"Deals Water damage to targets in a fan-shaped area. Additional effect: Knockback"

Note: The [main Xzomit page on FFXIcyclopedia from August 2007](https://ffxiclopedia.fandom.com/wiki/Category:Xzomit?oldid=329850) does have it listed as a "Siphon Discharge - AoE cone water damage and knockback" but then clicking the link to the ability links to the page listed above that specifies its "damage to a fan-shaped area."

Below is a screen shot of the TP move going off hitting my RDM at 14.9' behind the mob facing another direction.

![Xzomit AOE](https://user-images.githubusercontent.com/73006091/144755540-34abfbf3-58d2-44a1-a0ce-9127cb6f1eaa.jpg)

As well as a shot of the chat log showing we both took damage from it. 

![Siphon Discharge chat log](https://user-images.githubusercontent.com/73006091/144755539-5ba076b2-656f-4aa6-b749-d42514d73a29.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
