### ISSUE TITLE
Ash Dragon should be immune to sleep

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4685]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
On eden sleeps land easily even tho it should be completely immune to sleep & lullaby:
![image](https://user-images.githubusercontent.com/69089249/144842908-112fd6ba-1310-4133-ad5d-7cffb59dbc83.png)

Unfortunately not too many marks on the series of tubes about this, aside:
![image](https://user-images.githubusercontent.com/69089249/144843269-1896fd6c-27cd-45d5-96d8-5bebb947f99c.png)
https://ffxi.allakhazam.com/db/bestiary.html?fmob=569

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
