### ISSUE TITLE
ISNM Compliments to the chef NM missing a trait that enables "TP move spam"

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4686]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Sorry in advance for the vague bug report. Angler Orobon needs something that enhances its tp gain. Currently on eden it has normal tp patterns and uses tp moves in a normal way above +25% (aka rarely compared to retail videos).

On retail it has 2 "unique" tp behaviours, 
1: It uses tp moves very often
2: Some independent pattern where it spams hypnic lamp but doesnt use deathgnash every time (but this bug report focuses on the first one because its easier to "adjust" without knowing the exact mechanic)

![image](https://user-images.githubusercontent.com/69089249/144904130-659fa86c-6838-4c71-8d70-096e7fc19e0e.png)

For example in this rdm solo video it uses first tp move after 6 damaging spells which would normally give it 600 tp. But doesnt use a 2nd tp move after further 6 damaging spells. So its propably not just set to the below 25% mode for the entity of the hp bar where it would use a tp move instantly after hitting 1k tp. Something like a hidden STP+70 would bring it to 1020 tp which would be in the typical rng tp move range thats above +25%.
(https://www.youtube.com/watch?v=zJTbZydBfhs)

BLM burn where he also uses alot of tp moves: https://www.youtube.com/watch?v=2Jh-Vhz-tYg&t=71s

Melee comp where he "spams" tp moves https://www.youtube.com/watch?v=0b2ZtJu5mek&t=14s

He does not have regain though because it would be easy to notice in the solo video.

Not totally sure what "trait" would bring it close to retail accuracy, +70-100 STP could be an option. Figured id try to get the ISNMs closer to retail accuracy with them being a major source of khroma ores.

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update

**Comment by Steam-arch** [comment]
@59blargedy before/instead doing a new bug report, did this isnm two times after patch now and both times Angler Orobon used almost nothing else but Abominable Belch. 1x Seismic tail and + 25x abominable belch, no other tp moves were used from a tp move pool of 4/5. Seems weird to me atleast even if correct behaviour.

To be maybe noted, both of the times the lights on his whips cut off almost straight away.

**Comment by 59blargedy** [comment]
I see where it can still occasionally use tp moves even while enfeebled, so
will make a slight adjustment for next patch.

**Comment by Steam-arch** [comment]
Ah didnt know it has a trait like that.  Was Slowed + parad + dotted.
