### ISSUE TITLE
Monk with 0 h2h skill are only attacking once after patch

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#4687]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Multiple new players have reported on the discord that when they are a monk with 0 hand to hand skill they are only attacking once. They start attacking twice once they get lvl 1 h2h skill. Just checking to see if this is expected or just a minor bug with the new change.

**Comment by dowzer** [comment]
On retail they currently attack twice with 0 hand to hand skill:

https://i.imgur.com/wHjRLlj.mp4

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
