### ISSUE TITLE
Dread spikes effect not being reduced by Shell

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#4691]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The September 2007 revision of wiki says, "Enemies with percent magic reduction will be drained for less than normal." 

This still appears on retail today, as long as a monster has a form of MDT or Shell, it will reduce every hit for that value.

Shell IV on these Light Elementals:

https://i.imgur.com/HSUREuj.png

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
