### ISSUE TITLE
Merrow 5 hits too soft

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4695]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Merrow No. 5s level seems to be wrong? Hits soft compared to retail vids and one Decent Challenge Leech can basically solo it.  Wiki level is set to 82-85.
![image](https://user-images.githubusercontent.com/69089249/145392359-9af47d2d-2981-4472-8edf-389a0aef8a61.png)
Attacks around 80-130 on ashakkus. RDM -50 pdt was taking around 50/hit

2009 bst vs merrow video using same leeches
![image](https://user-images.githubusercontent.com/69089249/145392464-ad675dbb-451e-4331-af04-fb7a79b477a0.png)
![image](https://user-images.githubusercontent.com/69089249/145392508-41713cbe-e404-4109-b29e-7b68622c91ab.png)
![image](https://user-images.githubusercontent.com/69089249/145392535-9d625470-d06b-4c1f-8eff-105d84d65083.png)
![image](https://user-images.githubusercontent.com/69089249/145392562-57f8cbc2-e249-4f83-a8a5-7981371c6d98.png)
![image](https://user-images.githubusercontent.com/69089249/145392618-8567644b-f7e2-4f9a-a798-b3c6898a085e.png)
![image](https://user-images.githubusercontent.com/69089249/145393513-dc0df9be-eee8-4516-a3bc-e297f5a15d8b.png)

https://www.youtube.com/watch?v=mQZ6Dhi7rsc
Attacks around 180-240

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
