### ISSUE TITLE
Tomb bats in KRT have wrong respawn timer

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4696]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Tomb bats in KRT (G-8) that are placeholders for Crypt Ghost should have 8 minute respawn timer, but currently have 11 minute timer.

Modern Wiki
https://ffxiclopedia.fandom.com/wiki/Tomb_Bat

Era Wiki
https://ffxiclopedia.fandom.com/wiki/Tomb_Bat?oldid=242072

First note of the 8 min respawn timer is 2007
https://ffxiclopedia.fandom.com/wiki/Tomb_Bat?oldid=194758

BGwiki lists no information

This alla post says he pops about 5 min after the PH dies when he is going to spawn. Two separate people note the 5 min timer.
https://ffxi.allakhazam.com/db/bestiary.html?fmob=152

"i started out camping spook for my evil plan to camp for 2 days and have my friend come to take them and put them on AH so far im 2/11 and the price would raise since we selling for 40k instead of 30 and we only ones who are gettin em ;) and then i decided between 4-20 what if i camped crypt ghost and did the same thing and since he is around an hour repop this works perfect but for the first 3 huors i didn't know the bats where his PH xD so i went back to this forum read the post killed the bats waited 5 min pop killed him got slakcs 1/1 hopefully soon to be more =D and hopefully mu evil plan or price raising because of demand will work"

"I decided to camp this guy while farming bat wings in the tomb and this is some basic info. This guy pop roughly every hour and the 3 tomb bats in the room in G-8 act as the Place Holders for this guy. You only need to kill one of the bats and watch out they do Link and Aggro'd me often when healing after the fight (like the Skeletons outside aswell)But after you have killed a Bat he pops roughly after 5 mins. Anyway i am 1/4 for this guy on Slacks. Defiantly less camped than Spook as people tend not to bother with him."

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
