### ISSUE TITLE
Curaga 2 has wrong recast

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#4697]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
The recast in game is 10 seconds even and should be set to 10.25

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
