### ISSUE TITLE
Diremite Spinning Top

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4698]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently Spinning Top when used by Diremite mobs / jug pets is multi-hit as this ability can hit pretty hard if multiple hits land. This TP move should only be one hit (but AoE) from what I've seen on retail / resources online. 

https://i.gyazo.com/5ab5f49480735c1bc1ac110c77287724.mp4 - shows it being evaded
https://ffxiclopedia.fandom.com/wiki/Spinning_Top

version 30181205_0

**Comment by Spintimalli** [comment]
is the 2-4 shadows absorbed not indicative or a multi-hit though?

**Comment by FariskaEden** [comment]
From my understanding AoEs can take multiple shadows and I think the amount of shadows lost is based on your ninjutsu skill versus mob level (when using utsusemi).

**Comment by 59blargedy** [comment]
resolved with recent tp move changes
