### ISSUE TITLE
Plastron set "Enhances effect of Absorb Spells" not functioning

### ISSUE THREAD

**Issue by Snugglepunk** [EdenServer/community#4699]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Each piece of the Plastron set excluding the body should add 10seconds duration to Absorb spells.  This is not functioning at all on Eden currently with any piece.  90sec is max possible and is just the base duration.

https://ffxiclopedia.fandom.com/wiki/Plastron_Set
https://ffxiclopedia.fandom.com/wiki/Absorb_Spells
https://ffxiclopedia.fandom.com/wiki/Absorb-INT

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
