### ISSUE TITLE
Arch Corse was intimidated by a Crab

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#4700]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I brought out a CourrierCarrie and fought an Arch Corse and at one point the Corse was intimidated by CC. I don't know of a reason why this should happen.

![image](https://user-images.githubusercontent.com/15933400/145753528-f15e2eaf-de90-4d7a-b051-4dcf203afa19.png)

**Comment by FariskaEden** [comment]
Isn't it because Courier Carrie is a PLD and has the undead killer trait?
