### ISSUE TITLE
Mobs aggro while in blm af cutsceen, cancel cs, and consume the key

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4701]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

During the blm af boots quest the Ore door CS in castle zvahl baileys doesn't prevent aggro https://ffxiclopedia.fandom.com/wiki/Recollections. If you get aggro during the cs you'll get knocked out of the CS and they key is consumed.

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
