### ISSUE TITLE
Napalm in Ordelle's Caves should have longer respawn

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4703]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Napalm in Ordelle's Caves are respawning every 5 minutes, which is OOE. Era appears to be 12 minutes.

Current Wiki
https://ffxiclopedia.fandom.com/wiki/Napalm

Era Wiki
https://ffxiclopedia.fandom.com/wiki/Napalm?oldid=375681

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
