### ISSUE TITLE
Dhalmel Hair synth is out of era

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4704]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Dhalmel Hair appears to be out of era. The first entry is 1 day after the Eden cutoff on ffxiclopedia, and bgwiki is 2008. The era page for dhalmel hide (used to make it) also does not link to dhalmel hair at all. The only use of dhalmel hair is for campaign, Gobbie Bag VIII, and DNC relic+1 upgrade.

https://ffxiclopedia.fandom.com/wiki/Dhalmel_Hair

Era Dhalmel hide, no mention of hair
https://ffxiclopedia.fandom.com/wiki/Dhalmel_Hide?oldid=341029

It is used to make Cilice which only is for Gobbiebag VIII and DNC Relic +1
https://ffxiclopedia.fandom.com/wiki/Cilice

version 30181205_0

**Comment by 59blargedy** [comment]
falls within new bounds
