### ISSUE TITLE
Crystals shouldn't drop in beastmen controlled zones 

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4705]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

We got light crystal drops today off Aura Statues while farming Diorite and sky is under beastmen control. According to wiki this should be impossible

https://ffxiclopedia.fandom.com/wiki/Signet?oldid=397003

**Comment by TracentEden** [comment]
From my understanding crystal drops happen based on who is leading in conquest in the zone at that moment, not depending on if the area is under control from the last conquest tally. Thus if you kill enough and your nation takes over the conquest race in that zone then crystals can drop. I have been told this behavior is era correct.

**Comment by KnowOne134** [comment]
Corrected on 11/21 patch
