### ISSUE TITLE
Cutscene for 2-3 fight doesn't play at horlais peak

### ISSUE THREAD

**Issue by Zackreaver** [EdenServer/community#4711]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version: 30181205_0

So for some reason, the cutscene for 2-3 doesn't play when the fight is done in sandoria, happened twice on my character and my friends character, my character was from windurst, theirs was from bastok.  I think the 2-3 cutscene for the sandy battlefield might not be working right.

The fight just goes straight from selecting "Rank 2 Final Mission" at the burning circle, to being in the battlefield, no cutscene played.

It seems to just be tied to the battlefield being performed at horlais peak.

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
