### ISSUE TITLE
Noble Mold Incorrect spell list.

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#4713]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Noble Mold appears to have an incorrect spell list.
Should only cast Water based spells such as Aquaveil, Water II, Waterga II, Enwater, Poison II.
Upon engage it opened with Freeze, then attempted to cast Aeroga II.

The NM might just be set to BLM instead of having a set list of spells. 

![image](https://user-images.githubusercontent.com/62901732/146685365-43072b0a-998e-49e3-85a7-bdc0c90928df.png)
![image](https://user-images.githubusercontent.com/62901732/146685373-f2a472d8-2653-4600-930f-8221a1034730.png)

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
