### ISSUE TITLE
Yagudo in Dynamis - Beaucedine are doing the wrong animation for "Howl".

### ISSUE THREAD

**Issue by Aslipperyotter** [EdenServer/community#4716]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Version: 30181205_0
Yagudo mobs in Dynamis-Beaucedine have a very odd animation for Howl, I think it looks like Seismostomp?
Both NMs and regular Yagudo are doing it
I can not confirm if the same is true for Yagudo in Windurst or Yagudo in other zones
Attached is a video showing exactly what is happening
https://youtu.be/Grjkd4vS3ec

Update: Tested Yagudo in Dynamis-Windurst and the animation for Howl is incorrect with them aswell. Tried Yagudo mobs in Giddeus and their animation is correct so it seems only Dynamis Yagudo are affected.

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
