### ISSUE TITLE
Hydra Summoner are able to do Grim Halo in Dynamis when they should not be able to.

### ISSUE THREAD

**Issue by Aslipperyotter** [EdenServer/community#4717]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version: 30181205_0
Hydra Summoner should not be able to use Grim Halo since they are using a one-hander (two handed move only)
I unfortunately did not grab a screenshot but can do so on test if it would be useful as "proof
![hydra summoner](https://user-images.githubusercontent.com/77862983/146698266-fa1b2527-34a7-46c0-a342-6c54d2d34456.png)
"

**Comment by FariskaEden** [comment]
https://i.gyazo.com/9aa7fb8c473440679bbda3daeed96f1b.mp4 - usage of foxfire from hydra SMN on retail (weapon based not class based)

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
