### ISSUE TITLE
Big Bomb Pop Item (Smoke-Filled Flask) Not Dropping From Grow Type Bombs In Halvung

### ISSUE THREAD

**Issue by HunnyDoo** [EdenServer/community#4718]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver30181205_0

The growing Friar's Lanterns in Halvung don't appear to have Big Bomb's pop item in their loot pool.

edit: Can verify that it is dropped by the non-growing bombs which is incorrect.

**Comment by jdpitt05** [comment]
For whatever's its worth, I've killed maybe 100+ in the area and i've only seen 2 drop.  They both dropped off the lower level one by the ??? and never from the higher level ones on the ramp.

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
