### ISSUE TITLE
Ouryu in "Ouryu Cometh" does not return to original position after wipe.

### ISSUE THREAD

**Issue by Aslipperyotter** [EdenServer/community#4719]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

During a LS attempt at this fight, we wiped and Ouryu did not return to his original position. This resulted in us not being able to attempt him again because he would just kill people as they got up and then he would stand still. I tried to recreate this on test server by simply dying to him myself, he walked a little bit towards his starting location and then turned towards the portal and stayed there till I was automatically removed. (I find it curious that after he took a few steps he turned towards the portal orienting himself as he would back at his start location, but not being in the proper location in the battlefield.)

Attached is a link showing him not resetting, it is on test but it shows the issue we faced.

https://youtu.be/edVSbNXqepU

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
