### ISSUE TITLE
Lovers in the dusk ??? will not trigger

### ISSUE THREAD

**Issue by Eolis82** [EdenServer/community#4720]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Version 30181205_0
Lovers in the Dusk ??? at (H-8) in Sanctuary of Zi'tah will not trigger Cut-Scene. I have verified that the quest is flagged and key item to trigger it is in my inventory. I received the proper pre-quest dialogue shown in the following video https://www.youtube.com/watch?v=3cG4MOMyqGM and the ??? is in the correct area with the white flowers around it. 
The ??? must be checked between 16:00 and 18:00 game time. It says nothing. There was a bug from 2019 #2193 that had the wrong time set on the ??? but no other issues shown with it. I have gone back to the quest giver to validate and nothing has changed. 

![Eolis_2021 12 24_060026](https://user-images.githubusercontent.com/75533568/147357750-7e60acf4-d7c2-4d71-96d9-9651d8704371.png)
![Eolis_2021 12 24_060102](https://user-images.githubusercontent.com/75533568/147357755-c3231d02-6cea-472b-99ee-126eb8de8bf1.png)
![Eolis_2021 12 24_060145](https://user-images.githubusercontent.com/75533568/147357761-6f3f7f05-b974-4665-94fd-b14becd450ac.png)

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
