### ISSUE TITLE
Cop 5-3 Snoll Fight Hypothermal Combustion Wins 

### ISSUE THREAD

**Issue by mark-johnstone** [EdenServer/community#4724]
### Checklist

- [Y] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [Y] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [Y] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Enter the Cop 5-3 Snoll Fight (Flames for the Dead BCNM) 
Survive for the 45s until it self destructs using Hypothermal Combustion - this grants a win on the BCNM instead of a loss, making it an easily solo-able fight 

version 30181205_0

era wiki stating if it blows up its a loss: https://ffxiclopedia.fandom.com/wiki/Where_Messengers_Gather_(Ulmia%27s_Path)?oldid=777535#Snoll_Walkthrough

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
