### ISSUE TITLE
Storing seals at Shami is OOE

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4726]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Storing seals at shami was added sometime in 2008 https://ffxiclopedia.fandom.com/wiki/Shami?direction=next&oldid=425316

**Comment by slassen** [comment]
This is going to be a tough fix. And you’ll need to edit and distribute updated dats for it. The old events are missing.

**Comment by KnowOne134** [comment]
Is in era now
