### ISSUE TITLE
Toau 13 NM Jazaraat doesn't hit hard enough

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4727]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
NM hits like an EP fomor on eden and has terrible acc so its level is propably slightly off from retail.
![image](https://user-images.githubusercontent.com/69089249/147589139-80a4a439-e627-4e0e-8df2-480aede345fd.png)
no pdt, protect IV 75 sam/war

Pics from era vids
![image](https://user-images.githubusercontent.com/69089249/147589247-449ca055-509a-420c-afd2-900200dfec28.png)

![image](https://user-images.githubusercontent.com/69089249/147591676-b5c5292f-6b28-4a56-bd1c-59ff249a0bc7.png)
(On plds, not sure if these guys levels)
![image](https://user-images.githubusercontent.com/69089249/147589479-9611b068-93b4-4028-b414-bf048e909703.png)
https://www.youtube.com/watch?v=-o7QiQnicS4 
https://www.youtube.com/watch?v=qXqLy_A2tRI

![image](https://user-images.githubusercontent.com/69089249/147590885-98f766c7-25b0-4a4b-8bd7-7a2aba544c22.png)
![image](https://user-images.githubusercontent.com/69089249/147590926-0b769fc8-e470-4320-92f4-88cb70c8f080.png)
![image](https://user-images.githubusercontent.com/69089249/147592030-24c0f160-2086-497b-a4d0-a4dacea58026.png)

https://ffxiclopedia.fandom.com/wiki/Talk:Jazaraat#Testimonials
![image](https://user-images.githubusercontent.com/69089249/147591263-7292e96a-dd30-4a4c-ada6-0052f43276d2.png)
on 67 thf no protect

Wiki has NM level set to 67 - 70.

So maybe should be hitting for ~100-160 with protect IV (?), or slightly more if you spawn it as higher level

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
