### ISSUE TITLE
Fellows should not be able to be cast on by party spells or job abilities

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#4728]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

In 3/2008 update is when the ability to use party actions on fellows were introduced. Spells such as refresh and protectra/Shellra should not proc as well as trick attack

**Comment by Mildew-Von-Eden** [comment]
That's very close to era. Pre WotG even.
