### ISSUE TITLE
Quest "Expertise" appears to be bugged

### ISSUE THREAD

**Issue by AzrielltheWise** [EdenServer/community#4729]
![ffxi_valgeir](https://user-images.githubusercontent.com/90195635/147609176-455162e7-a4b2-418c-af61-9067164dcb7d.png)
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

The Selbina quest "Expertise" appears to be bugged.  

[Eden Wiki](https://classicffxi.fandom.com/wiki/Expertise)
[FFXIclopedia](https://ffxiclopedia.fandom.com/wiki/Expertise)

Both FFXIclopedia and Eden Wiki say you must turn in ingredients to the NPC Valgeir, wait 24 in-game hours, and then talk to Valgeir again to receive the key item Crab Bisque.  I have checked Valgeir multiple times across the span of about a week, IRL time.  Each time, all he says is "What? I'm busy.  Can't this wait till later?"  Thus, it seems this quest is currently impossible to complete.

I have checked my key items, I have not received the key item Crab Bisque.

I have tried completing the next step (talking to an NPC in Mhuara), it does not work.

The quest is active in my quest log.  The prereq quests have been completed and show in my completed quest log.

I searched Github to see if anyone else had reported this.  I don't see it reported.  However, I also searched the Eden Discord and another user was complaining about this issue on 12/13/2021.

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
