### ISSUE TITLE
Tanegashima has incorrect goldsmithing subcraft level

### ISSUE THREAD

**Issue by rylendffxi** [EdenServer/community#4730]
### Checklist

- [✅ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [✅ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ✅] I have provided my client version in the details. (type /ver into your game window)
- [✅ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

While attempting to complete my GP item, Tanegashima, I was given the message “Synthesis Canceled.  That synth is beyond your current crafting skill.”

At the time I was 76smithing/40woodworking/20goldsmithing.

Eden Wiki has the synth listed as:
54smith/30wood/??goldsmithing.
https://classicffxi.fandom.com/wiki/Tanegashima

Retail Wiki has it listed as:
54smith/30wood/9goldsmithing
https://ffxiclopedia.fandom.com/wiki/Tanegashima

BG Wiki has the synth listed as:
54smith/30wood/??goldsmithing.
https://www.bg-wiki.com/ffxi/Tanegashima

This post from alla in 2006 says: “ Ok, I'm 88 Smith, 25 on Wood and 5 on Goldsmithing. I tried at lvl 3 Goldsmithing & 21 Wood no support. I made 2 after several failures without Advanced. So its less than 18 on Goldsmithing. I skilled at lvl 25 wood and 5 GS. ” https://ffxi.allakhazam.com/db/item.html?fitem=291

**Comment by bliven-was-taken** [comment]
https://www.twitch.tv/videos/1245489555  I did a retail test to confirm it is 29 or 30 woodworking, and 27 or under GSM. Think leads me to believe ffxiclopedia is correct.

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update
