### ISSUE TITLE
Trial Size Avatar fights (20 cap) shouldn't use their full bloodpact list

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4731]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The level 20 Leviathan Prime fight can have Spring Waters that heal it from 30 something % to 100%. It is likely to use this many times in the fight, which is very hard to overcome in the lvl 20 fight.

Currently mini avatars use all BPs including merited BPs, Titan used Geocrush on my carby.

Searching youtube videos, the highest level BP I see it use in this video is tail whip. It uses Water II a ton, and barracuda dive at least once, but I don't see any higher level BPs.

https://www.youtube.com/watch?v=RIF6dkO-QD8

This video is only 9 years old, but I don't see it use anything higher level than Tail Whip either.

https://www.youtube.com/watch?v=0cyCbIhQTzY&t=1s

Another here, nothing above tail whip level

https://www.youtube.com/watch?v=68XlPDHiMvA

Trying to undestand their cutoff, I checked this video too of Ifrit Prime to see if he would use Double Punch. He DID use it, but used nothing higher. I wonder if they have a level cut off, or just a "tier" cutoff. 

https://www.youtube.com/watch?v=yhVdb1s3IIg

Shiva uses nothing above Frost Armor here, hard to say what the rule is. Maybe just anything under 30? 

https://www.youtube.com/watch?v=5hqJhDDTRw4

Not definitive, but Ramuh doesn't use Rolling Thunder in any of the clips I've seen so far, maybe 30 is the cutoff then, since this is 31.

https://www.youtube.com/watch?v=2wU2HJHeuPA
https://www.youtube.com/watch?v=KASz2NZj2ng

Sorry for lack of specific info, but to me it seems like they shouldn't use any BPs 31 and above. 

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
