### ISSUE TITLE
Behemoth's Thunderbolt hits everyone in range

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4732]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Only KBs thunderbolt is supposed to hit everyone in range in and outside ally. Similar to nids hurricane wing hits everyone and NQs doesnt. Amazed this is still a thing

https://www.youtube.com/watch?v=LNx4Kz10Kzw
7:02 only hits solo nin

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
