### ISSUE TITLE
Bahamut v2 stun resist too high

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#4733]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

We did a Bahamut v2 zerg last night, it went:
Stunx5
Resist
Stun
Resistx7

Which meant that less than 30s into the fight Bahamut had full stun resist already.

In some era sources:
https://www.youtube.com/watch?v=K8jLL7-TwHA 55 second Bahamut with 17 stuns cast no resists.
https://www.youtube.com/watch?v=fR0lOcnAdFE&t=3s over 1m long, like 15ish casts that I can tell no resist.
https://youtu.be/eQY7fKAcEJ0 short fight but 7 casts no resist.

Seems like Stun resist should be exceptionally rare, I could only find 1 video where it actually happened and I'm not sure that was a resist or a bad timed stun since I couldn't see the log.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
