### ISSUE TITLE
Hide shouldnt drop aggro vs. monsters that blood aggro if hp is below threshold

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4734]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On eden hide drops aggro on undead even if used on yellow/red hp.  If hide is used against undead on yellow hp, hide should simply just fail and give the message: "Player tries to hide, but was spotted by the undeadmonster."
![image](https://user-images.githubusercontent.com/69089249/147812455-4c700581-825a-4819-9482-79ab91fb85c6.png)
![image](https://user-images.githubusercontent.com/69089249/147812538-b1890ec6-4222-4c7d-8090-cadb3101c53f.png)

![image](https://user-images.githubusercontent.com/69089249/147814870-800c029a-f8f2-4b59-815f-ced44ffc83c6.png)

On eden, Hide gives invisible + form of glitched Sneak where soundmonsters aggro and deaggro immediately when you walk to sound aggro range with hide up. 

What should happen: When hide is used against a Sound detecting monster (that is not undead), hide should fail, and give the message: 
![image](https://user-images.githubusercontent.com/69089249/148819515-14d51bfb-ff1c-4cfc-b4a9-52c9d15323ac.png)
(this hide fails because dowzer had yellow hp)

For whatever logic though, if you hide a undead mob at white hp, it does briefly lose aggro even thought its a sound mob

There is an ticket about hide giving sneak already https://github.com/EdenServer/community/issues/810) but ill sum here how hide should work vs most types of detection since Hide needs a bigger audit/update.

**Going to sum up some Hides retail mechanics after consulting dowzer/others + dowzers testing + making sense of wikies:**
- If used against sight detecting monsters, Hide will work normally, if the monster doesnt track via scent.
- If used against sight detecting monster that tracks via scent, Hide fails and gives "Player tries to hide, but was spotted by the scentmonster"-message, **regardless of range.**
- If used against sight detecting monster that tracks via scent, If you have deodorize/water weather/ice weather/if player walks through water when using hide, Hide will work normally. 
- When used against sound detecting monsters (not undead, they are special for whatever reason), hide will fail completely and give the "Player tries to hide, but was spotted by the soundmonster"-message, **regardless of range.** 
- If used against undead at white hp, Hide will work and drop aggro briefly, but quickly reaggro if you stay at sound aggro range (8)
- If used against undead at red/yellow hp, hide will not work and it will give the  "Player tries to hide, but was spotted by the undeadmonster"-message  , **regardless of range.** 
- If used against Pet users with sound pets, Hide will not work and give the  "Player tries to hide, but was spotted by the soundpet", **regardless of range.** 
- If used against Pet users with sight pets, Hide will work.
- If you link a sound/truesight/truesound/scent tracking monster + sight monsters, hide will still fail and give the "<player> tries to hide, but was spotted by the <sound/truesight/truesound/scentmonster>"-message, **regardless of range.** 
- If used against truesight/truesound monster, Hide will give the  "Player tries to hide, but was spotted by the <truesight/truesoundmonster>"-message, **regardless of range.** 

https://www.youtube.com/watch?v=cKp9HYrtzP0
dowzer testing sneak mob + sight mob link hiding

https://www.youtube.com/watch?v=KBHIs3Twz0Y
dowzer testing blood aggro drop +21 range

https://www.youtube.com/watch?v=Ex3r9PkKTfQ
Hide failing vs quadavs with deo + sneak

https://www.youtube.com/watch?v=RPZBnKwD-MA
Hide working on orc with single water weather, should work with ice weather too.
ver 30181205_0

**Comment by Steam-arch** [comment]
Hmm actually from what I heard scent follow seems to be working more or less and hide doesnt drop it. Not sure why that skele dropped aggro upon hiding it while having yellow hp since. Ill check this out abit more after new year and get back to this.

**Comment by Steam-arch** [comment]
Did some tests:
So against skeles atleast, Hide does prevent all aggro, both blood aggro and sound aggro + you can hide them in the yellow/red threshold regardless of what distance you are of the mob. 

If you walk with hide among skeles with +76%hp, the skeles aggro for a split second after you walk to sound aggro range (because hide does not have sneak implemented), but they immediately drop aggro, its basically just the aggro animation and straight going passive again. Some sound mobs seem to aggro normally but not everything.

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
