### ISSUE TITLE
Sneak attack + Hide shouldnt work on monsters that detect via sound/smell

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4735]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

SA + hide shouldnt work on monsters that aggro/track via sound/scent (unless of course you stand behind it). This is solely because Hide does not grant sneak/deo on retail. With sneak applied to you, you can still SATA Hide sound mobs though because they dont detect you, trick attack applies normally, just the SA wont proc from every angle without sneak/deodorize applied (depending on what the monster detects/tracks by.

![image](https://user-images.githubusercontent.com/69089249/147815228-3485d59d-402f-412d-8d90-3810869592f9.png)
![image](https://user-images.githubusercontent.com/69089249/147815481-f02868f5-ab3b-404b-894e-c8ef90cedf2a.png)
from sata guide page https://ffxiclopedia.fandom.com/wiki/SATA

 #810 
is more or less related to this ticket because for SATA hide to work on sound mobs, hide has to give sneak so the mob isnt able to detect the user.

Hide should give neither sneak nor deodorize, only invisible and briefly reset sound mobs which reaggro if you stay in range.

ver 30181205_0

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
