### ISSUE TITLE
Hide shouldnt grant deodorize

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4736]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Now that we actually have scent tracking on eden. Hide shouldnt drop aggro on mobs that scent track unless its rain/snow weather or you run through water which acts like deodorize (might have to be double rain/snow not sure which/both).
  
 bg wiki:
![image](https://user-images.githubusercontent.com/69089249/147817962-444e6e51-4a3c-4981-ae40-3948d020d0a6.png)

regular wiki:
![image](https://user-images.githubusercontent.com/69089249/147818026-e56a7437-a46b-41b5-9a51-bf512189e4cb.png)

discussion on allakzaham: 
![image](https://user-images.githubusercontent.com/69089249/147818496-1994b1ed-5ba4-437e-8536-482a2100f7a1.png)
![image](https://user-images.githubusercontent.com/69089249/147818534-faaa9a9a-affc-45b8-b458-598867d7f33b.png)
![image](https://user-images.githubusercontent.com/69089249/147818568-d50391c2-0233-4799-b648-89e2f7a502b7.png)
https://ffxi.allakhazam.com/db/spell.html?ffspell=258 

![image](https://user-images.githubusercontent.com/69089249/147818342-3fd625b4-7502-4935-a85b-c5951150388b.png)
skelly not blood aggroing, most likely because hide gives deodorize.

**Hide should only give invisible and hate reset sight and sound mobs (and shortly after reaggro if the mob aggros via sound and you are in range, if it scent tracks, aggro is not lost at any point unless you have deodorize from other items/spell/terrain) when hide is used**

ver 30181205_0

**Comment by Steam-arch** [comment]
Hmm actually from what I heard scent follow seems to be working more or less and hide doesnt drop it. So deodorize might not even be in hide´s effects. Not sure why that skele dropped aggro then upon hiding it while having yellow hp since blood aggro should be coded as scent.. unless its not just coded to be scent tracked? Well anyhow Ill check this out abit more after new year and get back to this.

**Comment by slassen** [comment]
Hide doesn’t grant deodorize in era. I would keep deodorizers with me in crawlers nest when pulling beetles. If I linked I’d have to flee then deodorizer then hide.

It might have had some other special condition but not deodorize.

**Comment by Steam-arch** [comment]
Closing this one because it appear to be a problem with hide dropping blood aggro and preventing it for other reasons. will leave the other one open and ill edit it to be more specific
