### ISSUE TITLE
Sabotender Bailarin drops incorrect items.

### ISSUE THREAD

**Issue by ZionGaius** [EdenServer/community#4738]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
version 30181205_0
Sabotender Bailarin drops incorrect items, it should drop Cactuar Root currently getting Cactus arm which is incorrect according to these resources https://classicffxi.fandom.com/wiki/Sabotender_Bailarin & http://www.ffxidb.com/zones/208/sabotender-bailarin

Five kills with four arms dropping, looks like the drop rate is correct just the wrong item. all with TH4.

Many thanks.

![Zion_2022 01 01_094458](https://user-images.githubusercontent.com/69005200/147871987-34dacc8d-7563-49ec-91ee-6084451eab23.png)
![Zion_2022 01 01_131044](https://user-images.githubusercontent.com/69005200/147871992-cde3dc67-8ce8-419a-b6db-aae91d69efae.png)
![Zion_2022 01 01_173249](https://user-images.githubusercontent.com/69005200/147871994-f6b35d4a-9f0e-4f28-8b36-6da085f04b7b.png)
![Gaius_2022 01 01_195705](https://user-images.githubusercontent.com/69005200/147871997-bcbf59c7-46c9-4cb2-9803-3b8cc7d253ef.png)
![Zion_2022 01 02_091720](https://user-images.githubusercontent.com/69005200/147872002-4c02e689-7674-4847-8b6a-9ab7199eec90.png)

**Comment by 59blargedy** [comment]
resolved in january 19, 2022 mini-update
