### ISSUE TITLE
Wyverns shouldn't link

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#4741]
### Details

Hurricane Wyverns in Ifrit's Cauldron don't link on retail. It's presumable that all others shouldn't as well, unless evidence is found proving certain wyverns do link with each other.

https://www.youtube.com/watch?v=CU-lsXJhmls

version 30181205_0

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
resolved in january 19, 2022 mini-update
