### ISSUE TITLE
Sabotender Bailarina's kicks hit too soft

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4743]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Bailarina's kick procs should do alot more damage than its normal autos, normal AAs are around 70, kick attacks should be around 200-270

19:49:06The Sabotender Bailarina hits Harbringer for 64 points of damage.
19:49:06The Sabotender Bailarina readies 1,000 Needles.
19:49:07The Sabotender Bailarina hits Harbringer for 78 points of damage.
19:49:07The Sabotender Bailarina hits Harbringer for 79 points of damage.

19:41:34The Sabotender Bailarina hits Smoke for 75 points of damage.
19:41:34Steam casts Refresh.Steam gains the effect of Refresh.
19:41:35The Sabotender Bailarina hits Smoke for 103 points of damage.
19:41:35Harbringer starts casting Utsusemi: Ni on Harbringer.
19:41:35The Sabotender Bailarina hits Smoke for 73 points of damage.

Proof:
![image](https://user-images.githubusercontent.com/69089249/148269955-f207f7bb-34be-41fb-a207-49fa7d7a19a4.png)
![image](https://user-images.githubusercontent.com/69089249/148270123-d2166e7e-aa5a-4092-a873-8ada36316902.png)

![image](https://user-images.githubusercontent.com/69089249/148269118-f50f2c77-89e8-4f43-9bb6-0b96e995dee3.png)
![image](https://user-images.githubusercontent.com/69089249/148269230-5d9a6992-0198-4121-b948-26a7d78af2c1.png)
![image](https://user-images.githubusercontent.com/69089249/148270256-69c456d1-c658-4bcd-bb26-e548f00d8490.png)
on  75 mnk with protect IV and 75 NIN, https://www.youtube.com/watch?v=XiQLcUySamM

Seems like no difference on kick attacks on eden.  

Also the NM is easily perma sleepable on eden which doesnt feel right but couldnt find mentions nor videos about sleep immunity/resists. That aspect might need retail testing, but it might just be building sleep resists like most nms, which isnt an eden feature yet.

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
