### ISSUE TITLE
Reraise isn't removed by Dispelling Wind

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#4744]
### Details

Hurricane Wyverns and possibly other Wyverns can't dispel Reraise with Dispelling Wind. I haven't found direct confirmation in an old video or screenshot as proof. Instead I'm using the update notes regarding Reraise being changed and a forum post. 

https://www.bg-wiki.com/ffxi/Version_Update_(12/08/2008)
> The Reraise effect granted by certain spells and items will no longer be removed by magic and abilities such as Dispel and Voidsong. 

https://ffxi.allakhazam.com/db/bestiary.html?fmob=4301
> These Wyverns will use an ability called Dispelling Wind every once in awhile during Besieged...and it can and will dispel your Reraise effect (or anything else you happen to be buffed with). 

version 30181205_0

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by falzum** [comment]
Not sure it was every properly documented but NM dispels should remove Reraise while normal mobs dispel won't. Which is in line with a besieged(NM) wyvern dispelling your rr

**Comment by dowzer** [comment]
That makes sense, I'll close this unless another source is found.

**Comment by dowzer** [comment]
Something interesting I found among Talk:Ungur @ FFXIclopedia:

> Another thing I notice is his **dispelling wind never wiped reraise from rr earing**, only other buffs. 300 xp for nin75, 292 xp for rdm73 and 6k gil each. AstralDream October 25, 2008.
