### ISSUE TITLE
Xolotl's Adds shouldnt automatically despawn when xolotl dies

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4746]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
On eden Xolotl's adds automatically despawn around 30s after Xolotl dies. On retail the adds wont depop from Xolotls death.
 
https://www.youtube.com/watch?app=desktop&v=NenGndEHCd4

Xolotl dies at 4:00 and adds dont despawn and keep fighting untill they are killed.

Not totally sure what happens to the adds if everyone warps and they are left alone, they just stand there untill game night ends (?)

Ver 30181205_0

**Comment by 59blargedy** [comment]
Resolved in January 18 2022 mini patch
