### ISSUE TITLE
Monk mobs not spawning with HP Boost. 

### ISSUE THREAD

**Issue by Fng098** [EdenServer/community#4749]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Monk type mobs do not spawn in with their HP boost.  (maybe all mobs are this way).

**Comment by 59blargedy** [comment]
im unsure what you are claiming, and there's no information provided. can you please explain why you believe this is the case? how would you be aware?

**Comment by rude-jerk** [comment]
I confirmed it. Monk mobs immediately drop to below 100% HP when acted on by any spell.

**Comment by 59blargedy** [comment]
it sounds like they actually do spawn in with hp boost trait, but their hp is just not filling up?

**Comment by Fng098** [comment]
They are at 100% HP when spawned-  claim with Therndy (or any no damage action) it will change the HP to 97%.  So the trait doesnt seem to be adding HP until its claimed?

**Comment by Fng098** [comment]
Does not do it on Provoke for some weird reason, just Threnody.

**Comment by Fng098** [comment]
![image](https://user-images.githubusercontent.com/57783175/148841490-20a3ee58-c37e-4ec4-a7e9-bb1d79f0be0e.png)

**Comment by 59blargedy** [comment]
thank you! sorry i just was unsure what you meant at first

**Comment by 59blargedy** [comment]
forgot to mention this in patch notes, but resolved in February 7, 2022 update
