### ISSUE TITLE
Mog tablet

### ISSUE THREAD

**Issue by Mikokiko** [EdenServer/community#475]
See SS a mog tablet has been discovered in Xarcabar. I was too lazy on retail to deal with this, I sure aint gonna here, but I dont think this ERA.

![kiko_2018 12 12_203437](https://user-images.githubusercontent.com/43910014/49909657-c83a4900-fe4d-11e8-800c-d27b4a77a066.png)

**Comment by panfunk** [comment]
I think the mog tablet message appeared instead of "you got keyitem xxx" message

**Comment by godmode** [comment]
Please let us know if you are using the correct version for Eden so we can open this ticket if it was an issue with the server.

**Comment by Mikokiko** [comment]
Version 30181003_1

**Comment by baroom84** [comment]
I just got this also
![baroom_2018 12 30_135022](https://user-images.githubusercontent.com/46089689/50550243-d0aac600-0c3a-11e9-92ac-59354d642828.png)
