### ISSUE TITLE
Hee Mida the Meticulous is a rng with spells

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4750]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

This is a Dynamis - Bcd NM spawn from statue # 017
https://static.wikia.nocookie.net/lowdroprates/images/d/db/Beaucedine.jpg/revision/latest?cb=20100501090622

A patch or two ago Hee Mida's 2-hour and job was changed to rng but he still has his ninjutsu spells from when he was incorrectly a nin.

**Comment by 59blargedy** [comment]
resolved in january 19, 2022 mini-update
