### ISSUE TITLE
Mining Nodes in Gusgen are not disappearing or giving items for hits

### ISSUE THREAD

**Issue by Ramp87** [EdenServer/community#4753]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Hitting mining nodes in Gusgen Mines indicates in the log that items are being mined and axes are breaking and all expectations, but the nodes are not actually giving items to the players inventory.  The nodes are not disappearing after excessive hitting either.

**Comment by KnowOne134** [comment]
Corrected 1/10/22
