### ISSUE TITLE
Castle O Passwords not Working

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#4754]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Not sure if it's an issue with server coming back up after reset, or something that will persist past the day, but Castle O passwords aren't working. 

Tried every word on the list and none registered, as well as just trying the actual combination/solution from statues. 

![image](https://user-images.githubusercontent.com/52988064/148812063-d1329a5b-6bb4-48fb-8cb1-eb967d9cb34c.png)

Will edit if it's working next game day and is just an issue on zone load.

**Comment by KnowOne134** [comment]
Corrected on 1/10/22
