### ISSUE TITLE
Self destruct damage incorrect in Nyzul Isle Investigation

### ISSUE THREAD

**Issue by Ashcroftings** [EdenServer/community#4755]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
![selfdestrruct](https://user-images.githubusercontent.com/97471878/148820873-a195f5bc-4af9-468a-a204-4d3c1771d9db.jpg)

Cluster was @ 1% health remaining yet the damage was higher than I've ever seen.

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
