### ISSUE TITLE
Learned spells disappeared

### ISSUE THREAD

**Issue by Gravionblack** [EdenServer/community#4756]
The spells I learned for my dark knight disappeared ever time I zone
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by KnowOne134** [comment]
Corrected 1/10/2022 mini update
