### ISSUE TITLE
Huu Xalmo the Savage too low HP

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4759]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Has around 2,5k hp on eden, 30k on retail
![image](https://user-images.githubusercontent.com/69089249/148842007-8a5ab149-fa3e-44c3-9f17-ab27b0280a95.png)
(had eva gear on so acc propably fine, 1 kasha did almost 50% hp)

![image](https://user-images.githubusercontent.com/69089249/148842092-759d8cda-613e-423c-a62a-b47cf31a7725.png)
![image](https://user-images.githubusercontent.com/69089249/148842157-aaf6d299-ecfc-401c-b47e-fd81117d15a8.png)
![image](https://user-images.githubusercontent.com/69089249/148842199-1f9c507d-1046-402a-afae-855d5fc36d3e.png)

Might also need a counter rate buff, but no real era videos about it so no clue about the rate
![image](https://user-images.githubusercontent.com/69089249/148842656-be503f40-bc19-4c6d-a1a3-5a9228aefdb6.png)
![image](https://user-images.githubusercontent.com/69089249/148842805-09e20e93-fe5b-4a68-9485-bfed490db356.png)

ver 30181205_0

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
