### ISSUE TITLE
Xolotl despawns at 5:00 instead of 4:00

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4760]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
![image](https://user-images.githubusercontent.com/69089249/148851488-ec913d1d-baa4-4ec9-9555-dec3162f8dcf.png)

Should despawn at the normal 04:00.
![image](https://user-images.githubusercontent.com/69089249/148849937-7e4d3027-6897-4287-ba99-a91aa5f648a7.png)

ver 30181205_0

**Comment by 59blargedy** [comment]
resolved in january 19, 2022 mini-update
