### ISSUE TITLE
Nyzul Isle Behemoth has insane hp

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4761]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Just ran into behemoth as our floor 20 boss and it's HP is off the charts. With Apoc and Gungnir we were unable to get it below 40% hp after wailing on it for 9 minutes. That's using Every two-hour, all the temp items buffs. 

As you can see in this era video(Turn volume down) it's hp drops like a rock https://www.youtube.com/watch?v=JYT5a_pTA3o

**Comment by 59blargedy** [comment]
this is fixed live

**Comment by 59blargedy** [comment]
resolved January 11, 2022
