### ISSUE TITLE
Porrogo Gent in Nyzul Isle not conning Impossible to Gauge

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#4762]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

On the "Kill specified enemies" floor of Nyzul Isle we got a Porrogo Gent floor but none of them conned Impossible to Gauge. We couldn't figure out what enemy to kill so we killed all the Porrogo and then the objective cleared.

**Comment by ThoseWhoFight** [comment]
https://i.imgur.com/2xcUPgI.png

Same for Vile Yabeewa for leader floor

**Comment by 59blargedy** [comment]
resolved January 11, 2022
