### ISSUE TITLE
Nyzul isle Psycheflayers HP way too high and uses NM only ability Reprobation

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4764]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Too high hp atleast.

![image](https://user-images.githubusercontent.com/69089249/148940559-85fcefa9-aaff-433a-9183-bf5e2ba94919.png)
We just had the same floor and the normal flayers were like IT+++++++ which seems wrong, also they used NM only tp move Reprobation, even tho they are NMs in nyzul, they might not have that on retail imo but cant confirm this rn.

Im sorry for the lack of information ill try to find more about this later and update.

**Comment by Steam-arch** [comment]
![image](https://user-images.githubusercontent.com/69089249/148941938-a264a0e0-5319-415d-9ec7-51fbf7cd0b5e.png)
punks floor parse.

I ran with a seperate group but just posting this because we ran to the same floor

**Comment by Steam-arch** [comment]
https://www.youtube.com/watch?v=10UH-F79pGo&list=PLQYIJpyD4NgtkSTtKE3t8akMbDP_s53cJ&index=5

at 16:44 they kill some flayers from ~70%. I counted 4488 damage till it died so that would make it have around 5.8k hp.

**Comment by Steam-arch** [comment]
Recounted, mb, 4889 dealt in total and ~70%ish hp so X x 0.7 = 4889, X = 4889/0.7  so puts it at  6.984k hp

**Comment by KnowOne134** [comment]
There are 2 sets. It's already adjusted, will close when patch is in

**Comment by Steam-arch** [comment]
kk

**Comment by 59blargedy** [comment]
resolved January 11, 2022
