### ISSUE TITLE
Frog Song/Chorus Charm isn't wearing off after frog dies

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#4767]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Charm didn't wear off after killing Oriri Samariri. After going up to the next floor, a charmed player was stuck on the Rune of Transfer until it wore off.

Charm should wear off after the NM/Mob dies.

Here's an example at 48:02 of this video:

https://youtu.be/DW2TG04Y-Zg?t=2882

version 30181205_0

**Comment by 59blargedy** [comment]
was just the costume, resolved in February 7, 2022 update
