### ISSUE TITLE
Ayame and Kaede Leeches ??? not giving KI upon defeat

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#4768]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Can infinitely respawn the leeches / no KI given once beaten. 

Could reproduce on GM with variables set for spawning leech step.

**Comment by perkuprightmeow** [comment]
This is also happening with the Chigoe at the end of The Prankster.

**Comment by 59blargedy** [comment]
resolved by another dev January 11, 2022
