### ISSUE TITLE
Total haste cap now in era

### ISSUE THREAD

**Issue by TracentEden** [EdenServer/community#4769]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

A haste cap of 80% should now be in era (https://www.bg-wiki.com/bg/Version_Update_(03/11/2008)), according to prior issue (https://github.com/EdenServer/community/issues/2025) there should be haste cap flag to toggle.

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
