### ISSUE TITLE
SMN - Elemental Spirits Initial Casting Timer

### ISSUE THREAD

**Issue by Mildew-Von-Eden** [EdenServer/community#4772]
### Checklist
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
When an Elemental is summoned, they will cast immediately if you have main hate on a mob. Their initial casting timer is supposed to start at half. At capped summoning skill and before external factors/gear, the timer is 45 seconds.

Source- https://ffxiclopedia.fandom.com/wiki/Spirit_Guide_by_Spira?oldid=268671#Elemental_Spirit_Casting_Timer

![20220109_223336](https://user-images.githubusercontent.com/35544823/149008626-f99c1a16-5332-4808-b68f-b3d5c8dc1cc8.png)

**Comment by 59blargedy** [comment]
mostly resolved in April 18, 2022 patch. i will put up a ticket about day/weather changes
