### ISSUE TITLE
ToaU mission 37 black screens in transition

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4773]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Got stuck in blackscreen on both characters, compass reloaded and I could run around after Naja's final line in this screenshot. Luckily I was able to type /warp II Falzum and /warp <me> on starby to get myself back to Windurst. Upon zoning back into whitegate the cutscenes continued as normal and the mission completed. 

/ver 30181205_0

![mission 37](https://user-images.githubusercontent.com/55296729/149022497-70d53921-8853-498c-89fc-242198cf09c8.PNG)

**Comment by Raulfin** [comment]
had the same, i reloged and it started the final bit with Abqu walking me out the the S.S. office.

**Comment by 59blargedy** [comment]
live patched for this and similar cses

**Comment by 59blargedy** [comment]
Formally resolved Jan 13, 2022
