### ISSUE TITLE
Nyzul Isle Bull Bugards Aggro Type

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4774]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Bull Bugards in Nyzul Isle currently have true-hearing type aggro instead of regular sound aggro. From what I can see on the wiki only the ones in besieged have true-hearing while ones in Nyzul should be regular sound aggro.

https://ffxiclopedia.fandom.com/wiki/Bull_Bugard

version 30181205_0

**Comment by 59blargedy** [comment]
Resolved Jan 13, 2022
