### ISSUE TITLE
AU40 cs typo

### ISSUE THREAD

**Issue by Raulfin** [EdenServer/community#4775]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

In the last part of the AU40 CS Naj says to speak to 'Rohin-Codimin', the npc you are meant to speak to is 'Rodin-Comidin'. Not sure if this is a SE typo from back in the day.
https://classicffxi.fandom.com/wiki/More_Questions_Than_Answers
https://i.imgur.com/rlDZU9s.png?1

**Comment by bliven-was-taken** [comment]
Naj says that on retail lol.

**Comment by 59blargedy** [comment]
yeah, it's just what he says, not sure if SE typo or indicative of his character
https://youtu.be/YJqd3h0zRRc?t=433
