### ISSUE TITLE
Should be able to guard physical tp moves

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4777]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

https://ffxiclopedia.fandom.com/wiki/Guarding_Skill

2008 wiki: https://ffxiclopedia.fandom.com/wiki/Guarding_Skill?oldid=591293 

Single hit ws should 'miss' if guarded. And multi hit ws will have the first guarded attack nullified and subsequent guarded hits deal reduced damage according to wiki.

Linked both wiki pages because the current version has more details on the expected outputs

**Comment by 59blargedy** [comment]
dupe https://github.com/EdenServer/community/issues/4507

**Comment by falzum** [comment]
So weird. I searched guard and nothing came up. Maybe I typod sorry

**Comment by 59blargedy** [comment]
Don't need to apologize. We have 21903928392 dupes, and i leave most of
them open as i don't want to discourage people from posting bug reports but
i figured you could handle it lol
