### ISSUE TITLE
Nyzul isle  - Being ported up dead while having RR disables your RR and makes you unraisable

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4778]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

If a team mate brings you up a floor while you are dead and have a RR. You cant be Raised nor will you have raise from RR.

**Comment by 59blargedy** [comment]
dupe https://github.com/EdenServer/community/issues/4757
