### ISSUE TITLE
Cure V does not generate enmity

### ISSUE THREAD

**Issue by AcornFFXI** [EdenServer/community#4780]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Cure V does not generate enmity and does not even put you on the hate list

https://drive.google.com/file/d/1C2OB9mk7gqYzU2TyA1xbaLAiaWnTv9bj/view

**Comment by slassen** [comment]
> I have provided reproducible steps.

To clarify for anyone reading. Do you mean you’re casting cure 5 on Eden and you do not generate enmity when you should? Or you are casting cure 5 on Eden and you are generating enmity when you shouldn’t?

**Comment by AcornFFXI** [comment]
The video contains reproduceable steps, but:

- player 1, pull something, do some damage, take some damage
- player 2, cast cure V on player 1 (lots of times)
- player 1, warp out
- mob ignores player 2

**Comment by 59blargedy** [comment]
resolved by another dev in january 19, 2022 update
