### ISSUE TITLE
Qiqirn Archaeologist on "Specified Enemies" floors in Nyzul have too much health

### ISSUE THREAD

**Issue by gasleavitt** [EdenServer/community#4782]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version 30181205_0

Qirin Archaeologists seem to have too much health. I have included discord screenshots to show claims of how much health they appear to have, and a developer saying it should be less and to make this report.
![Screenshot 2022-01-13 102249](https://user-images.githubusercontent.com/18636729/149368514-af02530d-fd45-40f0-8685-c05e4968b2ab.png)
![Screenshot 2022-01-13 102216](https://user-images.githubusercontent.com/18636729/149368517-68e9bbd7-c498-40c9-af2a-1d691bf796ff.png)

**Comment by Steam-arch** [comment]
The boss qiqirns might have too much hp aswell, but can not confirm atm.

**Comment by statuseffect** [comment]
The THF boss ones can also run through walls when fleeing.

**Comment by KnowOne134** [comment]
corrected 1/19/2022
