### ISSUE TITLE
Random mob spawn in Dyna-Xarc

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4784]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

https://static.wikia.nocookie.net/lowdroprates/images/1/15/Xarcabard1.jpg/revision/latest?cb=20100430122508

I believe it's statue 76 on this map. Pulling spawns 3 smns like normal but after killing 2, a 4th one spawned that summoned a dark elemental

**Comment by Norrissnake** [comment]
we had 2 NM's in Beaucadine randomly  re-pop after defeating them earlier

**Comment by 59blargedy** [comment]
resolved in january 19, 2022 mini-update
