### ISSUE TITLE
Dynamis Xarcabard Kindred TP Moves

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4785]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently Kindred in Dynamis Xarcabard aren't using Condemnation or Quadrastrike and should be able to. They were using these prior to patch.

https://ffxiclopedia.fandom.com/wiki/Category:Demons

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in january 19, 2022 mini-update
