### ISSUE TITLE
Hecatomb wave hitting for 0

### ISSUE THREAD

**Issue by somedudestolemyname** [EdenServer/community#4786]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

as per wiki i presume the calc is [(Current HP)/4 + (Level)/1.5 subject to resistst] i was astonished
tried a couple monster types in passhow and rolanberry every cast was a hit for 0

to repeat just cast hecatomb wave on something

ver 30181205_0

![Kerx_2022 01 14_203404](https://user-images.githubusercontent.com/97771638/149604903-17b7e928-cc82-49af-ba98-6c5ec9777c6b.png)
![Kerx_2022 01 14_203148](https://user-images.githubusercontent.com/97771638/149604914-ad5f0279-456e-433c-92e2-6f7a55cba280.png)

**Comment by 59blargedy** [comment]
it was just an error, it's resolved now

**Comment by 59blargedy** [comment]
resolved in january 19, 2022 mini-update
