### ISSUE TITLE
Opening Chest / Coffer with Sneak / Deodorize

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4789]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently when opening a chest / coffer with sneak or deodorize active won't remove these buffs when the chest / coffer is opened. Opening a chest / coffer should remove sneak & deodorize. Also I think there's a chest / coffer opening animation that isn't present on Eden.

https://www.youtube.com/watch?v=wnsJmJcwPaY

version 30181205_0

**Comment by dowzer** [comment]
Unless it was changed, on Eden it's possible to use a key while under the effect of invisible as well. In your video it displays the message, "You cannot use that command while invisible."

The same happened to me with a living key.

https://i.imgur.com/XhX8Kl3.mp4
