### ISSUE TITLE
Clear Mind not giving proper bonus

### ISSUE THREAD

**Issue by Eden-Beaster** [EdenServer/community#479]
Clear mind 4 should give +24, +26, +28 MP (increment by 2 each tick.)  Currently increments by 1 (+24, +25, +26)
Did not test CM3 but assume the same issue (should be +21, +23, etc.)  Not high enough level to test CM5, but should increment by 3 (+27, +30...)

**Comment by Toritos** [comment]
`INSERT INTO dspdb.traits (traitid, name, job, level, rank, modifier, value, content_tag, meritid) VALUES (24, 'clear mind', 3, 65, 4, 295, 1, NULL, 0);
INSERT INTO dspdb.traits (traitid, name, job, level, rank, modifier, value, content_tag, meritid) VALUES (24, 'clear mind', 4, 60, 4, 295, 1, NULL, 0);
INSERT INTO dspdb.traits (traitid, name, job, level, rank, modifier, value, content_tag, meritid) VALUES (24, 'clear mind', 15, 60, 4, 295, 1, NULL, 0);
INSERT INTO dspdb.traits (traitid, name, job, level, rank, modifier, value, content_tag, meritid) VALUES (24, 'clear mind', 20, 65, 4, 295, 1, 'WOTG', 0);`

^ These entries are missing in the traits table. This will fix the issue but may be better to change how it is calculated. I am hypothesising here but I reckon that when it gets a HEALMP modifier of rank 4, it tries to get a CLEAR_MIND modifier of the same rank or higher, thus ignoring the rank 3 CLEAR_MIND modifier and not finding a rank 4 one, hence why the increment was back at 1mp. I couldn't find where the formula was being calculated (I only started looking at DSP yesterday 😄), so SQL entries.

**Comment by tigo9** [comment]
Testing as a 75 blm right now, so Clear Mind V.

The first tick is 25, followed by a 28, etc. This should be 27, followed by 30, etc. Source: all revisions of the following page

https://ffxiclopedia.fandom.com/wiki/Clear_Mind

**Comment by bkesecker** [comment]
@tigo9 Opened new issue, since the report is specific to CM3 and CM4.  https://github.com/EdenServer/community/issues/3120
