### ISSUE TITLE
Stealth Bomber Gagaroon issue in Nyzul Isle

### ISSUE THREAD

**Issue by bahamut44** [EdenServer/community#4790]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Client Version 30181205_0
When fighting Stealth Bomber Gagaroon, he runs around the room dropping mines and ignoring any hate generating moves. Unable to hit the mob most of the time. When it does stop and you can get a WS off, an 800+ damage WS doesn't seem to bring its HP down by much, suggesting it has LOTS of HP. I don't know if either of these are by design or a bug. Someone in-game suggested it is bugged. It took us 20+ min to kill it and basically waisted the run. In addition, one of our party members D/C'd during the fight and when he logged back in, was unable to be invited to the party and couldn't assist. Didn't provide screenshots as I'm unsure what or how that would assist in this bug report. I can provide if needed.

**Comment by falzum** [comment]
The running around part is normal behavior but the insane hp he has I believe is in error. When we encountered him he was super chonky as well

**Comment by KnowOne134** [comment]
corrected 1/19/2022
