### ISSUE TITLE
Dance Shoes NQ/HQ model

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#4791]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Dances shoes and the +1 model are currently using the Strider/Trotter boots model.

They should be using the shoes/moccasins model.

https://ffxiclopedia.fandom.com/wiki/Linen_Cloak_Set
https://ffxiclopedia.fandom.com/wiki/Combat_Caster%27s_Cloak_Set

version 30181205_0

**Comment by Bakgodek** [comment]
I wore these quite often back in era and from what I remembered they were always Strider/Trotter boots model. I'm not seeing any proof of your claim.

**Comment by 59blargedy** [comment]
i (painfully) validated on retail by synthing them all before i scheduled a change for them. shoes = moccasins = dance shoes model. we actually have our moccasins model wrong too.

**Comment by dowzer** [comment]
Thanks, my bad for not posting the pic

https://i.imgur.com/vdhjMQV.png

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
