### ISSUE TITLE
Assault providing too many points after first run

### ISSUE THREAD

**Issue by tarutarulord** [EdenServer/community#4792]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Did assault Assault Private First Class Missions, Mamool Ja Training Grounds Missions Preemptive Strike 3 times on a character which hasn't done the assault before. Each mission success resulted in the character receiving 1500 points. 3 runs totaling 4500 points. While dual boxing, the other character, which has done the assault before, received 1000  points for successive runs.

All 3 runs were done consecutively within the same day.

Per the wiki, first run should yield 1500 points, and successive runs should yield 1000 points with the arm band adding 100 additional points.

version 30181205_0
![1500points](https://user-images.githubusercontent.com/82719341/149667672-2984586f-d9ec-4868-84f8-d1f96432b4c6.JPG)

![i dont want to do this](https://user-images.githubusercontent.com/82719341/149667752-5c3de4ed-c1fd-45ac-a5a5-0a1b06146f49.JPG)

**Comment by 59blargedy** [comment]
this has been fixed live. thank you for the report!! will formally close when maintenance occurs

**Comment by 59blargedy** [comment]
resolved in january 19, 2022 mini-update
