### ISSUE TITLE
Kick Out should be rear conal and take 2-3 shadows

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4793]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Kick Out is falsely absorbed by 1 shadow and hits only 1 target on eden, Retail accurate would be 2-3 shadows  + cone aoe 31 yalms backwards.

![image](https://user-images.githubusercontent.com/69089249/149670146-76360925-88f0-44de-b198-297ab23cdfd2.png)
![image](https://user-images.githubusercontent.com/69089249/149669801-f865e7de-c080-4c74-a631-f99641281044.png)
![image](https://user-images.githubusercontent.com/69089249/149670111-34cd8380-ed47-4d74-987d-cf48375d8057.png)

Can someone confirm this on the test server. both behe and KB are using kick out atm, NQ Behe maybe shouldnt be able to use it.

**Comment by falzum** [comment]
Makeme may have dodged some hits. Shadows lost currently is based on evasion, not ninjutsu skill like it should be. Was he consistently losing one shadow to kickout?

**Comment by dowzer** [comment]
Should NQ Behemoth use Kick Out at all? I fought it for nearly 20 minutes on retail and it used every other TP move except for that.

**Comment by Steam-arch** [comment]
Ah true! Only saw 2 kick attacks and both 1 shadow, but might have been evaded aswell. NQ can use it aswell if its attacking with its tail, pretty sure atleast.


Aaaand now that I checked allakzaham: 
![image](https://user-images.githubusercontent.com/69089249/149672807-cc456289-a67a-4373-a5f7-c665db1e10a1.png)

Hmm lol, ill check this out abit more

**Comment by Steam-arch** [comment]
bg wiki: 
![image](https://user-images.githubusercontent.com/69089249/149673081-7509b491-7abf-43f1-b0dd-8e55d3e2f95d.png)

**Comment by Steam-arch** [comment]
finalfantasu fandom 
![image](https://user-images.githubusercontent.com/69089249/149673124-a9440dac-70cf-468c-8e98-50f45ddb996d.png)

**Comment by Steam-arch** [comment]
I mean alla also claims KB kick out is a single target and its defo not. All wikis say nq behe also uses kick out.

**Comment by dowzer** [comment]
All wikis are wrong! I don't remember it using kick out, I spammed hundreds if not thousands when I went 1/151 on dring when it was changed. Anyone have evidence that it should?

**Comment by Steam-arch** [comment]
Yeah seems like it. Odd. Maybe nq shouldnt be able to use it then... ?

**Comment by slassen** [comment]
I don’t remember NQ behe ever using kickout either

**Comment by Steam-arch** [comment]
@dowzer I checked pretty much every behemoth video from YouTube (only a handful had tp moves used from behind). No kick outs used.

**Comment by dowzer** [comment]
Thanks, I looked at some and didn't see it either. Here's a kick out clip from KB:

https://i.imgur.com/Av7rV2R.mp4

- Hits multiple targets and outside of party
- Around 31' range
- Always took 2-3 shadows

**Comment by Steam-arch** [comment]
KB's kick out might be actually coded properly here, but needs a confirmation.

@dowzer Ah, maybe allakhazam listing it single target non aoe is actually true for the nq nyzul behemoth since it missed you in the screenshot (in the other bug report, but maybe it just has lower acc and its still cone)? But would explain why the wikis have different info and why kick outs listed in behemoths pages. If thats true, and KB's kick out is coded as backwards aoe 2-3 shadow cone on eden, this bug reports accidently false.

**Comment by dowzer** [comment]
I didn't have shadows in Nyzul and Limbus, I'll have to check again

**Comment by dowzer** [comment]
Nyzul Behemoth had the same range as KB and might be 1-3 shadows

https://i.imgur.com/OwBR7Ow.mp4

**Comment by Steam-arch** [comment]
So alla is simply wrong, k
