### ISSUE TITLE
NQ Behemoth shouldn't use Kick Out

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#4794]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

NQ Behemoth in Behemoth's Dominion shouldn't use Kick Out. Kronprinz Behemoths in NW Apollyon shouldn't use Kick Out as well. Nyzul Isle Behemoth WILL use Kick Out.

https://www.youtube.com/watch?v=SNCbln4Bt-8

https://i.imgur.com/xFK6U1m.png

version 30181205_0

**Comment by Steam-arch** [comment]
That is so weird tho lmao, why can the nyzul behe use kick out and the real one cant.

**Comment by dowzer** [comment]
It goes to show that not only is their coding spaghetti, so is their logic.

**Comment by dowzer** [comment]
My weirdest bug report is that saplings link trees by sound in Jugner, sight in Woodlands/Thickets, and then back to sound in Caedarva Mire.

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
