### ISSUE TITLE
ToAU 31 - Shades of Vengeance: Black screen after winning battlefield.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#4795]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

After killing 3x K23H1-LAMIAE, we received the warp/exit animation suggesting we had won the mission.  Screen then went black but the cutscene never trigged. Other K23H1-LAMIAE that had aggro'd and been slept subsequently woke up and killed us. We were able to cast spells and disengage from targets during this time. When all members died, we received the failure message indicating we'd be kicked out after 3 minutes. Upon reraising, we still had black screens and didn't get a cutscene despite not having any aggro. 

After DC'ing in order to get back in the BC without a black screen, we continued and killed 4 more K23H1-LAMIAE without anything being triggered. We received another black screen lock when being kicked out of the BCNM.

**Comment by Lilswitche** [comment]
This bug also assigned us all a "fail" for assault missions. Whenever we picked up assault orders, we had to go back to the tag NPC and he'd tell us we failed the mission (aka. lost a tag for nothing).

**Comment by Garphilius** [comment]
Just want to add to this: apparently the block that is in place for all other assaults on Eden in order to not allow more than one person to initiate the runic portal to zone into the mission zone is not in place for this mission.

We just got bugged by having two people initiate the runic portal at the same time. One person got ported to their own instance while the other two got ported to another instance.

**Comment by KnowOne134** [comment]
corrected 1/19/2022
