### ISSUE TITLE
NPC Bheem in Upper Jeuno froze character

### ISSUE THREAD

**Issue by Springfeel8** [EdenServer/community#4796]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I first checked the weather in Upper Jeuno, then randomly clicked the npc Bheem. I received no dialogue and my character became stuck. Submitted ticket. Used !unstuck. Version 30181205_0. Thank you.

**Comment by 59blargedy** [comment]
are you currently on or have completed any of the following quests: 'unlisted qualities' or 'girl in the looking glass'?
do you currently have a fellow? what is your fellow (taru, galka, etc)
im unable to replicate your issue so need more info

**Comment by Springfeel8** [comment]
I have completed those quests and my fellow is lv 40 female tarutaru Yawawa.

**Comment by 59blargedy** [comment]
this was resolved in a recent update
