### ISSUE TITLE
Genbu Tortoise Stomp

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4798]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently turtle stomp inflicts damage in a cone but should be single target for Genbu's version.

https://i.gyazo.com/0d8f0aa323652ce59321b7da5bd38800.mp4

https://ffxiclopedia.fandom.com/wiki/Turtle_Stomp

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update

**Comment by PfistoFFXI** [comment]
Has resurfaced as a bug that Tortoise stomp is now Circular AoE.
verison 30181205_0
