### ISSUE TITLE
Greater Manticores should not link

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4799]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently greater manticores link but shouldn't. Unsure if other types of manticore follow the same behaviour on retail as wiki says some types link but others don't.

https://www.youtube.com/watch?v=RW9HSUlC6Lo

https://ffxiclopedia.fandom.com/wiki/Greater_Manticore

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
