### ISSUE TITLE
Gigas Double Attacking and attacking super fast.

### ISSUE THREAD

**Issue by Cheezcakee** [EdenServer/community#48]
Gigas in beaucedine glacier double attacking and attacking very fast.

**Comment by Mozzy4Ever** [comment]
Seems to be a beastmen thing. a lot of orcs in Davoi are doing the same thing, if even they're PLD.. Monks attack very fast, and DRGs were double attacking every round.

**Comment by godmode** [comment]
Duplicate of #44

**Comment by godmode** [comment]
Seaboard Vulture and Gigas in beaucedine glacier as well
