### ISSUE TITLE
Cape Terrigan Air Elemental Level

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4800]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently air elementals found in cape terrigan are a lower level than they should be (around 50). They should range from level 67-69 here.

![image](https://user-images.githubusercontent.com/46270382/149805287-aac3f339-a434-4cbf-ac12-7b6e4d01b75c.png)

https://ffxiclopedia.fandom.com/wiki/Air_Elemental

version 30181205_0

**Comment by Raulfin** [comment]
looks to have been an undocumented change in the Jun 12 2007 update.

https://ffxiclopedia.fandom.com/wiki/Air_Elemental?diff=prev&oldid=278513

**Comment by 59blargedy** [comment]
resolved in january 19, 2022 mini-update
