### ISSUE TITLE
If ToAU Black Coffin fight is available, COR AF Head quest won't show in bcnm list at cutter

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#4801]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

have not validated this myself, but was reported by a gm that you are not given the option to complete the cor af fight if you also have the black coffin TOAU mission open (i.e. menu at cutter door will only give black coffin option).

**Comment by KnowOne134** [comment]
Corrected 2/7/2022 update
