### ISSUE TITLE
Nyzul assault "Rank-up Points"

### ISSUE THREAD

**Issue by scorchedxi** [EdenServer/community#4803]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Nyzul assault upon completing a new set of floors is not awarding 5 points toward mercenary "rank-up points". Before doing nyzul, I did 2 unique assaults and checked my progress via Abquhbah. He stated I was within the 10 point range. Upon completing up to floor 16 in nyzul (3 separate assaults), I was at the same exact range. This, to me, means that it isn't even awarding 1 point when successfully completing them.

Here is the quote from a wiki page in 2007 to show proof of both:
```You earn 5 points for completing each new set of 5 floors in Nyzul Isle Investigation.
You earn 1 point for completing a previously-completed set of 5 floors in Nyzul Isle Investigation.```
And the link to this page: https://ffxiclopedia.fandom.com/wiki/Mercenary_Rank?direction=prev&oldid=339921

**Comment by KnowOne134** [comment]
Coming in next patch. I was a day ahead of you in figuring it out

**Comment by ConteAlmaviva** [comment]
@KnowOne134 any thoughts on if we will get credit for already-completed floors? I’m at 20/25 points for my current rank up and my Nyzul static just hit floor 26. Hypothetically, if I did a non-Nyzul assault tonight, ranked up, and the patch were applied tomorrow, would I be immediately eligible for another rank up?

**Comment by KnowOne134** [comment]
After patch
 on the next run of nyzul it will count as +5 and then every run after +1

**Comment by KnowOne134** [comment]
corrected 1/19/2022
