### ISSUE TITLE
Empyreal Paradox zone-in issue

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#4804]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

If you do not receive the elevator up prompt when you zone into the Empyreal Paradox, you will be locked upon clicking the Transcendental Radiance, unable to enter any battlefield and unable to take any action at all.

**Comment by falzum** [comment]
You can check to see if you're stuck by trying to /heal. If you got the 'elevator bug' you won't be able to /heal. Crashing the client and relogging in is a temp solution for now

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
