### ISSUE TITLE
Mamool Ja's Wyvern respawn

### ISSUE THREAD

**Issue by scorchedxi** [EdenServer/community#4806]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
version 30181205_0

Mamool Ja's Wyvern pets are supposed to be a 5 minute respawn. Sometimes it is taking up to 30minutes for them to be called again.

Link
https://ffxiclopedia.fandom.com/wiki/Mamool_Ja%27s_Wyvern

If the page isn't sufficient enough evidence, please note and I will log into retail for further proof!
Thanks!

**Comment by MalteseFalcon** [comment]
There's a post referring to this camp. it starts by mentioned a patch  "around Sept 13, 2008" which would like be the patch up to which our current cut off is.

![image](https://user-images.githubusercontent.com/33695616/150218064-048ebab8-0e31-40a6-8c20-9d293e3c410c.png)


Further into the post it mentions that after first repop of wyverns they were taking 20~ minutes to repop and that wyverns were never good sustained exp.

![image](https://user-images.githubusercontent.com/33695616/150218181-9c6b6b0d-e230-4fd8-a497-a4e69eb30fc0.png)


https://evilpaul.blogspot.com/2008/10/12k-exphr-black-mage-solo-or-why.html

Confirmation it was the Sept 8 2008 patch
https://www.bg-wiki.com/ffxi/Version_Update_(09/08/2008)
![image](https://user-images.githubusercontent.com/33695616/150218486-43f5d6de-5f5e-44f1-a54c-26ef690da899.png)

**Comment by 59blargedy** [comment]
can't find when it changed to 5 minute repops, but looks to be well after our date.
