### ISSUE TITLE
Can't get key item for toau 42 after failed mission

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4809]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

If you fail you will lose your key item: Nyzul Isle Route. Another one can be obtained from Rodin-Comidin at (I-7).

https://ffxiclopedia.fandom.com/wiki/Aht_Urhgan_Mission_42:_Path_of_Darkness?oldid=398373

If you fail the mission it consumes your entry item but doesn't let you get a new one from Rodin. 

/ver 30181205_0

**Comment by FariskaEden** [comment]
Did you wait a game day after failure before trying to get it again? I think I remember being able to get one the next game day from him on retail at least.

**Comment by falzum** [comment]
I didn't wait at all since back dated wiki didn't mention a wait, but I can run over and try real quick

**Comment by falzum** [comment]
Nope, still nothing

**Comment by KnowOne134** [comment]
its a midnight wait

**Comment by falzum** [comment]
Was able to get it today after jp midnight. Thanks!
