### ISSUE TITLE
Walking Tree in Jugner Forest seem to have a 6:40ish respawn rather than a 6min respawn

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4810]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Not sure if the wiki is just vague when it says 6 min (in era and in current wiki) but the Walking Trees in Jugner Forest seem to have about a 6 min 40 second respawn time from the time the body disappears until the next pop.

![image](https://user-images.githubusercontent.com/13668758/150354483-1cc59117-c8c0-4e2a-b498-bd8b24d3be04.png)

2007 (I'll shift to 2008 in bug reports when we get those patches)
https://ffxiclopedia.fandom.com/wiki/Walking_Tree?oldid=408630

Current wiki
https://ffxiclopedia.fandom.com/wiki/Walking_Tree

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
