### ISSUE TITLE
Headgear +1 giving incorrect Guild Points

### ISSUE THREAD

**Issue by GiichiHiro** [EdenServer/community#4811]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Daily CC GP item is Headgear
Proceeded to make 9 of them, 6 of which HQ'd
Traded in the 6 HQ first, and got 756 which maths out to 126 each which is Current Retail value, and not era value:
Era Value should be 183:
https://ffxiclopedia.fandom.com/wiki/Headgear_%2B1?oldid=435915

Traded in my NQ ones and got the proper Era amount.

![Batch2](https://user-images.githubusercontent.com/66037286/150369083-294721a1-37c7-4dd0-99f6-c341cf71b223.PNG)
![BatchOne](https://user-images.githubusercontent.com/66037286/150369088-d0a5df6f-b254-4a75-8181-b0c80c7a750c.PNG)
![Ree](https://user-images.githubusercontent.com/66037286/150369085-2be14786-f013-4a2d-a5df-59c732812acb.PNG)

ver 30181205_0

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
