### ISSUE TITLE
Saga of the Skyserpent - Title Reward Missing

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4812]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The title Skyserpent Aggrandizer might not be rewarded from this quest currently as the Aht Urhgan title changer Koyol-Futenol does not have it as a selectable title.

https://ffxiclopedia.fandom.com/wiki/Saga_of_the_Skyserpent

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
