### ISSUE TITLE
Job abilities executing via macros while /healing

### ISSUE THREAD

**Issue by Acedffxi** [EdenServer/community#4816]
### Checklist

- [ /] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ /] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ /] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Version 30181205_0
I rested and hit my convert macro to apply my HP+ gear prior to converting. My Divine Seal and Convert abilities still executed while resting, the cure III in the bottom line did not. Performed this for GM[Luminous] in game. Submitting this report at their request. Seems to be something to do with Gearswap, as when I unloaded gearswap it stopped happening.

**Comment by KnowOne134** [comment]
Corrected 2/7/2022 update
