### ISSUE TITLE
Sheepfoe Mambo and Dragonfoe mambo give too little evasion

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4818]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

There is an old closed issue about this, but it does not seem to be fixed.

Old ticket: https://github.com/EdenServer/community/issues/1255

tested 21.1.2022:
Combined skill 493
![image](https://user-images.githubusercontent.com/69089249/150564713-71a0fc0e-0763-4b4c-8926-f9700c0e3673.png)

No songs:
![image](https://user-images.githubusercontent.com/69089249/150564837-a49808bc-a0fb-40bd-be26-86382a9d2049.png)
Sheepfoe mambo:
![image](https://user-images.githubusercontent.com/69089249/150564942-421695bd-27c8-42ba-a479-cc74a67d99b8.png)
Sheepfoe mambo + Dragonfoe mambo:
![image](https://user-images.githubusercontent.com/69089249/150565025-10d474ac-0d08-4b56-bbad-685094c32cf7.png)

Mambo +2 instrument, hellish bugle +1, was used

On sheepfoe mambo bg and ffxiclopedia.fandom wiki both suggest
![image](https://user-images.githubusercontent.com/69089249/150566188-9224482a-0128-4a77-bd5d-c3934f29858c.png)

ffxiclopedia.fandom about dragonfoe mambo
![image](https://user-images.githubusercontent.com/69089249/150566466-28569efa-396d-4b33-aeb4-09c544582bc6.png)

Bg wiki about dragonfoe mambo: https://www.bg-wiki.com/ffxi/Dragonfoe_Mambo
Seems like atleast dragonfoe was updated and bg has the newer info (?).

version 30181205_0

(maybe I should have just added into the old post, but it was closed so wasnt sure, feel free to close this and re-open the old one if you'd like)

**Comment by 59blargedy** [comment]
the previous issue was correctly resolved. we restructured the amounts generated and the caps were based on 
https://www.bg-wiki.com/index.php?title=Category:Mambo&oldid=379248

the above is from current wiki. it appears that changes occurred to caps in the feb 2017 update
https://forum.square-enix.com/ffxi/threads/52095-Feb.-10-2017-%28JST%29-Version-Update
which is when bg wiki updated to the current values. 
it looks like your posts are all from current wiki so im inclined to close this ticket, but if im missing something let me know, thanks.

**Comment by Steam-arch** [comment]
Can close, you are right, I think. Only "era" reference I found was this:
![image](https://user-images.githubusercontent.com/69089249/150606790-50fc1133-2db4-4348-9486-8beb82d88b28.png)

Mb, gj for not listening to me!
