### ISSUE TITLE
Minor name bug with multiple NMs

### ISSUE THREAD

**Issue by Nyoomy** [EdenServer/community#482]
It's just a minor bug that doesn't affect gameplay, but I've noticed going through the server that multiple named mobs are being treated by the game as standard creatures, so the game refers to them as "The" instead of just by their name.

Eg
![image](https://user-images.githubusercontent.com/45608627/49963134-12cfca00-ff0f-11e8-91d1-100967bcb2d7.png)

So far - Spiny Spipi, Leaping Lizzy, some Yagudo NMs I've noticed it on, I'm sure many more.

**Comment by godmode** [comment]
This is an easy to fix problem but please let us know when you see more.
