### ISSUE TITLE
Geocrush properties seem wrong?

### ISSUE THREAD

**Issue by Lilmallet** [EdenServer/community#4820]
### Checklist

ver- 30181205_0
After several days of doing the Avatar Prime fights using the magical BPs, Geocrush damage properties seem off.  Geocrush(earth based merited magical BP) is doing 600-800 on Garuda who should just be weak to ice, and is doing 99-113 on Ramuh who should be weak to earth.  All others besides Leviathan's Grand Fall, which none of my SMN friends that I do the Prime runs with have, do the expected damage, this is including all the tier IV BPs.  Which Ramuh takes appropriate damage from Stone IV, but no damage from Geocrush.  Geocrush also heals Titan, so it seems to still be earth based.

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
