### ISSUE TITLE
THF Stealing the effect of Boost from Jailer of Love crashes client

### ISSUE THREAD

**Issue by Spintimalli** [EdenServer/community#4821]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

**Precondition:** 5/5 Steal Aura merits on THF (I have 4/5. I did not gain the buff the first time i stole it. Just dispelled, and no crash)

**Repro:** Steal from JoL when he uses Fluorescence.

Stole Boost from JoL and immediately crashed. I also crashed trying to log back in until the buff was no longer on me. Hard to provide proof of claim, but should be a simple repro.

**Comment by 59blargedy** [comment]
gonna close this one out as we already have a ticket for it, but thanks for reporting!
 https://github.com/EdenServer/community/issues/3136

**Comment by Spintimalli** [comment]
I must have derped in the search, sorry bout that. I'll leave a comment on that ticket. Thanks
