### ISSUE TITLE
Sturdy Axe wrong model in game

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4822]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Seems to be set to a wrong model. 
![image](https://user-images.githubusercontent.com/69089249/150635462-65e4a7b5-425e-4064-bcf0-622b5cb3dd35.png)

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update

**Comment by statuseffect** [comment]
Wardancer has same wrong model. Appears as blue greatsword.
