### ISSUE TITLE
ToAU Mission 35 Gessho Fight

### ISSUE THREAD

**Issue by Garphilius** [EdenServer/community#4823]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

It appears that Gessho is not popping any clones throughout the fight. 

Further, he only teleported once and hate was never lost to make him do so. Fight was duo'd with a rdm and mnk.

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
