### ISSUE TITLE
Can assist with toau 42 regardless of mission progress

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4824]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently as long as the person initiating the fight is on toau 42, everyone in nyzul isle staging point that's in party will be forced into the instance. Everyone in party had assault tags because we were gearing up to do nyzul isle investigation so unsure if that is a factor. 

Was able to drag in a friend of mine who we thought was on the mission but after winning learned he hadn't gotten all his cutscenes so he should have been inelligable for entry.

**Comment by Garphilius** [comment]
I am pretty sure if anyone in your PT is not on Mission 42, it will not let you enter the instance. I tried to enter with someone on like Mission 10 and it would not let me enter.

I think the bug that Silgar faced (I am assuming Silgar is the person you are talking about) is that he did not touch the lamp in Nyzul to initiate the first CS before going into the fight.

**Comment by falzum** [comment]
It gave me the entry prompt when we had 5 people in zone, two of which were still on black coffin fight. I didn't click to try to enter because it felt wrong

**Comment by Garphilius** [comment]
If you try to hit enter it will not let you. I tried hitting enter just to see what would happen and then report it if it did let me enter with a person nowhere near the mission.

**Comment by KnowOne134** [comment]
Instances are set different than bcnms. You don't get the menu kick out until after the pick. I did forget to add in the check for clicking the rune to enter and allows anyone on the mission and over to assist. So will need to adjust that they at least clicked rune also since it does check that on win to give credit

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
