### ISSUE TITLE
Dread Spikes should be reduced by MDB

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#4825]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Monsters with magic defense bonus should reduce the amount of HP restored by Dread Spikes
https://i.imgur.com/8fDvQsB.png

1712 max HP * 0.6 = 1,027

Dmg / HP absorbed
171 / 85
168 / 84
131 / 65
172 / 86
177 / 88
186 / 93
136 / 11

Wore off after only restoring 512 HP

https://i.imgur.com/tRwZzlT.png
https://i.imgur.com/qD1vR7q.png

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
