### ISSUE TITLE
Missing "???" for Sin Hunting quest (Blank Target)

### ISSUE THREAD

**Issue by Norrissnake** [EdenServer/community#4827]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
 the ???'s are missing on the spot to get the key item for sin hunting @ h-6 in Jugner Forest.  the spot is just a blan k target and all quest pages call to check the "???"

Version 30181205_0

**Comment by 59blargedy** [comment]
is the quest is working correctly and it's just a visual issue of ???  vs. a blank target?

**Comment by Norrissnake** [comment]
the quest does complete correctly  it is just the missing  "???"

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
