### ISSUE TITLE
Activating Same Time/Order Lamps should drop all aggro

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#4828]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

For "same time" and "order" lamp floors, activating a lamp will cause you to lose aggro from any enemies that currently have you as their target.

https://www.bluegartr.com/threads/52946-Nyzul-Lamp-Order-Trick-no-its-not-random-order?p=1846041&viewfull=1#post1846041

> Kill the gears, have a BRD or WHM carefully sleep hold the Soulflayers. Touching a lamp removes the hate aggro. Not a run breaker. 

https://i.imgur.com/tFCQ3nN.mp4

**Comment by KnowOne134** [comment]
is this a retail snapshot you took?

**Comment by dowzer** [comment]
Ya that's from retail

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
