### ISSUE TITLE
Failing TOAU#31 count as Assault Mission Fail and can cost you a tag

### ISSUE THREAD

**Issue by Gantofu** [EdenServer/community#4829]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Failed TOAU#31 that required entering Periqia Assault map earlier today.
Later the evening, I grabbed a Nyzul Assault order with a tag on my char, when clicking on the Nyzul assault teleporter, nothing happened, so I went back to Rytaal to see if i can exchange tag back to obtain a new order.  
Immediately the NPC responded with mission failure messge, and hence no tag returned.
I grabbed a new tag for new assault order, and was able to enter Nyzul assault normally.
I was able to reproduce the same outcome with my other char that entered the same TOAU#31 earlier. 

Client version 30181205_0

To reproduce the issue:
Following screenshot was taken using my other character that ran the same TOAU#31
-get a new order with existing tag on char
-go straight to Rytaal, and received mission fail message

![image](https://user-images.githubusercontent.com/59887688/150666251-ad1979e6-3443-4818-87eb-c879dc1ae169.png)

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
