### ISSUE TITLE
Chocobo's run too fast

### ISSUE THREAD

**Issue by Strumerjohn** [EdenServer/community#483]
They seem to be running at normal retail rates and not the of era rate that is like 10-20% slower.

**Comment by godmode** [comment]
I was unable to verify if this was a thing or not but if it was--it appears that it is all clientside so we won't able to fix it until we release an older client. (At least a year away)

**Comment by godmode** [comment]
Just did some extensive testing and determined they are the correct speed. If you find this is not the case please post. I verified by having a fleeing THF run alongside a chocobo for several minutes.,
