### ISSUE TITLE
Floor 100 Khimaira Fulmination HP%

### ISSUE THREAD

**Issue by MalteseFalcon** [EdenServer/community#4830]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Floor 100 Khimaira appears to use Fulmination at any HP%. First time it used was around 55-60%. Wiki states it should be "at low health". 

![image](https://user-images.githubusercontent.com/33695616/150690639-6f995d6a-5c2a-4ef0-951e-f8819c0fd611.png)

Watched a few videos and never saw a Fulmination in any of them but a group says "now comes the hard part" at what appears to be normal HP for access to Fulmination (~37%.).

https://youtu.be/DlrlsfRAfRU?t=115

ver 30181205_0

**Comment by 59blargedy** [comment]
this is fixed live

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
