### ISSUE TITLE
equipping Werebuster gives 8 STR

### ISSUE THREAD

**Issue by Aslipperyotter** [EdenServer/community#4831]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
![werebuster](https://user-images.githubusercontent.com/77862983/150694137-d559a66c-7edf-4df9-820d-c697efcf61c6.png)
*Submitting on behalf of another*
Equipping Werebuster gives 8 STR (see SS)

Also despite having the Mystic Boon obtainment quest active, after closing 90+ SC the npc gives message that corresponds to the lowest amount of points

**Comment by Aslipperyotter** [comment]
Edit: Misunderstanding for WS point accumulation so disregard. STR+8 is still a bug however.

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
