### ISSUE TITLE
No HQ GP crafter rings are now in Era

### ISSUE THREAD

**Issue by TracentEden** [EdenServer/community#4832]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
The no HQ GP crafter rings (such as [Smith's Ring](https://ffxiclopedia.fandom.com/wiki/Smith%27s_Ring)) are now in era (see https://www.bg-wiki.com/ffxi/Version_Update_(06/09/2008)). See https://github.com/EdenServer/community/issues/1701 for the issue that removed them originally in case that is of any help for devs.

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
