### ISSUE TITLE
Shell We Dance Issues

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4833]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver = 30181205_0
Basing issues off of: https://youtu.be/RzkSwhLgmsI?t=135, https://www.youtube.com/watch?v=prJoIZposDU , https://www.youtube.com/watch?v=-HIzIa01cQw , https://youtu.be/GvF7S70UZKQ

# Mechanics
In the first vid, Bladmall didn't go into shell until he was cast on. Maybe going into shell is HP based? Though 4th vid counters that since Bladmall ate a 1038 Blizzard IV and didn't go into shell...

In first vid, Parata went into shell almost immediately upon taking damage. 100%->77% in 2 nukes (~2.5k damage it looked like )

BLM who took video did a 1338 Freeze 2 with Parata out of shell. 795 Burst II, 634 Thunder 4, and 578 Blizzard 4, while in shell. Seems like they should have -50% MDT while in shell. 

Time spent from start of being in shell to end was <20 seconds, after a volley of nukes and immediately went back in which suggests in/out has a damage amount attached to it as well as time. Currently on Eden this seems -mostly- time based? Though not 100% sure. Could be the damage  required to force it in/out is to high? Bladmall went into shell @ 5:08 in 1st vid after 2 nukes brought it from 68%->56%. Didn't come out until 6:38 (1.5 minutes later). DoTs only took it to 52% in that time. 1339 Freeze II brought it from 51%->36% and pushed it back into shell @ 6:50. @ 8:34 (1 min. 44s later) it came back out of shell once it ticked from 30% to 29% (8% of it's HP done via a nuke & DoTs)

"Gas Shell" TP move missing. Can use both in and out of shell. If there isn't anybody in range, it produces a "No valid target in range" message in chat. If it doesn't have a valid target, it seems to not use it's TP? Though hard to tell. Radius <15' it seems? Maybe 10'.

# Bladmall
Seems to have too high of HP on Eden. In vid @ 6:48 the BLM does a 1339 Freeze 2 for ~14% of it's HP which would put Bladmall's HP at 9.5-10kish I believe. 4th vid has a 1176 Blizzard IV taking 11% though which indicates ~10,690hp?

Bladmall missing: Cure 5 (which he can cast on the other Urganites), Erase, Paralyga (3rd vid)

Nepionic Bladmall missing: Water III, Waterga II

# Parata
Parata went from 89% to 77% from a 1338 Freeze II which would put his HP at around 11,150

Parata should have MP to Aspir based on 3rd video (@ 4:09)

Parata's melees seem weak. In the first video it hits the BLM (who is mid-cast so no PDT) for 279. Currently on Eden it hits me for 130-150ish typically with 264 defense, no PDT.

Nepionic Paratas should have ~2600hp. Currently have 1.9k-2k.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
