### ISSUE TITLE
Nyzul: saving floor progress after beating floor 100 doesnt save to disk floor 100

### ISSUE THREAD

**Issue by tacbox3** [EdenServer/community#4834]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [? ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

My group cleared Nyzul earlier today. We had one tag left and ran floor 80 once after obtaining our runic keys.
![image](https://user-images.githubusercontent.com/48967119/150745899-a1b11bd1-1ccc-403b-9421-f6ebdee3bf23.png)

I activated my Radiant Lance quest after the floor 80 run, and accumulated 367 WSP
![image](https://user-images.githubusercontent.com/48967119/150746081-8a8a8c6c-5384-4453-b8f1-8882f84807e5.png)

For floor 100 this is more than enough to complete the quest. However, I am getting the ~25% message from Zalsuhm
![image](https://user-images.githubusercontent.com/48967119/150746190-372303cc-0ff8-45f7-b725-89c20f8e0b97.png)

Does the quest think I am on floor 80? Report entered as discussed with Luminous.

version 30181205_0

**Comment by KnowOne134** [comment]
Do you actually have floor 100 saved. Having the key doesn't mean anything and there is an error in the code giving them out early that nobody has reported yet

**Comment by ThoseWhoFight** [comment]
Bliven pointed out that we didn't get "Data up to and including Floor 100 has been recorded on your runic disc." in the chat log after reviewing his text file logs. So that's likely the culprit. Because we did choose to go up to next floor after F100 boss death, which puts you back at Floor 1. So even though we successfully completed Floor 1 after 100 I guess it didn't give us the progress despite giving us Runic Keys. Is that accurate?

**Comment by KnowOne134** [comment]
Correct. It shows you are at 96 still. Updating title to correct issue

**Comment by KnowOne134** [comment]
Changed. Real issue is looping back to floor 1 code doesn't recognize that you beat prior floors. It sees progress lower than current floor and doesn't save

**Comment by ThoseWhoFight** [comment]
Makes sense. So would a temp self fix to this issue be just reclearing F100 and exiting after boss so it saves progress?

**Comment by KnowOne134** [comment]
Exactly. Will have to patch, suggest until said if any group wants 100 saved to disk to exit on 100 for now

**Comment by tacbox3** [comment]
In the meantime, is there a way to correct my group's runic discs, or will we need to re-clear floor 100?

**Comment by KnowOne134** [comment]
Re-Clear, or if have picture proof can make a gm ticket. Having the key is not enough evidence

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
