### ISSUE TITLE
[Nyzul] Sewer Syrup drops Jelly Ring directly

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#4836]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

1. Enter Nyzul Isle floors 81-99
2. Locate Sewer Syrup and defeat
3. Note Jelly Ring appears in Treasure Pool when it should not
4. Note that a gold chest appears and contains ??? ring as it should

**Comment by KnowOne134** [comment]
Corrected 2/7/2022 update
