### ISSUE TITLE
Centurio XII-I does not 2hr

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4839]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

NM Centurio XII-I is impotent and is unable to use Eagle Eye Shot. Simply does not 2hr at any %.

Wiki mentions about it using 2hr
![image](https://user-images.githubusercontent.com/69089249/150839213-dc2c101c-b96f-4dc7-a2d3-668a9e5041bb.png)
![image](https://user-images.githubusercontent.com/69089249/150839231-4e083e5c-beb0-4c9c-b575-63876f43d68a.png)
https://ffxiclopedia.fandom.com/wiki/Centurio_XII-I

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
