### ISSUE TITLE
THF AF1 Quadav Stew Steal Issue

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4840]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Following the modern wiki, I talked to the NPC in windurst, then the NPC in the tenshodo and it suggests you then get your stew before going to talk to the NPC in selbina that says to get the stew. It says that you CANNOT steal a silver beastcoin and can only steal nothing or the stew at this point, yet I stole a silver beastcoin.

https://ffxiclopedia.fandom.com/wiki/The_Tenshodo_Showdown

![image](https://user-images.githubusercontent.com/13668758/150858980-f6b4beff-c78b-4566-b889-8944afeee2e2.png)
![image](https://user-images.githubusercontent.com/13668758/150859019-f0bd1766-bb0b-43aa-b2b8-27003177a889.png)

According to the modern wiki, at this point you should be able to get only the stew with a steal, maybe that isn't era? To me that sounds like enhanced information on the quest rather than something new, but now way to be sure.

![image](https://user-images.githubusercontent.com/13668758/150861292-c3168ef8-dfa9-4af6-8928-79cd6a59152b.png)

![image](https://user-images.githubusercontent.com/13668758/150861426-1bbeaf35-42d6-4025-a079-6cb16e906788.png)

![image](https://user-images.githubusercontent.com/13668758/150857086-9cb16680-0086-46a6-af8e-61423683bf61.png)

So I went and got the selbina cutscene

![image](https://user-images.githubusercontent.com/13668758/150859234-785994ae-97ca-49a9-84c5-5f3957967abc.png)

And it worked after that after a few failed attempts. Maybe related to https://github.com/EdenServer/community/issues/1222 if the user didn't have the CS in selbina before stealing. Not sure, it doesn't say if they went and did that between hours of attempts on silver and trying on garnet.

![image](https://user-images.githubusercontent.com/13668758/150860935-08297868-9fc6-4ef0-92d0-0c9f30bd2fa9.png)

version 30181205_0

**Comment by MalteseFalcon** [comment]
Also had the issue with being able to steal the silver beastcoin but I did obtain the stew without the Selbina cutscene, took maybe 8 attempts.

**Comment by E5una** [comment]
Awesome, thanks for the update ^^ that helps narrow it down fast!

**Comment by KnowOne134** [comment]
was correct on 11/19/2023 update
