### ISSUE TITLE
Dawn Mission bugged when ally defeats Promathia

### ISSUE THREAD

**Issue by davidsound** [EdenServer/community#4842]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Upon defeating Promathia and starting the cutscene, users are disconnected from the server and stuck in the zone upon logging back in and cannot progress mission.

**Comment by davidsound** [comment]
Version 30181205_0

**Comment by davidsound** [comment]
[https://i.imgur.com/CKswMbS.png](url)

**Comment by KnowOne134** [comment]
has been recitied by another dev in a prior update
