### ISSUE TITLE
Received to many guild points from daily turn in.

### ISSUE THREAD

**Issue by MauMix** [EdenServer/community#4845]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Received an absurd amount of guild points from the cooking guild. I traded around 14 hq roast carp and 10 nq at once and all hq where used and none of the nq.

![Guild1](https://user-images.githubusercontent.com/98431609/151072224-07c1770f-9564-4016-b863-a9b988d4153f.png)
![Guild2](https://user-images.githubusercontent.com/98431609/151072542-9a898e5a-57d2-4632-ba1e-a07d660675f2.png)

**Comment by Steam-arch** [comment]
Alot of people wouldnt have reported that, props to you.

**Comment by 59blargedy** [comment]
resolved by another dev in february 20, 2023 update
