### ISSUE TITLE
Troubadour + Etude increases the duration of the song but doesnt increase the time it takes for stats to decrease

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4847]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

When using Etudes with troubadour, it increases the overall time of the song itself, but stats still drop at the same rate. So for the second half of the trobadoured Etude, you have a zero stats from the etude.

I cant confirm from retail, nor did I find mentions of it, but using simple logic, the time it takes for stats to drop should most likely be doubled aswell. 

Someone can still maybe confirm this on retail just incase.

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
