### ISSUE TITLE
Bloodsucker in Nyzul checked as Tough.

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#4848]
### Checklist

- [] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)
- [] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
We saw Bloodsucker, checked it, it was Tough, decided to kill anyway.

[18:55:29] Logos obtains a ??? ring!

**Comment by MalteseFalcon** [comment]
Also has wrong mode, appears as a common leech.

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
