### ISSUE TITLE
Nyzul Isle Assault level capped to 60.

### ISSUE THREAD

**Issue by PyreOgion** [EdenServer/community#4849]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Armband was already on the player. Did not pick one up from Shahayl
Entered Nyzul Isle, and it level capped us to 60.
![60cap Nyzul](https://user-images.githubusercontent.com/32087703/151687213-0efe8499-19b2-4278-bb18-24d905ec5bf4.png)

**Comment by KnowOne134** [comment]
Member that entered did a 60 cap assault prior? Or try and was backed out of menu? It's just not possible from this entrance without something messing up at another portal

**Comment by PyreOgion** [comment]
Last assaults all of us did was Nyzul. 
We had that guess as well that it was related to the armband. The member who opened the assault recalls that the 60caps were the last they would have done, but that was many months ago.

**Comment by KnowOne134** [comment]
if any others encounter id like to hear about it and what led up to it

**Comment by statuseffect** [comment]
Just did this with my group,  person taking us in had an armband from unknown area, zone capped us at 70. Failed at boss.

**Comment by re1master** [comment]
Just had this happen to us at level 70. I took us in with an armband that was obtained from another assault area. Seems to be the possible cause.

**Comment by KnowOne134** [comment]
But you can equip 75 gear?

**Comment by re1master** [comment]
Some 75 gear was working, some was not. It seemed to mostly be what we were wearing at entry that was 75 was working.

EX: I had Algol equipped but could not equip my Aegis (when swapping to 1H Joyeuse).

**Comment by KnowOne134** [comment]
rectified few updates back
