### ISSUE TITLE
Kawahori Kabuto´s Enchantment is not usable

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4850]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The games greatest item's enchantment is not usable. When you equip it and try to use the enchantment, it just says:
![image](https://user-images.githubusercontent.com/69089249/151700851-f48c6d5f-ee12-4601-943b-8b265961e6b5.png)
![image](https://user-images.githubusercontent.com/69089249/151700802-7a1c1531-7d80-4e5d-9b12-bb48a70abf7b.png)

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
