### ISSUE TITLE
ToAU rank key items kept when promoted

### ISSUE THREAD

**Issue by ConteAlmaviva** [EdenServer/community#4852]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version: 30181205_0

After completing the PFC and SP rank up quests (making my current rank SP), I kept the PSC and PFC Wildcat badges in my temporary key items. 

![image](https://user-images.githubusercontent.com/8880996/151725666-011e8108-9bfa-40c3-a088-db4eda88a842.png)

Per feedback from Dowzer (https://discord.com/channels/482610771126386688/547611374679883787/935695328382963753), on retail you only have the badge from the rank you're on (admittedly I'm not sure if this was true in era or just the current retail behavior, but it seems like an odd thing to go back and change later on).

This is probably just cosmetic, but thought I should put in a report nonetheless.

**Comment by KnowOne134** [comment]
verified on retail and correct, 1 badge, hoofprint should be consumed on quest complete

**Comment by KnowOne134** [comment]
Corrected 2/7/2022 update
