### ISSUE TITLE
DRK Effigy Shield is immune to sleep

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4856]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver = 30181205_0

DRK Effigy Shield (ID 17539488) in Dynamis-Bastok is immune to both Sleep and Foe Lullaby. The other Effigy Shields are not

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
