### ISSUE TITLE
Extra-Fine File drop rate glitched 

### ISSUE THREAD

**Issue by asphodel-eden** [EdenServer/community#4858]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version: 30181205_0

The drop rate of Extra-Fine File (for the quest Tuning In) is either in the wrong category or glitched. In over 60 kills with TH4, I haven't seen a single file drop. I hunted Fomor Samurai / Warrior / Monk specifically in Lufaise Meadows.

**Comment by falzum** [comment]
I've only ever seen this drop from the fomor samurai by blueblade fel, and it was a pretty common drop when I farmed fomor hate for swift belts.

Perhaps it isn't in the loot table of the other fomors in the zone?

**Comment by asphodel-eden** [comment]
A linkshell member of mine says he got it from the lower level fomors in Lufaise Meadows sometime last year. Maybe one of the recent updates glitched the loot table somehow.

**Comment by pklwsl** [comment]
I have been trying to get the extra-fine file drop form the lower level fomors over the past few weeks. I would guess I'm about 0/40 on the Warrior and 0/25 combined on the lower level MNK and SAM.

**Comment by 59blargedy** [comment]
resolved in February 7, 2022 update
