### ISSUE TITLE
Leaden Salute damage incorrect

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#4859]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Based on this screenshot of damage given by Velo in the corsair channel on discord:
![image](https://user-images.githubusercontent.com/49970272/152444950-20abed86-e74e-42a7-a207-c9accabe5e4d.png)

Unsure what gear they had, but being very generous and assuming that they have Eden Leaden Salute BiS gear equipped, the damage is too high.

Using the following gear:
![image](https://user-images.githubusercontent.com/49970272/152445079-8f26770d-6be1-4d50-81af-9d031d92526c.png)

Player AGI = 115
Aspid INT = Rank A G G = 47+18+9 = 74
Player MAB with Wizard's Roll XI with a BLM in the party = 63

Assumption made they are using Pluto's Staff, Martial Gun, darksday bonus, and Wizard's Roll of 11 with a BLM in the party. If any of this wasn't the case, then the damage is even more off than expected.

According to Motenten's magic damage formula posted on a BG thread in 2014:
(Note: Leaden Salute uses dSTAT = (pAGI-mINT)×2)

Damage = ((Player Level + 2 + WSC) * fTP + dSTAT) * Elemental Staff * MAB/MDB * Weather/Day Bonus
Damage = ((75+2+28) * 4.25 + 82) * 1.15 * 1.63 * 1.1
Damage = ((105 * 4.25) + 82) * 1.15 * 1.63 * 1.1
Damage = (446 + 82) * 1.15 * 1.63 * 1.1
Damage = 528 * 1.15 * 1.63 * 1.1
Damage = 1087

This shows that the damage they did was impossible. If I had to wager a guess, perhaps the weapon's DMG or ammo DMG is making its way into the formula somehow?

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
