### ISSUE TITLE
Ballista End of Match Rewards (Tie)

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4861]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently when a match results in a tie no experience points are rewarded. The Herald NPC also does not refund gil or give out a Ballista Instawarp. I already had a Ballista Instaport temp KI but the Herald may not give this out as well if the match ends in a tie. Ballista points were still rewarded properly like they should be.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved by another dev in February 7, 2022 update
