### ISSUE TITLE
Orcs not deaggroing when riverne gates used

### ISSUE THREAD

**Issue by junebug341** [EdenServer/community#4862]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by junebug341** [comment]
hello?

**Comment by 59blargedy** [comment]
hello, what exactly are you trying to report? i can't really tell. What about orcs in misareaux coast? did you mean orcs are bypassing gates (which gates? what pos? what exactly do you mean by bypassing? are you trying to say you're using the riverne gate and you had aggro and got hit in the gate cs?) sorry, am trying to guess at your report but it's better if you let us know what actually happened. there's nothing in the details section of the report :(

**Comment by junebug341** [comment]
the gate that leads to site ao1-bo1. orc's arent deaggroing if i get pass that gate
