### ISSUE TITLE
Sacrarium Ghost NM spawning crashes zone (happened twice on spawning NM)

### ISSUE THREAD

**Issue by Hernandez915** [EdenServer/community#4866]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by Hernandez915** [comment]
Attempted to pull the NM out of the room where it spawns and both times we attempted this the zone crashed. There was another alliance in zone as well who told us they also crashed at the exact same time we did both times.

**Comment by 59blargedy** [comment]
resolved by another dev in February 7, 2022 update
