### ISSUE TITLE
Ranged Attacks absorbed by Utsusemi/Blink shouldn't give TP

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#4867]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
version 30181205_0

Ranged attacks are currently giving 20 TP per shadow absorbed with Utsusemi or Blink, this shouldn't happen.

https://i.imgur.com/m3P1XbZ.mp4
https://i.imgur.com/j7zeGr4.mp4

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch

**Comment by dowzer** [comment]
This appears to be happening again, is it intended and actually correct?

Note: TP is only gained when the ranged attack removes a shadow, if it misses, no TP is gained

![Image](https://github.com/user-attachments/assets/59da1bd5-64d2-4de1-bfa2-047976350e00)

![Image](https://github.com/user-attachments/assets/913e0539-a1c2-447b-9d23-a110778d948f)
