### ISSUE TITLE
Stirges, Oldtown Movalpolos

### ISSUE THREAD

**Issue by PfistoFFXI** [EdenServer/community#4869]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Stirges in Oldtown Movalpolos aggro, they shouldn't.
version 30181205_0
https://ffxiclopedia.fandom.com/wiki/Stirge?oldid=609116
https://classicffxi.fandom.com/wiki/Stirge

Even on the classic wiki, they are not listed as aggressive.

Reproducible steps: Rest next to these bats with no sneak.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
