### ISSUE TITLE
Ugrihd no longer recognises players as eligible for imperial coins

### ISSUE THREAD

**Issue by iklarazu** [EdenServer/community#4870]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

Prior to the patch today (07 Feb 2022,) Ugrihd, G-9 in Whitegate would offer imperial coins in exchange for credits (Beseiged version of conquest points.)

Log from earlier today:

>  [13:59:50] Ugrihd : Meowzma, is it?
I see from your PFC Wildcat badge that you are a Private First Class.
[13:59:51] Ugrihd : According to my records, your Imperial Standing currently entitles you to 96678 credits.
[13:59:53] Ugrihd : How many Imperial pieces would you like? (Maximum: 966)
[13:59:55] Ugrihd : 1 Imperial silver piece will cost you 100 credits.
[14:00:00] Ugrihd : Salaheem's Sentinels values your contribution to the success of the company.
Please come again!
[14:00:00] Obtained: Imperial silver piece.

After the patch however, Ugrihd no longer recognises anyone (I've asked a few people passing by to test) as an employee of Salaheem's Sentinels, and as such, no longer offers imperial coins:

>[17:27:34] === Area: Aht Urhgan Whitegate ===
[17:28:03] Ugrihd : Greetings!
This is the Balrahn Way branch office of Salaheem's Sentinels.
[17:28:04] Ugrihd : A thousand pardons, but our services are only available to employees of Salaheem's Sentinels.
Good day to you!

Those I've asked have all received the same message.

![image](https://user-images.githubusercontent.com/65548510/152849960-f12bd02b-981b-44a7-af2a-01be95b24359.png)

**Comment by 59blargedy** [comment]
this has already been solved live , try again

**Comment by iklarazu** [comment]
> this has already been solved live , try again

Not at the time of posting but yes, I can confirm it works now - thank you.
