### ISSUE TITLE
Capricious Cassie missing unique hate reset from Impale

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4871]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Cassie is supposed to have a unique hate reset function on the tp move "Impale". 
![image](https://user-images.githubusercontent.com/69089249/152874927-1ce5ea44-5d3c-46ee-ab77-3c1f2b96a2b6.png)

https://www.youtube.com/watch?v=QwXKz4y9Fck
Can be seen used here at 1:28

https://www.youtube.com/watch?v=U3SKhwhq_y0
Lots of hate resets, for example 4:56

**Comment by Steam-arch** [comment]
@59blargedy

Btw just realized that doing this change might require an audit on the draw in mechanic also. Since every time cassie will use an impale, the next target will get drawn in because its coded so harshly on it.

Right now the draw in is pretty rough and cassie draw ins every time you move 5-10 range from it.

![image](https://user-images.githubusercontent.com/69089249/155824720-78b51b1c-f5dc-417a-8825-fad83a3a2600.png)
Atleast wiki says its supposed to be area limited instead of distance from the monster (similar to what VV is).

https://www.youtube.com/watch?v=HzmnRrxikIw
8:57 can see cassie reset hate on the nin and just walk to the rdm.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
