### ISSUE TITLE
Voluptous Vivian And Capricious Cassie	are using Vampiric Lash instead of Drain whip

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4872]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Voluptous Vivian and Cassie should use Drain whip instead of Vampiric Lash.
![image](https://user-images.githubusercontent.com/69089249/152880465-8db3db5a-62b9-4229-8e70-3aa1b5ef363c.png)

From cassies wiki page:
![image](https://user-images.githubusercontent.com/69089249/152876742-57f2458d-c996-4f91-9848-84f87907c848.png)

cassie & vivi using drain whip from era video:
![image](https://user-images.githubusercontent.com/69089249/152875771-47c82b6e-40fc-4fd0-b1f5-410208335abf.png)
![image](https://user-images.githubusercontent.com/69089249/152877419-85a25912-024b-4468-a68d-d409cfe7c4ec.png)
![image](https://user-images.githubusercontent.com/69089249/152880206-a51289af-8fce-4d86-a9fd-0c5b0be5f7e6.png)

Currently both are using Vampiric Lash on eden, but they should have that move replaced with Drain Whip. Couldnt find any HP numbers from VV´s Drain whip.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
