### ISSUE TITLE
Bad Breath and Sweet Breath deal too much damage

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4873]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Both moves hit around 500 with Shell IV on eden from both VV & Cassie.

Era damage numbers:
![image](https://user-images.githubusercontent.com/69089249/152880721-ce45d8c5-8991-43cb-92b3-5e4cfb613c2d.png)
RDM75s with Shell IV + SS
Source: 2008 video https://www.youtube.com/watch?v=mCtheeXMuHo

![image](https://user-images.githubusercontent.com/69089249/152880753-9187a4a9-3e53-48a6-8ce3-15fcc706d883.png)
VV bad breath
![image](https://user-images.githubusercontent.com/69089249/152891457-326e32f5-f4b1-48c4-b41e-1623bb5cf936.png)
VV Sweet breath
Source: 2006 video, 0:36 https://www.youtube.com/watch?v=xR9kthcVHnQ

![image](https://user-images.githubusercontent.com/69089249/152881104-97566109-1c7c-4b55-88ea-63da31004b95.png)
CC tops 176 here  on DNC no shell
Source 2009 video https://www.youtube.com/watch?v=q-b4xEwiPxM

![image](https://user-images.githubusercontent.com/69089249/152881810-a49ff714-256b-4b54-81a2-e59f8ca76c87.png)
VV Bad Breath tops 275 on weakened taru smn no shell no ss
Source 2008 https://www.youtube.com/watch?v=KdGJr7f2Grw

![image](https://user-images.githubusercontent.com/69089249/152880831-cf602668-94eb-41dc-85a9-9ae4d8b29b07.png)
solo lvl 80 (?) Bst/whm with shell II no ss
Source: 2010 https://www.youtube.com/watch?v=gqezXqm5K7Q&t=78s

![image](https://user-images.githubusercontent.com/69089249/152892404-10739fb4-38b0-4c6d-b57f-c407e8eab530.png)
Cassie Bad Breath on nin 75 + rdm 75 with Shell IV
(Highest damage I found)

Source: https://www.youtube.com/watch?v=HzmnRrxikIw
-

**Comment by 59blargedy** [comment]
that kaoz guy often soloed things post-75, can you provide the video links to help validate?

**Comment by Steam-arch** [comment]
Added

**Comment by Steam-arch** [comment]
https://m.youtube.com/watch?v=tuJqEDEQ4Ow
Also a decent video even though its lvl 80 cap and no damages on log, but you can see hp clearly drop. 0:45 VV used 2hr and hp drops around ~150 per bad/sweet breath

**Comment by 59blargedy** [comment]
resolved (for NMs specified, assumed unique mechanics) in April 18, 2022 patch
