### ISSUE TITLE
Scouting The Ashu Tailif mobs don't move off corpse after a wipe

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4874]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Couldn't reraise at all after a wipe because mobs camped our corpses when we were camped up the stairs

https://ffxiclopedia.fandom.com/wiki/Scouting_the_Ashu_Talif?oldid=980979

According to this 2009 wiki page reraising on upper deck should be safe

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
