### ISSUE TITLE
Ashu Talif Ranged mobs don't follow up stairs

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4875]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

When pulling the ranger type fomors up the stairs they get stuck at the bottom and won't pursue up the steps, even when the player is outside of ranged attack range, which in turn links repops prematurely.

**Comment by falzum** [comment]
Ran this again today and ranged mobs are giving a lot of 'unable to see' messages especially on the stairs. Like their model is being displayed in the wrong spot maybe? You can auto attack them if you find a sweet spot but unable to cast on them at all

**Comment by falzum** [comment]
![rng stuck](https://user-images.githubusercontent.com/55296729/153290513-100023f6-db48-481b-9a14-6ddba813d466.PNG)

Ranger just chillin. He's stuck there. Had to run down and kill

**Comment by FariskaEden** [comment]
I think all hydra / fomor with ranged attacks might have this issue currently? In Dynamis Beaucedine yesterday hydra rangers / ninjas (and Velosareon) did not seem to move after being aggro'd but would attack if whoever had aggro was close enough.

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
