### ISSUE TITLE
Capricious Cassie hits too weak

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4878]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Hits relatively weak on Eden compared to retail, rarely breaks 100 with protect IV

Era Numbers

NIN75 no protect
![image](https://user-images.githubusercontent.com/69089249/152895319-c9d56f73-faeb-48fc-b940-3baab9988e82.png)
![image](https://user-images.githubusercontent.com/69089249/152897869-f8cd3131-e4bf-47af-abc6-8240a350dcfe.png)
(Can also see cassie start to do 250-295 with berserk on)
Source: 2009 https://www.youtube.com/watch?v=O4ok9MkPsZc

NIN75 no protect
![image](https://user-images.githubusercontent.com/69089249/152895548-fec45f74-388f-4e7e-b553-a669bc91278a.png)
source: https://www.youtube.com/watch?v=O4ok9MkPsZc

![image](https://user-images.githubusercontent.com/69089249/152895464-3697697b-c1fa-4351-b69e-d71ae76c2116.png)
![image](https://user-images.githubusercontent.com/69089249/152896046-3946ca78-9ebc-440a-a1f1-a43e119de744.png)
no protect DNC 75
Source: https://www.youtube.com/watch?v=q-b4xEwiPxM

NIN75 with protect IV
![image](https://user-images.githubusercontent.com/69089249/152895708-256aff91-8027-4100-ba98-a66d9b97393a.png)
![image](https://user-images.githubusercontent.com/69089249/152895778-ccc88984-d392-455a-a490-df313773103f.png)
![image](https://user-images.githubusercontent.com/69089249/152895833-2b8a130a-17e4-4981-b58e-9a60bd604d2b.png)
Source: https://www.youtube.com/watch?v=HzmnRrxikIw

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
