### ISSUE TITLE
F100 Boss in Nyzul not giving Runic Key KI on first kill with progress saved to 95

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#4880]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The floor 100 boss (verified with Hydra and Cerb) isn't giving the Runic Key on the first kill if you're saved to floor 95. 
If you go back and kill again with your progressed saved to Floor 100, you receive a Runic Key. 

![image](https://user-images.githubusercontent.com/52988064/153056018-19b9ed7a-aa85-45f1-9dd7-8f4f5992ac93.png)
![image](https://user-images.githubusercontent.com/52988064/153056037-217a3593-8fec-4d8f-9dc9-ff643434d607.png)
![image](https://user-images.githubusercontent.com/52988064/153056051-89411e31-0e82-4b84-be96-f0bbb62c5bed.png)

**Comment by ConteAlmaviva** [comment]
Related to this - shouldn't the floor 100 boss give two weapon drops, one matching the job of the person who paid tokens to take you to floor 96, and the other a random one?  We just got our first 100 clear and got only one weapon drop, a Death Sickle, with no DRK in party.

**Comment by KnowOne134** [comment]
Only of initiator has runic key. So just a problem with floor 100 not giving a key on 1st win

**Comment by ConteAlmaviva** [comment]
@KnowOne134 per the report Mozzy just put in (https://github.com/EdenServer/community/issues/4887) which linked to the September 9th version update (http://www.playonline.com/pcd/verup/ff11us/detail/3668/detail.html) which has the following:

Certain weapons previously obtainable only from monsters on the 100th floor will now be dropped by other monsters in Nyzul Isle as well. Also, defeating the monsters on the 100th floor will now result in two weapons being dropped. One weapon will be randomly determined, while the other will match the job of the player who activated the Rune of Transfer **(regardless of whether this is the player in possession of the Runic Key or not).**

**Comment by re1master** [comment]
Can confirm this is also happening with Khimaira on first clear floor 100.
![2022-02-15 08_07_12-Kitaro_2022 02 14_225949 png ‎- Photos](https://user-images.githubusercontent.com/2515375/154068288-e021e1e7-82a4-4399-892d-41d76899c65b.png)

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
