### ISSUE TITLE
Vanguard Dragons shouldn't drop Hundos

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4881]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

http://ffxidb.com/zones/135/vanguard-dragon
![image](https://user-images.githubusercontent.com/11255886/153119110-b00993a5-7c09-4f8f-a617-d84809e5a410.png)

**Comment by 59blargedy** [comment]
there's reference in three back to back posts in this forum post, as well as very low drop rates listed on old wiki, so im personally more inclined to trust the multiple sources. neo dynamis drop rates are the bulk of ffxidb there.
https://www.bluegartr.com/threads/33575-100-Currency-on-Statues-only?p=1100159&viewfull=1#post1100159

**Comment by Mozzy4Ever** [comment]
Ah you are correct. For once, FFXIClopedia had good information for drop rates 🤣 
https://ffxiclopedia.fandom.com/wiki/Talk:Vanguard_Dragon
![image](https://user-images.githubusercontent.com/11255886/153122314-4d907fca-b924-47b2-af6d-9c0689c7af03.png)
