### ISSUE TITLE
Quest "Tuning Out" - no response from ??? after NM fight. 

### ISSUE THREAD

**Issue by rka666** [EdenServer/community#4884]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

After reaching NM fight part during "Tuning Out" quest, when all 5 bee NMs are dead touching ??? responds in "Nothing out of the ordinary". Waited 15 minutes, checked ??? again and NMs respawned. Checking ???, same issue. Tried zoning/talking to NPC Romaa Mihgo for quest part before and after the fight, but she sends me to the same ??? once again. I have realised that my alt has no CoP progression (which is required for the quest), so I kicked her out of the party. Zoned after that, came back to ???, popped NMs again, killed them and before checking ???, I decided to wait until actual name of the last dead NM disappeared from screen. Clicked ??? and CS appeared. After that, all other steps were working perfectly fine and got Cache-nez in the end. 

So not 100% sure what was causing the issue, or what was actual solution of it, but might be worth looking into it.

**Comment by KnowOne134** [comment]
did same player that popped the bees same person that clicked for reward becuase that is required

**Comment by rka666** [comment]
Yes. It was only myself doing the quest. I was doing it on my main only and alt was there for support. 
As mentioned previously, I kicked my alt from party and zoned before #3 try at killing NMs.

**Comment by rathorse** [comment]
Had a similar issue, I spawned the quest and my alt was on the same quest. Killed the bee's no CS from the ???'s afterwards. I broke pt and checked again no CS. I ran back to kazam and nothing from the npc. I ran all the way back to the ???. This time not in party, I spawned the bee's killed them and got the CS.  Could just be a party bug on this leg of the quest.

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
