### ISSUE TITLE
Ashu Talif MNK, too high HP

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4885]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

MNK crew in Scouting the Ashu Talif seem to be getting their HP bonus applied after the 500hp cap. Capture vid (can PM to dev if requested, always unsure about posting capture vids in public places >.>) shows one at 6% after 469 damage

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
