### ISSUE TITLE
F100 should guarantee 2 weapons

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4887]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

http://www.playonline.com/pcd/verup/ff11us/detail/3668/detail.html says:

Certain weapons previously obtainable only from monsters on the 100th floor will now be dropped by other monsters in Nyzul Isle as well. **Also, defeating the monsters on the 100th floor will now result in two weapons being dropped.** One weapon will be randomly determined, while the other will match the job of the player who activated the Rune of Transfer **(regardless of whether this is the player in possession of the Runic Key or not).**

**Comment by KnowOne134** [comment]
Which makes the runic key in possession mean....nothing. way to go se, a ki only you can see to prove you got to floor 100 and does nothing else.

**Comment by ConteAlmaviva** [comment]
“This certifies that you have ~~gathered
no less than ten thousand carp~~ climbed no less than 100 floors of Nyzul Isle.
Please spend your time in a manner
more beneficial to society like farming bat wings.
Your achievement is noteworthy
for its utter lack of meaning."

             With heartfelt disapproval,
             ~~Gallijaux & Joulet~~ Sage Sundi

**Comment by reemer200** [comment]
Just adding some more info here, we just finished 100 and got 1 weapon (bow).  We had a Sam take us in as well.
![image](https://user-images.githubusercontent.com/99575828/154199388-d94b2adf-96f9-4f2f-910d-ca9f8118fff8.png)

**Comment by reemer200** [comment]
![image](https://user-images.githubusercontent.com/99575828/154199629-224da1e6-0fc7-46be-b59c-506dcee6dfaa.png)

We did floor 100 and just got 1 weapon.  It was a bow and a Sam brought us in.

**Comment by setsuk0** [comment]
Had this happen to us. I took us in on pld. Only received one weapon (lance). Can confirm we did all the steps correctly.

**Comment by KnowOne134** [comment]
just did this on retail tonight, 1st time completeing floor 100 got the runic key and only 1 weapon, which was a random weapon and not for the job i was on.
So looks to me the keyItem as well as being the person to pick the floor is required to get 2 weapons 1 of which is the initiators job.

by this picture it is working as intended ofr with key or not
![img_20220223_205545](https://user-images.githubusercontent.com/35616771/155450797-2dd68abc-21c7-4780-af16-42ede3521f59.png)

**Comment by KnowOne134** [comment]
round 2 and 3 of this showed that if you have the weapon already on you or in storage then it will not drop from the boss and you only get 1 random weapon

**Comment by KnowOne134** [comment]
todays testing:
found out the weapon didnt actually make it into storage for last runs. so incorrect data.
having item in storage does allow for you to get another.
if you have the item and are solo then only 1 random weapon drops
if you are in a party and someone else doesnt have the weapon then it can drop.

im now wondering can floor 100 only drop weapons nobody has yet in thier inv

**Comment by bliven-was-taken** [comment]
(You need the runic key to start the mythic quest so it's technically not needed for nothing)

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
