### ISSUE TITLE
CoP mission "An Eternal Melody" Plays the wrong cutscene upon entering Rivirne Site A01

### ISSUE THREAD

**Issue by Tavnazian** [EdenServer/community#4889]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Upon entering the area from Miseraux coast, the Cutscene for "the savage"(CoP 4-2) plays. the correct cutscene can be found here: https://youtu.be/-OkkoTBr8aM?t=1105

the incorrect cutscene (that currently plays) can be found here: https://youtu.be/tMYvpOa4ZiI?t=488

NOTE: there is a CS that plays first when you enter the area, this scene is correct. after that scene you would approach the displacement and another CS would trigger. this scene is the incorrect one.

Ver 30181205_0

**Comment by ConteAlmaviva** [comment]
I think I ran into the same thing when I was running through CoP last April: https://discord.com/channels/482610771126386688/547611374679883787/836407842847457323

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
