### ISSUE TITLE
Duendes' Amoroso does not follow around his master Tres Duendes

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4890]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Duendes is supposed to follow tres around like a normal pet. Currently roams alone in the room..

https://www.youtube.com/watch?v=V44OclDqWUE
Retail behaviour can be seen briefly at 0:20

**Comment by Steam-arch** [comment]
Tres Duendes might also be missing his 2 unique tp moves but I cant confirm this as it just might have not used them.

![image](https://user-images.githubusercontent.com/69089249/153721791-ec57acea-ef87-43be-9bc6-ba432afa6fbf.png)

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
