### ISSUE TITLE
Demon Skulls Dropping in Uleguerand Range

### ISSUE THREAD

**Issue by reemer200** [EdenServer/community#4892]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
version 30181205_0

Demon Skulls should only drop off the higher level Kindred Warrior/Summoner/Black Mage in Uleguerand Range.  They can currently also drop from the lower level Stygian/Dread/Judicator Demon in Uleguerand Range.

Links to loot tables:
Wiki link from July 2008: https://ffxiclopedia.fandom.com/wiki/Demon_Skull?oldid=605744

BG Wiki link from June 2008: https://www.bg-wiki.com/index.php?title=Demon_Skull&oldid=91740

It seems like they were added to the lower level Stygian/Dread/Judicator Demons later on, see:

https://ffxiclopedia.fandom.com/wiki/Demon_Skull?oldid=970808

**Comment by 59blargedy** [comment]
i see examples of editing in 2007 and 2008 adding to the specific mob pages. 

https://ffxiclopedia.fandom.com/wiki/Stygian_Demon?oldid=332229
https://ffxiclopedia.fandom.com/wiki/Judicator_Demon?oldid=614057
https://ffxiclopedia.fandom.com/wiki/Dread_Demon?oldid=405054
judicator looks to have been added to the skull page july 2008
https://ffxiclopedia.fandom.com/wiki/Demon_Skull?oldid=614060

it seems like it is just a case of not being added to the main demon skull page and someone finally doing it later on.  i cant find any update notes on demon skull rates being adjusted or added to existing mobs. let me know if you find any more detail, based on this research im going to close the ticket but am happy to reopen if im wrong.
