### ISSUE TITLE
New PUP attachments nm wont attach new attachments.

### ISSUE THREAD

**Issue by Koga83** [EdenServer/community#4893]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Was told to submit this so devs can take a look at it but, apparently the new attachment isnt being able to attach to the pup when you go to trade in the new attachments, thank you
The pup attachment : Optic Fiber

**Comment by 59blargedy** [comment]
There are a couple new attachments, can you clarify which one you are
referring to?

**Comment by Hamato11** [comment]
I have Condenser and Economizer, both cannot be equipped. Also noticed they do not stack. Can't confirm but I would assume none of the new attachments are useable.

**Comment by KnowOne134** [comment]
Its fixed but awaiting patch. Didn't know about stacking will look into

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
