### ISSUE TITLE
Nyzul Isle Black / Ebony Puddings don't seem to use Amorphic Spikes

### ISSUE THREAD

**Issue by ThoseWhoFight** [EdenServer/community#4894]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Maybe someone else can confirm if they have seen it before, but out of floors 1-100 and probably 20+ tags used on F80 boss runs at this point our group has yet to see any flan mobs use Amorphic Spikes TP move.

**Comment by Steam-arch** [comment]
I think this is right, went over a few runs logs and Ebony flans + Custard Bosses only used amplification and boiling point. So Ebony Flans seem to be missing Synergism (if they are able to use it in nyzul) and Amorphic spikes.

![image](https://user-images.githubusercontent.com/69089249/153840714-bca93bbe-3f48-44b7-ad17-c0211612da27.png)

Custard bosses (from which only 1 seems to be implemented atm) are also missing atleast Xenoglossia and Amorphic Scythe.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
