### ISSUE TITLE
COR AF3 Against All Odds - Bugged.

### ISSUE THREAD

**Issue by serrhenry** [EdenServer/community#4898]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Myself and a friend tried the COR AF3 Against All Odds fight. I had all prerequisite cutscenes finished. When I walk up to Cutter, I have the option to select "Against All Odds" fight. When I select the fight, "Black Coffin" starts instead. No cut scenes before or after the Black Coffin Fight. My friend and I cleared Black Coffin twice and it still kept replacing the Against All Odds fight. Neither one of us was on that mission (he was way later, I am on AU 3). 

Version: 30181205_0

**Comment by KnowOne134** [comment]
Is the menu only displaying that fight or does black coffin also appear?

Do you have that mission as current ?

**Comment by serrhenry** [comment]
The menu displays "Against All Odds" but that is not the fight that starts.

I have "Against All Odds" current. I am not that far into Aht Urghan for Black Coffin (I am on AU 3 - President Salaheem).

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
