### ISSUE TITLE
Automaton attachment Tension Spring I/II not providing attack increase 

### ISSUE THREAD

**Issue by re1master** [EdenServer/community#4899]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Automaton attachments Tension Spring & Tension Spring II are not giving additional attack power with fire maneuvers. Testing on mobs shows the same ~10 damage spread with 0 fire maneuvers and 3 fire maneuvers.

Per wiki links, there should be bonuses to attack power with additional maneuvers.

https://ffxiclopedia.fandom.com/wiki/Tension_Spring?oldid=343931
https://ffxiclopedia.fandom.com/wiki/Tension_Spring_II?oldid=346680

Version 30181205_0

**Comment by 59blargedy** [comment]
what level mobs did you observe this damage spread on, and what level are you?

**Comment by re1master** [comment]
I am PUP75 and was fighting Gigas in Xarcabard which should be between 45-48.

**Comment by E5una** [comment]
Your pet was attack capped

**Comment by 59blargedy** [comment]
yep, at a certain point attack will do nothing for you as the ratio of att/def is capped, so on lower level mobs attack bonuses don't help you out and if you're farming you can use different attachments since attack isn't useful here. hope that makes sense!
