### ISSUE TITLE
Weapon Vendor Prices

### ISSUE THREAD

**Issue by LokiStinkpalm** [EdenServer/community#49]
Both the shellbuster and the orc piercer npc values are wrong.  orc piercer sold for 275gil and shellbuster for 98.  orc piercer was vendoring for like 8.3kish and i dont remember the value for shellbuster but it certainly wasnt 98 gil

**Comment by Lilswitche** [comment]
Wiki references for the era:
[Orc Piercer](http://ffxiclopedia.wikia.com/wiki/Orc_Piercer?oldid=318843)
[Shellbuster](http://ffxiclopedia.wikia.com/wiki/Shellbuster?oldid=376746)
[Yagudo Freezer](http://ffxiclopedia.wikia.com/wiki/Yagudo_Freezer?oldid=376750)
