### ISSUE TITLE
Blu AF hat Nepionic Soulflayer hits too soft

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4904]
- [x] ### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Hits like an EP soulflayer on eden
![image](https://user-images.githubusercontent.com/69089249/154795816-cfd9bb63-39d8-41d5-90da-0e7be618b3ef.png)
on MNK75 with Protect IV + -5% dmg from black belt

some  era numbers
![image](https://user-images.githubusercontent.com/69089249/154795787-dcf1a29e-1f34-4d0a-82e3-cd8d9a74b65e.png)
on RDM 75 with protect IV id assume( https://www.youtube.com/watch?v=Ws3RQHXdUkU )

![image](https://user-images.githubusercontent.com/69089249/154796210-87f59be9-7dee-4951-8523-72cca57db066.png)
![image](https://user-images.githubusercontent.com/69089249/154796242-6d4ce62a-892f-4a53-bd9d-2c8a68622492.png)

75 WAR/nin with Protect IV ( https://www.youtube.com/watch?v=WySEHjK8rjA )

Hard to find more damage numbers from this.

Other "maybe" things
Also propably missing extra resists on: 
![image](https://user-images.githubusercontent.com/69089249/154796342-d3f92b19-ab11-434b-8209-c63ca55e75d1.png)
Since silence lands easily atleast, but I cant really confirm if he is immune to these or just highly resistant or what so Ill leave it at this.

Also not totally sure if Stonega III and Waterga III are in his spell list (or if he did just not use them or maybe he is set to a lower level)
![image](https://user-images.githubusercontent.com/69089249/154796524-d24da612-a54a-4d91-b8f5-ace9fa71e10e.png)
![image](https://user-images.githubusercontent.com/69089249/154797527-89c23d62-f513-4f3e-8c24-f22ec3a1dd93.png)
 It does not give exp on retail but going by its highest spell (if it correlates) it would be 66 I suppose.
 

Same thing for 
![image](https://user-images.githubusercontent.com/69089249/154796543-970cef40-a682-49b9-8948-9ba0b6360baf.png)

**Comment by E5una** [comment]
Giichi did a casual capture of it on retail. About 45 seconds in you can see it’s immune to silence.

https://m.youtube.com/watch?v=uGBNVF4b5H8

Eden already added the stun/terror/sleep immunity per his capture. I think because it wasn’t a full capture the level remained unknown.

**Comment by Steam-arch** [comment]
Gotcha, ty, Silence immunity makes sense.

![image](https://user-images.githubusercontent.com/69089249/154804137-4e48ba37-3e79-423b-be1d-496195a6de10.png)
Silence immunity not applied on eden currently.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
