### ISSUE TITLE
Toau 12 Black Coffin enemies arent sleepable anymore

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4906]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Should be sleepable. The Ashu Talif  has the same enemies and they were made sleep immune so going to assume that messed up with this fight too.

![image](https://user-images.githubusercontent.com/69089249/154847083-864c56df-47ee-4531-8f91-13396073d58a.png)
From Black coffin fight

**Comment by KnowOne134** [comment]
You would be correct. Use same script with if fight = this do that changes, some stuff overlaps. Will look into, I believe agro was affected also

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
