### ISSUE TITLE
Toau12 Black Coffin fight starts on its own

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4907]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Monster were already hitting Gessho when we entered. Might have something to do with 1 (me) person having cleared it already.

![image](https://user-images.githubusercontent.com/69089249/154847207-7f0fb5af-0256-4e99-87f6-da6818e4312e.png)

**Comment by KnowOne134** [comment]
Agro mechanics changed from new quest and need to separate conditions

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
