### ISSUE TITLE
Nyzul - Specified Enemy, mobs not spawning

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#4909]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Between floors 80-88 we had a Specified Enemy floor with do not destroy archaic gears. Only archaic ramparts and gears spawned. There was no Impossible to Gauge monster.

The next tag the same thing happened, but without archaic gears. This time, only ramparts and an NM spawned. There was no Impossible to Gauge monster.

**Comment by Mozzy4Ever** [comment]
This happens because of people performing actions that animation lock themselves (like casting on themselves/someone) when the bubble for going up to the next floor is supposed to be playing

**Comment by Volkaru** [comment]
Had this happen today on floor 92. No one was animation locked. Only thing I can think is that two people tried interacting with the lamp to take us up at once, possibly. Specified Enemy, Large floor with nothing but a single Archaic Rampart on it.

**Comment by KnowOne134** [comment]
issue has been resolved in last update
