### ISSUE TITLE
Mobs not chaining in Valkurm Dunes. 

### ISSUE THREAD

**Issue by Cheezcakee** [EdenServer/community#491]
We are currently killing VT lizards in valkurm at level 10 and they aren't chaining. Have gotten one Chain1 and the rest are 122 xp. Killing them super fast. Should be getting xp chains.

**Comment by Cheezcakee** [comment]
Also Chains were not working properly in Carpenter's Landing.

**Comment by Nyoomy** [comment]
Also not getting any EXP chains in dunes, kill rate is decently fast, too.

**Comment by godmode** [comment]
Does this still happen?
