### ISSUE TITLE
NM despawn issue

### ISSUE THREAD

**Issue by kingTurtles77** [EdenServer/community#4910]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [n/a] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [30181205_0] I have provided my client version in the details. (type /ver into your game window)
- [do not have, will take video if it happens again] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Xolotol in Attowha Chasm was sitting up unclaimed and despawned at 4:00 game time. When the following 20:00 gametime came around it did not re-appear as it was supposed to.

I will try to take a video to submit for evidence if it happens again.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
