### ISSUE TITLE
Unpullable statue in Dynamis Windurst

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4911]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

https://static.wikia.nocookie.net/lowdroprates/images/c/c6/Windurst1.jpg/revision/latest?cb=20100430140039

At the death house on the west side, statue 71 is 'Out of Range' of all actions. Can't be pulled with magic, ranged, and won't aggro

**Comment by 59blargedy** [comment]
that link is blank for me for some reason, so adding a new pic
![image](https://user-images.githubusercontent.com/52636208/154990837-834bd8e7-c695-4ecc-9244-c2f8184e0884.png)
to confirm, when you pull 69 70 and 71 appear, but 71 is not able to be aggroed or pulled in any way?

**Comment by setsuk0** [comment]
>to confirm, when you pull 69 70 and 71 appear, but 71 is not able to be aggroed or pulled in any way?

Correct, cannot be aggroed or pulled in any way that we could find. Adding a picture. Tried to ranged attack it and cast on it from various angles but have never been able to pull this statue since it's been broken 

![image](https://i.imgur.com/n2laDgH.png)

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch (will need updated renamer to have it not named NPC)
