### ISSUE TITLE
RSE ??? In Gusgen mines weird repop times

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4913]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The rotating ??? for the RSE Satchet in Gusgen seems to respawn anywhere from 5 to 25ish minutes after the time of death of the Aroma Fly. 

https://ffxiclopedia.fandom.com/wiki/Aroma_Fly

According to wiki it should be a static 30min repop

**Comment by KnowOne134** [comment]
resolved 10/8/2024 up update
