### ISSUE TITLE
Caedarva mire - imps named vauxia flies

### ISSUE THREAD

**Issue by failffxi** [EdenServer/community#4914]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
![image_2022-02-21_124239](https://user-images.githubusercontent.com/41841824/154957371-98464b66-c73c-49c5-a9e5-971712f08d3e.png)

Several 'Vauxia Fly' mobs in Caedarva Mire are spawning  with the imp models.

Caedarve Mire Map-2 G-9 location and it's surroundings.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
