### ISSUE TITLE
Serket's Rage timer is off - should be 20 mins. Was being fought for 27 minutes with no rage. 

### ISSUE THREAD

**Issue by HitGubz** [EdenServer/community#4915]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)
- X[ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Serket claimed at XX:07 killed at  XX:32 with no rage. Should be 20 mins according to Era wiki.

**Comment by 59blargedy** [comment]
since no proof provided here i went searching on my own and found varying reports of the 20 minute timers actually being 30. i honestly don't see anything definitive yet.

**Comment by HitGubz** [comment]
https://ffxiclopedia.fandom.com/wiki/Serket?oldid=397335 (Revision as of 21:24, 14 December 2007) - **This one is verified 20 mins.** 
https://ffxiclopedia.fandom.com/wiki/Serket?oldid=778102 (Revision as of 17:03, 29 December 2008) - **This one says verification needed 30 mins.** 
https://ffxiclopedia.fandom.com/wiki/Rage States the following
"The [August 1, 2005 patch](https://ffxiclopedia.fandom.com/wiki/2005_-_(08/1/2005)_Update_Details) read as follows 
The notorious monsters listed below will slowly grow in strength after a certain amount of time has passed since being claimed: King Arthro / Simurgh / Roc / Serket / Capricious Cassie /Lord of Onzozo / Behemoth / King Behemoth / Adamantoise / Aspidochelone / Fafnir / Nidhogg."

[King Arthro](https://ffxiclopedia.fandom.com/wiki/King_Arthro) 
20 Minutes
[Simurgh](https://ffxiclopedia.fandom.com/wiki/Simurgh) 
20 Minutes
[Roc](https://ffxiclopedia.fandom.com/wiki/Roc) 
20 Minutes
[Serket](https://ffxiclopedia.fandom.com/wiki/Serket) 
20 Minutes
[Capricious Cassie](https://ffxiclopedia.fandom.com/wiki/Capricious_Cassie) 
20 Minutes
[Lord of Onzozo](https://ffxiclopedia.fandom.com/wiki/Lord_of_Onzozo) 
20 Minutes
[Behemoth](https://ffxiclopedia.fandom.com/wiki/Behemoth) 
30 Minutes
[King Behemoth](https://ffxiclopedia.fandom.com/wiki/King_Behemoth) 
60 Minutes
[Adamantoise](https://ffxiclopedia.fandom.com/wiki/Adamantoise) 
30 Minutes
[Aspidochelone](https://ffxiclopedia.fandom.com/wiki/Aspidochelone) 
60 Minutes
[Fafnir](https://ffxiclopedia.fandom.com/wiki/Fafnir) 
60 Minutes
[Nidhogg](https://ffxiclopedia.fandom.com/wiki/Nidhogg) 
60 Minutes

**Comment by HitGubz** [comment]
I would also apply logic and say why would SE code all 'lesser HNMs' to be 20 minutes except from Serket which bucks the trend.

**Comment by 59blargedy** [comment]
yeah the original patch note did not mention timings at all, and like i said cassie and serket were shown to be 30 minutes instead of 20 while others were proven to actually be 20 like KA and simurgh, so it looks like some people made assumptions back in the day.

**Comment by HitGubz** [comment]
> yeah the original patch note did not mention timings at all, and like i said cassie and serket were shown to be 30 minutes instead of 20 while others were proven to actually be 20 like KA and simurgh, so it looks like some people made assumptions back in the day. this isn't world ending, but im just personally uncomfortable changing it when there's so many wildly different opinions on what serket's timer actually should be. (thanks for providing more information, i appreciate it)

Yeah appreciate that. no worries at all. I was a bit quick to submit the ticket, from memory it was always 20 minutes back in the day but having done some research myself now it's not easy to tell. I'll do a bit more digging and if I find anything concrete will re-raise the ticket but will close with this comment. Happy for it to remain 30 mins.
