### ISSUE TITLE
Scouting the Ashu Talif waves not moving 

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4916]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

We just attempted the fight, and the waves seemed not to be moving forward? Always spawned just shades and and more shades/fomors were also spawning mid wave. 

We killed 78 x Ashu Talif Crew and did not see a single imp or other monster
![image](https://user-images.githubusercontent.com/69089249/154986922-ed7af163-812f-4668-bb1c-64906ac49329.png)

**Comment by 59blargedy** [comment]
they're supposed to respawn mid-wave if you are very slow at killing. were you picking them off one at a time/how were you killing them? (not saying it's right to not progress, but some of this is expected)

**Comment by KnowOne134** [comment]
My personal experience getting the info for this is:
There are waves with a set amount of ids to spawn. 
If the id is in the current wave and the next wave it will respawn when it is killed before the full next wave starts.
And it can keep respawning until all mobs for the 1st wave have been killed. 
Once next wave starts if that id is not in the next wave it will not respawn again.

**Comment by Steam-arch** [comment]
Was killing them decently fast with rdm/blu sacking them and sam/war mowing through them with cor buffs. But yeah we did not use the aoe strat.

**Comment by KnowOne134** [comment]
Its not about speed but killing each mob that spawned from the original wave. Pulling each wavrle to the top and killing them and leaving the repops until full wave is done is the key.

**Comment by Steam-arch** [comment]
Hmm kk, will give it another shot later with a similarish comp and pay more attention to the waves. Maybe there was a fomor in a corner that didnt link or somethin so monsters kept respawning then (?).

**Comment by KnowOne134** [comment]
Currently there is an issue with thf/rng mobs they don't turn correctly and you have to lead them upstairs. If they are left down below they will keep linking new pops. 
Nav mesh stuff

**Comment by pimpchan** [comment]
COR mobs still remain downstairs if left unclaimed, they may or may not move if you range attack them. Also on rare occasions they are unkillable, this happens when they get on the top of the stairs (while still on the stairs). You can engage them, but cannot nuke or attack, the only thing that works is aoe WS.
