### ISSUE TITLE
Cannot deliver starting ring to other character on same account

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#4919]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I made a new character to send a Bastokan Ring to my main character. Going into the delivery box, the ring is initially greyed out. Entering my main as the recipient causes the ring to be lit again. Selecting the ring results in a delay (the ring is quickly greyed out and then lit again after selection), and then the delivery window closes with error message "Communications seem to be congested." I am able to deliver other items besides this one, so I'm guessing whatever special check that allows these EX items to be delivered is bugged.

Game version 30181205_0.

The sending and receiving characters are both the second holders of their respective names. In case the presence of deleted characters with the same name is somehow contributing to this.

**Comment by setsuk0** [comment]
Ex items are bound to that specific character and cannot be transferred. The only way to receive a Bastokan ring is to start in Bastok as a Hume or Galka. You cannot send the ring even if it's on the same account. This goes for any ex item.

**Comment by randomslumber** [comment]
> Ex items are bound to that specific character and cannot be transferred. The only way to receive a Bastokan ring is to start in Bastok as a Hume or Galka. You cannot send the ring even if it's on the same account. This goes for any ex item.

I thought I read somewhere on the EdenXI site that mentioned they can be sent between characters. Also the Eden wiki page for the ring says it can be sent to another character on the same account. https://classicffxi.fandom.com/wiki/Bastokan_Ring?so=search

**Comment by setsuk0** [comment]
> Pretty sure I saw another starting character running around with two Sandorian rings even though they lacked a subjob. So I'm guessing they didn't have enough CP to purchase them. Or I was hallucinating and the wiki is wrong and you're right.

It wouldn't even be possible to have two equipped because they are rare (i.e., can only have one in inventory) and ex (i.e., bound to that character).

**Comment by randomslumber** [comment]
Ok thanks. Still strange why the item is lit and the error message is not descriptive of the actual issue.

**Comment by setsuk0** [comment]
Tried it for myself, got the "Communications seem to be congested" message as well, so original bug report would be accurate then but if you can somehow equip two of these rings at the same time then that'll be a separate bug since the ring is "rare."

**Comment by godmode** [comment]
I believe the dats need to be edited to get rid of that message. There is a setting on the item that blocks transfer but the client doesn’t know about it so that’s why this message pops up.

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
