### ISSUE TITLE
San d'Oria mission 2-3 Mythril Sand not trading

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#492]
Went to do Sandoria mission 2-3 starting with bastok and talked to all the right NPCs.   Savae E Paleade followed by Pius and Grohm.  Pickaxed my Mine gravel, processed it for Mythril sand and headed back.  Savae wouldn't take the sand, so I talked to the other NPCs again just in case and the sand disappeared from my inventory!  Went back, got sand again, and it's still untradable.   :(

**Comment by shih58** [comment]
I'm having the same problem. Now i'm stuck with no one of advancing my ranking. So are you guys fixing it?

**Comment by godmode** [comment]
@shih58 did it disappear from your inventory as well?

**Comment by shih58** [comment]
Mine is really a bug because my other character which I duo-boxing was able to trade in the sand to the NPC. By the way, how do I get a GM ticket?

**Comment by godmode** [comment]
If this is still an issue please request a GM ticket. We are currently looking into the issue but have enabled GMs to progress you through this mission if you meet the necessary requirements.
