### ISSUE TITLE
Tuning Out Quest

### ISSUE THREAD

**Issue by junebug341** [EdenServer/community#4923]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The second cuts even not loading, after killing the 5 NM bee's in Yuh. Jungle

**Comment by 59blargedy** [comment]
for now, try waiting until the bees' name has fully disappeared before clicking. if you have more information to add to this ticket https://github.com/EdenServer/community/issues/4884  
please do, closing this new one as a duplicate
