### ISSUE TITLE
Issues receiving Shaft 2716 Operating Lever from Twinkbrix (Bionic Bug ENM)

### ISSUE THREAD

**Issue by danismyhero** [EdenServer/community#4924]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver 30181205_0

Attempting to trade Sylvan Stone to receive [Shaft 2716 Operating Lever] for ENM Bionic Bug to Twinkbrix  will result in ineligible time frame (in the past).

Notes on situation:  Last time this ENM was completed for both characters was several weeks prior, so cooldown was complete. Other ENM from this NPC (Pulling the Strings via [Shaft Gate Operating Dial] (Key Item) is on cooldown.

These ENM are accessed via separate key items, and should not be locked out from each other.

![image](https://user-images.githubusercontent.com/49649778/155242672-1d86ee06-6182-4732-a8b4-176b35ee593f.png)

**Comment by 59blargedy** [comment]
It's resolved for next update. Just some old wrong code

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
