### ISSUE TITLE
Loudspeaker II subcraft level incorrect

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#4925]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Loudspeaker II subcraft is currently set to 39 Bonecraft per Eden webpage.

![image](https://user-images.githubusercontent.com/61694447/155402172-0a960e84-b417-4012-9a6b-632508de9c28.png)

ffxiclopedia, bgwiki, and allazkazham all say ? for the subcraft

JP wiki says it should be 22? http://wiki.ffo.jp/html/9071.html

My retail testing shows at the very least it has to be 31 bonecraft or below, it can't be 39. https://www.twitch.tv/videos/1307852874

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch. level 31 based on retail testing, so may still be incorrect. since craft levels generally increase with the item, assumed jp wiki to be a typo.
