### ISSUE TITLE
Picture Perfect cannot be completed

### ISSUE THREAD

**Issue by Appotemmis** [EdenServer/community#4927]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Issues with Umberto progressing the Picture Perfect quest. Currently when attempting to complete the Picture Perfect quest with Umberto, he provides the cutscene and the text to say that the quest is complete and level cap has risen to 55 but the quest doesn't complete, speaking to Umberto again gives the same CS and the quest complete jingle but still does not raise the level cap

**Comment by Windsong2** [comment]
I have the same problem.  I "completed" the quest weeks ago, but my NPC doesn't level up.  I checked my quest log and see Picture Perfect is still listed as an active quest. The <old woman's portrait> is still in my key items.  And when I talk to Umberto again, he defaults to his non-quest dialog "... ...leave me alone."

**Comment by KnowOne134** [comment]
Fixed on next update

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
