### ISSUE TITLE
Conquest

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#493]
I think Conquest is still not working as intended: these screens were taken within a few seconds:

![pan_2018 12 14_112525](https://user-images.githubusercontent.com/36666121/50019036-98b44980-ffd1-11e8-867d-5b85d3d1d32d.png)
![chan_2018 12 14_112520](https://user-images.githubusercontent.com/36666121/50019037-98b44980-ffd1-11e8-93ad-e2a8d7f64b42.png)

**Comment by coins4clothes** [comment]
Yup, a group of 3 people is able to flip a zone relatively reliably within an hour. This creates a scramble in the last hour before reset for everyone to claim their zones. For instance, I saw 3 people in my LS flip Kolsholou in about 30 minutes from no bar to full bar, all right before tally reset.

Thanks for adding this!

@GitCash send .0025 bch to @panfunk
@GitCash send .0025 bch to @tectal831

**Comment by GitCash** [comment]
Hey **panfunk**, user **coins4clothes** tipped you **2500 bits** in Bitcoin Cash ( ~ **$0.49** ).

*[Click here to claim it!](https://gitcash.io/claim/panfunk)*

You can also add the "thumbs down" reaction to **coins4clothes**'s comment above to prevent future tips.

**Comment by coins4clothes** [comment]
@GitCash send .0025 bch to @tectal831

**Comment by GitCash** [comment]
Hey **tectal831**, user **coins4clothes** tipped you **2500 bits** in Bitcoin Cash ( ~ **$0.49** ).

*[Click here to claim it!](https://gitcash.io/claim/tectal831)*

You can also add the "thumbs down" reaction to **coins4clothes**'s comment above to prevent future tips.
