### ISSUE TITLE
Wings of Fury: Furies should use Slipstream + Turbulence

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4930]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The bat trios (Furies) in Wings of Fury seem to only have Jet Stream and Sonic Boom, but should also have Slipstream and Turbulence.

Modern Wiki:
https://ffxiclopedia.fandom.com/wiki/Wings_of_Fury
![image](https://user-images.githubusercontent.com/13668758/155829776-25e52cd4-8bac-4471-90c4-fa2153cd4d6e.png)

Era wiki:
https://ffxiclopedia.fandom.com/wiki/Wings_of_Fury?oldid=381070
![image](https://user-images.githubusercontent.com/13668758/155829765-fb3a6863-9295-4c8a-a89a-d42c40193ce2.png)

Note: the era wiki didn't listen slipstream so I found a 2013 video showing slipstream and a 2006 video showing turbulence. I think its safe to say they had both in era from this.

https://www.youtube.com/watch?v=bXeztXSnmJM

![image](https://user-images.githubusercontent.com/13668758/155829715-55b31906-bed0-49d1-97f0-909a5b75a730.png)

2006 video of turbulence

https://www.youtube.com/watch?v=185yQJFpfBI

![image](https://user-images.githubusercontent.com/13668758/155829846-55cd2882-0c67-487b-9d04-0c78d5dea224.png)

Note: We ran this BCNM 4 times tonight and never saw either, but if it was just bad RNG I'm eternally sorry for the false report ^_^

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
