### ISSUE TITLE
base counter rate incorrect

### ISSUE THREAD

**Issue by m1k3yk** [EdenServer/community#4931]
### Checklist

- [yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ yes] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ yes] I have provided my client version in the details. (type /ver into your game window)
- [ yes] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

If you equip gear that gives the trait "counter" +1, such as avengers earrings or muscle belt +1, the gear will not gear appropriate skill in said job trait.

**Comment by Steam-arch** [comment]
they are +1%s pretty sure

**Comment by Falaras** [comment]
Per bgwiki:
"Equipment that says "Counter +X" gives an X% increase in Counter [proc](https://www.bg-wiki.com/ffxi/Proc) rate, before the accuracy check."

So Avengers Earring is at best +.95% counter rate.

**Comment by m1k3yk** [comment]
I've don extensive testing with +1 and +2 with rasetsu +1 gear, and it is definitely much lower than 1/100 or 1/50. just from the feel, compared to retail. the rate does seem much lower.

**Comment by Falaras** [comment]
Can you post that testing?

**Comment by m1k3yk** [comment]
as in... post the ss of me getting hit. and it NOT proccing
?

**Comment by Falaras** [comment]
Extensive testing would be using a Parser to track your counter % rate over tens to hundreds of thousands of samples, then it can be compared to what it should be based on math (either by you or someone else) and we can find out if its wrong. Eyeballing small increases in counter rate and saying "I've done extensive testing" is not useful.

**Comment by Steam-arch** [comment]
Are you sure you were capped acc? Also did you note that in NQ rasetsu you need to have red hp (and tp below 1000 I suppose?). Muscle belt is hp below 50%

**Comment by m1k3yk** [comment]
yes, rasetsu HQ, not nq

**Comment by m1k3yk** [comment]
just trust me falaras. its at a lower rate for some reason than retail.

**Comment by falzum** [comment]
Well it sounds like either the items aren't giving the bonus like they should(maybe?), or your recollection of how good they should be is wrong. Without any numbers it's hard to say.

Provide some data on how they are supposed to work with links to proper documentation so a dev can check them for you.

**Comment by Mozzy4Ever** [comment]
The way counter is coded is that each +# is +% chance to counter. Base counter for a MNK75 is 8% (which I'm not sure if it should be 8 or 10? Can't find info on if it was 8 in era or 10 🤷 
Nonetheless, 8 is with no earring. 9 is with Avenger's so it is working.
![image](https://user-images.githubusercontent.com/11255886/155908533-53b9f612-e3c1-4b10-85cf-01689ff1ed61.png)

**Comment by falzum** [comment]
https://ffxiclopedia.fandom.com/wiki/Counter?direction=next&oldid=1281736

Here's the first page from 2011 which cites that base rate is 10%. Not sure where the 8% base mozzy is seeing comes from I can't find a source

**Comment by Falaras** [comment]
bgwiki currently has Counter I listed at 8%, which honestly could just be wrong. There's links at the bottom of that page that show info for example of a 99 Rdm/mnk with Counterstance on getting an accuracy adjusted 55% counter rate, which would lean to 10% base + 45% counterstance. https://www.bluegartr.com/threads/108197-Random-Facts-Thread-Abilities?p=5098259&viewfull=1#post5098259

**Comment by m1k3yk** [comment]
> The way counter is coded is that each +# is +% chance to counter. Base counter for a MNK75 is 8% (which I'm not sure if it should be 8 or 10? Can't find info on if it was 8 in era or 10 🤷 Nonetheless, 8 is with no earring. 9 is with Avenger's so it is working. ![image](https://user-images.githubusercontent.com/11255886/155908533-53b9f612-e3c1-4b10-85cf-01689ff1ed61.png)

ok, thank you for clearing it up.

**Comment by m1k3yk** [comment]
> bgwiki currently has Counter I listed at 8%, which honestly could just be wrong. There's links at the bottom of that page that show info for example of a 99 Rdm/mnk with Counterstance on getting an accuracy adjusted 55% counter rate, which would lean to 10% base + 45% counterstance. https://www.bluegartr.com/threads/108197-Random-Facts-Thread-Abilities?p=5098259&viewfull=1#post5098259
> 
> Worth mentioning that when they changed it from 10% to 8% on bgwiki the person linked to the JP wiki, so maybe that's where the info came from. It's a dead link now.

ah that is interesting.

**Comment by Steam-arch** [comment]
Heres a 2008 era test aswell, altho not that many attack rounds in it.
![image](https://user-images.githubusercontent.com/69089249/156009182-4684ac7d-10ff-4680-a2e4-49187af5c7eb.png)
source https://web.archive.org/web/20081003212236/https://www.ffxionline.com/forums/monk/70198-test-counter-data.html

**Comment by 59blargedy** [comment]
the actual issue of base counter rate being off was resolved in April 18, 2022 patch
