### ISSUE TITLE
Jailer of Faith and Jailer of Fortitude´s adds should have spellcasting on cooldown upon spawning

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4933]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Seems like Jailer of Faith and Jailer of Fortitude adds should not cast spells upon spawning.

Jailer of Faith never seems to cast spells upon being popped
https://www.youtube.com/watch?v=wlqEzT4T2ro&t=5s
https://www.youtube.com/watch?v=P9vyeiSPxi0
https://www.youtube.com/watch?v=E83puAkylFE
https://www.youtube.com/watch?v=uSrzICxia7g
https://www.youtube.com/watch?v=qRfvNq41iJ4
https://www.youtube.com/watch?v=1FYAdWaPJ6M
https://www.youtube.com/watch?v=1uLxgpAupXM&t=7s

Jailer of Fortitude adds never cast spells either
https://www.youtube.com/watch?v=Ok5Rcx5a4t8&t=29s
https://www.youtube.com/watch?v=IM75niQRpKs
https://www.youtube.com/watch?v=bDkhLTwnKmU
https://www.youtube.com/watch?v=1FYAdWaPJ6M (several forts here)

But for example I couldnt find a single hakutaku video where he didnt cast a spell at start so I would assume the two jailers are just built coded/differently than the spawnable mage mobs in general (?). Could not find a video that had a different spawn pattern from the ones listed above for Fortitude/Faith, they propably always have spellcasting on cd when spawned. 

Fortitude also seems to have a slight extra delay from popping untill engaging the player. Can be seen here https://www.youtube.com/watch?v=IM75niQRpKs and here https://www.youtube.com/watch?v=TKMl4-c2rT8

**Comment by E5una** [comment]
I could be wrong but all mobs seem to function this way on Eden in general (maybe some specific exceptions). 

Era videos of BCNMs like Wings of Fury don’t have the bats all casting in unison upon being aggrod, but that’s how it always works here.

Feel free to disregard this comment and focus on the jailers but I feel like it’s a system issue.

**Comment by Steam-arch** [comment]
Right. Atleast suzy and genbu seem to have differing patterns on retail and both can cast at the start or wait X seconds. Hakutaku seems to cast a spell every time (or havent seen one where he didnt yet). Maybe its better to just take the breakga threat from JoF or the diaga gangbang from fortitude rather than dable in this for now.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
