### ISSUE TITLE
Ooze in Beadeaux (Dodge Earring monster) have 5m Respawn instead of 10+ min

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4934]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Oozes in Beadeaux are respawning after 5 minutes but should be at least 10 minutes.

The earliest wiki page I can find with a respawn time listed is May 2009 where it says at the bottom of the chart: "Spawns every ten mins."

https://ffxiclopedia.fandom.com/wiki/Ooze?oldid=898303

Even modern Oozes have 10 minute repop time per the modern wiki

https://ffxiclopedia.fandom.com/wiki/Ooze

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
