### ISSUE TITLE
Receiving multiple RSE during RSE event

### ISSUE THREAD

**Issue by jasonm323** [EdenServer/community#4935]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

v. 30181205_0

Hello I recently did the RSE for Hume M in Maze of Shakhrami and received both the Hume M Rse Sachel and the Galka one from the Aroma Crawler.  I was the only person in the party.  I did not take a screen shot of the event.

**Comment by tarutarulord** [comment]
Hello I recently did the RSE for Taru M in Ordelle's Cave and received both the Hume M Rse Sachel and the Galka one from the Aroma Leech. I was the only person in the party in the zone at the time. I did take a screen shot of the event.
![wrong ammo](https://user-images.githubusercontent.com/82719341/158062487-68b1fe6b-b2fb-451f-920e-ece35692288d.JPG)

**Comment by KnowOne134** [comment]
has been corrected in a later update
