### ISSUE TITLE
RangeAttackEnabled mobs get stuck

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#4936]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Mobs that enabled to use range attacks as a normal weapon, not skill enabled range attacks ***

Such as the Talif Crew in The Ashu Talif that are thf/rng. With the ranged enabled the will get stuck if
1. Line of sight prevents
2. Out of range for the ranged attack

If this occurs they just stop attacking or doing anything at all but stand there until the condition is cleared. 

The binding needs a check for in range and if target can be seen.

**Comment by falzum** [comment]
This also happens with hydra ninjas in dynamis Beaucidine

**Comment by falzum** [comment]
Reopening this because it's definitely still happening in ashu talif and with hydra rangers and ninjas in dynamis

**Comment by statuseffect** [comment]
Happens in Aqueducts with the fomor RNG and NIN. The nin tries to cast ninjutsu while it's target out of range until the target is back in range.

**Comment by randomslumber** [comment]
> Happens in Aqueducts with the fomor RNG and NIN. The nin tries to cast ninjutsu while it's target out of range until the target is back in range.

For some reason with RNG I feel like I've been able to unstuck them by running into LOS to eat a RA and then breaking LOS and they'll pursue like normal

**Comment by Mozzy4Ever** [comment]
Yes they'll get unstuck once they're able to RA, but will get stuck again if they try to RA and can't due

**Comment by Dukilles** [comment]
resolved in July 5th, 2024 patch

**Comment by Snugglepunk** [comment]
Still happening in Dynamis Tav Hydra Rangers and Ninjas.
