### ISSUE TITLE
Nyzul: Bay Eye checks as T

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4938]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The Bat Eye encountered on floors 1-19 checks as T even though it drops a gold NM coffer. 

In the overworld the mob isn't an NM according to wiki. I assume the nyzul version should be though. 

https://ffxiclopedia.fandom.com/wiki/Bat_Eye?oldid=772552

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
