### ISSUE TITLE
2009 NM list + items

### ISSUE THREAD

**Issue by Nyoomy** [EdenServer/community#494]
https://docs.google.com/document/d/1NpwzAVUMKURPLes97cSXawCYaZFwHXl9uGbsAzMTvCk/edit?usp=sharing

Full list (Hopefully) of the NMs that were added in Wings of the Goddess, including their drops/what they craft.

Some NMs on this list might have already been removed from the server ofcourse, but that's everything. :D

**Comment by icariumkupo** [comment]
Lot of cool, working, simple content to remove just because it's not era. Sad.
