### ISSUE TITLE
Boreal Hound Poison Breath double damage

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4940]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

From what I can see in this 2008 video of a 55 WAR (with a high level WHM supporting them), Poison Breath seems to cap at 250 while Methane Breath caps at 400. On Eden Poison Breath is capping at 500 but Methane Breath is correctly capping at 400, so it seems like Poison Breath is the only one that needs an adjustment.

Admittedly I don't know a lot about Breath attack from monsters so someone can correct me here if I'm wrong, maybe the warrior just happened to half resist all casts in the video, but it seems unlikely.

Also from what I could tell from researching, the Shell from the WHM wouldn't affect breath attacks, but I know very little on the subject. Also worth noting he is /whm (he uses divine seal) so he has Magic Defense Bonus I, it appears this also doesn't affect breaths from what I've read, and also I reproduced this as 55MNK/WHM on the test server and still am taking full damage.

https://www.youtube.com/watch?v=tu3esi2rh7w

250 Poison Breath
![image](https://user-images.githubusercontent.com/13668758/156890452-a6b28251-1057-4dab-8b0a-6ad26293ab9a.png)

250 Poison Breath
![image](https://user-images.githubusercontent.com/13668758/156890497-f1fd461a-a02a-4bcb-b9a9-5e94eab32eba.png)

400 Methane Breath (matches Eden)
![image](https://user-images.githubusercontent.com/13668758/156890523-4cd39ae4-a8e4-4dff-985c-aa7e5592e764.png)

400 Methane Breath (matches Eden)
![image](https://user-images.githubusercontent.com/13668758/156890603-55f9a9ef-1047-4d68-9b8c-0679887b2b35.png)

400 Methane Breath (matches Eden)
![image](https://user-images.githubusercontent.com/13668758/156890628-479b060a-b104-4d70-947d-06f7c2670185.png)

400 Methane Breath (matches Eden)
![image](https://user-images.githubusercontent.com/13668758/156890644-983fbda5-155a-4650-b101-b7487d142f9f.png)

217 Poison Breath (You can see that its health is low, so presumably this is no longer hitting the cap)
![image](https://user-images.githubusercontent.com/13668758/156890678-03210205-b949-4f93-8aed-9aedd2fbcb2d.png)

116 Methane as it is almost dead
![image](https://user-images.githubusercontent.com/13668758/156890706-93b71286-5fd0-4292-b19d-a60fa3299115.png)

On Eden
![image](https://user-images.githubusercontent.com/13668758/156890728-42893470-78dc-4f96-8259-db2c79734cfd.png)

![image](https://user-images.githubusercontent.com/13668758/156890750-b0a535f1-1e32-45f4-b476-a1b2292b3a14.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
