### ISSUE TITLE
Empress Band not tuned to cutoff date announced.

### ISSUE THREAD

**Issue by PrymalNights** [EdenServer/community#4942]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

VER: 30181205_0

According to ffxiclopedia's history before and after the announced Eden cutoff date that the Empress Band charges should be 15 cooldown, not 16 hours that is currently marketed. See below for screenshots and links to each page.

https://ffxiclopedia.fandom.com/wiki/Empress_Band?diff=688796&oldid=618511
https://ffxiclopedia.fandom.com/wiki/Empress_Band?diff=618511&oldid=578517 

![image](https://user-images.githubusercontent.com/70297289/156910977-50828a05-de50-4d50-a9ec-ce6eb3fac7f3.png)
![image](https://user-images.githubusercontent.com/70297289/156910990-695c5d80-57ae-4abe-a9c3-c72695af7fe1.png)

**Comment by Mozzy4Ever** [comment]
![image](https://user-images.githubusercontent.com/11255886/156911093-ffa6399f-de62-4e2a-aac3-8efb6fe6e79e.png)

The image is pulling current retail picture.

**Comment by PrymalNights** [comment]
> 
Can you confirm the date that's shown? I see no date, unlike mine.

**Comment by PrymalNights** [comment]
And that update it March 18, 2014... Cutoff date for the Sever is SEP 2008
