### ISSUE TITLE
Adventure Fellow NPC not pushing past 50 level cap

### ISSUE THREAD

**Issue by Azmatic1** [EdenServer/community#4943]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I reported a prior issue with the "Picture Perfect" quest not progressing when taking the route involving Umberto. However, the alternate route through the windy NPC does allow for completion of the quest. The follow up to this is now my adventuring fellow does not level pass 50 although I have completed the level cap quest and also have an alt with all 'LB" quests completed that reached the 65 cap before I restarted. I've killed over 80 colibri to ensure that I reached the requisite mob count and nothing happens. Also, there is no dialogue indication anymore with the NPC that hints on when they should be leveling.

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
