### ISSUE TITLE
Tigers should not link.

### ISSUE THREAD

**Issue by PfistoFFXI** [EdenServer/community#4944]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
version 30181205_0
Tigers should not link aside from pets to their masters, all tigers link to eachother.

Steps to reproduce: Make a tiger aggressive, walk it in front of another tiger for the sight link.
https://ffxiclopedia.fandom.com/wiki/Forest_Tiger
https://ffxiclopedia.fandom.com/wiki/Sabertooth_Tiger
https://ffxiclopedia.fandom.com/wiki/Wajaom_Tiger
I assume this is a widespread problem across the Tiger family, but the three above I've tested and found them all to link.

**Comment by PfistoFFXI** [comment]
Earlier posts the monster, realized I had the modern wiki pages in the initial issue. https://ffxiclopedia.fandom.com/wiki/Forest_Tiger?oldid=44693
https://ffxiclopedia.fandom.com/wiki/Sabertooth_Tiger?oldid=236114
https://ffxiclopedia.fandom.com/wiki/Wajaom_Tiger?oldid=139944
It should be noted. The Sabertooth Tigers in Sauromugue Champaign are supposed to link and do.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
