### ISSUE TITLE
Mammet-22 Zeta Sleep-Lullaby Immunity

### ISSUE THREAD

**Issue by PfistoFFXI** [EdenServer/community#4946]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
version 30181205_0
Mammet-22 Zeta are immune to sleep/lullaby, they should not be.

Reproducible Steps: Enter "One to be feared" Battlefield. Attempt to sleep/lullaby. Fail with "Completely Resists" aka immunity.

Link to 2007 wiki page:
https://ffxiclopedia.fandom.com/wiki/Mammet-22_Zeta?oldid=207067
It mentions resistance, not immunity.

**Comment by E5una** [comment]
For what it’s worth, the family page for mammets has the Resist Sleep trait listed for them. I can’t speak to original CoP difficulty but at least wanted to point out the trait.

**Comment by PfistoFFXI** [comment]
They are supposed to have resist sleep and it be semi difficult to land (Ele Seal was encouraged) but not flat immune, while it's not the biggest thing, it's weird to me how it pushes groups to use certain compositions and devaluing BLM a lot for the majority of COP.

**Comment by 59blargedy** [comment]
wiki often mentions things are resistant instead of immune as players received the same messaging in era for a resist as for a complete immunity (something we should fix on eden at some point). 
retail capture of at least these particular mammets shows full dark and light sleep immunity, so that's why they were coded that way. where is there mention of "ele seal encouraged"? can you point out that forum post/vid?

**Comment by PfistoFFXI** [comment]
That's my bad, I wrote that comment thinking about the other ticket about contemplator not sleeping in https://github.com/EdenServer/community/issues/4945
in reference to https://www.bluegartr.com/threads/71974-Pulling-the-Plug

No you're 100% right for this after looking into it more. Can close.

**Comment by 59blargedy** [comment]
no worries, thank you!
