### ISSUE TITLE
Satiator only has one spawn location implemented + Wrong respawn time

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4949]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Supposed to spawn on both islands on the 3rd floor in Promyvion-Dem. On eden it only spawns in one location, G-12. Also has a static  respawn time on eden (if I remember correctly its 4h). 

Some 2nd spawn points notes:
![image](https://user-images.githubusercontent.com/69089249/157715309-65ad8390-1d34-492a-97c2-51a78da68fcc.png)
bg-wiki
![image](https://user-images.githubusercontent.com/69089249/157701020-6daa629d-14f1-41e5-8929-c2ebed32a4c0.png)
https://ffxiclopedia.fandom.com/wiki/Satiator
![image](https://user-images.githubusercontent.com/69089249/157714763-fdcdb924-48b2-4bb5-b52e-f71829ba7064.png)
![image](https://user-images.githubusercontent.com/69089249/157714858-b4959e19-57b8-4c75-b8b8-d169ebd28d83.png)
https://ffxiclopedia.fandom.com/wiki/Talk:Satiator

2nd spawn location can be somewhat seen here I think: https://www.youtube.com/watch?v=BQnCRV3i8Qs
Not sure of the exact position though, but it looks very similar to the G-11 spot.

Coveter and Cerebrator also can spawn on the other Islands, and I think they might be coded similarly to one location on eden. Will do a bug report for these if needed when dia wand/Hamayumi is released:

![image](https://user-images.githubusercontent.com/69089249/157717710-7fb7c4ec-d293-4066-ba08-b91b5ef8444b.png)
![image](https://user-images.githubusercontent.com/69089249/157717780-96694e48-23a0-4c53-b93d-0786a1540f15.png)

Some spawn time notes on Satiator:
![image](https://user-images.githubusercontent.com/69089249/157715012-2446ae18-e09b-4750-8cac-1e070bf03b3c.png)
https://ffxiclopedia.fandom.com/wiki/Satiator
![image](https://user-images.githubusercontent.com/69089249/157715159-1c8ca053-9477-44e7-9089-397c821fb8d4.png)
https://ffxiclopedia.fandom.com/wiki/Talk:Satiator
![image](https://user-images.githubusercontent.com/69089249/157717096-0271e6f9-97e5-48b6-b4dd-526becf2410b.png)

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
