### ISSUE TITLE
LB2 mobs respawn too quickly

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4950]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Currently on Eden the Boreal mobs for LB2 respawn about 15 seconds after previous despawn.  With the era date change, https://ffxiclopedia.fandom.com/wiki/Boreal_Hound?direction=next&oldid=333853 has them respawning 5 minutes after previous despawn. I can't find a specific patch note mentioning this time change. Closest I can see that mentions LB2 is August 28th, 2007 (http://www.playonline.com/pcd/update/ff11us/20071120wwnX41/detail.html). This is also where the respawn change is filed under on the JP Wiki (http://wiki.ffo.jp/html/7.html).

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
