### ISSUE TITLE
Charmed players should have a movement speed penalty

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4951]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

https://ffxiclopedia.fandom.com/wiki/Charm_(Status_Effect)?direction=prev&oldid=343027

According to wiki dating back all the way to 2007 charmed players should have a movement speed penalty. Would need retail testing to verify the proper amount I suppose but I'll see if I can find a dyna sandy video or something for reference

**Comment by Steam-arch** [comment]
https://www.youtube.com/watch?v=6UjCRFfNZxU

not sure how good that is

**Comment by Steam-arch** [comment]
https://www.youtube.com/watch?v=0MQtbXsvLyU

**Comment by 59blargedy** [comment]
we already have this ticket from you, so gonna close
