### ISSUE TITLE
Brothers ENM - Incorrect Spells

### ISSUE THREAD

**Issue by MalteseFalcon** [EdenServer/community#4953]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver 30181205_0

Mindertaur and Eldertaur have access to incorrect spells in the Brothers ENM.

Eldertaur: should only have Shell 3, not Shell 4

![image](https://user-images.githubusercontent.com/33695616/158031334-5cdc8181-00f2-4768-bbd0-476eaf82448b.png)
 
BG Wiki:
![image](https://user-images.githubusercontent.com/33695616/158031358-57e0e3e7-531e-4fb8-bd11-c8fa9c1d9108.png)
Wiki:
![image](https://user-images.githubusercontent.com/33695616/158031365-4cda9f5a-b6b4-4856-a84b-f149a743aff5.png)

Mindertaur: shouldn't have access to Shell (Eldertaur did not cast it him)

![image](https://user-images.githubusercontent.com/33695616/158031402-366f97f7-b896-42aa-bc77-341c23b8c22b.png)

BG Wiki:
![image](https://user-images.githubusercontent.com/33695616/158031471-7838b20b-e91b-4a20-bfa5-da35a7437bd8.png)
Wiki:
![image](https://user-images.githubusercontent.com/33695616/158031476-1f75e269-2177-4082-85aa-b75d0aa702e7.png)

Extended log showing Eldertaur did not cast Shell on Mindertaur (Shell dispelled at 13:57:18 as noted above). Must have self casted while beyond 30 yalms.

![image](https://user-images.githubusercontent.com/33695616/158031557-aba7f134-b85c-460d-a699-58ac653dcde9.png)

**Comment by 59blargedy** [comment]
can confirm elder casts shell iv on retail from a capture i did
![image](https://user-images.githubusercontent.com/52636208/158032003-eb4d4cca-fc8e-4895-bc61-77609b4afc0a.png)
did the spell's level ever change, maybe? could have affected.
will look or get another capture to validate min's spells

**Comment by Steam-arch** [comment]
Monsters are programmed to cast the highest shell available?

https://www.youtube.com/watch?v=FSc2LNk2btQ&t=333s
1:22 shell III and other era videos have shell IIIs aswell

**Comment by 59blargedy** [comment]
looks like the mindertaur, not the eldertaur. makes sense for the minder to have shell 3.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch downgraded the shells to shell3, but both mobs did indeed have them
