### ISSUE TITLE
Bait and Switch

### ISSUE THREAD

**Issue by kelsmilr** [EdenServer/community#4954]
### Checklist

On the Bait and Switch quest, the R/Ex item Key Ring Belt, the quest will show complete without giving the item if you currently have it in your inventory or a full inventory. This prevents you from repeating the quest or getting the item for that week.

Proof: see conversation w/ GM Luminous
-Kmillenium
/ver 30181205_0

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
was your case having the key ring belt in your inventory already? doesnt look like a normal full inventory would trigger this issue, so wanted to understand your exact situation.

**Comment by kelsmilr** [comment]
Yes, I had the Key Ring Belt already in my inventory. When GM_Luminous tried it, he also found that a full inventory would also cause the quest to complete without giving you the item.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
