### ISSUE TITLE
Dynamis Mob Levels

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#4955]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
ver 30181205_0
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Normal Beastmen (Sandy/Basty/Windy/Jeuno/Glacier)
Level 75-77
the 90-92 ones are OOE

Normal Beastmen Pets
Level 75
level 80 ones are OOE

NMs (Sandy/Basty/Windy)
Level 81-85

NMs (Jeuno)
Unknown, needs retail capture. Likely lower level than the other zones due to higher number.

NMs (Glacier)
Unknown, 80-81 on capture but tiny number. Possibly also 81-85? Goblin NMs likely lower level than the other beastmen.

Attestation NMs
unknown

Tombstones (Sandy/Basty/Windy/Jeuno/Xarcabard)
Level 65
level 80 ones are OOE

Tombstones (Glacier)
Level 70

Eyes (Glacier/Xarc)
Level 70
level 82 & 85 ones are OOE

Hydra
Level 80-82
level 92-95 ones are OOE

Hydra Pets
Level 80
level 92 ones are OOE

AngraMainyu (Glacier Boss)
Level 85
4 Dragons Level 82 (Fire/Poison/Wind/Petro Pukis)

Kindred
Level 77-80
The 93-95 ones are OOE

Kindred Pets
Level 77
level 93 ones are OOE

Animated Weapons
Level 82

Qufim/Buburimu/Valk
Vanguard = 75-77
Nightmare = 78-80
Tombstones = 70
NMs = 85

Tav
Nightmare = 78-80
Hydra = 77-80
Eyes = 82
Boss = 85

[Dynamis - Bastok.log](https://github.com/EdenServer/community/files/8281303/Dynamis.-.Bastok.log)
[Dynamis - Beaucedine.log](https://github.com/EdenServer/community/files/8281305/Dynamis.-.Beaucedine.log)
[Dynamis - Beaucedine2.log](https://github.com/EdenServer/community/files/8281306/Dynamis.-.Beaucedine2.log)
[Dynamis - San d'Oria.log](https://github.com/EdenServer/community/files/8281307/Dynamis.-.San.d.Oria.log)
[Dynamis - Windurst.log](https://github.com/EdenServer/community/files/8281308/Dynamis.-.Windurst.log)
[Dynamis - Xarcabard.log](https://github.com/EdenServer/community/files/8281309/Dynamis.-.Xarcabard.log)
[Xarc Weapons 2.log](https://github.com/EdenServer/community/files/8281310/Xarc.Weapons.2.log)
[Xarc Weapons.log](https://github.com/EdenServer/com
[Dynamis - Qufim.log](https://github.com/EdenServer/community/files/8558193/Dynamis.-.Qufim.log)
[Dynamis - Tavnazia.log](https://github.com/EdenServer/community/files/8558194/Dynamis.-.Tavnazia.log)
[Dynamis - Valkurm.log](https://github.com/EdenServer/community/files/8558196/Dynamis.-.Valkurm.log)
[Dynamis - Buburimu.log](https://github.com/EdenServer/community/files/8558197/Dynamis.-.Buburimu.log)
munity/files/8281311/Xarc.Weapons.log)

**Comment by KnowOne134** [comment]
What's the source of this info? Given in retail they gave no xp and you couldn't widescan the levels with packets and all mobs checked as impossible to guage?

**Comment by Slamm21** [comment]
Captures from Retail.
We ideally do need one from jeuno too.

While Dynamis did change, they kept the old mobs and just added newer higher level versions as well. The chances that they lowered mob levels in Dynamis when they raised the cap from 75-99 is basically zero.  Mob stats all follow family so damage dealt/taken would be fine, but HP should be higher than it currently is (If Eden follows DSP/Topaz/LSB) 
For example every normal Orc/Quadav/Yag in dynamis seems to have 4k hp, and I have a capture showing a whm yag had a bit over 5k
17543173 (Vanguard Priest): 5048~5159HP, Est.HP: 5097 (Mthd: I)
needs more data for the hp side really.

**Comment by KnowOne134** [comment]
I'm wondering though when they changed it to once a day and triggers and solvable there WAS a huge overhaul to the system including removing and placement of mobs and that only we we can achieve the old way is by faking most if it with renamer

**Comment by ccl085** [comment]
Might explain #4438 Dynamis mob in city do more damage with EES on eden than retail (specially in city)

**Comment by ccl085** [comment]
ffxi.allakhazam.com has 2007 page with dynamis mob level matching current retail capture -> https://ffxi.allakhazam.com/db/bestiary.html?fmarea=131
and
https://ffxi.allakhazam.com/db/bestiary.html?fmob=1792
-> "This page last modified 2007-09-25 13:50:41."

**Comment by Slamm21** [comment]
on the alla page if that level range was created OOE it would have said about the mobs level 90+ also and it doesn't.
So 75-77 must be correct.

**Comment by Slamm21** [comment]
Makise found a screenshot, the damage aligns with the data above

https://i34.photobucket.com/albums/d138/a5speedromance/img_20091014_222051.jpg
![image](https://user-images.githubusercontent.com/5552081/162883315-f8166645-3d55-4cff-aee0-18f80359bbab.png)
Date on the screenshot shows 14th October 2009
https://www.ffxiah.com/player/Fenrir/Valkyris#equip
shows he didn’t get Bravura until 22nd December 2009
equip history shows hume female also and links to a set for KJ
https://www.ffxiah.com/item-sets/115404

Swapping out the great axe for perdu (96 damage during ws)
finding base stat for hume WAR/SAM
https://github.com/EdenServer/community/issues/2975
https://w.atwiki.jp/studiogobli/pages/27.html
D for Hume
A for War
C for Sam
=72 STR (30+25+9+5+3) see my bug report for details

11+4+10+11+5+5+4+5+10+7 STR in gear = 72 additional STR
+5 for hasso
=149 STR

Weapon Skill Damage = ( D + fSTR + WSC) * fTP * PDIF

D = 96
FSTR max = weapon rank +8. Weapon rank is based off the non latent weapon damage so =(91/9)=10+8=18
WSC = 149*0.5 = 74* alpha (0.83) = 61

Weapon Skill Damage = ( 96 + 18 + 61) * fTP * PDIF
Weapon Skill Damage = ( 175) * fTP * PDIF
ftp is increased to 1.1 for the first hit with the gorget, remains at 1 for all remaining hits
PDIFmax is cratiox1.2

ratio caps at 2.25 for 2h
vanguard mesmerizer caps at level 77 so we minus 0.05*2 so minus 0.1
cratio is 2.15
pdifmax = 2.58

First Hit = ( 175) * 1.1 * 2.58 = 192*2.58 =495
Other Hits = ( 175) * 1 * 2.58 =451

5 hit KJ (max hits) = 2,299

if the mob was level 79
cratio is 2.05
pdifmax = 2.46

First Hit = ( 175) * 1.1 * 2.46 = 192*2.46 =472
Other Hits = ( 175) * 1 * 2.46 = 430
5 hit KJ (max hits) = 2,192

therefore this era dynamis mob could not have possibly been level 79 or higher
it is also very unlikely to be level 78, as to make these numbers all the stars have to align.

pdifmin is -0.8 + 1.2 * cratio which in the level 77 example would be 1.78 so the damage would vary between 1,585 and 2,299 for a 5 hit IF you capped ratio and FSTR

his total attack was 627
base is 8
combat skill (assuming max merit) = 292, so 282 attack
from str 111
in gear is +12+25+15+5 = 57
total before berserk and food = 458
from berserk = 114 (25%)
from pizza+1 =55

that caps ratio if the mob has 278 defence or lower, it's not much attack.

**Comment by Falaras** [comment]
Some things worth noting with all the assumptions: 

That character's first scan was 2009-11-28 and included an Abaddon Killer, so very probable that was done with a D:99 Gaxe.

We can't really make any gear assumptions based on an FFXIAH set called "Perfect KJ", also if using scan dates that character didn't actually own some of the gear used in that FFXIAH set in October when that picture was taken. In fact we don't know what they owned since the first scan was in December. 

The total STR total could have been much higher. Hume war/sam base total could be 77 STR with capped STR merits, we don't know what food that is so could be an extra +5/6, they didn't own Shadow Breastplate at that time according to the scan dates so that could be something like Hecatomb for +12 STR. Assuming all that we are now talking about STR+77+6+5+74 for 162 STR not 149 STR. 

Savagery could definitely be up adding a 500 TP bonus to the WS, meaning the FTP assumption of 1.1 could be almost double that FTP.

I'm sure there's more intangibles I didn't think of really, Mathing out a mobs level based on a screenshot from 13 years ago seems pretty much impossible to me unless we have some pretty wildly exact parameters.

**Comment by ccl085** [comment]
Buff are mentionned here, https://www.bluegartr.com/threads/72117-Fapworthy-WS-SC-or-MB-damage-III-I-critted-both-hits?p=3158470&viewfull=1#post3158470
Unlikely to have Warcry since only Zerk/Aggressor are mentionned.

Also this is the same character: https://www.ffxiah.com/player/Carbuncle/Valkyris#equip Abandon killer is registered  2009 - 10 -31 so after the screenshot.

His buff/gear doesn't cap attack on Dynamis mob so assuming max pdif on every hit is unlikely too.

There are also screenshot of  HP being at least 4700 wich is close/match current retail HP.

**Comment by Slamm21** [comment]
We did forget STR merit, we know food was pizza+1 and we did include hasso
this means wsc would be 154 x 0.5 =77 x0.83 =63, an increase of 2

for level 77 mob
First Hit = ( 177) x 1.1 x 2.58 = 194x2.58 =500
Other Hits = ( 177) x 1 x 2.58 =456

5 hit KJ (max hits) = 2,324

a level 79 would be
First Hit = ( 177) x 1.1 x 2.46 = 194x2.46 =477
Other Hits = ( 177) x 1 x 2.46 =435
5 hits = 2,217

we also can see his buffs and know they were berserk+aggressor so no savagery. If he did not have some of the gear he would be even more likely to not cap ratio (he is unlikely to already with only 640 attack including food and berserk)

Note that even if he did, the chance to get a pure pdmax is 1/100 as it randoms between that and pdifmin
DA base is 10%, 5% for merit, 7% in gear, 22% total
0.0484 chance to DAx2, multiply by the chance to get a pure pdifmax = 0.000484
that is 1 in 2,066 IF he had capped ratio which is unlikely to begin with.

It's clear the original dynamis mobs are still in dynamis, along with the newer higher level ones

**Comment by Falaras** [comment]
Good to know there is some more info, although much of what I mentioned is still a big issue. Why are we assuming Pizza also?

**Comment by Slamm21** [comment]
https://www.bluegartr.com/threads/82751-Post-Pictures-of-Your-Gear-IX-The-Starr-and-Omnipotent-love-thread?p=3278760&viewfull=1#post3278760
says pizza

note the gear he has at this point, he mentions he has "new shit" yet has the relic legs instead of the str+10 ones and triumph vs vampire earring so 7 str less.
this is also a month after he did the ws. Also the less of the gear he has, the more it proves mob levels are low in dynamis.
like his gear shows, 77+65 str, +5 from hasso not shown = 147

WSC = 147x0.5 = 73x alpha (0.83) = 60
D = 99
FSTR max = weapon rank +8 = 11+8 = 19

for level 77 mob
First Hit = ( 178) x 1.1 x 2.58 = 195x2.58 =503
Other Hits = ( 178) x 1 x 2.58 =459
=2,339

a level 79 would be
First Hit = ( 178) x 1.1 x 2.46 = 195x2.46 =479
Other Hits = ( 178) x 1 x 2.46 =437
5 hits = 2,227

**Comment by Falaras** [comment]
I think the "for all we know" line sums it up best, we really just don't know. For example that picture shows AF2 legs as you point out, but FFXIAH says he had Hachiryu Haidate months before that. You can't make any assumption of Vampire Earring, that's not a fulltime piece, I don't even think you can assume he's using Pizza because in an unrelated post months later he mentions his accuracy numbers are before Pizza. We all switch food depending on the accuracy needs of the event. Especially if we are assuming level 77 Dynamis mobs he would be an idiot to use pizza, his sets cap acc on current Eden dynamis mobs, and I doubt someone that is parsing and understands acc as well as he seems to is just spamming pizza for no reason.

**Comment by Slamm21** [comment]
The ffxiah set never had a date on it, however we knew at that point he did not have bravura.
the bg post is him showing his actual gear and him saying he uses pizza. Here is another post saying he uses pizza
https://www.bluegartr.com/threads/82751-Post-Pictures-of-Your-Gear-IX-The-Starr-and-Omnipotent-love-thread?p=3283054&viewfull=1#post3283054

and even if he used red curry and a vampire earring, that extra 9 str total doesn't really change anything here. the numbers won't move much.

This ws number is so high it is literally impossible with current Eden mob levels, before we even begin to get into pdif.

level 81 colibri have 322 defence
82 has 327, so it lost 5 in 1 level
obviously it can't lose 5 every level as otherwise a level 1 bird would have minus 78 defence.
Of course Colibri are not orcs, but they are squishy and by using 5 per level instead of 4, it's assuming lower defence for the mob which gives more chance for them to be higher level.

yet a level 77 orc, based on colibri stat, would have 302 defence.

for level 77 mob with 302 defence, 616 attack (2.03 ratio)
cratio = 1.93
pdifmax = 2.31
First Hit = ( 178) x 1.1 x 2.31 = 195x2.31 =450
Other Hits = ( 178) x 1 x 2.31 =411
=2,094

so even with squishy colibri stat it's impossible for this mob to be level 77, it would have to be lower.

**Comment by Falaras** [comment]
That post specifically says he doesn't use Pizza lol

**Comment by Slamm21** [comment]
it really doesn't matter, any food he had it's still the same, red curry or not and he was saving for bravura at the time.
75-77 is correct as per the original post.

**Comment by ccl085** [comment]
Another thing that is weird about private server dynamis mob, while level is too high, HP is too low, most have city mob around 4k hp. But if you look at beastmen outside dynamis (and lower level) they have more than 4k HP.

Now if you go to retail dynamis, level 75 have around 4.8-5k hp.

This era screenshot 
![Mercy1428](https://user-images.githubusercontent.com/48790940/163094810-6d97ba1a-2f30-4080-ab2c-f27010db06c0.jpg)
show that mob have at least 4.6-4.7k in Dynamis wich seems to match what we can find in current retail.

**Comment by Slamm21** [comment]
Assuming this mob was 77
it's defence would be 298.5 (thanks Jimmayus)

(142+((77-50)*4.8) = 271 floored
It's job is BLM/WAR, so +10 from job trait
and 35 VIT/2 = 17.5
=298.5 defence

we have 616 attack (2.06 ratio)
cratio = 1.96
pdifmax = 2.35
First Hit = ( 178) x 1.1 x 2.35 = 195x2.35 =458
Other Hits = ( 178) x 1 x 2.35 =418
=2,130

if the mob was level 76
cratio = 2.01
pdifmax = 2.41
First Hit = ( 178) x 1.1 x 2.41 = 195x2.41 =469
Other Hits = ( 178) x 1 x 2.41 =428
=2,181

**This mob has to be level 75, otherwise the 2,206 is impossible**

**Comment by Slamm21** [comment]
updated the first post with COP dynamis data.
only things missing are now is attestation NMs, Jeuno, and Glacier NMs

**Comment by Slamm21** [comment]
missed the +8 base which is shown here to defence
https://w.atwiki.jp/studiogobli/pages/25.html

Assuming this mob was 77
it's defence would be 306.5

(142+((77-50)*4.8) = 271 floored
It's job is BLM/WAR, so +10 from job trait
and 35 VIT/2 = 17.5
+ 8 base
=306.5 defence

we have 616 attack (2.00 ratio)
cratio = 1.9
pdifmax = 2.28
First Hit = (178) x 1.1 x 2.28 = 195x2.28 =444
Other Hits = (178) x 1 x 2.28 =405
=2,064

if the mob was level 76
defence is now 301.5
ratio 2.04
cratio = 1.99
pdifmax = 2.38
First Hit = ( 178) x 1.1 x 2.38 = 195x2.38 =464
Other Hits = ( 178) x 1 x 2.38 =423
=2,156

**This mob has to be level 75 or below, otherwise the 2,206 is impossible**

**Comment by 59blargedy** [comment]
resolved by another dev in may 22, 2023 patch
