### ISSUE TITLE
BRD/BST. BST abilities work on Virelai-charmed pets

### ISSUE THREAD

**Issue by muneonna** [EdenServer/community#4956]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Client version 30181205_0

The details of Maiden's Virelai:

"Foes charmed by Virelai become passive pets, only taking actions when the caster is engaged in combat."

I was able to use fight, leave, and sic on Virelai-charmed pets, when BST was set as my subjob.

**Comment by muneonna** [comment]
https://ffxiclopedia.fandom.com/wiki/Maiden%27s_Virelai?oldid=63770

2006 comment on wiki... "It does not give the same amount of control over the mob as a Beastmaster's Charm does. Charmed enemy will attack anything that attacks the caster."

**Comment by muneonna** [comment]
Did I level bard on the production server just to test this? Yes. Yes I did.

I'm about to test if I can charm things I shouldnt be able to, and use Sic... But I get the feeling Virelai is programmed as a very short BST charm so I doubt it will work xD

**Comment by muneonna** [comment]
Thats a negative. Man, I was hoping I could charm a goblin and Sic it to use bomb toss.

**Comment by 59blargedy** [comment]
resolved by another dev in July 5th, 2024 patch
