### ISSUE TITLE
Bad Breath Poison damage is incorrect

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4958]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On eden its set to 7hp/tic. Should be just 1hp/tic from both VV and Cassie. No idea about the blue mage spell, but might be identical to the monster versions?

https://www.youtube.com/watch?v=KdGJr7f2Grw&t=1s
2:49 VV bad breath and can kind of see HPs dropping 1hp/tic

https://www.youtube.com/watch?v=U3SKhwhq_y0&t=435s
8:31 is Cassie bad breath, /whm regen countering it to 0hp/tic
https://www.youtube.com/watch?v=q-b4xEwiPxM
6:30 bad breath poison on for 1/tic

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
