### ISSUE TITLE
COR LB5 doesn't complete if you have warp scroll

### ISSUE THREAD

**Issue by Appotemmis** [EdenServer/community#4960]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

If you have a Warp Scroll or a full inventory wen completing the COR LB5 quest, the quest will not update your level cap to 75

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
