### ISSUE TITLE
Eraser should remove all maneuvers, not just light maneuvers

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4962]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

In the 12/14/2011 Update Eraser was changed to only consume Light Maneuvers. The era version should remove all maneuvers regardless of element. 

https://ffxiclopedia.fandom.com/wiki/Eraser?oldid=375560
https://www.bg-wiki.com/index.php?title=Eraser&oldid=28572

Current functionality on Eden can be seen by getting a status ailment and having a light maneuver and a non-light maneuver active. Only the light maneuver will be removed, when it should be all maneuvers.

version 30181205_0

**Comment by Norrissnake** [comment]
id like to add that the auto uses eraser on the master after it has used a spell to remove said debuff.  let me know if this should be its own ticket

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch. the conflict with erase and -na sounds like the queued abilities bug, present on another report
