### ISSUE TITLE
Damage Gauge has OOE healing cooldown reduction

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4963]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Damage gauge appears to have its December 2011 shorted recast effect. In era Damage gauge did not have any effect on healing spell global cooldowns.

Picture from Dec 2011 Patch Notes

![image](https://user-images.githubusercontent.com/13668758/159596703-4ec531f2-3c52-4e69-9d06-a7a6d84fce0f.png)

Era Damage Gauge: 
https://ffxiclopedia.fandom.com/wiki/Damage_Gauge?oldid=597833

Modern Damage Gauge:
https://ffxiclopedia.fandom.com/wiki/Damage_Gauge

Right now it looks like this is what Damage gauge appears to be doing on Topaz, and I was able to validate at least the presence of the code on the test server, but didn't test all the specifics because it seemed like overkill.

Light Maneuvers  / Healing Cooldown Reduction
0 / 3 seconds
1 / 3 more seconds (6 total)
2 / 2 more seconds (8 total)
3 / 2 more seconds (10 total)

Here is some validation that I did to show that it is in effect.

This screenshot is an automaton with 0 attachments and 0 maneuvers being deployed when I have 1 health, retrieved so that it doesn't cast an enfeeble and delay its next cast, and then deployed again just before the 15 second mark. Note that it Opts to use slow because its healing cooldown is rightfully on cooldown.

![Just under 15 seconds, it used Slow instead of another Cure](https://user-images.githubusercontent.com/13668758/159597164-36e272e4-2881-421d-919d-d0c5be02938f.JPG)

In this screenshot, I have a Damage Gauge on and add 3 light maneuvers, to take 10 seconds off the healing spell cooldown. It should be able to cure as soon as 5 seconds with this with the OOE damage gauge.  Note that this time, the deploys were still less than 15 seconds apart, but it opted to Cure IV (its Cure V was still on cooldown). This shows the OOE Damage Gauage is in effect.

![DamageGauge](https://user-images.githubusercontent.com/13668758/159597365-8e1c9b97-fd27-46eb-9ffa-fedc169d4bbb.JPG)

Correct behavior would be for Damage Gauge not to modify the healing spell recast at all.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
