### ISSUE TITLE
Soil Gear Desynthesis recipes missing

### ISSUE THREAD

**Issue by Lokey1979** [EdenServer/community#4964]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

LVL 29 Soil Gear Desynthesis not working for most pieces

**Comment by 59blargedy** [comment]
please help us out and list the specific pieces you cant desynth, provide a link to the set at least, and change the title to something that's specific to your issue like unable to desynth soil ____, ____ and ____.

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
