### ISSUE TITLE
Gem Heister Roorooroon occasionally doesn't run around

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4965]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

Gem Heister Roorooroon doesn't run around his area dropping bombs. He will instead just spam (and boy I do mean spam.. Mine Blast every 4-5 seconds at times ; ;) Qiqirn Mines while standing still.

**Comment by Slamm21** [comment]
He also seems to drop bombs when asleep.

**Comment by KnowOne134** [comment]
Corrected 6/11/2022 update
