### ISSUE TITLE
Blue magic self-Destruct wrong formula/scaling

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4966]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently blue spell self-destruct scales with INT & Mabb & Vulcans staff. Supposedly nothing is supposed to affect it aside user HP determines max damage.

Fully decked (all int spells set & int food &  int and mab gear & memento mori & burst affinity & enervation & sound blast) self-destruct on eden with ~850 hp:
![image](https://user-images.githubusercontent.com/69089249/161346731-e9f8798d-3584-4106-949f-41e2545333ee.png)

clopedia & bluegartr Wiki notes:

![image](https://user-images.githubusercontent.com/69089249/161346388-e2f6a2cd-19d1-4d53-9092-895da81a12ef.png)
![image](https://user-images.githubusercontent.com/69089249/161346552-1ac6dc62-5f5b-460b-96d6-b23b6700677b.png)
![image](https://user-images.githubusercontent.com/69089249/161346580-7ee01f91-a337-43d9-b6fc-f69cbb594cf5.png)

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
