### ISSUE TITLE
NM Pelican missing sleep immunity & wrong HP value

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4968]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Should most likely be immune to sleep
![image](https://user-images.githubusercontent.com/69089249/161862288-b46cad53-d7e9-4ed3-905c-23425a6d41ae.png)
![image](https://user-images.githubusercontent.com/69089249/161864552-b06816d2-b9aa-42df-9599-2137922c2240.png)

![image](https://user-images.githubusercontent.com/69089249/161862303-9c737cf0-f5b9-44f1-818c-a43ff58f9316.png)
clopedia wiki

-------------
Also seems to have over double the HP its supposed to. 800dmg gekko was doing 2/3% so Assuming it has around 35k hp on eden.

https://www.youtube.com/watch?v=-E3M1TUOmBs
4:75 651 damage blizzard III brings it from 37% > 33/32%

https://www.youtube.com/watch?v=JWsjLHYA1Vg
5:25 chainspell blizzard III is used and 650 takes out 4/5% hp every nuke so Assuming its HP is between 15-16,5k

------------------

Wikis also point out it also procs enmity reset whenever the petri from autos proc, but couldnt find a video to confirm, Isnt implemented on eden.
![image](https://user-images.githubusercontent.com/69089249/161863625-892307a9-d99f-482e-89eb-922588a8ef35.png)
![image](https://user-images.githubusercontent.com/69089249/161863639-31b509e4-a3a4-4a58-b239-b09b1b4d8c4d.png)
clopedia wiki & allakhazam

----------
Might also hit slightly too soft (89-140) to 322 def SAM, but can not confirm
![image](https://user-images.githubusercontent.com/69089249/161864080-c86c76e4-d6b0-4a47-bbfb-4fcb836882f3.png)
![image](https://user-images.githubusercontent.com/69089249/161864095-1ba2231b-5c3c-40f2-b6e2-6a4bc29a2f92.png)

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
