### ISSUE TITLE
Item Bug: Senior Gold Musketeer's Scimitar DEF is missing

### ISSUE THREAD

**Issue by DwinJohnsel** [EdenServer/community#4970]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
client version: 30181205_0

The item (sword) Senior Gold Musketeer's Scimitar is supposed to give +10 DEF to Citizens of Bastok but when I equip it and remove it my DEF does not change. I am a citizen of bastok and always have been on Eden, currently Rank 9. Screenshots attached.

![1_no_weapon_equipped_268_DEF](https://user-images.githubusercontent.com/100724168/162102040-96f1b7c8-ea6e-4c7a-9587-12db68f2a821.png)
![2_sword_equipped_still_268_DEF](https://user-images.githubusercontent.com/100724168/162102079-ddc6f94c-3bbb-42b5-a553-c54a97b0531b.png)
![3_I_am_citizen_of_bastok_(shows_eden_version_too)](https://user-images.githubusercontent.com/100724168/162102220-dfa15bc9-315b-4a7e-bc89-5065b3a422d3.png)

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
