### ISSUE TITLE
Spell Slow overwrites Haste

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4972]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently slow1 will overwrite haste. Spellwise, only Slow2 should overwrite haste

![image](https://user-images.githubusercontent.com/69089249/162419614-4e5bc976-0052-4760-926c-58bcc25cb2e6.png)
![image](https://user-images.githubusercontent.com/69089249/162419862-4edcc68f-e2c6-4e60-a515-5f7b8620a562.png)

Talked to Juul about this and dev team seems to be aware that slow (ability inflected atleast) & haste interactions have some gimmicks here. But reporting this incase its an easier fix than an total overhaul of the system.

**Comment by KnowOne134** [comment]
closing issue for 1 big issue of, reference this issue in it
