### ISSUE TITLE
Zvahl Chest Key dropping from incorrect mobs

### ISSUE THREAD

**Issue by Appotemmis** [EdenServer/community#4975]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
30181205_0

Zvahl Chest Key dropping from incorrect mobs in Zvahl Baileys. Should only drop from the ones where their name starts with "Demon" (so "Demon Knight", not "Doom Demon". Currently drops from both.

**Comment by 59blargedy** [comment]
it isn;t coded to drop from doom demons. do you have a screenshot that shows what incorrect mob it dropped from? otherwise it's a bit difficult to root out the issue, since it's not the mob mentioned here.

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
