### ISSUE TITLE
Drum Magazine Spelling Error: "Increass" instead of "Increases"

### ISSUE THREAD

**Issue by joeedmo** [EdenServer/community#4976]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
![drum_magazine_image](https://user-images.githubusercontent.com/20552984/162828482-250df6c0-0bb5-4111-b67d-e03af09cb49d.PNG)

**Comment by KnowOne134** [comment]
Ha, that's funny. That error report would have to goto square as they made that one

**Comment by Mildew-Von-Eden** [comment]
Was it spelled correctly in era?

**Comment by KnowOne134** [comment]
Doesn't matter. It's the games dat and apparently se screwed up
