### ISSUE TITLE
CoP 8-3 Spinning Zdei

### ISSUE THREAD

**Issue by Appotemmis** [EdenServer/community#4977]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

30181205_0

CoP 8-3 When Angels Fall: 
In the part of the mission where you have to kill the 4 pots to get to the elevator, the spinning Zdei have too wide of sight aggro making sacking the room impossible. They will aggro you at the other end of the room. https://youtu.be/mShK0bDCMbk?t=3142 shows that they shouldn't.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
