### ISSUE TITLE
Sleep is removed by rest tics

### ISSUE THREAD

**Issue by Strumerjohn** [EdenServer/community#498]
Sleep is removed by rest tics. Not true on retail (or Nas)

**Comment by godmode** [comment]
@jmcmorris didn't we patch this?

**Comment by jmcmorris** [comment]
Yeah, this was patched but I think I see what I messed up after testing it. I will patch it. @Strumerjohn Thanks for reporting!

**Comment by godmode** [comment]
I'm closing this ticket. Please comment if this is still happening.
