### ISSUE TITLE
Nyzul Isle -Pathos effects missing 

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4980]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Beneficial and Detrimental pathos effects seem to be missing currently.
![image](https://user-images.githubusercontent.com/69089249/163470470-9329f756-4114-45da-a9a6-2ebd89b525df.png)

https://www.youtube.com/watch?v=tsMWQir62us
6:22 they recieve the effect of flurry
![image](https://user-images.githubusercontent.com/69089249/163470583-552ea31c-c888-405e-a945-51dbba865ec0.png)

**Comment by 59blargedy** [comment]
both positive and negative effects are coded and have been experienced on live.

**Comment by Steam-arch** [comment]
Alright. Possibly I have missed this completely then, is the chat message also in game? Or am I just completely blind
![image](https://user-images.githubusercontent.com/69089249/163472154-d659934d-d66f-402d-bf82-4c8de343da6f.png)

**Comment by 59blargedy** [comment]
yes, the message displays. personally experienced flurry and stat boosts. it's fine to believe they may need to occur more often, but they definitely exist.

**Comment by Steam-arch** [comment]
Gotcha, thx.
