### ISSUE TITLE
No Chalaimbille listed on NPC in Cooking Vendors

### ISSUE THREAD

**Issue by Magnum1965** [EdenServer/community#4982]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

After the update, no [Chalaimbille](https://ffxiclopedia.fandom.com/wiki/Chalaimbille) are listed on the cooking ingredient vendors, which is an ingredient in making Pizza's

**Comment by bliven-was-taken** [comment]
https://ffxiclopedia.fandom.com/wiki/Chalaimbille?oldid=600676

**Comment by 59blargedy** [comment]
resolved in april 18, 2022 mini-update
