### ISSUE TITLE
In Beloved of the Atlantes, Guard Hippogryph doesn't despawn when Watch Hippogryph dies

### ISSUE THREAD

**Issue by Goutan** [EdenServer/community#4986]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version: 30181205_0

After killing the Watch Hippogryph, the Guard Hippogryph didn't despawn. In our run, we died after killing the second Guard spawned (the first Guard was already dead).

After a full wipe, we reraised and started over. We killed the Guard, then the next one didnt spawn until 25%.  The Watch died before the Guard but didn't end the encounter. The fight ended after we killed the Guard.

According to the wiki page at: https://ffxiclopedia.fandom.com/wiki/Beloved_of_the_Atlantes

"Only the Watch Hippogryph must be defeated to win the ENM."

**Comment by 59blargedy** [comment]
resolved in April 19, 2022 update
