### ISSUE TITLE
Nyzul Isle Prefferd items not working correctly

### ISSUE THREAD

**Issue by Norrissnake** [EdenServer/community#4987]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
the temp item box won't dispense all of your preferred items at once  have to select each item individually
also if you hit all items it will change to cots of each item to an absurd amount

**Comment by 59blargedy** [comment]
resolved in April 19, 2022 update
