### ISSUE TITLE
Nyzul skip boss floor

### ISSUE THREAD

**Issue by Norrissnake** [EdenServer/community#4988]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

We cleared floor 79 and were having issues with porting all night then this happened when we hit the port button 2x

![image](https://user-images.githubusercontent.com/85299428/164048471-4b9e5513-58b2-4e9d-a43b-c68f3001c848.png)

**Comment by KnowOne134** [comment]
corrected 4/28/2022
