### ISSUE TITLE
Slave Globes not following Mother Globe

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4989]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

https://youtu.be/_ZCoYzFp-_I shows Slave Globes following MG around the room. Currently on Eden they don't. They used to, but now just roam around the area. They do still link no matter the distance from MG though.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
