### ISSUE TITLE
Rest with debuff on me

### ISSUE THREAD

**Issue by dakumauler** [EdenServer/community#499]
I able to rest well having dia on me and heal up right now. i know that is a bug

**Comment by godmode** [comment]
Does it cause damage?

**Comment by dakumauler** [comment]
when i am sitting no

**Comment by tectal831** [comment]
Did you have stoneskin on?

**Comment by dakumauler** [comment]
No I was on my monk.  I had no buffs  just dia on me after fighting a goblin in dunes

**Comment by beauxq** [comment]
I just tested this with Bio.
Bio doesn't do damage, doesn't stop me from resting, doesn't lower my attack, and doesn't wake me from sleeping.
I'm guessing dia has all the same problems.

I tested the Rasp dot and it does do damage and stops me from resting.
