### ISSUE TITLE
Outpost NPC Not Offering Signet When Owned By My Nation 

### ISSUE THREAD

**Issue by mark-johnstone** [EdenServer/community#4990]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I'm nation San d'Oria and outpost NPCs (owned by San d'Oria) are not offering one of my characters signet. 
![image](https://user-images.githubusercontent.com/29806202/164070275-3378d497-c7c8-438f-b907-e160f558053f.png)

Changed my homepoint (originally thinking it was due to that being set outside of the city) back to mog and OP NPC still not offering signet.

City guards within San d'Oria offered signet. 
![image](https://user-images.githubusercontent.com/29806202/164070772-91dc4719-b282-467a-a16d-fa9fdf031e49.png)

One difference between my character who can get it from OP NPC and the one which can't is the one which can't has done a few of the tutorial NPC quests introduced last patch. Quest 4 complete, Quest 5 in progress. 

version: 30181205_0

**Comment by bliven-was-taken** [comment]
![image](https://user-images.githubusercontent.com/61694447/164071830-005b10d6-4534-424e-a83e-2111cf4ccba7.png)

Have not started tutorial quests yet on this char. 

(To be clear, in the original post, the character that hasn't started the tutorial quests can get signet and the one that is on quest 5 in the tutorial quest chain can not get signet) Trying not to see if this repeats for me on my char.

**Comment by bliven-was-taken** [comment]
Bug seems related to possessing the Conquest promotion voucher.

**Comment by KnowOne134** [comment]
Flag needs to be set only on town npcs for owning the voucher 👍

**Comment by KnowOne134** [comment]
Corrected 9/21/2022 update
