### ISSUE TITLE
Mobs able to "Block" Trick Attack WS completely

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#4991]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

Currently on Eden, mobs seem to be blocking (but completely negating the damage from) Trick Attack weaponskills. Block doesn't seem to proc on non-WS Trick Attacks though.

Sadly the best retail data I have for this not being a thing is https://ffxiclopedia.fandom.com/wiki/Trick_Attack?oldid=673763 - "If this ability is used while dual-wielding, both hits are guaranteed to hit, but only the first hit will deal critical damage. If Double Attack and/or Triple Attack activate, these hits are guaranteed as well."

Tested on PLD mobs w/ shields and I would often have my main hit not return any TP, and WS damage was greatly reduced. If I didn't DW, WS would miss and return 0 TP. 

Parry proc doesn't seem to cause the same effect. Never had main hand hit return 0 TP on mobs that can parry that don't have shields.

**Comment by 59blargedy** [comment]
they can block TA regular attacks too, and it will occur on parried and guarded wses as well. just to clean up some assumptions.
whether or not that is right is definitely up for debate, i am unsure. any addl info is helpful.

**Comment by 59blargedy** [comment]
resolved in July 8, 2022 update
