### ISSUE TITLE
Beadeaux afflictors messaging repeating too quickly

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#4992]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
When running past afflictors, they inflict you with curse normally but then stack the movement speed down infinitely untill you cap on it and move at a very slow speed
![image](https://user-images.githubusercontent.com/69089249/164082235-6c00cbc7-a097-4218-b80a-249bce956ebb.png)

**Comment by 59blargedy** [comment]
Resolved in April 28, 2022 update
