### ISSUE TITLE
Dynamis Buburimu Apocalyptic Beast Mega Boss abilities not locking

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#4996]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Mega boss 2hrs and abilities don't seem to be locking properly.

Unlocked sub jobs before pulling anything

My group ran dynamis bubu today for the first time and kill a bunch of dragons before killing any beastmen. 

**We killed, in order:**
Aitvaras > Koschei > Stollenwurm > Tarasca > Barong

After killing the dragons we killed The quadav mobs to lock benediction, invincible, and perfect dodge. Unsure on the order here. I'm being told we pulled statue 025 then 037. https://cdn.discordapp.com/attachments/683974282501816332/966762394565099550/Buburimu1.webp 

Then Apoc Beast was pulled, during the fight it used all dragon abilities including ones that should have been disabled. However, 2hrs all seemed to be locked fine because we never saw benediction go off. 

I know someone in discord was talking about the inverse happening, dragon moves being locked but beastmen 2hrs still happening.

**Comment by 59blargedy** [comment]
resolved april 28, 2022
