### ISSUE TITLE
Dynamis - Buburimu: Killing dragons beforehand doesn't lock abilities used by Apocalyptic Beast from taking effect

### ISSUE THREAD

**Issue by FrankWHansen** [EdenServer/community#4997]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver = 30181205
Searched just the last week or so of bug reports as this is such a new event.

Summary of events: Apocalyptic Beast (AB) is the zone boss of Buburimu. AB has numerous abilities at his disposal, some of them dangerous. To prevent these abilities from being used, we killed several of the dragons located around the zone before pulling and engaging AB. Killing one dragon should lock one specific ability from harming our group while fighting AB. AB should still use them, but they will not have any effect, from my understanding kind of like firing a gun that isn't loaded.
My screenshots aren't the best. I thought these bugs would be handled the same way as Nyzul (being a new event), where GMs would take bug reports on the fly, so I just called a GM, planning to let them verify that we had already killed various dragons in the zone and then after event finish provide screenshots of AB using the abilities successfully regardless. Also at the time we were killing dragons, I wasn't aware I would need to bug report AB later, so I don't have proof of that taking place.

There's similar mechanics to lock him from using two-hours, by killing beastmen of the same job as the two-hour you want to lock. We killed WHM PLD THF nms and I didn't notice any of these 2hrs going off, so that seemed to work just fine.

To reproduce this bug, you need to enter Dynamis - Buburimu and kill some of the dragons. Then locate and engage AB in battle, feed him TP and wait to see the abilities go off and still take effect. All this could probably be achieved in a test environment with just one character with some godmode features.

3 images of my battle log, and one image of ffxiclopedia's article on AB (going back in history to dec. 2007.

![Bilde_2022-04-22_002543654](https://user-images.githubusercontent.com/10707774/164561554-98e1125f-07d3-4da7-9d6f-a3dcfcb07834.png)
![Bilde_2022-04-22_002724355](https://user-images.githubusercontent.com/10707774/164561708-03bf78d8-5a8d-4c2d-a831-01ce582c8054.png)
![Bilde_2022-04-22_002819705](https://user-images.githubusercontent.com/10707774/164561791-2bcfe966-7242-4606-af6b-de18e7410348.png)

![image](https://user-images.githubusercontent.com/10707774/164563006-82cf2153-99d4-4c41-8ba8-8c9bd35361c4.png)

**Comment by 59blargedy** [comment]
resolved april 28, 2022
