### ISSUE TITLE
Carpenter's Aurum tome

### ISSUE THREAD

**Issue by AzrielltheWise** [EdenServer/community#5001]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver: 30181205_0

I received a key item "Carpenter's Aurum tome" while buying maps from the Imperial Standing/Sanction npc Asrahd in Whitegate.  I tried to buy a Map of Mamook but received the wrong key item.  I was then able to choose Map of Mamook from the list again, and actually purchase it the second time around.  

Before going to buy the map, I first looked at the Rank 0 items, specifically Katana Strap, Axe Grip, and Staff Strap from Asrahd's menu.  Then I backed out (I did not close the dialog window, I simply back out a few menus) and went to Rank 1 items and bought Map of Mamook.

I purchased the Map of Halvung and the Map of Arrapago Reef immediately after with no issue.

Carpenter's Aurum tome appears to be a key item from retail that is used to craft item level 119 wood working items.

![Screenshot 2022-04-22 131757 carpeter's aurum](https://user-images.githubusercontent.com/90195635/164763953-6548aab5-b5e4-4f45-a73d-db0cac3854b3.png)

![Screenshot 2022-04-22 132731 carpenter's aurum 3](https://user-images.githubusercontent.com/90195635/164764603-f172b4b0-376d-4a17-bf01-cb3a56256cff.png)

The BG-Wiki page for Carpenter's Aurum tome.  Please note that the items it is linked to are i119 and require this key item to craft.  https://www.bg-wiki.com/ffxi/Carpenter%27s_aurum_tome

**Comment by 59blargedy** [comment]
i'll add your details to this existing ticket https://github.com/EdenServer/community/issues/2578
thanks for providing addl info!
