### ISSUE TITLE
Blood saber from skeletons should wipe utsusemi/blink 

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5005]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

https://ffxiclopedia.fandom.com/wiki/Category:Skeletons

Blood saber is an AoE magic attack and as such should wipe shadows. It currently does not

**Comment by 59blargedy** [comment]
some aoe magic attacks ignore shadows completely, as this one is currently set to. will just need to retail validate at some point (didnt see anything definitive in link).

**Comment by falzum** [comment]
Trying to find a video but coming up empty. This is the best I have for now 


https://ffxiclopedia.fandom.com/wiki/Copy_Image

"Loses all copy images, and takes damage and/or becomes enfeebled
The caster is hit by an AoE magical WS such as Blood Saber, or an AoE spell such as Firaga."

**Comment by ConteAlmaviva** [comment]
My recollection is that there are some abilities that wipe shadows and others than ignore them - Cursed Sphere (Damselflies) being an example of the latter if memory serves. Blood Saber was another than did damage through shadows but did not overwrite them, if I’m remembering correctly from retail.

**Comment by Steam-arch** [comment]
https://m.youtube.com/watch?v=0KNoBcwTmp0

1:00 blood saber removes fresh utsu

**Comment by 59blargedy** [comment]
Validated on retail as well and Resolved in April 28, 2022 update
