### ISSUE TITLE
Dynamis Buburimu - Wrong npc name/model Cockatrice/Mandragora

### ISSUE THREAD

**Issue by jasonm323** [EdenServer/community#5007]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver. 30181205_)

![image](https://user-images.githubusercontent.com/80853832/164950609-8d615ec9-f3fa-4d52-879e-43c5603e5d57.png)

Wrong name or Model for monster

**Comment by Mozzy4Ever** [comment]
Do you have the updated renamer? https://github.com/EdenServer/community/blob/master/renamer/eden.lua

**Comment by jasonm323** [comment]
I do not

**Comment by 59blargedy** [comment]
just did this zone last night and mobs appear correctly named with most recent renamer files. some steps to update your files - 
1) navigate to here in your eden folder: PlayOnline\Ashita\addons\renamer and open the renamer file in your preferred text editor. hit ctrl/command a to select all. after selecting all  you can hit the del key to delete everything and have a clean slate. the file should be empty now.
2) separately, click on the below link, ctrl/command a to select all, and ctrl/command c to copy.
https://raw.githubusercontent.com/EdenServer/community/master/renamer/eden.lua
3) paste the copied text into your open renamer file and save. if you are in the game already, you'll need to /addon reload renamer

im sure there's a better way to do this, but this is the way that most people can understand regardless of tech level. hope it helps!
