### ISSUE TITLE
Speed isn't capped to +100%

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5009]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

Per https://ffxiclopedia.fandom.com/wiki/Movement_Speed?oldid=1008232 , the highest +speed you should be able to get is +100% (Flee). Any additional amount over that (NIN AF feet, mazurka, wlegs, striders, aketon, etc) shouldn't increase beyond that. Furthermore, when you have multiple sources of movement speed, you should only gain the highest effect. IE: Having Chocobo Mazurka (+25%) and WLegs will only result in +25% increase.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
