### ISSUE TITLE
CoP 5-3 Tenzen's Path CS Bug

### ISSUE THREAD

**Issue by Shueiki** [EdenServer/community#5010]
Unable to activate the CS from Carbuncle at the ???. Carbuncle gives the key item for Waking the Beast and further dialog regarding the fight when clicking the ???again. Carbuncle does not give CS regarding Tenzen's Path to start the quest. No issues with running Louverance's Path and Ulmia's Path simultaneously. Appears to be a bug since Waking the Beast was added.

**Comment by Shueiki** [comment]
Was able to complete Ulmia's Path and Louverance's Path just now without issue. Just unable to start Tenzen's Path.

**Comment by 59blargedy** [comment]
put in a gm call, gm can reach out to me for details on temp bypassing.

**Comment by Shueiki** [comment]
Done! Put in a ticket in game.

**Comment by 59blargedy** [comment]
Resolved in April 28, 2022 update
