### ISSUE TITLE
Bunnies in Kazham do not hop [very important] 🐇

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#5014]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The Rarabs in Kazham at (J-9) next to the SMN quest do not hop / move around like they should. 

Proof of hopping : https://youtu.be/j0y4eze7Mwc?t=1485

**Comment by 59blargedy** [comment]
Critical hopping issue resolved in April 28, 2022 update
