### ISSUE TITLE
Investigation of the Emptiness Reward Issue

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5017]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I received food from my NPC from Investigation of the Emptiness, but according to bgwiki and ffxiclopedia you need to reach the second island to get the food reward (and have completed Mixed Signals). I only did the first island.

The exp reward also seemed to go over the cap. I stopped counting my enemies but I killed right around 30, maybe a few under and got just over 1500, despite the cap for island 1 saying 1500 on the wiki.

https://www.bg-wiki.com/ffxi/Investigation_of_the_Emptiness
![image](https://user-images.githubusercontent.com/13668758/165540900-60731ef1-940f-4c9e-a875-1c7f526efe57.png)

https://ffxiclopedia.fandom.com/wiki/Tactics_Pearl_Quest
![image](https://user-images.githubusercontent.com/13668758/165540956-0160ac7a-5372-4515-b49b-55d976bd0465.png)

As for the exp:

![image](https://user-images.githubusercontent.com/13668758/165541084-b665628b-51a2-4f54-a849-98cd2d4999a7.png)
![image](https://user-images.githubusercontent.com/13668758/165541144-7f3bf899-a0c5-4759-b7db-944f5e4aa16a.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 19, 2023 update
