### ISSUE TITLE
ToAU Mission 9 dialogue options are not going away

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#5018]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

In the ToAU 9 mission cutscene in the ruins, you get to a part where it asks you if you want to hear about the windows, the pillars or, the floor. Once you select each option, it's supposed to go away, and once you have listened to the 3rd option the cutscene continues. However, the dialogue options are not going away after I select them, so it's just asking me which part of the ruins I want to ask about over and over, I've done each dialogue option at least 10 times on 2 different characters and nothing is happening.

https://www.youtube.com/watch?v=hbUs-XsCnbk  9:28 in this video the first option is picked and you can see the options going away.

30181205_0

**Comment by KnowOne134** [comment]
Fixed 4/29/2022
