### ISSUE TITLE
Final Fight for Aht Urhgan Mission isnt in BCNM

### ISSUE THREAD

**Issue by Koga83** [EdenServer/community#5019]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [? ] I have provided my client version in the details. (type /ver into your game window)
- [? ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
My group zoned in and there was no boss.  Also it didnt use up KI on enter needed for the fight. 
![unknown (3)](https://user-images.githubusercontent.com/99617008/165781424-e0eef25f-2a1c-4213-86b6-1bb88633c4e1.png)

**Comment by 59blargedy** [comment]
resolved april 28, 2022
