### ISSUE TITLE
When entering a BCNM, if you forget to invite someone, i.e. your alt inviting them from inside doesn't allow the outside person to enter or give them the BCNM buff. 

### ISSUE THREAD

**Issue by HitGubz** [EdenServer/community#5020]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Version: 30181205_0

This might not be a valid bug report, but as I've done it a couple times worth dropping in here to see. I've searched the forums and can't find anyone confirming either way. I don't have an active retail account to check what happens on retail. 

Steps: 
Me and my alt wandered down to the BCNM one day, in my haste and excitement at the thought of all the juicy loot I was about to receive I didn't realise I hadn't partied up with myself. Low and behold I traded my Comet Orb (50 Seals) to the Burning Circle, it took me all of 0.1 nano seconds to realise I had F'd up, and my dreams of juicy loot were quickly dashed when I picked the wrong chest. RIP me.

**Comment by falzum** [comment]
This isn't a bug. Everyone needs to be in party before the fight is selected
