### ISSUE TITLE
Unable to enter dreamlands with more than 1 party

### ISSUE THREAD

**Issue by FrankWHansen** [EdenServer/community#5022]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205

The character limit seems to be set to 6 instead of 36, for Dyna Valkurm. I recommend checking the other Dreamlands zones as well.

We were trading glasses and entering, but once we had 6 people in, we were unable to enter any more. Every person past six original characters were unable to enter, upon zoning they would just end up in Dunes near outpost again.
Tried dropping a character then re-entering and that worked just fine.

Idk what else to write here. We called a GM and they confirmed there was a real issue with this and we got a replacement hour glass for our next dynamis run.

**Comment by 59blargedy** [comment]
partially resolved in recent update (the issue was not a typo, so i changed title to correct one for records)
