### ISSUE TITLE
"Chips" quest is repeatable even though you have a Rare item in your inventory

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5023]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Game lets you repeat the quest even with CCB polymer in your inventory
![image](https://user-images.githubusercontent.com/69089249/165854145-83971889-8091-431b-96f0-e09628282f4e.png)
![image](https://user-images.githubusercontent.com/69089249/165854406-a444c073-de3a-430a-bae3-a26c663eaf3c.png)

**Comment by 59blargedy** [comment]
(hopefully) Resolved in June 13, 2022 update.
