### ISSUE TITLE
Beadeaux Afflictor curse effect movement- too strong?

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5024]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Afflictors curse's movement speed- got drastically increased (might be a stacking effect-bug) a few patches ago. The effect seems close to -85% movement speed. I assume this is a bug? Curse lowers your HP to ~1/4 of your max HP which seems correct. 

2017 video (unfortunately cant find anything era):
https://www.youtube.com/watch?v=JAtavwAnqfA
13:17 curse is afflicted. Movement speed is reduced by not alot. Retail had its base movement speed was changed by abit so maybe someone else can evaluate on what the movement speed- should be, I cant find any notes for it.

Close away if im wrong.

**Comment by 59blargedy** [comment]
the strength was adjusted, but need someone to put on some dusk gloves or something and run through on retail, should compensate enough for the increased movement speed. then we can compare and see if we need to split out curse power from movement speed effect

**Comment by FariskaEden** [comment]
https://www.youtube.com/watch?v=_2COj_ZHLxo - running through with 2 pieces of dusk + curse

Felt like a 12.5% drop in speed. Curse duration is currently 5 minutes but should be 2 minutes. Also the animation for getting cursed is missing I believe.

**Comment by 59blargedy** [comment]
resolved this with the speed changes in July 5, 2024 patch
