### ISSUE TITLE
Bard Song Casting time are Wrong (tested Minuet/March)

### ISSUE THREAD

**Issue by ccl085** [EdenServer/community#5025]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)
- [X ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

vers: 30181205_0

Bard casting time on song are wrong, they are 11-12 sec on Eden (couldn't pint point to exact casting time but should be easy looking at the code).

On every Era wiki I could find casting time is 8sec: 
-> https://ffxiclopedia.fandom.com/wiki/Valor_Minuet_IV?oldid=300965
-> https://www.bg-wiki.com/index.php?title=Valor_Minuet&oldid=28700
-> https://www.bg-wiki.com/index.php?title=Victory_March&oldid=52060

**Comment by Mozzy4Ever** [comment]
![image](https://user-images.githubusercontent.com/11255886/165991944-03a05d2b-7e8d-4049-8527-9d998936db73.png)
Because of how FFXI delays messaging, it looks like 12 seconds. If you use something that makes the messages instant (like battlemod), it's 8 seconds

**Comment by ccl085** [comment]
Ok, thank you for the clarification

**Comment by 59blargedy** [comment]
i checked db to be sure and the cast times are 8 secs so closing this one out.
