### ISSUE TITLE
SJ not unlocking in Dyna-Tav

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5028]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

Entered tav and SJ restricted properly. Went to 3rd floor and killed Antlion, then down to 2nd to kill worm. SJ didn't unlock as it should've. Had to exit and reenter for it to be removed.

**Comment by 59blargedy** [comment]
this was resolved by another dev and fix is live, unsure of date of resolution.
