### ISSUE TITLE
Dyna Tav- 18th member repeatedly kicked

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#5030]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

During dynamis tav tonight, our LS was only able to have 17 people inside. When the 18th member would join, they would be instantly booted. Player tried a few times to join but was kicked each time after getting inside. At one point the alliance had to drop glass to re-enter to unlock our subjobs. There were no issues then with players re-entering; however 18th player could never join without being instantly booted.

To reproduce, take 18 people into dynamis tav and see if the 18th player gets repeated kicked out of the instance.

**Comment by falzum** [comment]
Your 18th person had all the key items from the other 3 zones?

**Comment by setsuk0** [comment]
> Your 18th person had all the key items from the other 3 zones?

Yes

**Comment by 59blargedy** [comment]
This should no longer occur - resolved in a previous update.
