### ISSUE TITLE
WAR JA Retaliation has wrong animation

### ISSUE THREAD

**Issue by masamuneCS** [EdenServer/community#5031]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver 30181205_0
Retaliation currently shares the same animation as the THF ability Accomplice/Collaborator

Retaliation animation on retail 
https://youtu.be/oxbC0xzyVXY?t=256

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
