### ISSUE TITLE
Nightmare Makara Screwdriver should be conal

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5034]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

Eden currently has Nightmare Makara Screwdriver (In Tavnazia at least) as single target.
According to the best video I have ever found (complete with era accurate music), it should be conal. https://youtu.be/1DcXRtZDMds?t=167

You can see the windup animation is Screwdriver and if you get a lucky pause you can see that the Makara readied screwdriver. Both the person in front of the Makara and the video taker were hit by it.
It does look like a very "line" style of cone (which makes sense considering the animation tbh) because the people to either side of Ansetsu weren't hit by it

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
