### ISSUE TITLE
ToAU15 progresses to ToAU16, even if you fail

### ISSUE THREAD

**Issue by KeziaC** [EdenServer/community#5035]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Went to try and solo ToAU15. Almost had it, died before my vile elixir went off near the end of phase 2. Got the system message that "All party members have fallen in battle. Mission failure in 3minutes." Then instantly got transported into a cutscene, even though I was dead. 

My dead body got ported to Nashmau (embarrassingly right in front of all the people fishing), where Gessho proceeded to give me the CS for the usual successful completion of the Black Coffin fight. When the CS was done, one of the fishers kindly raised me. I checked my mission log and I had been advanced to ToAU16. 

According to the wiki, I there should be a fail state, such that if you fail the fight you have to go retrieve another KI from the previous mission (Jakaraat fomor fight in the cemetary) in order to retry the Black Coffin. 

/version 30181205_0

Reproducible steps: 1. Enter ToAU15 solo 2. Clear first wave 3. When I died the captain was still alive in the 2nd wave, but I had killed a few of the smaller duders. 4. Die 5. Wake up dead in Nashmau and sulk in shame as you accept a raise from a fisher

**Comment by KnowOne134** [comment]
Could you have killed the mobs while being dead with a dot?

**Comment by KeziaC** [comment]
That's what Aether suggested as well. Its quite possible, I had Bio3 on it. Also possible is Gessho could have pushed it past the 20% threshold. Sorry, when I made the bug report I didn't even realize it gave up at 20%.

**Comment by KnowOne134** [comment]
If gesho was still alive he would still keep fighting until the 3 min mark to escape you so I'm pretty sure that's what happened

**Comment by KnowOne134** [comment]
looked into and only way to have won was with gessho finishing the fight within your time limit, so same as another party member dealing final blow while your dead, you still get win progress

closing as no real issue, but thanks for bringing it up to check
