### ISSUE TITLE
PUP Relic +1 Feet - Missing item for completion

### ISSUE THREAD

**Issue by ArsinoeX** [EdenServer/community#5036]
### Checklist

- [ x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ x ] I have provided my client version in the details. (type /ver into your game window)
- [ x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Unable to complete Pantin Babouches +1 turn in as it requires a Peiste Leather to complete. As monsters in the Peiste family are out of era, I wasn't sure if this item was added to Eden upon the last patch.

https://ffxiclopedia.fandom.com/wiki/Pantin_Babouches_%2B1?oldid=717002
(November 2008)

Edit: Client Version - 30181205_0

**Comment by KnowOne134** [comment]
We have decided that the item needed is out of reach since we do not carry the wotg expansion, therfor the upgrade is unobtainable. 1 of the few issues we will find with our date change without going fully custom will happen.
