### ISSUE TITLE
Lure of the Wildcat (All Nations) blocking ToAU missions

### ISSUE THREAD

**Issue by StormyEden** [EdenServer/community#5037]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
version 30181205_0
Progress in ToAU:18 is blocked by the active quest "Lure of the Wildcat (All Nations)" 

Declining to turn in the invitation card to receive your coin reward seems to block any further interactions with Naja. Since you are required to make a zone transition to initiate this part of the mission, it also resets the Invitation card turn in. Creating and endless loop of not being able to progress.

was resolved by turning in the quest for any amount of coin reward and then zoning once more

**Comment by KnowOne134** [comment]
Corrected 6/11/2022 update
