### ISSUE TITLE
Yowie NM - Kuftal Tunnel

### ISSUE THREAD

**Issue by UpNGone** [EdenServer/community#504]
Please audit the spawn rate and conditions for Yowie in Kuftal Tunnel.  I have spent ~15 hours killing Deinonychus (Raptors) at his spawn area (H-8) on lower map of Kuftal Tunnel and have yet to see him spawn.  I have spent time killing all of the raptors on the lower map in case his placeholder is incorrect and still have not seen him pop.  He is supposed to a fairly quick respawn (~2hrs) and he only drops crafting items for a small handful of synths.

**Comment by LongTimeGaming** [comment]
I've gotten him to pop fairly consistently the past few days, but his gil amount he drops is not correct. Have gotten barely 100gil when wiki says he's supposed to drop 12k+ https://ffxiclopedia.fandom.com/wiki/Yowie
![yowie](https://user-images.githubusercontent.com/47086093/54173691-5330dc80-4459-11e9-9a5e-d69503edc11e.png)
