### ISSUE TITLE
Dynamis - Qufim Nightmare rocs Should be (atleast) sleepable with lullaby

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5040]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Some conflicting info about dark based sleep
dynamisbums info
![image](https://user-images.githubusercontent.com/69089249/166981626-d2e60762-8dc7-45cc-91c0-7075ff712281.png)
![image](https://user-images.githubusercontent.com/69089249/166981650-e1e5417d-baa7-43c5-8184-3ed7c0373ca6.png)

but should be atleast sleepably with horde lullaby

Currently:
![image](https://user-images.githubusercontent.com/69089249/166981487-764d1daf-bb93-49eb-9e15-6cc82c78ffdc.png)

Hmm. Deleted a portion. Actually gotta find some better evidence for this first. Wont close right away since theres some conflicting info about it.

**Comment by bliven-was-taken** [comment]
![image](https://user-images.githubusercontent.com/61694447/166985019-e50a9b2b-a069-4ea3-8791-23d5305dad9d.png)

**Comment by 59blargedy** [comment]
Resolved by another dev in June 13, 2022 update.
