### ISSUE TITLE
Spells being cast on entity carry on to the next entity (pets, reraised players)

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5041]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
If a long spell is being cast on your current summon, you desummon it and resummon any avatar, the spell will go off on the new avatar
![image](https://user-images.githubusercontent.com/69089249/167120944-a369a13f-aaba-4193-b54a-a16d43e10c3b.png)

**Comment by xwiz75** [comment]
so apparently last night a goblin cast flare on me i died mid flare cast and rr'd and ate a flare. definitely a thing.

![Xwiz_2022 07 01_214637](https://user-images.githubusercontent.com/104098935/177012883-e979d41a-f732-4b46-aa5f-9587cd99744e.png)

**Comment by 59blargedy** [comment]
this was resolved in a previous update
