### ISSUE TITLE
Nostokulshedra showing as Soulflayers not Kraken

### ISSUE THREAD

**Issue by xwiz75** [EdenServer/community#5043]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- x[ ] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Nostokulshedra in Arrapago Reef are shown as Soul Flayers when in fact they show be Kraken.  Ibar shows them as MNK with Ice/Lightning weakness. Also per wiki they should be Kraken type mobs.

https://ffxiclopedia.fandom.com/wiki/Nostokulshedra
![Xwiz_2022 05 06_121358](https://user-images.githubusercontent.com/104098935/167222851-06d88ac3-b829-4ebd-9e3d-bb62e4655215.png)

**Comment by Mozzy4Ever** [comment]
This is a renamer issue.

Open \Ashita\addons\renamer\lists\eden.lua -> Go to https://raw.githubusercontent.com/EdenServer/community/master/renamer/eden.lua and copy everything -> Paste into eden.lua -> Save -> Ingame can type `renamer load eden` and it should fix their names.

**Comment by 59blargedy** [comment]
i asked since im not entirely sure if those are supposed to be soulflayers or krakens in that location

**Comment by Frozzen907** [comment]
at g-7 there is some Crabs named Nostokulshedra aswell.. my renamer is current. i even rechecked that.  

Crabs on the IBar addon also show as "Detects: Sound     Job;Monk    Weak VS: Ice, Lightning    LV,88-89

Wiki shows Nostokulshedre as Kraken mobs. 

My /ver is 30181205_0
![reefmobs](https://user-images.githubusercontent.com/97677834/203775657-02063c5e-4bf0-483e-b3cb-c5ab36d7b2d6.jpg)

**Comment by statuseffect** [comment]
Nostokulshedras are OOE by looking at the dated wiki page of 2010,

The mobs should be wootzshells and soulflayers by the looks of it.

**Comment by 59blargedy** [comment]
Resolved in February 20, 2023 update, update renamer for fixes
