### ISSUE TITLE
Blocked in quest "Regaining Trust"

### ISSUE THREAD

**Issue by Nonono-Amb** [EdenServer/community#5044]
### Checklist

- 

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)

- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

After killed Ingaevon, talked with my fellow then hit on the Giant Footprint. Nothing happened. GM was called and suggest to submit a bug report.

* Quest[3][85] Prog var isn't advancing to 4 after talking to NPC.
![Nonono_2022 05 07_074539](https://user-images.githubusercontent.com/105087043/167228643-191fd67d-2ca9-46d4-ad78-6563bf026942.png)

**Comment by KnowOne134** [comment]
Talking to the fellow changes var to 3, you then have to click on the ??? Again to advance to 4

**Comment by Nonono-Amb** [comment]
I clicked on the giant footprint after talk with fellow but nothing happened.

**Comment by Nonono-Amb** [comment]
Problem fixed by GM. Quest completed.  Thank you very much.

**Comment by KnowOne134** [comment]
Reopening g as there is an issue with a fix incoming

**Comment by KnowOne134** [comment]
corrected 6/11/2022 update
