### ISSUE TITLE
Entering Dynamis - Sandy issues

### ISSUE THREAD

**Issue by jasonm323** [EdenServer/community#5046]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Tried entering Dynamis-Sandy on 5/7/2022 at 3:00pm EST, 10/12 members could enter but 2 could not.  Just traded an hourglass like normal.

**Comment by ConteAlmaviva** [comment]
Had they done a Dreamworld Dynamis (Valkurm, Buburimu, Qufim)?  I think if you've done a Dreamworld Dynamis there's a CS flag or something you need to clear at the Hieroglyphics (Maybe Valkurm specifically, or  just at the Hieroglyphics for whichever one you did).

**Comment by jasonm323** [comment]
IDK we've all done the same thing that entered, and only two of us couldn't enter.

**Comment by bliven-was-taken** [comment]
Tell the people to go check all the hieroglyphics and dynamis trail markings, it's been a pretty common bug.

**Comment by 59blargedy** [comment]
resolved by another dev in November 21, 2022 update
