### ISSUE TITLE
Phalanx II Damage reduction calculation

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#5047]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [N/A] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Suspect current Phalanx II calculation (and probably Phalanx, as well) are not rounding down Enhancing Skill number as required when determining potency. 

Per era [wiki](https://ffxiclopedia.fandom.com/wiki/Phalanx_II?oldid=867562): 
Damage prevented Formula for this spell is [(enhancing magic/25) +1 + (3 x MeritLv)], but it also states "Adding more enhancing magic is useless unless you can break another 25 skill tier" implying the formula should be the following: 

[Floor(enhancing magic/25) +1 + (3 x MeritLv)] as described in more recent edits. 

However, when testing this with 263 Enhancing skill, it results in a Phalanx mod of 27 (expected result of 26 for this skill level). Some more Enhancing skill test:

286 skill = 27 Phalanx
289 skill = 28 Phalanx (27 expected)
293 skill = 28 Phalanx (27 expected)
301 skill = 28 Phalanx

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
