### ISSUE TITLE
Dyna Tav Reservation not clearing (clears in 3.5 hours from entry)

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#5048]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
First group from KC entered at 7:45P ET, second group tried to enter around 9:50 ET when first group had timed out / left the zone. 

Second group tried to trade glass, got to confirmation screen, and nothing happened (no perpetual glass give, no timeless consumed). 

Had a feeling and went to check at 10:20P ETish (3.5 hours after original entry) if the reservation was clear and it was. Was able to get a Perpetual glass/fresh run etc.

**Comment by 59blargedy** [comment]
this was resolved in a previous patch
