### ISSUE TITLE
SMN Avatars SDT needs an audit

### ISSUE THREAD

**Issue by Mildew-Von-Eden** [EdenServer/community#5049]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Client version: 30181205_0

As per this link...
https://ffxiclopedia.fandom.com/wiki/Leviathan

Leviathan is supposed to have a "very high resistance to amnesia."

Day 1 when I first noticed something:
![20220509_200848](https://user-images.githubusercontent.com/35544823/167536293-a275a122-e4f3-476a-bce8-def8513fe954.jpg)

Day 2 further testing:
![20220509_200827](https://user-images.githubusercontent.com/35544823/167536335-cfa2bc31-20f6-433e-875f-d324c0d7000c.jpg)
![20220509_200806](https://user-images.githubusercontent.com/35544823/167536350-1b8efe94-8539-4c89-9459-6a75e2d5226b.jpg)
![20220509_200746](https://user-images.githubusercontent.com/35544823/167536368-e9403d84-032d-4c08-860a-15d8acdaca3d.jpg)
![20220509_200659](https://user-images.githubusercontent.com/35544823/167536403-7975dc8f-a376-452e-9a03-a8962cfc0e29.jpg)

4/5 amnesic

I doubt this is specific to Leviathan, so I would suggest an audit of all avatars SDT.

**Comment by Steam-arch** [comment]
Currently atleast amnesia can get partial duration resists. You can increase the resist rate with stacking fire resist, and Leviathan has high resist to his own element & opposite, with high fire & water resists and amnesia being fire based, I would assume he got atleast partial resists for those amnesias that landed, would explain why someone on wiki would write "high amnesia resist".

No idea if the fire resist should be buffed though, or if theres some gimmicks involved where status effects infected by abilities/tantara would always be either a full resist or a full duration (dont think so [?]), or if leviathan just has a resist amnesia trait, idk.

**Comment by Mildew-Von-Eden** [comment]
It's not about the duration of the debuff. Each avatar is basically immune to certain debuffs. It shouldn't be landing nearly that much... for any duration.

**Comment by 59blargedy** [comment]
the resist is already very high (amnesia barely lasts). could certainly increase it, but all i'm seeing here is the statement that leviathan's amnesia resistance is high. did some info get cut off that shows levi/ifrit should be immune as stated or is this just a memory thing? it's fine if it is, but that means someone will need to validate/research before any adjustments are made, and i can put the research tag on for someone to check out.

**Comment by Mildew-Von-Eden** [comment]
Dowzer said he tested on retail and it didn't land once out of 20 Abrasive Tantaras.

I was going off this guide at first:
https://ffxiclopedia.fandom.com/wiki/Summoner_Solo_Guide_by_Keepongo#Levels_73-75

**Comment by E5una** [comment]
From the SMN channel where Dowzer mentioned it for context, also here is a link to the video he posted, its just a clip from the larger video where he did more testing.

![image](https://user-images.githubusercontent.com/13668758/167707781-e6feb747-52fc-4857-ba97-0a84ccd0af0f.png)

https://www.youtube.com/watch?v=FY8m_6vmvTE

![image](https://user-images.githubusercontent.com/13668758/167707834-042d58e6-e408-4a4d-9ed1-190ac8dc6497.png)

We'd have to ask Dowzer if he'd lend us the full video for more info if it was desired.

**Comment by Steam-arch** [comment]
Atleast bg takes a wider approach and states water enfeebles too.

![image](https://user-images.githubusercontent.com/69089249/167709757-3002ad70-7cf1-44cd-9cd9-a86f01ce02fa.png)

**Comment by dowzer** [comment]
I watched that video again and I missed one that landed.

After more testing, it was evaded 67 out of 75 times and landed 8. I'm uploading a 25min clip where it was evaded 22 times in a row. 

Levi resisted their Poisonga II and Ifrit resisted Amnesia as well.

https://www.youtube.com/watch?v=Pe1FU2Lnz9g

![Leviathanpoison](https://user-images.githubusercontent.com/54732693/167768233-b925cfd1-68f2-49d5-99fc-e156bbbecbf8.png)

**Comment by Mildew-Von-Eden** [comment]
Sand Trap has "missed" Garuda 100% in my testing. I'm wondering if it's Abrasive Tantara that needs to be audited.

**Comment by dowzer** [comment]
I’ve completely evaded Abrasive Tantara countless times on Drk with Barfira from Rdm/Whm. It can also halve the duration when it doesn’t evade it completely. 

It sounds like a lucky streak with Sand Trap.
