### ISSUE TITLE
ToAU31 - Pair of potential bugs

### ISSUE THREAD

**Issue by KeziaC** [EdenServer/community#5050]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I have been working on ToAU31 solo, and closely reading the era wiki entry for it:
[https://classicffxi.fandom.com/wiki/Aht_Urhgan_Mission_31:_Shades_of_Vengeance](https://classicffxi.fandom.com/wiki/Aht_Urhgan_Mission_31:_Shades_of_Vengeance)

Two things stand out that I think may be bugged:
1. I have failed this instance a few times, and am definitely losing xp each death. The wiki claims that even though the area is technically an assault, it should instead be treated like a battlefield instance and have no death penalty. If you watch the video to the end you will see the xp bar goes down.
2. The lamias are not inflicting poison with their ranged attacks, or if they do it is a very very low chance. In the linked video, I take 10 ranged attacks and do not get poisoned. I have a similar video with an attempt on SMN where I noticed that I was not being poisoned (can upload it if you would like to see it lmk). The wiki indicates that they should poison with each RA.

Video link (it's unlisted): btw this is just a hilarious watch if you have 1:51 to spare. Tried RDM/SMN and died while frantically trying to get the treat staff warp instead of dying lol

[https://www.youtube.com/watch?v=lm72dVq3Jfk](https://www.youtube.com/watch?v=lm72dVq3Jfk)

/ver 30181205_0

Steps to recreate: Load up ToAU31, tank a few RAs to check for poison chance, die to check exp loss.

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
