### ISSUE TITLE
Nyzul Isle Investigations Floor objectives should not repeat back to back

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#5056]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

There are 6 types of floors.
Eliminate Specified Enemy (single random Impossible to gauge mob)
Eliminate Specified Enemies (Group of ToAU Impossible to gauge mobs, certain families)
Eliminate Enemy Leader
Eliminate All Enemies
Free Floor
Activate All Lamps (Can be Code, Same Time, or Order)
Any floor besides free can have do not destroy gears or avoid discovery from gears.

You can't get the same objective back to back in my experience on retail (I just finished getting 150k tokens on retail for a mythic). I did not see a single repeat floor. I did see 2 avoid discovery floors in a row, Floor 7 was eliminate all enemies avoid discovery and floor 8 was eliminate enemy leader avoid discovery so those can be back to back.

**Comment by bliven-was-taken** [comment]
If it's really needed I can try to compile my chat logs showing all the floors I got but that would take quite awhile to do.

**Comment by statuseffect** [comment]
Just did a 20 boss run and got Lamps x4

**Comment by KnowOne134** [comment]
Question since you have logs, can same groupings of mobs pop back to back? 
Also lamps is considered 1 objective with sub objective correct? Can't have order on 1 floor and register on another?

**Comment by bliven-was-taken** [comment]
Correct for 2nd question. I never saw 2 lamp floors in a row even if the sub objectives are different. 
Here's a list of a lot of the floors I got. 
[Nyzul floors.txt](https://github.com/EdenServer/community/files/8882747/Nyzul.floors.txt)

For the first question, I feel like I saw the same mob grouping back to back but I honestly am not sure and my data isn't the best for that because quite often I was just standing at the lamp taking us up so there were a lot of floors I never saw the enemies on.

**Comment by statuseffect** [comment]
Too add to our run, on our first 2  lamp floors they were both same time and after the teleport up to the second same time lamp floor they were on "cool down" as if we failed to activate them at the same time. "You must wait a while to use."

**Comment by KnowOne134** [comment]
Resolved 7/8/2022 update
