### ISSUE TITLE
intruder earring not converting MP to HP

### ISSUE THREAD

**Issue by ProtomanEXE** [EdenServer/community#5058]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- x ] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Location is the Phonmiuna Aqueducts. I am waring the intruder earring in a location that is not controlled by my nation. With the effect of that earring I should have 40 MP converted to HP. it is currently controlled by beastmen.  my character is a dragoon yes but I have MP merits as you can see. I have provided a picture with the earring on and off to show no MP to HP change has happened.

earring on https://gyazo.com/2aa178a9a5e023ad928142895a6c0bf7

earring off https://gyazo.com/5d6c8838e6028f170690a97c85f93244

ver and proof of beastmen controlled area https://gyazo.com/d4623258cbf671358d0cded1f0c7cdc4

**Comment by MalteseFalcon** [comment]
Do you have signet?

**Comment by Mozzy4Ever** [comment]
Worked fine for me so long as I had signet, which is a requirement for those sort of items.

**Comment by ProtomanEXE** [comment]
I believe I did but I should have screenshotted the whole thing. Sanction that is... Possibly wore off when I noticed this effect. I apologize.

**Comment by 59blargedy** [comment]
gonna close bc my guess is you did not have signet on, but feel free to reopen if not the case
