### ISSUE TITLE
Davoi Coffer Chest Doesn't open

### ISSUE THREAD

**Issue by ThoseWhoFight** [EdenServer/community#5059]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Attempted picking with a Living key, someone else apparently tried using the actual coffer key a day or two prior. Neither work, inventory had plenty of space. No animation played, nor sound effect, no dialogue in text box. Doesn't seem to move at all either after a long period of time (hours). Re-attempted after zoning/logging out hours later to no avail. Unable to progress on AF quests

ver 30181205_0

**Comment by ThoseWhoFight** [comment]
This is specifically in Monastic Cavern btw, in case that wasn't known already.

**Comment by 59blargedy** [comment]
If they haven't already, have them file a gm ticket for short term so that
they're not stuck.

**Comment by KnowOne134** [comment]
It is handled and can go back. Working on a solution as issue is dying while trading a key nils either the animation or the messaging on the timer

**Comment by KnowOne134** [comment]
Has been fixed
