### ISSUE TITLE
Fishing - Missreading rod type when catching fish.

### ISSUE THREAD

**Issue by Vanellope-DonutRibs** [EdenServer/community#506]
Bastore Sardine - Clothespole/Sabiki Rig. Pretty good setup normally, and before the fishing patch was getting Bastore Sardines at a very nice rate. Now I might get 1 sardine every 10-15 minutes. An error message comes up now that states "You lost your catch. Whatever caught the hook was too small to catch with rod". This error message is normally associated with using rods that are not suitable for the fish you are trying to catch. When it comes to Bastore Sardine the only message you are supposed to get this with is "Single hook fishing rod". I know it's a Bastore Sardine because when you get Fishing Instincts it tells you what fish it is. I routinely lose Bastore Sardines while in Instinct mode.  I also get this message with other fish too, namely Cheval Salmon. I am trying other fish, but all the results seem to be the same. I made a mention of this on Discord, but felt I should just put it here too.

**Comment by Setz0r** [comment]
Catching small fish with a "large" type rod will result in randomly losing it due to being too small for the rod.  large type rods are: Single Hook, Mithran, Composite, Clothespole.  This was not functioning properly pre-update.

**Comment by Setz0r** [comment]
Because large rods have a much higher durability over small ones, the counterbalance is to make small fish harder to catch with them.

**Comment by Vanellope-DonutRibs** [comment]
Ah sorry then. I seem to have misunderstood the guides in relation to how rods function on FFXI. I'm very new to Fishing and I did ask someone for advice on this very subject before I posted this. https://ffxiclopedia.fandom.com/wiki/Bastore_Sardine Seemed to indicate that clothespole was never affected by "the fish may be too small" message.
