### ISSUE TITLE
Ebony Pudding Drain Through Fresh (Capped) Stoneskin

### ISSUE THREAD

**Issue by Deirdre5017** [EdenServer/community#5060]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

When soloing ebony puddings on black mage, a pudding drained me for 185 HP through a fresh stoneskin. My stoneskin gearset swaps in the exact mind needed to hit 350 damage absorbed (114 mind at 200 enhancing magic skill) but the drain didn't seem to even register the stoneskin since it did drained HP but stoneskin didn't drop afterwards. Unless it was a 535 hp drain (350 absorbed by stoneskin plus the 185 hp drained), it should have registered in the chat log as 0 hp drained given that the stoneskin remained up. 

Here's a screenshot of the chat log which shows the stoneskin being freshly cast then the drain showing as absorbing HP:

![Drain Screenshot](https://user-images.githubusercontent.com/73006091/168491436-b5d1a364-89fb-4bb9-8f81-d66e6620279a.png)

Also a screenshot from Discord a few years ago where Setzor is discussing basically this exact scenario.

![Setzor drain discussion](https://user-images.githubusercontent.com/73006091/168491450-3477c80b-8728-4cb8-bf25-4760d71138ed.png)

[Wiki entry in era - "A Stoneskin effect has a certain number of 'hit points' that it absorbs damage with, and it wears off once this number reaches zero."](https://ffxiclopedia.fandom.com/wiki/Stoneskin_(Status_Effect)?oldid=634761)

[Another Stoneskin era entry ](https://www.bg-wiki.com/index.php?title=Stoneskin&oldid=54579)

**Comment by LahaEden** [comment]
Any possibility you had a dot or multiple eating away at the fresh SS, 30 seconds elapsed from fresh SS > aggro. Knowing that camp its worth asking.

**Comment by Deirdre5017** [comment]
I can't definitively say I didn't have a dot up but I'm 95% certain I
didn't. But the stoneskin was still up after the drain hp came through,
which is my main reason for bug reporting (which, of course, I didn't get a
larger screenshot to show the stoneskin icon still there or that it didn't
drop in chat log because I was midfight and it confused me haha). I'll try
to murder some more this weekend without blink to see if I can recreate the
draining for hp without dropping stoneskin. My understanding is it should
have reflected 0 hp drained in chat log (or just a smaller amount of hp
drained if it broke stoneskin). I also wasn't watching the puddings hp bar
closely enough to be able to verify if it gained the hp reflected in the
chat log or not. I'll report back after more testing!

**Comment by Steam-arch** [comment]
![image](https://user-images.githubusercontent.com/69089249/169499225-130f53cc-6ebb-443a-920e-2a659e7936bd.png)

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
