### ISSUE TITLE
Ranger AF weapon quest

### ISSUE THREAD

**Issue by elthann** [EdenServer/community#5061]
### Checklist
 
     Ranger AF weapon quest ??? not showing during Full-moon 

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by KnowOne134** [comment]
Corrected 6/11/2022 update
