### ISSUE TITLE
Inhibitor seems to be giving OOE Store TP values

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5063]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Inhibitor was changed in a 2011 patch to have increased values of store TP. Eden matches these Store TP values but should have the era values.

https://www.bg-wiki.com/ffxi/Version_Update_(12/14/2011)

The simplest place to see the correct era values is the history section of the jpwiki:

![image](https://user-images.githubusercontent.com/13668758/168811322-442b2ef2-6fab-4fd7-8daa-778d5fa79d60.png)

But the same can be validate on ffxiclopedia and bgwiki

Era
https://ffxiclopedia.fandom.com/wiki/Inhibitor?oldid=597722

After 2011 Patch
https://ffxiclopedia.fandom.com/wiki/Inhibitor?oldid=1389077

Era
https://www.bg-wiki.com/index.php?title=Inhibitor&oldid=73397

Modern
https://www.bg-wiki.com/ffxi/Inhibitor

Validation on the test server shows 93 TP gained w/ no Inihbitor
97 with Inhibitor
106 w/ Inhibitor + 1 fire
116 w/ Inhibitor + 2 fire
130 w/ Inhibitor + 3 fire

Store TP of 40 means +40% TP gain, and 93 (our base) x 1.4 = 130, so this checks out as the OOE version.

version 20181205_0

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
