### ISSUE TITLE
Jailer of Prudence with mouth open hits too hard

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#5066]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Prudence when open mouth on Eden currently hit's significantly too hard, from what I can eyeball it hits about 2x harder than it should. 

Testing on Eden with a nearly BiS blood tank Paladin (894 defense, -22% PDT):
150-244 non blocked hits, I'd say eyeballed average of 200.
60-90 blocked hits, I'd say eyeballed average of 70.

Looking at this video from 2009 (Around the same defense values, zero PDT) https://www.youtube.com/watch?v=GkNsfh2newA
Eyeballed average hit for 110.
Eyeballed average block in the 30s.

This is another much worse video that I feel like I can barely make out a VERY badly geared paladin taking pretty low damage on Prudence also. https://www.youtube.com/watch?v=73MlPoaCT4Y
Another supporting video of a Paladin taking very low damage from Prudence compared to what I was getting on Eden.
https://www.youtube.com/watch?v=8eMMCf3-aRw

**Comment by Steam-arch** [comment]
Im pretty sure its attack power doesnt increase with mouth open mode but instead it just gets a very higher triple attack rate and flee is removed.

For once theres actually good eraish videos for this and /war tanking and once the other one dies, the damage doesnt really spike up:
https://m.youtube.com/watch?v=GkNsfh2newA
https://m.youtube.com/watch?v=8eMMCf3-aRw

An era post (I didnt save link this time sorry) says the advantages of mouth closed form is "it moves with flee speed but attacks are weaker and triple attacks less", If the normal sea dolphins do attack with 2x damage in mouth open form, maybe prudences mouth open form was just balanced abit more so your average ffxi player wouldnt get rammed open by it. 

Not an era vid but I think you can see a high (I think ?) triple attack increase after one of them dies at 4:00
https://www.youtube.com/watch?v=7xPGzcjMwGM
unfortunately he took logs off just before mouth open form but can watch the animations.


Only 2 hits but can also see its attack power not doubling here with 2 autos:
https://www.youtube.com/watch?v=ajwEay47-xM

1 mouth mode damage:
![image](https://user-images.githubusercontent.com/69089249/170687893-df63d0aa-4902-40fc-a47f-977ecb32020f.png)

open mouth mode damage:
![image](https://user-images.githubusercontent.com/69089249/170687999-3f89b4d0-423d-436d-91d8-2bd55b4c3dac.png)
(only got 2 autos off in open mouth mode)

You can see the damage not doubling in the longer era videos. Im more or less convinced its just a big triple attack % increase when it gets to mouth open mode.

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
