### ISSUE TITLE
Stroper Chyme

### ISSUE THREAD

**Issue by SleazyFFXI** [EdenServer/community#507]
There should be 4 that spawn in Ordelle's Caves but there's only 2

**Comment by Aneyus** [comment]
As far as I'm aware there's only ever been two Stroper Chyme spawns. Where are you finding this information?

**Comment by SleazyFFXI** [comment]
Wiki from entries in early 2007

**Comment by godmode** [comment]
This is true, the open areas where you drop down should also include 1 per area. Right now they are high level camps (although the mobs have been lowered) Sleazy do you know the other mobs that should be there? I was waiting for that to fix this.

**Comment by SleazyFFXI** [comment]
I do not :(

**Comment by Aneyus** [comment]
Just looked into it more and 4 spawns does in fact sound correct. I had thought that there were 4 spawn locations but only 2 actual mob spawns for some reason.

**Comment by beitlich** [comment]
Curious as to why this was moved to out of era? Any way this could possibly be looked at again to be fixed?

**Comment by godmode** [comment]
The label is kind of useless to players just a way to organize internally. It will be fixed. If you’d like to see it in sooner and have some screenshots of the area. Like how many mobs were there and of what type that’ll speed things up

**Comment by HunnyDoo** [comment]
Stroper Chyme respawn time is 13 mins 30 seconds. Appears to be different from other mobs in the zone.

**Comment by SleazyFFXI** [comment]
Why hasn't this been fixed yet?   There's still only 2

**Comment by godmode** [comment]
For the same reason I mentioned above.
