### ISSUE TITLE
Amethyst Quadav combat ai

### ISSUE THREAD

**Issue by Raulfin** [EdenServer/community#5071]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0
Was fighting an Amethyst Quadav in North Gustaburg and when it got to about 30% it started to cast Cure on a nearby Amber Quadav, that wasn't in combat, instead of itself. Not sure how combat ai's are set up in XI kinda wondering now though as i've never seen other whm mobs do this.

chat log:
https://imgur.com/a/j1Y9AHB

**Comment by 59blargedy** [comment]
there's another ticket that covers this - basically mob allegiance whether quadav or another mob is a little funky still, just happens that both examples are quadavs
https://github.com/EdenServer/community/issues/3397
