### ISSUE TITLE
BLU AF has no waits

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5072]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Atm the BLU AF quests have no wait times coded at all. Was able to just spam through all of them in a single game day

**Comment by Spintimalli** [comment]
This wasn't the case for me so far. I started and finished Omens yesterday, and wasn't able to pick up the next quest from Waoud.

**Comment by Mozzy4Ever** [comment]
I did have to wait until next game day to proceed with Transformations though? I was able to start it immediately upon finishing Omens, but couldn't get the CS at the Imperial Whitegate door. Not sure if it actually was a "next game day" wait though. Might've been just needing to zone?

**Comment by Spintimalli** [comment]
Wiki says needing to zone as well as JP midnight in era. I started transformations today and got 1 of the AF crafted, and was not able to start the next one in the same in game day. Too tired to wait for the next but i can check before JP midnight tomorrow.

**Comment by Mozzy4Ever** [comment]
I moreso mean the waits required during "Beginnings", before starting "Omens", and before starting "Transformations". I haven't gotten to the additional AF portion of Transformations yet

**Comment by Spintimalli** [comment]
I can't go back and see for that one since i'm past it now, but as for the 3 piece crafting, I looked at the history on it and here are the conditions:

> You must zone and wait one game day after trading the synthesis items to [Lathuya](https://ffxiclopedia.fandom.com/wiki/Lathuya) to receive your reward.
>You must wait past Japanese midnight before ordering another piece of equipment from [Lathuya](https://ffxiclopedia.fandom.com/wiki/Lathuya).

I turned in the crafting materials and just waited by Lathuya till the next in-game day and got the armor piece without needing to zone or wait till JPM. I wasn't able to immediately start the next item though. I will check the next in-game day.

**Comment by Spintimalli** [comment]
Update: Was able to collect all 3 pieces in 5-6 in-game days. Once I obtained all 3, talking to Lathuya again has no response, and you can't move untill you cancel out of it.

**Comment by KnowOne134** [comment]
Was resolved in 5/3/2023 update
