### ISSUE TITLE
Khimaira resists enfeebles too much

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#5073]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Khimaira currently resists enfeebles more than it should based upon evidence found in old videos/posts from 2007-2009. I included videos I found from 2008/2009 because of the difficulty in finding anything from that era + the players in the videos were using basically the same gear we have now, if not worse. On on our khim fights, we usually have multiple rdm/blms casting enfeebles. To use one specific kill as an example, Zoti + Setsutaru with 5/5 earth accuracy, 5/5 slow2, and earth threnody and nearly perfect gear could barely land slow2 on Khim. I also used a goblin mushpot (+10 mnd food) just to see if it would even help. Zoti did not use a food, and we were both casting over and over and over again without luck a lot of the time. Also in one of the videos I posted below, the LS never had to use earth threnody to land slow. They used ice threnody for the BLMs nuking, which suggests they didn't have issues getting slow on. Landing paralyze II on eden is also nearly impossible. 

In era videos and strategy posts, I've found players talking about letting RDMs sj DRK to handle stuns and letting the WHMs be the ones to handle slow. While the posts mention that BRDs should SJ BLM for elemental seal and recast as much as necessary to land elegy, there's little mention of this ever being an issue with slow2. I get that slow 2 was supposed to have some higher resistance than other HNMs, but there is nothing I can find that suggests fully merited and well geared RDMs should have the difficulty that we are currently having on Eden. Also, though this is anecdotal, I asked some friends from BG about old fights and they stated that well geared, fully merited RDMs should not have this kind of difficulty. I realize there were some captures done on Khimaira at some point, but with the way khim is now on eden, it simply does not line up with anything I find from era. I also note that in the old videos you can frequently see paralyze landing and/or procing, whereas on Eden we basically can't land paralyze II unless we just get really lucky. Our ESs always have to be saved for slow2. 

Additionally, era videos show that Khimaira could be bound. On Eden, it will provide the "completely resists" message. 

https://youtu.be/DS8V87J6SpU 
Dec. 2008, Fair server
0:32- NIN lands hojo: ichi
2:23- NIN lands bind (“Khimaira is bound.” Msg viewable in log)
4:36- NIN lands bind again

https://youtu.be/3xOKhaEh8MU
July 2009, Phoenix server
0:09- can see paralysis proc on khim in log
1:02- RDM casts paralyze II and lands it first cast
1:19- RDM lands poison II on first cast
2:20- RDM lands poison II again
2:37- RDM lands slow II

https://youtu.be/uEUNC05Kad8
May 2007, Shiva server
1:05- blurry log but can see other people pull hate and khim draw in a couple of times
2:06- again, blurry but can see paralyze II land (had to rewatch a few times to make it out since it scrolls fast)
Note: Khimaira appears to be slowed/elegy’d throughout the entire video, tho it skips around and hate is wonky at times. However you can tell by the attack speed that it is not eating the pld’s asses

https://youtu.be/KdlLnztQkRc
March 2008, Quetzalcoatl
Note- Can tell from start of video that Khim is already slowed, not attacking fast as a mfer

https://www.bluegartr.com/threads/49889-Strategy-s-to-fighting-Tiamat-khimaira
^Thread talks about having whms use ES slow if rdms are on stun duty. Thread generally says brds should /blm for ES elegy but doesn’t talk about slow being super difficult to land.

https://kanican.livejournal.com/tag/hnm%20fights!
^ LS’s setup only used one rdm/blm and one rdm/drk. Mentions that slow can be difficult to land, but compared it to Cerberus. On Eden, Khim is much more difficult to debuff than Cerberus. This post mentions BRDs having to spam elegy but no mention of Slow2 being equally as difficult to land and having to be spammed. Also mentions a NIN could probably solo tank a khim pretty easily if slow2/elegy are both on, which is never the case on eden.

**Comment by 59blargedy** [comment]
this will feel like a mixed bag, but artificial resists were removed in favor of retail tested sdt values. failures will still occur (as evidenced by the guy in the vid casting paralyze 2 four times in a row) but should feel accurate now. resolved in November 21, 2022 update
