### ISSUE TITLE
Buffs cast in the uncapped areas of promyvions dont wear if you rezone into level capped area

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5079]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently buffs that are cast in the uncapped area (next to boss doors) of promyvion dem/holla/mea (might be vahzl too), dont wear upon rezoning back into the lvl 30 capped area.

**Comment by 59blargedy** [comment]
resolved in July 8, 2022 update
