### ISSUE TITLE
Bilis Leech

### ISSUE THREAD

**Issue by SleazyFFXI** [EdenServer/community#508]
Bilis Leech's shouldn't be in game but the area of G-11/12 in Ordelle's Caves there's a bunch

**Comment by Aneyus** [comment]
The names can't be fixed without a .dat change which I think is intended for a future version of the Eden installer, but the mobs should otherwise behave like their normal era counterparts in the meantime.

**Comment by godmode** [comment]
We can put them on our renamer list for a temporary fix next time we have a patch to adjust mobs

**Comment by 59blargedy** [comment]
looks like this was resolved a while ago with a renamer update, as i cant spot any bilis leeches
