### ISSUE TITLE
Lure of the Wildcat (Jeuno) progress prevented by Luto Mewrilah (begins quest: Unlisted Qualities)

### ISSUE THREAD

**Issue by LazarusKai** [EdenServer/community#5083]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

Recently tried to do the Lure of the Wildcat (Jeuno) quest on my alt and ran into an issue where when talking to Luto Mewrilah (having not previously talked to Luto at all, and not having the adventuring fellow quest started before flagging Lure of the Wildcat) would cause her to flag the adventuring fellow questline and prevent the badge flashing dialogue from happening. I even completed the first quest in the adv fellow series and attempted to get the badge flashing dialogue before rezoning (which allows Luto to flag the nest quest in the line) and no dice. 

My alt was already a mercenary at this point in time and had completed only one other Lure of the Wildcat quest: San d'Oria.

While I don't have video/picture/forum evidence, there is nothing on the wikis or from a cursory google search (that I could tell) that mentions her preventing this dialogue from happening if you haven't completed the adv. fellow line yet.

**Comment by ConteAlmaviva** [comment]
Nothing to add here, just confirming I ran into the same issue. I did the same, completed first NPC quest, but no luck getting the Lure of the Wildcat dialogue.

**Comment by ConteAlmaviva** [comment]
Small update - I was finally able to get the Lure of the Wildcat dialogue from Luto after completing the third NPC quest Mirror, Mirror (BCNM fight in Ghelsba that gives you the Signal Pearl).

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
