### ISSUE TITLE
Aquarius Hits too soft + missing enwater

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5085]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Hits around 75 zero PDT (no bb on either) on protect II mnk 75
![image](https://user-images.githubusercontent.com/69089249/170791689-2b3831f2-73e5-4f4f-9508-a7cbe9b81cd0.png)

Era damages on no protect mnk 75 (no idea what food)
![image](https://user-images.githubusercontent.com/69089249/170791762-2fe39530-d72b-4584-be3b-971702df2b09.png)
![image](https://user-images.githubusercontent.com/69089249/170791787-e22c2074-4117-4d52-9c1c-f409cf3010c8.png)

hits around  85-125 on protect IV af pld 75 (no idea what food)
![image](https://user-images.githubusercontent.com/69089249/170792060-983e99fe-eb0f-4c2e-95b0-ca15df9b15b0.png)
![image](https://user-images.githubusercontent.com/69089249/170792369-f19390db-c89f-4dc6-bdf9-e88d401a1aec.png)

enwater 21-28 damage (with shell III or shell IV)
![image](https://user-images.githubusercontent.com/69089249/170792048-82db0523-95be-48b9-a463-e101070d7d63.png)

Enwater around ~30% proc rate:
https://www.youtube.com/watch?v=q2VU9dETHaQ

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
