### ISSUE TITLE
Aquarius defence too low

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5086]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Defence is very low on eden. Should be much much higher. All damages below without crab defence tp move.

full eva destroyers mnk hitting aquarius ( The [2] infront of bigger damage numbers means two attacks so a h2h attack round):
![image](https://user-images.githubusercontent.com/69089249/170794719-51c8436e-8831-4152-b94f-4816acfc9c79.png)

eden pld hitting aquarius ( [2] infront of bigger damage numbers means two attacks:
![image](https://user-images.githubusercontent.com/69089249/170794446-f8f55b9f-c105-4cc4-a4eb-09030acdbfc8.png)

similar gear era pld hitting aquarius :
![image](https://user-images.githubusercontent.com/69089249/170794506-b09806a4-8d29-4586-b130-6324361bc771.png)
![image](https://user-images.githubusercontent.com/69089249/170794565-301e365b-bf79-467d-98b5-b171927c5a0d.png)
source: https://www.youtube.com/watch?v=5M79QIxDT28

other pld:
![image](https://user-images.githubusercontent.com/69089249/170794897-309e8ba4-8282-48ee-af9a-1d326b10f5c3.png)
![image](https://user-images.githubusercontent.com/69089249/170794925-fece25b4-4f74-4952-ac91-38b52853c73b.png)
source: https://www.youtube.com/watch?v=q2VU9dETHaQ&t=33s

Eva hades sainti mnk hitting aquarius:
![image](https://user-images.githubusercontent.com/69089249/170794614-98a3e659-d365-402d-a8e7-9fb0de8c68b2.png)
source: https://www.youtube.com/watch?v=7uY2_hBC1mc&t=163s

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
