### ISSUE TITLE
Aquarius missing poison immunity

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5087]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

missing poison immunity.
![image](https://user-images.githubusercontent.com/69089249/170795489-a880db96-61ba-4e72-8bb2-97bc52544f85.png)

clopedia wiki:
![image](https://user-images.githubusercontent.com/69089249/170795471-d89081e4-04c2-4f2d-9293-a2ea5936e2f6.png)
![image](https://user-images.githubusercontent.com/69089249/170795499-8580ef12-0711-4435-8b4c-4d3e44cf9cdb.png)

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
