### ISSUE TITLE
Mamool Ja Mob Size

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#5092]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently Mamool Ja mobs are smaller than they should be. They should all be larger. Pics below with bonus Bambino for scale.

Retail:
![image](https://user-images.githubusercontent.com/46270382/171201189-b653e6c6-02f8-4046-bbe8-5fa5be156ce2.png)

Eden:
![image](https://user-images.githubusercontent.com/46270382/171201222-6f985306-781a-4314-b134-95ea98cc957a.png)

version 30181205_0

**Comment by Raulfin** [comment]
Kinda hard to really tell the actual diff with these 2 pics. They are at different vertical and horizontal angles from both targets, one has the mob a bit up a hill. Yeah it does look like there is some difference is just hard to see what that difference actually is.

**Comment by FariskaEden** [comment]
Some more retail screenshots of it.
![image](https://user-images.githubusercontent.com/46270382/171461828-dff4373f-7f51-4ae1-a467-9d4937184087.png)
![image](https://user-images.githubusercontent.com/46270382/171461849-dbd76fc6-e727-4f6d-9e62-19579331fdee.png)
![image](https://user-images.githubusercontent.com/46270382/171461885-ac66c0c1-6dcc-45f3-9167-133290b56149.png)
![image](https://user-images.githubusercontent.com/46270382/171461909-2761171d-4aa3-4ac8-a22d-8c4de38e10d0.png)

**Comment by 59blargedy** [comment]
resolved in July 8, 2022 update
