### ISSUE TITLE
Gugru Orobon doesn't drop Orobon Lure when you break its lure

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5093]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Gugru Orobon should drop an Orobon Lure 100% of the time if you break its lure. I killed it 3 times (including /THF, not that this should matter), breaking its lure each time, and haven't gotten a lure yet.

To reproduce, fish up a Gugru Orobon on the boat connecting Mhuara to Al Zahbi and break its lure (I did it with a crit), observe no lure drop on kill. To fish one up, use any rod with a Minnow as bait. I used a Single Hook / Clothespole.

https://ffxiclopedia.fandom.com/wiki/Gugru_Orobon

https://www.ffxiah.com/item/2154/orobon-lure

"Will only drop if you break the Orobon's lantern, which makes it a guaranteed drop. If farming these in bulk, use lots of crit and multi-attack gear and Lilisette II trust (orient the enemy so that she attacks the face). A great spot to farm them is I-11 in Foret de Hennetiel."

![image](https://user-images.githubusercontent.com/13668758/171255262-13b490bb-da43-478f-add9-0c4ff4bc3e91.png)
![image](https://user-images.githubusercontent.com/13668758/171255274-544e35d2-d767-4f9d-a8df-83cbccf4c3b5.png)

version 30181205_0

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
