### ISSUE TITLE
Kingslayer Doggvdegg NM has incorrect job

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5095]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

In Central Temenos - 4th Floor, our boi Kingslayer Doggvdegg has a chance to pop from one of the Armoury Crates.

Right now on Eden, I did not see him cast any spells and he used Mighty Strikes, indicating he is currently a WAR:
![image](https://user-images.githubusercontent.com/95725249/171474620-c76f55bc-2df2-4cf6-84ad-82afa928bd27.png)

FFXIclopedia indicates that he should be a PLD and use Invincible at some point:
https://ffxiclopedia.fandom.com/wiki/Kingslayer_Doggvdegg?oldid=863744

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
