### ISSUE TITLE
The Sanctuary of Zi'Tah - Goblin's Leech Level / Model

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#5096]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I think currently the level range of these pets may be incorrect. Wiki has them listed as being 35-40 but they seem to currently range from 35-42. On retail they looked to range from 35-37. Also another thing is the model of these pet leeches is incorrect, they should be blue like the other leeches in the zone.

![image](https://user-images.githubusercontent.com/46270382/171529295-785c95a5-169e-4edd-a81f-29db21598e2d.png)
![image](https://user-images.githubusercontent.com/46270382/171529314-f4b1bff4-1179-40b1-8129-7807d7717c34.png)
![image](https://user-images.githubusercontent.com/46270382/171529435-c8ba18fd-2986-47a1-8604-49722832699b.png)

version 30181205_0

**Comment by 59blargedy** [comment]
Resolved in June 13, 2022 update.
