### ISSUE TITLE
Outpost NPC not giving me Signet

### ISSUE THREAD

**Issue by uparapa** [EdenServer/community#5098]
![Upa_2022 06 03_120247](https://user-images.githubusercontent.com/106829134/171904588-4eb57f60-b720-4445-8d9c-087f39bb43b6.png)
![Upa_2022 06 03_120255](https://user-images.githubusercontent.com/106829134/171904598-3dabce02-e66f-4c35-92b9-ca29ed7c7485.png)
![Upa_2022 06 03_120404](https://user-images.githubusercontent.com/106829134/171904600-a6b77f7c-d0ce-48b2-bb16-c61b392bc07e.png)
I am Sandorian and not able to get signet from OP that is owned by San Doria. ### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by uparapa** [comment]
Not able to get signet from West Ronafaure or Qufim Island which were under San Doria conquest.

**Comment by bliven-was-taken** [comment]
Already bug reported if you had followed the template. You need to spend your ring key item from the tutorial quest.

**Comment by uparapa** [comment]
Can i just throw the item away?

**Comment by bliven-was-taken** [comment]
You can use up your emp ring and instead of charging it for the week you just drop it and use the key item to buy a free new one. It's a key item so you can't drop it.

**Comment by uparapa** [comment]
Thanks Bliven for the help. Closing the issue.
