### ISSUE TITLE
SMN Job Ability Apogee

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#51]
Out of Era; should not be in.

Apogee

Job Ability
Eliminates the recast time on the next blood pact, but causes it to consume more MP.
Obtained: Summoner Level 70
Recast Time: 3 minutes
Duration: 60 seconds

**Comment by godmode** [comment]
When was this added in retail?

**Comment by Treble011** [comment]
http://forum.square-enix.com/ffxi/threads/44539-dev1235-Job-Adjustments

September 30th, 2014, same patch that Atomos was released. I attached the full patch note. This patch also saw THF dagger skill going from A > A+, BST axe skill A > A+, and PUP h2h skill going B+ > A+
