### ISSUE TITLE
Bodach not taking extra blunt damage?

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#510]
Asuran Fists NM Bodach felt like he wasn't taking extra damage from my MNK, he's a skeleton. He's an NM though so /shrug

**Comment by gweivyth** [comment]
Definitely makes this a much longer fight.  We had 2 blunt damage dealers when I did it, (me on MNK, Chlorr on WHM/NIN with Kraken) and the fight took FOREVER.  You'd think with what we had we would have shredded it, but he has a lot of HP and the bonus for blunt not working was very obvious.

**Comment by godmode** [comment]
You guys tested other weapons to make it obvious that blunt wasn’t working?

**Comment by gweivyth** [comment]
I can go try it again tonight, I'll see if I can find someone to pop it for me.  With our setup that we had we only had Club and H2H available but I can go try it out on THF this time, that way I'll have slashing, piercing, and blunt available.

**Comment by 59blargedy** [comment]
resistances go by https://www.bg-wiki.com/bg/Category:Skeleton
skeletons take 1.125 from h2h and 1.25 from blunt, so it may have been too marginal too notice.
