### ISSUE TITLE
mobs extra dmg from atonement

### ISSUE THREAD

**Issue by 59blargedy** [EdenServer/community#5100]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Khimaira appears to be taking 870 dmg from atonement at certain points in the fight. effect does not seem to happen on other mobs (or at least it hasnt been reported). potentially the issue occurs below a certain hp percentage but hard to say from limited reports. 
this seems to occur regardless of weapon type, from joyeuse to excal. 
atonement should cap at 750 damage with no exceptions other than cerberus

**Comment by Steam-arch** [comment]
![image](https://user-images.githubusercontent.com/69089249/174845215-6b2a8fa4-06dc-465d-8490-51c7b81cee4c.png)
Just updating that happens on other mobs also. Was thunderday.

**Comment by 59blargedy** [comment]
resolved by another dev in November 21, 2022 update
