### ISSUE TITLE
Beastmen Puppetmasters should only summon automatons every 20 minutes

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5102]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Beastmen Puppetmasters seem to be on the same resummon cycle as Beastmen Beastmasters. According to the monster pet page on ffxiclopedia, they should be on the 20 min cycle similar to a dragoon.

"Beastmaster and Summoner monsters re-summon their pets approximately 2-3 minutes after they are killed, and have no known limit to the number of pets which can be summoned. Dragoon and Puppetmaster monsters, however, can only summon their pets every 20 minutes, which tends to discourage hunters to use them as potential prey due to the long wait time in-between the summons."

https://ffxiclopedia.fandom.com/wiki/Category:Monster_Pets

Unfortunately I think this probably requires retail validation or a secondary source, that says something one way or another, but I'm unavailable to find a second source.

version 30181205_0

**Comment by 59blargedy** [comment]
looks like retail now is the shorter time frame, and i cant find anything to support longer pops for autos, just tons of data about the longer pops for wyverns. my assumption is that this was assumed based on the 20 minute cooldown for activate, similar to call wyvern, but mob pups dont actually use activate
