### ISSUE TITLE
Antican Pauldron drop rate too high

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5105]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver = 30181205_0

Antican Auxiliarius in Eastern Altepa Desert have too high of a drop rate of Antican Pauldrons (Desynth'd to make Darksteel Ingots for pick vendoring). Should be a base 10% (18% w/ TH4) according to http://www.ffxidb.com/zones/114/antican-auxiliarius, is currently base 15% (45% w/ TH4)

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
