### ISSUE TITLE
Toadal Recall BC30 issues

### ISSUE THREAD

**Issue by LahaEden** [EdenServer/community#5106]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Unfortunately i do not have screenshots.

*to satisfy the second item of the checklist simply try and defeat the bcnm. Specifically while kiting some frogshrooms*
https://ffxiclopedia.fandom.com/wiki/Toadal_Recall?oldid=469522      **<-- Wiki page**     According to that wiki page from March 2008, each frogshroom is supposed have certain tp moves unique to itself. Currently they all seem have access to everything barring frogkick.(i think that one is exclusive to toadpillow as it should be) The rest can all use dark spore and silence gas at will. Also they appear to have some sort of regain which isnt mentioned and the mechanic regarding the mushrooms on their respective heads regrowing seems nonexistent. Lastly, we didnt get extensive information regarding this final issue but there is something wrong with their collective hate as it appears they do not share aggro.  Also a thing that could be worth mentioning is the range on dark spore and silence gas seems to be quite far. im not saying too far, however i cant find any info regarding its range.

**Comment by 59blargedy** [comment]
do you have logs of any kind?
individual moves are coded
they have regain when caps are on, that's how the moves are used
silence gas is at least 18 from capture
heads do regrow
cannot replicate your issues so full info (jobs used, did you stun, what preceded the first wrong tp move, etc) will help determine what broke down in your run.

**Comment by Frozzen907** [comment]
I don't have screenshots from the runs we did.. But i do have saved text logs... If that helps at all..

**Comment by Frozzen907** [comment]
[Frozzen_2022.06.09_toadal_recall.log](https://github.com/EdenServer/community/files/8885683/Frozzen_2022.06.09_toadal_recall.log)
^ My Text logs from that day, just saved the section from all the Toadal Recall BCNM Runs we did that day; if you want my full text file of the 24h that day i can post that too.. lol, just figured it was easier to pull out the bcnm section so you didnt have to browse through 24h of text.

**Comment by 59blargedy** [comment]
lol yeah just the fight is helpful, thanks for taking the time to do that.

**Comment by 59blargedy** [comment]
honestly this is mystifying to me but a check was added to see if it resolves the issue in June 13, 2022 update. did not note in patch notes bc legit this should not happen even with old code, but more stuff in place now to prevent this issue, potentially. leaving ticket up for further reports.

**Comment by 59blargedy** [comment]
resolved in July 8, 2022 update
