### ISSUE TITLE
Mandragora family jug pets are only attacking once

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5109]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Mandragora pets should attack twice like a standard Mandragora/Monk. Below are screenshots from Eden showing the single attacks with long delays.

![image](https://user-images.githubusercontent.com/13668758/173359175-747e98bf-1b1f-42a5-af1f-271ae62b2b0e.png)

![image](https://user-images.githubusercontent.com/13668758/173359470-f1efe5e0-a416-4f5d-b4bf-2f28f21042d3.png)

![image](https://user-images.githubusercontent.com/13668758/173359999-2b353e53-df5e-4fd1-816e-e5285c871634.png)

Here is an era video showing the Homunculus doing two attacks per round.

https://www.youtube.com/watch?v=3ov_wkNjv-8

Note that in this other era video, the tiger/funguar jug is hitting roughly twice as hard as a single mandy hit (if not even harder for the funguar). Just mentioning this since its not like the mandy should just deal 2x damage.

https://www.youtube.com/watch?v=6RoFWQs40f4&t=3s
https://www.youtube.com/watch?v=i7c_SXLPUMA

And finally here are some pictures from the jug pet pages on BGwiki that show the job family for all these mandragoras are Monk. I'm not sure about the rest of the details on this page, but figured the job family would be helpful to reference.

https://www.bg-wiki.com/ffxi/Category:Jug_Pets

![image](https://user-images.githubusercontent.com/13668758/173364979-94be48b8-d31b-444e-a496-788bd81c9ea5.png)

![image](https://user-images.githubusercontent.com/13668758/173365035-ac778fa1-2a8a-42b4-b423-2b1483b38681.png)

![image](https://user-images.githubusercontent.com/13668758/173365073-26510785-bba6-4a64-91ea-689f9d6da983.png)

version 30181205_0

**Comment by E5una** [comment]
There is an old closed ticket regarding this, seems like it was fixed in the past and then broke later, thought I'd mention it to link them. https://github.com/EdenServer/community/issues/66

**Comment by 59blargedy** [comment]
resolved in July 8, 2022 update
