### ISSUE TITLE
Goldsmithing Guild Vendor

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#511]
Guild Vendor doesn't sell Tufa

**Comment by SleazyFFXI** [comment]
Have you checked wiki entries from before Dec 2007?

**Comment by SleazyFFXI** [comment]
Just did and it's unsure if that NPC sells it

**Comment by SleazyFFXI** [comment]
I just checked and that's the only source of Tufa from a wiki entry in Oct 2007

**Comment by Deepupuu** [comment]
History says alchemy guild use to sell it but alchemy guild doesnt have it either, please add it in thanks.

**Comment by MGramolini** [comment]
Can we get this item at some point?  It has been almost 4 months.
