### ISSUE TITLE
Rabbit Footprint respawning too quickly

### ISSUE THREAD

**Issue by Mildew-Von-Eden** [EdenServer/community#5111]
### Checklist
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Rabbit Footprint respawn is ~10 minutes, but it should be 15 minutes per ffxiclopedia
https://ffxiclopedia.fandom.com/wiki/Black_Coney?oldid=637892
and classic wiki
https://classicffxi.fandom.com/wiki/Black_Coney

![Shevek_2022 06 13_193517](https://user-images.githubusercontent.com/35544823/173482317-8b94bfe1-00b6-447b-bfed-a5288dc68079.png)

**Comment by 59blargedy** [comment]
resolved in July 8, 2022 update
