### ISSUE TITLE
Genbu Headbutt DMG is overtuned

### ISSUE THREAD

**Issue by PfistoFFXI** [EdenServer/community#5112]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

verison 30181205_0

Genbu (the normal one, not the kirin version) does too much damage on it's Headbutt.
Reproducible steps, get headbutt with the gear shown in the video below, another video is also linked.
https://www.youtube.com/watch?v=d2QAiQsahRY
^ Shows gear of PLD/WAR, does not have sentinel at t=306
Takes 300~ dmg with def down and defender

https://www.youtube.com/watch?v=zbGqdIsYFHc
another video, PLD/WHM gets headbutt for 500 dmg, unknown ailments (if he has def down) but definitely doesn't have SS or Blink because takes a Waterga III and health depletes prior to the headbutt.

I can comb for more videos if desired, but believe is presently overtuned on Eden as have seen many 1.3k+ headbutts.

**Comment by ThoseWhoFight** [comment]
Have been saying it's overtuned on the Nyzul Isle version at least, but just going off of memory. Looked for some era video proof with little success. However, if this is the case with the sky god version too then idk why it wouldn't also translate over to the nyzul version. As it stands it's basically a OHKO if you aren't a Galka melee.

**Comment by Steam-arch** [comment]
![Screenshot_2022-06-15-06-23-20-490_com mi globalbrowser](https://user-images.githubusercontent.com/69089249/173731745-eeab8afc-7f04-4c31-8aa8-1ea1240c6b37.jpg)
(Wanted to toss in a headbutt dmg print that doesnt have a "it could have just been a block chance"). To be noted, genbu was at 15-20% and has a very large attack steroid

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
