### ISSUE TITLE
Chips lost upon Zone Crash Jailer of Fortitude

### ISSUE THREAD

**Issue by xwiz75** [EdenServer/community#5114]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
If the zone crashes when you pop or are fighting Jailer of Fortitude you lose the chip set.

**Comment by falzum** [comment]
Place a gm ticket and take a screenshot of the crash. GMs typically refund popsets.

**Comment by 59blargedy** [comment]
thanks for reporting - this isnt something development can solve, but you can reach out with a gm call.
if you have information relating to the crash, i.e. what may have triggered it, that's good to report on so it can get looked at. Your chip set is correctly removed when you pop the mob, so losing the mob on a crash is not something we'd bug fix, rather we'd work on the crash source itself. Is your group doing something right before the crash? are there others in zone? etc.
