### ISSUE TITLE
Zone crashes when popping Jailer of Fortitude.

### ISSUE THREAD

**Issue by Vampjess** [EdenServer/community#5115]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Zone has crashed twice when popping Jailer of Fortitude once the Mob has spawned causing everyone to r0 and pop set to be lost. 
First crash was on 06/07/2022. Submitted GM call and was given chips back right away.
Second crash was 06/14/2022. Submitting bug report due to repeated crash.
Group in zone is not doing anything before the crash and is just on standby. Nothing has been done differently but it has happened twice already and seems to be an issue once Fortitude is actually popped? Zone then crashed again about 5 minutes after we zoned back into the area. Not sure if related but may seem like two different things are crashing in zone.

**Comment by 59blargedy** [comment]
probably a little late to ask, but are players engaging, or is it happening right as the mob pops?

**Comment by 59blargedy** [comment]
this was potentially solved by equipment change fixes, can you update when your group attempts again?

**Comment by 59blargedy** [comment]
am pretty sure this was resolved by the mentioned fixes and havent heard any updates, so closing

**Comment by 59blargedy** [comment]
sounds like this wasn't resolved by other fixes, reopening. really need more information to nail down the issue and resolve.

**Comment by Vampjess** [comment]
Hi sorry, I did not have access to this email. We have recently popped fortitudes last Tuesday 01/03 and did not have any issues. Hopefully it was just an error for that timeframe it was being reported by my group and a few others. Will update if anything changes. Once again, sorry for the extremely late reply.
