### ISSUE TITLE
Retaliation is returning too little TP

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#5117]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

Retaliation on Eden currently is giving a low TP return, around 25-30 per Retaliate with a 2 handed Gaxe, previously it was giving something like 160 TP.

**Comment by 59blargedy** [comment]
resolved in the patch follow-up update
