### ISSUE TITLE
Genbu missing increasing attack boost the lower its HP gets

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5118]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Genbu should start hitting harder the lower its HP gets. Currently his attack doesnt shift through out the fight. Might be easier to get the right increments from a retail test for this one I think? Note: Doing this adjustment without adjusting headbutts damage might make it go bonkers. Fun ffxi fact: Genbu is the hardest hitting god at low hp.

Retail:
High HP genbu:
![image](https://user-images.githubusercontent.com/69089249/173749605-76b37784-342c-4145-85a7-a6908facc685.png)
![image](https://user-images.githubusercontent.com/69089249/173747978-1a7cfcef-fd3e-4442-a689-5695e06f7db4.png)

Low HP genbu:
![image](https://user-images.githubusercontent.com/69089249/173748304-e2c82160-57a8-430a-985b-ae66fb8a1fcc.png)
![image](https://user-images.githubusercontent.com/69089249/173748628-992b73f3-3c65-4b4b-9c97-048fbaf1cccb.png)
![image](https://user-images.githubusercontent.com/69089249/173749303-d342a464-8f90-49ec-8484-84082a5e6784.png)
https://www.youtube.com/watch?v=GKUid6RtScc

![image](https://user-images.githubusercontent.com/69089249/173751893-117c4eea-6865-4b4c-aa27-bf5383a38e30.png)

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update people are going to die
