### ISSUE TITLE
Dynamis Tavnazia Endless Tauri

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5121]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

If you aggro and die to an eye that pops tauri, it will pop two more upon reaggro. Keep dying and repulling to have endless mobs to farm.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
