### ISSUE TITLE
Aura Pot in Ru'avitu wrong Job/Spell List audit

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#5123]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window) 30181205_0
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

Aura Pots are coded as RDM/WAR with OOE Tier 5 BLM spells and access to double attack and Bio III when they should be BLM/RDM.
![image](https://user-images.githubusercontent.com/62901732/174925097-84f819a0-a971-451b-a5cd-dd5d92c2859c.png) Old Data
![image](https://user-images.githubusercontent.com/62901732/174925185-587190e9-12d5-4740-9310-618557411238.png) Current Data
https://www.youtube.com/watch?v=qlSZRr4_FwI 2009 Video but best quality I can find, Shows Casting only T4s and Bio II.

**Comment by statuseffect** [comment]
Correction apparently at 2 points in the video, they do appear to double attack. But do not cast any of the tier 5 spells or bio 3.

**Comment by 59blargedy** [comment]
resolved in July 8, 2022 update
