### ISSUE TITLE
Diabolos - Noctoshield - Only Affects Avatar

### ISSUE THREAD

**Issue by madmikeblvd** [EdenServer/community#5127]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window) 30181295_0
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Blood Pact: Ward "Noctoshield"
"Diabolos grants [Phalanx] (https://ffxiclopedia.fandom.com/wiki/Phalanx_(Status_Effect)) to party members within area of effect."

Currently this does not affect the party or the summoner, it is only hitting the avatar itself, regardless of range.

Step 1 - Summon Diabolos
Step 2 - Use blood pact ward: Noctoshield.
Complete - you will see only the avatar gets phalanx and you nor any party member will receive the buff.

![SMN - Diabolos](https://user-images.githubusercontent.com/71995009/175393195-af1de6cd-e365-4dbc-a977-5b7c19d2e17f.JPG)
![SMN - Diabolos2](https://user-images.githubusercontent.com/71995009/175393197-2b1a1f22-ff1d-4def-b015-695aab47677f.JPG)
![SMN - Diabolos3](https://user-images.githubusercontent.com/71995009/175393204-e2cb837d-9746-47fe-9627-b2955dfcc077.JPG)
![SMN - Diabolos4](https://user-images.githubusercontent.com/71995009/175393208-da94f198-54b8-40e0-8542-86e61c39c779.JPG)
![SMN - Diabolos5](https://user-images.githubusercontent.com/71995009/175393214-03be53a6-a0d5-47af-9ee9-ea555a78be95.JPG)
![SMN - Diabolos6](https://user-images.githubusercontent.com/71995009/175393218-8b082713-2fbe-4958-af89-96e522a65de9.JPG)
![SMN - Diabolos7](https://user-images.githubusercontent.com/71995009/175393223-e87fe91f-92b5-455f-8e1b-666d259eab7d.JPG)

**Comment by Norrissnake** [comment]
just tested  not working

**Comment by 59blargedy** [comment]
resolved in July 8, 2022 update
