### ISSUE TITLE
Garlaige Citadel has too quick of respawns on some mobs

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5128]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Sorry that this isn't comprehensive of every mob in the zone, but for sure the Fallen Mages and Fallen Majors behind gate 2 were respawning every 5 minutes when they should have a 16 minute respawn.

https://ffxiclopedia.fandom.com/wiki/Fallen_Major
https://ffxiclopedia.fandom.com/wiki/Fallen_Mage

I want to say the ghost/beetles might have been too, but its been a few weeks so I'm sorry I don't remember exactly but wanted to report the skeletons. Some mobs were fine, like the Hellmines.

Version 30181205_0

**Comment by KnowOne134** [comment]
corrected in 8/7/2023 update
