### ISSUE TITLE
A Taste of Honey not unlocking Irmik Helvasi synth

### ISSUE THREAD

**Issue by somedudestolemyname** [EdenServer/community#5129]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
completed [A Taste of Honey](https://classicffxi.fandom.com/wiki/A_Taste_of_Honey) questline and received all cutscenes and rewards but was still unable to synthesize [Irmik Helvasi](https://classicffxi.fandom.com/wiki/Irmik_Helvasi)
Quest Completion:
![Screenshot 2022-06-25 021937](https://user-images.githubusercontent.com/97771638/175762720-50ca31ff-6586-4a80-8221-3af07d59069d.png)
Patisseir:
![Screenshot 2022-06-25 032423](https://user-images.githubusercontent.com/97771638/175763293-3dbdb54f-c162-49e2-b84f-fc2f95b6926f.png)
Skill:
![Screenshot 2022-06-25 031902](https://user-images.githubusercontent.com/97771638/175763111-798eaf57-af6e-46b7-8264-51a4e8be6eb1.png)

Recipe Used:    https://classicffxi.fandom.com/wiki/Irmik_Helvasi
Cooking (65)
Fire Crystal
Key Item Patissier
1 x Pine Nuts
1 x Selbina Butter
1 x Selbina Milk
1 x Semolina
1 x White Honey
![Screenshot 2022-06-25 021730](https://user-images.githubusercontent.com/97771638/175762739-64b3eb9f-5268-4378-b442-a1cf891aa358.png)
![Screenshot 2022-06-25 021805](https://user-images.githubusercontent.com/97771638/175763342-dd2a516d-5ca4-4444-88d3-4ee53503bc89.png)
Version:
30181205_0

**Comment by 59blargedy** [comment]
resolved in July 8, 2022 update
