### ISSUE TITLE
Listing items on AH sometimes lists the rest of the stack in your bazaar

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#513]
I'm not 100% sure of how this happens yet, but this is the 2nd time I have run into the issue.

I posted a pickaxe on the AH for 280g from a stack of 4 in my inventory.  The other 3 were now listed in my bazaar for 280g, when inspecting myself or others inspected me.  I checked my bazaar "set prices" menu option and they weren't listed for sale there.  They were not greyed out in my inventory.

I checked the website for my character, here is a screenshot.
![image](https://user-images.githubusercontent.com/1774728/50060182-9501fd80-015e-11e9-89de-3d86181fa338.png)

I asked someone to buy them (Aisu) and they were able to.  I now do not have the pickaxes.

**Comment by MGramolini** [comment]
This happened again today.  I put up a few dark clusters on the AH for 2500g and then 2600g between 11:37 and 11:42 PM EST.  I now have them listed in my bazaar at 2600g for the last 3 of the stack.
Here is an in game picture of my own bazaar:
![image](https://user-images.githubusercontent.com/1774728/55678502-fc3bed00-58c8-11e9-90d0-991114d0a304.png)

Here is a screenshot of the current status of my bazaar on the website:
![image](https://user-images.githubusercontent.com/1774728/55678514-31483f80-58c9-11e9-962c-3066acdaa96e.png)

Here is a screenshot of Heinlein buying the dark clusters (i did receive the gil):
![image](https://user-images.githubusercontent.com/1774728/55678536-91d77c80-58c9-11e9-993d-41d93f306b15.png)

**Comment by MGramolini** [comment]
I didn't screenshot it, but when i went to edit the price in my bazaar, it wasn't actually priced at all.

**Comment by pnavuf** [comment]
![bug513](https://user-images.githubusercontent.com/19671590/55678566-17f3c300-58ca-11e9-929d-f71c8c75f019.PNG)
Can confirm was able to buy.

**Comment by MGramolini** [comment]
This actually happens every time i put up individual items from a stack.  Happened 10+ times today.

**Comment by MGramolini** [comment]
I have to go into my bazaar, set the price, then unset the price to prevent people from being able to buy.

**Comment by MalteseFalcon** [comment]
I got a a Bronze Knife from zine ore quest, was listing it on AH and decided to just vendor it. After leaving AH menu I noticed the bronze knife listed in my bazaar, however in my inventory it didn't have any price set and was not greyed out like it was for sale. I had another player check my bazaar to confirm it wasn't just on my end, he bought the knife and I reimbursed him for it.

**Comment by Mahou81** [comment]
I am having the same issue with deathstones, exactly as described here.

**Comment by 59blargedy** [comment]
resolved by another dev in November 21, 2022 update
