### ISSUE TITLE
Pots in When Angels Fall don't try to full heal

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5132]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

https://ffxiclopedia.fandom.com/wiki/When_Angels_Fall

When a pot gets low on HP, it may attempt to flee to its spawn position. If it is allowed to be there a mere few seconds, it will regenerate to full HP. [Stun](https://ffxiclopedia.fandom.com/wiki/Stun) and the use of [Weapon Skills] may prevent this from happening.

They used to do this but I assisted some ls mates with a fight and this behavior was absent

**Comment by 59blargedy** [comment]
just to make sure, only the blm pots will return to spawn. are you referring to the rdm behavior (they will not do this)?

**Comment by falzum** [comment]
All 4 pots just stood around and let us kill them. None of them attempted to return to their platforms.

When I've done this previously on Eden all 4 pots would try to return once they got below whatever threshold triggers it

**Comment by 59blargedy** [comment]
yeah that was wrong so it was fixed, but still worked on blm as intended for at least a while. will look to see what broke, thanks!

**Comment by falzum** [comment]
After watching some era videos it seems like there's some time aspect to when the pots try to go back to their stands which wouldn't have been triggered since we had clear times of under 5 minutes.

The problem may be that my group was just too strong
