### ISSUE TITLE
Temenos East Avatar spawn rate too low

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5133]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

Prime Avatar spawn rate in Temenos East seems to be too infrequent. It should be a 50/50 chance (given that you spawned both item chests before triggering one). Recently completed my 5th or 6th run in a row where I didn't see a single Avatar spawn despite choosing the item chest for 5 of the 6 floors. While statistically possible, errs on very improbably especially given other people's data.

Evidence:
https://ffxiclopedia.fandom.com/wiki/Temenos_-_Eastern_Tower, specifically the top section referencing - "Opening a chest causes the remaining Elementals and any other chests on that floor to despawn, and also opens the gate to the next level.
One of the two Items chests on any given floor is "fake", and contains a [Mystic Avatar](https://ffxiclopedia.fandom.com/wiki/Mystic_Avatar) of the appropriate element. Opening this chest will despawn the remaining Elementals, but not any chests that are already on the ground. The remaining chests will lock until the avatar is defeated, at which point you will be permitted to open one of the other chests to open the gate to the next level. If no other chests are present, the gate will automatically open upon the avatar's defeat."

**Comment by falzum** [comment]
Interesting. I just did this as well and thought I was lucky going 0/6
