### ISSUE TITLE
Destroyers in Double Dragonian not dropping at correct rate

### ISSUE THREAD

**Issue by Bizaroblyatt** [EdenServer/community#5134]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I have been trying to get Destroyers from double dragonian ksnm30, in total we have done 15 runs, 13 of which were in one day. We have yet to see a pair of the fists. When the drop rate is supposed to be over 20%. First 7-8 runs I just consider unlucky. But now we are under a 1% drop rate. So I feel this may be an issue on the server end.

Version - 30181205_0

**Comment by zanderken7** [comment]
Can Attest to this, the loot pool that houses the 4 latent effect weapons have a reportedly  close-to-even split  around 25% after performing approximately 100 runs on live servers. 0/15 With most of the weapon drops being "Heart Snatcher" may indicate an error relating specifically to that item. 

Of the 15 runs 
1 subduer dropped
2 dissectors dropped
**12 heart snatchers dropped**
0 destroyers dropped

Outside of further saying its unlucky, I'd at least recommend an audit for the treasure pools for accuracy.

**Comment by 59blargedy** [comment]
they're all set equally. rng can be painfully streaky sometimes and lead you to believe that something is off, but i can validate the drop rate for these items is equal across the board. i understand that it can be very frustrating and am happy to check these issues when they come up, but in this case there are no issues with the drop rate. best of luck getting your weapon.
