### ISSUE TITLE
dye recipes are now era and will need to be reactivated, and the recipes associated with them.

### ISSUE THREAD

**Issue by danismyhero** [EdenServer/community#5135]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

[White Yellow Green Blue] Textile Dye
[White Yellow Green Blue] [Three Six Nine]-Drawer Almirah

Proof:

https://ffxiclopedia.fandom.com/wiki/2008_-_(09/09/2008)_The_Version_Update_Is_Here!
"Several new synthesis recipes have been added."

https://www.ffxiah.com/new-items/2008-09-08

***Note***
Red Textile Dye is made from a WotG synthesis material, and does not end up making any other items until December 2008+.

**Comment by DeuceFFXI** [comment]
Just commenting here to give this more visibility.  I was going to craft one of these furnishings tonight and I hit a roadblock with the textile dye.  I would appreciate if these could be added in the next patch.

I'm uncertain if there are other recipes missing from the September 2008 patch besides the 4 textile dyes, and then the synths for the dyed drawers.

**Comment by 59blargedy** [comment]
resolved in this week's update.
