### ISSUE TITLE
Paradise, Salvation, and Maps (Sacrarium Map Quest) Bugged

### ISSUE THREAD

**Issue by Avarghaladion** [EdenServer/community#5136]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

1. Spoke to Nivorajean in Tavnazian Safehold and received the quest like normal.
2.  Farmed a Sacrarium Chest Key and opened Treasure Chest, receiving Piece of Ripped Floor Plans Key Item like normal
3.  Upon returning to Nivorajean with the Key Item, he did not give the proper dialog. He is supposed to display a map and then ask the player at what position they opened their Treasure Chest for the Key Item. He instead removed the Key Item and gave only the mission failure dialog immediately without displaying the map or giving the option to choose chest position. [This screenshot](https://ibb.co/MVmwNqh) demonstrates NPC defaulting to quest-failure dialog.

_Note: Did this with a friend and their own quest worked normally, without any issues. They picked the lock on their chest as THF whereas we farmed a key for mine._

**Comment by falzum** [comment]
What's you're version?

Type /ver ingame to check

**Comment by Avarghaladion** [comment]
Added after posting, sry. 30181205_0

**Comment by KnowOne134** [comment]
Do you have the addon eternity?  It presses enter for you during cs

**Comment by Avarghaladion** [comment]
Negative. All manual and I only hit enter a single time to initiate
conversation. The normal dialog also didn't appear in the log and there's
supposed to be a bunch he says before presenting the map and asking the
player to pick the chest position. He just skipped everything entirely and
went directly to the failure dialog on contact.

**Comment by 59blargedy** [comment]
do you remember the pos where you opened the chest? the quest functions for
most players so it's either a blip for you specifically (a not specific to
the quest bug) or an issue with a particular chest (something to fix in the
quest, so more info could help)
if you haven't done so, file a gm ticket.

**Comment by 59blargedy** [comment]
resolved in July 8, 2022 update (thanks for the details, it was your particular location only that was bugged)
