### ISSUE TITLE
NOTICE: guild point npcs are temporarily unavailable

### ISSUE THREAD

**Issue by Windsong2** [EdenServer/community#5146]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x) ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The Bonecraft guild point NPC (Samigo-Pormigo) is missing since the new update.
![Bony_2022 07 08_140819](https://user-images.githubusercontent.com/94816023/178056473-d4381024-3357-46ed-ada4-7aa33ec8d484.png)

**Comment by bliven-was-taken** [comment]
There's literally an announcement in the discord that says they removed them currently.

**Comment by 59blargedy** [comment]
not everyone reads discord, all good. the guild points folks are forcibly removed atm while an issue is resolved. will return asap

**Comment by 59blargedy** [comment]
resolved
