### ISSUE TITLE
Reprisal is not able to be sold on ah after implementation

### ISSUE THREAD

**Issue by Camuel666** [EdenServer/community#5147]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)
- [X ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version 30181205_0

After todays patch and implementation of reprisal it is not listed in the AH and is not able to be sold or bought from ah
![image](https://user-images.githubusercontent.com/24218461/178091453-1f46246c-ba64-4be1-bf75-e20c2d9496b7.png)
this is a picture form the current ah and where reprisal should be listed

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
