### ISSUE TITLE
Cutscenes from COP mission 2-4 Ancient Vows are duplicated

### ISSUE THREAD

**Issue by pavigeant** [EdenServer/community#5148]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

For mission CoP 2-4 : Ancient Vows, the cutscene for clicking the Spacial Displacement is the same than the cutscene viewed when clicking the Dilapidated Gate in Misareaux Coast at F-7. The cutscene involves Prishe and Ulmia seeing a completely destroyed Riverne coast.

### Steps to reproduce

1. Start mission CoP 2-4 : Ancient Vows
2. Head to the Dilapidated Gate in Misareaux Coast at F-7 and examine it.
3. View the cutscene.
4. After the cutscene, proceed to the Spacial Displacement and examine it.
5. View the same cutscene from the Dilapidated Gate at the Spacial Displacement.

### Version

Version 30181205_0

### Proof

https://classicffxi.fandom.com/wiki/Ancient_Vows

![image](https://user-images.githubusercontent.com/8645893/178160890-b81feff2-61b9-4d93-9bc4-44edeea07cbb.png)

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
