### ISSUE TITLE
Simple Bed yielding unlimited iron ore even upon re-log

### ISSUE THREAD

**Issue by Kaijikunito** [EdenServer/community#5149]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
The day before yesterday I placed a simple bed in my Mog House in Windurst and logged out without using the Moogle or Mog House functions. I logged in to my character Kaijikunito on account Kaijikun today around 17:20 CST and received 4 iron ore from my moogle with the messages "Master! I have something to tell you, kupo! I found this precious item under the simple bed pillow, kupo!". I talked to the Moogle several more times and he continously gave me 4 iron ore with the same message. Upon re-log, the same issue occurred. I used the Mog House menu to remove my bed from layout and replace it. Talking to the Moogle again did not yield any iron ore, nor did relogging and then talking.

This character has 4 stacks of iron ore plus another 8 all from this issue. I will not be using these items until told otherwise (I would just toss them but I don't know if having the item in my inventory assists the investigation). If possible I would like to keep 4 of the iron ore as I believe that is what was intended to happen unless it is out of era.
![iron ore bug 1](https://user-images.githubusercontent.com/109045612/178164324-66c95402-9605-45eb-9f04-4c795ef0d430.png)

**Comment by Kaijikunito** [comment]
Update:

I am using the simple bed for Moghancement: Experience and I logged in receiving another 4 chunks of iron ore after speaking with my moogle. I removed the bed and placed it down again to stop the moogle from giving me ore when I talked to him. The excess ore is in my Mog Safe 2. Should I throw it away?

**Comment by 59blargedy** [comment]
this kind of stuff is best for a gm call, have you made one? GMs have DMed you trying to get in touch, so you can also respond that way.

**Comment by Kaijikunito** [comment]
Oh! Do you mean in game? I'm sorry for missing that, I have been switching characters alot in the past hour trying to gear up and get my items on my mule. I will call a GM, thanks!

**Comment by Kaijikunito** [comment]
I tried to place a GM call with a message but I received the messages "Your call has been placed in the queue. GM call message was empty. No new GM call has been placed." I will be online now for a while and will keep a lookout.

**Comment by Kaijikunito** [comment]
Update:

I have not received any iron ore from my simple bed in 9 days. My nation is in Windurst which is in last place for conquest, so at first I thought that maybe the quest wouldn't activate when my nation is in last place. However, a linkshell member claims that Windurst was also in last place last conquest tally.

**Comment by 59blargedy** [comment]
this was resolved in a live fix a couple months ago, forgot to close
