### ISSUE TITLE
Raise Rod

### ISSUE THREAD

**Issue by Falastor** [EdenServer/community#5151]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Tried using Raise Rod today on some dead friends but the rod didn't work.   Tried looking into how to actually use it, but no luck.  Maybe it's not properly coded? Maybe it's user error....

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
