### ISSUE TITLE
Gear macro set causing tp loss even with no weapon/ammo change.

### ISSUE THREAD

**Issue by Bizaroblyatt** [EdenServer/community#5152]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.) If I use a macro with a gear set in it, then I lose all my tp. If I use a macro just specifically changing one piece of gear for another will work just fine.  In both gear sets the same weapon and ammo is used. I have tried logging out and it would not effect it. It has happened three separate days in a row now.
- [x ] I have provided my client version in the details. (type /ver into your game window)
- 30181205_0
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by falzum** [comment]
Set your gearsets to "Keep same piece"

https://discord.com/channels/482610771126386688/547611374679883787/995187434587435149


Also in the future, but your bug report text below the check boxes. It's much easier to read that way

**Comment by Bizaroblyatt** [comment]
I changed all of the gear sets to that on the weapon and ammo slots. The issue is still occurring.

**Comment by Steam-arch** [comment]
@Bizaroblyatt change the sets so that there arent any red X's anywhere at all and it wont reset

**Comment by ConteAlmaviva** [comment]
This happened to me too; I had some equipsets to change ammo and just keep the currently equipped item in the ranged slot (i.e. empty, no red X on ranged), that instead changed to explicitly unequip the ranged slot (red X), which I thought was strange since it seems like equipsets should be stored client side rather than server side.  Once I fixed them the issue went away, though.

**Comment by 59blargedy** [comment]
from what im gathering, there is a way to prevent this issue from occuring, so closing as completed. if im misreading, can just comment here.
