### ISSUE TITLE
Haste belt enchantment isnt usable

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5153]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Upon use, says
![image](https://user-images.githubusercontent.com/69089249/178536358-54e3a180-0ad4-496c-a5ee-6381a3af33be.png)
But then it does give the timer top left as if you would be using it (no animation either), but action never goes off

**Comment by 59blargedy** [comment]
hmm, this works fine for me, even if i have haste up. gonna need more info. did you have any enchantments active?

**Comment by Steam-arch** [comment]
Hmm, I checked it again and I still cant get it to work in any situation. Checked all jobs listed, removed all effects and such, no enchantments, 

Are you sure you checked 
![image](https://user-images.githubusercontent.com/69089249/179355263-bbed7795-a94a-46f2-9280-8a9f03c23943.png)
and not hydra legs? Hydora legs work as intended

**Comment by 59blargedy** [comment]
is this occurring on live?

**Comment by Steam-arch** [comment]
checked on test server, not sure about live

**Comment by ThoseWhoFight** [comment]
Checked on live just now and it works fine for me.

**Comment by ThoseWhoFight** [comment]
Are you using Windower by chance?

**Comment by Steam-arch** [comment]
Hmm, yeah windower here

**Comment by ThoseWhoFight** [comment]
Did you update windower at all recently? or your gearswap folder?

**Comment by ThoseWhoFight** [comment]
also did haste buff never apply at all? or did it apply and auto cancel?

**Comment by Steam-arch** [comment]
it just never applies at all. havent done any updates/changes recently I dont hink

**Comment by 59blargedy** [comment]
this is a test server issue
