### ISSUE TITLE
Peallaihd and its chigoes hit too weak + peallahd stops spawning chigoes after 3 sets

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5155]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

1: The chigeos it spawns hit too weak, they hit 5-15 against 245 def (protectless rdm)
 ![image](https://user-images.githubusercontent.com/69089249/178583251-57e66055-22d7-4e34-a872-5a82ac36ec50.png)

Should hit around 15-55

Retail numbers vs no protect nin/dnc
![image](https://user-images.githubusercontent.com/69089249/178583197-a55903e5-6a1e-4eb6-a38b-2506588a1adf.png)
![image](https://user-images.githubusercontent.com/69089249/178583354-57d23c7d-9bca-42a2-86ad-eeab1e609b0a.png)
![image](https://user-images.githubusercontent.com/69089249/178583462-46e37a78-288b-422e-a514-a1e80534763d.png)
![image](https://user-images.githubusercontent.com/69089249/178583484-1748ce64-d9fb-421c-975d-b81f35031325.png)
![image](https://user-images.githubusercontent.com/69089249/178583582-a8d2ab13-af1e-4a24-87cb-e991cf8d10c0.png)
![image](https://user-images.githubusercontent.com/69089249/178583669-e19f5478-ff6f-472e-a799-d445967226df.png)
![image](https://user-images.githubusercontent.com/69089249/178584088-5831a8af-a87a-4957-9c08-f49aa9d273e5.png)

2: Peallahid hits abit too weak also, Hits around 85-140 on 245 def no protect RDM

Should be hitting a protectless nin 140-210, should be able to break even 290 with berserk on (sorry lost the ss of the 290 hit).
![image](https://user-images.githubusercontent.com/69089249/178584361-fd9b7622-3fd2-4b4b-9a22-f30e880be460.png)
![image](https://user-images.githubusercontent.com/69089249/178584449-4369ab07-6701-47e2-9ddc-856fd939c254.png)
![image](https://user-images.githubusercontent.com/69089249/178584571-d51ec271-e5b8-4513-bcae-661e501c9e4c.png)
![image](https://user-images.githubusercontent.com/69089249/178584669-adff4d6a-f47b-46d0-b8e0-06b8a863dcf0.png)

3: Spawns 2x chigeos 3 times and then stops spawning them with TP moves.

era video https://www.youtube.com/watch?v=rAcX3dNUuuw

**Comment by 59blargedy** [comment]
this was resolved in the last update, forgot to include patch note.
