### ISSUE TITLE
Cerberus Gates of Hades burn should be 20/tic

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5157]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently 40/tic. Should be 20/tic

1:30 GoH goes off and can see it being 20/tic
https://www.youtube.com/watch?v=t4IgygjDsno&t=343s

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
