### ISSUE TITLE
Rogue's Roll values incorrect

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5160]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

Based on the various wikis, values of Rogue's Roll hasn't really changed since era. BGWiki and JPWiki match each other in terms of the roll values. FFXIClopedia is what Eden currently uses, making non-5 & 11 very weak and 5 & 11 OP

BGWiki: https://www.bg-wiki.com/ffxi/Rogue%27s_Roll
JPWiki: http://wiki.ffo.jp/html/6053.html

FFXIClopedia: https://ffxiclopedia.fandom.com/wiki/Rogue%27s_Roll?oldid=692929
(Backdated wiki isn't what Eden has. Eden seems to use current retail FFXIClopedia)

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
