### ISSUE TITLE
Asrahd (Whitegate Sanction guard) seems confused about his identity (says he is "<player's name>, officer of the Imperial Army")

### ISSUE THREAD

**Issue by ConteAlmaviva** [EdenServer/community#5161]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On my alt, I've only just gotten to Whitegate and haven't yet completed AU Mission 2, which is needed for access to Sanction.  Talking to Asrahd (Sanction NPC in Whitegate) gives the following dialogue:

![image](https://user-images.githubusercontent.com/8880996/179422020-e70ecb04-9cd5-4491-9f70-7210a3d84196.png)

Identity theft is not a joke, Asrahd.  Millions of adventurers suffer every year.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
