### ISSUE TITLE
Puppetmaster Drum Magazine seems to have incorrect penalties and inconsistent behavior

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5164]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

There are many era sources that indicate how brutal Drum Magainze was on any meaningful target and recommend only using it for farming. In later years its penalties were reduced (2011), and even further than that they were removed altogether. Below you can see the JPwiki values for the penalty from pre-2011 (presumably our version) as well as the 2011 penalties. 

http://wiki.ffo.jp/html/8882.html

![image](https://user-images.githubusercontent.com/13668758/179868683-60819338-c8a5-45dc-ad0c-1f90b0acdc93.png)

It appears as though era penalties should be -20/-40/-70/-100. Oddly enough if you view this page on mobile it translates slightly differently in the sense that it credits the data to a user that has their own wiki page where it details their credentials.

![image](https://user-images.githubusercontent.com/13668758/179868866-905e1996-bef3-4ba3-be2d-5d37103700c3.png)

Here are the values today on Eden. 

Note: There seems to be a bug. I'll detail at the end.

![image](https://user-images.githubusercontent.com/13668758/179868951-ef190cef-4e09-48f0-bb61-41e5fdc340dc.png)

![image](https://user-images.githubusercontent.com/13668758/179869050-576d457b-f541-4037-95ed-5a642e3d45f2.png)

On Eden the penalty appears to be either 0/-15/-4/-5 or maybe -15/-0/-4/-5. I'm not entirely sure. The reason for my confusion is because you can see that my automaton has the same RACC in the 0 attachments 0 maneuvers screenshot as the drum magazine 0 attachments screenshot. But if you look at the last test at the end, I still have the penalty. 

Either way, strange behavior aside, looks like the penalties should be significantly higher.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
