### ISSUE TITLE
Misareaux Coast Logging Points

### ISSUE THREAD

**Issue by Akeanin** [EdenServer/community#5165]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Logging Points in Misareaux Coast not spawning.  Current date is 7/20/22 and the time is 3:23PM EST and there isn't a single logging point up.  Also had a friend come out and check to see if it was a client issue.

**Comment by falzum** [comment]
Not all nodes are marked on the wiki map. I believe there's one really deep by the gate to riverne that isn't on the wiki map
