### ISSUE TITLE
Ulbuconut Milk synth is out of era. 

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#5168]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version 30181205_0
Synth being crafting in Windurst Woods is out of era and was added with Adoulin in 2013.

![image](https://user-images.githubusercontent.com/62901732/180099520-e556ae9e-6abf-42d6-acb3-af0f963fb2d6.png)

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
