### ISSUE TITLE
Assault (Pet Command) distance is too far

### ISSUE THREAD

**Issue by Mildew-Von-Eden** [EdenServer/community#5169]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Version
30181205_0

### Details
As per wiki...
https://ffxiclopedia.fandom.com/wiki/Assault_(Command)
Summoner pets should have an assault range of 17.5 yalms. Current it's right around 20 yalms.

### Apology
Sorry fellow summoners.
:'(

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
