### ISSUE TITLE
Aspidochlone issues

### ISSUE THREAD

**Issue by Snugglepunk** [EdenServer/community#5172]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

Aspid is very undertuned with many issues currently.   I'm very confident a RDM + BLM could duo Aspid in its current state on Eden.  It sure doesn't feel like the HNM it was in era.

**Is missing its 50% MDT**
It seems to have no MDT and nukes do full damage.
JP wiki talked about damage being cut by 50% 
![image](https://user-images.githubusercontent.com/56851217/180671800-36308c98-e5fe-42ad-9a4e-4d7565917905.png)
Era videos + current retail testing also show it should take 50% damage from Ice nukes.
![image](https://user-images.githubusercontent.com/56851217/180671888-59d1f115-39c0-412b-9054-77c7ca188254.png)
![image](https://user-images.githubusercontent.com/56851217/180671901-5eb9cb9f-6450-4e4d-a0d8-aa95858c3d53.png)
![image](https://user-images.githubusercontent.com/56851217/180671918-20e4d078-cd02-40dd-8a2f-bc2567474d4b.png)

Current Eden damage, with cor rolls.
![image](https://user-images.githubusercontent.com/56851217/180671845-4d4cc3b7-19e4-4256-bc4b-828e4bd1fbdd.png)

**HP is too high and Regen too low**
On Eden it has 35k HP. It  should only have 20k HP
Its regen is under tuned and should be 1% per 3 second tick, so with the correct 20k HP it should be 200hp/tick regen while in its shell.

**In/Out of shell mechanic is not working correctly**
This part is hard to explain but will do my best.  In era we all thought big burst damage forced it out of its shell and stopped the regen.  From researching era videos + retail testing this is partially true, but not quite as we thought.  
Big nukes that overcome its regen force it out of its shell briefly, it uses a TP move and then retreats back into its shell immediately.  **There is no amount of burst damage that forces it to stay out of its shell** for any longer than a TP move animation.  
I like to think of the 20k HP as his shell, and you need to damage his shell to get the in/out of shell mechanic.  When he is popped and at 100% hp his shell is undamaged.  Soon as you do any damage to his shell, he retreats and gains his potent 1% hp regen. Lets say 1 nuke took him to 95%, no one else casts, wait 15seconds he regens to 100% and will pop out of shell.  5% damage has been done to his shell, now he will not retreat back into his shell till you take all the 5% regen'd HP off and start damaging his shell again.  
The only way that Aspid comes out of his shell mid fight is if he regens to 100% or 90 seconds pass with no damage taken to his shell, only then he will then come out on his own.  If any damage is done to his shell and he pops out and uses a TP move this resets the 90sec timer he will spend inside the shell.

Era Video
https://youtu.be/ADCRVcEVRp8

Retail testing
https://youtu.be/UEKkkyMdmxs

More Retail testing, shows 90sec in shell after last TP move
https://youtu.be/VepcFwob6o4

**Tortoise song should remove 3 buffs**. Not sure if this is working correct on Eden or not but could do with double checking.
![image](https://user-images.githubusercontent.com/56851217/180672428-e22ea090-4ab6-453c-9fc6-9f596ab1b27a.png)

**Should only have regain while inside its shell**
Difficult to see this in era vids as we always insisted on having melees on this thing but from retail testing it does not have regain while out of shell.  Eden has a potent regain while out of shell making the hold on this much harder.

**Takes 1/3rd spirits within damage when in shell, full damage when out of shell.**  
![image](https://user-images.githubusercontent.com/56851217/180673983-53412ad5-2e2d-499a-b156-3864a694c802.png)
![image](https://user-images.githubusercontent.com/56851217/180673995-99a1d75f-d382-42f4-8320-9e878a853415.png)

**Draw in raidus too large**
There is a max draw in range where you cannot move Aspid any further from its spawn point.  The radius of this is too large and you can pull Aspid to the walls of the zone making it very easy to hold/kill without dealing with any adds.  This was a huge part of Aspid camps, you always wanted a few people to take care of adds. 
Era 
![image](https://user-images.githubusercontent.com/56851217/180672242-c66f133c-7236-4bf2-b3cf-e45b2d0d68b1.png)
Eden
![image](https://user-images.githubusercontent.com/56851217/180672256-1ed7daa4-cb82-466c-b1ef-b763ac11f3ef.png)

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
