### ISSUE TITLE
Sea Monks shouldn't guard or counter

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5174]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Reverse proof of claim bug report. 

Guard and counter traits need to be removed from Sea Monks. They can double attack before level 50, making Warrior their main job.

Every mob of the sea monk family appears to be coded as Monk for their main job on Eden. I've only personally seen Lord of Onzozo and Proteus assigned with the correct job. 

Only Tieholtsodi in Limbus is known to counter. Several others will use Hundred Fists, yet they cannot guard or counter. Tieholtsodi is the only exception. It uses Hundred Fists, it can counter, but it can't guard.

Please contribute by adding proof of Sea Monks using guard and counter traits.

**Comment by dowzer** [comment]
These sea monks currently counter and guard on Eden when they shouldn't:

SSG:
https://www.youtube.com/watch?v=l4P-TkJH2j0

Kuftal:
https://www.youtube.com/watch?v=qsbqK8vTR8k

LoO PH:
https://i.imgur.com/30mhLTE.mp4

**Comment by dowzer** [comment]
Sea Horror:
https://www.youtube.com/watch?v=VFDKMwb7Lug
![seahorror](https://user-images.githubusercontent.com/54732693/212179663-7e016b34-ca89-4468-8d77-83f505a55b0b.png)

**Comment by dowzer** [comment]
Valor:

https://www.youtube.com/watch?v=TwOBD5kN_vw

It shouldn't counter or guard^

**Comment by dowzer** [comment]
I tested Tieholtsodi wearing full ilevel 119 gear and it was still able to counter my attacks. Regardless if evasion is capped, there is always an opportunity to land hits due to floored accuracy being 20% hit rate.

I'm not going to re-confirm SSG or Kuftal Devil Mantas. They weren't able to counter or guard when I checked in previous videos.

I'm only going to re-confirm Flying Manta in LoO. 
https://www.youtube.com/watch?v=CFzQryNBExc

Sea Monks on the Selbina<>Mhaura boat aren't supposed to counter or guard.
https://www.youtube.com/watch?v=XtXEe8eUXAQ

Kulshedra aren't supposed to counter or guard.
https://www.youtube.com/watch?v=NrDn0TXDvMA

**Comment by dowzer** [comment]
Sea Bonze in SSG aren't supposed to counter or guard.
https://www.youtube.com/watch?v=xEVeLbOtCoY

The Kraken guarding the Nightflower isn't supposed to counter or guard.
https://www.youtube.com/watch?v=ca0k4FdHgsI

**Comment by dowzer** [comment]
Nightmare Kraken in Dyna Qufim aren't supposed to counter or guard.
https://www.youtube.com/watch?v=seCvLzasYiA

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
