### ISSUE TITLE
Aht Urhgan Mission 44: Nashmeira's Plea Alexander regens if left unclaimed

### ISSUE THREAD

**Issue by Shika10** [EdenServer/community#5175]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Ver. 30181205_0

Our group completely wiped during Aht Urhgan Mission 44: Nashmeira's Plea. Alexander slowly regained HP to 100%. This is not era behavior according to classic wiki, retail wiki from Sept 2009 and era video from March 19, 2009.

Retail wiki Sept 2009: https://ffxiclopedia.fandom.com/wiki/Aht_Urhgan_Mission_44:_Nashmeira%27s_Plea?oldid=990585

_Alexander does not Regen health if left unclaimed, so it is possible to wipe, Reraise, unweaken, and continue damaging him from the point at which the wipe occurred. Do not run away too far from Alexander or he'll use draw in and use a move on you making it difficult for a raiser to get back up without aggro. Wipe just outside of aggro to prevent draw in._

Classic wiki: https://classicffxi.fandom.com/wiki/Aht_Urhgan_Mission_44:_Nashmeira%27s_Plea

_Alexander does not regen health if left unclaimed, so it is possible to wipe, reraise, unweaken, and continue damaging him from the point at which the wipe occurred._

YouTube era video from March 19, 2009:

You can watch entire video from the start to see this was a wipe and regroup before the fight continued. URL link starts at 3:49.

https://youtu.be/qKzfmzqayTE?t=229

**Comment by Shika10** [comment]
@KnowOne134 While you are in there, I found no reference anywhere online that states you have to wait for JP midnight for another Mythril Mirror key item from Naja. We are being told there was proof this is the case. If you could look into that again, I would appreciate it.

**Comment by KnowOne134** [comment]
Different issue, best to make new report

**Comment by KnowOne134** [comment]
this was fixed some time ago
