### ISSUE TITLE
DRG Healing breath goes off too fast

### ISSUE THREAD

**Issue by Snugglepunk** [EdenServer/community#5176]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

DRG Healing breath on Eden has ~1 sec delay from the ready message to the heal landing.  It's missing a 2-3 sec ready time.

Era 
https://youtu.be/WuFi2UONZ-s?t=198

2009 with chat log time stamps
https://youtu.be/zkX1zQfEQcE

Eden
https://youtu.be/j8T26WQV2Uw

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
