### ISSUE TITLE
Memory Receptables occasionally spawns Strays in at double rate or two together

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5177]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Sometimes when engaged with a MR, it can spawn 2 strays instead of just 1, can happen back to back. Happens quite rarely though and havent really noticed any trigger for it. Doesnt necessarily happen in a single climb but maybe once every 4-7 climbs. He poops out 2 strays on the timed spawns a few times and then goes back to behaving normally and spawns just 1´s

**Comment by Steam-arch** [comment]
Hmm, just wanted to throw a small update on this. Sometimes the MR spawns strays at double speed. Went back to normal after wipe, getting up and trying again.

**Comment by KnowOne134** [comment]
Corrected on 7/5/2024

**Comment by Avarghaladion** [comment]
This, or something similar, seems to be an issue again after last patch.
