### ISSUE TITLE
Strange Juice should probably be a 5 min duration instead of 10 min

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5178]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently 2tic and 10 min duration. Should propably be a 5 min duration(?). Can be found in nyzul & Salvage

![image](https://user-images.githubusercontent.com/69089249/181018183-4d06e0f3-39ba-459d-bf08-7093f00adafa.png)
https://ffxi.gamerescape.com/wiki/Talk:Refresh_(Status_Effect)

![image](https://user-images.githubusercontent.com/69089249/181019604-8033b6cf-98b0-42e0-b04e-1bd1c2cf67f0.png)
strange milk is also 5 min duration
![image](https://user-images.githubusercontent.com/69089249/181018386-393a018c-f1d5-46ad-8aeb-82e4f1ae53b6.png)

clopedia wiki currently says:
![image](https://user-images.githubusercontent.com/69089249/181018503-159e1841-0a56-4d08-b70b-0ed00c2f0449.png)

take back says:
![image](https://user-images.githubusercontent.com/69089249/181018708-df1b68f2-29d5-4c73-89f4-7dba0163a81a.png)

bg-wiki lists salvage counter part as a 5 min duration aswell:
![image](https://user-images.githubusercontent.com/69089249/181021056-b8353785-ce93-4702-be3b-a099a8462446.png)
https://www.bg-wiki.com/ffxi/Category:Salvage/Temporary_Items
(last edited 10 years ago)

Might be an off era change?

**Comment by Steam-arch** [comment]
![image](https://user-images.githubusercontent.com/69089249/181049642-37e89695-9a6d-4032-bae6-fa1b6835a95d.png)
might be barely are actually

**Comment by KnowOne134** [comment]
corrected in 8/7/2023 update
