### ISSUE TITLE
DRG's Wyvern has too much att/damage rating

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5179]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Wyverns seem to be hitting for almost double, triple or maybe even quadruple of what they are supposed to hit for.

Offensive Wyvern comparison:
https://www.youtube.com/watch?v=FF_Z50bEka0

Note: This should be before the march 2008 patch aswell.
On Ul phuabos Eden drg hits for around 64-111 (used att food, he does not show what food he used but id imagine that)
On Ul phuabos era drg hits for around 65-115

On Ul Phuabos Eden wyverns are hitting for ~40-77
On Ul phuabos Era vid wyvern is hitting for a static ~23-33 (its a short video though but one of the only decent one of the offensive wyvern, not 100% sure if they have the same specs as support wyverns)

Offensive Wyvern damage numbers:
![image](https://user-images.githubusercontent.com/69089249/181381378-a35f8a1a-7a11-4914-b9b9-c0d2f404062a.png)
![image](https://user-images.githubusercontent.com/69089249/181381498-0eb22a11-f320-45b1-a80e-c5f7ccbfbebf.png)
![image](https://user-images.githubusercontent.com/69089249/181381822-832c36fa-1ccc-4419-9791-9e66eb750a99.png)

Lowest Ul-phuabo lvl 75
![image](https://user-images.githubusercontent.com/69089249/181382344-5b0b5954-0a5b-4fb9-9005-a550928959f8.png)
![image](https://user-images.githubusercontent.com/69089249/181382754-8af1f77e-f2a0-455c-8d5f-49b5051dab38.png)

era damage numbers:
![image](https://user-images.githubusercontent.com/69089249/181379683-2696fa24-390e-4207-91d2-40c8c75195f2.png)
![image](https://user-images.githubusercontent.com/69089249/181379751-9ac36a90-cf9c-47a3-927a-b9c0b8550acb.png)
![image](https://user-images.githubusercontent.com/69089249/181379803-56d996bd-1d1e-4dbd-baf6-7fdfe72fb62e.png)
![image](https://user-images.githubusercontent.com/69089249/181379845-30df6131-d069-49a4-8575-7f291abcf446.png)
![image](https://user-images.githubusercontent.com/69089249/181379887-51587ac9-e9a6-4b8b-ba20-35f7c624a562.png)
![image](https://user-images.githubusercontent.com/69089249/181379923-01ebaa52-33cc-4df1-8ba6-83234890a0b1.png)
![image](https://user-images.githubusercontent.com/69089249/181379972-0ae06a02-f96b-4ab1-bc55-568b758d1465.png)
![image](https://user-images.githubusercontent.com/69089249/181380016-5f6b836f-b437-404d-869b-faf56e3c9a14.png)

Offensive and support wyvern on current retail do have identical /checkparam stats on retail (confirmed by punk).

**Comment by Steam-arch** [comment]
Simurgh defencice stats seem around correct range so did a comparison with him:

Eden Elvaan  sushi drg/whm hits simurgh for around 154-261: 
(took feet and head pieces off to compensate abit the mithra vs elvaan STR difference)
![image](https://user-images.githubusercontent.com/69089249/181753069-674877ec-b480-48ee-b064-b0fce1817c4f.png)
![image](https://user-images.githubusercontent.com/69089249/181753381-4235eeca-9ebf-43f1-8ccd-b3682379e60f.png)
![image](https://user-images.githubusercontent.com/69089249/181753498-b3d826e3-26a6-4066-a05d-df4f44fe1051.png)

Eden support wyvern hits simurgh for around 111-141:
![image](https://user-images.githubusercontent.com/69089249/181753692-2f4d4820-eb2d-411c-bf33-e43e74e34edf.png)
![image](https://user-images.githubusercontent.com/69089249/181753739-66cf7710-c58c-4b29-b9ee-b1e9caa31a50.png)
![image](https://user-images.githubusercontent.com/69089249/181753790-6f92d63d-9ea6-41fc-bc0f-c49e39065306.png)
![image](https://user-images.githubusercontent.com/69089249/181753824-8ff78b8f-c78f-4fda-bedb-ce477bff80bf.png)
![image](https://user-images.githubusercontent.com/69089249/181754015-c9b1cbb5-f4a2-4595-9fe5-358c9a6784fb.png)
![image](https://user-images.githubusercontent.com/69089249/181754214-0a79cf48-1f57-406f-9dd1-e56527655ddf.png)
![image](https://user-images.githubusercontent.com/69089249/181754720-4f3fc890-b71b-4914-88ff-58e968c6807a.png)
![image](https://user-images.githubusercontent.com/69089249/181754878-54ca128f-85db-4389-a795-d57a5593a685.png)

------------------

Era mithra sushi drg/whm hits simurgh for around 156-268:
![image](https://user-images.githubusercontent.com/69089249/181751244-26d2564a-f6f1-400d-a3ac-1b1e88ad0c29.png)
![image](https://user-images.githubusercontent.com/69089249/181751310-970e8ab4-a511-491a-9b60-f6134c8eae6d.png)
![image](https://user-images.githubusercontent.com/69089249/181751380-09167f47-b848-43af-9961-9535d5c27f87.png)
![image](https://user-images.githubusercontent.com/69089249/181751412-ee170ff0-5e44-4b10-ad18-4a9196e31435.png)
![image](https://user-images.githubusercontent.com/69089249/181751495-5242676b-b9b9-4dee-83dc-cb739387a4f4.png)
![image](https://user-images.githubusercontent.com/69089249/181751542-3316e4b0-1996-4d98-988e-3d04782e8cfe.png)
![image](https://user-images.githubusercontent.com/69089249/181751571-ad73f84c-faf3-4c07-bfd8-765563254549.png)
![image](https://user-images.githubusercontent.com/69089249/181751651-d4075241-6387-4c78-8bef-80664f3a737f.png)
![image](https://user-images.githubusercontent.com/69089249/181751706-27bcf2f7-7cc3-48ef-9f53-1f4ee87a7d3d.png)
![image](https://user-images.githubusercontent.com/69089249/181751756-ecc5582a-42b7-4cc7-8bb9-8fd6dab59866.png)

Era support wyvern hits simurgh for around 79-111:
![image](https://user-images.githubusercontent.com/69089249/181751284-2a9daf82-d24d-41d7-88b4-28992791ee79.png)
![image](https://user-images.githubusercontent.com/69089249/181751455-1bf30dc6-e235-4621-ad83-ba2113c1d669.png)
![image](https://user-images.githubusercontent.com/69089249/181751593-caede033-0001-4705-8685-65c5a06bd678.png)
![image](https://user-images.githubusercontent.com/69089249/181751808-e03954c2-e0ac-4fb7-b1f2-4ca77c7e28d7.png)
![image](https://user-images.githubusercontent.com/69089249/181751853-b7348d38-ee05-46bd-bc11-2fce13c32d5b.png)
![image](https://user-images.githubusercontent.com/69089249/181751981-45f94ede-0e4d-46b9-a0ca-a54c707530b0.png)
![image](https://user-images.githubusercontent.com/69089249/181752014-6eef213f-7212-468c-a300-1118fbe6d41a.png)
![image](https://user-images.githubusercontent.com/69089249/181752118-7e986405-e989-40a8-a869-dcd0cb44ea9b.png)
![image](https://user-images.githubusercontent.com/69089249/181752155-342b1437-67b8-4fe2-a39f-88bda011fc07.png)

**Comment by Steam-arch** [comment]
Also heres a video about a taco retail drg/blu vs zoraalja, and some damage numbers wyvern vs the DRG:
https://www.youtube.com/watch?v=zkX1zQfEQcE
![image](https://user-images.githubusercontent.com/69089249/181756099-ccfa5100-4fd2-4542-b91f-3e1df47f47c7.png)
![image](https://user-images.githubusercontent.com/69089249/181756266-b36b2b27-7ffa-4e6e-897e-ce81658c238e.png)
![image](https://user-images.githubusercontent.com/69089249/181756312-b328ec5c-a1c1-41ba-93ba-26bc999ac481.png)
![image](https://user-images.githubusercontent.com/69089249/181756366-978013f8-03ae-432f-818e-785f5e43ed97.png)
![image](https://user-images.githubusercontent.com/69089249/181756530-6734034d-3dbd-43c1-ab47-44faf80c23cb.png)
![image](https://user-images.githubusercontent.com/69089249/181756579-37345719-d6f7-4c5f-9025-8595e3b8bb8f.png)
where the wyvern hits for around 1/3-1/4 of what the DRG hits for. Somewhat surprised that the wyvern vs simurgh is hitting for that much hmm

**Comment by Steam-arch** [comment]
Heres 1 more decent era video of a drg/blu (that ate a taco I think), below damage numbers wyvern vs the DRG
https://www.youtube.com/watch?v=Ej0rc2tKmxk
![image](https://user-images.githubusercontent.com/69089249/181763344-d07c70b5-cf7c-4c1f-ae8a-2e5bdda246b1.png)
![image](https://user-images.githubusercontent.com/69089249/181763413-ba31c38c-7237-49d4-992b-6131547e9755.png)
![image](https://user-images.githubusercontent.com/69089249/181763458-8b8911f6-5a47-4f3e-977f-080bbb837376.png)
![image](https://user-images.githubusercontent.com/69089249/181763485-5ce8e9a3-982b-48aa-b0f7-1489457dfbed.png)
![image](https://user-images.githubusercontent.com/69089249/181763510-e081c660-8881-4077-93f8-44e6f1c4964d.png)
![image](https://user-images.githubusercontent.com/69089249/181763553-b119dd1e-32df-47f8-8429-cddff4cb983c.png)
![image](https://user-images.githubusercontent.com/69089249/181763586-9438782f-74f3-4251-810b-4cb93c6b3848.png)
![image](https://user-images.githubusercontent.com/69089249/181763639-0db08536-62fd-4b36-8532-9c787bdec853.png)
era wyvern hits for 1/3-1/5 of what the drg hits for here aswell

**Comment by ThoseWhoFight** [comment]
The wyvern in the Zoraal Ja video is capped on exp/levels, but still hits harder on average on Eden. Granted it could be because the NM itself on Eden is likely inaccurate and requires an audit of its own, but it's hitting for quite a bit less on the retail video in a scenario where it should be stronger than current Eden's non leveled wyverns.

"As of the March 10th, 2008 update, a Dragoon's wyvern's attributes are temporarily boosted over time as experience or limit points are gained by the player. This boost includes increased HP (max 24% more, improving breath abilities), improved damage per hit, and a minor accuracy bonus. All stat boosts gained this way are removed, returning the wyvern to its normal stats, should the Dragoon change areas, dismisses his or her wyvern in any way (via "Dismiss" or "Spirit Surge"), or if the wyvern or Dragoon is K.O.'d. Furthermore, Experience/limit points gained from any large scale battles (such as Besieged and Campaign battles) will not boost the wyvern's stats."

![image](https://user-images.githubusercontent.com/37572397/181775768-c22d6abd-280e-4238-a970-309b90601dda.png)


I manually tallied the melee average for the wyvern in the video and it averaged 55.88 MAVG on the Pkuucha mob. In an Eden parse I did yesterday vs the same target, it averaged 86.33

For comparison I manually tallied every hit for the Dragoon too, just to get an idea, for which there is no doubt a disparity in gear equipped etc. but just for posterity's sake.
Drg mavg was around 200 in video. Eden Drg mavg was 173.00

Video Drg likely using augmented Fay Lance w/ 94-95 base damage, and maybe an extra 5 STR 15 ATT in stats from gear
vs Eden Drg's Mezraq and gear no food used.

I'm going off of memory because I'm the Drg in the retail video lol

**Comment by ThoseWhoFight** [comment]
Also can confirm the wyvern hits Aura statues for much more than that on Eden currently, but I can go to sky later and add to this for proof if needed.

**Comment by Steam-arch** [comment]
I might be wrong but dont think the wyvern leveling update has hit during the making of the zoraalja video? says +12 years and the patch was  09/08/2010

![image](https://user-images.githubusercontent.com/69089249/181782869-14944b3f-9eb7-4d80-82de-0c52dcd856a1.png)

Should be just the 2008 update active I think? I didnt check how zoraalja/aura stats compare on eden so not sure about those.

**Comment by ThoseWhoFight** [comment]
![image](https://user-images.githubusercontent.com/37572397/181784522-8b04a793-4994-406e-9425-2166ad2174c2.png)
 
It's after the wyvern exp patch, which was 12/09/08
https://ffxiclopedia.fandom.com/wiki/2008_-_(12/09/2008)_The_December_Version_Update_Cometh!

![image](https://user-images.githubusercontent.com/37572397/181784919-1210fc0b-a8ae-4bbc-bc43-c78dde0ba7ad.png)

You can also tell it's post update, because my wyvern breaks 500 HP healed w/ healing breath multiple times, which wasn't possible prior to capping wyvern exp (which increases wyvern max HP).

**Comment by Steam-arch** [comment]
Yeah so to sum up, both patches are OOE.

Ul'Phuabo video doesnt have 2008 patch nor 2010 patch
Zoraalja video has 2008 patch but not 2010 patch implemented 
Simurgh video has both 2008 and 2010 patch (so way out of OOE)
Aura Statue video has only 2008 patch implemented but not 2010

So only true "era" vid/comparison from these is the phuabo one.

(also gj on the zoraalja kill)

**Comment by ThoseWhoFight** [comment]
Also totally posted the wrong update in that last reply about patch dates by mistake, it was the March 2008 patch. December patch was just for the heal on level up I guess, but doesn't change the point of the video upload date and patch

**Comment by Steam-arch** [comment]
Updated the posts abit and deleted the simurgh one since it was grossly ooe. Ill do the abraxas one later maybe it gives an idea about the 2008 patch buff

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
