### ISSUE TITLE
Weaponskills don't seem to be gaining +100 ACC boost on first hit

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#518]
Info on +100 accuracy boost confirmed here (translate page to english): http://forum.square-enix.com/ffxi/threads/49839-%E5%A4%9A%E6%AE%B5%E3%82%A6%E3%82%A7%E3%83%9D%E3%83%B3%E3%82%B9%E3%82%AD%E3%83%AB%E3%81%AE%E5%91%BD%E4%B8%AD%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6?p=571812#post571812

Fan translation of the same article from BG: https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6633828&highlight=accuracy#post6633828

"The first hit of a weapon skill gains +100 accuracy. Originally, this property was meant to counterbalance the fact that elemental weapon skills have no risk of missing. Elemental weapon skills can greatly increase the odds of a successful skillchain, so we added the accuracy bonus to the first hit of a weapon skill. Under this assumption, every hit from the second one onwards from a multihit weapon skill is considered the “proper” value."

**Comment by Aneyus** [comment]
That link also explains how sea gorgets work with multi hit WS

**Comment by SleazyFFXI** [comment]
Please fix this,   seems like my WS accuracy is way worse than my auto attack accuracy,    even capped skills and using sushi in a party and my WS's miss more than they land....
