### ISSUE TITLE
Dragoon Wyvern's Healing Breath is queued when slept but shouldn't be

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5182]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On Eden a wyvern will receive the command to use Healing Breath while slept and hold onto that command until it wakes up. This is not the case on retail.

Eden:
![image](https://user-images.githubusercontent.com/13668758/181751576-9dab4331-45cc-4ac5-b572-6c0a3100bbdc.png)

Retail:
![image](https://user-images.githubusercontent.com/13668758/181751617-78cb53d8-b7ed-4aaa-a5ba-53ee38cbdd1e.png)

Wiki: https://ffxiclopedia.fandom.com/wiki/Healing_Breath
![image](https://user-images.githubusercontent.com/13668758/181751687-5fdf74ea-e089-4cd8-a82f-7a5cf886889a.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
