### ISSUE TITLE
Dragoon's Wyvern should not using Healing Breath while under the effect of Amnesia

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5183]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On Eden wyverns are currently able to Healing Breath while afflicted with Amnesia. Per the wiki this should not be possible.

Eden:
![image](https://user-images.githubusercontent.com/13668758/181752492-ddd32008-6c0d-419e-b93e-f4cc75eae863.png)

(Sorry for the amateur screenshot of mashing the button XD)

Wiki:
"Because Healing Breath is essentially a weapon skill (it is readied and consumes TP), it cannot be used when the wyvern is afflicted with Amnesia. It will appear to be readied, but will not execute. Of course, the same still applies if the wyvern is afflicted with any other status ailment that prevents actions, such as sleep."

https://ffxiclopedia.fandom.com/wiki/Healing_Breath

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
