### ISSUE TITLE
Level sync issues with Dragoon's Wyvern

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5184]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Per the wiki, a wyvern is the only pet that will stay out when put under the effects of level sync.

![image](https://user-images.githubusercontent.com/13668758/181756123-e9899ce0-35da-4791-a109-d7ab62b24bf7.png)
Modern wiki: https://ffxiclopedia.fandom.com/wiki/Level_Sync#:~:text=Level%20Sync%20is%20a%20party,that%20of%20a%20designated%20player.
Era wiki with same quote:
https://ffxiclopedia.fandom.com/wiki/Level_Sync?oldid=920053

On Eden, this is true, but the way it is implemented causes two unintended results:

1. When you have an injured wyvern on Eden and level sync down, it is instantly filled to full HP (it's changing level, which I feel is relevant)

Here is the same thing on retail, note that its health % changes, but its current HP remains the same, only the max HP changes:
![image](https://user-images.githubusercontent.com/13668758/181756666-45bddff0-c4b5-4e0f-9d93-e9e325a72f63.png)

To reproduce on Eden - Summon a wyvern, set it to immortal, get it to 1% health, party with a 2nd character that is at least level 10 and a lower level than you. Level Sync to them, you will see your Wyvern instantly is restored to full health.

2. The second bug is really the same as the first but shown in the reverse situation. When you REMOVE level sync and the wyvern grows in level (this is correct, we retail tested) the wyvern will also heal to full health. 

Retail video showing the current health should stay the same and only the max HP should change, and also showing that the wyvern grows in level (you can tell by comparing the /checkparam <pet> from before and after the sync wearing off)

https://www.youtube.com/watch?v=X59A-x2HICY

To reproduce on Eden - Summon a wyvern, level sync down to another character, set wyvern to immortal and get it to 1% health. Drop sync and note that the wyvern is healed to full.

version 30181205_0

**Comment by Dukilles** [comment]
Resolved by 12/14/24 update.
