### ISSUE TITLE
Rivals quest wrong itemID in event

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5187]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

for the "Rivals" quest in Bastok, the "Obtained" at the end of the cutscene says Wolf Mantle (ID 13571) when it should be Wolf Gorget (ID 13089). Item actually obtained is correctly Wolf Gorget though.

![image](https://user-images.githubusercontent.com/11255886/182001867-96042b62-6453-4c07-9065-36b3d7d22c22.png)

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
