### ISSUE TITLE
Desynthesis recipes missing for Copper Hairpin +1

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5188]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver. 30181205_0

Attempted desynthesis on copper hairpin +1 and was unallowed to even though it is listed on one of the wikis from in era edits.  BG-Wiki conflicts with this due to the absence of such information.

https://ffxiclopedia.fandom.com/wiki/Copper_Hairpin_%2B1?oldid=687758

I'm sure there are several other desynthesis recipes that were possible during era that are not on Eden because there is no recipe added in the database.  Many other items possibly need to be investigated for missing desynthesis recipes as these are not the first I've encountered that are unable to be desynthesized when it should be possible according to some sources.  Hopefully more players will report missing recipes as they come across them.  The free login campaign begins next week, so I'll try to confirm both are possible and reply back here with my results.

**Comment by KnowOne134** [comment]
I'd make this 2 reports with titles for the item. When we fix things we read titles 1st to do what we can. Description is key. :2 cents:

**Comment by DeuceFFXI** [comment]
Apologies, fixed the title.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
