### ISSUE TITLE
Desynthesis recipes missing for Brass Dagger

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5190]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver. 30181205_0

Attempted desynthesis on a brass dagger and was unallowed to even though it is listed on one of the wikis from in era edits. BG-Wiki conflicts with this due to the absence of such information.

https://ffxiclopedia.fandom.com/wiki/Brass_Dagger?oldid=687015

I'm sure there are several other desynthesis recipes that were possible during era that are not on Eden because there is no recipe added in the database. Many other items possibly need to be investigated for missing desynthesis recipes as these are not the first I've encountered that are unable to be desynthesized when it should be possible according to some sources. Hopefully more players will report missing recipes as they come across them. The free login campaign begins next week, so I'll try to confirm both are possible and reply back here with my results.

**Comment by DeuceFFXI** [comment]
[Video](https://youtu.be/t2TnkANkYXg) confirmation of wiki data regarding this item on retail.

NQ: bronze ingot
HQ1: copper ingot

![img_20220815_002108](https://user-images.githubusercontent.com/61279359/184593780-6c49df82-ea2c-4f9c-b335-acf593dfb928.jpg)

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
