### ISSUE TITLE
Nyzul isle boss evasion too high

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5191]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Atleast khimaira & Cerb & hydra evasions seem too high in nyzul.  I often go mnk and without sushi acc revolve around 360-375 pre focus, and I whip the air propably more than the boss so I would assume their evasions are the same or close to the real versions (?)

They should be much lower:
Retail test Floor 60:
![image](https://user-images.githubusercontent.com/69089249/182040708-926f687a-15e2-47cf-9efe-5406aa50b9c6.png)
![image](https://user-images.githubusercontent.com/69089249/182040728-952b777e-3940-4087-b6f4-c53786ddd40b.png)
Final acc for cerb was 86%:
![image](https://user-images.githubusercontent.com/69089249/182040752-c9983834-bf51-4151-a9b2-706d1464af4a.png)

if 364 is 86% acc I would assume you cap around ~390 (?) on Nyzul cerberus atleast

**Comment by Steam-arch** [comment]
100 floor Hydra 364 acc:
![image](https://user-images.githubusercontent.com/69089249/182041666-7a06bc0c-0b4d-475d-b1f0-2b1754d8ec33.png)
Died accidently, they hit pretty hard

**Comment by 59blargedy** [comment]
if you are level 99, and are using ilevel gear, you are ignoring level correction entirely.

**Comment by Steam-arch** [comment]
Right, forgot about the level correction since it doesnt exist because they are lower level, retail problems! Alright closing since im defenitely not redoing as 75 sync.
