### ISSUE TITLE
KS99 Early Bird Catches the Wyrm Redux

### ISSUE THREAD

**Issue by TracentEden** [EdenServer/community#5192]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Steps to Reproduce:

In KS99 Early Bird Catches the Wyrm, if the wyrm is brought from above 66% to below 33% very quickly (before the wyrm has a chance to go to the center and fly) by like big SC + MB, the wyrm behavior becomes unstable and it jumps up and down rapidly spamming touchdown. This is confirmed to still occur even after the recent fix for this KSNM (which I think was related to a draw-in crash issue).

Relatedly, if the wyrm was stunned when it is attempting to land (at or near 33%) the wyrm will stay in the air (which I assume is not intended behavior?). I am not sure if this still occurs after the recent fix.

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
