### ISSUE TITLE
Dragoon has OOE Evasion and Parrying Skill

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5193]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Dragoon is using its OOE Parrying and Evasion skill per the modern wiki when it should be using era skill caps:
![image](https://user-images.githubusercontent.com/13668758/182141355-1218e224-b556-4df4-8c4c-d5cbbf8ea4fe.png)
https://ffxiclopedia.fandom.com/wiki/Dragoon

Era:
![image](https://user-images.githubusercontent.com/13668758/182141436-e598f374-1e0e-4b59-9590-ef5df8bea883.png)

https://ffxiclopedia.fandom.com/wiki/Dragoon?oldid=704693

Dragoon on Eden, with annotation because I have Parrying and Evasion merrits:
![image](https://user-images.githubusercontent.com/13668758/182141878-af3ed54f-5f98-4401-afdc-518f14484acb.png)

Pictures of skill calculators to show for comparison/validation (Note, not DRG, just showing that B rank is 250 and B- is 240)
![image](https://user-images.githubusercontent.com/13668758/182142003-9ff9de22-79fc-431f-87da-68b7b3451165.png)
![image](https://user-images.githubusercontent.com/13668758/182142097-6b6a05fc-0611-480c-9b2a-1fffffd46dfe.png)

Thanks to Palorm for pointing this discrepancy out

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
