### ISSUE TITLE
Ninja Throwing Skill is using OOE Rank

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5194]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Ninja is using the OOE A+ Throwing skill rank instead of the era A- rank.

Modern wiki (https://ffxiclopedia.fandom.com/wiki/Ninja):
![image](https://user-images.githubusercontent.com/13668758/182142429-72cf15eb-8e9c-4d1d-8a1f-e74982a03646.png)

Era wiki (https://ffxiclopedia.fandom.com/wiki/Ninja?oldid=652966):
![image](https://user-images.githubusercontent.com/13668758/182142504-c59a0b7a-d9dd-4514-af1c-c4af23dfba8b.png)

Eden Ninja Skill reflecting OOE A+:
![image](https://user-images.githubusercontent.com/13668758/182142812-06ac25b0-23b0-46c5-9fc4-cbe3990fb9b0.png)

Skill Calculator to show what A- should be:
![image](https://user-images.githubusercontent.com/13668758/182142655-20ac0a32-7af2-4444-9d20-c17838bb3aba.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
