### ISSUE TITLE
Ranger Quest Old Sabertooth not dying correctly

### ISSUE THREAD

**Issue by LeaflyXI** [EdenServer/community#5195]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Old Sabertooth dies in 30~ seconds without walking around on eden. Should take a few minutes. 
Eden:
![image](https://user-images.githubusercontent.com/110419727/182219090-e7683539-5a68-4796-89ea-501526bd07a3.png)

Era~ video:
https://www.youtube.com/watch?v=d_un1NqECzI&ab_channel=FinalFantasyDocumentary

version: 30181205_0

**Comment by KnowOne134** [comment]
1 min 30 seconds to be exact

**Comment by KnowOne134** [comment]
the timing is now correct, pathing will need changed still

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
