### ISSUE TITLE
Razor Fang should be slashing damage not piercing

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5199]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

This could probably use some retail validation if that's possible from anyone, but I can't find anything that says that Razor Fang should be piercing, and it is currently set to Piercing on Eden (tested in limbus):

![PiercingBasicAndRazor](https://user-images.githubusercontent.com/13668758/182829582-c9ff59fb-982e-4bf0-a656-80447514b198.JPG)

And here is a screenshot just to clarify the auto in the above picture is bludgeoning so there is no confusion
![image](https://user-images.githubusercontent.com/13668758/182829490-2623bc7d-a489-437a-9fe9-5284cd672571.png)

The following two wiki sources don't seen to specify a damage type at all:
http://wiki.ffo.jp/html/23627.html
https://ffxiclopedia.fandom.com/wiki/Tiger_Familiar
Also here is the Razor Fang wiki page, although its the mob version and differs on # of hits from the familiar page: https://ffxiclopedia.fandom.com/wiki/Tiger_Familiar

However this bg page has it listed as slashing
https://www.bg-wiki.com/ffxi/Category:Jug_Pets

![image](https://user-images.githubusercontent.com/13668758/182830157-a99a47f2-2a8b-4e33-a6c0-ba5e480f5551.png)

Would benefit greatly from a retail test due to the lack of detail on the wiki pages, but I can't find anything suggesting it should be piercing.

Note: As far as the number of hits / damage goes, I tried researching but it was also inconsistent. I compared an era Under Observation video to our UO numbers though and they are very close.

version 30181205_0

**Comment by madmikeblvd** [comment]
BG page seems post 2020 update data, so we would have to see if there is any SE update data showing a change between server era and this. Also the main wiki seems to only have the mob version the the move not the BST pet version, and yeah no damage type is listed anywhere in the historical part of fandom wiki whomp whomp.

Interesting but it would seem strange to take it from BG Wiki's 2020+ perspective that it's slashing as opposed to piercing/puncture damage from teeth since piercing would at least physically make more sense. 

"A puncture is a wound made by a pointed object such as a nail, knife, or sharp tooth."

**Comment by Snugglepunk** [comment]
Current retail Razor Fang is slashing and auto attacks are blunt.  
![image](https://user-images.githubusercontent.com/56851217/183232148-6a5eb972-c4c2-45ee-b7a8-54b64891f1b3.png)
![image](https://user-images.githubusercontent.com/56851217/183232099-31c588f5-0af8-4d97-854c-57649ba0a7ab.png)
![image](https://user-images.githubusercontent.com/56851217/183232102-f5f5b525-68af-4be9-b900-749361772f33.png)
![image](https://user-images.githubusercontent.com/56851217/183232203-6268ebc7-28ea-4122-bbfa-366b915de017.png)
