### ISSUE TITLE
Crayfish are catchable in the lake in East Sarutabaruta

### ISSUE THREAD

**Issue by joe-graves** [EdenServer/community#5201]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

According to all wikis and my recollection from era, crayfish should only be catchable in the ponds in East Sarutabaruta, but I catch them when using little worms in the lake. Also in the rivers

https://classicffxi.fandom.com/wiki/East_Sarutabaruta#Fishing

![ESarutaBarutaFishing](https://user-images.githubusercontent.com/62125399/183300394-ad4f485d-529b-4a93-81ee-1569a2ce082a.png)

![CrayfishLake](https://user-images.githubusercontent.com/62125399/183300404-7274d102-3596-49c9-944a-c782df70f1dd.png)

ver 30181205_0

**Comment by falzum** [comment]
Wiki is unreliable. We use https://www.great-blue.jp/?aid=038&bid=&lng=en for our fishing system.

**Comment by 59blargedy** [comment]
while not extensive testing, 60 mins of fishing at the lake with 2 different baits yielded no crayfish, and .02 nanoseconds at the river yielded a crayfish. im inclined to believe wiki is right on this one, which is not often the case.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
