### ISSUE TITLE
Nyzul Archaic Ramparts should be "Impossible to gauge"

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5204]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Should gauge as impossible to gauge, Unless this was changed at some point?

eden:
![image](https://user-images.githubusercontent.com/69089249/183645993-e74ae00b-902b-4b06-81ea-aab88d814500.png)

retail:
![image](https://user-images.githubusercontent.com/69089249/183646632-01c56b86-f023-4b75-87a0-b03965f54367.png)

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
