### ISSUE TITLE
BST Ready Razor Fang should be a single hit not double

### ISSUE THREAD

**Issue by Snugglepunk** [EdenServer/community#5208]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I believe Edens version of the BST Ready move Razor fang is 2 hit damage and it should be a single hit. 

Tested on many NIN mobs in dynamis it always only took 1 single shadow each time
![image](https://user-images.githubusercontent.com/56851217/184128945-5a80407b-529b-4dbc-9401-6d7bab6f8c27.png)

Compared to a known 2 hit ready move
![image](https://user-images.githubusercontent.com/56851217/184128985-1de89f80-4fb3-466b-add4-c0d5258bb3cf.png)

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
