### ISSUE TITLE
Making a Mockery Issues

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#5212]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently the Mocking Colibri does less damage than it should, on retail it feels a lot stronger with it's auto attacks and pecking flurry. Wisecrack duration may also be longer than it should on Eden, on retail it seems to last 30 seconds. Also currently aluminum sheet is a possible reward from the chest when it should be an aluminum ingot instead (first video shows this).

https://www.youtube.com/watch?v=er6MuwhEkU0 - Me: 310 defense, no PDT / Automaton: 313 Defense, 37.5% PDT
https://www.youtube.com/watch?v=EWS8cGVauBc - Automaton: 313 Defense, 32.5 % PDT
(timestamp for wisecrack in both video descriptions)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
