### ISSUE TITLE
Diabolos quest (Waking Dreams) reward menu overwrites top item in list

### ISSUE THREAD

**Issue by ConteAlmaviva** [EdenServer/community#5213]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

When selecting a reward for the Waking Dreams quest, Diabolos's Pole appears at the top of the list.  Selecting any other item in the list (e.g. to see stats on the item) and then backing out appears to overwrite that top item with whatever you selected, and appears twice in the list.

Here I selected Diabolos's Earring to look at its stats, hit the "Wait!" option, and when I went back to the root menu Diabolos's Earring had replaced the top item (Diabolos's Pole) and appears twice in the list.

![image](https://user-images.githubusercontent.com/8880996/184703315-b2c293d3-9194-456b-b80d-73c47c5bab93.png)

I then selected Diabolos's Ring and hit "Wait!" and when I went back to the top menu, Diabolos's Ring replaced the top item and appears twice in the list.

![image](https://user-images.githubusercontent.com/8880996/184703343-a63bd4be-1be1-4422-9f55-3232a0390d09.png)

**Comment by ConteAlmaviva** [comment]
Version is 30181205_0.  I wanted to get Diabolos's Pole, so I force quit and logged back in, and after doing so Diabolos's Pole appeared back at the top of the menu and I was able to get it.

**Comment by 59blargedy** [comment]
ill add your notes to the existing report, thank you!!
