### ISSUE TITLE
Scholar and Dancer Die are not on the AH

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#5218]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Scholar and Dancer die were added to the npc Chayaya but have not been added to the AH.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
