### ISSUE TITLE
Dynamis: Dropping glass and having time expire should NOT instantly kick you, it should be a 30 second countdown.

### ISSUE THREAD

**Issue by Aslipperyotter** [EdenServer/community#5219]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

[Source](https://enedin.be/dyna/html/general_info.htm)

Currently in Dynamis, dropping your/a glass or having time expire results in immediately being zoned out. This is incorrect and it should be a 30 second countdown.

![image](https://user-images.githubusercontent.com/77862983/185508154-50ecc66a-a8e6-4dea-bf23-71df8831f48d.png)

**Comment by DeuceFFXI** [comment]
https://www.youtube.com/watch?v=MjuyODCZaUI

Here's an example of this happening.

**Comment by KnowOne134** [comment]
corrected in 8/7/2023 update
