### ISSUE TITLE
Kreutzet spams Stormwind 13x in a row

### ISSUE THREAD

**Issue by Eme-FFXI** [EdenServer/community#522]
![inkedeme_2018 12 17_213750_li](https://user-images.githubusercontent.com/44308523/50114451-d5d44200-0244-11e9-8275-94264bf58acf.jpg)
![inkedeme_2018 12 17_213642_li](https://user-images.githubusercontent.com/44308523/50114452-d5d44200-0244-11e9-96a6-a46be08b473a.jpg)

I was under the impression it can do it 3x in a row and that multiple times. But here we have 13x Stormwind in a row. It did use 3x in a row earlier in the fight.

Cheers

**Comment by gweivyth** [comment]
Yeah I had this happen to me a few times on Kupo too.  Kruetzet is a jerk.

**Comment by Altnob** [comment]
It's my understanding he's SUPPOSED to use Stormwind 3x in a row if he uses Stormwind. He gets really nasty under 25%

**Comment by godmode** [comment]
I was unable to reproduce this. Is this still happening? I only got 3x in a row.
