### ISSUE TITLE
Bst Pets shouldn't respawn while the master has aggro

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5221]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
version 30181205_0

Beastmaster monsters shouldn't be able to summon their pet when they have aggro.

It's currently possible to aggro Beastmaster monsters and hold them. They will continue resummoning their pets as if they are idle with no aggro. It can easily be abused to power level, it makes it effortless to pull the pet without risk of linking the master.

https://www.youtube.com/watch?v=YLJ7vqoheuo

**Comment by 59blargedy** [comment]
going to tack your info on to this one: https://github.com/EdenServer/community/issues/5091
