### ISSUE TITLE
Royal Archer's Sword wrong model

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5223]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Seems like its a wrong model?
![image](https://user-images.githubusercontent.com/69089249/185786104-b6521e0a-9758-4ea3-bebd-489f2eed25e4.png)

**Comment by Steam-arch** [comment]
![image](https://user-images.githubusercontent.com/69089249/185969503-4a899098-56e0-4cea-ba75-d046e915bc48.png)
Actually a pretty cool model

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
