### ISSUE TITLE
Sea Hog NM doesn't have variable spawn location

### ISSUE THREAD

**Issue by ThoseWhoFight** [EdenServer/community#5224]
- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Per ffxidb, supposed to spawn in the entire area, but currently spawns in the same spot(red dot) similar to how Upyri used to.
![21 20_rCm41sN7Ez](https://user-images.githubusercontent.com/37572397/185822272-fd297e82-c53c-4b51-b8af-9b80e6619d28.png)
http://www.ffxidb.com/zones/176/sea-hog

This + no claim shield makes it impossible to compete vs better connections.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
