### ISSUE TITLE
Ranged WS with Invisible did not wear off the effect

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#5227]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

while invisible engaged a mob my party was fighting used Detonator WS it killed mob and invisible did not wear off

**Comment by Mildew-Von-Eden** [comment]
Proof this isn't working as intended?

**Comment by KnowOne134** [comment]
na ill test it later, if i dont jot it down ill forget, but doesnt sound correct

**Comment by Steam-arch** [comment]
Should wear
![image](https://user-images.githubusercontent.com/69089249/186397610-978103eb-eccc-4aff-a799-129aaa423db3.png)

**Comment by KnowOne134** [comment]
Corrected 9/21/2022 update
