### ISSUE TITLE
Dosetsu Tree should be stationary

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5228]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Shouldnt roam like a normal NM, its a tree after all. Defenitely roams on eden.
![image](https://user-images.githubusercontent.com/69089249/186388581-1f38d2a5-722b-4ff6-9b3c-7cb14a46bbe0.png)

![image](https://user-images.githubusercontent.com/69089249/186390218-a91f08aa-2dd4-4659-bdaf-1e3cb33299b4.png)

**Comment by 59blargedy** [comment]
resolved in September 21, 2022 update
