### ISSUE TITLE
moglification is not active on eden

### ISSUE THREAD

**Issue by Bait31** [EdenServer/community#5230]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
it doesn't appear that moglification is working on eden. A Furnishing that gives the crafter increased skill and lowers the chance of a failing synthesis. As we have changed the dates on Eden this should now be available. here are some links to discussions on discussion pages re the new addition of moglification items (signboards) and also a historical account on ffxi 

https://ffxiclopedia.fandom.com/wiki/Final_Fantasy_XI_Fan_Festival_2007

fan festival 17th Nov 2007 day 2 5.18pm : 
New furniture for guild trading contract quests. New sign boards and flags. New furniture will be sign boards, which will improve crafting skill and decrease the rate items are lost while crafting.

discussions:

27th Nov 2007
https://www.bluegartr.com/threads/51277-Moglification
21st Jan 2008
https://www.ffxiah.com/forum/topic/64/signboard-possabilities

ffxi link 

Revision as of 17:03, 29 November 2007 by [Spops]
https://ffxiclopedia.fandom.com/wiki/Weaver%27s_Signboard?oldid=387764

thank you

**Comment by 59blargedy** [comment]
resolved by another dev in November 21, 2022 update
