### ISSUE TITLE
Lufaise Gigas - Incorrect drop table/rate(s)

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5231]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The various Gigas in Lufaise Meadows seem to have too high of a drop rate. Sadly FFXIClopedia has basically no info, and FFXIDB doesn't have a good sample size for the gigas either (http://ffxidb.com/zones/24/). Looking at the various Gigas in Lufaise on FFXIDB though, they seem to all have essentially the same drop table. 
The best example is http://ffxidb.com/zones/24/gigas-braver which in 442 kills only had 69 diamonds (15%), 15 maple shields (3.3%), and 5 gigas necklace (1.1%) across mostly unknown TH/TH0. Meanwhile on Eden I've killed 174 Gigas Bravers with TH4 and have gotten 112 socks (64.3% and doesn't exist on any of the gigas drop tables on ffxidb), 114 necklaces (65.5%), 10 diamonds (5.7%), and 2 shields (1.1%)

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
