### ISSUE TITLE
Sandoria Mission Journey Abroad 2-3 Missing Text

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#5232]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

In Journey Abroad you are given a key item "Shield Offering" to give to an NPC Uu Zhoumo. On Eden currently when you hand him the KI there is no text indicating you turned in your KI. https://i.imgur.com/SweMNcY.png

On retail there is an extra line that says "Offered up key item: Shield Offering!" https://i.imgur.com/FuoBZ6k.png

**Comment by 59blargedy** [comment]
resolved in September 21, 2022 update
