### ISSUE TITLE
Qiqirn Poulterer ranged attack behavior incorrect

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5233]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

Qiqirn Poulterer in Alzadaal Undersea Ruins (and possibly other areas, Mamook) will use melee attacks after falling below ~70% HP. They should only used ranged attacks from a 13' distance.

https://www.youtube.com/watch?v=9hum3JLDHbg

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
