### ISSUE TITLE
Ice Shield wrong model

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#5234]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

Ice Shield on Eden currently looks like: https://i.imgur.com/cKe2HdR.png

Ice Shield on Retail looks like: https://i.imgur.com/gJo207V.png

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
