### ISSUE TITLE
Chiroptera Dagger wrong model

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#5235]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

Chiroptera Dagger on Eden looks like: https://i.imgur.com/eDn2PCA.png

Chiroptera Dagger on retail looks like: https://zam.zamimg.com/ffxi/i/images/fashion/daggers/F-Chiroptera-Dagger.jpg

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
