### ISSUE TITLE
Able to obtain multiple of same RSE Item from The Goblin Tailor

### ISSUE THREAD

**Issue by Frozzen907** [EdenServer/community#5236]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version: 30181205_0

Currently on Eden you are able to Obtain more then 1 of the same RSE item from "The Goblin Tailor" Quest. 

I First noticed this after doing one RSE chest in Ordelles Cave & Deciding to wait to do the rest in Gusgen Mines. Once the Day for my races RSE was in Gusgen Mines i went and continued to do the quest. When going to collect the first piece of my RSE from my Gusgen run, i noticed i could choose the same piece i obtained from the run i did a few days before.
 
Classic & Retail Wiki  both states you can repeat The Goblin Tailor 4x (Once per reward item(Body, Hands, Legs, Feet))
 
Classic Wiki: https://classicffxi.fandom.com/wiki/The_Goblin_Tailor?so=search
Retail Wiki: https://ffxiclopedia.fandom.com/wiki/The_Goblin_Tailor?so=search

Steps to reproduce: 
1.) Start The Goblin Tailor Quest, Go Find your first Magical Pattern, Return to NPC for Reward.  
2.) Send Reward to another character or remove it from your possession. 
3.) Continue The Goblin Tailor Quest & when you go to receive your next reward you will be able to claim the same reward again.

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
