### ISSUE TITLE
Tonberry Pursuers should not drop Unlit Lanterns

### ISSUE THREAD

**Issue by Appotemmis** [EdenServer/community#5237]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

As per the below image, Tonberry Pursuer's should not drop Unlit Lanterns, only Flickering Lanterns

![image](https://user-images.githubusercontent.com/77178224/187051402-99577086-fe58-4f63-b601-6576c8be981f.png)

Era Wiki (https://classicffxi.fandom.com/wiki/Tonberry_Pursuer) does not display this on the drop list, neither does BG (https://www.bg-wiki.com/ffxi/Tonberry_Pursuer) nor FFXIDB (http://www.ffxidb.com/zones/159/tonberry-pursuer). The only Wiki that does is current ffxicylopedia with a 20/305 drop rate but this is the only place it is referred

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
