### ISSUE TITLE
The Worm's Turn - Flesh Eaters not charmable

### ISSUE THREAD

**Issue by Kagekiki** [EdenServer/community#5238]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
The Flesh Eaters in The Worm's Turn are not currently Charm-able like they are supposed to be. According to strategies listed in 2006 Wiki BST should be able to Charm the Flesh Eaters and use them against the Main Target (Flayer Franz). When attempting to use this strategy this evening the charm reacted as if the Flesh Eaters were NMs and not regular monsters as they are supposed to be. This resulted in my whole team (5 BST/WHM and a NIN/WAR) getting dunked on by 16 worms.  I made sure to attach the following to support my claim:

1. Screen shot of the Worms Binding not getting Charm. (Please notice none of the Charms failed just bound instead)
 ![Lunarblade_2022 08 27_195230](https://user-images.githubusercontent.com/64233561/187058914-c2fd1e0b-db42-4e73-b59a-5271df10c679.png)

2. Link to 2006 BST strategy on wiki.
https://ffxiclopedia.fandom.com/wiki/The_Worm%27s_Turn?oldid=324225

**Comment by 59blargedy** [comment]
resolved in September 21, 2022 update
