### ISSUE TITLE
Recreated adventure fellow does not progress pass lv 50

### ISSUE THREAD

**Issue by Azmatic1** [EdenServer/community#5239]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Prior to recreating my adventure fellow for a new skin I had a capped(65) fellow. I still have all the limitbreak quest mark as completed  and can no longer receive a new limitbreak quest but my fellow does not level past 50. Furthermore, it skips over the dialogue in regards to their experience gain or progression.

**Comment by KnowOne134** [comment]
This needs more quests cleared from logs on starting over

**Comment by KnowOne134** [comment]
Corrected on 11/21 patch
