### ISSUE TITLE
San d'Oria mission 2-3 Journey to Bastok

### ISSUE THREAD

**Issue by gosen-willow** [EdenServer/community#524]
Went to do Sandoria mission 2-3 starting with windurst then bastok and talked to all the right NPCs. Savae E Paleade followed by Pius and Grohm.
I was not able to do the BCNM fight and continue with the dragon fight. I contacted the GM and all he was able to confirm is that i am missing the key item "dark key"then to contact you to resolve the issue.
In the event that i missed a step I went and talked to all mission 2-3 NPCs to include the windy portion as well and retraced my steps. The bug seems to be i did not get the key item to fight the BCNM when i spoke to the NPC

**Comment by godmode** [comment]
If this is still an issue please request a GM ticket. We are currently looking into the issue but have enabled GMs to progress you through this mission if you meet the necessary requirements.
