### ISSUE TITLE
Chariot NMs in Nyzul use the wrong models. 

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#5244]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

All "Eliminate enemy leader." Chariot bosses use the Long-Armed Chariot model, instead of their proper models.

Battledressed Chariot should be thew same as Battleclad Chariot (Discoid)
![image](https://user-images.githubusercontent.com/62901732/188006795-6a77e6cf-08de-4402-83ab-2fe001834230.png)

Long-Horned Chariot (Brainjack)
![image](https://user-images.githubusercontent.com/62901732/188006946-a6606746-ecce-425f-bd8e-7e09d9a9b9b3.png)
(Should be correct model)

Long-Gunned Chariot should use the Long-Bowed Chariot model (Homing Missle)
![image](https://user-images.githubusercontent.com/62901732/188007125-a899f95d-f07d-4759-ace1-e6011f9592dd.png)
![image](https://user-images.githubusercontent.com/62901732/188007150-a0212ede-2bb4-4eac-bc8c-3133d128bca5.png)

Shielded Chariot - (Mortal Revolution)
![image](https://user-images.githubusercontent.com/62901732/188007268-0ba9ba2f-1118-470b-b386-0b6e927b6977.png)

**Comment by 59blargedy** [comment]
only found one to be incorrect, let us know if we missed something. resolved in September 21, 2022 update

**Comment by statuseffect** [comment]
Thanks for everything you do!
