### ISSUE TITLE
Dynamis Monster Stats are incorrect

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#5245]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

After taking a look at dynamis monster stats on test server, I've confirmed that (at least some) dynamis monsters are not currently following our known stat ranks/formulas like other monsters are. I'm unsure what the scope of this is, but I have confirmed its true of at least Orcish WAR/THF and Quadav MNKs within Dynamis specifically.

Example:

Lv 82 Vanguard Footsoldier (Orc WAR)
In-Game stats: 
STR: 115
DEX: 90
VIT: 82
AGI: 76
INT: 64
MND: 60
CHR: 76

Based on our stat rank sheet as well as JP wikis, these are the stat ranks for WAR job and Orc family, as well as stat table at level 82:

![Untitled](https://user-images.githubusercontent.com/49970272/188245122-3052d166-72d6-475f-864e-0ee041373407.png)

![Untitled](https://user-images.githubusercontent.com/49970272/188245319-389191db-eae8-4eb2-9211-a2a7452914da.png)

![Untitled](https://user-images.githubusercontent.com/49970272/188245423-79b2c415-a23c-4ccf-89d0-0b935c098211.png)

With the above, we can check everything besides their STR and DEX, which are likely just using default DSP values since STR and DEX ranks are currently unknown for Orcs.
(Note: Letters refer to "Mob Family Rank + Main Job Rank + Sub Job Rank")

VIT: D D D = 31 + 31 + 15 = 77 (in-game is 82)
AGI: C D D = 36 + 31 + 15 = 82 (in-game is 76)
INT: F G G = 22 + 18 + 9 = 49 (in-game is 64)
MND: F D D = 22 + 31 + 15 = 68 (in-game is 60)
CHR: E C C = 27 + 36 + 18 = 81 (in-game is 76)

**Comment by 59blargedy** [comment]
resolved by another dev in may 22, 2023 patch
