### ISSUE TITLE
Fomor Beastmasters Linking with Lesser Colibri

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#5247]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***) 
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

Full HP in Wajaom and Bhaflau Thickets, provoked a Lesser colibri as a 75 WAR and the Fomor Beastmaster standing about 5 yalms in front of the colibri I was provoking linked along with its pet bats.

Tested in both Wajaom and Bhaflau yielded same results. Was outside of sound aggro range.

**Comment by FariskaEden** [comment]
Aht Urghan fomor have job ability aggro, were you outside of JA aggro range as well?

**Comment by statuseffect** [comment]
I was at max range i believe. It could have been JA aggro.

**Comment by 59blargedy** [comment]
went to just confirm this to be sure - there is no linking, just JA aggro

**Comment by falzum** [comment]
For what it's worth I thought only the Ephramadian Shades aggro'd job abilities. Back dated wiki seems to support this.

First mention of the wajaom fomors aggroing job abilities was added in 2012 https://ffxiclopedia.fandom.com/wiki/Fomor_Beastmaster?oldid=1389466

**Comment by E5una** [comment]
FWIW, era jp wiki page references them having "Job Sense" so it was a thing in era, here's a 2008 wiki page:

http://wiki.ffo.jp/wiki.cgi?Command=HDetail&articleid=86655&id=9739
![image](https://user-images.githubusercontent.com/13668758/192165850-b1d2c4ab-6a0c-44aa-a437-eb983c494583.png)
