### ISSUE TITLE
Beastmaster AF legs are not repeatable even with memory wipe.

### ISSUE THREAD

**Issue by fluffydeadangel** [EdenServer/community#5248]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Version 30181205_0

After clearing AF memories to redo Beastmaster AF, you cannot do the pants again. The starting NPC does not respond. We tried a few fixes with the GM's already, once the quest was added it acted like we already had the tamers whistle even though the key item was not present. Once the key item was added, the sarcophagus still did not respond.  In the end, Luminous was able to provide a temporary fix. I'm unsure of those details.

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
