### ISSUE TITLE
SW Apollyon 2nd floor: Tree moves

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5250]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

Currently on Eden, the "no leaves" tree on SW Apollyon 2nd floor seems to path towards a default point when you enter the floor. According to https://youtu.be/omHDRSdDphQ, it should be a non-moving mob like the rest of the trees.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
