### ISSUE TITLE
Taxim has incorrect drop rates

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5253]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Did 31 spawns on test server with TH4, got:
Blizzard 3 1 x
Blizzard4 1x
Blizzaga2 3-4x
Blizzaga3 0x
Freeze 3x
Cocytus pole = felt like~25% drop rate with TH4, (already closed window, sorry)

Also have never seen blizzaga3 drop from him on live either.

What db says:

![image](https://user-images.githubusercontent.com/69089249/189483879-c43a300c-2611-447f-8891-82e13eaa35c2.png)

Clopedia drop rates are atm:

Blzizard III 22,2%
Blizzaga II 24,4%
Blizzaga III: 28,9%
Blizzard IV  2,2% 
Freeze 11,1%
Cocytus pole 44,4%

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
