### ISSUE TITLE
Actinic Burst not reducing ACC

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5255]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

![image](https://user-images.githubusercontent.com/11255886/189513632-3eaa12b0-6aca-4d99-9125-fd0a37a7dceb.png)

402 ACC is what I have w/o Actinic Burst too

**Comment by Steam-arch** [comment]
Hmm, has to be more to this because it does reduce acc:

![image](https://user-images.githubusercontent.com/69089249/189544895-48b6f7c8-fdba-4520-8b8f-31de651cea85.png)

**Comment by Mozzy4Ever** [comment]
Could be a difference between live and test

**Comment by Steam-arch** [comment]
Maybe, I only checked this because long time ago I was spamming checkparam (on live) during actinic burst and it seemed to work back then. Anyhow test works, not sure about current live.
