### ISSUE TITLE
Assaults: characters stuck in black screen upon failing an instance

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5256]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Did this assault earlier today and had an issue with the server not properly moving players out upon failure of the assault.  One player homepointed while three others waited for the assault to end per failure conditions.  After the three minute timer ended the server left several people in a black screen while still in the instance.  Fixed by closing all of the clients for the player's in the zone and waiting for the instance to close.  After waiting some time players were able to log back in and it placed them at the proper exit.

**Comment by randomslumber** [comment]
Same issue with failed Mamool Ja Imperial Agent Rescue. Two people warped out and I used fireflies. Might have missed the failure assault points because of it

**Comment by DeuceFFXI** [comment]
Changed the title.

Once again encountered this bug inside of Leujoam Sanctum, so it appears to be an overall issue for assaults.  Same issue from before, characters did not properly exit upon failing the assault.  Requires closing each of the clients in order to force disconnect and waiting for the zone to time out.

**Comment by KnowOne134** [comment]
Can't use fireflies?

**Comment by DeuceFFXI** [comment]
If a character dies you can't do any of these things with it, hardly a solution.

**Comment by DeuceFFXI** [comment]
I might add that I believe an additional concern will be this same bug possibly affecting players doing Salvage in the future.  I imagine both Assaults and Salvage will use a similar backend.  And with Salvage being far more nuanced, many players will likely run up to the time limit and end up being forced out, especially inexperienced players.

**Comment by KnowOne134** [comment]
Resolved in February 20, 2023 update
