### ISSUE TITLE
Goblin Enchanter's in Castle Zvahl Keep have less spawns than they should

### ISSUE THREAD

**Issue by SleazyFFXI** [EdenServer/community#5258]
### Checklist

- [Yes ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [Yes ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [30181205_0 ] I have provided my client version in the details. (type /ver into your game window)
- [ [Castle Zvahl Keep](https://ffxiclopedia.fandom.com/wiki/Castle_Zvahl_Keep)] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

https://ffxiclopedia.fandom.com/wiki/Goblin_Enchanter?oldid=608980

There should be 9 Goblin Enchanter spawns in Castle Zvahl Keep but on Eden there is only 6.

**Comment by statuseffect** [comment]
Beastmen spawns as a whole on private servers aren't correct as most beastmen can share the same spawn. On private servers almost all entities are spawned (hence monastic caverns clogged tunnels)

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
