### ISSUE TITLE
Crab sushi has post nerf prices.

### ISSUE THREAD

**Issue by failffxi** [EdenServer/community#5262]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

 - - - - - - - - - - -

### Details

Crab sushi have the post-nerf vendor price of 91-96gil, compared to their 519-531gil (813~831 gil for +1) vendor price back in era. 
These prices were not nerfed until the same patch as remedy's were, so these prices should be fairly retail accurate.

![image_2022-09-20_190547541](https://user-images.githubusercontent.com/41841824/191331873-3a0c8026-b4fa-44a1-a4b0-3c9a4dfff406.png)

Ver: 30181205_0

**Comment by statuseffect** [comment]
Fairly certain our new cutoff is September 2008 which reflects the updated npc pricing. Remedies haven't been adjusted yet and should be soon.

**Comment by 59blargedy** [comment]
yep, crab sushi has the correct price based on the September 2008 data established. appreciate the report, but in this case the price is correct.
