### ISSUE TITLE
Timeless Hourglass/Cosmo-Cleanse incorrect pricings.

### ISSUE THREAD

**Issue by failffxi** [EdenServer/community#5264]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
- - - - -
Since September'08 is the new cut-off date, then 'Timeless Hourglasses' & 'Cosmo-Cleanse' have incorrect era pricing. 

![image_2022-09-21_133241121](https://user-images.githubusercontent.com/41841824/191504565-f9dcb390-9404-4c2c-acbf-b21192f6547d.png)

September '08 Update was the update where they lowered these costs alongside the increased drop rates of relic items from dreamlands/Northlands Dynamis zones as well as adding COR/BLU/PUP AF2 armours.
Ver: 30181205_0

**Comment by statuseffect** [comment]
This is a known issue and has not been implemented yet.
