### ISSUE TITLE
Puppetmaster Attachment Abilities Not Activating

### ISSUE THREAD

**Issue by bobusffxi** [EdenServer/community#5267]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

As of the most recent patch (version 30181205_0, september 21,) automaton abilities enabled by attachments aren't being used when under the appropriate conditions. 

I've personally tested Strobe (deployed with Fire Maneuver active, 45 seconds after activation,) Shock Absorber (Earth Maneuver, 3 minutes after activation,) and Flashbulb (Light Maneuver, 45 seconds.) Multiple times each, in and out of a party, after zoning with sync on and off. I've also taken off and put on the attachments again. I've linked a little video of trying to get shock absorber to work and attached some discord testimonials. Feel free to DM me on discord if you need anything else at Derrek#6688.

https://streamable.com/a32i8v

![Discord_nJf6ngolaM](https://user-images.githubusercontent.com/114133762/191672701-f7d98fa3-1575-477a-9169-0408e93bfcc4.png)

**Comment by 59blargedy** [comment]
resolved September 23, 2022
