### ISSUE TITLE
BLU "Bomb Toss" always hitting for 0

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5268]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

BLU75 casting Bomb Toss on a SGusta mob always lands for 0. Happens at various levels too. My personal experience was L40 on Goblins in East Altepa. No Burst Affinity used.

**Comment by 59blargedy** [comment]
resolved live 9/22/2022
