### ISSUE TITLE
"As thick as Thieves" Missing dialouge

### ISSUE THREAD

**Issue by Tavnazian** [EdenServer/community#5269]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Version 30181205_0
During the opening dialogue with Nanaa Mhigo, there is missing text in one line(see attached image). The missing part should say "Tenshodo Envelope" in the Key Item text color, as seen at https://youtu.be/xpnBmNlqMWQ?t=53.
![missing](https://user-images.githubusercontent.com/86973967/191860205-63b234e0-3e9f-426a-99c0-e916f6481d54.jpg)

**Comment by 59blargedy** [comment]
resolved September 23, 2022
