### ISSUE TITLE
Sandy Mission 9-2: Adds too much health

### ISSUE THREAD

**Issue by Aeshur** [EdenServer/community#527]
The fight is way over tuned.

**Comment by beauxq** [comment]
from https://ffxiclopedia.fandom.com/wiki/Talk:The_Heir_to_the_Light#Testimonials
"The orcs are very weak, war could take off 70%~ of ones Hp with a Raging Rush."

**Comment by beauxq** [comment]
All over that page it says easily duo and trio by level 75s.
