### ISSUE TITLE
Feral Howl says No Effect when a stun is already on the target but still applies its effect

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5270]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

This bug is specifically about the inconsistency of the message. If the mob is stunned prior to applying the terror effect you will get a message that says no effect, even though the terror works. I will create a separate bug report after I do some research to understand what correct behavior is with stun/terror. Currently on Eden Terrors can overlap Stuns, but I'm not sure on that part. This bug report is ONLY about the inconsistent message!

![image](https://user-images.githubusercontent.com/13668758/191968333-9e64ab4a-9ae5-47ed-8065-e0054be4e76e.png)

Steps to reproduce:

1. BST/DRK with feral howl
2. Set Macc to large value like 3000
3. Cast stun on the target.
4. Immediately use Feral Howl while the target is stunned.

The result will be that the target becomes terrorized (animation freezes) BEFORE the stun wears off message shows up, so they are definitely overlapping, but there is a message printed that says no effect, that doesn't match the bahvior.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 7, 2022 update
