### ISSUE TITLE
Terror effects should not overwrite stuns and vice versa

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5271]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On Eden right now you can apply Terrorize and Stun effect at the same time on a monster. Per Fariska's retail testing, this should not be the case:

![image](https://user-images.githubusercontent.com/13668758/192042067-4600f279-3598-4bf7-951d-ce7bd9a1019d.png)
![image](https://user-images.githubusercontent.com/13668758/192042094-e15e6c2a-5d09-4a6c-b17b-3631a1b9a0ff.png)
![image](https://user-images.githubusercontent.com/13668758/192042109-7b007aac-45f4-4b4c-9bd0-dfe8470fe851.png)

Currently on Eden BLU can apply both of these affects freely. 

Stun -> Terror (You can see they are both on at the same time based on the messages)
![image](https://user-images.githubusercontent.com/13668758/192044585-66e4706f-aa31-458f-8bcf-49b17e7196ad.png)

BST can do the same with Feral Howl, although when they do so they get a status effect saying it had no effect, even though it works. 
![image](https://user-images.githubusercontent.com/13668758/192043424-dd726c05-e863-4f71-96a7-7de655ffec50.png)

I created a separate report for their messaging issue here. Sorry if these being separate issues is confusing! Let me know if we'd prefer to consolidate. https://github.com/EdenServer/community/issues/5270

version 30181205_0

**Comment by KnowOne134** [comment]
Resolved in February 20, 2023 update
