### ISSUE TITLE
Automaton Assault Not Giving Enter Prompt

### ISSUE THREAD

**Issue by CurzonEden** [EdenServer/community#5272]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I am unable to enter Automaton Assault. Meet all the requirements listed on the 2008 wiki entry on. 
I have confirmed that I have the proper key item (Shaft gate operating dial). I do receive the entry prompt for Pulling the Strings. 

Both members of the party are Tarutaru, and the prompt also does not appear if solo without a party.  We both experienced the same issue.

Possible this just related to Tarutaru. 

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 7, 2022 update (sorry tarus)
