### ISSUE TITLE
Herald NPC for Ballista is crashing zone after match is over or match is cancelled

### ISSUE THREAD

**Issue by inaringo** [EdenServer/community#5273]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Interacting with Herald NPC for ballista is crashing the zone, either after a match is over or after a match is cancelled.

**Comment by ThoseWhoFight** [comment]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/37572397/192079961-dd75a48c-9861-4485-b623-4476e343d3c6.png">

Idk if this helps, but as far as the match being cancelled, it happens directly after this dialogue. Possible that it's tied to a Pup being an entry? But thinking it's just post matches in general.

**Comment by ThoseWhoFight** [comment]
Seems to be following a pattern of when a Puppetmaster is one of the entries, that this bug happens. Been every match with a PUP entry, but the one time there wasn't a PUP, we had no issues.

**Comment by 59blargedy** [comment]
resolved by another dev in October 7, 2022 update
