### ISSUE TITLE
Receiving crafting skillups when modified skill = skill cap

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5274]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I'm crafting tav salad cap 92 and my skill is 89. With advanced synth support (+3), I just received a 0.2 and 0.3 skillup.

Game version 30181205_0.

**Comment by Falaras** [comment]
That's how crafting works.

**Comment by 59blargedy** [comment]
sorry just saw this - you will still get skillups when your skill is below the cap, even if you have support that reaches the cap. that is ok/expected behavior. thank you for reporting, always good to check.
