### ISSUE TITLE
Centurions Axe model is wrong

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#5275]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

Centurions Axe (level 30 Gaxe) model is using a Toporok model on Eden currently.

Picture of what it looks like now: https://i.imgur.com/pT0teez.jpg

Picture of what it should look like from FFXIAH: https://cdn-b2.ffxipro.com/file/ffxiah/images/ss/full/Lariel06Np0V67W5Nt.jpg

**Comment by 59blargedy** [comment]
resolved in October 7, 2022 update
