### ISSUE TITLE
COP 7-4 NMs tonberry NMs fixed in previous update keep respawning after killing.  

### ISSUE THREAD

**Issue by Fng098** [EdenServer/community#5277]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

COP 7-4 NMs fixed in previous update to despawn after killing first NM do despawn.    But when you click the ??? to complete the mission, they respawn and the mission is uncompleteable.  

Was not able to kill all three NMs with our group.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 7, 2022 update

**Comment by Fng098** [comment]
Seems to still be respawning.  Hiroshi attempted today.

**Comment by 59blargedy** [comment]
were they in an alliance or a party?

**Comment by Fng098** [comment]
Sorry I just assisted with the kill all three NMs so I can't 100% be sure.  They did their first attempts with 4? toons. I highly doubt they were in an alliance but I wasn't there to be 100% sure.

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
