### ISSUE TITLE
Casting Tractor in battlefields removes Battlefield status

### ISSUE THREAD

**Issue by Appotemmis** [EdenServer/community#5278]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently as of the latest patch, if a player accepts a Tractor from another player in Limbus, they will lose battlefield status and are booted out of the instance.

We had a group in Ultima where we wanted to Tractor some players out of the pit and upon accepting Tractor, they would be ported outside of the instance while everyone else remained

**Comment by Mozzy4Ever** [comment]
Note: This issue isn't specific to Limbus. Happens in other Battlefield fights too.

**Comment by 59blargedy** [comment]
this issue was resolved with the last update
