### ISSUE TITLE
Bonecraft Guild Vendor

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#528]
Bonecraft guild doesn't sell Bone Chips. I have no evidence that they should restock automatically, but this is such a basic ingredient like copper for GS or Iron for BS, it should be restocked.

**Comment by Wiggo32** [comment]
I have evidence they are not restocked automatically.

**Comment by gweivyth** [comment]
Definitely not supposed to be restocked, but the good news is that they're super common thanks to Chocobo Digging.

**Comment by tectal831** [comment]
They are not restocked automatically. Closing ticket. Will reopen if you can provide evidence to support your claim.
