### ISSUE TITLE
PUP Bone Crusher should be blunt damage, it seems to be blunt/slashing hybrid

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5280]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Tested in limbus after Lloyd brought it up in discord:

![image](https://user-images.githubusercontent.com/13668758/192163213-36e17a64-563c-49aa-98a3-2cabada2b946.png)

Source showing the blunt damage:
https://ffxiclopedia.fandom.com/wiki/Bone_Crusher
https://www.bg-wiki.com/ffxi/Bone_Crusher
http://wiki.ffo.jp/html/14829.html

![image](https://user-images.githubusercontent.com/13668758/192163307-ee901cde-9c00-49b0-bea7-6dd89b122f6b.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
