### ISSUE TITLE
OOE Effect For Healers Role on COR

### ISSUE THREAD

**Issue by Topher269** [EdenServer/community#5282]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

In Al Zahbi the NPC Chayaya lists a WHM Die for sale with the incorrect description for how the Phantom Roll ' Healer's Roll ' is supposed to work.

It is supposed to read " Increases the amount of MP recovered while healing the party members within area of effect "

It list's " Increases potency of "Cure" effect for party members within area of effect. "

![Corsair WHM Die](https://user-images.githubusercontent.com/114368171/192170756-ed240d67-5011-487a-8b19-915940ad114a.png)
![Corsair WHM Roll](https://user-images.githubusercontent.com/114368171/192171101-dc9b614a-1a1a-43a3-aab3-a994e8109b7f.png)
![Wiki Page COR](https://user-images.githubusercontent.com/114368171/192171236-db3c1278-a0c3-48bd-9783-6e04152d8825.png)
My Version is 30181205_0
Era Link to the ability from the wiki : https://ffxiclopedia.fandom.com/wiki/Healer%27s_Roll?oldid=775525

**Comment by bliven-was-taken** [comment]
Did you actually try using the roll and see what it does?

**Comment by bliven-was-taken** [comment]
Also, https://github.com/EdenServer/community/issues/2580

**Comment by Steam-arch** [comment]
Yeah, need the non updated game files if someone has on an old laptop/hard drive.

**Comment by 59blargedy** [comment]
appreciate the report, closing as this is already reported and to confirm, is a dat issue vs effect.
