### ISSUE TITLE
Skillchains doing extra damage

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5283]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

![image](https://user-images.githubusercontent.com/11255886/192173957-8fc1fc4c-8471-4a5c-ae22-623841b5be0d.png)

Death Blossom -> Mercy Stroke should just do Darkness, so SC damage should cap at 100%. Instead it's acting as if I did a 3 weaponskills to make the darkness, so damage is capping at 150% of WS damage. Happens with other skillchains no matter if relic or light/dark SC.

**Comment by ConteAlmaviva** [comment]
Was the Phuabo open mouth at the time?

**Comment by Mozzy4Ever** [comment]
You're thinking Hpemde. Phuabo are sharks

**Comment by 59blargedy** [comment]
resolved in October 7, 2022 update

**Comment by Snugglepunk** [comment]
This seems to still be an issue. 1 step Level 3 Darkness is doing 150%, should cap at 100% and a level 4 darkness is doing 225%

![image](https://user-images.githubusercontent.com/56851217/194754935-3b4b418a-cab8-4108-9d37-4733291b76fc.png)

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update

**Comment by dowzer** [comment]
Level 2 skillchains are doing more damage than they should.

![skillchaindmg](https://github.com/EdenServer/community/assets/54732693/a06061bf-3944-49da-bd13-19dc7e178966)

https://youtu.be/AKzUUVMaGPg?t=31

Both her 3rd and 4th skillchains created level 2 Induration/Fragmentation for less damage than my 2nd skillchain created.

My first skillchain was a 77% increase and it should be 60%
My second skillchain was a 112% increase and it should be 75%

Her third skillchain was a 70% increase
Her fourth skillchain was a 104% increase

Resistance could be playing a factor in the video as well, unresisted skillchain damage should have been 100%(only did 70%) and 125%(only did 104%) respectively.

Feel free to critique any mistakes or misinformation
