### ISSUE TITLE
Been kicked really quickly after a death in "Unvited guest" Quest

### ISSUE THREAD

**Issue by Taehg** [EdenServer/community#5285]
### Checklist
 I'd like to report a really quick kick after a death during this fight (2Min) : ( no time for RR or whatever)

Find the SS below for more details:
![image](https://user-images.githubusercontent.com/108333470/192323036-89743995-6d24-44d8-ad08-20e673dac0f9.png)

Ver 301812105_0
- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
resolved in October 7, 2022 update
