### ISSUE TITLE
BLU Burst Affinity is being consumed by SOME physical spells

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5287]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Resurfacing of a previous bug: https://github.com/EdenServer/community/issues/1709

Burst Affinity should only be consumed on "magic" style BLU magic, not physical. I haven't tested every spell but I tested the ones below and the only ones that are consuming it are Terror Touch and Tail Slap. If you can find anything in common with those two spells that is different than the rest, it may help to reveal the problem.

Tested These and they work normally (don't consume the buff):
Disseverment
Vertical Cleave
Bludgeon
Screwdriver
Frypan
Bodyslam
Spinal Cleave
Pinecone Bomb
Queasyshroom
Death Scissors
Hell Dive
Featherstorm
Headbutt

Tested these and they consume the buff, which is wrong:
Tail Slap
Terror Touch

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 7, 2022 update
