### ISSUE TITLE
Unable to purchase additional Mannequins

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#5288]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Upon completing the quest [It's Raining Mannequins](https://ffxiclopedia.fandom.com/wiki/It%27s_Raining_Mannequins?oldid=593747), the player should be able to purchase additional mannequins from Fyi for 100k each.

**Comment by Frozzen907** [comment]
Also; When completing "It's Raining Mannequins" you should be able to trade the one you recieve + 10k back to the NPC to change it's race/sex. Currently you cannot.

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
