### ISSUE TITLE
Morion Worm should always drop 3 ore

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#5289]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver 301281205_0

![image](https://user-images.githubusercontent.com/61694447/192603695-a6994522-122c-4c98-bf96-ee04bd79242a.png)

![image](https://user-images.githubusercontent.com/61694447/192599715-d8b7e3e3-cf1e-4f9f-b158-c3db51d55005.png)
There was no dot on it this time when it died?

Morion worm should always drop exactly 3 ore of varying types, and also the potential tathlum. 

https://ffxiclopedia.fandom.com/wiki/Morion_Worm  This page says so. 
http://ffxidb.com/zones/173/morion-worm 

![image](https://user-images.githubusercontent.com/61694447/192599982-b2982747-9061-4fcb-8c6c-4f20e1c218e6.png)

165 + 54 + 23 + 10 = 252 (Not counting tathlum.) 252 / 3 = 84 which is the provided sample size.

https://www.youtube.com/watch?v=qXEnU71Wyco shows 3 copper ore. 

https://www.youtube.com/watch?v=T8LmdA9zl8U 1 iron 2 copper.

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
