### ISSUE TITLE
Casting Knight's Minne 3 with a Harp +1 equipped is only giving 5 defense.

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#5290]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

2 Different people reported on discord that casting knight's minne 3 without an instrument seems to give 40 defense, but casting knight's minne 3 with a harp +1 (+2 minne) is only giving 5 defense. Did not have a ghorn or a NQ harp test.

https://ffxiclopedia.fandom.com/wiki/Knight%27s_Minne_III?oldid=499288

Opinion: I believe 5 defense is supposed to be the bonus the harp gives, so maybe it has something to do with that.

**Comment by Steam-arch** [comment]
Hmmmmm,  Im curious on whats going on with these now, test server & values are defences:

![image](https://user-images.githubusercontent.com/69089249/192875650-391bbf67-7692-455e-954a-a43c70883b8d.png)

**Comment by bliven-was-taken** [comment]
I think it's only giving the bonus defense instead of the base defense + the bonus defense
