### ISSUE TITLE
The Grand Palace of Hu'Xzoi Eo'euvhi level range is incorrect (should be 74-76)

### ISSUE THREAD

**Issue by Midgard-was-taken** [EdenServer/community#5291]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I have no idea what the following means, but Mozzy said this on Discord:

"Capture of Grand Palace mob levels in 2019 shows 74-76
(When it comes to retail captures, there's no guesswork on mob levels because it can be found via widescan with capture suite addons)"

**Comment by 59blargedy** [comment]
thanks for reporting! looks like i have a more recent capture that looks like it has level 74-77 eo'euvhis in it so we'll go ahead and keep the level ranges as is.
