### ISSUE TITLE
Help me solve the problem, after I have minimized the game, I cannot return to it and it crashes. Has anyone had a similar experience?

### ISSUE THREAD

**Issue by Cericaso** [EdenServer/community#5292]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by Mozzy4Ever** [comment]
This is a #tech-support issue via Discord, not a bug report.

**Comment by 59blargedy** [comment]
if you launch in fullscreen, this will always happen with ffxi on any client. use windowed mode to prevent. work with the folks in #tech-support on discord for more info
