### ISSUE TITLE
Elemental Breath from Dragoon's Wyvern is always being resisted

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5293]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

As of the last patch 9/21 (or potentially the 9/23 maintenance that followed) the Elemental Breath from Dragoon's Wyvern is unable to do above minimum damage. Here is a parse from today as a 60-61 DRG vs. Lesser Colibri, note that all resists were full resisted for 20 dmg.

![image](https://user-images.githubusercontent.com/13668758/193306994-b9082a46-424b-46bd-81bb-9693e120835a.png)

Here is a parse from pre-patch (9/17) of a 54-57 DRG vs. Lesser Colibri, not that while many are full resisted, not all are:
![image](https://user-images.githubusercontent.com/13668758/193307274-12a1a947-adfe-4d95-87df-96719df6f4f3.png)

Here is my testing on the test server. The first 105 tests were vs Lesser Colibri as a 56 DRG, the remainder of the tests were vs an Easy Prey Ogrefly in Zitah as 56 DRG. Note that the highest damage was still 20 (You can ignore the lower damage, those are just from my wyvern getting hit and losing HP, thus lowering breath damage, which I tried to quickly correct between tests each time it happened):

![image](https://user-images.githubusercontent.com/13668758/193307747-2788aa30-d5bc-4ca6-9d5e-83f4145e42a1.png)

A friend also tested on live as 61 DRG vs gobs in the dunes while farming a scroll and also had the same results.

Note: Nearly all numbers are produced with a 100% HP Wyvern. Very few were not due to dropped effects like TERROR/INVINCIBLE that I was trying to keep on to maintain static tests results.

version 30181205_0

**Comment by E5una** [comment]
Update to this that might help with debugging: The cap seems to be 20 regardless of what level. Capped at 20 dmg breaths at level 75, also capped at 20 dmg breaths at level 20. I tested at level 1 to make sure it wasn't a static amount and its not, 6 damage breaths at level 1.

**Comment by 59blargedy** [comment]
resolved in October 7, 2022 update
