### ISSUE TITLE
Level sync.... FOREVER!

### ISSUE THREAD

**Issue by Veru90** [EdenServer/community#5295]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

So, after ballista - clicked on the Herald which dc'd the entire zone, and very quickly as soon as I logged back in -ran to the OP and warped back to town (not level synced yet).  OP'd to ronfaure to run to KA (still no sync yet).  Zone from KRT into Jugner, perma level 50 sync applied.  Exiting Jugner forest removes the level sync.  Entering Jugner applies the level sync, relogging & GM help no work!

**Comment by ThoseWhoFight** [comment]
Think this was fixed with the previous patch fixing Herald zone crash bug
