### ISSUE TITLE
Limbus bug cannot do actions to mobs or pt

### ISSUE THREAD

**Issue by Azmatic1** [EdenServer/community#5296]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I was unable to do any actions to mobs or party members in the limbus group I entered with. In addition, they were unable to perform any actions on me. I restarted app after submitting ticket and still had the same issue. I did not drop from server and was still able to receive invites but bug still occurred. GM said they were unfamiliar with the problem and couldn't assist.
![Inny_2022 10 01_135916](https://user-images.githubusercontent.com/99223333/193422717-7033760e-dc0e-47d7-84e6-92315b4c26a2.png)
![Inny_2022 10 01_135715](https://user-images.githubusercontent.com/99223333/193422783-31391b2d-7058-4af7-bd79-0309d4365ce5.png)

![Inny_2022 10 01_141512](https://user-images.githubusercontent.com/99223333/193422750-eee7fa35-e8c4-43d0-8fd5-d73be17f758b.png)

Reformed pt and casted diamondhide (AOE stoneskin) with pt in range and I only received effect
![Inny_2022 10 01_143503](https://user-images.githubusercontent.com/99223333/193423514-44677c7e-0b2d-489a-a83b-c0ef3e95703e.png)

Even unable to aggro
![Inny_2022 10 01_144432](https://user-images.githubusercontent.com/99223333/193423800-d78d4010-5094-473d-9f3f-a46e18b6a233.png)

**Comment by 59blargedy** [comment]
did you enter after the rest had engaged? enter as they were engaging? at what point in the limbus did this occur? 
did you try to enter and choose the location while someone else was choosing it? have the menu open while they were entering? did you dc at any point and come back? 
really need as much information to help resolve the issue.

**Comment by Azmatic1** [comment]
> did you enter after the rest had engaged? enter as they were engaging? at what point in the limbus did this occur? did you try to enter and choose the location while someone else was choosing it? have the menu open while they were entering? did you dc at any point and come back? really need as much information to help resolve the issue.

I may have entered at the same time as leader entered I'm unsure on this, I was unable to perform any action from the beginning, I chose same zone as leader (NE was only available), I did have menu open while entering and I didn't dc at any point.

**Comment by Snugglepunk** [comment]
Have also just got this bug in the same zone.  Entered on 1st character Punk, waited for chatlog to say you hear a hum before entering on 2nd character Snugglebug.  Both entered into same instance, was able to cast haste once and then lost battlefield status on Snugglebug and was unable to act on any char/mob in the zone after.  Tried logging out and back in to see if it fixed it but no luck.
![image](https://user-images.githubusercontent.com/56851217/193793436-245540fd-b56d-45cd-8ea6-f7524b4b163b.png)

**Comment by Frozzen907** [comment]
My group also had this happen last week with one of our members... I believe last Monday.. Was a temenos zone tho.

**Comment by 59blargedy** [comment]
resolved in October 7, 2022 update
