### ISSUE TITLE
Ouyu Absolute Terror absorbed by shadows

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5297]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Steps:

Gameversion 30181205_0
Steps:
1. Cast Utsusemi
2. Face Absolute Terror from Ouryu

Wiki says normal Absolute Terror is single-target, but Ouryu's is AoE. Is this intended?

**Comment by 59blargedy** [comment]
yep, ouryu's and bahamut's versions are aoe and absorbable by shadows. thanks for checking.
