### ISSUE TITLE
Leviathan's Couse has an incorrect additional effect in addition to latent

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5298]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

https://ffxiclopedia.fandom.com/wiki/Leviathan%27s_Couse

Should only proc when someone including the wielder has Leviathan out. It's currently procing seemingly randomly in a merit party I just completed. No smn in sight. 

![unknown](https://user-images.githubusercontent.com/55296729/193434937-d9054481-8d9e-44bc-9f37-e5d7404231c1.png)

/ver 30181205_0

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
