### ISSUE TITLE
Hate not resetting on death/opwarp

### ISSUE THREAD

**Issue by Aliptical** [EdenServer/community#530]
We were in valkrum dunes. had alittle aggro issue and people died/zoned into selbina. upon hp and op warp back to dunes and others zoning back into dunes from selbina, hate did not reset and several party members died yet again. and even then it did not reset. we only got away from it after i unsynced, caught it alone (because it was linking like crazy and killing us over and over) and finally solo killed it.

**Comment by velius877** [comment]
This morning I was in a party fighting Damselflies and a few of us died. Me being one. Prior to the death I was last one to provoke the fly that got me. I homepointed in Bastok Markets, changed to Bastok Mines, outposted back to Valkurm Dunes. Upon my return I had emnity above all the others and it bee lined at me. I was about 20 to 30 yalms from it when I zoned in. Needless to say it led to many extra links running to Selbina and some goblin aggro unfortunately.
