### ISSUE TITLE
Republican Gold Medal doesnt work.

### ISSUE THREAD

**Issue by DelphiXI** [EdenServer/community#5300]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Client ver: 30181205_0

Bastok Conquest Point item Rank 8 doesn't work.
This item supposed to give +50 MP outside own nation control.
Screenshot bellow on different area.
In the City of Bastok:
![image](https://user-images.githubusercontent.com/114884851/193478676-1db6e1d2-5f47-47ba-a01a-af79254cbfc7.png)

At Li'Telor which is under conquest of Sandy:
![image](https://user-images.githubusercontent.com/114884851/193478783-1d70146c-6de1-4320-8bf5-df203bf70a85.png)

At Sarutabaruta which is under conquest of Windy:
![image](https://user-images.githubusercontent.com/114884851/193478861-fa23f5be-2dc4-4c81-9fba-64a6a086838a.png)

**Comment by E5una** [comment]
Hmm worked for me last patch, haven’t checked this patch, I’ll do some testing and try to update this with some extra detail. I know it definitely worked in sea too

**Comment by E5una** [comment]
I think this is your problem.

![image](https://user-images.githubusercontent.com/13668758/193479584-f0cae3f3-416b-470d-8823-0e8f9233fd6a.png)

![image](https://user-images.githubusercontent.com/13668758/193479616-c740661c-d2b2-4a1b-9c89-d910e2be9016.png)


![image](https://user-images.githubusercontent.com/13668758/193479612-0fbdf451-1512-4fed-8b53-58028f22c8e5.png)

**Comment by DelphiXI** [comment]
Yes, its works after put signet on.
Going to close this, thank you.
