### ISSUE TITLE
Charmed Ziryu follows BST out of BC when running away from Ouryu Cometh

### ISSUE THREAD

**Issue by AzrielltheWise** [EdenServer/community#5304]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

![image](https://user-images.githubusercontent.com/90195635/194712767-e3ed20bb-f84d-427b-b6f9-51d2a613f3d7.png)

Fighting Ouryu in Ouryu Cometh, our BST charmed the Ziryu (worm mob) to control it.  We wiped on the fight so some members decided to exit the BC (run away).  When our BST exited the fight, the charmed Ziryu moved with him through the portal.  It could not be made to engage with mobs outside of the BC.  Releasing it (un-charming) caused it to instantly aggro the other players who were outside of the BC.  The BST re-charmed it and held it so AFK member didn't die.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
