### ISSUE TITLE
Ifrit Prime Double Punch leads to double TP move

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5306]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

It looks like Double Punch isn't consuming Ifrit Prime's TP, leading to back to back TP moves whenever he starts with Double Punch. This doesn't happen when he leads with something else.

**Double TP:**

![image](https://user-images.githubusercontent.com/13668758/194762266-92e241e1-538d-4f92-ba23-79093f54bd32.png)
![image](https://user-images.githubusercontent.com/13668758/194762268-f72083e7-b4fc-4d7e-98ca-841396a6c819.png)
![image](https://user-images.githubusercontent.com/13668758/194762273-7b5aa598-b4e5-4506-abc6-231b01197a82.png)

**Single TP:**

![image](https://user-images.githubusercontent.com/13668758/194762315-2f02e798-a56a-4158-9b4e-a888ed59a9f5.png)
![image](https://user-images.githubusercontent.com/13668758/194762363-0dffc7b7-3c7f-4550-aefb-29314fd9da45.png)
![image](https://user-images.githubusercontent.com/13668758/194762399-c75b7277-ae84-4e46-a08d-3f0ef37d823f.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
