### ISSUE TITLE
Rivulet Sahagin are 5m respawn, should be 14m

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5307]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Around M-11 of Sea Serpent's Grotto, where Fyuu the Seabellow spawns, the Rivulet Sahagin are 5m respawn but should be 14m respawn. 

![image](https://user-images.githubusercontent.com/13668758/194863439-abb6f668-499c-4caa-b4df-31cd3bf3e6bf.png)
![image](https://user-images.githubusercontent.com/13668758/194863495-8f4945dd-d61c-4bb1-9ca1-53c771d125bd.png)

Earliest wiki page with a respawn date (it shows 14m)
https://ffxiclopedia.fandom.com/wiki/Rivulet_Sahagin?oldid=710659

Modern wiki page (also shows 14m)
https://ffxiclopedia.fandom.com/wiki/Rivulet_Sahagin?oldid=1457878

version 30181205_0

**Comment by KnowOne134** [comment]
seems to have been fixed already
