### ISSUE TITLE
Kirin & Genbu seem to have artificial MDB

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5310]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Netherblast damage differs from retail on atleast Genbu and Kirin. Suzaku, Byakko and seiryu also have some old MDB, but not sure how accurate those are..

On kirin:

no merits no dream shroud
![image](https://user-images.githubusercontent.com/69089249/194935963-7abe97b3-05b0-48df-8b78-9e314053bec7.png)

5/5 Magic attack merits
![image](https://user-images.githubusercontent.com/69089249/194935302-1fef0479-84c8-4d8c-b856-1ca7c16bef5f.png)
![image](https://user-images.githubusercontent.com/69089249/194935317-2960644c-d20a-4f22-ad62-13bba74627d0.png)

5/5 magic attack merits + Dream shroud
![image](https://user-images.githubusercontent.com/69089249/194935374-0413d40e-c68e-495f-a7f0-a86887ba749a.png)
(max archievable netherblast dmg I think?)

no merits no dream shroud
![image](https://user-images.githubusercontent.com/69089249/194939914-29d3867f-c1bd-437e-8062-496ab8c6ef3e.png)

Some era netherblasts:

No Dream shround on! unknown merits, earth day
![image](https://user-images.githubusercontent.com/69089249/194936337-c1bc825b-c1a5-43de-9771-258f1ff9169a.png)

No idea what buffs/merits here,  earth day
![image](https://user-images.githubusercontent.com/69089249/194936479-27b64ac0-cb3d-4917-b430-3a3ecd42b6a7.png)

-----||----
![image](https://user-images.githubusercontent.com/69089249/194937386-16c04418-deb6-48fa-83c6-fa63e97efc23.png)

-----||----
![image](https://user-images.githubusercontent.com/69089249/194937425-acf2d75a-4557-471a-8f5e-7c302ffad54d.png)

-----||----
![image](https://user-images.githubusercontent.com/69089249/194938760-a49a50c1-7611-44bc-b891-f8041ef3f5f6.png)

![image](https://user-images.githubusercontent.com/69089249/194939299-5a5d45a7-8f7d-4a26-8ece-61c09c29b4fd.png)
source: https://www.bluegartr.com/threads/35650-Diabolos-This-Way/page8

Video sources:
https://www.youtube.com/watch?v=41APcolOLMI

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
