### ISSUE TITLE
ToAU Mission 39 (Allied Rumblings) cutscene causes players to be stuck on a black screen.

### ISSUE THREAD

**Issue by AzrielltheWise** [EdenServer/community#5311]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

For ToAU Mission 39 (Allied Rumblings) you get a cutscene when you approach the palace in Ru'lude Gardens.  This cutscene starts and proceeds as expected, but at some point it fades to black and never comes back.  Taking a screenshot (Print Screen) did not fix the freeze.  Changing the fps divisor did not matter.  All members were using Ashita, and between the four people who had the problem one runs only stock Ashita plugins/addons.    

Closing the game and logging back in 5~10 minutes later causes the game to put you back into the black screen (NOT "downloading data").

I was able to teleport myself out of cutscene with a second character, but this did not count as completing the mission.  When I returned to Ru'lude, the cutscene started at the beginning and got stuck at the same place again.  A few other members also got stuck, and did !unstuck to get out but had the same results (mission not complete).  

The below screenshot shows how far the cutscene got before it made us all stuck.

![image](https://user-images.githubusercontent.com/90195635/194970347-e4278733-8f50-405e-81ce-d8cf9e516fb1.png)

It also put the stuck people in permanant night time mode, across multiple zones. 
![image](https://user-images.githubusercontent.com/90195635/194971502-32d7c6e8-c9ff-48d8-ab1c-6e4f7e8e9721.png)

**Comment by Avarghaladion** [comment]
Some of us in my LS are encountering the same issue. Have tried with and without xipivot, with and without enternity, with different Ashita configs, and nothing seems to work. Currently awaiting !unstuck.

**Comment by Avarghaladion** [comment]
Update: It appears that our entire group encountered this bug and are unable to progress.

**Comment by SigHammer** [comment]
Same issue here.  The cutscene fades out in the middle like it's in transition to a different setting and then just stays on the black screen.  The HP/MP bar is still visible and chat window still works, but there's no menu access.  !unstuck both times and returned to the Mog House in Ru'Lude Gardens, without the mission log advancing, and into permanent nighttime as previously mentioned.  Running vanilla un-modded Ashita.

**Comment by KnowOne134** [comment]
Corrected on 11/21 patch
