### ISSUE TITLE
Wyvern Monster Family's Dread Shriek Should be 10' not 15'

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5312]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

As shown below, the range of Dread Shriek is currently 15'

![image](https://user-images.githubusercontent.com/13668758/195179943-1b4a163c-455a-4e5b-ad1d-4e213ecb156c.png)

Per BGwiki and ffxiclopedia it should be 10'

https://ffxiclopedia.fandom.com/wiki/Dread_Shriek
![image](https://user-images.githubusercontent.com/13668758/195180075-c3b86cef-ea43-4c28-8886-f46f31be0351.png)

https://www.bg-wiki.com/ffxi/Category:Wyvern
![image](https://user-images.githubusercontent.com/13668758/195180111-e5c3b5ce-e913-4d11-ad61-106c9423bcf1.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
