### ISSUE TITLE
Lumber Jack spellcasting not instant.

### ISSUE THREAD

**Issue by Tofutoshi** [EdenServer/community#5313]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Lumber Jack should not have a cast time.

https://www.youtube.com/watch?v=i8JEVUkpKpU

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
