### ISSUE TITLE
Evil Eye in Xarcabard seem to have the wrong Ahriman Tear drop rate

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5316]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

![image](https://user-images.githubusercontent.com/13668758/195344588-5adeadee-6be8-4cab-8259-62c820f01d06.png)

My computer crashed after my first parse, but the last time I looked at it I was 11/22 with TH1. Here is my second parse to add onto that (note that on 3 of these kills my Automaton WS's and 1 shot it before I tagged with any TH, so 3 of them were no drop and no TH, the rest had TH1)

![image](https://user-images.githubusercontent.com/13668758/195344869-19b11180-8a6e-4bdb-a405-91dbdee50b02.png)
![image](https://user-images.githubusercontent.com/13668758/195344899-4760b682-d8e2-4bb2-9567-4880053b961c.png)

Seems like they are two categories too high and are set to Common when they should be Rare.

![image](https://user-images.githubusercontent.com/13668758/195345224-8c3529d3-b4e0-444d-89f4-c0e73d5b1c2e.png)

FFXIClopedia suggests maybe even Uncommon, with a sample size of 1478, but hard to say without a TH breakdown.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update or last update i cannot remember
