### ISSUE TITLE
Mog Safe upgrade 2 - 'The Moogle's Picnic' glitched

### ISSUE THREAD

**Issue by maxdecphoenix** [EdenServer/community#5318]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

placed the mahagony bed in layout several days before conquest tally. 
purchased several White Jars to procure 'moghancement experience' from bed.
awaited tally.  Shortly after tally talked to moogle and received paralyze potion. 
talked to moogle again, recieved quest moogle's picnic CS. 
traded moogle requisite items: shrimp lure, selbina butter
moogle accepted items, gone from inventory.
CS of moogle saying he was leaving.
Awaited til the following 'JP midnight' talked to moogle expecting completion.  
Nothing

Have tried zoning, logging, re-trading items. moogle will not accept. quest still shows as active.

appears that two furniture quests activated, but the jars took precedence over the bed?  still confusing.

**Comment by falzum** [comment]
The Mog safe upgrade is awarded after a couple of days. It's not one jp midnight. If this still isn't resolved by the next conquest tally call a gm.

**Comment by maxdecphoenix** [comment]
> The Mog safe upgrade is awarded after a couple of days. It's not one jp midnight. If this still isn't resolved by the next conquest tally call a gm.

i did the first safe upgrade on an alt, it triggered on tally, i gave the moogles the goods, the completion occured the following JP midnight.

So, that's not accurate.  Atleast for all safe upgrades, which would be odd.  thanks for reply though

**Comment by maxdecphoenix** [comment]
upon todays tally, talking to moogle resulted in completion of quest.  seems it was just an issue of multiple quests initiating (safe and white jar), but only able to resolve one per tally.

**Comment by KnowOne134** [comment]
All furniture quests/hidden quests are 1x per conquest coded and I would agree with that by reading what people say in the talk pages for furniture items/quest

**Comment by KnowOne134** [comment]
https://ffxiclopedia.fandom.com/wiki/Talk:Furniture_Quest
