### ISSUE TITLE
Trader's Chapeau has no desynth recipe

### ISSUE THREAD

**Issue by ThoseWhoFight** [EdenServer/community#5319]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Trader's Chapeau currently has no desynth recipe, [current wiki says it should](https://ffxiclopedia.fandom.com/wiki/Trader's_Chapeau), [era wiki has a small amount of results](https://ffxiclopedia.fandom.com/wiki/Trader%27s_Chapeau?oldid=670709). Currently other Trader's set items do desynth, leading me to believe this piece also should.

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
