### ISSUE TITLE
Cutscene for quest "To Cure a Cough" is freezing

### ISSUE THREAD

**Issue by MysticLogos** [EdenServer/community#532]
When talking to Nenne to unlock "To Cure a Cough" - a rank 3 reputation San d'Oria quest - the cutscene freezes when the son says "Mother, I'm home!" when the player and Nenne look at the open door.  Tried at both 60 fps and 30 fps, tried using print screen key, nothing worked.  Had to force close the client all 3 times.

**Comment by gweivyth** [comment]
That seems like it might be an issue with your install, those cutscenes aren't handled server-side.

**Comment by UhtredFFXI** [comment]
I Just ran into this issue as well. I tried on both 60 and 30 FPS. I ONLY have Eden installed on my PC, So the CS should work fine. There is a bug with this CS somewhere...

**Comment by Blex64** [comment]
Encountered the same issue at both 30 and 60 fps.  ver30181003_1

**Comment by bkesecker** [comment]
Spoke with Lotus from DSP Discord and it could be that SE has updated the client in such a way that it shifted the IDs related to this quest.  It has worked for a long time and few changes were made in DSP LUA for Nenne.  I'm still trying to determine if this quest has any bearing on reading page 4 of the Diary.

**Comment by bkesecker** [comment]
Zynjec 1/8/2018 at 8:49 PM
"the NPCs are all there...
the Raminel script is triggering for both the Raminel (17719325, cutscene) and Raminel (17719326, roaming npc)
so raminel (cutscene) is trying to path through the entire zone getting to the cutscene(edited)"

**Comment by bkesecker** [comment]
This appears to be fixed in DSP master via https://github.com/DarkstarProject/darkstar/pull/5571

**Comment by bkesecker** [comment]
SQL to apply:
SELECT * FROM dspdb.npc_list WHERE name LIKE '%Raminel%';
UPDATE dspdb.npc_list SET name = 'Raminel_CS' WHERE name = 'Raminel' AND pos_rot = 188

**Comment by shadowrunner6699** [comment]
I am also getting stuck in this CS waiting on NPC to show up.
 Lotus 1/8/2018 at 9:07 PM
"short legs, he'll get there eventually"

I have been waiting over 10mins. 

Please have another look at this
