### ISSUE TITLE
ENM "When Hell Freezes Over" does not kick you out (neither timer)

### ISSUE THREAD

**Issue by AzrielltheWise** [EdenServer/community#5320]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Full wipe on the ENM "When Hell Freezes Over."  After 3 minutes it should've ejected us from the battlefield, but it never did.  After 15 minutes we should have timed out regardless of alive/dead, and it never ejected us.  

The entry text specifies 15 minute time limit on the battlefield.  Eden Wiki and Retail Wiki both confirm this.

After 30 minutes we still hadn't been ejected.  In the attach screenshot I have been dead for over 30 minutes.

![image](https://user-images.githubusercontent.com/90195635/195867503-9e96e865-b584-4b23-9213-fbe53841c56e.png)

**Comment by KnowOne134** [comment]
tested both conditions and both got kicked out at appropriate times
