### ISSUE TITLE
Fenrir Prime's Moonlit Charge applies Blind even when absorbed by shadows

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5321]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Can't find anything online that says Fenrir Prime's Moonlit Charge should apply Blind through shadows but it currently does. Looks like a similar issue to this closed issue that was fixed in the past: https://github.com/EdenServer/community/issues/3491

Steps to reproduce:
1. Have shadows on
2. Have Fenrir Prime use Moonlit Charge
3. Observe that the shadow blocks the damage correctly but the blind is applied anyway.

![image](https://user-images.githubusercontent.com/13668758/195926017-438b5163-0318-40ef-acfb-f53d29915d89.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
