### ISSUE TITLE
Aht Urhgan Mission 42: Path of Darkness - Delayed KI Replacement

### ISSUE THREAD

**Issue by DivoXI** [EdenServer/community#5322]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Client version: 30181205_0

Compared to Toau mission 44, mission 42 is incorrectly implemented when it comes to requesting a Key Item (KI) replacement from the NPC after failing the mission.

Currently on Eden:
- Mission 42 forces the player to wait for next Japanese day to get a KI replacement.
- Mission 44 allows the player to get a KI replacement immediately after failing the mission.

Yet the text on the retail wiki for both KI replacements is exactly the same: both don't have a time delay.
-  [August 2008 retail wiki](https://ffxiclopedia.fandom.com/wiki/Aht_Urhgan_Mission_42:_Path_of_Darkness?oldid=638945) states that "If you fail you will lose your key item: [Nyzul Isle Route](https://ffxiclopedia.fandom.com/wiki/Nyzul_Isle_Route). Another one can be obtained from [Rodin-Comidin](https://ffxiclopedia.fandom.com/wiki/Rodin-Comidin) at (I-7)."
- [August 2008 retail wiki](https://ffxiclopedia.fandom.com/wiki/Aht_Urhgan_Mission_44:_Nashmeira%27s_Plea?direction=prev&oldid=675787) states that "If you fail the mission, you will need to return to [Naja Salaheem](https://ffxiclopedia.fandom.com/wiki/Naja_Salaheem) to obtain another [Mythril Mirror](https://ffxiclopedia.fandom.com/wiki/Mythril_Mirror) key item for another fight."

Therefore, players should be allowed to request a KI replacement immediately after failing mission 42 in order to match the wiki text and the behavior of mission 44. In other words, another Nyzul Isle Route can be obtained from Rodin-Comidin **immediately**.

**Comment by KnowOne134** [comment]
Mission 42 I know for fact since capturing them that current retail has a 1 game day wait which usually means it was adjusted down from a jp midnight just not documented

**Comment by KnowOne134** [comment]
corrected in the 11/19/2023 update
