### ISSUE TITLE
sandy mission 2-3  cant be completed

### ISSUE THREAD

**Issue by larserwin** [EdenServer/community#5323]
sandy mission 2-3 

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
hi larserwind, the mission is able to be completed by others, please make a call to a gm using the help desk menu to help sort your individual situation out so that you can progress!

**Comment by ConteAlmaviva** [comment]
Possible explanation here: https://github.com/EdenServer/community/issues/5265 Halver is involved in a lot of quests, and I think if an NPC is involved in multiple quests, sometimes you need to progress in or complete one before you can start or progress in another.

**Comment by 59blargedy** [comment]
no details provided here, so not really a bug we can look at and address, closing
