### ISSUE TITLE
Validate rancor tank drop rate

### ISSUE THREAD

**Issue by maxdecphoenix** [EdenServer/community#5324]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

While messing around in Uggalepih, I acquired two of the 'rancor' items in quick succession. Knowing a third was a 100% drop from a scarcely camped NM and could be acquired quickly, i decided to go for the fourth one on an impulse.  I acquired the NM one after a few moments effort, and then began killing Hexers in Yhoat expecting the final item to not take too much time.

Well shit if it didn't.  I spent about an hour killing hexers that evening, possibly 25-30.  Nothing.  Sunday rolled around and I decided to try again.  I had two characters pumping out over 5 kills in 3 minutes each.  After an hour or so of that, i switched one from /thf to full thf and joined up. While I haven't kept track, I would be shocked to learn i haven't killed over 200 of these in the last 3hours.  I found an endless loop murdering 8-9 Hexers per 6 minutes and mindlessly plowed through for over an hour and a half, then again for over an hour after a short break.  80% of more of these kills with TH1 or 3.  Nothing.  Just per the law of average I should have expected to have seen 14 after this many kills, assuming the 7% drop rate reported by ffxidb.  Which is comparable to the other possible drops all of which have a roughly comparable drop rate.

So either the drop rate has been severely reduced, which ok. fine; the drop was some how inadvertently removed from Hexers, or I have just been stupid unlucky.  Either way i get investigating the item isn't a massive priority, but some response would be appreciated.

**Comment by 59blargedy** [comment]
will look into it, thanks

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
