### ISSUE TITLE
Aquarius attack speed is too slow

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5325]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

His attack speed is way too low on eden.

Can see right attack speed here
https://www.youtube.com/watch?v=7uY2_hBC1mc&t=59s

**Comment by ConteAlmaviva** [comment]
This video footage looks like it's playing back at double normal game speed, so it's sort of hard to make an exactly accurate comparison.  I duoed him a bit back and his attack speed seemed like what I remembered from retail.

**Comment by Steam-arch** [comment]
Oh yeah im drunk as hell
