### ISSUE TITLE
Tsutsuroon missing items from vendor list

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5326]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Every other merchant in nashmau seems to have correct lists and prices. But Tsutsuroon is missing tons of items and prices of current items are mostly incorrect.

Current list:
![image](https://user-images.githubusercontent.com/69089249/196417484-31a73252-1487-42b8-918e-b28055a6f4d6.png)
![image](https://user-images.githubusercontent.com/69089249/196417521-57183a83-b4ec-4c3b-b53b-594b709cdb22.png)
![image](https://user-images.githubusercontent.com/69089249/196417551-7e46e197-553e-471c-b6c7-ccdecb8064ef.png)

Seems to be missing:
![image](https://user-images.githubusercontent.com/69089249/196417421-8c0a3aa0-024b-4420-be52-0b4a0cd12852.png)
![image](https://user-images.githubusercontent.com/69089249/196415566-09dfd91a-2d82-4de4-8339-0bc490217449.png)
![image](https://user-images.githubusercontent.com/69089249/196415715-803d833a-c9ef-49bc-9fac-935821af0cae.png)
![image](https://user-images.githubusercontent.com/69089249/196415755-164a5477-dfdd-4b6e-bbcc-58381871810f.png)
![image](https://user-images.githubusercontent.com/69089249/196415818-4a98d53a-b77c-484f-ba70-73bb80b6306c.png)
![image](https://user-images.githubusercontent.com/69089249/196415852-6ebd098c-074e-4fc8-91f0-032a0dc364ae.png)
![image](https://user-images.githubusercontent.com/69089249/196415916-4f4ec14b-e38a-4982-83da-e2e9cfbe81b2.png)
![image](https://user-images.githubusercontent.com/69089249/196415955-e53e6b02-e824-4fc8-87f4-d525723ff684.png)
![image](https://user-images.githubusercontent.com/69089249/196416246-4989aef1-e9cc-4e71-961e-d4488dd6eb7d.png)
![image](https://user-images.githubusercontent.com/69089249/196416272-cbf9e6fc-2644-4427-9039-2e8a66a1a9da.png)
![image](https://user-images.githubusercontent.com/69089249/196416385-f8b22dd4-674c-4ce5-8c47-e8c912c6818e.png)
![image](https://user-images.githubusercontent.com/69089249/196416479-601096fa-90ca-45f4-9b37-68351195d1d1.png)
![image](https://user-images.githubusercontent.com/69089249/196416622-a467f081-aa8b-4817-80d5-b185c56a6519.png)
![image](https://user-images.githubusercontent.com/69089249/196416722-8f669c7d-5d74-45c6-a88e-20d48bcde6dd.png)
![image](https://user-images.githubusercontent.com/69089249/196416745-01e167f0-6eb5-429a-add4-3f2dbfa83bca.png)
![image](https://user-images.githubusercontent.com/69089249/196416782-76d7d7eb-d989-4e53-ab60-a293d25876fc.png)
![image](https://user-images.githubusercontent.com/69089249/196416821-a4e9ceae-6da1-48d9-b402-f897a355da9c.png)
![image](https://user-images.githubusercontent.com/69089249/196416886-3d4c2150-f38f-47e5-acf9-bad66d8698cb.png)
![image](https://user-images.githubusercontent.com/69089249/196416901-2520615e-6935-4ec1-af3e-2d7a2065d946.png)
![image](https://user-images.githubusercontent.com/69089249/196417031-1c164322-02a5-4bb8-b0ca-612db8828ef7.png)

wiki revision:
https://ffxiclopedia.fandom.com/wiki/Tsutsuroon?type=revision&diff=516743&oldid=388248

Going through every npc in nashmau, noticed Mimiroon is a mute on eden, is he supposed to have a text line on retail?
![image](https://user-images.githubusercontent.com/69089249/196420680-a5379cb2-8f1a-4757-9891-4b9df23100be.png)

**Comment by 59blargedy** [comment]
going to track this under the existing tickets about this, thank you for reporting.
