### ISSUE TITLE
Volt Gun always dealing 0 damage after PUP code refactor patch 

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5327]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

As of the 9/21 patch, a lot of the attachments stopped working and were fixed in the patch the following day. Volt Gun looks like it went unreported, but this one always deals 0 damage since that patch:

![image](https://user-images.githubusercontent.com/13668758/196705048-282dec15-5690-4cbe-82c6-1cb03fd2ef0d.png)

I've tested on a variety of enemies (including much lower level enemies with no lightning res) and other players have reported that they haven't seen a non-zero value since that day as well.

version 30181205_0

**Comment by KnowOne134** [comment]
Corrected on 7/5/2024
