### ISSUE TITLE
Aht Urhgan Mission 37: Path of Blood - No 2nd CS.

### ISSUE THREAD

**Issue by DelphiXI** [EdenServer/community#5328]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Client ver: 30181205_0

Char Name: Pinssi
Aht Urhgan Mission 37: Path of Blood - No 2nd CS.
https://classicffxi.fandom.com/wiki/Aht_Urhgan_Mission_37:_Path_of_Blood
Zoning to Salaheem office doesn't give me the 2nd CS involving Ayame.

Kay Item:
![image](https://user-images.githubusercontent.com/114884851/196769351-e7a28e7a-cbff-44c4-86ec-26b3dd01cc0a.png)
Mission Log:
![image](https://user-images.githubusercontent.com/114884851/196769438-a0969198-6fb4-4101-b77d-87a0285f1b1a.png)

**Comment by 59blargedy** [comment]
looked into this and cant replicate. my guess is your mission log got glitched, but leaving up for a while just in case this happens to others.

**Comment by KnowOne134** [comment]
no other comments as of yet
