### ISSUE TITLE
Orcs are above the ceiling in Yughotto Grotto 

### ISSUE THREAD

**Issue by Fng098** [EdenServer/community#5329]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
![image](https://user-images.githubusercontent.com/57783175/197226448-918cb5e4-1b90-48a0-870c-b423f29cf8bc.png)

Version 13081205_0

**Comment by Mozzy4Ever** [comment]
They're supposed to be there. There's 2 floors to yughott grotto, the top one is only reachable by going through Fort Ghelsba and is the area right before Horlais Peak

**Comment by 59blargedy** [comment]
yeah in this case they're supposed to be there. it's not really obvious that yughott is two "floors" but it aligns with climbing all the way up to fort
