### ISSUE TITLE
Thunder Elemental's health filled up when nearly dead

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#533]
Was fighting a Thunder Elemental in Zitah, it was almost dead, and suddenly it's health filled completely up. Was using a bloody bolt at the time. Also I do believe the screen changed when it happened showing that the weather changed (before I engaged, it was double thunder, after I killed it it was only single thunder, perhaps that's the cause).

**Comment by Setz0r** [comment]
sounds like weather change forced it to "respawn" in place which refreshed its hp.

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
