### ISSUE TITLE
Suzaku Sune-Ate Blaze Spikes messaging and animation proccing 100% of time instead of 20%

### ISSUE THREAD

**Issue by ThoseWhoFight** [EdenServer/community#5333]
- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently blaze spikes damage procs often in chat log, but actually does 0 damage to target.

**Comment by 59blargedy** [comment]
the proc rate is only 20%, but messaging will indicate its effect on 100% of hits. so the messaging is messed up, and potentially the rate. need more info on how often these should proc / retail testing. anyway, they do work, just look like they work more.

**Comment by 59blargedy** [comment]
tested this on retail, the proc rate should only be 20%, so basically all that is wrong in this scenario is the messaging/animation shows a 100% proc rate instead of what it;'s actually proccing as

**Comment by 59blargedy** [comment]
Resolved by another dev in december 15, 2023 update
