### ISSUE TITLE
Multi-hit blue magic spells not killing resistant enemies

### ISSUE THREAD

**Issue by Tofutoshi** [EdenServer/community#5334]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Multi-hit spells won't kill mobs resistant to the damage type unless the first hit would kill. Noticed while leveling bludgeon would never finish off leeches due to their blunt resist. So I got a friend to help test.

Tested on a lvl 42 skeleton with around 1000 hp, first hit doing 650 (presumably full damage), the next doing only 280 leaving it right before it were to die.

![Screenshot 2022-10-24 032105](https://user-images.githubusercontent.com/107894001/197506037-8d2360e9-f62a-429e-b09d-e99dd904c20d.png)

Here is a lvl 20 ghoul living a disseverment.

![Screenshot 2022-10-24 033413](https://user-images.githubusercontent.com/107894001/197507032-129bfdd6-6e22-4bbc-a73e-90b55eeb4069.png)

And one where we get a ghoul to 1 hit from death before using disseverment.

![Screenshot 2022-10-24 034032](https://user-images.githubusercontent.com/107894001/197508233-fc7e10f5-4f45-4868-a2d3-cdade296fd47.png)

**Comment by 59blargedy** [comment]
Resolved in december 15, 2023 update
