### ISSUE TITLE
ENM moves all on "entry" list to exit, even if not in party anymore

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5337]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Started an ENM with 2 chars in party, meant to break party before. Left party on 2nd char, logged out to clear BCNM status. Logged back in before completing ENM with 1st char. On chest opening, both chars were moved to exit point even though 2nd char wasn't in party and didn't have BCNM icon.

**Comment by KnowOne134** [comment]
Corrected on 7/5/2024
