### ISSUE TITLE
Holy Cow - Apis too accurate

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#5339]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

Just did a run of Holy Cow on Nin/thf and I think the mobs accuracy might be an issue. I parsed a 3.23% evasion chance with 57 swings on me. I had 382 Evasion. In the video linked the Ninja likely is using less evasion than me, there's some variables you can't tell like merits but his evasion gear is significantly less evasion than I was using. He doesn't have to recast shadows until 2:15 into the fight because the mob is so inaccurate on him. It looks like in that first 2:15 the mob swung 18 times and missed 14 times. 

https://youtu.be/Favb3KCiN2s

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
