### ISSUE TITLE
Low level Mandragora(Tiny Mandragora) aren't suppose to attack twice

### ISSUE THREAD

**Issue by notimezeta** [EdenServer/community#534]
Low level Mandragora like Tiny Mandragora are only suppose to attack once per attack round. I don't know what level or types of Mandragora gets two attacks per round and which ones only get one. But I know for sure at least Tiny Mandragora are suppose to attack once per attack round.

Having Tiny Mandragora attack twice per attack round is too strong and makes leveling in Windy a lot harder than it should be.

**Comment by raventn** [comment]
they are mnks they use both fist tho, even tho they need to be reduced dmg

**Comment by notimezeta** [comment]
They are MNK but Tiny Mandragora(and I think other low lvl mandragora but not sure which) never attacked twice on retail. You can look for videos on youtube if you don't believe me. Tiny Mandragora are too strong because they attack twice.

**Comment by raventn** [comment]
they did tho just could hit you for 0 1 or even 2 dmg maybe max 3 dmg as level 1

**Comment by godmode** [comment]
This is likely a private server but you may be correct. I've modified the h2h damage of all MNK mobs so it will be less of an issue. If you find a retail video (says server and such and from an old date) or capture from retail yourself please post.

**Comment by notimezeta** [comment]
Pretty sure that video is on retail.  The previous video he made shows the retail system messages. https://youtu.be/L8WCwwT3T0k?t=857

Another video that's on retail with the retail server messages, shows it attacking once. (The slimes are from a Dragon Quest cross-over SE had at that time.)
https://youtu.be/Oh77T72s0Cg?t=927

I don't think I'll be able to find a video from 2007 retail era showing Tiny Mandragora attacking. But i'm pretty sure it wasn't changed. And I don't have an active retail sub or I'd log on and record that.  

Just thought I'd post this bug cause It's kinda annoying while starting out as a WHM in Windy and having to avoid Tiny Mandragora because they're too strong with the double attack.
