### ISSUE TITLE
 Imdugud PHs have incorrect respawn time

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5343]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

PHs are 5 min respawns atm, should be 16 min

![image](https://user-images.githubusercontent.com/69089249/199067090-60d35cd6-624c-4acc-83af-a9f448b94499.png)
![image](https://user-images.githubusercontent.com/69089249/199067222-3982e456-7320-4ece-a063-c6ac2109e062.png)
![image](https://user-images.githubusercontent.com/69089249/199067331-d11a47f1-7f18-4b4b-b0dc-09ec398160fc.png)

Notes about how long it takes to pop:
![image](https://user-images.githubusercontent.com/69089249/199066262-c1a354db-e0bd-439d-9315-09c055e23d2e.png)

![image](https://user-images.githubusercontent.com/69089249/199066512-40f2b080-1291-49ba-adf0-8d4d9674c51d.png)
![image](https://user-images.githubusercontent.com/69089249/199066846-740adc2a-70be-4142-9594-2ee02c0e5970.png)
![image](https://user-images.githubusercontent.com/69089249/199067130-99afd7e7-1abd-43a6-a629-e298d188a565.png)

---------------

Also its currently set to 21-24h, not sure if correct, but cant fully debunk this atm, but if we go by this:
![image](https://user-images.githubusercontent.com/69089249/199220591-42227c90-6ef2-41b3-8561-77d13cb789ac.png)
It should propably just be a lotto pop with 0-2h cooldown (?), similar to Ose

**Comment by Steam-arch** [comment]
1 more thing to be noted about the spawn conditions on eden vs retail. Currently all/most of the areas Hippos might act as a PH. The problem is how fast it can be popped currently (if window is open) because it takes 5-30 min on eden.

So increasing the PH respawn from 5>16 min has little effect on how fast it can be popped because theres a lot of hippos around.

Have to decrease the amount of PHs too on top of increasing the respawn time to get a correct ~era spawn rate.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
