### ISSUE TITLE
Things wrong with Self-Destruct (cluster)

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5345]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Doing a seperate ticket I suppose since from first glance seems to be 2-3 things slightly incorrect with self-destruct used by clusters.

1: Chance % of all clusters exploding under 20% seems to be too high. Seems to be closer to 50% on eden, Sweeping Cluster Test showed 5/15, 33,33% chance for it to explode all clusters on a self-destruct under 20% HP. 

2: Damage formula for enemies seems to be off? Below some numbers from retail, maybe someone can pull the ~correct formula from it (once someone great with a capture suite gets cluster HPs!) :

Some DMG numbers lvl 99rdm/blu vs 73-74 clusters:
Shell V + Phalanx II (195 enhancing) on

243 dmg (XX% 2 > 1 bomb)
197 dmg (XX% 3 > 2 bombs)
306 dmg (XX% 2 > 1 bombs)
167 dmg (15% 3 > 2 bombs)
256 dmg (14% 2 > 1 bombs)
606 dmg (~15% 3 > 0 bombs)
165 dmg (14% 3 > 2 bombs)
514 dmg (13% 2 > 0 bombs)
616 dmg (51% or 52% 3 > 2 bombs)
470 dmg (~12% 2 > 0 bombs)
461 dmg (39% 3 > 2 bombs)
96  dmg (12% 2 > 1 bombs)
163 dmg (14% 3 > 2 bombs)
241 dmg (13% 2 > 1 bombs)
173 dmg (16% 3 > 2 bombs)
537 dmg (~15%ish 2 > 0 bombs)
610 dmg (~16%ish 3 > 0 bombs)

lvl 73/74 cluster has ~ XXXXX HP (I should have taken cluster levels mb)

3: Edens tp move selection % of Self-destruct rate under 20% could use a confirmation on what it is set to.  60/55-21% on retail seems to follow the standard 1/5 (5 tp moves total)  and seems to match on eden, but the rate on retail seems to spikes up and double at 20% HP (according to the smallish retail sweeping cluster test anyhow). (this one might be right on eden)

Related tickets: 
https://github.com/EdenServer/community/issues/2685
https://github.com/EdenServer/community/issues/4755

--------------------------------

Self-Destruct test
Sweeping Clusters MountZ

Self- Destruct rate under 20%
Total:
15/38 - 39,47%

Cluster1
1/4
Refueling (2 bomb)
Refueling (2 bomb)
Formation Attack (2 bombs)
Self Destruct (2 > 1 bombs)

Cluster2
2/5
Sling Bomb (3 bombs)
Circle of Flames (3 bombs)
Formation Attack (3 bombs)
Self Destruct (3 > 2 bombs)
Self Destruct (2 > 1 bombs)

Cluster3
2/3 
Formation Attack (3 bombs)
Self-Destruct (3 > 2 bombs)
Self-Destruct (2 > 1 bombs)

Cluster4
1/3
Sling bomb (3 bombs)
Sling bomb (3 bombs)
Self Destruct (3 > 0 bombs)

Cluster5
2/5
Sling Bomb (3 bombs)
Formation Attack (3 bombs)
Formation attack (3 bombs)
Self-Destruct (3 > 2 bombs)
Self Destruct (2 > 0 bombs)

Cluster6
1/2
Refueling
Self-Destruct (2 > 1 )

Cluster7
1/4
Circle of Flames (2 bombs)
Formation Attack (2 bombs)
Formation Attack (2 bombs)
Self-Destruct (2 > 1 bombs)

Cluster8
2/5
Sling bomb (3 bombs)
Refueling (3 bombs)
Self-Destruct ( 3 > 2 bombs)
Circle of Flames (2 bombs)
Self-Destruct ( 2 > 1 bombs)

Cluster9 
2/2
Self-Destruct (3 > 2 bombs)
Self-Destruct (2 > 0 bombs)

Cluster10
1/5
Formation Attack
Circle of Flames
Sling bomb
Formation Attack
Self-Destruct (3 > 0 bombs)

% of all bombs exploding under 20%
5/15

---------------------

Wiki Claims clusters use self-destruct under 50% HP, seems to be 60%, which is set correctly on eden.
![image](https://user-images.githubusercontent.com/69089249/199817572-3b6f8cca-40d7-4341-bb3f-beb37c3a818d.png)
![image](https://user-images.githubusercontent.com/69089249/199824683-ce6bb009-dc78-4cc2-90f6-243d09696e9b.png)

 
![image](https://user-images.githubusercontent.com/69089249/199818103-ebaa1f9d-2e46-400d-bef1-499ce9c4ffb1.png)

**Comment by Steam-arch** [comment]
Let me know if you think I missed something

**Comment by 59blargedy** [comment]
we know damage is too high but adjusting to a guess isn't something we tend to do so have just left until we can get to it, this gets us closer. i will want more samples to move forward with a change; not necessarily for you to do just what i would need to be the one to change it. either way thanks for getting the ball rolling.

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
