### ISSUE TITLE
Aern Wyvern pets are immune to Sleep & Lullaby

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5346]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Eden:
![image](https://user-images.githubusercontent.com/69089249/200041466-5abed728-ce10-40db-bcba-8c6466fa4175.png)
![image](https://user-images.githubusercontent.com/69089249/200042543-3dca555a-0dcd-49ea-b1ef-ef1911fc5d5e.png)

Retail:
![image](https://user-images.githubusercontent.com/69089249/200037235-9da549ea-7b2d-49e5-b58a-0f6bb03dcf99.png)

Problem with Atleast Om'aerns and Aw'aerns Wyvern pets

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
