### ISSUE TITLE
Wearing GP Rings Can Still Result in HQ Items

### ISSUE THREAD

**Issue by iamyhhy** [EdenServer/community#5347]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Wearing the CC GP ring (Tailor's Ring) still results in HQ items. This happened to me in Desynthesis of the Baron's set several times: have seen resulted in HQ1 and HQ2 items. GM has tested in on other GP rings as well and has duplicated the same issue (I think the GM tried the Smithing GP ring, but I don't remember exactly).

**Comment by dowzer** [comment]
It looks like they do prevent HQ desynthesis

All results while wearing Smith's Ring were NQ until near the end of the video (around 44min)

https://www.youtube.com/watch?v=87dybJndVGc

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
