### ISSUE TITLE
Incorrect conquest rank requirements on various CP items

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5348]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Somewhat related to #2205, though that's moreso about messaging being incorrect.

2 common items that I know that confuse people are Royal Knight's Chainmail, and Royal Knight's Breeches. Currently on Eden, both require Sandy being rank 1 in conquest to purchase. Both https://ffxiclopedia.fandom.com/wiki/San_d%27Oria_Conquest_Points_Items?oldid=666614 and http://wiki.ffo.jp/wiki.cgi?Command=HDetail&articleid=92842&id=497 say that Sandy can be either rank 1 **or** rank 2 to purchase those items. These are the two that I know of off the top of my head, I'm unsure if any others are incorrect.

JP wiki also has a nice table showing each rank for each nation, and what conquest ranking is required for each item in that rank.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
