### ISSUE TITLE
Tyrannic Tunnok HP too low

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5350]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Confirmed to have ~17k HP on retail (1714 dmg did 10% HP), 9k HP on eden
![image](https://user-images.githubusercontent.com/69089249/200282720-28cb8111-2d9a-4841-88a0-892574a7314c.png)

-----------

Seems to have some STP/lowered WS thresholds similar to angler orobon in ISNM3000, does not have regain. Got 1k tp from just 8 x 221 delay sword attacks under 25% HP.
![image](https://user-images.githubusercontent.com/69089249/200290039-2b55720b-9070-4120-bd24-80bf78f3a80f.png)
No filters on.

In usegis vid he is very spammy with TP moves and under 25% gets 1k tp with just 5 soboro hits aswell
https://www.youtube.com/watch?v=pSK_hTs8jVw

![image](https://user-images.githubusercontent.com/69089249/200292355-44a14632-6dc9-494b-831e-018c4ed0de0e.png)

-------

Couldnt confirm wikis large att boost+ the lower HP % Similar to genbu. It seems very minor (checked era vids too). Id assume wiki statement was confused with sharp sting boosting attack and hitting a lower level guys
![image](https://user-images.githubusercontent.com/69089249/200289348-5b054c08-9cd1-4ac6-84cb-417cacf4c6e3.png)

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
