### ISSUE TITLE
Lindwurm issues

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5351]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

1: Hits too weak atm, like a EP raptor, around 80-110 on NIN without protect
![image](https://user-images.githubusercontent.com/69089249/200412505-047bfe66-5280-4466-9945-e516e5d5a563.png)

Should hit around 150-199s
![image](https://user-images.githubusercontent.com/69089249/200412647-159afb25-3b93-40ef-b104-24110fa5a84f.png)
![image](https://user-images.githubusercontent.com/69089249/200412834-2de48185-312f-49e4-a7e4-2f490821dc70.png)
https://www.youtube.com/watch?v=zXRspRQ-9Zo&t=335s

2: Missing sleep immunity

retail:
![image](https://user-images.githubusercontent.com/69089249/200422749-f27a4e93-3c17-4afe-87f9-61fdd6756a7c.png)

3: HP Too high, has +20k on eden, 3,666 damage brought it to 74% which would be around 14k if we go by that

![image](https://user-images.githubusercontent.com/69089249/200423054-126dae38-2705-41f3-a982-19886233fcfb.png)

4: Missing DA Trait
![image](https://user-images.githubusercontent.com/69089249/200424713-cc2e6f0e-afbc-423f-8c79-b762f2f335b9.png)
![image](https://user-images.githubusercontent.com/69089249/200424766-2f40651e-55f9-4473-85fc-838685a9e9fb.png)
![image](https://user-images.githubusercontent.com/69089249/200424803-f0526a45-0a4a-46d3-80e5-fed050c81e98.png)
![image](https://user-images.githubusercontent.com/69089249/200425337-af648e39-0486-4606-a0b8-fab6ca2059bf.png)
![image](https://user-images.githubusercontent.com/69089249/200426498-4bb7a17f-4b0d-4134-aea0-a068cd7b100b.png)

![image](https://user-images.githubusercontent.com/69089249/200426295-32a80962-f92a-4f8b-a497-aea62aa5d5f0.png)

DA rate seems about same as triple attack rate, [X] indicates number of (same kind) of attacks (misses / hits / crits are seperate so if theres a [2] misses target between misses, its a double attack 100%, otherwise it can also be a hit + 2x miss/hit since no stamps on this.
Wiki says it has  regen in spawn area but couldnt find a spot where it had a regen, ran around abit

**Comment by 59blargedy** [comment]
resolved in previous update
