### ISSUE TITLE
Stealing Buffs should only give the remaining duration not the full duration 

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5353]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I have only tested with Voracious Trunk, but presumably this applies to Aura Steal as well. When an enemy applies a buff, regardless of if you cast to steal it right away, or wait until the buff is almost off, the buff is reapplied to you with its full duration. Per the wiki page it should only steal the remaining buff duration.

https://ffxiclopedia.fandom.com/wiki/Aura_Steal

![image](https://user-images.githubusercontent.com/13668758/200424900-bcdd0c86-3a07-41fd-8eb6-28e9742ef6be.png)

I have tested exclusively with Voracious Trunk vs Crab mobs using Metallic Body, Bubble Curtain, and Scissor Guard. To reproduce, fight a crab, let it use one of the moves, steal the buff and note the full duration buff time. Let it use it again, wait some time, steal it and note that the buff is still the same/full duration.

version 30181205_0

**Comment by KnowOne134** [comment]
Corrected on 11/21 patch
