### ISSUE TITLE
Bomb Queen unable to spawn Bomb Bastard

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5355]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Bomb Queen seems to be unable to give birth to a bastard. 

![image](https://user-images.githubusercontent.com/69089249/200594192-297e7d2e-bd41-44ed-a54b-d80dbc3db645.png)

Note: Will leave char there to pop adds for a few more hours to see if a bastard actually pops, Ill edit/close the bug report if he appears.

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
