### ISSUE TITLE
Hurricane Wyvern/Wyvern sight aggro range too large

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5356]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

10 on retail, 12 on eden.

![image](https://user-images.githubusercontent.com/69089249/200612865-eaf7d3fd-961d-407e-8c27-247015bdf2f7.png)

**Comment by 59blargedy** [comment]
Resolved by another dev in February 20, 2023 update
