### ISSUE TITLE
Hachiman Sune-Ate incorrect vendor price

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#5357]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

Hachiman Sune-Ate vendor at NPCs on Eden for 2100ish gil per when with base retail fame they NPC for 11,400G

At work so I'll update with the actual Eden vendor price. 

https://ffxiclopedia.fandom.com/wiki/Hachiman_Sune-Ate

**Comment by KnowOne134** [comment]
corrected in the 11/19/2023 update
