### ISSUE TITLE
FFXI-3001 error after selecting character

### ISSUE THREAD

**Issue by Toxophile** [EdenServer/community#536]
Any time I try to log in with any character, even a newly created one, I get a black screen and eventually a FFXI-3001 error. I was able to log in and play as normal last night and have not made any changes to my system since then. I can log in fine from my laptop, but on my desktop I always get the FFXI-3001 error.

**Comment by godmode** [comment]
Was this resolved @Toxophile?

**Comment by Toxophile** [comment]
Not resolved. After 3 days it just stopped happening. I did not change anything or take any action that prompted it to stop happening. Just got home from work one day and suddenly it worked again. There's already another person in discord saying it's happening to them too.

**Comment by Boss821** [comment]
I'm having this issue on my desktop after a few days of no problems. If my character is in San d'Oria I can't log on to it, but I can from my laptop just fine. Then if on the laptop I leave the city and log out I can get on with my desktop. I have reinstalled and tried the other fixes that i found with the 3001 error but they have not worked.
