### ISSUE TITLE
Memento Mori buff is too strong

### ISSUE THREAD

**Issue by somedudestolemyname** [EdenServer/community#5363]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

memento mori is more than doubling damage on its own

naked while casting on lvl 1 mandies
![memento](https://user-images.githubusercontent.com/97771638/201251055-b44b30b7-954e-4738-90a7-909bb272b760.png)

vs +20 mab from armor 
![mab gear](https://user-images.githubusercontent.com/97771638/201251160-84c0e8fe-1b1a-4ee5-8af6-d828b58b39e6.png)

**Comment by 59blargedy** [comment]
fixed live, thanks!
