### ISSUE TITLE
Gargoyle Boots Stoneskin effect, doesn't apply properly

### ISSUE THREAD

**Issue by ThoseWhoFight** [EdenServer/community#5364]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Gargoyle Boots Stoneskin enchantment effect doesn't seem to be applying at all, kept boots equipped. Still had the buff applied on my status effect bar (unsure if there's supposed to even be a buff on the user itself, possibly related?). Tested in ballista but I'm guessing the issue probably follows outside of pvp too.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/37572397/201457343-392372a7-3b0c-4e30-8679-43ebc29d1b34.png">

<img width="386" alt="image" src="https://user-images.githubusercontent.com/37572397/201457349-db428aea-f958-4365-b8a9-3ec126c765f5.png">

**Comment by ThoseWhoFight** [comment]
May be worth auditing the effect on these as well since it's very similar.
![image](https://user-images.githubusercontent.com/37572397/201457409-2c22d070-8b57-45ab-b2ba-4b55cfcf9d4a.png)

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
