### ISSUE TITLE
BLU Job Trait bug: Evasion Bonus not working

### ISSUE THREAD

**Issue by DwinJohnsel** [EdenServer/community#5365]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

client version: 30181205_0

To test/recreate:
1. As Elvaan, 75 BLU/NIN, 4 evasion skill merits, naked, with spells Hysteric Barrage and Screwdriver not equipped: checkparam shows Evasion 257. "Evasion Bonus" is not in the Job Traits window (as expected since spells are not set).
2. Set spells Hysteric Barrage and Screwdriver. "Evasion Bonus" now appears in the Job Traits window (as expected), however checkparam still shows Evasion 257. This should now read Evasion 267.

Other notes: while I was testing, I checked the BLU Job Trait from setting spells for Accuracy Bonus and Defense Bonus, using checkparam to verify, and they both appear to be working properly. From my testing I only found the Evasion Bonus trait to not work based on checkparam. However I did not go further and test any other job trait bonuses.

![evasion_bonus_notworking_1](https://user-images.githubusercontent.com/100724168/201498010-84b8f8e0-69b6-4dfb-9bfa-6d764965595e.JPG)

![evasion_bonus_notworking_2](https://user-images.githubusercontent.com/100724168/201498015-303804ae-5702-41c4-bb04-030e6644dbc1.JPG)

**Comment by 59blargedy** [comment]
Don't worry we all see every bug report when posted!, And some of us get emails. I have them all memorized at this point. pings aren't needed for stuff and spoiler alert this is already fixed for next update. 
Bumps of old tickets I already have memorized on the other hand... ::makes slashing motion across throat:

**Comment by DwinJohnsel** [comment]
<Understood> thanks blarg, I shan't ping anyone in future reports. Also I did search the existing open cases for "evasion" and didn't find this one, so I'm sorry if it was already reported somehow.

**Comment by 59blargedy** [comment]
Nah you're fine! This was the first time it's been reported.

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
