### ISSUE TITLE
TOAU: The Black Coffin Issues

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#5367]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Ver 30181205_0
Here are some various issues I have come across with The Black Coffin mission.

Duo'd the black coffin while dual boxing SAM THF BRD COR, 
Opened the first wave with Horde and Gessho did not engage for the entire first wave.
Gessho aggros upon the spawn of the second wave. 
Causing the Captain to give up before defeating the other Ashu talif crew members appears so cause a crash,.
Have not tested this by defeating everything first. Upon logging back in the completion cutscene plays and you are ejected to Nashmau. This has happened on both my main characters progression and my alts.

**Comment by KnowOne134** [comment]
corrected in last update
