### ISSUE TITLE
Blind 1 & 2 caps incorrect

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5373]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

Currently Eden is using retail's Blind 1 & 2 potency calculations, with caps of 50 and 90 (respectively). 
In era, Blind 1's calculation was `( Castist INT - Opponent MND + 60)/4` with a cap of 20 according to https://ffxiclopedia.fandom.com/wiki/Talk:Blind
Blind 2's calculation was `( Castist INT - Opponent MND + 100)/4` with a cap of 30 according to various BGwiki threads (See testing Discord for links/research)

EDIT: Duration/Calc are correct, it's the caps that are wrong (didn't realize I had 999 INT in testing >_>)

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
