### ISSUE TITLE
Aggro ranges and how they work

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5375]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

https://docs.google.com/spreadsheets/d/1Hdvt4dyGJW5ih296VnAhqOzbVqYX_A8lGnW27megCZo/edit#gid=0
(somewhat on the works still but mostly concluded)

![image](https://user-images.githubusercontent.com/69089249/202679167-23f1eee5-7a92-46cb-bff5-a43b201db995.png)

**Comment by 59blargedy** [comment]
resolved by another dev in february 20, 2023 update
