### ISSUE TITLE
Birdtraps in Carpenters Landing not dropping Flytrap leaf

### ISSUE THREAD

**Issue by Fng098** [EdenServer/community#5376]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Ver 30181205_0
Trying to pop Orctrap have killed 40 Birdtraps with THF4.  No flyleaf drops.

**Comment by 59blargedy** [comment]
hmm...double-checked, it exists, is rare category, which matches ffxidb. sounds like you're just getting extraordinarily unlucky.
