### ISSUE TITLE
CoP Three paths Disaster idol hits too weak

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5377]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Hits too weak on eden.

Hits around 80-100 to protect III 75 DDs no PDT on
![image](https://user-images.githubusercontent.com/69089249/202875271-50168bdb-1a49-43db-9893-af9de70aa11c.png)
![image](https://user-images.githubusercontent.com/69089249/202875275-0a7ee768-7f15-461c-9b7f-dde8ea317030.png)

Era video where Garuda takes ~105 per hit:
![image](https://user-images.githubusercontent.com/69089249/202875298-077043e1-ba36-46f3-b071-1b72f3695a18.png)
![image](https://user-images.githubusercontent.com/69089249/202875316-82d466c9-cb0d-4618-8dd3-82926aab5bc9.png)

https://www.youtube.com/watch?v=aXlK5CusWBw

**Comment by 59blargedy** [comment]
this was adjusted in the august update, the idol spawns / attacks based on the attacker's level hence the damage variations
