### ISSUE TITLE
Woodland Sage issues

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5378]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

1: DA too high on eden
![image](https://user-images.githubusercontent.com/69089249/202916798-309d82a7-1b55-447a-be71-72a097cf8fe6.png)

Retail seems more like 5-10%
![image](https://user-images.githubusercontent.com/69089249/202916824-8639777e-9bc4-4e3c-ae92-c1df7dba63e3.png)
(note propably some parries here)

2: Hits slightly too weak
Hits around 55 to no protect mnk 271 def mnk
![image](https://user-images.githubusercontent.com/69089249/202917201-17b4d8aa-09c4-41aa-bb53-5a5fc5a30fd0.png)

Should hit abit more
![image](https://user-images.githubusercontent.com/69089249/202917228-cc40799f-1887-48f0-856d-b6aadf8d6b88.png)
![image](https://user-images.githubusercontent.com/69089249/202917268-c7942160-cb0e-47a1-a8cd-2777314e35b5.png)
![image](https://user-images.githubusercontent.com/69089249/202917276-a5442ecd-a076-4e14-9e4d-fa27104ed91a.png)
![image](https://user-images.githubusercontent.com/69089249/202917283-dd97a554-a4a0-40ce-9b66-8b7b385f8cb6.png)
![image](https://user-images.githubusercontent.com/69089249/202917292-5bb00d21-dbd5-4359-a025-10a93494fae1.png)
![image](https://user-images.githubusercontent.com/69089249/202917311-ee9f5601-ea64-4752-aacb-a62d0601ad77.png)
![image](https://user-images.githubusercontent.com/69089249/202917320-d820c981-009d-444e-b08f-ec6d2e5ec300.png)

3: Sound range should be 20 game time 17-07 (dusk to dawn) and 10 game time 07-17

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
