### ISSUE TITLE
Poison (and all DoTs) should be removed upon entering Mog House

### ISSUE THREAD

**Issue by masamuneCS** [EdenServer/community#5379]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
30181205_0

Poison from a Recluse Spider in Kuftal Tunnel was not removed upon warping and entering mog house. Subsequently, the poison continued to persist after I changed jobs.

Oldest backdated wiki page mentioning effects of entering mog house, no patch note related to this being a new implementation at this time https://ffxiclopedia.fandom.com/wiki/Mog_House?oldid=712194

Similar ticket https://github.com/EdenServer/community/issues/2051#issue-494926870

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
