### ISSUE TITLE
Claret despawn

### ISSUE THREAD

**Issue by Goutan** [EdenServer/community#5380]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

When kiting Claret, it changed aggro to someone else within the alliance. It then pathed into the wall to pursue that person, killed them, then despawned. We didn't witness the despawn so we don't know if it did right away after killing the player. (the player it killed was afk) We confirmed the despawn by seeing the ??? reappear.

**Comment by 59blargedy** [comment]
resolved november 21, 2022
