### ISSUE TITLE
Can't get samurai job after completing quest

### ISSUE THREAD

**Issue by jookiez** [EdenServer/community#5381]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version: 30181205_0

I completed the samurai job quest about 30 mins ago. I have the Mumeito in my inventory. Yet when I go to my mog house, the samurai job is still unavailable.

![image](https://user-images.githubusercontent.com/70607817/203120736-2ecf8635-b17a-4dc4-a722-f95d72d800eb.png)

![image](https://user-images.githubusercontent.com/70607817/203120764-2dd98e1e-fe96-4199-b8cf-594e53c4e885.png)

Note: When I went back to the quest giver, it gave me the cutscene again, and another Mumeito:

![image](https://user-images.githubusercontent.com/70607817/203120841-cfc3d022-fae9-453e-b182-d97341590863.png)

**Comment by 59blargedy** [comment]
resolved by another dev november 21, 2022
