### ISSUE TITLE
Crystals dropping incorrectly / too often after patch

### ISSUE THREAD

**Issue by Kythaela** [EdenServer/community#5384]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

Crystals are dropping on mobs that don't give exp. Also feel like they are dropping too frequently, probably a 90% drop rate.

**Comment by 59blargedy** [comment]
this should be resolved, can comment if not
