### ISSUE TITLE
still cant activate moglification?

### ISSUE THREAD

**Issue by Bait31** [EdenServer/community#5386]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
hi i tried to activate my moglification as per update and it doesnt appear to be working. my active mh say moghancement not moglification. i have both items (150 &200) my aura needed is earth ( i have 50 E 22F, 8wa, 1 l, 1 wi) so well within arua guidelines. my top highest aura affect is the cc so thats why i have the cc moghancement, but it should be showing up as moglification. have posted a ss int he crafting chanel of what my active effect looks like. have tried taking them out of layout putting them bk in, tried taking them out putting one in, backing out, putting other in. waited for mini update, still nothing,

**Comment by 59blargedy** [comment]
can you try placing both items in safe 1 and seeing if that resolves your issue?

**Comment by Bait31** [comment]
hi have tried it in mh 1 and 2, have moved all my furniture out and just had the 2 items, ive tried putting them in one at a time zoning and reentering. maybe because i got the item before the patch mine is somehow bugged? was thinking if poss could we duplicate my sign, ill drop my original one and try the new one? i cant think of anything else i can do. i dont know why its not working

**Comment by 59blargedy** [comment]
should be working for you now based on today's update, can you confirm?

**Comment by Bait31** [comment]
i took it out of mh2 and back into mh1 and yes can confirm it is now working :) thank you!

**Comment by 59blargedy** [comment]
Awesome thanks
