### ISSUE TITLE
ToAU Mission 30 - Teleports after CS 

### ISSUE THREAD

**Issue by nickycupcakes** [EdenServer/community#5387]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
version:  30181205_0

During ToAU Mission 30 (https://classicffxi.fandom.com/wiki/Aht_Urhgan_Mission_30:_Prevalence_of_Pirates) on the 3rd step (zone into Arrapago Reef) I used entrance #3 as the wiki suggests.  So I entered Arrapago Reef at H-10 on Map #5 to be prepared for the next step to approach the Cutter.  However, when the cutscene completed, I was teleported to G-11 on Map #4.  

I witnessed the same thing happen to my party member.

**Comment by 59blargedy** [comment]
Resolved in November 22, 2022 mini-update.
