### ISSUE TITLE
Food Buffs Lasting too Long

### ISSUE THREAD

**Issue by Kissfork** [EdenServer/community#5388]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
version 30181205-0
![image](https://user-images.githubusercontent.com/118778568/203176468-e16d2b9d-b0d8-41a7-b683-62a34a85ed78.png)

**Comment by falzum** [comment]
What food did you eat? Do you have food duration sanction up?

**Comment by Kissfork** [comment]
I had HQ Squid Sushi with Food Duration Buff up

**Comment by Kissfork** [comment]
As a side note it's now increased to 99 hours

**Comment by KnowOne134** [comment]
problem area has been discovered

**Comment by 59blargedy** [comment]
Resolved by another dev in November 22, 2022 mini-update. Thank you for reporting
