### ISSUE TITLE
Anantaboga's Lodesong sometimes applies flee speed

### ISSUE THREAD

**Issue by Goutan** [EdenServer/community#5389]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

The weight from Anantaboga's Lodestone ability sometimes applies flee speed to the target. The buff bar still shows weight and the increased speed wears off when the debuff wears.

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
