### ISSUE TITLE
Karura hachigane perp cost- not working

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5391]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

With and without head piece same -tic/mp.

False alarm on the att/def bonus working on other avatars! spaghetti fell out of pocket.

**Comment by Steam-arch** [comment]
Wiki states only supposed to work on garuda:
![image](https://user-images.githubusercontent.com/69089249/203343916-7444ab87-08a3-4e5a-b0f3-0e07ffa78669.png)

**Comment by 59blargedy** [comment]
resolved in November 27, 2022 update
