### ISSUE TITLE
Unable to get new Ephramadian Gold Coin during ToAU 34

### ISSUE THREAD

**Issue by nickycupcakes** [EdenServer/community#5392]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version:  30181205_0

During ToAU Mission 34 (https://classicffxi.fandom.com/wiki/Aht_Urhgan_Mission_34:_Testing_the_Waters) when I click Jazaraat's Headstone I only get the message "The name Sir Jazaarat is engraved on the headstone..." instead of getting a new Ephramadian Gold Coin.

I have tried to skip that step and visit the Cutter, however the cutscene there just tells me that I need the coin.  (Returning to the headstone after that CS gives the same result)

Screenshot of message, along with proof of Mission 34 being active:
https://ibb.co/fXCkCk1

Edited to add - I have double and triple checked that I do not have the Coin KI already, as did another player I was partied with at the time.

**Comment by KnowOne134** [comment]
while we fix this make a GM in game ticket so that someone can give you a coin please

**Comment by KnowOne134** [comment]
Has been corrected
