### ISSUE TITLE
mountain clot taking poison damage from claret

### ISSUE THREAD

**Issue by somedudestolemyname** [EdenServer/community#5394]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

attempted solo Claret with bst and the Mountain clot i charmed was taking poison damage 
was going off if this info

![test](https://user-images.githubusercontent.com/97771638/203437812-88213f34-f45c-4dc6-8965-77d5af70fb07.png)

https://ffxiclopedia.fandom.com/wiki/Talk:Claret#Testimonials

charm a nearby clot and send it after claret. can see that it is taking damage over time

**Comment by 59blargedy** [comment]
Just went to check this one out on retail. doesn't seem to be true, sadly. Mountain clot was going down by 2% hpp a tic. if that incorrect note is on eden wiki we should remove it.
