### ISSUE TITLE
Fighting Chamrosh appears to crash the zone

### ISSUE THREAD

**Issue by boggartff11** [EdenServer/community#5395]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x
![chamrosh_crash](https://user-images.githubusercontent.com/118860824/203440953-fd7f4ff4-b8b8-45a4-8db5-64e6a12c80d0.PNG)
] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

Popped Chamrosh, got to 55% and the zone crashed, no indication of what happened.  Lost the pop item.

**Comment by 59blargedy** [comment]
there's nothing triggered at 55%, so this could be completely unrelated to chamrosh with the same amount of probability as it being related.
what actions were people taking at time of crash beyond those in the logs? any more information to help determine?

**Comment by boggartff11** [comment]
We just tried out a second pop and no crash, so could be unrelated.  Was only pet actions and RA occurring.  Blood Pact Rage from SMN, Ready from BST, RA from THF.  We also saw it use Wisecrack this time without any issues.

**Comment by 59blargedy** [comment]
we've identified the issue and it's stemming from something else in another zone, but will be resolved asap. reporting helped us track down,even if it wasnt chamrosh, so thank you
