### ISSUE TITLE
Mission 1-2 Tomb Cutscene does not play upon examining the tomb

### ISSUE THREAD

**Issue by RaxenLight** [EdenServer/community#5396]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Ver 30181205_0
After acception San d'Orian Mission 1-2 and venturing to King Ranperre's Tomb, clicking the tomb shows the game message of a waterskin being there, but no cutscene plays.  Returning to the city with the required Orchish Mail Scales the mission does not complete.

**Comment by KnowOne134** [comment]
Corrected 11/23/22
