### ISSUE TITLE
You can open halvung levers solo/duo without KI

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5397]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Seems like you can cancel the:
![image](https://user-images.githubusercontent.com/69089249/203582610-02e4746e-b519-4cf3-8375-f24d736b3db4.png)
text and click on the lever again and stack "people", got past the first gate but couldnt open the 2nd gate with the same strategy with its correct lever, but worked again using the lever past the door by using fillmode, propably shouldnt be able to press the lever past the door either. Might have to alternate between the cancels and presses with 2 chars for it to work not sure.

![image](https://user-images.githubusercontent.com/69089249/203582527-3f89fac3-a93b-43b3-87b8-117feec1acde.png)
![image](https://user-images.githubusercontent.com/69089249/203582886-a8f79b25-f524-404d-9f07-7de4f7b7183e.png)

Not entirely sure if how it works on retail but propably shouldnt be cancellable?

**Comment by Steam-arch** [comment]
Note: I think the lever at the marked position is glitched regardless, was unable to open it with 5 people pressing at the same time and getting the succes-text. Had to open with the other switch with fillmode through the door.

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
