### ISSUE TITLE
Since 11.21.22 Patch: Reward now generates hate to the Beastmaster

### ISSUE THREAD

**Issue by Mu-cky** [EdenServer/community#5398]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
As of 11.21.22 Patch, noticed Reward was pulling hate for the first time. Client version: 30181205.0
All these results are post patch. I've only tested this at 75 so far, with jug pets, with about 1200 Zeta rewards. Reward pulls hate to the BST.

**Steps**
With job set to Beastmaster at level 75, with Currier Carrie & Pet Food Zeta available
1. Fight a mob or group of mobs with your pet
2. Use Ready moves as desired or single target or multiple target attacks
3. Use Reward
4. Observe hate generation on the player/Beastmaster

**Tests**
Tested on groups of 10 Gigas in Xarcabard while farming for Hickory Lumber. Reward pulled hate to the BST every time from every Gigas in the group, even when Carrie had put in 1000+ damage with Bubble Shower Spam.

Tested on Gration. Reward pulled hate to the BST every time from Homunculus and from Carrie. Even after damage from Carrie was laid down and multiple Readys used.

Tested on level 64-66 Testiomony dropping demons in Castle Zvahl Bailies. Reward pulled hate off Carrie to the BST every use. 

Tested on level 59-62 Over/Vault Weapons in Garliage Citadel. Reward pulled hate off Carrie to the BST from singles and multiple mobs every use.

Reward generates enough enmity to the BST that it pulls hate even if my pet has laid down 2000+ damage on the mob. When fighting alongside the jug pet, using Ready then Snarl the mob typically gets 1-2 hits in on the Beastmaster before Snarl goes off.

Still need to test with charmed pets where Snarl is not an option.

**Proof this isn't era:**
Checked era wiki on Reward ability, which states, "Usage of this ability will restore some of user's pet's HP and will generate enmity toward the pet." See link to wiki here: https://classicffxi.fandom.com/wiki/Reward

**Screenshot**
The following screenshot shows Carrie hitting the Arch Demon for a total of 603 damage. Mucky hitting the Arch Demon for a total of 298 damage. A Reward for 1119 HP and the Arch Demon Turning to Mucky and hitting him, before Snarl goes off. This illustrates that significant hate is now generated by Reward.
![Reward Generates BST Hate](https://user-images.githubusercontent.com/94568270/203634352-48cc52fd-d6da-4ed6-9bb6-74a611918432.png)

**Comment by 59blargedy** [comment]
resolved by another dev in November 27, 2022 update
