### ISSUE TITLE
Ul'xzomit have invincibility and unusually high attack

### ISSUE THREAD

**Issue by Azmatic1** [EdenServer/community#5399]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I was doing some organ farming and noticed one of the Ul'xzomits was not taking any damage and  having very high attack values. I had a GM confirm there was a issue and I could identify the bugged mob as they checked high evasion/defense  as a decent challenge. Its seems to be in every trio of Ul'xzomits that follow each other, there is one with this invincibility bug. 
client version 30181205_0

Here's a normal battle against a Ul'xzomit
![Inny_2022 11 23_205835](https://user-images.githubusercontent.com/99223333/203677567-ef562d2d-f4ed-410e-a9af-6beea4334842.png)

Here's the super saiyan (Bugged) Ul'xzomit
![Inny_2022 11 23_205757](https://user-images.githubusercontent.com/99223333/203677728-12c155cb-5ba9-47af-8b24-37b98d0d6640.png)

Additional testing with a thf and pet doing no damage while taking absurdly high damage
![Daddygalka_2022 11 23_211958](https://user-images.githubusercontent.com/99223333/203680055-2e144d41-318d-464a-a018-7450032268cb.png)

Notice the bugged mob of trio checks high evasion/defense despite being a lower level
![Screenshot 2022-11-23 210702](https://user-images.githubusercontent.com/99223333/203679256-fc9e69e1-6058-4301-86a1-ceba51b59430.png)

**Comment by Mozzy4Ever** [comment]
From what I've seen: The stats of the bugged ones are doubled (or close to it) from what they should be, and it's only the xzomits that are pets of a parent. Regular Xzomits by themselves are fine, but 1 pet out of the trio will be doubled.

**Comment by statuseffect** [comment]
Adding to this report on some behavioral issues with the "baby" xzomits.

- Pulling the mother and linking the babies gets the babies "stuck".

How to recreate: Pull mother with ranged(THF), Sleep mother(BLM), Flee or run the babies out of range of their roaming area.
Babies will get stuck and keep their aggression animation, upon death of the mother, they will return to passive.

- Killed babies and mother will not respawn if the entire "family" is not defeated.

How to recreate: Use the above strategy to kill the mother and the non-bugged baby xzomit and wait 5 minutes for respawn. 
(I have waited upwards of 15 minutes and no respawn as the bugged baby xzomit is still stuck where i flee'd it.)

**Comment by statuseffect** [comment]
UPDATE: The stuck baby eventually de-spawned allowing the family to respawn in an indeterminate amount of time. Will test.

**Comment by statuseffect** [comment]
Updated upon further study.

**Comment by statuseffect** [comment]
Mother can also get stuck if pulled too far from roaming area.

**Comment by 59blargedy** [comment]
resolved by another dev in february 20, 2023 update
