### ISSUE TITLE
Tabar Beaks in Sauromugue Champaign don't drop loot.

### ISSUE THREAD

**Issue by Anonyy89** [EdenServer/community#540]
Decided to farm them a bit today. Killed a few and didn't get any drops. Thought I was just unlucky. Killed about 10-15 more and still not a single drop of any item. All of this with TH2.

**Comment by Kurtalicious** [comment]
2/19/19 - Thought this was patched?  Killed at least 15 of these things and only 1 of them dropped an earth crystal and beastmen seal.  No other loot is dropping and I have TH2.

**Comment by godmode** [comment]
I will check it out tonight when I get back to my computer. Thanks for reporting

**Comment by Kurtalicious** [comment]
Was this resolved?

**Comment by Redenius** [comment]
Seems the steal table is missing off the Tabar Beak. You are supposed to be able to steal Giant Bird Feathers and I have failed over 10 times.
