### ISSUE TITLE
Ob not dropping correct gil quantity

### ISSUE THREAD

**Issue by PyreOgion** [EdenServer/community#5400]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

A party of 5 fought Ob twice. Dropped roughly 70 gil total. Wiki and videos from era and after state it should be around or at 3k.
version 30181205_0

![image](https://user-images.githubusercontent.com/32087703/203679902-106c35bf-9859-419b-864a-799db4390a23.png)
![image](https://user-images.githubusercontent.com/32087703/203679932-fc7acc0b-fb57-458f-8c9c-221241a4f6a9.png)

ERA: https://youtu.be/xLLMGfIQBY4?t=281
2012: https://youtu.be/8Twbxfwg66E?t=60

**Comment by PyreOgion** [comment]
Yes, we switched it to the Sharpshot frame.

**Comment by 59blargedy** [comment]
resolved in November 27, 2022 update
