### ISSUE TITLE
Elel Spawn Conditions Not Proper

### ISSUE THREAD

**Issue by Camuel666** [EdenServer/community#5402]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Elel NM in Sacarium does not spawn properly according to wiki claims
currently it spawns every night regardless of kill prior
according to wiki it is only to spawn when weather in sacarium is dark weather and at night and should have a 2 hour respawn after death
also if it were to despawn with out death it would then skip the next night with dark weather and then spawn on the night after with dark weather
here is a link to the wiki page https://ffxiclopedia.fandom.com/wiki/Elel
and another page stating its spawn conditions https://ffxi.allakhazam.com/db/bestiary.html?fmob=3523
retail testing may be needed to confirm this behavior
version 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 27, 2022 update
