### ISSUE TITLE
Khromasoul Bhurborlor spawns in incorrect location & travels to pop location through the floor/walls

### ISSUE THREAD

**Issue by setsuk0** [EdenServer/community#5403]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

T3 ZNM Khromasoul Bhurborlor and his adds in Mount Z spawn near the G-7 zone. Then it travels through the void where players cannot walk until it reaches the actual ??? where the pop item was traded. Retail videos show that the troll and his adds should spawn at the ???. We popped him multiple times, and this occurred each time. 

https://youtu.be/LyFfkhX4AnA

To reproduce, spawn Khromasoul and note where he spawns.

**Comment by 59blargedy** [comment]
resolved in November 27, 2022 update
