### ISSUE TITLE
Dea Using Firespit

### ISSUE THREAD

**Issue by Deirdre5017** [EdenServer/community#5404]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Did x2 Dea pops and both times it used Firespit which is a Mamool Ja specific special move.

Dea - 
"Has all the normal Wivre TP moves, plus:
[Crippling Slam] - AoE physical damage plus very strong [paralyze]. Stunnable, absorbed by Utsusemi."
https://ffxiclopedia.fandom.com/wiki/Dea?oldid=668803

Firespit - 
"Mamool Ja Special Moves
Firespit: Single-target fire damage, absorbed by 3 Utsusemi shadows."
https://ffxiclopedia.fandom.com/wiki/Category:Mamool_Ja?oldid=682126

![image](https://user-images.githubusercontent.com/73006091/204069218-b1ad39e5-9e34-4886-a460-8ec0438e1a6a.png)

Version - 30181205_0

**Comment by 59blargedy** [comment]
resolved in November 27, 2022 update
