### ISSUE TITLE
Soultrappers able to be used without a cooldown. 

### ISSUE THREAD

**Issue by Frozzen907** [EdenServer/community#5405]
### Checklist

- [√] I have searched for existing issues for issues like this one. The issue has not been posted.
- [√] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [√] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Ver: 30181205_0

Soultrappers are able to be used repeatedly without waiting for cooldown timer, believe it has something to do with Windower & Gearswap. 

How to Reporduce: 
1.) Have Gearswap addon loaded & a Gearswap LUA loaded (even a blank one works)
2.) Make two Equipsets, One with Soultrapper 2000 & Plates, The other with Soultrapper & Plates.
3.) Make Macros as such: 
Macro1:   Line1:  /Equipset#       Line2:   /item "Soultrapper 2000" <t>  
Macro2:   Line1:  /Equipset#       Line2:   /item "Soultrapper" <t> 
4.) Go Start taking pictures. After the first regular use press macro to swap to other trapper and it will use it instantly. Swapping between the two allows for use without waiting for cooldown timers. Even if the NQ Soultrapper is empty you can swap to it then back to HQ soultrapper and use it without waiting for cooldown timer.

**Comment by 59blargedy** [comment]
resolved by another dev  in the November 27, 2022 update
