### ISSUE TITLE
Carbuncle unable to assault further mobs after being slept.

### ISSUE THREAD

**Issue by maxdecphoenix** [EdenServer/community#5407]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

noticed recently that when carbuncle has been slept by a mob (sleep, sleepga, w/e) that upon killing said mob, you can't assault Carbuncle on another mob. He must be released and resummoned.  I've been noticing this with high regularity since most recent patch. 

In a specific case at the entrance to LoO, i attacked the mage gob and the other two linked.  The mage gob cast sleepga, which hit carbuncle.  Upon killing the mage gob, carbuncle returned to my side, but couldn't be assaulted on the other gobs.

**Comment by falzum** [comment]
It's probably because carbuncle hadn't woken up yet. Carby shouldn't move while slept which is probably the actual bug you encountered and you thought he was awake.

**Comment by maxdecphoenix** [comment]
I considered that as a possibility.  Since noticed it on garuda as well killing imps.  imp threw out a death-throw sleepga, which landed log stated garuda was asleep, imp died, garuda returned.  Reviewed the log looking for bio/poison or some other dot but didn't notice it.

**Comment by KnowOne134** [comment]
closing due to another issue already open for same thing, found here https://github.com/EdenServer/community/issues/3552
