### ISSUE TITLE
Ifrit's Crimson Howl's attack increase is much too small

### ISSUE THREAD

**Issue by Isabel-Eden** [EdenServer/community#5408]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

As a lvl 55 summoner, using Ifrit's Crimson Howl increased my primary attack (as reported by `/checkparam <me>`) from 172 to 173 - about 1%, while the [classic wiki](https://classicffxi.fandom.com/wiki/Crimson_Howl) claims 15%, and [ffxiclopedia](https://ffxiclopedia.fandom.com/wiki/Crimson_Howl) 8%.

It would be good to check whether the bonus should apply to ranged attack as well. Unfortunately I do not have access to retail FFXI, so I cannot check myself.

Client version:  30181205_0

**Comment by madmikeblvd** [comment]
![crimson roar](https://user-images.githubusercontent.com/71995009/204146091-fea57ef5-d41a-4466-a147-ee880925b7c3.PNG)

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
