### ISSUE TITLE
Ob Arcuballista, Armor Piercer, and Cannibal Blade shouldn't ignore shadows

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5411]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I don't think any of Ob's WS's should ignore shadows but currently Arcuballista and Armor Piercer do. Daze does not, it is absorbed by shadows.

You can see in this video (although laggy) that Arcuballista is absorbed by a shadow.

https://youtu.be/7sPfExRub7E?t=60

Can be seen in this video as well

https://youtu.be/YB1fuNH2JRc?t=323

Currently it goes through shadows

![image](https://user-images.githubusercontent.com/13668758/204412295-34890fca-09ba-40e7-8a3a-e7e1d1734b09.png)

Armor Piercer can be seen absorbed by shadows in this era video

https://youtu.be/YB1fuNH2JRc?t=340

version 30181205_0

**Comment by E5una** [comment]
I believe cannibal blade is also going through shadows at the moment. This video shows that it shouldn’t (around 11 minutes)

https://m.youtube.com/watch?v=12nNGdEicUE

**Comment by 59blargedy** [comment]
Resolved in February 20, 2023 update
