### ISSUE TITLE
ToAU 44 - Nashmeira's Plea:  Nether Blast counts as physical damage.

### ISSUE THREAD

**Issue by AzrielltheWise** [EdenServer/community#5413]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

During ToAU Mission 44, the start of the fight is broken down into multiple phases.  During the first two phases, primarily dealing magic damage will cause Raubahn to be immune to magic damage in the third phase; dealing primarily physical damage will cause him to be immune to physical damage in the third phase. 

My group used Nether Blast + Lullaby to kill Raubahn in the first and second phase.  When the third phase started, Raubahn took 0 damage from Predator Claws as well as Nether Blast (proving that Nether Blast was counting for physical damage).  Garuda's Aero IV still did normal damage.  Also, Diabolos's Dream Shroud (magic attack bonus buff) increased the damage of Nether Blast, so it appears to still be doing magical damage, it's just being tallied as physical.

https://classicffxi.fandom.com/wiki/Aht_Urhgan_Mission_44:_Nashmeira%27s_Plea

**Comment by 59blargedy** [comment]
Resolved in February 20, 2023 update
