### ISSUE TITLE
ODS bug

### ISSUE THREAD

**Issue by frynearn** [EdenServer/community#5414]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by frynearn** [comment]
When completing ODS the chest isnt  appearing GM tested it and seems to be bugged only one that isnt working properly.

**Comment by 59blargedy** [comment]
this is fixed as of November 29, 2022. thanks for reporting
