### ISSUE TITLE
ZNM - Nosferatu - Decollation

### ISSUE THREAD

**Issue by Elysien** [EdenServer/community#5417]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Nosferatu's ability "Decollation" does not actually deal damage to players, despite showing damage in the log. Didn't bother with a screenshot as a still image doesn't really show much, but repro should be very easy.

1) Spawn Nosferatu
2) Feed it TP, allow it to use Decollation, and let it connect
3) Observe damage is displayed in the log, but player HP isn't reduced.

Damage of the actual attack also appears to be weak, per what the log displays. This ability is the Vampyr families strongest ability if it fully connects (works as a 3-hit ability, requires 3 shadows to fully absorb, 2 or less will reduce the damage). From what I observed in the log, with no shadows and no PDT, a player took 450~, I would expect 800-900 at least in this case.

**Comment by Elysien** [comment]
![Screenshot_20221203-161157_Samsung Internet](https://user-images.githubusercontent.com/44657197/205450524-b5edeacf-ccf4-4a33-8942-e8b17fc70456.jpg)

Crude screenshot of Decollation, to a beastmasters pet. I believe that is a local Funguar enemy, and that Decollation would have been a connect; damage is very similar to what I'd expect players to take if hit clean, without stacking defense/-pdt, shield blocking

**Comment by 59blargedy** [comment]
Resolved in February 20, 2023 update
