### ISSUE TITLE
Khimaira Stun Resistance audit

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#5418]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Today during Khimaira, he resisted stuns both times. They were the only stuns cast during the fight.
![image](https://user-images.githubusercontent.com/46233090/205803043-d8cfc2e3-adba-4aa6-ad25-1dbc12c6937e.png)
![image](https://user-images.githubusercontent.com/46233090/205803257-fa589b66-ec93-4758-96d0-ff12435aa579.png)

I'm only asking for an audit, because he spawns so infrequently it might be something that we cannot test on the live server.  According to LS members, the previous Khimaira (a few days ago) did not have these issues with stun.  After reviewing chat logs, Stun was not used by any member in the group prior to 35%.  I'm curious if it is linked to the November 21st, 2022 update or if there were backend things done to "TYGER" that effected Khimaira.  (■ Removed bonus Khimaira's resistance to enfeebling effects in lieu of correct SDT resistance values, and added in his spawn animation. )

![image](https://user-images.githubusercontent.com/46233090/205804215-847724ec-db98-4ca6-9a92-e60a63ec84a4.png)

**Comment by 59blargedy** [comment]
Are these blms casting stun or something with low dark skill

**Comment by StriderClerix** [comment]
Nah both are fully skilled up. 

Nashira body, af1 legs, af2 hands, Jupiter etc.

**Comment by Steam-arch** [comment]
Does seem too high yeah

Could land 0 with this
![image](https://user-images.githubusercontent.com/69089249/206007467-149f3972-f28b-4443-b4df-ec8108f2ee9e.png)

![image](https://user-images.githubusercontent.com/69089249/206003989-95ad40b0-d9b8-45d5-bca9-7bfc806adc4b.png)
![image](https://user-images.githubusercontent.com/69089249/206003930-ebd5b4a3-6474-4fbd-87ac-a4a1485af62b.png)

------------

Could land 2 with this
![image](https://user-images.githubusercontent.com/69089249/206004579-46c15bbd-4240-4a8c-b2f4-b7369d89fcdf.png)
![image](https://user-images.githubusercontent.com/69089249/206004612-23b5be37-54cb-4a92-bf8b-186ea077a2f0.png)
![image](https://user-images.githubusercontent.com/69089249/206004754-1249972d-6f5b-427d-954e-5feb88d629cf.png)

----------
Could land 0-2 with this
![image](https://user-images.githubusercontent.com/69089249/206005323-e46ad593-c362-4dba-adbb-b5e8f77bbced.png)
![image](https://user-images.githubusercontent.com/69089249/206005360-15122c13-11ef-4aa5-b333-7de788c151cd.png)
![image](https://user-images.githubusercontent.com/69089249/206005537-7355bdfe-49ef-408a-85fe-01461bb503f9.png)

Popped it again and resisted from the start
![image](https://user-images.githubusercontent.com/69089249/206005839-caa3d04e-92ad-48af-9fea-f5cbcb1f6ac1.png)

3rd khim
![image](https://user-images.githubusercontent.com/69089249/206006100-4f5076c8-812b-42ba-90f2-612bbec0d2e0.png)

Could get abit more stats still but even with the first build should have a good chance of landing.

**Comment by ccl085** [comment]
Could it be that now it is accurate and we do need the stun "hidden macc  bonus" to actually be able to land stun on mob such as Khim ?

**Comment by 59blargedy** [comment]
that's there already, will need to look and see what is going on. not worried about the multiple casts but the first couple of stuns, or stuns spaced well apart, should def be able to get through.

**Comment by ccl085** [comment]
good to know, I couldn't see it on patch note with the macc bonus to tier 2-4

**Comment by 59blargedy** [comment]
nothing changed, the bonus has existed forever

**Comment by ccl085** [comment]
Oh I believe "proof" of +200 macc bonus only recently got found out, wich make wonder even more why I cannot stun qufim island crab as drk 67 while skilling up dark magic (20)

**Comment by StriderClerix** [comment]
So are we operating on the assumption that Khimaira is working as intended? 

So can I close the ticket or does it need more data?

**Comment by 59blargedy** [comment]
we will close this out when the related fix resolves this one indirectly. (the stun res value is from validated sources so it's not that but no, it shouldnt be this hard to stun)

**Comment by 59blargedy** [comment]
this should feel better but leaving the ticket open for feedback

**Comment by 59blargedy** [comment]
resolved in previous update, probably need to increase the res a bit more
