### ISSUE TITLE
Lil' Apkallu shouldn't Flee during Hundred Fists

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5419]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Currently on Eden, Lil' Apkallu's Flee speed doesn't decrease until all of his TP/2h usage is done post-tappy runs.

https://ffxiclopedia.fandom.com/wiki/Lil'_Apkallu?so=search mentions "Lil' Apkallu can easily be kited while Hundred Fists is being used."

https://youtu.be/OGCQ7jqdjeE?t=209 is a video showing Apkallu using Hundred Fist and not having increased movement speed during.

**Comment by 59blargedy** [comment]
Resolved in February 20, 2023 update
