### ISSUE TITLE
Soul Eater Damage not Calculating

### ISSUE THREAD

**Issue by KOS-elos** [EdenServer/community#5420]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The damage with WS Damage with SE vs Non-SE are relatively the same amount of damage, but still are losing the HP from SE. 

(Without SE)
![Non-SE1](https://user-images.githubusercontent.com/112454780/206018790-0d66fddc-9057-41d7-b073-61914e576914.png)

![Non-SE2](https://user-images.githubusercontent.com/112454780/206018908-cdc56713-6352-4242-803b-f93dad5a3b61.png)

(With SE)
![With SE1](https://user-images.githubusercontent.com/112454780/206019133-982b960c-dfdb-492b-ba1b-ae78aec92da5.png)

![With SE2](https://user-images.githubusercontent.com/112454780/206019220-bcd8f3e8-cea8-4bc7-b818-91af150f836e.png)

Seems to effect all WS 

White Damage seems fine and still does the proper amount of damage.
![White Damage](https://user-images.githubusercontent.com/112454780/206019536-0c416901-3584-4350-83a1-142b2066f609.png)

**Comment by 59blargedy** [comment]
Resolved live December 7, 2022
