### ISSUE TITLE
Ix'Aern MNK and DRK adds sleepability

### ISSUE THREAD

**Issue by TracentEden** [EdenServer/community#5421]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
The Ix'Aern MNK and DRK adds called Qn'aern potentially should not be dark sleepable. See this [retail capture](https://youtu.be/7YtDok1lhvo?t=48) and this [retail capture](https://youtu.be/j7k9HsChq4c?t=150) which shows that all the pets completely resist sleepga (which is not the case on Eden currently). I am not sure of their light sleepability.

I also could not find any SE patch note mention of these mobs changing. Though maybe I am missing some era proof of their sleepability.

**Comment by 59blargedy** [comment]
Resolved in February 20, 2023 update
