### ISSUE TITLE
Turning in cursed item/abj for item I already had made me lose abj and cursed item

### ISSUE THREAD

**Issue by LeaflyXI** [EdenServer/community#5422]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details 
Turned in cursed mufflers and e hands abj to the npc to uncurse. went through all text and animation as if it was uncursing. did animation on myself, got text prompt saying i couldnt hold more than 1 of said item. continued on without realizing items had been lost but they had been so dont have picture proof. looked a few places and have not read anything about this happening. dont have any duplicate abj right now to try to recreate.

version 30181205_0

**Comment by 59blargedy** [comment]
Resolved in February 20, 2023 update
