### ISSUE TITLE
Desynthesis recipe of Wool Doublet missing

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5423]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

This recipe was known about as early as March 2007 according to the [wiki](https://ffxiclopedia.fandom.com/wiki/Wool_Doublet?oldid=209911).  The current retail entry includes the result for HQ2 which is missing from earlier edits of the page.

**Comment by 59blargedy** [comment]
Resolved in February 20, 2023 update
