### ISSUE TITLE
Quick Draw does not grant skill ups

### ISSUE THREAD

**Issue by PfistoFFXI** [EdenServer/community#5424]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Version 30181205_0
Quick Draw should grant skill ups to Marksmanship, it does not.

Validated issue on Test, set marksmanship to 0 and shot about half a case of fire shots at a Sea Puk, no skill ups attained.

Link to where it says skillups should be attained: https://ffxiclopedia.fandom.com/wiki/Quick_Draw

Hopefully similar to jump fix ^^

**Comment by Mozzy4Ever** [comment]
http://wiki.ffo.jp/html/3349.html

Gaining skillups (and TP) from Quick Draw was added September 9th, 2010. It's OOE
