### ISSUE TITLE
Can charm a mob that has "Call for help" status

### ISSUE THREAD

**Issue by Smalfio** [EdenServer/community#5425]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window) 
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Not supposed to be able to charm Mobs with Call for help status.
I engaged a mob cfp and have my alt charm it and it can fight as per usual
v 30181205_0

![Alfio_2022 12 07_135821](https://user-images.githubusercontent.com/118784488/206306855-a30b7c70-356a-4eed-9bd5-6b5da0948650.png)
this wiki page from 2008 says you aren't supposed to be able to
https://ffxiclopedia.fandom.com/wiki/Charm?direction=prev&oldid=773608

**Comment by KnowOne134** [comment]
Resolved in February 20, 2023 update
