### ISSUE TITLE
ZNM Gotoh Zha Redolent Firespit damage hits too weak

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5427]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Unresisted does a static 560ish on war/nin with Shell IV
![image](https://user-images.githubusercontent.com/69089249/206484377-e56caf31-24e4-43e2-b776-412b9879e075.png)
![image](https://user-images.githubusercontent.com/69089249/206484426-0a69e3c9-1682-4194-98d4-0af01a7903e9.png)

![image](https://user-images.githubusercontent.com/69089249/206485182-0a3c07b7-1e25-463b-a38b-eb42c61ecd37.png)

Some era numbers:
![image](https://user-images.githubusercontent.com/69089249/206485377-8edcd79d-a383-4cd7-ac4c-dec18f8ca58a.png)
https://www.youtube.com/watch?v=HjjRv417yjI
4:31 ~900 firespit

https://www.youtube.com/watch?v=HjjRv417yjI
5:33
~900 Firespit

--------------------------------------------

Also Groundburst is easily outrunnable if you start running on warm-up, is this intended?

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
