### ISSUE TITLE
Nobushi Kyahan - "Store TP"+4 not applied

### ISSUE THREAD

**Issue by ArsinoeX** [EdenServer/community#5428]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

**Client Version**: 30181205_0

**_Nobushi Kyahan - "Store TP"+4 stat is not being applied on hit._**
_Accuracy & Rice ball stats are working as intended._

_**Feet On:**_
![NobushiKyahanOn](https://user-images.githubusercontent.com/58524966/206553843-5c1342e2-ccf7-4c9b-8a12-e8a6293f114c.png)

_**Feet Off:**_
![NobushiKyahanOff](https://user-images.githubusercontent.com/58524966/206553856-0dc93920-21d8-4bc7-ab67-1916b0b1a0e0.png)

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
