### ISSUE TITLE
Goblin Archaeologist Doesn't Exist

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5429]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Short summary: There should be 3 ???s that appear between in each main crag zone between the telepoint and the shattered telepoint where you can trade items once per day to bring a goblin NM closer to the surface. He can drop a variety of things but always drops a specific random amount of gold beastcoins.

Sorry, this is more to have a record that this doesn't exist, I can't find all the specifics of exactly how he should work but I wanted to create something to note that Goblin Archaeologist doesn't exist at the moment on Eden. If anyone else has more information on the specifics feel free to attach links here to the documentation.

The ffxiclopedia page is a good start but with some unconfirmed information, the jpwiki page seems to have more concrete details.

https://ffxiclopedia.fandom.com/wiki/Goblin_Archaeologist
http://wiki.ffo.jp/html/11426.html

version 30181205_0

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
