### ISSUE TITLE
Raptors outside uleguerand seem to be missing Thunderbolt tp move

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5433]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Raptors outside of uleguerand raptors seem to be missing Thunderbolt
![image](https://user-images.githubusercontent.com/69089249/207171657-7e4bb6aa-4f56-413d-83ab-5e83a9840578.png)

![image](https://user-images.githubusercontent.com/69089249/207170447-a61dba69-0322-4e77-b5f4-1b7cf6cbd8d1.png)

![image](https://user-images.githubusercontent.com/69089249/207170402-cf7b0834-64b4-4708-8bb3-aa5be14ec0d4.png)

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
