### ISSUE TITLE
COP mission: desires of Emptiness, Missing words in cutscene

### ISSUE THREAD

**Issue by Tavnazian** [EdenServer/community#5436]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
In the final cutscene of the mission "desires of Emptiness", the  KI colored words "mysterious amulet" are missing twice. 
screenshot of my dialogue box showing the error is attached.
![error](https://user-images.githubusercontent.com/86973967/207511653-fa9b3cc6-44e9-4f28-8ae8-ddfecb5d549e.jpg)
 
and clip of the intact cutscene can be found at https://www.youtube.com/watch?v=3teLKLOFRdQ&t=627s

version 30181205_0

**Comment by KnowOne134** [comment]
corrected in the 11/19/2023 update
