### ISSUE TITLE
Say It with Flowers will not complete

### ISSUE THREAD

**Issue by Kaijikunito** [EdenServer/community#5437]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I was playing on character Nekolai with version 30181205_0 on December 12th. I had answereOhbiru-Dohbiru's questions correctly (rarest, mysticalest, elegantest). At 00:31 CST I received the Tahrongi cactus which is not showing my key items. Moari-Kaaori will not complete the quest and will instead repeat "The rarest, mysticalest, elegantest flower there is! What a blooming good idea! Now that it's arranged, I've got to do all the preparations that stem from it!".
![tahrongi1](https://user-images.githubusercontent.com/109045612/207531486-4e3c4383-7b6b-4f46-83da-4dca0b5f2efb.png)
![tahrongi2](https://user-images.githubusercontent.com/109045612/207531524-48ab04d9-7003-4c83-8d21-dd343cb343b4.png)

**Comment by Kaijikunito** [comment]
I thought this was a key item, not an item in my inventory. The issue was between my chair and my computer.

**Comment by KnowOne134** [comment]
Well thank you for closing when finding out the issue -> person in 💺
