### ISSUE TITLE
Claim name colour issue

### ISSUE THREAD

**Issue by Nyoomy** [EdenServer/community#544]
![image](https://user-images.githubusercontent.com/45608627/50299520-ac502c00-0479-11e9-9918-cae92a77e07a.png)
![image](https://user-images.githubusercontent.com/45608627/50299599-ea4d5000-0479-11e9-968e-250ce7ad91ff.png)

Main character only sees mob names as yellow (unclaimed) or red (claimed by both my party or outside party).

I've had this bug over on Nasomi and since I started playing here, but I made an alt character to test something else and found that it's working properly for the alt.

**Comment by coins4clothes** [comment]
@GitCash send .005 bch to @Nyoomy

**Comment by GitCash** [comment]
Hey **Nyoomy**, user **coins4clothes** tipped you **5000 bits** in Bitcoin Cash ( ~ **$0.985** ).

*[Click here to claim it!](https://gitcash.io/claim/Nyoomy)*

You can also add the "thumbs down" reaction to **coins4clothes**'s comment above to prevent future tips.

**Comment by KnowOne134** [comment]
all new claiming code installed now, open a new issue with details if reoccurs
