### ISSUE TITLE
Scouting The Ashu Taliff : mobs move when they pop

### ISSUE THREAD

**Issue by pimpchan** [EdenServer/community#5440]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I stopped doing this quest in May. I started again today and I'm surprised noone reported it. All the mobs dowstairs move right as they pop when they should not. This wasn't happening before. It makes the win harder (one more bug ontop of the other bugs that still occur : COR mobs not moving, COR freezing occasionnaly on stairs).

Also the ??? dagger drop rate is around 50% so this might be a bug too, as it reduces the chance of getting attachements.

**Comment by 59blargedy** [comment]
resolved in march 5, 2023 update

**Comment by falzum** [comment]
Did this today and the Ashu Talif Crew mobs and the NM Swiftwing Gekko seem to be working perfectly, but the Watch Imps are still roaming on spawn

**Comment by 59blargedy** [comment]
Ahh forgot to fix those thanks

**Comment by KnowOne134** [comment]
Was resolved by another dev in 5/3/2023 update
