### ISSUE TITLE
Hydra using Nerve Gas with only 1 head.

### ISSUE THREAD

**Issue by DeliriumOnEden** [EdenServer/community#5442]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Issue:
Hydra is using the TP move Nerve Gas when its left and right heads are destroyed.

Steps to Reproduce:
Engage Hydra
Break Left and Right Head
Hydra uses Nerve Gas TP move

Game Version:
30181205_0

"Proof":
Per eden wiki it should not use it when its right head is destroyed.
https://classicffxi.fandom.com/wiki/Hydra_(NM)
![image](https://user-images.githubusercontent.com/62824162/209450527-a2d3c40d-9618-4f94-be21-76f68860dd35.png)

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
