### ISSUE TITLE
Sha'ir Seraweels subcraft level incorrect

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5444]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver 30181205_0

Currently on Eden the Leathercraft requirement for Sha'ir Seraweels is set to 56:
![image](https://user-images.githubusercontent.com/95725249/209987886-09b03378-f6a3-4d5b-ab20-cc29b766daaa.png)

JP Wiki is the only source I could find with a craft level set for Leather and it is 51:
https://www.bg-wiki.com/ffxi/Sha%27ir_Seraweels

I did some testing on Asura to confirm:
https://www.youtube.com/watch?v=HumsauHxcts

As far as I know, you need to be within 27 levels to attempt the synth. Failed the Seraweels synth at 66 CC and 24 Leather.

Sha'ir Seraweels should therefore be 93 Cloth and 51 Leather.

**Comment by 59blargedy** [comment]
thanks for the retail testing

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
