### ISSUE TITLE
"Shades of Vengence" mission, can't get new KI after fail

### ISSUE THREAD

**Issue by PetiteBichette** [EdenServer/community#5445]
Im currently unable to obtain the Key Item for the ToAU mission "Shades of Vengence"'s assault portion entry after failing the mission. NPC talks about my badge and does nothing else. Issue is on both Petite and Petitaru, the two characters that ran the mission.

Started ToAU mission Shades of Vengence. Both members of the Assault portion died and had to home point. Key item was removed at some point entering and failing the mission. Wiki suggest to speak with the immortal in the staging point for any following Key items to re-enter. This was the first fail. Immortal only addresses topic about mercenary badges: "Your mercenary badge flashes. 'I too was once a mercenary' ". Spoke to the immortal on a different day, tried zoning, tried running a perique assault, tried returning to the cutter, tried moving on with the mission, nothing works. 

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by falzum** [comment]
https://ffxiclopedia.fandom.com/wiki/Aht_Urhgan_Mission_31:_Shades_of_Vengeance?oldid=821017

Wiki says first retry should be instant, with subsequent retrys needing an in game day wait

**Comment by KnowOne134** [comment]
Resolved in February 20, 2023 update
