### ISSUE TITLE
NMs despawn too early

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5446]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

NMs should have to reach their spawn point before their despawn timer begins. The best example that comes to mind for this is Despot (definitely didn't just have it despawn on me after 2 hours of camping... nooope 😅). <https://ffxiclopedia.fandom.com/wiki/Despot?oldid=655767> says that Despot will walk to "the center and despawn within a minute". Current retail wiki further clarifies that it will walk to it's spawn point before despawning. Have seen this come up in relation to both lottery spawns and popped NMs, where despawn time is started on idle and not on finishing path to spawn point.

**Comment by falzum** [comment]
This is likely on a case by case basis. Jailer of Prudence timer starts as soon as it goes idle
