### ISSUE TITLE
Naja Roaming in Path of Darkness Mission fight

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#5447]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

in the fight inbetween stages Naja will do 1 to 2 roam ticks back to her spawn point instead of just waiting for next stage

**Comment by 59blargedy** [comment]
resolved by another dev in february 20, 2023 update
