### ISSUE TITLE
Synthesis: Wool Slops subcraft of GSM (28) is incorrect.

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5448]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
As the title suggest the subcraft for [Wool Slops](https://edenxi.com/tools/item/12858) should not be 28 Goldsmithing.  That is actually wildly inaccurate.  The [era wiki](https://ffxiclopedia.fandom.com/wiki/Wool_Slops?oldid=1760917) has it estimated around 11 goldsmithing, which would make sense as the [wool robe](https://ffxiclopedia.fandom.com/wiki/Wool_Robe) (12 GSM sub) uses scales, which require a higher crafting skill than sheets to make.

The [wool hat](https://ffxiclopedia.fandom.com/wiki/Wool_Hat) also has a sub of (8 GSM), which also uses a sheet.  The only clothcraft recipe from that set which requires a higher GSM sub is the [Wool Cuffs](https://ffxiclopedia.fandom.com/wiki/Wool_Cuffs), which require 18 GSM due to the Tourmaline used in the synth.

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
