### ISSUE TITLE
Phantom Puk not using Ill/White Wind

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5449]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Phantom Puk (Shadows of the Mind ISNM) should use both Ill Wind and White Wind according to:
https://www.youtube.com/watch?v=WhrKIZx5_2w
http://wiki.ffo.jp/html/2581.html
https://ffxiclopedia.fandom.com/wiki/Shadows_of_the_Mind
https://www.bg-wiki.com/ffxi/White_Wind

Currently, uses neither.

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
