### ISSUE TITLE
Sacrifice Torque drain is still active if you die with an Avatar summoned.

### ISSUE THREAD

**Issue by maxdecphoenix** [EdenServer/community#5450]
### Checklist

- [c ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [c ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [c ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
In dynamis windurst, mob sleepga alliance.  Equip sacrifice torque to wake up, and wake up party.  die to AOE-ga.  Pet dies.  Accept raise. die instantly because the game thinks I still have a pet out.  I have gone back and looked at attendance screenshots to verify I am only summoner there and no /smns in party, alliance or zone.   There seems to be a sequencing error in the OnDeath routine wherein the game is not properly clearing the 'HasPetOut' variable and is triggering latent as if pet was out.

This has happened on two different runs.  the first time i did some testing and verified that the torque wasn't just consuming HP even without a pet. But never put in bug report.  Just happened again tonight.

and no, no one else had a pet out.

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
