### ISSUE TITLE
Wivre Gorget Desynthesis Missing

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5451]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I think the Desynth of Wivre Gorget is missing. I tried it in game and it didn't work, and I don't see it on the website under the crafting section for Karakul Leather / Wivre Horn (the two results).

https://ffxiclopedia.fandom.com/wiki/Wivre_Gorget

Era
https://ffxiclopedia.fandom.com/wiki/Wivre_Gorget?oldid=583600

BGwiki
https://www.bg-wiki.com/ffxi/Wivre_Gorget

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
