### ISSUE TITLE
Aydeewa Diremites missing

### ISSUE THREAD

**Issue by faivruit** [EdenServer/community#5452]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The quest description for olduum ring on wiki mentions after dropping off a ledge there's a room with Aydeewa Diremite. The room is empty here.

https://ffxiclopedia.fandom.com/wiki/Olduum?oldid=627006

How to reproduce:

Enter the cave at (I-7) of Bhaflau to zone into [Aydeewa Subterrane].

    Follow the path to a room with columns, (I-8).
    Drop off a ledge North-West into a room that is missing [Aydeewa Diremites].

ver 30181205_0

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
