### ISSUE TITLE
'Evil Weapon' mobs appear to take less magic damage than should.

### ISSUE THREAD

**Issue by maxdecphoenix** [EdenServer/community#5453]
### Checklist

- [ .] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [3.1.1.9 ] I have provided my client version in the details. (type /ver into your game window)
- [ *] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

While testing Garland of Bliss, I noticed that Evil Weapons reduce magic damage to a higher degree than they should. By almost twice that of what it should be.  

While i no longer have the exact figures, back in the day I mained BLU  and was constantly testing out spells on different mobs to work out the mechanics and then proofing formula on various monsters to determine their stats.  I could use Dark Orb to show exactly how much INT a monster had for example.  While checking out weapons in sarumugue my formula didn't work if i had the 12.5 resist in MDB, but did if i used it as MDT.  Subtle difference, but they are different things.  
Again, it's not exactly proof, but I posted a comment on the wiki in 2012 describing this which can be found here. https://ffxiclopedia.fandom.com/wiki/Category_talk:Evil_Weapons

Here's also a link when the mob-family page was first updated 'MDB' reference was added to the wiki page in early 2008 https://ffxiclopedia.fandom.com/wiki/Category:Evil_Weapons?direction=next&oldid=336809 

The difference in damage report is subtle, but if you pass a damage variable of 270 to Mdif of 1/1,125 the damage report in the log would be 240.  However is you pass 270 to Mdif of 1/1 and then reduce that by 32/256 (12.5) in MDTA, the damage report would be 236.  But where the reduction is occuring becomes more apparent the more MAB you add which is how i concluded it was -MDT and not MDB.  

The evil weapons I tested on on Eden, however, appear to have -MDT of 58/256 (22.6%). Which is almost twice the reduction i tested it at on retail. And what the player base had noticed years before.

Assuming that i somehow overlooked something and it's actually MDB, that reduction would require like +30MDB leaving all factors the same. Which just seems ridiculously high.

**Comment by 59blargedy** [comment]
Resolved in February 20, 2023 update
