### ISSUE TITLE
Monsters unequipping gear does not cause your character display to update

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5454]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On Eden your character doesn't blink to change gear when a mob unequips something, which a lot of time leads to players not noticing for a while that they are stripped. This was validated on the test server without gearlock.

![image](https://user-images.githubusercontent.com/13668758/211668444-36ba29a2-bb5e-45fd-b4fa-e634426ca2c9.png)

Retail video showing the char model being updated when stripped.

https://youtu.be/kwilCnGEeFw?t=484

version 30181205_0

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
