### ISSUE TITLE
Bo'Who Warmonger (Pashhow Marshlands NM) doesn't appear to link other Quadav

### ISSUE THREAD

**Issue by ConteAlmaviva** [EdenServer/community#5455]
### Checklist

- [*] I have searched for existing issues for issues like this one. The issue has not been posted.
- [*] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [*] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version 30181205_0.  Noticed when fighting Bo'Who Warmonger earlier today that a nearby Onyx Quadav that was definitely in sound aggro range (pretty much on top of him) did not link to him.  If I get him again tomorrow I will check if the reverse is true as well (i.e. does Bo'Who Warmonger link to other Quadav, even if other Quadav don't link to him).

**Comment by 59blargedy** [comment]
Resolved in February 20, 2023 update
