### ISSUE TITLE
Tres Duendes should not resummon Duendes' Amoroso

### ISSUE THREAD

**Issue by ConteAlmaviva** [EdenServer/community#5456]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Per the retail wiki entry from September 2008 (https://ffxiclopedia.fandom.com/wiki/Tres_Duendes?oldid=662887), Tres Duendes shouldn't resummon Duendes' Amoroso once the latter is killed; I just saw it do exactly that after killing Amoroso.  (Client version 30181205_0)

![image](https://user-images.githubusercontent.com/8880996/212429112-73c883ea-b31e-4402-9951-05782d9fd34b.png)

**Comment by 59blargedy** [comment]
yeah, it's noted on another bug report, so we'll keep track of it there.
