### ISSUE TITLE
Golden-Tongued Culberry should be immune to sleep

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5457]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Golden-Tongued Culberry is still able to be slept, it's supposed to be immune

![culberrysleep](https://user-images.githubusercontent.com/54732693/212435802-678b5a9a-ea17-4f07-b188-858c57357c2f.jpg)

**Comment by 59blargedy** [comment]
what did you sleep him with on eden? he is coded as immune

**Comment by E5una** [comment]
That’s our bad, we were chatting in discord yesterday about the mob and I was saying how when my group did it 2 years ago we sleep nuked it to death and Dowzer said he thought it should be immune so he went to test it. Sounds like it was already fixed between those two events, thanks!

**Comment by dowzer** [comment]
Thanks for confirming
