### ISSUE TITLE
Plumbago (item) is out of era

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5458]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30191205_0

Killed some trolls today and one dropped a Plumbago:
![image](https://user-images.githubusercontent.com/95725249/212447565-10984ad6-f909-4461-aab7-8d5b5af968c2.png)

Plumbago was added in 2010:
https://ffxiclopedia.fandom.com/wiki/Plumbago_(Item)?action=history

Plumbago (item) is out of era and should be removed. :)

**Comment by 59blargedy** [comment]
Resolved in February 20, 2023 update
