### ISSUE TITLE
Scouting the Ashu Talif NM recovers hp

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5461]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Swiftwing Gekko is supposed to respawn with the same hp as when he disappears. Damage dealt to him sticks between appearances.

Currently sometimes he will respawn with more hp then when he last disappeared. We just knocked him down to the 20%ish range on his 3rd appearance and he resapwned with almost 50% on his 4th.

Also, if you wait to recover before pulling the NM, he will to regen in 10% hp chunks, similar to a disengaged mob, which I believe shouldn't happen.

**Comment by 59blargedy** [comment]
Resolved in February 20, 2023 update
