### ISSUE TITLE
Rapido shouldn't Counter

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5462]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Cactrot Rapido isn't supposed to counter. Regardless if Upbeat's evasion is capped, there's still a chance to be hit even when accuracy is floored.

https://www.youtube.com/watch?v=aZomjNcYyqs

**Comment by 59blargedy** [comment]
he is set to war so should not counter. we updated him maybe 1.5 years back, so not sure if this report is based on fighting previous to that time or if something is broken now, can you confirm?

**Comment by dowzer** [comment]
It looks like it was previous to that time, I can't reliably confirm on live

**Comment by 59blargedy** [comment]
all good, im gonna close it out then!
