### ISSUE TITLE
CoP 6-4 Ultima's Particle Shield has incorrect chat message

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5464]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Doing CoP 6-4 airship fight tonight and Ultima used the move Particle Shield which puts the effect of "Defense Up" on Ultima.  The message, however, says he puts the effect of defense up on the person he is currently targeting:
![image](https://user-images.githubusercontent.com/95725249/213900104-83377775-7420-4f41-b298-753becee7cb6.png)
  
Should say "Ultima gains the effect of Defense Boost." : 
![image](https://user-images.githubusercontent.com/95725249/213900171-95240217-8304-4d57-9d13-ed573ce0f8f8.png)

screenshot from this vid from 14 years ago:
https://www.youtube.com/watch?v=wEYl5OGOovc

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
