### ISSUE TITLE
Against all Odds fight issues

### ISSUE THREAD

**Issue by faivruit** [EdenServer/community#5465]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

This fight for the COR AF Hat has a couple issues. As mentioned on another ticket the side quests for other pieces are missing the JP midnight wait. In the fight, when you start you are supposed to be able to buff and rest, but the blu and war are walking around and aggro after a couple seconds, when they see you.

https://ffxiclopedia.fandom.com/wiki/Against_All_Odds?oldid=663582
"You have time to buff and rest before engaging [Yazquhl](https://ffxiclopedia.fandom.com/wiki/Yazquhl) and [Gowam](https://ffxiclopedia.fandom.com/wiki/Gowam)."

Then at least Yazquhl used their 2hr way before the mentioned 50-60%.
[Yazquhl](https://ffxiclopedia.fandom.com/wiki/Yazquhl) will use [Mighty Strikes](https://ffxiclopedia.fandom.com/wiki/Mighty_Strikes) at about 50-60% HP.
    [Gowam](https://ffxiclopedia.fandom.com/wiki/Gowam) will use [Azure Lore](https://ffxiclopedia.fandom.com/wiki/Azure_Lore) at 50% HP and begin to spam spells, but he is easily interrupted with regular hits or [Stun](https://ffxiclopedia.fandom.com/wiki/Stun).

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update (think i forgot the patch note for this, will try to add)
