### ISSUE TITLE
Kuftal Digger drops are incorrect

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5466]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Kuftal Digger (ID 17490196 for example) drop rates on Eden are incorrect. http://www.ffxidb.com/zones/174/kuftal-digger

On Eden: (Bold is what they shouldn't drop at all)
Copper Ore
Tin Ore
**Zinc Ore**
**Iron Ore**
**Mythril Ore**
**Silver Ore**
**Gold Ore**
Platinum Ore

It looks like Copper Ore should be 10%, Tin Ore should be 5%, and Platinum Ore should be 1% drops.

NOTE: It looks like Flesh Eaters in Eastern Altepa Desert also drop Iron Ore at a much higher rate than they should. http://www.ffxidb.com/zones/114/flesh-eater has them at a 1%ish drop rate. On Eden it's more like 50% with TH4

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
