### ISSUE TITLE
Something is broken in Davoi

### ISSUE THREAD

**Issue by rathorse** [EdenServer/community#5467]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
![Corvus_2023 01 23_022030](https://user-images.githubusercontent.com/54687166/213994941-acdadaf4-38de-4a0c-bfd7-7907e7e26c06.png)

hitting orcs for 0 damage

**Comment by statuseffect** [comment]
Might want more information and aess vague title. Looks like the orc blocked/guarded/parried your attack.

**Comment by rathorse** [comment]
Thank you for getting back with me. I did check the screenshot and it does
not say the orc blocked/guarded/parried any attack. If there is any
information that I can provide please let me know.

**Comment by KnowOne134** [comment]
Don't believe it prints a message? You will see the mob use a stance though

**Comment by ConteAlmaviva** [comment]
That's a MNK mob successfully guarding your attacks. Guard doesn't give a combat log message, it just reduces damage and plays a different animation than a normal attack (e.g. Mandragora will duck into the ground when they guard an attack).

**Comment by 59blargedy** [comment]
while we probably need to do an audit on guard rate, both guard and extremely low attack vs defense can result in 0 values. going to close this one out, thanks for reporting
