### ISSUE TITLE
Absorbed Utsusemi Shadow don't work

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5469]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

If you absorb Utsusemi shadows from a mob whether via Aura Steal or Voracious Trunk, the absorbed shadows will overwrite your own however they won't work. Mob will continue to deal damage as if you didn't have any shadows. This works inversely as well where if a mob absorbed your shadows, the mob will have the same bugged shadows on them that don't actually absorb any hits.

**Comment by 59blargedy** [comment]
Resolved in december 15, 2023 update
