### ISSUE TITLE
equipment change- "you move and interrupt your aim"

### ISSUE THREAD

**Issue by yueamyen** [EdenServer/community#547]
Macro'd a gear change for ranged weapons. Switching out between regular bow and crossbow causes me to get the text " you move and interrupt your aim". This happens every time.

**Comment by beauxq** [comment]
Can you post here what the macro looks like?

**Comment by Aneyus** [comment]
I think this is related to the character blinking because all of my ranged attacks will also have the same thing happen unless I'm lockstyled.

**Comment by yueamyen** [comment]
Macro1:

/equip range "Self bow"
/equip ammo "Bone arrow"
/ra <t>


Macro2:

/equip range "Legionnaire's crossbow"
/equip ammo "Blind Bolt"
/ra <t>

**Comment by xerodok** [comment]
Bump. This is still an issue.

**Comment by godmode** [comment]
Please do not bump with no additional info if the ticket is still open.

**Comment by Mahou81** [comment]
This still seems to be an issue.
I got the message "You move and interrupt your aim." message with the following macro:
/ra <stnpc>
/equipset ## <wait 5>
/equipset ##
I tried putting a wait behind the /ra command of 1 second, but this didn't help.
It seems the blinking during equipment change while preparing a ranged attack is considered moving by the game.

**Comment by KnowOne134** [comment]
Has been fixed
