### ISSUE TITLE
Crafting: Brass Zaghnal incorrect GP value

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5471]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Discovered earlier that Brass Zaghnal, a goldsmithing GP item, has incorrect values for both turn-ins and the cap.

According to the old [wiki](https://ffxiclopedia.fandom.com/wiki/Brass_Zaghnal?oldid=306557), each item should give roughly 565 GP and the total that can be earned from turning in said item is 3520.  These values were also posted to [Allakhazam](https://ffxi.allakhazam.com/db/item.html?fitem=158) with the earliest date for the turn-in value being posted in early 2005.

On Eden, both values are considerably lower at the moment.  It seems these values were taken from an [FFXIAH post](https://www.ffxiah.com/item/16769/brass-zaghnal) from 2015; however, those values are taken from modern retail, in which this GP item was most likely nerfed due to it being the crafting result of the Goldsmithing Kit 15.

Correction: It was most likely this being added as an item obtainable via Sparks of Eminence that led to the GP value being nerfed in 2014.

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
