### ISSUE TITLE
Sacrarium pews

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5477]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

It should be possible to act on targets over the pews and desk in Sacrarium.

https://www.youtube.com/watch?v=SXxOz9FWgag

**Comment by 59blargedy** [comment]
I think this line of sight issue was fixed a while back but will check into it

**Comment by E5una** [comment]
No need to check, as usual, I've lead Dowzer astray. It was an issue last I checked, just validated it is no longer an issue on test.
