### ISSUE TITLE
Alkyoneus shouldn't counter

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5479]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Alkyoneus is able to counter. It didn't appear to be guarding on Eden, if it currently is then it shouldn't be. 

It doesn't counter or guard on retail. 

https://www.youtube.com/watch?v=EdLvQphWtE8

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
