### ISSUE TITLE
Demons shouldn't use Quadrastrike/Condemnation outside Dynamis

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5484]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Demon NMs in the Castle and Keep are currently using Quadrastrike and Condemnation. Only Dynamis mobs should be able to, with the exception of Marquis Sabnock which is ooe.

https://ffxiclopedia.fandom.com/wiki/Category:Demons

https://www.youtube.com/watch?v=SH-IHwUSGLY
https://www.youtube.com/watch?v=fNHUWvlZIus

**Comment by Steam-arch** [comment]
Hmm Condemnation might need a check in uleguerand though since its specifically mentioned
![image](https://user-images.githubusercontent.com/69089249/218276518-5fac0f88-96e4-49aa-83e0-63339b57a3f9.png)

**Comment by 59blargedy** [comment]
recently tested condemnation, wiki note is correct re: ule range

**Comment by dowzer** [comment]
Thanks for checking

**Comment by 59blargedy** [comment]
resolved in february 20, 2023 update
