### ISSUE TITLE
Out of Era Vendor Item: Slacks 

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5487]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently Slacks are sold by vendors that are listed on the current [wiki page](https://ffxiclopedia.fandom.com/wiki/Slacks) for the item.  These vendors are absent on this historical page from [2008](https://ffxiclopedia.fandom.com/wiki/Slacks?oldid=778316).  This [JP wiki](http://wiki.ffo.jp/html/14898.html) entry seems to confirm this item was added to vendors in July of 2011.

Other similar items may also be incorrectly added to vendors.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
