### ISSUE TITLE
Ix Aern(DRK) not pathing back to spawn area before despawning

### ISSUE THREAD

**Issue by LeaflyXI** [EdenServer/community#5489]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

popped ix drk, ran it back to zone line. adds despawned fast. die on one char from ix drk, zone on the other. let him walk back a little bit towards spawn area, zoned again. did this about 3 times while getting other char back, 4th time go back into zone, ix drk walked back a little bit and despawned. should despawn at ??? after a bit. 
https://www.bluegartr.com/threads/62459-Solo-in-Sea-and-stealing-NMs?p=2191969&viewfull=1#post2191969

version 30181205_0

**Comment by KnowOne134** [comment]
corrected in 8/7/2023 update
