### ISSUE TITLE
Khromated Leather recipe missing subcraft requirement

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5490]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

The Eden site right now shows that Khromated Leather has a synthesis requirement of 86 Leather and no sub:
![image](https://user-images.githubusercontent.com/95725249/220171740-3e9b916a-6881-420a-90c8-6b580f652ee6.png)

FFXI Wiki and BG Wiki show that this recipe has an Alchemy requirement of 45+:
https://ffxiclopedia.fandom.com/wiki/Khromated_Leather
https://www.bg-wiki.com/ffxi/Khrom._Leather

JP wiki lists this recipe as having an Alchemy requirement of 51:
http://wiki.ffo.jp/html/16189.html

**Comment by 59blargedy** [comment]
resolved in march 5, 2023 update
