### ISSUE TITLE
Mog Lockers are Inaccessible

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5491]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Following the most recent patch, Players are unable to access their Mog Lockers even if they're in Whitegate.

**Comment by FariskaEden** [comment]
I'm currently able to access mine and put items in / out without having paid. Issue may be that payment locks you out currently?

**Comment by Shika10** [comment]
My moogle says my mog locker is expired and I have access.

**Comment by NotSydes** [comment]
I was originally blocked from storage this morning after update and tried a number of remedies. Reloggong, adding coins, changing zones, talking to npc, coins to moogle, increasing storage space, swapping the zone access. Everything blocked.   
I'm version 30181205_0

**Comment by Thr33Swords** [comment]
A while back I paid several coins which made my expiry in June this year. I can't access my mog locker, says I don't have access to one.

**Comment by DeuceFFXI** [comment]
> 

On a mule whose mog locker should be expired currently and am able to access the mog locker.  Seems that whatever affected Mog Locker access changed a simple TRUE/FALSE value.

**Comment by KnowOne134** [comment]
Resolved in mini update 2/21/2023
