### ISSUE TITLE
Navigating the Unfriendly Seas end CS is slightly off

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5492]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 3018120_0

https://youtu.be/majpggPWa9E?t=527 shows a BLU gesturing with his sword. On Eden, he's empty handed and not very threatening at all since BLU doesn't have H2H skill

![image](https://user-images.githubusercontent.com/11255886/220177819-1c9334ea-73a5-4dba-9ae0-188ef014eb5f.png)

CSID is 233 btw

**Comment by 59blargedy** [comment]
But he has pants

**Comment by Mozzy4Ever** [comment]
![image](https://user-images.githubusercontent.com/11255886/220178450-9b9ef9bb-04e4-4e67-a509-fe88f565fd26.png)

As a COR, he should just take 'em off imo 😄

**Comment by KnowOne134** [comment]
corrected in the 11/19/2023 update
