### ISSUE TITLE
Funguar Breath TP moves, too much damage

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5493]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

PLD35 vs L43 Funguar (Max HP 1336)
![image](https://user-images.githubusercontent.com/11255886/220430826-3d371e45-64f0-40e0-9a30-ce9c2e2c1351.png)
![image](https://user-images.githubusercontent.com/11255886/220430857-223b9b8d-c315-4a6f-9ace-6671fd53ee3a.png)

At 200hp, funguar should be doing max 50 with both these moves according to Jimmayus sheet.
![image](https://user-images.githubusercontent.com/11255886/220431104-470c4481-7917-4860-b7a7-dbdc7b6adadd.png)

Instead is getting the OOE FTP 10 modifier.

**Comment by 59blargedy** [comment]
resolved march 2, 2023
