### ISSUE TITLE
Warp Tarutaru (Whitegate) teleport to nation (Bastok) sends you underground

### ISSUE THREAD

**Issue by Croftings** [EdenServer/community#5497]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Client Version 30181205_0
Using the warp tarutaru in Whitegate and selecting Nation (Bastok) teleported me into some grey underground area in Bastok Markets (POS : P-8)

Warped out, tried it again - Once again teleported to the grey underground area in Bastok Markets.

I can upload a screenshot if required.

**Comment by 59blargedy** [comment]
Resolved live February 25, 2023
