### ISSUE TITLE
Warp Tarutaru (Whitegate) teleport to nation (Bastok)

### ISSUE THREAD

**Issue by Shueiki** [EdenServer/community#5498]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Client Version **30181205_**
Warp Taru warping to Bastok sends you in an abyss. Still able to move, but not able to get anywhere. Warping, logging out and shutting down does not fix the issue.
![935892](https://user-images.githubusercontent.com/104343815/220820196-b9687072-18e3-4652-8402-6cff6e06fb04.png)
I seem to be stuck somewhere in (P-8) in Bastok Markets

**Comment by Mozzy4Ever** [comment]
Related to #5497
![image](https://user-images.githubusercontent.com/11255886/220820983-84be161b-d925-424f-a9fc-92e55046f412.png)

**Comment by Shueiki** [comment]
Update: using WHM teleports seem to work as well as BLM warp. However, will put you right back in the same place if using the warp Taru in WG.

**Comment by KnowOne134** [comment]
Duplicate issue
