### ISSUE TITLE
Dynamis Buburimu - Yagudo Chanters drop wrong currency

### ISSUE THREAD

**Issue by Snugglepunk** [EdenServer/community#5499]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

Vanguard Chanters in Dynamis Buburimu always drop bynes and should drop shells.
As far as I know there are only 3 chanters in the whole zone and they always drop Bynes every run.
![image](https://user-images.githubusercontent.com/56851217/220872474-f88c7441-6a75-4cf9-9627-82423a4f6215.png)
![image](https://user-images.githubusercontent.com/56851217/220872518-ea82a6aa-1c1c-4e33-b0f8-9de5bb0cfa27.png)

**Comment by 59blargedy** [comment]
resolved in recent update
