### ISSUE TITLE
Delivery Outbox Error

### ISSUE THREAD

**Issue by LokiStinkpalm** [EdenServer/community#55]
I have an alt named Triggered that has had mail in her outbox since icon was in charge.  im not sure if the person never took it ouf of their delivery box or if it just got stuck in there.  Any chance i could have the items either returned to Triggered or just taken out so i can have a whole delivery box to send from?

**Comment by godmode** [comment]
I've deleted the items from the delivery box. Please send a discord message to me when you are online to reclaim the items.
