### ISSUE TITLE
West Sarutabaruta mobs do not wander

### ISSUE THREAD

**Issue by ag4te** [EdenServer/community#550]
From leveling here, I have noticed that all monsters only take one step and stop, lingering around their spawn location instead of having a pathing a la retail.

**Comment by godmode** [comment]
Thanks for reporting. I'm not able to reproduce this issue. If it happens again can you call a GM and show him/her?

**Comment by beauxq** [comment]
I'm seeing the same thing, everywhere.
I think this is something that changed recently.
Does anyone see mobs wandering more than 1 step anywhere right now?
