### ISSUE TITLE
Dynamis Buburimu Apocalyptic Beast Soul Voice Firaga3

### ISSUE THREAD

**Issue by Snugglepunk** [EdenServer/community#5500]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Ver 30181205_0
Dynamis Buburimu Apocalyptic Beast often uses Firaga3 while using soul voice
![image](https://user-images.githubusercontent.com/56851217/220874212-fcb35696-f375-46d1-be36-13fa5c61fecd.png)

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
