### ISSUE TITLE
Rock Smash petrify going through shadows

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5501]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Rock Smash from Trolls is currently  applying Petrification even when the hit was absorbed by shadows. Shows Damage dealt as 0 and is actually doing 0 damage with shadows up.
![image](https://user-images.githubusercontent.com/11255886/221024433-38c5b338-defd-4a37-8262-f1693088c23e.png)

Without shadows it appropriately does damage and petrifies.
![image](https://user-images.githubusercontent.com/11255886/221024807-dec86611-3aa7-44fa-94b9-4fe158a030d2.png)

**Comment by 59blargedy** [comment]
resolved March 2, 2023

**Comment by Mozzy4Ever** [comment]
Still petrifying through shadows on live
