### ISSUE TITLE
Tiger Hide/Fang too common drop

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5502]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Tiger Hide itemID = 861
Tiger Fang itemID = 884

Batallia Downs: DropID 3023. http://www.ffxidb.com/zones/105/sabertooth-tiger Has hide at "Common" (15%) when it should be Uncommon (10%). Fangs are at Very Common (24%) and should be Common (15%)
Carpenters Landing: DropID 1033 http://www.ffxidb.com/zones/2/sabertooth-tiger Has Fang at Very Common (24%) and should probably be Common (15%)
Beaucedine Glacier: DropID 3624 http://www.ffxidb.com/zones/111/tundra-tiger Same as Carpenter's Landing, just Tiger Fang seems to be 1 too high. Should be Common
Uleguerande Range: DropID 3647 http://www.ffxidb.com/zones/5/uleguerand-tiger Same as Carpenters/Beaucedine. Tiger Fang is 1 too high, should be Common
Jugner Forest: DropID 1033 http://www.ffxidb.com/zones/104/forest-tiger Same as above, Tiger fang is 1 too high and should be Common
Aydewwa Subterrane: DropIDD 493 http://www.ffxidb.com/zones/68/cave-tiger Looks like Hide should be Uncommon (10%), is currently Very Rare (1%).

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
