### ISSUE TITLE
SAM (polearm) Ul'aern in sea at bottom of ramp to palace entrance seems to have Hundred Fists

### ISSUE THREAD

**Issue by ConteAlmaviva** [EdenServer/community#5504]
### Checklist

- [*] I have searched for existing issues for issues like this one. The issue has not been posted.
- [*] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [*] I have provided my client version in the details. (type /ver into your game window)
- [*] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

There's a Ul'aern at the bottom of the ramp leading to the Palace entrance that used to scoot around dead.  It seems like that behavior has been corrected, but when engaging him yesterday it seemed like he had Hundred Fists/0 weapon delay:

![image](https://user-images.githubusercontent.com/8880996/221371023-84532b4b-26c5-4081-b5b7-299552f5c116.png)

**Comment by StriderClerix** [comment]
![image](https://user-images.githubusercontent.com/46233090/222026502-2d12f483-92b6-4c48-8b7b-232366fa4ad0.png)
This is a SS of the HuXoi RDM Aern near the Ix'MNK pop.  Elegy was on, Slow2 just landed mid-SS (then I lost hate)

According to Tsulimae, some of the RuHmet ones are hitting fast too with bracelets up.

**Comment by 59blargedy** [comment]
this issue is resolved but the zone needs to restart (i.e. crash or maintenance) before it will resolve in game. !uptime of 0+ days from this point on means it's fixed.

**Comment by 59blargedy** [comment]
(hopefully) resolved in march 5, 2023 update
