### ISSUE TITLE
Feral Howl failing 100% of the time. Since the newest update

### ISSUE THREAD

**Issue by cellx17** [EdenServer/community#5505]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by Mu-cky** [comment]
Feral Howl in era is described as follows:
![Last Wiki Article on Feral Howl from June 2008](https://user-images.githubusercontent.com/94568270/221378447-5a257310-b921-432e-b59b-d46ec19e13b1.jpg)

Prior to patch, Feral Howl had some message errors such as not displaying that a character used the ability, but would take effect on most mobs up to and above the characters level.

After patch, Feral Howl has the same message errors, but no longer takes effect on mobs. I have tested it on level 10 strolling sapling in Tahrongi Canyon and a level 72 Tregopan in Bibiki Bay. Reports have come in to me from other BSTs that it is no longer functional.

Reproducible Steps
/ja "Feral Howl" <stnpc>
Enter
Observe the message, "No effect on the <name of mob>"

Images:
![Mucky_2023 02 25_122014 Showing No Effect - level 72 Tregopan F-6 Bibiki Bay](https://user-images.githubusercontent.com/94568270/221378864-8e06491b-7976-4978-83ed-ef4df0b1316f.png)
![Mucky_2023 02 25_122724 Showing No Effect - Level 10 Strolling Sapling - H-6 Tahrongi Canyon](https://user-images.githubusercontent.com/94568270/221378875-249c1d0c-04f5-4d21-b435-61ee7fdc2efb.png)
![Mucky_2023 02 25_124225 Showing No Effect - Level 10 Strolling Sapling - H-6 Tahrongi Canyon 2](https://user-images.githubusercontent.com/94568270/221378884-dee9fe3a-4281-46b2-aef8-f36ec203972d.png)

Video:
[Feral Howl Failure on a level 10 Strolling Sapling in Tahrongi Canyon](https://drive.google.com/file/d/1-qE_mihxa-ej_TBsh1btacgZm7KHQSOk/view?usp=sharing)

Version: 30181205_0

**Comment by 59blargedy** [comment]
resolved in march 5, 2023 update
