### ISSUE TITLE
Sagheera not giving back bard's slippers +1 after conquest tally

### ISSUE THREAD

**Issue by boggartff11** [EdenServer/community#5507]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Traded Sagheera NQ bard slippers, bard slippers -1, 28 one byne bills and the griffon leather last night at appox. 10:20 PM EST.
Logged out in place, logged back in after conquest and Sagheera reacts as if I just traded her everything still.
![image](https://user-images.githubusercontent.com/118860824/221427410-c6c6e239-76c6-4f37-8656-825e8651b26f.png)

I am just going to wait until next tally to get them, but wanted to capture this in a report since it was definitely before tally when I traded everything.

**Comment by 59blargedy** [comment]
resolved by another dev in march 5, 2023 update
