### ISSUE TITLE
Blue Light Groundskeepers Aren't aggroing with /NIN

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#5508]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.
ver 30181205_0
### Details

Looks like the Groundskeepers arent aggroing when standing in front of them on their pedestals when you have Stealth as a subjob.
Tested with BRD/WHM and they aggro as normal.

![image](https://user-images.githubusercontent.com/62901732/221437012-a2cccf6f-f805-4235-b121-0e1b207e4ced.png)

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
