### ISSUE TITLE
Ifrit's cauldron mobs not aggroing properly

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#5509]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.
30181205_0
### Details

Since the last patch, Ifrit's cauldron's navmesh appears to be reverted to before the navmesh tweaks. 

Bombs are back to not aggroing when on ledges or raised platforms when mining.

**Comment by Steam-arch** [comment]
Bombs had their vision range drastically reduced to 2,5/5/7,5 depending on weather and game time. Sure it wasnt just a short vision range and you expected a much higher one? They used to have 15 vision on eden I think

**Comment by statuseffect** [comment]
Fairly certain it's not the vision. But I'm not at home to test that. Can later though.

**Comment by Steam-arch** [comment]
@statuseffect -b 

Most likely the /nin Stealth trait issue as mozzy pointed in dm. Stealth further drops aggro range to 0 when aggro range is already reduced by weather

**Comment by statuseffect** [comment]
Looks like its reduced to 0 even without weather
![Iaito_2023 02 28_173455](https://user-images.githubusercontent.com/62901732/221997637-c373020b-9b7f-439e-8b16-f13d4580fd5a.png)

**Comment by statuseffect** [comment]
I think it may have been fog or something because they eventually started aggroing again.

**Comment by DeuceFFXI** [comment]
It's not just fog.  Stealth is seriously broken.  Ran past a bat that didn't even flinch as a ran right on top of it without sneak.  In Ifrit's by the way.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
