### ISSUE TITLE
Crawler Poison Breath doing 15/tic

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5511]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Poison Breath currently doing  15/tic. Should be 1/tic per Jimmayus sheet.

**Comment by 59blargedy** [comment]
issue resolved March 2, 2023

**Comment by Tofutoshi** [comment]
Poison breath should be 4 damage/tick. 

At 1m28s in the video you can see the poison breath ticking for 4.
https://www.youtube.com/watch?v=nBgefcTk0ho
