### ISSUE TITLE
Bomb Self-Destruct has -1000+ MACC

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5512]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Self-Destruct from Bombs (ie: Volcanic Gas in Ifrit's Cauldron) currently has over -1000 MACC in the MHR print. Tested with a brand new character

![image](https://user-images.githubusercontent.com/11255886/221772861-fa889484-fdcf-4106-805f-951bcf9c1aa9.png)

**Comment by Mozzy4Ever** [comment]
> can you list instead what the issue is on live that caused this bug report?

Bombs in Ifrit's Cauldron constantly doing <100 damage despite being >2k HP

**Comment by 59blargedy** [comment]
issue resolved march 2, 2023
