### ISSUE TITLE
Tiamat damage too high

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5513]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

In air on Eden, Tiamat is doing 621+ damage unresisted to a PLD (No MDB/MDT)
Firaga's hitting for 848

https://www.youtube.com/watch?v=dTEzoFiE-2o has what looks like a NIN (Donnie) in PDT gear taking: 244, 244, 244, 244, 244, 274 to Darkwind (NIN/WAR), 258 (Donnie), 250 (Darkwind)
Firagas for: 339 (452 to Sinitruli, 444 to Irou), 339 (434 to ), 69 to Donnie

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
