### ISSUE TITLE
Znm Tyger aggro sight 

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5516]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Ended up in a situation where we had to zombie a Tyger yesterday(March 1st) and found out that he aggros.

According to bg wiki's chart it doesn't aggro 

https://www.bg-wiki.com/ffxi/Tyger

**Comment by dowzer** [comment]
It should be passive

https://www.youtube.com/watch?v=-ue13d13HZw

**Comment by 59blargedy** [comment]
resolved in may 22, 2023 patch. thanks dowzer for the research
