### ISSUE TITLE
Unable to activate Howling Moon (Fenrir 2hr BP) while under Astral Flow

### ISSUE THREAD

**Issue by AshleyAwakens** [EdenServer/community#5517]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I was unable to use Fenrir's 2-hr Blood Pact while under the effect of Astral Flow. We were level synced to 35 in Zitah, and the BP was not avaliable through menuing nor macro. I also attempted resummoning Fenrir and could not access the 2hr BP. Attached is an image showing that I have the Astral Flow buff active but no access to Howling Moon in the Pet Command->Blood Pact: Rage menu.

My /ver output is "version 30181205_0"
![image](https://user-images.githubusercontent.com/119537953/222870666-2d26d9b0-dbf4-43ee-90e4-f8c1072c0378.png)

**Comment by StriderClerix** [comment]
How much MP did you have?  I know there’s a minimum mp needed to activate the BP - unsure if the BP disappears from the menu if you drop below that.

**Comment by AshleyAwakens** [comment]
I had at least 200 mp, and the wiki says that if you have less than 2xLVL mp, the BP will fizzle and deal no damage.

**Comment by AshleyAwakens** [comment]
As requested by several people, here is a full image screenshot taken during a BST burn at lvl sync 40, with no Howling Moon avaliable within the Blood Pact: Rage menu. While I didnt get another screenshot while pulling, I did check that Carby had access to Searing Light before summoning Fenrir to check
![image](https://user-images.githubusercontent.com/119537953/222876545-34894a41-bd54-44d4-87f3-fad4674f5be3.png)

**Comment by 59blargedy** [comment]
resolved in march 5, 2023 update
