### ISSUE TITLE
Doomed Pilgrim ZM5 hits too weak 

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5521]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Hits for 40-75 (0s are guards), should hit for 160-220. HP needs a check too, should have 17k HP

![image](https://user-images.githubusercontent.com/69089249/223440758-f587fb5c-9570-47a1-8945-70b836a7c194.png)

Good era vid for damage numbers
https://www.youtube.com/watch?v=fMqumvLQ2PA

(I might update this later just doing quick checks on these)

**Comment by 59blargedy** [comment]
this was resolved in the august update
