### ISSUE TITLE
Guivre has an unknown despawn mechanic

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5523]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I was doing the not suspicious at all "Bring guivre to the pond"-challenge, brought him to the pond area at devil manta, died, guivre blinked off the screen, ran to his normal route and despawned once he got back there.

Recreated on test server a few times also, but it does not seem to happen every time, highest success rate having guivre red. 
![image](https://user-images.githubusercontent.com/69089249/223485950-84033caf-b91a-4336-80d6-52f30823c2f4.png)
 
(Disclaimed: wasnt mpking anyone, was just going to have a mexican stand off at the now cleared from scorps battle arena next to the pond)

![image](https://user-images.githubusercontent.com/69089249/223487844-25d49d07-3795-48b0-b869-d6ca48254256.png)

**Comment by 59blargedy** [comment]
This is intended behavior for guivre. Has a special despawn mechanic.
