### ISSUE TITLE
Nue Fang drop rate 1 tier too low?

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5525]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Looks like currently Nue Fang is set to "Common" (15%). Based on <http://www.ffxidb.com/zones/111/nue> it seems like it should be Very Common (24%). 

TH0 = 34.8% (181 sample size)
TH3+ = 62.3% (583 sample size)

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
