### ISSUE TITLE
Proto-Ultima magic attacks too powerful

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5526]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

https://www.youtube.com/watch?v=5TEZU_aR0dA&t=382s
Antimatter for 1157 at 3:42
Hydro Cannon for 857 at 4:09

Both were without buffs, dissipation went off shortly before and full dispelled the alliance

Based on this video I believe our Proto-Ultima is too strong. Specifically Antimatter and the 6 elemental conal weaponskills, 
Antimatter is hitting an eden pld for around 2k, and the conals are doing 1500+. From the video Antimatter should be 1100ish and the conal around 800.

https://ffxiclopedia.fandom.com/wiki/Proto-Ultima

**Comment by falzum** [comment]
May have spoken too soon, Antimatter for 1620 at 5:15 in the video. Might just be the conal attacks that are tuned up

**Comment by Slamm21** [comment]
![image](https://user-images.githubusercontent.com/5552081/223558665-ccaabe9e-c018-4e4b-be66-0774141277a5.png)
Our Damage taken today

This should be a good reference point
https://kanican.livejournal.com/4431.html

> TP Moves and Special Abilities to Watch For
> 
> Anyone who's done a Proto-Ultima fight knows how insane some of the TP moves are.  Using this setup, we were able to limit them for the most part so they were managable; however, special precautions still needed to be made for a couple of them.  Here are the ones we watched for particularly.  They appear at different frequencies and HP ranges - for more information about which are used when, try looking at the FFXI Wiki for Temenos.
> 
> Dissapation - AoE Full Dispel all Buffs except Food + Terrorize
> This one isn't quite as bad as it looks, although this is especially annoying for BRDs since they get hit sometimes and have to rebuff songs.  RDM has to rebuff haste, refresh, protect, and shell after every one of these.  Then there is the terrorize effect.  Typically we'll just have the BLMs stun in succession and the terror will wear after Senrez only ate 1-2 hits (in physical damage reduction gear).  This move sounds horrible, but it's not when you're prepared.
> 
> Equalizer - 800+ Damage Conal + Partial Hate Reset
> This one presents a bit of a problem as a partial hate reset would cause the BLMs to take hate immediately and possibly take a death, slowing down progress considerably.  Luckily, as mentioned previously, you can counter this with 2 shadows so as long as the NIN keeps 2 up at all times, this one isn't all that bad.
> 
> Antimatter - 1000-1500 Damage Single Target Light Attack
> The damage on this move goes right though blinks but does not wipe them.  This move is really the reason Senrez is using Merman's Rings at all times - the damage range on this move is so large because of the constant weather effects.  This move by itself isn't too bad as it is survivable with large HP, but if Ultima follows this quickly with other moves like its Holy II, there could be an issue and possible tank death (wipe).  Stun after this move is a good idea to prevent something like Antimatter > Double Attack > Holy II, which would instantly kill the tank.
> 
> Smoke Discharger - 600 Damage Conal + Petrification
> This move is only bad because our setup lacks a WHM for stona.  Essentially switch into full Physical Damage reduction gear and stun after this one gets off.  That's about the best you can really do using this setup.  The move doesn't wipe shadows so it has some decent leeway with it.
> 
> Holy II - 600-800 Damage Light Magic
> This one is dangerous for 2 reasons - 1) he can cast this randomly throughout the fight and it automatically wipes a shadow and 2) it will use this once after every TP attack after 60% HP on a random target in range - typically the tank again or a BRD.  The BRDs need decent HP and stoneskin to be ready for this one.  It gets really dangerous after a strong TP move such has Antimatter > Holy II.

We had shell iv and mdt roll and still getting one shot.
tanking ultima as rdm on retail, usually stoneskin absorbed all damage throughout (recasting after each hit) and most fights would end taking 0 damage.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
