### ISSUE TITLE
Kraken on Purgonorgo Isle not respawning

### ISSUE THREAD

**Issue by Hakuhen** [EdenServer/community#5527]
### Checklist
Kraken spawning at F-9 on Western beach / Purgonorgo Isle didn't respawn after kill. Fandom says 5 min respawn. Was killed about an hour ago now.

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Client version 30181205_0
https://classicffxi.fandom.com/wiki/Kraken

**Comment by 59blargedy** [comment]
they won't respawn on the same island. if it's not respawning everywhere, then that's a different story.

**Comment by Hakuhen** [comment]
Didn't know they could respawn at different spots. Used to see the one im talking about respawn same place 3 or 4 times in a row. Its true i saw 2 on Eastern beach so might be it. Had to emergency warp because of clot aggro but will definitely come back and check again. Thank you for the intel.

**Comment by 59blargedy** [comment]
sure, it's something that was updated last patch.
