### ISSUE TITLE
Scouting the Ashu Talif - Imps are stlll roaming after patch, however crewman are fixed.

### ISSUE THREAD

**Issue by LahaEden** [EdenServer/community#5528]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by LahaEden** [comment]
First run after recent patch that had fixed the roaming issue. the Crewman(fomors) appear to be fixed but the imps are still moving. This includes the imp NM

**Comment by Mozzy4Ever** [comment]
https://github.com/EdenServer/community/issues/5440

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
