### ISSUE TITLE
Cactrot Rapido - Depop/Vanishing unclaimed

### ISSUE THREAD

**Issue by Timberwolfwood** [EdenServer/community#5529]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [30181205_0 ] I have provided my client version in the details. (type /ver into your game window)
- [Z ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Tracking Cactrot Rapido with Widescan, no one else in zone gathering our team to kill it and he de-spawn/depops of his own accord after being tracked for almost 30 minutes on his run paths with widescan attached, widescan then just fell off and the mob vanished.

Can't find any information from Era or otherwise that suggested the mob should despawn / depop of it's own accord?
Believe this might be incorrect behaviour and hard to qualify now without another D3 wait but will attempt to get more data on next spawn.

![image](https://user-images.githubusercontent.com/76717525/224306660-97c655e7-2b72-4cd3-a194-2baeda8f916b.png)
![image](https://user-images.githubusercontent.com/76717525/224306791-7cd9d786-49a3-4b9d-8483-659dcefca1a7.png)

**Comment by dowzer** [comment]
I camped it regularly era and never experienced it despawn

**Comment by Steam-arch** [comment]
Did you happen to do a /sea of the zone when it disappeared? a few job combos can 2hr it in less than 30s and can be in and out in 5 min if rng is right

**Comment by falzum** [comment]
If they had it tracking on widescan the name would have turned red if someone claimed it I think

**Comment by 59blargedy** [comment]
i was informed that on the day in question, cactrot was indeed killed. think this was just a case of it being killed fast and it getting missed. appreciate the report in case it was an issue, and for someone letting me know it wasn't something to look into.
