### ISSUE TITLE
Shadow NMs not linking with Specters

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5530]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Currently the nearby Specters to Western/Eastern/Southern/Northern Shadows won't link to the NMs when you pull them. The Specters themselves will link with each other, though.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
