### ISSUE TITLE
Shadows NM/Specters missing Evasion Down

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5531]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

The various wikipedia pages for the Shadow NMs say they all have Evasion Down on their melee attacks. 

http://wiki.ffo.jp/html/2629.html (JP wiki also says that the ones in Eldieme Necropolis should have Evasion Down on attacks too)
![image](https://user-images.githubusercontent.com/11255886/224468449-14b135ef-a048-4ca4-a503-c1e9f70aec43.png)
http://wiki.ffo.jp/html/18132.html
![image](https://user-images.githubusercontent.com/11255886/224468514-fb26516b-5e56-419c-bc76-d219d53aeb52.png)

https://ffxiclopedia.fandom.com/wiki/Specter?so=search
https://ffxiclopedia.fandom.com/wiki/Southern_Shadow?so=search

https://www.youtube.com/watch?v=Gay5qFbvZtU (good 'ol Kaoz vid...) shows Eastern Shadow putting Evasion Down on a Courier Carrie relatively often. Other vids I could find of other NMs sadly were too quick to get an idea of proc rate, but do know it's not guaranteed at least.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
