### ISSUE TITLE
Sarameya Scorching Lash should be conal

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5532]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

http://wiki.ffo.jp/html/2903.html
https://www.bg-wiki.com/ffxi/Category:Cerberus
https://ffxiclopedia.fandom.com/wiki/Scorching_Lash
https://youtu.be/BJOMFHjz17U?t=224 (yay kaoz vid)

All links either show it being rear conal, or say it should be. Currently it's single target on Eden. Guessing it should be rear conal on Cerberus too.

**Comment by 59blargedy** [comment]
resolved by another dev in may 22, 2023 patch
