### ISSUE TITLE
Mythril Dagger Desynth Results incorrect

### ISSUE THREAD

**Issue by bliven-was-taken** [EdenServer/community#5533]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Results should be:  
NQ: Iron Ingot
HQ1: Iron Ingot
HQ2: 4x Mythril Nugget
HQ3: 6x Mythril Nugget

https://www.twitch.tv/videos/1765161057

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
