### ISSUE TITLE
Steam Cleaner should be an unique snowflake and sound aggro

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5534]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Only magic aggro currently on eden

![image](https://user-images.githubusercontent.com/69089249/225320066-c084988a-0841-44ed-988f-a01fd1b97f3d.png)

![image](https://user-images.githubusercontent.com/69089249/225320224-aa4cb4cc-52fb-4ec8-bcf3-79416ff2eb7a.png)

Might need a retail check?

**Comment by Steam-arch** [comment]
Confirmed it to be 8 non true sound aggro, standard 20 magic. Recorder failed to save vids for some odd reason, so no actual clip, sorry.

![image](https://user-images.githubusercontent.com/69089249/225424958-f3bf97bd-da1c-4a37-9234-3fd9cd33b367.png)

**Comment by Steam-arch** [comment]
Also noted that it does not stop moving when it unaggroes. It rushes straight back to the bottom floor without doing the normal  move stop move stop move stop-pattern, The wheels keeps on turning.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
