### ISSUE TITLE
Dosetsu Tree does not move after being claimed

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5535]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Spawns stationary correctly but does not move after being claimed.

![image](https://user-images.githubusercontent.com/69089249/225605367-8c5b3af0-e0c7-4f54-ae23-b9e77187eb7e.png)

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
