### ISSUE TITLE
Horror Cloud overwrites the spell Haste

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5536]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Propably will be corrected whenver haste & slow is overhauled together, but submitting this just incase, currently Horror Cloud overwrites haste and can not be overwritten by haste.

![image](https://user-images.githubusercontent.com/69089249/225611411-a63c2835-f0be-4ebd-8f2f-fc341dddce0d.png)

Refuelings text about horror cloud cant even overwrite that
![image](https://user-images.githubusercontent.com/69089249/225611505-1cf0b0b6-51ac-4c39-b8aa-702264983225.png)

**Comment by KnowOne134** [comment]
making 1 report to put these all under with reference to this issue
