### ISSUE TITLE
Viscount Morax in Castle Zvahl Keep uses Astral Flow and spawns avatar, but avatar does not use blood pact

### ISSUE THREAD

**Issue by Shika10** [EdenServer/community#5537]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
 version 30181205_0

Viscount Morax uses his 2 hour animation, the avatar spawns, but no blood pact happens. I have reproduced this twice. The avatar will stay out and fight until it is defeated. It even stays active after the NM dies. Almost like it decouples from the NM upon being spawned. As an NM SMN, he is supposed to Astral Flow, but the blood pact itself is obviously broken.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
