### ISSUE TITLE
Treasure Chests in Castle Zvahl Keep only produce Phalanx Rings upon opening

### ISSUE THREAD

**Issue by Shika10** [EdenServer/community#5538]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

I don't have a huge sample size yet, but I have received four Phalanx rings in a row from Castle Zvahl Keep treasure chests. According to the classic wiki, these are supposed to produce precious stones or gil as well. If anyone has received any of the other drops very recently, please add to this. https://classicffxi.fandom.com/wiki/Castle_Zvahl_Keep?so=search

**Comment by Mozzy4Ever** [comment]
![image](https://user-images.githubusercontent.com/11255886/225699641-d67c16fc-4101-48e9-be0b-09258dcad366.png)

**Comment by DeuceFFXI** [comment]
The classic wiki page is missing a lot of useful information.  The [retail wiki](https://ffxiclopedia.fandom.com/wiki/Castle_Zvahl_Keep) has the estimated rates for each item on the page, which has Phalanx Ring listed as being ~54%.  So, four of them in a row shouldn't be out of the norm.  And I believe the rates for chests/coffers on Eden are roughly based on what the retail wiki has listed.

**Comment by 59blargedy** [comment]
Thanks for reporting, code and testing look to be fine, able to get other items and gil.
