### ISSUE TITLE
Stealth Trait and the new mob Aggro Range changes

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5540]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

So, based on this [bug report](https://github.com/EdenServer/community/issues/5509), I believe further testing is warranted on retail regarding how weather affects the variable aggro range of monsters in-game.

Currently as it stands on Eden, based on my own experience in Ifrit's Cauldron, during certain weather, all of the following mobs have failed to aggro even while the player is within 5 yalms of their "line of sight"; Volcanic Gas, Dire Bat, and Sulfur Scorpion.  Both the bat and scorpion were ran directly by without any sneak effect active and they failed to aggro.

This honestly doesn't seem like the correct behavior for these or any monster in FFXI.  My theory is that on retail there is a floor to how "blind" aggressive monsters are.  That is to say, while weather may reduce the range at which certain mobs aggro, Stealth can reduce it further, only up to a certain point.  I'd also be curious how stealth effects mobs which detect by sight vs those which detect by sound.  I wouldn't be surprised if there is a difference.

Lastly, per the original bug report, this may indeed only pertain to Ifrit's Cauldron; however, due to the recent change of weather altering the aggro range of monsters, I find it unlikely that the zone is the issue.

**Comment by Steam-arch** [comment]
Yeah, we have tried to find out what Sneak I / Sneaking boots does on retail, but so far havent seen any unexpected variance in sight/sound aggro ranges in any scenario, even though most claims are that in reduces aggro ranges. On eden it drops some mobs with short/reduced sighted/hearing mobs to 0. Might drops direbats and sulfur scorps to 0 whenver their sound range is reduced from 8.

Will be fixed eventually, latest whenever someone figures out what stealth _actually_ does.

**Comment by DeuceFFXI** [comment]
In all honesty, these changes were something that shouldn't have been deployed with the overall state that Stealth mechanics are in.  It would have been best to test Stealth on retail with these changes in mind, as a significant portion of the playerbase is subbing Ninja at any given time.  Currently, when combined with the recent changes Stealth is quite literally a game breaking job trait.

I am sure there are other zones that this is noticeable in, but in Ifrit's, where I've spent a decent amount of time mining in the last 24 hours, Stealth allows a player to effectively run around the zone with impunity.  To emphasize my concerns, below I'll relist some of the things I've observed as well as add some more observations.

- Volcanic Gas, ran in front of their line of sight inside a 2y radius without aggroing (Possibly under certain weather conditions)
- Dire Bat, ran directly past them within a 2y radius without aggroing (Likely under certain weather/time conditions)
- Sulfur Scoprion, at times only aggro when a player with Stealth is next to or within their model, 1-2y
- Volcanic Bomb, ran by their line of sight within 2-3y, no aggro.
- Nightmare Bats, ran by them within 2-3y, no aggro.

Again, Ifrit's is the zone I've noticed this issue in the most.  I've been to some other zones with mobs that aggro a 75 player to a lesser extent and their behavior is seemingly unchanged.  Although, these zones are several inside dungeons that lack day/night and foggy weather effects from my understanding.

As much as this may come across as an alarmist stance, under the right conditions, several mobs fail to behave in the way that they should.  And aggro mechanics are a core aspect of FFXI's gameplay as most if not all of us are aware.

**Comment by Steam-arch** [comment]
Yeah I agree aside hard to sometimes tell beforehand how a eden mechanic behaves with a completely new system. Id just kill the trait for now untill someone brings something to the table about it.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update. just a request, if you could please keep bug reports to facts only - discord is a good place to discuss your opinions, but the intention of a bug report is a report of the issue encountered. it makes it easier to resolve to not have to search through to find the facts. thanks!
