### ISSUE TITLE
Warrior's Lorica Bug

### ISSUE THREAD

**Issue by Oir11** [EdenServer/community#5541]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I have obtained the Warrior Lorica which per Classic Wiki & Eden Wiki states that it enhances Aggressor effect (This should decrease the evasion penalty by 10) it does not say while equipped, (like the Warrior's calligae) . Upon a bit of testing with /checkparam It does not appear that it gives any decrease in evasion penalty.

Client Version: 30181205_0

![1](https://user-images.githubusercontent.com/128196658/226076268-1cdbc101-008d-4d0c-a25f-d02401992af8.png)
![2](https://user-images.githubusercontent.com/128196658/226076272-7b3db8fe-e347-42a5-a0e5-a4655d5d2b76.png)
![3](https://user-images.githubusercontent.com/128196658/226076276-d73f8c99-39d6-4574-a0c2-414d170cd75b.png)
![4](https://user-images.githubusercontent.com/128196658/226076278-4ee3abd0-478e-43f8-915c-76691b3b42c8.png)
![5](https://user-images.githubusercontent.com/128196658/226076282-9a71e5ed-2bdf-4300-84c4-85c03a9620b2.png)

![chrome_iz931v5E
![chrome_YaBJ5HIede](https://user-images.githubusercontent.com/128196658/226076478-4a428527-c362-41cb-ba58-5c6766180610.png)
cz](https://user-images.githubusercontent.com/128196658/226076475-06d1f200-7bd1-4b05-9c25-41cd921a9afb.png)
![chrome_YaBJ5HIede](https://user-images.githubusercontent.com/128196658/226076487-7d162a62-6dd2-4c17-9d08-9437e268b44d.png)

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
