### ISSUE TITLE
Trial-Sized Battle Healing issue

### ISSUE THREAD

**Issue by WideEyedKid** [EdenServer/community#5543]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version - 30181205_0

I have just attempted the Garuda and Leviathan trial sized battles and in both instances after having kited them down to about 50% without ult, once Searing Lights have started, the avatars seem to be healing for too much via their curing abilities. After the first searing light and running away to prepare to recast carbuncle, the avatars end up with almost full hp. Leviathan was the only one I happened to be in range of to see the log for healing, and it was for about 450hp. The battles timed out as there was no possdible way to win with them at full hp and with summoner ult used x3.

There is an open bug report from 2021 on Leviathan, but I see nothing on Garuda. Seems to be a very similar issue though.

![Cyril_2023 03 18_135926](https://user-images.githubusercontent.com/128250970/226127176-52514a3d-f60f-4b96-818e-6c491022c83a.png)

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
