### ISSUE TITLE
Scorpions missing enhanced movement speed?

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5546]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Scorpions in West altepa easily caught up on retail running away. On eden they stay same distance. MIGHT be sandstorm (weather) related or maybe its all scorps, will update & confirm later.

**Comment by 59blargedy** [comment]
tested in western, with and without single weather up, day and night, tulwar scorpion had normal movement speed, gonna close this one out.
