### ISSUE TITLE
Bastok Mission 6-1 issues

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5548]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

1: No Message when touching ???
Can see message here:
![image](https://user-images.githubusercontent.com/69089249/226457769-426f2652-e2e6-4837-9379-e360db994176.png)
![image](https://user-images.githubusercontent.com/69089249/226457671-ce50e6e4-0919-4848-bb48-d9d456e54a9a.png)

2: Spawns passive on eden

era vids where they pop it:
https://www.youtube.com/watch?v=Nx0uIIEK3WY
https://www.youtube.com/watch?v=TwQkqaR1U-0

Can see both sight aggroing players

![image](https://user-images.githubusercontent.com/69089249/226459460-418ccd98-e39d-48e6-8d75-43547c5d866d.png)

3: Pop positions are slightly wrong but no biggie. Other one should spawn on top of the big pillar.

⁴: Killing one and depopping the other doesnt count as a win. Reclicking the ??? After killing just one respawns them. Can see depop strat mentions and wins in wiki & youtube
![image](https://user-images.githubusercontent.com/69089249/226865638-a597f09f-6881-4ece-a99a-d0a22cc5fd5c.png)

5: They might be set to link in a set time which shouldnt happen (the other one waited awhile before linking which seemed abnormal)

**Comment by Steam-arch** [comment]
Confirmed the things above and added two

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
