### ISSUE TITLE
Bastok Mission 6-2 issues

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5549]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

1: Hits like a popoto atm

![image](https://user-images.githubusercontent.com/69089249/226862623-3282ca83-f9b1-4304-afa3-04d869042512.png)

(mnk75/blm37, no bb or other dmg- equipped, 311 def, protect III)

Wiki mention:
![image](https://user-images.githubusercontent.com/69089249/226862824-4ef62cf4-8106-483c-af77-ea4e1090e341.png)

You see, carefully observing and judging from these pixels, you can see that Magma is hitting a lvl 75 BSTs couriercrab for 150s
![image](https://user-images.githubusercontent.com/69089249/226863035-67fabd27-9ea1-4d6e-bdb4-0fb1894dc390.png)
![image](https://user-images.githubusercontent.com/69089249/226863287-aeb6dcaa-4ec4-49e5-a37a-280c3e707440.png)
![image](https://user-images.githubusercontent.com/69089249/226863390-5039a06a-5114-435e-9bd1-46f8c5258d23.png)
![image](https://user-images.githubusercontent.com/69089249/226863489-2588cc8f-332b-46b3-9e0b-0abef1510a6f.png)
![image](https://user-images.githubusercontent.com/69089249/226864932-2bf11cdd-e178-4966-8f41-6c94dc742f82.png)

https://www.youtube.com/watch?v=hdn-IW-Ok48

Vid where X level sam takes 170ish
https://www.youtube.com/watch?v=rp4y6H_7Wo8

----------------

2:  Upon spawning should give text:
![image](https://user-images.githubusercontent.com/69089249/226866093-ad4c5641-c960-488c-b74e-1772bbcd3e29.png)

--------

3: Sleep and stun immunity might need a check
![image](https://user-images.githubusercontent.com/69089249/226864883-5b9664b5-d1fa-4dce-84fd-d97f92f46655.png)
![image](https://user-images.githubusercontent.com/69089249/226865204-e3f35ee8-54dc-4e9a-8d9f-d605c09f21d6.png)

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
