### ISSUE TITLE
Bastok mission 8-1 Issues

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5550]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

1: BLM antica propably has double the ammount HP that it should. The other mobs match wiki HP
![image](https://user-images.githubusercontent.com/69089249/226984355-18c70b58-b4ed-401c-a1af-1945ceacb0c5.png)

![image](https://user-images.githubusercontent.com/69089249/226984474-e00b6195-73e8-40e0-b1a8-c60530038336.png)

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
