### ISSUE TITLE
Bastok Mission 8-2 NMs might hit too weak

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5551]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Close if you feel like its right already. Enter the talekeeper mobs seem to hit for verylittle atm, pretty sure they should hit for abit more atleast? but might require someone to go on retail to check since era vids are poor.

![image](https://user-images.githubusercontent.com/69089249/227010884-503ff19d-f338-4a0a-9aba-857c90448b55.png)
![image](https://user-images.githubusercontent.com/69089249/227010907-586bcfec-5f4e-4fe2-b2fe-784f20816777.png)
![image](https://user-images.githubusercontent.com/69089249/227010942-80607881-6379-4c76-8537-2fcf3f3f7068.png)

Some video damages (no clue on levels), machor af pld.
![image](https://user-images.githubusercontent.com/69089249/227011349-e8ce496c-1784-4771-8863-f50b1391cea3.png)
![image](https://user-images.githubusercontent.com/69089249/227011407-cdae1518-c739-42b7-9094-db22444cf4e1.png)
![image](https://user-images.githubusercontent.com/69089249/227011453-d29f7bee-948a-4496-a7d5-25acb74acb62.png)
![image](https://user-images.githubusercontent.com/69089249/227011545-3d2697bc-ea7d-4c95-8475-1f47151dfca1.png)

Cant really find proper era damage numbers but:
off era fenrir (no idea on smn level)
![image](https://user-images.githubusercontent.com/69089249/227010739-2d159565-0345-4a03-9ad3-b4bd5c8ca1f1.png)
![image](https://user-images.githubusercontent.com/69089249/227010799-a0537ebc-0ab9-4193-838b-163e6999cc72.png)
![image](https://user-images.githubusercontent.com/69089249/227010821-d98a20cd-4cab-4875-9862-3f42f01f3280.png)

https://www.youtube.com/watch?v=phnW0cO1GfM
https://www.youtube.com/watch?v=r7tokwyjeeY

![image](https://user-images.githubusercontent.com/69089249/227012330-ee051eff-1be8-4774-af01-53c4f6b54e29.png)
![image](https://user-images.githubusercontent.com/69089249/227012478-2413869d-6cdf-4f6d-96bf-4074f73f9a4e.png)
![image](https://user-images.githubusercontent.com/69089249/227012360-531458e6-b78b-4337-9e8d-8aba0c39c01d.png)
![image](https://user-images.githubusercontent.com/69089249/227012624-57ccb0ec-888d-4183-83c9-50f67f9cbabb.png)
https://ffxi.allakhazam.com/db/quests.html?fquest=430

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
