### ISSUE TITLE
Seiryu not Weapon Skilling or Casting when spawned. 

### ISSUE THREAD

**Issue by hallowFFXI** [EdenServer/community#5552]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
- Version 30181205_0 

Popped Seiryu, did not Weapon Skill or cast spells until he used Hundred Fists. Same thing sorta happened with Tiamat, I'll link both videos linked below just in case it helps. 

Seiryu: 
https://www.youtube.com/watch?v=wb523NdtWtU&ab_channel=hallow

Timestamps: 
- Popped at 01:25
- 2 Hour at 08:21

---------------------------
Tiamat:
https://www.youtube.com/watch?v=upNtrOMSqro&t=5s&ab_channel=hallow

**Comment by 59blargedy** [comment]
believe resolved in may 3, 2023 update, but didnt make sense that this was occurring for seiryu in the first place, so please comment and will reopen if it's spotted again
