### ISSUE TITLE
Everyone's Grudging quest not triggering.

### ISSUE THREAD

**Issue by Allorddemon** [EdenServer/community#5553]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

1) I obtained Rancor Flame by trading Unlit Lantern to the Altar of Rancor at Den of Rancor D/E-5 and used it at Altar of Rancor at Den of Rancor  I/J-13.
2) Have level 9 reputation in Kazham.
3) While speaking with Jakoh Wahcondalo she does not triggering quest Everyone's Grudging. She either tell me that she's a chief or speak about Angelica letter.
4) Speaking with Etteh Sulaej also does not triggering anything, she just telling me about voices in Uggalepih Temple.
5) Re-zoning does not help.

version 30181205_0

**Comment by 59blargedy** [comment]
use the menu ingame to make a gm call, it will help solve your issue and help determine if it's a bug or an intermittent issue

**Comment by Allorddemon** [comment]
I called. GM asked to create a bug report.

**Comment by ConteAlmaviva** [comment]
> While speaking with Jakoh Wahcondalo she does not triggering quest Everyone's Grudging. She either tell me that she's a chief or speak about Angelica letter.

Do you have the quest "A Question of Taste" active? Jakoh starts and is involved in multiple quest lines, and NPCs that span multiple separate quest lines sometimes won't start or advance one quest if another they're involved in is active, similar to https://github.com/EdenServer/community/issues/5265. I've experienced the same problem with some of the SMN AF quests not triggering from Koru-Moru until I completed the Star Struck quest line.

**Comment by Allorddemon** [comment]
I thought about that, so completed "A Question of Taste" quest twice, and "Cloak and Dagger" also comleted.

**Comment by KnowOne134** [comment]
this quest has not been made yet

**Comment by KnowOne134** [comment]
as well as the quest before it 
https://classicffxi.fandom.com/wiki/A_Question_of_Taste

**Comment by KnowOne134** [comment]
corrected in the 11/19/2023 update
