### ISSUE TITLE
Meteormauler Zhagtegg has stopped spawning

### ISSUE THREAD

**Issue by Tavnazian** [EdenServer/community#5554]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

I have had my character in zone without disconnects for 4 days and he has not spawned. He should be a timed pop every 21-24 hours(Source: https://classicffxi.fandom.com/wiki/Meteormauler_Zhagtegg).
based on nothing in chat logs(i have not enabled any chat filters) about him being attacked, killed, or attacking others or using abilities. for 4 days, i have determined he has not spawned for at least that long.

**Comment by Steam-arch** [comment]
Just confirming this, it does seem that meteormauler cant spawn atm.

![image](https://github.com/EdenServer/community/assets/69089249/e5bfae9d-226a-4f4f-b782-ef0a98c360d5)

**Comment by KnowOne134** [comment]
has been corrected,
if test server says no coorinates given just means it hasnt spawned yet since server was up, so not a def answer if broken or not.
this time it was though.
