### ISSUE TITLE
Raise II and Raise III get up animation incorrect

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#5555]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver 30181205_0

Raise II and Raise III on eden have the Raise 1 animation when accepting the Raise.

Raise II:
https://www.youtube.com/watch?v=5HvwAdVbNf8

Raise III:
https://youtu.be/QTpwfWXWoYc?t=724

**Comment by falzum** [comment]
You posted the same video twice. Cool that the animations are unique

**Comment by statuseffect** [comment]
Woops my link didnt paste right 1 sec.

**Comment by KnowOne134** [comment]
Was gonna say the same thing. Nice info that they are different...and smn raise!?!

**Comment by statuseffect** [comment]
Updated.

**Comment by KnowOne134** [comment]
corrected in the 11/19/2023 update
