### ISSUE TITLE
ToAU 20 Aydeewa CS places player at entrance 10

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5556]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I am going through ToAU mission 20 "Teahouse Tumult" and triggered a CS zoning into Aydeewa Subterrane from entrance 5. At the end of the cutscene my character was at Aydeewa entrance 10.

**Comment by randomslumber** [comment]
Client ver 30181205_0

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
