### ISSUE TITLE
Sarameya missing instant tp moves during chainspell

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5557]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Sarameyas tp moves should be instant during chainspell. They behave normally on eden during chainspell.

Can see Goh and sulfurous breath to be instant during chainspell here atleast 2:40
https://www.youtube.com/watch?v=fg9PEZrJM9M

Going to try to find a chainspell hoplo later also, maybe.

Tinfoil theory: Might also have a slight GoH priority in tp move selection during chainspell based on all the goh spams, thoughts?

**Comment by 59blargedy** [comment]
resolved in may 2023 update
