### ISSUE TITLE
Sarameyas Chainspell should (most likely) lock out Magma Hoplotion and Ululation for the duration

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5558]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Can close if this is proven wrong/already implemented (was using atleast ulutation on eden during cs).

Theres a high chance that all non damaging tp moves should be locked during Sarameyas chainspell. Havent seen a single vid where it has used Magma Hoplotion or Ulutation during chainspell, and checked most of the non eye hurting ones on youtube. 

Some decent ones:
(+3 chainspells)
https://www.youtube.com/watch?v=SJX6kYmpalY
(1 chainspells)
https://www.youtube.com/watch?v=fg9PEZrJM9M
(+3 chainspells)
https://www.youtube.com/watch?v=GhE9lJVNfc8
(+3 chainspells)
https://www.youtube.com/watch?v=TsG7Kfgd06I&t=1713s
(1 chainspell)
https://www.youtube.com/watch?v=_X2u3IGCZ74

This might be why it seems to spam GoH during CS in era after 25%, because tp threshold is lowered to 1000 and TP moves are (most likely) limited to Lava spit + Sulfurous Breath + GoH

Note: One video has ulutation after chainspell ends (can tell it uses it after because the previous spell before it wasnt chainspelled anymore), another one has hoplo right at the end but this has a ready time so its most likely just a hoplo after chainspell duration ends as it stops casting also.

---------

Others: Based on retail it also might use magma hoplotion and ulutation slightly less compared to sulfurous breath & lava breath in general outside chainspell/howl (or atleast it seems like it, would need a check on retail), so wondering if the SulfBreath:LavaSpit:Ulutation:Hoplotion ratio isnt actually 1:1:1:1, but closer to 2:2:1:1 because it already has ulutation and hoplo in howl cycle. On GoH phase might be 2:2:2:1:1 or even 3:2:2:1:1 (?). This part is mostly just spitballing/theory crafting without any evidence (yet)

**Comment by Steam-arch** [comment]
Some more vids with chainspell and no hoplo/ulutations during it

https://m.youtube.com/watch?v=9tGSORXEUhM&pp=ygUNRmZ4aSBzYXJhbWV5YQ%3D%3D

https://m.youtube.com/watch?v=jB1SO5-BpII&pp=ygUNRmZ4aSBzYXJhbWV5YQ%3D%3D

I think this one is pretty much confirmed unless we want to dwell on that 0,001% chance of it being "just luck" it didnt use ulu/hoplo in the vids

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
