### ISSUE TITLE
Proto-Ultima Citadel Buster shouldnt have a ready time

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5561]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently theres a solid 1-2s ready time on Citadel Buster and with fingers you can stun it easily.

Can see it be pretty much instant here at 1:15
https://www.youtube.com/watch?v=YXRXLQv-m7Q

HP bars drop pretty much immediately citadel buster appears in the log, but remarks say its still stunnable somehow so... I assume there still is a teenyweeny window somewhere?

3:49 can see HPs drop pretty much immediately too and its a slightly newer vid so Id assume no changes been made to the ready time 
https://www.youtube.com/watch?v=1VII4GriIZw

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
