### ISSUE TITLE
NPC Magriffon in Khazam does not move

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5562]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Should walk between this
![image](https://user-images.githubusercontent.com/69089249/228680188-3dfcdcfc-8dcc-4591-8464-5c79fff79c5c.png)

and this position
![image](https://user-images.githubusercontent.com/69089249/228680254-1ec19f60-3ab8-4cd5-bb58-457ace9cd2cc.png)

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
