### ISSUE TITLE
Sam third eye merits are not halved under Seigan

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5563]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Should be 25 second recast with 5/5 third eye merits,  currently its 19-20s so they arent halved.

![image](https://user-images.githubusercontent.com/69089249/228807010-cd1d4b74-111d-465c-ae13-1d5a2fe9b435.png)
![image](https://user-images.githubusercontent.com/69089249/228807438-485eae5d-4dad-4a45-8cc6-b57c0fa9e696.png)

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
