### ISSUE TITLE
Wivre Ring missing subcraft

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5566]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Wivre Ring should have lvl 31 GSM subcraft requirement per ffxiclopedia/bgwiki/jpwiki

![image](https://user-images.githubusercontent.com/13668758/229227967-b03ae6c4-69f7-46d3-b0c5-530c240b00e6.png)

https://ffxiclopedia.fandom.com/wiki/Wivre_Ring
https://www.bg-wiki.com/ffxi/Wivre_Ring
https://wiki.ffo.jp/html/12993.html

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
