### ISSUE TITLE
Ships from selbina to mhaura can agro through floor from upper level

### ISSUE THREAD

**Issue by ThatssoKenneth** [EdenServer/community#5567]
Monsters are pasing through the floor. I am a 24 level WHM and I was on the ship on the lower floor cabin and mobs phased through the floor and aggroed me. I ended up dying and losing a level. 

### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by KnowOne134** [comment]
Corrected on 7/5/2024
