### ISSUE TITLE
Tonberry Pontifex missing Everyone's Rancor and wrong location

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5569]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

It used Everyone's Grudge instead of Everyone's Rancor, even though it was below 10% HP. 

![Pontifexclopedia](https://user-images.githubusercontent.com/54732693/229592325-e2f75bdc-f745-45e4-a449-a5a1c79463f8.png)

![pontifexjpwiki](https://user-images.githubusercontent.com/54732693/229592347-e6726be2-dd9d-446d-bc18-63422c6ec958.png)

It should spawn in the main room with the Decapitator

![pontifexlocation](https://user-images.githubusercontent.com/54732693/229592496-4040457b-ce9d-4459-a39f-f5d18825ccc6.png)

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
