### ISSUE TITLE
Potential Damselfly Worm Drop Rate Issue

### ISSUE THREAD

**Issue by FuzzyRavioli** [EdenServer/community#5570]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Helped 4 new players farm subjob items in Valkurm Dunes with two characters with Treasure Hunter 4. Drop rates on Damselfly Worm seemed MUCH lower than usual (I usually see 1-2 a round camping Valkurm Emperor), while other drops seemed normal. The players had been farming for multiple hours prior with only one drop. I realize this is somewhat subjective, but based on the opinion of both thieves, it seemed incorrect and both of us felt it necessary to report.

Version 30181205_0

**Comment by Mozzy4Ever** [comment]
http://www.ffxidb.com/zones/103/damselfly shows 6.0% with 22540 sample size at TH0. Drop rate matches the category that FFXIDB lines up with.

**Comment by FuzzyRavioli** [comment]
Some shit ass luck then. Thanks for confirming :)

**Comment by 59blargedy** [comment]
cool, ill close this out, thank you.
