### ISSUE TITLE
Attack speed of Death From Above is too slow.

### ISSUE THREAD

**Issue by inaringo** [EdenServer/community#5571]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

https://www.youtube.com/watch?v=bg8yVunvFSw for comparison

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
