### ISSUE TITLE
MNK Counter and kick attack merits might not work at all?

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5572]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Adding merits to either Counter or Kick Attacks doesnt show an increase on !getstats. 

![image](https://user-images.githubusercontent.com/69089249/230056080-c6fa3922-5885-4da5-a2dd-c38b50792c65.png)
Bhose shows correctly
![image](https://user-images.githubusercontent.com/69089249/230056128-d5f63b14-3831-4c84-8e0c-5f589e74da92.png)
Items and JA's increasing counter stance (counterstance) show an increase correctly. Counter/kick Merits just coded oddly or duds?

WAR DA merits dont show either so propably just a coding thing? Better safe than sorry I suppose! Ty for closing beforehand

![image](https://user-images.githubusercontent.com/69089249/230059075-a7a663e5-4987-4933-8540-f20aecc9231d.png)

**Comment by 59blargedy** [comment]
yeah merits (often) function differently and do not add straight mod values. merits are functioning as intended here, thank you!
