### ISSUE TITLE
Sagelord Elimination assault has NM spawn way out of bounds sometimes

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5573]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Entered Sagelord Elimination assault today, ran to the west area, and the NM initially spawned about 40 yalms out of bounds to the West:
![image](https://user-images.githubusercontent.com/95725249/230516510-2f38e3f6-2983-4f86-b719-c348d5612761.png)
![image](https://user-images.githubusercontent.com/95725249/230516552-b2aa2fed-fbf8-4d9e-85a3-5d9b6f44512f.png)

Presumably, he should spawn in bounds

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
