### ISSUE TITLE
GM entering assault area to fix bugged mob counts as extra person when assault points are awarded(?)

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5575]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Doing Sagelord Elimination, we ran into an issue where the NM spawned out of bounds (reported here: https://github.com/EdenServer/community/issues/5573)

We also submitted a GM ticket and thankfully a GM moved the mob in bounds so we could do the assault. Hurray!

However, when we finished the assault, we were awarded 1080 assault points each (I got 1188 since I had the armband) which is the reward for a 4 person party, despite entering with 3 people:
![image](https://user-images.githubusercontent.com/95725249/230518988-32cb654f-00e6-475a-b52c-e262a73bd708.png)

Next run, with the same party of 3 people, we got the correct amount of assault points of 1200 a person:
![image](https://user-images.githubusercontent.com/95725249/230519028-f9c9e2d6-4188-4da6-baad-71639dc40055.png)

Presumably, the GM going into zone shouldn't impact assault points awarded?

**Comment by KnowOne134** [comment]
corrected in 8/7/2023 update
