### ISSUE TITLE
Aerns not reraising

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5576]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Since the patch that added aerns switching to bracelets mode, I've camped Ix'DRG and Ix'DRK a few times and I haven't seen the normal aerns reraise at all.  

Occasionally I have seen a reraise animation when the aern switches from bracelet mode back to normal mode, so I am unsure if the switch is somehow "using up" the reraise effect.  Only getting exp and drops once per fight, when the aern actually dies.

Wiki claims that aern reraise rate should be at 40%.  Ix'DRK has still been reraising though.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
