### ISSUE TITLE
Cannot get Rat Race CS from Ququroon

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5577]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I think I was already on Cook-a-roon before starting Rat Race. I advanced Rat Race to Ququroon making stew, received the CS for Cook-a-roon, and completed Cook-a-roon off quest log. The next successful stew gave the Cook-a-roon CS instead of Rat Race CS. Cannot trade stew to Kyokyoroon.

Client ver 30181205_0

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
