### ISSUE TITLE
White Wind heals target based on total targets healed

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5578]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Sorry, my game crashed when I tried to open recording software to capture this, but I had the Puk below 25% and it used White Wind and went to 70%. I think maybe the AoE healing while it had its clones out replicated onto itself and it benefitted from each clone being healed. Sorry that I don't have more info at this time.

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
