### ISSUE TITLE
Mighty Strikes with WS

### ISSUE THREAD

**Issue by Atigeve** [EdenServer/community#558]
Ok have noticed that Mighty Strikes is not working with Weaponskills.  It should force crits on on all melee attacks and this includes WS (physical non magical of course). I confirmed this on ffxiclopedia and the notes go back to April 2, 2005 showing it worked with WS too.  

https://ffxiclopedia.fandom.com/wiki/Mighty_Strikes?oldid=7201

Thanks for working so hard on Eden, really enjoying the server.

**Comment by Aenge** [comment]
From scripts\globals\weaponskills.lua:

There's a flag called hasMightyStrikes that isn't properly checked in doPhysicalWeaponskill:

if (params.canCrit or isSneakValid or isAssassinValid) then
                local critchance = math.random()
                if (critchance <= critrate or hasMightyStrikes or isSneakValid or isAssassinValid) then -- crit hit!

params.canCrit is a flag on each weaponskill that is only high for ws's that can crit naturally. Mighty strikes should force all physical ws to crit, even if this flag is low. So adding hasMightyStrikes to the if statement should address that. Ie

if (params.canCrit or isSneakValid or isAssassinValid or hasMightyStrikes) then ..

There is another if statement lower in the file that needs the flag as well which affects multi-hit weaponskills.

**Comment by ccl085** [comment]
Is this supposed to be fixed ? I still see no difference between Mighty Strikes WS and non MS WS

**Comment by Shoruto** [comment]
Thanks for your question ccl085, if a submitted bug hasn't been closed then it is still in the process of being worked on or verified.  That is why it appears to have not been changed.

The developers are working hard on getting to each bug, but there are so many it takes time.

**Comment by Caelic** [comment]
Independently came to the same conclusion in this thread: https://www.edenxi.com/forums/viewtopic.php?f=10&p=6425#p6425

It's a really simple fix. Pls fix.
