### ISSUE TITLE
ToAU42 Path of Darkness lets members in when not on mission

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5580]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Client ver 30181205_0

We have been going through ToAU missions as 3 and reached 42. We all got nyzul route KI and went to Nyzul staging point for 42. Only leader was able to select mission, and I wasn't leader. When I entered the mission I received a message the nyzul route was torn up. We won the mission, and when we all went back to Sentinels only leader received CS. I never received any CS as part of mission, entering BC, winning the fight, completion.

**Comment by 59blargedy** [comment]
did everyone examine the lamp for the cutscene?

**Comment by randomslumber** [comment]
> did everyone examine the lamp for the cutscene?

I didn't but the other member of our party who was not leader and did not receive credit says they did.

**Comment by 59blargedy** [comment]
yeah, you would need to examine and get the cutscene. granted, it should not let you into the bcnm without that done so that's more of the bug than anything else.

**Comment by randomslumber** [comment]
The other member said they actually didn't examine the lamp either. But yeah leader shouldn't be able to select mission if members missing CS.

**Comment by KnowOne134** [comment]
corrected in 8/7/2023 update
