### ISSUE TITLE
Demonic Tiphia does not spam Cure V under 50% HP / Spell cast pattern is wrong

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5581]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Killed it a few times and seems to be missing unique spell cast pattern of Cure V spam under 50% HP.

![image](https://user-images.githubusercontent.com/69089249/230773940-b210dd64-2b03-47b2-8df1-83b981602254.png)

https://www.youtube.com/watch?v=lOmbvyvkf_A
atleast at 2:01 can see it try to cast Cure V twice in a row with low cd

Lots of cure V spam here too:
https://www.youtube.com/watch?v=qMpVoX19Tvs

![image](https://user-images.githubusercontent.com/69089249/230773980-c66c8555-8508-435e-a894-06a5799be277.png)

-----------------

Might need a MP pool check just incase since uniqueish big mp pool (?)
![image](https://user-images.githubusercontent.com/69089249/230773988-e2fa5f63-cb32-4b07-a458-7a971a967959.png)

-----------

Might also have a preferance to sleepga2/erase on retail (according to wiki) which doesnt seem to exist on eden, but would need to fight it on retail to confirm

**Comment by Steam-arch** [comment]
Most likely a decent mention also that she does seem to spawn fairly easily on eden, and wiki reads can often take up to 8 hours
![image](https://user-images.githubusercontent.com/69089249/230792585-4cff85ad-ba77-4292-b0c1-71ad6aea07f4.png)

But I dont think strider has even completed the imgudud respawn time/rate check yet so a shot in the dark on what the spawn % should be

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
