### ISSUE TITLE
Lebros supplies assault bug wall at left side prevents reaching NPC's

### ISSUE THREAD

**Issue by Maesedanielot** [EdenServer/community#5582]
### Checklist
We were a 6man pt trying to get lebros supplies done, after trading food items to first team at south we proceeded to go left side, but there was a wall blocking our way so we could never reach those 3 npc's. After calling a gm, one of our members also had a bug that made him unavaible of watch others or do anything, seems he was cast away from the assault. 

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
