### ISSUE TITLE
Dolls TP Move Gravity Field is overwriting haste

### ISSUE THREAD

**Issue by Snugglepunk** [EdenServer/community#5583]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Ver 30181205_0

Dolls TP Move is over writing Haste and Haste has no effect on top of it.  
As per the Monster Stats sheet that was made public + this 2009 video it should not overwrite haste.
https://youtu.be/Nh5PzEkYNGw?t=145

![image](https://user-images.githubusercontent.com/56851217/231156166-0a893bb3-2845-4545-a29f-a82091b3e2f3.png)

![image](https://user-images.githubusercontent.com/56851217/231156301-d0c27647-b44b-49de-84cd-d5a9e8898d86.png)
![image](https://user-images.githubusercontent.com/56851217/231156329-ebf0943c-3913-4ff3-ab2e-b8799ec6d8e9.png)
![image](https://user-images.githubusercontent.com/56851217/231156372-88fc67ac-1b79-43c7-b5ed-a8f728b92abd.png)

**Comment by KnowOne134** [comment]
moving to 1 big issue report with reference to this one
