### ISSUE TITLE
Puppetmaster Blues Valkeng Valoredge form too weak defensively

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#5584]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Sorry for lack of details, there are a lot of aspects of this fight I did not get to see because it was over so fast, but comparing my damage to an era video, it seems like at a minimum, the Valoredge frame needs "more defensive stats". I say that in quotes because I don't know if its PDT or Defense, but I assume it should be modeled a bit more like Ob (not exactly, but similar).

I did this fight as 75 PUP using sushi and wearing my evasion gear that is basically full evasion with only +3 attack and +5 STR. My attack is 311.

Here is a screenshot of a SAM double attacking for damage in the 20s
![image](https://user-images.githubusercontent.com/13668758/231200146-3f55e364-140d-46e5-993f-3c6dbe4075d1.png)
https://www.youtube.com/watch?v=JjX-8nZa4pU

Here is me hitting it in harlequin, and then me hitting it in valoredge
![image](https://user-images.githubusercontent.com/13668758/231200660-b48f3fd0-789f-4571-865a-4190227f3cbe.png)

More of me hitting it in valoredge
![image](https://user-images.githubusercontent.com/13668758/231200842-5693e609-bb4d-424b-b40a-047a087f4a97.png)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
