### ISSUE TITLE
ToAU mission 20 moves your character on entering Aydeewa Subterrane

### ISSUE THREAD

**Issue by orzomorzogorzo** [EdenServer/community#5587]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

When you enter Aydeewa Subterrane, you get teleported to just inside the 10 entrance after the cutscene with Aphmau and the Qiqirin. I entered through entrance 5 and ended up here (my characters fell down a bit prior to the screenshot):

<img width="792" alt="bug report screenshot" src="https://user-images.githubusercontent.com/119286035/231972729-70666403-7741-427b-b994-d14b84c84ad8.PNG">

/ver is in screenshot

**Comment by 59blargedy** [comment]
resolved in may 3, 2023 update
