### ISSUE TITLE
Commodore Tricorne job bonus recalculation on double up

### ISSUE THREAD

**Issue by bherynk** [EdenServer/community#5590]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

The job bonus added to rolls with the Commodore Tricorne is recalculating on every double up and adding/removing the bonus each time. Per the era wiki ~2008 the hat should either give you the bonus or not on the first use of the roll and if the bonus is granted it should persist on double up but I cannot verify this personally. 

https://ffxiclopedia.fandom.com/wiki/Commodore_Tricorne?oldid=752846

In this screen shot I did not get the job bonus on 4 but I did on 5 then lost it again on the 6 and 11 rolls. The first set of values was without a roll on then the next sets were 4 (25% buff no bonus) 5 (21% buff with bonus) 6 (13% buff no bonus) and 11 (31% buff no bonus).

Version 30181205_0

![Chaos roll testing with tricone](https://user-images.githubusercontent.com/130816172/232183189-6cc83a85-c4d1-49b8-9035-6e8b5f383d2a.jpg)

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
