### ISSUE TITLE
Enkelados not spawning correctly

### ISSUE THREAD

**Issue by SolidSioux** [EdenServer/community#5593]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I have camped this nm on multiple occasions over the last month sometimes spending 9+ hours and have been unable to spawn this nm. I have also been unable to find anyone that has seen Enkelados in at least two months possibly longer. Is it possible for someone to verify that this nm is spawning correctly? I know lottery nm's can be a pain and take forever and year to spawn but this seems legitimately broken.

**Comment by SolidSioux** [comment]
/ver 3.1.1.9, forgot to add that sorry.

**Comment by 59blargedy** [comment]
we ran some tests and looked into this when it was mentioned on discord a couple weeks back and couldn't find any issues. can look again.

**Comment by 59blargedy** [comment]
i didnt spot anything after another look but did confirm he is able to pop when testing the spawn/slot changes.
