### ISSUE TITLE
Call Beast pet levels are incorrect when the BST is above the pet's maximum range

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#5594]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- x] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.
/ver 30181205_0
### Details

I was in a BST burn today and at 38/39/40/41/42 I collected the Pet DEF stats from other BSTs.  At level 38, we had the Pet DEFs of: 137 and 142.  At level 39, we had Pet DEFs of 137, 139, 142, and 146, thus giving us the data of levels 36-39.  At level 40 and 41, the highest DEF anyone got was 149.
DEF: 137.  Pet level: 36
DEF: 139.  Pet level: 37
DEF: 142.  Pet level: 38
DEF: 146.  Pet level: 39
DEF: 149.  Pet level: 40

According to the familiar page/call beast pages, Call Beast “Their level varies between 0 and 2 levels below the Beastmaster (up to their cap).”
At level 42, I used call beast and these were my pet stats.
![image](https://user-images.githubusercontent.com/46233090/233848105-09b6ec71-0005-4f2d-abd3-281ddef0ef13.png)
According to the wiki, the tiger pet should've spawned at 40, not 38.

My second call beast done at level 42 resulted in a level 39 pet.
![image](https://user-images.githubusercontent.com/46233090/233848236-cf2e538c-fa7e-4215-ac88-92ee7a316b66.png)

Sources:
https://ffxiclopedia.fandom.com/wiki/Category:Familiars?oldid=249779
https://ffxiclopedia.fandom.com/wiki/Tiger_Familiar?oldid=533013

https://ffxiclopedia.fandom.com/wiki/Talk:Call_Beast
"Jug level cap question
The 0-2 levels below is based on the beastmaster's level and not the level cap of the jug right?

For example, would Funguar familiar(which is normally 65 cap) be levels 63-65 on a level 75 BST or always 65 because it's 0-2 levels below the beastmaster and not the jug cap? [Petco](https://ffxiclopedia.fandom.com/wiki/User:Petco) 15:02, 12 January 2009 (UTC)"  There were no responses.

**Comment by StriderClerix** [comment]
Level 43; after a few call beasts this is the highest pet I got:
![image](https://user-images.githubusercontent.com/46233090/233849327-81cae79f-0a4e-4ed7-ac74-51a0d4e6f60d.png)
Further showing that 142/146/149 pet def is the range for a 42-43 sync, indicating that it's currently 0-2 levels up to cap of jug, not 0-2 levels below the BST up to the cap of jug.

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
