### ISSUE TITLE
Tiamat sight angle range too wide?

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#5595]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.
VER 30181205_0
### Details

Tiamat is currently aggroing to true sight *AND* true sound at 30 yalms.  I am operating under the assumption that if she was "true sound" there would be a T(H) tag on the wiki.

Sources:
https://ffxiclopedia.fandom.com/wiki/Tiamat?oldid=800027 Just T(S),A
https://ffxiclopedia.fandom.com/wiki/Jormungand -indicates T(S) and T(H)
https://www.bg-wiki.com/ffxi/Tiamat -indicates true sight
https://www.bg-wiki.com/ffxi/Jormungand - Needs verification.

**Comment by 59blargedy** [comment]
nah, is just true sight, however the angle of detection it's set at is unnaturally large and im not sure if it's valid or not, would need retail testing.

**Comment by StriderClerix** [comment]
Unless she was bugged and not facing the way she looked like she was facing, I got aggro at 29yalms behind her tail/left leg around 135/225 degrees behind her.

**Comment by slassen** [comment]
I forgot what the setting is because I think it’s based on 255 not 360° but should be around 180° vision.

**Comment by dowzer** [comment]
Tiamat's field of vision is very narrow, I would estimate between 20-30°

Sight aggro from approximately ~30 in front

Sneak aggro from approximately ~12 behind

Checked from behind with sneak and she has true sound

https://www.youtube.com/watch?v=maM1uhR66NM

There weren't any peculiar differences between day time and night time. I'll add more if weather plays a role similar to Jorm

**Comment by dowzer** [comment]
No change during Wind weather and no sign of fog yet

Earth weather reduced sight aggro to approximately ~14 in front, no change in angle of vision, and no change from behind

https://www.youtube.com/watch?v=VE-XofO-ibA

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
