### ISSUE TITLE
G2 Limit Break NMs Respawn Too Fast

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#560]
The 3 NMs for the G2 Limit Break quest in Xarcabard respawn incredibly fast, I'm talking like 10-15 seconds.  Low levels are getting agroed right after they get their KI. I don't know what the respawn time is supposed to be but it definitely shouldn't be this fast lol.

**Comment by godmode** [comment]
Era retail the mob should die and then the ??? should be available. Then the mob should respawn relatively quickly. It is entirely possible that people would get aggro if they weren't ready to grab the key item.
