### ISSUE TITLE
Bard T2 Merits songs Foe Sirvente and Adventurer's Dirge arent usable

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5602]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Can not cast either of them on myself or on others.

![image](https://user-images.githubusercontent.com/69089249/235782046-06b75e34-7102-4ea8-8e9f-0b3f419501f5.png)

rollbacked wiki on adventurer's dirge's enmity-
![image](https://user-images.githubusercontent.com/69089249/235782421-6813950a-80dd-4d06-97d9-bb418f070cc0.png)

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
