### ISSUE TITLE
Eagle Eye Shot (EES) should not be shield blockable

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5603]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently blockable by shield on eden (ill double double check later just incase and will edit this out).  It most likely shouldnt be possible. Dowzer and his ochain couldnt remember any dynamis blocks either.

Evidence to support the claim:
- RA's in general  cant be blocked by shield (think RA also skips parry, intimidate and guard checks so would make sense it couldnt be guarded either)
- Every EES page you can find only seems to mentions it can miss (as RA's only go through evasion check)

Evidence against the claim:
![image](https://user-images.githubusercontent.com/69089249/235885299-519ca79e-f517-46c7-9bd3-99bee1772082.png)

---------------

Some wiki notes but nothing too special in there:

![image](https://user-images.githubusercontent.com/69089249/235885535-7d0df91d-1463-4dca-b75e-059bb1136767.png)

jp wiki:
![image](https://user-images.githubusercontent.com/69089249/235886307-119c6b83-f507-4ce6-a291-369ba4b773fe.png)
https://wiki.ffo.jp/html/937.html

---------------------

Feel free to add your input on he subject

**Comment by dowzer** [comment]
![wardrobenotfree](https://github.com/EdenServer/community/assets/54732693/589e8cbb-b55d-4c80-8286-bfa2b6fb426d)

My main's pld gear is locked in a wardrobe, testing with another shield that has 100% block rate with reprisal. No shield as a baseline, then checked damage wearing a shield. 

https://www.youtube.com/watch?v=jJMM9EhkBbc

For the lulz, EES in Dynamis Divergence. Pld Empyrean body +2/+3 has a glitch where it incorrectly multiplies damage

![dyndivergees](https://github.com/EdenServer/community/assets/54732693/2f35cf82-3692-4d8e-a0a7-b1723aad4a19)

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
