### ISSUE TITLE
Spirit summoning taking ~11 seconds instead of 1 second

### ISSUE THREAD

**Issue by ReportingRegret** [EdenServer/community#5605]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

https://ffxiclopedia.fandom.com/wiki/Fire_Spirit?oldid=390516 shows Casting Time for Spirits is 1 second, and has always been 1 second even if you roll back all the way to the very first wiki page https://ffxiclopedia.fandom.com/wiki/Fire_Spirit?oldid=5530.

Currently on Eden (5/3/2023), the casting bar is about 1second and disappears after 100%, but the actual casting animation continues on-screen and the spirit does not appear on-screen until after closer to 11 seconds. Begin casting 21:53:03 and spirit appears on screen 21:53:14.

Steps: Cast Fire Spirit. See casting bar go and finish but your character is still casting and no Fire Spirit appears. Wait. Fire Spirit appears ~11 seconds.

https://user-images.githubusercontent.com/94092577/236104641-9e7b39f8-38ed-4a17-8aaa-796362fbfbad.mp4

**Comment by Steam-arch** [comment]
Just throwing this in here just incase need a proof, 15 years ago 1s too.

https://m.youtube.com/watch?v=xUbDeka3D2E&pp=ygUZRmZ4aSBTTU4gZWxlbWVudGFsIHNpcGhvbg%3D%3D

Other notes for myself (theory crafting spirit viability/usability in my head with the new merits):
-Noted fire spirit never gets parad from spikes 
-Wonder if magic att merits transfer to spirits automatically
-Can see cast era fire spirit cast patterns in this vid nicely
- Spirit damage taken correct?

**Comment by 59blargedy** [comment]
Resolved may 4, 2023

**Comment by Gantofu** [comment]
Dear Dev,
Thanks for looking into the issue so quickly.  
I noticed only Air Spirit is left with casting time of 11s

**Comment by 59blargedy** [comment]
ugh, thanks, will take care of it
