### ISSUE TITLE
BahaV2 Vrtra adds should probably die when Vrtra dies

### ISSUE THREAD

**Issue by TracentEden** [EdenServer/community#5606]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I think currently on Eden the adds from Bahamut v2 Vrtra do not die when Vrtra dies. I do not have era video but do have link to video from 2012 showing that they die when Vrtra dies (see [here](https://www.youtube.com/watch?v=YHBfqLpGsp0&t=568s), credit to Siknoz for the link). If there is era video/wiki info showing otherwise would be awesome to have link to that. Thanks!

**Comment by 59blargedy** [comment]
resolved in may 22, 2023 patch
