### ISSUE TITLE
Airship from Sandy > Jeuno takes you on the Jeuno > Bastok route

### ISSUE THREAD

**Issue by iMattchoo** [EdenServer/community#5608]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

![image](https://user-images.githubusercontent.com/104252278/236426788-d324dd4d-5291-456d-b58b-be9955649dc1.png)

When getting on the Airship at Port Sandy you are zoned in to an Airship going to Bastok. Also has potential to blackscreen you when the Airship reaches Bastok.

**Comment by KnowOne134** [comment]
has been corrected 5/5/2023
