### ISSUE TITLE
Dyna-Tav leech acid mist potentially not reducing attack and ranged attack to 1

### ISSUE THREAD

**Issue by TracentEden** [EdenServer/community#5609]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I think dyna-tav leeches should be reducing attack and ranged attack to 1 (see [wiki](https://ffxiclopedia.fandom.com/wiki/Nightmare_Leech?oldid=216173 and [capture video](https://youtu.be/oQgAsMTnpSM?t=6239)).  However, I am not sure this is happening on Eden (based on anecdotes from players), I might be wrong though so feel free to close if that is the case.

**Comment by 59blargedy** [comment]
the attack down value is definitely extremely high but not currently taking a player down to 1, so thanks for the report

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
