### ISSUE TITLE
BRD songs generating too much threat

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#561]
If I pull a mob with Wind Threnody (or Requiem) and do 2 party buffs when I get back to camp, I'm probably gunna pull threat off of the tank who voked when I brought it in.. Definitely doesn't seem accurate

**Comment by godmode** [comment]
This is probably more of an issue with the enmity that is created from a puller. DSP default does not have any VE generation. I added this for Eden because it was in retail era.
