### ISSUE TITLE
Bloodpact Nightmare Doesn't Sleep Through Damage Over Time Spells

### ISSUE THREAD

**Issue by inaringo** [EdenServer/community#5610]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Not sure if problem is particular to Poison, Dia, or Bio, but Nightmare should sleep through all DoT spells.

Era wiki: https://ffxiclopedia.fandom.com/wiki/Nightmare?oldid=544137
Modern BG Wiki with some dead allakhazam links if anyone knows how to recover: https://www.bg-wiki.com/ffxi/Nightmare

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
