### ISSUE TITLE
Already existing Promyvion MR strays shouldnt link automatically when attacking Memory Receptacle

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5612]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently passive strays all come at you when you attack MR. They shouldn't link with the MR instantly if they are already up and passive. When the MR is engaged, new strays should link automatically. Can see best in jimmys video below:

Can see it here 0:35
https://www.youtube.com/watch?v=9NJJPOs_b0E&feature=youtu.be

2:29 also
https://www.youtube.com/watch?v=5RTpWlNMiDo

Important note!: Apparantly might be level dependant *needs retail research*

**Comment by Steam-arch** [comment]
Checked this matter abit, will update when more certain on (?) marked things:

Confirmed that strays do not link with each other and should not automatically link to MR. They link mostly via sight (might also have a smaller sound range implemented, totally guessing but might be set to 10 sight 5 sound). Checked every floor in Dem and Vazhl.


Other marks:

Promyvion dem 

1st floor
Strays link to MR via Sight atleast, but also pretty sure they also have a shorter sound range implemented (?)
3 strays max up at one time
When MR is engaged 1 stray spawns every 15-16s
When MR is passive, 1 stray every 3/4/5/6 min, seemed very RNG on what minute they choose (?)

2nd floor
Strays link to MR via Sight atleast, but also pretty sure they also have a shorter sound range implemented (?)
5 strays max up at one time
When MR is engaged 1 stray spawns every 15-16s
When MR is passive, 1 stray every 3/4/5/6 min, seemed very RNG on what minute they choose (?)

3rd floor
Strays link to MR via Sight atleast, but also pretty sure they also have a shorter sound range implemented (?)
7 strays max  up at one time
When MR is engaged 1 stray spawns every 15-16s
When MR is passive, 1 stray every 3/4/5/6 min, seemed very RNG on what minute they choose (?)


Promyvion vazhl

1st floor (these MRs have a crazy ammount of HP compared to promy-dem ones seesh)
Strays link to MR via Sight atleast, but also pretty sure they also have a shorter sound range implemented (?)
3 Strays max  up at one time
When MR is engaged 1 stray spawns every 15-16s
When MR is passive, 1 stray every 3/4/5/6 min, seemed very RNG on what minute they choose (?)

2nd floor
Strays link to MR via Sight atleast, but also pretty sure they also have a shorter sound range implemented (?)
5 strays max  up at one time
When MR is engaged 1 stray spawns every 15-16s
When MR is passive, 1 stray every 3/4/5/6 min, seemed very RNG on what minute they choose (?)

3rd floor
Strays link to MR via Sight atleast, but also pretty sure they also have a shorter sound range implemented (?)
5 strays max  up at one time
When MR is engaged 1 stray spawns every 15-16s
When MR is passive, 1 stray every 3/4/5/6 min, seemed very RNG on what minute they choose (?)

4th Floor
Strays link to MR via Sight atleast, but also pretty sure they also have a shorter sound range implemented (?)
7 Strays max  up at one time
When MR is engaged 1 stray spawns every 15-16s
When MR is passive, 1 stray every 3/4/5/6 min, seemed very RNG on what minute they choose (?)

Vazhl does indeed have some mixed models in strays on retail also
![image](https://github.com/EdenServer/community/assets/69089249/8cd61121-d8f8-49e7-afab-aa806006250d)

------------

Other Notes: Retail Strays always walk into 1 direction and stop soon after, they never change directions like other mobs. But they do start moving pretty soon again.

-------------------

More Other notes: Time between Empty Seeds has some varying in when it uses it, usually seems to be between 30-60s but not sure what the exact mechanic is rn

**Comment by Steam-arch** [comment]
From first glance

Strays aggro on eden, shouldnt aggro 
Stray spawn rate is wrong (higher than 15s, didnt time)
Stray Move pattern is also wrong (?)

Will update the (?)s later

**Comment by KnowOne134** [comment]
Corrected on 1/5/2024
