### ISSUE TITLE
Fei'Yin Shadow on first floor is a Doll instead

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5613]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
As I was running through Fei'Yin I see a Shadow mob has a doll's model. At the second right intersection

**Comment by falzum** [comment]
Do you have the most up to date rename file?

It can be found at the bottom of the #patch-notes channel on Eden discord

**Comment by 59blargedy** [comment]
resolved in November 19, 2023 update with a renamer change.

**Comment by statuseffect** [comment]
![image](https://github.com/user-attachments/assets/5508ac8b-7dc3-4933-98e2-1c5426903c98)
Looks to be happening again. Idk if something got revered in a previous patch, but my renamer is up to date.
