### ISSUE TITLE
Yoran-Oran not giving the quest Mandragora-Mad

### ISSUE THREAD

**Issue by benwhiteman** [EdenServer/community#5614]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
when i talk to Yoran-Oran he give dialogue about visiting the rhinostery and then says he will buy mandragora related items however i never get the quest mandragora mad in my quests and he will not allow me to trade cornettes to him

game version 30181205_0

![image](https://user-images.githubusercontent.com/32311468/236849612-77ab0b60-a182-4e3d-afba-3162673af04a.png)
![image](https://user-images.githubusercontent.com/32311468/236849683-a7d90255-a4a4-4563-a2f1-1de20ef53506.png)

**Comment by KnowOne134** [comment]
If he also does a mission or another quest you may uave active it would be blocking adding the quest. Look at logs for missions and other quests he is involved with and see iglf you have any of those

**Comment by Mozzy4Ever** [comment]
Wasn't any quest or mission conflict. 

CoP Mission = 1
Blast from the Past = Available
Mandragora Mad = Available

Verified on test server that speaking to Yoran with no conflicts results in double event response. Gives 245 which is default dialogue, then 249 which is supposed to start Mandragora Mad. Quest not started. Adding quest manually results in proper completion/repeatability

**Comment by KnowOne134** [comment]
Good info. Will look it over

**Comment by 59blargedy** [comment]
this was resolved in the may 22, 2023 update
