### ISSUE TITLE
Anniversary Ring Not Awarded from Moogle

### ISSUE THREAD

**Issue by Mu-cky** [EdenServer/community#5616]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Reproducible steps. 
1. On a character that has received an Anniversary Ring in the past, speak with the event Moogle. 
2. Check to ensure you do not have an Anniversary Ring in your inventories visually and using the Find addon.
3. Select the option, "Gimme my present, kupo!"
4. Observe the Moogle awarding a different item and not an Anniversary Ring + Adventurer's Certificate

Client Version: 30181205_0

I haven't looked into proof or era specific yet, but asked within FFXI chat and got a response that many did not receive the ring. One of the responders mentioned that Anniversary ring is always the first reward.

Update: Here is a link to the Adventurer Appreciation Campaign 2008: https://www.bg-wiki.com/ffxi/Adventurer_Appreciation_Campaign_2008

I have included images of my own experience and the chat from Discord today.
![anni issue](https://github.com/EdenServer/community/assets/94568270/7d731a85-0c7b-4362-bc47-959319aa5c79)
![anni further](https://github.com/EdenServer/community/assets/94568270/11964fff-7bfa-4390-b2e3-042a46517657)
![anni further further](https://github.com/EdenServer/community/assets/94568270/8ac8381b-9756-46de-b7fe-981f682dc529)

**Comment by KnowOne134** [comment]
has been corrected
