### ISSUE TITLE
Even More Gullible's Travels Stuck in CS

### ISSUE THREAD

**Issue by Temenos1337** [EdenServer/community#5617]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I cannot complete the cutscene in "Even More Gullible's Travels", ( opo opo crown quests in kazham ). Everytime i try to run the CS with the NPC Magriffon in Kazham i got stuck at the same point of the CS ( when you see sea serpent grotto area ). I have to crash the game to come back in front of the npc.

I have tried the usual stuff :
- Running in 30 fps
- Using printscreen to pass the CS

Game version 30181205_0

Link to the Era wiki : https://classicffxi.fandom.com/wiki/Even_More_Gullible's_Travels?so=search
Link to FFXIclopedia wiki : https://ffxiclopedia.fandom.com/wiki/Even_More_Gullible%27s_Travels

Thank you
Temenos

**Comment by FuzzyRavioli** [comment]
I also am having this exact bug.

**Comment by 59blargedy** [comment]
resolved in may 22, 2023 patch
