### ISSUE TITLE
Hostile Herbivores 

### ISSUE THREAD

**Issue by rathorse** [EdenServer/community#5618]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Attack too fast for a ninja with haste to keep shadows up. That can't be right.

**Comment by statuseffect** [comment]
Do you have era proof on how fast their attack speed should be?

**Comment by 59blargedy** [comment]
this was updated in the salvage patch and we forgot to note - their attack speed was slowed and missing regain added.
