### ISSUE TITLE
Zmn: soultrappers should not be able to be used on fortification type mobs

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#5621]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Retail testing has shown that they are able to be used, thought would be because they cannot fight back, such as brittle rocks.
Message says 

```
The "item" can not be used on that target.
```

**Comment by FariskaEden** [comment]
![image](https://github.com/EdenServer/community/assets/46270382/27b5e3aa-af62-454f-a9c2-2cec7195b308)

**Comment by KnowOne134** [comment]
corrected in 8/7/2023 update
