### ISSUE TITLE
NM Shii hits too weak

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5625]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Seems to hit slightly too weak, around 50-90 with 342 DEF, taru VIT
![image](https://github.com/EdenServer/community/assets/69089249/e100bf6a-f06f-433a-9955-4d6e4c17ffd0)

Heres a taru WHM/DNC solo who sits at around 350-366 DEF most of the time and getting hit for 70-127
https://www.youtube.com/watch?v=K3Bq2Txnj4k

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
