### ISSUE TITLE
BST AF A New Dawn - NMs don't appear to aggro

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5626]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
While doing A New Dawn I spawned Sturm, Taifu, and Trombe but they didn't seem to aggro or link. I was not sneaked or invisible. I'm level 75 so if they're level 62 I think they're supposed to aggro?

**Comment by KnowOne134** [comment]
just personally tested and is working correctly, possible was the bug due to stealth trait
