### ISSUE TITLE
Volcanic Gas not dying

### ISSUE THREAD

**Issue by Katchoo70** [EdenServer/community#5627]
Encountered a Volcanic Gas in Ifrit's Cauldron that would not die. Got to 1% Health and kept taking damage but did not die. Had Dia on did not die from that or WS damage. Tried letting go to yellow, no effect. Letting it use Self Destruct also did no effect.

**Comment by Mozzy4Ever** [comment]
Issue was resolved live

**Comment by 59blargedy** [comment]
resolved in may 22, 2023 patch
