### ISSUE TITLE
Tiamat casting during mighty strikes

### ISSUE THREAD

**Issue by TracentEden** [EdenServer/community#5628]
Tiamat is now casting during mighty strikes which I think is not retail accurate (see https://youtu.be/xU-V5DqYRBQ?t=254).

**Comment by 59blargedy** [comment]
there's currently an issue with effects-based triggers so stuff like this is going to be common until maintenance. same issue with sarameya and armed gears.

**Comment by 59blargedy** [comment]
resolved in may 22, 2023 patch
