### ISSUE TITLE
Signed in Blood (cunning earring quest)

### ISSUE THREAD

**Issue by Larwann** [EdenServer/community#563]
Today I tried to do the signed in blood quest. I have rank 3 fame for sandy so there should be no reason why Sobane gives no dialogue back to me. When I click on the npc, she responds with nothing. NPC is acting the same as the deactivated npc that are out of era, but cunning earring is definitely from era. Can someone please check this out for me? Thanks.

**Comment by Moldran** [comment]
I did this quest this weekend and it worked perfectly. Sobane will not engage in dialogue until your fame is the appropriate level. Perhaps there is a bug with the npc that suggests what rank fame you have. After several million corn hand ins, Sobane gave me full dialogue and cutscene.

**Comment by godmode** [comment]
Please comment if you can verify your fame level is correct and the quest is not activating.
