### ISSUE TITLE
Exiting MH into Port Jeuno triggered Windy airship arrival CS

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5633]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
When I exited Port Jeuno MH into zone I received a cutscene showing the Windy-Jeuno airship dock, and my character was placed on the dock. I did arrive via this airship but I was afk and don't know if I got the CS at that time.

**Comment by KnowOne134** [comment]
Will check on clearing port var after cs

**Comment by Mapi-Eden** [comment]
This happened to me today. Happened 3 times is a row. I started up streamlabs and have it recorded on twitch.

**Comment by KnowOne134** [comment]
No need I know the issue

**Comment by KnowOne134** [comment]
corrected in 8/7/2023 update
