### ISSUE TITLE
Bonnacon hits too weak + attack speed too slow

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5637]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Attacks are too weak, retail 110-169. Eden 69-122~. Attack speed is also slightly too slow compared to the video below for example. Can see theres a decent delay between attack animations on eden, much less in vid.
https://www.youtube.com/watch?v=ZHUkOX_HS7Q

![image](https://github.com/EdenServer/community/assets/69089249/7f64e3a9-d076-478b-b9e2-025a48065caa)
![image](https://github.com/EdenServer/community/assets/69089249/8ffd1ff7-81b6-42c4-8620-c83145f641c2)
![image](https://github.com/EdenServer/community/assets/69089249/4193195e-7456-4139-a9c4-226bf3324bcd)
![image](https://github.com/EdenServer/community/assets/69089249/1fb8d043-6f8f-45c3-ae80-6f0717360a79)
![image](https://github.com/EdenServer/community/assets/69089249/115c3cec-6eaf-4c00-80c6-5a77c00a995b)
![image](https://github.com/EdenServer/community/assets/69089249/4914f610-b9a3-4109-aa12-1e3be55ab585)
![image](https://github.com/EdenServer/community/assets/69089249/8ff69125-7f97-4aaa-b15e-65e199f69ba4)
![image](https://github.com/EdenServer/community/assets/69089249/4632b89e-deee-4e85-aeef-e4bb789d6205)
![image](https://github.com/EdenServer/community/assets/69089249/3c855831-a643-4496-8fd2-da54f5480e2e)
![image](https://github.com/EdenServer/community/assets/69089249/5d3f23e2-f564-411b-a26e-55e9c629a579)

similarish mnk gear to the video, I used walahra turban and 9 def fuma kyahan just incase as he swaps gear alot, no guards in any of the pics
![image](https://github.com/EdenServer/community/assets/69089249/d033df18-b107-4db2-a0c8-44e3d29fcb0d)
![image](https://github.com/EdenServer/community/assets/69089249/53be3f83-8ebd-44ed-8b2d-f12ad007b6aa)
![image](https://github.com/EdenServer/community/assets/69089249/8851f321-5d6e-4e6a-af47-0fff6a8500d6)

Edit: 169 is just a High hit, no counterstance up:
![image](https://github.com/EdenServer/community/assets/69089249/b832c66e-ba60-4aae-ab86-134f1cdf1cb5)

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
