### ISSUE TITLE
Fe'e Audit

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5639]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Immune to Slow
Very high resistance to Paralyze
Doesn't guard
Doesn't counter

https://www.youtube.com/watch?v=XCUuFs28Km0

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
