### ISSUE TITLE
Absorb-ACC (NULL)

### ISSUE THREAD

**Issue by EzeEden** [EdenServer/community#5640]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I used a scroll of acc. Item used, game crashed when i went into my magic menu, twice. Now i have (NULL) at the bottom of my magic list. I have downloaded the and replaced the DATS from the latest patch notes, as well as DAT 114 and the master.zip from Mozzys posts. Restarted the game. 

Tried on my laptop with a fresh install, and got the same issue.

Ver 30181205_0

![Screenshot 2023-05-18 095506](https://github.com/EdenServer/community/assets/133981973/c68d733a-a8b3-4f2d-8eb2-568bee04183a)
Still says (NULL).

**Comment by ConteAlmaviva** [comment]
Absorb-ACC appears to have been added in March 2008, which seems like it should be in era, purchasable from Mazween in Whitegate, but it only drops from Orcish Neckchoppers in East Ronfaure (S).

**Comment by Mozzy4Ever** [comment]
> Absorb-ACC appears to have been added in March 2008, which seems like it should be in era, purchasable from Mazween in Whitegate, but it only drops from Orcish Neckchoppers in East Ronfaure (S).

Yes it's era and purchasable from vendor in era (and currently is). Point of the bug report is because the client .DAT is incorrect for Eden and needs to be fixed so it can be cast.

**Comment by KnowOne134** [comment]
believe you have curupted your game file or the server save of your char with the crash, i was able to pop in a new char and get scroll use it and cast it without issue on edens files.

![image](https://github.com/EdenServer/community/assets/35616771/6962c4bf-251e-4aa7-8efb-8a884774ca18)

![image](https://github.com/EdenServer/community/assets/35616771/2139830f-929c-4919-97e8-6a46f1ed8d91)

**Comment by KnowOne134** [comment]
after you have reinstalled and got newest dats and still have issues open a GM ticket to further escalate your problem
