### ISSUE TITLE
Air Spirit cast time too long

### ISSUE THREAD

**Issue by AshleyAwakens** [EdenServer/community#5643]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
SMN's Air Spirit currently has a cast time that it significantly too long, it is currently about 7ish seconds with loquacious earring to cast compared to the ~1 second for all other spirits (cannot test Dark Spirit). I have the updated DATs that include the lvl 1 pet food changes.

version 30181205_0

**Comment by ConteAlmaviva** [comment]
Mentioned on closed issue here https://github.com/EdenServer/community/issues/5605 I think the last maintenance fixed all the other spirits, just Air Spirit is left.

**Comment by 59blargedy** [comment]
resolved may 22, 2023
