### ISSUE TITLE
Assault Orichalcum Survey pixckaxes dont break

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5644]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Pickaxes dont break currently. Should break according to wiki. Unsure what the rate of breaking should be as pickaxes break pretty consistently atm.

![image](https://github.com/EdenServer/community/assets/69089249/7c95f238-2adb-46be-869f-deffd17b9d54)

**Comment by KnowOne134** [comment]
corrected in 8/7/2023 update
