### ISSUE TITLE
Nuke wall seemingly too potent

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5645]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Have a couple reports that the nuke wall implemented today is too potent. Only the first nuke is doing full damage and subsequent nukes are doing way less then expected

https://media.discordapp.net/attachments/182956971668799489/1110202466387107891/image.png

https://media.discordapp.net/attachments/182956971668799489/1110204552893964309/edenxi_jNZf9GPc3f.png

**Comment by StriderClerix** [comment]
More data:
https://discord.com/channels/482610771126386688/707915352100831312/1110210126087983175

https://cdn.discordapp.com/attachments/707915352100831312/1110210125513371788/image.png 
https://cdn.discordapp.com/attachments/707915352100831312/1110210125827932261/image.png

**Comment by 59blargedy** [comment]
resolved live shortly after the may patch
