### ISSUE TITLE
enemies and allies doing double attack everyhit or even triple

### ISSUE THREAD

**Issue by Maesedanielot** [EdenServer/community#5646]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

In colibri, spider pt rngx3 with vulcan staff, all our vulcan hitted double attack in every single attack,.

Also all enemies, colibris and spiders did double or tripple attack in every single hit.

**Comment by Mu-cky** [comment]
![image](https://github.com/EdenServer/community/assets/94568270/f32c36cc-cdab-4f94-9b69-48204af9ccb8)

**Comment by Maesedanielot** [comment]
Extra info. We were a lvl sync 56 pt, during the lvl sync and after the pt broke we were capable of double attack in every staff hit.

The double attack 100% rate stopped after change weapons. Enemies kept doing double attack at spider/colibri camp

**Comment by 59blargedy** [comment]
resolved with maintenance last week
