### ISSUE TITLE
Charmed pets dont de-aggro after bst dies

### ISSUE THREAD

**Issue by Camuel666** [EdenServer/community#5649]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Several times today I have died while leveling BST in Garlaige Citadel and and my charmed pet doesnt move back to its original spawn nor does it depop when far from the spawn. I would have reraise up and upon reraising no matter how far away from the pet I was the pet would engage me and kill me again before it would start moving or depop.

**Comment by KnowOne134** [comment]
Closing due to duplicate issue found here
https://github.com/EdenServer/community/issues/4649
