### ISSUE TITLE
Windurst 9-2: Failed BC but Rank10 attained

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#565]
So, like a month ago I failed the BCNM for 9-2,
then today while helping a friend to do Fenrir Prime, I thought I might tackle it again, but the BCNM didn't show up to choose at entrance.
So I check at Heaven's Tower to see if I need to get the last CS again so I can reenter, but instead I got the completion CS and Rank10.
I'm 100% certain I failed the BCNM last time (NPC got one shot by TP attack) and didn't try again.

**Comment by slassen** [comment]
This should have been fixed awhile back. If anyone runs into this scenario again let me know in this ticket. The issue that was fixed had to do with receiving a different nation's CS in Fei'yen.
