### ISSUE TITLE
Level cap not applying properly in Sacrificial Chamber 60BCNM

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5650]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Was running Jungle Boogeymen and noticed some allies getting level 75 (uncapped) HP/MP and/or job abilities. Possibly related to using Tractor and then Raising after wipe.

**Comment by Dukilles** [comment]
Resolved by 12/14/24 update.
