### ISSUE TITLE
Nyzul not awarding appropriate assault rank up points

### ISSUE THREAD

**Issue by scorchedxi** [EdenServer/community#5651]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Nyzul is not awarding 5 points for each new set of floors cleared.
Tested on a character that has no previous assault clears.
Ran: 3x Floor 80, 1-5, 6-10, 11-15, 16-20, 21-25, 26-30

Message from Abquhbah to check points: "Hello... Seems someone has been a good little mercenary. You have some glowing reports from the Commissions Agency here. You've finally pulled yourself up to the borderline between worthless pile of beaten pulp and respectable employee."

This implies I lie between 12-18 points meaning Nyzul is only awarding a 5 point bonus for the first successful clear, totaling to 12 points. The total I should have should be 37 total points.

From Eden wiki: You earn 5 points for completing each new set of 5 floors in [Nyzul Isle Investigation](https://classicffxi.fandom.com/wiki/Nyzul_Isle_Investigation).

Source(s):
 https://classicffxi.fandom.com/wiki/Mercenary_Rank
 https://classicffxi.fandom.com/wiki/Abquhbah

Version 30181205_0

**Comment by falzum** [comment]
https://ffxiclopedia.fandom.com/wiki/Mercenary_Rank

**Comment by falzum** [comment]
https://ffxiclopedia.fandom.com/wiki/Mercenary_Rank?oldid=603516

Backdated wiki from 2008 corroborates that it's working as intended. Server day is sept 2008 so this should be the way it is

**Comment by KnowOne134** [comment]
Falzum is correct, it is working as intended. 5 point for 1st time completing and 1 point after
