### ISSUE TITLE
Lamia No. 13 Belly Dance charm cannot be dispelled on players

### ISSUE THREAD

**Issue by Mirridelle** [EdenServer/community#5652]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Version 30181205_0
Both the [Eden classic wiki](https://classicffxi.fandom.com/wiki/Assault_Mission_-_Lamia_No.13) and the [retail wiki (set to Sep 2008)](https://ffxiclopedia.fandom.com/wiki/Lamia_No.13_(Mission)?oldid=666802) explicitly state that Lamia No. 13's charm can be dispelled off of players. We went in to Lamia No. 13 assault with the plan to have myself as PLD tank the Lamia without any buffs, while mages stood outside of charm range to dispel the charm once PLD got hit by Belly Dance. As soon as the first charm landed, we spammed dispels on PLD but all of them said they had no effect. The NPC's charmed status were dispellable though.

![Mirridelle_2023 05 24_155000](https://github.com/EdenServer/community/assets/134561322/04eae2b9-29a4-4604-9dfb-91b9bd0b6ff4)
![Mirridelle_2023 05 24_155006](https://github.com/EdenServer/community/assets/134561322/8df5cbbb-9192-4e7d-945e-450d5da2780a)

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
