### ISSUE TITLE
Bugbear Watchman facing the wrong direction in newton movalpolos

### ISSUE THREAD

**Issue by commanderkeys** [EdenServer/community#5653]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The bugbear watchman are facing the wrong way at (G-9) in newton movalpolos. There are possibly other areas they are facing the wrong way as well. These bugbears are stationary and should be watching for players coming into newton movalpolos, and not having their backs turned to people coming in (because they're... watchman).

Evidence #1: posted 2007
     https://ffxi.allakhazam.com/wiki/Salacia's_Detailed_Solo_Guide_-_Lv._19-70
          section: 64-71 Newton Movalpolos - Camp #1

"The camp itself is at G-9, **just behind** the two Bugbear Watchman. They will never turn around unless you attack them.
PROS:

There is a zone partway into the tunnel **in front** of the Bugbear Watchman. You will, however, be hard pressed for survival should they see you.
The bugbears never turn around, making resting in this section very safe.

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
