### ISSUE TITLE
Alastor Antlion audit

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5658]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Some need retail checks but:

1: Only 4 executioners can spawn. Should be able to spawn 5 and after that further sandputs yield no executioners, retail checked by Dowzer.  

Wiki states +8 can be up at same time but this seems false 

Is the spawn logic correct?  Feels like it picks 1 out of 5 positions (4 executioners, 1 alastar), if it repicks an already spawned slot, it spawns nothing even if there isnt 4 executioners up.

2: On eden Alastor despawns/goes underground instantly when it goes passive due to deaggro. It should never go underground, retail checked by Dowzer.

3: On eden Executioner antlions go instantly underground when they go passive (this is maybe a common antlion problem that some antlions do. Can see one being just passive roaming here https://www.youtube.com/watch?v=Rv_AncYTLF8 time 8:55

Executioners should never go underground, retail checked by dowzer.

4: Feeler antlion deaggros, It should track by scent and not deaggro.
Can see a blm flee boot it to the zone here
https://www.youtube.com/watch?v=Rv_AncYTLF8
Also retail checked by dowzer.

5: Alastor antlion might spawn too easily (needs retail check/related to nr1)

6: Alastor antlion has wrong model atm. Should be massive. Shares model with exectutioners atm.

![image](https://github.com/EdenServer/community/assets/69089249/14dd84e2-83b5-4e41-a354-23dd8ff3769e)

Notice his big juicy booty? On eden he is flat
![image](https://github.com/EdenServer/community/assets/69089249/64789d9d-d9cf-42aa-94c6-a1811523da0c)
 
9: Executioners seem to hit abit too weak (will drop some numbers later, can pull some of the blm pentalogy thats linked in this post)
10: Alastor antlion might hit abit weak too (will drop some numbers later, can pull some of the blm pentalogy thats linked in this post)

11: Magic seems to be doing too little atm as he bops +1k quakes on non shelled blms here:
![image](https://github.com/EdenServer/community/assets/69089249/56743bfb-90e3-4dd3-9e5b-7fd285aa9a65)
Era picture us 75blm/rdm. On blm/whm on eden he does:
![image](https://github.com/EdenServer/community/assets/69089249/2fbcb3ca-5689-4f80-8710-d2dfb2255160)

12: Also needs a mdb check

-------------

Bonus 13: Is Enpetrify proc rate correct? Has pretty low proc% on eden
![image](https://github.com/EdenServer/community/assets/69089249/aa3341ab-7819-440b-9e5c-595149b3cd1b)

**Comment by dowzer** [comment]
1. Only 5 Executioners can be up at the same time. After 5 were spawned, additional uses of Sandpit spawned no adds.

2. Alastor Antlion doesn't despawn and shouldn't ever go back under ground. I suspected it might share Despot/Genbu's unique "re-aggro" mechanic, but it doesn't, it's just a slow boy who recasts Stoneskin over and over when nothing is in range.

3. & 4. None of them should deaggro.

5. Likely needs more evidence to see if it can spawn early.

Additionally, it is immune to Slow, Paralyze, Blind, Bind, and Sleep. Only Gravity was able to land. Wasn't able to confirm Elegy and Stun.

https://www.youtube.com/watch?v=D3RLBDcy2Eg

**Comment by Steam-arch** [comment]
Updated ticket abit according to dowzers post.

**Comment by Steam-arch** [comment]
I do wonder about the spawn logic though, is retail always a trench/alastor so after 5 trenches alastor is always a force pop and after those if all 6 are up it spawns nothing? 

On eden the code seems to pick an ID slot every sandpit and if that mob is already up, it spawns nothing, so you can get blanks before all executioners are up. Might or might not be correct?

Also "also casts stoneskin when out of range", psure on eden mobs spell lists arent limited if there arent any targets in range. That WOULD make great sense that spell lists are limited to self buff spells when targets are out of range 🤣

**Comment by 59blargedy** [comment]
he's referring to the idle casting when alastor is deaggroed from zoning. all retail testing so far shows that mobs will cast offensive spells even if out of range if they are aggressive and following you.

**Comment by dowzer** [comment]
I did a quick example showing a mob attempting to cast from about 35' to 40' away and it still tried to cast Dia

https://www.youtube.com/watch?v=OHwlIWUGfgk 

The strange thing with Alastor is it only casts Stoneskin when I'm further than 50' away

**Comment by 59blargedy** [comment]
oh, what deaggroed him then? he was not chasing you in that first vid when you got on your mount

**Comment by dowzer** [comment]
Sorry for the confusion, it was still chasing Karl

I switched the camera from Karl to Com, showing Alastor's out of range behaviour from outside the party

**Comment by 59blargedy** [comment]
got it, wonder if there's a range variance of over 50 for nms, thanks!

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update but dont want to lose note about NM spellcasting while aggroed
