### ISSUE TITLE
Pallas Charm OOE 

### ISSUE THREAD

**Issue by vonspar** [EdenServer/community#5659]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Ver: 30181205_0

Reproduce - Issue identified when fighting Pallas with two characters, pet had been killed and character with hate was charmed by Pallas.

Era Evidence: 
https://www.ffxionline.com/forum/ffxi-game-related/general-ffxi-discussion/67443-final-fantasy-xi-update-apr-19

https://classicffxi.fandom.com/wiki/Pallas: "In an update on April 19, 2007 to combat MPK, Pallas will no longer use charm. This is expected to change at a later date."

Worth checking on retail if this was ever reimplemented.

**Comment by dowzer** [comment]
In a video well over a year after that update, Pallas still wasn't using Charm.

In September 2008, a Samurai killed the Gigas's Bat while Pallas had over 90% HP. Later on, when Pallas was below 20% HP it summoned another bat and used Familiar instead of charming the Samurai.

https://www.youtube.com/watch?v=zbbLId8x26I

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
