### ISSUE TITLE
Moonlit Path: Fenrir Prime

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#566]
Just did Fenrir Prime and several issues occured:
He spammed TP attacks. He used at one point 6 TP moves in a row, no auto attacks between them. But usually only spammed 3-4 in a row.
Howling Moon wasn't used until ~25% but then he used it like 8-9 times and it didn't hit players within 20 yalm. 
I usually thought Astral Flow is a 20 yalm ability. I stood at ~18 and thought I'd be gone. But maybe that's a grid issue, not astral flow.
And I'm not sure if that's a Fenrir or Carby issue, but every Meteorite was resisted. We prob used it 20 times always just dealing ~120 dmg. Usually Metorite resists happen definately, but maybe at a rate of 25% to my experience

**Comment by panfunk** [comment]
Did Fenrir Prime again yesterday and above issues are still there, with the recent change to Astral Flow tho his Howling Moon was bearable with around 700dmg instead of 2k, also it appeared to only have a range of '15 yalms. He used AF 5 times.
Added a screenshot to show the TP-Move spam:
![Pan_2019 06 30_010954](https://user-images.githubusercontent.com/36666121/60398617-a939a500-9b5a-11e9-80d9-ac7bc541997c.png)

**Comment by KnowOne134** [comment]
has been rectified
