### ISSUE TITLE
Aketon and WLegs Movespeed stack

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5660]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I noticed that my character's steps seemed faster with both Crimson Cuisses and Windurst Aketon equipped. So I did a timed run to test.

60s No MS gear
55s Cuisses only
50s Cuisses and Aketon

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
