### ISSUE TITLE
Egg soup with bird egg synth has a HQ result

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5662]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Only synth with Lizard egg should have HQ "Humpty Soup" as a HQ result. Currently bird egg can produce Humpty Soup, lizard egg HQ is correctly humpty soup

![image](https://github.com/EdenServer/community/assets/69089249/5a30a040-4a18-4229-a0c4-f0c7e48f4008)

![image](https://github.com/EdenServer/community/assets/69089249/16709f46-856d-4c8f-84f6-114559d8e156)
![image](https://github.com/EdenServer/community/assets/69089249/1beb2f7e-1a0d-4d85-9652-cd58d46285ae)

**Comment by 59blargedy** [comment]
resolved in August 7, 2023 update
