### ISSUE TITLE
Citipati hits too weak

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5663]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Seems to hit too weak on eden. Never even breaks 80 on couriercrab. Hits atleast 88-144 in era vid

![image](https://github.com/EdenServer/community/assets/69089249/55aed292-e862-4714-805f-8f0d3675aa22)

couriercrab dmg taken from kaoz era vid:
![image](https://github.com/EdenServer/community/assets/69089249/9a6f2971-a51b-4577-9b9b-c42ae1239744)
![image](https://github.com/EdenServer/community/assets/69089249/51abbe5c-8617-4565-8cb0-943c6366e4ac)
![image](https://github.com/EdenServer/community/assets/69089249/1ff41132-cb9f-43d9-b536-ff3a61a3e798)
![image](https://github.com/EdenServer/community/assets/69089249/2698029a-3713-4c80-a34b-859b371acb7a)
![image](https://github.com/EdenServer/community/assets/69089249/39b07c13-92f0-4da5-86fc-e963021bc090)
![image](https://github.com/EdenServer/community/assets/69089249/dcd39553-de41-425f-a211-444844f6db0e)
![image](https://github.com/EdenServer/community/assets/69089249/07a048d6-1d33-4785-a115-02cb315caa7e)
![image](https://github.com/EdenServer/community/assets/69089249/03bef050-e684-47a5-8aa2-d681c3fd49fe)
![image](https://github.com/EdenServer/community/assets/69089249/1173908b-1158-4881-bea9-9e66f7596c97)

https://www.youtube.com/watch?v=_M_-bjyI8-g

--------

Extra note: Might be missing atleast Aeroga IIII from spell pool also, atleast havent used it when I checked 
![image](https://github.com/EdenServer/community/assets/69089249/c14a97b0-2d8c-44ab-898d-b03fa95d2a84)

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
