### ISSUE TITLE
Dynamis-Tavnazia bombs can self-destruct from 100% HP

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5665]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Can currently blow up at 100% HP dealing 6k damage if all bombs explode. Should propably follow normal cluster behavior and cant explode above 50% HP?

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
