### ISSUE TITLE
Sheep in Antlions clothing adds move underground and can be located because of it

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5666]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The mini mobs in the ENM move underground in a small area and leave track marks above, main NM doesnt move.

So you can just stand 30s in one location and see if theres any track marks there and then scan for main NM. Easy to abuse and easy to complete the enm in ~6 min every time,

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
