### ISSUE TITLE
Overwriting Specific Buff Chat Message

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5667]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Certain buffs will display the message "effect wears off" when there should be no message at all when overwriting it.

Eden examples:

Recasting Refresh on itself will display the "effect wears off" message. It should only happen if the spell runs the duration, is manually removed, or dispelled.

Overwriting Hasso with Seigen or with itself will display the "effect wears off" message. The same happens with Seigen on Eden. Neither should happen unless the ability runs the duration, is manually removed, or dispelled. 

Hasso overwriting itself:
https://youtu.be/HPDwZk9WiNg?t=9

Seigen overwriting itself:
https://youtu.be/W7C5ykmm-Yg?t=149

Seigen overwriting Hasso:
https://www.youtube.com/watch?v=ntPttj7T23U

Refresh overwriting itself:
https://www.youtube.com/watch?v=Y9sQroDcL7Y

I need era clarification for Aquaveil overwriting itself, the "effect wears off" on Eden.

I'm not sure how many other occurrences there are. 

Other spells seem to be correct, I've checked Haste, Barspells, Enspells, Protect/Shell, Spikes, Blink, Phalanx, Reraise, and how Utsusemi interacts with ichi/ni.

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
