### ISSUE TITLE
Kirin's Astral Flow should be instant

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5669]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On Eden, Kirin appears to summon immediately after using Astral Flow, but the avatar is slow and readies the pact.

The avatar should instantly use the pact without the readies chat log message. There's such a low (or zero) delay that it's able to use Deadly Hold seemingly simultaneously as it uses Astral Flow. 

https://youtu.be/y3R13bVjmVg?t=152

Lower your volume fanatics of era, it's horny:
https://youtu.be/N_2wcQHbtc8?t=43

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
