### ISSUE TITLE
Bostaunieux Obliette, Level 99 mobs.

### ISSUE THREAD

**Issue by NovadragonZero** [EdenServer/community#567]
https://ffxiclopedia.fandom.com/wiki/Wurdalak

1st time going in, see these Vampyrs spamming Dread Spikes on the log and they're level 99 mobs completely out of era. They come from Abyssea Era to unlock level 99.

https://i.imgur.com/zK20mq9.jpg

**Comment by Aujin81** [comment]
I was in there today and Wurdalak is still there.

**Comment by shawnhind** [comment]
Saw again today, still there.

**Comment by Temenos1337** [comment]
Up, NM is still there

**Comment by godmode** [comment]
If the ticket is still open then it means it hasn’t been resolved. Please do not bump tickets.

**Comment by shawnhind** [comment]
"Search to see if your issue has already been submitted. If it has you can comment on that issue instead of posting your own."

Readme should likely be updated to stop encouraging that behaviour then.

**Comment by godmode** [comment]
Fair

**Comment by Wade9363** [comment]
I killed a few of these Wuldurak's and they definitely aren't lvl 99.  Probably closer to ~72 I'd guess.

I can't remember what mobs spawned in that room they're in, but the room beyond that was the spawn point of shadow NM's Drexerion and Phanduron the Condemned.


http://ffxi.allakhazam.com/db/bestiary.html?fmob=542

Right now those NM's are spawning at H-9/H-10

**Comment by dowzer** [comment]
Arioch used to spawn in that room. There’s an old map on this page. 

https://ffxiclopedia.fandom.com/wiki/Arioch
