### ISSUE TITLE
Balthilda NPC Missing From "Brunhilde the Armourer" Shop in Bastok

### ISSUE THREAD

**Issue by Tybold** [EdenServer/community#5675]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Game Version: 30181205_0

Balthilda, the NPC who sells low-level mage armor, is missing from her location at (F-11) in the shop "Brunhilde the Armourer". The wiki confirms that she was in the game as early as 2005, and I've had multiple people confirm that they have bought from her before. Included is a screenshot of where she *should* be, according to https://ffxiclopedia.fandom.com/wiki/Balthilda

![Balthilda](https://github.com/EdenServer/community/assets/8304590/12c87ffe-7e10-4fc5-b820-ee3299792b1f)

**Comment by 59blargedy** [comment]
yep these were removed recently as they are ooe. the mention of "harvest festival 200x" is probably what's confusing you, but they did not exist in era.
