### ISSUE TITLE
Field Gear Causing Hatchets not to break

### ISSUE THREAD

**Issue by Katchoo777** [EdenServer/community#5676]
### Checklist

Currently I think Field Gear is over tuned with Logging and probably Harvesting too.  After logging for several hours in the three piece field set I had 0 breaks. Testing showed using no Field Gear got breaks as usual, just the body breaks as usual, using only the Hand or Legs I received no breaks. 

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
this was resolved live a few months ago, forgot to close
