### ISSUE TITLE
Garlaige Key does not break on use

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5679]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

**Comment by slassen** [comment]
Coffer key? Chest key? Or what kind of key?

**Comment by falzum** [comment]
Garlaige key is the item used to open the incinerator room

https://ffxiclopedia.fandom.com/wiki/Garlaige_Key

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
