### ISSUE TITLE
Pebbles throwing at instant speed.

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#568]
Delay should be 276, but that shit is like claiming with provoke.

**Comment by kochiemonster** [comment]
Arent they instant to use and the delay refers to reuse?

**Comment by tectal831** [comment]
I can't find any information that says if this is proper behavior one way or the other. Godmode, do you know?

**Comment by tectal831** [comment]
They should not be instant, neither should darts. Please look into these
