### ISSUE TITLE
Argus spawn location missing

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5681]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On Eden Argus only spawns in the rmt adjustment locations. Before the spawn location was widely expanded, it used to only spawn in the small room near the Iron Door. 

It should still be able to spawn there:

https://www.youtube.com/watch?v=ciwaLjDQq9c

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
