### ISSUE TITLE
Seiryu's building resistance to bind is too high

### ISSUE THREAD

**Issue by Snugglepunk** [EdenServer/community#5684]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

Seiryu currently builds resistance to bind to the point it's basically 100% resist rate.
Seiryu was soloable in era by skilled geared RDMs, on Eden it is not possible to solo replicating the bind method as seen in era videos.

Played with Seiryu today for a total of 45min with the following stats.
RDM/NIN, Enfeebling skill 349 + 104INT + 6 Magic Accuracy + 5/5 Ice Magic Acc Merits + HQ Aquilos Staff.  I believe this is best in slot and no more magic accuracy is possible.
Was also dual boxed with a BRD using Ice threnody for the entire fight.
![image](https://github.com/EdenServer/community/assets/56851217/132d5ff8-c6e8-4e75-977e-f7002af29681)
![image](https://github.com/EdenServer/community/assets/56851217/99b6dd9f-76d5-4bb8-8ce2-e1e4309869e6)

The first 50% Bind landed as expected, 1 resist and varying bind duration's.  
20mins into the fight and at 50% HP Bind started resisting, from here I landed only 1 bind for 3 seconds, all the rest 100% resisted. I tried spacing binds out with at least 1 min in between casts because I heard time waiting between casts reduced the resistance built.  Time did not seem to make any difference.  
![image](https://github.com/EdenServer/community/assets/56851217/51a28b4a-bde7-4a15-9e37-a8c8886a9ec3)
![image](https://github.com/EdenServer/community/assets/56851217/60236365-5638-4274-8d82-a00346f28ace)
![image](https://github.com/EdenServer/community/assets/56851217/5d241c1c-a0cf-4640-a295-cb9d93197c0c)
![image](https://github.com/EdenServer/community/assets/56851217/c31d442d-9a4d-480e-b18b-0079d4fd76ea)
![image](https://github.com/EdenServer/community/assets/56851217/b44085cd-3ba7-47ce-b70e-86f50daae2b3)
![image](https://github.com/EdenServer/community/assets/56851217/1417102f-d5af-435a-8f8e-bb7df4ee5f1e)

We can watch the famous Avesta Era Seiryu solo and he did not see any resists at all from what I can see.  You can fast forward toward the end when its very low HP and he is still landing bind for solid duration's, many repeat casts without wait times in between.   It doesn't appear to build any resistance. Bind at the end of the fight is still as powerful as the beginning.  He spams bind on cool down and lands every single one. 
Sub 50% he lands binds at these video time stamps before the video is cut to a different stage.  16:24  16:56  17:34  18:08  18:48  19:25  20:05
https://youtu.be/pqTbRTZeyo4?t=981

Again bind spam every 20-30 seconds at these video time stamps with 0 resists. 20:21  20:46  21:32  21:59  22:26  23:09  23:37  24:03  24:40  25:07  25:34
https://youtu.be/pqTbRTZeyo4?t=1219

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
