### ISSUE TITLE
When Hell Freezes over ENM Snow Devils occasionally roam around like normal mobs

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5685]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Just reporting this, but some of the ENM Snow Devils roam around like normal unclaimed mobs, Sometimes they stayed at the center normally. Didnt do anything special other than waited for meditates between waves at the start

![image](https://github.com/EdenServer/community/assets/69089249/ec54ac34-6a44-46c7-8c1e-8e23f7d3eee1)

**Comment by 59blargedy** [comment]
only 2nd + waves i assume?

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
