### ISSUE TITLE
+Combat Skill items not giving attack in offhand.

### ISSUE THREAD

**Issue by Falaras** [EdenServer/community#5686]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

Currently items like Suppanomimi or Fortitude Torque are not giving attack to an offhand weapon, although they do give accuracy.

No Suppanomimi equipped with OH Sword
![image](https://github.com/EdenServer/community/assets/55264978/81d0b572-7e45-413d-ae46-241bf5a9df81)

Suppanomimi equipped with OH Sword
![image](https://github.com/EdenServer/community/assets/55264978/3ce79657-e511-412f-aa69-4d475d05ab7f)

Dowzer confirmed it should give attack in offhand.
![image](https://github.com/EdenServer/community/assets/55264978/639bfcf7-5c94-42e7-8415-08fa79f7b900)

**Comment by Dukilles** [comment]
Resolved in 10/9 patch
