### ISSUE TITLE
 mog safe / furniture quests post#2

### ISSUE THREAD

**Issue by Helios314** [EdenServer/community#569]
My reputation is 9. maxed
I have a bronze bed installed in my Mog House. I even uninstalled and reinstalled after the last 3 failed chances to active the quest. I'm not super sad about it, because I've made some gil off the promise that this quest works. I just feel like I'm making dirty money at this point. 

Just reopening this so you know it doesn't work. I have tried everything I can think to do. 

Apollo (my wife's character) reputation 4 (only 3 required for quest) didn't get the quest to activate either. This is her first week doing it.

**Comment by panfunk** [comment]
I got my first mog safe upgrade not after tally (JST Midnight) but the next day, maybe the 'tally' for the quest is set at EST midnight on Sunday or even JST Midnight on monday. I'd suggest waiting until then and not touching the bed.

**Comment by Helios314** [comment]
Well that makes me feel better about selling the items. 

Still like I guess I don't understand what happened with the last 4 weeks. I just want to know what is wrong with my character if other people are getting the quest at this point it seems random.

**Comment by tectal831** [comment]
There was a bug that prevented it to be completed prior to the last patch. It should be good to go now. Closing this ticket. If it doesnt work, please provide additional information so we can reopen it.

**Comment by Helios314** [comment]
![image](https://user-images.githubusercontent.com/45501460/50393182-fa835a80-0719-11e9-9537-a48ece265b8d.png)
Sounds like what I was told last time. Hope it works.... or I just make another post about it. What information am I not giving you?

**Comment by Helios314** [comment]
It just activated on Helios. Not sure what was causing it to delay. It might have something to do with day of the week? idk

Thank you
