### ISSUE TITLE
Panna Cotta Attacking Nonstop (no delay)

### ISSUE THREAD

**Issue by Chodah** [EdenServer/community#5690]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that devel
![Capture](https://github.com/EdenServer/community/assets/140283047/97635747-101c-459d-a368-b2475865ce0f)
opers' research time is minimized.

### Details5_+
client version 30181205_0
I am 75BST/THF. I am camping Sewer Syrup. I logged out in Bostaunieux Oubliette (on top of Panna Cotta spawn). I log in, ready to engage the mob. I'm loading in like usual... When I'm in, Panna Cotta is attacking me and I'm almost half dead! The Panna Cotta pretty much has Hundred Fists. See attached pic. It's attacking nonstop (2-4 times/ second). It did end up killing me lol. Just dont want to walk all the way back down there and it still be bugged. Thank you.

**Comment by Steam-arch** [comment]
Its a "Known" issue but I dont think there was a proper ticket for it yet. Only 3 times I have seen it happen was also when logging into a mobs aggro radius. Doesnt seem to happen every time though so propably more to it.

Ticket
https://github.com/EdenServer/community/issues/5690 
is most likely the same bug

**Comment by KnowOne134** [comment]
Closing due to link to same bug reported
