### ISSUE TITLE
Dynamis: Vanguard Eyes should be susceptible to Stun.

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5695]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently players are unable to stun Vanguard Eyes as they fully resist the spell on Eden.  As seen in this [video](https://youtu.be/NNZ2-SB28Ps?t=347), this should not be the case.  In the chatlog, two different Black Mages can be seen casting Stun and landing the spell on two different eyes.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
