### ISSUE TITLE
game crash glitched mission

### ISSUE THREAD

**Issue by SqueeksAlaster** [EdenServer/community#5697]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
game crashed to windows after mission 2-3 clear. didn't receive KI and cannot complete.
![Nanai_2023 08 03_114959](https://github.com/EdenServer/community/assets/20497620/f5cf022b-0475-438b-a7c4-983a1d8a02fb)
character name squeeks

**Comment by KnowOne134** [comment]
Open a gm ticket in game
!menu can assist

**Comment by SqueeksAlaster** [comment]
I have tried  3 days in a row with no luck

**Comment by vonspar** [comment]
> I have tried 3 days in a row with no luck

Did you try raising a GM ticket in game?

**Comment by SqueeksAlaster** [comment]
> > I have tried 3 days in a row with no luck
> 
> Did you try raising a GM ticket in game?

all 3 days and 1 currently in queue

**Comment by 59blargedy** [comment]
confirmed help was received, closing
