### ISSUE TITLE
Sandy Mission 1-3 Save the Children

### ISSUE THREAD

**Issue by Atigeve** [EdenServer/community#570]
Clicked on the hut door to start the BC Fight for this mission, got warped in with someone else killing it (Tatortot) and now I am stuck in here.

**Comment by tectal831** [comment]
Not repeatable, think you encountered a bug. Please give additional feedback if you hear of this again

**Comment by KnowOne134** [comment]
All new bcnm system redone. Repost if issue reoccurs
