### ISSUE TITLE
Dynamis: Missing Animation on Monster Spawns

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5700]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

There should be an animation that occurs when any monster is spawned by another such as statues spawning beastmen or bosses spawning statues and beastmen.

Examples: [1](https://youtu.be/Sx-H6pozQdM?t=59), [2](https://youtu.be/ZwMahKabyTE?t=15), [3](https://youtu.be/A5FNMNPL_TI?t=38).

This animation also occurs when a monster such as an NM or zone boss triggers the spawn of additional enemies or "repops" as seen [here](https://youtu.be/d7dDJm-NSlg?t=82).  Also based on this video, it seems that statues when spawned in can immediately become aggressive and trigger the spawn of their children.

**Comment by DeuceFFXI** [comment]
After I noticed that when Beastmaster's summon a jug pet the same animation gets played I decided to do some digging.  Fortunately, it wasn't too hard to find using AltanaView.  It's the "Call beast (summon)" effect or more specifically the file located at ROM\97\113.DAT

In addition, this same animation should be played on mobs that are summoned by Ramparts in salvage after using reinforcements.

![mobSpawnAnimation](https://github.com/EdenServer/community/assets/61279359/d977ea63-a025-43ff-8e72-ae3037f606e4)

If needed, I can make an additional bug report for reinforcements in salvage.

**Comment by statuseffect** [comment]
Doesn't look like we get the HP or MP stat animations either. Which is the benediction animation. Which is in example 1.

**Comment by DeuceFFXI** [comment]
> Doesn't look like we get the HP or MP stat animations either. Which is the benediction animation. Which is in example 1.

It's been bug [reported](https://github.com/EdenServer/community/issues/5683#issue-1788655408).

**Comment by 59blargedy** [comment]
resolved by another dev in July 5th, 2024 patch
