### ISSUE TITLE
Dynamis - Beaucedine: Attestation NMs should be susceptible to Stun.

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5701]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On Eden, Attestation NMs fully resist stun, this should not be the case.

- [Quiebitiel](https://youtu.be/EoHQPCx-3F4) - Can be seen stunned multiple times in this video alone.
- [Velosareon](https://youtu.be/5qKzrJowV1U?t=280) - Is stunned at this timestamp.  Chatlog is a bit difficult to read, but if put at 25% video playback speed it should be easier to read.  Stunned again later in the video.
- [Goublefaupe](https://youtu.be/yNsnsKnqv4E?t=25) - Once again, slow the video playback speed down and stun can be seen taking effect in the chatlog.  Additional stuns follow after.
- [Goublefaupe #2](https://youtu.be/U943fZXjeOU?t=104) - RDM/DRK using chainspell stun without getting resisted.

Unable to find footage of the other two attestation NMs; however, based on the other three NMs being stunnable, I imagine all should be stunnable.  I'm uncertain if currently these NMs on retail differ from how they were in era, but retail testing may be warranted to see if there's any additional issues.

**Comment by DeuceFFXI** [comment]
Just found a [post](https://www.bluegartr.com/threads/41718-Attestation-Run-Help?p=1413560&viewfull=1#post1413560) from Blue Gartr which mentions Magic Shield preventing Goublefaupe from being stunned.  So, it seems that they will resist but only under certain conditions.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
