### ISSUE TITLE
Elel doesnt have a minimum respawn time and despawns at 5:00

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5704]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Respawns rather quickly on eden, can repop within minutes. Also stays up to 5:00

![image](https://github.com/EdenServer/community/assets/69089249/c4d6f6aa-19aa-4f72-8b9a-222ac2088c08)

Wiki suggests 2h respawn time, but in reality might be set to abit less to suit night cycles, but who knows.

![image](https://github.com/EdenServer/community/assets/69089249/a34bd740-1139-4c35-852f-fe0b10d79547)

Also set to respawn at 5:00 instead of 4:00 like the old xolotl

**Comment by 59blargedy** [comment]
resolved in august 22, 2023 update (need to add patch note, forgot!)
