### ISSUE TITLE
Jug pet Ready moves that scale to TP in recent patch do 0 Damage

### ISSUE THREAD

**Issue by Smalfio** [EdenServer/community#5705]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Using Sabre Siravarde jug pet claw cyclone ready move does 0 damage with 0 TP and also with 1k tp and 3k tp. I used it on multiple mobs much lower lvl than the tiger

![Alfio_2023 08 07_095202](https://github.com/EdenServer/community/assets/118784488/e86eed40-e8e8-4813-8d35-e10be2650673)

ver 30181205_0

https://ffxiclopedia.fandom.com/wiki/Saber_Siravarde?oldid=533074

**Comment by Smalfio** [comment]
Antlion Familiar, LifedrinkerLars ready moves are doing more than 0 dmg
Humunculus head butt is doing 0 dmg too

**Comment by 59blargedy** [comment]
can you check again? made some live changes (thanks and sorry)

**Comment by Smalfio** [comment]
they seem to work now, thank you!

**Comment by 59blargedy** [comment]
sweet,  closing this out.
