### ISSUE TITLE
Salvage: Cells disappearing upon entering inventory

### ISSUE THREAD

**Issue by Axelution** [EdenServer/community#5707]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

![image](https://github.com/EdenServer/community/assets/72828303/fcfa2dce-c383-4327-95b7-9099ffd1ef02)

This only occurred with the humilus cells in Bhaflau Remnants. As soon as it exited the treasure pool and entered my inventory, it blipped in and out, visibly taking up a slot for a microsecond, then disappearing all of the sudden. This was happening on my character only -- everyone else was able to use their humilus cell, and it only happened with humilus cells.

![image](https://github.com/EdenServer/community/assets/72828303/ad4549e3-8972-4c83-9f0c-dead68cffa3f)
![image](https://github.com/EdenServer/community/assets/72828303/646e529a-c9d3-4d28-823e-041e6eaf6886)
![image](https://github.com/EdenServer/community/assets/72828303/859e69a3-03c4-401f-ab04-1df9bce4ccdb)
![image](https://github.com/EdenServer/community/assets/72828303/63fc9ce8-18a8-48d7-91be-8f61ab1b8110)

After the run, 4 of them finally showed up in my inventory as I was getting rid of cells
![image](https://github.com/EdenServer/community/assets/72828303/e616e758-a534-449f-bbae-a838c34a6d0f)

**Comment by MeshGearFox** [comment]
I was in a group that experienced issues with cells disappearing in Bhaflau Remnants also. In our case, it was various equipment cells. I noticed early in the run that I was missing a couple of cells I'd lotted, but chalked it up to user error. Later in the run, another member was missing cells immediately after we saw him obtain them in the chat log. The cells reappeared in inventory after leaving the run.

**Comment by MeshGearFox** [comment]
I had a single character logged in. The other person had two characters logged in and in the run.

**Comment by Axelution** [comment]
I had more than one character logged into the run. Even though the 2 cells I lotted and tried to use before disappearing fell to me, I noticed that my alt had a couple that I didn't remember lotting. I wondered if they somehow jumped inventories, but they could have been extras that just fell to the alt -- too much going on then to be certain.

**Comment by MeshGearFox** [comment]
I can't say with absolute certainty that my issue wasn't user error, such as someone else lotting the wrong cells. I haven't reviewed logs to see if that might be the case. The other member who had two characters in the run definitely had cells disappearing after they dropped to him.

**Comment by Axelution** [comment]
Same issue happened with an undulatus cell and congestus & velum cell in SSR and ZR, but can confirm that relogging fixes the issue and the cells reappear in your inventory and are usable afterward.

**Comment by MeshGearFox** [comment]
Happened to another member in my group with radiatus cells in SSR. He obtained one and it disappeared. I lotted one and put it in my bazaar and it disappeared from his inventory after he bought it. He did not have two characters in the run. I'm not sure if he had a second character online.

**Comment by DeuceFFXI** [comment]
> If you see again can you logout and in and let me know if resolves or not. And the people this is happening to did you have more than 1 char logged in and were they in the run as well

Did a run last night and had someone with this issue logout and then back in.  Cell was in their inventory after doing this.

**Comment by Lilswitche** [comment]
Two members of our run had this happen in Bhaflau during our run with Stratus cells. We attempted to sell a Stratus cell via a bazaar and that one disappeared as well. I question if it's occurring in Bhaflau because the amount of cells that are dropping and being kicked out of the pool all at once?

**Comment by Deirdre5017** [comment]
Just an FYI, this happened to our group in SSR too with a Humilus cell. Of the three HP cells that dropped from the fomor RDM in Hammerblow Majanun's room, 2 cells went to single boxed characters with no issue but the one that lotted by someone dualboxing disappeared from his inventory. Relogging did make the cell reappear but, when he used it, it removed his HP down but either didn't get used up or duplicated the cell itself. The Humilus cell left in his inventory was both bazaarable and usable by a second person.

**Comment by Steam-arch** [comment]
Propably enough details here already, but pretty sure this happened with a bazzaared cell also with my group.

Cells not showing in inventory seems to be vey common though and almost every run atleast 1 person needs to relog

**Comment by Mozzy4Ever** [comment]
Also of note, have -NOT- seen this happen in Arrapago despite many runs with people dual boxing.

**Comment by falzum** [comment]
Seems to happen when using a cell, and another cell drops from treasure pool into your inventory

**Comment by Dukilles** [comment]
We have a fix in for this as of today. Can reopen this issue if our fix doesn't catch all occurrences. (if it happens again)
