### ISSUE TITLE
Seismostomp damage from the Dynamis bosses is too high

### ISSUE THREAD

**Issue by asphodel-eden** [EdenServer/community#5708]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver: 30181205_0

After the recent update, the dynamis boss stat's damage from Seismostomp is too high (and inaccurate). 

Here are recent examples from dynamis runs on Eden:

![InkedPicture1](https://github.com/EdenServer/community/assets/61460959/b5e1c5bb-3820-4a43-b1f0-f682a0bbba45)

![InkedPicture2](https://github.com/EdenServer/community/assets/61460959/8a73dba7-80b4-480b-96e5-b4f0b0c89102)

In the image above, the 1263 damage is with SS. 

And here is an era video (posted August 2007) that shows the Dynamis-Bastok boss's, Gu'Dha Effigy, damage from Seismostomp

https://www.youtube.com/watch?app=desktop&v=qJYozDgD_jg

![image](https://github.com/EdenServer/community/assets/61460959/4b1ea9f9-0d8e-41a3-bb1a-cfbcb5775a41)

(Raytheon is a caster (either blm or rdm) and only gets hit for 333 points of damage from Seismostomp).

**Comment by DeuceFFXI** [comment]
Took similar damage from the Sandy boss yesterday.  Multiple people hit for over 1100 dmg including two for over 1450.  I certainly don't recall seisomostomp doing this much damage in retail.  The problem always was the boss hitting you with two or three in quick succession that would start killing people.

**Comment by DeuceFFXI** [comment]
[Windurst Boss](https://youtu.be/bqY8Rc0G0qE?t=77) - Stomps twice, no damage in logs, but HP oh alliance is somewhat legible.
[Jeuno Boss](https://www.youtube.com/watch?v=N2yqtTvMdmo) - Stomps once, harder to see alliance HP

I'm fairly certain I've come across other videos of large statues doing seismostomp in Dynamis, so I could try to look for those as well if needed.

From what was posted before and these two videos, I'd say it's safe to say stomps from zone bosses are maybe doing 50-100% more damage than they should.  As it seems to hit players for about 700-900 damage unmitigated other than defense from gear and protect.

**Comment by 59blargedy** [comment]
this was fixed live August 10, 2023

**Comment by Mozzy4Ever** [comment]
![image](https://github.com/EdenServer/community/assets/11255886/7d803741-7e54-44af-a848-3f312afdf711)
First Seismo looked about right but the 2nd and 3rd were... not so kind

![image](https://github.com/EdenServer/community/assets/11255886/18ba520a-1dcb-405f-aa6e-c7285a7ca31d)

![image](https://github.com/EdenServer/community/assets/11255886/0653fb21-8dad-4a2e-a59a-931012ea688f)

Of note is that Longhammer is in bravura aftermath and full PDT
