### ISSUE TITLE
Arrapago Remnants floor 1 drop rate doesnt increase on kill

### ISSUE THREAD

**Issue by Maesedanielot** [EdenServer/community#5709]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
this mechanic, assuming you're referring to the "kill x number of qutrubs to increase drop rate of draugars" is in place and working, though drop rates in general will be getting a bump on early floors.

**Comment by 59blargedy** [comment]
qutrub/draugar drop rates for floor 1/2 were increased live august 10, 2023
