### ISSUE TITLE
Arrapago Remnants Floor 3 lamia dropping gold beastcoins and pickaxes

### ISSUE THREAD

**Issue by Maesedanielot** [EdenServer/community#5713]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
this was fixed live August 10, 2023
