### ISSUE TITLE
Salvage port up heal not checking if player dead

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5714]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Porting up in Salvage is putting dead people's HP at full while still dead. Player is still raiseable though.

**Comment by 59blargedy** [comment]
resolved in previous update
