### ISSUE TITLE
Zhayolm Remnants - Archaic Chariot respawns Archaic Gear + Gears multiple times

### ISSUE THREAD

**Issue by MeshGearFox** [EdenServer/community#5716]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Client Version: 30181205_0

We teleported to the 6th floor of Zhayolm Remnants. Our THF attacked the Archaic Chariot to pop the Archaic Gear/Gears. He kited around the room until all mobs deaggroed. Our group proceeded to kill all of the Archaic Gear/Gears. After killing all of them, we attempted to kill the Archaic Chariot. As soon as the Archaic Chariot was attacked, all of the Archaic Gear/Gears respawned.

In era, the Archaic Chariot was always the last mob we killed before porting up to the boss floor. It shouldn't respawn gears for a second time.

Here's a [link](https://ffxiclopedia.fandom.com/wiki/Zhayolm_Remnants/Boss_Walkthrough?oldid=374949#Sixth_Floor) to an era walkthrough for a Zhaylom Remnants boss run that advises killing all of the gears before the chariot.

**Comment by 59blargedy** [comment]
resolved live august 11, 2023
