### ISSUE TITLE
Exiting Aht Urhgan Whitegate mog house after using Nashmau boat loads you back on the dock

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#5717]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

![image](https://github.com/EdenServer/community/assets/65121606/e44c64a7-211f-4a43-9fe7-bdf88a050931)

If you rode the boat to Aht Urhgan Whitegate from Nashmau, then go into the mog house and exit back out to the city, it will place you under the fountain while you get the boat docking cutscene with no boat and place you back on the boarding dock.

Reproducible steps:
• Ride the Nashmau -> Aht Urhgan Whitegate Ferry
• Go to the Aht Urhgan Whitegate Mog House
• Exit back out into Aht Urhgan Whitegate

Video:
https://youtu.be/TAutKd0OCrU

**Comment by 59blargedy** [comment]
this was corrected in the last update
