### ISSUE TITLE
Seismostomp range is incorrect

### ISSUE THREAD

**Issue by asphodel-eden** [EdenServer/community#5719]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver 30181205_0

Currently, it appears the range of Seismostomp from Dynamis bosses on Eden is ~15 yalms. In the era video below, at timestamp starting at 3:01, you will notice the player is 12.9 yalms away and doesn't get hit with Seismostomp. 

https://www.youtube.com/watch?app=desktop&v=qJYozDgD_jg

Here are some screen captures from the video that show Egon (the one recording) standing 12.9 yalms and not getting hit with the stomp: 

![image](https://github.com/EdenServer/community/assets/61460959/a0a879b1-c024-4dd4-ab3a-a4d539c6a716)

![image](https://github.com/EdenServer/community/assets/61460959/b8e96a16-5497-40b9-899d-3c40cdd60b2c)

My guess is Seismostomp should be a 10-yalm tp move.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
