### ISSUE TITLE
Ronfaure OutPost Warp Bugged

### ISSUE THREAD

**Issue by Ganbatte92** [EdenServer/community#572]
Hi

Earlier today I completed the outpost ronfaure warp. I am able to easily warp back from Ronfaure's outpost to Northern Sandy with no problems, but in an attempt to go from Northern Sandy back to West Rounfare's, I have found a bug.

As soon as I confirm my 80 conquest points with the NPC to go to West Ronfaure, my character suddenly vanishes and all I can see is my character's name. I am STILL in Northern Sandy, and it has not zoned me. I have to zone into the nearby moghouse to see my character again. 

Thanks for all your efforts so far with Eden (it's amazing!)

**Comment by godmode** [comment]
Duplicate of #512
