### ISSUE TITLE
Zhayolm Remnants: HP/MP cells not dropping from 3F South Mamool 

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#5720]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [N/A] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Cleared the entire south side of the 3F to spawn the Poroggo Madame and we did not get a single Spissatus or Humilus cell to drop from the Mamool. Either a very questionable drop % in the drop table or they are missing. 

Expected Behaviour: Hp or Mp is a relatively common drop from each Mamool on the south side.

**Comment by Lilswitche** [comment]
http://www.ffxidb.com/zones/73/mamool-ja-spearman
http://www.ffxidb.com/zones/73/mamool-ja-zenist
http://www.ffxidb.com/zones/73/mamool-ja-strapper
http://www.ffxidb.com/zones/73/mamool-ja-bounder

**Comment by 59blargedy** [comment]
resolved in august 22, 2023 update
