### ISSUE TITLE
Zhayolm Remnants 2F NE Draco Lizards drop table.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#5721]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [N/A] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Received a single Virga Cell drop (Rings) from a Draco Lizard. Undulatus/Virga Cells in this room should always 2 cells at a a time when they do drop. 

Wiki page also mentions it should drop in sets of 2. 
https://ffxiclopedia.fandom.com/wiki/Zhayolm_Remnants

KnowOne capture for reference: https://youtu.be/JRbnmgcsNjw?t=1859

[Bluegartr post](https://www.bluegartr.com/threads/42012-Salvage-Zhayolm-Remnants?p=1905422&viewfull=1#post1905422) that mentions that Rings/Ranged can only drop in pairs. A couple posts later another person mentions how their group got screwed by only have 1 pair of Rings and 1 pair of Ranged cells drop without getting a Ring/Ranged from the starter chest.

**Comment by Lilswitche** [comment]
Did another Zhayolm run and we got a single undulatus drop from a Draco Lizard as well - it's not just Virga Cells that need adjusting. 

Also, [FFXI DB](http://www.ffxidb.com/zones/73/draco-lizard) for Draco Lizard has a about a 1:1 ratio between Cirrocumulus and Virga+Undulatus cells combined. e.g. For every 8 Cirrocumulus from Draco Lizards, on average you would see 4 Undulatus and 4 Virga. The drop data on FFXIDB points to the drop slot for Cirrocumulus and Virga cells being 100%, even though KO's capture clearly had a Draco lizard that didn't have that drop slot activate.

**Comment by Lilswitche** [comment]
![image](https://github.com/EdenServer/community/assets/41595732/a12caad9-bb34-44b0-844e-fd0325cf495e)

Looking at the table data for Draco Lizard it will include both the NE and SE rooms for sample size. If we localize the Cirrocumulus cell data alone (36926), that should be the number of NE Draco Lizards killed; we then see that Undulatus and Virga Cells combined account for 19517 + 19196 = 38713 drops. Knowing that the Cirrocumulus are not subject to TH where the Virga/Undulatus might be, it implies that the rarity category for Virga/Undulatus should be 'Common', as Very Common would be too high, and Uncommon would be too low to match these numbers. 

Also, 
![image](https://github.com/EdenServer/community/assets/41595732/1411654b-99c3-4946-87d1-1317d0541674)
The TH + TH2 numbers for both of the cells also point to a Common rarity.

**Comment by Goutan** [comment]
Just to add to this - here are the cell drops from the capture video from that room:

Lizards	
Cirro: 8
Virga: 6
Undu: 2
Mamool
Cirro: 2

**Comment by Garphilius** [comment]
The capture video by KnowOne show the cell drops:

Lizards
Cirro: 8
Virga: 2
Undu: 2

Mamool
Cirro: 2

Currently on Eden, Virga and Undu are only dropping singles, not in pairs how it should be. This is making popping 3 Pathos NM on the later floor almost impossible. 

We have now done ZR about 5 times and we are also noticing this pattern from NE as stated by Lilswitche.

**Comment by Slamm21** [comment]
https://www.bluegartr.com/threads/42012-Salvage-Zhayolm-Remnants?p=1906089&viewfull=1#post1906089

comments here show unless you had rather bad luck you never had an issue getting enough rings/ranged to pop the floor 5 frog.

**Comment by Raphtalia1** [comment]
https://youtu.be/I9xJ8y8UYB8?t=507 

NO TH

4 Rings (dropped in doubles)
2 Ranged (dropped in doubles)

**Comment by Slamm21** [comment]
https://youtu.be/I9xJ8y8UYB8?t=534
in raphs video, notice the Savant drops 4 cells
https://www.bg-wiki.com/ffxi/Zhayolm_Remnants
like bg wiki says `"The Northeast room [Mamool Ja Savant](https://www.bg-wiki.com/ffxi/Mamool_Ja_Savant) (WHM) will drop 2 [Cirrocumulus Cell] (Back/Waist) and 2 of one of the others."`

there are 2 issues right now
1) should drop in doubles, Eden is singles
2) savant should drop 2 back/waist along with either 2 hand, 2 body, 2 ranged or 2 ring

**Comment by Slamm21** [comment]
opening the crate you have 50% chance of ranged as one of the slots is. You get 0-2
"2x Humilus (HP), Spissatus (MP), Undulatus (Ranged) or Cumulus (Body)"
ring chance 1/6 in chest
"2x armor or stat cells other than the four above" there are 7 stats and 5 armour not in the 4 so it's 2/12 = 1/6

Savant = 25% chance to drop 2 ranged, or 25% chance to drop 2 ring

so before we count the lizards on average you would have 1 ranged and 0.666 rings

It's worth noting a fair few groups in era did not bring a THF to this zone
with TH4, the drop rate on the 8 lizards which drop must be 45% for the pool of both pairs, so 22.5% each
this gives 1.8 rings and ranged on average
total 2.8 ranged on average and 2.4666 rings

so with a bit of luck, one of those was 3, you duped the other and was good to go for the floor 5 frog

**Comment by DeuceFFXI** [comment]
Finally commenting on this after running Zhayolm on retail over twenty times collecting drop data that can be found on this [spreadsheet](https://docs.google.com/spreadsheets/d/1dQ3ExnPUJQzEeJ3z5iYojTkuGJ-D_CSCxrmXl1EgCc4/edit#gid=302535065).  XIDB is full of inaccurate data due to the methods in which it was collected over the years.

As has been stated, the four Draco Lizards which drop Cirrocumulus cells can also drop two Virga and Undulatus cells.  The Mamool Ja Savant, which spawns after all eight Lizards have been defeated, can drop two Virga, Undulatus, and Cumulus cells.  The Draco Lizards can only drop ONE cumulus cell.

All cells which are NOT 100% guaranteed should have a Very Common drop rate (24%).  Thus, with Treasure Hunter while unlikely it is still possible for players to not get enough Virga and/or Undulatus cells from the five mobs that can drop them on the second floor.

To reiterate:
**Draco Lizards**
- Cirrocumulus x2, 100%
- Virga x2, 24%
- Undulatus x2, 24%
- Cumulus x1, 24%

**Mamool Ja Savant**
- Cirrocumulus x2, 100%
- Virga x2, 24%
- Undulatus x2, 24%
- Cumlus x2, 24%

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
