### ISSUE TITLE
Zhayolm Remnants 5F Ramparts in Poroggo Madame rooms aggro.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#5722]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The Airchaic Ramparts in both of the 5F South and North Poroggo Madame rooms currently aggro. Expected behaviour is that they should not be aggressive. 

[Era Proof](https://www.youtube.com/watch?v=oSWEJxvl5HA&ab_channel=MarcRodwell)

**Comment by 59blargedy** [comment]
resolved in august 22, 2023 update

**Comment by Lilswitche** [comment]
North side ramparts still aggro on Eden. Patch only indicated South side ramparts were adjusted.

**Comment by Lilswitche** [comment]
Ran Zhayolm Remnants last night and did the 5F South Poroggo Madame and an Archaic Rampart still aggrod us.
