### ISSUE TITLE
Both salvage exits not working at same time

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5723]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Only 1 salvage exit portal works at a time. Seems to be random which. Zone says I lost but it's full of lies! I got to the portal damnit. 

I have no evidence saying they both should work and honestly after all the shenanigans, it wouldn't surprise me if SE was like "heheh lets make 'em 50/50 for just not having a loss message despite winning"... still tho

**Comment by Mozzy4Ever** [comment]
Fastest close ever. Fuck SE, it's supposed to be this way.

**Comment by DeuceFFXI** [comment]
So, I'd have to guess that which portal works might be dependent on the direction that was taken while climbing the floors.  It could be entirely random, which is a huge troll, but it's not like there's any benefit to actually exiting is there?

**Comment by KnowOne134** [comment]
None
