### ISSUE TITLE
Salvage Arrapago Remnants 4th Floor Booth & Flayer NM shouldnt link to lesser mobs

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5724]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently both Booth NM and Flayer NM links to the lessers. Propably should not link. Could use a video evidence still.

bg wiki:
![image](https://github.com/EdenServer/community/assets/69089249/3bf704fb-7f89-4694-91d4-8fefdd6c5399)
![image](https://github.com/EdenServer/community/assets/69089249/d0636b5d-b8a7-4879-8d67-fe138f4e32a5)

![image](https://github.com/EdenServer/community/assets/69089249/8edbcf29-f214-4939-af39-347132d69eb2)

https://www.youtube.com/watch?v=8Pl5xfe1dcw&t=432s

Not definite proof but 4:30 the NM aggros and the mini flayer doesnt link immediately, propably walks closer to tacocats range and normally aggros via sound

**Comment by 59blargedy** [comment]
resolved in august 22, 2023 update, psycheflayers already didnt link
