### ISSUE TITLE
Ovinnik hide might have an incorrect drop rate

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5725]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Careful request to check Ovinnik hide's drop rate. Went around 2/70 on live + test. Might be set to something lower than what DB/enclopedia/TH chart reflect. Maybe easier to check from the matrix rather than to mindlessly kill tigers.

![image](https://github.com/EdenServer/community/assets/69089249/8fb0b0fb-0de1-43fd-a292-3761bcdd7d80)
![image](https://github.com/EdenServer/community/assets/69089249/23ea1faa-12af-42db-9c61-42b6daa36d4f)

**Comment by 59blargedy** [comment]
resolved in august 22, 2023 update (need to add patch note, sorry)
