### ISSUE TITLE
Arrapago Remnants - Gespenst drop rates should increase akin to Qutrub/Draugar mechanic.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#5726]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [N/A] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently, Gespenst have static drop rates and they do not increase based on Qutrub kills. 

[FFXIdb Drop tables](http://www.ffxidb.com/zones/74/gespenst). They should be able to drop 2 Virga Cells and at a high rate once rate increase is triggered.

**Comment by Lilswitche** [comment]
I may be mistaken about the increase in drop rate due to Qutrub kills, but the drop rate of Virga cells should nonetheless be very high. 

Very early [livejournal entry by Aurik](https://aurik-ffxi.livejournal.com/27874.html) describing drops rates of cells and zone mechanics even before most of the zone mechanics were discovered. He describes the VIT and Virga Cells as dropping at a high rate while also describing the Draugar HP/Waist cells as poor.

![image](https://github.com/EdenServer/community/assets/41595732/3b0fc915-961f-414d-a827-9302ae71c8e9)

**Comment by Lilswitche** [comment]
According to [FFXIDB](http://www.ffxidb.com/zones/74/gespenst), TH3+ drop rate is 108% with confidence interval +/- 4.4%. Because it's a double drop, 54% chance on average with TH3+ on kill. Likely a Common rarity where Eden's Gespenst have a far lower drop rate.

**Comment by DeuceFFXI** [comment]
Here's my [spreadsheet](https://docs.google.com/spreadsheets/d/1dQ3ExnPUJQzEeJ3z5iYojTkuGJ-D_CSCxrmXl1EgCc4/edit#gid=302535065) which contains drop data for Gespenst.   All recorded kills/drops were done without TH.

1st Floor
- Congestus (~18%)
- Virga x2 (~20%)

2nd Floor
- Inconclusive, lacks enough data

3rd Floor
- Congestus (~20%)
- Virga x2 (~24%)

When combining data from all three floors, both cells dropped above 20% of the time, which leads me to believe both cells should be Very Common from Gespenst.  I have found nothing to support the idea that any other mobs aside from Draugars and Qutrubs share their increased drop rate mechanics.  It would take a lot of testing to prove one way or the other.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update (but no increase from draugar/qutrub kills)
