### ISSUE TITLE
Arrapago Psycheflayer Spissatus cell drop rate too low.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#5727]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [N/A] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Expected drop rate is significantly higher than Psycheflayers on Eden. [FFXIdb table](http://www.ffxidb.com/zones/74/psycheflayer) shows it as being a Common drop category. This is primary reason people normally farm a few Psycheflayers when doing the south path.

**Comment by 59blargedy** [comment]
resolved in august 22, 2023 update
