### ISSUE TITLE
Kuftal Devil Manta's droprate appears too low since the udpate

### ISSUE THREAD

**Issue by Corvinus1337** [EdenServer/community#5729]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

ver 30181205_0

Recent update may have messed up droprate on Angel Skins from Devil Manta in Kuftal tunnel.  Over the past 40 hours I have gone 8/105 on Angel Skins with TH4. I've been a fairly regular fisher and I have never seen the droprate go this low considering it should be a 18% droprate with TH4. Over the course of the last 6 months with >1000 mantas fished, I can attest that the droprate previously was ~18% with TH4 but this is not the case now.

Is it possible to audit this on the test server and/or live? I think n = 105 is a high enough sample size for live at least since it's extremely time consuming to fish these "for science." I don't have access to the test server so can't check there.

Thanks!

**Comment by Oir11** [comment]
I have also noticed that there is what appears to be a dip in the drops. I have spent the last few days out there by myself and with over 50 manta I've got a total of 4 skins. I know that it is random at times but this seems far worse than I ever remember. It would be interesting to test just to see.

**Comment by 59blargedy** [comment]
the rate hasn't changed since it was created. we ran a test spanning 10k drops and drops were as expected. cannot think of a scenario where live would have an issue but test would not, did as much due diligence as possible and closing ticket.
