### ISSUE TITLE
Salvage Bhaflau Remnants Skirmish Pephredo wrong model

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5730]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently shares model with  Hunting Wasps

Should be a red sporty bee like this:

![image](https://github.com/EdenServer/community/assets/69089249/2bc2f2c7-1dbf-4687-82a7-3b57dbc8b267)

**Comment by A-nomaly** [comment]
Not sure if its a coincidence or it got swapped, but Gate widow has the colors of what the Skirmish Pephredo should look like. The model from retail is a regular Aht Urhgan Attercop.
![image](https://github.com/EdenServer/community/assets/77242296/a1ef9610-264e-4cab-acbb-48a28ef67b9f)

**Comment by 59blargedy** [comment]
resolved in august 22, 2023 update
