### ISSUE TITLE
Quest: Pieuje's Decision

### ISSUE THREAD

**Issue by Daywhite83** [EdenServer/community#5731]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

It is not a big deal or anything but during the quest "Pieuje's Decision" for the White Mage AF Body, after obtaining the Tavnazia Bell, when zoning into Fei'Yin for the cutscene, it put me on the stairs which is behind the zone line. When i ran down the stairs to do the quest it zoned me back outside, since that is where the zone line is. I just thought id let yas know about it.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
