### ISSUE TITLE
Zhayolm Remnants F1 Puks dropping nothing

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5732]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Past the first room, the F1 Puks in Zhayolm don't have anything in their drop table. Notes section at the bottom of https://www.bg-wiki.com/ffxi/Zhayolm_Remnants#First_Floor state that in subsequent rooms beyond 1st, first two mobs on widescan in room will drop cells.

**Comment by 59blargedy** [comment]
resolved in august 22, 2023 update
