### ISSUE TITLE
Auction House: Dyer's Woad missing

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5736]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

This item is not listed under either Alchemy page or Clothcraft.  The two main wikis have it listed under Alchemy 1 currently.

https://www.bg-wiki.com/ffxi/Dyer%27s_Woad
https://ffxiclopedia.fandom.com/wiki/Dyer%27s_Woad

For whatever reason, SE initially placed Dyer's Woad under Clothcraft.

https://ffxiclopedia.fandom.com/wiki/Dyer%27s_Woad?action=history

If you look at the wiki history for the item, you can see the change after December 8th, 2008.  Below is a link to the official patch notes for the December 2008 version update.  They seem to confirm this oddity.  So, I guess category placement depends on if we want it to be era accurate.

http://www.playonline.com/pcd/verup/ff11us/detail/3893/detail.html

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
