### ISSUE TITLE
Black Coney using Dust Cloud Instead of Snow Cloud

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5737]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Snowy area bunnies, including black coney should use snow cloud instead of dust cloud. Black Coney currently using dust cloud.

From Wiki: 
![image](https://github.com/EdenServer/community/assets/69089249/5dc0932f-9602-4b9b-8338-13f1dbb76974)

![image](https://github.com/EdenServer/community/assets/69089249/93320d2d-e322-4e0e-b063-0d167c72b537)

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
