### ISSUE TITLE
Dot effects can be erased while charmed 

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5738]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Was able to erase the for effect from Brainjack last night.

Brainjack is used by Long-Armed Chariot in silver sea remnants. 

Afaik you shouldn't be able to erase debuffs from charmed players.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
