### ISSUE TITLE
Auction House: Rusty Medal missing

### ISSUE THREAD

**Issue by clebs** [EdenServer/community#5739]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Client version: 30181205_0

According to the wiki [here](https://classicffxi.fandom.com/wiki/Rusty_Medal) the Item Rusty Medal should be under **Other > Misc.** in the Auction House but it is not.

It is used for [this](https://classicffxi.fandom.com/wiki/Fist_of_the_People) quest. I was able to start the quest.

I have not tested if the item is dropped by [Wajaom Tiger](https://classicffxi.fandom.com/wiki/Wajaom_Tiger).

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
