### ISSUE TITLE
Bhaflau Remnants incorrectly dropping Nemain's Slops instead of Nemain's Sabots

### ISSUE THREAD

**Issue by doughnuteden** [EdenServer/community#5740]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Today my salvage group ran bhaflau remnants and received the nemain's slops drop twice. After the runs I went ahead and double checked because i seemed to recall those dropping in Arrapago. This is a chatlog for one drop

![image](https://github.com/EdenServer/community/assets/132183590/43236bee-3c44-4abc-ab79-cf5fb8788c0a)

And one for the other drop.

![image](https://github.com/EdenServer/community/assets/132183590/efec8244-8d9a-4a01-9b48-30345f82f335)

And these are wiki posts for the Nemain's Sabots (should be in Bhaflau) and the Nemain's Slops (should be in Arrapago)

https://ffxiclopedia.fandom.com/wiki/Nemain%27s_Sabots?oldid=671675
https://www.bg-wiki.com/index.php?title=Nemain%27s_Sabots&oldid=396776 (era posts don't include the drop location unfortunately)

https://ffxiclopedia.fandom.com/wiki/Nemain%27s_Slops?oldid=583510
https://www.bg-wiki.com/index.php?title=Nemain%27s_Slops&oldid=59252

**Comment by doughnuteden** [comment]
I went back and found a chatlog from an Arrapago Remnants run on the 23rd.

![image](https://github.com/EdenServer/community/assets/132183590/80168888-e6f6-4dba-8f32-5f29fba91db4)

Seems like slops is dropping in both zones so only Bhaflau needs to be fixed.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
