### ISSUE TITLE
Battleclad Chariot (Zhayolm Remnants) Dropping Cotton Coin Purse instead of Linen

### ISSUE THREAD

**Issue by Croftings** [EdenServer/community#5743]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- x[ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

![coin purse2](https://github.com/EdenServer/community/assets/66039475/6cfa4ab8-85ce-4835-bd3d-93879d28be3b)

Should be dropping Linen Purse instead of cotton coin purse, according to FFXI Wiki/FFXI Classic wiki.

**Comment by Garphilius** [comment]
Same just happened to us today.
![Garphilius_2023 09 24_114040](https://github.com/EdenServer/community/assets/57615904/4bf93e5b-35e3-48ea-8da0-e4ddb120867f)

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
