### ISSUE TITLE
Dynamis - Beaucedine Fomor Aegis chism is a -99.99% Armor reduction

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5745]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Drops Defence to 1 every time in Dynamis-Glacier.  Jimmy marks it to be a -75% Defence down, unless the fomors there are special...?
![image](https://github.com/EdenServer/community/assets/69089249/a4e1dcee-ce5b-4c1f-9a67-f8bca035f92c)
![image](https://github.com/EdenServer/community/assets/69089249/a81fb21d-8520-4674-84e4-66db37f031fe)

Some mob in that area also does a -100 acc down (not blind), harsh on paper atleast.  Unsure what mob/skill it is as fomors/hounds/eyes dont seem to have other than blind in their tp skill list...(?)

**Comment by 59blargedy** [comment]
cant replicate this, need more information, consistently get 75% defense down. are you using food? do you have dia on? etc etc

**Comment by 59blargedy** [comment]
ah, it's when berserk is applied and then aegis schism or vice versa. nothing to do with the skill itself. not sure if bug will have to retail research if 75% is of your total current defense or your max defense. assume it's going to be former, but needs to be checked.

**Comment by 59blargedy** [comment]
aegis schism + berserk also equals 1 defense in retail, closing ticket
![image](https://github.com/EdenServer/community/assets/52636208/7d93b503-a6ea-4166-8d02-471e75442ac4)
