### ISSUE TITLE
Kawahori Kabuto Blind is -0 acc

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5746]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Blind is usable but the debuff itself gives -0 acc

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
