### ISSUE TITLE
SMN should have a larger widescan radius

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5748]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

To help with YYR?

Going to need more confirmation than this, interesting nonetheless

[SMN75/RNG11](https://img.photobucket.com/albums/v498/hawkfangor/smnwidescan.png)
[DRG75/RNG11](https://img.photobucket.com/albums/v498/hawkfangor/drgwidescan.png)

**Comment by KnowOne134** [comment]
75 blm/ 11 rng
![image](https://github.com/user-attachments/assets/d990bbc3-cc9e-40cd-9f2f-4782fc4056df)

75 smn/ 11 rng
![image](https://github.com/user-attachments/assets/7550dc8b-5e00-4377-a2ec-9788f4b20b71)

75 war / 11 rng
![image](https://github.com/user-attachments/assets/73c9afe2-6ea8-466b-ae8d-0831d96aedfe)

**Comment by KnowOne134** [comment]
all look to be the same to me now
