### ISSUE TITLE
Marids most likely respawn  too fast

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5749]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Respawns at 5 min currently, atleast in wajaom. Wiki states 15 min. Unsure about bhaflau marids
![image](https://github.com/EdenServer/community/assets/69089249/6aeb7838-d0e0-49c5-a280-dc36851512ce)

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
