### ISSUE TITLE
Linkshell Name Glitched

### ISSUE THREAD

**Issue by JerichoReigns** [EdenServer/community#575]
I purchased a linkshell the other night before bed, and while I was looking at the color charts to figure out the best color I tabbed back over to the game and it confirmed the color I did not want. 
So i refarmed the 8k to purchase another, bought the new one, dropped the old miscolored one, then upon trying to confirm the color intended with the new shell its giving me a message saying the name was in use still even though I have discarded the shell. Is there anyway Godmode or a GM assist in clearing the ghost name so I could finish creating the LS? Thanks for the work, -Jericho

**Comment by Setz0r** [comment]
there is currently no support in the code for handling deleting a linkshell...  this will require a pretty massive overhaul to the core system, so this issue will need to be put on the backburner.
