### ISSUE TITLE
Rock Bottom quest requiring NQ and HQ Mythril Pick to complete

### ISSUE THREAD

**Issue by AlFastrider** [EdenServer/community#5752]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Client Version 30181205_0

Followed the steps for the quest from [the Wiki](https://classicffxi.fandom.com/wiki/Rock_Bottom).

-Clicked the blank spot in Mount Zhayolm, received first cutscene
-Traded a Pickaxe to the blank spot, received second cutscene
-Zoned and then re-entered the area
-Traded a Mythril Pick to the blank spot and nothing happened

Contacted a GM who told me that it seemed to be requiring a NQ and HQ Mythril Pick to complete, instead of either one. Was advised to open a ticket.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
