### ISSUE TITLE
JAs should instantly kill chigoes

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5756]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently chigoes dont die on Job Abilities.
![image](https://github.com/EdenServer/community/assets/69089249/cb610c31-953c-4829-8d5c-99b84df1f32c)

![image](https://github.com/EdenServer/community/assets/69089249/cf0e1773-93d0-4fa2-b7db-1f48eb5ab028)
![image](https://github.com/EdenServer/community/assets/69089249/9f56eac0-d8a6-48d6-9702-8a954fe717c4)

1:54 SAM/DNC uses box step on a chigoe and it dies
https://www.youtube.com/watch?v=JBLVrh8Mw7U

**Comment by 59blargedy** [comment]
Resolved in december 15, 2023 update
