### ISSUE TITLE
Can leave Mamool Ja Staging Point with Assault orders

### ISSUE THREAD

**Issue by LaurelEden** [EdenServer/community#5757]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Can bypass the need for a Runic Permit using Mamool Ja Assault orders

![Laurel_2023 09 20_172538](https://github.com/EdenServer/community/assets/145617205/9983e468-87d1-4870-ac80-5f2e41108a9b)

Lebros for example:
![Laurel_2023 09 20_172308](https://github.com/EdenServer/community/assets/145617205/4bf3920c-1d60-4222-9fac-bbd2944796df)

![Screenshot 2023-09-20 173057](https://github.com/EdenServer/community/assets/145617205/ae947d88-c576-4f1a-8ed3-8c2b1d0346d7)

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
