### ISSUE TITLE
Princess Pudding in Arrapago Remnants Floor 2 SE Seems to Have Smaller Model

### ISSUE THREAD

**Issue by Garphilius** [EdenServer/community#5759]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

It seems like the model size for Princess Pudding on Floor 2 SE side of Arrapago Remnants has a smaller size when it's size should be a bit bigger as in the capture by Knowone: https://www.youtube.com/watch?v=fGKq5QeA3KE&t=630s

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
