### ISSUE TITLE
Third Eye + Seigan various issues

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#576]
Seigan itself seems to be granting the ability to counter, rather than Third Eye granting the ability to counter only while active **with** Seigan.
Third eye fails to overwrite itself if you manage to use it in the brief window that sometimes occurrs between the cooldown coming back and the effect wearing off. This window can also be created/extended by meriting third eye recast. It should overwrite itself.
Third eye is not properly absorbing physical weapon skills. It appears that only the first and last hits anticipated by a given use of third eye will absorb weapon skills from enemies. If an enemy weaponskill that should be absorbed occurs between these first and last hits while third eye is active, it instead does normal damage and third eye is ignored entirely.

**Comment by GalkaZajin** [comment]
Also wanted to add to this, that SAM can have Utsu shadows and third eye up at the same time, this should not be possible.

**Comment by erenik** [comment]
Can agree to the issues of the brief window of Third eye failing to overwrite itself.

**Comment by erenik** [comment]
Suggested fix for the brief window where Third eye fails to recast. In Dsp the Power of 3eye is updated to match the duration, and when compared on cast if the duration is not 0 on the server it won't activate, see screenshot. 

This fix changes the overwrite behaviour from the status effect power comparison to Always, solving at least that bug.
![Screenshot 2019-05-19 13 24 35](https://user-images.githubusercontent.com/6832027/57981715-a025c600-7a3b-11e9-9641-60e451067364.png)

[0001-Third-eye-overwrite-always-greater-than-for-effect-f.zip](https://github.com/EdenServer/community/files/3195020/0001-Third-eye-overwrite-always-greater-than-for-effect-f.zip)

**Comment by erenik** [comment]
Proposed fixes for Seigan/Third eye counterattack under review, would suggest opening a new ticket for the WS/TP move absorption issue or detailing further, as I am unsure on the details there

**Comment by MGramolini** [comment]
I know it’s annoying but is third eye supposed to overwrite itself when recast?  Remember there are merits to lower recast time, so if it’s a skill/lag issue and not improper coding of the ability I’m not sure it should be changed.

**Comment by FallenXI** [comment]
Yes it's supposed to overwrite

**Comment by Serephim** [comment]
I have also noticed that third eye is not blocking multi hit physical TP moves as well sometimes.
Here is a screenshot of it not working....
![Serephim_2019 05 27_043444](https://user-images.githubusercontent.com/43891789/58441823-3d73a080-80b3-11e9-837c-33cd13bb4d00.png)
And here is a screenshot of it working.....
![Serephim_2019 05 27_045524](https://user-images.githubusercontent.com/43891789/58441827-50867080-80b3-11e9-8974-9be16e750202.png)

**Comment by erenik** [comment]
Found ref where Third Eye blocks Combo in Maat fight: https://www.youtube.com/watch?v=PzV3oMsp14Y

**Comment by godmode** [comment]
So it should completely absorb all hits of every WS if it’s up?

**Comment by FallenXI** [comment]
Pretty sure that is correct, yes.
