### ISSUE TITLE
No Grand Marids in Wajaom?

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5760]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Close if unneccessary, but do Grand marids exist in wajaom currently? Only seen them in bhaflau, but havent dabbled around with some of the marid spawns. Chigoes in wajaom didnt induce rabies, but bhaflaus did so maybe they were forgotten from the Grand Marid patch aswell.

![image](https://github.com/EdenServer/community/assets/69089249/e83be350-c68a-4f9e-868d-9a5e7fb6dc38)

**Comment by 59blargedy** [comment]
looks like they have the same chance as bhaflau ones to pop, closing
