### ISSUE TITLE
Mining and harvesting points stack together

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5761]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Unsure if correct/incorrect, but I would assume incorrect. Mining points and harvest points atleast can stack on top of each other on eden. Anyone able to verify that they are/arent supposed to stack?

**Comment by dowzer** [comment]
It appears they do stack, likely the same with harvesting as well

https://www.youtube.com/watch?v=3Jq4zc4Hm5c

**Comment by Steam-arch** [comment]
Kk gonna close ty ty!
