### ISSUE TITLE
Dynamis Lord Evasion is too high

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#5763]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
30181205_0
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Could not reset 2hrs the other day after some fragments so I hit DL with Apoc instead of KC, immediately noticed his evasion is wrong.
He should have 344-359 eva according to Jimmayus testing in the monster stats sheet. I assume this would be 359 on Eden.
He has 403 evasion on Eden, so you need 493 acc to cap instead of 449

I assume this is just a typo in his base evasion value before AGI from race, job and sj as his AGI is 100. So if someone accidentally put the evasion in for him after AGI so he gets the +50 from AGI twice, he would have 409 so can't be that
I can't tell since !statcheck does not show base eva before stats. Considering the 44 difference, there must be a typo in the base evasion even if there is also one for his AGI ranks.

pictures attached
![Slamm_2023 10 01_180333](https://github.com/EdenServer/community/assets/5552081/d0ff21ff-a827-476e-812e-c2b5f568826a)
![image](https://github.com/EdenServer/community/assets/5552081/25acbf65-fd5b-404f-8ac4-91660725101e)

**Comment by Slamm21** [comment]
looking deeper into this, thanks Jimmayus as always.

Evasion for a level 90 DRK/DRK is 310 (C rank)
he should have 101 AGI (says 100 on Eden)
His race is A, job and sj are DRK which is a D
50 for race
34 for main job
17 for sub job

=310+50 = 360

so he should have 360 evasion and that matches with the guess of up to 359

**Comment by 59blargedy** [comment]
Resolved in december 15, 2023 update, though not to 360. DL will need a retail retest to determine.
