### ISSUE TITLE
Distance Correction Accuracy Penalty

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#5764]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Something seems to be up with distance correction in regards to accuracy. It seems like Eden might have a % correction in place like the old slugwinder days before that was changed to the correct -50 for ws. Furthermore I'm not sure if the +100 for relic and quested ranged ws is on Eden? this was found by makise and discussed on test in 2020. Right now Namas arrow is missing way too much. Namas on DL had 50/50 hit rate which despite his current evasion issue should be very inprobable, and this is seen everywhere. A dyna dunes parse has 1 Namas at 88% and the other 93% despite when both should be easily capping. Even in cities where the mobs have tiny eva this is happening.

To clarify the only reliable data I know of on accuracy loss from distance is here
https://wiki.ffo.jp/html/9286.html

it says 

> accuracy , regardless of weapon type, the farther away you are, the lower your accuracy will be.
> However, it is not directly proportional to the distance,
> At the gun 's proper distance of 5 Ym , the accuracy is about -35, and there is a rapid attenuation when you move just a little away from the edge of close range .
> Ranged accuracy is about -70 at 15 Ym , which is a little far from the appropriate distance for a longbow.
> At 20 Ym, which is the limit for remote WS , the accuracy is -80, and the decay becomes gentler as the distance increases.
> 
> As mentioned above, the "appropriate distance" is set separately for damage and hit rate , but it is the "appropriate distance for damage " that is usually talked about. The hit rate is ``close contact = appropriate distance'' for all long range categories, probably because there are few opportunities to talk about it.

in summary no matter what ranged weapon you have, accuracy is reduced the father away from the mob you are, so with a bow for example if you stand in correct distance to negate the attack penalty, you still get a penalty to ranged accuracy, roughly -50 in the correct position. 

So Sidewinder would get approx -113 total because it gets -50 from the ws itself, whereas Namas or Empyreal arrow get +100 from ws so would be at +37 approx.

Slugshot would get approx -90 total because -50 from ws itself and roughly -40 from the correct position, whereas  Coronach and Detonator would be at +60 approx.

Since we only have values for certain distances, I've created a guestimate chart based on those values which seems to line up
![image](https://github.com/EdenServer/community/assets/5552081/cf1a0d2d-68a8-4840-9e16-06111dc2f6ca)

**Comment by 59blargedy** [comment]
the assumptions in this bug report were all false, but assuming the change in block/guard to ra will see a higher acc rating for you in dyna zones.
