### ISSUE TITLE
Minstrel's ring is not calculating HP+% or 'Converts MP to HP' gear in its formula when detecting players HP%.

### ISSUE THREAD

**Issue by failffxi** [EdenServer/community#5766]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Minstrel's ring is not calculating HP+% or 'Converts MP to HP' gear in its formula when detecting players HP%.

Unlike the 'Sorcerer's Ring', the 'Minstrels Ring' does not care if you use HP+, HP+% or Converts MP to HP, all that matters is that the player is at 75% HP and TP<1000 regardless of how you get there.

ver. 30181205_0

In my top gearset, I can cast my songs at around 45% castbar whilst at 75%HP.  (1177/1580 HP)
In the bottom gearset, I cast my songs at around 65% castbar whilst at 70% HP. (1186/1706 HP)

![image](https://github.com/EdenServer/community/assets/41841824/96c2802c-fc72-48d7-bb3d-9f0219b83404)

It seems the ring is only calculating base HP+xx gear when checking a players HP%. Putting my base HP to 76%, then adding +6%HP (gold moogle belt + Shiekh legs) and an extra 30HP from 'Cassie Earring' instead of a 'Crimson Earring' does not allow the Minstrels Ring to work, despite the player now being at a lower HP%.

![image](https://github.com/EdenServer/community/assets/41841824/a0cb4859-a573-4cba-8a4e-0eb8db4bbf62)

As can be seen on the wiki, any forms of 'Converts MP to HP' (including HP+% equipment ) is not treated specially and should work the same as HP+xx gear.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
