### ISSUE TITLE
/check level ranges incorrect

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#5767]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ X] I have provided my client version in the details. (type /ver into your game window)
- [ X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

This seems to be an issue branching off of the exp changes in the last patch.

I am seeing DC mobs at lv58 while on a level 75 job, and level 1 mobs are checking DC to a level 8 job.
https://ffxiclopedia.fandom.com/wiki/Check?oldid=708594

according to this entry on wiki:
Decent Challenge Abbreviation: DC

A Decent Challenge enemy is 1-2 levels below you at level 1, or 1-7 levels below you at level 75.
These enemies give at least 50 but less than 100 experience points before modifiers.

![image](https://github.com/EdenServer/community/assets/62901732/5e0dd24f-8b91-4863-9d51-22c86b74c5cb)
This is just one instance on my level 75 warrior but it seems to carry for every mob currently. Notice how the lvl 55 mob checks as Too Weak.
This level 58 mob should check as easy prey as it is 17 levels under me.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
