### ISSUE TITLE
Arva not removing Adventurer Coupon from inventory after trade

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5769]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Trading Arva the Adventurer Coupon will result in gaining 50 gil, but it does not remove the Coupon from your inventory letting you trade it to her infinitely:
![image](https://github.com/EdenServer/community/assets/95725249/723d8b99-7174-480f-a513-6049839a5f2c)

Arva should remove the Coupon from your inventory after the first trade.

**Comment by KnowOne134** [comment]
has been corrected
