### ISSUE TITLE
Shrieker in Carpenters' Landing should not link

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5770]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Currently, Shriekers in Carpenters' Landing will link with eachother:
![image](https://github.com/EdenServer/community/assets/95725249/b6b06d6c-c150-40c2-847f-d50f7a32cb86)

According to both FFXIclopedia and BGWiki, the Shriekers in CL specifically should NOT link (but they do in Ordelle's Caves):
https://ffxiclopedia.fandom.com/wiki/Shrieker?oldid=700852
https://www.bg-wiki.com/index.php?title=Shrieker&oldid=64809

**Comment by KnowOne134** [comment]
corrected in the 11/19/2023 update
