### ISSUE TITLE
Salvage - Zhayolm Remnants: Poroggo Gent & Madame are not True Sight or Sound and therefore susceptible to Hide.

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5771]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

In this bug report I will prove:
1. Poroggo Gents are not True Sound/Sight
2. Poroggo Madame are not True Sound/Sight
3. Hide works on both mobs.

Please refer to this retail [capture](https://youtu.be/rE6ukMV969g?si=UmRGB0QIyc9gxC_A&t=1494) of Zhayolm Remnants.  In this video, I tested the aggro mechanics of Poroggos on the 4th and 5th floors including the Madames.  Sneak and Invisible were both effective in avoiding detection from both the Poroggo Gents and Madames.  Hide can also seen to be quite effective at dropping aggro from Poroggo.

The [ffxiclopedia](https://ffxiclopedia.fandom.com/wiki/Poroggo_Gent?oldid=771299) page for Gents falsely states that Poroggo in Zhayolm Remnants are true hearing.  As seen in the video above, they should detect by Sight, Sound, and Linking.

The behavior I captured from current retail is corroborated by several posts in the [era Zhayolm Remnants forum thread](https://www.bluegartr.com/threads/42012-Salvage-Zhayolm-Remnants) from BG.  Below are two examples of discussion surrounding pulling the Poroggos.
- [Post 1](https://www.bluegartr.com/threads/42012-Salvage-Zhayolm-Remnants?p=1651053&viewfull=1#post1651053) Several subsequent posts that corroborate current retail behavior.
- [Post 2](https://www.bluegartr.com/threads/42012-Salvage-Zhayolm-Remnants?p=2168548&viewfull=1#post2168548)

Also, searching these posts and overall thread with "hide" will demonstrate that players in era talked about a THF using hide being an effective strategy for pulling the Madames without the need of a sac pull.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
