### ISSUE TITLE
Salvage - Arrapago Remnants: Orobon droprate/list

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5772]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Per retail captures, Orobon, ID 17080536, should drop the following cells when killed:

- Radiatus x2 (100%)
- Cumulus x2 (<15%)
- Pileus x2 (<15%)

So far, I don't have enough data to completely narrow down the droprate of Cumulus or Pileus cells from Orobon.  At the least they appear to be uncommon.  None of the wikis list Pileus cells as a potential drop, but that is likely just incomplete information due to the spawn mechanics of this mob.

![Salvage Arrapago Orobon CumulusCells](https://github.com/EdenServer/community/assets/61279359/621477c7-324c-4e28-a45e-7acff54fb9e9)

![Salvage Arrapago Orobon Pileus](https://github.com/EdenServer/community/assets/61279359/89b77681-ae6f-4fb5-9e8b-4ee0eccc7b7f)

[Video 1](https://youtu.be/4dVTnIgn5yg?si=L7guTajqM89K2tKY&t=4607) - Cumulus cells dropping
[Video 2](https://youtu.be/oto-dKmcVrY?si=YSI7ldZ8t4QtUbkv&t=5189) - Pileus

[Drop Data](https://docs.google.com/spreadsheets/d/1dQ3ExnPUJQzEeJ3z5iYojTkuGJ-D_CSCxrmXl1EgCc4/edit#gid=302535065) - Spreadsheet containing drop data.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
