### ISSUE TITLE
Salvage - Arrapago Remnants: Archaic Chariot occasionally drops 5 cells instead of 6.

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5773]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Uncertain if this is a bug; however, twice in the last two weeks my Salvage group has encountered an issue in which the Archaic Chariot failed to drop all SIX of it's guaranteed cells.  One instance it only dropped 1 Virga, the other it dropped 1 Stratus.

![Salvage Arrapago 5th Eden Chariot 1Virga](https://github.com/EdenServer/community/assets/61279359/93f5e7f5-e5dc-4346-9732-d5c0eae018c5)
![Salvage Arrapago 5th Eden Chariot 1Stratus](https://github.com/EdenServer/community/assets/61279359/925fdc13-ee8f-4389-a957-bc360aacc690)

Unfortunately, I forgot to take screenshots both times, so a snippet of my logs is my evidence of this occurring.  Both times our treasure pool was reasonably full, so I'm not sure if that's related.  And in case there's any doubt about the droprate, my [data](https://docs.google.com/spreadsheets/d/1dQ3ExnPUJQzEeJ3z5iYojTkuGJ-D_CSCxrmXl1EgCc4/edit#gid=302535065), which contains 17 recorded kills shows a 100% drop rate for all cells.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
