### ISSUE TITLE
Salvage - Arrapago Remnants: Archaic Rampart (1F) only spawns after 10 Lamia/Merrow are killed.

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5774]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Currently, the 1st floor Rampart spawns randomly.  So, I'm providing [verification](https://youtu.be/oto-dKmcVrY?si=0ZtfGiMeWyfPrL4q&t=1722) for the following:

![Salvage Arrapago 1st Rampart wikiEntry](https://github.com/EdenServer/community/assets/61279359/2f8968ac-e53c-4f49-98a6-4e66b1eb7b19)
[Wiki](https://ffxiclopedia.fandom.com/wiki/Arrapago_Remnants)

This concerns Archaic Rampart, ID 17080321.

If requested, I can link another recording of this Rampart spawning following the death of a Lamia.  In addition, I have several other recordings of me checking widescan after each Lamia kill, which provides further evidence of this exact spawn mechanic.

**Comment by KnowOne134** [comment]
Believe I've done the same and found it popping early but I'm not gonna search again for it. If someone can prove it doesn't it xan be reversed

**Comment by Maesedanielot** [comment]
We got rampart pop after kill 5 lamia's last run. I would say its totally random and only 1 lamia/merrow triggers it

**Comment by DeuceFFXI** [comment]
> We got rampart pop after kill 5 lamia's last run. I would say its totally random and only 1 lamia/merrow triggers it

Well, I can't comment on the exact trigger as it is currently coded on Eden as I don't know.  A previous run on Eden I believe my group had to kill 13 or 14 of the Merrow and Lamia before it spawned.  Or perhaps that was on the test server.

The retail accurate mechanic would be any combination of 10 Lamia and Merrow dead will spawn the Rampart.  As there's only 8 Lamia and 7 Merrows on the 1st floor, you always have to kill some from either group to trigger the Rampart spawn.  It took me several runs on retail before I narrowed that down, but I can confidently say the unverified comment on the wiki is correct.

**Comment by KnowOne134** [comment]
corrected in the 11/19/2023 update
