### ISSUE TITLE
SSR F2 SE Devilet shouldn't trigger TP on Defeaning Tantara

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5775]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

According to [this capture video from KO](https://youtu.be/G9eGSKSxg4A?si=d1BvfHGwmxjtmmAQ&t=1318), Devilet on SSR 2nd Floor SE room should only trigger a TP move from surrounding Crew when the Devilet is using "Abrasive Tantara". Currently on Eden, they're triggering Crew TP moves on -every- Devilet TP move.

**Comment by Steam-arch** [comment]
Hmm, do they cast spells on Eden? I feel like I havent seen any spells but cant recall atm for sure. Casting T3/Ga2 and sleepgas in the vid.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
