### ISSUE TITLE
Salvage - Arrapago Remnants: Psycheflayer NM, 4F model size and Cotton coin purse droprate

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5776]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Psycheflayer, 17080482, based on thirteen retail kills should drop Cotton coin purse 100% of the time it is killed similar to Archaic Chariot on the 5th floor.

In addition, it's model size needs to be increased to better match how it appears on Retail.  On Eden from certain angles it can be difficult to tell which Psycheflayer the NM is, whereas on retail it is painfully obvious where the Psycheflayer is each time one enters the room.

Eden
![Salvage Arrapago 4 Psycheflayer EdenSize](https://github.com/EdenServer/community/assets/61279359/1f16d2fe-de00-4054-95f6-1de5085267dd)

Retail
![Salvage Arrapago 4 Psycheflayer RetailSize](https://github.com/EdenServer/community/assets/61279359/9e66537a-67f1-4c5b-ac68-0c36f21bdd7e)

As one can see, Retail's version of this NM is over a head taller than regular Psycheflayers.  The [wiki](https://ffxiclopedia.fandom.com/wiki/Psycheflayer) page for this mob states that it's model is "~50% larger than other Psycheflayer..."

**Comment by DeuceFFXI** [comment]
Some more images from retail for comparing size

![Salvage Arrapago 4 Psycheflayer RetailSize5](https://github.com/EdenServer/community/assets/61279359/e2fdb4d2-c248-47e2-b68a-76eb66e5e525)
![Salvage Arrapago 4 Psycheflayer RetailSize4](https://github.com/EdenServer/community/assets/61279359/8d396d40-3448-4589-b9a1-d7191b710982)
![Salvage Arrapago 4 Psycheflayer RetailSize3](https://github.com/EdenServer/community/assets/61279359/38ee81a9-14e4-4f8e-ba36-824a17389e94)
![Salvage Arrapago 4 Psycheflayer RetailSize2](https://github.com/EdenServer/community/assets/61279359/31e720fd-6042-446e-bdd3-23e24f72aaa9)

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
