### ISSUE TITLE
Issues with Bastok 9-1 Slime

### ISSUE THREAD

**Issue by Avarghaladion** [EdenServer/community#5777]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

The Bastok 9-1 slime fight currently has the following issues with enmity, pathing, and despawn:

**1. Enmity on Spawn**

Upon being defeated, as long as the party is far enough away from the slime being killed, newly spawned slimes should not have anyone on their hate list. We would sleep the slime, move to max range, then finish the current slime off with a nuke. Every time we did this, the new baby slimes would bee-line it for a party member who had taken no action at all against the previous slime. We observed this after every split and they always went after the same person. That person was afk once and died, reraised, and the new baby slimes would still go after them immediately upon spawning. At the end they ran all the way to the zone and the slimes still tried to chase.

The person the slimes were always chasing was not the popper and they were the only non-Bastokan in the group.

**2. Pathing**

Any deaggroed slimes are pathing through the walls/floor/ceiling but instead of returning to spawn they are hovering above the map in an unreachable place per the below images (red dot = spawn point in the slime PoV image).

![2](https://github.com/EdenServer/community/assets/101778864/af106f7c-ac8b-41bb-899e-73216a083236)
![1](https://github.com/EdenServer/community/assets/101778864/74ffa9f7-e32a-4e8a-b86a-671b838f994a)

**3. Despawn**

Any deaggroed slimes are supposed to despawn after 180s but are persisting indefinitely. We encountered this issue when newly spawned Nanoplasms chased the person who was having issues with enmity on spawn to the zone. We tagged one but the other made it out of range before we could get a cast on it. We killed the last slime we had after the other would have despawned when the player it was chasing zoned but we were unable to collect our key items from the ??? and we were unable to respawn the mobs after logging/zoning. A GM detected that the remaining Nanoplasm had pathed through the floor and stopped moving in an unreachable place.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
