### ISSUE TITLE
Salvage - Silver Sea Remnants: The random Archaic Rampart on 3rd Floor East Path should not auto attack.

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5778]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
As the title suggests, the Archaic Rampart which unlocks the door on the East Path of 3rd Floor does not auto-attack.

Please refer to this [video](https://youtu.be/LSRC8_Ob0Wk?si=uy-aNoYj2UUTB2JR&t=4035) for evidence of this Rampart's behavior.  From 100 to 0% this Rampart never auto-attacked a single time.  However, another [capture](https://youtu.be/ePITwwF5_tY?si=8MVK7RccUW_2Dp_8&t=2287) shows the Rampart auto-attacking one time.  

I believe the key difference between these two captures is that in the second instance my character was within range of the Rampart upon initial aggro.  Regardless, this Rampart normally shouldn't auto-attack and therefore it poses less of a threat to players when fighting it.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
