### ISSUE TITLE
Salvage - General: Unlike Reactionary Ramparts, Archaic Ramparts do not share hate with Reinforcements

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5779]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Please see the following examples:

[Arrapago](https://youtu.be/Zcj5k0OgWPY?si=uNjZ-STWLw313QJb&t=1346)
[Silver Sea](https://youtu.be/LSRC8_Ob0Wk?si=JSULadjhoY9EeRIw&t=4518)
[Zhayolm](https://youtu.be/rE6ukMV969g?si=u2ZpgaD8h2d5XwCP&t=4469)

As demonstrated, once an Archaic Rampart begins using Reinforcements if the player(s) run from the Rampart, it is possible to avoid aggroing the mob that is spawned.  These videos clearly show that Archaic Ramparts do not share hate with the mobs they spawn from using Reinforcements.  Please note that these mobs are immediately aggressive, shown [here](https://youtu.be/Mj9KyyUfTdw?si=IW5x4ETWaIzEBHFH&t=4562), so players must be some distance from them to avoid detection.  Mobs which detect by sight may be harder to avoid.

This behavior is clearly different from that of Reactionary Ramparts found in Bhaflau Remnants seen in this [video](https://youtu.be/7Ad1FnZgNTQ?si=u5PnZz6diHHbfagG&t=787).

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
