### ISSUE TITLE
Catastrophe should go through shadows

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5781]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

According to [this BG post](https://www.bluegartr.com/threads/80197-Actual-Relic-information-thread?p=2993992&viewfull=1#post2993992) from August 17th, 2009, Catastrophe should go through shadows. It currently doesn't on Eden. A couple posts down from that link is another player saying "As mentioned by Taint, Catastrophe goes through Utsusemi blink, but not mage blink. (Does not work on Third Eye either.)"

[JPWiki](https://wiki.ffo.jp/html/3088.html) also says "Also, Blink's illusion may not be able to penetrate, but utsusemi's clone can penetrate 100%". 

Looking at patch notes from August 17th, 2009 to September 2008, I don't see anything referencing this change. JPWiki also only has the stat mods being changed in 2014 under it's "History" section

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
