### ISSUE TITLE
Hydra Corps should not be undead

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#5782]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
https://wiki.ffo.jp/html/2158.html
https://ffxiclopedia.fandom.com/wiki/Drain?oldid=1040427

Unlike normal fomors, these should not be undead so should be able to be drained/aspir/cata and can not be cured to damage them

thanks @Mozzy4Ever for the proof

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
