### ISSUE TITLE
Salvage - Zhayolm Remnants: 3F Mamool Ja cell drops

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5785]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
After collecting data from Zhayolm, found on this [spreadsheet](https://docs.google.com/spreadsheets/d/1dQ3ExnPUJQzEeJ3z5iYojTkuGJ-D_CSCxrmXl1EgCc4/edit#gid=302535065), a few changes need to be made to the Mamool Ja on the south side of the third Floor.

- Mamool Ja Strapper, ID: 17076349 change Congestus -> Pannus
- Mamool Ja Strapper, ID: 17076350 change Pannus -> Congestus
- Mamool Ja Strapper, ID: 17076366 change  Pileus -> Mediocris

In addition, the drop rate for Humilus and Spissatus cells from all Mamool Ja on the south side, excluding the three which do not drop cells needs to be increased.  The drop rates for both should be very common or 24%.

All data was collected without the use of Treasure Hunter.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
