### ISSUE TITLE
Salvage - Zhayolm Remnants: 4F North Poroggo Gents cell drops

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5786]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
At the moment, Poroggo Gents on the north side of the fourth floor are dropping the incorrect cells.  The mob IDs range from 17076462 thru 17076485.  The only cells that either group can drop are the following:

- Cirrocumulus
- Castellanus
- Virga
- Spissatus
- Undulatus
- Cumulus

Please refer to [this](https://youtu.be/NZyXPG-aJyI?si=wDV7AgrRrM-SqxPL&t=1836) retail capture for evidence.

Furthermore, through numerous clearings of each group it has been observed that only certain Poroggos can drop cells.

### Group A
- 17076462 -  Undulatus & Spissatus
- 17076463 - Cumulus & Virga
- 17076464 - Castellanus & Cirrocumulus

### Group B
- 17076474 - Undulatus & Spissatus
- 17076475 - Cumulus & Virga
- 17076476 - Castellanus & Cirrocumulus

The droprate for all of the above cells appears to be very common (24%).  Either one or both cells can be dropped as can be seen [here](https://youtu.be/NZyXPG-aJyI?si=EN11_fDf9f8jGpMR&t=2339).

None of the other Poroggos from this side of the fourth floor drops cells.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
