### ISSUE TITLE
Chain Affinity + SATA Blue Magic Enmity Transfer Issues

### ISSUE THREAD

**Issue by Aezaeo** [EdenServer/community#5789]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Client_Version: 30181205_0

Hate transfer from SATA Blue Magic seemed inconsistent. Through testing we have determined:
When CLOSING a skillchain with Chain Affinity + SATA Blue Magic, enmity DOES NOT transfer correctly, it is instead directed towards the caster, i.e., the Blue Mage. When simply using SATA Blue Magic, enmity DOES transfer correctly, directing attention towards the intended player. The same goes for Chain Affinity + SATA Blue Magic.  To reiterate it is only when closing a skillchain with Chain Affinity + SATA Blue Magic that the enmity transfer DOES NOT occur.

Testing(Done Multiple Times):
Player 1: BLU/THF (Aezaeo)
Player 2: Initial Agro (Jimmidy)
Player 3: SATA Target (Jammidy)

1: Engaged, SATA, Extra Distance, Cannonball = Player 3 Agro
2: Disengaged, SATA, Extra Distance, Cannonball = Player 3 Agro
3: Disengaged, SATA, Chain Affinity, Extra Distance, Cannonball = Player 3 Agro
4: Engaged, Player 1 WS, SATA, Chain Affinity, Melee Distance, Cannonball, Skillchain = Player 1 Agro
5: Engaged, SATA, Chain Affinity, Melee Distance, Cannonball = Player 3 Agro
6: Engaged, Player 2 WS, SATA, Chain Affinity, Melee Distance, Cannonball, Skillchain = Player 1 Agro

Recorded Testing(Screenshot):
Closing Skillchain  with Chain Affinity + SATA = No Hate Transfer

![OfaDhAJ](https://github.com/EdenServer/community/assets/24560181/cafdd627-14fd-4b42-9fb8-cfa9d55c789b)

NO Skillchain: Chain Affinity + SATA = Hate Transfer
 
![GgzZ3j9](https://github.com/EdenServer/community/assets/24560181/7710c788-2e32-4b0c-aa78-35148ab6b080)

**Comment by Slamm21** [comment]
looks like the enmity is transferring from cannonball but not from the light sc?

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
