### ISSUE TITLE
Eden 5-2 Shadowlord BCNM Throne Room R0 During Physical Immune Phase

### ISSUE THREAD

**Issue by Kalifriki** [EdenServer/community#579]
While attempting to clear 5-2 BCNM Shadowlord fight via Throne Room with 4x Sandorians, x1 Bastokan and x1 Windustrian; the client will R0 during the Shadowlord's physical immune phase.

Four attempts were made at this fight; R0's took place during Shadowlord's remaining HP:
25% HP remaining - Attempt 1; with RA
27% HP remaining - Attempt 2; with RA
8% - HP remaining - Attempt 3; with RA
20% - HP remaining - Attempt 4; no RA used

Each R0 required Eden's BCNM server to be reset to allow participants to log back into the game.

<img width="551" alt="5-2_shadowlord" src="https://user-images.githubusercontent.com/46100825/50393328-29e69700-071b-11e9-9a8c-f8ae25794457.PNG">
<img width="820" alt="5-2_shadowlord_round4" src="https://user-images.githubusercontent.com/46100825/50393332-2eab4b00-071b-11e9-868c-4702cf1c1ea2.PNG">

https://ffxiclopedia.fandom.com/wiki/The_Shadow_Awaits

**Comment by godmode** [comment]
It may have been a coincidence. I think other players were in the BCNM at this time as well which caused a crash. Did he try to prepare any moves or did you do anything to him before the crash that was the same each time?

**Comment by Kalifriki** [comment]
Yes, during 2 of the attempts there were players attempting to complete 2-3 Dragon fight. From what I recall there were no consistencies in our actions during the physical immune phase that may of prompted the R0 crashing. I'd suggest messaging my other party members to confirm.
