### ISSUE TITLE
Corsair Healer's Roll

### ISSUE THREAD

**Issue by Vidoqueen** [EdenServer/community#5791]
### Checklist
 I don't know if this is true or not. I was told the Corsair ability "Healer's Roll" does not affect the power of cure, but instead allows the healer to heal mp faster. I was wondering if this was true, and if Eden should change the tooltip. 

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by KnowOne134** [comment]
It is changed. You need the dats posted at https://github.com/EdenServer/Eden-Client_DATs
