### ISSUE TITLE
Quest "The First Meeting" Missing Cutscene

### ISSUE THREAD

**Issue by inaringo** [EdenServer/community#5792]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

After completing the quest the "The First Meeting", there should be an optional cutscene from the NPC Michea in Bastok Markets.

**Comment by KnowOne134** [comment]
corrected in the 11/19/2023 update
