### ISSUE TITLE
Salvage - Zhayolm Remnants: 4F South Poroggo Gents cell drops

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5793]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
The drops for Poroggo Gents on the South side of the 4th floor needs to be adjusted.  Currently on Eden, Poroggo can drop none, 1, 2, or 3 cells some of which can be seen in the two images below.  The information in this bug report is based upon the data from this [spreadsheet](https://docs.google.com/spreadsheets/d/1dQ3ExnPUJQzEeJ3z5iYojTkuGJ-D_CSCxrmXl1EgCc4/edit#gid=302535065).  All data was gathered from ~20 runs without TH.

### Eden
![Salvage Zhayolm 4S PoroggoDropsEden2](https://github.com/EdenServer/community/assets/61279359/f2bbaf39-e399-4fac-9622-7fd8f85011f3)
![Salvage Zhayolm 4S PoroggoDropsEden](https://github.com/EdenServer/community/assets/61279359/8cd30f69-3398-4ff1-99d5-666c7c74bfd5)

The actual cells should drop in multiples of THREE.  So, the options are none, three, or six.  Examples below.

### Retail
![Salvage Zhayolm 4S PoroggoDrops](https://github.com/EdenServer/community/assets/61279359/e3e187f5-fb03-45a9-828d-cee0016a2340)
![Salvage Zhayolm 4S PoroggoDrops2](https://github.com/EdenServer/community/assets/61279359/9be070c0-f867-444a-9a83-af0bf7beddc0)

Also, some cells seem to be missing, and all Poroggo seem capable of dropping Spissatus on Eden, which should not be the case.  In addition, what cells are dropped by which Poroggo by ID is set and there are two Gents which do not drop cells at all.

Drops by ID
- 426, Spissatus & Undulatus
- 427, Cumulus & Virga
- 428, Cirrocumulus & Castellanus
- 429
- 430, Spissatus & Undulatus
- 431, Cumulus & Virga
- 432, Cirrocumulus & Castellanus
- 433

Lastly, the droprates for all cells seems to be Very Common or 24%.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
