### ISSUE TITLE
Salvage - Arrapago Remnants: Gespenst dropping too many Congestus cells

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5794]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
![Salvage Arrapago 1st GespenstTooManyCongestusEden](https://github.com/EdenServer/community/assets/61279359/6a64f9a4-bd52-498c-8e0d-9b22d45b23a9)

The above screenshot for reference.  It seems that on Eden, Gespenst are capable of dropping two Congestus cells.  This should not be the case.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
