### ISSUE TITLE
Salvage - Arrapago Remnants: 4F North Demonic Rose does not spawn

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5795]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Retail [Capture](https://youtu.be/qc8LAksN_HY?si=1hUfQBgbKVArCBwO&t=3404) for reference.
[Spreadsheet](https://docs.google.com/spreadsheets/d/1dQ3ExnPUJQzEeJ3z5iYojTkuGJ-D_CSCxrmXl1EgCc4/edit#gid=1425599195) for drop data

As the title suggests, Demonic Rose, 17080513, does not spawn when Archaic Rampart, 17080512, uses Reinforcements.  This mob also doesn't appear to be in the database when attempting to force spawn it on the test server.

When killed it should drop (3) Stratus Cells guaranteed every time.  Second, a single Cumulus cell can drop at approximately a rate of 15%, Common. More data may need to be collected to further narrow down the actual drop rate of the Cumulus cell in the future, as it could be as high as Very Common.

Lastly, this mob can only spawn once from this Rampart.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
