### ISSUE TITLE
Salvage - Arrapago Remnants: 5F North Mourioche cell droprate

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5796]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Retail [Capture](https://youtu.be/gpEckJY9ukI?si=88ATqsZe4jmFqXqu&t=4524)
[Spreadsheet](https://docs.google.com/spreadsheets/d/1dQ3ExnPUJQzEeJ3z5iYojTkuGJ-D_CSCxrmXl1EgCc4/edit#gid=1425599195)

The drops for Mourioche in Arrapago need to be changed significantly.  As can be seen in the data and the retail capture linked above, Mourioche ALWAYS drop (3) Mediocris Cells.

**Comment by DeuceFFXI** [comment]
Forgot to mention, Archaic Rampart, 17080545, can only use reinforcements three times.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
