### ISSUE TITLE
Salvage - Arrapago Remnants: 5F North Goobbue Wanderer cell drops

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5797]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Retail [Capture](https://youtu.be/gpEckJY9ukI?si=88ATqsZe4jmFqXqu&t=4524)
[Spreadsheet](https://docs.google.com/spreadsheets/d/1dQ3ExnPUJQzEeJ3z5iYojTkuGJ-D_CSCxrmXl1EgCc4/edit#gid=1425599195)

Similar to the bug report for Mourioche, Goobbue Wanderer need their drop rates adjusted.  They should ALWAYS drop (2) Pannus cells when defeated.  In addition, as seen in the below screenshot, they can drop (1) Pileus cell, at approximately 12.5%, which I believe means it should be an uncommon drop rate, 10%, similar to the Orobon on the South side.

![Salvage Arrapago 5N GoobbuePileusDrop](https://github.com/EdenServer/community/assets/61279359/6c97d1fc-4381-4437-9367-6a239bf19a23)

Furthermore, Archaic Rampart, 17080555, is limited to using reinforcements twice.  Rampart, 17080553, can only use reinforcements once.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
