### ISSUE TITLE
Zhayolm Remnants Floor 5 Poroggo Madame NM Needs Audit

### ISSUE THREAD

**Issue by Garphilius** [EdenServer/community#5799]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

We have now been lucky (ring/ranged cells bugs currently as posted in another report) to pop this NM five times and have killed it to have zero drops each time. According to both wiki's, this frog should be dropping a Cotton Purse 98% to "guaranteed" drop each time the NM dies. Yes, he was killed with TH4 each time.

This first link states that: "Guaranteed drop from most level 75 Salvage notorious monsters, not guaranteed from Qiqirns in Arrapago Remnants."

https://www.bg-wiki.com/ffxi/Ctn._Purse_(Alx.)

This next link shows that this NM should drop a Cotton Coin Purse:

https://www.bg-wiki.com/ffxi/Poroggo_Madame

And finally, this link shows that the drop rate should be 98%: 

https://ffxiclopedia.fandom.com/wiki/Poroggo_Madame

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
