### ISSUE TITLE
Linkpearl in Bazaar

### ISSUE THREAD

**Issue by Restarted** [EdenServer/community#580]
Got a bazaar glitch and a linkpearl is up for sale for 130K. I don't want to get banned because they specifically say they have no market value in the description. Can't remove price or buy it from myself.

**Comment by Setz0r** [comment]
@Restarted you wouldn't happen to know what the conditions were that lead to you having a linkpearl in bazaar?

**Comment by beerking27** [comment]
i purchased the linkpearl to resolve the issue.

**Comment by KnowOne134** [comment]
cant reproduce
