### ISSUE TITLE
Roc's accuracy/evasion/attack all need an audit

### ISSUE THREAD

**Issue by Corvinus1337** [EdenServer/community#5800]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Roc’s accuracy and evasion are currently too low compared to how it should be in this era. His stats/level are very similar to Simurgh but currently it can easily be duoed by a DPS + mage within the rage timer. Part of the issue is that after Simurgh was adjusted on Eden, Roc was NOT adjusted accordingly.

Here’s a video from 2007 which shows a lvl 72 NIN (evasion skill 254 + 10 evasion from emp hairpin) and out of 115 total attacks, Roc lands 105 of them, the NIN parries 5 and Roc only misses 5 attacks.

Additionally out of the 17 hits that Roc lands on the NIN he’s getting hit for an average of 200.6471 which is substantially higher than it is currently. From my own experience his difficulty was fairly close to Simurgh.

https://www.youtube.com/watch?v=BcsJJMIqSPE

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
