### ISSUE TITLE
Quick Draw recast merits doing nothing.

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#5801]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window) 30181205_0
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
x5 quick draw merits does not reduce charge recast by 10 seconds. 

![image](https://github.com/EdenServer/community/assets/46233090/ddb70790-d92c-4ff5-bb0f-5929b6b83639)
![image](https://github.com/EdenServer/community/assets/46233090/5201522d-227d-4ad3-8251-c7db60388de3)

![ffxi_2023 10 30_02 50 28](https://github.com/EdenServer/community/assets/46233090/62adbb50-0a41-429b-9f07-18fc9a24692c)

**Comment by StriderClerix** [comment]
![ffxi_2023 10 30_02 54 19](https://github.com/EdenServer/community/assets/46233090/8fd54b20-3b6e-44ca-9910-69bd2f769262)
![ffxi_2023 10 30_02 54 22](https://github.com/EdenServer/community/assets/46233090/c2b71389-17e6-430c-957a-b8f9a1ef6fad)

some lag inbetween the screen shots, but the UI / recast shows it should be ready, but it's unable to be used.

**Comment by Dukilles** [comment]
Resolved in 10/9 patch
