### ISSUE TITLE
Salvage - Bhaflau Remnants: 4F Dormant Rampart should have multiple spawn locations

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5804]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Currently, the Dormant Rampart on the 4F spawns in the central room past the Gilded Door on Eden as shown on the map below.

![BhaflauRemnants4FresizeMarked](https://github.com/EdenServer/community/assets/61279359/b2c43633-241b-499b-bb7b-30e5438b237f)

This is not the location in which it should spawn.  In fact, there are four locations on each side of the fourth floor where this rampart can spawn for a total of eight different spawn locations.  Where the Dormant Rampart spawns is determined by which room the last of the ten Archaic Gear was from.  For example, the three Archaic Gear; 17084662, 17084663, 17084664,  if killed last will spawn the rampart in the same room they spawn and roam in, the fourth room on the east side.

The below image is an example of one location in which this rampart can spawn.

![Salvage Bhaflau 4th DormantRampartEast2ndRoom](https://github.com/EdenServer/community/assets/61279359/c21e686f-7d16-465f-ab01-c9c666a0b71c)

### West Side
- 1st Room; X: -380 Y: 0 Z: -75 R: 192
- 2nd Room; X: -365 Y: -004 Z: 020 R: 128
- 3rd Room; X: -460 Y: -004 Z: 125 R: 192
- 4th Room; X: -380 Y: 0 Z: 195 R: 064

### East Side
- 1st Room; X: -300 Y: 000 Z: -75 R: 192
- 2nd Room; X: -315 Y: -004 Z: 020 R: 0
- 3rd Room; X: -220 Y: -004 Z: 125 R: 192
- 4th Room; X: -300 Y: 0 Z: 195 R: 064

The same coordinates for each spawn location are used for where the player is teleported to after the Reactionary Rampart is defeated.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
