### ISSUE TITLE
No error message when you have insufficient assault points to buy Remnant permit when AP between 500 and 1499

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5807]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

If you try to buy a remnant permit without enough assault points, zasshal still gives you the text that he's giving you a permit. Instead of some variation of the 'You don't have enough points' speech. 

https://cdn.discordapp.com/attachments/774383314651840524/1169793852316598272/1169792550723407973remix-1698970987156.png?ex=6556b26c&is=65443d6c&hm=a434b65eca83425d51ccb0c7b551b4163881141afa4a9dfa304e8fdb0e52ae91&

**Comment by 59blargedy** [comment]
updated title as you'll get the fail message if you have less than 500, but not if you have between 500 and 1499. need a dat edit to resolve

**Comment by KnowOne134** [comment]
i am not having this issue using the new dats posted to discord
900ish points trying to use and get correct error message.

https://github.com/EdenServer/Eden-Client_DATs

![image](https://github.com/EdenServer/community/assets/35616771/8de2ffed-2ed7-495a-abe6-9853e3c32f15)
