### ISSUE TITLE
Gigas Stonemasons in Upper Delkfutts Tower aren't linking with other mobs

### ISSUE THREAD

**Issue by MonkeyAce9** [EdenServer/community#5808]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

So after camping Enkelados in Upper Delkfutts Tower for a couple of days now I believe the Gigas Stonemasons in both F-8 and J-8 aren't linking with the other mobs like they should. Whilst it is possible to pull and kill the Gigas' in the room without getting aggro, I've done this too many times to not get them accidentally aggroed.

I believe they are suppose to link with the other mobs in the room and just don't link.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
