### ISSUE TITLE
Salvage - Bhaflau Remnants: Reactionary Ramparts should be Non-Aggressive

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5809]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
[Capture](https://www.youtube.com/watch?v=FbeSCHwCIXA) of behavior on retail.

As can be seen in the short clip linked above, Reactionary Ramparts are non-aggressive.  This is contrary to what one of the retail [wikis](https://ffxiclopedia.fandom.com/wiki/Reactionary_Rampart?so=search) lists in their notes for these mobs.  Currently Eden's Reactionary Ramparts are coded to be aggressive when a player approaches them, which should not be the case.  Players must act on each Reactionary Rampart to trigger their behavior.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
