### ISSUE TITLE
Adaman Gauntlets wrong NPC price

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5811]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

Eden's current Adaman Gauntlets vendor price is 4,996g. 
[FFXIClopedia's](https://ffxiclopedia.fandom.com/wiki/Adaman_Gauntlets?direction=next&oldid=771780) first instance of a price shows base at 9,371 in April 2009. Current retail FFXIClopedia says 9,371-9,605.
[JPWiki](https://wiki.ffo.jp/html/11088.html) says "about 9300 gil"
BGWiki doesn't list vendor prices sadly

**Comment by KnowOne134** [comment]
Corrected in 11/19/2023 update
