### ISSUE TITLE
Salvage - Zhayolm Remnants: 2F Cumulus Cell drop rates

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5812]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Based on the data from this [spreadsheet](https://docs.google.com/spreadsheets/d/1dQ3ExnPUJQzEeJ3z5iYojTkuGJ-D_CSCxrmXl1EgCc4/edit#gid=302535065), Cumulus cells, from the second floor of Zhayolm Remnants, which can drop from the following:

- Wyverns
- Draco Lizards
- Mamool Ja Bounder
- Mamool Ja Zenist
- Mamool Ja Savant
- Mamool Ja Spearman

needs to be increased.  The correct rate for the Mamool Ja should be 24% or very common.  The Wyverns and Lizards appear to _also_ share a **_24%_** or common drop rate for a singular cumulus cell.  Only the Wyverns and Draco Lizards that are capable of dropping cells should be able to drop them as is already the case.

All drop rates are based on data collected from retail without TH.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
