### ISSUE TITLE
"Smoldering Salisbury Steak" item and recipe is out of era

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5814]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Currently, there is a recipe for the Smoldering Salisbury Steak food in the game as seen on the Eden site:
https://edenxi.com/tools/item/5924

According to wiki, this item was added in 2012:
https://ffxiclopedia.fandom.com/wiki/Smoldering_Salisbury_Steak?action=history

This item/recipe should be removed

Or, if it is going to be kept around, the recipe materials are also incorrect.  It has Cockatrice Meat listed when it should be Cerberus Meat.

**Comment by 59blargedy** [comment]
Resolved in December 14, 2024 update
