### ISSUE TITLE
Corsair AF wait times incorrect (game day not midnight JST)

### ISSUE THREAD

**Issue by Deirdre5017** [EdenServer/community#5815]
- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version 30181205_0

I'm assuming this is also an issue for BLU AF as well and was something that was previously resolved last year:

https://github.com/EdenServer/community/issues/4864

But it appears to be an issue again. Accidentally clicked the door in Bastok and received Corsair's Bottes before midnight JST when I turned them in the night before and it should not be ready yet:

![image](https://github.com/EdenServer/community/assets/73006091/c2221f0e-cd62-4d32-b577-a4beded2783a)

I then tested and was then able to accept Corsair's Frac quest as well as turn in the items needed:

![image](https://github.com/EdenServer/community/assets/73006091/512a3b4d-cc90-4dc4-83a1-1b0886a66eec)

And the NPC gave the completed Frac to me less than 10 minutes later at the next game day (although it was next game day AND midnight JST so not sure if that factored into it):

![image](https://github.com/EdenServer/community/assets/73006091/930167ce-3be5-4c27-8714-92c001626191)

**Comment by StriderClerix** [comment]
https://ffxiclopedia.fandom.com/wiki/Transformations?oldid=854095

https://discord.com/channels/482610771126386688/670754214628032513/1170379260951806002

I had to wait a JP midnight between picking up and selecting the new BLU AF piece back at the beginning of this month.

**Comment by 59blargedy** [comment]
blue mage is fine, cor was just never updated, probably bc it was a comment and not a separate bug report and got missed is all. thanks for reporting.

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.
