### ISSUE TITLE
Investigation of the Emptiness Reward Issue

### ISSUE THREAD

**Issue by Gantofu** [EdenServer/community#5819]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
Tested with 2 different game character on the same quest with same result
- [x] I have provided my client version in the details. (type /ver into your game window)
![image](https://github.com/EdenServer/community/assets/59887688/921a93a3-1bbc-4bf7-9d93-ee526fff9d69)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.
![image](https://github.com/EdenServer/community/assets/59887688/1593c32a-133a-4524-ae39-393c7d80382a)

### Details
Before the patch, when talking to NPC at Rendezvous point for the quest reward, i would receive 1x homemade food, and 1x tactic pearl.  but today after patch i found npc no longer gives out the reward, only the quest completion line in chat window
Double checked that no tactic pearl item in inventory to prevent the quest completion

**Comment by 59blargedy** [comment]
yeah, missed a patch note, was resolved in accordance with another bug report. food is only floor 2 and beyond

**Comment by Gantofu** [comment]
Hello, need to follow up on this issue.  
The problem is now everytime i click Rendezvous Point, NPC auto-reply as this quest is completed and end CS
i can't access Rendezvous Point for other fellow options such as checking level, change fellow job type, etc
![284081289-1593c32a-133a-4524-ae39-393c7d80382a](https://github.com/EdenServer/community/assets/59887688/327f6703-d570-4f8d-9c16-97f18eb2ae1f)
