### ISSUE TITLE
Out of Era NM

### ISSUE THREAD

**Issue by Atigeve** [EdenServer/community#582]
Metal Shears Crab in VD Saw him Friday when i was getting SJ items.  I did not get a screenshot sorry.

**Comment by Frutiebutie** [comment]
If we must... Bedrock Barry in N. Gustaberg so old school Kupo people can't farm noobs with his accuracy drop, Thoon in Korolakka, Stalking Liger in Batalia Downs, and I assume that entire retarded earring line.  I mean, while we're at taking away stuff that couldn't possibly be considered breaking the game for "era".
