### ISSUE TITLE
3F Silver Sea Remnants Reinforcements not working

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5826]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Rampart on 3rd floor of SSR east side (not sure about west), is using reinforcements but not spawning mobs. In chat log, says it's doing 0 damage to itself. ID 17088693

**Comment by 59blargedy** [comment]
Resolved in december 15, 2023 update
