### ISSUE TITLE
Altepa Gate opening incorrect

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5828]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

https://ffxiclopedia.fandom.com/wiki/Altepa_Gate
Altepa Gate opening should require hitting the 4 elemental columns. The status of which you need to hit is displayed by the entrance of the gate. 
Currently on Eden, all of the indicators show the columns have been hit. All you have to do is hit 1 of the columns (and there's one on the way to the gate) and the gate will open. The column you hit will say "it does not respond" but it does open the gate.

**Comment by 59blargedy** [comment]
Resolved in december 15, 2023 update
