### ISSUE TITLE
Arrapago Remnants: Incorrect cell drop

### ISSUE THREAD

**Issue by doughnuteden** [EdenServer/community#5831]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Run date 12/6
![image](https://github.com/EdenServer/community/assets/132183590/486b4ab0-c488-4bf8-a47a-fef553bc1f6b)
Merrow Shadowdancer on 2F SE room dropped a radiatus cell which should not exist on their drop table.

https://ffxiclopedia.fandom.com/wiki/Merrow_Shadowdancer

https://ffxiclopedia.fandom.com/wiki/Arrapago_Remnants

https://www.bg-wiki.com/ffxi/Arrapago_Remnants

**Comment by falzum** [comment]
Did this last week and this same Merrow dropped a body cell as well
