### ISSUE TITLE
Cythara Anglica +1 not extending duration of Virelai

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5832]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Virelai has a base duration of 30 seconds.
Currently, casting Virelai with Cythara Anglica +1, which has +2 Virelai, results in a 30 second duration:
![image](https://github.com/EdenServer/community/assets/95725249/539a28b8-50ff-47c2-b931-80fb28bcf009)

Bard songs should get an extra +10% duration per bonus to the song, so in this case it should gain an extra 6 seconds going up to 36 seconds:
https://www.bg-wiki.com/ffxi/Maiden%27s_Virelai
https://ffxiclopedia.fandom.com/wiki/Maiden's_Virelai

Wiki backdated to 2008 claims that Cythara Anglica +1 extends duration by 10 seconds, but I am assuming that was an approximation since every other song works as described above:
https://ffxiclopedia.fandom.com/wiki/Maiden%27s_Virelai?oldid=776461

I do not know if NQ or gjallarhorn work correctly.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
