### ISSUE TITLE
Pulling the Strings ENM Fantoccini wandering arena

### ISSUE THREAD

**Issue by AshleyAwakens** [EdenServer/community#5833]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
In the Pulling the Strings ENM, the Fantoccini mob wanders around the arena allowing it to be pulled without linking the Moblin and thus being able to ignore the dice mechanic. I assume this is unintentional behavior since other BCNMs were fixed a while ago to stop mobs wandering around.

**Comment by 59blargedy** [comment]
Resolved in december 15, 2023 update
