### ISSUE TITLE
Valkrum Emperor Placeholder audit

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#5834]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

VE can spawn from any of the Flies around whitebone sands when it should only be able to spawn from the one that spawns on the beach. Mob ID 14A
https://ffxiclopedia.fandom.com/wiki/Valkurm_Emperor

listing from another issue to close as its 2 issues
https://github.com/EdenServer/community/issues/3255

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
