### ISSUE TITLE
Bhaflau Remnants lvl 15 drop rate check + potential F2 rampart issue

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5837]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Could we get a BR 15 drop rate check that there isnt anything goofy going on like the 15 gear share a drop rate slot or anything like that? 

Done a fair bit of BR and very skeptical that the 15 drop rates actually reflect DB's drop rates because every mob should potentially have ~2.5-5% drop rate for a 15 piece PER kill. Yet they drop rarely even if you clear 90% of a path

Bifron loot table from DB
![image](https://github.com/EdenServer/community/assets/69089249/0de30d88-088d-40b6-b335-02889c89a01f)

Scorpion loot table from DB
![image](https://github.com/EdenServer/community/assets/69089249/2fbe5fe2-4c97-41cf-9805-6510df8a63e1)

-----------------

Also should make sure F2 rampart is actually spawning since the last update Did 2 runs and pretty sure we did it perfectly atleast the second time as we played it as safe as you can, yet no rampart spawned for 2 runs.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch. if the rampart issue occurs again can you make a separate ticket?
