### ISSUE TITLE
Steelbiter Gudrud has wrong enemy model

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5838]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Currently, the NM Steelbiter Gudrud in Davoi spawns with his Campaign model:
![image](https://github.com/EdenServer/community/assets/95725249/7b0228b4-bbc0-4ee9-a9b4-d52c2d5c6e30)

The Davoi version should have this enemy model instead: 
![image](https://github.com/EdenServer/community/assets/95725249/8761d7dd-63bb-4370-815f-7ccbc4ba7071)

https://ffxiclopedia.fandom.com/wiki/Steelbiter_Gudrud

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch. think i forgot this in patch notes, or it was resolved in a previous patch.
