### ISSUE TITLE
Steelbiter Gudrud drops incorrect

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5839]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

According to Wiki, Steelbiter Gudrud should drop One of: Lizard Piercer or Sentinel's Mantle:
https://ffxiclopedia.fandom.com/wiki/Steelbiter_Gudrud

Currently, this NM can drop nothing:
![image](https://github.com/EdenServer/community/assets/95725249/80b91cb3-a406-4cae-a7b8-125b1b62150a)

This NM should drop one of these items always.

Further, I am not sure if this NM even drops Sentinel's Mantle at all.  There is no sales history on AH for the item or for the item that it is a synth material for.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
