### ISSUE TITLE
Bastok + San d'Oria Allied T.K. Bug

### ISSUE THREAD

**Issue by maeinit** [EdenServer/community#584]
While speaking to any T.K. guard; outpost or within San d'Oria itself, unable to choose any dialog options typically offered such as "Set Homepoint here" (for outposts) or "Spend Conquest Points" and others (when within naiton). 

Instead the guard skills the options box and goes straight to casting signet.

**Comment by tectal831** [comment]
which guards, which outposts, and proof of your claim would be helpful here. Thanks

**Comment by KnowOne134** [comment]
unable to reporduce
