### ISSUE TITLE
AU42 Path of Darkness death should not result in loss of experience

### ISSUE THREAD

**Issue by ConteAlmaviva** [EdenServer/community#5840]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Per https://ffxiclopedia.fandom.com/wiki/Aht_Urhgan_Mission_42:_Path_of_Darkness?oldid=638945 (August 2008 retail wiki entry for this mission), no experience should be lost on death in this mission, but it appears that is not the case on Eden.  (Game version is 30181205_0.)

**Comment by KnowOne134** [comment]
Find this claim hard to believe since it's not a true bcnm and thus doesn't follow rules the same as a bcnm. Bg says no refrence to this. I'd need to see evidence of the case being the 1st instanced zone with the claims I've heard as of yet to even make an option toggleable

**Comment by KnowOne134** [comment]
Wiki is a good start but is never the definite answer we find it wrong consistently.

**Comment by ConteAlmaviva** [comment]
That's very possible, but the classic wiki should also be updated if that's the case, as it also states there's no experience loss ("so it's okay to home point warp").  I'd guess that it was just pulled from a retail wiki snapshot from 2007 (or 2008), but it also has reference to an Eden bug concerning when the Nyzul route key item can be collected. (That bug was corrected in a November update.)  That seemingly lent some credence to there not being experience loss.

**Comment by KnowOne134** [comment]
wiki has been updated over the years and the tag for no experience lost was removed. I Believe it was a mistake someone added in and was later removed by someone else correctly, as SE doesnt have a record of making things harder over the years, only easier. BG also says nothing about no xp loss.
