### ISSUE TITLE
Aerns ignore effects of statuses received while reraising

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5842]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
When an aern reraises it's immediately targetable and finishes the reraise animation before moving and attacking. If slept or stunned during this time the aern seems to receive the effect but ignore it. Despite the status having seemingly no effect, you'll still see a message in the log when the status wears off (if you inflicted the status of course).

Client version 30181205_0

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
