### ISSUE TITLE
Hoo Mjuu the Torrent placeholders are not spawning as they were

### ISSUE THREAD

**Issue by RyanTevious** [EdenServer/community#5845]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Version: 30181205_0

Several of the Yagudo in the immediate area where Hoo Mjuu the Torrent spawns in Giddeus are not spawning as they used to and only about half of them are spawning at any given time. This may have been an intentional change, as this spot was pretty crowded with Yagudo previously. While Hoo Mjuu can still be spawned, the odds are now greatly reduced as there are less lottery chances with the reduced amount of placeholders present at any time. I had to give up camping him once recently when he did not spawn after clearing the area for over 5 hours straight.

This change seems to have happened sometime in late 2023, either December or possibly November, as all Yagudo were previously spawning in full when I was camping him before then. I'm not the only person to notice this behavior. To my knowledge, the server was reset at least once since I noticed this change and it did not reset to the way it was before.

Here I arrived at the site and there were only 7 Yagudo in the H-9/H-10 area:
![Pumpzkin_2024 02 13_120026](https://github.com/EdenServer/community/assets/58167027/847fe714-7e04-418a-8caa-062b3214a790)
![Pumpzkin_2024 02 13_120052](https://github.com/EdenServer/community/assets/58167027/c2f4d012-3bbb-41ee-a50c-cda7df26aed0)

10 minutes later when the Yagudo respawned, there were only 6 of them there:
![Pumpzkin_2024 02 13_121257](https://github.com/EdenServer/community/assets/58167027/728cbb61-a190-4612-b8fb-13ce42467075)
![Pumpzkin_2024 02 13_121328](https://github.com/EdenServer/community/assets/58167027/268c447e-c574-4491-b64a-5580c585536c)

Previously, there were about 11 or 12 Yagudo there.

After reviewing videos on Youtube, this change seems to be in line with how retail is currently. As for whether it is ToAU era appropriate, I'm unsure and maybe someone else could verify. I think I remember there were a large amount of Yagudo that would spawn at this site originally when the game was released, like how it was before the change on Eden. But I also vaguely remember something being changed at some point on retail with this area. I cannot remember for sure what the case was back then.

Additionally, on a related note, one of the Yagudo Mendicants gets stuck in place and cannot move about the era.
![Pumpzkin_2024 02 13_121611](https://github.com/EdenServer/community/assets/58167027/d1c32586-a138-4526-946c-54bec377d735)

**Comment by RyanTevious** [comment]
So I've done some further testing and I think I understand what happened. And I've made a map to demonstrate what I think is going on:
![Hoo Mjuu Placeholders](https://github.com/EdenServer/community/assets/58167027/43fb3ea0-24c7-403c-9ba5-0c8da850656f)

The Yagudo in this area are now linked (see lines connecting circles) so that only one of the linked Yagudo will spawn at any one time. Whereas before, they were all unlinked and all spawned together at the same time. This explains why the area used to be packed with double the amount of Yagudo; much more than in other areas. So now, the placeholders (green 1, 2, and 3) each have a percentage change of spawning as Yagudo Mendicants, or alternatively as Yagudo Pipers or Yagudo Persecutors (not placeholders). Because of this, Hoo Mjuu theTorrent has a far lesser chance of spawning than he did previously.

I'm beginning to suspect this may have been an unannounced intended change? This may have just been broken originally on retail and fixed later at some point, if it ever indeed was like this on retail. Personally, I would like to see the two Yagudo Mendicants (green 1 and 2) de-linked from the Yagudo Pipers and Yagudo Persecutors that they are now linked to as an alternative solution, but that's just my opinion.

**Comment by Mozzy4Ever** [comment]
November 19th, 2023 in #patch-notes
![image](https://github.com/EdenServer/community/assets/11255886/e598192d-eeaa-43ab-9be8-c1a3bf3fd279)

That is how it works on retail

**Comment by RyanTevious** [comment]
Okay, I see. Thank you. I brought it up in the discord a while back and was told to make a bug-report for this. I just got around to it now. The one Yagudo that is stuck is still an issue, however.

**Comment by 59blargedy** [comment]
Resolved in July 5, 2024 patch by correcting the placeholder and increasing chance of pop. Slotting/alternating is appropriate. 
if the yagudo mendicant continues to get stuck, please file as a separate issue, im unable to recreate.
