### ISSUE TITLE
Olla Media takes excessive damage from Sirrocco Kukri when Spectral Barrier is active.

### ISSUE THREAD

**Issue by danielson144** [EdenServer/community#5847]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X ] I have provided my client version in the details. (type /ver into your game window)
- [X ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The wind added effect of Sirrocco Kukri is dealing anywhere from 300-1100 damage a hit on Olla Media (doesn't happen to the first or 3rd olla) when Spectral Barrier is active it seems. See screenshots. I didn't get to test if casting Aero on it does the same, but definitely seems like something is broken with it. 

![image_2024-02-21_150007081](https://github.com/EdenServer/community/assets/76822480/d7ca0ad3-eafc-448b-b90e-e64a76d6312f)
![image_2024-02-21_150018295](https://github.com/EdenServer/community/assets/76822480/44d42067-5cc4-4a92-9358-3e93c9bc8dec)

**Comment by danielson144** [comment]
Forgot to add Version. 30181205_0

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
