### ISSUE TITLE
Nosferatu Nocturnal Servitude draws in regardless of zone

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5849]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
/ver 30181205_0

If Nosferatu does a party draw-in from Nocturnal Servitude while someone is not in zone, that player will be put at 0,0,0 of their current zone.

**Comment by DeuceFFXI** [comment]
Also will draw-in dead party members.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch. think i need to add this to patch notes.
