### ISSUE TITLE
Zhayolm Remnants - darksday > Firesday change causes Porogos to take 0 skill chain damage

### ISSUE THREAD

**Issue by Snugglepunk** [EdenServer/community#5851]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Ver 30181205_0

Unsure if this is intended or a bug~

To repoduce, Enter Zhayolm Remnants on Darksday, wait for game to change to Firesday.  Use any skillchain on any Porogo in the zone and it takes 0 skill chain damage.    

![image](https://github.com/EdenServer/community/assets/56851217/7fc6f650-5054-4da9-92a3-f64f8a3ae71f)
![image](https://github.com/EdenServer/community/assets/56851217/5cbb37a6-b4ed-41b5-991c-5d5f5789b90f)
![image](https://github.com/EdenServer/community/assets/56851217/5673751c-5a0d-495e-9687-77c4dca38799)

**Comment by falzum** [comment]
Poroggo are intended to be immune to the element of the day you entered. Being immune to all 3 darkness skill chains if you entered on darks day makes sense to me.

Now for level 2 and 3 skill chains should it only negate the darkness component of the damage? I can't say

**Comment by Snugglepunk** [comment]
Very cool.  Hmm on darksday they do take darkness skill chain damage (double damage that seems to be unique to darksday). Is why it really confused me with the day change and taking 0.  Thanks for the info.
