### ISSUE TITLE
Drachen Roll buff description incorrect

### ISSUE THREAD

**Issue by AshleyAwakens** [EdenServer/community#5853]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
The roll buff icon for Drachen Roll shows increasing pet accuracy (image 1) instead of pet MATK and MACC as its shown under the phantom roll menu (image 2). The third image below is a before and after of 11 on Drachen Roll using "/checkparam \<pet\>" to show there is no change in physical acc nor atk. Before testing I made sure to download the latest dats from the github and my version is 30181205_0.

I currently do not have Puppet Roll to test if it has a similar issue with the buff icon text but will update this report if needed.

![image](https://github.com/EdenServer/community/assets/119537953/16694302-c389-4270-8b39-0c89ce83e23d)
![image](https://github.com/EdenServer/community/assets/119537953/b5b5a133-48d2-4212-943f-9f1fa9f6c5da)
![image](https://github.com/EdenServer/community/assets/119537953/81dfc89e-fa5b-4b26-856d-5a454b595424)

**Comment by falzum** [comment]
Do you have the updated Dat files?

https://github.com/EdenServer/Eden-Client_DATs

**Comment by AshleyAwakens** [comment]
> Do you have the updated Dat files?
> 
> https://github.com/EdenServer/Eden-Client_DATs

Yes, I said in the original post that I had downloaded the latest DATs before testing this.

**Comment by KnowOne134** [comment]
How do you have the dats loaded? Xipivot or strait replaced in directory?

**Comment by AshleyAwakens** [comment]
> How do you have the dats loaded? Xipivot or strait replaced in directory?

I placed them straight into the directory, the only DAT mods used through Pivot are XIView and the 2x HD pack

**Comment by KnowOne134** [comment]
![image](https://github.com/EdenServer/community/assets/35616771/aefff934-5a60-4e6a-a5eb-cb2d3b8bc928)

![image](https://github.com/EdenServer/community/assets/35616771/09efd2c7-9dae-45bc-a6a5-10cea254406b)

![image](https://github.com/EdenServer/community/assets/35616771/2c5fb672-d2ec-483a-86db-d114b4062b3c)

![image](https://github.com/EdenServer/community/assets/35616771/1d0a5a6f-092a-4d38-8c4f-060f3ccc8ea7)

pictures show that something is not right on your end, tool tip and ability text show correctly and that it is Magic Acc and Attack that are enhanced and wont show on /checkparam but with my gm commands show that they do changed based on roll, yes i still havent changed my plugin data to reflect

**Comment by AshleyAwakens** [comment]
Closing issue because I figured out its an issue with either my XIView or HD dat pack, I relaunched my game with nothing loaded in Pivot and got the correct buff description

**Comment by AshleyAwakens** [comment]
> Closing issue because I figured out its an issue with either my XIView or HD dat pack, I relaunched my game with nothing loaded in Pivot and got the correct buff description

Confirmed that it is my XIView that was causing the issue.
