### ISSUE TITLE
Juice/Drink effect not overwriting itself

### ISSUE THREAD

**Issue by LaurelEden** [EdenServer/community#5855]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Drink effects should overwrite themselves but currently give "no effect" message. tier of drink shouldn't matter, eg orange juice can overwrite melon juice and vice versa

Eden:
![Screenshot 2024-03-07 162405](https://github.com/EdenServer/community/assets/145617205/9b2b77be-367b-4789-a64b-4da4e48af92c)

Retail:
![Screenshot 2024-03-07 162444](https://github.com/EdenServer/community/assets/145617205/c11bfc7c-5dc4-46f5-ba55-9aa3b1e45fb9)

**Comment by KnowOne134** [comment]
But do the effects change or just consume?

**Comment by LaurelEden** [comment]
effects change to the new drink

**Comment by KnowOne134** [comment]
tested myself, as said but will not overwrite but is overwritten by all spells of refresh

**Comment by slassen** [comment]
Test

**Comment by KnowOne134** [comment]
Corrected on 1/5/2024
