### ISSUE TITLE
The Search for Goldmane - Bugged NM respawn

### ISSUE THREAD

**Issue by Chiandra** [EdenServer/community#5856]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X ] I have provided my client version in the details. (type /ver into your game window)
- [X ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Character - Chiandra
Version - 30181205_0

During the quest "The Search for Goldmane" a Weathered Boat is clicked in Purgonorgo Isle and the NM Rohemolipaud is spawned. Once 1400 HP is depleted, he is supposed to use Camouflage and the fight end. Then the weathered boat is clicked again for a cutscene. However, once he is beaten and the boat clicked for the follow up cutscene, the NM simply keeps respawning. I have beaten him 4 times and the cutscene after the fight will not appear.

First pop at 10:28:20
Second pop at 10:29:18
Third pop at 10:30:55
Fourth pop at 10:33:41

![Chiandra_2024 03 10_104022](https://github.com/EdenServer/community/assets/55801859/6a37026d-a8c4-44e4-bbf6-74e4849d1af9)
![Chiandra_2024 03 10_104018](https://github.com/EdenServer/community/assets/55801859/1267e4d5-42bb-443e-8ac1-c918f18873c3)
![Chiandra_2024 03 10_104021](https://github.com/EdenServer/community/assets/55801859/40772c8a-4cb0-42d2-8f80-fd5161dd98e7)

**Comment by 59blargedy** [comment]
kill without a pet and it will work fine, will fix the pet issue for next update.  can alternatively make a gm call and they'll progress you past

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
