### ISSUE TITLE
BRD AF Quest The Requiem - Missing Dialogue

### ISSUE THREAD

**Issue by inaringo** [EdenServer/community#5857]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
version 30181205_0
After completing the quest there should be optional dialogue from Mataligeat which currently missing.
https://ffxiclopedia.fandom.com/wiki/The_Requiem

**Comment by 59blargedy** [comment]
looks like the wiki is wrong here, there's no quest specific dialogue from him. it's just when you are not on bard (at any point during this series of quests when mataligeat doesnt have changed dialogue), you get a different message from him.  This is controlled by the client so is on eden
