### ISSUE TITLE
Log displaying wrong damage when monk mobs Guard

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5858]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Fight Mandragora in Buburimu, mobs had Def down from Acid bolts, and Eva down from Shield Break ws. I keep getting guarded and doing 0 damage according to the log, but if you watch the mobs hp bar it still goes down a little bit so I'm still doing damage.

In the screenshot I posted you can see I hit for 0 but the mob still died. No DoTs were applied.

![image](https://github.com/EdenServer/community/assets/55296729/fa2f8373-caab-477e-a946-d491963a69e6)

**Comment by 59blargedy** [comment]
resolved by another dev in July 5th, 2024 patch
