### ISSUE TITLE
incorrect currency drops from statues

### ISSUE THREAD

**Issue by Bait31** [EdenServer/community#5860]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

i think the wrong currency is dropping from the sergent stats in bubu. from reading wiki it looks like they are ment to drop monti's but they are dropping jades. i dont know if this is what its ment to be or not. last night we got 3 jades from them. have provided ss. i could be wrong and this is how its ment to be, but those stats drop montis in other zones so thought it might be worth mentioning. cheers

![1](https://github.com/EdenServer/community/assets/104273078/38da56e0-6e55-4f0b-ba2e-861d76792fbd)

![2](https://github.com/EdenServer/community/assets/104273078/c54463c3-514c-4be1-8bf2-3be75d136fed)

**Comment by 59blargedy** [comment]
resolved by another dev in July 5th, 2024 patch
