### ISSUE TITLE
Senjuirikio critical hit rate bonus should not apply when equipped offhand

### ISSUE THREAD

**Issue by Corvinus1337** [EdenServer/community#5861]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

In era Senj's damage applies to offhand but the critical bonus should NOT. Currently on Eden the critical bonus is applying when the katana is equipped offhand. Here are a few references:

1) https://www.bluegartr.com/threads/46789-Weapon-Skill-setup-for-nin/page2

"The only thing that carries over from an off hand weapon are stats (STR, DEX, ACC, etc). Critical hit rate and TP bonus are two things that don't

"this is why destroyers are so pwn on mnk and why people cry about it. Because it's the only crit bonus weapon that applies to both hands, which is also why monks tend to parse around 15-16% crit rate.

2) https://www.bluegartr.com/threads/33669-Hm-does-the-6-Critical-Hit-rate-stack

"As far as I'm aware the critical hit rate +6% won't work in offhand but the additional D will.

Version 30181205_0

**Comment by Slamm21** [comment]
This also applies to Thunder and Jupiter Staff. The Critical hit rate on that only applied to the weapon itself, and not any ranged weapons
https://www.ffxiah.com/forum/topic/34712/agi-ranged-attack-critical-rate/

> I asked a member on my linkshell earlier tonight and he referenced a test done on bg a long time ago using thunder staff (simply because no other weapon has dex, not that it affects ranged crit. We all know that thunder staff only affects its own crit hit rate)

All weapons with crit+ on them should only affect that weapon itself

**Comment by Dukilles** [comment]
Resolved in 10/9 patch
