### ISSUE TITLE
Castle Oztroja torches won't light

### ISSUE THREAD

**Issue by gamechld** [EdenServer/community#5862]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Client Version: 30181205_0

There are issues lighting the torches to access the password statues for Passwords 2 & 3 in Castle Oztroja. This was discovered by my full party of 6 when we were working on Limit Break 3 - Whence Blows the Wind. I did a Yell to ask if anyone else ran into this issue, and received a confirmation from another user that said it has been broken for weeks at least. Another user chimed in and said he just guesses the passwords manually since the doors don't work. Thanks for your time!

**Comment by 59blargedy** [comment]
resolved live may? formally resolved in July 5th, 2024 patch
