### ISSUE TITLE
Hell Bat in Phomiuna Aqueducts is incorrectly aggressive

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5863]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Was walking through Phomiuna and got aggro'd by a Hell Bat: 
![image](https://github.com/EdenServer/community/assets/95725249/2b4b747b-fc2f-4de4-8bb7-33236ea3dc41)

BG Wiki and ffxiclopedia both say that Hell Bat in this zone should link by sound, but not be aggressive: 
https://www.bg-wiki.com/index.php?title=Hell_Bat&oldid=67516
https://ffxiclopedia.fandom.com/wiki/Hell_Bat?oldid=775565

Also, I saw this other open bug report where the title indicates that the Fomor Beastmaster is incorrectly linking onto a Hell Bat, but the description makes it sound like the Hell Bat simply aggro'd instead of incorrectly linking with the Beastmaster.  I'm _assuming_ it's because of this incorrect aggro behavior on Hell Bat but I don't know for certain (and I don't know whether or not the fomor bst not linking with other fomor as described in that bug report is yet another issue anyway): 
https://github.com/EdenServer/community/issues/5361

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
