### ISSUE TITLE
Plague effect from Bugard's Bone Crunch too strong

### ISSUE THREAD

**Issue by AshleyAwakens** [EdenServer/community#5864]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
The plague effect from bugard's Bone Crunch is ~10x stronger than intended. The screenshot below shows an echo output of my tp and mp draining at 500tp and 26mp/tick under the effect of this plague, with TP gained from a Joyeuse. Jimmayus' retail testing spreadsheet that was linked in #Patch-Notes shows that the tp drain effect should be 50tp/tick, and other plague effects have the same 50tp/tick listed along with 3mp/tick. Linked [here](https://docs.google.com/spreadsheets/d/1YBoveP-weMdidrirY-vPDzHyxbEI2ryECINlfCnFkLI/edit?pli=1#gid=57955395&range=A370:D370) is that Monster Stats spreadsheet showing the tested values of Bone Crunch. My client version is 30181205_0.
![image](https://github.com/EdenServer/community/assets/119537953/be6a9f04-99a1-47e6-b4ff-2a215123f9f0)

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
