### ISSUE TITLE
Crash in Lufaise Meadows

### ISSUE THREAD

**Issue by WhitewizardXI** [EdenServer/community#5866]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I outposted into Lufaise Meadows on 2 characters and both DCed to the character selection screen, when i try to log back in i get stuck in downloading data until booted back to character selection. i am still able to log into mules in town.

/ver 30181205_0

![img_20240421_104352](https://github.com/EdenServer/community/assets/62189912/17f2a637-f5c8-46fa-aef7-505e82f38be1)
![img_20240421_104415](https://github.com/EdenServer/community/assets/62189912/e6897d5d-856d-4e03-8ce3-01b27f8ed9ff)

**Comment by AshleyAwakens** [comment]
![image](https://github.com/EdenServer/community/assets/119537953/8fe42785-e8fd-4daa-90e0-def1bb27335a)
I'm not sure what it is but it wasn't a zone crash since !uptime shows Lufaise being up for almost a month at time of writing.

**Comment by WhitewizardXI** [comment]
fixed

**Comment by WhitewizardXI** [comment]
fixed
