### ISSUE TITLE
charmed scent mobs  attacking BST after raising

### ISSUE THREAD

**Issue by StormyEden** [EdenServer/community#5868]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

BST player died while having a pet with Scent  tracking(a raptor), pet was un-charmed and chased after the BST from over 50+yalms after they had raised up  30seconds~ after (BST) death

Scenario was - raptor attacking another mob while BST had 2 additional mobs aggro'd onto them, they ran off to die in safe area and after waiting a good amount of time to let the aggro'd mobs despawn or walk away they raised up. The raptor that was the pet then  ran all the way to them and killed them.

Pets should be immediately un-charmed upon players death and should not be aggroing in anyway other than normal distance detection

version 30181205_0

**Comment by ConteAlmaviva** [comment]
Probably related to (or same issue as) https://github.com/EdenServer/community/issues/4649.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
