### ISSUE TITLE
Goblin Archaeologist ??? has weird messages. NM's drops and stealing seem unfinished.

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#5872]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver 30181205_0

Repeatable steps:
1) Trade items with merchant value to the ??? at one of crags
2) Observe messages
3) Keep trading to pop the Goblin
4) Steal from the Goblin
5) Kill the Goblin

I've randomly teleported LS members after an event multiple times now and forced them to help me pop this NM for fun, but there is a few issues:

1) Some of the messages are wrong in different zones. For example you get a message seemingly meant for Treasure Caskets if your offer is refused at Crag of Dem. If needed I can detail them.

2) You seemingly cannot steal a Gold Beastcoin from it. Myself and other THFs have tried 10+ times and nothing, (I am using all possible steal + equipment with the exception of the latent effect ring). 

3) Finally, the drops, even with TH4, seem to only include the Gold Beastcoins (which appear to have the correct odds). However none of the other random junk will drop it. I know the junk items probably range from a in drop rarity tiers from 2.5% ~ 8% ~ 18% with TH4 but I've killed it enough times I'm positive I should have seen something. But, I will continue killing and will log results if needed.

On a positive note, the ??? does move and the actual Goblin seems to indeed have a massive level range, from 30 to 75.

Also, I have no idea if it actually has the 'Frag Bomb' WS, as I've never seen it or the normal Bomb Toss happen, only Goblin Rush.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch. drops unchanged, they are there!
