### ISSUE TITLE
Marble Bridge Eatery in Jeuno Displays Incorrect Text

### ISSUE THREAD

**Issue by Loolwindurst** [EdenServer/community#5873]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The Marble Bridge Eatery in Jeuno is displaying the incorrect text, at least for races when the day is a race. I attempted to enter as an Elvaan when told it was Elvaan day, and was denied. I then attempted to enter on the Tarutaru day, and was allowed entry. I will link an image below showing this, and my client version. 
![MarbleBridgeEateryBugReport](https://github.com/EdenServer/community/assets/138258001/9ea4323f-1581-470c-bb2c-a8744044714d)

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
