### ISSUE TITLE
Completeing Divine Might didn't complete Zilart Mission 14

### ISSUE THREAD

**Issue by OniHavoc** [EdenServer/community#5878]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ?] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

6/7 I completed Divine Might on two of my characters but it didn't give me the clear for zilart mission 14. Recieved my earrings and divine might showing under completed quests but both characters are still on zilart mission 14 ark angels. Both classic and current wikis state that clearing Divine Might will complete Zilart Mission 14.

https://ffxiclopedia.fandom.com/wiki/Divine_Might?so=search
https://classicffxi.fandom.com/wiki/Divine_Might?so=search

![fansdm](https://github.com/EdenServer/community/assets/91109644/a42469ae-1a3b-4fc7-a6b0-fc744bfc09ba)
![fanss](https://github.com/EdenServer/community/assets/91109644/f33ac794-0717-4725-9f76-a747f5b96f03)
![fansz](https://github.com/EdenServer/community/assets/91109644/88d5ae08-0ccc-4cfe-a0c1-e81c29920885)
![kickdm](https://github.com/EdenServer/community/assets/91109644/a9ac0174-ab2c-456d-906e-f868b6239bf1)
![kicks](https://github.com/EdenServer/community/assets/91109644/8aebead1-1085-4308-9214-3b5ea0f41dde)
![kickz](https://github.com/EdenServer/community/assets/91109644/81283f4a-a5da-4dc2-9644-88efad6c2f1f)

**Comment by falzum** [comment]
Have you tried doing the next step in the missions and talking to Gilgamesh in Norg?

**Comment by OniHavoc** [comment]
yes i didn't realize something was wrong until i came back for the cs with lion

**Comment by KnowOne134** [comment]
can you check your keyitems and see if you got all 5
```lua
if
    player:hasKeyItem(xi.ki.SHARD_OF_APATHY) and
    player:hasKeyItem(xi.ki.SHARD_OF_ARROGANCE) and
    player:hasKeyItem(xi.ki.SHARD_OF_COWARDICE) and
    player:hasKeyItem(xi.ki.SHARD_OF_ENVY) and
    player:hasKeyItem(xi.ki.SHARD_OF_RAGE)
then
    mission:complete(player)
```
