### ISSUE TITLE
Apollo staff proc damage

### ISSUE THREAD

**Issue by cragsten** [EdenServer/community#5879]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

![Qori_2024 06 11_003539](https://github.com/EdenServer/community/assets/151593935/aaced7fa-5681-4758-9125-c24ed7686d26)

Apollo staff just proc 992 addition damage on a bat eye in the glacier. Look at the bottom of the screen shot.

**Comment by cragsten** [comment]
actually not 100% sure it was apollo staff , it could have been my Holy Maul +1 , they both proc light damage and the whm uses that as her primary weapon , but i had cast cures and it swaps her to apollo staff. so it could have been either of the 2.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
