### ISSUE TITLE
Dire Bat in Newton Movalpolos should not be aggressive

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5882]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Got aggro from Dire Bats while walking through Newton Movalpolos:
![Rozsika_2024 06 27_140215](https://github.com/EdenServer/community/assets/95725249/3b459470-f47a-4a3b-aa37-f90756cc1c4a)

Both FFXIclopedia and BGWiki claim that these bats should be non-aggressive in Newton specificially:
https://ffxiclopedia.fandom.com/wiki/Dire_Bat?oldid=734606
https://www.bg-wiki.com/index.php?title=Dire_Bat&oldid=96755

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
