### ISSUE TITLE
Feast of Swords event Armor NMs stop moving indefinitely if zoned

### ISSUE THREAD

**Issue by AshleyAwakens** [EdenServer/community#5883]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
With the new Feast of Swords event, if one of the Armor NMs is aggroed to you and you either zone or die, the NM stops moving indefinitely until reaggroed. Image 1 shows the Omodaka Armor remaining at the South Gustaberg zoneline to Bastok markets for over 7 minutes (zoned at 14:39:40 and image taken at 14:47:07), while Image 2 shows the Hachiryu Armor remaining stationary for over 2.5 minutes after zoning at the time of screenshot.  While I did not take a screenshot of it, I also came across a stationary Hizamura Armor in the far NE corner of (L-8) in S.Gustaberg at 28% hp, leading to the conclusion that the movement also freezes on death. My /ver is 30181205_0.
![image](https://github.com/EdenServer/community/assets/119537953/866134e7-fb65-4e53-9b94-6e9236d85988)
![image](https://github.com/EdenServer/community/assets/119537953/8565ce8f-8ae7-435c-bd6e-f2fefcfd40fd)

**Comment by 59blargedy** [comment]
resolved in bugfix patch July 6, 2024
