### ISSUE TITLE
Cannot obtain Parradomo Stones item for Boneyard Gully ENM

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5885]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Got the Flaxen Pouch from the Attohwa Chasm ENM dude, climbed the mountain, traded the pouch to the "Cradle of Rebirth," did not get any messaging at all and Flaxen Pouch is still in inventory:

![Rangua_2024 07 05_182525](https://github.com/EdenServer/community/assets/95725249/0b454d75-ed09-4d7f-a967-196330666488)
![Rangua_2024 07 05_182534](https://github.com/EdenServer/community/assets/95725249/a25ba521-a238-41a7-80d1-191effc86617)

expected: enm item plz :(

**Comment by 59blargedy** [comment]
is your inventory full?

**Comment by 59blargedy** [comment]
nvm i see the issue

**Comment by 59blargedy** [comment]
resolved in bugfix patch July 6, 2024
