### ISSUE TITLE
Dragoon Wyvern not auto-attacking during Sheep in Antlion's Clothing ENM

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5886]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

I entered Boneyard Gully on DRG/NIN in a party with one other character and my wyvern was already summoned.  Entered the arena, engaged Tuchulcha and my wyvern did not auto-attack at all, it just stayed idle the entire time and followed me around:
![image](https://github.com/EdenServer/community/assets/95725249/c31350e9-761b-4484-b660-09213a7f1b6c)

Screenshot is all I have, but it is noticeable wyvern is facing me and not the monster and nothing in chat log about Mikan doing anything

edit: my chat log doesn't show me actually hitting the mob because my battlemod has that filtered out, but I did hit it, used jumps and penta thrust on it

**Comment by 59blargedy** [comment]
it seems limited to when you have a wyvern up from outside the bcnm vs calling it inside, where it will auto attack. i get it's still a bug, just want to clarify.

**Comment by 59blargedy** [comment]
resolved in july 12, 2024 maintenance
