### ISSUE TITLE
Damselfly Spawns in Valkrum Dunes (Despawning)

### ISSUE THREAD

**Issue by InoSiX** [EdenServer/community#5888]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version: 30181205_0

This may very well apply to other places, but I am witnessing it in real time at Valkrum Dunes near the Whitebone Sands Beach. The Damselflies that otherwise spawn Valkrum Emperor. There is traditionally two on the far West side of the beach, two more to the North West of that, and at least one on the far East of the beach. Of the 4 on the far West side of the beach, they seem to consistently despawn, as if they were brought to an area outside their patrol range due to aggro.

I am the only person in the zone. There is no one moving these flys. **LIVE EDIT** It isn't just flies, I just witnessed a Golbin Mugger do the same thing. I am actively hunting VE right now. These mobs are despawning for no reason.

**Comment by hyakuzaku** [comment]
I saw a tiger despawn in Batallia Downs, then a bird randomly spawn near where it was, no people in the zone but me and I wasn't killing anything.

Also there were no skeletons out at nighttime, only wolves.

**Comment by Frozzen907** [comment]
Also witnessed this in Rolanberry Fields. The Ochu near the lake at Simurgh spawn area was doing this. Ochu would path around randomly as usual, then just disappear as if it was killed... then respawn again.

**Comment by Daywhite83** [comment]
Sometimes the damselfly's will spawn, then immediately start to despawn to the point where i cant even RA to claim them before they despawn.
Ive watched the Thread leeches and Snippers also despawn here.

**Comment by Nadrojj82** [comment]
Things have been strange in Konschtat Highlands, a sheep in the north mary camp with no name plate. I camped mary for 8 hours going back and forth between the two camps chasing the placeholder. No pop. This morning widescan mobs still seem to be incorrect.  Here is an example of the sheep in the north camp that isn't showing up on widescan and has no name plate. This screenshot was taken two days ago so it may have been addressed but still wanted to call it to attention as my gm ticket didn't get an answer. 

![Nadrojj_2024 07 10_201524](https://github.com/user-attachments/assets/e841a521-6b61-4ac8-8fc0-aed97676a61c)

**Comment by 59blargedy** [comment]
resolved by another dev in a previous update - if you're still seeing despawning issues can comment here and ill open a new ticket

**Comment by hyakuzaku** [comment]
> resolved by another dev in a previous update - if you're still seeing despawning issues can comment here and ill open a new ticket

Also there still no skeletons out at night time in Batallia Downs with the exception of ones near Lumberjack, only wolves. I'm unsure if this is related but it happened after the same update.

**Comment by 59blargedy** [comment]
oh - yes that was a patch note - they are slotted with their beastmen counterparts, with the exception of the ones near Lumberjack. this the case in most zones and was done deliberately and was part of era.
