### ISSUE TITLE
Ifrit's Cauldron Mining

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#589]
Nodes are currently spawning on top of one another -- up to five in one spot making it appear as if there is only one node in the zone when in reality they're all clustered on top of one another.

Here's an imagine of what it looks like, you can see there are multiple effects there. 

http://i63.tinypic.com/2j758x.jpg

**Comment by tectal831** [comment]
If possible, please look into ore rates as well to take out both tickets at once

**Comment by TracentEden** [comment]
This issue still appears to happen on Eden in IC (at least) as sometimes multiple mining nodes will spawn at the same location  thus "clogging up" mining if that location is not mined for some time, Thus may need to reopen this ticket. I checked on DSP and there does not seem to be a check to see if a potential location already has a mining point there. If this behavior is retail accurate then can ignore, but I do not remember this happening there.

**Comment by ThoseWhoFight** [comment]
Just noting, this seems to be true for all types of gathering. Can confirm for logging at least, and also in every zone where it's possible. Not exclusive to just mining and Ifrit's Cauldron
