### ISSUE TITLE
Feast of Swords: Per-Character Reward Bug (Malice Not Resetting?)

### ISSUE THREAD

**Issue by Avarghaladion** [EdenServer/community#5890]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

30181205_0

Certain characters seem to eventually become unable to obtain anything but Stable Collars regardless of what their absorbed Malice total should be, despite having not yet received Hardwood Katana or other weapons. Affected characters tested all Malice values from 0-10+ and now always receive Collar. In one instance a character traded with 0, received a Collar, then immediately traded again to the same ??? resulting in another Collar. It appears that Ibushi shinai's Malice total is not correctly resetting on trade for some characters.

While this was happening, other characters had no issue always getting weapons at 5 Malice so appears to be a character specific issue. Race of the characters observed to have been affected by this bug is Taru and Mithra but unsure if there's a connection.

**Comment by 59blargedy** [comment]
if players have the item in their inventory already, their malice does not clear. they need to drop it, claim the reward anew, and then points are reset. 

there should be another reward when people have the collar of that zone, so can patch it with something along those lines but until then you have to drop.

**Comment by Avarghaladion** [comment]
> if players have the item in their inventory already, their malice does not clear. they need to drop it, claim the reward anew, and then points are reset.
> 
> there should be another reward when people have the collar of that zone, so can patch it with something along those lines but until then you have to drop.

Weird. Other characters not having the issue. Eg. I never dropped the collar on any of my chars, did a ton of 10+ trade before seeing 5 was the sweet spot, then switched to 5 and got nother but weapons then a normal collar/mochi split after receiving Hardwood.

**Comment by 59blargedy** [comment]
resolved in July 12, 2024 maintenance to allow granting other items if you already have the medal
