### ISSUE TITLE
Have to talk to Naja twice to trigger Corporal Rank up

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5892]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

https://ffxiclopedia.fandom.com/wiki/Promotion:_Corporal

I had to talk to Naja twice to start and complete the Corporal rank up mission. Her first dialogue both times was something generic about how much I owe her. 

Fariska mentioned he only had to speak with her once to start Corporal rank up, and thinks it might be because I'm done with ToAU missions, and he isn't.

**Comment by KnowOne134** [comment]
absolutely right, is becuase you are done with the missions. good find and made the find the fix way more easier

**Comment by KnowOne134** [comment]
this has been completed
