### ISSUE TITLE
ZM8 Kam'lanaut healing from incorrect elemental damage

### ISSUE THREAD

**Issue by AshleyAwakens** [EdenServer/community#5894]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
During the ZM8 fight against Kam'lanaut, he was healed by a Blizzard IV that was cast on him while he had Enstone up. According to several wikis ([ClassicFFXI](https://classicffxi.fandom.com/wiki/Return_to_Delkfutt%27s_Tower), [FFXIclopedia](https://ffxiclopedia.fandom.com/wiki/Return_to_Delkfutt%27s_Tower?oldid=642941)), he should only be healed from damage that matches the element of his current enspell buff.

From the battlemod combat log shown below, the following events occurred as such:
- [14:49:52] Enaero buff dispelled.
- [14:49:56] Thunder IV dealt 949 damage with no enspell active.
- [14:50:11] Kam'lanaut gains Enstone.
- [14:50:15] Blizzard IV healed for 912 hp with Enstone active.
- [14:50:21] Enstone buff dispelled.

I was not able to test further if an active enspell buff caused all elemental damage to heal him.
![image](https://github.com/EdenServer/community/assets/119537953/47482963-7dfb-4e6d-8111-c61096b1f5b4)

**Comment by 59blargedy** [comment]
resolved in July 30, 2024 update
