### ISSUE TITLE
unable to open the inventory in salvage

### ISSUE THREAD

**Issue by Maesedanielot** [EdenServer/community#5896]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

During a SSR run , only on danielot, it happened twice.

somehow the /item screen u select to use cells and temp items, was bug, only showing fireflies, this somehow caused the main menu "items" to open the same bugged inventory, with only showing fireflies. 

somehow the bug was gone after 3min waiting. 

didnt took screenshoots

**Comment by Dukilles** [comment]
will try to reproduce. any info you can try to remember will be helpful

**Comment by Avarghaladion** [comment]
> will try to reproduce. any info you can try to remember will be helpful

Happened to me last night as well. Occurred every single time I used any temporary item. Hitting auto sort made the inv reappear each time but still very annoying.

**Comment by Maesedanielot** [comment]
i can confirm i was the only one in my team using temp items so prolly has to be on that interaction

**Comment by Dukilles** [comment]
working on a solution, looks like we've got it identified. thanks for letting us know

**Comment by 59blargedy** [comment]
retested ghosting and still doesnt occur. 
able to see items in both items menus in salvage, and use regular and temp items with no issues. 
interestingly, the cleanup for temp items blanks out the entire item list and then refreshes, while using a normal item just gently slides the inventory up.

**Comment by 59blargedy** [comment]
awkwardly just posted this to community but
retested ghosting of cells and change does not remove that fix
temp and regular inventory items appear in both items menus and using items does not cause issues.
