### ISSUE TITLE
Humilus Cells giving max hp AND mp

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5897]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

As of 7/7 Humilus Cell currently is unlocking max hp and mp. Spisstatus isn't doing anything

**Comment by 59blargedy** [comment]
resolved in July 12, 2024 maintenance.
