### ISSUE TITLE
Dynamis-Beaucedine Hydra Invisible

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#5900]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
30181205_0
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Doing Dynamis-Beaucedine last weekend, we noticed some but not all Hydra mobs were invisible. We could see the names for all but not the monsters themselves. Pets were always visible.
I don't think we had a problem with this with the attestation hydras, just the ones in the hydra area of the map

**Comment by MeshGearFox** [comment]
Noticed the same issue in Dynamis-Tavnazia after the July 5th patch. Most of mobs were visible, but there were a few that we could only see their names. IIRC the few that were invisible were all Hydra mobs.

**Comment by 59blargedy** [comment]
resolved in July 30, 2024 update
