### ISSUE TITLE
Blade Bash Rarely Stunning after patch. 

### ISSUE THREAD

**Issue by Frozzen907** [EdenServer/community#5904]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Ver: 30181205_0

Ever Since July 5th Patch Blade Bash (Unsure if other bashes are also acting this way) rarely stuns the mobs anymore. 
Classic Wiki states it's a 90-100% chance and Retail wiki says 99% chance of stun; Going back in Retail Wiki History; it appears Stun chance was very low until the August 28 2007 Update, Where it was changed to 90-100% chance to stun.

**Comment by 59blargedy** [comment]
resolved in July 30, 2024 update
