### ISSUE TITLE
Cannot enter Undersea ruins with Salvage permit from Caedarva Mire via Nuimahn

### ISSUE THREAD

**Issue by Pingletown** [EdenServer/community#5905]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version 
30181205_0
I ran out using my salvage permit to the cutter from nashmau, but when I wanted to return via the same path the NPC Nuimahn keeps asking for 1 imperial silver and will not allow entry, Happened for multiple characters.
I believe all entry ways are meant to allow passing through with the permit.
![Nuimahn the jerk](https://github.com/user-attachments/assets/68b0bf3a-1d1e-40b8-81ce-09ba8189c77a)
![Uploading Nasheefa the chad.PNG…]()

**Comment by Pingletown** [comment]
![Nasheefa the chad](https://github.com/user-attachments/assets/da0dc2fe-705b-4c1e-9e28-58b44a809706)
Added cos i didn't let it actually upload the picture,

**Comment by 59blargedy** [comment]
resolved in July 30, 2024 update
