### ISSUE TITLE
Demolition Duty - Wreckage should be able to spawn their crab more than once

### ISSUE THREAD

**Issue by Dukilles** [EdenServer/community#5906]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Retail captures appear to show that the Wreckage will spawn their Carrion Crab on Slapstick given:
- The Slapstick does not kill the wreckage
- The Carrion Crab is not already spawned

https://www.youtube.com/watch?v=83G3H2bbsJ4

Timestamp is about the 13 minute mark. Also below HPTrack showing the same ID being killed twice.

![image](https://github.com/user-attachments/assets/699a52dd-9f4f-4f8a-9082-76c43ceffb91)
![image](https://github.com/user-attachments/assets/19f91b59-48b0-41b7-9a4b-c416513cdda7)

ver 30181205_0

**Comment by KnowOne134** [comment]
resolved 10/8/2024 up update
