### ISSUE TITLE
Low level mobs have increased magic accuracy

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#5907]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window) 30181205_0
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Started playing again after the update. Been sittin in Quu Domi's room for about 3 days now on and off camping. Noticed while fighting the level 30ish yagudos and their elemental pets that their magic accuracy was insanely high. In the 3 days of on and off camping (So far have killed Domi 21 times) I have only resisted 2 Foe Requiiem II's. Every Ninjutsu has landed, every Elemental DOT has landed, every Gravity, and Lulluby has landed. 

Something seems off. 

JOB: SAM75/WAR37, no minus resist gear except dark. Elvaan

**Comment by 59blargedy** [comment]
resolved in July 30, 2024 update
