### ISSUE TITLE
Auto RA emnity late on miss

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5908]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Killing bst pets on pup I'm noticing that the mob moves differently depending on whether the RA that pulled it hit or missed. If the auto's RA misses then the mob only starts moving much later. And if it hits then the mob immediately starts moving towards to auto.

**Comment by Dukilles** [comment]
Resolved in 10/9 patch
