### ISSUE TITLE
Rain Hat regen effect not working

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5909]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

I had my Rain Hat on while it was single water weather in both Caedarva Mire and Periqia and I did not recover any HP on either of my characters.
 
example screenshot, at 1101 HP with rain hat on, additional screenshots taken 7 game minutes later and after exiting to Caedarva with single water weather up the entire time:
![Eko_2024 07 18_202725](https://github.com/user-attachments/assets/fa22c721-fb04-44aa-982a-7f2df2ccbbb0)
![Eko_2024 07 18_202741](https://github.com/user-attachments/assets/a69eae37-8238-48e0-ac7b-dfc1338f81a5)
![Eko_2024 07 18_203057](https://github.com/user-attachments/assets/7b6408e0-5104-402a-933f-32140580d8f7)

**Comment by Avarghaladion** [comment]
Having the same issue. I believe it was working prior to the last patch but not certain.

**Comment by 59blargedy** [comment]
resolved in July 30, 2024 update
