### ISSUE TITLE
FISHING: gold carp catch rate

### ISSUE THREAD

**Issue by blacknesscrows** [EdenServer/community#591]
Setzor,

I fished in windy walls for a while and i notice the catch rate between moats and goldies are about 1:1. In my retail experience I remember catching significantly fewer goldies/moat. 

It's possible higher skill may impact the rate at which goldies bite but I dont think that is the case. 

Sootle

**Comment by blacknesscrows** [comment]
back in the day this was a popular spot to grind moats while skilling on the elusive goldies. at the current rate i will probably hit cap before I even get half the moats for lu shang.

**Comment by Setz0r** [comment]
I have a fix submitted already that is a sweeping adjustment of the rarity on all fish that need it.  This is something that will have to be continuously audited.  Thanks for reporting.
