### ISSUE TITLE
Ghouls are not spawning at night in Valkurm Dunes

### ISSUE THREAD

**Issue by Mirridelle** [EdenServer/community#5910]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Went to Valkurm Dunes to help a new player with subjob quest, and noticed that not a single ghoul was spawning even at night in-game (from 20:00 to 4:00). Ran around the zone with 75 RNG Widescan and didn't see a single ghoul on widescan. Other players I've spoken to who tried to help with subjob quests have said the same thing, they can't find any ghouls.

Ghouls are still available to hunt in Gusgen Mines.

To reproduce: just go to Valkurm Dunes at night and look for ghouls, with or without widescan

Version 30181205_0

**Comment by 59blargedy** [comment]
hi there, thanks for reporting. this is not a bug - the ghouls alternate with goblins. when you kill particular goblins during nighttime hours they will spawn ghouls. This was done in multiple areas (can see all adjusted in patch notes) and is accurate.

**Comment by Avarghaladion** [comment]
> hi there, thanks for reporting. this is not a bug - the ghouls alternate with goblins. when you kill particular goblins during nighttime hours they will spawn ghouls. This was done in multiple areas (can see all adjusted in patch notes) and is accurate.

Might that behaviour not be OOE? I always farmed peoples' Skulls from the Dunes in era and goblins dying for them to pop was not a requirement. Could see them on widescan as soon as nighttime hit even if there was no one in zone killing goblins at all. Similarly, had to adjust pulls for them in some camps at night even if Goblins were not being killed. Could this be something retail did post-era to make zones easier for low level players?

**Comment by Steam-arch** [comment]
This was actually (atleast) first mentioned in a Booklet released in japan called Final Fantasy XI Maniax Hunter's Bible, That booklet is way way older than 2014, couldnt find the exact release date with a quick peek, but propably pre 2008.

Heres a translation from it

![image](https://github.com/user-attachments/assets/4865189b-cc6d-4657-8feb-a7848deacf5c)

Can download the entire booklet (in japanese) at https://drive.google.com/file/d/1YP1ocr1rfbuzmcSUprs_psYYp4c56JeR/view 

Unsure if there was regional differences/other things going on

**Comment by Avarghaladion** [comment]
I suspect the alternating spawn behaviour existed in tandem with the normal nighttime spawns vice being the _only_ means of spawning these mobs. While it appears that the changes SE eventually made to mobs in retail solidified the alternating spawn system as being the only way to get them on retail now, Eden's pre-patch nighttime spawn positions/behaviour appeared to be era accurate.

**Comment by Steam-arch** [comment]
Heres a mention of it in December 2008

![Screenshot_2024-07-21-20-57-15-96_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/f1cd5ad1-6ea9-443a-8b8c-bd4675fd4f41)

![Screenshot_2024-07-21-20-57-32-35_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/a446e89b-9f53-45ba-91d6-735f76b58795)

**Comment by Avarghaladion** [comment]
Weird. I know I've watched them spawn in era without any parties present or beastmen being killed so I'd tend to agree with the sentiment in several of the references we found that it got changed at some point, maybe in one of the patches that made the gamer easier. Regardless, based on your examples it definitely seems to be in-era behaviour, for better or worse.
