### ISSUE TITLE
Euhvis double damage while flower is open mechanic not working

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5912]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Euhvis 2x damage while flower is open doesnt seem to be working. Atleast true with Garden of Ruhmets Aw'euhvis. Damage triggers the closing of the flower but doesnt actually do double damage.

open flower damage vs closed flower damage
![image](https://github.com/user-attachments/assets/49f1bcd1-23b1-418d-80a7-09b6cb1d0433)

Also noticed that the flower opens after being woken (after the internal timer is due) from sleep. is this intended or is it supposed to open while still slept also?

**Comment by 59blargedy** [comment]
double damage doesnt apply to magic, but leaving open to resolve the sleep thing.

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update, need to add patch note
