### ISSUE TITLE
Assassin Flies/Flies might be missing +25% piercing bonus?

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5913]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Could use a check maybe? Damage difference Between Magmatic erucas and Assassin flies with polearm/dagger doesnt seem high enough to reflect +25% pierce dmg bonus. Highest pentas and crits are all vs erucas, other sam had a average WS ~11% higher VS (thf and other sam had ~same averages on both mobs) Flies but Crawlers have cocoon + other variables (like berserk/preferences to use warcry/hasso vs flies to boost numbers) in play.  

![image](https://github.com/user-attachments/assets/a7cde2a5-0340-4961-adaf-af174c732db0)

Highest pentas are the pretty much the same with crawlers and flies (or slightly higher on erucas, lower sample rate with flies)
![image](https://github.com/user-attachments/assets/1247cf6a-942f-4af8-af32-6d3ca77b91b4)
![image](https://github.com/user-attachments/assets/8d7a49db-0574-4955-9fe0-945fb1c02ed6)
THF has highest crits vs erucas
![image](https://github.com/user-attachments/assets/0ead2548-90bd-47e0-ae8f-12d11ccdc842)

![image](https://github.com/user-attachments/assets/b01511dc-72bd-4922-acbb-0b3100e7d470)

**Comment by 59blargedy** [comment]
assassin flies do have the 25% piercing bonus, including on weaponskills.
