### ISSUE TITLE
Fly Families in Promathia/Aht Urghan might be missing Somersault + Debilitating Drone

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5914]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Another "Might" report, but atleast Asssassin flies in MountZ might be missing Somersault and Debilitating Drone. I feel like I have never seen Assassin flies (or any other honestly) use these and flies just spam Venom and Cursed Sphere, I didnt even remember they had more than 2 WSs untill I checked their page.  Might be missing them in other zones aswell as wiki states Flies use them in Promathia and Aht Urghan areas.

![image](https://github.com/user-attachments/assets/bb674213-7120-4e32-8b7b-c8d16cc4063c)

**Comment by 59blargedy** [comment]
looks like it's cop only from retail testing, and DD is nm only

**Comment by 59blargedy** [comment]
resolved in July 30, 2024 update
