### ISSUE TITLE
Riding on th Clouds - Fontoumant did not accept Kindred Seal

### ISSUE THREAD

**Issue by Twobutts22** [EdenServer/community#5917]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
While doing limit break 4 I got Fontoumant as one of my npcs. When going to trade him a seal I clicked on him first which activated his quest, "The Brugaire Consortium". I then tried to trade him a seal and nothing happened (seal remained in my inventory). I then completed the quest and he still did not accept the seal. Also tried rezoning and relogging but this did not fix the issue. A GM got back to me today and confirmed the issue and changed my npc, saying that the issue is with Fontoumant. Unsure if it would have worked if I hadn't started the quest or not.

**Comment by 59blargedy** [comment]
resolved in July 30, 2024 update
