### ISSUE TITLE
Mobs in Dynamis - San d'Oria Despawning

### ISSUE THREAD

**Issue by Daywhite83** [EdenServer/community#5918]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- version 30181205_0
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Last night when my linkshell was doing Dynamis - San d'Oria, we noticed that if someone had aggro'd a statue and died before any action was taken on the associated mobs, the mobs would despawn (the statue did not) This happened to us only a few times at the beginning near the fountain during wave 1.

**Comment by 59blargedy** [comment]
i could not replicate this so if others encounter it please supply any additional details you can think of

**Comment by Croftings** [comment]
This has happened to us in both Dynamis Bastok & Sandoria  - When the puller dies the mobs despawn.. The pull I noted in particular was statue #78 in Dynamis Sandoria (Vanguard Mesmerizer).

Our THF Range attacked #79 and subsequently aggro'd #78 which spawned Vanguard Mesmerizer, THF got slept/stunned whilst the Mesmerizer's nuked him to death during stun/sleep. Only noticed the Mesmerizer's despawning and not the mobs from Statue #79

![dynaissue](https://github.com/user-attachments/assets/4a8efe4d-ab9f-4fc8-bbff-68abba36c494)

**Comment by Croftings** [comment]
This has happened to us in both Dynamis Bastok & Sandoria - When the puller dies the mobs despawn.. The pull I noted in particular was statue 78 in Dynamis Sandoria (Vanguard Mesmerizer). 

Our THF Range attacked 79 and subsequently aggro'd 78 which spawned Vanguard Mesmerizer, THF got slept/stunned whilst the Mesmerizer's nuked him to death during stun/sleep. Only noticed the Mesmerizer's despawning and not the mobs from Statue #79
> 
> ![dynaissue](https://private-user-images.githubusercontent.com/66039475/368546371-4a8efe4d-ab9f-4fc8-bbff-68abba36c494.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTg5ODAsIm5iZiI6MTcyNjY1ODY4MCwicGF0aCI6Ii82NjAzOTQ3NS8zNjg1NDYzNzEtNGE4ZWZlNGQtYWI5Zi00ZmM4LWJiZmYtNjhhYmJhMzZjNDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDExMjQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZDUxZGNhODVhZmZjMGM0YjQzZjQ4ZjRhMzJlZjA2OWQxY2RiOTIwNjE2MzkwNGE4NDEwNDBlMzNlNDZjNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CNJNvG1mZ-WH9Sm0O1vMy4lM6pMlLmVC9IDTPeMvcSc)



> i could not replicate this so if others encounter it please supply any additional details you can think of

This has happened to us in both Dynamis Bastok & Sandoria - When the puller dies the mobs despawn.. The pull I noted in particular was statue https://github.com/EdenServer/community/issues/78 in Dynamis Sandoria (Vanguard Mesmerizer).

Our THF Range attacked https://github.com/EdenServer/community/issues/79 and subsequently aggro'd https://github.com/EdenServer/community/issues/78 which spawned Vanguard Mesmerizer, THF got slept/stunned whilst the Mesmerizer's nuked him to death during stun/sleep. Only noticed the Mesmerizer's despawning and not the mobs from Statue https://github.com/EdenServer/community/issues/79

**Comment by Daywhite83** [comment]
When it happened to us the last time we did dynamis bastok. It deported the 3 quadav NM tes.

For one reason or another our sleepers did not get the pull slept fast enough before our puller died.
________________________________

**Comment by KnowOne134** [comment]
Its been figured out and a fix submitted, awaiting a mait to implement

**Comment by Croftings** [comment]
My heroes

**Comment by KnowOne134** [comment]
has been corrected now
