### ISSUE TITLE
Shiva's Shotel additional ice effect not triggering when party member has Shiva summoned

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5919]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Various Wikis state that the additional ice damage effect on Shiva's Shotel should trigger when you yourself or a party member has Shiva summoned:
https://ffxiclopedia.fandom.com/wiki/Shiva%27s_Shotel?oldid=778187
https://www.bg-wiki.com/index.php?title=Shiva%27s_Shotel&oldid=127729

Currently, as BLU/SMN with Shiva summoned, Shiva's Shotel seems to be working correctly:
![Eko_2024 07 22_234755](https://github.com/user-attachments/assets/45ca888b-21c7-4865-8d1d-aad27198950a)

However, a party member having Shiva out doesn't make Shiva's Shotel proc.  An example:
![Eko_2024 07 22_234913](https://github.com/user-attachments/assets/58390863-fc3f-4cc5-bdc9-d93e922692b6)

One screenshot of one fight obviously isn't a huge sample size, but over the course of 2 hours in Dynamis - Bastok, 40~ min killing Lesser Colibri in Bhaflau, or 20 minutes slaughtering monsters in Tahrongi, I did not get a single proc over hundreds of swings which seems exceedingly unlikely when the proc rate is reported to be 40-50% and in the screenshot of it actually working it is about that high.

**Comment by 59blargedy** [comment]
resolved in July 30, 2024 update
