### ISSUE TITLE
BST Skill "Stay" Doesn't Work

### ISSUE THREAD

**Issue by nfontanait** [EdenServer/community#5920]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Client Version: ver.30181205_0
The BST Skill "Stay" does not appear to be functioning. I have attempted to use it on two different Beetles in Garlaige Citadel (one upstairs and one in the basement). In both cases I tried using the ability several times. Each time, the Beetle continued to follow me.
I can try to provide video is necessary/required, though that will take time.

**Comment by 59blargedy** [comment]
resolved by another dev in July 30, 2024 update
