### ISSUE TITLE
Jailer of Fortitude Spams Invincible and doesn't move

### ISSUE THREAD

**Issue by balvont** [EdenServer/community#5922]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Once Jailer of Fortitude 2hr's, it will spam invincible in the same spot until its dead.

![Whim_2024 07 27_203745](https://github.com/user-attachments/assets/5002cddf-59ed-4cb0-b6f6-dc448fe0925d)

![Whim_2024 07 27_201130](https://github.com/user-attachments/assets/3eeb5685-56a9-4cb2-9753-f2bac0a02f9b)

**Comment by 59blargedy** [comment]
resolved July 30, 2024
