### ISSUE TITLE
Mobs in Central Temenos - 1st Floor have powerful regen from the start

### ISSUE THREAD

**Issue by joe-graves** [EdenServer/community#5925]
- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

30181205_0

The July 5th update increased the regen of the mobs once the linked mob has been killed. However, it seems as though mobs in this area now have a very powerful regen even when the linked mob has not been killed. This was not mentioned in the patch notes. Wikis say that they gain HP regen when the linked mob is killed, so I don't think this was an intended effect.

Step to recreate:

1. Enter Temenos - Central 1st Floor
2. Fight a mob without ever engaging it's linked mob
3. The mob will immediately begin to regen what seems like hundreds of HP per tick

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
