### ISSUE TITLE
Sacrifice Torque latent effect broken by 30Jul mini-update

### ISSUE THREAD

**Issue by maxdecphoenix** [EdenServer/community#5927]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver: 30181205_0

The HP/MP drain effect on the Sacrifice Torque is not taking effect, however the +3 Avatar attack is.  Currently, cannot use the piece to break sleep.

**Comment by Avarghaladion** [comment]
Having same issue. Sacrifice torque's DoT effect is not proccing at all. The latent should be active if you or any party member has an avatar summoned.

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
