### ISSUE TITLE
Acid Mist Issue

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5928]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Acid Mist is currently not clearing shadows, not applying attack down, and doing 0 damage. Goblin's Leech from Shephards in Gustav, not sure if other leeches are doing the same.

https://ffxiclopedia.fandom.com/wiki/Acid_Mist?oldid=522094

**Comment by Tofutoshi** [comment]
![image](https://github.com/user-attachments/assets/14361868-7e6e-4f84-9c45-74e71afdae40)

Happening with Great Whirlwind as well, no Choke effect. 0 damage.

**Comment by dowzer** [comment]
This may have been fixed live, Acid Mist is now clearing shadows, applying attack down, and doing damage.

**Comment by 59blargedy** [comment]
closing out, resolved live
