### ISSUE TITLE
Virgo subligar drops from Hume fomors

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5929]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

On eden RNG Virgo subligar drops From Hume RNG fomor/s at Phomiuna Aqueducts (unsure about sacrarium). 

JP wiki states it only drops from elvaan  RNG fomors

![image](https://github.com/user-attachments/assets/6cda01c0-e4a7-41c6-9731-4db2c68a9d68)

so does enclypedia 
![image](https://github.com/user-attachments/assets/b24b7082-d594-4047-a90d-5d94a26bab3d)

**Comment by Steam-arch** [comment]
Throwing in a note that Balloon clothes in Aqueducts drop on singles also

![image](https://github.com/user-attachments/assets/5a907fd3-f851-4094-8437-b84c4c18b36e)

Enclypedia states it drops in pairs

![image](https://github.com/user-attachments/assets/38337e16-f5a6-4524-a512-09e6767b100b)

But here only sacrarium is mentioned 
![image](https://github.com/user-attachments/assets/82bd8eff-06a8-4aec-b689-591b7e9d654c)

Might drop in pairs of two in both zones

**Comment by KnowOne134** [comment]
confirmed that balloon cloth and shakudo ingot always drop in pairs

**Comment by KnowOne134** [comment]
confirmed also on the elvaan only drop at least in aquaducts for now

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
