### ISSUE TITLE
Puk's tp spamming

### ISSUE THREAD

**Issue by Pingletown** [EdenServer/community#5930]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
I was soloing puks outside of mamool staging point for an hour, no issues til one of the last one i fought triggered tp moves 4 times back to back.
![Puk's tp moves](https://github.com/user-attachments/assets/ad889a06-47e8-4446-88ed-e55e6ccc91d6)

I had been casting diaga up til then to clear shadows and it hadn't set off their tp moves like that, so I have zero idea how to replicate but will test next time i have time.

**Comment by falzum** [comment]
Did it become lights day?

Pul family gets max tp if hit with element of the day iirc

**Comment by Pingletown** [comment]
That may have been it then? Can't say i was looking, had no idea that still worked with dia.

**Comment by falzum** [comment]
Yeah I checked the Ingame time after my comment and it was lightsday. That was what it was

**Comment by 59blargedy** [comment]
closing out as this is intended. thank you for checking
