### ISSUE TITLE
Shiva's Shotel's additional ice damage latent triggers on offhand weapon

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5933]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Repro steps:
Dual wield weapons as BLU/NIN (I had Shiva's Shotel mainhand with Beast Slayer offhand)
Have someone in party that can summon Shiva, and have her out.
Hit monsters.
Ice damage can proc on the offhand weapon hit:
![image](https://github.com/user-attachments/assets/c05298ab-f5b7-4b3e-ad0d-0a07891ac24f)

The additional ice damage should (probably) only affect the Shiva's Shotel itself and not the offhand weapon

**Comment by 59blargedy** [comment]
resolved issue in December 14, 2024 update
