### ISSUE TITLE
Attribute merits not reflecting correct values.

### ISSUE THREAD

**Issue by balvont** [EdenServer/community#5935]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

I believe Taru's are supposed to have 76 Base INT at 75BLM/37RDM

Whim - 75BLM/RDM with 5/5 INT merits has base INT of 81. My AGI is 74
Runtz - 75BLM/RDM with 4/5 INT merits has base INT of 81. Runtz AGI is 73

The 5th Merit into INT might be going into AGI in my situation, as I have +1 more than him and we are tied in INT. whatever the case we should not have the same base int considering INT attributes are merited to different levels.

![image](https://github.com/user-attachments/assets/c434a5fd-55a6-47fb-abac-189c42494262)
![image](https://github.com/user-attachments/assets/7d8eb5d9-8dd9-4ffa-a7d2-91de2535a36b)

![image](https://github.com/user-attachments/assets/2d50ad8d-1d63-4e55-a6f9-6e222db21d64)
![image](https://github.com/user-attachments/assets/24b6e98e-ffd7-45af-a355-10b584001d39)

**Comment by Slamm21** [comment]
the alla calculator is dead now I think, but all the correct values are in the spreadsheet from my bug report here
https://github.com/EdenServer/community/issues/2975

**Comment by balvont** [comment]
![image](https://github.com/user-attachments/assets/97f50e99-3592-48e7-b2f2-fd0a946648c0)
![image](https://github.com/user-attachments/assets/4e0425f3-d80a-4ebb-85e7-ad1f9ef1c72a)
Jez, has 0 merits into INT and has base int of 81. 

Thanks Jez for the screenshots, also thanks Slamm for referencing your spreadsheet. Looking that immediately after I finish this post.

**Comment by balvont** [comment]
![image](https://github.com/user-attachments/assets/a419c258-5c0e-4ec6-b2ae-33bbfb312913)
![image](https://github.com/user-attachments/assets/b1eac442-c7ee-4911-ad10-c2a53879de97)
Same with Norrissnake. 81 base int with 0 merits.

**Comment by Slamm21** [comment]
My spreadsheet is about character stats on Eden being wrong in general so was worth mentioning here, but if merits into 1 stat are appearing in another that's a whole different issue.

**Comment by niennaeden** [comment]
I actually just tested this with my taru who had zero INT merits. I put one INT merit in, and her AGI rose by one!!

<img width="133" alt="image" src="https://github.com/user-attachments/assets/b80fea8c-0dc0-40a1-bc62-d96ba98eb203">

<img width="391" alt="image" src="https://github.com/user-attachments/assets/1188b24a-a410-4e4c-b285-8b034c3317b2">

<img width="134" alt="image" src="https://github.com/user-attachments/assets/8b20db31-8422-4e1a-aa9d-a2c27b133cf1">

<img width="393" alt="image" src="https://github.com/user-attachments/assets/ff29cc50-be0c-4940-8e5f-a135d04ac4b4">

**Comment by Dukilles** [comment]
Resolved in 10/9 patch
