### ISSUE TITLE
Jailer of Love's summons attacking incorrect initial target

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5936]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

When Jailer of Love summons its adds, they should initially target the person that Jailer of Love currently is targeting:
https://ffxiclopedia.fandom.com/wiki/Jailer_of_Love?oldid=710641

Last night, when doing JoL, every wave of adds spawned would attack me, ignoring the person that currently has hate. examples:
![Eko_2024 08 07_215433](https://github.com/user-attachments/assets/7e5ffb2b-8fe9-41f1-a3be-0de541047dbb)
![Eko_2024 08 07_214435](https://github.com/user-attachments/assets/ac1e8b6d-0546-4854-820a-752bdc1168e8)

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
