### ISSUE TITLE
WM 9-2 all participants disconnect after defeating Tatzlwurm & Yali

### ISSUE THREAD

**Issue by The-Misneach** [EdenServer/community#5937]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Ver:  30181205_0
link to wiki article for this mission: https://classicffxi.fandom.com/wiki/Moon_Reading

The issue is with the BCNM in Full moon Fountain "Moon Reading"

You can: Select the BCNM, buff, fight the first wave of enemies (4 Cardians), a cutscene occurs, after the cutscene, Tatzlwurm & Yali are in the arena to fight. Both times I ran this encounter we defeated Tatzlwurm, then Yali. After defefating Yali, all players are disconnected. (R0). 

After recovering from the disconnect, characters can be logged back in, still in the BCNM, the enemies still appear to have been defeated. 

There is nothing to kill, nothing to click on. There is no way I've been able to find to kick off the cut scene to end the mission. 

If you go back to the entrance, and click on the entrance, you have the option to run away, or stay. 

The first time this happened, I clicked run away, and checked to see if the mission progressed anyway, it did not. 

To be specific: from the wiki
"After the fight return to [Heavens Tower](https://classicffxi.fandom.com/wiki/Heavens_Tower) and examine the Vestal Chambers twice to get two cutscenes and complete the mission and Windurst storyline."
I returned to heaven's tower, examined the Vestal Chambers repeatedly, and nothing happened. 

[WM9-2 Moon Reading Screenshots.docx](https://github.com/user-attachments/files/16554055/WM9-2.Moon.Reading.Screenshots.docx)

**Comment by 59blargedy** [comment]
resolved by another dev in October 9, 2024 update.
