### ISSUE TITLE
Dread Spikes issues with some dynamis mobs

### ISSUE THREAD

**Issue by Snugglepunk** [EdenServer/community#5939]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
 ver 30181205_0

Unsure if this effects all dynamis zones as I've only played DRK in Beaucedine recently.  
First noticed this issue after the July 5 Update.

Dread spikes seems to only function on the Orc mob family and does 0 damage to all statues and all other mobs/NMs.

Orchish Family
![image](https://github.com/user-attachments/assets/12481880-5b08-4093-a65c-68c5330564f0)
![image](https://github.com/user-attachments/assets/7ba56df6-8a09-4c81-ae3e-09e6b6a7164a)
![image](https://github.com/user-attachments/assets/76f50fd6-a937-4687-a513-25fffa006fc1)

Yags/Qudavs/Goblin family
![image](https://github.com/user-attachments/assets/c28d7eaf-29de-4acd-b991-5d5c102d6cf1)
![image](https://github.com/user-attachments/assets/bdebe4a3-6a8b-4b5c-8533-1f71c7047621)
![image](https://github.com/user-attachments/assets/1d323ecb-ff2e-4dd1-bf25-6d89416e44a8)
![image](https://github.com/user-attachments/assets/d320f343-6544-4fb1-8a55-4c0293f1d424)
![image](https://github.com/user-attachments/assets/19c556a1-0442-442d-ac7b-f308d3ba9b04)
![image](https://github.com/user-attachments/assets/82b8868a-cdb0-4c1d-96a6-56a1a16c3553)
![image](https://github.com/user-attachments/assets/80a868fb-3cac-449a-a05b-a1a0496d8611)
![image](https://github.com/user-attachments/assets/7fcdca04-da25-4f81-a3cc-549dfe1c4e7f)
![image](https://github.com/user-attachments/assets/afc7fc15-99d7-445e-86ac-4884458c0bdd)
![image](https://github.com/user-attachments/assets/6dda9414-f879-454b-b2ea-93df91ff45cc)
![image](https://github.com/user-attachments/assets/6c73cae6-7857-441d-9887-0f7654ba6781)

**Comment by Slamm21** [comment]
Came DRK to bastok last night
Dread spikes worked on some of the mobs, but not others so it's not just glacier. Unsure if this is dynamis specific or is a problem outside of dynamis too.

**Comment by 59blargedy** [comment]
Resolved in December 14, 2024 update
