### ISSUE TITLE
game crashes- uninstalls

### ISSUE THREAD

**Issue by saphironazure** [EdenServer/community#594]
basically, the game crashed, and the ashita icon ceased to function. I had to reinstall the entire game, and once I begin it, it let's me get to the character selection screen, then crashes when i try to connect to the server.

**Comment by Zalnoch** [comment]
Resolved, McAfee antivirus was getting a false positive for a trojan "Ashita.exe" and was moving the executable to quarantine. Switched off auto scan, issue was resolved.
