### ISSUE TITLE
Wrong RSE Dropped in Shakrami Maze as Hume M

### ISSUE THREAD

**Issue by Satcom-5** [EdenServer/community#5942]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

August 10th 2024
Client version 30181205_0
My race: Hume M

During Hume M RSE week I went to Shakrami Maze Clicked the ??? to spawn the Aroma Crawler,
Kill the monster got Olibanum Sachet (E) (1/5)

![RSE](https://github.com/user-attachments/assets/368c9ede-0b8d-4c96-8dce-74ea61c04994)
![RSE2](https://github.com/user-attachments/assets/231f765e-ffbe-415c-a4ba-8ffcbf503d34)
![RSE3](https://github.com/user-attachments/assets/a27a00c8-5053-47d1-b690-3f7069d094ef)

**Comment by KnowOne134** [comment]
resolved 10/8/2024 up update

**Comment by Pingletown** [comment]
![Image](https://github.com/user-attachments/assets/e6fd3cd0-a8b9-443c-bd12-146b7ca28ace)

Still active bug. Popped as Taru Female in correct week.

not sure if relevent, but zone crashed 5 mins before popping.
