### ISSUE TITLE
Multiple Ring doesn't give any HP bonus

### ISSUE THREAD

**Issue by Mirridelle** [EdenServer/community#5944]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

[Multiple Ring](https://ffxiclopedia.fandom.com/wiki/Multiple_Ring?oldid=583236) is suppose to give +50 HP and +20 MP when level is a multiple of 10, including level capped areas. When equipping Multiple Ring inside Promyvion, I noticed that I do get the +20 MP but not the +50 HP. 
Shown below are before and after equipping Multiple Ring. My max HP remains at 338, but my MP does go up from 453 to 473.
I do have HP and MP merits, if that matters.

![Erutanda_2024 08 15_231716](https://github.com/user-attachments/assets/642e9b0f-7f1f-49d2-8a74-75cfe2b90485)
![Erutanda_2024 08 15_231722](https://github.com/user-attachments/assets/9400519e-1784-4e95-a144-819ce37e6a6a)

Version 30181205_0

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
