### ISSUE TITLE
Bubbly Bernie's ??? is missing

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#5946]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

30181205_0

I stood around behind the lighthouse for 10 minutes looking for it. I was trying to show a new player how to pop him, but the ??? is missing! There is no one else in the zone but a THF camping Leaping Lizzy.

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
