### ISSUE TITLE
Lamia 13 - BST pets get Charmed when the BST gets Charmed.

### ISSUE THREAD

**Issue by nickycupcakes** [EdenServer/community#5950]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Steps to reproduce:
1)  Enter Lamia 13 Assault with at least one BST and a Dispel capable job
2)  Call pet during Lamia 13 Assault - Dispel all 3 of Lamia's pets and put BST pet on Lamia
3)  Have nearby teammate pull hate and draw Lamia toward you (pet should follow)
4)  Lamia uses Belly Dance and Charms BST + BST pets

(I am reasonably sure this is the series that leads to this case)

During Lamia 13 Assault, I had a Belly Dance performed on a nearby teammate while I had my pets out.  The pets were Charmed by Lamia 13, though I'm fairly sure they should have despawned.  When I became uncharmed, the pets remained Charmed by Lamia 13 and proceeded to attack me, I was able to target and hit them as well.  

It's happened more than once, so I'm putting in 2 different screenshots.

Thanks for all you do for Eden!

![Kittyexpress_2024 08 23_141809](https://github.com/user-attachments/assets/f1ee3979-a413-4178-9792-da01cffd20df)
![Kittyexpress_2024 08 02_212659](https://github.com/user-attachments/assets/4756c246-179e-4031-bd03-df28a28f8131)

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
