### ISSUE TITLE
BCNM50 Loot table potentially incorrect. 

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#5954]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

According to the classic wiki, astral ring is not a part of the treasures and tribulations loot table. 

It is showing as a possible drop from the BCNM as early as 2005 all the way up to current day with a rather common drop rate. 

![image](https://github.com/user-attachments/assets/eb8c35b6-9818-4092-98fd-646d915e1ed5)
![image](https://github.com/user-attachments/assets/f9c3be81-9658-4543-9238-0082e0763204)
![image](https://github.com/user-attachments/assets/bd11573e-ab08-420e-9721-9a7af4a37e99)

**Comment by Midgard-was-taken** [comment]
I have gotten one Astral Ring from this BCNM on Eden.

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
