### ISSUE TITLE
Weapon Bash + Blade Bash Animations swapped.

### ISSUE THREAD

**Issue by statuseffect** [EdenServer/community#5955]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Blade Bash should use the Greatsword bash/swing animation, as im pretty sure on Eden it uses the scythe swing version.
https://www.youtube.com/watch?v=SM19i4KTEuw - Blade bash

Scythe weapon bash is currently using the Greatsword bash.

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
