### ISSUE TITLE
Advanced synthesis support deducting incorrect amount of gil

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5959]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

On my 92 Veteran Clothcrafter, I talked to Terude-Harude in the Windurst Woods Clothcrafting guild to get advanced synthesis image support.

He tells me it will cost 300 gil.  Accept charges, receive advanced support, check gil and notice he only deducted 30 gil, not 300.

As far as I know, it is supposed to be 30 gil for each rank you are, up to 300 at Veteran rank.

Unknown if this affects other ranks or other guilds in general.

Screenshots:
![Tawni_2024 08 30_185956](https://github.com/user-attachments/assets/a3a457ba-a1c1-44d4-9f72-31dd7ecd68bf)
![Tawni_2024 08 30_190003](https://github.com/user-attachments/assets/545b1e1b-def1-47ce-b135-502eeb1d7cd3)
![Tawni_2024 08 30_190011](https://github.com/user-attachments/assets/a17b2ef0-e711-4113-b53b-f378a6e78bae)

**Comment by statuseffect** [comment]
wonder if its just the CC guild or translating across all guilds.

**Comment by statuseffect** [comment]
Takes the full 300 from smithing guild.

Does not take the full 300 from bonecraft guild.

**Comment by 59blargedy** [comment]
thanks guys, we'll just check all of them so you don't have to check others.

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
