### ISSUE TITLE
Eldieme Necropolis Escape point is incorrect

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5960]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Casting Escape in The Eldieme Necropolis currently brings you to the Goblin Camp outside the Upper Jeuno zoneline at K-8, the same spot the free warp taru brings you to:
![Eko_2024 08 30_205523](https://github.com/user-attachments/assets/08b63804-8b6c-4720-863e-84e823a2ec8d)

According to Wikis, it should bring you to G-8, 4 squares West (exact spot unknown):
https://www.bg-wiki.com/index.php?title=The_Eldieme_Necropolis&oldid=118304
https://ffxiclopedia.fandom.com/wiki/The_Eldieme_Necropolis?oldid=755008
https://ffxiclopedia.fandom.com/wiki/Escape:_Guide_to_Positions_and_Shortcuts?oldid=736726

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
