### ISSUE TITLE
Sandy 9-2 R0 @ end of fight

### ISSUE THREAD

**Issue by Oir11** [EdenServer/community#5964]
Sandy 9-2 Mission will work up until you complete the BCNM. Once you have finished both P1 and P2 instead of getting the completion Cutscene it makes you R0 and when you return you are in the BCNM but have not completed the fight. The R0 occurred with everyone that went, Sadly I did not get a SS, If its needed I can try to get people to go, but it has happened for multiple people via the shouts.

I have reviewed the current tickets and did not find anything (If I missed one i'm sorry) 

Version: 30181205_0

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
resolved by another dev in October 9, 2024 update.
