### ISSUE TITLE
Getting incorrect messages for actions from NPCs.

### ISSUE THREAD

**Issue by jaheny13** [EdenServer/community#597]
I've been seeing an issue from random NPCs and other things (like telepoint crystals) where I am getting an entirely different and wrong message. For example:

I just got my Chocobo license and instead of it saying that I've gotten the key item Chocobo License. It says that I have gotten 138 gil. My gil doesn't change and I do get the Chocobo license.

I've gotten this issue at Telepoints where it says I get gil instead of the telepoint (the Telepoint is in my permanent key items and gil does not change).

While fishing, it immediately says my rod breaks. Then seconds later, says that they don't know how long I can hold on. And when I catch something, it doesn't say anything and I do not have a fish in my inventory (this might be separate? But seems related since they are wrong messages).

When getting Outposts, it says that my supplies are old and that they will discard them. But I do get the OP. 

Just a bunch of weird messages all around with a little bit of everything. I've had other weird ones, but these are the ones I remember off the top of my head.

**Comment by gweivyth** [comment]
This isn't a bug, you are version mismatched.  If you're using your Nasomi (or other non-version matched) install that will happen.

**Comment by godmode** [comment]
@gweivyth is correct. You need to use Eden's installer. We will be updating to a newer client version though shortly. So if you are coming here from retail you will be fine in a week or two.
