### ISSUE TITLE
Fenrir uses 2hr instantly in his bcnm

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5972]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Helped with a Fenrir fight today. Fenrir used Howling Moon with zero windup, twice (Once at 50% and again at around 30)

Skip to 3:00 and watch muted: https://www.youtube.com/watch?v=5ejMEbS-73Y&t=119s

Fenrir's 2hr, Howling Moon, has about a 3 sec windup in the video. And he only uses it once around 50%

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
