### ISSUE TITLE
Quest "Making Headlines" Bugged (Port Windurst Scoop - Yujuju)

### ISSUE THREAD

**Issue by InoSiX** [EdenServer/community#5973]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
![Screenshot 2024-09-18 123346](https://github.com/user-attachments/assets/26917f0e-610f-45ad-a618-9da379f8d009)

Version: 30181205_0

I am currently unable to finish both "Making Headlines" and "Lure of the Wildcat (Windurst)" as a result of of what appears to be a bug. I have obtained 3 of the 4 scoops needed for "Making Headlines" and am missing the key item "Port Windurst Scoop". When talking to the NPC involved (Yujuju, nearby the airship in Port Windurst) she mentions content that reference the mission starter NPC (Naiko-Paneiko) and mentions "Anyway, here... Take it, you scoundrel." suggesting she is about to give me something but never does. I have zoned many times, waited for conquest tally. She doesn't provide the key item "Port Windurst Scoop".

To be sure, I visited the next part of the mission by going to the door in the Inner Horutoto Ruins without success. I am confident I am at the right door because I recently did finish the quest at my alt.

I suspect the issue involves the interaction between "Making Headlines" and "Lure of the Wildcat (Windurst)" as this NPC is involved with both quests. Alternatively, it could be related to Windurst Mission 2-1 "Lost for Words" as I may have obtained the "You confirmed the Windurst Woods Scoop" message while completing that Mission (same door is involved with both) but before talking to Yujuju to get the "Port Windurst Scoop" key item. This is a theory.

https://classicffxi.fandom.com/wiki/Making_Headlines

**Comment by KnowOne134** [comment]
hmm, tested on my local test server and got same cs but anded with getting the Keyitem. Then i checked your char for having the keyitem also and you dont...
I will have to make an order for a GM to adjust your char in the time being.
![image](https://github.com/user-attachments/assets/41ce36a5-2dcc-4231-b739-a7236c56bc8e)

**Comment by KnowOne134** [comment]
can you make a gm ticket please, i have instructions left with how to fix your situation. !menu for instructions on how to do a gm ticket

**Comment by InoSiX** [comment]
Thanks for your responses. I have submitted a ticket with reference to this GitHub thread. Does it require me to be logged in?

**Comment by KnowOne134** [comment]
Sadly yes. When a gm comes on they will search to close

**Comment by InoSiX** [comment]
Ok. Well I'll try to remain logged in.

**Comment by KnowOne134** [comment]
issue is resolved

**Comment by InoSiX** [comment]
Thank you for the assist. I was able to complete the quest. I may need to open a new issue regarding "Lure of the Wildcats (Windurst)" as the Yujuju is not prompting the dialog "badge shines brightly" to complete the questline, but I'll double check that I have talked to all others again before attempting to finish another time. Hopefully it's as simple as I missed a NPC. Thanks again!

**Comment by KnowOne134** [comment]
Np. I haven't got to re writing the windusrt quest lines yet. As it's last of the nation's in numerical order
