### ISSUE TITLE
Assault zone crash - All affected chars unable to login / stuck Downloading Data

### ISSUE THREAD

**Issue by Avarghaladion** [EdenServer/community#5975]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

About 30min ago, Ilrusi Atoll assault Demolition Duty crashed. All affected characters have been unable to log back in since then, getting stuck on the black Downloading Data screen. Issue persists after leaving zone empty without any relog attempts for 5-10min.

**Comment by Mozzy4Ever** [comment]
Cluster has been restarted and is back online.
