### ISSUE TITLE
Charybdis shouldn't guard or counter

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5977]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

This video is slightly ooe but demonstrates that Chary shouldn't guard or counter.

https://www.youtube.com/watch?v=2T8o216Pjn8

Link to a previous report:
https://github.com/EdenServer/community/issues/5174

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
