### ISSUE TITLE
Orc TP move Arm Block seems to be broken

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5978]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Temenos 3rd floor PLD boss seems to be doing armblock and it goes 0 damage to him and doesnt give defence bonus.

![image](https://github.com/user-attachments/assets/170fbdee-5712-481d-a76d-5c8e9962be37)

![image](https://github.com/user-attachments/assets/6f275228-67ab-4f7c-b67e-8dc9c6f9374c)

![image](https://github.com/user-attachments/assets/9790a3ac-4fe7-4871-8e17-ebda10d4000b)

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
