### ISSUE TITLE
Can't Purchase Fisherman's Signboard, and Angler's Almanac 

### ISSUE THREAD

**Issue by Gambiol** [EdenServer/community#5979]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Ver 30181205_0

Got enough gild points for both items but unable to purchase them.
Items are Fisherman's Signboard, and Angler's Almanac 
Character name Gambino.

Thanks

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update, almanac ooe so not resolved
