### ISSUE TITLE
Incorrect Level Up Animation

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#5980]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

After dying and leveling down as a result, being raised afterward and regaining the lost level shouldn't play the level up animation.

Die and level down.
Accept Raise or Reraise.
Level up animation will not play.

Please provide any feedback or proof that the alternative is correct. It's a cool looking gimmick but it's not accurate.

**Comment by dowzer** [comment]
My apologies for confirming that the level up animation shouldn't play after deleveling and raising.

https://www.youtube.com/watch?v=1ZE8Dm6hBiQ

RIP 22.gif

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
