### ISSUE TITLE
Unable to complete the quest "Smoke on the Mountain"

### ISSUE THREAD

**Issue by Rhomagus** [EdenServer/community#5983]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
The campfire in South Gustaberg at the goblin camp doesn't have a ??? targeting point. Due to this, a character is unable to receive a Galkan sausage from the fire in order to complete the quest.

1.) Talk to Hungry Wolf in the Metalworks to flag the quest
2.) (Optional) Talk to Offa in Bastok Markets, he tells you how to make a Galkan Sausage
3.) Travel to the Goblin campfire located around (K-9)
4.) Observe there is no ??? that can be targeted

Ver. 30181205_0

https://classicffxi.fandom.com/wiki/Smoke_on_the_Mountain

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
