### ISSUE TITLE
Yowie spawn behaviour seems to be incorrect

### ISSUE THREAD

**Issue by Avarghaladion** [EdenServer/community#5984]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
30181205_0

Below image provided by Dowzer and corroborated by Falaras shows observed Yowie spawn locations in Eden (red) vs era retail (green):
![yowiekuftal](https://github.com/user-attachments/assets/464a8083-9290-40d0-a6fa-93e1f5e44708)

Era retail spawn location is corroborated by FFXIDB:
![image](https://github.com/user-attachments/assets/404c3f97-152e-44bc-8cf6-f4a81ee17fa7)

Retail wiki indicates it ought to be a lottery spawn of the raptors "around H-8" and that "placeholder ID is 119 and 11B (shared spawn)," indicating a single and alternating PH mob. 

Spawn rate may need to be assessed if PHs are reduced from every raptor to a singular PH, as spawn rate currently seems low relative to what appears to be the number of Eden PHs in the area.

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
