### ISSUE TITLE
final sting is too strong

### ISSUE THREAD

**Issue by mattadjohnson** [EdenServer/community#599]
Just got hit for 501 by a final sting by Stinging Sophie NM in North Gustaberg, according to wiki final sting should hit for the bee's remaining HP (it seemed to do it's full HP). https://ffxiclopedia.fandom.com/wiki/Category:Bees

Sophie was at 15%~ HP when using it and according to wiki she should have ~545HP https://ffxiclopedia.fandom.com/wiki/Stinging_Sophie

This could just be a bug or maybe working as intended for Final Sting itself across all bees, but I got one shot by this one so figured I'd throw in a bug report.

Also, it didn't drop anything or reward experience for the remaining party members after it killed me and itself. When other normal bees in this area final sting they still give exp and items.

[
![finalsting](https://user-images.githubusercontent.com/4438672/50485727-77396180-09c4-11e9-8dd4-34f410006197.PNG)
](url)

**Comment by beauxq** [comment]
Yeah, this is not a Stinging Sophie bug. It's a final sting bug.
It's too strong on all bees.
