### ISSUE TITLE
Chakra showing max HP healed in log even if you are full HP/heal for less

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#5991]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Posting for easier tracking, from Is it a bug-thread

![image](https://github.com/user-attachments/assets/f4eb9545-44b8-4ab0-be57-cd639c863d77)

**Comment by 59blargedy** [comment]
resolved in October 9, 2024 update.
