### ISSUE TITLE
CoP 5-3 Ulmia CS player in water

### ISSUE THREAD

**Issue by bahamut44** [EdenServer/community#5994]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

My static is doing the Ulmia path of CoP Mission 5-3. When following the wiki, "5-3U1: Entanglement -> Zone into [Port San d'Oria] for a cutscene." Three of us have been placed in/under the water off the port where the airship lands after the CS ends. We were all able to warp or !unstuck out, but since this happened exactly the same way to 3 of us I thought I'd report it as a bug. See pictures attached. Kelson's version is 30181205_0

![Kelson-Psandy](https://github.com/user-attachments/assets/db34d9ad-e860-4136-bfe2-5a8295ea917d)
![Gnomie-Psandy](https://github.com/user-attachments/assets/4da81d22-3840-46d5-8098-d5d2c1747cc1)
![Ardok-Psandy](https://github.com/user-attachments/assets/abddc637-0ae9-4d6e-bbfd-55469b5cbbca)

**Comment by KnowOne134** [comment]
how did you get to port sandy? and did you take an airship to that zone prior?

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
