### ISSUE TITLE
Adding/removing merits not giving chat log message

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5995]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Recently, I was removing parry skill merits (don't ask) and putting merits into marksmanship and noticed that I was not getting messages in my chat log for either of these actions.

Removing a merit should give a red line of text that says:
Your X modification has dropped to level Y.

Adding a merit should give a yellow line of text that says:
Your X modification has risen to level Y.

I have this prime, vintage screenshot from June 30th, 2009:
![ffxi_2009 06 30_04 09 17](https://github.com/user-attachments/assets/b83f66e3-66d1-4af6-98cf-fdbd4b21f603)

While I understand that this screenshot is past our cutoff by 9 months or so, I have to imagine it was still a thing during our era.  I just don't know where to look for something this small.

**Comment by WinterSolstice8** [comment]
I had implemented this on LSB (feel free to take)
https://github.com/LandSandBoat/server/pull/3706

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
