### ISSUE TITLE
Mother Globe not spawning Slave Globes

### ISSUE THREAD

**Issue by tuckermand** [EdenServer/community#5997]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
30181205_0. 
As title says, MG not spawning slaves(both when idle and during combat). Behavior otherwise normal.
https://classicffxi.fandom.com/wiki/Mother_Globe

**Comment by 59blargedy** [comment]
resolved by another dev in October 24, 2024 update
