### ISSUE TITLE
Detectors not spawning dolls, nor Steam Cleaner

### ISSUE THREAD

**Issue by balvont** [EdenServer/community#5999]
Tried popping Steam Cleaner, Detector did not summon a doll or SC.
![image](https://github.com/user-attachments/assets/bde73f38-2a1c-48fa-9d8e-2907f5e235bc)
![image](https://github.com/user-attachments/assets/83567bb4-94bf-43a4-ac55-0c5425db5b3e)
![image](https://github.com/user-attachments/assets/9b379083-eba9-4072-94f2-cec58e918463)

### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
resolved by another dev in October 24, 2024 update
