### ISSUE TITLE
Xolotl

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#6]
1. I was able to sleep him with dark based sleep but he should be immune. (I believe all corse type mobs should be)
2. Xolotl's hound warrior and Xolotl's sacrifice weren't being summoned. 
3. Xolotl, Xolotl's hound warrior, and Xolotl's sacrifice were all linking with the surrounding antlions but they shouldn't. 
4. Xolotl was repopping the night after death, but he should be a 21-24 hour repop. 

http://ffxiclopedia.wikia.com/wiki/Xolotl
https://www.youtube.com/watch?v=O9gFQ4C_4Cw

**Comment by godmode** [comment]
All is fixed except for the linking problem. That will be fixed in the future. Feel free to remind us if it's done done in a timely manner.
