### ISSUE TITLE
Respwwn timers for Jellies and Lesser Gaylas.

### ISSUE THREAD

**Issue by Wolforrd** [EdenServer/community#600]
I noticed last night lesser gaylas in Zi Tah spawn at 18:00 and despawn at 4:00. I believe there suppose to be spawning at 16:00 . Atleast from wiki information. Jellies in Korlokka Tunnel are also spawning 13-15 minutes after death and should be 8 min. Unless there was an update on retail i dont remember.

**Comment by Shoruto** [comment]
Proper time for Lesser Gaylas should be 16:00-6:00
https://ffxiclopedia.fandom.com/wiki/Lesser_Gaylas?oldid=373448

Respawn time for Jellies should be 10 minutes
https://ffxiclopedia.fandom.com/wiki/Jelly?oldid=363608

**Comment by MGramolini** [comment]
From my experience on Eden, they are spawning at 18:00 and despawning at 6:00.  That is a 12 hour window.  I believe the most accurate description to be in the latest update of the page.

Spawn starting at 16:00 and despawn at 8:00. Some of the Lesser Gaylas can despawn as early as 6:00. Some also don't start spawning until 18:00.

If there are 2 different "groups" of lesser gaylas, then maybe someone should check retail for the behavior, or we just compromise based on DSPs current ability and pop them all 17:00-7:00.

**Comment by Far-The-Killer** [comment]
The wiki is right on spawn times for the Gaylas (we did some retail checking), but this is not an easy fix because of how dsp handles mobs that have certain spawn times.

**Comment by KnowOne134** [comment]
Corrected 11/2
