### ISSUE TITLE
Bostaunieux Oubliette Cell Door opens on the wrong axis (video)

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#6002]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

ver 30181205_0

Reproducible steps:
Go to Bostaunieux Oubliette entrance floor at H-8
Click to open the 2nd 'Cell Door' on the right

Video: https://youtu.be/_0u_21c1j58

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
