### ISSUE TITLE
Lamia No. 13 Charmed Fenrir and made him a bad doggo

### ISSUE THREAD

**Issue by Avarghaladion** [EdenServer/community#6004]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
30181205_0

During Lamia No. 13 assault, she was able to charm Fenrir and convert him into a permanently aggressive mob that persisted when the SMN summoned other avatars. After this happened, the Lunar Roar from subsequently summoned Fenrirs was no longer effective against the Imperial NPCs. Similarly, the traitor Fenrir could not be dispelled ("no effect"). It also could not be claimed and its name renamed yellow regardless of any direct action taken on it.

![Sigua_2024 10 15_234906](https://github.com/user-attachments/assets/b7c21ad3-2d0f-40bb-8c84-459817b78339)

The traitor Fenrir did not appear on Wide Scan.

![Sigua_2024 10 15_235733](https://github.com/user-attachments/assets/bd51804b-8f80-4da5-b9d6-611abcd17b44)

Once Lamia No. 13 was defeated, the traitor Fenrir stopped being aggressive and was not pullable but would fight back if attacked.

![Sigua_2024 10 16_000208](https://github.com/user-attachments/assets/d606b24a-8b1a-48a3-9541-00739e91d541)

I suspect this was caused by her doing a Belly Dance at the exact moment during unsummon that the pre-traitor Fenrir's name went from white to grey. Anecdotally, that phase of unsummon also breaks /ignorepet in that players can target grey-named avatars during unsummon despite having /ignorepet on.

I suspect this could be reproduced vs any mob with charm.

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
