### ISSUE TITLE
Ix'DRG not spawning his Wynav buddies

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#6006]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

Ix'DRG is currently not spawning its Wynav adds.  Probably related to the open MG and Detector/SC bug reports but wanted to report just in case.

**Comment by 59blargedy** [comment]
resolved by another dev in October 24, 2024 update
