### ISSUE TITLE
Shady Business (Port Bastok Quest) giving BOTH Bastok & Tenshodo fame

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#6012]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

30181205_0

After completing 'Beauty and the Galka', the following repeatable quest 'Shady Business' should only be giving fame for the Tenshodo, but it's giving fame in Bastok as well. See screenshot for proof. The FFXI wiki clearly states (even going back to 2008) that it should only be raising Tenshodo reputation. 

![image](https://github.com/user-attachments/assets/1f379376-8e90-477b-9e33-0cb83dabd9fa)
![image](https://github.com/user-attachments/assets/5dbfe317-af65-406c-878e-ffc4c8bb3da1)

**Comment by KnowOne134** [comment]
resolved in last update
