### ISSUE TITLE
Repeatable Mission "Fetichism" does not grant Rank Points

### ISSUE THREAD

**Issue by Rhomagus** [EdenServer/community#6015]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Upon achieving Rank 2 in Bastok the gate guard mentions two ways in order to receive further missions. One is to repeat earlier missions and the other is to donate crystals to a gate guard. Donating crystals does indeed result in gaining Rank points and is correctly displayed on the Rank Bar under the Profile Menu option. Unfortunately, repeating the quest Fetichism only nets a 1000 gil reward and does not increase the Rank Bar. I have repeated this quest multiple times as I would rather use my crystals for crafting but I have not been offered to do any other Rank 2 missions such as "The Crystal Line" or "Wading Beasts". I had thought that maybe it was being recorded in the background and just not displaying on the Rank Bar but after doing the mission over seven times and not being offered a new mission I tried trading a singular Water Crystal to see if the Rank Bar display was accurate and when I traded a Water Crystal the Rank Bar correctly displays an increase in Rank points. 

The Wiki also confirms that repeating quests will result in an increase in rank points as seen on the following page:

https://classicffxi.fandom.com/wiki/Rank

"Rank Points can be acquired by either completing missions, or by turning Crystals into your home nation's or Jeuno's Conquest Overseers."

This was my preferred method of gaining rank points back during era until I was able to unlock the repeatable Mission: Wading Beasts, to which I would then switch to trading Lizard Eggs instead of Quadav Fetich Pieces. The quest should reward both gil and Rank Points. 

Reproducible Steps:

1.) Achieve at least Rank 2 for Bastok by completing the Nation Mission "Fetichism" one time. 
1a.) Upon completing said Mission you'll the gate guard will explain that you can either repeat missions or trade crystals in order to be entrusted with further missions.
2.) As at least Rank 2 for Bastok, undertake the "Fetichism" Mission again by talking to a gate guard. 
3.) Obtain and trade the four Quadav Fetich Pieces to a gate guard
4.) The chat log will confirm that you were awarded 1000gil, but will not make any mention of Rank points. 
5.) Check under the Profile tab in the Menu to confirm that your Rank Points bar has not increased. 

(Optional)
1.) Trade a Crystal to the appropriate Gate Guard. 
2.) The Gate Guard will return a line of dialogue that confirms you have been rewarded Rank Points
3.) Confirm you have received Rank Points by checking under the Profile tab in the Menu and observe that the Rank Bar displays an increase in Rank Points.

This is all on version 30181205_0

**Comment by 59blargedy** [comment]
Resolved in December 14, 2024 update
