### ISSUE TITLE
Diatryma Giant Bird Feather Drop Rate too high

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#6016]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_5

Reproducible steps:
Kill Diatryma in Misareaux Coast
Observe Drop Rates

![image](https://github.com/user-attachments/assets/8764e21a-e3a0-4db2-8a65-eee7ca54f681)

I'm pretty sure Giant Bird Feather as a drop from Diatryma, and perhaps the entire Roc family outside of NMs, might be too high. It appears to be in the 'Common' column, when I feel it should be in the 'Uncommon' one in the chart above. This parse from Eden using TH4 shows it at around 45% with TH4 over 100 kills:

![image](https://github.com/user-attachments/assets/f7f8f416-a1c8-43a3-8100-434a548bacf5)

Era drop rate evidence of it probably being 18% with TH4:

![image](https://github.com/user-attachments/assets/946f779b-c38c-4f90-a87c-083bf5a8c138)
![image](https://github.com/user-attachments/assets/3ca91d7a-43cc-493e-a734-3d5bf80d26a7)

My parse leans to 'Giant Bird Plume' being between the 2.5% and 8% columns with TH4, so I would appreciate an audit of that as well. I suspect it should be 8% given the above era information.

Thanks.

**Comment by 59blargedy** [comment]
Resolved in December 14, 2024 update
