### ISSUE TITLE
Resetting ZR F4 Seals Gilded Doors

### ISSUE THREAD

**Issue by Avarghaladion** [EdenServer/community#6019]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

30181205_0

Resetting ZR F4N is causing the Gilded Doors to the portal room to become sealed and nothing will unseal them. This has started occurring for us on ZR 4N+5+6+boss runs where it's necessary to kill the "wrong" rampart to reset the floor to finish unlocking cells to still do F5+F6 frogs after reaching F4 in <30min. 

Killing the wrong rampart should allow you to port back to the same floor with mobs reset and let you farm/guess again on repeat. This was working previously, not sure when it changed.

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
