### ISSUE TITLE
Harajnite Shell Drop Rate

### ISSUE THREAD

**Issue by tieig** [EdenServer/community#6021]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
 ver 30181205_0

I believe Harajnite Shell drop rate is broken. Between Hat and Tieig we are an estimated 0/100+ kills

**Comment by 59blargedy** [comment]
the drop looks ok, so your luck appears to just be really unfortunate. it is set at rarity 3, without much data to go on that is as good a guess as any for the rate.
