### ISSUE TITLE
NPC Brugaire bugs final cutscene in Souls in Shadow

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#6022]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
client version 30181205_0

The final cutscene for Souls in Shadow can't finish because the model for NPC Brugaire who walks in doesn't show up. I'm assuming the cutscene is hanging waiting for him to finish some animation so it can advance dialog. Specifically the line "As long as I get my money I don't much care, but what the hell are you doing with this thing? I've never seen anyone blunt a blade so quickly."

**Comment by randomslumber** [comment]
Forgot to mention my second attempt I did /fps 2 but 30 cap fps didn't make him appear either

**Comment by randomslumber** [comment]
Tried without xipivot loaded but that just caused the client to crash at the same spot. The NPC still didn't appear in the cutscene

**Comment by KnowOne134** [comment]
Resolved in 12/14/2024 update
