### ISSUE TITLE
PUP Drum Magazine effect undertuned with only one maneuver active

### ISSUE THREAD

**Issue by AshleyAwakens** [EdenServer/community#6024]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
The current Drum Magazine when using only one Wind Maneuver does not lower the ranged attack recast as much as it should. The expected behavior based on the [retail wiki](https://ffxiclopedia.fandom.com/wiki/Drum_Magazine?oldid=688561) is that 1x Wind Maneuver should reduce the RA delay by 3 seconds from 20 to 17s. From my testing, it currently only reduces RA delay by ~1 second as shown below, with one Wind Maneuver kept up the entire time:
First RA at 21:19:47
![image](https://github.com/user-attachments/assets/38c3ff08-a7f3-493f-913c-3589d927aa00)
Second RA at 21:20:06
![image](https://github.com/user-attachments/assets/fcc6cc8e-913b-4bc4-9701-16ab6be05292)
Third RA at 21:20:25
![image](https://github.com/user-attachments/assets/63fd5061-fc73-44eb-976c-0dd0eddb5501)

As a control I also did testing with zero Wind Maneuvers to verify non-altered RA delay:
First RA at 21:37:27
![image](https://github.com/user-attachments/assets/0acf3cdd-416a-43bc-82ed-43b93cc6c733)
Second RA at 21:37:46
![image](https://github.com/user-attachments/assets/74ecffd6-8275-4568-ac50-b19dbbe57623)
Third RA at 21:38:06
![image](https://github.com/user-attachments/assets/e08b96ae-23a6-47d2-9218-bd129502a7a4)

From previous experiences skilling up Ranged skill, the attachment functions properly at 2x Wind Maneuvers, reducing RA delay by 6 seconds as intended. I have not done any testing to verify 3x Wind Maneuver's effect.

/ver 30181205_0

**Comment by 59blargedy** [comment]
Resolved in December 14, 2024 update
