### ISSUE TITLE
Pulling the strings SMN not using avatars

### ISSUE THREAD

**Issue by LaurelEden** [EdenServer/community#6026]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Fantoccini just attempts to use blood pacts without summoning a pet
![Laurel_2024 12 01_160030](https://github.com/user-attachments/assets/42d93e93-92bb-475b-ac73-872f7c53351d)

era video: https://www.youtube.com/watch?v=FOuYDA6vWgU

**Comment by 59blargedy** [comment]
Resolved in December 14, 2024 update
