### ISSUE TITLE
Some Fossorial Fleas drop dead around 40-50% and give no XP

### ISSUE THREAD

**Issue by Crissski** [EdenServer/community#6027]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

This was a previous bug that still is problematic.
Some fleas get a critical hit of 0 then fall to the ground and give 0 XP.

**Comment by Crissski** [comment]
Mobs are not dirty (killed multiple rounds after respawning).
Usually has a significant amount of HP 35-55%.
Falls to ground and no XP given. Mobs are IT.

**Comment by Pingletown** [comment]
This is not a bug, it's how that mob type works.

**Comment by 59blargedy** [comment]
Hi @Crissski thank you for reporting but it is not actually a bug so I'll go ahead and close. Let me know if you have questions~
https://ffxiclopedia.fandom.com/wiki/Category:Chigoes
![image](https://github.com/user-attachments/assets/c776cde2-3b06-47a8-8e2e-8aa26eaf3dc0)
