### ISSUE TITLE
Full Inventory and Mannequin NPC

### ISSUE THREAD

**Issue by InoSiX** [EdenServer/community#6028]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Ver. 30181205

Uncovered a bug and am hoping to get reimbursed for the damages. Some months ago I finalized the last of my Mannequin parts to finish the Mannequin quest. Turns out Mannequins are good sources of storage at capped prices (versus something like a bookshelf which costs more on the AH and provides less storage.). After a few weeks, I went back to purchase a mannequin from the NPC for 100k. I attempted to purchase 2 (specifically the Elvaan male/female). After purchasing them, I didn't immediately return back to Sandy to set them up.

Instead, some time later, when I went to set them up, I noted I only had 1 of the 2 mannequins. At the time I didn't have much gil and I definitely was missing the gil (I had some 400k around that time so missing 100k was very noticeable). I didn't understand what happened.

Yesterday, I uncovered what almost certainly happened: **If you purchase a mannequin from the NPC with a full inventory, she will suggest the purchase was successful but will not give you anything and still take your gil. In fact, the NPC will give you the same "Obtained: xxxx" you would get if you actually successfully purchased one.**

This time around I lost 300k to this process. I did it twice before taking the screenshots attached for a third time. Once I realized what was going on I wanted to document it to get it fixed.

Please correct this by preventing people from purchasing with full inventories. Also, please please please reimburse me, at the very least, for the 300k I lost this time around. Although it would be great to get the previous 100k back also, I don't have much expectation of that at this point.

I was running to an EXP party while I gathered these pictures. At the time they were taken, I made sure my invo was 60/60. When the NPC in the picture says I obtained the mannequin, she is lying. I still have the option to purchase the mannequin.

![BEFORE](https://github.com/user-attachments/assets/c3def615-c9fd-40ad-971d-8ebb77384da5)
![AFTER](https://github.com/user-attachments/assets/9856e4ab-ece9-4235-b124-9b0aac48e757)

**Comment by 59blargedy** [comment]
listing an issue with no full inventory message is an appropriate bug report, but anything personal on this report should instead be filed as a gm ticket, as that's the team that would look at your request.

**Comment by 59blargedy** [comment]
Resolved in December 14, 2024 update
