### ISSUE TITLE
Dynamis San d'Oria Mob Claiming Issue - You cannot attack that target.

### ISSUE THREAD

**Issue by Croftings** [EdenServer/community#6034]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

We had a Bard earlier swapping parties for Ballad in our San d'Oria run, and noticed on multiple occasions the Black mages in the alliance were not able to do any actions on the mob until the bard re-joined the alliance OR died forcing the mob to go unclaimed, allowing the alliance to once again perform actions.

No screenshots sadly but the messages were as follows:-

[19:33:51] You cannot attack that target.

**Comment by 59blargedy** [comment]
resolved December 15, 2024
