### ISSUE TITLE
Storage not accessible or lost from MH2

### ISSUE THREAD

**Issue by Lonewulf724** [EdenServer/community#605]
Wanted to start gardening so I put my 2 tables and 10 pots into MH2. Naturally it allows 12 spaces of storage. I put a bunch of stuff into there, today I went to access my storage not only is everything missing, says 0/12, I cant put anything into there even if I wanted to. Im afraid to move anything from MH2 into MH1, like the previous person who posted this, for the fear I would lose the items I had in there forever...

**Comment by godmode** [comment]
Players it may be best that you don't try these steps unless you're ok with possibly losing items permanently. This note is for the dev that picks up this ticket. When I tested the item is still in the database. So when you remove your furnishings, place them into the 1st mog safe, then place them all, exit and reenter your items show up. It is easily reproducible.

1. `!additem 77` and place it in 2nd mog safe
2. place an item in the safe
3. exit your mog and reenter and the item is missing
