### ISSUE TITLE
RDM Enspells not taking weather/day into account

### ISSUE THREAD

**Issue by Altnob** [EdenServer/community#607]
Tested with 150 enhancing 

formula for <200 Enhancing

E*6/100+3 = 11.82

Day is 10%
Weather is 10%
Double weather is 25%

Testing enstone on earths day with earth weather in dunes on mob without shell and weak to light

Enstone without weather was 11AE
With weather on earth's day 11AE <- should be 14
Enthunder on stone day = 11AE <- should be 10.63 (or 10)

**Comment by godmode** [comment]
https://ffxiclopedia.fandom.com/wiki/Red_Mage:_En-Spell_Damage_Calculations

**Comment by Altnob** [comment]
That's where I got my formula. Guess I shouldve posted it.

**Comment by KnowOne134** [comment]
code is in and tested, bonus and weakness are not 100% on every hit
