### ISSUE TITLE
2-3 Mission Balgas Dais

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#610]
I ran into a problem on 2-3 mission today. The beginning CS would freeze up on me. Tried relogging, zoning, GM help and nothing. Was not able to get credit for the BCNM, and unable to enter.  Attached is the screenshot of where both of my characters freeze up. 
![strider_2018 12 28_203832](https://user-images.githubusercontent.com/46233090/50532191-e8236b00-0ae3-11e9-82a0-5fec7c98b9f4.png)

**Comment by tectal831** [comment]
Did you have fps set to 60? I think we have been able to narrow this bug down to people with fps set to 60. Please let me know if this wasnt the case

**Comment by godmode** [comment]
If this is still an issue please request a GM ticket. We are currently looking into the issue but have enabled GMs to progress you through this mission if you meet the necessary requirements.
