### ISSUE TITLE
Charging Sheep in Beadeaux drop table

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#612]
https://ffxiclopedia.fandom.com/wiki/Charging_Sheep
They are only dropping at most 1 of the items listed, wiki says they should be dropping more.

**Comment by godmode** [comment]
The drop rate was not far off but I did adjust it.

**Comment by rujind** [comment]
FYI I didn't mean the % chance, I meant that the wiki says up to 3x sheepskin can drop at once, etc and they were never dropping more than 1 at a time.

**Comment by godmode** [comment]
The possibility was there but I adjusted the rates.
