### ISSUE TITLE
Nihniknoovi Attack Rate Low

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/community#615]
Unsure if this NM behaves as intended.
From https://ffxiclopedia.fandom.com/wiki/Nihniknoovi
"Nihniknoovi has an extremely fast attack rate, not far off from Hundred Fists, and between 575 - 850 HP."
I found that Nihniknoovi's attacks seems like a normal bird rate.

**Comment by bkesecker** [comment]
Saw another post from Treble this NM is out of era.  Closing.

**Comment by jamiehavok** [comment]
https://ffxiclopedia.fandom.com/wiki/Nihniknoovi?action=history

Goes back top 2006...? Doesn't look like it's out of era

**Comment by bkesecker** [comment]
Thank you.  I thought so too.  Info on sompage differs as well.  http://ffxi.somepage.com/mobdb/3521
