### ISSUE TITLE
ZM8 Kam'lanaut Additional Effect: Kam'lanaut recovers 131062 HP (w/o actually recovering it)

### ISSUE THREAD

**Issue by Eme-FFXI** [EdenServer/community#616]
Just noticed on ZM8, that sometimes there is this weired message in the log. I could not see any actual effect from it tho.

Regards
![inkedeme_2018 12 29_195343_li](https://user-images.githubusercontent.com/44308523/50541341-f8028400-0ba3-11e9-8812-df2dd6670049.jpg)

**Comment by InoUno** [comment]
Resolved in March 15th, 2021 update.
