### ISSUE TITLE
"Out of the depths" quest chain not implemented

### ISSUE THREAD

**Issue by jamiehavok** [EdenServer/community#619]
Cool quest chain expanding on moblin lore in cop. Results in a 40 cap battlefield in "Return to the depths" (cap removed in later updates when they started removing cop caps)
Ravorara gives text saying to talk to Ayame about moblin settlement. Ayame wont give the quest. Should start at fame level 3.  
https://ffxiclopedia.fandom.com/wiki/Out_of_the_Depths

**Comment by Shoruto** [comment]
Can confirm this quest should exist during era and at Bastok rep 3.  The only issue that might have caused this is you talked to Ravorara first.  The quest requires you to talk to Ayame first then Ravorara, so maybe it glitched your character.  Did you try zoning then coming back and talking to Ayame first?

**Comment by jamiehavok** [comment]
Yeah there are a lot of quests that dont work on dark star project as no one has got around to coding them yet as they are not high priority compared to missions, end game stuff or the spammable fame grinding quests. 

I'm 99% sure the quests i report aren't working before i try them from playing on other DSP servers. There's a mostrly up to date list on the dsp wiki but i was told to report them as i find them anyway. Guess it creates kind of a demand as to what to work on first. Now that Bkesecker seems to be working through them.

Cheers Bkesecker

**Comment by aprilgarrity** [comment]
With all of the hype for the launch of sea content, I feel that implementing this quest will save players a lot of time. I just tried to flag this quest and found that it is still not implemented.

**Comment by jamiehavok** [comment]
The quest is awesome and i hope it gets implemented but how does it make anyone save time!?

**Comment by 59blargedy** [comment]
resolved in april 18, 2022 update
