### ISSUE TITLE
"Accuracy varies with TP" is not implemented correctly

### ISSUE THREAD

**Issue by beauxq** [EdenServer/community#622]
DSP contains the claim:
"acc varies with tp ALL apply an acc PENALTY"
This is false.
I have looked for a source for this claim and can't find one.
I asked in DSP development discord, and nobody there had any source for it either.

I have noticed, and gweivyth reported documenting, that this makes Asuran Fists worse than Raging Fists.
Anyone who played MNK in retail era knows that Asuran Fists was not worse than Raging Fists.

Here is the fix:
https://github.com/bdhs/darkstar/commit/bb97b5c1ae07be63eb3332ee4693fc0c16b7bd4a

**Comment by Altnob** [comment]
Yea, as someone who's been playing FFXI since RoZ, I have never heard of a acc penalty on those weapon skills.

**Comment by tectal831** [comment]
Moved to in progress since fix has been given with ticket

**Comment by gweivyth** [comment]
Here's a VOD with me using both weapon skills a bunch on Aura Pots in sky.  It's muted, so now you don't have to listen to my stupid ass talk over the entire thing.  (Mostly because I was listening to copyrighted music while streaming...)

https://www.twitch.tv/videos/340819341

**Comment by beauxq** [comment]
The TP return is a different bug reported and fixed a long time ago.
(But the fix hasn't been put in Eden yet.)
https://github.com/EdenServer/community/issues/214

**Comment by Qair** [comment]
Please do something about Asuran fists, in it's current state I'm averaging 300 damage less than every other melee jobs weaponskill which makes an already supbar class on this server even less appealing.

**Comment by KnowOne134** [comment]
This issue was corrected last update
