### ISSUE TITLE
Maat's cap quest not functioning

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#626]
Just putting this here because there are several people in close range of this (or in the case of Oyaziiiiii, ready) to complete.

**Comment by bkesecker** [comment]
Ran through it all with each job at level 66.  Each testimony used (unable to use after use), each Maat defeated, cutscene, and Cap awarded.  Teleport function of the hat tested also.  @Treble011 Can you comment more?

**Comment by Treble011** [comment]
This was tested on the public test server before Eden went live. It's possible that a DSP merge fixed it perhaps?

**Comment by beauxq** [comment]
It might be the case that you have to do all the Maat fights on Eden. (Having done them on Kupo might not work.)

**Comment by Treble011** [comment]
Yeah, I did them all on the test server at the correct levels. I'll tell Oyaziiiiiii to try doing it, he's the only one that can get maat's cap yet, I'm 2 jobs short.

**Comment by Serephim** [comment]
Is the quest Beyond The Sun supposed to trigger in your logs before you start? I am also ready to start.

**Comment by bkesecker** [comment]
No.  It is a strange one.  Beyond the Son is never accepted, only shows in your completed log.  Once you have done all of the fights, a check is made against a set of flags, if they are all 'true', you immediately get the cutscene that results in obtaining Maat's cap.  Afterwards, you will find Beyond the Sun in your completed list.

**Comment by bkesecker** [comment]
Serephim obtained.  Closing.
