### ISSUE TITLE
Trouble geting to rank 5

### ISSUE THREAD

**Issue by Qair** [EdenServer/community#627]
The npc in the san d'orian consulate won't give my alt, Riaqpl, rank 5 or the gil reward. I have gotten the airship pass but the San d'orian receptionist just keeps telling me to make haste to the archduke's palace.

**Comment by tectal831** [comment]
This is more of an issue for GM requests. Godmode, please assist if possible

**Comment by Qair** [comment]
I want to add that I talked to the Bastokain consulate first on accident as I forgot I was from bastok and got a cutscene which i think may have bugged my rank 5 reward.
