### ISSUE TITLE
Seasoning Stone

### ISSUE THREAD

**Issue by NovadragonZero** [EdenServer/community#628]
Seasoning Stone is a level 99 limit break item and dropping from the de-levelled Goblins in Dangruf Wadi.

https://i.imgur.com/P6owPJ2.jpg

Don't have proof of dropping, but is in my inventory killing them.

**Comment by tectal831** [comment]
Earliest instance of this is 12/14/2011. Please remove

https://ffxiclopedia.fandom.com/wiki/Seasoning_Stone?oldid=1373313
