### ISSUE TITLE
Garlaige Citadel gate switches not "staying down".

### ISSUE THREAD

**Issue by Anonyy89** [EdenServer/community#631]
The switches for the doors at Gate 3 don't seem to stay down when a player steps onto them. They move down but after a sec or 2 pop right back up. Hard to get all 4 switches to be down at the same time because of this. So those need fixing.

Or just add in the stone KI.

**Comment by bkesecker** [comment]
Stone KI is out of era.  Need 4 players.

**Comment by Anonyy89** [comment]
I think you misunderstood what this bug report was about.

**Comment by godmode** [comment]
This is about the switches themselves popping up when someone is on them. Not about the stone opening the door. Reopening the issue.

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
