### ISSUE TITLE
Supplies Delivered - Outpost Not Unlocked

### ISSUE THREAD

**Issue by Siushaga** [EdenServer/community#632]
Had three new Outposts for my alt character to deliver. However, noticed that two of the three had (Done) next to them even though I had never delivered to those outposts previously - Valdeaunia and Volbow. The third new one (Elshimo Uplands) both my main and alt needed, it didn't say (Done) for either character when grabbing the supplies, delivered successfully and confirmed new OP warp available from teleported NPC. 

Next game day, even though it had (Done) for supply quest from the guard in town, I grabbed Valdeaunia supplies and delivered them, but when I checked the teleporter NPC, I do not have the new region available (so it's not just a visual bug). I confirmed that the temporary KI was removed, as well. I plan to try Volbow also, but I expect it to behave the same as Valdeaunia since it also says (Done) even though I do not have it yet - not sure if it would help for a GM/Dev be there when I deliver to try and capture what might be happening?

Character: Sadadar
Nation: San d'Oria
Regions: Valdeaunia & Volbow
Game Client: version 30181003_1

**Comment by gweivyth** [comment]
Your character isn't high enough level to warp there. If you get on a higher level job you will be able to warp there.  You can still unlock them by delivering supplies, but you won't be able to warp there unless you meet the minimum level required for that Outpost.

**Comment by Siushaga** [comment]
Okay, so even though it shows as (Done) on my list prior to ever delivering there, then as long as I still grab them and deliver once to each location then they will eventually show up on my teleporter later when I am high enough level to use it?
