### ISSUE TITLE
MNK h2h TP gain/returns

### ISSUE THREAD

**Issue by asmolyneux** [EdenServer/community#633]
MNK h2h weapons are not having their delays added to the base h2h

https://www.bg-wiki.com/bg/Category:Hand-to-Hand

"The Damage and Delay on Hand-to-Hand weapons indicate the amount of Damage and Delay added to the base damage and delay."

https://clips.twitch.tv/HardQuaintHamburgerLitty

Vid proof here, all 8 hits landed for 116 TP return which would be accurate if no weapon was equipped.  However cross-counters were.

**Comment by beauxq** [comment]
116 is not what I would expect with 8 hits no weapon. That would be 115.
116 is what I would expect with 7 hits and cross-counters equipped. I think that's what we're seeing in that video. So I think delay is being taken into account as it should be.

**Comment by asmolyneux** [comment]
Excluding store TP, each additional hit in a WS is an extra 1 TP return. Missing only 1 non-first hit would be 115 TP return. 116 is the TP return of Asuran fists with no weapon equipped and no store TP.

Full return with cross-counters should be 134 without any store TP. 

It looks like TP returns are very inconsistent overall since you got a 126, unless you WS'd in +10 sTP or had SAM sub.
