### ISSUE TITLE
BRD Unlock Quest

### ISSUE THREAD

**Issue by Syphur74** [EdenServer/community#635]
Trying to unlock bard but when I go to Bubu and click the headstone the game freezes.  It does load into the cutscene and the npc gets to the second sentence then the game locks up.  I am still able to type in ls chat and send tells but I cannot go through the cs to finish it and have to close out of Eden and relog into the game each time this happens.  I have not changed any settings from the installer and FPS is the normal 30.

**Comment by tectal831** [comment]
Are you still version matched? if yes, I recommend putting in a GM ticket for this so a non-player GM can try to trigger the cutscene for you.

**Comment by ZaksHouse** [comment]
I just did the bard quest worked perfectly for me no issues.

**Comment by Syphur74** [comment]
What do you mean version matched?

**Comment by beauxq** [comment]
What version of the client do you have?
type /ver in game

**Comment by Syphur74** [comment]
Version 30181205_0

**Comment by Syphur74** [comment]
I opened a GM ticket who had me redo the installer.  After doing that the bard quest worked just fine.  Please close this out the issue has been fixed.. Just had some corrupted files.
