### ISSUE TITLE
Hercules Beetle

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#637]
Does not seem spawnable. https://ffxiclopedia.fandom.com/wiki/Hercules_Beetle

**Comment by sugreff** [comment]
Tried for several hours (in game hours) and was not able to trade the Honey to the ???.

**Comment by Mozzy4Ever** [comment]
Just to update: NM -should've- been implemented when we last updated from DSP on Jan 4th ( 8f1bf33c63007c68eccc24925c893fe8540981ff ). NM was coded on DSP on Jan 2nd ( cac05b8176533e0ce1048825ecddb5ae50d3eb5a ). It is a valid era NM per https://ffxiclopedia.fandom.com/wiki/Hercules_Beetle?diff=231353&oldid=48314

**Comment by statuseffect** [comment]
Any word on this NM being implemented yet?
