### ISSUE TITLE
Ammo delay incorrectly added to ranged weapon delay

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#639]
From the wiki, pre WoTG (not that it was any different):

Ranged Delay
Ranged delay have a different mechanism from melee delay :

Ranged delay is about twice as fast as melee delay : 110 delay/second
Ranged weapon delay is the only variable affecting the total delay. Ammo delay doesn't affect the total delay.
Ranged attack delay is divided into 3 phases :
1. Pulling out ranged weapon, aiming, and shooting : this time span is calculated by : Weapon Delay / 110
2. After shooting → putting back ranged weapon : This delay usually takes 1.7 second to 1.8 second. However, occasionally, it can take fluctuate from 1.6 second to 1.9 second
3. "Free" phase : at this time span, melee timer is un-paused. The minimum time this delay can have is 1.1 second
So the delay between shot of ranged weapon is :
Delay = (Weapon Delay/110)s + 1.7s~1.8s + 1.1s

https://ffxiclopedia.fandom.com/wiki/Delay?oldid=252176

**Comment by godmode** [comment]
I think what has happened is the ammo delay was added to the aim phase instead of the delay between shots. Good link.

**Comment by Siushaga** [comment]
Yep, ammo delay should be for the delay after shooting. Otherwise, it's mostly for the TP return formula. 

https://ffxiclopedia.fandom.com/wiki/Talk:Delay?useskin=oasis

This was a good discuss page with other details that essentially confirm what you're saying. It was something we were discussing on the forums too.

http://www.edenxi.com/forums/viewtopic.php?f=3&t=434

**Comment by godmode** [comment]
Other than it just seeming longer; then, for most purposes, I think the change won't be game breaking or nerfing for now. (Compared to retail) Just puts when the delay happens out of order.

**Comment by Siushaga** [comment]
I would disagree... things likes pulling where only shooting once and done until next pull, it's adding unnecessary extra delay.

**Comment by godmode** [comment]
Ah good call

**Comment by ThrisStraizo** [comment]
> I think what has happened is the ammo delay was added to the aim phase instead of the delay between shots. Good link.

I don't think the delay is even added for the delay between shots, but purely for TP reasons.  The wiki suggests that it's a near constant.

Take a look at this corsair shooting bullets, which have a long delay for ammo.  The delay between shots would be noticeably longer if it was added between the shots.

https://youtu.be/pG83mG8W634?t=140

This one might be a better example: https://youtu.be/-8-VsYyNwFM?t=132

I threw in this one too even if he is a filthy casual and not using a /ra macro. 
https://youtu.be/D5wvgcXZomE?t=159

The delay seems just as long as the pause was before this patch.

**Comment by godmode** [comment]
Thanks for the links I’ll check them out when I’m off work tonight. I do remember there being a delay after you shot before you could shoot again though and that delay doesn’t exist on DSP. Granted I only shot about 5 times to test that part.
