### ISSUE TITLE
Nihniknoovi - ??? functioning incorrectly

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#645]
This NM is out of era and current the ??? in La Theine gives bird eggs constantly.

https://ffxiclopedia.fandom.com/wiki/Nihniknoovi

**Comment by rujind** [comment]
The wiki history shows that NM as in era.

**Comment by Treble011** [comment]
You're correct, it was era, never saw it that early. 

The ??? does not move, however, and you can spam click it for bird eggs, needs fixed.

**Comment by bkesecker** [comment]
I didn't seem to have trouble getting the FallenEgg to disappear leaving only 1 bird egg behind.  It respawned in the northern most point both tries I made.  I filed another bug related to the mob's attack rate.
