### ISSUE TITLE
Journey Abroad (2-3 mission) NPC won't talk to me

### ISSUE THREAD

**Issue by Ganbatte92** [EdenServer/community#646]
Having received the KI (Letter to the consuls), I decided I wanted to do the Windurst dragon, and so I went to Bastok first and headed to the top floor of the consult. 

The wiki says I need to receive a CS from Savae E Paleade in Metalworks. However, every time I speak to her she says, "Good luck on your mission" and I don't get a CS, as if I've already spoken to her before... 

I went to Pius, the next NPC I'm supposed to speak to, but he doesn't offer me a CS either or forwards my mission in any way. I'm stuck. 

I contacted a GM and they asked me if I definitely spoke to Halver, have the KI and if the mission is flagged in my inventory. I checked and, yes it is flagged in my current missions. 

I've logged, zoned, and restarted my computer. Nothing seems to work.

I'm not sure whether this affected anything, but I was in a party at the time with someone who had dragon access. They were waiting for me to catch up.. 

(Thanks for all your work as usual!)

**Comment by Ganbatte92** [comment]
*WORKS*

I travelled all the way back to see Halver, and he gave me ANOTHER KI (???).

Went back to Bastok, and this time it worked! 

Oh well.. got there in the end.

**Comment by godmode** [comment]
If this is still an issue please request a GM ticket. We are currently looking into the issue but have enabled GMs to progress you through this mission if you meet the necessary requirements.
