### ISSUE TITLE
Level Sync XP Not the Same

### ISSUE THREAD

**Issue by CdoubleOkay** [EdenServer/community#650]
When lvling with my alt I was receiving different XP on each character. I had signet running on both and no rings and I was properly synced to the lower character.

https://gyazo.com/0e2de0b4df3ef23530eb2e99bc676186

https://gyazo.com/fe7d5b7b28b16de936d60fe3b63cd211

For reference. This has happened 3-4 times to me now.

**Comment by InoUno** [comment]
Should be resolved in February 1st, 2021 patch.
