### ISSUE TITLE
Bi'Gho Headtaker no drops

### ISSUE THREAD

**Issue by yokhai** [EdenServer/community#651]
Just killed Bi'Gho Headtaker for a shot at one of his guaranteed drops, Power Crossbow or Plantbane and didn't receive either. Might be a bug, might not be set to drop one or the other. 
![vinsanity_2019 01 02_101101](https://user-images.githubusercontent.com/10634251/50598068-9a0dbf00-0e77-11e9-9264-b3c0447dfb85.png)

Thanks for everything guys. Love y'all!

**Comment by yokhai** [comment]
Second screenshot of no drops. 
![vinsanity_2019 01 03_223934](https://user-images.githubusercontent.com/10634251/50673008-48655180-0fa9-11e9-9c7b-804007cade1d.png)

**Comment by yokhai** [comment]
Jasson confirmed the items were not grouped together in the DB, he said you'd just need to set their item type to be the same number then define their values, i think its 80% for Power Crossbow and 20% for Plantbane. If anyone has time to look at it I can show you what he showed me. Vinsanity in-game.

**Comment by godmode** [comment]
Will fix just working on some higher priority things right now.
