### ISSUE TITLE
Quest - Missionary Moblin

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#652]
Tried to start this quest by talking to the npc Koblakiq in Oldton Movalpolos but all she tells me is "Back off!", which is odd as this quest seems to have to no pre-requirements. Also tried to trade her the letter for the quest and that didn't do anything either.

https://ffxiclopedia.fandom.com/wiki/Missionary_Moblin

**Comment by mpinholster** [comment]
I tried the same and got same result

**Comment by KnowOne134** [comment]
Added 2/8/2021
