### ISSUE TITLE
Unable to purchase Royal Knight's Breeches with CP at rank 10

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#654]
![chawlee_2019 01 02_195038](https://user-images.githubusercontent.com/40915578/50623154-f00a5300-0ec7-11e9-85fe-9e797fe6bd47.png)

**Comment by Siushaga** [comment]
Doesn't San d'Oria have to be 1st in the Conquest placement to purchase that? An odd error message for that reason, but I do believe that is what's preventing the purchase.

https://ffxiclopedia.fandom.com/wiki/Royal_Knight%27s_Breeches?oldid=368559

**Comment by Siushaga** [comment]
I bought some earlier today no problem.
