### ISSUE TITLE
Ubume

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#655]
Ubume for SAM AF quest in Labyrinth of Onzozo never seemed to cast the spells it's supposed to. Someone also said the goblins where the spawn ??? is are also higher level than they should be but can't confirm this atm.
https://ffxiclopedia.fandom.com/wiki/Ubume

**Comment by godmode** [comment]
Could you add more information on this. The wiki only says that it favors Horde Lullaby. What was it casting and what should it be casting?

**Comment by Zaekkor** [comment]
I just did this fight. It's supposed to cast Horde Lullaby every 30 seconds per the wiki, and it did not cast it at all.
https://ffxiclopedia.fandom.com/wiki/Yomi_Okuri

**Comment by 59blargedy** [comment]
resolved in January 18, 2021 update
