### ISSUE TITLE
pet kills remove treasure drop chance

### ISSUE THREAD

**Issue by blacknesscrows** [EdenServer/community#656]
IF a mob is killed with a ready ability, the chance for a drop goes to 0%. If you open with a 'ready' the mob remains unclaimed. These issues are most likely linked. 

sootle

**Comment by Lilswitche** [comment]
My experience with ready is slightly different.  If you 1-shot a mob with ready before any other action you don't get a drop but I was hitting mobs with /re from a THF then readying and it was fine.

**Comment by roriffxi** [comment]
Pets don't claim with special abilities, so if they 1shot with that ability, no loot or xp is awarded.

I'm not certain if this is intentional to prevent Astral flow burns.

**Comment by gweivyth** [comment]
> Pets don't claim with special abilities, so if they 1shot with that ability, no loot or xp is awarded.
> 
> I'm not certain if this is intentional to prevent Astral flow burns.

Worked this way in retail too, you always needed to at least tag it with an auto attack or something on the pet before nuking.
