### ISSUE TITLE
NM Goliath in Fei'yin, check if present request

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#657]
Could someone with server code access please check if the NM Goliath is active on Eden?

https://ffxiclopedia.fandom.com/wiki/Goliath?oldid=243231

It is era, the drop is of no real value, just used for a single Era synth (Millionaire Desk)
Current Wiki says it may pop back to back, no clue if that's era lol

Edit, asking since I'm killing all the statues in spawn area since like 6hrs now

**Comment by godmode** [comment]
It is implemented in Eden
