### ISSUE TITLE
Journey Abroad Sandy 2-3 Mythril Sand.

### ISSUE THREAD

**Issue by Sethious** [EdenServer/community#658]
On mission 2-3 i started at Bastok talk to the npc, went into palborough mines mined the gravel, grinded it and collected it, took the boat back to Bastok and now Savae E Paleade will not accept the sand when i trade it.

**Comment by beauxq** [comment]
duplicate https://github.com/EdenServer/community/issues/492

**Comment by Cyclohexene1** [comment]
Character name: Saga
Mission Sandy 2-3 - Part 1 (Bastok) 
I've talked to consolute, Pius, and Ghrom. 
Mythril Sand won't trade, and Ghrom does not give CS.
