### ISSUE TITLE
2x of a Character displayed, but only one logged in

### ISSUE THREAD

**Issue by Snitchie** [EdenServer/community#659]
![doublesni2](https://user-images.githubusercontent.com/33019601/50656029-34622580-0f92-11e9-9793-977f0d2b561e.JPG)

I dual box with Lilo and Snitch. When Snitch logs in , no matter if b4 or after Lilo. There is always 2x Snitch in Snitch's Ashita client.   See screenshot..  

so when a REAL 3rd member joins pt, to target that member i must press F4...

Do not know what will happen if in a party of 6 ppl..

**Comment by Snitchie** [comment]
Issue solved. Ty to Enthyx  :P

**Comment by godmode** [comment]
Can you elaborate? What was the solution? So others that have the problem can reference it

**Comment by Snitchie** [comment]
Solution, after logged in with double Chr's Solo. I made party with Lilo (alt) disbaned party, and voila I was no longer duplicated..   Tried this yesterday but didnt work so not sure why it worked today.   But disbanding a party made it "refresh" and only one chr.

**Comment by Snitchie** [comment]
Replied in post. Sorry should have elaborated the solution. But was
streaming when it got fixed.

Den fre. 4. jan. 2019, 12:55 skrev Godmode <notifications@github.com:
