### ISSUE TITLE
Bait and Switch quest not implemented

### ISSUE THREAD

**Issue by jamiehavok** [EdenServer/community#660]
Npc does not give the quest.
Wiggo got this working for dsp end of 2017 but was not merged.
https://ffxiclopedia.fandom.com/wiki/Bait_and_Switch

Wiggos dsp entry:
https://github.com/DarkstarProject/darkstar/pull/4235

**Comment by bkesecker** [comment]
Code is ported.  Testing now.

**Comment by jamiehavok** [comment]
awesome thanks Bkesecker!

**Comment by bkesecker** [comment]
Fully implemented.  Once reviewed, it hopefully makes it into the March 25th update.

**Comment by hookstar** [comment]
Did this ever get pushed to TPZ/LSB or subsequent repos?

**Comment by bkesecker** [comment]
@hookstar I don't see it, or see it pending.  However, I was planning to port it after my latest LSB PR merged.  I owe it to Wiggo since he started it.
