### ISSUE TITLE
Can't Unequip Shield

### ISSUE THREAD

**Issue by Khuul80** [EdenServer/community#662]

**Comment by Khuul80** [comment]
Hey I saw this issue but it was closed so I opened a new one.  I am having the issue right now with a Shell shield blabs on about needing grips.  In game name is Khuul

**Comment by bkesecker** [comment]
I used Shell Shield also at your level, but did not have an issue with unequip.  Try removing your weapon, then the shield.  Or, get a https://ffxiclopedia.fandom.com/wiki/Butterfly_Axe and equip that.  Or, change jobs in Mog House.  All of these would be workarounds.

**Comment by tectal831** [comment]
Not reproducible
