### ISSUE TITLE
High level Quadav in Beadeaux aggroing through floor.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#665]
The Ancient/Sapphire/Darksteel Quadav at I-J/5-6 on Map 1 aggro through the floor upstairs.

**Comment by TheKingOfJeuno** [comment]
i second this, specifically in the area around J6 , J7 , K6 , and K7... if you're also fighting any mobs up top.. they can also area sound aggro to sapph, dark, ancient, and plantinum quadavs which then kill you.... making it hard to farm the NM that drops valkyrie's mask/ duelist rapier

**Comment by starnack** [comment]
Can Third this issue, especially around Valk Mask NM.
