### ISSUE TITLE
Weskit Curse effect & Power leveling

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#666]
Mobs cursed by an Igqira/Genie weskit still yield full exp. Could be abused to take 15% hp off of every exp mob when powerleveling. Recommend yielding 85% exp or negating exp entirely in this circumstance.

**Comment by godmode** [comment]
Do you know how it was in retail? I don’t remember if it did something to exp? I do know the chance was kinda rare though so waiting for it to proc would be kinda more chore than just killing 15%. Is it super common for curse to proc on Eden?

**Comment by Aneyus** [comment]
I'm not sure how common the procs were, but over the course of the party I cursed a single mob on 2-3 occasions when roughly ~6 mobs were attacking me during thunder 4 casts. The vast majority of the time I was wearing other body pieces

**Comment by godmode** [comment]
This is on a PL though? Like the PL curses the mob but exp is not dirtied to PLs level?

**Comment by Aneyus** [comment]
Yes exactly. In particular we were doing the bat camp in fei'yin and before we would take breaks I would nuke the bat we were using to link pulls. During the nuke cast sometimes one of the mobs attacking me would get cursed but still give full exp, untainted by the PL's level.

**Comment by tectal831** [comment]
I just wanted to point out that ticket #666 has to do with curse effect. Well played Aneyus
