### ISSUE TITLE
Allowed to Harvest on full Mog Safe

### ISSUE THREAD

**Issue by maeinit** [EdenServer/community#668]
Sadly I did not check before fully harvesting my plants, but when I did check my safe I only received one of my harvest (probably since I was 49/50). 

Instead of prompting that I did not have enough room it said I had harvested from every pot, which just caused the items to be lost. 

No error messages and just continues without checking safe.
https://gyazo.com/e39c6628bd27e0e31a99ced8e4f1023e
![image](https://user-images.githubusercontent.com/12605529/50710965-6373a800-1021-11e9-8ca0-b80efc90361a.png)

>  When you harvest your plant, your results will be placed directly into your Mog Safe, so make room, as you will not be allowed to harvest until there is room. 

From about middle of gardening guide page, under life cycle image. : https://ffxiclopedia.fandom.com/wiki/Category:Gardening

Full safe, least I got one rock.
https://gyazo.com/72c6e3fca373bdaefc29336b9a731473
![image](https://user-images.githubusercontent.com/12605529/50710975-6a021f80-1021-11e9-8981-55242bf35ca3.png)

**Comment by godmode** [comment]
I’m slightly confused. Is this a bug or a warning to others? Does retail handle it like Eden does?

**Comment by maeinit** [comment]
Retail will say you cannot harvest them since your Mog Safe inventory is full.

Eden currently does not handle it like retail because there is no error if your Mog Safe inventory is full. Instead it just takes the plants out and throws them off into some abyss of no return.

In short, Eden is missing an error message and stop from moogle harvesting the plants if Mog Safe is full.

**Comment by godmode** [comment]
Gotcha! Ok thanks

**Comment by Oyaziiiiiii** [comment]
Did you check mog safe 2? When I harvest they go into mog safe 1, then mog safe 2 if the first safe is full. If both are full it doesn't let me harvest the plant.

**Comment by Setz0r** [comment]
Confirmed this is how the harvesting functionality is coded.
