### ISSUE TITLE
Quest "A Timely Visit" will not start

### ISSUE THREAD

**Issue by MysticLogos** [EdenServer/community#671]
The quest "A Timely Visit" which starts in Southern San d'Oria will not start.  It requires 3 San d'Oria fame, and I have 6.  I tried zoning and both 30 fps and 60 fps.

**Comment by bkesecker** [comment]
I also find this quest unable to start.

**Comment by bkesecker** [comment]
Not implemented in DSP.  https://wiki.dspt.info/index.php/Quests

**Comment by bkesecker** [comment]
I plan to implement this one soon.

**Comment by bkesecker** [comment]
As it turns out, beauxq worked on this at one point, but said it got lost.  https://github.com/bdhs/darkstar/commit/d92aa9e7fa3c9624f393276e4b692533cdf76563 Will use a lot of this to finish implementation.

**Comment by bkesecker** [comment]
Progress note: Getting close to finishing this one up, but the other pull request I made is still pending.

**Comment by bkesecker** [comment]
All the blanks are filled, final testing to be done 2/17/2019, and then issue a pull request to DSP master.

**Comment by bkesecker** [comment]
https://github.com/DarkstarProject/darkstar/pull/5753
