### ISSUE TITLE
Scrawled Writing (Parade Gorget pop) repop instantly

### ISSUE THREAD

**Issue by Zaekkor** [EdenServer/community#672]
The Scrawled Writing pop in Oldton Movalpolos that is used to spawn Goblin Wolfman, the Parade Gorget NM is supposed to take 15 minutes to respawn in one of 3 locations after the NM dies or despawns. However, upon popping and killing the NM, the Scrawled Writing repopped instantly after the NM was defeated. This occurred each time it was defeated and it repopped each time in the same location so it did not bounce.

https://ffxiclopedia.fandom.com/wiki/Goblin_Wolfman?oldid=375778

**Comment by jmf9808** [comment]
It wasn't implemented in DSP so I made a pull request with it. 
https://github.com/DarkstarProject/darkstar/pull/5629

**Comment by Setz0r** [comment]
Thanks Far
