### ISSUE TITLE
Misnamed Tonberry in Den of Rancor

### ISSUE THREAD

**Issue by kochiemonster** [EdenServer/community#678]
There is a tonberry imprecator (blm) with a club and drops blm test.  But it is called slasher  at H-8 on map 5  i think. Right near zone back into jungle

**Comment by Caelic** [comment]
Mob names can't be changed server side. They have to be fixed with .dat mods in your client.

**Comment by tectal831** [comment]
Please check version update from today and try again

**Comment by Setz0r** [comment]
@kochiemonster can you confirm the issue is still ongoing?  Which version of client are/were you using.

Thanks!

**Comment by kochiemonster** [comment]
I'd have to get back through the gates. ><  
I was updated after latest dsp pull.
