### ISSUE TITLE
Unable to progress quest "Say it with Flowers"

### ISSUE THREAD

**Issue by maeinit** [EdenServer/community#680]
Questing in Windurst I was able to pick it up just fine from the starting NPC, Moari-Kaaori. After picking it up I went to speak to Ohbiru-Dohbiru to continue progressing it. Only to find that all he says is "Thank you and ta-ta~ru!" 

I did not do any other quest with or needing to speak to Ohbiru-Dohbiru, so I'm guessing it's not coded yet. And I'm pretty sure I do not have any active quest/missions that would conflict with it.

Quest details; https://ffxiclopedia.fandom.com/wiki/Say_It_with_Flowers
NPC;  https://ffxiclopedia.fandom.com/wiki/Ohbiru-Dohbiru

**Comment by Xerlic1212** [comment]
I also have the same problem. I have the quest flagged and in my log. I cannot progress the quest past the part with Ohbiru-Dohbiru similar to the OPs experience.

**Comment by Xerlic1212** [comment]
Follow-up: I was able to progress with the quest after completing other quests in Windurst. I can't say for certain which one it is, but if you're stuck just try finishing more quests and then try speaking to Ohbiru-Dohbiru again.

**Comment by erenik** [comment]
An update on this: I managed to start the quest, but gave the wrong order of answers resulting in Ohbiru-Dohbiru giving me a Rain Lily instead. I cannot trade this to the quest-giver to complete the quest (supposedly doable with a lesser reward).

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update
