### ISSUE TITLE
Slendlix Spindlethumb NM, Inner Horutoto Ruins.

### ISSUE THREAD

**Issue by Novadragon-Siren** [EdenServer/community#681]
NM is meant to be a Goblin, but he is a mage Warlord in Inner Horutoto Ruins.

https://imgur.com/sgVkyPP

**Comment by Novadragon-Siren** [comment]
Pretty sure Eden. Friend Mattyg from Kupo said he saw him as an Orc.

**Comment by jmcmorris** [comment]
@godmode This would be caused by the NM having the wrong model assigned to it in the mob_pool table.

**Comment by godmode** [comment]
Yep

**Comment by MGramolini** [comment]
NM is out of era anyway.  But it has been this way since Kupo.
