### ISSUE TITLE
Can't Desynth Rising Sun

### ISSUE THREAD

**Issue by Caelic** [EdenServer/community#682]
As title states. The desynthesis recipe on FFXIclopedia was added in Dec 2009 though I believe this is due to lack of information as the alternative would that SE added a desynth recipe to it years later when this is already an incredibly rarely seen item. I checked my own server and it appears this desynth just is not on base DSP (I haven't updated my server to the latest dsp build in months, but still...) so I'm assuming that's why it is also not on Eden. Here's the page: https://ffxiclopedia.fandom.com/wiki/Rising_Sun?oldid=1054658

I spent 12 hours straight in Davoi farming masks for gold then another hour desynthing the masks then grabbing tama-hagane in Norg all depending on being able to desynth for extra skillups. Please fix this for my own sanity... here's an SQL script to do it.

```
INSERT INTO dspdb.synth_recipes VALUES 
(5577, -- just some very high synth ID number, unused on DSP, double check on Eden?
0, -- desynth
0, -- no key item
0, -- alch
0, -- bone
0, -- cloth
0, -- cook
51, -- goldsm (same value used to craft Rising Sun)
0, -- leathercr
87, -- smith (same value used to craft Rising Sun)
0, -- woodw
4100, -- lightning crystal
4242, -- HQ lightning crystal
17286, -- ingredient, Rising Sun
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
914, -- NQ, mercury
1225, -- HQ1, gold nugget
1225, -- HQ2, gold nugget
657, -- HQ3, tama-hagane
1, -- 1x mercury
4, -- 4x gold nugget
6, -- 6x gold nugget
1); -- 1x tama-hagane
SELECT * FROM dspdb.synth_recipes where ID > 5500;
```

Saw a report on Greaves not desynthing either so here's a bonus for that:

```
INSERT INTO dspdb.synth_recipes VALUES 
(5578, -- just some very high synth ID number, unused on DSP, double check on Eden?
0, -- desynth
0, -- no key item
0, -- alch
0, -- bone
0, -- cloth
0, -- cook
0, -- goldsm
6, -- leathercr
33, -- smith
0, -- woodw
4100, -- lightning crystal
4242, -- HQ lightning crystal
12936, -- ingredient, Greaves
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
851, -- NQ, ram leather
651, -- HQ1, iron ingot
651, -- HQ2, iron ingot
651, -- HQ3, iron ingot
1, -- 1x ram leather
1, -- 1x iron ingot
2, -- 2x iron ingot
3); -- 3x iron ingot
SELECT * FROM dspdb.synth_recipes where ID > 5500;
```

**Comment by Caelic** [comment]
What info do you need Tectal? Also edited again, github formatting fucked up the first line of the code, just fixed it.

**Comment by Caelic** [comment]
Rising Sun's first entry in FFXIclopedia is June 4 2006
https://ffxiclopedia.fandom.com/wiki/Rising_Sun?oldid=76799

WOTG release date is
November 20, 2007

Thus, it is at the latest, a ToAU item, so in era for Eden.

**Comment by Caelic** [comment]
https://ffxiclopedia.fandom.com/wiki/Rising_Sun?oldid=94656

This is a June 25, 2006 revision, still well before WOTG era. States "Crafted Only!" at the bottom. Desynth is "??" probably indicating unknown information. It's a bit of an expensive item in era times, hence a very rare item to see, so it's pretty safe to assume it had a desynth recipe since the item was added, it was just that whoever made/bought one didn't desynth theirs so noone really knew the desynth results.

**Comment by Caelic** [comment]
Some additional info here: while on FFXIclopedia the desynth recipe was written in Dec 2009, there is a comment on FFXIah.com that predates that by over a year showing the desynth was still a thing then too: Oct 2008. Here's a link: https://www.ffxiah.com/item/17286/rising-sun

BG wiki has a full log of version updates here: https://www.bg-wiki.com/bg/Category:Update_History

The WOTG update was Nov 19, 2007. In that patch or the three patches after which all come before Oct 2008, there is no info stating any desynthesis recipes were added.

A bit off-topic too but as I was reading I realized the rings we can get at the guild point NPCs on Eden are out of era:
https://www.bg-wiki.com/bg/Version_Update_(06/09/2008)

**Comment by Caelic** [comment]
Also the FFXIAH comment conflicts with the desynthesis recipe. This is one singular guy's post on FFXIAH versus the one singular guy who wrote it in on FFXIclopedia but it would make more sense to me if the tama-hagane was HQ1 instead of the HQ3 since the gold nuggets are worth more. Edited script for that instead:

```
INSERT INTO dspdb.synth_recipes VALUES 
(5577, -- just some very high synth ID number, unused on DSP, double check on Eden?
0, -- desynth
0, -- no key item
0, -- alch
0, -- bone
0, -- cloth
0, -- cook
51, -- goldsm (same value used to craft Rising Sun)
0, -- leathercr
87, -- smith (same value used to craft Rising Sun)
0, -- woodw
4100, -- lightning crystal
4242, -- HQ lightning crystal
17286, -- ingredient, Rising Sun
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
0, -- null ingredient
914, -- NQ, mercury
657, -- HQ1, tama-hagane
1225, -- HQ2, gold nugget
1225, -- HQ3, gold nugget
1, -- 1x mercury
1, -- 1x tama-hagane
4, -- 4x gold nugget
6); -- 6x gold nugget
SELECT * FROM dspdb.synth_recipes where ID > 5500;
```

**Comment by icariumkupo** [comment]
I know we shouldn't bump but I just made like 30 of these x.x lol

The script has been provided.. could we get this one resolved? 

Thanks so much for your hard work!

**Comment by Caelic** [comment]
still waiting for this to get fixed so i can continue with smithing... the code is here just run it
