### ISSUE TITLE
Parry Procs when Asleep

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/community#683]
Parry activates despite being asleep. Suspect this may be the case with petrification and/or stun also.

Related issue for Counter: https://github.com/EdenServer/community/issues/614

**Comment by Caelic** [comment]
It's happened to me too. Slept in necropolis a few weeks ago and was parrying attacks so it took forever to wake up. Was in quicksand last week killing anticans and parried 3 attacks while petrified... that one saved my ass too.
