### ISSUE TITLE
Threnodies Increasing Resistance Instead of Lowering

### ISSUE THREAD

**Issue by Alamandaros** [EdenServer/community#684]
Apparently this is or was a known DSP bug on other servers. Threnodies will increase the appropriate resistance on the mob, rather than decreasing it. I've been unable to test this myself, and according to 75 BRDs on the server they don't use the songs often enough to notice, however a 75 BLM mentioned that they thought this was in fact happening.

**Comment by Setz0r** [comment]
confirmed threnody raises resistance...  water damage went from consistence 28-29 on quadav down to 7-9 after casting water threnody on it.
