### ISSUE TITLE
Recollection of Guilt acting like Rare

### ISSUE THREAD

**Issue by ghost** [EdenServer/community#685]
Shown below, i could not obtain a second Recollection of Guilt even though it's not rare.

![image](https://user-images.githubusercontent.com/10634251/50743120-17bc2c80-11e2-11e9-9bf5-fc41d4fbc60b.png)

**Comment by godmode** [comment]
Check the wiki history it might be rare in this era. If so it needs a dat mod

**Comment by Caelic** [comment]
@godmode you are correct, a ToAU era dated revision states it's Rare/EX

https://ffxiclopedia.fandom.com/wiki/Recollection_of_Guilt?oldid=124259

**Comment by Camuel666** [comment]
https://ffxiclopedia.fandom.com/wiki/Recollection_of_Guilt?oldid=365773
this link is the 2007 link stating we can sell and that it isnt rare/ex

**Comment by MGramolini** [comment]
This item along with other CoP mission items were once said to be “original” and not era aka 2003, per Godmode. The chips in Pso’xia is another example of items that are also rare/ex originally but not in 2007.

**Comment by KnowOne134** [comment]
These now have been dat moded
