### ISSUE TITLE
Tele Dem ??? KI Retrieval

### ISSUE THREAD

**Issue by SaberSuper** [EdenServer/community#687]
I have the quest active and i've found the ??? but it says "You Find Nothing Special Here."  i've checked every other room on this level and it's the only ???.  Quest details don't seem to specify any other steps required.

**Comment by godmode** [comment]
Need more details. What position were you at for one. Maybe a SS.

**Comment by Aneyus** [comment]
I believe he was in the correct spot if it's at H-8 in the room with two Wingrats.

**Comment by SaberSuper** [comment]
I was at the location on the map provided.
Altana's Sorrow


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Altana's Sorrow

Walkthrough Talk to Virnage at (H-5) in the back room of the Bat's Lair Inn. He mentions paint from the Great Wa...
 |

 |

 |



I also checked every other room on the upper floor 3 times and no other ??? was available inside of the rooms.
    On Tuesday, January 8, 2019, 12:30:14 PM EST, Aneyus <notifications@github.com> wrote:  
 
 
I believe he was in the correct spot if it's at H-8 in the room with two Wingrats.

**Comment by KnowOne134** [comment]
Closing as havent heard of the issue occurring to anyone else
