### ISSUE TITLE
Incorrect skillchains

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#69]
Raging rush > Raging rush is creating Induration.  It should be doing Fragmentation.

I'm sure there are other combinations that aren't creaing the correct SCs and I'll add them here if I find them.

http://magitekarmy.com/skillchain.php

Heres what I use for figuring out what chains get created with what WS combinations, but if you read any old Maat guides for warrior they all talk about self-SC'ing fragmentation to beat him.

**Comment by Shoruto** [comment]
Raging Rush has the attributes of **Induration** and **Reverberation**.  When the skillchain combo is used once it makes **Induration**.  When used a second time right after it makes **Fragmentation** (Level 2).  I was able to verify this through these sources.  I placed each one back to era dates for accuracy.

https://ffxiclopedia.fandom.com/wiki/Raging_Rush?oldid=338835
https://ffxiclopedia.fandom.com/wiki/Category:Skillchains?oldid=750925
https://www.bg-wiki.com/index.php?title=Raging_Rush&oldid=104862
http://ffxi.allakhazam.com/wiki.html?p=Induration&oldid=137496
https://finalfantasy.fandom.com/wiki/Skillchain?oldid=2675434

**Comment by Lilswitche** [comment]
I double checked base DSPs skillchain attributes for Raging Rush and other similar WSs and they seemed correct.  The issue may like with how it determines the skillchain.

On Mar 19, 2019 8:44 AM, Shoruto <notifications@github.com> wrote:

Raging Rush has the attributes of Induration and Reverberation. When the skillchain combo is used once it makes Induration. When used a second time right after it makes Fragmentation (Level 2). I was able to verify this through these sources. I placed each one back to era dates for accuracy.

https://ffxiclopedia.fandom.com/wiki/Raging_Rush?oldid=338835
https://ffxiclopedia.fandom.com/wiki/Category:Skillchains?oldid=750925
https://www.bg-wiki.com/index.php?title=Raging_Rush&oldid=104862
http://ffxi.allakhazam.com/wiki.html?p=Induration&oldid=137496
https://finalfantasy.fandom.com/wiki/Skillchain?oldid=2675434

**Comment by Shoruto** [comment]
It definitely could be reading them incorrectly in some manner

**Comment by 59blargedy** [comment]
this was resolved in 5/16/20's patch, just needs to be added to notes
