### ISSUE TITLE
Crafting time is borked with new patch

### ISSUE THREAD

**Issue by Caelic** [EdenServer/community#690]
38 seconds from the end of one synth to the start of the next. That's like 1synth/min if you count start to start... so awful to play with. PLEASE fix. It's only happened since the patch...

https://i.imgur.com/1uKCwAB.jpg

**Comment by inaringo** [comment]
Issue is back after the server came up just now.

**Comment by godmode** [comment]
Does this issue still occur?

**Comment by FariskaEden** [comment]
Been using the last synth macro with like a 20 second wait time, so I think the issue doesn't occur anymore.

**Comment by godmode** [comment]
Thanks, closing this issue then. Please comment if it still exists.
