### ISSUE TITLE
Black Mage using retail spell values after 1/7/19 patch

### ISSUE THREAD

**Issue by Zheta** [EdenServer/community#691]
Level 9 Black Mage
Stone is costing 4 MP
Water 5 MP
Casts almost instantly
Seems to be using retail values

(Ranger in Discord, Astra/Bashtra in game)

**Comment by Zheta** [comment]
video: https://youtu.be/uD3xK-mD304

**Comment by Bringerofdeath56** [comment]
Yeah I just cast stone went from 407 mp to 403 mp
