### ISSUE TITLE
Balam-Agab

### ISSUE THREAD

**Issue by Kurtalicious** [EdenServer/community#694]
Balam-Agab is a Fields of Valor NM in Sauromugue Champaign and needs to be removed from Eden because it is OOE.

**Comment by Caelic** [comment]
That's weird how it does spawn...

Proof it's WOTG era:
https://ffxiclopedia.fandom.com/wiki/Balam-Agab

Original page was Apr 2009.

**Comment by Kurtalicious** [comment]
Idk how it spawns but I never seen it down.
