### ISSUE TITLE
Not receiving Holla gate crystal 

### ISSUE THREAD

**Issue by Hruizii** [EdenServer/community#698]
When clicking telepoint, text indicates reviving "Holla gate crystal".  It is not in permanent key item section, and i am unable to tele-holla

**Comment by Hruizii** [comment]
full inv blocks getting the key item

**Comment by godmode** [comment]
I was unable to reproduce this with full inventory. Please fill your inventory again and see if this happens again next telepoint crystal you get. If it does please comment on this ticket. Also please make you are on the latest client.

**Comment by Hruizii** [comment]
I updated yesterday afternoon prior to this issue. I will try it at
tele-dem and update you today
