### ISSUE TITLE
Guivre doesn't roam

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#70]
Guivre is supposed to roam around Kuftal tunnel, eating hapless XP parties and interfering with people trying to break weapons. I miss this important aspect of classic FFXI.

He currently just stands still in the middle of the big room and doesn't move unless aggrod.

**Comment by Lilswitche** [comment]
FFXI is all about the small details - Like when you're just doing your thing in Kuftal thinking Guivre is dead, and he pops and eats your face off.... ahh the good ol' days.
