### ISSUE TITLE
Incorrect Era guild point return for brass finger gauntlets

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#702]
After turning in 6 brass finger gauntlets I recieved 2592 guild points, which is 432 per turn-in (current retail values). Era retail values peg individual turn-ins at 736 per capping at 4000. Reference: https://ffxiclopedia.fandom.com/wiki/Guildworker%27s_Union#Goldsmithing

**Comment by Shoruto** [comment]
Slight issue, the link you posted is from 2017, the latest update they have which makes it post era.  There wasn't any updated guild points for that item during era times.  I checked everywhere I can think of and wasn't able to find a current era guild point number.  But 736 with cap of 4000 is from November 6, 2017

https://ffxiclopedia.fandom.com/wiki/Guildworker%27s_Union?oldid=1605126

The earliest Wikia starts posting guild points for that item is April 4th, 2012

https://ffxiclopedia.fandom.com/wiki/Guildworker%27s_Union?oldid=1392834

**Comment by Setz0r** [comment]
https://ffxiclopedia.fandom.com/wiki/Brass_Finger_Gauntlets?oldid=291399
clearly shows it should be 736 with 4k cap
