### ISSUE TITLE
Kalifriki - Quest Progress Erased

### ISSUE THREAD

**Issue by Kalifriki** [EdenServer/community#704]
While returning to Windurst Waters on to talk to the NPC to complete the Quest: Early Bird Catches the Bookworm relevant NPCs failed to acknowledge Kalifriki's current quest status; regardless of having the temporary key item: Art for Everyone. Additional dialog for Orn, nor the completion NPCs in Opistery responded to the quest.

https://ffxiclopedia.fandom.com/wiki/Early_Bird_Catches_the_Bookworm

Upon further inspection it was confirmed Kalifriki lacks any log of Current or Completed Quests in any area he has undertaken them. His Key Items are intact, but without the NPCs giving him the ability 'restart' the quests are irrelevant.

Balthamel undertook the same quest earlier without the same issue, having maintained all her Quest information.

<img width="815" alt="quests_kali" src="https://user-images.githubusercontent.com/46100825/50859904-39402400-135a-11e9-8b4b-5e17b5b97c45.PNG">
<img width="832" alt="quests_kali_completed" src="https://user-images.githubusercontent.com/46100825/50859911-3c3b1480-135a-11e9-86a0-9b0488a94549.PNG">

**Comment by Kalifriki** [comment]
This also means that Kalifriki currently lacks his fame / reputation levels.

**Comment by godmode** [comment]
You reported this in the correct place but for this specific issue please post on this thread if you haven't already: http://www.edenxi.com/forums/viewtopic.php?f=3&t=523
