### ISSUE TITLE
Current and Completed quests erased

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#707]
My current and completed quest progress is completely erased. Between when I last checked and now the only actions I've done are zone into windurst waters, attempt to advance the Aspir quest, zone into my mog house and change jobs to black mage and then zone out into windurst waters again. I checked my quest status as I zoning back into windurst waters while  my data was still loading, maybe that was the problem?

**Comment by godmode** [comment]
You reported this in the correct place but for this specific issue please post on this thread if you haven't already: http://www.edenxi.com/forums/viewtopic.php?f=3&t=523
