### ISSUE TITLE
Carmine Dobsonflies spam spells with no cooldown

### ISSUE THREAD

**Issue by MB213** [EdenServer/community#708]
I don't think this is correct behaviour. 

![mihki_2019 01 09_115505](https://user-images.githubusercontent.com/37488914/50869082-b628d780-1406-11e9-847b-4a1ff846abe2.png)
![mihki_2019 01 09_115508](https://user-images.githubusercontent.com/37488914/50869087-bde87c00-1406-11e9-80a5-6584d8ffc07a.png)
![mihki_2019 01 09_115510](https://user-images.githubusercontent.com/37488914/50869095-c2149980-1406-11e9-8923-8a61a8ba9449.png)

**Comment by Aneyus** [comment]
Here's a video for reference for their proper behavior:
https://www.youtube.com/watch?v=k_cLz1C1Ay8

**Comment by KnowOne134** [comment]
issue seems to be resolved

**Comment by E5una** [comment]
For what it’s worth Knowone, this happens when they acquire a new target. Note that each slam is on a different target (presumably they are killing the target each time in these screenshots).
