### ISSUE TITLE
Seiryu Angel Skin

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#710]
The droprate for angel skin on Seiryu is set to 0 on DSP. I did a little research since FFXIclopedia shows it as a drop but not FFXIDB nor BG-Wiki. It did seem to in fact drop, but was very rare. It was probably around a 5% drop rate, maybe less. 

The 2 end-game LSes on the server have been doing Sky for around a year and a half now. I'd like to suggest a little compensation and have sent tells to both LS's leaders to chime in on perhaps coming up with an estimate of how many Seiryus have died in the past 1.5 years, in an effort to help staff decide whether to compensate and how much to.

**Comment by tectal831** [comment]
Please validate drop rates, regarding compensation, that belongs on forums. Personally, as long as the drop rate is validated and corrected if need be, that is good enough for me. If you would like to discuss that further, please make a forums post

**Comment by godmode** [comment]
This was brought up before. Without substantial proof of a drop from retail we won't be adding this to the loot pool.

**Comment by rujind** [comment]
https://www.bluegartr.com/threads/30808-What-else-drops-Angel-Skin
https://www.bluegartr.com/threads/37773-Angel-skins
I thought I had a 3rd thread about it, but can't find it.
