### ISSUE TITLE
Neckchopper Orcs in Ghelsba Outpost spam Drain

### ISSUE THREAD

**Issue by mpinholster** [EdenServer/community#716]
I fought an Orcish Nekchopper in Ghelsba Outpost and it casted Drain 3 times in a ~60 second time spam.
Drain should have a 60 second recast.

**Comment by mpinholster** [comment]
![image](https://user-images.githubusercontent.com/25998004/50881216-30714180-139e-11e9-80c8-cfa9c3b6bde8.png)
![image](https://user-images.githubusercontent.com/25998004/50881235-3ff08a80-139e-11e9-97ea-c46a3d2dc3f4.png)

**Comment by KnowOne134** [comment]
unable to reproduce, is the problem more that it cast back to back of 1 spell? or that mobs seem to be able to bypass recast timers? if its the latter needs a different error report and verification that in retial its not possible
