### ISSUE TITLE
Flyers for Regine Bugged

### ISSUE THREAD

**Issue by Godlyhax** [EdenServer/community#718]
So i picked up the quest from Port sandy magic shop from Regine.

Everything was working fine, handed the flyers out in Port and North sandy, all worked. Zoned into South Sandy and thats when it stopped working.

Wouldn't let me hand a flyer to any of the NPCs that were on the quests. So i checked my quest log and noticed it wasn't in my current quest log, went to my completed and all of my completed quests have gone!

And they have actually gone as well as its letting me repeat quests that aren't supposed to be repeatable.

**Comment by rujind** [comment]
http://www.edenxi.com/forums/viewtopic.php?f=3&t=523
