### ISSUE TITLE
TP reset to 0 after level up

### ISSUE THREAD

**Issue by Shaghy** [EdenServer/community#719]
I was solo, around lvl 8 or 9. Did not zone.

**Comment by Setz0r** [comment]
Are you sure you didn't miss your previous weapon skill right before leveling?

**Comment by Shaghy** [comment]
I'm pretty sure. I was saving it, mob died, I dinged, then I wanted to use
it on the next mob and I had 0 tp.

**Comment by Setz0r** [comment]
can't reproduce.
