### ISSUE TITLE
Girtablulu only using Sharp Strike

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#72]
Fought him earlier while unlocking savage blade and all he used was sharp strike. He should have access to all the normal scorption-mob TP moves.

http://ffxiclopedia.wikia.com/wiki/Girtablulu
http://ffxiclopedia.wikia.com/wiki/Scorpion_(MON)

**Comment by godmode** [comment]
This should be fixed. Please let me know if you see it again.
