### ISSUE TITLE
Inner Horutoto mob pathing issue

### ISSUE THREAD

**Issue by Nyoomy** [EdenServer/community#720]
This possibly happens elsewhere too, but mobs from deeper in the Inner Horutoto Ruins hang at corners trying to path back to their original spawn locations, possibly due to not understanding the concept of invisible doors. 
![image](https://user-images.githubusercontent.com/45608627/50935045-9b844c00-1462-11e9-8417-1262a06594c6.png)
These skeletons have been here for over 10 minutes just standing here

**Comment by Novadragon-Siren** [comment]
Seen plenty in Gusgen Mines to.

**Comment by InoUno** [comment]
Resolved with May 31st, 2021 update.
