### ISSUE TITLE
Chariot band

### ISSUE THREAD

**Issue by Jowy68** [EdenServer/community#723]
Bought Chariot Band in Windurst Woods, zoned out to east sarutabaruta popped my ring, said it had 1 hour left (instead of 720 minutes) I got about 1-1.5k exp total (so less than 10k bonus exp) and it simply expired after 10 minutes.

**Comment by Altnob** [comment]
10k exp bonus isn't accurate. i believe chariot is bonus 1.5k originally in 2007 maybe 2k but def not 10k. it's a text bug.

**Comment by panfunk** [comment]
The tooltip of Chariot/Empress/Emperor bands show current retail values. 
This server however uses Era values which are: 500/1000/200 xp bonus at 75%/50%/50% rate. buff lasting ~3hrs

**Comment by MGramolini** [comment]
Panfunk's values are accurate.

Requires DAT edits to properly display values in game.
