### ISSUE TITLE
Orcs in Ghelsba Outpost, Fort Ghelsba and Yughott Grotto appear to be on a 5 min respawn

### ISSUE THREAD

**Issue by mpinholster** [EdenServer/community#724]

**Comment by mpinholster** [comment]
Orcs in Ghelsba Outpost, Fort Ghelsba and Yughott Grotto appear to be on a 5 min respawn.
On retail, it was a 15 or 16 min respawn for all monsters in dungeons.
This makes it very hard to farm experience points in these areas.
I can check the other lowbie beastmen strongholds later.

**Comment by 59blargedy** [comment]
resolved in november 23rd update
