### ISSUE TITLE
Mission log and Completed missions gone while finishing 2-3 Bastok, yet retain finishing KI after a DC finishing the mission.

### ISSUE THREAD

**Issue by jackalstink** [EdenServer/community#725]
After Finishing off The Black Dragon for Mission 2-3 (Bastok), I received the KI  (Kindred Report) from melek at the consulate of Bastok in Windurst.  At this point I still had "The Emissary" in my current mission log and my completed missions were showing.  The Last step was to return to the metal works and bring the KI (Kindred Report) to Naji to finish 2-3 and receive rank 3.  I warped back to the Bastok Mines using a warp scroll.  I then ran into my moghouse so i could re-exit to the Bastok Markets residential area since i have done the quest to be able to exit to any residential area in bastok.  I headed straight into the Metalworks.  While in the Metalworks heading to Naji I got Disconnected.  Upon re-logging back in, I no longer had any mission active nor did it show I had any completed missions for bastok.  I do however still have the final KI (Kindred Report) to give to Naji.  Unfortunately since no mission is showing (The Emissary) Naji does not acknowledge im even on a mission so I can not finish mission 2-3.  Note that between the moghouse entering and exiting and entering the metalworks, I did not check to see if the missions log and completed missions were affected already before getting disconnected in the metalworks.  So all I have is the KI (Kindred Report) and the title of "Black Dragon Slayer"

My Character's name in game is "Caska"

*** Similiar Issue from another Player I saw ***

[18:16:37] [1]<Jimmayus> uh
[18:16:41] [1]<Jimmayus> when I zoned out of my mog house
[18:16:49] [1]<Jimmayus> I no longer have any current or completed quests listed
[18:16:58] [1]<Zajin> rip
[18:16:59] [1]<Chronogears> whoa
[18:17:25] [1]<Zajin> sounds like u broke something else
[18:17:47] [1]<Chronogears> between that and the key items, it scares the hell outta me, might log until they figure it out

**Comment by godmode** [comment]
If this is still an issue please report it on this thread. https://www.edenxi.com/forums/viewtopic.php?f=3&t=586
