### ISSUE TITLE
Nidhogg post-merge

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#726]
-Breath doing 0 damage after shell/phalanx/Hrotti;
-Wing damage is high (700~800) after shell;
-TP usage seemed low until 30%.

To note: if wing damage is a function of TP% it would explain why the damage was higher because of less TP usage. Initial wing when we first started fighting didn't break stoneskins.

**Comment by Elysien** [comment]
Nuke damage in wing mode also seemed too good; may just be eyeballing, but outside of MB's they should more or less have a floored land rate

**Comment by godmode** [comment]
@Elysien let me know after this next patch goes live how his damage taken is during wing mode please.
