### ISSUE TITLE
Crab monster stoneskin is {Too weak}

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#73]
I've noticed from King Arthro and crabs in kuftal that their stoneskin isn't absorbing much, if any, damage at all. Edit: This is from the metallic body TP-move.

**Comment by roriffxi** [comment]
I'm fighting Steelshells at the top of the boyahda tree and one melee attack from a thief is breaking it.  So roughly 20 hp on these stoneskins.
