### ISSUE TITLE
CN Exoray has been reverted back to Olid Funguar drops

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#730]
Think this is a post levelincrease change.

**Comment by Aneyus** [comment]
This is correct, here is the page for King Truffle in 2007 for reference. https://ffxiclopedia.fandom.com/wiki/King_Truffle?oldid=396824

**Comment by rujind** [comment]
Actually after a discussion, we EXPed on these earlier today and I just realized that these mobs never dropped an exoray mold. They've clearly been retuned back to their post era drops.
