### ISSUE TITLE
Tres Duendes summoning his fomor pet multiple times

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#731]
https://ffxiclopedia.fandom.com/wiki/Tres_Duendes

I just killed Tres Duendes but the fight was significantly harder than it should have been because he resummoned his pet after it was killed (supposed to be able to kill the fomor and then it won't resummon).

**Comment by Serephim** [comment]
Confirmed, he is still doing this.

**Comment by Volkaru** [comment]
This is an issue with almost all BST and PUP mobs/NMs. They can summon their pet multiple times when they shouldn't be able to.

**Comment by KnowOne134** [comment]
needs pet status removed and just spawn his pet and follow in script

**Comment by KnowOne134** [comment]
Corrected 11/2

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
