### ISSUE TITLE
BRD quest

### ISSUE THREAD

**Issue by Xenith-the-Red** [EdenServer/community#733]
Talked to Metairie > Bki Tbujhja as 37WHM.  After that, I tried to click/parchment-trade with Bubu runes.

I got neither a CS nor Poetic Parchment item.

**Comment by Xenith-the-Red** [comment]
-edit-
Talked to the nearby Elvaan "Mataligeat" (supposed to be totally unrelated to quest), then tried talking to the "required" NPCs in the prescribed order... still nothing (and tried this entire order a few times).


BUUUUUT when I talked to Mataligeat followed immediately by Bki Tbujhja... I finally got the "Hey you should become a Bard" dialogue.

**Comment by Aneyus** [comment]
Seems difficult to diagnose this as well since the quest's status options seem to only be AVAILABLE and COMPLETED as it's hidden.

**Comment by godmode** [comment]
Thanks for the information. I'm going to close this for now but we can reference it if the issue pops up for others.
