### ISSUE TITLE
Padfoot, Upyri, Tres Duendes (and probably all other CoP NMs) repopping after crash instead of persisting ToD through it.

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#736]
Title says it all.

**Comment by roriffxi** [comment]
I just killed Odqan at 9am game time with lightning weather going.

I didn't see it pop (was just idled there overnight to catch ToD) and it was up and standing next to me when I got on.

I'm wondering if maybe it went from foggy to lightning weather and skipped "clear" or w/e and so the event to despawn it didn't trigger.

**Comment by roriffxi** [comment]
Upyri is still not persisting its ToD through crashes and is instead respawning on crash.

**Comment by CurzonEden** [comment]
Upyri is still re popping after server crashes.

**Comment by setsuk0** [comment]
Not sure if this was ever fixed but can confirm that after the past 2 maintenances, Padfoot tod did not persist.

**Comment by ThoseWhoFight** [comment]
Carmine Dobsonflies, and the other riverne NMs too I'm pretty sure.
