### ISSUE TITLE
Blackout when I zone

### ISSUE THREAD

**Issue by Mase111** [EdenServer/community#737]
This seems to happen 25% of the time when I zone (see pic below).. only PC/NPC's load and I can't move other than in circles. Logging out and in doesn't fix, I have to shutdown and load from fresh:

https://imgur.com/a/VJgp49K

**Comment by Strumerjohn** [comment]
Are you using HD Zone packs or anything? Happens to me sometimes in Gustaberg lol. Can always tell this is about to happen when it loads the zone instantly instead of taking 5 minutes

**Comment by Mase111** [comment]
Yeah I am, best to remove them?

**Comment by Strumerjohn** [comment]
If it happens often I would. If you can put up with it and enjoy the HD zones though, keep 'em. Entirely up to you.

**Comment by Setz0r** [comment]
As this is unrelated to the server, there's nothing to be done.  Closing.
