### ISSUE TITLE
Exp loss with a PL taking aggro

### ISSUE THREAD

**Issue by LokiStinkpalm** [EdenServer/community#74]
In two different exp camp locations when our PL would take threat then the exp went from 315 to 0-9 exp.  And no the PL didnt have any kind of spikes or damage the mob in any way.  This needs attention asap

**Comment by jmcmorris** [comment]
I think this may have been caused from the patch tonight with blaze spikes. We have another patch in the works that should fix things up properly. If this still persists after the next patch then let us know. Thanks!
