### ISSUE TITLE
Cluster and Atomic Cluster spawning without fog (up 24/7)

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#740]
Edited to say this should only apply to Lufaise/Misareaux, not RiverneA/B.

**Comment by falisaxi** [comment]
Chiming in to say that this is still occurring. Atomic Clusters should only be up when it is foggy weather. Foggy weather should only be occurring when there is no other weather up. Screenshot attached of me standing in front of a cluster with windy weather occurring.

![Raine_2019 05 01_081533](https://user-images.githubusercontent.com/48370698/57024484-91d94c80-6be9-11e9-8beb-66d66d461720.png)

**Comment by DrfistMD** [comment]
Came to add that I was out during a thunder storm and Clusters were still spawning in this zone.
