### ISSUE TITLE
Mining Colored Rocks in Gusgen Mines issue

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#741]
Colored Rocks are supposed to match the element of the day when mining them, e.g. firesday = red rock.
Currently this mostly works fine except Watersday and Earthsday's yields are switched.

**Comment by MGramolini** [comment]
Checked wiki for both blue and yellow rocks and as far back as 2007, it says they can only be obtained on their respective days.  So this swap must be a DSP bug.

**Comment by Setz0r** [comment]
thanks Far :D
