### ISSUE TITLE
Norvallen supplys stuck in temp key items

### ISSUE THREAD

**Issue by eskimoslayer** [EdenServer/community#746]
I am able to use the warp. Just not able to obtain another set because of temp key item not disappearing and guard acting as I already delivered. Wife is having same issue. We are from sandy

**Comment by Kahrox** [comment]
I'm having the same issue, except mine is the Derfland supply temp item.  I was hoping it would go away after the conquest tally, but it hasn't.

**Comment by godmode** [comment]
Please call a GM using the website for these supply quests. They will be able to remove them fairly quickly.
