### ISSUE TITLE
Mobs slept by sleep bolt will occasionally turn to face you

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#748]
While they are asleep.   Like god damn.  Really annoying when trying to land a solo sneak attack.

**Comment by MGramolini** [comment]
This happens with any sleep action, had it happen today when duoing rdm + thf

**Comment by Setz0r** [comment]
which mobs... i've tried on a handful but can't reproduce this error.

**Comment by MGramolini** [comment]
quadavs for me

**Comment by MGramolini** [comment]
In beadeaux, downstairs on the way to qulun dome, before the room that looks like a plus sign, one of those 3.

**Comment by ThrisStraizo** [comment]
Now that you mention it, I mostly recall it only happening to beastmen.  I'm pretty sure I remember Orcs and Yagudo doing it.

**Comment by ThrisStraizo** [comment]
> edit: My thf also had 0 hate on the mob, which makes this even stranger.


Based on this I would venture a guess that it only happens if someone is in melee range of the mob.  The same behavior as if it was bound, but still turns to attack.

**Comment by rujind** [comment]
Are you sure someone didn't dia, bio, viper bite, wasp sting or use some other DoT on the mob?

**Comment by Setz0r** [comment]
If someone would like to demonstrate this happening in game, please send me a message on discord to arrange it.  On test server I cannot reproduce on any mob, beastman or not.

**Comment by HunnyDoo** [comment]
Couldnt get it to happen too much but it does definitely happen at 0:55

https://www.youtube.com/watch?v=WgQrAJu7unE&feature=youtu.be
