### ISSUE TITLE
Bard Quest - Mertaire does not take Poetic Parchment.

### ISSUE THREAD

**Issue by ukemipanda** [EdenServer/community#749]
When I try to trade the poetic parchment to mertaire.. he does nothing. It could be caused by the fact I talked to him before trading the quest item. (or buggy due to the fact it's a "hidden quest") Quest is called "The Old Monument"

**Comment by Setz0r** [comment]
The requires for the trade:
Trading parchment
Old Monument completed
Minstrel in Despair Available

**Comment by godmode** [comment]
From a GM ticket: Habanero, Jalapeno, Namiea, and Amura are all experiencing the bugged BRD quest as well. They don't get anything in Buburimu Peninsula when trading the parchment.

**Comment by Setz0r** [comment]
@godmode  this was fixed in the completequest update.
