### ISSUE TITLE
Possible issue with Bugard Tusk and H.Q. Bugard Skin drop rates?

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#75]
Over 40 reported kills on the Gigantobugards in Misareaux Coast from just one individual (Fate) and only NQ skins have dropped.

Shortly after switching to farm regular Bugards in Lufaise Meadows, a Bugard tusk dropped, so they definitely exist from the mob that is supposed to have a significantly lower drop rate. Could we get a review of Gigantobugard loot tables?

**Comment by roriffxi** [comment]
See my post in the drop rates thread to confirm that the drop rate at the very least is way too low

**Comment by roriffxi** [comment]
@godmode 

I was just killing Gigantobugards in Mis. Coast.  Absolutely nothing dropped with TH3 in approx 20 kills.

Something is definitely wrong with the drop rate.

**Comment by mlandrum22** [comment]
I think the HQ Skin drop rate is still too low on these, went 0 for 21 with TH4, I'm guessing it's set to 1% or 5% when it should be 10%. 

http://www.ffxidb.com/zones/25/gigantobugard
