### ISSUE TITLE
Cop Wyrm issues~

### ISSUE THREAD

**Issue by Elysien** [EdenServer/community#750]
Vrtra and Jormungund to my knowledge have not be seen, but are believed to have spawned and despawned already. Appears the persist after crash coded into their spawn code is only half working, or something. Their spawn timer doesn't seem to reset after a crash, but once they are actually spawned and a crash occurs, they will be despawned and, presumably, completely reset.

No other issues are known with the two aforementioned besides that, but where Tiamat is concerned there is word that:

-Tiamat possesses Regain (Tiamat, nor the other two Cop Wyrms, possess regain at all).
-Standard melee hits (non crit, above 25% hp) were hitting a RDM in -50% PDT+Phalanx for 500 to 550 (under the same conditions, this needs to dropped down to 250 to 300 to be retail accurate).
-Tebbad Wing is dealing 700 dmg per use with Shell V (MDT-25%), round about 500 under the same conditions would be accurate.
-Tiamat draws in everybody and apparently uses it exceeding merely 5-10 yalms. Should more or less be the same as King Behemoth's draw in; exceeding 40 yalms results in a single target draw in, but also has regional draw like most of HNM, preventing you from removing them from their general spawn area.

Nothing much else could be assessed from Tiamat, but here are some notes on things she should also have:

-15/tic HP regen.
-180 Base Delay (permanently dropped to 160 under 25%).
-Highly resistant to Paralyze, Sleep and Foe Lullaby (about 10% land rate or so outside of Elemental Seal in very good equipment)
-Highly resistant to Fire and Ice elemental magic, also passively possesses -50% MDT to all magical based attacks, and -50% reduction to physical ranged attacks.
-Susceptible quite reliably to; Slow, Elegy, Stun, Dispel, Magic Finale.
-15% Double Attack Rate.
-Uses Mighty Strikes every 2 minutes under 90% -- will not fly, or use a TP ability during mighty strikes.
-Will not use Mighty Strikes while in flight.
-Tiamat will fly every 2 minutes, and flight will last 2 minutes, but can be forced down before then upon taking a total of 10,000 damage during that instance of flight.
Touchdown, the ability wyrms use to come back to the ground counts as a TP ability; it's damage is based on the Wyrm's current TP, and thus consumes all their current TP upon use; does not require the Wyrm 1000+TP to execute. (damage is very low, 100~300 at most, 300 being the high end of a Wyrm having a lot of TP upon using.)
Under 25% Tiamat goes into a "rage" state that cannot be dispelled or removed upon regaining over 25% HP --- aforementioned; drops her base delay to 160, and gives her a 20% attack boost.

**Comment by Lilswitche** [comment]
I would also add Gravity as being quite reliable to land.
