### ISSUE TITLE
Bastok 9-1 Slimes HP too high.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#753]
The slimes for the Bastok 9-1 mission are supposed to have smaller HP pools as they split off.  They currently do not.  All of the slimes had the same massive HP pool as the original one, it took us almost an hour and a half to finish the fight due to this.  (We had 2 BLMs, a RDM, a WHM and a MNK)  We also had to kill ALL of the slimes, but in the wiki entries I saw you do not have to do that, you should only have to kill one of the "smallest" ones and the rest should despawn.

Here's a link to the wiki article on the fight.  

https://www.bg-wiki.com/bg/Bastok_Mission_9-1

**Comment by Volkaru** [comment]
Can agree there's lots of issues with this fight. It took us over an hour to kill them all. Slimes also don't despawn or attempt to move back to spawn point when everyone zones or dies. We had a trail of nano/micro slimes all the way from Taxim to the Valkurm entrance.

**Comment by Wiggo32** [comment]
here's a link to the retail fight for a 72 BLM and a party of trusts... 
https://youtu.be/YZKC5HkjhV0
does it seem comparable to what was experienced on eden or do you think we still need to make some changes?

**Comment by Volkaru** [comment]
@Wiggo32 I think you replied to the wrong bug report.
