### ISSUE TITLE
Stuck on The Crystal line Mission.  Cid won't take Faded Crystal.  Ref Ticket# 725

### ISSUE THREAD

**Issue by jackalstink** [EdenServer/community#756]
Stuck on The Crystal line Mission.  Cid won't take Faded Crystal.  Ref Ticket# 725

Now first of all I did this quest before, if you refer to my ticket #725 You can see that I got all the way to the end of mision 2-3  and all I had left to do was goto Naji in the Metalworks and trade him the key item (Kindred Report) to finsih 2-3 and get rank 3.  On my way back to Naji after going in and out of my moghouse ,  I no longer had The Bastok mission "The Emmisary" in my quest log and i no longer had any completed missions listed.  After 4 days with no info on it I decided to check out the Mission giver in bastok and mission 2-1  The Crystal line was listed in there again.  I flagged it to see if i could do it again real quick and get the emmisarry mission reflagged so I can give the KI i have to complete mission 2-3 to Naji.  He wont acknowledge me since the emmisary quest isnt flagged in the quest log.

Now i went and got a faded crystal again but cid wont take it when i trade it to him  nothing happens at all.   

Is there no way to force the emmisary back into my quest log so i can go give naji this KI i have to finish the mission?

and now with the crystal line  quest flagged again i can't switch nations which is what i was about to do because i'm just plain stuck on the end of mission 2-3.  I have the last KI and the title Black Dragon slayer.

**Comment by gweivyth** [comment]
This sounds like an issue that was addressed in last week's patch. There is a post on the forums you should post in regarding missing key items and quests, Godmode will probably have to intervene manually as he was with the other people on that post. 

Here's a link.

http://www.classicffxi.com/forums/viewtopic.php?f=3&t=586&sid=4e38d4dfad62a4de05424ef104d1940c

**Comment by bkesecker** [comment]
Please place a GM call if this is not yet resolved.
