### ISSUE TITLE
Various Coffer Bugs

### ISSUE THREAD

**Issue by HunnyDoo** [EdenServer/community#757]
A lot has been odd with coffers lately

It sometimes takes 5-6 tries to open even if you aren't lock picking and are using a real key. Message will say its successfully opened each time

The message of what was in the coffer doesn't pop up for like 10 seconds

Gil is shared between party members and items are going into treasury (edit: ignore this one)

Gil from coffers is becoming super rare in some locations. Physical Earrings is like 90%+ drop at monastic caverns now when gil used to be the most common prize (anecdote, can't prove this one).

A mimic I spawned in Boyahda Tree yesterday is still alive.

**Comment by rujind** [comment]
> Gil is shared between party members and items are going into treasury

This is supposed to happen. It's just never worked on private servers until now.

**Comment by HunnyDoo** [comment]
Ah thanks, scratch that one. It was by far the least important thing on the list by a mile anyway.

**Comment by gweivyth** [comment]
From what I recall, all of this is normal except the long delay on opening and the Mimic never unspawning.

**Comment by Eme-FFXI** [comment]
Just picked a coffer with Thief's Tools but it failed. I found a Moonstone on it anyway 10s after.
![capture](https://user-images.githubusercontent.com/44308523/51440361-9f1b9c80-1cc6-11e9-9fef-438c2742b38f.JPG)

**Comment by MGramolini** [comment]
The price of rare items like Mages Ballad 2 is down 50% in the past 2 weeks.  I think there might be some truth behind the items being more common than they should be.

**Comment by KnowOne134** [comment]
mimics now despawn, any other issues can re opened if still there
