### ISSUE TITLE
Nanban Kariginu

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#758]
This piece isn't listed in the pamama or wild pamama scripts and doesn't give additional stats with using said food. Unfortunately I think we'll need to acquire it on retail and use /checkparam to find the exact bonus values, as it seems different sites report different things.
https://ffxiclopedia.fandom.com/wiki/Nanban_Kariginu
https://www.bg-wiki.com/bg/Nanban_Kariginu
https://github.com/DarkstarProject/darkstar/blob/53455bdca3808cb1b1454e72d8a700ff717c1f6b/scripts/globals/items/bunch_of_pamamas.lua
https://github.com/DarkstarProject/darkstar/blob/53455bdca3808cb1b1454e72d8a700ff717c1f6b/scripts/globals/items/bunch_of_wild_pamamas.lua

**Comment by xizeta** [comment]
Obtained on retail and used /checkparam. With Pamamas received a flat +10 evasion and no bonus acccuracy. Same results with Wild Pamamas.
