### ISSUE TITLE
Singing while throwing darts

### ISSUE THREAD

**Issue by blacknesscrows** [EdenServer/community#759]
i was spamming darts for skillups and sootle started singing like a bard with no instruments.

sootle

**Comment by gweivyth** [comment]
This has only happened to me using lockstyle.  It also happens when using Gearlock.

**Comment by blacknesscrows** [comment]
I handed another player a few darts to see if he sang and he confirmed the dart made him sing too.

**Comment by rujind** [comment]
Config>Misc.>What's PC Armor Display set to?
Also BlinkMeNot is the Windower equivalent of gearlock in case you're using that.

**Comment by blacknesscrows** [comment]
set to normal

**Comment by ThrisStraizo** [comment]
I have pretty much everything at default and everyone sings when they throw darts.  Everyone.

**Comment by Setz0r** [comment]
good news, this is fixed in next update
