### ISSUE TITLE
Blighting Brand NM out of era 

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#76]
http://ffxiclopedia.wikia.com/wiki/Blighting_Brand 

WotG NM, spawns  at -189, 9, 164 Sauromague Champaign 

Cassandra's EarringRareExclusive
[Earrings] All Races
MP+5
Set: "Magic Atk. Bonus" +5
Magic Accuracy+5
Lv. 60 All Jobs

**Comment by godmode** [comment]
Thank you for the report. We will leave him in but the drop rate will be adjusted.
