### ISSUE TITLE
Prime Avatar BCNMs not always giving cutscenes

### ISSUE THREAD

**Issue by beerking27** [EdenServer/community#761]
While dual boxing the avatar prime BCNMS, I do not always get the win cutscene. Garuda i had to do twice. Titan no issue. Leviathan i did 4 times and was only able to get whisper on one toon. I did leviathan after updating to eden client. Screen will go black after a win and need to force d/c.

Toons ingame are Hex and Vex

**Comment by KnowOne134** [comment]
bcnm sysem has been reworked, reopen if issues still arrise
