### ISSUE TITLE
Cannot trade in guild point items after swapping guilds

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#762]
I switched from Goldsmithing to Leathercraft guilds today and just completed my guild turn-ins. I tried to trade them to the npc but the npc just doesn't react. When I talk to the npc normally he says I still have 2721 points available. If it matters the item for today is a leather ring.

**Comment by beerking27** [comment]
you may have to wait a day

**Comment by psyops78** [comment]
I'm having the same issue after switching from Cooking to Fishing as active guild. Has been maybe 5 days since i've switched. Cannot trade current item (Trilobite) for guild points.

**Comment by Jimmayus** [comment]
For what it's worth I could trade in guild points once I ranked up

**Comment by psyops78** [comment]
I ranked up today but still unable to.

**Comment by shaddix83** [comment]
I have switched to from cloth to leathercraft. It's been 3 jp midnights and the npc Alivatand will tell me what he is accepting but when I trade it, nothing happens. I did not rank up. He should be accepting the items. I switched to smithing and was able to turn in items just fine. I got my 10k GP and key item I needed. I switched back to leather (thinking maybe something bugged the 1st time) waited a jp midnight and crafted the items the npc above asked for. He does not accept them, gives me any dialouge...nothing happens at all. The Leather GP npc is not accepting my items and I cannot receive any leather Guild points (I've tried a total of 4 days [jp midnights and even a weekly tally] and this npc isn't giving me guild points at all

**Comment by bkesecker** [comment]
Linking
https://github.com/EdenServer/community/issues/1776

**Comment by Mozzy4Ever** [comment]
Those having this issue are likely being blocked by Flyers for Regine.

https://github.com/DarkstarProject/darkstar/blob/ee1f489efbdee2d95a4f1a6c842790da9f54306e/scripts/zones/Southern_San_dOria/npcs/Alivatand.lua

![image](https://user-images.githubusercontent.com/11255886/122625447-d266df00-d06a-11eb-90d4-fe61936b2a01.png)

Looks like if they have that quest accepted, it'll block the unionRepresentativeTrade function from firing.

**Comment by KnowOne134** [comment]
Corrected 6/11/2022 update
