### ISSUE TITLE
Citipati respawning very quickly

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#763]
This NM is spawning independently from it's placeholders. It's also respawning very quickly - about 5 minutes. This makes it possible to kill this NM more than one time per night, every night.

https://ffxiclopedia.fandom.com/wiki/Citipati

**Comment by gweivyth** [comment]
This must be a recent DSP merge bug, I have hours of VOD footage of me farming in his spawn area and not seeing this happen, but that was prior to the DSP merge.

**Comment by Aneyus** [comment]
In addition to this, Citipati seems to not be a lottery like he is supposed to be and just spawns at night.

**Comment by Far-The-Killer** [comment]
Current DSP issue is that his PH despawn after night is over which trigger his spawn. Then he also doesn't despawn at night.

**Comment by Far-The-Killer** [comment]
Fixed this in recent update

**Comment by Far-The-Killer** [comment]
Oops, this was a different issue than the PH. Will look into it.
