### ISSUE TITLE
Bomb toss (possibly maelstrom?) Not affecting outside party

### ISSUE THREAD

**Issue by kochiemonster** [EdenServer/community#765]
Just had bomb toss  and maelstroms go off on me and didn't affect character following me outside of my party in Labyrinth of onzozo

**Comment by godmode** [comment]
Were you healing outside or performed an action that would give your outside character hate on those mobs?

**Comment by kochiemonster** [comment]
No. Vix was on follow and for some of the tosses had used Hide and was invisible.  Stayed invisible, no damage no dodge or miss or no effect, mesage

**Comment by rujind** [comment]
I believe AOEs used to hit everyone regardless, but was changed on retail at some point. Not sure when (probably out of era). I'm sure DSP is using the latter.

**Comment by godmode** [comment]
I don’t believe all AoEs did. I think just certain monsters. For example Fafnir and Nidhogg wings used to hit everyone now only Nidhogg’s does. I could be wrong as well. Any patch notes or history would be welcomed.

**Comment by mpinholster** [comment]
AoEd most definitely effected people outside of a party.
It was a common way for BST to clear out an area.  They/we (I was a BST, but I never did this) would have that threat of making a bomb do Self-Destruct on top of a party...and it would be an automatic party wipe.
The most common place to do this was in Garliage Citadel basement.
It was also a way to cause people to wipe to Serket.

**Comment by godmode** [comment]
http://www.playonline.com/pcd/update/ff11us/2006041883vPh1/detail.html
