### ISSUE TITLE
"The Requiem" Bard AF Quest 

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#766]
NMs are not spawning. I just checked the tomb and got the key item without having to do the fight. :(

**Comment by godmode** [comment]
Duplicate of #224

**Comment by godmode** [comment]
Had you ever helped someone do this fight before Serephim?

**Comment by Serephim** [comment]
> Had you ever helped someone do this fight before Serephim?

I've done it before for Voretechz's Bard but that was on Kupo.
