### ISSUE TITLE
Guildpoints issue

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#767]
Went to the fishing guild. My lvl was 58 and it asked me to trade Tiger Cod.
I then traded a fish to rank up to Craftsman and the new item the npc asked for was Yellow Globe.

I did not trade any Tiger Cods previously before the rank up, and after ranking up, the npc will not accept any fish. Not the Yellow Globe that it is asking for and not Tiger Cod which was the daily fish for my previous rank.

**Comment by Nyoomy** [comment]
The fishing guild works like the other guilds, in that GP trade-ins are disabled until the next reset after a rank up, right?
