### ISSUE TITLE
Windurst gate guards not giving signet

### ISSUE THREAD

**Issue by Tacoxtuesday** [EdenServer/community#769]
Title says it all, Tried getting signet from embassy in bastok and anywhere in windurst with no luck.

**Comment by godmode** [comment]
Are you Windurstian?

**Comment by Tacoxtuesday** [comment]
Yes, Windurstian Rank 3. I logged out and back in. Seems to have fixed it.

**Comment by godmode** [comment]
I see. Without more information we can’t really debug it. If it happens again and you can provide more details please add on to this ticket.
