### ISSUE TITLE
Linkshell chat acting as though no linkshell equipped

### ISSUE THREAD

**Issue by beastffxi** [EdenServer/community#771]

**Comment by beastffxi** [comment]
also when you check the linkshell list on another character i do not show up

**Comment by rujind** [comment]
I've noticed that linkshell lists update at different times, not sure what those are. Also the actual linkshell list and /sea all linkshell shows different people.
Does this problem happen after equipping or unequipping a linkshell? I feel like I've had issues after unequipping one. I was seeing the dialogue for the other LS twice...

**Comment by KnowOne134** [comment]
All new ls code introduced months back
