### ISSUE TITLE
Windurst 2-1, Lost For Words

### ISSUE THREAD

**Issue by Valkyrie-ffxi** [EdenServer/community#773]
I followed the guides exactly, however, once I got through the Mahogany Door and returned to Windurst, I made it to the House of the Hero, clicked the doors and only got "The doors are firmly sealed shut." and nothing happens - I tried zoning and clicking, and then zoning and logging off and back on, zoning back into Windurst Walls, back to the house of the hero and nothing, just the doors being shut.

**Comment by marlinla** [comment]
I just did this mission on 2 characters and I got the the House of the Hero cutscene.

**Comment by jmf9808** [comment]
If you died during the cutscene with the Mahogany Door it doesn't register and you have to go back and do it again.

**Comment by marlinla** [comment]
@jmf9808 not true

Both my characters died in cutscene and eventually completed mission with zero backtracking

https://i.imgur.com/VhglfM4.jpg

**Comment by jmf9808** [comment]
Strange, that happened to me in December. I got the cutscene/died during it and when I went to the house of the hero it didn't trigger. Had to go back and do the cutscene again (this time without dying).

**Comment by godmode** [comment]
Was this issue resolved?
