### ISSUE TITLE
Quest "One Good Deed?" Not Triggering

### ISSUE THREAD

**Issue by Blex64** [EdenServer/community#775]
Can't seem to trigger the quest "One Good Deed?" for Attowah Chasm from Chipmy-Popmy at the Fishing Guild. I have requisite fame, and I don't see anything else listed on the Wiki that could conflict.

**Comment by gallanon** [comment]
Is there any update on this and/or an alternative way to get a map of Attohwa chasm on this server?

**Comment by bkesecker** [comment]
No in-era alternative.  Will have to wait until it is implemented.
Old ID: https://ffxiclopedia.fandom.com/wiki/Map_of_the_Attohwa_Chasm?oldid=270520
Eden Wiki: https://classicffxi.fandom.com/wiki/Map_of_the_Attohwa_Chasm?action=edit&redlink=1
