### ISSUE TITLE
Yinyang robe drop

### ISSUE THREAD

**Issue by zuultek** [EdenServer/community#777]
I was farming the robe with two characters, got first one on 3rd try. Then kept dboxing it and 18 times in a row no drop (chances are less than 1%). Then I tried to drop party on the character that already got the robe just before NM died and got the robe immediately. I suspect that one of the characters (who was also party leader) having this item was interfering with the drop somehow.

**Comment by panfunk** [comment]
https://github.com/EdenServer/community/issues/277

According to Dev, the droprate is fine. I personally went 3/20~ on Shikigami with th3

**Comment by ultimazero** [comment]
Currently 0/6 with TH1, seems like drop is supposed to be 25% but may be lower?
