### ISSUE TITLE
Stoneskin unavailable when Windurst is 1st

### ISSUE THREAD

**Issue by maeinit** [EdenServer/community#780]
Windurst is currently first in conquest and Scroll of Stoneskin is not being sold by Kosusu in Port Windurst. I am a citizen of Windurst on rank 5 and it still does not appear. 

It is sold to Windurst citizens only and only when Windurst is 1st in conquest.

https://ffxiclopedia.fandom.com/wiki/Kususu

( I have asked people fron San d'Oria if it was in their shop and they said it was not. In case it was forever stuck there like the circus is stuck in Port Bastok. )

**Comment by xizeta** [comment]
I have confirmed this is now working correctly.
Thanks for the report!
