### ISSUE TITLE
Unclaimed MOB HP

### ISSUE THREAD

**Issue by ZaksHouse** [EdenServer/community#782]
I am on BST, I notice if a pet comes unclaimed it don't always attack you just casually just goes back to where it belongs is that meant to happen? Also when you leave a pet or it does unclaimed it takes well over 10min for the MOB to regen its health I don't think thats right the Regen tick for unclaimed mob should be way higher I would think please inform me if I am wrong?

**Comment by Lexxi-foxxx** [comment]
The first part of this I noticed back in 2018 quite often. I haven't played on Eden for about 14 months but came back last week to see if any of the BST problems had been fixed (not a lot of love for BST I see ; ;)
I think I only had 1 pet uncharm mid fight and it attacked me. However, the second part is definitely broken and making leveling BST a massive headache. It's quicker to just let your pet die and wait the 5 minutes for a respawn than it is for one to regen to max hp. Duo'ing beetles vs dhalmels in altepa there would be 6 beetles roaming around with < 100% hp by the time we got to chain 4.

**Comment by mlandrum22** [comment]
#2171

similarly, pets should be regening HP outside of battle and Stay should be regening WAYYYY more.

**Comment by gweivyth** [comment]
Were the Stay changes not after 2007?  I don't remember that being a thing when I leveled my BST.

**Comment by mlandrum22** [comment]
It was an August 2007 change. 

http://www.playonline.com/pcd/update/ff11us/20070828oz52G1/detail.html

**Comment by Lexxi-foxxx** [comment]
I figured out last night that idle mobs regen 10% every time they move. Which for some mobs is more often than others. I feel like it used to be 10% after x number of seconds, probably 10 like /heal. I don't know where to look to prove it though...

**Comment by KnowOne134** [comment]
not an issue anymore
