### ISSUE TITLE
Chocobo in Xarcabard

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#784]
If you receive a teleport while on a chocobo, your chocobo goes to Xarc with you.

This...should not be a thing. 

http://i68.tinypic.com/j0zj95.jpg

**Comment by whiskeyhughes** [comment]
I confirmed this yesterday as well, the chocobo follows you into any teleport.

**Comment by godmode** [comment]
Dev who picks this up: most likely it is the zonemisc column including choco flag

**Comment by godmode** [comment]
Very clever! Thanks for contributing. What is likely the issue—I haven’t looked yet—is that it is missing this flag in its zone setting. If that’s the case; it’s just adding this number (in decimal) to that zones misc column in the db. 
https://github.com/DarkstarProject/darkstar/blob/09b3ddfe5f24190203a2ceb225c479bcc699d045/src/map/zone.h#L430

**Comment by jmf9808** [comment]
Thanks! I looked at the zonemisc and I may be wrong, but that seems like it's for area's that shouldn't be allowed to have chocobos at all. However, you can currently teleport to any of the other crags with chocobo not just vahzl.

**Comment by godmode** [comment]
That’s true. I wonder if that behavior is on retail. @Wiggo32 wanna try? 💃

**Comment by godmode** [comment]
For now I'm just going to make it so you can't use it in wrong areas. If someone on retail can prove that they can't keep their choco after teleporting to a valid choco zone that would be great!

**Comment by Wiggo32** [comment]
just finished teleporting with setzor on retail. 

found: being mounted on a chocobo makes you ineligible for any teleporting to any area whatsoever. what happens is the people who are not mounted will disappear and the people who are mounted will simply just stand in their position unaffected.
