### ISSUE TITLE
TP Gain for Hand-to-Hand

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#785]
TP gain for Hand-to-Hand is wrong. It is also wrong for H2H WSes (per https://github.com/EdenServer/community/issues/214)
I've done a lot of testing and have had Meloetta test on retail to confirm.
H2H is supposed to be treated the same as Dual Wield in TP gain and WS situations. On DSP it's treated the same on neither. Per the issue linked above, TP gain from hitting with the offhand during a WS isn't being applied to H2H. When dual wielding or using H2H, you should get TP from both weapon swings when using a WS. For example if you get 50 TP per swing, then as long as the main WS hit lands as well as your offhand/second fist, you should always get at least 100 TP regardless of how many hits the WS is. Each hit afterwards only gives 10 extra TP. So if a H2H user was getting 50 TP per hit and landed all 3 hits of a Combo, they'd get 110 TP back (for the record, Combo is assumed to only be 1 extra hit, since all H2H tooltips have been changed to say every WS is two hits. I assume this is due to H2H being unable to ever be 1 hit due to permanent "dual wield." Raging Fists is only 3 extra hits and Asuran Fists is only 6 extra hits).
Next, moving on to the issue of H2H auto attack TP gain. For Dual Wield, both weapon's delays are added together, then -delay from the dual wield trait is applied, then divided by 2. H2H should basically be the same, but on DSP never gets divided by 2. Presently, a naked level 75 MNK should get 55 TP per fist. Per this formula (https://www.bg-wiki.com/bg/Tactical_Points):
61+[(Delay-180)×63÷360]
A naked 75 MNK has 300 delay. It should be divided by 2 to get delay per fist, which is 150. So replace "delay" in the formula with 150. 
150-180=-30
-30x63=-1890
-1890/360=-5.25
-5.25+61=55.75
As per the wiki page, that value is then floored, so a naked 75 MNK should get 55 TP per fist - however currently, only 45 TP is gained because the H2H delay isn't divided by 2, and is using the 181-540 delay formula. For example, once again naked 75 MNK delay is 300, and the 181-540 formula is:
 61+[(Delay-180)×88÷360]
300-180=120
120x88=10560
10560/360=29.33333~
29.33333~+61=90.33333~
Floored=90. Since we didn't divide by 2 before, we're getting the TP gain for both fists. If we divide by 2 NOW, we're getting 45. So currently on DSP, a naked 75 MNK is getting 45 TP per fist, when it should be getting 55.

On DSP, MNK is not only being screwed from WS TP returns, but all TP gain in general.

**Comment by gweivyth** [comment]
I demand reparations.

**Comment by MGramolini** [comment]
This is why we don't invite monks.

**Comment by Setz0r** [comment]
looks like something fun for me to work on.  would any of you expert monks wanna take some time to work with me over a live stream to get it right just like i did for ranged delay/tp ?

**Comment by gweivyth** [comment]
> looks like something fun for me to work on. would any of you expert monks wanna take some time to work with me over a live stream to get it right just like i did for ranged delay/tp ?

You know I'm always down my dude.  I already have 75 MNK on Eden live.  I can suit up on your test server too if you want.

**Comment by gweivyth** [comment]
@Setz0r If you want some footage to go over until I'm around later tonight, I posted some videos in ticket #622  of me MNK/WAR'ing stuff.

**Comment by Setz0r** [comment]
@gweivyth i'm talking about doing an interactive dev situation where i change, we test, i change we test, repeat until working correctly.
