### ISSUE TITLE
Astral Ring + Safeguard Ring Castle O.

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#786]
I have not tested drop rates of these items, but Astral Ring was replaced by Safeguard Ring (lvl10 +2 def).  I believe the drop rate of the ring slot of the coffer to be 26-27% per https://ffxiclopedia.fandom.com/wiki/Castle_Oztroja .

Since nobody really wants the Safeguard Ring.. i suggest we either remove it or make the drop rates of rings be  3|24 6|21 or 9|18 .   Preferably the lower end for the Safeguard Ring.  Since this is the only way to obtain the Astral Ring..it would make sense to be a little closer to its Era drop rate for the coffer.

Per the discussion I had with @godmode , he suggested to lower the weight of the Safeguard Ring.

**Comment by godmode** [comment]
This looks like it may be a bit of an overhaul to refactor for this specific issue. For now I'm going to just leave the weight as it is. 50/50 chance once you get to the item selection part of the coffer.
