### ISSUE TITLE
Missions messed up:

### ISSUE THREAD

**Issue by whiskeyhughes** [EdenServer/community#788]
I accepted Windurst Mission 3-1 and noticed that it didn't give me a mission. I talked to the gateguard again and got the initial 1-1 cutscene and was forced to accept mission 1-1. My character's name is Tookosoko.

**Comment by godmode** [comment]
Please follow the first post at the attached link. There will be a patch on Monday to address this bug. https://www.edenxi.com/forums/viewtopic.php?f=3&t=586
