### ISSUE TITLE
Rain in Crawlers Nest:

### ISSUE THREAD

**Issue by whiskeyhughes** [EdenServer/community#789]
I am working on BLM AF2, and you need to kill a Water Elemental is Crawler's Nest to get seeds. I have been there for over 16 hours and have not seen rain. This seems bugged because rain should be common there.

**Comment by Jummel** [comment]
the frequency of the rain is based on time of year (in game). You can check to see the in game date by typing /clock.  raid is supposed to be very uncommon during the summer months.

**Comment by godmode** [comment]
This seems to be working as intended. Please comment if you feel the issue persists with some more information.
