### ISSUE TITLE
Stationary Bugbears are moving in Movapolos.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#79]
Bugbears in Oldton and Newton Movapolos that are in pairs of two are moving around when they are supposed to be stationary both facing the same way towards the tunnels close to them. This makes EXP camps in Movapolos very difficult.

**Comment by Wiggo32** [comment]
are all bugbears stationary or just some?

**Comment by Serephim** [comment]
> are all bugbears supposed to be stationary or just some?

Only some. The ones that are in pairs of 2 right outside of the tunnels. They should stand still beside each other facing the same way towards the tunnels.

**Comment by Wiggo32** [comment]
I found data on those... it's on the schedule to be implemented. (hopefully sooner than later)
