### ISSUE TITLE
2-3 Mission Bug

### ISSUE THREAD

**Issue by darthkado** [EdenServer/community#793]
Hello.  Just completed the first part of "The Emissary" Bastok 2-3 Mission and left Sandy for Windhurst after talking to Helaku and got the dialogue saying I needed to go to Windy.  I got to Windy and nothing.  I check my missions and my current and completed is empty.  Any assistance please. My character name is darthkado.  Thank you.
![2-3](https://user-images.githubusercontent.com/46846685/51429148-0f191c80-1c0c-11e9-8614-ecf6e1142bff.JPG)

**Comment by godmode** [comment]
If this is still an issue please request a GM ticket. We are currently looking into the issue but have enabled GMs to progress you through this mission if you meet the necessary requirements.
