### ISSUE TITLE
Altepa Gate

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#795]
Altepa Gate didn't open upon clicking all 4 columns, nor did the coloured columns appear at the Altepa gate as they should when 'clicked/activated'

We activated all columns withing ~30-40min but as of Aug/2007-Wiki there is no timer anyway.

**Comment by MGramolini** [comment]
The colored columns should be hidden if you clicked them all afaik.

**Comment by ThrisStraizo** [comment]
Can confirm this is an issue.  The gate didn't open for us after popping all 4 columns.

**Comment by Tank23** [comment]
Still an issue.

**Comment by Strumerjohn** [comment]
Still an issue

**Comment by godmode** [comment]
Please do not bump these unless they are closed. We know it's an issue if the ticket is still open.
