### ISSUE TITLE
Level Sync removes exp even when you're not in the same zone.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#798]
![image](https://user-images.githubusercontent.com/37130689/51432536-6a94db80-1c07-11e9-97da-929c4ae8a1ff.png)

I was not in the same zone as everyone else and yet I received no XP because they had level sync turned on.

**Comment by E5una** [comment]
Same as OP:

![SyncNoExp](https://user-images.githubusercontent.com/13668758/64036495-5318bc00-cb21-11e9-9abb-10216f4c9df9.PNG)

**Comment by GiichiHiro** [comment]
This still happens

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
