### ISSUE TITLE
Bootloader intercepted another account, created character on my account. Now it's the first character on my character list.

### ISSUE THREAD

**Issue by marlinla** [EdenServer/community#800]
The appeared to log into another account while I was logging into Poroburu:
https://i.imgur.com/WhkHVWt.jpg

I could not log into their account FFXI-3305. Good.

I created the following character to test if I could create a character on their account with an obvious name: http://www.edenxi.com/db/characters/33030/Bugreportlogin

Got FFXI-3305 again. Good.

Now after relogging the bootloader it's the first character in my character list. Incredibly annoying:
https://i.imgur.com/fTI8bOu.jpg

I know deleting is disabled. But I made the character to see if I could identify a bug. Is it possible to get a manual deletion? Or at the very least a rename so that it's at the bottom of the list below Poroburu.

**Comment by KnowOne134** [comment]
All new login server created. Should be rectified
