### ISSUE TITLE
windy 3-2 issue

### ISSUE THREAD

**Issue by Zaki1128** [EdenServer/community#802]
i log on, trying to do 4-1 with my friend. accidentaly grabbed the 3-2 i skipped. go to jeuno and try to grab 4-1, it doesnt work. i put in a ticket and a gm tells me that i have to do 3-2...

so i go to windy and zubaba will not speak to me to progress in 3-2

**Comment by Shoruto** [comment]
In your active missions does it show Windurst Mission 4-1 or 3-2?

**Comment by bkesecker** [comment]
Please put in a GM call if this is still an issue.
