### ISSUE TITLE
Windy missons gone.

### ISSUE THREAD

**Issue by Lohkie** [EdenServer/community#804]
So decided to go and do some windy missions to unlock airship eventually. was just into rank 3 when started with friend, did 3-1 no problems, skipped over 3-2 and picked up 3-3. Got the key item, Star Crested Summons, to go to Vestal Chamber door. Click on door and says that the doors is shut, zoned out and tried again with same message. Go into my missions list and 3-3 does not show up in my current missions and all my completed missions are gone. Thought maybe I just have to go talk to guard again and pick it back up but instead they give me the very first mission all over again 1-1, The Horutoto Ruins Experiment. PLEASE HELP. Thank you. 
-Lohkie

**Comment by godmode** [comment]
Please follow the first post at the attached link. There will be a patch on Monday to address this bug. https://www.edenxi.com/forums/viewtopic.php?f=3&t=586
