### ISSUE TITLE
CoP Wyrm issues v2

### ISSUE THREAD

**Issue by Elysien** [EdenServer/community#807]
If someone can remove the other reports on these Wyrms go ahead, making this to just get it all together in one report and add some Vrtra stuff.

**Jormungund:** 

_Current issues:_
-Possesses regain; None of the cop wyrm should possess regain at all. To boot it looks like it's regain is 250-300/tic or something utterly insane.
-Possesses Double Attack: of the three cop wyrms, only Tiamat should have the Double Attack trait.
-Hits way too hard for what would be expected of Jormungund: was hitting me for 200~250 damage per hit in -50% PDT, a strong phalanx, and Protect IV. This is the kind of damage I would expect from a functional pre-25% Tiamat--for Jorm to be accurate I would expect hits under the same conditions to deal 150 per hit.
-Glacial Breath dealt 1.200 damage to me positioned on it's paw, should be round about 300-400.

I lasted a whole 15 seconds or so against it, so I couldn't really get to see it's other issues. 

Here are what an accurate Jormungund should have:
-:80,000HP.
-:No regain.
-:No double attack.
-:30hp/tic regen.
-:180 Base ground delay (adjusted by slow effects).
-:250 Base air delay (unaffected by slow effects).
-:As with Tiamat, Jormungund's air attacks count as magical attacks and therefor do not generate TP for the wyrm.
-:Regular hits for round about 150 to a 75 RDM in -50% PDT, strong Phalanx, and Protect IV.
-:Should cast: Ice Spikes, Blizzaga III, Paralyga, and Bindga with a fair degree of Fast Cast.*
*Fast cast appears to be about 30% or so.
-:While Tiamat and Jormungund -can- be slept in the air, if they're slept whilst airborne the effect will wear off immediately regardless of accumulated resistance or elemental seal.
-:Highly resistant to Sleep and Lullably (10% land rate in excellent gear/merits outside of Elemental Seal).
-:Highly resistant to Paralyze of all sources (the white magic spell, and Fenrir's bloodpact ability).
-:Highly resistant to Bind, with the exception of Shadowbind.
-:Highly resistant to Silence.
-:Highly resistant to Ice and Wind elemental magic.
-:Reliably susceptible to most other elements, with Fire being it's most vulnerable.
-:Reliably susceptible to Slow, Elegy, Dispel, Magic Finale, Stun, Gravity(<this one would build heavy resistance quickly).
-:Under 30% HP, Jormungund enters it's "rage state" where if Horrid Roar is selected as it's TP ability, it will be able to perform this 2-3 times back-to-back.
-:All three CoP Wyrms possess the strongest form of Horrid Roar; Removes all buffs(food included), and completely resets generated VE/CE to 0.
-:Should have 1 minute of Ground time, followed by 30 seconds of Flight time.
-:Under 90% HP, it will use Blood Weapon every 2 minutes. Will not fly, or use a TP-ability, during Blood Weapon.
-:As with Tiamat, Touchdown should reset it's TP to 0. Does not require 1000 or more TP to execute Touchdown, but the damage of this ability varies based on the amount of TP the wyrm has at the time of use. (100~300 damage, 300 damage being very high TP).
-:Touchdown strips Blink and Utsusemi shadows.
-:Sleet Blast should deal around 700 damage to a Lv.75 with at least Shell IV.
-:Gregale Wing should deal around 500 damage to a Lv.75 with at least Shell IV.
-:Gregale Wing additional effect: Paralyze.
-:With correct positioning on the paw, Glacial Breath should deal 500 damage with at least Shell IV.
_**On an outgoing note,**_ I am honestly not sure what kind of damage Jormungund's air attacks should look like using only MDT-, as I never fought it that way in retail; if I had to guess I think 150-200 per shot would be within good guesswork with -50% MDT. I was also unable to get a look at how it's draw-in functions, but it should be similar to KB: unless you exceed 30 yalms of Jormungund or leave the general area in which it spawns (that valley area), you will not be drawn in, and the draw in was single target.

**Tiamat:**

_Current issues:_

-Tiamat possesses Regain, should not have regain.
-Standard melee hits (non crit, above 25% hp) were hitting a RDM in -50% PDT+Phalanx for 500 to 550 (under the same conditions, this needs to dropped down to 250 to 300 to be retail accurate).
-Tebbad Wing is dealing 700 dmg per use with Shell V (MDT-25%), round about 500 under the same conditions would be accurate.
-Tiamat draws in everybody and apparently uses it exceeding merely 5-10 yalms. Should be similar to King Behemoth's draw in; exceeding 30 yalms results in a single target draw in, but also has regional draw like most of HNM, preventing you from removing them from their general spawn area.

Here is what an accurate Tiamat should have:
-:120,000HP.
-:No regain.
-:15% Double Attack Rate.
-:15hp/tic regen.
-:180 Base ground delay (permanently dropped to 160 under 25%).
-:250 Base air delay (unaffected by slow, does not change under 25% health.)
-:As with Jormungund, Tiamat's air attacks count as magical attacks and therefor do not generate TP for the wyrm.
-:While Tiamat and Jormungund -can- be slept in the air, if they're slept whilst airborne the effect will wear off immediately regardless of accumulated resistance or elemental seal.
-:Should cast: Blaze Spikes, Firaga III.
-:Highly resistant to Sleep and Foe Lullaby (10% land rate outside of Elemental Seal in very good equipment)
-:Highly resistant to Paralyze from all sources (the white magic spell and Fenrir's bloodpact ability).
-:Highly resistant to Silence.
-:Highly resistant to bind, with the exception of Shadowbind.
-:Highly resistant to Fire and Ice elemental magic. 
-:Reliably susceptible to most other elements, with Water being it's most vulnerable.
-:Susceptible quite reliably to; Slow, Elegy, Stun, Dispel, Magic Finale, Gravity(<this one builds heavy resistance fast).
-:Possesses a Magic Damage Taken-50% passive trait that cannot be removed.
-:Possesses a Physical Ranged Damage Taken-50% passive trait that cannot be removed. 
-:Uses Mighty Strikes every 2 minutes under 90% -- will not fly, or use a TP ability during mighty strikes.
-:Will not use Mighty Strikes while in flight.
-:Should have 2 minutes of ground time, followed by minutes of flight time.
-:Tiamat can be forced to the ground if she receives a total of 10,000 damage during an instance of flight.
-:As with Jormungund, Touchdown should reset it's TP to 0. Does not require 1000 or more TP to execute Touchdown, but the damage of this ability varies based on the amount of TP the wyrm has at the time of use. (100~300 damage, 300 damage being very high TP).
-:Touchdown strips Blink and Utsusemi shadows.
-:All three CoP Wyrms possess the strongest form of Horrid Roar; Removes all buffs(food included), and completely resets generated VE/CE to 0.
-:Under 25% Tiamat goes into a "rage" state that cannot be dispelled or removed upon regaining over 25% HP --- aforementioned; permanently drops her base ground delay to 160, and gives her a 20% attack boost.
-:Fire Blast should deal 700 damage to a Lv.75 with at least Shell IV.
-:Tebbad Wing should deal 500 damage to a Lv.75 with at least Shell IV. 
-:Tebbad Wing additional effect: Plague.
-:With correct positioning on the paw, Fiery Breath should deal 500 damage with at least Shell IV.
-:Similar to KB; exceeding 30 yalms of Tiamat or attempting to leave the area of it's spawn will result in a single-target draw in. On retail, you could get it as far as the rock on the entering side, of just before the exit side leading to the Boneyard Gully area. 
-:Likewise with Jormungund, I've never fought Tiamat in pure magic reduction equipment only, but I expect Tiamat's and Jormungund's air attacks do not differ much in damage.

**Vrtra:**

_Current issues:_ has not been fought, issues are unknown.

Here is what an accurate Vrtra should have:
-:100,000HP.
-:No regain.
-:No double attack.
-:50hp/tic regen.
-:180 base delay.
-:Summons an Undead pet every 1 minute, 30 seconds.*
*there is no limit to the amount of times Vrtra can summon, but there is a limit of 6 (two of each pet) that can be spawned at once.
-:Summoned pets are round about as strong as the undead in Vrtra's spawn area, and also share hate with Vrtra.
-:Regular hits for round about 150 to a 75 RDM in -50% PDT, strong Phalanx, and Protect IV.
-:Should cast: Bio III, Dispelga, Blindga, Sleepga II.
-:Immune to Sleep and Lullaby.
-:Highly resistant to Bind, with the exception of Shadowbind.
-:Highly resistant to Silence.
-:Reliably susceptible to all elements except Dark-based attacks/magic, most vulnerable to Light.
-:Reliably susceptible to Slow, Elegy, Dispel, Magic Finale, Stun, Gravity(<this one builds heavy resistance quickly).
-:Uses Charm on the player at the top of the hate list every 2 minutes under 90%.
-:Charm effect can last upwards of 1 minute.
-:Like the other Wyrms, will not draw you in unless you exceed 30 yalms of it, or attempt to leave the room in which it spawns. Draw in is single target.
-:All three CoP Wyrms possess the strongest form of Horrid Roar; Removes all buffs(food included), and completely resets generated VE/CE to 0.
-:Cyclone Wing should deal 500 damage to a Lv.75 with at least Shell IV.
-:Cyclone Wing additional effect: Sleep.
-:With correct positioning on the paw, Sable Breath should deal 500 damage with at least Shell IV.

**Comment by Lilswitche** [comment]
A few notes to go with all of the above information:
-100,000 Max HP on all wyrms. [Source for Vrtra HP](https://images-ext-1.discordapp.net/external/H7EbXQ5Dx_YrFyY5oV_-Ofy_ah96422yRbqTecRJPaY/https/i.ytimg.com/vi/pbwivxFeuBE/maxresdefault.jpg);
-Watching any jormungand or vrtra video you'll notice they do infact NEVER double attack (won't provide video evidence, there's just too many videos); and
-Vrtra is susceptible to silence and paralyze. [Source](https://www.bluegartr.com/threads/46543-Vrtra-HP?p=1617956&viewfull=1#post1617956).

**Comment by tectal831** [comment]
everything ive seen for vrtra HP says he is roughly 40k hp, nowhere near the 100k mark.

https://ffxiclopedia.fandom.com/wiki/Vrtra?oldid=1671124

**Comment by Lilswitche** [comment]
I realize the wiki says 40k but that information isn't backed up anywhere else.  Every video or forum post I've seen points to 100k.

**Comment by Lilswitche** [comment]
Currenty, they are resisting Stuns pretty reliably.  The duration of stuns is normally subject to the skill level, but they shouldn't be outright resisting stuns.

**Comment by Falaras** [comment]
>  On an outgoing note, I am honestly not sure what kind of damage Jormungund's air attacks should look like using only MDT-, as I never fought it that way in retail; if I had to guess I think 150-200 per shot would be within good guesswork with -50% MDT. I was also unable to get a look at how it's draw-in functions, but it should be similar to KB: unless you exceed 30 yalms of Jormungund or leave the general area in which it spawns (that valley area), you will not be drawn in, and the draw in was single target.

So this is a really old report but I was bored and linked to KC's recent Jorm video. He's smacking their tanks around for 450 damage in the air unresisted but with Shell up. Seemed crazy to me so I decided to go see what it really should look like. Found two things: 

https://www.youtube.com/watch?v=xrjFhpPso18 
Twelve man Jorm from mid 2007s. The Paladins are not using bar-ice sets at all and honestly it looks like they aren't using any form of MDT and are just fulltiming random tanking gear like many Plds did back then. Highest hit I saw was 272, average seemed to be 210 or so. 

https://rukenshin.livejournal.com/11067.html#cutid3
Here's a sample from Rukenshin's livejournal of him using an uncapped MDT-% set and taking 236 damage a hit. He also mentions "normal" being 287 a hit and being able to get under 200 eventually. 

So it seems Jorm is hitting for nearly double what his max unresisted damage should be in the air.

**Comment by Falaras** [comment]
Fought the new changed Jorm. 
Air attacks are now doing era accurate damage, fully unresisted was hitting for 270.
Touchdown seems a lot better, usually didn't break full Stoneskin.
Sleet Blast seems too low, Wing might be too low as well.
Still can be paralyzed.
Still has absolutely insane defense, regain, and is highly resistant to magic.
Could not get any real Sleeps to stick, except the rare Nin/drk and Rdm/nin Sleep I in their rotation.

**Comment by Falaras** [comment]
Wing is once again doing way too much damage, 900+ through Stoneskin massacring all my Tarutaru mages. 
Still can be paralyzed.

**Comment by dowzer** [comment]
Here's a retail video of Tiamat

https://www.youtube.com/watch?v=Af5HH177lUk

I posted two time stamps in the description noting her ability to counter.
Aside from that, she's completely immune to Paralyze and Horrid Roar seems to completely reset enmity.

**Comment by Shoruto** [comment]
Adding this here as it applies for the breath attacks #2308

**Comment by 59blargedy** [comment]
The great majority of these issues were validated before fixing, then resolved if appropriate on december 7 update. 
however, i know that some issues exist. please continue to report issues, or open a new report if some of this is not resolved, it's just a lot to wade through with 98% of it solved.
