### ISSUE TITLE
Hide also has the effect of sneak applied

### ISSUE THREAD

**Issue by kochiemonster** [EdenServer/community#810]
With latest dsp pull hide now has sneak effect on it as well

**Comment by Novadragon-Siren** [comment]
Not exactly, doesn't work on Quadavs.

**Comment by kochiemonster** [comment]
It worked for me last night in palborough mines getting kazahm keys. Pulled an old quadav, had 2 others on me instantly,  used hide, lost all agro 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Novadragon-Siren <notifications@github.com> Date: 2019-01-23  3:04 PM  (GMT-08:00) To: EdenServer/community <community@noreply.github.com> Cc: kochiemonster <primetimedrywall@gmail.com>, Author <author@noreply.github.com> Subject: Re: [EdenServer/community] Hide have sneak effect (#810) 
Not exactly, doesn't work on Quadavs.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/EdenServer/community","title":"EdenServer/community","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/EdenServer/community"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Novadragon-Siren in #810: Not exactly, doesn't work on Quadavs."}],"action":{"name":"View Issue","url":"https://github.com/EdenServer/community/issues/810#issuecomment-457001230"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/EdenServer/community/issues/810#issuecomment-457001230",
"url": "https://github.com/EdenServer/community/issues/810#issuecomment-457001230",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AikoSachi** [comment]
Also I've noticed that even if you catch aggro from something with True Sight, You drop all enmity again.

**Comment by Volkaru** [comment]
Fixed in the December 30th patch.

**Comment by Volkaru** [comment]
Needs more testing.

**Comment by godmode** [comment]
I'm unsure how it worked on live. I tested live and local and I was able to reproduce this bug. Hiding from sneak detecting mobs as well as resting near by. They do not aggro. Please leave open for now ty.

**Comment by KnowOne134** [comment]
tested on sneak mobs, invis mobs, true sight mobs. true sound mobs and found no problems

**Comment by dowzer** [comment]
Hide isn't functioning correctly.

**Comment by Far-The-Killer** [comment]
Hide is confirmed to still be broken. Lots of data has been gathered on how it should work, someone just has to implement (i'll get around to it eventually)

**Comment by dowzer** [comment]
Aside from true sight and sound detecting mobs, it shouldn't work on most NMs. It would be easy to propose they follow detection per monster family. I don't think that's possible, others can be specific.

Here's a mixed bag from retail:

Fail vs. Suzaku
https://imgur.com/a/CJpb1wC

Success vs. Simurgh
https://imgur.com/a/mcfOqb1

Fail vs. Maat
https://imgur.com/a/DOxczLX

**Comment by Slamm21** [comment]
Suzaku likely TS where Simurgh is not.

**Comment by dowzer** [comment]
That’s true, yet on Eden it works on Suzaku and Maat.

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
