### ISSUE TITLE
Rumble Crawler (Crawler's Nest) drops missing

### ISSUE THREAD

**Issue by dantaface** [EdenServer/community#815]
[https://ffxiclopedia.fandom.com/wiki/Olid_Funguar](url)

Not supposed to drop Mold for LB1.

[https://ffxiclopedia.fandom.com/wiki/Rumble_Crawler](url)

No drops or almost nothing. Killed around 20 .. got 1 silk thread....

**Comment by xizeta** [comment]
The Rumble Crawlers in Crawler's Nest were found to have missing drops. This is being addressed.

I also investigated the Uggalepih drop rates as part of this ticket and they are working as era. Regarding the above comment in reference to the DSP sql, 4357 is the Crawler Egg ID and it has the correct drop rate. Silk thread ID is 816.

Thank you for your reports!
