### ISSUE TITLE
Windy 2-1 Lapis Coral KI not possible to get.

### ISSUE THREAD

**Issue by Snitchie** [EdenServer/community#821]
My character Snitch and LS friend Youda, can't get the Lapis Coral KI from Maze of Shakhrami. We have the KI Lapis Monocle, also have backtraced and talked with NPC in windurst woods. Checked all 5 (also the extra Fossil rocks in cave) in totalt of 8 times now. First time Sunday 20 Jan, then on Monday 21, and on login 22 Jan. Nothing to be found is the message. 

Had other LS mate needing it coming out to try with us yesterday (21 Jan), he got the KI Lapis Coral on 2nd Fossil Rock checked. So there is a bug on Snitch and Youda characters. Since no luck so far. Also used 12+ silent oils running all over the cave to check. So very frustrating.  We cannont complete rank 2, and also not possible to trad Yag Necklace to NPC in windurst woods until this mission is done. So please help with this..

Quote from Clopedia. 
"There are 5 Fossil Rocks to examine; one will give you the Lapis Coral."
This is supposed to be a 100% droprate on one of the 5.

**Comment by godmode** [comment]
What was the problem with this @Snitchie?

**Comment by Snitchie** [comment]
There was some code error he said, and that he would update in here. But guess he forgot.  Wiki says 6 places there can be a KI, but on Eden its 7 places. My KI was at the 7th...
