### ISSUE TITLE
Cursed in Beadeaux

### ISSUE THREAD

**Issue by Bringerofdeath56** [EdenServer/community#829]
Cursed in Beadeaux while walking up top.
![bringerofdeath_2019 01 22_210916](https://user-images.githubusercontent.com/46075859/51582643-2f560f00-1e8a-11e9-9c81-ac5f3635783d.png)

**Comment by RottenUnagi** [comment]
I experienced this as well last night in the same area pictured here @G-7/8 near the slime there. Also, the Afflictors are not giving the warning that "your skin feels cold" (I think that's the message?) when you start to get closer to its area of effect.

**Comment by E5una** [comment]
Also exists at L-6. 

![image](https://user-images.githubusercontent.com/13668758/154524203-9fbe02a6-17f5-4b23-a576-fbc63da3a111.png)

**Comment by KnowOne134** [comment]
I was gonna look into this soon and was thinking of adding a y check from npc, but in doing so will have to separate all npcs in the code by regions

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
