### ISSUE TITLE
Bo'Who Warmonger/Centurio XII-I, spawns after server resets.

### ISSUE THREAD

**Issue by Novadragon-Siren** [EdenServer/community#831]
https://ffxiclopedia.fandom.com/wiki/Bo%27Who_Warmonger

The NM Bo'Who Warmonger only spawns after server resets.

After encountering 1st: https://i.imgur.com/FPAunbt.jpg

I found him up.

This NM only persists to spawn once his window is up and will ONLY spawn after a server reset. This theory came forward from a 2nd kill since he only spawned after the server crashed (R0).

After the 3rd kill: https://i.imgur.com/Yzb7k7n.jpg

Again the 3rd only spawned after maintenance when his window was clearly done.

This NM is currently bugged only to spawn after server resets once his window has closed to a set spawn.

**Comment by Novadragon-Siren** [comment]
I'll investigate him more after a server crash to see if he respawns.

**Comment by rujind** [comment]
I'm pretty sure he spawns like he's supposed to, ~21 hours after death. However, his TOD isn't set to persist through crashes. So checking him 21 hours after death when there have been crashes is pointless. The crash causes his respawn time to reset, meaning he'll be up after a crash causing the old TOD to be useless.

**Comment by Novadragon-Siren** [comment]
Actually Bikini, twice the server crashed, he was standing right there, soon the server goes up.

**Comment by Novadragon-Siren** [comment]
There's no way twice in a row, he would instantly spawn soon Servers return.

**Comment by rujind** [comment]
Yes, any NM that isn't set to persist, will be up when the server comes back up after a crash. NMs that have PHs will also be popable.

**Comment by Novadragon-Siren** [comment]
Centurio XII-I

Found him up instantly after server crash/reset to.

**Comment by blacknesscrows** [comment]
Faust did this too couple days ago and thwarted me and a buddy's exp session

**Comment by godmode** [comment]
I'm going to leave him to spawn after a server reset for now. Please comment if it does not spawn after 21 hours and 15 minutes from last ToD without server reset.

**Comment by StriderClerix** [comment]
He currently spawns after each server reset.

**Comment by StriderClerix** [comment]
With today's multiple maintenance, he was killed 3 times.

**Comment by tectal831** [comment]
godmode 
commented 24 days ago

"I'm going to leave him to spawn after a server reset for now. Please comment if it does not spawn after 21 hours and 15 minutes from last ToD without server reset."
