### ISSUE TITLE
Ranguemont Pass has some super high level monsters

### ISSUE THREAD

**Issue by mpinholster** [EdenServer/community#836]
At the exit to the Glacier, there are Hovering Occulus that conned IT++ to me as a 32 THF.

I suppose they could be like level 38?  On Retail these are level 89.

On a different private server I played on, these were level 89 as well (I was level 75 and they were still IT++).

A level 40+ player could check this, or a GM.

If I am way off, I am sorry to report this.  Just trying to be helpful to the server that I have quickly grown to love!

EDIT: Nevermind, I think these are probably the same level as the "Bat Eye"
https://ffxiclopedia.fandom.com/wiki/Bat_Eye

If these are 42-44, then the name is just off, but the levels are accurate.

This seemed to be the case with the Hoodoo Goblins in that area.

**Comment by godmode** [comment]
Are you using an install with the Eden installer? It should have them renamed

**Comment by godmode** [comment]
Please comment on this ticket even though it’s closed.

**Comment by mpinholster** [comment]
I haven't updated the launcher since the Jan 21 update, but I have used the Eden installer/launcher.

**Comment by godmode** [comment]
Thanks, it should have been included in that so we will rename it for the next one.
