### ISSUE TITLE
SMN Pets no longer "defending" caster

### ISSUE THREAD

**Issue by maeinit** [EdenServer/community#837]
I noticed during BCNM about a hour or so ago that my carbuncle and ifrit would no longer go towards the monsters that were agro'd on me. Instead I had to manually re-Assault it every time. 

I just went outside to Sauromugue Champaign and had carbuncle hit a weapon. I then ran a good distance away and released Carbuncle and resummoned. Carbuncle stood there doing nothing, even long after the weapon was already back to me and hitting me. 

I am pretty sure that it was working fine before the server crashes today a few hours before that...

Edit: to note during the BCNM Tacotuesday and Winlogon was also there and their summons also did not do anything, causing us all to have to re-assault every time.

**Comment by Setz0r** [comment]
we recently updated the auto-attack for avatars to not auto attack claimed mobs if the summoner gets hate from the mob while someone else outside your party is fighting it. not sure how this would affect normal behavior, but will take a look. thanks for reporting.

**Comment by Xamba1** [comment]
I also had the same issue with avatars.  Avatars will no longer go after a mob that has been aggroed (when soloing) and they will not attack a mob (defend the summoner) if a mob is aggroed.  If I am soloing I have to re-assault every time the avatar dies (no more carby kiting) and if I get aggro from a mob I have to assault it as carby will not auto-attack it and save the day.
I was in a few different zones and noticed this.  Dungeons and outdoor areas.
