### ISSUE TITLE
Windurst Mission 3-2

### ISSUE THREAD

**Issue by pksweets** [EdenServer/community#838]
Went to Horutoto and got the cutscene at the Gate of Light with the cardians and Ajido-Marujido. Returned to Heavens' Tower to speak with Zubaba, but she just restated her original text. Checking my temporary key items, I still the charm of light even though it was supposed to "disappeared in a flash of light" according to in-game text.
![lekubugreportwindymission3_2](https://user-images.githubusercontent.com/27723566/51660764-a27f8400-1f63-11e9-9518-e7f1900dbe96.png)

**Comment by Novadragon-Siren** [comment]
Happened to me to, I'm in the exact same position as you.

**Comment by pksweets** [comment]
Now similarly, I traded a cathedral tapestry to Sobane for the quest Signed in Blood, then went to talk to Abelard, but he does not progress the quest. Checking my inventory I saw that, similar to last night, I still had the cathedral tapestry in my inventory.
![leku_2019 01 24_202930](https://user-images.githubusercontent.com/27723566/51725457-26467880-2017-11e9-93fd-647fb961ca21.png)

**Comment by godmode** [comment]
@pksweets Try talking to Zubaba again. Have you already finished the next mission?

**Comment by godmode** [comment]
For the characters Swankyjr, Sulfuricsixx, and Molecular you should be able to visit the Gate of Light to get it. Please follow the system message that pops up and contact me if it seems wrong.
