### ISSUE TITLE
Unable to flag quest "The Setting Sun" in San d'Oria

### ISSUE THREAD

**Issue by MysticLogos** [EdenServer/community#839]
I know someone else who was able to flag this quest, so I don't think it's a DSP problem.  I got the key from the NM and went to talk to this NPC, Vamorcote.  However, no matter what I do, I am unable to flag this quest.  The only thing I haven't tried is a complete reinstall.  I have rank 9 reputation, and the only dialog I get is about how there are both a Smithing and Carpenter guild in the city.

**Comment by Shoruto** [comment]
Try completing the previous quest in the series Blackmail, then zone and go back to Vamorcote to see if you can flag it.

**Comment by MysticLogos** [comment]
I completed the Blackmail quest months ago - just tried to talk to the NPC again and rezone, no luck flagging The Setting Sun with Vamorcote.  As an update, I have done a complete reinstall since I originally put in this ticket.

**Comment by Corvinus1337** [comment]
I'm having the same issue as MysticLogos. I have max Sandy fame and have completed the Blackmail quest already.

**Comment by DeliriumOnEden** [comment]
I'm unable to flag this quest. Blackmail is listed in my completed quests as well.

**Comment by KnowOne134** [comment]
So this quest by code says you can only flag it if you haven't completed blackmail. Which doesn't sound right. Any info to shed light why this quest is even mentioned for this one?

**Comment by tigo9** [comment]
I can also not flag it, good to know the reason though sounds like a low complexity fix.

I'd guess someone committed that following misinformation on the wiki
https://ffxiclopedia.fandom.com/wiki/The_Setting_Sun?action=history

**Comment by DeliriumOnEden** [comment]
According to ffxiclopedia the only requirement is rank 5.

https://ffxiclopedia.fandom.com/wiki/The_Setting_Sun

According to classicffxi.fandom the requirements are rank 5 and Blackmail
is listed as the previous quest in the quest chain.

https://classicffxi.fandom.com/wiki/The_Setting_Sun

BG also lists rank 5 and Blackmail as a previous quest.

https://www.bg-wiki.com/bg/The_Setting_Sun

**Comment by KnowOne134** [comment]
Thank you for the research, plan to have this fixed soon then

**Comment by KnowOne134** [comment]
Fixed in update 11/9
