### ISSUE TITLE
Bastok Mission 2-3 The Emissary

### ISSUE THREAD

**Issue by Sonic85** [EdenServer/community#843]
Character: Sonic
Server: Eden
Issue:
Quest log does not progress when speaking to Helaku after obtaining Warchief Wrecker title.

Speaking to Helaku with the title gives the correct dialogue and quest complete sound effect but does not progress the quest to allow me to speak to Melek in Windurst.
speaking to him again continues to give the same dialogue.
Did it 2x and talked to npc in Windy but nothing happen..Mission Log still in Sandy/kill Warchief progress

**Comment by godmode** [comment]
If this is still an issue please request a GM ticket. We are currently looking into the issue but have enabled GMs to progress you through this mission if you meet the necessary requirements.
