### ISSUE TITLE
Incorrect guild point value for barbarian's belt

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#844]
For reference: https://ffxiclopedia.fandom.com/wiki/Guildworker%27s_Union#Leathercraft

Era value is 606 guild points per turn-in. For one turn in I received 256. The total cap (3760) is correct, but the per-item value is incorrect.

**Comment by Shoruto** [comment]
On Wikia they start showing guild points for specific items on April 4th, 2012 and it shows 606 with 3760 cap.  It continues to show this number all the way to the latest update. This would be post era.  So far I have found no charts/lists showing what the number should be during era.

https://ffxiclopedia.fandom.com/wiki/Guildworker%27s_Union?oldid=1392834

**Comment by Setz0r** [comment]
https://ffxiclopedia.fandom.com/wiki/Barbarian%27s_Belt?oldid=190156

shows 506 for era. with 3160 cap.
