### ISSUE TITLE
San d'Ora mission 2-3 Journey Abroad.

### ISSUE THREAD

**Issue by AkumoBunni** [EdenServer/community#845]
After completing the Bastok leg of this mission(Which involed talking to the ambassador, Savae E Paleade, Speaking to Pius, Speaking with Grohm and obtaining the pickaxes, running out to Palborough Mines, mining up Mine Gravel, going to the refiner, trading the gravel, pulling the lever, dropping down, hitting the second lever and receiving the Mythril sand, returning to Bastok and trading the Mythril sand to Savae E Paleade.)  on Wednesday(Bastok > Windy), I was not able to get the Windurst NPC to give me the starting dialog to begin Windurst leg of the mission on Thursday. After visiting Windurst, I returned to Bastok and talked to NPCs in the mission order to see if I missed something. (Even tho I clearly remember trading the Mythril sand the day prior.) Requested GM assistance, GM Warden was able to fix whatever issue it was, and I was able to continue with the mission.

Mission link for reference: https://ffxiclopedia.fandom.com/wiki/Journey_Abroad?oldid=610274

**Comment by godmode** [comment]
If this is still an issue please request a GM ticket. We are currently looking into the issue but have enabled GMs to progress you through this mission if you meet the necessary requirements.
