### ISSUE TITLE
Bastok 2-3 The Emissary (Naji + Kindred Report)

### ISSUE THREAD

**Issue by reynierk** [EdenServer/community#847]
Have the Kindred Report in my possession and I'm talking to Naji but he only tells me to not go into the President's office, instead of completing my mission and making me rank 3

Thanks!
Character: Reynierk

**Comment by godmode** [comment]
If this is still an issue please request a GM ticket. We are currently looking into the issue but have enabled GMs to progress you through this mission if you meet the necessary requirements.
