### ISSUE TITLE
Bastok 2-3 The Emissary

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#849]
Did the windurst > Sandy leg. 
Dragon is defeated, spoke with the npc in sandy and got the kindred report. 
When I return to Naji in Bastok to complete the mission, nothing happens.

**Comment by godmode** [comment]
If this is still an issue please request a GM ticket. We are currently looking into the issue but have enabled GMs to progress you through this mission if you meet the necessary requirements.
