### ISSUE TITLE
Melampus Staff NPC Price

### ISSUE THREAD

**Issue by LokiStinkpalm** [EdenServer/community#85]
The Melampus Staff from Wake Warder Wanda is vendoring for 0 gil

![loki_2018 10 05_230002](https://user-images.githubusercontent.com/43826696/46567983-b343b580-c8f2-11e8-9870-6849f7e86ee8.png)

**Comment by roriffxi** [comment]
Wake warder Wanda herself is out of era, added in 2009

**Comment by godmode** [comment]
In the future if you see these things if you have a price you found and a link that helps a ton.
