### ISSUE TITLE
Bastok Mission 2-3

### ISSUE THREAD

**Issue by nfortyseven** [EdenServer/community#851]
I'm currently on Bastok Mission 2-3 and have chosen San d'Oria for the first leg of my journey.

When I try to speak to Helaku I get no response.  I've spoken to the rest of the NPCs in the consulate, and the Galka behind the desk tells me to proceed to Helaku, but then nothing.

Thanks,
Syntaxerror

**Comment by godmode** [comment]
If this is still an issue please request a GM ticket. We are currently looking into the issue but have enabled GMs to progress you through this mission if you meet the necessary requirements.
