### ISSUE TITLE
/assist woes

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#853]
/assist will target the assisted player's TARGET and not only mobs that they've ENGAGED

**Comment by Aneyus** [comment]
If I remember retail correctly, /assist would do nothing until the person being assisted had engaged.

**Comment by rujind** [comment]
No, it's supposed to work this way. It also works when a player has another player targeted and you /assist them. You'll target the same player they are, even if that player is themselves.

**Comment by Aneyus** [comment]
Guess it just feels extra terrible right now because of how bad Dynamis lag can be. Closing ticket and remaining hopeful for more packet optimization 😥

**Comment by godmode** [comment]
I remember it was engaged as well. Maybe I remembered wrong

**Comment by icariumkupo** [comment]
I also recall it was engaged. On retail, my dynamis LS had someone in the backline always engage the next mob we were to assist from afar. That would have not been necessary if we could have assisted just off their target.

**Comment by ThrisStraizo** [comment]
Was main assist for years, can confirm it's engaged.

**Comment by KnowOne134** [comment]
Fixed last patch
