### ISSUE TITLE
Bastok 2-3 Mission

### ISSUE THREAD

**Issue by darthkado** [EdenServer/community#855]
![2-3](https://user-images.githubusercontent.com/46846685/51789425-0c2ca780-2189-11e9-9886-062e89178025.JPG)
Character name: DarthKado

Just finish the Black Dragon at Balgas Dias and went to turn in Kindred report to Naji but not responding to complete Bastok 2-3 mission. Thank you.

**Comment by godmode** [comment]
Thanks for reporting. This is a known issue please call a GM for assistance on each branch of the mission.
