### ISSUE TITLE
An Explorer's Footsteps bugged

### ISSUE THREAD

**Issue by trollsc** [EdenServer/community#858]
I have completed all clay except the 2 10k ones that are not needed for map. I click on npc and tells me needs one in West  sarutabaruta. I go there and get clay again when I return to turn in will not take it.

**Comment by trollsc** [comment]
Thanks for getting fixed.

**Comment by godmode** [comment]
For my recollection later: his current tablet was set to 1024 (Sarutabaruta) but the mask was missing 4096 (tahrongi canyon). He was asked to redo the Sarutabaruta one

**Comment by comatose420** [comment]
This is happening to me as well. i was asked for batallia downs tablet but when i was doing thf af fight in north gustaberg  i got that tablet instead. i turned it in got 3kgil npc gave me new clay but asked me to then get clay from north gustaberg again. so i went and got it but now the npc wont take the tablet

**Comment by trollsc** [comment]
So new issue. I doing quest signed in blood. The mayor Abelard will not tell me next step. Keeps asking for clay. I went and got clay from area you said I not got but he not take it. How can I get next quest?

**Comment by godmode** [comment]
This will be fixed on the next patch. However characters that have already started it may be stuck. If this is the case **after the patch** place a GM ticket and I will progress you to where you should be.
