### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by DistantClose** [EdenServer/community#86]
Flying from Jeuno, loading into Port Sandoria led to Black Screen loading endlessly

Logged back in and am now on Airship again.

Airship led me back to Jeuno and another black screen

**Comment by MGramolini** [comment]
I have this same issue, flying between windurst to jeuno twice, jeuno to sandy, and also jeuno to kazham.

**Comment by roriffxi** [comment]
The boat between Mhaura / Selbina is currently having issues where you end up black screening a lot of the time and not actually being able to get to the other side.

Maybe a temp fix for this would be to make the Captain on the ship teleport you to the opposite side?  That way players can still get on the ship to fish and try to kill pirates (if the pirate encounter works here?), but players who are just traveling are able to get to their destination properly.

@godmode

**Comment by godmode** [comment]
Will make it like the others as a temp measure. Will have to carry a warp item with you for safe fishing

**Comment by Volkaru** [comment]
Currently having this issue with the Jeuno to Kazham Airship. Still lets us use menus, etc. So a few people were able to warp out. However neither me, nor my alt have any form or warp. I've tried restarting the client to ride the ship again three times now, and have gotten a black screen each time. Character names Volkaru and Aerun
