### ISSUE TITLE
Physical TP abilities from mobs and spell casting

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#861]
Physical TP abilities from mobs seem to not have a chance to interrupt spellcasting; specifically observed this in Utsusemi: Ichi multiple times.

**Comment by gweivyth** [comment]
This is working correctly.  Unless the ability has some kind of stun or displacement, they should not interrupt spell casting as long as they hit at least 1 shadow.  To elaborate, if you get hit by Claw Cyclone, it will deal damage and strip your remaining shadows, but will not interrupt you.  However, Goblin Rush will still interrupt you as it causes you to move. 

 Source: Played a cubic shitload of Ninja on retail during era.

**Comment by Wiggo32** [comment]
i think this person is referring to the fact that while casting Utsusemi in the process of obtaining shadows the mob physical tp moves do not interrupt. testing...

**Comment by ThrisStraizo** [comment]
Yeah I'm talking about if shadows are completely down.

**Comment by 59blargedy** [comment]
resolved december 7 update
