### ISSUE TITLE
SMN Avatars still steal claim

### ISSUE THREAD

**Issue by ultimazero** [EdenServer/community#863]
Summoner pets will still steal claim from people if the monster aggros. Read it was patched out but it still happens.

**Comment by roriffxi** [comment]
The patch for this was rolled back because it was preventing avatars from protecting their master normally, which is a huge hamper on gameplay.  For now please just do the right thing and transfer claim back (by joining their party, or warping) if a monsters claim is stolen by a pet.

**Comment by godmode** [comment]
Duplicate of #293
