### ISSUE TITLE
Beastmen mobs are not pooled, all spawn

### ISSUE THREAD

**Issue by mpinholster** [EdenServer/community#864]
It "feels" like there are too many Gigas in Qufim.

What I think may have happened with these Gigas (and some other monsters) is shared Spawns not being shared.

On FFXIClopedia it lists a large number of spawns for the 4 types of Gigas 13,17,17,13 (or 13,13,17,17)
https://ffxiclopedia.fandom.com/wiki/Qufim_Island

But some of those Gigas should share a spawn ID, but instead they have separate spawns.  This leads to there being roughly twice as many Gigas as there should be.  Goblins around Selbina is another noticeable "different feeling" area.

If you head to the right as you leave the tunnel headed out from Port Jeuno, it is most noticeable.

I might be 100% wrong, but I have asked a couple people in game and they expressed the same "feelings".

I am unsure how to check this though.

**Comment by Lilswitche** [comment]
This is absolutely what is happening.  DSP doesn't do split spawns for normal mobs.  It's quite noticeable in beastman strongholds - some areas are a complete clusterf*ck.

**Comment by godmode** [comment]
We are planning at some point to overhaul the mob system / storage. We will probably fix this issue at that point.

**Comment by mpinholster** [comment]
Oooh glad I am not going crazy lol.

**Comment by beauxq** [comment]
They could be treated exactly the same as a lottery spawn.
If X is a true lottery spawn with placeholder Y, with a 50% pop rate, then half the time it would be X and half the time it would be Y.

**Comment by godmode** [comment]
We could but instead of touching 100s of files for it we are just going to do it in the refactor.

**Comment by mpinholster** [comment]
> We could but instead of touching 100s of files for it we are just going to do it in the refactor.

Man, I can't imagine how much a PITA that'd be to change all that stuff.
I get mad when I have to re-write a few macros if I don't log out properly lol.
BTW I hope you guys don't view this bug reporting as my being ungrateful.
I am really enjoying playing on here and this feels like my Vana'Diel home.

**Comment by 59blargedy** [comment]
Resolved by another dev in February 20, 2023 update
