### ISSUE TITLE
Geyser Lizard NM geysers in Dangruf Wadi not erupting

### ISSUE THREAD

**Issue by Kurtalicious** [EdenServer/community#866]
Spent 3 hours in this zone at the geysers and never saw one eruption.  According to wiki these geysers erupt every 60 +/-15 minutes.  The Geyser Lizard NM spawns on when the geysers erupt.  It's broken.

**Comment by godmode** [comment]
I believe there is more to his spawning than that. Please check again and include a link if you find otherwise.

**Comment by Kurtalicious** [comment]
https://ffxiclopedia.fandom.com/wiki/Geyser_Lizard

**Comment by Kurtalicious** [comment]
http://ffxi.allakhazam.com/db/bestiary.html?fmob=102

**Comment by Kurtalicious** [comment]
Both of those links say that this NM spawns when the geysers erupt.  Like I said I was in the zone for 3 hours and the geysers never went off.

**Comment by godmode** [comment]
I thought I had mentioned it in my first comment but it looks like I didn’t. I believe the geyser animations do not work but the code is there. I will have to look but I’m fairly certain someone has seen this NM

**Comment by Kurtalicious** [comment]
I also know ppl who say they have seen this NM.  However, I spent 3 hours walking between the 3 different spawn areas and never saw him once.  I should have seen him at least 2-4 times, something does not seem right.  The lack of auction house sale history and zero stock is another supporting indicator that this NM is not functioning as intended.

http://www.classicffxi.com/db/items/12567/steam_scale_mail

**Comment by Kurtalicious** [comment]
I'm going to ask that you please reopen this ticket and give it due diligence.  I have visited this campsite twice since I made my original claim.  Over 90 minutes on each visit which is enough to see the NM at least once.  Unless someone can provide a screenshot of this NM in the last two weeks then I'm calling bullshit.

**Comment by KnowOne134** [comment]
The lizard does spawn and if not engaged within 3 mins despawns. The geysers are just missing the animations

**Comment by rreina** [comment]
I confirm I saw this NM spawning in the wrong location two months ago. I also saw it despawn after those 3 mins because I was low level and I couldn't kill it.
It spawned in G11 next to a group of Beam Lizards.

Could you verify it spawns at Geysers? H3, E7, and F9 respectively. It would be also good to know if those animations can be fixed.

Thanks

**Comment by TeoTwawki** [comment]
> Spent 3 hours in this zone at the geysers and never saw one eruption. According to wiki these geysers erupt every 60 +/-15 minutes. The Geyser Lizard NM spawns on when the geysers erupt. It's broken.

Retail has very quietly changed him a few times.  I dunno which version modern is using now. In 2004, he lotto popped off steam lizard. in 2006 till at least 2008, he spawned when the geysers blew but not necessarily at the one that went off - he could be at any of them, including the one that never goes off. Then when I they put in the lv80+ mobs they moved him back to lotto. but last year I found him just up idling.. At the geyser.

Considering you folks at eden are intending to be old era, you probably want the spawns at geyser-time version. Unfortunately, no iteration of private server development did the larger geysers animations yet.

**Comment by KnowOne134** [comment]
Retail:
camped the geysers today and he spawned when the geyser went off, camped all 3 and it spawned at the 1 that went off

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
