### ISSUE TITLE
Nebimonite breaking Halycon Rod

### ISSUE THREAD

**Issue by LongTimeGaming** [EdenServer/community#868]
I don't believe they're supposed too. I've broken it 3 or 4 times now with them.

**Comment by ZaksHouse** [comment]
Ya it's misleading, wiki says its breakable but if you go by what they always promote which is Great Blue website its unbreakable, need clarification.

**Comment by LongTimeGaming** [comment]
Ya, again most guide I've looked at for fishing (https://www.bluegartr.com/threads/84574-Fishing-Guide-1-100) show that you should be fine fishing for Nebi's with Halycon Rod and no fear of breaks. It's really annoying having to use the Clothespole to get away from breaks but then I lose because the fish is too small.

**Comment by LongTimeGaming** [comment]
Nebimonite are still breaking my Halycon rod on the ships between Mhaura and Selbina when they still shouldn't be.

**Comment by godmode** [comment]
Thank you for your ticket. Please do not bump tickets unless they are closed or you have more information to provide for them.

**Comment by Mozzy4Ever** [comment]
So a bit more information on this - Nebimonites (27 fishing) seem to be a bit weird. I'm 21+4 fishing and have used both Halc and Hume rod and will get "You have a bad feeling" on them occasionally. I'll sometimes be able to fish them up despite this, though usually it results in a line break. However if I don't get bad feeling, I get angler senses to proc. My last attempt I was using a Hume rod with crayfish paste, got angler sense proc, and it broke my rod? https://www.great-blue.jp/?fid=014&lng=en says both Halc and Hume rods are unbreakable...
