### ISSUE TITLE
3321, 3201, etc. on 1/27/19 @ 4:33pm PST

### ISSUE THREAD

**Issue by Dabman710** [EdenServer/community#870]
The only people allowed online at this time seem to be the linkshell in Dynamis-Windurst, so either that zone breaks the server or something bugs when it is activated. been going on for the past hour. only the 28 ppl in Dynamis are online at this time.. please fix! i wanna play too D:

**Comment by rujind** [comment]
lol, its because dynamis is on the BCNM server. BCNMs are on their own server.

**Comment by godmode** [comment]
I appreciate the bug reports but please reserve bug reports for actual bug reports. This is just clutter.
