### ISSUE TITLE
Quest "Faded Promises" not triggering

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#874]
According to: https://ffxiclopedia.fandom.com/wiki/Faded_Promises I should be able to trigger the quest as long as I'm level 20+ nin and I guess rank 4 tenshodo fame, which is the same level as leviathan. I'm talking to the NPC having fulfilled both those requirements (talking to him AS 25 ninja) with no success.

**Comment by bkesecker** [comment]
Not implemented in DSP.  https://wiki.dspt.info/index.php/Quests

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
