### ISSUE TITLE
Incorrect Miasma Filter ENM name list in Boneyard Gully

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#877]
Not sure if this is client side or server side, but the menu selection Head Wind was actually Sheep in Antlion's Clothing. Once I entered the battlefield all ingame text references afterward used the correct ENM name

![aneyus_2019 01 28_060328](https://user-images.githubusercontent.com/40915578/51848858-473af200-22d3-11e9-84dc-e67f6f1fb15f.png)

**Comment by roriffxi** [comment]
I selected 'like the wind' and it put me into Sheep In Antlions as well.
