### ISSUE TITLE
Beadeaux mobs dropping unintended items

### ISSUE THREAD

**Issue by ikatsu808** [EdenServer/community#882]
**Zircon** https://ffxiclopedia.fandom.com/wiki/Zircon_Quadav
and **Silver** Quadavs https://ffxiclopedia.fandom.com/wiki/Silver_Quadav
 confirmed to drop "**Quadav Helm**" https://ffxiclopedia.fandom.com/wiki/Quadav_Helm

**Comment by godmode** [comment]
Good attention to detail! Thanks for reporting.
