### ISSUE TITLE
Sororo sells OOE spell Repose

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#883]

**Comment by Aneyus** [comment]
Repose was added in 2007, it actually should be in the game if anything.

**Comment by rujind** [comment]
Yes, it is a WOTG spell. WOTG was released in November 2007.

**Comment by Aneyus** [comment]
Same patch changed 2 handed calculations, should we revert those as well? https://www.bg-wiki.com/bg/Version_Update_(11/19/2007)

**Comment by rujind** [comment]
Yes?

**Comment by Aneyus** [comment]
Okay, before this patch nerfed things, it was 1:1 DEX:ACC and 1:1 STR:Attack for 2 handed weapons, so I'm all for it as a SAM main!

My point is that just because something was changed after November 18 2007 doesn't mean it shouldn't be open to consideration. We all know that ToAU content was still being developed well after that point. Following this line of logic we shouldn't include mythic weapons either because they were added in 2008.

**Comment by rujind** [comment]
It's not really for you or I to decide. The development team wants Mythic Weapons and ZNMs in, which were post WOTG. They want just about everything else left out.

Pretty sure the decision was already made on this spell anyway, and when used you lose it when you zone, **which is why I'm reporting it as needing to be removed from the vendor.**

Lastly, I'm frequently told to post my opinions regarding things like this on the forums and not on the git, soooo.....

**Comment by Aneyus** [comment]
I am merely providing relevant information to the issue in question, I'm not attempting to pass a verdict here. And you are right; it is neither of our positions to do so in the first place.

You advocate that it should be removed entirely, and I'm advocating that it should be enabled.
We're both offering different solutions for the same issue, and as long as we can provide our reasoning and facilitate discussion I don't see an issue with it. These aren't opinions, these are facts.

Furthermore, I would also argue that ZNMs and other content designed after November 18th, 2008 probably had **the abilities in the game at that point in time** in mind when balancing them.

**Comment by AnimeMuyou** [comment]
Please delete this scroll from Sororo if we're not supposed to be able to cast the spell.  I farmed for the 30k gil, bought and used the scroll, only to notice later that Repose wasn't in my spell list.  :(  30k might not be a lot to some, but to my fresh new WHM48 (highest level job), it was a lot of gil lost.  Thanks for listening.

**Comment by godmode** [comment]
Does it still sell it?

**Comment by AnimeMuyou** [comment]
Thank you, godmode!
