### ISSUE TITLE
Cant' cast Reraise 1 on my 30 WHM

### ISSUE THREAD

**Issue by ArtemisXI** [EdenServer/community#887]
I bought a reraise scroll from the AH and noticed it said level 33 whm on it. I know the spell should be level 25 the same level you get raise, out of curiosity I used the spell anyways on my 64 brd/ 30 whm and was able to use the scroll. When I check my magic list its not there and when I click on white magic I see the spell but I am unable to cast it. My friend logged onto my character and was able to use the spell for some reason but I am unable to. Any help would be great. Thanks.

**Comment by ArtemisXI** [comment]
Never mind I think we figured it out, I am currently using Eden installer 2.1 which I believe had some .dat swaps to make spells more era accurate. My friends never downloaded the installer and are using 2.0 still so that is probably why they can use reraise at 25 and I cant use it until 33.

**Comment by godmode** [comment]
It shouldn’t even let them use it at 25. It should be purely aesthetic that the 2.1 installer gives

**Comment by ArtemisXI** [comment]
I just installed Eden 2.0 installer and I can now use the spell on my 30 whm, not sure whats going on or if the spell is suppose to be 25 or 33.

**Comment by godmode** [comment]
It should be 33. Will fix it. Thanks for reporting
