### ISSUE TITLE
Various mobs don't drop crystals when XPing on them.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#888]
There are a few mob families that seem to not drop crystals when they should.  If you exp on flies in most places, you will not receive Wind Crystals even though you should.  I've also noticed this issue on Gigas and Quadav.  This is regardless of conquest tallies, even when areas are not beastmen controlled this seems to be happening.  

Most commonly I've noticed the flies in Sanctuary of Zi'Tah and Crawlers' Nest, although this might also be the case in Valkurm and other areas as well.

**Comment by ShiyoKozuki** [comment]
Never had an issue getting crystals from Quadavs in the starter zones around Bastok

**Comment by KnowOne134** [comment]
can not reproduce
