### ISSUE TITLE
Empress Band losing charges without use

### ISSUE THREAD

**Issue by VeilEden** [EdenServer/community#890]
This is the second week in a row my Empress Band has randomly lost all remaining charges without use. I recharged on Sunday to save for this week. Tonight, I equipped it to use and it showed 0 charges remaining. I tried last week dropping it, and buying a new one. No luck. It occurred again this week.

Character name: Veil

**Comment by godmode** [comment]
Closing this issue in favor of a ticket that addresses the root cause. https://github.com/EdenServer/community/issues/918
