### ISSUE TITLE
DRG AF Helm NM's don't spawn

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#892]
Just tried to pop the DRG AF Helm NMs, but they wouldn't spawn.
Done all steps leading to this fight and had Wyvern out when trying to pop. Even tried w/o wyvern.

![pan_2019 01 30_133844](https://user-images.githubusercontent.com/36666121/51981885-b14ec500-2494-11e9-9f9a-0f0435b3bb3f.png)
![pan_2019 01 30_133854](https://user-images.githubusercontent.com/36666121/51981897-b6137900-2494-11e9-8570-3bb48dbb35f2.png)

**Comment by panfunk** [comment]
Checking the current DSP code for this quest and it's history I think I might have found the bug:

https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Temple_of_Uggalepih/npcs/qm15.lua

I think the 'and' in line 25 must be removed

**Comment by godmode** [comment]
Cool! Thanks for digging into this!

**Comment by panfunk** [comment]
Sadly, still doesnt work ;;

**Comment by godmode** [comment]
Its not deployed :)

**Comment by panfunk** [comment]
![pan_2019 02 08_234255](https://user-images.githubusercontent.com/36666121/52510225-73bc0b80-2bfb-11e9-9f79-01479af995a2.png)

woot, thanks! :D
