### ISSUE TITLE
Ulycille woodworking NPC recipe information locks character

### ISSUE THREAD

**Issue by marlinla** [EdenServer/community#894]
Ulycille in North Sandy at the woodworking guild who gives out adv. synth support. 

Locked down my character twice while click on the recipe option. Can only type text. Cannot use menus or anything else meaningful with character. Reconnecting fixed the issue.

**Comment by falantar** [comment]
Can confirm this also happens at alchemist and goldsmith guild for advanced support NPCs.

**Comment by KnowOne134** [comment]
appears to no longer be the case, can click and does nothing sonce reciepes are not coded, but can go on freely, acts as though you canceled out of the menu now
