### ISSUE TITLE
Monster Ranged Attacks are OP

### ISSUE THREAD

**Issue by AikoSachi** [EdenServer/community#895]
They're not only hitting extremely fast when you're out of melee range, but they're also hitting extremely hard almost like they're weaponskilling you every turn.

**Comment by AikoSachi** [comment]
Should mention noticed on my alt when I was in Valkurm Dunes

**Comment by erenik** [comment]
Have to agree. The Ranged attacks the gobs do are overpowered as it is right now. We had a party in the dunes the other day and a pal was getting one-shotted for 110-120 damage from a Goblin ambusher that should have dealt maybe 60-80 damage in retail (IT gob).

There are more voices around this on the forum as well: https://www.edenxi.com/forums/viewtopic.php?f=1&t=1140

**Comment by Volkaru** [comment]
It's an issue with any ranger mob (and NIN). Between this and BLM mobs casting almost constantly, it's incredibly hard to solo BLM or RNG on this server.

**Comment by 59blargedy** [comment]
resolved december 7 update. can reopen if the delay issue still exists, but damage has been fixed.
