### ISSUE TITLE
Like The Wind

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#9]
Upon completion of the ENM, it cuts to a CS from COP with Shikaree X/Y/Z instead of exiting the ENM; 

For the fight: The roadrunner is supposed to run away after using TP moves and reaggroes when the person highest on the hate list is nearby.  Also, when attempting to land slow/elegy, it says 'no effect' instead of a resist message.

All other mechanics seems to be working well for the ENM.

**Comment by godmode** [comment]
This should be disabled, we will be using Sheep in Antlion's Clothing for the ENM of choice in this area until DSP's `bcnmcrap` branch is merged into `master`. Thanks for reporting.
