### ISSUE TITLE
Homing Ring working outside of regions your nation controls

### ISSUE THREAD

**Issue by mattadjohnson** [EdenServer/community#900]
I saw someone use a homing ring today in a region that their nation didnt control, according to the wiki (an old revision with the first description of the requirements) it should only work in places that your nation controls.

https://ffxiclopedia.fandom.com/wiki/Homing_Ring?oldid=86362

note: It may be possible they used it and it didnt actually work but I didn't pay attention beyond that and the thought occurred to me later on, but I figured i'd open a bug report just in case.

**Comment by panfunk** [comment]
Can confirm that you can use Homing Ring while your nation does not hold the region

**Comment by KnowOne134** [comment]
GetRegionOwner(player:getRegion()) == player:getNation() then

**Comment by KnowOne134** [comment]
Corrected 11/30
