### ISSUE TITLE
door to Toraimarai Canal half broken

### ISSUE THREAD

**Issue by dakumauler** [EdenServer/community#901]
So if you use the door to go to Toraimarai Canal it will let you in. but if you try to use it to go back out to Windurst walls it will start the process then kick you back inside the side to Toraimarai Canal entrence.

**Comment by godmode** [comment]
This did not happen to me at the Toraimarai Canal door only the Sealed Portal door which is intentional behavior--it should be sealed from the outside. I'm closing the ticket but if the Toraimarai Canal door doesn't open from behind please let me know and I'll investigate with you.
