### ISSUE TITLE
Enagakure unexpectedly spawning on ship to Selbina

### ISSUE THREAD

**Issue by BenForgot** [EdenServer/community#902]
The ffxiclopedia says [Enagakure ](https://ffxiclopedia.fandom.com/wiki/Enagakure) should only spawn if someone onboard has the Seance Staff from the [I'll Take the Big Box](https://ffxiclopedia.fandom.com/wiki/I%27ll_Take_the_Big_Box) quest.

I haven't unlocked ninja and am not on the quest but it has spawned twice when I've been the only one onboard, and another time there was someone else. They warped out after getting aggro'd and were there to fish, so probably didn't have it either.

**Comment by Setz0r** [comment]
i noticed this when working on boats last night.  I'll be submitting a fix for this with my boat PR

**Comment by LongTimeGaming** [comment]
Even with it being up it's not the worst, it's that things also still aggro through the bottom of the boat. Died twice trying to fish.

**Comment by bkesecker** [comment]
Saw this guy yesterday.  Spawned at night around 20:00.  I was 34 WAR, no NIN quest or staff.  Did not engage.

**Comment by Eleeciam** [comment]
i road boat 5 times in window with key item for nin af he never spawned one time in 33 hours

**Comment by Setz0r** [comment]
did you depart on the nighttime boat?

**Comment by Eleeciam** [comment]
Yes I boarded boat to Selbina at 16:00 and he never popped at 20:00 - 1:00 end of boat ride was 3 hours 5 rides had friends with me all we saw was phantom pop sea manta and horror

**Comment by Eleeciam** [comment]
Every time at 20:00 phantom would pop should have been him and yes I have the key item

**Comment by Setz0r** [comment]
1600 is not night time.
with the current code, you'll need to leave on the boat that actually departs during night time hours for him to show up.

**Comment by Setz0r** [comment]
also, he currently only spawns on the ship from mhaura to selbina

**Comment by Eleeciam** [comment]
boat finally left at 22:00 to selbina and there he was this quest is a real pos thanks for your help
