### ISSUE TITLE
Ninja Magic burst with Ninja elemental wheel.

### ISSUE THREAD

**Issue by ElectroNicMan83** [EdenServer/community#903]
Hi, 
I have searched for a thread about it on forum and it said :
 "Development automation moved this from Bugs to Done on 31 Dec 2018"

Bug was :
I couldnt magic burst on any skillchain with ninja tool . 

Less important bug  :
 
BST pet doesnt respond to, when calling them back even when close.

**Comment by Kross22** [comment]
Bump, just noticed this last night while partying in Qufim.

Couldn't MB with Hyoton: Ichi with Distortion.  Tried many different timings as well.

**Comment by baggedmilk2112** [comment]
Tried hyoton and suiton with no success on MB.

**Comment by Volkaru** [comment]
Also noticed this. Confirmed it wasn't just a text box error, the bonus damage wasn't applied, as well.

**Comment by ShiyoKozuki** [comment]
I get a lot less resists when I "magic burst" hyoton so I'm not sure if it's applying or not tbh.
