### ISSUE TITLE
Spell shop in Lower Jeuno will sometimes sell spells without them appearing in your inventory until you zone

### ISSUE THREAD

**Issue by Strumerjohn** [EdenServer/community#904]
I bought a Shellra III that did not appear in my inventory until I zoned. I had space for it and the Gil was taken immediately with the purchase but I did not get the item until I switched zones. Caused me to panic making me think I lost 30k at first and I opened a GM call before issue sort of resolved itself when I zoned.

**Comment by KnowOne134** [comment]
Have not heard of this before, reopen ticket if it occurs again
