### ISSUE TITLE
Bastok mission 2-3 San d'Oria leg helaku

### ISSUE THREAD

**Issue by pksweets** [EdenServer/community#905]
On Bastok 2-3, killed Warchief Vatgit, still have the title, but Helaku does not allow me to complete this leg of the mission.
![zoltz_2019 02 03_215943](https://user-images.githubusercontent.com/27723566/52192483-0f660a00-27ff-11e9-9a03-50b9d5e9580c.png)

**Comment by godmode** [comment]
This appears to be fixed. Please comment if it wasn't.
