### ISSUE TITLE
An Explorer's Footsteps bugged

### ISSUE THREAD

**Issue by yokhai** [EdenServer/community#909]
The quest "An Explorer's Footsteps" will not drop from my quest list when i turn the clay tablet to Abelard so he constantly talks about the quest, blocking me on any other quest he is apart of, meaning I cannot progress through "Signed in Blood". Was told this was a known issue and a GM needs to manually remove the "An Explorer's Footsteps" quest flag.

**Comment by godmode** [comment]
Duplicate of #858
