### ISSUE TITLE
Gusgen Mines gates: Unable to open from behind.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#91]
Levered gates should be able to be opened from behind by clicking.  Instead, it gives the message that prompts you to activate a lever.

**Comment by chlorr** [comment]
I thought those ones specifically weren't openable from behind? At least my exp on kupo / nasomi have been like that. yet to go back on Eden though

**Comment by godmode** [comment]
Which gate?

**Comment by chlorr** [comment]
the doors on map 1, routes A B C that lead to map 2, and probs the 2nd set on map 2 as well
![gusgen-mines_1](https://user-images.githubusercontent.com/43849717/46576234-f09f5600-c979-11e8-86ca-cff209c2f46f.png)

**Comment by Lilswitche** [comment]
All 6 (A, B, C, D, E, F).  A-C specifically, on Eden if you pass them, you're trapped inside.

**Comment by chlorr** [comment]
they should stay open until you hit another lever

**Comment by Lilswitche** [comment]
They're supposed to close on their own after a brief period of time.  They're supposed to open from behind.  If what you are saying is true, the moment you open D-F, you're trapped inside.  Likewise, if they were to remain open til another was switched, it would be very easy to grief and trap someone inside.

**Comment by chlorr** [comment]
Ah, my exp on kupo is open B, check for mining node in that tunnel, then back out to A. And on my pathing, A will still be open when i come back around on the next run thru after i escape and restart

**Comment by chlorr** [comment]
Just spoke to Chawlee, i gave him my path last night and he said he had no issues with the doors staying open, unless he hit a different lever to use a different door

**Comment by Lilswitche** [comment]
I'll do some more research but on retail I thought these were specifically changed to keep people from griefing.

**Comment by chlorr** [comment]
Hmm, perhaps just wasn't implemented on kupo / eden(?).

**Comment by Aneyus** [comment]
When D/E/F are closed you drop at H and climb back up at G to get back behind them.

**Comment by godmode** [comment]
Was there a consensus if this should be looked into or everything good?

**Comment by Aneyus** [comment]
I don't know if anybody has tested gates A/B/C conclusively. If they stay open indefinitely until another lever is pulled, then everything is fine. If they close on their own eventually, then they should probably be able to be opened from behind.

**Comment by godmode** [comment]
Please reopen if this appears to be an issue.
