### ISSUE TITLE
Lost Scroll of Utsusemi Ichi to paralyze

### ISSUE THREAD

**Issue by Tacoxtuesday** [EdenServer/community#910]
Happened on tacotruck, dunno if it can be recovered or if it's an expensive lesson. 
![tacotruck_2019 02 04_140508](https://user-images.githubusercontent.com/46499148/52241357-46ccc900-2888-11e9-8998-6d8189c655b7.png)

**Comment by godmode** [comment]
It is intentional, not a bug. But you can make a GM call about it and I will confer with GMs/devs if we want to make a one time item replacement.
