### ISSUE TITLE
Can't re-enter Promyvion-Holla after win.

### ISSUE THREAD

**Issue by klement87** [EdenServer/community#911]
I can't enter Promyvion-Holla after clearing the zone. The shattered telepoint just gives the "The telepoint has been shattered into a thousand pieces" message and no option to enter. At first I thought this was because of the old erasing memory mechanic, but I can enter Mea and Dem with no issue.

**Comment by klement87** [comment]
That's definitely not an era thing. Kind of sucks if I wanted to help someone else.

**Comment by Wiggo32** [comment]
not sure if that's era or not, but thats how it's seems to be set up, maybe someone else could shed some light.

**Comment by klement87** [comment]
I mean it's not a big deal if I join a group that has no clears. I can just explain to them I need to clear mea and dem first. But if I teamed up with someone who has dem or mea cleared our group as a whole is effectively locked out of 2 zones. 
In era once you cleared a zone there was no restriction on it for re entry. If you failed to clear a zone there was the whole memory reset bs before you could enter another new zone.

**Comment by panfunk** [comment]
https://ffxiclopedia.fandom.com/wiki/The_Mothercrystals?oldid=320086

> 
> Promyvion zones are keyed upon entry; if you've gone into Dem you can skip the entry cutscenes by talking to the Cermet Door in Dem. Conversely you can't warp directly to Mea and enter the crystal there. You'll receive no message explaining your inability to enter. If you want to leave the Promyvion you're working on and go elsewhere, use the Large Apparatus on your way out. The Apparatus will erase your memory, allowing you to enter any Promyvion zone.
> 

Did you try 'erasing' memory?

**Comment by klement87** [comment]
Finished Promyvion-Dem and now I can enter all of the zones again.

**Comment by mlandrum22** [comment]
This seems to be broken again.
