### ISSUE TITLE
Quest "A Clock Most Delicate" Not Triggering

### ISSUE THREAD

**Issue by Blex64** [EdenServer/community#912]
See title. I should have max Jeuno fame, so it shouldn't be an issue. Nothing associated looks like its going to trigger. Not sure if its implemented in DSP or not.

**Comment by Volkaru** [comment]
Attempted this quest, myself. It worked on Kupo (very old AH sales) and the entire questline works on base DSP according to their Quests wiki page. So the issue is specifically eden.
