### ISSUE TITLE
Sidewinder seems too accurate after the WSACC buff

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#914]
I didn't play RNG on retail but I know it isn't missing nearly enough right now on Eden. Hopefully some other rangers can weigh in.

**Comment by Elysien** [comment]
I did some brief digging but couldn't find anything, however I do remember talk of accuracy penalty imposed on Sidewinder/Slug Shot known as the big "rng nerf" of retail. I vaguely remember talk of it being -40%, which effectively means that if you're capped ranged accuracy on the target, you're going to miss those two WS 55% of the time no matter what. I'm not sure if that number is accurate, but I'm fairly sure that is how the 'nerf' worked.

**Comment by Setz0r** [comment]
the WSACC buff only applied to regular physical weapon skills, not ranged

**Comment by KnowOne134** [comment]
Has been adjusted
