### ISSUE TITLE
RSE Sachets

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#92]
Only tested in Gusgen Mines with Galka.  ??? did appear in 1 of the 3 locations, but does not spawn the NM.  Attempted spawn was done during Galka RSE week.

Gusgen Mines: [Aroma Fly](http://ffxiclopedia.wikia.com/wiki/Aroma_Fly)
Ordelle's Caves: [Aroma Leech](http://ffxiclopedia.wikia.com/wiki/Aroma_Leech)
Maze of Shakrami: [Aroma Crawler](http://ffxiclopedia.wikia.com/wiki/Aroma_Crawler)

**Comment by Timonthy** [comment]
Searched to find if this was reported. Can confirm, was in Ordelle's for Hume RSE and there were multiple ??? but none of them would spawn the leech. Thanks!
