### ISSUE TITLE
Escape breaks the Shadowlord Cut Scene and You Will Not Receive the Key Item

### ISSUE THREAD

**Issue by SaberSuper** [EdenServer/community#920]
After we defeated the Shadowlord today, I escaped w/ my Black mage since i was left in the throne room (b/c i'm just helping) and the cut scene is supposed to drop you at the entrance to castle zhav bailey.  Somehow the escape from the throne room took the people in the cut scene with me (even tho they were not visible too me).  This interrupted their cut scene and they did not receive the Key Item forcing us to repeat the mission fight in order to re-obtain the Key Item.  I don't believe this should even be possible and this will undoubtedly create problems in the future.

**Comment by panfunk** [comment]
probably connected to: https://github.com/EdenServer/community/issues/460#issue-389454921

**Comment by godmode** [comment]
@jmcmorris does your PR stop friendly fire too? 🗡

**Comment by jmcmorris** [comment]
Yes, it makes it so that you cannot be a target of any spells (direct or indirect) while in a cutscene.
