### ISSUE TITLE
Suspected incorrect dig table for Wajaom Woodlands.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#923]
Base dsp has incorrect items/weightings for Wajaom Woodlands dig table.  It uses the same one from Bhaflau Thickets.  I've edited the table in dsp's format/weighting to the correct items/values based on the wiki.

    [dsp.zone.WAJAOM_WOODLANDS] = -- 51
    {
        {  646,   3, digReq.NONE    },
        {  845,  75, digReq.NONE    },
        {  770,  31, digReq.NONE    },
        {  702,  52, digReq.NONE    },
        {  833, 190, digReq.NONE    },
        {17296, 147, digReq.NONE    },
        { 2164,  17, digReq.NONE    },
        { 2213, 152, digReq.NONE    },
        {  838,   4, digReq.NONE    },
        { 4096, 100, digReq.NONE    }, -- all crystals
        { 1255,  10, digReq.NONE    }, -- all ores
        {  688, 137, digReq.BURROW  },
        {  690,  10, digReq.BURROW  },
        { 1446,   1, digReq.BURROW  },
        {  700,   4, digReq.BURROW  },
        {  699,  31, digReq.BURROW  },
        {  701,   4, digReq.BURROW  },
        {  696,  35, digReq.BURROW  },
        {  678,   1, digReq.BORE    },
        {  645,   1, digReq.BORE    },
        {  768,  98, digReq.BORE    },
        {  737,   2, digReq.BORE    },
        { 2475,   3, digReq.BORE    },
        {  739,   1, digReq.BORE    },
        {  738,   3, digReq.BORE    },
        { 4570,  10, digReq.MODIFIER},
        { 4487,  11, digReq.MODIFIER},
        { 4409,  12, digReq.MODIFIER},
        { 1188,  10, digReq.MODIFIER},
        { 4532,  12, digReq.MODIFIER},
    },

**Comment by godmode** [comment]
@Wiggo32 you wanna take this one or want me to?

**Comment by Wiggo32** [comment]
the entire thing still needs to be gone over, not just wajaom. there are inconsistencies on other maps as well. i've been working on it... slowly =(

**Comment by KnowOne134** [comment]
checked and these changes have already been made
