### ISSUE TITLE
Beast Affinity not working correctly.

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#924]
I'm not exactly sure what Beast Affinity is doing right now, but I currently have merits in it which should ensure that my 75 cap jugged pets should be the same level every time. That currently isn't the case though. 
![2019-02-07_13-48-36](https://user-images.githubusercontent.com/2160211/52442195-28650880-2ae8-11e9-8034-26f216c42385.png)
![2019-02-07_14-44-10](https://user-images.githubusercontent.com/2160211/52442196-28650880-2ae8-11e9-811f-85dedfea9a96.png)

I'm also almost certain that the formula for jug pets is undertuned. I don't have an account on retail to check but if someone does if they can sync to 75 or below I can help with the eden side of the comparison on /checkparam

**Comment by panfunk** [comment]
Beast Affinity does not work on Lv75 Jugs, they will always be spawned as Lv73-75 pets unless you get Relic Gloves which will make them 74-75. Beast Affinity only influences Jugs that cap <Lv73. Like Funguar familiar (63?) will be 65 with 1 merit in BA

**Comment by montijin** [comment]
I wasn't aware of that, stopped playing before checkparam was a thing. ^^; Oh well! If any 75BST wants to check if its working correctly here is stats on my funguar familiar with beast affinity. 
![fcdtrz3](https://user-images.githubusercontent.com/2160211/52455749-4a29b400-2b17-11e9-9f23-af84c4faa8cf.png)
