### ISSUE TITLE
Incorrect monster model in Promyvion

### ISSUE THREAD

**Issue by roclm** [EdenServer/community#925]
Minor nitpick, but the Empty mob "Thinker" in Promyvion - Holla has a Seether's model instead of a Thinker. Granted, I've only seen the one Thinker on the first floor, I'm unsure if the issue persists higher up.

What it looks like on Eden:
https://i.imgur.com/FOXMvXZ.png

What it should look like:
https://vignette.wikia.nocookie.net/ffxi/images/5/59/Thinker2.jpg/revision/latest?cb=20080513164229

**Comment by godmode** [comment]
Did you use Eden’s installer? If so which version?

**Comment by roclm** [comment]
I did use Eden's installer v2.1
EDIT: I remembered my laptop was still on v2.0 installer, and the issue exists there too.

**Comment by Novadragon-Siren** [comment]
Same for me, it's an incorrect mob.

**Comment by roclm** [comment]
A related issue is a bunch of Wanderer mobs in Promvyion-Dem are called "Weeper." This isn't a case of incorrect model, as they use the appropriate weapon skills to Wandered type monsters.

**Comment by Mikokiko** [comment]
Same thing for a few in promivion-Vahzl

**Comment by godmode** [comment]
Could you give more details? Your install version. What mobs you saw were named what. Etc

**Comment by Mikokiko** [comment]
It was mainly the stray that had the wrong name, or they had the model of the weaper.

Version did not seem to mather, as mine is out of date, but 2 peoples had up to date and were seeing the same thing (out of the 12 people there, we all saw stray showing as weaper and uncorrect names). 

iirc it was on floor 3 and 4.

If you need more info, I can bug someone from the group to come update this.

**Comment by godmode** [comment]
I see. Floors 3 and 4 have occasional weeper and seether strays.

**Comment by KnowOne134** [comment]
unable to produce, promy v 3rd floor up you will see strays with other models
