### ISSUE TITLE
/yell not reaching Xarcabard

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#927]
Just noticed that my Alt didn't see /yells in Xarcabard, possibly Beaucedine Glacier also. 
Tried relogging, no change.

Saw tells again once back in Bastok.

Since I modded my chat filters alot, would be nice if someone could comment if they noticed something similar.

Alos link to other /yell issue: https://github.com/EdenServer/community/issues/423#issue-388505146

Edit. I don't use that yell filter addon someone (Matty?) made

**Comment by dakumauler** [comment]
yell not working in xarcabard. just tried it.

**Comment by panfunk** [comment]
Appears to apply to Attohwa Chasm aswell.

**Comment by marlinla** [comment]
/yell does not reach Kazham.

This seems like the best spot to report zones which don't have /yell.
