### ISSUE TITLE
Kirin's Osode drop rate too low

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#928]
This should be a ~40% drop but we aren't seeing anything close to that so far. We've only had 2 drops in 16 kills on Eden.

https://ffxiclopedia.fandom.com/wiki/Kirin

**Comment by Oyaziiiiiii** [comment]
Update: 2/20 now

**Comment by panfunk** [comment]
I can't speak for Osode, but I noticed something similar for N.feet droprate on Suzaku, current retail droprate is at 30%ish, with up to two. Which should apply to era aswell I suppose. Yet in the last 10 kills I seen, it never dropped. Also, of these 10 the shura abjuration dropped at least 5 times. (yay)
Ofc this could be bad RNG, but maybe there is a general issue with loottables/drop generation on NMs/HNMs with a large itempool

**Comment by Shoruto** [comment]
I am only able to compare the drop percentage to Wikia as that is the only resource I'm finding that list percentages. But as of February 20th 2008 it starts to list the Osode, as 63% and then goes up to the latest update at 39%. So far I am not finding what the current percentage should be during era.  

February 20, 2008
https://ffxiclopedia.fandom.com/wiki/Kirin?oldid=452881

September 16, 2014
https://ffxiclopedia.fandom.com/wiki/Kirin?oldid=1499553

**Comment by Oyaziiiiiii** [comment]
I think it should have a similar drop rate to the armor pieces from the other gods. From memory, it 
seemed to drop about as often as it didn't, so the 40%ish thing doesn't seem far off.

https://www.ffxiah.com/item/12562/kirins-osode (top comment)
http://www.ffxidb.com/zones/178/kirin

I agree that this may also be a deeper problem with how loot pools are setup and/or how they are affected by TH.

**Comment by Slamm21** [comment]
We have killed 40 Kirins since the beginning of August
Got 12 Osodes (30%)
8 W legs (20%)
Sadly I only reported what people used points for so I don't have the numbers on the rest.
Every kill had TH3, never TH4 or TH2.
