### ISSUE TITLE
Signed in blood/ explore

### ISSUE THREAD

**Issue by trollsc** [EdenServer/community#930]
I have completed all turn in areas for crawlers nest map. Have map. But keeps telling me to go to other areas. When I do that area it will not take clay. I have signed in blood quest up to point to talk to mayor. He will not give me next step because he wants clay. I talked with GM warden today. He asked me to open with this information.

**Comment by Curon6** [comment]
I have almost the same issue (I only did 2 monuments of the explorer quest line) and the NPC Abelard doesn't bother to talk about the Signed in Blood quest, therefore won't let progress with the quest.

**Comment by godmode** [comment]
There is an issue with progressing through An Explorers Footsteps but if you have started that it is normal to have to complete it before you can progress with Signed in Blood

**Comment by Curon6** [comment]
Ahh ok, I didn't find a hint that the quest blocks it but thank you for the quick clarification!

**Comment by godmode** [comment]
This will be fixed on the next patch. However characters that have already started it may be stuck. If this is the case **after the patch** place a GM ticket and I will progress you to where you should be.
