### ISSUE TITLE
Shiva's Claws paralyze effect seems non-existent

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#931]

**Comment by FariskaEden** [comment]
Tested on Icesday when the proc chance is greatly increased and had no luck trying to get the paralysis effect. Other days I had no luck as well so yes I can also confirm that the paralysis effect from these do not seem to work.
https://ffxiclopedia.fandom.com/wiki/Shiva's_Claws

**Comment by jubs1982** [comment]
Can confirm these still do not proc at all.

**Comment by bkesecker** [comment]
Big ticket: https://github.com/EdenServer/community/issues/1487

**Comment by laroneda** [comment]
Shiva Claws still not proc, are these being looked at? Notice it’s been months since they were reported with no feed back. Would love to be able to use them.

**Comment by gweivyth** [comment]
I haven't tested this one yet but unless I majorly screwed up, this should be a functioning lua for this weapon. 

-----------------------------------------
-- ID: 17665
-- Item: Shiva's Claws
-- Additional Effect: Paralyze (Chance increased on Iceday)
----------------------------------
require("scripts/globals/status")
require("scripts/globals/magic")
require("scripts/globals/weather")
require("scripts/globals/msg")
-----------------------------------

function onAdditionalEffect(player,target,damage)
    local chance = 15

    if (VanadielDayElement() == dsp.day.ICEDAY) then
        chance = chance+6
    end

    if math.random(100) <= chance and applyResistanceAddEffect(player, target, dsp.magic.ele.ICE, 0) > 0.5 then
        target:addStatusEffect(dsp.effect.PARALYSIS, 17, 0, 30) -- I couldn't verify how powerful the paralyze was, may need adjusting.
        return dsp.subEffect.PARALYSIS, dsp.msg.basic.ADD_EFFECT_STATUS, dsp.effect.PARALYSIS
    end
    
    return 0, 0, 0
end
end

**Comment by gweivyth** [comment]
I haven't tested this one yet but unless I majorly screwed up, this should be a functioning lua for this weapon. 

```lua
-----------------------------------------
-- ID: 17665
-- Item: Shiva's Claws
-- Additional Effect: Paralyze (Chance increased on Iceday)
--Retail testing done by Gweivyth.  May need adjusting, couldn't verify paralyze duration.  Retail duration was very varied. 
----------------------------------
require("scripts/globals/status")
require("scripts/globals/magic")
require("scripts/globals/weather")
require("scripts/globals/msg")
-----------------------------------

function onAdditionalEffect(player,target,damage)
    local chance = 15

    if (VanadielDayElement() == dsp.day.ICEDAY) then
        chance = chance+6
    end

    if math.random(100) <= chance and applyResistanceAddEffect(player, target, dsp.magic.ele.ICE, 0) > 0.5 then
        target:addStatusEffect(dsp.effect.PARALYSIS, 17, 0, 30) -- I couldn't verify how powerful the paralyze was, may need adjusting.
        return dsp.subEffect.PARALYSIS, dsp.msg.basic.ADD_EFFECT_STATUS, dsp.effect.PARALYSIS
    end
    
    return 0, 0, 0
end
end
```
