### ISSUE TITLE
Quadav Ore Toss is multi-hit when it shouldn't be

### ISSUE THREAD

**Issue by roclm** [EdenServer/community#934]
Quadav's Ore Toss TP ability should be a single hit ranged attack, but it's behaving as a 3-hit skill right now.
Wikipedia showing Ore Toss' statistics:
https://ffxiclopedia.fandom.com/wiki/Category:Quadav

Screenshots showing Ore Toss taking 3 shadows, and wiping 2 & dealing damage:
https://i.imgur.com/xjvHSCS.png
https://i.imgur.com/jW0Rbdo.png

**Comment by Elysien** [comment]
I cant say whether or not I remember if this is correct behaviour for this specific TP ability, but there are single-fold TP attacks that require multiple damage to fully absorb, even in the absence of multi-attack traits occurring on them. For instance, in the very same family, the Quadav ability "Shell Charge" is a single-fold attack, but required 2-3 shadows to fully absorb. The Orc ability "Battle Dance" is also single-fold, but can consume 1-2 shadows even without double/triple attack traits. There are more examples though I struggle to recall; I believe Cerberus' "Sulphurous Breath" was another one.

**Comment by roclm** [comment]
You are correct that certain TP abilities can take multiple shadows, however I believe every instance of this is an AoE ability.  However, you are right, it is something I had forgotten! Shell Charge was a conal WS from WOTG NMs, Battle Dance is an AoE centered on the Orc, and Cerberus' Sulfurous Breath was another conal skill. Whirl of Rage is another AoE centered on the caster (Evil Weapon) that took a variable amount of shadows. (All of these multi-shadow taking AoE skills took shadows based on the user's Ninjutsu skill according to 2004 patch notes.)

The above makes me believe that perhaps Ore Toss is behaving as an AoE TP move when it shouldn't be, but honestly I'm now questioning myself a lot more. I was quite certain it absorbed one shadow in retail, and I'm going to attempt to do some more research.
