### ISSUE TITLE
Scroll of Instant Warp CP

### ISSUE THREAD

**Issue by klassenjo** [EdenServer/community#938]
**NPC**: Rabid Wolf, I.M in Bastok Markets
**Issue**: Scroll of Instant Warp is listed at 10 CP. I purchased it while I had just over 1000 CP, it charged me 700 CP.

**Comment by klassenjo** [comment]
I don't have enough CP to test this again (new player), but if someone with enough CP could confirm this that would be great.

**Comment by godmode** [comment]
This is expected. Please read the following post: https://www.edenxi.com/forums/viewtopic.php?f=31&t=68

**Comment by klassenjo** [comment]
Ah ok. Understood. Thank you.

**Comment by godmode** [comment]
It’s best to leave this open because the issue is still there. I just wanted to point out a place that you can see it.

**Comment by klassenjo** [comment]
> It’s best to leave this open because the issue is still there. I just wanted to point out a place that you can see it.

Oh right, oops. Thanks for the quick response.

**Comment by KnowOne134** [comment]
Has been dat edited
