### ISSUE TITLE
Possible NM drop issues [Hoo Mjuu the Torrent, etc]

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#939]
Some NMs that are supposed to have a 100% drop rate of one item or the other are not correct. Namely Hoo Mjuu the Torrent, and likely others. Here's a cursory list of NMs that may be affected:

Hoo Mjuu the Torrent - Confirmed not working
Mee Deggi the Punisher - Likely working properly
Quu Domi the Gallant - Likely working properly
Juu Duzu the Whirlwind - Unknown
Vuu Puqu the Beguiler - Unconfirmed that this NM even shares the same either-or drop condition, just assuming

Notable exception - Yaa Haqa the Profane - Does not share the same either-or drop conditions, so not ALL Yagudo NMs with two drops are necessarily this way. https://ffxiclopedia.fandom.com/wiki/Talk:Yaa_Haqa_the_Profane

**Comment by ThrisStraizo** [comment]
To add to this, I've personally witnessed Poisonhand Gnadgad drop the pants AND Jijitsu Gi simultaneously.

**Comment by godmode** [comment]
The only one I could verify that is missing this mechanic was Poisonhand. I feel like Hoo Mjuu was like this on retail but I am not 100% on it and I don't see any data that supports it either. Please let me know if you find some.

**Comment by jamiehavok** [comment]
I camped Hoo Mjuu the Torrent a ton on retail and he indeed either drops the signa (lowest drop rate) or the zealott mitts or a scroll of deodorise but never more than one. This page kind of confirms it http://ffxi.allakhazam.com/db/bestiary.html?fmob=117&p=2#comments Most notably DariganLFrits post a few down. But there are several posts describing the drops they have that pretty much confirms it.

**Comment by Nyoomy** [comment]
Just killed Hoo Mjuu post update, and he dropped nothing at all, as opposed to 1 of 3 items.
Was he changed to be 1 of 3, or just a chance to drop any of his drop table?

**Comment by godmode** [comment]
He should be definitely 1/3 all the time. I’ll take a look at it when I get home.

**Comment by Tavnazian** [comment]
can confirm, Juu Duzu the Whirlwind is not working properly. had a no drop today

**Comment by Tavnazian** [comment]
and a double drop. which isn't supposed to be possible either.
