### ISSUE TITLE
Garlaige Citadel gates not opening from the inside

### ISSUE THREAD

**Issue by Umarusuzy** [EdenServer/community#94]
The banishing gates aren't opening once past the gate.  Clicking on these gates from the inside should open them but nothing happens.

**Comment by godmode** [comment]
They shouldn’t open from inside. But the gates should probably stay open a bit longer

**Comment by gweivyth** [comment]
Garlaige gate doesn't open from the inside, you have to navigate back to the other side via one-way drops.

**Comment by Serephim** [comment]
I remember them opening from the inside on retail. Never have I ever had to drop down and go back around to hit the switches again for someone that didn't make it through on time. It is almost impossible to make it through the gate from the far switches at gate 3 with how fast they close. Maybe that was changed at some point?
