### ISSUE TITLE
Issue with Beastmaster pet and 2h vs 1h weapons.

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#940]
HI, 
So far Beastmaster is good but there is something not wrong with the pet and experience.

Slime cant be used at all vs other mob because they are as squishy when they are supposed to be stronger.

Ex Bat vs Slime -> slime should win high hand. 

I dont know if its the same issue but for subligar farming I heard Slime dont have the same Piercing defense resistance than retail.

BST have A+ axe skill yet so far DPS is way lower compared to Scythe wich is B+ in a dual wield setting. 

Even when I was leveling my ninja dual wield was very weak even if I was using almost best in slot gear + food.

**Comment by ElectroNicMan83** [comment]
Further problem with bst Is ****pet not responding to command when close and get stuck in a little rock on the ground or every corner.****

**Comment by ElectroNicMan83** [comment]
/stay dont work most of the time.

**Comment by 59blargedy** [comment]
i believe all of these concerns have been addressed via various patches in the past year.
