### ISSUE TITLE
windy 3-2 issue. going on a month

### ISSUE THREAD

**Issue by Zaki1128** [EdenServer/community#941]
im trying to do 3-2 and zubaba wont talk to me. this has been going on forever. can i please drop the quest or get it fixed? i would really like to get my airship pass. and because i accidentally picked up this broken quest that i dont even want to do, im screwed

**Comment by godmode** [comment]
I’m sure you made a GM ticket but it may be missing information. This is not a detailed enough ticket to do anything with on my end. Can you provide more information?

**Comment by Zaki1128** [comment]
me and a buddy were going to do 4-1, which comes from jeuno. me, not knowing, picked up the 3-2 i skipped earlier.

so i go to jeuno hoping that i could do 4,1 instead. i get the cutscene in the windy office and receive the audience paper or whatever, but nothing works after that.

gm i spoke to said i have to go do 3-2. so i go to windy and i cant even start it. 

thats thewhole story

**Comment by godmode** [comment]
Please remind me tonight on Discord if you are online. Between 6-8pm I'll investigate.

**Comment by godmode** [comment]
This issue should be resolved.
