### ISSUE TITLE
2-3 glitched

### ISSUE THREAD

**Issue by Tanabeo** [EdenServer/community#948]
I'm working on 2-3 from sandy I went with the Windy->Bastok way I was able to do all the stuff for windy just fine but when I got to bastok nothing is working right. Savae E Paleade is telling me good luck on my mission but I never got a CS. Pius won't talk to me and Grohm tells me about the magic circle in Palborough Mines but when I go there I don't have the choice for rank 2 mission. I have updated the client, I deleted everything and reinstalled and still nothing. Anyway you can reset my mission and I can start over?

**Comment by godmode** [comment]
When was this mission started?

**Comment by Tanabeo** [comment]
I started it about 3 weeks ago was hoping a update would fix mine

**Comment by godmode** [comment]
Ok cool, yeah it will need manual intervention. I’ll be able to help tomorrow evening after work. Possibly tonight if I finish coding. Please make a GM ticket and address it to me tomorrow night or message me on Discord.
