### ISSUE TITLE
Bastore Sweeper out of era Fishing GP request.

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#949]
It's only fishable in WOTG areas, shouldn't be in the game.

**Comment by HammerhandsKupo** [comment]
Got this today as well with the Artisan (68-70) GP request.

**Comment by Deepupuu** [comment]
Got it today too, it's also fishable in Abyessa areas :P

**Comment by Hatberg** [comment]
As far as I can tell, in the period it was implemented, Bastore Sweeper should have been Greedie.

Closest record I can find for the original Fishing Recruit (F) Pattern:
https://ffxiclopedia.fandom.com/wiki/Guild_Points/Items?direction=next&oldid=1005699
First registered at December 4, 2009

The Guild Pattern was updated with Bastore Sweeper around Feb 2, 2013:
https://ffxiclopedia.fandom.com/wiki/Guild_Points/Items?direction=next&oldid=1424695

**Comment by Mozzy4Ever** [comment]
Still getting it as a guild item =|

![image](https://user-images.githubusercontent.com/11255886/57316201-de75c980-70ba-11e9-803c-ea8fc067c0fa.png)

**Comment by Raphtalia1** [comment]
just ran into this today for artisan

**Comment by MeyiLekoh** [comment]
Got this again as a Guild Point item today. :( Novice Fishing (37).

![bastoresweeper](https://user-images.githubusercontent.com/47701928/60379430-41168200-99e7-11e9-840b-ee13fbc4489d.png)

**Comment by MonkeyAce9** [comment]
Received this Guild Point item today. Still in game. oh well. :(

**Comment by baggedmilk2112** [comment]
Got this one again today @ level 47 fishing. 
https://ffxiclopedia.fandom.com/wiki/Bastore_Sweeper?action=history

**Comment by falisaxi** [comment]
Still getting this today

**Comment by danismyhero** [comment]
A little more detail, Journeyman fishing got it today.

**Comment by freddiepines** [comment]
![image](https://user-images.githubusercontent.com/50085658/85131301-84738d00-b204-11ea-9274-626673ac3dd2.png)
