### ISSUE TITLE
Candle Holder NPC Buy Price

### ISSUE THREAD

**Issue by xrocksterx** [EdenServer/community#950]
While skilling up gs ran into an issue with Candle Holder.

Currently NPC buys Candle Holder for 0 gil.

Attempted multiple npc and still same price.

Buy price should be in the range of 4,960~5,059 gil according to wikia.

Wikia: https://ffxiclopedia.fandom.com/wiki/Candle_Holder
ffxiah: https://www.ffxiah.com/item/459/candle-holder

**Comment by godmode** [comment]
@Far-The-Killer looks like this item should be removed from Eden
