### ISSUE TITLE
2-3 

### ISSUE THREAD

**Issue by bigtooltwo** [EdenServer/community#951]
now im not sure on era or not...however on wiki since classic is not updated i used regular says final 2-3 battle not capped but was capped to 25 making this impossible solo which was the plan.  so when i died i lost xp which states your not suppose to lose xp from those fights

**Comment by godmode** [comment]
Someone must have written the wrong information on our wiki. It’s capped at 25 and you can lose exp. The wiki is user editable though. I hope you win next time!
