### ISSUE TITLE
Teleport-Altep NPC Not Giving Me Scroll. FIXED. 

### ISSUE THREAD

**Issue by Ganbatte92** [EdenServer/community#952]
Completed the quest by talking to the NPC known as, "Charlaimagnat" in Northern Sandy
He says I should return another day to get my scroll, but upon talking to him almost 4 days later he still gives me the same dialogue and doesn't give me the Teleport-Altep scroll. 

EDIT:
I've also zoned several times but to no avail. 
Maybe it's **Japanese Midnight** instead of one in-game day? Not sure how that works on Eden. 

Fixed: Yes, it was JP Midnight. Sorry.

**Comment by godmode** [comment]
By days you mean vanadiel days?

**Comment by Ganbatte92** [comment]
> By days you mean vanadiel days?

Yup. I waited a few in-game days, but I've just gone back after JP midnight and he gave me the scroll! Looks like it was JP midnight.

**Comment by 33username** [comment]
So close this?

**Comment by godmode** [comment]
I want to make sure that it’s the correct time. Please leave it open for now.

**Comment by KnowOne134** [comment]
Its up midnight
