### ISSUE TITLE
quest string in windhurst for aspir spell

### ISSUE THREAD

**Issue by bigtooltwo** [EdenServer/community#955]
completed quest reap what you sow by trading deathball thus should make quest non repeatable however when zoned and returned that is still the quest offered.  I need to complete this to complete let sleeping dogs die to get quest for aspir making the grade

**Comment by Shoruto** [comment]
As long as you don't have Let Sleeping Dogs Lie active (showing in your log) you are able to access Making the Grade.  Just make sure you complete Teacher's Pet before Making the Grade and zone after each quest.

**Comment by Althaia** [comment]
I seem to be unable to get "Let Sleeping Dogs Lie" to activate, it's just an endless string of "Reap What You Sow," despite also trading in a Deathball -- which should've made the quest non-repeatable. Like the person above, when I zone back in, it's just more "Reap What You Sow."

I have talked to the NPC for "Reap What You Sow" many times -- and completed "Reap" quest many times -- and he only ever alternates between his default text of not being pleased with adventurers being at the school and his dialogue for initiating "Reap What You Sow."

I even tried giving him a Thumbs Down on his request of gardening assistance, but it didn't change his dialogue options.

So I suppose my purpose here is twofold:

1) To confirm that trading a Deathball does not close out the "Reap What You Sow" quest as expected (I don't know what's era vs. non-era).

2) To pose the question of whether "Let Sleeping Dogs Lie" is even implemented in the game; it's a non-repeatable quest, so we should be able to do it once after completing "Reap What You Sow."

Side Note: like Shoruto said, "Let Sleeping Dogs Lie" is not required for flagging "Making the Grade." I've done the "Making" quest successfully already.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
