### ISSUE TITLE
Issues entering Mog House post patch 2/12/19

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#956]
Entering my Mog House from Southern San d'Oria puts me in a Windurstian Rent-a-room. I am also unable to exit to other zones except the one I entered from despite completing the relevant quest.

**Comment by godmode** [comment]
I can confirm this happens on each zone entry in San d'Oria.

**Comment by panfunk** [comment]
same with Bastok MH from Mines entrance

**Comment by godmode** [comment]
I've been told that Jeuno is the same but Windurst is fine.

**Comment by mpinholster** [comment]
Was about to report this as well
