### ISSUE TITLE
Lord of Onzozo respawn timer

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#957]
On DSP LoO's respawn time is wrong.
    dsp.mob.phOnDespawn(mob,ID.mob.LORD_OF_ONZOZO_PH,4,math.random(75600,86400)); -- 18 to 24 hours
Problems:
1. The numbers for the hours in the comment are wrong. 75600 seconds is 21 hours, not 18.
2. It's not supposed to be 18 in the first place, it's supposed to be 16.
3. It seems as though it shouldn't even have a random respawn window, and it should be a flat 16 hours. So 57600 seconds.

**Comment by godmode** [comment]
This is not the case on Eden
