### ISSUE TITLE
Pet names not showing after update

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#960]
After the patch on 2/13/2019 my pet's name doesn't appear. 
![rph4cbb](https://user-images.githubusercontent.com/2160211/52750172-1c2def00-2fb1-11e9-97a7-2f906fbab479.png)

**Comment by jmcmorris** [comment]
What is your pet?

**Comment by montijin** [comment]
@jmcmorris Courier Carrie. Issue seems to be happening with other pets as well from what I'm hearing.

**Comment by dakumauler** [comment]
also carbuncle does not show up or any other summon pet
