### ISSUE TITLE
Desynth doesn't work

### ISSUE THREAD

**Issue by manbro1** [EdenServer/community#961]
Can't desynth raptor strap. I did a few weeks ago now I can't.

https://ffxiclopedia.fandom.com/wiki/Raptor_Strap

**Comment by CloudyDesarroi** [comment]
https://ffxiclopedia.fandom.com/wiki/Raptor_Strap?oldid=583943 - Edit from 2007
It looks like the desynthesis recipe wasn't added until later. Either that or nobody tested it until 2010ish: https://ffxiclopedia.fandom.com/wiki/Raptor_Strap?oldid=583943 - Edit from Jan, 2010

**Comment by manbro1** [comment]
Updated title.

Also, it was working in a previous patch, then it wasn't, If it's not era let me know!

**Comment by jmf9808** [comment]
When was the date you last remember being able to do this?
