### ISSUE TITLE
Knight Crabs not raging after 5 mins

### ISSUE THREAD

**Issue by Riphook** [EdenServer/community#965]
Knight Crab was held for 15 mins, my LS had to kill 3 round of knight crab pops, waiting for their LS members to show up for a chance to claim KA. Knight crabs should rage at 5 mins and also is holding KA like that allowed?

**Comment by gweivyth** [comment]
Not sure about the rage thing, but holding is allowed as long as you aren't holding stuff to grief players.  If you're waiting for backup it's fine.

**Comment by godmode** [comment]
I’d be careful with the wording there. The wording in rules is more or less “holding without intent or ability to kill” so waiting for backup without actively damaging it while it has competition may get someone in trouble.

**Comment by gweivyth** [comment]
Really?  If that's the case why not just put the rage back?  I remember having talked about this in the past and I thought we had come to the conclusion that as long as it wasn't blatantly griefing people that it was OK?  I ask because I've done this a few times without realizing I was doing anything wrong.

**Comment by Riphook** [comment]
Well then you have the discussion of whether not holding a NM from spawning is griefing every single player waiting for that player to kill the crab so the NM can spawn...let alone forcing people there to kill the crabs multiple times because one is being held...

**Comment by gweivyth** [comment]
I mean I don't think it's greifing if you intend to actually kill it and just need more firepower.

**Comment by Riphook** [comment]
So it's ok for just me to camp KA, claim a knight crab, and then tell the LS come out because I'm holding a knight crab and don't worry about not getting to attempt KA because I'm forcing him to not spawn since it's okay to make everyone wait?

**Comment by godmode** [comment]
It is not. I’m not sure what confusion is going on here. If you are actively killing the Knight Crab or King Arthro (meaning you are legitimately trying to kill it) and calling for backup that is fine. If you are holding it just for backup but not putting active damage on it then it is now.

Bug reports are not for discussion on anything except bugs. If either of you have questions please post a topic on the forums.

**Comment by Riphook** [comment]
Ok then the bug part got forgotten but I also posted in this topic that they aren't raging when they should be "Rages after a short amount of time. (approximately 5 to 10 minutes)". Sorry to make this a discussion, hopefully the rage timer get implemented to it's retail-like.

**Comment by godmode** [comment]
There should be a rage timer on them but they are low level and the gradually rage. What’s the longest you’ve seen one held?

**Comment by Riphook** [comment]
15 mins just a few days ago, it caused the knight crabs to spawn three times

**Comment by Lilswitche** [comment]
On retail, each Knight Crab would respawn after 5 mins if all were not killed.  The rage timer on them was 20 mins (which is more or less an eternity).

On Feb 17, 2019 11:49 AM, Riphook <notifications@github.com> wrote:

15 mins just a few days ago, it caused the knight crabs to spawn three times

**Comment by godmode** [comment]
They are set to rage but it's like all rage--it takes awhile to build up and since they are low level it takes long for it to really matter.
