### ISSUE TITLE
Regen II (and others?) not available at NPC in Mhaura

### ISSUE THREAD

**Issue by Timonthy** [EdenServer/community#966]
Hi! From my limited research on Regen II, it seems like it was once sold by a certain NPC in Mhaura (Pikini-Mikini) at one point, and later switched to be sold by a newly added NPC (Tya Padolih). However, Tya Padolih does not exist here, and Pikini-Mikini doesn't sell the scroll (amongst others). It seems like we are stuck in a limbo between the two. Thanks! Love you!

**Comment by godmode** [comment]
https://www.bg-wiki.com/index.php?title=Pikini-Mikini&oldid=44385
