### ISSUE TITLE
Imps stuck behind Heavy Iron Gate in Caedarva Mire at Staging Point

### ISSUE THREAD

**Issue by CloudyDesarroi** [EdenServer/community#970]
Seen some Heraldic Imps stay right inside staging point side of gate.

**Comment by yokhai** [comment]
Updated, all mobs that you zone through the gate are getting stuck. I just drug two chigoes through and they are there now as well. 

![vinsanity_2019 02 15_144308](https://user-images.githubusercontent.com/10634251/52880574-4e198f80-3130-11e9-8218-131a69771d5d.png)

**Comment by KnowOne134** [comment]
Part of the problem linked here. Will close this as when other issue is fixed. This will be as well
https://github.com/EdenServer/community/issues/460
