### ISSUE TITLE
Out of Era Corsair Rolls/Effects

### ISSUE THREAD

**Issue by roclm** [EdenServer/community#972]
I'm suspecting it might just be a DAT issue, but WHM, PLD, DRG, & PUP rolls were changed in retail during 2012.  This update also changed values for RDM, BST, BRD and DNC rolls as well.
http://forum.square-enix.com/ffxi/threads/19789-dev1069-Corsair-Job-Adjustments?p=264442#post264442

Currently on Eden, the corsair dice list the current retail abilities:
https://i.imgur.com/nmdObwY.png
She also sells the OOE DNC & SCH rolls:
https://i.imgur.com/BoQGrlk.png

Like I said, it's entirely possible these are just DAT issues but I thought it'd be best to mention it early. Especially considering I don't know any Corsairs high enough to test whether or not they're working era appropriate or not!

(And still on Eden installer v2.1)

**Comment by Jimmayus** [comment]
It is definitely a dat issue, this was specifically looked into during the coding stage

**Comment by KnowOne134** [comment]
Has been dat modded now
