### ISSUE TITLE
BLU Spell Learned When Shouldn't

### ISSUE THREAD

**Issue by DrfistMD** [EdenServer/community#973]
I fought a Giant Bee who used Pollen and then it eventually killed me.  I came back what might have been the same bee, killed it, it did not use Pollen during this 2nd fight, but I learned Pollen when it died.  When I died I went to Home Point and zoned several times inbetween coming back to fight this bee, I am not 100% certain it was the same bee, but I believe it was.

**Comment by Jimmayus** [comment]
This is expected behavior, it is literally the first interaction that appears in the megathread on blue gartr related to blue mage
