### ISSUE TITLE
Wild Oats Damage on BLU

### ISSUE THREAD

**Issue by DrfistMD** [EdenServer/community#975]
The damage damage on Wild Oats seems absurdly high.  I'm a level 7 BLU and blasting mobs for 50-100 damage.

![oats](https://user-images.githubusercontent.com/46073012/52833170-a2c5f780-30a9-11e9-81bf-0d9c8012ef32.PNG)

**Comment by Arlen90** [comment]
It is high damage, and may be an issue, I'm not sure. However, people should be aware Wild Oats is piercing dmg, and will be boosted on enemies such as birds. Same with Sprout Smack being blunt. It may be over tuned, but it should be taken into consideration. My wild oats was hitting 70ish on non-piercing weak EP--

**Comment by jmcmorris** [comment]
This needs more data to really know if it is overpowered or not. Low levels are weird.

**Comment by Spintaru** [comment]
Seeing as it's Piercing damage, and that was a "Bird" type, which are naturally weak to Piercing damage, I would say that it's normal. If you try it on say a crab, and it did that much damage, I would say it would need modifying.

**Comment by DrfistMD** [comment]
I don't have any other screenshots from when I was that level, but even against non-piercing weak mobs (Goblins) I was still doing 50-80 damage, which sub level 10 seems very high.  And I was able to safely solo T Goblins just with Oats very safely for a while.  The damage hasn't scaled wildly into high levels though, and it just seems very beefy when you first get it.

**Comment by 59blargedy** [comment]
assumed solved during pdif update
