### ISSUE TITLE
Chocobo rental prices.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#976]
Suspect that chocobo rental prices aren't resetting properly. They've been steadily rising since the patch - currently at 2.6k.

**Comment by gweivyth** [comment]
Noticed this earlier this morning at Teleport-Mea crystal, Chocobo cost me 1.5k per toon.  Feels bad man.

**Comment by ElectroNicMan83** [comment]
I think once ToAu got out in retail choco price went crazy. It is Era.

**Comment by KnowOne134** [comment]
this has been fixed some time ago
