### ISSUE TITLE
Lure of the Wildcat (All Nations)

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#979]
https://ffxiclopedia.fandom.com/wiki/Blue_Invitation_Card

After completing all 4 Lure of the Wildcat quests (Bastok, Sandoria, Windurst, Jeuno), you should be able to talk to Naja to receive the rewards in the link above.

**Comment by pksweets** [comment]
![leku_2019 02 16_000800](https://user-images.githubusercontent.com/27723566/52896584-10902300-317f-11e9-80a3-37f9b396a4af.png)

Perhaps related, maybe you need to get the proper cutscene from Rytaal and then return to Naja afterward before she'll accept the invitation cards? However, Rytaal doesn't offer the Assault explanation cutscene yet.

**Comment by bkesecker** [comment]
Rytaal Lua, if the player meets mission criteria, will play the default event, followed by the mission event.  This should be fixed.

**Comment by KnowOne134** [comment]
would need to see a snippet of the game text to make this a thing, no idea what the words spoken by naja are if I had them i could possibly find the cs

**Comment by KnowOne134** [comment]
Corrected 4/18/2022
