### ISSUE TITLE
Unable to unequip shield

### ISSUE THREAD

**Issue by Heretic667** [EdenServer/community#98]
Getting a "You must have a two-handed weapon equipped in the main weapon slot in order to equip a grip" error message.

Changed jobs as a workaround and moved shield to safe.

Edit: did a bit more testing, this error occurs when i have a shield in my inventory; I'm able to unequip shields when its stored in wardrobe.

**Comment by Wiggo32** [comment]
unable to reproduce this issue. i've equipped/unequipped shield / sword combo in every different way. If you could provide steps to reproduce this (what shield, what job, level, etc.) we could probably figure out what's causing it.

**Comment by Heretic667** [comment]
I'm unable to replicate now either.  I was level 10 rdm, standing in front of the Nomad Moogle in Selbina.  I was moving all my gear from inventory into wardrobe and received the error message when the only piece I had left to unequip was a Maple Shield.

**Comment by godmode** [comment]
Please reopen with additional details to reproduce if you encounter this again. Thanks for reporting.
