### ISSUE TITLE
Nashmau NPC 'Nabihwah' won't give sanction buff.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#980]
NPC is an Imperial Gate Guard and has the correct initial menu.  When you request sanction, he doesn't prompt you got the "Not Now/Regen/Refresh" options and instead goes right to doing the Sanction animation. Upon completion of the animation/menuing, you don't receive a Sanction buff on the icon tray.

**Comment by ababyduck** [comment]
This NPC will also cast sanction even if you haven't completed AU2 and are ineligible for Sanction. The player will not receive Sanction, but the eventid will play as if they did.
