### ISSUE TITLE
PUP Frame quests not showing correct items needed

### ISSUE THREAD

**Issue by chlorr** [EdenServer/community#981]
So the PUP frame quests at 10, 20 and 30 are showing the newer retail matierals, when he doesn't accept them, he takes the old ones.

**Comment by FariskaEden** [comment]
Can confirm he doesn't take the newer retail materials, for the Valoredge frame I traded in Tigerfangs with the other requested materials instead of Patas. If possible would he be able to accept either the newer or older requested materials?

**Comment by godmode** [comment]
We can try to update the params in the cutscene so it shows the old materials. Will look into it.

**Comment by jmcmorris** [comment]
Unfortunately we can't completely fix this but I do have a workaround in code review.

**Comment by KnowOne134** [comment]
Has been dat fixed now
