### ISSUE TITLE
??? for Cast Metal Plate in mount zhayolm not (re?)spawning

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#986]
Checked all the spawn points twice and we couldn't find it.
https://images-ext-2.discordapp.net/external/R93-tyiEN3PQT1TLhqCThkBvBWxHEx0Pbwy9It_F3ok/%3Fcb%3D20081113212528/https/vignette.wikia.nocookie.net/ffxi/images/6/6e/MountZhayolm.png/revision/latest

**Comment by icariumkupo** [comment]
@jmcmorris unable to obtain this key item. clicking ??? at H9 gave message "There is nothing out of the ordinary here"

**Comment by Arlen90** [comment]
Tried to get this KI today, I've checked the gate at both sides and found the ??? but I get the message of "There is a detached part here." - This message should be given if it's the correct ??? but I haven't checked the gate. I've checked both, multiple times and I have not zoned inbetween these checks.
