### ISSUE TITLE
Bhaflau Thickets map not purchaseable

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#989]
This map is not sold at the vendor

https://ffxiclopedia.fandom.com/wiki/Map_of_Bhaflau_Thickets

**Comment by panfunk** [comment]
I think instead of Bhaflau map, the Caedarva Mire map was added to this NPC, Caedarva map should be quested only in this era.

https://ffxiclopedia.fandom.com/wiki/Riyadahf?oldid=362948

**Comment by icariumkupo** [comment]
@jmcmorris this is still not purchase-able - maybe because I already bought the Caedarva map that was being sold in it's place. When attempting to buy, the menu just reloads.
