### ISSUE TITLE
Wardrobe #2 Missing

### ISSUE THREAD

**Issue by Shadowlesss** [EdenServer/community#996]
After Finishing Rank 6 Bastok i did not recive Wardrobe #2

**Comment by godmode** [comment]
I'm not sure what happened, I manually gave you wardrobe 2 for now. Please do not close this ticket so we can investigate later.

**Comment by Shadowlesss** [comment]
ok thank you 

IGN is shadowless

**Comment by Umarusuzy** [comment]
I'm currently rank 6 Bastok. Wardrobe 2 isn't functional on my character Umaruchan.

**Comment by BuffaloOnEden** [comment]
I accidentally posted on a closed page, but I have this problem too. My mog wardrobe #2 is not working, and I am rank 6 Bastok. Character name is Buffalo.

**Comment by mlandrum22** [comment]
Azmanz also did not get Wardrobe 2.

**Comment by godmode** [comment]
Are you guys all Bastok? Are you getting a message that says "You can now use Mod Wardrobe" or no message at all?

**Comment by mlandrum22** [comment]
(Azmanz) I am Bastok. I don't remember seeing that message around the time I saw "RANK 6". I can use Wardrobe 1, but it's 0/0 on Wardrobe 2

**Comment by Umarusuzy** [comment]
Umaruchan is Bastok rank 6 as well, I'm seeing a trend here =P

**Comment by BuffaloOnEden** [comment]
Didn't get any message about it, and I still don't have access. 0/0 it says

**Comment by BuffaloOnEden** [comment]
Still no wardrobe 2 on Buffalo

**Comment by saintfoley** [comment]
Another Bastoker missing wardrobe 2. IGN is **Foley**.

**Comment by Tolkage** [comment]
Another Bastokan, **Roon**, missing Wardrobe 2 after getting Rank 6.

**Comment by godmode** [comment]
I will be working on bugs next week for the next patch. Will be taking on this one at that time.

**Comment by Volkaru** [comment]
Glad to see this is getting fixed, thank you! If I completed rank 6 before this next update, will I get my wardrobe after patch? Or do you still need to manually give it to me? IGN is Volkaru. Also Bastok

**Comment by godmode** [comment]
It’ll happen during the patch

**Comment by CdoubleOkay** [comment]
Just wanted to let you know me, my alt, Zajin and his alt reached rank 6 today after the patch and did not receive our wardrobes

**Comment by godmode** [comment]
All Bastokian?

**Comment by CdoubleOkay** [comment]
Yessir, Cdoubleokay, Cdbleokay, Zajin, and Zarian

**Comment by Kopolt** [comment]
Hey godmode,
I am having the same problem. Bastok Rank 6 and no wardrobe 2. Can you please help me out?
IGN: Kopolt

**Comment by godmode** [comment]
You need to place a GM ticket. They have a temporary command to permit it until we get this debugged

**Comment by Mikokiko** [comment]
Just updating this, it still happen. 2 of us reached rank 6 bastok, MW2 did not unlock for us. I will place GM ticket as per previous entry.

**Comment by thorules** [comment]
Raised a GM ticket for this as it still happens
