### ISSUE TITLE
PUP pet SC

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#997]
I think the PUP pet is WSing too fast after player WS, so it can never SC :(

**Comment by Volkaru** [comment]
Also noticed this. Please fix this, being able to solo SC with our automaton is a big part of our damage in a party. Especially the higher we get.

**Comment by Nyoomy** [comment]
Had this happen aswell. Seems to be that the delay on the pet's WS is too short, or possibly that it just queues it's next action as the WS without taking into account the time needed for the SC to actually open.

**Comment by Volkaru** [comment]
I think it's worse than that. It seems like we can't SC with our auto's WS at all
