### ISSUE TITLE
Deactivate didn't reset Activate despite Automaton at 100%

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#999]
First time I've seen it happen so far. It may possibly be because of the way percentages are handled (I've noticed that you can hurt a mob at 100% and it will still display 100% HP. I don't know if it was like this on retail or not but sounds like something that could/should be fixed either way >_>;)

**Comment by Nyoomy** [comment]
I think on retail they changed it to be around 98%-100% that it'd reset as a QoL change.
I do think this is a case of being hit for 1-2 health's worth of damage and the game still showing 100%, as I've seen this quite often on mobs/myself, and had this happen to me a few times before.

**Comment by jmcmorris** [comment]
This will now check for 100% instead of the Automaton having exactly max HP
